### ISSUE TITLE
Make resizable-mode work

### ISSUE THREAD

**Issue by RobinWeymans** [runelite/runelite#10]
If you put the client in resizable mode and change the size of the screen, the ClientPanel does not change size. This is because the ClientPanel is not anchorred to the ClientUI's borders because it uses a FlowLayout.

I tried changing the code to:
```
                container = new JPanel();
                container.setLayout(new BorderLayout(0, 0));

//		container.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));

		panel = new ClientPanel();
		container.add(panel, BorderLayout.LINE_START);

		navigationPanel = new NavigationPanel();
		container.add(navigationPanel, BorderLayout.LINE_END);

		add(container);
```

If you change the height of the client now, when its in resizable mode, the client actually gets bigger. The NavigationPanel should have a max width, because with this solution, if you change the width, only the NavigationPanel gets wider. Im not sure yet how to solve that, but i'll post my answer when i find out.

**Comment by KronosDesign** [comment]
I found a temporary fix to this, but it breaks the side bar menu's (not that theres anything inportant there yet)

Just change the ClientPanel layout to use BorderLayout.CENTER
`container = new JPanel();
container.setLayout(new BorderLayout(0, 0));

panel = new ClientPanel();
container.add(panel, BorderLayout.CENTER);

navigationPanel = new NavigationPanel();
container.add(navigationPanel, BorderLayout.EAST);`

**Comment by KronosDesign** [comment]
I've made a pull request with some small UI changes that will fix this issue.
In addition to the code above the only thing left was to add the NavigationPanel  and PluginsPanel to their own navContainer that was set to BorderLayout.EAST

**Comment by RobinWeymans** [comment]
Yup that solves it! Two little things. Everytime you resize the screen the client flickers (because the size/location gets updated?). I just removed all the code from componentResized() and that solves it for me. Resizing the client is smooth now.

Another thing is the expand method. This is the code i have:
```
if (!expanded)
{
	navigationContainer.add(pluginPanel, BorderLayout.LINE_END);
	this.setSize(this.getWidth() + PluginPanel.PANEL_WIDTH, this.getHeight());
	expanded = true;
}
else
{
	navigationContainer.remove(pluginPanel);
	this.setSize(this.getWidth() - PluginPanel.PANEL_WIDTH, this.getHeight());
	expanded = false;
}
```
It does the same thing as your code, but its less complex.

Also, you guys seem to like revalidating components. That's not necessary here.

**Comment by RobinWeymans** [comment]
Also, if you resize the client, the applet itself shifts down for a second. Any idea what might be causing this?

**Comment by Adam-** [comment]
Should work now, see #16.
