### ISSUE TITLE
Hard Clue: Dig locater wrong tile

### ISSUE THREAD

**Issue by MatthijsvandenBosch** [runelite/runelite#10005]
![image](https://user-images.githubusercontent.com/2892841/66350947-dcab7d00-e95c-11e9-9ae4-6e495a638ff6.png)

**Comment by MatthijsvandenBosch** [comment]
In yanille south east, it should be the blue marked tile.

**Comment by Alexsuperfly** [comment]
the current tile is correct

**Comment by Nightfirecat** [comment]
This was added some time ago in #3338, because it is a more optimal way to complete this clue than walking around the building.
