### ISSUE TITLE
Menu entry swaps for clan chats

### ISSUE THREAD

**Issue by xtsov** [runelite/runelite#10000]
Having a rank in clan chats and the ability to kick can be problematic due to left click option being kick user. This could cause accidental kicks from missclicking on people in the clan chat.

Perhaps a menu entry swap for clan chats can be made to move the kick user option to the bottom of the right click menu and prioritizing hop-to option instead

**Comment by Nightfirecat** [comment]
The right-click menu is opened by default on left click, and that behavior is included in the vanilla client, so this shouldn't be an issue.
