### ISSUE TITLE
Add Opacity Value Customization for Chat Tab

### ISSUE THREAD

**Issue by PimmoSocks** [runelite/runelite#10015]
It would be really nice to be able to darken the chatbox's opacity in order to better see a wider range of custom chat colors.

**Comment by MMagicala** [comment]
Can we still implement this?

**Comment by Alexsuperfly** [comment]
pretty sure there is a plugin in the hub that does exactly this

**Comment by Trevor159** [comment]
https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub for information on how to use the plugin-hub
