### ISSUE TITLE
Suggestion: Herb farming hitboxes

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#10017]
Look on a herb herb farming patch, it is 2x2 tiles. However, if you hover your mouse cursor, you can see that the inspect option is only showing around the middle of the patch. Similarly, and more importantly, you also need to click close to the middle of the patch when you are applying compost. I think it would be nice if I could have highlighted the area where I need to click in order to add the compost, similar to agility hitboxes. 

I think there is a similar problem for bushes, cacti and flower patches.

**Comment by sadegr** [comment]
Can the [Object Markers](https://github.com/runelite/runelite/wiki/Object-Markers) plugin be used for this? At least for patches with something growing in it, maybe not for bare patches.

**Comment by dekvall** [comment]
This can indeed be done with object indicators, so i suggest using that. 
Bare:
![mark_empty_patch](https://user-images.githubusercontent.com/25151927/66496759-b18b6f80-eabb-11e9-81b1-d419ded64927.png)

Planted:
![mark_plated_patch](https://user-images.githubusercontent.com/25151927/66496766-b3edc980-eabb-11e9-82d0-4784e410f380.png)
