### ISSUE TITLE
Toggleable run hotkey

### ISSUE THREAD

**Issue by s-osborne** [runelite/runelite#10028]
**Is your feature request related to a problem? Please describe.**
There are some areas, usually in PvM, where it is beneficial to walk as well as run. Whilst there is the default option to press CTRL + Click to run to the location, nothing exists to do the opposite and make you walk. 

**Describe the solution you'd like**
A Toggleable run hotkey. This would likely just be the default walking but on hotkey press it would emulate holding the CTRL key, and show an overlay on top of or around the run energy orb.

**Describe alternatives you've considered**
Whilst I could manually hold the CTRL key and then release when I wished to walk, or use sticky keys, it's a frustrating workaround.

**Comment by Hydrox6** [comment]
This was added by Jagex alongside Deadman Reborn as an undocumented change (25/08/21)
