### ISSUE TITLE
Add Player Kill value in chat

### ISSUE THREAD

**Issue by pbs1234** [runelite/runelite#10034]
Would like to request a simple feature that would enable you to see the GP value of the player kill as shown in lootracker. So defeated player xx value xx. 

This  way you do not have to have lootracker open all the time ( world switcher ) and see how much ur last kill is worth very quickly.

I'v seen this on some other clients its really nice feature.

**Comment by Nightfirecat** [comment]
Is there a specific format that you've seen this message in? Ex. "You've killed *Zezima* for 73.5k loot."

**Comment by pbs1234** [comment]
> Is there a specific format that you've seen this message in, or like to see it if it's added to RuneLite? Ex. "You've killed _Zezima_ for 73.5k loot."

Format is not too important, just regular message as it is just added loot value at the end is fine. So ur example would be completly fine.
