### ISSUE TITLE
Error switching monitors with a maximized client.

### ISSUE THREAD

**Issue by markmjb** [runelite/runelite#10037]
Hi Runelite Devs,
I have a dual monitor setup: 
- 1280 by 1080 monitor.  (the "small" monitor)
- 2560 by 1440 monitor.  (the "big" monitor)
I use Windows key + Shift+ directional keys to move the active window to the other monitor. The runelite client bugs out when you do this while maximizing the client. 

2 noticeable behaviours:
1. If you switch a maximized client from the small monitor to the big monitor, it tries to fit the runelite client in the top left corner. There are more pixels on the big monitor, so this does fit.
2. When you switch the maximized client from the big to the small monitor, it fills the small monitor but tries to fit the big monitor resolution on screen, which stretches the client halfway the big monitor.
In **both** instances the client becomes unresponsive to dragging or resizing the client with a mouse , only fixable by using the buttons of minimize/restore. 
Seems like the client isn't maximizing, just trying to resize with the same amount of pixels of the screen. 

Addendum: 
Seems like windows key + left or right to snap the client to that part of the screen isn't supported either, was that intentional?

Using the 64bit Windows Runelite client. Had some non-related lagg earlier, so the client and it's cache is 2 days old.

**Comment by raiyni** [comment]
You have to make the larger resolution monitor your `Main` monitor in windows settings. You can also try turning off `Custom Chrome` in Runelite setttings to see if that fixes your freezing.

From the last time I investigated this, it's a Java bug--either in Substance or the JVM. It's a similar to https://github.com/runelite/runelite/issues/7638 and https://github.com/runelite/runelite/issues/4778 I think.

**Comment by markmjb** [comment]
@raiyni  The larger monitor is the Main monitor. Thanks for the custom chrome idea, that at least allows you to drag the client to where you want it, although you are still unable to resize the client until you have moved it again. 
Didn't realise Jframe was this dumb, guess a lot of people have issues with it.

**Comment by abextm** [comment]
Duplicate #5153
