### ISSUE TITLE
Loot Tracker Saving without 30day / 1000 drop restriction

### ISSUE THREAD

**Issue by DisneyManBro** [runelite/runelite#10041]
**Is your feature request related to a problem? Please describe.**
(I am using a runelite account to use the cloud) I got problems a few days ago with the loot tracker removing kills due to the maximum amount of drops restriction., I got frustrated about it because I wanted to make a "huge" loot tab (in the tracker, longer then 30 days) of my drops to see what I made and to resee my rare uniques.

**Describe the solution you'd like**
Removing the 30 day and 1000 drops restriction.

**Describe alternatives you've considered**
Making a local (automatic) save when closing the client that hasn't the 30 day and 1000 drops restriction. 

**Additional context**
If the alternative passes a way to import it to another pc would be great!
I know that you can export your last 30days but you can't import/merge it from so far I know.

**Comment by abextm** [comment]
We can't easily make the client show any more data because swing is too slow to handle that many components. You can see the last 30 days of data on runelite.net, and if you to keep older data you can download it and view it locally in the json
