### ISSUE TITLE
GPU plugin freezing client and now unstable frame drops.

### ISSUE THREAD

**Issue by gypsyvoiidz** [runelite/runelite#10043]
Hi there,
Runelite was running amazingly and about 2 weeks ago the GPU plugin started freezing my client. I  attempted to fix it via  disabling Hardware Acceleration (https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration), reinstalling Runelite, optimizing when running Runelite and reverting/updating drivers. None of these options worked. So I didn't worry about it and kept playing with GPU off.  

Today, the FPS has dropped and is constantly fluctuating randomly between 30 and 45 FPS. I've tried the previous options and changing core affinity but it has not fixed the drop. Is anyone else having this issue and is there a way to fix it ? 

If you need any other details such as logs, please let me know. 
Thanks!

Environment:
LAPTOP
 OS: Windows
RuneLite version: 1.5.35
CPU: i7-9750H
GPU: RTX 2060
RAM: 16GB DDR4 (Dual 8GB)

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest release of RuneLite or join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.
