### ISSUE TITLE
Using discords "go live" feature crashes runelite

### ISSUE THREAD

**Issue by Frutsalad** [runelite/runelite#10044]
the GPU plugin is OFF, i dont know how to fix

**Comment by Alexsuperfly** [comment]
turn off sharing audio

**Comment by Frutsalad** [comment]
How do i do that i see that setting on RL

**Comment by Alexsuperfly** [comment]
its a discord thing afaik, you should join our discord support channel for things like this, its much easier to handle there.

**Comment by Frutsalad** [comment]
alright, do you know where the setting is? I cant find it

**Comment by Nightfirecat** [comment]
See the ["Sound Hook/Sound Share" section of this article](https://support.discordapp.com/hc/en-us/articles/115000982752-Screen-sharing-Video-Calls).
