### ISSUE TITLE
Swap "Attack" with "Walk here" in PvP Safe Zones

### ISSUE THREAD

**Issue by nateprat** [runelite/runelite#10064]
**Is your feature request related to a problem? Please describe.**
Attack option first priority in safe zones in PvP

**Describe the solution you'd like**
Swap "Attack" with "Walk here" in PvP safe zones

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by dekvall** [comment]
This falls under `Removes or deprioritises attack, cast (or similar) options from the minimenu in any scenario` which is behaviour explicitly [rejected by Jagex](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1).
