### ISSUE TITLE
An addon to the runecrafting plugin that tells you when your RC pouch degrades.

### ISSUE THREAD

**Issue by CaraPis** [runelite/runelite#1007]
I was wondering if there could be an addition to the runecrafting plugin that tells you when your RC pouch is going to degrade the next time you put rune essence in it? It'd be very helpful for lava rcing.

Kind regards, Cara

**Comment by Gamer1120** [comment]
I would also like a notification when it has degraded. Not sure whether that should be a new issue.

**Comment by deathbeam** [comment]
Probably yeah

**Comment by null-zero** [comment]
Currently theres a notif when it decays, any chance to get a notif warning that the next use it will decay?

**Comment by Nightfirecat** [comment]
It looks like [this hub plugin achieves this](https://runelite.net/plugin-hub/show/rc-pouch-usage)
