### ISSUE TITLE
Press enter to chat and WASD Camera controls

### ISSUE THREAD

**Issue by Ragefit** [runelite/runelite#1008]

**Comment by CaraPis** [comment]
Remapping F-keys to 1,2,3,... would also be a nice addition to this

**Comment by deathbeam** [comment]
I feel like remapping f-keys should be job of like AHK or w/e keyboard daemon you use.

**Comment by CaraPis** [comment]
well, what's the difference, i can now also remap camera controls with WASD?

**Comment by deathbeam** [comment]
Yeah you can

**Comment by ChaoticConundrum** [comment]
I don't know if we'd want generic remapping inside runelite. Camera controls are a special case because they require interaction with the game. For other keybindings, every OS has a tool to remap keys for one application/window.

**Comment by Mamboosun** [comment]
Is this a hard thing to create?

**Comment by Adam-** [comment]
Added in #4874
