### ISSUE TITLE
Chat between Runelite Clients for Muted Players

### ISSUE THREAD

**Issue by Onyx349** [runelite/runelite#10086]
Accounts that are muted currently have no way to talk to each in-game. The best part of playing OSRS is playing with friends and when you can't talk to them it takes the life out of a really enjoyable game!

When you private message someone who is also using the Runelite client, it will send a duplicate message through the Runelite client. This will show like a Private Message. This feature should only be used if you are Muted and should be turned OFF by Default (Otherwise people will be sending 2 messages at the same time) and can toggle it ON/OFF.

Alternatively, a separate chat window on the Runelite Client itself (Like World Seeker / Skills Calculator etc) where you can invite friends. 

Would also like to see this integrated for Clan Chat too!

On behalf of all Permanently Muted players, thank you for reading this and please help make this game even more enjoyable than you already have!

**Comment by critzd** [comment]
This seems fairly open to abuse by third parties, and wouldn't this be essentially attempting to circumvent Jagex enforcement of chat for Runescape?

**Comment by abextm** [comment]
This is not something we want to have to moderate, and targeting this at people who have already proven themselves to cause issues doesn't help.

**Comment by SheeranJL** [comment]
support. anyone who disapproves with muted people being able to circumvent chat is a cuck

**Comment by SheeranJL** [comment]
> This is not something we want to have to moderate, and targeting this at people who have already proven themselves to cause issues doesn't help.



> This seems fairly open to abuse by third parties, and wouldn't this be essentially attempting to circumvent Jagex enforcement of chat for Runescape?

cope
