### ISSUE TITLE
Enhance VarbitChanged Event

### ISSUE THREAD

**Issue by Infinitay** [runelite/runelite#1009]
I noticed that unlike many other events, VarbitChanged doesn't really give you much information. The only thing that happens is the event is thrown. 

There's no varbit id that changed, the value it changed from/to, etc. Would it be possible to change the event so it does contain said-values?

Currently I am trying to see if I can do it myself, but to be honest, I'm not really sure what I'd be doing as I'm not too good with the backend/how the game works and what not

**Comment by raiyni** [comment]
This can be closed by https://github.com/runelite/runelite/commit/b6ab78b5012bc1ff1b57eb3534bbd49e08423f01 ?

**Comment by Nightfirecat** [comment]
That only really addresses varp changes, not varbits in general

**Comment by raiyni** [comment]
added in 668d99dfef72c900b1c6c7a5ab121863ddb06252
