### ISSUE TITLE
PVP KD counter is no longer moveable

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#10093]
It was removed in this commit: https://github.com/runelite/runelite/commit/a0eedbe39f1e402ec4f4eef3b3ccd1f007ce9481 because it for some reason broke and abex wasnt able to make it properly movable again.

**Comment by dekvall** [comment]
It seems to work as intended for me on a f2p world.
![moving_kd](https://user-images.githubusercontent.com/25151927/67106618-3ddc1780-f1cb-11e9-9b59-7dbd78932850.gif)

**Comment by deathbeam** [comment]
Well then we should probably add it back, good for first contribution issue? :d
