### ISSUE TITLE
Attack Indicators Plugin Displays Removed Styles

### ISSUE THREAD

**Issue by RyleeT** [runelite/runelite#1010]
Upon hopping worlds, it seems that that the "Attack Indicators" plugin fails to remove blocked attack styles. Once the unwanted combat styles are present, they do not disappear until the player's weapon is changed, the plugin is reset, or client is restarted.

Edit: Setting a spell to autocast also breaks the plugin. To restore functionality, one of the procedures noted above must be followed.

**Comment by devLotto** [comment]
Is this fixed as of #639 ?

**Comment by Adam-** [comment]
Yes, this is fixed.
