### ISSUE TITLE
Runelite resets all plugin preferences, notes and timers whenever launched

### ISSUE THREAD

**Issue by ItsCorrupt** [runelite/runelite#10118]
When I launched RuneLite today, all of my plugin preferences, farming timers, and notes were completely gone. 

To test it, I activated a few plugins again, wrote something in my notes, logged out, restarted RuneLite, and they were all gone once again. This has never been a problem in the past.

**Comment by Elpan1** [comment]
Have you made any radical changes somewhere on your computer or with the client recently?

**Comment by ItsCorrupt** [comment]
Nope, no changes of any sort.

**Comment by winterdaze** [comment]
Are you playing on multiple clients by chance? I'm pretty sure RL will save the last client closed, so if you made changes on client A, closed A, then closed client B, it would save the settings of client B (this has happened to me having alt/main clients open). If not, I don't know what's causing your issue

**Comment by ItsCorrupt** [comment]
Sadly no, I’ve only ever played on one RuneLite client at a time. This problem has also yet to happen again since the day after the original post.

**Comment by Hydrox6** [comment]
This is now extremely stale, and was a better fit for Discord support either way
