### ISSUE TITLE
Value of items gained from Miscellania kingdom

### ISSUE THREAD

**Issue by daMatt1** [runelite/runelite#10129]
**Is your feature request related to a problem? No.

A clear and concise description of what the problem is. 
I'd really like to be given the value of the items obtained from miscellania. And, if possible, profit gained based off of what was spent. 

**Describe the solution you'd like**
I just want a notification in the "game" tab regarding the value.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Rough-Draft** [comment]
If possible an in game calculator for assisting in choosing where to put workers.

**Comment by daMatt1** [comment]
That's an excellent idea, Rough-draft. I'm not sure how difficult that would be

**Comment by Adam-** [comment]
Getting the value of the items gained is already tracked in the loot tracker.
