### ISSUE TITLE
Keyboard shortcut for screenshot

### ISSUE THREAD

**Issue by Tekonaz** [runelite/runelite#1013]
While having a button to screenshot, also assign a keyboard shortcut for example print screen (this is to include other stuff like hold over xp while taking screenshot etc)

**Comment by deathbeam** [comment]
I don't think stealing system's PrintScreen and using it from doing screenshot of RuneLite instead is good idea, but some different shortcut might work.

**Comment by Hxnry** [comment]
I'm not entirely sure what it is you're asking for, but in windows, you can achieve a cropped screenshot of your current window by holding down the alt key while pressing print screen.

**Comment by Tekonaz** [comment]
@Hxnry I'm talking about the RuneLite screenshot feature where it shows the date, so if you set a keyboard shortcut for that feature like insert (what OSBuddy use) to take a screenshot of the client. Basically what the screenshot button does but a keyboard shortcut instead.

**Comment by CasvanDongen** [comment]
This would be an interesting feature, would it be better to let the user choose a specific shortcut on enabling this option? Or would you like to see a default shortcut? If yes, what would the "best" shortcut be that isn't default to Windows, Mac and preferably Gnome / Unity.

**Comment by Tekonaz** [comment]
I think the best would be to let the user be able to choose the specific shortcut, otherwise something as ctrl + s would be reasonable.

**Comment by Nightfirecat** [comment]
I'm in favor of a user-defined shortcut and/or F11 as default. (as F11 is a default in many other programs)

**Comment by Adam-** [comment]
Fixed in #2044
