### ISSUE TITLE
Advanced Key Remapping

### ISSUE THREAD

**Issue by alexander-bachmann** [runelite/runelite#10137]
**Is your feature request related to a problem? Please describe.**

I recently switched to Linux from Windows and am really struggling with finding an alternative to AHK for key remapping on Linux, specifically for remapping mouse button clicks to the keyboard (left click and middle hold). 

My ideal mappings
ASDF: F1, F2, F3, F4 (which RuneLite already can do)
E and R: left mouse clicks 
Left Shift: middle mouse hold aka faster camera rotation

**Describe the solution you'd like**
I would like to be able to remap a key to the mouse actions within the RuneLite client

**Describe alternatives you've considered**
I have considered buying a new keyboard with remapping profiles but that seems excessive to me

**Additional context**
The reasoning for this request is because after even a couple hours of clicking my finger tips start to seriously hurt so this solution lets me distribute the clicking across 3 fingers instead of 1.

Thank you for reading

**Comment by deathbeam** [comment]
https://github.com/baskerville/sxhkd

And regardless, that is not the point of key remapping. Everything that is in key remapping atm is related to the game, your inconvenience with Linux isn't.
