### ISSUE TITLE
Kitten timer for growing cats

### ISSUE THREAD

**Issue by Wingspan005** [runelite/runelite#10130]
**Is your feature request related to a problem? Please describe.**
I'm always
frustrated when my  cat runs away from me trying to train him while skilling/doing other things. 

**Describe the solution you'd like**
A timer for all the types of ways you can feed/play/interact with your kitten and the amount of time before the kitten will need more attention. All info for timing I found from the wiki page about kittens in osrs. 

**Describe alternatives you've considered**
A timer for only the best possible way to train a kitten into a cat. aka a ball of wool (51 minutes)

**Additional context**
I'm not good with coding and I thought it would help a lot of people while not being too strong.

**Comment by BlackFalcons** [comment]
This seems relevant, would like to see this in Runelite.

**Comment by Hydrox6** [comment]
You already get chat messages when your cat is needing attention or food, which can be made to notify you with `Chat Notifications`

**Comment by Nightfirecat** [comment]
Duplicate of #3815
