### ISSUE TITLE
Colour selector bugged with green panel (Tile indicator, NPC indicator)

### ISSUE THREAD

**Issue by Ashe** [runelite/runelite#10138]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When I open the colour panel, I can't see any colours. This screenshot shows it all. It does still function but I can't see what I'm clicking.

**To Reproduce**
1.Click on `Tile Indicators`
2. Click on one of the colour boxes, like the `current destination` one

**Expected behavior**
I expect to see a big colour pallette that allows me to choose a colour 

**Screenshots**
![image](https://user-images.githubusercontent.com/8940077/67602443-80bf6180-f76e-11e9-83fc-62d445b4e41d.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - RuneLite version: 1.5.36
 - Launcher version: 2.0.0

**Comment by raiyni** [comment]
What Window Manager are you using?

**Comment by Ashe** [comment]
> What Window Manager are you using?

BSPWM, a tiling window manager. I also forgot to mention that people in the discord told me to turn off hardware acceleration, and that didn't do anything. I verified that it was turned off as this appeared in the terminal: `2019-10-25 21:19:58 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to OFF`

**Comment by abextm** [comment]
Try setting this env var `_JAVA_AWT_WM_NONREPARENTING=1`

**Comment by Ashe** [comment]
Yeah fixed by exporting `export _JAVA_AWT_WM_NONREPARENTING=1`. Thanks everyone.
