### ISSUE TITLE
Remember Password

### ISSUE THREAD

**Issue by Aholicknight** [runelite/runelite#10145]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
Regular OSRS allows you to save the email/username for your account. Another great addiction to this would be a plugin to save your password if you want.
**Describe alternatives you've considered**
Save the password in notes so you can easily access it.

**Additional context**
None.

**Comment by Hydrox6** [comment]
Storing passwords in the client is a really really bad idea. If you want quick logging in, the `Login Screen` plugin already allows you to paste in passwords, allowing easy use of a password manager such as KeePass.

**Comment by coreybruce** [comment]
Would be fine if you did two step than either way it doesn't matter

**Comment by binury** [comment]
> Storing passwords in the client is a really really bad idea.

This would be the same behavior as the official mobile client

**Comment by binury** [comment]
> Storing passwords in the client is a really really bad idea

This feature would mirror the current behavior of the official mobile client. Could salt the password locally.... or trust the player to secure their own PC.

**Comment by Adam-** [comment]
> > Storing passwords in the client is a really really bad idea
> 
> This feature would mirror the current behavior of the official mobile client. Could salt the password locally.... or trust the player to secure their own PC.

The official mobile client doesn't store passwords

**Comment by Jin-Jiyunsun** [comment]
theres a plugin on the hub, "KeePassXC", it auto fills for you and if setup correctly means you only need to put the master password into keepassxc once per startup on your pc

**Comment by coreybruce** [comment]
In Linux for example it could be stored in your keyring and remembered that way user wide

**Comment by Aholicknight** [comment]
> Storing passwords in the client is a really really bad idea

You can encrypt the password so they are not stored in cleartext

**Comment by Jin-Jiyunsun** [comment]
99.99% chance this isn't going to happen. Use the keepass plugin if you want something close to remembering passwords, great thing about the plugin in you can have multiple accounts saved into keepass and clicking on them in the plugins sidebar will fill username and password for you

**Comment by coreybruce** [comment]
@Hydrox6 not sure why you thumbs down my comment, it's not like anyone else is going to know someone else's password and even if they did they wouldn't have access to it without 2step and they could change their password ontop of that using a Password manager like Bitwarden to generate a decent password for example making it a non issue. Not to mention if they client did save the password or with Mac/Linux or even WIndows if you used a password manager like Linux and Mac has built in it's not like the password wouldn't be encrypted and not stored as plain text, that would be stupid.

**Comment by Hydrox6** [comment]
No matter how it's done, *we* would be responsible for storing the passwords. Sure, Mac and Linux have built-in keyrings, but Windows does not, at least not universally (and even Linux kinda doesn't). Given that the vast majority of users are on Windows, requiring users to download entirely external software just to use a feature in the client is just silly. 

If a user already has a "decent password" with Bitwarden, then they should just use the hub plugin for it. Same with any password manager that there's a hub plugin for. Either way, it's not getting any further than an optional integration with an optional application, and it's definitely not getting into core.

**Comment by coreybruce** [comment]
Well sadly for Windows unless you install a password manager than it won't be able to but on Linux it's a no brainer to impliment

**Comment by Espionage724** [comment]
Password managers (including KeePassXC and other KeePass variants) may not be able to auto-type on Linux when using Wayland. I just ran into this on Fedora 36 and was looking for another auto-login solution, and landed here.

I can switch to Xorg, but I would prefer to see some integration with keyrings or even Hello or Credential Manager on Windows.
