### ISSUE TITLE
World Map: Split "Show quest names and status" option into two separate options

### ISSUE THREAD

**Issue by makingcomment** [runelite/runelite#10144]
Less selfish reason: Having this as single option is inconsistent with having split options for each of agility shortcuts and rare trees.
More selfish reason: I like the extra information provided by the quest names tooltips, but I'm not a fan of the quest status icons on the world map. Every other icon on the world map is circular, while the quest status icons aren't, which to me makes them a bit of an eyesore. And even beyond that, I like the default world map icons and don't like having to change them to gain the tooltips.

**Describe the solution you'd like**
Two options within the world map plugin: A "Show quest names" option to control the tooltip, and a "Show quest status" option to control the quest status icons.

**Describe alternatives you've considered**
- Change the quest status icons to be more in line with the all of the other icons' circular aesthetic (maybe do this regardless?).
- ~Move the quest status into the quest name tooltip.~ Upon further inspection, quest status information information is already in the tooltip, so this option would just be removing the quest status icons.

**Comment by Darkkgreen** [comment]
I'll take a look into it later

**Comment by Darkkgreen** [comment]
Would you take a look inside the pull request, please?

**Comment by makingcomment** [comment]
Closed by game update
