### ISSUE TITLE
Entity Hider: Hide NPCs and Players by level

### ISSUE THREAD

**Issue by Whalehalla** [runelite/runelite#10140]
The entity hider is generally a great feature. However, for the PVP community it could still be made much better, and I'm sure there are cases this would also help PVMers:

Desire:
-  Ability to choose the levels of players and NPCs (e.g. within a certain range) which are hidden by the entity hider.

Example uses:
- PVP; don't have to search crowded areas for players within attackable range
- Slayer; can hide death spawns at Nechryaels 
- Probably many more

**Comment by Hydrox6** [comment]
This would come under the `Level-based PvP player indicators` in the [rejected list](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features), due to being easily abusable
