### ISSUE TITLE
chat command to share CoX rotation

### ISSUE THREAD

**Issue by paularcoleo** [runelite/runelite#10146]
I feel like it could be a nice qol improvement to have a chat command, something like `!roto` or `!rotation` to announce the rotation of the current Chambers of Xeric instance in chat, so if scouting in multiple worlds, rotation could be easily shared. output could be something like

`Guardians - Shamans - Crabs - Muttadile - Tightrope` and maybe include world?

**Comment by Adam-** [comment]
We have support for sending layouts to parties currently, though I think not many people use it. I suppose we could do this in addition..

**Comment by SieBrum** [comment]
I'd love this. I myself dislike using the discord plugin to raids with others and rather use a command like !rotation to broadcast it in my clanchat or private message

**Comment by Adam-** [comment]
This is basically #7736 again but we closed that due to the party raid thing.

**Comment by Adam-** [comment]
added in #10155
