### ISSUE TITLE
Suggestion - menu entry swapper: Eat, Clean

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#10159]
I would like to be able to use the menu entry swapper to hide the default "Eat" option for food. Example usage: when making pineapple pizza, you don't want do accidentally eat neither the pineapplie ring nor the Plain pizza. Similarly, I would like to be able to hide the default "Clean" option for grimmy herbs. I prefer to have them banked uncleaned. Both these swaps should be disabled by the plugin by default, naturally.

**Comment by deathbeam** [comment]
We already have shift-click configuration for stuff like this.
