### ISSUE TITLE
Change the size of infoboxes

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#1016]
Currently the infoboxes can take up quite some space in the user's screen, especially in fixed mode.

Proposed changes:
- Option to remove the spacing in between infoxboxes.
- Remove padding from infoboxes and make them 30x30 or even 28x28 by default

**Comment by Infinitay** [comment]
Hopefully with the overlay moving, if it's dynamic, it'd be wonderful to also size it dynamically, if that makes sense

**Comment by Kamielvf** [comment]
My hopes for when they're resizable is that you can resize them horizontally to limit the amount of infoboxes in a row etc.

**Comment by martinezjorge** [comment]
Hey guys, I'd be happy to work on this but can you give me some specific info boxes you would like to see modified?
