### ISSUE TITLE
Barrows Minimap Overlay Not Showing

### ISSUE THREAD

**Issue by sswetonic** [runelite/runelite#10167]
I don't see the barrows minimap overlay showing anymore. I have the barrows pulgin enabled and all the options enabled. I'm using the most current version of runelite. Normally there a map that shows which doors you can go through with green dots.

**Comment by raiyni** [comment]
This is intentional due to Jagex's updated 3rd party client statement.

https://runelite.net/blog/show/2019-10-30-1.5.37-Release/
