### ISSUE TITLE
Add the ability to hide or move the Godwars Killcount 

### ISSUE THREAD

**Issue by FoxyToaster** [runelite/runelite#10162]
Would it be possible to add the ability to hide or move the NPC killcount from the upper right? 

Thanks in advance!

**Comment by PERSS0N** [comment]
@deathbeam Any ideas on how to approach this? I thought God Wars had its own plugin, but the killcount overlay is in the vanilla client?

**Comment by deathbeam** [comment]
Check WidgetOverlay, it should be as simple as adding the godwards kc widget id there.
