### ISSUE TITLE
Disable left click remove placeholders

### ISSUE THREAD

**Issue by dion-perez** [runelite/runelite#10175]
We currently have the ability to disable left click bank equipment/inventory etc, which is really useful. But sometimes I click and remove my placeholders, which makes me almost want to cry when I see my lovely bank get ruined by a single click with no warning.

Can we please get an option similar to the "Disable left click bank inventory" and "Disable left click bank equipment", for something like "Disable left click placeholders"?

**Comment by Hydrox6** [comment]
Vanilla already does this: all placeholders open the menu on left click, and so does the `Release all placeholders` option

**Comment by dion-perez** [comment]
@Hydrox6 ahh, so is there no way that we can remove/disable that button to prevent misclicks?

**Comment by Hydrox6** [comment]
The `Release all` button is in a menu that isn't high traffic, and requires 2 misclicks to trigger. The chances of that happening enough to actually warrant intervention are so incredibly low.

**Comment by dion-perez** [comment]
Hmm, is it possible my bank layout is different to others? The release all placeholders is at the bottom of my bank next to deposit inventory/worn equipment. It's underneath the bank where if I'm doing things where skilling items are at the bottom for ease of access (MLM, Rc etc), if my mouse is off by a few pixels I can accidentally click this. 

All it takes in my case is one click and a close of the bank interface for all of my placeholders to be removed, which can be done very easily when I'm quickly banking things like essence, then pressing esc and teleporting before I've even realized that I misclicked.

**Comment by Hydrox6** [comment]
The padlock between the Quantity selectors and the Search icon just says whether items should leave placeholders; it doesn't remove them.

**Comment by dion-perez** [comment]
Oh for real? I don't know what I must've done when I misclicked that to get my bank ruined, but that's good to know. Thanks for the clarification man.
