### ISSUE TITLE
Login screen plugin - Password pastes double characters 

### ISSUE THREAD

**Issue by jolty1** [runelite/runelite#10173]
**Describe the bug**

Login screen plugin bug,

Pasting in **password** inputs double characters or something. Login pastes correctly

**To Reproduce**
1. Click in Password
2. CTRL-V password from clipboatd
3. See too many characters pasted..
4. Test pasting 1 character
5. Outputs 2 ?

**Expected behavior**
Paste correct characters.

**Environment (please complete the following information):**
 - OS: Windows 7 x64
 - RuneLite version: 1.5.38
 - Launcher version: 2.0.2

**Comment by jolty1** [comment]
I am able to paste with the plugin disabled, this fixes it oddly.

**Comment by Adam-** [comment]
This seems to be due to Jagex adding their own pasting mechanism to the password field now, so both take effect.

**Comment by Adam-** [comment]
I've removed ours in dde308f2e8c1908146570cc80234c7747325e39a
