### ISSUE TITLE
Music plugin's Mute Other's doesn't mute npc mining sounds.

### ISSUE THREAD

**Issue by TrevorMartz** [runelite/runelite#10176]
**Describe the bug**
The music plugins' Mute others' area sounds does not mute npc mining sounds in motherload mine. Probably happens elsewhere, I didn't check.

**To Reproduce**
1. Go to motherload mine
2. Find an npc mining dwarf. I was on the upper level.
3. With the plugin off, note that you can hear the dwarves mining.
4. Turn the Music plugin on with the Mute Others' area sounds on.
5. Note you can still hear the dwarves mining.

**Expected behavior**
The plugin should mute both players and npc mining sounds.

**Environment (please complete the following information):**
 - OS: Wndows 10
 - RuneLite version: 1.5.38
 - Launcher version: 1.6.0

**Comment by neeerp** [comment]
I'd imagine there might be situations where you would want to hear area sounds from NPCs but not players or vice versa... perhaps a separate option for NPC sounds might be suitable? I can take a shot at implementing that.
