### ISSUE TITLE
Client is crashing after login since update from yesterday.

### ISSUE THREAD

**Issue by rennard8** [runelite/runelite#10174]
Since the update of yesterday the client keeps crashing after login on Runescape.
I have tried uninstal then reinstall, i have tried the 32 version, i have the most recent version of Java, i tried moving in vanilla to Lumbridge and then try Runelite, i tried running the Jar file, i tried deleting several files to reupdate but nothing works for me.

Can someone help me?

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-crashing-on-login

**Comment by rennard8** [comment]
> https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-crashing-on-login

I tried everything which is listed on that page

**Comment by Hydrox6** [comment]
Issues like this are better addressed on the Discord, not in the issue tracker

**Comment by Hydrox6** [comment]
[Come join us there](https://discord.gg/mePCs8U)
