### ISSUE TITLE
Adjusting slayer counter for slaughter/expeditious bracelets

### ISSUE THREAD

**Issue by Romothy** [runelite/runelite#1017]
Given that you receive a chatbox message when either of these effects trigger, I assumed it'd be pretty easy to implement this to the slayer plugin.

Ty!

- Rom

**Comment by CasvanDongen** [comment]
I'll start working on it today, you'll see a pull request in an hour or so.

**Comment by Romothy** [comment]
Sounds awesome, thanks man! @CasvanDongen

**Comment by Adam-** [comment]
Added in #1033
