### ISSUE TITLE
Ground Item Color Bolding

### ISSUE THREAD

**Issue by fixgrounditemcolors** [runelite/runelite#10180]
**Problem:** **High** and **Insane** value price ranges within the Ground Items plugin have notable **Drop Shadow** effects for their text while **Low, Medium**, and **Highlighted** value price ranges do not.

![](https://puu.sh/EzmjP/50b47b2fb4.png)

**Suggestion:**
1. Make all value price ranges have drop shadow text for consistency sake.
2. Make a toggle-able option for value price ranges to have drop shadow text.

**Additional context**
I think it looks very odd and out of place. This is just a minor suggestion/fix.. :)

**Comment by Nightfirecat** [comment]
All of the text in that screenshot has the same type of drop shadow.

**Comment by fixgrounditemcolors** [comment]
You're right. It seems pastel colors made it seem less noticable.
