### ISSUE TITLE
Bank value plugin overflow

### ISSUE THREAD

**Issue by BegOsrs** [runelite/runelite#10182]
**Describe the bug**
Bank value plugin is overflowing when you have something like 3 twisted bows. That is, the result is over 2147m. This results in sometimes a negative result showing up as the bank value.
I believe the problem lies in these lines, as two integer values are multiplied and causing an integer positive overflow.

**To Reproduce**
Have the bank value plugin enabled.
Have more than 2147m worth of one item in the bank.

**Expected behavior**
The value of the bank shouldn't be overflowing.

**Screenshots**
![image](https://user-images.githubusercontent.com/17231890/68020488-8947f880-fc96-11e9-9fe6-598032febbbe.png)

**Environment**
 - OS: Ubuntu 18.04.3 LTS
 - RuneLite version: 1.5.38
 - Launcher version: 2.0.2

**Comment by Adam-** [comment]
fixed in ec0858548ff52986a0e84706472b85180df22ac1
