### ISSUE TITLE
Object Markers cannot be removed if the object changes

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#10188]
**To Reproduce**
1. Mark the Dense runestone at the Zeah essence mine
2. Deplete it
3. Try to Mark the Depleted runestone. The menu entry will say `Unmark`, and clicking that option causes a second mark to be applied.
4. Once the Runestone recharges, you'll be able to remove the mark

**Comment by Adam-** [comment]
fixed in 2c5f52e57c15a57db4f91901042955a3640597ac
