### ISSUE TITLE
Multi-Way Combat tile highlighter

### ISSUE THREAD

**Issue by Klixiso** [runelite/runelite#10203]
It can be difficult to memorize each and every tile of the game that is designated as multi

If there could be a plugin that visually shows what tiles are multi, that would solve this issue and would help less experienced players to stop falling for baits into multi from clans.

I've considered just looking into memorizing a map that shows all the places that are multi, but this seems unreasonable for the average person.

Apologies if this has already been requested or something, I didn't see anything about it in the rejected/rolled back features page.

**Comment by abextm** [comment]
This is prohibited https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1
