### ISSUE TITLE
Draynor's Tool Leprechaun Clue Scroll highlighting is ambigious

### ISSUE THREAD

**Issue by yanikore** [runelite/runelite#10216]
**Describe the bug**
For the clue scroll where you have to talk to the tool leprechaun at Draynor Maynor, all Tool Leprechauns are highlighted instead of just the correct one.

**To Reproduce**
Read the specific clue scroll hint to start the clue scroll widget and go to any tool leprechaun.

**Expected behavior**
Only the Tool Leprechaun at Draynor Maynor should be highlighted. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6956790/68376602-1ed90180-0149-11ea-8f33-21c5a901fa11.png)
![image](https://user-images.githubusercontent.com/6956790/68376628-2a2c2d00-0149-11ea-8639-2cc148c1a6a7.png)

**Comment by Hydrox6** [comment]
This is the same issue that #3164 has: the plugin currently highlights by name, not ID or location.
