### ISSUE TITLE
Launcher stuck on 0% - downloading bootstrap.

### ISSUE THREAD

**Issue by DamianWasilewski** [runelite/runelite#10214]
As stated in topic. When i try to run runeLite client it gets stuck on "downloading bootstrap", after some time it crashes. Logs says about connection timeout.

Everything was working perfectly untill now.

I already did put runelite to my firewall exceptions and reseting network connection.

Logs:
[launcher.log](https://github.com/runelite/runelite/files/3816757/launcher.log)

**Comment by Hydrox6** [comment]
Please join the Discord for support queries
