### ISSUE TITLE
amount traded

### ISSUE THREAD

**Issue by extreme4all** [runelite/runelite#10220]
Runelite doesn't track prices which makes finding accurate ge prices harder since osbuddy is dying

either runelite implements its own database or colab with osbuddy database

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

See the GE tracker section

**Comment by extreme4all** [comment]
@deathbeam thanks for responding with this source, did jagex ask for:
GE Tracker: There's no way to validate that any of the data coming from the client is legitimate, thus allowing for easy spoofing and price manipulation.
Hiscores for KCs, PBs, and more: Same as the GE Tracker, the data could easily be spoofed, rendering it useless
or is it just GE tracker policy?

**Comment by deathbeam** [comment]
KCs, PBs etc do not affect anyone so they are not important. But faked GE data would affect game economy, and I dont think we want to be responsible for it. There is also some more discussion about this here: https://github.com/runelite/runelite/issues/733 (and some other issues but I cant find any atm).
