### ISSUE TITLE
Manually reset Kourend Library known locations 

### ISSUE THREAD

**Issue by glowinghands** [runelite/runelite#10224]
Sometimes when the library resets, or when you log off or change worlds, or any number of things can cause the info in the plugin to no longer be accurate, I find myself just going blind until the plugin finally catches up.

It would be very beneficial to have a clear button to reset known locations, as if you were showing up for the first time in a while.

**Comment by Hydrox6** [comment]
In the sidebar, click on the Book icon. You'll find what you want there.
