### ISSUE TITLE
Music plugin: Add teleport sounds to the "other players' area sounds" filter

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#10248]
Judging by #10190 it will need some sort of special case since the source is `null` for teleport sounds.

**Comment by Nightfirecat** [comment]
I'm not sure I understand your request. Those would be covered under the "Mute environment area sounds" option which is added in the linked PR.

**Comment by ShaunDreclin** [comment]
They are covered by that but they aren't really "environment" sounds, they're caused by players.

**Comment by ErikHumphrey** [comment]
I disagree; it should be a third option.

**Comment by Adam-** [comment]
https://github.com/runelite/runelite/pull/10190#issuecomment-549096831 - this is the issue here, we basically can't fix it without building lists of sound ids.
