### ISSUE TITLE
Player Indicators for Skulled Players

### ISSUE THREAD

**Issue by eX-C0n** [runelite/runelite#10244]
**Is your feature request related to a problem? Please describe.**
No, but friendly people in the wilderness are typically not skulled, while non-friendly players typically are. As it stands, you can choose to highlight all Non-Clan Members, among other things, but to highlight only Skulled players would be an easy addition.

**Describe the solution you'd like**
A boolean for Highlighting Skulled players in Player Indicators.

**Describe alternatives you've considered**
Using my eyeballs to look at the Skull icon on screen, but to highlight *potentially* dangerous players in a chosen color would be very noticeable.

**Comment by Hydrox6** [comment]
This basically comes under the `PK/Skull Warnings` in the [Rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features) list

**Comment by eX-C0n** [comment]
under the "Not *currently* being considered" category.
