### ISSUE TITLE
Client crashes unexpectedly

### ISSUE THREAD

**Issue by spikin2** [runelite/runelite#10243]
**Describe the bug**
Client crashes without warning and no log is created in logs folder for the crash

**To Reproduce**
1. Load Client
2. Login
3. Walk around on RS for an undetermined period of time.
4. Client Terminates

**Expected behavior**
Client should not terminate randomly

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 64 Bit
 - RuneLite version: 1.5.39
 - Launcher version: NA

[client.log](https://github.com/runelite/runelite/files/3838049/client.log)

**Comment by Nightfirecat** [comment]
Do you have any `hs_err` files in your log directory? Your client log unfortunately does not show any information about this crash.

**Comment by spikin2** [comment]
No. I don’t have any error logs for this crash and that’s the weird part. I’m running barrows and it’s crashing me there.

**Comment by dekvall** [comment]
I am closing this, if the problem persists and you have information to add feel free to reopen the issue.
