### ISSUE TITLE
Graphical bug

### ISSUE THREAD

**Issue by cmaher94** [runelite/runelite#10254]
![Fishing(59)](https://user-images.githubusercontent.com/48571379/68802419-e5faca00-062b-11ea-85cf-df271f522709.png)

When running with GPU mode enabled, there are light blue squares covering any water on the screen. These squares also exist as holes in solid structures. If I toggle GPU off it goes away but if I flip it back on its back. Maybe its just my GPU? GT755M

**Comment by Nightfirecat** [comment]
I assume that's the skybox color? If you turn off the skybox plugin, I'm guessing those squares become black?

**Comment by Alexsuperfly** [comment]
duplicate of #8680
