### ISSUE TITLE
Bug with the status bars plugin

### ISSUE THREAD

**Issue by GoebbelsJr** [runelite/runelite#10260]
![2019-11-14_05-39-54](https://user-images.githubusercontent.com/51222916/68850180-80e1bb80-06a1-11ea-9bf2-26ee55667a69.png)
The status bars are no longer positioned correctly after the system update regardless of stretched mode.

**Comment by Bram91** [comment]
Client hasnt been updated yet to work with the latest version of the game. Should be fixed soon.

**Comment by abextm** [comment]
Fixed in 9d6f817a7072992583b1efab558560df59bebcfe
