### ISSUE TITLE
Screenshot Plugin: Twisted League screenshots are saving in the Deadman folder

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#10266]
**Describe the bug**
Screenshots are getting saved in `/CharacterName-Deadman`

**Expected behavior**
Screenshots should be saved in something like `/CharacterName-Leagues` or `/CharacterName-TwistedLeague`

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.41-SNAPSHOT

**Comment by Adam-** [comment]
fixed in ef15e79885f347cb5471c1a5b2e6bb2bf42c7842
