### ISSUE TITLE
Shift Anti-Drag in bank screen

### ISSUE THREAD

**Issue by Hydropwnic** [runelite/runelite#10262]
Hello,  I have a condition that makes my hands shake most of my waking life. It is very mild but has caused a lot of issues when playing the game until you guys introduced the Shift Anti-drag plugin. It has been an enormous help for me, but I still often struggle with clicking things in the bank interface.

Would it be possible to extend the functionality of the plugin to work within the bank also? I also was curious if it would even be possible to have the anti-drag feature be something that could just be toggled globally without also having to use any modifier keys?

I just want to say how much I appreciate you all. This feature alone has more than doubled the level of enjoyment I've had while playing again as an adult. 

Seriously, thank you guys!

**Comment by Adam-** [comment]
anti-drag has been added to the bank in #10318
