### ISSUE TITLE
Re-add the 'inventory grid' delay option

### ISSUE THREAD

**Issue by racast5** [runelite/runelite#10269]
There used to be an option to set the delay for the inventory grid. Specifically, it was how long you could move an item in ms before the inventory grid appears. 

I always accidentally move items just barely when shift-dropping large inventories or performing other quick inventory activities and the 'strobe effect' created by the inventory grid is extremely off putting. I loved the feature that allowed me to delay it's appearance.

**Comment by Adam-** [comment]
@dekvall do you think you could work this back in?

**Comment by dekvall** [comment]
Yep, I will figure it out.

**Comment by gregg1494** [comment]
@dekvall if you look my PR #9142 the last merge that is there has it.

**Comment by dekvall** [comment]
I see, but I would still like for this to be an option, maybe when the delay is set to 0. It's nice to have when you play with a trackpad.

**Comment by deathbeam** [comment]
Imo delay should be just added on top of current dragging check if anything.
