### ISSUE TITLE
Grapghics

### ISSUE THREAD

**Issue by Tloring8** [runelite/runelite#10261]
Run/HP/Special moved to the far right after update also, task bar is off as well
![image](https://user-images.githubusercontent.com/57754099/68852281-ce0b6080-0694-11ea-8377-c9969638226c.png)

**Comment by abextm** [comment]
Fixed in 9d6f817a7072992583b1efab558560df59bebcfe

**Comment by Tloring8** [comment]
still seeing same issue..
