### ISSUE TITLE
Kourend Library not showing locations in either regular or Twisted League

### ISSUE THREAD

**Issue by RycellaQ** [runelite/runelite#10272]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Spedwards** [comment]
Would you care to provide any information at all for this? I haven't had any issues with it in the Twisted League.

**Comment by Nightfirecat** [comment]
I've seen multiple streamers using this plugin during twisted leagues. If you have any details to add, please do so.
