### ISSUE TITLE
Shift-click bank option to withdraw 1

### ISSUE THREAD

**Issue by glowinghands** [runelite/runelite#10289]
**Is your feature request related to a problem? Please describe.**
I find ALL or X to be the most useful left click option when banking. Most times when I withdraw something, I withdraw all of them - runes, gold, food, ores, etc. It's almost never the correct option to use 1 because of how rarely you need just 1 of something. However, there are times where it would definitely speed up to have an easy way to withdraw 1. For example, you're restocking between slayer tasks and you need 1 super attack, 1 super strength, 1 super defense, and the rest food.

**Describe the solution you'd like**
The option of making [Shift]+[Left Click] to withdraw 1 instead of withdraw All

**Describe alternatives you've considered**
The most obvious workaround is to use the right click menu to withdraw 1, but I find it slows down my workflow a lot.

**Additional context**
This is probably a reasonably simple thing to implement and a prime candidate for someone looking to familiarize themselves with the codebase. A low hanging fruit, if you will. Of course, it's possible this is against TOS or actually not a good idea in the long run, for reasons I'm just not seeing at the moment.

**Comment by abextm** [comment]
This is on our [Rejected features list](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features)

**Comment by glowinghands** [comment]
Should it be though? It was on the rejected list because of its potential impact to bankstanding skills. But since it was added to the list, Jagex has released Withdraw-All and Withdraw-X. Presumably this would have been the intended purpose behind a Shift-click mechanism. Since that already exists, it seems weird that, givenWithdraw-All and Withdraw-X being a baseline of what is or isn't acceptable withdraw speeds, makes having Withdraw-All selected (as provided by Jagex!) and adding Withdraw-1 as a Shift-click mechanism would push it into unacceptable capabilities. 

The argument that the game not having Withdraw-All or Withdraw-X introduced as a single-click option and then introducing it with a plugin makes perfect sense. But since they now exist in the game proper, it seems obsolete to say that adding a Shift-click mechanism is overpowered.
