### ISSUE TITLE
d

### ISSUE THREAD

**Issue by ahahn95** [runelite/runelite#10283]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When I launch the game, everything looks checkered. Note, I just installed a new linux distro yesterday.

**Screenshots**
![Screenshot from 2019-11-17 09 15 13](https://user-images.githubusercontent.com/15878201/69008839-0c1ab580-091d-11ea-9ba1-54f30781340f.png)

**Environment (please complete the following information):**
 - OS: Elementary OS (Based on Ubuntu 18)
 - RuneLite version: 1.5.41.1
 - Launcher version: 1.6.2

**Comment by dekvall** [comment]
Try disabling [hardware acceleration](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration). I also would like to recommend our discord channel for first-hand support with issues similar to this.

**Comment by ahahn95** [comment]
That did the job. Cheers!
