### ISSUE TITLE
Kourend Library Varlamore Envoy and Dark Manuscripts

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#10296]
I'd like to request two changes to the Kourend Library plugin.

1. Varlamore Envoy does not show unless The Depths of Despair quest has been started and not finished.
    Varlamore Envoy is a book that is used for the aforementioned quest and nothing more. You cannot find it in the library under normal circumstances so it should not be shown unless those circumstances are met.
2. An option is included in the plugin to toggle showing Dark Manuscripts.

**Comment by abextm** [comment]
Added in 91417aca982687d58c51b5e8244ee61f3e2106ec
