### ISSUE TITLE
Menu Entry Swapper - Teleport Item Skull Sceptre(i) request

### ISSUE THREAD

**Issue by MaXaRaYkIn** [runelite/runelite#10295]
I just enabled my Menu Entry Swapper and I still can't believe this is not bannable! 
**Problem description**
The only thing that is not satisfying is that the Skull Sceptre(i) does not have his options switched. Maybe it is because the teleport option is called "Invoke". Probably the unimbued version has the same problem. 

**Solution**: Add the Menu Entry Swapper support for the Skull Sceptre(i) (and unimbued version).

![Untitled](https://user-images.githubusercontent.com/57946703/69145142-a3c30400-0ad5-11ea-8c57-1c591feb0457.png)

**Comment by Hydrox6** [comment]
Use [Shift click configuration](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#shift-click-configuration)

**Comment by jdmalter** [comment]
[_QUESTION_] What is the decision making process for how developers decide which teleport items whether receive toggle versus using shift click configuration?

**Comment by Adam-** [comment]
In the past the way the configuration menu worked & the way the swapper worked meant adding more things to it became sort of troublesome. Now it is less of a problem so we can probably revisit stuff like this.

**Comment by jdmalter** [comment]
Should this issue be re-opened, or should I raise a new issue?

**Comment by Adam-** [comment]
I can reopen it.

**Comment by Mrnice98** [comment]
ill fix this in a few hours

**Comment by jamesahhh** [comment]
sorry for sniping, was already looking @Mrnice98

**Comment by MaXaRaYkIn** [comment]
I'm glad to see this getting solved. Tyvm!
Now I gotta learn to click it without shift pressed xD
