### ISSUE TITLE
Target Indicator

### ISSUE THREAD

**Issue by ThePharros** [runelite/runelite#10302]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot tell what my current target is due to camera angle or stacked mobs, especially in multi-combat zones as Ironman. It helps a little with the asterisk menu entry indicator, but a rendered visual would be better.

**Describe the solution you'd like**
Same exact concept as NPC Indicators plugin, except instead of highlighting all mobs of the same name, it only highlights the one you are currently targeting and/or attacking. Would also like to see a complementary option in Entity Hider for PvM where entering combat hides all entities except your current target, and unhides them when combat ends, although this is of lower importance.

**Describe alternatives you've considered**
Only alternative right now is to attack target and manually toggle Entity Hider to make my target explicitly visible, then retoggle it as my target dies.

**Additional context**
N/A

**Comment by Nightfirecat** [comment]
I'm a little confused on the use case for this. What situations are you in where you are (a) in multi-combat, (b) attacking an NPC in a crowded group of NPCs, and (c) don't know what you're attacking? And in that situation, how would marking that NPC be more useful than the menu entry indicator that already exists?

**Comment by ThePharros** [comment]
it was a very niche situation for fighting in areas during Twisted League, but I've discovered you can just manually tag individual NPCs rather than having the entire type of NPC be highlighted

**Comment by ThePharros** [comment]
> I'm a little confused on the use case for this. What situations are you in where you are (a) in multi-combat, (b) attacking an NPC in a crowded group of NPCs, and (c) don't know what you're attacking? And in that situation, how would marking that NPC be more useful than the menu entry indicator that already exists?

it was a very niche situation for fighting in areas during Twisted League, but I've discovered you can just manually tag individual NPCs rather than having the entire type of NPC be highlighted
