### ISSUE TITLE
Chat command for league points

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#10301]
Something like `!lp`, would look like the current quest points command but instead show the players league points.

**Comment by kmutchnick** [comment]
@Adam- I tried taking a stab at this, but we'd need an API endpoint that works for League Points first, right?

**Comment by Adam-** [comment]
Yes, but since the api is implemented in `http-service` you can just make that yourself as part of a PR. Though TL might be over by the time this is finished.
