### ISSUE TITLE
Twisted League Kill Counter

### ISSUE THREAD

**Issue by glowinghands** [runelite/runelite#10304]
**Is your feature request related to a problem? Please describe.**
Kill counters do not consider bonus xp from twisted league. Prayer works because it's drop based, not kill based.

**Describe the solution you'd like**
The kill counter on twisted league to accurately depict the number of kills to level.

**Describe alternatives you've considered**
Manually dividing by 5 in my head

**Additional context**
Should also consider not just the 5x but other relics that affect xp gains.

**Comment by Nightfirecat** [comment]
fwiw this is a bug on DMM as well due to the boosted xp rates there

**Comment by glowinghands** [comment]
hmm, I guess it is technically a bug - i was considering it a feature since it's new functionality? Either way, I can live with it =)
