### ISSUE TITLE
Boost Indicator Spam when hopping from Main game to Twisted League

### ISSUE THREAD

**Issue by Jetter1** [runelite/runelite#10303]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I had my boost threshold notification set at 3 and when I swap from my main game profile to my twisted league profile where every stat is lower I get spammed with a lot of notifications.

**To Reproduce**
1. Login to main game with an account that has higher stats than the twisted league account
2. Hop to twisted league world using world hopper.
3. Rip ears

**Expected behavior**
There should ideally be no notifications if it could recognize twisted league world.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.41.1
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by LlemonDuck** [comment]
Twisted League is no longer available, so this ticket is now invalid
