### ISSUE TITLE
Lookup option for monster drop tables 

### ISSUE THREAD

**Issue by Entropyed** [runelite/runelite#10312]
I would like to be able to lookup monsters drop tables similarly to how we can currently lookup player hiscores. 

It can be implemented similarly as to the hiscores and player lookup was done but just grab the info from the wiki.

An alternate solution is you can use player drop data from the loo tracker but that would be unnecessary as the wiki has almost the exact drop percentages for the majority of the monsters in game provided by Jagex.

**Comment by Alexsuperfly** [comment]
using the wiki feature to lookup the monster basically gets you that

**Comment by Nightfirecat** [comment]
It's not so simple to "just grab the info from the wiki", unlike getting player data. I recommend [using the Wiki plugin's search feature](https://github.com/runelite/runelite/wiki/Wiki) to do this instead.
