### ISSUE TITLE
NMZ: Add health above threshold notification

### ISSUE THREAD

**Issue by bg451** [runelite/runelite#10330]
**Is your feature request related to a problem? Please describe.**
Runelite is really nice for AFKish nightmare zone, the absorption and overload notifications allow me to pop in from time to refresh my stats. When using Dharok armor and a rock cake/locator orb, the goal is to stay at very low health to maximize the strength bonus from Dharok. It'd be nice to have an config option where I can set a threshold that alerts me when my health goes above X hp so I can switch to my client and use my locator orb.

**Describe the solution you'd like**
A configurable threshold that allows alerting when HP goes above that threshold.

**Describe alternatives you've considered**
I've set the Idle notifications health threshold and it does not seem to work for this use case.

I'd be happy to tackle this as a first contribution if this seems like a reasonable thing to add upstream. Otherwise I'll just add it in a fork.

**Comment by Alexsuperfly** [comment]
The `Hitpoint Regen Notification (seconds)` option in the Regen Meter plugin will do this for you

**Comment by bg451** [comment]
Awesome, thank you!

**Comment by molo-pl** [comment]
Hello there! I believe this issue describes a reasonable feature (and, by the way, it's not really a duplicate of #10588).

To my understanding, the workaround that's been mentioned here and in PR #10513 will only work if a player wants to stay low on HP and react to **every** HP up. But there is a different scenario: players may want to stay below some HP threshold, let's say 10 HP, allowing them to only interact with the client every 10 minutes or so.

It's for a more AFKable approach, which maybe wouldn't be the best for Dharoking w/ overloads, but would work for NCR with super combat and absorption pots. Check out descriptions of both NCR variants (Melee, Ranged) under https://oldschool.runescape.wiki/w/Nightmare_Zone/Strategies.

Could we please reconsider reopening this ticket and PR #10513? CC @abextm, @Nightfirecat, @JZomerlei

**Comment by Nightfirecat** [comment]
If a time-based notification is what you're looking for, wouldn't the Time Tracking plugin already cover that more effectively?

**Comment by molo-pl** [comment]
Well, a time tracking tool can be used as a workaround. But same could be said e.g. about overload potions, and yet there's a dedicated feature for it in NMZ plugin.

IMO the benefit of having it integrated into the client comes with just a QOL improvement: you don't need to remember about the timer, no need to manually (re)set it after every game interaction.

**Comment by Nightfirecat** [comment]
While that may be the case, this strikes me as an exceedingly niche feature. We would, however, welcome a plugin hub submission to add this feature.

**Comment by JZomerlei** [comment]
The plugin on plugin hub nmz utilities does what my PR wanted to do. You could set threshold to 1 and it’ll alert you when ever you’re above 1 hp.

**Comment by molo-pl** [comment]
That's great to know, thank you!
