### ISSUE TITLE
Client process randomly terminates

### ISSUE THREAD

**Issue by bebbieee** [runelite/runelite#10333]
**Describe the bug**
Client sometimes randomly closes for me. It happened once last week, and occured again today.

**To Reproduce**
1. Be logged in for a certain amount of time
2. Client randomly closes

**Expected behavior**
It shouldn't close randomly. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.41.2
 - Launcher version: 2.0.2

**Additional context**
From the error log called jvm_crash_pid####, this is said at the top, can provide full file if needed:

 A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000213341463cb, pid=8692, tid=7472

 JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
 Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
 Problematic frame:
 J 18717 c2 dv.<init>([Ldv;I)V (1154 bytes) @ 0x00000213341463cb [0x0000021334143fc0+0x000000000000240b]

 No core dump will be written. Minidumps are not enabled by default on client versions of Windows

 If you would like to submit a bug report, please visit:
   https://github.com/AdoptOpenJDK/openjdk-build/issues

**Comment by Hallako** [comment]
Do you happen to be running navi based GPU like amd 5700 series? i'm trying to debug it a bit.

amd 3700x, 5700xt, windows 10 (1909).

**Comment by bebbieee** [comment]
Im running a ASUS Dual RTX2080, CPU im using is a AMD Ryzen 7, 8 Core 3.89 GHZ

**Comment by alexgermann** [comment]
Also having this issue. Sometimes it has happened when I right click -> lookup a person. Other times when opening the plugins menu. And sometimes while just playing the game.

**Comment by Hallako** [comment]
I would say it is same boat as many other games and programs getting violation errors with ryzen CPUs. Googling "ryzen 3000 0xc0000005" will yield a lot of similar problems. So it would be a issue with chipset driver or with AGESA.

Cannot really point where it would come in code as it seems to rise at different places. 
It's either EXCEPTION_ACCESS_VIOLATION or more specifically or while debugging:
java.lang.ArrayIndexOutOfBoundsException: Index 16777287 out of bounds for length 104
	at hg.fz(hg.java:1209)
	at el.zp(el.java)
	at el.fv(el.java:16996)
	at aj.gh(aj.java:4183)
	at az.io(az.java:9062)
	at az.io(az.java:9093)
	at bb.iq(bb.java:8951)
	at client.hp(client.java:3862)
	at client.ar(client.java:1207)
	at bo.lw(bo.java:385)
	at bo.run(bo.java:339)
	at java.base/java.lang.Thread.run(Thread.java:830)
Error: aj.gh() az.io() az.io() bb.iq() client.gs() client.ar() bo.q() | hg:1209 el.zp el:16996 aj:4183 az:9062 az:9093 bb:8951 client:3862 client:1207 bo:385 bo:339 Thread:830 | java.lang.ArrayIndexOutOfBoundsException: Index 16777287 out of bounds for length 104
error_game_crash

**Comment by MESLewis** [comment]
Does this happen on the latest release of RuneLite?
