### ISSUE TITLE
Stealing Artefacts plugin

### ISSUE THREAD

**Issue by ThePharros** [runelite/runelite#10348]
**Is your feature request related to a problem? Please describe.**
While stealing Artefacts in Port Piscarilius, it can be easy to forget which house your task was assigned to if not fully paying attention, if you go AFK mid-heist, or simply have bad memory. It can also be easy to forget where the pick-able drawers are for each location.

**Describe the solution you'd like**
**Feature 1:** An overlay in the corner that states which house the current heist is at after accepting a heist task (North-western, Western, South-Western, Northern, Southern, or South-eastern).
**Feature 2:** A highlight and arrow indicator for the drawers of the current heist. This could be the same highlight seen during clue steps that require drawer searching.
**Feature 3:** An auto NPC indicator highlight for the Patrolmen and Patrolwomen around the docks during a heist. This would make it easier to see which of the entities need to be avoiding while carrying the artefact.
**Feature 4:** Menu entry swap option for accepting a new task from Captain Khaled.

**Describe alternatives you've considered**
Currently I am using NPC Indicator with Patrolman and Patrolwoman as entries. For house location, I keep referencing [this image from the wiki](https://oldschool.runescape.wiki/images/c/c2/Piscarilius_residential_district_map.png?72707).

**Additional context**
Not all suggested features are dire. Even having just one or two of the four suggestions would be beneficial and a QoL improvement.

**Comment by ShaunDreclin** [comment]
Feature 4 was added by #10355

**Comment by honeyhoney** [comment]
I'll submit pull request for this tomorrow. I'll include at least feature 1.

Not sure how useful feature 3 would be given we have an NPC Indicator plugin already but I suppose it might be nice to have the patrolmen highlighted only when you have an artefact in your possession.

**Comment by Nightfirecat** [comment]
A Stealing Artefacts plugin now exists on the plugin hub: https://runelite.net/plugin-hub/show/stealing-artefacts

**Comment by alamedast** [comment]
Plugin is currently broken as of today, will it be fixed?

**Comment by LlemonDuck** [comment]
Issues with hub plugins should be directed to the authors: https://github.com/Chris-Bitler/Runelite-StealingArtefacts
