### ISSUE TITLE
Toggle antidrag

### ISSUE THREAD

**Issue by memis245** [runelite/runelite#10343]

**Comment by dekvall** [comment]
You would have to expand on this, it's not clear what you mean by only reading the title.

**Comment by Nightfirecat** [comment]
Please provide some detail to your issue report. We cannot act on something which is not described.

**Comment by memis245** [comment]
Runelite currently only has shift antidrag, where if you hold shift items wont drag for a certain time, a lot of people have shift drop and thats why we dont use it. It would be nice if you can toggle antidrag with a user picked keybind. For example, if i press ctrl, antidrag will be enabled. If I press it again, it will be disabled
