### ISSUE TITLE
Sidebar glitching please help! 

### ISSUE THREAD

**Issue by ScaredWombat** [runelite/runelite#10359]
I have looked at previous posts here about turning hardware acceleration off but it did not work for me! I tried the .bat file and it didn't work (I did uninstall and reinstall the client and osrs itself). Any other ways to fix it? its incredibly annoying.

**Comment by ScaredWombat** [comment]
![image](https://user-images.githubusercontent.com/58374852/69906496-a9e09c80-1381-11ea-8219-9fcf17b7851d.png)

**Comment by sethtroll** [comment]
Try this: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by ScaredWombat** [comment]
I did everything on it and it didnt help.

**Comment by Hydrox6** [comment]
Please join the [Discord](https://runelite.net/discord) for support queries
