### ISSUE TITLE
Chat League Icons, Icon is ugly

### ISSUE THREAD

**Issue by Phobos97** [runelite/runelite#10352]
Chat icon that replaces the default ironman helmet is too bright and colorfull.

Suggested: Normal ironman helmet with a green tint.

**Comment by Adam-** [comment]
We decided to only go with one icon to avoid confusion & keep it consistent. Additionally we went with the leagues icon and not the ironman icon because the fact that accounts in leagues are ironmen is a detail of the league and isn't really reflective of the whole game mode.
