### ISSUE TITLE
Time Tracking (farm timer) plugin Twisted League Harvester relic support feature-request

### ISSUE THREAD

**Issue by batye2** [runelite/runelite#10356]
**Is your feature request related to a problem? Please describe.**
I feel it would be a very helpful feature to more easily track specific farm times within Twisted League

**Describe the solution you'd like**
Just a toggleable 5x quicker farm time to the plugin

**Additional context**
Would be really stoked to see this added!

**Comment by honeyhoney** [comment]
I was briefly looking over this request and it looks like you could just divide the regrow tickrate and tickrate by 5 to achieve this.
https://github.com/runelite/runelite/blob/f4ede95e8615b0bcb9a723d6b5ffe755d023af39/runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/PatchState.java#L45-L48
Can anyone more familiar with the farming plugin comment? It seems like this tickrate is used as the basis for all the farming timers, including patch prediction.
Although I'm not sure how the relic affects harvesting (i.e. picking coconuts off a tree and how quickly they grow back) so perhaps only the `GROWING` case is relevant.

**Comment by dekvall** [comment]
Leagues are over for now and there will probably be other relics in the next iteration.
