### ISSUE TITLE
Set amount of cannonballs for the Cannon plugin notification,  instead of just when empty

### ISSUE THREAD

**Issue by stupididiot-nobrain** [runelite/runelite#10365]
With something like Idle Notifier, you can state the minimum amount of x statistic to notify you on, eg when below 30 health give a windows notification. Currently, with the Cannon plugins notification settings, you can only get it to notify you when the cannon is empty. I would prefer it if you could get it to notify you when the cannon has x cannonballs left, similar to the idle notifier plugin, so you do not miss cannon firing ticks when AFKing.

**Comment by LucasChilders** [comment]
I liked @JZomerlei implementation, but I wanted to keep the boolean toggle switch for ease of use, instead of `-1` for disabled.
