### ISSUE TITLE
Suggestion: Shift+click fill runecrafting pouches

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#10367]
Runelite allows to shift+click empty runecrafting pouches. The pouches can be filled when the bank interface is open, but that requires a right click and than another click. To simplify this, I suggest the pouches can be filled from the bank interface via a single shift+click, analogical to how they can be emptied.

- Pros: Makes training rc a tiny bit less cancerous.
- Cons: None

**Comment by abextm** [comment]
Duplicate #5668
