### ISSUE TITLE
Receiving your first slayer task from Konar (in Twisted Leagues) does not set your slayer task

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#10374]
Unfortunately, I skipped past the chatbox dialog before realizing my slayer task wasn't set properly, so I don't know what the exact text was. Perhaps this can be found via some content creator's YouTube videos?

**Comment by dekvall** [comment]
The raw message is:
```We'll start you off bringing balance to cows, you'll need<br>to kill 44 of them.```

**Comment by sethtroll** [comment]
added in https://github.com/runelite/runelite/commit/4578333fe003eece1642949ae73be89c8bb38a9e
