### ISSUE TITLE
[Skill Calc] Arrow Shaft wrong xp

### ISSUE THREAD

**Issue by whartd** [runelite/runelite#10384]
I just checked in game and cutting logs into arrow shafts yields 0.33 xp per shaft created. The skill calc has this incorrectly listed as 5 xp, which is the amount per 15 shafts.

The reason I have an issue with it being xp / 15 shafts is because it means you cannot use the skill calc's feature where you select multiple options. I.e. I can select headless arrow and broad arrow together and see how many arrow shafts I need to turn into headless arrows, and then into broad arrows. However, if I select all 3 it gives an inaccurate number of how many arrow shafts I will need to cut start to finish.

If you select all three actions, and try to find how many complete broad arrows you must make from 52 to 99 fletching, the skill calc will tell you that you need 1,291,078. The accurate value would be roughly 1,139,186 (rounded up). Calculated by :  `15 * ( 12910771 / (5 + 1 * 15 + 10 * 15) )`

If I went with the number from the skill calc I would cut 151,892 extra arrow shafts (I use maples from kingdom, so 2.5k extra logs), as well as buy 151,892 extra feathers (300k gp) and 151,892 extra broad arrow heads (8.3m gp)

An alternative solution, if the desire is still to base cutting arrow shafts on actions, would be to have separate entries for each type of log which you can cut, placed at the level required to cut them. I.e. Logs(maple) or Logs(magic), since each gives a different amount of xp. However, this does not solve my issue with calculating start to finish how many arrow shafts I will need for my desired level.

Edit: corrected xp / shaft, and explained why it matters to me
Edit2: added an alternative solution

**Comment by Alexsuperfly** [comment]
i get 5 xp in game

**Comment by dekvall** [comment]
It should be 5 xp per set of 15, what logs did you use?

**Comment by whartd** [comment]
5 xp per set of 15 = 3 xp / shaft though, no? If I see "48,809" actions to level, I think the intuition would be that I need to cut 48,809 shafts, not 48,809*15 shafts. It's not very helpful for determining actions as I'd have to go through and figure out how many sets of 15 my log uses.

**Comment by whartd** [comment]
It's also inconsistent with the rest of the calc. If you look down at Headless Arrows, it accurately says that it's 1 xp / headless arrow - it doesn't say "15" just because you make 15 at a time.

**Comment by whartd** [comment]
wait my math is really messed up here

**Comment by whartd** [comment]
So my number was wrong, it's less than 1 xp per arrow shaft. it's 0.33 xp / shaft. The reason I have an issue with it being xp / 15 shafts is because it means you cannot use the skill calc's feature where you select multiple options. I.e. I can select headless arrow and broad arrow together and see how many arrow shafts I need to turn into headless arrows. However, if I select all 3 it gives an inaccurate number of how many arrow shafts I will need to cut start to finish.

**Comment by Alexsuperfly** [comment]
its based on actions, making shafts is a single action, it just so happens that that one action will always make 15 shafts.

**Comment by whartd** [comment]
@Alexsuperfly Why is it based on actions when the rest of the fletching skill calc is not? That's inconsistent.

**Comment by Nightfirecat** [comment]
Because you can make fewer than one full action's worth of most other ammunition. eg. One feather + one million arrow shafts will only produce a single headless arrow. The same will never be true of getting arrow shafts from logs.

**Comment by dekvall** [comment]
You get more than 15 arrow shafts from higher order logs though, so using the per shaft xp makes it scale better for those actions. It's also a nice bonus that it enables you to combine the action with adding feathers and arrowtips.

**Comment by Mekanation** [comment]
I believe I fixed this. I made a pull request. (First ever open-source fixup, let me know if I need to improve anywhere.)

**Comment by dekvall** [comment]
Added in #10457
