### ISSUE TITLE
Target level

### ISSUE THREAD

**Issue by tildahoglund** [runelite/runelite#10385]
**Is your feature request related to a problem? Please describe.**
I always wonder how long a couple of levels might take but Runelite only let us see how much xp that is left to next level. So I have to go search on the internet to do the calculation.

**Describe the solution you'd like**
When rightclicking on the skill the only option right now is to reset. Solution to problem: add another option to "set target level" and let the player choose which level they want to se xp for. For example if im at lvl 40 fishing i would like to see how many actions/lobsters there are left until im lvl 50. 

**Additional context**
I was playing with osbuddy and switched to runelite. Runelite is way better in my opinion, only thing im missing from OSB is this. =)

**Comment by dekvall** [comment]
We use [vanilla xp goals](https://github.com/runelite/runelite/wiki/XP-Tracker).
