### ISSUE TITLE
Add spellbook reordering

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1038]
To go with the prayer reordering plugin, would be nice to move the order of your spellbook around too.

**Comment by Adam-** [comment]
Considering the other clients don't have this, I probably don't want to do it because it makes alching and enchanting somewhat easier.

**Comment by ShaunDreclin** [comment]
I dunno, I don't think it makes that big of a difference really.

You can already position items in the same place as the spell so you can click without moving the mouse.

**Comment by SoyChai** [comment]
I can't think of any alch or enchant advantages, since alching works the way that Shaun mentioned, and enchanting is a wrist exercise no matter where the icon is.

 Maybe it's the the complexity of multiple spellbooks that scares off other clients?

**Comment by CaraPis** [comment]
Only superheating would have an advantage. But then if you use WMK, it's pretty much the same as if you'd click in one spot imo.
