### ISSUE TITLE
Woodcutting tree timers disappearing

### ISSUE THREAD

**Issue by iDre4M** [runelite/runelite#10380]
**Describe the bug**
Timers near the tree stumps disappear out of nowhere.

**To Reproduce**
I was cutting yews in F2P world near GE.
1. Go to that area;
2. Click on yews;
3. Repeat cutting yews and banking;
4. Sooner or later yews respawn timer disappears when you are a bit further or near by yews you just see blank tree stump without any timers near it;

**Expected behavior**
Timers would remain near the trees all the time, no matter if I was banking or I was near the trees, waiting for their respawn.

**Screenshots**
Well, I haven't made a screenshot, but it's basicly disappearance of that timer you just see tree stump without timer near it.

**Environment (please complete the following information):**
 - OS: Windows 10 64-bit (version 1909, build 18363.476)
 - RuneLite version: 1.5.42.1
 - Launcher version: 2.1.0

**Additional context**
In the logs folder everything seems to be fine.

P.S. If screenshot is very needed I might post it tomorrow, since it happens quite often.

**Comment by Adam-** [comment]
Not sure I understand this. For the timer to work the plugin has to clearly see the tree felled; there isn't a way around that.

**Comment by iDre4M** [comment]
> Not sure I understand this. For the timer to work the plugin has to clearly see the tree felled; there isn't a way around that.

Well that was happening while standing near the yews themselves... So, I'm not entirely sure if client didn't see it.

Now seeing that 'pull request' it would make a sense, because it felt like game got insta update or something and timers disappeared, so I would guess that's GameState changes or something like that, not sure tho.

**Comment by Adam-** [comment]
Yes, we're going to adjust it so the tree is remembered even if you leave the area. If you are standing next to a tree and it falls and the plugin doesn't report it that sounds like a separate problem though.

**Comment by iDre4M** [comment]
Mhm.. Well I've noticed that this thing still happens... I was banking and run back to yews and timers disappeared in front of my eyes. So it's most likely not the GameState change/update, might be something more.
