### ISSUE TITLE
sidepanel creates overlay

### ISSUE THREAD

**Issue by tubeegern** [runelite/runelite#10394]
When i hover my mouse over a button on the sidepanel in runelite it creates an overlay that covers the buttons on the sidepanel, if i hold my mouse over a button i can often see that button but it makes it really hard to navigate the sidepanel, and it becomes nearly useless.

I have tried to delete and redownload runelite a few times but the bug reappears again.

I have also tried to  turn everything off in the configuration menu to see if it was a plugin like GPU or something that made the bug appear.

It doesnt affect or overlays the game itself in any way, but just makes the sidepanel kinda useless, its also only visual so the buttons placement doesnt change. 

Here is a picture of the bug
![bug picture](https://user-images.githubusercontent.com/58561921/70248649-7d5ec300-177b-11ea-93fc-82c98b7fc28b.PNG)

system and RuneLite information  
 - Windows 10
 - RuneLite version: 1.5.42.1
 - Launcher version: 2.1.0

[client.log](https://github.com/runelite/runelite/files/3927659/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3927660/launcher.log)

**Comment by Nightfirecat** [comment]
Please [disable hardware acceleration](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration).
