### ISSUE TITLE
Add support for Boss Hiscores

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#10397]
With the update on the 5th of December, Jagex implemented Boss Hiscores. These should be incorporated into the Hiscore panel.

Exactly how it should look will need some discussion.
Currently, there is basically no space in the current UI to display both the Hiscores and the Boss Hiscores at the same time, since the normal Hiscores fill the entire ~503 pixel height when the client is its smallest.
Having the panel scroll would be a simple fix, but since the panel hasn't ever scrolled before, it could confused users. A button also poses a similar problem, since nothing else is a button on there.

The layout of `index_lite` should be pretty simple to modify, I've mapped out the new format [here](https://pastebin.com/xrN6ZnUv). Note: Callisto and Cerberus are missing from the list. I have no idea when Jagex will notice and fix it.

**Comment by Rulesy** [comment]
I believe Cerberus is missing also.

**Comment by Hydrox6** [comment]
That's been brought up a couple of times in Discord, forgot to edit it here. Ty for reminding me

**Comment by Rulesy** [comment]
Also, using your pastebin reference I found I also needed to remove League Points to correctly pull data.
