### ISSUE TITLE
Add Jekyll on Random events notifier

### ISSUE THREAD

**Issue by Abi1024** [runelite/runelite#10403]
**Is your feature request related to a problem? Please describe.**
With the new Twisted League, it probably makes sense to add Jekyll to the list of random events that can notify the player in the Random Events plugin. Jekyll is the only way to obtain stamina potions in Twisted League, which are needed for restoration pools.

**Describe the solution you'd like**
Add Jekyll to the random events plugin.

**Comment by sethtroll** [comment]
According to https://github.com/runelite/runelite/blob/5494249636322830e2672da905bd1e1eec81a53f/runelite-client/src/main/java/net/runelite/client/plugins/randomevents/RandomEventPlugin.java#L58, Jekyll is included.

**Comment by Blackberry0Pie** [comment]
There is not a specific option for dr jekyll only. There is a "notify for all events".

**Comment by Abi1024** [comment]
Yeah, as @Blackberry0Pie  said, there basically needs to be a config option for enabling Dr Jekyll specifically.
