### ISSUE TITLE
GPU Plugin giving glitch/square graphics in AMD Radeon R8 M445DX

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#10409]
**Describe the bug**
Graphics glitched when GPU plugin is activated.

**To Reproduce**
1. Get AMD Radeon R8 M445 DX (which is actually a name for a dual-graphics card. R5+R7).
2. Turn on GPU plugin.

**Expected behavior**
Glitchy graphics.

**Screenshots**
https://prnt.sc/q7smfw

**Environment (please complete the following information):**
-OS Windows 10 x64 Single Language 
-RuneLite 1.5.42.3

**Additional context**
This happened on MMORPG Tibia too and was something with OpenGL but the developers fixed I don't know how.

**Comment by Adam-** [comment]
reopen if this is still an issue
