### ISSUE TITLE
Plugins lost saved settings

### ISSUE THREAD

**Issue by agoge69** [runelite/runelite#10406]
Over night, all my plugins were disabled (minus homeworld). I lost all my bank tags/tabs, screen markers, tile markers, etc.). I have tried to restore from a previous version but there were none that were able to be recovered. Even now, I can't use some plugins such as item prices. I would like the most to get the bank tabs back if possible.

**Comment by Hydrox6** [comment]
Closing as incredibly stale. 
For further questions of support, please join the [Discord](https://runelite.net/discord)
