### ISSUE TITLE
Add time to level to the xp globes tooltip

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1041]
Also if possible, hook into the vanilla xp tracker to get your goal xp/level and show you time until you reach your goal.

**Comment by DevDennis** [comment]
https://github.com/runelite/runelite/pull/1030 this PR adds that except the time to level

**Comment by LeviSchuck** [comment]
![image](https://user-images.githubusercontent.com/245911/39504330-6e9c187e-4d90-11e8-9e6a-7a8abaf07d1f.png)

Adding many of those duplicates the xp tracker panel.. but then we might as well just merge these plugins so they share the same data structures and events.

**Comment by LeviSchuck** [comment]
Specifically what is not implemented so far, and is asked for in this issue is:

1. Time to level
2. XP per hour

Actions to level is already present.

**Comment by ShaunDreclin** [comment]
Is exp/h in the tooltip now?

**Comment by Nightfirecat** [comment]
From the screenshot in #4380, yes.

**Comment by deathbeam** [comment]
We have TTL in sidebar and everything else mentioned in this issue was implemented
