### ISSUE TITLE
PC Stutters / Freezes while using Runelite (while pick pocketing)

### ISSUE THREAD

**Issue by KnottyDog** [runelite/runelite#10410]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I'm getting a bug where my PC will freeze up for a few seconds at a time every 5 - 10 seconds or so and eventually chrome tabs become unrsponsive and runelite smetimes closes itself during the freezing. The computer continues to stutter and hang every 5 - 10 seconds until I'm forced to do a hard rest as windows button also become unresponsive.

**To Reproduce**
The bug seems to happen when I'm pick pocketing guards in east ardy. I'll be clicking the guards then all of a sudden my whole pc locks up for a few seconds then unfreezes then locks up again several seconds later as described above and hard restarting my PC is the only way it stops.

**Expected behavior**
No freezing/stuttering

**Screenshots**
N/A

**Environment (please complete the following information):**
 Windows 10 64 bit, Runelite version 1.5.42.3.

**Additional context**
N/A

**Comment by Hydrox6** [comment]
"Latest RuneLite version" is not a valid version

Support issues are best handled in the [Discord server](https://discord.gg/mePCs8U)

**Comment by KnottyDog** [comment]
> "Latest RuneLite version" is not a valid version
> 
> Support issues are best handled in the [Discord server](https://discord.gg/mePCs8U)

When you open the client it auto download the latest version so why even comment this useless info? come back when you can help me with my issue, thanks.
