### ISSUE TITLE
Running runelite with gpu cause stutter every few steps.

### ISSUE THREAD

**Issue by jboyken3** [runelite/runelite#10413]
**Describe the bug**
When I play the game running off of GPU my character stops moving for an instant every few steps.
**To Reproduce**
1. Run game through gpu or turn on gpu mode.
2. Walk anywhere

**Expected behavior**
When not on GPU the game doesn't have this stutter walking.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.42
 - Launcher version: not sure how to check

**Additional context**
Using NVIDIA GeForce GTX 1060

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest release of RuneLite or join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.
