### ISSUE TITLE
Runelite window is invisible and unaccessible

### ISSUE THREAD

**Issue by MarkisJr** [runelite/runelite#10429]
**Describe the bug**
Starting today, when I open Runelite, the application appears in my task bar but when maximised the entire window is invisible and just shows my desktop behind it. 

**To Reproduce**
I am unsure as how to reproduce this bug as I didn't do anything abnormal compared to my usual routine of:
1. Opening Runelite through Start Menu on Windows
2. Logging in

**Attempted Fixes**
To try and fix this myself I have done a number of things in vain to try and solve the issue:
1. Delete jagexcache before launching
2. Reinstalling (attempted three times)
3. Uninstalling and deleting every file I could possibly find relating to Runelite, such as .runelite in %userprofile% etc.
4. Step 3 but I also uninstalled all java versions on my pc and reinstalled java 64bit and 32bit
5. Multiple computer restarts

**Expected behavior**
When I open the application I expect to see the login page.

**Screenshots**
![taskbar icon](https://user-images.githubusercontent.com/25335443/70712915-00ae8480-1d39-11ea-9073-e38f1d9511e6.png)
There's little to see as you cannot even see the client but in the snip above you can see how it remains in the task bar.

**Environment:**
 - OS: Windows 10 64bit operating system
 - RuneLite version: I am unable to tell as I cannot see anything on the application (but I just downloaded the latest 64bit version on the 12th of December 2019)
 - Launcher version: Same issue as seen above ^^

**Logs**
[client.log](https://github.com/runelite/runelite/files/3955711/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3955712/launcher.log)

**Additional notes**
Not sure if this means anything but when open Runelite the launcher still comes up and initialises Runelite (like saying loading bootstrapper and all that). Not sure if that helps.

*Edit 1: Bad late night grammar

**Comment by JZomerlei** [comment]
Join the discord and link this issue in there and some one will help you, this place isn't a super good way to respond and chat about this issue.

**Comment by MarkisJr** [comment]
Fixed, had to turn off gpu in properties
