### ISSUE TITLE
A way to mark players with a tag

### ISSUE THREAD

**Issue by ianpoe** [runelite/runelite#10427]

**Comment by Alexsuperfly** [comment]
this is currently [rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#not-currently-being-considered)
`Highlighting "Offline" Friends (and generic player highlighting):`

**Comment by Hydrox6** [comment]
Alternatively, this is just the `Player Indicators` plugin, which can mark everyone.
