### ISSUE TITLE
Runepouch overlay in bank

### ISSUE THREAD

**Issue by themozerath** [runelite/runelite#10437]
**Describe the bug**
When the runepouch is filled in the bank, and you scroll past it, the overlay gets over the 'frame' of the bank screen.

**To Reproduce**
1. put a filled runepouch in the bank relatively low on the first tab, so you have to scroll to it
2. scroll towards the runepouch location and back 
3. you will see that the overlay gets over the 'frame' 

**Expected behavior**
The overlay has to be between of the runepouch icon, and the frame of the bank screen

**Screenshots**
![image](https://user-images.githubusercontent.com/58338708/70849675-1ed3cc00-1e82-11ea-8f4a-d361a9b00899.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.42.3
 - Launcher version: 1.6.0

**Additional context**
It's not top priority, but in my opinion it is quite disturbing for some reason

**Comment by raiyni** [comment]
Fixed in 9a103f8ccd4928c6da8679ace7e02f1f9f874a63
