### ISSUE TITLE
Client crashes on linux when i click the "click here to paly" button after logging in

### ISSUE THREAD

**Issue by steffenhaug** [runelite/runelite#10430]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Client crashes on linux when i click the "click here to paly" button after logging in.
The reason is an ArrayIndexOutOfBoundsException. I attached the relevant error message here (
[crash.txt](https://github.com/runelite/runelite/files/3955843/crash.txt) ), but it doesn't seem to give many hints. I can provde the rest of the log if desired, but I restricted it to this message because i don't want to read through the entire log to ensure it doesn't leak anything I don't want it too if it's not necessary.

**To Reproduce**
1. Log in on linux
2. Click "click here to play"

**Expected behavior**
I get logged in to the game like normal

**Environment (please complete the following information):**
 - OS: Linux running X11 and BSPWM
 - RuneLite version: I downloaded the .AppImage again from the website today (12. Dec)

**Additional context**
The vanilla client still works without any problems, and runelite worked yesterday. I don't know if perhaps runelite was updated along with the OSRS update, but if so it seems like something in that update caused this issue.

**Comment by Alexsuperfly** [comment]
Try [this](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-crashing-on-login), if not join us on [discord](https://runelite.net/discord) for further support of this type.

**Comment by steffenhaug** [comment]
Deleting the jagex cache did the trick, as explained in the "client closes when loading". Although my client didn't close when loading, so maybe this (client simply freezing) can be included in there so it's easier to search for?

Anyways, thanks a lot!

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-crashing-on-login links to https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-closing-when-loading on the wiki already, so I think this is appropriately covered.
