### ISSUE TITLE
Add a Grand Exchange option for setting the default "withdraw as" option (note/item)

### ISSUE THREAD

**Issue by fashionLeek** [runelite/runelite#10434]
![image](https://user-images.githubusercontent.com/25644323/70821753-cb0aa980-1dd3-11ea-8aaa-210543a4aabe.png)

Currently RS switches the options based on if there are 1 or multiple items to collect. My suggestion is to add a setting for the user to set a default option so it doesn't change.

**Comment by fashionLeek** [comment]
@Rami-J Thanks for contributing 👍 

I was just thinking, does it work with the "collect" option in the Grand Exchange? It also changes the withdraw type depending on the stack size.

**Comment by fashionLeek** [comment]
![image](https://user-images.githubusercontent.com/25644323/70938791-cdbd0700-203e-11ea-92c7-fa07a609ba37.png)

**Comment by Rami-J** [comment]
@fashionLeek I've only gotten the collect button to swap entries between "Collect to inventory" and "Collect to bank". When I collect to inventory using the collect button, it still changes withdraw type depending on stack size.
![4](https://user-images.githubusercontent.com/44623786/70947463-30a2a400-2027-11ea-9744-8c1a846ac5f8.png)
