### ISSUE TITLE
Client glitched heavily affects the usage of the client

### ISSUE THREAD

**Issue by AshIsAlone** [runelite/runelite#10436]
![image](https://user-images.githubusercontent.com/58869015/70841814-08c2fe80-1de3-11ea-8a67-22b3d09f4f93.png)

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by AshIsAlone** [comment]
Appreciate ya mate
