### ISSUE TITLE
Ignore list notes

### ISSUE THREAD

**Issue by adambtwl0l** [runelite/runelite#10442]
**Is your feature request related to a problem? Please describe.**
It's rather annoying when reporting toxic individuals/bots and seeing your ignore list and that you don't realize why people are on there anymore. 

**Describe the solution you'd like**
Would it be possible to make it function like friends list where people can add tags? Also would it be possible to right click look them up to see if they've been banned? That way we could easily see they're banned and thus no real reason to keep them on there 

**Describe alternatives you've considered**
Typing the names into the hs plugin manually (very annoying)

**Comment by Adam-** [comment]
added in #10455
