### ISSUE TITLE
Examine plugin positive overflow

### ISSUE THREAD

**Issue by BegOsrs** [runelite/runelite#10443]
**Describe the bug**
Examine plugin is overflowing when the total price is over max integer value.

**To Reproduce**
1. Enable the examine plugin
2. Examine some item stack valued at over max integer value

**Expected behavior**
Should be displaying the real value instead of a negative value (overflowing)

**Screenshots**
https://github.com/runelite/runelite/blob/f8b801f6cdad414a66349b808f45f7eda78dd8b0/runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java#L359
https://github.com/runelite/runelite/blob/f8b801f6cdad414a66349b808f45f7eda78dd8b0/runelite-client/src/main/java/net/runelite/client/plugins/examine/ExaminePlugin.java#L379
**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - RuneLite version: 1.5.42.3
 - Launcher version: 1.6.2

**Comment by zacharydwaller** [comment]
I fixed this and put in a pull request. The same overflow occurs with the mouse-over price text as well
