### ISSUE TITLE
Woodcutting: Tree respawn timers don't go away when changing floors at redwoods

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#10449]
**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/5851433/70902204-4766dd80-1fca-11ea-97ac-69ec2e9634f7.png)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.43-SNAPSHOT

**Comment by Alexsuperfly** [comment]
I believe this is caused by the despawn event only firing when you go to that level, making the plugin think it has just been chopped down while it could have been depleted for any amount of time already.
