### ISSUE TITLE
Monsters left on slayer task completely useless when barraging

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#1046]
When bursting/barraging slayer monsters you stack them and kill multiple at the same time. This results in multiple monsters dying in the same tick, giving only one slayer xp drop, and the counter only counting one monster dying. This throws it off, making i unusable when bursting slayer tasks.

**Comment by Adam-** [comment]
When more than one person contributes to a slayer monster kill, the xp drop is halved, so you cannot tell solely based on xp drops how many npcs have died that tick. You would have to be able decide who damaged what NPC as well, which is either not possible or not feasable, so I do not think we will be fixing this anytime soon.

**Comment by rune3132** [comment]
Yeah, all the other clients have the same problem, so I imagined it wouldn't be an easy fix. Also, I'm sorry if my wording was a bit harsh, that was in no way my intent

**Comment by CasvanDongen** [comment]
I can look into this, there are some ways to determine the single kill xp drop but they aren't 100% failsafe.

**Comment by ShaunDreclin** [comment]
It may be safe to assume that most of the time you will not be sharing kills, so we could just ignore that and let the counter get slightly out of sync when people do interfere. More important to make multikills work with the counter imo

**Comment by Adam-** [comment]
I think this is probably a good assumption.

**Comment by lund8619** [comment]
Just finished a bursting task and was thinking about this. What do people think of the logic of something along the lines of if xp % hp == 0, kills remaining = kills remaining - xp/hp?

One potential issue I see there is superiors. Thoughts?

**Comment by lund8619** [comment]
It's not a 100% solution, but it'd be more often correct than currently. Are "less wrong" logic fixes ever implemented, or do things like this usually wait for a absolute fix? It looks like Davis Cook's got a much more sophisticated PR that would resolve this, so just curious about the approach to issues like this now.

**Comment by raiyni** [comment]
there's also the fact some monsters have bonus xp

**Comment by lund8619** [comment]
I acknowledged that issue in my first comment. That's why the "if xp % hp == 0" part. The else would just have to default back to the current decrement by 1. So for the philosophical question, I take it the answer is keep the most simplistic logic until somebody comes up with a complete solution and don't bother with the might be better might not type of solution I'm posing here?

**Comment by Adam-** [comment]
fixed in 67030e38a44f355a0131cff5250ed45c7b01dc53
