### ISSUE TITLE
Command move?

### ISSUE THREAD

**Issue by zandybobandy** [runelite/runelite#10461]
is there a possible way to make lets say a shift click or some sort of combo of keys to always make click option walk?
lets say you hold shift and click on and npc you will walk under instead of attack or talk

**Comment by Adam-** [comment]
This is on Jagex's list of unacceptable features: https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

`Allows you to prioritise the walk-here option by holding a certain key, or similar`
