### ISSUE TITLE
Runelite 1.3.0.1 windows build does not open

### ISSUE THREAD

**Issue by MattyJacques** [runelite/runelite#1047]
I just downloaded and installed the most recent windows build release. When the installed application is opened, nothing happens. There is no flicker of something opening and closing, nothing at all. Process also does no show up in the task manager.

OS is Windows 10 version 1709

**Comment by Adam-** [comment]
This maybe should be filed against https://github.com/runelite/launcher instead. The best way to debug it would be to navigate to AppData\RuneLite and run `RuneLite.exe -c --console`.

**Comment by MattyJacques** [comment]
Whoops, thanks for the reply. I'll have a look at the console. 👍

**Comment by Adam-** [comment]
Moved to https://github.com/runelite/launcher/issues/8
