### ISSUE TITLE
Highlight items in bank that can be stored in the POH

### ISSUE THREAD

**Issue by ellmck** [runelite/runelite#10486]
Certain items will be taking up bank space such as armour sets and treasure trail awards.

There are several ways to add this feature:

1.  Highlight treasure trail items and full armour sets that can be stored.
2.  A new tab that shows banked items that can be stored elsewhere.
3. A simple csv list of the items that can be stored elsewhere.

**Comment by abextm** [comment]
This is probably better to just be a bank tag people can import
