### ISSUE TITLE
Teleport Item Whitelist

### ISSUE THREAD

**Issue by SPLfeed** [runelite/runelite#10505]
Although a minor annoyance, when just turning on the "Teleport Item" plugin it allows all items with teleport options to be left clicked. Which for the most part isnt a problem, but when doing Corp it makes you left click to myths guild when putting Myths cape on. Is there any way to whitelist items like Construction & Crafting Capes while also leaving the left click option for the Myths Cape as "wear"?

**Comment by Adam-** [comment]
There is no `Teleport Item` plugin.
