### ISSUE TITLE
Tab tag icons for a tag with a ':' in the name do not get loaded correctly

### ISSUE THREAD

**Issue by NullBy7e** [runelite/runelite#10500]
**Describe the bug**
When a tag includes an ':' in the name, icons are saved but not loaded from the settings and the icon appears as a a spade.

**To Reproduce**
1) create a tag tab named test:2
2) assign a custom icon
3) close the bank
4) logout
5) close the client
6) log back in and open the bank
7) the icon appears as a spade

**Expected behavior**
The icon should load correctly when a tag name includes an ':'.

**Screenshots**

**Environment**

OS: Windows
RuneLite version: 1.6.0.1
Launcher version: 1.6.0

**Comment by dekvall** [comment]
I can't reproduce this with the steps provided.

**Comment by NullBy7e** [comment]
> I can't reproduce this with the steps provided.

[2020-01-09 18-18-35.zip](https://github.com/runelite/runelite/files/4041679/2020-01-09.18-18-35.zip)

Here's a video that shows the problem, icons for tags with : and/or - in the name that are not surrouned by whitespace aren't loaded correctly (as it appears).
