### ISSUE TITLE
Ignore list autofill / right click lookup

### ISSUE THREAD

**Issue by adambtwl0l** [runelite/runelite#10516]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Very frustrating to go through the ignore list trying to clean it out from bots/etc that you've reported to check which ones are banned and which aren't.

**Describe the solution you'd like**
Please make it so there's either a right click lookup option for the hiscores feature on the client, or so that the autofill option includes the ignore list just as it does for accounts on your friends list as well as in your physical area (possibly toggle-able)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
Manually typing them to search which is pretty time consuming and inconvenient

**Additional context**

**Comment by Adam-** [comment]
This was already added in f3b8bace727ffd8ba2f1cc6898496e30d981689a
