### ISSUE TITLE
Spec Counter does not have accurate damage values on ToB and CoX bosses

### ISSUE THREAD

**Issue by adambtwl0l** [runelite/runelite#10518]
**Is your feature request related to a problem? Please describe.**
Since some of the NPCs have scaled EXP (just in general as well as varies with party size), the special counter will often give you the wrong damage amount with BGS/arclight (anything where the amount of damage is important as opposed to whether or not you actually hit like DWH), and in cases where everyone is speccing at once or in quick succession you may miss the damage amount entirely. This also happens in chambers of xeric (I believe?) and I think other bosses with scaled hp/exp as well, such as KQ (but in many of these cases barring cox/tob it isn't too relevant since presumably you'd be solo and see your own hits clearly.) 

**Describe the solution you'd like**
If possible make the plugin read properly based on what the client witnesses you speccing as opposed to based off exp in these rooms/situations, or if possible make the plugin account for the equations/party size scalings that effect this to make it accurate.

**Describe alternatives you've considered**
Not much to do as an alternative in many situations where you're all speccing at once since obviously a finite amount of hits appear.

**Comment by Adam-** [comment]
fixed in 8674a4f998ada7708de842ec98e9cc098b4c385c
