### ISSUE TITLE
Entity hider ignore list

### ISSUE THREAD

**Issue by adambtwl0l** [runelite/runelite#10520]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Entity hider allows you to hide either everyone or just not clan mates/friends, as opposed to removing specific individuals. In crowded areas where there's lots of bots you may choose to report them but you may still not want to see them. Same goes for public areas (ToB lobby for instance) if you don't want to see the usual toxic crackheads begging for attention/flaming/whatever by the board or following you around even if you've got them on ignore. 

**Describe the solution you'd like**
Allow entity hider to toggle hiding just people who are on your ignore list - possibly in DDs/right clicks as well although that's not as important. So you're able to hide people you have on ignore without hiding everyone else. 

Assuming entity hider works in pvp at all I imagine this would have to be disabled there though because you could have someone on ignore for ragging/toxicity and they'd be able to attack you/rag you while invisible which would be problematic.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by abextm** [comment]
This is against the rules <https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1>

**Comment by theoddsheep** [comment]
@abextm What part of the rules here :  https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

Is this against? I can't find anything that I would interperate as breaking the rules relating to this issue. Sorry if I've missed something.
