### ISSUE TITLE
Save loot tracker entries

### ISSUE THREAD

**Issue by adambtwl0l** [runelite/runelite#10523]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Currently with large grinds / loot recordings if you reload the client (especially if you do something else in the meantime which records other entires), it will mess up the loot tracker deleting some of the loot/progress from the larger grouping. This happens with smaller-ish things such as the black knights for falador diary, long raid recordings (for instance recording loots from 100 raids but doing things in the meantime and not/forgetting to clear the other entries from the tracker), longer grinds with lots of kills (moss/hill giants for keys - any champion scroll npc - even barrage tasks if you camp slayer for a while and get a lot of the same task.)

**Describe the solution you'd like**
Allow people to "Save" a loot tracker grouping if they have it categorized by npc instead of individual kill, so people can save entries for their most preferred activity for instance raids killcount without having it messed up by them doing slayer or something else in the meantime and deleting raids entries. This would (preferably) keep any entries in that specific category from being wiped/pushed out of the loot tracker unless manually cleared. And I imagine you'd only be able to allow 1 activity max to prevent some sort of overload or people just saving everything so nothing was ever cleared which I imagine would be less than preferable, as well as potentially add a cap for killcount.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by abextm** [comment]
Duplicate #10041
