### ISSUE TITLE
RW warning

### ISSUE THREAD

**Issue by adambtwl0l** [runelite/runelite#10521]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
It's beyond annoying to go into group / publicly available activities and realizing you ended up with someone on your team who is a scammer or known for being toxic/griefing teammates. This often results in the activity experiencing problems, especially raids. A lot of people also don't like the idea of dealing with scammers even in free for alls.

**Describe the solution you'd like**
If possible add a plugin which will warn you when there's someone with publicly available evidence for scamming/other serious offenses - Runewatch ( https://runewatch.com/incident-index-page/ )  and WDR discord ( https://discord.gg/WDR ) both have publicly available ban lists with reasoning and in many cases evidence.

If possible just like a chatbox warning that says something along the lines of "(user) is listed on Runewatch for scamming" or "(user) was banned from WDR for griefing raids)"

I believe both of the mentioned entities regularly track/update RSN changes themselves.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by abextm** [comment]
Duplicate #3828

**Comment by RuneWatch** [comment]
We have refactored our case system and are now able to support this feature.
Here's a case list you can use: https://www.runewatch.com/api/cases/list
If you would like to query a single rsn please let us know via twitter @RuneWatch or dm Will osrs#0480 on Discord.

(I do not wish to re-open an issue/request for this, so pick it up if you'd like to move forward with it)
