### ISSUE TITLE
Random Client Crashes 

### ISSUE THREAD

**Issue by Aeell** [runelite/runelite#10525]
""Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)""

- All i saw was posts with not full info posted and not a clear answer to my problem

**Describe the bug**
-Title pretty much sums it. Client crashes by force closing itself on random times,tend to always be after 30+ mins gamplay.

**To Reproduce**
-I guess open the client on my machine ?

**Environment (please complete the following information):**
 - Windows 10
 - RuneLite version: 1.6.0.1
 - Launcher version: 2.1.0

**Additional context**
[client.log](https://github.com/runelite/runelite/files/4012478/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4012479/launcher.log)

**Comment by Nightfirecat** [comment]
Do you have an `hs_err` file in your logs directory? Neither of the provided logs show any detail on this crash.

**Comment by Aeell** [comment]
There is no such hs_err file in the directory. However last 2 hours the client closed itself 2 times.

**Comment by Nightfirecat** [comment]
Are there any files aside from `client` and `launcher` log files in that directory? Maybe a `jvm_crash` file?

**Comment by dekvall** [comment]
I am closing this, if the problem persists and you have information to add feel free to reopen the issue.
