### ISSUE TITLE
Add spicy stews to item stats plugin

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1052]
Would be nice if it would show the possible boosts you could get from eating a spicy stew, based on how many spices you put in it. Mechanics are on the wiki, http://oldschoolrunescape.wikia.com/wiki/Spicy_stew

**Comment by Kamielvf** [comment]
You can't know from the item how many spice has been put in it though, you'd have to track the user's actions and then based on those display the possible boosts. Seems kind of unnecessary work for an item that's not used as much.

**Comment by ShaunDreclin** [comment]
Yeah if there's no way to tell what spices have been used without manually tracking it, might not be worth the effort.

**Comment by SoyChai** [comment]
If nobody else takes this on, I might use it as an excuse to make some progress in Recipe For Disaster. I haven't looked into the items API but I'm convinced that there'd be some metadata which can assist with this. We'll see if I'm wrong.

**Comment by SoyChai** [comment]
@SomeoneWithAnInternetConnection and I figured this one out, no tracking required ;) Shouldn't take long to add a tooltip listing the affected skills.

**Comment by SoyChai** [comment]
This is resolved by #1088 now. 🍵
