### ISSUE TITLE
Add tree markers to woodcutting plugin

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1053]
Nice little feature that osbuddy has to mark the trees you want to cut down so they're easier to tell apart at a glance.

**Comment by rune3132** [comment]
Also, the dense essence rocks mined when Zeah runecrafting to tell the difference between to depleted rock. Furthermore, the markers are removed when your inventory is full to combat you not knowing whether or not your inventory is full when the notification blocks part of your inventory as shown in the image
![2018-03-22_04-09-14](https://user-images.githubusercontent.com/12607046/37749190-20e6c9ae-2d87-11e8-9b73-c076ae0c78ec.png)

**Comment by SoyChai** [comment]
Could you snap a screenshot of these osbuddy features for the issue thread? It'd help those of us who aren't familiar with the client (I dunno if they're paid features or not).

**Comment by ShaunDreclin** [comment]
osb just puts a little axe icon on the marked trees, I dunno if I'd want to do that or highlight the whole model. 

![screenshot](https://user-images.githubusercontent.com/5851433/37764994-76ba646e-2d99-11e8-9ac9-997027fa4ed6.png)

**Comment by ShaunDreclin** [comment]
(To clarify how it works, there's a toggle for each type of tree, so if you're chopping oaks then you toggle Oak on and it puts the axe icon on all oak trees)

**Comment by SoyChai** [comment]
Thanks, this sounds helpful and easy to use. Support!

**Comment by Juzzed** [comment]
Im currently working on this. 
I think i will PR it in a few days as its very WIP atm. 

![image](https://user-images.githubusercontent.com/25037124/39961042-5b7f4e4a-562e-11e8-8ffc-0e291ea9a743.png)

**Comment by ShaunDreclin** [comment]
Sexy! Bonus points if you make the axe icon show the axe you're holding lol

**Comment by Juzzed** [comment]
i was thinking about making an icon. but i guess thats a nice idea.

**Comment by Adam-** [comment]
#3386 adds redwood trees to the woodcutting plugin. I do not think showing any other type of tree is useful.

**Comment by ShaunDreclin** [comment]
Yew, oak, and normal trees all look similar from above. Differentiating them is useful.
