### ISSUE TITLE
Ctrl + Click while running to walk

### ISSUE THREAD

**Issue by ctnbeh** [runelite/runelite#10531]
Similar to how there’s already a run feature of Ctrl + Click to run while walking.

**Comment by Alexsuperfly** [comment]
I believe this would fall under the `Allows you to prioritise the walk-here option by holding a certain key, or similar` feature that jagex has explicitly said not to do in their [statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1)

**Comment by abextm** [comment]
The entry in the jagex statement is about reordering the `Walk here` option to the top of the menu. This is not that.
Duplicate #10028
