### ISSUE TITLE
Quick-enter : Enter menu swap in ToB doesn't work with some configurations

### ISSUE THREAD

**Issue by l2-** [runelite/runelite#10553]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Quick-enter : Enter menu swap in ToB doesn't work with some configurations.

**To Reproduce**
Have the Home swap set to Home and the Quick Pass/Open/Start/Travel set to true.
Expected: Quick-enter becomes the top menu entry for the door to go to the next room in ToB.
Actual: The swap isn't performed and Enter is still the top menu entry.

**Comment by melkypie** [comment]
Could you take a screenshot of the ToB next room door with the menu open?
