### ISSUE TITLE
Improve the POH bookcase usability

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#10552]
The POH bookcase is sometimes useful to withdraw a book you need or want, however it is very painful to navigate, since 1) the book titles are not even alphabetically sorted and 2) the titles in the bookcase are sometimes different from the item names, e.g. the item "Translation book" I wanted to withdraw for mm2 is called "Gnome-English translation dictionary" in the bookcase. I suggest two solutions:

1. (preferred) Add a search filter to the book case, similar to seach filter of the quest list. It should probably search in both titles and respective item names.
2. Add a "sort-by-alphabet" button to the bookcase interface.

**Comment by abextm** [comment]
This isn't possible because the client only knows about 4 books at a time; pagination is done on the server. You can also just search the wiki for the book, it has transcripts of all of them
