### ISSUE TITLE
Hotkey for ground item + and - box is the same as one to rotate screen (Mac)

### ISSUE THREAD

**Issue by Caia-OSRS** [runelite/runelite#1055]
The option key on Mac is used to rotate the screen with the mouse. Since the update today the option key defaults to showing the + and - box and does not allow you to rotate the screen. Is it possible the hotkey could be changed to command?

**Comment by ShaunDreclin** [comment]
Can you not hold alt/option and drag with right mouse to rotate the screen?

**Comment by deathbeam** [comment]
There is bug currently that consumes the mouse event all the time in ground items, so prevents ypou from moving camera around :d

**Comment by sethtroll** [comment]
Fixed in #1096
