### ISSUE TITLE
Menu Entry Swap for NPC Contact

### ISSUE THREAD

**Issue by Borgiie** [runelite/runelite#10567]
Would it be possible for a menu entry swap for NPC contact, so it contacts your previous NPC on left-click insted of having to right-click for previous NPC?

Thanks

**Comment by Adam-** [comment]
Yes. It would probably be best to make it shift-click similar to how we swap the teleport destinations.

**Comment by Borgiie** [comment]
Okay thank you, also with the new options added today to eat/drink in bank interface, could we possibly get shift click options for these? Aswell as filling essence pouches?

**Comment by Hydrox6** [comment]
That is a separate issue, both of which have already been created.

**Comment by DADtheMaggot** [comment]
I don't know if this is the best place for discussion, but can I ask your reasoning for making this a shift-click?
