### ISSUE TITLE
Shift click MES for equipping items in the bank. 

### ISSUE THREAD

**Issue by Jawnb64** [runelite/runelite#10572]
**Is your feature request related to a problem? Please describe.**
Right clicking from the bank interface to equip items is pointless since its faster to just close the back and left click equip. 
**Describe the solution you'd like**
Adding an MES to shift click equip would add actual utility to the option.

**Comment by dekvall** [comment]
Added in 4845560cb8f7b735ea4fd5ca0f8a0336d9f1d3b9
