### ISSUE TITLE
Support for templeosrs.com

### ISSUE THREAD

**Issue by JorisvanRoy** [runelite/runelite#10578]
Templeosrs is a improved version of cml and is getting more popular among the high pvm clan, would love to automatically see my stats update like with crystal math labs

**Comment by Adam-** [comment]
This would probably be good for an external plugin. We've been talking about moving the CML plugin to an external plugin to try and dis-associate with them some since they've started serving advertisements for RWT which is not so great.

**Comment by dekvall** [comment]
At least as of now, Templeosrs is not serving any rwt ads and i think that having this plugin in the client by default would further incentivize migrating away from cml. That said, I don't know what their plan is and it looks like they are just starting out. So maybe we should hold off on this for the moment until they have an api set up and we have talked to them to see if this is something they want.

**Comment by Alexsuperfly** [comment]
added in 553e56862927f8591fd37ad3e86425e640b23eaf
