### ISSUE TITLE
League Points module for hiscores in the latest update uses shortened values

### ISSUE THREAD

**Issue by SweetAzu** [runelite/runelite#10574]
![image](https://user-images.githubusercontent.com/59693883/72069679-fce63180-32e7-11ea-9ac4-1cf427de549e.png)

As of the 09/01 runelite update, the League Points listed in the hiscores sidebar uses shortened values (21k) over full length (21580) and doesn't show any exact values when hovered either.

**Comment by Adam-** [comment]
I've added it to the tooltip.
