### ISSUE TITLE
Option to exclude items from total bank value

### ISSUE THREAD

**Issue by chanmioo** [runelite/runelite#10585]
Would it be possible to see an option added to the “Bank” plugin to exclude items from the total GE bank value?
Right now it includes untradables like imbued items, falsely inflating your true bank value.

Suggestion: it could work similarly to hiding select ground items and they would appear in a list on the bank plugin panel.

**Comment by dekvall** [comment]
The bank value is not "falsely inflated", it's what you would get if you un-imbued your rings and sold them. It works as intended and I don't think that this is something that should be implemented.
