### ISSUE TITLE
Select bosses to show/hide in player lookup

### ISSUE THREAD

**Issue by zombiezrule** [runelite/runelite#10580]
As title says, would be nice to select certain bosses to show/hide the KC of when doing right click -> lookup on a player.

**Comment by dekvall** [comment]
I don't think the list of bosses is large enough to warrant being able to hide entries. You can easily just ignore the particular fields that you are not interested in. It also wouldn't make sense for a Hiscore lookup function to not show the entirety of the Hiscores of the player you are looking up..

**Comment by Nightfirecat** [comment]
In the same way that we are not interested in hiding certain skills of a player when looking them up in the hiscore panel, I don't see any reason to hide certain boss kill counts in this way.
