### ISSUE TITLE
Hiscores Lookup Not Working!

### ISSUE THREAD

**Issue by justinsorders** [runelite/runelite#10592]
The majority of the time now when you right click a player and click lookup, the hiscores stats never show up. It's just shows a red circle with a white exclamation point next to the name you lookup, like they don't exist (even though you're right clicking the player and clicking lookup lol)

Is this being worked on?

**Comment by Hydrox6** [comment]
This is not a RuneLite issue; this is due to Jagex's servers being incredibly laggy and broken since the release of Boss Hiscores. This only affects normal hiscores; Ironman and League hiscores are fine.
