### ISSUE TITLE
Real-Time Language Translation Plugin

### ISSUE THREAD

**Issue by D-uncanClark** [runelite/runelite#10591]
**Is your feature request related to a problem? Please describe.**
i saw a comment regarding the recent Venezuela vs RoT incident about us having to learn spanish to assimilate into the new OSRS community. Someone offhandedly mentioned a translator, which i though is a great idea as i frequently see people speaking their native tongue's from around the world.

**Describe the solution you'd like**
Plugin for real time translation of the game chat (player messages, private messages).

**Describe alternatives you've considered**
learn like 8 new languages
alt tab to google translate and try and type in what they typed in minus the fancy letters
ignore them

**Additional context**
everything is already in english, except player input stuff (names, chat) you could also put a little (xxxxx) after their osrs name showing if any of the words in it mean stuff in other languages. It would also be sick if we had the option to translate to a language while typing for speaking with people not using the client (dropdown menu or something)

**Comment by sanderhelleso** [comment]
This sounds like a very nice feature to have.

**Comment by SieBrum** [comment]
#5895 might be better as an external plugin though.

**Comment by Graviton1647** [comment]
This could be added fairly easy the issue is that with osrs text they only have normal characters no special characters so for some languages would be hard to support it, also the issue is with interfaces most are made to fit a certain with of characters

**Comment by Adam-** [comment]
This could maybe work as an external plugin, though I'm not sure of any translation services where it wouldn't be a TOS violation for us to have this?

**Comment by D-uncanClark** [comment]
> This could be added fairly easy the issue is that with osrs text they only have normal characters no special characters so for some languages would be hard to support it, also the issue is with interfaces most are made to fit a certain with of characters

original suggestion was just with chat in mind, which already has wrapping for long messages as i wasn't sure if changing the interface text was even something you guys can control. would be pretty cool if that would work though.

> This could maybe work as an external plugin, though I'm not sure of any translation services where it wouldn't be a TOS violation for us to have this?

https://oldschool.runescape.wiki/w/Update:Another_Message_About_Unofficial_Clients
this is just the wiki, but i did a decent amount of googling and there is no mention of anything even remotely similar mentioned.

the closest i could find is this
> Software that monitors, modifies or decrypts the communications between our game applets and our game worlds.
from here https://www.runescape.com/game-guide/rules
but that is clearly regarding memory scanning/packet sniffing and injection.

**Comment by Adam-** [comment]
I am referring to the TOS of the translation services.

**Comment by raiyni** [comment]
Polywoof translation plugin on the plugin hub does this
