### ISSUE TITLE
Add a location to General Bentnose Cryptic Clue

### ISSUE THREAD

**Issue by Notn0t** [runelite/runelite#10602]
**Is your feature request related to a problem? Please describe.**
The General Bentnose Cryptic Clue does not include a location, unlike many other clues.

**Describe the solution you'd like**
Add a description of his location to the solution.

**Additional context**
![](https://cdn.discordapp.com/attachments/442492468307427330/666723448642600981/unknown.png)

**Comment by Nightfirecat** [comment]
Does this not bring up a location on the world map? I agree we can improve the solution text, but there should be a location marked on the world map when opened.

**Comment by Hydrox6** [comment]
Just checked the file, it does have a WorldPoint associated with it, so it should have a world map marker. Still, a location in the overlay would be useful, to bring it in line with other cryptics

**Comment by Notn0t** [comment]
From what I've experienced, It does not show a location on the world map, I had to manually search for it and find it on wiki. I think it because it's in an instance or cave. The location or arrows for that matter (from what I can tell) only pops up when u are inside either the instance or the cave

**Comment by Hydrox6** [comment]
Bentnose is not in a cave, he's just in a house north of Falador. There should be a pointer over him when the clue is active

**Comment by Notn0t** [comment]
Isnt it an instance?  So the marker will only appear when u enter?

**Comment by Hydrox6** [comment]
![image](https://user-images.githubusercontent.com/2979691/72384464-71203b00-3715-11ea-92e3-182468dc240f.png)
Not an instance

Also can confirm that there is a world map arrow
![image](https://user-images.githubusercontent.com/2979691/72384372-40400600-3715-11ea-9753-789abfa6db0f.png)
