### ISSUE TITLE
Remove 'remove' option from POH furniture when not in building mode

### ISSUE THREAD

**Issue by JacoboMoral** [runelite/runelite#10617]
**Is your feature request related to a problem? Please describe.**
There is no need to have the remove option on every furniture piece in your POH when not in building mode. It just adds visual clutter to the right click menu. in my opinion.

**Describe the solution you'd like**
The solution would be to remove the 'remove' option from the menu when it is not needed (i.e. when not in building mode)

**Comment by Nightfirecat** [comment]
[Jagex's latest third-party clients statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1) has an explicit section regarding construction menus. While I don't think the spirit of this entry would be broken by hiding the "Remove" entry, we would rather not push the envelope in this regard.

> Modifies menu options for construction, such as prioritising build/remove options

**Comment by JacoboMoral** [comment]
While I think this issue has very little to do with Construction, since the change would only ve visible outside building mode, I understand the policy of not taking the risk. Thank you very much for your time :)
