### ISSUE TITLE
Add ability to refresh the Plugin Hub

### ISSUE THREAD

**Issue by loldudester** [runelite/runelite#10610]
Currently (afaik) the Plugin Hub only refreshes when you re-launch the client. It's a minor QoL thing but it'd be nice to be able to refresh it in-client to grab plugin updates and new plugins.

Could be a manual refresh or happen automatically (on an interval or when you open the hub menu).

**Comment by while-loop** [comment]
Seems as this request was already implemented. F5 refreshes the hub.

https://github.com/runelite/runelite/blob/f2d7515ff3a93f17d1543a93a52182420a69e1f6/runelite-client/src/main/java/net/runelite/client/plugins/config/PluginHubPanel.java#L349

**Comment by abextm** [comment]
it also refreshes if you just leave it and reopen it
