### ISSUE TITLE
corrdinate clue, south of elf camp

### ISSUE THREAD

**Issue by zemtehweeb** [runelite/runelite#10626]
elf camp was changed into Iorwerth camp a little while back but this master step clue is still south of elf camp

**Comment by VukAnd** [comment]
forgot something?
![image](https://user-images.githubusercontent.com/46850780/72774226-118cc880-3c0a-11ea-9a94-ef8c733cf523.png)

**Comment by dekvall** [comment]
There's currently three coordinate clue hints referencing "Elf Camp" and it would be great if whoever takes care of this issue addresses all of them.

**Comment by Adam-** [comment]
There are also 2 other hotcold ones as I mentioned here https://github.com/runelite/runelite/pull/10633#issuecomment-578535772
