### ISSUE TITLE
Loot tracker resets on each new session

### ISSUE THREAD

**Issue by Huww** [runelite/runelite#10624]
As of yesterday the loot tracker keeps resetting each time I close my runelite client. I have also logged into my account on the website and my previous loot is all gone too. I have all the correct settings enabled and am logged in to my runelite account when playing.

**Comment by Adam-** [comment]
The tracker data was reset due to #10590 recently, but it should not be losing any new drops across restarts. Do you have logs of it not able to load on startup?
