### ISSUE TITLE
True Widescreen for Static Window (AMBITIOUS)

### ISSUE THREAD

**Issue by Godric777-OpenRSC** [runelite/runelite#10627]
This feature request is not essentially problem, but rather an extremely ambitious suggestion to improve what we currently have for aspect ratios and display.

We have two displays for OSRS: Static and Expand.

Static is the original UI for RuneScape 2, and typically better designed for gameplay when it comes to PVM and PVP (because the UI is more compact and situated with the game screen.

Expand is when the client allows you to stretch the window to any aspect ratio you like, taking up as much of the screen as you want. This display option more or less is used for mobile as well, as it allows you to collapse parts of the UI (dialogue and menu).

All OSRS YouTubers (probably 100% or at least 99%) and record OSRS in static mode and stretch the picture so it takes up the full screen in a sort of 16:9 stretched widescreen display. This causes a stretched effect, causing models and really everything in within the client to be stretched and not be shown in their true aspect ratio.

This is not really  a big deal at all, I know. No one truly cares, and it really is hardly noticeable. However, it would be impressive if someone were capable of making it so you could play OSRS in Static mode using True or Forced Widescreen 16:9. I am sure that demand for this is close to no one, and it really is NOT necessary. I understand.

**However** I would be awesome if someone could figure out a why to redesign or shift the existing static UI so the game screen could be enlarged to take up the remaining space. Keeping the Static display in true widescreen. It would be really nice if future OSRS content were recorded in this theoretical true widescreen.

I understand that a project like this would be very ambitious and to be honest probably not possible. Or perhaps it is possible but a developer would need to do one of the two things (as far as I know):

1. Edit the existing UI that surrounds the game screen and expand it in an accurate way that will proportionally fit any widescreen/16:9 display.

2. Expand the existing game screen in static mode without stretching or compressing the 3D graphics to dimensions that will fit to a 16:9 display without distorting or damaging the existing static UI.

I am not a visual artist or designer myself so it is very difficult for me to give any more specific logistics than that. However, I would love to see this idea brought to fruition, and with a ton of hard work and dedication I am sure it would be possible. From where I am standing right now though, it sounds like an extremely challenging project.

Despite that I still wanted to throw the idea out there.

Additional Context:
When recording a static OSRS client window with OBS, if you center the window within OBS and DO NOT stretch the window to fill the widescreen space, you will have black bars on both sides. This is similar to playing a 4:3 movie or show on a widescreen display (for example, playing an old console on an HDTV). By NOT stretching the OSRS client you are recording the game in it's true aspect ratio. The basis of this idea is to find a way to alter the currently existing static mode so it can match an aspect ratio of 16:9 without stretching both the UI or 3D models of the game.

**Comment by abextm** [comment]
Use resizable mode + the stretched mode plugin with a high enough scaling factor
