### ISSUE TITLE
Shift click

### ISSUE THREAD

**Issue by Alex-alt-ops** [runelite/runelite#10634]
It would be nice if we could shift click and the bank option would change to all.

**Comment by WesleyM77** [comment]
Duplicate of #10612 which currently has a pull request in.

**Comment by Alex-alt-ops** [comment]
What is a pull request ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by WesleyM77** [comment]
@Alex-alt-ops A pull request is a request from a contributor to a repository to approve their changes and allow the integration of their changes into the repo's codebase. Basically, in this case there's a pull request that is waiting to get merged that already addresses this request.
