### ISSUE TITLE
Wasd camera bug

### ISSUE THREAD

**Issue by sanobrewww** [runelite/runelite#10635]
After the update, if you use your camera normally and then attempt to chat it will spam your chat with "aaaaaaddd" or whatever it is that you pressed, for the amount of times you have pressed it. So if I just hold A and press "enter to chat" as normal it will literally spam my public chat with "Aaaaaaaaaaaaaaaaaaaa."

**Comment by wintershine** [comment]
This also happens with remapped F-keys. When you have a full message, your chatbox turns into this: https://i.imgur.com/qaHNRSf.png

**Comment by dekvall** [comment]
Fixed in 05f2117b8f60026b7822129c7777246e3b4b2976
