### ISSUE TITLE
Allow users to rearrange plugin icons on RuneLite sidebar

### ISSUE THREAD

**Issue by JacoboMoral** [runelite/runelite#10648]
**Is your feature request related to a problem? Please describe.**
I don't really like that you can't rearrange (AFAIK) plugin icons on RuneLite sidebar.

**Describe the solution you'd like**
I would like to be able to rearrange the icons dragging them, having two options: **swap** and **insert**.

**Comment by Nightfirecat** [comment]
Duplicate of #783
