### ISSUE TITLE
Save current camera angle to compass

### ISSUE THREAD

**Issue by Aksu1** [runelite/runelite#10651]
Right click compass to save current camera angle and when you click the compass it would make your camera face to that preset (currently it makes you camera look north)

**Comment by Graviton1647** [comment]
I like this idea... Could also just make it save and load on login / logout

**Comment by Graviton1647** [comment]
> Right click compass to save current camera angle and when you click the compass it would make your camera face to that preset (currently it makes you camera look north)

Hey have made it save your last camera position on logout and load back in :) ill be making a request to add it tonight

**Comment by mistcurve** [comment]
Does saving on logout and putting it back on login reflect what was asked? To my understanding it meant more so that you could change the behavior for when it is left clicked to be the saved position.
