### ISSUE TITLE
Developer On-boarding Reference Material

### ISSUE THREAD

**Issue by CreativeTechGuy** [runelite/runelite#10660]
**Is your feature request related to a problem? Please describe.**
When a new developer, like myself, is trying to contribute to the codebase, it's difficult to discover how the project is architected and how new things can be added technically.

**Describe the solution you'd like**
I'd like more wiki pages which detail some of the core aspects of the codebase and architecture. For example, most of the methods defined in Interfaces are never implemented anywhere so I have to assume this is implemented in the base runescape-client (which we cannot see). So a guide on how to add/find new methods to add to these base interfaces would be useful.

On that note, a guide about how this codebase interacts with the core Runescape client's code. Where/how does this codebase download the updated Runescape jar? What is the process for decompiling and reverse engineering it? How does the code written in this package interact with Jagex's code? Etc. Maybe a diagram showing how all of the pieces are wired together would answer a lot of these questions.

It's fairly easy to use data which is already being used by another part of Runelite, but when trying to build something entirely new, there is no information on how to go about doing that.

**Comment by Adam-** [comment]
We have an informal agreement with Jagex to not release most of the reverse-engineering code & documentation anymore, you can read the backstory of that if you check our blog/their news posts from May 2018. I've also taken down some other parts of it due to people overwhelmingly using it to cheat instead of to play the game. I don't think we plan on changing this anytime soon.

**Comment by CreativeTechGuy** [comment]
What would you recommend to new contributors to learn about the project so they can contribute? It seems like there's a lot of knowledge that's only held by a few people who were around before this change and now it's very difficult to get the whole picture.

**Comment by Trevor159** [comment]
Looking at plugins similar to what you want to do is a great way to learn. Also the discord has a channel to ask any development questions you have that you cannot find yourself.

**Comment by Alexsuperfly** [comment]
I've honestly never needed to know any of the info that is now hidden, at times looking at it gave ideas to how it worked, but seeing it in use inside other plugins has always been enough for me.  After that the development channel in discord is very helpful with any questions.

**Comment by Hydrox6** [comment]
The stuff in `internal` is either direct references to stuff in the Jagex client, references to the Jagex stuff with functions to convert the data into a more sane format, or hooks that run the events. The stub API functions are named sensibly (for the most part), and they have docs explaining what they do.

**Comment by Adam-** [comment]
> 
> 
> What would you recommend to new contributors to learn about the project so they can contribute? It seems like there's a lot of knowledge that's only held by a few people who were around before this change and now it's very difficult to get the whole picture.

Most people who contribute to RuneLite add or extend existing plugins, and since we have an established and somewhat-documented API (especially so just by referencing existing usages of the API) they are able to do so easily with that layer of abstraction.

As others have mentioned also #development on discord is a good resource too.

What is it you are trying to do?

**Comment by CreativeTechGuy** [comment]
@Adam- Here's a few examples of things which I recently tried but got stuck due to lack of architecture understanding.

* Allowing the camera to clip through objects. So it'd be like the opposite of `relaxCameraPitch`. It'd be useful in situations where you are backed up against a large mountain and the game stops you from moving the camera down so you are stuck at a steep angle. It'd allow the camera to go inside of the mountain and see through the geometry. I tried looking how the other camera modifications were created but couldn't trace the code as it's likely not in this codebase.
* Creating a "remember me" functionality for logins similar to mobile. So once you sign in with your username and password it'll save your account information to your OS' password manager. I couldn't figure out how to add to the `Client.java` interface to get a `getPassword()` method.
* Writing Grand Exchange transactions to a local file/database so you could export them from the game and perform analysis on your entire history. I couldn't find much information on how to get data from the network or read text off of a native UI.

Some of these things I might be able to figure out if I just struggle for much longer. But I know it'd be very useful to have some more explanation and documentation that I could refer to when trying these things. I get the fact that a lot of code cannot be published in this repository anymore. But what's the difference of giving someone this codebase and asking them to re-derive how you got here, or explicitly explaining how this code got to where it is today so other people can get up to speed faster.

I know many people don't care about the low level stuff. But understanding how this code and the Runescape code works together and technically how it's "injected" or "build" would be useful for people who want to try new things without examples.

**Comment by abextm** [comment]
1) This is very difficult, and requires internal access
2) ditto, or requires storing the password, which we will not do
3) the ge plugin already knows how to get this data, just look at that

So the first two we won't document for already mentioned reasons and the last one has code that you can use as reference.

**Comment by habibalamin** [comment]
Doesn't `getUsername()` return the username typed by the user into the login screen? A `getPassword()` method that gets the password typed into the login screen wouldn't need to store the password, it would simply get it from the process' address space.

This would be really useful for integrations with password managers; subscribe to `onUsernameChanged()`, fetch the password for that username from the password manager and `setPassword()`, and if none exists, `getPassword()` `onGameStateChanged()` when the `GameState` is `LOGGING_IN` (or successfully logged in).

Right now, we can do the first half of this, but the user has to manually create an entry in the password manager (or have an entry created from logging in with the browser) and give RuneLite permission to access that entry.
