### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by gemy244** [runelite/runelite#10666]
my runelite client everytime i log on it it gets me a black screen i  hope u can help me
![osrs](https://user-images.githubusercontent.com/60330392/73143647-5fd81680-40a5-11ea-9aea-2b6cb7e2fc92.png)

**Comment by Graviton1647** [comment]
This is not for support

**Comment by Nightfirecat** [comment]
Please [join the `#support` channel of our Discord server](https://runelite.net/discord) to get help running RuneLite. Thanks!
