### ISSUE TITLE
Expand individual items in loot tracker when minimized

### ISSUE THREAD

**Issue by ws-volt** [runelite/runelite#10661]
When having all items in the loot tracker minimized, it would be nice to be able to just expand individual ones rather than having to fully focus one, allowing you to have just a few open at a time.

**Describe the solution you'd like**
Small dropdown arrow on each loot tracker item when they are all collapsed to expand individual ones. 

**Describe alternatives you've considered**
N/A

**Additional context**
Ill try do this myself at some point, but if anyone feels like doing it then great ;)

**Comment by Hydrox6** [comment]
This is already a feature though?
![](https://user-images.githubusercontent.com/2979691/73140169-ba558080-406d-11ea-9258-962f5ef8aae0.png)

**Comment by ws-volt** [comment]
yea cool im very stupid lets pretend you saw nothing here and move on thank you.
