### ISSUE TITLE
Add open container items as variations of their closed versions

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#10669]
In recent updates, Jagex added the ability to open the Seed box, Herb sack, Coal bag, and Gem bag much like the ability the Looting bag has had for some time. These items should be added as variations of their closed versions so that inventory tags, bank tags, etc. are maintained for both versions.

**Comment by DeliciousLunch55** [comment]
Though I haven't seen a linked pull request for this, it appears to be done.  Item IDs for the open versions of the items you mention are in the master branch.

**Comment by Nightfirecat** [comment]
It still seems to be missing the herb sack and seed box, but does contain the coal bag and gem bag.

**Comment by abextm** [comment]
Fixed in 9c90c0931c65abd6fc63a0a09c38b77a9e7c54dc / https://github.com/abextm/runelite-cache-code-updater/commit/a35c71c49e5277e037c7c9979d38e2fb7ed3c65f
