### ISSUE TITLE
!lvl targeting

### ISSUE THREAD

**Issue by BMatze** [runelite/runelite#10668]
Hiscores are down a lot, the !lvl function may be to blame. Using !lvl in a dense area can cause a large number of requests to the hiscore server. 

Consider adding conditions you can add to the level command[and alike] to reduce the number of requests that are sent. Prevent it's function in heavily populated areas, or use a server of your own to prevent a DOS attack on the hiscore server. I am unsure if you cache the retrieved values at all, but doing so can really reduce the impact on the server. 

Potential conditions to implement
- Distance from source
- Clan
  - clan:recruit
  - clan:recruit+ 
  - clan:member
- name [name1,name2, name3]
- level >x (the >, =  or < does a local check on the player, will only send if the skill queried meets the condition
`!lvl smithing [name1]
!total clan:all -if they are in a cc with you they send the request
!lvl fishing >90 - anyone over 90 fishing sends the request`

**Comment by abextm** [comment]
If our requests are causing high enough load on Jagex's servers for it to be a problem (which it isn't) they know how to contact us.
