### ISSUE TITLE
Add counter to RC pouches to show when they will degrade.

### ISSUE THREAD

**Issue by Dynasty2424** [runelite/runelite#10673]
This will save a lot of time for people running with Giant Pouch. You need to repair your pouches frequently but dont know exactly when to do it. When a pouch degrades, you have to put more ess in it after repairing. It would be really useful to know when it will degrade so I can repair it 1 use before it degrades.

This feature is already happening on other items in the game such as Binding Necklace and Ring of Dueling. I feel RC pouches should get this same feature.

**Comment by dekvall** [comment]
Duplicate of #1007
