### ISSUE TITLE
Annoying Idle Notifier

### ISSUE THREAD

**Issue by FuryFight3r** [runelite/runelite#10672]
This is a great feature, however while using this on an alt account and playing on main, having the window forcefully open and cancel my typing, or in risky situations is so frustrating. I Love the idea that it 'bings' and lets me know im idle and no longer wc'ing or fishing for example, but why does it have to pop the window open to cover my current playing window, please implement a toggle to turn this intrusive part of the feature off.. Again having it 'bing' and flash the application in the task bar is fine, but having it open in my face usually in the worst possible times is so frustrating, even had to click back to this window a handfull of times just to continue typing out the issue.

**Comment by Dahje** [comment]
I just came on here to request the same thing. It can be handy, but sometimes I am afk while doing actual work and don't want to be interrupted so forcibly. A notification should be just that, a notification, not forcibly grabbing the screen.

**Comment by JourneyOver** [comment]
There already is a toggle..

Go into runelite settings panel, disable "Request focus on notification", done. It will no longer request focus whenever you end up idling.

**Comment by Dahje** [comment]
This maybe isn't the best place to have it, it might be better off to have the toggle in the actual idle notifier plugin configuration. I am however quite happy that I can toggle it off regardless.

**Comment by WesleyM77** [comment]
@Dahje it's probably the best place for it since there are other plugins that generate notifications. Though maybe having the setting on a per-plugin basis would allow for more control.

**Comment by FuryFight3r** [comment]
> There already is a toggle..
> 
> Go into runelite settings panel, disable "Request focus on notification", done. It will no longer request focus whenever you end up idling.

After just about finishing up typing a comment saying I couldnt find it and had many screenshots showing this, but I found it.. That seems a rather silly spot to hide a very instrusive feature, my first guess would be that it would be within the Idle Notification Settings, I had never been through the RuneLite Settings and honestly thought you were just talking about Clicking the spanner (Configuration) when you said RuneLite Settings, but eitherway I'm happy you pointed me in the right ddirection, Cheers that will save a lot of frustration.
