### ISSUE TITLE
Add ability to close world map with ESC

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1067]
Possible features:

- Esc to close map
- ~~Fairy ring codes on map (#902)~~
- ~~Agility level and diary requirements for shortcuts on map~~
- ~~Clue scroll locations~~

**Comment by MESLewis** [comment]
I am going to investigate adding custom tooltips, custom map markers, and clue scroll locations to the Jagex world map. I was intending to make our own full featured world map to replace the Jagex map but the Jagex map has more features than I realized and it would be significant work to reimplement those features.

I'm not very interested in either
 A) Recreating various Jagex map features to make our current map have feature parity to replace the Jagex map.
 B) Creating our own map with it's own feature set, leading to 2 world maps with some overlap in features and inconsistent behavior.

Someone is welcome to pick up work on expanding the current instance map. My original plan is not going to work out and I would rather not put in the time if it isn't going to be work I will be proud of.

**Comment by ShaunDreclin** [comment]
Yay! I'm good with getting it either way but my preferred approach would be using the vanilla map and adding to it, since the vanilla map really does have a lot of functionality.

**Comment by MESLewis** [comment]
#2064 fixes 'Clue scroll locations'

I'm working on 'Fairy ring codes on map'. There are a few issues to figure out first but it's coming.

**Comment by nmq12** [comment]
It would be nice if there was a button to zoom straight to where the clue is on the map. In addition, coordinate clue should also include who you would need to fight.

**Comment by MESLewis** [comment]
You can click on the drawn overlay and it will center the map there

**Comment by deathbeam** [comment]
http://services.runescape.com/m=news/deadman-experience-cap-increase-and-quality-of-life-changes?oldschool=1 :tada:

**Comment by ShaunDreclin** [comment]
Wooo!
