### ISSUE TITLE
Item stats for absorption potions

### ISSUE THREAD

**Issue by lukasfehr** [runelite/runelite#10675]
It would be nice if absorption potions could have a popup similar to the existing popup for regular potions from "Item Stats".

It could tell you how many absorption points you will have after you drink the dose, and it could similarly be green if all 50 absorption points will be applied and yellow if you will reach the 1000 cap.

Ex: 
(green) +50 (800) Absorption
or
(yellow) +30 (1000) Absorption

This would be useful for efficiently checking absorption points when using remote desktop to afk at nmz.

**Comment by Mynuber** [comment]
You can only drink an absorption dose when it can be fully added to your total

**Comment by lukasfehr** [comment]
Ah. Guess I never tried it lmao
