### ISSUE TITLE
Missing login method

### ISSUE THREAD

**Issue by PolyFlower** [runelite/runelite#10674]
So I wrote little plugin that sets username+pass and selects server from config, but I'm missing how to press login button via methods
Any idea?

![clown](https://user-images.githubusercontent.com/34143071/73213140-b9e9e200-4160-11ea-8653-bfb38793cd08.gif)

**Comment by Hydrox6** [comment]
The issue tracker is not a support board.

For further questions of support, please join the [Discord](https://runelite.net/discord)
