### ISSUE TITLE
Hide  Attack Option

### ISSUE THREAD

**Issue by xbpayx** [runelite/runelite#10686]
Would be nice to have a plugin or it be added to another. The ability to hide the "Attack" option of certain enemies such as abyssal monsters in the abyss, etc

**Comment by dekvall** [comment]
This falls under `Removes or deprioritises attack, cast (or similar) options from the minimenu in any scenario` which is behaviour explicitly [rejected by Jagex](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1).
