### ISSUE TITLE
Inventory grid not handling dragged items properly

### ISSUE THREAD

**Issue by dekvall** [runelite/runelite#10696]
When overlays were updated to follow dragged items, it had unintended effects on the inventory grid plugin.
 - The grid square that previously appeared in the item's original place now follows the item
 - There is now a green box following the dragged item which previously only indicated where the item would be placed if the `Highlight background` config is turned on.
 - The `Show Item` config now doesn't replace the sprite in the original position when hovering over another item in the case of a swap.
![inventory-grid-follow](https://user-images.githubusercontent.com/25151927/73477514-b3dc4700-4394-11ea-9d6d-53fe10736983.gif)

**Comment by Adam-** [comment]
fixed in cda92a18dc74af087a7e66b916a5a4d512a0911d
