### ISSUE TITLE
Fake runelite download link

### ISSUE THREAD

**Issue by jalwin** [runelite/runelite#10703]
I don't know how to or who to talk to but watch out there's a fake runelite website 

https://runelite.wiki

if you google runelite its the third result

**Comment by dekvall** [comment]
We are aware. It has been reported to both Namecheap & Google but so far no action has been taken. You can try reporting it too i guess, they might care if enough people do. Meanwhile, let's not give them more publicity than they already have. Thanks for reporting this though!
