### ISSUE TITLE
ImageUtil.getResourceStreamFromClass does not log attempted path if load fails

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#10708]
As it currently stands, the method will (after a lengthy set of stacktraces) yield the following exceptions:

```
Caused by: java.lang.IllegalArgumentException: file.png
 
Caused by: java.lang.IllegalArgumentException: input == null!
```

It would be helpful to developers to print the searched path so they can more easily figure out why their images are not being loaded.

**Comment by kkozera** [comment]
Hey, I see nobody is assigned here, can I take this one?

**Comment by Nightfirecat** [comment]
Yes
