### ISSUE TITLE
Add some sort of centralized inventory/equipment system

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1070]
Various plugins behave differently depending on what you have in your inventory or equipped. Rather than every plugin scanning the inventory constantly, it'd be good if there was a single system doing it. Then to check it, you could do things like `inventory.contains(CHISEL)`, `equipment.contains(RUNE_PICKAXE)` etc.

Being able to test for all of or any of the items in an array/list/set/etc of items would be nice too.

**Comment by Nightfirecat** [comment]
This didn't end up needing any centralized system to be written for it. `ItemContainer#contains(int itemId)` fulfills this nicely and was added in https://github.com/runelite/runelite/commit/8f12c2846d45e9354e82d792ea1b06dc160de39e.
