### ISSUE TITLE
Slayer plugin forgets your points and streak

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1072]
No idea what the cause of this one is.

**Comment by ShaunDreclin** [comment]
![screenshot](https://user-images.githubusercontent.com/5851433/37826819-667c1b56-2e6b-11e8-9cb6-56966187a855.png)

**Comment by novakivanovski** [comment]
Does this happen after you login?

**Comment by ShaunDreclin** [comment]
Yeah it could be on login. It never seems to forget it during a session, it just doesn't remember what it was from the last session.

**Comment by deathbeam** [comment]
Fixed in aec908d
