### ISSUE TITLE
Search Filter

### ISSUE THREAD

**Issue by dragonboi44** [runelite/runelite#10729]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [I would like to purchase an item but i cant easily filter valuable items in my bank for me to withdraw and sell in ge to buy my tbow]

**Describe the solution you'd like**
Allow us to filter the items in the bank by X value that we may like to see show up in bank

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
Another solution to this would be to show items over 100k including stacks of items which are over 100k gp worth even though their individual worth could be -1000gp ea , say a stack of water runes

**Additional context**

**Comment by Alexsuperfly** [comment]
search `ge > ###` in the bank, works for ha(high alch) and less than symbol too

**Comment by dragonboi44** [comment]
> 
> 
> search `ge > ###` in the bank, works for ha(high alch) and less than symbol too
omg tyyyy never knew about this!
