### ISSUE TITLE
first clue completion doesnt get picked up by loot tracker

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#10730]
the current pattern for picking up a completed clue from the message in game is `You have completed [0-9]+ ([a-z]+) Treasure Trails.` however if the message is for the first one it is not plural, failing to match that pattern.

reference ![](https://cdn.discordapp.com/attachments/442492468307427330/674374557838213130/unknown.png)

**Comment by ddaltonzkd** [comment]
I'm also noticing that it says in your loot tracker that the clue you just completed was and elite clue. I'm not sure if this is already another open issue, however I am going to take a look at the code and see if I can get it done in a timely fashion.

**Comment by Alexsuperfly** [comment]
fixed in 99e885cb0ae0b4f7cf5dfc60e88e68cfdd4e5d5b
