### ISSUE TITLE
Menu entry swapper for bank all on shift click

### ISSUE THREAD

**Issue by renfc01** [runelite/runelite#10732]
Enable bank-all/secondary banking on shift click 

**Describe the solution you'd like**
While holding shift and clicking a stack of items in the inventory it would deposit all off the stack into the bank. (swapping deposit 1 with deposit all)

This would help when managing lots of items quicker.

**Comment by Bram91** [comment]
This has been implemented in #10631 and can be found under the 'Menu Entry Swapper' plugin settings.
