### ISSUE TITLE
Tick Counter

### ISSUE THREAD

**Issue by BizzTime** [runelite/runelite#10749]
Would it be possible to add a tick counter plugin that shows the combat ticks of each player in a raid for example? I know many other third party clients have this but I'm not sure why RL doesn't have it because I think it's a brilliant plugin and offers no 'advantage' or 'cheat' just a bit of information that will hopefully help you improve your gameplay :) 

Thanks in advance,

Mike 

![FC9wp9s2QJCls3pe5GjmNg](https://user-images.githubusercontent.com/36641108/74086091-8029ad00-4a77-11ea-809d-6acda3f0b167.png)

**Comment by BizzTime** [comment]
Any news on whether this will be a thing or not?

**Comment by Dyldozer** [comment]
I believe https://github.com/devinfrench was the original creator.

**Comment by BizzTime** [comment]
So wish this was made, having to use other clients instead of RuneLite for now :/

**Comment by basicDamen** [comment]
I’ve been working on a more advanced option of this, but once I finish it, I will release the simplified version of it to RL as an external, if it’s desired.

**Comment by abextm** [comment]
This is now in the plugin hub
