### ISSUE TITLE
New Hard Clue step missing from Clue Scroll plugin

### ISSUE THREAD

**Issue by iawhd** [runelite/runelite#10747]
**Issue:**
A new hard clue step was added in the Nightmare of Ashihama update, To solve you need to talk to Daer Krand in the Sisterhood Sanctuary under Slepe and solve his puzzle box.

**Solution:**
Add the step to the Clue Scroll plugin

**Screenshots:**
![image](https://user-images.githubusercontent.com/29826207/74065928-e5d15700-49ed-11ea-93b3-ee884a655a0f.png)

![image](https://user-images.githubusercontent.com/29826207/74066017-2204b780-49ee-11ea-9aa3-b22816d543c5.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Build 1909
 - RuneLite version: 1.6.5
 - Launcher version: 2.1.0

**Comment by kmutchnick** [comment]
#10748
