### ISSUE TITLE
Integrated combat calculator

### ISSUE THREAD

**Issue by gasmar** [runelite/runelite#10741]
Some accounts have specific builds that require capping them at a specific cb level (eg, pkers, pures, etc.), which is usually planned out with combat stats using online calculators. Turns out, the available online calculators return different combat levels, I'm guessing because they use different formulas and round up or down.

Since RL has a solid next cb level math algorithm, it would be cool to implement a calculator that would let us calculate cb with future/desired levels, similar to [OSRS Tools](https://oldschool.tools/calculators/combat-level) for example.

It would be pretty convenient if the calculator was integrated on the side panel, similar to the skill calculator.

The reason for this request is basically that the results vary, and making an account with a single level off can screw up the entire build.

**Comment by ch4s1ngs4nity** [comment]
To tag team...

Note, this is NOT requesting a skill-like training calculator that projects how many actions are required. This is simply a calculator for your combat level. This is not issue [448](https://github.com/runelite/runelite/issues/448) and its associated [#725](https://github.com/runelite/runelite/pull/725). That solution only displays the xp required to gain 1 level in each combat skill.

**Solution**
Under the _skill calculator_ panel, add a _combat_ button (the crossed swords). In that calculator, your combat related stats will be pre-loaded in _**eitable**_ fields (could add a search to load other player stats). The calculated combat level will be displayed underneath. Then underneath the calculated level, the number of levels required to reach the next combat level will be provided for each combat skill. Similar to the setup on [oldschool.tools](https://oldschool.tools/calculators/combat-level). It also has the nice _estimate hitpoints_ toggle with the options to exclude magic |& range in estimate. Also, a _auto calculate_ toggle would be awesome so you don't have to keep clicking a _calculate_ button.

**Alternatives**
Could be pseudo-implemented in the hiscores panel. The combat related skills would be editable and update the combat level calculated. The skill progression required to hit the next combat level could be provided in a tool tip.

**Comment by crzynsane1** [comment]
It would be nice if they introduced an algorithm to calculate the last monster killed to next lvl based on monster hp for a combat skill.

**Comment by raiyni** [comment]
duplicate #6796

**Comment by ch4s1ngs4nity** [comment]
@raiyni, this is not the same as [#6794](https://github.com/runelite/runelite/issues/6796). @crzynsane1 didn't read the suggestion and his comment is a duplication of #6794. However, this was not the intent of this request. Please read the first sentence of my previous comment, it's not an "actions until level calculator," it's a fiddle with combat skill levels to calculate your combat level..

**Comment by Hydrox6** [comment]
This feature is better served by the [wiki's combat level calculator](https://oldschool.runescape.wiki/w/Combat_level#Wiki_combat_calculator) anyway

**Comment by gasmar** [comment]
The wiki's calculator rounds the result combat level up. I used it and tested it in rs and it was wrong. That's why I was asking for this feature.

**Comment by Hydrox6** [comment]
Ask them to fix it then, or fix it yourself. They're open to suggestions
