### ISSUE TITLE
Highscores not working. 

### ISSUE THREAD

**Issue by DarthMadara** [runelite/runelite#10745]
**Describe the bug**
Just as the title says, The Highscores tab is not working correctly. It acts like it can not find the player, even searching for myself. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.5
 - Launcher version: Claims to be "Unknown"

**Additional context**
I will supply logs if requested.

**Comment by Noahh16** [comment]
Jagex servers for the highscores are intermittently down, so I'm willing to bet this is an issue with that and not runelite.

**Comment by dekvall** [comment]
Duplicate of #10592
