### ISSUE TITLE
Newly spawned implings do not trigger notification

### ISSUE THREAD

**Issue by Primer81** [runelite/runelite#10750]
I've been trying to AFK at puro-puro by relying on RuneLite notifications, but I when an impling spawns within my vicinity, I do not receive a notification for it. 

It seems I only receive notifications when implings _enter_ my field of view.

This may be related to #3533

**Comment by Adam-** [comment]
It looks like the plugin does correctly have code for changed-but-not-spawned imp notifications: https://github.com/runelite/runelite/commit/cb032ab6099d7e89056241056426d37edb3ba70d#diff-f826753c83ddef705e9bd8a17ae7b682R118-R121

Are the implings properly marked when this happens?

**Comment by Primer81** [comment]
Yes they are properly marked, I just don't get a notification

**Comment by Adam-** [comment]
That's odd, I don't see any reason why it would not notify.

**Comment by Primer81** [comment]
Strange, I'm continuing to see this issue in-game. I should note that I have noticed a _couple_ of imps that triggered a notification when spawning. However, the majority I see spawn do not receive any notification.

It seems spawned imps will _sometimes_ receive notifications, but it's also very rare (in my experience).

**Comment by Primer81** [comment]
It seems there are two ways implings can "spawn". They either spawn normally like any other NPC, or they appear in a puff of smoke. RuneLite seems to properly notify when the implings spawn normally, but _not_ when they appear in a puff of smoke.

I did not notice this at first because when I AFK in puro puro, I've set it so that I only get notified when Magpies, Ninjas or Dragons appear. However, it seems these implings never spawn normally, they only ever appear in a puff of smoke.

After noticing this I enabled notifications for all implings. After doing so, I could see that I was getting notifications for implings that appear in a "puff of smoke" _at first_. However, after being logged in for a while, I _stopped_ receiving notifications for them.

I should note that I've started AFK'ing with my own build of RuneLite for debugging purposes. One thing I've noticed is that when an impling spawns in a "puff of smoke", it triggers the "onNpcChanged" callback rather than the "onNpcSpawned" callback like I expected.

After noticing this, I changed line 121 in ImplingsPlugin.java from:
`if (impling != null && !implings.contains(npc))`
to:
`if (impling != null)`
I made this change because I witnessed an impling spawn in a "puff of smoke" which triggered the "onNpcChanged" callback, but did not satisfy the condition above.

After making this change, I have yet to see an impling spawn in a "puff of smoke" that did not trigger a notification.

**Comment by king-koda** [comment]
Nice find, i had this issue 6 months ago when farming implings for my ironman, glad to hear you found a fix!

**Comment by Primer81** [comment]
My change might have consequences for the size of `implings` so the condition I removed should probably be moved to line 127 so that instead of reading as:
`implings.add(npc)`
it will read:
`
if (!implings.contains(npc)) 
{
    implings.add(npc);
}
`

**Comment by Adam-** [comment]
That's interesting. This doesn't make sense unless the implings were to spawn first as a lesser impling before changing. Do they do that?

**Comment by Primer81** [comment]
That is what I suspect yes. For example, when I had notifications enabled for all implings, I saw a few nature and eclectic implings appear in a puff of smoke which triggered notifications. Later I saw a magpie appear in a puff of smoke which did not trigger any notification. 

It seems like the impling NPC objects that appear in puffs of smoke are reused for multiple impling types.

**Comment by Adam-** [comment]
For it to be added in the first place it has to match a npc id from `Impling` which are all named, though, so I wouldn't expect it to track puffs of smoke (if those even are npcs). Can you add more logging for the spawn and despawn events and see if you can figure out what it is doing?

**Comment by Primer81** [comment]
I'm at work right now, but I can try to do so this afternoon.

**Comment by Primer81** [comment]
Okay so first I wanted to identify the in-game events that trigger each of the callbacks; namely, onNpcSpawned, onNpcChanged, and onNpcDespawned.

I observed the following when testing each callback:
- The onNpcChanged callback _only_ triggers when an impling spawns in a puff of smoke
- The onNpcSpawned callback will _always_ trigger if an impling spawns "normally"
- The onNpcSpawned callback will _always_ trigger if an impling enters your field of view
- The onNpcDespawned callback will _always_ trigger if an impling leaves your field of view
- The onNpcDespawned callback will _sometimes_ trigger if a player catches an impling

After that first test, I started logging every time one of the three callbacks were triggered. For each callback I logged the name of the imp which triggered it, the npc id, and the hash code of the npc object. For the onNpcChanged callback I added some additional logging including a boolean which told me if that impling was stored in the implings list. (Source: [ImplingsPlugin.java](https://github.com/runelite/runelite/files/4183980/ImplingsPlugin.java.txt))



The following is a snippet of the resulting log. I have bolded 3 lines for emphasis (you can find the full log here: [implings_callback_log.txt](https://github.com/runelite/runelite/files/4183910/implings_callback_log.txt))

> 2020-02-10 20:46:20 [Client] INFO  n.r.c.p.implings.ImplingsPlugin - onNpcSpawned triggered: imp_name: Nature	npc_id: 1651	**hash_code: 1809858817**
> ...

> 2020-02-10 20:49:12 [Client] INFO  n.r.c.p.implings.ImplingsPlugin - onNpcChanged triggered:
> imp_name: Ninja
> npc_id: 1653
> new_npc_name: Ninja impling
> old_npc_name: null
> hash: 0
> **hash_code: 1809858817**
> new_comp_id: 1653
> old_comp_id: 9390
> **is_in_implings?: true**

Above you can see that I have logged two events, a "onNpcSpawned" event and a "onNpcChanged" event. The first event is triggered by a nature impling either spawning normally or entering my FOV. The second event is triggered by a Ninja impling spawning in a "puff of smoke".

Now notice a few things:
1. This is the _first_ mention of a Ninja impling in my log
2. The onNpcSpawned event for the Nature impling is not accompanied by a onNpcDespawned event by the time we receive the Ninja impling event. This means that the Nature impling is still in implings list.
3. The hash code of the Ninja impling NPC object is equal to the hash code of the Nature impling NPC object.
4. According to the log, the Ninja impling was _already_ in the list of implings before the onNpcChanged event occurred.
5. I _caught_ this ninja impling and as you can see in the log, there is no onNpcDespawned event for a Ninja impling **anywhere** in the log
6. Slightly farther down in the log, you will find a onNpcChanged event for a Magpie (that I also caught) which has the same hashcode as the Ninja and Nature impling and similarly is not accompanied by an onNpcDespawned event (there are more examples of this occurring in the log)

So it seems that certain implings do not trigger a onNpcDespawned event when caught by players (I've confirmed that other implings do in fact trigger this event if caught). This leads to some NPC objects remaining in the list of implings even after they have disappeared. In addition, impling NPC objects can apparently be reused to represent different implings as is evidenced by the same hashcode (which in this case we can assume to be the address in memory) being associated with a Nature, Ninja, and Magpie impling.
