### ISSUE TITLE
Permanent object markers

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#10758]
Currently object markers will disappear after a game update, and as such all object markers get reset and you're forced to manually retag the things you want. It'd be nice if there were some preset boxes for commonly marked things to be always highlighted. I assume the reason you can't name objects (like NPCs) is to avoid abuse.

Some of the things that come to mind for preset boxes are:
- Jewelry boxes
- Mounted POH jewelry 
- Waterbirth Island Dungeon ladders (they can be kinda annoying to see the exact clickbox on some of them)

I'm sure there are a lot more good ones, but I won't bother thinking of more unless this idea is acceptable by Jagex/Runelite standards.

**Comment by Adam-** [comment]
Object markers have always persisted across game updates, although we've had some bugs in the past related to them. I've just tested this today on Jewelry boxes in the POH and it works across restarts. Reopen if this is still an issue.

**Comment by chandlerbh** [comment]
This just happened

**Comment by Unmoon** [comment]
> This just happened

see https://github.com/runelite/runelite/issues/19440
