### ISSUE TITLE
Login Crash

### ISSUE THREAD

**Issue by NugsNotDrugs** [runelite/runelite#10753]
If I login to Runelite the game freezes. I have to go into task manager to end it. Then if I try and relaunch, it usually takes me a few tries to get it to launch again so I can sign out of Runelite. Typically I will launch it but it Runelite will be unviewable or freeze my PC entirely. 

I've tried reinstalling both with 64 bit and 32 bit versions. I've looked at the logs and there are no obvious errors.

If I can manage to get it to launch to start with, and if I don't login with Runelite, I can login to osrs and play - just means a lot of features do not work for me.

Has anyone else been experiencing this issue?

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join [our Discord server](https://runelite.net/discord) for support.
