### ISSUE TITLE
Add shift+click to fill Essence Pouch within bank

### ISSUE THREAD

**Issue by IronEveStar** [runelite/runelite#10765]
As of now the shift click within the bank only allows you to wear item, consume pot/food, or withdraw 1,5,10,X,All. I think it would be very advantageous to add an option to fill essence pouch to the list. 
This would enable a user to hold shift while in the bank interface and left click on an essence pouch to fill it (assuming they have essence in their inventory).

**Comment by dekvall** [comment]
You can already do this by setting the `Bank Deposit Shift-Click` option to `Eat/Wield/Etc.` in menu entry swapper.
