### ISSUE TITLE
Item stats on insured items not showing correctly

### ISSUE THREAD

**Issue by Yidz** [runelite/runelite#10778]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
If you have an insured item from a Trouver parchment such as avernic or infernal, the item stats overlay will show no stats for the item, as well as if you have the item equipped and hover over an item to replace it, it doesn't account for the insured item's stats.

**To Reproduce**
1. Insure an untradeable item with a trouver parchment
2. Hover over the item with Item stats overlay on, or equip the item and hover over an item that will replace it.
3. See error

**Expected behavior**
I expect the item stats to show as normal, as if it wasn't insured.

**Screenshots**
Hard for me to get screenshots of it, should be pretty easy to see what I mean though.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: latest as of 2/11/2020
 - Launcher version: latest as of 2/11/2020

**Additional context**
Don't think logs are needed, but if they are let me know and I can provide them.

**Comment by melkypie** [comment]
Seems like this is partly because of runelite scraping data from the OSRS wiki which doesn't have the item stats listed for them as they are basically a whole new item (new item id, new name with (l) in it). So until wiki adds these, there is not much that can be done.
