### ISSUE TITLE
Nightmare of Ashihama update region tracking

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#10771]
- [x] Add theme-appropriate skybox colors to the new regions, iron and main account versions of the boss room as well
- [x] Add the new regions to discord plugin

**Comment by Nightfirecat** [comment]
The dungeon region IDs reported by the "World Map Location" dev tool are accurate. That is, the following regions correspond to the dungeon:

* 14999
* 15000
* 15001
* 15255
* 15256
* 15257
* 15511
* 15512
* 15513
