### ISSUE TITLE
Boss Hiscores not updated with The Nightmare

### ISSUE THREAD

**Issue by bph6** [runelite/runelite#10789]
**Describe the bug**
The Nightmare being added to the boss hiscores has shifted all boss kc after The Nightmare alphabetically by one.

**To Reproduce**
Lookup any account on the hiscore plugin

**Expected behavior**

**Additional context**
runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePanel.jav

To fix, add The Nightmare to the BOSSES list in that file.

**Comment by Nightfirecat** [comment]
Fixed in #10783
