### ISSUE TITLE
Add amulet of bounty to item charges plugin

### ISSUE THREAD

**Issue by thebinaryeagle** [runelite/runelite#10781]
Add the amulet of bounty to the item charges plugin.

Below are the text strings you should need to reference. Apologies for the mobile screenshots, away from my PC for a few days.

Charge being used:
![3838636F-7B44-4AAC-82A8-C57BAA63D65D](https://user-images.githubusercontent.com/60583962/74369312-2987e000-4da3-11ea-9c3d-7bce94a15b04.jpeg)

Using the ‘check’ option on the amulet
![3E1A565F-C975-492E-9082-58E40D0CA159](https://user-images.githubusercontent.com/60583962/74369313-2987e000-4da3-11ea-8e20-235f818d15a3.jpeg)

One charge remaining:
![DC189768-8DC6-495E-A518-7FF43B8B2FDB](https://user-images.githubusercontent.com/60583962/74369318-2bea3a00-4da3-11ea-8081-ee603a95870d.jpeg)

Using the last charge:
![2BA25387-0016-4AC6-8D7E-DEFCA2636572](https://user-images.githubusercontent.com/60583962/74369326-2f7dc100-4da3-11ea-8257-0e8b0f1e6f9a.jpeg)

Manually breaking the amulet using the option to:
(Doesn’t show up in the chat box, just this pop up)
![2ECD18D5-155C-45AC-8C7B-68F737E6FDAF](https://user-images.githubusercontent.com/60583962/74369324-2db3fd80-4da3-11ea-9a62-53d08a8194c4.jpeg)

**Comment by dabolink** [comment]
I got this
