### ISSUE TITLE
New Master Clue Hot/Cold step - NE Slepe

### ISSUE THREAD

**Issue by davidg100** [runelite/runelite#10784]
New Master Clue H/C location northeast of Slepe:
![](https://i.imgur.com/mNDCGD8.png)
![](https://i.imgur.com/foiTqrC.png)
Map region:
![](https://i.imgur.com/L3ATbcb.png)

**Comment by Nightfirecat** [comment]
Did you check to find out whether the point you found it was centered? (we have an ongoing effort to center all hot-cold locations to improve the narrowing process)

**Comment by davidg100** [comment]
I didn't test to center it but will if I get it again - would this be where I'd isolate the true dig location based on the device's messages?

**Comment by Nightfirecat** [comment]
The mega-issue is located at #9601. We'll make sure to add it to the list!
