### ISSUE TITLE
Client doesn't resize on second monitor and is hard to grab and move

### ISSUE THREAD

**Issue by Mirino97** [runelite/runelite#10785]
Hi!

I'm having a problem where selecting the top of the screen to grab and move it around is almost impossible on a secondary monitor. Sometimes, to be able to drag it, you have to click 20+ times untill the mouse kinda sticks to the top of the window and then it can be dragged, having to click again for it to stop being dragged.

Also, clicking maximize doesn't maximize it to the whole screen, it just makes it about 10 pixels bigger on each side. Resizing the window is also very complicated as the option to resize it (cursor changing to an arrow) rarely shows up.

I'm currently using the x64 version on Xubuntu. I have already tried reinstaling the program.
This only happens on the second monitor, on the principal it resizes, can be dragged and maximized normally.

I apologize if this post is improper as I'm new to github and might've missed some rule.
Thank you in advance!

**Comment by Nightfirecat** [comment]
Do you have monitors of different sizes? If so, it sounds like you're running into the same maximizing bug as is reported here: #5153

Regarding the other issues (window chrome "stickiness", resize handles), these sound like they may be issues with your window manager. What DE/WM are you using?

**Comment by Mirino97** [comment]
Yup, I do have monitors of different sizes. One is 19" and the other is 21", if I'm not mistaken.

Thanks for the link for #5153, if you consider necessary I'll close this one and post it on the other one.

I'm currently using Xfce DE!

**Comment by Nightfirecat** [comment]
Does disabling the "Enable custom window chrome" option under "RuneLite" configuration help the window dragging issue?

**Comment by Mirino97** [comment]
Wow, it literally solves all my problems!

It allows me to drag the screen correctly and double clicking the top bar resizes it to full screen.
Resize handles are also very responsive!

It does seem to get rid of the button to hide the right bar that gives me access to all the configuration/tools/plugins, but that's a very small price to pay.

I'll leave the post open in case you want to answer/say something, but if not, you can close it and if you can't, I'll close tomorrow.

Thank you once again for your time!

**Comment by Nightfirecat** [comment]
I believe that is moved to be an overlay in the top right corner over the game frame, appearing when hovered? See: #6694

**Comment by Mirino97** [comment]
Ah, I have found it. You sir, are very smart lol.

**Comment by Nightfirecat** [comment]
Glad to help. Hopefully we'll add a solution for 5153 in time. I can't say for sure why custom chrome had its other issues with your DE, but I'm glad it works well when disabled!
