### ISSUE TITLE
Toggle/Filter "Occult Content"

### ISSUE THREAD

**Issue by OgMono** [runelite/runelite#10788]
Preface: Posted a nearly identical version of this post to the osrs forums, but realized the RL team may be better suited to the task. If there's already a way to configure settings to do this, my apologies for the redundant post -- but would sincerely appreciate a DM/reply on how to setup said configuration

By "Occult Content", I'm referring to the more "spiritually dark" content in the game -- NOT the Occult Necklace (post-patch ; it's pre-patch examine text was "spiritually dark" ), nor "traditional fantasy" content _per-se_ (magic, wizards, elves, druids, fairies, etc..)

-----------

Suggestion: In the spirit of Quality of Life month, it'd be wonderful to see a setting that allows users to toggle occult references on/off

Similarly, perhaps a filter for occult content with several different "tiers":

On -- completely unfiltered occult symbolism
Filtered -- hides the "more intense"** occult references, but leaves the more benign ones in tact
Off -- removes most to all references to occultism

** The two "most intense" occult messages I've currently seen in game, imo, are the upside down pentagram on Nechryael, as well as the repeated Cerberus' ghost message "steal your soul" **

Game features and previous Jagex updates with a similar spirit/philosophy as this proposed feature:

*Chat box, game, and profanity filters
*Ignore list, and to a lesser extent the report function
*As mentioned previously, changing the Occult Necklace's examine text to filter out spiritually dark content

Runelite plugins/settings with a similar spirit and/or technical concept as this proposed feature:

*Chat filter
*Entity hider
*Emojis
*NPC indicators

Cheers,

OgMono

**Comment by Nightfirecat** [comment]
Hi OgMono, thanks for the detailed feature request.

I don't think we will be adding any features specifically to address this need, [but would welcome a submission to the plugin hub](/runelite/plugin-hub) if someone else were interested in creating and maintaining the features necessary to fulfill this request.
In the meantime, as you've noted, you can make use of some existing plugins (primarily Chat filter) to accomplish some of these changes. Others, like replacing the NPC model of the Nechryael are not currently possible with the API we provide, but may be possible in the future should we attempt to add features like #4024.
