### ISSUE TITLE
Several Compost Bin/Bucket improvements (Markers, Timers and Indicators)

### ISSUE THREAD

**Issue by iawhd** [runelite/runelite#10794]
**Issues:**
1. Currently there is no indication for if a compost bin is done making compost without mousing over it. 

2. There is also no indication for how much compost is left in a bin when collecting or how much compostable materials have been deposited.

3. It would be nice to have a timer for compost bins in the timers plugin. The timers plugin could be used as a resolution to points 1 and 2.
_[Similar to #2960 but more expansive]_

4. An overlay indicator for how much compost is left in the Bottomless Compost Bucket (Either as an overlay on the item like the slayer helm does or as an infobox while farming) 
_[Originally proposed in #8387 but that issue is almost a year old and lacks a lot of context]_

5. Compost types should be added to the item identifcation plugin (Ultra/Super/Compost | UC/SC/C) 
_[Please note this is regarding regular buckets, not bottomless buckets like #10020 suggests]_

**Reasoning:**
I would like to sugest adding a highlight to the bin when compost can be collected (Like object markers), as well as an indicator that counts when filling or collecting. It would also be nice to have compost bins added to the timers plugin.

My final two sugestions improve QOL while farming by allowing quicker identifation of the very similar looking compost types and allowing players to see the status of a bottomless compost bucket without right clicking and choosing check.

**Solutions:**
My proposed solutions are an object marker on a 'ready' bin, as well as an indicator (could look like the 'clock' icons used in tithe farm plugin etc.) or just an overlayed number with the state of the bin. Also add the bins to the timers plugin and the buckets to item identifation.

Thanks Guys.

**Comment by Nightfirecat** [comment]
#2960 already covers the current request for compost bin status, as far as timers are concerned. I think there is little demand for knowing the amount of compostable items or compost remaining in a bin given that most players will completely fill or empty a bin in one go every time.

Bottomless bucket charges/type are already requested in #8387 and #10020.

Maintaining duplicate feature requests is not conducive to maintaining our tracker so I am closing this as all features we hope to implement in the future have already been requested in other issues.
