### ISSUE TITLE
Tooltips are rendered in an incorrect location with tooltip position Above Cursor

### ISSUE THREAD

**Issue by Bram91** [runelite/runelite#10791]
Tooltips are rendered incorrectly when `Tooltip Position` is set to `Above Cursor` resulting in the tooltip being rendered outside of the client bounds or partially under the mouse cursor:

![image](https://user-images.githubusercontent.com/7499230/74464392-bd38d980-4e93-11ea-8dc0-de874f6e16dd.png)
![image](https://user-images.githubusercontent.com/7499230/74464402-c033ca00-4e93-11ea-8895-1cd96729611e.png)

**Comment by Adam-** [comment]
fixed in 080f3133c5c94db601159477741bdc6fe8502d80
