### ISSUE TITLE
Loottracker: Hide/Show ignored items not working

### ISSUE THREAD

**Issue by Bram91** [runelite/runelite#10802]
When pressing the `Eye` Icon in the loot tracker it doesnt show hidden items, making items permanently hidden with no way to show them again in the loot tracker:

![](https://i.imgur.com/g4IWKAH.gif)

**Comment by Nightfirecat** [comment]
I can confirm this bug's behavior. Clicking that button makes no changes in the visible loot.

**Comment by abextm** [comment]
Fixed in 75019396655854a195e535f458731f663b832f1b

**Comment by joshfisk3** [comment]
This bug seems to have returned, clicking hide and show seems to have no affect

**Comment by Nightfirecat** [comment]
I used it just yesterday and it was working fine, so I don't think it has regressed again.
