### ISSUE TITLE
Hide all UI

### ISSUE THREAD

**Issue by David-Key** [runelite/runelite#10803]
Yes, You can already hide the minimap.
But I'd like a plugin that would hide ALL UI elements of the stretched display mode, preferably with a keyboard shortcut.
Would be great for taking screenshots and stuff.
![begone, ui](https://user-images.githubusercontent.com/61071184/74580322-1e030780-4fa3-11ea-84ef-0f429d807f83.png)
(at some point I'd like to get rid of the top Runelite bar as well, but hey one step at a time)

**Comment by Hydrox6** [comment]
The `Hide Widgets` plugin on the [Plugin Hub](https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub) does this.
