### ISSUE TITLE
Solved: Shift-click options in the bank

### ISSUE THREAD

**Issue by EmmaKittyO** [runelite/runelite#10806]
Recently there has been an update (I think recently at least, I'm kind of new to the game) where you can eat or equip stuff while in the bank, could we have it so that we could use shift for these actions?
So just to clarify if I have a rune fullhelm in my inventory while banking the left click option would be to deposit it to the bank, but instead while holding shift the option would be to equip it.
Things i'd like to see this work for:
- gear (equiping items)
- food and potions (eating sharks or drinking prayer potions)
- pouches while runecrafting 
- probably more that i cant think of right now

edit: im big dumdum
thank you!

**Comment by Alexsuperfly** [comment]
`Bank Deposit Shift-Click` already exists in the menu entry swapper plugin
