### ISSUE TITLE
Add recent search history function in highscore lookup

### ISSUE THREAD

**Issue by RiddleTime** [runelite/runelite#10809]
**Is your feature request related to a problem? Please describe.**
I don't want to remember the history of my searches, it could be a bit more persistent within RuneLite.

**Describe the solution you'd like**
I would like to add an optional checkbox to the HiScores plugin.
It would display suggestions based on search history, this should be limited to an X amount of results.
This would happen with either a small popup/overlay triggered by a button on the right side of the search bar or within the search bar by typeahead.

An entity in the list of previous searches would look like this: DisplayName, LookupCount, AccountType (normal, ironman, hardcore ironman etc. ). Please think about the options!

**Describe alternatives you've considered**
Optionally I was thinking about caching these recent searches, this to at least display something during osrs highscores downtime, maybe with a small indicator displaying whether the hi-score results are live or retrieved from the cache.

**Additional context**
The current search bar:
![image](https://user-images.githubusercontent.com/4581237/74593718-80edb080-502e-11ea-8aeb-7f7636840001.png)

I would like to write it but I am not very well known to your coding style/formats/rules.

**Comment by DSerp** [comment]
Should this expand on the autocomplete feature that is already implemented?

**Comment by RickertdeH** [comment]
@DSerp it seems like the original writer actually had [this in mind] (https://github.com/runelite/runelite/blob/b322f2ef6c0b0ba89ed75412dbe46e9c3ec55735/runelite-client/src/main/java/net/runelite/client/plugins/hiscore/NameAutocompleter.java#L194).

**Comment by Adam-** [comment]
> 
> 
> Should this expand on the autocomplete feature that is already implemented?

I think so, yes

**Comment by RiddleTime** [comment]
@DSerp I think the addition of only using the successful queries is a very nice addition as well.
