### ISSUE TITLE
Runelite audio works with speakers, but not headset

### ISSUE THREAD

**Issue by Fetaii** [runelite/runelite#10818]
As mentioned in the title, whenever I select my headphones as my main audio source I get no audio from Runelite but from everything else (Twitch, Youtube, Windows sounds) I can hear. Runelite is essentially silent. But, however, when I change my audio source to my speakers I can hear Runelite and Twitch, YouTube, etc. I believe I attached my log below, if not I apologize Thank you for your help.

[client.log](https://github.com/runelite/runelite/files/4212536/client.log)

**Comment by Nightfirecat** [comment]
RuneLite does not set any specific audio settings--please double-check your Windows audio settings. [If you need further support, please visit the `#support` channel of our Discord server.](https://runelite.net/discord)
