### ISSUE TITLE
GPU Plugin Optimization - Too Much Buffer Generation

### ISSUE THREAD

**Issue by tylercamp** [runelite/runelite#10819]
**Is your feature request related to a problem? Please describe.**
I've been experiencing consist BSODs while RuneLite is running, and unexpectedly poor performance on an RTX 2080 Max-Q considering OSRS' minimal graphics.

Looking at the source for the GPU plugin I see `glGenBuffers` called several times each frame, which is inefficient and may be causing BSODs on my machine. (There are various other factors of course but RuneLite is consistently present when it happens. Its use of buffers is the only strange thing I've seen so far in its code.)

Regardless of whether RuneLite is the cause of that issue, it shouldn't be continuously regenerating buffers.

**Describe the solution you'd like**
Buffers generated up-front during plugin init.

**Describe alternatives you've considered**
I'm not sure why the GPU plugin was originally written this way. I don't see any comments explaining why we're creating and deleting buffers each frame.

**Additional context**
I intend to make a PR with a fix, but want to understand why buffers are being used this way in the first place.

**Comment by Nightfirecat** [comment]
Based on discussion in Discord earlier today, it sounds like the plugin is not behaving in the way you described:

> [9:00 AM]  Adam: [...] it only creates buffers each frame
> [9:03 AM]  Adam: regardless, its definitely not freeing a fbo each frame
> [9:04 AM]  Adam: you are being confused because it is amortized
> [9:04 AM]  Adam: but it is not created/free'd per frame
> [9:05 AM]  Adam: it means that if you have two frames with the same canvas size, and same aa settings, it will not delete/recreate the fbo

Based on the discussion there, we are open to making changes if you can identify opportunities to increase performance. (which don't cause issues on certain hardware!)

**Comment by tylercamp** [comment]
I made a change locally to create buffers only once instead of creating and destroying them every frame. I've seen notable performance improvements and much better performance stability. I tested on the iGPU and NVIDIA GPU. I'm testing more locally to ensure there aren't any hidden issues (and to see if it happened to fix the BSOD issue) but I'm pretty confident that this will bring performance improvements without causing issues for others.

I did performance testing last night to quantify some of the improvements, though I didn't set up any framerate/frametime logging so it's just rough numbers and descriptions.

```
# Varrock square (unpopulated)
## unplugged
intel igpu:
- updated: ~43 avg
- original: ~37 avg

2080 Max-Q
- updated: ~48 avg (frequent dips to 30-35 when moving)
- original: ~30/41 avg (swaps occasionally) (frequent dips to 20-25 when moving)

## plugged in
intel igpu:
- updated: 50 avg (30 infrequently when moving and occasional dips to 48-49)
- original: 50 avg (frequent dips to 30/43 fps)

2080 Max-Q:
- updated: 50 avg (49 occasionally when moving and panning camera)
- original: 50 avg (48-49 occasionally when moving and panning camera) 


## Setup:
mostly standing/moving slightly in varrock square, occasionally running to banks
always looking top-down
"camera -> expand outer zoom limit" at 150



# GE W302
## unplugged
intel igpu:
- updated: 48 avg (occasional dips to 40-43 when moving, 50 frequently when standing still)
- original: 32 avg

2080 Max-Q:
- updated: 38 avg (occasionally 25-30 when moving, frequently 30-40 when moving, 45-50 when stationary)
- original: 28 avg (frequently ~23-28 moving)

## plugged in
intel igpu: 
- updated: 49 avg (occasional dips to 40-43 when moving/loading, 50 frequently when standing still and moving after loading; 45deg camera angle and spinning maintained stable 50fps)
- original: 42 avg (occasionally 50, frequent dips to ~30)

2080 Max-Q:
- updated: 49 avg (frequently 50, occasionally 40-45 when moving)
- original: 48 avg (frequently varies between 44-50)

## Setup:
combination of looking top-down and spinning camera around
combination of standing still and running around g/e
"camera -> expand outer zoom limit" at 150
```

**Comment by tylercamp** [comment]
Closing this since the branch was merged. Haven't seen any BSODs since making this update, been throwing a lot at my desktop - considering that issue to be fixed as well.
