### ISSUE TITLE
Music plugin: Make the volume control sliders toggleable

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#10811]
I prefer the volume control snapping to 25% increments, but if I turn the plugin off then I can't use the sound effect muting or music search features.

**Comment by abextm** [comment]
Just wondering, why do you like not like having granular control of the volume?

**Comment by ShaunDreclin** [comment]
I dunno really haha I just like the feel of the vanilla volume controls

**Comment by abextm** [comment]
That's really weird tbh
