### ISSUE TITLE
Twitch & Better TTV Emotes

### ISSUE THREAD

**Issue by obviouslyherbie** [runelite/runelite#10821]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

I don't know anyone personally who uses emojis, but there is a huge community that plays OSRS that actively uses both Twitch and BTTV emotes commonly, and I think they would be widely used in RuneLite.

**Describe the solution you'd like**

An addition to the Emojis plugin or a separate plugin simply titled "Emotes" that allows phrases in chat to be replaced with popular Twitch/BTTV emotes like these:

https://i.imgur.com/UxEAQaR.png

An example would be people typing PogChamp or Pog after an item drop, or various frequently used Pepe memes like "FeelsBadMan", "FeelsGoodMan", "Poggers", "PepeHands", "MonkaS", "peepoHappy", etc.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

Not sure what an alternative would be.

**Additional context**

**Comment by Alexsuperfly** [comment]
afaik most of those are copyrighted so you would need twitch's permission to use them

**Comment by obviouslyherbie** [comment]
> 
> 
> afaik most of those are copyrighted so you would need twitch's permission to use them

Even if normal twitch emotes couldn't be added, wouldn't Better TTV emotes be okay to add?

**Comment by Nightfirecat** [comment]
[BTTV's Terms of Service seems to indicate that's not the case.](https://betterttv.com/terms)

**Comment by Nightfirecat** [comment]
For the same reason as runelite/plugin-hub#43, I am closing this request. If you're able to get permission from NightDev to use these emotes, we can look at adding this feature here, or having someone submit an external plugin on the plugin hub.
