### ISSUE TITLE
Move "Tag" from Left Click option

### ISSUE THREAD

**Issue by Lalonde33** [runelite/runelite#1082]
So for black chins you only want a certain chin highlighted therefore you must use the "tag" option instead of typing the NPC name. Having "Tag" as a left click option has me accidentally unflagging and re-tagging instead of walking. Causing major issues whilst black chin hunter.'

I recommend to to make tag a right click menu option whilst holding shift. (What konduit does)

**Comment by Infinitay** [comment]
Would love this, the only reason why I don't have NPC Indicators enabled is because it adds the Tag npc menu option always. It'd be nice if the op could only be added when holding down shift as you said.

Or if you want to ignore the whole menu ops, allow us to hold ALT and tag/highlight the entity

**Comment by ShaunDreclin** [comment]
Yeah just tossing in my +1, I would like tag to be a shift-right-click instead of just right-click
