### ISSUE TITLE
Custom LOCKED window size

### ISSUE THREAD

**Issue by Arczii1337** [runelite/runelite#10820]
I found issue on Runelite when you use "application" dpi setting it does not allow maximize window to truly full screen. It is known issue and can be fixed by choosing other dpi setting but only "application" dpi gives me the best quality (others give more blurry effects). There are two solution:
a) set windows 10 dpi to 100% and you can play true fullscreen with the best quality (but other apps are very small)
b) play "application" dpi with NO maximize window. 

Option B is easier to get buuuut... on custom window size it's easy to resize or hover its with other app (mistake click).

My proposal is: gives us option "set custom window size (resolution) AND LOCK IT" - whole runelite client.

I am sorry for my english. Best regards!

**Comment by Nightfirecat** [comment]
I haven't used Windows 10's DPI settings, so I can't speak with 100% certainty here. Do the "Lock window size" and "Resize type" settings under `RuneLite`'s configuration satisfy your requirements? If not, can you be more clear in your issue description?

**Comment by Arczii1337** [comment]
This is my proposal to add option that let you set whole runelite client window size to custom values ex. 1920x1000 and lock it (it means you cannot resize a client window by drag mouse on window client border). As I said it gives the best quality without settings windows 10 OS' dpi. If it already exist, drop this idea and sorry.

**Comment by Nightfirecat** [comment]
Does setting "Resize type" to `Keep window size`, enabling "Lock window size", and setting your "Game size" setting to the appropriate dimensions address this?

**Comment by Arczii1337** [comment]
Yes, it helps! I did not know this options is already implemented under configuration -> RuneLite.
Thank you.
