### ISSUE TITLE
Status Bars missalined after recent update

### ISSUE THREAD

**Issue by lexwebb** [runelite/runelite#10837]
**Describe the bug**
After the recent update (20th Feb 2020), when in expanded window mode the status bars plugin bars are missalined and sit half offscreen.

**To Reproduce**
1. Enable Status Bars
2. Enable expanded window mode

**Screenshots**
![image](https://user-images.githubusercontent.com/1963311/74931593-d67fdf80-53d7-11ea-9d5a-d832ca4ab674.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.6.1
 - Launcher version: 1.6.0

**Comment by abextm** [comment]
Fixed in 4e9da518a30e634263d50ba0ce3c451a931a83f5

**Comment by yyruneliter** [comment]
No clue how to fix it with 4e9da51. Not knowledgeable. Will there be a fix for it via client updater?

**Comment by abextm** [comment]
restart your client

**Comment by yyruneliter** [comment]
Awesome, thank you! Restarted a min ago and didn't update. All good now :D
