### ISSUE TITLE
Status bars appearing offscreen on fullscreen mode

### ISSUE THREAD

**Issue by ifsquid** [runelite/runelite#10839]
**Describe the bug**
On fullscreen "old school box" mode, the status bar health and prayer indicators from the status bar plugin appear partially offscreen since the newest update.

**To Reproduce**
1. Turn on fullscreen mode in the osrs settings.
2. Make sure you're using "old school box" mode in the advanced settings menu.
3. Turn on the "status bars" plugin.

**Screenshots**
https://imgur.com/a/yc7kI6q

**Comment by hex-agon** [comment]
Fixed on https://github.com/runelite/runelite/commit/4e9da518a30e634263d50ba0ce3c451a931a83f5, please restart your client
