### ISSUE TITLE
Resizeable mode and inventory styles both broken after newest game update.

### ISSUE THREAD

**Issue by PetrolPumpingRat** [runelite/runelite#10838]
Many Runelite Assets are out of place using these two plugins after the most recent update.

For example, the barrows brothers minimap indicators are shifted too far up and to the left in resizeable mode.

Many overlapping and out of place icons using inventory styles as well.

**Comment by abextm** [comment]
Fixed in 4e9da518a30e634263d50ba0ce3c451a931a83f5
