### ISSUE TITLE
Ground Item value threshold (Low/medium/high/insane) overrides highlight > value threshold

### ISSUE THREAD

**Issue by MrBlueSkkyy** [runelite/runelite#10840]
When using the ground items plugin, the thresholds for the item values for low/medium/high/insane seem to always take priority over the threshold for highlight > value. That is, items that meet one of the four value thresholds will not be highlighted (or trigger a notification enabled), but instead only colored based on value tier.

For example, if the highlight > value threshold is set to 5,000 and the low item value threshold is set to 20,000, and I drop an item of value 6,000, it will highlight and notify me. However, if I drop an item of value 21,000 or greater, it will color based on item value alone and will _not_ notify me. The following screenshots demonstrate this.

![](https://puu.sh/FcEal/d61651c3a7.png)
![](https://puu.sh/FcEaN/8696b5a825.png)

Ideally, at least in my opinion, it would make more sense for the highlight > value threshold to override the item value thresholds, especially considering the highlight is the only way to receive a notification on loot drop.

**Comment by Nightfirecat** [comment]
I don't know about the intended behavior of the ground items plugin (it's been changed many times to get to where it is now), but it certainly seems like a bug that an item which is explicitly in the highlighted list, but colored differently due to its value does not trigger a highlight notification. If nothing else, that should be addressed.

**Comment by Adam-** [comment]
I think this is a simple as just reordering this:

```java
		// Cache colors
		priceChecks.clear();

		if (config.insaneValuePrice() > 0)
		{
			priceChecks.put(config.insaneValuePrice(), config.insaneValueColor());
		}

		if (config.highValuePrice() > 0)
		{
			priceChecks.put(config.highValuePrice(), config.highValueColor());
		}

		if (config.mediumValuePrice() > 0)
		{
			priceChecks.put(config.mediumValuePrice(), config.mediumValueColor());
		}

		if (config.lowValuePrice() > 0)
		{
			priceChecks.put(config.lowValuePrice(), config.lowValueColor());
		}

		if (config.getHighlightOverValue() > 0)
		{
			priceChecks.put(config.getHighlightOverValue(), config.highlightedColor());
		}
```

**Comment by prilosac** [comment]
I found this thread because I want the exact opposite behavior of OP. If I want >10k highlighted, but I explicitly say I want >1m to be a certain color, why should the color of highlight > value take precedence over the more specific color?
