### ISSUE TITLE
Since the latest update the Always Stack Tiles option in the Interface Styles plugin doesn't work.

### ISSUE THREAD

**Issue by MattRKing** [runelite/runelite#10846]
Title.

The tiles being completly fucked was fixed like an hour after the update but this setting in the Interface Styles plugin is still not working.

**Comment by Adam-** [comment]
I looked at this yesterday and I think it is due to this: https://github.com/runelite/runelite/commit/e7efd50703e734ce136f073a3fc5bcef71f968e9#diff-ebfb462aa231072e6c93cc08364661e2R46
