### ISSUE TITLE
Export friends list

### ISSUE THREAD

**Issue by RLrequest** [runelite/runelite#10843]
To make creating clan lists on websites such as CML or Temple a lot easier,  
an export friends list into notepad which is then c+p into the XP tracking websites. I believe currently for clans they'd have to manually type out X amount of members from in game friends list to 3rd party XP tracker. 

hope this is detailed enough,
ty

**Comment by JeljoGb** [comment]
This is already available in an external plugin, made by PyriteTurtle.
https://github.com/MarbleTurtle/FriendsExporter
![image](https://user-images.githubusercontent.com/34870401/74997517-91e75900-5456-11ea-99af-5fdeb5f22775.png)
![image](https://user-images.githubusercontent.com/34870401/74997543-a166a200-5456-11ea-8b10-b6c7e712dbb4.png)
Works very well.
