### ISSUE TITLE
Stew boosting incorrectly resets boost timer

### ISSUE THREAD

**Issue by leon-dubey** [runelite/runelite#10842]
With "Boosts Information" plugin enabled at default settings and a boost currently active, consuming an orange spicy stew will incorrectly reset the boost timer back to 60 seconds.

**Comment by Hydrox6** [comment]
Is this any stew, or just stews that lowers levels?

**Comment by leon-dubey** [comment]
I encountered the issue for sure with orange stew, but if I recall correctly it happened with brown as well so most likely all of them.

**Comment by Hydrox6** [comment]
I specifically meant whether it happens all the time, or just when you get your stats lowered.

**Comment by leon-dubey** [comment]
Understood. Upon my testing the reset only occurs when a stew lowers a level. boosts and other forms of lowering levels like beers seem to be functioning as intended.

**Comment by Hydrox6** [comment]
Duplicate of #3394
Sounds like the same issue.
