### ISSUE TITLE
game closes random amount of time

### ISSUE THREAD

**Issue by thomasdelamp** [runelite/runelite#10852]
**Describe the bug**
game closes after random amount of time. 

**To Reproduce**

**Environment **
windows 10
i5 9600k
rtx 2080 super
16gb ram
using the newest version of runelite

**Additional context**
[client.log](https://github.com/runelite/runelite/files/4239874/client.log)

**Comment by Nightfirecat** [comment]
Duplicate of #9889. Unfortunately, we do not have any resolution for this bug currently.
