### ISSUE TITLE
skill challenge clue: steal from ardougne chest 

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#10854]
looking through logs for a support issue i noticed `2020-02-22 14:16:31 [Client] WARN  n.r.c.p.cluescrolls.ClueScrollPlugin - Encountered unhandled clue text: Steal from a chest in Ardougne Castle.`

the current skill challenge clue file has [this](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java#L131) listed, so either the text changed from some update or a new one came out thats very similar.

to fix this just add that clue text from the log to the [SkillChallengeClue.java](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java) file

**Comment by Hydrox6** [comment]
This is because after SotE, it's no longer King Lathas's castle. I'd been wondering since its release what the text was.

**Comment by BrandtHill** [comment]
https://github.com/runelite/runelite/pull/10901
