### ISSUE TITLE
Allow separate flash notifications to be different colors

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#10867]
IE: red flash for inactivity, white flash for impling detection, green flash for chat notification, cyan flash for loot drop. Bonus points for a setting module where each type can be set up, or just baked into the option of the root setting.

E: Need for this would be it isn't always obvious what the flash notification is trying to tell me in certain situations. If they could be customized to a color, the user would always know what each one means.

**Comment by Nightfirecat** [comment]
Closing in favor of #11679 as these are effectively the same request.
