### ISSUE TITLE
Add new emote to runelite ingame chat

### ISSUE THREAD

**Issue by GenoOSRS** [runelite/runelite#10864]
I would like the 😔 emote to be added to runelite. I find that i use the emote a lot in discord but when talking to others in runescape pms it isnt there so would appriciate if it was added :)

**Comment by dekvall** [comment]
Here's the emoji for whoever wants to add this ![pensive-face](https://raw.githubusercontent.com/dekvall/twemoji/runelite-emoji/runelite-emoji/1f614.png)

**Comment by hjdarnel** [comment]
any ideas for a trigger phrase?

**Comment by dekvall** [comment]
Discord seems to like `v_v`
