### ISSUE TITLE
Menu Icons Jumping when on Interface Mode and Resizable

### ISSUE THREAD

**Issue by JSturge** [runelite/runelite#10861]
**Describe the bug**
When you have Interfaced Styles enabled and resizable turned on, the menu icons surrounding the inventory icon jump when clicking other icons.

**To Reproduce**
1. Turn on Interface Styles
2. Enable 2005 interface
3. Enable resizable mode
4. Click on equipment icon, stats, etc.

**Expected behavior**
The icons should not jump.

**Screenshots**'
Video of the problem:
https://i.gyazo.com/8df1d9ef929066024ae7a20b082969e5.mp4

**Environment (please complete the following information):**
 - OS: Windows 10
 - Runelite 1.6.7

**Comment by Adam-** [comment]
fixed in abaf45092b9f20d1068698da3ed726db6b35bce2
