### ISSUE TITLE
MLM Plugin: Option to disable agility plugin/shortcut highlight

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#10872]
Once you get access to the top level, you'll never use that shortcut again. At a lot of angles on the top level, it just becomes visual clutter. An option within the plugin that would either turn off the agility plugin while the MLM plugin is active, or just some way to tell the game not to highlight that shortcut anymore would be great.

**Comment by TheStonedTurtle** [comment]
Having one plugin override the functionality of another sounds like a bad idea. You can turn off the agility plugin while inside MLM.

**Comment by dekvall** [comment]
I agree with the previous comment; you can just turn the plugin off while in mlm.
