### ISSUE TITLE
Add Time-To-Level to Canvas And XP Tracker [cash bounty available]

### ISSUE THREAD

**Issue by larkable** [runelite/runelite#10888]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to hover over the XP tracker stat to find out my Time-To-Level. I like to see my TTL update in realtime. 

Instead of "XP Left", why not have an option to switch it with "Time To Level"?

Additionally, there needs to be an XP Expiry feature (like OSBuddy's) where the user can specify how long XP is stored for calculating XP/hr and Time To Level. For instance, after 1 hour, the XP used to calculate both XP/hr and TTL (Time To Level) is reset and is now calculated based on a new hour of XP gained.

**Describe the solution you'd like**
It would be nice to add Time-to-Level to the Canvas. Time to Level is not a default feature of OSRS and I feel like this would be a great thing to add. Canvas is also not an OSRS feature. Adding an option to add Time-To-Level under "XP/Hour" would be neat.

Additionally, adding "TTL" in the right-side menu would be great. Instead of "XP Left", it could be replaced with "TTL."

**Describe alternatives you've considered**
I haven't tried any alternatives, I just miss the TTL feature from OSBuddy.

For those who argue that "Auto-Pause" is a thing, it does not accurately reflect XP/hr and TTL if you are skilling for a long amount of time. I like to see how much XP I've gained in one day. The XP/hr can be inaccurate if, for instance, you level up and can now get more XP/hr by unlocking a method to do something. For example, I could get 70 fishing after fishing for 10 hours. My XP/hr is still going to say something like 35k XP/hr, but now I should be getting close to 50k XP/hr. Even with Auto-Pause, the XP/hr is now wildly inaccurate and doesn't reflect the actual current XP/hr. This is what XP Expiry is for.

Example of what I am looking for:
![image](https://user-images.githubusercontent.com/883586/79644382-43acb880-816e-11ea-96fa-c30509e2971b.png)

**Comment by Nightfirecat** [comment]
Related to #8373

**Comment by larkable** [comment]
https://www.bountysource.com/issues/89163088-add-time-to-level-to-canvas

I have added a $20 bounty to get these two features added.

**Comment by while-loop** [comment]
@Nightfirecat I'd like to take a stab at adding TTL to the canvas and panel. and #8373 
(while also adding a selection for "Actions" or "Actions/Hour" in the panel)

@larkable is the expiry time request auto-resetting the skill's xp after N minutes/hours?

**Comment by larkable** [comment]
@while-loop: 

The total skill XP should not be reset after N minutes/hours. However, a separate variable will hold the XP value that actually resets. This variable is the variable used for calculating XP/hr and TTL.

Hopefully that makes sense, ask if you have questions!

**Comment by while-loop** [comment]
I think I understand, a moving XP/hr. So, if I set my expiry to 2 hrs, only use the latest 2 hours of xp and deleted anything else gained before that 2hr mark.

**Comment by larkable** [comment]
That's correct!

**Comment by while-loop** [comment]
And a little more clarifications.. XP gained and actions done should be of the total session? While xp/hr and actions/hr should be within the 2hr expiry time?

**Comment by larkable** [comment]
Yes, there should be a total XP and total actions done still calculating the entire time without reset.

XP/hr and actions/hr should be stored separately for the length of time that the user sets their options to.

If you need an example, OSBuddy's XP tracker shows exactly what I'm looking for.

**Comment by while-loop** [comment]
Could we split this issue into 2?

The first part includes code for just being able to modify the infobox labels. I think the xp expiry time is a separate issue w/ a different scope.

(and the bounty could be for the newly created expiry issue)

**Comment by larkable** [comment]
> Could we split this issue into 2?
> 
> The first part includes code for just being able to modify the infobox labels. I think the xp expiry time is a separate issue w/ a different scope.
> 
> (and the bounty could be for the newly created expiry issue)

Yes, absolutely. I will create an XP Expiry request.

**Comment by larkable** [comment]
#11344

**Comment by Nightfirecat** [comment]
Between this issue and #11344, is the right issue marked as having the posted bounty on it?

**Comment by larkable** [comment]
Yes, this one will be the bounty one as this was the most important feature request.
