### ISSUE TITLE
Venom / poison damage taken countdown

### ISSUE THREAD

**Issue by Juliacare** [runelite/runelite#10909]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

I want to minmax dps on bosses such as Zulrah and Vorkath by only drinking pots during intermissions. This can be done for every pot with ease except for the anti venom pots which you have to hover over your HP bar to check the time remaining on application of the debuff which is just really annoying when you go to check that and you get specced by vorkaths aoe spec for example.

**Describe the solution you'd like**

Similair to how the time of divine potions or NPC aggression timers are displayed on your frames, a toggleable icon that counts down until the next damage taken from poison or venom so you can know in an eye glance if you can wait until the intermission to drink or if you have to lose dps.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

An alternative could be to have a countdown similair to the stat change counter when potted up on non divine pots.

**Additional context**

Similair to these frames ![image](https://user-images.githubusercontent.com/36482621/75587652-3bda6d00-5a77-11ea-8b7b-a423daf31467.png)

**Comment by Hydrox6** [comment]
The [Poison](https://github.com/runelite/runelite/wiki/Poison) plugin already does this, with the Infoboxes option, or is there something I'm missing?

**Comment by Juliacare** [comment]
I must've missed it. Asked in clan as well and got redirected here.
Sorry for wasting time 😅
