### ISSUE TITLE
Fishing Tooltip does not update on level-up

### ISSUE THREAD

**Issue by netctrl** [runelite/runelite#10900]
**Bug**
The fishing tooltip (Status, Caught, Per hour) does not update the status when character levels up. and pauses their action.

**Expected behavior**
When leveling up, fishing becomes interrupted. The tooltip should update status to "NOT Fishing" until the level-up screen is cleared, since the screen is not interrupted and must be cleared by the user.

Screenshots (.gif):
https://i.gyazo.com/afb59824d2dc18dc09223d327e74dac7.gif

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.6.8
 - Launcher version: 2.1.0

**Comment by BrandtHill** [comment]
See pull request: #10908
