### ISSUE TITLE
Better stretched mode for Mac

### ISSUE THREAD

**Issue by eprkr** [runelite/runelite#10918]
I get that nobody wants to make the GPU plugin work for Mac, I've come to terms with that :(

However, I'd really love to see the UI scaling settings ported over if possible.

**Comment by Nightfirecat** [comment]
The Stretched Mode plugin is not dependent on the GPU plugin to work. The GPU-powered UI scaling options do require GPU to work on the platform, so they will not work until we are able to integrate GPU functionality on MacOS.
