### ISSUE TITLE
Timer doesn't notify when it's run out

### ISSUE THREAD

**Issue by dovry** [runelite/runelite#10921]
The timer doesn't notify when it's run out, with no option to enable an alert.
![image](https://user-images.githubusercontent.com/15201298/75628400-dacaaa80-5bd8-11ea-83dc-72cf504fa820.png)

**Describe the solution you'd like**
Send a notification or another type of alert when the timer hits 00:00, with a checkbox to toggle (en/dis)able alerts

**Comment by jsnells1** [comment]
The "Time Tracking" plugin has an option to notify for timers

**Comment by dovry** [comment]
The [documentation](https://github.com/runelite/runelite/wiki/Time-Tracking) for this plugin is outdated.
