### ISSUE TITLE
Stab Attack Bonus is Wrong

### ISSUE THREAD

**Issue by Chee-RS** [runelite/runelite#10926]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Incorrect stab bonus (and speed when unarmed) on weapon scroll over

**To Reproduce**
Steps to reproduce the behavior: idk

**Expected behavior**
Have correct stat bonuses

**Screenshots**
[Let me know if you need more!](https://imgur.com/a/Fd50aqA)

**Environment (please complete the following information):**
 - OS: Mac
 - RuneLite version: 1.6.8
 - Launcher version: 'Unknown'?

**Additional context**
It seems to think I have attack speed of 6 unarmed (seems to only be an issue when unarmed) and:
+77 stab when not wearing anything and about to equip Abyssal Dagger (-2),
+9 stab when not wearing anything and about to equip Katana (-2),
+3 stab when not wearing anything about to equip Toxic Blowpipe (-3),
-1 stab when not wearing anything and about to equip Heavy Ballista (+1),

**Comment by Adam-** [comment]
Looks like @BenDol broke this in #10258 - https://github.com/runelite/runelite/pull/10258/files#diff-726aed9d5db03fc1de5694de6970f8b2R284
