### ISSUE TITLE
Staking Problem

### ISSUE THREAD

**Issue by EvanH1998** [runelite/runelite#10929]
I would like you guys to consider adding a feature where you can block a world like world 302 (duel arena world) so I can no longer lose money. Kind of like how you can hide attack styles, make it possible to hide a world

**Comment by EvanH1998** [comment]
I would like you guys to consider adding a feature where you can block a world like world 302 (duel arena world) so I can no longer lose money. Kind of like how you can hide attack styles, make it possible to hide a world

**Comment by Chee-RS** [comment]
won't you just end up either turning it off or staking on a different world?

**Comment by dekvall** [comment]
For the same reason that we don't support custom game modes whose rules could be easily bypassed by turning its corresponding plugin off, I don't see this being added. #435 is open and has a comment mentioning the ability to blacklist certain worlds, which essentially seems to be what you want in this case, though it would be just as easy to bypass.
