### ISSUE TITLE
Make shift-click interaction on RC pouches ignore empty

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#10930]
There's almost no reason I can ever think of you'd want to empty a rune pouch while in your bank interface, as then you'd have to refill it and waste a 'charge', forcing you to repair earlier. Would be nice if the shift-click functionality for pouches while viewing your bank would only defer to 'Fill' and ignore 'Empty'. Could replace it with deposit, since that's a bit of a 'no harm no foul'.

Bonus: maybe make a filled rune pouch a different color so its more obvious which have been filled? I feel like this use to be in, but maybe I'm dumb. Or maybe it got removed for some reason.

**Comment by Nightfirecat** [comment]
These features are both available via plugin-hub plugins. [Preventing the "Empty" option on essence pouches is available in the Essence Running plugin](https://github.com/AaronPoon/essence-running#swap-bank-op) and [showing the number of essences stored in a pouch is available via the Essence Pouch plugin](https://github.com/Adam-/runelite-plugins/blob/esspouch/runelite-plugin.properties).
