### ISSUE TITLE
Slayer Plugin Update

### ISSUE THREAD

**Issue by ez1ollie** [runelite/runelite#10935]
Is it possible to update the slayer plug in to add highlighting options like the NPC indicator plug in has. Current option only allows for the hull highlight.

current highlighting - https://i.imgur.com/j8Uvui1.png
slayer plug in options - https://i.imgur.com/0tkLtqQ.png
npc indicator plug in options - https://i.imgur.com/iAmphK1.png

**Comment by Nightfirecat** [comment]
Duplicate of #4606
