### ISSUE TITLE
Feature - Kingdom of Miscellania notification message

### ISSUE THREAD

**Issue by BrandtHill** [runelite/runelite#10939]
Picture this - you're logging on to Runescape after not having played for a few weeks. You afk NMZ for a few hours while watching Vampire Diaries with the Misses. You log off. Alas, all this while you've had money in the dwindling coffer of your vassal state, Miscellania, but your approval rating is so low that your once-loyal subjects aren't bringing in nearly as much coal and mahogany logs as you'd prefer. If only there was a way to be reminded of your diplomatic duties...

Introducing additional functionality to the Kingdom Plugin. Wouldn't it be great to be shown the current status of you coffer and favor/approval ratings? Check out the screenshot below:
![image](https://user-images.githubusercontent.com/38387397/75793972-bdf7b980-5d35-11ea-9a52-68fcdc743cca.png)

*But how does it work? I thought the Varbits associated with Managing Miscellania were only sent to your client by the server when you're in the bounds of Miscellania.*
Astute observation. This plugin works by saving the state of your coffer and favor when you visit Miscallenia, and when when you haven't visited Miscellania in more than a day, the displayed values will be calculated based on how many days have passed since you last knew about your favor/coffer status.

Luckily I've already implemented this feature in Pull Request #10933 

~~If anyone has any requests, like making this configurable with thresholds, let me know.~~
I made it configurable with thresholds

**Comment by jachymb** [comment]
The numbers could get messed up, if you use the kingdom from another client, e.g. mobile.

**Comment by BrandtHill** [comment]
> The numbers could get messed up, if you use the kingdom from another client, e.g. mobile.

If you use Runelite on multiple desktop clients and sign into Runelite, your properties should sync across them (including your configuration settings for other plugins). 
In the case of mobile, if you contribute to coffer/favor, the next time you login to desktop client, it will err on the side of reporting less than the actual value.

**Comment by jachymb** [comment]
The favor will never be lower than the estimated value, true, but the coffer value can be changed both ways.

**Comment by BrandtHill** [comment]
That's true. I never withdraw, so my use case is only depositing. Unfortunately this is the best we can do since the values are only updated while in Miscellania.

**Comment by Adam-** [comment]
> 
> 
> The numbers could get messed up, if you use the kingdom from another client, e.g. mobile.

This is true of a whole bunch of our features and I think most people are okay just overlooking that.
