### ISSUE TITLE
[Suggestion] Disable all

### ISSUE THREAD

**Issue by LewisKappa** [runelite/runelite#10937]
Disable all option, which would do as it says in the title, but you would be able to click it on and off and it would enable all your previous settings as before. 
People probably won't see this as very useful, but it has some uses depending on the user.

**Comment by Hydrox6** [comment]
Examples would help, since what you've described is basically just turning the plugin off, which can already be done

**Comment by LewisKappa** [comment]
All at once, whilst still remembering the old settings. Mainly because earlier I had trouble with the client lagging, as it somehow made my system process use a lot of disk usage until I restarted it.

**Comment by Alexsuperfly** [comment]
moving the settings file will do this, its not a button in the client but i dont see this being an issue that warrants a dedicated feature in client for it

**Comment by Espionage724** [comment]
I reinstall operating systems and RL frequently. I don't like majority of the default-enabled plugins, and only really use RL for the the GPU plugin while on Linux.

Currently I toggle-off every plugin one-by-one down the list, and this is cumbersome. I would prefer a setting or method to turn off all plugins all at once, and allow me to enable the few I want.

I'd prefer it to be some easy-click button, but I wouldn't mind it being some hidden file or easy text config.

**Comment by raiyni** [comment]
This can be accomplished now by making profiles

**Comment by Espionage724** [comment]
> This can be accomplished now by making profiles

How _specifically_?

I tried doing Google sync with RL and disabled all plugins. They were enabled the next reinstall I did while signed into the same Google account. If I recall right there wasn't an obvious disable-all-plugins button in the UI settings.
