### ISSUE TITLE
X above minimap isn't smooth when xBR UI scaling is enabled

### ISSUE THREAD

**Issue by M1ch431** [runelite/runelite#10938]
The X (logout button) above the minimap doesn't appear to be completely smooth when xBR UI scaling is enabled.

1. Go to the OSRS settings and turn on the game client expands to window option.
2. Go to the GPU plugin and turn on xBR UI scaling
3. See error

The transparent X should be smooth and not be jagged when in an unpressed (transparent) state. When not transparent and pressed, it looks as intended and is smooth.

 - OS: Windows 10 LTSC 2019
 - RuneLite version: 1.6.8
 - Launcher version: Not sure how to find this, but the latest at the time of posting.

![Image of Issue](https://i.imgur.com/IFhyGN4.png)

**Comment by Nightfirecat** [comment]
If the image on the left is taken ingame from using the xBR scaling option, how have you generated the image on the right?

**Comment by M1ch431** [comment]
@Nightfirecat The right image is simply when the X is in a pressed (active) state (logout frame visible). I believe the transparency has something to do with the jagged edges.

**Comment by Nightfirecat** [comment]
We have recently replaced the GL library used by the GPU plugin. Given that change, we are closing this. Please comment if you still experience this issue.
