### ISSUE TITLE
[Suggestion] Search Option for loot tracker

### ISSUE THREAD

**Issue by LewisKappa** [runelite/runelite#10940]
Because of the loot tracker being spammed after a while, and not wanting to reset it. It would be nice for a search option.

**Comment by Alexsuperfly** [comment]
the placing of the most recently killed monster is a duplicate of #8519 
could you narrow the scope of this request to only be the searching

**Comment by Chee-RS** [comment]
kinda off-topic but I think (like 99.8% sure) the loot tracker sometimes slows down my game so I have to reset it to not lag, is there a way to fix this?

**Comment by ypperlig** [comment]
Duplicate of #10704
