### ISSUE TITLE
*Feature Request* Runecrafting pouches that show essence when scrolled over

### ISSUE THREAD

**Issue by Chee-RS** [runelite/runelite#10943]
IDK how to add 'Feature Request' label sorry

**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
It would be nice to have a scroll over option on runecrafting pouches that shows the amount (if any) of essence inside, also maybe show the text color in red if it's 0

**Describe alternatives you've considered**
Can't think of any

**Additional context**
[something like this I think](https://i.imgur.com/D7kAcjz.png)
sorry for the bad photoshop lol I only have Preview

**Comment by Nightfirecat** [comment]
The `Essence Pouch` plugin available via the plugin hub implements this feature.

**Comment by Chee-RS** [comment]
> The `Essence Pouch` plugin available via the plugin hub implements this feature.
How do I get this?

**Comment by loldudester** [comment]
Scroll to the bottom of the plugin list in the Config panel of Runelite, and click Plugin Hub at the very bottom. Then look for the Essence Pouch plugin in there.

**Comment by Chee-RS** [comment]
Oh my god I had no idea that button existed lmfao

thank you <3
