### ISSUE TITLE
Moveable/Alphabetical ordering for Inventory Setups.

### ISSUE THREAD

**Issue by lifelulz** [runelite/runelite#10958]
Hello i would like to be able to either move the ordering or choose maybe an alpabetical ordering for my inventory setups as of this moment i have 26 different setups (more to come ofc ). and i find it to be a clusterfuck atm. Love the compact mode that was added recently which helps but aint quite the solution i was looking for.

**Comment by melkypie** [comment]
For plugin-hub plugins you should post at the respective plugin's repo https://github.com/dillydill123/inventory-setups/issues. I also believe there's a way to right click the setup and move it up and down that way.

**Comment by lifelulz** [comment]
THX melkypie you are totally correct there indeed is that option, thx for the help/and fast response hope your day is filled with puppydogs and rainbows
