### ISSUE TITLE
Please revert ground items change or give us an option 

### ISSUE THREAD

**Issue by ir1descent** [runelite/runelite#10961]
**Is your feature request related to a problem? Please describe.**
It is illogical to have it work this way, where "value >" takes priority over anything and everything else. That defeats the whole purpose of the other options in the plugin, and essentially downgrades the plugin to a more barebones variant.

**Describe the solution you'd like**
Asking for this change to be undone might be too big of an ask, but at least give us an option to choose the behavior please.

**Describe alternatives you've considered**
I've considered giving up on the plugin.

**Additional context**
-

**Comment by Nightfirecat** [comment]
What makes it more valuable to not have "value >" take priority over highlighting? Why is it more useful one way or the other?

**Comment by ir1descent** [comment]
> What makes it more valuable to not have "value >" take priority over highlighting? Why is it more useful one way or the other?

When doing quests for example and you need to keep an eye out for a very specific item, that will be otherwise very easy to miss, or when you're farming a specific item for whatever reason other than money really.

This new change is just bad for quality of life in my honest opinion.

**Comment by TheStonedTurtle** [comment]
I believe the issue is that the only way to get notified of a drop over a certain value is to use `Highlight > Value` option with the `Notify for Highlighted drops` option enabled. After the most recent changes these items are always the same color making it harder to distinguish valuable drops from manually listed items(`Highlighted Items` box).

**Comment by Adam-** [comment]
> 
> 
> > What makes it more valuable to not have "value >" take priority over highlighting? Why is it more useful one way or the other?
> 
> When doing quests for example and you need to keep an eye out for a very specific item, that will be otherwise very easy to miss, or when you're farming a specific item for whatever reason other than money really.
> 
> This new change is just bad for quality of life in my honest opinion.

I don't see how this is valid use case. If there are specific items you want to watch for you would just add them to the highlight list, which is by name. That hasn't changed.

**Comment by ir1descent** [comment]
Oh sorry I misunderstood how this plugin works.

Does this not break the other colors functionality still though? Since value > takes priority

________________________________
Van: Adam <notifications@github.com>
Verzonden: vrijdag 6 maart 2020 22:15:21
Aan: runelite/runelite <runelite@noreply.github.com>
CC: ir1descent <xbx963@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [runelite/runelite] Please revert ground items change or give us an option (#10961)


What makes it more valuable to not have "value >" take priority over highlighting? Why is it more useful one way or the other?

When doing quests for example and you need to keep an eye out for a very specific item, that will be otherwise very easy to miss, or when you're farming a specific item for whatever reason other than money really.

This new change is just bad for quality of life in my honest opinion.

I don't see how this is valid use case. If there are specific items you want to watch for you would just add them to the highlight list, which is by name. That hasn't changed.

**Comment by ir1descent** [comment]
Sorry had to delete a comment because replying via email was not a good experience.

Anyways, I misunderstood how this plugin works.

It still breaks the other color functions though, does it not?

That's not something I personally use, but I can see how someone else might not be really happy.

**Comment by stevebasher** [comment]
massive +1 to this, I really liked the ability to configure notifications for all items over X value, but still get a granular breakdown of the worth via the colour option.

Plus I used highlight for 5k+ items, so it gave me another level of colouring (5-20k) which was nice.

**Comment by stevebasher** [comment]
Suggestion: add another optional level of colouring (for the 5-20k range) and an option to notify on any coloured drops - keep the rest the same (so we can just set value > to be 0 to remove that functionality)

**Comment by Adam-** [comment]
> 
> 
> massive +1 to this, I really liked the ability to configure notifications for all items over X value, but still get a granular breakdown of the worth via the colour option.

The bug that this is fixing, #10840, is specifically that you could not get notifications for > value due to having other color thresholds set, since the notification is based off of the color. So I don't see how you could have configured it to do this originally.
