### ISSUE TITLE
Ammo incorectly shown in loot tracker

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#10979]
I am not sure how to reproduce this, because it happens infrequently, but I am seeing a broad bolt in my Aberrant spectre loot tracker. Of course they don't drop them, but I was shooting broad bolts at them so probably the loot tracker confused the monster drop with the ammo lying on ground. 

I can simply toggle the item to not show in the tracker and the problem is solved for me, so maybe it's not worth fixing? Decided to report anyway.

**Comment by Adam-** [comment]
This can happen if the item spawns on the same tick and at the same location as the monster when it despawns. We can't fix it.
