### ISSUE TITLE
Improving Timers In The Time Tracking Plugin

### ISSUE THREAD

**Issue by SamuraiPR** [runelite/runelite#10980]
**Problem:**
I been using multiple timers from the Time Tracking plugin to know when to go to a certain world for a resource.

I try to put them in expiration order but sometimes situations such as delays happens that puts the timers out of order to the point that it becomes hard to know which timer will expire next.

Additionally the current indicator that a timer has expired (0:00 in a red colored thin font) does not pop-out and can go unnoticed easily.

**Solution A:**
Make timers draggable so that we can put them in order of expiration.

**Solution B:**
Add an option to sort them by time left.

**Solution C:**
Improve the 0:00 mark red text highlight by making the whole box red instead. Optionally add a feature in which you can choose when to highlight the timer, for example 10 seconds before expiration, etc...

Thanks for your consideration.

**Comment by melkypie** [comment]
This is mostly a duplicate issue of #7240 except for coloring the timer boxes. Also most of this was added in #10996, which will be available next release.

**Comment by Nightfirecat** [comment]
I agree. If after our next release you find that you're still wanting more features out of this plugin, please edit the issue and re-open it.
