### ISSUE TITLE
Unable to use Numpad-6 in client

### ISSUE THREAD

**Issue by ziro-wav** [runelite/runelite#10995]
When typing in-game, either through menu interfaces or in chat, the numeric keypad is completely functional except for the number 6. I'm certain this is RuneLite specific as it works in other programs, and when turning off num-lock the 6 key functions as an arrow key without issue. The only time it doesn't work in RuneLite is when trying to type the number 6.

 - OS: Windows 10
 - RuneLite version: 1.6.9
 - Launcher version: 2.1.0
 - OldSchool revision: Rev 188

**Comment by Nightfirecat** [comment]
Are any of your various plugin settings using Numpad-6 as a hotkey? (such as the screenshot plugin)

**Comment by ziro-wav** [comment]
Not to my knowledge, no. I've tried sorting through them but having some-50 odd plugins enabled makes it a little difficult to filter through which plugins allow hotkeys, but I can't recall setting any hotkeys within recent memory.

**Comment by Nightfirecat** [comment]
Can you upload your client.log file after opening the client, logging in, pressing your Numpad-6 key a few times, then logging out and closing the client?

**Comment by Nightfirecat** [comment]
Closing as no new information was provided.
