### ISSUE TITLE
Clan information.

### ISSUE THREAD

**Issue by derpyderpaderp** [runelite/runelite#11001]
**Is your feature request related to a problem? Please describe**. 
Not really

**Describe the solution you'd like.**
Could their be a clan information implemented. Where this could benefit is for clans like w308 anvil where they can use that tab to keep the prices of their alching items updated. It could also be used for clan rules, ways to rank up, and generally what the clan is for. I don't know it just seems like something that would be beneficial and something runescape is lacking. How this would be implemented I have no idea. I feel like it would take up valuable resources but if it could be hosted somewhere locally on the clan owners computer or something, like I said I have no clue on how this could work. Anyways if their is a way it would be a great plugin idea and something to keep players informed about things going on in a clan chat. Tbh this should be something runescape itself should implement but they don't care about features as much as they care about content.

**Comment by Nightfirecat** [comment]
I don't think we will offer this feature, both because it would be technically difficult (to verify authentic cc owner identity, requires database storage or some other means to distribute info, etc.) and because Jagex is currently working on a clan system which I imagine would address this need.
