### ISSUE TITLE
Getting stuck in a party (party plugin/discord plugin)

### ISSUE THREAD

**Issue by matcpn** [runelite/runelite#11003]
I'm running into issues with the Party Plugin/Discord Plugin where I seem to be stuck in a party by myself. The behavior is that I cant join other people's parties, I cant ask anyone to join my party. I don't have exact steps to reproduce but it seems to happen occasionally. Root cause is unknown to me from looking at the code, but I think having an explicit "leave party" button in the party plugin would potentially help this situation. 

Right now in the party plugin, the "leave party" button is only available if you shift + right click one of your party member's names, but if you have no party members then it isn't available. The only other code path that lets you leave the party is turning the discord plugin off. I think having a "leave party" button similar to the [Party Panel Plugin](https://github.com/TheStonedTurtle/party-panel/blob/master/src/main/java/thestonedturtle/partypanel/PartyPanel.java#L211) is a good solution, and I think it may also be nice to expose the [dev mode information](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/party/PartyPlugin.java#L463) somewhere so that it's clearer what the issue is

**Comment by Nightfirecat** [comment]
If you end up in this situation, there is an overlay menu button (accessible via Shift+right-click if you don't have the option set to make it a right-click option by default) to leave your party. Does that work for you?

**Comment by matcpn** [comment]
Can you clarify what "overlay menu button" means? I know right now it has this available: 
![image](https://user-images.githubusercontent.com/4219663/76686828-cf25ad80-65f4-11ea-94c2-d2e54d4ec235.png)
This shows up if you shift+right click on the party member overlay. It's just a little hidden because you can turn off that overlay. Plus this didn't help the situation I found myself in where I was in a party with no other members of the party.  I was thinking something like this in the config panel (image is from the external plugin "party panel"):
![image](https://user-images.githubusercontent.com/4219663/76686885-6d197800-65f5-11ea-93df-29fe1eacb79d.png)
Maybe there's something else I'm missing though

**Comment by Nightfirecat** [comment]
Since we're not using a panel in the main client plugin, we're not going to add one specifically for this feature. I misspoke regarding the "overlay menu button"--I should have said _overlay menu option_, which you showed in your first screenshot.

Why didn't that help when you were in a party with no other members?

**Comment by matcpn** [comment]
As far as I understand the "leave party" menu option only appears when you shift + right click on a party member's name

**Comment by deathbeam** [comment]
Its option on overlay, so as long as the overlay exists, it will be there

**Comment by matcpn** [comment]
Also just to clarify, the suggestion wasn't to create a panel for this, rather just stick it in this panel: 
![image](https://user-images.githubusercontent.com/4219663/76687895-722ef500-65fe-11ea-8ed8-04022c9163a3.png)

**Comment by Hydrox6** [comment]
Sadly, config panels don't work like that, which is why it's only on the overlay

**Comment by Nightfirecat** [comment]
I don't think there is any actionable change to be made here, so I am closing this issue.
