### ISSUE TITLE
GPU Plugin freezes client when turned on

### ISSUE THREAD

**Issue by Sappattack06** [runelite/runelite#11015]
**Describe the bug**
Client freezes when I switch on the GPU plugin. It worked perfectly the first time I tried using it with my new gaming PC. I come back the next day and now it freezes every time I switch it on. I have tried ALL trouble shooting options located in the GPU FAQ. I have even tried older drivers for my GPU and still no luck.

1. open runelite
2. login to your account or stay on login screen (doesnt matter)
3. Switch on GPU plugin
4. Client freezes

Expected behavior
Runescape looks amazing and I can play the game.

**Screenshots**

Environment 
 - Windows 10 64 bit
 - RuneLite version: current
 - intel i5-9600k
-Geforce GTX 1060 6GB GPU

Additional context
[client crash log.txt](https://github.com/runelite/runelite/files/4333422/client.crash.log.txt)

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. GPU related issues are usually very specific to the user's setup.
For further questions of support, please join the [Discord](https://runelite.net/discord)
