### ISSUE TITLE
please move cannon recommended spot 1 tile south in stronghold dungeon

### ISSUE THREAD

**Issue by oslokebab** [runelite/runelite#11027]
Hey, I have noticed that if you would move recommended cannon spot in this area in gnome stronghold dungeon 1 tile south then you would always double hit bloodvelds if standing as shown on picture. this is because of the wall to the east blocking the pathway for npcs... the current recommended spot doesn't allow this. please move it 1 tile south. thank you. 

![2020-03-17_05-05-07](https://user-images.githubusercontent.com/62274373/76821078-3a49cc80-680d-11ea-8f1f-e5df531a1c60.png)
![2020-03-17_05-07-04](https://user-images.githubusercontent.com/62274373/76821089-403fad80-680d-11ea-8bb6-f53b7129b291.png)
![2020-03-17_05-07-18](https://user-images.githubusercontent.com/62274373/76821099-459cf800-680d-11ea-8b1a-e1a1031dc90e.png)

**Comment by dekvall** [comment]
Added in #11028
