### ISSUE TITLE
Feature Request: Offline Friend Finder

### ISSUE THREAD

**Issue by jpr227** [runelite/runelite#11020]
**Is your feature request related to a problem? Please describe.**
Currently, many members of multi-combat pking clans rely on using their own handmade clients or using osbuddy which is clunky and laggy for the offline friend indicator feature on the map. 

**Describe the solution you'd like**
Runelite is perfect for pking except for the offline friend finding feature which is used heavily in multi-clans on osrs. I would love if an offline friend finder could be added to runelite where it shows a player you added to your friendslists' name on the minimap and on the main screen on top of their character. 

**Describe alternatives you've considered**
N/A, only one real solution or else multipkers will have to continue using other clients as the feature is that useful/critical to them.

**Additional context**
https://i.gyazo.com/516ce4bcd66fc1d6d9adc38a7783a378.png 

example

**Comment by Alexsuperfly** [comment]
this on the the [rejected list](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features)

`Highlighting "Offline" Friends (and generic player highlighting): Not included to respect players with their messaging mode set to Private and to avoid harassing players (see #951)`
