### ISSUE TITLE
Shift Anti Drag

### ISSUE THREAD

**Issue by jalwin** [runelite/runelite#11039]
Shift Anti Drag doesn't work properly on Mac OS correctly. No matter how low or high the delay you will have the item being dragged instead of being worn when holding down shift. I haven't tested on different Macs or OSX. 

**Environment**
OS: Catalina (10.15.3)
Model: (2019 13in) 2.4 GHz Quad-Core Intel Core I5 8GB RAM

**Comment by JZomerlei** [comment]
You don’t happen to have the plugin hub ‘left click dropper’ do you? That plugin has to be off for shift anti drag to work properly. 

If not it may be helpful to post your client.log to paste bin here.

**Comment by jalwin** [comment]
is this only a Mac OS behavior cause when I use it on windows I have both plugins with no problem.

**Comment by JZomerlei** [comment]
Left click dropper when enabled essentially disables shift anti drag.

**Comment by Nightfirecat** [comment]
@jalwin Can you confirm if disabling the `Left click dropper` plugin-hub plugin makes Shift Anti Drag work as expected?

**Comment by Nightfirecat** [comment]
Closing due to stale issue.
