### ISSUE TITLE
plugin menu is bugging

### ISSUE THREAD

**Issue by madpatter73** [runelite/runelite#11047]
**Describe the bug**
every time I try to access the plugins and try to look at any plugins it drags over everything and makes it impossible to click

**Expected behavior**
I expected to be able to access the plugins I guess?

**Screenshots**

![](https://media.giphy.com/media/ie2E3uI66kTHvvE4Fs/giphy.gif)

**Environment**
 - OS: [Windows 10]
 - RuneLite version: [1.6.9]
 - Launcher version: [2.1.0]

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
