### ISSUE TITLE
Black knight cannon spot

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#11045]
There is a requirement to kill 1300 black knights for the Falador diary. This is often done using a cannon. The wiki suggests a good spot: https://oldschool.runescape.wiki/w/White_equipment#/media/File:Cannon_placement_killing_black_knights.png

**Comment by tabbartley** [comment]
What should be done here? A highlighted tile recommending where to place the cannon?

**Comment by Nightfirecat** [comment]
The cannon plugin automatically displays a set of tiles when you have a cannon ready to be set up. This tile should be added to that set.
