### ISSUE TITLE
XP Updater Plugin Doesn't Work

### ISSUE THREAD

**Issue by Nealon01** [runelite/runelite#11040]
I've been reading posts online that say CrystalMathLabs (and I assume TempleORSR) filter out the updates from Runelite due to API spam.  If that's the case (which it certainly appears to be, as my stats are not updating), why does this plugin exist?  To confuse users and make them think their stats are updating when they aren't?  Please fix or remove this plugin.

**Comment by Nealon01** [comment]
Could you elaborate what further information you need?  The plugin doesn't work. Try it yourself.

**Comment by Adam-** [comment]
I don't know if CML is filtering it, but I've talked to the templeosrs owner about this before and I am not aware of them filtering it. Also I doubt it is causing "API spam" since we have it rate limited.

**Comment by Nealon01** [comment]
Ok.  I just checked TempleOSRS and it looks like that one is working now.  It was probably the rate limiter earlier because I had just added my account.  But CML is definitely not working correctly.  What kind of a limit do you have though?  Once per hour?

**Comment by Adam-** [comment]
It triggers at logout if you have gained at least 10k xp since logging in

**Comment by Nealon01** [comment]
Ahh, interesting.  So with that in mind, I checked my calquat tree (12k xp) and then logged out.  TempleOSRS updated, CML did not.

**Comment by Adam-** [comment]
This probably isn't our problem.

**Comment by Nealon01** [comment]
Well, your plugin doesn't work.  So I think it is.  Like I said, you're just misleading users.

**Comment by Adam-** [comment]
The plugin is submitting the request correctly. If CML doesn't work that isn't our concern. I suspect it probably works but only occasionally. We do not own or operate CML or have anything to do with it; so there is nothing to do here.

**Comment by Nealon01** [comment]
You could at least put a note on the plugin informing users of it's unreliability.  I've got weeks of missing chunks of tracked data that I assumed was being tracked.  It would have been nice to know that the plugin was broken.

**Comment by ChakatStormCloud** [comment]
had this turned on for wiseoldman, on 2 characters that so far are at about 300k xp and 200k.

It has not successfully updated the site **even once**. this plugin _**is broken**_ and no amount of "not our issue" will change that. At a bare minimum it needs to show diagnostics, like last attempted update, and offer options to force-send an update.

**Comment by Alexsuperfly** [comment]
if you arnt on the hiscores, there is no data that exists for you to begin with, what is going to be updated?

**Comment by ChakatStormCloud** [comment]
> if you arnt on the hiscores, there is no data that exists for you to begin with, what is going to be updated?
Pretty sure these should be getting updated.
https://wiseoldman.net/players/chakatstorm
https://wiseoldman.net/players/chakat-async

**Comment by YvesW** [comment]
Those accounts are clearly not on the hiscores
https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal

The websites pull the information from Jagex's hiscore API. The plugin is correctly sending the requests, but there's no data for the website to pull. Thus, the plugin is not broken and there's a perfect amount of "not our issue" here.

**Comment by ChakatStormCloud** [comment]
> Those accounts are clearly not on the hiscores https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal
> 
> The websites pull the information from Jagex's hiscore API. The plugin is correctly sending the requests, but there's no data for the website to pull. Thus, the plugin is not broken and there's a perfect amount of "not our issue" here.

wait, so the plugin doesn't even send the skill levels to the website at all, it just tells the website to go grab it itself? what is even the point of it then?

**Comment by cdfisher** [comment]
> > Those accounts are clearly not on the hiscores https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal
> > The websites pull the information from Jagex's hiscore API. The plugin is correctly sending the requests, but there's no data for the website to pull. Thus, the plugin is not broken and there's a perfect amount of "not our issue" here.
> 
> wait, so the plugin doesn't even send the skill levels to the website at all, it just tells the website to go grab it itself? what is even the point of it then? (so the websites can update automatically without getting rate limited obviously, but that is not at all what I think most people expect it be for.)

Most, if not all external experience tracking sites refresh relatively infrequently, so this plugin tells them that it's necessary to refresh the information for a given account, more or less.
