### ISSUE TITLE
runecrafting plugin needs to be better

### ISSUE THREAD

**Issue by Battulga93** [runelite/runelite#11054]
please we need ring of dueling swape beetwheen duel arena and castle wars this would help for runecrafting so much and make it easier. we need autoswapper between duel arena and castle wars! i don't even get 50k xp per hour when i following guide switch says 70k plus xp per hour. even if i use f keys it still not get up to 70k xp not even close. so swaping in equipment interface is all people need for runecrafting! i use all 3 pouches. some people can get 70k xp plus and thats not fair because i don't even get 50k xp per hour when i do fast i can.

**Comment by dekvall** [comment]
According to Jagex's recent [statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1) any menu modifications on worn/equipped items are not permitted.
