### ISSUE TITLE
Stretched Fixed Mode Artifacts

### ISSUE THREAD

**Issue by MESLewis** [runelite/runelite#1105]
When the window is resized the old content is never cleared.
The image is a result of shrinking the width of the window, causing the client to shrink.

Running on Intel Integrated Graphics.  Java 1.8

![image](https://user-images.githubusercontent.com/597053/37871508-991c9530-2fac-11e8-8459-5dc4e6dc19fd.png)

**Comment by MESLewis** [comment]
I looked into the code but I can't find exactly what panel that would be to clear. Hopefully someone who has been involved longer can figure it out /  point me in the right direction.

**Comment by devLotto** [comment]
Definitely something related to the GPU, since I get this same problem when the client is positioned on a monitor I have hooked up to my motherboard, but not when it's on a monitor hooked up to my dedicated GPU.

**Comment by deathbeam** [comment]
This was fixed in #1565
