### ISSUE TITLE
Fix GPU Plugin

### ISSUE THREAD

**Issue by xDeklab** [runelite/runelite#11059]
GPU plugin broke for a lot of people overnight.
Client doesn't boot and I have to go through the powershell method to fix, then kill processes to enable again.
Windows Version 1903 (OS Build 18362.720)

**Comment by Nightfirecat** [comment]
We have not made any updates to the GPU plugin, or RuneLite actually, in nearly three weeks. I recommend you check whether you have made any system changes (such as graphics driver updates) and potentially revert those.

**Comment by xDeklab** [comment]
No windows driver updates were made, nor any GPU ones according to windows update history/GeForce Experience

**Comment by xDeklab** [comment]
Furthermore, I rolled back the GPU drivers anyway - did not fix the issue.
This started for me following the addition of temporary OSRS worlds.

**Comment by xDeklab** [comment]
Bump
