### ISSUE TITLE
[Suggestion] GE Tracker to see how much profit you made

### ISSUE THREAD

**Issue by satinof** [runelite/runelite#11050]

**Comment by ypperlig** [comment]
There's this which was recently merged for the plugin hub:
https://github.com/runelite/plugin-hub/pull/167

**Comment by LlemonDuck** [comment]
This can be done with either of these hub plugins:
* https://runelite.net/plugin-hub/show/flipping-utilities
* https://runelite.net/plugin-hub/show/flipper
