### ISSUE TITLE
Suggestion: Notification based on the HP of your target

### ISSUE THREAD

**Issue by Mooshake** [runelite/runelite#11051]
I have been afk farming brutal black dragons a lot recently and sometimes get too absorbed into the Netflix show I'm watching. An easy solution for this (besides paying more attention to the game) would be a notification based on the HP of your target. 

For example, if the monster you are fighting falls below a customizable percentage (10%) or a customizable hard HP number (30) the client would send a notification similar to being low on prayer points.

This is far from a necessity, but it would greatly cut back on the pointless damage I'm taking while farming dragons.

**Comment by Callum-A** [comment]
I have just finished working on a plugin that does just that, here is the [link](https://github.com/Callum-A/health-notifier-runelite) for it. Feel free to get back to me with any bugs.

**Comment by Nightfirecat** [comment]
@Callum-A Has this been added to the plugin hub? If so, does this address this request @Mooshake?

**Comment by Callum-A** [comment]
@Nightfirecat I have just created a PR to add it to the plugin hub, so I believe it does address the request from @Mooshake

**Comment by Nightfirecat** [comment]
:+1: 

Closed by runelite/plugin-hub#182
