### ISSUE TITLE
Inability to minimize RuneLite on MacOS

### ISSUE THREAD

**Issue by SomeRangerOSRS** [runelite/runelite#11067]
**Describe the bug**
I'm unable to minimize the client on any machine running MacOS. When attempting to, it'll either do nothing or it will resize the window. 

If the window is already maximized and you attempt to minimize the window, it'll cause the window to just resize to a smaller screen. If the screen is not currently maximized and you press the button to minimize it, nothing happens at all.

**Expected behavior**
Minimize the application. 

**Screenshots**

**Environment (please complete the following information):**
- macOS Catalina 10.15.4 (19E266)
- RuneLite Version 1.6.9
- Launcher Version 1.6.1
- RuneScape Version Rev 188

https://youtu.be/Al4JVJ_QN2Y

**Comment by SomeRangerOSRS** [comment]
I just found this from back in 2018 

https://github.com/runelite/runelite/issues/2967

**Comment by Nightfirecat** [comment]
Does this work properly if you run from the jar rather than the dmg?

Given that 2967 seems to be largely the same issue (minus the rest of the UI locking up after clicking the minimize button), I am closing this as a duplicate. Please feel free to post there.
