### ISSUE TITLE
Shift Click Teleport on Equipped Capes

### ISSUE THREAD

**Issue by SomeRangerOSRS** [runelite/runelite#11073]
**Is your feature request related to a problem? Please describe.**
The ability to move the teleport option to the top when holding shift on capes that we have equipped instead of the option being "Remove" 

**Describe the solution you'd like**
Teleport Option goes to the top when holding the shift key.

**Comment by Hydrox6** [comment]
This is banned under [Jagex's Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Modifies the menu options on worn/equipped items`
