### ISSUE TITLE
Runelite Black Screen after newest update

### ISSUE THREAD

**Issue by thatonekj** [runelite/runelite#11080]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by thatonekj** [comment]
GPU option was OFF, changing it didnt help with the issue

**Comment by tylercamp** [comment]
OSRS is having some technical difficulties, not much that can be done until Jagex fixes things

**Comment by abextm** [comment]
https://twitter.com/OldSchoolRS/status/1243156082631086081
