### ISSUE TITLE
Screenshots not being saved automatically.

### ISSUE THREAD

**Issue by Cxxkiee** [runelite/runelite#11083]
Runelite hasn't been saving automatically taken screenshots.
Checked all settings and appears to be correct.

Taking a manual screenshot it gets saved.

**Comment by Nightfirecat** [comment]
You're not the first person who has reported this as being an issue, but as of now we don't have enough information to diagnose this issue. Can you please upload your client logs and describe some situations you would expect a screenshot to be taken but didn't get one?

Also, are you checking the new sub-folders in your screenshots folder? [Our 1.6.9 release added screenshot sub-folders](https://runelite.net/blog/show/2020-03-05-1.6.9-Release) so you might need to check a slightly different location for most of the automatic screenshots.

**Comment by Cxxkiee** [comment]
Ah that is it didn't see those new sub folders.

Thanks for you help!
