### ISSUE TITLE
Resizable overlays/widgets.

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11086]
Resize option for Widgets like:
World map, minimap:
Motherlode Mine overlays:
Xp/H Canvas
XP orbs

Furthermore, changing font style/size would be a nice addition for them.

**Comment by Nightfirecat** [comment]
Deathbeam's old PR, #4509, would address this. (I'm not sure why it was closed though)

**Comment by Pingvinszar2** [comment]
> 
> 
> Deathbeam's old PR, #4509, would address this. (I'm not sure why it was closed though)

Yeah, exactly, although I have never found it out, how to use it.
That's the reason, I have requested it once more, so I either would find it out, why it was removed, or it'd get added once more.

**Comment by dekvall** [comment]
Added in #11188
