### ISSUE TITLE
Client does not run since update to 1.6.10

### ISSUE THREAD

**Issue by SimplyComplexable** [runelite/runelite#11084]
**Describe the bug**
The app starts up like normal then goes to a "Check For Updates" screen, and eventually goes black.

**To Reproduce**
1. Start the client

**Expected behavior**
It should run

**Screenshots**
![image](https://user-images.githubusercontent.com/8563846/77660361-d7f47880-6f3e-11ea-94c6-979c86d250bd.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - RuneLite version:  1.6.10
 - Launcher version:  2.11

**Comment by abextm** [comment]
Jagex are fixing the servers. For updates, follow this thread: https://twitter.com/OldSchoolRS/status/1243156082631086081

**Comment by SimplyComplexable** [comment]
Thanks!
