### ISSUE TITLE
Grand Exchange Limit restart timer

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11088]
After you've bought out your limit. (eg. 20k fire runes) , the plugin shows you, how much time you have left, until you can buy it again.

The plugin also shows you, how much more you can buy until trade limit.

Adds you widgets in your game so you can monitor your G.E offers.

a) Ability to customize to show buys-only, sales only, both.
b) Ability to high-light certain transactions.

**Comment by Belieal** [comment]
This feature has recently been implemented in my [external plugin.](https://github.com/Belieal/flipping-utilities)

**Comment by Pingvinszar2** [comment]
> 
> 
> This feature has recently been implemented in my [external plugin.](https://github.com/Belieal/flipping-utilities)

Would it be possible for you to make a widget for it to the in-game window as well?

**Comment by Belieal** [comment]
Honestly, I have no idea how to make a widget but I can look into it.

**Comment by Nightfirecat** [comment]
Since the requested feature already exists in an external plugin, I'm closing this request.
