### ISSUE TITLE
Replace Adamant with Adamantite and Rune with Runite for non-magic items.

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11087]
Option to rename Adamant to Adamantite and Rune to Runite and vice-versa for Adamantite/Runite Armour/Weapon/Tools to give players the option to make materials AND crafted goods' names more unified. (Eg. Rune Pickaxe to Runite Pickaxe)

**Comment by Nightfirecat** [comment]
I don't think we want to rename items in a way which would confuse users. `adamantite` and `runite` refer to raw materials and `adamant` and `rune` refer to finished products, and that is already consistent throughout the client.

**Comment by Pingvinszar2** [comment]
I don't think, it would cause any confusion.

I wouldn't say, that it's consistent in any way, here's an example why:
Based on, what you're saying, "adamant and rune" refer to finished products:
If bolts are finished products, why are they named "Runite"?
if they are NOT finished products, why are they named "Adamant"?


In the other hand, this would allow players to somewhat filter their search results in g.e from magical items mostly.

The option by default would be turned off, so this would for sure be a good way to avoid confusion.

**Comment by Nightfirecat** [comment]
That is the only case I can think of which breaks that rule, and a request to Jagex could likely resolve that inconsistency. My point is that this feature sounds so niche that few players would find real benefit from it, while it would likely require a significant dev effort to add to the client.

**Comment by abextm** [comment]
It would also break wiki and ge lookups, and ground item filters, and make anyone who got used to this sound like a weirdo in conversation.
