### ISSUE TITLE
Grand Exchange Categories Plugin

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11085]
1) Create Categories:
Melee Armour
Magic/Runecrafting
Ranged/Fletching
Herblore/Farming/
Mining/Smithing
Crafting/Construction
Fishing/Cooking
Firemaking/Woodcutting
Grocery (general store) items
Hunter/Slayer
Miscellaneous
etc.

6) Ability to Swap Collect-Note, Collect-Item options
7) In-Game-Window widgets for ongoing transactions
a) Ability to customize to show buys-only, sales only, both.
b) Ability to high-light certain transactions.

**Comment by Nightfirecat** [comment]
Hi, can you please open separate issues for each of these separate feature requests? It is much easier for us to keep track of what code changes address specific feature requests that way.

**Comment by Pingvinszar2** [comment]
> 
> 
> Hi, can you please open separate issues for each of these separate feature requests? It is much easier for us to keep track of what code changes address specific feature requests that way.

Alright, I will try.

**Comment by Nightfirecat** [comment]
(2) already exists, implemented #10447

What would you expect (1) and (3) to look like? I suspect we're unlikely going to be able to accomplish these and these may be better suited as feature requests to Jagex.

**Comment by Pingvinszar2** [comment]
> 
> 
> (2) already exists, implemented #10447
> 
> What would you expect (1) and (3) to look like? I suspect we're unlikely going to be able to accomplish these and these may be better suited as feature requests to Jagex.

1) I would expect the option look like this:
When the game interface prompts for "What would you like to buy?", in addition to the usual search field, there would be additional, clickable, cascaded groups, for example:

Magic/Runecrafting->Runes->*show only runes*

The Interface would look like this:
https://ibb.co/wpz8R1h
https://ibb.co/TkWrnHS

3) The way, Grand Exchange plugin currently shows the G.E offer on the right panel would be just perfect.
Even an expansion of the plugin, like left-click "High-light offer in Game Window" menu (similar to Add canvas in skills tab) would be perfect.

**Comment by Nightfirecat** [comment]
I'm not sure what the purpose of (3) would be... If you already have the GE interface open, why would you need to select one of your offers in the side panel to see where it is ingame? You'd already be looking at it.

As for (1), I don't think this would be valuable as an ingame-style interface. I'm not even sure this would be useful as a plugin. This seems like something that is better covered by a trading website similar to the [OSRS Grand Exchange pages](http://services.runescape.com/m=itemdb_oldschool/).

**Comment by Pingvinszar2** [comment]
> 
> 
> I'm not sure what the purpose of (3) would be... If you already have the GE interface open, why would you need to select one of your offers in the side panel to see where it is ingame? You'd already be looking at it.
> 
> As for (1), I don't think this would be valuable as an ingame-style interface. I'm not even sure this would be useful as a plugin. This seems like something that is better covered by a trading website similar to the [OSRS Grand Exchange pages](http://services.runescape.com/m=itemdb_oldschool/).

3) That would be exactly the point. You could continuously monitor your Grand Exchange offers, WITHOUT having your G.E interface open.
This would be useful when you are doing click-intensive activities like high-alchemy, herb cleaning, etc.

1) The interface would be indeed useful, especially when is an option like "remember last group".
Let me come up with an example:
Someone buys an Iron Scimitar.
In this case, the plugin would store a last browsed group(s) "Scimitars".
From that on, the user (assuming, he wants), can just click the group, then click-and-buy steel-scimitar, black scimitar, etc. up to dragon.
Similar way to arrows, armour-sets, runes, etc.
This option would be especially useful for newly made accounts/pures that wish to prepare themselves the gear in one go, they would need later on.

As an addition, it would be/could be useful, if the player could re-arrange the search result (ie. by required level) rather than alphabetical order.

**Comment by Belieal** [comment]
To your 4th point, a feature like this has passed in the [latest content poll](http://services.runescape.com/m=poll/a=13/oldschool/results.ws?id=1602) (question 16).

**Comment by Pingvinszar2** [comment]
> 
> 
> To your 4th point, a feature like this has passed in the [latest content poll](http://services.runescape.com/m=poll/a=13/oldschool/results.ws?id=1602) (question 16).

> Should we add a 'Last Searched' section to the Grand Exchange to allow you to quickly buy items based on the last thing you entered? This would appear when searching for an item to buy on the Grand Exchange interface.

I guess, this is, what you're trying to point out.

But this is not, what I'm looking for.

Let's say, you're trying to buy multiple type staves.
If you would type in "staff", trident of the seas wouldn't be listed.
In opposition, if you have a "Staff" group, it would be possibly listed there, because it fits the group criteria "staff".

Another example:
Let's say, you want to buy some "rune" armour in parts (fullhelm, platebody, platelegs, kiteshield).

_Problem 1)
Every item, that includes the word "rune" would be listed, this includes magical items, rune arrows, ores, bars, etc. potentinally over 100 results.

Problem 2) 
If you write in "rune f", except the Rune Full helm, nothing else would be listed.
If you write in "rune plate", except Rune kite/full helm wouldn't be listed.
If you write in "rune kite", except rune kite, nothing else would be listed._

So in order to get your complete rune set, you would have to do three different searches.

In opposition to my requested plugin:
There could be a group "rune armour", that would list the items that fit the criteria (med helm, full helm, sq shield, kiteshield, plateskirt, platelegs, chainbody, and platebody).

These were just examples, and I'm not even sure, whether they are the most sensible way to "group" the items.

**Comment by Nightfirecat** [comment]
We likely cannot create such an interface as it would require creating elements which, when clicked, would send server requests which is forbidden. I think #7500 would address most of the concerns in this feature request, if merged.

**Comment by Pingvinszar2** [comment]
> 
> 
> We likely cannot create such an interface as it would require creating elements which, when clicked, would send server requests which is forbidden. I think #7500 would address most of the concerns in this feature request, if merged.

What about this idea:

> I think, the most feasible way to create this system would be this:
> Similar to the current Bank Tags plugin, a player could create a Grand Exchange Tag tabs.
> The player could tag an item with a certain word, so in case an item fits in more categories, they would be shown in all.

**Comment by Nightfirecat** [comment]
You can already search the grand exchange for bank tags. This was added in  #6254

**Comment by Pingvinszar2** [comment]
> 
> 
> You can already search the grand exchange for bank tags. This was added in #6254

Yeah, this would work be perfect.
Would it be possible to add the **Bank Tabs** below the search field?
