### ISSUE TITLE
Loot tracker not tracking correctly 

### ISSUE THREAD

**Issue by bl0delysians** [runelite/runelite#11098]
[client.log](https://github.com/runelite/runelite/files/4389791/client.log)
client log 2:
[client_2020-03-26.0.log](https://github.com/runelite/runelite/files/4389849/client_2020-03-26.0.log)

Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I received a drop in chamber of xeric solo. it was an arcane prayer scroll. runelite took an auto screenshot like it normally does and put it in the screenshot folder as usual. The drop did not show up in the loot tracker though. my gpu plugin is off.

**Screenshots**
screenshot of loot tracker
https://gyazo.com/cbd6ffae90375c9116b1deed885bdd64

screenshot of the drop
https://gyazo.com/2c84aa23a035a9f987524199191bd945

**Environment (please complete the following information):**
 - OS: Mac OSX Mojave 10.14.6
 - RuneLite version: 1.6.10
 - Launcher version: 2.1.1

**Additional context**
![Chambers of Xeric(832) 2020-03-27_00-47-22](https://user-images.githubusercontent.com/62722144/77694230-b0012580-6fcf-11ea-9379-659c26e68d4b.png)

**Comment by Nightfirecat** [comment]
I don't see anything in the logs which would indicate a root cause for this error

**Comment by Hydrox6** [comment]
This is very stale, and probably should have been a Discord Support question instead.
