### ISSUE TITLE
Menu Entry swapper with opened bank Interface

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11096]
Allows you to swamp menu entries while having your bank window open.

This would allow you to Left-Click eat foot, drink potions, fill essence/rune pouches while you are banking.

**Comment by melkypie** [comment]
You can already do it by setting the deposit option eat/wield in menu entry swapper. You just have to hold shift while doing it.

**Comment by Pingvinszar2** [comment]
> 
> 
> You can already do it by setting the deposit option eat/wield in menu entry swapper. You just have to hold shift while doing it.

I would prefer an option without using the Shift key. :)

**Comment by Nightfirecat** [comment]
I do not think we want to add further customization to this. As-is, you can already Shift+click using the menu entry swapper to get the desired behavior.
