### ISSUE TITLE
World Hopper Should Skip Full Worlds

### ISSUE THREAD

**Issue by boguemagnus** [runelite/runelite#11102]
When using the quick-hop functionality of the World Hopper plugin, full worlds are not skipped. The client tries to login to the full world, and if unsuccessful, the client logs-out the player. This is inconvenient.

Please add a toggle which will skip full, or near-full worlds while quick-hopping. This is similar to the already implemented 'Quick-hop out of dangerous worlds' toggle, but will require an additional check to the player-count when attempting to hop worlds. 

Alternatively, this functionality may be made default. When the login to a full world fails, perhaps the plugin could just try the next world, instead of the player being logged-out. I don't think this will work, though, since the failure directly results in being logged-out.

**Comment by Adam-** [comment]
this was fixed in 15b5dd02902b5f86440441009aa82e656458643f
