### ISSUE TITLE
IronMan Ground Drops / NPC Pricing

### ISSUE THREAD

**Issue by ViciousFaye** [runelite/runelite#11101]
**Is your feature request related to a problem? Please describe.**
It's very frustrating to be a Hardcore Iron Man and the ground indicators still show the Grand Exchange Prices.  

**Describe the solution you'd like**
A separate ground indicator ( Named like.. Iron Ground Items or something.. ) 
It would include the Store Buy Price for when selling to NPC's ( preferably the highest one ) and the High Alchemy Price as usual. 

**Additional context**
Maybe also set to where other ground items that are not yours, do not show up so you are not tempted to click them.  It would help when looting from piles 

That is all for now, Thank you for your time and consideration!  You guys are the best <3
![drops](https://user-images.githubusercontent.com/62726588/77704066-49a5e400-6f8a-11ea-9b68-2037dbf52e74.png)

**Comment by Hydrox6** [comment]
You can turn off GE pricing and have it only show HA
You can enable `Only show loot` to have it only show your own stuff
Showing the shop price is interesting, but isn't it basically the same as High Alch price anyway?

**Comment by ViciousFaye** [comment]
It is usually not, its significantly lower

**Comment by ViciousFaye** [comment]
The other reason for requesting a 2nd one instead of just making settings for it, is because i usually play with 2 runelite screens up, while playing on my HCIM and my regular account.  The settings seem to cross over

**Comment by Hydrox6** [comment]
In the update today, support was added for custom config file and/or session file support (`--config` and `--sessionfile` respectively). Using those, you might be able to have an easier time with multiple accounts.
Run RL with `--c --sessionfile="/path/to/new/session/file"` if you're logged in or `--c --config="/path/to/new/config/file"` if you're not.

**Comment by Nightfirecat** [comment]
Displaying shop prices would be extremely niche, and is also based on the intrinsic value of an item which can already be determined by the item's high alch price. Hence, changing your Ground Item plugin settings accordingly should suffice.

Per Hydrox's comment, using custom config/sessions for different RuneLite instances can address this issue for multiple open clients if you wish to use different settings in each of them.
