### ISSUE TITLE
Stretched Mode messes with the mouse 4/5 buttons

### ISSUE THREAD

**Issue by chelabellic** [runelite/runelite#11106]
**Describe the bug**
When enabling Stretched Mode, mouse buttons 4 and 5 are clicking as they used to before the 1.6.10 update. Doesn't matter what options you change for that particular plugin.

**To Reproduce**
1. Go to 'Configuration' on RL
2. Find 'Stretched Mode' on the plugin list
3. Enable it
4. Mouse 4/5 will start clicking as regular mouse buttons like before. Even if you change the settings within, it will still do that.

**Expected behavior**
Stretched mode should not interfere with mouse buttons.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.10
 - Launcher version: 2.1.0

**Additional context**
Had a friend test it too, it does the same bug. We have different gaming mouse. Mine uses Razer Synapse and his does not use any software.

**Comment by Adam-** [comment]
fixed in ec11040150b57803832a07f33e0604a76f2834fa
