### ISSUE TITLE
Music Plugin Area Sound Bug with Woodcutting

### ISSUE THREAD

**Issue by CriminX** [runelite/runelite#11100]
Describe the bug
The woodcutting chopping sound used to be classified as a player area sound but now it is classified as an environment area sound. Muting player area sound will not mute the chopping sound but muting environment sounds will. 

Additionally, the mute other players' area sounds no longer works. I am assuming this is because other players' area sounds are also now classified as environmental. 

To Reproduce
1. Turn on music plugin
2. Mute environmental area sounds
3. Chop wood
4. No sound
5. Unmute environmental area sounds
6. Sound returns

Expected behavior
The woodcutting sound effect should be enabled/disabled with mute player area sounds. 

Environment
 - OS: Windows 10
 - RuneLite version: 1.6.10
 - Launcher version: 1.6.0

Additional context
Possibly related to the server crash after the implementation of the recent game update and new worlds.

**Comment by Adam-** [comment]
This was due to the sound hook being broken internally from the game update. I've fixed it now.
