### ISSUE TITLE
Mouse Button 4/5 usability 

### ISSUE THREAD

**Issue by Leyawin** [runelite/runelite#11107]
**Is your feature request related to a problem? Please describe.**
I used to use my side mouse buttons 4/5 as an alternative m1 for various niche reasons. (Mostly because they're quiet, and I like having the option to use them to not disturb people around me with my loud clicking mouse). Being able to use my mouse buttons as mouse buttons was a feature I enjoyed having. Today's update (26 March 2020) made m4/5 no longer work unless in stretched mode. I'm not sure if this was an intentional change that allows the buttons to still work in stretched mode, but there is absolutely no reason that the functionality of my mouse should be reduced by default.  

**Describe the solution you'd like**
If the update was entirely intentional, give it a toggle. Allow users the choice to disable their side buttons.  

**Describe alternatives you've considered**
Returning to the base client? I dont want to have to switch clients whenever I need to use quieter buttons on my mouse
-- 
Disabling the side buttons is useful for certain things, but having no way to reenable them is extremely frustrating and shouldn't be default.

**Comment by Nightfirecat** [comment]
We changed this functionality to block those buttons as it was problematic to users who would, say, use them as hotkeys for push-to-talk in chat programs such as Discord or Mumble. I would recommend writing a simple [AutoHotKey script](https://www.autohotkey.com/) something to the effect of the following, which would remap mouse4/5 to mouse1 for the RuneLite window:

```
#IfWinActive ahk_class RuneLite
XButton1::Send{LButton}
XButton2::Send{LButton}
```

Furthermore, most games do not consider mouse4 and mouse5 to be the same as mouse1; RuneLite was previously the exception to that, which was unexpected behavior to many users.

**Comment by Nightfirecat** [comment]
A configuration option has been added to the `RuneLite` settings to optionally disable mouse4 and mouse5 in 22235925be7c061d6d3633d67c956f6e003d2147.
