### ISSUE TITLE
Deposit Magic secateurs from equipped items

### ISSUE THREAD

**Issue by Pathemeous** [runelite/runelite#11115]
**Is your feature request related to a problem? Please describe.**
The tool exchange interface does not show the Magic secateurs when they are equipped by the player. It is inconvenient to have to explicitly unequip them.

**Describe the solution you'd like**
I would like the possibility to deposit the Magic secateurs  even when equipped.
- Either the original secateur deposit button is activated in this case (optionally with a visual distinction);
- or there could be a separate button for when the secateurs are equipped vs. the standard button for when they are in the player inventory.
A separate button could be similar to the new 'equipped items' button in the bank interface.

**Describe alternatives you've considered**
An extended solution would be an option to 'Deposit all', that also deposits equipped Magic secateurs, as well as any other farming tools in the player inventory.

**Additional context**
I am not sure whether Jagex will allow this, or whether this feature request should go to the OSRS devs directly.
I did not find any similar requests in the Runelite issue tracker or via Google.
Changing menus is in many cases [not considered acceptable](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features), however this feature cannot be used to gain any advantage and is simply a quality of life improvement.

**Comment by Nightfirecat** [comment]
This is not possible for us to do, please direct this request to the OSRS team.
