### ISSUE TITLE
Cannot set a name for new character

### ISSUE THREAD

**Issue by WhiteSp1rit** [runelite/runelite#11116]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I cannot set a name for new character.
No matter what I enter, even completely random combinations of characters, the "Set Name" button never becomes active. Also, the "Display Name" filed stays empty even when I enter something.
Getting past the "set name" screen is impossible so can't actually play the game.

**To Reproduce**
1. Create a new character
2. Attempt to set a name

**Expected behavior**
Should be able to set the name.

**Screenshots**
![RuneLite - #Player1516_20200328_145759_01](https://user-images.githubusercontent.com/7308007/77823781-90fcb380-70f5-11ea-951f-459e554d38f3.jpg)

**Environment (please complete the following information):**
 - OS: Linux Manjaro KDE x64
 - RuneLite version: 1.6.10.1
 - Launcher version: 2.1.0

**Comment by Hydrox6** [comment]
Try pressing Enter

Either way, this is not a RL issue
