### ISSUE TITLE
Loot Tracker Registers CoX Completions on Opening Rewards Chest

### ISSUE THREAD

**Issue by trelkins3** [runelite/runelite#11114]
**Description**
Loot tracker counts Chambers of Xeric loot based on the number of times the rewards chest is opened rather than actual completions. Opening the chest multiple times at the end of the raid raises the completion count and numbers of each item looted despite only a single real completion.

**To Reproduce**
1. Open loot tracker
2. Finish CoX
3. Open rewards chest, close it without withdrawing items
4. Open again - CoX completions and number of items in loot tracker will increase

**Expected behavior**
CoX loot tracker entry should increase based on actual completions and not chests being opened. Might be a tricky implementation but maybe there are events that could gate the logic? ex. saving the loot from the raid and then clearing that info once the raid is exited?

**Environment**
Windows 7/10, RL v1.6.10.1

**Comment by trelkins3** [comment]
It looks like for this to happen you have to step at least one tile away from the chest before opening it again. I also haven't been able to get it to count past 2 entries with just 1 raid - maybe it has something to do with the fact it was in a duo?

**Comment by Hydrox6** [comment]
Pretty sure this was fixed in #9334, and the only way to break that would be to cause the client to go into a `LOADING` state between each opening of the chest. 
@Nightfirecat might be interested in this.

**Comment by Nightfirecat** [comment]
I agree, I don't see how this can be reproduced in the way you're describing. Can you provide logs from the day you saw this behavior or a video of this happening?

**Comment by basicDamen** [comment]
> I agree, I don't see how this can be reproduced in the way you're describing. Can you provide logs from the day you saw this behavior or a video of this happening?

`public void onWidgetLoaded(WidgetLoaded widgetLoaded)
	{
		final String event;
		final ItemContainer container;
		switch (widgetLoaded.getGroupId())
		{
			case (WidgetID.BARROWS_REWARD_GROUP_ID):
				event = "Barrows";
				container = client.getItemContainer(InventoryID.BARROWS_REWARD);
				break;
			case (WidgetID.CHAMBERS_OF_XERIC_REWARD_GROUP_ID):
				if (chestLooted)
				{
					return;
				}
				event = "Chambers of Xeric";
				container = client.getItemContainer(InventoryID.CHAMBERS_OF_XERIC_CHEST);
				chestLooted = true;
				break;`

The only two things that set the chestLooted variable to false are the plugin _shutdown_ and _onGameStateChanged_ methods.

As Nightfirecat stated, we'd need a video of seeing exactly what you are doing to cause this to take place. If you're just simply opening and re-opening the chest without doing anything further, then let us know. Unless, you're adding further steps to make this possible within the plugin's current state.

**Comment by trelkins3** [comment]
Let me see if I can run another duo raid and pull video or logs, if I can't we can just close as 'not reproducible'. It did seem weird that it only duplicated a single time, and I haven't tried it on raids with more or less than 2 people. Like I said though, you have to step away from the chest a few tiles for this to happen.

Bear with me a few days - don't have much time to play during the week because of work and social obligations.

**Comment by trelkins3** [comment]
Friend and I were able to get it to replicate on video: https://www.youtube.com/watch?v=DRgRkqTxti0

@Nightfirecat

**Comment by trelkins3** [comment]
@Nightfirecat @Hydrox6 I am still pretty new to the architecture of RuneLite - is there specifically a raids plugin or would this be some sort of misbehavior in the loot tracker plugin? I feel like there would have to be raids specific behaviors with some sort of limiting condition bug that could be tweaked.

**Comment by Nightfirecat** [comment]
As Hydrox mentioned, #9334 is where we added prevention for duplicate chest loot events. If you can figure out how that code is wrong, or get a client log (with the log level set to debug), that would be appreciated.

**Comment by basicDamen** [comment]
@Nightfirecat -> What about an instanced region check added to both? Once you loot a COX or TOB chest, you can’t do another run without restarting an instanced raid. Therefore, if you use a gamestate change event and check if in an instance.. it will likely help. I’m assuming it’s just not strict enough and maybe is throwing something near the edge.. but, there’s no way to not be in the instance and reloot a chest. 🤷🏼‍♂️ Food for thought. - I can test the addition and see what she shows.

**Comment by trelkins3** [comment]
@basicDamen nice, that is an awesome solution if it works. Also apologies, I glazed over Hydrox's link there. Thanks for the info!
