### ISSUE TITLE
Bank: Left-Click Unnote-Last item [x] (Possible?)

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11119]
I expect the option work similarly to the fairy rings.

The option would allow you to left-click unnote your items without having to use them on bank clerk/chest/booth.

**Comment by Hydrox6** [comment]
Banned by [Jagex's Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Adds additional menu entries which cause actions to be sent to the server`

Please read this before opening any more issues
