### ISSUE TITLE
Grand Exchange: Left-Click Repeat Last Buy Offer, Repeat Last Sell-Offer

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11113]
Title is obvious.

I'm looking for left-click options in Grand-exchange window.

Below "Create Buy Offer", I expect a "Repeat Last Buy Offer" menu added.
Below "Create Sell Offer", I would expect a "Repeat Last Sell Offer" menu added.

**Comment by Nightfirecat** [comment]
We are not able to add this feature. Please request this of the OSRS team.
