### ISSUE TITLE
In-Game Window Notes:

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11123]
I expect this feature to work exactly the same way it used to work on RS3.

![](https://i.ibb.co/gSfLbHp/38767355-4beef9dc-3fe8-11e8-8cec-22beff971d4a.png)

**Comment by Hydrox6** [comment]
We already have the notes in the sidebar

**Comment by Pingvinszar2** [comment]
> 
> 
> We already have the notes in the sidebar

I would like this to be moved in the game window. Would that be possible?

**Comment by Hydrox6** [comment]
Adding an extra UI stone AND creating a notes UI isn't something we can feasibly do at the moment.
