### ISSUE TITLE
Clue scroll kc chat command

### ISSUE THREAD

**Issue by Barry-Batser** [runelite/runelite#11129]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to show off my clue kc in chat. For all tiers but especially per clue tier. Just like with bosses. Otherwise I got to 1150 medium clues for nothing.''

For example, a chat command;
!Kc easy clue
!Kc medium clue
etc...

**Describe alternatives you've considered**

**Additional context**

**Comment by Kamielvf** [comment]
`!clues (easy/medium/hard/elite/master/all)` already does this.
