### ISSUE TITLE
Skill tab:Information filtering

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11121]
I expect an option, that adds/removes the following information when hovering over a skill:

a) [Skill] xp:
b) Next level at:
c) Remaining XP:

In addition, a percentage bar when hovering over the skills would be useful in my opinion.

**Comment by melkypie** [comment]
I believe for the last part Skills Progress Bars (a plugin on plugin-hub) is something you will want. For the others I don't see any reason to do that, since it is just basically a tooltip that appears on mouse hover and don't believe there is any useful reason for anyone to commit their time to make something like that.

**Comment by Nightfirecat** [comment]
Each of the three pieces of information are already shown in an ingame tooltip when hovering a skill. Is this request to add an option to remove any or all of those items from the tooltip? I don't think it would be worth the time and effort to add a feature to remove features from what is already present ingame.

**Comment by Pingvinszar2** [comment]
> 
> 
> Each of the three pieces of information are already shown in an ingame tooltip when hovering a skill. Is this request to add an option to remove any or all of those items from the tooltip? I don't think it would be worth the time and effort to add a feature to remove features from what is already present ingame.

Yes, the goal of the plugin would be to partially (or completely) hide the tooltips when hovering a skill.

The point of this plugin would be the following:
The user could hide information they deem annoying or unneeded.
For instance, I would only like to see remaining exp, nothing else.
Other probably would like to see current XP only, or any combination of the above ones.

**Comment by Nightfirecat** [comment]
Since the skills menu is unlike the magic or prayer menu in that players do not have any pressing need to hide or minimize tooltips so they can accurately see and rapidly click on the others, I think this request is too niche to be useful to most other players. Hence, I am closing this request.
