### ISSUE TITLE
Custom Cursor Custom Image problem.

### ISSUE THREAD

**Issue by Incubliss** [runelite/runelite#11135]
I'm not sure how to contact the plugin developer directly, but the Custom Cursor's new Custom Image option doesn't seem to work. 

I've pasted a 32x32 image titled "cursor.png" into the runelite folder the application is in, as well as the cursor folder deeper inside, but my custom cursor won't show up when selecting the option despite this.

If there is further instruction than "The custom cursor plugin now allows user-supplied cursors by placing a file named cursor.png in your .runelite directory." then I'm not finding it.

**Comment by Nightfirecat** [comment]
This is a tracker for application bugs, not for feature support. I recommend [joining our Discord server](https://runelite.net/discord) and seeking support in our `#support` channel.
