### ISSUE TITLE
New Interface Option (2012)

### ISSUE THREAD

**Issue by TyLags** [runelite/runelite#11136]
Since we have the 05-06 interface along with the 2010-2011 Interface, can we please get a 2012 interface option too? 
![5B105F77-D621-439C-853A-AA04A4BCBB60](https://user-images.githubusercontent.com/62826798/77842479-a5c26100-7160-11ea-85d2-3e5423c2c2af.png)

**Comment by melkypie** [comment]
This interface style has been added to the plugin-hub plugin resource packs. Look here on how to get it https://github.com/melkypie/resource-packs
