### ISSUE TITLE
NPC Tags on Farming NPCs Disappear on Relaunch

### ISSUE THREAD

**Issue by nseguin42** [runelite/runelite#11145]
When a farming NPC such as Nikkie (Fruit Tree patch at Farming Guild) is tagged with the NPC tagger plugin, the tag is lost upon relaunching Runelite. I have tested with the NPC at every fruit tree patch.

**Comment by TheFlemoid** [comment]
Are you tagging the NPCs by typing their name in the text field in the NPC Indicator plugin, or by shift + right clicking them?  The tag will not persist with the shift + right click method.

**Comment by nseguin42** [comment]
> Are you tagging the NPCs by typing their name in the text field in the NPC Indicator plugin, or by shift + right clicking them? The tag will not persist with the shift + right click method.

The latter. Thanks.
