### ISSUE TITLE
Idle Animation Notification triggered by fishing karambwans

### ISSUE THREAD

**Issue by plazmach** [runelite/runelite#11144]
After clicking a karambwan spot, then off client to another window, an idle notification is triggered at the _start_ of fishing if "Idle _Animation_ Notifications" box is checked.

This does not come from "Idle Interactions Notifications" like with most fishing. It triggers before fishing.

With notification delay at 0ms, it seems to trigger right as the player reaches the spot, before fishing animation can be seen.

**Environment**
 - OS: Windows 10, 64bit
 - RuneLite version: 1.6.10
 - Launcher version: 2.1.0

**Comment by Nightfirecat** [comment]
I'm pretty sure this simply comes from having a notification delay of 0ms, as that will notify for most things as even a momentary animation delay would trigger it. Does this happen with a delay of `2000ms`?

**Comment by plazmach** [comment]
I first noticed it at 1000ms, just tested 1000 again and it still triggers.
But at 2000ms it does not.

Seems I misunderstood the function of the delay; thought it was the amount of time to delay only the notification, not increase the trigger window.

The Wiki notes the workaround, and it's good enough. Just thought it was karambwan specific.
