### ISSUE TITLE
FPS drops while scrolling sidebar menu

### ISSUE THREAD

**Issue by Erksike** [runelite/runelite#11153]
Whenever I scroll through the sidebar menu with my mouse, or through the settings and tabs themselves, my fps drops as low as 15. 
Windows 10 OS
CPU - Ryzen 5 2600
GPU - GT 1030 
16GB RAM

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
