### ISSUE TITLE
Daily task indicators: Don't send Herb Box notifications to Ironmen by default

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1116]
Ironmen can't buy Herb Boxes from NMZ (btw), so there is no point in sending notifications.

**Comment by Infinitay** [comment]
I was thinking of disabling every option by default anyways, I will push it right now and if Adam or anyone else wants, they can merge it

**Comment by Infinitay** [comment]
Just pushed a lame solution #1119
