### ISSUE TITLE
Suggestion: Ground Items Plugin Addition

### ISSUE THREAD

**Issue by the88shrimp** [runelite/runelite#11168]
**Is your feature request related to a problem? Please describe.**
For Ironmen the color coded items based on value (be it G.E. value or Alch value) aren't overall very useful as a lot of unique's alch value aren't related to their G.E. or actual value and at the same time G.E. value isn't useful.

**Describe the solution you'd like**
An interesting idea I had was to have multiple input boxes each with their own corresponding color for highlighting items. Take the **Highlighted Items** section of the plugin and change that to have multiple boxes for highlighted items each with their own color. E.g. you could have herbs in one box and highlight it green, alchs in another and highlight it in gold, untradable uniques in another color, resources in another etc.

**Describe alternatives you've considered**
I can't really think of an alternative

**Additional context**
I guess a TL;DR would be to split or add more **Highlighted Items** boxes each with a color code for highlighting. Such as Highlighted Items #1 set to green, Highlighted Items #2 set to blue etc.

**Comment by Hydrox6** [comment]
Closing in favour of #12274
