### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by 1urbik1** [runelite/runelite#11162]
Hello, when im trying to login in game or hop worlds i have 9 out 10 attemps message CONNECTION TIMED OUT. Try using a different world. Either lan or wifi. So logging into game takes me every time like 10minutes.
 I think its probably some secure related problem - im using secured network in hospital.
Recently i installed linux and before that it worked just fine on vista.
On ipad/mobile i can log in only with vpn and never got connection timed out error.
When i try it like i said few times it lets me in, sometimes first attemp sometimes 10th attemp. Sometimes i can log out/hop without problem sometimes im trying to log in half hour.
Havent tried vpn on pc yet. 

I have tried almost all worlds - same - sometimes 1 attemp works sometimes trying to log in 10min
When i use vpn mobile hotspot never get connection time out

Any advice pls? every help would be apreciated
Thanks all And sorry for my bad english

**Comment by Nightfirecat** [comment]
Are you seeing the same behavior with the vanilla client? I doubt this is related to RuneLite and is instead an issue of your connection to Jagex's servers.

I suggest [joining our Discord server](https://runelite.net/discord) and seeking further help with this issue in our `#support` channel there.
