### ISSUE TITLE
OSRS WIKI Expansion: a) Search results on Sidebar b) Search summary in the Chatbox. c) Floating Wiki

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11166]
The title is very self-explanatory.

I'm looking for a plugin expansion for the current *OSRS Wiki plugin*

These features would allow you to: 
1) Rather than opening up a web browser, the search results would be shown in the Sidebar.
2) The search results would be shown (clickable if multible) in the chatbox. (Only text or very small images are shown). 
Players would also have the option to:
a) Show essential information only. 
b) Show all information/scrollable wiki-in-chatbox.
3) Similarly to the current **World Map plugin** there could be a (preferably resizable) floating widget for OSRS WIKI (illustration images could be shown here).

**Comment by abextm** [comment]
Duplicate #3038

**Comment by Pingvinszar2** [comment]
> 
> 
> Duplicate #3038

...and the rest?

**Comment by abextm** [comment]
1) is #3038
2) is either #3038, not possible, or already implemented
3) is also #3038

**Comment by Pingvinszar2** [comment]
> 
> 
>     1. is #3038
> 
>     2. is either #3038, not possible, or already implemented
> 
>     3. is also #3038

if it's already implemented, I haven't found out about it yet.
Could you please explain, how could I display a floating OSRS Wiki **in the game window?**

**Comment by abextm** [comment]
displaying anything that is not the existing search results would be what is described in #3038, which we are not doing because we are not embedding a browser in the client.
