### ISSUE TITLE
Idle Notifier should not notify when starting fishing

### ISSUE THREAD

**Issue by alaaneme** [runelite/runelite#11179]
Idle Notifier plugin's option "Idle Animation Notifications" also notifies when you are off screen when starting the fishing animation. That happens every time you click on a fishing spot far away and then go off RuneLite screen to do other things. That means that unless I open RuneLite window to get rid of the notification, I don't know when the next notification appears e.g. I stop fishing - quite annoying.

This behaviour is ofcourse expected, because the animation changes and that's why this is a feature request not a bug report. In this case (starting fishing animation) it shouldn't notify in my opinion. I see no situation where you would want to get a notification when starting fishing. My request would be to exclude "starting fishing" from "Idle Animation Notifications".

**Comment by Nightfirecat** [comment]
What is your Idle Notification Delay set to?

**Comment by alaaneme** [comment]
I usually have set it to 1 second. Now I tested with higher values (like 2s) and the problem is gone. I wonder why that helps? The animation is still 'changed' after 2 seconds

**Comment by Nightfirecat** [comment]
There is often a delay for certain activities where an animation will start late even if you're doing the activity--fishing is a common culprit. Setting the delay just a little higher like you did usually covers those edge cases.
