### ISSUE TITLE
Sire hitpoints won't show as absolute values, only percentage

### ISSUE THREAD

**Issue by jbillman** [runelite/runelite#11173]
I tried setting opponent information to hitpoint and both and neither would show sire hp as values instead of a percentage. Same behavior on the vents. Both used to show absolute values.

**Comment by Nightfirecat** [comment]
I'm not able to reproduce this for sire itself, and I see its hitpoints and combat level present in the NPC stats JSON file. Can you upload your `client.log` file please?

**Comment by jbillman** [comment]
I'm going to try changing the setting and then closing the client to see if that changes anything

**Comment by jbillman** [comment]
Weird, closing and reopening worked. My mistake.
