### ISSUE TITLE
Add a way to edit bounds for boosts/timers

### ISSUE THREAD

**Issue by Rebirthh** [runelite/runelite#1117]
When stat boosts/timers are being used, if you're, for example, super combatted, mage potted, and range potted, all stats line up horizontally along with boss timers. Leads to a really cluttered screen if you're on fixed. Suggesting a way to edit the bounds such that they can stack say, in a 3 column grid vertically?

**Comment by ShaunDreclin** [comment]
Yeah there should be options for
- Horizontal growth direction
- Vertical growth direction
- Length before wrapping

**Comment by sethtroll** [comment]
Added in #1248
