### ISSUE TITLE
Runelite fatal error 

### ISSUE THREAD

**Issue by boxofpoop** [runelite/runelite#11174]
Upon launching the client I will get the message that Runelite encountered a fatal error while loading the client. I have reinstalled the latest version of Runelite and Java.

Thanks in advance for the help! 

The error in the logs are the following:
[au18Ch9K.txt](https://github.com/runelite/runelite/files/4423990/au18Ch9K.txt)

**Comment by ypperlig** [comment]
I recommend joining the Discord https://runelite.net/discord for support as this is not a support forum.
