### ISSUE TITLE
Own deaths will be screenshotted if 'Screenshot Friend Deaths' is on and 'Screenshot Deaths' off

### ISSUE THREAD

**Issue by Allemaalbaas** [runelite/runelite#11184]
**Describe the bug**
Runelite will screenshot your deaths eventhough 'Screenshot Deaths' is off

**To Reproduce**
1. Go to 'Screenshot Settings'
2. Toggle 'Screenshot Friend Deaths' on and 'Screenshot Deaths' off

**Expected behavior**
Runelite will screenshot your deaths eventhough 'Screenshot Deaths' is off

**Environment:**
 - OS: Windows
 - RuneLite version: 1.6.10.1
 - Launcher version: 1.6.0

**Comment by Alexsuperfly** [comment]
looks like a check for `player != client.getLocalPlayer()` should be done [here](https://github.com/runelite/runelite/blob/c703a35f15fa25f99437953b7e76d28e44105863/runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java#L252)

**Comment by Adam-** [comment]
fixed in edcfeb25fdf99d47d6fce8b9b7c4eaa30f85b687
