### ISSUE TITLE
Fully charged Dragonfire Ward (Bank tag)

### ISSUE THREAD

**Issue by 1337Mo** [runelite/runelite#11185]
The Dragonfire Ward when fully charged, not sure about it being uncharged either, always disappears from the Bank Tag when withdrawn. 

For instance: I click on Elite void top, it becomes invisible in the bank tag with value set to 0, as in there isn't any Elite void tops in that slot but it is reserved.

When I withdraw the ward, it simply disappears, and is no longer there in the bank tag (while I have it in invo or equipped), however, when I deposit all my items back, it returns to the bank tag slot. 

It's just a bit irritating because when it disappears, it sort of messes my clicks while withdrawing other items. 

Thought I'd share for QOL update. :)

**Comment by Hydrox6** [comment]
Use Variation tagging, either by adding a `*` after the tag, or by shift dragging it to the tag tab
