### ISSUE TITLE
Add offset value for Eternal Teleport Crystal in the ItemsKeptOnDeath plugin

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#11187]
With the [2020 Easter Event update](https://secure.runescape.com/m=news/a=13/easter-event?oldschool=1), Jagex made the Eternal Teleport Crystal "prioritised over a greater selection of other items on death". As the store price of the item is the same, the item will now have an offset for use in death scenarios.

**Comment by thomaschow** [comment]
@Hydrox6  how do we determine the offset value?

**Comment by Hydrox6** [comment]
The vanilla kept-on-death interface shows the value of the item with offset if you're risking it.

**Comment by 000000653** [comment]
The offset is 78500
