### ISSUE TITLE
GE Tracker

### ISSUE THREAD

**Issue by osrsexo** [runelite/runelite#11186]
I'm not sure but I think GE tracker only uses the data from osb.
because that is not the main client anymore it has become fairly inaccurate with items traded with a low quantity.

I would like to see a plugin where we can see the actively traded prices from runelite so that they're more accurate.

To further discribe my problem i'd like to take the new nightmare items as an example. I've come to the point where screenshots of transactions are more accurate than ge-tracker which frustrates me.

The reason I'm suggesting this is because I dislike being kept in the dark with outdated prices on the ge/ge-tracker.

**Comment by Hydrox6** [comment]
RL uses Jagex data. The only data we use from OSB is the (optional) "actively traded price" display in the GE interface. 

GE Tracking is not something we want to do, as we would have absolutely no way to ensure the data is accurate, so it would be defaced and manipulated heavily, and would therefore be useless.

**Comment by osrsexo** [comment]
is there not something similar Runelite can develop because the OSB "actively traded price" on low quantity traded item's is useless. What would be the point of using OSB data anyway?

**Comment by Hydrox6** [comment]
We didn't want OSB data initially, but after a lot of desire for it, it was added as a small option, and nothing more. It's still there since it doesn't really do any harm.

Read my second paragraph again for the answer to the rest of your comment.

**Comment by osrsexo** [comment]
I read your 2nd paragraph, what I meant by my comment was,
OSB is influenced even easier as that playerbase has grown a lot smaller. 
Because there is a lot of desire for this plugin why not add the data of runelite which would make it more reliable.

Or is there something I'm not seeing? 
would it not be as easy as to say data of a bigger playerbase is more reliable?

**Comment by Hydrox6** [comment]
> We would have absolutely no way to ensure the data is accurate, so it would be defaced and manipulated heavily, and would therefore be useless.

**Comment by osrsexo** [comment]
you said that, but what would then be the point of putting the plugin in with osb data as that would be useless aswell

**Comment by Nightfirecat** [comment]
As Hydrox said earlier:

> We didn't want OSB data initially, but after a lot of desire for it, it was added as a small option, and nothing more.

I don't see any further discussion being valuable on this topic, so I am locking this issue. If you'd like to discuss this further, you can do so in our `#runelite` Discord channel.
