### ISSUE TITLE
Blackjacking - Status indication

### ISSUE THREAD

**Issue by MantaDroid** [runelite/runelite#11196]
**Is your feature request related to a problem? Please describe.**
While blackjacking, it can be hard at times to determine whether the NPC is knocked out or not. This is due to

1. NPC model looking bugged depending on square they're standing at
2. When you try to knock them out it can at times take a few tries before you finally knock them out.

**Describe the solution you'd like**
Some kind of clear status indication, such as red colour around the npc (like tag-function) when they're not knocked out and green when they're knocked out. 

This is to make it clear when the NPC is to be pickpocketed, which will be quite helpful when knocking them out.

Example image: https://i.imgur.com/MQQpFHU.png

Sometimes when knocking them out in succesion after failed attempts they don't get knocked down on the ground, or the NPC model looks weird. Basically it delays you to the point where you only can get in one pickpocket per knockout at times.

**Describe alternatives you've considered**
Unsure as I don't know what's allowed and isn't allowed, on top of not being sure what limitations runescape has.

**Additional context**
I believe this is a feature that would aid blackjacking without becoming incredibly overpower such as the entry swapper previously did. This solution would simply aid those who pay more attention when blackjacking.

**Comment by abextm** [comment]
I don't think we can detect if the npc is knocked without just looking at the animation that makes them face the floor, so their broken standing state would just show as awake.

**Comment by abextm** [comment]
also you may want to make sure you are using the real RuneLite; we have never had a feature that lets you swap menu entries for blackjacking

**Comment by MantaDroid** [comment]
> I don't think we can detect if the npc is knocked without just looking at the animation that makes them face the floor, so their broken standing state would just show as awake.


I mean them being shown as awake would be fine, but I was thinking if some kind of colour indication is possible? 


> also you may want to make sure you are using the real RuneLite; we have never had a feature that lets you swap menu entries for blackjacking

Oh, nah I haven't used that function myself. Just something I read about/saw on YouTube as I looked things up for blackjacking as I started playing ironman recently.

**Comment by abextm** [comment]
the color indication would show them as awake; we can't tell the difference between them being actually awake and them being standing-up-but-actually-knocked-out

**Comment by MantaDroid** [comment]
> the color indication would show them as awake; we can't tell the difference between them being actually awake and them being standing-up-but-actually-knocked-out

Hmm. Bummer. So it's not possible to detect if they're awakre VS knocked out?

**Comment by seanmcclure22** [comment]
@MantaDroid I wrote a plugin for this that is now in the plugin-hub, if you want to close this issue out.

**Comment by Nightfirecat** [comment]
I recommend using the mentioned plugin which can be found on the plugin hub.
