### ISSUE TITLE
Sidebar: Achievement Diary manager

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11203]
Part 1:
What I expect from the plugin?
1) **Ability to navigate between diaries, or even choose multiple ones.** (All, or Varrock, Ardougne, Lumbridge, etc.) and show their requirements respectively,
2) **Ability to navigate between difficulty.** (Easy, Medium, Hard, Elite),
3) **Show a task list for incomplete** tasks** and mark them as red,
4) **Show a task list for  completed** tasks** and ability to show/hide them, mark them as green if shown,
5) **Show a list for _skill tab/quest requirements list**_ and ability to hide/show requirements that are not met/not met and ability to show/hide them. Requirements that are met would be painted green, while requirements that are not met would be painted red.
6) Rather than thicking the requirements, **I would expect a "look-up-system"** if it was possible.

**I expect a system something similar to this:**]

![all elite](https://user-images.githubusercontent.com/62700066/78473054-ed875080-773d-11ea-89c1-8e36c67e436d.jpg)

Part 2:
**Import sound tracks from RS3 to OSRS** to indicate a completed task. (Currently, only Karamja diaries have this, not sure about Elite tasks though).

**Comment by abextm** [comment]
1) this is a thing in vanilla
2) ditto
3) ditto
4) ditto, but automatic
5) ditto, automatic
6) I have no idea what you mean by `thicking`

2) this isn't legal and not something we would want anyway; ask jagex for content features like this

Please stop opening issues that are
a) containing multiple requests
b) descriptions of existing features
c) or are solved by existing features
