### ISSUE TITLE
Animation bug w/ animation-smoothing: Bows-shooting

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11201]
Currently, the shooting-animation, and the arrow-animation are not synchronized.
More precisely, the arrow gets shot even before the character would have the arrow in it's hand.

I'm not sure, whether it's also the case with other weapons/items, etc.

**Comment by abextm** [comment]
We aren't jagex, if you want that changed ask them

**Comment by Pingvinszar2** [comment]
> 
> 
> We aren't jagex, if you want that changed ask them

As much, as I'd love to, the bug is caused after I turn the animation-smoothing on in runelite.
I don't think, they have anything to do with it.

**Comment by abextm** [comment]
anim smoothing just tweens the animations; it will be desynced without it on too

**Comment by Pingvinszar2** [comment]
I've tried to make as accurate images as I could.

As you can see on the image WITH smoothing, the arrow is being fired without the figure actually touching the arrow.

This is not the case in the other image.

I'm not sure, what causes this bug, but I'm very positive, that it's not Jagex-sided.

![without smoothing](https://user-images.githubusercontent.com/62700066/78472420-e90c6900-7738-11ea-881e-aafb90d3e511.jpg)
![with smoothing](https://user-images.githubusercontent.com/62700066/78472421-e9a4ff80-7738-11ea-91a4-b7f03bd06354.jpg)
