### ISSUE TITLE
Suggestion: Toggle option to show general store prices for all items by hovering over item in inventory.

### ISSUE THREAD

**Issue by rockett1** [runelite/runelite#11202]
Iron men at low levels dont have access to high alch so selling to general stores is a way to make a small amount of money. 

Having to not go to the store and hit value on the item itself is a nice quality of life change for low leveled iron men.

here is an example of what i mean: https://storage.googleapis.com/rockettsharex/ShareX/2020/04/runlite%20general%20store%20price.png

(The GS in the image above stands for general store, up to you devs what you want to call it if you choose to implement it)

**Comment by abextm** [comment]
Duplicate #7084
