### ISSUE TITLE
LMS rank HUD centered

### ISSUE THREAD

**Issue by bug-report-throwaway** [runelite/runelite#11207]
The rank box displayed while in LMS mode is centered if using Runelite, compared to it being on the right side next to the minimap on the official client.

Screenshot of the LMS rank HUD on Runelite:

![runelite_lms](https://user-images.githubusercontent.com/63214790/78514094-472c6100-77b8-11ea-94c2-31023969d345.JPG)

Screenshot of the LMS rank HUD on the official client.

![vanilla_lms](https://user-images.githubusercontent.com/63214790/78514017-e6048d80-77b7-11ea-98a2-aea15b35b539.JPG)

**Comment by caleyz** [comment]
You can change the location of a majority of overlays including this one by holding 'alt' and then dragging the box anywhere you want. You can also anchor it by dragging it into one of the transparent boxes 
![lmsfine](https://user-images.githubusercontent.com/22836786/78691087-27985400-78f0-11ea-8b1e-14125c291e8c.png)

**Comment by Nightfirecat** [comment]
We should default this widget to be in the `TOP_RIGHT` anchor point to match vanilla behavior better.
