### ISSUE TITLE
Stacks: Show exact amount after 100k/10m

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11208]
I expect this plugin work in the following way or have the following features:

Ability to choose between "green/white/yellow stacks".

**1) Yellow stacks:**
a) Would show the exact gold amount even after 100k/10m stacks. (ie. 10 750 000),
b) The numbers would be separated with spaces points or commas (option to choose),

**2) White stacks:** 
a) Would show the gold amount in thousands (ie. 10,750k).
b) Would show parts-of-thousand after a decimal point (ie. 10,750.5k)
c) Option to choose how many numbers would appear after the decimal point

**3) Green Stacks:**
a) Extend the "green stack" with decimals. If someone has 10.75M, it would be shown in the inventory. 
b) It would also be possible to change, how many digits we would like to see after the decimal point.)

**Comment by abextm** [comment]
There isn't enough room between inventory slots to show more than a single decimal, which is mostly pointless

**Comment by Pingvinszar2** [comment]
> 
> 
> There isn't enough room between inventory slots to show more than a single decimal, which is mostly pointless

Well, perhaps showing ONE decimal would be also helpful, as currently NONE is shown.
If there's room for "99999", there would be also room for 10,750.5k or 10.75M.

I honestly don't understand, why did you choose to close my thread this time..

**Comment by abextm** [comment]
there is room for 6 characters in the sprite, most of the time you are close enough to this limit you would only have one extra digit of precision. Also this is nearly impossible to change, and we certainly wouldn't do it for something this useless
