### ISSUE TITLE
GPU Plugin Freezes Client, but Doesn't Crash it

### ISSUE THREAD

**Issue by Jowj96** [runelite/runelite#11205]
Hi,

Had this issue since I got my PC 3 months ago. Running a RTX 2060 with the latest drivers. It happens on every version of Runelite I've used, having uninstalled and re-installed numerous times.

The client works as expected until I turn on the GPU plugin, which causes a freeze, though I can still use the side panel to change plugin settings. The game screen stays frozen even after I turn off the GPU plugin. If I don't turn off the GPU rendering before I close the client, the client doesn't open correctly and I have to re-install it.

I've fiddled with all possible settings in the Nvidia Control Panel and the game is definitely set to run from my GPU. I've also tried the --mode=OFF trick to run without hardware acceleration, even though I don't have the ability to turn it off or on with this PC.

Help appreciated :)

**Comment by MoistGravy** [comment]
Hey man, I had this same issue. I fixed it by opening task manager and then starting runelit. When runelit shows up under app process, expand it by clicking the little down arrow beside it. You should see a jogamp file l. End the jogamp file twice and you should be good 🙂

**Comment by Jowj96** [comment]
You're a HERO!

Worked first time, thanks a bunch!

For anyone following this, you have to enable the GPU plugin before the jogamp file appears in task manager.

Thanks again!!

**Comment by MoistGravy** [comment]
> You're a HERO!
> 
> Worked first time, thanks a bunch!
> 
> For anyone following this, you have to enable the GPU plugin before the jogamp file appears in task manager.
> 
> Thanks again!!

No worries 😁. Just remember that you have to do it everytime you open runelit. It's a pain, but at least you get that sweet sweet draw distance 👌
