### ISSUE TITLE
Plugins load config from local properties on initial startup

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#1121]
At the initial startup of the client, when accessing the plugin config from `startUp()` it will use the local `properties` and not the one that's synched trough the cloud (if you're using that feature). These two `properties` are not identical and will result in different settings being loaded on startup.

Disabling and re-enabling a plugin will result in the `startUp()` method using the correct `properties` and thus loading your synched settings.

RuneLite version 1.3.2, did not test on previous releases.

**Comment by ChaoticConundrum** [comment]
I agree this is confusing, and for for more reasons.
Currently, the process is
- `ConfigManager.load()` loads local configuration
- `PluginManager.startCorePlugins()` starts plugins enabled locally (`startUp()` called from here)
- `SessionManger.loadSession()` opens a session
- `ConfigManger.switchSession()` loads session config (produces `ConfigChanged` events)
- `SessionOpen` event in `PluginManger` enables/disables plugins according to session config (`startUp()` and `shutDown()` may be called)

So the things that get me:
- Plugins may be enabled and immediately disabled by session config. This isn't really performance hindering, but it is completely unnecessary.
- `ConfigChanged` events are not produced when the plugins start, but are produced when the session opens. So, plugin startup for users with/without accounts can have different code paths.
- As mentioned above, config available at `startUp()` time is only local, and is immediately changed if session configuration is different.

This seems to me easily solved by loading the session after the local configuration is loaded and before the plugins are started. I tested this, end everything worked as hoped. `ConfigChanged` events are never produced on startup, session config is available at `startUp()` and plugins are not enabled and immediately disabled.

If it was desirable to have more `ConfigChanged` events for development purposes, events could be generated for all the configuration fields after plugins are started. This would at least be consistent.

If I've got anything wrong, or there are other problems with this, please let me know.
