### ISSUE TITLE
Grand Exchange Buying limit reached (Notification and 4 hour timer)

### ISSUE THREAD

**Issue by nlruk** [runelite/runelite#11217]
When an Item from the grand exchange has successfully been bought we get a notification in the chat.

Is it possible to get a similar notification when the 4-hour buying limit has been reset? 

Can we also have a real-time 4-hour timer that is shown under the offer section of the Grand Exchange plugin? So we can see in real time how many hours, minutes, seconds is left till we can buy that item again.

This will be extremely useful.

**Comment by SammiIvan** [comment]
I agree! I feel this would be an extremely useful addition.

**Comment by abextm** [comment]
I think the flipping utilities plugin on the plugin hub tracks this

**Comment by Nightfirecat** [comment]
It does appear to do so. I would recommend using that plugin for these features.
