### ISSUE TITLE
Rename Fremennik Shield in Grand Exchange Tab

### ISSUE THREAD

**Issue by liebzer** [runelite/runelite#11211]
Currently the newly named Neitiznot Shield is called the fremennik shield in the grand exchange tab.  It should be renamed with the proper new name as the item is needed for frem isles quest.
![Screen Shot 2020-04-06 at 6 21 50 PM](https://user-images.githubusercontent.com/57821073/78620032-c14dfb80-7833-11ea-8b75-c2c1dbaf831a.png)

**Comment by Adam-** [comment]
This should be fixed by 670e62b6b9fd877d473b296d5d68a93930c0a222 but we'll have to let it run for awhile and see what happens.
