### ISSUE TITLE
Clues using "vambraces" in their text are not recognized after the update

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#11228]
From [the Poll 70 Improvements update today](https://secure.runescape.com/m=news/poll-70-improvements?oldschool=1), `Item names using abbreviations like 'vamb' or 'vambs' now all use 'vambraces'.` This means that clues which referenced them are likely changed as well, so those which we need to read the text off of must be updated to continue working.

**Comment by abextm** [comment]
I wouldn't be surprised if the wording has been slightly changed outside of just find/replace on some of these

**Comment by Hydrox6** [comment]
Reported by `Joppig` in the Discord

![](https://i.imgur.com/WQvG4sC.png)

**Comment by Hydrox6** [comment]
Reported by `Ransom` in the Discord

![image](https://user-images.githubusercontent.com/2979691/78987023-a970c300-7b24-11ea-92cb-92e80c42b683.png)

**Comment by Nightfirecat** [comment]
These are the only two clues which used `vambs` in their text, so I think we're good to go with updating these now. I doubt the clue text of other clues which used the word `vambraces` has changed.

**Comment by SirGirion** [comment]
Will take this one
