### ISSUE TITLE
Video overlay (Skilling)

### ISSUE THREAD

**Issue by nlruk** [runelite/runelite#11221]
Would it be possible to add the ability to watch Youtube videos or Twitch streams inside its own overlay window in Runelite? It will be perfect for skilling. This will allow us to stay in the same window.

There is a famous RS3 client that does this and its a very popular feature.

**Comment by Spedwards** [comment]
Picture-in-picture.

**Comment by nlruk** [comment]
> Picture-in-picture.

Thank you! did not know about this. Anyone who is interested in this youtube 'Picture-in-picture"

**Comment by Nightfirecat** [comment]
For what it's worth, we have declined many similar feature requests on the grounds that we aren't interested in incorporating a web browser into the client. Thankfully picture-in-picture, which is available in most major browsers, generally addresses this need nicely.

Duplicate of #3038 et al.
