### ISSUE TITLE
Ground Items: Add support for stack counts

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1123]
Would love to be able to add "Coins<100", "Feather<20", "Fire rune<50" etc to my hidden items.

**Comment by Infinitay** [comment]
Hide GE/HA value if < 100?

**Comment by ShaunDreclin** [comment]
That would hide items that I want to pick up that are worth less than 100gp on the GE. (Ironman btw)

Hiding everything below one price isn't as useful as hiding specific items by their stack counts

**Comment by Nemo296** [comment]
I'd like to voice my support for a feature like this. I like to loot stackable items that are worth over X amount and having items that are stackable over X price highlighted or stackable items under that price hidden would be a super helpful feature!

Thanks.
