### ISSUE TITLE
Add current world to !layout command

### ISSUE THREAD

**Issue by Gosemer** [runelite/runelite#11236]
**Is your feature request related to a problem? with multiple accounts in clan chat and more than one person typing the command, its easy to mix up what world to go to.

**Describe the solution you'd like**
when typing the !layout command and the world the account in on as well as the rotation.

**Describe alternatives you've considered**
a separate command that sends current world in chat.

**Additional context**

**Comment by melkypie** [comment]
Duplicate of #10566
