### ISSUE TITLE
Worn items bank menu incorrect weights

### ISSUE THREAD

**Issue by ch4s1ngs4nity** [runelite/runelite#11237]
**Describe the bug**
When viewing _worn items_ within the bank, all the item weights are _+0.453_ if you have the _show weight_ setting enabled in _item stats_

**Expected behavior**
Should show proper item weights.

**Environment**
 - OS: Windows 10
 - RuneLite version: 1.6.10.1
 - Launcher version: 2.1.0

**Comment by vonpawn** [comment]
Created pull request #11327
