### ISSUE TITLE
Connecting to update server

### ISSUE THREAD

**Issue by killkill57** [runelite/runelite#11239]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I am unable to access the login screen. When I open RuneLite, I am able to load the client up until the "connecting to update server" screen. After a few seconds the whole screen goes to black and I am unable to do anything.

[error rs.pdf](https://github.com/runelite/runelite/files/4457987/error.rs.pdf)

**Environment (please complete the following information):**
 - OS: [macOS]
 - RuneLite version: [2.1.1]

**Additional context**
WARNING: An illegal reflective access operation has occurred

**Comment by killkill57** [comment]
I have tried uninstalling and re-installing the client multiple times to no success. I also have updated java to the newest version.

**Comment by abextm** [comment]
You should ask for help in [the #support channel in our Discord server](https://runelite.net/discord)
