### ISSUE TITLE
.getDrawDistance() returns 0 if gpu plugin hasn't been enabled

### ISSUE THREAD

**Issue by chestnut1693** [runelite/runelite#11247]
People reported problems with the bats locator plugin. One person discovered that turning the gpu plugin made it work. The overlay renderer of the bats locator plugin uses .getDrawDistance() to determine if the player is close enough to draw the dots. Unfortunately nothing gets drawn since 0 is returned.

Is it possible to have .getDrawDistance() return the default draw distance used by the vanilla client when the gpu plugin is disabled?

**Comment by Adam-** [comment]
This is intentional behavior. You can assume it is 25 otherwise.

**Comment by chestnut1693** [comment]
Alright.
