### ISSUE TITLE
We need the most expressive emoji to date, the middle finger

### ISSUE THREAD

**Issue by Rawleigh** [runelite/runelite#11241]
**Is your feature request related to a problem? Please describe.**
There is a major lack of expressing frustration in clan chats across RS. Sometimes, one just needs to release that tension with a solid flipping of the bird.

**Describe the solution you'd like**
We need the middle finger emoji to be implemented.

**Describe alternatives you've considered**
I've once considered actually being nice to others, but found that to be rather hard.

**Additional context**
Please!

**Comment by dekvall** [comment]
You can use this image if you are planning to implement this ![middle-finger](https://user-images.githubusercontent.com/25151927/79083829-e4dfdd00-7d30-11ea-84ec-59ae59f66455.png)

**Comment by Nightfirecat** [comment]
We're not interested in adding this emoji at this time.
