### ISSUE TITLE
Optionally require ctrl to be held to zoom

### ISSUE THREAD

**Issue by Abextm** [runelite/runelite#1124]
To prevent accidental movement.
@Stickaplex on discord

**Comment by mihkelwow** [comment]
![ctrl scroll](https://user-images.githubusercontent.com/39198864/42417018-41bdbc06-8286-11e8-87e4-c3444718e0cc.png)

Something like this please...

**Comment by whitehooder** [comment]
I've got ctrl + wheel click working locally. Might see if I can add an option for requiring ctrl & submit a PR.

**Comment by iLackIQ** [comment]
is there any progress on this?
