### ISSUE TITLE
Minor Issue - White Screen

### ISSUE THREAD

**Issue by MrPotatox** [runelite/runelite#11240]
Searched existing issues, nothing found.

Minor issue really although this only started a day or two ago... steps below.
RuneLite app already open.
Issue arises when idle.
PC/laptop is inactive for x amount of time.
PC/laptop times out and reverts back to device account login screen.

Upon entering keyphrase and going to already open RuneLite client faced with a white screen within the interface. Sidebar options are still functional, only the game screen that is white.

![image](https://user-images.githubusercontent.com/63432576/78953208-01c9a580-7ad0-11ea-89c0-f0c7275176bd.png)

Can be solved by closing and restarting the app.

Issue arises on Windows 10
Latest RL version 1.6.10.1

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by abextm** [comment]
If this still happens post your gpu driver version + if you have gpu enabled

**Comment by DankSteelMemes** [comment]
Still happens to me as well even with HW acceleration disabled. Do not use the GPU plugin or HD, none of that. Just like the many other threads on this if I go into options and Stretched Mode plugin and turn it off, the white screen goes away. Turn the plugin back on and white screen appears again. No options selected in Stretched Mode and scaling set to 30%.
