### ISSUE TITLE
Missing Master Clue Emote Step

### ISSUE THREAD

**Issue by SirGirion** [runelite/runelite#11250]
**Describe the bug**
The dance in KBD lair master emote step is missing.

**To Reproduce**
1. Get a clue telling you to dance in the KBD lair with a black d'hide body/vambraces and black dragon mask
2. Open it
3. Observe it doesn't tell you about the items needed

**Expected behavior**
A helper widget should pop up with the items needed and indicating that this step has a STASH associated.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.11

**Additional context**
N/A

**Comment by SirGirion** [comment]
Will take this one

**Comment by Hydrox6** [comment]
Duplicate of #11228
