### ISSUE TITLE
XP Tracker Goal - Show level milestone markers

### ISSUE THREAD

**Issue by arlause** [runelite/runelite#11258]
Would it be possible to get markers on the xp tracker if it is tracking a multi-level goal? So, for example, there would be a tick mark for every level from 90 - 99 (9 tick marks in total) so that you could see how close you are to each individual level.

**Comment by Hydrox6** [comment]
This is already a feature, under `Show intermediate level markers`

**Comment by arlause** [comment]
> This is already a feature, under `Show intermediate level markers`

Thank you for bringing that to my attention! I had not found it yet!
