### ISSUE TITLE
motherlode mine ore depletion notification

### ISSUE THREAD

**Issue by dec0yable** [runelite/runelite#11256]
I have been using the idle notifier to get a notification when the ore i'm mining is depleted. Problem is since it uses the animation of my character it is very unreliable with false pings and the delay between depletion and the notification.

I'd like to get a notification the tick the ore depletes, not when my character is idle for x time.

I think this could be added to the mining plugin. This detects already when the ore depletes so i would imagine it would be pretty straight forward to detect whether i was mining that particular ore and then send a notification. this could also be added to the motherlode mine plugin but i think this would be handy as well for stuff like addy and rune mining.

**Comment by Nightfirecat** [comment]
If it is notifying you between animation cycles, it is set to too short an interval increase the delay and it will not notify you unless it has depleted.
