### ISSUE TITLE
Sound on xp drop

### ISSUE THREAD

**Issue by giver35** [runelite/runelite#11269]
**Is your feature request related to a problem? Please describe.**
When mining (especially gem rocks), I would like to look away from the screen and the idle notification is generally too slow and intrusive to let me know when the rock is depleted (and seems to require the client is minimized or not selected).

**Describe the solution you'd like**
It would be great to have an additional sound cue option added to the xp drop plugin. Since every time the rock is depleted you get an xp drop it would help me a ton!

**Comment by Nightfirecat** [comment]
This is what the idle notifier plugin is for. You can change your notification sound in your system settings [or use a custom sound via RuneLite's settings](https://github.com/runelite/runelite/wiki/RuneLite#notification-sound). Just make sure the "Send notifications when focused" option is enabled in your `RuneLite` settings.
