### ISSUE TITLE
Menu Entry Swapper for Portal Nexus

### ISSUE THREAD

**Issue by JacoboMoral** [runelite/runelite#11267]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I left click the Portal Nexus and teleport to its default location instead of opening the menu.

**Describe the solution you'd like**
I'd like the left click on the Portal Nexus to be the Teleport Menu instead of the default teleport.

**Describe alternatives you've considered**
Another way would be to disable left click teleporting on the Portal Nexus, but I would lose the ability to quick teleporting to a chosen destination, which is not ideal IMO.

**Additional context**
Actual right click menu entries of the Portal Nexus when a Left click teleport is enabled:
![image](https://user-images.githubusercontent.com/24235786/79223540-d50fe800-7e59-11ea-9103-56057f748da0.png)

**Comment by DADtheMaggot** [comment]
I'm trying to straighten this out in my head, are you saying you want to have a default teleport set, but still have the left-click open the teleport menu? So that you could still access the default with a right-click?

**Comment by Spedwards** [comment]
I believe this is mostly for using other people's houses who have a default teleport set.

**Comment by DADtheMaggot** [comment]
Ahhh, lol, I forgot you can use other people's houses, that makes more sense.

**Comment by JacoboMoral** [comment]
> I'm trying to straighten this out in my head, are you saying you want to have a default teleport set, but still have the left-click open the teleport menu? So that you could still access the default with a right-click?

Well not exactly. In my case, I like having a default teleport set for quick access. The downside of that is that I keep left clicking the nexus and teleporting to the wrong location when I wanted to open the menu.

**Comment by joelewis43** [comment]
Looks like the PR didn't link with this issue. Can someone please manually close it.
