### ISSUE TITLE
Bank Search "Warm" for Wintertodt related equipment items

### ISSUE THREAD

**Issue by Dayoak** [runelite/runelite#11260]
Searching "clue" will return equipment in your bank which is required to completed your current clue step when applicable. Same functionality concept, just with Wintertodt.

All "warm" items to be returned from a search that's related to wintertodt, e.g. "warm", "wintertodt", "pyro".

Using bank tags would remedy this "problem" if the previous articles of equipment are known, or you're looking at the wiki page, however that solution is a little ... 'cumbersome'. Integrated functionality would be more stream-lined and easier for all players.

N/A, I just hate searching the bank.

**Comment by dekvall** [comment]
Your current clue scroll step is dynamic but whether or not an item counts as warm isn't. It's easier to just create your own bank tag containing the items listed on the wiki.
