### ISSUE TITLE
Menu Entry Swapper for Captain Barnaby

### ISSUE THREAD

**Issue by OliverBroadbent** [runelite/runelite#11264]
**Is your feature request related to a problem? Please describe.**
Simple request. Support Captain Barnaby in the Menu Entry Swapper plugin. Useful for fruit tree runs.

https://imgur.com/a/UhiIr9c

**Comment by Plondrein** [comment]
Barnaby has different options in each location - how would you want that to be configured?
Per location? Or route priority?

**Comment by Nightfirecat** [comment]
I would imagine this would prioritize one menu entry and therefore not do anything for the Barnaby menu options when at the selected location.

**Comment by Plondrein** [comment]
If someone is often uses boat to go Ardy <-> Brim, then he would set 'Brimhaven' option - but would get 'Talk-to' option as first while talking to Barnaby in Brimhaven - not sure if it's intended behaviour, but maybe it's enough as most fruit tree runners just tele out after getting to Brimhaven.

As alternative, we could have options with routes ( A <-> B") and in each location first option would be A given we are at B and vice versa.

**Comment by ShaunDreclin** [comment]
I think having a selection of all possible routes is the best way to do it. `Ardougne <-> Brimhaven`, `Ardougne <-> Rimmington`, `Brimhaven <-> Rimmington`

Similar options for veos, mistag, and any other multi-destination npcs would be good too.

**Comment by Adam-** [comment]
This can be swapped now via the custom left click swap option in dadf3661e13be1e201ade1addadd554fda346cc3
