### ISSUE TITLE
Easy view of Alchables in Bank

### ISSUE THREAD

**Issue by JonathanSolipa** [runelite/runelite#11271]
When clearing out my bank I like to look for any alchables I have lying about and find it annoying to have to look at each one individually to see which turn a profit and which don't.

I would like for there to be a tab, perhaps through the use of the Bank Tab addon by automatically attributing a specific tag, within the bank that only shows items that high alch for a profit. Possible features that can be added include setting a profit margin as a filter and selective item filtering.

An alternative solution would be to highlight the items which alch for profit but I can imagine this would be more difficult as it presents issues with scrolling.

**Comment by raiyni** [comment]
You can search in the bank with ha > 350

**Comment by JonathanSolipa** [comment]
Had no idea you could do that, thank you.

I still think it would be nicer to be able to have a bank tag do that, is this still a possibility?

**Comment by raiyni** [comment]
It was a conscious decision at the time to not have it as a tag tab.

You can also search on a range or GE price

`ge >= 2k`

or

`ha 400 - 5k`

**Comment by JonathanSolipa** [comment]
Thank you very much!

**Comment by JonathanSolipa** [comment]
I noticed that there is no way of calculating the difference between the ge price and the high alch price which is what this request was all about, ha > 250 only gives items that alch for more than 250gp, there also doesn't seem to be a possibility of doing ha-ge > 250 in order to resolve this, would that be a viable solution?

**Comment by LlemonDuck** [comment]
Available in plugin hub as [High Alc Highlight](https://runelite.net/plugin-hub/show/high-alc-highlight)
