### ISSUE TITLE
XP Tracker

### ISSUE THREAD

**Issue by nlruk** [runelite/runelite#11273]
Is it possible to be able to change the XP tracker to show XP left/Actions left to our desired level (input level) instead of the next level? I think it would be nice to see.

Can we also be able to resize the canvas instead of just move it? I want to make it 10x bigger

Thanks

**Comment by Nightfirecat** [comment]
The XP tracker uses [ingame level goals](https://github.com/runelite/runelite/wiki/XP-Tracker#setting-level-goals) to determine actions/xp remaining, so you can set those and it will track against those set goals.

With today's update, overlays are now resizable. While you can't resize it vertically (all the components of it are laid out horizontally), you can widen it as much as you'd like. Is that what you were hoping for?

**Comment by nlruk** [comment]
Yes. Thank you.
