### ISSUE TITLE
Mouse tooltip item value color does not match ground item value color

### ISSUE THREAD

**Issue by thebinaryeagle** [runelite/runelite#11277]
**Describe the bug**
When hovering over an item on the ground, the color of the mouse tooltip name of the item does not match the color of the text of the ground item. This only seems to happen on untradable items from my small amount of testing with feathers and cannonballs, though it is a small sample size.

**Screenshots**
![NQcjIRbL5J](https://user-images.githubusercontent.com/60583962/79393485-70c95300-7f43-11ea-9b57-dfc2940595e7.gif)
![CyuvFuUbOP](https://user-images.githubusercontent.com/60583962/79393491-72931680-7f43-11ea-8a95-5a0499f880c5.gif)
My ground item settings for reference:
![RuneLite_Zp40O7J4IQ](https://user-images.githubusercontent.com/60583962/79393611-b7b74880-7f43-11ea-933b-95413780a9af.png)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.6.10.1
 - Launcher version: 1.6.0

**Comment by rnoennig** [comment]
Based on my observation I believe there are two underlying problems:
1) When the GE price is 0 (untradeable items) the GroundItemPlugin used the store price, not the HA price (which is the store price multiplied by 0.6). So the 1 brimstone key has a storeprice of 80.000, which explains the blue color for that medium value
2) For non-stackable untradeable items the relevant code didn't handle the quantities correctly, e.g. dropping two raw lava eels returned a quantity of 1 and a wrong price, which lead to the wrong color

The pull request https://github.com/runelite/runelite/pull/11304/ fixes both issues

**Comment by rnoennig** [comment]
There is still some issue with stackable items:
![](https://i.imgur.com/pgOO2zn.png)... I need to analyze this.

**Comment by rnoennig** [comment]
Now it works for stackable and non-stackable, tradeable and non-tradeable items. Also the default item color is now used when items' prices don't match any value threshold. I'll continue using this version and see if anything acts up, but the last few hours looked fine to me.
