### ISSUE TITLE
Show average combat level of raid

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#1127]
Show the average combat level of the people who are in the raid team, and give a warning/have it turn red if the average is <115

**Comment by Twinkiel0ver** [comment]
Has anybody done this? If not, I would like to work on it.

**Comment by winterdaze-rs** [comment]
I don't think this is useful anymore after the recent update:

> Chambers of Xeric scaling will now be based on the player with the highest combat level rather than the average. This is means that if a team of level 80 players takes someone with 126 combat, their raid will be scaled around 126 combat rather than their average which would be much lower and would in turn give them fewer points.

(https://secure.runescape.com/m=news/qol-and-w45-changes?oldschool=1)
