### ISSUE TITLE
Customcursor- not scaling on 4K

### ISSUE THREAD

**Issue by tomw00** [runelite/runelite#11278]
Custom cursor plugin does not scale with 4K monitor - cursor becomes tiny.

**To Reproduce**
Enable custom cursor plugin on high res screen

**Expected behavior**
Cursor should scale

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: latest
 - Launcher version: latest

**Comment by Nightfirecat** [comment]
Duplicate of #8782

**Comment by tomw00** [comment]
@Nightfirecat - Is anyone looking at #8782 ? Looks to be nearly a year old :-)

**Comment by Nightfirecat** [comment]
Not to my knowledge.

**Comment by tomw00** [comment]
Okay, thanks
