### ISSUE TITLE
Fishing Session with Pearl Fishing Rod does not track activity

### ISSUE THREAD

**Issue by CupOnoodles** [runelite/runelite#11283]
When fishing with the pearl fishing rod, the fishing session stats still indicate "NOT fishing".

Quick tests compared a regular fishing rod with the pearl fishing rod at angler and sacred eel fishing spots. Regular fishing rods will correctly indicate "Fishing" while the pearl fishing rod will indicate "NOT fishing"

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.6.11
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
There are three types of pearl fishing rods: regular, fly, and barbarian. Could anyone with these fishing rods and the ability to run RuneLite with the developer mode plugin enabled please check for the two animations associated with them? There is one animation for when you first cast your rod, and another as you continue to fish at a fishing spot.

**Comment by Joe-Qing** [comment]
https://i.imgur.com/nOYRpkZ.gifv Seems to be only one animation ID for both parts
