### ISSUE TITLE
[Suggestion] Add abbreviations to the GE Search Plugin

### ISSUE THREAD

**Issue by royoffire** [runelite/runelite#11285]
Add common abbreviations for the newly added search plugin. Some of them still pull up 100+ items and it would be a huge QoL for the plugin. Some examples being: 

Armadyl Godsword - AGS
Saradomin Godsword - SGS
Bandos Godsword - BGS
Zamorak Godsword - ZGS
Twisted Bow - Tbow
Granite Maul - Gmaul
Dragon Warhammer - DWH
Prayer Potion - Ppot
Super Combat Potion - SCB
Armadyl Chestplate - ACP
Bandos Chestplate - BCP
Bandos Tassets - Tassys
Dragon Pickaxe - Dpick
Dragonfire Shield - DFS
Dragon Hunter Lance - DHL
Dragon Hunter Crossbow - DHCB
Armadyl Crossbow - ACB
Dragon Dagger(P++) - DDS

The list could be expanded on as needed but above is a handful of them.
Thanks.

**Comment by abextm** [comment]
You can add bank tags for these and they will work in the ge search like you want
