### ISSUE TITLE
Can't remove Wiki button

### ISSUE THREAD

**Issue by liverare** [runelite/runelite#11297]
The Wiki lookup-entity button under the world map icon doesn't go away when I turn off the Wiki setting.

![Annotation 2020-04-17 121410](https://user-images.githubusercontent.com/1773742/79563592-fd3f5700-80a4-11ea-9fc7-359db4c71ade.png)

**Comment by Hydrox6** [comment]
Since the 23rd of January, OSRS itself has Wiki integration. You'll need to dig into vanilla settings as well to turn it off

**Comment by liverare** [comment]
Thanks I wasn't aware of this. It's a pretty annoying button that gets in the  way sometimes during Gauntlet when I'm spam clicking about trying to do many different things at once.

**Comment by hex-agon** [comment]
You can disable it in the vanilla client by going into the Options Tab -> Advanced Options -> Wiki lookup
![image](https://user-images.githubusercontent.com/4876366/79567740-1e934980-808b-11ea-8ea4-9f4b9916d9ae.png)
