### ISSUE TITLE
(suggestion) Banked Farming Experience - Pull from Seed Vault

### ISSUE THREAD

**Issue by ehhhhhok** [runelite/runelite#11293]
Whenever trying to use the banked experience plugin, it only pulls from the seeds and saplings in my bank. I don't think many people keep these items in their banks, but rather the seed vault.

I would suggest having the banked farming experience have the option to pull from your bank, the seed vault, or both.

**Comment by Hydrox6** [comment]
Requests for changes to plugin hub plugins should be opened on the [plugin's repository](https://github.com/TheStonedTurtle/banked-experience)

**Comment by ehhhhhok** [comment]
Thanks, didn't know. Reposted there.
