### ISSUE TITLE
Add rotation to Inventory Viewer

### ISSUE THREAD

**Issue by ijustlovemath** [runelite/runelite#11294]
**Is your feature request related to a problem? Please describe.**
When I want to have my RuneLite window in the corner of the screen, I use the Inventory Viewer to be able to have more screen real estate without losing functionality. I want to be able to view the status of the inventory while having the viewer off to the side (only viewing one row or column)

**Describe the solution you'd like**
If I could rotate the inventory viewer 180 degrees, the top left corner would be the last inventory slot, which is good to watch for when your inventory fills up.

**Describe alternatives you've considered**
Simply not having this feature is an alternative, it's not critical.

**Additional context**

Here's where the fix could be applied:
https://github.com/runelite/runelite/blob/7c5d8cccbb6f2e4e2629494b8a984f4bb6c5202f/runelite-client/src/main/java/net/runelite/client/plugins/inventoryviewer/InventoryViewerOverlay.java#L104

You could (potentially) use `ImageUtil.rotateImage(graphics, Math.PI)`:

https://github.com/runelite/runelite/blob/1.6.11/runelite-client/src/test/java/net/runelite/client/util/ImageUtilTest.java#L221

Would be nice to have all 4 90-degree rotations if possible. Not sure how to implement that.

Here's a screenie to demonstrate the problem:

https://i.imgur.com/QfR8GoQ.png

**Comment by simonkrol** [comment]
A potential alternative to this is to move the inventory viewer to the left side of your screen. I'm not sure which button it is on windows, but on mac you can hold option and drag the viewer. It seems like it would fit nicely below your minimap (and if it doesn't, you can hide your minimap with the Minimap plugin)

**Comment by Nightfirecat** [comment]
I think the requirement of "a more space-efficient" inventory viewer is better fulfilled by the Inventory Summary plugin found on the plugin hub: https://github.com/Hydrox6/external-plugins/tree/inventory-summary

**Comment by ijustlovemath** [comment]
@simonkrol for the play I was doing, I needed to still be able to see the full game window, but I have done that with some success.

@Nightfirecat I'd rather keep things vanilla, as even though it's audited, I don't know how the update mechanisms work, so there's potential for abuse in the future.

**Comment by deathbeam** [comment]
Well your request is super niche, and when there is already solution in plugin hub, you should just use that imo.

**Comment by Nightfirecat** [comment]
Not to mention, we audit all plugins which are submitted to the hub, so there's only as much "potential for abuse" as there is for plugins/features which land in the client itself.

**Comment by ijustlovemath** [comment]
Okay, I'll close this for now!
