### ISSUE TITLE
Glitchy Sidebar

### ISSUE THREAD

**Issue by Cufantce** [runelite/runelite#11307]
Sidebar is glitching whenever i move the mouse over options. I am also unable to rearrange items in my bank. I have tried disabling hardware acceleration, however this has not had any effect. I have uninstalled and reinstalled as well and tried disabling the hardware acceleration however it has not helped either

**Comment by Nightfirecat** [comment]
Please post your `launcher.log` and `client.log` files.

**Comment by Cufantce** [comment]
[client.log](https://github.com/runelite/runelite/files/4496413/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4496414/launcher.log)

Is this the right thing? sorry im not great at this kinda thing

**Comment by Nightfirecat** [comment]
I'm seeing this line appear in your launcher log, which indicates you're not properly disabling hardware acceleration in your client:

```
2020-04-18 02:07:36 [Thread-0] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
```

I recommend double-checking the steps to disable it and trying those again. If you need help doing so, [you can join the `#support` channel of our Discord server](https://runelite.net/discord).
