### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Glafuski** [runelite/runelite#11306]
**Describe the bug**
Runelite starts using excessive amount of RAM when using Kourend Library plugin. I have 16gb of ram and at some point my memory usage was 85% even though i had only Runelite and Google Chrome open. I ended Runelite process and after that my RAM usage was 25% at this point. For some reason Runelite only shows that it is using normal amount of memory (600 - 800 MB) but yet it is using 60% of total memory. There must be somekind of problem with memory management within this plugin / area. 

I teleported to other parts of Runescape and excessive memory usage does not happend anywhere else so the problem must be tied to this area/Kourend Library plugin.

**To Reproduce**
1. Go to Kourend library
2. Start collecting books with Kourend Library plugin set on
3. Keep doing it for awhile 
4. Check total memory usage

**Expected behavior**
I expect Runelite to not use 60% of my 16GB RAM.

**Environment (please complete the following information):**
 - OS: Windows 7
 - RuneLite version: 1.6.11
 - Launcher version: 1.5.2

**Comment by Nightfirecat** [comment]
This is very likely just graphics driver issues. Try roaming the area with the GPU plugin disabled to compare.

**Comment by Glafuski** [comment]
> This is very likely just graphics driver issues. Try roaming the area with the GPU plugin disabled to compare.
> 
> In fact, this is likely [the AMD driver issue described on our GPU FAQ wiki page](https://github.com/runelite/runelite/wiki/GPU-FAQ#im-getting-incredibly-high-memory-usage-while-using-the-gpu). Please read that and try the solution it suggests.

It worked that i disabled GPU plugin. I will try to rollback my drivers to that certain version later. 

Thank you for solving this so quickly!
