### ISSUE TITLE
How to disable anti-aliasing

### ISSUE THREAD

**Issue by 07Elf** [runelite/runelite#11301]
How can i get the anti aliasing of the default client (osrs client) on my game through runelite? it only allows me to go as low as x2 anti aliasing, or just completely turn off gpu panel, but thats too low, i want the anti aliasing that the default game has, i think its possible but i just dont know how to get it, ive tried so many things on nvidia control pannel but nothing helps, if anyone can help me with this issue please do as i have been trying to fix this for 3 months and have made a github account just specially for this issue that im having. much love <3

**Comment by Nightfirecat** [comment]
What are your GPU plugin settings? You should have the "Anti Aliasing" setting set to `Disabled`.

**Comment by 07Elf** [comment]
> What are your GPU plugin settings? You should have the "Anti Aliasing" setting set to `Disabled`.

yes it is but its still has noticeably less pixelation when comparing it to default launcher.

**Comment by Nightfirecat** [comment]
You will need to check your graphics card settings further. We do not force AA to be enabled, so this is not something we can control.

**Comment by 07Elf** [comment]
wow not even a heads up or tip on what to do :/

**Comment by Nightfirecat** [comment]
A user on Discord suggested it could be due to your system's DPI scaling settings, not your graphics card's AA settings. This is also the wrong place to seek support--this is used exclusively for tracking feature requests and client bugs. You can [seek help in our `#support` channel on Discord](https://runelite.net/discord).
