### ISSUE TITLE
Separate Quick Pass/open/start/travel option for Theatre of blood

### ISSUE THREAD

**Issue by wyborowa1** [runelite/runelite#11313]
**Is your feature request related to a problem? Please describe.**
Currently there is only a single option to quick pass/open/start/travel for all options in RS (under menue entry swapper). This is an amazing plugin, but it automatically does this in every place it is possible in the game. In the Theatre of blood this can be really annoying if you misclick next to the chest on the door, which makes you go through without a warning even if you did not buy supplies yet. 

**Describe the solution you'd like**
Could tob get a seperate option for this, or something that makes it possible to turn this plugin on for different things in the game as it is a very nice plugin to have but I can't turn it on if im doing tob.

**Describe alternatives you've considered**
Remove the quick pass option for tob completly (as I do not know a single person that actually likes it in tob), or make it a seperate option from the rest.

**Comment by Hydrox6** [comment]
This can now be done with the changes in 92aac53f4273e7944c3da767637e083847c03808
