### ISSUE TITLE
Clue Scroll plugin not detecting runes in runepouch for enchant dragonstone jewellery step

### ISSUE THREAD

**Issue by skyblownet** [runelite/runelite#11319]
**Describe the bug**
When you have earth runes in your rune pouch and you have the enchant dragonstone jewellery clue step from an elite clue the plugin will not mark the earth runes with the green check in the overlay.

**To Reproduce**
1. Have elite clue with step "enchant dragonstone jewellery"
2. Have rune pouch in your inventory
3. Have earth runes, water or cosmic rune inside your rune pouch
4. You will not see the green check (it displays the red X) next to the requirement in the overlay

**Expected behavior**
The green check should be displayed in the overlay next to the runes if you have them in your rune pouch.

**Screenshots**
/

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: [e.g 1.6.11.1]
 - Launcher version: [e.g 1.6.2]

**Additional context**
/

**Comment by Hydrox6** [comment]
It actually doesn't detect the Rune Pouch at all, not just for that step btw
