### ISSUE TITLE
Bank/Bank Tags: Skill Icons and other requests.

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#11328]
I would like to make some requests for the "Bank Tags" plugin, these would be the following:

1) Make it possible to add **"Skill Icons"** as tags.
2) Make it possible to create **"Skill Group icons"** as tags (ie. Artisan, Combatant, Gatherer, Support).
_This would allow you to combine several "Skill icons" into one icon, then use it as a single bank-tag._
3) Make it possible to remove "edit/delete tags" menu from the right-click menu.
4) Make it possible to add tags to items that DON'T exist in bank.
5) Make it possible to hide search/placeholder icons.
6) Make it possible to arrange bank tags horizontally.
7) Make it possible to break the tags into multiple lines rather than the scroll menu.
8) Make it possible to see tag names upon hover BELOW/ABOVE the cursor.
9) Ability to resize bank tags.
10) Ability to use texts instead of item icons as bank tags (too long texts would be wrapped).

That's all for now, if I find something else, I'll update.

**Comment by Hydrox6** [comment]
1. Nice idea
2. Nice idea, though a lot of the icons don't exist
3. Have you ever used the plugin?
4. You can already import tags to do that
5. Why?
6. No space to do this
7. No space to do this
8. Why is this even in here? This is already a feature in the client under `RuneLite`
9. What?
10. This just seems like a bad idea.

Don't make giant issues like this of basically unconnected requests, because it's impossible to manage.

Actually check for duplicate issues and **features that already exist in the client** before making issues. These issues are getting to the point where they're annoying.

**Comment by Pingvinszar2** [comment]
> 
> 
>     1. Nice idea
> 
>     2. Nice idea, though a lot of the icons don't exist
> 
>     3. Have you ever used the plugin?
> 
>     4. You can already import tags to do that
> 
>     5. Why?
> 
>     6. No space to do this
> 
>     7. No space to do this
> 
>     8. Why is this even in here? This is already a feature in the client under `RuneLite`
> 
>     9. What?
> 
>     10. This just seems like a bad idea.
> 
> 
> Don't make giant issues like this of basically unconnected requests, because it's impossible to manage.
> 
> Actually check for duplicate issues and **features that already exist in the client** before making issues. These issues are getting to the point where they're annoying.

2) That's why I have suggested, there should be an option combine multiple skill icons into one.
This would for example Att/Str icon next to each other, and Def aligned in the center of the 2nd line. (depending on, how many skills the user would like to see in one row.

3) Yes, I have used, and I frequently misclick on those menus, that's exactly the reason I have requested this.

4) I will try.

5) Misclick issues as well, when doing actions that require a lot of banking. (ie. banking runes while runecrafting). And because I don't use them.

8) Not as a seperate option, as far I know. 

9) Similar way to canvas, you could press alt and pull the tag column (within' certain limits) to side.
This would allow you the NR10.

10) Some people prefer use text rather than icons, similar way to the option that's already built for bank tags (vanilla), but instead of NR1 to NR9 or roman, you could write a certain text (ie. Artisan, Combat, etc).

**Comment by abextm** [comment]
Please stop opening garbage issues with multiple requests that are mostly duplicates or THINGS THAT ALREADY EXIST. You can open this things here that are actually useful as individual issues (just 1). You should run your ideas against someone in discord before posting here in the future
