### ISSUE TITLE
Timers & Stopwatches - Improve the "Done" distinction

### ISSUE THREAD

**Issue by 3mptylord** [runelite/runelite#11332]
**Is your feature request related to a problem? Please describe.**
I struggle to distinguish the green of "Done" from the green of "healthy but in-progress". 

**Describe the solution you'd like**
On the overview screen, completed timers say "Ready" in bright green - so would it be possible to have the same colour for Done on all the other tabs. 

![request](https://user-images.githubusercontent.com/4316321/79803107-40c1eb80-8359-11ea-9f26-0aa46d045a0d.png)

**Comment by abextm** [comment]
Duplicate #3282
