### ISSUE TITLE
Discord channel for OSX/LINUX

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#11331]
I have been following https://github.com/runelite/runelite/issues/6482#issuecomment-616189834
for a while and I think it would be a good idea that all the users that are contributing could join this suggested OSX/LINUX discord channel

I am not a programmer but I would happily test any build and report back. I am sure many people would also love to do so!

Lets come together 😃

**Comment by abextm** [comment]
This is better discussed in discord itself.
