### ISSUE TITLE
Automatic Screenshot of Gauntlet loot

### ISSUE THREAD

**Issue by georgegaytan** [runelite/runelite#11335]
**Is your feature request related to a problem? Please describe.**
Gauntlet loot doesn't automatically screenshot with the Screenshot plugin, it isn't a generic Boss Kill format in the chatbox and there is no existing custom handling for Gauntlet loot scenarios

**Describe the solution you'd like**
We'd need to add custom handling to the Screenshot plugin to capture screenshots when viewing Gauntlet loot

**Describe alternatives you've considered**
Based on [ScreenshotPlugin.java](https://github.com/runelite/runelite/blob/19412ac51c61d4904022f548cd165c35db86875d/runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java) 
When grabbing gauntlet loot, the `BOSSKILL_MESSAGE_PATTERN `checks for `"Your (.+) kill count is: <col=ff0000>(\\d+)</col>."`

The Gauntlet specifically names completion as `Your Gauntlet completion count is: x` with various timestamps above it, but that isn't your loot! The loot comes when you open the chest, which shows a generic chest message

I'm looking into how we can automatically screenshot these screens

This may also differ based on Corrupted, but I'm sure we can mask the text differences... if only I could complete Corrupted rn to check ;)

**Additional context**
... workaround atm is to screenshot Untradeable drops and delete the 500 screenshots taken inside the Gauntlet

~Yes loot tracker reads Gauntlet loot. Might look into how they track it later and see if I can draw inspiration~

Gotem https://github.com/runelite/runelite/blob/fae69d4fd267f7b4000ee7c25cd137c7336923a1/runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java#L134 Thanks LootTrackerPlugin

I'll probably throw something together locally tomorrow night EST, kinda late atm

**Comment by georgegaytan** [comment]
Created Draft PR on my branch https://github.com/runelite/runelite/pull/11339

Ughhhhh there's an issue for sure. Won't be as easy as I'd thought (documented in PR)

**Comment by georgegaytan** [comment]
PR set to Ready for Review #11339

**Comment by Adam-** [comment]
added in 1444ddcb677baf74839bea0752896309391ffee3
