### ISSUE TITLE
Menu Entry Swapper for Rune Pouch

### ISSUE THREAD

**Issue by JacoboMoral** [runelite/runelite#11359]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I left click the Rune Pouch **by mistake** and it opens a new interface with some delay.

**Describe the solution you'd like**
I'd like the left click on the Rune Pouch to be the _Use_ instead of the _Open_.

**Describe alternatives you've considered**
There aren't any alternatives to this solution, except making the swap option choosable in the configuration.

**Comment by Spedwards** [comment]
You should create an issue over at https://github.com/raiyni/menu-swapper-extended.
