### ISSUE TITLE
Linux client ammo/slayer_task overlay bug

### ISSUE THREAD

**Issue by rjfitzg** [runelite/runelite#11356]
The ammo and slayer overlay boxes take up an enormous amount of the screen when active. The overlay resizing option presents itself, but does not change the dimensions when clicked and dragged.

Linux runelite client, running on Ubuntu 18.04. 

![Screenshot from 2020-04-23 18-42-58](https://user-images.githubusercontent.com/48196695/80163171-80bfe300-8592-11ea-82e4-e6bd1afd1c82.png)

**Comment by Hydrox6** [comment]
Change `Infobox size` under `RuneLite` to something more sensible
