### ISSUE TITLE
Windows Won't let me go full screen after working for a year 

### ISSUE THREAD

**Issue by foxy94** [runelite/runelite#11353]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I've been using runelite for a year and just today it won't let me fill the screen i've used the guide from the previous thread and it didn't work 
**To Reproduce**
1. Go to Runelite
2. Click on maximise

**Expected behavior**
Client to fill the screen
**Screenshots**
![image](https://user-images.githubusercontent.com/64222103/80133798-b3b7a600-8595-11ea-8966-99dab84dd5fa.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - RuneLite version: 1.6.12
 - Launcher version: 2.1.0

**Comment by Alexsuperfly** [comment]
You can try disabling custom chrome in "Runelite" settings then restarting the client, or setting your systems dpi scaling to 100%, i.e. no scaling.

If you need further assistance join us on [discord](https://runelite.net/discord) since that is a much better place to receive help of this type.
