### ISSUE TITLE
Runelite Configuration, XP tracker, etc. UI bug

### ISSUE THREAD

**Issue by angeredmage** [runelite/runelite#11364]
**Describe the bug**
Hi, I'm having a problem with the user interface as of late for Runelite and I'm not really sure what's causing it at this point. Opening up and scrolling over anything in Runelite's menus will either re-layer the current menu or UI on top of itself or black out the menu altogether.
It almost seems like a refreshing error between my screen and Runelite. Do you think that's possible since I'm currently running 144Hz monitors because I when swap between 100Hz and 144Hz. The problem goes away for maybe 5 seconds as I start scrolling and clicking through all the Runelite options. I have the resizing options active at the moment as I've seen some other people mentioning issues on the forum prior.

**Screenshots**
![image](https://user-images.githubusercontent.com/64165476/80272617-edfd7200-867f-11ea-9e0a-a2e69e70f221.png)

**Environment (please complete the following information):**
 - OS: Windows [10] (edit)
 - RuneLite version: 1.6.12
 - Launcher version: 2.1.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
[client_2020-04-23.0.log](https://github.com/runelite/runelite/files/4532465/client_2020-04-23.0.log)

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

> As of RuneLite Launcher 1.5.1, RuneLite attempts to enable hardware acceleration based on your operating system. If you are having hardware-acceleration issues (such as artifacting) you can disable it by following one of the instructions below.

**Comment by angeredmage** [comment]
Thanks Nightfirecat, seems to be working properly.
