### ISSUE TITLE
Idle notification when inventory is full

### ISSUE THREAD

**Issue by adamacampbell** [runelite/runelite#11377]
**Summary**
I think it would be useful to add the option to notify the player when their inventory is either; completely full, or has reached X amount of used slots. 

**Use-cases**
This would come in handy for semi-AFK skilling, such as thieving when users are spam clicking stalls without looking at their monitor.

**Implementation**
This could be added under the existing idle notification menu, following the same format as the existing idle notification settings.

**Comment by thebinaryeagle** [comment]
The "Advanced Notifications" plugin on the hub already does this.

**Comment by Nightfirecat** [comment]
As thebinaryeagle mentioned, [the Plugin Hub's Advanced Notifications plugin](https://github.com/Zakru/advanced-notifications) will do this for you. [A demonstration of its features can be seen in the merge request where it was added](https://github.com/runelite/plugin-hub/pull/156).
