### ISSUE TITLE
Right click remove options

### ISSUE THREAD

**Issue by Vasteline** [runelite/runelite#11372]
Hello there,

Is it possible to make a feature that hides specific features when you right click an item?

As in, when you right click the crafting cape when worn, can you remove the entry : boost, and only have teleport, remove and examine?

**Comment by TheStonedTurtle** [comment]
It sounds like this could potentially be against the rules.

> Modifies the menu options on worn/equipped items

https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1

**Comment by Nightfirecat** [comment]
Generally speaking, we avoid removing menu entries in pretty much all cases, beyond Jagex's rules on third-party clients. Beyond that, we are forbidden from reordering/removing entries on equipped items as Turtle said.
