### ISSUE TITLE
Left click player (Username)

### ISSUE THREAD

**Issue by nlruk** [runelite/runelite#11386]
When we left click a player can we see their username in lowercase only

This will allow us to differentiate between capital i (I) and lower case L (l) this is important as these techniques are used in scamming, luring etc

Please make this a default feature in Runelite.

<img width="363" alt="Screenshot 2020-04-27 at 12 51 27" src="https://user-images.githubusercontent.com/63312904/80369250-dee81100-8885-11ea-82bf-836df09810b1.png">

**Comment by stoddy15** [comment]
Very good idea but the question is are the Runelite developers allowed to do that?
