### ISSUE TITLE
Remove Dismiss (random events)

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#11388]
Can we have an option to remove dismiss on random events that are beneficial like the genie?

**Comment by Hydrox6** [comment]
["Generally speaking, we avoid removing menu entries in pretty much all cases, beyond Jagex's rules on third-party clients."](https://github.com/runelite/runelite/issues/11372#issuecomment-619584878)

**Comment by Nightfirecat** [comment]
This would [fall under `conditional menu entry removal`](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping). We could remove all `Dismiss` options from random events, but that is unlikely to be a feature most players want. As such, I'd recommend someone interested in implementing a blanket `Dismiss` menu option remover to write a plugin for the plugin hub.
