### ISSUE TITLE
Picking up items (Shift + Click) (PVP)

### ISSUE THREAD

**Issue by nlruk** [runelite/runelite#11382]
Can we please have the feature that when we hold shift and click on items on the floor we can't click attack unless we let go of shift

**Comment by Hydrox6** [comment]
Banned by the [Jagex Statemet](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Removes or deprioritises attack, cast (or similar) options from the minimenu in any scenario`
