### ISSUE TITLE
Add a "warning" tag to the GPU plugin's Compute Shaders option

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#11387]
The Custom Chrome option pops up to tell the user they need to restart for it to take effect. Similarly, the Compute Shaders option requires the user to restart the plugin, so having it also pop up would be a good idea.

**Comment by TylerADavis** [comment]
Are there any other plugins that already have popups when their values are changed? I know how to add a popup, but I'm not sure how to do so within the context of `ConfigItem` and `Config`

**Comment by abextm** [comment]
It would probably be better to make the plugin aware of this config changing and reset itself?

**Comment by TylerADavis** [comment]
I'm not aware of a built in "reset" function in the GPU plugin, but it might work to just toggle it off and on automatically?

**Comment by Hydrox6** [comment]
Making the plugin reset itself sounds like a load of extra work when we already have the stuff in place to inform the user.

**Comment by deathbeam** [comment]
Well we have stuff that informs user mostly because there was no way around that (e.g with custom chrome, the ideal case scenario would also be to not have the warning at all and simply switch the ui, but that is not an option).
