### ISSUE TITLE
Have Loot Tracker store drops by account

### ISSUE THREAD

**Issue by zombiezrule** [runelite/runelite#11391]
It's annoying having loot between my main and iron shared and unsorted in the loot tracker plugin. Other plugins, like the farming timers one, are able to differentiate between the account that's logged in. It would be nice to have the loot tracker plugin do the same, although with uploading to the Runelite servers it might be more difficult. Alternatively, instead of only containing the account that's logged in, allow it to be split into different account tabs at the top of the sidebar so that loot for each account can be viewed separately.

**Comment by LlemonDuck** [comment]
Added in 64abf450d9f72778b5ff1555f3ad04485964143c
