### ISSUE TITLE
Confusing grammar on "Import local settings to remote RuneLite account"

### ISSUE THREAD

**Issue by Atroxide** [runelite/runelite#11393]
**Describe the bug**
On the info side panel, there is a button that says

> Import local settings to remote RuneLite account

I don't know what that button does? 
Does it **export** local settings **to** remote RuneLite account
Or does it **import** local settings **from** remote RuneLite account

The words **import** and **to** contradict one another.

I have no idea which direction the sync is when you click this button, and I guessed wrong and lost all of my plugin configuration.

**To Reproduce**
1. Go to 'info' side-panel
2. Read the first button

**Expected behavior**
Either 
**Export** local settings **to** remote RuneLite account
Or
**Import** local settings **from** remote RuneLite account

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.12
 - Launcher version: 1.6.0

**Comment by dekvall** [comment]
I don't think that they contradict each other. In order to get the `Import..` option you have to be logged in to your RL account, and hence the local settings file will be the external source that we are importing from. Namely, we are importing the current *local settings* and where are these settings imported to? Well, the RL account that you are logged in to, so i think it's more of a clarification than a contradiction.

A backup of your remote settings is also stored in `~/.runelite/profiles` when you import your local settings so your original remote RL settings can be restored by moving that file and importing again.

**Comment by Atroxide** [comment]
So if I understand correctly- my client isn't actually using my local settings, its using 100% strictly the remote settings? Where exactly do the local settings come from? from before I logged into my account?

From a UI perspective, its extremely confusing and isn't user-friendly. I assumed clicking the button would sync my local settings (how my client is right now) to the cloud (remote account) so if I log in else where, my settings would be the same as they are now. Instead it ended up reverting my settings to when I first downloaded runelite before I ever set any plugins to be how I want them to be.

Maybe it's just me though. What is the actual intended use of this button if it isn't to sync your current setup to the 'cloud'?

**Comment by dekvall** [comment]
If you are logged in to an RL account it's strictly using the settings stored in that account yes. The local settings file is used to save your current configuration when you are not logged in.

If you are logged in on the same account on multiple devices, the settings are automatically synced between them. Having to re-import your settings every time you made a change in a config would kind of defeat the purpose of being logged in in the first place.

The purpose of the button is if you have been playing an extensive amount of time without being logged in, the process of transferring your setting will be smooth if you ever choose to make an account.

**Comment by claudiodekker** [comment]
> I don't think that they contradict each other. In order to get the `Import..` option you have to be logged in to your RL account, and hence the local settings file will be the external source that we are importing from. 

It's a matter of perspective: 
- You, the RuneLite user, are _exporting_ your local server to your _remote_ account. 
- The RuneLite server, is accepting this request and _imports_ it to your remote account.

From the perspective of the user/client, the label is indeed incorrect.

**Comment by claudiodekker** [comment]
@dekvall Just replied on my PR, but to keep discussion centralized and on-topic for everyone, I figured it would be better to reply here. [Here's what he mentioned](https://github.com/runelite/runelite/pull/11607#issuecomment-629130904): 
> I disagree with this proposed change and think that if anything, it makes it more confusing. You are still logged in, and i think it's wrong to use `Export` just because the server is spatially further away from you than your local settings file is.
> 
> `Synchronizing` in this context (you have just logged in and lost all your settings) would infer losing all your settings. Which is strictly not true, since you replace your logged in settings with settings from a local settings file.
> 
> I also think the amended `[...] as well as to any other RuneLite clients you might be logged in to` is unnecessary here, since preserving settings over devices is an integral part of the account system, and what else would replacing your settings do?
> 
> I understand that the issue you are referring to is tagged as `discussion` and i personally believe that the text is best kept as is, it's what most correctly describes what's happening.

@dekvall If I understand this correctly, you're saying that this feature/button is for **only for the following use case**:

1. User Installs RuneLite
2. User changes settings
3. User logs in to existing RuneLite account
4. RuneLite account settings are retrieved, overwriting & 'losing' the settings from step 2
5. User uses this feature/button, which reverts the previous step
6. RuneLite picks up on the 'revert', synchronizing the settings from step 2 to your RuneLite account.

Does that sound about right?

**Comment by abextm** [comment]
`Import` is the correct word because you are copying settings from the inactive (local) profile to the active (remote) profile

**Comment by dekvall** [comment]
I wouldn't say it "reverts the previous step" since your local settings file and Runelite account settings are separate entities, i.e. if you log out you get your local settings back. But yes, that's the only use case i see for this button. And it's extremely useful when you need it.

**Comment by claudiodekker** [comment]
Right. Yeah, totally. 

_Now that I'm aware_ of the way RuneLite handles account/settings-related things, the naming is indeed correct. However, that doesn't take away the problem of people that aren't similarly aware still clicking it, expecting it to be an oddly-worded way to manually sync your settings with your RuneLite account (like me and @Atroxide).

Is there anything we can do with the warning message to clarify this better? 
Perhaps something along the lines of:
> By continuing, you will lose your current settings, as well as your RuneLite account settings.
> They will be replaced with the settings you had prior to signing in with your RuneLite account.

**Comment by Atroxide** [comment]
> I wouldn't say it "reverts the previous step" since your local settings file and Runelite account settings are separate entities, i.e. if you log out you get your local settings back. But yes, that's the only use case i see for this button. And it's extremely useful when you need it.

So the use-case is only when you log into an account? what if when you log into an account, it has a checkbox option to "Override remote RuneLite settings with current local settings".

I mean it honestly doesn't make a big difference in the long run but I just feel like the button is super confusing on what it does, heck- my initial issue completely misunderstood what the button did and that's not good from a UI point of view. I asked a few buddies that I knew had RL what the button does and not a single one guessed the behavior correctly.

**Comment by abextm** [comment]
maybe it could say `Push logged-out settings to RuneLite account`

**Comment by jordan-git** [comment]
Came here to make the same request.  Proper grammar would definitely be "Export local settings to remote RuneLite account".

You, the local user, are exporting your settings to the cloud. The cloud is not importing your settings, as it did not initialize the transfer.

https://www.dictionary.com/browse/import

> to bring in (merchandise, commodities, workers, etc.) from a foreign country for use, sale, processing, reexport, or services.

https://www.dictionary.com/browse/export

> to send or transmit (ideas, institutions, etc.) to another place, especially to another country.

**Comment by Alexsuperfly** [comment]
you are already logged in to the account and pressing the button brings the logged out settings into the logged in profile

**Comment by jordan-git** [comment]
> you are already logged in to the account and pressing the button brings the logged out settings into the logged in profile

Technically would it not be you are exporting your settings to the cloud and then the client is importing them afterwards automatically?

**Comment by Alexsuperfly** [comment]
what the data actually does behind the scenes is sort of moot imo, the action that the user is taking is to bring something they dont have into their possession, they are importing settings that they currently do not have to the profile that they are currently in.

**Comment by PolarKC** [comment]
This thread is kind of old, but I'd just like to give my two cents.

The language for that button has led me to overwrite my local settings (which are always the most up to date, and preferred) on two occasions in the span of this year. I mistakenly used that button yesterday again thinking it would sync my settings up to the cloud, instead it overwrite what I had... reverting months of tweaks. I so infrequently need to do this sort of sync that I forgot what this actually does.

Please update the language, or make the upload/download sync process more intuitive. The auto-syncing is nice, but some indication of that happening on the computer I installed Runelite and logged into on would have potentially stopped me from trying to solve this problem myself and messing up by using this button.

**Comment by Adam-** [comment]
> 
> 
> This thread is kind of old, but I'd just like to give my two cents.
> 
> The language for that button has led me to overwrite my local settings (which are always the most up to date, and preferred) on two occasions in the span of this year. I mistakenly used that button yesterday again thinking it would sync my settings up to the cloud, instead it overwrite what I had... reverting months of tweaks. I so infrequently need to do this sort of sync that I forgot what this actually does.
> 
> Please update the language, or make the upload/download sync process more intuitive. The auto-syncing is nice, but some indication of that happening on the computer I installed Runelite and logged into on would have potentially stopped me from trying to solve this problem myself and messing up by using this button.

Note that it will create a backup prior to doing the overwrite so you can do the following to restore it:
```
1. Go to .runelite/profiles/<email>
2. Find the correct backup you want to use. It will have a big timestamp at the end.
3. Copy that file to .runelite
4. Delete settings.properties if it exists, then rename your backup file to settings.properties
5. Start up the client, log in (if you're not already), and import (found in the Info panel in the sidebar, the (i) icon)
6. Wait 30 seconds, then restart the client
```
Notwithstanding though I would not mind changing the wording to be clearer.

**Comment by TDinh1201** [comment]
> This thread is kind of old, but I'd just like to give my two cents.
> 
> The language for that button has led me to overwrite my preferred settings on two occasions in the span of this year. I so infrequently need to do this sort of sync that I forgot what this actually does.
> 
> Please update the language, or make the upload/download sync process more intuitive. The auto-syncing is nice, but some indication of that happening on the computer I installed Runelite and logged into on would have potentially stopped me from trying to solve this problem myself and messing up by using this button.

Oh my goodness, it's not just me. I accidentally lost my settings this way because I misunderstood it, too. I came upon this while trying to restore my settings. 

> By continuing, you will lose your current settings, as well as your RuneLite account settings.
> They will be replaced with the settings you had prior to signing in with your RuneLite account.

If there had been an explanation like what claudiodekker suggested earlier, I would've been able to avoid this frustration. I want to stress this: If it's not clear to a regular ol' user, then it's unhelpful regardless of how *technically* correct it is. 
Please, please adjust the wording.

**Comment by Adam-** [comment]
How about `Import local settings to RuneLite account`?

**Comment by alyoshanks** [comment]
I also overwrote my settings upon misunderstanding this button when I first began using runelite. I'm a little surprised this hasn't been adjusted in the year since this thread was opened, and want to second everyone who notes that being technically correct isn't helpful if that's confusing to the user.

**Comment by PolarKC** [comment]
> How about `Import local settings to RuneLite account`?
Here are a couple ways this could be worded better.
`Export local settings to Runelite account`
`Override Runelite account settings with current local settings`

**Comment by Alexsuperfly** [comment]
Those suggestions are terrible.  Exportation is the opposite of whats happening, and current implies its what you currently have which is obviously false.

**Comment by Hydrox6** [comment]
[Export is entirely wrong](https://github.com/runelite/runelite/issues/11393#issuecomment-629141396).
The `Override` line is basically just rewording the existing label without actually changing its meaning, perceived or otherwise.

This issue is going to keep happening not because of the wording, but because users are failing to read the warning box and thinking that they need to press the button to save their settings, which is entirely misfounded.

**Comment by PolarKC** [comment]
Yup, the users are wrong. If you want this place to have discussion and for users to give feedback, I suggest the bare minimum of not attacking the suggestions. You can take them or leave them.

It might be that your perspective, as contributors to the project, has made you incapable of understanding how regular braindead users view the client. As a regular user playing on an application running on my local machine EXPORT means "leaving my machine/client" and IMPORT means "going into my machine/client". When I'm interacting with my Runelite client I'm not thinking about the settings from the perspective of some fucking website and cloud stored settings.

**Comment by LlemonDuck** [comment]
It is valid to raise the concern that the wording confuses some users, but in the act of suggesting a **new** wording, you should not be offended to be told your suggestion was bad, if your suggestion was bad.

Hydrox is right with this:
> This issue is going to keep happening not because of the wording, but because users are failing to read the warning box and thinking that they need to press the button to save their settings, which is entirely misfounded.

This button needs to convey a lot of information in a very tiny space, which is going to inevitably cause some confusion from users that parse it (by no direct fault of their own) incorrectly. More detail is given in the confirmation screen, which many users skip, which is not the fault of RuneLite itself.

**Comment by Adam-** [comment]
Or, how about:
![image](https://user-images.githubusercontent.com/309739/117368048-01493d00-ae91-11eb-9c3c-805d0d0187b1.png)

**Comment by Adam-** [comment]
> 
> 
> Or, how about:
> ![image](https://user-images.githubusercontent.com/309739/117368048-01493d00-ae91-11eb-9c3c-805d0d0187b1.png)

I've changed the text to this.
