### ISSUE TITLE
Runelite Blue Screen of death everytime

### ISSUE THREAD

**Issue by Alexmaia23977** [runelite/runelite#11390]
I have runelite and I keep getting a blue screen of death crash everytime I play. I've tried turning plugins on and off, I've searched various forums, doing everything I could find and nothing works I still get the blue screen of death and I cannot use it. I've updated drivers etc everything on my computer is up to date and working fine.

**Comment by Alexmaia23977** [comment]
This is the error log 
 
The computer has rebooted from a bugcheck.  The bugcheck was: 0x00000124 (0x0000000000000000, 0xffffa08fdcc45028, 0x00000000b2000000, 0x0000000000070005). A dump was saved in: C:\Windows\MEMORY.DMP. Report Id: 4331d918-b4d6-4855-86c8-5d5456045d62.

**Comment by Alexmaia23977** [comment]
Can anyone help?

**Comment by abextm** [comment]
Runelite is not a kernel mode driver, and as such cannot cause a kernel panic such as the bsod

**Comment by Alexmaia23977** [comment]
Why does this not happen on the regular client or osbuddy then? Seems like a runelite caused problem. Kinda crappy to just close and say not your problem.

**Comment by abextm** [comment]
we likely hits a code path (probably in your graphics driver) that the other 2 clients don't.

**Comment by Alexmaia23977** [comment]
Is there any fix to that? I've updated graphics drivers and tried previous ones
