### ISSUE TITLE
Hide fires in minimap (Red Dot)

### ISSUE THREAD

**Issue by nlruk** [runelite/runelite#11401]
The red dot can be useful as it displays items on the ground however it also shows fires that aren't useful.. The only thing that does is clutters the minimap.

Would it be possible to keep the functionality of the red dot but exclude fires?

**Comment by Nightfirecat** [comment]
Fires do not make red dots appear on the minimap. You might be thinking of the ashes that fires leave behind?

**Comment by nlruk** [comment]
> Fires do not make red dots appear on the minimap. You might be thinking of the ashes that fires leave behind?

Ok, please remove them. It clutters the minimap especially when someone is training firemaking and it has no utility to us.

**Comment by Nightfirecat** [comment]
Minimap dots are of no concern when training firemaking. Beyond that, it is not a good idea or good precedence for us to hide minimap dots of ground items.

**Comment by nlruk** [comment]
> Minimap dots are of no concern when training firemaking. Beyond that, it is not a good idea or good precedence for us to hide minimap dots of ground items.

that is such a shame... ashes do in fact clutter the minimap go to any bank and you will see.
