### ISSUE TITLE
screenshot doesn't capture full screen with gpu on and dpi scaling at 125%

### ISSUE THREAD

**Issue by kobyhinnant** [runelite/runelite#11403]
**Describe the bug**
Taking a screenshot with windows dpi scaling set to 125% doesn't capture the full game area unless GPU plugin is turned off

OS: Windows 10
RuneLite version: 1.6.12
Launcher version: 2.1.0

**To Reproduce**
Set windows 10 dpi scaling to be 125%
Turn on GPU plugin
Launch runelite
Take a screenshot with the screenshot plugin

**Expected behavior**
The screenshot plugin should capture the full game regardless of GPU being turned on or off

**Screenshots**
With GPU turned on
![image](https://user-images.githubusercontent.com/42243069/80556625-0ecc0d00-8989-11ea-9050-74d291291492.png)

With GPU turned off
![image](https://user-images.githubusercontent.com/42243069/80556633-1d1a2900-8989-11ea-84e0-26fa4a1c8271.png)

**Comment by Alexsuperfly** [comment]
idk why you are flip flopping launcher versions but this should be fixed in 2.1 so just stick with that and stop using the 2.0 one randomly

**Comment by kobyhinnant** [comment]
meant to write 2.1, i'm not using 2.0

**Comment by kobyhinnant** [comment]
> idk why you are flip flopping launcher versions but this should be fixed in 2.1 so just stick with that and stop using the 2.0 one randomly

**Comment by kobyhinnant** [comment]
> idk why you are flip flopping launcher versions but this should be fixed in 2.1 so just stick with that and stop using the 2.0 one randomly

meant to write 2.1, i'm not using 2.0, edited now

**Comment by raiyni** [comment]
This is fixed for me in 2.1

**Comment by Biice** [comment]
@kobyhinnant Slightly off-topic, but when using windows scaling at e.g. 125%, does your Runescape also turn blurry? The new UI scaling options under the _GPU_ plugin make it somewhat more bearable, but I still find it virtually unplayable. Feels like I need glasses playing with windows scaling—due to the blurriness, not the size of the launcher of course, which is where windows scaling helps.

**Comment by kobyhinnant** [comment]
> @kobyhinnant Slightly off-topic, but when using windows scaling at e.g. 125%, does your Runescape also turn blurry? The new UI scaling options under the _GPU_ plugin make it somewhat more bearable, but I still find it virtually unplayable. Feels like I need glasses playing with windows scaling—due to the blurriness, not the size of the launcher of course, which is where windows scaling helps.

Yeah without gpu on I can't bear it, its super blurry. With gpu on its not nearly that bad, but my screenshots don't work... So...

**Comment by Adam-** [comment]
Going to assume this is fixed by #12594 - reopen if not. To test it you need to be running the *launcher* with the fix (so wait for a release). Also preferably use the 2.1.3 launcher.
