### ISSUE TITLE
Prevent Plugin Hub button from scrolling

### ISSUE THREAD

**Issue by while-loop** [runelite/runelite#11407]
**Is your feature request related to a problem? Please describe.**
In order to view plugins in the hub, you must scroll to the very bottom of the PluginList. 
For frequent checks of the plugin hub, scrolling can become tedious (with an ever-growing plugin list).

It also makes sense to remove it from the scroll pane since it's the button itself is not a plugin ( for example, the search text area does not scroll)

**Describe the solution you'd like**
I would prefer then Plugin Hub button to be fixed at the bottom of the PluginListPanel

**Describe alternatives you've considered**
None

**Additional context**
I'm able to provide the change, just want to get "Okay" or alternate suggestions for the button.

**Comment by abextm** [comment]
It was placed at the bottom of the scroll pane so its not front and center for discoverability — we aren't trying to push everyone to install a bunch of code that may or may not work correctly.

**Comment by makingcomment** [comment]
One solution would be to add a setting that would add an icon/button to the sidebar (e.g. under the wrench icon), which would take you directly to the plugin hub.

By putting the switch to enable that within the plugin hub and defaulting it to "off", the plugin hub would become easily accessible for those who have already found it without increasing its discoverability for those who haven't.
