### ISSUE TITLE
Add Blade of Saeldor (c) to Bank Value

### ISSUE THREAD

**Issue by TripleDeuce** [runelite/runelite#11404]
Can the Blade of saeldor (c) have the same value as the Blade of saeldor (inactive) in the Bank value indicator. I understand why an item like the avernic defender doesn't have any value, because once combined you can't get the avernic defender hilt back to potentially sell. The Blade of saeldor (c) is able to be uncharged and become the Blade of saeldor (inactive) which is still around 172M. I hate how my bank value drops about 172m by having the Blade of Saeldor with infinite charges.

**Comment by SammRosenthal** [comment]
I would like to take this as a first issue. I was looking at the change to be made and was wondering if there is an example of how this has been handled in the past? I am assuming the api call to get the GE price will return undefined or some failed value? If this is not the correct place to ask for help could you please point me in the right direction. Thanks!

**Comment by dekvall** [comment]
You can take a look at [ItemMapping.java](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/game/ItemMapping.java) where we map other untradeables to to tradeable counterparts. You are also very welcome to join our [Discord](https://discord.gg/mePCs8U) if you have any further questions.
