### ISSUE TITLE
Highscores look up tab

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1140]
-Auto switch tabs to highscores tab when looking someone up
-Double click in search user fills own name

**Comment by deathbeam** [comment]
1st option is already implemented, but not working in release, should be working in next release.

**Comment by burgo7** [comment]
Could an autofill option be added using your friends list? Similar to the feature in OSBuddy

**Comment by Adam-** [comment]
First one was done some time ago? Second was implemented in #1530
