### ISSUE TITLE
Plugin organizer

### ISSUE THREAD

**Issue by TormStorm** [runelite/runelite#11417]
I am suggesting a plugin that will let users choose to organize all plugins into categories to make it much easier to find plugins without having to remember the names of plugins.

This plugin would put all plugins into categories like combat, skills, items etc to make it much easier to find plugins related to a specific activity. I would also suggest having a favorite category at the very top where all of a users favorite plugins will be. These plugin categories should be drop-down menus to show the plugins for each category. This will make it much easier to find the plugins and categories without having to scroll a lot to find what you want.

This plugin have been suggested before, but has never been released, and i think that's a shame, because i think that a lot of people would like to have the option to organize plugins by categories, and i think a lot of people would greatly benefit from it.

This is a screenshot from https://github.com/runelite/runelite/pull/2444, which was never released, but is similar to something that i have in mind for this plugin, except like i said i think that the categories should be drop down menus to make categories and plugins easier to find without a lot of scrolling.
![2444](https://user-images.githubusercontent.com/35997481/80745527-b9c2ff00-8b20-11ea-89a5-27e8fbe3b8a8.png)

**Comment by psikoi** [comment]
Why is the font on those category titles so big?
