### ISSUE TITLE
Add keybind to toggle ground items overlay

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1141]
Press alt (or any key really) to toggle item overlay on ground

Edit:
Option for different fonts/size/boldness of characters to make it a bit easier to read? Dunno how many options or how feasible this is

**Comment by Adam-** [comment]
Seems this issue got lost? I think this was added in 1.3.1 in #991

**Comment by Nightfirecat** [comment]
This isn't fixed; you cannot completely toggle ground items on and off with a keybind.
