### ISSUE TITLE
Skybox

### ISSUE THREAD

**Issue by nlruk** [runelite/runelite#11425]
Can you remove the skybox plugin and put it in the gpu plugin?

**Comment by Alexsuperfly** [comment]
its designed to be able to work without gpu, why would you want to remove that

**Comment by nlruk** [comment]
> its designed to be able to work without gpu, why would you want to remove that

not many people know about the skybox plugin and I want everyone to benefit from it.

It's a nice visual effect and could be added to the more frequently used gpu plugin

**Comment by raiyni** [comment]
As alex said, it's made to work with both CPU and GPU. They can look through the plugins themselves. It's literally called `Skybox`.

**Comment by stoddy15** [comment]
This is what I was referring to but fair enough if you don't like that.

<img width="265" alt="Screenshot 2020-05-02 at 15 26 21" src="https://user-images.githubusercontent.com/63739578/80920777-e87fe600-8d69-11ea-9d8b-1ed07b41fd2c.png">
