### ISSUE TITLE
NPC Agression timer Ammonite crabs not working

### ISSUE THREAD

**Issue by themanlile** [runelite/runelite#11421]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
whenever im attacking ammonite crabs i cant get it to activate. I tried adding rock, and other variates of the name. I read that if you put *dragon it works on all dragons so i put *rock and *crab, nothing still. i teleported to lumbridge and back but that didnt work.

**To Reproduce**
1. Go to Ammonite crabs
2. Click on Activate the plugin
3. Make sure the names are on.
4. See error. nothing appears

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/64623228/80778242-525f7c00-8b2d-11ea-9cb6-7e5eacc46dc1.PNG)

**Environment (please complete the following information):**
 - OS: windows
 - RuneLite version: [e.g 1.6.
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by emerald000** [comment]
You need to use the rock form of crabs (Fossil Rock in this case).

**Comment by themanlile** [comment]
> You need to use the rock form of crabs (Fossil Rock in this case). If there's the warning message as in your screenshot, you also have to leave and then come back.


I have left and come back, i have relogged, i have tp to lumbridge and come back. the only thing i havent tried is to go into a dungeon like it says and come back. but thats cause idk where a close dungeon is.

**Comment by Nightfirecat** [comment]
Based on the overlay, you need to teleport or enter a dungeon so the plugin can establish where your "aggression zones" are. Until you do that, it does not know where you would have to run to in order to restart the aggression timer.
