### ISSUE TITLE
Rune pouch tooltips icons

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1142]
Have an option to have the hover option be the rune icons instead of the text

This: https://i.imgur.com/P75H5Tm.png   takes up a lot of space in inventory vs this https://i.imgur.com/KhdbbwG.png

With this probably have the icons/amount go away except on hover aswell (so you would see only the rune pouch when not hovering because currently this is the only option when its on https://i.imgur.com/mhwf2zN.png . At least the one that has the least stuff on it

**Comment by SoyChai** [comment]
Are you suggesting two features here? I think the screenshots actually made it more confusing for me than the text alone, haha.

- Use icons in the tooltip so it looks like the pouch overlay, just with longer numbers
- Add an option to disable the pouch overlay and only see the tooltip

That's what you want to see, right?

**Comment by Stickaplex** [comment]
Essentially what I am looking for is 

1. With no hover it just shows plain old rune pouch no overlays or anything on it
2. With hover it only shows the icons and the numbers (eg 15k). So how it currently looks with icons enabled

Hope that makes it a bit more clear. Reading it over i can understand why your confused =p

**Comment by ShaunDreclin** [comment]
Personally I'd like having the overlay always on it, and remove the tooltip for it all together since it's redundant. If you have more than four (three?) digits of runes, you don't need any more granularity than what the overlay gives you at a glance.

**Comment by Stickaplex** [comment]
Yea I personally dont like overlay at all for the rune pouch, but if I want to know how much/what is in there I like having it on for that reason and the current tooltip takes up a lot of space. So thats why I would kind of like having the current overlay as a tooltip if that makes sense

**Comment by ShaunDreclin** [comment]
Yeah maybe get rid of the tooltip completely and have a toggle to show the overlay always or on mouseover

**Comment by Stickaplex** [comment]
I like that idea. Although not sure if people like the current tooltip or not, hence why I suggested this work-around

**Comment by SoyChai** [comment]
I agree with the logic of just dropping the tooltip, no offense to anyone who worked on it! 😏 It does feel redundant to me personally.

**Comment by deathbeam** [comment]
I use the tooltip only :d

**Comment by SoyChai** [comment]
What if we allowed the _overlay_ to show exact numbers on hover instead?

**Comment by deathbeam** [comment]
i don't like reinventing the tooltip system just for this single case very much tbh

**Comment by deathbeam** [comment]
As noone has looked at this since the issue creation I guess this request is not needed at all and can be closed
