### ISSUE TITLE
Add buy/sell 1/5/10/50 menu entry swaps for shops, like you can do on mobile.

### ISSUE THREAD

**Issue by geheur** [runelite/runelite#11427]
**Is your feature request related to a problem? Please describe.**
When buying a lot of an item from shops, having to right click to select the buy/sell option for the item takes some effort. The same is true for selling large amounts an item to shops.

**Describe the solution you'd like**
I'd like to be able to swap the buy/sell 1/5/10/50 options to the top of the menu so I can buy or sell lots of items with just a left-click.

**Describe alternatives you've considered**
Mousekeys/ahk - takes more effort than a single click and I'd have to do some research to learn how to set this up.
For selling stackable items, putting the item in the bottom of the inventory to make the right click menu open up with "Sell 50" already under the mouse - only works for selling.

**Additional context**
This swap was once rejected but the wording on this page https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping makes it sound like it would now be ok to have this swap due to mobile having something similar.

**Comment by Adam-** [comment]
added in #11453
