### ISSUE TITLE
Grand Exchange plugin "Search Mode" configuration has no meaningful description

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#11431]
Currently it is only "The search mode to use for the GE", which does little to describe the difference between Default, Fuzzy Fallback, and Fuzzy Only. This should be fleshed out to give at least a high-level description of its function.

**Comment by mokhan5** [comment]
Hi, can I tackle this issue?

**Comment by Spedwards** [comment]
Go for it! @mokhan5

**Comment by mokhan5** [comment]
Okay, I wrote descriptions for each search option. But it doesn't seem like I can add line separators to break them up?

**Comment by Nightfirecat** [comment]
You can use `<br>`.
FYI, we recommend bringing development discussion to our `#development` Discord channel.

**Comment by mokhan5** [comment]
Okay, thanks! As for the discord development channel it says I don't have permission to send messages

**Comment by Nightfirecat** [comment]
Read the channel description for steps on how to chat there.
