### ISSUE TITLE
Add phone notification support via Pushover or other service

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#11437]
Can someone implement this please? I was recommended this in the discord but I don't know how to use it.

https://pushover.net/

https://github.com/sps/pushover4j/

**Comment by stoddy15** [comment]
There are other services if its easier or better

https://kdeconnect.kde.org (open source)
https://www.pushsafer.com

**Comment by ks0i** [comment]
> There are other services if its easier or better
> 
> https://kdeconnect.kde.org (open source but doesn't support iOS)
> https://www.pushsafer.com

iOS is very necessary.
