### ISSUE TITLE
hiscore: Bounty Hunter emblem indicators cause hiscore lookups to use wrong name

### ISSUE THREAD

**Issue by abelbriggs1** [runelite/runelite#11440]
Searched for this issue, didn't seem to find one for this. Feel free to close if this is a duplicate.

**Describe the bug**
In the new version of Bounty Hunter, players who have emblems have their name strings modified to have the tier of emblem they are currently carrying appended to their username. This causes the 'lookup' option on players to use the wrong name and fail.

**To Reproduce**
1. Go to a Bounty Hunter world
2. Right click someone with an emblem skull and click 'lookup'

**Expected behavior**
The correct player name should be used in the lookup.

**Screenshots**
![Example image](https://user-images.githubusercontent.com/27463243/80893281-8609e580-8c96-11ea-88b8-ea696da0550b.png)

In this instance, the player's actual name is 'lite tur', but the lookup option sends 'lite tur4' to the hiscore tab.

**Environment (please complete the following information):**
Linux Mint 19, Java 8
RL 1.6.13
Launcher 1.6.1

**Comment by abelbriggs1** [comment]
https://github.com/runelite/runelite/blob/baf4f58768ef98e180457846c35b74135bb229ff/runelite-client/src/main/java/net/runelite/client/plugins/hiscore/HiscorePlugin.java#L186

It looks like the actual symbol for the emblem is not a text character, so it's omitted from the text returned by `event.getMenuTarget()`. A hack might be needed to handle this in the HS plugin itself by doing some text removal logic there based on if someone has a Bounty Hunter emblem skull. I don't know if there's something in the API yet to check for that specific type of skull.

**Comment by Nightfirecat** [comment]
This is because we strip images from names (such as when players have BH emblems or clan chat icons appearing in their menu options) but apparently the number appearing after BH emblems is a plain `4` afterward.
