### ISSUE TITLE
Content Creator Mode

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#11445]
This will be useful to streamers/youtubers

- Hide text above players (Malicious players say racial slurs to ruin footage)
- Hide world in friends list 

<img width="430" alt="Screenshot 2020-05-03 at 12 13 51" src="https://user-images.githubusercontent.com/63739578/80913084-adfe5500-8d39-11ea-8d13-18a4774df8eb.png">
<img width="374" alt="Screenshot 2020-05-03 at 12 13 32" src="https://user-images.githubusercontent.com/63739578/80913086-b2c30900-8d39-11ea-927a-64c16160a00b.png">
<img width="378" alt="Screenshot 2020-05-03 at 12 13 09" src="https://user-images.githubusercontent.com/63739578/80913088-b9ea1700-8d39-11ea-979e-2d0131f23a6e.png">

**Comment by Hydrox6** [comment]
1. `Chat Filter` does this already
2. `World Hider` in the hub does this already
