### ISSUE TITLE
The "edit-tag" option is formatted the same as your name if you are in a cc

### ISSUE THREAD

**Issue by flizzflobking** [runelite/runelite#11448]
If you aren't in a cc, your edit-tags option looks normal: 
![](https://i.imgur.com/ZHvGqgs.png)
If you are in a cc, your edit-tags option looks like your name in cc (different colour, purple in my case), and has your rank icon in front of it: 
![](https://i.imgur.com/I6YODqs.png)
![](https://i.imgur.com/ltq8JAY.png)
![](https://i.imgur.com/PvMygu6.png)
![](https://i.imgur.com/3MJKWCo.png)

**Comment by MarbleTurtle** [comment]
Managed to have it happen to me as well, was resolved by relogging without closing the client.
![image](https://user-images.githubusercontent.com/60723971/81773620-92afea00-949d-11ea-8e40-12b0a4c09984.png)
As suspected its plugin hub related plugins I have are: Banked value tracker, banked experience, chat transcripts, clan chat warnings, clanchatcountryflags, detatched camera (i think its this one), emoji palette, equipment inspector, fight cave waves, flipping utilities, friends exporter, herb sack price check, inventory setup, loot logger, menu swapper extender, profiles, raidreloader, spec gregen timer, supplies tracker, volcanic mine, world highlighter, zulrah plugin

**Comment by raiyni** [comment]
Probably the Player Indicators plugin https://github.com/runelite/runelite/commit/087b2ac9695778464962f6d28b02db7c2e3ae9cd

**Comment by Adam-** [comment]
Do we know why this happens?

**Comment by raiyni** [comment]
Happens with `menuType == RUNELITE` and the entry identifier op happens to be an index in `client.getCachedPlayers()` with clan information. 

Because the only check on identifier is `if (identifier >= 0 && identifier < players.length)`
