### ISSUE TITLE
Make Boost Infoboxes Support Different Interface Styles

### ISSUE THREAD

**Issue by Biice** [runelite/runelite#11443]
![Runelite Boost Mismatch](https://user-images.githubusercontent.com/46752106/80895305-b166f180-8ce3-11ea-9cd8-15c38df852e2.png)
As can be seen in the above image, the boost infoboxes rely on the default skill icons despite using a different Runelite interface style. It'd be great if these could be updated to work with the various interface styles available.

**Comment by Nightfirecat** [comment]
Duplicate of #11406
