### ISSUE TITLE
"Runelite has not yet been updated"

### ISSUE THREAD

**Issue by TheSOlsen** [runelite/runelite#11457]
Anyone else ever had this issue? On the latest version (1.6.13). Yes I've googled it, Yes I've uninstalled it, Yes I've even used the Registry Editor to uninstall it. Nothing seems to be working.. It's made my Client literally a vanilla RS client.

**Comment by TheSOlsen** [comment]
![Annotation 2020-05-04 193756](https://user-images.githubusercontent.com/64772629/80945473-015acb00-8e40-11ea-8bb6-5988372c2d2a.png)

**Comment by Unmoon** [comment]
Delete `cache` folder in `%userprofile%\.runelite`.
