### ISSUE TITLE
Runecrafting Pouches not updating correctly

### ISSUE THREAD

**Issue by hkbertoson** [runelite/runelite#11459]
Runecrafting Pouches not updating correctly. While Runecrafting at ZMI, I have to fill my Runecrafting pouch and then "Check it" before the overlay will update correctly. This is only happening with the Medium Pouch.

**Comment by Hydrox6** [comment]
Issues with Plugin Hub plugins should be filed in [their repo](https://github.com/Adam-/runelite-plugins), not here
