### ISSUE TITLE
Glitching Screen 

### ISSUE THREAD

**Issue by jtrinh33** [runelite/runelite#11468]
![Capture](https://user-images.githubusercontent.com/64823346/81033490-e436f400-8e61-11ea-964f-e5f995dd42ee.JPG)

**Comment by Nightfirecat** [comment]
Please check through our [GPU FAQ wiki page](https://github.com/runelite/runelite/wiki/GPU-FAQ) and [join the `#support` channel on our Discord server](https://runelite.net/discord).
