### ISSUE TITLE
WorldArea::canTravelInDirection always returns false.

### ISSUE THREAD

**Issue by jegijsje** [runelite/runelite#11464]
**Describe the bug**
WorldArea.canTravelInDirection always returns false.

**To Reproduce**
Get the RuneLite client from source and compile it with the --dev-tools argument.

**Expected behavior**
When on the plugin panel of Dev Tools and I click on Valid Movement, I expect there to be a 3x3 box around me showing me if something blocks my movement.

**Screenshots**
[Hosted on Imgur](https://i.imgur.com/FIe424A.png)

**Environment (please complete the following information):**
Windows 10, RuneLite source pulled on 03/05/2020

**Additional context**
I used this code to test what happend:
```
if (area.canTravelInDirection(client, dx, dy))
{
	LocalPoint lp = actor.getLocalLocation();
	if (lp == null)
	{
		return;
	}

	lp = new LocalPoint(lp.getX() + dx * Perspective.LOCAL_TILE_SIZE + dx * Perspective.LOCAL_TILE_SIZE * (area.getWidth() - 1) / 2, lp.getY() + dy * Perspective.LOCAL_TILE_SIZE + dy * Perspective.LOCAL_TILE_SIZE * (area.getHeight() - 1) / 2);

	Polygon poly = Perspective.getCanvasTilePoly(client, lp);
	if (poly == null)
	{
		return;
	}

	OverlayUtil.renderPolygon(graphics, poly, Color.GREEN);
}
```
Nothing happens. When I change `if (area.canTravelInDirection(client, dx, dy))` to `if (area.canTravelInDirection(client, dx, dy)) == false` this happens:
[Imgur link](https://i.imgur.com/Lg0C6sL.png)

**Comment by Nightfirecat** [comment]
This is because `Client#getCollisionMaps()` returns `null` while standing in most locations to prevent abuse, and is expected behavior.
