### ISSUE TITLE
Infobox wrap count missing?

### ISSUE THREAD

**Issue by MissHollieB** [runelite/runelite#11470]
On the runlite plugin, the setting to change the number of infoboxes that stack before wrapping is missing.

This is a recent change, and fresh installs don't fix it, the problem also occurs on my laptop as well.

![wiki picture](https://user-images.githubusercontent.com/64510974/81065031-b0e07d80-8ed2-11ea-872d-41d9e7d59395.PNG)
This picture is the one found on the wiki page for the plugin

![my client](https://user-images.githubusercontent.com/64510974/81065040-b342d780-8ed2-11ea-95ae-deb10f85a9d8.PNG)
And this is what I see on my client. The option is missing.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.13
 - Launcher version: 2.1.0

Sorry if i'm missing anything haven't used github before really.

**Comment by Hydrox6** [comment]
[Read the announcements](https://runelite.net/blog/show/2020-04-16-1.6.11-Release/)
