### ISSUE TITLE
Idle Notifier checks notification levels when RuneLite is minimized and notifies if needed

### ISSUE THREAD

**Issue by marmiha** [runelite/runelite#11486]
**Is your feature request related to a problem? Please describe.**
Im always frustrated when I open RuneLite client to attack a mob and exactly at that time my prayer points drop under the level I've set the notifications in the Idle Notifier. When I minimize RuneLite it does not notify me about the low prayer level so I just die or get the low hitpoints notification.

**Describe the solution you'd like**
Maybe add a feature (optional or not), that checks the prayer level with the one in Idle Notifier when you minimize the app. If that level is lower than the set one, send a notification about low prayer level otherwise don't

**Describe alternatives you've considered**
Mini screen overlay when you minimize RuneLite, showing basic player status like - hitpoints, prayer, player idle/fighting/running status and a list ground items in 5 square radius. The overlay would be like the one of windows game recording when u pres WIN + G or something simillar.

**Comment by Nightfirecat** [comment]
You can already enable the "Send notifications when focused" option under RuneLite's settings to ensure you'll be notified.

**Comment by marmiha** [comment]
Alrgiht will look into that, thanks for the reply :)
