### ISSUE TITLE
Bot Analysis Plugin

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#11484]
Can you use the data here to form a plugin?

https://youtu.be/3LH1TYoqDDI

https://github.com/chriskok/BotClassification-OSRS/blob/master/data/player_data_04-2020.csv
https://github.com/chriskok/BotClassification-OSRS/blob/master/EDA.ipynb
https://mybinder.org/v2/gh/chriskok/BotClassification-OSRS/2920f262e2a54ef0d2aa30c973b85c8a68cd8e04

**Comment by Nightfirecat** [comment]
What would such a plugin do?

**Comment by stoddy15** [comment]
> What would such a plugin do?

Ask Adam or Hydrox. 




Their brilliant minds will come up with something.

**Comment by Nightfirecat** [comment]
I'm closing this for now as it's not an actionable suggestion.

**Comment by stoddy15** [comment]
> I'm closing this for now as it's not an actionable suggestion.

It's not actionable because you haven't asked Hydrox or Adam.
