### ISSUE TITLE
Add option to toggle activity overlay in the Wintertodt Plugin

### ISSUE THREAD

**Issue by anonymouscnidaria** [runelite/runelite#11482]
**Is your feature request related to a problem? Please describe.**
The wintertodt plugin shows the number of roots and kindlings in the inverntory

**Describe the solution you'd like**
I would like it to be toggle-able so I can turn it off as it's not something i need to see on screen

**Describe alternatives you've considered**
n/a

**Screenshot**
![image](https://user-images.githubusercontent.com/58953980/81161053-87505080-8fbd-11ea-81ed-eab3163f8c54.png)

**Comment by abextm** [comment]
added in eae4e0b
