### ISSUE TITLE
Runelite freezes when I start the GPU plugin

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#11492]
**Describe the bug**
My runelite freezes when I attempt to start the GPU plugin and stops reacting to any kind of input. I have to kill it using an external utility. 

These are the last lines on standard output:
```2020-05-07 12:15:09 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1678x980,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized_vert,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1678x1067,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@4a6441af,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2020-05-07 12:15:20 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
com.jogamp.opengl.GLException: Profile GL4bc is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7f63c06037c0, owner true, JAWTToolkitLock[obj 0x61d8435, isOwner true, <5b4a9e1f, 4ef4120f>[count 1, qsz 0, owner <Client>]]], but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw], GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]
        at com.jogamp.opengl.GLProfile.get(GLProfile.java:991)
        at jogamp.opengl.GLContextImpl.verifyInstance(GLContextImpl.java:1471)
        at jogamp.opengl.GLContextImpl.setGLFunctionAvailability(GLContextImpl.java:1942)
        at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:395)
        at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
        at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
        at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
        at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$1(GpuPlugin.java:327)
        at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
        at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:193)
        at client.my(client.java:21613)
        at client.ao(client.java)
        at br.ab(br.java:362)
        at br.run(br.java:316)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**To Reproduce**
Not sure what information is needed. I just try to toggle the plugin on. See "environment". 

**Expected behavior**
If the plugin cannot work in my environment, it should produce an error message and stay turned off, instead of freezing the whole program. 

**Screenshots**

**Environment (please complete the following information):**
Runelite version is  1:1.6.12.

I am using `java-14-adoptopenjdk` and I have `mesa` installed.

I hope the following describes my Linux system, can provide more info if requested:

    $ uname -a
    Linux jb-lenovo 5.6.10-arch1-1 #1 SMP PREEMPT Sat, 02 May 2020 19:11:54 +0000 x86_64 GNU/Linux
    $ lspci -v|grep VGA
    00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

However, some quick points:
* 1.6.12 is not the latest version. If you're constantly restarting the client and it still says that version, make sure you're actually using RL and not a fake.
* Certain Java versions do not work. Use the AppImage to use a Java version that is known to work

**Comment by Nightfirecat** [comment]
In addition to what Hydrox mentioned, it's important to understand that RuneLite is only officially supported via the following distributions:

* Launcher downloads provided on [runelite.net](https://runelite.net) (32- and 64-bit Windows exe installers, MacOS dmg installer, AppImage for linux, and all-platform jar)
* Via `snap`, [on Snapcraft](https://snapcraft.io/runelite)

If you've installed your client from anywhere else it is at best not an official distribution, and at worst a malicious client masquerading as us.
