### ISSUE TITLE
Slayer plugin: Add more task icons

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1149]
Plenty of tasks still missing icons, suggest em here!
Feel free to think outside the box, I think an odd semi-fitting icon is better than no icon.

- Scorpions: Ensouled scorpion head
- Shadow warriors: Corrupted helm (Maybe? closest thing I could think of.)

**Comment by SoyChai** [comment]
[List of all supported Slayer tasks](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java) if anyone needs to double-check.

**Comment by rune3132** [comment]
The plugin is missing fire giants, flesh crawlers, ghosts, ghouls, icefiends, ice giants, jungle horrors, moss giants, waterfiends, fossil island wyverns, scorpions, and shadow warriors.

Fossils island wyverns have an icon that can be used, scorpions have the ensouled head, and shadow warriors have corrupted/black full helm. Bue the rest doesn't seem to have any obvious icons.

**Comment by ShaunDreclin** [comment]
- Jungle horror: Ensouled horror head
