### ISSUE TITLE
Wealth Evaluator (External Plugin)

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#11494]
Detects items other players are wearing and calculates their wealth. Another open source client does it but I want this for my favourite client!

<img width="341" alt="Screenshot 2020-05-07 at 15 09 04" src="https://user-images.githubusercontent.com/63739578/81304817-7b27ca00-9075-11ea-97ef-434e909ab67e.png">

**Comment by Hydrox6** [comment]
Banned by the [Jagex Statemet](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Offers additional information about other players, with the purpose of scouting PvP targets`

**Comment by stoddy15** [comment]
> Banned by the [Jagex Statemet](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Offers additional information about other players, with the purpose of scouting PvP targets`

This has nothing to do with pvp.

**Comment by stoddy15** [comment]
> Banned by the [Jagex Statemet](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Offers additional information about other players, with the purpose of scouting PvP targets`

This has nothing to do with pvp. I am dyslexic so it would be useful to know prices. please Hydrox can you consider it? I am sorry for naming you on my issue yesterday. I didn't mean to offend you.

**Comment by nlruk** [comment]
Ask Milky he seems to take on everything.

**Comment by nlruk** [comment]
I can't find his email or contact information on his profile but you can find him here @melkypie

**Comment by stoddy15** [comment]
How do I PM him?

**Comment by nlruk** [comment]
> How do I PM him?

https://oldschool.runescape.wiki/w/User:Melkypie
