### ISSUE TITLE
Runelite Lagging

### ISSUE THREAD

**Issue by ItsTyme** [runelite/runelite#11497]
Hello everyone. I'm having an odd issue with the RuneLite client. Whenever it starts up it makes my screen flicker until it loads the login screen. After that, everything is fine until I try and use the sidebar features. It then makes my fps drop drastically and sometimes shuts my screen off for a second or two. 

I've also followed the accelerator guide in turning it off, it fixed an initial issue at first but was no help for this particular one. 

If anyone has any idea why this could be happening please let me know.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
