### ISSUE TITLE
Bank Tags & Degradeable armor such as barrows

### ISSUE THREAD

**Issue by claythearc** [runelite/runelite#11501]
**Is your feature request related to a problem? Please describe.**
I have noticed that when you add a tag to an item such as Guthans spear, it only persists for that single stage of the item, leading to needing to add a tag for every stage of it throughout its degradation.

**Describe the solution you'd like**
Some way to tag a degradeable item X and have it also store tags for the broken, new, 100, 75, 50, 25, etc variations.

**Comment by Nightfirecat** [comment]
From the [Bank Tags wiki page]:

> You can tag and un-tag all variations of an item, e.g. all dosages of a particular type of potion, all charges of an Amulet of Glory, or all degraded states of a Barrows equipment piece or piece of crystal equipment, etc. To do so, drag the item onto a tag tab while holding Shift, or add "*" to the end of the tag.

![variation bank tags](https://user-images.githubusercontent.com/5115805/47704264-69b16680-dc23-11e8-8ead-a4934fb9ef38.gif)
