### ISSUE TITLE
Calling client.getWidgetRoots() during the first frame after gamestate == logged_in throws an exception

### ISSUE THREAD

**Issue by ThatGamerBlue** [runelite/runelite#11500]
**Describe the bug**
Calling client.getWidgetRoots() on the first frame the gamestate changed to logged_in throws an ArrayIndexOutOfBoundsException

**To Reproduce**
1. Create a plugin with
```java
@Subscribe
	private void onBeforeRender(BeforeRender event)
	{
		if (client.getGameState() != GameState.LOGGED_IN)
		{
			return;
		}

		client.getWidgetRoots();
	}
```
2. Ensure plugin is enabled when logging into game
3. Observe java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 663
	at client.getWidgetRoots(client.java:26930)

**Expected behavior**
A return value of an empty array if client.rootInterface == -1, otherwise normal behaviour.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS] Windows 10 LTSC
 - RuneLite version: [e.g 1.4.6] 1.6.14-SNAPSHOT
 - Launcher version: [e.g 1.5.2] N/A

**Comment by Adam-** [comment]
This has been fixed to return a 0 length array if no tli is set.
