### ISSUE TITLE
Decrypt base64

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#11519]
Sometimes my friend sends me messages in base64, can we have a plugin that decrypts it on the fly? He is paranoid about big brother

Example:

UGxlYXNlIGRvbid0IGRlbGV0ZSB0aGlzIGFkYW0gYW5kIGh5ZHJveC4gdGhpcyBpcyBhIHN1Z2dlc3Rpb24=

**Comment by loldudester** [comment]
bm8=

**Comment by stoddy15** [comment]
> bm8=

Very funny bro

What exactly is wrong with this suggestion? Can you please give intelligent criticism?

**Comment by Spedwards** [comment]
It's bad. We don't want it. Can you please give an intelligent reason as to why we'd want this?

**Comment by stoddy15** [comment]
There is more uses for this than Inventory Scrabble

**Comment by Hydrox6** [comment]
1. There's a difference between a silly thing that someone made, and a stupid request
2. This won't ever work due to how the game handles messages. If you actually did what you said, you would know this.
3. Stop making issues you have not actually thought about. Some of your suggestions are good, but a whole load of them are obviously not possible and/or entirely useless.

**Comment by stoddy15** [comment]
Some of your suggestions are good, but a whole load of them are obviously not possible and/or entirely useless.

Sorry I will try not to disappoint you on my next one.

**Comment by stoddy15** [comment]
I have been trying to find a solution and came across this: http://anvyst.com/2016/10/base32-advantages-over-base64/

This can prevent big brother reading our in-game messages unless they have the runelite base32 plugin

**Comment by stoddy15** [comment]
I've been thinking for a while and was wondering if we could have a pastebin runelite plugin that we can communicate within the text? for example I would send jCKdgSrG to someone on runelite. they would click it and it would redirect to https://pastebin.com/jCKdgSrG

After someone has clicked that link, read it once it will be burnt so no-one can read it again then they will create a pastebin to reply

<img width="498" alt="Screenshot 2021-01-09 at 1 16 35 pm" src="https://user-images.githubusercontent.com/63739578/104092612-f123a700-527c-11eb-9bdd-48490a1fa76c.png">
