### ISSUE TITLE
Keyboard Bankpin conflicting with Key Remapping

### ISSUE THREAD

**Issue by erobert98** [runelite/runelite#11512]
When you use the keyboard bankpin option to enter your pin, if you used key remapping to change the default Escape key to a number key, it will act like the escape key closing the bank window.  This is only a problem when using the number keys above the keyboard, using numlock numbers doesnt face the same problem.

**Comment by BKOSRS** [comment]
This is a result of these changes here: https://github.com/runelite/runelite/commit/26ffd1be33157ad7e798c8675969a6b5da454203

Unfortunately this leaves those who have their number keys remapped to F keys, but don't have a numpad in conjunction, unable to use keyboard bankpin.

**Comment by Adam-** [comment]
> 
> 
> This is a result of these changes here: [26ffd1b](https://github.com/runelite/runelite/commit/26ffd1be33157ad7e798c8675969a6b5da454203)
> 
> Unfortunately this leaves those who have their number keys remapped to F keys, but don't have a numpad in conjunction, unable to use keyboard bankpin.

FWIW There's a good chance hes not even running 26ffd1be33157ad7e798c8675969a6b5da454203 as it isn't in the release.

**Comment by MatiasLumio** [comment]
I also lost the capability to use numbers for bankpin as of today, when remapping is also enabled. I was using both of the settings on yesterday fine, but today something has changed and I can no longer use keyboard bank pin and remapping at the same time.

**Comment by Nightfirecat** [comment]
Fixed in #11536

**Comment by graingert** [comment]
@Paradoxis @Pooooky this feature came out in runelite 1.6.13 https://runelite.net/blog/show/2020-05-01-1.6.13-Release/

here's the commit that added it: https://github.com/runelite/runelite/commit/c1fdec9d2ed44302cbc93df4fcc7caba17bdfd9c

https://github.com/runelite/runelite/issues/9033
https://github.com/runelite/runelite/issues/11512
