### ISSUE TITLE
Item overlays draw on top of world map

### ISSUE THREAD

**Issue by DingusPingus** [runelite/runelite#11534]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
if you have runes inside your rune pouch in the bank and you decide to open the map while the bank is already open, those rune values will appear on top of the map. I have tested with the other icons and it seems at first glance to only be associated with the pouch

**To Reproduce**
1. scroll through your bank to where rune pouch is located
2. open map
3. notice values on top of the map

**Expected behavior**
I would expect these be hidden when the map is over

**Screenshots**

![values on top of map](https://user-images.githubusercontent.com/55999153/81504859-db528200-92a8-11ea-821b-6d40b9e8c31c.png)

behind the map my bank is open, and in that same location is my rune pouch with those runes in it

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.14
 - Launcher version: 1.6.0

**Comment by ThePharros** [comment]
I managed to reproduce the issue, seems to happen for any rendered overlay on banked items, such as Item Identification's overlays ![image](https://user-images.githubusercontent.com/18340303/81667764-add51800-9411-11ea-9dbc-c4cbc8b4cbcd.png)

**Comment by Adam-** [comment]
fixed in 34e37dcc575e4f867c4d99a2b5c00ce1bffabdc1
