### ISSUE TITLE
Sanfew prayer restoration formula is wrong

### ISSUE THREAD

**Issue by towelcat** [runelite/runelite#11539]
It appears to be using lvl\*0.25+9, but after testing at a few thresholds I've found it to be lvl\*0.3+4.

Holy wrench adds +0.02 to the lvl mult (so prayer/super restore use 0.27, and sanfew would use 0.32)

Not sure which plugins this affects.

**Comment by Nightfirecat** [comment]
The maximum restoration tables on the [super restore](https://oldschool.runescape.wiki/w/Super_restore#Maximum_restoration) and [sanfew serum](https://oldschool.runescape.wiki/w/Sanfew_serum#Maximum_prayer_restoration) wiki pages are accurate. Whoever fixes this bug, please write tests against the boost amounts shown on these tables.

**Comment by towelcat** [comment]
I'm an idiot and forgot that these potions restore other stats as well. Thankfully the same formulas are used for the other stats.

- Prayer potion: `floor(level * 0.25) + 7`
- Super restore: `floor(level * 0.25) + 8`
- Sanfew serum: `floor(level * 0.3) + 4`

Holy wrench/rotg(i)/prayer cape act as an additive +0.02 to the multiplier for the purposes of prayer restoration.
