### ISSUE TITLE
Chat command proving whether you have Piety, Rigour, and Augury unlocked

### ISSUE THREAD

**Issue by Brianmm94** [runelite/runelite#11544]
One problem that occurs fairly often for clan applications and when joining PvM groups is proving whether someone has the Piety, Rigour, and Augury prayers unlocked. Because even if they have the prayer level requirements, it doesn't mean that they have the prayers unlocked. As far as I'm aware, the only ways to prove this are through their max hit or by them taking a screenshot of their prayer tab with them activated.

So, what I'm suggesting is a command that lists whether you have these prayers unlocked by completing the Knight Waves Training Grounds (Piety), using a Dexterous prayer scroll (Rigour), or using an Arcane prayer scroll (Augury) since your prayer level can already be seen through the hiscores.

If you want, this could also be expanded into a command that lists all permanent non-visible unlocks an account has (if there are any more that come to mind other than these prayers).

**Comment by Nightfirecat** [comment]
Players would just use modified clients to send a faked value.

**Comment by Brianmm94** [comment]
Yeah, I guess part of the question is whether there is any way to do this without the command being modified (and this doesn't necessarily need to be through a command). Because that would definitely be the best scenario. If not, I still think the command would suffice for most situations.

Currently: There is no way to tell.
With command: You can tell unless they modified their client.

**Comment by Brianmm94** [comment]
And I suppose a screenshot doesn't mean it's true either since they might photoshop it, but I still think both of these would at least be good indicators.

**Comment by abextm** [comment]
This is impossible to implement in a way that would not be immediately abused

**Comment by Brianmm94** [comment]
I don't see how this could be "abused". There isn't any way to prove this as it is, so how can a command be any worse than someone just saying "Yeah, I have them unlocked".

**Comment by abextm** [comment]
Because people would think it is an absolute indicator of whether or not they have the thing unlocked, which it is not

**Comment by ThePharros** [comment]
^ Since the command itself can be spoofed, making it no different than the already available options to lie on having them unlocked or not.

**Comment by Brianmm94** [comment]
I suppose that's true. I guess there isn't a way to prove this through a software client and Jagex would need to provide a way to prove this if anything.
