### ISSUE TITLE
GPU Rendering with Stretched Mode + Fixed on macOS

### ISSUE THREAD

**Issue by mahmudzero** [runelite/runelite#11554]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When enabling GPU and Stretched Mode (in RuneLite), with Fixed Mode (in RuneScape) turned on, resizing the client window causes the UI to scale larger than the client window. See attached video for example

**To Reproduce**
1. Turn on 'Fixed Mode' in game
2. Turn on stretched mode in RuneLite
3. Turn on gpu in RuneLite
4. Resize client

**Expected behavior**
To not do this...

**Screenshots**
Attached video zip
<img width="248" alt="image" src="https://user-images.githubusercontent.com/13858161/81620821-c36b2300-93ba-11ea-9b00-aa202bf0ac24.png">
<img width="250" alt="image" src="https://user-images.githubusercontent.com/13858161/81620844-cb2ac780-93ba-11ea-9144-a0ebc3876e92.png">
[May-11-2020 19-01-35.mp4.zip](https://github.com/runelite/runelite/files/4612521/May-11-2020.19-01-35.mp4.zip)

**Environment (please complete the following information):**
 - OS: macOS
 - 2019 16inch Macbook Pro
 - 2.6ghz 6-core i7
 - AMD Radeon Pro 5300M 4GB // Intel UHD Graphics 630 1536MB
 - --------------------------------------------------------------------
 - 2019 15inch Macbook Pro
 - 2.6ghz 6-core i9
 - AMD Radeon Pro

**Comment by mahmudzero** [comment]
Adam-, feel free to let me know if you need more info/need me to debug stuff on my own to help!

I am willing and able, with some guidance. I am not familiar with the code base lol.

**Comment by nick-woodward** [comment]
I ended up running into this issue as well upon full screening the application.

Here's a workaround I discovered while playing around with the settings.

1. Log out to the main menu (_mine has had a tendency to crash if I'm logged in_)
2. Toggle the GPU plugin off and on again
3. The game should now be rendered correctly.

**Comment by mahmudzero** [comment]
> I ended up running into this issue as well upon full screening the application.
> 
> Here's a workaround I discovered while playing around with the settings.
> 
> 1. Log out to the main menu (_mine has had a tendency to crash if I'm logged in_)
> 2. Toggle the GPU plugin off and on again
> 3. The game should now be rendered correctly.

@nick-woodward, I've been playing in scalable (or whatever its called, the one thats not fixed in the runescape settings) for now, as that mode doesnt have an issue with scaled + gpu

**Comment by simonosrs** [comment]
https://imgur.com/L1VCsbU

smh

**Comment by simonosrs** [comment]
nah come one what is this? https://imgur.com/XRXaVF9

**Comment by mahmudzero** [comment]
> nah come one what is this? https://imgur.com/XRXaVF9

Temporary fix like nick-woodward mentioned is to toggle GPU on and off, @simonosrs

**Comment by davidscottconrad** [comment]
I'm a Jr. Web Dev, but I was having this issue as well. Can I take a crack at fixing it? Any ideas on where to start? @Adam- @alexanderhenne

**Comment by Adam-** [comment]
fixed in bb43d232bb594c6e062e3342fa7db1b53f594c11
