### ISSUE TITLE
Screenshot plugin includes windows on top of Runelite when Runelite is in background

### ISSUE THREAD

**Issue by cox34** [runelite/runelite#11559]
Runelite 1.6.14, launcher 2.1.0
Arch Linux 5.6.11-arch1-1
nvidia Driver Version: 440.82
using AppImage
however, issue also present when using .jar and java-13-openjdk set to default
Arch is using nvidia driver package and KDE plasma desktop environment

issue only occurs when GPU plugin is enabled. 

screenshot plugin includes windows on top of runelite when runelite is not active window/in the background. this could mean a part of or all of runelite is covered by another window in the screenshot. 

understandable if the issue is too specific to my machine. any suggestions welcome. 

example, i died to corp and the plugin took a screenshot of the death: 
![Death 2020-05-12_19-55-15](https://user-images.githubusercontent.com/17260496/81678430-1a1b4000-9441-11ea-85b2-130956948e4a.jpg)

**Comment by cox34** [comment]
nothing new to add, but problem still exists on 

Runelite 1.6.26, launcher 2.2.0
Arch Linux 5.8.10-arch1-1
nvidia Driver Version: 455.23.04

**Comment by Adam-** [comment]
Reopen if you can reproduce this on RuneLite from https://runelite.net
