### ISSUE TITLE
Runelite converted to unity or C#

### ISSUE THREAD

**Issue by juglia02** [runelite/runelite#11553]
Can we have Runelite converted to Unity or C#.... it is superior according to this video?

Is that true or clickbait? 

https://www.youtube.com/watch?v=KczXejPoOFc

**Comment by Nightfirecat** [comment]
We are not porting RuneLite to another language.

**Comment by juglia02** [comment]
> We are not porting RuneLite to another language.

How are you going to compete? I know you're planning Vulkan when Adam decides to learn it but I doubt that will be enough.

Is the reason for not porting to another language because your developers don't know more advanced programming languages?

Please consider this. it's make or break time..............

**Comment by stoddy15** [comment]
Vulkan will be a significant upgrade vs OpenGL. Runelite is already the better client.

**Comment by stoddy15** [comment]
Vulkan will be a significant upgrade vs OpenGL. Runelite is already the better client.

The developers at runelite are the best. the client is the best.

the client you showed is clunky af and will not be adopted.

**Comment by Nightfirecat** [comment]
We are well aware of the other existing clients, and of those which don't exist and are still in development--let's be honest, the client you posted a video of does not yet exist and is still under heavy development.

Our choice of language is plenty efficient, and was with the aim of being accessible to new contributors. If you have knowledge of another language which would offer significant performance benefits while maintaining the qualities I mentioned, please let us know. Vague statements like "more advanced programming languages" are at best uninformed and at worst outright wrong; in both cases, these statements are not constructive. Furthermore porting any project to a new programming language is a huge endeavor, of similar difficulty to writing the project anew from scratch. It is not appropriate to ask us to redo all the work that's already been done for the sole goal of being written in some other language.

**Comment by juglia02** [comment]
Once it finishes development how are you going to compete @Nightfirecat ?????

They are releasing 2 clients (Ultra and enhanced) which will take away from your active users. Vulkan WILL NOT CUT IT.

Jordan you need to be smart.
