### ISSUE TITLE
Gorilla emoji for the "Emojis" plugin

### ISSUE THREAD

**Issue by Heksaaniq** [runelite/runelite#11561]
This is a nice emoji that me and my friends use a lot in discord for example. It looks funny and cute and I dont really see any reason it wouldn't be a good addition to the plugin!

Add the discord :gorilla: emoji to the emoji plugin. The emoji "trigger" could be something like ":l", ":]"  or "._."

I havent really thought of any alternative solutions, there really isn't any. The gorilla emoji is the way to go!

This is an example of what the gorilla would look like
![runelitegorillaexample](https://user-images.githubusercontent.com/65235995/81701480-bc9fe700-9472-11ea-8b18-ebb4eb30bd35.png)

**Comment by dekvall** [comment]
Emoji: ![image](https://user-images.githubusercontent.com/25151927/81702524-ae9a9800-946b-11ea-80fd-93e696e6fb56.png)

**Comment by makingcomment** [comment]
The triggers you suggested are completely unrelated to the gorilla emoji. They're also common (non-gorilla) emoticons, which means they'd result in people sending gorillas they had no intention of sending.

**Comment by Heksaaniq** [comment]
True. I know they aren't the best triggers possible but they aren't completely unrelated either. The gorilla face for me at least looks like some variation of those. Alternative triggers could be something like "8~8" as if the 8's were the gorilla's large hands even though its just the face in the emoji.

**Comment by juglia02** [comment]
This could be used for racist slurs. don't support
