### ISSUE TITLE
Swap dream on Dominic onion at NMZ

### ISSUE THREAD

**Issue by Kmtfwtm** [runelite/runelite#11560]
These would be awesome additions to the menu swapper!

**Comment by melkypie** [comment]
Left click guzzle is a duplicate of #1860.

**Comment by Broooklyn** [comment]
Exists within Menu Entry Swapper Extended on the Plugin Hub under "Minigames"

**Comment by Kmtfwtm** [comment]
> Exists within Menu Swapper Extended on the Plugin Hub under "Minigames"

It doesn't work

**Comment by Broooklyn** [comment]
@Kmtfwtm It should be fixed now

**Comment by Kmtfwtm** [comment]
@Broooklyn Very nice thank you it works (: 
Could you add left click guzzle on rock cake? ;o

**Comment by Broooklyn** [comment]
@Kmtfwtm Don't thank me, thank raiyni—He fixed it, I just pointed it out to him.  

You can find left click guzzle for rock cake in the `NMZ Utilities` plugin on the hub.

**Comment by Kmtfwtm** [comment]
@Broooklyn Sweeet thank you! Idk why no1 mentioned that before haha I just got told it was a duplicate request.
