### ISSUE TITLE
Login screen drop down menu

### ISSUE THREAD

**Issue by Tatertots8008** [runelite/runelite#11576]
a lot of players have more that one account me included. it would be nice to have a drop down menu for the accounts users name to pick from instead of having to type a new user every time you open another client

**Comment by Broooklyn** [comment]
"Profiles" on the Plugin Hub does what you are describing.

**Comment by deathbeam** [comment]
Implemented in plugin hub

**Comment by Tatertots8008** [comment]
ya, im not seeing anything like that in my plugin options, im talking about the user name for the runescape account https://i.gyazo.com/6675e544ebd2113171d06709cbe28df6.png if that wasn't clear

**Comment by melkypie** [comment]
There is a plugin-hub which contains plugins maintained by people. Read more about it here https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub
