### ISSUE TITLE
1 2 and 3 key do not work 

### ISSUE THREAD

**Issue by Dizasterr** [runelite/runelite#11579]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

This is a legitimate problem I am having and not a troll, I've  tried to look online and see if anyone else was having this problem and couldn't find anything. 

**Describe the bug**
My 1 2 and 3 key do not work on runelite but when I press shift the ! @ and # work in game, The only keys that do not work are 1 2 and 3. 

**To Reproduce**
I press my 1 2 or 3 key and they do not work but if I press shift I can get ! @ and # to work, Numpad keys all work too. 

**Expected behavior**
I expected a 1 2 and 3 to appear when I typed them
**Screenshots**
Can't really take a pic of me doing this. 

**Environment (please complete the following information):**
 - OS: Windows 10 64 bit 
 - RuneLite version: 1.6.14
 - Launcher version:2.1.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment]
Try disabling any plugins you have enabled which may remap your keys, such as the Plugin Hub's zulrah rotations plugin and see if this is still an issue.

**Comment by Dizasterr** [comment]
that fixed my problem, I feel like an idiot, Thank you lol.
