### ISSUE TITLE
Bank, Bank Tags and Item Identification plugins not working after today's game update

### ISSUE THREAD

**Issue by iawhd** [runelite/runelite#11589]
**Describe the bug**
1. Bank tags are not shown on the left hand side of the bank interface
2. Bank Value is not shown on the top bar
3. The deposit worn items button is missing its icon
4. Item Identification labels are being shown on the tabs in the bank 

All bugs visible in below screenshot:

![image](https://user-images.githubusercontent.com/29826207/81937154-25aa6a80-95eb-11ea-99b5-d158041e77b9.png)

**To Reproduce**
1. Open Bank

**Comment by raiyni** [comment]
Duplciate of #11585
