### ISSUE TITLE
Key Remapping issues

### ISSUE THREAD

**Issue by jadevdw** [runelite/runelite#11587]
**Describe the bug**
I have remapped my F Keys to my number keys but they are not working and instead they are just typing in the numbers i push, i did not have this problem before the update that just went live so i was a bit confused. Also have problems with WASD (Camera Remapped)

**To Reproduce**
Log into the game and turn on key remapping and adjust F keys to numbers and try for yourself, ive tried logging & restarting client but no successs

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.14
 - Launcher version: Unkown

**Comment by Hydrox6** [comment]
Duplicate of #11585
