### ISSUE TITLE
Screenshot Specific Area

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1158]
Not sure of how this would work exactly but able to select an area to screenshot instead of the entire client

Probably would be pressing a key like f9 or something (not sure what would be a good key) and be able to select an area

Also saw in another issue was to be able to only take a pic of the game itself. None of the client stuff

Also I noticed when you click on a screenshot (after its already been taken it hardly zooms in at all) so if you are decently zoomed out at all you cant see a whole lot

**Comment by devLotto** [comment]
I think you should use an external tool such as ShareX to screenshot a region. The original objective of the plugin was to take screenshots automatically when certain events happen ingame.

I think there's already an option in the plugin's configuration to only screenshot the game.

The zoomed out issue seems to be related to your way of viewing screenshots, as in what program you're using?

**Comment by Stickaplex** [comment]
for the zoomed out bit i just have it upload to imgur. took the screenshot using the apps function

**Comment by ShaunDreclin** [comment]
+1 For ShareX, would highly recommend.

**Comment by Stickaplex** [comment]
actually have that. was just using the clients screenshot thing tho due to it being riight there

**Comment by deathbeam** [comment]
You should use external tool, this feature is not really related to runescape or runelite at all.
