### ISSUE TITLE
clues: ZCZL cipher clue needs updating

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#11588]
In today's release, Jagex updated the name of Adam (the ironman tutor) to just `Iron Man tutor`. The wiki has the clue listed now as `HQNM LZM STSNQ` on the cipher page, but proof of this would be very much appreciated.

**Comment by IMGokhan** [comment]
![image](https://user-images.githubusercontent.com/38979025/81954008-a035b300-9608-11ea-9690-1a7cb6148647.png)

It is 'Iron man tutor' in Lumbridge.
