### ISSUE TITLE
Camera plugin inner zoom does not work

### ISSUE THREAD

**Issue by Hallako** [runelite/runelite#11591]
Client does not zoom close as before. This can be seen at making oak doors or just hovering on the zoom slider in oldschool settings that the zoom goes to 896/1004.

Enable camera plugin
Tick the "Expand inner zoom limit"
Zoom client

**Expected behavior**
Camera to zoom little further in.

**Environment
Windows 10 on 1.6.14. observed after oldschool update on 14.5.2020.

**Comment by melkypie** [comment]
Restart your client. The client will update.

**Comment by Hallako** [comment]
Thanks. Did few restarts earlier, maybe the update was little slow. Sorry for the noise.
