### ISSUE TITLE
ground items not showing or changing colors on certain value items

### ISSUE THREAD

**Issue by walloftime39** [runelite/runelite#11605]
my ground items isn't working properly as when i get valuable items it doesn't change colors and won't show the values of certain items when on the ground. the ground items was working a couple a days ago.

**Comment by Nightfirecat** [comment]
We've made an update to it with today's release. What are your plugin settings?

**Comment by walloftime39** [comment]
https://gyazo.com/79779a0de304f51d59c82dc1c290d534

**Comment by walloftime39** [comment]
> 
> 
> We've made an update to it with today's release. What are your plugin settings?



> 
> 
> We've made an update to it with today's release. What are your plugin settings?

https://gyazo.com/79779a0de304f51d59c82dc1c290d534

**Comment by Nightfirecat** [comment]
Can you also upload your client logs?

**Comment by walloftime39** [comment]
where do i find my client logs?

**Comment by Nightfirecat** [comment]
Instructions are at the top of this page: https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by walloftime39** [comment]
tried finding my log but for whatever reason i can't find them.

**Comment by walloftime39** [comment]
here a quick clip of the issue i am having though. i have my hide<value set at 3k.https://gyazo.com/19f7a362b17c1dafc9605a6fe35b4bc9

**Comment by Nightfirecat** [comment]
You should be able to open your logs folder by hitting <kbd>Win</kbd> + <kbd>R</kbd> to bring up the "Run" dialog, and pasting `%userprofile%\.runelite\logs` into it. I suspect the issue is that your client isn't able to reach our item prices API.

**Comment by walloftime39** [comment]
https://gyazo.com/a2b637370427c0f60fe36f04105f469a

**Comment by walloftime39** [comment]
dropping higher value items is working but for whatever reason when i try and drop stuff under 20k but over 3k they dont show up.

**Comment by walloftime39** [comment]
if you need me to gointo a specific log lmk

**Comment by Nightfirecat** [comment]
Please upload the one named `client`

**Comment by walloftime39** [comment]
[client.log](https://github.com/runelite/runelite/files/4632619/client.log)

**Comment by Nightfirecat** [comment]
It looks like you have "Show highlighted items only" checked. I believe that's affecting what is shown

**Comment by walloftime39** [comment]
yes that was the issue thank you for your help!
