### ISSUE TITLE
Highlight name/words in chat

### ISSUE THREAD

**Issue by Tekonaz** [runelite/runelite#1161]
Request:
Would love to have a option to highlight certain words or just even your RSN in chat. Not the whole line just your name, for example if you get a drop in raids.
![](https://i.imgur.com/orvhhxm.png)

**Comment by SoyChai** [comment]
Sounds good. I like the idea of a custom whitelist, for highlighting any of your nicknames and/or favourite topics. We could deploy notifications for this too.

**Comment by SomeZer0** [comment]
Chat highlight with notifications would be nice.

**Comment by Kamielvf** [comment]
My plan was to integrate this with #995 when expanding its functionality to the chat in general.

**Comment by deathbeam** [comment]
This was already added.
