### ISSUE TITLE
Update clue, tl, lms and bh tooltips in Hiscore tab

### ISSUE THREAD

**Issue by ripsey** [runelite/runelite#11618]
**Is your feature request related to a problem? Please describe.**
I am not sure which rank is showing.

**Describe the solution you'd like**
The tooltip of skills says which skill is being shown, I'd like this the same way in the clue, tl, lms, bounty scores. Currently it only says what rank you are but not which rank.

**Additional context**
![image](https://user-images.githubusercontent.com/7533915/82104441-3bb54980-9717-11ea-9f53-7a053381f2ad.png)

**Comment by Nightfirecat** [comment]
Duplicate of #6368
