### ISSUE TITLE
Automatically highlight - bank key (ground items) (dmm)

### ISSUE THREAD

**Issue by nlruk** [runelite/runelite#11617]
Can you automatically highlight the bank key on the ground when a player dies in dmm?

it's super important in this game mode.

thanks

**Comment by dekvall** [comment]
Add it to the highlight list in `Ground Items`

**Comment by nlruk** [comment]
> Add it to the highlight list in `Ground Items`

I just thought it would be beneficial if you could do that automatically for us. it would save every DMM player to add it manually when it's universally important in that game mode. Thanks anyways.
