### ISSUE TITLE
Togglable left click option for teleport items

### ISSUE THREAD

**Issue by David-Igou** [runelite/runelite#11627]
**Is your feature request related to a problem? Please describe.**
Accidental left clicks a one-click teleport can be frustrating. For players willing to mitigate that risk in favour of the extra time required to right click it, it would be nice

**Describe the solution you'd like**
Players should be able to swap use/teleport (tablets, ectophail, seed pod) for left click options if they are willing. Similar to how the ancient tablets work

**Additional context**

**Comment by Nightfirecat** [comment]
@raiyni This may be a good candidate for your [Menu Swapper Extended](https://github.com/raiyni/menu-swapper-extended) plugin?

**Comment by raiyni** [comment]
I've been discussing it with people, yes

**Comment by Nightfirecat** [comment]
8944eb9be6d62ec8384e29484dab14c4c2858d9d was added to master, which sufficiently covers this use case.
