### ISSUE TITLE
Quick-hop region:  select multiple

### ISSUE THREAD

**Issue by orlp** [runelite/runelite#11625]
When using the "Quick-hop region" feature you can choose from USA, UK, Germany and Australia.

For me the UK and Germany servers are equally preferable, but significantly better than USA or Australia. For other players I can see similar scenarios occurring.

I think it would be a nice improvement if we could select for each region separately whether or not to include that region in our quick-hop target world list. A suggested solution would be to replace the drop down menu with a check box (default checked) for each region separately.

**Comment by LlemonDuck** [comment]
This can be done by Shift-clicking the options in the "Quick-hop region" config item

![image](https://user-images.githubusercontent.com/1868974/179183286-dd599442-825e-44b6-ab86-5627d2095840.png)
