### ISSUE TITLE
Chat history plugin: Line breaks in private messages aren't persisted

### ISSUE THREAD

**Issue by SoyChai** [runelite/runelite#1162]
I don't condone the advertising in this screenshot :) but it's what alerted me to this bug.

The first four messages each spilled over to a second line before I hopped worlds. After the plugin restores them, they lose their line breaks and become truncated by the chatbox width.

![image](https://user-images.githubusercontent.com/37604308/38026991-f0357f96-32d9-11e8-837c-53ca25904b36.png)

**Comment by ShaunDreclin** [comment]
banned for advertising

**Comment by Adam-** [comment]
fixed in e71b18b02b124bff69cc347238551d2e0d3bf29b
