### ISSUE TITLE
Collection Log for Skilling

### ISSUE THREAD

**Issue by syberbagel** [runelite/runelite#11629]
**Is your feature request related to a problem? Please describe.**
When skilling, there is no tracker to see what resources I have collected during the session.

**Describe the solution you'd like**
A tracker similar to the loot tracker that will show a log of whatever you have collected during that skilling session separated by skill being used

**Describe alternatives you've considered**
There are no alternatives currently.

**Comment by Nightfirecat** [comment]
Duplicate of #7177
