### ISSUE TITLE
Runelite resolution issue

### ISSUE THREAD

**Issue by legitstitch** [runelite/runelite#11631]
I've been having issues with my runelite window's resolution. When I click to expand the size of the window to full screen, it doesn't cover my entire screen. Also the game is in an even smaller box in the window (shown in screenshot). Also, the black bars surrounding the game screen will allow the green runelite click-boxes to show through and duplicate. (also shown)
![RL Prob](https://user-images.githubusercontent.com/40655734/82136601-cefc8680-97cc-11ea-95ad-292c5f7693a8.PNG)

**Comment by raiyni** [comment]
Update your launcher to the newest version.

**Comment by legitstitch** [comment]
how do i do that? ive redownloaded runelite many times today, wouldnt it automatically download the newest version?
