### ISSUE TITLE
Unable to set negative config values at plugins

### ISSUE THREAD

**Issue by paulocsanz** [runelite/runelite#11640]
**Describe the bug**
If I set a @ConfigItem method returning int to return a negative number the config tab truncates to 0. It would be very good to have negative values supported.

**To Reproduce**
Add to Config based class.

```
    @ConfigItem(
            keyName = "negativeConfig",
            name = "Config that returns a negative number",
            description = "Example"
            position = 1
    )
    default int negativeConfig() { return -1; }
```

**Expected behavior**
To appear -1 at the config panel and to be able to change to another negative number

**Comment by raiyni** [comment]
Add a `@Range` config to your config item.
