### ISSUE TITLE
Sidebar overlap issues

### ISSUE THREAD

**Issue by AdamMartell** [runelite/runelite#11644]
Visual issues with sidebar(loot tracker, hi-scores, etc.). overlapping and artifacting.

**To Reproduce**
1.  Use sidebar

Screenshots

![image](https://user-images.githubusercontent.com/14206823/82245420-8a760580-9908-11ea-9467-a7add192953e.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.15
 - Launcher version: 2.1.0

**Additional context**
This happens even when hardware acceleration is disabled

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Nightfirecat** [comment]
Please join our `#support` channel on discord for support on this matter.

**Comment by Alexsuperfly** [comment]
join us on [discord](https://runelite.net/discord) if you cant get that to work, since it is the better place to field support questions such as this
