### ISSUE TITLE
Idle notifications no longer bring focus to client

### ISSUE THREAD

**Issue by cwhaley17** [runelite/runelite#11642]
Last I used the client (5/14/2020), when AFK fishing/mining and an idle notification would pop, the client would then get re-focused. Currently, when going idle while AFK fishing/mining I only get the popup notification if I am on a different app (like Chrome). 

**To Reproduce**
1. Open Runelite
2. Make sure Idle Notifications are turned on
3. Go to Fishing Guild or MLM and begin doing the activity
4. Once Idle, receive notification and realize that runelite does not come back into focus anymore.

**Expected behavior**
When going Idle and receiving the notification, expected behavior is to bring RL back into focus.

**Environment (please complete the following information):**
 - OS: Mac Sierra 10.12.6
 - RuneLite version: 2.1.1

**Comment by Broooklyn** [comment]
The setting was reset in the most recent update. Go to `Runelite` in settings and change `Request focus on notification`
