### ISSUE TITLE
Add support for OpenGL

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1165]
OSBuddy Pro has support for using OpenGL. It makes textures look nicer and when pickpocketing ardy knights, you won't have the issue that your left click pickpocket sometimes doesn't register. This happens because the texture is not loaded on that frame or something. I have no idea how much work this would be to implement and stuff, but I thought I'd throw the issue out there.

**Comment by ShaunDreclin** [comment]
This would be a lot of work and also not worth doing right now because hardware rendering is likely coming in vanilla sometime after mobile launches.

**Comment by deathbeam** [comment]
Yeah we are not doing something similar like OSB did with OpenGL, it is not even worth when hardware renderer is coming anyway.

**Comment by Tylemagne** [comment]
Can anyone find an official statement from Jagex regarding an official PC version of this?

**Comment by devLotto** [comment]
https://twitter.com/JagexDark/status/868439744484696066 for macOS

There's reference to a Windows library in the mobile beta code: 

![](https://i.imgur.com/NhVcpNm.png)

They'll probably eventually release it for desktop, yes

**Comment by ShaunDreclin** [comment]
👀

**Comment by deathbeam** [comment]
This was implemented in <https://github.com/runelite/runelite/commit/3f5e2733495cd53c7881ea8579fa0e336ad72b8a>
