### ISSUE TITLE
Area Reporting

### ISSUE THREAD

**Issue by kgtheg** [runelite/runelite#11664]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot report all bots due to it being time consuming. 

**Describe the solution you'd like**
A plugin to scan the area for bots that can easily help you left click and report them rather than right clicking on them individually. 

**Describe alternatives you've considered**
N/A

**Comment by abextm** [comment]
this is obviously botting

**Comment by Hydrox6** [comment]
Also going to mention that this would likely come under the following line from the [Jagex Statemet](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1):
> Adds additional menu entries which cause actions to be sent to the server
