### ISSUE TITLE
Ground Items Plugin Issue

### ISSUE THREAD

**Issue by Armrdbacon21** [runelite/runelite#11662]
Every time I close the client and reopen it, a few items are categorized as "Hidden Items" and bypass the settings. I will delete them from the "Hidden Items" category, but as soon as I reopen the client, they appear in the category again.

Thanks!

**Comment by Armrdbacon21** [comment]
I am looking at it, and it seems that when I click Reset at the bottom of the plugin, that is the base setting for this plugin. Any idea how to permanently change that? Or make it so that it doesn't reset every time I close the client?

**Comment by Nightfirecat** [comment]
This is an issue tracker for bug reports and feature requests. [You can get general client support in the `#support` channel in our Discord server.](https://runelite.net/discord)
