### ISSUE TITLE
Translator Plugin

### ISSUE THREAD

**Issue by kgtheg** [runelite/runelite#11663]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when someone chats with me in a different language that I cannot understand. 

**Describe the solution you'd like**
Open for whatever. 

**Describe alternatives you've considered**
Sometimes it's hard to copy the text in Google since there are wierd character letters. 

**Additional context**
A side plugin maybe?

**Comment by Nightfirecat** [comment]
Duplicate of #10591
