### ISSUE TITLE
cross-save

### ISSUE THREAD

**Issue by PerishBtw** [runelite/runelite#11675]
Unsure if you can do this since there's no "runelite" login.
But I thought it might be nice if Runelite could remember your settings and preferences from computer to  computer. I just spent a good hour transferring all my preferences and stuff manually to my new tablet and it was quite the pain.
But it might also be neat if it remembered via your runescape account? For instance, I enable and disable settings based on if I'm on my alt or my main to make my life easier.  That way I'm not constantly enabling/disabling stuff every time I re-open Runelite.
Hope that all made sense.

**Comment by raiyni** [comment]
Click the the green door and sign in with a google account. Then use the upload settings button in the info panel.
