### ISSUE TITLE
Lost a ton of saved tags + plugins, boss hiscores wrong after having to redownload

### ISSUE THREAD

**Issue by momcookies** [runelite/runelite#11684]
I couldn't start runelite today, even after flushing dns. So I decided to simply redownload the app. My loot tracker is accurate 

**Expected behavior**
Wouldn't expect this to happen, but I think my kc's have been reset to what they were weeks ago. My bank tag order is messed up, and many of the recent ones are gone. Additionally, I lost a couple of the external plugins I downloaded about a day ago, which I suppose is to be expected when redownloading the client? I loaded my local settings and tried logging in and out to no avail.

**Screenshots**
![image](https://user-images.githubusercontent.com/65835399/82742635-521a6100-9d26-11ea-955a-205d19cc7838.png)

**Environment (please complete the following information):**
 - OS: Windows (64 bit)
 - RuneLite version: 1.6.16
 - Launcher version: 2.1.0

**Comment by momcookies** [comment]
Also, tried restarting runelite and just lost the plugins again for some reason, along with my whole loot tracker being reset.

**Comment by JZomerlei** [comment]
!kc command is using local kill count and the loot track resets when you’re not logged in with a gmail to enable cloud syncing. 

You are likely logged out and your old kill count you used to have is the one showing up. Your bank tags are also likely still saved but only on that cloud profile. If neither is the case join the discord and talk in the support channel.

**Comment by Hydrox6** [comment]
Closing since this is very very stale

For further questions of support, please join the [Discord](https://runelite.net/discord)
