### ISSUE TITLE
OpenGL Issue

### ISSUE THREAD

**Issue by sginley** [runelite/runelite#11694]
I built a new PC a few days ago. Whenever I turn on the GPU plugin it causes my client to crash, and give me an OpenGL ES Error: Can't find the Intel graphics. I had to take the PC to a repair shop, as the components weren't working together out of the box. I tried booting up runelite when i got home and wasnt able to open the client; I would get the OpenGL error every time. The only way to get runelite to boot up was by turning the GPU plugin off. The PC repair guy installed Windows 10 Pro N. My processor is a 9700k, and my GPU is an RTX 2070 super. Both the GPU and Intel graphics show up under device manager under display adapters. I am on Runelite version 1.6.16 and Launcher version 2.1.0
![OpenGL error](https://user-images.githubusercontent.com/65874854/82768384-abed5a80-9dfc-11ea-8852-cf544d951545.png)
![Display adapters](https://user-images.githubusercontent.com/65874854/82768385-b14aa500-9dfc-11ea-80ea-89901c1e5a10.png)

**Comment by Nightfirecat** [comment]
Please post your `client.log` file--directions on finding it can be found at the top of this wiki: https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by sginley** [comment]
![RL Logs](https://user-images.githubusercontent.com/65874854/82769595-49e42380-9e03-11ea-9451-606ddc1754d4.png)

**Comment by sginley** [comment]
[client.log](https://github.com/runelite/runelite/files/4674779/client.log)

**Comment by Nightfirecat** [comment]
Ah, could you also upload one of the `jvm_crash_pid` files? Whichever one is most recent, date-wise

**Comment by sginley** [comment]
This one is from about 3.5 hours ago
[jvm_crash_pid_5024.log](https://github.com/runelite/runelite/files/4675227/jvm_crash_pid_5024.log)

**Comment by sginley** [comment]
I fixed this issue. I'm not sure what fixed it but i did 2 different things. First i completely uninstalled runelite from my m.2 ssd. I also had runelite instaleld on my old ssd, so i competeely took runelite, and everything related to jagex off my old ssd. Then i reinstalled runeltie on my new ssd, and the issue was gone. I think the issue may have been that I had runlelite installed on 2 different ssds that were both plugged into my motherboard. Anyways, one of these 2 steps fixed the problem, as the gpu plugin works fine now. Thanks for your help Nightfire.
