### ISSUE TITLE
runelite GUI ghosting error

### ISSUE THREAD

**Issue by KjellTexas** [runelite/runelite#11698]
This error occurs intermittently after starting runelite.
When sliding the mousepointer over the GUI tabs on the right side, the pictures disappear and/or duplicates "ghosting".

I will attach some screenshots of the error to see if anyone has the same issue.

I am running Windows 10 Pro 64-Bit
 - RuneLite version: 1.6.16
 - Launcher version: 2.1.3

![runelite error2](https://user-images.githubusercontent.com/65910270/82825964-828c0780-9eac-11ea-8a4b-70ed3360d8c2.png)
![runelite error1](https://user-images.githubusercontent.com/65910270/82825966-83249e00-9eac-11ea-995f-02752dff1f07.png)

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Hydrox6** [comment]
runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by KjellTexas** [comment]
> https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

Hi, i tried all the "tricks" in the link for Windows but i keep getting the same issues.
Any more ideas?

**Comment by Alexsuperfly** [comment]
join us on [discord](https://runelite.net/discord)
