### ISSUE TITLE
Southernmost orange salamander spot in north of desert doesn't turn green on catch

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1169]
All others do, just the southernmost spot not.
https://imgur.com/SE7RIfB

**Comment by deathbeam** [comment]
Also swamp saladamnder southern and western trap is not working properly.

![swamp-sallys](https://i.imgur.com/MnvxhT4.png)

**Comment by Fryslan** [comment]
This is an issue for black salamanders aswell.

**Comment by Adam-** [comment]
Fixed in #1577
