### ISSUE TITLE
Wrong skybox color in wilderness godwars dungeon

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#11692]
Unlike the rest of the wilderness, and most cave areas, the wilderness godwars dungeon shows a light blue color as though the player was above ground. This should be changed to a similar color to the wilderness (dark grey) or other cave areas (usually also dark grey).

**Comment by abextm** [comment]
its probably just snow colored

**Comment by abextm** [comment]
Yeah, this shares the same color as every other snowy area, with the notable exception of gwd proper, which has no color. So this seems working as intended™ to me
