### ISSUE TITLE
Add a download tracker for Plugin Hub

### ISSUE THREAD

**Issue by ffalor** [runelite/runelite#11701]
## Suggestion
I think it would be beneficial to keep track of the number of downloads a plugin receives. Most sites that distribute community made modules/plugins etc have this functionality [Puppet](https://forge.puppet.com), [Docker ](https://hub.docker.com/) are two examples.

## Reason
This could help users find popular plugins and make decisions between two similiar plugins.

This would also help plugin developers to gauge interest.

I'm not sure if this is the right place to open the issue, but currently the plugin hub repo has issues disabled.

**Comment by abextm** [comment]
Duplicate #10494
