### ISSUE TITLE
Virtual Machine support

### ISSUE THREAD

**Issue by j278787** [runelite/runelite#11705]
Hi I have been playing RuneScape with Runelite and haven't really had any issues that are for the front. That was until I started playing Runelite in windows sandbox Virtual Machine. The only that I have so far found is that the GPU scaling and altering do not work. I have yet to try any other plug-ins because I haven't played much in the VM with Runelite but I was just making this issue aware for the purpose of later fixes.

**Comment by ChristiaanDev** [comment]
Sounds much more like a Virtual Machine driver problem than a RuneLite problem.
