### ISSUE TITLE
Repeated Chat Notification trigger on world hop

### ISSUE THREAD

**Issue by Broooklyn** [runelite/runelite#11706]
**Describe the bug**
With `Chat Notifications` and `Chat History`: `Retain Chat History` enabled, if a notification word is sent to chat, the chat notification is triggered every time you hop worlds. This only occurs when the trigger for the chat notification is one word.

**To Reproduce**
1. Enable `Retain Chat History` within `Chat History`
2. Trigger a single word `Chat Notification`.
3. Hop worlds or log out.
4. On login the chat notification triggers again.

**Expected behavior**
I would expect to not be spammed by the same chat notification every time I hop worlds, while still being able to see chat history.

**Screenshots**
Original trigger:
<img width="282" alt="Screen Shot 2020-05-26 at 7 54 47 PM" src="https://user-images.githubusercontent.com/54762282/82961279-dc62ff00-9f8a-11ea-9cd7-8d2f615c5629.png">

After world hop:
<img width="245" alt="Screen Shot 2020-05-26 at 7 55 04 PM" src="https://user-images.githubusercontent.com/54762282/82961291-e258e000-9f8a-11ea-8cad-38ef81525fb5.png">

**Environment:**
 - OS: MacOS
 - RuneLite version: 1.6.16
 - Launcher version: 2.1.2

**Comment by Adam-** [comment]
fixed in e71b18b02b124bff69cc347238551d2e0d3bf29b
