### ISSUE TITLE
Bank fillers for Tag Tabs

### ISSUE THREAD

**Issue by aguscerdo** [runelite/runelite#11709]
Tag tabs only hold items placed. Sometimes I want items to be on the far-left side for less mouse travel (e.g. gold ore for smithing). 

**Describe the solution you'd like**
Add tag fillers to be able to reposition items.

**Describe alternatives you've considered**
When adding a tag to existing fillers, do not add all fillers, but only the ones for the added.

**Additional context**
N/A

**Comment by aguscerdo** [comment]
Correction: items on the far-right, close to inventory

**Comment by raiyni** [comment]
As mentioned in #6795 we have had prior stances in not wanting to manage the layout of the bank other than removing the tab separators. 

You can use bank fillers in a normal tab.
