### ISSUE TITLE
Proxy configuration plugin

### ISSUE THREAD

**Issue by h0dgep0dge** [runelite/runelite#11704]
I recently had need to tunnel runescape through a firewall, and in my research I learned that Java has capability to transparently tunnel network connections through a SOCKS proxy built right in. This works great, but the drawback is that it has to be configured from the command-line. 

According to the documentation, the proxy can be configured with a simple call to `System.setProperty`. Knowing this, I've been considering implementing a plugin to set this option, allowing lay-people to easily use a proxy, even such as an http proxy at a school, or any number of other use-cases.

However, while I have contributed to the runelite code-base previously, i'm not intimately familiar with the ins and outs of Java permissions and security and what-not, so I don't even know if it's possible to call `System.setProperty` from a plugin. Is anyone more familiar with the runelite architecture able to let me know if this is even possible?

For anyone who is interested in using the solution I'm currently using, the command line is `java -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080 -jar runelite.jar`

**Comment by Hydrox6** [comment]
A Proxy plugin would be pretty useless, since to get to the point to be able to configure it, you'll have needed to connect to both RL and OSRS servers.

Also, I'm pretty sure you can set the `JAVA_OPTS` env var, and you can always use a batch/shell script to run the client with the settings you want anyway.

Also probably a duplicate of #8129

**Comment by h0dgep0dge** [comment]
I don't believe it is a duplicate of that issue exactly, but if you think it's off-topic I'm happy to take it somewhere else to work out if it's possible

**Comment by Adam-** [comment]
I think the solution of passing `socksProxyHost` etc to the VM the launcher runs in is certainly the best/most robust. Anything we could do would be post-VM start at the very least, and would have to be in the launcher if anything as the client runs very late in startup.

**Comment by rumstead** [comment]
> Also, I'm pretty sure you can set the `JAVA_OPTS` env var, and you can always use a batch/shell script to run the client with the settings you want anyway.

https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts

**Comment by naturedamends** [comment]
2026-02-13 03:28:03 GMT [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool.config.runescape.com" (Connect timed out)
2026-02-13 03:28:23 GMT [main] ERROR n.r.client.RuntimeConfigLoader - error fetching runtime config
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: Connect timed out
	at java.base/java.util.concurrent.CompletableFuture.wrapInExecutionException(CompletableFuture.java:345)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:440)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2094)
	at net.runelite.client.RuntimeConfigLoader.get(RuntimeConfigLoader.java:63)
	at net.runelite.client.RuneLiteModule.configure(RuneLiteModule.java:86)

on macos After the inital screen I get this

**Comment by h0dgep0dge** [comment]
@naturedamends What are you trying to do, and what have you set up?

**Comment by naturedamends** [comment]
> [@naturedamends](https://github.com/naturedamends) What are you trying to do, and what have you set up?

I am just trying to connect via a proxy

ssh -N -D 1080 other@machine.local

I have just tried the commands like
/Applications/RuneLite.app/Contents/Resources ················································ INT ✘ ─╮
❯ jre/bin/java  -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080 -Djava.net.httpproxy.host=127.0.0.1 -Djava.net.httpproxy.port=1080 -jar RuneLite.jar

I have a sock5 proxy setup at port 1080 on localhost. I. have the internet turned off on this computer, and I connect to computer with it setup

curl -v --socks5-hostname 127.0.0.1:1080 oldschool.config.runescape.com                                 ─╯
*   Trying 127.0.0.1:1080...
* Connected to 127.0.0.1 (127.0.0.1) port 1080
* SOCKS5 connect to oldschool.config.runescape.com:80 (remotely resolved)
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 1080
> GET / HTTP/1.1
> Host: oldschool.config.runescape.com
> User-Agent: curl/8.7.1
> Accept: */*


It works. And it does the first loading screen. But it hands on the seond
2026-02-13 03:51:13 GMT [Preloader] INFO  net.runelite.client.rs.ClientLoader - Failed to get jav_config from host "oldschool.config.runescape.com" (connect timed out)
2026-02-13 03:51:33 GMT [main] ERROR n.r.client.RuntimeConfigLoader - error fetching runtime config
java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: connect timed out
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)

with the same config options as in the config.json file, it still fails
```
jre/bin/java -XX:+DisableAttachMechanism -Drunelite.launcher.nojvm=true -Xmx1024m -Xss2m -XX:CompileThreshold=1500 -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080 -jar RuneLite.jar
```

**Comment by h0dgep0dge** [comment]
I'm not immediately seeing anything wrong with this, and the curl line is a good test. I'm wondering if the curl command still works if you use `https://oldschool.config.runescape.com`?

**Comment by naturedamends** [comment]
> I'm not immediately seeing anything wrong with this, and the curl line is a good test. I'm wondering if the curl command still works if you use `https://oldschool.config.runescape.com`?

```
curl -v --socks5-hostname 127.0.0.1:1080 https://oldschool.config.runescape.com                         ─╯
*   Trying 127.0.0.1:1080...
* Connected to 127.0.0.1 (127.0.0.1) port 1080
* SOCKS5 connect to oldschool.config.runescape.com:443 (remotely resolved)
* SOCKS5 request granted.
* Connected to 127.0.0.1 (127.0.0.1) port 1080
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384 / [blank] / UNDEF
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=GB; L=Cambridge; O=Jagex Limited; CN=oldschool.config.runescape.com
*  start date: Jan 14 00:00:00 2026 GMT
*  expire date: Jan 21 23:59:59 2027 GMT
*  subjectAltName: host "oldschool.config.runescape.com" matched cert's "oldschool.config.runescape.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
* using HTTP/1.x
> GET / HTTP/1.1
> Host: oldschool.config.runescape.com
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 404 Not Found
< Server: nginx
< Date: Fri, 13 Feb 2026 04:00:52 GMT
< Content-Type: text/html
< Content-Length: 146
< Connection: keep-alive
<
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact
```

Does it do use strange ports, I did setup some ip filters on the router. But i'm pritty sure I just enable all ports

**Comment by h0dgep0dge** [comment]
No the client doesn't seem to be using a weird port, but it is using https

<img width="1465" height="28" alt="Image" src="https://github.com/user-attachments/assets/d0d11015-db74-4590-8e20-3a890909a29c" />

My only other suggestions would be to enable detailed logging on whatever you're using for your proxy to see if there are any clues there, or trying to capture and analyze the traffic at the packet level

**Comment by naturedamends** [comment]
> No the client doesn't seem to be using a weird port, but it is using https
> <img alt="Image" width="1465" height="28" src="https://private-user-images.githubusercontent.com/5608965/549217402-d0d11015-db74-4590-8e20-3a890909a29c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA5NTYwNDAsIm5iZiI6MTc3MDk1NTc0MCwicGF0aCI6Ii81NjA4OTY1LzU0OTIxNzQwMi1kMGQxMTAxNS1kYjc0LTQ1OTAtOGUyMC0zYTg5MDkwOWEyOWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAyMTNUMDQwOTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjk3NDZlY2UzODM2MGI4YTNiYTkxZGMzNWU1Y2ZhYWYwNzZhYzIxNmRkYzc5NTgxMzgwYjljN2VjOGMwNWFkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5TDQIMOKPD5NQxFw8lKKBgdoXbULIn12M_N2cuRr8HE">
> 
> My only other suggestions would be to enable detailed logging on whatever you're using for your proxy to see if there are any clues there, or trying to capture and analyze the traffic at the packet level

From the ssh -vvv I can't make out any active connections, none that start, or fail. But it must have worked for the launcher. in the client the only error is the one i have posted already. Failed to get config.

I'm not sure what to look for in wireshark if there are no connection via tunnel. I support that I might be trying to setup while not using the socks5 proxy, but if it works for you , I don't see why it would not for me

**Comment by h0dgep0dge** [comment]
You should get messages like the following when running `ssh` at verbosity level 2 or higher (Hot tip, run ssh with the -N flag to not open a shell on the remote end, makes the log cleaner to read)

`debug2: channel 2: dynamic request: socks5 host wtfismyip.com port 443 command 1`

Make sure you're getting those messages with your curl tests, and if you're not getting those messages running runelite then the java client isn't connecting to your proxy for some reason.

EDIT: I only just tried to actually replicate your issue by running runelite through a SOCKS proxy, and i'm having the same issue. Investigating further.

**Comment by h0dgep0dge** [comment]
@naturedamends The issue I've worked out is twofold. First, I believe my original instructions are incorrect and not what I was actually doing at the time. The options I gave in that post did make the launcher use the proxy, but when the launcher launches the client, that client doesn't inherit those options. The correct way to do that is by setting an environmental variable, like `export JAVA_TOOL_OPTIONS="-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080"` which the client will inherit.

The second issue is that the launcher itself no longer respects these proxy options, since commit [602ae31f5561920aeca2d386807700a3d87216cd](https://github.com/runelite/launcher/commit/602ae31f5561920aeca2d386807700a3d87216cd) switched to using a Java API that ignores the proxy options.

The workaround I would suggest is using an old version of the launcher, according to my testing [2.6.13](https://github.com/runelite/launcher/releases/tag/2.6.13) is the most recent version that works. As for a proper solution, I'm not sure what the "correct" way to get a Java application to run through a proxy without editing the source code, but maybe this would warrant a feature request to add explicit proxy support.

**Comment by naturedamends** [comment]
> @naturedamends The issue I've worked out is twofold. First, I believe my original instructions are incorrect and not what I was actually doing at the time. The options I gave in that post did make the launcher use the proxy, but when the launcher launches the client, that client doesn't inherit those options. The correct way to do that is by setting an environmental variable, like `export JAVA_TOOL_OPTIONS="-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080"` which the client will inherit.
> 
> The second issue is that the launcher itself no longer respects these proxy options, since commit [602ae31f5561920aeca2d386807700a3d87216cd](https://github.com/runelite/launcher/commit/602ae31f5561920aeca2d386807700a3d87216cd) switched to using a Java API that ignores the proxy options.
> 
> The workaround I would suggest is using an old version of the launcher, according to my testing [2.6.13](https://github.com/runelite/launcher/releases/tag/2.6.13) is the most recent version that works. As for a proper solution, I'm not sure what the "correct" way to get a Java application to run through a proxy without editing the source code, but maybe this would warrant a feature request to add explicit proxy support.

Ohh @h0dgep0dge, it does work. Setting the export :) 👍 legend. And running the commands, I did try doing some exports but they must not have been correct!!!!

@Enriath can we reopen this pr? Or the duplicate one?

```
 /Applications/RuneLite.app/Contents/Resources ························································─╮
❯ export JAVA_TOOL_OPTIONS="-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080"                             ─╯

  /Applications/RuneLite.app/Contents/Resources ················································ INT ✘ ─╮
❯ jre/bin/java -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080 -jar RuneLite.jar  
```

**Comment by naturedamends** [comment]
> [@naturedamends](https://github.com/naturedamends) The issue I've worked out is twofold. First, I believe my original instructions are incorrect and not what I was actually doing at the time. The options I gave in that post did make the launcher use the proxy, but when the launcher launches the client, that client doesn't inherit those options. The correct way to do that is by setting an environmental variable, like `export JAVA_TOOL_OPTIONS="-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080"` which the client will inherit.
> 
> The second issue is that the launcher itself no longer respects these proxy options, since commit [602ae31f5561920aeca2d386807700a3d87216cd](https://github.com/runelite/launcher/commit/602ae31f5561920aeca2d386807700a3d87216cd) switched to using a Java API that ignores the proxy options.
> 
> The workaround I would suggest is using an old version of the launcher, according to my testing [2.6.13](https://github.com/runelite/launcher/releases/tag/2.6.13) is the most recent version that works. As for a proper solution, I'm not sure what the "correct" way to get a Java application to run through a proxy without editing the source code, but maybe this would warrant a feature request to add explicit proxy support.


EDIT FIXED:  when doing this the fix was to remove my DNS servers at the network level, then it worked.

When doing this, using version 5 to have try to use sock5h for dns resolution, and blocking any dns resolution from my machine. 
It gets passed the launcher, downloads some stuff over the proxy. Then opens runeline and starts what I think is the client. When the client is running and it laoding things, it says "connecting to the update server and it just hangs there
```
export JAVA_TOOL_OPTIONS="-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080 -DsocksProxyVersion=5 -Djava.net.preferIPv4Stack=true"
jre/bin/java -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080 -DsocksProxyVersion=5 -Djava.net.preferIPv4Stack=true  -jar RuneLite.jar
```

```
RuneLite is unable to connect to the RuneScape update server. RuneScape might be offline for an update, check the game status page. If the game is online, then either a firewall is blocking RuneLite, or you don't have internet access.
```

```
2026-02-19 03:47:23 GMT [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 4.1 ATI-4.14.4
      error_game_js5connect
```

Thanks for your help
