### ISSUE TITLE
Darkmeyer & Sins of the Father quest update changes (2020-06-04 update)

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#11713]
### New world map icons

- [x] Sins of the Father quest start
- [x] Hallowed Sepulchre minigame
- [ ] Drakan's medallion teleport locations (both Darkmeyer and Theatre of Blood)
- [ ] Daeyalt essence mine (if it has mining icon)

### New overlays

- [x] Hallowed sepulchre? (Likely only want parity with pyramid plunder, not dedicated plugin or trap/path overlays)

### New loot tracking

- [x] ~~Vampyre pickpocketing~~ (already covered by existing pickpocket code)
- [x] Hallowed Sepulchre coffin / ghost loot

### Others

- [x] Clue scrolls which allow ivandis flail should accept upgraded flail
- [x] Code which accepts graceful outfit should be updated for the new dark theme graceful
- [ ] Possible charge tracking for the added Blood fury amulet, Strange Old Lockpick, and Ring of Endurance. These may be tracked per item, like crystal items, in which case this may not be reasonably possible
- [x] Timers plugin should have a lengthened stamina timer when activating a Ring of Endurance charge
- [x] Blood fury amulet should be added to our item mapping as it will revert to a normal amulet of fury after its charges deplete
- [x] New squirrel pet variations should be added to items kept on death plugin in the appropriate pets file
- [x] ~~If applicable, Hallowed marks should be given an untradeable item mapping to the appropriate value~~ (all Halloweed Sepulchre store items are untradeable)
- [x] ~~New regions (hallowed sepulchre may be the only one?) should be assigned new skybox values~~
- [ ] New / updated regions should be given names for the Discord plugin
- [x] New elite clue scroll
- [x] New hot-cold clue step (see #9601)

**Comment by melkypie** [comment]
Vampyre pickpocketing works with current implementation

**Comment by melkypie** [comment]
Daeyalt essence mine only has a dungeon icon in worldmap and doesn't have it's own section in the worldmap.

**Comment by makingcomment** [comment]
Based on the cache update, item id 24773 is a new elite clue step, so that's something to be on the lookout for.

**Comment by melkypie** [comment]
There are no tradable items in the shop where you use the hallowed marks, so there is no way to mark a ge value to them.
Also the worldmap location for the new medallion teleport is 3592, 3337. Since there currently isn't an icon for the other teleport either someone should design one and put it at theatre of blood also.

**Comment by melkypie** [comment]
Loot tracker for the new minigame Hallowed Sepulchre's coffins doesn't work with current implementation. When implemented it should also account that sometimes the loot may be given after a dialog with a ghost and depending on wheteher or not you are wearing a ghostspeak amulet or the mory legs 2 will give/not give you loot

**Comment by ThatGamerBlue** [comment]
Heres the new elite clue text. Probably will change after the next update but who knows http://imgur.com/OyEf9x2

**Comment by fontivan** [comment]
I was doing a master clue just now and had this step in darkmeyer, digging in front of this window did the trick. Very close to the new Drakan's teleport spot at least :)
![darkmeyer-new-clue-dig-spot](https://user-images.githubusercontent.com/21060660/84091058-6d8d9900-a9c1-11ea-9902-fc36092342aa.png)

**Comment by MarbleTurtle** [comment]
New elite clue is music step no changes required.
![image](https://user-images.githubusercontent.com/60723971/84601571-0abf5600-ae36-11ea-848b-61c74e280437.png)
