### ISSUE TITLE
Hide "x" combat range in Entity Hider

### ISSUE THREAD

**Issue by StreamFrankOceann** [runelite/runelite#11719]
The huge increase of people doing PvP related activities in smaller areas (Grand Exchange in PvP worlds, Revs Caves for big wars) plus the huge surge of looter accounts have taken a toll on my computer's FPS as well as making it really annoying to have an enjoyable experience when there is so many other people running around.

Since we have the option to hide clan mates, Npcs, local etc; why not the option to hide players on a certain combat bracket? Realistically when I'm pking im only interested in seeing people within my combat range, the rest are just adding noise and making my computer work harder.

Thank you from a fellow pker.

**Comment by Nightfirecat** [comment]
This banned by Jagex, per their [Unofficial Client Statement](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1):

> Offers additional information about other players, with the purpose of scouting PvP targets

Additionally, since long before that statement was authored, we have not considered conditional entity hiding to be an acceptable feature.
