### ISSUE TITLE
Flipping Utilities profit margin 

### ISSUE THREAD

**Issue by EtchasketchPL** [runelite/runelite#11712]
Flipping Utilities is not tracking buy and sell prices and total profits properly.

![Flipping Utilities](https://user-images.githubusercontent.com/32853654/82987743-ea297c00-9fac-11ea-9295-fc1fb0bbb4b3.PNG)
I should be at about 118,861 in profit with this quick test. 

 - OS: Windows 10
 - RuneLite version: 1.6.16
 - Launcher version: 1.6.0

If any more information is needed please ask.

**Comment by Broooklyn** [comment]
You should post this issue in https://github.com/Belieal/flipping-utilities rather than in Runelite
