### ISSUE TITLE
Item identification plugin tags are being drawn over the incinerator window

### ISSUE THREAD

**Issue by aoleszek** [runelite/runelite#11728]
**Describe the bug**
Names/tags from the Item identification plugin are being drawn over the bank's incinerator window.

**To reproduce**
1. Enable Item Identification plugin.
2. Open your bank.
3. Enable incinerator in the bank settings.
4. Scroll to a place in the bank where you have weeds/seeds stored.
5. Put any item in the incinerator.

![RuneliteBug2](https://user-images.githubusercontent.com/56226227/83143630-c451c380-a0e1-11ea-891a-55a8f379560b.gif)

**Expected behavior**
(Easier solution) The names shouldn't be drawn when the incinerator window is open.
(Harder solution) The names should be drawn under the incinerator window.

**Environment**
RuneLite 1.6.16

**Comment by raiyni** [comment]
Related to #10437

**Comment by Hydrox6** [comment]
Apparently this was fixed at some point, as this no longer happens. Not entirely sure when.
