### ISSUE TITLE
Agility obstacles of Rellekka Lighthouse

### ISSUE THREAD

**Issue by ComfortCurry** [runelite/runelite#11721]
**Is your feature request related to a problem? Please describe.**
The stepping stones from the barbarian outpost -> lighthouse do not have the green agility boxes.

**Describe the solution you'd like**
The correct path on the stepping stones should be pathed with green boxes

![image](https://user-images.githubusercontent.com/66047129/83102009-7187f580-a068-11ea-86d3-fdaaebcc5fca.png)

Using devtools in runelite, I found the right stones and tried to add them in the same style, but I'm new to Java and based on some errors, I'm probably doing something I shouldn't. I believe that these lines should be added to the [Obstacles file](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java) below the additions for Prif.

```
		// Rellekka lighthouse
		BEACH_4550, BASALT_ROCK_4551, BASALT_ROCK_4552, BASALT_ROCK_4553, BASALT_ROCK_4554,
		BASALT_ROCK_4555, BASALT_ROCK_4556, BASALT_ROCK_4557, BASALT_ROCK_4558, ROCKY_SHORE_4559
```

**Comment by Adam-** [comment]
added in 91bac5821a1adb172157bd45e2f0d6eae7185b04
