### ISSUE TITLE
Idle Notifier: Opening Rune Packs

### ISSUE THREAD

**Issue by whartd** [runelite/runelite#11732]
When you open one rune pack and afk it will slowly open each rune pack of the same type in your inventory. Some players take advantage of this to purchase runes 0 time during IRL obligations. In such cases, an idle notifier letting the player know when they have stopped opening packs would be useful. With the potential introduction of blood rune packs there may be increased demand for this feature soon - even if they do not get introduced, this would already be an incredibly useful feature.

Of the existing categories in the Idle Notifier plugin, this would most likely fall under "Idle Interaction Notifications."

**Comment by Nightfirecat** [comment]
The [Advanced Notifications plugin](Advanced Notifications) available on the plugin hub can accomplish this. I recommend using that plugin to send notifications for your use case.
