### ISSUE TITLE
Dragging Mini-Map Orbs with ALT

### ISSUE THREAD

**Issue by TzHaar-Kai** [runelite/runelite#11738]
**Describe the solution you'd like**
It would be nice to have the ability to reposition and possibly resize the Orbs near the Mini-map just like other screen overlays can be moved while holding down ALT. 

**Additional context**
Bring back the old Mini-map orb overlays from early Runelite and give us the option to move them around the Mini-map with ALT.
![download](https://user-images.githubusercontent.com/66086187/83179308-b185c180-a0d6-11ea-8702-06d65ff922a8.png)

**Comment by Nightfirecat** [comment]
We are not going to reimplement the minimap orbs. We already have a feature request to add repositioning to them in #11152, so I am closing this as a duplicate.
