### ISSUE TITLE
Idle Notification bugging out when crafting/fletching

### ISSUE THREAD

**Issue by ThaDankantor** [runelite/runelite#11755]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
So bascially when im crafting (blowing molten glass) or when im fletching(adding feathers to bolts or making shields from logs), the idle notification constantly pops up even when im still not done with finishing my inventory

**To Reproduce**
1. have idle notification on
2. blow molten glass or fletch anything
3. press somewhere outside of runelite so the computer isnt focused on runelite

**Expected behavior**
When im crafting or fletching, the idle notification goes off even when im not done crafting (blowing my glass)

**Screenshots**
https://docs.google.com/document/d/1XeF4GoViQZjpTlSrZ4i-DWP4VdzyYtLZIUhETSd8sjQ/edit?usp=sharing

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - RuneLite version: [e.g 1.6.17]
 - Launcher version: [e.g 2.1.0]

**Comment by Alexsuperfly** [comment]
set the delay higher
