### ISSUE TITLE
Agility shortcut highlight of unusable obstacle 

### ISSUE THREAD

**Issue by Mylosas** [runelite/runelite#11759]
Suggestion to remove Agility shortcut highlight of west 'Big window' obstacle on the south wall of Al Kharid palace. 
This one can't be used to leave the palace.

Screenshot: https://i.imgur.com/2PIf3gY.png

**Comment by mcnabbian** [comment]
I took a look at this yesterday and found that both 'big windows' have the same ID number, so there doesn't seem to be an easy fix. They could be differentiated based on x/y location, but that would take considerably more work.

**Comment by Adam-** [comment]
fixed in 1f3634d429d561165132c0616b051c65592a152f
