### ISSUE TITLE
Rename Jewelery Count plugin and add all items with charges/doses to it

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1176]
Also, possibly add a way to automatically detect items with charges by their name, so we don't have to manually put them all in.

**Comment by SoyChai** [comment]
Yup, there's been a consensus on renaming since #624 at least. I was planning a refactor once the 1.3.2 changes are shipped!

**Comment by ShaunDreclin** [comment]
Category toggles might be good, like "teleport items", "potions", "other" or something like that

**Comment by SoyChai** [comment]
I do like the idea of auto-numbering items using the (#) naming pattern. If we start filtering by item category though, we'll have to hardcode all of the known ones anyway, so it'd only be useful for new items during the dead week after their release.

**Comment by ShaunDreclin** [comment]
Well I was thinking doing it by the left click option, so if it has a "drink" op its a potion, if it has "rub" or "teleport" its jewelery, etc. Not sure if every item would fit into that pattern, might be worth trying

**Comment by SoyChai** [comment]
Sounds pretty smart on the surface. Time to start making a list 📝

**Comment by Nightfirecat** [comment]
This has been done afaik. Can be closed now?

**Comment by ShaunDreclin** [comment]
Partially but the new plugin doesn't work for all items with charges. Not sure if that's still on the table or not

**Comment by Nightfirecat** [comment]
Thus far we've been adding new items as they've been requested. (see the recently-added Ogre Bellows, and open issues/PRs for other items)

**Comment by ShaunDreclin** [comment]
I was hoping for a more automatic solution like Soy's PR but yeah I guess we can just do them manually as requested.

**Comment by deathbeam** [comment]
Yeah looks like the per-item solution is preferred so I will close this
