### ISSUE TITLE
Kills per hour tracker

### ISSUE THREAD

**Issue by twelve123322** [runelite/runelite#11763]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A plugin that trackers Kills per hour for us pvms. 

**Describe alternatives you've considered**
n/a

**Additional context**
It would come up in chat after each boss kill something like this https://i.imgur.com/bwcuZs8.png

**Comment by mcnabbian** [comment]
You can view your kills/hour by configuring the XP tracker plugin to show 'actions hour'.

<img width="244" alt="Screen Shot 2020-06-01 at 10 25 33 AM" src="https://user-images.githubusercontent.com/41792400/83436365-95459580-a3f2-11ea-8948-0052ff94a5a5.png">
<img width="279" alt="Screen Shot 2020-06-01 at 10 26 35 AM" src="https://user-images.githubusercontent.com/41792400/83436372-9a0a4980-a3f2-11ea-876e-d87ed738d8bb.png">

**Comment by On3TwO** [comment]
Thats not very accurate. currently at corp and it says im doing 82 k/hr in strength and 42 k/hr in hp. Thats why i suggested making it a separate plugin.

**Comment by LlemonDuck** [comment]
Available on plugin hub as [Bossing Info](https://runelite.net/plugin-hub/show/kph-tracker)
