### ISSUE TITLE
Expanded NMZ notifications

### ISSUE THREAD

**Issue by ivcosan** [runelite/runelite#11771]
**Is your feature request related to a problem? Please describe.**
Recently I've discovered a Push Notifications plugin for RL (push-notifs). It's great but it doesn't help at all in NMZ when I'm trying to AFK.

In the Idle Notifications plugin there is no option to trigger a notification when the HP is above set value (only below).

In the NMZ plugin there is no trigger for range/mage boost only the overload and absorb effects. 

**Describe the solution you'd like**
I'd like to be able to set a trigger for notification when my range level/boost falls below set value in the NMZ pluging

and/or

be able to select a trigger for when my HP is above set value in the Idle Notifications plugin.

**Describe alternatives you've considered**
Two alternatives explained in the point above.

**Comment by Broooklyn** [comment]
Check out `NMZ Utilities` on the plugin hub

**Comment by ivcosan** [comment]
> Check out `NMZ Utilities` on the plugin hub

Huh, I've completely missed that when looking through the plugin hub, thanks for that.

That somewhat solves the issue but still it would also be very useful to expand NMZ Utilities for another types of notifications (range/mage).

**Comment by JZomerlei** [comment]
Boosts information can notify when your boosted stats are below a threshold.

**Comment by ivcosan** [comment]
> Boosts information can notify when your boosted stats are below a threshold.

Just verified this. It also works perfectly together with the push notification plugin. The options were very scattered and I honestly overlooked them.

Thanks for help guys.
