### ISSUE TITLE
Client will not load, despite turning GPU off

### ISSUE THREAD

**Issue by jswann123** [runelite/runelite#11805]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Client will not load properly, and when turned off gpu plugin, was just stuck on "connecting to server updates"

[client.log](https://github.com/runelite/runelite/files/4729737/client.log)

**Expected behavior**
Just advice based on the client log on what to do would be great

**Comment by melkypie** [comment]
OSRS itself is offline https://twitter.com/OldSchoolRS/status/1268480445550866432

**Comment by jswann123** [comment]
I see I see thanks for the update
