### ISSUE TITLE
DPS Calculator integration

### ISSUE THREAD

**Issue by onyxflye** [runelite/runelite#11800]
It would be helpful to be able to check DPS vs. certain monsters by gearing up and not having to interact with a spreadsheet. 
This is Bitterkoekje's calculator that I'm referring to: https://docs.google.com/spreadsheets/d/1wzy1VxNWEAAc0FQyDAdpiFggAfn5U6RGPp2CisAHZW8/edit#gid=158500257

Thanks :)

**Comment by Hydrox6** [comment]
Duplicate of #350
