### ISSUE TITLE
buy limit reset timers duplicate themselves

### ISSUE THREAD

**Issue by 000000653** [runelite/runelite#11808]
**Describe the bug**
The buy limit reset timers duplicate every time you click any button in the grand exchange interface, guide price, enter quantity, and enter price buttons duplicate it once, any other button duplicates it twice.

It's also duplicated once upon opening the sell interface via clicking the item in your inventory instead of clicking the item after opening the sell interface.

This seems to only happen with items missing buy limits, items with known limits such as vial of water or brass key I cannot reproduce this with. Here's a list on the wiki. https://oldschool.runescape.wiki/w/Category:Exchange_items_missing_limit

**To Reproduce**
1. Buy any item that doesn't have a buy limit. Some examples are Elven top, Blighted karambwan, Blighted manta ray, Dragonstone boots, etc.
2. Either open the same item's buy interface or that item's sell interface.
3. Click buttons.
4. Observe dupe bugs.

**Expected behaviour**
Should only set a timer when you actually buy an item.

**Screenshots**
(gh doesn't support mp4 so youtube link it is)
https://youtu.be/FX1N0YjrtgQ

**Environment (please complete the following information):**
 - windows 10
 - RuneLite version: 1.6.18
 - Launcher version: 2.0.2

**Comment by Adam-** [comment]
fixed in 3d762d7ca2f5cad30009f1d48dca5093155a8fc8
