### ISSUE TITLE
Runelite Crashing daily/hourly

### ISSUE THREAD

**Issue by Nitonon** [runelite/runelite#11803]
**Describe the bug**
During CoX I tend to crash the most right before Olm room, other times its just random. I've reinstalled RL multiple times, made sure java/drivers are all up to date and nothing helps. 

I have a decent PC. R7 1700x with an rtx 2060 so I assume it doesn't have anything to do with these, although I did see posts talking about the gpu plugin being the issue but nothing to back it up. I'll also post logs on the most recent crash, I have others if needed.

[client_2020-06-03.0.log](https://github.com/runelite/runelite/files/4731687/client_2020-06-03.0.log)
[jvm_crash_pid_17440.log](https://github.com/runelite/runelite/files/4731688/jvm_crash_pid_17440.log)
[client_2020-06-02.0.log](https://github.com/runelite/runelite/files/4731690/client_2020-06-02.0.log)
[jvm_crash_pid_15676.log](https://github.com/runelite/runelite/files/4731692/jvm_crash_pid_15676.log)

**Comment by Nightfirecat** [comment]
Your launcher log shows no signs of issues. You should upload your client log file and/or any `hs_err_pid` or `jvm_crash_pid` files from the day(s) you experienced crashes.

**Comment by Nitonon** [comment]
[jvm_crash_pid_17440.log](https://github.com/runelite/runelite/files/4731661/jvm_crash_pid_17440.log)
[jvm_crash_pid_15676.log](https://github.com/runelite/runelite/files/4731664/jvm_crash_pid_15676.log)
[jvm_crash_pid_17764.log](https://github.com/runelite/runelite/files/4731667/jvm_crash_pid_17764.log)

**Comment by Nitonon** [comment]
Updated with client/jvmcrash for two days.

**Comment by MESLewis** [comment]
Does this happen on the latest release of RuneLite?
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.

**Comment by Felanbird** [comment]
Closing as this was very likely a duplicate report of #10628
