### ISSUE TITLE
GPU - Random freezing

### ISSUE THREAD

**Issue by jswann123** [runelite/runelite#11811]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Hi, I do a lot of risk fighting in PVP worlds via runelite, stretched mode and GPU enabled, within the logs I have had a recent crash and the GPU has been to blame...which lost me some gp...is there a way i can fix this to ensure i don't dc mid fight again please?

**Expected behavior**
Advice based on the logs uploaded.

**Screenshots**
Not applicable, I closed the client down in a fit of rage...apologies.

**Environment
[client.log](https://github.com/runelite/runelite/files/4732481/client.log)
:**

**Comment by Adam-** [comment]
You aren't using RuneLite, but instead a cheat client. Instead download runelite from https://runelite.net.
