### ISSUE TITLE
Make Pickpocketing Vampyres a Left-Click Option

### ISSUE THREAD

**Issue by AdamMartell** [runelite/runelite#11816]
**Describe the solution you'd like**
update the menu entry swapper to have an option to make pickpocketing a left click option for vampyre people

**Comment by JZomerlei** [comment]
This not allowed as per the statement given by Jagex.
Specfically: `Modifies menu options for pickpocketing, such as swapping 'Pickpocket' and 'Talk-to'`

See the full list here:
https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1
