### ISSUE TITLE
After the update today my zoom will not go out farther than default.

### ISSUE THREAD

**Issue by ffalor** [runelite/runelite#11817]
**Describe the bug**
Before todays update I could zoom out very far and one click much of the run for blood runes. Now zooming out is very limited. (it even looks like the default runescape client).

It is very unplayable to the point where I am now using OSbuddy.

**To Reproduce**
I don't know how to reproduce I just logged in after update, and this is what is happening.

**Expected behavior**
I should be able to zoom very far out, but it is now limited.

**Screenshots**

Picture of me fully zoomed out (in the past i could see the blood alter and click straight to it. Now i have to click through the fence at a very specific spot.
Runelite: https://gyazo.com/c8302138997bbc95109a5e45af8e49c8

Screenshot from OSbuddy where I can fully zoom out. (Runelite renders farther)
https://gyazo.com/a7aed4c52732811aeeacc06fb1da1f87

**Environment (please complete the following information):**
 - OS: Windowsos
 - RuneLite version: 1.6.18.1

**Comment by abextm** [comment]
restart your client
