### ISSUE TITLE
Olm "Shadow" Highlighter

### ISSUE THREAD

**Issue by ImShaped** [runelite/runelite#11821]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

When going into the olm room, you can't tell on which side olms shadow appears with gpu on (even with it off its quite difficult to see).

**Describe the solution you'd like**

I was wondering if a "Olm Highlight" feature could be added to RuneLite or the plugin hub.

This would highlight Olm's Head for a few seconds _when it is still not attackable_ so you can more clearly tell what side it comes up on.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

Alternative solutions to this are tagging the head/hand with the npc indicator plugin, as many people have; but I feel like this is just a bypass and rather inconvenient and ugly in my opinion.

**Additional context**

There used to be clients that had this plugin and I've got a gif of what those used to look like. These allowed for the option to recolour the tile too but that isn't a big deal obviously
![2020-06-05_12 56 40](https://user-images.githubusercontent.com/20026258/83871812-08237900-a731-11ea-8dca-12bf546c1dad.gif)

Also here's Olm's Head ID that would be tagged when it's not attackable 
![2020-06-05_13 41 14](https://user-images.githubusercontent.com/20026258/83872429-42d9e100-a732-11ea-8ca1-f44b410061fd.png)

**Comment by Hydrox6** [comment]
99% sure this is banned by the [Jagex Statemet](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Adds additional visual or audio indicators of a boss mechanic`

**Comment by ImShaped** [comment]
Isn't this already achievable by using NPC Indicators? With it already being achievable, making it less inconvenient doesn't seem like it would be that dramatic. Half the streamers have already got the hand or head tagged and I felt like this would allow it to look nicer. Not trying to come across as ignorant and if you still disagree that's fine.

> 99% sure this is banned by the [Jagex Statemet](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Adds additional visual or audio indicators of a boss mechanic`

**Comment by Hydrox6** [comment]
If it's doable with NPC Indicators, then there's really no need to have a specific option to do it then.

**Comment by ImShaped** [comment]
Hence, I'm suggesting this feature as a more convenient way of knowing where it comes out. Just like a lot of plugins have been added for the sake of convenience. Surely you can see where I'm coming from and I doubt I'm asking for the world here. Again, this would be a niche but nice feature to have in RuneLite and I can't see why it shouldn't be allowed as a request.

**Comment by Hydrox6** [comment]
As precedence, many features have been rejected because they can be done with another plugin already, such as Kitten Alerts, or basically any Menu swap for items. The stuff that's left over is either actually not possible without something custom, or it's old (an example of Old is the NMZ notifications, which could be done today with Chat Notifications instead).

We have enough options as is that something to automatically put a single name into NPC Indicators is just bloating the configs. Even as an external, it would be bloated imo. And if it really is as simple as adding a single name to NPC Indicators, there's no convenience to get here; putting a name in a box is about as simple as you can already get.

**Comment by ImShaped** [comment]
Is there any stance on a feature that would allow you to tag NPC ID's? Since that's (as far as I know) not possible through NPC Indicators.

**Comment by Hydrox6** [comment]
> Isn't this already achievable by using NPC Indicators?

> not possible through NPC Indicators.

:thinking: Make up your mind

If it's not possible under current stuff, then imo it falls under the Jagex statement.

**Comment by ImShaped** [comment]
It isn't possible to tag the non attackable form of the great olm's ID which would only tag a small _centered_ square. It is possible to tag the olm head all together but this will tag it as a big box that stays there forever and looks atrocious.
