### ISSUE TITLE
Mouseover Side Panel Disarster

### ISSUE THREAD

**Issue by cheekypaladin** [runelite/runelite#11836]
**Mouseover side panel disaster**
when mousing over, any of the side panel features it will duplicate, remove, grey out, white out, and glitch up the 'everything', although if you know where everything is you can still click on things, you just can't see whats going on.

**To Reproduce**
1. load runelite
2. Click on the side panel arrow to bring up options
3. mouse over things

**Expected behavior**
Chaos

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 2.1.3
 - Launcher version: 2.1.3?

![issue with runelite](https://user-images.githubusercontent.com/66541842/83959170-3930b480-a8bd-11ea-9498-1390968091f4.png)

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
