### ISSUE TITLE
Bank tag rearrangement

### ISSUE THREAD

**Issue by OilyHands** [runelite/runelite#11841]
**Is your feature request related to a problem? Please describe.**
I feel as if the bank tabs' ability to aid gearing up could be enhanced further - if possible

**Describe the solution you'd like**
Ability to change the order of items within a bank tag, without changing their order in the bank. So I could optimise the order and make gearing up easier. Attached are photos of what'd it be like before/after if this feature were to be added - with the xerics/air staff/ectophial arranged optimally for farm run gearing, despite not appearing in that order in my bank.

But currently, by rearranging stuff with a tag you also move the order of it in your bank too
![before](https://user-images.githubusercontent.com/32822218/83969167-4605d600-a8c6-11ea-88db-46914c5597aa.png)
![after](https://user-images.githubusercontent.com/32822218/83969168-47cf9980-a8c6-11ea-9cc7-d1b9ffb2c999.png)

**Describe alternatives you've considered**
Arranging items in your bank to optimise them for tags, but this is difficult when some items are used for lots of activities - also makes bank look worse.

**Comment by raiyni** [comment]
We have turned this feature down several times in other larger issues. Notably, bank tags only hooks the vanilla bank search.
