### ISSUE TITLE
Improving Clue Steps

### ISSUE THREAD

**Issue by liebzer** [runelite/runelite#11840]
Below are a series of clue step solution that need improvement.  They are unclear as to what location they pertain to.  I have given suggested solutions to each one.

<img width="573" alt="Screen Shot 2020-06-05 at 11 40 10 PM" src="https://user-images.githubusercontent.com/57821073/83960285-13170000-a83c-11ea-8b06-f799fa29d921.png">
"The bookcase located on the ground floor of the Wizard Tower."

<img width="539" alt="Screen Shot 2020-06-05 at 11 46 43 PM" src="https://user-images.githubusercontent.com/57821073/83960298-288c2a00-a83c-11ea-89c3-4c3c7faa6f5b.png">
"Search in the tents in the northwest corner of the soldier's camp in Burthorpe."

<img width="568" alt="Screen Shot 2020-06-06 at 1 38 13 PM" src="https://user-images.githubusercontent.com/57821073/83960307-4063ae00-a83c-11ea-8b31-b865ec391057.png">
"Located in the small building in Taverley attached by a fence to the main building.  Climb over the stile." 

<img width="457" alt="Screen Shot 2020-06-06 at 5 40 56 AM" src="https://user-images.githubusercontent.com/57821073/83960320-5a04f580-a83c-11ea-9158-246b692f18b1.png">
"The house east of the eastern bank in Falador."

<img width="238" alt="Screen Shot 2020-06-06 at 5 43 20 AM" src="https://user-images.githubusercontent.com/57821073/83960324-6e48f280-a83c-11ea-858a-bee57c88bfb3.png">
"Turael is located in Burthorpe in the small house east of the Toad and Chicken inn."

<img width="541" alt="Screen Shot 2020-06-06 at 9 07 07 PM" src="https://user-images.githubusercontent.com/57821073/83960334-84ef4980-a83c-11ea-951a-d45827ad90f5.png">
"The chest located in the house with the spinning wheel in Barbarian Village."

<img width="560" alt="Screen Shot 2020-06-06 at 9 45 02 AM" src="https://user-images.githubusercontent.com/57821073/83960345-ac461680-a83c-11ea-85d6-971487c86068.png">
"Morgan can be found in the house with the quest start map icon in northern Draynor Village."

<img width="511" alt="Screen Shot 2020-06-06 at 10 16 28 AM" src="https://user-images.githubusercontent.com/57821073/83960353-c4b63100-a83c-11ea-9103-53ee153e8884.png">
"Search the boxes in the tent east of the Silk trader in Al Kharid." 

<img width="574" alt="Screen Shot 2020-06-06 at 10 20 41 AM" src="https://user-images.githubusercontent.com/57821073/83960359-db5c8800-a83c-11ea-9cd4-37d833240486.png">
"Search the crates in the house, marked with a icon, southeast of the gem stall in Al Kharid."

**Comment by Broooklyn** [comment]
emerald000 on discord has been working on a large clue overhaul/update, which I believe includes these.
