### ISSUE TITLE
Anti Drag plugin does not work in the inventory while banking

### ISSUE THREAD

**Issue by fincher321** [runelite/runelite#11855]
![2020-06-08 11-09-05](https://user-images.githubusercontent.com/64691070/84054795-87a38900-a979-11ea-876a-ceb4daa282f3.gif)
(sorry for the low quality GIF)

I am not sure if this is considered a bug, or simply a limitation, but the Anti Drag plugin does not work when you interact with items in the inventory when banking. Holding shift does not stop items from dragging either.

**Comment by raiyni** [comment]
Duplicate #11768
