### ISSUE TITLE
Essence Counter in Runecrafting pouches

### ISSUE THREAD

**Issue by AgustinBanchio** [runelite/runelite#11850]
**Is your feature request related to a problem? Please describe.**
I empty the runecrafting pouches and don't always know if there was enough inventory space or not, so I always have to check the pouch again after crafting the essences.

**Describe the solution you'd like**
Have a small number indicating the number of essence inside the pouches on top of the inventory icon (like dose counters or similar)

**Additional context**
I don't know if it's possible for you to know the number inside without using the `check` option, but maybe counting how many essence get inside when filling them and how many go back to the inventory when emptying might be able to do it? If unsure of how many don't display the number or display `?`

**Comment by Broooklyn** [comment]
`Essence Pouch` in the plugin hub accomplishes this
