### ISSUE TITLE
Hallowed Sepulchre commands

### ISSUE THREAD

**Issue by Broooklyn** [runelite/runelite#11853]
It should be possible to share your Sepulchre floor/overall times as well as floor/overall completion counts. It could also be possible to pull the PBs from the Statistics board outside the minigame.

The following could have KC and PB commands:
 

- Floor 1

- Floor 2

- Floor 3

- Floor 4

- Floor 5

- Overall/Grand Hallowed Coffin

**Comment by Broooklyn** [comment]
Raw text for each floor:

Floor 1:

`2020-06-10 18:33:56 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: You have completed Floor 1 of the Hallowed Sepulchre! Total completions: <col=ff0000>112</col>.`

`2020-06-10 18:33:56 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: Floor 1 time: <col=ff0000>1:19</col>. Personal best: 0:28`

Floor 2: 

`2020-06-10 19:50:40 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: You have completed Floor 2 of the Hallowed Sepulchre! Total completions: <col=ff0000>111</col>.`

`2020-06-10 19:50:40 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: Floor 2 time: <col=ff0000>0:45</col>. Personal best: 0:34`

Floor 3:

`2020-06-10 19:52:19 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: You have completed Floor 3 of the Hallowed Sepulchre! Total completions: <col=ff0000>108</col>.`

`2020-06-10 19:52:19 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: Floor 3 time: <col=ff0000>1:26</col>. Personal best: 1:02`

Floor 4: 

`2020-06-10 19:54:53 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: You have completed Floor 4 of the Hallowed Sepulchre! Total completions: <col=ff0000>100</col>.`

`2020-06-10 19:54:53 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: Floor 4 time: <col=ff0000>2:22</col>. Personal best: 1:52`

Floor 5: 

`2020-06-10 19:59:15 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: You have completed Floor 5 of the Hallowed Sepulchre! Total completions: <col=ff0000>81</col>.`

If completing F5 with time left (time for F5 not given if you run out of time):

`2020-06-10 19:59:15 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: Floor 5 time: <col=ff0000>3:56</col>. Personal best: 3:05<br>Overall time: <col=ff0000>9:14</col>. Personal best: 7:49<br>`

Grand Hallowed Coffin:

`2020-06-10 19:59:07 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: You have opened the Grand Hallowed Coffin <col=ff0000>36</col> times!`

**Comment by ThePharros** [comment]
Correct me if I'm wrong but that appended Overall message is going to make Floor 5 w/ Overall messages messy:

* Floor 5 pb, overall pb
* Floor 5 new pb, overall pb
* Floor 5 pb, overall new pb
* Floor 5 new pb, overall new pb

Not all of these will be trivial to test the raw message for :|.

**Comment by Broooklyn** [comment]
Floor 5 pb, overall new pb:

``` 
2020-06-11 13:18:46 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: You have completed Floor 5 of the Hallowed Sepulchre! Total completions: <col=ff0000>124</col>.

2020-06-11 13:18:46 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: Floor 5 time: <col=ff0000>3:10</col>. Personal best: 3:04<br>Overall time: <col=ff0000>7:47</col> (new personal best)<br>
```

**Comment by Broooklyn** [comment]
Floor 5 new pb, overall new pb:

```2020-06-12 16:43:44 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: Floor 5 time: <col=ff0000>4:46</col> (new personal best)<br>Overall time: <col=ff0000>9:53</col> (new personal best)<br>```

**Comment by Nightfirecat** [comment]
Floor 5 new pb, without overall new pb:

```
2020-06-12 23:42:55 [Client] DEBUG client-patch - Chat message type GAMEMESSAGE: Floor 5 time: <col=ff0000>3:26</col> (new personal best)<br>Overall time: <col=ff0000>9:17</col>. Personal best: 9:15<br>
```

**Comment by Disconext** [comment]
It would be cool if the pb overall command showed each individual pb too, instead of just the overall time, e.g. "F1: 0:29, F2: 0:34 F3: 0:52, F4: 1:34, F5: 2:24, Overall: 6:26"

Similar somewhat to the !Cmb command

**Comment by ThePharros** [comment]
> It would be cool if the pb overall command showed each individual pb too, instead of just the overall time, e.g. "F1: 0:29, F2: 0:34 F3: 0:52, F4: 1:34, F5: 2:24, Overall: 6:26"
> 
> Similar somewhat to the !Cmb command

Yeah that can be done, would be better off as a separate command though. So `!pb hs overall` would give the overall pb, and then something like `!pb hs` would give all of their times.

**Comment by Nightfirecat** [comment]
I mentioned this in Discord and I'll repeat it here: I think there should not be variations for each floor and overall for the kc/pb commands. There should be only `!kc hs` and `!pb hs` (probably with `hallowed sepulchre` and `sepulchre` name variations) which should show all five floors and your overall stats. Having a sub-command for each variation is overkill imo

**Comment by ThePharros** [comment]
We discussed this briefly earlier in the Discord. I believe the consensus was to keep the individual variations and not the the appended variations.

**Comment by Adam-** [comment]
Is there a per-floor new pb message? Does anyone have it?

**Comment by melkypie** [comment]
```
[Client] DEBUG client-patch - Chat message type GAMEMESSAGE: You have completed Floor 2 of the Hallowed Sepulchre! Total completions: <col=ff0000>88</col>.
[Client] DEBUG net.runelite.client.plugins.examine.ExaminePlugin - Got examine without a pending examine?
[Client] DEBUG client-patch - Chat message type GAMEMESSAGE: Floor 2 time: <col=ff0000>0:47</col> (new personal best)
```
Here's a floor 2 new pb message, pretty sure it's the same for other floors except for floor 5

**Comment by Adam-** [comment]
added in #11897
