### ISSUE TITLE
Assigning colors to friends

### ISSUE THREAD

**Issue by Crynceps** [runelite/runelite#11854]
**Is your feature request related to a problem? Please describe.**
My friends and I talked about this issue a couple times. When you're messaging a lot of people at once using private messages, it can be a little tedious to see who sent what and you can make the mistake of thinking someone else sent a specific message and respond to the wrong person. 

**Describe the solution you'd like**
It would be cool to be able to assign colors to usernames. For example person A would be assigned green and person B would be blue. This would not only be a lot clearer but might also look nicer. 

**Describe alternatives you've considered**
Didn't really find any alternative solutions that wouldn't make the UI look pretty bad.

**Comment by Hydrox6** [comment]
Duplicate of #10316
