### ISSUE TITLE
Morytania Legs 3 teleport crashes client

### ISSUE THREAD

**Issue by dangithub96** [runelite/runelite#11856]
Whenever I log in, and use mory legs 3 to teleport to Burgh De Rott, my client crashes. This only happens if it's the first teleport of that login session.

First time submitting an issue so hope this helps and let me know if you need more information. Thanks!

**Comment by Nightfirecat** [comment]
Please post your `client.log` and any `hs_err_pid` or `jvm_crash_pid` files from your logs folder

**Comment by dangithub96** [comment]
> Please post your `client.log` and any `hs_err_pid` or `jvm_crash_pid` files from your logs folder

[jvm_crash_pid_4620.log](https://github.com/runelite/runelite/files/4748703/jvm_crash_pid_4620.log)

[client.log](https://github.com/runelite/runelite/files/4748704/client.log)
