### ISSUE TITLE
Slayer plugin does not update when querying the task through Activating a Slayer Gem

### ISSUE THREAD

**Issue by Nyanaro** [runelite/runelite#11863]
The Plugin shows a different task with a different number of monsters left. I have tried resetting the plugin with an enchanted gem, but that has proved futile.

It started after I completed a task on mobile, and once I returned to the runelite client the plugin wasn't working. I've uploaded a video of the occurrence here https://streamable.com/10x2z6

I am on Windows 7, Runelite version 1.6.18.1, Launcher version 2.1.0

**Comment by Hydrox6** [comment]
Check your gem via the right click menu to fix this right now. It should probably check for the dialogue text as well though.
