### ISSUE TITLE
Exiting Diablo II casts the game into a white screen

### ISSUE THREAD

**Issue by AcridBrimistic** [runelite/runelite#11878]
**Describe the bug**
Opening Diablo II and then closing it while RuneLite is open turns the game client into a white screen.

This can be remedied by doing something that causes a screen update (e.g changing resolution, low detail mode, etc.)

**To Reproduce**
1. Open RuneLite and Diablo II concurrently.
2. Close Diablo II.
3. The game client is now a white screen

**Expected behavior**
The game should continue as normal, with nothing unusual happening.

**Screenshots**
![what](https://user-images.githubusercontent.com/18503603/84442442-4dbad700-ac46-11ea-8e4e-76f81d0b4a69.png)

**Environment (please complete the following information):**
 - OS: Arch Linux (X, icewm, no compositor)
 - RuneLite version: 1.6.18.1
 - Launcher version: 2.1.0
 - Diablo II version: 1.13c

**Comment by Nightfirecat** [comment]
Does [disabling hardware acceleration](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration#linux) fix this for you? Also, can you upload your `client.log` and `launcher.log` files from when this occurs?

**Comment by Adam-** [comment]
fixed in f072c82973d58889abcb3df064ac3efb2eee4deb
