### ISSUE TITLE
Request Add Time to level

### ISSUE THREAD

**Issue by Pombos** [runelite/runelite#1187]
Can we have a time or actions till level up on skills?
 if this is already an upcoming feature sorry but i don't understand this website very much.

**Comment by SoyChai** [comment]
We don't have this afaik, it'd be a strong addition to the xp globe tooltips.

**Comment by sethtroll** [comment]
maybe this could be added to #1030

**Comment by JustANull** [comment]
Actions/level is already present in the XP tracker.

**Comment by SoyChai** [comment]
Ah there it is, it's not visible unless you left-click on the tracked stat. 💭

**Comment by deathbeam** [comment]
yeah both actions till level and time till level up are in XP tracker

**Comment by JustANull** [comment]
Time until level is not in the XP tracker.

**Comment by deathbeam** [comment]
It is, hover the XP bar :d

**Comment by sethtroll** [comment]
You need to hover over the progress bar to display time to level, but I think it should also display on the orbs aswell

**Comment by deathbeam** [comment]
But, duplicate information :( I think i still have image somewhere where we display the same information at like 4 different places close to eachother :d

**Comment by sethtroll** [comment]
I don’t think it’s that big of a deal since the information is coming from the xp tracker. Also it’s convenient for people who don’t want to open the sidebar to quickly check their skill details

**Comment by ShaunDreclin** [comment]
I think duping information is okay if we have it once in the game window and once in the sidebar, like Seth said I don't like having to open the sidebar all the time haha

**Comment by ShaunDreclin** [comment]
Also, related: #1041

**Comment by LeviSchuck** [comment]
This was introduced in 4272ba590fdde38c30297b3c87a725df70be34ac in March 10th 2018

**Comment by deathbeam** [comment]
This should be closed as the original feature description clearly wants what is already implemented.
