### ISSUE TITLE
Fairy ring tip BJS

### ISSUE THREAD

**Issue by JSadones** [runelite/runelite#11889]
**Is your feature request related to a problem? Please describe.**
Whenever you get the clue task that's near Zulrah, it says to teleport to BJS fairy ring.
Every god damn time I teleport there and then I notice you need 76 agility.

**Describe the solution you'd like**
Mention 76 agility in the tooltip

**Describe alternatives you've considered**
Uninstalling RuneLite

**Comment by brignano** [comment]
Valid point, I can see how this user experience would be frustrating.

To fix it, I believe the verbiage just needs to be updated for the below ```CoordinateClue```'s but, we should probably define a standard around how we will document these kinds of edge cases.

https://github.com/runelite/runelite/blob/e5adab24ddb088b35d7e09ac5a90bbb0909129a7/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java#L122
https://github.com/runelite/runelite/blob/e5adab24ddb088b35d7e09ac5a90bbb0909129a7/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java#L210

To me, it appears as though the current standard for documenting fairy ring codes in ```CoordinateClueInfo.directions``` is simply to add the relevant code (XXX) so, does anyone have any input on how we should communicate the additional requirement(s) in these scenarios?

**Comment by makingcomment** [comment]
Maybe `(XXX if _____)`? Here, that would be `(BJS if 76 Agility)`.

**Comment by Nightfirecat** [comment]
I agree, `(BJS if 76 Agility)` is decent verbiage

**Comment by JSadones** [comment]
Awesome, thanks guys!
