### ISSUE TITLE
Client failing to launch

### ISSUE THREAD

**Issue by simplepeon** [runelite/runelite#11890]
![Untitled](https://user-images.githubusercontent.com/66863317/84562459-9f4d8980-ad4c-11ea-8f2d-610d49ca042c.png)
I'm trying to launch Runelite but it keeps failing straight away, it was working fine yesterday. I've tried uninstalling it and installing it again, I've checked the firewall and it's allowing it but it keep saying it's timed out in the log

**Comment by Nightfirecat** [comment]
A solution was found in the `#support` channel of our Discord server. The following command was reported to work:

```
%localappdata%/runelite/jre/bin/java.exe -Djava.net.preferIPv4Stack=true -jar %localappdata%/runelite/runelite.jar --mode=OFF
```
