### ISSUE TITLE
Special attack Deffence pure

### ISSUE THREAD

**Issue by Sashim90** [runelite/runelite#11898]
I have been playing defense pure for many years, every time with pk I have to look at my watch to know when I will have dfs special again .. I would like to add a plugin that shows the time of reuse, thank you and I hope you will do it for me and other deffence pure

**Comment by Hydrox6** [comment]
The `Spec Regen Timer` plugin on the [Plugin Hub](https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub) does this.
