### ISSUE TITLE
Hardware Acceleration mode=OFF not fixing graphical issue w/ Sidebar

### ISSUE THREAD

**Issue by nathank92** [runelite/runelite#11902]
Notes:
64 bit Windows system w/ installed 64 bit Runelite.
RTX 2080 Super, Intel 9700k
Nvidia Driver #: 446.14 released 5/27/2020

NVIDIA Control Panel for Runelite is shown in the attachment.
![settings1](https://user-images.githubusercontent.com/66957374/84666739-13239980-aee7-11ea-8df5-e99a7a58bd43.JPG)
![settings2](https://user-images.githubusercontent.com/66957374/84666740-13bc3000-aee7-11ea-95ed-c0d85e458b4e.JPG)
![settings3](https://user-images.githubusercontent.com/66957374/84666743-13bc3000-aee7-11ea-9567-c6a27773e3ba.JPG)

**Comment by Alexsuperfly** [comment]
duplicate of #11727 

try [this](https://github.com/runelite/runelite/issues/11727#issuecomment-636641220) comment in there, or post an additional one if that doesnt seem to work for you

**Comment by nathank92** [comment]
> duplicate of #11727
> 
> try [this](https://github.com/runelite/runelite/issues/11727#issuecomment-636641220) comment in there, or post an additional one if that doesnt seem to work for you

The CMD seemed to have worked. 

Thank you Alexsuperfly!! Sorry for not being able to find this while searching.
