### ISSUE TITLE
Dead link on Building with IntelliJ IDEA Developer wiki

### ISSUE THREAD

**Issue by kevinforrestconnors** [runelite/runelite#11913]
**Describe the bug**
https://github.com/runelite/runelite/wiki/Using-RuneLite's-mixins is linked to [here](https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA) but the page does not exist

**To Reproduce**
1. Go tohttps://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA
2. Click on the "RuneLite mixins" link in the paragraph "You can build RuneLite locally using JDK 8 (or above) as the codebase supports language features up to Java 8. RuneLite mixins are the exception - these are are limited to Java 6."
3. You'll see that the link takes you to a page that doesn't exist

**Expected behavior**
The page exists.

**To Fix**
If the README is no longer relevant, remove the link and reword the paragraph.  If it is, create the page.

**Comment by abextm** [comment]
Fixed in b0a483378a47b514e19a01d264f627befe276b53
