### ISSUE TITLE
Add support for other types of dragon axes for use with the enchanted valley clue step

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#11928]
Per today's update post:

> Players can now store the Infernal or crystal axes in the Enchanted Valley S.T.A.S.H. unit.

**Comment by SammRosenthal** [comment]
does anyone know if the inactive version can be stored in the stash?

**Comment by MarbleTurtle** [comment]
![2020-06-18_22-03-02](https://user-images.githubusercontent.com/60723971/85098453-a2fb6900-b1af-11ea-8f79-03ed8424a77f.gif)
May want to wait on this as it appears to be bugged atleast with infernal axe.
