### ISSUE TITLE
Runelite Graphics Bug

### ISSUE THREAD

**Issue by Nekolist** [runelite/runelite#11929]
**Describe the bug**
Whenever I hover over things weird stuff starts happening.

**To Reproduce**
Steps to reproduce the behavior (Note, I am not sure if this is the only way to trigger it or if it works every time, this is just what I did):
1. Log into OSRS
2. Click on the info button
3. Hover over some stuff in the panel
4. Watch the world burn

**Expected behavior**
I expected the icons to work as they normally do (light up and when clicked launch a link (the link does launch btw))

**Screenshots**
I decided a video would make more sense
https://www.youtube.com/watch?v=umwMS1iiIe4

**Environment (please complete the following information):**
 - OS: Windows 10 x64 1909
 - RuneLite version: 1.6.20
 - Launcher version: 2.1.3

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
