### ISSUE TITLE
Add ability to change alpha of runelite overlays

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1193]
Sorry long day spacing the words but make it not see through so things like ground item overlay dont appear through it. Personally liked the look of old points info just like the extra stuff this one has.

**Comment by sethtroll** [comment]
I would like the ability to change the transparency of all our overlays, which might cover this.

**Comment by Stickaplex** [comment]
if we did all overlays though i would want option to change each specific one because I like it on some of them

**Comment by deathbeam** [comment]
I am personally against any customization of the current overlay look other than position and size to keep it consistent with native overlays. But maybe toggle to bring back original raids overlay would be okay.

**Comment by raiyni** [comment]
Added in https://github.com/runelite/runelite/pull/11619
