### ISSUE TITLE
Value modifier to ground items 

### ISSUE THREAD

**Issue by AlexZabe** [runelite/runelite#11932]
It would be nice if you could set a value on certain things (i.e. coins) to be hidden or not based off that.

For example: when doing gargoyle tasks it would be nice if when I get a 10k coin drop it would show up on the ground items but the 500 coin drops wouldn't.

**Comment by Alexsuperfly** [comment]
itemName `<|>` value 
in the hidden or highlight list should do exactly that

**Comment by Broooklyn** [comment]
Just for clarity, you can add `coins>10000`, for example, to highlighted items in the ground items plugin to only show coin stacks that are greater than 10,000.
