### ISSUE TITLE
de-aggro timer

### ISSUE THREAD

**Issue by AlexZabe** [runelite/runelite#11933]
A timer on screen that shows how long till you lose aggro against whatever monster you're fighting, and resets when you leave aggro range and re-enter.

Maybe where you can write the NPC's you want this pluggin to work on.

idk if anything like that is possible.

**Comment by MarbleTurtle** [comment]
You've described the features of the NPC aggression plugin. It shows you how long till you lose aggro, the area you need to leave to reset the aggro and can be setup to only work with npc's you specify or always active.
