### ISSUE TITLE
Menu Entry Swapper Prayer Book

### ISSUE THREAD

**Issue by bhurler1** [runelite/runelite#11930]
Swap the Read and Recite-prayer options of the book received as a reward from the The Great Brain Robbery. This will make curing poison with it less tedious.

**Comment by Hydrox6** [comment]
Use [Shift Click Configuration](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#customizable-shift-click) while it's in your inventory.

Swapping while equipped is banned by the [Jagex Statemet](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1)
