### ISSUE TITLE
Client stuck on launch.

### ISSUE THREAD

**Issue by Brandontroll** [runelite/runelite#11948]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)
(Could not find a similar issue.)

**Describe the bug**
On launching the RuneLite executable the client opens but gets stuck at various parts of the game loader, i.e: Prepared sound engine. 
Deleting cache and loading again produces the same issue.
Re-installing Runelite produces the same issue.
Using "--mode=OFF" extension also produces same issue (to combat sidebar glitch).

**To Reproduce**
1. Launch RuneLite.exe
2. Wait

**Expected behavior**
The game should launch normally and did so for months, but suddenly the client wont load the game. 

**Screenshots**
![RuneLite_ClientStuck](https://user-images.githubusercontent.com/67217271/85217845-c87ca400-b362-11ea-9d0a-129dda1f3bf2.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - RuneLite version: 1.6.20
 - Launcher version: 2.1.3

**Additional context**
[client.log](https://github.com/runelite/runelite/files/4808976/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4808978/launcher.log)

Launching the .jar from command prompt produces this output:
[Runelite_ClientReport.txt](https://github.com/runelite/runelite/files/4808985/Runelite_ClientReport.txt)

Relevant Hardware:
GPU: GTX 1080 ti
Driver version: 446.14

**Comment by Nightfirecat** [comment]
This may help: https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-closing-when-loading

Also, this is likely not a client bug, but would be better suited to ask [in our Discord's `#support` channel](https://runelite.net/discord)
