### ISSUE TITLE
Object Markers not rendering clickboxes accurately on certain objects

### ISSUE THREAD

**Issue by githubuser9989** [runelite/runelite#11941]
**Describe the bug**
Certain object clickboxes are no longer accurate. They were correctly rendered at least a few weeks ago.

**To Reproduce**
1. Enable the Object Markers plugin
2. Mark any anvil
3. The rendered clickbox area seems to be the size of tile of the anvil instead of the actual clickbox area

**Expected behavior**
The clickbox should be correctly rendered

**Screenshots**
Furnace clickbox is accurate, anvil is not
![image](https://user-images.githubusercontent.com/3521020/85195144-cef11a00-b295-11ea-80d2-ea0d83fab043.png)
![image](https://user-images.githubusercontent.com/3521020/85195166-0364d600-b296-11ea-87de-7d8ce03ebfca.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.20
 - Launcher version: 2.1.3

**Comment by Nightfirecat** [comment]
Object markers have never highlighted object clickboxes, they highlight the convex hull of objects. If this has changed, it is almost certainly because Jagex changed this anvil's model, not because we changed any of this plugin's code.
