### ISSUE TITLE
Mining Plugin has the wrong time for Lovakite rock respawn

### ISSUE THREAD

**Issue by M-a-x-y** [runelite/runelite#11949]
**Describe the bug**
The rock respawns when the timer is mostly through (like 85%)

**To Reproduce**
1. Make sure Mining plugin is on
2. Mine Lovakite rock
3. Wait for respawn

![ezgif-4-14af07752a52](https://user-images.githubusercontent.com/36554991/85222377-c582c180-b3fd-11ea-9578-bf11768c73df.gif)

**Expected behavior**
The loading timer to complete fully exactly on time of rock respawn

**Screenshots**
GIF attached.

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.6.20
 - Launcher version: 1.6.2

**Comment by Alexsuperfly** [comment]
lovakite rocks have a dynamic respawn time from 30 all the way to 45 seconds the wiki says, in my testing i never had one go over 38 seconds so i set the max at 39.  The timer is yellow when it cannot respawn and green when its hit the minimum threshold to possibly respawn, while still filling up untill the maximum time
