### ISSUE TITLE
Icons off center and weirdly placed

### ISSUE THREAD

**Issue by pickausername00** [runelite/runelite#11950]
Not sure when this first happened, but my icons seem to be like stuck in resizable mode and when i switch to fixed they just stay there and are off center and annoying. The inventory icons to be more clear. 

![2233](https://user-images.githubusercontent.com/67225719/85223005-28f1fc80-b3c8-11ea-9e3e-4f5e13eb7f3a.PNG)

**Comment by Hydrox6** [comment]
Issues with Plugin Hub plugins should be made on the [repo](https://github.com/melkypie/resource-packs) for that plugin

**Comment by pickausername00** [comment]
?
