### ISSUE TITLE
Menu entry swap (equip / use )

### ISSUE THREAD

**Issue by AlexZabe** [runelite/runelite#11955]
Could we get an addition to the menu entry swapper to swap equip with use.

Specifically for when alching onyx bolts. I've started the corp grind on my ironman and this would be nice for alching the bolts. thanks.

**Comment by Hydrox6** [comment]
Use [Shift Click Configuration](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#customizable-shift-click)

This is also essentially the same request as issues such as #7963 and #10159
