### ISSUE TITLE
Strange Graphic issue with runelite 

### ISSUE THREAD

**Issue by jalexander93** [runelite/runelite#11957]
recently downloaded runelite as it is open source and in the processes of learning/writing myself after moving over from a basic laptop to a built PC ran into the following error ( see image below). GPU has been turned off also hardware acceleration has been disable using --mode=OFF (found on this site reason why i joined) issue has been addressed in previous post but seems that it is only a quick fix luckily in game graphics are fine looks to be more of a client issue as some commands can not be click due to this issue 

![image](https://user-images.githubusercontent.com/67282839/85311746-e4c43200-b483-11ea-9f46-b181a7906d2a.png)

**Comment by Hydrox6** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by jalexander93** [comment]
> https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

i just wrote those were quick fixes and did nothing

**Comment by Hydrox6** [comment]
Fine, Duplicate of #11727

**Comment by jalexander93** [comment]
> Fine, Duplicate of #11727

that still doesn't work hence why i posted this lol ... and opening runelite through the command prompt is not ideal yea it works for the time being but its not a fix to the issues as stated in those comments that you say are "duplicated"
