### ISSUE TITLE
Inventory icons off center on the runelite client

### ISSUE THREAD

**Issue by pickausername00** [runelite/runelite#11951]
So yeah basically my inventory icons are weird. Its like they're stuck in the resizable mode state. When i switch to fixed mode they dont move.

![2234](https://user-images.githubusercontent.com/67225719/85223071-a74e9e80-b3c8-11ea-9313-782984799176.PNG)

**Comment by Psyda** [comment]
The selected tab icon appears to be from the 2005 theme in interface styles. Do you have that or resource packs enabled?

**Comment by Hydrox6** [comment]
Duplicate of #11950
