### ISSUE TITLE
Banked xp plugin to include molten glass/seaweed?

### ISSUE THREAD

**Issue by mitchhanks** [runelite/runelite#11956]
It would be something like:

// seaweed
GIANT_SEAWEED(ItemID.GIANT_SEAWEED, "seaweed", Skill.CRAFTING, 60.0),//produces 9.6 molten glass each when using 3 giant seaweed/18 buckets of sand. + 10 crafting xp per bucket of sand when using superglass make spell. 18/3 = 60 xp per giant seaweed.

SEAWEED(ItemID.SEAWEED, "seaweed", Skill.CRAFTING, 10.0),//produces 1.3 molten glass per seaweed when using superglass make. 1 each if using a furnace.

SODA_ASH(Item.ID.SODA_ASH,"seaweed", Skill.CRAFTING, 20.0) each soda ash + bucket of sand creates 1 molten glass and gives 20xp each when using a furnace. 
OR it's the same as seaweed if using superglass make 1.3 molten glass per one.

Reference
https://oldschool.runescape.wiki/w/Molten_glass

// molten glass level req/name/xp
1 Beer glass  17.5 
4  Empty candle lantern  19
12 Empty oil lamp  25
33  Vial 35
42 Empty fishbowl 42.5
46 Unpowered orb  52.5 
49 Lantern lens  55
87 Empty light orb  70

**Comment by raiyni** [comment]
Please open this on the plugins repository

**Comment by mitchhanks** [comment]
> Please open this on the plugins repository

Is it possible to be moved there? Not used this before.

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us.
