### ISSUE TITLE
Dorgesh-Kaan rich chests menu entry swapper

### ISSUE THREAD

**Issue by CaptainSpaz** [runelite/runelite#11952]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

When looting the Dorgesh-Kaan rich chests it always has 'open' ontop and requires a right-click to 'picklock'.

**Describe the solution you'd like**

A menu entry swapper for this would half the clicks required to train thieving this way.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by dekvall** [comment]
Duplicate of #7522
