### ISSUE TITLE
Shift+Right click to add/remove NPC name to NPC Indicators Highlight list

### ISSUE THREAD

**Issue by LewdMantaRay** [runelite/runelite#11961]
**Is your feature request related to a problem? Please describe.**
It is not an issue, but would be an amazing addition towards the NPC indicator, rather than having to type in / delete everytime you'd like to change it up.

**Describe the solution you'd like**
Have an option in the NPC indicators plugin where you can shift right click NPCs, to add it to the highlighted list, or remove it. (kind of like the option when you can mark ground tiles)

**Comment by Nightfirecat** [comment]
There is already a <kbd>Shift</kbd>+right-click option for tagging individual NPCs. Are you asking for another right-click option to add the NPC name to the highlight list?

**Comment by LewdMantaRay** [comment]
> There is already a Shift+right-click option for tagging individual NPCs. Are you asking for another right-click option to add the NPC name to the highlight list?

Waaaaaaaaaaaaait, I was suggesting it to add things to the highlight list, but tagging thing kinda works the same way, right? even for groups of that npc?

**Comment by Broooklyn** [comment]
It only works for the specific npc, not the group, and I don't believe it is retained across restarts.

**Comment by LewdMantaRay** [comment]
O, then yeah it would be great if we could shift right click to add/remove to the highlighted lists,
