### ISSUE TITLE
Barrows brother location incorrect

### ISSUE THREAD

**Issue by davsan56** [runelite/runelite#11980]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

The location of the brothers crypts on the minimap is incorrect

**To Reproduce**
1. Go to Barrows
2. See error

**Expected behavior**

Barrows brother location to be correct

**Screenshots**

![image](https://user-images.githubusercontent.com/7637218/85714316-4d93f000-b6b8-11ea-92ee-7b87620dd7f5.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS] Windows 10
 - RuneLite version: [e.g 1.4.6] 1.6.20
 - Launcher version: [e.g 1.5.2] 2.1.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by abextm** [comment]
restart your client
