### ISSUE TITLE
stacked icons

### ISSUE THREAD

**Issue by RuthlessClapper** [runelite/runelite#11981]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
My inventory and usch are stacked up on each other in the left upper corner. Yesterday there was nothing wrong with my client, but when i logged in my client looked like this: https://imgur.com/a/qzp3izy
I tried to resize my screen with the ingame settings. The icons still are not on the spot they use to be: https://imgur.com/a/dsAWABi

can someone help me?

Thanks,
RuthlessClapper (IGN: LilUziiiVert)

**Comment by abextm** [comment]
restart your client

**Comment by RuthlessClapper** [comment]
tryed it, reinstalled it, still the same.

**Comment by dekvall** [comment]
What if you try restarting right now?

**Comment by RuthlessClapper** [comment]
It works now! hahaha wth just happend?
