### ISSUE TITLE
Menu Entry Swapper Customizable Shift-Click Teleport Items Bugged

### ISSUE THREAD

**Issue by BlingTeeth** [runelite/runelite#11986]
I have always used Custom Shift Click to wear my Amulet of Glory with Teleport item enabled so I can click to Rub, but now that is broken with all the teleport jewelry. I have found a workaround by doing shiftclick Rub and normal click to wear but I miss my old setup. Please fix this bug or let me know if it was changed on purpose.

**Comment by jevonsp** [comment]
Ah, didn't see you submitted this as I was working on my bug report. 

I am also quite annoyed with the change.

**Comment by DADtheMaggot** [comment]
I'm happy to add this as a separate issue if you'd prefer, but I also noticed the "claim-slime" entry swap got mixed up in the restructure. It turns on when you check "trade", rather than "claim-slime". 

Cheers for all of the menu entry swap updates thought, it looks so much cleaner!

**Comment by Adam-** [comment]
> 
> 
> I'm happy to add this as a separate issue if you'd prefer, but I also noticed the "claim-slime" entry swap got mixed up in the restructure. It turns on when you check "trade", rather than "claim-slime".
> 
> Cheers for all of the menu entry swap updates thought, it looks so much cleaner!

Can you test https://github.com/Adam-/runelite/commit/597bbc6b1c51dd8f357eed1befc596a14a2e651d? it should fix this issue.

**Comment by BlingTeeth** [comment]
> > I'm happy to add this as a separate issue if you'd prefer, but I also noticed the "claim-slime" entry swap got mixed up in the restructure. It turns on when you check "trade", rather than "claim-slime".
> > Cheers for all of the menu entry swap updates thought, it looks so much cleaner!
> 
> Can you test [Adam-@597bbc6](https://github.com/Adam-/runelite/commit/597bbc6b1c51dd8f357eed1befc596a14a2e651d)? it should fix this issue.

How do I use this script? Do I download it and drag and drop? Sorry, I am quite new to this stuff. I am just a casual user after all.

**Comment by Broooklyn** [comment]
Don't worry, I've tested it and can confirm it fixes the teleport item issues.

**Comment by Adam-** [comment]
fixed in 31c66294f09bb8fefd1691601bf4cd7906864779
