### ISSUE TITLE
Client crashes when logging onto alt

### ISSUE THREAD

**Issue by macrousd** [runelite/runelite#11997]
Client crashes when logging onto my alt account. It crashes within first 5 seconds after logging in on that account, ive tried to replicate it on my main but it never crashes. It was never an issue until about a week ago June 18th-25th in that time frame.  It works fine in runescapes normal client even alongside with runelite on my main.

Things ive tried to troubleshoot:
Disabled all plugins
Logged into alt with just the one client open
Restarted computer

I havent tried reinstalling client yet but just wondering if anyone else had any issues recently maybe after a runelite update

**Comment by Nightfirecat** [comment]
Have you tried [following the steps on our troubleshooting page for "Client crashing on login"?](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-crashing-on-login)

If that does not work, please upload your client.log, launcher.log, and the most recently-created of any `hs_err_pid` or `jvm_crash_pid` files you find in your logs folder. (see the top of the linked wiki page for directions on finding your logs)

**Comment by macrousd** [comment]
I just reinstalled it and it seems to be working ill see if it crashes again hoping thst fixed it though
