### ISSUE TITLE
Barrows Reward Potential not being colored properly

### ISSUE THREAD

**Issue by rchinerman** [runelite/runelite#12009]
For every monster killed, the player gains Reward Potential equal to the combat level, up to a cap of 1000. Upon item roll, for every Barrows brother killed the player gains an additional +2 points, which increases the cap to 1000 + 2 * # brothers killed, up to 1012. 

The Reward Potential being returned from the client `client.getVar(Varbits.BARROWS_REWARD_POTENTIAL)` doesn't have the +2 points for each brother, just the combat levels. This means that when the client states that the user has 880 Reward Points, which is displayed as green in RuneLite because it's under 88.0%, for the sake of item rolling they will actually have 892 Reward Points and accidentally unlock Bolt Racks, which are unlocked at 881. 

One possible solution would be to re-calculate both the Reward Potential and the total possible points to include the +(2 * # brothers killed) bonus points for item rolls, as this is what the user actually cares about. The color thresholds would need to be calculated, rather than hard coded, in this scenario. Another solution would be to simply adjust the current upper threshold for green to 86.8%, which is the ideal number - 1.2% from the 12 invisible points.

I think my favorite solution would be to move away from using percentages and instead just use the Reward Potential integer, as this is how all of the resources around Barrows track the information. One could either show the Reward Potential and correct it by adding the invisible points, or show Base Reward Potential as the number returned from the API, Bonus Reward Potential (which is the 2 * brothers killed figure), and then lastly Total Reward Potential for maximum clarity. 

Sources: 
[Wiki](https://oldschool.runescape.wiki/w/Barrows/Strategies#Optimising_the_average_value_of_the_rewards)
[Mod Kieren](https://twitter.com/JagexKieren/status/705428283509366785/photo/1)

**Comment by Nightfirecat** [comment]
This is fixed in 807a22172f. The overlay still displays a percentage, but the coloring of that percentage is now based solely on the player's reward potential points.
