### ISSUE TITLE
Tick Counter

### ISSUE THREAD

**Issue by mindheady** [runelite/runelite#12011]
Can we get a tick counter for theatre of blood? like some other clients have. i feel like im missing out but dont wanne not use RuneLite.....

**Comment by Nightfirecat** [comment]
Can you provide some more information? What would a tick counter look like?

**Comment by mindheady** [comment]
Alright, what i meaning is that the dps counters are based of RNG.
i would like to see a tick counter or afk timer.
meaning to be able to see if somebody (prefered team wide) is standing afk in an room or running around not doing dmg

**Comment by Adam-** [comment]
This has been added to the pluginhub now.

**Comment by mindheady** [comment]
Thank you very very much!!!
