### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by jrobinallsopp** [runelite/runelite#12014]
Possible to make a chromecast plugin so we can have super low quality java graphics on our big ass TVs?

**Comment by ErikHumphrey** [comment]
I don't think Google Cast / Chromecast APIs are meant to be used outside of Android, iOS, and Chrome applications.

**Comment by Nightfirecat** [comment]
From what I understand of Chromecast, it does not support this. You could cast your whole desktop, but you generally cannot cast specific application windows.
