### ISSUE TITLE
GPU Plugins crashes client

### ISSUE THREAD

**Issue by Not2Day1024** [runelite/runelite#12022]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
With the GPU plugin enabled, I lose lots of frames and then crash.

**To Reproduce**
1. Enable GPU plugin
2. Wait for client to crash

**Environment (please complete the following information):**
 - OS: Windows 10
 - CPU: Ryzen 1700
 - GPU: GeForce GTX 1080
 - RuneLite 1.6.21.1 (launcher version 2.1.0)

[client_2020-06-27.0.log](https://github.com/runelite/runelite/files/4842860/client_2020-06-27.0.log)
[launcher_2020-06-27.0.log](https://github.com/runelite/runelite/files/4842861/launcher_2020-06-27.0.log)

**Comment by MESLewis** [comment]
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.
