### ISSUE TITLE
Var Inspector doesn't work past varbit 2633

### ISSUE THREAD

**Issue by aeramos** [runelite/runelite#12025]
**Describe the bug**
The Var Inspector in Dev Tools doesn't record changed varbits past varbit 2633, it will instead show the changed varp and varp values.

**To Reproduce**
1. Start the client with the Dev Tools available after compiling from source
2. Start the Var Inspector and do an action ingame that should change a varp or a varbit value, like entering/exiting the wilderness. It will start looking through each varbit that changed and stop at 2634 with an IndexOutOfBoundsException. It'll say in the console that it "Hit OOB at varbit 2634".
3. The Var Inspector will show you the changed varp and varp values instead of the varbit change if the varbit is past 2633.

**Expected behavior**
It should work for all varbits. It used to work fine a few months ago, but I tried it today and found this bug.

**Environment (please complete the following information):**
 - OS: Windows 10 Enterprise version 1903
 - RuneLite version: compiled from current source: 1.6.22-SNAPSHOT
 - Launcher version: "Unknown"

**Comment by aeramos** [comment]
My pull request (https://github.com/runelite/runelite/pull/12026/) should fix this.

**Comment by Adam-** [comment]
fixed in 53c8593929c89290530f18f52eed8117b3ef8a21
