### ISSUE TITLE
Change overlay tooltip to show plugin's metadata while holding alt

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#1203]
Lots of people are confused about what plugins create what overlays, so displaying that info would be very helpful.

**Comment by SoyChai** [comment]
I imagine metadata here to mean the title and description of the plugin hovered over, that'd help speed up the search for an overlay's plugin config.

**Comment by ShaunDreclin** [comment]
Plugins that create overlays could add that info to the overlay as they're created though, right? Maybe not as ideal as a more centralized solution, but would still get the job done

**Comment by deathbeam** [comment]
well not only plugins create them, but they could I guess.

**Comment by deathbeam** [comment]
We now have right-click menus so i think this is somehow solved
