### ISSUE TITLE
Provide a total count of number of ores deposited at blast mine

### ISSUE THREAD

**Issue by jcharles8246** [runelite/runelite#12039]
[From the wiki](https://oldschool.runescape.wiki/w/Blast_mine).

> When there are 450 of any single type of ore in the sack, it will become full and the player will need to collect it

Would be nice to update the blast mine plugin overlay to show how much ore is deposited.

**Comment by Bram91** [comment]
This is already a feature in the current plugin: https://github.com/runelite/runelite/wiki/Blast-Mine#show-ore-overlay

**Comment by jcharles8246** [comment]
My mistake, it seems its any *single* ore not a total sum of ores
