### ISSUE TITLE
Suggestion: Gnome restaurant plugin

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#12031]
There are plugins for many minigames, but there is none for the Gnome Restaurant. It would not require too much and could work similar to the clue scrolls plugin, here's what I think would be useful:

- Add a hint arrow on the customer, similar to NPCs when solving clues. 
- Some HUD which would should the information about remaining time, customer and food, again similar to clue scrolls plugin
  - There could be a check if the required food is in inventory, similar to emote items for clues
  - perhaps include suggested transportation method?
  - perhaps include ingredients/recipe required to cook the food if not present in inventory?
- Some integration with the loot tracker plugin?

**Comment by Nightfirecat** [comment]
Some parts of this request are not fulfilled by the hub plugin. (loot tracker integration, suggested transportation method) Transportation method can be requested on MMagicala/gnome-restaurant, loot tracker integration (if wanted) can be requested on this repo in a separate issue.
