### ISSUE TITLE
Cancelling a partially-filled buy/sell offer results in duplicate GrandExchangeOfferChanged events

### ISSUE THREAD

**Issue by jmhertlein** [runelite/runelite#12037]
When a buy or sell offer partially fills, but is then cancelled, two GrandExchangeOfferChanged events get generated instead of just one.

**To Reproduce**
1. Place a buy offer for 21,000 Air runes (GE limit is 20k)
2. 20k will buy, and it'll sit waiting to buy the last 1k.
3. Hit cancel.
4. Collect your gold from the menu

At this point, two GrandExchangeOfferChanged events fire, both with the exact same info, with state `CANCELLED_BUY`.

**Expected behavior**
I would expect exactly one event to be sent.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - 1.6.21.1
 - tbh not sure how to get the launcher version

**Additional context**
Printing the state to stdout, I see this flow:

```
[...]
BUYING
BUYING
BUYING
CANCELLED_BUY
CANCELLED_BUY
EMPTY
```
So I think there's more "duplicates" going on perhaps, but personally I'm only worried about CANCELLED_BUY. Furthermore, I could see how "BUYING" would be fair game to send multiple times, since you are indeed still buying.

I could obviously pretty easily debounce this in my plugin, but if this is something that can be fixed internally, I think that would be a lot more robust of a solution.

**Comment by Adam-** [comment]
The event fires whenever a ge update packet is received, and the server sends duplicates. We can't really fix this without trying to deduplicate it ourselves internally maybe. Currently the GE plugin deduplicate this itself by storing the previous known state, which it has to do regardless.

**Comment by jmhertlein** [comment]
dang it jamflex.

Thanks for the context. I'll debounce on my side.
