### ISSUE TITLE
Kourend Library plugin bugs and resets when you grab "Varlamore Envoy"

### ISSUE THREAD

**Issue by avirunes** [runelite/runelite#12041]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Kourend Library plugin bugs and resets when you grab "Varlamore Envoy"

**To Reproduce**
1. One the "Kourend Library" plugin solves library, try to pick up the "Varlamore Envoy" book 

**Expected behavior**
Plugin doesnt reset and you don't have to find other books again for the plugin to show book locations

**Comment by Blackberry0Pie** [comment]
I'm not able to reproduce this. The library rotation chances every 80-100 minutes. It is possible that the library rotation changed before you searched that bookshelf, and the plugin reset when no book was found in the expected location.
If you still have this issue please give more details on your plugin config settings.

**Comment by honeyhoney** [comment]
I'm pretty sure I came across this bug too. I've since completed the quest `The Depths of Despair` so I can't test this personally but here are what I believe to be the steps to reproduce the bug:

1. Make sure `The Depths of Despair`  quest is not complete (maybe not even started?)
2. Use the plugin normally to solve the library
3. Once the library is solved, seek out the `Varlamore Envoy` quest (make sure the config isn't set to hide it)
4. Attempt to "loot" the bookcase that the plugin has indicated contains `Varlamore Envoy`. The plugin will its solved state.

**Comment by hawkins** [comment]
I can confirm honeyhoney's reproduction steps. I have not started the Depths of Despair quest and I have been using the plugin to solve the library for about 3 hours now and have yet to be asked for the book at all. However, every time I loot the shelf that should give me the book, the plugin resets and all books are lost (though all books can be found in the same places originally expected, so the rotation has not changed).

**Comment by Nightfirecat** [comment]
It would help for someone to get a simple and clear reproduction video of this--starting from a clean state (toggle the plugin off and on, or from a fresh session) search bookcases to determine the active rotation, then show the plugin losing the rotation when searching for the Varlamore Envoy.

**Comment by hawkins** [comment]
Here's a link to a very painful 1fps repro: https://giphy.com/gifs/d7JrnXfUj9YhMSioJr

Exporting the video is taking forever, but I'll edit this comment if I can get a better version hosted.

**Comment by Blackberry0Pie** [comment]
Looks like the bug is
1. Don't have The Depths of Despair started or completed.
2. Search the bookcase that would contain the Valramore Envoy if 1) was false.
3. Plugin resets because the book is not found.
