### ISSUE TITLE
Vorkath attack counter (for his special attacks)

### ISSUE THREAD

**Issue by ZenyteFury** [runelite/runelite#12054]
As most of you probably know, Vorkath uses one of two special attacks after 6 normal attacks. However, sometimes I mess up the count because I don't pay enough attention, which leads to me dying or taking a lot of damage. 

To help with this, I feel like an attack counter would help. This attack counter would either count up to 6 (or count down from 6), after which it displays a special attack indication.

Another option would be to give some type of warning a little bit (maybe 1 attack) before the special attack comes.

I hope multiple of you like this idea as well since it can make Vorkath a little less of an effort.

**Comment by Bram91** [comment]
This would be against the rules:
https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

Specificially breaks the following:

- Attack counters
- Next attack prediction (timing or attack style)
