### ISSUE TITLE
Add support for ItemID overrides (re: reverting to old divine potion appearances)

### ISSUE THREAD

**Issue by parasailer** [runelite/runelite#12058]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to override ItemIDs the same way that we can with overriding SpriteIDs or WidgetIDs. This means that it is not possible to -- as an example -- create a plugin in the Plugin Hub where one could revert the appearance of divine potions (and egniol potions) to their pre-July 2020 look.

**Describe the solution you'd like**
Ideally, I'd like for developers to have the ability to override ItemID sprites freely with custom images. 

**Describe alternatives you've considered**
AFAIK there is no alternative currently for the proposed behavior (asked in the RL Discord and it was confirmed to not be possible with the current limitations).

**Additional context**
Here is my current implementation of such a plugin (just trying it out): https://github.com/parasailer/old-divine-potions
I realized that the sprite overriding didn't work, which is when I turned to Github/Discord for more answers.

**Comment by abextm** [comment]
duplicate #7954
