### ISSUE TITLE
Critical Security Issue

### ISSUE THREAD

**Issue by aghfshds** [runelite/runelite#12069]
On the Runelite website, when I log into my account, I noticed that it saved all of my login emails and login usernames. This is extremely worrying, as Runelite does not have 2FA and if they somehow access my Runelite account, they'll gain all of my emails, which is equivalent of subjecting my account to endless recovery requests. It appears right under "Account" in pictures.

I request we be able to change this information to our in-game names to mask this issue or replace it with a randomized number/letter sequence.

![YGy26xJ](https://user-images.githubusercontent.com/67884113/86548575-ea515b80-bf0a-11ea-9326-34d74d5726b8.png)

**Comment by Nightfirecat** [comment]
Google has 2FA. Also this is a duplicate of #8050
