### ISSUE TITLE
Runelite weird bug

### ISSUE THREAD

**Issue by bardockjr** [runelite/runelite#12074]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I'm really not sure what I would say is happening with this bug thats why I decided to make my own post about it.

**To Reproduce**
It starts as soon as I use any of the side plugins.

**Expected behavior**
https://gyazo.com/eb7c5f6ac6f6db860406d730ca3b789d

**Screenshots**
https://gyazo.com/eb7c5f6ac6f6db860406d730ca3b789d

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.21.1
 - Launcher version: 2.1.3

**Additional context**
N/A

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
