### ISSUE TITLE
HiScore plugin: Show barbarian assault gc

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#12076]
It would be nice to see the Barbarian Assault high gamble count in the hiscores along the boss kc. It is essentially the kc equivalent in that minigame. The functionality to get the number is already somewhere implemented, for example it is shown when using the !gc chat command. The Penance queen pet could be used as the icon, similar to other boss pets shown there. It could be helpful to see other players gc when setting up BA teams.

**Comment by Nightfirecat** [comment]
The hiscore plugin is not meant to show data that we can't look up on the hiscores. If Jagex adds BA high gamble counts to their hiscores, we will add it to the plugin.
