### ISSUE TITLE
Quick chat skill guide option

### ISSUE THREAD

**Issue by Ezea10** [runelite/runelite#12089]
**Is your feature request related to a problem? Please describe.**
As someone who isn't necessarily fond of using chat commands due to a slight disability of my left arm, I would find it extremely beneficial to be able to say my levels in public chat without having to type out !lvl thieving. 

Adding this toggleable feature to the skill guide would also allow for a quicker way to say said level.

**Describe the solution you'd like**
A right-click quick chat **TOGGLEABLE** feature added to the skill guide to display level to public chat.

**Additional context**
![download](https://user-images.githubusercontent.com/62921327/86999395-55976980-c167-11ea-9eba-270b8f47c460.png)

**Comment by Nightfirecat** [comment]
This would be a macro, which is not allowed by Jagex.
