### ISSUE TITLE
Improve readability of texts inside info boxes

### ISSUE THREAD

**Issue by molteber** [runelite/runelite#12085]
**Is your feature request related to a problem? Please describe.**
Info boxes with counters or timers can have a little bit of visual difficulty. Mostly because the text of blending with the image in the info box.

Here is an example of a bit difficult text to read at instant:  
![image](https://user-images.githubusercontent.com/8125386/86899983-03285f80-c10b-11ea-8b7b-b9a64ad282d4.png)

**Describe the solution you'd like / Describe alternatives you've considered**
I have been a little premature and made a pull request to add outline to absorption points in NZM  #(#12083), but have also decided to try other solutions, hence this issue.

**Suggestion # 1**: The solution I've proposed in the PR, outlining the text:  
![image](https://user-images.githubusercontent.com/8125386/86900001-09b6d700-c10b-11ea-8784-7137becfd60d.png)

**Suggestion # 2**: Add a transparent gray* background behind the text in the infobox:  
![image](https://user-images.githubusercontent.com/8125386/86899876-da07cf00-c10a-11ea-8324-c7890a376725.png)

\* Could be configurable, but I assume gray will work for most.

**Comment by pushaton42** [comment]
Can I 2nd this one please? I have an Astigmatism and the bright green text on the white part of the Slayer boost background strains my eyes heavily.
![slayerboo](https://user-images.githubusercontent.com/71233306/93028311-0d6e4a80-f5e1-11ea-93e3-b786583eca27.png)

**Comment by Nightfirecat** [comment]
I don't think we're likely to add the second proposal as it does not look good. That said, adding a text outline is certainly possible [as is shown in Adam's comment](https://github.com/runelite/runelite/pull/12083#issuecomment-675590328) which we'll likely add

**Comment by pushaton42** [comment]
Yeah that's understandable. I'm just backing the fact it needs better readability in general so an outline or being able to change the color of the text or something would be nice.
