### ISSUE TITLE
Avernic defender not counting towards bank value

### ISSUE THREAD

**Issue by mleves10** [runelite/runelite#12081]
Currently, avernic defender doesn't count towards bank value.

I feel like it would be appropriate to make the avernic defender have the same value in the bank as an avernic defender hilt would.

**Comment by Nightfirecat** [comment]
This is intentional. You cannot turn an Avernic defender into cash in any way, so it does not add anything to your bank's value.

**Comment by Broooklyn** [comment]
This is intentional iirc since the avernic defender can not be reverted back to a hilt
