### ISSUE TITLE
Shift Click NPC Menu Swapper

### ISSUE THREAD

**Issue by Faets** [runelite/runelite#12086]
This idea stems from Chinchompa training and slayer training on enemies that are stacked and hit with a multi-hit spell/attack. The idea is simple, have a plugin that adds shift clicking as a way to change between "Always right click" and "Left Click where Available". Just an easy way to stack enemies without accidentally attacking them and ruining the stack.

**Comment by Bram91** [comment]
This would be against the following rule jagex mentioned in their statement:
`Removes or deprioritises attack, cast (or similar) options from the minimenu in any scenario`

The full statement can be found here:
https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1
