### ISSUE TITLE
ReEquip Last Gear Button

### ISSUE THREAD

**Issue by Yewish1488** [runelite/runelite#12102]
Have a button in the bank where when you deposit your equipped items they are "tagged" with a randomly generated code that when clicked a second time would withdraw and equip those exact items (provided they are still in your bank of course).

Example: You are killing green dragons wearing full rune armor with a rune dagger because you're challenged when you suddenly get a hard clue scroll. Your first step is to go into the place for challenged people called the wilderness. Everything is falling into place but you don't want to risk your equipped gear nor inventory so you can bank all, but can't as quickly equip it all upon returning. This button would bank your inventory or equipment (two separate buttons), tag them temporarily, and then upon returning to click the button withdraw and equip exactly those tagged items. An added bonus would be returning your inventory items right where they were prior.

The same can be achieved with inventory tags and setting up a gear slot but this would offer a quicker alternative with less clicking and would also rearrange your items were they were prior if possible. Plus you don't need to set up 20 tabs so you have a unique green dragon nonwilderness tab, etc.

**Comment by Nightfirecat** [comment]
This feature request would be considered macroing/botting, so we cannot implement it.
