### ISSUE TITLE
Elite clue step broken

### ISSUE THREAD

**Issue by xRyanCat** [runelite/runelite#12107]
Edit: Possible user error.

Note: I completed the clue on mobile, which brings up a pop-up box. I realized after submitting, this bug may be user error, and its simply that the desktop Runescape UI doesn't have the same pop-up. 

**Describe the bug**
Elite clue step does not work in Runelite. "Input number box" to complete doesn't appear. 

**To Reproduce**
Elite clue. Step 0. Anagram: Old Crone. Question/Answer clue. Answer: 619.
Talk to Old Crone. 
She says "Answer this."
Nothing happens.
Clicking clue does nothing.
Clicking on Old Crone again makes her say "Answer this."
Clicking clue again does nothing.
Repeating either clicking the Old Crone or Elite clue does nothing. No new objects are added to inventory.
The clue step cannot be answered in Runelite.

**Expected behavior**
If you open the same clue in Vanilla client/Mobile client, the clue works. This clue seems to be specially coded by Jagex. Rather than give you a 'new clue' object that has the question, and answering the question to the NPC. The question is answered by clicking on the original clue object. 
Click clue in vanilla.
A dialog box pops open to answer the question.
Enter answer: 619.
Clue successfully completes.

**Screenshots**
None.

**Environment (please complete the following information):**
 - OS: Windows 10 updated
 - RuneLite version: 1.6.21.1
 - Oldchool: rev 190
 - Launcher version: 2.02

**Additional context**
client.log: Attached below.

[client-copy.log](https://github.com/runelite/runelite/files/4905945/client-copy.log)

**Comment by Nightfirecat** [comment]
Nothing in the logs indicates an issue happening here. We don't do any kind of menu entry swapping for clue scrolls so I'm not sure how you would have experienced what you're describing.

**Comment by MarbleTurtle** [comment]
Having gotten this clue I was unable to replicate the issue, its standard for elite clues to replaces the existing clue while lower tiers give you a challenge scroll, but clicking on the clue opens the challenge without issue.
