### ISSUE TITLE
Pet cat plugin

### ISSUE THREAD

**Issue by 984514566554** [runelite/runelite#12114]
A complete plugin for your pet cat. 

- Notify whenever your kitten is hungry or needs attention
- Infoboxes with timers till next actions
- Pet kitten growth timer infobox to Cat
- Cat growth timer infobox to Overgrown Cat
- Wily cat reversal timer infobox to Lazy Cat
- Cat hitpoints threshold notification while fighting Hell-rat behemoth/King rat
- Cat training NPCs highlight/indicator
- Configurable Hell-rat behemoth indicator or colored highlight according to the appropriate spice color

**Comment by Nightfirecat** [comment]
Duplicate of #3815
