### ISSUE TITLE
Runelite freezes as soon as GPU is enabled and side bar constant sidebar glitch

### ISSUE THREAD

**Issue by Panda1785** [runelite/runelite#12113]
**Describe the bug**
I can no longer load Runelite with GPU enabled, it instantly freezes while loading the log in screen. 
I can load Runelite with GPU disabled and log in etc.. but as soon as I enable, it freezes.

Have uninstalled and installed RL a number of times, no luck. (If I download the 32 bit, it will instantly close rather than freeze while loading.)

I have uninstalled suggested programs that may clash such as 'Alien command center' 
I have tried adding --mode=off and disabling acceleration as suggested here:
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

I have played around with the 3d settings (all quite new to me) but nothing seems to make a difference. 

**Screenshots**
![image](https://user-images.githubusercontent.com/68154047/87225765-29f2ca00-c387-11ea-9e83-7611a0f090a7.png)

**Environment (please complete the following information):**
 - OS: Windows 10   
 - RuneLite 1.6.21.1 (launcher version 2.1.3)

I have a Dell G7 laptop
Nividia - GeForce GTX 1660 Ti  

[client.log](https://github.com/runelite/runelite/files/4906877/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4906878/launcher.log)

Any help would be appreciated! I've looked all over here and reddit etc and I can't find a solution! This is the only game I play and I'm eager to get back online! Thank you.

**Comment by Nightfirecat** [comment]
Have you followed our troubleshooting page? This entry sounds like what you're describing. https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-closing-when-loading

**Comment by Hydrox6** [comment]
Closing since stale, and this should have been done through the support channel
