### ISSUE TITLE
http api is responding with 403 error for xtea requests

### ISSUE THREAD

**Issue by jdknox** [runelite/runelite#12116]
The http api for xtea requests is responding with 403 errors.

**To Reproduce**
1. Go to http://repo.runelite.net/net/runelite/http-api/maven-metadata.xml
2. Get latest version
3. Go to https://api.runelite.net/runelite-1.6.21.1/xtea (version 1.6.21.1 is latest as of this issue creation)

I can try to pinpoint when it stopped working if that would be helpful.

**Comment by Nightfirecat** [comment]
We haven't served xtea data for some time intentionally.

**Comment by jdknox** [comment]
Ah, ok.  I tried searching for xtea issues before posting, but didn't see anything right off...
