### ISSUE TITLE
Agility rooftop course laps per hour inconsistencies

### ISSUE THREAD

**Issue by AndreasBoegh** [runelite/runelite#12125]
**Describe the bug**
Laps per hour is inconsistent to the true laps per hour see screenshot for example

**Expected behavior**
Doing my example of 1 hour of laps on agility course for example 1 hour doing 64 laps. Should yield a 64 laps per hour estimate

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/32385164/87293313-6991f100-c502-11ea-8ad6-51c85d085097.png)

**Comment by Cyborger1** [comment]
The agility plugin estimates laps per hour from the 10 previous lap completions. The discrepancy would be from slowing down slightly for the last 10 laps of the hour.

I'm not sure this counts as a bug, but the behaviour could be communicated to the player.

**Comment by Nightfirecat** [comment]
10 laps seems like a very small amount considering it's cheap to increase that number and prevent people from thinking the estimation is as wrong as it is sometimes.
