### ISSUE TITLE
Time tracking plugin shows inaccurate info when farming plot contains diseased crop

### ISSUE THREAD

**Issue by malstad** [runelite/runelite#12124]
**Overview of the Issue**
The issue pertains to the farming contract aspect of the Time Tracking official plugin. This plugin normally gives the status of the plot you're currently assigned to using an infobox overlay in the upper left corner of the screen. The infobox includes the estimated time until growth is complete if the correct plant is currently growing already. 

Specifically, if the plant is diseased when user logs in, it will report that the plot is ready to be harvested, even if it's not usually the time it would be finished had it not become diseased.

**Java Version and Operating System**
_(copied from About tab in client)_
Runelite version: 1.6.21.1
Oldschool revision: Rev 190
Launcher version: Unknown

**Reproduce the Error**
1. Plant seed/sapling according to current farming contract in empty plot
    a. Ideally plant a snapdragon seed after receiving a snapdragon as a contract assignment (unsure if necessary step)
2. Use ultracompost from bottomless bucket (unsure if necessary step)
3. Logout within the farming guild
4. Log back in after at least one growth stage has occurred

Expected: Infobox overlay in upper left should show that the contracted plot is diseased and must be cured (perhaps warning yellow text instead of white or green) else the crop will be lost. If not, at least show the actual time remaining as if it were not diseased.

Actual: Infobox overlay shows the name of the plant in green and status of "Ready" also in green (see screenshot below)

![image](https://user-images.githubusercontent.com/3912318/87268278-d499e400-c47e-11ea-9f29-957454256a44.png)

**Comment by Cyborger1** [comment]
I am currently testing a fix for this.
