### ISSUE TITLE
Launcher issue

### ISSUE THREAD

**Issue by Laufijs** [runelite/runelite#12126]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
<a href="https://gyazo.com/ad2d4c8c8952ebdd9637e16f5500a3e2"  target="_blank"> Gyazo Gif </a>
**To Reproduce**
1. Opened the laucher, it loaded everything
2.Launcher opens, but is empty ?
**Expected behavior**
That I'd be able to play and use Runelite.

**Screenshots**
Gif above showing the issue.

**Environment (please complete the following information):**
 - OS: Windows 10, with the latest update.
 - RuneLite version: 1.6.21.1
 

[client.log](https://github.com/runelite/runelite/files/4913571/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4913572/launcher.log)

**Comment by Nightfirecat** [comment]
Please upload your `launcher.log` and `client.log` files

**Comment by Laufijs** [comment]
Found the issue, while playing F76, it changed resolution and sent the launcher off the "desktop's edge" , dragged the edge of tool belt and the launcher popped out, feel so stupid atm, thanks for trying.
