### ISSUE TITLE
How to detect a game object being removed

### ISSUE THREAD

**Issue by fartliquid** [runelite/runelite#12135]
I'm trying to detect the despawning of a game object using a GameObjectDespawned event but the client is registering the object as despawned even though it still appears on the client.

![6gnN3hmfIK](https://user-images.githubusercontent.com/68258771/87406827-a2b28a00-c604-11ea-896b-8365b40d0251.png)

I want to be able to tell when the exit crystal (ID: 30017) in the above picture opens, removing the object. The logs below the client show the ID's of despawned Game Objects, and the crystal's ID is repeatedly despawned while still there on the client before finishing the kill.
`
@Subscribe

	public void onGameObjectDespawned(GameObjectDespawned event)
	{
		if(event.getGameObject().getId() == TEKTON_END) //30017
		{
			//do this
		}
	}`
Am I using this the wrong way? What's the best way to detect this?

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) and use the development channel for questions of development.
