### ISSUE TITLE
Clue Scroll Plugin: Beginner clue scroll map step has an incorrect hint

### ISSUE THREAD

**Issue by Blastburn94** [runelite/runelite#12139]
**Describe the Bug**
A beginner clue scroll step for a map has an incorrect description. The hint states "South West of the Champion's Guild" but the location is actually west of the Champion's Guild. Traveling south west would take you across the river, which is wrong.

**To Reproduce**
1. Get a beginner clue scroll with the map step shown in the screenshot while the clue scroll plugin is enabled in RuneLite.
2. Confirm that the hint is stating to travel in the wrong direction from the Champion's Guild.

**Expected Behavior**
The hint should say to travel west, not south west from the Champion's Guild.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/7637340/87446186-f69e7e00-c5c6-11ea-96ae-912db15e5f76.png)
![Map Clue](https://user-images.githubusercontent.com/7637340/87446198-faca9b80-c5c6-11ea-82b6-e1f216ceeaf5.png)

**Environment**
 - OS: Windows 10 Professional 64-Bit Version 2004
 - RuneLite version: 1.6.21.1
 - Launcher version: 1.5.2

**Comment by Hydrox6** [comment]
Note: this is also a possible Easy clue scroll
