### ISSUE TITLE
Changing font size or using a "cleaner" font for ground items

### ISSUE THREAD

**Issue by MeLikeChoco** [runelite/runelite#1214]
Right now the font looks very pixelated and it's kind of hard to read from a distance away. I recommend font size and/or font size options with a "cleaner" font for ground items. If possible for other stuff too like the text when you mouse over stuff.

**Comment by SoyChai** [comment]
RuneLite's small fonts were actually a big thing I noticed when I first tried it out, because they're rather squinty compared to other clients whom I believe use the action menu font?

**Comment by deathbeam** [comment]
Hmm, yeah, we use the smaller version of the font for tooltips and ground items. I guess it might be worth switching to the regular sized version?
