### ISSUE TITLE
Not drawing item name on screen for ground items

### ISSUE THREAD

**Issue by jordan-git** [runelite/runelite#12145]
**Describe the bug**
Item names for items tagged by the ground items plugin randomly stopped working

**To Reproduce**

**Expected behavior**
Item names to appear on screen above tile as usual

**Screenshots**
![RuneLite_NwcTcBb3Rg](https://user-images.githubusercontent.com/19174130/87460438-c83f9380-c604-11ea-8df2-bd42a9965c89.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.21.1
 - Launcher version: 2.1.3

**Additional context**
I have tried resetting the plugin settings and nothing changed. Screenshot shows a tile highlighted by "Ground Items", yet the name of the item does not appear.

**Comment by Alexsuperfly** [comment]
double tap alt

**Comment by jordan-git** [comment]
> double tap alt

That fixed it! Thanks.
