### ISSUE TITLE
Loot Tracker misses coins if they're dropped in 2 stacks

### ISSUE THREAD

**Issue by cmcerove** [runelite/runelite#12159]
I wasn't able to find a similar bug by searching. I tried looking for coins, gp and gold.

**Describe the bug**
I just got a double drop of coins from Vorkath where only one of the stacks shows up in loot tracker. This is the first time I've noticed the issue so I'm not sure how often. Unless there's a 16-bit limit on the amount of coins loot tracker tracks, it seems suspicious the amount is the maximum value for a 16 bit number.

**To Reproduce**
1. Pray to rng gods to give you a double drop of coins for testing this.
2. Receive double drop of coins.
3. Observe only one of the two drops shows up in loot tracker.

**Expected behavior**
I expect that all loot is tracked.

**Screenshots**
![Screen Shot 2020-07-16 at 7 41 10 AM](https://user-images.githubusercontent.com/7104313/87667592-a2b3a680-c738-11ea-872e-7ceda594c4b4.png)
![Screen Shot 2020-07-16 at 7 45 21 AM](https://user-images.githubusercontent.com/7104313/87667444-58cac080-c738-11ea-8a04-3ae4f323818c.png)
![Screen Shot 2020-07-16 at 7 44 49 AM](https://user-images.githubusercontent.com/7104313/87667453-5cf6de00-c738-11ea-85ca-5d897a2331a8.png)

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.6.21.1
 - Launcher version: 2.1.2

**Comment by Hydrox6** [comment]
The loot tracker tracks item drops. Item stacks on the ground have a limit of 65535, as you can see.

**Comment by Hydrox6** [comment]
There's probably 2 main reasons:
* The engine was made in 2004, and data was more limited back then.
* Item stacks on the ground only need quantities to be able to use the right model for different quantities. Coins, for example, have differing models all the way up to 10,000. If it's entirely for this, I'm not too sure why the limit is so high; maybe they wanted to future proof it?

Maybe someone else knows the actual reason :shrug: 

Either way, this limit rarely causes issues. iirc, from non-player related events, this can only ever happen at Vorkath and Hydra.

**Comment by abextm** [comment]
Duplicate #1387

**Comment by cmcerove** [comment]
Ah, okay, I thought you were saying it was a runelite limitation. Thanks for the explanation.
