### ISSUE TITLE
Add Chronicle charges to Daily Task Indicator

### ISSUE THREAD

**Issue by Wakahisa** [runelite/runelite#12154]
You are allowed to buy up to 100 chronicle charges a day.

Having a notifier if possible would be useful.

**Comment by Cyborger1** [comment]
I have an implementation for this written [in this branch](https://github.com/Cyborger1/runelite/tree/daily-chronicle). I will be testing it to make sure it works properly and open a PR when I'm confident it has no issues.

Anyone feel free to clone my branch and try to find issues with it, it'd be much appreciated.
