### ISSUE TITLE
Plugin that shows progress on Make-10s

### ISSUE THREAD

**Issue by GitAlt** [runelite/runelite#12167]
Is it possible to get a plugin, or a status icon (like the ones for boosted stats, worn ammo, minigame teleport timer, boss respawn timers etc) for the progress you're making on Make-10 actions? Such as fletching headless arrows, making broad arrows etc? A counter down from 10 to 0. There might be other actions such as enchanting bolts? Maybe others can pitch in on that. 

On top of that, would it be possible to get some sort of dedicated alert to it that lets you know when you can earliest start making another set of 10, like a sound cue as opposed to a visual cue that the suggested counter would be. So either when that counter disappears or reaches 0, or you hear a toggleable sound cue, you can start another action.

**Comment by Nightfirecat** [comment]
The [Action Progress plugin on the hub](https://runelite.net/plugin-hub/show/action-progress) does this.
