### ISSUE TITLE
Inventory tags being a small bar under the item instead of fully outlining the item. 

### ISSUE THREAD

**Issue by WizardMascot** [runelite/runelite#12164]
I would love to see the beautiful items uninterrupted, and the inventory tags -- although insanely useful -- are really [ugly.](https://gyazo.com/3076da87b0357241a590adeac3737247)

**Comment by Nightfirecat** [comment]
Can you be more clear? I don't understand what the issue is

**Comment by WizardMascot** [comment]
I am sorry I put this in the wrong place..
