### ISSUE TITLE
Track the date you last collected your Miscellania kingdom

### ISSUE THREAD

**Issue by alexclifford** [runelite/runelite#1216]
I like to collect from my kingdom every 3 days, which I track myself currently. If it were possible for RuneLite to tell me when this is that would be very helpful.

**Comment by alexclifford** [comment]
@Infinitay what branch is this in? I can give it a test also.

**Comment by Infinitay** [comment]
I'll push it to my existing PR if you'd like to help give it a go, maybe you can help see if there's any flaws #1267

**Comment by alexclifford** [comment]
I ran up this PR branch and it loads. I don't see the Kingdom popup though and can't edit the configuration at this time. When I click on the red X to enable it nothing changes in the interface and IntelliJ reports errors like:

>2018-04-04 19:48:56 [pool-2-thread-1] WARN  n.r.client.config.ConfigManager - unable to set configuration item
java.net.SocketTimeoutException: timeout

**Comment by alexclifford** [comment]
It might be a more general issue with my IntelliJ setup though as I've also noticed I can't search in the stats lookup either. XP tracker seems to work. GE lookup does not.

**Comment by Infinitay** [comment]
I haven't worked on it since the push, if you could wait that'd be nice, as the current push didn't implement code to track when you collect.

I was waiting till I could collect my rewards again, which should be a few hours from this message as according to OSRS wiki, it says rewards reset the same time you completed the quest

**Comment by alexclifford** [comment]
Is there anything else I can help test on this one to look at getting it into this or next week's Release?
