### ISSUE TITLE
Tag tab icon search omits Infernal Cape

### ISSUE THREAD

**Issue by Broooklyn** [runelite/runelite#12174]
**Describe the bug**
Only `Infernal Cape (broken)` shows when searching for `Infernal Cape` in the tag tab icon-search. Per a discussion in Discord, this is possibly due to `Infernal Cape` and `Infernal Cape (broken)` having the same model, but with different ambient lighting. That said, `Infernal Max Cape` and `Infernal Max Cape (broken)` both show up when searched, just not the regular `Infernal Cape`. 

According to a friend of mine, this is a regression as you used to be able to set it properly, although I don't have confirmation of when. Whenever the change happened it reportedly removed the tag tab if it had been set to the Infernal Cape icon.

**To Reproduce**
1. Create a tag tab
2. Right-click and `Change icon`
3. Search for `Infernal Cape`
4. Note that it only displays the broken version

**Expected behavior**
To be able to set a tag tab icon to the regular Infernal Cape.

**Screenshots**
<img width="311" alt="Screen Shot 2020-07-16 at 10 01 02 PM" src="https://user-images.githubusercontent.com/54762282/87740321-e695c280-c7af-11ea-9b0e-c7a4a5e132a9.png">
<img width="367" alt="Screen Shot 2020-07-16 at 10 02 13 PM" src="https://user-images.githubusercontent.com/54762282/87740430-2ceb2180-c7b0-11ea-87c5-c4a258da23f1.png">
<img width="322" alt="Screen Shot 2020-07-16 at 10 02 03 PM" src="https://user-images.githubusercontent.com/54762282/87740431-2d83b800-c7b0-11ea-8d1e-5c856d869b61.png">

**Environment (please complete the following information):**
 - OS: All
 - RuneLite version: 1.6.22

**Comment by mikearche** [comment]
I'm unable to repro this on RuneLite 1.6.26.

**Comment by Nightfirecat** [comment]
We're not on 1.6.26... :thinking:

**Comment by mikearche** [comment]
I was on 1.6.26-SNAPSHOT. I tested on 1.6.25 and am still unable to repro.
