### ISSUE TITLE
[Suggestion] Clipboard Pasting Functionality on the Login Menu. 

### ISSUE THREAD

**Issue by FakeDavid** [runelite/runelite#12176]
I use a password manager to keep track of all my passwords, and most of these passwords are randomly generated. I do not know a single one myself. I rely on pasting them from my clipboard into a password field on websites. These password managers come with 'Auto-Type' features which could help on OSRS, but as you could imagine, that may not be the smartest way to go about using them.

I would simply like the ability to paste my password from my clipboard into the OSRS client under the condition that the player is not logged in. A simple CTRL+V would do.

I understand that copying and pasting your passwords is not a significant security measure when phishing and keylogging is taken into account, however, simply having a unique password for every single account IS. With the amount of accounts some of us have... it can get pretty annoying trying to remember them all. This is a simple QOL request that will promote at least a basic level of internet security.

**Comment by loldudester** [comment]
This is already a feature of the default Oldschool client

**Comment by FakeDavid** [comment]
> This is already a feature of the default Oldschool client

I didn't know this. However, after 5 minutes of posting this, I found the 'Login Screen' plugin which allows paste functionality... wow. 

Closed.
