### ISSUE TITLE
Xp Drop Color

### ISSUE THREAD

**Issue by Potionboost** [runelite/runelite#12189]
Under the 'XP Drop' settings on Runelite there are 3 options for changing the colour of xp drops to correlate with a certain activated offensive prayers, however the coloured xp drops do no work if the 'hide skill icons' with in this setting is 'un-ticked'. this meaning that you would have to have skill icons turned on in order to see the coloured text. This however was not always the case as you could have skill icons turned off and still get coloured text before. I think this bug may have happened in a recent RL update.

**Comment by Broooklyn** [comment]
I believe this has been fixed for next release

**Comment by Adam-** [comment]
this has been fixed in 4e3c887e878012949019ebcb2747b32e07bb9bdf
