### ISSUE TITLE
Withdraw bank items by tag?

### ISSUE THREAD

**Issue by Astronought** [runelite/runelite#12195]
Hi all,

I'm curious if this is a feature that has been considered before (perhaps technically it isn't possible but I'm not familiar with the limitations of runelite's API), but essentially I would love to be able to withdraw all items by a particular tag.

This would be super useful for things like withdrawing different gear set ups for slayer/bossing or even just farm run supplies. 

I envision the option being potentially added to the right-click menu of tag tabs, or perhaps when right clicking on an item that has a tag so that having a tag tab wouldn't be required.

Any thoughts?

**Comment by Alexsuperfly** [comment]
this would be basically botting which is against the rules
