### ISSUE TITLE
Menu entry swapper plugin swaps talk-to and pickpocket on all NPCs

### ISSUE THREAD

**Issue by XrioBtw** [runelite/runelite#1219]
The menu entry swapper plugin is currently swapping talk-to and pickpocket on all NPCs that have these options. This means that we are swapping talk-to and pickpocket on pollnivnian bandits and menaphite thugs. Is this something we want to do? On the other hand we are swapping talk-to and pickpocket on every custom named level-2 man (Woman, Cuffs, Narf, Rusty, Jeff, etc.).

Could someone provide a complete list of every NPC that has this option swapping in other clients? If Konduit and OSB is swapping options on blackjacking NPCs then I guess we don't have to do anything.

If we choose to change this, would we go for `!target.equals()` or `target.equals()` or something else?

**Comment by ShaunDreclin** [comment]
Yeah I was thinking we may want to consider blocking the blackjack npcs from the menu entry swapping, if I do it then `!target.equals()` would be the way to go.

**Comment by Infinitay** [comment]
I personally don't find an issue with "swapping talk-to and pickpocket on pollnivnian bandits and menaphite thugs" because it doesn't also swap to knock-out.

And as far as I know, you can't **simply** swap knock-out, so once again, i dont see a point

**Comment by ShaunDreclin** [comment]
If you position the camera correctly, the knock-out option appears directly under the cursor on right click. that would let you blackjack without moving the mouse

**Comment by Infinitay** [comment]
Does OSB/Konduit support menu entry swapping to easily pickpocket? If not, then okay I see where you guys are coming from and I agree

**Comment by ShaunDreclin** [comment]
I know osb has an option for it but idk if it works on blackjack ones, that'd be something to check.

**Comment by sethtroll** [comment]
Fixed in #1305

**Comment by husky3g** [comment]
Made an account just to necro. is this ever going to be reimplemented as an "optional" feature? This comes in handy so well when training AFK pickpocketing.

**Comment by MarbleTurtle** [comment]
When this was active Jagex had not provided guidelines that directly state this feature would have been allowed, and referencing #1305 it was actually merged which is why this was closed, current day this is not a feature that can be added back into RL without breaking the guideline that Jagex provided.
