### ISSUE TITLE
Slayer kill tracking subtracting too many kills since multikill support

### ISSUE THREAD

**Issue by Ley-line** [runelite/runelite#12192]
**Describe the bug**
After the implementation of the slayer multikill tracking support, it's possible for it to subtract too many kills. I suspect this has to do with the Expeditious Bracelet (Don't know if this is also bugged with Bracelet of Slaughter).

**To Reproduce**
Haven't been able to reproduce this yet, since you need a slayer task and some pretty good RNG.

**Expected behavior**
When the bracelet procs it subtracts 2 kills for each monster it procs on, instead of one. But when 2 monsters die at the same time and the bracelet only procs on one of them, 4 kills are subtracted instead of 3. Again, I suspect this is the issue but I can't confirm for 100%. I noticed this when my counter dropped to 0 (as seen in the screenshot), when my task had not yet finished.

**Screenshots**
https://puu.sh/G8s1x/1a1f038154.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.22
 - Launcher version: 2.13

**Comment by Krysaczek** [comment]
I was bursting Abyssal demons yesterday in barrows gloves and had this happen also. I noticed the remaining kills tracker going up from 34 to 37 after checking through slayer helmet.

**Comment by Adam-** [comment]
I've just done a full dust devil task without bracelets, and the counter was correct the whole time. So this is probably limited to bracelets if it is a problem at all.

**Comment by Nightfirecat** [comment]
I can also confirm having done a full burst task of jellies without issue--without bracelets.

**Comment by Esption** [comment]
This happens without the slayer bracelets for sure.  AFAIK always counts too many kills (like overlay says 23 left but really 24 left), and I've just assumed it's due to slayer rules around ironman.  Curious if the other people saying they see it are ironmen too?

**Comment by adragon0216** [comment]
Thermy seems to count for 2 kills pretty commonly. No bracelet just killing it normally.

**Comment by emiljensen2** [comment]
I'm using slaugther bracelets while barraging abby demons, and it bugs out as well. I've seen it go as far as -17 before my task actually finished.

**Comment by Adam-** [comment]
We've figured out this issue is specific to abby demons and has to do with the way they teleport at the same time as dieing, which delays their death

**Comment by Adam-** [comment]
fixed in 1f6ae893d732cf3a022fe6d9662cd2a42ff2b217
