### ISSUE TITLE
Add Pleading emoji to runelite

### ISSUE THREAD

**Issue by Mxnki** [runelite/runelite#12198]
The title says all 
![0ce9053a1b52719a8982a9b3bbd7ee3d](https://user-images.githubusercontent.com/68596112/88053808-b443e680-cb5c-11ea-9164-e31a371555cf.png)

**Comment by Hydrox6** [comment]
As with all emoji requests, provide a trigger version of it. We do not accept colon-codes (so no \:pleading\:). You can see current ones [here](https://github.com/runelite/runelite/wiki/Emojis#emoji-reference).

**Comment by OneProGoober** [comment]
Hi,

Working on this. I didn't see a trigger but I felt that n_n was appropriate. Let me know if you think it should be different and I will update it as so.

**Comment by abextm** [comment]
Closed by #12203
