### ISSUE TITLE
RS3 style examine

### ISSUE THREAD

**Issue by AildirMike** [runelite/runelite#12196]
Possibility to add a hovering textbox with the examine text over, around or near the object that is being examined? Sort of like in RS3?
![Unicorns](https://user-images.githubusercontent.com/51796970/87934121-b9d2fb00-ca8e-11ea-968c-7a53423e4a82.png)

Thanks in advance!

**Comment by mrboots123** [comment]
#12233

**Comment by Hydrox6** [comment]
Whoops, this shouldn't have been closed by plugin-hub#500

**Comment by mrboots123** [comment]
#12248

**Comment by mrboots123** [comment]
#12250
