### ISSUE TITLE
Remember camera position on world hop

### ISSUE THREAD

**Issue by Gwiggle** [runelite/runelite#12193]
**Is your feature request related to a problem? Please describe.**
When you world hop your camera resets to down and facing north

**Describe the solution you'd like**
Remember camera position so when you world hop it would reset to last known position

**Describe alternatives you've considered**
I mean it's a simple request. Either it can be done or it can't

**Additional context**
N/A

**Comment by Gwiggle** [comment]
Unable to edit post at all to give it a label. Apologies

**Comment by Adam-** [comment]
this was added awhile ago in c9f5f93b52f42098845c7e6871bb984a1979dec6
