### ISSUE TITLE
Editing a tag tab item's tags does not honor remove tag separators

### ISSUE THREAD

**Issue by Broooklyn** [runelite/runelite#12207]
**Describe the bug**
Editing a tag tab item's tags makes previously-removed bank tab separators visible again until reentry into the tab.

**To Reproduce**
1. Enable `Remove tab separators` in `Bank Tags` plugin
2. Open the bank and click on a tag tab.
3. Right-click an item and select `Edit tags`.
4. Note that when the search window pops up, the separators return until you unselect and reselect the tag tab.

**Expected behavior**
It is expected that the separators would always be removed if the setting is enabled.

**Video**
https://streamable.com/aobef1

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.6.23 (master)
 - Launcher version: n/a

**Comment by Nightfirecat** [comment]
Since the plugin has been significantly refactored, this no longer occurs for me on release. Please reopen if you can reproduce.
