### ISSUE TITLE
Ground item count in right click menu is wrong

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#1220]
It looks like it counts the first stack of items and assigns it to also second stack of items.

![image](https://cdn.discordapp.com/attachments/404427878076514304/429984194215673866/runelite_maths.png)

**Comment by EvanWalden** [comment]
I also ran into this, but on further inspection the behavior of the game itself here is really weird. It actually doesn't matter which of the two menu item you click on, you'll always pick up the same pile.

To reproduce this: kill a goblins until it one drops 5 gp then drop a different amount of gp on the same pile. Regardless of which menu option you pick, you'll always get the 5gp the goblin dropped.

If you do the same backwards (Kill a goblin on top of an existing gold pile) you'll always get the existing gold pile.

**Comment by zeruth** [comment]
Can easily be explained with an Item array. When requesting to pickup an item, it doesn't specify which stack, only the item you are grabbing. it finds the first item that matches your request in the array (first drpooed)
