### ISSUE TITLE
Examiner marked by clue plugin isnt clue related

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#12205]
This Examiner is marked for the clue plugin but she doesnt give the puzzle box

![image](https://user-images.githubusercontent.com/55747379/88204519-bf147f00-cc21-11ea-8998-9cb1c3a33401.png)

**Comment by Broooklyn** [comment]
The wiki says `You might need to talk to several different examiners.`

**Comment by Nightfirecat** [comment]
Duplicate of #3164
