### ISSUE TITLE
Menu Entry Swapper for Construction

### ISSUE THREAD

**Issue by StonedNaruto** [runelite/runelite#12211]
Ability to swap "walk here" with "build _____" and also ability to swap "walk here" with "remove ______" 

I noticed that you already have a Menu Entry Swapper, but no options for construction, And since I'm doing this construction grind right now. I thought this might be a good suggestion.

**Comment by Hydrox6** [comment]
Banned by the [Jagex Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1)
