### ISSUE TITLE
Runelite ELO system for LMS

### ISSUE THREAD

**Issue by FrogTamer** [runelite/runelite#12227]
Since Jagex is not interested in pvp anymore, maybe Runelite can open up a new avenue for PvP by simply creating its own ELO system for LMS and host games such as title matches and tournaments. This would be a great benefit for PvP since as of right now since theres no competition, while giving Runelite the opportunity to take initiative in the PvP content (Although I know Runelite is just a client with rare event fabrication, the chance of pushing PvP forward and to the wider audience would be an opportunity worth considering).

I'm not sure on how the statistics would be shown, but it would be apparent where the bots will dot on the ELO system, making it much easier to determine which players in LMS are botting.

ELO system Ideas:
- A discord channel which is for checking out your ELO advancement. A command like !ELO(Name) would show a graph which displays your progression. (or maybe even on a Runelite plugin)
- ELO hiscores
- Competitive Tournaments
- Titles at certain ELO ranks, expressing prowess
- Future PvP prospects

**Comment by abextm** [comment]
Same issues as #5146
