### ISSUE TITLE
Saved Interface Layouts

### ISSUE THREAD

**Issue by HughRaynor** [runelite/runelite#12232]
**Is your feature request related to a problem? Please describe.**
When toggling between fixed and resizeable modes, any interface components that are not assigned to one of the boxes does not move. This is problematic for users who place their infoboxes in the pillars next to the inventory.

**Describe the solution you'd like**
An ideal solution would be to allow user-defined presets for interface layouts, which would automatically (or manually) change the layout to match the currently selected game mode.

**Describe alternatives you've considered**
An alternative would be to add one of the preset boxes that components snap into to the pillars, which would automatically do this.

**Additional context**

![image](https://user-images.githubusercontent.com/6563035/88486849-915c6c80-cf78-11ea-8c89-dba8660e647b.png)
The infoboxes aligned for resizeable mode.

![image](https://user-images.githubusercontent.com/6563035/88486867-a5a06980-cf78-11ea-9462-904dd0262705.png)
The result of switching to fixed mode.

**Comment by makingcomment** [comment]
#11657
