### ISSUE TITLE
A % chance for a unique in the raids overlay

### ISSUE THREAD

**Issue by Steve-07** [runelite/runelite#12235]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Hydrox6** [comment]
The `Raid Points Overlay` plugin on the [Plugin Hub](https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub) does this.
