### ISSUE TITLE
Replace jewelry bank reminder

### ISSUE THREAD

**Issue by MESLewis** [runelite/runelite#1223]
An overlay that is displayed when you open the bank after a charged jewelry breaks / becomes uncharged.
The overlay would display the icon of the item which depleted as a reminder to withdraw a new one.

Would be very useful for dueling ring and glory runecrafting and other activities relying on repeated use of jewelry teleports.

**Comment by deathbeam** [comment]
Duplicate of #1223 (adding configurable option to show the infobox at 0 charges, probably in red would solve this).
