### ISSUE TITLE
Inventory Setup categories 

### ISSUE THREAD

**Issue by Smeety** [runelite/runelite#12239]
When looking through my inventory setups, I've got quite a lot now, and it would be nice to put them into categories like a skilling and pvm category - it would also be nice to color the names in the inventory setups tab :)

**Comment by Nightfirecat** [comment]
Inventory Setups is a hub plugin, and not supported by the main development team. Please open this request on that repository. (you can find it by clicking the support link found on its entry in the client or by [clicking the link on the plugin hub page on our website](https://runelite.net/plugin-hub/))
