### ISSUE TITLE
Essence Running > Runner Settings > Highlight Trade Binding with "26 (pure)" is not highlighting.

### ISSUE THREAD

**Issue by ItsHeavy** [runelite/runelite#12242]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
In the plugin named Essence Running (vanilla plugin), there is a setting that will highlight an item in inventory when it notices via trade with a client that they have a certain number of inventory spaces left. In Running Settings drop down, and option Highlight Trade Binding and option "26 (pure)", it is supposed to highlight the Binding Necklace in _your_ inventory when it notices via trade that the other individual only have 26 spaces remaining in their inventory. It will still highlight for Highlight Trade Binding and option "25".

**To Reproduce**
1. Go to Essence Running > Runner Settings > Highlight Trade Binding with "26 (pure)"
2. Click on a trade with another individual who has 26 empty spaces in their inventory, while you have one Binding Necklace in your inventory
3. Notice that the Binding Necklace in your inventory is not being highlighted, signifying an action is needed.
4. See error ^ of no highlighting.

**Expected behavior**
Previously, the Binding Necklace in your inventory would be highlighted via a red square. This action was meant to signify that the other individual needed said highlighted necklace due to the fact they have 26 empty inventory spaces.

**Screenshots**

**Environment (please complete the following information):**
 - OS: All OS (have various users that have submitted the same issue). However, Windows10.
 - RuneLite version: most recent version [1.6.24]
 - Launcher version: unknown how to locate and difference.

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

[client.log](https://github.com/runelite/runelite/files/4989326/client.log)

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
