### ISSUE TITLE
Kingdom of Miscellania reminder

### ISSUE THREAD

**Issue by MrJudly** [runelite/runelite#12241]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I think it would be an awesome addition to have a Kingdom of Misc reminder added to the plugin daily tasks indicator as people like me keep forgetting :)

**Describe alternatives you've considered**
I did check the kingdom plugin but doesn't seem to be able to be done on there.

Let me know what you think - Jed

**Comment by Hydrox6** [comment]
Duplicate of #10939

**Comment by BrandtHill** [comment]
@MrJudly I've implemented this feature in pull request 10933 (linked issue 10939). It's been awaiting final review for approval for a few months. Check it out if you're interested
