### ISSUE TITLE
Performance Issues [FPS] on a new laptop.

### ISSUE THREAD

**Issue by qwertywatsu** [runelite/runelite#12240]
Hi, my Runelite client’s FPS drops from 50 to 20-30 most of the time when I go to instances such as CoX, or even when I zoom out of my poh. I am using the GPU function with 40 render distance and AA off. My friends who also use this client don’t experience issues like these with much lower specs for their system. 

My CPU is 9th gen i7-9750H, GPU is RTX2070 8gb, RAM is 16gb ddr4, and my Runelite is installed in my SSD.

When I open my taskbar, I can see Runelite only consuming around 15-20% of my computers power. I have also made sure to set my laptops power mode to high performance. I have also disabled the G-SYNC function of the monitor to increase my fps in other games. 

Is there any way to optimize/fix my game so that it stays at 50fps consistently?

Thank you!

**Comment by weiwang11** [comment]
Make sure you're using your Nvidia GPU for your java application as laptop tends to run Java on the integrated GPU instead.

**Comment by MESLewis** [comment]
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.
