### ISSUE TITLE
GPU crash - monitor flicker then client crash

### ISSUE THREAD

**Issue by dabezian** [runelite/runelite#12252]
Logs attached below.

Was doing 2t teaks in Priff for about 1 hour before the crash. I had the issue several times before but a GPU driver update fixed it. My entire monitor will flicker "black" then come back and RuneLite is gone. 

GPU: MSi RTX 2070 SUPER
CPU: AMD Ryzen 7 3700x

[client.log](https://github.com/runelite/runelite/files/4998217/client.log)
[launcher.log](https://github.com/runelite/runelite/files/4998220/launcher.log)

**Comment by Nightfirecat** [comment]
Do you have a hs_err_pid or jvm_crash_pid file in your logs folder after the crash? I don't see anything in your client log regarding that crash.

**Comment by dabezian** [comment]
No, I only have client.log and launcher.log archive files. Is there any where else that errors would dump to?

**Comment by dabezian** [comment]
I found crash logs on in Event Viewer

Event 1000 Application Error
Faulting application name: RuneLite.exe, version: 0.0.0.0, time stamp: 0x5b50f2ae
Faulting module name: nvoglv64.dll, version: 27.21.14.5167, time stamp: 0x5f021eb1
Exception code: 0xc0000409
Fault offset: 0x00000000010f6fc9
Faulting process id: 0xd94c
Faulting application start time: 0x01d66a00c1cba8e7
Faulting application path: C:\Users\Brandon\AppData\Local\RuneLite\RuneLite.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_edab19158bdd0d0a\nvoglv64.dll
Report Id: 597a9afa-6301-4f8d-80f3-bd153b360919
Faulting package full name: 
Faulting package-relative application ID: 

Event 1, NVIDIA OpenGL Driver
Unable to recover from a kernel exception. The application must close.


Error code: 3 (subcode 2)
 (pid=55628 tid=22992 runelite.exe 64bit)

Visit http://www.nvidia.com/page/support.html for more information.

**Comment by dabezian** [comment]
I resolved the issue with the following action:

NVIDEA Control Panel -> 3D Settings/Manage 3D Settings -> Global Settings/Power Management Mode = Prefer maximum performance

The same issue has happened to streamer 25x_, so it's not an isolated incident, seems to be a client issue with the GPU plugin.

**Comment by BlitzAceSamy** [comment]
Just had the same issue; never had it before. My Event Viewer stated the following:
"The GPU has been disconnected and this application may become unresponsive. Error code: 10 (pid=50000 tid=31588 runelite.exe 64bit) Visit http://www.nvidia.com/page/support.html for more information."

Tried changing the setting as stated above, fingers crossed this doesn't occur again!
