### ISSUE TITLE
Minimap Stuck in the middle top of the screen on Ultrawide

### ISSUE THREAD

**Issue by larsy1995** [runelite/runelite#12257]
When using my new ultrawide 3440x1440 monitor, the minimap hovers in the middle of the screen, obstructing xp orbs and other things.
The rest of the UI does move to their appropriate locations, but the minimap does not.

**Comment by Alexsuperfly** [comment]
alt right click it

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
