### ISSUE TITLE
Clue Scroll Plugin: Add reminder to return items to stash after clue step

### ISSUE THREAD

**Issue by Marstead** [runelite/runelite#12254]
**Is your feature request related to a problem? Please describe.**
Frequently I will complete an emote clue step and forget to return my items to the clue stash before progressing to the next step. The relevant stash is highlighted in red for an active clue step, but the stash highlight goes away once the step is complete (and the items need to be returned to it).

**Describe the solution you'd like**
When an emote clue step is completed, if the player still has the exact set of items from that clue step in their inventory or equipment, add red reminder text to the clue overlay listing the items and reminding the player to return them to the stash. Continue to highlight the stash in red until the stash is refilled.

**Describe alternatives you've considered**
Alternatively, a new always-on STASH plugin could work the same way. This STASH plugin could highlight stashes based on whether they are built, built but not filled, or built and filled. This way a player can quickly see if they forgot to re-fill any stash tab.

**Comment by tpsteiner** [comment]
I came here to ask for the same feature. I forget to return STASH items almost every time, resulting in the stashes wasting time rather than saving time.

**Comment by Adam-** [comment]
This is not so straight forward to do since there is no var for us to tell if the stash unit is filled or not (hence why the checkmark only shows whether its "built")

**Comment by vitorebom** [comment]
Would it be too awkward for it to check if "A" clue scroll/casket is in the inventory and then look for the emote clue items equipped/in inv for that specific tier and then display an arrow on the closest, visible, stash unit if it matches the items found?

**Comment by Marstead** [comment]
> Would it be too awkward for it to check if "A" clue scroll/casket is in the inventory and then look for the emote clue items equipped/in inv for that specific tier and then display an arrow on the closest, visible, stash unit if it matches the items found?

I think something like that could work, because we know the locations of STASHes, we know which items each unique STASH requires, and we know the player's location, and we know what's in the player's inventory. 

So maybe a Plugin that checks if you are within X tiles of a STASH and then highlights any items in your inventory that are required for that STASH? It might end up highlighting extra items that you coincidentally have in your inventory when near a relevant STASH.
 
To reduce the chance of it highlighting when it's not relevant, to your point I think you could also make it so that it checks if you have a clue scroll or casket in your inventory first before highlighting anything. And/or it could only highlight if you have *all* of the required items in your inventory/equipment and not if you have partial items.

@Adam- , thoughts?
