### ISSUE TITLE
ESC not working on RL

### ISSUE THREAD

**Issue by FrostJTS** [runelite/runelite#12260]
Having an issue on Runelite, all of a sudden ESC will not close any of my interfaces. I didnt change any settings and they are all correct on runelite and on actual runescape. It isnt my ESC button either because it works on everything else including the OldSchool Client, just not on runelite, anyone have this issue at all?

**Comment by Bram91** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://www.runelite.net/discord) for questions or support.

**Comment by FrostJTS** [comment]
Another point to add is it does work when i hold shift which is weird. If anyone has any idea let me know thank you
