### ISSUE TITLE
"Cast Bloom" Menu Entry Swap on Silver Sickle (b)

### ISSUE THREAD

**Issue by Ckmpls** [runelite/runelite#12278]
**Is your feature request related to a problem? Please describe.**
Its annoying having to right click and select "cast bloom" on an object im never realistically going to "weild"

**Describe the solution you'd like**
Menu swap the wield and cast options

**Describe alternatives you've considered**
X

**Additional context**

**Comment by Hydrox6** [comment]
Duplicate of #1848
