### ISSUE TITLE
Allow the ground items plugin to create multiple groups of color-coded items

### ISSUE THREAD

**Issue by ExpnandBanana** [runelite/runelite#12274]
Being able to tag ground items with multiple colors would make identifying item types at a glance much simpler. At the moment you can only highlight items in one group or color-code by value. Attached is a concept I made in Photoshop to show what it could be used for.
![image](https://user-images.githubusercontent.com/46093712/89125258-3a402580-d4ab-11ea-8753-f15a84f2f05e.png)

**Comment by dasangrypanda** [comment]
This would be an awesome and helpful feature, especially for irons who often care less about the value of an item and may want to make groups based on their needs. Didn't see any dev comment on here yet, so just wanted to say that this is also a feature that I'd like to see.

**Comment by Sidrathx** [comment]
I would also like to see something like this added to the ground items plugin. It's a great concept and I think that it would make identifying items on the ground a lot easier at a glance.

Please let this be a thing!

**Comment by Pushkasuggests** [comment]
this would be extremely helpful to ultimate ironmen when sorting their deathpiles as well!

**Comment by Adam-** [comment]
added in bd05ac363c074f9d11469111932f9538d6393e34
