### ISSUE TITLE
Bridges not appearing in Port Piscarilius Sewers

### ISSUE THREAD

**Issue by FiniteEnds** [runelite/runelite#12275]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Bridges aren't appearing in the Port Piscarilius sewers.  These were discovered while doing the Queen of Thieves quest.

**To Reproduce**
1. Go to 'Port Piscarilius sewers'
2. Walk west.
3. See missing bridges (or don't in this case).

**Expected behavior**
Bridges to appear such that I know how to walk to the west to the sewer camp.

**Screenshots**
See screenshots here: https://imgur.com/a/ow9U7KG

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.23
 - Launcher version: 2.1.0

**Comment by Alexsuperfly** [comment]
turn off low detail

**Comment by FiniteEnds** [comment]
Perfect!  Issue solved!
