### ISSUE TITLE
Hover over chat text + CTRL-C to copy

### ISSUE THREAD

**Issue by fennecOS** [runelite/runelite#12282]
Was looking around to see if there was a translator plugin, saw it was on the feature request

Being able to CTRL-C while hovering over text from another language so we can paste into translator may be an easy workaround until we could possibly get a real time translator.

Can also be used for other things. Could also add configuration options to copy the time, name, and whether or not it was in public, cc, or pm.

Sorry if this is a duplicate.

**Comment by Nightfirecat** [comment]
There is already a right-click copy to clipboard feature which is sufficient for this I think.
