### ISSUE TITLE
Cadava berries GE limit changed

### ISSUE THREAD

**Issue by thevesylum** [runelite/runelite#12288]
The GE limit of Cadava berries was changed pretty recently. It used to be 15, and RL still shows that as the item's 4 hour limit. The new GE trade limit for Cadava berries is 200.

**Comment by Adam-** [comment]
The buy limits are synced from the official OSRS wiki weekly, so it should be changed there if it is incorrect.

**Comment by thevesylum** [comment]
I just did that like 30 minutes ago, 10:4
