### ISSUE TITLE
Bracelet of Slaughter charge resets to 30 on every proc

### ISSUE THREAD

**Issue by MattRKing** [runelite/runelite#12299]
I have been bursting Nechs while wearing a Bracelet of Slaughter (and having a spare in my inv) and have noticed that everytime the bracelet procs and uses a charge, the charge counter resets back to 30.  After it resets to 30 I have to check the bracelet again to correct it, only for it to occur again on the next proc.

Issue:
Bracelet charge count resets to 30 each time it procs.

Reproduce:
Have the correct charge count showing, and have it proc.  
Not sure if it only occurs when bursting or if it only occurs when you have a spare in the inventory.

Expected Behaviour:
Each time the bracelet procs the charge count should decrease by the amount of times it procs.  Eg: bracelet has 3 charges displayed, procs once, goes down to 2 charges displayed.

[Clip of it in action](https://drive.google.com/file/d/1G_m_4tHxd27xYKFJtmnTC3tZHwcby-HB/view?usp=sharing)

Windows 10
Latest version of the client (dunno how to see what version exactly, sorry)

**Comment by Adam-** [comment]
We think this is due to the message which is shown when the bracelet activates having changed?

**Comment by MattRKing** [comment]
I play on filtered so I wouldn't know if there is a message for each individual charge change.

**Comment by MattRKing** [comment]
Without the filter the prompt says: "Your bracelet of slaughter prevents your slayer count from decreasing.  It has x charges left."
