### ISSUE TITLE
Show minimum KC required for boss KCs on hiscore plugin

### ISSUE THREAD

**Issue by justin-nierendorf** [runelite/runelite#12291]
**Is your feature request related to a problem? Please describe.**
If you only have a few KC on a boss, it will not show on the hi-scores. It may be clearer to users if instead of showing "KC: 0" for an unranked boss, you show "KC: <50" (or <2, <10 depending on the boss)

This would also create an easy way for users to know what KC they need to be ranked for a certain boss. A frequent example I see is people asking what TOB KC they need to be ranked in the hi-scores.

**Describe the solution you'd like**
On the hiscore plugin, when you hover over a boss that you are unranked in, it will show "KC: < x" where x is the minimum KC needed to be ranked in the hi-scores. Currently, it shows "KC: 0" which can be inaccurate.
![image](https://user-images.githubusercontent.com/33694916/89306647-25e06200-d63e-11ea-898f-91291645d1e6.png)

KCs needed for a rank can be found on the wiki: https://oldschool.runescape.wiki/w/HiScores

**Comment by Nightfirecat** [comment]
We've addressed this in 2f85f574875f13ad60317ecfc2a4a79727ccef04 by not showing the KC line if the rank is unranked.
