### ISSUE TITLE
No Longer working: Big Sur Beta 4

### ISSUE THREAD

**Issue by austin-thesing** [runelite/runelite#12307]
Client loads up and stays stuck on this screen. I'd like to keep using it.
![CleanShot 2020-08-07 at 16 31 00@2x](https://user-images.githubusercontent.com/13810854/89696145-643e8100-d8cb-11ea-9a6a-1e064cbf51b0.png)

**Comment by Nightfirecat** [comment]
Duplicate of #11965

For now, disable your GPU plugin until Apple fixes whatever they broke in the beta. If this is still occurring once Big Sur is no longer in beta, we will investigate and address the issue.
