### ISSUE TITLE
Graphic Problem on Plug In Panel of RuneLite Client

### ISSUE THREAD

**Issue by UchihaRich** [runelite/runelite#12305]
Hello,

First time poster. When I hover my mouse over the right plugin panel I experience heavy graphic skips or double images making it impossible to view or use any of the plugins. I have uninstalled and reinstalled, updated all my graphic drivers, completed all available updates on my PC. When I double click the top bar of the client to make it full screen the plugin panel resets to normal, until I hover my mouse over it and then the same problem persists. 

Its driving my crazy when I am trying to track my loot. This problem does not occur on game play but specifically on the plug in panel. Hope you guys can help. Pictures attached below. 

Thanks. 

![skip 1](https://user-images.githubusercontent.com/69367129/89684096-c0070b00-d8c7-11ea-8e1f-f25705ac9259.png)
![skip 2](https://user-images.githubusercontent.com/69367129/89684102-c2696500-d8c7-11ea-8756-0eb89d86dfe7.png)

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

**Comment by UchihaRich** [comment]
Thank you for the proper direction.
