### ISSUE TITLE
Player Indicators: Add Bold font option

### ISSUE THREAD

**Issue by ErikHumphrey** [runelite/runelite#12304]
Similar to the Small/Regular/Bold "Font" options in the configuration for the RuneLite plugin, add the ability to configure the font weight in the Player Indicators plugin so that you can choose to have Bold overhead player names.

Potentially good first issue.

**Comment by pilino1234** [comment]
Setting the Dynamic Overlay Font in the RuneLite settings also affects the player indicators plugin, but also changes things like the FPS counter and ping indicator. Should these be settable independently or is this solution good enough?

**Comment by ErikHumphrey** [comment]
Thought I had that one on Bold so I thought it didn't affect it. Though it would be nice to customize it on a plugin-by-plugin basis, because I personally prefer almost every RuneLite overlay on Bold, it's good enough for now. Thanks!
