### ISSUE TITLE
Stopped working: Remember client position

### ISSUE THREAD

**Issue by Darookan** [runelite/runelite#12308]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Until 1.6.23, my windowed client was opening fine on Monitor 1. After latest update, it now loads at same position but on Monitor 2 (main display). I recall having this in the past but it seems it was fixed on 1.6.22.

Unchecking  "Remember client position", reloading client and checking again does nothing.

Nothing else has changed on my PC setup (i.e. no Windows updates, no hardware changes).

**Comment by Adam-** [comment]
The behavior was changed to reset the client position if it is partially off screen instead of completely off screen, due to users getting the client stuck in ways which they were unable to move or fix the size of it. Is your normal client position partially off screen?

**Comment by Darookan** [comment]
Hi Adam, thanks for your reply.
That makes sense! I had originally the client windowed and resized to the whole screen. It was probably a couple pixels over boundaries. After the update It was keeping the same size but loading on my second monitor (which is smaller resolution), hence i thought the issue had came back.

I just resized the client to one pixel smaller than the screen res and it worked!

Thanks for the info! 👍 This can be closed.
