### ISSUE TITLE
Font issue on startup?

### ISSUE THREAD

**Issue by revize-jpg** [runelite/runelite#12317]
Getting a client log when starting it up and it says "Error while loading! Please check your internet and DNS settings". DNS has been flushed, internet is fine (it works on my laptop), and it's still giving me this error. Anyone got any ideas?
[client.log](https://github.com/runelite/runelite/files/5048867/client.log)

**Comment by Nightfirecat** [comment]
Whatever program you're running is not the software we're offering. You're either running a fake RuneLite client or some derivative client. In either case, we cannot offer support for that--we recommend uninstalling the program you're using now, running virus scans, changing your passwords, then installing RuneLite from runelite.net. This is the only website we offer downloads from.
