### ISSUE TITLE
rubber cap teleport breaks object marker

### ISSUE THREAD

**Issue by botanicvelious** [runelite/runelite#12318]
If you take the rubber cap teleport to land on the mushy bed when woodcutting sulliuscep the object markers do not show up

1. mark some objects at the mushy bed
2. Go to the rubber cap on fossil island and take the teleport
3. The marked objects wont be marked 

**Expected behavior**
The marked objects to show marked

 - OS: Windows
 - RuneLite version: 1.6.24

**Comment by Adam-** [comment]
This is probably fixed in e5b5292267b3240f7320c05f4c232e4d66b0142b, reopen if it isn't.
