### ISSUE TITLE
Missing Maven Repositories + Other Issues [Fresh Installation]

### ISSUE THREAD

**Issue by ShieldDrop** [runelite/runelite#12312]
I'm currently trying to set up the RuneLite source to be able to start making my own plugins, but I'm getting multiple errors after following the set up guide.

I have pre-installed Java and Git before installing IntelliJ. After cloning RuneLite, when the IDE opens and begins installing everything in the project, I have an error "Cannot resolve plugin net.runelite:script-assembler-plugin:1.6.25-SNAPSHOT".

I've set the project SDK, but inside libraries, I'm missing every Maven "sources.jar" and "javadoc.jar" files. Below I will provide a couple screenshots, also the error in the class file occurs on any file opened. I'm assuming because of the missing repositories.

https://i.imgur.com/2oiXmrN.png
https://i.imgur.com/omkMeIB.png

I'm familiar with codex and I've worked in IntellJ for a couple years with AS3. Would appreciate any insight or help, thanks.

**Comment by Nightfirecat** [comment]
You need to build maven again. For future reference, [our `#development` channel in Discord](https://runelite.net/discord) is a better place to ask these kinds of questions.
