### ISSUE TITLE
The bank tag tab overview tab doesn't get a scroll bar

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#12313]
If you have a bunch of tag tabs, they no longer fit in one screen:
![image](https://user-images.githubusercontent.com/34870401/89716100-88bd5a80-d9aa-11ea-807e-cdb6ab86878f.png)
So I have to elongate my client to be able to see them:
![image](https://user-images.githubusercontent.com/34870401/89716105-8eb33b80-d9aa-11ea-906d-471dcd6b6389.png)
There is a scroll bar but it doesn't do anything currently.

**Comment by geheur** [comment]
fixed in #13761
