### ISSUE TITLE
Ferox Enclave breaks Menu Entry Swapper on the Jewelery Box

### ISSUE THREAD

**Issue by Evan-Murray** [runelite/runelite#12326]
Description:
Menu Entry Swapper allows you to left click the jewelry box to go to last location. However if your last location is Ferox Enclave, it doesn't work.

1. Enable Menu Entry Swapper
2. Under Object Swaps, check the box for the jewelry box.
3. Use jewelry box to go to ferox enclave.
4. Return to POH and notice you can't left click to go to ferox enclave.

Desired Outcome:
Left click to use the Jewelry box should still work if ferox enclave was your last destination.

 - RuneLite version: 1.6.24

**Comment by Nightfirecat** [comment]
This is fixed in master in commit 6998931f84964cf2071df23faaa495329e96e520
