### ISSUE TITLE
Highlight specific names on players, similar to NPC tags

### ISSUE THREAD

**Issue by GeneralIroh1** [runelite/runelite#12331]
Looking to see if it is possible to add the ability to highlight specific player names. Currently in the player indicator tab you can highlight friends, clan members, team cape, yourself and everyone else. I was hoping it could be added the ability to enter specific names you would like highlighted if they show up exactly like how you enter specific names for NPC indicators or taging and it is highlighted.

Thanks.

**Comment by Hydrox6** [comment]
This is [Rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features):
> Highlighting "Offline" Friends (and generic player highlighting): Not included to respect players with their messaging mode set to Private and to avoid harassing players
