### ISSUE TITLE
supply crate tracker

### ISSUE THREAD

**Issue by snitgaard** [runelite/runelite#12349]
**Is your feature request related to a problem? Please describe.**
There's recently been added a few new trackers for for example birds nests / seed packs, and it's kind of inconsistent that there hasnt been added one for Wintertodt supply crates, as I'd like to be able to track the loot I get from wintertodt over long periods of time.

**Describe the solution you'd like**
The loot tracker expanded to check and log wintertodt supply crates, just like how we've recently got Seed packs and Birds nests added to the loot tracker

**Comment by melkypie** [comment]
Duplicate of #5824
