### ISSUE TITLE
Bank Tag Tabs Close When Switching Withdrawal Type

### ISSUE THREAD

**Issue by jevonsp** [runelite/runelite#12346]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Bug**
When viewing a runelite bank tab on the left, clicking between note and item will make the rl bag tab disappear 

**To Reproduce**
1. Open Bank
2. Click a runelite bank tab (on the left)
3. click on note (withdraw as) while having been on item before
4. the tab closes

**Expected behavior**
I should be able to select note or item and still use the tab

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.24.1
 - Launcher version: 1.6.0

**Comment by raiyni** [comment]
This cannot be reproduced.

**Comment by drummerkid** [comment]
Just attempted to reproduce this and couldn't.

Can you go into more detail about your game settings (bank settings etc.) or perhaps provide a streamable of the problem occurring.

**Comment by jevonsp** [comment]
It was happening over and over, but I can't seem reproduce it either now,
