### ISSUE TITLE
Chat filter to remove mesages from players' heads

### ISSUE THREAD

**Issue by OilyHands** [runelite/runelite#12351]
**Is your feature request related to a problem? Please describe.**

The chat filter removes messages from public chat but they still appear above players' head. This is a bit of an eyesore at hotspots like lms/ge where there are gambling bots or infernal cape sellers spamming messages. Bit of an eyesore

**Describe the solution you'd like**
Messages no longer appear above the players' heads. 

**Describe alternatives you've considered**
Autoignore players saying a particular phrase. The former suggestion is preferred, since someone might say one of the prases who isn't a bot

**Additional context**

**Comment by Hydrox6** [comment]
The plugin already edits overhead messages to apply the filtering, including removing the entire message if the Filter type is set to Remove messages
