### ISSUE TITLE
Add alpha channel for configs with color options

### ISSUE THREAD

**Issue by discomethod** [runelite/runelite#12353]
Allow plugins that allow you to choose colors for marked tiles to include an alpha channel in the options.

As one specific example, the fishing plugin will automatically mark fishing spots, but its tile color selector does not have the `@Alpha` decorator and so no alpha value can be set.

Adding this alpha channel would match the behavior of the Ground Marker and Tile Indicator plugins.

**Comment by discomethod** [comment]
Plugins that do not have opacity enabled:
- Agility
- Drift Net
- Fishing
- Herbiboar
- Implings
- Player Indicators
- Pyramid Plunder
- Slayer

Plugins that do have opacity enabled:
- Cannon
- Ground Marker
- NPC Indicators
- NPC Aggression Timer
- Object Markers
- Tile Indicators

**Comment by pilino1234** [comment]
Is there any place where the ability to add opacity to tile indicators would be unwanted or cause problems?

I'd be willing to take this on, it seems like slapping `@Alpha` on the relevant config items should do the trick

**Comment by Adam-** [comment]
> 
> 
> Is there any place where the ability to add opacity to tile indicators would be unwanted or cause problems?
> 
> I'd be willing to take this on, it seems like slapping `@Alpha` on the relevant config items should do the trick

No. Many of our Color config options predate `@Alpha` is why they don't have it. There's probably some others.

**Comment by pilino1234** [comment]
Alright cool, then I might as well just add it to all the Color config options :+1:
