### ISSUE TITLE
Option to change potion color?

### ISSUE THREAD

**Issue by kultklassic** [runelite/runelite#12357]
Can you make an option to change the color of potions since some potions look almost exactly the same color as other potions? Or the ability to "mark" items like you can "mark" npcs and tiles?

**Comment by Hydrox6** [comment]
`Item Identification` can already do this, just with text instead.

**Comment by Nightfirecat** [comment]
Alternatively, `Inventory Tags` can mark items with an outline, so this feature you want already exists.
