### ISSUE TITLE
Discord Loot Logger

### ISSUE THREAD

**Issue by SirTowliee** [runelite/runelite#12365]
**Is your feature request related to a problem? Please describe.**
I'm not sure it's a problem but the current "Discord Loot Logger" plugin doesn't track loot you get from chests (Raids, Gaunlet, ToB)

**Describe the solution you'd like**
Just adding the ability to track loot from chests

**Describe alternatives you've considered**
A seperate plugin to just broadcast unique items you get from raids

**Comment by Alexsuperfly** [comment]
since that is a hub plugin not maintained by the RuneLite project, its normally requested that you open an issue on that specific plugins GitHub repository, you should be able to find that through the support link on the plugin
