### ISSUE TITLE
GPU Causing Client To Freeze

### ISSUE THREAD

**Issue by toxiconsortium** [runelite/runelite#12371]
I've tried all the options on the GPU FAQ page and I can't seem to figure out what to do from here. Whenever I turn on the GPU plugin, no matter what the settings of the plugin are, the client will "glitch" the game for a few seconds (images attached) and then completely freeze on screen. The music continues to play, unlike when the game crashes on its own and I can still turn off the plugin and close the client. The game itself is what messes up. AMD Radeon HD 5450 card in this computer with latest drivers on Windows 10.. I'm not great with computers so I don't really know what else to put other than that.
![screenshot](https://user-images.githubusercontent.com/69987782/90816620-97850500-e2fa-11ea-8d62-0e11239c2d9d.png)

**Comment by toxiconsortium** [comment]
I found pretty much the exact problem in [https://github.com/runelite/runelite/issues/11351](url) thread. I disabled the Compute Shaders option and this fixed all the glitching. However, now the draw distance no longer works (as stated in that thread).

I noticed a comment in that thread that said "Reverting 3b0bb05 and rebuilding the client fixed the issue... just like gonX mentioned." and was wondering since I have absolutely no idea what that means if someone could explain to me how to do just that and see if it fixes the issue? I understand it's a small issue on the grand scale of things but I would like to increase my draw distance for visuals if possible.

**Comment by toxiconsortium** [comment]
Did more digging and released that issue was referring to Linux OS computers. So I'm guessing the problem has now merged into the Windows version. If somebody with more technical knowledge than me could look into this, I'd appreciate it.

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest RuneLite release.
