### ISSUE TITLE
Mouse key remapping for mouse 4 and 5

### ISSUE THREAD

**Issue by ege420** [runelite/runelite#12370]
Sometimes you don't want to use your keyboard when you are dropping items or emptying/filling rune pouches.

To facilitate you could bind shift key to mouse 4 or 5. This would solve the problem.
![image (2)](https://user-images.githubusercontent.com/69967286/90763488-74a12380-e2ef-11ea-862b-febafb46f636.png)

:)

**Comment by Hydrox6** [comment]
Rebinding keys to the mouse (or vice versa) is not something we want in the client ([see here](https://github.com/runelite/plugin-hub/pull/372#issuecomment-643683260)). You're better off using an external program such as AHK or your mouse's software to remap your keys to do that.
