### ISSUE TITLE
Player Indicator plugin messes up menu entries

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#1237]
When enabled and one of the menu entries has been coloured, it messes up the menu entries with lookup/report. When clicking lookup/report it also doesn't seem to do anything.

Player indicators w/ draw non-clan member names disabled:
![image](https://user-images.githubusercontent.com/35824069/38182133-a01882d6-3637-11e8-936a-c3ef3be69f77.png)

Player indicators enabled w/ draw non-clan member names enabled:
![image](https://user-images.githubusercontent.com/35824069/38182112-6b784228-3637-11e8-9932-865515807186.png)

`[Thread-2] DEBUG net.runelite.client.callback.Hooks - Menu action clicked: MenuOptionClicked(actionParam=0, menuOption=Lookup, menuTarget=<col=ffffff>Player name<col=c0ff00>  (level-124), menuAction=UNKNOWN, id=1775, widgetId=0)`

`[Thread-2] DEBUG net.runelite.client.callback.Hooks - Menu action clicked: MenuOptionClicked(actionParam=0, menuOption=Report, menuTarget=<col=ffffff>Player name<col=40ff00>  (level-124), menuAction=UNKNOWN, id=1432, widgetId=0)`

**Comment by Adam-** [comment]
I think this is fixed by #1241
