### ISSUE TITLE
Runelite refuse to launch

### ISSUE THREAD

**Issue by madel-anis** [runelite/runelite#12384]
After the last update  "1.6.24.1" 
when I try to double-click on runelite nothing happen at all.

I tried to uninstall then reinstall runelite, but the issue still there.

Any help ?

**Comment by madel-anis** [comment]
[launcher.log](https://github.com/runelite/runelite/files/5126246/launcher.log)
here is the launcher log it is indicating that libraries are missing

"RuneLite\jre\bin\javaaccessbridge.dll: Can't find dependent libraries" 

i found this solution https://github.com/runelite/runelite/issues/9798
and i tried to install both of the links attached in the solution, the first successfully installed, but the second told me that i have a newer version of it, so it won't installed

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#unsatisfiedlinkerror-javaaccessbridge-32dll-cant-find-dependent-libraries

**Comment by madel-anis** [comment]
> https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#unsatisfiedlinkerror-javaaccessbridge-32dll-cant-find-dependent-libraries

ty very much
