### ISSUE TITLE
Boss Hiscores

### ISSUE THREAD

**Issue by stmsteele** [runelite/runelite#12393]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

Nothing major, the hiscores function of RuneLite doesn't seem to be tracking my boss killcounts, nor does it provide any hiscores information. Does not seem to affect every account i lookup. 

**To Reproduce**
1. Go to 'Hiscores'
2. Search any name (Specifically Farmin Jesus, is mine)
3. Scroll down to the list of bosses and their rank
4. See that it does not load my killcounts or show a hiscore

**Expected behavior**

I expected to look up my name and see where my kill counts rank amongst my friends; unfortunately mine seems to be the only one not loading properly. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by stmsteele** [comment]
Totally not urgent, but just a little something that i've been meaning to swing over here and mention.

**Comment by Nightfirecat** [comment]
You probably don't have enough boss kills to be listed on the hiscores. [That information is detailed here](https://oldschool.runescape.wiki/w/HiScores):

> To be featured in the Boss Killcount highscores, you will currently need to kill a boss or complete an activity at least 50 times. This is true for all bosses and Boss Killcount activities, except for Bryophyta, Chambers of Xeric: Challenge Mode, Hespori, Obor, Skotizo, The Corrupted Gauntlet and TzTok-Jad, which all require just 10 'kills' to be featured, and The Mimic and TzKal-Zuk, which just require 2 kills to be featured.
