### ISSUE TITLE
Sire timer broken in 1.6.25

### ISSUE THREAD

**Issue by tim880158** [runelite/runelite#12397]
I was doing sire on the old RL version and updated when the new version came I noticed the timer displays incorrectly.

**Describe the bug**
When you "wake" sire the timer appears counting down from ~30 seconds, but once you stun sire to attack his respiroators the timer disapears.

**To Reproduce**
Attack sire (you can attack sire with anything first, spell or ranged this does not matter i've tried both),
See timer appear
Stun sire with shadow spell
See timer disapear

**Expected behavior**
Only once you stun sire with a shadow spell should the timer appear counting down how much time he is stunned.

**Screenshots**
After the first attack
![](https://i.imgur.com/LzdmT5b.png)
After the stun
![](https://i.imgur.com/PTyvGur.png)

**Environment (please complete the following information):**
 - OS: win 10
 - RuneLite version: 1.6.25
 - Launcher version: 2.1.3

**Comment by abextm** [comment]
It looks like the id of the stunned phase is now 5888, and 5887 is it's awoken state

**Comment by gagepatton** [comment]
Mikearche our savior
