### ISSUE TITLE
Item Stats tooltips incorrectly showing Superantipoison duration as 12 minutes

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#12398]
The actual duration is 6 minutes

Thanks to `Gnomercey` on Discord for reporting this

**Comment by mnasra** [comment]
I was looking to fix this as my first contribution but I either can't seem to re-create this or it's already been fixed, just came here and drank a dose and it's coming up as 6 minutes:
![Capture](https://user-images.githubusercontent.com/22745261/91356791-1f31ae80-e7e8-11ea-9ca5-0c1898b6f29e.PNG)

**Comment by Nightfirecat** [comment]
this is in reference to the item stats tooltips, not the Timers plugin infobox. The code which defines these times is here: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/itemstats/potions/PotionDuration.java#L37
