### ISSUE TITLE
Graphical Bug Issues

### ISSUE THREAD

**Issue by hkbertoson** [runelite/runelite#12394]
When I try to open the side bar for Runelite. It will bug out. I have attached a video of the error in progress. I have uninstalled/reinstalled Runelite as well. I have tried clearing out the cache. 
Computer Specs are as follows:

Intel Core I7 - 9750 Hexa-Core running at 2.6GHZ
16GB of DDR4 Ram
256 GB SSD and 1TB HDD
Nvidia GeForce RTX2060

All of my drivers are fully updated. Not sure what else could be causing this? 

Had to ZIP the video. 
[RuneLite.zip](https://github.com/runelite/runelite/files/5127112/RuneLite.zip)

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by hkbertoson** [comment]
This fixed it. Thanks!
