### ISSUE TITLE
Interact-only click mode

### ISSUE THREAD

**Issue by ragsmaroon** [runelite/runelite#12409]
**Is your feature request related to a problem? Please describe.**
At blast furnace sometimes I misclick the ground around the chest, conveyor belt, or the collection part.

**Describe the solution you'd like**
I'd like there to be a toggle that only lets you click on interactable objects like mentioned above. If you click on the ground, you don't move there.

**Comment by raiyni** [comment]
This goes against the spirit of https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1
