### ISSUE TITLE
Filter for installed Plugin Hub Plugins

### ISSUE THREAD

**Issue by Jademalo** [runelite/runelite#12404]
**Is your feature request related to a problem? Please describe.**
It's impossible to filter the plugin list to only show plugins installed via the Plugin Hub, which would be useful for organisation.

**Describe the solution you'd like**
Add a filter to the search box that shows only plugins installed via the Plugin Hub

**Describe alternatives you've considered**
Another option would be having a button to enable/disable plugins from within the plugin hub interface, but this could potentially add confusion and ambiguity with regards to the difference between enabling/disabling and installing/uninstalling.

**Additional context**
![image](https://user-images.githubusercontent.com/386846/91379065-ba8f4780-e819-11ea-84e4-ae92c53ccd18.png)

**Comment by abextm** [comment]
You can configure, and therefore enable/disable, plugin hub plugins from the plugin hub panel, but enforcing a tag onto them is probably a good idea

**Comment by Jademalo** [comment]
![image](https://user-images.githubusercontent.com/386846/91379868-7e5ce680-e81b-11ea-9d97-bd1d5679334a.png)

The current issue with that approach is more a visual one - It's not obvious which plugins are enabled/disabled from this view. 

Adding that to this list would probably introduce a bit too much ambiguity between the difference of installing and enabling, so I do think it's probably better giving them a tag.

**Comment by Broooklyn** [comment]
Closed by ab8fb76cac590d79415e668c41c48687d9ceaf4d
