### ISSUE TITLE
64bit client for Runelite will not open on my PC - Help!

### ISSUE THREAD

**Issue by Iconiic** [runelite/runelite#12411]
I've always used the 64bit Runelite client on my PC to play OSRS. Never had any issues in the past. Until yesterday. I was unable to, and still am unable to open the 64bit client for Runelite. I am however able to open the 32bit version. I'm on a Windows PC, running more than good enough specs to play OSRS. I've noticed while playing on the 32bit client, I'm constantly dropping frames, where as before, with the 64bit client, I never ever EVER dropped frames, even in highly populated areas. I'm still unable to open the 64bit version of Runelite. If anybody has any solutions, it would be greatly appreciated. 

Thanks,
Iconiic

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
