### ISSUE TITLE
Filter Game Chat

### ISSUE THREAD

**Issue by loegare** [runelite/runelite#12416]
Could it be possible to add the ability to custom filter the game chat? i am getting messages that i would prefer to have filtered.

**Comment by mikearche** [comment]
That plugin already exists. https://github.com/runelite/runelite/wiki/Chat-Filter

**Comment by loegare** [comment]
> 
> 
> That plugin already exists. https://github.com/runelite/runelite/wiki/Chat-Filter

it doesnt work like that, it custom filters the public chats, and collapses game chat.
