### ISSUE TITLE
terminal-notifier not used (macOS)

### ISSUE THREAD

**Issue by markvl91** [runelite/runelite#12427]
**Describe the bug**
After having installed terminal-notifier through Homebrew using `brew install terminal-notifier`, RuneLite still uses osascript to show notifications.

I've noticed it works properly when launching RuneLite through the terminal (`open /Applications/RuneLite.app`), just not when launched normally.

Also, I've taken the liberty to add some debug logging to the Notifier class in development mode. It indicates that in this mode terminal-notifier is seen as available, but it doesn't seem to have a launcher version set, which causes the availability check to fail. The actual release version does have this set, which leads me to believe it's related to terminal-notifier not being available/accessible for whatever reason.

**To Reproduce**
1. Install terminal-notifier using Homebrew
2. Launch release version of RuneLite.app normally
3. Cause any notification to occur
4. See the osascript notification instead of a terminal-notifier one.

**Expected behavior**
Notifications should be fired through terminal-notifier instead of osascript.

**Screenshots**
<img width="824" alt="Screen Shot 2020-08-31 at 23 22 18" src="https://user-images.githubusercontent.com/5470392/91770618-c7c58100-ebe1-11ea-8816-2185b0c9a279.png">
<img width="382" alt="Screen Shot 2020-08-31 at 23 24 55" src="https://user-images.githubusercontent.com/5470392/91770666-dca21480-ebe1-11ea-8e59-7e7eb11ff91d.png">

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.6.25
 - Launcher version: 2.0.0

**Additional context**
No errors related to Notifier appear in the log.

**Comment by Adam-** [comment]
What do you mean exactly by `launched normally`? It requires it to be running in the launcher for it to identify terminal-notifier, so as long as the info panel has something for the `Launcher version` that should be enough for it to work.

**Comment by markvl91** [comment]
With launching normally I mean simply double-clicking the RuneLite app.

Am I misunderstanding how this is supposed to work? Just to be sure, a screenshot of everything:

<img width="1280" alt="Screen Shot 2020-09-01 at 00 32 37" src="https://user-images.githubusercontent.com/5470392/91775249-ebd99000-ebea-11ea-854b-a65c6dd20a89.png">

**Comment by Adam-** [comment]
That's strange. I think that must mean `isTerminalNotifierAvailable()` is returning false for some reason. You could try and add logging there to see (+ also remove the launcher version check).

**Comment by markvl91** [comment]
I've added logging there and removed the launcher version check, running it from source properly detects the availability of terminal-notifier and everything works flawlessly. Is there anything different in the (packaged) macOS release version that could cause it not to detect terminal-notifier?

Just to reiterate, if I launch the release version using `open` it also works fine. I'm completely blanking on why a 'normal' launch doesn't.

**Comment by Adam-** [comment]
Maybe the path is different when run from the shell vs otherwise. Where is terminal-notifier at? Maybe try symlinking it from /bin?

**Comment by markvl91** [comment]
It's located in `/usr/local/bin/terminal-notifier` as a symlink to wherever Homebrew installed it. MacOS SIP prevents modifying `/bin`, and I don't really want to disable that just to try that out. 

Could there be something else different in my system that could cause this to not work, or is terminal-notifier usage simply not working for any macOS RuneLite users? I sadly don't know anyone to check this with, maybe you do?

**Comment by Adam-** [comment]
There may be some users in #12417 who you could ask. Or @Broooklyn.  Its also possible this used to work and now has broken due to some OSX behavior change.  I'd be okay with checking `/usr/local/bin/` and maybe 1-2 other paths for terminal-notifier if we needed.

**Comment by Broooklyn** [comment]
It seems the issue revolves around Finder-launched applications not having access to `/usr/local/bin/` so it's unable to access the symlinked  `/usr/local/bin/terminal-notifier` or the original location.

Using ```sudo launchctl config user path /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin``` (and restarting afterwards) does enable terminal-notifier to work with the finder-launched release client, but that's probably not ideal.

**Comment by markvl91** [comment]
Thanks @Broooklyn for taking a look. I ended up fixing it by adding the following to the app bundle's Info.plist:

```<key>LSEnvironment</key>
<dict>
  <key>PATH</key>
  <string>/usr/local/bin:</string>
</dict>
```

Since changes in Info.plist aren't picked up automatically it also required re-registering the bundle with LaunchServices: `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -v -f /Applications/RuneLite.app`.

This seems like a reasonably targeted approach to fix the issue, maybe this could be incorporated as a solution. 

Thanks so much for the input and help!

**Comment by deathbeam** [comment]
Yea that sounds like good solution imo. The Info.plist is located here so opening PR for adding it there might be good idea: https://github.com/runelite/launcher/blob/master/packr/Info.plist
