### ISSUE TITLE
Plank Sack overlay

### ISSUE THREAD

**Issue by OilyHands** [runelite/runelite#12425]
**Is your feature request related to a problem? Please describe.**
Slight inconvenience reaching a MH destination/poh with an empty sack

**Describe the solution you'd like**
Overlay showing how many planks are left in your sack

**Describe alternatives you've considered**

**Comment by SirGirion** [comment]
There doesn't seem to be anyway to get this information exposed to the runelite API. There is no varbit associated with it nor does Jagex send a game chat message saying you've filled the sack. If you have any info to the contrary on how to tell that you've filled the sack let me know.

**Comment by thebubbsy** [comment]
@SirGirion The esspouch plugin avaliable on the plugin hub counts the amount of ess ID's in the inventory with the action of clicking fill on the essence pouch. The same thing could be applied for the plank sack to be able to count how many planks are put in.

**Comment by Nightfirecat** [comment]
It's worth noting that the hub plugin does a best-effort attempt to figure out the amounts contained in the pouches (and is usually correct) but cannot be 100% accurate.
