### ISSUE TITLE
Skybox not working in POH

### ISSUE THREAD

**Issue by Aero56** [runelite/runelite#12431]
**Describe the bug**
When in your POH the Skybox plugin doesn't work anymore.

**To Reproduce**
1. Enter your POH
2. Skybox is all black.
**Expected behavior**
A nice blue sky like everywhere else.

**Screenshots**
![image](https://user-images.githubusercontent.com/30606372/91867918-71ede900-ec74-11ea-8a88-fa50873fcb8b.png)

**Environment (please complete the following information):**
 - OS: Windows 7
 - RuneLite version: 1.6.25
 - Launcher version: 1.6.0

**Comment by Matthew-nop** [comment]
I was unable to reproduce this issue on my platform with the latest release. Skybox worked within my POH with the GPU plugin on and off.

- OS: Linux 5.4.61 (x86_64, Mesa)
- RuneLite version: 1.6.26.1

**Comment by makingcomment** [comment]
It looks like OP is using the new Hosidius house style. Maybe this issue is related to that?

**Comment by Matthew-nop** [comment]
Possibly, I wasn't testing with the same theme. Hopefully someone else who has it unlocked can try to reproduce this.
