### ISSUE TITLE
Discord "Time elapsed" reset when you start training something new.

### ISSUE THREAD

**Issue by CoopJax** [runelite/runelite#12438]
**Is your feature request related to a problem? Please describe.**
This is more of a fix but it's where, on the discord rich presence,  training times out after a set amount of time and the time elapsed at the bottom resets. It does not happen for new locations, just different forms of training reset it.

**Describe the solution you'd like**
I would like the time elapsed to stay the same no matter what you are doing to make it feel more synced to the gameplay.

**Describe alternatives you've considered**
Remove the time elapsed possibly? Not sure about any alternatives.

**Comment by Nightfirecat** [comment]
To be clear, this would be a request to have the plugin simply show your logged-in time instead of the duration you've been doing your current activity right? We could look into adding this with a toggle for the behavior.

**Comment by CoopJax** [comment]
Yes.
