### ISSUE TITLE
Grubby chest incorrectly tracks loot

### ISSUE THREAD

**Issue by BRhodes** [runelite/runelite#12440]
I noticed that grubby chests are appearing on the loot tracker now, but the loot does not appear to be getting tracked correctly.

Currently in the source (runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin) there is:
private static final String GRUBBY_CHEST_LOOTED_MESSAGE = "You unlock the chest with your key.";

There are 2 messages that are presented when looting the chest. For large KCs (>2000) this message is shown:
"You have opened the Grubby Chest lots of times."

**Comment by Adam-** [comment]
fixed in c774117d93eadcea367553c5d0c985d7a56bfc33
