### ISSUE TITLE
Typing caret (^) doesn't work

### ISSUE THREAD

**Issue by JonathanOuwens** [runelite/runelite#12447]
For me (and someone else ingame when I asked) shift+6 (^) doesn't work. Is it too late to fix this issue? It's been a problem for me since I started using RuneLite. And yeah, sadly, I don't know how to reproduce it.

I'm on Windows 10 and my keyboard is set to Dutch (Nederland) - United States (international).

**Comment by Hydrox6** [comment]
Sounds like one of the plugins with hotkeys has had a hotkey set to `^`. In the core client, this is probably the `Screenshot` plugin, and there are also some Hub plugins that have hotkeys (notably the `Zulrah` plugin), so have a look through them

**Comment by JonathanOuwens** [comment]
> 
> 
> Sounds like one of the plugins with hotkeys has had a hotkey set to `^`. In the core client, this is probably the `Screenshot` plugin, and there are also some Hub plugins that have hotkeys (notably the `Zulrah` plugin), so have a look through them

I don't have a screenshot hotkey set, and the problem has existed far before the plugin hub came out. :(

**Comment by JonathanOuwens** [comment]
I just went through all the plugins, (disabled, tried typing ^, enabled) none of them seems to be the culprit!

**Comment by Matthew-nop** [comment]
Also check to make sure there's nothing in the 'RuneLite' plugin configuration bound to '^' as well. I'm unable to reproduce this with a clean RuneLite installation, so it's most likely a configuration issue.

**Comment by Nightfirecat** [comment]
We've added some logging to the client which helps us identify hotkeys being pressed. Please launch the client with debug logging enabled and post your client logs after reproducing the bug again. You can follow [Method 1 or 2 of the Disabling Hardware Acceleration wiki page](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration#method-1-creating-a-shortcut), adding `--debug` as the argument instead of `--mode=OFF`

**Comment by JonathanOuwens** [comment]
Well, this is awkward... It suddenly works again! :D Someone must've fixed it in the last update!

Thank you mysterious stranger! And thanks to everyone else for helping :)

**Comment by JonathanOuwens** [comment]
Should I still send my debug logs? Where do I find them?

**Comment by Nightfirecat** [comment]
If it's working fine, then no need. If you need to find them in the future, you can do one of the following things:
* Open the screenshot directory (if you have access to client by right-clicking "Camera" button) and navigate 1 directory up and then open logs folder
* Navigate to `%userprofile%\.runelite\logs` on **Windows** or `$HOME/.runelite/logs` on **Linux** and **macOS**.
