### ISSUE TITLE
Add Dwarven Rock Cake to Menu Entry Swapper

### ISSUE THREAD

**Issue by markbmullins** [runelite/runelite#12445]
**Is your feature request related to a problem? Please describe.**
Having to right click the rock cake to guzzle in NMZ is annoying.

**Describe the solution you'd like**
Add Dwarven Rock Cake to Menu entry Swapper so guzzle can be the single left click option.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Broooklyn** [comment]
This is available in `NMZ Utilities` on the plugin hub

**Comment by markbmullins** [comment]
Interesting. I would think that is desired enough to be a core feature, especially since the plugin already exists.
