### ISSUE TITLE
Plug-in that lists which items in your bank can go into the costume room

### ISSUE THREAD

**Issue by Antobite** [runelite/runelite#12454]
A simple plug-in that searches your bank and lists which items will go in PoH the costume room. There's way too many items, it's hard to keep track and search your entire bank. Also, some items that you'd expect to go in the costume room actually don't (such as blessings, vestment cloaks, many other clue items).

**Comment by Graviton1647** [comment]
I can work on this the way I would go about it personally would just show it on the tooltip EG: Storage: Costume Room (Cape Rack)

**Comment by ChopinDavid** [comment]
Lookup "Costume Room Highlight"
