### ISSUE TITLE
Time tracking: "Show Relative Time" option no longer available

### ISSUE THREAD

**Issue by Darookan** [runelite/runelite#12451]
After this week's update, the "Show Relative Time" option was removed?
The Farming time track lists and infobox now show absolute times.

![image](https://user-images.githubusercontent.com/69372970/92292339-c93fd200-ef70-11ea-83a5-f2468c908bd2.png)

**Comment by Nightfirecat** [comment]
Select the "Relative" option of the `Time format` config.

**Comment by Darookan** [comment]
Thanks mate. The wiki may need an update in this case.
