### ISSUE TITLE
Next Combat Level tooltip empty

### ISSUE THREAD

**Issue by TheStonedTurtle** [runelite/runelite#12467]
With 97 defence an 94 prayer the tooltip does not display the levels require for 126cmb.
![image](https://user-images.githubusercontent.com/29030969/92367523-5e46e600-f0ab-11ea-9505-447f180df035.png)

Per Nightfirecat's investigation it seems that the issue is inside the CombatLevelOverlay and since neither 2 defence levels nor 5 prayer levels gets me 126 combat the overlay doesn't add anything.

```java
if ((hitpointsLevel + defenceLevel + hpDefNeed) <= Experience.MAX_REAL_LEVEL * 2)
{
    sb.append(hpDefNeed).append(" Defence/Hitpoints</br>");
}
// ...
if ((prayerLevel + prayerNeed) <= Experience.MAX_REAL_LEVEL)
{
    sb.append(prayerNeed).append(" Prayer");
}
```

**Comment by Adam-** [comment]
fixed in 6f60750c313d586b5130717c7b9b8dc2383aa319
