### ISSUE TITLE
Associating GrandExchangeOfferChanged events with a server side timestamp (if possible)

### ISSUE THREAD

**Issue by zumaad** [runelite/runelite#12469]
**Is your feature request related to a problem? Please describe.**
When a user logs out after having placed some offers in the GE and then logs back in we get the GrandExchangeOfferChanged events that occurred when the user was logged out. However, because there is no timestamp associated with these events, we don't know when they happened while the user was logged out. This poses a problem when calculating things that require knowing when an offer event came in, such as calculating the next ge limit refresh, etc.
 

**Describe the solution you'd like**
This may be impossible (not sure if the server even sends the timestamp of the offer to the client), but ideally there could be a timestamp associated with GrandExchangeOfferChanged events that represents when the offer changed (from the perspective of the server)

**Describe alternatives you've considered**
We currently timestamp the offer events as they come in while the user is logged in, but this doesn't solve the problem of events we receive on login that occurred when the user was logged out.

**Comment by Nightfirecat** [comment]
The client doesn't receive that data sadly.
