### ISSUE TITLE
Screenshot size issue with GPU and Stretched Mode plugins on Linux

### ISSUE THREAD

**Issue by mselchow** [runelite/runelite#12463]
Note: [11403](https://github.com/runelite/runelite/issues/11403) is the same issue for Windows, not Linux.

**Describe the bug**
When using RuneLite on Linux with GPU and Stretched Mode plugins, screenshot functionality only captures ~25% of the game window.

**To Reproduce**
1. Use RuneLite on Linux
2. Enable GPU plugin
3. Enable Stretched Mode plugin
4. Take screenshot

**Expected behavior**
Full-size client screenshot of entire window.

**Screenshots**
[https://imgur.com/a/j29YI4B](https://imgur.com/a/j29YI4B)

**Environment (please complete the following information):**
 - OS: Pop!_OS 20.04
 - RuneLite version: 1.6.26.1
 - Launcher version: 2.1.3

**Additional context**
I am using the .jar file on a 4K monitor with 200% desktop scaling.

**Comment by Matthew-nop** [comment]
I'm unable to reproduce this with the provided steps. Are you certain the scaling or desktop environment/window manager isn't the issue?

**Comment by mselchow** [comment]
Sounds like it might be if you're not able to reproduce it. I'm using Gnome and to launch RuneLite I use `GDK_SCALE=2 RuneLite.jar` after making the jar executable. Without the `GDK_SCALE` environment variable, RuneLite launches without scaling and is too small to read anything on 4K.

I'll see what other scaling methods for Java might work to see if it nets a different result. The screenshot with the issue looks to be exactly 1/4 the size of my screen, which would lead me to believe that it's directly associated with the upscale to 200% on my DE.

**Comment by mselchow** [comment]
> I'm unable to reproduce this with the provided steps. Are you certain the scaling or desktop environment/window manager isn't the issue?

If you try running the jar with `GDK_SCALE=2 ~/Games/RuneLite.jar` are you able to reproduce the issue?

I have tried a few other methods for scaling with Java (namely `java -Dsun.java2d.uiScale=2 -jar RuneLite.jar`) and while the initial RuneLite loading bar displayed appears as expected, it then closes and appears to launch a second process that is not scaled. As this secondary process is launched from within RuneLite, it doesn't seem like there's a way to address this by using the `jar` file.

**Comment by Matthew-nop** [comment]
I've just tried launching it with `GDK_SCALE=2` on my desktop and laptop. Neither have the issue without the environment var set, but both have issues with. My laptop (HiDPI, Mesa) has the same issue you've mentioned. My desktop (nvidia) seems to only render one quarter of the screen.
