### ISSUE TITLE
net.runelite.cache.Cache null error

### ISSUE THREAD

**Issue by JasonM97** [runelite/runelite#12475]
**Describe the bug**
net.runelite.cache.Cache is not working as expected. It only loads up to index 16 and then encounters a null because index 16 is empty. If I open the idx255 file and take a look at index 16 it's completely blank (screenshots). I'm not sure if it was always like this or something changed but the current code can't handle it being blank. I've tried deleting and downloading the cache again but it's still showing as blank.

**To Reproduce**
I opened RuneLite in IntelliJ and followed this tutorial: https://www.osrsbox.com/blog/2018/07/26/osrs-cache-research-extract-cache-definitions/

**Expected behavior**
Cache should be loaded without any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/15971253/92616416-2e0a6d80-f28c-11ea-9cd8-fe3020cc6917.png)
![2](https://user-images.githubusercontent.com/15971253/92616427-319df480-f28c-11ea-9921-7807d60dc940.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.27-SNAPSHOT

**Additional context**
When trying to read idx255 it seems like the 16th section is empty so it causes an error. I tried fixing it myself by skipping any section that's null and it mostly fixes it except when trying to dump sprites.

**Comment by Nightfirecat** [comment]
As was mentioned on Discord, the cache you were using was not full. Use the cache client (and not the game client) to get a full cache downloaded instead.
