### ISSUE TITLE
macOS full screen support

### ISSUE THREAD

**Issue by motorable** [runelite/runelite#12478]
There is a simple method to enable full screen when maximising the client on macOS.

We can add a key for Launch Services to change the [Application UI Presentation Mode](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-113616) from Normal to All Suppressed. I'm not familiar with Java and Packr, and can't see where I'd add this key before the JDK bundles the .dmg otherwise I'd submit a pull request. So I'm just going to show how I did it after it's been installed to the Applications directory.

`plutil -insert LSUIPresentationMode -integer 4 /Applications/RuneLite.app/ContentsInfo.plist`

The int 4 will suppress the menu bar and dock but will show the mouse in response to mouse movements. Here's a screenshot with the launcher maximised.
<img width="1440" alt="Screen Shot 2020-09-09 at 3 42 19 pm" src="https://user-images.githubusercontent.com/7337933/92677843-d7706280-f363-11ea-906b-81b57e4e7157.png">

--

**Comment by Nightfirecat** [comment]
> `LSUIPresentationMode` (`Number` - macOS) identifies the initial user-interface mode for the app.

The docs seem to indicate this would cause RuneLite to take up the full screen when started, as opposed to when it is maximized, which we would not want to do.

**Comment by motorable** [comment]
@Nightfirecat that's right. My solution was merely a workaround for users wanting some form of full-screen and can be achieved with relative ease. Ideally we'd use the com.apple.eawt library to access the native macOS full-screen. This Stackoverflow answer seems to be what I'm looking for: https://stackoverflow.com/a/8693890/1573326

**Comment by Adam-** [comment]
We already do this though: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/util/OSXUtil.java#L47

**Comment by motorable** [comment]
FullScreenUtilities.setWindowCanFullScreen doesn't seem to enable the window (gui). In lieu of an explicit full-screen toggle, we'd use control+option+f but that doesn't work. I might have time tomorrow to look closer at this -- haven't been on osrs for a few weeks

**Comment by motorable** [comment]
Enable native macOS full-screen in RuneLite:
 - disable custom window chrome in plug-in settings **RuneLite > Enable custom window chrome**
 - restart RuneLite
 - press the green button in the apps title bar or hover and select Enter Full Screen

<img width="913" alt="Screen Shot 2021-02-12 at 12 21 20 am" src="https://user-images.githubusercontent.com/7337933/107647637-49f6bd00-6ccb-11eb-923f-afff7f773ecc.png">
