### ISSUE TITLE
Error loading runelite, Even though I am sure it is the latest version. 

### ISSUE THREAD

**Issue by Psychotechnopath** [runelite/runelite#12470]
When starting  RuneLite, I get the following error msg: "Runelite has not yet been updated to work with the latest game update, it will work with reduced functionality untill then." But I have downloaded the latest version of RuneLite (1.6.26.1). Also, on my laptop everything works fine. I have tried to re-install but this doesn't solve the problem. Launcher version is 2.1.3.

**Comment by abextm** [comment]
Try deleting `~/.runelite/cache`. It may have incorrect permissions. Otherwise make sure you installed from https://runelite.net/ and not some phishing site.

**Comment by Psychotechnopath** [comment]
Deleting the cache solved the problem for me. Thx =)
