### ISSUE TITLE
Update GE Limits for September 10th, 2020 Update

### ISSUE THREAD

**Issue by Asymons** [runelite/runelite#12480]
**Is your feature request related to a problem? Please describe.**
GE Limits have been changed and need updating.

**Describe the solution you'd like**
Update the GE limits in the ge_limits.json file.

**Describe alternatives you've considered**
Keeping a notepad next to me at all times tracking the limits ;)

**Additional context**
These are the items that have been changed as per: https://secure.runescape.com/m=news/a-porcine-of-interest?oldschool=1#_ga=2.104720134.784067941.1599784266-88067259.1594783900
Fire Rune
Air Rune
Water Rune
Earth Rune
Feathers
Gold Ore
Blood Rune
Death Rune
Mithril Dart Tip
Pure Essence
Adamant Dart Tip
Grapes
Cannonballs
Headless Arrows
Asgarnian Seed
Barley Seed
Hammerstone Seed
Jute Seed
Yanillian Seed
Krandorian Seed
Wildblood Seed
Compost
Supercompost
Ultracompost
Filled Plant Pot
Fire Orb
Water Orb
Earth Orb
Air Orb
Cadava Berries
Drift Nets
Climbing Boots
Zenyte Necklace
Zenyte Bracelet
Necklace of Anguish
Elder Chaos Robes Top
Elder Chaos Robe Bottom
Elder Chaos Robe Hood
Ring of Suffering
Tormented Bracelet
Zenyte Ring
Ancient Crystal
Ancient Relic
Ancient Effigy
Ancient Medallion
Ancient Statuette
Ancient Totem
Ancient Emblem

On Reddit this was reported for runes: 
![image](https://user-images.githubusercontent.com/1833964/92831812-dc093b00-f3a4-11ea-8ff3-7005b316236e.png)

This is a good first-time ticket if anyone is interested. I won't be working on it.

**Comment by abextm** [comment]
the script that does this will run in <30 minutes
