### ISSUE TITLE
Discord streaming doesnt show all of Runelite.

### ISSUE THREAD

**Issue by Kameronii** [runelite/runelite#12486]
When i live stream Runelite in Discord the entirety of Runelite isnt showed on screen. It only captures the game its self and not the runelite side pannel plugins or the top of runelite where it shows what account is playing

**To Reproduce**
1. Stream Runelite on Discord
2. Open plugin side pannel
3. Look at the share screen on Discord

When my friend shares screen it shows all of runelite but whn i do it it jsut shows the game

**Screenshots**
My Friends Stream
![good RL](https://user-images.githubusercontent.com/71194024/93004858-1c89c580-f519-11ea-8cbb-ee013f67f23e.png)

My Stream
![Bad RL](https://user-images.githubusercontent.com/71194024/93004859-201d4c80-f519-11ea-899e-1b573f2fa703.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.26.1
 - Launcher version: 2.0.2

**Comment by l2-** [comment]
https://i.imgur.com/U4Fr4MO.png try turning this off

**Comment by Kameronii** [comment]
> https://i.imgur.com/U4Fr4MO.png try turning this off

It fixed it, thank you
