### ISSUE TITLE
New Very Powerful PC Build Came With New Runelite Visual Glitch? 

### ISSUE THREAD

**Issue by Nosfuratoo** [runelite/runelite#12487]
I just finished my new build yesterday featuring a 2070 super/ ryzen 9 3900x / 32gb ram  and my runelite now has a new issue when GPU settings are turned on where there's horizontal black lines that flash lightly across the top quarter of the screen every so often / randomly. Please help I want the GPU settings on like I used to have it Runelite on 144hz and GPU on is amazing these flashes are a new issue.

**Comment by Nightfirecat** [comment]
What are your GPU plugin settings and graphics card driver settings?

**Comment by Hydrox6** [comment]
Closing since stale, and this should have been done through the support channel
