### ISSUE TITLE
Menu Entry Event

### ISSUE THREAD

**Issue by Graviton1647** [runelite/runelite#12490]
**Is your feature request related to a problem? Please describe.**
An Event for on hover menu option so contextual icons can be added 

**Describe the solution you'd like**
Like the on click event for the menu but this event fires when you hover over the menu and outputs the id of the entry or returns the data for MenuEntry

**Describe alternatives you've considered**
I've looked into just doing it the cheap way by getting the mouse position and working it out based on the height of the menu but I also can't seem to be able to get the menu height

**Comment by raiyni** [comment]
Why have the menu entry added event.
