### ISSUE TITLE
Reduce GE history loading time on Runelite.net

### ISSUE THREAD

**Issue by Maximuis94** [runelite/runelite#12499]
**Is your feature request related to a problem? Please describe.**
I frequently export my GE history from Runelite.net. Initially this could be done within a minute, but as the number of logged trades grew, so did the loading time. As of now, it takes about an hour to load all logged trades. Exporting them before all transactions are loaded results in an incomplete JSON file.

**Describe the solution you'd like**
For me personally, I only need the trades logged over the past 1-2 weeks. Some suggestions that would presumably fix this issue are;
- Being able to reverse the loading order, so that newest trades are loaded first
- Being able to manually delete (a subset of) the GE history of a RuneLite account 
- Being able to lower the maximum time for which trades are saved
- Being able to set a time frame in which transactions are loaded (e.g. only load transactions that are up to X days/weeks old)

**Additional context**
Before being able to export the history, I have to wait for about an hour. The exported history consists of ±15K trades.

**Comment by abextm** [comment]
duplicate runelite/runelite.net#355
