### ISSUE TITLE
Switch for Loot Tracker to reset apon logout

### ISSUE THREAD

**Issue by xMiyuka** [runelite/runelite#12502]
Before I wasn't logged into a Runelite account, my loot tracker would reset every time I logged out. I perfer this because I tend to forget to reset my loot tracker apon logging in. I like seeing how much money a task makes me and due to it storing previous data it will show my previous kills. If a button toggle could be added to auto reset all loot tracker data apon logout / login, that would be awesome!

**Comment by Hydrox6** [comment]
`Loot Tracker` -> `Synchronize panel contents`
