### ISSUE TITLE
Trouble accessing API?

### ISSUE THREAD

**Issue by alexalmonte49** [runelite/runelite#12508]
I logged back into my account through runelite after about a month of inactivity. Noticed that the GE price checking, chat commands, and other plugins were not working even though I have them enabled. I re-installed the client and still can't get it to work. After doing some digging it appears that it may an issue "accessing the API" but I am not very code-savvy so I don't know what that means and I do not understand the workaround that is in the FAQ section. Any help would be appreciated

I am on Windows and I have the latest release of runelite (1.6.26.1). I will also attach my logs
[client.log](https://github.com/runelite/runelite/files/5243450/client.log)
[launcher.log](https://github.com/runelite/runelite/files/5243451/launcher.log)

**Comment by abextm** [comment]
You are not using our software. Make sure you downloaded from https://runelite.net and not a phishing site. You probably want to change your passwords and/or run a virus scan
