### ISSUE TITLE
Runelite full screen is messed up

### ISSUE THREAD

**Issue by JoeSwanson24** [runelite/runelite#12503]
Runelite wouldn't go entirely full screen, all selection options flicker at the top of the screen, and the news is stuck above. not sure what caused it, i just didn't play runelite for a while, the exe stopped working, and the jar still ran but is really buggy

![](https://i.imgur.com/1kmsYdu.png)

**Comment by raiyni** [comment]
Update to the newest launcher or install java 11.0.8
