### ISSUE TITLE
Experience Tracker "actions left" improperly handles *.5 xp drops

### ISSUE THREAD

**Issue by MESLewis** [runelite/runelite#1251]
When doing an action that gives x.5 xp per action the experience drops alternate between x and x + 1. This causes the "actions left" calculation to go back and forth between xp left / x and xp left / (x + 1).

This may be able to be alleviated by detecting xp drops that alternate between two values and averaging them for the "actions left" calculation.

**Comment by LeviSchuck** [comment]
How is this?

![after](https://user-images.githubusercontent.com/245911/38464525-b57422e2-3ad4-11e8-84ae-3b1727001494.gif)
