### ISSUE TITLE
Add Pick-Lock/Swap to Dorgeshuun Rich Chests in the Menu Entry Swapper (Extended)

### ISSUE THREAD

**Issue by chadamantbar** [runelite/runelite#12515]
Adding a Pick-Lock/Swap to Dorgeshuun Rich Chests in the Menu Entry Swapper (Extended) would be convenient if it is allowed

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
