### ISSUE TITLE
Mute Magic Tree Sounds (Environment Area Sound)

### ISSUE THREAD

**Issue by Demonslay335** [runelite/runelite#12526]
**Describe the bug**
The magic tree area sound does not mute using any option of the Music plugin. Its volume is controlled by the "Adjust Area Sound Volume" in the client Audio options, so I would expect it to be controlled by the "Mute environment area sounds" checkbox.

I personally find the magic trees sound very annoying, but I don't want to mute the entire Area sounds thru the client. I still want to hear the wood chopping sound while I AFK (this is controlled by the "Mute player area sounds" in the Music plugin, so it appears to be separate).

**To Reproduce**
1. Enable the Music plugin
2. Check "Mute environment area sounds"
3. Stand by some magic trees

**Expected behavior**
The magic tree area sound is muted when selecting the "Mute environment area sounds" setting.

**Environment (please complete the following information):**
 - OS: Windows 10 1909
 - RuneLite version: 1.6.26.1
 - Launcher version: 2.1.0

**Comment by killzone111** [comment]
I have the same issue.
Can this be fixed?

**Comment by bhekman** [comment]
+1

**Comment by bhekman** [comment]
Looked through the relevant code briefly: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/music/MusicPlugin.java#L374

Perhaps source != null for the sounds from the magic trees? Nevertheless, this sound is not generated by a player or NPCs, so it should be muted according to the option setting. I think the "source == null" conditional probably needs a change.

**Comment by Adam-** [comment]
I've looked into this before briefly, and the event doesn't even fire for these sounds because they work differently.

**Comment by killzone111** [comment]
any news on this? :)

**Comment by Garcia-Julz** [comment]
Yeah while skilling I just noticed this annoyance :P

**Comment by ulises-c** [comment]
This would be appreciated

**Comment by Adam-** [comment]
added in 099221993ab8802993acf4ffccb4ba19a9b5a2c9
