### ISSUE TITLE
!kc rooftop

### ISSUE THREAD

**Issue by rafagracioso** [runelite/runelite#12529]
could you add !kc to the same rooftops as ape atoll and prifddinas? thank you

**Comment by Broooklyn** [comment]
Lap counts are already accessible with the `!kc` command, you just need to type exactly what is displayed. For example, `!kc ardougne rooftop` works just fine. 

![image](https://user-images.githubusercontent.com/54762282/93833486-be5e9000-fc46-11ea-9fda-6ce7037da4b2.png)


Perhaps you'd like to change this to a suggestion for adding additional short names for each rooftop course, so something like `!kc ardy` would work?

**Comment by rafagracioso** [comment]
it's working yes, thank you very much <3

**Comment by rafagracioso** [comment]
!kc ardy doesn't work
