### ISSUE TITLE
dps calc plugin

### ISSUE THREAD

**Issue by QGoh** [runelite/runelite#12538]
is there any interest in adding a dps calculator plugin? i made something here: https://github.com/QGoh/runelite/tree/qgoh-branch.
it's still missing some gear sets and gear special effects like the dharok set and berserker necklace but it works for the most part.

**Comment by CasvM** [comment]
nice, I was thinking about making one myself. It might work better as a pluginhub external plugin rather than a main plugin so that people can enable it only if they want to

**Comment by CasvM** [comment]
Would you mind if I used your code to create a dps calc plugin for the plugin-hub? I might make a few UI changes, and add the missing gear sets/special attacks, but otherwise it would be mostly your code.

**Comment by QGoh** [comment]
> Would you mind if I used your code to create a dps calc plugin for the plugin-hub? I might make a few UI changes, and add the missing gear sets/special attacks, but otherwise it would be mostly your code.

all yours

**Comment by CasvM** [comment]
thank you!

**Comment by raiyni** [comment]
duplicate of #350
