### ISSUE TITLE
Runelite goes Invisible on my 2nd Monitor when maximizing

### ISSUE THREAD

**Issue by Scahry** [runelite/runelite#12546]
**Describe the bug**
when maximizing the client on my second monitor, runelite goes completely invisible,
though it can still be found on the taskbar and when hovering over i can see runelite running

**To Reproduce**
open client
drag to 2nd monitor
maximize

**Expected behavior**
I expect to see the runelite client

**Video**
https://www.youtube.com/watch?v=kNYUhT0PUB8

**Environment (please complete the following information):**
 - OS: Windows 7 Ultimate
 - RuneLite version: 1.6.28
 - Launcher version: i compile myself

**Additional context**
monitor resolution: 
main: 1920x1080 
2nd: 1600x900 (downscaled, technically 1920x1080)
scale and layout is 100%

**Comment by Scahry** [comment]
does not happen on the release 1.6.27 client, which apparently uses the same code

**Comment by Adam-** [comment]
Custom launcher builds are not supported.
