### ISSUE TITLE
LMS HEALTHPOINT FIX PLEASE <3

### ISSUE THREAD

**Issue by justaplayer5** [runelite/runelite#12540]
Can someone make a plugin to fix the health points in LMS when your osrs accounts hp level is 10. I die alot in lms because i just see green text and full red hp bar in my bottom right (when it should be RED and almost BLACK background because i am 14 hp!) but because my osrs accounts hp stats is 10, it shows it full hp and green text. can someone make a fix for this?
![11](https://user-images.githubusercontent.com/71757942/93989176-42715e80-fd92-11ea-95e6-812163c66253.png)

**Comment by justaplayer5** [comment]
.

**Comment by Nightfirecat** [comment]
This is a bug with the vanilla client, not with RuneLite. We may try to add a fix for it in our client specifically, but recommend you report this as a bug to Jagex.

**Comment by Nightfirecat** [comment]
This was fixed [in the June 22 update](https://secure.runescape.com/m=news/pride-2022-pet-reclaim-changes--new-mobile-client?oldschool=1):

> * The Minimap's HP orb now shows your health in Last Man Standing as a proportion of 99, as that’s the base HP level used in the minigame.
