### ISSUE TITLE
Stetched Runelite no longer resizes correctly on some resolutions with taskbar disabled.

### ISSUE THREAD

**Issue by jesse1412** [runelite/runelite#12548]
After f7606c7acaf25331331e85d4d1bad7b8e2ff3e9c runelite no longer resizes correctly when trying to make the application full screen in some cases. In my example, my monitors are 1920x1080 (LHS) and 1680x1050 (RHS). [Full screen works correctly on the LHS monitor, but not on the RHS monitor](https://streamable.com/sb7yby). By reverting f7606c7acaf25331331e85d4d1bad7b8e2ff3e9c we return to [expected behaviour](https://streamable.com/1bvfrj). This seems to be caused by the fact that after f7606c7acaf25331331e85d4d1bad7b8e2ff3e9c runelite no longer appears to account for displays having additional space from hiding the taskbar. Even before f7606c7acaf25331331e85d4d1bad7b8e2ff3e9c [my setup didn't work perfectly with the taskbar enabled](https://streamable.com/5sw027), however hiding the taskbar on that display made runelite work correctly in stretched fullscreen on both monitors.

**To Reproduce**
For my exact issue, use 1920x1080 (LHS) and 1680x1050 (RHS) display settings.

Use resolution 1680x1050 with stretched mode on.
Hide the taskbar.
Full screen the application.

**Expected behavior**
The application will stretch correctly on either display.

 - OS: Windows
 - RuneLite version: [e.g 1.6.12]

**Comment by Adam-** [comment]
For https://streamable.com/sb7yby which launcher version and RL version is this? Are you using the launcher?

**Comment by jesse1412** [comment]
In that clip, I'm using a self built jar, so no launcher. I just did a fresh install of the release version of the client (RL 1.6.27, launcher 2.1.3), and the issue didn't occur, however launching from the release jar caused the issue to occur again.

**Comment by Adam-** [comment]
This is not really a valid issue since it is only happening on unsupported Java versions but I've added version checks for this specific issue in 9c362fb836b83a69dfeae4514b774f28cf573d7e.
