### ISSUE TITLE
My PC keeps freezing when using Runelite

### ISSUE THREAD

**Issue by Wasif-Anton** [runelite/runelite#12556]
Hello, I need help I don't know if its the right place to post here!!

**Describe the bug**
So after 3 months, I came back to play OSRS.
Runelite was working fine, I have no idea what happed my pc keep freezing when I use Runelite **(RuneLieSetup.exe)**
I deleted Runelite and download it again nothing changed, Java is also updated.

I downloaded **RuneLite.Jar** now I got an Error message
1. "Error: A JNI error has occurred, please check your installation and try again"
2. "A Java Exception has occurred"

Can someone guide me for fixing my problem?
For me, it is hard to play on OSRS Client. Please help :/

Environment (please complete the following information):
- OS: Windows 10 64 bit

My pc specs:
- CPU - i9 7900x
- GPU - GTX 1080ti
- RAM - 32 bits
- Storage - 2TB HDD, 500GB SSD

**Comment by drummerkid** [comment]
Are you sure you're downloading the .exe installer from the official Runelite site? You should be using the .exe in almost all circumstances rather than the .jar.

Try downloading the 64 bit windows launcher from the official site - https://runelite.net/

**Comment by Wasif-Anton** [comment]
> Are you sure you're downloading the .exe installer from the official Runelite site? You should be using the .exe in almost all circumstances rather than the .jar.
> 
> Try downloading the 64-bit windows launcher from the official site - https://runelite.net/

Yes, It ends with .net. the Client opens fine but when I start playing it crashes my pc randomly.

**Comment by drummerkid** [comment]
Ah, that's a separate issue to what you posted above. You'll likely need to post your logs for someone to have a look at. I recommend you join the discord and describe your problem in the #support channel.

https://runelite.net/discord

**Comment by Wasif-Anton** [comment]
> Ah, that's a separate issue to what you posted above. You'll likely need to post your logs for someone to have a look at. I recommend you join the discord and describe your problem in the #support channel.
> 
> https://runelite.net/discord

Can you tell me how/where can I find my logs?

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
