### ISSUE TITLE
Suggestion: Right Click Examine NPC's

### ISSUE THREAD

**Issue by Woodey79** [runelite/runelite#12554]
I think it would be cool to have a feature where, if you right click and examine an npc that it will show all of the combat stats of the thing you examined so you do not have to look at the Wiki to learn if you should be training or fighting an enemy with a certain attack style. 

I dont mean for this to be super in depth, but just listing the Range Melee and Magic attack buffs along with the defense buffs and or other positive or negative combat effects

**Comment by Hydrox6** [comment]
This is really better served with the wiki plugin's lookup. The "orb" makes it really fast to look anything up, and the full information on there will be better that anything we could cram into a tiny section in the client.

**Comment by Nightfirecat** [comment]
Not only that, combat stats are not the only determinant of whether a monster is vulnerable to a certain attack styles since there are many special cases, particularly when it comes to bosses.
