### ISSUE TITLE
Tagging items in bank / inventory colors for Barrows & other degrading gear should consider the other %'s

### ISSUE THREAD

**Issue by xMiyuka** [runelite/runelite#12560]
Basically, if I tag a degradable item like barrows gear and it degrades, I have to retag the other versions (75%, 50%, 25% broken). I believe tagging the gear should be default consider the other versions so we don't have to retag the gear. This would be useful for raiders especially because sometimes we can forget the exact armor we had if it degrades and it's missing from the bank.

**Comment by Broooklyn** [comment]
Shift drag the item to a bank tag and it will tag all %s. Alternatively, tag it with a `*`
