### ISSUE TITLE
Clue scroll hint stays after casket has been received.

### ISSUE THREAD

**Issue by Klievan** [runelite/runelite#12565]
**Describe the bug**
The clue-hint and arrow stays after receiving the casket.

**To Reproduce**
1. Complete a beginner clue.
2. When receiving the casket, do not close the dialogue but open the casket.

Not sure if this happens every time, but arguably a simple check to see if there is no cluescroll in the inventory would suffice to fix this every time.

**Expected behavior**
When there is no clue-scroll is in the inventory or when the player receives a casket, the clue-hint should dissapear.

**Screenshots**

![image](https://user-images.githubusercontent.com/5279685/94487039-99d35c80-01e0-11eb-8466-c13bf4ed899e.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - RuneLite version: 1.6.1
 - Launcher version: n/a

**Additional context**
The logs do not seem to show any relevant information.

**Comment by Nightfirecat** [comment]
This can only happen for beginner and master clues.
