### ISSUE TITLE
Cannot use settings interface

### ISSUE THREAD

**Issue by minimog27** [runelite/runelite#12561]
![12a635d1e5f8bba918ecefe7cc507e51](https://user-images.githubusercontent.com/71974884/94366598-5923f800-00a7-11eb-8ad2-8fe9761690e5.png)

Normally trying to use the client but for some reason i just cant look at anything it will just duplicate the layers and text

**Comment by Bram91** [comment]
Duplicate of https://github.com/runelite/runelite/issues/11727
