### ISSUE TITLE
"Log in to RuneLite" button not working

### ISSUE THREAD

**Issue by dot-io** [runelite/runelite#12571]
_Operating system - Linux (Elementary OS)_

When pressing the "Log in to RuneLite" button in the top right corner, between the discord and screenshot buttons, nothing seems to happen. I've managed to log into my RuneLite account through the official website, so the issue doesn't lie there to my knowledge.

Before switching to Linux a few weeks ago I had the client installed on Windows and the button worked fine there.

**Comment by Nightfirecat** [comment]
Please upload your client.log file

**Comment by dot-io** [comment]
[client.log](https://github.com/runelite/runelite/files/5301214/client.log)

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
