### ISSUE TITLE
Divine potion countdown persists after some stat resets

### ISSUE THREAD

**Issue by Klievan** [runelite/runelite#12572]
**Describe the bug**
Divine potion counter seems to persist even though stats have been reset through the Pool of Refreshment or FFA portal at Ferox Enclave.

**To Reproduce**
1. Drink a divine potion
2. Reset your stats by drinking from pool or going through FFA portal.

**Expected behavior**
As the stats are not boosted anymore, the timer should fade.

**Screenshots**
![image](https://user-images.githubusercontent.com/5279685/94670350-bec7ec80-0312-11eb-8dd3-72f26c1d3a32.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - RuneLite version: 1.6.1
 - Launcher version: n/a

**Comment by winterdaze** [comment]
this isn't a bug, the timer is for the divine effect which will keep your stats boosted without ticking down (if you drank another regular boosting potion dose). it also persists on death

**Comment by Klievan** [comment]
My bad. Closing this issue.
