### ISSUE TITLE
RuneLite no longer lets me log in with authenticator but authenticator works for RuneScape 

### ISSUE THREAD

**Issue by DielleVerity** [runelite/runelite#12577]
RuneLite no longer lets me log in with authenticator but authenticator works for RuneScape and everything else

Steps
Log In
It will ask for the authenticator code
Enter the code
And then it says "try again" and "forgot password?"

Expected Behavior is that it normally logs me in. I did it with 2 different authenicator apps starting with the one I've always used which is Google Authenticator. When it didn't work I downloaded a new authenticator app called 2FA Authenticator and  it worked for RuneScape as well but again not RuneLite. I've never had a problem logging in with authenticator before but since it works for everything else it has to be a bug with RuneLite 

**Environment
 - OS: Windows
 - RuneLite version: RuneLite for Windows (64 bit)
 - Launcher version: I don't know much about computers or how to find that

**Comment by thebinaryeagle** [comment]
Double check that your login info is being entered correctly. Plugins with keybinds such as the screenshot plugin or the zulrah one on the hub can, if bound to those keys, intercept your key presses and make them not be entered.

**Comment by Nightfirecat** [comment]
Keybinds should not be triggered on the login or authenitcator. We do not intercept authenticator requests in any way, so you should double-check to make sure you are typing it correctly and do not have any other programs intercepting it as you type it out.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

**Comment by DielleVerity** [comment]
I typed in  the codes correctly every time. it used to always work

**Comment by DielleVerity** [comment]
why did you close it! now no one can fix the bug! also idk how to use discord. its extremely confusing

**Comment by Bram91** [comment]
Because the issue tracker is not a support forum. Join the discord for questions of support:  [Discord](https://runelite.net/discord)
