### ISSUE TITLE
Mouse keeps disappearing after I alt to move something

### ISSUE THREAD

**Issue by three6mafiaa** [runelite/runelite#12596]
**Describe the bug**
When I alt + drag to move anything in the interface, minimap for example, my mouse disappears after. It is still ''usable'' but I don't see it, runelite restart is necessary to see it again.

**To Reproduce**
1. Go to game.
2. Press alt 
3. Drag anything
4. Mouse has disappeared

**Expected behavior**
Expected behavior is for mouse to be visible all the time.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: [1.6.27]
 - Launcher version: [2.1.3
[client_2020-10-03.0.log](https://github.com/runelite/runelite/files/5323439/client_2020-10-03.0.log)
]
[client_2020-10-02.0.log](https://github.com/runelite/runelite/files/5323442/client_2020-10-02.0.log)

**Comment by Hydrox6** [comment]
This is a bug in Contextual Cursors v1.2. It will be fixed in 1.2.1

**Comment by three6mafiaa** [comment]
Thanks for the quick response! Indeed I turned off contextual cursors and no more issue.
