### ISSUE TITLE
Ge prices are never accurate 

### ISSUE THREAD

**Issue by CnPx98** [runelite/runelite#12597]
The GE price tool is never correct on anything. The only thing its useful for is checking buy limits. If its not going to be correct just remove the price checker all together as its just misleading people. 
You could use the same idea as RS buddy and have it so it gets prices from other users also using runelite and when they open an item in the GE it grabs the price and updates itself.

**Comment by Nightfirecat** [comment]
The GE tracker shows prices from Jagex. If those are not accurate to your liking, you should bring that up to them.

We are not considering creating a GE tracker ourselves, [as mentioned on our rejected features page](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features):

> GE Tracker: There's no way to validate that any of the data coming from the client is legitimate, thus allowing for easy spoofing and price manipulation.

**Comment by CnPx98** [comment]
> The GE tracker shows prices from Jagex. If those are not accurate to your liking, you should bring that up to them.
> 
> We are not considering creating a GE tracker ourselves, [as mentioned on our rejected features page](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features):
> 
> > GE Tracker: There's no way to validate that any of the data coming from the client is legitimate, thus allowing for easy spoofing and price manipulation.

I suppose thats fair enough. Thank you for your fast reply!
