### ISSUE TITLE
Add loot tracker for Grubby Chest

### ISSUE THREAD

**Issue by WholesomeDogg0** [runelite/runelite#12618]
There's currently no way to track the grubby chest loot except by manually taking note of the items obtained. Similar to opening bird nests or any other monster drops, it would be nice to have a tracker for loot obtained by opening grubby chests in Forthos Dungeon.

**Comment by Nightfirecat** [comment]
We should already have loot tracking working for the grubby chest: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java#L625

Is that not working?

**Comment by WholesomeDogg0** [comment]
I'll check it out. I didn't notice the plugin before

**Comment by WholesomeDogg0** [comment]
> We should already have loot tracking working for the grubby chest: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java#L625
> 
> Is that not working?

If this is for the main loot tracker then it's not currently working

**Comment by WholesomeDogg0** [comment]
> We should already have loot tracking working for the grubby chest: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/loottracker/LootTrackerPlugin.java#L625
> 
> Is that not working?

Currently working now. For some reason when I tried tracking it earlier last week the plugin didn't work for me

**Comment by Nightfirecat** [comment]
It was added [in today's release](https://runelite.net/blog/show/2020-10-07-1.6.28-Release):

> The loot tracker now correctly tracks the Grubby chest.
