### ISSUE TITLE
Supplies Tracker (option to remove previous session data saving)

### ISSUE THREAD

**Issue by 808n** [runelite/runelite#12613]
This is a very simple request. 

With the addition to the changelog 1.9, we received session saving - supplies will now save previous sessions. 

Give us an **option** to turn that off. For me, that is counterintuitive of how I think the supplies tracker should work, although a great feature for certain tasks, if the user so wishes. 

I want to know how much I've spent over how much I've earned (via loot tracker) per single session while doing a gluttonous boss like Cerberus. I will reset the tab before I log off every night, and sometimes it will continue to store the data. So when I start a new session, I go into the boss not knowing how many supplies I've consumed that trip because it retained the data from the last session by default. It is very easy to forget to check and reset when logging back on the next day.  I hope that makes sense. 

Thanks for all the hard work you folks do! 
                                                         -808n

**Comment by Nightfirecat** [comment]
Supplies Tracker is an external plugin not owned by the RuneLite team. [Please raise this as a feature request to them directly.](https://github.com/Dyldozer/SuppliesTrackerExternal/issues)
