### ISSUE TITLE
Disregard

### ISSUE THREAD

**Issue by Mwellrett** [runelite/runelite#12623]
**Describe the bug**
****Disregard****
Crash was caused by Chrome eating up all my memory I guess.

Client Crashes when mousing over slayer mobs

**To Reproduce**
1. Go to a slayer mob (Specifically Ancient Zygomite in my experience (While underground))
2. Mouse over it
3. Crash

**Expected behavior**
 
Not Crashing 
Disabling Slayer Plug-in Stops Crash

**Screenshots**

N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.28 Rev 191
 - Launcher version: 2.1.3

**Additional context**

[client_2020-10-08.0.log](https://github.com/runelite/runelite/files/5354658/client_2020-10-08.0.log)
[jvm_crash_pid_10788.log](https://github.com/runelite/runelite/files/5354661/jvm_crash_pid_10788.log)

**Comment by Nightfirecat** [comment]
That is not the cause of the crash. Please upload your full `client.log` file and the most recent `hs_err_pid` or `jvm_crash_pid` file you have in your logs folder.
