### ISSUE TITLE
Please add Tmorph to runelite, transmog for runelite.

### ISSUE THREAD

**Issue by Bamboozaler** [runelite/runelite#12645]
Please add Tmorph as it would allow players to Tmog client side. I don't know if this causes issues with the bot detection system but I know runelite is capable of it. Could you please add it? This would be great feature for players who really like to fashions cape but can't while they're doing certain skilling/bossing/slayer. I would greatly appreciate adding support for this if you can.

**Comment by abextm** [comment]
duplicate #12482
