### ISSUE TITLE
Allow key remapping of Control key

### ISSUE THREAD

**Issue by willediger** [runelite/runelite#12658]
The Control key is used for a somewhat little-known feature in Old School Runescape, [[Control]+click to run](https://oldschool.runescape.wiki/w/Game_controls#Running). This is useful in PvM situations where you need to be able to either switch from walking to running quickly, or vice versa.

If you don't need to run in a situation, but need to be able to run at a certain point quickly in reaction to something, you keep the run orb off, and when you need to run, you [Control]+click to run and do your thing. When you no longer need to run, you just click normally, and you're back to running.

If you don't need to walk in a situation, but need to be able to run at a certain point quickly in reaction to something, you keep the run orb off, [Control]+clicking to run where you need to go, and when you need to walk, you simply click to walk where you need to go.

It's also useful if you are running all the time and have the run orb on, and then forget to drink a stamina potion. If you run until your energy runs out, and you switch to walking, but don't notice it immediately, or aren't bothered by it incredibly at the time, if you realize that you need to run to react to something, [Control]+click is a great way to get running without having to click the run orb first.

This all avoids having to move your mouse first to the run orb to change your speed. Very helpful in intense PvM situations such as Inferno, ToB, and CoX. The problem is that the Control key is far away from where my fingers are normally, and the Control key is small as well. I would like to remap the Control key to [space] so that I can easily hit it while using my F-keys.

I know there's a workaround I could set up by using AutoHotkey, but it would be great if it was built into RuneLite.

I appreciate all of your work on this great client!

**Comment by mzegar** [comment]
@willediger 

Seemed like a reasonable request to me, PR implements rebinding of "Control".

**Comment by mzegar** [comment]
Looks like this issue can be closed : D

**Comment by Adam-** [comment]
added in #12724
