### ISSUE TITLE
Runelite game window stalls when switching focus

### ISSUE THREAD

**Issue by amerheb** [runelite/runelite#12669]
When playing with 2 or more clients open, there is a very high chance that the game window of a client freezes/stalls every time you click back onto the window. The game window is unable to be interacted with at all until you click back off the client. When you click off the client, the game "resumes" and appears to have acted like there was just a huge disconnect (all hitsplats that occured/xp drops that happened during that time the game is frozen all appear at the same time, your character runs very fast to "catchup" to where he actually is, etc.).

Although the game window freezes, the rest of the client/sidebar are able to be interacted with, with the game still frozen.

This typically happens when you are in combat on the client that gets frozen.

This happens with GPU mode both turned off and turned on. 

I have also noticed that when the client freezes, the CPU usage of the client drops down to nearly 0.

**Note: This sometimes happens when clicking from the main client to another window/off screen, and it wont resume until clicking back.

**To Reproduce** (Not 100% of the time, moreso 20%)
1. Have more than 1 client open and logged into.
2. Perform some clicks on the "Main" client, then do some clicks on the "Alt" client
3. Try to go back to the "Main" client and click around
4. Main client game window freezes until you click back off.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.28
 - Launcher version: 2.1.3

**Additional context**
GPU: GTX 1080
CPU: I7-6700k

Desktop clip of client freezing (Top client): https://streamable.com/lioypx

For some reason, none of this shows up in logs. Will update if changed.

**Comment by Nightfirecat** [comment]
Does this still happen with the latest launcher version? If so, can you produce this bug and upload your client log?

**Comment by Nightfirecat** [comment]
Since this issue is lacking information and has not been updated in some time, I am closing it.
