### ISSUE TITLE
Loot tracker not tracking lizardman shamans

### ISSUE THREAD

**Issue by pangpower** [runelite/runelite#12662]
Quite simply, the loot tracker plugin is not tracking my lizardman shaman kills, it has worked in the past but now it just doesn't for some reason.

**Comment by Nightfirecat** [comment]
What are your loot tracker plugin settings?

**Comment by pangpower** [comment]
Oh this was from a long time ago and I’ve since found the problem. For some reason shamans were just hidden.

Från: Jordan<mailto:notifications@github.com>
Skickat: den 18 januari 2021 07:15
Till: runelite/runelite<mailto:runelite@noreply.github.com>
Kopia: pangpower<mailto:Pober@live.se>; Author<mailto:author@noreply.github.com>
Ämne: Re: [runelite/runelite] Loot tracker not tracking lizardman shamans (#12662)


What are your loot tracker plugin settings?
