### ISSUE TITLE
Grapple location icon missing from World Map near Water Obelisk (Catherby)

### ISSUE THREAD

**Issue by Sethmare** [runelite/runelite#12660]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
On the World Map, the agility shortcut icon is missing but the tooltip still exists.

**To Reproduce**
1. Go to World Map, Catherby
2. Hover mouse between two fishing spots by rocks

**Expected behavior**
Expected to see the agility shortcut icon in the same spot as the tooltip.

**Screenshots**
![Screenshot_45](https://user-images.githubusercontent.com/66145237/96362896-f5ad4900-10ed-11eb-961b-8acb46773e69.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.28

**Comment by trelkins3** [comment]
Silly question sanity check - can you see other grapple icons on your world map?

**Comment by Sethmare** [comment]
Yes I can, it's not pictured but just to the right of this screenshot is another that was clearly marked.

**Comment by Nightfirecat** [comment]
It seems they've removed they icon for this grapple location. We currently only add tooltips to shortcuts which show a world map icon, so we should remove this tooltip.
