### ISSUE TITLE
Intermittent Client Crash

### ISSUE THREAD

**Issue by trelkins3** [runelite/runelite#12670]
**Description**
I have noticed intermittent crashes with RuneLite in the most recent patch. I am running a relatively up to date Win10, Ryzen 7 3700X, and a Radeon RX 5600 XT. AMD drivers recently rolled to 20.9.2 and I was not experiencing the problem before then.

Both of my monitors flash, then when image returns to the display the overlay itself is still present but the game has disappeared and just shows my desktop background. GPU plugin is enabled - settings (and the crash itself) are in the screenshot.

![image](https://user-images.githubusercontent.com/22403959/96489968-072d4880-11f5-11eb-879b-6124f5b40440.png)

If I click around or try to do things in the UI overlay, it seems fine. But if I click on where the game was before the screen flicker, RuneLite will hang and crash.

**To Reproduce**
I cannot find a consistent way to reproduce, but it has happened multiple times at the Smoke Devil Dungeon. I suppose it's possible that it is a problem with RuneScape itself?

**Expected behavior**
The game... not crashing.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.28
 - Launcher version: 2.1.3
 - OldSchool Revision: Rev 191

**Additional context**
Logs for the client and launcher attached - didn't see anything particularly crazy, though I did have Discord open when the crashes started happening.

[client.log](https://github.com/runelite/runelite/files/5403648/client.log)
[launcher.log](https://github.com/runelite/runelite/files/5403649/launcher.log)

**Comment by trelkins3** [comment]
I'm certain this is not enough information to root cause this problem - let me know what I can do to further investigate and I will do so as soon as possible.

**Comment by Nightfirecat** [comment]
You should have some `jvm_crash_pid` file(s) in your log folder. Can you upload the most recent ones of those?

**Comment by trelkins3** [comment]
[jvm_crash_pid_9712.log](https://github.com/runelite/runelite/files/5405915/jvm_crash_pid_9712.log)
[launcher.log](https://github.com/runelite/runelite/files/5405917/launcher.log)
[client.log](https://github.com/runelite/runelite/files/5405918/client.log)

I've had it crash twice since I created this issue. Here are the requested logs.

**Comment by Nightfirecat** [comment]
The last time we updated the GPU plugin looks to be [October 7th with the 1.6.28 release](https://runelite.net/blog/show/2020-10-07-1.6.28-Release). Unless you experienced this starting at that time, I'd imagine this is caused by your recent driver update. Try rolling back your drivers and see how that behaves.

**Comment by trelkins3** [comment]
Since rolling my AMD drivers from 20.9.1 to 20.10.1 and re-enabling the GPU plugin I haven't gotten this crash again. I think your hunch about the driver was right, going to close this and I'll reopen it if it happens again.
