### ISSUE TITLE
Whole RuneLite client crashing and black screening pc especially with gpu plugin

### ISSUE THREAD

**Issue by KarosM8** [runelite/runelite#12676]
Runelite will completely crash and lag out my pc to a full black screen and will obviously itself close runelite. I did a full reinstall of the game and deleted all plugins and i've learned that even going anywhere remotely close to the sidebar begins to lag my pc, and turning on the GPU plugin had immediately crashed and lagged out my pc. I tried reinstalling java and everything else too and nothing works.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
