### ISSUE TITLE
NPC Inidicators plugin: Highlight menu names does not highlight all options

### ISSUE THREAD

**Issue by syngfaa** [runelite/runelite#12671]
**Is your feature request related to a problem? Please describe.**
The plugin has a " Highlight menu names" configuration option, but when you toggle it on it only highlights the first menu item.
**Describe the solution you'd like**
Highlight all menu item names hat belong to the tagged npc. I have implemented this and will create a PR shortly after submitting this issue.

**Describe alternatives you've considered**
None, just a fun enhancement of the npc indicator plugin 

**Additional context**
Before picture:
<img width="332" alt="Screenshot 2020-10-19 at 22 56 35" src="https://user-images.githubusercontent.com/7204871/96511260-21037580-125f-11eb-8f79-ddb15363393f.png">

After pictures:
<img width="236" alt="Screenshot 2020-10-19 at 23 05 38" src="https://user-images.githubusercontent.com/7204871/96511675-abe47000-125f-11eb-81eb-b175f92f22b2.png">
<img width="253" alt="Screenshot 2020-10-19 at 23 04 46" src="https://user-images.githubusercontent.com/7204871/96511570-8c4d4780-125f-11eb-8e1e-eac8af684a22.png">

**Comment by Adam-** [comment]
For me, it already does highlight multiple npc options, leaving out only examine:

![image](https://user-images.githubusercontent.com/309739/99882441-847e1b80-2bee-11eb-9b05-2b40bfc81ccd.png)

**Comment by Nightfirecat** [comment]
We're not interested in this at the moment--the plugin currently highlights entries which will cause some kind of ingame action, which is intended.
