### ISSUE TITLE
Efficient cannon spots for the new wildy slayer cave introduced on 10/21

### ISSUE THREAD

**Issue by Schipholrs** [runelite/runelite#12679]
Main purpose of the spots is to reach all/most of the monsters while preventing all/most monsters from moonwalking away from the player.

List includes: 
- Lesser Demons
- Greater Demons
- Ice Giants
- Ankous
- Black Dragons
- Green Dragons

List doesn't include:
- Hellhounds (didn't get a task)
- Black Demons (weren't efficient for me)

![greater demons](https://user-images.githubusercontent.com/73258545/96893573-234a1780-148b-11eb-882e-c8288b128530.png)
![greens](https://user-images.githubusercontent.com/73258545/96893576-23e2ae00-148b-11eb-9df9-0cc94509008b.png)
![blacks](https://user-images.githubusercontent.com/73258545/96893579-23e2ae00-148b-11eb-81b4-a5ab91636248.png)
![ankou](https://user-images.githubusercontent.com/73258545/96893580-247b4480-148b-11eb-8615-8ca04189f8df.png)
![ices](https://user-images.githubusercontent.com/73258545/96893581-247b4480-148b-11eb-958e-0b3062de55cc.png)
![lesser demons](https://user-images.githubusercontent.com/73258545/96893584-247b4480-148b-11eb-99cc-a5bbd7060e26.png)

**Comment by Nightfirecat** [comment]
We've added these spots in 34f89715a1ba62743094af91b54f761146f73095
