### ISSUE TITLE
Tzhaar slayer task bug

### ISSUE THREAD

**Issue by Zunkrah** [runelite/runelite#12684]
When you have 'Hot Stuff' unlocked at a slayer master for Jad/Tzhaar tasks and choose Tzhaar over Jad you have to 'check' your task on your slayer helm/gem, etc to have the infobox for Tzhaar's show up.

Added a gif rather than a screenshot.
![Tzhaar bug github](https://user-images.githubusercontent.com/73383516/97077937-d878ee80-15b5-11eb-943a-1bb1d1fc8756.gif)

 - Windows 10 
 - RuneLite version: [1.6.29]
 - Launcher version: [2.1.3]

This is just a tiny bug and would be nice qol to have fixed. (Not sure of any other tasks this happens to as this is the only one I've experienced it with).

**Comment by Nightfirecat** [comment]
Do you have a screenshot of the text your slayer master gives you after selecting Tzhaar over a jad/zuk task? Without that, we can't really fix this bug.

**Comment by Zunkrah** [comment]
I will upload that once I get another task

**Comment by Zunkrah** [comment]
https://imgur.com/a/0o7SNqg

There's an imgur photo list.

**Comment by Nightfirecat** [comment]
What about the text where he actually says how many you have to kill? That's the text we would need to parse to correct this.

**Comment by Zunkrah** [comment]
Ah, I didn't get that my bad. I believe the issue is more so with the second chat box because it won't show 100% of the time then but only sometimes for me when it says how many to kill. I can upload it next task I get; apologies for leaving that out.

**Comment by Nightfirecat** [comment]
No problem. If your task is set as soon as you get the "A wise choice." text and you leave, we won't have any way to know what the task is based only on that.

**Comment by Zunkrah** [comment]
Oh, okay. I guess I must teleport out too quickly after hitting 3rd chat box which makes it irregular.

Thank you for the response, I appreciate it.
