### ISSUE TITLE
Zalcano plugin: Possible violation of 3rd party client rules

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#12681]
The Zalcano plugin highlights falling rock tiles. This may be violating the 3rd party client rule prohibiting to implement "Anything that indicates where to stand, or not to stand during a boss fight". One could argue the tiles are already indicated by the shadows and the plugin merely highlights those, but I think it should be looked into to make sure.

**Comment by Hydrox6** [comment]
We have the plugin because OSB has one, and Jagex confirmed they were compliant while they had the plugin. If Jagex actually don't want something like that in 3pcs, they should contact both us and OSB to remove it, though they don't seem to care too much about the skilling "bosses"
