### ISSUE TITLE
Option to have NPCs say "Sit" or other 'toxic' phrases when they kill you

### ISSUE THREAD

**Issue by reetzz** [runelite/runelite#12683]
Bit of a jokey one and not serious at all in terms of necessary, but thought it would be a funny idea to add in an option to have NPCs flame you if they kill you. So just some sort of phrase appearing above their head and/or in chatbox if they kill you.

Was just thinking of how salt-inducing having Olm tell you to sit if he kills you, or being called a rat by Graardor.

**Comment by Nightfirecat** [comment]
After discussion, we've decided we aren't interested in adding this feature whether in the main client or in the plugin hub.
