### ISSUE TITLE
RuneLite is way too laggy

### ISSUE THREAD

**Issue by runeliteisbroken** [runelite/runelite#12691]
First time problem; game was running smooth as silk just six hours ago. Logged back in to find a laggy, unplayable mess. I have no plugins installed, and the regular client works just fine. Window would stop stuttering when I had another window open, but would return to unplayable, choppy horseshit when I'd click back over. Windows 10. It's not my internet. It is NOT my GPU or CPU. Restarted the client and my PC several times. Discord was no help so I hope I can find someone who actually knows about this client here.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

**Comment by runeliteisbroken** [comment]
Well I have an issue, that nobody in your brainless Discord could help me with, so pardon me for thinking I was in the right fucking place. This client is fucking trash.
