### ISSUE TITLE
DPS Counter Plugin

### ISSUE THREAD

**Issue by yuskootr** [runelite/runelite#12692]
Currently DPS Counter plugin has 2 issues which makes it useless for many situations.
1) DPS Counter doesn't reset after the target NPC is killed
2) DPS Counter counts damage dealt to any NPC, its not separate for different NPCs, but they are combined

1st issue is when a player uses the plugin to make sure they do most damage to an NPC for example when bossing with an alt account to make sure alt doesn't snioe the kill. If damage doesn't reset, it would be very hard to calculate if the main or alt has dealt more damage for that specific kill.

2nd issue is if you are bossing in a situation where there are multiple NPCs for example like at GWD. DPS counter will count the damage dealt to minions and the boss at the same time, which is not most users want. 

These options could be added as toggles to current plugin. Thanks

**Comment by Adam-** [comment]
added in d8e97dd1f7ac40b2f99e3cba31b78732a9537fcb and e9acabf54915efcdf6e7f8c29aef6d96f245b688
