### ISSUE TITLE
Object Markers on some doors disappear after leaving the area and then coming back.

### ISSUE THREAD

**Issue by Jeaper** [runelite/runelite#12690]
Hello!
I am doing mahogany homes atm, and I started to 'Mark object' for the closed doors, so that I could easily see if I need to open them.

But in this house, and some others, whenever I leave the area, the object markings disappear

**To Reproduce**
1. Go to 'The house next to the Ardougne Zoo and upstairs '
2. Object mark the closed doors'
3. Teleport away
4. Teleport back
5. go back to the house
6. go upstairs and notice the doors not being marked

**Expected behavior**
Doors should still be marked

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.29
 - Launcher version: 1.6.0

**Video**
https://i.imgur.com/mapXoGv.mp4

**Comment by akhtar-u** [comment]
For me the door markings stay after teleporting away but the other markers dissapear like the drawer and cabinets. 

Drawer examine ID is: 40282, dev tools shows it as 40172. Debugger adds 40172 when marking the object. After teleporting away it dissapears. When both examine and dev tools ID is the same, the markers stay. 

Don't know how to fix it, but could be useful to someone else.

**Comment by discomethod** [comment]
FWIW I've noticed this happening at scullisceps as well. I have all the obstacles marked so it's easy to see where to click or if somebody else has cleared the obstacles ahead of me, but it is fairly inconsistent whether or not the obstacles appear marked (I can sometimes clearly see them but they are not marked).

**Comment by ShaunDreclin** [comment]
This and #12318 #10758 #9924 all seem to be the same issue

**Comment by Adam-** [comment]
fixed in e5b5292267b3240f7320c05f4c232e4d66b0142b
