### ISSUE TITLE
Camera plugin outer zoom limit not functioning

### ISSUE THREAD

**Issue by Moedig9191** [runelite/runelite#12709]
**Describe the bug**
The camera plugin for expanding the outer zoom limit no longer works as of the RS update for League II - Trailblazer (Rev 192)

**To Reproduce**
1. Enable Camera plugin
2. Set 'Expand outer zoom limit' to 400 and attempt to zoom out in game, it does not allow the same maximum zoom level as pre-update

**Expected behavior**
Allows zoom out to an extreme distance

**Environment (please complete the following information):**
 - Windows 10 Home 10.0.19041 B19041
 - RuneLite version: 1.6.29
 - Launcher version: 1.6.0

**Comment by abextm** [comment]
fixed by 8a5825fbde105f71099bd9e03beb8a7b65cad7ca
