### ISSUE TITLE
Require position values in @ConfigItem interface

### ISSUE THREAD

**Issue by SoyChai** [runelite/runelite#1270]
[ConfigItems](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/config/ConfigItem.java) omitting this value can potentially be listed in random order between launches, which isn't a great user experience, but this is not currently forbidden.

`int position() default -1;`

I suggest removing this default value and numbering all of the offending configs by hand.

**Comment by MESLewis** [comment]
Soy and I discussed this on Discord and if we get the go ahead from the Admins I would like to help Soy to get this done in a timely manner.
Abex is working on a new config system but he stated that it would be a while before that is ready.

**Comment by psikoi** [comment]
If it's a matter of just adding positions to configs to order them, I can chip in too.

**Comment by deathbeam** [comment]
What about just sorting it by name by default instead? Requires a lot less changes, and having position for each config item is annoying because each change in config file with priorities then requires changing rest of the config file if you want to not insert new config item at the end.

**Comment by SoyChai** [comment]
I know, I just mean the unpositioned configs.

Here's a few examples of such configs where a reasonable code order is already present:

- [RuneLite](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/config/RuneLiteConfig.java)
- [Cannon](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonConfig.java)
- [Item Stats](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/itemstats/ItemStatConfig.java)
- [Puzzle Solver](https://github.com/runelite/runelite/tree/master/runelite-client/src/main/java/net/runelite/client/plugins/puzzlesolver)
- [Runecraft](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftConfig.java)
- [XP Drops](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/experiencedrop/XpDropConfig.java)

**Comment by deathbeam** [comment]
For cannon, alphabethical order is probably what you want there anyway, it will nicely sort colours next to each other, same with item stats, same with xp drops, and most of the stuff there.
WHen adding alphabetical order what would you do is first sort by priority, then by alphabet. So, you can easily add logical groups of fields into configuration by just adding same priority to fields (e.g, would be perfect for color configs to be separate from others).

**Comment by SoyChai** [comment]
For the cannon config, how would `showDoubleHitSpot` be sorted close to `highlightDoubleHitColor`? Even the human-readable names begin with different letters.

**Comment by deathbeam** [comment]
As I said, with combination of alphabethical order and priorities.

**Comment by deathbeam** [comment]
It would require going back and adding the priority to a lot less of the configs, what is goal of my suggestion to this :smile: Also, for new stuff in the configs you would probably just reuse the priority in some logical group so you would not need to alter all the configs after in the change.
