### ISSUE TITLE
Client crashes when attempting to scroll in Runelite when another window is active

### ISSUE THREAD

**Issue by binchicken** [runelite/runelite#12705]
**Describe the bug**
The Runelite client immediately closes/crashes when another windows is active (eg. Chrome) and you mouseover Runelite and scroll. The client immediately closes, and another instance/Runelite icon appears in the taskbar tray each time the  crash happens. Task manager also shows that Runelite is actually closing; it no longer appears under open apps.

I find myself encountering this quite frequently as I will be checking Grand Exchange prices in Chrome, then attempt to scroll my bank or GE history and the client immediately closes.

**To Reproduce**
1. Open Chrome and Runelite side by side so that they are both visible.
2. Log into Runelite.
3. Click Chrome so that it is the active window.
4. Mouseover Runelite without clicking and scroll. A dialog box in OSRS is not necessary for this to occur, happens while on a farm run also for example and I am trying to adjust the camera by zooming out with scroll.

**Expected behavior**
No crashes, I did not encounter this bug before about a month or two ago. 

In Windows settings > Devices > Mouse, clicking 'Scroll inactive windows when I hover over them' makes no difference, still crashes.

**Screenshots**
Screenshot of multiple Runelites in taskbar tray attached.
![Windows10taskbartray](https://user-images.githubusercontent.com/18513843/97363900-5bbc7c00-18f7-11eb-98cf-58e01368cce8.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Home 19041.572
 - RuneLite version: 1.6.29
 - Launcher version: 1.6.0

**Additional context**
Logs are attached.
[launcher.log](https://github.com/runelite/runelite/files/5448188/launcher.log)
[client.log](https://github.com/runelite/runelite/files/5448189/client.log)

Many thanks, huge fan of Runelite and thank you for such a professional and fantastic product to use!

**Comment by Nightfirecat** [comment]
Check your logs folder for an `hs_err_pid` or `jvm_crash_pid` file and upload the most recent one

**Comment by binchicken** [comment]
No such files, only client_2020-**-**.*.log and launcher_2020-**-**.*.log files.

I am looking in C:/Users/<myname>/.runelite/logs

**Comment by Nightfirecat** [comment]
How about in `%localappdata%/RuneLite`?

**Comment by binchicken** [comment]
[hs_err_pid5620.log](https://github.com/runelite/runelite/files/5504170/hs_err_pid5620.log)

Hi Nightfirecat, apologies for my late reply. Attached is the most recent hs_err_pid file, no jvm file in that directory.

**Comment by binchicken** [comment]
Hi there, I think I have located the cause of the crashes. I was still running [X-Mouse Button Control v2.19.2](https://www.highrez.co.uk/downloads/XMouseButtonControl.htm) from when Windows 8.1 didn't allow for scrolling inactive windows natively. With this closed, I can't recreate the crashing. I don't need to use this program anymore so for me, this issue is resolved. Cheers.
