### ISSUE TITLE
Highlight options for Ground Items missing

### ISSUE THREAD

**Issue by rext24** [runelite/runelite#12704]
Hi, 

I was trying to set up my highlight settings today and noticed that there is no longer a highlight > Value option. There is also no longer a highlight valuation calculator. 

I'm not sure if these features were removed intentionally or not but they were listed on the runelite features section on the homepage. 

Thank you!

**Comment by Alexsuperfly** [comment]
The price highlight tiers cover the use that old option had, it was removed because of user confusion.  The website/wiki docs aren't updated much for little details like that, sorry they were misleading.

**Comment by rext24** [comment]
> The price highlight tiers cover the use that old option had, it was removed because of user confusion. The website/wiki docs aren't updated much for little details like that, sorry they were misleading.

Ohhh okay. 

So by setting say my Low Tier value to 3k, and then setting the notify for tier >= low, I can accomplish the same thing?
Thank you for your quick reply.

**Comment by Alexsuperfly** [comment]
correct
