### ISSUE TITLE
Suggestion: Add lap count chat command

### ISSUE THREAD

**Issue by thomasbh92** [runelite/runelite#12706]
A new chat command to show others how many laps of a certain agility course you've completed would be a welcome addition. The new lap counter recently added to the game could be used to pull the numbers from.
i.g. !laps seers, !laps wilderness
Perhaps even including your personal best for a course could be added, but that may be unnecessary.

**Comment by Broooklyn** [comment]
Commands for lap counts already exist under `!kc`, for example `!kc ardy` or `!kc ardougne rooftop`
