### ISSUE TITLE
Graphic Issue on 3090

### ISSUE THREAD

**Issue by Bubbles67** [runelite/runelite#12713]
https://i.imgur.com/g1mECml.png happens over time randomly. Mostly occurs if I hover my mouse hover the side panel. I fix this by doing WIN + CTRL + SHIFT + B to reset the graphics driver.

**Comment by Hydrox6** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

For further questions of support, please join the [Discord](https://runelite.net/discord)
