### ISSUE TITLE
Key Remapping is working differently than it used to.

### ISSUE THREAD

**Issue by NightmareSHW** [runelite/runelite#12712]
Description:
I'm not sure if it is something different within Runelite or something that happened to the game client, but I used to be able to press the buttons on the side of my mouse and they would function as numbers and menu/dialogue options (or F-keys) simultaneously. For example, my Numpad-1 key is bound to Spacebar, but no longer functions as a "1" when in a menu or dialogue, whereas it used to before.

Replication:
You must own an MMO mouse (in my case, a Corsair Scimitar).
1. Remap "1" on the side of the mouse to NumPad-1.
2. Remap Space in Runelite's Key Remapping plugin to NumPad-1
3. Attempt to do something such as create unpowered orbs (pressing 1 should, according to the Key Remapping plugin, hit space, therefore repeating the last created item in the menu) or open a one-track dialogue. No issues thus far for me.
4. Open a dialogue or menu with multiple options (as shown below). Pressing "1" on the side of my mouse no longer selects the first dialogue option like it used to before.

I expected the dialogue to continue with "Yes" after pressing 1, but this is no longer working. It still works when attempting to substitute the key for "Space," however.

![](https://puu.sh/GHHSc/1c67964b18.png)
Attempting to press the 1 key on the side of my mouse here (which, as previously stated, is rebound to NumPad-1, and NumPad-1 is used for Space in Runelite's Key Remapping plugin) continues the dialogue as expected.

![](https://puu.sh/GHHxE/12931fe58c.png)
In this picture, I can no longer press the 1 key to continue the dialogue with "Yes."

OS: Windows
RuneLite Version: 1.6.29
Oldschool Revision: Rev 192
Launcher Version: 1.6.0

**Comment by Hydrox6** [comment]
Restart your client

**Comment by NightmareSHW** [comment]
Still not working.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
