### ISSUE TITLE
Programmer Looking to Help :)

### ISSUE THREAD

**Issue by NolanRudolph** [runelite/runelite#12729]
Hey, sorry I didn't know where else to put or ask this. I love your addon and would love to work on implementing quests that don't exist yet! Let me know if you're interested, my email is nolanrudolph1@gmail.com or you can reply and I'm sure I'll be notified. I've got a bachelor's in science for comp sci and do all things tech related.

**Comment by Nightfirecat** [comment]
You can click the support link for the quest helper plugin on the plugin hub to find its repository. You can also likely contact the owner directly via email, GitHub, or on Discord.
