### ISSUE TITLE
Thieving: Pickpocketing stun timer over player (consider eating while stunned)

### ISSUE THREAD

**Issue by CptBrian** [runelite/runelite#12720]
(A timer like those you see on trees and rocks)
• Place over player or the player's head.
• Timer shows stun duration until you can pickpocket again.
• This is not the same as the timer until you can move again(explained below)
• Eating while stunned will extend/pause the stun timer(beyond its visible effect), but only for your ability to pickpocket, not move.
• The duration it extends/pauses should be however long you spent eating while stunned.
• Eating while *not* stunned does not affect the pickpocket cooldown.
I'm sure with a little trial-and-error, you'll figure out the right timings.

**Comment by Mrnice98** [comment]
I like this idea, I am going to take a look into implementing something along these lines in the coming days.

**Comment by Adam-** [comment]
added in #13552 as an infobox
