### ISSUE TITLE
Allow profile-specific time tracking

### ISSUE THREAD

**Issue by asmith-personal** [runelite/runelite#12738]
**Is your feature request related to a problem? Please describe.**
When playing across multiple account profiles (e.g. leagues vs. main game), it's difficult/impossible to track which patches are planted on which profile since the timers are shared.

**Describe the solution you'd like**
Profile-specific time tracking. If I'm in a league world, show my league profile's time tracking. If I hop to a normal world, show my normal profile's time tracking (and/or a drop-down to switch between them manually at will)

**Describe alternatives you've considered**
Let me clear currently tracked items in the 'time tracking' plugin.

**Comment by discomethod** [comment]
Having notifications persist across profiles could be useful, e.g. to get a reminder to switch back to your main profile to do birdhouses while you are mostly playing your league profile.

**Comment by ShaunDreclin** [comment]
This should be done in general for any place there is a per-user configuration saved for something

**Comment by Nightfirecat** [comment]
Profile support was added in f0787178229d967477fea5d52ae35022f712fbde. While leagues has ended, this work will remain in the client, available for us to utilize for future alternate-profile game modes.
