### ISSUE TITLE
XP tracker messes up at Tears of Guthix

### ISSUE THREAD

**Issue by eklypss** [runelite/runelite#1273]
Long story short, I did ToG and upon completion the XP tracker messed up, assumed I gained all XP I have in every single skill in the game: [image for reference](https://i.imgur.com/KuOxdRw.png)

Previously it has worked fine there, not sure if you can replicate it since you can only do it once a week and last week it was fine.

**Comment by deathbeam** [comment]
Hmmm, maybe the cached XP should be reset upon logout that should fix the issue.
