### ISSUE TITLE
[REQUEST] Add a value for experience multipliers for future Leagues

### ISSUE THREAD

**Issue by JangoD00D** [runelite/runelite#12732]
This would assist in knowing how many actions you will need to do during leagues when players are changing tasks repeatedly or aiming for efficiency. This league could possibly be the only one with changing experience modifiers.

**Describe the solution you'd like**
A field with a custom value or a drop down menu with available experience modifiers. Examples 5x, 8x, 12x, 16x which are available in the current Trailblazer League (2020).

**Describe alternatives you've considered**
This is easily doable with an external calculator and experience values obtained through the wiki to get your number goal.

**Screenshot**
![runelitesuggestion](https://user-images.githubusercontent.com/73824203/97855513-d8b96e00-1cc8-11eb-8815-869b2000e8be.png)

Thank you for your time and I appreciate your hardwork.

**Comment by Hydrox6** [comment]
Kind of a duplicate of #3027, given [Nightfirecat's comment](https://github.com/runelite/runelite/issues/3027#issuecomment-565680701)

**Comment by JangoD00D** [comment]
> Kind of a duplicate of #3027, given [Nightfirecat's comment](https://github.com/runelite/runelite/issues/3027#issuecomment-565680701)

Yikes. I apologize. Would love to see the feature, hehe. Thanks for the headsup.
