### ISSUE TITLE
Abby sire timer still not working

### ISSUE THREAD

**Issue by ckazenske** [runelite/runelite#12747]
Hello. I believe this issue has already been brought up, and the latest version was supposed to fix it, but I am still having an issue with the Abby Sire timer. I am using RuneLite version 1.6.30. When stunning the sire the timer does not appear at all. However, when the stun wears off, the timer starts.

**Comment by ckazenske** [comment]
Sorry, it's not when the stun wears off that the timer starts, it's when I re-stun it while it's already stunned that the timer starts.

**Comment by Adam-** [comment]
fixed in a4daa407a1f23e857d0b4f4417c4fad9ff1f7521
