### ISSUE TITLE
Differentiate between Plugin Hub plugins and built-in ones in the Configuration panel

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#12750]
There currently isn't any easy way to determine which plugins are from the Plugin Hub if you want to uninstall them. (or just get a reminder of what you've installed)

Splitting them into sections/tabs or adding an icon/text colour change to the Plugin Hub plugins would work.

**Comment by Hydrox6** [comment]
You can click the down arrow in the search bar and select `Plugin Hub` to see all the hub plugins that are installed.

**Comment by ShaunDreclin** [comment]
Whoops, I'm blind 😏

Thanks haha
