### ISSUE TITLE
checkHighHitpoints for nmz afking

### ISSUE THREAD

**Issue by Zalmix** [runelite/runelite#12756]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when I afk for too long and I get up to 10hp without using my locator orb, so I would want a plugin added to either NMZ or idlenotifier that could have a threshold you could set so you don't waste too much absorption points.

**Describe the solution you'd like**
I want added to the idlenotifierplugin/nmz plugin a too high hp notifiers so I can afk a bit more. It shouldnt too hard with the checkLowHitpoints being there already

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered. I know I could use timers but sometimes I remember to use my locator orb

**Additional context**

**Comment by Alexsuperfly** [comment]
the `NMZ Utilties` plugin does this on the hub afaik
