### ISSUE TITLE
Disable custom chrome on MacOS by default

### ISSUE THREAD

**Issue by LullaAI** [runelite/runelite#12751]
I have read a lot of threads about this feature, but I don't find anything related to it, so I don't know if you are going to develop it in the future or not. I think that it would be nice to be able to run Runelite with fullscreen mode on Mac

**Comment by lukegg** [comment]
This is achievable by disabling "Enable custom window chrome" under RuneLites' configuration plugin. It restores the OS's native titlebar, thus allowing fullscreening on macOS. This screenshot is obviously from Windows, but it works as expected on Mac as I was utilizing it yesterday.
![image](https://user-images.githubusercontent.com/7662793/98439533-6098e100-20ea-11eb-87ad-89853a8b0e7f.png)

**Comment by LullaAI** [comment]
It worked like a charm.

I think it could be a good idea to put it like default option.

Thanks!

**Comment by Optumasfx** [comment]
Agreed, can this please be the default option for macs? @Adam-

**Comment by makingcomment** [comment]
Definitely don't make custom chrome the default. The button to toggle the sidebar that's added near the minimap with custom chrome disabled is not obvious.

**Comment by Optumasfx** [comment]
> Definitely don't make custom chrome the default. The button to toggle the sidebar that's added near the minimap with custom chrome disabled is not obvious.

I'm not sure what you are talking about? can you please show us a screenshot?

I personally think disable chrome should be default on mac because it breaks the full screen feature and the ability to use password managers such as 1password. It looks better too 👍

**Comment by kslop** [comment]
> > Definitely don't make custom chrome the default. The button to toggle the sidebar that's added near the minimap with custom chrome disabled is not obvious.
> 
> I'm not sure what you are talking about? can you please show us a screenshot?
> 
> I personally think disable chrome should be default on mac because it breaks the full screen feature and the ability to use password managers such as 1password. It looks better too 👍
> 
> https://1password.community/discussion/94251/cant-autotype-password-to-specific-application

doesn't take long to turn it off

**Comment by makingcomment** [comment]
> > Definitely don't make custom chrome disabled by default. The button to toggle the sidebar that's added near the minimap with custom chrome disabled is not obvious.
> 
> I'm not sure what you are talking about? can you please show us a screenshot?

With custom chrome disabled, the toggle the sidebar is moved to the pictured button, which is only visible on hover.

<img width="30" alt="custom_chrome_sidebar_toggle" src="https://user-images.githubusercontent.com/49528120/104407700-d6c12600-5527-11eb-9a6f-716f18e017b3.png">

**Comment by Nightfirecat** [comment]
I think that is a separate but related concern. It seems worthwhile to investigate a better UX for toggling the sidebar with custom chrome disabled whether or not we choose to disable custom chrome on MacOS by default. I didn't see any open issues for this, one should be created so that can be discussed there.

**Comment by psikoi** [comment]
Maybe a more sensible solution is to display a dialog/message asking mac users if they'd like to turn it off, with a quick explanation on why they might want to.

Nothing too intrusive that would delay their gameplay.

**Comment by kslop** [comment]
> Maybe a more sensible solution is to display a dialog/message asking mac users if they'd like to turn it off, with a quick explanation on why they might want to.
> 
> Nothing too intrusive that would delay their gameplay.

It should be off by default. It literally breaks mac features

https://1password.community/discussion/94251/cant-autotype-password-to-specific-application

**Comment by kslop** [comment]
It should be off by default. It literally breaks mac features

https://1password.community/discussion/94251/cant-autotype-password-to-specific-application

Unless I am missing something what are the benefits of keeping it on for a mac user?

**Comment by makingcomment** [comment]
> Unless I am missing something what are the benefits of keeping it on for a mac user?

Better sidebar UX, as I mentioned in my post.

**Comment by kslop** [comment]
> > Unless I am missing something what are the benefits of keeping it on for a mac user?
> 
> Better sidebar UX, as I mentioned in my post.

That is subjective but what is not is that it is breaking built in mac features which includes security.

**Comment by makingcomment** [comment]
> breaking built in mac features which includes security

1Password is not a built-in mac feature.

**Comment by kslop** [comment]
> > breaking built in mac features which includes security
> 
> 1Password is not a built-in mac feature.

Copy and paste is which does not work when it is enabled.

**Comment by kslop** [comment]
> > breaking built in mac features which includes security
> 
> 1Password is not a built-in mac feature.

Copy and paste is which does not work when it is enabled for 2FA.

**Comment by makingcomment** [comment]
> > > breaking built in mac features which includes security
> > 
> > 
> > 1Password is not a built-in mac feature.
> 
> Copy and paste is which does not work when it is enabled.

Copy and paste still works with custom chrome though... I just tested it.
Can you describe the steps you're taking for it to fail? Are you sure you have the login screen plugin's `Ctrl-V` setting enabled?

**Comment by kslop** [comment]
> > > > breaking built in mac features which includes security
> > > 
> > > 
> > > 1Password is not a built-in mac feature.
> > 
> > 
> > Copy and paste is which does not work when it is enabled.
> 
> Copy and paste still works with custom chrome though... I just tested it.
> Can you describe the steps you're taking for it to fail? Are you sure you have the login screen plugin's `Ctrl-V` setting enabled?

Thank you that fixed it. Do you know why Ctrl-V setting is not enabled by default?

**Comment by Optumasfx** [comment]
So you want to break features for OSX because you don't like the UX? Even the official client does not have a custom chrome window. Everything on OSX/Linux is unified for a reason.

**Comment by Hydrox6** [comment]
The official client does not have a custom window because it's simply a wrapper around the game itself so it can run outside of the browser, not providing any UI to the player like RL's UI does. If you want the unified UI, you can already disable Custom Chrome; this issue isn't about its existence

**Comment by Optumasfx** [comment]
> The official client does not have a custom window because it's simply a wrapper around the game itself so it can run outside of the browser, not providing any UI to the player like RL's UI does. If you want the unified UI, you can already disable Custom Chrome; this issue isn't about its existence

Shouldn't it be the other way round? if you don't want a unified UI you can enable the custom chrome feature but let the users know that is it breaking osx features for a cosmetic look.

**Comment by Hydrox6** [comment]
It's on by default since RL is unified across all versions. This is not unique to this; a lot of programs do it to have a consistent brand.

**Comment by Optumasfx** [comment]
Adam is open to changing that for linux so surely that would apply for osx?

Screenshot:
<img width="575" alt="Screenshot 2021-01-13 at 2 38 48 pm" src="https://user-images.githubusercontent.com/76658119/104466381-12ea9a00-55ad-11eb-9e70-29fe6b8efdb9.png">

**Comment by makingcomment** [comment]
> So you want to break features for OSX because you don't like the UX?

Absolutely yes

**Comment by Optumasfx** [comment]
> > So you want to break features for OSX because you don't like the UX?
> 
> Absolutely yes
> 
> (ideally, everything would work with custom chrome. But when I'm using RuneLite, my priority is having RuneLite work in the way I want)

That is why there is an option to enable it? it should be off by default to give the best experience for the user per the operating system.

**Comment by kslop** [comment]
> > > So you want to break features for OSX because you don't like the UX?
> > 
> > 
> > Absolutely yes
> > (ideally, everything would work with custom chrome. But when I'm using RuneLite, my priority is having RuneLite work in the way I want)
> 
> That is why there is an option to enable it? it should be off by default to give the best experience for the user per the operating system.

Agreed +1

**Comment by makingcomment** [comment]
> > > So you want to break features for OSX because you don't like the UX?
> > 
> > 
> > Absolutely yes
> > (ideally, everything would work with custom chrome. But when I'm using RuneLite, my priority is having RuneLite work in the way I want)
> 
> That is why there is an option to enable it? it should be off by default to give the best experience for the user per the operating system.

I think it should be on by default to give the best experience for the user per the program that they have actively decided to use.

**Comment by Optumasfx** [comment]
Adam and many respected members like dkvl are not opposed to changing it to being disabled by default.

**Comment by makingcomment** [comment]
> Adam and many respected members like dkvl are not opposed to changing it to being disabled by default.

There's a difference between "not opposed" and "for"

**Comment by Optumasfx** [comment]
Okay. I just personally think it should be disabled due to breaking critical features for osx and can cause performance issues. Brooklyn can attest to this.

I am happy to let anyone view this on teamviewer. having it enabled does not make sense for osx but for people like you there should be an option to enable it.

**Comment by makingcomment** [comment]
> Okay. I just personally think it should be disabled due to breaking critical features for osx

Fullscreen and password managers are not critical features imo. Are there other critical features you're referring to?

> and can cause performance issues

What performance issues does it cause? That hasn't been brought up in this thread before.

> for people like you there should be an option to enable it.

I think there are more people like me than there are people like you (based on absolutely no evidence 🙃). If that's the case, it would be better to keep it opt-out than to switch to opt-in.

**Comment by kslop** [comment]
People who are in the Apple ecosystem tend to be professionals so fullscreen is important if you value multiple desktops to multi task

**Comment by Optumasfx** [comment]
Fullscreen enables multiple desktops 

> > Okay. I just personally think it should be disabled due to breaking critical features for osx
> 
> Fullscreen and password managers are not critical features imo, and based on @kslop's comments, the later may not even be broken. Are there other critical features you're referring to?
> 
> > and can cause performance issues
> 
> What performance issues does it cause? That hasn't been brought up in this thread before.
> 
> > for people like you there should be an option to enable it.
> 
> I think there are more people like me than there are people like you (based on absolutely no evidence 🙃). If that's the case, it would be better to keep it opt-out than to switch to opt-in.

Password managers are actually really important especially when most people reuse passwords which are leaked in database breaches. Good passwords should not be remembered.

**Comment by Optumasfx** [comment]
Password managers are actually really important especially when most people reuse passwords which are leaked in database breaches. Good passwords should not be remembered.

**Comment by Optumasfx** [comment]
Password managers are actually really important especially when most people reuse passwords which are leaked in database breaches. Good passwords should not be remembered.

please refer to https://haveibeenpwned.com/Passwords

even Jagex themselves recommend their users to use a Password Manager? https://support.runescape.com/hc/en-gb/articles/206558669-Password-creation-advice

**Comment by kslop** [comment]
> I think there are more people like me than there are people like you

There are people even complaining on https://1password.community/discussion/94251/cant-autotype-password-to-specific-application

**Comment by LlemonDuck** [comment]
> > I think there are more people like me than there are people like you
> 
> There are people even complaining on https://1password.community/discussion/94251/cant-autotype-password-to-specific-application

If anything, this shows that it's more of a 1Password problem than a RuneLite problem imo

**Comment by Optumasfx** [comment]
> If anything, this shows that it's more of a 1Password problem than a RuneLite problem imo

Maybe if that was the only problem but it breaks full screen and multiple desktops.

**Comment by makingcomment** [comment]
> Password managers are actually really important especially when most people reuse passwords which are leaked in database breaches. Good passwords should not be remembered.
> 
> please refer to https://haveibeenpwned.com/Passwords
> 
> even Jagex themselves recommend their users to use a Password Manager? https://support.runescape.com/hc/en-gb/articles/206558669-Password-creation-advice

Does custom chrome _actually_ break password managers? Like I said, kslop's comments make it seem like it might be an issue with the login plugin rather than the custom chrome

>I think there are more people like me than there are people like you
> > There are people even complaining on https://1password.community/discussion/94251/cant-autotype-password-to-specific-application

This is a textbook example of selection bias.

**Comment by Optumasfx** [comment]
> Does custom chrome _actually_ break password managers? Like I said, kslop's comments make it seem like it might be an issue with the login plugin rather than the custom chrome

Yes Password Managers can't detect the window and require auto typing for it to work.

>You can use multiple desktops on a mac without putting an app in fullscreen...

But not with the best experience.

**Comment by Hydrox6** [comment]
> Yes Password Managers can't detect the window and require auto typing for it to work.

Except KeePass apparently works fine

**Comment by dekvall** [comment]
Resolved by 8cc7448f58f62c28d752d4717af840499405f6f5

**Comment by Optumasfx** [comment]
> Resolved by [8cc7448](https://github.com/runelite/runelite/commit/8cc7448f58f62c28d752d4717af840499405f6f5)

If its on keep game size instead of keep windows size with custom chrome its a bit funky

<img width="220" alt="Screenshot 2021-01-13 at 5 14 37 pm" src="https://user-images.githubusercontent.com/76658119/104485914-fb1e1080-55c2-11eb-806e-f590718d5268.png">
