### ISSUE TITLE
Can we get the ability to disable the chats scrollbar?

### ISSUE THREAD

**Issue by SandroVA** [runelite/runelite#12755]
**Is your feature request related to a problem? Please describe.**
When being able to click through the chatbox is enabled sometimes you accidentally click on the scrollbar and it moves the chat up which is annoying.

**Describe the solution you'd like**
Ideally an easy way to hide / show the scrollbar.

**Describe alternatives you've considered**
You could also have a button on screen / rightclick option to lock / unlock the scrollbar.

**Additional context**
https://i.imgur.com/WizwQtn.png

**Comment by Broooklyn** [comment]
You can change the location of the scrollbar to the left in Advanced Options. That stopped my misclicking personally.
![image](https://user-images.githubusercontent.com/54762282/98417591-3a723300-204f-11eb-8fca-a15461c7aadb.png)

![image](https://user-images.githubusercontent.com/54762282/98417532-1c0c3780-204f-11eb-9c4e-0c6b1969def5.png)

**Comment by SandroVA** [comment]
Ahh oops! I don't know how I didnt see that setting. Question how did you get that dark interface?

**Comment by Nightfirecat** [comment]
That is part of the "Resource packs" hub plugin
