### ISSUE TITLE
Right Click Clan/Team for Pkers/Raiders

### ISSUE THREAD

**Issue by YankinBrow** [runelite/runelite#12758]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**A right click function to search a player in a clan data base. 
Allow clans to actively fill out the database themselves with a way to confirm they are the named account
Follow username changes in the database**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by MESLewis** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
