### ISSUE TITLE
NPC Agression Timer - incorrectly displayed zones as of 11th November

### ISSUE THREAD

**Issue by GasertTheGreat** [runelite/runelite#12776]
I haven't seen anything in update log, but it looks like there have been a hidden update to aggression zones. Yesterday the zones shown by the "Aggression Timer" were tile-perfect. As of today (11th of November) they are incorrect.

1. Turn on aggression timer for a specific monster.
2. Go to an area with said monster and wait for the aggression to run out (10min).
3. Run out of the aggression zone (currently inactive) a few tiles past.
4. Aggression timer and zone resets to new ones.
5. Run back to the monsters - they do not attack you, even though the timer shows they should.
6. Run far away (approximately 10 tiles past the shown zone) and go back - the monsters are aggro again.

So far, the zone was shown correctly in approximately 15% cases, majority was wrong.
The correctly shown zones mean, I only needed to run out a single tile and it reset correctly. The incorrect I ran out around 7 tiles and agro still not reset.
This implies the change is not simply "X tiles larger area" but rather different calculation/shape for the agro zones.

I will try to find a pattern in my free time, so far unsuccessful.

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - RuneLite version: 1.6.30
 - Launcher version: 2.1.3

**Comment by Nightfirecat** [comment]
I have not been able to experience this issue. I recommend teleporting to two distant areas to reset the plugin's knowledge of your aggression area, then returning to the location with these monsters to ensure it had been set correctly.
