### ISSUE TITLE
Ardougne cape does not count as a teleport item in Menu Entry Swapper

### ISSUE THREAD

**Issue by lolidkman** [runelite/runelite#12781]
Curious if this is intended.

After selecting "teleport item" under menu entry swapper, the crafting cape becomes left-click to teleport. But Ardougne cape does not.

**Comment by Nightfirecat** [comment]
This is intended--that swap specifically only swaps "Teleport" and "Rub" options for teleportation items and jewellery. You can [use the customizable shift-click options of the plugin](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#customizable-shift-click) to get shift+left-click teleports with your Ardougne cloak.

**Comment by Broooklyn** [comment]
Just to piggyback before this is lost to the ether, `Menu Swapper Extended` on the plugin hub has the ability to change the left click option for the Ardougne Cloak.

**Comment by lolidkman** [comment]
@Nightfirecat then why does it swap the options for the crafting cape?

**Comment by Nightfirecat** [comment]
Because the crafting cape has a "Teleport" option.
