### ISSUE TITLE
Determine what a player is attacking

### ISSUE THREAD

**Issue by maxbla** [runelite/runelite#12798]
**Is your feature request related to a problem? Please describe.**
I'm writing a plugin that (in the course of doing something more substantial) must determine what, if anything, a `Player` is attacking. I don't think this is currently possible in general.

**Describe the solution you'd like**
an api for `Player` or `Actor` that looks something like either
```java
// @return the actors that are attacking this (or null if not being attacked)
List<Actor> getAttackers()
```
or 
```java
// @return the actor that this is attacking (or null if not attacking)
Actor getAttacking()
```
If this is not possible, I could hack it with `onInteractingChanged` + `AnimationId`s for attacking, however `AnimationId`s for most attacks appear to be missing (I would be happy to add as many as I can find in a PR).

**Describe alternatives you've considered**
I have considered using `onInteractingChanged` as the opponent information plugin does, but I don't know how to distinguish between attacking and any other interaction like following or trading (and the opponent information plugin doesn't distinguish either).

**Comment by Adam-** [comment]
This mostly isn't possible for us to do, because there is no exhaustive list of all possible combat animations.

**Comment by Nightfirecat** [comment]
Generally speaking, you can safely assume any NPC with an "Attack" option which is interacting with, or being interacted by a player is attacking or being attacked.

**Comment by maxbla** [comment]
Would you entertain a pull request which added more `AnimationID`s for attacking and also added a property `isCombatAnimation` to `AnimationID` which tried to exhaustively list ?

This is outside my area of expertise, but doesn't the client know if the Player is attacked for the purpose of auto-retaliate? Or is auto retaliation performed server side?

**Comment by Adam-** [comment]
That seems fine if you want to try that, but it isn't possible to prove a list is exhaustive. Auto retaliate is server side.

**Comment by maxbla** [comment]
Thanks @Nightfirecat, but my use case involves players, not NPCs in a way where I don't think I can make that assumption.

**Comment by Nightfirecat** [comment]
Perhaps you can follow [how the PVP Performance Tracker plugin](https://github.com/Matsyir/pvp-performance-tracker) determines when you're in combat then? Unfortunately, the client has basically no information regarding active combat status beyond what's already exposed. (interacting)

**Comment by maxbla** [comment]
That plugin uses the same trick we've been discussing here, with additional sanity checks (like that both interacting Actors are players). Here's a comment from their code
```java
// Keep track of a player's new target using this event.
// It's worth noting that if you aren't in a fight, all player interactions including
// trading & following will trigger a new fight and a new opponent. Due to this, set the lastFightTime
// (in FightPerformance) in the past to only be 5 seconds before the time NEW_FIGHT_DELAY would trigger
// and unset the opponent, in case the player follows a different player before actually starting
// a fight or getting attacked. In other words, remain skeptical of the validity of this event.
@Subscribe
public void onInteractingChanged(InteractingChanged event)
{
```
Additionally, the authors of PVP performance tracker mention in comments that the plugin won't work as intended in multi-combat fights, which I aim to support. I suspect accurate attack detection is possible using a hybrid of Interacting and Animations.

Thanks again for the help. I'll write a plugin with the implementation of attack detection that I'm imagining and if it is good enough, try to get it merged into Runelite proper.

**Comment by maxbla** [comment]
Closing because there's no perfect way to do this in general.
