### ISSUE TITLE
Visual bug - red screen

### ISSUE THREAD

**Issue by BeachPlease9** [runelite/runelite#12794]
**Describe the bug**
The right half of the Runelite screen is red tinted. This only happens on Runelite and not the normal osrs client. I have tried uninstalling and reinstalling the client and clearing the cache.

**To Reproduce**
Every time I open Runelite and play the game.

**Expected behavior**
I expect this to be normal coloring.

**Screenshots**
![image](https://user-images.githubusercontent.com/74418504/99086609-5f0a6580-258f-11eb-9a06-bf9404e428ce.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.31
 - Launcher version: 2.1.5

**Comment by Hydrox6** [comment]
To fix right now, choose a different mode for UI Scaling (not Bilinear or Nearest Neighbor)

**Comment by BeachPlease9** [comment]
That worked. Thank you Hydrox

**Comment by Adam-** [comment]
fixed in ad4d1787a15a733ee2883c140055b0d53ba3f6a7
