### ISSUE TITLE
Minimum infobox size auto wrapping

### ISSUE THREAD

**Issue by RobinVandeWalle** [runelite/runelite#12805]
When I alt drag my boost infoboxes to a single column with my infobox size set to 31px or higher, it works as intended.
![image](https://user-images.githubusercontent.com/36442094/99317017-9a45b680-2865-11eb-8834-2f0e2342e437.png)
When I set my infobox size to 30px or lower, it automatically puts the stats into 2 columns, and alt dragging it back into 1 column doesn't work.
![image](https://user-images.githubusercontent.com/36442094/99317124-ca8d5500-2865-11eb-9622-a4eb1a357f08.png)
This used to be very easy to setup with the "display infoboxes vertically" setting, but I assume that was replaced in the 1.6.11 release.
Is there some setting I am missing? Or is this working as intended.

**Comment by Alexsuperfly** [comment]
shift right click flip

**Comment by Nightfirecat** [comment]
This can be seen in the topmost gif of [our 1.6.28 release blog post](https://runelite.net/blog/show/2020-10-07-1.6.28-Release).
