### ISSUE TITLE
Mine indicator near the ladder to the Ourania cave is incorrect

### ISSUE THREAD

**Issue by CerpinTaxt-OSRS** [runelite/runelite#12801]
**Describe the bug**
When hovering the mouse over the mine indicator on the world map for the rocks just north of the Ourania teleport, it suggests there are 2 copper and 1 tin rock, when in reality, there are 3 copper rocks

**To Reproduce**
1. Open the world map
2. Pan over to the Ourania cave entrance
3. Hover your mouse over the mine indicator nearby
4. Compare that to the actual ores available.

**Screenshots**
https://i.imgur.com/aHdz3VY.png
https://i.imgur.com/CRimWZG.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.31.1
 - Launcher version: 1.6.0

**Comment by dekvall** [comment]
The rock with tin is further south.

**Comment by CerpinTaxt-OSRS** [comment]
I didn't see the tin rock, but there's still 3 copper nodes there too.
