### ISSUE TITLE
Remove unused function warnings

### ISSUE THREAD

**Issue by maxbla** [runelite/runelite#12812]
I noticed that IDEs mark functions annotated `net.runelite.client.eventbus.Subscribe` as unused, as they are not directly called by main, but are hooks for runelite. I think this could be fixed by adding `@SuppressWarnings("unused")` to Subscribe.java. This would be a breaking change, as duplicate `SupressWarnings` annotations are a compiler error.

An alternative non-breaking change would be to create a new annotation combining `@Subscribe` with `@SupressWarnings("unused")`

**Comment by Nightfirecat** [comment]
This can be fixed by adjusting your IDE settings to recognize `@Subscribe` as an entry point.

**Comment by ShaunDreclin** [comment]
If anyone else is looking for that setting in IntelliJ:
![Screenshot](https://user-images.githubusercontent.com/5851433/99546085-0f0f1280-2984-11eb-9ed0-5dda1c103fb2.png)
