### ISSUE TITLE
npc indicators: Indicators aren't updated when NPCs change state

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#12810]
I had `Afflicted` highlighted to use up my leftover Serum 208s in Mort'ton but they remained highlighted after they transformed into `Mort'ton Local`s.

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.6.32-SNAPSHOT

**Comment by Hydrox6** [comment]
Duplicate of #5161
