### ISSUE TITLE
Account plugin: Local settings are wiped after account creation

### ISSUE THREAD

**Issue by SoyChai** [runelite/runelite#1281]
Anecdote from a user on discord. The plugin is supposed to retain local settings separately, but it seems these aren't restored after logging out. We probably need more details.

**Comment by remedyremedy** [comment]
if this issue can't be fixed please make a warning that this will occur, wasted hours of time

**Comment by remedyremedy** [comment]
A fix Lotto suggested is just to sign out (up here: http://prntscr.com/jdrr08 ). This reset my settings back but not my notes which is better than having to redo everything
