### ISSUE TITLE
Screen doesnt fit the full window 

### ISSUE THREAD

**Issue by Idkimlosthelp** [runelite/runelite#12826]
**Describe the bug**
The game doesnt fit the full window, no matter how I scale the window. It cuts off the top and right side of the screen, making it black, and causes a weird duplicating, and flickering effect in those areas. I can still click on the black area and my character will move to the spot selected. 

**Screenshots**
![osrs ss](https://user-images.githubusercontent.com/74840536/99889652-efdee200-2c1c-11eb-88af-f9c8982e8997.png)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.6.32
 - Launcher version: 2.1.5

**Additional context**
Ive uninstalled and reinstalled RuneLite, updated my gpu drivers, and restarted my computer. It looks fine on the normal client but then I have to use the normal client. 
I have two monitors but theyre the exact same models, and im running the game on the main monitor. Messing with the RuneLite game size does nothing but zoom me in more. Ive tried the DPI suggestion and turned off custom chrome. Sorry if this has been answered but Ive looked for an hour and couldnt find any suggestions that worked. 

**Logs**
[client.log](https://github.com/runelite/runelite/files/5578667/client.log)
[launcher.log](https://github.com/runelite/runelite/files/5578668/launcher.log)

**Comment by MESLewis** [comment]
Reopen this issue if the problem can be recreated on RuneLite 1.6.36.2 or later.
