### ISSUE TITLE
Interface Styles: Menu text loses its drop shadow when alpha is dropped below 255

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#12822]
**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/5851433/99833391-e6c41700-2b2f-11eb-99fc-970e4f1dd826.png)
![Screenshot](https://user-images.githubusercontent.com/5851433/99833395-e88dda80-2b2f-11eb-8153-58aeb97e9ded.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.33-SNAPSHOT

**Comment by Nightfirecat** [comment]
This is now fixed as of client patch 981291173.22
