### ISSUE TITLE
Varrock Museum Uncleaned finds Plugin

### ISSUE THREAD

**Issue by kreeptik** [runelite/runelite#12820]
Since the update of the Varrock Museum in April 2019, there has been an active community of roughly 100 players there.
The reason why people do this content is because there is a 1/97.5 chance of getting an Antique lamp of 500 experiences. It creates unique builds like : level 25 combat w/ 99 hitpoints, level 27 combat w/ 99 defence, level 35 w/ 99 attack and level 3 combat w/ 99 slayer.
These builds takes approximately 6500 hours to complete. Since getting lamps is all RNG, we would like a plugin that provide us with some valuable information and that would ultimately help us with our long-term goal.

We would like a plugin that tracks three things : 
1. The amount of Dig Site specimen rocks we took. !ref1
2. The amount of Artifacts we got from cleaning at the Specimen table. The artifacts are : Pottery, Jewellery, Old chipped vase and Arrowheads. !ref2
3. The amount  of Antique Lamps we got from the Storage crate. !ref3

Also, it would be nice to have an option to reset the tracker. 

Thanks for reading, 
Kreeptik

![references](https://user-images.githubusercontent.com/74718003/99672312-3972d580-2a41-11eb-809c-04edd59b3a09.png)

**Comment by acdvs** [comment]
I don't participate in this, but I'm interesting in developing a plugin for it. Seems pretty straightforward. It would definitely have to be an external plugin since the scope is extremely limited and the audience isn't very large.

**Comment by abextm** [comment]
Added as `specimin-cleaning` to the PluginHub
