### ISSUE TITLE
Loot Tracker

### ISSUE THREAD

**Issue by rabitwarior2** [runelite/runelite#12839]
I think it would be super cool if you could select 2 or 3 "entities" on Loot Tracker that you want to carry over if Runelite updates, I'm always really sad when I'm actively grinding an activity, and have a high KC or loot tab, and it resets on update, obviously we don't want EVERYTHING to carry over as it would become a data storage issue for those who don't reset their loot tracker, but being able to explicitly select an option of "long term save" until you choose to reset it, and being able to do this with between 1-3 loot entities would be a really nice QoL feature

**Comment by Hydrox6** [comment]
Logging in to an account (the door in the top right of the client) will cause the loot tracker to persist when restarting the client, plus other benefits such as protection against settings corruption and a farming tracker that can be viewed anywhere you want.

Follow [this guide](https://github.com/runelite/runelite/wiki/Account#sync-local-settings-to-your-remote-runelite-account) to have your settings carry over, and please join the [Discord](https://runelite.net/discord) for further questions of support

**Comment by rabitwarior2** [comment]
Thanks for the info, I'm actually already on the Discord, I guess I should've asked there first, thanks again mate.
