### ISSUE TITLE
Replay & Archive plugin

### ISSUE THREAD

**Issue by XrioBtw** [runelite/runelite#12836]
A plugin that will continuously archive your gameplay sessions, and allow you to replay these sessions. The replay should allow for some interaction, e.g. examining or toggling NPCs, objects, etc.. in the scene, but not allow for moving the camera.

A similar feature has been implemented for the RuneScape Classic project [RSCPlus](https://github.com/RSCPlus/rscplus), as seen in this [video](https://youtu.be/EUcPCHEwPuM?t=100).

It is desirable to let the client perform the replaying of the gameplay rather than creating a stand-alone program to achieve the same. Unfortunately, I have no knowledge of whether it is even possible to turn the client into such an *offline* mode.

What the replay feature might look like:
![animation](https://user-images.githubusercontent.com/33559295/100098671-abdb1f80-2e5e-11eb-8db3-7bd88840089d.gif)

Continuously recording gameplay with a stand-alone screen recorder is not an option as it will both take up too much disk space and not allow for interaction. A replay plugin would only need to store about 2 MB/hour, assuming that it can perform as well as the OSRS Mobile app[<sup>[1]</sup>](https://secure.runescape.com/m=news/a=142/osrs-mobile-data-and-battery-blog?oldschool=1).

The following must be archived (as references to the cache, not copies) with timestamps (incomplete):
* [Actor](https://github.com/runelite/runelite/blob/master/runelite-api/src/main/java/net/runelite/api/Actor.java)
  * World location
  * [Animations](https://github.com/runelite/runelite/blob/master/runelite-api/src/main/java/net/runelite/api/AnimationID.java)
  * [Spot animations](https://github.com/runelite/runelite/blob/master/runelite-api/src/main/java/net/runelite/api/GraphicID.java)
  * Model components and colours
  * Equipment
* GameObject, GraphicsObject, GroundObject, DecorativeObject, ... state (e.g. when was the tree chopped down?)
* Camera
* [Widgets](https://github.com/runelite/runelite/tree/master/runelite-api/src/main/java/net/runelite/api/widgets)

**Comment by Hydrox6** [comment]
So we've discussed this a bit on the Discord. The short of it is that it would be a crazy amount of work and internal tinkering to get this to work in a way that's not insanely fragile.
