### ISSUE TITLE
Slayer task chat command throw NullPointerException

### ISSUE THREAD

**Issue by skyblownet** [runelite/runelite#12847]
**Describe the bug**
NullPointer is throw when chat command is executed

**To Reproduce**
1. Have the slayer task (from konar): 94 lizardman in the battlefront
2. Type !slayer in chat

**Expected behavior**
Show the standard chat response on the command with the amount of kills / total kills ....

**Screenshots**
![slayer_task_null](https://user-images.githubusercontent.com/63957499/100371032-7c1b4b80-3007-11eb-8999-b6c20f467059.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.32
 - Launcher version: 1.6.2

**Additional context**
/

**Comment by Alexsuperfly** [comment]
Can you show us the exact text the gem says when you check it please?  The location just needs to be added to this [list](https://github.com/runelite/runelite/blob/fa79a51bca871ad611b3bbec36146cd4d6fa6cdf/runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java#L187), and having the exact text would help verify "in the battlefront" is correct.
