### ISSUE TITLE
Customizable status bars width

### ISSUE THREAD

**Issue by ColdDudeX** [runelite/runelite#12846]
Hello, I would like to suggest the option of making the width of the bars configurable, with the main idea being to make them thinner.

How is it now:
![image](https://user-images.githubusercontent.com/75078713/100356000-6854f280-2fd1-11eb-9e67-45fb9714a8f2.png) 

As I suggest having an option:
![image](https://user-images.githubusercontent.com/75078713/100356563-29736c80-2fd2-11eb-85b2-1e1dc349fa55.png)

When using some UI configurations the bars are on top of the columns and looks very nice, but with this Resizable Mode configuration the double bars to the left of the inventory take up a lot of space and perhaps giving a width option would make the settup cleaner.

I got this idea while using the skills progress bar plugin, as this plugin have exactly this option (*but for height).  

Thanks and sorry for bothering

**Comment by letterbit** [comment]
Yes please! And/or allowing stacking the bars on _top_ of the inventory to avoid collision entirely with stock ui elements and runelite ones moved to this poor unusable dock u_u [ui element](https://user-images.githubusercontent.com/80227409/112914277-92c2d380-90c9-11eb-9634-1cb67e917cd0.png)

**Comment by pwatts6060** [comment]
I'm working on this now

**Comment by pwatts6060** [comment]
#14138 implements this feature with being able to resize the width of the bars from 3 to 40 pixels, default is 20
