### ISSUE TITLE
Entity hider for random events

### ISSUE THREAD

**Issue by pettrs** [runelite/runelite#12849]
**Is your feature request related to a problem? Please describe.**
When tick fishing, sometimes you click the randome vent npcs beneath you, and it's very annoying at times. however, since the fishing spts are actually npcs, hiding npcs will also remove the fishing spots

**Describe the solution you'd like**
Just like there is an option for just hiding pets, add one for hiding random events

**Describe alternatives you've considered**
allow people to rightclick and add to custom list of npcs to hide, for example, you might only want to hide some npcs when doing ZMI

**Additional context**
not really, thank you for the consideration, it would be really helpful.

**Comment by Adam-** [comment]
There is a random event plugin, which can hide the ops on most other's random events. Maybe this already does what you want.
