### ISSUE TITLE
Runelite client mini freeze every 5-10 seconds

### ISSUE THREAD

**Issue by phoecz** [runelite/runelite#12859]
ust recently, I have been experiencing periodic freezes in the Runelite client. When playing, from the moment I log in, approximately every 5-15 seconds, everything in the game (movement, chat etc) will freeze for about half a second. This process keeps repeating itself indefinetely, which hinders a smooth and enjoyable gameplay.
OS: Windows 10,i have very good pc,internet 500mb/s,java8 build 271 pls help me

**Comment by Unmoon** [comment]
Please join the [discord](https://runelite.net/discord) for support.

**Comment by MESLewis** [comment]
If your issue was not resolved on discord you can reopen this issue.
