### ISSUE TITLE
Pharaoh's Sceptre left-click teleports

### ISSUE THREAD

**Issue by sarcophaguy** [runelite/runelite#12854]
**Is your feature request related to a problem? Please describe.**
Jagex somewhat recently changed the left-click option on the Pharaoh's sceptre to 'wield' in an attempt to crack down on lures that involve this item. This made training Thieving through Pyramid Plunder slightly more tedious by requiring more inputs. The 'Menu Entry Swapper Extended' plugin from the hub has a feature that's supposed to let you toggle the left-click option on the sceptre, but it doesn't seem to work, probably due to this default change from 'teleport' to 'wield'.

**Describe the solution you'd like**
Would be rad if someone made the entry swapper actually work on the Pharaoh's sceptre again.

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
