### ISSUE TITLE
Suggestion: Status Bar HP Turns Pink When Infected (The Nightmare

### ISSUE THREAD

**Issue by Goostafus** [runelite/runelite#12857]
The Status Bar plugin will currently change the red health color to lime green for poison or dark green for venom.

During Phase 2 of The Nightmare, when a player gets infected with a parasite, the health orb next to the minimap will change to a pink color, indicating a player needs to drink a sip from a Sanfew Serum or a Relicym's Balm to avoid full damage from the boss mechanic.

My suggestion is to have the Status Bar plugin change the Hitpoints bar to the same pink color that appears on the health orb when a player gets infected with a parasite during The Nightmare boss fight. This would align the various status effects regarding the health orb to the Hitpoints bar.

**Comment by Yttrium-tYcLief** [comment]
Paging @Malfuryent as he's the original Status Bar dev and is responsible for the recent additions involving poison/venom.

**Comment by Malfuryent** [comment]
It should certainly be possible, but i currently dont have a account that can take on the nightmare to figure out the varbit that changes when you get infected by the parasite. 
If someone can figure out the varbit for that it should be a quick add to the plugin

**Comment by Hydrox6** [comment]
It seems to be 10151. Was annoying to find since it requires some form of update for the orb to change colour, unlike poison/venom/disease

**Comment by Nightfirecat** [comment]
Fixed in #12874
