### ISSUE TITLE
Visual metronome for hearing impaired players

### ISSUE THREAD

**Issue by pettrs** [runelite/runelite#12850]
**Is your feature request related to a problem? Please describe.**
Currently, if you're doing actions that require a metronome, like tick manipulation, the metronome i a good guide. However, if you are watching a movie, or listening to music, the additional beat might throw you off the rythm

**Describe the solution you'd like**
Similar to the prayer orb, or another vosual counter that hops inbetween selected colors if the beat is not linear. it flashes, or slides from side to side to mimic the rythm of one or multiple tick.

**Describe alternatives you've considered**
similar to what once was on vorkath tick timer in the past, but make it movable around the client so that it can be places next to the inventory, or next to player switches where it'd be most fit. scaling and changing colors could also be nice. aswell as selecting inbetween color switching inbeween eacother to represent a tick, or hat it just flashes for each tick

**Additional context**
no.

**Comment by acdvs** [comment]
This sounds like a good basis for an Accessibility plugin. The color blind feature (#1959) could be grouped with it as well.

**Comment by MESLewis** [comment]
This is available on the plugin hub: https://github.com/vincent0955/Visual-metronome

**Comment by Hydrox6** [comment]
As MESLewis mentioned, this is available on the hub under `Visual Metronome`
