### ISSUE TITLE
High GPU Usage/Runelite running at 15-30 frames

### ISSUE THREAD

**Issue by infamousvox** [runelite/runelite#12861]
I went on vacation for two weeks, came back and had a graphics driver update for my rtx 2080. 
Did it, and now my runelite runs at anywhere between 15-35 FPS when it used to be at a constant 50 FPS and never dipped from that. I’ve reverted back to the previous graphics driver with no luck. I made sure in Nvidia control panel that runelite is using my GPU and not attaching to my onboard graphics. I’ve turned off and on the GPU plug-in and animation smoothing, doesn’t help. 
I turned off my OC on my graphics card, doesn’t help, turned it back on, doesn’t help. 
Resorted to reinstalling windows completely and wiping my m.2 and my SSDs. Didn’t fix it. 
I am playing on resizable on a 2560x1440p monitor at 144hz. Even when I move it to one of my other monitors that are 1920x1080p 60hz it barely makes a performance impact. 
My first thought was okay maybe my graphics card or processor is taking a shit, loaded up Rust, Apex legends, valorant, and Dayz. They all run perfectly fine. 
Specs:
Nvidia RTX 2080. 
Amd Ryzen 7 2700x
32gb Corsair vengeance ram at 3000mhz. 
WD black edition m.2 1tb. 
Hopefully someone on here can help in my last cry for help lol. 
Thanks

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
