### ISSUE TITLE
Amplified height

### ISSUE THREAD

**Issue by Jimlom9** [runelite/runelite#12864]
Please add amplified height feature like in minecraft to runescape, it would be so nice of you guys to do that.

**Comment by Nightfirecat** [comment]
A quick search of this doesn't really explain what "Amplified height" is. Can you provide some screenshot/video/link that describes it? As-is, I don't really understand what this request means

**Comment by Jimlom9** [comment]
Yes multiply heit by custom quantitity. now 1ft high becomes 2ft heigh. White wolf mountain is tall like in rs3 (look at videos of rs3 and youl see). Thank you!

**Comment by Yttrium-tYcLief** [comment]
I think what he's asking for is literally stretching the Z axis for regular terrain, but not objects.

**Comment by Jimlom9** [comment]
Hello when will you add this? I will pay to patreon if you add it.
