### ISSUE TITLE
GPU Setting Crashes Client

### ISSUE THREAD

**Issue by helpmepleasemygamewontwork** [runelite/runelite#12879]
Yo, before I start, Id like to clarify that I'm not super tech savvy or anything like that. The most I can do is change the background color on the google homepage, so go easy on me, eh?

Anyway, whenever I try to turn on the GPU switch in the client, it immediately crashes. I don't get any error messages, the client just closes. 

**Environment**
 - OS: Windows 10
 - RuneLite version: 1.6.33
 - Launcher version: 2.15

**Additional context**
Now here the deal, I'm probably just an idiot, but I cant find my logs. I followed the instructions one here, the ones on discord, and I just cant find them. BUT, what I did find is this text file called "hs_err_pid24256". Now this could just be my lizard brain at work, but "err" makes me think this says something about it. I cant really understand what its saying, but hopefully someone here can help.

[hs_err_pid24256.log](https://github.com/runelite/runelite/files/5633115/hs_err_pid24256.log)

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
