### ISSUE TITLE
Add obscure items to item stats

### ISSUE THREAD

**Issue by maxbla** [runelite/runelite#12873]
**Is your feature request related to a problem? Please describe.**
the "Item Stats" plugin is missing a few niche consumable items, such as [Cooked mystery meat](https://oldschool.runescape.wiki/w/Cooked_mystery_meat), and [Barbarian potions](https://oldschool.runescape.wiki/w/Barbarian_Training#Barbarian_Herblore). 

**Describe the solution you'd like**
I want to submit a PR that adds these item to the item stats plugin. I think this is as simple as adding some lines to the `net.runelite.client.plugins.itemstats.ItemStatChanges.java` file.

**Comment by Nightfirecat** [comment]
Cooked mystery meat was added in #12823
Barbarian potion support is requested in #12057
