### ISSUE TITLE
Game stop when i bank my items faster

### ISSUE THREAD

**Issue by fernandodr15** [runelite/runelite#12877]
the game stops when I am putting objects into my bank quickly, at first I thought it was because of the anti drag plugin, but then I deactivated it and saw that it was not.  what happens is that the game stops or freezes, however the client can not minimize and close, also activate or deactivate plugin without any problem, but the game as such is the one that crashes strangely, I have to close and return  to enter.  it's quite annoying, please fix it thanks.
![FB_IMG_1606944797455](https://user-images.githubusercontent.com/8400878/100934482-2b9f6480-34c5-11eb-9991-5a8e00101d08.jpg)

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
