### ISSUE TITLE
Hide Ignored Players with Entity Hider

### ISSUE THREAD

**Issue by mmcmd** [runelite/runelite#12884]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Somewhat, it's to highlight ignored players so it can be used for multiple reasons

**Describe the solution you'd like**
Add "Hide Ignored players" as an option to Entity hider

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
There is currently nothing in place that can do this

**Additional context**
This feature was requested 2 years ago but refused because it would allow you to hide your clan members https://github.com/runelite/runelite/issues/3349 but it seems like there is now an entity hider option for hiding clan members, which means that this really cannot be abused for multi-pking.

**Comment by Alexsuperfly** [comment]
duplicate of #3349

**Comment by m4chinations** [comment]
This needs to be re-opened, or someone needs to update the reasoning behind the wontfix. The original reason was given that you could hide CC members, but this exact functionality was introduced directly with 6c21b2e21b289afb2a59526017503533600faf12.
