### ISSUE TITLE
Camera zoom and rotation presets

### ISSUE THREAD

**Issue by berserk64** [runelite/runelite#12899]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I have to setup my camera and zoom for activities such as construction and zmi, etc

**Describe the solution you'd like**
Saving presets different presets of camera zooms and rotations for activities, maybe right click the compass to select presets

**Describe alternatives you've considered**
I've considered tunning it every time I play but its never just right

**Comment by Hydrox6** [comment]
Duplicate of #3195
