### ISSUE TITLE
[Idle Notifier] Trigger Idle notifications at Shades of Mort'on

### ISSUE THREAD

**Issue by Marstead** [runelite/runelite#12905]
**Is your feature request related to a problem? Please describe.**
Repairing the temple wall during the Shades of Mort'on minigame is an automated idle activity that occasionally times out. However, even with Animation/Interaction checked in the Idle Notifier plugin settings, no notification triggers when the repair process times out, even though the player character stops performing the repair animation.

**Describe the solution you'd like**
Adjust the plugin so that an idle notification triggers when the temple repairing animation stops, if "Idle Animation" notifications are enabled.

**Describe alternatives you've considered**
"Idle Interaction" would work too if RuneLite can distinguish temple repair as an interaction activity.

**Additional context**

**Comment by Mrnice98** [comment]
I will take a look at this

**Comment by Nightfirecat** [comment]
Added in d58cecdb8d5a2d6958a5bcf1381805c6d64be7b8
