### ISSUE TITLE
System.gc() is called way too often.

### ISSUE THREAD

**Issue by zeruth** [runelite/runelite#1290]
This **does** cost frames at the rate it is being called. While it's nice to keep the memory footprint very low. Java's garbage collector is pretty robust and shouldn't be called with the frequency it is.

**Comment by Abextm** [comment]
When is this being called?

**Comment by zeruth** [comment]
multiple times per second in release.

**Comment by Abextm** [comment]
Where is it being called from? Are you sure its not the GC running automatically?

**Comment by zeruth** [comment]
And normally doesn't gc wait until memory is near max? from my experiences. java gc will even go over max as much as it can. into over 1GB with enough stale references before clearing.

**Comment by Abextm** [comment]
I'm not 100% sure, but I think it will kick in at 70% newgen.

**Comment by zeruth** [comment]
I can absolutely confirm this is a real problem costing frames

**Comment by Abextm** [comment]
What OS? Did you use the installer?

**Comment by zeruth** [comment]
https://i.imgur.com/DFzdTsd.gifv

Thats with the two instances of System.gc removed in runescape-client.

Yes I used the installer.

**Comment by Abextm** [comment]
Yeah, those two instances are from the `::gc` chatcommand, and the other one is on logout. I cannot repro this at all. What plugins are you currently using (What are you doing in-game)?

**Comment by zeruth** [comment]
sorry this is the right gif with gc calls disabled.
https://i.imgur.com/itqSn4t.gifv

standing in lumby, doing nothing. default plugins, fresh install, and fresh fork in IntelliJ with gc calls removed

**Comment by Abextm** [comment]
If you revert removing the gc calls, does it still happen from intellij?

**Comment by zeruth** [comment]
No it doesn't affect IntelliJ builds. Must be the Release version.

We need somebody else to look into it. I have an i7 4770k and it was dipping below 50fps. it would be much worse felt on lower end PC's

**Comment by Abextm** [comment]
I can repro this on release now. I will look into it.
