### ISSUE TITLE
Ground Items Block

### ISSUE THREAD

**Issue by 3K32000** [runelite/runelite#12902]
It is possible in some way that the objects on the ground can be blocked so that it does not pick it up, this blocking function was in runelite plus +, if it has it then I cannot find it,

Example: You kill an enemy, and drop 3 objects, objects of which one is of your interest and the other two are not of your interest so, you can see the three objects but when you pass the pointer over the pile you cannot pick up the objects that You are not interested because they are blocked in some way, and only pick up the object that interests you, because it is not blocked.

I saw this function in runelite plus +, I think it is possible then.

**Comment by Hydrox6** [comment]
Removing menu entries is [Rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features).
