### ISSUE TITLE
Barrows overlay percentage shows too many digits

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#12916]
Following the merging of 807a22172f0fd09a89f1e72e35e5eb7fb6816881, the barrows overlay shows too many digits for the reward potential. It should be capped to some smaller number, perhaps 2 digits? eg. `12.34%`

![](https://user-images.githubusercontent.com/2199511/101866762-901b8d00-3b71-11eb-9f84-d32d0946afe1.png)

**Comment by TaylorAbraham** [comment]
Made a fork, working on it.
