### ISSUE TITLE
GPU Plugin Crashing on New Laptop

### ISSUE THREAD

**Issue by bassemb** [runelite/runelite#12913]
I just got me a MSI GE66 Raider, loaded with the RTX2070 and i7-10750h @ 2.6Ghz and can't seem to run the GPU plugin (tried both Integrated and Dedicated) as it crashes giving me a "Can't find opengl" error message. I know the laptop is overkill for OSRS lol obviously I did not get it solely for this game but it would be nice if I could run it on this beast. Anyways I tried searching up fixes but couldn't find much other than running the client through a jar executable (really don't want to mess with these without proper guidance). I'm not a programmer so I'm asking you pros here how can I fix this (if there is any fix at least)? Thanks!

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
