### ISSUE TITLE
Limpwurt seeds are not counted when thieving the master farmer

### ISSUE THREAD

**Issue by ManchineV** [runelite/runelite#12915]
**Describe the bug**
Title says it all, Limpwurt seeds are not counted when thieving the master farmer

**To Reproduce**
Tested in Draynor Village while wearing full Rogue, did not test on other master farmer or without rogue
1. Go to 'Master Farmer' 
2. Steal from him
3. When you steal limpwurt seeds you will notice they are not counted in the loot tracker

**Expected behavior**
They are counted in the loottracker

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 64bit
 - RuneLite version: ?
 - Launcher version: ?

**Comment by Hydrox6** [comment]
Click the eye in the top right and check if you've got them hidden.

**Comment by ManchineV** [comment]
omfg how stupid of me... should have known... Thanks Hydrox6
