### ISSUE TITLE
sidebar lag/stutter causing in game fps drops

### ISSUE THREAD

**Issue by xgahx420** [runelite/runelite#12911]
side bar is lagging the hell out of my client, when open and mouse hovers over it or attempting to scroll down the plugin list or world hopper list in the side bar causes CPU to spike from its usual 6% to 12% cpu and cause FPS in game to drop from perfect 50 to 30 or less. noticed also even if side bar is not open hovering over over the top right corner (where you can close the client and where runelite sign in/screenshots are) when the mouse hovers over the area and it gets highlighted this is causing the lag same inside as the side bar, also trying to look someone up in game causes a massive client lag until it finishes loading everything from the hiscores.

hardware acceleration being disabled made no difference, no programs interfering with RL. this only started happening a few days ago, everything had been fine for months.
seems I am not the only one this is happening to, several threads on reddit from the past few days.

window 10, NVidia 1660 super, Ryzen 5 2600, 16gb ram

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
