### ISSUE TITLE
incorrect constant value for net.runelite.api.widgets.WidgetID.Shop.ITEMS_CONTAINER

### ISSUE THREAD

**Issue by larsvansoest** [runelite/runelite#12929]
The value `net.runelite.api.widgets.WidgetID.Shop.ITEMS_CONTAINER = 2` is inconsistent with the actual in-game shop items container widget. As shown by this [screenshot](https://i.imgur.com/j1ZLxAB.png), the path to the container is 300.16, instead of the suggested 300.2.

https://github.com/runelite/runelite/blob/78e0cf53926a9060a559769bd3e40eab16582d22/runelite-api/src/main/java/net/runelite/api/widgets/WidgetID.java#L306

**Comment by Nightfirecat** [comment]
We are no longer using that definition, so it was removed in #13011.
