### ISSUE TITLE
GE MouseWheel Item Count Adjustment

### ISSUE THREAD

**Issue by Gooby200** [runelite/runelite#12937]
**Is your feature request related to a problem? Please describe.**
When going to the GE, clicking "+" and "-" to lower or increase the item count by 1 is annoying and time consuming.

**Describe the solution you'd like**
I'd like to be able to use my mouse's scroll wheel to automatically increase/decrease the amount of items that I want to sell/buy whenever my mouse is over the "Quantity" box.

**Additional context**
![image](https://user-images.githubusercontent.com/16640989/102157795-c133e000-3e45-11eb-885e-cda1278bb851.png)

**Comment by Nightfirecat** [comment]
We cannot implement this feature as it would require faking mouse clicks.
