### ISSUE TITLE
Additional npc options? QOL

### ISSUE THREAD

**Issue by ShuaMiszyn** [runelite/runelite#12933]
**Is your feature request related to a problem? Please describe.**
It is not really a problem so much as possible QOL improvement. I am not sure if you have already thought of this, but adding extra npc options so left clicking for different options are available.

**Describe the solution you'd like**
Say an npc has all their normal options, make an option so that you take a copy of one of those actions and the copy is at the top. I'm not sure if this was considered but I heard that removing options was against jajex's terms and this would give us similar results for left clicking.

**Additional context**
For example if I wanted to left click on npcs for examine or something.
This: https://gyazo.com/d81cf20e0e5b7c1e9e43e15e568c1155
Would add examine without removing other options.
https://gyazo.com/09d4385eb2a424f8909175ff0b1899d0

I thought about this when someone told me one of the reasons we cannot left click for certain actions. Maybe this can inspire alternatives or be one for some QOL improvements.

**Comment by Nightfirecat** [comment]
This would fall under the following line item of [Jagex's statement regarding third-party clients](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1):

> Removes or deprioritises attack, cast (or similar) options from the minimenu in any scenario

Hence, we cannot implement this feature.
