### ISSUE TITLE
Item prices plugin can't handle Platinum Token stacks with a value over 2147m

### ISSUE THREAD

**Issue by emiljensen2** [runelite/runelite#12934]
**Describe the bug**
The item prices overlay can't show what a stack is worth if it's more than 2147m, just goes into -

**To Reproduce**
Enable item prices overlay, have a stack (fx platinum tokens) that's worth more than 2147m.

**Expected behavior**
Should show the true value.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.35
 - Launcher version: 1.6.0

**Comment by Hydrox6** [comment]
So I was wondering why this was happening; we already fixed this issue in #10466, and I can verify it's still working.

Turns out that Platinum Tokens weren't given the same treatment in that PR for whatever reason.

**Comment by emiljensen2** [comment]
Ah makes sense, I only tested on a platinum stack.
