### ISSUE TITLE
Draw distance not going beyond 25 in Mac

### ISSUE THREAD

**Issue by FoamyAdampower** [runelite/runelite#12949]
For some reason the Draw distance won't go over 25, but when I put it lower than 25 I changes?
This is really weird.
![2020-12-18_13-40-20](https://user-images.githubusercontent.com/63113396/102649317-efac0680-4136-11eb-8b54-aa50ab172320.png)
![2020-12-18_13-40-37](https://user-images.githubusercontent.com/63113396/102649328-f33f8d80-4136-11eb-8d84-9f14f8deb058.png)

**Comment by Nightfirecat** [comment]
Extending the draw distance requires enabling compute shaders, which is not available on MacOS. [From our 1.6.14 release where we started to offer GPU support for the platform:](https://runelite.net/blog/show/2020-05-09-1.6.14-Release)

> Due to limitations of OpenGL on MacOS the plugin does not offer extended draw distance at this time. We plan to continue development of the plugin to add extended draw distance support on MacOS in the future.

**Comment by stoddy15** [comment]
Why is it not available @Nightfirecat its 2021
