### ISSUE TITLE
Set Xp Goals (rse feature that I used to love)

### ISSUE THREAD

**Issue by Shawn538** [runelite/runelite#12942]
Rs3 did some things right. we have to admit. I think one of those things was the ability to set xp goals. Its not a groundbreaking feature to possibly add. But its something i know i really enjoyed.

**Comment by Bram91** [comment]
We are using vanilla XP drops. To configure them: [https://github.com/runelite/runelite/wiki/XP-Drop](https://github.com/runelite/runelite/wiki/XP-Drop)
Whatever goal you set here will be reflected in the xp tracker/orbs

**Comment by Shawn538** [comment]
wow, i had no idea this feature was in the game at all. THank you!
