### ISSUE TITLE
Port RuneLite to run natively on Apple Silicon

### ISSUE THREAD

**Issue by cwille97** [runelite/runelite#12959]
**Is your feature request related to a problem? Please describe.**
The client would run even more smooth and efficient if it ran natively on M1

**Describe the solution you'd like**
A RuneLite port that runs natively on Apple Silicon

**Describe alternatives you've considered**
Allowing it to continue running on Rosetta which wouldn't be quite as efficient, doesn't take advantage of the M1s power.

**Additional context**
I recently got a new M1 so I might be able to try and help develop this port in the near future. 

[Additional Information](https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary)

**Comment by Adam-** [comment]
This is current blocked on https://github.com/AdoptOpenJDK/openjdk-build/issues/1922 - but once that is available I would appreciate having someone work on this.

**Comment by Optumasfx** [comment]
@Adam- when will we know when its available? where would it be posted?

**Comment by kopvm** [comment]
This would be great to have this.  I just downloaded the Azul JDK for ARM64 and runelite does run using this when running the jar.  Cant turn the GPU plugin on but I'm getting 50 fps at the bank

**Comment by stoddy15** [comment]
This would be a game changerrrr

**Comment by stoddy15** [comment]
This would be a game changerrrr

it would sip battery and zero dropped frames

**Comment by Cornelius-Cell** [comment]
OpenJDK sourcecode + the macos bits that already exist for the macos-x64 release can be combined rather easily once someone with some familiarity with the openjdk sourcecode has an M1-based macos system to test it on, which should mean an adoptopenjdk macos-aarch64 release should be here within the month.

**Comment by hex-agon** [comment]
Running it natively is already possible using [Azul's Zulu VM](https://www.azul.com/downloads/zulu-community/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk) and the jar launcher. Since this requires a bit more technical knowledge and is not as streamlined as the pre-compiled binaries, this setup is only recommended to those who know what they're doing.

**Comment by Optumasfx** [comment]
> Running it natively is already possible using [Azul's Zulu VM](https://www.azul.com/downloads/zulu-community/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk) and the jar launcher. Since this requires a bit more technical knowledge and is not as streamlined as the pre-compiled binaries, this setup is only recommended to those who know what they're doing.

Hows the performance comparing to intel chips?

**Comment by tcosculluela** [comment]
@hex-agon I was able to get it running pretty easily with Azul JDK in IntelliJ following [this guide](https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA)

GPU plugin is broken (error below), but it's not really needed until compute shaders are worked out tbh. Outperforms the Rosetta2 version with the GPU plugin enabled & maintains a pretty solid 50fps

```2021-01-15 00:58:37 [Client] ERROR n.r.client.plugins.gpu.GpuPlugin - Error starting GPU plugin
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:310)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
	at jf.al(jf.java:3071)
	at client.av(client.java)
	at bd.sl(bd.java:377)
	at bd.run(bd.java:331)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-15 00:58:37 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.UnsatisfiedLinkError: 'boolean jogamp.nativewindow.macosx.OSXUtil.IsMainThread0()'
	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread0(Native Method)
	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread(OSXUtil.java:419)
	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:306)
	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1684)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:434)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:61)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:46)
	at net.runelite.client.plugins.gpu.GpuPlugin.shutDown(GpuPlugin.java:429)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:420)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
	at jf.al(jf.java:3071)
	at client.av(client.java)
	at bd.sl(bd.java:377)
	at bd.run(bd.java:331)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-15 00:58:37 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.UnsatisfiedLinkError: 'boolean jogamp.nativewindow.macosx.OSXUtil.IsMainThread0()'
	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread0(Native Method)
	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread(OSXUtil.java:419)
	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:306)
	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1684)
	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:434)
	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
	at jf.al(jf.java:3071)
	at client.av(client.java)
	at bd.sl(bd.java:377)
	at bd.run(bd.java:331)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by nlruk** [comment]
> @hex-agon I was able to get it running pretty easily with Azul JDK in IntelliJ following [this guide](https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA)
> 
> GPU plugin is broken (error below), but it's not really needed until compute shaders are worked out tbh. Outperforms the Rosetta2 version with the GPU plugin enabled & maintains a pretty solid 50fps
> 
> ```
> java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
> 	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:310)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
> 	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
> 	at jf.al(jf.java:3071)
> 	at client.av(client.java)
> 	at bd.sl(bd.java:377)
> 	at bd.run(bd.java:331)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 2021-01-15 00:58:37 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
> java.lang.UnsatisfiedLinkError: 'boolean jogamp.nativewindow.macosx.OSXUtil.IsMainThread0()'
> 	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread0(Native Method)
> 	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread(OSXUtil.java:419)
> 	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:306)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1684)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:434)
> 	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:61)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:46)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.shutDown(GpuPlugin.java:429)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:420)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
> 	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
> 	at jf.al(jf.java:3071)
> 	at client.av(client.java)
> 	at bd.sl(bd.java:377)
> 	at bd.run(bd.java:331)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 2021-01-15 00:58:37 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
> java.lang.UnsatisfiedLinkError: 'boolean jogamp.nativewindow.macosx.OSXUtil.IsMainThread0()'
> 	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread0(Native Method)
> 	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread(OSXUtil.java:419)
> 	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:306)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1684)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:434)
> 	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
> 	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
> 	at jf.al(jf.java:3071)
> 	at client.av(client.java)
> 	at bd.sl(bd.java:377)
> 	at bd.run(bd.java:331)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ```

Do you notice a difference dramatic increase in performance? can you please provide some benchmarks. Thanks for letting us know.

**Comment by Cornelius-Cell** [comment]
apparently someone managed to build jogamp for osx arm64 http://forum.jogamp.org/JOGL-for-Mac-ARM-Silicon-td4040887.html

**Comment by Adam-** [comment]
> 
> 
> @hex-agon I was able to get it running pretty easily with Azul JDK in IntelliJ following [this guide](https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA)
> 
> GPU plugin is broken (error below), but it's not really needed until compute shaders are worked out tbh. Outperforms the Rosetta2 version with the GPU plugin enabled & maintains a pretty solid 50fps
> 
> ```
> java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
> 	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:310)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
> 	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
> 	at jf.al(jf.java:3071)
> 	at client.av(client.java)
> 	at bd.sl(bd.java:377)
> 	at bd.run(bd.java:331)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 2021-01-15 00:58:37 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
> java.lang.UnsatisfiedLinkError: 'boolean jogamp.nativewindow.macosx.OSXUtil.IsMainThread0()'
> 	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread0(Native Method)
> 	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread(OSXUtil.java:419)
> 	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:306)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1684)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:434)
> 	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:61)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:46)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.shutDown(GpuPlugin.java:429)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$startUp$2(GpuPlugin.java:420)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
> 	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
> 	at jf.al(jf.java:3071)
> 	at client.av(client.java)
> 	at bd.sl(bd.java:377)
> 	at bd.run(bd.java:331)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 2021-01-15 00:58:37 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
> java.lang.UnsatisfiedLinkError: 'boolean jogamp.nativewindow.macosx.OSXUtil.IsMainThread0()'
> 	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread0(Native Method)
> 	at jogamp.nativewindow.macosx.OSXUtil.IsMainThread(OSXUtil.java:419)
> 	at jogamp.nativewindow.macosx.OSXUtil.RunOnMainThread(OSXUtil.java:306)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.invokeOnMainThread(GpuPlugin.java:1684)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.lambda$shutDown$4(GpuPlugin.java:434)
> 	at net.runelite.client.callback.ClientThread.lambda$invoke$0(ClientThread.java:48)
> 	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
> 	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:187)
> 	at jf.al(jf.java:3071)
> 	at client.av(client.java)
> 	at bd.sl(bd.java:377)
> 	at bd.run(bd.java:331)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> ```

Until we are able to get a native build it may be good to write a wiki page on what you did to get this working for others.

**Comment by tcosculluela** [comment]
@Adam- Haha I never realized there was a jar launcher, that makes things easier. I can make this into a wiki page when I have more time tonight/tomorrow. In the meantime...

1. [Download Azul JDK11 for arm64 here and install the .DMG](https://www.azul.com/downloads/zulu-community/?version=java-11-lts&os=macos&architecture=arm-64-bit&package=jdk) It should install to `/Library/Java/JavaVirtualMachines/zulu-11.jdk/`
2. Ensure that `/usr/libexec/java_home` points to `/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home` (if not, a restart should do the trick)
3.  That's pretty much it, from here you should just be able to use the jar launcher as normal. (If macOS refuses to use the correct VM when doubleclicking for whatever reason, either restart do it the old fashioned way & write a script that runs `java -jar Runelite.jar`)

**Comment by Adam-** [comment]
Hydrox has made a wiki page https://github.com/runelite/runelite/wiki/MacOS-Arm64-(M1-chips)-Native-Support

**Comment by tcosculluela** [comment]
> apparently someone managed to build jogamp for osx arm64 http://forum.jogamp.org/JOGL-for-Mac-ARM-Silicon-td4040887.html

Nice find! I was able to get the GPU plugin running on my air with this! (After failing multiple times to build Gluegen&JOGL, I just ended up copying his files)

I can write up a quick guide on what I did in IntelliJ to get it running if anyone is interested, just be warned that it's super hacky (it's pretty much replacing the "macosx-universal" JOGL&Gluegen with the arm64 versions, and also copying over some .dylibs)

**Comment by Adam-** [comment]
> 
> 
> > apparently someone managed to build jogamp for osx arm64 http://forum.jogamp.org/JOGL-for-Mac-ARM-Silicon-td4040887.html
> 
> Nice find! I was able to get the GPU plugin running on my air with this! (After failing multiple times to build Gluegen&JOGL, I just ended up copying his files)
> 
> I can write up a quick guide on what I did in IntelliJ to get it running if anyone is interested, just be warned that it's super hacky (it's pretty much replacing the "macosx-universal" JOGL&Gluegen with the arm64 versions, and also copying over some .dylibs)

We're going to need to be able to build them. I have built the ones we use currently on osx (obviously not for arm64) so it should be possible. If you could figure out how to build our version of jogl and glugen (https://github.com/runelite/gluegen and https://github.com/runelite/jogl) and submit a patch for it, that would be the most useful thing you could do.

**Comment by Adam-** [comment]
@tcosculluela can you test if these two jars work on your m1:

https://cdn.discordapp.com/attachments/359016743802503178/800430206283415552/jogl-all-natives-macosx-universal.jar

https://cdn.discordapp.com/attachments/359016743802503178/800430370357116978/gluegen-rt-natives-macosx-universal.jar

You can do this by replacing 
```xml
		<dependency>
			<groupId>net.runelite.jogl</groupId>
			<artifactId>jogl-all</artifactId>
			<version>${jogl.version}</version>
			<classifier>natives-macosx-universal</classifier>
			<scope>runtime</scope>
		</dependency>
```
with
```xml
		<dependency>
			<groupId>net.runelite.jogl</groupId>
			<artifactId>jogl-all</artifactId>
			<version>${jogl.version}</version>
			<classifier>natives-macosx-universal</classifier>
			<scope>system</scope>
			<systemPath>/path/to/library.jar</systemPath>
		</dependency>
```

+ also for the glugen jar.

**Comment by tcosculluela** [comment]
@Adam- Yes, both jars work with that pom.xml modification (after I copy over some dylibs: `libgluegen_rt.dylib`, `libjogl_desktop.dylib`, `libnativewindow_awt.dylib`, and `libnativewindow_macosx.dylib` into `/runelite/natives/macosx-universal`)

I'm going to try nuking the project & recloning to see if that's just a remnant of my earlier modifications

P.S I figured out why my builds were failing, I was trying to build with JDK8 because I can't read

Pretty much what you have to do is [(loosely following this guide):](https://jogamp.org/jogl/doc/HowToBuild.html)

1.  Install both Zulu JDK8 and JDK11. Set $JAVA_HOME to the JDK11 home folder (e.g, `export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home` 
2. Clone both projects into the same root folder with `git clone --recurse-submodules https://github.com/runelite/gluegen.git gluegen` and `git clone --recurse-submodules https://github.com/runelite/jogl.git jogl`
3. Edit the file `gluegen/make/gluegen-cpptasks-base.xml`. In the following lines, replace "x86_64" with "arm64". 

    `<compilerarg value="x86_64" if="use.macosx64"/>` 
    `<linkerarg value="x86_64" if="use.macosx64"/>`
4. open your terminal at the `gluegen/make` directory and run `ant -Dtarget.sourcelevel=1.8 -Dtarget.targetlevel=1.8 -Dtarget.rt.jar=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/rt.jar` <br> The build should be successful
5. In the same terminal that you built Gluegen, cd to the `/jogl/make` directory. Delete the following folders (swt fails to build but we don't care about it):

    `jogl/src/nativewindow/classes/com/jogamp/nativewindow/swt`
    `jogl/src/jogl/classes/com/jogamp/opengl/swt`
    `jogl/src/newt/classes/com/jogamp/newt/swt`
6. After deleting the folders, in the `/jogl/make` terminal, again run `ant -Dtarget.sourcelevel=1.8 -Dtarget.targetlevel=1.8 -Dtarget.rt.jar=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/rt.jar`

NEWT will fail to build but we don't care about it either. The resulting jars that we care about can be found in `/gluegen/build` & `/jogl/build/jogl`, and the dylibs we care about can be found in `/gluegen/build/obj`, `/jogl/build/jogl/obj`, and `/jogl/build/nativewindow/obj`

**Comment by Adam-** [comment]
I don't understand, the jars contain the dylibs, so you shouldn't be copying anything. At any rate I found some other people to test it and it seems they are ok.

**Comment by tcosculluela** [comment]
![After making your modifications](https://i.imgur.com/uuaQJ24.png) You're right about that lmao

My maven repo got all wacky. RL was still using the jars that I had built which was why it was still asking for the dylibs. Can confirm that the plugin works with your jars after I let maven re download everything.

And yeah, I had written most of that message before I saw your response with the jars, was figuring out how to build them myself as you had previously asked

> If you could figure out how to build our version of jogl and glugen (https://github.com/runelite/gluegen and https://github.com/runelite/jogl) and submit a patch for it, that would be the most useful thing you could do.

**Comment by Adam-** [comment]
Okay. I've pushed the required changes to the gluegen/jogl repos.

**Comment by Adam-** [comment]
I've updated the client to use these newer libraries 6d42e7ba42fac6e8748d8ad3f0c789a59900337e

**Comment by kopvm** [comment]
If you need any help testing something I don't mind helping.  Thanks for all the work that you are doing!

**Comment by Adam-** [comment]
The jogl updates went into the last release, so if you follow https://github.com/runelite/runelite/wiki/MacOS-Arm64-(M1-chips)-Native-Support I think everything should be working.

**Comment by GeorgeKosrs** [comment]
> This is currently blocked on [adoptium/temurin-build#1922](https://github.com/adoptium/temurin-build/issues/1922) - but once that is available I would appreciate having someone work on this.

I think it is done. does this mean runelite can officially work on the m1 and upcoming m2?

**Comment by Vulki0** [comment]
https://www.tickcounter.com/countdown/2683708/java-17-release-date

**Comment by Adam-** [comment]
This has been done in launcher release 2.2.0
