### ISSUE TITLE
GPU plugin's 'Compute Shaders' option is causing artifacts

### ISSUE THREAD

**Issue by Steve4448** [runelite/runelite#12952]
This issue seems to be related/a duplicate of #11351 but that issue has been closed.

**Describe the bug**
Depending on the complexity of the environment, vertices will start to disappear/stretch. I was able to get a few screenshots (added below). I was also able to test and confirm that this issue only occurs while the "Compute Shaders" option is enabled in the GPU plugin. In most situations this issue seems very minor and uncommon but when it does occur it's very noticeable.

**Screenshots**
![Stretching vertices 1](https://user-images.githubusercontent.com/3617835/102696983-50534600-4200-11eb-86ea-7b1d688a2bd3.png)
![Stretching vertices 2](https://user-images.githubusercontent.com/3617835/102696984-51847300-4200-11eb-835a-dc426bb2b5e1.png)
![Stretching vertices 3](https://user-images.githubusercontent.com/3617835/102696985-51847300-4200-11eb-9173-519dcd114ae8.png)

**Environment**
 - OS: Windows 10 (Version 20H2 - build 19042.685)
 - RuneLite version: 1.6.35
 - Launcher version: 2.1.5 (Using the standalone .jar file and using Java 11.0.9)
 - GPU: Asus TUF RTX 3080 (They exist!)
 - Nvidia Driver Version: 460.89 (Did a fresh driver install.)

If there's anything I can do to help better diagnose this problem let me know. Thank you.

**Comment by Steve4448** [comment]
Recorded a video to really see what's going on in better detail: https://user-images.githubusercontent.com/3617835/103157122-d41bae00-477d-11eb-8722-9e10631986d7.mp4

**Comment by Nightfirecat** [comment]
Our release last week made a number of changes to the GPU plugin, though I don't think they would impact this. Can you confirm if this is still an issue?

**Comment by Steve4448** [comment]
Yes, still occurring on RuneLite version 1.6.36.2 and with Nvidia's newest drivers 461.09.

**Comment by Steve4448** [comment]
Recorded a better video that's actually formatted properly: 

https://user-images.githubusercontent.com/3617835/104375261-13bdf600-54f1-11eb-81a7-949fea21b613.mp4

**Comment by jammy-dodgers** [comment]
Can confirm this bug also happens on the RTX 3070 (My model specifically is a Galax GeForce RTX 3070). On NVIDIA Driver ver 461.40, Runelite version 1.6.39

![](https://cdn.discordapp.com/attachments/559899386470203392/806752761105612830/unknown.png)
![](https://cdn.discordapp.com/attachments/559899386470203392/806752772250140682/unknown.png)
![](https://cdn.discordapp.com/attachments/559899386470203392/806752750552612904/unknown.png)

https://user-images.githubusercontent.com/16457802/107139165-15de6d80-6954-11eb-8669-85c4078fb31b.mp4

From these images, both times I have seen the glitch all of the glitched vertices are to the south-west direction.

The GPU plugin settings:
Draw dist: 90
Remove color banding: true
Anti aliasing: MSAA x4
UI scaling: bilinear
Fog depth: 0
Computer shaders: true (As the original poster mentioned, this only appears with compute shaders turned on)
Anisotropic filtering: 4
Colorblindness: None
Bright textures: false

**Comment by Steve4448** [comment]
Still an issue on RuneLite 1.7.7 & Nvidia 466.27.

**Comment by Adam-** [comment]
We suspect this is fixed in 881175630170a91441bb7c70106598b2afd4438c - reopen if it is still an issue
