### ISSUE TITLE
Mac/Linux ping should use ICMP if available

### ISSUE THREAD

**Issue by Hello71** [runelite/runelite#12955]
since 2011, Linux has supported unprivileged ping. however, it was not enabled by default in most distros until https://github.com/systemd/systemd/pull/13141. since this was only merged about a year ago, some older distros (Debian) may not have it yet. additionally, some users may turn it off or use non-systemd distros, and it may not be available if a user namespace (sandboxing) is being used. therefore, since the maintenance cost is negligible, TCP ping support should remain for the foreseeable future.

**Comment by Hello71** [comment]
actually, this is supported on Mac too, as pointed out in the initial Linux commit: https://github.com/torvalds/linux/commit/c319b4d76b9e583a5d88d6bf190e079c4e43213d

**Comment by Hello71** [comment]
```c
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/ip_icmp.h>

int main() {
    int sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_ICMP);

    struct sockaddr_in addr = {
        .sin_family = AF_INET, .sin_addr = {
            .s_addr = htonl(0x01010101)
        }
    };
    struct icmphdr icmp = {
        .type = ICMP_ECHO,
        .un = {
            .echo = {
                .sequence = 100
            }
        }
    };
    struct timeval timeout = {
        .tv_sec = 5
    };
    setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, &timeout, sizeof(timeout));
    setsockopt(sock, IPPROTO_IP, IP_RECVERR, &(int){1}, sizeof(int));
    sendto(sock, &icmp, sizeof(icmp), 0, (const struct sockaddr *)&addr, sizeof(addr));
    recvfrom(sock, 0, 0, 0, 0, 0);

    return 0;
}
```

strace with 1.1.1.1 (works), 0.0.0.1 locally unreachable (sendto fails), 0.0.0.1 remote unreachable (recvfrom fails), 0.0.0.2 unrouted (recvfrom fails slowly), all works fine. also tested connect+send, but apparently IP_RECVERR still needs to be set for some reason.

```java
class Timeval64 extends Structure {
    public long tv_sec;
    public long tv_nsec;
}

public interface MyLibC extends LibC {
    public static final int SOCK_DGRAM = 2;
    public static final int SOL_SOCKET = 1;
    public static final int IPPROTO_IP = 0;
    public static final int IPPROTO_ICMP = 1;
    public static final int SO_RCVTIMEO = 20;
    public static final int IP_RECVERR = 11;
    MyLibC INSTANCE = Native.load(NAME, MyLibC.class);
    int socket(int domain, int type, int protocol);
    ssize_t sendto(int sockfd, Pointer buf, size_t len, int flags, Pointer dest_addr, int addrlen);
    ssize_t recvfrom(int sockfd, Pointer buf, size_t len, int flags, Pointer src_addr, Pointer addrlen);
    int setsockopt(int sockfd, int level, int optname, Pointer optval, int optlen);
}

public int ping(World world) throws IOException
{
    MyLibC libc = MyLibC.INSTANCE;
    InetAddress inetAddress = InetAddress.getByName(world.getAddress());
    byte[] address = inetAddress.getAddress();

    int sock = libc.socket(libc.AF_INET, libc.SOCK_DGRAM, libc.IPPROTO_ICMP);
    if (sock < 0)
    {
        throw new IOException("failed to open ICMP socket");
    }

    try {
        Timeval64 tv = new Timeval64();
        tv.tv_sec = 2;
        if (libc.setsockopt(sock, libc.SOL_SOCKET, libc.SO_RCVTIMEO, tv, tv.size()) < 0)
        {
            throw new IOException("failed to set SO_RCVTIMEO");
        }
        int[] yes = {1};
        if (libc.setsockopt(sock, libc.IPPROTO_IP, libc.IP_RECVERR, IntBuffer.wrap(yes), 4) < 0)
        {
            throw new IOException("failed to set IP_RECVERR");
        }

        byte[] request = {
            8, // type
            0, // code
            0, 0, // checksum (set by kernel)
            0, 0, // id (set by kernel)
            0x76, 0x52 // sequence = 0x7652 == 'RL'
        };
        byte[] addr = {
            2, 0, // sin_family = AF_INET
            0, 0, // sin_port
            address[0], address[1], address[2], address[3] // sin_addr.s_addr
        };
        long start = System.nanoTime();
        if (libc.sendto(sock, ByteBuffer.wrap(request), request.length, 0, ByteBuffer.wrap(addr), addr.length) < 0)
        {
            if (Native.getLastError() == ErrNo.EHOSTUNREACH)
                return -1;
            throw new IOException("failed to send packet");
        }

        if (libc.recvfrom(sock, null, 0, 0, null, null) < 0)
        {
            if (Native.getLastError() == ErrNo.EHOSTUNREACH)
                return -1;
            throw new IOException("failed to receive packet");
        }

        long end = System.nanoTime();
        return (end - start) / 1000000000L;
    } finally {
        libc.close(sock);
    }
}
```

totally untested because i'm totally sick of java and jna already. C version took five minutes, Java took five hours and I'm still pretty sure it's wrong.

**Comment by Adam-** [comment]
If you could get this working I wouldn't mind adding this. But I am not going to merge untested code from a snippet in an issue comment.

**Comment by Hello71** [comment]
Nah, I don't even use RuneLite anymore. I don't really care that much if you merge it or not, it was mostly a learning exercise. JNA kinda sucks, so I can understand if you don't wanna spend time fiddling with it.

**Comment by Leo288** [comment]
https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#isReachable

```
public boolean isReachable(int timeout)
                    throws IOException
```
> A typical implementation will use ICMP ECHO REQUESTs if the privilege can be obtained, otherwise it will try to establish a TCP connection on port 7 (Echo) of the destination host. 

Wouldn't it be easier (and less error prone) to delegate this to `InetAddress.isReachable` as it falls back gracefully? Unless there's something obvious I've missed there.

**Comment by Adam-** [comment]
`isReachable` doesn't return the ping rtt, which is the entire purpose.

**Comment by Leo288** [comment]
Client-side overhead must be fairly minimal there, wouldn't you just timestamp it either side? I could profile that perhaps..?

**Comment by Adam-** [comment]
That might be possible, you could look into it if you want. Although I think a pure-JNA impl wouldn't be so bad if done correctly. It seems like he has most of it already.

**Comment by Hello71** [comment]
there's actually another issue with isReachable: it uses IPPROTO_ICMP, but with SOCK_RAW, not SOCK_DGRAM, which means unprivileged use is not permitted. that should probably be fixed upstream, but my experience with openjdk contribution is that feature requests are ignored without either money or patches with signed CLAs.

**Comment by Hello71** [comment]
also, I wasn't clear earlier, but I did test the C version and it works fine on my Linux. the only work required is to convert it into JNA (since I assume regular JNI is not preferred).

**Comment by Adam-** [comment]
I've fixed this and committed it in fc72d17a5575a0a6c042979fe3c018d19fa578a5. It does not work on macos currently though.

**Comment by Adam-** [comment]
If anyone is following this, I've added support for macos in 8fa085f4f9f2431ed92e2d7b5043e9b885a669fc

**Comment by Vulki0** [comment]
Adam is trying really hard to redeem himself after trashing the mac community and deliberately making the user experience worst for runelite users. Don't forget the huge scandal back in 2020 when he lied the mac numbers. It is not 6%.

Don't trust him guys.

**Comment by MACOSRL** [comment]
Adam is trying really hard to redeem himself after trashing the mac community and deliberately making the user experience worst for runelite users. Don't forget the huge scandal back in 2020 when he lied the mac numbers. It is not 6%.

Don't trust him guys.
