### ISSUE TITLE
Add !Def {Monster/Boss Name} to Display the targets defensive stats

### ISSUE THREAD

**Issue by tactics-osrs** [runelite/runelite#12963]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
it is time consuming to have to check the defensive stats of every slayer task to know what 
attack style i should bring for efficiency.
**Describe the solution you'd like**
I would like a command to be added : !Def which would display the Defensive stats of monsters and bosses depending on what was typed like this ::!def {Monster name/Boss name}
{enter} *displays the defensive stats of the target*
example of this would be: {Send} !Def Ancient Wyvern{Enter}
Tactics:Ancient Wyvern Defensives: s 70 s 70 c 70 m 170 r 120
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
another alternative could be adding a option to the wiki button under map to look up and chat the stats of the monster/boss or add a gui that shows when hovering over monster
**Additional context**

**Comment by Nightfirecat** [comment]
This is very similar to #12554. I don't think we're interested in adding something like this since getting that information via the wiki lookup only requires two clicks.
