### ISSUE TITLE
Change cursor to waiting when server lags.

### ISSUE THREAD

**Issue by bluelightzero** [runelite/runelite#12964]
Like this:

![image](https://user-images.githubusercontent.com/4492982/102924581-c7e7d600-4489-11eb-896e-5b67f4806777.png)

All you would need to do every frame is check when the last tick was, and if it is longer than 600ms ago, use this.

**Comment by MESLewis** [comment]
This is on the plugin hub.
https://github.com/bluelightzero/unresponsive-cursor
