### ISSUE TITLE
Whenever you tag an item, whatever you are searching in your bank goes away

### ISSUE THREAD

**Issue by Chipure** [runelite/runelite#1297]
If you changed this it would make it much easier to tag several items at once. E.G if you are attempting to tag a full void set, you have to tag each, and then search it again and repeat. 
Thanks

**Comment by Abextm** [comment]
To do this we would have to save varcstr22 before opening our input widget, run the GE input script, and then restore varcstr22. I think we would have to fix the event bus recursion thing if we were to do this.
