### ISSUE TITLE
Clickbox for ape atoll agility course to big

### ISSUE THREAD

**Issue by randomfeedbackguy** [runelite/runelite#12976]
I noticed that the 4th obstacle of the course, the skull slope, isnt correctly highlighted with the green clickbox.  The clickbox is to big, so if you click to high/low in the clickbox, you dont go up the slope.

Its a minor bugg/glitch but can be annoying.

**Comment by llamositopia** [comment]
Looks like the object (ID 15483) clickbox dips below the ground. There are multiple distinct accessible clickboxes, one for each of the skulls on the ground. However, all of these are encapsulated in one game object. 

Highlighting these likely isn't possible to fix.

Here's a video demonstrating it. All these clickboxes are considered one object together: 


https://user-images.githubusercontent.com/1868974/103426849-75de3900-4b8a-11eb-8a6c-29dc9fd289a4.mp4

**Comment by randomfeedbackguy** [comment]
I haven't noticed that! Thanks for looking into it.

**Comment by Adam-** [comment]
fixed in fdd84f929de8199f50514f80d98f97dbbd6b20d6
