### ISSUE TITLE
Zalcano plugin: shows overlay whenever a vanilla healthbar is shown

### ISSUE THREAD

**Issue by Bram91** [runelite/runelite#12984]
**Describe the bug**
When entering the Hunleff fight in the gauntlet the zalcano overlay appears.
The same issue occurs for the nightmare/chambers of xeric

**To Reproduce**
Trigger any vanilla healthbar to show

![image](https://user-images.githubusercontent.com/7499230/103213246-63a39700-490d-11eb-93de-e3fbdedc342b.png)

**Comment by Broooklyn** [comment]
This also occurs during the olm fight in chambers

**Comment by Nightfirecat** [comment]
Fixed in c5a52754e06abfc0f7dc35be0e86e3ec604d5040
