### ISSUE TITLE
UI bug whilst in RL settings

### ISSUE THREAD

**Issue by OBJordz** [runelite/runelite#12981]
Cant change any RL settings not sure how to describe this bug also cant really retrace my steps as you can see from the video it kind of just happens, I am using the latest version of RL and on Windows 10 pro if this is any help.

https://user-images.githubusercontent.com/76656628/103174448-203c2080-485a-11eb-9926-3ff5562a7b52.mp4

**Comment by Hydrox6** [comment]
Duplicate of #11727
