### ISSUE TITLE
Toolbar stutters when client is focused causing fps drops

### ISSUE THREAD

**Issue by armadylgamer** [runelite/runelite#12991]
**Describe the bug**

When the game is in focus and you use a function of the toolbar such as player lookup or the metronome for prayer flicking it causes an fps drop in game to unplayable levels until the toolbar finishes whatever it was doing.

**To Reproduce**
1. Focus runelite
2. Scroll through plugins/settings or search for a players stats
3. Client will lag until finished toolbar action or focusing new app

**Expected behavior**
I expect to be able to use the metronome/lookup player stats/scroll through settings without my client dropping fps to unplayable amounts

**Screenshots**
Video of issue below
[https://twitter.com/kyle71115176/status/1343868772973649922?s=20](url)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Newest
 - Launcher version: Newest
 -PC Specs: Ryzen 5 3600, RTX 2060 SUPER

**Additional context**

I have tried reinstalling and disabling hardware acceleration. Thanks if anyone can find a fix for this.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
