### ISSUE TITLE
Add a Master Switch to turn off and on plugins.

### ISSUE THREAD

**Issue by imzondax** [runelite/runelite#13003]
Hi, I was wondering if it would be possible to add a master switch for runelites plugins.

One larger button that turns on and off your active plugins. I would love for it to be possible to remember what plugins where on when you turn them off, so you dont have to remember each time what plugins you last used. 

I made this Gif of how I think it could look like.

![Master switch](https://user-images.githubusercontent.com/36119211/103449433-943a5680-4ca8-11eb-8e07-733a4488e6b5.gif)

It makes it easier to turn on and off all your plugins. for times that you would like to play vanilla or just check something out real quick instead of turning off 10-20 plugins manually to check something fast out.

**Comment by stoddy15** [comment]
Sorry I don't think this should be developed. It's a waste of developers time when there are critical things that have not worked on Mac for a while.

**Comment by abextm** [comment]
Disabling every plugin is a bad idea because it will make people think they can do that as a substitute to reproducing a bug on vanilla.
