### ISSUE TITLE
Reset xp tracker "XP/hour" field after set delay

### ISSUE THREAD

**Issue by xlrc** [runelite/runelite#13001]
**Is your feature request related to a problem? Please describe.**
Xp tracker that runs on a 5 min rolling average similar to how the runemetrics xp tracker in rs3 works.

**Describe the solution you'd like**
Skill experience tracker displays XP/hour based on previous 5 minute window of experience gained. Currently, a few minutes of afk causes the XP/hour to be inaccurate. I realise there is an autopause to achieve something similar, but it still uses and continues from the previously collected data, still requiring a reset of the tracker.

I'd like for the XP/hour (but not the XP gained) field to reset after some timeout.

**Comment by Nightfirecat** [comment]
If added, would you be expecting this to automatically reset the tracker for skills that have not had recent activity? Would changing the "Auto pause after" setting to allow for pausing or for resetting fulfill this request?

**Comment by xlrc** [comment]
I'd love for it to auto-reset all skills that have not had recent activity. 

After thinking about it after your selection, if there was a toggle for auto-pause/auto-reset it would allow for a custom reset value to be entered
