### ISSUE TITLE
Disable custom chrome window fullscreen bug

### ISSUE THREAD

**Issue by Optumasfx** [runelite/runelite#13017]
These are my settings and I am on OSX 11.1 in full screen mode

<img width="279" alt="1" src="https://user-images.githubusercontent.com/76658119/103916186-09bc8180-5104-11eb-922a-c7795877eb43.png">

when I press the tab on the right hand side it looks like this

<img width="2048" alt="2" src="https://user-images.githubusercontent.com/76658119/103916356-3cff1080-5104-11eb-94af-d52b76b5343f.png">

when I close the tab the screen messes up

<img width="2048" alt="3" src="https://user-images.githubusercontent.com/76658119/103916447-5738ee80-5104-11eb-99e4-8e983a6b5c39.png">

**Comment by Optumasfx** [comment]
I think I fixed it by changing resize type to keep window size. Can this and disable custom window chrome be default on mac please?

**Comment by stoddy15** [comment]
I don't think the developers are Mac users

**Comment by Optumasfx** [comment]
I think Adam has a mac as he fixed the gpu plugin
