### ISSUE TITLE
addon to idle notifyer

### ISSUE THREAD

**Issue by pettrs** [runelite/runelite#13026]
**Is your feature request related to a problem? Please describe.**
It's not a problem, no

**Describe the solution you'd like**
Add an option to get notification based on remaining inventory space, so that if say im fishing, and i want to be notified before it stops fishing, having an option to set that you get a notification when you have 2 inventory spaces left i'd be able to upkeep the efficiency a little bit better.

**Describe alternatives you've considered**
idk

**Additional context**
nop

**Comment by Hydrox6** [comment]
Duplicate of #3969
