### ISSUE TITLE
Runelite does not sent Idle notifications when mining with a dragon pickaxe with trailblazer ornament.

### ISSUE THREAD

**Issue by acheng-ubc** [runelite/runelite#13025]
Runelite does not sent Idle notifications when mining with a dragon pickaxe with trailblazer ornament, nor does it recognize it as mining (top left corner stays on "NOT mining")

**To Reproduce**
1. Idle Animation and Interaction Notifications checked in Idle Notifier
2. Use Trailblazer tool ornament on Dragon Pickaxe
3. Go to Motherlode Mine 2nd floor
4. Mine rocks

**Expected behavior**
Expected notifications for when mining stops.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.6.36.1
 - Launcher version: Unknown??

**Additional context**

**Comment by 115Apollo** [comment]
Same thing happens when using dragon axe with trailblazer kit for any tree
