### ISSUE TITLE
Maniacal Monkey Hunter

### ISSUE THREAD

**Issue by BradleeThomas** [runelite/runelite#13038]
Could we get a feature to link the idle parts of Maniacal Monkey Hunter into the runelite feature that flashes the screen red when my character is afk

**Comment by Nightfirecat** [comment]
We have developer support for sending notifications from any plugin, not just the idle notifier. Please request this feature from the maker of that plugin, as that is not a main client plugin.

**Comment by BradleeThomas** [comment]
There isn't a plugin for maniacal monkey hunter as far as I'm aware so how can I ask for developer support to send me a notification? sorry if I'm not using the correct terms or am writing simple, I don't have any understanding of coding and plugins.

I just want my screen to flash red when a monkey escapes the trap or I catch one or the trap falls so I know to do my next action.

**Comment by Nightfirecat** [comment]
My bad, I misunderstood this request, confusing it with the Monkey Metrics hub plugin

**Comment by BradleeThomas** [comment]
hey sorry you can close this again. theres actually an option in hunter settings thats disabled for manical monkeys automatically and i had to turn it on, i feel so stupid
