### ISSUE TITLE
UI Scaling Inappropriately

### ISSUE THREAD

**Issue by Mason0567** [runelite/runelite#13037]
Haven't played OSRS in awhile, and I reinstalled windows since the last time. I just installed runelite again, but realized that my client isn't resizing as it used to. The monitor I'm using hasn't changed.

Attached are two screenshots:
 • Old - How my UI used to scale
 • New - Current screenshots with a variety of settings on/off including stretched mode on/of, same as GPU and adjusting game size in the Runelite plugin.

Any ideas why it changed?

### Old
![Old](https://user-images.githubusercontent.com/39751299/104116278-ea705080-52cb-11eb-872c-27abcb0887ce.jpg)

### New
![New](https://user-images.githubusercontent.com/39751299/104116277-e93f2380-52cb-11eb-8c52-ef332a4952e4.png)
![New2](https://user-images.githubusercontent.com/39751299/104116308-3f13cb80-52cc-11eb-94a5-8fe06b4aaabe.png)
![New3](https://user-images.githubusercontent.com/39751299/104116307-3de29e80-52cc-11eb-8b8a-b5a7bdf41730.png)

**Comment by Mrnice98** [comment]
your in fixed mode ?

**Comment by MESLewis** [comment]
https://oldschool.runescape.wiki/w/Settings

**Comment by Mason0567** [comment]
All that, and it turns out to be an in-game setting... Sorry, thanks all!
