### ISSUE TITLE
Tor support

### ISSUE THREAD

**Issue by stoddy15** [runelite/runelite#13033]
Can you consider adding tor support so we can play privately?

**Comment by stoddy15** [comment]
also I posted a brilliant idea earlier on another issue this morning

I was wondering if we could have a pastebin runelite plugin that we can communicate within the text? for example I would send jCKdgSrG to someone on runelite. they would click it and it would redirect to https://pastebin.com/jCKdgSrG

After someone has clicked that link, read it once it will be burnt so no-one can read it again then they will create a pastebin to reply

<img width="498" alt="Screenshot 2021-01-09 at 1 16 35 pm" src="https://user-images.githubusercontent.com/63739578/104110723-55248a80-52d2-11eb-9237-3cb37cfecbf9.png">

**Comment by Adam-** [comment]
no

**Comment by stoddy15** [comment]
The primary reason for window curtains in our house, is to stop people from being able to see in. The reason we don’t want them to see in is because we consider much of what we do inside our homes to be private. Whether that be having dinner at the table, watching a movie with your kids, or even engaging in intimate or sexual acts with your partner. None of these things are illegal by any means but even knowing this, we still keep the curtains and blinds on our windows. We clearly have this strong desire for privacy when it comes to our personal life and the public.
