### ISSUE TITLE
Menu Entry Swapper for Pickpocketing Vyres

### ISSUE THREAD

**Issue by AbeAxis** [runelite/runelite#13035]
The specific example I have is Vyres. Their first option is Talk-To and their second option is Pickpocket. Because we cannot attack them, there are no options within the RuneScape settings to remove the talk-to option.

**Comment by hex-agon** [comment]
This is not allowed per jagex's statement:
https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1

**Comment by AbeAxis** [comment]
Thanks for the response! I didn't know they had these restrictions!
