### ISSUE TITLE
Can we please get the IOS moaning emoji

### ISSUE THREAD

**Issue by Markvsid** [runelite/runelite#13046]
![download](https://user-images.githubusercontent.com/77373801/104406215-0e29d580-551c-11eb-9e15-20f0e39230c1.png)

Hi, I am in desperate need of this emoji from IOS and I think many people would use it in the chat plugin. Runelite already has many different emojis similar to ios emojis  and I would appreciate it if this one was added.

**Comment by WolffTech** [comment]
Any suggestions for what you would type in chat to trigger this emoji?
