### ISSUE TITLE
JMacNotification support

### ISSUE THREAD

**Issue by Optumasfx** [runelite/runelite#13056]
Would it be possible to support JMacNotification or have this as a plugin?

https://github.com/airsquared/JMacNotification

**Comment by Cornelius-Cell** [comment]
Definitively possible but i think the devs would want to make it external

**Comment by nlruk** [comment]
+1 to having native support for mac notifications, not being able to click the notification to bring Runelite into focus is quite frustrating.

**Comment by abextm** [comment]
I dislike having random unknown natives on the hub since its nearly impossible for me to verify them. Also we don't provide a way to replace the notifier.

**Comment by Adam-** [comment]
There is a notification event that plugins can pick up on and then send their own notifications, wouldn't that work?

**Comment by abextm** [comment]
Hmm, yes that is a thing now. There is still a chunk of random objc that someone needs to verify + build + etc.

**Comment by Nightfirecat** [comment]
A feature request for more-native Mac notifications is already open here: #12417. Please continue discussion there
