### ISSUE TITLE
Odd Menu Display Bug

### ISSUE THREAD

**Issue by Deathomen** [runelite/runelite#13054]
Started having an odd bug today. I only recently started playing OSRS again this week, but I don't recall having this issue a few days ago when I reinstalled Runelite. The menu will sometimes bug out and start showing the text/graphics all over the place. I'm not really sure how else to describe it, sorry for the bad description.

I captured a video of the behavior, but please let me know if there is any other information I can provide to help troubleshoot.

https://youtu.be/vxEl8ej9l1s

**Comment by MESLewis** [comment]
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.
