### ISSUE TITLE
Trailblazer Pickaxe Issues with MLM plugin and Idle Notifications at MLM

### ISSUE THREAD

**Issue by KiteOrFlight** [runelite/runelite#13066]
**Describe the bug**
When A trailblazer pick is used at MLM the "show current mining state" feature of the MLM plug-in is non-operable. Shows a "not mining" state the entire time. Furthermore when using the trailblazer pickaxe idle notifications are not sent. 

**To Reproduce**
1. Go to MLM
2. Equip Trailblazer Pickaxe
3. Attempt to mine from ore vein, wait for vein to run out.
4. Notice non working mining state feature and lack of idle notification.

**Expected behavior**
MLM plugin to properly show current mining state, and for idle notifications to be send to the system properly.

**Environment (please complete the following information):**
 - OS: [macOS]
 - RuneLite version: [1.6.36]
 - Launcher version: [Unknown]

**Comment by Nightfirecat** [comment]
Related to #13025
This will be fixed by #13019
