### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by Exquze** [runelite/runelite#13078]
A couple weeks ago after a RL update I've had intermittent issues with the zooming feature. Most of the time it doesn't work, after a bunch of restarts of the client and the pc there's a chance it works.

I don't have any issues with the scroll outside the game and the scroll works in the plugin configuration window. Zooming isn't disabled in the control settings.
At first I thought it might be a plugin that's causing this so I've tried disabling every single plugin, restarting the client but it didn't fix it.
Tried reinstalling RL as well. I'm out of ideas now..

Edit: 
Sometimes when i log in the zoom works for about 3-5 seconds, and then it stops working.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
