### ISSUE TITLE
GPU plugin wont turn on (Mac M1)

### ISSUE THREAD

**Issue by Optumasfx** [runelite/runelite#13071]
The GPU plugin keeps turning off on the new M1 macbook

It worked on my other intel macbook pro

**Comment by Hydrox6** [comment]
The GPU works fine through Rosetta from what we've seen and tested.
Native Arm64 is unsupported at the moment.
This issue is incredibly barebones; use the issue template.
Related to #12959

**Comment by Optumasfx** [comment]
<img width="717" alt="Screenshot 2021-01-16 at 5 57 51 pm" src="https://user-images.githubusercontent.com/76658119/104819285-67e41580-5824-11eb-94e6-4573827cc890.png">

I followed everything in your guide and it does not work. I turn it on and it turns itself off

**Comment by Hydrox6** [comment]
1. Not my guide
2. Not officially supported

**Comment by hex-agon** [comment]
As stated on such tutorial, the gpu plugin it not functional on M1 macs.

**Comment by abextm** [comment]
duplicate #12959

**Comment by Optumasfx** [comment]
> As stated on said tutorial, the gpu plugin it not functional on M1 macs.

did not see, sorry. when should we see a fix? does this have anything to do with compute shaders?
