### ISSUE TITLE
Scamming Plugin

### ISSUE THREAD

**Issue by Jeroen1992** [runelite/runelite#13076]
Dear developers,

Last week i installed the official plug-in "armour trimmer" plug-in from the plug-in hub.
Shortly after that i got spooky messages in my chat box stating that i should go to edgeville with my best armour to get it trimmed for 50k even tough my private chat is always on friends.
Maybe i should have taken screenshots but to be honest i just wanted to remove this bad plug-in as fast as possible.
Luckily I'm experienced enough to know that armour trimming is a scam but newer player who might have taken a long time getting that armour might lose it which is a very bad thing.

Kind regards,
Jeroen

**Comment by 0anth** [comment]
It looks like that's the welcome message, it says it every time you login.

Turn off the "Welcome message" option in the config if you do not want to see this.

**Comment by Jeroen1992** [comment]
So it's supposed to be a joke?

**Comment by loldudester** [comment]
Yes

**Comment by Hydrox6** [comment]
It helps to read what the plugin does before installing it. iirc, the "spooky messages" are also from someone who's name is too long to exist.

Also, just a nitpick: hub plugins aren't "official plugins", just like how apps on Apple's App Store or Google Play aren't officially Apple's or Google's.
