### ISSUE TITLE
Time Tracking not syncing properly across devices

### ISSUE THREAD

**Issue by KnightosMaster** [runelite/runelite#13077]
**Describe the bug**
I use 3 different devices (actually two but I dual-boot on one) to play the game. I am logged in to RuneLite on all three, and the Time Tracking is not synced properly between the three clients. On the RuneLite webpage when checking the Time Tracking tab I have three accounts with the same name present (which correspond to the three devices).

The syncing of other features (notes, settings, loot tracker) work properly, it's only the time tracking that is bugged. 

**To Reproduce**
1. Log in to RuneLite on one device, plant plants
2. Log in to RuneLite on another device, see no plants are planted :( 

**Expected behavior**
Time tracking is synced properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/655652/104843185-910ab180-58c9-11eb-9e92-04c8acb137c8.png)
![image](https://user-images.githubusercontent.com/655652/104843199-a1229100-58c9-11eb-886f-500f277dfe56.png)
![image](https://user-images.githubusercontent.com/655652/104843209-a97acc00-58c9-11eb-96cd-50526d4c0579.png)

**Environment (please complete the following information):**
 - OS: Arch Linux, 2x Windows 10 (Enterprise - 1809)
 - RuneLite version: 1.6.32.2
 - Launcher version: 2.1.6

**Comment by Nightfirecat** [comment]
Are you on Discord? If so, could you join the RuneLite server (https://runelite.net/discord) and send your config file, found at `~/.runelite/settings.properties` to me via DM? This looks like it could be the result of a possible bug in our profile hash generation code.

**Comment by Hydrox6** [comment]
Closing as this is stale, and it seems no follow-up was taken

For further questions of support, please join the [Discord](https://runelite.net/discord)
