### ISSUE TITLE
Ignore special characters in chat filter Regex

### ISSUE THREAD

**Issue by jakkyjack** [runelite/runelite#13097]
Gambling and other scamming bots at G.E. have started using special characters to avoid chat filters.

Could we somehow make Chat Filter more resilient to this? Regexing all special characters seems to not be viable due to the amount of characters available.

Could we call Normalizer.normalize on all chat messages passed to Chat filter or something?

**Comment by ArchFrosty** [comment]
This would be very helpful I don't have enough time/gradle knowledge to implement and test this but I think it might be as simple as adding something like https://github.com/gcardone/junidecode#tldr right after this line https://github.com/runelite/runelite/blob/ab5d90fdca0b817414f6aece551efa40f274be50/runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java#L318

Public chat is full of this these days https://i.imgur.com/1UaVoOi.png

**Comment by Adam-** [comment]
added in 1362af414a1a7c4e6ec3fc678f00a9aecb233b6f
