### ISSUE TITLE
Right click on player to add them to ignore list

### ISSUE THREAD

**Issue by PopMyStack** [runelite/runelite#13090]
**Is your feature request related to a problem? Please describe.**
We have been experiencing a great deal of people at the GE repeating the following texts: "Buying all expensive items" or asking people to sell them expensive items that they are willing to over pay for. It is very annoying to watch. I have to manually add them to the ignore list if I wish to no longer see their text.

**Describe the solution you'd like**
A right-click option on the player to add to ignore list. It would allow you to no longer see new messages over their heads or in the chat.

**Describe alternatives you've considered**
Adding a list of usernames to the runelite client instead through right click to not overpopulated our ignore list.

**Additional context**
N/A

**Comment by Hydrox6** [comment]
Players can already be ignored by right clicking on the chat message. Given that ignoring only affects whether chat messages are visible, the only time you'll know whether you want to ignore someone will be a situation in which you can already mute them.

**Comment by PopMyStack** [comment]
You are absolutely right! Thank you for the reply.
