### ISSUE TITLE
Portal Nexus rename ancient magic teleport spells (and Marim)

### ISSUE THREAD

**Issue by ThimbleFire** [runelite/runelite#13092]
![](https://i.imgur.com/IE0U0CR.png)

to

![](https://i.imgur.com/FDKxEQB.png)

And Sennitisten, Marim, Carrallangar...

All the options available that show parenthesis on this page: https://oldschool.runescape.wiki/w/Portal_nexus

**Comment by Nightfirecat** [comment]
Related to #3354

**Comment by abextm** [comment]
The `Better Teleport Menu` plugin on the Plugin Hub can now do this.
