### ISSUE TITLE
Clue scrolls with incorrect steps

### ISSUE THREAD

**Issue by FalseRitual** [runelite/runelite#1309]
Start of a thread to post problems with the new clue scroll plugin (incorrect steps)

**Comment by FalseRitual** [comment]
clue step contains "dance a jig"
tags dance as the emote instead of jig

https://gyazo.com/922ec574f0a59ab57b89df0143782bfc

**Comment by FalseRitual** [comment]
Cheer for the monks at Port Sarim. Equip a coif, steel plateskirt and a sapphire necklace. (easy clue)
not registering clue

https://gyazo.com/f8bc7bd9dd11f6fb3df56df0423a837a

**Comment by FalseRitual** [comment]
Wave on Mudskipper Point. Equip a black cape, leather chaps and a steel mace. (easy clue)
emote square is in the incorrect position (put next to the STASH unit)

https://gyazo.com/42ab2ab166b1d3106fa9fa64b15ba83a

**Comment by FalseRitual** [comment]
Map clue (easy) near champion guild
not registering clue

https://gyazo.com/e1d376b2ff001ca153147bc935e98e02

**Comment by FalseRitual** [comment]
Dance in the Party Room. Equip a steel full helmet, steel platebody and an iron plateskirt.
not registering clue

https://gyazo.com/f4df46b485ead209311d5b0b9f28ea85

**Comment by MagicfTail** [comment]
Map clue near crafting guild, not registering

![image](https://user-images.githubusercontent.com/12607046/38456942-8b3600c6-3a8a-11e8-8682-8e6f527bf267.png)

**Comment by FalseRitual** [comment]
Search chests found in the upstairs of shops in Port Sarim.
bookcases are being tagged while the chest is the solution 

https://gyazo.com/0a766c0a1dbf5c0c37b5bc55df09764b

**Comment by FalseRitual** [comment]
Search the boxes in the house near the south entrance to Varrock.
Object labeled as table, should be box (arrow in the screenshot)

https://gyazo.com/a99f76f3eeb9868ac1cdc192019486de

**Comment by devLotto** [comment]
For map clues, the item ID of the clue scroll and the coordinates of the dig location is needed to be able to add it. This information can be collected by using the developer tools plugin, but the clue is needed to do it.

**Comment by FalseRitual** [comment]
Clap on the causeway to the Wizards' Tower. Equip an iron med helm, emerald ring and a white apron. (easy clue)
clue not registering
Clue ID: 10182
Tile: 3113, 3194, 0

![](https://i.gyazo.com/4348564549f97db0675dea569ea7c09b.png)

**Comment by SomeZer0** [comment]
Hard Clue: Read 'How to breed scorpions.' By O.W.Thathurt.
https://vgy.me/7pGmsf.png
Tooltip typo: "the 1st2nd floor"

**Comment by SomeZer0** [comment]
Easy Clue: Search the crates in Draynor Manor
![Image of Clue](https://vgy.me/Qy9FSP.png)
Highlights the wrong type of crate/incorrect position.

**Comment by MagicfTail** [comment]
Not highlighting crate in "search a crate near the monks that like to party" clue

**Comment by FalseRitual** [comment]
Dance in the shack in Lumbridge Swamp. Equip a bronze dagger, iron full helmet and a gold ring. (easy clue)
Not producing emote tile
Clue ID: 10180
Tile: 3203, 3169, 0

![](https://i.gyazo.com/e1b58cbcf18dcb30156a3ccb1fd15717.png)

**Comment by FalseRitual** [comment]
Wave along the south fence of the Lumber Yard. Equip a hard leather body, leather chaps and a bronze axe. (easy clue)
Not producing emote tile
Clue ID: 10230
Tile: 3307, 3491, 0

![](https://i.gyazo.com/a7ae5340e5f35f58b7c87b027d7f8de5.png)

**Comment by FalseRitual** [comment]
Search the drawers in Catherby's Archery shop. (easy clue)
Drawers not being highlighted
Clue ID: 2700
Tile of Drawers: 2825, 3442, 0
Drawer ID (closed): 350
Drawer ID (open): 351

![](https://i.gyazo.com/ff38e6e15053fd09b25d9f38ac9988c6.png)

**Comment by FalseRitual** [comment]
Strength potions with red spiders' eggs? He is quite a herbalist.
NPC not being highlighted
Clue ID: Forgot to push button soz (will update later)
NPC ID: 5036

![](https://i.gyazo.com/f6836b6c1584026b6713ee7d62a9fb46.png)

**Comment by FalseRitual** [comment]
Search the drawers, upstairs in the bank to the East of Varrock.
Clue not registering
Clue ID: 2687
Tile of Drawers: 3250, 3420, 1
Drawer ID (closed): 7194
Drawer ID (open): 7195

![](https://i.gyazo.com/fec0659162c85009300bd7e544c6c877.png)

**Comment by FalseRitual** [comment]
Search the crates in a house in Yanille that has a piano. (easy clue)
Incorrectly tagging search location (diagonal wall tiles)
Clue ID: 3491
Wall ID: 17088
Crate ID: 357
Tile location of crate: 2598, 3405, 0

![](https://i.gyazo.com/d85b684edffccd1dc7bdb50d5c6601b4.png)

![](https://i.gyazo.com/e8b88847f333faad7d4f23f4fcdeb68b.png)

**Comment by FalseRitual** [comment]
Search the crates in Canifis. (easy clue)
highlighting incorrect crates
Clue ID: 7238
Crate ID: 24344
Tile ID of crate: 3509, 3497, 0

![](https://i.gyazo.com/3442636bed85b28fa6d2ca56a0e92cb8.png)

**Comment by FalseRitual** [comment]
Search for a crate in Varrock Castle. (easy clue)
not highlighting crate
Clue ID: 3515
Crate ID: 5513
Tile ID of crate: 3224, 3492, 0

![](https://i.gyazo.com/3810799b13751c67382ce98ac1e0a043.png)

**Comment by FalseRitual** [comment]
Search the chest in the left-hand tower of Camelot Castle. (easy clue)
Chest not being highlighted
Clue ID: took a terrible screen shot (will update later)
Chest ID (closed): 25592
Chest ID (open): 25593
Tile ID of chest: 2748, 3495

![](https://i.gyazo.com/58b1c20d5f7448d69c7a13b17fefc4cb.png)

**Comment by FalseRitual** [comment]
Search the bucket in the Port Sarim jail. (easy clue)
bucket not being highlighted
Clue ID: 12192
Bucket ID: 9568
Tile ID of bucket: 3013, 3181, 0

![](https://i.gyazo.com/5489eae2b4c0cdb5241394f2d6b687a0.png)

**Comment by FalseRitual** [comment]
Search the crates in the shed just north of East Ardougne. (easy clue)
crate not being highlighted
Clue ID: 2707
Crate ID: 355
Tile ID of crate: 2617, 3347, 0

![](https://i.gyazo.com/bfbda8c653afe2670ba8d42316f9ddcc.png)

**Comment by FalseRitual** [comment]
Search through some drawers found in Taverley's houses. (easy clue)
Drawers not being highlighted
Clue ID: 3500
Drawer ID (closed): 350
Drawer ID (open): 351
Tile ID of Drawers: 2894, 3418, 0

![](https://i.gyazo.com/460803d4d3003d0309084322cf546755.png)

**Comment by FalseRitual** [comment]
Yawn in Draynor Marketplace. Equip studded leather chaps, an iron kiteshield and a steel longsword. (easy clue)
No emote tile produced
Clue ID: 10184
Tile ID: 3083, 3253, 0

![](https://i.gyazo.com/6fb982badff2cc739244b064bfd133b7.png)

**Comment by FalseRitual** [comment]
Talk to Ermin. (easy clue)
NPC not highlighted
Clue ID: 19828
NPC ID: 2567

![](https://i.gyazo.com/a08363f21465bce9e7e5f25829324e7c.png)

**Comment by FalseRitual** [comment]
Search the drawers in a house in Draynor Village. (easy clue)
Drawers not being highlighted
Clue ID: 3512
Drawer ID (closed): 350
Drawer ID (open): 351
Tile ID of Drawers: 3097, 3277, 0

![](https://i.gyazo.com/0ff2e1045760f2efa6b36dd84dca1051.png)

**Comment by FalseRitual** [comment]
Search the chests upstairs in Al Kharid Palace. (easy clue)
chest not being tagged
Clue ID: 2680
Tile of Chest: 3301, 3169, 1
Chest ID (closed): 375
Chest ID (open): 376

**Comment by FalseRitual** [comment]
Anagram clue: Blue Grim Guided (hard clue)
Clue not being registered
NPC ID: 306

![](https://i.gyazo.com/83eea680aafed0de576f3be1137d5e47.png)

**Comment by KingLehon** [comment]
Cryptic Clue : Search for a crate on the ground floor of a house in Seers' Village
Object appears as "Null" should be a crate
![image](https://user-images.githubusercontent.com/29807845/38675363-70b9b19a-3e25-11e8-8ea2-3c2c753c75c7.png)

**Comment by mtarik550** [comment]
Medium clue - 

> Speak to Hazelmere.
 doesn't open the clue interface
Should also show the answer when speaking the Hazelmere

**Comment by mtarik550** [comment]
add world point for this medium clue
https://i.imgur.com/9XNgVXa.png

**Comment by mtarik550** [comment]
https://i.imgur.com/VYgchXf.png

Please add cluescroll help to this clue, including the item requirements and the emote requirements as with other clues.

**Comment by Adam-** [comment]
Well this thread has quickly turned into a disaster. This is maybe all fixed now from #1383? Hard to tell.

**Comment by KingLehon** [comment]
![image](https://user-images.githubusercontent.com/29807845/39089100-536f4e50-458d-11e8-9aa7-ec4aaa5c96a3.png)

Cry on the shore of Catherby beach (emote clue) doesn't open interface to show it's an emote clue.
((Medium clue))

**Comment by Savion** [comment]
![image](https://user-images.githubusercontent.com/923785/39090995-19ead0a4-45b1-11e8-8012-153cc40afb1b.png)

Equip an iron platebody for the  "Spin in Draynor Manor" easy clue but it states to equip an iron plateleg.

**Comment by nmq12** [comment]
![image](https://user-images.githubusercontent.com/5819477/39706448-779b96f4-51df-11e8-8bfc-d69346ac2bed.png)
Lumberyard hint is 1 off from the actual crate

**Comment by Nightfirecat** [comment]
I think most of these have been fixed. Can we close this mega-issue now?
