### ISSUE TITLE
Additional compass interface

### ISSUE THREAD

**Issue by pettrs** [runelite/runelite#13113]
**Is your feature request related to a problem? Please describe.**
Current compass isn't movable without moving the entire map on resizable

**Describe the solution you'd like**
A compass that is seperate from the map and can be alt-moved freely around the screen, or attached to a tile, object or an npc.

**Describe alternatives you've considered**
Could be useful in instances like inferno where someone helps you. if you can customize certain tilemarker compasses to highlight north, south, east or west direction it could help increase efficiency like for example if i mark the spirit tree in the grand exchange with east, ill be able to see what direction to click without having to use my map.

**Additional context**
Compass should be as simple as possible, something like this if it hilights a direction
![unnamed](https://user-images.githubusercontent.com/75093127/105844909-3f091080-5fda-11eb-8af0-cf906ab9d2ff.jpg)

And attached to a tile, object or npc similar to this
![68747470733a2f2f692e696d6775722e636f6d2f414b70354245592e706e67](https://user-images.githubusercontent.com/75093127/105845893-ba1ef680-5fdb-11eb-876a-d576f3750a08.png)

**Comment by Nightfirecat** [comment]
We're not going to separate the compass widget from the world map. As for adding labels, this is basically covered by using ground marker labels already.
