### ISSUE TITLE
Make "walk here" the default option for pets so you dont accidentally click on them

### ISSUE THREAD

**Issue by forevernomana** [runelite/runelite#13139]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Hydrox6** [comment]
This is already a vanilla option: `Move follower options lower down`.
