### ISSUE TITLE
Clue scroll plugin highlights every matching GameObject.

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#1314]
For example:
![4 Bookcases](https://vgy.me/oAnlKt.png)
Only 1 bookcase should be highlighted, but it selects them all.

Not sure exactly what information is required to fix this.
I'm assuming it needs to be fixed per step? If so, I can try and help grab Clue scroll ID and Coordinates of the GameObjects when I get these clues.

**Comment by devLotto** [comment]
Yeah, the plugin should be improved to know the position of the object that it should mark.
I think the reason for it not being like that already is the coordinates not being at the objects, but through community effort we can fix that.

**Comment by SomeZer0** [comment]
@devLotto What would be the best way to help / what information is needed?
Would having clue IDs and object coords be required?

**Comment by devLotto** [comment]
Clue text + object coordinates (from developer tools plugin)

Clue scroll item ID is only needed for map clues
