### ISSUE TITLE
Idle notifier not working in ectofunctus

### ISSUE THREAD

**Issue by FelixAbrahamsson** [runelite/runelite#13144]
Idle notifier does not trigger after grinding bones or picking up slime

1. Grind bones in ectofuntus or fill buckets of slime
2. Tab out and wait until idle

**Expected behavior**
Idle notifier should go off but it doesnt.

**Environment**
 - OS: Ubuntu 18.04
 - RuneLite version: 1.6.38
 - Launcher version: 2.1.0

**Comment by Nightfirecat** [comment]
Added in #13177
