### ISSUE TITLE
Mind runes not showing in rune pouch

### ISSUE THREAD

**Issue by CodeLoggerzz** [runelite/runelite#13149]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Mind runes icons are not displaying on the rune pouch

**To Reproduce**
1.  Add mind runes to rune pouch

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13066036/106801606-4081ab00-6662-11eb-8ff7-91a77db935a2.png)
![image](https://user-images.githubusercontent.com/13066036/106801664-50998a80-6662-11eb-89c5-82de2ec7181d.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.38
 - Launcher version: 2.1.5

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in

**Comment by Nightfirecat** [comment]
Can you please upload your client logs? I'm seeing the mind rune icon appearing just fine on my end.

**Comment by CodeLoggerzz** [comment]
do you mean this file?

[client.log](https://github.com/runelite/runelite/files/5921306/client.log)

**Comment by Nightfirecat** [comment]
Nothing in that file seems to indicate any clear issues. If you're still seeing this issue after a client restart, can you try launching the client in safe mode? This will disable the GPU plugin and hub plugins for that run. Steps to do so can be found here: https://github.com/runelite/runelite/wiki/GPU-FAQ#how-can-i-disable-gpu-plugin-if-the-client-does-not-open

**Comment by CodeLoggerzz** [comment]
when launching in safe mode it resolves the issue

**Comment by Nightfirecat** [comment]
Your log shows you using a small list of hub plugins. Can you try turning them all/each off and restarting? I imagine one of them is causing this behavior, and the author of the one at fault should be able to fix this.

**Comment by CodeLoggerzz** [comment]
I deleted all the hub plugins and restarted runelite like normal and all this solved the problem

**Comment by Nightfirecat** [comment]
Well if you find out which one is the culprit, you can open an issue on its issue tracker for them to fix.
