### ISSUE TITLE
Runelite account settings reverted after the update. 

### ISSUE THREAD

**Issue by IronErro** [runelite/runelite#13150]
I imported my offline settings to my logged in Runelite account maybe a week ago. After this update I logged it and all of my settings have reverted back to what they were before the import. Any changes I've made are all gone back to what they were when I first imported. 

I expected that when I imported my settings into my runelite account that everything would be saved into the cloud as I continued to tweak my settings, but as far as I can tell, nothing saved at all and everything has reverted back to what it was right before I imported the settings. 

I'm not sure if there would be anything else I can add that would be helpful here.

**Comment by Alexsuperfly** [comment]
Something like this is better suited for the [discord](https://runelite.net/discord), join us in the support channel.
