### ISSUE TITLE
Clue Scrolls: New Isle of Souls Elite Coordinate Step

### ISSUE THREAD

**Issue by Demonslay335** [runelite/runelite#13159]
Today I got the new Elite coordinate clue that is on the Isle of Souls. The plugin correctly showed the location, but figured I would show where it is so a description can be added. Also, I encountered an Armadylian guard there, so that can be tagged as spawning Armadylian/Bandosian guards.

>8 degrees 30 minutes south
>10 degrees 48 minutes west

![2021-02-05_14-36-15](https://user-images.githubusercontent.com/5551512/107080591-21e0f880-67b7-11eb-882e-2d90600c7cf7.png)
![image](https://user-images.githubusercontent.com/5551512/107080667-391fe600-67b7-11eb-8e48-8aec0fc1a5f2.png)
![image](https://user-images.githubusercontent.com/5551512/107080785-5b196880-67b7-11eb-91a3-b5bc304131e4.png)

**Comment by melkypie** [comment]
The clue has already been added in #13152.

**Comment by Demonslay335** [comment]
Ah sorry. I tried searching Issues and never saw this clue mentioned. I should have also checked the PRs. 😅
