### ISSUE TITLE
Jagged text (DPI scaling issue?)

### ISSUE THREAD

**Issue by Leo288** [runelite/runelite#13155]
**Describe the bug**
In-game text appears jagged, as if a non-integer font size has been used, when not using the GPU plugin.  Official client appears normal.  Screenshots have been attached. 
Resolution: 1920x1080
Scaling (windows): 190%

**To Reproduce**
Unsure how to reproduce on other machines. Have not noticed it on my other laptop.

**Expected behavior**
Font should appear smooth as with the official client.

**Screenshots**

### RuneLite Login
![rl](https://user-images.githubusercontent.com/78256408/106928796-7cbd1600-670b-11eb-9653-d202429dd806.png)

### Official Login
![official](https://user-images.githubusercontent.com/78256408/106928812-80509d00-670b-11eb-83e2-cf2f5d8a488a.png)

### Runelite In-Game
![rl-ingame](https://user-images.githubusercontent.com/78256408/106928736-657e2880-670b-11eb-927d-0247e2387c9d.PNG)

### Official In-Game
![official-ingame](https://user-images.githubusercontent.com/78256408/106928824-86df1480-670b-11eb-9959-f040f44721ca.PNG)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.38
 - Launcher version: 2.1.6

**Additional context**

**Comment by Nightfirecat** [comment]
Is this fixed by [changing your DPI settings for RuneLite](https://github.com/runelite/runelite/wiki/Change-DPI-Scaling-%28Windows%29)?

**Comment by Nightfirecat** [comment]
Since this issue is lacking information and has not been updated in some time, I am closing it.
