### ISSUE TITLE
Bank tab named "clue" behaving oddly, other tabs unaffected

### ISSUE THREAD

**Issue by dpedu** [runelite/runelite#13162]
**Describe the bug**

I have a bank tag/tab named "clue" with many items tagged within it. Today, when I opened this particular tab, it no longer had any items displayed in it. 

If I attempt to add more items to this tab, they don't appear in it. If I export the tab, the copied string has a list of about 90 items. If I delete and recreate the tab, items added still don't appear within it.

If I look at items that SHOULD be in it, by right clicking and editing tags, they still have the "clue" tag. 

None of my other bank tabs/tags are behaving oddly.

If I search my bank for "clue", none of the items tagged "clue" appear. But I can search for other tags/tabs and the expect items are shown.

If I completely reset Runelite (by deleting/renaming ~/.runelite), the issue persists (after making a new tab named `clue`).

**To Reproduce**
1. Create a bank tag named `clue`
2. Drop items into the tab
3. Open the tab, see that no items appear!

**Expected behavior**

Bank tags should work properly even if named "clue".

**Screenshots**
N/a

**Environment (please complete the following information):**
 - OS: macOs and Ubuntu Linux
 - RuneLite version: 1.6.39
 - Launcher version: 2.1.2

**Additional context**
I have multiple computers with Runelite and this problem appeared on all of them within the last day or so. I don't sync my ~/.runelite directory or sign into Runelite.

**Comment by raiyni** [comment]
For a work around until next release, you can rename your tag to something else.

Fixed in https://github.com/runelite/runelite/commit/f13be14280d8fc7d6f12c05ea0f3807daabaddf4

**Comment by dpedu** [comment]
Oof, I just noticed that was the latest commit, too. Thanks!
