### ISSUE TITLE
Client Randomly freezes.

### ISSUE THREAD

**Issue by NoLimitsFunRs** [runelite/runelite#13169]
Hello people.

I recently got myself a used Lenovo e450 laptop.

Intel i5 4200m CPU
6bg ram

I'm able to pull 50 fps on the client but it would randomly freeze.

mostly when I change focus, but sometimes it also happens while I'm solely playing the game.

Any assistance would be appreciated, as I have tried a few OS but the issue persists.

I've tried the 32 and 64 bits version and the client has randomly frozen on both.

I attached a file of the Client Logs found on the runelite 
[freeze-log.txt](https://github.com/runelite/runelite/files/5938188/freeze-log.txt)

**Comment by Nightfirecat** [comment]
Please do not request support for non-RuneLite clients.

**Comment by NoLimitsFunRs** [comment]
This also happens with the Runelite client.
I tried OpenOSRS as an alternative.
Apparently, both clients share the same log folder, I will do deeper research and share the correct log then.

Many thanks for your time.
