### ISSUE TITLE
Bank Tag Tab issue with Name "clue"

### ISSUE THREAD

**Issue by ZGorlock** [runelite/runelite#13172]
Items do not show up in a bank tag tab named "clue", it used to work fine. All my other tabs work as expected, and I created a tab named "clues" and put some items in it, also worked fine.

When searching my bank with "tag:clu" everything showed up, but "tag:clue" returned nothing. Also creating a tag tab wit the name "clu" showed everything with the tag. Checking the tags on the items, it is indeed "clue" and not "clu".

**Comment by raiyni** [comment]
duplicate of https://github.com/runelite/runelite/issues/13162

For now, rename your tag to something else
