### ISSUE TITLE
POH Tip Jar Notifier/Data Logger

### ISSUE THREAD

**Issue by ZoltanPepper** [runelite/runelite#13179]
I have started hosting my house for players to use all the things used in a max house, we know how this works. Some players use the tip jar and donate me GP for my time I guess. I've noticed it's hard to keep track of which user and how much, mainly to say thankyou and to notice the repeat tippers.

**Describe the solution you'd like**
It would be brilliant if an overlay could be made to keep hold of the user and the amount, for instance the last 5 users that tipped on screen so If I have gone AFK I can see straight away who tipped and how much.

**Describe alternatives you've considered**
Another idea would be to allow the text that appears in the chatbox "USER has tipped X AMOUNT" to be a much brighter colour as at the moment this blends in with other ingame text.

**Additional context**
![908bab9fba3d94c197d75a345e8945f6](https://user-images.githubusercontent.com/78757822/107269838-135a4180-6a42-11eb-96c3-a3d13c031df7.png)
Just a clip of a donation so you can see the text for context.

-Zoltan

**Comment by ZoltanPepper** [comment]
> You should be able to use the [Chat Notifications plugin](https://github.com/runelite/runelite/wiki/Chat-Notifications) to get notifications for this already.

Thats a good idea, I didn't think of that!

**Comment by ZoltanPepper** [comment]
> You should be able to use the [Chat Notifications plugin](https://github.com/runelite/runelite/wiki/Chat-Notifications) to get notifications for this already.

Hi @Nightfirecat for some reason that doesn't work :/

**Comment by Nightfirecat** [comment]
What configuration settings were you using?

**Comment by ZoltanPepper** [comment]
> What configuration settings were you using?

Please see images attached.
![chat setup](https://user-images.githubusercontent.com/78757822/107344944-f57cf300-6aba-11eb-9d82-5aa420385e72.png)
![example 2](https://user-images.githubusercontent.com/78757822/107344949-f746b680-6aba-11eb-8369-6a188de10259.png)

I imagine will only give a pop up notification when alt tabbed?

**Comment by Nightfirecat** [comment]
Turn on "Send notifications when focused" in your RuneLite settings

**Comment by ZoltanPepper** [comment]
> Turn on "Send notifications when focused" in your RuneLite settings

Great, but currently there is no way to highlight that message? change the colour etc only a windows notification?

**Comment by Nightfirecat** [comment]
It already highlights the matched text. You could expand that to `has left you a tip:` to highlight more of the message. The highlight color can also be changed in Chat Color config

**Comment by Nightfirecat** [comment]
I'm fairly certain this is already covered via a combination of settings in `Chat Notifier`, `RuneLite`, and `Chat Colors`. As such, I'm closing this request.
