### ISSUE TITLE
Runelite client randomly freezing

### ISSUE THREAD

**Issue by NoLimitsFunRs** [runelite/runelite#13182]
Hello team.

I recently bought a Lenovo e540 laptop.
intel i5 4200m
6gb ram ddr3

Can you have a look at the log and point me into the right direction as to what I can do to stop the client from randomly  freezing? I'm able to pull 50fps but it would randomly freeze.
[client.log](https://github.com/runelite/runelite/files/5948251/client.log)
[launcher.log](https://github.com/runelite/runelite/files/5948252/launcher.log)

Many thanks.

Peace & prosperity,

Hugo.

**Comment by Mrnice98** [comment]
you can get more support in the RL discord support channel, but from that log is seems like your having some internet / dns issues

**Comment by NoLimitsFunRs** [comment]
Thanks for your time. I will reach out on the disc.

**Comment by Nightfirecat** [comment]
Like MrNice said, this is less of a bug report and more of a general support question. You can definitely find help there so I echo his suggestion.
