### ISSUE TITLE
Pharaoh's sceptre Left-click teleport.

### ISSUE THREAD

**Issue by humblemeal** [runelite/runelite#13187]
Since the change in October 2020 of Pharaoh's sceptre left-click option being switched from teleport to wield, the suggestion is to add an alternativ on Menu Entry Swapper on the Pharaoh's sceptre being able to left-click teleport this item.

**Comment by Broooklyn** [comment]
This is an option in ‘Menu swapper extended’ on the plugin hub. It allows you to pick the left click teleport location.

**Comment by humblemeal** [comment]
ty beast @Broooklyn
