### ISSUE TITLE
Show Jewellery charges as overlay

### ISSUE THREAD

**Issue by Lalonde33** [runelite/runelite#1318]
Display bneck/ ring of dueling somewhere on screen as overlay. Currently players have to go to their equipment tab to look at current charges. Which is not ideal for Runecrafting. Also incorporating some sort of flash or notification noting that bneck has broke would be great. Thanks

**Comment by RandaliciousRS** [comment]
any update on this @deathbeam

**Comment by deathbeam** [comment]
Not really. Should be very simple to make, only problem is that we have jewellery split between multiple plugins and so implementing infoboxes for all jewellery we already show as overlay can introduce some code duplicity what is slightly annoying.

**Comment by RandaliciousRS** [comment]
any easy way of implementing like a toggle or something to try and avoid the duplicity? would love this feature

**Comment by mooseweener** [comment]
FYI from the future! Item Charges plugin built in, show infoboxes.
