### ISSUE TITLE
Grammatical error in the Farming Tracker notification

### ISSUE THREAD

**Issue by Technifocal** [runelite/runelite#13184]
**Describe the bug**
I received a notification that makes no grammatical sense, `Your Compost BinArdougne.`

**To Reproduce**
I am unsure on this, I got the notification randomly while in Edgware.

**Expected behavior**
Produce a grammatically correct notification such as `Your compost bin in Ardougne is empty.`, for example.

**Screenshots**
While in Edgware:
![image](https://user-images.githubusercontent.com/20205745/107313507-8e474a80-6a8a-11eb-9354-3394392da3ac.png)
![image](https://user-images.githubusercontent.com/20205745/107313513-91423b00-6a8a-11eb-8f10-32209fe34fc3.png)

After visiting the patch in Ardougne:
![image](https://user-images.githubusercontent.com/20205745/107313573-bb93f880-6a8a-11eb-87d1-2407d1459095.png)
![image](https://user-images.githubusercontent.com/20205745/107313579-be8ee900-6a8a-11eb-8cbc-b038cfee756f.png)
![image](https://user-images.githubusercontent.com/20205745/107313713-fe55d080-6a8a-11eb-8ca3-7cd89bb31cb5.png)

**Environment (please complete the following information):**
 - OS: N/A
 - RuneLite version: `1.6.40-SNAPSHOT`
 - Launcher version: Unknown

**Additional context**
I believe the code responsible for this is located here:

https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java#L576-L603

I think adding a check to make sure the `prediction.getCropState()` != `EMPTY` should fix this, as I don't believe a notification is needed for an `EMPTY` state at all.

**Comment by Adam-** [comment]
It may also be good to move this notification logic to its own method which you can then test. cc @loldudester

**Comment by NJohnsonJ** [comment]
This commit should resolve this issue:  https://github.com/runelite/runelite/commit/525c64b8dfa239b9bba5e8e7e12ee8684ac130ef

A fall through case was added that prevents notifications from being sent when the compost bin is empty. See https://github.com/runelite/runelite/blob/1684eccd006560f984474ffea1248dd8666df78c/runelite-client/src/main/java/net/runelite/client/plugins/timetracking/farming/FarmingTracker.java#L592

**Comment by abextm** [comment]
Fixed by #13189
