### ISSUE TITLE
notify until resolved

### ISSUE THREAD

**Issue by pettrs** [runelite/runelite#13193]
**Is your feature request related to a problem? Please describe.**
if you have alot of notification requirements, keeping track of them all can be confconfusing as well as get you killed at times.

**Describe the solution you'd like**
Have the option to keep warning if the issue hasn't been resolved. for example if your health goes below a set point, it will keep notifying you not until it's cancelled, but until your health exceeds the set value.

**Describe alternatives you've considered**

**Additional context**
should have a ui that tells you what it is that needs to be resolved, as well as a button to ignore (for a certain amount of time, or until it's been resolved. (for example if you've teleported out and don't need to eat)

for example;

1. Your hitpoints is low
2. Your *potion recently used* has expired
3. Your stamina is low
4. Your special attack is now avalible

**Comment by Nightfirecat** [comment]
We send notifications through your OS to be displayed. You can change your OS notification settings to behave this way.
