### ISSUE TITLE
Menu selects wrong tile when opened in fixed mode

### ISSUE THREAD

**Issue by Brandieee** [runelite/runelite#13199]
**Describe the bug**
When shift-right clicking near a tile border the context menu for the intended tile is opened however the actual tile might be the adjacent one. See attached .gif

**To Reproduce**
1. Shift-right click near a tile border
2. Select mark/unmark
3. Observe adjacent tile switching its marked state

**Expected behavior**
Either the original intended marking/unmarking of the tile or the context menu reflecting the actual tile the operation will be performed on.

**Screenshots**
![](https://i.ibb.co/tMDNDTy/ground-Markers.gif)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.6.39
 - Launcher version: 2.1.0

**Comment by Nightfirecat** [comment]
This is more noticeable when attempting to mark/unmark far-away tiles

**Comment by bugfixer-hub** [comment]
Seems like there is an inconsistency with the client's last selected tile (especially near the edges), which is being called twice when menu is added and when option is selected. 

Keeping a reference to the tile used in the onMenuEntryAdded and re-using it when an option is selected would probably address this.

**Comment by Adam-** [comment]
This is a Jagex bug in their tile collision checks. I've pushed a workaround for it internally so it should no longer happen on master. I also gave it to one of their devs since it does happen on vanilla.
