### ISSUE TITLE
Cannon spot marker under Mourner HQ is now invalid after song of the elves quest release

### ISSUE THREAD

**Issue by buttonpoker** [runelite/runelite#13195]
After the release of song of the elves, the cannon placement marker that was located underground in the mourner HQ in West Ardougene is now invalid due to being unable to cannon in this spot anymore. If you were to place a cannon anywhere underground within the confines of this building the cannon will not fire therefore the cannon marker spot placed by runelite should be removed. [](url)
![mourner_Hq](https://user-images.githubusercontent.com/36622019/107600377-77167300-6bd8-11eb-9f97-42829d07a184.PNG)

**Comment by Adam-** [comment]
What about before doing song of the elves?

**Comment by buttonpoker** [comment]
> What about before doing song of the elves?

I have not completed the quest song of the elves so I can confirm that in this scenario it's valid. I have seen others within youtube comments and posts stating the same issue of not being able to cannon anymore after the quests release. It probably would be best to have someone who has completed the quest to attempt to cannon here to double check if that would make a difference.

**Comment by Mrnice98** [comment]
![Capture](https://user-images.githubusercontent.com/49848962/107601038-8656ea00-6bf3-11eb-9105-d4e4bb092966.PNG)
can confirm that after the quest it lets you at least place the cannon however the cannon will not fire at the npcs

**Comment by buttonpoker** [comment]
> ![Capture](https://user-images.githubusercontent.com/49848962/107601038-8656ea00-6bf3-11eb-9105-d4e4bb092966.PNG)
> can confirm that after the quest it lets you at least place the cannon however the cannon will not fire at the npcs

Thanks for confirming!

**Comment by buttonpoker** [comment]
#13196
