### ISSUE TITLE
News Feed Plugin: Favicon Overlay to Indicate News Sources

### ISSUE THREAD

**Issue by F-Lambda** [runelite/runelite#13218]
In the news feed plugin, it's not always clear which posts are news posts and which are just tweets. So, it'd be great if each entry had the favicon of the site that the news source is from. For example, tweets would have a twitter icon, news posts would have the RuneScape home page icon, and Runelite updates would have the Runelite icon.

**Comment by Nightfirecat** [comment]
We've removed the news feed plugin as Twitter's API is no longer freely accessible, and OSRS/RuneLite posts are more easily accessed directly via their websites.
