### ISSUE TITLE
Master clue Hot and Cold Isle of Soul location missing from solver

### ISSUE THREAD

**Issue by Bensemus** [runelite/runelite#13223]
I got a master clue with a hot and cold step. RL kept getting stuck and giving up. I followed the directions manually and found the hottest place was the Wrath alter. The only location farther southwest was the Isle of Soul but RL didn't show a possible clue location there. The Wiki has one and when I went there the device finally became hot. RL just seems to be missing this location.

OS: Windows 7
RL: 1.6.38
Launcher: 2.1.0

[client.log](https://github.com/runelite/runelite/files/5986080/client.log)
[client_2021-02-14.0.log](https://github.com/runelite/runelite/files/5986082/client_2021-02-14.0.log)

![2021-02-15_20-26-30](https://user-images.githubusercontent.com/31749689/108018666-37cb9600-6fcd-11eb-8166-e02575ed61b2.png)
![2021-02-15_20-26-38](https://user-images.githubusercontent.com/31749689/108018671-3b5f1d00-6fcd-11eb-866f-aa80177694ea.png)
![2021-02-15_20-29-43](https://user-images.githubusercontent.com/31749689/108018673-3bf7b380-6fcd-11eb-9947-b7156215deb2.png)

**Comment by Nightfirecat** [comment]
This has already been fixed in 0b993b635c079075d4bdc287842ee336d77fa660 and will be available in our next release.
