### ISSUE TITLE
Laggy settings

### ISSUE THREAD

**Issue by adamizir7** [runelite/runelite#13229]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**when i hover over settings or try to navigate the settings on runelite it gets laggy and keeps opening new instances, making it impossible to get anything done.
![bug](https://user-images.githubusercontent.com/79238313/108299362-e99ccb00-7163-11eb-9529-18f2ee2cf279.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment]
Follow the steps on this wiki page: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

In the future, you can join our Discord's `#support` channel for support with setup issues that aren't related to client bugs.
