### ISSUE TITLE
Coal bag indicator

### ISSUE THREAD

**Issue by tinfoiljoe** [runelite/runelite#13221]
**Is your feature request related to a problem? Please describe.**
i have crappy internet so i dont know if i click and my coal bag gets filled

**Describe the solution you'd like**
just like the rune pouch indicator if its filled id like to see if the coal bag is filled

**Describe alternatives you've considered**
if it cant be on the coal bag a little indicator on the top showing how much coal in the coal bag would be helpful

**Comment by WolffTech** [comment]
This was my attempt at adding a feature like this. This is my first time using Java and I basically just copied Adams essence pouch plugin. If anyone has any suggestions on making this better or wants to improve upon it feel free!
https://github.com/WolffTech/coal-bag-addon

**Comment by Nightfirecat** [comment]
https://runelite.net/plugin-hub/show/coal-bag seems to accomplish this.
