### ISSUE TITLE
Self/own messages triggering chat notifications 

### ISSUE THREAD

**Issue by ausnlpe** [runelite/runelite#13238]
**Describe the bug**
When you type a message containing phrases you have highlighted to send notifications
>Chat notifications on
>Highlight words
>Notify on highlight
>Allow desktop notifications (not necessary but annoying)

you will receive a desktop notification every time your chat (including autochat!) says the phrase INCLUDING if your username has the phrase/word in it for example you want to know if someone says "whip" if your name is "whip" and/or u say "whip 5m" (including on autochat - more likely to happen in this scenario) u will receive notifications you definitely do not want.

**To Reproduce**
I believe this is example above sorry

**Expected behavior**
No notifications for own messages, alternatively a button to allow self-messages to be excluded from notifications.

**Environment (please complete the following information):**
 - OS: windows 10 home unactivated
 - RuneLite version: 17.0
 - Launcher version: 2.1.6

**Comment by bluelightzero** [comment]
Example:

![image](https://user-images.githubusercontent.com/4492982/108544879-fd207100-72de-11eb-82aa-335bc68b8f0a.png)

Red text is the notification.

**Comment by MarbleTurtle** [comment]
While the image doesn't indicate it both public and clan messages will trigger the notification
