### ISSUE TITLE
Screenshots do not take automatically when config is open

### ISSUE THREAD

**Issue by arisingangel** [runelite/runelite#13243]
I have found that if I open the screenshot configuration menu, this stops screenshots from being taken automatically until I click 'back'. This may occur even if no settings are changed. This was unexpected and lost a lot of screenshots desired. This is particularly problematic if I minimize the configuration tab without going back, as I would have no reason to notice the function isn't working.

**Comment by Nightfirecat** [comment]
Can you please upload your `client.log` file from some day where this occurred? Directions to find it are at the top of this page: https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by arisingangel** [comment]
[client_2021-02-17.0.log](https://github.com/runelite/runelite/files/6016895/client_2021-02-17.0.log)
[client_2021-02-18.0.log](https://github.com/runelite/runelite/files/6016896/client_2021-02-18.0.log)
I know I got 92Att and 95HP on those two days, although I can't recall at which time exactly.

**Comment by Nightfirecat** [comment]
Where did you get those levels? It's possible to miss level-up screenshots--especially for combat levels--when the dialog is auto-closed, such as when you're in combat.
