### ISSUE TITLE
Birdhouse notification setting not preserved between sessions

### ISSUE THREAD

**Issue by xSlysoft** [runelite/runelite#13262]
**Describe the bug**
I'm not sure if this is intentional or not, but when I click the new bell icon to enable notifications in the time tracker, they are not saved and everything is reverted to the default (muted notifications) when I restart the client. If this is intentional then I think it would make more sense to save the settings.

**To Reproduce**
Turn on notifications for a farming patch / birdhouse and restart the client.

**Expected behavior**
When restarting the client, patches which I set to notify should be automatically enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/42144975/108943700-5cf08200-7627-11eb-8062-77f9f460a259.png)

**Environment (please complete the following information):**
 - OS: Winblows 10
 - RuneLite version: 1.7.0
 - Launcher version: 2.1.3

**Comment by Nightfirecat** [comment]
This appears to be specific to birdhouses. Other patches are working fine for me.

**Comment by Hannah-GBS** [comment]
This is because the birdhouse notifications are handled by the `Bird house notification` option in the Time Tracking plugin config. As such, the bell icons on their tracker do nothing, and were included in the time-tracking update by mistake.

**Comment by xSlysoft** [comment]
That makes sense. Would it not be a good idea to depricate the birdhouse notification option and just move it to the bell notifications? I suppose you might end up getting spammed with notifications at that point though.

**Comment by Nightfirecat** [comment]
Generally if someone wants notifications for birdhouse completion, they want only one notification for all of them, rather than one per spot. (I don't think anyone skips certain birdhouses) The UI currently doesn't allow for that in a straightforward way, but it would be nice to find some way to incorporate birdhouse notification toggles in the UI rather than config.

**Comment by xSlysoft** [comment]
Yeah since birdhouses have their own dedicated tab it could just have a single bell icon that handles the whole set. Basically just moving the location of the existing option toggle.
