### ISSUE TITLE
Entity Hider plugin hide attacker while attacker option is off

### ISSUE THREAD

**Issue by qtv1** [runelite/runelite#13269]
please take a look .
thank you for your help 
Entity Hider plugin hide attacker while attacker option is off

**Comment by Nightfirecat** [comment]
This is fixed internally as of client patch `1053521533.55`. Hence, you'll find this is fixed in our next release.

**Comment by qtv1** [comment]
Hello . thank you for your reply. Is it possible to use the fixed version before next week update?
Thank You

**Comment by Nightfirecat** [comment]
It would only be possible by building the client yourself, see: https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA

Unless you are fairly technically-minded, I recommend waiting for our next update instead.
