### ISSUE TITLE
The indicator numbers for the Status Bars plugin no longer has a drop shadow

### ISSUE THREAD

**Issue by Jademalo** [runelite/runelite#13271]
**Describe the bug**
The shadow behind the numbers on the status bars plugin has disappeared. I believe it was a result of the improvements made in this release - https://runelite.net/blog/show/2020-11-11-1.6.31-Release

**To Reproduce**
1. Enable the Status Bars plugin
2. Look at the text

**Expected behavior**
The numbers should have a single pixel drop shadow for easier readability

**Screenshots**
![image](https://user-images.githubusercontent.com/386846/109131861-1b58f780-774b-11eb-8450-d6c8723f376a.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.1
 - Launcher version: 1.6.0
 
**Additional context**
I believe the relevant commit that changed it is this one - https://github.com/runelite/runelite/commit/1165780f427e1d9f86f2d658b050bf04a7ae237e

**Comment by Adam-** [comment]
It looks like this was using text component before, but was changed in https://github.com/runelite/runelite/commit/1165780f427e1d9f86f2d658b050bf04a7ae237e to not. Why was this changed? cc @Malfuryent @Nightfirecat

**Comment by Nightfirecat** [comment]
I don't see a good reason for it being changed, it should be changed back.
