### ISSUE TITLE
Steam Account Log in for OSRS?

### ISSUE THREAD

**Issue by mcmuffonman** [runelite/runelite#13278]
Hi Everyone, 
I haven't played OSRS for sometime and just wanted a fresh start, so as of them putting OSRS on steam directly. I just have been logging in through my steam account to play OSRS. And today I made runelite the primary client for when I launch the game through steam but every time I do that it won't just log in through my steam it asks me for an email and password. If I try using my steam email and password it doesn't recognize it. I was wondering if there is a way to connect my new steam account to a new runescape one under the same email. Or what the best course of action is for logging into runelite as I am very eager to using runelite. 

Thank You

**Comment by Adam-** [comment]
https://support.runescape.com/hc/en-gb/articles/360013472137-Add-a-login-email-to-a-Steam-created-account
