### ISSUE TITLE
Loot tracker displays items as Members objects

### ISSUE THREAD

**Issue by ohganot** [runelite/runelite#13282]
**Describe the bug**
Loot tracker displays all members items as members objects and doesn't stack all of them properly.

**To Reproduce**
1. Open runelite client
2. Log in an F2P account
3. Log out
4. Log in an P2P account
5. Now P2P account has loot tracker items displayed as members objects

**Expected behavior**
Runelite still recognizes members objects and displays them correctly both on F2P and P2P worlds. 
Or atleast after logging into P2P account, makes sure items have names instead of members objects.

**Screenshots**
![](https://i.imgur.com/3W7pVXE.png)

**Environment (please complete the following information):**
 - OS: Windows 7
 - RuneLite version: 1.7.1
 - Launcher version: 1.5.2

**Comment by Adam-** [comment]
fixed in fd2c4a40af8102890c742dd014e03bac5e608e77
