### ISSUE TITLE
ChatFX Plugin

### ISSUE THREAD

**Issue by MoniMars** [runelite/runelite#13280]
Hello, I've come to make a quick proposal for a QoL plugin to make text effects more accessible

![chatFX_concept](https://user-images.githubusercontent.com/69696657/109368855-86e4b700-7868-11eb-9914-5a27c6e5d756.png)

I just think it would be really neat to use effects without all the hassle they normally pose!!!

**Comment by Hydrox6** [comment]
Since those effects are pieces of text added to the start of messages, this would count as autotyping, which is against the rules. 

Love the mockup though, very well done.
