### ISSUE TITLE
World Map/Quest Helper/Optimal Quest Guide 0 FPS Spike since 03/03/21 RS Update

### ISSUE THREAD

**Issue by FeniksX** [runelite/runelite#13300]
Game runs at 0 fps. Current location Edgeville Dungeon, tested with GPU and FPS Limiter on and off.

EDIT: Both Quest Helper and Optimal Quest Guide plugins causing the slowdown in FPS. Returned to 50fps with both disabled.

**Comment by Hydrox6** [comment]
Disable Quest Helper and Optimal Quest Guide hub plugins if you have them.

**Comment by FeniksX** [comment]
> Disable Quest Helper and Optimal Quest Guide hub plugins if you have them.

This fixed the issue immediately.

**Comment by FeniksX** [comment]
Back-end Quest change relating to the "IsComplete" flag are the cause. This is also affecting the World Map core plugin.

**Comment by abextm** [comment]
fixed for core plugins by 6526fd9d7c8155c88c8fcf0eef6406de643b81c8
