### ISSUE TITLE
One small favour Quest helper spelling mistake 

### ISSUE THREAD

**Issue by KennyXOXX** [runelite/runelite#13301]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Spelling mistake during one small favour see attached gyazo. 

**To Reproduce**

**Expected behavior**

spelling mistake or mistype "on in barbarian village" should be "one"

**Screenshots**
https://i.gyazo.com/7073fab4e366fd848a1f0b6b5f044646.png
**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
