### ISSUE TITLE
Suggestion: Selective Roofs

### ISSUE THREAD

**Issue by KakronPrime** [runelite/runelite#13314]
**Is your feature request related to a problem? Please describe.**
A recent Reddit post made me consider how we are missing a lot by having roof’s disabled all the time. There’s a lot to the world we don’t get to see. Zanaris has fairy houses above ground level I never knew about and priffdinis is beautiful.

**Describe the solution you'd like**
I’m told that RS3 has a “selective roof mode” that removes roofs that obscure player view but leaves roofs on in the distance/surrounding area. Is this implementable in RuneLite?

**Additional context**
An example of selective roofs on rs3:
![](https://runescape.wiki/images/b/be/NXT_Remove_roofs_On.png?df821)

**Comment by goudekid** [comment]
I was also thinking about this, and a perhaps plausible way to implement would be to show rooves in the distance when using the GPU plugin and hide them when they enter a certain distance (maybe where the limit of default vision normally is?)

**Comment by Hydrox6** [comment]
This was added with a6e3d4ca20de7d095020942f774a847be6f4a2b4
