### ISSUE TITLE
Efficient Clue scrolls suggestion

### ISSUE THREAD

**Issue by ImPinu** [runelite/runelite#13336]
With the clue scroll helper, maybe tell the user which teleport is most efficient. I do alot of medium clues and alot of the clues are like "fairy ring AKQ" when its faster to use a piscarillius teleport. Or make us able to make our own notes on each step.

**Comment by owlfredo** [comment]
Not sure if bumping is a thing in GH but I'm interested in this issue/improvement.

**Comment by Adam-** [comment]
added in d87f3f6319f61d6bc43a28384d1175be78f689db
