### ISSUE TITLE
Shooting Stars Plugin [Feature Request]

### ISSUE THREAD

**Issue by iDre4M** [runelite/runelite#13346]
**Is your feature request related to a problem? Please describe.**
Shooting stars D&D was added, RuneLite has no plugin for this activity.

**Describe the solution you'd like**
It would be nice to have plugin which would remember world, location and possible time of stars landing and maybe mark possible locations on the map. Advanced level would be to share information between everyone and if someone visited one site and star wasn't there to remove it from the map, have list of all star land times etc.

**Describe alternatives you've considered**
Worst case scenario, just remember in which world, when and where star should land and list it on the sidebar of RuneLite.

**Comment by Nightfirecat** [comment]
A number of hub plugins exist which fulfill this now.

**Comment by nucleon** [comment]
crowdsourced: https://runelite.net/plugin-hub/show/shooting-stars
local: https://runelite.net/plugin-hub/show/shooting-stars-tracking
