### ISSUE TITLE
RuneLite is unable to connect to a required server while downloading the bootstrap. Please check your internet connection

### ISSUE THREAD

**Issue by agkilla321** [runelite/runelite#13345]
Hello, Im unable to launch Runelite successfully. 

When launching, the loading screen opens and shows " Downloading Bootstrap"

It gets stuck for a few seconds and then says : " RuneLite is unable to connect to a required server while downloading the bootstrap. Please check your internet connection" 

Using a PC , have uninstalled and reinstalled runelite, am only using windows security.

[client.log](https://github.com/runelite/runelite/files/6157719/client.log)

**Comment by jaydenkieran** [comment]
If you're Canadian, try using a VPN to launch RuneLite. There's some issues going on currently.

**Comment by agkilla321** [comment]
Okay ! Il try that. 

Thank you !
