### ISSUE TITLE
GPU Plugin crashes my Mac

### ISSUE THREAD

**Issue by GeorgeKosrs** [runelite/runelite#13354]
I originally thought that compute shaders crashes my runelite but after extensive testing I figured out its happens if the gpu plugin is on regardless. Once it's off it does not crash.

It does not crash straight away when the gpu plugin is on but randomly after a few hours of playtime.

I have spoken to a few members on the discord that looked at my logs. They told me I can't do anything because its a driver issue and Apple need to fix it. They suggested I should throw away my Mac and buy a PC. 

Someone else on the discord told me its not a driver issue but my graphics card is overheating so I don't know what to believe.....

I wasn't going to post this up on github but then I saw @LlemonDuck requesting for mac graphic issues to be posted 

[jvm_crash_pid_56604.log](https://github.com/runelite/runelite/files/6174572/jvm_crash_pid_56604.log)
[jvm_crash_pid_71781.log](https://github.com/runelite/runelite/files/6174573/jvm_crash_pid_71781.log)
[jvm_crash_pid_99320.log](https://github.com/runelite/runelite/files/6174574/jvm_crash_pid_99320.log)
[jvm_crash_pid_7039.log](https://github.com/runelite/runelite/files/6174576/jvm_crash_pid_7039.log)
[jvm_crash_pid_30251.log](https://github.com/runelite/runelite/files/6174577/jvm_crash_pid_30251.log)

**Comment by GeorgeKosrs** [comment]
Maybe llemonduckie is right. I just had 2 successful 6 hour sessions with the GPU plugin on without it crashing. It may be a compute shaders problem.

I will keep testing and report back next week. Hopefully he can fix this issue since he coded compute shaders into runelite for Mac.

**Comment by GeorgeKosrs** [comment]
Maybe llemonduckie is right. I just had 2 successful 6 hour sessions with the GPU plugin on without it crashing. It may be a compute shaders problem.

I will keep testing and report back next week. Hopefully he can fix this issue since he coded compute shaders into runelite for Mac. 

I pray its not a driver issue as that will never be fixed.

@LlemonDuck said he could possibly create a workaround for the m1 but what about my system?

These are my specs

<img width="239" alt="Screenshot 2021-03-20 at 11 13 32 pm" src="https://user-images.githubusercontent.com/80487500/111888234-9a4ff180-89d2-11eb-8069-fca2395dd53c.png">

**Comment by LlemonDuck** [comment]
If you're capable of modifying and building RuneLite yourself, you can try the fix here and let me know how it goes:

> My guess is that if all 3 compute calls are skipped, the clEnqueueReleaseGLObjects should be given {0, null} as the list of events to wait on, rather than {0, []}

You'll need to change https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/gpu/OpenCLManager.java line 514 to check whether numComputeEvents is 0, and pass null instead of the computeEvents array. 

If you aren't able to modify it yourself, someone else who stumbles upon this will have to try it. I don't have a machine to test this on.

**Comment by GeorgeKosrs** [comment]
I don't know how to do that but thank you. Hopefully someone can sort out a test build. Anyone who wants to to use my system via teamviewer let me know.

I assure you I am not faking these crashes.

**Comment by GeorgeKosrs** [comment]
@Bram91 has helped me to do the above. I will be testing it and will report back on any findings.

<img width="1278" alt="Screenshot 2021-03-21 at 12 02 28 pm" src="https://user-images.githubusercontent.com/80487500/111904601-a8882700-8a3f-11eb-9705-964c5afa0599.png">

**Comment by GeorgeKosrs** [comment]
Thank you @LlemonDuck @Bram91 

I have tested the code and I have had no crashes for 12 hours. I use to always get them during the 6 hour limit!!!

Can you please implement this in the mac version? According to a few people that I've spoken to it shouldn't effect anyone in a negative way.

I can't believe I can finally play with extended draw distance !!! :D

**Comment by LlemonDuck** [comment]
If you're able, can you give it a few more days of testing to make sure it's solved. Let us know in three or four days?

Happy to add this if it's still working then.

**Comment by Adam-** [comment]
> 
> 
> If you're able, can you give it a few more days of testing to make sure it's solved. Let us know in three or four days?
> 
> Happy to add this if it's still working then.

Looks like the existing code is wrong according to https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueReleaseGLObjects.html

The relevant section:
```
event_wait_list , num_events_in_wait_list

    These parameters specify events that need to complete before this particular command can be executed. If event_wait_list is NULL, then this particular command does not wait on any event to complete. If event_wait_list is NULL, num_events_in_wait_list must be 0. If event_wait_list is not NULL, the list of events pointed to by event_wait_list must be valid and num_events_in_wait_list must be greater than 0. The events specified in event_wait_list act as synchronization points.
```

So we should probably change this regardless.

**Comment by Adam-** [comment]
fixed in 9d048fce4138d128d0dd9f4e18ba1986802f8088

**Comment by GeorgeKosrs** [comment]
@LlemonDuck was right again :(

[jvm_crash_pid_7992.log](https://github.com/runelite/runelite/files/6201094/jvm_crash_pid_7992.log)

**Comment by GeorgeKosrs** [comment]
@LlemonDuck was right again :( can you please make a workaround?

[jvm_crash_pid_7992.log](https://github.com/runelite/runelite/files/6208644/jvm_crash_pid_7992.log)

I have posted here as well maybe they know whats wrong

https://github.com/AdoptOpenJDK/openjdk-support/issues/284

**Comment by GeorgeKosrs** [comment]
and here https://github.com/gpu/JOCL/issues/40

**Comment by LlemonDuck** [comment]
As we've mentioned in other places, this is an AMD driver issue. Please don't bother other library maintainers, they are not responsible for this nor capable of fixing it, same as us.

I'm going to show you here in your log files that this is AMD:
![image](https://user-images.githubusercontent.com/1868974/112646675-1e183c80-8e1e-11eb-97ee-68d02133caa7.png)

We're stuck using outdated technology to make a client for a game that isn't ours, on platforms (macOS) that aren't friendly to us. We can't do much better than this.

All the log files you've uploaded have been at 10+ hours of uptime. Perhaps try restarting your client more often.

If you really want to see this fixed in code, you need to contact AMD or Apple. What can be done in open-source is done. Again, please don't bother third-party library maintainers with issues that aren't theirs to fix.

**Comment by GeorgeKosrs** [comment]
I am currently running runelite in debug mode to see if it spits out anything useful that can diagnose the issue. @aHooder has provided me with a potential fix also which I am testing.
