### ISSUE TITLE
significant stuttering when time tracking plugin is displayed

### ISSUE THREAD

**Issue by 00-Evan** [runelite/runelite#13364]
**Describe the bug**
Runelite hitches for about a quarter to a half second at regular intervals when the timer plugin is displayed. This happens every 10 or so seconds passively. If you are harvesting a patch then the stuttering occurs very frequently if any panel except the overview is selected. The more frequent stutter might be happening whenever a patch's 'life' is consumed, so harvesting things like herbs better reproduces the issue.

**To Reproduce**
1. Log into the game with the time tracker plugin displayed
2. keep rotating the camera with the arrow keys, to make the stutter more noticeable, observe the intermittent stuttering
3. harvest a patch with the appropriate category panel open and rotate the camera, observe the frequent stuttering

**Expected behavior**
Displaying the timer plugin UI should not result in stuttering

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.2.2 (I believe this issue is recent, but I'm not sure how recent)
 - Launcher version: 2.0.2

**Additional context**
Issue was present with GPU mode enabled or disabled, and with the client fullscreened or with it in a small window.

If there is any issue reproducing this then I'll happily share my config or client logs.

**Comment by Hydrox6** [comment]
Given that nothing has happened on this issue for months, and no one has reported anything similar, closing as stale
