### ISSUE TITLE
Whitelist H.A.M. storeroom guards in menu swapper plugin.

### ISSUE THREAD

**Issue by EvanWalden** [runelite/runelite#1337]
The menu swapper plugin was recently changed from working for all npcs to just H.A.M members. Specifically, it looks for the substring "H.A.M." in the npc's name. However, the H.A.M. storeroom guards are just called "Guard", so their options aren't swapped.

I don't think there are any other npcs called "Guard" that can both be talked to and pick pocketed, so it should be easy enough.

**Comment by ShaunDreclin** [comment]
This is what I was afraid of when that change was made :p I still say it woulda been better to just blacklist the pollnivnean npcs

**Comment by EvanWalden** [comment]
I've decided I don't care.

**Comment by ShaunDreclin** [comment]
I still do, could you reopen the issue?
