### ISSUE TITLE
Bank Tag Layout - Info Stats & Scrollbar

### ISSUE THREAD

**Issue by BabsCox** [runelite/runelite#13378]
The Bank Tag Layout is pulling in Info Stats and Mousetooltips that are turned off. See example: "Law Rune" which if I move to the traditional tab (not the bank tag) it does not include this tooltip/item info. 

Additionally, the plugin was updated to include the scrollbar regardless of the # of items in the layout. Can this be adjusted to only be included if the number of items exceeds the available space, therefore requiring a scrollbar? 

![image](https://user-images.githubusercontent.com/81268914/112229756-f6e92180-8c09-11eb-821e-6d5e8d36ebfb.png)

**Comment by Nightfirecat** [comment]
We do not handle bugs for hub plugins. Please open this issue on the appropriate plugin's repository.
