### ISSUE TITLE
Allow partial word search in Grand Exchange panel

### ISSUE THREAD

**Issue by kempyboi123** [runelite/runelite#1338]
Swordfish is not found via the G.e. search feature on the client, Entering 'sword' 'fish' or 'swordfish' do not return it.

Little problem that i noticed while doing some cooking, Great client keep up the good work :)

**Comment by gregg1494** [comment]
When I search it is appearing.
![image](https://user-images.githubusercontent.com/14902604/38539644-9d8a4aea-3c5e-11e8-8fd4-9ff7dea66ea3.png)

**Comment by TheeWiki** [comment]
@gregg1494 If you type in swordf nothing will appear, that's what he's basically asking about for shortcut search phrases, similar to how the real GE works for finding item index when searching a phrase.
