### ISSUE TITLE
[Bank Tags] Tiny tempor tag icon not centered

### ISSUE THREAD

**Issue by asmith-personal** [runelite/runelite#13389]
**Describe the bug**
Tempoross inventory icon is not centered and looks really off.

**To Reproduce**
1. Change icon on a tag tab
2. Search and select 'tiny tempor'
3. Note off-center icon

**Expected behavior**
Icon would be center

**Screenshots**
![image](https://user-images.githubusercontent.com/22417976/112670963-95a29780-8e2f-11eb-8ad8-64e25bf82c08.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.3
 - Launcher version: 2.1.0

**Comment by Nightfirecat** [comment]
We don't control the centering of icons. If its centering is an issue, please report this to Jagex.
