### ISSUE TITLE
Slayer highlight targets tile option

### ISSUE THREAD

**Issue by Olmium** [runelite/runelite#13393]
Slayer monsters can be highlighted in the Slayer plugin but only highlighted. I would like a tile highlighter option like the NPC Indicators plugin has currently.

**Comment by Nightfirecat** [comment]
Related to (maybe duplicate of?) #4606. Currently there's no simple way to add this behavior without fully duplicating the code used by the NPC Indicators plugin.

**Comment by Olmium** [comment]
Looks like this is a duplicate. Sorry about that but it would be really nice to have this feature. I really dislike the hull option and the tiles look a lot cleaner and nicer imo
