### ISSUE TITLE
Custom notifications

### ISSUE THREAD

**Issue by Olmium** [runelite/runelite#13394]
Notifications are a big part in Runescape AFK playing and also as warnings. These warnings are triggered fairly often depending on the content and can range from leaving combat to low hitpoints. The low hitpoints is the most common contributor but other also, but whenever I receive a notification for low hitpoints I get a notification like I should. The problem is with the notification itself. Windows integrated notifications tend to have a big hitbox as it were and it stays on the screen for a long time with the only option being the smaller cross in the corner of the notification. Because this notification is so big it pretty much blocks the entire inventory on my screen which results in some extremely stressful situations while doing some quest combat, or afking slayer.

A custom notification option would be nice. Maybe not as a standard option but as a option in general would be amazing. A visual indication which you can choose to show anywhere on the screen with default maybe custom sound options would be nice. Anything simple like the default Windows sound, as long as I can distinguish it from any other sounds like music.

I've looked into custom notifications for Windows maybe even a program to edit current Windows notifications but there is nothing I could find. I have searched quite extensively, but maybe in the wrong place.

Here is a screenshot of the Windows notification obstructing my inventory. The "hitbox" extends all the way to my mouse cursor.
![Untitled](https://user-images.githubusercontent.com/81484914/112730296-1a290f00-8f31-11eb-80d5-8a88116dbcbd.png)

**Comment by Broooklyn** [comment]
I believe "RL Tray Notifications" on the plugin hub does essentially what you're looking for.

**Comment by Olmium** [comment]
> I believe "RL Tray Notifications" on the plugin hub does essentially what you're looking for.

This is amazing thank you!
