### ISSUE TITLE
The Mahoghany Homes PLugin should says planks needed

### ISSUE THREAD

**Issue by Tateygb** [runelite/runelite#13398]
The mahoghany homes plugin should say planks needed for the task and potentially how many you have on you to ensure that you can complete the task or whether you need to go to the bank and get more planks/steel bars out.

**Comment by Bram91** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
