### ISSUE TITLE
Runelite Settings Issue

### ISSUE THREAD

**Issue by ForeverrLSU** [runelite/runelite#13405]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
Happens as soon as I launch the game.

**Expected behavior**
Be able to cycle through possible pluggins.

**Screenshots**
Video attached.

**Environment (please complete the following information):**
 - OS: Windows 10 
 - RuneLite version: 1.7.3.1
 - Launcher version: ?????

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

https://user-images.githubusercontent.com/81549081/112790298-ac5e0f80-9024-11eb-8f7d-4a8a06c7d85f.mov

**Comment by Nightfirecat** [comment]
This can be solved by following the directions on this wiki page: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

In the future, we recommend reaching out in the `#support` channel of our Discord server at https://runelite.net/discord

**Comment by ForeverrLSU** [comment]
@Nightfirecat I've already tried doing this. The problem is still occuring?
