### ISSUE TITLE
Bandos godsword and Bandos godsword (or) dont combine damage for corp

### ISSUE THREAD

**Issue by Txaggie13** [runelite/runelite#13402]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

When using the special attack plugin along with party for duoing corp, if one person has a normal BGS and another has the ornament BGS, you will get two different damage counters

**To Reproduce**
One person with BGS, another with BGS (or)

**Expected behavior**
Two different damage counters, instead of one

**Screenshots**
![BGS damage](https://user-images.githubusercontent.com/60858037/112773119-5c6a5300-8ffa-11eb-899e-44982e2dde32.PNG)

**Comment by Adam-** [comment]
The expected behavior should just one damage counter for both bgs types, since they are effectively the same.
