### ISSUE TITLE
Health and prayer indicators in tray

### ISSUE THREAD

**Issue by DRAGINZAk** [runelite/runelite#1340]
Well there are some afk killing spots and would be nice to see your HP while game is minimized, for example : 
https://imgur.com/a/hXc6v
Maybe even show your prayer also. 👍 
P.S. I'm not really into clients etc. so I don't even know if it's possible (Smiling Face With Open Mouth And Smiling Eyes, but with a single drop of sweat on one side of the face).

**Comment by SoyChai** [comment]
Love the sound of this! Great idea.

Although the specific concept you've mocked up might not be possible without some ugly Windows voodoo, we *could* use Windows' native progress bars that are displayed on top of taskbar programs when they're doing things like downloading a file.

**Comment by LeviSchuck** [comment]
Implementing the suggested view would require OS-specific development. 

Something easier would be a always-on-top window powered with a canvas. It could be updated on events or with a scheduled method.

**Comment by deathbeam** [comment]
i don't really like the always on top window, as that can only work for Windows, it would be terrible behaviour for Linux and OSB (probably also for Windows). We could probably do what OSB does and display it as tray icon, even though I always found that feature pretty ugly.

**Comment by SoyChai** [comment]
I actually think Levi's suggestion escalates this idea to a whole new level, because that kind of window could display all *kinds* of useful afk'ing information.

**Comment by deathbeam** [comment]
Yeah but the implementation of the idea is not very good

**Comment by LeviSchuck** [comment]
Do we have a precedent for including native tools in runelite? 

In mac at least, a full screen app hides the tool bar, so an indicator there would be pointless. 
I would probably put it on another screen where I have my music player (not full screen)

**Comment by zeruth** [comment]
Yeah this is a pain, and would differ from OS to OS unless we wrote out own. I bet you we don't even have cross platform SystemTray support yet.

**Comment by deathbeam** [comment]
Actually, we do, well, Java have. Current tray icon is pretty cross-platform.

**Comment by LeviSchuck** [comment]
Can it be more than just a square icon of the RL logo?

**Comment by deathbeam** [comment]
You can set w/e icon you want

**Comment by SoyChai** [comment]
RuneLite's current icon isn't even a square, so there's your answer 👅

**Comment by LeviSchuck** [comment]
My point is, can we use something more than a 2D square sprite?

**Comment by deathbeam** [comment]
You can only use image. But, you can create the image programatically.

**Comment by SoyChai** [comment]
The icon could be a rotating image of a 3D object if we wanted, depending on how often the OS lets you update it.

**Comment by LeviSchuck** [comment]
It looks like the tray icon is not always supported in linux from java (despite Telegram and discord having tray ui). Having alternative methods would be necessary for me.

**Comment by deathbeam** [comment]
For me the tray icon works perfectly on Linux. Probably it's dependant on your tray implementation too. Alternative methods suggested in this thread are bad idea to implement.

**Comment by Hydrox6** [comment]
From what I can tell, this is currently supported with the `Tray Indicators` hub plugin
