### ISSUE TITLE
Tempoross pb tracking

### ISSUE THREAD

**Issue by red-eye-jedi** [runelite/runelite#13414]
!pb tempoross command to display personal best tempoross time. please/thanks

**Comment by evaan** [comment]
Runescape doesn't time Tempoross from what it know.

**Comment by red-eye-jedi** [comment]
yes it does https://gyazo.com/9c1d7afd10e884cab7412d34751845b5

**Comment by red-eye-jedi** [comment]
@evaan can we get tempoross Pb time added using this interface please <3 https://gyazo.com/9c1d7afd10e884cab7412d34751845b5
its next to the bank at tempoross

**Comment by Hydrox6** [comment]
This is unlikely to be useful unless Jagex add a message after the kill showing the time. Not sure why they didn't already tbh, but I'd imagine most people don't even know of the board.

The alternative is adding specific timing logic, though making that accurate to how Jagex times things has been an issue in past attempts, and it would also be a bit excessive for just a single skilling boss.

**Comment by red-eye-jedi** [comment]
@Hydrox6 i understand that if added this would not automatically update after each kill but rather when the board itself gets checked. i believe this would behave similar to how personal best chambers of xeric times work. having to view PB times in your POH to reset to your overall fastest time and not last team size played.
I imagine that most players do not know of the boards existence but for the small speedrunning community, this would be nice.

**Comment by evaan** [comment]
It pulls the time from what RuneScape tells you, if you wanted to make a plug-in that would time tempoross, I’m sure they’d be happy to merge it.

**Comment by red-eye-jedi** [comment]
@Hydrox6 https://gyazo.com/6892dae6dd300bb63362b8641f05d03d/
today jagex added the feature i have been requesting for a while now to both you guys and  jmods themselves.
now that we have the times tracked and displayed after each kill can we go ahead with the !pb command for tempoross?

**Comment by red-eye-jedi** [comment]
i have been checking every single day on j mod tweets and in here to get this done, i never wanted something in game more than this, no rest for the wicked aye. cheers @Hydrox6
