### ISSUE TITLE
Tempoross HarpoonFish Timer

### ISSUE THREAD

**Issue by FatClouds** [runelite/runelite#13416]
When doing solo tempoross, notice sometimes i will get to a harpoonfish spot and it will despawn fast,

Would like a timer added to harpoonfish spots if possible, similar to the double spot.

5 second timer or so alerting the spot will despawn soon.  alternative if possible

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
