### ISSUE TITLE
underwater mermaid area

### ISSUE THREAD

**Issue by picklllle** [runelite/runelite#13412]
hi.  i do not like extra pazzaz while playing rs and the underwater mermaid area seems to have a constant blinking red arrow showing where the mermaid tear chest currently is.  this is a little annoying while doing giant seaweed runs.  i dont know if it is a bug or just implemented but ive tried to turn it off and cannot find anything to configure it.  please allow a disable button for this that would be great!  thanks

**Comment by Nightfirecat** [comment]
I have not seen any arrows appearing when doing giant seaweed runs on my own accounts, so this may be some hub plugin or other feature you have enabled on your end. Can you provide more information on how to make this happen?

**Comment by makingcomment** [comment]
I think picklllle is referring to the minimap arrow that the game puts in to direct you to the agility/thieving chest. It only appears when you're in the eastern part of the underwater area (past the northern gate shown in https://oldschool.runescape.wiki/w/Underwater_Agility_and_Thieving#/media/File:Underwater-agility-course.png, where the word "underwater" is)

**Comment by picklllle** [comment]
yeah its the underwater area for agil/ thiev.  ive tried disabling all runelite plugs but no luck. here is a screenshot.  my mistake i thought it may have been put in from runelite but after thinking on it i think its part of jagex coding.  
![2021-04-11_05-59-05](https://user-images.githubusercontent.com/81590145/114305224-fd8dea80-9a8b-11eb-99fd-5c767121a592.png)
