### ISSUE TITLE
Mouseover tooltip's capital I and lowercase l are the exact same glyph

### ISSUE THREAD

**Issue by Tyrannosaurus1234** [runelite/runelite#13418]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The capital i and lowercase L share the exact same font glyph in the mouseover tooltip, very confusing for non-native English speakers. Official Runescape fonts have serifs to distinguish the two.

**To Reproduce**
1. enable Mouse Tooltips plugin
2. mouseover something with a capital i, and something with a capital l
3. compare glyphs

**Expected behavior**
I expected them to be different from one another.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/36250109/113105330-790bb400-91cf-11eb-8fff-c4692aa6604d.png)

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - RuneLite version: 1.7.3.1
 - Launcher version: 2.1.6

**Additional context**
n/a

**Comment by Nightfirecat** [comment]
Change the "Tooltip Font" setting to anything except "Small" under `RuneLite`'s settings.
