### ISSUE TITLE
Opening birds nests not counting correctly - Loot Tracker

### ISSUE THREAD

**Issue by DanCrayons** [runelite/runelite#13426]
When opening birds nests fast, the count does not increase correctly.

For example, opening 2 seed nests in the same game tick results in only the first nest being counted.

**Comment by Hydrox6** [comment]
You have to open them slower, see [the original](https://github.com/runelite/runelite/issues/5824#issuecomment-558206554)

There's really nothing we can feasibly do about this while keeping the speed. I made a plugin called `Crate Limiter` on the hub to enforce a lower speed if you just want to spam it; lmk on my plugin repo if it doesn't support bird nests and I'll look into it.
