### ISSUE TITLE
CTD after loading since 3/29

### ISSUE THREAD

**Issue by Faderr** [runelite/runelite#13424]
**Describe the bug**
On Friday, 3/26, I restarted my computer as I always do on Friday evenings. It wasn't used all weekend, but since I returned to it Mon 3/29, Runelite (and, in fact, even the Steam OSRS client) crash immediately upon loading. That is, plugins etc. will load but the moment RL's 'frame' displays, it crashes to desktop. Other than a Windows Update, I changed absolutely nothing in RL's settings, Java, what have you.

I have found that completely removing all graphics drivers will allow RL to open occasionally, but almost entirely at random. This, of course, isn't ideal as I'm unable to play practically any other game and causes RL to run very poorly.

**To Reproduce**
Launch RuneLite.

**Expected behavior**
RuneLite loading succesfully.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - RuneLite version: Whichever is current as of today.
 - Launcher version: Ditto

**Additional context**
[jvm_crash_pid_18536.log](https://github.com/runelite/runelite/files/6238759/jvm_crash_pid_18536.log)

**Comment by Nightfirecat** [comment]
We've not made any changes to the client over the weekend. This is likely a graphics driver bug on your machine.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
