### ISSUE TITLE
Menu entry swapper extended: Construction cape poh tele no longer first option after using fairy ring

### ISSUE THREAD

**Issue by HardMoo** [runelite/runelite#13429]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Construction cape is no longer left click "Teleport to POH" after using Fairy ring configure, but rather "Teleport" due to Menu entry swapper plugin "teleport item". If teleport item is not turned on, everything works

**To Reproduce**
1. Turn on "construction cape" in menu entry swapper extended plug in. - Teleport to POH will now be left click option.
(I also have teleport item turned on in the regular menu entry swapper.)
2. Go to any Fairy ring and click "Configure Fairy ring"
3. Either use the teleport or exit the menu
4. Construction cape is no longer left click "Teleport to POH", but rather "Teleport" due to Menu entry swapper plugin "teleport item". 
**Expected behavior**
To be able to have "Teleport item" turned on so I can use items such as dueling rings and amulets of glory, and to also be able to have "Construction cape" turned on so I get to my house efficiently.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.3.1
 - Launcher version: unknown

**Comment by Nightfirecat** [comment]
Please report this [to the Menu Swapper Extended authors](https://github.com/raiyni/menu-swapper-extended) as we do not support hub plugins here.
