### ISSUE TITLE
Feature Request: UIM Death Storage Tracker

### ISSUE THREAD

**Issue by TokenGoat** [runelite/runelite#13428]
Just tracks what's in your inventory, looting bag, runepouch, herb sack, seedbox and equipped and stores that information.

When a UIM suicides e.g. to zulrah or hespori just tracks what items are in the death storage, what's been removed and in zulrah's case what order those items are in.

Just a QOL for being lazy.

**Comment by Felanbird** [comment]
I believe this ended up being added via the hub plugin `Dude where's my stuff?`
