### ISSUE TITLE
The Banked Experienced Plugin Should Save Skilling Preferences

### ISSUE THREAD

**Issue by mrwhisker23** [runelite/runelite#13438]
Currently, the RuneLite plugin "banked experience" has a feature that allows you to ignore certain items or to set which method you are using. However, after closing the client this data is lost.

The preferences set should be remembered between sessions if possible. 

_Side Note:_ The construction tab should also be updated to show the average experience per plank while using Mahogany Homes.

Thank you!

**Comment by abextm** [comment]
Issues for plugin hub plugins should be opened on the plugin's repo

**Comment by Adam-** [comment]
(which is https://github.com/TheStonedTurtle/banked-experience)

**Comment by mrwhisker23** [comment]
> (which is https://github.com/TheStonedTurtle/banked-experience)

Thank you, sorry I was in the wrong place
