### ISSUE TITLE
Tag Tab items that don't hold placeholders

### ISSUE THREAD

**Issue by Yarhar00** [runelite/runelite#13449]
Hello. So i am trying the Tag Tab function to make a Vorkath tab i can easily go to, but the items "Verac's plateskirt" and "Karil's leathertop" never make a placeholder in this Tag Tab. All other items thus far i have tried do, merely these two seem to have some issue with it. Pretty simple to test. 

1: Make tag tab
2: Have "always set placeholder" On
3: Put Verac plateskirt and Karil leathertop in the tag tab
4: Remove said items

**Comment by Nightfirecat** [comment]
For your vorkath tag, tag the items `vorkath*` to tag all item variations. The placeholder version of these items is not the same as the partially-degraded equippable variant.

**Comment by Hydrox6** [comment]
can also shift drag the items to the tab for the same effect
