### ISSUE TITLE
Right click drop down menu color

### ISSUE THREAD

**Issue by ChoofHead** [runelite/runelite#13444]
**Is your feature request related to a problem? Please describe.**
wouldnt say its a problem persay, just OCD

**Describe the solution you'd like**
When useing Resource packs would like the right click drop down menu to be recoloured to match the current resource pack

**Describe alternatives you've considered**
Not useing resource packs and just useing the normal vanilla layout/colours

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
