### ISSUE TITLE
Number 9 doesn't work in game (Works typing in search bar)

### ISSUE THREAD

**Issue by D4l33** [runelite/runelite#13442]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Number 9 doesn't work in game but works typing in search bar within runlite. 

I have tried uninstalling and re-installing and it does the same thing. It also does it on my work computer (Windows PC) 

**To Reproduce**
1. Go to 'enter '9' int he chat or a dialogue ie clue scroll answer'
2. See error

**Expected behavior**
Type 9

**Environment (please complete the following information):**
 - OS: macOS & Windows 10
 - RuneLite version: 2.1.2
 - Launcher version: Im not sure. 

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

I can't Find this.

**Comment by Hydrox6** [comment]
Cannot reproduce; 9 works perfectly fine in game

If the date briefly appears on the report button, then you've got 9 bound as your `Screenshot` key. Also try disabling any hub plugins that have keybinds

For further questions of support, please join the [Discord](https://runelite.net/discord)
