### ISSUE TITLE
tempoross item despawn timers.

### ISSUE THREAD

**Issue by red-eye-jedi** [runelite/runelite#13456]
tempoross items: buckets, fish, hammers, ropes that are dropped are currently not displaying the correct despawn timer information when holding ALT. i believe this is behaving as if tempoross is any other instance where the despawn timer is 30 minutes. can this be fixed please? would be very useful.

**Comment by FlashBasedGod** [comment]
After seeing a few videos about solo/point stacking I can see the importance of this. I can do it if nobody else is.

**Comment by red-eye-jedi** [comment]
that would be absolutely amazing!!
