### ISSUE TITLE
Show virtual levels as 100/100 instead of 99/100

### ISSUE THREAD

**Issue by hugofaas** [runelite/runelite#13459]
The Virtual level plugin currently shows virtual levels as 99/100, 99/101, 99/102 etc.
It would be nice if there could be a toggle to show virtual levels in the same way as RS3, being 100/100, 101/101, etc.

It looks better/cleaner and you know in reality it's 99 anyway, that doesn't need to be shown.

If a skill is boosted, it can override the left number. It's done the same way on RS3. 103/103 becoming 118/103, 117/103, 101/103, etc.

**Comment by Nightfirecat** [comment]
The way it's currently implemented is intentional. If virtual levels were displayed as 100/100 for instance, there would be no way to distinguish between the skill being +1 boosted or at its default.

**Comment by Adam-** [comment]
This makes it completely ambiguous whether or not a skill is boosted. And it doesn't really line up with how skills work, since the boosted level affects eg. damage dealt or rate you get resources, and this wouldn't.

**Comment by Nightfirecat** [comment]
For what it's worth, we've already discussed (and turned down) this feature in #7173

**Comment by hugofaas** [comment]
The arguments make sense, but are related to personal opinion.
I understand it's not a comment that will 'win' this discussion on it's own, but considering RS3 has handled this differently for many years suggests to me there should be a decently sized group of people who would prefer to have other options here.

**Comment by Nightfirecat** [comment]
As was discussed nearly 2 years ago, this was discussed and turned down in the past. We haven't changed our minds on this in the meantime.
