### ISSUE TITLE
Add Herbiboar to the boss killcount leaderboards

### ISSUE THREAD

**Issue by CaptainCerg** [runelite/runelite#13469]
Even though Herbiboar is technically not a boss, the killcount is still tallied in the chatbox. I think it would be cool to be able to see everyone elses killcount on Herbiboar on the leaderboard search. Seems like it wouldn't really hurt to add it to the list since Tempoross is added to the list as well.

**Comment by Nightfirecat** [comment]
We only list bosses which are listed [on the official Old School RuneScape hiscores](http://services.runescape.com/m=hiscore_oldschool/overall.ws). Presently, you can share your herbiboar kill count using `!kc herbiboar` command with the Chat Commands plugin.
