### ISSUE TITLE
Minor bug: Swamp fishing spot not highlighted

### ISSUE THREAD

**Issue by Joeytje50** [runelite/runelite#13467]
**Describe the bug**
The western fishing spot in the Dorgesh-Kaan caves is not highlighted with the Fishing plugin.

**To Reproduce**
1. Put a rishing rod and bait in your inventory
2. Go south of Dorgesh-Kaan and walk to the western fishing spot
3. The spot is missing its fishing rod overlay ('Fishing' plugin)

**Expected behavior**
An overlay should appear if the Fishing plugin is turned on.

**Details**
The NPC ID that should be highlighted for this type of fishing spot are: 1497,1498,1499,1500, (of which 1500 is missing) which are https://oldschool.runescape.wiki/w/Fishing_spot_(frogspawn) on the wiki.

**Comment by jsgarrett22** [comment]
I'd like to take this one if it is still available.

**Comment by vmarlowe** [comment]
Trying to make changes suggested by @Nightfirecat for my first contribution/school project. I am new to this project!
