### ISSUE TITLE
Add a swap to "walk here" to "pick wheat"

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#13464]
I've been doing a lot of clues lately and the steps on wheat fields are very annoying because of how densely packed they are, I'd like to be able to have a Swap for replacing the "pick" option with "walk here" because I don't ever pick wheat in this game after doing cook's assistant.

**Comment by Hydrox6** [comment]
Banned by the [Jagex Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1)
> Allows you to prioritise the walk-here option by holding a certain key, or similar

It's kinda silly for something like this, but the wording is pretty clear. I would recommend navigating with the minimap there.
