### ISSUE TITLE
Logging in outside of Wintertodt's prison always causes a "Game is starting soon" notification

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#13468]
Even when a round of Wintertodt has already started and is underway, logging in while standing at the Wintertodt camp will always trigger a "Game is starting soon" notification. This should only be triggered when the timer is nearly finished counting down, never upon login.

**Comment by sbaisden25** [comment]
I cant seem to recreate this bug while hopping worlds in the wintertodt camp or prison.

**Comment by Adam-** [comment]
fixed in 7e9cb6c88e5efe72963bb58ed936dc45d34088a3
