### ISSUE TITLE
ardy easy task fishing requirement of 15 isn't correct

### ISSUE THREAD

**Issue by oob1234** [runelite/runelite#13476]
I was doing the ardy easy tasks today, and it said I needed 15 fishing for the trawler part. I went in with 11 fishing and the task completed anyway!

**Comment by Nightfirecat** [comment]
Of note for whoever fixes this, from [the Fishing Trawler wiki page](https://oldschool.runescape.wiki/w/Fishing_Trawler):

> Players need a minimum of level 15 Fishing to receive any rewards, **but can board the ship otherwise at any level.**

**Comment by pwatts6060** [comment]
Yeah just checked you can do it with 1 fishing even. 15 is req to get rewards.
