### ISSUE TITLE
Not sure if bug or intended but why are the status bars no longer either side of the inventory?

### ISSUE THREAD

**Issue by uhFuzu** [runelite/runelite#13474]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Not sure if bug or intended but why are the status bars no longer either side of the inventory? Is this intended or am I experiencing an issue. I haven't been using the runelite client long and I just wondered why it has moved to being two bars next to each other to the left of the inventory?

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'Configuration'
3. Scroll down to 'Status Bars'
4. Switch on and see bars incorrect location

**Expected behavior**
They should be either side of the inventory not both squeezed to the left
 

**Screenshots**
![Screenshot 2021-04-12 201512](https://user-images.githubusercontent.com/82410509/114448721-d0485600-9bcb-11eb-9d49-13c4dfe8e65b.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: [e.g 1.7.4]
 - Launcher version: [e.g 2.1.6]

**Comment by Alexsuperfly** [comment]
there are no pillars to place them on when in modern layout

**Comment by uhFuzu** [comment]
> 
> 
> there are no pillars to place them on when in modern layout

So could I potentially request them to be moved back in the modern layout if i submit a feature request ya think?

**Comment by Nightfirecat** [comment]
The bars have never been on the sides of the inventory in this layout as there's no space. You must use one of the classic layouts for them to overlap the side pillars.

**Comment by uhFuzu** [comment]
> 
> 
> The bars have never been on the sides of the inventory in this layout as there's no space. You must use one of the classic layouts for them to overlap the side pillars.
Any chance you could tell me how to do that, I've tried changing this using interface styles to no avail, is this an option I can switch to?

**Comment by Alexsuperfly** [comment]
the in game [settings](https://oldschool.runescape.wiki/w/Options)
