### ISSUE TITLE
Fairy ring code not appeearing when searching it (CJR)

### ISSUE THREAD

**Issue by IlPicasso** [runelite/runelite#13479]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When using a fairy ring and typing in search box CJR or Sinclair Mansion there is no result

**To Reproduce**
1. Go to a Fairy Ring
2. Type in search box CJR or Sinclair 
3. No Output

**Expected behavior**
Sinclair Mansion

**Comment by Hydrox6** [comment]
If you've never been to that fairy ring, it won't show, so you need to go there once
If the fairy ring is marked as a favourite, it won't show when filtered since it's an entirely separate interface.
