### ISSUE TITLE
100+ ping every night (Runelite only, not my network)

### ISSUE THREAD

**Issue by Sweegus** [runelite/runelite#13487]
My ping goes from 11 ms to 100+ ms for every world from 6-11 pm nightly. My ISP is not throttling my network and can't help me resolve this issue. My speedtest results are 10 ms ping and normal up/down and I'm only experiencing this ping issue on runelite. Trying to boss let alone do anything on 100+ ping is very annoying and its been like this 6 hours a night for the past 2 weeks.

**Comment by Nightfirecat** [comment]
RuneLite has nothing to do with the ping time for your connection to Jagex game servers. I expect you would experience similar lag on the official client during these time frames.
