### ISSUE TITLE
Option for Banked XP plugin - only calculate banked xp of items with secondaries banked

### ISSUE THREAD

**Issue by zombiezrule** [runelite/runelite#13492]
**Is your feature request related to a problem? Please describe.**
Banked xp plugin lists all primary items for herblore such as herbs and unfinished potions, and assumes all secondaries are banked/buyable. I recently found the option to show the required secondaries, although would like if there was an option to only show banked xp, particularly for herblore, for potions with secondaries also already banked.

**Describe the solution you'd like**
An option in the plugin that allows banked xp to factor in banked secondaries, and only calculate xp gained from a potion if its respective secondary is also banked.
For example: 
I have 1k unfinished dwarf weed potions, which would give 162,500 xp.
However, I only have 200 zamorak wines.
With the option enabled, the banked xp plugin would only say that I can get 32,500 xp from dwarf weed potions, as I only have 200 potions make-able from what I have banked.
Possibly, it would also note that I need 800 more zamorak wines to gain the rest of the xp. 

Ideally, along with the "total banked xp" listed above the individual potions, the plugin would also list the "total banked xp including secondaries", probably with some shorter phrase so it looks nicer.

**Describe alternatives you've considered**
Right clicking to ignore potions works when I don't have any of its respective secondary, but obviously doesn't suit what I want when I do have some, but not all, of the secondary required.

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
