### ISSUE TITLE
Time Tracking Not Working Correctly For Teak Trees

### ISSUE THREAD

**Issue by Spigotron** [runelite/runelite#13496]
Sometimes the Time Tracking plugin will assert that my teak trees on Fossil Island are ready, but when I go to check them, they've still got one more growth cycle to complete.

**To Reproduce**
S teps to reproduce the behavior:

**Expected behavior**
I expect to be able to check the health of my teak trees.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.6
 - Launcher version: 1.5.2

**Comment by Hydrox6** [comment]
The Time Tracking plugin now accounts for user offsets once calibrated.
> For anyone looking to quickly get accurate times the simplest solution is to plant a normal tree and keep it within your render distance for 40 minutes. After observing the tree growing one stage your timers for all crops will be 100% accurate.

**Comment by MirrorImageQS** [comment]
@Hydrox6 I believe this is actually still an issue. For the past several days, all of my Herb Patch timers have been showing the same issue.

I saw that point about planting a normal tree to calibrate it, so I planted a Magic Tree at the Farming Guild and sat around it for about an hour. That didn't seem to affect it, and my patches are still reporting one growth cycle too early.
