### ISSUE TITLE
Add colors array to PlayerComposition api

### ISSUE THREAD

**Issue by equirs** [runelite/runelite#13490]
I would like to access this int array in the `PlayerComposition` so that I can implement some features in the Fashionscape plugin. To my knowledge, the colors array is the only non-static `int[]` in this class other than the existing `equipmentIds`. I don't see any potential for abuse with this addition as the colors in this array are ids, and setting them to invalid values just messes up your colors slightly (so it doesn't allow selectively hiding players), but correct me if I'm wrong.

**Comment by Adam-** [comment]
added in c2621e236e51f6989aa2795badbda5412e94f3c4
