### ISSUE TITLE
Maven Comipler error

### ISSUE THREAD

**Issue by chngedd** [runelite/runelite#13498]
Can someone please for the love of got explain why this is happening. 

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project http-api: Fatal error compiling

It worked fine the first time I changed code and compiled and it worked I updated runelite at least twice and never had any issues and now I update today after Wednesdays patch, I guess intellij had some updates to, and now I get this error. I got the same error months ago when I tried to do this on my laptop after successfully doing it on my desktop and I thought it was just cuz my laptops old but now its infected my desktop and I cant do anything anymore.

I googled it and I deleted the .m3 for what ever reason that didn't help. and all the other solutions involve adding code which obviously isn't necessary on the stable version of a release that thousands of people are using 

I have jdk 8 and that's not a problem. I have the default maven packaged with intellij the same version I used months ago that worked.  It even runs some of the maven things fine like runelite/lifecycle/clean runs fine. just install doesn't work.

**Comment by Nightfirecat** [comment]
RuneLite now requires JDK 11-15 to build. Download it from https://adoptopenjdk.net/
