### ISSUE TITLE
cannon plugin: Add recommended spot for dagganoth in Jormungand prison

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#13503]
It is a pretty good task, comparable to Lighthouse. I prefer cannoning them in the western room. Not sure which tile is optimal.

**Comment by mattvermeer** [comment]
Hey mate, 

Do you know what the co-ordinates for Jormungand prison is, I don't have the requirements to get there. 

For anyone else that comes across this, to complete this request if you have the requirements/co-ordinates:
runelite-client/src/main/java/net/runelite/client/plugins/cannon/CannonSpots.java

Line 46 change from:

	DAGGANOTH(new WorldPoint(2524, 10020, 0)),
to
	DAGGANOTH(new WorldPoint(2524, 10020, 0), new WorldPoint(X, Y, Z)),

Where X,Y,Z is the x,y,z co-ordinates.
