### ISSUE TITLE
Left click talk to Rusty - Easy clue step

### ISSUE THREAD

**Issue by Allemaalbaas** [runelite/runelite#13516]
**Is your feature request related to a problem? Please describe.**
Currently it can sometimes be a little annoying that you have to right click Rusty to talk for the easy clue step: "Speak to Rusty north of Falador". The first option is attack, making you one shot him almost every time. This is frustrating, because it can take a while before Rusty spawns again.

**Describe the solution you'd like**
I would like to have the the left click option on Rusty to be talk-to instead of attack. Currently you have to right click and click talk-to, because the first option is attack and killing him doesn't give you a new clue step.

**Comment by Hydrox6** [comment]
Banned by the [Jagex Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1)
> Removes or deprioritises attack, cast (or similar) options from the minimenu in any scenario
