### ISSUE TITLE
Bonecrusher Necklace Does Not Display Correct Stats In Tooltip

### ISSUE THREAD

**Issue by calebjallen** [runelite/runelite#13510]
**Describe the bug**
When hovering over a bonecrusher necklace in your inventory, it reads +12 prayer, but not the +10 to all offensive stats, +2 to all defensive stats, and +2 to melee strength.

**To Reproduce**

1. Have a bonecrusher necklace in your inventory.
2. Hover it, see the stats are missing.

![image](https://user-images.githubusercontent.com/22329530/115611685-64937680-a2b8-11eb-9bf1-18225b7adaa2.png)

**Expected behavior**
Should say these stats:
![image](https://user-images.githubusercontent.com/22329530/115610971-86d8c480-a2b7-11eb-8902-a14b34b363b1.png)

**Environment (please complete the following information):**
 - Windows 10
 - RuneLite version: 1.7.5
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
This was updated today by Jagex. Assuming this is fixed on the wiki, it will be corrected the next time wiki stats are scraped and uploaded to static.runelite.net

**Comment by Nightfirecat** [comment]
Fixed in runelite/static.runelite.net#317
