### ISSUE TITLE
Add AFK Timer to "Report Button" Plugin

### ISSUE THREAD

**Issue by vanoreo** [runelite/runelite#13511]
A nice addition to the Report Button plugin would be to add a timer that shows how many minutes/seconds it's been since you last interacted with the game window.

I know that by default there are notifications when you get close enough to hitting the logout timer, but I think this change would be pretty simple and add a small amount of QOL.

![image](https://user-images.githubusercontent.com/36086015/115628984-1a65c180-a2c7-11eb-8acb-a16087993c44.png)

**Comment by Atrolantra** [comment]
Looking into this.
