### ISSUE TITLE
AA causes image to freeze and selections stay on the screen

### ISSUE THREAD

**Issue by ReleaseTheKrkn** [runelite/runelite#13522]
When AA is turned on at all under the "GPU" section, menus seem to get stuck. I've recently completely wiped my video driver out and installed fully updated ones. I've had friends also report this as well with their client along with hardware acceleration causing similar problems. Full reinstall of video drivers didn't help and neither did a reinstall of the client. The only solution is to turn off AA, but I like the quality improvement.
![Untitled](https://user-images.githubusercontent.com/83138786/115970880-07433380-a50b-11eb-8b8e-1dc21dd6a32e.png)

**Comment by Hydrox6** [comment]
This usually means you have some level of AA forced in your GPU driver. Turn off this forcing, set RL's AA to the same as the forced amount, or turn off AA entirely in RL and it will work.

**Comment by ReleaseTheKrkn** [comment]
> This usually means you have some level of AA forced in your GPU driver. Turn off this forcing, set RL's AA to the same as the forced amount, or turn off AA entirely in RL and it will work.

You were 100% correct and I never noticed it while poking around in my Nvidia Control Panel. The "Global Settings" was forcing 8x AA. I turned it off/told it to "Use Application Settings" and that fixed it. Thanks for the quick response!
