### ISSUE TITLE
GPU plugin randomly started doing weird things with Dell S2721DGF Monitor

### ISSUE THREAD

**Issue by pkrnewb** [runelite/runelite#13535]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I recently purchased this monitor and it was working great, including with runelite, but when I tried to login today I had a weird issue which I tracked down to being the GPU plugin. The backlight seems to go super bright and also has these weird squiggles (Maybe due to low amount of local dimming zones). Youtube video showing issue: https://www.youtube.com/watch?v=Hycl1lUcuGs

**To Reproduce**
Turn on GPU plugin and put my mouse to a specific position

**Expected behavior**
Not have my backlight go crazy on my monitor

**Screenshots**
If applicable, add screenshots to help
![Runelite GPU Plugin monitor issue Image 1](https://user-images.githubusercontent.com/83313504/116314643-5db7a880-a77d-11eb-93e2-33e363c0f2f1.png)
![Runelite GPU Plugin monitor issue Image 2](https://user-images.githubusercontent.com/83313504/116314657-601a0280-a77d-11eb-955a-7664af472217.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.5 I think, I'm unsure where to check this though
 - Launcher version: [e.g 1.5.2]

**Additional context**
[client.log](https://github.com/runelite/runelite/files/6387752/client.log)
Youtube video showing issue: https://www.youtube.com/watch?v=Hycl1lUcuGs

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
