### ISSUE TITLE
Recolouring usernames causes friends to not count as friends, and ignoring someone to not remove existing chat messages

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#13537]
If any of the username recolour options are set under `Chat Color`, the client fails in certain ways. Notably, if a username is recoloured and the user is subsequently ignored, the existing chat messages don't get removed like usual. Another obvious behaviour is if you have someone added as a friend, and either have `Public friend usernames`, `Usernames`, or `Friends chat usernames` (if they're in an FC with you), right clicking their message will give a menu as if they're not on your friends list (no `Message` option, shows `Add friend` and `Add ignore`)

**To Reproduce**
1. Set `Chat Color` -> `Usernames` to something.
2. Go to a high traffic area (eg. W302 GE)
3. Add any one of the spammers there to your ignore list
4. Add them to the ignore list again using the same message, and note that they're already on your ignore list. Without the colour, the message you used to add them the second time would have been hidden.
5. Add another random spammer to your friends list. It does not matter if you or the target have private on.
6. Note that if you right click their message again, it won't have the option to message them, and will instead show options to add them as a friend or to the ignore list.

**Expected behaviour**
Messages with recoloured usernames should act the same as messages without recoloured usernames.

**Screenshots**
This issue was originally reported by `Lazark` in the Discord, and I have confirmed all of the above situations. Below is a gif they provided of the issue.
![pcnPpJg79a](https://user-images.githubusercontent.com/2979691/116385527-c734c700-a810-11eb-823b-329a2c4b07e4.gif)

**Environment (please complete the following information):**
 - RuneLite version: 1.7.5

**Comment by Adam-** [comment]
fixed in 90f200be531b8a899a605521f3e9840de6f9794d
