### ISSUE TITLE
Loot Tracker doesn't count kills when nothing drops

### ISSUE THREAD

**Issue by peroa** [runelite/runelite#13534]
**Describe the bug**
Killing Flesh Crawlers in the Stronghold of Security, I noticed that the kill count in Loot Tracker doesn't count up when a kill drops nothing.

**To Reproduce**
1. Go to the Stronghold of Security, second level, south east corner
2. Start killing Flesh Crawlers with the Loot Tracker tab open, keeping an eye on the kill count
3. Eventually, you'll get a kill that drops nothing; happens fairly often, probably more than 1 in 10 odds.
4. Watch the kill count remain unchanged whenever nothing drops from a kill.

**Expected behavior**
I expect the kill count to also count kills where nothing drops. Also, with "Show chat message for NPC kills"  enabled, I expect to see the message "You've killed a Flesh Crawler for 0 loot." just like I see when I get an untradeable drop.

**Environment (please complete the following information):**
 - OS: macOS 11.2.3
 - RuneLite version: 1.7.5
 - Launcher version: 2.1.5

**Additional context**
If these "nothing drop" kills aren't factored into loot table calculations, then that could skew the numbers for any NPC that can have a "nothing drop." I also enabled "Show chat message for NPC kills" and the message fails to appear for a "nothing drop."

**Comment by Hydrox6** [comment]
Duplicate of #10831

**Comment by peroa** [comment]
Darn, I'm realizing that I only searched open issues before logging this, not closed issues. Sorry for the dupe.
