### ISSUE TITLE
Display run energy orb without full minimap

### ISSUE THREAD

**Issue by wzrddd** [runelite/runelite#13536]
**Is your feature request related to a problem? Please describe.**
Doing 3t sandstone I need to put my minimap bottom left and it sometimes makes it a bit difficult for me to right click "walk here" if I'm a little bit late, causing me to lose ticks

**Describe the solution you'd like**
A way to hide the minimap but keep the run energy orb visible

**Describe alternatives you've considered**
An infobox for run energy would work but I'd prefer if I was able to toggle it to display in seconds too just like the orb

**Additional context**
This wouldn't just be useful here, I'd enjoy having it at blast furnace too since less screen clutter

**Comment by vwmiller90** [comment]
Status Bars Plugins let's you have bars for HP, Pray, Special, Run, but only two. Can set one to Run Energy. I use this for Sepulchre as I turn my minimap off.

**Comment by wzrddd** [comment]
> Status Bars Plugins let's you have bars for HP, Pray, Special, Run, but only two. Can set one to Run Energy. I use this for Sepulchre as I turn my minimap off.

I actually never knew about that, ty. Would also be nice if we could configure them more as in resize like other infoboxes or change colours or position

**Comment by Nightfirecat** [comment]
For the time being, I think this is adequately solved by using the Run Energy status bar. We have some open issues regarding resizing/repositioning them (#8516, #12846) so I recommend following or :+1: reacting to those for updates.
