### ISSUE TITLE
Hard crash (sound and monitor freeze)

### ISSUE THREAD

**Issue by pawick1** [runelite/runelite#13547]
**Describe the bug**
Randomly while playing computer will freeze, monitors turn to a single color and any sound playing will freeze. 
**To Reproduce**
1. Turn on GPU plugin
2. be patient

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows, version 2004, build 19041.928
 - RuneLite version: 1.7.6
 - Launcher version: 2.1.0

**Additional context**
Only way to reset is to restart the computer by holding the power button. 
GPU is radeon Vega 64 and cpu is i7 6700k no clock
client.log: https://pastebin.com/2eLRLNL6
launcher.log: https://pastebin.com/858UvfaA

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
