### ISSUE TITLE
Bug: Status bar misaligned

### ISSUE THREAD

**Issue by svmson** [runelite/runelite#13540]
New RS update seems to have interfered with the position of status bars.

![2021-04-28_11-46-59](https://user-images.githubusercontent.com/83345163/116391941-b5a2ed80-a817-11eb-99fa-1f27374fdbcb.png)

Not sure what caused this but closing the client didn't fix the issue neither did disabling then re-enabling the addon or reinstalling RuneLite.

**Comment by Hydrox6** [comment]
Wait for the update
