### ISSUE TITLE
Interface Styles 'Bottom Bar Stacking' stopped working after latest update

### ISSUE THREAD

**Issue by pertsaonerrfa** [runelite/runelite#13542]
Hello,

Noticed after latest update that **Interface Styles** `Always stack bottom bar` feature stopped working.

RuneLite version: 1.7.5
Oldschool revision: Rev 195
Launcher version 2.1.3

Confirmed from friends that they have the same issue.

**Comment by abextm** [comment]
fixed in da9137c6928a2c1f3f7c03180055c929cdc06bed
restart your client

**Comment by Hydrox6** [comment]
`1.7.5` is not he latest version
Restart your client
