### ISSUE TITLE
Status Bars misplaced on resizeable mode

### ISSUE THREAD

**Issue by richardcane** [runelite/runelite#13543]
**Describe the bug**
Status bars are overlapping inventory and menu items as of today's update.

**To Reproduce**
1. Enable status bars
2. Switch to resizeable layout mode

**Expected behavior**
![image](https://user-images.githubusercontent.com/29371470/116409428-be9dba00-a82b-11eb-969a-89f29a5f40a7.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/29371470/116409487-cc533f80-a82b-11eb-9d0d-0b636a52ceda.png)

**Environment:**
 - OS: tested on MacOS and Windows
 - RuneLite version: 1.7.6

**Comment by Adam-** [comment]
fixed in 94685b6ef4e4cf12ffe1e8cd1a68d17f2d806036
