### ISSUE TITLE
Menu Entry Swap for Urns at Pyramid Plunder

### ISSUE THREAD

**Issue by leo4710** [runelite/runelite#13556]
A Quality of Life improvement for Pyramid Plunder.

This would add the option to toggle "Urns" nested under "Object Swaps" and would replace "Search" with "Check for Snakes" while holding down the Shift Key. This would also allow users to replace "Search" with "Charm Snake" after a successful check.

The Pyramid Plunder Plugin may be better suited for this request.

This is a request similar to #7138
![image](https://user-images.githubusercontent.com/50725965/116768610-c4e78e00-aa05-11eb-999b-b025ca8a2dec.png)

![image](https://user-images.githubusercontent.com/50725965/116768659-56570000-aa06-11eb-961f-c2376460bb96.png)

**Comment by leo4710** [comment]
Bump?

**Comment by Hydrox6** [comment]
This can now be done with the changes in 92aac53f4273e7944c3da767637e083847c03808

**Comment by Hydrox6** [comment]
This can now be done with the changes in 92aac53f4273e7944c3da767637e083847c03808, and even better since it can all be done on left click instead of having to deal with shift clicking, it just has to be done for each type of urn
