### ISSUE TITLE
"Remove tab separators" from Bank Tabs to maintain the tab labels

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#13550]
Currently when we enable "remove tab separators" the client just treats the items in a tab as if they were all in the same tab, which removes the annoying separators that clog up the screen, but this also removes organization such as all potions and food on the same line.
I'd like if the sparators would be removed but the line breakers for bank tabs that contain an item in the runelite tab to still be present, for example:
- tab 1 has cons cape
- tab 2 has zulrah gear
- tab 3,4 and 5 have no items with the "zulrah" tag
- tab 6 has food and pots
I'd like if tab 1 items would appear then a line break then tab 2 items followed by a line break and then tab 6 items to appear skipping the blank rows of the tabs that dont contain items with the "zulrah" tag

**Comment by Hydrox6** [comment]
so basically the tab separators would be there, just invisible?

**Comment by vitorebom** [comment]
Correct, I made a quick explanation on mspaint on what I'm asking for 
[https://imgur.com/a/EGvZbUV](url)
Hope it helps

**Comment by Nightfirecat** [comment]
For what it's worth, I think this is a problem better solved by the Bank Tag Layouts hub plugin

**Comment by vitorebom** [comment]
The mentioned plugin does exactly that after some dragging around, thanks!
