### ISSUE TITLE
Right-click !price for all items

### ISSUE THREAD

**Issue by arlause** [runelite/runelite#13561]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Instead of always typing out "!price [item name]" to check the current GE price and HA values, could we add an option to the right click menu to check the price of an item?

**Describe alternatives you've considered**
None currently

**Additional context**
---

**Comment by Hydrox6** [comment]
Both the `Item Prices` and `Examine` plugins can already do this. `Item Prices` does this on hover as a tooltip, and `Examine` does it when you examine the item
