### ISSUE TITLE
Option to minimize the chat options tray under the chatbox.

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#13582]
Allows you to minimize the chat settings tray, saving up some space.

**Comment by Hydrox6** [comment]
This might actually be the most useless feature request I've ever seen, solving basically nothing while increasing the chance of confusion from unknowing players.

**Comment by Pingvinszar2** [comment]
> 
> 
> This might actually be the most useless feature request I've ever seen, solving basically nothing while increasing the chance of confusion from unknowing players.

'Unknowing players' wouldn't use the feature as it would be toggleable, and turned off by default.
I also made a little description about, what it would solve.
I am starting to wonder, if there are ANY of the suggested/recommended plugins, you have deemed 'useful'..
