### ISSUE TITLE
[Bank Value] Plugin extension

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#13580]
Additional features:

_a) Highlight items (also move highlighted items to the top of the list)
b) Search for item
c) Highlight colors_

**Comment by Hydrox6** [comment]
a) There are hub plugins that do this
b) This is already a feature
c) What?

**Comment by Hydrox6** [comment]
Apparently this was all for a hub plugin, so...

Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
