### ISSUE TITLE
Client Freezing up - continues to run but unable to Click

### ISSUE THREAD

**Issue by WeeWab** [runelite/runelite#13594]
I will just be playing runelite and the client will freeze up rendering me unable to click on anything in the game.
The game will continue to play sound and animations but will drop to ~15fps during this freezeup (anything from 3-5 seconds)

I have tried playing without GPU mode on
Tried without HW Acceleration Off
Checked CPU to ensure I'm not hitting 100% on cpu/gpu/ram
Checked power plan to ensure CPU is allowed to boostclock

Ryzen 5 3600x
AMD 5700XT

 - Windows 10
 - RuneLite version: 1.7.6
 - Launcher version: 1.6.0
 - OSRS Revision: 195
 - 

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
