### ISSUE TITLE
Keyboard shortcuts for Bank plugin

### ISSUE THREAD

**Issue by motorable** [runelite/runelite#13600]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Keyboard shortcuts for Deposit inventory and Deposit equipment buttons.

**Describe alternatives you've considered**
Keyboard shortcuts for other functions of the bank interface.

**Additional context**

**Comment by Nightfirecat** [comment]
Such a feature would be macroing, and will not be added.
