### ISSUE TITLE
Give us a notification when we get a bird's nest

### ISSUE THREAD

**Issue by Rektumsempra** [runelite/runelite#13606]
When I'm cutting redwoods, I get notifications when I'm idle which is good, but I often miss birds nests because redwoods are so afk. To be clear, I'm always doing something else on my computer when I'm at redwoods. So yeah I think a notification saying "You got a bird's nest!" or something would be nice.

**Comment by Alexsuperfly** [comment]
use the chat notifications plugin

**Comment by RuneLogApp** [comment]
This already exists in the Woodcutting plugin:

![](https://i.imgur.com/rFLMBOY.png)
