### ISSUE TITLE
PvP Performance Tracker Visual Upgrade

### ISSUE THREAD

**Issue by Pan1c07** [runelite/runelite#13605]
**Is your feature request related to a problem? Please describe.**
No, it's not.

**Describe the solution you'd like**
The tracker in it's current state works fantastic, however it's visuals are a bit confusing to the average player as it's a bunch of numbers in a box. I'm wanting to simplify it and make it more visually appealing.

**Describe alternatives you've considered**
A bar that slides up/down, similar to the one on Chess.com - I've talked to much of the Pking community already, and they all love the idea - I just need to find someone who's interested in creating it, as I have no coding experience and don't have the time to learn right now.

**Additional context**
Please see the images below for a visualisation of the idea. Here is a twitter post about it as well: https://twitter.com/Pan1c_Pk/status/1393942171099623430

My discord is Pan1c#9692 if you'd like to discuss it more, as I'm not very active on GitHub. Thanks!

![idea](https://user-images.githubusercontent.com/84281072/118402744-9a0c6380-b6ae-11eb-8af5-d7df1b6ac1e0.png)

**Comment by Hydrox6** [comment]
When you mentioned this on Discord, I thought you meant something completely new.

Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
