### ISSUE TITLE
Gnome Restaurant KC

### ISSUE THREAD

**Issue by JoshJ96** [runelite/runelite#13602]
Let's add a kill count for Gnome Restaurant, for flex of course.

![image](https://user-images.githubusercontent.com/33074635/118372878-ab0b8680-b581-11eb-98b4-645db358034a.png)

**Additional context**
This data does exist, as it is present in the collection log

![image](https://user-images.githubusercontent.com/33074635/118372882-ba8acf80-b581-11eb-985a-d9ea41891777.png)

**Comment by Nightfirecat** [comment]
Generally we don't add `!kc` commands for activities which don't output your completions/kills in the chat. Gnome delivery only shows your delivery counts in the collection log but never has chat messages, so I don't think we should add this.
