### ISSUE TITLE
No Metronome Sound

### ISSUE THREAD

**Issue by AlanPearl** [runelite/runelite#13613]
After the clan update today, the metronome no longer works for me. I can turn on the plugin, but I can't hear any ticking or tocking.

**Environment:**
 - OS: Windows 10

**Comment by Toahsty** [comment]
Same here!!!!!!!!

**Comment by Najo-z** [comment]
Sound is fixed after today's system update for me, on windows 10.

**Comment by Adam-** [comment]
this has been fixed in 1.7.8.1
