### ISSUE TITLE
Giant Sea Snake from Royal Trouble counts towards the slayer task Trolls in the plugin

### ISSUE THREAD

**Issue by nilPadisha** [runelite/runelite#13610]
**Describe the bug**
I paused slayering when I got my Troll task, then continued to do Throne of Miscellania & Royal Trouble, to afterwards find out that I've slain 1 Troll towards my slayer task in the runelite slayer plugin's counter. I double checked the mobs I've slain in my loottracker and there was no hidden troll kill anywhere. The only kill I've made is on The Giant Sea Snake from Royal Trouble.

The bug was fixed after I checked on my slayer helmet and the !task command a few times back and forth.

**To Reproduce**
1. Get a slayer task on Trolls
2. Slay the almighty Giant Sea Snake
3. Confuse the plugin that you've killed a troll but in fact you have not (slayer helmet claims)

**Expected behavior**
To have 0/142 in my chat instead when running the !task command or hovering over the counter.

**Screenshots**
https://i.imgur.com/C5Vkczr.png
https://i.imgur.com/PuhvQmo.png

Screenshot showing the kills inbetween the Sea Snake and my last slayer task (dagannoth)
https://i.imgur.com/zYuI2Fc.png

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - RuneLite version: 1.7.7
 - Launcher version: 2.1.0

**Comment by Alexsuperfly** [comment]
any slayer exp drop counts as a kill

**Comment by Nightfirecat** [comment]
This is the same issue described in #7984, so I am closing this.
