### ISSUE TITLE
Menu Entry Swapper Suggestion - Swap the 'Pick' option with 'Inspect' on flowers

### ISSUE THREAD

**Issue by Rahko** [runelite/runelite#13617]
Issue:
Currently it is easy to misclick a flower used for protecting crops from disease and pick it out, resulting in losing the protection and having to replant said flower.

Solution:
Add the ability to swap the 'Pick' option with 'Inspect' to stop accidentally picking flowers.

Additional context:
Option should exclude Limpwurt Roots and Woad Seeds as they only provide crops, without protecting other crops from disease (so there is no reason not to pick them).

**Comment by Hydrox6** [comment]
This can now be done with the changes in 92aac53f4273e7944c3da767637e083847c03808
