### ISSUE TITLE
My PC Crashed and all my local settings have been reset

### ISSUE THREAD

**Issue by aleccaputo** [runelite/runelite#13621]
**Describe the bug**
Was playing with RL on one monitor, opened the windows netflix app on my other monitor. Clicked play on a show, screens go black and my fans on my pc ramp up. Sit in this state for 5 mins until i hard restart my PC. When i get back on and open RuneLite, all my settings are defaulted (i do not have an account, i just stored it locally). 

**To Reproduce**
No Sure.

**Environment (please complete the following information):**
 - OS: Windows 10 10.0.19042 build 19042
 - RuneLite version: 1.7.8.1
 - Launcher version: 1.6.0

**Additional context**
[client.log](https://github.com/runelite/runelite/files/6523758/client.log)

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

**Comment by aleccaputo** [comment]
@Hydrox6 how is this not an issue? All my local settings were wiped from runelite. Willing to work with someone get get more info for them if needed
