### ISSUE TITLE
[Skill Guides] integrated to the Sidebar

### ISSUE THREAD

**Issue by Pingvinszar2** [runelite/runelite#13628]
**Plugin description:**
The **Skill Guides menu** from the skills tab would be integrated into the **Sidepanel.**

**This includes the following, but not limited to:**
-showing **all the contents** of a chosen skill.
-showing **all the levels required** for the skill contents.
-showing **all the materials required** for craftables.
-showing **all the quests required** _(if any)_ for the content.

**Extra:**
_-Left-Click would open up the **Sidebar Skill-Guide** instead of the in-game one (toggleable).
-Recolors the contents: **green for available, yellow for 'freshly'** unlocked (same level as the content) **red for unavailable.**
-Filter options to show **only unlocked, only locked contents, or freshly unlocked contents.**
-**Quest requirement levels** would also be listed.
-**Diary requirement levels** would also be listed.
-Flash for very recently unlocked contents._

**Issues with the in-game built Skill Guide:**
_-Currently, you are forced to pause your activities, in order to use the in-game skill guides.
-Uses up too much space from the screen.
-Opens slowly.
-Unaesthetic._

**Why is it good?**
_-This plugin would finally allow you to look up for your desired contents without having to constantly pause other activities.
-Would be continuously visible.
-Would allow you to have other interfaces, which you can't have opened with the in-game skill guides simultaneously (bank, chat, minigame rewards, etc).
-Doesn't require you to have wikipedia opened._

**Comment by abextm** [comment]
Use the wiki

**Comment by Pingvinszar2** [comment]
> 
> 
> Use the wiki
Why is it good?
-This plugin would finally allow you to look up for your desired contents without having to constantly pause other activities.
-Would be continuously visible.
-Would allow you to have other interfaces, which you can't have opened with the in-game skill guides simultaneously (bank, chat, minigame rewards, etc).
-Doesn't require you to have wikipedia opened.
????
