### ISSUE TITLE
Client crashes after viewing inventory setup while in bank

### ISSUE THREAD

**Issue by ThatCrazyViking** [runelite/runelite#13624]
**Describe the bug**
The title is it. The client crashes completely after opening an inventory setup while also having the bank screen open. Just not every time. 

**To Reproduce**
1. Go to your bank and open it.
2. Click on 'View setup' with the following setup: {"inventory":[{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":9739,"name":"Combat potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":2434,"name":"Prayer potion(4)","quantity":1,"fuzzy":false},{"id":995,"name":"Coins","quantity":40,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":13393,"name":"Xeric\u0027s talisman","quantity":1,"fuzzy":false},{"id":-1,"name":"","quantity":0,"fuzzy":false},{"id":-1,"name":"","quantity":0,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":11806,"name":"Saradomin godsword","quantity":1,"fuzzy":false},{"id":8013,"name":"Teleport to house","quantity":1,"fuzzy":false},{"id":24478,"name":"Open herb sack","quantity":1,"fuzzy":false},{"id":12791,"name":"Rune pouch","quantity":1,"fuzzy":false}],"equipment":[{"id":11865,"name":"Slayer helmet (i)","quantity":1,"fuzzy":false},{"id":6570,"name":"Fire cape","quantity":1,"fuzzy":false},{"id":6585,"name":"Amulet of fury","quantity":1,"fuzzy":false},{"id":4151,"name":"Abyssal whip","quantity":1,"fuzzy":false},{"id":9674,"name":"Proselyte hauberk","quantity":1,"fuzzy":false},{"id":12954,"name":"Dragon defender","quantity":1,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":9676,"name":"Proselyte cuisse","quantity":1,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":22981,"name":"Ferocious gloves","quantity":1,"fuzzy":false},{"id":11840,"name":"Dragon boots","quantity":1,"fuzzy":false},{"id":-1,"name":"null","quantity":0,"fuzzy":false},{"id":11773,"name":"Berserker ring (i)","quantity":1,"fuzzy":false},{"id":22945,"name":"Rada\u0027s blessing 3","quantity":1,"fuzzy":false}],"rune_pouch":[{"id":561,"name":"Nature","quantity":100,"fuzzy":false},{"id":554,"name":"Fire","quantity":500,"fuzzy":false},{"id":-1,"name":"","quantity":0,"fuzzy":false}],"additionalFilteredItems":{"4162":{"id":4162,"name":"Rock hammer","quantity":1,"fuzzy":false},"19634":{"id":19634,"name":"Soul bearer","quantity":1,"fuzzy":false},"9811":{"id":9811,"name":"Farming cape(t)","quantity":1,"fuzzy":false},"9813":{"id":9813,"name":"Quest point cape","quantity":1,"fuzzy":false},"13116":{"id":13116,"name":"Bonecrusher","quantity":1,"fuzzy":false}},"name":"Slayer Melee Prayer","notes":"","highlightColor":{"value":-16711869,"falpha":0.0},"highlightDifference":true,"filterBank":true,"unorderedHighlight":false,"spellBook":0}
3. See error

Unfortunately, I can't purposefully reproduce this bug. It seems to only happen once after logging in for the first time each day.

**Expected behavior**
The game doesn't crash.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.8.1
 - Launcher version: 2.1.8
 
**Additional context**
I have two separate logs of this event occurring, one from May 19th and one from May 22nd. Each one has the same problematic frame:

# Problematic frame:
# J 10702 C1 net.runelite.api.Item.getId()I (5 bytes) @ 0x03f75adb [0x03f75ac0+0x1b] 

May 19th: 

[hs_err_pid2792.log](https://github.com/runelite/runelite/files/6527174/hs_err_pid2792.log)

May 22nd:

[hs_err_pid1188.log](https://github.com/runelite/runelite/files/6527175/hs_err_pid1188.log)

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
