### ISSUE TITLE
Friend highlight on minimap/over head

### ISSUE THREAD

**Issue by ImCOTW** [runelite/runelite#13634]
Ability to have your friends be highlighted on your friends list regardless if theyre online or not. Osbuddy has this plugin and it's the only deal breaker for me switching to runelite and those pk clients are sketchy af. 

Raggers are aids to deal with pking so it would be nice to know when they come into wildy so i can pray before they rag me.

**Comment by Nightfirecat** [comment]
This is one of the features we are not considering, [per our rejected features list](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#not-currently-being-considered):

> Highlighting "Offline" Friends (and generic player highlighting): Not included to respect players with their messaging mode set to Private and to avoid harassing players (see #951)
