### ISSUE TITLE
Add Clan/Visited Clan 'Player Indicators'

### ISSUE THREAD

**Issue by TheAdmired** [runelite/runelite#13639]
**Is your feature request related to a problem? Please describe.**
Not really related to a problem of any kind.

**Describe the solution you'd like**
Overhead names/configurable colors for players in your Clan/Visited clan (if possible for the latter)

**Additional context**
Primarily just wanting it for the names drawn on map, as their default orange isn't too friendly with my colorblindness

**Comment by Hydrox6** [comment]
We're keeping track of clan update issues like this in #13644
