### ISSUE TITLE
Clans update mega-issue

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#13644]
For the sake of organisation, all issues relating to the clans update changes are going to be catalogued here.

- [x] `Chat Colours` for the new channels (messages, channel name, usernames) (0f0d3de)
- [x] `Chat Commands` support in the new channels (and all other RL-controlled `!` commands) (5bd8932)
- [x] `Chat Notifications` support in the new channels (fbd0b57)
- [x] `Player Indicators` options for clan chats including icons for the minimenu (7de3b61)
- [x] `Skybox` colour for the clan hall (#13640)
- [x] `Chat Filter` support for the new channels (5f9ccd2)
- [x] `Emoji` support for the new channels (6957cea)
- [x] `World Hopper` `Hop-to` option for clan chat and guest chat (1c75a97)
- [x] An equivalent of the `Friends Chat` plugin for clans and guest clans&mdash;particularly the "Recent Chats" and "Confirm Kicks" features
- [x] `Chat Timestamps` for the new channels (#13635)

**Comment by RuneLogApp** [comment]
FYI chat timestamps are also missing from Clan chat messages, but have continued to work for Friends Chat messages.
