### ISSUE TITLE
Menu Entry Swapper Suggestion - Add Item Swap for Imcando Hammer (Use/Wield)

### ISSUE THREAD

**Issue by jcblomquist** [runelite/runelite#13655]
Issue:
The Imcando Hammer can be used to replace a regular hammer in all cases where a hammer is required in game. Some of these cases require the hammer to be used on an item in the inventory to operate (e.g. cracking open infernal eels or coconuts) rather than having it equipped or just in the inventory (e.g. smithing or construction)

Solution:
Provide an option under "Items Swaps" for swapping "Use" and "Wield" on the Imcando Hammer, so the left-click option can be "Use" by default.

Additional thoughts:
You can work around this today by using the customizable shift-click feature, but it would be nicer if shift-click was not required.

**Comment by Nightfirecat** [comment]
Why would you use an Imacndo hammer instead of a normal hammer for these activities?

**Comment by jcblomquist** [comment]
Hmm, I don't have a good answer for that other than "because you can", it looks cooler and it eliminates the need to keep a normal hammer I guess.

**Comment by Nightfirecat** [comment]
8944eb9be6d62ec8384e29484dab14c4c2858d9d was added to master, which sufficiently covers this use case.
