### ISSUE TITLE
Login Screen Stretched Bug

### ISSUE THREAD

**Issue by bmcdaniel94** [runelite/runelite#13659]
I noticed a weird bug that has happened recently.
For whatever reason when I start runelite with stretched mode enabled it doesn't apply the stretch correctly even though I can click on where the volume button would be if it correctly stretched at login screen.

See Image:
![image](https://user-images.githubusercontent.com/74314281/120060389-345c9780-c01d-11eb-9a2b-b15166da956f.png)

Here is a gif showcasing the bug in acton:
![Stretched Bug 5-29-21](https://user-images.githubusercontent.com/74314281/120060424-71288e80-c01d-11eb-8533-15cd11851205.gif)

Things I have tried:
1.) Making sure windows doesn't have any DPI scaling set
2.) Going To the .exe and Checking the box that says Disable Fullscreen Optimizations
3.) Change High DPI -> override scaling peformed by System.
4.) Downloading the 64bit version.

I would like to add this same issue is happening on my Manjaro Linux installation as well.

OS: Windows 10.19042.985
RuneLite version: 1.7.10
Launcher version: 1.6.0

**Comment by Hannah-GBS** [comment]
The volume button's clickbox is actually the entire area between the visible icon and the bottom right of the game window.

**Comment by bmcdaniel94** [comment]
Okay, but why isn't it stretching the full size of the window like it always has?

**Comment by Hannah-GBS** [comment]
It's affected by your "Resizable Scaling %" config in the Stretched Mode Plugin. This has had no recent behaviour changes as far as I know.

**Comment by bmcdaniel94** [comment]
I haven't changed any settings and I've always had no boxes checked along with base 50% resizable scaling. The login screen has always auto matched the size of the window (no black space). It only happened recently with the latest update of runelite

**Comment by bmcdaniel94** [comment]
I found the solution. When I go in-game and set the game to FIXED everything goes back to normal on ANY OS like the screenshot above. If you set the resolution in-game to be RESIZABLE it will result in bug related.
