### ISSUE TITLE
Player Indicator plugin Highlighting when use bug

### ISSUE THREAD

**Issue by Thomas-Famularo** [runelite/runelite#13658]
**Describe the bug**
The Player Indicator plugin is highlighting and putting the rank next to the name of the item and not the player when an item is used and right-clicked on a player.

**To Reproduce**
1. Turn on the Player Indicator plugin for Friends, Friends Chat, Team Members, or Clan Members.
2. Use an Item and right-click a player.
3. See error with rank and highlighting item and name of the player

**Expected behavior**
Highlight and put rank next to the name of the player and not the item being used.

**Screenshots**
![Runelite Player Indicator bug](https://user-images.githubusercontent.com/21990858/120053353-a8844480-bff7-11eb-8003-aa8b7a3e260a.png)

**Environment (please complete the following information):**
 - OS: Windows 10.0.1.19041
 - RuneLite version: 1.7.10
 - Launcher version: 1.6.0

**Comment by Adam-** [comment]
fixed in 264822e9715ca66f25b768b813770fd09ccdc6e8
