### ISSUE TITLE
Bad medium clue helper

### ISSUE THREAD

**Issue by tgeene** [runelite/runelite#13666]
**Describe the bug**
Instructions for coordinate clue "07 degrees 05 minutes north 30 degrees 56 minutes east", give the wrong fairy ring code.

**Expected behavior**
Should say BIP not BKR

![image_2021-05-30_100724](https://user-images.githubusercontent.com/2043140/120113335-d5874300-c12e-11eb-8a5b-5a0e2725c273.png)

**Comment by Adam-** [comment]
The wiki seems to disagree with you on where that clue is located - 
![image](https://user-images.githubusercontent.com/309739/120113572-0f654300-c149-11eb-87d5-3e0e6aa38852.png)

**Comment by tgeene** [comment]
> The wiki seems to disagree with you on where that clue is located -
> ![image](https://user-images.githubusercontent.com/309739/120113572-0f654300-c149-11eb-87d5-3e0e6aa38852.png)

Seems the wiki is wrong too. Feel free to go to BKR and tell me how that goes.

**Comment by Nightfirecat** [comment]
The wiki and clue text aren't wrong. BIP is close to the clue, but BKR is closer.
