### ISSUE TITLE
Multicombat world map overlay

### ISSUE THREAD

**Issue by Hjaldr** [runelite/runelite#13668]
Could a toggle be added that overlays a transparent box over all tiles that are multi-combat in the worldmap? This would be very useful to figure out which areas require extra caution on low level accounts.

**Comment by Hydrox6** [comment]
Banned by the [Jagex Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1):
> Indicates multicombat zone boundaries
