### ISSUE TITLE
Twitch Plugin not integrated with new Clan System

### ISSUE THREAD

**Issue by MoistGrandpa** [runelite/runelite#13677]
I would just like to briefly point out that the Twitch plugin needs to be updated to support the new clan system;

Previously, one would type "//" before their message to have it sent to the Twitch channel. That function is now reserved for Clan Chat. 

I believe it would be a quick fix.

Thank you for all your continued hard work

**Comment by Adam-** [comment]
This was already changed to `/t` as is stated here https://runelite.net/blog/show/2021-05-28-1.7.10-Release
