### ISSUE TITLE
update

### ISSUE THREAD

**Issue by KingCraftyxix** [runelite/runelite#13671]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by KingCraftyxix** [comment]
Runelite will not update

To Reproduce:

Open Runelite and login
![image](https://user-images.githubusercontent.com/85128698/120226861-0c845400-c216-11eb-81af-f2c752fdda31.png)

**Comment by Nightfirecat** [comment]
Please join the `#support` channel of our Discord server: https://runelite.net/discord
