### ISSUE TITLE
After logging in, ALL my settings were reset

### ISSUE THREAD

**Issue by 3ICE** [runelite/runelite#13682]
Hi, I spent several hours configuring RuneLite to my liking. (Yes, by going through every single option one by one.) Plus installing several dozen new plugins and turning half of the built-in ones off, marking tiles and monsters, moving around UI elements so they fit just right, setting my skill goals, etc. (My .runelite folder is over 200MB now.) 

Once I was satisfied with the entire setup, I decided to save my settings by logging in to my Google Account. Or so I thought... Because to my absolute devastation, my client froze (I was in combat too!) and after a bit of waiting I was presented with a reset to the default installation. None of my settings survived (except marked mobs for some reason.)

**To Reproduce**
1. Install RuneLite as a new user
2. Configure everything
3. Log in to (a never before used!) Google Account
4. See all your stuff get reset to default

**Expected behavior**
My settings should save to Google, not reset!

**What happens instead**
A brand new, empty profile is "downloaded" from Google, overwriting my hard-earned, but apprently guest-only settings.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.10
 - Launcher version: 2.1.7

--3ICE

**Comment by Hydrox6** [comment]
https://github.com/runelite/runelite/wiki/Account#sync-local-settings-to-your-remote-runelite-account

**Comment by 3ICE** [comment]
I found and pressed that button several times.
