### ISSUE TITLE
Kingdom plugin sometimes shows up outside of Miscellania when Show Only in Kingdom is enabled

### ISSUE THREAD

**Issue by sanderdegroot** [runelite/runelite#1368]
**Steps to reproduce**
1. Enable the Kingdom of Miscellania plugin
2. Enable the Show Only in Kingdom configuration setting
3. Enable the Show When Low Favor or Coffer configuration setting
4. Set the Alert if favor % below or Alert if coffer below settings to a value greater than your current Kingdom favor % or coffer amount

The Kingdom of Miscellania plugin will now appear while your character is not within the Kingdom of Miscellania region. Given the wording of the Show Only in Kingdom setting, one would expect the plugin to never appear if the character is not physically in the Kingdom if this setting is enabled.

**Suggested Fix**
The logic should be changed such that if Show Only in Kingdom is enabled and the character is not within the Kingdom of Miscellania region, the plugin is not shown.

**Comment by Adam-** [comment]
The misc plugin does not work correctly when you are too far away from the kingdom. I think it is due to the server not sending the varbit information? We have disabled the plugin by default now due to this, I think it needs to be reworked to probably only show the infobox when in the kingdom. cc @Infinitay

**Comment by Infinitay** [comment]
> I think it is due to the server not sending the varbit information

Correct

> I think it needs to be reworked to probably only show the infobox when in the kingdom

Been busy with school lately, I have 3 exams next week so I've been studying, but then again it's fairly simple so no clue why I haven't done it yet. I'll get to it as soon as I can, sorry.

**Comment by deathbeam** [comment]
The option for displaying the overlay outside of kingdom was removed.
