### ISSUE TITLE
Clan List Exporter

### ISSUE THREAD

**Issue by tannerdino** [runelite/runelite#13686]
Export your clan members list into a text file, much like the friends list exporter.

**Comment by fatfingers23** [comment]
Hey! My plugin takes care of this. Not to a file but to clipboard. It can export usernames, ranks, and joined date
https://runelite.net/plugin-hub/show/clanmate-export

There is also this one that exports just names.
https://runelite.net/plugin-hub/show/copy-clan-usernames
