### ISSUE TITLE
Chat Color Plugin Bugged

### ISSUE THREAD

**Issue by deeOSRS** [runelite/runelite#13700]
Since clan system update, the chat color plugin has guest and chat channel options added, but it seems they're not properly separated. When changing the settings in clan chat, friends chat, and guest chat, resetting them or changing colors changes some existing settings and in some cases doesn't successfully change the color at all. 

**To Reproduce**
Add colors for transparent chatbox settings in Chat Color (I imagine opaque is the same though), and reset the colors. They'll reset other settings or change colors without you having done it. Friends chat, clan chat, and guest chat are the ones I'm noticing with issues overlapping one another. Resetting clan chat settings will sometimes reset friends chat settings, as shown in the first gif, and the same with guest etc.

**Expected behavior**
The chat settings to be able to be changed separately and to actually function in changing the chat colors, not defaulting to the previous color and not actually changing due to this bug.

https://user-images.githubusercontent.com/85454054/120934761-b14ad980-c6cd-11eb-8a4d-0677bfd5ca4b.mp4

https://user-images.githubusercontent.com/85454054/120934775-b7d95100-c6cd-11eb-8873-ef3a02ca5de1.mp4

**Environment**
 - OS: Windows
 - RuneLite version: 1.7.11.1
 - Launcher version: 2.1.3

**Comment by Adam-** [comment]
I think this is fixed in 3f7146a6c2c6cd8a82f86aa8723991b3d7863d37
