### ISSUE TITLE
Allow the player to change the colours used in the Inventory Grid plugin

### ISSUE THREAD

**Issue by HalfOfAKebab** [runelite/runelite#13705]
**Is your feature request related to a problem? Please describe.**
I think the grid is too bright, it's distracting and can make it harder to see where I'm dragging things.

**Describe the solution you'd like**
I would like to be able to change the hex colour of the grid (both the white one and the green one), much like you can with other plugins.

**Describe alternatives you've considered**
I don't think there are any alternatives.

**Comment by LlemonDuck** [comment]
Already implemented in #9021, and doesn't even require a rebase despite its age!
