### ISSUE TITLE
Chat Color Plugin Still Bugged

### ISSUE THREAD

**Issue by deeOSRS** [runelite/runelite#13707]
**Describe the bug**
Certain settings aren't being controlled individually. I opened this issue yesterday and saw it was fixed, but I checked today and it still wasn't working properly.

**To Reproduce**
Change settings and check if they're controlled individually. From what I can tell it's mainly highlighted options if not exclusively. I use the transparent settings, I assume the same issues apply to opaque.

**Expected behavior**
Each setting to change color individually and successfully change the chat color, neither of which are happening for certain settings.

https://user-images.githubusercontent.com/85454054/121121775-3af1c880-c7ee-11eb-968c-68653a849b7a.mp4

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.11.1
 - Launcher version: 2.1.3

**Comment by Nightfirecat** [comment]
It is fixed on the master branch, which is not yet released. In our next release you will find it available.
