### ISSUE TITLE
Twitch chat after clan update

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#13713]
When using the "Twitch" plugin, it's setup to use "//" as the prefix which as of the clan update is used for clan chat messages. Attempting to send a message to a twitch chat gives a "You are not chatting in the channel of your own clan at the moment" but messages can be received normally in the Channel tab
Worth noting that I'm not in a clan so I can't test if it works while in one.

**Comment by Adam-** [comment]
duplicate of #13677
