### ISSUE TITLE
MSAA Glitch

### ISSUE THREAD

**Issue by Wave214** [runelite/runelite#13710]
When i activate "Anti Aliasing", the top and the right side of the game glitches out, like seen in the Screenshot. Its only with Anti aliasing.

**To Reproduce**
1. Go to 'GPU'
2. Click on 'Anti Aliasing'
3. Scroll down to 'MSAA x2 or Higher'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: newest
 - Launcher version: newest
![bug](https://user-images.githubusercontent.com/85584860/121247811-f5430780-c8a2-11eb-897e-3018622bfdde.png)

**Comment by Wave214** [comment]
disabled hardware acc. deinstalled river tuner. nvidia controle panel enhance modus etc, all not working

**Comment by Nightfirecat** [comment]
Please post your client logs.

**Comment by Wave214** [comment]
[client - Kopie.log](https://github.com/runelite/runelite/files/6619416/client.-.Kopie.log)
[launcher - Kopie.log](https://github.com/runelite/runelite/files/6619417/launcher.-.Kopie.log)

**Comment by Wave214** [comment]
[launcher - Kopie.log](https://github.com/runelite/runelite/files/6619439/launcher.-.Kopie.log)

**Comment by Wave214** [comment]
[client - Kopie.log](https://github.com/runelite/runelite/files/6619441/client.-.Kopie.log)

**Comment by Adam-** [comment]
Your logs show you are not (or were not?) using RuneLite, so I have no interest in looking into this much further. And anyway I can't do much if I can't reproduce it myself.
