### ISSUE TITLE
Add dragon hunter lance to bank tags icons

### ISSUE THREAD

**Issue by zang227** [runelite/runelite#13724]
**Is your feature request related to a problem? Please describe.**
I'd like the dragon hunter lance icon to be added so to make it easier for me to discern my vorkath melee and vorkath range tags.

**Describe the solution you'd like**
 dragon hunter lance icon

**Describe alternatives you've considered**
I could use a different icon but would prefer the dhl

**Additional context**

**Comment by Hydrox6** [comment]
The lance already exists as an icon. Members items cannot be selected on F2P worlds as they are all named `Members object` by the game. Similar to #13282
