### ISSUE TITLE
Chat does not work

### ISSUE THREAD

**Issue by Toxic-Coast** [runelite/runelite#13720]
**Describe the bug**
Chat and chat bubbles do not display, no idea on how it works.

**To Reproduce**
This bug happened once I enabled a few things, this being Chat Timestamps, Stretched Mode, as well as transparent chat. These are the three things I enabled and this has caused the chat to not work, I am not sure of the specific type of issue.

**Expected behavior**
I am ill sure of how this happens, but it may be something that messes up the chat in some manner.

**Screenshots**
https://gyazo.com/c48502e18a011dd56ac46cf1fb19239c

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.11.2
 - Launcher version: 2.16

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
