### ISSUE TITLE
Recoloring of "Options Menu" (right click)

### ISSUE THREAD

**Issue by zeroliter** [runelite/runelite#13732]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

My issue: I have a color blindness with yellow on white. When you want to click follow/Attack/etc the white changes to yellow. I barely can see the diffrence.

**Describe the solution you'd like**
It would really help if there was a option that vanilla doesnt have to change the yellow highlight in the option menu (see image, Not the monster)
![Desktop Screenshot 2021 06 13 - 12 29 37 14 (2)](https://user-images.githubusercontent.com/85831733/121807799-f931a980-cc55-11eb-95eb-3e7c4f5cace2.png)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

There is none

**Additional context**

**Comment by Hydrox6** [comment]
`Inteface Styles` has the option `High Detail menu` that does this 
![image](https://user-images.githubusercontent.com/2979691/121807892-faf76f00-cc4d-11eb-88c6-edfe0a4499d0.png)

**Comment by zeroliter** [comment]
Exactly what i am looking for!
