### ISSUE TITLE
Left Click Repair for POH Armour Repair Stand

### ISSUE THREAD

**Issue by liosrakia** [runelite/runelite#13753]
I've always been confused why I have to use my armor on the repair stand, instead of simply having a "repair" left-click that takes you to the armor repair menu. It's even more strange (in my mind) considering every other feature of the Workshop is a left-click...including the  verrry functional helmet pluming stand.

Adding a left click that takes you to that menu would be a great solution. Perhaps there is a way to simulate "I used an armor piece" on the repair stand. Note that there are is a secondary menu if the item used is already repaired. 
![cannot be repair](https://user-images.githubusercontent.com/48603673/122440017-0352f100-cf51-11eb-84d8-c494c8a913d8.PNG)

As the action is so simple, I don't believe there are any alternatives to this, although a right-click repair could also work. 
![make helmet](https://user-images.githubusercontent.com/48603673/122439749-c38c0980-cf50-11eb-9c1c-0c26b4f7059f.PNG)
![repair stand](https://user-images.githubusercontent.com/48603673/122439753-c424a000-cf50-11eb-94cc-4ab951647083.PNG)

**Comment by Hydrox6** [comment]
Banned by the [Jagex Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1): `Any addition of new menu entries which cause actions to be sent to the server`

**Comment by liosrakia** [comment]
Well, that's why I asked! Onwards, to twitter. :)
