### ISSUE TITLE
Menu Entry Swapper Suggestion: Allow configuring the left click of box traps

### ISSUE THREAD

**Issue by Marcarrian** [runelite/runelite#13755]
**Is your feature request related to a problem? Please describe.**
When using the Menu Entry Swapper Plugin the "reset" option becomes the left click on a box trap, that caught something.
This is frustrating when doing 3t hunter where the ideal left click option would be the default one. This leade me to disable the Menu Entry Swapper Plugin as a whole when doing that hunter method.

**Describe the solution you'd like**
A simple toggle to swap the "reset" and "check" options. The plugin also swaps the menu entries for collapsed box traps, making the "lay" option the left click option. I wish that the toggle has the effect on both scenarios that I've mentioned.
Meaning with the toggle **on** the left click options would be as follow:
Box traps that caught something: "check"
Collapsed box traps: "take"
The default option of the toggle should be **off**.

**Describe alternatives you've considered**
One alternative is to provide two toggle options. One for box traps that have caught something and one for collapsed box traps.

**Comment by Alexsuperfly** [comment]
just disable the reset option

**Comment by Hydrox6** [comment]
This is already in the client, as Alex has said
