### ISSUE TITLE
Display East or West on the USA world flags

### ISSUE THREAD

**Issue by FungiRS** [runelite/runelite#13756]
Add an E or W to the USA world flag in the world hopper to show whether a world is east or west coast.

**Comment by geheur** [comment]
related: https://github.com/melkypie/ClanChatCountryFlags/issues/2 (same request but for a hub plugin).

**Comment by geheur** [comment]
![flag_us_east_red_side](https://github.com/runelite/runelite/assets/41499327/7974298a-74be-4413-a68e-3e7a74ef21b2)
![flag_us_west_blue_side](https://github.com/runelite/runelite/assets/41499327/e6fff808-15a3-4c49-8a12-3da428be97aa)
I made some icons that don't look too bad in the world hopper and look similar to the icons jagex has chosen for their world hopper.
![image](https://github.com/runelite/runelite/assets/41499327/fb853afe-f43d-4b52-acbd-25e68e28bf0a)

**Comment by Adam-** [comment]
added in a4c8654c6cf22541d7b972615b8e37c14767a4eb
