### ISSUE TITLE
Alch Profit tooltip

### ISSUE THREAD

**Issue by TheeWiki** [runelite/runelite#1375]
Would be neat to preview a simple line dialogue in the tooltip indicating the profit or lose when hovering over an item to alch, also includes the value of a nature rune as well btw so it's more clear on the actual profit if alched).

(red gp value = lose, green = gain)
https://i.imgur.com/z4ruYPc.png

**Comment by ShaunDreclin** [comment]
Related issues: #1094 #1075

**Comment by deathbeam** [comment]
Duplicate
