### ISSUE TITLE
Redwood Click Box

### ISSUE THREAD

**Issue by PoopCrusher** [runelite/runelite#13752]
Redwood chopping is supposed to be the easiest most AFK woodcutting after reaching 90. I believe a great improvement can be made to the 'Show Redwood Trees' option in the Woodcutting settings.  Right now it is a dragon axe overlay on the spot ready to chop but the clickbox to actually chop the tree does not line up with this dragon axe icon.

I would like to see an improvement of the dragon axe icon to match the 'Chop Redwood" option of the tree. Alternatively, I think we would benefit from a clickbox outline highlighter that is green when redwood section is ready to chop and red when that particular redwood section is down. This clickbox and highlight would be very similar to the 'Show conveyor belt clickbox' and 'Show bar dispenser clickbox' that is currently used for the Blast Furnace.

Any and all help are suggestions are appreciated. Thank you!

**Comment by Hydrox6** [comment]
This can already be done with the `Object Markers` plugin. Either render option will work sufficiently, and different colours can even be applied with the `Remember color per object` option.
