### ISSUE TITLE
Book of the Dead menu entry swap

### ISSUE THREAD

**Issue by Foomanty** [runelite/runelite#13760]
I’d like a menu entry swap for the newly released item “Book of the Dead”

It would be nice to left click as equip instead of reminisce. 

It’s a +6 magic attack offhand item that would be useful to any low/med level iron without a better offhand. It’s also required for the use of thralls. 

Thanks

**Comment by Adam-** [comment]
They've already said they're changing it next week https://secure.runescape.com/m=news/a-kingdom-divided?oldschool=1
