### ISSUE TITLE
Clue scroll helper doesn't show anything for a clue in Forthos Dungeon

### ISSUE THREAD

**Issue by sampotato12345452** [runelite/runelite#13766]
**Describe the bug**
Clue scroll plugin doesn't tell the location of the clue "Dig in the lair of red wings, within the temple of the Sun and Moon."

**To Reproduce**
Open that clue and nothing will pop up.

**Expected behavior**
A pop up should appear that says the clue is in Forthos Dungeon and to bring a spade and when in Forthos Dungeon there should be a highlighted tile that shows where to dig.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.12
 - Launcher version: 2.1.0

**Comment by Nightfirecat** [comment]
This is already fixed in b7cbdcdf51ac9acbad0812b61c46fa380b99c16c and will be available in the client as of our next update.
