### ISSUE TITLE
Camera Plugin : Preserve pitch on compass look not working

### ISSUE THREAD

**Issue by Najo-z** [runelite/runelite#13774]
**Describe the bug**
After this morning's update, the "Preserve pitch on compass look" option has no effect, whether enabled or disabled. The camera will still reset to a horizontal view after looking any direction.

**To Reproduce**

1. Activate the Camera plugin and toggle the "Preserve pitch on compass look" option
2. Set the camera to a clear vertical angle
3. Right Click the compass and select any "Look *" option

**Expected behavior**
The camera vertical angle doesn't change, only the cardinal direction.

**Resulting behavior**
The camera vertical angle is reset to a horizontal value.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.12
 - Launcher version: 2.1.6

**Comment by Hydrox6** [comment]
Wait for the update
