### ISSUE TITLE
Runelite closed without any warning

### ISSUE THREAD

**Issue by iquicksnipe** [runelite/runelite#13771]
**Describe the bug**
I was playing for a few minutes and my client crashed randomly. No warning, no error, no confirmation, nothing.

**To Reproduce**
Not sure of the steps to reproduce. I was logged in and running, talking to my cc, and then runelite vanished.

**Expected behavior**
The game to not crash.

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - RuneLite version: [1.7.12]
 - Launcher version: [1.6.0]

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
