### ISSUE TITLE
Collection Log Screenshot Delay

### ISSUE THREAD

**Issue by mumbomination** [runelite/runelite#13789]
For the screenshot function, there's an option to take a screenshot when you get an item for your collection log. I think there should be an option to delay this screenshot for a second or two so it syncs up with the collection log screen pop-up for those who have that turned on.

**Comment by Nightfirecat** [comment]
I've implemented most of the checking needed for this here: https://github.com/Nightfirecat/runelite/commits/notification-callback

For collection log slots, it logs the following:

```
2021-08-04 23:13:01 [Client] DEBUG n.r.c.p.screenshot.ScreenshotPlugin - Client tick is: 53
2021-08-04 23:13:01 [Client] DEBUG n.r.c.p.screenshot.ScreenshotPlugin - Top text: Collection log
2021-08-04 23:13:01 [Client] DEBUG n.r.c.p.screenshot.ScreenshotPlugin - Bottom text: New item:<br><br><col=ffffff>Chompy bird hat</col>
```

For queued notifications, it sends log messages for each successive notification once it has fully opened, so it's possible that they could be delayed by a significant amount if many are queued. (such as for certain collection log entries, or for certain combat achievement tasks) As such, we're not certain that we'll be implementing this feature. If we do, the linked branch should be used as a starting point, already containing the majority of the needed implementation.
