### ISSUE TITLE
Fishing Plugin Located under Chat in Tempoross

### ISSUE THREAD

**Issue by uhFuzu** [runelite/runelite#13783]
When fighting tempoross the Fishing and Cooking Plugin show up in under the chat making them useless. Turning the plugin off then on during the fight also doesn't make a difference.

OS: Windows 10
![TemporossChatIssue](https://user-images.githubusercontent.com/82410509/123325855-6edc2600-d530-11eb-8f41-b4f1ad4327d2.png)

**Comment by Hydrox6** [comment]
move them by alt dragging them

**Comment by Hydrox6** [comment]
after getting a simultaneous report about a different Tempoross issue, it seems the two are linked. Jagex changed around a load of interfaces in the last update, which resulted in a load of our custom stuff breaking. One of those changes made the wrong widget be movable, which could in theory cause this. Either way, this is now known, I have a fix, and it'll be in the next update
