### ISSUE TITLE
Left Click Banker

### ISSUE THREAD

**Issue by cuzzbaby** [runelite/runelite#13781]
I saw a post from 2018 of someone asking for a 1 click on banks and ge to instantly bank but, that extension is no longer on Runelite. Is there an other way to enable this? Because coming from OSbuddy where that's the default to having to remember right click first is really annoying.

**Comment by Nightfirecat** [comment]
This hasn't been removed from RuneLite, it still exists in the Menu Entry Swapper plugin.

**Comment by cuzzbaby** [comment]
![image](https://user-images.githubusercontent.com/77865382/123299853-8c34d400-d4df-11eb-9c28-bf157e14f47c.png)


> This hasn't been removed from RuneLite, it still exists in the Menu Entry Swapper plugin.

This is the only one I see. This is part of Menu Swapper Extented. For my plugins there is no Menu Entry Swapper.

**Comment by cuzzbaby** [comment]
You know what I see it now. Sorry. i was looking in the plugins and not in the default ones.

**Comment by Nightfirecat** [comment]
`Menu Entry Swapper` is a main client plugin, not a hub plugin: https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper
![mes-bank-swap](https://user-images.githubusercontent.com/2199511/123300350-09753e80-d50a-11eb-8429-4d8daab1c80a.png)
