### ISSUE TITLE
BankTags PVM starter tabs

### ISSUE THREAD

**Issue by bugabuse** [runelite/runelite#13796]
BankTags plugin doesn't have any usable pre-configured tabs.

Would be great to have pre-configured templates for pre-built tabs (pk, pvm, etc).
side note: Ideally we'd support item substitution (ie Occult necklace 12002 OR Occult necklace (or) 19720)

Pulled data from bestinslot.com and populated a PVM template.
Attached the banktags config from settings.properties file with 37 PVM tabs containing mostly BiS items.

[settings.properties.txt](https://github.com/runelite/runelite/files/6721729/settings.properties.txt)

**Comment by Hydrox6** [comment]
This can already be done with bank tag importing. See the `#bank-tags` channel in the Discord server.

**Comment by hex-agon** [comment]
Bank tabs can be easily imported/exported by right clicking the + icon or the relevant bank tab:

![image](https://user-images.githubusercontent.com/4876366/123548726-66f0d180-d73c-11eb-9747-e8f63f796888.png)

Adding presets is not something ideal because we shouldn't assume that everyone is gonna be a maxed main pvmer.

**Comment by bugabuse** [comment]
right.  the same argument is made for those pre-configured tabs from discord.  
we can't really expect people to have the same gear so having substitution support would allow us to share pre-configured setups without much of an issue.

**Comment by Hydrox6** [comment]
we already have item variation support, which is what you asked in the original post
for different tiers of gear, make a writeup for your setup and provide multiple tiers of setups at different levels. The wiki already does this in strategy guides, and it's not something the client should need to be aware of.

**Comment by bugabuse** [comment]
I see it. VAR_TAG_SUFFIX.  missed that one.

so having pre-configured/starter tabs baked into the plugin isn't of interest?
the import/export is crude at best.

**Comment by Hydrox6** [comment]
Not sure how endgame PVM tags are considered "starter". and like I said, it's already possible with bank tag importing, which is a much better and less crude solution than trying to cram a load of tags into the client that the majority of the playerbase either don't need initially, or will never need.

**Comment by bugabuse** [comment]
i see the confusion. "starter" in this context doesn't exactly imply TTL.  next time i'll be really clear.
i suspect the lack of analytics is really to blame here but i suspect there is common base-config that would be useful.
we have common PK setups, etc.  just seems like a useful feature to have something baked into the plugin .vs blank config.
