### ISSUE TITLE
add "stay on top" (sticky) button to client

### ISSUE THREAD

**Issue by impotkid** [runelite/runelite#13790]
**Is your feature request related to a problem? Please describe.**
Sometimes you wanna watch a video or a movie on netflix in fullscreen or w/e and i'd be nice to have to ability to make the runelite client stay "above" the fullscreen so you can push it halfway in the corner so that it doesn't obstruct the movie too much and you can still see the game

**Describe the solution you'd like**
Add a "sticky" button on the client frame that'll make the client always stay on top of all the other windows & in fullscreen mode

**Describe alternatives you've considered**
There exist third party tools to make windows always stay on top but this functionality would be nice to have built into the client itself

**Additional context**
Please and thank you.

**Comment by Hydrox6** [comment]
This is already a thing

`RuneLite` -> `Always on top`

**Comment by impotkid** [comment]
i dont see it
where is the option to toggle it on

**Comment by impotkid** [comment]
nvm i found it!
