### ISSUE TITLE
Add cooldown timer for Death's Charge spell

### ISSUE THREAD

**Issue by Nilhilo** [runelite/runelite#13793]
With A kingdom Divided came new spells in the Arceuus spellbook.
Death's Charge effect has a duration of 0.6 x magic lvl, which comes down 60 seconds at 99 magic. The effect ends when you kill a monster. As a result you will gain spec energy.
The spell also has a fixed cooldown of 60 seconds.

Currently Runelite shows a timer for when the effect of Death's Charge ends. This timer is removed when you kill a monster as you have triggered the spec energy gain.

However there is no timer that shows the cooldown of the spell.
This information is arguably more important. Not having this info at a glance means having to go to the spell book multiple times to check if the cooldown has ended.

A timer should be added for the cooldown of Death's Charge.
Ideally it would be implemented in the following way:

- If the magic lvl of the player is 99 > Display a timer of 60 seconds, do not remove timer when a monster is killed. As the effect duration is equal to the cooldown timer at 99.
- If magic lvl below 99 > Display two timers; one for the effects duration ( 0.6 x magic lvl) and one for the spell's cooldown (60 seconds)

I have did a few tests using a stopwatch. The effect's duration uses the player's actual magic level. Brewing your magic stat down or increasing it with imbued heart does not decrease or increase the duration of Death's Charge effect.

![image](https://user-images.githubusercontent.com/86553685/123541169-5e4fc980-d743-11eb-8639-39232b982bf5.png)

**Comment by Hydrox6** [comment]
This is already a feature. Look at the settings for the `Timers` plugin
