### ISSUE TITLE
Birdhouse left-click Empty.

### ISSUE THREAD

**Issue by toetsenbord** [runelite/runelite#1379]
Hello, a menuswap to left-click Empty birdhouses would be nice. Current left click `option` is Interact.
![74ad61f897a3be61850fff14ecce919f](https://user-images.githubusercontent.com/38295787/38635006-618c477a-3dc4-11e8-8f3f-350c5587e3a7.png)

**Comment by SlLVERKlNG** [comment]
Would very much like to see this menuswap option!
