### ISSUE TITLE
Menu Entry Swapper Suggestion: fill - empty options essence pouch

### ISSUE THREAD

**Issue by Jan-Willem-Dev** [runelite/runelite#13799]
When the bank interface is open make the default left-click the fill option instead of 'deposit 1' for essence pouches and otherwise make the empty option the left-click default option. This could make rune crafting a tiny bit easier.

**Comment by Hydrox6** [comment]
This is already a feature.

`Menu Entry Swapper` -> `Bank Deposit Shift-click`
