### ISSUE TITLE
Popover direction in magic spell book

### ISSUE THREAD

**Issue by LeonBeilis** [runelite/runelite#13808]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
1. change spell book to arceus
2. Click on the magic spellbook icon 
3. turn on filter > show utility spells
4. hover the third row of icons
5. See error

**Expected behavior**
The popover should change the direction and show it above the game description box

**Screenshots**
![image](https://user-images.githubusercontent.com/13499652/123961306-e094f380-d9b8-11eb-89c8-2de0c5ed7d7c.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.14
 - Launcher version: 2.0.2

**Additional context**
I know its a really minor bug but if it not hard please fix it or direct me to how and I'll make a pull myself

**Comment by Hydrox6** [comment]
This isn't a bug or error, this is just down to how two different systems collide. Both are doing their job as expected, and tbh there's not really much that needs to be done here. There's also already an option to disable the tooltips specifically on the spellbook, probably to bypass this exact issue.
