### ISSUE TITLE
duel request & trade request notification/alert

### ISSUE THREAD

**Issue by JOMYGOD** [runelite/runelite#1380]
Could an alert be added for when you get a duel request or a trade request? 

A windows tray notification with the little sound :)

tytyty

![b47a119c2e877261370bcc8fb4d6b526](https://user-images.githubusercontent.com/38295978/40435634-fd30d1dc-5ea8-11e8-9de8-a04c1f969cf8.png)

**Comment by TheLonelyDev** [comment]
Would something along the lines of this meet the description?

![image](https://user-images.githubusercontent.com/8240706/38828409-4e81b69c-41b6-11e8-8eef-b682d0218ab8.png)

**Comment by deathbeam** [comment]
I would just copy-paste the chat message to the notifications for both events.

**Comment by TheLonelyDev** [comment]
It is indeed just "copy pasting" the message into a notification.

`notifier.notify(event.getMessage());`

**Comment by shmeeps** [comment]
Should be addressed by #3163, for anyone looking into this.

**Comment by Adam-** [comment]
Added in #3636
