### ISSUE TITLE
Mage Arena II

### ISSUE THREAD

**Issue by Adem1094** [runelite/runelite#13805]
RuneLite was not able to locate one of the bosses for the Mage Arena II miniquest.

This issue encountered for the Guthix boss. I was able to locate the Saradomin boss, but I can't speak for the Zammorak boss until I find the Guthix boss.

It would be nice to have all bosses included.

![Capture](https://user-images.githubusercontent.com/29441603/123689343-1e5f1400-d821-11eb-91f1-a6e2bf09e9c8.PNG)

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
