### ISSUE TITLE
Mac OS screen stretch bug

### ISSUE THREAD

**Issue by naus1a** [runelite/runelite#13804]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When stretching the screen with "stretched screen" and GPU plugin enabled, the screen stretches far larger than can fit in the box.

**To Reproduce**
On Mac OS
1. Enable GPU mode
2. Enable stretch screen 
3. Resize or full screen the client

A temporary fix to this is to disable and enable the GPU plugin after resizing the interface but of course this is far from ideal. The bug appears to only be visual as all the buttons appear to be in their right places when you hover over them on the screen. This also creates the unintended side effect of appearing to displacing buttons when the screen is only stretched a little.

<img width="1791" alt="Screenshot 2021-06-28 at 7 03 22 pm" src="https://user-images.githubusercontent.com/74320049/123683439-19f82280-d844-11eb-8b6d-72c3c2737d1f.png">

**Environment (please complete the following information):**
 - OS: [Mac OS Big Sur 11.2.3]
 - RuneLite version: [1.7.13.1]
 - Launcher version: [2.1.4]

**Comment by mmccoy37** [comment]
I found another requirement for reproduction. The runescape client must be using fixed classic view mode. If you use resizable modern or resizable classic the issue does not repro.

**Comment by Adam-** [comment]
fixed in bb43d232bb594c6e062e3342fa7db1b53f594c11
