### ISSUE TITLE
Quit feature on main menu.

### ISSUE THREAD

**Issue by oogaboogadoogydoogy** [runelite/runelite#13811]
Could someone please make a plugin that either adds a "Quit" button on the main login screen or allows you to close the client with the escape key on the login screen?

I play in fullscreen & having no way to actually exit the game means force quitting it through task manager. I know most people play this game windowed but I don't so I think it's silly that the literal only way to close the game is through the client itself because Jagex didn't add a quit button until 2008.

okay pwease & tank-you <3

**Comment by Hydrox6** [comment]
We don't support full screen; the client can be maximised at most. Given that the only support is a hub plugin, you're better off asking them to do this.

Also, Alt F4 exists, and it's great for exiting anything.
