### ISSUE TITLE
Original game resolution on GPU plugin activation.

### ISSUE THREAD

**Issue by oogaboogadoogydoogy** [runelite/runelite#13812]
Hewwo!

From what I can tell, as soon as the GPU plugin is turned on, the game increases in resolution. Note that with antialiasing off & anisotropic filtering off, the image still becomes clearer. Even trying to turn compute shaders off doesn't keep the game at the original resolution when activating the GPU.

Could we get an option that doesn't increase the game's resolution when the GPU is activated?

I know this may sound silly at first. I always try to uphold artists'/developers' original creative vision & that means a blurry, pixelated Old School. I 100% understand if that does not appeal to you, & why someone would want the game clearer, not to mention the addition of antialiasing & such. 

I love the pixelated look of Old School.

Unfortunately, with the GPU plugin off, I struggle to hit even 30 fps. It is near unplayable framerate-wise.

I must enable the GPU to hit a rock solid 50 fps, however, as previously mentioned, the moment you do the game becomes a whole lot less blurry. 

Could we have the *option* to maintain the original resolution when turning on the GPU? This is a feature I would gladly donate towards.

<3

**Comment by oplosthee** [comment]
Adding some screenshots to confirm and show this:

Vanilla | GPU plugin | GPU plugin with the "Remove Color Banding" setting:

![image](https://user-images.githubusercontent.com/3659837/125189878-9c1c1a00-e23a-11eb-88a8-972d304e1180.png)

![image](https://user-images.githubusercontent.com/3659837/125189926-e30a0f80-e23a-11eb-95fd-e636bd72beaf.png)

This is with anti-aliasing disabled, UI scaling on bilinear, compute shaders enabled, no anisotropic filtering, and bright textures disabled.

**Comment by Nightfirecat** [comment]
We are not planning to change the GPU plugin to render pixel-for-pixel accurate images when compared to the CPU renderer. This is, for multiple reasons, not feasible nor the goal of the plugin.
