### ISSUE TITLE
Add how many seconds before logout should logout alerter warn

### ISSUE THREAD

**Issue by JOMYGOD** [runelite/runelite#1381]
It would be nice if we could change the amount of time to pass before getting the log out notification

at the moment you are notified when you are 15 seconds from being logged, would be cool if we could change that time :)

**Comment by deathbeam** [comment]
Maybe we could just honor the idle notifier delay and substract it, that would make everyone happy.

**Comment by deathbeam** [comment]
I think this is fine as is, no need for adding configuration for this, 20 seconds is enough to react
