### ISSUE TITLE
Audio settings

### ISSUE THREAD

**Issue by joaogardenberg** [runelite/runelite#13815]
**Describe the bug**
Since today's update (maybe even before, I haven't checked that in a while), messing with the audio settings (the small one, outside of the "All settings" window) doesn't work anymore.

I can't move the volume sliders and muting/unmuting does nothing at all.

Doing that in the "All settings" window works though.

**To Reproduce**
1. Go to the "Settings" main tab;
2. Click on the sound icon sub tab;
3. Try to change the volumes;
4. Also try to mute/unmute.

**Expected behavior**
I should be able to move the sliders and mute/unmute.
It works in the official client.

**Screenshots**
![image](https://user-images.githubusercontent.com/6900749/124040446-50b47100-d9db-11eb-8c82-97d4c4d01af0.png)

**Environment (please complete the following information):**
 - OS: **Windows 10**
 - RuneLite version: **1.7.13.1**
 - Oldschool revision: **Rev 197**
 - Launcher version: **2.1.7**

**Comment by abextm** [comment]
458e6852086ff528c1b62755fe1d9e5cf49d73b5
