### ISSUE TITLE
Addittions/Improvements Ideas to 'Idle Notifier' (colors, potion timers, smooth flash option)

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#13829]
My suggestions to improve the '**Idle Notifier**' -plugin:

**1.** Ability to change the colour of the flashing

**2.** Based on why the plugin is flashing your screen, each reason should have its own colour (e.g. you're about to log out; flash [set] color], your prayer is low; flash [**different** color], etc.)

**3.** In addition to idle animation/interaction/movement/logout/HP/prayer/run energy/oxygen/spec notifications, it should also have options for example. "Antifire effect" running low (set your own [how_much_time_left] setting), and other potions/stuff with timers.
**3.1.** Another notification idea is that you should be notified if you're losing a single HP in combat (perhaps you're safe-spotting and stepped 1 tile away or AFK), different to HP threshold already existing, because you can be over or below that threshold.
**3.2.** You should be able to be notified whenever you have finished killing the monster you are fighting

**4.** Add a smooth flash option for flash notifications (like in OSB), see here how it looks like: https://www.youtube.com/watch?v=SoCgKICR8Io&t=63s

**Comment by Hydrox6** [comment]
Don't make an issue that contains 6 different issues

1. Colour can already be configured.
2. Duplicate of #11679
3. This can already be done with `Chat Notifications` and the messages Jagex gives the client.
3.1. This is so incredibly narrow, and can basically already be done with the existing HP threshold being set to 1 less than your current (and just updating that if you take damage by being silly)
3.2. This already exists, it's called `Idle interaction notifications.
4. Duplicate of #12147. Don't make a new issue as a bump of an old issue

**Comment by Popedigoz** [comment]
> 
>Don't make an issue that contains 6 different issues
> 

Sorry about that

> 
> 
> 
> 
> 
>     3. This can already be done with `Chat Notifications` and the messages Jagex gives the client.
>        3.1. This is so incredibly narrow, and can basically already be done with the existing HP threshold being set to 1 less than your current (and just updating that if you take damage by being silly)
>        3.2. This already exists, it's called `Idle interaction notifications.
> 

3. Yes and no. You can't set your own desired value of the time left as I described.
3.1 The idea behind this was that if you miss the initial notification it should keep notifying you each damage you take.
3.2 Actually this does not exist, because if you have auto retaliate on and enemies keep you interacting all the time it has no time to notify you between kills (because your character is not idle), so a notification exclusively for killing an NPC is a great idea.

@Hydrox6 Shall I open 3 more issues then?
