### ISSUE TITLE
Loot split tracking

### ISSUE THREAD

**Issue by alexbowers** [runelite/runelite#1382]
Being able to track loot split would be pretty neat.

For example, a group of 3 people:

Alex
Tom
Peter

go to KQ  for a few trips.

If at the end of the trip, each person indicates how much they have earned from that trip, and it gets stored against a running total for that person.

At the end of the trips, a "calculate" button is pressed that says how much each person needs to pay each other to make the trip even.

For example,

Alex gets 100k
Tom gets 50k
Peter gets 300k

in drops

This means that a split of 150k each is due.

The split for this would be Peter pays Alex 50k, Peter pays Tom 100k.

That would get them all to 150k each which is the split needed.

**Comment by alexbowers** [comment]
Version 2 of this would be being able to automate it by having the drops recorded for who got what, and the current estimated selling price of those drops.

**Comment by Kamielvf** [comment]
This would probably best be added after something like #1235 is done.

**Comment by deathbeam** [comment]
We have loot tracker, so you can just look at it and divide between players, simple

**Comment by alexbowers** [comment]
@deathbeam That doesn't fully solve the problem.

A full loot tracker would be able to track other peoples drops too and work out who owes who what based on the sale value of the items.

Eg. Player 1 got a drop and player 2 & 3 didnt.

Then player 1 has to simply split their items by 3 and everyone is even

But if player 1 and player 2 got drops, then their combined wealth has to be split by 3.

**Comment by deathbeam** [comment]
You would need to compare your own loot trackers. You cant see other peoples drops
