### ISSUE TITLE
Add Biblia locator for the Kourend library

### ISSUE THREAD

**Issue by mmccoy37** [runelite/runelite#13836]
**Is your feature request related to a problem? Please describe.**
When using the Kourend library for Arceuus favor, it is much more efficient when talking to Biblia. However she moved fast and randomly changes location. It is annoying having to manually locate her.

I have tried the existing plugin which is great, but once you hit 20% favor it becomes faster to get the dark manuscript book. This book can be in any 1 of like 20 tiles, requiring one to talk to Biblia

**Describe the solution you'd like**
It would be nice if there was an arrow + highlight option for Biblia which directed the user to her location if they are on the 3rd floor.

**Describe alternatives you've considered**
I have tried manually locating her.

**Additional context**
N/A

**Comment by LlemonDuck** [comment]
Have you tried the existing "Library of Kourend" plugin that already exists? It narrows down books to the exact bookshelf after some trial and error, and is much quicker than talking to Biblia between each book.

**Comment by mmccoy37** [comment]
> Have you tried the existing "Library of Kourend" plugin that already exists? It narrows down books to the exact bookshelf after some trial and error, and is much quicker than talking to Biblia between each book.

I have, but once you hit 20% it becomes faster to get the dark manuscript book which can be in any 1 of like 20 tiles, requiring one to talk to Biblia

**Comment by Nightfirecat** [comment]
You can use the NPC Indicators plugin to mark her. I believe it's possible to stall her movement by talking to her, so the plugin would not be able to accurately predict her location while she's out of sight.
