### ISSUE TITLE
Add Desert Amulet menu swaps

### ISSUE THREAD

**Issue by AFile94** [runelite/runelite#13831]
Can we add the Desert Diary Amulet to the swapper for left click teleport to Nardah?

**Comment by jbattipaglia** [comment]
I think you can do this with "teleport item" under the item swaps in the plugin

**Comment by AFile94** [comment]
> I think you can do this with "teleport item" under the item swaps in the plugin

Nope, Desert amulet has numerous teleports and they aren’t rub/teleport labeled options.

**Comment by raiyni** [comment]
This is covered by the `Menu Swapper Extended` plugin

**Comment by Nightfirecat** [comment]
We've added other diary swaps to the core client, this can be added also.
