### ISSUE TITLE
Adding a countdown to making arrows

### ISSUE THREAD

**Issue by damnnitbobby** [runelite/runelite#1384]
When you feather arrow shafts, or put arrow heads onto headless arrows, it does a maximum of 10 actions. It's also very afk and people dont pay attention to how many actions are left until they need to click again. It would be really nice if there was a small number somewhere (on the inventory icon maybe) of how many actions were left until you were done. I think making broad arrows is the ironman fletching meta so it will be used a lot. gif related but adds nothing https://i.imgur.com/ghKmi0m.gifv

**Comment by deathbeam** [comment]
We have idle notifier that is more than enough for this
