### ISSUE TITLE
Completed Quests in Achievement Diaries Are Not Crossed off

### ISSUE THREAD

**Issue by lcud** [runelite/runelite#13846]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I have completed all quests. When opening achievement diary menu, the requirements for tasks involving quest requirements do not have the quest "X'd" out.

**To Reproduce**
1. Go to 'Achievement Diaries'
2. Click on 'Any unfinished Diary that you have quest completed for'
3. Scroll down to 'Requirements'

**Expected behavior**
Completed quests should be stuck out.

**Environment (please complete the following information):**
 - OS: WIndows
 - RuneLite version: 1.7.15
 - Launcher version: 2.1.0

**Comment by abextm** [comment]
Fixed in afde6c899e822af01feb89da1dbf8512900fe556
