### ISSUE TITLE
Pet rate plugin

### ISSUE THREAD

**Issue by Mr1DRFL** [runelite/runelite#13855]
I have seen a plugin that tracks probability based on several factors, and things like the loot tracker that can track actions and items received. I first thought it would be nice for loot tracker to count things like gems that are pickpocketed and go straight into gem pouch, and it got me thinking. 

Is there a way to make a plugin, say for runecrafting, that has the set rates of pet chance per blood runes crafted, and similar to loot tracker, sees how many you have made vs the target of pet rate to give a realistic idea of how close we are to the pet chance if we need to go all the way(or heaven forbid past) the rate itself. 

I have no experience in coding or plugins but i thought this would be awesome as i have recently maxed and im going through skilling pets first... hours of blood runes would be a tad easier to see a progress bar for pet rate similar to skill progress bars :o

thank you for reading, let me know!

**Comment by ThePharros** [comment]
You can use my Probability Calculator on the plugin hub for this. Insert the drop rate (for Rift Guardian at bloods, this is ```1/(804984-Lvl*25)``` where Lvl is your RC level, and for kill count use the number of essence crafted. Then for drops received, use 1 to see what odds of having the pet by now is.

**Comment by Nightfirecat** [comment]
As ThePharros said, there's not really any way to display a "progress bar" for pets since you're no closer to getting a pet after many attempts than you were when you started. For now, I recommend using his proposed approach to calculating your pet chance luck.
