### ISSUE TITLE
npc indicators outline bugged in fixed

### ISSUE THREAD

**Issue by emiljensen2** [runelite/runelite#13864]
**Describe the bug**
Using outlines in npc indicators when using fixed causes errors

**To Reproduce**
1. Go to maiden while using fixed
2. Enable npc indicators outline on maiden
4. See error in logs

**Expected behavior**
[Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.ArrayIndexOutOfBoundsException:

**Environment (please complete the following information):**
 - OS: Windows 10 20H2, build 19042.1052
 - RuneLite version: 1.7.15
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
[client - Copy.log](https://github.com/runelite/runelite/files/6804798/client.-.Copy.log)

**Comment by Adam-** [comment]
@WooxSolo can you check this out?
