### ISSUE TITLE
Crabclaw Isle master clue step missing information

### ISSUE THREAD

**Issue by thebinaryeagle** [runelite/runelite#13867]
The Crabclaw Isle master clue step does not indicate that there is an Ancient Wizard Trio that spawns when you dig in the indicated location. This is the only thing the clue plugin shows:
![RuneLite_Ufqn1W8gYW](https://user-images.githubusercontent.com/60583962/125521065-e17af2c3-d312-4217-9aa8-656852d05eea.png)

I have since completed the step but here's a link to it on the wiki in case you need the coordinates, etc.: [[link]](https://oldschool.runescape.wiki/w/Treasure_Trails/Full_guide/Master#508)

**Comment by Nightfirecat** [comment]
Fixed in 583794a26a513a7c7af4fd65e297cc0f94dbd54e
