### ISSUE TITLE
Runelite keeps closing itself every few minutes.

### ISSUE THREAD

**Issue by AJZade** [runelite/runelite#13863]
Seen some posts about this in the past and tried some "fixes" with no success.

Currently doing Mahog homes and whenever I enter a home and sometimes when I tele to a new area, the client just spontaneously closes. 
Was working fine yesterday and throughout the weekend with no issues, had no driver updates in a good week, problem continues before and after a Java update, and cant find anything in any log folders.

Any advice / help is appreciated, thank you :)

**Comment by julianIppolito** [comment]
Hey,

I've encountered the same issue, but I was in the Catacombs of Kourend and when I teleported using the Xeric's talisman it crashed my client and auto-closed. I experienced this last night as well. I think there is a deeper issue.

**Comment by ThePharros** [comment]
There is currently an instability with 64-bit Java. Using the 32-bit RuneLite client  should resolve this issue for the meantime.

**Comment by Nightfirecat** [comment]
I recommend following ThePharros's advice. If you have further issues, please reach out in our Discord server's `#support` channel.
