### ISSUE TITLE
max hit not working

### ISSUE THREAD

**Issue by craycrayxx** [runelite/runelite#13861]
When going to the worn equipment tab it would previously tell your max hit but now it says "equip your character" i tried to reinstall aswell. any reason to why its not working anymore?
![no max hit](https://user-images.githubusercontent.com/87279498/125206678-6c900080-e280-11eb-923c-78fc15830196.png)

**Comment by Hydrox6** [comment]
This has never been a feature of the client. Maybe you're thinking of OSB?

**Comment by raiyni** [comment]
Max hit is a phub plugin

**Comment by craycrayxx** [comment]
> This has never been a feature of the client. Maybe you're thinking of OSB?

this could be because before runelite i used osbuddy and i remember it calculating your max hit. thank you
