### ISSUE TITLE
Roof removal plugin rendering bug

### ISSUE THREAD

**Issue by Varelden** [runelite/runelite#13877]
I was at magic guild in Yanille and pieces of the floors above me were rendering when they shouldn't

1. Go to Magic Guild
2. Turn on Roof Removal plugin
3. See error

**Environment (please complete the following information):**
 - OS: windows 10
 - RuneLite version: 1.7.16
 - Launcher version: 1.6.0
![2021-07-14_20-21-27](https://user-images.githubusercontent.com/74330765/125713098-7d1f9b2f-50b5-4669-bfa7-34d0ca674828.png)

**Comment by Nightfirecat** [comment]
For whoever may look to solve this, an easy way to test roof override file changes is to make the following change to the plugin, replacing the path I used with the path to the overrides file in the project on your machine:

```diff
diff --git a/runelite-client/src/main/java/net/runelite/client/plugins/roofremoval/RoofRemovalPlugin.java b/runelite-client/src/main/java/net/runelite/client/plugins/roofremoval/RoofRemovalPlugin.java
index a9e92f4420..8577d77d56 100644
--- a/runelite-client/src/main/java/net/runelite/client/plugins/roofremoval/RoofRemovalPlugin.java
+++ b/runelite-client/src/main/java/net/runelite/client/plugins/roofremoval/RoofRemovalPlugin.java
@@ -28,6 +28,7 @@ import com.google.common.base.Stopwatch;
 import com.google.gson.Gson;
 import com.google.gson.reflect.TypeToken;
 import com.google.inject.Provides;
+import java.io.FileInputStream;
 import java.io.IOException;
 import java.io.InputStream;
 import java.io.InputStreamReader;
@@ -175,7 +176,8 @@ public class RoofRemovalPlugin extends Plugin
 
 	private void loadRoofOverrides() throws IOException
 	{
-		try (InputStream in = getClass().getResourceAsStream("overrides.jsonc"))
+//		try (InputStream in = getClass().getResourceAsStream("overrides.jsonc"))
+		try (InputStream in = new FileInputStream("/home/nightfirecat/Documents/git/runelite/runelite-client/src/main/resources/net/runelite/client/plugins/roofremoval/overrides.jsonc"))
 		{
 			final InputStreamReader data = new InputStreamReader(in, StandardCharsets.UTF_8);
 			//CHECKSTYLE:OFF

```

Once applied, you can make changes to `overrides.jsonc` and toggle the plugin off and on to see them enacted. (just don't forget to reverse the plugin change before committing and pushing)

**Comment by neilrush** [comment]
adding:
```java
 "10288": [ // Yanille East
    {
      "rx1": 30,
      "ry1": 15,
      "rx2": 31,
      "ry2": 16,
      "z1": 1,
      "z2": 1
    },
```
To the overrides did not fix the issue for some reason.
