### ISSUE TITLE
Ground Item Coins

### ISSUE THREAD

**Issue by Kyle-Newton** [runelite/runelite#1387]
To help keep things clean, it'd be good to remove Exchange price on Coins when the feature is enabled, we all know that 429 coins is probably worth about 429.  ;)
I'm not sure how much of a pain this would be, but if it's a quick fix it'd be nice. I've also noticed that after 65K or so it just say's "Lots" which is probably good enough for everything outside drop parties and PKing.

**Comment by Nightfirecat** [comment]
Each of these topics should be separate issues for better tracking.

Regarding the "Lots" text, Runescape doesn't send exact numerical values for cash values above 65535, and that's reflected in the code here: https://github.com/runelite/runelite/blob/5633053ec7dfe2f2f690dcc7ca2fcfe15463e3a9/runelite-client/src/main/java/net/runelite/client/plugins/grounditems/GroundItemsOverlay.java#L56-L58

**Comment by Kyle-Newton** [comment]
Separated the issues :)

As for the 65535 limit, that's really interesting. Do you know how other clients handle this and if it'd be a future possibility? As if you drop 1m coins in a client like OSBuddy it will display such.

**Comment by Kyle-Newton** [comment]
Your right @Nightfirecat , for some reason I thought large coin drops displayed accurately but I logged in and dropped a stack and OSbuddy just displays 65535. It seems like an unfixable issue, and this issue can be closed. :)
