### ISSUE TITLE
Unable to filter recolored chat using a starts with regex

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#13885]
**Describe the bug**
Recolored chat has a color tag appended to it so trying to filter a message that starts with a phrase for example: `^buy` wont match since the message starts with the color tag.

**To Reproduce**
1. set public chat to a custom color
2. find a spammer, recommend house portal on party world
3. filter a message thats getting spammed like `^join`
4. the chatbox message wont be censored but overhead text will

**Expected behavior**
the message in the chatbox and overhead text to be censored the same way

**Comment by Adam-** [comment]
fixed in 90f200be531b8a899a605521f3e9840de6f9794d
