### ISSUE TITLE
Music resets on 1% volume when changing control panel tabs

### ISSUE THREAD

**Issue by Bram91** [runelite/runelite#13881]
When using granular volume sliders and having the music volume set to 1%, the song will reset on control panel changes.  This only occurs when clicking the tabs, not through F keys
ie: going from the inventory to the gear tab resets the song.

**Comment by ThePharros** [comment]
Looks like it might trigger when VarClientInt INVENTORY_TAB(n) is changed. In addition, I was able to reproduce this via certain onVarbitChanged as well (tested with going in and out of single/multi combat and doing some dailies).
