### ISSUE TITLE
Roof Removal Plugin - add toggle for POH 

### ISSUE THREAD

**Issue by kaidejager** [runelite/runelite#13891]
It would be very nice to have a toggle for inside player owned houses. 

Because you tend to move the cursor around a lot while deciding where you're teleporting it causes a bit of an annoyance. Would be even more useful for others homes to quickly identify the layout or room you're looking for.

**Comment by A-RooK** [comment]
Big support.  Love the functionality in the open world, but would love to see a toggle to set POH roofs to always off.

**Comment by BrianFrobey** [comment]
I think this is an excellent idea because my POH is one of the few places I always want the roofs hidded.

**Comment by nmachen** [comment]
I think it's a great idea too, it's definitely a minor annoyance. 

@Hydrox6 I see you removed the internal tag. I looked into this and I couldn't figure out how it could be done without access to the `generateHouses()` and `setRoofRemovalMode()` methods. Am I missing something obvious?
