### ISSUE TITLE
Missing items for clue

### ISSUE THREAD

**Issue by Dragon911XX** [runelite/runelite#13896]
I'm doing a clue, and it seems like there's a missing item for the following clue 

![image](https://user-images.githubusercontent.com/7053735/126056481-0986eb5a-66e8-42ce-b9de-6f7183a42ca2.png)

The clue doesn't specify needing an OILY fishing rod, nor does it say you need the Icy Gloves.

**Comment by geheur** [comment]
You don't need an oily fishing rod or icy gloves to catch sacred eels. I catch them all the time with a regular rod and no icy gloves. Oily rod might be for lava eels, idk.

**Comment by Cyborger1** [comment]
You are confusing [Infernal Eels](https://oldschool.runescape.wiki/w/Infernal_eel) with [Sacred Eels](https://oldschool.runescape.wiki/w/Sacred_eel).

The items are correct, you must catch the eel close to where you go to fight Zulrah.
