### ISSUE TITLE
Idle Notification

### ISSUE THREAD

**Issue by doughboy623** [runelite/runelite#13892]
simple request to set it to send notification even if client is in focus i enjoy to watch movies while playing and my cooking is 800/hr when it could be 1300-1400 please and tyy great client btw.

**Comment by Bram91** [comment]
This is already an option, see: https://github.com/runelite/runelite/wiki/RuneLite#send-notifications-when-focused

**Comment by doughboy623** [comment]
> This is already an option, see: https://github.com/runelite/runelite/wiki/RuneLite#send-notifications-when-focused

wow i was staring at it thank you for the link btw
