### ISSUE TITLE
Add custom recolor for items that are worth alching on ground

### ISSUE THREAD

**Issue by Kyle-Newton** [runelite/runelite#1390]
I'd like to see an option to recolor items that are considered worth alching.
If item_price + nature_rune_price ≤ item_alch_price, recolor. #

**Comment by apierce376** [comment]
I'm almost done working on this right now! You can check on the progress on my pull request https://github.com/runelite/runelite/pull/1399.

**Comment by deathbeam** [comment]
You can just set highlight > value
