### ISSUE TITLE
Roof removal plugin works weirdly in Keldagrim Palace

### ISSUE THREAD

**Issue by Trencha** [runelite/runelite#13911]
**Describe the bug**
Roof removal plugin doesn't remove some of the roof bits from Keldagrim Palace. Occurs on ground level and 1st floor (UK). 2nd floor (UK) is fine.

**To Reproduce**
1. Go to Keldagrim Palace
2. Turn off Roof removal plugin if it is on. Hide roofs. Observe the building.
3. Turn on Roof removal plugin and mouse over either side of the palace building or stand inside the building. Observe that the roof of the middle section which goes over the river is still drawn (including the inside of the upper floor).
4. Go upstairs and repeat.

**Expected behavior**
When the plugin is enabled and the building is moused over, the middle section of the building disappears.

**Screenshots**
Ground level:
Without plugin, roofs hidden:
![image](https://user-images.githubusercontent.com/2754136/126385336-6d6caea6-45ae-4910-bdfa-af6694206655.png)
Roofs not hidden (or with plugin without mouseover):
![image](https://user-images.githubusercontent.com/2754136/126385382-10e8852e-3fa8-4752-9fe7-564e8ace63bf.png)
With plugin, mousing over:
![image](https://user-images.githubusercontent.com/2754136/126385487-45518616-e9f5-4bf0-9252-7b6fb608e0da.png)
First floor (UK):
Without plugin:
![image](https://user-images.githubusercontent.com/2754136/126385527-0673a3e9-6b4a-4dc1-bdce-6a98d9a0e39a.png)
With plugin:
![image](https://user-images.githubusercontent.com/2754136/126385548-b6c406f9-a7b5-4baf-8ebc-6ae8a1926db7.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.16
 - Launcher version: 2.1.0

**Additional context**
This may be partially due to the two sides of the building on ground level being treated as 2 separate buildings despite being joined by the 2nd floor.

**Comment by Nightfirecat** [comment]
Fixed in c64cb8e5f543835c28ef0d062f9bd53535e259fd
