### ISSUE TITLE
Recolour "valuable drop" chat message

### ISSUE THREAD

**Issue by chunderbolt** [runelite/runelite#13921]
The "Valuable drop" chat message is a bit difficult to see (for me) when using the opaque chatbox. It would be nice to be able to recolour it.

![chat](https://user-images.githubusercontent.com/59027738/126573646-bbf50799-c2ee-4812-9dcf-44b35b8cb572.PNG)

**Comment by Alexsuperfly** [comment]
if none of the options in the `chat color` plugin work on it, then my hub plugin `force recolor` will
