### ISSUE TITLE
Nightmare team size display prevents reading pb times

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#13932]
With the release of Combat Achievements, Nightmare was given the same team size treatment as Chambers of Xeric when displaying pb times.

new message looks like this when receiving a kill
![image](https://user-images.githubusercontent.com/7191512/126799291-d9046291-46be-49d7-bba9-ba3bce5fe6bc.png)

I imagine the Adventure log section for nightmare has been changed too to reflect all the different possible team sizes.

**Comment by Adam-** [comment]
fixed in 7854c6f096492d0208b82f3b501e839502ac3aea. We need the non-pb version of this probably still though.

**Comment by Adam-** [comment]
Someone found the non pb ver: ![image](https://user-images.githubusercontent.com/309739/127390064-1bae8f49-1c2b-44f7-9f40-b60840976bfb.png)

**Comment by Adam-** [comment]
fixed in 87c72e94a30434f2e7abcedcebee8da184fe2de9
