### ISSUE TITLE
Roof Removal Plugin - Grim Tales Tower

### ISSUE THREAD

**Issue by CarlOlson** [runelite/runelite#13930]
**Describe the bug**

The roof isn't removed in the tower south of the mind alter. It is visited during the Grim Tales quest.

**Screenshots**

![Screenshot_20210723_194145](https://user-images.githubusercontent.com/6601628/126771870-aa0c2cff-a87f-4438-9f51-a9710ad2c912.jpg)

**Environment:**
 - OS: Ubuntu
 - RuneLite version: 1.7.17
 - Launcher version: 2.1.5

**Comment by Hydrox6** [comment]
This area is inaccessible after the quest; someone who hasn't done the quest will need to fix this.

**Comment by mithom** [comment]
issue still here
