### ISSUE TITLE
Roof Removal Piscarilius Buildings

### ISSUE THREAD

**Issue by WolffTech** [runelite/runelite#13940]
The tall buildings in Piscarilius seems to still be shown even when the building is in-between the player and the camera. Hovering your mouse more towards the bottom of the building or entering the building hides the roof.

https://user-images.githubusercontent.com/9462828/126860893-d7bb4e77-45b8-4f39-99a4-1230b9b67014.mp4

**Comment by Hydrox6** [comment]
This should be fixed with an internal change
