### ISSUE TITLE
Can't enable the GPU plugin

### ISSUE THREAD

**Issue by StoniMacaroni** [runelite/runelite#13949]
Hi!

I'm new here and I don't exactly know how this works but at least I can tell you what my issue is. So I've had an issue that I can't turn on my GPU plugin, and as soon as I do it it turns off by itself. I've taken a break from OSRS for the past couple of months and back then I could play the game with the GPU plugin with settings on the higher end of the spectrum without any issues.  

I've been trying to search around for people who have the same issue and usually what pops up is either that the drivers are not up to date or that there's some problem with what graphics card the game is running on, the internal or external one. I've double-checked both of these things and they haven't helped me at all, and the problem still stands as is. I've been trying to check if the problem could be java related without any luck. I've also checked my OpenGL rendering GPU option in the NVIDIA control panel, and it is set to my NVIDIA GPU as recommended in your FAQ. 

I've got an Acer Nitro 5 and (some of the) specs on my pc are:
Processor: IntelCore i5-7300HQ 
RAM: 8GB
Graphics Card: NVIDIA GeForce GTX 1050 Ti

Thank you in advance for your help, it is much appreciated! Also if there's any other info you need just ask, as I'm not very experienced with these types of issues.

**Comment by Bram91** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
