### ISSUE TITLE
Wilderness Moss giant task icon

### ISSUE THREAD

**Issue by jsBrian** [runelite/runelite#13959]
I got a Moss giant task from Krystilia (wildy slayer) and noticed that the icon used for tracking the Moss giants is the Hill giant club. Wouldn't it make more sense to use one of the Moss Giant uniques instead, such as the Mossy key or Bryophyta's essence?

This might be a bug that only occurs for Moss giant tasks in the Wilderness, I haven't been able to check it for Vannaka.

**Comment by Hydrox6** [comment]
Mossy key would definitely make a lot more sense imo
