### ISSUE TITLE
Ability to remove chop option

### ISSUE THREAD

**Issue by eyeslangmeat** [runelite/runelite#13975]
This would make moving around Prif especially nice, when hunting crystal imps. There is just so many trees

**Comment by domien96** [comment]
Hi @eyeslangmeat 
How do you see this practically? Because as a player, you don't want to go and search into the settings every time you enter Prif.
Any hotkeys or?

**Comment by eyeslangmeat** [comment]
Well I haven't thought about hot keys, but for me personally I would keep it on all the time except when training wc. I just used prif as an example because it's mega annoying. 

 
 
  On Mon, Aug 9, 2021 at 3:12 PM, Domien Van ***@***.***> wrote:   


Hi @eyeslangmeat
How do you see this practically? Because as a player, you don't want to go and search into the settings every time you enter Prif.
Any hotkeys or?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by domien96** [comment]
Having an axe wielded on in your inventory can be a condition to toggle the chop feature for example.
But we may have to think of exceptions. We want to avoid players being unable to chop whenever they wish to do so.

**Comment by Nightfirecat** [comment]
This is not allowed [per Jagex's statement regarding third-party clients](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1) based on the following restriction:

> Allows you to prioritise the walk-here option by holding a certain key, or similar

**Comment by F-Lambda** [comment]
Is this still not allowed with the updated [Third-Party Client Guidelines](https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1) that were released a month after this was closed? The new guidelines don't say anything about walk-here, and there's already a "Shift click Walk here" option in the Menu Entry Swapper plugin now.

**Comment by Skretzo** [comment]
Menu entries can be removed with the Custom Menu Swapper hub plugin
