### ISSUE TITLE
Add highlight to Agility obstacles instead of an overlay

### ISSUE THREAD

**Issue by josemedina760** [runelite/runelite#13979]
**Is your feature request related to a problem? Please describe.**
The Agility overlay is too distracting when doing agility on actual courses. can we get the option for more subtle overlays ?

**Describe the solution you'd like**
I would like the Interact Highlight/Agility plug-in to always highlight agility shortcuts instead of having a big overlay.
![image](https://user-images.githubusercontent.com/12689117/128239948-cfd05846-aed8-4e83-a678-1a25cc787a4b.png)

**Describe alternatives you've considered**
The Interact Highlight  plug-in can add a "Highlight all Agility obstacles" or the agility plug-in can have a "use Highlight instead of overlay"

**Comment by Nightfirecat** [comment]
You can already change the color (ie. reduce the opacity) of agility clickbox overlays. Given that the clickboxes are what the vast majority of players care about, I don't think this should be changed to an outline overlay. For your case, you could reduce the opacity of the agility overlay so it's less visually noisy.
