### ISSUE TITLE
Status Bars floating in incorrect position on client HUD

### ISSUE THREAD

**Issue by iRhysBradbury** [runelite/runelite#13974]
After [the latest OSRS update](https://secure.runescape.com/m=news/new-client-features-milestone-2?oldschool=1#_ga=2.180267940.1020185686.1628073098-751684986.1561372201) it appears that the status bars are drawing incorrectly.

I have attached a screenshot.

I have re-installed runelite to the same end.

My friend is also having this issue after the update.

[Screen Shot 2021-08-04 at 11 40 05](https://user-images.githubusercontent.com/15735720/128167636-aa735fa9-1ed4-4482-9bca-fe6df5237b59.png)

**Comment by Hydrox6** [comment]
Wait for the update
