### ISSUE TITLE
Interactive Highlight clips in ground at Zulrah

### ISSUE THREAD

**Issue by Nillen** [runelite/runelite#13984]
![RuneLite_hqhgJ4rKdh](https://user-images.githubusercontent.com/7152910/128361419-f6086fbe-81a1-4457-9c20-743b68646901.png)

**Comment by Nightfirecat** [comment]
This doesn't seem like a bug to me. If some part of Zulrah's model displays at that spot during its animation, it would be highlighted by the plugin.
