### ISSUE TITLE
Menu Entry Swapper for Gaunlet to quick-leave

### ISSUE THREAD

**Issue by Fathlete** [runelite/runelite#13985]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option to switch the two options around in the screenshot in order to quickly be able to escape the hunllef fight with a left click on the door instead of having to right click. The currently is no left click option as if you click the door right now you'll just walk to the tile closest to it. 

**Describe alternatives you've considered**
The option is to get a teleportation crystal inside the gauntlet but that's very pricey at 200 shards which isn't feasible if you want to T3 prep. If this does get added please make it toggleable as it could annoy people who do not care about dying inside the gauntlet (non-HCIMs).

**Additional context**
https://i.imgur.com/mz5LeGL.png

**Comment by Adam-** [comment]
This should be possible now with 92aac53f4273e7944c3da767637e083847c03808
