### ISSUE TITLE
notification when a slayer task has ended

### ISSUE THREAD

**Issue by NathanGanesh** [runelite/runelite#13999]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Nightfirecat** [comment]
You can already get a notification based on the slayer task completion message: `You've completed 123 tasks and received 15 points, giving you a total of 1,234; return to a Slayer master.` Using the string "return to a Slayer master." in the Chat Notifications plugin with the `Notify on highlight` option enabled would achieve this.

**Comment by ThePharros** [comment]
To add, there is also a plugin on the plugin hub called Task Jingle if looking for an audible cue on task completion.
