### ISSUE TITLE
Update Client alongside Steam

### ISSUE THREAD

**Issue by Nimja1** [runelite/runelite#14004]
Many of the initial reasons I downloaded Rune Lite are now in the official client, but many are not. In fact, the fishing helper in the client is better than the fishing plugin natively on RL. 

I was hoping to swap out that particular plugin for the native but the client being used on RL doesn't have that option. Was hoping that could become the case.

**Comment by Vulki0** [comment]
It doesn't work like that. The official Runescape Client is programmed in a different language.

Maybe the Runelite plugin developers may update their work and take inspiration from the official client.

Don't forget Java 17 is coming out soon. Big things happening.
