### ISSUE TITLE
Ring of Forging count doesn't handle Varrock Platebody double smelting effect

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#14008]
When smelting in Edgeville furnace with the Varrock Armour on, you have a chance of smelting two bars at once. This is indicated by a filtered chat message (`The Varrock platebody enabled you to smelt your next ore simultaneously.`). When smelting Iron with the Ring of Forging, this causes the counter to desync by 1, as the extra bar used a charge from the ring.

Something very important to note is that the effect can trigger on the final ore in your inventory for whatever reason, meaning that you had the ability to smelt two bars at once, you didn't have the ore available.

**Comment by Adam-** [comment]
fixed in #14220
