### ISSUE TITLE
Info boxes flips when left clicking

### ISSUE THREAD

**Issue by theIsaia** [runelite/runelite#14023]
**Describe the bug**
Shift left clicking the info boxes puts the Flip option on the left click action istead of it being hidden behind the right click action first

**To Reproduce**
1. Hold shift
2. Left click info boxes
3. Info boxes flip

**Expected behavior**
Nothing happens when shift left clicking over an info box

**Screenshots**
https://gyazo.com/4a678a535ff6f10f6ca4fd2c8c0b20f2

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.19
 - Launcher version: 2.1.6

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by abextm** [comment]
Issues for hub plugins should be opened on the plugin's repo.

**Comment by Adam-** [comment]
we've adjusted this now to force open the menu
