### ISSUE TITLE
too many login attempts 

### ISSUE THREAD

**Issue by grayvi07** [runelite/runelite#14022]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
im getting the too many login attempts bug, it only applies to the runelite client im able to play on the vanilla and steam client/mobile just fine

**To Reproduce**
not really sure i just went afk doing hydra and came back and wasnt able to login

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS] windows 10
 - RuneLite version: [e.g 1.4.6] 1.7.19
 - Launcher version: [e.g 1.5.2]  2.1.7

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by hex-agon** [comment]
This is not a RuneLite issue and there's nothing that we can do to help you. You'll either have to play via mobile or steam and complain to Jagex about it, a VPN might help.

**Comment by grayvi07** [comment]
disappointing, i got the same reply from jagex basically to use their steam client instead
