### ISSUE TITLE
Banked XP calculator ignoring bonemeal and ashes

### ISSUE THREAD

**Issue by ramon284** [runelite/runelite#14026]
The banked XP plugin checks your bank for items and calculates how much xp is banked in a chosen skill. Currently when choosing prayer, it seems to look for bones, remains, ensouled heads and fossils. Currently, ashes and bonemeal are not checked for.

The reason I opened this request is because I know myself and many others stack bonemeal in their bank, from the daily morytania diaries reward.

**Comment by Nightfirecat** [comment]
That plugin is a hub plugin, not maintained by the RuneLite team. Please open this issue on the banked XP plugin's repository.
