### ISSUE TITLE
Quest Guide

### ISSUE THREAD

**Issue by DLCAYANAN** [runelite/runelite#14038]
Have a plugin for all the quest. Not sure if it's possible to pull info from OSRS Wiki for it but would be great to have it show item recommended to get from GE and even show you current GE price. Allows users to have checkmark option so they can figure where they are in the quest progression. Maybe highlight NPC they need to talk to on certain section of the quest still not check marked.

**Comment by raiyni** [comment]
Quest helper is a phub plugin

**Comment by Nightfirecat** [comment]
The most popular plugin on the plugin hub is Zoinkwiz's [Quest Helper plugin](https://runelite.net/plugin-hub/show/quest-helper). I recommend you take a look at that.
