### ISSUE TITLE
Double clicking the hiscore lookup bar 

### ISSUE THREAD

**Issue by russel204** [runelite/runelite#14049]
i remember years ago when using OSB you could double click the hiscore lookup entry and it would pull up the stats of the acc you were logged in on. I still miss this feature. Would be nice to see it added.

**Comment by geheur** [comment]
You can double click the magnifying glass left of where you type names into the hiscore lookup to look yourself up. Is this what you're looking for?
![image](https://user-images.githubusercontent.com/41499327/130311179-8b5f5740-2e78-4b7a-bf6f-d0b4e4558a25.png)

**Comment by russel204** [comment]
@geheur lmao yup this is it. feel dumb now. in osb you double clicked the entry box. never considered even trying it on the search button

**Comment by geheur** [comment]
It's not obvious, that's for sure.
