### ISSUE TITLE
Key Remapping plugin broken

### ISSUE THREAD

**Issue by Steimel** [runelite/runelite#14044]
My remapped keys don't work at all (e.g. WSAD don't move the camera), and pressing enter doesn't allow me to chat. Using the arrow keys does turn the camera.

OS version: Mac OS 10.13.6
RuneLite version: 1.7.20
OldSchool revision: Rev 198
Launcher version: 2.1.1

**Comment by Nightfirecat** [comment]
For now, you can fix this when you log in by hitting "Enter" instead of clicking the login button.

**Comment by Steimel** [comment]
That works! Thanks for the very quick response

**Comment by Nightfirecat** [comment]
We've released 1.7.20.1 which fixes this issue.
