### ISSUE TITLE
Quality of Life for Mouse Click Counter Plugin

### ISSUE THREAD

**Issue by soccerplayr** [runelite/runelite#14047]
Could it be possible to add an option in the settings for the Mouse Click Counter plugin that it resets upon every Login? It would be nice to see how many clicks you do in 1 session. I know you can manually reset it for this but having it automated would be nice.

In addition to the above, could you take it one step further to export the number of clicks per session into a notepad? Something like;

Login: 8/20/21 / 1400-1634 / 42124 
Date / Time / Clicks

**Comment by Nightfirecat** [comment]
The Mouse Click Counter plugin is a hub plugin, and not maintained by the RuneLite team. Please open this request on their repository instead.
