### ISSUE TITLE
Use Boss Health Overlay in Opponent Information

### ISSUE THREAD

**Issue by ulises-c** [runelite/runelite#14040]
Merge the "Show boss health overlay" setting in OSRS with "Opponent Information" plug-in from Runelite

OSRS's "Show boss health overlay" setting provides accurate hitpoint information for certain bosses, but many players find the size of the info box too large.

A proposed solution is to gather the information from the built in setting and feed that into the "Opponent Information" plug-in, and then replace the large health overlay with the small Runelite one

**Comment by Nightfirecat** [comment]
Duplicate of #12137
