### ISSUE TITLE
Grand Exchange (Default RL plugin) goes to new website, with new default browser

### ISSUE THREAD

**Issue by ltmetalman** [runelite/runelite#14054]
Grand Exchange plugin's price check sends me to a different website now, not sure if its a default browser change or on the update end... Would like a way to get back.

I have been using the plugin Grand Exchange, which usually takes me to <https://prices.runescape.wiki/osrs/>.
I have been using Vanilla Chrome as my default browser, therefore it opens there.
I switched my default browser to Google Chrome Canary. Now when I click an item, it takes me to <secure.runescape.com> which has a layout that doesn't help me as much. Would like to get to the other website.

Example:
Input: Search in app > type "pot" > enter > click on first item (Guam Potion -unf)
Output: <https://secure.runescape.com/m=itemdb_oldschool/Guam+potion+%28unf%29/viewitem?obj=91>

As I understand it, Chrome Canary, being a beta/developer version, is still referred to as chrome.EXE but the file location is different, so I hope that explains this issue.
Win10
Canary: "C:\Users\[derp]\AppData\Local\Google\Chrome SxS\Application\chrome.exe"
Vanilla: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"

Would like to get back to the old site. Can't figure it out from other places.

**Comment by Nightfirecat** [comment]
Enable `RuneLite` > `Use actively traded price`.

**Comment by ltmetalman** [comment]
It was already enabled

**Comment by ltmetalman** [comment]
I don't see why this was closed.... its not resolved

**Comment by Nightfirecat** [comment]
We haven't changed this code at all recently, so there's no way this could've changed for you. Please join our Discord server and inquire further in the `#support` channel if this behavior is continuing

**Comment by ltmetalman** [comment]
thank you. That is helpful...
