### ISSUE TITLE
Client freezing when teleporting to grand exchange 

### ISSUE THREAD

**Issue by Teminheit** [runelite/runelite#14069]
**Describe the bug**
Whenever I teleport to the GE after playing for a couple of minutes or hours my game freezes completely, I can click the sidebar with all the plugins but once I minimize the sidebar a copy of it freezes and covers some of the frozen game. I've recreated it and I think it happens because I click off the client and on to another tab while teleporting (I've tested again and it happens even if I don't click out).

**To Reproduce**
1. Be anywhere outside the GE
2. Wait a few minutes
3. Teleport back to the GE

**Expected behavior**
No freezing while teleporting to the Grand Exchange

**Screenshots**
![freeze](https://user-images.githubusercontent.com/89614611/131050389-e6b4bbee-c6bd-4f73-8f1b-ae85ac87e9af.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.7.21.1
 - Launcher version: 2.17

**Additional context**
https://pastebin.com/Kanrch1P

**Comment by Teminheit** [comment]
Issue was the new Roof Removal plugin, after disabling said plugin, the game stopped freezing when teleporting.

**Comment by Nightfirecat** [comment]
This should be fixed internally and working in our next release FYI
