### ISSUE TITLE
World Map option/toggle to display multi-combat chunks and DMM safe areas

### ISSUE THREAD

**Issue by Zaino60** [runelite/runelite#14085]
**Is your feature request related to a problem? Please describe.**
Would be useful for new DMM players and in main game for when going to wildy without having to know by memory which chunks exactly are multi and which are not

**Describe the solution you'd like**
When you open the world map there would be a button that if toggled on it would display all multi-combat chunks in a lighter shade of red and if on a DMMT/DMM world maybe also display safe areas in a lighter shade of green

**Describe alternatives you've considered**
DMM's "You have entered a multi-combat area" chat message for main game wildy.

**Additional context**
Display could work similarly to the Plugin Hub's "Region Locker" https://github.com/slaytostay/region-locker

**Comment by Hydrox6** [comment]
Banned by the [Jagex Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1):
> Indicates multicombat zone boundaries

Showing DMM safezones would likely fall under a similar category.
