### ISSUE TITLE
Slayer counter not working for monster variants?

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#14099]
I was killing reanimated abyssals on an abyssal demons task and noticed the slayer counter is not updating when I get the xp drop. (Reanimated abyssals do count as abyssal demons for the purpose of slayer task.) Not sure what all is affected.

**Comment by Nightfirecat** [comment]
When do you get the xp drop for reanimated monsters? It's possible this is caused because of some unique behaviors specific to those.

**Comment by Nightfirecat** [comment]
Fixed in 2eba3a886fb1d7c5292f84ea4326e1561fca90b4
