### ISSUE TITLE
Friends Chat Messages

### ISSUE THREAD

**Issue by ThManHimself** [runelite/runelite#14094]
Just started developing a plugin with a friend. We are trying to be able to broadcast a loot message to a Friends Chat. We made it as far as being able to be able to specifically send it to ourselves using `.addChatMessage` but we havn't yet determined how to send a message to everyone in the FC. Is there a different method besides `.addChatMessage` that we can use to make this happen or is it what is inside the `()` after addChatMessage that needs to be altered?

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

Though to be short: this is against the rules, as specified in the [Jagex Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1)

**Comment by ThManHimself** [comment]
I dont see anything about chat messages in that Jagex Statement

**Comment by Hydrox6** [comment]
It's actually just straight up autotyping. I thought the statement had a more generic line for 
> Adds additional menu entries which cause actions to be sent to the server

**Comment by ThManHimself** [comment]
Thanks for the clarification.
