### ISSUE TITLE
Galvek waves not showing on screen

### ISSUE THREAD

**Issue by greenbstud** [runelite/runelite#14093]
I am having an issue with Runelite where it wont even show the waves that galvek uses on wave 3.
I  also had an issue when doing the Lair of Tarn Razorlor where it would not showing the moving trap actually moving.

I thought this might be down to having GPU on but no difference when i turned it off, entity hider is not on.

any ideas what might be causing this issue?

**Comment by Nightfirecat** [comment]
I've never heard of either of these issues happening before. Can you upload your `client.log` file? Instructions to find it [are available on our troubleshooting wiki page](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client).

**Comment by Nightfirecat** [comment]
Since this issue has not bee reproduceable and has not been updated in some time, I am closing it.
