### ISSUE TITLE
Please shutdown RuneLite to force their hand

### ISSUE THREAD

**Issue by Haaroon** [runelite/runelite#14106]
It's quite apoorling and frankly disgusting  behaviour that they basically allowed you to waste your time to develop a HD plugin for thousands of hours. Then seemingly pulled the plug threatening legal action. 

It saddens me to say, but I think the best course of action is to shutdown RuneLite which may unfortunately cause those who rely on this amazing tool to perhaps leave. 

I enjoyed playing OSRS and did so because of this plugin. It is clear the community voice is never heard nor respected.

**Comment by raiyni** [comment]
The issue tracker is meant as a forum for reporting issues with the client and suggesting features. You are free to join our Discord for other discussions.

**Comment by Haaroon** [comment]
> The issue tracker is meant as a forum for reporting issues with the client and suggesting features. You are free to join our Discord for other discussions.

I did suggest a feature, the feature is to shutdown the project.
