### ISSUE TITLE
NPC Indicator ghosting between sessions

### ISSUE THREAD

**Issue by abrman** [runelite/runelite#14123]
NPC Indicator seems to remember highlights across sessions. (login/logout)

**Describe the bug**
1. Have your settings to highlight any NPC visible
2. Log out and log back in
3. The NPC will keep moving, but a new ghost of the NPC will appear in a offset location.

**Expected behavior**
No ghosting of NPC indicators are intended

**Screenshots**
In these screenshots I logged in and out of one account without moving, 
and logged back in on second account.
![Initial login](https://i.imgur.com/ftoQldT.png)
![Second login with another account](https://i.imgur.com/0pq1XhU.png)
Game after several re-logs:
![Several logins in the same location](https://i.imgur.com/1uFOjyo.png)

**Environment**
 - OS: Windows
 - RuneLite version: 1.7.23
 - Launcher version: 2.1.7

**Comment by Adam-** [comment]
fixed in 3c5f8123313b5f52027b5b2bd32f6c6c0d49dea1

**Comment by abrman** [comment]
![Screenshot](https://i.imgur.com/1nzFMNC.png)

Can't reproduce, but want to bring awareness to the bug still being present.
Think it may have been caused when returning from a random event? (Flippa's pinball random event)

Sorry for incomplete reproduction guide, first occurrence since runelite updated.
