### ISSUE TITLE
Hi, could we PLEASE get a larger health bar?  The current one is too short

### ISSUE THREAD

**Issue by MyopicHuman** [runelite/runelite#14127]
The problem is that I like to PvP and knowing what your health is, as exactly as possible, is important.

This is why I would LOVE to have a longer health bar, so it's easier to see how much hp I have

Numbers over the current health bar would also be amazing

**Comment by Whowhos** [comment]
![show](https://user-images.githubusercontent.com/90527043/132958474-c3add2f0-52b5-45a6-ac95-63db4d280c4c.PNG)

**Comment by Whowhos** [comment]
![statusbarsrl](https://user-images.githubusercontent.com/90527043/132958493-40918eac-c3a6-41fe-bf5e-e1a8821ade40.png)

**Comment by MyopicHuman** [comment]
Thank you!

**Comment by Whowhos** [comment]
You're welcome

**Comment by Hydrox6** [comment]
The healthbar above the player is limited, since the values used for it aren't representative of the actual health values; this is a Jagex limitation. A wider health bar would not make it more granular. Status Bars or the hp orb are much better ways of showing this.
