### ISSUE TITLE
Shift click walk here

### ISSUE THREAD

**Issue by kulershk** [runelite/runelite#1412]
Would be nice if you could use shift click to walk under npc

**Comment by SoyChai** [comment]
Clever idea, I would've never thought of this.

We could make this even more universal by allowing shift-clicks to interact with objects behind NPCs too.

**Comment by kulershk** [comment]
For bossing it would be really helpful

**Comment by Fryslan** [comment]
I would realy like this feature

**Comment by beshj** [comment]
please add this it is literally the most needed feature not in the game....

**Comment by deathbeam** [comment]
Based on discord discussion I don't think we want to implement this
