### ISSUE TITLE
clan notifier plugin suggestion

### ISSUE THREAD

**Issue by kohaas** [runelite/runelite#14121]
i was wondering if we could make a clan notifier plugin so when someone trys to join your clan it says they wanna join
because alot of times i dont see when it says someone is trying to join or people spam in the chat box so i cant see it
so could we make a overhead notifier plugin so people can see it better?

**Comment by Nightfirecat** [comment]
I don't understand this request. Can you add part of the text from a player trying to join your clan to the plugin so it would notify you upon that text being sent?

**Comment by kohaas** [comment]
well when i recruit people at the ge alot of people type so the "this user is trying to apply for your clan"
text i dont see in time and i scroll up about 10 minutes later to see that and when i try to recruit them
its too late they arent trying to join anymore and they arent in the applicants list.

when it says "atmosdelics has applied for your clan" its only for a few seconds if i look down in the chat box in time
i notice it but people are usually talking so much in the ge.

**Comment by Twiglet1022** [comment]
You should be able to do this with the Chat Notifications plugin already like this

![image](https://user-images.githubusercontent.com/29353990/134224651-18f0047f-6979-4a14-9368-de2bb2b7935b.png)

**Comment by Nightfirecat** [comment]
I agree with Twiglet here, this seems like a perfect case for the already-existing Chat Notifications plugin.
