### ISSUE TITLE
Unable to turn on GPU plugin despite meeting hardware requirement

### ISSUE THREAD

**Issue by TheLGRoute** [runelite/runelite#14134]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
My pc is unable to turn on the GPU plugin. Everytime I turn on GPU, it takes a moment then immediately turns itself off. Graphics unchanged. My pc's processor is Intel Core i5-4440 CPU @ 3.10GHz, no separate graphics card. It has 7GB free RAM, runs Windows 8.1.

**To Reproduce**
Everytime an attempt is made to enable the GPU plugin.

**Expected behavior**
Expected GPU plugin to enable.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 8.1
 - RuneLite version: 1.7.24
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

No crashes, RuneLite functions completely fine - just unable to turn on the plugin.

**Comment by JBerben** [comment]
Have you tried running RuneLite with the --debug option set? That might produce some more information on the problem I think

**Comment by TheLGRoute** [comment]
> Have you tried running RuneLite with the --debug option set? That might produce some more information on the problem I think

I have not. How should I go about doing that?

**Comment by JBerben** [comment]
If you don't have the RuneLite.jar file, download it from the RuneLite website, then run it using "java -jar RuneLite.jar --debug" in the directory that you saved the jar file in. Here are some pictures I took that might help out in doing this.

### Downloading the RuneLite.jar
![instruction1](https://user-images.githubusercontent.com/12043246/133043344-37b7143f-7090-471e-8b16-1c21d101a99b.png)

### Running the jar in debug mode
![instruction2](https://user-images.githubusercontent.com/12043246/133043390-88554410-a0bb-40bf-b890-a28403c5c123.png)

Then keep an eye on the console whilst you're trying to replicate the issue. That should provide a bit more detail on the issue :)

**Comment by TheLGRoute** [comment]
Hmm.. got the following error when I tried to run the file in debug mode. 

![image](https://user-images.githubusercontent.com/90597630/133048748-bf2f98c3-bb8b-460f-9a77-70fc4adda385.png)

**Comment by JBerben** [comment]
I'm not on a Windows machine, but I just checked my gf's machine and try running java from the Runelite folder in your Local folder in AppData. If you press windows key + r and type %appdata% and enter, go to the "Local" folder and then "Runelite" folder. You should see a "jre" folder and then a "bin" folder inside of it. Once you are there, type "cmd" inside the folder navigation bar.

Typing "java" from here will run the up to date version that RuneLite uses, but instead the command being
"java -jar RuneLite.jar -- debug"
it will be "java -jar PathToFolderThatRuneLiteJarIsInsideOf/RuneLite.jar --debug"

I hope this helps, and I'm curious and ready to help solve your problem. I just need that sweet debugging info :)

**Comment by TheLGRoute** [comment]
That ran! Never knew a feature like this existed. I tried to enable the plugin and the below appears. Granted, I was told that my pc is a bit dated and any older would not support the OpenGL version that GPU plugin needs. Hope the below shows the information needed. 

![image](https://user-images.githubusercontent.com/90597630/133055012-ed9fc1e6-e89f-4b66-9090-7647f528eb8f.png)

**Comment by JBerben** [comment]
Great! Do you have OpenGL installed? I believe it needs GL4.
Does your computer have a graphics card, or are you running it on integrated graphics?
Have you updated the drivers on your graphics card? 

Sorry for all the questions, but when I follow the stack trace you posted, and looked at the GPU plugin code, I couldn't find a definitive reason for your issue. The problem is that its unable to compile the shaders at the plugin startup, but I'm not 100% sure what is causing that. Check out the things I listed above and get back to me :)

**Comment by abextm** [comment]
The issue tracker is not a support form; use [Discord](https://runelite.net/discord) instead. This is an older iGPU on an older version of windows which probably does not support a modern enough version of OpenGL.

**Comment by TheLGRoute** [comment]
Apologies for posting in the wrong place, but appreciate all the help. I'll settle for playing without the plugin then.
