### ISSUE TITLE
Plug-in that takes screenshots with random intervals

### ISSUE THREAD

**Issue by victordegnbol** [runelite/runelite#14136]
The plug-in goes like this: it will randomly screenshot your game (but not too often). Why? When you look through your screenshot folder in the future you will see yourself doing all sorts of content, some of which is content that you'd normally not even think about screenshotting.

; Lightweight plug-in and more memories... for me that's a win-win!

**Comment by Nightfirecat** [comment]
You would be much better served running some recording software occasionally and saving that recorded video, or something of the sort.
