### ISSUE TITLE
Zoom bug

### ISSUE THREAD

**Issue by kulershk** [runelite/runelite#1413]
If inner zoom is enabled it pops to the middle when click and has zoomed in if outer enabled then pops middle if u zoomed out!
![image](https://user-images.githubusercontent.com/26186873/38674019-b3fc2772-3e5b-11e8-9e36-a3719024fdcc.png)

https://gyazo.com/27195b6a9cd1ce8160239ccf98e23a24

**Comment by deathbeam** [comment]
Fixed in #1416
