### ISSUE TITLE
Shadow disable option

### ISSUE THREAD

**Issue by Jaedan3101** [runelite/runelite#14149]
Currently when disabling shadows, the side of the object in while the shadow would emit stays very dark making the game very difficult to look at with shadows off, and on in my opinion, I play for long hours and I need something easy on the eyes. An hd touchup to the original look of the game. 

The first picture is HD on and the second is HD off.

![image](https://user-images.githubusercontent.com/61707368/133295827-cb16dca8-4ea3-4cf8-be3b-456fcb0a5f13.png)

![image](https://user-images.githubusercontent.com/61707368/133296147-2cc5db54-c71d-45e7-94c6-2fbdcca2ca21.png)

**Comment by Nightfirecat** [comment]
We don't have shadows support in the client. Issues/requests for 117's HD plugin should be directed to [his project](https://github.com/RS117/RLHD) instead.
