### ISSUE TITLE
Game does not run

### ISSUE THREAD

**Issue by AndnixSH** [runelite/runelite#14147]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The game does not run inside, it's just an empty frame. I have deleted all settings and reinstalled it, and make sure GPU plugin is disabled. The official OSRS client which is Java based works perfectly

**To Reproduce**
1. Launch RuneLite

**Expected behavior**
I expetected it to work

**Screenshots**
![image](https://user-images.githubusercontent.com/40742924/133273623-b4c2dc7d-456e-4521-b3f1-30c07f90bf76.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.7

**Additional context**
[client.log](https://github.com/runelite/runelite/files/7162607/client.log)
[launcher.log](https://github.com/runelite/runelite/files/7162609/launcher.log)

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
