### ISSUE TITLE
running operation system on usb hd plugin wont start/fan goes faster

### ISSUE THREAD

**Issue by kohaas** [runelite/runelite#14154]
when i start the runelite hd plugin it wont start im running a operating system on a usb
but on my other computer it starts fine and also i notice on my computer the plugin seems
to make the fan go faster.

the plugin is awesome these are just some bug reports.

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
