### ISSUE TITLE
issues enabling the GPU Plugin, on laptop

### ISSUE THREAD

**Issue by joshwaa1** [runelite/runelite#14155]
When i enable the GPU Plugin it automatically gets disabled within 2-4 seconds after turning it on, tried to reinstall runelite, and drivers but no luck. 
i've also changed the Nvidia settings so runelite uses my GTX1070 but when looking through the logs(see 1st image below)

![image](https://user-images.githubusercontent.com/14219904/133482566-7e310646-02cb-4678-8ec3-2deab21dd4af.png)
its like its still looking at the intergrated graphics, even though i've pointing the application to my 1070 

![image](https://user-images.githubusercontent.com/14219904/133482595-dc9e948b-e9b7-4aff-aad8-154f72affaac.png)
![image](https://user-images.githubusercontent.com/14219904/133483082-5a43b051-f6eb-42b8-af57-88400ef8b1dc.png)

any ideas?

**Comment by Nightfirecat** [comment]
What driver version do you have installed?

**Comment by joshwaa1** [comment]
for Nvidia the very latest, which i re-installed
![image](https://user-images.githubusercontent.com/14219904/133489312-181169be-a467-4223-8ecf-2f59554c64b4.png)

**Comment by Nightfirecat** [comment]
471 drivers have been problematic with the GPU plugin for a while, we recommend downgrading to 466.77.

Anyway, this is not a bug with the GPU plugin, but with your setup, so if that does not resolve the problem, we can continue troubleshooting in the `#support` channel on Discord.
