### ISSUE TITLE
Visual bug when using twisted home teleport next to a wall in the mythics guild 

### ISSUE THREAD

**Issue by therealzonder** [runelite/runelite#14158]
**Describe the bug**
When using the home teleport (with the twisted league animation, I haven't tried with the default) on some tiles in the myths guild, the wall texture goes solid for the first part of the animation. Seems to happen more often if the camera is positioned closer to the ground. See screenshot

**To Reproduce**
1. Go to Myth guild
2. Go to tiles in screen shot 
3. Position camera low
3. Use home teleport 

**Expected behavior**
The wall should continue to look like a wall throughout the animation 

**Screenshots**
https://imgur.com/a/IesSZoh

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 10.0.19043 
 - RuneLite version: 1.7.2.4
 - Launcher version: 2.1.0
- GPU RX480; driver version 21.8.1

- **Additional context**
[client.log](https://github.com/runelite/runelite/files/7181494/client.log)
[launcher.log](https://github.com/runelite/runelite/files/7181495/launcher.log)

**Comment by Nightfirecat** [comment]
What does this look like with the GPU plugin turned off?

**Comment by therealzonder** [comment]
It looks the same. My apologies, I guess its not the plugin at all.
