### ISSUE TITLE
Runelite is perm bugged after runlite hd

### ISSUE THREAD

**Issue by bshaun24** [runelite/runelite#14152]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)
[](url)
**Describe the bug**
i installed runelite hd turned on the anti aliasing and it bugged out. i uninstalled hd and it didnt fix it and ive unistalled and reinstalled runelite mutiple times still does it.
**To Reproduce**

**Expected behavior**
the hd plugin to work and this weird visual gitch to stop

**Screenshots**

**Environment (please complete the following information):**
 - OS: windows 10
 - RuneLite version: 1.7.24
 - Launcher version: 2.17
[client.log](https://github.com/runelite/runelite/files/7165666/client.log)
[launcher.log](https://github.com/runelite/runelite/files/7165667/launcher.log)
[client_2021-09-13.0.log](https://github.com/runelite/runelite/files/7165668/client_2021-09-13.0.log)
[launcher_2021-09-13.0.log](https://github.com/runelite/runelite/files/7165669/launcher_2021-09-13.0.log)
[client_2021-09-07.0.log](https://github.com/runelite/runelite/files/7165670/client_2021-09-07.0.log)
[client_2021-09-06.0.log](https://github.com/runelite/runelite/files/7165671/client_2021-09-06.0.log)
[launcher_2021-09-06.0.log](https://github.com/runelite/runelite/files/7165672/launcher_2021-09-06.0.log)
[client_2021-09-05.0.log](https://github.com/runelite/runelite/files/7165673/client_2021-09-05.0.log)
[launcher_2021-09-05.0.log](https://github.com/runelite/runelite/files/7165674/launcher_2021-09-05.0.log)

https://user-images.githubusercontent.com/86626361/133346255-2b857b02-e927-4a06-86e8-f640db06650f.mp4

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment]
This is a known issue, [with a fix described at length on this wiki page.](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration)
