### ISSUE TITLE
Crackling Audio when game is open

### ISSUE THREAD

**Issue by TheGreatestJannet** [runelite/runelite#14167]
**Describe the bug**
When the game is open my system audio crackles and pops constantly. I have pipewire-alsa installed and if I open pw-top I have a huge amount of ERR next to runelite. When the game isn't open audio is fine.

**To Reproduce**
1. Install pipewire-alsa.
2. Open Runelite
3. Hear crackling and see ERR in pw-top

**Expected behavior**
The audio shouldn't crackle or produce any ERR in pw-top

**Screenshots**
![image](https://user-images.githubusercontent.com/51300636/133896600-39017f19-4733-46f7-b7cd-b16197ac3c35.png)

**Environment (please complete the following information):**
 - OS: Arch Linux 
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.3

**Additional context**
This is the only program on my system to produce this crackle. I have also tried PIPEWIRE_LATENCY=4096/22050 1024/22050 4096/4800 4096/22050 and it still produces ERR and crackle. Maybe an option to completely disable sound output so it doesn't make a sink could be a workaround for the time being.

**Comment by Alexsuperfly** [comment]
Idk what pipewire is but we do have #3525 which instructs people to try `pulseaudio-alsa` if they have sound issues on linux.  Is that something you can do?

**Comment by TheGreatestJannet** [comment]
I have pipewire-alsa installed which does the same a pulseaudio-alsa. Pipewire is an alternative to pulseaudio: https://pipewire.org/ that is the default in fedora and think Ubuntu is switching to it soon as well.

**Comment by abextm** [comment]
https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Troubleshooting#underrununderflow-and-broken-pipe-errors

**Comment by TheGreatestJannet** [comment]
so what's the fix? It's a pipewire issue?

**Comment by MrCarroll** [comment]
Try using `export PULSE_LATENCY_MSEC=100` prior to running the game. Despite saying Pulse in the name this also works for PipeWire (as long as it's using an actual Pulseaudio client connection to the Pipewire server).

Not really a fix as such because it's basically sidestepping the problem if it works. If it doesn't work, try adjusting the value up/down (Realistically I think things start breaking if you go below 30, and as you go over 100 you're going to begin to perceptably identify the audio latency).

**Comment by johan-bjareholt** [comment]
@MrCarroll Thanks, works flawlessly. 100 wasn't enough for me but 1000 does, will try to find the perfect value for my computer at a later point (as I assume that it will depend on hardware).

Really wonder what's causing the issue though...
