### ISSUE TITLE
Ping not displaying for worlds

### ISSUE THREAD

**Issue by deruginm** [runelite/runelite#14163]
**Describe the bug**
In the World Hopper menu, ping is supposed to display under the "ping" column. Ping is instead displayed as a dash "-" for all worlds. Restarting Runelite, un-checking and re-checking settings does not solve the problem.

**To Reproduce**
1. Go to world hopper menu
2. Click off and on the "Show world ping"
3. Check the worlds if they are displaying ping

**Expected behavior**
The worlds ping relative to me, the user, is to be expected

**Screenshots**
https://imgur.com/a/Lylb9YV

**Environment (please complete the following information):**
 - OS: Windows 7
 - RuneLite version: ?? 
 - Launcher version: ??

![Ping Bug](https://user-images.githubusercontent.com/90934287/133848765-689d376f-5e39-454e-b198-ee3128b2585a.png)

**Comment by chloroken** [comment]
This is also happening to me. No current ping nor world hopper pings are displayed.

Began this week. No changes to modem/router settings from my end. More than happy to provide information for the dev(s) if they want to look into what's causing this for the few affected. Thanks.

**Comment by deruginm** [comment]
Why was this labeled with "need-information" @Nightfirecat? What more information could I provide? Is there any way to bump this thread? I would really like this issue resolved.

**Comment by Adam-** [comment]
> Why was this labeled with "need-information" @Nightfirecat? What more information could I provide? Is there any way to bump this thread? I would really like this issue resolved.

Most likely this isn't a RuneLite issue, and instead your network filters icmp. If you can show that that is not the case then maybe we would look deeper.

**Comment by chloroken** [comment]
This resolved itself with no action from me in late January.

Was highly frustrating though, especially because nobody had answers for me and I couldn't figure it out on my own.

**Comment by deruginm** [comment]
> This resolved itself with no action from me in late January.
> 
> Was highly frustrating though, especially because nobody had answers for me and I couldn't figure it out on my own.

The same exact thing happened to me... On all 3 devices that I use simultaneously...

**Comment by chloroken** [comment]
Yeah, the dev's indifference to the issue combined with the fact that it resolved itself over multiple devices lends credence to the idea that the issue was truly ISP-related. This kind of thing is why I feel bad for devs in general—if something out of their hands goes awry, they're often blamed for it anyway.

Hopefully, the issue doesn't return. It actually pushed me over the edge of quitting, and I didn't return until it was 'fixed'.

**Comment by Nightfirecat** [comment]
As Adam mentioned, this is almost certainly not an issue on RuneLite's end. Should someone have this issue in the future and can identify (via logs or some other method) that it is something wrong on our end, please raise a separate issue and we can look to fix it.
