### ISSUE TITLE
Roof removal camelot castle first floor bug

### ISSUE THREAD

**Issue by mithom** [runelite/runelite#14160]
**Describe the bug**
when going to the first floor, a part of the 3th floor is visible, this is the same scenario as with varrock castle training grounds
![image](https://user-images.githubusercontent.com/9282831/133773275-7df28ff3-334b-422b-b404-6e3422242c18.png)

**To Reproduce**
go up camelot castle to the first floor

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.6
the screenshot is in combination with 117 HD

**Comment by Nightfirecat** [comment]
Fixed in 5723c397a74a2c3c2d4108e97c4b2ec8a9c211c4
