### ISSUE TITLE
Excessive fog/ground not rendering after suspending in Ubuntu

### ISSUE THREAD

**Issue by Kh1ng** [runelite/runelite#14173]
When returning to game after suspending on Ubuntu game is extremely foggy.

1. Run runelite HD on linux (I'm on ubuntu 20.04)
2. Go AFK computer suspends
3. Relog

**Expected behavior**
When relogging there is a lot of fog/ground not rendering, see screenshots. This is usually fixed by restarting runelite. I've also had a completely black screen once which required a system restart, not sure if same issue.

**Screenshots**
![Screenshot from 2021-09-20 09-24-49](https://user-images.githubusercontent.com/89691651/134019540-b4d0cb08-ca42-4039-bb58-17d7284354b2.png)
![Screenshot from 2021-09-20 09-24-38](https://user-images.githubusercontent.com/89691651/134019543-bbde345f-b712-4516-b977-5c7c07cb4848.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04

 - RuneLite version: 1.7.24
 - Launcher version: 1.6.2

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
