### ISSUE TITLE
Left-click availability for Building?

### ISSUE THREAD

**Issue by Krill7** [runelite/runelite#14176]
Is your feature request related to a problem? Please describe.
Not a problem. I would like to train Construction with slightly less effort and with a slight increase in efficiency.

Describe the solution you'd like:
I would like an addition to the Menu Entry Swapper plug-in that allows for the toggling of 'Build Seating Space', 'Build Door Hotspot', and 'Remove gnome bench' etc. with left-click options for these actions. I don't know much about coding, so I would take a different plug-in if it required one!

Describe alternatives you've considered:
I have considered not being a complainer and just sticking with the right-click method.
I have done Mahogany Homes.

Additional context:
I think that many people would like this, and it could be a huge QoL change.

**Comment by Bram91** [comment]
As answered yesterday in https://github.com/runelite/runelite.net/issues/439

This would go directly against the following rule:

> Modifies menu options for construction, such as prioritising build/remove options

https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1
