### ISSUE TITLE
Suggested cannon spot at Shayzien Lizardman Canyon outdated

### ISSUE THREAD

**Issue by AmazingJesus** [runelite/runelite#14184]
Since the rework to the area the suggested cannon safespot isn't correct anymore.
![image](https://user-images.githubusercontent.com/39392593/134540049-985126ae-5569-41b6-84d7-f7de6526cf74.png)
![image](https://user-images.githubusercontent.com/39392593/134540119-46e0ab50-21bf-4c96-87a6-c2df5385b76f.png)

**Comment by AllanOcelot** [comment]
Is there a new/better spot I can move it to, or should it be removed?

**Comment by AmazingJesus** [comment]
> Is there a new/better spot I can move it to, or should it be removed?

I don't know, maybe someone can suggest one? 
I just placed my cannon 2 tiles south if I remember correctly, but I don't know if that is the best spot for it.
