### ISSUE TITLE
Bank Filler Icon With Spellbooks

### ISSUE THREAD

**Issue by Hoselater** [runelite/runelite#14191]
Sorry I am not adept with coding; but if it is easy to give a spellbook icon to bank fillers? With Standard, Ancient, Lunar, and now the Arceuus rework, its hard to keep what spell set I need to go to. Having the icon of that book in the bank doesnt seem game breaking or (without any knowledge) abusive. I know I am bad and dumb but if its an easy addition I would appreciate it.

**Comment by Nightfirecat** [comment]
This is not a feature we plan to add to the core client. Something like [the Inventory Setups hub plugin](https://runelite.net/plugin-hub/show/inventory-setups#user-content-editing-a-setup) should satisfy your use case, as it can have a specific spellbook selected.
