### ISSUE TITLE
117 HD Plugin MacOS 11.6 Big Sur

### ISSUE THREAD

**Issue by sethrh2009** [runelite/runelite#14196]
Hi,
Im having an issue with runelite HD pluggin.  When running it shows shadows on all objects as pictured.  I've tried this on my MacBook and iMac.  Both are having the same issue.  I have tried to look for this same issue but cannot find a way to resolve this.  Any suggestions would be appreciated!

Thanks

<img width="1234" alt="Screen Shot 2021-09-27 at 11 15 40 AM" src="https://user-images.githubusercontent.com/91487805/134947087-66111cee-963f-4519-89e8-14e84392f108.png">

<img width="991" alt="Screen Shot 2021-09-27 at 11 25 04 AM" src="https://user-images.githubusercontent.com/91487805/134947956-de1271dc-6be1-4b88-8ad0-165a71f39149.png">

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
