### ISSUE TITLE
Super Antifire Potion Countdown Timer off?

### ISSUE THREAD

**Issue by SlowPuzzler** [runelite/runelite#14194]
It seems to me that the count down timer for the extended super antifires is off by like 10 seconds. Meaning the effect of the potion ends, but the timer still says you have 10 seconds or so. Find myself having to redose early or get merked by dragonfire. The chat box notification even says the potion expires while the countdown still has time.

**Comment by Nightfirecat** [comment]
Duplicate of #8422. As far as we're aware, no data is sent from the server (aside from the low time remaining/expiry chat messages) regarding antifire type and duration.
