### ISSUE TITLE
Pin plugins to the top of the configuration tab

### ISSUE THREAD

**Issue by Josh-Priest** [runelite/runelite#14190]
I would love to be able to quickly access certain plugins I reconfigure often - For example, I flip between 117 HD and the GPU plugin when doing certain content, or I turn off true tile after doing content that I use it for. 

I think a solution to this would be a way to "pin" or "favorite" plugins to the top of the configuration tab.

**Comment by Alexsuperfly** [comment]
click the star icon next to the plugin name
