### ISSUE TITLE
Menu Entry Swapper -- Eternal Teleport Crystal?

### ISSUE THREAD

**Issue by Fe-Knee** [runelite/runelite#14201]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Frustrating every time I click that teleport, and find myself in Lletya instead of Priff

**Describe the solution you'd like**

Have an option under the Menu Entry Swapper, so that you can left click - teleport to priff. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Hydrox6** [comment]
Use [Shift Click Configuration](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#customizable-shift-click)

Otherwise, this is a feature of [Menu Swapper Extended](https://runelite.net/plugin-hub/show/menu-swapper-extended) in the plugin hub
