### ISSUE TITLE
Ground Items plugin Despawn timer not showing on arrows dropped on ground from Ranged skill

### ISSUE THREAD

**Issue by patcolyn** [runelite/runelite#14209]
**Describe the bug**
The 'Ground Items' plugin's Despawn timer does not show the timer for arrows dropped on ground from Ranged the skill.

**To Reproduce**
1. Enable Despawn timer in Ground Items plugin
2. Fire arrows at a target until an arrow drops on the ground
3. See error

**Expected behavior**
Despawn timer shows on items dropped on the ground

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.24
 - Launcher version: 2.1.7

**Comment by Nightfirecat** [comment]
You're not dropping arrows, you're firing them, which is very different. Fired ammunition also does not create a despawn timer when fired at normal NPCs, so this case wouldn't work either.

We're not likely to add this functionality as it's much more complex and likely error-prone than other item despawn timers.
