### ISSUE TITLE
Phosani's Nightmare hiscore icon is incorrect.

### ISSUE THREAD

**Issue by AngelZodiac** [runelite/runelite#14214]
**Describe the bug**
Phosani's Nightmare has a different icon than the regular version on the hiscores, RuneLite does not distinguish between the two visually.

**To Reproduce**
Look at the Phosani's Nightmare icon on the hiscore function.

**Expected behavior**
Weird egg thing displayed rather than Nightmare's head.

**Comment by Hydrox6** [comment]
iirc we decided against the egg because it just looks bad and nondescript. A smaller icon of the transmogged pet would probably look a lot better, though maybe it would be a little too small
![](https://oldschool.runescape.wiki/images/c/c5/Little_parasite.png?f5471)

**Comment by fifo1175** [comment]
where can the icons be changed?

**Comment by Felanbird** [comment]
Fixed in 0304007f4e3c61eab0d7c1b1e6947c8957426bda
