### ISSUE TITLE
Add "Randomize World" option to World Hopper plugin.

### ISSUE THREAD

**Issue by Gridleak** [runelite/runelite#14213]
It always sucks to be right behind someone using the plugin while trying to buy things from a shop. Or trying to hop 20 worlds ahead but catching the next person. I think if there was an _option_ for randomizing worlds people would play "cat and mouse" at shops less often.

**Comment by Hydrox6** [comment]
You can always just pick a semi-random world in the list. Those users jumping ahead of you are likely trying to force you to do that instead; those people would likely not use the feature intentionally. Alternatively they could just be exclusively using the keybind to hop and are double hopping ahead to try and force you out, and so would likely not use a feature that would end up being on the sidebar.

As such, this is so incredibly narrow that it would really not be worth implementing solely for the space it will take up on the UI.

**Comment by rugg0064** [comment]
https://runelite.net/plugin-hub/show/random-hopper
