### ISSUE TITLE
Add Dinh's Bulwark to the special attack counter plugin

### ISSUE THREAD

**Issue by jeffm9500** [runelite/runelite#14210]
With a [recent update](https://oldschool.runescape.wiki/w/Update:Wilderness_%26_Equipment_Rebalance_Changes), the Dinh's Bulwark special attack gained stat draining abilities. This makes it usable at Corp (an alternative to the BGS). Adding a counter for this weapon to the Special Attack Counter would be helpful in this capacity.

The counter should track each special attack use, whether the attack is successful or not (since the stat reduction applies regardless).

**Comment by Adam-** [comment]
Added in e60ce99081d5908cb3e2d7f87c9ce7cba0f9051b. We looked at the claim of it draining each attack regardless of if it is successful or not, however we think it isn't true. So we've made it work like how the dragon warhammer counter works.
