### ISSUE TITLE
Include Dinh's Bulwark in Special Attack Counter

### ISSUE THREAD

**Issue by Karambtwo** [runelite/runelite#14218]
With the recent changes to the Dinh's bulwark, it can now be used to lower stats at places like corp instead of a BGS. It now lowers offensive stats by 5% at a time. As was the issue with the spec weapons previously, if using it to spec down corp, the player must count all specs. Since this is now viable, I think it should be added to the counter.

**Comment by Hydrox6** [comment]
This was already added in e60ce99081d5908cb3e2d7f87c9ce7cba0f9051b, and will be in the next release
