### ISSUE TITLE
Not reading certain plugin data and glitchy sidebar after updating Java

### ISSUE THREAD

**Issue by Aurareus** [runelite/runelite#14223]
**Describe the bug**
After updating from OpenJDK 11 to Open JDK 16 RuneLite no longer displays the data for the plugins Flipping Utilities and Inventory Setups and the sidebar for the Flipping Utilities plugin displays visual glitches.

**To Reproduce**
1. With Java 11 installed, install Flipping Utilities and/or Inventory Setups from the plugin hub.
2. Create some inventory setups in it's sidebar panel and/or make transactions on the Grand Exchange to have Fiipping Utilities track them.
3. Close RuneLite.
4. Uninstall Java 11 and install Java 16 or Java 17.
5. Launch RuneLite, open the Inventory Setups sidebar panel and those previously created will be missing, open the Flipping Utilities sidebar panel and it will be visually glitchy.

**Expected behavior**
For the Flipping Utilities sidebar panel to display correctly and for both Flipping Utilities and Inventory Setups sidebar panels to contain their previously created data.

**Screenshots**
[Glitchy sidebar](https://i.imgur.com/IMA7wle.png)

**Environment (please complete the following information):**
 - OS: OpenSUSE Tumbleweed 20210929
 - RuneLite version: 1.7.24
 - Launcher version: 2.2.0

**Additional Information**

[client.log](https://github.com/runelite/runelite/files/7275203/client.log)

Uninstalling Java 16 and reinstalling Java 11 fixes the issue.

**Comment by Adam-** [comment]
We don't create or support flipping utilities or inventory setups. Please bring this up with their maintainers.

If you find an issue with the core client on 16 or 17 we would probably be willing to look at that. Note that we advise and also ship 11 and so we do recommend you use that.
