### ISSUE TITLE
[Chat Filter] Collapse only new chats

### ISSUE THREAD

**Issue by evprkr** [runelite/runelite#14236]
The collapse chat option is amazing, but can we add an option to collapse only new chats?

Current behaviour:

1. Click something out of reach, "I can't reach that!" message appears
2. Eat chicken, "You eat the chicken." message appears
3. Click something out of reach again, "I can't reach that! (2)" message appears, moving the original message into the new one and bringing it to the bottom of the chat log

Desired behaviour:
1. Click something out of reach, "I can't reach that!" message appears
2. Eat chicken, "You eat the chicken." message appears
3. Click something out of reach again, "I can't reach that!" message appears, is not stacked, original message stays where it's at

This is pretty nit-picky, but still an important aesthetic change, in my opinion.

**Comment by Nightfirecat** [comment]
The way collapsing works now is an intentional design, as most cases of alternating messages would never yield any messages collapsing. (think of alternating messages while cooking or mining for instance)

**Comment by Nightfirecat** [comment]
See #10584 for much of our previous discussion on the matter. Presently, I am closing this request.
