### ISSUE TITLE
Double-clicking the title bar on macOS still maximizes the window even if "Lock window size" is enabled

### ISSUE THREAD

**Issue by leftbones** [runelite/runelite#14235]
"Lock window size" is enabled in RuneLite settings, window size is set to 1280x800 and "Keep game size". Resizing arrows do not appear at the edges of the window, as expected, but double-clicking the window title bar expands the window to fit the screen. Double clicking it again does not restore the original size.

MacBook Air M1
macOS 11.4 Big Sur
RuneLite M1 client (latest version)

**Comment by LlemonDuck** [comment]
I couldn't replicate this on my 2019 Intel MBP on Monterey 12.3.1, is this still an issue for you @leftbones?

**Comment by Nightfirecat** [comment]
@testing-ongithub confirmed on Discord that this is still an issue:

> **testing:** I can reproduce this on an m1 mac on Monterey 12.3 with custom chrome off (but not with custom chrome on)
And even with custom chrome off, I could only reproduce it if I restarted the client after enabling "lock window size" (at which point, the first thing I tried to do after restarting the client was resize by double-clicking the title bar), so there might be something else at play
