### ISSUE TITLE
Make PLUGIN HUB more accessible

### ISSUE THREAD

**Issue by SmartKoolAid** [runelite/runelite#14237]
**Is your feature request related to a problem? Please describe.**
New users have a difficult time finding the button - the contrast makes it difficult and most people dont realize its at docked at the very bottom below all the default plugins

**Describe the solution you'd like**
Make the plugin hub button more visible / move it to the top row of icons.

**Describe alternatives you've considered**
I don't really know how or if this is something I can change myself easily, i am sure i could figure out whether its something i could possibly contribute

**Additional context**
Ludwig and co. all struggling to install necessary plugins

**Comment by Hydrox6** [comment]
The plugin hub access button is placed deliberately to avoid people errantly installing random plugins when they are new to the client or are unable to comprehend what installing a 3rd party plugin might entail.

Either way, the difference between the top and bottom of the panel makes very little difference.
