### ISSUE TITLE
Request: Documentation of rejected/rolled-back features

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#1424]
I've already seen a number of discussions here (ie. #1386) and on Discord of features that won't be added for competitive advantage reasons, or that have been rolled back at Jagex's request. It would be helpful for future discussions to have some kind of reference of these features to know what will or will not be allowed as features.

**Comment by ypperlig** [comment]
I believe they requested that the features mentioned in this article to be removed:
https://runelite.net/blog/show/2018-01-25-1.2.13-Release
> On a more serious note, Jagex has requested removal of the Zulrah Helper, Volcanic Mine Helper, > Teamcape Overlay, and AoE Plugin for being in violation of the game rules. These plugins have been removed.

Maybe add a wiki entry for this so it can be referenced.

**Comment by winterdaze-rs** [comment]
Made a list of the most frequently brought up ones, feel free to add any I missed https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by Nightfirecat** [comment]
We've got most of the common ones covered in the wiki now, I think this has been addressed.
