### ISSUE TITLE
RuneLite crashes and / or freezes every 30-60 minutes at Wintertodt

### ISSUE THREAD

**Issue by hankshill** [runelite/runelite#14253]
**Describe the bug**
Every 30-60 minutes at Wintertodt RuneLite will freeze up. The only way to stop the process is by using SIGKILL (`kill -9`), otherwise it will stay open, frozen, indefinitely. This occurs even in safe mode with every togglable plugin turned off. FPS will usually slow to a crawl (single digits) before freezing, but this does not happen every time.

**To Reproduce**
1. Launch RuneLite either in Safe mode or not (doesn't matter)
2. Do Wintertodt for 30-60 minutes

**Expected behavior**
The game should continue as normal without freezing

**Environment (please complete the following information):**
 - OS: Arch Linux, Kernel ver. 5.14.9
 - RuneLite version: 1.7.25
- Launcher version 2.2.0

**Additional context**
I tried running the game in Safe Mode and it still froze, so I again tried Safe Mode with every plugin turned off, including Entity Hider and Status Bars, but it still froze up after 30-60 minutes.

I have jre-openjdk installed and runelite is running with java-16-openjdk

Logs:
2021-10-08 `client.log`: https://clbin.com/i0xyR
2021-10-08 `launcher.log`: https://clbin.com/Ohwds

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
