### ISSUE TITLE
Seperate Ground Item Colour for Untradeables

### ISSUE THREAD

**Issue by keywok** [runelite/runelite#14255]
**Is your feature request related to a problem? Please describe.**
Nope not a problem.

**Describe the solution you'd like**
Within the Ground Items plugin to have the ability to have a seperate colour for untradeable drops to allow them to be easily distingushed from loot piles when highlight item is already in use for other items.

**Describe alternatives you've considered**
I tried just highlighting them but then when other items got added as well it became just as messy.

**Additional context**
Its a pain when doing slayer or other PVM where you only want to pickup certain items such as slayer in the Catacombs where you get huge piles of loot and the untradeables can get lost within it.

**Comment by Hydrox6** [comment]
Duplicate of #4779
