### ISSUE TITLE
Window issue crushing the buttons

### ISSUE THREAD

**Issue by Lloydg99** [runelite/runelite#1426]
![image](https://user-images.githubusercontent.com/38325043/38686016-3cf52c9a-3e6b-11e8-9f9f-d7fbc21f9c23.png)

The screenshot or whichever one of those buttons you enable first covers the minimize button meaning that that button doesn't work and the minimize feature works before that button.

**Comment by deathbeam** [comment]
Hmm, interesting. As a workaround, you can for now disable the "Custom window chrome" in "RuneLite" settings.

**Comment by Lloydg99** [comment]
What does that change out of interest?

**Comment by Lloydg99** [comment]
Will that not remove the custom RuneLite bar and replace it with the standard window JFrame?

**Comment by deathbeam** [comment]
No, it will just change the border to your system one and move the custom buttons to sidebar

**Comment by deathbeam** [comment]
No idea :/

**Comment by deathbeam** [comment]
Is this still issue?

**Comment by deathbeam** [comment]
No reply so I assume it isnt
