### ISSUE TITLE
First slayer task is not recognized, displays -1 for points and streak

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#14286]
For the first task of your account, the task is not recognized by the plugin's text matchers, causing the task infobox not to appear. When it does later appear when your task is checked or a slayer exp drop is received, it shows `-1` for your point and streak values.

![first-task-bug](https://user-images.githubusercontent.com/2199511/138044462-39b8fe8a-b296-4759-b21a-56b918f5a532.png)

Sadly, I do not have a screenshot/log of the text for the account's first assignment. I will plan to record it when Leagues III is released.

**Comment by Skretzo** [comment]
The [OSRS Wiki](https://osrs.wiki) has chat dialogue logging, and has several entries looking like this (this is from Turael):
> We'll start you off hunting goblins, you'll need to kill %NUMBER% of them.

https://chisel.weirdgloop.org/dialogue/content/29954

**Comment by Nightfirecat** [comment]
As it turns out, we already have handling for the account's first task, but we do not set the points and streak appropriately in that case.

**Comment by Nightfirecat** [comment]
What were the steps you took to cause that via turael resetting? And at what point exactly did the plugin's tracking of your points become wrong?
