### ISSUE TITLE
Maple tree respawn timer is ~1 tick too fast

### ISSUE THREAD

**Issue by Carsillas** [runelite/runelite#14285]
**Describe the bug**
Maple trees appear roughly one tick after the respawn timer disappears.

**To Reproduce**
Chop a maple tree

**Expected behavior**
The tree will appear as the the timer reaches zero.

**Observed behavior**
The tree will appear about one tick after the timer disappears.

**Note**
This could be intended, but it is notable that the other trees do not behave this way. The other trees appear on the same tick as the timer disappears. Very minor issue.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.7.26
 - Launcher version: 2.1.5

**Comment by LlemonDuck** [comment]
#14436 fixes this and was merged, but did not link to this issue correctly at the time to auto-close,
