### ISSUE TITLE
Make it possible to have a range of items mean the same item when worn

### ISSUE THREAD

**Issue by mtarik550** [runelite/runelite#1429]
You don't need 'ring of dueling(8)' specifically you can use any type of dueling ring however the equip thing doesn't show the green 'X' unless you wear a dueling ring 8
https://i.imgur.com/iwRHqQY.png

Suggestion: change it from 'ring of dueling(8)' to just 'ring of dueling' this would be less confusing and make it show the green 'X' which ever dueling ring you wear. (hopefully that is possible)

**Comment by deathbeam** [comment]
I think it is strictly tied to item id, OSB works exactly the same I believe.
