### ISSUE TITLE
Current World Ping stuck at 229ms

### ISSUE THREAD

**Issue by TheOnlyPillow** [runelite/runelite#14301]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
In the in-game infobox the ping is stuck at 229 for whichever world I am currently logged into. There are also inaccurate ping times for other worlds in the world hopper from my location. 

**To Reproduce**
1. Go to world hopper and observer the ping of the world you're logged into
2. Double click on any world to hop to that world
3. Look back at the world hopper to find that the ping has changed to 229ms for your current world
4. 

**Expected behavior**
An accurate ping time to be shown both in the game and on the world hopper menu. Usually I would expect the ping to be similar to other US East worlds for my location (around 35ms) 

**Screenshots**
![image](https://user-images.githubusercontent.com/15838955/138528326-253c6d22-3df2-4bc3-acf9-d9d5d71f00ac.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.3
 - RuneLite version: 1.7.27
 - Launcher version: 2.2.0

**Additional context**
This was working fine last weekend, October 14-15.

**Comment by BradyRyun** [comment]
Looks like the ping is generated at the time of opening up the plugin sidebar, but is never regenerated. Let me see if I can make a change to fix this.

**Comment by BradyRyun** [comment]
To me, it would make sense that this would get generated at various times:

1. When the sidebar is opened
2. X seconds when the sidebar is open - 5-10s?
3. When you hop worlds.

**Comment by BradyRyun** [comment]
Do you have "Display current ping" set on the plugin settings?

**Comment by TheOnlyPillow** [comment]
Yes

**Comment by Adam-** [comment]
This is likely fixed by ec9ac44f92b893555a59e22bdcf091e90965d475 and e56494c5ce9f37c5f984bcb9cf237ed1ecafa7f1
