### ISSUE TITLE
Runelite crashes when NVDA screen-reader is running

### ISSUE THREAD

**Issue by SnipersRecon** [runelite/runelite#14326]
**Describe the bug**
When Runelite is running, opening "NVDA" one of the most common screen readers for people with disabilities causes Runelite to crash immediately. I definitely wouldn't expect Runelite (or Runescape) to be announce everything correctly, but allowing NVDA to run at the same time allows users to have other content read aloud, such as quest guides in their browser.

**To Reproduce**

1. Open Runelite client, no need to log in
2. Open NVDA screen reader
3. As NVDA launches Runelite will close completely

If you have NVDA open already:

1. Have NVDA running normally
2. Launch Runelite
3. Runelite never opens

**Expected behavior**
NVDA running in the background without the client crashing, so users can use the screen reader with their browser while they grind.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 21H1
 - RuneLite version: 1.8.0
 - Launcher version: 1.6.0
 - NVDA Version: 2020.4

**Additional context**
This issue does not happen using the normal OSRS client downloaded through the website.

Logs below:
[launcher.log](https://github.com/runelite/runelite/files/7455368/launcher.log)
[client.log](https://github.com/runelite/runelite/files/7455369/client.log)

**Comment by Jonfor** [comment]
I just installed NVDA and had it running in the background. I opened up runelite fine. Have you tried updating to the latest NVDA? That appears to be 2021.2 and you are on 2020.4. I didn't see any errors in those logs.

**Comment by SnipersRecon** [comment]
> 
> 
> I just installed NVDA and had it running in the background. I opened up runelite fine. Have you tried updating to the latest NVDA? That appears to be 2021.2 and you are on 2020.4. I didn't see any errors in those logs.

Interesting. I've uninstalled & reinstalled NVDA & updated to 2021.2, and the issue still happens.

Runelite also crashes on my roommate's desktop when NVDA starts, however I just tried it on my laptop and it works fine, same Runelite account & same plugins. The main difference I can think of is my roommate & I's desktop use AMD Ryzen CPUs (1600x &  3700x) and my laptop uses an Intel Core i7 10th gen, though at that point it could be any of the hardware.

I have noticed some weird startup behavior with NVDA & web browsers, occasionally it zooms your current tab out to around 60% zoom when NVDA starts up. If NVDA is sending out commands or something on startup it could be just closing Runelite out, do you know I could check that?

**Comment by Jonfor** [comment]
I have an AMD Ryzen 7 3700X so the CPU probably isn't the issue. Just curious I see that there are two types of NVDA installations a normal installation and a portable installation. Have you tried the portable version? Also does NVDA have any logs? Also if you could find the runelite logs from the time it started crashing there might be a better error message there.

**Comment by Jonfor** [comment]
Are you using 32 bit or 64 bit runelite? I'm seeing some mentions of issues with 64 bit java applications on NVDA's github: https://github.com/nvaccess/nvda/wiki/GSOC-2020-Ideas-List

**Comment by SnipersRecon** [comment]
Just uninstalled NVDA & made a portable version, starting that also crashes Runelite.

Using 64bit Runelite on all computers, even the laptop that has no issues.

I made a 32bit Runelite installation and that seems to run just fine with NVDA running, so it seems like it may be that "NVDA cannot currently interact with 64 bit Java applications" issue they mention. Seems like the issue may be on NVDA then, correct?

**Comment by Jonfor** [comment]
Ya if you can get the NVDA logs perhaps open an issue with them and see what they say?
