### ISSUE TITLE
[Suggestion] Crafting skill calculator section - Add checkbox similar to bonuses for "Making your own molten glass" 

### ISSUE THREAD

**Issue by buttonpoker** [runelite/runelite#14323]
**Is your feature request related to a problem? Please describe.**

After playing GIM for some weeks now, like the majority I have gone through the route of blowing glass to raise my crafting level but I noticed that I would always have to do my own calculation regardless because the skill calculator does not take into consideration if you were to create your own molten glass.

**Describe the solution you'd like**
I believe there should be a toggleable button titled "Crafting own Molten Glass" that will simply add the 20xp on top of the xp of making the respective glass blowing item and then from there the needed xp can be divided by the new total. This way players could gather the respective supplies needed properly.

Ex: If you need 1000 xp  for the next level and decide to make Unpowered orbs which is 52.5 xp and you're also planning on making your own molten glass it would be  Math.ceil(1000 / (52.5 + 20)) and the Calculator would show "14 Actions" as opposed to the "20 Actions" it would of been. 

**Describe alternatives you've considered**
At higher levels the majority of people making their own glass would most likely use the superglass make spell which would also be an interesting thing to add as its own item on the crafting skill calculator or as a toggle since you get 10 xp per bucket of sand used. The only issue is you wouldn't end up with exactly the same amount of molten glass needed due to the fact its an average of 1.6 molten glass per bucket of sand not a specific number. Another issue would also taking into consideration if people use regular or giant seaweed and the amount of seaweed they use per cast.

**Comment by Nightfirecat** [comment]
You can select multiple actions by holding shift. Doing so causes the action info to display:

> 2 actions selected
> 72.5 exp - 14 actions

**Comment by Nightfirecat** [comment]
There's not really any good way to handle superglass make, however

**Comment by buttonpoker** [comment]
> You can select multiple actions by holding shift. Doing so causes the action info to display:
> 
> > 2 actions selected
> > 72.5 exp - 14 actions

Ah man I feel really dumb for having a brain fart and forgetting that haha. Sorry about that. This would obviously be suffice.
