### ISSUE TITLE
Unlocked Frame Rate causes harsh drop in FPS

### ISSUE THREAD

**Issue by valarauca** [runelite/runelite#14321]
## Please check if your issue is not a duplicate by:

It is similar to these issues, but some of the details are different. 

* https://github.com/runelite/runelite/issues/14320
* https://github.com/runelite/runelite/issues/14319

## Describe the bug**

Enabling the uncapped FPS option causes my ingame FPS to fall from 50, to 30.

## To Reproduce**

1. Check the unlocked FPS check box
2. ???
3. FPS falls

## Expected behavior

FPS should hover around 60

## Screenshots

GPU Driver reporting monitor refresh rate

![image](https://user-images.githubusercontent.com/19227148/139467033-43a4c21f-0ced-44dd-90f1-9b54fa478883.png)

Windows Control Panel information

![image](https://user-images.githubusercontent.com/19227148/139467098-20b32146-bdc6-49e7-8e60-f4c58b031304.png)

Here is with FPS Unlocked

![image](https://user-images.githubusercontent.com/19227148/139468602-a9c78e49-3005-4ae1-96e2-18e1e102a99c.png)

Here is without (sorry for position change, weird people in bank)

![image](https://user-images.githubusercontent.com/19227148/139468686-99475051-d158-497c-836c-a0fce29572e7.png)

FPS Control Settings

![image](https://user-images.githubusercontent.com/19227148/139468999-4b0d1d9c-66cf-499c-91d4-ad51b3ccb47e.png)

## Environment (please complete the following information):

* Windows 10
* AMD Radeon RX 5700 XT
* Driver Version: 21.7.2 (up to date at time of posting)

**Comment by nucleon** [comment]
Could this be because of VSync? The GPU drops frames to sync with the monitors refresh rate (which is low at 60hz)

**Comment by valarauca** [comment]
> Could this be because of VSync? The GPU drops frames to sync with the monitors refresh rate (which is low at 60hz)

Given my monitor's refresh rate is 60 Hz, I don't see why it would synchronize to 30 FPS with V-Sync on.

**Comment by jasonren5** [comment]
this is usually related to vsync.. you can google 'vsync 30fps' to get a much better explanation than I am able to provide.

you might have vsync on in your nvidia global profile or similar

**Comment by valarauca** [comment]
Resolution appears to be:

Setting an override in AMD Radeon Game Settings 

![image](https://user-images.githubusercontent.com/19227148/144766692-949b092f-ffe9-437f-9c08-c9efda0c32b2.png)

And setting the runelite GPU settings to

![image](https://user-images.githubusercontent.com/19227148/144766707-e45197ed-50d3-4df4-8fc4-cc5ac90367fb.png)

This yields FPS rates well above 60
