### ISSUE TITLE
Canifis rooftop course obstacle has incorrect clickbox

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#14330]
**Describe the bug**
As shown below, for the obstacle shown, it's possible to have your mouse inside the highlighted clickbox and not click the obstacle, and to click it outside of the clickbox at certain camera angles.

**Screenshots**
![](https://cdn.discordapp.com/attachments/419891709883973642/905132955234611260/unknown.png)
![](https://cdn.discordapp.com/attachments/419891709883973642/905133368285474886/unknown.png)

**Additional context**
All of my screenshots were taken in the fixed viewport. The mapping for this agility course makes heavy use of bridges, so this could be some bug relating to that.

**Comment by Adam-** [comment]
Can you additionally get the camera position and game size this happens at? I can't reproduce

**Comment by Adam-** [comment]
From nfc:

![image](https://user-images.githubusercontent.com/309739/140407396-bc2fbdb8-bdd1-4a6e-ba10-1ea405eb607f.png)

**Comment by Nightfirecat** [comment]
Another one.
![](https://cdn.discordapp.com/attachments/419891709883973642/905908265421004890/unknown.png)

**Comment by sirachillies** [comment]
This Issue only popped up for me today after the runelite update. This issue is not present on my laptop

**Comment by sirachillies** [comment]
I reinstalled the game on my Desktop where the issue has shown up at and the issue has resolved for me.

**Comment by Adam-** [comment]
When I was looking at this before it only happened occasionally and not in a way I could reproduce it. Usually just teleporting away/back fixed it.

**Comment by sirachillies** [comment]
I did not try teleporting away and coming back. But the issue for me has been fixed. So I am happy. If it reoccurs I can come back to this thread and continue discussion.
