### ISSUE TITLE
Add whitelist to Ground Items plugin

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#14337]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A 'Whitelist' box in the Ground Items area, to show items that I don't want _highlighted_, but still want shown regardless of other filters such as being above a certain price. 

**Describe alternatives you've considered**
Outside of highlighting the items, I don't think there is any kind of whitelist.

**Additional context**
I'm an ironman. I'd like to hide a lot of 'trash' drops, but certain things I always want to see, such as seeds. I don't necessarily want to highlight them, as they aren't THAT important, generally speaking.

**Comment by Hydrox6** [comment]
Instead of hiding by price, keep the price value at 0 and hide stuff you don't want to see.
