### ISSUE TITLE
Thin light bar on top of window

### ISSUE THREAD

**Issue by grepsedawk** [runelite/runelite#14338]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
A thin, transparent bar shows up

**To Reproduce**
start runlite

**Expected behavior**
no bar to be there

**Screenshots**
![image](https://user-images.githubusercontent.com/6721355/140387162-b0e64883-3861-488e-b473-109f921095e0.png)

**Environment (please complete the following information):**
 - OS:linux
![image](https://user-images.githubusercontent.com/6721355/140387226-1482322d-a170-4d87-afac-2716482f5e79.png)

**Comment by Nightfirecat** [comment]
What DE/WM are you using?

**Comment by grepsedawk** [comment]
i3-gaps with picom for composition

**Comment by Nightfirecat** [comment]
Can you post a screenshot of all the settings under the `Windoow Settings` group of `RuneLite`'s settings?

**Comment by grepsedawk** [comment]
![image](https://user-images.githubusercontent.com/6721355/141235375-68560f55-26f6-4b67-8ff9-d440203f99f1.png)

**Comment by Nightfirecat** [comment]
According to another admin, they use `i3-gaps` without issue, so this is likely a compositor or JVM bug.

**Comment by Matthew-nop** [comment]
I'm currently using i3-gaps and picom too, this definitely seems like an issue with either your configs or the JVM.

As it appears for me:
![2021-11-24-145553_1369x420_scrot](https://user-images.githubusercontent.com/66925241/143323095-a79a54ea-7eb1-4456-84aa-71af11301447.png)

**Comment by abextm** [comment]
This looks like a bug in i3 that picom is making visible. See yshui/picom#547. You can work around this by setting `frame-opacity = 1.0` in your `~/.config/picom/picom.conf`

**Comment by grepsedawk** [comment]
@abextm thanks! I actually have no frames, so I could see why this might bug out.

I just noticed that the other day and worked it out, didn't even think of runellite I'll give it a shot!
