### ISSUE TITLE
Would it be possible to switch the options for cooking Karambwans so space and 1 is well cooked and  is poorly

### ISSUE THREAD

**Issue by Lloydg99** [runelite/runelite#1434]
Would it be possible to switch the options for cooking Karambwans so space and 1 is well cooked and  is poorly?

**Comment by ShaunDreclin** [comment]
Having space remember the last option you selected might be a better solution than messing with the ordering of the options.

**Comment by deathbeam** [comment]
That sounds like faking user input, so no
