### ISSUE TITLE
Right Click Teleport for Max Cape

### ISSUE THREAD

**Issue by marlenekoh** [runelite/runelite#14353]
**Edit:** 
Feature Request to swap Max Cape 'Teleports' with 'Wear' in Menu Entry Swapper

**Is your feature request related to a problem? Please describe.**
Difficult to teleport when max cape in inventory. If I wear the max cape, I am able to teleport to POH but this requires me to change tab from inventory to worn equipment.

**Describe the solution you'd like**
Add feature request to configure teleport for menu entry swapper
- When max cape is inventory, swap wear with click to teleport like Ardougne cloak but choose from all available max cape teleports 
- Will be great if can configure teleport to POH, or to Crafting bank for example

**Describe alternatives you've considered**
Alternatively, add one more option to max cape context menu when right click from inventory

**Additional context**

> Menu entry swapper (Ardougne cloak)

![image](https://user-images.githubusercontent.com/28558150/140743286-462f626d-2be8-4bca-a27c-33093af29b49.png)

> Max cape context menu in inventory

![image](https://user-images.githubusercontent.com/28558150/140743738-91d3bc92-cc28-40d8-9d11-3038a1460093.png)

**Comment by Alexsuperfly** [comment]
swapping menu options on equipped items and creating new menu options entirely which send an action to the server are both explicitly prohibited by jagex in their [third party statement ](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1)

the general teleport swap in the plugin should work for the max cape, if not, we can leave this open as a feature request for adding that.

**Comment by marlenekoh** [comment]
I see, I didn't read their third party statement.
The general teleport swap in the plugin doesn't seem to work for the max cape. I'll leave it open as a feature request then, thanks!!

**Comment by Adam-** [comment]
added in #14379
