### ISSUE TITLE
Opponent Information (feature request): A filter to exclude certain monsters from having their HP info show up

### ISSUE THREAD

**Issue by nickyGyul** [runelite/runelite#14356]
Jagex added official boss health overlays to _some_ recent bosses, such as Hunllef, Zalcano, the Nightmare, Zuk etc. The opponent information is redundant for only those monsters. 

The plugin is super useful during the preparation stage of Gauntlet, but it can get in the way during the final fight with Hunllef.

I would love to have an editable dialog/text box where you can filter specific NPCs (kinda like the NPC Indicators plugin). This way I could keep the plugin enabled while having it disabled for only specific bosses.

Thank you in advance!

**Comment by Adam-** [comment]
What if we just made the opponent info overlay automatically hidden if the in-game health bar overlay is up? The in-game one is better I think since it has the exact HP values when we do not.

**Comment by nickyGyul** [comment]
That would be even better! 
I was not sure whether the TzKal-Zuk's health bar worked the same as the more modern bosses. Didn't realise an elegant implementation like that was possible.

**Comment by Adam-** [comment]
I think Zuk's healthbar is different from the others so it probably wouldn't work for that. It's also largely inaccessible so probably not something I would try to fix for.

**Comment by Adam-** [comment]
Okay I've added this in 7b6074f0f86320efe644db08b40633b362e10bfb
