### ISSUE TITLE
Bring back “Hour, Day, Week, Session, etc.” to loot tracker. 

### ISSUE THREAD

**Issue by TranceHD** [runelite/runelite#14355]
**Is your feature request related to a problem? Please describe.**
There used to be a way to do this and I don’t know if it was purposefully removed, but I’d love to see a return. 

**Describe the solution you'd like**
Add organization of the loot tracker via drop down menu to organize by session, hour, day, week, etc.  

**Describe alternatives you've considered**
I’ve tried manually resetting it or logging out of Runelite but then gets rid of past data, which I’d rather not have. 

**Additional context**
The menu used to be where the “Collapse” arrow was.

**Comment by hex-agon** [comment]
This was never a feature in RuneLite.

**Comment by TranceHD** [comment]
Maybe I was remembering it wrong, but it could still be an added feature, no?
