### ISSUE TITLE
GPU Plugin Unlock fps option causes high usage when idling at login

### ISSUE THREAD

**Issue by jasonren5** [runelite/runelite#14360]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)
(i took a quick glance at the issues and didn't notice anything - sorry if this is a duplicate)

**Describe the bug**
Idling at login screen while using the unlock fps option will cause high cpu/gpu usage (the fps limiter's draw fps option doesn't work here, but i'd guess it's just rendering at a very high framerate).

I know unfocused fps can be capped using the fps limiter plugin, but in my case I was just using it to draw the fps (prior to the unlock fps option I had never felt the need to cap my fps, so I had those boxes unticked.

I have a 3060ti and a ryzen 3600, and this issue has been causing massive stuttering in other applications for the past several weeks. I figure there might be others in my situation, and I don't see any benefit to uncapping the fps of the login screen, so if possible I think this might be worth working on 

**To Reproduce**
1. Open runelite, do not login
2. Make sure fps cap options in fps limiter plugin are unused
3. Observe the cpu/gpu usage of Runelite using Task Manager or similar
4. Tick unlock fps option
5. Observe that the cpu/gpu usage increases
6. Untick fps option
7. Observe that usage decreases

**Expected behavior**
idling at login screen in any case wouldn't adversely affect other programs on pc

**Screenshots**
![unlockfps](https://user-images.githubusercontent.com/31326470/141184078-c48458e6-f831-48a3-9914-0737d5943bf2.gif)

**Environment 
(please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.2
 - Launcher version: 2.2.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Adam-** [comment]
This is probably just because it's drawing the login screen at 120fps or whatever. I wouldn't be opposed to limiting the fps on the login screen to the normal 50fps I think.

**Comment by Adam-** [comment]
patched internally in 1.8.3-SNAPSHOT
