### ISSUE TITLE
Right click hi-score lookup in CC doesn't work

### ISSUE THREAD

**Issue by Caia-OSRS** [runelite/runelite#1436]
<img width="240" alt="screen shot 2018-04-12 at 12 57 18 pm" src="https://user-images.githubusercontent.com/37057941/38692200-0f74df64-3e51-11e8-8bc1-60371e8add93.png">
When clicking lookup the hi-score just freezes like this. Issue seems to be with names of ironman accounts.

**Comment by deathbeam** [comment]
This was issue with client fetching the hiscore data, it is fixed now.
