### ISSUE TITLE
No Stun Timer for Martin the Master Gardener

### ISSUE THREAD

**Issue by Tocseoj** [runelite/runelite#14375]
**Describe the bug**
When stunned by Martin the Master Gardener the pickpocket stun timer doesn't appear (from plugin "Timers")

**To Reproduce**
1. Enable the "Timers" plugin with the pickpocket timer checkbox enabled
2. Go to Draynor, Right Click and select "Pickpocket Martin the Master Gardener" 
3. If you get Stunned, it won't show the timer
4. You can check this by Pickpocketing the regular "Master Gardener" and see the timer

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: 1.8.2
 - Launcher version: 2.2.0

**Comment by BradyRyun** [comment]
Checking this out now. Looks like it's because the message generated from failing to pick Martin's pocket is different than others.
