### ISSUE TITLE
Request: Allow /1?[0-9]{2}/ format for Default World plugin

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#1437]
In #915, `/[0-9]{2}/` format was added for the default world plugin, effectively allowing entries like "22" to translate to "322". As OSRS now has at least one permanent world above 399 (w417 is the permanent f2p pvp world), can `/1?[0-9]{2}/` translate values between 100 and 199 to 400-499 actual values?

**Comment by nrodrigues0213** [comment]
Fixed #1445

**Comment by Nightfirecat** [comment]
Never mind, #915 basically does `world = world < 300 ? world + 300 : world`, so the 400 worlds are already covered.
