### ISSUE TITLE
Risk command for Pkers.

### ISSUE THREAD

**Issue by GucciVans** [runelite/runelite#14373]
It would be cool with a command Plug-in, that tells in the chat how much you risk atm.

That way you can tell the pker that you risk nothing, so theres no reason to kill you.

Or it can be used in risk fights so you dont get scammed.

**Comment by Nightfirecat** [comment]
This would be a terrible idea. Anyone could run their own build which would report false values.

**Comment by GucciVans** [comment]
Could you elaborate what you mean with that, or maybe im explaining it bad.

what i want is a "!risk" command that tells in chat the same info you get when you check "View items kept on death -> Guide risk value"

kinda like !kc or !price

**Comment by Adam-** [comment]
There is no financial incentive to fake !kc or !price data. Since there is financial incentive to fake !risk data, it would be heavily abused and rendered useless.
