### ISSUE TITLE
resizing the client

### ISSUE THREAD

**Issue by osrsexo** [runelite/runelite#14370]
If you drag your chrome client for example to a corner of your screen you can devide it into sections of your screen for easy multitasking. (or hover over the resize button in windows 11)

I'd like runelite to be able to resize like other applications, instead of having to manually resize it.

hovering over resize button to select desired position in windows 11 (not possible with runelite yet)
![2021-11-14](https://user-images.githubusercontent.com/42911224/141676131-3cde4b1a-6e4b-4f17-8796-4ba7e856050c.png)
(

**Comment by Unmoon** [comment]
Disable custom chrome under Runelite plugin.
