### ISSUE TITLE
Zoom out minimap like vanilla client

### ISSUE THREAD

**Issue by zipper11** [runelite/runelite#14371]
**Is your feature request related to a problem? Please describe.**
Is it possible to zoom out on the minimap? Exactly like it works on the vanilla client.

**Describe the solution you'd like**
Mouse over minimap then zoom out or in with mouse scroll wheel.

**Describe alternatives you've considered**
Nothing really, like leaving it like it's now. But is imo a greate qol improvement.

**Additional context**
Makes walking long distances really easy.

**Comment by abextm** [comment]
Added in bbfd974b14a9838c3938c3bd13c77b9a30da5148
