### ISSUE TITLE
Screenshots not being taken for duels

### ISSUE THREAD

**Issue by djpginthegits** [runelite/runelite#14387]
Since the update last night screenshots are not being taken when winning a duel, and occasionally not being taken for a loss.
I have tried disabling the checkbox/re-enabling, as well as disable/re-enabling the screenshots plugin, have not tried a complete re-install, though.

**Comment by Adam-** [comment]
Can you get a screenshot of winning and losing a duel? Maybe the text has changed.

**Comment by djpginthegits** [comment]
Hey mate,
Thanks for getting back to me so quickly - here's a win and loss (the loss
was automatically taken, the win was manual)
[image: 2021-11-19_03-18-57.png]

[image: Duel lost (1909) 2021-11-19_03-00-42.png]

Here's a screenshot taken prior to the update - appears to be
identical ¯\_(ツ)_/¯
[image: image.png]

**Comment by Nightfirecat** [comment]
Can you post the images directly to this issue instead of by email? We can't see what you're seeing

**Comment by djpginthegits** [comment]
Ah, was not aware that the email reply was text only... here you go c:

![2021-11-19_03-18-57](https://user-images.githubusercontent.com/38811421/142455750-e338a458-eca6-4cdc-97b6-16ce797ac52a.png)
![Duel lost (1909) 2021-11-19_03-00-42](https://user-images.githubusercontent.com/38811421/142455832-47d04b8e-3b16-450c-b4b1-f5bbadce8fef.png)

![image](https://user-images.githubusercontent.com/38811421/142455880-eaed3cda-6ce7-4bee-9836-2c807efbb63d.png)

**Comment by Adam-** [comment]
Looks like they added a comma into the number of duels won/lost

**Comment by djpginthegits** [comment]
Ah yep you're right - I was looking in the 'trade screen' lol

**Comment by Adam-** [comment]
If you win you get a message `You have lost x duels.` but if you lose you also get a message `You have now lost x duels.` 🍝

**Comment by Adam-** [comment]
fixed in 58bc37f0516e1fa866206c667abf993caac2f0f2
