### ISSUE TITLE
Barrows Items seem to not hold placeholders when using bank tags

### ISSUE THREAD

**Issue by Caia-OSRS** [runelite/runelite#1438]
The recent update fixed bank tag placeholders but it seems that barrows items that are degraded (25, 75 etc.) still do not keep a placeholder.

**Comment by Caia-OSRS** [comment]
Add amulet of glory (4) to that list that doesn't keep a placeholder still

**Comment by deathbeam** [comment]
I think this is Jagex issue, we cannot cause something like this.
