### ISSUE TITLE
Chat Timestamps 12 hour Format

### ISSUE THREAD

**Issue by mooseweener** [runelite/runelite#14382]
Please add 12 hour format with AM PM to the built in Chat Timestamps.

I personally never use 24 hour format so it throws me off sometimes, especially with 2 other clocks in 12 hour format in sight.

I hope I'm not the only one, and yes I know it's simple math. ;)

**Comment by Nightfirecat** [comment]
Use the `Timestamp Format` option of the plugin to configure this. For the format "12:34 AM", use `hh:mm a`
