### ISSUE TITLE
[Suggestion] Store Loot Tracker Data Locally

### ISSUE THREAD

**Issue by KodouDesuu** [runelite/runelite#14397]
Is it possible to make the Loot tracker store the data from past sessions without being signed in?

**Comment by Matthew-nop** [comment]
[This plugin](https://github.com/TheStonedTurtle/Loot-Logger) from the pluginhub appears to offer these features

**Comment by trelkins3** [comment]
I believe as of 1.8.13.1 this is how it works now.

**Comment by Adam-** [comment]
Indeed, see https://runelite.net/blog/show/2022-03-09-1.8.13-Release
