### ISSUE TITLE
Fishing tiles not showing up?

### ISSUE THREAD

**Issue by derpyderpaderp** [runelite/runelite#14392]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Tile markers for fishing spots are not showing up.

**To Reproduce**
1. Go to: Any fishing spot
2. Click on: N/A
3. Scroll down to: N/A
4. See error: N/A

**Expected behavior**
Fishing tile markings are missing, Checked in lumbridge and in Barbarian village.

**Screenshots**
My Settings: https://i.imgur.com/Cehs2xo.png

Showing no tiles: https://i.imgur.com/F1yeVF5.png

**Environment (please complete the following information):**
 - OS: Windows 11
 - RuneLite version: 1.8.3
 - Launcher version: 2.2.0

**Comment by Nightfirecat** [comment]
You need to have the items needed to fish them in order for them to show up. Try again with a fly fishing rod and feathers in your inventory.

**Comment by matt-buckley** [comment]
This issue is also appearing for me even when I have a net in my inventory. I'm in the Ruins of Camdozaal.
