### ISSUE TITLE
Item stats definitions missing for many alcoholic beverages

### ISSUE THREAD

**Issue by Matthew-nop** [runelite/runelite#14409]
The itemstatus plugin currently does not have information for some drinks/food. This causes the status bar plugin's "show restores" to not function with these items. <br>

Here are those that I've come across, but there are certainly more (mature ales, obscure quest items, etc)
 - beer
 - whisky
 - vodka
 - brandy
 - grog
 - dwarven stout
 - wizard's mind bomb
 - asgarnian ale
 - greenman's ale
 - cup of tea
 - barbarian potions

## Expected result:
![2021-11-24-033137_409x539_scrot](https://user-images.githubusercontent.com/66925241/143233686-1dc9f286-8351-410d-9367-dfe30c78b4b3.png)
## Result:
![2021-11-24-033559_411x540_scrot](https://user-images.githubusercontent.com/66925241/143233765-5ff60d29-9797-498d-ba54-9bc2dfff3f8b.png)

**Comment by Nightfirecat** [comment]
fyi the actual place which needs this data updated is the Item Stats plugin, not the Status Bars plugin.

**Comment by Jonfor** [comment]
I'll take a look at this.

**Comment by Matthew-nop** [comment]
> fyi the actual place which needs this data updated is the Item Stats plugin, not the Status Bars plugin.
Thanks for the heads up, I've added this to the post

**Comment by Nightfirecat** [comment]
Most of these are added in #14412; barbarian mixed potions are requested separately in #12057
