### ISSUE TITLE
Ground Items Highlight Value calculation when set to High Alchemy doesnt work for "default Items" color

### ISSUE THREAD

**Issue by rockett1** [runelite/runelite#14417]
**Describe the bug**
When Ground Items Highlight Value calculation is set to High Alchemy, it still uses GE prices to highlight "Default items". Here is an example of what I mean: https://imgur.com/a/atzN1ND Despite having it set to High Alch it still highlights the ground items despite them being worth < 1000gp

It works for all the other options low value, medium value, high value etc... but not default items

**To Reproduce**
1. Configure ground items
2. Set Highlight value calculation: to High Alchemy
3. See items get highlighted based off of GE price instead

**Expected behavior**
Ground items to be highlighted based off of High Alchemy price

**Screenshots**
![image](https://user-images.githubusercontent.com/1695078/143497487-04859cda-b8e0-4877-9ab7-d836a76860f5.png)
![image](https://user-images.githubusercontent.com/1695078/143497494-1e4fe811-3f6c-498a-974b-bacda5e59279.png)

**Comment by raiyni** [comment]
This is an intended feature. You need to enable the option at the top, `Show Highlighted Items Only`.
