### ISSUE TITLE
Add the overlays for charges left.

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#1441]
![image](https://user-images.githubusercontent.com/37475765/38695446-333dc14e-3e84-11e8-8816-1d9d8d9f733a.png)
add these i know its at the armour slot but it should be where we don't have to go to the armour slot to see how many charges left it should be on the screen
![image](https://user-images.githubusercontent.com/37475765/38695522-6d4e64ba-3e84-11e8-8c04-bd52098e4457.png)
like this

**Comment by deathbeam** [comment]
Duplicate
