### ISSUE TITLE
HiScore plugin: Make "Lookup" automatically search DMM Hiscores if you're on a DMM world

### ISSUE THREAD

**Issue by dginovker** [runelite/runelite#14418]
**Is your feature request related to a problem? Please describe.**
I only play DMM, and when I Lookup a player I always have to click on the DMM skull as soon as the hiscores plugin pops up. If I'm on w345 (DMM), and I'm right-click Lookup-ing a player, it makes sense that I would want to see the DMM hiscores

**Describe the solution you'd like**
* When on w345, the Lookup function searches DMM hiscores

**Describe alternatives you've considered**
* A toggle that allows this feature
* A similar feature for Leagues

**Comment by Adam-** [comment]
fixed in 6ec534b396c1ea52e1b7fc374976e8ce1df5a36d
