### ISSUE TITLE
Persist clan chat broadcasts across logins like other chat

### ISSUE THREAD

**Issue by Chrisazy** [runelite/runelite#14425]
**Is your feature request related to a problem? Please describe.**
When you log out, especially from afking, and come back to a clan chat full of "gzzzzz" with no context. Would be a nice QoL to be able to know the broadcasts from before you logged out last, much like the rest of the chat is persisted.

**Comment by Adam-** [comment]
The "broadcasts" are actually system messages, so include things like the "To talk in your clan's channel"... message
![image](https://user-images.githubusercontent.com/309739/143789684-6bb99cd9-d036-4f62-b2e8-42d0e423ada2.png)
though I suppose that's fine

**Comment by Adam-** [comment]
added in ab471aa13a21f79ff36cf317200bb6e6d65d25e9
