### ISSUE TITLE
(suggestion)  All Mobs All Drops plugin game

### ISSUE THREAD

**Issue by ChaffedBussy** [runelite/runelite#14429]
What i suggest is a plugin that has every mob's drop check list. 

example, 
Kills a goblin
Drops hammer, Checks off hammer.

i think it would be an enjoyable thing for players to work on and maybe a few youtubers will make it new content? 

If this is a wrong place to suggest this then i would like someone to pass it on to someone who could create such a plugin. :)

**Comment by Nightfirecat** [comment]
There's already a plugin on the hub which does something like this: https://runelite.net/plugin-hub/show/boredgenerator

We're not going to be adding anything like this to core.
