### ISSUE TITLE
RSProfileConfig retrieves integer string as scientific notation after RuneLite restart.

### ISSUE THREAD

**Issue by larsvansoest** [runelite/runelite#14433]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When storing a large number as string with  [net.runelite.client.config.ConfigManager::setRSProfileConfiguration](https://static.runelite.net/api/runelite-client/net/runelite/client/config/ConfigManager.html#setRSProfileConfiguration(java.lang.String,java.lang.String,java.lang.Object)), after rebooting RuneLite, [net.runelite.client.config.ConfigManager::getRSProfileConfiguration](https://static.runelite.net/api/runelite-client/net/runelite/client/config/ConfigManager.html#getRSProfileConfiguration(java.lang.String,java.lang.String)) returns the stored number as string in scientific notation.

**To Reproduce**
1. Let `config` denote an instance of [ConfigManager](https://static.runelite.net/api/runelite-client/net/runelite/client/config/ConfigManager.html)
2. Let `s = "1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"`
3. Store `s` using `config.setRSProfileConfiguration("debug_group", "debug_key", s);`
4. Restart RuneLite
5. Retrieve `s'` from config using `config.getRSProfileConfiguration("debug_group", "debug_key");`
6. Observe s' = `"1.1111111111111111E108"`  != `s`

**Expected behavior**
Because we stored a string, and not an integer, we would expect the retrieved string to be equal to the input string.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: 1.8.4
 - Launcher version: Unknown (observed when debugging with IntelliJ)

**Additional context**
This issue was encountered when debugging [emote-clue-items#33](https://github.com/larsvansoest/emote-clue-items/issues/33). The plugin allows configuration of all stash fill statuses, and stores the status as a string 108 times 0/1 to represent the fill status of each stash unit ordered by object id.

**Comment by abextm** [comment]
this is working as expected

**Comment by larsvansoest** [comment]
In that case, could you add this expected behaviour to the java doc?
