### ISSUE TITLE
Menu Entry Swapper for Fish sack barrel

### ISSUE THREAD

**Issue by TheRedSock** [runelite/runelite#14435]
The fish sack barrel has a very annoying property where the main menu option for it is "Fill", and not "Wear". This is frustrating due to the fact that you have to de-equip it to be able to deposit the fish from it, meaning you have to re-equip it after every banking. It is also unnecessary since the sack automatically fills anyway by having it open. 

It would be very nice if in the menu entry swapper I could choose for the fish sack barrel to default to the wear option like the other items on the list like karamja gloves and morytania legs.

**Comment by Nightfirecat** [comment]
8944eb9 was added to master, which sufficiently covers this use case.
