### ISSUE TITLE
Right Click "Release Item" edits tag rather than removes

### ISSUE THREAD

**Issue by GETrackerDan** [runelite/runelite#1443]
Right clicking on remove item in bank to remove seems to just prompt to edit?

![cchzztz](https://user-images.githubusercontent.com/38025439/38696815-2c5d4da0-3e88-11e8-89cf-647288e0cd76.png)

Goes to this ->

![y8ygsku](https://user-images.githubusercontent.com/38025439/38696823-2ec97cee-3e88-11e8-9ae2-17191f6b21e8.png)

**Comment by Adam-** [comment]
Fixed in #1440

**Comment by Nightfirecat** [comment]
@Adam- Will a new release be pushed to fix this behavior, or will players encountering this issue need to disable the plugin until next Thursday?

**Comment by SoyChai** [comment]
Adam's working on pushing this out as a hotfix today, far as I can tell.
