### ISSUE TITLE
Key Remapping Plugin no longer disables keypresses before pressing enter to chat

### ISSUE THREAD

**Issue by vendeta44** [runelite/runelite#14434]
Normally with "key remapping" plugin wasd will move camera, and that still works, but it also adds a "press enter to chat" requirement on typing into a chat window. Previously that would stop you from typing anything without pressings enter, but now if you type any letter besides "wasd" it will still get entered into the chatbox but not be visible as the chat box still shows the "press enter to chat" message and if you press enter it will send the invisible message to chat. Seems like a recent bug probably from recent chat changes.

**Comment by geheur** [comment]
Have you tried restarting your runelite client? It sounds like you might have an old version of runelite.
