### ISSUE TITLE
Allow players to change the fill color and opacity of Tile Indicators

### ISSUE THREAD

**Issue by dakoders** [runelite/runelite#14445]
**Is your feature request related to a problem? Please describe.**
Yes - The tile indicators currently add a dark gray shade to any tile indicator that is enabled (hover, true, destination) and can often make it really difficult to tell if a portal/grasping claws is spawning under the player in Nightmare and Phosani's Nightmare.

**Describe the solution you'd like**
I'd like to be able to select the color and opacity of the tile indicators, so I can choose to either have the tile filled with a light color (like the official client), have it just outlined and the fill transparent, or have both a colored infill and outline.

**Comment by Hydrox6** [comment]
Duplicate of #4188

**Comment by Adam-** [comment]
added in #14447
