### ISSUE TITLE
Some convenient feature request.

### ISSUE THREAD

**Issue by Goldi3Boi** [runelite/runelite#14448]
I used RuneLite and i liked it. It has many good opportunities for me. I wanted to play it on other devices rather than on a desktop. But i realised that i already added so many configurations when signed out.. So make a feature where by the time i sign up on a device where i configurated some stuff would save on that account unless it has been on it's first device.

**Comment by Hydrox6** [comment]
https://github.com/runelite/runelite/wiki/Account#sync-local-settings-to-your-remote-runelite-account
