### ISSUE TITLE
Option to remove/hide menu bar Runelite icon. [ Mac ]

### ISSUE THREAD

**Issue by Jonotaku** [runelite/runelite#14443]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Its wasted space. All it does is open Runelite when I can just use my mouse shortcuts instead or go down to the dock in the same amount of time. 👎 
I have a 2021 Mac M1 Pro and I have a notch on this computer and its pretty close to being behind the notch I would absoulutly love more real-estate with the icon removed! 

**Describe the solution you'd like**
Option to remove menu bar icon with Command+Mouse Button 1 (Dragging off screen) 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
Add a setting to remove it in the built in 'Runelite' setting

**Additional context**
I am uploading a quick little screen recording of what the problem is:

https://user-images.githubusercontent.com/28886725/144695847-9ca4f003-5aec-4d69-8aee-9d34c0475983.mov

**Comment by makingcomment** [comment]
I agree that having the option to remove the icon within RuneLite would be good, but in the meantime, using an app like Bartender or Dozer to manage the menu bar should work.
