### ISSUE TITLE
Runelite plugins not working due to update

### ISSUE THREAD

**Issue by amitaymolko** [runelite/runelite#14457]
**Describe the bug**
Runelite plugins stopped working because of an updating in OSRS

**To Reproduce**
Open Runelite 

**Additional context**
[Update Blog Post](https://secure.runescape.com/m=news/grand-exchange-tax--item-sink?oldschool=1)

**Comment by amitaymolko** [comment]
![Screen Shot 2021-12-09 at 13 48 17](https://user-images.githubusercontent.com/1846494/145391182-72ef1720-ce23-48b4-89a7-65b0e9aadf87.png)
MacOS 12.0.1

**Comment by amitaymolko** [comment]
Why is this marked as invalid?

**Comment by Hydrox6** [comment]
Read the box, and wait for the update

**Comment by amitaymolko** [comment]
ok, thanks!
