### ISSUE TITLE
Runelite GPU/HD not working

### ISSUE THREAD

**Issue by jgbdgch2** [runelite/runelite#14451]
I built my own machine, and have had the same NVIDIA GeForce GTX 1060 6GB since. I have since changed motherboards to the same company (MSI). On the original motherboard I could use Runelite GPU but on this motherboard I have never been able to. My graphics drivers are up to date, my OpenGL is version 4.6, NVIDIA is allowing OpenGL rendering GPU for Runelite. I have installed the 64 bit version of Runelite for my 64 bit Windows 10 machine. Does anyone know what it could possibly be, and how to fix it?
[client.log](https://github.com/runelite/runelite/files/7673268/client.log)
.

**Comment by LlemonDuck** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

**Comment by jgbdgch2** [comment]
Will do, thanks.
