### ISSUE TITLE
Show map for coordinate and map clues

### ISSUE THREAD

**Issue by mtarik550** [runelite/runelite#1446]
It would be nice if Clue scrolls that ask for coordinates had a map icon that you could press which would show you exactly where to go, this would save players a bit of time going on google and typing the coordinates them selves. 

Example of coordinates 

> 00 degrees 05 minutes south, 01 degrees 13 minutes east

or an alternative that could be that it could say the clue destination instead of the regular 

> Coordinate clue | Travel to the marked out destination to see a marker for where you should dig.

**Comment by deathbeam** [comment]
This will be solved by #1373

**Comment by MESLewis** [comment]
Should this be renamed to something like "Show coordinate and map clues on world map" so it is easier to see what the suggestion is? This request has come up a lot lately and is being worked on.
