### ISSUE TITLE
Agility click zone misplaced Canafis rooftop

### ISSUE THREAD

**Issue by sirachillies** [runelite/runelite#14460]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
On canafis rooftop after climbing the tree the next click spot has been turned sideways and there is now a zone that cannot be clicked in. The blue drawn in square area is a click zone that does not progress to canafis rooftop

**To Reproduce**
see description of big

**Expected behavior**
Normally this square zone is not turned sideways and the entire green zone is clickable to go to next area of rooftop

**Screenshots**
![image](https://user-images.githubusercontent.com/95868862/145421031-edf7adb7-88cc-4881-806d-3b95387d0784.png)

**Environment (please complete the following information):**
- latest version of runelite installed 12/9/2021

**Comment by abextm** [comment]
duplicate #14330
