### ISSUE TITLE
Actively traded price text covered by the new GE format

### ISSUE THREAD

**Issue by KodouDesuu** [runelite/runelite#14463]
![2021-12-10_09-02-13](https://user-images.githubusercontent.com/94813867/145499756-d44cf49e-f9c0-4c60-936d-35e9f2b14a91.png)

**Comment by Nightfirecat** [comment]
This is somewhat a problem which exists in the vanilla client as well--some items with extraordinarily long examine texts can encounter that issue with no extra text appended by us. That said, we do need to find some other way to display this as we're especially out of space now.

**Comment by iDre4M** [comment]
Why not to move "examine text" into format such as "Convenience fee: 1%" explanation hidden inside that "i" icon? Or if not touching that part, then move actively traded price near "Buy limit" or with "i" icon near by maybe... unless there are limitations behind it.

**Comment by Adam-** [comment]
this was fixed awhile ago
