### ISSUE TITLE
menu entry swapper request - Plank sack - bank

### ISSUE THREAD

**Issue by bigchungus2222** [runelite/runelite#14470]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

Hi,

https://gyazo.com/ebec16609821fe6704f16de8b7e38b4b

can you add plank sack to menu entry swapper and when in invent like the above photo let it so empty is the default.

https://gyazo.com/e90ed177b78bb1358e32c36e368c4a4c

Also when in the bank make the default option "use" as it fills your plank sack with whats in the invent.

appreciate the consideration

thank you

**Additional context**

**Comment by Hydrox6** [comment]
This is already possible using multiple options in the `Menu Entry Swapper` plugin.

**Comment by bigchungus2222** [comment]
hi, 

if thats possible could i get some help with how?

thanks
