### ISSUE TITLE
1-2 Second Latency when opening plugin sidebars

### ISSUE THREAD

**Issue by fe-steevo** [runelite/runelite#14474]
Have searched online to no avail, as well as asked my clan chat with no fix thus far. 

This randomly began maybe 2-3 weeks ago. I haven't downloaded a plugin in a long time so I know its not a new plug in. Whenever I am playing Runescape, on a fresh start of Runelite, it plays great. 50fps locked and no problems at all. As soon as I open a plug in side bar like world hopper, hiscores, xp tracker, etc... I start to get a 1-2 second latency issue with my clicks. And that is literally counting out 1 Mississippi, 2 Mississippi before the click registers. 

I have uninstalled Runelite and reinstalled to no avail, and have removed all of the added on plugins I had to no avail. To add to this issue, it ONLY happens on my PC in my game room. My gaming laptop does not have this issue. nor does my work laptop that doesn't even have a GPU. 

Any help would be greatly appreciated. I am going to dive in to my PC and see if the issue lies within that and will update when I can.

**Comment by Hydrox6** [comment]
<details>
<summary>Details</summary>

The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

</details>
