### ISSUE TITLE
Add the features of OnTopReplica (clone window, select region, change opacity, interact)

### ISSUE THREAD

**Issue by ragsmaroon** [runelite/runelite#1448]
[OnTopReplica](https://github.com/LorenzCK/OnTopReplica) is a program that allows you to clone a selected region of a window, change the opacity, and interact with the original window through it. For some reason, it doesn't work with Java applications.

**Comment by deathbeam** [comment]
What if you try to disable custom window chrome? in the "RuneLite" settings

**Comment by ragsmaroon** [comment]
Nope, just tried. Same thing with other clients, removing the custom border does nothing.

**Comment by Nightfirecat** [comment]
It sounds like this may be a bug with OnTopReplica rather than RuneLite if this issue applies to any Java application.

**Comment by ragsmaroon** [comment]
Yes lad, that's why I'm suggesting it be added as a feature so that we can use it.

**Comment by Lalonde33** [comment]
Actually ontopreplica click through sort of works. If I remember you have to use normal client on fullscreen. Even then the clicks were off center.

**Comment by deathbeam** [comment]
Looks like this is bug related to other 3rd party application not related to RuneLite at all. Adding all features of different program just because it is bugged do not makes sense, closing.
