### ISSUE TITLE
Add detailed Prifiddnas view to World Map

### ISSUE THREAD

**Issue by Jonfor** [runelite/runelite#14484]
**Is your feature request related to a problem? Please describe.**
The Prifiddnas map has no details on the World Map when outside of the city.

**Describe the solution you'd like**
The detailed Prifiddnas map used within the city should be used while outside the city.

**Additional context**
Undetailed map (Shown while outside):
![Capture](https://user-images.githubusercontent.com/3246528/146314374-f76fbdd2-1676-459f-9b17-a3a2a36ef927.PNG)

Detailed map (Shown while inside):
[Wiki Link](https://oldschool.runescape.wiki/w/Prifddinas#/media/File:Prifddinas_map.png)

**Comment by Jpmcrespo** [comment]
I'm pretty sure that if you click the blue arrows in the edges it shows you the detailed map, like with caves

**Comment by Jonfor** [comment]
> I'm pretty sure that if you click the blue arrows in the edges it shows you the detailed map, like with caves

Well, TIL! I'll close this issue.
