### ISSUE TITLE
Menu entry swapper overrides manual left click "wear" settings

### ISSUE THREAD

**Issue by KogasaPls** [runelite/runelite#14487]
**Describe the bug**
Some Menu Entry Swapper settings take priority over some (but not all?) manually set left-click options. For example, "Item Swaps --> Teleport item" overrides a manually-set "Wear" option on mythical capes and max capes. It does not override "Use."

**To Reproduce**
1. Enable menu entry swapper.
2. Enable "Item Swaps --> Teleport item."
3. Right click inventory, "Configure Left-click", set a mythical cape's left-click option to "wear" and save.

**Expected behavior**
Manually set left-click options should take precedence. 

**Screenshots**
![image](https://user-images.githubusercontent.com/87504405/146402355-a16e448a-0f7a-4242-9267-61d3176ef1d1.png)
![image](https://user-images.githubusercontent.com/87504405/146402386-171903b5-00dc-4051-8255-4d855e7e01e0.png)

**Environment (please complete the following information):**
 - OS: Arch Linux (Linux Zen 5.15.6)
 - RuneLite version: 1.8.7
 - Launcher version: 2.2.0

**Additional context**
When certain Menu Swapper (or other plugin) settings are enabled, left-click options are changed from default. For example, "Wear" is the default option on the mythical cape, but with "teleport items" in Menu Entry Swapper, the default option becomes "Teleport." Attempting to change it to "Wear" manually doesn't work, presumably because "Wear" is the **actual** default setting, so it is overriden by the plugin.

**Comment by Adam-** [comment]
fixed in 0f52e3ff18dcece4ff0ca39148bc2d0a9fb96e55
