### ISSUE TITLE
Graphical issue in the client side bar.

### ISSUE THREAD

**Issue by taylorswifty13** [runelite/runelite#1449]
I have stumbled upon an issue with the sidebar. I have attached images to show the issue. it changes around when you hover over other icons. I have tried reinstalling the client. closing and opening the sidebar. the only thing that solves it (temporarily) is closing the client and reopening it. my friend says he doesnt get this issue. if there is a fix for this please let me know.  If it helps I am running windows 10, have a xeon e3 1230 v5 and a gtx 1080ti.

![ybfenxd](https://user-images.githubusercontent.com/38328018/38700764-0dccb856-3e94-11e8-8cb9-9ccb33b1ee1a.png)

![vfzucnm](https://user-images.githubusercontent.com/38328018/38700770-11a2d5fa-3e94-11e8-9339-78b353a56733.png)

**Comment by deathbeam** [comment]
This will most likely be solved with https://github.com/runelite/launcher/pull/10.
If you want to test it, here is my build of the launcher with the change included: https://www.dropbox.com/s/wj8q3ui37zra1ey/RuneLite.jar?dl=0

**Comment by taylorswifty13** [comment]
Thanks for your reply. Been using that new version all night and didn't run into it once. My only problem now is a minor issue with the space below the game window being filled with random stuff. you can see in the image i attached what i mean. Sometimes it will fill the rest of the black space with other things from my desktop. this occurs for me using stretched full screen while maintaining the aspect ratio (i am aware that stretched full is a finicky feature to get working since nearly every client has some sort of issue with it)
![fqtqdl3](https://user-images.githubusercontent.com/38328018/38713464-3cdddd84-3ec9-11e8-8511-9fa60bcd42ff.png)

**Comment by deathbeam** [comment]
Awesome, glad it is working for you. The stretched fixed mode artifacts is different issue, #1105 .

**Comment by deathbeam** [comment]
Fixed in runelite/launcher#10

**Comment by Adam-** [comment]
A new launcher release 1.5.0 has been issued to address this.

**Comment by KingKleece** [comment]
I am still unfortunately receiving this issue. I have tried uninstalling the launcher and reinstalling it with no avail. I am pretty stumped because at this point I'm unsure how to resolve this issue. Thanks in advance.

![capture](https://user-images.githubusercontent.com/40524069/41811636-484c7f2c-76e1-11e8-9b24-e2f2b187e9d5.PNG)

**Comment by KingKleece** [comment]
@Adam- 
@deathbeam

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by KingKleece** [comment]
Thank you so much!

**Comment by LukeJefferies** [comment]
I'm also getting this issue;
I am using Runelite version 1.6.18.1 and I have disabled hardware acceleration as posted above. 
![Runelite Version](https://user-images.githubusercontent.com/7721573/83919551-bbf92880-a772-11ea-9c22-b2bc674f517d.png)
![Runelite HWMode](https://user-images.githubusercontent.com/7721573/83919650-f2cf3e80-a772-11ea-9bc3-efac626f46cb.png)
![Runelite Sidebar](https://user-images.githubusercontent.com/7721573/83919679-07abd200-a773-11ea-8700-b567d606b194.png)

**Comment by Nightfirecat** [comment]
Please see #11727
