### ISSUE TITLE
calculator suggestion update

### ISSUE THREAD

**Issue by tylerstone193** [runelite/runelite#14492]
Would be a very nice update if the calculator had a ironman checkbox which would calculate molten glass xp into the xp gained for something. why? this would let the calculator tell someone exactly how much molten glass they need to get without having to do the math of adding 20 xp to the base amount of xp given for making the item then dividing it by the total xp needed from current xp to the targeted xp level

**Additional context**
https://i.imgur.com/GjbgObC.png
https://i.imgur.com/FppvJXr.png

**Comment by Nightfirecat** [comment]
Holding shift allows you to select multiple items, which is what you're looking for.

**Comment by tylerstone193** [comment]
> Holding shift allows you to select multiple items, which is what you're looking for.

D: thanks
