### ISSUE TITLE
Multiple examine options when ground items "Show Menu Item Quantities" is enabled

### ISSUE THREAD

**Issue by LootBagger** [runelite/runelite#14490]
**Describe the bug**
A regression in the grounditems plugin probably due to `MenuEntry` changes in 1.8.7. Multiple "Examine" options are shown, when before 1.8.7, only one examine option was shown per item

**To Reproduce**
1. Enable the ground items plugin
2. Turn on the "Show Menu Item Quantities" option in ground items plugin
3. Drop two items in game
4. Right click the dropped items
5. Observe multiple examine options (see attached screenshots)

**Expected behavior**
I expect only one examine `MenuEntry` to appear per item id on the ground.

**Screenshots**
Multiple examine options!
![runelite1 8 7GroundItemsRegression](https://user-images.githubusercontent.com/91767458/146466476-939b1dd8-df00-43ff-b39b-42be015a9ab4.png)

Roughly how it looked before 1.8.7 (photo edited)

![runeliteGroundItemsFix](https://user-images.githubusercontent.com/91767458/146466531-ee96cad3-9d20-4678-8dbb-66b506cfe841.png)

**Environment (please complete the following information):**
 - OS: Arch, kernel 5.15.7-arch1-1
 - RuneLite version: 1.8.7
 - Launcher version: 2.1.3

**Comment by Adam-** [comment]
I fixed this a little earlier in e458507953442998f10638d55f2cbfd4e1065b67
