### ISSUE TITLE
Grand Exchange Plugin's 'fuzzy search' breaks bank tags search in the GE

### ISSUE THREAD

**Issue by Zoinkwiz** [runelite/runelite#14499]
**Describe the bug**

Usually when you search for something like `tag:clue` in the Grand Exchange, it will show results as the items you have tagged.

If you also have the 'fuzzy fallback' or 'fuzzy only' config settings on in the Grand Exchange plugin, this will override the aforementioned behaviour and instead show fuzzy results of the text searched.

It would make more sense to me for features such as tag searching to override fuzzy search.

**To Reproduce**

* Turn on 'Grand Exchange' and 'Bank Tags' plugins
* Turn on one of the fuzzy search config settings for 'Grand Exchange'
* Try to search for one of your bank tags in the Grand Exchange, for example 'tag:clue'
* Get fuzzy results of the text instead

**Expected behavior**
You should get the tag search results instead of the fuzzy results.

**Screenshots**
![2021-12-18 (2)](https://user-images.githubusercontent.com/29153234/146653239-70169d32-3bfe-4773-873b-3279d296d13c.png)
Example of fuzzy results instead of tag results.

**Comment by Adam-** [comment]
fixed in ce56056e2f89372d69a9af0683cb4266c4ebaa5c
