### ISSUE TITLE
Skills reduced notification

### ISSUE THREAD

**Issue by Deathking133** [runelite/runelite#14503]
An issue I often run into is when I brew down. I then try casting an auto cast and the auto gets removed, and I get no notification that I lost the auto. When the auto is lost even if I restore the levels the auto cast is not reset. Only notification is instead of casting a spell you run and melee the target.

**Describe the solution you'd like**
A notification when a skill drops below a specific level. Allow for customizable thresholds. Magic is one issue but agility can also be an issue if in the wild. (Hp and prayer already have a setting) if we had an option for all skills this would cover fringe cases that might arise. 

**Describe alternatives you've considered**
To my knowledge there is no ability to get a screen flash or notification sound when a skill other than HP or prayer drop below a set threshold. I could not find anything in the plugin hub or any settings in the currently installed plugins.

**Comment by jcarbelbide** [comment]
I guess the first question I have is where this feature would go. The plugin you reference I believe is the idle notifier, that sends a notification when HP or prayer falls below a certain threshold, but this feature wouldn't really be an idle notifier, so I'm not sure it fits there. I also did not find any other existing external plugin that does this, or may make sense to be updated to do this. So it sounds like it should be its own plugin. 

I'm going to try to see if I can get something working, but I'm pretty new to this so I'm learning as I go. I'll work on this tomorrow, and will provide updates.

**Comment by Deathking133** [comment]
> I guess the first question I have is where this feature would go. The plugin you reference I believe is the idle notifier, that sends a notification when HP or prayer falls below a certain threshold, but this feature wouldn't really be an idle notifier, so I'm not sure it fits there. I also did not find any other existing external plugin that does this, or may make sense to be updated to do this. So it sounds like it should be its own plugin.
> 
> I'm going to try to see if I can get something working, but I'm pretty new to this so I'm learning as I go. I'll work on this tomorrow, and will provide updates.

In a sense of easy to add idle notifier would be the easiest place to add this. It would not be a perfect match but it would still be notifying. Some friends of mine have coded this into a custom version of the plugin but they do not know how to publish the change. It was about an hour to code and test the change.

**Comment by jcarbelbide** [comment]
Wow they are fast haha. Still working on [my version](https://github.com/jcarbelbide/runelite-external-plugins/tree/skill-level-notifications). 

To publish it, [here is an article](https://github.com/jcarbelbide/runelite-external-plugins/tree/skill-level-notifications) that talks about how to submit a PR for an external plugin. If you wanted to change the official idle notifier plugin, it may be a bit harder to add this feature there, but they could submit a PR I suppose.

**Comment by jcarbelbide** [comment]
Hey, been a little bit, but I finished my plugin. I ended up just creating an overlay that address your first request: a notification when your magic level falls below the level required for a skill. Check out [here](https://github.com/jcarbelbide/runelite-external-plugins/tree/autocast-utilities). 

PR is [here](https://github.com/runelite/plugin-hub/pull/2287).

**Comment by adamk33n3r** [comment]
I'll add here that once [Watchdog](https://github.com/runelite/plugin-hub/pull/2308) is merged in, you'll have the ability to have a notifier for stat changes. It's not as specific for magic spells as @jcarbelbide's plugin (which is awesome btw) but it will allow for any stat drain. I have some plans to specifically enhance this trigger in my plugin after initial release to add more conditions.

**Comment by jcarbelbide** [comment]
> I'll add here that once [Watchdog](https://github.com/runelite/plugin-hub/pull/2308) is merged in, you'll have the ability to have a notifier for stat changes. It's not as specific for magic spells as @jcarbelbide's plugin (which is awesome btw) but it will allow for any stat drain. I have some plans to specifically enhance this trigger in my plugin after initial release to add more conditions.

Thanks, Adam! Once our plugins are merged, I think we can move to close this issue.

**Comment by Deathking133** [comment]
I apologize for going away from this thread so long. That is awesome that plugin looks like it will do what we need it to do. Thanks!

**Comment by jcarbelbide** [comment]
Thanks @Deathking133 ! I think there are still some stuff that can be added (like detecting when you no longer have enough runes in your inventory), but I'm glad you like the plugin!
