### ISSUE TITLE
Sidebar is missing/hidden/glitching

### ISSUE THREAD

**Issue by sysx6** [runelite/runelite#14506]
I have played on Runelite for weeks and didn't have any problems.

Suddenly, when I log in the sidebar (xp, settings, plugin hub etc.) is missing and I am not able to get it visible again. Doesn't matter if the window is small or fills the screen.

Any ideas? What information is needed? 

Looking forward.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
