### ISSUE TITLE
Ability to change infobox text to bold

### ISSUE THREAD

**Issue by lolplayer509845** [runelite/runelite#14505]
![image](https://user-images.githubusercontent.com/96413024/146734590-e0f8a09a-fd5a-4961-b119-505038ea672f.png)
![image](https://user-images.githubusercontent.com/96413024/146734624-0d5615f8-3758-4d3a-8554-841f3829dc48.png)

Was just requesting if there can be an option added to change the infobox text to bold. Right now you can have your overlay, tooltip, and interface text set to bold, but not the infoboxes. The text for infoboxes can go the "small" size if decreased in size, but does not go past "regular" to "bold". Just wondering if this is an easy addition. Image 1 is to show current infobox text, 2nd image is the requested text for infoboxes. Thanks

**Comment by Adam-** [comment]
added in 791912a7c0ea6fcac6972b6054da4469109947a5
