### ISSUE TITLE
Update the launch script to move the Runescape cache to a better location on Linux

### ISSUE THREAD

**Issue by coreybruce** [runelite/runelite#14510]
Hi there I wanted to request to update the Runelite launch script so it doesn't all just go to the main home folder getting mixed up with users files.

Here is the example code I use to easily resolve this and the code you can use to move it all to the .config folder to keep it all tidy and out of the way. :) 

```
#!/bin/sh

RL_DIR="/home/$USER/.config/Runelite"

if [ -z _JAVA_OPTIONS ] ; then
    _JAVA_OPTIONS="-Duser.home=\"$RL_DIR\""
else
    _JAVA_OPTIONS="$_JAVA_OPTIONS -Duser.home=\"$RL_DIR\""
fi
export _JAVA_OPTIONS

exec java -Dhttps.protocols=TLSv1.2 -jar /usr/share/java/runelite/RuneLite.jar "$@"
```
I hope my example code helps!

**Comment by abextm** [comment]
Duplicate #7940

**Comment by coreybruce** [comment]
Oops sorry about that, I'll move the talk to the proper post.
