### ISSUE TITLE
AppImage does not launch under Firejail / incorrect permission on launcher exectuable

### ISSUE THREAD

**Issue by ScoreUnder** [runelite/runelite#14519]
# Description
The `RuneLite` launcher executable inside the RuneLite Linux x64 appimage provided on the website has 764 permission instead of 755 permission. As a consequence `firejail` cannot launch it.

# Steps to reproduce
1. Install `firejail`
2. run `firejail --appimage RuneLite.AppImage`
3. See error

# Expected behavior
The program should be able to launch under firejail.

# Environment
 - OS: Linux (Gentoo 17.1, desktop, hardened, no multilib)
 - RuneLite version: N/A
 - Launcher version: 2.2.0
 - Firejail version: 0.9.64.4

# Additional context
```
score@hakurei ~/downloads/runelite % firejail --appimage RuneLite.AppImage 
Mounting appimage type 2
Reading profile /etc/firejail/default.profile
Reading profile /etc/firejail/disable-common.inc
Reading profile /etc/firejail/disable-passwdmgr.inc
Reading profile /etc/firejail/disable-programs.inc

** Note: you can use --noprofile to disable default.profile **

Parent pid 21666, child pid 21670

**     Warning: dropping all Linux capabilities     **

Child process initialized in 138.74 ms
zsh:1: permission denied: /run/firejail/appimage/.appimage-21666/AppRun

Parent is shutting down, bye...
AppImage unmounted
```

```
score@hakurei ~/downloads/runelite % unsquashfs -ll =(tail -c +188393 RuneLite.AppImage) | grep 'RuneLite$' 
lrwxrwxrwx root/root                 8 2021-09-25 19:49 squashfs-root/AppRun -> RuneLite
-rwxrw-r-- root/root             86152 2021-09-25 19:49 squashfs-root/RuneLite
```
Note permissions on the last file, `-rwxrw-r--` (764) instead of `-rwxrwxr-x` (775) or `-rwxr-xr-x` (755). This might be the result of a command like `chmod +x RuneLite` instead of `chmod a+x RuneLite`. ~~(I can't find the script which packages the AppImage but I would be happy to patch & PR this myself if necessary.)~~ (Found it)

Firejail seems to be enforcing these permissions to-the-letter, i.e. they state that only root is allowed to execute RuneLite, so it gets "permission denied" trying to execute it as another user.

Related discussion on Firejail's end: https://github.com/netblue30/firejail/issues/2690

**Comment by Adam-** [comment]
Setting group/world execute on the RuneLite executable seems fine, we do this already on osx - https://github.com/runelite/launcher/blob/master/build-osx-x64.sh#L66

**Comment by Adam-** [comment]
fixed in https://github.com/runelite/launcher/pull/103
