### ISSUE TITLE
[Suggestion] Add Soul Wars tables to Menu Entry Swapper

### ISSUE THREAD

**Issue by Toasty64** [runelite/runelite#14525]
**Is your feature request related to a problem? Please describe.**
It is not.

**Describe the solution you'd like**
There is currently no option within Menu Entry Swapper to change "Take-from" at the Bandage / Potion tables. It would be nice to be able to select from "Take-from, -1, -5, and -10".

Picture of the menu in question:
![RuneLite_Ng4y42AUM4](https://user-images.githubusercontent.com/22701517/147437904-0d37728f-8680-443b-ba19-c594147a05d2.png)

**Comment by Hydrox6** [comment]
This can now be done with the changes in 92aac53f4273e7944c3da767637e083847c03808
