### ISSUE TITLE
Chat Request

### ISSUE THREAD

**Issue by agithubusername1** [runelite/runelite#14520]
Hello, and Merry (upcoming) Christmas!

This particular issue is not strictly related to a feature request for the RuneLite client per-se, but I have been unsuccessful in contacting any maintainers or administrators of RuneLite thus far about my particular request, so I thought to try here.

If there's anyone I can contact on Discord to discuss the prospect of being reinstated message sending privileges in the RuneLite Discord, it would be greatly appreciated. Happy holidays!

**Comment by Nightfirecat** [comment]
This is a tracker for client bugs and feature requests, not a forum for unban requests. If you believe you have legitimate reason to be unbanned from Discord you can email the relevant info to nightfirecat (at) runelite (dot) net.
