### ISSUE TITLE
Add WorldHop shortcut

### ISSUE THREAD

**Issue by davjet1** [runelite/runelite#1453]
On osbuddy it is possible to press Ctrl + Shift + Left/Right arrowkey to hop one world backwards or forwards. Would it be possible to implement something like this?

**Comment by SourSpoon** [comment]
Support.

The OSB one also skips pvp worlds, f2p worlds, deadman worlds and tourney worlds.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by Nightfirecat** [comment]
Added in #4761
