### ISSUE TITLE
[Suggestion] Countdown timer on Gauntlet tiles

### ISSUE THREAD

**Issue by Zerviol** [runelite/runelite#14532]
Solution: Each tile for it to look clean not isolated on one. A countdown for when it disappears so you can predict the timing for your character to be safe.

Customizable colors for the actual numbers so it sticks out, alternative solution could just be one tile or optional if it's a feature.

Pretty straight-forward imo, just seems like a nice QoL to make Gauntlet easier all around.

**Comment by Hydrox6** [comment]
Banned by the [Jagex Statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1):
> Anything that automatically indicates where to stand, or not to stand. This applies to only automatic indicators, and not tiles which have been manually marked.
