### ISSUE TITLE
Frequent Disconnecting

### ISSUE THREAD

**Issue by sweater-god** [runelite/runelite#14535]
This issue started just a couple weeks ago out of nowhere. Only on runelite, i temporarily disconnect for a few seconds once every hour or so, while any other streaming service, game or application that uses internet in the back or by itself has had no issues at all. I've tried looking through logs when it happens and nothing ever shows up. my client never crashes and i have only disconnected long enough one time to go back to the log in screen. it freezes my client as if nobody is moving and no actions are being taken, then the screen goes white and it says "attempting to reconnect" in the top for about 5 seconds and then the game comes back. This has happened to me multiple times while bossing, questing, doing minigames and just afk skilling many times over the last couple weeks and it is extremely consistent. It is stopping me from progressing my account how i want to as i can't go out and do combat without a HUGE risk of dying. Ive tried turning all plugins off, still disconnecting, and im trying the OG client now to see if things are different. These are my most recent logs, i log out and close my client very shortly after experiencing a disconnect. If needed i can provide the launcher logs, however it only happens after about an hour or an hour and a half between disconnects. This has also happened on multiple different worlds, as i thought it was just due to high player counts/ping however it happens even when i have under 30ms ping on any world ive been in. EDIT: After playing on the original and steam client for multiple hours i have not encountered any of the disconnection issues i experience with runelite

[client_2021-12-29.0.log](https://github.com/runelite/runelite/files/7795343/client_2021-12-29.0.log)

[client.log](https://github.com/runelite/runelite/files/7795341/client.log)

**Comment by Nightfirecat** [comment]
RuneLite doesn't do anything with the client's networking, so this is much more likely to be something else on your computer interfering with RuneLite than it is RuneLite messing with the client. Anyway, this is a query better suited to the `#support` channel of our Discord server: https://runelite.net/discord
