### ISSUE TITLE
Menu entry swapper - setting customisable shift click to examine causes the game to freeze

### ISSUE THREAD

**Issue by joshkalsi** [runelite/runelite#14545]
If you set a custom shift-click option of an item to Examine, rather than the default of Drop, then hover (not click)the item holding shift,  it causes the game to freeze, requiring a full client restart. I've observed this issue on every item I've tested, so I assume it's global, but this may not be the case. This occurs even when all other plugins are disabled, and Menu Entry Swapper is reset to it's default configuration.

Items tested: Fire rune, Law Rune, Air Rune, Ensouled Dagannoth Head

The full logs are attached, but the specific error that is being logged at the crash point is 
`2022-01-02 21:07:33 [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index 972 out of bounds for length 5
	at fa.jo(fa.java:11146)
	at client.jb(client.java:11275)
	at bl.ji(bl.java:11514)
	at h.jy(e.java:11381)
	at bl.ji(bl.java:11865)
	at bl.ji(bl.java:11846)
	at bl.ji(bl.java:11846)
	at bl.ji(bl.java:11846)
	at h.jy(e.java:11381)
	at client.gg(client.java:3983)
	at client.i(client.java:1843)
	at am.k(am.java:335)
	at am.run(am.java:314)
	at java.base/java.lang.Thread.run(Unknown Source)`

Steps for reproduction:
Right click the Inventory button, and select Configure shift-click. Pick an item, and change the option from * Drop to * Examine, then save the changes. Hold shift and hover over the item - the game should freeze.

Runelite version: 1.8.8 (launcher version 2.1.3) 

Logs: 
[launcher.log](https://github.com/runelite/runelite/files/7799852/launcher.log)

[client.log](https://github.com/runelite/runelite/files/7799851/client.log)

**Comment by Adam-** [comment]
fixed in a2f8a4219e29aaf976f8cc78074e990ed0de0106
