### ISSUE TITLE
[Suggestion] Have the option to deselect agility shortcuts for Shortest Path plugin 

### ISSUE THREAD

**Issue by rploumpis** [runelite/runelite#14548]
Using the Shortest Path plugin without the agility level needed for certain shortcuts can be confusing. It would really help if there was the option to disable shortcuts so that the shortest path without agility shortcuts would be shown instead. And for extra credit, you could instead have RuneLite check our agility level and only use the shortcuts we are able to access.

**Comment by Nightfirecat** [comment]
We do not maintain the Shortest Path plugin, it is a hub plugin maintained by a community member. Please direct this request to its maintainers.
