### ISSUE TITLE
Ground item

### ISSUE THREAD

**Issue by Kingzelta** [runelite/runelite#14557]
The GE price doesn't show next to the HA price for ground Items. If I examine I also only see the HA price of the item. I did not change anything in the settings for the ground items or loot. 
![Knipsel](https://user-images.githubusercontent.com/97231980/148383934-c489a5d9-86f2-4048-9b6e-e6b93df14a0b.PNG)

**Comment by hex-agon** [comment]
The issue tracker is not a support forum, please join our discord and use the #support channel
