### ISSUE TITLE
Entity Hider Clan Members

### ISSUE THREAD

**Issue by LeonardoMaurins** [runelite/runelite#14558]
**Is your feature request related to a problem? Please describe.**
In masses for content like Nex, it's annoying having too many players on screen and with entity hider working successfully, its still a problem not being able to only see clan members, similar to friends clan function.

**Describe the solution you'd like**
I believe a "Clan members" toggle to see players from your clan when using entity hider to hide the rest should be added. This would allow you to see all members of the clan you're in, similar to how the friends clan chat toggle currently works.

**Describe alternatives you've considered**
I believe the implementation should be simple enough with all the code already in place for such an addition.

**Comment by Adam-** [comment]
added in 6924802362436e022a8a48e2fee550f2c784899c
