### ISSUE TITLE
Let RuneLite be detected as window by 1Password

### ISSUE THREAD

**Issue by MarcDirven** [runelite/runelite#14560]
**Is your feature request related to a problem? Please describe.**
A little bit, since my RS password is very cryptic, I often can use 1Password to use "Type in window > <some window>". But not, as you can see in the screenshot, it can't recognize it as a window. Restarting both services didn't result in the expected behaviour.

**Describe the solution you'd like**
I'd like to see that RuneLite shows up in "type in window" menu.

**Describe alternatives you've considered**
Restarting both services.

RuneLite was active at the time the screenshot was taken.
![Screenshot_1](https://user-images.githubusercontent.com/31624073/148588109-cf37bd8e-fe4b-4a80-9ea2-c6336567d3a9.png)

**Comment by deathbeam** [comment]
Have you tried disabling custom chrome? That will most likely fix it

**Comment by MarcDirven** [comment]
I have and have also had some contact with 1Password. 1Password said that copying the password from 1Password and then pasting using Ctrl-V within runelite (while the cursor is on password) does work. Should have said this earlier but forgot all about this issue. 

I've also disabled the Chromium framework due to other reasons but I can imagine the window appears in "Type in window" after disabling it.
