### ISSUE TITLE
Medium clue - doesn't open clue interface or label emotes in order 

### ISSUE THREAD

**Issue by mtarik550** [runelite/runelite#1456]
I've also posted two similar reports so its basically like them.. I'll also include a picture so you know which clue. 
https://i.imgur.com/CpGrxY0.png

**Comment by Kamielvf** [comment]
theres #1309 which is probably better to post them there, theres several issues there already too so you can see if you're not submitting a duplicate.

**Comment by mtarik550** [comment]
Okay, I'll start posting them there from now :) thanks for letting me know.
