### ISSUE TITLE
Hiscore: Skotizo KC being displayed as Scorpia KC

### ISSUE THREAD

**Issue by Nilhilo** [runelite/runelite#14564]
**Describe the bug**
Runelite Hiscore displays Skotizo KC as Scorpia KC.
This is possibly an issue since the addition of Nex. 

**To Reproduce**
1. Go to the Hiscore tab within runelite
2. Look up any player with Skotizo KC
3. Scroll down to the Scorpia KC

**Expected behavior**
The player's Skotizo KC and rank should be displayed as Skotizo KC and rank

**Current behavior**
The player's Skotizo KC and rank is displayed as Scorpia KC and rank

**Screenshots**
![screenshot-2](https://user-images.githubusercontent.com/86553685/148628528-4f21eb82-4f23-41a5-a77d-cd32bcc78058.png)
![screenshot-1](https://user-images.githubusercontent.com/86553685/148628529-423b7214-8733-47d7-bd9b-69ec91c4710a.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.9
 - Launcher version: 2.1.3

**Additional context**
I have no idea what is currently being displayed as Skotizo KC.

**Comment by geheur** [comment]
This is a known issue on jagex's end, they are working to fix it: https://twitter.com/RubenPsikoi/status/1478696750860972033

**Comment by Nightfirecat** [comment]
It will be fixed next week, so we are not applying a fix on our end for this single week it's broken.
