### ISSUE TITLE
Runelite Outdated Error

### ISSUE THREAD

**Issue by fuckgithub03** [runelite/runelite#14573]
Runelite shows popup saying it is outdated and in reduced functionality mode.

This occurs on one PC not any others.

![image](https://user-images.githubusercontent.com/97377129/148671385-1164232e-1f39-4943-862f-32c3ca89df82.png)
![image](https://user-images.githubusercontent.com/97377129/148671391-5692080f-f85a-481c-9c93-dcd8d2cd30ec.png)

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.

**Comment by fuckgithub03** [comment]
Thanks!
