### ISSUE TITLE
MenuEntrySwapper: Nex Portal Private instance

### ISSUE THREAD

**Issue by wagnerjt** [runelite/runelite#14572]
**Is your feature request related to a problem? Please describe.**

To avoid joining in the Nex portal accidently, we can add another option in the menu entry swapper plugin. This can be by waiting for people to join in the party, miss clicking the bank, or trying to go into the private instance. 

**Describe the solution you'd like**

By having the menus swapped between private and normal entry, we can avoid since the private instances ask if you want to join an instance or start your on. 

Note: A very similar feature is the Corrupted Gauntlet menu entry.

**Describe alternatives you've considered**

It could also be resolved by hiding the left click to enter. You are forced to right-click the portal for the entry options

**Comment by Hydrox6** [comment]
This can now be done with the changes in 92aac53f4273e7944c3da767637e083847c03808
