### ISSUE TITLE
Loot tracker doesn't track coin drops if you're using a ring of wealth

### ISSUE THREAD

**Issue by Palyon-dev** [runelite/runelite#14578]
I'm not sure if this fits better under "bug" or "feature request," but I'll treat it as a bug.

**Describe the bug**
If you're using a ring of wealth to pick up coin drops automatically, said coin drops won't be tracked by the loot tracker.

**To Reproduce**
1. Equip a ring of wealth
2. Kill something that drops coins until you get a coin drop
3. Check loot tracker, see that the coins you got aren't tracked

**Expected behavior**
The loot tracker should track coin drops while you're using a ring of wealth

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.9
 - Launcher version: 2.1.3

**Comment by abextm** [comment]
duplicate #5077
