### ISSUE TITLE
Grass clipping through POH with ground blending turned on in Runelite HD

### ISSUE THREAD

**Issue by Cambysses** [runelite/runelite#14583]
Big fan of Runelite HD, however I noticed an unfortunate visual bug when "ground blending" is enabled. 

In my POH (at least with the house styles I have tried) the outside grass blends into the indoor floor tiles. It looks like I have a major mold issue or something.

Here's how it looks with blending on:
![image](https://user-images.githubusercontent.com/36931193/148870385-a97c8396-cc28-43b9-800f-a592382102c0.png)

And off:
![image](https://user-images.githubusercontent.com/36931193/148870397-9cf32adb-9e64-41d9-9307-14602e4d0936.png)

For reference here are my HD settings:
![image](https://user-images.githubusercontent.com/36931193/148870455-294e98f1-2a32-48bc-8aee-4ab9f7479ff9.png)

**Comment by Nightfirecat** [comment]
Please open an issue on https://github.com/rs117/rlhd; we do not maintain hub plugins.
