### ISSUE TITLE
Pin UI elements to the black space around game

### ISSUE THREAD

**Issue by jplarsen98** [runelite/runelite#14584]
I don't know if this is possible or not, but I think it would be very cool if you were able to pin elements of the UI to the black space around the game screen. Things like the XP Globes plugin, XP Tracker, Opponent Information, etc. It would keep the game window a lot cleaner while also letting people add a lot more information to their screen. Playing in fixed mode the game can feel a little cluttered with too many plugins on the screen and I think this would be a great use of the wasted space! As you can see in the picture if you go fullscreen there is a huge amount of space that could be used for all the different plugin UIs.

![RuneLiteSuggestion](https://user-images.githubusercontent.com/97491848/148872899-777f952c-f457-4d15-8679-57669d0d210a.png)

**Comment by raiyni** [comment]
You can enable resizable mode in the the runescape settings or enable the stretched mode plugin
