### ISSUE TITLE
add Blood essence to Item Charges plugin

### ISSUE THREAD

**Issue by DingusPingus** [runelite/runelite#14589]
Since blood essence can be high alched for 120k coins even when they only have one charge left it is beneficial to check when your blood essence is at very low charges and then high alch them before it disintegrates. but this requires you to manually press check on the blood essence to see the count. I am pretty sure this check can be avoided similar to how slayer gems count kills left or teleportation jewelry counts charges left.

**Comment by DingusPingus** [comment]
Blood Essences were actually just changed so that you can no longer high alch the active version. I believed this change to the blood essence slightly reduces the need for this feature but it would still be beneficial to add in the future.

**Comment by Adam-** [comment]
added in #14567
