### ISSUE TITLE
Hiscore tab is off after Nex addition. Scorpia and Skotizo are swapped

### ISSUE THREAD

**Issue by FondleBottoms** [runelite/runelite#14585]
**Describe the bug**

As title says. Seems like those two are swapped since nex hit the hiscores. Not a huge deal but tolerance stacking and all that stuff. Thank you :)

![image](https://user-images.githubusercontent.com/97492526/148874292-eed2f2a8-d96c-41c1-b272-88b062fbbbb7.png)
![image](https://user-images.githubusercontent.com/97492526/148874410-b0bfb797-38f5-4ba0-b23a-229214d24db5.png)

**Comment by Nightfirecat** [comment]
Duplicate of #14564
