### ISSUE TITLE
chatbox faces in main game- gpu (feature request)

### ISSUE THREAD

**Issue by liosrakia** [runelite/runelite#14597]
I've always thought that the faces from classic added a lot of character to the game. Certain NPCs have pretty noticeable features, and even our own character looks...more expressive in chat boxes. Considering the graphical element of the head is in the game, I was wondering if anyone has looked into a GPU plugin that allows the chatbox heads to replace the standard blank expression heads for players and npcs. 
![elena chathead](https://user-images.githubusercontent.com/48603673/149653971-1a7482e8-efb2-42d7-b0fb-0e604fceac0f.png)
![elena](https://user-images.githubusercontent.com/48603673/149653972-c9b34d37-cfa9-4085-a6cc-4ab760d26b64.png)

**Comment by Nightfirecat** [comment]
There's not a way for us to splice the models together the way you're describing--they are completely separate.
