### ISSUE TITLE
[Request] Change Phosani's Nightmare boss hi score icon to parasitic egg

### ISSUE THREAD

**Issue by Jager618** [runelite/runelite#14590]
Currently Nightmare and Phosani's Nightmare both use the same icon on the Hi scores. To match COX and ToB challenge modes that use the pet metamorphic dust as their Hi Score icon, it could have the parasitic egg as the icon. I think it would be a nice feature for clarity.

![100px-Parasitic_egg_detail](https://user-images.githubusercontent.com/35355439/149291600-c2d95c3b-bf9c-45fe-9653-dfa4ca007979.png)

**Comment by geheur** [comment]
dupe #14524 and #14214
There's also #14247 pr to change the icon.
