### ISSUE TITLE
Nex plugin

### ISSUE THREAD

**Issue by Mayerdynn** [runelite/runelite#14598]
**NEX plugin**
The chat is being spammed by multiple lines of her dialog:
AT LAST, Fumus!, Umbra!, Cruor!, etc.
There is also currently no way to mute her or filter the messages

**Solution:**
It would be great if her voice audio sounds were imported from pre-eoc and at the same time give us an ability to filter her chat messages in game.

Also, while we are there, - it would be great if we had some damage immunity indicators

**Comment by Alexsuperfly** [comment]
1) chat filter plugin for removing her chat
2) nex nostaliga plugin from the hub for adding voice lines

**Comment by Hydrox6** [comment]
The voices are already in a hub plugin.

The chat messages should be filterable with `Chat Filter`

and whether Nex is immune at the moment is covered by either the voice line, or the chat messages
