### ISSUE TITLE
Item Identification: Add Label for Jewellery (Enchanted & Non-Enchanted)

### ISSUE THREAD

**Issue by corrigami** [runelite/runelite#14612]
**Is your feature request related to a problem? Please describe.**
As a colour-blind player, I find that distinguishing the different jewellery (unenchanted and enchanted) is quite difficult.

**Describe the solution you'd like**
Add in a category in the Item Identification plugin for jewellery (and separately enchanted jewellery).

**Describe alternatives you've considered**
Not much I can think of, as I struggle with it regardless :(

**Comment by JordanHanley** [comment]
Working on this now.
