### ISSUE TITLE
My world map, run energy, spec attack, and insta prayer icon has disappeared

### ISSUE THREAD

**Issue by Rawr2134** [runelite/runelite#14618]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
1. Go to 'Runelite'
2. Click on ' Any Shattered Relics World '
3. Scroll down to 'look at my world map'
5. 
![image](https://user-images.githubusercontent.com/20760860/150493657-b60ed50d-fd4a-4936-a152-c171da2efd9f.png)

**Expected behavior**
These Icons to appear 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 
 - RuneLite version: 1.8.10
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
![Problem](https://user-images.githubusercontent.com/20760860/150493923-9ff8d0be-fbb3-437f-809b-2b47e74e00c3.PNG)

**Comment by Nightfirecat** [comment]
Turn on the "Show data orbs" option found under the "All Settings" option ingame.
