### ISSUE TITLE
Add "Zealot's robes" bonus effect to "Skill Calculator"

### ISSUE THREAD

**Issue by TiboDeMunck** [runelite/runelite#14610]
**Describe the solution you'd like**
Add the Zealot's robes bonus effect to the Skill Calculator on the prayer tab

**Describe alternatives you've considered**
Calculating it myself

**Comment by Giovds** [comment]
The [wiki](https://oldschool.runescape.wiki/w/Zealot%27s_robes) states the following:
> Zealot's robes are a set of robes that provides a 1.25% chance per piece to prevent [bones](https://oldschool.runescape.wiki/w/Remains#Bones) or [ensouled heads](https://oldschool.runescape.wiki/w/Ensouled_head) from being consumed whilst training [Prayer](https://oldschool.runescape.wiki/w/Prayer) – totaling 5% with the full set equipped.

A couple of things to note:
- The set does not provide an experience bonus. So it would probably follow [similar math as the Chaos Altar](https://oldschool.runescape.wiki/w/Chaos_Temple_(hut)#Mathematical_Proof).
- It works both on bones and ensouled heads. Quickly glancing over the code, the latter seems to require quite a refactor.
- It can be stacked with the Chaos Alter (resulting in a 52.5% chance of not consuming bones).
