### ISSUE TITLE
Fishing session stats not working.

### ISSUE THREAD

**Issue by donbfry** [runelite/runelite#14626]
**Describe the bug**
Fishing session stats are not working. Just shows the status of "Fishing" or "Not fishing".

**Screenshots**
![fishingstats](https://user-images.githubusercontent.com/33989414/150650073-2d8896b4-99aa-40c5-9a89-fc7d48d6a07e.png)
![fishingsettings](https://user-images.githubusercontent.com/33989414/150650092-277b7a85-dc16-4956-9e08-6292f4aaea99.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - RuneLite version: 1.8.10
 - Launcher version: 2.3.0
 - Oldschool revision: Rev 202

Fishing plug-in is enabled and "Show Fishing session stats" is checked. Also uninstalled Runelite and deleted every single leftover file and reinstalled. Still didn't work.

**Comment by Adam-** [comment]
Is the xp tracker on?

**Comment by Alexsuperfly** [comment]
turn on the xp tracker plugin

**Comment by donbfry** [comment]
That was the issue. Wonder if it would be possible to add a note in the description when hovering the "Show session stats" to mention Xp Tracker needs to be on.
