### ISSUE TITLE
Shift click not changing to eat/wield/etc anymore, defaults to "deposit-1".

### ISSUE THREAD

**Issue by Raisoshi** [runelite/runelite#14628]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Shift click from bank interface changing to "deposit-1" instead of eat/wield/etc. Randomly stopped working, have double checked that the option selected is right.

**Expected behavior**
Option to equip the item.

**Screenshots**
https://imgur.com/a/UlKr216
Shift is pressed down here.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: Not sure how to check, probably latest?

**Comment by Adam-** [comment]
This works ok for me. You probably don't have the inventory item options on 
![image](https://user-images.githubusercontent.com/309739/150686050-62261ed7-7ae9-409f-ab69-1ab62ca31ccc.png)

**Comment by Raisoshi** [comment]
Thank you I'll try that, I just found it weird that it randomly stopped working, maybe I missclicked the option or something
