### ISSUE TITLE
Idle Notification when Runelite is the active window

### ISSUE THREAD

**Issue by LittleVinne** [runelite/runelite#1462]
Can you please either by default or with a toggle add the idle or prayer/hp low notification when the RuneLite client window is the open/active window? Its nice to have a notification when you are doing something else in the room or watching tv when window is still open.
Thank you! and thank you for all that you've done. This client is amazing

**Comment by deathbeam** [comment]
Go to "RuneLite" settings, there is setting "Send notification when focused".
