### ISSUE TITLE
Add shift-click option to add/remove relic fragments

### ISSUE THREAD

**Issue by emerald000** [runelite/runelite#14625]
**Is your feature request related to a problem? Please describe.**
The current fragment interface is clunk and slow to use.

**Describe the solution you'd like**
In the fragment menu, the shift-click would modify the default option from View to Equip (on the equipped fragments) or Unequip (on the list of fragments)

**Comment by Nightfirecat** [comment]
Leagues is over now, but this was added to several hub plugins which helped manage relic loadouts/presets.
