### ISSUE TITLE
Leagues Relic Progress

### ISSUE THREAD

**Issue by PerishBtw** [runelite/runelite#14624]
Any chance we can get a feature where a small progress bar under or below each relic fragment (above chat UI) will show progress towards the next tier?
Picture for reference:
[https://gyazo.com/9b36f93827746e16397f4841bc63a0e8](url)

**Comment by Bram91** [comment]
There is a plugin on the plugin hub that does that called `Shattered Relic XP`.

**Comment by PerishBtw** [comment]
Ah, I see. I hadnt updated my client so I didnt see it in the hub. My bad.
