### ISSUE TITLE
[Suggestion] Better Greenscreen Plugin

### ISSUE THREAD

**Issue by Mud-Brain** [runelite/runelite#14622]
**Is your feature request related to a problem? Please describe.**
The current greenscreen plugin is incredibly inefficient, manually drawing a background around the player and tanking performance.

**Describe the solution you'd like**
All the plugin needs to do is unrender everything except the player and let me change the color of the skybox.

**Describe alternatives you've considered**
I can make due using my POH grass but it doesn't work for green outfits or extreme angles.

**Comment by raiyni** [comment]
Make an issue on the plugins repo.
