### ISSUE TITLE
Opaqueness setting for Lootbeams

### ISSUE THREAD

**Issue by russel204** [runelite/runelite#14620]
Not sure if its possible for the new lootbeams that were added but i'd love the ability to make them a bit more opaque. They're gorgeous and i'd love to be able to make them stand out a bit more

**Comment by Adam-** [comment]
The existing beams are actually lit incorrectly compared to West's original screenshot, which we will be fixing soon, which will make them more vibrant.

**Comment by russel204** [comment]
@Adam- that's lovely to hear! thank you :)
