### ISSUE TITLE
Ghosting in the plugins (right window) UI. 

### ISSUE THREAD

**Issue by CalebCo** [runelite/runelite#14635]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Ghosting in the plugins (right window) UI. Please see here for what it looks like: https://imgur.com/a/pKml1W4 I've already attempted disabling hardware acceleration in this guide: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

Makes using plugins almost unusable. 

**To Reproduce**
1. Open Runelite
2. Open right side bar
3. Run mouse on side bar
5. Resolves if I resize Runelite's dimensions. Reappears the moment I move the mouse over it again.

**Expected behavior**
For ghosting not to show up 

**Screenshots**
(https://imgur.com/a/pKml1W4) included photo of what the ghosting looks like and having hardware acceleration turned off

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.8.10
 - Launcher version: 2.1.3

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.
[client.log](https://github.com/runelite/runelite/files/7930274/client.log)

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
