### ISSUE TITLE
Menu Entry Swapper Equip in Bank isn't Working

### ISSUE THREAD

**Issue by jevonsp** [runelite/runelite#14638]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Shift Click in bank behavior for equipping items is being ignored

**To Reproduce**
1. Set Bank Deposit to Eat/Wield/Etc
2. Withdraw a piece of equipment and try to equip it with shift click
3. The item defaults to Bank Withdraw rules and deposits instead

**Expected behavior**
The item should equip

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.8.10
 - Launcher version: 2.1.6

**Comment by geheur** [comment]
do you have the jagex bank setting for the eat/wield option enabled? In other words, do you see that option in the right-click menu?

**Comment by jevonsp** [comment]
Yes I do

**Comment by gregkopcienski17** [comment]
Any word on the fix? I am also having this issue

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
