### ISSUE TITLE
Make the Notifications feature actually relevant please

### ISSUE THREAD

**Issue by Kwazix** [runelite/runelite#14639]
**Is your feature request related to a problem? Please describe.**
The current "notifications" add on is essentially useless as it is. A number of things need to be improved or added.

**Describe the solution you'd like**
1. Add more options for the notification system in general, Multiple ways to be notified(Multiple sound choices, Screen indicators, Pop ups ect. Options to have Notifications both in the foreground and in the back ground. 

**Additional context**
If not updated honestly you might aswell remove the feature entirely, because unless you're glued to your screen and chat box (which would make an additional notification add-on useless to begin with) then the feature is useless, Idk how many times ive let complete farm patches go for hours without being renewed because the "notifications" failed to appropriately notify me.  Same thing goes with dieing because prayer drops to 0. There should be more options and they should be more advanced. More notification options, The option to have foreground and background notifications and the option to pick different noise indications depending on the notifications. Having 1 sound for every notification is kind of redundant to begin with....

**Comment by Hydrox6** [comment]
All of these are already things you can do with the notifier

**Comment by Kwazix** [comment]
Which one, Ive checked all the built in plugins as well as the external ones and none of them have any of the necessary features I mentioned.

**Comment by LlemonDuck** [comment]
Notification features are under the "RuneLite" settings, with their own collapsible section for "Notification Settings":

![image](https://user-images.githubusercontent.com/1868974/151074858-1272d511-fa28-4fad-a92b-a6cb84c20b04.png)

You can provide screen flash settings, custom sounds, game messages, native (tray) notification support, etc.

**Comment by Kwazix** [comment]
Ah that’s slightly helpful, but again the options are still quite limited, They should be more customizable. Such as different notifications and notification sounds for different things.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Hydrox6** [comment]
That's a duplicate of #11679

**Comment by adamk33n3r** [comment]
And would (at least partially) be solved by my plugin [Watchdog ](https://github.com/runelite/plugin-hub/pull/2308) once merged. I do plan on adding more trigger and notification types in the future after release.
