### ISSUE TITLE
Runelite side bar is gone

### ISSUE THREAD

**Issue by wierzba3** [runelite/runelite#14642]
Version 2.3.0

My runelite client shows no functionality at all except barebones runescape. No overlays and no side bar on the application. I'm confused, maybe this is user error? Do I need to enable runelite somehow? 

<img width="961" alt="Screen Shot 2022-01-25 at 8 44 09 PM" src="https://user-images.githubusercontent.com/3789407/151100727-002644f0-226e-4fc1-ab84-75db5db0ba00.png">

**Comment by Nightfirecat** [comment]
Hover in the upper-right corner of the client, near your minimap, to see a `>` button appear, which will open your sidebar. Alternatively, Ctrl + F11 should be the shortcut to toggle the sidebar.

**Comment by wierzba3** [comment]
oh wow, thanks
