### ISSUE TITLE
PlayerIndicators libraries

### ISSUE THREAD

**Issue by DragonTTK** [runelite/runelite#14681]
Does anyone know what libraries are used for Player Indicators i've been trying to use a lightly modified version but isn't showing up in the runelite plugin directory but seems to compile fine i've also tried a version without any changes and same thing.

It starts plugin according to logs but never actually loads it.

https://github.com/runelite/runelite/tree/master/runelite-client/src/main/java/net/runelite/client/plugins/playerindicators

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support. Instructions to join the `#development` channel can be found using the `/dev-channel` command.
