### ISSUE TITLE
Webhook for Death screenshots

### ISSUE THREAD

**Issue by HogyBun** [runelite/runelite#14689]
Can there be an option added to the screenshot section for discord webhooks? Will be nice to have a chat channel to make fun of people dying not just in raids but anywhere too. 

I know there's already a plugin called Raid Shamer, but that creator doesn't seem to be updating that plugin any longer.

**Comment by Shexting** [comment]
also a Webhook for clan broadcasts like loot/ pets/ levels
Also deaths for clanmates/friends/self

**Comment by JakeDeakin** [comment]
There looks to be a couple of plugins in the plugin hub that do what you want. 1 does all deaths. Another does deaths, levels, quests, pets and clues. https://github.com/jamesdrudolph/Discord-Death-Notifications/ https://github.com/WilliamWinterDev/Discord-Notifications
