### ISSUE TITLE
Add additional granularity to "Send notifications when focused"

### ISSUE THREAD

**Issue by Jademalo** [runelite/runelite#14694]
**Is your feature request related to a problem? Please describe.**
In the notification settings, there is an option for `Game message notifications`. This is pretty useful, and outputs whatever notification is sent directly to the chat box. However, for this to work when the window is focused, `Send notifications when focused` needs to be ticked.
The issue is that when the window is focused, the full system notifications aren't necessary. However, it would still be nice to have the information printed in the chat box.

**Describe the solution you'd like**
Instead of being a simple check box, have a dropdown for `Send notifications when focused` - `None`, `Chat Box Only`, `Full`. This allows for more control over how the chat box messages are printed, regardless of other settings. 

There may be a better way to allow more combinations of the three core settings of `Enable tray notifications`, `Game message notifications`, and `Send notifications when focused`, but the above solution is the best I can come up with. The one weird case is if `Game message notifications` is disabled then `Chat Box Only` is the same as `None`, but I think no matter how it's set up there's going to be a partially redundant option somewhere.

**Comment by Adam-** [comment]
This is probably superseded by 7eaa9ca7be3f46dbd78634de8f6389e4507bfde5 as now each notification can be set individually to do different things.
