### ISSUE TITLE
Drop Notifications

### ISSUE THREAD

**Issue by IronPerish** [runelite/runelite#1469]
So I like to AFK while using a cannon. Sometimes I can't see everything my cannon is hitting on my screen if I'm standing still and there are certain items I'm waiting to drop.
Is there anyway someone could make an item list that if it drops, not only will it show up with a colorful text on the ground, there will be a bell noise letting you know it dropped?

**Comment by Exstatic** [comment]
Along with this, lets say we have are hunting champions scrolls which take forever. It would be nice to get an alert

**Comment by Reasel** [comment]
I have started working on this. Would it be better to have a separate list for items to be notified of or a toggle that will notify the user if a highlighted item is dropped?

**Comment by deathbeam** [comment]
I would say toggle to notify on highlighted item

**Comment by Reasel** [comment]
Next decision is if we want a windows notification like the idle notifications or just a sound to play. Right now with the sounds being tied to the in game sound I am leaning towards windows notification, but some sort of chaching sound would be really cool later.

**Comment by deathbeam** [comment]
If you use the `Notifier` class for sending the notification it can be configured from the "RuneLite" settings to show either only notification, or only sound, or both. That is the preferred way to notify user, as then all changes could be done from the Notifier, so I would just use that one.

**Comment by Reasel** [comment]
Awesome that is what I have right now. So things should follow the "RuneLite" settings. Ill test it when I am able to play.

**Comment by king-koda** [comment]
just wondering if this feature has been added yet or not? when it does it will make every other client even more obsolete, seriously afking this game with notifications is the way of the future

**Comment by deathbeam** [comment]
This was implemented in #3643

**Comment by seitzcasey** [comment]
I may be stupid but it seems that #3643 and this were both closed due to there being duplicates
