### ISSUE TITLE
chat transcripts plugin feature request

### ISSUE THREAD

**Issue by Tech-Freddie** [runelite/runelite#14706]
**Is your feature request related to a problem? Please describe.** 
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...] no 

**Describe the solution you'd like**
add a toggleable option to the chat transcripts plugin when enabled upon a kick issued to a user a transcript is automatically saved to the screenshots folder this would include the entire chat so that upon some one questioning a kick there is proof of why they kicked the person in question or if kicked for no reason there is proof as well 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
