### ISSUE TITLE
A plug in the reminds you of an item you specify if you leave the bank without it (bank reminder)

### ISSUE THREAD

**Issue by martinezjorge** [runelite/runelite#1470]
Ever forgotten a holy wrench when you wanted to take it? Ever gone to <insert color here> dragons and forgot your anti dragon shield?

This plug in will let you specify an item or a list of items that you want RuneLite to remind you off whether its an item in your inventory or and equipped item. 

I also want the user to be able create a list of items they want checked for and be able to save that list to a drop down menu so they can quickly switch between lists that would help them in whatever they are doing.

**Comment by jerwuqu** [comment]
How would you configure such a thing and how would you use it?

Let's say you're gonna go on something that requires a holy wrench, do you enable the plugin then? If that's the case... Why not just have a list or use bank tags? 

It's an interesting idea but I don't understand how it would be used; could you explain?

**Comment by martinezjorge** [comment]
Well I'm trying to figure that out.  I kinda have like an outline of code I'll post when I get to my computer but it's mostly a java file filled with comments.  
It definitely would use some of the bank plug in code and it has to check your inventory and equipped items.
You'd activate the plug in when you need it if for example your going to camp but want to also bank when inventory is full.
I really want to try to do this as it's an idea I have had for a while.

**Comment by Nightfirecat** [comment]
@martinezjorge Why did you remove the text and title? It would be more useful to simply close this issue instead of erasing what you've written.

**Comment by martinezjorge** [comment]
I'll put it back on but I want to work on it as my first contribution.

**Comment by Cyborger1** [comment]
Does the [Inventory Setups](https://github.com/dillydill123/inventory-setups) hub plugin work for this issue?

**Comment by Nightfirecat** [comment]
I think that sufficiently fulfills this request for now. If something more specific is needed, I would recommend writing a hub plugin for that.
