### ISSUE TITLE
"Send notifications when focused" causes double notifications

### ISSUE THREAD

**Issue by Brickfingers** [runelite/runelite#14700]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

I couldn't find anything similar searching for "send notifications"

**Describe the bug**

When killing slayer monsters with the checkbox for "Send notifications when focused" under Runelite checked, I am getting double messages appear in my chat saying
"A superior foe has appeared..."
"A superior foe has appeared..."

**To Reproduce**

Setup the relevant settings:
Runelite -> Game message notifications -> checked/on
Runelite -> Send Notifications when focused -> checked/on
Slayer -> Superior foe notification -> checked/on

Kill slayer monsters to get a superior to spawn. Notification plays twice.

**Expected behavior**

Only one message

**Screenshots**

https://imgur.com/a/17EVlbT

**Environment (please complete the following information):**

 - OS: Windows 10
 - RuneLite version: 1.8.11
 - Launcher version: 2.3.0

**Comment by Alexsuperfly** [comment]
The notification message associated with the notification for receiving a superior slayer creature is the same message that jagex makes, so when you tell the notification to be printed in the chat you will see a seemingly duplicate one
