### ISSUE TITLE
Disabling left clicks on chat window

### ISSUE THREAD

**Issue by PenguinMeat** [runelite/runelite#14703]
Sometimes when trying to spam click a chat option or click a skilling menu that appears over the chat window, I will end up clicking a few times on the chat window. This sometimes leads to accidentally adding friend/ignoring/reporting of players whose messages are under my mouse cursor in the chat box. This usually occurs when trying to click a chat box option while in combat and trying to spam the button as fast as possible to prevent the combat hits from removing the chat options.

A simple solution to this issue would be an option to disable left clicks on the chat box.  Left clicks and right clicks already act the same way in the chat, so no functionality would be lost.

Alternatively, the option to remove menu entries from the left click chat box menu would also prevent accidentally adding friends or ignoring players accidentally.

**Comment by LlemonDuck** [comment]
There is already a vanilla workaround for this: The space bar will advance chat, and numerical keys 1-9 can select dialogue options.

I think disabling left click options over the chatbox is a big net-negative change in terms of usability for mostly a non-issue.

**Comment by Nightfirecat** [comment]
I agree with LlemonDuck here, this does not seem like a feature which would be of much benefit given that keyboard chat dialog navigation is a vanilla feature which works well for this situation.
