### ISSUE TITLE
Chat filter plugin includes blocking messages from self

### ISSUE THREAD

**Issue by SynapsisMK** [runelite/runelite#14705]
Hello, a small issue I noticed and I'm thinking it's a quick fix.  Within the chat filter plugin settings, I have the filter type set to remove, and the repeat filter set to 3.  This is great for reducing spam.  It has a side effect however of also removing repeat messages I've sent myself, which in my case is "!task".  In this case, I cannot check my task count using the command unless I disable the repeat filter.

**Comment by geheur** [comment]
I can only get this to happen with the "Collapse Player Chat" option enabled. Without that my repeated messages do not get filtered.

**Comment by SynapsisMK** [comment]
Seems you're right, thank you.

**Comment by geheur** [comment]
I was just adding some information on how to replicate this; I wasn't implying that the current behavior is necessarily correct. Filtering out the player's own messages doesn't sound like something that has any practical purpose; sounds like a bug to me (I don't use chat filter plugin though so idk).
