### ISSUE TITLE
Ground Items bug

### ISSUE THREAD

**Issue by oslokebab** [runelite/runelite#14728]
When I highlight Super restore(4) in ground items plugin it will not shift click drop properly... This is probably an issue with all types of highlited potions.

To reproduce: 
1. highlight a potion 
2. have a lot of potions in your inventory to spam drop
3. hold shift and spam drop all potions in your inventory

Chances are that character will take a sip of the potion instead of dropping it.

**Comment by Nightfirecat** [comment]
The only way this would fail is if the vanilla shift-drop feature didn't work for some reason. I could not reproduce this ingame

**Comment by oslokebab** [comment]
do you also get a chat message when you drop potion?

**Comment by Nightfirecat** [comment]
No. Dropping items doesn't cause a chat message. Do you mean a chat message from a notification firing for a highlighted item appearing on the ground?

**Comment by oslokebab** [comment]
yes

**Comment by oslokebab** [comment]
when i have an item highlighted and chat message appears in red when potion is dropped it causes some problem with spam dropping potions.

**Comment by Nightfirecat** [comment]
Even enabling game message notifications and notifications while focused doesn't cause that behavior for me. My desktop environment has a little bit of lag when notifications are fired (which is a separate issue from RuneLite entirely) but doesn't impact dropping the potions or shift-drop.

**Comment by oslokebab** [comment]
are you dropping the potions fast? it has to be a lot of them too.

**Comment by Nightfirecat** [comment]
Yes, and I'm dropping a full inventory of them. I don't believe this is a RuneLite issue, I'll be honest.

**Comment by oslokebab** [comment]
it is because i tested it on both runelite and steam client

**Comment by oslokebab** [comment]
![ground items](https://user-images.githubusercontent.com/62274373/156850383-d1757b7f-8d9c-4d91-ae2b-cec2d89cdcea.png)

**Comment by oslokebab** [comment]
this were my settings when bug was happening

**Comment by Nightfirecat** [comment]
I think the issue is your computer is stealing focus or lagging when you receive notifications, and that's interfering with shift-dropping, so it wouldn't apply to the vanilla or Steam clients.
