### ISSUE TITLE
Ardy cloak/explorer ring teleport charges

### ISSUE THREAD

**Issue by somedude408** [runelite/runelite#14723]
can there be a counter of teleport charges on these items? i have no way of knowing how many charges are on them unless i actually teleport or like, manually keep track. if this feature already exists in game can someone show me how to see that?

**Comment by AndresConforti** [comment]
Yeah, i would be great to have this feature added to the client.
I mean, people uses the teleports on both items for their farm runs than the alch charges.

**Comment by Trentr9** [comment]
Ardy cloak doesn't have a limit of teleports does it? I thought it was unlimited teleports at any level of the cloak.

**Comment by Hydrox6** [comment]
There is a limit on Ardy Farm teleports with `0/3/5/Unlimited` for each tier respectively
