### ISSUE TITLE
Sire vents counting toward slayer task on leagues

### ISSUE THREAD

**Issue by The1Investigator** [runelite/runelite#14725]
Title as described bug.

Bug likely situational to league worlds, situational to fix or not

**Comment by Nightfirecat** [comment]
Leagues leagues has now ended, so this is no longer applicable. I'm leaving this issue open, however, as any world with an xp multiplier would experience the same issue (ex. DMM worlds) and we should consider that multiplier for checking slayer kills to exclude vent kills.

**Comment by Adam-** [comment]
this was fixed a long time ago in e027955e8a4d8aa3985e6999638d0a8fcdbaee28, but is also fixed by 1f6ae893d732cf3a022fe6d9662cd2a42ff2b217
