### ISSUE TITLE
MacOS Top bar changes from native style to windows-style after logging in

### ISSUE THREAD

**Issue by DalderupMaurice** [runelite/runelite#14721]
**Describe the bug**

**To Reproduce**
1. Clean install of RL on Mac
2. Sign in (have the settings sync)
3. Relaunch RL
4. Top bar with minimize, maximize, close buttons changed from native style to windows-style

**Expected behavior**

RL Client should remain its native top bar

**Environment (please complete the following information):**
 - OS: Apple M1 Max macOS Monterey v12.2.1
 - RuneLite version: Latest
 - Launcher version: Latest

**Comment by Alexsuperfly** [comment]
That behavior is governed by the `enable custom window chrome` option in the `Runelite -> Window Settings` section.  The signed in profile uses an entirely different settings configuration than when signed out, and so the option must just be enabled on it but not in your signed out settings.
