### ISSUE TITLE
MenuEntrySwapper: Toggle Pet Click Options

### ISSUE THREAD

**Issue by Writ3r** [runelite/runelite#14733]
**Is your feature request related to a problem? Please describe.**
It is quite frequent that I'll accidently left or right click on my pet, and thus mess up whatever I'm doing. 
This makes it suboptimal to keep a pet with me despite it being fun to do so. 

**Describe the solution you'd like**
A toggle to force all pet options to the bottom of the right click menu under 'Walk Here', and also have less priority than 'Walk Here' on left clicks as well. 
Or just add a toggle to remove the (Talk-to, and Pick-up) options entirely. 
Just any way to prevent accidental clicks on the pet from interfering in the game is better than the current situation. 

**Describe alternatives you've considered**
Even just making a toggle under the Entity Hider plugin to essentially make your pet act like other people's pets when it comes to clicks (impossible to click them) would be better than the current situation. 

Thanks for your consideration, have a great day!

**Comment by hex-agon** [comment]
This is already available under the game options

**Comment by Writ3r** [comment]
@hex-agon It is?!?! I thought I looked everywhere for it lol. Where is it?

**Comment by hex-agon** [comment]
`Move follower options lower down`

**Comment by Writ3r** [comment]
@hex-agon Gahhh, it's in 'Controls'. Alright, I see it now, thanks. I'll close this out.
