### ISSUE TITLE
Clue Scroll Issue...

### ISSUE THREAD

**Issue by jastone23** [runelite/runelite#1473]
When i look at the clue scroll clue and get Runelites helper on the side it says, travel to the marked out destination. There is no marked out destination :(

**Comment by jastone23** [comment]
@Nightfirecat it's all of them...

**Comment by SomeoneWithAnInternetConnection** [comment]
We don't currently mark your map. We only highlight the tile in the world. If the highlighted tile is missing, or incorrect then #1309 is the place to report it. If you're talking about marking the map, then that'll be solved in the future once we get our map situation sorted.

**Comment by jastone23** [comment]
@SomeoneWithAnInternetConnection ah okay thanks 👍

**Comment by deathbeam** [comment]
Duplicate of #1446
