### ISSUE TITLE
Item Identification - a couple missing potions

### ISSUE THREAD

**Issue by ArashiJoe** [runelite/runelite#14731]
~ Add the new green Goblin Potion to the _Item Identification_ plugin as "**Goblin**"
~ Add the orange Magic Essence to the _Item Identification_ plugin as "**MagEss**"
![Consumables](https://user-images.githubusercontent.com/61663896/156906465-487eeba6-40a3-4f50-bc21-2196d0a54b27.png)
~ Both are quest items and do not necessarily need tags, but both still maintain some usability after their respective quests are finished.

**Comment by Adam-** [comment]
added in #14734
