### ISSUE TITLE
Add toggle for loot tracker to reset between sessions

### ISSUE THREAD

**Issue by trelkins3** [runelite/runelite#14745]
**Is your feature request related to a problem? Please describe.**
1.8.13.1 has overhauled loot tracker to save data between client sessions. Some users may find the old behavior of resetting the loot tracker between sessions desirable; a toggle to allow resets between sessions would effectively accommodate these players.

**Describe the solution you'd like**
A toggle in the loot tracker settings to allow enabling the legacy behavior of clearing the loot tracker log between sessions. Alternatively, a toggle to enable the "new" behavior would work as well.

**Additional context**
I believe there has been some interest for this from players on Twitter; I'm not just suggesting it to be change-averse ;)

**Comment by Adam-** [comment]
Added in 4f8991dc7e22913d001877d77c37342d428f1c05. This doesn't actually reset it, but won't load the loot on startup instead.
