### ISSUE TITLE
RuneLite is the only program that uses Ctrl+Backspace to clear an entire line?? 

### ISSUE THREAD

**Issue by hankshill** [runelite/runelite#14754]
This is in relation to the Chat Commands plugin, but may be better suited for a general RuneLite feature?

**Is your feature request related to a problem? Please describe.**
1. Ctrl+Backspace does not work in the Password box on login. 
2. Additionally, ctrl+backspace does not work as expected for many users. In Microsoft Windows and Linux, the command "ctrl+backspace" will clear the last word by default, not the entire line in any program other than RuneLite as far as I'm aware.

**Describe the solution you'd like**
1. Make ctrl+backspace work in the password box to clear the entire password, or everything up to a "space" in the password
2. Swap the defaults for ctrl+backspace and ctrl+w in the "Chat Commands" plugin. I understand that these can be customized, but the default behavior is quite unintuitive and it took me many months to realize that it was a plugin causing this and not RuneLite itself. Most users will expect Ctrl+Backspace to clear a single word, and not their entire chat box.

**Describe alternatives you've considered**
One alternative I have considered is the following: Once, maybe twice, send a notification to desktop (ignoring notification settings) alerting the player that they can change the behavior of "Ctrl+Backspace" within the Chat Commands plugin. That way people aren't entirely lost when their entire chat box disappears as opposed to the last word they typed.

**Additional context**
I don't know if there's any additional context. I'd like to know why Ctrl+Backspace was chosen as clear chat and Ctrl+W was chosen as clear single word, considering the fact that in every other program Ctrl+Backspace will clear a single word. 
I don't expect a full explanation for this, but it sure would be nice to know why it is this way.

**Comment by Vandager** [comment]
Looking into this.
