### ISSUE TITLE
Clue Scroll Helper

### ISSUE THREAD

**Issue by Ampl-T** [runelite/runelite#1475]
Hi, During my time grinding out some med clues the clue helper wont update for the next clue whether it be one with items and emotes required or a dig clue. If you need more specifics let me know, I'll try answer your questions otherwise I'll go do some more clues to get you the answers.

**Comment by deathbeam** [comment]
There are already plenty of issues open for clues, also megathread for clue problems. Check if your issue is not listed there already, and if not, either update the megathread or open new issues for clues that are not working.
