### ISSUE TITLE
chambers of xeric overlay RSN correct capitalizations please

### ISSUE THREAD

**Issue by Wiserd07** [runelite/runelite#14761]
I took a year break and could've swore that on the cox scouter overlay that the rsn to identify what channel to join used to be correct capitalization to match the persons exact name to distinguish i's and L's etc 

either way could this be added? thanks.

**Comment by Nightfirecat** [comment]
We don't change any capitalization of the cc owner: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/raids/RaidsOverlay.java#L125
