### ISSUE TITLE
Game freezes when travelling by sea to relekka, can't login after also

### ISSUE THREAD

**Issue by king-koda** [runelite/runelite#14768]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Travelling by sea from pirates cove/ waterbirth island causing the game to freeze indefinitely. Can only be fixed by logging into the vanilla client and taking the character out of the location.

**To Reproduce**
1. Go to '...' Waterbirth or Pirates Cove
2. Click on '....' Travel to relekka option
3. See error

**Expected behavior**
Game not to freeze 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 64 bit
 - OpenOSRS 4.20.5
 - Launcher version: 2.20

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by king-koda** [comment]
Invalid how?

**Comment by forsco** [comment]
> Invalid how?

This is not OpenOSRS. You'd best go to their Github
