### ISSUE TITLE
Trade window displays the players name your trading with in green text to signify if it's a friend. 

### ISSUE THREAD

**Issue by Newman1230** [runelite/runelite#14767]
On the trade window where it says "Trading with [player name]" would it be possible to make the player name highlighted in green text to signify that its a friend incase you are trading back a lent item and nobody with a similar name could quickly snag it. I know the runewatch feature shows at bottom of the trade screen in red text if someone is on the watch list. Possibly something like this where in green at bottom it will say "friend" I've seen alot of people on stream and known friends who get name baited and trade over their items to a wrong account with similar name that's posing as their friend. 
 Below is a example of what I mean. The username is highlighted in green instead of the regular color. 
<img width="308" alt="tradelog" src="https://user-images.githubusercontent.com/101942455/159190336-96cc9607-2e29-4c15-97e3-8b27ba07210e.png">

**Comment by Vandager** [comment]
Looking into this.

**Comment by Newman1230** [comment]
> Looking into this.

Thank you
