### ISSUE TITLE
Black screen after loading without plugin bar

### ISSUE THREAD

**Issue by c143** [runelite/runelite#14769]
When i open runeLite with the pluginbar closed, most of the time the client loads, but just shows a black screen. I can even login if I click on the right spot but can't see anything. If the pluginbar isn't collapsed I don't have a problem at all.

Tested it on an older version and on runeLite 1.8.14, launcher 2.4.3 on macOS bigSur 11.6.1

<img width="769" alt="image" src="https://user-images.githubusercontent.com/9988714/159163611-b210ac69-dcbd-4a28-8c1b-116be6e61362.png">

[client.log](https://github.com/runelite/runelite/files/8311271/client.log)
[launcher.log](https://github.com/runelite/runelite/files/8311272/launcher.log)

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
