### ISSUE TITLE
Ground items hidden items resetting to default

### ISSUE THREAD

**Issue by aooie3** [runelite/runelite#14773]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The ground items plugin refills my hidden items with the default hidden items if there are none when I close and reopen runelite.

**To Reproduce**
1. Enable ground items plugin on the configuration sidebar and then open its plugin configuration
2. Delete all the text in the hidden items list field
3. Drop vial/ashes/coins/bucket/bones/jug/seaweed on the ground to see that it displays the overlay, then pick it up again
4. Log out and close runelite and then reopen runelite and log in again
5. Drop the same item on the ground to see there is no overlay
6. Open the ground items plugin configuration again to see the hidden items list field is filled again with "Vial, Ashes, Coins, Bones, Bucket, Jug, Seaweed"

**Expected behavior**
The hidden items list field should remain blank when runelite closed and reopened

**Screenshots**
If you don't understand please ask and I can screenshot something you need

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.14
 - Launcher version: 2.3.0

**Comment by Nightfirecat** [comment]
Duplicate of #8457

**Comment by aooie3** [comment]
Thank you @Nightfirecat for finding that the workaround https://github.com/runelite/runelite/issues/8457#issuecomment-564522544 works for me

**Comment by Tunatroll** [comment]
So... Like... Been four years... You guys ever gonna be able to handle an empty block list?
