### ISSUE TITLE
Runelite settings tooltip hover text appearance duration

### ISSUE THREAD

**Issue by BartVanGrimbergen** [runelite/runelite#14780]
Simple request. The problem I have is that when I'm hovering over a Runelite setting to make the tooltip text appear (see picture below) which I need to read to understand what I'm enable or disabling for example. The text disappears after like 5 seconds, but I'm sometimes still reading the text so I need to re-hover which is anoying. Can the text stay as long as you hover over the setting and have reached the threshold at which the text will appear? 

![image](https://user-images.githubusercontent.com/29555642/159481824-5fb604c2-b4a7-4247-93f0-7bc74d376385.png)

**Comment by Nightfirecat** [comment]
Tooltips now have infinite duration after the client's FlatLAF changes.
