### ISSUE TITLE
Missing quest helper plugin

### ISSUE THREAD

**Issue by jeraziah** [runelite/runelite#14784]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

The quest helper plugin does not appear on pluginhub or on my runelite install

**To Reproduce**
Open runelite

**Expected behavior**
Quest helper exists

**Screenshots**

**Environment (please complete the following information):**
Windows 
RL 1.8.15 - RuneLite version: [e.g 1.4.6]
Launcher 2.1.6

**Additional context**

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
