### ISSUE TITLE
Home/Minigame Teleport Cooldown Timer doesn't appear for Default Animation

### ISSUE THREAD

**Issue by chrisngobanh** [runelite/runelite#14789]
**Describe the bug**
After the most recent OSRS update, the teleport cooldown timer doesn't appear when you use the default teleport animation. This occurs for both minigame and home teleports. I noticed that, at the very end of the animation on the most recent update, your character very briefly stops animating and just stands there before you actually get teleported. I think this might be the reason for the bug (See gif)

![teleport](https://user-images.githubusercontent.com/8410793/159984468-aa1122a3-c021-4bac-bfb1-e888889364e6.gif)

**To Reproduce**
1. Switch your home teleport animation to "Default." by right cicking the home teleport.
2. Do your home teleport
3. After the teleport, you'll notice that the cooldown timer doesn't appear.

Workaround:
1. Switch your home teleport animation to anything other than "Default." by right cicking the home teleport. I use the "Runefest 2014." option.
2. Do your home teleport.
3. After the teleport, your cooldown timer appears.

**Expected behavior**
Cooldown timer should appear after home or minigame teleport.

**Environment (please complete the following information):**
 - OS: Windows and MacOS
 - RuneLite version: Latest (1.8.15.1)

**Comment by Nightfirecat** [comment]
This is caused by a (likely unintended) change on Jagex's side. We're raising it with them to find out more.

**Comment by Adam-** [comment]
I was told this change to the animations was unintentional and they are working on changing it back.

**Comment by chrisngobanh** [comment]
It appears that this issue has been fixed because of this update: https://secure.runescape.com/m=news/easter-2022?oldschool=1

> * Fixed an animation glitch with the Home Teleport.
