### ISSUE TITLE
!lvl kbd please : ) 

### ISSUE THREAD

**Issue by bellisonoroff** [runelite/runelite#14794]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

!lvl works for other hiscore bosses but not kbd, it would be nice if it did : ) thank u for making, maintaining, and improving runelite!

**Comment by Nightfirecat** [comment]
You're confusing `!lvl` with `!kc`. `!lvl` isn't used for looking up kill counts.

**Comment by bellisonoroff** [comment]
> You're confusing `!lvl` with `!kc`. `!lvl` isn't used for looking up kill counts.

nah, !kc shows kill count and !lvl shows hiscore ranks. !lvl bandos or !lvl sarachnis displays your kc and hiscore rank. !lvl kbd doesnt show kbd rankl

**Comment by bellisonoroff** [comment]
I dont think anywhere did i mention looking up kill counts, either. 

"_**!lvl works for other hiscore bosses**_ but not kbd" 
"lvl works for **hiscores**"

**Comment by Nightfirecat** [comment]
`!lvl bandos` does not look up your bandos kc on the hiscores, but `!lvl general graardor` does.

**Comment by Nightfirecat** [comment]
So what you're really asking for is to allow the same abbreviations we use in `!kc` for `!lvl` as well

**Comment by bellisonoroff** [comment]
> So what you're really asking for is to allow the same abbreviations we use in `!kc` for `!lvl` as well

if you are telling me that !lvl king black dragon works, but !lvl kbd doesnt, then... no, not particularly.. I didnt know that !lvl didnt work with abbreviations like !kc does and have no issue taking the extra time to type it out fully. i thought for some reason kbds didnt work : ) 

doing what you said - allowing the same abbreviations would be _nice_ by all means, but much more of a low impact qol than anything. thank you for educating me on the correct usage of the !lvl command and thank you for taking your time to engage with me!

**Comment by bellisonoroff** [comment]
![image](https://user-images.githubusercontent.com/95214548/160668350-c5ef0324-9178-4948-9f14-348e40c8a623.png)

nah !lvl doesnt work for king black dragon

**Comment by Nightfirecat** [comment]
Added in bdf556f4bd0ba46dd866e21ff0b1fff7e68ddfe8
