### ISSUE TITLE
Add Shayzien agility courses to KC chat command

### ISSUE THREAD

**Issue by invalidCards** [runelite/runelite#14796]
**Is your feature request related to a problem? Please describe.**
Not really

**Describe the solution you'd like**
Add lookups for `!kc` chat command for the Shayzien Basic and Shayzien Advanced agility courses

**Describe alternatives you've considered**
Typing it out myself like some kind of noob

**Additional context**
Even the werewolf course has a KC command so why not this one :)

**Comment by LlemonDuck** [comment]
Some short names for the shayzien courses were added in ce0ec53:

![Uploading image.png…]()
