### ISSUE TITLE
"Item charges" plugin not tracking loss of charge for Binding necklace when Hat of the eye is equipped. Possibly any piece of outfit, only have the hat and it caused this issue.

### ISSUE THREAD

**Issue by KazHarper** [runelite/runelite#14793]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by realsies** [comment]
it does seem to happen with any piece of the outfit, i have the leg piece

on my end it also erroneously shows that it has 17 charges when a necklace breaks, as well as saying in chat that bindng the runes was only partially successful despite getting the full amount

(the latter could be a jagex issue tho, not sure)

**Comment by Nightfirecat** [comment]
If you have the game chat filter off, what chat message do you get when you bind runes with part of the outfit equipped? I assume it is changed since GotR's release, or changed when you have the outfit equipped. The plugin expects it to look like:

> You bind the temple's power into lava runes.

**Comment by call-me-maple** [comment]
When wearing pieces of the outfit the chat message changes to:

> You partially succeed to bind the temple's power into steam runes.

This is weird because it's the message you get when not using a binding necklace. But the charge will still be used and the correct amount of runes will be given as well. I was getting the partial success message with any combination of the set pieces.

**Comment by Nightfirecat** [comment]
That sounds like an ingame bug then.

**Comment by majiru** [comment]
I believe this has been worked around now with this commit https://github.com/runelite/runelite/commit/a350b5a57b688411a8f953ad82c55a0fac412c99
