### ISSUE TITLE
Make discord plugin not show RuneLite if in menu. 

### ISSUE THREAD

**Issue by madden044** [runelite/runelite#14797]
**Is your feature request related to a problem? Please describe.**
It's not necessarily a problem, but it would be nice if the discord plugin would not show you playing Runelite if you are on the main menu not logged in. 

**Describe the solution you'd like**
Enable the plugin to not send discord info if you are not logged in.

**Describe alternatives you've considered**
None at the moment.

**Additional context**
I saw a few fixes in pull requests from around 2020, I don't think they were ever merged with base Runelite, but I might be dumb.

**Comment by Nightfirecat** [comment]
Is unchecking the "Main Menu" option of the plugin not what you're asking for already?
