### ISSUE TITLE
SUGGESTION: Player Status

### ISSUE THREAD

**Issue by ronplaysgames** [runelite/runelite#14803]
**Is your feature request related to a problem? Please describe.**
It's always really tedious having to constantly message friends to organize group activities. 

**Describe the solution you'd like**
Have the ability to hover over a friend's username on the friends list and see a status that they've set. Much like the ones you'd find on discord. E.g. "LFG (looking for group) ToB / Nex. Could be used for a range of things. A way to advertise yourself and your current interests. It would promote socializing between players more.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Nightfirecat** [comment]
This would require some sort of server data storage for arbitrary data, we're not interested in hosting such a service. We recommend using Discord or some external service for this.
