### ISSUE TITLE
Idle notifier doesn't send system notification on Kubuntu 20.04

### ISSUE THREAD

**Issue by mstrnisko** [runelite/runelite#14809]
**Describe the bug**
Runelite is not sending native Kubuntu notifications

**To Reproduce**
1. Enable Idle notifier
2. Set HP threshold to X
3. Go to combat and wait for HP to fall under X
4. Screen flashes, so the notifier works, but there's no system notification

**Expected behavior**
When the HP falls under the specified threshold, the system should get a notification about it.

**Environment (please complete the following information):**
 - OS: Kubuntu 20.04
 - RuneLite version: 1.8.15.1
 - Launcher version: 2.4.2

**Comment by Nightfirecat** [comment]
Do you have `libnotify4` installed?

**Comment by mstrnisko** [comment]
> Do you have `libnotify4` installed?

Yes

**Comment by Nightfirecat** [comment]
Does running `notify-send test` create a system notification?

**Comment by Nightfirecat** [comment]
Also, which launcher do you have? (All-platform? AppImage? snap? flatpak? etc.)

**Comment by mstrnisko** [comment]
> Does running `notify-send test` create a system notification?

Is the `libnotify4` the correct package to have the `notify-send` provided? Because I don't have the `notify-send` command available to my system
```bash
matrez@matrez:~$ sudo apt install libnotify4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libnotify4 is already the newest version (0.7.9-1ubuntu2).
libnotify4 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 231 not upgraded.
matrez@matrez:~$ notify-send test

Command 'notify-send' not found, but can be installed with:

sudo apt install libnotify-bin
```

> Also, which launcher do you have? (All-platform? AppImage? snap? flatpak? etc.)

AppImage, directly downloaded from the runelite website.

**Comment by Nightfirecat** [comment]
I've added https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#notifications-dont-work-on-linux
