### ISSUE TITLE
Missing proper quaternion rotation API

### ISSUE THREAD

**Issue by Billybishop** [runelite/runelite#14804]
Add API to perform quaternion rotations on Models...

So far all I can see is a way to perform single axis rotations from the model level without defining a custom set of vertices. 

Either document how draw() should be used or add a proper quaternion rotation method.

Affects:
Model, ModelDefinition, ModelData

**Comment by Nightfirecat** [comment]
I don't think this is needed and you're misunderstanding how to do what you're trying to achieve. The `#development` channel [of our Discord server](https://runelite.net/discord) would be a better place to ask about this.
