### ISSUE TITLE
low detail mode sometimes has no floor

### ISSUE THREAD

**Issue by tysontro** [runelite/runelite#1481]
Cant be seen when roofs are disabled. But
some rooftop agility courses have graphical glitches. 

![glitch](https://user-images.githubusercontent.com/38305008/38734229-59fa8f50-3f57-11e8-8a95-5c35da90f5d8.PNG)

**Comment by Adam-** [comment]
This is not specific to agility courses and is due to low detail mode.

**Comment by iVilux** [comment]
As I understand low detail mode was used before 2007? And rooftops are new so they were only implemented to high detail (default) mode. [https://i.imgur.com/kvKbZSv.png](https://i.imgur.com/kvKbZSv.png)

**Comment by SomeZer0** [comment]
Also happens in wintertodt and catacombs of kourend.

**Comment by ShaunDreclin** [comment]
I don't think this counts as a bug, or at least it's not one we can fix. Afaik the rooftops use ground decorations, which is what low detail mode hides.

**Comment by Adam-** [comment]
I think that this is probably fixable to an extent.

**Comment by ShaunDreclin** [comment]
Oh :o if it is that'd be cool then~

**Comment by Hubcapp** [comment]
:dancer:

**Comment by BramManuel** [comment]
I know this issue is closed, but the issue still occurs, and if you have a drop on the ground you won't be able to see it and you will not be able to pick it up. Turning off low detail fixed it. had to learn this the hard way....

**Comment by Adam-** [comment]
This issue isn't closed. It just has no resolution.

**Comment by Adam-** [comment]
I've worked around this internally by detecting the tiles which are removed in low detail mode and loading them in anyway.
