### ISSUE TITLE
[Menu entry swapper] Separate Quick Pass/Open/Start/Travel

### ISSUE THREAD

**Issue by nathanmobbs** [runelite/runelite#14810]
With the new Guardians of the Rift minigame update on 30 March, they added a quick-pass option on the gate. Unfortunately, many people spam-click to enter and immediately get sent out again using this plugin's "quick pass" menu entry swap without people realising. It's also possible to quick-pass and leave the game early by mistake, which is very frustrating and common.

The issue is that we can turn this off, but it also turns off other quick Open/Start/Travel options. So while this works, it isn't ideal for other quick options.

Can we separate the quick options into multiple checkboxes or have an override option for the gate at Guardians of the Rift?

**Comment by Hydrox6** [comment]
This can now be done with the changes in 92aac53f4273e7944c3da767637e083847c03808
