### ISSUE TITLE
[Menu Entry Swapper] Suggestion to add "Group Previous" as a UI swap option for shift+click on home teleport

### ISSUE THREAD

**Issue by ThickPeep** [runelite/runelite#14813]
Would it be possible to have the menu entry swapper have a drop down option for home teleport which would let you choose a different shift+left click option instead of only "outside"? I know this is a bit niche since it only applies to group Irons, but it is a feature that group irons can make a lot of use of, especially when bossing.

**Comment by EliasLahham** [comment]
Looking into
