### ISSUE TITLE
Bank plugin ability to search for quantities

### ISSUE THREAD

**Issue by raniem** [runelite/runelite#14814]
**Is your feature request related to a problem? Please describe.**
Currently Bank plugin supports searching for items with user defined values for GE or HA prices. In a messy bank there is no way to see only placeholders (items with stacks of 0 in bank) to release unneeded ones (releasing all could potentially mess the bank even further). 

**Describe the solution you'd like**
I would like a feature in which user could search for items in stacks of defined size. E.g. `q = 0`, `q > 1` and so on with same supported patterns as `ge` and `ha` do. 

**Describe alternatives you've considered**
None other than the Vanilla `Release placeholders`-button. 

**Additional context**
This is just something I figured to maybe be useful for some players as I watched my friends bank fill with some random placeholders here and there, but releasing all would have made their bank even messier than it already is.

**Comment by EliasLahham** [comment]
Currently in progress, will update this issue with a PR sometime tonight

**Comment by pwatts6060** [comment]
Nice, someone in my clan asked for this today as as well. Mainly for find placeholders with q=0

**Comment by raniem** [comment]
Hey! Are there any updates on this?
