### ISSUE TITLE
Randomly can't type after unlocking computer with runelite running in background

### ISSUE THREAD

**Issue by dpedu** [runelite/runelite#14817]
**Describe the bug**
Sometimes, after I unlock my computer, keyboard input to the runelite client behaves oddly:

* I can type on the login screen to enter my username & password to log into the game
* I can type in the runelite ui (e.g. the text field in the highscore lookup in the sidebar works)
* I **cannot** type into the in-game chatbox nor input fields (e.g. the bank withdraw-X numerical input)
* I can press tab and receive the message saying that I received no recent PMs to which I can reply (which is correct)

**To Reproduce**
1. Run runelite on macOs Big Sur 11.6.5
2. Leave it running for several days (I literally only close it when the game update forces me to)
3. Put the computer through countless lock/unlock sleep/wake cycles
4. Observe the behavior above, but only sometimes

**Expected behavior**
Keyboard input always works

**Screenshots**
N/a

**Environment (please complete the following information):**
 - OS: macOs Big Sur 11.6.5 (arm, using x86 runelite)
 - RuneLite version: 2.1.5
 - Launcher version: ? Not sure how to find this

**Additional context**
I viewed client.log which had many repeated messages but they all looked like:

```
2022-03-31 04:53:55 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - non-echo reply
2022-03-31 09:26:56 [Client] INFO  c.s.ShootingStarTrackingPlugin - No match found
2022-03-31 20:29:54 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - sequence number mismatch (-27638 != 17)
```

I recall first seeing this issue about two months ago, but I am not so confident of this date. I've had the particular computer for longer.

**Comment by IComplainInComments** [comment]
> **Describe the bug** Sometimes, after I unlock my computer, keyboard input to the runelite client behaves oddly:
> 
>     * I can type on the login screen to enter my username & password to log into the game
> 
>     * I can type in the runelite ui (e.g. the text field in the highscore lookup in the sidebar works)
> 
>     * I **cannot** type into the in-game chatbox nor input fields (e.g. the bank withdraw-X numerical input)
> 
>     * I can press tab and receive the message saying that I received no recent PMs to which I can reply (which is correct)
> 
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Run runelite on macOs Big Sur 11.6.5
> 
>     2. Leave it running for several days (I literally only close it when the game update forces me to)
> 
>     3. Put the computer through countless lock/unlock sleep/wake cycles
> 
>     4. Observe the behavior above, but only sometimes
> 
> 
> **Expected behavior** Keyboard input always works
> 
> **Screenshots** N/a
> 
> **Environment (please complete the following information):**
> 
>     * OS: macOs Big Sur 11.6.5 (arm, using x86 runelite)
> 
>     * RuneLite version: 2.1.5
> 
>     * Launcher version: ? Not sure how to find this
> 
> 
> **Additional context** I viewed client.log which had many repeated messages but they all looked like:
> 
> ```
> 2022-03-31 04:53:55 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - non-echo reply
> 2022-03-31 09:26:56 [Client] INFO  c.s.ShootingStarTrackingPlugin - No match found
> 2022-03-31 20:29:54 [pool-6-thread-1] WARN  n.r.c.plugins.worldhopper.ping.Ping - sequence number mismatch (-27638 != 17)
> ```
> 
> I recall first seeing this issue about two months ago, but I am not so confident of this date. I've had the particular computer for longer.

This might actually be a Rosetta bug, have you tried using the native version? It is available on the runelite main site.

**Comment by dpedu** [comment]
Thanks, I wasn't aware there was an ARM copy of Runelite available - I'll go ahead and install that and report back later.

I was indeed using the intel copy, though I use a decent amount of other software that requires Rosetta and hadn't experienced this.

**Comment by Thomas-Scott** [comment]
I suspect this might be broader than just unlocking or an ARM bug as I experience this issue as well on Intel Mac mini (2018).  With RuneLite version 1.8.30, Launcher 2.4.3 (and have for several previous versions). I find switching window focus *multiple times between different applications* can sometimes restore keyboard functionality. 

Some additional notes: I began to notice this after enabling the Mac OS accessibility features (mouse keys) and notice it far more often during periods when I'm making use of that feature (ardy knights, etc). @dpedu do you perhaps also use mouse keys and/or have a second language input attached to your keyboard?

**Comment by dpedu** [comment]
@Thomas-Scott I don't use mouse keys or have a second language input, though I use some other macOS accessibility features (zoom, text to speech).

**Comment by dpedu** [comment]
I was able to partially reproduce this just now - the client was ignoring keyboard input just as before, but after locking and unlocking my computer it was normal again.

**Comment by dpedu** [comment]
I haven't had this happen in more than a year, so I'm going to close it.
