### ISSUE TITLE
Two monitor set up, new 1440p monitor not as clear or crisp as the 1080pm monitor.

### ISSUE THREAD

**Issue by xxznightmare** [runelite/runelite#14818]
I have tried playing with the stretched mode plugin that did not make any impact and I've changed the high dpi setting to system in the properties, this also had no impact, any advice?

![1440](https://user-images.githubusercontent.com/102827112/161348096-96cf1fa9-571d-4029-9353-95659b0577ad.png)
![1080](https://user-images.githubusercontent.com/102827112/161348101-0b439633-efdd-4103-ae57-940dbb6e94c6.png)

**Comment by Nightfirecat** [comment]
I don't understand the problem. Both of those screenshots look perfectly clear to me.
