### ISSUE TITLE
Runecrafting plugin: Missing degraded Colossal pouch

### ISSUE THREAD

**Issue by BegOsrs** [runelite/runelite#14822]
**Is your feature request related to a problem? Please describe.**
Runecrafting plugin is missing the new Colossal pouch [in this set](https://github.com/runelite/runelite/blob/43a7a60c7b220edd3d2e49239f59a677e275eb7a/runelite-client/src/main/java/net/runelite/client/plugins/runecraft/RunecraftPlugin.java#L69).

**Describe the solution you'd like.**
Add the degraded colossal pouch id, which is one of:
- ItemID.COLOSSAL_POUCH
- ItemID.COLOSSAL_POUCH_26786
-  ItemID.COLOSSAL_POUCH_26906

**Comment by Adam-** [comment]
added in 1550fae2eda8b334070e505830296b0e89d30e55
