### ISSUE TITLE
"Idle Interaction Notification" not working at Kraken boss

### ISSUE THREAD

**Issue by YvesW** [runelite/runelite#14849]
This is a duplicate of [#11943](https://github.com/runelite/runelite/issues/11943), which is closed, but the problem hasn't been resolved. Discussed it in the discord and added this ticket.
 
**Describe the bug**
Just as in #11943, I don't get a notifcation after I'm out of combat at kraken. Private instance using fishing explosives, tried restarting runelite.

![image](https://user-images.githubusercontent.com/7929021/162791993-0d2d3c49-1581-48d7-bc74-ce697d7ae8d9.png)
![image](https://user-images.githubusercontent.com/7929021/162792014-8ba539f0-0021-44af-bfc5-f10bdb217c81.png)

**To Reproduce**
1. Go to kraken. I've only tested private instances, but public probs also works.
2. Use a fishing explosive on the pool and kill kraken.
3. No notification when out of combat. The tentacles are probably doing something funky. Low hp and high value loot notifications still work as expected.

**Expected behavior**
Receive a notification after kraken or its tentacles have died/stopped attacking.

**Environment (please complete the following information):**
 - OS: W10
 - RuneLite version: 1.8.16
 - Launcher version: "Unknown". Assume it's the latest since I reinstalled and restarted RL.

**Additional context**
Github doesn't like my client.log, so I've uploaded it to [zippyshare](https://www66.zippyshare.com/v/sEtaO8Xl/file.html
).

**Comment by fuhsaz** [comment]
I can confirm that idle notifications do not work in the public Kraken room either.

**Comment by YvesW** [comment]
Fixed by #16017

**Comment by Nightfirecat** [comment]
#16017 is not merged yet, please do not close this issue.

**Comment by Nightfirecat** [comment]
Fixed in 82fe3f371f9cf3b2a66c7cd022b7daec627613c3
