### ISSUE TITLE
Clue Scroll Plugin - Add a filter view in bank to show Uri's emote clue items and in GE

### ISSUE THREAD

**Issue by pwatts6060** [runelite/runelite#14848]
**Is your feature request related to a problem? Please describe.**
It's slow to withdraw/buy clue emote items when you have to search for each one.

**Describe the solution you'd like**
A button appears in the top right of the bank with a small clue icon, you click the icon and it filters the bank view to just show the emote clue items you need for your current step.
Optional extra: Same for grand exchange when you have search option when buying items

This feature is present in the quest helper plugin for quest items needed for the current quest step I believe.

**Additional context**
![image](https://user-images.githubusercontent.com/30028569/162631869-378f308c-bf47-40d3-a1dd-9aa40cb6bc7d.png)
![image](https://user-images.githubusercontent.com/30028569/162631899-9ab3d5b2-6716-4ddd-9d49-eb98289fe5a7.png)

**Comment by Hydrox6** [comment]
The bank tag `clue` already exists to search out the items needed for the current clue step. Add it as a bank tag tab, or search for `tag:clue`

**Comment by larsvansoest** [comment]
Nonetheless, I see the added value of having a single button to do all the searching for you. I will add it to the feature request list of the emote clue items plugin.
