### ISSUE TITLE
Penance queen kills and Gambles under Soul wars zeal on hiscores

### ISSUE THREAD

**Issue by WelshRepo** [runelite/runelite#14859]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

No, but it would make the plugin great and with the addition of GOTR, even it out.

**Describe the solution you'd like**

Penance queen or barb assault icon underneath the soul wars zeal icon that displays a players queen kills/gambles

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

I am trying to implement this myself, but I am unfamiliar with the codebase and I do not know how to pull the scores from jagex. It seems like it would be a pretty easy addition. If anyone can point me in the right direction I am all ears

**Comment by Adam-** [comment]
If the data isn't available on the hiscores, we can't add it to the hiscore panel.

**Comment by WelshRepo** [comment]
I see. I will petition jagex to track it. Thanks for the reply
