### ISSUE TITLE
Path Tile counter

### ISSUE THREAD

**Issue by ForTimeBeing** [runelite/runelite#14851]
Watching swamp man I could see it being useful for all the new tileman modes... Eg: You select 2 separate tiles, itll configure the optimal route between the two and count the tiles so you know how many tiles you need before unlocked. Easier than individually counting

**Comment by Skretzo** [comment]
This is available in the [Shortest Path](https://runelite.net/plugin-hub/show/shortest-path) plugin (both the optimal path and the number of tiles)
