### ISSUE TITLE
Client: Rounded corners

### ISSUE THREAD

**Issue by kstalnacke** [runelite/runelite#14854]
Give users an option to enable rounded corners for the Runelite client. 

Since Windows 11 offers new styling to most other apps, I believe it would be appropriate to give users this option. The difference in border radius for win 11 users is quite jarring as of now.

Either give users an option within the client, or perhaps try to allow Windows to alter the border-radius. Alternatively implement a check within Runelite for OS.

**Comment by Nightfirecat** [comment]
Do you have custom chrome enabled or disabled?
