### ISSUE TITLE
Kourend Library Plugin - Request to add tracking of Dark Manuscript in the side bar

### ISSUE THREAD

**Issue by pwatts6060** [runelite/runelite#14867]
**Is your feature request related to a problem? Please describe.**
It's easy to forget where the Dark manuscript is located after talking to Biblia for the location.

**Describe the solution you'd like**
The side panel with the book positions can have a slot for the dark manuscript and can update after you talk to Biblia.

If this is ok, I can look into adding the feature myself

**Comment by Hydrox6** [comment]
Dark Manuscripts have 1/2 spots out of 20 active ones which will actually have the manuscript in it, which changes after getting a manuscript. Current potential locations are already shown on the overlay anyway.

It's much more efficient to just do normal books and ignore manuscripts entirely; they're a lot of extra effort for very little gain.

**Comment by Felanbird** [comment]
Dark Manuscripts were removed from the game in the `January 10 2024` update, so I'm going to go ahead and close this
