### ISSUE TITLE
Item Stats only show up in bank

### ISSUE THREAD

**Issue by immaZebrah** [runelite/runelite#14878]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Stats of items don't show up in inventory after the update this morning (4/20/22) i.e. food/prayer healing (which also causes the hp and prayer bar not to show their potential for healing/restoring), potion boosts, armour stat changes. They do however show up if you hover over the items in the bank.

**To Reproduce**

1. Hover over item
2. see no stats

**Expected behavior**
Plugin should show stats of items in inventory.

**Screenshots**
https://i.imgur.com/cJxB7BX.png
https://i.imgur.com/lqV8Ddu.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.8.18
 - Launcher version: 1.6.0

**Additional context**
Client logs: https://pastebin.com/sZXTA2vY
Launcher logs: https://pastebin.com/tZGnMhmu

**Comment by Bram91** [comment]
Restart your client.

**Comment by Adam-** [comment]
This is fixed in 1.8.18.1
