### ISSUE TITLE
aerial fishing + npc indicators (show respawn timer)

### ISSUE THREAD

**Issue by ajdavis25** [runelite/runelite#14875]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

when aerial fishing with "show respawn timer" turned on in npc indicators it gets all wild and crazy in the water
**Describe the bug**

**To Reproduce**
1. Go to 'npc indicators'
2. turn on 'show respawn timer' at the very bottom
3. get bird from arly
4. wait
5. see error(s)

a bajillion timers
**Expected behavior**

**Screenshots**

**Environment (please complete
![Screen Shot 2022-04-17 at 8 05 11 AM](https://user-images.githubusercontent.com/98492932/163716231-8160d65c-7c98-42c7-87ce-2cf7e66685a8.png)
 the following information):**
 - OS: [macOS monterey]
 - RuneLite version: [e.g 1.8.17]
 - Launcher version: [e.g 2.2.0]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Adam-** [comment]
This isn't RuneLite
