### ISSUE TITLE
117's HD Plugin with Night Time Feature 

### ISSUE THREAD

**Issue by DoctorArden** [runelite/runelite#14874]
This feature would allow users to enable a night time feature for all of Gielinor that would turn on either manually by the user or automatically depending on the users time zone. (Similar to WoW)

I think it would be super cool to see iconic areas such as Varrock, Falador, etc. and what they would look like at night lit by the moon and fire.

**Comment by Nightfirecat** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
