### ISSUE TITLE
Guardians of the rift !kc stopped updating

### ISSUE THREAD

**Issue by Lemonjuic33** [runelite/runelite#14877]
**Describe the bug**
3 days ago my !kc gotr (guardians of the rift) killcount in the chatbox stopped updating, it's stuck at 201 no matter what i do.
please see the screenshot i've attached

it's not really game breaking, but it would mean the world to me if you could help me out here,

Kind regards

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: [1.8.17]
 - Launcher version: ?

![Screenshot_3](https://user-images.githubusercontent.com/104032765/164087470-5824817c-5f09-47e1-8fd9-53a8abc1f219.png)

**Comment by Nightfirecat** [comment]
This should already be fixed in 9bd36db0c9f0e42adaab9a3b546adcdc8a72cc0f. Getting any further completions will update your saved kill count.
