### ISSUE TITLE
Show marked tiles & label on Worldmap as well

### ISSUE THREAD

**Issue by Mrcubix** [runelite/runelite#14872]
**Is your feature request related to a problem? Please describe.**

Showing marked tiles on the minimap is nice and all but the core feature in itself is obviously half baked.

Map Waypoint is gone from the Plugin Hub from what i've seen and a dead PR for something similar solution hasn't moved in 3 years.
I need a way to mark a location for my farm runs as i don't always remember where all the patches are and i also change route depending on the run i'm doing (Herb / jute Run OR Complete farming run)

**Describe the solution you'd like**

- We need a toggle to show marked tiles on the Worldmap,
- We need a toggle to display or not a tile label.

**Comment by Hydrox6** [comment]
Showing marked tiles on the world map would not solve your problem. If you struggle to remember where each farming patch is, the world map already has an icon at each of them; putting a marker there would not bypass having to look around the map for said patch in the first place. Allowing the text on those tiles would also not change anything, as the text would either be too small to notice, or overpower anything around it and be annoying to the vast majority of users.

We already have a feature to help with remembering your farm run: the `Notes` plugin. Write whatever you want in there, then bring it up if you need to remember how you tend to get to specific places. If your notes are already in use for something else, use an external note-taking app (every operating system has one built in).

As for marked tiles on the minimap being "half-baked", they're really not if you look at why the plugin exists. The plugin allows you to remember very specific locations, either for clicking or standing purposes. I have markers to help me remember exact tiles to stand in the Hydra fight; many players benefit from marking where to click in the Inferno and both Raids, as position matters a lot in those places; and for a non bossfight application, I have markers around the Xeric's Glade teleport spot so I can easily remember which direction each Mahogany Homes customer is, taking advantage of putting text on the markers. All of these uses are relating to clicking specific areas, and having them on the minimap is an extension of that, as you can click the minimap. This allows the player to more precisely position themselves without having to click in the scene. As you cannot path the world map, having the markers there for specific spots does not help like it does in the scene or on the minimap.

Maybe all this would be fine, except for the small issue of the world map being so incredibly weird to work with. The overworld map is fine, but every other map does not map as expected, with specific chunks and areas being moved around weirdly, and often planes being displayed side by side. As such, getting markers to display on the world map is not only something with very low impact, it has a very high "cost", along with likely requiring internal changes to get it to work in a way that can't be considered "half-baked".

The only feature I can think of that can *only* be solved with world map markers would be for pixel art, which is a pretty meh reason (as cool as it would be). If there are any other uses that can only be solved with world map markers, then it would be interesting to hear them. Alternatively, if another useful feature would want to accurately display worldpoints on the world map, it might make something like this easier to implement; I still think it would not be a worthwhile feature as outlined above, but it's always interesting to see how users use things in weird ways.

You may also be interested in the `Shortest Path` hub plugin, it might do something similar to the now defunct `Map Waypoints`

**Comment by Mrcubix** [comment]
1. it would help me in showing routes using another plugin of my own conception

2. Since Connection to a Runelite account in the client in bugged right now, Note aren't synced between machine + you obviously cannot visualize text on a map instantly.

3. that's one use, but i'm not complaining about that, you have tiles marked on the minimap but not the world map, at least complete the core feature.

4. It doesn't cost as much as you make it to be, i know that for sure from looking into it.

5. see first point.

6. Shortest path probably doesn't take into account teleports of different nature + nothing would allow me to change the destination when the last one is reached, unless i modify it myself.

With that said, what i understood is that nobody want to put the time in fixing the issues plaguing the client and making it flexible.
As for the feature i requested, i guess i'll do it myself. 
Bye.
