### ISSUE TITLE
Item pickup not being sorted by value anymore

### ISSUE THREAD

**Issue by joetimlin** [runelite/runelite#14884]
Noticed today while doing slayer that item pickup is no longer functioning the same, as I've had many low value items stacked on top of high value ones while left clicking.

**Comment by Hydrox6** [comment]
afaik, the only time RuneLite changes this order is with `Ground Items`'s `Deprioritize menu hidden items`, and that's specifically for stuff hidden with ground items. Otherwise this is something Jagex controls.

**Comment by Nightfirecat** [comment]
Per hydrox's comment, this is expected behavior. #14946 is open for discussion of `Deprioritize menu hidden items` behavior for items not explicitly hidden.

**Comment by CreativeTechGuy** [comment]
@Enriath is this something that would be against Jagex' rules to sort? I have only seen the RuneLite team mention in various threads that it isn't sorted, but can it be?
