### ISSUE TITLE
Linux appimage crash: error_game_js5connect

### ISSUE THREAD

**Issue by jayveedee** [runelite/runelite#14889]
A bit odd. I usually run the appimage from my USB drive and it works great, no problem. But today I forgot the drive and just downloaded the appimage again, when I tried to run it this time it crashed with the message: error_game_js5connect
I've looked through the logs and there are a couple of NullPointerException as well as SocketTimeoutException

My system is the following:
![image](https://user-images.githubusercontent.com/24821250/164894704-bf10147b-de16-4906-a805-c475e7bc5228.png)

A couple of screenshots of the log
![image](https://user-images.githubusercontent.com/24821250/164894520-6944c29e-8a0e-4e04-98bc-342e718ea595.png)
![image](https://user-images.githubusercontent.com/24821250/164894563-2700e821-2bdd-4f12-ba50-715a8787cb26.png)

**Comment by Adam-** [comment]
All of these errors are from post-startup, so they wouldn't have prevented the client from launching. Probably you have no internet connectivity if you are getting any sort of js5 error.

**Comment by jayveedee** [comment]
> 

I wrote this post right after I got the errors on the same machine. I also restarted the client 2 times before coming here.

**Comment by jayveedee** [comment]
Works again now. Probably was a connectivity issue, although my PC had internet at the time
