### ISSUE TITLE
buggy shift-wthdraw

### ISSUE THREAD

**Issue by butterscotchbonnet** [runelite/runelite#14887]
**Describe the bug**
The shift-withdraw option is being applied when it shouldn't

**To Reproduce**
- Turn on MES > item swaps > bank with shift held > withdraw all
- Set vanilla withdraw option in bank to 1
- Quickly withdraw an item without shift held then a different item with shift held

**Expected behavior**
- Withdraw 1 of the first item and all of the 2nd item

**Environment (please complete the following information):**
- OS: Windows 10 Pro
 - RuneLite version: 1.8.18.2
 - Launcher version: 2.1.7

**Additional context**

https://user-images.githubusercontent.com/88224718/164884638-d9cfaaea-0c71-45e3-9a3f-a8dac26e1bc8.mp4

https://user-images.githubusercontent.com/88224718/164884640-c20049b6-507c-4d97-8c1c-616ecb86d933.mp4

https://user-images.githubusercontent.com/88224718/164884644-d043a8ef-8c7a-4439-830c-2068f5e25329.mp4

**Comment by Nightfirecat** [comment]
This looks like it's working as intended. In each of the attached videos you're hitting shift before you finish clicking on the steel bars.

**Comment by butterscotchbonnet** [comment]
Thanks, I think it's probably a side effect of the inventory rework that happened a few weeks before this post was made.
