### ISSUE TITLE
Client crashes with "Unable to verify jar entry" on OpenJDK 18

### ISSUE THREAD

**Issue by apsun** [runelite/runelite#14891]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

When running the game with OpenJDK 18, the client crashes during loading with the following error:

```
2022-04-23 15:22:56 [Preloader] ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
net.runelite.client.util.VerificationException: Unable to verify jar entry: v.class
	at net.runelite.client.rs.ClientLoader.verifyJarEntry(ClientLoader.java:620)
	at net.runelite.client.rs.ClientLoader.verifyWholeJar(ClientLoader.java:628)
	at net.runelite.client.rs.ClientLoader.updateVanilla(ClientLoader.java:414)
	at net.runelite.client.rs.ClientLoader.doLoad(ClientLoader.java:145)
	at net.runelite.client.rs.ClientLoader.get(ClientLoader.java:112)
	at net.runelite.client.RuneLite.lambda$main$1(RuneLite.java:236)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I double checked and the cache file looks intact (compared it with another machine where it works fine, checksum matches). For posterity:

```
$ sha256sum vanilla.cache 
cc7bb0fc33f3541eba45eb3b46fd31b45cd469fbe5f6c0098a7026cb2dbd4dbe  vanilla.cache
```

From running the client in a debugger, it looks like the problem is that [this line](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/rs/ClientLoader.java#L611) is returning `null`. Testing on OpenJDK 11 and 17 work fine, so this seems to be something specific to OpenJDK 18.

As a workaround, adding `-Drunelite.updateVanilla=false` to the client arguments seems to work (as it bypasses the crashing codepath), as does forcing the client to run under an older JRE version (on Arch, `sudo archlinux-java set java-11-openjdk`).

**To Reproduce**
1. Launch the game with OpenJDK 18 (either via launcher or running it directly)
2. Crash dialog appears

**Expected behavior**
Game does not crash.

**Screenshots**
![Screenshot_2022-04-23_15-33-41](https://user-images.githubusercontent.com/14020276/164948174-5310686b-10d0-44a7-b258-246ce6bbadf0.png)

**Environment (please complete the following information):**
 - OS: Arch Linux (btw)
 - RuneLite version: 1.8.18.2
 - Launcher version: 2.4.2

**Additional context**

[client.log](https://github.com/runelite/runelite/files/8548726/client.log)

**Comment by abextm** [comment]
You will need to `archlinux-java set java-17-openjdk` for the next few weeks. Jagex signed this weeks release with SHA1 instead of SHA256, which is rejected by java >= 18.
