### ISSUE TITLE
Implings Plugin Request - Add impling world to notification 

### ISSUE THREAD

**Issue by Smiteyou2** [runelite/runelite#14899]
Currently the notification for the impling plugin is "(impling type) is in the area" is it possible to change this to also include the world it is on? Would be a little quality of life improvement for scouting on multiple accounts.

**Comment by Smiteyou2** [comment]
Thats awesome! Is there a way for me to add this to my runelite?

**Comment by Adam-** [comment]
The notification should already include the rsn of the account it is found on... is that not enough distinction?

**Comment by Smiteyou2** [comment]
The notification only says "Nature impling is in the area" when its pulled in with a webhook. If it includes the name it doesnt show on the webhook. The world would be better because it would tell me exactly where it is with just looking at the notificaiton if my buddy is hopping and looking.

**Comment by Adam-** [comment]
Webhook? There is no webhook

**Comment by Smiteyou2** [comment]
In the plugin hub there is a plugin called Discord Notifier that lets you pull in notifications into a discord channel using a webhook.

**Comment by Adam-** [comment]
The tray notifications which *I* send set the notification title to `RuneLite - <player name>`. If your plugin isn't including the player name that sounds like an issue with it.

**Comment by Smiteyou2** [comment]
hmm maybe the table tray notification does include it (I've disabled that) but the webhook doesnt. I copied and pasted the exact message that comes through the webhook. I was thinking that if the notificaiton included the world it would be easy to locate.

**Comment by Adam-** [comment]
Try notifications also usually (system dependent, but, on Windows at least) will flash in the tray too which makes it easy to identify which client it is. I think this combined with the player name being in the title should be more than sufficient. 

Maybe ask the plugin author to include the player name in the notification title, that seems like an oversight.

**Comment by Smiteyou2** [comment]
Yeah, I just dont have tray notifications on because they get in the way of the inventory. Is LucasChilders the plugin author?

**Comment by Adam-** [comment]
No, I don't know which one you have installed there are a few - check https://runelite.net/plugin-hub
