### ISSUE TITLE
Jewelry Enchanting

### ISSUE THREAD

**Issue by Mitchellvb93** [runelite/runelite#14897]
It would be nice to have a green to red overlay of the items to enchant due to certain items not changing much in appearance after enchanting. Right now I am doing sapphire rings and I'm going cross-eyed trying to keep track. Any help will be much appreciated.

**Comment by Nightfirecat** [comment]
You can use the Inventory Tags plugin to achieve this.

**Comment by Mitchellvb93** [comment]
Is it listed under something else because I do not see inventory tags in the plugins

**Comment by Nightfirecat** [comment]
Make sure you're not searching the plugin hub. (Hit the `<` button to the left of the search bar, if present)

**Comment by Mitchellvb93** [comment]
Ah found it thanks you so much, also for future people who struggled follow nightfirecats instructions to find it then look on youtube to find out how to set them up.

**Comment by Nightfirecat** [comment]
FYI, every core plugin has a wiki page which details how to use it, which can be found [by browsing our wiki](https://github.com/runelite/runelite/wiki) or by right-clicking the plugin and selecting the 'Wiki' option. Inventory Tags' page is here: https://github.com/runelite/runelite/wiki/Inventory-Tags
