### ISSUE TITLE
Player Indicators Plugin suggestion

### ISSUE THREAD

**Issue by troywingert21** [runelite/runelite#14894]
I think it would be a wonderful feature to add a players combat level above their head in addition to their name. If possible, it would also be cool to see their clan and clan rank.

**Comment by Hydrox6** [comment]
Duplicate of #6567

iirc the plugin already shows icon of the clan rank for the clan you're in. The client has no way of getting users of a clan that you're not in.

**Comment by troywingert21** [comment]
The main point of this was combat level next to name
