### ISSUE TITLE
6 Hour logout warning

### ISSUE THREAD

**Issue by joshbt44** [runelite/runelite#14896]
**Is your feature request related to a problem? Please describe.**
6H logging randomly is super annoying and a lot of long sesh gamers probably have encountered this once in a while at the worst times.

**Describe the solution you'd like**
A plugin you can turn on or off that displays a box that you can resize and place anywhere that you can have the option to have flashing that can be cleared by right clicking or suggestions

**Describe alternatives you've considered**
reminding myself but it has happened so many times at certain bosses and i always seem to forget :(

**Comment by LlemonDuck** [comment]
The vanilla client already provides reminders at 4hr, 5hr30 and 5hr55, afaik. You can also use the "Report Button" plugin to show time since logging in, and Idle Notifier also provides 6hr logout notifications.
