### ISSUE TITLE
Abyssal Lantern not included as light source for clue steps

### ISSUE THREAD

**Issue by rheine15** [runelite/runelite#14924]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Clue scroll overlay does not remove the light source required warning when a player has a lit Abyssal Lantern equipped or in their inventory. This warning appears for any steps where the player must enter a dark cave and does not have a valid light source. E.g. Lumbridge swamp caves, Cave Horror Cave in Mos Le'Harmless

**Comment by Nightfirecat** [comment]
For future reference,  you do not need to retroactively create an issue for a PR you wish to open. (Though for something which is not a clear enhancement/bugfix we appreciate doing so, or creating a Discussion topic first so it can be reviewed.)
