### ISSUE TITLE
Ticking Sound While Not Moving/Attacking (No metronome plugin)

### ISSUE THREAD

**Issue by DanielJKaiser** [runelite/runelite#14931]
### Type

Other

### Operating System

MacOS

### OS Version

Most up to date

### Bug description

Randomly started, ticking sound that occurs when I'm not doing anything. It ticktocks in between actions like attacking or moving. I don't have any metronome plugin enabled and have tried to turn off all plugins, still to no avail. Super annoying. Please assist.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
