### ISSUE TITLE
Random events rewards recorded as kc

### ISSUE THREAD

**Issue by scatter-dev** [runelite/runelite#14934]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10 x64

### Bug description

Because the client uses regex to match game messages like "Your Corporeal Beast killcount is: 12" to record kc, it catches events such as "Your reward is: Coins x 120" that are commonly seen from random rewards (the mystery box from Quiz Master, for example). This leads to `!kc reward` reporting a "Reward kill count", that is of course a meaningless number because it's just the most recent reward you got.

### Screenshots or videos

![2022-05-11-02-07-20_RuneLite](https://user-images.githubusercontent.com/24556079/167780384-26047900-fdfe-4462-8a7e-eaf7a0414c95.png)

### RuneLite version

RuneLite version: 1.8.18.5
Launcher version: 2.4.2

**Comment by Nightfirecat** [comment]
Funny timing, we found this via other channels and committed a fix for this mere hours ago. Fixed in 50af007e944570de1138ce99f52e16bd2d8faee2
