### ISSUE TITLE
Using ctrl + backspace for the "Clear Single Word" feature of Chat Commands removes an extra character

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#14941]
### Discussed in https://github.com/runelite/runelite/discussions/14940

Per the title, setting `Clear Single Word` to <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> processes the backspace after clearing the last word, effectively removing the trailing space in the chatbox. This should be consumed like it is with any other keybind, like it is with the default keybind of <kbd>Ctrl</kbd> + <kbd>W</kbd>.

**Comment by RL-User** [comment]
@Nightfirecat @LlemonDuck Omg thank you this has driven me crazy forever. Ya'll the best
