### ISSUE TITLE
GPU Plug in recently causing FPS drop

### ISSUE THREAD

**Issue by lee-CS** [runelite/runelite#14970]
### Type

Performance

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Since couple weeks may be few months ago, I noticed my game would drop FPS to like 20-30 for split second and come back to 50 fps like normal.

What's annoying is that game seems to freeze for a second, not just FPS drop so clicks don't register. Really annoying when bossing and you miss food/potion.

I have a high end set up, 1080 Ti, i7-10700k, 32gb.

Game was totally fine and smooth last year, no FPS drop or anything.

I tried playing without the GPU plug in, and did not notice any FPS drop since.

I tried limiting the GPU draw distance, mess with some options to increase performance, no dice.

What's weird is that my 2nd computer is not suffering from this problem. It has slightly lower spec but pretty similar. 1070, 4700k, 16gb, Win 10.

Log files look different too, getting lots of NullPointerException on comp with problem. May be java update caused this?

### Logs

[client_2022-05-12.0.log](https://github.com/runelite/runelite/files/8692954/client_2022-05-12.0.log)
[launcher_2022-05-12.0.log](https://github.com/runelite/runelite/files/8692956/launcher_2022-05-12.0.log)

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
