### ISSUE TITLE
[BUG] Static background missing at login screen

### ISSUE THREAD

**Issue by SirFancyBacon** [runelite/runelite#14972]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Ubuntu 22.04

### Bug description

At the login window the static background image is missing; this happens with GPU enabled and disabled, as well as 117HD.

Upon first launch without the plugin enabled, with the plugin toggled the effect is the same, toggling the plugin to its opposite state will resolve the issue for the session.

### Screenshots or videos

https://i.imgur.com/ODD1EV3.png

### RuneLite version

Runelite Version: 1.18.19.1
Launcher Version: 2.4.2

### Logs
Client: https://pastebin.com/scRaX6Q4
Launcher: https://pastebin.com/HL093Kyn

**Comment by Nightfirecat** [comment]
What are your login screen plugin settings? Also, please upload your client log.

**Comment by SirFancyBacon** [comment]
@Nightfirecat Sorry for the delay; I have uploaded the logs and screenshot in the main post, This issue happens upon first launch without the plugin enabled, with the plugin toggled the effect is the same, toggling the plugin to its opposite state will resolve the issue for the session.

**Comment by Nightfirecat** [comment]
Does this still happen when running the client in safe mode? (execute the launcher with the `--safe-mode` flag)

**Comment by SirFancyBacon** [comment]
It works in safemode

**Comment by Nightfirecat** [comment]
This is likely caused by some plugin hub plugin then. If you are able to reproduce this in safe mode, we would be interested in investigating it further.
