### ISSUE TITLE
Interact Highlight - Motherlode Mine: Interact Highlight does not highlight empty (or full) sack

### ISSUE THREAD

**Issue by MarcDirven** [runelite/runelite#14992]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

When using Interact Highlight plugin, you'd expect that - if you have "Show on hover" enabled - every interactable object shows an outline. However this is not the case for the Motherlode Mine ore sack at the end of the water cleaning stream.

### Expected
![](https://i.imgur.com/ry8fOK3.png)
### Actual
![](https://i.imgur.com/vsaUieL.png)

### RuneLite version

RuneLite version: 1.8.20
Launcher version: 2.4.2

**Comment by Adam-** [comment]
This is because the object you click on is not the sack, but a separate object that is transparent. The sack itself isn't clickable and is a bridge. So this can't realistically be fixed without us special casing this situation.

**Comment by MarcDirven** [comment]
I'll close this one for now then.
