### ISSUE TITLE
The Isle of Souls Fairy Ring needs to be configured in the World Map plugin

### ISSUE THREAD

**Issue by DrYoshiyahu** [runelite/runelite#15016]
### Type

Other

### Bug description

Really simple of course—just a missing detail for a recently-added feature. The Isle of Souls recently got a Fairy Ring added, which means the World Map plugin needs to be updated, both for the Fairy Ring Code Tooltip option and the Fairy Ring Travel Icon option. For the record, the code for the ring is b•j•p.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/14756430/170974114-4c87989d-b96a-4d68-afa3-de36ce91f8ed.png)

### RuneLite version

![image](https://user-images.githubusercontent.com/14756430/170974501-67eacde1-3221-4e45-92d3-de2d7f5ca6f9.png)

**Comment by Hydrox6** [comment]
Also to note, the Necropolis fairy ring also needs adding to the world map.

Both are already present and supported in the `Fairy Ring` plugin itself, which put the name into the ring's UI.

**Comment by DrYoshiyahu** [comment]
It's only tangentially related, but the other icons at the Necropolis all need the same update as the Fairy Ring.
![image](https://user-images.githubusercontent.com/14756430/170978215-642fd936-5bbb-45b4-a1ce-1ac756d260b2.png)
![image](https://user-images.githubusercontent.com/14756430/170978233-a7e877db-66cf-4da5-89bc-2fda88d2af4e.png)
![image](https://user-images.githubusercontent.com/14756430/170978246-2445da03-3398-4846-8a31-48e1ccfe6c2c.png)
![image](https://user-images.githubusercontent.com/14756430/170978266-a025db34-3e82-4ede-bc0f-a753d2b9a866.png)

**Comment by Adam-** [comment]
fixed in 10b84c803c40e3d6b6320adadcef1903eda7198a
