### ISSUE TITLE
JVM Crash & Error_game_crash

### ISSUE THREAD

**Issue by Mattii124** [runelite/runelite#15070]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Win 11

### Bug description

Cannot replicate easily. Random crashing at random times at GE. Though almost always crashing whenever entering OLM room, then runelite crashing so I cannot raid at all.

### RuneLite version

Runelite version: 1.8.21
Launcher: 2.4.2

### Logs

[jvm_crash_pid_1780.log](https://github.com/runelite/runelite/files/8839211/jvm_crash_pid_1780.log)
[client.log](https://github.com/runelite/runelite/files/8839212/client.log)
[launcher.log](https://github.com/runelite/runelite/files/8839213/launcher.log)

**Comment by problemsproblemsyes** [comment]
I have the exact same crashes. Seems like multiple people on this forum have the same crashes: 0xc0000005. Tried literally everything but so far no fix.

**Comment by Nightfirecat** [comment]
Duplicate of #10628, we don't know what causes this crash.
