### ISSUE TITLE
Entity Hider no longer hiding pets correctly

### ISSUE THREAD

**Issue by sonofachamp** [runelite/runelite#15088]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The Entity Hider plugin randomly stopped hiding pets. It was working previously.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/6614021/173175063-da572e4d-2b9b-4f30-af11-ac61332fc20d.png)

### RuneLite version

RuneLite version: 1.8.22
Launcher version: 2.4.2

### Logs

[launcher.log](https://github.com/runelite/runelite/files/8883341/launcher.log)
[client.log](https://github.com/runelite/runelite/files/8883342/client.log)

**Comment by Vanillj** [comment]
I believe this was fixed in commit db0e561.
