### ISSUE TITLE
Daeyalt Essence not tracked for Craft multiple cosmic runes from a single essence for Elite Clue Skill Challenge

### ISSUE THREAD

**Issue by BearsOnABus** [runelite/runelite#15082]
### Type

Incorrect behavior

### Bug description

Skill Challenge Clue Challenge: Craft multiple cosmic runes from a single essence - I grabbed an inventory of daeyalt essence but the clue helper was still X'd out. Grabbing at least one pure essence turns it to accepted. Challenge is completable with Daeyalt.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/97892675/173097266-2e8c12d2-cb9e-4f72-91ff-5e4d69d0bd18.png)

![image](https://user-images.githubusercontent.com/97892675/173097316-49a0f804-f232-4bda-a615-ff315f347186.png)

Was able to complete with the daeyalt essence

**Comment by SpencerSKane** [comment]
Looking at the code, this appears to have been implemented. Is there still an issue or is this issue supposed to be closed?

**Comment by Felanbird** [comment]
As noted by the above comment, this was fixed a few days after the issue was opened 0980331e1b4a0c0b923359225406b8b12a6db5a3
