### ISSUE TITLE
Screenshot valuable drop not working

### ISSUE THREAD

**Issue by Edpon** [runelite/runelite#15093]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The auto screenshot for valuable drops is not working. Even when the threshold is set to 1gp, it does not take screenshots of drops.  No valuable drop folder has even been generated. 
Confirmed the box was checked, threshold was 100k and received eternal gem (9.9m) drop. No screenshot was taken.

### Screenshots or videos

![1](https://user-images.githubusercontent.com/994650/173210536-cd26e288-d4af-41a9-852f-0baef4121cf6.png)

### RuneLite version

RuneLite version: 1.8.22
Launcher version: 2.4.2

### Logs

[launcher.log](https://github.com/runelite/runelite/files/8885014/launcher.log)
[client.log](https://github.com/runelite/runelite/files/8885015/client.log)

**Comment by Nightfirecat** [comment]
Do you have the valuable drop game messages turned on in the game's settings? Those are required for that setting of the plugin to work.

**Comment by Edpon** [comment]
I am the big dumb, thanks for the reply :)
