### ISSUE TITLE
[decompilation] Replace char primitives with integer values

### ISSUE THREAD

**Issue by kylestev** [runelite/runelite#151]
This boils down to seeing `'\xffff'` vs `65535` in the code. The latter being preferred.

It's sometimes difficult to tell at first glance if examples like the following are the same integer value.

[`this.readUnsignedShort() - '쀀'`](https://github.com/runelite/runelite/blob/master/runescape-client/src/main/java/Buffer.java#L402)

[`this.readUnsignedShort() - '耀'`](https://github.com/runelite/runelite/blob/master/runescape-client/src/main/java/Buffer.java#L497)

This might require an upstream fix in fernflower. Not really sure, just thought I'd open this for discussion.

**Comment by kylestev** [comment]
This should probably be scoped to places where `char`s are used in arithmetic statements.

**Comment by kylestev** [comment]
Mentioned in discord:

fesh0r/fernflower@e44ba99

**Comment by kylestev** [comment]
Further notes from @Adam- regarding the work required.

> The decision is to either update fernflower completely or simply apply that patch. the version of fernflower I use now is https://github.com/runelite/fernflower and it is versioned and deployed up to repo.runelite.net which the updater pulls in using maven. So you could PR that patch against that repo if you wanted. But to change fernflower you need to manually run the full decompile and mapping procedure locally since the CI does not cover it and I dont know of what impacts it will have
> [...]
> I wouldnt mind seeing fernflower updated completely if it still functions
> [...]
> Also I find that the decompiled result of the compiled fernflower decompile is generally drastically different from the decompiled result of the output of the deobfuscator. which I think is due to javac more than anything.  so when I update things I will re-map everything and then re-decompile it instead of redecompiling runecsape-client
> so you would have to basically get 154, deobfuscate it, map the existing client to it, and then decompile that with the newer ff version and commit that

**Comment by Adam-** [comment]
Fixed in #176

**Comment by kylestev** [comment]
Nice!
