### ISSUE TITLE
Top center overlay doesn't move to the correct location for its first paint

### ISSUE THREAD

**Issue by Brianmm94** [runelite/runelite#15102]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I've been helping with the development of a plugin that uses an overlay, which is located at the link below. I'm not exactly an expert at coding in Java, so it's pretty likely that I'm just doing something wrong. When I enable or disable the overlay within my plugin's configuration, which causes changes to occur in my `OverlayPanel` member function `public Dimension render(Graphics2D graphics)` it looks like it's painting it in the wrong location and then on the second paint it's shifting to the correct location. I took a look at other plugins like Attack Styles, and it occurred there as well when I rapidly select and deselect "Always show style". You can also see it with the XP Globes plugin as well if you set "Duration of orbs" to 1s and do something that gives an exp drop after the orb disappears. Adding and removing my overlay from the `OverlayManager` when the plugin is disabled and enabled still seems to make it paint correctly the first time though. [https://github.com/cmsu224/clan-events](url)

### Screenshots or videos

https://gyazo.com/d37d907ce6900869086f2b9dceee0a8e
https://gyazo.com/f9990ca0c38767618a1e422b64284fd7

### RuneLite version

1.8.22
2.1.3

**Comment by Nightfirecat** [comment]
This is a somewhat unfixable problem related to how our overlay renderer draws them.

**Comment by Brianmm94** [comment]
Gotcha, no problem. I mainly just wanted to make sure it wasn't a bug with how I was handling the overlay in our plugin.
