### ISSUE TITLE
configure function key to hide sidebar

### ISSUE THREAD

**Issue by ychoudhury** [runelite/runelite#1510]
I understand that the sidebar is pretty necessary for the client. My proposition is to add an option within runelite settings to enable a function key to hide the sidebar. That way, no one would accidentally disable it. I feel that it would promote a more seamless gameplay experience. Pressing the key again would immediately bring it back up. I feel it would be useful in instances where sidebar options would not be used often. Does anyone have any thoughts?

**Comment by ychoudhury** [comment]
edit title

**Comment by Kamielvf** [comment]
Duplicate of #656

**Comment by ychoudhury** [comment]
closed, thank you
