### ISSUE TITLE
smelting plug-in doesn't account for new 8-cannonball mould (giants foundry)

### ISSUE THREAD

**Issue by clebauer** [runelite/runelite#15110]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

Mac OS Big Sur

### Bug description

A new 8-ball cannonball mould was released as a reward in Giant's Foundry. It takes the same number of ticks to turn two (2) steel bars into eight (8) cannonballs that a normal 4-ball ammo mould takes to turn one (1) steel bar into four (4) cannonballs

However, the plugin only counts 4 at a time, not accounting for the potential that the new ammo mould is in use, which should double the cannonballs smelted. (and I'm unsure whether that should be reflected in the actions per hour).

ADDITIONALLY: I'm unsure if this is a bug, but it may be worth looking into: this may need to be reflected within the XP globes if they use the same variables!

### Screenshots or videos

<img width="1440" alt="Screen Shot 2022-06-14 at 6 41 59 PM" src="https://user-images.githubusercontent.com/31354379/173701255-9729b2fb-ff5a-47c1-9e1f-68539c25f3ed.png">

### RuneLite version

Runelite version: 1.8.22
Oldschool version: Rev 205
Launcher version: 2.3.0

### Logs

[launcher.log](https://github.com/runelite/runelite/files/8904335/launcher.log)
[client.log](https://github.com/runelite/runelite/files/8904336/client.log)

**Comment by Adam-** [comment]
added in #15446
