### ISSUE TITLE
Change !pb command to display hours, if applicable

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#15122]
The `!pb` command should show its format as `h:mm:ss(.ff)` if its duration is long enough that hours would be necessary. It should remain `mm:ss(.ff)` for any duration under 60 minutes.

### Discussed in https://github.com/runelite/runelite/discussions/15120

<div type='discussions-op-text'>

<sup>Originally posted by **movieminer** June 17, 2022</sup>
Yesterday, I got my first Fire cape ever, with the wonderful time of 1:23:45.60.
Unfortunately, the !pb command shows this as 83:45.60
For more consistency (and a little flex) it would be nice if the !pb command also shows the pb times in the format of hh:mm:ss.t
</div>

**Comment by Thource** [comment]
I'll do this
