### ISSUE TITLE
Tile Indicators plugin doesn't work properly with Ranged

### ISSUE THREAD

**Issue by iVilux** [runelite/runelite#1513]
> The tiles keep being shown after attacking something when using Ranged: 
![image](https://user-images.githubusercontent.com/1732344/38766359-ad2012ea-3fd9-11e8-85b8-c7285a9ef2e5.png)

**Comment by Kamielvf** [comment]
We just paint the tile the minimap flag is pointing at. I don't think this is really an issue since your minimap flag is still there when you're ranging? Or is that not the case?

**Comment by iVilux** [comment]
It is, but as I understand a check could be added if the player is both ranging + the last click was an attack, the tile indicator doesn't activate?

**Comment by Bartvhelvert** [comment]
I just tested this and I personally don't have this problem while ranging. The tile marked while ranging is set where it would walk to if the player was using melee. In the picture above this just happens to be far off the actual npc. A much better approach to fixing this would be to calculate the path client sided.

**Comment by iVilux** [comment]
It's because the NPC came over to me.

**Comment by deathbeam** [comment]
This is just how the destination tile works and so it is intentional
