### ISSUE TITLE
Remove dead npc menu respawns npcs with no options

### ISSUE THREAD

**Issue by 115Apollo** [runelite/runelite#15139]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Killing an npc with Remove dead npc menu causes the npc to spawn without options/attackable or highlight it as a mob. This includes left click attack on in vanilla settings or highlighting all npcs of the same type/name.

### Screenshots or videos

After respawning with dead menu on (w/ hightlight on)
![2022-06-17_22-50-56](https://user-images.githubusercontent.com/28681269/174420460-537a45f2-a2f9-4646-917a-72b3bede58e6.png)

Is attackable with dead menu off (but no highlight even w/ on)
![2022-06-17_22-55-28](https://user-images.githubusercontent.com/28681269/174420491-d576b606-fb3a-4c93-9d86-a06c42d92acb.png)

No attack/option available with dead menu on
![2022-06-17_22-56-18](https://user-images.githubusercontent.com/28681269/174420501-842fed02-2d9e-4430-bfb5-97eb036759fe.png)

### RuneLite version

Runelite version 1.8.24
Launcher version 2.1.7

### Logs

[client.log](https://github.com/runelite/runelite/files/8932858/client.log)
[launcher.log](https://github.com/runelite/runelite/files/8932859/launcher.log)

**Comment by Nightfirecat** [comment]
We had someone test this and wasn't able to reproduce it. Can you try reloading your client? You're currently a point release behind what's current--we released 1.8.24.1 a few hours after your version today.

**Comment by 115Apollo** [comment]
Reloading the client did solve the issue.

**Comment by Nightfirecat** [comment]
Well if you do manage to run into this again (particularly if you can reproduce it reliably), let us know and we'll reopen this and investigate it.
