### ISSUE TITLE
Certain NPCs are incorrectly considered dead for MES and Entity Hider plugins

### ISSUE THREAD

**Issue by trinitiislozer** [runelite/runelite#15135]
### Type

Incorrect behavior

### Bug description

The `Remove dead npc menus` option of the Menu Entry Swapper plugin and the `Dead npcs` option of the Entity Hider plugin cause some monsters to become uninteractable or invisible, which prevents you from killing them after phase changes or interacting them with state changes as intended. Some examples are:

**NPCs with multiple forms:**
* [x] ~~Forms 2-4 of the Witch's Experiment~~ Fixed in internal change
* [x] ~~Nazastarool~~ Fixed in internal change
* [x] ~~Kolodion~~ Fixed in internal change
* [x] ~~Tarn Razorlor~~ Fixed in internal change

**NPCs which should be interactable (but not attackable) after transforming on death:**
* [x] ~~Pyromancers at Wintertodt~~ Fixed in b96867bb06e6f29b0327c2d7a634484ba12f1293
* [x] ~~Nightmare / Phosani's Nightmare cannot be re-awakened once they die~~ Fixed in b96867bb06e6f29b0327c2d7a634484ba12f1293
* [x] ~~Chompy and Jubbly birds cannot be plucked once killed~~ Fixed in b96867bb06e6f29b0327c2d7a634484ba12f1293
* [x] ~~Gadderanks from the In Aid of the Myreque quest~~ Fixed in b96867bb06e6f29b0327c2d7a634484ba12f1293
* [x] ~~Desert lizards cannot be ice coolered~~ Fixed in #15144
* [x] ~~Dead ents cannot be chopped~~ Fixed in b96867bb06e6f29b0327c2d7a634484ba12f1293

**Comment by Alexsuperfly** [comment]
Nazastarool should also be checked if this happens to them too.

**Comment by mxiia** [comment]
The pyromancers in Wintertodt are also unable to be healed when they die because of this.

**Comment by animatic-ps** [comment]
This also affects Phosani's nightmare (and presumably regular nightmare), after killing the nightmare can't be disturbed. Also after respawning if you turn Entity hider back on it will never become visible again even when alive.

**Comment by Nightfirecat** [comment]
I've rolled up the NPCs from the comments and those mentioned in #15146 and #15149 into the original post for this issue. Please consolidate any other NPCs needing fixing to this issue.

**Comment by queicherius** [comment]
Noticed this yesterday with Desert Lizards (hidden / not targetable when ice coolers have to be used)

**Comment by shawncrobinson** [comment]
Dead Ents are also unable to be chopped with either of these plugins enabled.

**Comment by MESLewis** [comment]
Jubbly birds as well

**Comment by RsFoe** [comment]
Can you include nightmare/phosanis totems active ID in excluded npcs. You are unable to attack the totems once fully charged anyway and there are situations where you are unable to charge them because of entity hider. One example I can remember is during a parasite phase if you kill one near the totem the plugin removes the charge option on it for Id guess like 10 ticks then realizes its still alive.

**Comment by Nightfirecat** [comment]
@RsFoe This should already be fixed if you are on 1.8.24.1 instead of 1.8.24.

**Comment by Nightfirecat** [comment]
As of release 1.8.24.2 all reported NPCs have been fixed and we expect the changes applied for them should generally fix all NPCs. For any specific ones needing further fixing, please open new issues.
