### ISSUE TITLE
Remove dead NPC menu doesn't allow you to pluck chompies

### ISSUE THREAD

**Issue by Yocairo** [runelite/runelite#15146]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

Just kill a chompy, and you can't pluck it, have to disable the option

### RuneLite version

Runelite version 1.8.2.4.1
Jagex Launcher version 0.17.2.0

**Comment by Nightfirecat** [comment]
I've added this to #15135 for general tracking of NPCs needing fixing with this feature.
