### ISSUE TITLE
'Remove dead npc menus' breaks mage arena fight with Kolodion

### ISSUE THREAD

**Issue by jodelahithit** [runelite/runelite#15149]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Enabling the new 'Remove dead npc menus' option breaks the mage arena fight with Kolodion. He can no longer be attacked after changing stages. Disabling and re-enabling the option fixes the problem.

**Comment by Nightfirecat** [comment]
I've added this to #15135 for general tracking of NPCs needing fixing with this feature.
