### ISSUE TITLE
Quest bug with Menu entry swapper

### ISSUE THREAD

**Issue by Culinarist** [runelite/runelite#15152]
### Type

Other

### Operating System

Windows

### OS Version

Win 11

### Bug description

There is a guy in my clan who was doing the Aid of Myreque quest and he killed Gadderanks but couldn't speak to him to continue the quest because he had that new Menu Entry Swapper "Remove Dead npc menus" and the option was hidden. I'm not sure which other quests contain interactions with something that has been considered defeated but I think it should be fixed! I wanted to report it in hopes that it helps!

**Comment by Nightfirecat** [comment]
I've added this to #15135 for general tracking of NPCs needing fixing with this feature.
