### ISSUE TITLE
Kourend Library Plugin bug

### ISSUE THREAD

**Issue by iVilux** [runelite/runelite#1515]
Tradgedy is written with a grammar error and also, the wrong location is written on the right hand menu.
![image](https://user-images.githubusercontent.com/1732344/38767056-eecdf09a-3fe3-11e8-9713-bd307a150082.png)

**Comment by Gamer1120** [comment]
Reopen this, isn't fully fixed.

**Comment by deathbeam** [comment]
Hmm, I changed it to see also, idk why it closed this

**Comment by Nightfirecat** [comment]
The PR used the phrase `closes #1515`, which GitHub picked up to automatically close this once it was merged.
