### ISSUE TITLE
Hellhounds bug out with smooth animations plugin

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1516]
Demonstration video: https://youtu.be/uuDJrtZgWwU

**Comment by iVilux** [comment]
Same happens with default OSBuddy OpenGL. I don't think this can be fixed easily.

**Comment by TheeWiki** [comment]
Happens with other npcs as well, it's not a game breaking bug but there's probably be a fix for it when openGL comes out on OSRS

**Comment by iVilux** [comment]
Wiki, what makes you think it's going to come out? Only graphics card acceleration is said to come.

**Comment by MESLewis** [comment]
I believe the assumption is that if Jagex are going to use openGL for mobile then they will need to fix the animation bugs. But the bugs aren't with openGL, it's with trying to smooth the animations. Some animations are just weird.

**Comment by iVilux** [comment]
They're not using OpenGL for mobile, but they're using graphics card acceleration.

**Comment by iVilux** [comment]
Oh okay, guess I was wrong. Looked it up, software rendering is CPU only so it's probably OpenGL without anti-aliasing and smooth animations.

**Comment by Adam-** [comment]
Fixed in 68639d893271c825ac8406193bd9f9072e5a5378
