### ISSUE TITLE
Alchemical Hydra Respawn Time

### ISSUE THREAD

**Issue by BoomBappa** [runelite/runelite#15167]
I have been doing some Alchemical Hydra lately and one day the respawn timer just stop working for it so i can't tell when he will spawn, having to wait for him with the prayer on have been costing some prayer points for lengthy trips. Tried with another boss to check if it was a problem with the whole plugin but it worked in other bosses, it just stop working at Hydra.

**Comment by Hydrox6** [comment]
This has been fixed internally and will be in the next update released.
