### ISSUE TITLE
Menu Entry Swapper - "Remove dead npc menus" prevents you from fighting Tarn's second form.

### ISSUE THREAD

**Issue by LostKnight411** [runelite/runelite#15161]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The "Remove dead npc menus" option in Menu Entry Swapper hides all click options on Tarn's second form during the boss fight of the Lair of Tarn Razorlor miniquest. This prevents the player from fighting the second form until the option is turned off.

### RuneLite version

Runelite 1.8.24.1
Launcher 2.1.3

**Comment by Nightfirecat** [comment]
I've added this to #15135 for general tracking of NPCs needing fixing with this feature.
