### ISSUE TITLE
World map location for Vannaka easy cryptic clue is incorrect

### ISSUE THREAD

**Issue by MrRickroll** [runelite/runelite#15203]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

While doing an easy clue I found out that the location of a map marker for the vannaka step is way off. it's located north-east of where it should be.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/59365572/175525939-a3088160-c3c6-44df-8b75-0cb5396c351a.png)

### RuneLite version

Runelite Version: 1.8.24.3
Launcher Version: 2.4.0

**Comment by SpencerSKane** [comment]
fix: https://github.com/runelite/runelite/pull/15211

It seems there is two cryptic clues that have you seek out Vannaka. One has the correct coordinate and the other has an incorrect 'x' coordinate.
