### ISSUE TITLE
UI Overlay request

### ISSUE THREAD

**Issue by SidabrasJ** [runelite/runelite#1520]
Hello, I thought maybe some one could try and do that 2010 overlay that osbuddy has? With those bars and sprites? Thanks!
![d4ly96t](https://user-images.githubusercontent.com/38375633/38767355-4beef9dc-3fe8-11e8-8cec-22beff971d4a.png)

**Comment by Abextm** [comment]
Duplicate #457

**Comment by devLotto** [comment]
Closing as duplicate
