### ISSUE TITLE
Entity Hider [Hide Dead NPCs] bugged for KQ second form

### ISSUE THREAD

**Issue by Murcja** [runelite/runelite#15214]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The RuneLite plugin 'Entity Hider' has a new option for 'Hide Dead NPCs'.

However, for about 2% of Kalphite Queen kills (of 350 kills), this option hides the boss as it's almost dead in her second form yet she remains alive but HIDDEN due to this plugin option.

Disabling the plugin fixes the issue and she becomes visible again.

It seems to be unique to this boss from my experience so far. The plugin works as intended everywhere else I have seen.

I suppose the client thinks the NPC is dead as she regens 1hp or so? I'm not sure. The boss is always on less than 5hp when I see it happen. I am using Ring of Suffering (ri) with recoil effects and blowpipe. Sometimes Vengeance. Can't find consistency in reproducing issue.

Screenshot provided.

### Screenshots or videos

![2022-06-25_14-44-38](https://user-images.githubusercontent.com/108184770/175776771-2a19b936-828d-4c03-86be-d4fd6e4ec612.png)

### RuneLite version

RuneLite version: 1.8.24.3

Launcher version: 2.1.0

**Comment by Nightfirecat** [comment]
We are working on a broader fix for some other edge cases not covered by our current implementation of dead NPC entity/menu entry hiding--it should fix this as well.

**Comment by Nightfirecat** [comment]
This has been fixed via internal changes and 13d8308b9ecf7e3b04574ef4d329ddfe00197f47.
