### ISSUE TITLE
Entity Hider - Hide Dead Npcs scuffs Npc Indicator Respawn timers

### ISSUE THREAD

**Issue by pwatts6060** [runelite/runelite#15256]
### Type

Incorrect behavior

### Bug description

Respawn timers appear to be too fast when you hide dead npcs. My theory is the early removal starts the respawn timer earlier than it should. Confirmed that turning off Hide Dead NPCs fixes the issue.

Reproduce requirements:

Entity Hider plugin on
-"Hide Dead NPCs" on

Npc Indicators plugin on
-"Show respawn timer" on

Tag "Greater Nechryael"

### Screenshots or videos
https://i.gyazo.com/140b563d28093d9e14ee54c6146d1880.gif

RuneLite version: 1.8.25
Launcher version: 2.4.2

**Comment by LlemonDuck** [comment]
I was unable to replicate this on Greater Nechryaels or any other monsters. Does the issue persist for you after restarting your client?

**Comment by pwatts6060** [comment]
> I was unable to replicate this on Greater Nechryaels or any other monsters. Does the issue persist for you after restarting your client?

I tried again this time at Mutated bloodvelds cannoning and whipping them and it was normal. Didn't restart client. Maybe it's specific to bursting, fps control, or something else?

**Comment by russel204** [comment]
> > I was unable to replicate this on Greater Nechryaels or any other monsters. Does the issue persist for you after restarting your client?
> 
> I tried again this time at Mutated bloodvelds cannoning and whipping them and it was normal. Didn't restart client. Maybe it's specific to bursting, fps control, or something else?

I had this happen when afking (melee) cave horrors for slayer. Restarting the NPC indicators plugin fixed it for me.

**Comment by Nightfirecat** [comment]
While it's possible that the NPC Indicators could have recorded the wrong respawn time for a given spawn, I don't think that has anything to do with the entity hider plugin. If anyone has reliable steps to cause an inaccurate respawn timer, I'd be interested to look at it in a separate issue.
