### ISSUE TITLE
Menu Entry Swapper: Hopeless creature (A Soul's Bane)

### ISSUE THREAD

**Issue by Ammako** [runelite/runelite#15250]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The Hopeless creatures during A Soul's Bane have multiple phases, and the Menu Entry Swapper option to remove dead NPC menus makes them unattackable after you finish off a phase. Current workaround is to either disable the menu entry swapper option while you do that part of the quest, or off-screen them so they get their attack options back after they come back on screen.

### RuneLite version

RuneLite: 1.8.25
Launcher: 2.4.0

**Comment by Nightfirecat** [comment]
Have you finished the quest yet? If not, we'd like to get some help testing fixes for this. We have code in place for other similar NPCs, but don't have the particular IDs of the hopeless creature to test with. (and since the quest can't be repeated, we don't have any way to test with new IDs)

**Comment by russel204** [comment]
i've been having this issue as well at abby demons. one of them keeps not having click options when it respawns and i have to toggle the remove dead npc menus option to fix it
