### ISSUE TITLE
Skill Calculator: "Ensouled hellhound head" missing

### ISSUE THREAD

**Issue by ArashiJoe** [runelite/runelite#15261]
### Type

Other

### Operating System

Windows

### OS Version

Win 10 Home x64-bit

### Bug description

"Ensouled hellhound head" is missing from the Prayer actions in the Skill Calculator.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/61663896/177024150-4cdc60e8-dfd9-492a-b68a-34aab3f501eb.png)

**Comment by Nightfirecat** [comment]
Added in #15064
