### ISSUE TITLE
Loot Tracker ( Zalcano )

### ISSUE THREAD

**Issue by AsunaKonno** [runelite/runelite#15264]
### Type

Other

### Bug description

When killiing Zalcano the loot tracker PNL does not keep track of KC's or the drops. I do not have the loot hidden or ignored. I did get the loot tracker for the golem tho.

**Comment by Nightfirecat** [comment]
This is already fixed in 7690e5c5f3850f4879b11eeb33229d77a4b86c37, and restarting your client so it will be on version 1.8.25.3 will make sure you're running with that fix integrated.

**Comment by AsunaKonno** [comment]
Thank You.
