### ISSUE TITLE
World switcher not working - even after restarting client

### ISSUE THREAD

**Issue by Ingenioer** [runelite/runelite#15279]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

W11

### Bug description

I cannot hop worlds in the world switcher menu. It keeps loading and wont go any further. I tested my internet, no problems. I tried restarting client but still same issue.

### Screenshots or videos

![world switch error](https://user-images.githubusercontent.com/108811074/177554486-c9f2b4cf-f049-4d6b-86e5-cadc9d9b5410.PNG)
![World switch](https://user-images.githubusercontent.com/108811074/177554490-28d9cef5-c79b-43d3-acff-877ffbc9a886.PNG)

**Comment by Hydrox6** [comment]
This has nothing to do with RuneLite; it's a connection issue between you and Jagex.

The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
