### ISSUE TITLE
Additional black bar when opening RL Menu on MacOS

### ISSUE THREAD

**Issue by BUCKFAE** [runelite/runelite#15276]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

macOS Monterey - Version 12.4

### Bug description

Steps to reproduce:
1. Play in Fullscreen Mode
2. Open any of the menus on the right

To get rid of the black bar, you have to exit Fullscreen.

### Screenshots or videos

https://user-images.githubusercontent.com/33499592/177497109-4bc7da05-fab4-41f8-8a5d-293f39ed093e.mp4

### RuneLite version

Version 2.4.2

**Comment by Alexsuperfly** [comment]
do you have this on game or window
![image](https://user-images.githubusercontent.com/7191512/177538065-0c242995-2d26-4ad2-9c99-21b0a8d9e17d.png)

**Comment by BUCKFAE** [comment]
> in the "RuneLite" plugin settings do you have this on game or window?
> ![image](https://user-images.githubusercontent.com/7191512/177538065-0c242995-2d26-4ad2-9c99-21b0a8d9e17d.png)

No, it was set to `Keep window size`. After changing it to `Keep game size`, everything behaves as expected. 
Thank you, I was not aware of this setting.
