### ISSUE TITLE
Ring of Forging Does not list correct amount of charges for new ring

### ISSUE THREAD

**Issue by Watevir** [runelite/runelite#15286]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

Pretty much just what it says on the label, RuneLite starts a ring of forging at 139 charges instead of the correct number 140

**Comment by Alexsuperfly** [comment]
the fix for this requires the or operation on line 354 of ItemChargePlugin.java to be evaluated first

**Comment by Braiden123** [comment]
I have been unable to replicate the issue myself.
New rings start at 140 for me either brand new or after breaking.

**Comment by Tatters654** [comment]
I was able to replicate this. It only happens if the ring disintegrates after smelting iron ore.

**Comment by Hydrox6** [comment]
Duplicate of #12725
