### ISSUE TITLE
menu swapper coal bag issue

### ISSUE THREAD

**Issue by at331** [runelite/runelite#15299]
### Type

Incorrect behavior

### OS Version

windows 11

### Bug description

I set the bank deposit to eat/wield. Withdrew coal to inventory then shift left clicked the coal bag to fill it up while in bank. The coal bag fills up then my inventory automatically fills with coal as well without me clicking anything. I tested the same thing with rune pouches that works properly. it fills the pouch and the inventory doesn't automatically fill.

**Comment by geheur** [comment]
when you fill the coal bag while the bank is open it takes the coal from your bank not your inventory so it makes sense that your inventory remains full of coal.

**Comment by kamielvf** [comment]
This has nothing to do with the menu entry swapper or even RuneLite in general. This is how the "fill" option works within the bank and we do not impact it in any way whatsoever.
