### ISSUE TITLE
Incorrect clue location

### ISSUE THREAD

**Issue by solowanna** [runelite/runelite#15317]
### Type

Incorrect behavior

### Bug description

For the anagram clue for Cam the Camel, the location says 'Outside Duel Arena'.. With the release of the new PvP arena the location should be changed to 'Outside PvP arena'

### Screenshots or videos

![image](https://user-images.githubusercontent.com/2229515/178295912-d45824a5-6cb0-4701-9834-4619f00c9dec.png)

**Comment by Adam-** [comment]
fixed in 91e5d18bace3414c944b3ae546e5ea87408ce4ad
