### ISSUE TITLE
Mahogany homes plugin is gone

### ISSUE THREAD

**Issue by neosporinn** [runelite/runelite#15333]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When i started runelite today all my downloaded plugins were gone, I couldn't find them on pluginhub either. I closed the sidebar and reopened it and then I could find them, particularly 117 HD. But as I went to do mahogany homes the plugin was still gone. I've searched pluginhub for it and it just doesn't show up anymore. It's like it's completely gone. I even found the link to the mahogany homes plugin through reddit and when I go there it won't let me download it or anything. I don't understand what's going on.

### RuneLite version  1.8.27

Launcher Version: 1.6.0

**Comment by Hydrox6** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
