### ISSUE TITLE
Shift-clicking worn equipment sometimes causes shift button to "stick" in inventory tab

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#15349]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Manjaro Linux

### Bug description

To reproduce:
Equip an item with a right-click option (Teleport, Check, etc.)
Open equipment tab
Swap the item's shift-click option to Teleport, Check, etc.
Shift-click the item and quickly switch to the inventory tab using F-keys
Roughly 1 in 20 times, the inventory will act as though the shift button is held down. Most items essentially act as though their left click option is swapped to Drop. This lasts until you either click, or press and release shift.  This does not affect other tabs, e.g. the Magic tab will not swap any spells (NPC Contact, various teleports) to their shift-click options.

### RuneLite version

RuneLite version: 1.8.27
Launcher version: 2.4.2

### Logs

[client_2022-07-13.0.log](https://github.com/runelite/runelite/files/9117687/client_2022-07-13.0.log)
[launcher.log](https://github.com/runelite/runelite/files/9117688/launcher.log)

**Comment by Nightfirecat** [comment]
We use the client's shift button detection, so this is caused by a Jagex bug.

**Comment by fuzxi** [comment]
This week's game update has fixed this bug.
