### ISSUE TITLE
Loot tracker data missing from runelite sidebar

### ISSUE THREAD

**Issue by Tuonentytti** [runelite/runelite#15367]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I updated my runelite and suddenly my loot tracker was empty. I'm still signed in and i can find my loot from the website and everything is fine there. All the settings and other plugins are fine as well. When i log out it finds the data but not when i sign in.

**Comment by Hydrox6** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
