### ISSUE TITLE
Clue scroll overlay intercepts shift input in bank

### ISSUE THREAD

**Issue by Whaitiri** [runelite/runelite#15360]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When attempting to withdraw items from the bank while holding shift, using Custom Menu Swaps to change the withdraw amount, when the clue scroll overlay is underneath the bank interface, the shift input will not be read. e.g. Withdraw-All by default, Withdraw-1 with shift held. In the screenshot below, the items in the green area will Withdraw-All when shift clicked. Items outside this area Withdraw-1 as normal, and moving the clue scroll overlay will also fix the issue.

Not sure if this should be a Custom Menu Swaps issue, will close and post there if so.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/17192016/179383627-4ba98053-ed48-44d8-8e57-1d6a510f03f8.png)
![image](https://user-images.githubusercontent.com/17192016/179383675-504ad9a1-6808-41fb-af44-042909d1d7ef.png)

### RuneLite version

Latest

**Comment by Nightfirecat** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
