### ISSUE TITLE
Arrow keys not moving camera M1 MacOS

### ISSUE THREAD

**Issue by JoshFairw** [runelite/runelite#15377]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

MacOS Monterey

### Bug description

I have never had this issue until today, but the camera is not being controlled by my arrow keys in game.

I have restarted my Mac, reinstalled the client, and nothing is working.

If I remap the keys to WASD, it begins controlling the camera again using these, but not the arrow keys?!

### RuneLite version

1.8.27.1
2.4.2

**Comment by JoshFairw** [comment]
I have not amended or changed any settings, simply logged into my accounts this evening and arrow keys do not move the camera.

The arrow keys are working in all other applications.

**Comment by JonathanLab** [comment]
Any updates on this? Currently experiencing the same problem on a M1 13-inch M2 2022 Macbook Pro. WASD keys do not move the camera when using the Key Remapping Plugin.

**Comment by JoshFairw** [comment]
Hi, I did fix it and it was something very simple, like a setting that needed changing or something. I can’t for the life of me remember what it was though I’m so sorry, it was a while ago!!JoshSent from my iPhoneOn 24 Feb 2023, at 14:36, JonathanLab ***@***.***> wrote:﻿
Any updates on this? Currently experiencing the same problem on a M1 13-inch M2 2022 Macbook Pro. WASD keys do not move the camera when using the Key Remapping Plugin.
