### ISSUE TITLE
OverlayRenderer.java uses bounds.contains(mousePosition) in a wrong way.

### ISSUE THREAD

**Issue by PatrykSitko** [runelite/runelite#15385]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

runelite-client\src\main\java\net\runelite\client\ui\overlay\OverlayRenderer.java
line:  372

Whenever I set the bounds for an Overlay and the bounds do not start at location x:0,y:0.
The mousePosition is wrongly calculated as bounds.contains method does not start calculating at canvas startpoint but at (Rectangle) bounds startpoint. So if bounds are x:1,y:1,width:100,height:100; And mouse position is x:101,y:101; The bounds.contains method will return false as it starts to calculate from within the rectangle bounds and does not take notice of the canvas position.
x:101,y:101 mouse position sould be in bounds as the bounds start at x:1,y:1 and end at width:100,height:100 what relative to the canvas means that the mouse position is in bounds but the method does not remove the rectangle x,y coordinates from mousePosition in order to get the .contains method to trigger correctly.

**Comment by Nightfirecat** [comment]
What code are you writing where this is clearly reproduceable? Can you give us a minimal case where we can see this for ourselves?

**Comment by PatrykSitko** [comment]
So I have created an overlay, Whenever I try to use onMouseOver the function does not trigger.
When you draw something inside of the overlay with bounds set to example:
x:100,y:100 and then you draw it at location x:0,y:0 the drawn item will get drawn inside of the Overlay bounds that start at 100,100 but the drawn item is at position 100,100 as the bounds start there. that's the x:0,y:0 coordinates for the render method.
So whenever bounds.contains(mousePosition) method is run inside of: 
```runelite-client\src\main\java\net\runelite\client\ui\overlay\OverlayRenderer.java
``` at ```line: 372```. The mousePosition is relative to the canvas X,Y but for the (Rectangle) bounds it's relative to it's own x,y starting point.

**Comment by Nightfirecat** [comment]
Again, can you please provide a minimal Overlay class which reproduces this?

**Comment by PatrykSitko** [comment]
To reproduce:
Create an overlay. set bounds to be example: x,100,y:100,width.10,height:10 and try to trigger the public void onMouseOver()
	{
	} method that's a optional override.

**Comment by PatrykSitko** [comment]
package net.runelite.client.plugins.tileMapper;

import java.awt.Dimension;
import java.awt.Graphics2D;

import net.runelite.client.ui.overlay.Overlay;

public class OverlayExample extends Overlay {

    public OverlayExample(){
        super.getBounds().setBounds(100, 100, 100, 100);
    }
    @Override
    public Dimension render(Graphics2D graphics) {
        // TODO Auto-generated method stub
        return null;
    }
    
    @Override
    public void onMouseOver(){
        System.out.println("will not get triggered!");
    }
}

**Comment by PatrykSitko** [comment]
> Again, can you please provide a minimal Overlay class which reproduces this?

- Example:

package net.runelite.client.plugins.examplePlugin;

import java.awt.Dimension;
import java.awt.Graphics2D;

import net.runelite.client.ui.overlay.Overlay;

public class OverlayExample extends Overlay {

public OverlayExample(){
    super.getBounds().setBounds(100, 100, 100, 100);
}
@Override
public Dimension render(Graphics2D graphics) {
    // TODO Auto-generated method stub
    return null;
}

@Override
public void onMouseOver(){
    System.out.println("will not get triggered!");
}
}

**Comment by Nightfirecat** [comment]
We don't consider that to be proper usage of the overlay API. Generally you should always return the size of your array as the `Dimension` from `render()` and not try to set its position at all, as that is meant to be controlled by the user. You can still draw outside of those bounds as needed using `graphics.translate()` or any other method which draws at a point besides the graphics origin, such as the following:

```java
package net.runelite.client.plugins.example;

import java.awt.Dimension;
import java.awt.Graphics2D;
import lombok.extern.slf4j.Slf4j;
import net.runelite.client.ui.overlay.Overlay;

@Slf4j
class ExampleOverlay extends Overlay
{
	public Dimension render(Graphics2D graphics)
	{
//		these commented lines achieve the same effect as the line following it
//		graphics.translate(100, 100);
//		graphics.fillRect(0, 0, 100, 100);
		graphics.fillRect(100, 100, 100, 100);
		return new Dimension(100, 100);
	}

	@Override
	public void onMouseOver()
	{
		log.debug("moused over");
	}
}
```

This overlay would print only when you hover the 100x100 box directly to the upper-left of the drawn rectangle.
