### ISSUE TITLE
Screenshot Valuable drops not working at Barrows

### ISSUE THREAD

**Issue by Akryn** [runelite/runelite#15381]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

I've ran around 40 Barrows chests and screenshots are not being taken of the valuable loot. First noticed when one wasn't taken for a Karil's leathertop.  I check existing issues and found https://github.com/runelite/runelite/issues/15093 and checked that I had valuable drop game messages turned on, which I believe I do (see screenshots below).

I believe this was happening before todays RuneScape update but I'm not 100% sure.

Perhaps this is expected behaviour since it isn't a "drop", but a chest. The text colour is blue in the chat window and doesn't say "Valuable drop" in red text.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/40525296/180025504-b1623a7b-ae3d-4893-8567-7ee7b6937c36.png)
![image](https://user-images.githubusercontent.com/40525296/180027171-8353370e-e383-4a7c-a0e0-a19ce539dcf2.png)
![image](https://user-images.githubusercontent.com/40525296/180027278-c5bcc38e-4c6c-4710-ab20-ded0e85ee330.png)

### RuneLite version

RuneLite version: 1.8.28
Oldschool revision: Rev 206
Launcher version: 2.2.0

### Logs

[client.log](https://github.com/runelite/runelite/files/9151698/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9151701/launcher.log)

**Comment by Nightfirecat** [comment]
If the "Valuable drop" text doesn't appear for the chest, then it wouldn't be captured as a valuable drop screenshot.

**Comment by Akryn** [comment]
So this feature will never work for Barrows chests?

**Comment by Nightfirecat** [comment]
I guess we could update it to accommodate barrows chest value messages

**Comment by Adam-** [comment]
Barrows chest is already covered by "screenshot rewards", so this doesn't seem necessary.
