### ISSUE TITLE
Sorry this isn't a bug, just not sure where to report it. The rare trees and rocks in the new area aren't showing what trees/ores are there on the world map

### ISSUE THREAD

**Issue by edgarsaurus** [runelite/runelite#15415]
### Type

Incorrect behavior

### Bug description

The trees and the ores just aren't updated on the world map. I imagine there's a better place to report this, but I don't know where. Sorry.

### Screenshots or videos

<img width="483" alt="image" src="https://user-images.githubusercontent.com/39506282/181585984-0658bbe3-9a83-464f-8b0c-d9cc7399ad70.png">

**Comment by edgarsaurus** [comment]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/39506282/181586962-1405d2e0-b59e-49e6-b316-3d153199a2bb.png">

**Comment by edgarsaurus** [comment]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/39506282/181587108-b33d1b58-8fd4-4aee-8a7b-f7b151cde38b.png">

**Comment by devPhatt** [comment]
![image](https://user-images.githubusercontent.com/90698746/181690707-3d196497-9cfb-48c4-9801-c346f67e9159.png)

Just wanted to provide a better screenshot of the mining area since one old rock was cut off.

**Comment by Nightfirecat** [comment]
Fixed in 2486bca73a9d02af3d1063520087504b9c5ac5e5
