### ISSUE TITLE
Could we please get an option similar to "Lock client to screen"

### ISSUE THREAD

**Issue by anon199469** [runelite/runelite#1542]
OSB and Konduit both have this option. I and a fair share of others like to be able to toggle the option off so the client will stick to one screen instead of moving to another.

**Comment by deathbeam** [comment]
The option should definitely be phrased in opposite way, to make it clear it is opt-in and not opt-out. Something like lock window to screen.

**Comment by anon199469** [comment]
I agree, I was just quoting what OSB option for this was because I forget what the konduit option says. I think it's what you posted so i updated. Thank you!

**Comment by Adam-** [comment]
Fixed in 1b7bdc616b5268bfc6a0de5cfabdab4bed2d3f49
