### ISSUE TITLE
frequent crashing if multiple clients open

### ISSUE THREAD

**Issue by jakescroggy** [runelite/runelite#15421]
### Type

Crash or hang

### Operating System

Windows

### OS Version

win11

### Bug description

this happens even if i run runelite in safe mode. if I have multiple clients open I crash frequently (i.e. 1-3 client crashes an hour).

### Logs

[client.log](https://github.com/runelite/runelite/files/9227007/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9227008/launcher.log)
[jvm_crash_pid_12460.log](https://github.com/runelite/runelite/files/9227009/jvm_crash_pid_12460.log)

**Comment by MileProwler** [comment]
Having a similar problem as well on windows 10
[jvm_crash_pid_20248.log](https://github.com/runelite/runelite/files/9285086/jvm_crash_pid_20248.log)
[client.log](https://github.com/runelite/runelite/files/9285087/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9285088/launcher.log)
0

**Comment by jakescroggy** [comment]
for anyone landing on this page from a search engine because they have multiple games/programs crashing randomly; I had to turn off RAM XMP/overclock to fix my issue.
