### ISSUE TITLE
Game Client Layout setting not remembered between different profiles

### ISSUE THREAD

**Issue by TheJellycake** [runelite/runelite#15423]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Game Client Layout setting not remembered between different profiles.

Playing on my main Runelite profile through the Jagex Launcher. I recently started an alt while using a secondary profile in Runelite without the Jagex Launcher. 

When changing my Game Client Layout in Display Settings between Fixed (Classic) and Resizable (Classic) the change transfers to other profiles. This doesn't happen for the control settings.

All plugin settings differences act as they should. The only setting I know of is Game Client Layout.

Using this feature to setup a profile -> https://github.com/runelite/runelite/wiki/General-Features#playing-with-multiple-accounts
Each of my accounts have separate emails and runelite accounts.

The "Target" field for my shortcut is "S:\Users\MYNAME\AppData\Local\RuneLite\RuneLite.exe --clientargs "--config=settings2.properties --sessionfile=session2"

The directory of my original client and the shortcut is "S:\Users\MYNAME\AppData\Local\RuneLite\"

### RuneLite version

Runelite Version: 1.8.29
Oldschool revision: Rev 207
Launcher Version: 2.2.0

**Comment by Hydrox6** [comment]
The game client layout, along with all other Jagex settings, have nothing to do with RuneLite or its settings, as it is a feature of the vanilla game.
