### ISSUE TITLE
Make impling minimap icons solid colour and put name next to.

### ISSUE THREAD

**Issue by Aelthien** [runelite/runelite#1543]
Currently the icons have a white outline for some reason which makes the colour harder to discern.

**Comment by SomeZer0** [comment]
Agreed. We should remove the outline of the imp highlight, as it makes it hard to see which one it is at a glance.
Having the name of the imps show on the map would be good as a toggle as well.

**Comment by SomeZer0** [comment]
A way you can currently get the names to appear in the minimap is with the NPC tag feature, although all the text is blue. But works if you're specifically looking for 1 or 2 types of imp.

Just a workaround in the meantime.

**Comment by Kamielvf** [comment]
Text on minimap is done in #1371 so that will be in next release. As for the outline, I agree it should probably be removed.
