### ISSUE TITLE
Inaccessible areas North East of Nardah and South West of Sophanem 

### ISSUE THREAD

**Issue by DaftVinci** [runelite/runelite#15432]
### Type

Performance

### Operating System

MacOS

### Bug description

If you look at the world map, North East of Nardah and South West of Sophanem there is two large black boxes. When trying to enter the area it is completely inaccessible. 

### Screenshots or videos

https://user-images.githubusercontent.com/110493513/182457225-6653cbf4-ab3a-4371-93fb-e8866c6a7e75.MOV

### RuneLite version

Runelite Version: 1.8.29
Launcher Version 2.4.2

**Comment by LlemonDuck** [comment]
These areas do not exist in-game and have not been created by Jagex. Not a RuneLite bug.

**Comment by DaftVinci** [comment]
Are you saying Nardah and Sophanem do not exist?

**Comment by LlemonDuck** [comment]
These cities exist but the black regions on the map beside these areas do not exist: https://www.runescape.com/oldschool/world-map

**Comment by DaftVinci** [comment]
Gotcha. Thanks for your help!
