### ISSUE TITLE
Max hit hitsplat not interacting with Special Attack counter plugin

### ISSUE THREAD

**Issue by ghostoo666** [runelite/runelite#15436]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Win10

### Bug description

The special attack counter records either number of successful hits per weapon (dwh) or total damage in special attacks per weapon (bgs).  With the new max hit hitsplats, if you hit your max hit during the special attack, it won't be recorded to the counters.

**Comment by Adam-** [comment]
fixed in d81463e4ad60eceab47470519ac49c91eea53139
