### ISSUE TITLE
Werewolves shake when standing still

### ISSUE THREAD

**Issue by Z-Kaz** [runelite/runelite#15464]
### Type

GPU

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Werewolves in the GWD noticeably shake only when standing still. Just noticed it when doing a task in the GWD. Unsure if werewolves at other locations have the same issue but they probably do.

### Screenshots or videos

![2022-08-08_22-15-54](https://user-images.githubusercontent.com/49293460/183557808-6cf0368f-46bf-43c1-b09c-7d734c9315bd.png)

### RuneLite version

Runelite Version: 1.8.30

Launcher Version: 2.3.0

**Comment by Nightfirecat** [comment]
...can you submit a video of this? A screenshot isn't going to show this happening.

**Comment by Z-Kaz** [comment]
Yeah, sorry about that. Here you go. Also it seems to be an issue specifically with animation smoothing as the issue stops when the plugin is turned of

https://user-images.githubusercontent.com/49293460/183559634-8bf04ffc-e95e-4c46-9543-13c6086fcffe.mp4

**Comment by Nightfirecat** [comment]
This appears to have been a Jagex bug, and was fixed [in today's update](https://secure.runescape.com/m=news/tombs-of-amascut?oldschool=1):

> Werewolves are now less jittery.
