### ISSUE TITLE
Highlight agility shortcuts in Meiyerditch Laboratories

### ISSUE THREAD

**Issue by eemkukko** [runelite/runelite#15461]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The level 74 and 93 agility shortcuts in Meiyerditch Laboratories, leading to the true blood altar, are currently not being highlighted by the agility plugin.

### Screenshots or videos

![blood_altar_shortcuts](https://user-images.githubusercontent.com/56926061/183496597-de32ec3a-9074-4ccc-a58a-e4f1e78ee832.png)

### RuneLite version

RuneLite version: 1.8.30
Launcher version: 2.4.2

**Comment by raiyni** [comment]
Added in https://github.com/runelite/runelite/commit/f72a8ab50bf56676f4dfc410b09629433d2b3bf4
