### ISSUE TITLE
Death Animation Bug

### ISSUE THREAD

**Issue by jukeboxbrass17** [runelite/runelite#15471]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

killin kq p2 it dies
but it doesnt die
skip 2 around 2:40
to see me coming bak

### Screenshots or videos

https://youtu.be/VAI180AoyVQ

### RuneLite version

https://i.imgur.com/RUYhnvL.png

**Comment by Nightfirecat** [comment]
Duplicate of #15394
