### ISSUE TITLE
[Prayer] Prayer bar is rendering under the character instead of above.

### ISSUE THREAD

**Issue by derektedor** [runelite/runelite#15473]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

Prayer bar is rendering under character instead of above as of 8/8/2022

### Screenshots or videos

![Uploading image.png…]()

### RuneLite version

RuneLite version: 1.8.30
Launcher version: 2.4.2

### Logs

[client.log](https://github.com/runelite/runelite/files/9295595/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9295597/launcher.log)

**Comment by geheur** [comment]
Do you have "Improved Tile Indicators" plugin and does the issue disappear if you disable that plugin?

**Comment by derektedor** [comment]
Yep, disabling that does indeed fix it, but it's not ideal. Should I open an issue there?

**Comment by geheur** [comment]
@derektedor yes https://github.com/LeikvollE/tileindicators/issues
