### ISSUE TITLE
Unable to click ingame when recieving loot/loading up panel.

### ISSUE THREAD

**Issue by Casesos** [runelite/runelite#15491]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I discovered it when receiving a drop the client will "hang" or consume clicks unsure,
I am able to replicate it using `loot logger` when loading up a log. 
See GIF for example,
I am spam clicking while it is loading up, it is the same behavior when receiving loot w/ loot panel.
Unsure if this is intentional but thought could be worth mentioning.

Uploaded Client.log in case there's something I can't see.

### Screenshots or videos

![RuneLite_BugReport](https://user-images.githubusercontent.com/90038205/184493530-1aad4917-abc4-4bf0-8bd6-410ad546d530.gif)

### RuneLite version

RuneLite Version: 1.8.30
Launcher Version: 2.4.2

### Logs

[client.log](https://github.com/runelite/runelite/files/9331393/client.log)

**Comment by geheur** [comment]
Is this the same as #14978?

**Comment by Nightfirecat** [comment]
Yes
