### ISSUE TITLE
Cannot drag Runelite window, can only resize

### ISSUE THREAD

**Issue by ewagsjr** [runelite/runelite#15504]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When I unmaximize the client to pull up 2 windows at a time, I cannot grab the application in order to place the window where I want it. 

### Screenshots or videos

https://user-images.githubusercontent.com/25017419/184720028-12bfb0fe-030f-4c04-84af-5ef498b0449b.mp4

### Logs

[launcher.log](https://github.com/runelite/runelite/files/9339879/launcher.log)
[client.log](https://github.com/runelite/runelite/files/9339880/client.log)

**Comment by Nightfirecat** [comment]
Your video did not upload so we can't see how this went wrong

**Comment by ewagsjr** [comment]
@Nightfirecat updated. my apologies

**Comment by ewagsjr** [comment]
Updated windows and cleared client cache with no luck.

**Comment by MESLewis** [comment]
Uninstall the "Client Anti Drag" plugin which prevents moving the client.
