### ISSUE TITLE
Default Fishing Plugin Not Displaying Tiles

### ISSUE THREAD

**Issue by matt-buckley** [runelite/runelite#15501]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Default Fishing plugin is not displaying tile overlays. I have no other plugins installed bar 117 HD, and the issue still shows up even when it's disabled. I've tried reinstalling and deleting the cache and nothing seems to work. Issue is the same as described at https://github.com/runelite/runelite/issues/7750 but is meant to have been patched some time ago. Any ideas?

### Screenshots or videos

![WhatsApp Image 2022-08-15 at 1 02 33 AM](https://user-images.githubusercontent.com/29579469/184662847-e13bd403-68fa-499a-a0f3-3af0246c4ef4.jpeg)
Screenshot of OSRS Mobile which displays what behaviour should look like

![WhatsApp Image 2022-08-15 at 1 02 39 AM](https://user-images.githubusercontent.com/29579469/184662986-715e1327-8a30-4dba-8190-85a68649ef1c.jpeg)
What is displayed by RuneLite

### RuneLite version

RuneLite version: 1.8.30
Launcher version: 2.4.5

### Logs

[client.log](https://github.com/runelite/runelite/files/9338135/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9338136/launcher.log)

**Comment by Nightfirecat** [comment]
This is specific to the fishing spots in Camdozaal, which we don't have support built in to the fishing plugin for yet. Generally though, you need to have a fishing tool in your inventory for the spots to be highlighted with the plugin, so other spots you see should work fine.

For whoever implements this, adding it will require adding the spot IDs to the FishingSpot enum with the appropriate name and item ID of the caught fish, then (in a separate commit) adding the appropriate world map spots for the fishing spot icons on the world map.

**Comment by matt-buckley** [comment]
Thanks, good to know. Worth noting I do have a fishing tool in my inventory in this screenshot.
