### ISSUE TITLE
Easy Clue: Search the bucket in the Port Sarim jail.

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#1551]
Bucket not highlighted w/ clue overlay, object listed in tooltip as null.
![Clue Image](https://vgy.me/qsHiqX.png)

**Comment by richardbadman** [comment]
This should be fixed from this [PR](https://github.com/runelite/runelite/pull/1383), if you wanna update your game and check? _(if you still have the clue scroll)_

**Comment by SomeZer0** [comment]
I don't have the clue still, sorry. Not using the Snapshot, if it was fixed in there.

**Comment by devLotto** [comment]
Fixed with #1383
