### ISSUE TITLE
Runelite crashes on mac

### ISSUE THREAD

**Issue by Jallah123** [runelite/runelite#15514]
### Type

Crash or hang

### Operating System

MacOS

### OS Version

macOS Monterey 12.3.1

### Bug description

Runelite seems to randomly crash. Happened a few times during different activities

### RuneLite version

Runelite version 1.8.30
Launcer version 2.1.5

### Logs

[client.log](https://github.com/runelite/runelite/files/9363954/client.log)
[jvm_crash_pid_55765.log](https://github.com/runelite/runelite/files/9363955/jvm_crash_pid_55765.log)
[jvm_crash_pid_76098.log](https://github.com/runelite/runelite/files/9363956/jvm_crash_pid_76098.log)
[jvm_crash_pid_86029.log](https://github.com/runelite/runelite/files/9363957/jvm_crash_pid_86029.log)
[launcher.log](https://github.com/runelite/runelite/files/9363958/launcher.log)

**Comment by Nightfirecat** [comment]
This is a GPU driver crash, there is likely nothing we can do to resolve it.

**Comment by keyosk** [comment]
@Jallah123 you're using an older version of the launcher which has an older version of Java which causes this issue.

To solve the problem you're seeing, download the latest launcher from the RuneLite website.

**Comment by Jallah123** [comment]
Updated to the latest launcher, I'll see if this will fix it. thanks
