### ISSUE TITLE
Menu entry swapper not working for teleports in spellbook, but working everywhere else.

### ISSUE THREAD

**Issue by 94Iris** [runelite/runelite#15534]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

trying to use menu entry swapper to shift click switch teleport destination on spells with multiple destinations, such as Grand exchange or Varrock, however the shift press is doing nothing. Shift click still works everywhere else I expect it to though.

### RuneLite version

RuneLite version 1.8.31
Launcher version 2.2.0

### Logs

[client.log](https://github.com/runelite/runelite/files/9391736/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9391738/launcher.log)

**Comment by Adam-** [comment]
I am able to swap the grand exchange teleport with both left and shift-click to the alternate site at both configurations of the spell correctly.

**Comment by mpowers93** [comment]
I don't even see NPC contact or teleport in the UI Swaps section of MES anymore. Did something get changed?

**Comment by Nightfirecat** [comment]
Read the UI Swaps section of the latest release blog post: https://runelite.net/blog/show/2022-08-21-1.8.31-Release

**Comment by mpowers93** [comment]
@Adam- https://github.com/runelite/runelite/commit/b5762ae86e151b6f5a6ecf17dbbd9aa766b96102 intentional removal?

**Comment by mpowers93** [comment]
> Read the UI Swaps section of the latest release blog post: https://runelite.net/blog/show/2022-08-21-1.8.31-Release

thank you. Missed that
