### ISSUE TITLE
Contract/Guildmaster Jane option gone from Menu Entry Swapper NPC options

### ISSUE THREAD

**Issue by bucketcat** [runelite/runelite#15537]
### Type

Other

### Operating System

Windows

### OS Version

Win 10

### Bug description

Contract/Guildmaster Jane option gone from Menu Entry Swapper NPC options. Noticed when my left click opened the dialogue box for the first time in years. Went into settings and sure enough, the setting is missing. It's still in the Github Wiki however.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/91589201/185932749-5a8b4063-1dc8-4cf6-b835-e9431b058d1e.png)

### RuneLite version

RuneLite version 1.8.31
Launcher version 1.6.0

**Comment by Enriath** [comment]
This was intentional. Use the customisable menu swaps (Items, NPC, Objects, and most UI works like this now)
![](https://cdn.discordapp.com/attachments/909197220883095653/994416998157127680/RuneLite_NuAlcrESdp.gif)
