### ISSUE TITLE
Party ping hotkey overrides chat

### ISSUE THREAD

**Issue by BelphisDewbub** [runelite/runelite#15543]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When setting the hotkey for the Ping setting in the Party plugin, this appears to override any interaction with chat. For example, if I set my Ping Hotkey to the letter Q, I cannot type Q in any chat window.

### RuneLite version

RuneLite version: 1.8.30
Oldschool revision: Rev 207
Launcher version: 2.1.3

**Comment by Nightfirecat** [comment]
How did you expect this to work? How would we know whether you wanted to type a `q` in chat versus ping?

**Comment by Nightfirecat** [comment]
Closing as no more information was provided.

**Comment by mfarrugi** [comment]
I ran into this earlier and struggled to figure out why my 'F' key wasn't working, especially since I wasn't actually using the party plugin at the time.

Potential fixes:
- Change default hotkey to something like Alt+F
- Disable when chatbox is focused
- Disable ping hotkey outside of a Party

**Comment by YvesW** [comment]
> I ran into this earlier and struggled to figure out why my 'F' key wasn't working, especially since I wasn't actually using the party plugin at the time.
> 
> Potential fixes:
> - Change default hotkey to something like Alt+F
> - Disable when chatbox is focused
> - Disable ping hotkey outside of a Party

The default party ping hotkey is unset (``Keybind.NOT_SET``). You put if on ``F`` yourself.
