### ISSUE TITLE
continual zuk timer

### ISSUE THREAD

**Issue by picklllle** [runelite/runelite#15546]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 10

### Bug description

it happens not of my doing.  automatically when i log in. started about a week ago.

### Screenshots or videos

![2022-08-23_12-25-49](https://user-images.githubusercontent.com/81590145/186279497-14060720-2185-4f0e-8901-0716950757d4.png)
![2022-08-23_12-25-44](https://user-images.githubusercontent.com/81590145/186279512-195a1a3c-0c09-4727-84a4-5fc9e46e437b.png)

**Comment by geheur** [comment]
This sounds like the set timer plugin. do you have that installed?

**Comment by Nightfirecat** [comment]
Support for hub plugins should be directed to the author of the plugin.
You can find the support link by searching for the plugin in the Plugin Hub panel and clicking the `?` button on the plugin, or by right-clicking the plugin in the plugin panel and clicking the `Support` menu option.
