### ISSUE TITLE
Java Heap Space (OOM)

### ISSUE THREAD

**Issue by BillyDas** [runelite/runelite#15555]
### Type

Crash or hang

### OS Version

Windows 10

### Bug description

During normal content on my 2k monitor i get lag that turns into freeze after a bit, cecked the log and have heaps of `java.lang.OutOfMemoryError: Java heap space` errors.. 
[client.log](https://github.com/runelite/runelite/files/9423964/client.log)

### RuneLite version

Unsure

### Logs

Supplied above

**Comment by Nightfirecat** [comment]
Since this issue was opened, we've made a number of changes which should reduce the amount of memory the client in general uses, which should address this issue. Let us know if it is still a problem for you.
