### ISSUE TITLE
Crashing and frame drops when loading game areas

### ISSUE THREAD

**Issue by Nildorff** [runelite/runelite#15553]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Consistent frame dropping and crashing.

Starting ~ 7 days ago, whenever I load new areas of the game (cox loading lines, all TOA rooms) my client either drops from 80 frames to sub 20, or just totally freezes and crashes.

I've reinstalled Runelite, updated Java, updated my graphics card drivers and rebooted my pc, nothing has fixed this behaviour.

### RuneLite version

1.8.32
2.4.5

### Logs

[client.log](https://github.com/runelite/runelite/files/9422852/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9422853/launcher.log)

**Comment by Bram91** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

**Comment by Nildorff** [comment]
This is an issue
