### ISSUE TITLE
Freezing consistently in Tombs of Amascut at Kephri room 

### ISSUE THREAD

**Issue by rw377** [runelite/runelite#15550]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10, 64 bit

### Bug description

When playing the Tombs of Amascut raid, during the Kephri room, I begin to lose FPS drastically to the point where Runelite eventually completely freezes to the point where I can't even drag the window around. This has happened both times I got to this room in the raid now.  I had to kill the process via task manager both times and re-open Runelite. There is no jvm_crash_pid log.  Seems like some type of memory leak but I could be wrong. Issue starts to happen about 1 min 5 seconds into video. 

PC Specs:
CPU: Intel i9-9900k
Memory: 32 GB, DDR43200 
GPU:  RTX 3080

For log reference, the first crash was at 10:50 am. The second was at around 11:48 am. 

### Screenshots or videos

Video: https://drive.google.com/file/d/10i49h2lz62T3jW0UgmMpACVvwmbyWiic/view?usp=sharing

### RuneLite version

Runelite: 1.8.32
Oldschool rev: Rev 207
Launcher: 2.3.0

### Logs

[launcher.log](https://github.com/runelite/runelite/files/9417684/launcher.log)
[client.log](https://github.com/runelite/runelite/files/9417685/client.log)

Looks like the issue is:
`2022-08-24 10:50:12 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2022-08-24 10:50:12 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
2022-08-24 10:50:12 [D3D Screen Updater] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/sun.java2d.d3d.D3DScreenUpdateManager.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by aHooder** [comment]
Could you see if you can reproduce this with no plugin hub plugins? To temporarily disable all hub plugins, you can run in safe mode with the following command: `"%localappdata%\runelite\runelite.exe" --clientargs --safe-mode`

**Comment by rw377** [comment]
> Could you see if you can reproduce this with no plugin hub plugins? To temporarily disable all hub plugins, you can run in safe mode with the following command: `"%localappdata%\runelite\runelite.exe" --clientargs --safe-mode`

I run this command (see below) in explorer and RL launches, but all of my plugins are still enabled.. Am I doing something wrong/is there another way to enable safemode? 
C:\Users\XXXX\AppData\Local\RuneLite\runelite.exe --clientargs --safe-mode

**Comment by aHooder** [comment]
It should only disable GPU plugins and hub plugins. I don't know if you can run this in explorer. Maybe try cmd.exe or win + R instead?

**Comment by Enriath** [comment]
I'd hazard a guess and say that this is the HD plugin causing issues.

The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
