### ISSUE TITLE
Resizable Modern Layout stretching

### ISSUE THREAD

**Issue by Adam7e72** [runelite/runelite#15578]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Stretching the window while in this mode moves the bottom bar. 

### Screenshots or videos

![image](https://user-images.githubusercontent.com/112408931/187228200-fab6a7fb-fac0-4903-b0ea-65d7176cf49c.png)
![image](https://user-images.githubusercontent.com/112408931/187228307-18405159-7d99-4f41-aab7-3485f9ef47e6.png)

### RuneLite version

1.8.32.1
2.1.7

**Comment by Enriath** [comment]
RL overlays and many Jagex widgets can be moved around the screen by holding the `Drag` Hotkey, (default: Alt) configurable in "RuneLite" settings, and left click dragging it around the screen.
Some overlays can be resized by dragging their bounds, right clicking will also reset their size and position.
They can also contain additional options, such as opening the config of the plugin that makes them, which can be discovered by shift right clicking.

The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

**Comment by Adam7e72** [comment]
Thanks for the response!
