### ISSUE TITLE
MES: some shift swaps not working with shift drop disabled

### ISSUE THREAD

**Issue by emiljensen2** [runelite/runelite#15582]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

If you have shift click drop disabled in osrs settings then some shift click swaps won't work on items in inventory, release on chins, and destroy on the water container in the zebac puzzle room is some I've noticed

### RuneLite version

Runelite 1.8.32.1
Launcher 2.4.2

**Comment by Enriath** [comment]
This is intended. Our shift-click stuff modifies how the vanilla shift-drop system works. If you don't want to drop an item while holding shift, you can shift right click the item and set something else to happen instead.

**Comment by emiljensen2** [comment]
So this bug is intended? Everything else works with shift click drops disabled, it's only these specific options on these items and possibly other items.
I can successfully set an item to shift click drop using mes and it'll work just fine.

some shift swaps simply don't work when set if you've set the game's shift click drop option to disabled.
>disable shift click drop in game settings
>shift right click chins and set them to release when holding shift
>doesn't work

Unfortunately your bandaid won't work for me since I'd have to swap the shift click on every item in the game then to avoid the game dropping my items when shift is not held.
