### ISSUE TITLE
severe lagging/stuttering/freezing/skipping

### ISSUE THREAD

**Issue by bellisonoroff** [runelite/runelite#15597]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Seems to be after toa release this bug started. awful freezing but its clientwide, cant click or type when it happens. nothing to do with latency. seems like runelite just skips really hard. have uninstalled and reinstalled, redownloaded and installed, adjusted and disabled plugins, disabled hardware acceleration, uninstalled and disabled programs like msi and rivatuner. tried various settings in nvidia control panel, disabled any OCs, etc. bug seems to come and go without any clear reason. sometimes relaunching the client gives me an hour of no bug time, sometimes there is nothing i can do.

not that it matters but 3080 and i7 8700 16gb ddr4 on a m.2 so thats not an issue. nothing changed on my pc end.

### Screenshots or videos

https://user-images.githubusercontent.com/95214548/187763696-082ddd96-4b58-42fd-a6a2-4f67cc0e8029.mp4

https://user-images.githubusercontent.com/95214548/187763737-7925a6cc-c07d-4485-b314-135d9e8c3cb9.mp4

https://user-images.githubusercontent.com/95214548/187763768-1484a0da-9d8b-4820-a3af-cd3a519d23c9.mp4

### RuneLite version

runelite 1.8.32.2
launcher 2.4.5

### Logs

[client_2022-08-09.0.log](https://github.com/runelite/runelite/files/9464379/client_2022-08-09.0.log)
[client_2022-08-10.0.log](https://github.com/runelite/runelite/files/9464380/client_2022-08-10.0.log)
[client_2022-08-11.0.log](https://github.com/runelite/runelite/files/9464381/client_2022-08-11.0.log)
[client_2022-08-12.0.log](https://github.com/runelite/runelite/files/9464382/client_2022-08-12.0.log)
[client_2022-08-13.0.log](https://github.com/runelite/runelite/files/9464383/client_2022-08-13.0.log)
[client_2022-08-14.0.log](https://github.com/runelite/runelite/files/9464384/client_2022-08-14.0.log)
[client_2022-08-15.0.log](https://github.com/runelite/runelite/files/9464385/client_2022-08-15.0.log)
[client_2022-08-16.0.log](https://github.com/runelite/runelite/files/9464386/client_2022-08-16.0.log)
[client_2022-08-17.0.log](https://github.com/runelite/runelite/files/9464387/client_2022-08-17.0.log)
[client_2022-08-18.0.log](https://github.com/runelite/runelite/files/9464388/client_2022-08-18.0.log)
[client_2022-08-19.0.log](https://github.com/runelite/runelite/files/9464389/client_2022-08-19.0.log)
[client_2022-08-20.0.log](https://github.com/runelite/runelite/files/9464390/client_2022-08-20.0.log)
[client_2022-08-21.0.log](https://github.com/runelite/runelite/files/9464391/client_2022-08-21.0.log)
[client_2022-08-22.0.log](https://github.com/runelite/runelite/files/9464392/client_2022-08-22.0.log)
[client_2022-08-23.0.log](https://github.com/runelite/runelite/files/9464393/client_2022-08-23.0.log)
[client_2022-08-24.0.log](https://github.com/runelite/runelite/files/9464394/client_2022-08-24.0.log)
[client_2022-08-25.0.log](https://github.com/runelite/runelite/files/9464395/client_2022-08-25.0.log)
[client_2022-08-26.0.log](https://github.com/runelite/runelite/files/9464396/client_2022-08-26.0.log)
[client_2022-08-27.0.log](https://github.com/runelite/runelite/files/9464397/client_2022-08-27.0.log)
[client_2022-08-28.0.log](https://github.com/runelite/runelite/files/9464398/client_2022-08-28.0.log)
[client_2022-08-29.0.log](https://github.com/runelite/runelite/files/9464399/client_2022-08-29.0.log)
[client_2022-08-30.0.log](https://github.com/runelite/runelite/files/9464400/client_2022-08-30.0.log)
[launcher.log](https://github.com/runelite/runelite/files/9464401/launcher.log)
[launcher_2022-08-01.0.log](https://github.com/runelite/runelite/files/9464402/launcher_2022-08-01.0.log)
[launcher_2022-08-03.0.log](https://github.com/runelite/runelite/files/9464403/launcher_2022-08-03.0.log)
[launcher_2022-08-04.0.log](https://github.com/runelite/runelite/files/9464404/launcher_2022-08-04.0.log)
[launcher_2022-08-05.0.log](https://github.com/runelite/runelite/files/9464405/launcher_2022-08-05.0.log)
[launcher_2022-08-06.0.log](https://github.com/runelite/runelite/files/9464406/launcher_2022-08-06.0.log)
[launcher_2022-08-07.0.log](https://github.com/runelite/runelite/files/9464408/launcher_2022-08-07.0.log)
[launcher_2022-08-08.0.log](https://github.com/runelite/runelite/files/9464409/launcher_2022-08-08.0.log)
[launcher_2022-08-09.0.log](https://github.com/runelite/runelite/files/9464410/launcher_2022-08-09.0.log)
[launcher_2022-08-10.0.log](https://github.com/runelite/runelite/files/9464411/launcher_2022-08-10.0.log)
[launcher_2022-08-11.0.log](https://github.com/runelite/runelite/files/9464412/launcher_2022-08-11.0.log)
[launcher_2022-08-12.0.log](https://github.com/runelite/runelite/files/9464413/launcher_2022-08-12.0.log)
[launcher_2022-08-13.0.log](https://github.com/runelite/runelite/files/9464414/launcher_2022-08-13.0.log)
[launcher_2022-08-14.0.log](https://github.com/runelite/runelite/files/9464415/launcher_2022-08-14.0.log)
[launcher_2022-08-15.0.log](https://github.com/runelite/runelite/files/9464416/launcher_2022-08-15.0.log)
[launcher_2022-08-16.0.log](https://github.com/runelite/runelite/files/9464417/launcher_2022-08-16.0.log)
[launcher_2022-08-17.0.log](https://github.com/runelite/runelite/files/9464418/launcher_2022-08-17.0.log)
[launcher_2022-08-18.0.log](https://github.com/runelite/runelite/files/9464419/launcher_2022-08-18.0.log)
[launcher_2022-08-19.0.log](https://github.com/runelite/runelite/files/9464420/launcher_2022-08-19.0.log)
[launcher_2022-08-20.0.log](https://github.com/runelite/runelite/files/9464421/launcher_2022-08-20.0.log)
[launcher_2022-08-21.0.log](https://github.com/runelite/runelite/files/9464423/launcher_2022-08-21.0.log)
[launcher_2022-08-22.0.log](https://github.com/runelite/runelite/files/9464424/launcher_2022-08-22.0.log)
[launcher_2022-08-23.0.log](https://github.com/runelite/runelite/files/9464425/launcher_2022-08-23.0.log)
[launcher_2022-08-24.0.log](https://github.com/runelite/runelite/files/9464426/launcher_2022-08-24.0.log)
[launcher_2022-08-25.0.log](https://github.com/runelite/runelite/files/9464427/launcher_2022-08-25.0.log)
[launcher_2022-08-26.0.log](https://github.com/runelite/runelite/files/9464428/launcher_2022-08-26.0.log)
[launcher_2022-08-27.0.log](https://github.com/runelite/runelite/files/9464429/launcher_2022-08-27.0.log)
[launcher_2022-08-28.0.log](https://github.com/runelite/runelite/files/9464430/launcher_2022-08-28.0.log)
[launcher_2022-08-29.0.log](https://github.com/runelite/runelite/files/9464431/launcher_2022-08-29.0.log)
[launcher_2022-08-30.0.log](https://github.com/runelite/runelite/files/9464433/launcher_2022-08-30.0.log)
[client.log](https://github.com/runelite/runelite/files/9464434/client.log)
[client_2022-08-01.0.log](https://github.com/runelite/runelite/files/9464435/client_2022-08-01.0.log)
[client_2022-08-03.0.log](https://github.com/runelite/runelite/files/9464436/client_2022-08-03.0.log)
[client_2022-08-04.0.log](https://github.com/runelite/runelite/files/9464437/client_2022-08-04.0.log)
[client_2022-08-05.0.log](https://github.com/runelite/runelite/files/9464439/client_2022-08-05.0.log)
[client_2022-08-06.0.log](https://github.com/runelite/runelite/files/9464440/client_2022-08-06.0.log)
[client_2022-08-07.0.log](https://github.com/runelite/runelite/files/9464443/client_2022-08-07.0.log)
[client_2022-08-08.0.log](https://github.com/runelite/runelite/files/9464445/client_2022-08-08.0.log)

**Comment by Adam-** [comment]
If you disable 117hd, reboot your client, and then don't use 117hd, does that fix it?

**Comment by bellisonoroff** [comment]
> 

unfortunately not, still happening with 117hd turned off after restarting computer

**Comment by Adam-** [comment]
If you can get a heap dump using the debug helper plugin from the pluginhub when it is freezing, that would be useful

**Comment by bellisonoroff** [comment]
> ### github doesnt support that filetype

**Comment by bellisonoroff** [comment]
> If you can get a heap dump using the debug helper plugin from the pluginhub when it is freezing, that would be useful

how can i share that with you? not hip on the norms on github

**Comment by Adam-** [comment]
Join `#support` on https://runelite.net/discord and ping me there

**Comment by Nightfirecat** [comment]
Since this issue was opened, we've made a number of changes which should reduce the amount of memory the client in general uses, which should address this issue. Let us know if it is still a problem for you.

For some more information, you can read the blog post we published on it here: https://runelite.net/blog/show/2022-09-04-recent-performance-regressions-and-tombs-of-amascut
