### ISSUE TITLE
exp tracker shared exp not displaying kills to level correctly

### ISSUE THREAD

**Issue by dec0yable** [runelite/runelite#15613]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When using a shared exp attack style, the exp tracker plugin displays the kills to level as if you are using a non- shared combat style. i.e. it still counts 4 exp per dmg done instead of 1.33 exp.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/406517/188309192-dface719-f777-4fc2-ae62-de7b45057bdd.png)

**Comment by Alexsuperfly** [comment]
duplicate of #6479
