### ISSUE TITLE
Essence Pouch doesn't display Normal Essence

### ISSUE THREAD

**Issue by Jademalo** [runelite/runelite#15626]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When adding Rune Essence rather than Pure Essence to an Essence Pouch, the counter stays at 0 regardless of how many are added.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/386846/188943914-72dfc24b-a693-4386-8910-472113583b0c.png)

### RuneLite version

RuneLite version: 1.8.32.4
Launcher version: 2.4.5

**Comment by Enriath** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.

**Comment by Jademalo** [comment]
Oh apologies, I thought this was a native plugin.
