### ISSUE TITLE
Slayer gem overlay firestaff for fire giants?

### ISSUE THREAD

**Issue by richardbadman** [runelite/runelite#1562]
Not really a major thing, but would require a little fix, will personally look at it later today but thought I'd log it as an issue anyway. 
<img width="80" alt="screen shot 2018-04-15 at 12 32 25" src="https://user-images.githubusercontent.com/6727336/38778360-88844834-40b0-11e8-97ff-64beade90c46.png">

**Comment by HypoxiaOSRS** [comment]
The itemID for Fire giants doesn't exist it seems. The itemID is for most of the Slayer Monsters are pulled straight from the Slayer Guide so for the rest of the monsters that can be assigned, objects of close resemblance or thought are in their place, Eg - Ghost have the Ghostspeak Amulet. 

![idea64_2018-04-16_16-34-42](https://user-images.githubusercontent.com/38278943/38833989-157deeea-4195-11e8-9257-b125905330af.png)

**Comment by deathbeam** [comment]
As there is no in-game icon for fire giants, we decided to use this
