### ISSUE TITLE
Can't install Runelite on Windows VM (Parallels) on Macbook M1 processor

### ISSUE THREAD

**Issue by niels0005** [runelite/runelite#15623]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11 > through Parallels VM running on MacOS Monterey (M1 chip)

### Bug description

I have installed Windows 11 Home. I'm on a Macbook Pro (M1, 2021) using Monterey (12.5.1) and the latest version of Parallels Desktop.

I am trying to install the latest runelite client (trying both x32 and x64), but I get the following error when I try to run the installer executable: "This program can only be installed on versions of Windows designed for the following processor architectures: x86 x64". I'm not sure why I'm getting this error. When I check the System Info in Windows 11, under System Type it reads "64-bit operating system, ARM-based processor".

**A similar issue is discussed on another forum and someone gave the below reply, which eventually fixed the problem after contact with the devs fixed the issue: Reply:**

"Windows on ARM can emulate both x86 and x64 software (not drivers, though), but it looks like the program you are trying to install is checking the architecture before you can even install it. If the software requires the installation of drivers, it would make sense to prevent the installation. Otherwise I can't think of a good reason to prevent the installation and the developers of the software should just remove that architecture check."

_Source: https://forum.parallels.com/threads/articy-requiring-windows-processor-architecture-x86-x64.357253/_

Is it as simple as reworking the installation check? Because it doesn't make sense to me that Runelite can't run on a Windows installation through Parallels. Really hope this could be resolved <3

### Screenshots or videos

![Screenshot 2022-09-06 203512](https://user-images.githubusercontent.com/14327985/188713589-a5116c70-8c64-4a4a-adc0-447c79c4f105.png)

**Comment by niels0005** [comment]
OSRS through the regular client launches without problems on Windows 11 (via Parallels), proof: 
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/14327985/188715538-47b27e53-b3ba-4fb4-adea-498909db95e7.png">

**Comment by TzZek** [comment]
I believe this is because RuneLite doesn't have an ARM image. You should be able to install java and use the jar file via Windows Terminal. java -jar RuneLite.jar , after installing the JRE. 

I haven't tested this personally but I've only got VMWare Fusion to test with.

**Comment by Felanbird** [comment]
ARM builds were added at some point in the past 2 years
![image](https://github.com/user-attachments/assets/b58da431-6df9-45fd-84d5-d60501a81b24)
