### ISSUE TITLE
Runelite Crash (Array index out of bounds)

### ISSUE THREAD

**Issue by sketchyfresh** [runelite/runelite#15631]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Win10

### Bug description

I've had this crash a few times, all seemingly random. 
My client will freeze, and i'll get a pop-up message saying 'runelite has crashed'. This time I was solo'ing DK's in the slayer lair when it happened. Bad timing! 

I made a dropbox link if you'd like to look at the whole log. ----> https://www.dropbox.com/s/190gh40gxoak51a/client.log?dl=0

Here is the error I copy and pasted from my log when the client crashed.

> 2022-09-07 18:40:14 [Client] ERROR client-patch - Client error: null
java.lang.ArrayIndexOutOfBoundsException: Index 17160437 out of bounds for length 483481
	at qn.e(qn.java:441)
	at qn.p(qn.java:432)
	at ff.if(ff.java:10098)
	at ff.if(ff.java:9930)
	at ff.if(ff.java:9930)
	at bb.iv(bb.java:9788)
	at client.fr(client.java:4391)
	at client.ar(client.java:1128)
	at ab.e(ab.java:388)
	at ab.run(ab.java:342)
	at java.base/java.lang.Thread.run(Unknown Source)

Any kind of help would be much appreciated! Please let me know if you need more info, my discord is Kadez#3476

### Logs

[client.log](https://github.com/runelite/runelite/files/9522175/client.log)

**Comment by sketchyfresh** [comment]
[jvm_crash_pid_16152.log](https://github.com/runelite/runelite/files/9612012/jvm_crash_pid_16152.log)

Here is a jvm crash log after runelite closed on me while playing. This happened while fighting supreme in DK's slayer lair. This is the 2nd time fighting Supreme the client ended (stopped and exited) while fighting Supreme, although its happened at other times and areas.

**Comment by Nightfirecat** [comment]
Can you reproduce this while running in safe mode?

> Windows: In Command Prompt, run:
>
>     "%localappdata%\runelite\runelite.exe" --clientargs --safe-mode
>
> Mac: In Terminal, run:
>
>     /Applications/RuneLite.app/Contents/MacOS/RuneLite --clientargs --safe-mode

**Comment by sketchyfresh** [comment]
I will run runelite In safe mode tonight Jordan. Thank you for reaching
out. My problem seems quite random, as it could happen again today, or in 2
days. I remember specifically my client has closed on me twice while
fighting supreme in DK’s lair, both times giving me a crash error. The most
recent time was blood runecrafting at arceuus. Just mining essence and my
client closed. This time no error popup.

I’ve already deleted all third party plug-ins from the hub, and tried to
minimize the amount of default plugins enabled while I play.

Should I turn off the GPU plugin also?

**Comment by sketchyfresh** [comment]
Hey Jordan, I’ve been playing in safe mode, making sure my gpu is disabled,
and my client will still randomly close and give me array index out of
bounds errors. I did some more research and have seen ryzen CPU’s have been
known to give array index errors with Java? Have you heard of this?
I’ve re-downloaded runelite, my chipset drivers, and deleted all overlay
software like GeForce experience etc.

**Comment by Alexsuperfly** [comment]
can you provide logs from the instances when you were running in safe-mode and also crashed

**Comment by Nightfirecat** [comment]
Let us know if you get crash logs from running in safe mode.
