### ISSUE TITLE
Side panel doesn't open when in plugin hub and search bar is filled

### ISSUE THREAD

**Issue by rorro** [runelite/runelite#15630]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 7

### Bug description

If the plugin hub is open and you fill in anything into the search bar, the side panel doesn't open after closing it. It requires an additional close and open. That clears the search bar and allows it to open again. This happens both with custom window chrome and without.

It's not just lag with opening the panel, it can seem that way because the attached gif is very short. The side panel stays closed.

### Screenshots or videos

![explorer_tHX6GBa1oC](https://user-images.githubusercontent.com/5983417/188997598-00917829-cbf4-4a69-a616-06d4b451814e.gif)

### RuneLite version

RuneLite version: 1.8.32.4
Launcher version: 2.1.3

### Logs

[client.log](https://github.com/runelite/runelite/files/9522121/client.log)

**Comment by Nightfirecat** [comment]
Fixed in e976d5b3ab21ffcaeeeede901a567d63e2fd0d39
