### ISSUE TITLE
World Hopper doesn't show my ping to worlds or current ping while connected via ethernet

### ISSUE THREAD

**Issue by Smench** [runelite/runelite#15644]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

Monterey 12.5.1

### Bug description

When connected to the internet via ethernet, world hopper does not display my ping to any of the worlds. This is reproducible by unplugging my ethernet connection and switching to wifi and then having my ping shown. Once plugged back into a direct connection, the ping is gone.

### RuneLite version

RuneLite version: 1.8.33
Launcher version: 2.4.4

### Logs

[client.log](https://github.com/runelite/runelite/files/9531295/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9531298/launcher.log)

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
