### ISSUE TITLE
[Logout Timer] wiki reference leads to 404

### ISSUE THREAD

**Issue by Zarthus** [runelite/runelite#15656]
### Type

Other

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Pressing "wiki" on the plugin Logout Timer brings you to the wrong page.

It brings you to [Wiki Page for "Logout-Timer"](https://github.com/runelite/runelite/wiki/Logout-Timer) (img 1) which then redirects you to the [home wiki](https://github.com/runelite/runelite/wiki/) (img 2) with the message `You do not have permission to update this wiki.`

### Screenshots or videos

1. Pressing "Wiki" in runelite

![image](https://user-images.githubusercontent.com/3660408/189519085-836304d7-be97-4a51-8f54-b854f2a5a851.png)

2. The error page

![image](https://user-images.githubusercontent.com/3660408/189519119-0f5089f1-72bb-4757-aaef-7625d4e5840a.png)

### RuneLite version

Runelite 1.8.33
Rev 208
Launcher 2.4.2

**Comment by geheur** [comment]
I added a wiki page for that plugin.

The wiki was made uneditable to prevent vandalism, the only way to edit it is to make a pull request at https://github.com/runelite/wiki

**Comment by Zarthus** [comment]
It's uneditable, but it's also not viewable, is that also what you meant to do with it? @geheur
