### ISSUE TITLE
Ladder and target markers appear in random places and multiply

### ISSUE THREAD

**Issue by Tobias11007** [runelite/runelite#15665]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windiws 10 Pro

### Bug description

Over time, the green shaded area markers indicating ladders and drawers appear in locations far away from their true locations. The longer you use the plugin the more of these incorrect markers show up (see screenshot). Logging out and back in briefly fixes this before starting again

### Screenshots or videos

![ArtefactPluginBug](https://user-images.githubusercontent.com/63586244/189999561-2234f5e1-ea0c-43a0-a96b-6494bc6b8b4f.PNG)

### RuneLite version

Runelite Version: 1.8.33
Oldschool rev: Rev 208
Launcher Version: 2.4.2

**Comment by Enriath** [comment]
Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
