### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by melxin** [runelite/runelite#15694]
### Type

Incorrect behavior

### Operating System

Any

### OS Version

Any

### Bug description

When you die the error pops-up, also tested in safe-mode.

### Screenshots or videos

![Screenshot from 2022-09-18 13-41-14](https://user-images.githubusercontent.com/112344529/190900553-c7912ce7-f397-453e-9627-095a626c5af8.png)

### RuneLite version

All versions after rev-208 update

### Logs

[client.log](https://github.com/runelite/runelite/files/9594131/client.log)

**Comment by Nightfirecat** [comment]
Please upload your log file, not just a screenshot of it

**Comment by melxin** [comment]
The error is the same
