### ISSUE TITLE
Can't Load or Switch Worlds

### ISSUE THREAD

**Issue by Dominierenn** [runelite/runelite#15709]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

When I click the World Tab, it just says 'Loading...' & won't do anything. It does the same thing when I'm logged in, trying to switch worlds as well.

**Comment by Enriath** [comment]
This just means you have a bad connection to Jagex.

For further questions of support, please join the [Discord](https://runelite.net/discord)
