### ISSUE TITLE
ITS NOT EVEN STARTING

### ISSUE THREAD

**Issue by aur1melis** [runelite/runelite#15708]
### Type

Crash or hang

### Operating System

Windows

### Bug description

It loads but its not start

### Screenshots or videos

![image](https://user-images.githubusercontent.com/114051803/191425802-75a0640d-246f-446d-9295-39912908a7df.png)

**Comment by Jesse-Lucas1996** [comment]
This tells us nothing, Can you give us some type of log?

**Comment by Enriath** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
