### ISSUE TITLE
Client not loading, stuck at 3,4 MiB Retrieving client

### ISSUE THREAD

**Issue by goedgaras** [runelite/runelite#15705]
### Type

Crash or hang

### Operating System

Windows

### Bug description

Good day,
Have a problem with runelite. My Runelite stops loading at this point and nothing happening. Tried to run as administrator, reinstall, reinstall Java, disabled Eset. No further information on web...

### Screenshots or videos

![555](https://user-images.githubusercontent.com/94706095/191302386-79fbedc8-f728-42b5-b4c2-358c9f0237da.PNG)

**Comment by Enriath** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
