### ISSUE TITLE
Diary Requirements Plugin Not Working

### ISSUE THREAD

**Issue by cpg-osrs** [runelite/runelite#15710]
### Type

Performance

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Plugin not working, not showing requirements for diaries

### Screenshots or videos

![image](https://user-images.githubusercontent.com/114083146/191517626-6222e1d5-9c65-47cf-b6db-a9ec4824d7e0.png)

### RuneLite version

Runelite version: 1.8.33.1
Revision: Rev 208
Launcher version: 2.3.0

**Comment by DLCorazon** [comment]
![image](https://user-images.githubusercontent.com/114110920/191605422-00350b72-712d-4a11-85a8-1e4b0cd7c724.png)


Having the same issue. Same versions of both RuneLite and launcher
