### ISSUE TITLE
RuneLite Error: failed to load VM runtime library!

### ISSUE THREAD

**Issue by Adam199711** [runelite/runelite#15719]
### Type

Other

### Operating System

MacOS

### OS Version

Yosemite

### Bug description

Noticed RuneLite wasn't working so I've reinstalled and now can't open the application. I am receiving an error saying "Error: failed to load VM runetime library!".

Would be quite grateful for any assistance.

Thanks

**Comment by Alexsuperfly** [comment]
Newer launchers no longer support Yosemite.  Use https://github.com/runelite/launcher/releases/download/2.4.2/RuneLite-x64.dmg to download the 2.4.2 version of the launcher for mac

**Comment by Adam199711** [comment]
That works, really appreciate it Alex!!
