### ISSUE TITLE
Opponent Info: null Opponent name

### ISSUE THREAD

**Issue by nrodrigues0213** [runelite/runelite#1572]
While fighting against the Temple guardian during Priest in Peril, the client is unable to retrieve the name of the dog.
![image](https://user-images.githubusercontent.com/25905465/38781839-343d0406-40b9-11e8-9816-367b275b05b5.png)

Due to how the client retrieves the data, it is my belief that there may be another source somewhere that includes special NPCs found in instanced areas like these. I'm completely ignorant of the underlying mechanics of the client, so I may be wrong.

**Comment by deathbeam** [comment]
I guess no reply means its not valid
