### ISSUE TITLE
Mage Training Arena Telekinetic Theatre Plugin

### ISSUE THREAD

**Issue by QrowsGaming** [runelite/runelite#15747]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10 64 Bit

### Bug description

After doing the first part of the puzzle it doesn't continue showing where to stand. happens after the first Telekinetic grab. Had a friend stream to me to confirm it was Runelite and not just Me/My system.

### Screenshots or videos

![Working](https://user-images.githubusercontent.com/114645749/192959470-aa583a28-0a15-4204-9437-7a677b71754e.jpg)
![Not Working](https://user-images.githubusercontent.com/114645749/192959487-d3976033-e369-4755-8d15-24333c0cc063.jpg)

**Comment by kamielvf** [comment]
This has been fixed in 6af244848326e2283c3a9a966b50d2bafa3c837e
