### ISSUE TITLE
Mage Training Arena - Telekinetic room not working 

### ISSUE THREAD

**Issue by Soulwinner12** [runelite/runelite#15752]
### Type

Performance

### Operating System

MacOS

### OS Version

MacOS Mojave 

### Bug description

The tile indicators are only working for the first cast of telekinetic grab - it then fails to highlight a new tile 

### RuneLite version

Runelite version 2.4.3

**Comment by Nightfirecat** [comment]
Duplicate of #15741. This has been fixed in 6af244848326e2283c3a9a966b50d2bafa3c837e but has not been released yet
