### ISSUE TITLE
Mage Training Arena - Telekinetic Room

### ISSUE THREAD

**Issue by EstNox** [runelite/runelite#15750]
### Type

Other

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The Magic Training Arena - Telekinectic Room is still not working after fix.
Already reported  #15749 but is still behaving the same way. Tiles and arrows does not show after casting the first spell.
Suppose to was fixed but it is very much still not fixed.

### RuneLite version

![image](https://user-images.githubusercontent.com/114663952/193019757-f94df6d3-f325-4e90-8d1c-e42c3023b88e.png)

**Comment by kamielvf** [comment]
This was fixed in 6af244848326e2283c3a9a966b50d2bafa3c837e but has not been released yet, please refrain from making duplicate issues and just comment on any of the other ones if you actually do find that it has not been resolved.
