### ISSUE TITLE
Super Combat Potion/Stat timer not working

### ISSUE THREAD

**Issue by Gagethemasaro** [runelite/runelite#15768]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Timers for stats increased by normal super combat potions is no longer displaying. It has not indicator on screen whatsoever. Checking the timers section of the plugins has not been any help, it seems that it was likely replaced for divine timers and overload timers?

### RuneLite version

RuneLite version: 1.9.0
Oldschool revision: Rev 208
Launcher version: 2.1.5

### Logs

[client.log](https://github.com/runelite/runelite/files/9717481/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9717482/launcher.log)

**Comment by Nightfirecat** [comment]
Stat timers were never a part of the timers plugin, they are part of the "Boosts Information" plugin. Some time ago, we updated the settings for it to allow multiple stat indicator overlays, which caused the setting selection to be reset for users. You can re-enable infoboxes via the "Display infoboxes" setting, and/or use either of the other displays that way.
