### ISSUE TITLE
Loot tracker multiplies loot on account switch

### ISSUE THREAD

**Issue by Juzzed** [runelite/runelite#15779]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

11

### Bug description

It seems that the loot is beeing multiplied (most of the times doubled sometimes tripled) on account switch. It seems that only the loot obtained on the same session is beeing multiplied.

Reproduced by:
Account A: kill NPC -> logout -> login to account B -> logout -> login to account A

### Screenshots or videos

https://youtu.be/HL3_j8p5TRM

### RuneLite version

RuneLite version: 1.9.0
Launcher version: 2.4.5

**Comment by Juzzed** [comment]
I looked through the code but cant seem to find whats wrong with it. 

But just an idea for now:

Step 1: Account A kills NPC -> loot tracker logs -> Account A logs off 
Step 2: Account B logs in -> loot tracker loads Account B loot -> loot tracker dosent clear loot from Account A -> Account B logs off
Step 3: Account A logs in -> lott tracker loads Account A loot from settings.properties on top of already loaded loot which has not been cleared from step 1 log off

**Comment by Adam-** [comment]
fixed in cd017aab55bde6853c27e86c62383bfcb8905b6f
