### ISSUE TITLE
[Minimap] With zoom enabled, hopping while looking through telescope adds black squares next to terrain

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#15771]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Manjaro Linux

### Bug description

Replication:
1) Enter Player-Owned House
2) Use Telescope
3) Hop worlds
4) Black squares appear on the minimap. These disappear and appear if the Minimap plugin zoom feature is toggled. They disappear permanently when the inventory tab is opened.

### Screenshots or videos

![2022-10-06-00-00-28](https://user-images.githubusercontent.com/33790641/194235602-9b6e72dd-037e-4a06-ab75-d8aabe5e2cb4.png)
![2022-10-06-00-00-22](https://user-images.githubusercontent.com/33790641/194235604-ae0950ea-444c-44f8-b754-9f68589097f0.png)

### RuneLite version

RuneLite version: 1.9.0
Launcher version: 2.5.0

### Logs

[client.log](https://github.com/runelite/runelite/files/9722069/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9722070/launcher.log)

**Comment by abextm** [comment]
This was already fixed internally
