### ISSUE TITLE
weird grey artefacts

### ISSUE THREAD

**Issue by light-mooner** [runelite/runelite#15789]
### Type

GPU

### Operating System

Windows

### OS Version

windows 21H2 + Ubuntu 22.04

### Bug description

i get weird grey artefacts when enabling 117 HD.

tried launching the game without HW acceleration, and disable all options inside the settings of the mod.
I also checked the anti aliasing option of my GPU driver, which is set to "use application settings"

Spec : 
32Go RAM
RX 6700 XT
Ryzen 7 5800X

also happens under linux systems.

i don't have the problem with the "GPU" addons on runelite

Those artefacts are constantly 'blinking' ( it's not fixed on the image, it's like 1hz refresh on the image, and appear somewhere else, constantly flashing ), image below

No problem on other games, GPU driver reinstalled

### Screenshots or videos

![image](https://user-images.githubusercontent.com/17829219/194743926-45694758-719f-4311-b2ae-845ea046639d.png)

### RuneLite version

Runelite : 1.9.0
Launcher :  2.4.2

### Logs

[launcher.log](https://github.com/runelite/runelite/files/9741001/launcher.log)
[client.log](https://github.com/runelite/runelite/files/9741002/client.log)

**Comment by Unmoon** [comment]
Visit 117's HD plugin discord (https://discord.com/invite/U4p6ChjgSE) for support, issues & feedback

**Comment by light-mooner** [comment]
![osrs-gpu-bug-compressed](https://user-images.githubusercontent.com/17829219/194744783-2c68588f-40d4-4588-8d68-3cd9a619456d.gif)

gif of the bug

**Comment by kamielvf** [comment]
For problems with plugin hub plugins please refer to their respective repository/discord. A link can be found within the client's plugin hub list by clicking on the ❔ icon.
