### ISSUE TITLE
Minimap Issue

### ISSUE THREAD

**Issue by Doughboy2783** [runelite/runelite#15781]
### Type

Other

### Operating System

Windows

### OS Version

windows 8

### Bug description

At times these little dark squares pop up on the mini map and then disappear.  I first noticed while doing barrows, but after that noticed it while using balloon to Varrock from castle wars, crafting orbs, even just walking around the map. It is quite annoying now.  I have tried removing the two plugins i had installed, which were quest helper and Zulrah helper, reinstalled runelite, logged out of runelite, update my pc, restarted pc multiple times and nothing fixed the issue.  This didn't start till after the update on Wednesday morning.  I did take screenshots. stuff like that happens all over the map not just the few locations I posted.

### Screenshots or videos

![2022-10-06_23-24-47](https://user-images.githubusercontent.com/71573626/194467893-be77ba09-7597-4eee-8bcc-c42e35c515d6.png)
![2022-10-06_23-12-13](https://user-images.githubusercontent.com/71573626/194467970-a22577a1-f256-4f40-a4f4-c7bfcedc6078.png)
![2022-10-06_23-32-30](https://user-images.githubusercontent.com/71573626/194468373-4245f604-e89c-469b-a917-04f6568779fc.png)

### RuneLite version

Runelite version 1.9.0
Launcher version 2.5.0

### Logs

[client.log](https://github.com/runelite/runelite/files/9730705/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9730707/launcher.log)

**Comment by abextm** [comment]
duplicate #15771
