### ISSUE TITLE
Ctrl clicking minimap with zoom enabled does not walk

### ISSUE THREAD

**Issue by Naosyth** [runelite/runelite#15784]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

11

### Bug description

Normally when holding ctrl and clicking on the minimap, your run state will be inverted e.g. walk instead of run or vice versa.

With minimap zoom enabled, this doesn't happen - holding ctrl and clicking on the minimap does not affect run/walk.

**Comment by Adam-** [comment]
this has been patched internally
