### ISSUE TITLE
Jewelry Enchanting UI

### ISSUE THREAD

**Issue by c5gaspar** [runelite/runelite#1579]
Wondering if it would be possible to have an inventory overlay to make enchanting easier on the eyes. Something along the lines of what OSBuddy has where there's translucent green/red boxes so you know which piece to click on next. 

Can't find a photo of the behaviour on OSBuddy (as its a Pro feature) but I can clarify further if necessary.

**Comment by Nicholas-Ingram** [comment]
Yeah I'll get onto it :D

**Comment by deathbeam** [comment]
We have inventory tags, and jagex added differentiating between enchanted and unenchanted jewellery already.
