### ISSUE TITLE
Sidebar glitching out even without hardware acceleration turned off.

### ISSUE THREAD

**Issue by vinstaal0** [runelite/runelite#15809]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I have had issues with Runelite's sidebar glitching out for a while now. I have tried it with and without hardware acceleration, tried it with both an AMD gpu (RX 590) and a Nvidia GPU (RTX 3060 ti) and both have had the issue. Have reinstalled my GPU drivers multiple times over the years and waiting for update after update and the issue still show up. (can't really upload a proper image, but the issue should be know since disabeling hardware acceleration fixes it)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/2960100/196041267-a4e6e5c8-151d-4e9b-b4c2-b1022e63f5c1.png)

### RuneLite version

Runelite Version: 1.9.1
Oldschool revision: Rev 209
Launcher version: 2.1.6

### Logs

[jvm_crash_pid_28420.log](https://github.com/runelite/runelite/files/9794835/jvm_crash_pid_28420.log)
[launcher.log](https://github.com/runelite/runelite/files/9794836/launcher.log)
[launcher_2022-09-24.0.log](https://github.com/runelite/runelite/files/9794837/launcher_2022-09-24.0.log)
[launcher_2022-10-05.0.log](https://github.com/runelite/runelite/files/9794838/launcher_2022-10-05.0.log)
[launcher_2022-10-06.0.log](https://github.com/runelite/runelite/files/9794839/launcher_2022-10-06.0.log)
[launcher_2022-10-07.0.log](https://github.com/runelite/runelite/files/9794840/launcher_2022-10-07.0.log)
[launcher_2022-10-08.0.log](https://github.com/runelite/runelite/files/9794841/launcher_2022-10-08.0.log)
[launcher_2022-10-10.0.log](https://github.com/runelite/runelite/files/9794842/launcher_2022-10-10.0.log)
[launcher_2022-10-11.0.log](https://github.com/runelite/runelite/files/9794843/launcher_2022-10-11.0.log)
[launcher_2022-10-12.0.log](https://github.com/runelite/runelite/files/9794844/launcher_2022-10-12.0.log)
[launcher_2022-10-13.0.log](https://github.com/runelite/runelite/files/9794845/launcher_2022-10-13.0.log)
[launcher_2022-10-14.0.log](https://github.com/runelite/runelite/files/9794846/launcher_2022-10-14.0.log)
[launcher_2022-10-15.0.log](https://github.com/runelite/runelite/files/9794847/launcher_2022-10-15.0.log)
[client.log](https://github.com/runelite/runelite/files/9794848/client.log)
[client_2022-09-24.0.log](https://github.com/runelite/runelite/files/9794849/client_2022-09-24.0.log)
[client_2022-10-05.0.log](https://github.com/runelite/runelite/files/9794850/client_2022-10-05.0.log)
[client_2022-10-06.0.log](https://github.com/runelite/runelite/files/9794851/client_2022-10-06.0.log)
[client_2022-10-07.0.log](https://github.com/runelite/runelite/files/9794852/client_2022-10-07.0.log)
[client_2022-10-08.0.log](https://github.com/runelite/runelite/files/9794853/client_2022-10-08.0.log)
[client_2022-10-10.0.log](https://github.com/runelite/runelite/files/9794854/client_2022-10-10.0.log)
[client_2022-10-11.0.log](https://github.com/runelite/runelite/files/9794855/client_2022-10-11.0.log)
[client_2022-10-13.0.log](https://github.com/runelite/runelite/files/9794856/client_2022-10-13.0.log)
[client_2022-10-14.0.log](https://github.com/runelite/runelite/files/9794857/client_2022-10-14.0.log)
[client_2022-10-15.0.log](https://github.com/runelite/runelite/files/9794858/client_2022-10-15.0.log)
[jvm_crash_pid_8132.log](https://github.com/runelite/runelite/files/9794859/jvm_crash_pid_8132.log)
[jvm_crash_pid_12500.log](https://github.com/runelite/runelite/files/9794860/jvm_crash_pid_12500.log)
[jvm_crash_pid_13936.log](https://github.com/runelite/runelite/files/9794861/jvm_crash_pid_13936.log)

**Comment by Alexsuperfly** [comment]
Update your launcher, version 2.4.0 added a blacklist of dlls identifed to cause this issue, preventing them from loading themselves into the client.

**Comment by vinstaal0** [comment]
> Update your launcher, version 2.4.0 added a blacklist of dlls identifed to cause this issue, preventing them from loading themselves into the client.

@Alexsuperfly nope that didn't seem to fix the issue

**Comment by Alexsuperfly** [comment]
the debug plugin on the hub has a method to dump natives, provide that file since you could have a dll not identified yet causing the issue.  I would suggest joining us on [discord](https://runelite.net/discord) though since it is easier to provide debugging assistance there.
