### ISSUE TITLE
Supplies Used Tracker does not track runes used by "String Jewellry" correctly

### ISSUE THREAD

**Issue by NoahTingey** [runelite/runelite#15810]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

MacOS 12.6

### Bug description

The "String Jewellry" spell takes 2 astral runes per cast. Clicking the spell once automatically casts the spell for each unstrung amulet in your inventory -- with each of these casts taking 2 astral runes. 

The Supplies Used Tracker plugin only counts the astral runes used by the first click, not the casts for each amulet strung. 

### Screenshots or videos

https://user-images.githubusercontent.com/94259127/196042696-4aaec9c2-7178-4ce7-ad82-b69f2375c116.mp4

### RuneLite version

RuneLite version 1.9.1
Oldschool revision: Rev 209
Launcher version: 1.6.1

**Comment by kamielvf** [comment]
For issues with plugin-hub plugins please refer to their respective [repository](https://github.com/pwatts6060/SuppliesTrackerExternal) and file your issue there.
