### ISSUE TITLE
World 316 always at top for world switcher

### ISSUE THREAD

**Issue by ragnarokatz** [runelite/runelite#15818]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

World 316 always is at top of the list for world switcher, regardless of which column I click on for filtering.
World 316 is not in my favorites list.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/33646954/196310691-0ae89715-89c9-4b6b-8c01-ad701c1b66e6.png)
![image](https://user-images.githubusercontent.com/33646954/196310708-7a8fad90-fdcf-4354-9492-37e3ebce701e.png)
![image](https://user-images.githubusercontent.com/33646954/196310731-0f407ac4-d8e1-4441-9258-12a30fc9de1f.png)

### RuneLite version

RuneLite version: 1.9.1
Launcher version: 2.3.0

### Logs

[client.log](https://github.com/runelite/runelite/files/9805496/client.log)

**Comment by Alexsuperfly** [comment]
you have it favorited in game
