### ISSUE TITLE
Idle Notifier not sending notifications

### ISSUE THREAD

**Issue by Zerkia** [runelite/runelite#15824]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Idle Notifier plugin not sending proper notifications for action requirements being met.

No notification pops up, upon an interaction ending (Used to say "You are now idle!"), however, said notification now pops up once an inventory is full, saying "You are now idle!" instead of "Your inventory is full!", almost as if some ID number is wrong and the wrong message is being sent or something.

EDIT: This has been happening while chopping blisterwoods. I noticed that one of the latest commits is a Blisterwood jump scare feature. Not sure if this could be the culprit, but wanted to mention my testing grounds.

### RuneLite version

RuneLite version: 1.9.2
Launcher version: 2.1.0

### Logs

[client.log](https://github.com/runelite/runelite/files/9833035/client.log)
[launcher.log](https://github.com/runelite/runelite/files/9833040/launcher.log)

**Comment by Nightfirecat** [comment]
According to your chat in our Discord support channel, this is specifically having to do with blisterwood idle notifications not firing; this is fixed in master in commit 12da1231c566fc0c29630bca77f0bb1dabea433d and will be fixed in our next release.
