### ISSUE TITLE
Maximised window doesn't fill whole screen when on a secondary monitor that has taskbar disabled

### ISSUE THREAD

**Issue by Ivy9217** [runelite/runelite#15871]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

On Windows 10

When Runelite is on a secondary monitor

And the Windows setting "Show taskbar on all displays" is disabled

A maximised Runelite window does not take up the entire screen. Instead, a blank space is left at the bottom, as if a taskbar was present.

### Screenshots or videos

![lnPlAocREo](https://user-images.githubusercontent.com/5096359/199212823-e64de874-7c1d-4ba8-b014-3f66261bfd2a.jpg)

### RuneLite version

1.9.3

**Comment by Adam-** [comment]
This is most likely fixed on the latest launcher version. Since you have omitted the launcher version completely from your report, I'm going to close this. Reopen if it is still an issue on 2.5.0.
