### ISSUE TITLE
Pest control bug

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#1592]
![image](https://user-images.githubusercontent.com/38350898/38824061-bc2f746e-41b0-11e8-9afb-a879d03fe809.png)
The 6% is supposed to be 0% I tried 3 games and it keeps bugging. It reaches 0% then automatically goes to 6%.. 

Also move the number (percentage to the left a little- it's currently next to the bar exactly.)

And I'll like to suggest to add more color/edits to the plugin.. And a simple calculator for the plugin.  
![image](https://user-images.githubusercontent.com/38350898/38824235-46bd03d0-41b1-11e8-8062-83373dea6dbd.png)

In the small red box on the left:

- Add a PEST CONTROL Box with the icon of pest control (Any which you see nice/worthy).
- Inside that box, you will show 3 things.  How many games you lost, how many games you won, and how many games left until you reach x points.

In order to make the small box, you need to add a simple calculator in the pest control plugin.. 
"How many points you need: *x* "

If you can't do the suggestions, please fix the bug.

**Comment by Floukru** [comment]
Also the percentage should be like this

```
Color color = Color.GREEN;
                 if (perc >= 26 && perc <= 60)
			color = Color.ORANGE;
		else if (perc < 25) {
			color = Color.RED;
		}

```

And the ATK NEXT tags on portals should be changed color to;

HOLD: Not attackable [red]
NEXT: Next to line [ORANGE]
ATK: Attackable [GREEN]

**Comment by raiyni** [comment]
This appears to have been fixed at some point.

**Comment by deathbeam** [comment]
Awesome!
