### ISSUE TITLE
Bank Tags - Tag Tabs - Bank Tag with single letter shows items tagged with a string beginning with that letter

### ISSUE THREAD

**Issue by hessrs** [runelite/runelite#15921]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When you have two bank tabs, one with a tag with a single letter, and the other with a string that _begins_ with that letter, the items tagged with said full string appear in the single letter tab.

Example:

Bank tab 1: Items tagged with letter `f`
Bank tab 2: Items tagged with letter `farming`

Items tagged with `farming` but **not** tagged with `f` will appear within the `f` tab. (see image)

### Screenshots or videos

Tag named `f`:

![1KXKdD5](https://user-images.githubusercontent.com/67039554/202077753-f5b7a400-ff22-486f-bea5-118d53f0deda.png)

Tag named `fish`:

![hZXgF8A](https://user-images.githubusercontent.com/67039554/202077839-d3e74902-d722-4652-8c19-aeaaec68cd90.png)

Examining the item tags for `Pearl barbarian rod`:

![q5xGVLH](https://user-images.githubusercontent.com/67039554/202077892-2fe4adbb-4596-49ba-a223-67f44eb35f77.png)

Showing there's only `1` tag:

![gXmk3VI](https://user-images.githubusercontent.com/67039554/202077969-a12dad80-6f3e-4b1f-b20f-e8554fdddc3a.png)

Even though the `Pearl barbarian rod` **only** has the tag `fish`, it appears in the `f` bank tab:

![eGZlTZ8](https://user-images.githubusercontent.com/67039554/202078099-4a48b382-886b-4207-bcd3-4ae1f38cc75d.png)

When you right click and `edit-tags`:

![yCGxmgg](https://user-images.githubusercontent.com/67039554/202078146-83ae5b14-dbc0-46a8-9e25-204cd0f97ef1.png)

### RuneLite version

RuneLite version: 1.9.3
Oldschool revision: Rev 209
Launcher version: 2.1.0

**Comment by Alexsuperfly** [comment]
this is intended behavior

**Comment by raiyni** [comment]
This is an intended side effect and isn't limited to single letters. Ex. Two tags named `melee - something` and `melee - other`, `melee` would show both of them.

**Comment by geheur** [comment]
duplicate of https://github.com/runelite/runelite/issues/8014

But it is certainly buggy. For example it results in items that you cannot remove from the tag tab using the right-click option `remove-tags` because it is not in the tag that is currently viewed. Items should show the correct tag; this would at least provide a hint for why this is happening.

**Comment by hessrs** [comment]
This behavior makes sense when _searching_ but doesn't seem like it really has a place for the tabs themselves
