### ISSUE TITLE
Add "Kills Left" on the XP Tracker for combat kills

### ISSUE THREAD

**Issue by kleinaeinar** [runelite/runelite#1594]
Right now the combat XP Tracker shows "### Action Left" until a level up.  If the client could be updated with "### Kills Left" for the combat skills that would help out a lot.  Because right now I am 62 ranged, and I look at the XP tracker and it shows "1612 Actions Left" and than a few second later "1323 Actions Left", few seconds after that "1852 Actions Left".  It is not very accurate when it comes to combat skills.

**Comment by king-koda** [comment]
i think thats because the actions left is calculated based on how much xp is given for that particular hit eg. 40xp for hit of 10, 80xp for hit of 20, that's why it isn't accurate. The kills left should be implemented or at the minimum, actions left removed because of it's misinterpretation.

**Comment by MrHoward190** [comment]
Hows progress on this going? Was just talking to a friend about how useful it would be.

**Comment by Nightfirecat** [comment]
@deathbeam I think this one was closed in error.

**Comment by MrHoward190** [comment]
Any update on progress? Does this look doable?

**Comment by IanMcNelly** [comment]
Opened PR #4015 to address this, based off the work in #3143

**Comment by Kingdavid337** [comment]
Is this closed, or has it just not been accepted by anyone?

**Comment by IanMcNelly** [comment]
I had it working finally locally, and posted a few times in discord/github asking for more feedback on my PR #4015 , and it was working fine locally but gave up on keeping it up to date because i couldnt get a resposne. On https://github.com/runelite/runelite/pull/3143 @LeviSchuck posted he would pick it up again

**Comment by Adam-** [comment]
I'm sorry it's been neglected. I've left some review on #4015 now.

**Comment by IanMcNelly** [comment]
@Adam- awesome thanks for the feedback! I'll take a look asap and see if i can get it into a state where its mergable :)

**Comment by Titowam** [comment]
Any updates? This would be a great addition!

**Comment by IanMcNelly** [comment]
@Titowam this was added in october: https://github.com/runelite/runelite/pull/6163
