### ISSUE TITLE
Bird house timer

### ISSUE THREAD

**Issue by kulershk** [runelite/runelite#1596]
On screen timer for bird runs, probably with current bird house icon

Something like this but birdhouse under timer
![image](https://user-images.githubusercontent.com/26186873/38828112-ade6f92e-41bd-11e8-907c-c2deb166b8aa.png)

**Comment by GODTFREDSENAPMXD** [comment]
That would be hella dope

**Comment by deathbeam** [comment]
This should probably work in similar way as farming plugin, e.g side panels? not sure

**Comment by deathbeam** [comment]
Actually, duplicate of #1224
