### ISSUE TITLE
MES Shift click settings 

### ISSUE THREAD

**Issue by vitorebom** [runelite/runelite#15972]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

Before today's build, using the following settings:
NPC Swaps > Shift Click Walk here > TRUE
Ground Item Swaps > Shift click Walk here > FALSE
I was able to shift click to pickup items under a NPC, because the NPC's option was walk here and the items below would not swap.  
Now when I shift click an Item stack under a NPC, both get swapped and I walk to the stack instead.

**Comment by Adam-** [comment]
fixed in 034408186752070722a55be7636993a8b4b313f7
