### ISSUE TITLE
Overlay behaviour when snapping to top right anchors

### ISSUE THREAD

**Issue by Th3-DoC** [runelite/runelite#15975]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Normally the overlays would snap and drop below the minimap or the xp bar in top right anchors however they are now being displayed behind the minimap or exp bar. All other anchor points are working as intended with the minimap and exp bar. Also All other overlays i have tried seem to work as intended at these anchor points, its only affecting the map and exp bar overlays.

**Comment by aLatif01** [comment]
The issue of the plugin not dynamically moving seems to be for party UI's in all raids as well. See example image here: https://imgur.com/4IzvCUz

**Comment by spencerfjz** [comment]
same thing happening with potion boost overlay and the TOA raids UI too, glad to know im not the only one. 
https://imgur.com/a/DctKjUV

**Comment by Adam-** [comment]
fixed in dc77c6a3a5ae44a1f3714d53ae49e4e9056e01a8
