### ISSUE TITLE
Request for a ping indicator in the world switcher menu

### ISSUE THREAD

**Issue by Popret** [runelite/runelite#1597]
I believe it would be very useful, and hopefully easy to implement an indicator to show how much ping a world has when hopping. 

Two potential design mock-ups:

![image](https://user-images.githubusercontent.com/38439564/38830109-8697e90c-41bb-11e8-8585-a42b9ff1d2db.png)
![image](https://user-images.githubusercontent.com/38439564/38830128-93a5b5c0-41bb-11e8-9dad-8577478dd048.png)

**Comment by kulershk** [comment]
I would say first one when u hold shift or alt

**Comment by gtjamesa** [comment]
Will submit a PR for this tomorrow, with an option for [SHIFT] to display the pings in place of world activities

![WorldPing Plugin](https://i.imgur.com/OGb2B7K.gif "WorldPing Plugin")

**Comment by gtjamesa** [comment]
World Switcher Filter plugin inclueds ping
#2873
