### ISSUE TITLE
quest helper

### ISSUE THREAD

**Issue by ShadeR3av3r** [runelite/runelite#15971]
### Type

Other

### Operating System

Windows

### Bug description

the tab menu doesnt display quest helper anymore and cant find in plugins

**Comment by LlemonDuck** [comment]
Problems with hub plugins should be directed to the author. In this case, https://github.com/Zoinkwiz/quest-helper

For today's update, the RuneLite client and Quest Helper have been updated for the new game update, and you should restart your client to receive the changes.
