### ISSUE TITLE
Method to get an existing overlay from the OverlayManager

### ISSUE THREAD

**Issue by RGamberini** [runelite/runelite#15986]
### Type

Other

### Operating System

None

### Bug description

Is there a reason there's no direct way to get an existing overlay from the OverlayManager?

There's a couple of indirect ways already, we can listen to the `OverlayMenuClicked` event and access it's `getOverlay()` method.
Or (what I do in my plugin) we can just re-instantiate all of the default overlays on plugin startup:
```java
@Inject
private OverlayManager overlayManager;
private Collection<WidgetOverlay> overlays;
@Override
protected void startUp() {
	overlayManager.clear();
	overlays = WidgetOverlay.createOverlays(overlayManager, client);
	overlays.forEach(overlayManager::add);
}
```

Rather than go through these roundabout methods can't we just have a `getOverlay()` method on the OverlayManager?

**Comment by raiyni** [comment]
What purpose does this serve?

**Comment by RGamberini** [comment]
> What purpose does this serve?

I need it for my plugin.

**Comment by Nightfirecat** [comment]
I'm not understanding your use case. If the created overlays are managed by your plugin, you should already have a reference to them. If they're not, your plugin shouldn't have access to them. Please elaborate why this is necessary.

**Comment by RGamberini** [comment]
> If the created overlays are managed by your plugin, you should already have a reference to them. **If they're not, your plugin shouldn't have access to them.**

Then is the `OverlayMenuClicked` event implemented incorrectly?  
The point is I can already access Overlays from outside my plugin, I would just like it to be easier to do so.

If you want to continue to reject plugins from the plugin hub that operate on the default / other plugins overlays that's fine but I don't see why we should be forced to use reflection or these hacky method to do so within the confines of our own plugins.

**Comment by Adam-** [comment]
> If you want to continue to reject plugins from the plugin hub that operate on default / other plugins overlays that's fine but I don't see why we should be forced to use reflection or these hacky methods to do so within the confines of our own plugins.

As far as I can tell, we have never rejected a plugin from the pluginhub for operating on other overlays. I have no idea what you are referencing

> I need it for my plugin.

I am struggling to provide a valid use case for this. Since you seem to be unwilling or unable to provide yours, I do not see a reason why it should be added.

**Comment by RGamberini** [comment]
> As far as I can tell, we have never rejected a plugin from the pluginhub for operating on other overlays. I have no idea what you are referencing

@Nightfirecat  said 
> your plugin shouldn't have access to them[other plugin's overlays].

That's why I assumed it wasn't allowed.
> I am struggling to find a valid use case for this. Since you seem to be unwilling or unable to provide yours, I do not see a reason why it should be added.

Here is my plugin:
https://github.com/RGamberini/inventory-dvd-logo
Rather then the ugly
```java
try {
  Field overlaysField = OverlayManager.class.getDeclaredField("overlays");
  overlaysField.setAccessible(true);
  inventory = ((List<Overlay>) overlaysField.get(overlayManager)).stream()
    .filter(overlay ->
      overlay.getName().equals("RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_PARENT")
    )
    .findFirst()
    .orElseThrow(() -> 
      new IllegalStateException("STARTUP FAILED CANNOT FIND INVENTORY")
  );
} catch (NoSuchFieldException e) {
        throw new RuntimeException(e);
}
```
I would much prefer to use
```java
overlayManager.getOverlay("RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_PARENT");
```

Does that make sense as a use case?

**Comment by Adam-** [comment]
> 
> ```java
> try {
>   Field overlaysField = OverlayManager.class.getDeclaredField("overlays");
>   overlaysField.setAccessible(true);
>   inventory = ((List<Overlay>) overlaysField.get(overlayManager)).stream()
>     .filter(overlay ->
>       overlay.getName().equals("RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_PARENT")
>     )
>     .findFirst()
>     .orElseThrow(() -> 
>       new IllegalStateException("STARTUP FAILED CANNOT FIND INVENTORY")
>   );
> } catch (NoSuchFieldException e) {
>         throw new RuntimeException(e);
> }
> ```
> 
> I would much prefer to use
> 
> ```java
> overlayManager.getOverlay("RESIZABLE_VIEWPORT_BOTTOM_LINE_INVENTORY_PARENT");
> ```
> 
> Does that make sense as a use case?

This isn't a use case, this is just showing how you are using reflection to access the overlays. A use case would be an example of why what you want to do requires accessing this field.

>  Here is my plugin: https://github.com/RGamberini/inventory-dvd-logo

This looks like you are using the WidgetOverlay as a way to move Widgets around on the screen. What you should be doing instead is moving the Widget directly via either `setForcedPosition` or `setRelativeX/Y`. So, I do not think you have a valid use case.

**Comment by RGamberini** [comment]
> This looks like you are using the WidgetOverlay as a way to move Widgets around on the screen. What you should be doing instead is moving the Widget directly via either `setForcedPosition` or `setRelativeX/Y`. So, I do not think you have a valid use case.

Oh I didn't realize you needed more context, excuse me. 
This was the first thing I tried, you can clone the [widget mode branch](https://github.com/RGamberini/inventory-dvd-logo/tree/widget-mode) of my repo if you don't believe me but using `setForcedPosition` or `setRelative` on the inventory widget doesn't work at all. This is my code:
```java
@Subscribe
public void onBeforeRender(BeforeRender beforeRender) {
  Widget inventory = client.getWidget(WidgetInfo.TO_GROUP(10747998));
  if (inventory == null) return;
    dvdLogo.travel();
    inventory.setForcedPosition((int) dvdLogo.x, (int) dvdLogo.y);
}
```

 I figured that was intended and that you knew that already, if that's a bug than my apologies.

Using the overlay is also preferred because the overlay (for the inventory at least) is never null.
Also rather than setting the position when we change the `preferredLocation` of the Overlay it doesn't completely break the user moving it around themselves.

Is that a use case?

**Comment by Adam-** [comment]
> > This looks like you are using the WidgetOverlay as a way to move Widgets around on the screen. What you should be doing instead is moving the Widget directly via either `setForcedPosition` or `setRelativeX/Y`. So, I do not think you have a valid use case.
> 
> Oh I didn't realize you needed more context, excuse me. This was the first thing I tried, you can clone the [widget mode branch](https://github.com/RGamberini/inventory-dvd-logo/tree/widget-mode) of my repo if you don't believe me but using `setForcedPosition` or `setRelative` on the inventory widget doesn't work at all. This is my code:
> 
> ```java
> @Subscribe
> public void onBeforeRender(BeforeRender beforeRender) {
>   Widget inventory = client.getWidget(WidgetInfo.TO_GROUP(10747998, 0));
>   if (inventory == null) return;
>   dvdLogo.travel();
>   inventory.setForcedPosition((int) dvdLogo.x, (int) dvdLogo.y);
> }
> ```
> 
> I figured that was intended and that you knew that already, if that's a bug than my apologies.
> 
> Using the overlay is also preferred because the overlay (for the inventory at least) is never null. Also rather than setting the position when we change the `preferredLocation` of the Overlay it doesn't completely break the user moving it around themselves.
> 
> Is that a use case?

If I open jshell and run

```java
Widget w = client.getWidget(164, 94);
w.setForcedPosition(50,50);
```

It certainly moves the inventory 
![image](https://user-images.githubusercontent.com/309739/205406045-a69d4d7c-5dc9-4270-a2ab-574440fa2b35.png)


So I think you are doing something else wrong.

**Comment by RGamberini** [comment]
> So I think you are doing something else wrong.

Or maybe you should've tested it slightly more?
https://user-images.githubusercontent.com/1889821/205407636-dca0ea04-1b50-4811-b666-0626994c9330.mp4

```java
Widget w = client.getWidget(164, 94);
w.setForcedPosition(50,50);
```

Only works if the position has not yet been changed by the user.
Once again the _canonical_ way to move an overlay should be to change it's preferred location right?
That allows the user to still change the position of it after we're done.

The preferred location _can only be set_ if you allow us access to the `Overlay` list inside `OverlayManager`.
