### ISSUE TITLE
[Clue Scroll Plugin] Graceful outfit: Adventurer not detected for master clue step in Rellekka

### ISSUE THREAD

**Issue by Breina** [runelite/runelite#15999]
### Type

Incorrect behavior

### Operating System

None

### OS Version

Windows 10

### Bug description

"Complete a lap op the Rellekka rooftop agility course whilst sporting the finest amount of grace."

The game allows the set 'Gradeful outfit: Adventurer' -which is gained through quest speedrunning- to be used to complete the lap. The plugin, however, does not give a checkmark when detecting items in the inventory / equipment.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/3009914/205958226-9a330d6c-4279-472a-b895-5f41d5722dcc.png)

### RuneLite version

Runelite version: 1.9.4.1
Launcher version: 2.3.0

### Logs

[client.log](https://github.com/runelite/runelite/files/10167982/client.log)

**Comment by Nightfirecat** [comment]
Added in 318c910d0d4378f15b42fa3c65b3eb261b67a2e5
