### ISSUE TITLE
"use" as left click on Imp box

### ISSUE THREAD

**Issue by Epicurius** [runelite/runelite#1599]
The option to have "use" as left click on "Imp-in-a-box(2)" and "Imp-in-a-box(1)", instead of "bank".

**Comment by Kamielvf** [comment]
#1556 will allow you to do this. You can already do it with shift-clicking but that won't make it show as first-click unless shift is held.

**Comment by Kamielvf** [comment]
You should probably leave this issue open as it is valid as long as the other PR has not been merged.

**Comment by Epicurius** [comment]
How do you swap the Imp box to left click use when holding shift, i cant find it anywhere?

**Comment by Kamielvf** [comment]
enable the menu entry swapper plugin, then this:
![preview](https://puu.sh/zVEcD/aff42db5c7.gif)

**Comment by Epicurius** [comment]
thanks :)

**Comment by deathbeam** [comment]
Looks like this is solved with shift-click configuration, for generic left-click shift-click there should be separate issue (and probably already is)
