### ISSUE TITLE
Clue scroll info panel randomly changing width

### ISSUE THREAD

**Issue by tg3eada** [runelite/runelite#15994]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The info panel for clues sometimes widens seemingly at random (though I did notice it happening after running a master clue and then going back to mediums.)
The only way I've found to fix this is to close and reopen Runelite.

### Screenshots or videos

![normal](https://user-images.githubusercontent.com/116391688/205516796-d9e8181e-daf3-479b-b80f-b35bf226fab2.PNG)
![wide](https://user-images.githubusercontent.com/116391688/205516798-780b7837-2ab6-4785-a2fe-e1e54f4fabd6.PNG)

**Comment by Adam-** [comment]
Are you able to resize it back down by holding alt and dragging the right edge to the left?

**Comment by tg3eada** [comment]
Yes, I am able to resize it. I had another 3 step master clue, and that does appear to be the cause.
