### ISSUE TITLE
Show Ghommal's Hilt Teleport Locations on the World Map

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#16006]
### Discussed in https://github.com/runelite/runelite/discussions/16005

<div type='discussions-op-text'>

<sup>Originally posted by **DrYoshiyahu** December  7, 2022</sup>
Pretty self-explanatory. Ghommal's Hilt has a teleport just like many of the Achievement Diary rewards, which is located north of Trollheim, about here. Much like the Achievement Diary teleports, it would be nice to have this location shown on the map.

![image](https://user-images.githubusercontent.com/14756430/206188897-41987c79-949e-410b-9f23-5b2a4d5e52c6.png)
</div>

<br>

Please note, there are two teleport locations: God Wars Dungeon entrance, and Mor Ul Rek. Both locations should be added. (possibly with different icons, as Ghommal's Hilt 1 grants some daily teleports to God Wars Dungeon, but only Ghommal's Hilt 4 and above grant teleports to Mor Ul Rek)

**Comment by KPGoik** [comment]
Done! Created PR #16022.
