### ISSUE TITLE
Fairy ring menu entry swap

### ISSUE THREAD

**Issue by Treedot** [runelite/runelite#1602]
Would be really nice to be able to have "Configure" as the left click option on the Fairy Rings. I switched over from OSBuddy and I'm really used to having that feature.

**Comment by HypoxiaOSRS** [comment]
Assuming #1556 is merged, this should be easy to add.

**Comment by Kamielvf** [comment]
#1556 only applies to items @HypoxiaOSRS

**Comment by HypoxiaOSRS** [comment]
I was referring to fact you move several of the event's and conditions around in the menuswapper that it would be best to leave it be until yours is merged. The conditions would be very easy to implement. Something along this line would work fine. 
`if (config.swapFairyRing() && target.contains("fairy ring"))
{
   swap("configure", option, target, true);
}`
