### ISSUE TITLE
Poor Performance on Gaming PC

### ISSUE THREAD

**Issue by ryan4761** [runelite/runelite#16035]
### Type

Performance

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Hey Guys,

I've been using RuneLite for some time now (3-5 Years)
I have a issue where whether I'm on GPU, 117 HD, or just normal, my fps is right around 30 FPS, it sometimes jumps to 40, but never above. 
I've noticed when I load new tabs and such on Chrome it droops my FPS down to 5-10, however I am able to play games on my other monitor with Runelite running and still achieve 30fps. 
Now I know this might not sound too alarming, but on my work PC, that has no graphics card and an old Processor runs it 50fps.
I've always had this issue with Runelite.

Things I've done:
- .Bat file to disable hardware acceleration.
- Disabled all Plugins
- Verified plugins were either Uncapped or Capped at 60FPS
- Set core Affinity in my processes for RL
- Followed guides to change settings in Geforce Experience
- Increased ram for Runelite
- No Overlays
- Reinstalled RuneLite ( Heard of issues where old launchers wont update)
- Even fully zoomed in cant reach much over 30 FPS
- Only Program open being RuneLite

I've tried all of these and had no luck, nothing was able to increase my FPS. 

Specs:
Nvidia 1070
AMD FX 8350
16GB RAM
RL Installed on SSD
Windows 10

Sometimes loading into zones it will freeze slightly.

20ish % GPU Usage 
10-30% CPU Usage
750ish MB RAM Usage.

Any Suggestions would be fantastic
Thanks!

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
