### ISSUE TITLE
[Clue Scroll] No longer properly identifies the current step for Charlie the Tramp beginner steps

### ISSUE THREAD

**Issue by SirJorb** [runelite/runelite#16043]
### Bug description

The clue scroll plugin no longer shows the current task after checking the scroll after talking to Charlie, instead the info box disappears completely until getting the next step.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/23423782/208226629-84730827-3295-484f-ac76-1b875e3a4232.png)

**Comment by Nightfirecat** [comment]
We need all the new clue texts for this feature to work, and we don't have them all yet. Thus far, I've seen:

* `I need to give Charlie a piece of iron ore.`
* `I need to give Charlie some leather chaps.`
* `I need to give Charlie a raw herring.`
* `I need to give Charlie one iron dagger.`

We still need clue texts for the tasks to give him:

* Raw trout
* Trout
* Pike
* Leather body

**Comment by SirJorb** [comment]
![image](https://user-images.githubusercontent.com/23423782/208227564-5e01b9e2-d22f-43e6-979b-56c2629564fa.png)
Here's the raw trout one. I'll update this reply as I find the others while doing beginners.

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/208231783-eb31c594-faa5-40ed-a877-b7f1a9fbb6cb.png)

`I need to give Charlie a cooked pike.`

**Comment by Adam-** [comment]
We also need the updated return text for the clues too, eg was `i need to take the iron dagger i smithed to charlie.` but now?

**Comment by Nightfirecat** [comment]
> The text displayed on the clue widget is not the same to the dialogue when talking to the NPC.  I haven't checked if the plugin relies on the latter but thought it'd be worth mentioning.
> 
> Clue text
> 
> > I need to give Charlie a raw trout.
> > I need to give Charlie a leather body.
> 
> Dialogue
> 
> > I really need a raw trout.
> > I really need a leather body.

That's known, release and master don't update on seeing the chatbox text. I have a PR (which I need to update after this update...) which will add support for that.

> We also need the updated return text for the clues too, eg was `i need to take the iron dagger i smithed to charlie.` but now?

There's no return text since you don't need to perform actions for these steps anymore, so we'll just need to remove it entirely.

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/208264893-717b42f9-6020-46eb-bee3-68790e18e0bd.png)

`I need to give Charlie a leather body.`

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/208269156-4bce3ce2-0c7e-43de-b2eb-473603b9d962.png)

`I need to give Charlie a cooked trout.`
