### ISSUE TITLE
Missing 'search' option on motherlode mine ore sack

### ISSUE THREAD

**Issue by igorrrrrrr9** [runelite/runelite#16055]
### Type

Other

### Operating System

Windows

### OS Version

Windows 10

### Bug description

No issues for over an hour of motherlode mine. Suddenly after depositing ore to the hopper, I notice that the ore sack has no 'search' option. Had not been changing any plugin settings.

The sack IS searchable when I play on the Jagex oldschool client, or on mobile. Just not on runelite. I am not using any custom plugins - only those that are in the plugin hub. I do not think this is an issue with plugin settings - as I was not changing plugin settings when it occurred. 

I have tried:
-teleing away and returning
-logging out
-hopping worlds
-restarting runelite
-fresh install of runelite
-turning on/off various plugins related to hiding entities or swapping options
-emptying sack using mobile/jagex client and then refilling on runelite

None of these attempts have brought back the ore sack 'search' option 

### Screenshots or videos

![Capture](https://user-images.githubusercontent.com/121185071/208954734-4cb74406-3c46-496b-992f-2ee967caf9d0.PNG)

### RuneLite version

RuneLite Version: 1.9.5
Launcher Version: 2.5.0

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run: 
```
"%localappdata%\runelite\runelite.exe" --clientargs --safe-mode
```

Or on Mac: In Terminal, run: 
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --clientargs --safe-mode
```

**Comment by igorrrrrrr9** [comment]
Hey thanks for the super speedy response! I tried that. No, it does not occur when running runelite in safe mode.

**Comment by Nightfirecat** [comment]
Then this is caused by some hub plugin you have installed. We don't offer support for those. I recommend turning them off individually to identify which one is the culprit.

**Comment by igorrrrrrr9** [comment]
I just did that and that did not resolve the issue.

**Comment by igorrrrrrr9** [comment]
Solved. Thank you.

Removing all the external plugins resolved the issue. For some reason, merely turning them off did not.
