### ISSUE TITLE
Bunch of plugins not working

### ISSUE THREAD

**Issue by eDiTicX** [runelite/runelite#16068]
### Type

Other

### Operating System

Windows

### OS Version

11

### Bug description

A have a bunch of plugins not working. Some are default plugins, some are added. For instance, inventory tags are not working. I have it enabled, i right click the inventory icon and there is no configure. other things such as when hovering over items in the inventory, no price appears. Sometimes I can turn off/on or restart client and it works. Other times, nothing works to fix it. 

### Screenshots or videos

![d9bfb11d5153a2cc2c201bf18f5d8353](https://user-images.githubusercontent.com/121438579/209550036-a2b02458-51a6-4703-9d45-7b51795f6124.png)

### RuneLite version

RuneLite version: 1.9.5
Oldschool revision: Rev 210
Launcher version 2.4.2

### Logs

[client.log](https://github.com/runelite/runelite/files/10303474/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10303475/launcher.log)

**Comment by Nightfirecat** [comment]
Inventory tagging is no longer done via shift+right-clocking the inventory icon, it's done by shift+right-clicking the items directly. I expect the item prices issue you're encouraging is also something which can be resolved by some setting or other. Please [join our Discord server's #support channel](https://runelite.net/discord) for help with that.
