### ISSUE TITLE
Save window size

### ISSUE THREAD

**Issue by ipkpjersi** [runelite/runelite#1607]
Hello,

I have noticed that the window size is reset every time you close the client, I think saving this locally and ideally to your account as well would be really nice to have, or at least an option to have this.

Thank you.

**Comment by sethtroll** [comment]
Check the "RuneLite" plugin settings, has an option to set the size.

**Comment by ipkpjersi** [comment]
Oh, I am sorry, I did not see it. I searched for "window", "size" and "screen" and did not find anything. Thank you, I will now close this issue.
