### ISSUE TITLE
Minimap not showing player dots

### ISSUE THREAD

**Issue by IdzyQ** [runelite/runelite#16093]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

When I load up RuneLite no white player dots appear on the minimap until I toggle off the minimap plugin. This only happens with player dots. NPC and item dots etc. still show up.

I can toggle the minimap plugin back on again and everything works fine, this only happens when using a fresh instance of RL, and with any account.

Player Indicators still shows names on the map as usual and toggling doesn't cause the dots to show up.

### Logs

[launcher.log](https://github.com/runelite/runelite/files/10328782/launcher.log)
[client.log](https://github.com/runelite/runelite/files/10328783/client.log)

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run: 
```
"%localappdata%\runelite\runelite.exe" --clientargs --safe-mode
```

Or on Mac: In Terminal, run: 
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --clientargs --safe-mode
```

**Comment by IdzyQ** [comment]
Nope, the minimap works exactly as expected in safe mode
