### ISSUE TITLE
Significant, sporadic lag when the "Time Tracking" panel is open

### ISSUE THREAD

**Issue by vanoreo** [runelite/runelite#16095]
### Type

Performance

### Operating System

Windows

### OS Version

Windows 10 (10.0.19045.2364)

### Bug description

I've noticed while doing farm runs, that if I have the "Time Tracking" plugin panel open, there is significant input delay every few seconds.

My FPS will go from ~160FPS to ~70FPS roughly every 5 seconds as well.

It is worth noting that I am also running 117HD, but the performance issues only occur when that specific panel is open. Other ones (such as Loot Tracker) do not seem to have this effect.

### RuneLite version

RuneLite version: 1.9.6
Launcher Version: 2.2.0

### Logs

[client.log](https://github.com/runelite/runelite/files/10329600/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10329601/launcher.log)

**Comment by Nightfirecat** [comment]
Your logs show no issues. Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run: 
```
"%localappdata%\runelite\runelite.exe" --clientargs --safe-mode
```

Or on Mac: In Terminal, run: 
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --clientargs --safe-mode
```

**Comment by vanoreo** [comment]
Looks like it does occur while using safe mode (though of course the frame rate goes from ~50fps to ~35fps since safe mode has the FPS cap)

One way to easily notice the behavior is to use the middle mouse button to move the camera for a bit and you'll see it basically "snag" on itself

**Comment by Nightfirecat** [comment]
I'm told this is the same issue as #14978

**Comment by gotohopper** [comment]
I have near same issue, as explained here: https://github.com/runelite/runelite/discussions/16088

input failing to register is the crux of my issue with the time tracking feature
