### ISSUE TITLE
many bbug

### ISSUE THREAD

**Issue by dexter-305** [runelite/runelite#16107]
### Type

Performance

### Operating System

Windows

### OS Version

windows 10

### Bug description

1.when i open bank or take item from band get fps drop don't know why i have very good cpu and gpu
2.don't show world in world switcher
3.don't show any thing in news feed
4.dont show item price in ground and loot tracker always 0 value i make item price on and show ge price on

**Comment by Enriath** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
