### ISSUE TITLE
Minimap player dots disappearing

### ISSUE THREAD

**Issue by nomadicvice** [runelite/runelite#16118]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Occasionally the white player dots on the minimap will disappear when the plugin is active. Restarting the plugin will fix this issue. 

### RuneLite version

RL version: 1.9.6
Launcher: 2.2.0

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run: 
```
"%localappdata%\runelite\runelite.exe" --clientargs --safe-mode
```

Or on Mac: In Terminal, run: 
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --clientargs --safe-mode
```

**Comment by nomadicvice** [comment]
I haven't checked to see this if this happens on safe mode yet. When I get
the chance I will play around for a little while and see if it happens (as
it's random if/when it occurs)


Sincerely,

Brendan Ecker

___________________

Brendan Ecker

Eurofins Scientific PSS Insourcing Solutions

B.S. in Forensic Chemistry

***@***.***

***@***.***

(518) 779-1801

**Comment by nomadicvice** [comment]
The issue continued in safe mode. Here is how the issue appears in-game. Note the other player's name still appearing despite no white dot being present:
![image](https://user-images.githubusercontent.com/122106639/211125107-a7ed84b0-8636-4f90-92b2-3bc4ed06ce99.png)

**Comment by Adam-** [comment]
This issue is most likely caused by the 3rd party prop hunt plugin. This screenshot you've provided is not from safe mode.

**Comment by nomadicvice** [comment]
> This issue is most likely caused by the 3rd party prop hunt plugin. This screenshot you've provided is not from safe mode.

Turned off that plugin and it seems to work again. Thank you for the advice!
