### ISSUE TITLE
Request: Add user-configurable timers/stopwatches

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#1612]
I've found much use of a plugin that provided user-configurable stopwatches and timers in OSBuddy. See image below for their implementation.

![OSBuddy timers and stopwatches sidebar plugin](https://user-images.githubusercontent.com/2199511/38844078-74192e00-41e1-11e8-9423-aa2386c68009.png)

**Comment by Matsyir** [comment]
Started to work on this btw, but it will probably take a fair bit of time. If anybody has any suggestions or anything let me know. Using system time okay? More efficient than creating a new timer as far as I understand.

**Comment by Matsyir** [comment]
If someone wants to work on this feel free, it turns out I won't be getting around to it anytime soon. All I have are some basic class skeletons to get started, lemme know if you'd like those.
