### ISSUE TITLE
Sidebar Image dragging

### ISSUE THREAD

**Issue by DravenDarkKnight** [runelite/runelite#16131]
### Type

GPU

### Operating System

Windows

### OS Version

1.9.6

### Bug description

Any time i open the side bar the image drags and overlays incorrectly. It makes it really hard to use any trackers.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/122430466/211736466-fd8551af-6bab-480e-8a63-8a1f82a47fe7.png)
![image](https://user-images.githubusercontent.com/122430466/211736491-63682794-ff56-4183-949c-cd92af0a2c60.png)

### RuneLite version

1.9.6 vs and 2.1.7

### Logs

[client.log](https://github.com/runelite/runelite/files/10389508/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10389510/launcher.log)

**Comment by Enriath** [comment]
This is fixed in newer launcher versions.
Please join the [Discord](https://runelite.net/discord) for questions of support.
