### ISSUE TITLE
MES Bank Deposit Fill not working with Plank Sack

### ISSUE THREAD

**Issue by samuelcolburn** [runelite/runelite#16137]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10.0.19045 Build 19045

### Bug description

Setting MES Bank Deposit shift-click to Eat/Wield/Etc. no longer allows filling the Plank Sack from the bank screen. Other fill items like Coal Bag still appear to work as intended.

### RuneLite version

RuneLite Version: 1.9.7
Launcher Version: 2.2.0

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run: 
```
"%localappdata%\runelite\runelite.exe" --clientargs --safe-mode
```

Or on Mac: In Terminal, run: 
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --clientargs --safe-mode
```

**Comment by samuelcolburn** [comment]
Yes, same behavior. (side note: that command just throws an error for me on windows terminal, works fine as a shortcut target though)

**Comment by Nightfirecat** [comment]
I'm looking ingame, and the plank sack doesn't have a "Fill" or "Empty" option when the bank is open.
![Screenshot_20230116_082831](https://user-images.githubusercontent.com/2199511/212725951-864d06c5-53f1-45eb-8c77-bc7a7167c33f.png)

**Comment by Alexsuperfly** [comment]
"Use" functions as both afaik

**Comment by Enriath** [comment]
The `Use` option will fill the sack. idk if it empties it, personally haven't tried it.

**Comment by Nightfirecat** [comment]
This is evidently a regression from custom UI swaps being added to the plugin. We'll look at sorting this out at some point; in the meantime, you can use said custom UI swaps to change the shift-click option of the plank sack to "Use" to get the same functionality back.

**Comment by Nightfirecat** [comment]
Upon further review, this works fine in release, just make sure any custom swaps you have set on the plank sack are unset.
