### ISSUE TITLE
Add Bow of faerdhinen to Iorwerth camp emote clue

### ISSUE THREAD

**Issue by Enriath** [runelite/runelite#16144]
The emote clues to bow in Iorwerth's camp both accept the Bow of faerdhinen instead of a crystal bow. The clue plugin should be updated to support all forms of the bow (normal, corrupted, and corrupted + recoloured).

Proof submitted in Discord, and has been verified by another contributor
![image](https://user-images.githubusercontent.com/2979691/212326575-92d44dad-d2d3-4a01-a62b-68a10d050169.png)

**Comment by Nightfirecat** [comment]
Do we know if this clue works for the inactive forms of the crystal bow and bow of faerdhinen? I assume it does not since it specifically asks for a charged crystal bow

**Comment by hex-agon** [comment]
Based on what's available in the dbrows, no:
```
[dbrow_2180]
table=dbtable_9
data=dbcolumn_0,369
data=dbcolumn_1,5
data=dbcolumn_2,Bow in the Iorwerth Camp. Beware of double agents! Equip a charged crystal bow.
data=dbcolumn_3,dbrow_420
data=dbcolumn_4,2
data=dbcolumn_6,dbrow_1692
data=dbcolumn_7,inconspicuous_crate_master_multi_29050
data=dbcolumn_8,0_34_50_22_57
data=dbcolumn_9,dbrow_1806
```

```
[dbrow_1692]
table=dbtable_28
data=dbcolumn_0,Equip a charged crystal bow.
data=dbcolumn_4,crystal_bow_23983
data=dbcolumn_15,20
```
