### ISSUE TITLE
Remove "Hidden Items" from the ground items right click menu

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#1615]
This is a feature that I miss from RuneLoader.
There was a toggle to have items which are on your blocklist not appear in the context menu.
This would also make it so there is no left click "pick up" option for the item when on the floor.

This was nice for Slayer, as when I had a good Highlight/Block list set up, I could just left click the pile for the item every time.

This is also nice in areas such as Wintertodt, where there are constantly empty wine jugs on the floor. With the toggle on and empty jugs blocked, you could click on the empty jug, and you would "walk here" instead of picking up the jug.

This also makes it so if you accidentally drop an item on a large pile (like when barb fishing) you can pick it back up easily. (And removes the clutter of 100 Leaping Salmon on the floor when right clicked)

**Comment by SoyChai** [comment]
I presume we don't this yet because the feature's only just been added, but yeah, this is a critical part of what makes drop hiding so useful.

**Comment by TheArbalist** [comment]
Would be a welcome addition to the feature, such a shame that RuneLoader is the only client that does it presently.

**Comment by deathbeam** [comment]
This could be both useful and abusable, so I am not really sure if we want to implement this.

**Comment by SomeZer0** [comment]
RuneLoader had this feature for over a year, so I don't believe it to be overpowered.

**Comment by SoyChai** [comment]
Could you describe a common situation where this might be overpowered, @deathbeam?

**Comment by forsco** [comment]
Back to the original question though, it was only asked to hide 'hidden items' in the right click menu, would this remove the ability to left click said removed items on the ground?

**Comment by SomeZer0** [comment]
> The first thing that comes to mind is looting in the wilderness, 

Could help edge/pvp-world pkers by making it so they can loot without getting rushed.
Could potentially hurt deep wildy pkers by making them unable to pick up food when getting piled after a kill.
Could help looters get the most expensive items. Not sure if this would be good or not. Bots can already snipe the high value items before players can, so I don't see that as an issue. It really kinda just evens the playing field there.

>Back to the original question though, it was only asked to hide 'hidden items' in the right click menu, would this remove the ability to left click said removed items on the ground?
Removing the option from the context menu would remove the left click option as well.

**Comment by SoyChai** [comment]
☝️ This. The left-click action is just whatever action's on top of the right-click menu.

**Comment by forsco** [comment]
I see, it would then have pro's and con's for it going into the client then, it really is a double edged blade and a touchy subject. I could then understand reorganising the way the right click menu is sorted as we already change those for other things, but not completely removing fields.

**Comment by SomeZer0** [comment]
> I see, it would then have pro's and con's for it going into the client then, it really is a double edged blade and a touchy subject. I could then understand reorganising the way the right click menu is sorted as we already change those for other things, but not completely removing fields.

If we had it as a toggle, then people would know what they're getting themselves into when they turn it on. Like, in my example before with a deep wildy pker, they would have to add food to a blocklist, and then toggle the option on to "remove blocked items from context menu."

Turning this feature on is a double edged sword, yes, but that's why I believe it's not overpowered.

You give yourself a slight advantage of looting your kills faster/easier, but gain the disadvantage of not being able to loot food when you need it. And, since that would be a toggleable option, you could keep vanilla looting if the downside of this proposed plugin outweighs the upside.

And for the loot sniper issue, we could just make it so the plugin doesn't work in the wildy. And all of this would become a non-issue.

**Comment by forsco** [comment]
> And for the loot sniper issue, we could just make it so the plugin doesn't work in the wildy. And all of this would become a non-issue.

Cancels out 

> Like, in my example before with a deep wildy pker, they would have to add food to a blocklist, and then toggle the option on to "remove blocked items from context menu."

I can't think of any situations outside of the Wildernerss and Deadman Mode where this could be a potential controversial topic.

**Comment by deathbeam** [comment]
Well, as this is now [here](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features) closing as wontfix
