### ISSUE TITLE
RuneLite closes unexpectedly

### ISSUE THREAD

**Issue by bsk1ng** [runelite/runelite#16158]
### Type

Crash or hang

### Operating System

None

### OS Version

Windows 10

### Bug description

RuneLite randomly closes. No real pattern that I can detect.

### RuneLite version

Runelite 2.1.3
Jagex Launcher

### Logs

[jvm_crash_pid_14280.log](https://github.com/runelite/runelite/files/10418949/jvm_crash_pid_14280.log)

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001a3893e75f8, pid=14280, tid=22724
#
# JRE version: OpenJDK Runtime Environment (11.0.7+10) (build 11.0.7+10)
# Java VM: OpenJDK 64-Bit Server VM (11.0.7+10, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# J 25042% c2 du.e(Lcb;III)V (4708 bytes) @ 0x000001a3893e75f8 [0x000001a3893da4a0+0x000000000000d158]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#

---------------  S U M M A R Y ------------

Command Line: -XX:+DisableAttachMechanism -Drunelite.launcher.nojvm=true -Drunelite.launcher.blacklistedDlls=RTSSHooks.dll,RTSSHooks64.dll,NahimicOSD.dll,NahimicMSIOSD.dll,Nahimic2OSD.dll,Nahimic2DevProps.dll,k_fps32.dll,k_fps64.dll,SS2DevProps.dll,SS2OSD.dll -Xmx512m -Xss2m -XX:CompileThreshold=1500 -XX:ErrorFile=C:\Users\PC 1\.runelite\logs\jvm_crash_pid_%p.log 

Host: AMD Ryzen 5 3600X 6-Core Processor             , 12 cores, 31G,  Windows 10 , 64 bit Build 19041 (10.0.19041.2364)
Time: Sat Jan 14 16:58:09 2023 Eastern Standard Time elapsed time: 106880 seconds (1d 5h 41m 20s)

**Comment by Enriath** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.
