### ISSUE TITLE
Player minimap dots not appearing on the minimap

### ISSUE THREAD

**Issue by hballington12** [runelite/runelite#16167]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

My steps to reproduce this error:
1. Enable the minimap plugin.
2. Close the client.
3. Reopen the client.
4. Player minimap dots no longer appear on the minimap.

The minimap dots sometimes reappear when the minimap plugin is disabled.

### Screenshots or videos

With minimap enabled, before I close my client:
https://gyazo.com/da948f51e789f266719e589bf44d4cb1
After I reopen my client, with several players clearly visible in the game but no player minimap dots visible:
https://gyazo.com/7645d8682899eea738263e607d8c8366
After disabling the minimap plugin, player minimap dots reappear:
https://gyazo.com/bf81d93158598ea02e54eff1810b34df

### RuneLite version

RuneLite version: 1.9.7
Launcher version: 2.1.6

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run: 
```
"%localappdata%\runelite\runelite.exe" --clientargs --safe-mode
```

Or on Mac: In Terminal, run: 
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --clientargs --safe-mode
```

**Comment by hballington12** [comment]
This behaviour does not happen in safe mode. Any hints on how to fix?

Thanks for the response.

**Comment by Alexsuperfly** [comment]
prop hunt

**Comment by Enriath** [comment]
This is an issue of a misbehaving hub plugin (Prop Hunt, as @Alexsuperfly mentioned above), and therefore has nothing to do with RuneLite itself. You might want to go complain to them about the minimap being broken even when you're not actively using the plugin to play prop hunt. Issues and suggestions for hub plugins must be made on that plugin's repository; they are not maintained by us. The repo is usually accessible from the Support link on the plugin.
