### ISSUE TITLE
Chat Timestamps Broken

### ISSUE THREAD

**Issue by Kinomora** [runelite/runelite#16177]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 10 v19044.2486

### Bug description

Chat Timestamps plugin appears to not be working for main-chat (as opposed to separated friends chat) on my client.

I disabled and re-enabled the plugin, and set a color (which I hadn't had one set before) and it wont put anything next to chat messages in the main chat window.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/9062578/213176283-05e1239f-26b4-4601-bca4-a896ca4ad724.png)

### RuneLite version

RuneLite version: 1.9.7
Oldschool revision: Rev 210
Launcher version: 2.1.3

### Logs

[launcher.log](https://github.com/runelite/runelite/files/10446402/launcher.log)
[client.log](https://github.com/runelite/runelite/files/10446403/client.log)

**Comment by geheur** [comment]
Try restarting for runelite version 1.9.8.
