### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by SweaterPuppies** [runelite/runelite#16197]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Yesterday my audio was working fine. I boot up the Runelite client and when I got in-game I immediately noticed when I went into the Gauntlet teleporter that it was silent.

### RuneLite version

Runelite version: 1.9.8
Launcher version: 2.4.2

### Logs

[client.log](https://github.com/runelite/runelite/files/10474849/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10474850/launcher.log)

**Comment by Nightfirecat** [comment]
Nothing about the client has updated between yesterday and today, this is probably something else that changed on your computer.

**Comment by SweaterPuppies** [comment]
> Nothing about the client has updated between yesterday and today, this is probably something else that changed on your computer.

Well, yes, clearly, but I'd still like some feedback if anyone's kind enough to give me insight on this issue.

**Comment by Enriath** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

**Comment by SweaterPuppies** [comment]
> The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions of support.

Ah, so I shouldn't report any issues I'm having with the client. Hmm...
