### ISSUE TITLE
Highlight own name problem

### ISSUE THREAD

**Issue by Rithic3** [runelite/runelite#16211]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Within the past week or so, it seems that now when my character has a dialogue with NPC's, the Highlight own name notification gets triggered and shows me the chat and what is being said. I Never had this problem before. 

### Screenshots or videos

<img width="1247" alt="Screen Shot 2023-01-25 at 10 34 20 AM" src="https://user-images.githubusercontent.com/26880054/214622544-815018cc-9cfa-4e2b-badf-9d58235659db.png">

### RuneLite version

Runelite version: 1.9.8
Launcher version: 2.4.3

**Comment by Adam-** [comment]
This is due to change in Jagex's update last week and was fixed in 4221d4d44c87ee8d58bade6f43096bc7f381dcaf

**Comment by Rithic3** [comment]
How do I get the change to show up?

> This is due to change in Jagex's update last week and was fixed in [4221d4d](https://github.com/runelite/runelite/commit/4221d4d44c87ee8d58bade6f43096bc7f381dcaf)

**Comment by Nightfirecat** [comment]
Run a dev build or wait until our next release. (probably next week)

**Comment by SandroVA** [comment]
This may be its own issue but "[Name] received a drop:" should not trigger own name notification either. Especially since Ground items plugin does just that.
