### ISSUE TITLE
Calvar'ion & Calvar'ion Reborn need adding to the Menu Entry Swapper Lists

### ISSUE THREAD

**Issue by McEwann** [runelite/runelite#16215]
### Type

Other

### Operating System

None

### Bug description

Calvar'ion & Calvar'ion Reborn need adding to IsDying() & onNpcChanged() by the looks of things, currently when he hits 0 Hp he's counted as dead.

### RuneLite version

Current Build

**Comment by Nightfirecat** [comment]
I have the IDs for Calvar'ion ready to go, if someone could confirm the first and second phase NPC IDs for Vet'ion as well, that would be great. I assume they are `6611` and `12002`, but cannot currently confirm that.

**Comment by Nightfirecat** [comment]
Phase 2 being the form in the middle which is used only for the transformation animation?

**Comment by Nightfirecat** [comment]
Fixed in 900af027d9571085aa288174f7e2f2ee3be49929 and applied for runtime config to apply until that's released in runelite/static.runelite.net@4e48dfc445f5d115aa5558655a78af21c247f060
