### ISSUE TITLE
Loot not tracked for Spindel

### ISSUE THREAD

**Issue by vdrey** [runelite/runelite#16224]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Loot tracker captures Spindel's bone drop, but not the actual loot. See screenshots for example.
![RuneLite_Hjhdm48hyP](https://user-images.githubusercontent.com/7849488/215267294-0adba87d-12c5-457e-a5db-991887e484c9.png)
![RuneLite_qBOaGLmZcl](https://user-images.githubusercontent.com/7849488/215267700-747b536f-5eae-4058-966c-4cb53f9b04df.png)

### RuneLite version

![RuneLite_SNUHfa8fqu](https://user-images.githubusercontent.com/7849488/215267346-3863fb98-5ae4-41a3-93e3-c660e3e3e0ab.png)

**Comment by Nightfirecat** [comment]
This has been added in 172206d69f035581c2c4bfa9b377d90b79f6a4b3 and will be in our next release.
