### ISSUE TITLE
Split runescape-client into its own repository and import it via a submodule to improve code auditability

### ISSUE THREAD

**Issue by shuhaowu** [runelite/runelite#1622]
As I was browsing through the commit tree of runelite, I noticed large commits like https://github.com/runelite/runelite/commit/26fd71455faf5357dc75811dc0273791328611bf. This commit is not easily auditable as there are >300 files changed and 40kLoC changed. In comparison, a regular week worth of changes are in the orders of 1-5kLoC changed with about 100 files (as I can tell from recently).

The problem with such a large commit is that it's effectively impossible to review them to ensure nothing bad has been added. As I understand, the runescape-client directory contains no executable code. Thus, in theory, all you have to check is if the large commits contain any files that are outside of that directory. However, in practise, with >300 files changed, it maybe easy to miss it if manually reviewing the code via something like `git diff --stat`.

To solve the problem of not being able to audit such a commit: since there's nothing executing from runescape-client, we can split it into another repository and bring it in via a submodule. This way, the 40kLoC automated commits are hidden away from the main repo (exposed only as an updated sha to the submodule in the main repo). This brings the amount of files/code to audit to a reasonable level (assuming that 5kLoC/week is reasonable to begin with).

Thoughts? Is this practical? Not necessary?

**Comment by Nightfirecat** [comment]
runescape-client is now part of the private repository, this can be closed.
