### ISSUE TITLE
Eclectic and Essence impling jars are hidden in inventory

### ISSUE THREAD

**Issue by IromTypo** [runelite/runelite#16247]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I was collecting eclectic implings at Impetuous Impulses

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/107814537/216829029-5e26d193-0768-4c8e-ab68-c84af7326a60.png)

### RuneLite version

RuneLite Version: 1.9.9
Launcher Version: 2.2.0

### Logs

[client.log](https://github.com/runelite/runelite/files/10611422/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10611423/launcher.log)

**Comment by YvesW** [comment]
Disable the ImplingSaver plugin. This is not a RuneLite issue.
