### ISSUE TITLE
Equipment and consumable stats are disabled frequently

### ISSUE THREAD

**Issue by suyashm95** [runelite/runelite#16248]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I have noticed that the item stats plugin's `Enable consumable stats` and `Enable equipment stats` are often disabled. I have always left these on, but every once in a while, these are turned off. I have not found a pattern to recreate the error on demand, but I have noticed this while doing some ToA recently (as I'm grinding to get a profitable purple 🤞 )

I had noticed this same behavior a couple of months ago (but not at ToA as I recently started doing that, I don't remember where I was running into the issue before) but it was fixed and I didn't see the issue again until kind of recently.

### RuneLite version

RuneLite version: 1.9.9
Launcher version: 2.5.0

### Logs

[client.log](https://github.com/runelite/runelite/files/10611786/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10611787/launcher.log)

**Comment by geheur** [comment]
Do you have the "Bank item stats toggle" plugin installed?

**Comment by suyashm95** [comment]
I do! Do those plugins not play nicely with each other?

**Comment by Nightfirecat** [comment]
If you don't want to have the overlays toggled while banking, remove that plugin. [Per the README of the project, that's literally what it does](https://runelite.net/plugin-hub/show/item-stats-banking):

> Toggles Item Stats plugins overlays when banking

**Comment by suyashm95** [comment]
My bad, didn't see that
