### ISSUE TITLE
Timers for divine potions incorrectly changing to red early

### ISSUE THREAD

**Issue by doomercreatine** [runelite/runelite#16254]
### Type

Incorrect behavior

### Operating System

None

### OS Version

Windows 10

### Bug description

The Timers plugin for divine combat potions is incorrectly changing to red (signifying that the potion will run out) too soon. Previously it would turn red around the 30 second mark but recently it's been turning red anywhere from 0:55 to 1:20 left on the potions (see images below). 

I tested the potions in a bank and not doing anything and they correctly turned red at 0:30. However, I also drank a set of potions and then used my POH ornate rejuvenation pool and they turned red at ~0:58. I think this may be related to the issue raised in #16249

### Screenshots or videos

https://i.imgur.com/j3U5ALi.png

### RuneLite version

RuneLite version: 1.9.9
Launcher version: 2.1.0

### Logs

[client.log](https://github.com/runelite/runelite/files/10668561/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10668567/launcher.log)

**Comment by Nightfirecat** [comment]
A fix for this bug has already landed in master in d2e04b973d6cd7fcc715d22432810f22451d18fa, and will be in our next release.

**Comment by doomercreatine** [comment]
> A fix for this bug has already landed in master in [d2e04b9](https://github.com/runelite/runelite/commit/d2e04b973d6cd7fcc715d22432810f22451d18fa), and will be in our next release.

Ah perfect, thank you!
