### ISSUE TITLE
Change reset a single skill in skill tracker to be via right click

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1625]
Currently (as far as I know) you can only reset all on the skill tracker. Would be nice if you could only reset a single skill.

Also by skill tracker i mean the plug-in on the sidebar that tracks xp/hr, xp till level/actions left etc. if anyone wondered what I was talking about

**Comment by Kamielvf** [comment]
Click the skill icon. I don't like this behaviour but thats how it works atm.

**Comment by oojava** [comment]
By clicking on the skill icon itself you can reset

**Comment by Stickaplex** [comment]
ye id much rather it be right click. would be a lot smoother imo

**Comment by alecsolder** [comment]
Trying to address this in #1743

**Comment by deathbeam** [comment]
This was resolved
