### ISSUE TITLE
Mining Plugin Timer Not functioning Correctly in MLM

### ISSUE THREAD

**Issue by Instapwnx** [runelite/runelite#16263]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Mining Plugin in Runelite not properly displaying timer in MLM. Nodes refresh at around %70 of the timer pie chart.

### Screenshots or videos

![MLM moment before timer refresh](https://user-images.githubusercontent.com/125080284/218164135-e87dcf86-2e33-4312-88d2-069c49bc0491.PNG)

### RuneLite version

Runelite version 1.9.10

Oldschool Revision: Rev 211

Launcher version 2.1.3

**Comment by Alexsuperfly** [comment]
veins respawn randomly from 150 to 277 ticks after depleting, the green color shows its possible, the full chat shows the max time

**Comment by Instapwnx** [comment]
> veins respawn randomly from 150 to 277 ticks after depleting, the green color shows its possible, the full chart shows the max time

Okay, thank you, I was unaware of that.
Is there any reason why the mobile implementation allows for exact respawn timers but the mining plugin on runelite does not?

**Comment by Nightfirecat** [comment]
Some data is sent to the enhanced client (steam and mobile) which is not sent to the Java client, that may be among it.
