### ISSUE TITLE
XP Tracker post 99 percentage incorrect

### ISSUE THREAD

**Issue by SandroVA** [runelite/runelite#16271]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

Percentages for skills post 99 seem incorrect. 

### Screenshots or videos

![](https://i.imgur.com/io8apOk.png) ![](https://i.imgur.com/11XJotr.png)

### RuneLite version

Runelite: 1.9.10
Launcher: 2.4.2

**Comment by Nightfirecat** [comment]
What are your ingame xp goal settings? I haven't encountered this issue myself.
