### ISSUE TITLE
Random event plugin not notifying on Surprise Exam

### ISSUE THREAD

**Issue by evanc5** [runelite/runelite#16282]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I have gotten two Surprise Exam random events and one Genie today, and have my settings set to notify me on Genie and Surprise Exam. However, I have not gotten notified about the Surprise Exam, though I did get notified about the Genie.

### RuneLite version

RuneLite version: 1.9.10
Launcher version: 2.1.3

### Logs

[client.log](https://github.com/runelite/runelite/files/10762706/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10762707/launcher.log)

**Comment by evanc5** [comment]
![image](https://user-images.githubusercontent.com/11150077/219545134-1488e5c7-9c73-49f1-aa92-4f6190142b41.png)

+ screenshot with a third Surprise Exam today (herblore xp go brr I guess)

**Comment by Nightfirecat** [comment]
Under RuneLite settings, do you have "Send notifications when focused" enabled?

**Comment by evanc5** [comment]
I don't apparently, it's on now though. I seem to recall random events still showing a game message either way with "Game message notifications" on though? I might be mistaken though.

**Comment by Nightfirecat** [comment]
To my knowledge, those messages are only sent if a notification fires, which it would not when the client is focused.

**Comment by codestafa** [comment]
> I don't apparently, it's on now though. I seem to recall random events still showing a game message either way with "Game message notifications" on though? I might be mistaken though.

Does this still happen, or have you gotten a notification for the exam random event?

**Comment by evanc5** [comment]
I actually haven't gotten one since then, but I suspect this was user error to begin with.

**Comment by evanc5** [comment]
This was apparently user error as it turns out. Neat.
