### ISSUE TITLE
Missing Thrall Timer

### ISSUE THREAD

**Issue by RonnyTommy548** [runelite/runelite#16288]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I casted a thrall and I did not get a new thrall timer.

### Screenshots or videos

https://streamable.com/677174

https://streamable.com/ckvvv0
At the beginning of this clip you can see that a previous thrall timer was just ending, so it should be clear that I have Arceuus spells duration enabled in the base Timers plugin: 
![image](https://user-images.githubusercontent.com/104091491/219883457-4c4aadd6-7470-456e-85dc-26e73a5f5082.png)

### RuneLite version

RuneLite version: 1.9.10
Oldschool revision: Rev 211
Launcher version: 2.5.0

### Logs

[client.log](https://github.com/runelite/runelite/files/10774963/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10774964/launcher.log)

**Comment by Nightfirecat** [comment]
This will be fixed by #16251
