### ISSUE TITLE
Add prayer hiding to prayer reordering

### ISSUE THREAD

**Issue by Aelthien** [runelite/runelite#1628]
Would be handy to be able to hide prayers that I never use like retribution and the regeneration prayers.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by SalTor** [comment]
> https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

> Prayer hiding: Other clients don't do it and it would remove any possibility of missclicks, seems strong. Generally any hiding of in-game interactive interfaces is usually avoided.

Is there an exception for hiding entities in game in regards to this stance against "hiding in-game interactive interfaces"? I can see if this was meant to refer to menus, but I thought it was worth asking.

My interest in this feature request is to have a more 2007-like experience, and not seeing the prayers unique to OSRS would be appreciated.
