### ISSUE TITLE
Roof removal: Uzer Oasis, middle house

### ISSUE THREAD

**Issue by Trencha** [runelite/runelite#16296]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Roof removal plugin leaves a floating bit of upper wall for the middle house in the Uzer Oasis area that was recently added south of Uzer in preparation for Desert Treasure II.

### Screenshots or videos

Roofs showing:
![image](https://user-images.githubusercontent.com/2754136/219964778-8d0bee64-8d09-44fb-9414-f602c2c71e01.png)

With plugin on mouseover:
![image](https://user-images.githubusercontent.com/2754136/219964721-d7c3ac29-a849-4456-b15f-8e8a39bf2e76.png)

Without plugin, roofs hidden:
![image](https://user-images.githubusercontent.com/2754136/219964742-d9c982cf-62d8-4083-b916-b0c70cb2a49e.png)

### RuneLite version

Runelite version: 1.9.11.1
Launcher version: 2.1.0

**Comment by fiori** [comment]
@Nightfirecat @Trencha I left a pull request with the bug fix, let me know if you need something else to be done to resolve this issue.

**Comment by raiyni** [comment]
added in 0dd6d6916cef6cd158be9d64f277cfa066075ddb
