### ISSUE TITLE
Clue helper is not properly hidden

### ISSUE THREAD

**Issue by promitchell** [runelite/runelite#1629]
Was doing an Elite clue. Clue feature couldn't tell me where the coordinate was. Switched to OSB to quickly get the clue done. When I switched back to RuneLite it still thought I had the Elite Clue so the box that told me to go to the highlighted area or whatever was still up and I can't get rid of it even if I log in and out or turn the feature on or off.

**Comment by HypoxiaOSRS** [comment]
Can you post a screenshot?

**Comment by deathbeam** [comment]
This will be closed by #1493

**Comment by deathbeam** [comment]
Fixed in #1493
