### ISSUE TITLE
Magic Training Arena - Telekinetic room not working

### ISSUE THREAD

**Issue by trev-rock** [runelite/runelite#16315]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 10

### Bug description

I was trying to do the telekinetic grab room and nothing is appearing i tried restarting and everything asl well.

### RuneLite version

RuneLite version 1.9.11.2
Launcher version 2.5.0

**Comment by Felanbird** [comment]
Cannot replicate, plugin loaded as expected
![image](https://user-images.githubusercontent.com/41973452/220820825-ff1f2ce1-311c-45ef-bdfb-8a6ccf269a68.png)

**Comment by jonathangarelick** [comment]
I can also confirm this is working as of July 2023.
