### ISSUE TITLE
New profile system has broken my setup

### ISSUE THREAD

**Issue by Laurens-W** [runelite/runelite#16329]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I was using a setup with multiple google accounts and seperate session and properties files: \AppData\Local\RuneLite\RuneLite.exe --clientargs "--sessionfile=xxx.session"
Since the new profiles feature i have two issues: 
* The same profile exists for both clients
* After trying to create two profiles from the two clients and failing miserably, i've now lost some inventory setups in one of the clients... I have also heard of this happening to people who don't use the setup with different session files.

### RuneLite version

Runelite version: 1.9.11.2
Launcher version: 2.5.0

**Comment by Laurens-W** [comment]
I've tried manually fidgetting around with the new profiles.json and properties file but haven't yet investiged how they are parsed, haven't gotten it to work as i'd expect just yet.

**Comment by SwolePatrolOSRS** [comment]
I'm having the same issue. I had the same setup as you. 2 different google accounts with 2 different "profiles" via the shortcut session/properties method.

RL official profiles drop, and somewhere along the line one of the settings files with my bank tag layouts etc got deleted/overwritten or something, now I can't find the second account's bank tag layouts anywhere.

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/General-Features#profiles

**Comment by raiyni** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.

**Comment by Laurens-W** [comment]
@raiyni so you're saying that an issue caused by a new feature release is not an issue, but a support question?

**Comment by Laurens-W** [comment]
> https://github.com/runelite/runelite/wiki/General-Features#profiles

Managed to figure this out and now it semi works, only issue I now have is with the inventory setups plugin.

**Comment by Nightfirecat** [comment]
According to discussion in discord, that's a known issue with that hub plugin that'll require code changes from the author to work properly when changing profiles

**Comment by Laurens-W** [comment]
Fair enough, i've made an issue on the appropriate project
