### ISSUE TITLE
Nullpointer Exceptions since update 1.9.12

### ISSUE THREAD

**Issue by corporate9601** [runelite/runelite#16328]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I can't compile runelite in intellij IDE anymore since the update. I tried creating a fresh project with the new runelite github files and when I compile I get 7 NullPointer exceptions:

[ERROR] Errors: 
[ERROR]   EnumDumperTest.test:68 NullPointer
[ERROR]   KitDumperTest.test:68 NullPointer
[ERROR]   StructManagerTest.test:61 » NullPointer
[ERROR]   TrackDumperTest.test:73 NullPointer
[ERROR]   WorldMapDumperTest.extract:70 NullPointer
[ERROR]   InterfaceSaverTest.testSave:53 NullPointer
[ERROR]   DisassemblerTest.test:66 NullPointer

I've tried using other JDK's but I haven't done java since highschool I'm not all that clued up in the java world so I'm really stuck and needing some assistance

this is without my custom plugin it's just runelite source in a fresh project. anyone else get this on windows 10?

can I post any more info about the issue?

### RuneLite version

RuneLite: 1.9.12

### Logs

[net.runelite.cache.StructManagerTest.txt](https://github.com/runelite/runelite/files/10832136/net.runelite.cache.StructManagerTest.txt)
[net.runelite.cache.TrackDumperTest.txt](https://github.com/runelite/runelite/files/10832137/net.runelite.cache.TrackDumperTest.txt)
[net.runelite.cache.util.Djb2Test.txt](https://github.com/runelite/runelite/files/10832138/net.runelite.cache.util.Djb2Test.txt)
[net.runelite.cache.util.XteaTest.txt](https://github.com/runelite/runelite/files/10832139/net.runelite.cache.util.XteaTest.txt)
[net.runelite.cache.WorldMapDumperTest.txt](https://github.com/runelite/runelite/files/10832140/net.runelite.cache.WorldMapDumperTest.txt)
[net.runelite.cache.definitions.savers.InterfaceSaverTest.txt](https://github.com/runelite/runelite/files/10832141/net.runelite.cache.definitions.savers.InterfaceSaverTest.txt)
[net.runelite.cache.definitions.savers.ScriptSaverTest.txt](https://github.com/runelite/runelite/files/10832142/net.runelite.cache.definitions.savers.ScriptSaverTest.txt)
[net.runelite.cache.EnumDumperTest.txt](https://github.com/runelite/runelite/files/10832143/net.runelite.cache.EnumDumperTest.txt)
[net.runelite.cache.fs.ContainerTest.txt](https://github.com/runelite/runelite/files/10832144/net.runelite.cache.fs.ContainerTest.txt)
[net.runelite.cache.fs.flat.FlatStorageTest.txt](https://github.com/runelite/runelite/files/10832145/net.runelite.cache.fs.flat.FlatStorageTest.txt)
[net.runelite.cache.fs.jagex.DataFileTest.txt](https://github.com/runelite/runelite/files/10832146/net.runelite.cache.fs.jagex.DataFileTest.txt)
[net.runelite.cache.fs.jagex.DiskStorageTest.txt](https://github.com/runelite/runelite/files/10832147/net.runelite.cache.fs.jagex.DiskStorageTest.txt)
[net.runelite.cache.fs.jagex.IndexFileTest.txt](https://github.com/runelite/runelite/files/10832148/net.runelite.cache.fs.jagex.IndexFileTest.txt)
[net.runelite.cache.fs.StoreLoadTest.txt](https://github.com/runelite/runelite/files/10832149/net.runelite.cache.fs.StoreLoadTest.txt)
[net.runelite.cache.fs.StoreTest.txt](https://github.com/runelite/runelite/files/10832150/net.runelite.cache.fs.StoreTest.txt)
[net.runelite.cache.InterfaceManagerTest.txt](https://github.com/runelite/runelite/files/10832151/net.runelite.cache.InterfaceManagerTest.txt)
[net.runelite.cache.io.OutputStreamTest.txt](https://github.com/runelite/runelite/files/10832152/net.runelite.cache.io.OutputStreamTest.txt)
[net.runelite.cache.item.ItemSpriteFactoryTest.txt](https://github.com/runelite/runelite/files/10832153/net.runelite.cache.item.ItemSpriteFactoryTest.txt)
[net.runelite.cache.ItemManagerTest.txt](https://github.com/runelite/runelite/files/10832154/net.runelite.cache.ItemManagerTest.txt)
[net.runelite.cache.KitDumperTest.txt](https://github.com/runelite/runelite/files/10832155/net.runelite.cache.KitDumperTest.txt)
[net.runelite.cache.MapDumperTest.txt](https://github.com/runelite/runelite/files/10832156/net.runelite.cache.MapDumperTest.txt)
[net.runelite.cache.MapImageDumperTest.txt](https://github.com/runelite/runelite/files/10832157/net.runelite.cache.MapImageDumperTest.txt)
[net.runelite.cache.ModelDumperTest.txt](https://github.com/runelite/runelite/files/10832158/net.runelite.cache.ModelDumperTest.txt)
[net.runelite.cache.models.JagexColorTest.txt](https://github.com/runelite/runelite/files/10832159/net.runelite.cache.models.JagexColorTest.txt)
[net.runelite.cache.models.ObjExporterTest.txt](https://github.com/runelite/runelite/files/10832160/net.runelite.cache.models.ObjExporterTest.txt)
[net.runelite.cache.NpcManagerTest.txt](https://github.com/runelite/runelite/files/10832161/net.runelite.cache.NpcManagerTest.txt)
[net.runelite.cache.ObjectManagerTest.txt](https://github.com/runelite/runelite/files/10832162/net.runelite.cache.ObjectManagerTest.txt)
[net.runelite.cache.script.assembler.AssemblerTest.txt](https://github.com/runelite/runelite/files/10832163/net.runelite.cache.script.assembler.AssemblerTest.txt)
[net.runelite.cache.script.disassembler.DisassemblerTest.txt](https://github.com/runelite/runelite/files/10832164/net.runelite.cache.script.disassembler.DisassemblerTest.txt)
[net.runelite.cache.script.InstructionsTest.txt](https://github.com/runelite/runelite/files/10832165/net.runelite.cache.script.InstructionsTest.txt)
[net.runelite.cache.SoundEffectsDumperTest.txt](https://github.com/runelite/runelite/files/10832166/net.runelite.cache.SoundEffectsDumperTest.txt)
[net.runelite.cache.SpotanimDumperTest.txt](https://github.com/runelite/runelite/files/10832168/net.runelite.cache.SpotanimDumperTest.txt)
[net.runelite.cache.SpriteManagerTest.txt](https://github.com/runelite/runelite/files/10832169/net.runelite.cache.SpriteManagerTest.txt)

**Comment by corporate9601** [comment]
if I disable tests in maven I can build, but then when I run it's a black screen inside the runelite client UI. there's another "null pointer exception" in some overlay class here's a piece of the error

Caused by: java.lang.NullPointerException: null
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:392)
	at net.runelite.api.overlay.OverlayIndex.<clinit>(OverlayIndex.java:45)
	... 8 common frames omitted

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
