### ISSUE TITLE
Runelite client automatically linked to an e-mail

### ISSUE THREAD

**Issue by Senken12** [runelite/runelite#16326]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

I normally don't play with my account linked to an e-mail address syncing with the Runelite servers, but my client suddenly logged itself in without getting confirmation and cleared all of my settings

### RuneLite version

RuneLite 1.9.11.2
Launcher 2.1.3

**Comment by Felanbird** [comment]
What happens if you log out

**Comment by Senken12** [comment]
The client settings stay the same, but now logged out. All settings still lost

**Comment by Felanbird** [comment]
You can be better helped for this in the discord
![image](https://user-images.githubusercontent.com/41973452/221373292-659c7b87-eef2-400b-95e3-e1974c6535a9.png)

**Comment by Espionage724** [comment]
Was this figured out? I don't feel like digging through the mess of Discord. This seems like a security issue.

**Comment by Adam-** [comment]
> Was this figured out? I don't feel like digging through the mess of Discord. This seems like a security issue.

We have no evidence that this actually happens. This user reported this to Discord and we concluded they had had the account plugin off, and it turned on unexpectedly due to them creating a new profile.

If you have a security issue to report, please email `adam@runelite.net`
