### ISSUE TITLE
Item Stats plugin shows incorrect value for Forgotten Brew with boosted Prayer level

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#16335]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Forgotten Brews restore prayer points up to 5% above unboosted prayer level. If prayer points are already boosted above that, e.g. with an Ancient Mace special attack, the Item Stats plugin will show the potion as draining prayer points instead of restoring 0.

### Screenshots or videos

![2023-03-01-03-31-25](https://user-images.githubusercontent.com/33790641/222127612-41c64304-a825-44b0-b448-36b881843a5f.png)

### RuneLite version

RuneLite version: 1.9.11.2
Launcher version: 2.6.2

**Comment by Nightfirecat** [comment]
This is probably also an issue with ancient brews. I'll look into it.

**Comment by Nightfirecat** [comment]
Fixed in 99af10cbd3
