### ISSUE TITLE
Random event notifications

### ISSUE THREAD

**Issue by king-koda** [runelite/runelite#1634]
Title

**Comment by deathbeam** [comment]
First part is duplicate of #1469, second part is already implemented.

**Comment by king-koda** [comment]
even for random events? or like a filter so you aren't notified about drunken dwarf etc

**Comment by deathbeam** [comment]
no, that is why you should create separate issues for multiple feature requests. Just edit your issue to just contain the request for random event notifications.

**Comment by couxo** [comment]
and add toggles to which randoms you would or wouldn't want to be notified on.

**Comment by damane888** [comment]
Can this be added? I like A friend strategy to get stamina pots on an ironman - in the long term by random event. Its seriously a good idea.

**Comment by king-koda** [comment]
Yeah when I was on my iron man is when I thought of it tbh because I don't care about dwarf but maze and shit are great to be notified about.

**Comment by SirGirion** [comment]
I will start development on this one

**Comment by JJGrootveld** [comment]
Any progress on this issue? @SirGirion

**Comment by dylanvoll** [comment]
I picked up this feature request a few days ago, the development is almost done. I should have this PR'd soon.

**Comment by dylanvoll** [comment]
I've submitted a PR for this request.

https://github.com/runelite/runelite/pull/7755

**Comment by iRoxor** [comment]
To be honest, I would be fine with notifying the player if a Random Event NPC appeared regardless of who it is for.

This implementation could suffice temporarily until a more practical solution is found.
