### ISSUE TITLE
Add plugin to highlight agility shortcuts

### ISSUE THREAD

**Issue by Brezzoff** [runelite/runelite#1635]
**Quick example:**

![](https://i.imgur.com/e8DAZ6f.png)

**Comment by MESLewis** [comment]
Would the agility plugin be the best place for this to be added?

**Comment by Brezzoff** [comment]
Probably, keeps the list shorter

**Comment by Bartvhelvert** [comment]
Would be nice if shortcuts you can do would be green and shortcuts you can't do would be red

**Comment by MattyJacques** [comment]
As an extension of @Bartvhelvert suggestion, would it be possible to change the minimap icon with the same idea? So you don't get there and then find out you can't do it. 

So instead of the green arrow shortcut icon we could just change the arrow to red if our agility level is not high enough

**Comment by ShaunDreclin** [comment]
resolved in #1807, should be closed
