### ISSUE TITLE
Clue tip out of date

### ISSUE THREAD

**Issue by Dharr223** [runelite/runelite#16359]
### Type

Other

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Minor bug. 

Just doing a hard clue scroll in the wilderness. Noticed that the

19 degrees 00 minutes north
27 degrees 13 minutes east 

clue says to dig "North of Venenatis".
Just thought the tooltip should be updated. 

### Screenshots or videos

![image](https://user-images.githubusercontent.com/7830532/223870765-4f8d7b4f-c1fc-4cd6-8960-6e1ba3875bd4.png)

### RuneLite version

Runelite version 1.9.11.2
Launcher version: 2.6.1

**Comment by Nightfirecat** [comment]
Fixed by #16323
