### ISSUE TITLE
Lost all my account settings

### ISSUE THREAD

**Issue by ragnarokatz** [runelite/runelite#16361]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

On my personal computer, I use runelite with the account plugin enabled, and logged into my runelite account, and has been doing so for a long time. I assume that my settings have always been saved to the cloud.

Today I downloaded runelite client on my wife's computer. I logged into my runelite account on my wife's computer. My settings didn't sync up. I thought it was strange, so I went back to my own computer, and opened up runelite client. All my settings are gone and went back to the default.

I clearly remember the settings used to be stored under `.runelite/profiles/<email>/settings.properties`, however, when I checked, it seems that my last sync time was Feb 18, 2023, which is incorrect because I play everyday.
![image](https://user-images.githubusercontent.com/33646954/224180817-151379a3-14a3-40e6-9be1-451289bb692e.png)

and somehow there appears to be a second folder named `profile2` under my `.runelite` folder, with settings updated. the new files look like these:
![image](https://user-images.githubusercontent.com/33646954/224181075-f9a8ac9f-455c-4630-9320-de980b54fd29.png)

Is my data lost? can I recover what I changed from Feb 18 to today (March 9)?

### RuneLite version

RuneLite version: 1.9.12
Launcher version: 2.3.0
(my computer)

**Comment by Felanbird** [comment]
Github is for technical issues with the client/launcher - join the discord for support
![image](https://user-images.githubusercontent.com/41973452/220680975-ebe95451-e020-4d35-822e-9b7df6561d27.png)

**Comment by ragnarokatz** [comment]
thanks.

I just checked something. I logged into my runelite account on the web, and my settings are indeed saved to the cloud. This barbarian assault tag is something i created after Feb 18:

![image](https://user-images.githubusercontent.com/33646954/224182477-05a50689-b0aa-4a30-bdfc-717c10678509.png)

I"ll make a post in #support channel and link it back to this issue.

**Comment by ragnarokatz** [comment]
resolved. I found my settings in my second config profile. Closing.
