### ISSUE TITLE
Stall pickpockets not showing up in loot tracker

### ISSUE THREAD

**Issue by Bart123456789** [runelite/runelite#16360]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

Dear support,

I hope this is the correct place to create this ticket :)

When you pickpocket a stall, the loot tracker while never report the thieving action and also not display the amount of action done in the loot tracker?

**How to test:**
1. Teleport to Ardougne
2. Pickpocket a stall
3. No record shows up in the loot tracker

Greetings,

Bart

### Screenshots or videos

![image](https://user-images.githubusercontent.com/8875745/224131843-013cd0cd-e6f5-4a18-a113-fb28e29659b0.png)

### RuneLite version

Runelite version:1.9.12
Launcher version: 2.1.3

**Comment by Nightfirecat** [comment]
You're not picking a stall's pockets, they don't have pockets to pick.

On a more serious note, stalls are different from pickpocketing. So far we haven't seen reason to add loot tracking for them

**Comment by Bart123456789** [comment]
@Nightfirecat 

It would be nice if you are going for the rocky pet, you can somehow track how many stalls you did thief. Now it does not count it anywhere. And stalls are the fastest way to get the pet!

And if you steal from a stall It's still loot you get, the same as you pickpocket a NPC, so it's a little odd it's not showing up in the loot tracker. It should not be that big kind of implementation right, and with the implementation then you have no missing ends. Would be very nice to see at least the amount of stalls somewhere you did :)
