### ISSUE TITLE
Boss (and other) hp not displaying

### ISSUE THREAD

**Issue by sbertram** [runelite/runelite#16365]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

HP will not show on certain bosses (I have recognised this most at Zulrah and muttadile), as well as at behemoth hellrats and the dialogue of Mawnis Burowgar giving jester commands during freminnik exiles not showing up. I have tested this between base client and with runelite with the above glitches not occuring on the base client.

### RuneLite version

Runelite versions 1.9.12

### Logs

[launcher.log](https://github.com/runelite/runelite/files/10943231/launcher.log)
[client.log](https://github.com/runelite/runelite/files/10943232/client.log)

**Comment by raiyni** [comment]
You've got a lot of phub plugins installed and is likely one of them. You are getting a lot of errors from `spawn predictor` as well. You can start by disabling that one or going one by one on them. For further help join our discord.
