### ISSUE TITLE
Zoom speed not updating ingame

### ISSUE THREAD

**Issue by yoshi-isle** [runelite/runelite#16379]
### Type

Incorrect behavior

### Operating System

None

### OS Version

Windows 10

### Bug description

Zoom speed is not updating ingame when changing the value

### Screenshots or videos

![image](https://user-images.githubusercontent.com/123754082/225317811-bef26015-21fe-4bff-95ba-1b7770caa7f0.png)

### RuneLite version

RuneLite: 1.9.14
Launcher: 2.1.3

**Comment by abextm** [comment]
`1.9.14` is not a version of RuneLite.

The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
