### ISSUE TITLE
zoom speed isn't changing. scroll is very slow

### ISSUE THREAD

**Issue by yoshi-isle** [runelite/runelite#16378]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Zoom speed isn't updating properly ingame when changing the value

### Screenshots or videos

![image](https://user-images.githubusercontent.com/123754082/225317297-0bb5151f-e156-45ed-9019-2c2d260f04f5.png)

### RuneLite version

latest

**Comment by abextm** [comment]
`latest` is not a version
