### ISSUE TITLE
Kalphite Queen ironman instance ground items indicates wrong time

### ISSUE THREAD

**Issue by harbingerofme** [runelite/runelite#16375]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

In the KQ lair for ironmen, the "Ground items" timer indicates a 30 minute despawn timer, but items despawn after 3 minutes here.

### RuneLite version

Runelite version: 1.9.12
Oldschool version: Rev 212
Launcher version: 2.1.3

**Comment by AdamRWeinstein** [comment]
I've verified that the ironman instance of the KQ Lair has a dropped item despawn time of 3 minutes and loot despawn time of 2 minutes. 

This will be my first time working with github, but I've found the method and hopefully done the clone/remote/checkout stuff correctly. Will try to fix then submit a pull request citing this issue #
