### ISSUE TITLE
Minimap is transparent when fully zoomed out

### ISSUE THREAD

**Issue by cwjoshuak** [runelite/runelite#16380]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When in certain areas, the minimap becomes transparent. It appears fine when the minimap is at default zoom, but is transparent at max zoomed out + up to 2~3 scroll clicks in.

Can recreate in Ardougne and Seers areas.
Also occurs in safe mode.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/15935660/225328986-0daee9b2-917f-470c-8954-da6ed6dffd47.png)
![image](https://user-images.githubusercontent.com/15935660/225329080-d5bc29e7-ada9-4311-8698-01f2100f2f68.png)

### RuneLite version

RuneLite version: 1.9.13
Oldschool revision: Rev 212
Launcher version: 2.6.2

### Logs

[client.log](https://github.com/runelite/runelite/files/10980500/client.log)
[launcher.log](https://github.com/runelite/runelite/files/10980508/launcher.log)

**Comment by Jure-Pokerznik** [comment]
I have the same issue on resizable mode. On fixed mode the image loops around as you turn your camera. Attaching images.
Fixed:

![2023-03-15 14_44_20-RuneLite - Alch Coins](https://user-images.githubusercontent.com/16636240/225407454-25033377-571e-4ee5-bdd8-7aa12c7fa708.png)
![2023-03-15 19_25_39-RuneLite - Alch Coins](https://user-images.githubusercontent.com/16636240/225407462-2a5dfa9b-779a-4908-aee4-3618c86627dc.png)

Resizeable:
![2023-03-15 19_26_09-RuneLite - Alch Coins](https://user-images.githubusercontent.com/16636240/225407464-472d23b9-633d-4d4a-a982-9dedba12e913.png)

I have no issues when Minimap -> Zoom is disabled. The issue doesn't always happen, only sometimes and it's easiest to reproduce by teleporting around (For example, sometimes during a farm run in Morytania I get the issue, or when teleporting to Camelot / Ardy)

**Comment by Nightfirecat** [comment]
This has been fixed by an internal change and released with 1.9.13.1. Anyone still experiencing this issue should restart their client.
