### ISSUE TITLE
Menu Entry Swapper does not work on Zanaris fairy ring

### ISSUE THREAD

**Issue by Jimbimanim** [runelite/runelite#1639]
Menu Entry Swapper plugin normally puts "Last Destination" as the left click option, but on the Zanaris fairy ring "Configure" is the left click option as it would be with the plugin off.
I think this maybe has something to do with the fact that this particular fairy ring only has the options Configure/Last Destination/Examine rather than the Zanaris/Last Destination/Configure/Examine that every other fairy ring has

This probably isn't needed for this issue, but as per your submission guidelines i am on linux mint 18.3 using java 1.8.0_162 and runelite 1.3.4.1

**Comment by Gamer1120** [comment]
I will work on this for a bit. I think we want a separate option for the Zanaris fairy ring, since I could see some people preferring Configure and some people preferring Last Destination.

**Comment by Gamer1120** [comment]
This needs more feedback from the community. The specific question to answer is: "Should the Zanaris fairy ring have a separate option in the Menu Entry Swapper plugin?"
A more detailed explanation is: "The options on the Fairy ring in Zanaris are "Configure" and "Last-destination". The options on all other Fairy rings are "Zanaris", "Configure" and "Last-destination". In other words, would you want to be able to select "Last-destination" on the Fairy ring in Zanaris and select "Zanaris" on all other Fairy rings (or Configure on the Zanaris Fairy ring and Last-destination on all others)?"
A scenario in which it would be useful to be separate is when you want to fish Karambwans and bank in Zanaris. You'd want Zanaris on the regular Fairy ring, and Last-destination on the Zanaris Fairy ring.

**Comment by Jimbimanim** [comment]
I say yes, doing karambwan fishing is actually what prompted me to report this in the first place and having both fairy rings able to be left clicked would be great. A separate option for Zanaris ring sounds great

**Comment by Neokolzia** [comment]
I believe this is still open and unfufillled in the game if someone is willing to tackle it!  it would certainly help individuals looking to use Zanaris for banking (ensouled heads, karambwans etc)

**Comment by Gamer1120** [comment]
This issue is still not fixed. There is still no distinction between the Zanaris Fairy ring and the other fairy rings. That is what this was about. I checked out master, and saw it for myself. I made a quick MSPaint mock-up of what I mean::
![image](https://user-images.githubusercontent.com/9074448/43659064-1f89b952-975b-11e8-802d-10f6191708ae.png)

**Comment by deathbeam** [comment]
Well, the original report was for the zanaris swap simply working, so it is resolved. For separate option for zanaris fairy ring, open up new issue I guess.

**Comment by Gamer1120** [comment]
You're right. My apologies. The comments in this point should have been in another issue. I'll open a new issue in a couple of minutes.
