### ISSUE TITLE
Screenshotting Issue for Chambers of Xeric and Cox Scouter external

### ISSUE THREAD

**Issue by Hyped-Impact** [runelite/runelite#16413]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Chambers of Xeric & Cox Scouter External both seem to be unresponsive to my hotkey for screenshotting the layout. It use to work for me and out of no where is quit working. I set a hotkey to numpad+ and that didn't work then moved it to a bunch of different ones to check and insured that it was set to copy to clipboard once the hotkey was pressed to screenshot layout, but nothing goes to the clipboard to be posted. Not sure what seems to be the root cause of this but could use some help.

### RuneLite version

Runelite version: 1.9.13.1
Launcher version: 2.6.1

### Logs

[client.log](https://github.com/runelite/runelite/files/11068638/client.log)
[launcher.log](https://github.com/runelite/runelite/files/11068639/launcher.log)

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
