### ISSUE TITLE
Add option to MLM plugin to hide top/bottom level mining spots

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1642]
![image](https://user-images.githubusercontent.com/9074448/38902149-973569e4-429f-11e8-91ec-5959aa2c2001.png)
It's very difficult to see which spots are mineable. Maybe it could even auto-detect whether you are mining on the upper or lower level.

**Comment by deathbeam** [comment]
This should not be an option, but auto-detected and the only behaviour.

**Comment by sethtroll** [comment]
For anyone attempting, the upper level is on the same plane (which is why you can see everyone) so you would probably need to check the object height

**Comment by Gamer1120** [comment]
First thing I found out while working on this is that ore veins are not close to each other, which was unexpected for me. The ore veins in the motherlode mine are ORE_VEIN_26661 through ORE_VEIN_26664 respectively. I decided to give each of these a different icon to see whether I could do anything with them. It looked like this:
![image](https://user-images.githubusercontent.com/9074448/38937198-ee05e996-4322-11e8-9716-460353a22716.png)
This means I cannot choose to render either the top or bottom level based on their ORE_VEIN id's. I also found out that client.getPlane() always returns 0, whether you are on the lower or the upper level. This makes it difficult to distinguish between the upper and lower level.

**Comment by Gamer1120** [comment]
@Adam- Which method would I need to call for that? I can only find a getX and a getY, but no such thing as height.

**Comment by Gamer1120** [comment]
Okay, I found out that the following code:
`private void renderVein(Graphics2D graphics, WallObject vein)
	{
		if( Perspective.getTileHeight(client, vein.getX(), vein.getY(), vein.getPlane()) > -500) {
			Point canvasLoc = Perspective.getCanvasImageLocation(client, graphics, vein.getLocalLocation(), miningIcon, 150);

			if (canvasLoc != null) {
				graphics.drawImage(miningIcon, canvasLoc.getX(), canvasLoc.getY(), null);
			}
		}
	}`
only makes the client render everything on the bottom floor. Let's see where I can take this. I know this doesn't comply with coding standards and checkstyle yet.

**Comment by Adam-** [comment]
Fixed in #1661
