### ISSUE TITLE
Clue scroll plugin doesn't recognize Eastfloor spade

### ISSUE THREAD

**Issue by Ammako** [runelite/runelite#16468]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

You can use the Eastfloor spade from the Easter event when doing treasure trails. The plugin doesn't see it and thinks you have no spade, and yells at you for it.

### RuneLite version

Runelite version: 1.9.13.3
Launcher version: 2.5.0

**Comment by geheur** [comment]
Already added and will be in the next release: f0dbd63

**Comment by Nightfirecat** [comment]
This is already in master ala #16464, and will work the way you expect it to after we next release.
