### ISSUE TITLE
Slayer plugin forgets starting amount

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#16469]
### Type

Incorrect behavior

### Bug description

The slayer plugin seems to forget the starting task amount between play sessions. I'm not sure what triggers it, but have experienced it recently, after integration of 1f6ae893d732cf3a022fe6d9662cd2a42ff2b217.

### RuneLite version

RuneLite version: 1.9.14-SNAPSHOT (dev build; no changes to slayer plugin)

**Comment by geheur** [comment]
Happens for me when I disconnect and reconnect without getting to the login screen. Here's a log of some relevant variables when this happens:
```
loginflag false
varbitchanged: slayer task size varp 0
varbitchanged: slayer task creature varp 0
updatetask: VarPlayer.SLAYER_TASK_SIZE is 0
updatetask: VarPlayer.SLAYER_TASK_SIZE is 0
varbitchanged: slayer task size varp 104
varbitchanged: slayer task creature varp 95
updatetask: VarPlayer.SLAYER_TASK_SIZE is 104
updatetask: VarPlayer.SLAYER_TASK_SIZE is 104
loginflag false
```
