### ISSUE TITLE
Bank withdraw and deposit menu swap

### ISSUE THREAD

**Issue by Aelthien** [runelite/runelite#1647]
Can we have the option to make the last withdraw-x amount and deposit all the left-click options? This would be very handy for herblore and fletching and banking in general. I don't see any issues with this feature since mobile is getting this exact thing.

**Comment by e-102** [comment]
It would helpful in crafting as well when making jewelry instead of scrolling down to 'make all' and instead have it be the first option.

**Comment by Adam-** [comment]
As discussed previously I do not think we are comfortable with doing this. Jagex will release it if they want.

**Comment by Aelthien** [comment]
I guess I'll just do it on mobile if not. :D

**Comment by Adam-** [comment]
Jagex has added this now.
