### ISSUE TITLE
Slayer plugin shows incorrect jad/zuk task amount

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#16470]
### Type

Incorrect behavior

### Bug description

Some users have reported that recently the slayer plugin will show a very incorrect jad or zuk task length, such as 154/155. It seems to always be a large overall task length with one less remaining than the "original" length.

Reproduction steps are unknown, but this may be related to getting assigned a tzhaar task, walking away from a slayer master before completing the dialog prompting the player to switch to a jad/zuk task, then returning to the master and using "Talk-to" to resume that dialog and choosing to switch to a boss task.

**Comment by 6enny6** [comment]
i have this issue with every single zuk task i get, can confirm its not related to walking away and then using talk-to, it just instantly shows incorrect number on the infobox and !task command. Ill try pay attention from now on to the numbers and see if its related to a previous slayer task or anything
