### ISSUE TITLE
Low FPS with RX 6950 XT

### ISSUE THREAD

**Issue by tivervac** [runelite/runelite#16480]
### Type

Performance

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I'm experiencing quite low performance, down to 10-15 fps depending on the area. My system has an RX 6950 XT, i7-9700k, m2 NVMe SSD, and 32 GB or DDR4 ram. Other games run fine as expected, also only running at 1080p on one screen.

With the 117 plugin I get to 15 fps and 100% GPU usage, without it, 30 FPS and 0% GPU usage.

I made sure to:
* Disable integrated graphics in BIOS
* Try disabling model caching in 117
* Unlocked FPS
* Disable windows defender
* Disable hardware acceleration
* Try turning down 117 settings
* Try on RuneLite safemode
* Made sure I'm running the 64bit runelite client
* Tried without plugins
* Update all drivers and install windows updates

Not sure what else I can do.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/3389524/230788252-79845076-30ff-4b8e-b3ef-376bbf10c3b9.png)

### RuneLite version

RuneLite version: 1.9.13.3
Oldschool revision: rev 212
Launcher version: 2.6.3

### Logs

[launcher.log](https://github.com/runelite/runelite/files/11186027/launcher.log)
[client.log](https://github.com/runelite/runelite/files/11186028/client.log)

No JVM crashes

**Comment by aHooder** [comment]
This should be directed at 117 HD's repository instead: https://github.com/117HD/RLHD

**Comment by tivervac** [comment]
> This should be directed at 117 HD's repository instead: https://github.com/117HD/RLHD

Don’t think it should. Sure the fps with 117 is abysmal, but it’s also terrible without. The problem seems to be in runelite (or osrs?) first

**Comment by aHooder** [comment]
> > This should be directed at 117 HD's repository instead: https://github.com/117HD/RLHD
> 
> Don’t think it should. Sure the fps with 117 is abysmal, but it’s also terrible without. The problem seems to be in runelite (or osrs?) first

That's fair, I suppose. You can leave 117 HD out of it though, as RuneLite doesn't maintain plugin hub plugins. Feel free to join 117 HD's Discord (link in the repo) and we can try to diagnose this further.
