### ISSUE TITLE
Highlight Marks of Grace on Rooftop agility & Ground Item's not always highlighted

### ISSUE THREAD

**Issue by kleinaeinar** [runelite/runelite#1648]
Basicly what the title says, maybe add a big red box around a Mark of Grace.  I have made a workaround by highlighting it in Ground Items, but sometime it doesn't register the MoG, and doesn't give green text.  So if it would be possible to add a toggleable option to highlight MoG, it would be very nice.  

And since I have already mentioned it here, there is a bug where MoG isn't always highlighted from the Ground items settings.  Sometimes it shows the green text above it, and sometimes it doesn't.

If it is more convenient to have these in two separate tickets than please let me know and I will edit this and make another ticket for the bug.
![screenshot_33](https://user-images.githubusercontent.com/1994280/38907700-869f0b14-42ac-11e8-813c-9e682b2625cd.png)

**Comment by TheeWiki** [comment]
Really need this, or at bare minimum have a Minimap text displaying the item name

**Comment by sethtroll** [comment]
Added in #1837
