### ISSUE TITLE
2005 Interface Styles

### ISSUE THREAD

**Issue by tannerdino** [runelite/runelite#16489]
### Type

Other

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Incorrect icons for the clan chat tab, and prayer tab. Although interestingly the icons are correct in the settings menu.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/61213166/231877881-628d99d0-76dc-4b5f-b03b-e67272094ab6.png)

### RuneLite version

RuneLite version: 1.9.14
Launcher version: 2.1.3

**Comment by Felanbird** [comment]
Related #16486

As noted by the comment in that thread, the prayer icon was likely changed due to the upcoming prayer book(s) - not sure what caused the clan chat icon to revert.
