### ISSUE TITLE
2010 Interface Style Prayer Icon Incorrect

### ISSUE THREAD

**Issue by jdeerturner** [runelite/runelite#16486]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

2010 Version of "Interface Styles" plugin prayer icon is currently displaying the 2006 version.

### Screenshots or videos

WAS:
![image](https://user-images.githubusercontent.com/6800167/231530692-6b2825a7-5ce1-41b5-9eb9-c7762b367e01.png)

IS:
![image](https://user-images.githubusercontent.com/6800167/231530778-a85650e0-8b22-4c65-91e1-829f98c77f61.png)

### RuneLite version

RuneLite version 1.9.14
Oldschool revision: Rev 212
Launcher version: 2.4.2

**Comment by MESLewis** [comment]
Can confirm the prayer icon on ui stones stays as the default icon on all layouts and interface styles. Likely a change was made by Jagex to support the upcoming prayer book.
