### ISSUE TITLE
Freezing when switching Runelite profiles

### ISSUE THREAD

**Issue by nisan98** [runelite/runelite#16481]
### Type

Crash or hang

### Operating System

Windows

### OS Version

10

### Bug description

I currently play two accounts and therefore use two runelite profiles. When I try switching profiles (double clicking the profile I want to switch to), the game stutters and my clicks stop registering. I then have to force close the client using the Task manager. Once I reopen the client, the profile has correctly switched.

This was not a problem when I could create a shortcut on my desktop to a specific profile as I didn't need to use this "switching profile" functionality. However, I just created a Jagex Account to which I have added all of my Runescape accounts. Using a Jagex Account requires the use of the Jagex Launcher, and there doesn't seem to be a way to select which Runelite profile to open from the launcher (it always opens the last profile used). It is incredibly cumbersome and annoying to open multiple accounts right now.

### RuneLite version

Runelite version : 1.9.13.2
Launcher version : 2.6.1

### Logs

[client.log](https://github.com/runelite/runelite/files/11187192/client.log)
[launcher.log](https://github.com/runelite/runelite/files/11187196/launcher.log)

**Comment by nisan98** [comment]
I'd like to add that it only freezes when switching from a profile that is not the default one. If I switch from the default profile to my other profiles, the switch takes 1-2 seconds as expected.

**Comment by geheur** [comment]
Join the discord at runelite.net/discord, it's better for support questions like this.
