### ISSUE TITLE
117HD invisibility glitch

### ISSUE THREAD

**Issue by Azatramus** [runelite/runelite#16499]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

11

### Bug description

When using the alchemy spell with the Plugin 117HD people will become invisible for the duration of the animation. 

### Screenshots or videos

https://user-images.githubusercontent.com/50136801/232761753-974cb115-ecc9-4856-aa83-e84b5f3608d1.mp4

### RuneLite version

Most current update as of 4/18/2023 7:20 AM est

**Comment by Presc** [comment]
Can confirm the Plank Make spell also does this

**Comment by JimmehG** [comment]
Seems like it happens when combined with animation smoothing (I dont use it but clannies who use it have confirmed it)

**Comment by Felanbird** [comment]
Should be fixed https://github.com/runelite/plugin-hub/commit/5ff047e4fcc62c0a9e0c344a03ca3377141a4f25
