### ISSUE TITLE
Ground Markers Border Width Is Uncapped

### ISSUE THREAD

**Issue by leestran1995** [runelite/runelite#16497]
### Type

Other

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The Border Width setting for the Ground Markers plugin does not have a ceiling, letting users do silly things like this (Border Width: 150): 
![image](https://user-images.githubusercontent.com/41343559/232270044-5525777d-406d-4871-ba2a-dfb5e3e44f0f.png)

The border starts to take up the entirety of the player's vision around Border Width 1500

![image](https://user-images.githubusercontent.com/41343559/232270320-b69eae48-ef08-4a52-89f3-93d0c4def207.png)

Some pretty interesting behavior crops up in the millions, here's Border Width 10,000,000

![image](https://user-images.githubusercontent.com/41343559/232270611-79614817-1904-4b9d-8b2f-834d74225ad8.png)

Eventually the border just disappears completely, here's Border Width 1,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000,000

![image](https://user-images.githubusercontent.com/41343559/232270874-1bc987f2-46b5-4719-b4d2-bd0c64164327.png)

### RuneLite version

RuneLite version: 1.9.14
Launcher Version: 2.1.7

**Comment by raiyni** [comment]
Players play with different screen sizes and if they want to block their entire screen for whatever reason, that's their prerogative.

**Comment by leestran1995** [comment]
Fair enough!
