### ISSUE TITLE
UI Scaling not working properly on UltraWide Resolutions

### ISSUE THREAD

**Issue by pauloaguiar26** [runelite/runelite#16498]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10 Pro - 19044.2846

### Bug description

While using runelite on fullscreen on a ultrawide monitor the UI doesnt fit the game
![image](https://user-images.githubusercontent.com/32967591/232286665-7df1e44d-0b22-4374-bc4a-a92f79f01ecb.png)
However if resizing it will always fit till a certain point example: 
![image](https://user-images.githubusercontent.com/32967591/232286693-d0c77119-c6a5-4a10-81fc-d83c6cbe178f.png)

### RuneLite version

RuneliteVersion 1.9.14
Launcher Version 2.6.1

**Comment by Nightfirecat** [comment]
Are you sure you haven't moved the inventory widget? If you Alt+right-click it, does it go into position correctly at the ultra-wide resolution?

**Comment by pauloaguiar26** [comment]
After removing the interface it was still bouncing because it was moved freely when reseting the interface there is no more error, thx for the help
