### ISSUE TITLE
Automatic Screenshots fail to save

### ISSUE THREAD

**Issue by Pixie35** [runelite/runelite#16502]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Arch (Steam Deck)

### Bug description

Whilst running RuneLite is desktop mode on the Steam Deck, the screenshots are being automatically taken and notified as normal. However,  when going to folder to retrieve them, no screenshots are saved. 

No automatic screen shot has saved since 18 Feb 23. Interestingly that's the last day of saved logs too.

My gut feeling is that its a permissions issue with Linux but not sure.

### RuneLite version

RuneLite Version: 1.9.15
OS Rev: Rev 213
Launcher Version: 2.5.0

### Logs

[launcher.log](https://github.com/runelite/runelite/files/11263113/launcher.log)
[client.log](https://github.com/runelite/runelite/files/11263115/client.log)

**Comment by Nightfirecat** [comment]
Have you changed something on your system which might make `~/.runelite` read-only? I wouldn't expect the client to work properly if that were the case, but it stands to reason something has either made that directory unwriteable for you, or has pointed RuneLite to a different directory.

**Comment by Pixie35** [comment]
The folder is down as Owner rwx, with group as r-x. I assume RuneLite will run as Owner?

**Comment by Nightfirecat** [comment]
`0750` or greater permissions should be just fine. Have any other files/directories in `~/.runelite` been modified since Feb 18?

**Comment by Pixie35** [comment]
Ok apologies for not getting back, but burnout hit.
I have learnt more and messed around a bit and now have it working.

As Runelite runs as a Flatpak the settings needed to be tweaked, as expected. What I didn't know is where this was kept.
For those that need the directions:
System Settings > Search: Flatpak > Flatpak Permission Settings.
On Runelite, select All User files and change the drop down to Read/Write.

I will put a warning here, from how I understand how flatpaks work, Runelite can now read and write from any file held in the user area. This includes plugins within Runelite (devs I assume this is right?), so the standard "Don't install dodgy plugins" applies.
