### ISSUE TITLE
Unranked Group Ironmen are classed as normal accounts

### ISSUE THREAD

**Issue by Auenc** [runelite/runelite#16510]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Logging into an unranked group iron. 

When a plugin calls `client.getAccountType().isGroupIronman()` the method will return false. 

To replicate, I modified the `checkHerbBoxes` method in the the `DailyTasksPlugin` class to add a log:

```java
private void checkHerbBoxes(boolean dailyReset)
	{
		log.debug("is group ironman: " + client.getAccountType().isGroupIronman());
		if (client.getAccountType() == AccountType.NORMAL
			&& client.getVarpValue(VarPlayer.NMZ_REWARD_POINTS) >= HERB_BOX_COST
			&& (client.getVarbitValue(Varbits.DAILY_HERB_BOXES_COLLECTED) < HERB_BOX_MAX
			|| dailyReset))
		{
			sendChatMessage(HERB_BOX_MESSAGE);
		}
	}
```

When logging in to the game on a unranked group ironman we receive this output in the console:
```
DEBUG n.r.c.p.d.DailyTasksPlugin - is group ironman: false
```

### Screenshots or videos

![runelite-bug](https://user-images.githubusercontent.com/14826315/233160195-60c653d7-9d19-498d-8da6-84ff0c0b52e6.png)

### RuneLite version

RuneLite version: 1.9.16-SNAPSHOT
Launcher version: Unknown

**Comment by iProdigy** [comment]
Fixed by https://github.com/runelite/runelite/commit/b3ec120efa7a4ee67b019702a1c16db2cda6c4bf
