### ISSUE TITLE
runite golems become unclickable after respawning

### ISSUE THREAD

**Issue by PoisonedPotion** [runelite/runelite#16537]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

After a runite golems respawns you can't click on it. Tested this out on Vanilla client and it isn't an issue so I thought I'd mention it here. 

### Screenshots or videos

![runite golem bug 2](https://user-images.githubusercontent.com/131811963/234380281-5414024f-bf86-4ddc-99c4-08820cf627a9.png)

![runite golem bug](https://user-images.githubusercontent.com/131811963/234380262-75e5d6e1-7a82-4ac9-a48f-f729e7fa3737.png)

### RuneLite version

Runelite Version: 1.9.15.3
Runelite Launcher: 2.1.6

**Comment by Felanbird** [comment]
I cannot replicate this issue, it's very likely one of your plugin-hub plugins causing your problem. 

<details><summary>Images</summary>
<p>

![image](https://user-images.githubusercontent.com/41973452/234389349-95d4d608-ccd8-4500-a792-a12089882561.png)
![image](https://user-images.githubusercontent.com/41973452/234389377-53570ab9-8b28-41a7-a40b-73489e93a7af.png)
![image](https://user-images.githubusercontent.com/41973452/234389405-c0c2bb29-6909-482d-878e-8308006f3665.png)

</p>
</details> 



Try safe-mode:

Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by Nightfirecat** [comment]
I pushed a runtime config update in runelite/static.runelite.net@17c6fd87d685555cdb988def83a14b2e9a9b45f1 which should keep runite golems from having their menu entries hidden (via the `Remove dead npc menus` option) by the Menu Entry Swapper plugin. Can you re-launch your client and test this again? If this is working fine now, I'll commit this change to the client directly.

**Comment by PoisonedPotion** [comment]
Seems to be working now!
