### ISSUE TITLE
Mesa 23.02 causes GPU plugin to crash system

### ISSUE THREAD

**Issue by Cattimus** [runelite/runelite#16531]
### Type

GPU

### Operating System

Linux

### OS Version

Fedora 37 workstation 6.2.11

### Bug description

GPU: radeon 5600XT

**Problem:**
Upon updating to mesa 23.02, runelite will cause a GPU crash that will lock the system until it reboots. Runelite will launch properly until you get past the login screen. As soon as the game starts to render, the system will crash. This effects both the GPU plugin and 117 hd plugin.

I have only observed GPU crashing issues with runelite. Other games run as expected.
I have included the client and launcher logs for the testing I was doing to reproduce the issue, as well as a (truncated) system log that shows the GPU crash.

**Attempted solutions:**
- Disable 2d acceleration by passing `--mode=OFF`. (no effect)
- Run runelite.jar directly with openjdk 17. (no effect)
- Switch from GPU plugin to 117 hd. (no effect)
- Disable both GPU plugins. (fixes the issue but not ideal)
- Downgrade mesa from 23.0.2 to 22.2.2. (fixes)

**Temporary solution:**
Downgrade mesa from 23.0.2 to 22.2.2 - Reverting mesa version stops the crashes from happening completely.

### RuneLite version

RuneLite version: 1.9.15.3
Launcher version: 2.6.3

### Logs

[client.log](https://github.com/runelite/runelite/files/11302572/client.log)
[launcher.log](https://github.com/runelite/runelite/files/11302573/launcher.log)
[syslog.txt](https://github.com/runelite/runelite/files/11302574/syslog.txt)

**Comment by Adam-** [comment]
Have you tried reporting this to mesa? We've had success before with them fixing bugs, but someone has to report them.

**Comment by Cattimus** [comment]
@Adam- I have not yet reported this to mesa. I'm not entirely sure where the bug originates because I'm somewhat inexperienced, but as it only effected runelite I figured I would at least make the runelite devs aware. I can make a report in their issue tracker as well if you think there's a good chance it is a mesa bug.

**Comment by Adam-** [comment]
If your system locks up and crashes and require a reboot, it would at the very least be a mesa bug if not something much deeper. If you do file one, link to it here so we can track it.

**Comment by Cattimus** [comment]
I have filed a report of the same issue with the mesa maintainers [#8896](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8896).

**Comment by Adam-** [comment]
> I have filed a report of the same issue with the mesa maintainers [#8896](https://gitlab.freedesktop.org/mesa/mesa/-/issues/8896).

If you are able to bisect mesa that is probably very useful to them, considering they even have a issue label for bisected issues.

**Comment by Adam-** [comment]
Someone on Discord said that mesa 23.0.3 fixed it. Have you tried it?

**Comment by Cattimus** [comment]
Somebody also commented that on the mesa issue. I am waiting for 23.0.3 to hit stable on fedora repos, I will let you know once I'm able to test it.

**Comment by Cattimus** [comment]
Confirmed - updating to mesa 23.0.3 fixes the system hang issue.
