### ISSUE TITLE
5 Key not working in Runelite

### ISSUE THREAD

**Issue by jacobhosking** [runelite/runelite#16541]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The number 5 key on the num bar does not work in while using runelite. All other numbers work correctly and the number 5 works outside of RL. No hotkeys are set so not sure whats going on. 

### RuneLite version

1.9.15.3
2.6.3

### Logs

[client.log](https://github.com/runelite/runelite/files/11328804/client.log)
[launcher.log](https://github.com/runelite/runelite/files/11328805/launcher.log)

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Or on Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by jacobhosking** [comment]
Yes, it still has the same behavior in safe mode.

**Comment by jacobhosking** [comment]
Party plugin got mapped to 5 somehow. Thank you so much for your help!
