### ISSUE TITLE
Can't mine rock in Kourend Catacombs

### ISSUE THREAD

**Issue by PogueEthics** [runelite/runelite#16551]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The option to mine the rock shortcut inside kourend catacombs (the shortcut to get to the fire giants from the main statue teleport) is not there.

It's works just fine when I'mon mobile, but not when I'm on Runelite.

### Screenshots or videos

https://cdn.discordapp.com/attachments/772155164625731626/1102315093800259655/image.png

https://discord.com/channels/772155164123594763/772155164625731626/1102382171043410010

### RuneLite version

1.9.15.2
Rev 213
2.1.7

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Or on Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by PogueEthics** [comment]
The issue does not occur in safe mode.

Running in safe mode I can see the option to mine the rock.

**Comment by PogueEthics** [comment]
Ah, I figured it out. User error, apologies.

I had added an option to custom hide mine,Rocks due to a method I saw involving the mining guild.
