### ISSUE TITLE
Karamja lobster f2p

### ISSUE THREAD

**Issue by GabbeHags** [runelite/runelite#1656]
In karamja lobster spot f2p it only shows lobster on all hitboxes even if i need fishing net

**Comment by Adam-** [comment]
This was fixed in #1538

**Comment by GabbeHags** [comment]
But i can only see lobster and i have restarted my game and restarted my pc
and still only lobster in karamja


Den ons 18 apr 2018 16:24Adam <notifications@github.com> skrev:

**Comment by Kamielvf** [comment]
The fix will be in next release, so thursday.
