### ISSUE TITLE
Cannot map to the "tab" key

### ISSUE THREAD

**Issue by TheMagzuz** [runelite/runelite#16573]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Arch Linux 6.2.13 - i3 4.22 (xorg 21.1.8)

### Bug description

When attempting to set a keybind (e.g. in the key remapper plugin) to "tab", the focused field simply changes to the next field in the order rather than binding the key to tab.

### RuneLite version

RuneLite version: 1.9.16
Launcher version: 2.6.3

**Comment by ldahleen54** [comment]
I think the PR i created will address this for any plugins that have keybinds

**Comment by Adam-** [comment]
added in #16942
