### ISSUE TITLE
Can't turn off sound after the recent update

### ISSUE THREAD

**Issue by Mewlina** [runelite/runelite#16572]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Hi,
As mentioned in the title, there seems to be a problem with adjusting sound in runelite since the recent update, and I'd thought I'd let you know!

Thank you for your service!

### Screenshots or videos

https://github.com/runelite/runelite/assets/133117199/7187b7e6-cb36-4d40-accd-60361985f273

### RuneLite version

Runelite version: 1.9.15.3
OS revision: Rev 213
Launcher version: 2.6.2

**Comment by Bram91** [comment]
Restart your client.
