### ISSUE TITLE
Per-object basis 'Walk here' swap doesn't work on all objects

### ISSUE THREAD

**Issue by CopyPastaOSRS** [runelite/runelite#16595]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

1. Go to the Grand Exchange
2. Right + shift click the polling booth (Looks likely to be all polling booths, Varrock bank also has the same)
3. Swap left-click option from 'Use' to 'Walk here'
4. Left-click option on poll booth is still 'Use'

Swapping this on poll booths seems kind of useless. But I'm still curious if this is a generic issue affecting other objects were this feature would be useful. Could it be for objects that have multiple display states? I.e. poll booths can have the flag up or down. Based on if you have voted or not.

### Screenshots or videos

Before swap
![image](https://github.com/runelite/runelite/assets/66518222/1aacc685-f84e-4b2f-9796-48ed578c236f)

After swap
![image](https://github.com/runelite/runelite/assets/66518222/2a8aa119-4408-4d77-bf86-2d053bf303e6)

Original left-click is still there
![image](https://github.com/runelite/runelite/assets/66518222/068811e5-54da-472d-b63c-35a5fd18157c)

Option change was registered in chat
![image](https://github.com/runelite/runelite/assets/66518222/94f4b5bb-44dd-4bf1-82ef-7ac0a1a92f1f)

### RuneLite version

RuneLite version: 1.10.0.5
Launcher version: 2.1.7

### Logs

No warning or error messages logged when reproducing the issue

**Comment by geheur** [comment]
Probably same issue as https://github.com/runelite/runelite/pull/16592

It does affects other objects, someone else complained that it doesn't work on the pyramid plunder sarcophagus.

**Comment by Adam-** [comment]
fixed in #16592
