### ISSUE TITLE
Building door missing, possibly as a result of 1.10.0

### ISSUE THREAD

**Issue by leguaan** [runelite/runelite#16593]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Mahogany Homes' Barbara's door was invisible and missing, couldn't enter the building. This was right after the "Loading - Please wait" speedup update was applied, so I assumed it to be related to that. Most of the times it was fine, this only happened once the whole day.

Hopping worlds fixed the issue and the door appeared again.

As a disclaimer I've used a plugin called "Ground object hider" in the past, which I presumed to be the culprit at first glance, but even after disabling the plugin the door was still invisible. 

### Screenshots or videos

https://media.discordapp.net/attachments/1066045453650645122/1107409841758158999/image.png

### RuneLite version

Runelite version: 1.10.0.5 (might've been 1.10.0.4, not sure)
Launcher version: 2.6.4

**Comment by Nightfirecat** [comment]
Relaunch your client. If you experience this again, please get a screenshot with your Info panel active so we can see the RuneLite version for certain.
