### ISSUE TITLE
Chat Timestamps in Wrong Timezone

### ISSUE THREAD

**Issue by sangoku116** [runelite/runelite#16624]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Arch Linux

### Bug description

I switched the timezone of hardware and software clock on my system and every software displays the appropriate except runelite which still displays the previous timezone. 

### Screenshots or videos

![306f59a05875dcc9ba664746d1a7622c](https://github.com/runelite/runelite/assets/18174977/2d1f147a-0f9c-434f-ab6d-721d5f138bf8)

### RuneLite version

RuneLite version: 1.10.0.7
Oldschool revision: Rev 213
Launcher version: 2.6.4

### Logs

[client.log](https://github.com/runelite/runelite/files/11559061/client.log)
[launcher.log](https://github.com/runelite/runelite/files/11559062/launcher.log)

**Comment by Nightfirecat** [comment]
Have you relaunched the client since changing your system timezone?

**Comment by sangoku116** [comment]
> Have you relaunched the client since changing your system timezone?

Yes, I also tried resetting the time in the chat timestamps settings.

**Comment by Adam-** [comment]
The code uses `ZoneId.systemDefault()`, which even goes so far to state `If the system default time-zone is changed, then the result of this method will also change.`. So I would expect it to work even without restarting RuneLite. Maybe you aren't actually changing your system time, or there is a Java bug preventing it from recognizing it.

**Comment by sangoku116** [comment]
> 

As you can see in the screenshot, the system time has been changed. ```hwclock``` and ```timedatectl``` both display a different time then runelite.

**Comment by sangoku116** [comment]
It looks like only Java applications use a file called ```/etc/timezone``` which you need to go and manually edit because ```timedatectl``` as defined by the archwiki as the way to do this does not touch that file nor is it mentionned. I eventually stumbled across this [thread](https://unix.stackexchange.com/questions/296776/how-can-i-easily-change-my-time-zone-in-arch-xfce) which took me some time to find.
