### ISSUE TITLE
Special Attack Counter Doesn't Track BH Kit Warhammer

### ISSUE THREAD

**Issue by RyanNuttall** [runelite/runelite#16629]
### Type

Incorrect behavior

### Operating System

None

### Bug description

The new bounty hunter ornament kit means the dragon warhammer specs are no longer tracked with the special attack counter plugin. 

### RuneLite version

Runelite version: 1.10.0.7
Launcher version: 2.4.5

**Comment by Nightfirecat** [comment]
This is already fixed in master in commit 34f6b89085f609c39d3314cd2e9925e520c91952 and will be working correctly in our next release.
