### ISSUE TITLE
White Screen on Run

### ISSUE THREAD

**Issue by calbright98** [runelite/runelite#16640]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When I run Runelite from Visual Studio Code it starts with a whitescreen but the Runelite UI is still there on the sidebar. Here's a link to the [terminal output](https://justpaste.it/67sjg) when I hit run in case that information is useful.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/43652094/913c4472-a0a6-4f90-af31-3cdf74057ef8)

### RuneLite version

Runelite 1.10.2-SNAPSHOT
Launcher version unknown

**Comment by raiyni** [comment]
The issue tracker is not a development support forum. Our intended development environment is through Intellij. You can ask development related questions in our discord.
