### ISSUE TITLE
Fullscreen doesnt work on vertical screens when having a vertical + horizontal screen setup

### ISSUE THREAD

**Issue by Cryslacks** [runelite/runelite#16642]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I have a dual monitor setup where one monitor is vertical and one is horizontal, the bug comes from enabling fullscreen on the vertical monitor. What happens is Runelite is still trying to fullscreen itself by getting the window boundaries of a horizontal screen.

This issue is caused by having the setup of one vertical and one horizontal, im guessing some sort of which screen-type is runelite present on would be required for this bug to be fixed!

Note: I did test just using a vertical screen and it works as intended, hence the problem occurs when using both in one setup!

### Screenshots or videos

Image of fullscreen already enabled:
![image](https://github.com/runelite/runelite/assets/1779288/96b13ecb-61af-4645-9590-37d1c40970c3)

Video of enabling fullscreen:
https://github.com/runelite/runelite/assets/1779288/8105a0a5-56ea-46c9-ba43-45c9bae35b97

### RuneLite version

RuneLite version: 1.10.1
Launcher version: 2.1.0

### Logs

[client.log](https://github.com/runelite/runelite/files/11618894/client.log)
[launcher.log](https://github.com/runelite/runelite/files/11618895/launcher.log)

**Comment by Adam-** [comment]
There is a chance this is fixed in the latest launcher version, try that first.

**Comment by Cryslacks** [comment]
> There is a chance this is fixed in the latest launcher version, try that first.

This was indeed fixed in the latest launcher version! Thanks for the quick reply and sorry about not testing that first!
