### ISSUE TITLE
Clarify potion timers on the website features page

### ISSUE THREAD

**Issue by Lonke** [runelite/runelite#1664]
There are two references to potions on the features page on the [RuneLite website](https://runelite.net/features) one being that it shows potion (and food) effects on potion hover and the one pictured below. With the only reference to potion timers being under the Nightmare Zone headline one might assume that they are only active/work in Nightmare Zone. 

One might also gloss over the Nightmare Zone description when specifically looking for potion timers. Description pictured below for reference.

![chrome_2018-04-18_0566](https://user-images.githubusercontent.com/8409189/38949335-5e53dc34-4342-11e8-8233-ddd72e44532d.png)

**Comment by sethtroll** [comment]
This should probably be posted as in issue on the runelite.net repo, but yes we should probably add option timers feature.

**Comment by deathbeam** [comment]
This belongs in https://github.com/runelite/runelite.net . Reopen it there if necessary.
