### ISSUE TITLE
Show whether the client is running in safe mode in Discord rich presence

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#16659]
We should prepend `(safe mode)` to the Discord rich presence tooltip, the same way it's done in the title bar.

**Comment by shi-vy** [comment]
Hello, I was interested in doing this for my first contribution but I think it's a bit more involved than it initially seems.

So, for Rich Presence I believe that the init that runs [here](https://github.com/runelite/runelite/blob/49ce8dbf1e01eada005533856d450f4db14d8e84/runelite-client/src/main/java/net/runelite/client/discord/DiscordService.java#L110) loads in the "RuneLite" title in rich presence.  

Once rich presence is initialized, it can be updated, with [these values](https://discord.com/developers/docs/rich-presence/how-to#updating-presence-update-presence-payload-fields).  Note that none of these values update the title itself.  So I think rich presence can't actually be used to edit the title, and that the game title is linked to the Discord app id.  But I could be wrong, I am no expert.

P.S. DiscordRPC is deprecated in favor of the Discord GameSDK, and Rich Presence is now meant to be implemented via the [Activity Manager](https://discord.com/developers/docs/game-sdk/activities).  I'm not sure if the desired output can be achieved via the new SDK either :(

**Comment by geheur** [comment]
pretty sure the text would be added here <https://github.com/runelite/runelite/blob/49ce8dbf1e01eada005533856d450f4db14d8e84/runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java#LL170C20-L170C20>

doesn't sound that difficult.

**Comment by AustinMay1** [comment]
> pretty sure the text would be added here [`49ce8db`/runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java#LL170C20-L170C20](https://github.com/runelite/runelite/blob/49ce8dbf1e01eada005533856d450f4db14d8e84/runelite-client/src/main/java/net/runelite/client/plugins/discord/DiscordState.java#LL170C20-L170C20)
> 
> doesn't sound that difficult.

This just sets the hover text for the large image. 
![image](https://github.com/runelite/runelite/assets/86316894/484c48d2-88d7-4230-ad7d-a40e962e3c55)

@shi-vy is correct in that Discord does not support changing the actual title of the application programmatically. Everything but the title may be changed unless you create a clone of the application with "(safe mode)" in the title and pass the appId conditionally to the init service, which does not sound to appealing. Also see [this](https://github.com/discord/discord-rpc/issues/375) issue in the discord-rpc repo requesting dynamically changing the applications name.

**Comment by Nightfirecat** [comment]
Changing the hover text is what we want, not changing the name of the application
