### ISSUE TITLE
Max hit doesn't take into account invisble bonus from combat style

### ISSUE THREAD

**Issue by billionai** [runelite/runelite#16660]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Fedora 37

### Bug description

I am exactly on a point where depending on the combat style, I get 1 extra max hit.  My current setup is: 30 strength, adamant mace.

When I use the accurate, controlled or defensive style, my max hit is (correctly) reported as 5. However, because of the invisible +3 boost to strength with the aggressive style, my max hit becomes 6, and the plugin does not change. I imagine that the same bug would happen if I was 32 strength and using the controlled style, but I having gotten there yet to verify :p 

### RuneLite version

RuneLite version: 1.10.4
Launcher version: 2.6.4

**Comment by Felanbird** [comment]
![image](https://github.com/runelite/runelite/assets/41973452/9fec54c0-fb09-4e5f-bd95-84fc544b45cd)

**Comment by billionai** [comment]
I'm sorry, I forgot that I installed that pluginas a 3rd party
