### ISSUE TITLE
Cannot type in game while holding shift

### ISSUE THREAD

**Issue by Rihsky** [runelite/runelite#16669]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I cannot type in runescape itself while holding shift, it works everywhere else on my pc, including within runelite (plugin searches, hiscore search etc.)
This started happening a week or 2 ago

### RuneLite version

Runelite version 1.10.4
Launcher version 2.6.4

**Comment by Felanbird** [comment]
Install the hub plugin `debug helper` and click the `display keybinds` button, it will likely indicate what's bound to shift.

Also this isn't a support forum, join the discord for support
![image](https://github.com/runelite/runelite/assets/41973452/c38f5c32-f1de-4b0d-ad27-ace3693cc137)
