### ISSUE TITLE
vertical stat boost indicators?

### ISSUE THREAD

**Issue by firehash** [runelite/runelite#1667]
![screen shot 2018-04-18 at 3 43 04 pm](https://user-images.githubusercontent.com/38506782/38954298-4426c20e-431f-11e8-9b57-d6d49deea8cf.png)

similar to that of konduit? gives the ability to rearrange the status boost indicators to be vertical/horizontal

**Comment by sethtroll** [comment]
I have #1248 but it needs to be reviewed
