### ISSUE TITLE
Quest Helper missing

### ISSUE THREAD

**Issue by Haliwe** [runelite/runelite#16675]
### Type

Other

### Operating System

Windows

### OS Version

12

### Bug description

Restarting Runelite at 13:40 after the system update of OSRS. Quest Helper is missing and it's not in the list either.
I did not change anything in game or on the computer. Restarted game and restarted computer, Quest Helper still missing.

### Screenshots or videos

![quest helper missing](https://github.com/runelite/runelite/assets/136595085/f4fd1785-b9d2-451f-bbe4-806401623554)

### RuneLite version

Runelite 1.10.5
Rev 214
Launcher Version 2.6.4

### Logs

[client.log](https://github.com/runelite/runelite/files/11745348/client.log)
[launcher.log](https://github.com/runelite/runelite/files/11745349/launcher.log)

**Comment by abextm** [comment]
Support for hub plugins should be directed to the author of the plugin.
You can find the support link by searching for the plugin in the Plugin Hub panel and clicking the `?` button on the plugin, or by right-clicking the plugin in the plugin panel and clicking the `Support` menu option.
