### ISSUE TITLE
Client crashing when revealing gauntlet rooms

### ISSUE THREAD

**Issue by G1R-Productions** [runelite/runelite#16684]
### Type

Crash or hang

### Operating System

None

### OS Version

windows 10

### Bug description

Sometimes when a room is revealed in the gauntlet the client crashes.

### RuneLite version

Runelite Version: 1.10.5
Launcher Version: 2.6.3

### Logs

[jvm_crash_pid_19384.log](https://github.com/runelite/runelite/files/11777760/jvm_crash_pid_19384.log)
[client.log](https://github.com/runelite/runelite/files/11777761/client.log)
[launcher.log](https://github.com/runelite/runelite/files/11777762/launcher.log)

**Comment by Felanbird** [comment]
Are you able to replicate this issue in safe mode?

You can enable safe mode with the `Runelite (safe mode)` application in your start menu. If you use the Jagex launcher you can instead use `Runelite (configure)` and ✔️ Safe Mode.

**Comment by G1R-Productions** [comment]
I was able to reveal all rooms while in safemode.

**Comment by raiyni** [comment]
Please join our discord for support.
