### ISSUE TITLE
prayer filter not working

### ISSUE THREAD

**Issue by MainMan11** [runelite/runelite#16686]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 10

### Bug description

my prayer filter is not workimg. gives the option to turn of tiered prayers and all other but nothing changes when i click them. works on original client but not on rl right now.

### RuneLite version

1.10.5
2.6.3

**Comment by Felanbird** [comment]
You can either turn off the `Prayer` plugin, or use the new prayer sorting feature.

The filtering while the `Prayer` plugin is enabled will be fixed in the next Runelite version 71ebd6882d7711933b11329aa3f4eda1181a3d16
