### ISSUE TITLE
Spawn events for objects under bridges have stopped working

### ISSUE THREAD

**Issue by domenur4** [runelite/runelite#16687]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows11

### Bug description

Objects under bridges are no longer appearing in the gameObjectSpawned event. They used to appear though.
I have isolated some objects under bridges (see screenshot bellow) and checked if they were spawning in the gameObjectSpawned event.

### Screenshots or videos

Some objects under a bridge: 
![image](https://github.com/runelite/runelite/assets/110786616/7e824031-4119-4933-b545-b2862f04306a)

### RuneLite version

RuneLite version 1.10.3

**Comment by abextm** [comment]
fixed in 3181371b71bb5365d14eef537c2ffb4aaf425a0c and internally

**Comment by domenur4** [comment]
> fixed in [3181371](https://github.com/runelite/runelite/commit/3181371b71bb5365d14eef537c2ffb4aaf425a0c) and internally
woo, thankyou my man.
