### ISSUE TITLE
Bank Tag- Syntax naming problem

### ISSUE THREAD

**Issue by Ahnii-Dev** [runelite/runelite#16698]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Win10 Home, Version 10.0.19045

### Bug description

Bank Tags don't seem to be correctly distinguished.
When creating two (or even more) tags so that the name of the first tag is a prefix of the second tag, for example "slayer" and "slayer shamans", all items from "slayer shamans" are also included in the "slayer" tag.
Instead of comparing the whole tag name it seems to start at the front and check every letter on its own immediately adding items to tags if the first letters match the tag, which is obviously wrong.

### Screenshots or videos

1. no problem ".slayer shamans"
![slayer shamans correct](https://github.com/runelite/runelite/assets/137184546/817133cb-7c97-40b0-aee4-4af5388512cb)

2. correct "slayer": with "." not being a prefix of "slayer" slayer is correctly displayed.
![Slayer correct](https://github.com/runelite/runelite/assets/137184546/66fa6754-8908-4ac0-910f-c15de43a9858)

3. problem "slayer shamans":
![slayer shamans broken](https://github.com/runelite/runelite/assets/137184546/a81d4013-e8e7-4f16-abd9-375955bb035c)

4. broken "slayer": with "slayer" (from "slayer shamans") being a prefix of "slayer" the "slayer" Tag also contains all items from "slayer shamans"
![slayer broken](https://github.com/runelite/runelite/assets/137184546/b457a9db-8bde-42af-a099-f37ed09bd412)

### RuneLite version

Runelite version: 1.10.5
Oldschool version: Rev 214
Launcher version: 2.1.0

**Comment by raiyni** [comment]
This is intended.
