### ISSUE TITLE
Prayer Filtering not working

### ISSUE THREAD

**Issue by Ahnii-Dev** [runelite/runelite#16695]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Win10 Home, Version 10.0.19045

### Bug description

Prayer filtering doesn't work on runelite anymore, it just shows all prayers no matter what and the interface doesn't change at all while on the native (mobile) client prayer filtering works just fine.

### RuneLite version

Runelite version: 1.10.5
Oldschool rev: Rev 214
Launcher version: 2.1.0

**Comment by Nightfirecat** [comment]
This is already fixed in commit 71ebd6882d7711933b11329aa3f4eda1181a3d16 and will be working properly in our next release.

**Comment by Ahnii-Dev** [comment]
Sorry for reporting and creating addition work, must have somehow overlooked the older posts about it.
