### ISSUE TITLE
loot tracker / kill count

### ISSUE THREAD

**Issue by gtoilet** [runelite/runelite#16690]
### Type

Other

### Operating System

Windows

### OS Version

win 11

### Bug description

so the loot tracker only tracks dropped items
but why does it not update your kill count to show you killed 222 with 2 drops or etc

out here killing hellhounds slayer task and since using the ash sanctifier with not many drops
but shows the kc of only items that dropped why dont it see i just killed them and add to KC total

### RuneLite version

runelite : 1.8.18.1

**Comment by Nightfirecat** [comment]
It's a loot tracker, not a kill tracker. It's not capable of knowing when you've killed something which doesn't drop loot, so it can't increment kill counts when no loot is given.
