### ISSUE TITLE
Slayer helm not visible when eqipped.

### ISSUE THREAD

**Issue by Smugg1laren** [runelite/runelite#16702]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When equipping the slayer helmet(i), there is a flash but then my characters head is visible as if no helmet was equipped. Tested on official client and helm is visible, checked GPU plugin on and off, 117 HD plugin on and off aswell.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/114673154/de7a3124-89de-4081-ae7c-4b06ab98c37e)

### RuneLite version

 Runelite Version : 1.10.5
Launcher Version : 2.6.4
![Screenshot 2023-06-23 110525](https://github.com/runelite/runelite/assets/114673154/5b3b2c55-46ec-4794-b455-f3bde8708450)
![Screenshot 2023-06-23 110535](https://github.com/runelite/runelite/assets/114673154/561bf59c-6a2c-428d-b0a7-d758341684e9)

**Comment by Hypsster** [comment]
Run the client in safe-mode, that will disable all plugin-hub plugins. And see if the issue still occurs.

Afterwards, I  would probably delete the cache, and back up plugin data & settings if safe-mode does not work.

**Comment by RebelliousRS** [comment]
You have some hub transmog plugin enabled.

**Comment by Felanbird** [comment]
As noted above you had the hub plugin `Fashionscape` installed, which very likely was causing this issue.
