### ISSUE TITLE
Can't use the zoom

### ISSUE THREAD

**Issue by berks041** [runelite/runelite#1672]
I can't use the zoom at all and the website wasn't helpful. can anyone help?

**Comment by Kamielvf** [comment]
![image](https://user-images.githubusercontent.com/35824069/38961575-6d41d134-4369-11e8-99f1-2466a13f8724.png)

**Comment by berks041** [comment]
thats not there on my client

**Comment by Kamielvf** [comment]
Yes it is, ingame runescape options.

**Comment by deathbeam** [comment]
We are using vanilla zoom, and just extending the distance, enable it as @Kamielvf said.

**Comment by berks041** [comment]
how do i get to that

**Comment by deathbeam** [comment]
![screenshot 2018-04-19 00 37 23](https://user-images.githubusercontent.com/5115805/38961677-e1c072fe-4369-11e8-97b0-d46543a73a85.png)

**Comment by berks041** [comment]
still not there

**Comment by berks041** [comment]
nvm i found it
