### ISSUE TITLE
Item Stats plugin has incorrect magic attack for Bloodbark Legs

### ISSUE THREAD

**Issue by rolfson32** [runelite/runelite#16728]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Item Stats plugin is showing bloodbark legs as having +13 magic attack, when they have +16 as of June 21.

### Screenshots or videos

SS from wiki of June 21 patch changes:
![image](https://github.com/runelite/runelite/assets/12105249/189f183e-50d5-4952-89a6-0e61fb7df12d)

SS from in-game with incorrect value from Item Stats plugin on hover
![image](https://github.com/runelite/runelite/assets/12105249/70e2830b-2262-41fe-bfd4-2c091ca74217)

### RuneLite version

Runelite Version 1.10.5
Oldschool version: Rev 214
Launcher Version: 2.4.5

**Comment by Adam-** [comment]
It looks like the wiki scraper had broken, it is fixed now.
