### ISSUE TITLE
Menu Entry Swapper - Sarabrew

### ISSUE THREAD

**Issue by fisherrjd** [runelite/runelite#16734]
### Type

Incorrect behavior

### Operating System

None

### OS Version

Windows 11

### Bug description

Swapped sara brew to use on left click and cannot swap it back to drink... on shift click or normal left click

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/92651075/36dc9dab-a3a4-44a5-bb31-71b24a86e693)
![image](https://github.com/runelite/runelite/assets/92651075/d76f2bf0-c57b-41d7-8fde-061419eb5e93)

### RuneLite version

Runelite: 1.10.5
Launcher: 2.5.0

### Logs

I dont think its applicable

**Comment by fisherrjd** [comment]
Also tried to reset the plugins with no avail

**Comment by Nightfirecat** [comment]
Select the "Reset" option

**Comment by fisherrjd** [comment]
> Select the "Reset" option

I already did

**Comment by Felanbird** [comment]
Click reset on 1,2,3 and 4 dose, when you change one it changes all of them.

**Comment by fisherrjd** [comment]
> Click reset on 1,2,3 and 4 dose, when you change one it changes all of them.

Thanks!  Why doesn't it allow to swap back? I was looking through are consumables just treated as "normal" items so you cant eat/drink them?

**Comment by Nightfirecat** [comment]
Eat and Drink are the default options, so "Reset" resets it back to the default option.

**Comment by Felanbird** [comment]
> Thanks! Why doesn't it allow to swap back?

The one you actually changed takes priority and changes them all, I only worded it the way I did because I don't have the knowledge of which one you actually changed, so instructing you to do all of them is the quickest solution.
