### ISSUE TITLE
Entity Hider Shows Players on Ignore List

### ISSUE THREAD

**Issue by hankoj** [runelite/runelite#16732]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

If you have Entity Hider on Hide Others, adding a player to your ignore list will cause them to appear.

### RuneLite version

RuneLite Version: 1.10.5
Launcher version: 2.4.5

**Comment by Adam-** [comment]
This is intentional, click "Hide Ignores" if you want to hide them too.
