### ISSUE TITLE
Forestry roots incorrectly increments Logs cut

### ISSUE THREAD

**Issue by chefyes** [runelite/runelite#16740]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Using the woodcutting plugin, I noticed that the Woodcutting interface that shows Logs cut and Logs/hr was misbehaving. While cutting roots from the forestry event, the values are incorrectly incremented even though the player doesn't obtain any logs.

### RuneLite version

RuneLite version: 1.10.6
Oldschool revision: Rev 214
Launcher version: 2.6.4

**Comment by Adam-** [comment]
fixed in 83a9f3d17a7d1ca94a7e3d6a0f15caa1290a57ff
