### ISSUE TITLE
"Preserve pitch on compass look" doesn't work as of lately

### ISSUE THREAD

**Issue by Rowan-Mulder** [runelite/runelite#16751]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I was changing my compass to face north, as usual, but I noticed it didn't preserve the pitch (vertical angle) of the camera.

More people in my clan experienced the same issue, so I think a log may be unnecessary.

### RuneLite version

RuneLite version: 1.10.6.1
Oldschool revision: Rev 214
Launcher version: 2.1.0

**Comment by Adam-** [comment]
Restart your client/reopen if it happens on 1.10.7

**Comment by Rowan-Mulder** [comment]
All good after a restart! I should have tried that before submitting the issue.
