### ISSUE TITLE
Entity hider "Hide Ignores" overrides "Hide Others" behaviour

### ISSUE THREAD

**Issue by calebjallen** [runelite/runelite#16763]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10.0.19045 Build 19045

### Bug description

When using the entity hider plugin, having a player on your ignore list allows them to show up when "Hide Others" is enabled (if hide ignores isn't enabled). 

In the below screenshots, I have the player beside me on my ignore list, but I can see them when "Hide Others" is enabled. I need to check the box "Hide Ignores" to get them to disappear. If I remove them from my ignore list, they disappear. 

While I understand this is in line with the functionality of the hide friends, clan members, etc. options, I feel as if Hide Others should take priority over Hide Ignores. It feels backwards that reporting a spam bot in my public chat causes them to appear when I'm using entity hider

### Screenshots or videos

I have Hide Others enabled, but this individual appears visible because they are on my ignore list
![image](https://github.com/runelite/runelite/assets/22329530/9b530262-46cc-44fa-aaa1-7a0ca5951e3d)

I check Hide Ignores and they disappear
![image](https://github.com/runelite/runelite/assets/22329530/99d4d1c1-665c-452c-b1a3-fe0f1be58f4b)

I remove them from my ignore list and they disappear
![image](https://github.com/runelite/runelite/assets/22329530/a8e7468b-784a-4fc4-b852-922ec77c830b)

### RuneLite version

RuneLite version: 1.10.7
Launcher version: 2.6.1

**Comment by matomario8** [comment]
I think hide others makes sense if you take it to mean hide the rest (anyone not in the other categories)
