### ISSUE TITLE
While having entity hider activated and your report someone they appear

### ISSUE THREAD

**Issue by jcarter1826** [runelite/runelite#16760]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

Reported an account selling inferno services while entity hider was activated then he just appeared.  Also, another player who teleported to the area appeared.  Tried turning entity hider off and on but they were still there.

### RuneLite version

latest... idk

**Comment by Nightfirecat** [comment]
Turn on "Hide Ignores"

**Comment by jcarter1826** [comment]
Well I feel foolish.  Thanks
