### ISSUE TITLE
Noella's Southeast most mirror always modifies the counter

### ISSUE THREAD

**Issue by old-moon-osrs** [runelite/runelite#16772]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

doing mahogany homes, in Ardougne, in the north location, from npc Noella.

when going up the east staircase then repairing the southeast mirror with a full inventory of mahogany planks, the southeast mirror will always deplete 1 from the plank sack.

### RuneLite version

runelite version: 1.10.7

oldschool revision: rev 214

launcher version: 2.6.3

**Comment by Nightfirecat** [comment]
Support for hub plugins should be directed to the author of the plugin.
You can find the support link by searching for the plugin in the Plugin Hub panel and clicking the `?` button on the plugin, or by right-clicking the plugin in the plugin panel and clicking the `Support` menu option.
