### ISSUE TITLE
Menu Entry Swapper : 1 Dose Stamina

### ISSUE THREAD

**Issue by ImTimushi** [runelite/runelite#16780]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

W11

### Bug description

The default behavior when banking for the Stamina Potion (1) item is to drink the potion while the bank remains open rather than depositing the item. Shift-click is default to deposit the item, which is not shared with the other dose amounts. Attempting to force Menu Entry Swapper to default to 'Deposit-1' is not possible as the option is not present in the menu, even after resetting. 

### Screenshots or videos

[Imgur Link](https://imgur.com/a/eJettrw)

### RuneLite version

RuneLite version 1.10.7
Launcher version 2.4.2

**Comment by geheur** [comment]
uninstall "runecrafting utilities" plugin, then close this issue if that fixes the issue.
