### ISSUE TITLE
Inventory Setups: When renaming a setup, the bank layout isn't retained

### ISSUE THREAD

**Issue by Telope** [runelite/runelite#16789]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

* In inventory setups
* Create an inventory setup
* Select inventory setup
* Open bank
* Drag items in bank to rearrange
* Rename the inventory setup
* Open bank

Expected: The layout of the items in the inventory setup should persist even though the name of the inventory steup has changed.
Actual: They bank layout is messed up.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/47144445/9f45ef85-081f-4c59-a8f1-634c01342f63)

### RuneLite version

Runelite: 1.10.7
Launcher 2.4.5

**Comment by geheur** [comment]
https://github.com/geheur/bank-tag-custom-layouts/issues/21 that issue already exists on the correct repo, please close this issue.
