### ISSUE TITLE
Woodcutting plugin does not notify or have overlay during Forestry Bee Event

### ISSUE THREAD

**Issue by calvinagar** [runelite/runelite#16790]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

Ventura 13.3.1

### Bug description

Since the rework to the Forestry Bee Event that gave the flowers colors, I have not received a notification from RuneLite that one has started and I have never seen an overlay during the event.

I tried re-enabling the plugin as that seems to fix some other issues with the woodcutting plugin overlays during Forestry events, but that didn't help this time.

### RuneLite version

RuneLite: 1.10.17
Launcher: 2.6.3

**Comment by Nightfirecat** [comment]
As you noted, this broke with the game update, and is already fixed on master in commit 36979d67f7a0ba420ec3ed3189ac27ff3c1a1abb. It'll be working again with our next release, which is likely to be mid next week.

**Comment by calvinagar** [comment]
Appreciate the quick response and thank you for everything you do!
