### ISSUE TITLE
Music plugin issue "control the in-game volume with more granularity." no longer works.

### ISSUE THREAD

**Issue by gojlus** [runelite/runelite#16803]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

W10

### Bug description

Had my ear drums blasted on login, went to adjust the volume back to 1-3%, found out the slider was back to the default deafening options.

### Screenshots or videos

https://i.imgur.com/q6jG4sN.png

### RuneLite version

Runelite Version: 1.10.8
Launcher Version: 2.5.0

### Logs

N/A

**Comment by gojlus** [comment]
Update: Reseting the plugin config corrected the issue. No other changes were made. 
https://i.imgur.com/alYkEQn.png

**Comment by Seyona** [comment]
Same spec and issue as @gojlus - Their fix worked for me for a bit, but then it randomly stopped working after a few log outs.

**Comment by muhammadtalhas** [comment]
Seems to break again once you teleport

**Comment by Nick2bad4u** [comment]
yup. when changing areas/zones it breaks

**Comment by Nightfirecat** [comment]
We've fixed this feature. If you are seeing issues with it, please restart your client and make sure your client version is at least version `1.10.8.3`
