### ISSUE TITLE
Issue With Login Screen PLugin

### ISSUE THREAD

**Issue by devwithdon** [runelite/runelite#16832]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

WIndows 10

### Bug description

Login Screen always shows as black background after using Login Screen plugin, regardless of how I try to change settings. Off or on, it does the same thing. Toggling the setting only temporarily fixes. Closing and opening Runelite reverts back to black background.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/33989414/1040cf0e-1e7f-483a-b193-96e8d1115680)
![image](https://github.com/runelite/runelite/assets/33989414/2b0421c4-6b4a-409e-91be-276ab243a9b3)

### RuneLite version

RuneLite version: 1.10.8.3
Launcher version: 2.6.4

### Logs

[client.log](https://github.com/runelite/runelite/files/12139760/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12139761/launcher.log)

**Comment by Felanbird** [comment]
Does this issue continue if you open Runelite with the `Runelite (safe mode)` shortcut found in your Windows start menu?

**Comment by devwithdon** [comment]
It does not!

**Comment by Nightfirecat** [comment]
Chances are this is caused by some hub plugin you've installed then.

**Comment by devwithdon** [comment]
After some investigating, I have found this is due to the "RL Immersive" Resource Pack. Thank you!
