### ISSUE TITLE
Resetting left-click or shift-click back to withdraw-1 not possible

### ISSUE THREAD

**Issue by lukavom** [runelite/runelite#16848]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I changed an items left click option to withdraw-x. Now I want to change it back, but when shift-right-clicking it and trying to assign withdraw-1 to left-click or shift-click it does not show up as an option. Swapping to other options works as intended. This is the case with all items which I have changed. I am not sure since when this is happening.

### RuneLite version

Runelite Version 1.10.9
Launcher Version 2.6.3

**Comment by Nightfirecat** [comment]
Click the "Reset" option

**Comment by MosheBenZacharia** [comment]
I think you just need to choose "Reset" and it will go back to the default.
