### ISSUE TITLE
improve NPC Aggression Timer loss of calibration message

### ISSUE THREAD

**Issue by Elite-Mercenary-Raven** [runelite/runelite#16843]
### Type

Incorrect behavior

### Operating System

Win10

### Bug description

This plugin is unusable as long as it keeps bringing up this huge text box every time it loses calibration. It takes up a ton of screen real estate and provides no useful information for me. It's extremely irritating. I *need* to have the plugin on 24/7 so it will auto-calibrate, but every time it loses calibration it asks me to go through a whole song and dance to fix it. Obviously, I'm not interested in going out of my way to teleport and run around as soon as I log in just to calibrate a plugin I'm not immediately using, just to make a text box disappear. Turning off the plugin is an inconvenience too though, because every time I need the plugin on, it's not calibrated, and I have to do all this extra stuff I shouldn't have to, just to set it up (when, as I said, I should be able to keep it on so it'll do the work of setting itself up for me). 

By design, this plugin should be kept on 24/7, and it should never be visually obstructive. The only time it should say that it needs calibration is when I'm trying to use it: EG, if "always active" is checked (which shouldn't be on by default), or if I'm near an NPC that I put in my list. Only at those points should a little infobox be able to appear with mouseover text showing brief calibration instructions. The huge always-on text box serves very little purpose for the user and I think is a clear net negative in terms of user experience. Imagine if every plugin put huge text boxes with calibration instructions all over the screen. 

That's the first half of the issue. 

I also need help trying to figure out why every so often this plugin loses calibration, assuming this is abnormal behavior. I'm not playing the game on other computers or logging on to other accounts, though I've got a few alts I used a while back that might have their own calibrations the plugin sees. Is there a settings file I need to delete or modify or something? Is there something on the cloud that's getting de-synced? What can I do to solve this issue? Thanks!

### RuneLite version

Runelite ver 1.10.9
Launcher ver 2.6.3

**Comment by fuzxi** [comment]
This is intended behavior, see #10420. I do agree that it is annoying if you're already aware of how it works, given how much space it takes up. An infobox would be a better and less obstructive solution, IMO.

**Comment by Nightfirecat** [comment]
The overlay is intended behavior, but having it appear after every launch is not.

**Comment by fuzxi** [comment]
Yeah, I should have clarified but that's what I was referring to.

**Comment by khogeland** [comment]
Yeah, there's no need for the info box to be so intrusive. A little warning icon that shows the existing text when hovered over would be way nicer.

**Comment by Elite-Mercenary-Raven** [comment]
Yup. 

Unsurprising update: I've stopped using the NPC aggression timer plugin altogether since the issue was never fixed.

**Comment by Adam-** [comment]
See my previous comment on this https://github.com/runelite/runelite/pull/17109#issuecomment-1875960335

**Comment by Elite-Mercenary-Raven** [comment]
A tool tip would be a much better solution, and wouldn't prompt people to turn the plugin off. 

Related, another thing RL needs that would help this kind of situation is a better way to present instructions in plugins' settings panel. A few plugins, such as Better NPC Highlight, use a workaround, including a text entry field with instructions there by default. If it was possible to add an image and/or simple text in a more presentable way I think that would also lower the amount of support requests you guys get.

**Comment by Alexsuperfly** [comment]
the overlay to display the plugin needs calibration was changed to be an infobox with tooltip in f1faf04145a36b99728f3932bc2d172f4e43ec24
