### ISSUE TITLE
Quest icons on world map no longer show quest progress.

### ISSUE THREAD

**Issue by geheur** [runelite/runelite#16859]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Quest icons on the world map do not show quest progress on the icon (e.g. green check mark).

I also noticed that abex's cache dumb does not contain enum 4385 (`EnumID.MAPELEMENT_TO_QUEST`) and that enum seems to return 0 every time it's used in `WorldMapPlugin`.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/41499327/a71dc700-f9f0-4737-b8cc-888696baf5eb)

### RuneLite version

RuneLite 1.10.9
Launcher 2.6.3

**Comment by Adam-** [comment]
fixed in 38ff79766c9509e2b68d3ea50149e88387ded275
