### ISSUE TITLE
Ground marker not rendering selected color unless "Remember color per tile" enabled

### ISSUE THREAD

**Issue by Joshua-F** [runelite/runelite#16851]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Attempting to color a marked tile via "Color Tile" menu option does not work when "Remember color per tile" is disabled (which is the default).

Mark a tile with "Remember color per tile" disabled and attempt the change the color of an existing marked tile. Either the "Color Tile" menu entry should not be shown, the color properly renders, or maybe some other solution.

### Screenshots or videos

![RuneLite_Hkjh1ImCNm](https://github.com/runelite/runelite/assets/924482/5bb22331-ebed-4304-bbd1-e44dc7d0d9ad)

### RuneLite version

RuneLite version: 1.10.9

**Comment by Adam-** [comment]
This is actually intended behavior. Although it makes not much sense. The "Remember color per tile" option is old and comes from back when the plugin used to always have the tiles all be one color. I think everyone uses this feature now, and with the ability to easily change colors now, it is probably no longer necessary. So I wouldn't mind seeing the option removed.

**Comment by Adam-** [comment]
removed in e07b3d310be8b6810bc55e4345051c97e31de2f3
