### ISSUE TITLE
Nature implings are labelled incorrectly as Mature implings on minimap overlay

### ISSUE THREAD

**Issue by HeavensVibe** [runelite/runelite#16854]
### Type

Other

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When using Implings plugin, the player selects "Nature impling" as Highlight option, the impling is labelled incorrectly as Mature impling on the minimap.

### RuneLite version

1.10.9
Rev 215
2.1.3

**Comment by Adam-** [comment]
The code does not contain any reference to "Mature impling". Most likely you are misreading "Nature" as "Mature".
