### ISSUE TITLE
Fairy Ring B L S and Map Icon

### ISSUE THREAD

**Issue by MulletRock** [runelite/runelite#16853]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The Fairy Ring Code B L S says "invalid location" when typed in and it is also not displayed on the map, it just says "teleportation". 

### Screenshots or videos

![Screenshot 2023-07-29 135411](https://github.com/runelite/runelite/assets/140893266/acb1aa0e-8902-4a6f-a6b2-236a32a08fca)
![Screenshot 2023-07-29 135458](https://github.com/runelite/runelite/assets/140893266/b2d631ad-6fb4-4dc6-8741-ae5250e8b5de)

### RuneLite version

Runelite Version 1.10.9

**Comment by xDemoN** [comment]
Pull Request has already been submitted #16849

**Comment by Nightfirecat** [comment]
As mentioned, this is added in #16849 and will be updated in our next release.
