### ISSUE TITLE
Loot Tracker - Loot Tracker no longer logging Thermy Boss Loot

### ISSUE THREAD

**Issue by Nick2bad4u** [runelite/runelite#16862]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Win 11

### Bug description

Killing thermy over the last few days, no loot is logged or tracked.

The other loot logger plugin does track loot however.

### RuneLite version

Runelite Version: 1.10.9
Oldschool Version: Rev 215
Launcher Version: 2.6.4

**Comment by Felanbird** [comment]
Cannot replicate, Thermy loot is still logged exactly as expected. Your _other_ loot logger is probably causing your issue.

dev note: I tested both 1.10.9 and 1.10.10 just just for completion sake, but it worked exactly as expected on both.
(incase Jagex had changed Thermy loot to work like the new bosses for some ungodly reason)

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Or on Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by Nick2bad4u** [comment]
> Does this behavior happen while running in safe mode?
> 
> To open in safe mode on Windows: In Command Prompt, run:
> 
> ```
> "%localappdata%\runelite\runelite.exe" --safe-mode
> ```
> 
> Or on Mac: In Terminal, run:
> 
> ```
> /Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
> ```

I got a new thermy task so I will test now.

Im going to try disabling the "Loot Logger" plugin to see if it works. If it doesn't, ill try safe mode.

**Comment by Nick2bad4u** [comment]
This can be closed I figured out the issue.

Somehow I got the thermy added to my ignored loot sources.

can this happen on click somehow?
