### ISSUE TITLE
Right click menu doesn't work on the same pixel after moving overlay

### ISSUE THREAD

**Issue by raiyni** [runelite/runelite#16864]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

1. Move an overlay
2. Do not move mouse
3. Release alt
4. Try and open right click menu 

### RuneLite version

Runelite version: 1.10.9

**Comment by Adam-** [comment]
fixed in fd3e4d67dbdf767f6e599512c6d6a29c9d9da303
