### ISSUE TITLE
Stopwatch overlay

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1686]
Idea is simply a stopwatch or countdown timer or simple variations of that that is an overlay (like how kingdom/potions/boosts are currently)

Would be a plugin you can turn off/on on in settings with a thing where you can set what you put the timer too. (eg: 1hr/15mins etc etc)

Can have it briefly flash in w/e color (i assume we can add this in as every other color thing you can change color) for set intervals.

When timer is done/finished it would flash a different color and potential notifications.

--------
Reason for adding this imo is to time how many of w/e u want per hour or per w/e time. or lots of things really. Only thing it really wouldnt help with is xp/hr (since thats kind of naturally included in the tracker)

**Comment by Nightfirecat** [comment]
Not an overlay, but a stopwatch/timer was added with the Time Tracking plugin. Does that fix this issue?

**Comment by holydeltawings** [comment]
Yes this is great for what I want it for. Would only be better if there was a notification sound for timer. Even like the idle notification sound.

**Comment by Nightfirecat** [comment]
There is a sound if you have notifications set to play a notification sound...

**Comment by holydeltawings** [comment]
Hmmm wonder why mine is not sounding off. Maybe only sounds when a game related timer ends?

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/RuneLite#enable-sound-on-notifications

**Comment by holydeltawings** [comment]
Weird thought I had notifications all set up. Guess not. Thanks!
