### ISSUE TITLE
Bug: Bank Plugin "Block Jagex Account popup" breaks "Clear-all" Bank filler

### ISSUE THREAD

**Issue by R-Y-M-R** [runelite/runelite#16873]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

In the "Bank" plugin, with the "Block Jagex Account popup" setting enabled, you cannot "Clear-all" on bank filters.

1. Enable bank plugin with "Block Jagex Account popup" setting enabled.
2. Add "All" placeholders to your bank.
3. Attempt to right click "Clear-all" on the Bank fillter.
4. The bug will cause the clear-all confirmation to close instantly.
5. Verify this setting is the issue by repeating Steps 1-4 without the "Block Jagex Account popup" setting. It will work normally.

### RuneLite version

RuneLite version: 1.10.9.1
Launcher version: 2.6.7

**Comment by Adam-** [comment]
fixed in a86a9ea4c90ea58bb6a9156fb06a8a4fc1212d45
