### ISSUE TITLE
Items on the ground are logged as loot when dying to the whisperer

### ISSUE THREAD

**Issue by smol-tako** [runelite/runelite#16880]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When dying to the whisperer the loot tracker will consider item on the ground at your respawn point as loot and add them as drop for a kill that didn't happened.

### RuneLite version

Runelite version: 1.10.9.1
Launcher version: 2.6.3

**Comment by Adam-** [comment]
this was fixed in 4f43819f59121465e221576f49ec9fa62759ff8a and 2c61107c9ccbe9a9fcd7dc258c61013c2c4b17e4
