### ISSUE TITLE
Regression with right click on blue objects

### ISSUE THREAD

**Issue by MBradbury** [runelite/runelite#16888]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

There seems to be a regression due to https://github.com/runelite/runelite/commit/9aabc88058fc61e53ae757a143682ce2309e9b09. When right clicking blue objects (e.g., bank chest) the menu is no longer shown by default. This means that it is not possible to `collect` from the chest only `use` it.

Enabling `Right click objects` in the camera settings fixes this.

### Screenshots or videos

Without right click objects, cannot interact with the menu:
![image](https://github.com/runelite/runelite/assets/2089920/f06463ec-87fd-4d56-b72a-e1d07a46263b)

With right click objects you can:
![image](https://github.com/runelite/runelite/assets/2089920/71fb2de9-4bc1-4551-9835-de514006156e)
![image](https://github.com/runelite/runelite/assets/2089920/0fd7ef3e-8a41-4b61-b71f-8d3f9025ff3d)

### RuneLite version

Runelite: 1.10.9.2
Oldschool: Rev 215
Launcher 2.1.0

**Comment by claudiodekker** [comment]
Can confirm. Saw the same on MacOS and got really confused. After resetting the plugin's default settings, the problem was fixed for me.

**Comment by Adam-** [comment]
The default behavior of the plugin was changed, with `Right click objects` being added to use the previous behavior. So this is working as intended.

**Comment by MBradbury** [comment]
Would it be possible to have right click objects enabled by default? By being disabled by default it means there are a few places with issues. For example, the inability to use the teleport option on GWD altars.

**Comment by Adam-** [comment]
By *default* right click moves camera is off, and so this isn't a problem normally. You must have had right click moves camera on, and with the new changes it becomes right click moves camera on + right click objects off. The thought was people prefer to remap mmb to right click using "Middle-button opens menu". But maybe that is not true. I honestly was not aware so many people used this right clicking camera behavior.

**Comment by MBradbury** [comment]
Ah that explains it, I do use left click to rotate camera. I wouldn't say there is a lot of us, this might just be a case of [xkcd 1172](https://xkcd.com/1172/). I'm happy for the issue to be closed as there is a way to re-enable the old behaviour.

**Comment by wickz80** [comment]
This behavior change was unexpected and I had to search here to find out how to enable the legacy behavior. Please consider rolling back this change.

**Comment by Adam-** [comment]
Okay. I've changed the default behavior back to right clicks move camera=off right click objects=on bc4bb30dde0025860a4eb75a9ce505b16f64548c and then also included players/npcs/items in "right click objects".
