### ISSUE TITLE
Raids Olm orb overlay

### ISSUE THREAD

**Issue by kulershk** [runelite/runelite#1688]
So basically when you are at olm you get his special attack orbs, where you have to protect from mage, range or mele and sometimes its hard to distinguish is coming for you or someone standing under you. 

There could be raids option to enable overlay for Olm orb attack.

**Comment by EatMyWeani** [comment]
Your chat box will tell you which orb is coming at you and the text will be a color based on which style is hitting you, so you don't even have to be able to read it. That seems just as useful as an overlay, so I don't really see the need for the overlay.

**Comment by abextm** [comment]
Jagex's [recent statement](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1) prohibits `Prayer switching indicators `
