### ISSUE TITLE
Loot tracker tracking unrelated loot

### ISSUE THREAD

**Issue by PolnerA** [runelite/runelite#16891]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When Pickpocketing Ardougne knights the loot tracker was tracking unrelated loot, such as jugs that were on the ground nearby. The Bug occurs when an item is dropped at the same tick you pickpocket causing the loot tracker to add the items dropped.

### Screenshots or videos

https://github.com/runelite/runelite/assets/113457255/3815ea2a-4c9b-4012-9e7b-a7bafad3d02c

### RuneLite version

Runelite Version: 1.10.9.3
Launcher version: 2.6.1

### Logs

[client.log](https://github.com/runelite/runelite/files/12271585/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12271600/launcher.log)

**Comment by Nightfirecat** [comment]
There isn't really a way around this as pickpocketing loot can appear on the ground for other NPCs.
