### ISSUE TITLE
runelite sidebar is blurry - lots of dots lines and purple green color

### ISSUE THREAD

**Issue by Wimrs** [runelite/runelite#16895]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 10

### Bug description

when i deploy the runelite sidebar it's all blurry - green pruple color and a lot of dots and lines cover the text. Any idea what causes this problem and what i can do to fix it pls? I deleted runelite and reinstalled it but nothing changed

### RuneLite version

1.10.9.3 runelite version
2.6.7 launcher version

**Comment by Nightfirecat** [comment]
Can you provide a screenshot of what you're seeing?

**Comment by Wimrs** [comment]
https://snipboard.io/iqTeoQ.jpg

**Comment by Nightfirecat** [comment]
Do you have AMD image sharpening enabled? If so, disable it

**Comment by Wimrs** [comment]
ok thanks, that was the problem.
