### ISSUE TITLE
GPU Plugin High GPU Usage

### ISSUE THREAD

**Issue by JSchroeder11** [runelite/runelite#16896]
### Type

Performance

### Operating System

Windows

### OS Version

WIN 11

### Bug description

GPU Plugin is using as much as 80% utilization on a 4070 ti when unlock FPS is turned on with either adaptive or "on" Vsync is selected. Never noticed this behavior previously and have been using the GPU plugin for 2+ years. (~6 months with the 4070ti). 

### Screenshots or videos

![Screenshot 2023-08-08 165611](https://github.com/runelite/runelite/assets/120575781/925e55da-f2ec-4e6c-8dad-4e4eecdfb5e8)

### RuneLite version

Runelite 1.10.9.3
Launcher 2.6.1

**Comment by Nightfirecat** [comment]
We haven't changed anything about the GPU plugin recently, so this is likely due to some change on your machine.

**Comment by JSchroeder11** [comment]
Thanks. Good to know. Maybe it was something in a recent GPU driver...

**Comment by Nightfirecat** [comment]
I'd recommend using the FPS Control plugin to limit your FPS if you don't want it to run at maximum FPS at all times.
