### ISSUE TITLE
Ground Item is invisible even when alt key is held

### ISSUE THREAD

**Issue by Rose8Light** [runelite/runelite#16903]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 10

### Bug description

Some items are completely invisible to me even though I have them on my "highlighted" menu under the ground items plugin.  Usually you hit alt key and you can either plus or minus the item to hide or highlight. Unfortunately my Mithril bolts are just invisible to the alt key. There is no plus or minus option for them, also noticed it does the same thing for seaweed spores. Making my bolts invisible is making it unplayable to range as I am going mad trying to find individual bolts on the ground without the highlight, or simply title, name, "mithril bolt" on the ground. Please help me. I literally have it in my highlight column list on ground items plugin. In the picture you can see that I am holding down Alt key and only bones are visible, mithril bolts, completely hidden and invisible. 

### Screenshots or videos

![thumbnail](https://github.com/runelite/runelite/assets/141893286/607d9fbe-aefc-4657-92bb-dd021a4b0abc)

### RuneLite version

RL version: 1.10.9.4
Launcher version: 2.4.2

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Or on Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by Rose8Light** [comment]
Hello, I just tried running under safe mode and it did not fix the problem. All bolts are still just invisible to me unless my mouse hovers over them. feels unplayable. what do you suggest?

**Comment by Rose8Light** [comment]
Hello I hope I can get help to find a way to fix the invisible bolts for me. I am unsure why it says closed ticket, please help
