### ISSUE TITLE
Cactus Farming Patch in Farming Guild does not show as protected

### ISSUE THREAD

**Issue by Hitpointler** [runelite/runelite#16909]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Cactus patch in Farming Guild does not show that the cactus seed is protected, when in actual fact it is. This has been this way since I can remember but been too lazy to report. No other bug that I have identified with RL in 30m farming exp. 

### Screenshots or videos

https://gyazo.com/b590ee61b19693fb521ece719061c0c3

https://gyazo.com/f24d794a5223b4cae8b5765ee8675816

### RuneLite version

RuneLite version: 1.10.9.4
Launcher version 2.6.7

### Logs

Fuck knows what any of this means, I just want a picture of a little basket next to one of my cactus patches tbh with you

**Comment by Birger9** [comment]
This is a similar bug as https://github.com/runelite/runelite/issues/17137 so I will take a look at both of these issues

**Comment by Adam-** [comment]
added in 1a6ede8902d8220941eae2fda21d326db853a061
