### ISSUE TITLE
RuneLite GPU Crashing Runelite on Mac

### ISSUE THREAD

**Issue by Joee94** [runelite/runelite#16912]
### Type

GPU

### Operating System

MacOS

### OS Version

Ventura 13.5

### Bug description

GPU Plugin crashes RuneLite. When turned off it runs fine. Crashes on default settings

### RuneLite version

RuneLite Version 2.6.3

### Logs

[client.log](https://github.com/runelite/runelite/files/12327625/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12327626/launcher.log)

**Comment by Joee94** [comment]
Seemed to be fine the next day

**Comment by smallbyname** [comment]
Updated to Ventura earlier and I am getting crashes now. Literally loads graphics all flickering and then crashes.
