### ISSUE TITLE
The Whisperer Loot tracker and Bossing info

### ISSUE THREAD

**Issue by bendzoo** [runelite/runelite#16911]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Before Jagex fixed the Whisperers loot mechanic for the perfect kill and now that the loot gets announced in the chatbox aswell, the 2 plugins stoped working; Loot tracker and Bossing info only tracks kp/hr withouth gp/hr cause theres no loot

### RuneLite version

1.10.9.4
2.4.2
Rev 215

**Comment by Adam-** [comment]
we think this is fixed in 785083d96976c05b96cfc78d923b341a5e3abe92 and will be in the next release.
