### ISSUE TITLE
Unable to right click "choose option" on game screen

### ISSUE THREAD

**Issue by chris-olszewski** [runelite/runelite#16931]
### Type

Other

### Operating System

Windows

### OS Version

Windows 10 Build 19045.3324

### Bug description

Unable to right click in game area to bring up the [choose option menu](https://oldschool.runescape.wiki/w/Choose_Option) unless there is a player under the cursor. Both items and NPCs seemingly won't register/display the right click unless there's a player under the cursor as well and then the choose option will come up.
Right click works on all other parts of the game interface (inventory, quick prayers, etc)

Temporary work around is using single button mode.

### Screenshots or videos
Attempting to right click exchange booth with cursor just off of the players
![2023-08-16_09-37-13](https://github.com/runelite/runelite/assets/4131117/8a01aab5-8d66-420b-b760-44fcacf14f98)
Right click with cursor slightly to the left so there's a player under it
![2023-08-16_09-37-19](https://github.com/runelite/runelite/assets/4131117/9ada2efb-d54d-4b06-ad7d-3c36441fae5c)
Right clicking in inventory
![2023-08-16_09-38-11](https://github.com/runelite/runelite/assets/4131117/9a45a70e-65dd-4785-a09d-1bc54a6ca640)

### RuneLite version

Runelite: 1.10.10.1
Launcher: 2.4.2
Oldschool: Rev 216

### Logs

[client.log](https://github.com/runelite/runelite/files/12361569/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12361571/launcher.log)

**Comment by YvesW** [comment]
Give this a try:
In the Camera plugin enable Right click objects, or disable Right click moves camera

**Comment by chris-olszewski** [comment]
That did the trick! Thanks for the quick response.
