### ISSUE TITLE
Can't right-click on objects or NPCs. Started in my POH now its the entire game.

### ISSUE THREAD

**Issue by thenicolassmith** [runelite/runelite#16940]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

Ventura 13.5.1

### Bug description

I can't right click on objects or NPCs. However, I can right click on players with no problem. I've ran runelite on safe mode and think it's definitely bugged. please let me know if you can help. Thanks!!

### RuneLite version

1.10.10.1
2.6.8

**Comment by Adam-** [comment]
turn off "right click moves camera" or turn on "right click objects" in the camera plugin

**Comment by thenicolassmith** [comment]
That solved my problem, thank you XD
