### ISSUE TITLE
Loot tracker doesn't track PNM loot

### ISSUE THREAD

**Issue by YvesW** [runelite/runelite#16943]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Reported by discord user lck.alex
Tested in safe mode and recorded on video
I suspect Jagex might have messed with the (P)NM drops like they did with the DT2 bosses, but not sure and I personally haven't tested it ingame

### Screenshots or videos

https://github.com/runelite/runelite/assets/7929021/8b7dddd7-e004-454e-a8b0-d66287a727ad

### RuneLite version

RL 1.10.10.2
Launcher 2.6.8

### Logs

[client.log](https://github.com/runelite/runelite/files/12383776/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12383777/launcher.log)

**Comment by Slayerlouver** [comment]
got the same exact problem. Randomly show some loot. Even though Bigbones also should go in collection log every time, it just doesn't mostly.
