### ISSUE TITLE
Show total xp in that skill in skill tracker

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1694]
Simple. Just a nice thing to have imo

**Comment by LeviSchuck** [comment]
It is already a crowded place, would you like this to be in the tool tip? (it is like that in game)

**Comment by Stickaplex** [comment]
Essentially just want some place where it shows current total xp for that skill w/o hover

**Comment by deathbeam** [comment]
What about just looking into "Stats" screen in runescape. Total exp has no place there and no client adds it afaik.

**Comment by Stickaplex** [comment]
Thats a hover though..essentially this came up when doin mole. Afk enough so i wouldnt have to pay attention and got curious about these kinds of things but had to pay enough attention to lazy flick prayer and such.

Kind of why i was thinking in skill tracker as its not 'in the way' aka on the main screen but also dont have to stop what your doin with mouse to look at it

Although to add to this now that ive had time to sit on it this could be incorporated into a skill goals type of thing. Fairly sure ive seen peeps talking about this kind of thing before just havent personally looked into it to see if its a request yet. 

So say for example you have a goal for range. 

90 over range symbol[Percent progress bar]99 over range symbol
Start xp: 2,375,875 (90 range symbol)
Current xp: 5,764,965 (94 range symbol)
End xp: 13,034,431 (99 range symbol) 

Dont kno xps off top of my head and on phone atm but that should make sense. Dont kno how cluttered that would look in reality though but i can see it working


Also this basically just popped into my head as an alternative to in skill tracker so theres that. 

Lmk watcha think

**Comment by deathbeam** [comment]
So like separate panel just to show start/current/end exp in list? I don't think that will be very useful. And for goals, they will be integrated into current xp tracker and use the in-game goal settings, so there is no need to have separate interface for goals.

**Comment by deathbeam** [comment]
We already implemented goals for target total xp, so this should be non-issue anymore, and for rest we have skill calc and in-game interfaces
