### ISSUE TITLE
Alt-Click to search ge item also does the left click option (equip, use, etc)

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1695]
kind of annoying when trying to pc something and i end up equiping it or something of the sort

**Comment by Kamielvf** [comment]
This seems interesting. By default runescape consumes the click when alt is held. Are you using fixed or resized? possibly stretch fixed?

**Comment by Stickaplex** [comment]
Using resizable

**Comment by deathbeam** [comment]
Cannot reproduce, reopen if this is still issue
