### ISSUE TITLE
World switcher does no longer respond in both game and start screen.

### ISSUE THREAD

**Issue by YahIAmLorde** [runelite/runelite#16965]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Since yesterday I cannot switch worlds anymore. Help

### Screenshots or videos

Difficult to screenshot as there just happens nothing

### RuneLite version

1.10.10.3
Rev 216
2.6.8

**Comment by Kevsosmooth** [comment]
It works for me 

I would delete both runelite and the plugin and download it all over again making sure to download the x64 bit edition versus the x32 bit edition

**Comment by Nightfirecat** [comment]
The issue tracker is not a support forum. Please join the [Discord](https://runelite.net/discord) for questions or support.
