### ISSUE TITLE
Able to color chat text of daily reminders

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1698]
Would be nice to be able to color the dailies log in messages aka herb boxes/zaff/p ess (maybe a different color for each?)

Just isn't very noticeable with other login text

**Comment by deathbeam** [comment]
Well, it is same color as any other in-game daily notification right? e.g TOG

**Comment by Stickaplex** [comment]
Mine just appears white. Same as any examine text basically....maybe im bugged then?

**Comment by deathbeam** [comment]
Ohh, that is not actually us sending it, that is just it being stuck in the chat history and replicated every hop/login. But the initial one is sent as red.

**Comment by MagicfTail** [comment]
For me, it's red when it sent, but turns white once i retrieve the "attempting to join cc" and such messages

**Comment by Infinitay** [comment]
Would you happen to be relogging? Because when you do so with the chat history plugin enabled, the text color turns black IIRC

**Comment by MagicfTail** [comment]
This is first time logging into a new client [Gif](https://i.imgur.com/4lOaahK.gifv)

**Comment by Infinitay** [comment]
Huh weird, ill hop on resizable and see if it happens to me

**Comment by deathbeam** [comment]
This should be already doable with Chat Color plugin I believe.
