### ISSUE TITLE
Animation smoothening not working aside from character running 

### ISSUE THREAD

**Issue by Forthewinwin** [runelite/runelite#17009]
### Type

GPU

### Operating System

Windows

### Bug description

Animation smoothing causes lag like behavior with flames and other moving items aside from the character running, such as Tombs of amascut raid Ahka special attacks where each quadrant lights up, or Zebak room with the spikes coming out of the sides before the waterfalls. Even turning windmills look like they lag or studder slightly  as turning. 

### RuneLite version

Latest version

**Comment by Nightfirecat** [comment]
We've fixed this in an internal change. Ensure you're on RuneLite version 1.10.12.1 or later (restart your client if you aren't) and it should be back to normal now.

**Comment by Forthewinwin** [comment]
Hi, it works now. Thank you Win Chan | AccountantC: 780-804-2735 From: JordanSent: September 10, 2023 9:10 PMTo: runelite/runeliteCc: Forthewinwin; AuthorSubject: Re: [runelite/runelite] Animation smoothening not working aside from character running (Issue #17009) We've fixed this in an internal change. Ensure you're on RuneLite version 1.10.12.1 or later (restart your client if you aren't) and it should be back to normal now.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
