### ISSUE TITLE
The Miscellania favor reminder should update at midnight GMT like the rest of the dailies

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#17004]
[Per Jagex's 2023-09-06 game update](https://secure.runescape.com/m=news/dmm-tweaks-upcoming-launcher-changes--more?oldschool=1):

> Those of you who are currently regents in the Kingdom of Miscellania will be glad to know that your subjects now attend to your various whims at exactly midnight each day, instead of whatever time you initially completed the quest.

This means we can more reliably update the active coffer funds and favor amount at midnight GMT instead of assuming it happens 1 day after it was last changed.

**Comment by sufferfish** [comment]
I'd be willing to take a stab at this.

**Comment by sufferfish** [comment]
> I'd be willing to take a stab at this.

I feel stupid. I'm unsure how to test my changes since I haven't completed the necessary quest...

**Comment by acrinklaw** [comment]
Hey @sufferfish, how did you implement it? You could always mock things out to test out the logic, especially since it seems like it would need minimal changes. I can also checkout your branch and test it for you in game if you'd like, I just didn't see it in your fork

**Comment by sufferfish** [comment]
Hey @acrinklaw I've pushed my changes to my fork. Feel free to check them out. Upon further review I don't think it's completed but I was hoping to check that the changes I currently made didn't bork the game. @Birger9 feel free to work on this though! I wouldn't want to keep it from being done in a timely manner.

**Comment by Birger9** [comment]
@sufferfish I have completed the task and I have tested it. My code should work. I will open a PR for this issue. 
Sorry if you feel like have stolen this issue from you, I'm sorry if you feel like that. I have pressure from my University to finish a number of issues from an open source project within a certain time frame.
