### ISSUE TITLE
RuneLite won't fully load, glitching out.

### ISSUE THREAD

**Issue by clebauer** [runelite/runelite#17001]
### Type

Crash or hang

### Operating System

MacOS

### OS Version

MacOS Ventura 13.5.2

### Bug description

I have been playing for over 5 hours today with no issue on my Macbook.

A few hours ago, I tried to open RuneLite and the screenshots below occurred. Between opening the application and the login screen loading, I can open and close the sidebar as well as navigation the settings menus within the sidebar plugins.

Eventually, the login screen does show up (with perfect flames rendering), lets me log in and it goes to the intro screen where you can click Play. Once I click Play, the game freezes again on the "play" screen, and after about 60 seconds, gameplay opens and freezes fully. During this time, I cannot engage with the sidebar/plugins without a SIGNIFICANT delay of at least 45 seconds.

---
When I first had this issue, I was still on MacOS Monterey. Since, I have restarted my computer twice, updated to Ventura and am still having this issue. I also deleted RuneLite from my computer and reinstalled a brand new copy (Intel).

Lastly, my internet speed is 600mbps, the default Old School Runescape client launches/plays fine on the same laptop, and my phone OSRS account also plays fine on the same WiFi network.

---
The photos show the lag when resizing the app during its time-of-being-frozen.

### Screenshots or videos

https://github.com/runelite/runelite/assets/31354379/4d5fdebd-d3cc-4f05-a9d3-79cb2f85b6c8

![image](https://github.com/runelite/runelite/assets/31354379/3f636a55-4b61-4765-a7af-d4c84b76ba6e)
![image](https://github.com/runelite/runelite/assets/31354379/c04b4c73-9c26-4194-be80-03060419f575)

### RuneLite version

RuneLite version: 1.10.11.3
Oldschool version: Rev 216
Launcher version: 2.6.8

### Logs

[launcher.log](https://github.com/runelite/runelite/files/12554782/launcher.log)
[client.log](https://github.com/runelite/runelite/files/12554783/client.log)

**Comment by Adam-** [comment]
This is a bug in the recent 117hd update. It sounds like they are getting close to a resolution. For now disable hd or use the normal gpu plugin.

**Comment by aHooder** [comment]
This should be fixed by https://github.com/runelite/plugin-hub/pull/4868
