### ISSUE TITLE
Idle notification when breaking infernal eels

### ISSUE THREAD

**Issue by sjrowley8** [runelite/runelite#1701]
hi - currently the client doesn't notify you once you have finished breaking all of your infernal eels.  I'm wondering if this is similar for zeah RC.   It would be really helpful to have this fixed.

Thanks!

**Comment by Reasel** [comment]
This could be as simple as logging the animation for breaking infernal eels and adding to the the idle notification plugin. I do not have the fishing level to do it myself.

**Comment by Adam-** [comment]
Fixed in #1792
