### ISSUE TITLE
117 HD Plug-in turning off when I teleport

### ISSUE THREAD

**Issue by Blodhevn** [runelite/runelite#17013]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When I teleport or when I hop worlds, the 117 HD plug-in turns itself off automatically. It's consistent and happens nearly every time. It just started doing this today as of 09/10/23.

Also, I'm suddenly having chunk loading issues.

### Screenshots or videos

https://github.com/runelite/runelite/assets/144629206/5958d7c2-d635-445d-8b61-639a2e6fe276

### RuneLite version

RuneLite Version: 1.10.12.1
Launcher Version: 2.4.2

### Logs

[client.log](https://github.com/runelite/runelite/files/12570633/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12570634/launcher.log)

**Comment by Nightfirecat** [comment]
Support for hub plugins should be directed to the author of the plugin.
You can find the support link by searching for the plugin in the Plugin Hub panel and clicking the `?` button on the plugin, or by right-clicking the plugin in the plugin panel and clicking the `Support` menu option.
