### ISSUE TITLE
Daily Tasks plugin bowstring infobox bug

### ISSUE THREAD

**Issue by Alexgopen** [runelite/runelite#17012]
### Type

Incorrect behavior

### Operating System

None

### OS Version

Windows 10

### Bug description

I do my bowstring, dynamite, ogre arrow, and battlestaff dailies every day, and use the Daily Tasks plugin to display infoboxes for them, which normally disappear when completed.  
A couple days ago Runelite was updated and added a new infobox for Dynamite, which didn't previously exist, however this update also broke the existing bowstrings infobox.  
When I collect my bowstrings, the bowstring infobox no longer disappears.  This has now happened two days in a row.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/16151797/2719c3d6-7463-4e80-a660-2a81f3be801a)
![image](https://github.com/runelite/runelite/assets/16151797/96f483a8-1b93-4e03-b6c5-9931ae4bd576)
These screenshots show my game state after having converted my daily bowstrings and collected my dynamite.  My other dailies are not complete at this point.  The issue here is that the bowstring infobox is still present even though I have already converted my daily bowstrings.

### RuneLite version

1.10.12

**Comment by Adam-** [comment]
The daily tasks plugin doesn't have infoboxes. Maybe these are provided by another, third party plugin.

**Comment by Alexgopen** [comment]
> The daily tasks plugin doesn't have infoboxes. Maybe these are provided by another, third party plugin.

Ah I see, yea you are right, it's a 3rd party plugin which now has this bug.  I'll have to bring it to the author's attention then
![image](https://github.com/runelite/runelite/assets/16151797/95c4672e-0c22-4978-aab2-7e5f46f2a3ab)


This is the stated functionality of that plugin
![image](https://github.com/runelite/runelite/assets/16151797/ab94576f-c8cb-41f4-bbb3-e511c6c36df0)

Disabling the bow string option in this plugin removes the persistent infobox.

**Comment by Alexgopen** [comment]
Actually it appears the issue has already been raised. I'll close this. Thanks!
https://github.com/TicTac7x/runelite-plugins/issues/83
