### ISSUE TITLE
GPU Draw Distance Won't Go Past 25 (Windows ARM64)

### ISSUE THREAD

**Issue by MasonBergstrom** [runelite/runelite#17017]
### Type

GPU

### Operating System

Windows

### OS Version

Windows 11 (ARM64)

### Bug description

On a Surface Pro X (SQ2 processor), running the ARM64 version of RuneLite, increasing the draw distance past 25 doesn't go anything. 

### Screenshots or videos

Draw Distance set to 25:
![image](https://github.com/runelite/runelite/assets/13530957/54772ef4-e5f6-43bb-a862-85856f2938f3)

Draw Distance set to 184:
![image](https://github.com/runelite/runelite/assets/13530957/8160d25e-85af-41c4-b425-cdcedff91230)

### RuneLite version

RuneLite version: 1.10.12.1
Launcher version: 2.6.8

### Logs

[client.log](https://github.com/runelite/runelite/files/12582888/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12582889/launcher.log)

**Comment by geheur** [comment]
`2023-09-11 22:09:09 PDT [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - disabling compute shaders because OpenGL 4.3 is not available` in `client.log` your computer does not support opengl 4.3 and therefore cannot use compute shaders and therefore cannot use higher render distance.

**Comment by MasonBergstrom** [comment]
It looks like the integrated Adreno 690 GPU doesn't support OpenGL 4.3 which may be to blame.

**Comment by BigTato02** [comment]
Tengo una computadora con OpenGL 4.0 y puedo modificar la distancia de dibujado (bajarla), pero tengo otra pc en la que ni si quiera puedo activar el plugin GPU, que puedo hacer para activarlo? Recuerdo que existía un plugin llamado "GPU (experimental)" que creo que podía ser activado en cualquier pc, pero hoy en día busco ese plugin y no lo encuentro, que pasa? Lo quiero para bajar la distancia de dibujado del juego, solamente bajarla, ¿existe alguna manera de hacerlo sin el plugin? Tal vez con un argumento JVM o de cliente

PD: estoy usando google traductor

**Comment by BigTato02** [comment]
I have a computer with OpenGL 4.0 and I can modify the drawing distance (lower it), but I have another PC where I can't even activate the GPU plugin, what can I do to activate it? I remember that there was a plugin called "GPU (experimental)" that I think could be activated on any PC, but today I look for that plugin and I can't find it, what's wrong? I want it to lower the drawing distance of the game, just lower it, is there a way to do it without the plugin? Maybe with a JVM or client argument

PS: I am using google translator

**Comment by Alexsuperfly** [comment]
9dfb067de628a5b4500cf3fc8402a0958a5f73e9 removed the draw distance limit without compute shaders
