### ISSUE TITLE
"Panic at Al Kharid Mine" Beginner Clue Step tells you to go much further into the mine than necessary

### ISSUE THREAD

**Issue by DataCrusade** [runelite/runelite#17022]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Not really a bug exactly, but the solver for this beginner clue step tells you to go much further into the mine than you need to to complete the step. As you can see in the attached image taken from the wiki, you can emote at the entrance of the mine to complete the step, so I don't believe there's a reason for it to have you go all the way to the end of the mine to perform it

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/36621129/40b6512c-7c64-4886-8f74-fe0145af94ba)

### RuneLite version

Latest version (although probably not relevant to the issue)

**Comment by geheur** [comment]
it would be cool if runelite remembered the spot you last dug at or used the emote at, then you could have custom locations for every clue automatically.

**Comment by Nightfirecat** [comment]
We updated this ~2 months ago so it doesn't say to go so far in. (see https://github.com/runelite/runelite/pull/16420) Where is the plugin telling you to emote now?

**Comment by Nightfirecat** [comment]
As mentioned in my previous comment, this is not a real issue in RuneLite today. The wiki may have a different location marked than what we display ingame. Please make sure you can reproduce bugs in the client before raising a bug report.
![Screenshot_20230914_090343](https://github.com/runelite/runelite/assets/2199511/9186f16e-8cde-421f-b3e5-c30b85fd953c)
