### ISSUE TITLE
Extended GPU distance has gaps in roofs

### ISSUE THREAD

**Issue by Mm2PL** [runelite/runelite#17023]
### Type

GPU

### Operating System

Linux

### OS Version

Kernel version: `6.1.50`. GPU is `NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2` using proprietary drivers version `535.104.05`.

### Bug description

If you look far away something causes roofs to have gaps in them or stuff behind them is rendering over them if you look from certain angles.
Reproducing:
  1. Set max render distance and extended map loading (184 and 5 respectively)
  2. Go to somewhere where you have cached tiles, like Varrock. 
  3. Use detached camera plugin/debug tool or Oculus orb.
  4. Fly somewhat far away
  5. Notice that it does not look right and roofs are missing a piece if looked at from certain angles.

I tested this on a fresh profile.

### Screenshots or videos

When taking this screenshot my character was standing just a couple tiles south of GE roof.
 
![2023-09-14_01-24](https://github.com/runelite/runelite/assets/25011746/d793824c-534c-4446-bf37-b6bb2814f46a)

### RuneLite version

RL version: 1.10.12.1
Game version: 216
Launcher: N/A using custom shadow jar for my niche GE plugin and debug tools.

**Comment by Adam-** [comment]
Looks OK to me 
![image](https://github.com/runelite/runelite/assets/309739/7da97cea-e722-40c7-9cce-9f0f21a33859)

**Comment by pajlada** [comment]
I'm able to reproduce this on:
 - Arch Linux desktop with an NVIDIA RTX 4070, driver version 535.104.05
 - Arch Linux laptop with an integrated AMD GPU, driver version 23.2.0
 - Mac Mini M2, running macOS Ventura 13.5

this video shows the reproduction of it with only changing the extended map loading once

[leaky-roof-macos-05.webm](https://github.com/runelite/runelite/assets/962989/ef5e96f5-5f32-44fa-9f69-74625a8f45ee)

`0:00` - `0:20` shows using detached camera without the GPU plugin  
`0:27` - `0:38` shows using detached camera with the GPU plugin at its default settings  
`0:39` - `1:06` show extending the map loading to 4, showing that only the newly loaded chunk experiences the roof glitch  
`1:06` - `1:16` show that the roof glitch sticks around after disabling the GPU plugin

**Comment by Adam-** [comment]
fixed in build 6185643510.257
