### ISSUE TITLE
POH Spirit Tree location option not displayed on GUI.

### ISSUE THREAD

**Issue by Trenz0** [runelite/runelite#17030]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Following the new quest, the Path of Glouphrie, which adds a new Spirit Tree, when accessing the Spirit Tree interface, the POH location option is now longer displayed. Using the hotkeys for the interface, however, 'd' can be pressed to teleport to POH despite the option not being displayed.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/145190005/77cfb1d8-f0e8-42c0-a720-4a41448aeb35)

### RuneLite version

1.10.12.1
2.6.7

**Comment by harbingerofme** [comment]
Either uninstall [https://runelite.net/plugin-hub/show/spirit-tree-menu](https://runelite.net/plugin-hub/show/spirit-tree-menu) or wait for it to be updated. I believe a PR is already out.
You can access your house by pressing `d` either way.

**Comment by Trenz0** [comment]
I didn't see anyone else bring this issue up so I thought I'd get a thread going to bring attention to the issue.

**Comment by Nightfirecat** [comment]
Please raise this bug to the author of that hub plugin; we don't have anything to do with it.
