### ISSUE TITLE
Object Markers: can't specify a default fill color

### ISSUE THREAD

**Issue by call-me-maple** [runelite/runelite#17058]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

Currently, you can't specify what the default fill color should be. You can only specify the default border color with the 'Marker color' config option. 

I believe this is caused by changes in https://github.com/runelite/runelite/commit/1952ed67f4b11aa832273538ce91a1de437f32c4 and looks like https://github.com/runelite/runelite/pull/14979 has a code change that would address it.

Also, I'm not sure how to go about changing the fill color option on all my existing object marks without configuring it for each one. Which maybe that's okay for a new feature, I'm just curious if there could be a nicer way.

### Screenshots or videos

![RuneLite_bbLkyH654T](https://github.com/runelite/runelite/assets/85463994/54af413d-5098-4d3a-ab1b-82dd4fe19dca)

### RuneLite version

Runelite version: 1.10.13
Launcher: 2.6.4

**Comment by Adam-** [comment]
I left this out intentionally since it is usually the same color with a/12. And now with convex hull I changed it to a=50. Which is the previous behavior. So I don't think this is really necessary?

**Comment by Adam-** [comment]
I think this was fixed by 639de097da53050a1203ad41a50424c205087513?

**Comment by Adam-** [comment]
A fill color config that defaulted to unset would be okay I think. Anything else would cause additional confusion because the fill color is dependent upon the highlight style.

**Comment by call-me-maple** [comment]
Yeah, I think that works. You could also make it a color picker without the alpha channel option if you are managing it anyway right?

Are the existing fill color options stored in the config file or are they just derived based on the border color and only stored if you go through the right-click menu?

**Comment by Adam-** [comment]
They are derived from the border color unless you set a different color

**Comment by call-me-maple** [comment]
What do you think of a boolean to enable the filling all altogether too?

**Comment by Adam-** [comment]
Your marks probably don't have any fill, they are just using the default fill of a/12

**Comment by call-me-maple** [comment]
yeah, that's whats happening I think.

**Comment by Adam-** [comment]
ok, I added a default fill color 859b541dbc7fae08c9a8cdd2add2eb5b5881f0f5
