### ISSUE TITLE
Karambwanji Fishing Issue

### ISSUE THREAD

**Issue by Tyler-ML** [runelite/runelite#17087]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When fishing karambwanji with a full inventory of shrimp the plugin stops displaying the fishing.
I'd imagine this is because your inventory doesn't really change while you fish them?

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/13242461/2698d9b7-934f-4c7d-ac05-0d35b3245934)
This is an image of the panel when you do not have a full inventory yet.

### RuneLite version

runelite: 1.10.14
launcher: 2.6.1
osrs: Rev 217

**Comment by skillingdev** [comment]
I've confirmed adding a check for the `You catch \\d+ Karambwaji.` message fixes this issue, and the fishing overlay then appears.

The only issue is that the "Caught fish" count is not correct - it's counting the actions performed, not the actual amount of fish. Does that matter in this case?

**Comment by Tyler-ML** [comment]
I'd

**Comment by skillingdev** [comment]
@Tyler-ML I think you might've accidentally closed this issue while making your last comment. Is it possible to re-open it?

**Comment by Tyler-ML** [comment]
Sorry, it was a mistake you're correct

**Comment by Nightfirecat** [comment]
> I've confirmed adding a check for the `You catch \\d+ Karambwaji.` message fixes this issue, and the fishing overlay then appears.
> 
> The only issue is that the "Caught fish" count is not correct - it's counting the actions performed, not the actual amount of fish. Does that matter in this case?

Technically this already was an issue with rada's blessing, and is similarly true of mining with the mining cape and varrock armor. We're counting actions, not actual # of fish, so it doesn't matter to us.

**Comment by Adam-** [comment]
fixed in 064c907fa7a070df98775721506a1059bac9da5a
