### ISSUE TITLE
Minimap styles stop working after client restart

### ISSUE THREAD

**Issue by dpedu** [runelite/runelite#17086]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

11.7.1

### Bug description

Runelite appears to have some sort of functionality where it restarts itself. I'm guessing it does this when the game has been updated instead of forcing the user to restart the client.

When this happens, the dot color customization option of the Minimap stops working and the dots are shown in their default colors. 

Toggling the plugin off then on again restores it.

### RuneLite version

RL: 1.10.13.2
Launcher: 2.4.2

### Logs

[client.log](https://github.com/runelite/runelite/files/12806358/client.log)
[client_2023-09-30.0.log](https://github.com/runelite/runelite/files/12806359/client_2023-09-30.0.log)
[launcher.log](https://github.com/runelite/runelite/files/12806360/launcher.log)

**Comment by Adam-** [comment]
fixed in 2f3f01054378bf2bddd20578317651b857ff7c68
