### ISSUE TITLE
Plugins not initialized at first startup

### ISSUE THREAD

**Issue by jayveedee** [runelite/runelite#17080]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

So when I restart my PC, first time I open runelite via the Jagex launcher most all plugins aren't working as they should. This started happening around last week or the week before that but before that it was working fine.

To fix the issue, I just have to restart runelite again and the plugins are loaded. 

### RuneLite version

1.10.13.2
2.5.0

### Logs

[client.log](https://github.com/runelite/runelite/files/12776812/client.log)
[launcher.log](https://github.com/runelite/runelite/files/12776813/launcher.log)

**Comment by geheur** [comment]
is it possible that you opened runelite right after an osrs update, so runelite wasn't updated to the new osrs version? almost all plugins not working sounds exactly like this.

**Comment by jayveedee** [comment]
> is it possible that you opened runelite right after an osrs update, so runelite wasn't updated to the new osrs version? almost all plugins not working sounds exactly like this.

Yeah it is similar to that, but it has been happening often so I'm not sure if it's runelite not being updated every time I restart my PC (which is pretty frequent, like every day or every 2nd day)

**Comment by jayveedee** [comment]
just restarted again now and it happened again. Fixed it by closing runelite and starting it up again. Weird.

**Comment by jayveedee** [comment]
It's either fixed now or maybe it was just some plugins that were acting up.
