### ISSUE TITLE
runecrafting pouch menu

### ISSUE THREAD

**Issue by e-102** [runelite/runelite#1709]
a setting that automatically reorders the menu so that full pouches will have a left click option set to empty.

**Comment by ypperlig** [comment]
I am not sure this will be added because it will increase xp/h. You can use the "Menu Entry Swapper" to set shift-click option to empty instead.

**Comment by e-102** [comment]
thanks, I didn't realize that's how the shift+click menu entry swapper operated.

**Comment by Kamielvf** [comment]
I am pretty sure the default shift-click action is already "empty". I have #1556 ready which would allow you to move this entry up (but that would just make "fill" move down so probably not what you're looking for in this case)
