### ISSUE TITLE
Matching PB on agility course causes notification to occur multiple times

### ISSUE THREAD

**Issue by Giovds** [runelite/runelite#17093]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Running the agility course in Priff multiple times

### Screenshots or videos

First occurrence:
![image](https://github.com/runelite/runelite/assets/27761321/a2ef8aaf-55ba-4d63-b2c6-2d4eef9e5cb4)

Second occurrence:
![image](https://github.com/runelite/runelite/assets/27761321/352f9444-7664-4a45-a886-c7186322d083)

### RuneLite version

RuneLite version: 1.10.4
Launcher version: 2.6.7

**Comment by Nightfirecat** [comment]
None of those messages are RuneLite messages; you've gotten two personal bests--one a tick faster than the other, but still 1:05.XX duration--and the game has announced it to your clan chat.

**Comment by Giovds** [comment]
That's what I thought, but assumed it was a RuneLite thing, thanks for the quick reply <3
