### ISSUE TITLE
Clue Helper - Falo Master Clue doesn't show Bow of Faerdhinen (c) as valid

### ISSUE THREAD

**Issue by c-kirkeby** [runelite/runelite#17107]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The Falo The Bard clue for showing him "A bow of elven craft was made, it shimmers bright, but will soon fade." shows only a crystal bow as a valid answer, but I gave him a `Bow of Faerdhinen (c)` which was also accepted. [According to the wiki](https://oldschool.runescape.wiki/w/Falo_the_Bard#cite_ref-2), both the corrupted and non-corrupted versions of Bow of Faerdhinen are accepted for this clue step.

### RuneLite version

RuneLite version: 1.10.14
Oldschool revision: Rev 217
Launcher version: 2.6.7

**Comment by Felanbird** [comment]
Would be fixed by #16887
