### ISSUE TITLE
Add menu entry swapper for valuable drops

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1711]
Imagine killing a blue dragon, and it drops a mithril spear, a blue dragonhide and dragon bones. If you spam left-click on the item stack, you first get the mithril spear, then the dragon bones and then the blue dragonhide. I'd prefer to get the dragon bones and blue dragonhide first.

Maybe make it such that highlighted items go on top of the list, and ignored items on the bottom.

**Comment by deathbeam** [comment]
We decided to not reorder ground item menus to be able to spam left-click.

**Comment by harry-graham** [comment]
Hi, do we have any more context around the decision for this? I would've found this a really useful feature, as I'm having to just pick everything up and then manually drop the things I don't want, which is quite painful (right clicking is not easy on my device).
