### ISSUE TITLE
Bolts are Invisible to me Even on Safe Mode

### ISSUE THREAD

**Issue by Rose8Light** [runelite/runelite#17129]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Bolts are invisible unless I hover my mouse over them. It feels unplayable as I am an ironman and need to collect all my bolts for sake of saving them. What can I do to help be able to read with the drop text that bolts are on the floor. I have started RL in safe mode and it still does not fix the problem.

### Screenshots or videos

![thumbnail](https://github.com/runelite/runelite/assets/141893286/4584bfd8-e722-454e-b5ad-eae2ce880602)

### RuneLite version

RL Version: 1.10.14.2
Launcher version: 2.6.7

**Comment by YvesW** [comment]
You closed the issue yourself. Feel free to join the discord server for support. Please stop opening github issues; it is not a helpdesk.

**Comment by Rose8Light** [comment]
thanks so much life saver
