### ISSUE TITLE
The GPU extension will not work on my pc, plz help...

### ISSUE THREAD

**Issue by auserishere** [runelite/runelite#17123]
### Type

Other

### Operating System

None

### OS Version

Windows 8 Home edition

### Bug description

Whenever I try to enable it, it turn off.

### RuneLite version

Runelite Version: 1.10.14.2

### Logs

[client.log](https://github.com/runelite/runelite/files/13048883/client.log)
[launcher.log](https://github.com/runelite/runelite/files/13048884/launcher.log)

**Comment by Adam-** [comment]
This is failing to compile the xbr shaders. Your gpu driver is probably just too old and broken, it is from from 2012.

**Comment by auserishere** [comment]
True, because the person who owned this PC said that someone else spilt beer on it.
(PS: Subscribe to me at YouTube @ https://youtube.com/@Sebby-Webby12345)
