### ISSUE TITLE
show runecrafting session stats

### ISSUE THREAD

**Issue by e-102** [runelite/runelite#1712]
Please consider making a counter similar to the woodcutting counter, this will keep track of total runes crafted and your average runes crafted per hour.

**Comment by deathbeam** [comment]
If all you need is tital runes crafted and average runes/hour you have that information in sidebar. If we are really going to start adding this for every single skill, we should just generalize it instead.

**Comment by e-102** [comment]
If you're referring to the skills sidebar that shows your experience, that keeps track of your average xp/hr and how many actions left/total exp gained, not a clear number of individual runes or quantity/hour.

**Comment by Lorentary** [comment]
The Runecrafting: ZMI Altar session statitics is not mean to be a "per hour" tracker like the exp tracker, or the woodcutting tracker.
It is meant as a way to track which TYPES of runes you craft at the ZMI. 
I don't think these two suggestions should have been merged.

**Comment by deathbeam** [comment]
That is basically the same thing

**Comment by raiyni** [comment]
duplicate #1442
