### ISSUE TITLE
Time Tracking Plugin doesn't track seaweed protection

### ISSUE THREAD

**Issue by TheHappyPittie** [runelite/runelite#17137]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

11

### Bug description

Time tracking plugin tracks most things but doesn't track if you've paid for protection for seaweed.  I've attached pics of the calquat tree that has it working correctly and my seaweed patches (which i've double checked are protected) are not showing that they're protected. 

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/114444106/ade9e8e3-66d8-4950-8e1a-6168b9d8f6d7)
![image](https://github.com/runelite/runelite/assets/114444106/52211766-c145-4399-8127-5e3380e79d21)

### RuneLite version

1.10.14.3
2.6.7

**Comment by Birger9** [comment]
I can take a look at this issue :)

**Comment by Adam-** [comment]
added in 1a6ede8902d8220941eae2fda21d326db853a061
