### ISSUE TITLE
Outer map areas are clipping and other locations are rendered in within 117 HD Plugin

### ISSUE THREAD

**Issue by PopePK** [runelite/runelite#17134]
![4851115](https://github.com/runelite/runelite/assets/141050054/dd392abb-ff46-4a12-9eb3-9598257f795b)
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Issue within the OSRS Runelite 117 HD Plugin
>Other areas or locations in most cases are appearing in the distance when they should not.
>Some parts of the map are clipping or not being rendered, creating an unfinished puzzle look.
>Turning off 117 HD Plugin resolves the issue, which leads me to believe the issue resides in the 117 HD plugin itself.
>Attachments with examples of both issues are included.

### Screenshots or videos

![9849844](https://github.com/runelite/runelite/assets/141050054/3eea8ed0-446a-44c6-9dfa-1cb6ff179c48)
![94984897](https://github.com/runelite/runelite/assets/141050054/85417dfe-b34a-411a-956c-1155ee584191)
![6854984144](https://github.com/runelite/runelite/assets/141050054/23ecb193-5a9d-4b78-89de-57a85f060de0)

### RuneLite version

RuneLite version: 1.10.14.2
Oldschool revision: Rev 217
Launcher version: 2.6.8

**Comment by Felanbird** [comment]
![image](https://github.com/runelite/runelite/assets/41973452/a93837d2-fa0f-4af7-9b43-4a5ac5baea59)

report your issue here: https://github.com/RS117/RLHD
