### ISSUE TITLE
Felling axe isn't identified as "Woodcutting" in activity box and doesn't trigger idle notification when stopped

### ISSUE THREAD

**Issue by cjung92** [runelite/runelite#17140]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

14.1

### Bug description

Whenever chopping a tree (Redwood, Dragon felling axe), the activity box that normally says "Woodcutting" or "NOT Woodcutting" doesn't regard chopping with the felling axe as "Woodcutting," and so it doesn't recognize that the player has gone idle whenever it is stopped. 

### RuneLite version

1.10.14.3

**Comment by Nightfirecat** [comment]
This is already fixed in ff88db263565fa62b25a0a1df0c95fd3e7778a0f and 8a215f4ac8a69d46d08eb38f1ae777c50cbb0918, which will be released in the near future.
