### ISSUE TITLE
No Screenshots for achieving lvl 99 with level-up dialogs disabled

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#17152]
### Discussed in https://github.com/runelite/runelite/discussions/17151

<div type='discussions-op-text'>

<sup>Originally posted by **iLight-24** October 30, 2023</sup>
Hi,
I achieved 2 99's last week but when I tried to see the screenshots in my folder it was missing.
All other lvls screenshot was there and the 99 missing.
</div>

**Comment by skillingdev** [comment]
I could take this if no one else is working on it.

**Comment by Adam-** [comment]
fixed in #17156
