### ISSUE TITLE
Allow customization of default overlay font

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#1716]
Since last update (1.3.5) the "small font" toggle was only applied to dynamic overlays. There should be another option for the regular overlays to allow changing these fonts too.

Requested several times on discord.

**Comment by deathbeam** [comment]
I don't think this should be possible even if requested. From what I saw in discord anyway the problem was that the smaller font makes the overlays smaller, so this will be solved by resizable overlays.
