### ISSUE TITLE
AnimationID for Forester Campfire

### ISSUE THREAD

**Issue by mikeweyandt** [runelite/runelite#17161]
### Type

Other

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I'm getting 10573 as the animation ID when tending to the campfire versus the 10572 defined here https://github.com/runelite/runelite/blob/master/runelite-api/src/main/java/net/runelite/api/AnimationID.java#L63.

Not sure if it's just a missing animation or a typo.

### RuneLite version

RuneLite Version: 1.10.14.5
Launcher Version: 2.6.7

**Comment by Adam-** [comment]
fixed in 5b12f573dc7b4827da1dcb3535d7f877036f52d7
