### ISSUE TITLE
Discord plugin always shows my game as runelite

### ISSUE THREAD

**Issue by cloftus96** [runelite/runelite#17170]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The "Discord" plugin used to NOT report my status as on runelite if I was logged out of the game, which should be the correct behavior as far as I know. This is no longer the case, and now it always says I am on runelite regardless of being logged in or not and regardless of duration. This is incredibly annoying because I leave my client open all the time, and it also supersedes all other game statuses. If I have any other games running it will always detect runelite over the other apps/games unless I disable detection of runelite in discord itself. If I have missed something obvious please let me know but I don't see any other settings I can change.

### Screenshots or videos

![runelite discord](https://github.com/runelite/runelite/assets/46966886/1b3a68f3-9a36-466f-8168-204064ac41dd)

### RuneLite version

RuneLite 1.10.15.1
Launcher version 2.6.8

**Comment by Nightfirecat** [comment]
That is not rich status, it's Discord showing RuneLite as a "game" you're playing. Remove RuneLite as a game in your discord settings.

**Comment by cloftus96** [comment]
> That is not rich presence, it's Discord showing RuneLite as a "game" you're playing. Remove RuneLite as a game in your discord settings.

Thanks for quick response. Much appreciated, wouldn't have noticed that without your help.
