### ISSUE TITLE
Bank `clue` search does not include items when multiple of said item are required

### ISSUE THREAD

**Issue by Felanbird** [runelite/runelite#17186]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

1. Type `::clue Create a barrows teleport tablet.` into chat
2. Open the bank
3. Click and search `clue`
4. Notice that `Law rune` & `Soul rune` do not come up
5. Build the client, change the values for law&soul rune found here to `1`, open the client, follow step 1-3, see all 3 rune types appear https://github.com/runelite/runelite/blob/e5de4d49f534ecfab1976bfe42b170a9f7fb439f/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java#L202 

### Screenshots or videos

<details>
  <summary>stable</summary>

![image](https://github.com/runelite/runelite/assets/41973452/4b0a81ab-c648-4822-9f0c-7ca80df965b3)

</details>

<details>
  <summary>changing the xOfItem values</summary>

![image](https://github.com/runelite/runelite/assets/41973452/bd3a0cde-8401-4db6-abb2-e23994e54609)

</details>

### RuneLite version

tested on `1.10.16.2` & e5de4d4

**Comment by cwjoshuak** [comment]
This seems to affect all clue items with `MultipleOfItemRequirement`. Can also replicate with `::clue kill a reanimated demon.`
https://github.com/runelite/runelite/blob/e5de4d49f534ecfab1976bfe42b170a9f7fb439f/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/SkillChallengeClue.java#L237

Stable:
![image](https://github.com/runelite/runelite/assets/15935660/3d69cc46-83ae-4690-a37f-784c9876385d)

Showing I have said items
![image](https://github.com/runelite/runelite/assets/15935660/c2dd6bb0-cba2-4da2-83cd-71ba05423e63)
