### ISSUE TITLE
Unable to remove Jagex Launcher credentials from RuneLite

### ISSUE THREAD

**Issue by JulianLee93** [runelite/runelite#17181]
### Type

Other

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I followed the [instructions](https://github.com/runelite/runelite/wiki/Using-Jagex-Accounts) to login using my Jagex account while working on RuneLite development projects. Now every time I launch RuneLite, my account credentials are automatically included, so my account is already logged in and I am unable to access any of my non-Jagex accounts via RuneLite. For example, if I'm logged into my account on RuneLite and I open a second instance of RuneLite, the only option I am given is a "Play" button for the same account, which is already logged in.

How can I remove the authentication credentials to run RuneLite as it had been before the configurations?

### RuneLite version

1.10.16.2

**Comment by Felanbird** [comment]
If you followed a guide that says it generates a file in a certain folder, did you try deleting that file?

**Comment by Felanbird** [comment]
I went ahead and updated the wiki article to prevent any future confusion, but deleting the generated file resolves your problem.
