### ISSUE TITLE
Stretched Mode doesn't expand properly when resizing in both dimensions

### ISSUE THREAD

**Issue by khogeland** [runelite/runelite#17207]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

When using integer scaling in stretched mode, the UI responds improperly to the window being resized in two dimensions.

 Example: Start with stretched mode on, set scale to 100%, enable integer scaling. Resize the window to the smallest possible size. If you expand the window horizontally, the game will expand to fill the available space, with the UI scale remaining at 1x. However, if you then expand the window vertically, the game for some reason shrinks until the window is large enough to display the UI in 2x scale, rather than filling the available space.

### RuneLite version

1.10.17 + launcher 2.5.0

**Comment by Nightfirecat** [comment]
Please add some screenshots showing this
