### ISSUE TITLE
Add notification for being poisoned

### ISSUE THREAD

**Issue by MESLewis** [runelite/runelite#1721]
Add a notification for the text "You have been poisoned!"

**Comment by ShaunDreclin** [comment]
In addition to this, an infobox showing that you're poisoned and how much damage the poison will do on its next hit would be useful.

**Comment by ShaunDreclin** [comment]
That one says to add it to the hitpoints orb instead of an infobox. Having both would be good though

**Comment by Nightfirecat** [comment]
I guess this is fixed by using the chat notifier plugin?

**Comment by deathbeam** [comment]
I would rather just add it to hitpoints orb, i see no reason why it should be in infobox when hp orb is perfect place for that and fits with e.g prayer plugin

**Comment by deathbeam** [comment]
If this is just about notification, chat notifier can already do this
