### ISSUE TITLE
Runelite crashes on Mac OS

### ISSUE THREAD

**Issue by faceprint11** [runelite/runelite#17211]
### Type

Crash or hang

### Operating System

None

### OS Version

Ventura 13.6.1

### Bug description

Seems to crash at random

### RuneLite version

1.10.17; 2.6.8

### Logs

https://github.com/runelite/runelite/discussions/17189

**Comment by Nightfirecat** [comment]
This is a gpu driver crash. You can avoid it on your system by disabling compute shaders in the GPU plugin, but we aren't aware of any way to fix it.

**Comment by faceprint11** [comment]
My GPU plug-in was disabled entirely when I went to check this. Could it have been anything else?Sent from my iPhoneOn Nov 20, 2023, at 1:54 AM, Jordan ***@***.***> wrote:﻿
This is a gpu driver crash. You can avoid it on your system by disabling compute shaders in the GPU plugin, but we aren't aware of any way to fix it.
