### ISSUE TITLE
Agility Arena - Leagues OSRS

### ISSUE THREAD

**Issue by DanVdr** [runelite/runelite#17229]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When running Agility Arena - the pop ups are not staying and the timer between each ticket point isn't visible

Unsure if this is RL bug or OSRS bug - or if it is even just for Leagues or not 

### RuneLite version

Runelite being launched by Jagex Account window

**Comment by YvesW** [comment]
Try disabling the ``Stealing artefacts`` plugin and restarting the client. For further support, please join the Discord server. GitHub issues is not a support tracker.

**Comment by Nightfirecat** [comment]
This is very likely due to some hub plugin you've installed clearing the hint arrow. I recommend running in safe mode or removing/disabling some hub plugins.
