### ISSUE TITLE
GIM and Reg account, doesnt allow regular account to use GE

### ISSUE THREAD

**Issue by optimallockdown11** [runelite/runelite#17238]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

If I log in through Jagex launcher, select my regular mode account using runelite, login, I cant trade anybody or use ge. Runelite thinks that I am a groupironman and group ironman icon shows up. 

### RuneLite version

1.10.17.1
2.6.7

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode? See this page for how to launch the client in safe mode: https://github.com/runelite/runelite/wiki/FAQ#how-do-i-run-runelite-in-safe-mode
