### ISSUE TITLE
raids: layout is not updated when reloading CoX via the steps

### ISSUE THREAD

**Issue by YvesW** [runelite/runelite#17241]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Jagex added an option to reload CoX using the ``steps``/lobby stairs today. The layout does not get updated when one reloads the raid using this feature.

When reloading a raid via the steps, it currently looks like:
- ``Varbit.IN_RAID`` goes 1 -> 0 -> 1
- ``Varbit.RAID_PARTY_SIZE`` 1 -> 0 -> 1
- ``VarPlayer.IN_RAID_PARTY`` not -1  -> -1 -> not -1

I suspect raid::layout needs to be nulled when reloading. I am not familiar enough with the RaidsPlugin code, the CoX varbits/varps, and CoX itself to properly update the code though. E.g. idk what happens with the varbs during the raids, on login, or when changing floors.

### RuneLite version

RL 1.10.17.1

**Comment by caerulescens** [comment]
I noticed this too and was coming to GitHub to report this if a ticket didn't exist. For anyone reading, the workaround is to turn off and turn on the plugin from the sidebar (see below).

![Screenshot from 2023-11-30 21-36-58](https://github.com/runelite/runelite/assets/29284192/16bf7a24-7c5b-4d44-9738-f540e2116a4f)

**Comment by vikke1234** [comment]
should get fixed by https://github.com/runelite/runelite/pull/17243

**Comment by TheWolfofWaterSt** [comment]
> should get fixed by #17243

Any guess as to when this will get merged in?

**Comment by Adam-** [comment]
fixed in fb98120b41560ba7c0c6195424b65f8e262836ec
