### ISSUE TITLE
Tree Textures

### ISSUE THREAD

**Issue by Guravod** [runelite/runelite#17246]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Very noticeable with the Autumn or Winter themes, Trees have a texture line below the leaves, surrounding the entire tree in a hexagon-like shape.

### Screenshots or videos

![TreeIssue117](https://github.com/runelite/runelite/assets/95885438/e58e4e5b-dfa7-444f-a548-60bcd76526b4)

### RuneLite version

Runelite Version: 1.10.17.1
Launcher Version: 2.6.4

**Comment by Felanbird** [comment]
![image](https://github.com/runelite/runelite/assets/41973452/41758311-b94a-485f-9694-4108139903e6)

**Comment by Nightfirecat** [comment]
This is part of 117HD plugin's settings.
