### ISSUE TITLE
The tagtabs tab does not display correctly

### ISSUE THREAD

**Issue by Hannah-GBS** [runelite/runelite#17263]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Clicking a tab named `tagtabs` does not display the other tag tabs as it should. Clicking `View tag tabs` from the right click menu on the `New tag tab` button works correctly, and even highlights the `tagtabs` tab if it exists, but clicking the tab from the left hand menu directly does not work.

Tested with a fresh config profile and in safe mode.

### Screenshots or videos

https://github.com/runelite/runelite/assets/7504779/7ec20133-b92f-4a2d-904f-a286543d269d

### RuneLite version

RL: 1.10.17.2
Launcher: 2.6.8

**Comment by Zanderax** [comment]
I had a crack at fixing this and I think I found a mildly elegant solution for this very niche bug.

**Comment by Adam-** [comment]
fixed in 242d23327df70f273fc577c44cd805b59bea1a59
