### ISSUE TITLE
Key Remap leads to macro ban on macOS Sonoma

### ISSUE THREAD

**Issue by Iron-Ham** [runelite/runelite#17279]
### Type

Other

### Operating System

MacOS, Apple Silicon, M1 Max

### OS Version

14.1.2

### Bug description

Turning on the WASD Remap along with f-key remaps in the client settings triggers a permanent macro ban.
I find this deeply disappointing, as playing OSRS for 25 minutes has caused my RS3 account (it's the same character) to be banned along with it. 

My setup was unaltered from the default, aside from four changes:

1. I installed `117hd`
2. I installed `quest-helper`
3. I setup WASD remapping
4. I remapped f-keys (F1 etc) as I have a 65% keyboard. 

### RuneLite version

macOS latest as of Dec. 4

### Logs

[client_2023-12-02.0.log](https://github.com/runelite/runelite/files/13679440/client_2023-12-02.0.log)
[launcher_2023-12-02.0.log](https://github.com/runelite/runelite/files/13679442/launcher_2023-12-02.0.log)

**Comment by pettrs** [comment]
can someone confirm if this has been looked into? I've just ordered a 65% keyboard online and was gonna use key remapping on the number keys. don't want to get banned though

**Comment by Iron-Ham** [comment]
@pettrs It may be worth noting that it could have been external factors to Runelite. While I experienced issues, it may have been other software I had running, such as:

- [Magnet Window Manager](https://magnet.crowdcafe.com/)
- [MacMouseFix](https://github.com/noah-nuebling/mac-mouse-fix), which I use for mapping the four-finger upwards swipe to the thumb button of my mouse, as well as mapping `⌘[` and `⌘]` to the forward/back buttons.
- I may have had my [website's](https://sundayswift.com/) development server in the background, but I have no clue if that was the case or not, since I use iTerm & have it set as an overlay.
- etc

What I can conclusively say is that I didn't have an issue with the RS3 client over a long period, but was banned within 48 hours of using RuneLite. Nothing different than my normal setup was going on when it happened. Whether that's a RuneLite issue or a Jagex issue wherein the underlying security / cheat detection system is different between the two games, I cannot say.

**Comment by Adam-** [comment]
> @pettrs It may be worth noting that it could have been external factors to Runelite. While I experienced issues, it may have been other software I had running, such as:
> 
>     * [Magnet Window Manager](https://magnet.crowdcafe.com/)
> 
>     * [MacMouseFix](https://github.com/noah-nuebling/mac-mouse-fix), which I use for mapping the four-finger upwards swipe to the thumb button of my mouse, as well as mapping `⌘[` and `⌘]` to the forward/back buttons.
> 
>     * I may have had my [website's](https://sundayswift.com/) development server in the background, but I have no clue if that was the case or not, since I use iTerm & have it set as an overlay.
> 
>     * etc
> 
> 
> What I can conclusively say is that I didn't have an issue with the RS3 client over a long period, but was banned within 48 hours of using RuneLite. Nothing different than my normal setup was going on when it happened. Whether that's a RuneLite issue or a Jagex issue wherein the underlying security / cheat detection system is different between the two games, I cannot say.

Can you email me your in game name? adam@runelite.net
