### ISSUE TITLE
WM Resizing Bug Linux (Fix / Solution provided)

### ISSUE THREAD

**Issue by Lilly966** [runelite/runelite#17271]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Arch Linux

### Bug description

When using **WM**, BSPWM in my case, the resizing is off, and creates glitches.
![bild](https://github.com/runelite/runelite/assets/115407560/60ae4f6c-8e90-4640-b561-9a298313a971)

Optionally, user can create another file that launches **RuneLite.AppImage** with the **_JAVA_AWT_WM_NONREPARENTING=1** parameter set.

**RuneLite_WM.sh**
`
#!/bin/bash
_JAVA_AWT_WM_NONREPARENTING=1 ./RuneLite.AppImage
`
`chmod +x RuneLite_SW.sh`
Then run `./RuneLite_SW.sh`
![bild](https://github.com/runelite/runelite/assets/115407560/74799a43-d4b8-450c-8b9d-f8889c853712)

### RuneLite version

RuneLite version: 1.10.17.2
Launcher version: 2.6.10
Oldschool revision: Rev 218
![bild](https://github.com/runelite/runelite/assets/115407560/e6ab49d0-e07a-415e-9b8f-f09a522d6cf5)

**Comment by Nightfirecat** [comment]
This is a known issue with certain window managers, as seen in #15909 and #16641, and is likely a bug with the window manager, not with RuneLite. That said, your workaround should work fine and not cause problems.

**Comment by abextm** [comment]
This is a well documented quirk of AWT.

**Comment by jb55** [comment]
this just started happening to me on nixos, weird. the workaround fixed it
