### ISSUE TITLE
GPU Plugin incorrectly rendering slopes

### ISSUE THREAD

**Issue by FenCooke** [runelite/runelite#17285]
### Type

GPU

### Operating System

Windows

### OS Version

Windows 11 23H2 OS Build 22631.2861

### Bug description

Issue occurs when rendering specific slopes in the game. Only the GPU plugin is enabled and uses the default settings in the provided video. This has persisted through using DDU and a new Windows installation. Using 537.58 as current GPU driver.

Hardware specs:
AMD Ryzen 5700x
NVIDIA RTX 3070
3600 @ CL16 32gb DDR4 RAM
Crosshair VII Hero

Ran the hardware through OCCT stress tests with no errors so I don't believe it's an instability issue as CPU and GPU are run at stock clocks with no undervolting, Precision Boost Overdrive etc.

The places I have noticed it occur are:
- Flamtaer temple @ Shades of Mort'ton
- The mound at the end of the Waterfall Cave created after finishing Waterfall Quest
- The slope at the entry of the Viyeldi caves (Legends' Quest cave in the jungle)

### Screenshots or videos

https://www.youtube.com/watch?v=VE109Ye_emI

### RuneLite version

Runelite Version: 1.10.17.2
Launcher Version: 2.6.10

### Logs

[client.log](https://github.com/runelite/runelite/files/13694195/client.log)
[launcher.log](https://github.com/runelite/runelite/files/13694196/launcher.log)

**Comment by Adam-** [comment]
fixed in b7d88347ea32611b262690320914e18516286825
