### ISSUE TITLE
Dragon felling axe, Crystal felling axe, and Crystal felling axe (inactive) not recognized for emote clue step

### ISSUE THREAD

**Issue by TheCrifix** [runelite/runelite#17280]
### Type

Incorrect behavior

### Operating System

None

### Bug description

When completing the clue for the following text, the overlay does not identify the Dragon felling axe, Crystal felling axe, and Crystal felling axe (inactive) as valid for it, though they are usable for the step and can be deposited into the stash unit.

> Stamp in the Enchanted valley west of the waterfall. Beware of double agents! Equip a dragon axe.

### Screenshots or videos

![incorrect](https://github.com/runelite/runelite/assets/19476885/837d5cf1-f4f7-479f-a039-d251b0d083da)

### RuneLite version

RuneLite version: 1.10.17.2
Launcher version: 2.6.7

**Comment by Nightfirecat** [comment]
I assume your axe did, in fact, work for the clue?

**Comment by TheCrifix** [comment]
Yes, my axe does work for the clue. Should have made that clear.

**Comment by Felanbird** [comment]
Fixed in 39956b2a6b2a9476b7cd60b7a81602470068c3bf
