### ISSUE TITLE
Menu Swap Metamorphosis For Chinchompa Pet

### ISSUE THREAD

**Issue by Eythrope** [runelite/runelite#1729]
Would be great if we're able to menu swap to the metamorphosis option, so we're able to spam click that option to obtain golden skin rather than having to right click & select.

![e9c70fff957d08e866a4829926026daa](https://user-images.githubusercontent.com/38555968/39042677-517557d0-4483-11e8-9692-34666d86539f.png)

**Comment by deathbeam** [comment]
I think this should not be swapped
