### ISSUE TITLE
Runelite is preventing the ESC key from working

### ISSUE THREAD

**Issue by DanMossa** [runelite/runelite#17315]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Pressing the ESC Key does not open the inventory nor close out interfaces when on Runelite.
I've tried Safemode and the issue still persisted.
I then opened and verified that the issue does not occur on the the New Client.

### RuneLite version

RuneLite version: 1.10.17.2
Launcher version: 2.6.10
Oldschool revision: Rev 218

### Logs

[client.log](https://github.com/runelite/runelite/files/13796776/client.log)
[launcher.log](https://github.com/runelite/runelite/files/13796777/launcher.log)

**Comment by Nightfirecat** [comment]
Are you certain the ingame setting to close interfaces when pressing Escape is enabled? If so, does this also happen when creating a new profile and switching to it?

**Comment by DanMossa** [comment]
@Nightfirecat 
![image](https://github.com/runelite/runelite/assets/10294777/5927b956-53fa-4bdb-82c7-ff83538af403)

I clicked new profile and switched into it and the ESC key is working again!
What do you suggest at this point?

**Comment by Felanbird** [comment]
Install the `Debug Helper` plugin from the hub and click `display keybinds` to figure out what plugin `Esc` is bound to
![image](https://github.com/runelite/runelite/assets/41973452/98a5c6fa-0401-4611-bb66-0fa529858c45)

**Comment by DanMossa** [comment]
Oh! @Felanbird 
Party Ping hotkey: Escape

Thank you!
