### ISSUE TITLE
GPU plugin black shadows on effects

### ISSUE THREAD

**Issue by BLuchterhand** [runelite/runelite#17325]
### Type

GPU

### Operating System

Windows

### OS Version

macOS Sonoma

### Bug description

Raiding in TOA and each effect has this weird set of black shadows that seems to be entirely out of sync with other effects. It's it almost appears to be some background that is out of sync and should be a different color? On static effects (like in my screenshot) it just appears as a fixture on top of whatever effect is otherwise happening.
This issue is happening with the "Compute Shaders" option enabled in the GPU plugin (I don't recognize this, is it newer?). Disabling this fixes the issue, but makes the draw distance setting completely ineffective. Notably, the 117HD plugin doesn't display either of these issues (and is lacking the same option). It behaves as normal without any issues.
For the above reasons I don't believe it to be a hardware issue on my own device, though I suppose I could be wrong.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/16824716/00199181-0f57-4be2-8f7c-16ced1aa7073)
![image](https://github.com/runelite/runelite/assets/16824716/7a55dfe2-054e-43d2-aad2-65112e5b818b)

### RuneLite version

Runelite Version: 1.10.18.1
Launcher Version: 2.6.11

### Logs

[client.log](https://github.com/runelite/runelite/files/13802350/client.log)

**Comment by BLuchterhand** [comment]
Updated to the newest update for MacOS Sonoma and the issue went away... Sorry for the inconvenience!

**Comment by Adam-** [comment]
This is an issue, I rolled back the release

**Comment by BLuchterhand** [comment]
Haha good timing then. Thanks for the update!

**Comment by Adam-** [comment]
The commit causing this has been reverted 5fdc5e6d68148acdc1f06b0349ba69a4ce4104f7. I will revisit it later.
