### ISSUE TITLE
Object Markers Permanently Showing Even With the Plugin Disabled?

### ISSUE THREAD

**Issue by kekwforyou** [runelite/runelite#17338]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I marked the latter bottom and top by shift-clicking > mark object.

When I went to remove the marker, the option was no longer present. I disabled the Plugin but the marker still shows and I do not have an option to unmark it now?

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/155770086/495b4005-cfec-4185-afea-de483756d8ca)
![image](https://github.com/runelite/runelite/assets/155770086/971532ea-d7b7-46f0-a4e3-0e50cea6b809)

### RuneLite version

1.10.18.2

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Or on Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by kekwforyou** [comment]
> Does this behavior happen while running in safe mode?
> 
> To open in safe mode on Windows: In Command Prompt, run:
> 
> ```
> "%localappdata%\runelite\runelite.exe" --safe-mode
> ```
> 
> Or on Mac: In Terminal, run:
> 
> ```
> /Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
> ```

Thanks for the quick response. This behavior does not happen while in safe mode. I do not see the objects marked in this mode.

![image](https://github.com/runelite/runelite/assets/155770086/c00c6d50-782b-4708-89a5-7f4f32574472)

**Comment by Nightfirecat** [comment]
Then you have some hub plugin installed which is marking those objects. I recommend disabling and uninstalling hub plugins which you might have until this behavior goes away.
