### ISSUE TITLE
XP Tracker briefly shows negative total XP/hr sometimes

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#1734]
Each of the following screenshots shows the total xp/hr displayed as roughly MIN_INT for a signed 32-bit integer. I was able to reproduce them each the following ways, with the issue being present for one or two game cycles before it corrected itself. With no other skills being tracked (that is, after "Reset All" is chosen):

- Check the health of a tree patch, then start chopping logs from that patch
- Pick herbs from an herb patch, then clean those herbs
- Teleport to Trollheim, then use the agility shortcuts to traverse down the mountain (not sure about this one; have not tested in isolation)

![2018-04-20_00-25-00](https://user-images.githubusercontent.com/2199511/39061493-ff5cabb6-44b3-11e8-9221-dd1a93266c79.png)
![2018-04-20_00-40-46](https://user-images.githubusercontent.com/2199511/39061494-ff76ac6e-44b3-11e8-804e-d2dd2ba4285f.png)
![2018-04-20_00-41-38](https://user-images.githubusercontent.com/2199511/39061495-ff92e9c4-44b3-11e8-852a-f0ffef0f94f1.png)

**Comment by Adam-** [comment]
Check if this is still present post #1367

**Comment by Nightfirecat** [comment]
I'll check with the coming release :+1:

**Comment by LeviSchuck** [comment]
#1367 is now on master. I believe this fixes that issue as I also noticed it while redoing the internal data structure.

**Comment by Nightfirecat** [comment]
I'll try to do a farm run on master's code to check if I remember.

**Comment by Nightfirecat** [comment]
Not fixed. This is from current master branch code.
![2018-05-01_22-37-29](https://user-images.githubusercontent.com/2199511/39506900-0867aefc-4dcb-11e8-940f-5db073cb69c2.png)

**Comment by Nightfirecat** [comment]
I noticed that XpTrackerPlugin subscribes to both `ExperienceChanged` and `GameTick` events. Which order do they come in on a tick where XP is updated?

**Comment by LeviSchuck** [comment]
Still not solved?

Okay, got a couple questions:

1. Are you world hopping?
2. Are you switching between accounts?
3. How much XP do your actions provide and to what skills?
4. How much time happens between actions?

**Comment by Kamielvf** [comment]
I was easily able to reproduce something similar using one of the steps @Nightfirecat mentioned (only thing my total exp not showing  -max_int)
![image](https://user-images.githubusercontent.com/35824069/39542371-acf7f102-4e48-11e8-8691-dac07bdcec35.png)

**Comment by Kamielvf** [comment]
It going into the minus just means that the integer overflows the max value, so I'm not exactly sure if there actually is a bug here aside from it briefly displaying such a huge amount (because first time you gain exp is "instant" so the the calculation would use for example 3ms = 1 action)

**Comment by LeviSchuck** [comment]
Cause: Divide by zero result = Max Integer.
Adding max integer to another integer results in negative integer due to signed integer behavior.

```
FISHING Time in seconds: 0
FISHING Value: 90
FISHING Result: 2147483647
...
FISHING Time in seconds: 1
FISHING Value: 90
FISHING Result: 324000
```

When I add `FLETCHING Result: 2147483647` to `FISHING Result: XXX`, I get `-214748XXXX`

I'll write up a PR for this. I think I have a solution for it.

**Comment by Kamielvf** [comment]
Yeah thats exactly what I was saying. Maybe we could assume time always being 0.5 seconds at the least, which seems reasonable.

**Comment by LeviSchuck** [comment]
@Kamielvf I tried low second values and it was still crazy. It worked well with 60 seconds in my testing.

**Comment by Kamielvf** [comment]
Makes sense, you could get an xp drop each tick which is why I suggested 0.5 seconds but if that happens your Xp tracker will update accordingly anyway.

**Comment by Nightfirecat** [comment]
Will do later today.

**Comment by Nightfirecat** [comment]
Yup, problem solved. :+1:

**Comment by Nightfirecat** [comment]
Unfortunately, it looks like this isn't fixed after all--just saw it again today... :confused: 

![2018-05-04_19-10-04](https://user-images.githubusercontent.com/2199511/39659020-eb257126-500e-11e8-8c31-56e796b57ecf.png)
![2018-05-04_19-10-10](https://user-images.githubusercontent.com/2199511/39659021-eb3f157c-500e-11e8-883d-df3edae3d148.png)

Video of a simpler repro case: https://www.youtube.com/watch?v=afAqr3EATvs (wind striking, meleeing, pickpocketing NPCs and burying bones in Lumbridge)

**Comment by psikoi** [comment]
https://github.com/runelite/runelite/pull/1419 fixed in here, in case you want to wait.
