### ISSUE TITLE
Runelite crash

### ISSUE THREAD

**Issue by ZigaJavornik** [runelite/runelite#17343]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I was in my bank interface at TOA, then i clicked on something and the application crashed. Log attached. Nothing more I can provide... I died, reclaimed items from chest opened the bank, equiped items from bank and on one of the clicks, the crash happened.

### RuneLite version

RL version 1.10.18.2
Launcher: 2.6.7

### Logs

[launcher.log](https://github.com/runelite/runelite/files/13850982/launcher.log)
[client.log](https://github.com/runelite/runelite/files/13850985/client.log)

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Or on Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by ZigaJavornik** [comment]
Hard to say, I couldnt replicate it. I will try and see if it can be replicated a bit more, if so I will try safe mode as well.
