### ISSUE TITLE
XP Tracker "Actions left" shows inaccurate number

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#1735]
The following screenshot was taken after getting a large single awarding of experience from Tears of Guthix: 11484, with 43736 experience remaining to achieve a new level. This should be 4 actions left, but the tracker instead shows 3 actions left.

```
$ python3 -c 'print(43736 / 11484)'
3.8084291187739465
```

![2018-04-19_17-04-04](https://user-images.githubusercontent.com/2199511/39061864-3d2f731e-44b5-11e8-8dde-7861eb0ea928.png)

**Comment by Nightfirecat** [comment]
I'm almost certain it's an integer division issue in the current code, given that the same calculation in other programs (like python2) will give the integer `3` as the result of that calculation. Glad it's already handled in your PR @LeviSchuck. :)

**Comment by Adam-** [comment]
Fixed in #1367
