### ISSUE TITLE
Jagex launcher

### ISSUE THREAD

**Issue by bubbawade9** [runelite/runelite#17367]
### Type

Other

### Operating System

Windows

### Bug description

I upgraded my account so i could use the Jagex launcher so that i could play in a hardcore ironman group, after doing so my main account (normal) now cannot access the grand exchange and says i'm in a group ironman, but i can still use houses and according to the iron man tutor, i am not an ironman.  Someone please help.

### RuneLite version

Runelite version: 1.10.19
Oldschool version: Rev 219
Launcher version: 2.6.7

**Comment by Adam-** [comment]
You've probably installed a plugin which limits grand exchange use. Using safe mode will disable the plugin and let you play. RuneLite does not restrict usage of the GE.

**Comment by bubbawade9** [comment]
The last plug-in I installed was a tombs of amascut, this started when I
upgraded my account to use the Jagex launcher

**Comment by bubbawade9** [comment]
Nvm I found the issue, thank you!!!!
