### ISSUE TITLE
Graphical alignment issue with 2024-01-10 client update

### ISSUE THREAD

**Issue by Speeddymon** [runelite/runelite#17360]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

![image](https://github.com/runelite/runelite/assets/1396056/e58b0a34-1851-4af5-878d-fe8ae7e52ca6)

This is every panel now. Yesterday before Leagues ended, it was aligned properly; so I guess the removal of the Kourend Favour tab changed some sizing related variables and they need to be adjusted to scale properly. I have no idea, just a wild guess.

### Screenshots or videos

See above

### RuneLite version

RuneLite version: 1.10.19
Oldschool revision: Rev 219
Launcher version: 2.6.8

**Comment by raiyni** [comment]
Hold alt and right click your inventory.

**Comment by Speeddymon** [comment]
Funny enough, I had actually tried that and while I could move other things around, the mentioned part of the UI was not one that it would allow me to move, however it worked and I could move it after restarting Runelite.
