### ISSUE TITLE
[Clue Scroll] New master clue step is missing

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#17362]
### Type

Other

### Operating System

None

### Bug description

The January 10th game update apparently ~~added a new~~ edited an existing master-tier cryptic clue. The previous version of the clue was, "She's small but can build both literally and figuratively, as long as you have their favour". The new version is, "She's small but can build both literally and figuratively." The solution is still to speak to Lovada in Lovakengj.

### RuneLite version

RuneLite version: 1.10.19
Launcher version: 2.6.10

**Comment by YvesW** [comment]
Already fixed in https://github.com/runelite/runelite/commit/9441b0c77a2085e69bd558e137dc6717d7bb1d2b

**Comment by Nightfirecat** [comment]
Per YvesW's comment this will be working again next release.
