### ISSUE TITLE
Fishing spots stack in the wrong order

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#1737]
Instead of being rendered based on distance from the player, they are strictly ranked based on type of fish, resulting in certain types always showing on top.

![2018-04-20_09-19-08](https://user-images.githubusercontent.com/2199511/39062602-8ed0ac18-44b7-11e8-908e-da96fb8c08e9.png)
![2018-04-20_09-19-38](https://user-images.githubusercontent.com/2199511/39062593-8640e59a-44b7-11e8-8099-0b38774a0979.png)

**Comment by LeviSchuck** [comment]
Shrimp > Lobster > Shark
Thus Shrimp > Shark;

It is not that these are being drawn in some sort of rank on our side.
It is that they are being drawn in the order that the get NPC query is returning.

FishingSpotOverlay refers to fishingSpots in FishingPlugin which is refreshed by `FishingPlugin::checkSpots`.

Thus, to fix this into the desired behavior, one would need to sort this array by distance from the player, either in FishingPlugin::checkSpots.

I do not recommend re-sorting the array in FishingSpotOverlay, as that is done every frame.  `FishingPlugin::checkSpots` runs every game tick so it should be fine for sorting purposes in relation to the player's relative position

**Comment by LeviSchuck** [comment]
I'll take this on.
