### ISSUE TITLE
API function call getMessage() for dialog boxes cuts off any content over 200 characters

### ISSUE THREAD

**Issue by Kipx** [runelite/runelite#17372]
### Type

Bug

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The API does not return the full dialog for text over 200 characters. Any characters after 200 are just cut off from the result.

An example is per the screenshot, the actual output of getMessage or related functions (like MessageNode.getvalue) will instead return:

> Ceril Carnillean|My son is a good boy, really, but how could he give his dinner to Scruffy without having the servants test it for poison first? How? How could he be so thoughtless and careless? He kn

Since the name of the NPC is returned with the result, the amount cut off at the end depends on the length of the NPC name.

### Screenshots or videos

![java_0w3VbCNeFQ](https://github.com/runelite/runelite/assets/1342711/90ea6916-0534-4660-b619-38c59c0871df)

### RuneLite version

1.10.19
2.6.10

**Comment by Adam-** [comment]
This is a Jagex limitation and can't be fixed by us. If you need to read a longer message, either read it from the dialog interface or maybe just do startsWith() for matching.

**Comment by Kipx** [comment]
Gotcha, thanks for the quick response. I'll find a workaround somehow!
