### ISSUE TITLE
Kourend Library Plugin Does Not Work

### ISSUE THREAD

**Issue by CloudyMischief** [runelite/runelite#17376]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

11

### Bug description

When entering the library all white squares appear than after collecting a book or to the locations configure but all of them are wrong/ do not actually give the books locations

### RuneLite version

RLV: 1.10.19 Launcher Version: 2.6.10

**Comment by Felanbird** [comment]
Restart your client, the update that has the fix literally just came out

**Comment by Adam-** [comment]
duplicate of #17358

**Comment by CloudyMischief** [comment]
Sick ty
