### ISSUE TITLE
Timer for overloads

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1738]
Not talking about the 5min timer overlay that currently exists but the every 15 seconds the boosts go back up. Would be nice to have some way of telling when it is going to 'reset'. Not entirely sure the best way to go about this tbh

**Comment by deathbeam** [comment]
I dont think timer for this is really useful, as you do not want to take any action during the "reset" period anyway (no point in boosting up when you are going to be boosted again soon anyway)
