### ISSUE TITLE
Special Attack Orb becomes non-interactive

### ISSUE THREAD

**Issue by pidymiles** [runelite/runelite#17388]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The special attack orb sometimes becomes non-interactive, meaning it cannot be clicked. When this happens, clicking on the special attack orb performs the action UNDERNEATH the special attack orb. For example, if the special attack orb is overlayed on top of an oak tree, the special attack orb will perform the action "Chop Oak tree" when clicked.

I found this bug because the majority of times I click the special attack orb, it does not perform special attack action. The issue started occurring very recently.

I was not able to replicate the issue on the official Jagex client and seems to be related to Runelite. As far as I know, I do not have any plugins which affect the functionality of the world map/special attack orb section of the client.

### Screenshots or videos

<https://youtu.be/k_ExRJGUUQs>

### RuneLite version

Runelite Version: 1.10.19.1
OldSchool revision: Rev 219
Launcher Version: 2.6.7

### Logs

[client.log](https://github.com/runelite/runelite/files/13956594/client.log)
[launcher.log](https://github.com/runelite/runelite/files/13956595/launcher.log)
[jvm_crash_pid_8092.log](https://github.com/runelite/runelite/files/13956602/jvm_crash_pid_8092.log)

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

To open in safe mode on Windows: In Command Prompt, run:
```
"%localappdata%\runelite\runelite.exe" --safe-mode
```

Or on Mac: In Terminal, run:
```
/Applications/RuneLite.app/Contents/MacOS/RuneLite --safe-mode
```

**Comment by pidymiles** [comment]
I would gladly test this; however, it is currently not possible to sign into Runelite without the Jagex Launcher. Is there a way to modify the Jagex launcher to run Runelite with this argument?

**Comment by Nightfirecat** [comment]
Run the `RuneLite (configure)` shortcut and tick the Safe mode box, then launch RuneLite via the Jagex launcher.

**Comment by pidymiles** [comment]
Yes, the issue is also occurring in Safe Mode. Thanks for showing me how to configure safe mode

**Comment by Nightfirecat** [comment]
Have you swapped the left-click option of these oak trees to "Chop-down" via the Menu Entry Swapper plugin?

**Comment by pidymiles** [comment]
I don't recall swapping these options but I must have done it inadvertently. Disabling MenuEntrySwapper corrected the issue I was having. I turned it back on and reset the left click options for Oak Tree and now I cannot replicate the issue.

Thank you for the assist.
