### ISSUE TITLE
GPU Draw Distance Limited - Windows 10 ARM64

### ISSUE THREAD

**Issue by alasdairhendry** [runelite/runelite#17400]
### Type

GPU

### Operating System

Windows

### OS Version

10

### Bug description

May be related to #17017, however, I dont have the same error messages in my logs.

As described in that report, the draw distance will not draw more than 25 tiles regardless of number selected.

### RuneLite version

Runelite Version: 1.10.19.1
Launcher Version: 2.6.1

### Logs

[client.log](https://github.com/runelite/runelite/files/13988667/client.log)
[launcher.log](https://github.com/runelite/runelite/files/13988668/launcher.log)

**Comment by Alexsuperfly** [comment]
enable compute shaders in the gpu plugin

**Comment by Alexsuperfly** [comment]
9dfb067de628a5b4500cf3fc8402a0958a5f73e9 removed the draw distance limit without compute shaders
