### ISSUE TITLE
"Remember client position" not working

### ISSUE THREAD

**Issue by Laurens-W** [runelite/runelite#17418]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

I have two monitors. 
Since today when I place a client on the left side of the right screen tightly against the top or bottom and left edges it doesn't seem to remember the position.

### Screenshots or videos

Re opening the client spawns it in the middle of my right monitor

### RuneLite version

runelite: 1.10.20.3
launcher: 2.5.0

**Comment by Adam-** [comment]
If you position the client more than 8px off of the edge of the screen, does it work correctly?

**Comment by Adam-** [comment]
this is fixed in 144e2269817ebf1699093289cf3e10c0aba3c316

**Comment by Laurens-W** [comment]
> If you position the client more than 8px off of the edge of the screen, does it work correctly?

Yeah when I initially loaded my clients yesterday they seemed about 8 pixels off the edge :)
Can't wait for the fix to be released, thanks for the quick response!
