### ISSUE TITLE
Kourend Library

### ISSUE THREAD

**Issue by slaytr** [runelite/runelite#17429]
### Type

Crash or hang

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Kourend Library book location combinations changed after the Varlamore patch. There was a PR that removed the Dark Manuscripts but the plugin itself is broken because the book location combinations got scrambled after that update and don't match the ones present in the plugin anymore. This results in incorrect book locations

### RuneLite version

1.10.20.4

**Comment by Felanbird** [comment]
Are you sure they changed the patterns, and not just the world you are on has a new pattern that Jagex added?

Can you replicate it not working as expected, on multiple worlds?

**Comment by YvesW** [comment]
This was fixed approximately 18 days ago in https://github.com/runelite/runelite/commit/4095801acebf28918c416f5e8f425b6b2ddca588

AFAIK there is one combination that is impossible, but that is a Jagex bug and requires hopping to a different world.

**Comment by slaytr** [comment]
@Felanbird @YvesW you guys are right, I can get it to work. I had previously tried it on 3 different occasions and it wasn't working  correctly. It appears to be working this morning 🤷
