### ISSUE TITLE
Clue Plugin: Dragon defender (l)(t) not detected 

### ISSUE THREAD

**Issue by akselsd** [runelite/runelite#17422]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Clue plugin GUI does not detect Dragon Defender (l)(t), as "Dragon Defender", but it is accepted by Falo

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/36104433/1703d9c4-70c8-4d51-a122-34274c74b1e6)
![image](https://github.com/runelite/runelite/assets/36104433/678eaf7c-6f26-40a0-b837-e5f1780c2393)
![image](https://github.com/runelite/runelite/assets/36104433/fd6d5a7c-e3d4-45f7-a0b4-de9b033886da)

### RuneLite version

Runelite version: 2.5.0

**Comment by Adam-** [comment]
fixed in 3791f7387ddd4acd7c876f3cf3985ca03eac151e
