### ISSUE TITLE
Runelite sidebar affects client size after Windows snapping

### ISSUE THREAD

**Issue by ImFlizz** [runelite/runelite#17428]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

With the new Runelite update, if the height of the client is too small for the number of icons in the sidebar, a second column will be created.

If your client has two columns originally, and you snap it to the right, and the client height is now large enough for all icons to fit in one column, then there will be a gap on the right because Windows thinks there is still a second column there.

Inversely, if you originally had one column and you snap it to a corner, thus reducing the client height, the newly created second column will either be offscreen or covering another window.

### Screenshots or videos

https://discord.com/channels/301497432909414422/442492468307427330/1201729635704901642

https://discord.com/channels/301497432909414422/442492468307427330/1201730019605352478

### RuneLite version

Runelite version: 1.10.20.4
Launcher version: 2.6.9

**Comment by idle-user** [comment]
Definitely annoying. 
Give us the option to have the side menu scrollable with the scroll wheel .
Or are we able to hide specific side menu items? What about grouping them in folders like Discord does to servers.

**Comment by abextm** [comment]
Fixed in 93e6f5e2d5c514e0f6112503776191ac8a20afa8
