### ISSUE TITLE
Highlight the respective STASH unit per emote clue.

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#1742]
Would be nice, as sometimes the STASH units are a bit out of the way compared to the emote spot. (And can kind of blend to scenery in some cases)

**Comment by raiyni** [comment]
closed by https://github.com/runelite/runelite/pull/6172

**Comment by Nightfirecat** [comment]
I'm pretty sure 6172 doesn't highlight them?

**Comment by Adam-** [comment]
This was added in #8892
