### ISSUE TITLE
Status bars plugin misalignment and Inventory not movable since most recent update

### ISSUE THREAD

**Issue by Inlustra** [runelite/runelite#17433]
### Type

Crash or hang

### Operating System

None

### OS Version

Windows 11

### Bug description

As described in the title, holding alt to move the Chat & also the inventory is broken. 
The Minimap appeared below when first logged in, but was  movable

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/2565465/11831007-189b-4e04-a221-272a490d865f)
![image](https://github.com/runelite/runelite/assets/2565465/e4dc0ca8-4163-49de-a656-c3de1e9a1ff8)

### RuneLite version

Runelite version: 1.10.20.4
Oldschool Revision: 219
Launcher version: 2.6.4

**Comment by abextm** [comment]
restart your client
