### ISSUE TITLE
Expand Outer Zoom Limit no longer working

### ISSUE THREAD

**Issue by GaelL42** [runelite/runelite#17437]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10, Version 22H2 (OS Build 19045.3930)

### Bug description

Despite having a value of 400 in the "Expand Outer Zoom Limit" field of the Camera plugin, I am no longer able to zoom out to my heart's content. I don't know if it stopped working today or slightly before, but I am sad :(

### Screenshots or videos

https://www.youtube.com/watch?v=OqQe_mVWlr8&ab_channel=GaelL

### RuneLite version

RL version 1.10.20.4, Rev 219, Launcher 2.6.7

### Logs

[client.log](https://github.com/runelite/runelite/files/14120828/client.log)

**Comment by Felanbird** [comment]
`1.10.20.4` is not the latest version, restart your client

**Comment by GaelL42** [comment]
...Damn, now I feel dumb ! The classic "turn it off and on again" trick worked, the Outer Zoom is now functional (my launcher version is now 1.10.21). Should have thought about that. Have a good day !
