### ISSUE TITLE
mac app appears to be transparent??

### ISSUE THREAD

**Issue by clebauer** [runelite/runelite#17445]
### Type

Incorrect behavior

### Operating System

None

### OS Version

MacOS Ventura 13.6.1 (22G313)

### Bug description

When I open Runelite, the loading screen is opaque (as shown in the screenshot), but once it loads, it's almost entirely transparent. I'm able to move the window around, log in, and even play. The tooltips on the side bar are opaque, but everything else is transparent.

I deleted runelite from my applications and redownloaded it from runelite.net.

I've never faced this issue before.
I'm unsure what to do next.

### Screenshots or videos

<img width="259" alt="image" src="https://github.com/runelite/runelite/assets/31354379/c52bb280-61de-4ef3-a765-443667e6d640">
<img width="1440" alt="image" src="https://github.com/runelite/runelite/assets/31354379/8e834470-0296-4692-85a6-1010bb375f31">
<img width="1440" alt="image" src="https://github.com/runelite/runelite/assets/31354379/9aad55e2-bb00-472a-b8b2-6eefa36d461f">
<img width="1440" alt="image" src="https://github.com/runelite/runelite/assets/31354379/c021c871-839e-4e48-a3f4-4fbcb13fd4b2">
<img width="449" alt="image" src="https://github.com/runelite/runelite/assets/31354379/de62bbdd-fd21-4e94-b831-f46997c68c5c">

### RuneLite version

Runelite Version: 1.10.21.1
Launcher Version: 2.6.13
<img width="209" alt="image" src="https://github.com/runelite/runelite/assets/31354379/145202a2-4d41-4977-8d20-89ebd7147984">
(it's hard to see)

### Logs

[client.log](https://github.com/runelite/runelite/files/14154560/client.log)
[launcher.log](https://github.com/runelite/runelite/files/14154561/launcher.log)

**Comment by Adam-** [comment]
Increase the "window opacity" too 100 
![image](https://github.com/runelite/runelite/assets/309739/653318bf-40cd-4866-bb16-24f4748de097)

The feature has existed for a long time, but only recently began working on macos.

**Comment by clebauer** [comment]
<img width="253" alt="image" src="https://github.com/runelite/runelite/assets/31354379/e59f885c-c8cb-4677-952c-173af28b6f99">

Amazing, thank you so much. I don't know why it immediately set itself to 10, but thank you so much!
