### ISSUE TITLE
Cox scouter

### ISSUE THREAD

**Issue by thefriendlydish** [runelite/runelite#17467]
### Type

Other

### Operating System

Windows

### OS Version

windows 11

### Bug description

Have been raiding recently and Yesterday (2024-01-07) the Cox scouters stopped functioning. I am unable to use the '!layout' commands and the little box that displays the raid layout is missing with both plugins enabled

### Screenshots or videos

![2024-02-07_12-34-33](https://github.com/runelite/runelite/assets/159275235/ab899aba-79fd-4d3c-a1da-103da4115e8f)

### RuneLite version

1.10.21.1 RL version
2.6.13 Launcher

### Logs

[client.log](https://github.com/runelite/runelite/files/14199604/client.log)
[launcher.log](https://github.com/runelite/runelite/files/14199605/launcher.log)

i hope this is what you mean

**Comment by YvesW** [comment]
Regarding the core CoX plugin: make sure to uninstall the ``low detail chambers`` plugin if you have it installed (your logs don't load on mobile for me).

Regarding CoX scouter external: it's a hub plugin. Feel free to contact the author of that plugin. We do not make or maintain it.
