### ISSUE TITLE
Holding ctrl+shift and clicking a tile sometimes causes ctrl-lock like behavior

### ISSUE THREAD

**Issue by 4tet** [runelite/runelite#17478]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I had initially reported this in the Hub Party Panel plugin's repo (TheStonedTurtle/party-panel#30) but was told that plugin doesn't implement tile pinging.

To reproduce, holding ctrl and shift and click a tile while in a party to ping a tile, then release both keys. Now click on a tile to walk there, but instead of walking there I'm finding that about half the time I end up pinging the tile even though I'm no longer holding the ctrl key. It nearly got me killed at ToB when I accidentally held both keys down while trying to shift click on a tile to walk there.

### RuneLite version

Runelite version: 1.10.21.2
Launcher version: 2.6.1

**Comment by Troelsbr** [comment]
Bump! This is definitely an issue more people must be experiencing.
To reproduce: 
 - Hold Ctrl down
 - Hold Shift down
- Release Shift
- Release Ctrl
This toggles a ctrl lock until ctrl is pressed again

**Comment by Troelsbr** [comment]
Update: This is a bug in the custom menu entry swapper plugin. It happens only if you have any custom swaps assigned to Ctrl

**Comment by geheur** [comment]
#15649 I made a PR for this issue

**Comment by Nightfirecat** [comment]
Fixed in  #15649
