### ISSUE TITLE
Kourand Tooltip in World Map plugin

### ISSUE THREAD

**Issue by Silersun** [runelite/runelite#17474]
### Type

Other

### Operating System

Windows

### OS Version

10

### Bug description

Hovering the Kourand Teleport icon on the world map still displays Level 69, however OSRS recently updated the spell to require level 48.
This is a feature with the World Maps plugin.

### Screenshots or videos

![Kourand World Map](https://github.com/runelite/runelite/assets/159461679/3bda2fef-e9ad-4e78-b5b4-ca35ae9d213f)
![Kourand Spell](https://github.com/runelite/runelite/assets/159461679/02c16f42-e42b-4a2c-92dd-62b6885c14cd)

### RuneLite version

Runelite version: 1.10.21.1
Launcher version: 2.6.8

**Comment by Alexsuperfly** [comment]
this was already fixed in #17447
