### ISSUE TITLE
[Chat Timestamps] Timestamp does not appear when examining Burning brazier

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#17487]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Examining the [Burning brazier](https://oldschool.runescape.wiki/w/Burning_brazier) in the Gnome Stronghold does not print a chat timestamp. Other nearby objects do not have this issue.
![2024-02-11-14-50-24](https://github.com/runelite/runelite/assets/33790641/d5319143-21af-446d-9ea3-933ac0147c2a)

### RuneLite version

RuneLite version: 1.10.21.2
Launcher version: 2.6.10

**Comment by Adam-** [comment]
The examine has a line break in it and so it gets wrapped to the second line. This is the intended behavior.
