### ISSUE TITLE
Cannot find symbol class ComponentID

### ISSUE THREAD

**Issue by dewi-deBaat** [runelite/runelite#17491]
### Type

Crash or hang

### Operating System

Windows

### OS Version

11

### Bug description

By running trough the build with IntelliJ guide. It started yesterday after (re)pulling from master branch

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/62606624/ac719fe9-7b74-4db6-9407-402d6bd3d63c)

### RuneLite version

Latest

**Comment by Adam-** [comment]
This class is generated at build time. This is not a bug.

**Comment by dhruvi1404** [comment]
I am trying to run the test cases after building and facing the same issue, what should I do to run all test cases, I want to check the coverage, and look into test cases

**Comment by CBOnyxDeveloper** [comment]
i still have this problem what is the solution??

**Comment by fmule** [comment]
![image](https://github.com/runelite/runelite/assets/96919124/6ebe20ec-6581-4c86-97f1-03b23e97df5f)

Worked for me.

**Comment by raynna** [comment]
![image](https://github.com/user-attachments/assets/6e60e525-2451-466c-9f6d-8db5c359acb3)
You have to run this before running the client, this installs the nessesary libraries
