### ISSUE TITLE
XP Tracker: Support on-screen widgets in addition to the sidebar panel

### ISSUE THREAD

**Issue by SoyChai** [runelite/runelite#1749]
With the new designs we have in the works, these could be much more data-rich than the vanilla XP widgets, and allow more full-screened skilling by freeing up the sidebar.

**Comment by LeviSchuck** [comment]
Do you have a mock up that you can share?

**Comment by SoyChai** [comment]
I don't, this is just a concept suggestion from a discord visitor.

**Comment by forfiet2** [comment]
This is just a mockup or the idea behind it 👍 

http://prntscr.com/jb1r0j

**Comment by Adam-** [comment]
Added in #4022
