### ISSUE TITLE
FlatLAF checkboxes are very hard to see on the Skill Calculator

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#17490]
### Bug description

It is very difficult to notice the checkbox on the right side of Skill Calculator bonus rows. Previously, it stood out better.
![Screenshot_20240212_155906](https://github.com/runelite/runelite/assets/2199511/c61f9880-083d-4354-a72b-6ddda19ae714)

This could be improved in a number of ways, such as changing the checkbox design, or changing the bonus rows design. Given the flexibility here, I figured a discussion would be worthwhile.

**Comment by abextm** [comment]
Fixed in 3662512f578d75ecfe4ec8c962221faa4425e9d3
