### ISSUE TITLE
Weiss herb patch wrong name for herb

### ISSUE THREAD

**Issue by loloias** [runelite/runelite#17508]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

I was doing my herb run and noticed that the feature where the herb object are named (e.g. "Avantoe herbs" instead of "Herbs") is wrong when planting Snapdragon seeds in the Weiss patch. It says "Torstol" herbs even though "Inspect" reveals that the herb is indeed Snapdragon.

### RuneLite version

RuneLite version: 1.10.22
Oldschool revision: Rev 220
Launcher version: 2.6.1

**Comment by joemckie** [comment]
Been trying to find the culprit of this myself. It's not just isolated to the Weiss patch; it's every protected patch, i.e. Weiss, Kourend and Troll Stronghold.

**Comment by loloias** [comment]
Hello. Thank you for the response - good to hear that I wasn't going crazy :)

Do you happen to know what plug-in names the herb objects in the first place?

**Comment by Adam-** [comment]
This is not a feature of RuneLite. It's probably caused by a third party plugin you've installed.

**Comment by joemckie** [comment]
> Hello. Thank you for the response - good to hear that I wasn't going crazy :)
> 
> Do you happen to know what plug-in names the herb objects in the first place?

I have no idea. It just appeared out of nowhere one day. Been trying to figure it out but it's not very obvious!

**Comment by joemckie** [comment]
@loloias Found it! The culprit is Item Charges Improved
