### ISSUE TITLE
Mountain Daughter Bug

### ISSUE THREAD

**Issue by amagician-rs** [runelite/runelite#17516]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Doing the Mountain Daughter quest and noticing an issue with the step when you have to chop the dead trees before entering the cave. On the Runelite client the trees always showed "examine" regardless of restarting client. 

On the official client however it was fine.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/85969397/f6bbea56-5b48-4ee5-9d38-246683e30255)
![image](https://github.com/runelite/runelite/assets/85969397/b23b043c-6c9e-4a00-89af-e67a2bd37dd2)

### RuneLite version

1.10.23
2.6.7

**Comment by YvesW** [comment]
You are using a hub plugin that hides these options, e.g. ``Custom menu swaps``.

**Comment by amagician-rs** [comment]
> You are using a hub plugin that hides these options, e.g. `Custom menu swaps`.

Ah. You are correct...
I thought I was on a fresh RL profile, apparently am not.
