### ISSUE TITLE
timestamp not working

### ISSUE THREAD

**Issue by gtoilet** [runelite/runelite#17517]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

win 11

### Bug description

timestamps not showing up today has been working for long time just fine

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/11322067/18ecdebf-754b-4052-83c0-718288c9b7bd)

### RuneLite version

2.6.7

**Comment by Alexsuperfly** [comment]
you have to restart the client to receive updates
