### ISSUE TITLE
NPC Aggro lines are not hidden after recent update

### ISSUE THREAD

**Issue by CreativeTechGuy** [runelite/runelite#17511]
### Type

Incorrect behavior

### Operating System

None

### OS Version

N/A

### Bug description

Ever since [this commit](https://github.com/runelite/runelite/commit/f30ce8ac4e5ae05e0e6fb9c446a533d0c8c86427) the NPC Aggression Timer plugin doesn't hide when leaving an area.

This applies when the configuration is:
* Always active: false
* NPC Names: _something defined_
* Hide when out of combat: false
* Show on slayer task: false

What used to happen was when you entered an area that had a matching NPC name, the plugin appeared (lines and timer), then when you left the area then it disappeared/deactivated.

Now, once you enter an area that has a matching NPC name once in a session, the plugin is active forever as it never automatically turns off.

### RuneLite version

RuneLite Version: 1.10.22

**Comment by Adam-** [comment]
This broke because the plugin uses the full npc scans to set active=false. I've reverted it in a45b983113d0c4932e42b2da53b296ee5a65f918. For good measure I tried to avoid some of the scanning in 020e8a200057d078839504ea523ada962110dad7 when it isn't necessary. Maybe it won't break again.
