### ISSUE TITLE
Recolor HP XP drops when praying

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#1751]
With split XP drops, HP XP drops are not recolored when using prayers.
I think they should be recolored. Why I think this would make sense:
- HP is a combat skill.
- Clarity (Makes it easier to see that you had pray enabled for the hit. Instead of seeing a non-colored drop and a colored drop, you'd see 2 colored drops.)

Before:
![before](https://vgy.me/ij0MJN.png)

After:
![after](https://vgy.me/k1eUMC.png)

Combined XP drops:
![nonsplit](https://vgy.me/JoYGqL.png)

**Comment by Kamielvf** [comment]
I agree, it would make sense to also colour the HP drop.

**Comment by Adam-** [comment]
Fixed in #1791
