### ISSUE TITLE
Wiki plugin does not respect "Show Wiki entity lookup" in-game setting

### ISSUE THREAD

**Issue by bool-laean** [runelite/runelite#17523]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When the Wiki plugin is enabled, the Wiki entity lookup button is displayed below the world map button, regardless of whether the "Show Wiki entity lookup" setting is checked or unchecked in the in-game settings menu. The only way to hide this button is to disable both the in-game setting *and* the Wiki plugin in RuneLite.

This means that there's no way to use the other features of the Wiki plugin (right click wiki lookup on quests/diaries, DPS calculator etc.) with the Wiki entity lookup button hidden. It also means that a default feature of RuneScape (the ability to hide the Wiki button) appears broken by a default RuneLite plugin.

Steps to reproduce:

- Enable the Wiki plugin
- Open the in-game settings menu, and disable the "Show Wiki entity lookup" setting in the Interfaces section
- Look below the world map button - The Wiki button is there!

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/161162979/c003a9c1-4504-40f7-b646-821a174a5cd2)

### RuneLite version

Runelite version: 1.10.23.1
Launcher version: 2.6.1

**Comment by Adam-** [comment]
This is the intended behavior currently. We do not typically have the RS settings enable/disable RL settings like that. However it makes sense to have a setting in the plugin to enable/disable our button though.  Doing what you suggest would make it not possible to use both the RS button (which has slightly different mechanics and also came after we made ours) + also have the DPS button on the equipment menu at once.
