### ISSUE TITLE
Display weakness when fight an NPC.

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#1752]
![image](https://user-images.githubusercontent.com/38350898/39081304-600e29e2-4547-11e8-92c3-50d22318aaa3.png)

You could do it in a better way, maybe change the position of the box.. or many ways, you can also disable and enable the plugin?

You only pull the data from osrswiki page.

**Comment by deathbeam** [comment]
I don't think implementing something like this is reasonable, we would need a lot of data + it would be annoying clutter. And on most monsters the weakness doesnt matter at all
