### ISSUE TITLE
Lost all data in loot tracker

### ISSUE THREAD

**Issue by frerems** [runelite/runelite#17534]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 11

### Bug description

Logged into my runelite account on another pc. when i logged back, all loot tracker info was gone. Is there a way to recover this? 

### RuneLite version

runelite: 1.10.23.1
launcher: 2.5.0

### Logs

[client.log](https://github.com/runelite/runelite/files/14425141/client.log)
[launcher.log](https://github.com/runelite/runelite/files/14425142/launcher.log)
[jvm_crash_pid_35052.log](https://github.com/runelite/runelite/files/14425144/jvm_crash_pid_35052.log)

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/FAQ#my-loot-tracker-data-is-gone

**Comment by frerems** [comment]
> https://github.com/runelite/runelite/wiki/FAQ#my-loot-tracker-data-is-gone

i found the correct profile on the runelite page - how would i export the entire profile or just the loot tracker file into my runelite launcher?

**Comment by YvesW** [comment]
You can't. Make sure you are logged into your RL account and OSRS account, and follow the instructions in the link Alex provided.
