### ISSUE TITLE
Option on Bank Value plugin to show full bank value number instead of "stack size".

### ISSUE THREAD

**Issue by xmatias** [runelite/runelite#1754]
Add a toggle option in bank value menu so we can change between full number and current "stack size".

Currently: The Bank of RuneScape (EX: 90.2M)
uses "StackFormatter.quantityToStackSize"

Full option: The Bank of RuneScape (EX: 90,201,536)
uses "StackFormatter.formatNumber"

**Comment by Kamielvf** [comment]
I would actually prefer to just show it as "Bank of RuneScape ~ 90,201,536" and not have a toggle. :+1:

**Comment by Stickaplex** [comment]
Eh I personally like it better it better rounded off

**Comment by deathbeam** [comment]
It looks like this was already implemented
