### ISSUE TITLE
ClueScroll plugin: Instanced npcs aren't transformed correctly

### ISSUE THREAD

**Issue by Rheon-D** [runelite/runelite#1755]
Cipher clue GBJSZ RVFFO Fairy Queen npc has null values, the tagging will not work unless a transform is applied to the NpcComposition. I suspect it to have something to do with the way instanced npcs are added to the npc list in client.

**Comment by Nightfirecat** [comment]
I think this has been fixed? I've not seen tagging of Fairy Queen fail recently.

**Comment by deathbeam** [comment]
Well I guess then we can close it and reopen if the bug reappears
