### ISSUE TITLE
menu bars

### ISSUE THREAD

**Issue by OSRSSPLOOGE** [runelite/runelite#17567]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

my menu bars are split in half

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/162887717/46610c23-22fc-4c57-8282-1acbfd741817)

### RuneLite version

jagex one, so latest

**Comment by OSRSSPLOOGE** [comment]
I just want my stats and quest shit, back next to the other one, its throwing me off, ive probably dont it to myself, cheers

**Comment by YvesW** [comment]
You probably moved them yourself. Alt+right click it a bunch to reset its position.

**Comment by OSRSSPLOOGE** [comment]
> You probably moved them yourself. Alt+right click it a bunch to reset its position.

Spot on. thanks legend
