### ISSUE TITLE
MacOS: Game doesn't render at native resolution

### ISSUE THREAD

**Issue by khogeland** [runelite/runelite#17575]
### Type

GPU

### Operating System

MacOS

### OS Version

Sonoma

### Bug description

The 3D rendering does not use the native screen resolution and instead depends on your system UI scaling, resulting in a much lower quality game view than is possible. These screenshots are taken with the GPU and Stretched Mode plugins enabled.

How it should look (this is with my system resolution set to native):

![Screenshot 2024-03-13 at 1 54 55 PM](https://github.com/runelite/runelite/assets/1495099/26840c2b-8142-4a87-813d-2bcad55a83e6)

How it actually looks (with the default high-DPI system resolution):

<img width="933" alt="Screenshot 2024-03-13 at 1 55 34 PM" src="https://github.com/runelite/runelite/assets/1495099/0ea2ace9-9dfe-4106-b803-0e457d533d03">

### RuneLite version

2.6.13

**Comment by Adam-** [comment]
added in 6dcbb05a40a937cfd864cb2efbb70b3a01395803
