### ISSUE TITLE
Tree Textures are broken at Hunters' Guild

### ISSUE THREAD

**Issue by Mark7625** [runelite/runelite#17589]
### Type

GPU

### Operating System

None

### OS Version

Windows 11

### Bug description

Walk to the Hunters' Guild turn on roofs, confirmed it only does this on GPU and 117

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/72366279/f8c43c0e-1c45-4fad-aeb2-7de1349c15c5)

Expected

![image](https://github.com/runelite/runelite/assets/72366279/45abea74-e326-4e58-8a4e-1caf3f7ce185)

### RuneLite version

RL: 1.10.25
Launcher: 2.6.10

**Comment by Nightfirecat** [comment]
Known issue related to gpu hillskew, it's being tracked as part of the mega issue: https://github.com/runelite/runelite/issues/17586
