### ISSUE TITLE
Time tracking for sweetcorn off-by-1

### ISSUE THREAD

**Issue by Niaxor** [runelite/runelite#17581]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Win 10

### Bug description

At the farming guild standing within distance of allotments and I received a notification that my sweetcorn was ready to harvest. It is only at stage 6. After inspecting the crop the tooltip did not update itself to correct itself.

My theory: The plant became diseased at one point, and I used plant cure so possibly the counter messed up there? 

Alternative theory: Since inspecting didnt fix it, maybe the sweetcorn stage counter for being ready to harvest is off by 1? 

The client log has these errors which seems of interest:

2024-03-15 11:43:59 AEDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 7, previous observed offset was 26 (6) Player Loc:WorldPoint(x=1253, y=3741, plane=0)
2024-03-15 11:43:59 AEDT [Client] ERROR n.r.c.p.t.farming.FarmingTracker - Offset error! Observed new offset of 7, previous observed offset was 26 (6) Player Loc:WorldPoint(x=1253, y=3741, plane=0)

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/12996080/08628c97-e31a-4c6f-bbee-7d64fb2cc095)

### RuneLite version

1.10.24

### Logs

[client.log](https://github.com/runelite/runelite/files/14609289/client.log)
[launcher.log](https://github.com/runelite/runelite/files/14609290/launcher.log)

**Comment by JZomDev** [comment]
If you type ::resetfarmtick in chat box and then watch preferably a tree go through a growth stage it will help with this issue.

**Comment by Felanbird** [comment]
mentioned by zom above the [::resetfarmtick](https://github.com/runelite/runelite/wiki/Time-Tracking#resetfarmtick-chat-command) can be used in the few times this sort of issue happens.
