### ISSUE TITLE
Implings plugin: "Show Spawn locations" option does not work for Essence Implings

### ISSUE THREAD

**Issue by Jinxer42** [runelite/runelite#17600]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Go to poro poro and with highlight Essence implings turned on and spawn locations toggled on. The plugin appears to work for all other imlpings correctly except for Essence imps.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/25554393/453fd0a4-c9de-495a-af33-2e5902175994)

### RuneLite version

RuneLite version: 1.10.25
Launcher Version: 2.6.9

### Logs

[launcher_2024-03-20.0.log](https://github.com/runelite/runelite/files/14694577/launcher_2024-03-20.0.log)
[client_2024-03-20.0.log](https://github.com/runelite/runelite/files/14694578/client_2024-03-20.0.log)

**Comment by Adam-** [comment]
Do essence implings have spawns? The plugin seems to think they do not. If they do, and you could collect the coordinates for them, that would be helpful.

**Comment by Jinxer42** [comment]
> Do essence implings have spawns? The plugin seems to think they do not. If they do, and you could collect the coordinates for them, that would be helpful.

According to the wiki they do have set spawns (5 of them).  Some rough testing confirms this.  I tested 1 spot for 10 spawns and 7 of the 10 occurred on the exact same tile, while three occurred in tiles to the north (see image below).  This is comparable to rates i have experienced with eclectic imp spawns (although I never actually took data on those).

You will have to forgive me. But how do I get the coordinates for the tiles, so I can send them to you?

![image](https://github.com/runelite/runelite/assets/25554393/7688ab48-b8a6-42c7-ad58-3de7dba222dd)

**Comment by mario026** [comment]
Added the 5 spawn points for the essence impling

https://github.com/runelite/runelite/pull/17613

**Comment by Jinxer42** [comment]
> Added the 5 spawn points for the essence impling
> 
> #17613

Thanks much! I look forward to it.
