### ISSUE TITLE
Save F-keys config

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1761]
It would be nice that if I were on a new computer and I would login to Runelite, it would load my saved F-keys configuration, like in this panel:
![image](https://user-images.githubusercontent.com/9074448/39085450-aa63500e-4582-11e8-9024-e2a2b5ceea6e.png)

**Comment by sethtroll** [comment]
RS doesn't already save this?

**Comment by TheArbalist** [comment]
It does, from what I've seen.

**Comment by Gamer1120** [comment]
Oh, really? Lemme check that.

**Comment by Gamer1120** [comment]
Can confirm it does that. Will close this issue.
