### ISSUE TITLE
Keris Partisan Not Working With Attack Styles Plugin

### ISSUE THREAD

**Issue by githubbingitup** [runelite/runelite#17623]
### Type

Incorrect behavior

### OS Version

win10

### Bug description

Equipping a non-upgraded Keris Partisan with the Attack Styles plugin enabled does not work. It shows all the regular attack styles.
This weapon is also bugged with attack styles on HDOS client as well, so I think the game update messed with the Keris.

### RuneLite version

RL: 1.10.25.2
L: 2.6.7

**Comment by Nightfirecat** [comment]
Sorry, what does "It shows all the regular attack styles" mean? Like, unarmed attack styles?

**Comment by ExamineText** [comment]
> Sorry, what does "It shows all the regular attack styles" mean? Like, unarmed attack styles?

He means it shows the attack style of the last weapon you have equipped. It's because the equipped weapon type varbit returns 30 for the keris partisan when the enum only goes from 0-29.

**Comment by Repcal** [comment]
type 22 is now the new blue moon spear.

**Comment by githubbingitup** [comment]
> Sorry, what does "It shows all the regular attack styles" mean? Like, unarmed attack styles?

I mean it doesn't work. The attack styles plugin does not work with the Keris Partisan...

**Comment by Felanbird** [comment]
> > Sorry, what does "It shows all the regular attack styles" mean? Like, unarmed attack styles?
> 
> I mean it doesn't work. The attack styles plugin does not work with the Keris Partisan...

In the time since that question was asked, we were able to confirm it being a bug on Jagex's side :+1:

**Comment by githubbingitup** [comment]
Oh i see, thank you for explaining. hope they fix soon

**Comment by Felanbird** [comment]
This was fixed with 52d091d4b6e49d92208a295616df0138ab18b6b6
