### ISSUE TITLE
RuneLite doesn't cover half my screen when I drag it all the way to the edge

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1762]
When I put my mouse cursor on the left or right edge of my screen, almost every other program fills half my screen. RuneLite doesn't do that. Mouse cursor is at the arrow in the picture:
![image](https://user-images.githubusercontent.com/9074448/39085486-3db1cdea-4583-11e8-9a5a-558da9d090b7.png)

**Comment by Adam-** [comment]
This is due to the custom chrome. If you disable it, it will do that. I do not know if its possible to make swing do it with the custom LaF or not.

**Comment by Gamer1120** [comment]
This fixed it for me, thanks!
