### ISSUE TITLE
Add a loot tracker for bosses

### ISSUE THREAD

**Issue by WSylv** [runelite/runelite#1763]
It would be extremely convenient to have some sort of menu or overlay that keeps track of the drops you get at certain bosses with, for example, members of your cc. This would, by nature, also support soloing the boss. It could keep a list of the items received, their price, who actually got the drop, and maybe what the current price of the split will be for each person.

**Comment by Infinitay** [comment]
I believe Woox is working on this

**Comment by deathbeam** [comment]
We implemented loot tracker so looks like this is non-issue anymore. For loot split tracking we already have issue open
