### ISSUE TITLE
Farming contract unknown

### ISSUE THREAD

**Issue by JamesJJT** [runelite/runelite#17635]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

The farming contract overlay is not showing, also, the farming tab, just shows "Contract Unknown"
This worked before todays update. 

Tried:
- Re-checking contract with Guildmaster Jane
- Logging in an out
- Completing task, getting a new one (Still not showing).
![image](https://github.com/runelite/runelite/assets/38963376/f5ef4620-a75a-417e-95a9-97ba86d30a18)

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/38963376/a2a083fb-8104-40f6-b10d-f30da110428e)

### RuneLite version

Runelite version : 1.10.26
Launcher Version: 2.6.9

**Comment by JamesJJT** [comment]
> Has the dialog changed for getting a farming contract? What does Guildmaster Jane say when a contract is assigned?

![image](https://github.com/runelite/runelite/assets/38963376/e7745526-cdbb-41e7-8178-81dfe1044017)
![image](https://github.com/runelite/runelite/assets/38963376/2577ce08-c68c-459d-a9f1-39892810b2eb)

**Comment by JamesJJT** [comment]
That above screenshot is checking the current assigned contract

**Comment by loloias** [comment]
I experience the same issue

**Comment by JamesJJT** [comment]
> I experience the same issue

Its being fixed https://github.com/runelite/runelite/pull/17636

**Comment by CashLibre** [comment]
This happened to me yesterday - farming contract now just shows "Unknown" regardless of what I do -new contract, ask Guildmaster Jane again about contract, complete the contract and get a new one, log out and in, reboot, disable then enable plugin, reset the plugin - nothing fixes it - so I guess it's some variable/flag somewhere in the code that's got stuck?
Any hints/ideas would be appreciated, thank you.

**Comment by cdfisher** [comment]
> This happened to me yesterday - farming contract now just shows "Unknown" regardless of what I do -new contract, ask Guildmaster Jane again about contract, complete the contract and get a new one, log out and in, reboot, disable then enable plugin, reset the plugin - nothing fixes it - so I guess it's some variable/flag somewhere in the code that's got stuck? Any hints/ideas would be appreciated, thank you.

As mentioned above, this is a known issue which will be fixed in the next release

**Comment by JamesJJT** [comment]
> This happened to me yesterday - farming contract now just shows "Unknown" regardless of what I do -new contract, ask Guildmaster Jane again about contract, complete the contract and get a new one, log out and in, reboot, disable then enable plugin, reset the plugin - nothing fixes it - so I guess it's some variable/flag somewhere in the code that's got stuck? Any hints/ideas would be appreciated, thank you.

This issue was fixed by #17636 .

If you've got a new issue with it, probably best to open a new issue.

**Comment by cdfisher** [comment]
> > This happened to me yesterday - farming contract now just shows "Unknown" regardless of what I do -new contract, ask Guildmaster Jane again about contract, complete the contract and get a new one, log out and in, reboot, disable then enable plugin, reset the plugin - nothing fixes it - so I guess it's some variable/flag somewhere in the code that's got stuck? Any hints/ideas would be appreciated, thank you.
> 
> This issue was fixed by #17636 .
> 
> If you've got a new issue with it, probably best to open a new issue.

They don't need to open a new issue, there's already #18260 (and several duplicates) which they missed and found this instead. It's fixed by 3b56b9f3dc489356b0028761013ef8d285bb7bd3 so will be resolved in the next release.
