### ISSUE TITLE
Cant change Style or color of tagged NPCs

### ISSUE THREAD

**Issue by KGruson** [runelite/runelite#17646]
### Type

Incorrect behavior

### Operating System

None

### OS Version

Windows 10

### Bug description

After the Varlamore Update i wasnt able to change either the color nor the Style of a tagged NPC or object via the right-click menu

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/89548146/314e3462-072a-410d-869c-b4082549b1aa)

### RuneLite version

RuneLite Version: 1.10.26
Launcher Version: 2.6.10

### Logs

[client.log](https://github.com/runelite/runelite/files/14796152/client.log)
[launcher.log](https://github.com/runelite/runelite/files/14796153/launcher.log)

**Comment by Felanbird** [comment]
![image](https://github.com/runelite/runelite/assets/41973452/80e18072-25f4-451f-95d0-1a03761016ed)

You have 158 hub plugins, one of them is highly likely 	causing this issue

**Comment by KGruson** [comment]
Found the conflicting Plugin, it was "Better Context Menu"
