### ISSUE TITLE
Show monsters aggro area

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#1765]
Show monsters' aggro area, (Show the area of which you can not step out of, or the monsters become aggro again.)

**Comment by eggbrow** [comment]
Yes this is something I wanted to ask also. It's interesting how some monsters have very different aggro area/attack range/aggro range inside that area.

**Comment by Popedigoz** [comment]
Can be closed, as this is now in the "game". (NPC Aggression Timer -plugin)

**Comment by Nightfirecat** [comment]
You should be able to close this issue yourself. But yes, this has been implemented.
