### ISSUE TITLE
Ground items plugin stacking arrows bug

### ISSUE THREAD

**Issue by Mikac91** [runelite/runelite#17669]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I have set the minimum value GE/HA of items to show set to 100 coins. This was done in order to reduce screen clutter while training ranged and show me only piles of arrows and not single arrows. It worked perfectly a month ago, I would shoot arrows and after they pile up it would show me the 5+ pile to pick up while ignoring single ones.

In the last month something was updated and now it seems that the plugin does not add arrow value as they pile up. 
It can go up and above 10+ arrows with value 500+ coins and still not show them. 
If I drop the same amount from my inventory (lets say 10) it does show the pile but will not register if they stack up 1 by 1. 
It will show the stacked pile if I turn off the plugin and turn it on again, or change any of the settings inside the plugin.

I have tried Safe Mode and updating the RL launcher, it did not help.

### RuneLite version

RL version: 1.10.26.1
Launcher version: 2.7.1

**Comment by YvesW** [comment]
Disable ``Show loot only`` in the ground items plugin. The client does not know that these are your arrows.

**Comment by Mikac91** [comment]
> Disable `Show loot only` in the ground items plugin. The client does not know that these are your arrows specifically.

It is disabled. Same settings that I have now worked a month ago, nothing is changed.

**Comment by Adam-** [comment]
fixed in f8024bfd15a3d83ef9e7542df3c6d8e29163cdfd
