### ISSUE TITLE
Medium clue bugs - 2 medium clues 

### ISSUE THREAD

**Issue by mtarik550** [runelite/runelite#1769]
1. Medium cluescroll (pointer) - https://i.imgur.com/WaWaQB7.png The issue with this is that the marker shown on the minimap and ingame are incorrect! https://i.imgur.com/WMLX6V6.png the correct marker should be inside McGrubor's Wood, west of Seers' Village.

2. Medium cluescroll (everything) - Nothing has been added for the following medium cluescroll "Cry on top of the western tree in the Gnome Agility Arena. Indicate 'no' before you talk to me. Equip a steel kiteshield, ring of forging, and green d'hide chaps." and what I mean by this is that here is nothing shown on the cluescroll plugin no (emote highlights, items needed etc) 

Please fix! :)

**Comment by mtarik550** [comment]
I just realized the marker on the map and ingame changes to the closest clue scroll location even if its not related to your cluescroll, this could be misleading to most people.

**Comment by devLotto** [comment]
2. was fixed by #1779

**Comment by Nightfirecat** [comment]
And (1) was fixed in b8737de5029ad5563115879b3730dffb16536cf3. @deathbeam, got one more for you to close. :heart:
