### ISSUE TITLE
Compass Button Snap to/between Cardinal Directions

### ISSUE THREAD

**Issue by xHous** [runelite/runelite#1770]
Add more options to right clicking the compass, such as Look East, Look South and Look West.

**Comment by devLotto** [comment]
I don't know if this maybe can be seen as automation/macroing from Jagex side

**Comment by Popedigoz** [comment]
Add S, W & E letters to the compass as it only shows N

**Comment by ShaunDreclin** [comment]
@Popedigoz #5019 😃

**Comment by Adam-** [comment]
added in da0f507ffbb9d57332a82fe25e6266fb4ecd3e13
