### ISSUE TITLE
Logs folder filled with error

### ISSUE THREAD

**Issue by joujoucoons** [runelite/runelite#17725]
### Type

Incorrect behavior

### Operating System

None

### OS Version

windows 11

### Bug description

my logs folder is getting filled with error "2024-04-13 12:37:28 EEST [Client] ERROR com.monsterhp.MonsterHPOverlay - there was an error:java.lang.NullPointerException" it takes 10-20 gb of space after week of clearing

### RuneLite version

RL: 1.10.26.4
Launcher: 2.6.4
OSRS: Rev 221

### Logs

[launcher.log](https://github.com/runelite/runelite/files/14967270/launcher.log)
[client.log](https://github.com/runelite/runelite/files/14967283/client.log)

**Comment by Alexsuperfly** [comment]
This is a hub plugin, we don't maintain it.  If you don't like how it behaves you should uninstall it, and or raise an issue with its maintainer.
