### ISSUE TITLE
Runelite command/highscore kc bug

### ISSUE THREAD

**Issue by Gekkie026** [runelite/runelite#17721]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

11

### Bug description

When I type !kc lunar chest, it shows that I have less kc than on the highscores, this is the problem for almost 1 week. 

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/166821900/cb0045ec-6e76-4845-ac06-39cd71ccfc42)
![Uploading image.jpg…]()

### RuneLite version

Newest

**Comment by Gekkie026** [comment]
![image](https://github.com/runelite/runelite/assets/166821900/88917f59-37f9-4a7e-ab25-a7414c7547a9)

**Comment by cdfisher** [comment]
Go do one more KC or use a ring of wealth to check the boss log.

**Comment by Nightfirecat** [comment]
Did you open 2 chests on a non-RuneLite client, such as on mobile? `!kc` only updates based on seeing your kc change, it doesn't fetch from the hiscores.

**Comment by Gekkie026** [comment]
> Did you open 2 chests on a non-RuneLite client, such as on mobile? `!kc` only updates based on seeing your kc change, it doesn't fetch from the hiscores.

Yes i did some kills on mobile. But that was more than only 2 kills.

**Comment by cdfisher** [comment]
> But that was more than only 2 kills.

It's not that it only *counts* kills done on RuneLite, just that it can only update the count when you do a kill on RuneLite. So like I said, if you go do one more kc on RuneLite it should be accurate again for you.

**Comment by Gekkie026** [comment]
> > But that was more than only 2 kills.
> 
> It's not that it only _counts_ kills done on RuneLite, just that it can only update the count when you do a kill on RuneLite. So like I said, if you go do one more kc on RuneLite it should be accurate again for you.

Ah I understand now, the last time I did some kills were on mobile so that should be it! Thanks!
