### ISSUE TITLE
Quest List not appearing in side menu

### ISSUE THREAD

**Issue by BrazyDevelopment** [runelite/runelite#17730]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Quest List plugin is not showing the sidepanel button and thus unable to open it.
I have tested this on multiple environments including windows server 2019 and windows 10.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/126255356/d5b9e819-4e53-42b6-a4a3-29dcdf41bb44)

### RuneLite version

latest

**Comment by cdfisher** [comment]
Quest List doesn't have a side panel or config options. It's either on or off. See [here](https://github.com/runelite/runelite/wiki/Quest-List).

**Comment by DapperMickie** [comment]
That's how the plugin works, if it's turned on, it adds search and filter for the quest list (in the game). If turned off, the buttons don't show up. The plugin doesn't have a side panel or config options.

**Comment by BrazyDevelopment** [comment]
Oh, which plugin is the one with the sidepanel then?

**Comment by cdfisher** [comment]
> Oh, which plugin is the one with the sidepanel then? Quest Helper?

You're probably thinking of "Quest Helper" on the plugin hub.

**Comment by BrazyDevelopment** [comment]
> > Oh, which plugin is the one with the sidepanel then? Quest Helper?
> 
> You're probably thinking of "Quest Helper" on the plugin hub.

Thanks!
