### ISSUE TITLE
[Menu Entry Swapper] Cannot use Teleport swap on some items with 'Teleport submenus' enabled

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#17745]
### Type

Incorrect behavior

### Operating System

Linux

### Bug description

With Teleport submenus enabled in the Menu Entry Swapper settings, setting the left-click option to Teleport on an item with teleport submenus will instead swap that option to Wear. Swapping its shift-click option to Teleport will swap it correctly to Teleport, but shift-clicking it doesn't actually open the teleport menu.
I would like to be able to shift-click my diary cape to teleport to Jarr, while still able to left-click it to open the teleport menu as I have the shortcut keys memorized.

### RuneLite version

RuneLite version: 1.10.27
Launcher version: 2.6.10

**Comment by Adam-** [comment]
fixed in 248aabf1eb9214b874f7a3452b47e6fce3c05024
