### ISSUE TITLE
ge: cme on price lookup

### ISSUE THREAD

**Issue by Macweese** [runelite/runelite#17763]
### Type

Other

### Operating System

Windows

### OS Version

10.0.19045.4291

### Bug description

Found ConcurrentModificationException occurance in logs, happens when looking up the prices (hotkey searching items e.g. in inventory "Search Grand Exchange foo"). I had trouble getting it to occur consistently but seemed to happen from searching in rapid succession.

### RuneLite version

RuneLite v1.10.27.2
Launcher v2.7.1
OSRS Rev 221

### Logs

[client.log](https://github.com/runelite/runelite/files/15042132/client.log)

**Comment by Adam-** [comment]
fixed in 1a2913141c25290cd6b28d06f93fa7ede2c26e10
