### ISSUE TITLE
Key Remapping conflicts with the report button update

### ISSUE THREAD

**Issue by Felanbird** [runelite/runelite#17789]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

Yesterdays update changed the report UI and because of this the Key Remapping plugin no longer recognizes it, and because of this it's not possible to type the letters that have been remapped, into the report UI. (e.g. wasd)

1. Enable the `Key Remapping` plugin
2. Enabled the `Remap Camera` setting
3. Click the `report abuse` button
4. Attempt to type w, a, s, or d into the input box, see the camera move instead.

### RuneLite version

RuneLite version: 1.10.28

**Comment by Adam-** [comment]
fixed in be446bddb0371febbaa16e85333bdcacb397feb1
