### ISSUE TITLE
[Skill Calculator / Firemaking] Shade firemaking bonus and creating pyre logs are missing

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#17780]
### Discussed in https://github.com/runelite/runelite/discussions/17770

<div type='discussions-op-text'>

<sup>Originally posted by **Pirocchio** April 20, 2024</sup>
I was cremating urium remains earlier today, and noticed that the calculator is missing the cremation process from Firemaking (although it is present in regards to prayer), with the respective toggle from Morytania elite diary 50% bonus xp. 

Also, "making pyre logs (1 dose)" should be there as well, since each dose of sacred oil gives fixed 4 xp.</div>

**Comment by Nightfirecat** [comment]
I'd make 3 actions (one for each possible dose application amount), and use the associated sacred oil items as their icons.

**Comment by Nightfirecat** [comment]
As for burning, yes, one action per log should be fine.

**Comment by DapperMickie** [comment]
FYI there's a small mistake on the wiki, for arctic pine it shows up as 12 xp when using a 2 dose, but I tested it and it's only 10xp.

**Comment by Pirocchio** [comment]
@Nightfirecat @evilgenious448 Ty for implementing this!

Now, there is a typo. The redwood pyre logs aren't distinguished :)

![image](https://github.com/runelite/runelite/assets/149321895/c293b5ea-f5c1-4da9-8860-be537708e36e)

**Comment by Nightfirecat** [comment]
This enhancement was added in the commits linked from #17781. The redwood pyre logs name is fixed in #17964.
