### ISSUE TITLE
Menu Entry Swapper doesn't work with Dizana's Quiver ammo slot

### ISSUE THREAD

**Issue by fuhsaz** [runelite/runelite#17803]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

When I shift-right click the special ammo slot provided by wearing a Dizana's Quiver, I'm unable to change the default left- and shift-click behavior for it. I'd like to be able to set one to "Swap" and one to "Quick-Remove". 

### Screenshots or videos

(This was the menu I got when shift-clicking)
![image](https://github.com/runelite/runelite/assets/15990644/8ef31ccf-3148-449a-bfca-f3e85f7529f3)

### RuneLite version

RL Version: 1.10.28.1
Launcher Version: 2.6.10

**Comment by Mr-Sisyphus** [comment]
Still an issue in June please runelite game is literally unplayable I have to right click "swap" when using a crossbow

**Comment by cdfisher** [comment]
There's a PR open to add this, #17659

**Comment by DrYoshiyahu** [comment]
Until this is resolved, Custom Menu Swaps does work. You can add `Swap,*` as a custom swap at the very least.

**Comment by Felanbird** [comment]
Added in 8fc859df97b76c125a2bb73fecf5ba0e94cd1a69
