### ISSUE TITLE
custom swaps work inconsistently close to shift press or release 

### ISSUE THREAD

**Issue by Orimazer** [runelite/runelite#17807]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 10

### Bug description

close to holding or releasing the shift key, menu swapped items sometimes have the incorrect option, as seen in the video. this was something i had seen before, but it hadn't lead to incorrect inputs, but it has become massively more pronounced since the update that allowed the con/max/achivo cape's options to be swapped to.
i have clean snapdragons as "use" for both regular and shift click (but have shift click drop as default behaviour in game settings) as i almost never want to drop them, but have grimy snaps as regular click as "use" and shift click as "clean"*, so grimy or not no default option should be drop for a snapdragon. now if i release shift (from cleaning a grimy herb), there's a brief window where the left click option is "drop". prior to the update, i have never had the swap mess up and drop a herb, but it is now a regular occurrence on my runs to drop a clean herb between patches.
similarly i have my con cape as regular click "Tele to PoH", shift as "teleport" to bring up the scroll menu. when i press and hold shift there's a brief window where it goes from "teleport" to "wear" before returning to teleport.

* (doesn't make the most sense, i know, but it's what i've done for years now, so its inertia at this point keeping it this way)

### Screenshots or videos

in this video shift is the only key i press or release 
https://github.com/runelite/runelite/assets/16553650/1cd4f159-3183-4d2d-8485-fc50cb0019a0

### RuneLite version

RuneLite version: 1.10.28.1
Launcer version: 2.6.7

### Logs

[client.log](https://github.com/runelite/runelite/files/15173218/client.log)
[launcher.log](https://github.com/runelite/runelite/files/15173221/launcher.log)

**Comment by Adam-** [comment]
Are you talking about the "custom menu swaps" plugin, or the "menu entry swapper" plugin?

**Comment by geheur** [comment]
So, what appears to happen is there is a short period after pressing shift where the left-click swap is disabled but the shift-click swap has not yet activated.

This can be replicated by setting the left-click option on a simple item such as a fire rune to "drop". Mouse over the fire rune and observe that when you press shift, it will show "use" for a very short period of time in the top left of the screen. It is possible to click when it says "use".

**Comment by Orimazer** [comment]
> Are you talking about the "custom menu swaps" plugin, or the "menu entry swapper" plugin?

sorry for the ambiguity, the base menu entry swapper plugin

**Comment by Adam-** [comment]
fixed in a95a26f01ffb86ecc7ab8b5bb4146f55e68babfd. The Jagex client has a 1 tick delay from when the shift key is changed to when the menu is updated, which was causing this.
