### ISSUE TITLE
Item Charges update required - Tome of Fire

### ISSUE THREAD

**Issue by IsaacGraham** [runelite/runelite#17806]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

I tried to update my tome of fire's charges overlay from the Item Charges plugin.
They recently (24/04/2024) changed the text to specify whether it is charged with Burnt or Searing pages.
Presumably this broke the functionality of using the Check function ingame to update the plugin's info.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/5593732/c95addda-7913-4c74-bd56-be729e858c60)

### RuneLite version

RL: 1.10.28.1
Launcher: 2.6.7

**Comment by geheur** [comment]
I don't think that's a vanilla runelite plugin. are you using https://github.com/geheur/weapon-charges?

**Comment by Nightfirecat** [comment]
The Item Charges plugin does not support the Tome of Fire at all, are you using a hub plugin to show those charges? If so, please report this bug to the author, not to us.

**Comment by IsaacGraham** [comment]
oh. Yes. my mistake. Disregard!
