### ISSUE TITLE
Quest Helper plugin bug - Kourend Medium Achievement Diary

### ISSUE THREAD

**Issue by Jmullane96** [runelite/runelite#17817]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

macOS Sonoma 14.4.1

### Bug description

When using Quest Helper, via plugin tab or right clicking on achievement diary and selecting start quest helper, the Kourend & Kebos Medium Diary quest helper will not open. When you click it to start, you won't be able to switch rune lite tabs until you try to then open a different quest/diary

### RuneLite version

RL: 1.10.28.1
Launcher: 2.6.8

**Comment by Felanbird** [comment]
![image](https://github.com/runelite/runelite/assets/41973452/3648d07e-c5e7-431c-bfad-621a1d9280e9)

Support for hub plugins should be directed to the author of the plugin. You can find the support link by searching for the plugin in the Plugin Hub panel and clicking the ? button on the plugin, or by right-clicking the plugin in the plugin panel and clicking the Support menu option. https://github.com/Zoinkwiz/quest-helper/issues/1534
