### ISSUE TITLE
Boss Timer for Crazy Archaeologist

### ISSUE THREAD

**Issue by lexigorse** [runelite/runelite#17816]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

It looks like the boss timer for Crazy Arch might have also been updated with some of the wildy rework changes. I see him respawn and my current timer shows there's still 20 seconds remaining. ~~I don't know exactly how long , but I was planning to hop after 10 second combat cooldown and he had respawned before I could.~~ Seems like it's about 9 seconds just by tracking the current boss timer to when he respawns.

### RuneLite version

Runelite version: 1.10.28.1
Launcher version: 2.6.10

**Comment by Filip-Joh** [comment]
Created a [pull request](https://github.com/runelite/runelite/pull/17824) to update this. Tested in-game to verify 9 second respawn. Also updated osrs wiki respawn timer from its incorrect 9 ticks to 15 ticks.

**Comment by lexigorse** [comment]
closing this since I can see the updated timer now in RL. Thank you!
