### ISSUE TITLE
Barrows - Loot Reward % 

### ISSUE THREAD

**Issue by Ampl-T** [runelite/runelite#1782]
This would be a pretty handy feature as sometimes I forget how many skeles I've killed.

Cheers

**Comment by deathbeam** [comment]
Isn't this already vanilla feature?

**Comment by Ampl-T** [comment]
Yea just checked, you're exactly right it is, I wasn't able to see it as my where it's hidden under my inventory in my game client as I have it pretty small and use resizeable
