### ISSUE TITLE
Preserve Prayer hidden when reordering is disabled

### ISSUE THREAD

**Issue by iBayouu** [runelite/runelite#17836]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Upon **disabling** prayer reordering, the preserve prayer goes hidden, it only reappears when I **enable** prayer reordering. 

### Screenshots or videos

https://imgur.com/EY7yWCt - Preserve hidden

https://imgur.com/gk8dyz8 - Preserve appears

### RuneLite version

Runelite Version: 1.10.29

Launcher Version: 2.7.1

**Comment by Felanbird** [comment]
Right-click preserve while re-ordering is enabled and click this 
![image](https://github.com/runelite/runelite/assets/41973452/2fe656e9-0442-4ef2-b0ac-c077fa214039)

**Comment by iBayouu** [comment]
I didn't even know that was a thing lol, thanks
