### ISSUE TITLE
Lunar chest screenshots

### ISSUE THREAD

**Issue by woahitisme** [runelite/runelite#17839]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 11

### Bug description

The screenshot plugin does not recognize a regular moons of peril kc/ Lunar chest opening as something to screenshot. unless there is a collection log pop up. There is no file after multiple openings of lunar chests.

### RuneLite version

1.10.28.1
2.7.1

**Comment by DapperMickie** [comment]
Can you send a screenshot of your settings for the screenshot plugin?

**Comment by woahitisme** [comment]
![Screenshot 2024-05-14 025940](https://github.com/runelite/runelite/assets/169689298/9c2eb837-307d-4726-ae12-54f1c04e5f16)
