### ISSUE TITLE
Add Skilling Calculator

### ISSUE THREAD

**Issue by gunit1234** [runelite/runelite#1784]
please add a calculator

**Comment by Infinitay** [comment]
No disrespect, but you can't open up the calculator your OS provides you? :p

**Comment by thestdman** [comment]
a calculator itself isn't too useful in my opinion but the multiple calculators for each skill would be something i'd enjoy. It is the one feature i miss from osbuddy, but I dont expect anyone to code a full set of them though. Would just be much more handy

**Comment by Kruithne** [comment]
@thestdman Waiting for approval on https://github.com/runelite/runelite/pull/947

**Comment by Adam-** [comment]
Added in #947
