### ISSUE TITLE
World Hopper attempts to hop into World 400 "Beta Testing" - Cannot log in, boots to login

### ISSUE THREAD

**Issue by wizzyhatg** [runelite/runelite#17849]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

The World Hopper ctrl+shift+left/right hop functionality attempts to hop to world 400, which is a beta world I/ I don't think anybody else has access to. This results in a kick to the login screen. Please add a filter to the World Type Filter in World Hopper plugin for Beta World

### RuneLite version

Runelite 1.10.30 Launcher 2.6.7

**Comment by Adam-** [comment]
This is actually a non-beta world that is labelled as a beta world. Normally we do skip over beta worlds (and color them blue). I will see what I can do about it.

**Comment by Adam-** [comment]
fixed in 8b8abb42bd4c139cd7e8627597719c20a0169a9c / d5dc55cfce491ae046dfa0c2947d644f87583851
