### ISSUE TITLE
Key Remapping Bug

### ISSUE THREAD

**Issue by imjustrengar** [runelite/runelite#17847]
### Type

Other

### Operating System

Windows

### OS Version

Win 11

### Bug description

Using key remapping plugin will make you press enter before you can type. Yet any key that is not being currently used as a remapped key will continue to type in game. This causes a message to send the next time you go to press enter to type a new message causing unwanted messages consisting of gibberish to be sent.

To recreate this bug:
1) Enable key remapping
2) Test that WSAD will move the camera and that you are being prompted to press enter to chat in the textbox
3) While it still says "press enter to chat" attempt to use keys that don't have an active remap on them (eg. H. K, U, L, etc)
4) After using those keys, press enter so you are able to send a chat message
5) you will see that it will send a message with the random key presses in there at the same time it allows you to begin typing a message

As you will see in my example video any key not bound to something will type regardless of the "press enter to chat" prompt.

### Screenshots or videos

https://github.com/runelite/runelite/assets/169007217/3e9cf1fa-e360-4469-8aa5-a15efc1889e8

### RuneLite version

RL: 1.10.29
Launcher 2.7.1

**Comment by geheur** [comment]
restart your client, you are on an old version.
