### ISSUE TITLE
Customizable xp drop plugin not working

### ISSUE THREAD

**Issue by NAMEnotlmportant** [runelite/runelite#17845]
### Type

Crash or hang

### Operating System

Windows

### OS Version

 Windows 11

### Bug description

Everything with this plugin was working perfectly fine but all of a sudden today it stopped showing predicted hits on opponent, not sure why as I havent changed anything at all. I tried turning it off and back on, same with the setting for predicted hit but nothing working,. 

### RuneLite version

Runelite version 2.7.1 
Launcher Version 0.33.0.0

**Comment by Felanbird** [comment]
![image](https://github.com/runelite/runelite/assets/41973452/3648d07e-c5e7-431c-bfad-621a1d9280e9)

Support for hub plugins should be directed to the author of the plugin. You can find the support link by searching for the plugin in the Plugin Hub panel and clicking the ? button on the plugin, or by right-clicking the plugin in the plugin panel and clicking the Support menu option.
