### ISSUE TITLE
Infobox grouping

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#1785]
Since you can't move our infoboxes separately, you are forced to have your boost icons, prayer icons, chest icon, and so on in the same place. I don't think most players like this since they, by the looks of it, place their non-combat icon by the chat, but boosts in the top left corner.
This could be fixed by making icon groups, such as combat, potion, non-combat, or by allowing contributors to create custom icon groups.

Dupe of comment from #1722

**Comment by deathbeam** [comment]
Maybe each plugin should have it's own movable part of the infoboxes, that would be cleanest solution and easy to implement, I think.

**Comment by Hydrox6** [comment]
Closed by #12550
