### ISSUE TITLE
Charged/degradable items don't show GE value

### ISSUE THREAD

**Issue by sil3xz** [runelite/runelite#17868]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Some charged/degradable items do not have a GE value and do not contribute to total bank value when charged/degraded. Examples:
- Tonalztics of ralos
- Blazing blowpipe
- Ring of the elements
- Blue moon helm/chestplate/tassets

This is inconsistent with other items, such as:
- Toxic blowpipe
- Sanguinesti staff
- Barrows gear/crystal armour

Although these are not tradable when charged, their GE value does show up when hovering over them and total bank value.

### Screenshots or videos

![2024-05-20_23-03-35](https://github.com/runelite/runelite/assets/98672380/cd97ab90-b889-4eb1-8d54-e61c891eaa54)

### RuneLite version

RuneLite version: 1.10.30
Launcher version: 2.6.7

**Comment by Felanbird** [comment]
The inconsistency comes from the fact that previously people PR'd the links to the respective sell-able item, nobody has done that for these new items.

e.g. https://togithub.com/runelite/runelite/pull/16394
