### ISSUE TITLE
Mini Map Display

### ISSUE THREAD

**Issue by Exobocci** [runelite/runelite#17877]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

As you walk around the map, the location of the map does not move. However the icons for shops and such do move with the player. Trying to walk via the map will cause and inaccurate movement.

### Screenshots or videos

https://github.com/runelite/runelite/assets/170644658/84578ee2-17c9-4168-ae0b-ca5c42e383e9

### RuneLite version

RuneLite Version:1.10.31
Launcher Version: 2.7.1

### Logs

[launcher.log](https://github.com/runelite/runelite/files/15418519/launcher.log)
[client.log](https://github.com/runelite/runelite/files/15418521/client.log)

**Comment by Exobocci** [comment]
Just noticed, it seems to be worse as you zoom out on the mini map
https://github.com/runelite/runelite/assets/170644658/1e2c4650-b697-4fd2-b25d-b12fe2422dd5

**Comment by abextm** [comment]
The fix for this will be in the next release.
