### ISSUE TITLE
GPU Performance sluggish on Linux

### ISSUE THREAD

**Issue by tylerbalaskovitz** [runelite/runelite#17875]
### Type

GPU

### Operating System

Linux

### OS Version

Arch Linux 6.6.31-1-lts 

### Bug description

Recently launching the program with the GPU plugin enabled has dropped performance from 60FPS to 6 to 8FPS with the GPU plugin turned on. Graphics card is a dedicated RTX 3060 (Desktop), Ryzen 3700x, 16GB RAM. I have reinstalled nvidia and nvidia-utils. Currently using bolt-launcher to launch runelite. 

### RuneLite version

RuneLite: 1.10.30
Launcher: 2.7.1

**Comment by YvesW** [comment]
Attach your logs so we can see if it's even using the correct GPU. Very likely a GPU driver issue anyway.
Also test your performance in a new profile with only gpu active and a restart (no hub plugins installed or ever active in the current session). Additionally, some people have commented that they need to restart their system after driver changes, even if they are on Linux.

**Comment by tylerbalaskovitz** [comment]
Yeah, that's correct, I tried removing drivers such as nvidia, nvidia-utils, nvidia-settings, nvidia-lts and reinstalling. I'll look for the logs, but it looks like bolt installs runelite in a separate location than $HOME/.runelite/logs. Will post when found.

**Comment by tylerbalaskovitz** [comment]
[client.log](https://github.com/runelite/runelite/files/15397272/client.log)

**Comment by tylerbalaskovitz** [comment]
[launcher.log](https://github.com/runelite/runelite/files/15397286/launcher.log)

**Comment by Felanbird** [comment]
`2024-05-21 20:53:06 EDT [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: llvmpipe (LLVM 17.0.6, 256 bits)`

llvmpipe is the fallback for when your GPU doesn't work, so this is clearly a GPU issue

**Comment by tylerbalaskovitz** [comment]
Yeah, you're correct. So, KMS was in the hooks, and had to be removed / rebuilt for graphics since nouveau was causing. Issues. Thanks.

**Comment by tylerbalaskovitz** [comment]
System configuration with KMS in hooks on arch linux can cause sluggish performance due to conflicting drivers being ran nouveau v. nvidia
