### ISSUE TITLE
XP Tracker not displaying kills to level for Sourhogs

### ISSUE THREAD

**Issue by Astraea0** [runelite/runelite#17893]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

The XP Tracker plugin is not displaying the number of kills to the next combat skill level when killing Sourhogs. It appears that the entry for Sourhogs in [npcs.json](https://github.com/runelite/static.runelite.net/blob/gh-pages/npcs/npcs.json) references the ID of the quest variant of the monster rather than the ID of the standard Sourhog encountered in the cave once Porcine of Interest is completed.

The file has the monster ID `10436` which the OSRS Wiki shows belonging to the [quest variant](https://oldschool.runescape.wiki/w/Sourhog_(A_Porcine_of_Interest)). The correct ID should be `10435` which belongs to the standard [Sourhog](https://oldschool.runescape.wiki/w/Sourhog).

### Screenshots or videos

Here is a screenshot of the XP Tracker plugin behavior while fighting Sourhogs after killing a few. Note that it says "Actions:" and has a very high number seemingly based on XP drops. It should show "Kills:" and then a fairly accurate estimate of how many left to level that skill (~1,711 in my case for Strength).

![image](https://github.com/runelite/runelite/assets/36280738/df60f81b-261a-4088-8962-0ef1ed6d615c)

Additionally, here is a standard Sourhog in-game identified with the Identificator plugin to confirm that it is ID `10435`.
![image](https://github.com/runelite/runelite/assets/36280738/1543f78b-4a0d-4555-9712-9e9d94bbc787)

### RuneLite version

RuneLite version: 1.10.31.2
Launcher version: 2.6.10

**Comment by abextm** [comment]
Fixed in https://github.com/runelite/runelite-wiki-scraper/commit/cf4b6238a3e5f9a69ee1bddb5c3440faa3851355
