### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by peperune** [runelite/runelite#17901]
### Type

Crash or hang

### Operating System

Windows

### OS Version

11

### Bug description

I can't log into my account on runelite, I've already done all the necessary steps and linked my account to the new system but it says that the account doesn't exist...

### RuneLite version

runelite 1.10.31.2 launcher 2.7.1

### Logs

error ao logar

**Comment by Nightfirecat** [comment]
RuneLite does not affect your ability to log in; perhaps, as Alex said, you're not using the Jagex launcher when you should be. Regardless, this is not a client issue, and I recommend seeking help in [our Discord server's](https://runelite.net/discord) support channel.
