### ISSUE TITLE
Exp Tracker tracking all xp from creation of account as new leading to massive xp gained and per hour values on every client restart.

### ISSUE THREAD

**Issue by SHvalross** [runelite/runelite#17910]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

This happens on every first log in of the day for me running RuneLite version 1.10.31.2, Oldschool version Rev 222, and Launcher version 2.6.4. I used attack as an example in the screenshots to show that the tracker is just taking all xp that I've ever gained and counting it as all gained upon login but only for the first log in of every client restart. All skills are included in the tracker but only showing the first three. Resetting the xp manually works alright but the current behavior is unexpected.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/125943245/c7d79c6c-5b50-4b3a-bf54-297adfaf12e7)
![image](https://github.com/runelite/runelite/assets/125943245/7bd44caf-a747-4a17-9ae8-f2508bff3690)

### RuneLite version

RuneLite version 1.10.31.2, Oldschool version Rev 222, and Launcher version 2.6.4.

**Comment by YvesW** [comment]
Can you include your logs, and give us the steps to reproduce? Did you previously log in to e.g. a duel arena world or QSR world?

**Comment by SHvalross** [comment]
Didn't know safe mode was an option but upon looking into it it looks to be caused by an external plugin which is good. So I can go looking through and diagnosing which it is myself. Appreciate it. Have not logged in to a Duel arena or QSR world prior to this happening though.

**Comment by merlinmarijn** [comment]
It seems to happen cause of the "Default World" plugin for me, can you test it out if that is also the cause for you? @SHvalross

**Comment by YvesW** [comment]
@merlinmarijn Can you...
- Provide us of a video in safe mode of this happening with the title bar visible?
- Provide logs of this happening in safe mode?
- Show us your default world plugin config?
- Show us your profile tab, specifically if you got config profiles linked to RSProfiles or not?
- Delete client.log and enable debug mode, then launch in safe mode once with the bug happening -> post client.log with debug enabled -> disable debug mode again?

**Comment by SHvalross** [comment]
@merlinmarijn Doesn't look like disabling the default word plugin solved it for me. The only way I can get it to not track all the xp on first log in is launching in safe mode. Also @YvesW Here's a client log of a standard launch where the issue is was present. Running in Safe Mode does not produce the issue.
[client.log](https://github.com/user-attachments/files/15526032/client.log)

**Comment by merlinmarijn** [comment]
@YvesW it doesn't happen in safe mode, but i did take a video of it just incase

Safe mode video: 
https://github.com/runelite/runelite/assets/18032411/4102f7ba-ffce-468d-83ed-4d70186fdfab

Not safe mode video:
https://github.com/runelite/runelite/assets/18032411/2e95c7d9-d5dc-4928-9233-d3adcadc3af2

here is the settings of my default worlds plugin:
![default world](https://github.com/runelite/runelite/assets/18032411/b6a604b7-3329-4c4c-8d8d-575cc5077fa9)

and my runelite profiles tab:
![runelite profiles](https://github.com/runelite/runelite/assets/18032411/d0165858-b4bd-4a5f-9233-13a0d9beef52)

Here are the logs with the only plugins being enabled [XP Tracker, Default World, Plugin Preset]:
Client Logs:
[client.log](https://github.com/user-attachments/files/15526024/client.log)
Launcher Logs:
[launcher.log](https://github.com/user-attachments/files/15526026/launcher.log)
Client Logs with debug mode:
[client.log](https://github.com/user-attachments/files/15526055/client.log)
LauncherLogs with debug mode:
[launcher.log](https://github.com/user-attachments/files/15526056/launcher.log)

Here are the logs with safe mode enabled:
Client Logs:
[client.log](https://github.com/user-attachments/files/15526038/client.log)
Launcher Logs:
[launcher.log](https://github.com/user-attachments/files/15526039/launcher.log)
Client Logs with debug mode:
[client.log](https://github.com/user-attachments/files/15526048/client.log)
Launcher Logs with debug mode:
[launcher.log](https://github.com/user-attachments/files/15526050/launcher.log)

**Comment by YvesW** [comment]
@SHvalross @merlinmarijn If it does not happen in safe mode, it is very likely a hub plugin causing the issue. I recommend using a binary approach to find the culprit (https://raw.githubusercontent.com/runelite/wiki/master/img/flowchart.png).

**Comment by antpz** [comment]
I was able to recreate this issue while in safe mode.

Video:
https://github.com/runelite/runelite/assets/172458208/3a70bd59-b4d6-4a85-a7da-4e71e09bc406

Logs from that specific video:
[client.log](https://github.com/user-attachments/files/15797412/client.log)
[launcher.log](https://github.com/user-attachments/files/15797437/launcher.log)

Logs from a clean log folder with debug enabled in safe mode:
[client.log](https://github.com/user-attachments/files/15797551/client.log)
[launcher.log](https://github.com/user-attachments/files/15797552/launcher.log)

Default world plugin config:
![defaultWorldConfig](https://github.com/runelite/runelite/assets/172458208/46f4e22e-3928-4cf5-9698-1fc108d942cd)

Profiles tab:
![profileTab](https://github.com/runelite/runelite/assets/172458208/cb92e701-3135-4e25-bc61-aae2eae5a58b)

**Comment by Felanbird** [comment]
I can replicate this issue when logging in inside Wintertodt (w309), assuming the other reporters either have a slow computer or logged into very high pop areas, this might just be a new need to wait a few more ticks before initialization

**Comment by merlinmarijn** [comment]
> I can replicate this issue when logging in inside Wintertodt (w309), assuming the other reporters either have a slow computer or logged into very high pop areas, this might just be a new need to wait a few more ticks before initialization

I think @Felanbird has found the issue, i logged in at the civitas illa fortis farming patch and didn't get the xp, moved to the GE, closed game and re-opened and it happened again. so it's most likely something to do with slightly slower loading in cause of alot of players being around.

**Comment by SHvalross** [comment]
Yep I think I’m inclined to agree here with @Felanbird and @merlinmarijn. I was logging in to world 444 as my default world and that’s a pretty high pop world most days. That would also help explain why disabling the default world plugin might help since it appears to steer you away from high pop worlds.
