### ISSUE TITLE
Unable to sign in into my account

### ISSUE THREAD

**Issue by Chelsby96** [runelite/runelite#17928]
### Type

Crash or hang

### Operating System

Linux

### OS Version

Chrome OS Version 125.0.6422.140 (Official Build) (64-bit)

### Bug description

I am trying to log into my OSRS account but it is saying it is incorrect username or password. I have tried several times and I know my username and password are correct as I have used it today to log into the OSRS website.

### RuneLite version

1.10.31.3

**Comment by YvesW** [comment]
You probably did not read the full message. Jagex accounts need to launch RL via the jagex launcher.
If you upgraded or semi-recently made an account, you got a jagex account.
