### ISSUE TITLE
Motherlod Mine - Game/Ore Tracking Not visible

### ISSUE THREAD

**Issue by pudding437** [runelite/runelite#17925]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10 Home 19045.4412

### Bug description

There is currently no Ui Element showing the ore or gems collected in the Motherlode Mine.  It worked previously.  I have tested this in Safe Mode to the same result.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/89750770/6bc61575-7812-4ffd-9f22-9abd6bdcd125)
This is the motherload Sack tracker, my inventory, and the mining tracker; this is immediatley after emptying the sack.

### RuneLite version

Runelite version: 1.10.31.3
Launcher version: 2.6.13

**Comment by Nightfirecat** [comment]
It was removed in favor of having your ore loot appearing in the loot tracker

**Comment by pudding437** [comment]
Ah ok.  Good to know.
