### ISSUE TITLE
The ladder to descend from the second floor of Jiminua's Jungle Store is counted as an agility course clickbox by the Agility plugin

### ISSUE THREAD

**Issue by Rosalktha** [runelite/runelite#17935]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Win 10

### Bug description

Clickboxes enabled, shortcuts disabled

### Screenshots or videos

https://github.com/runelite/runelite/assets/62796916/1d474840-261c-4eca-bf23-7b4186c89e6d

### RuneLite version

RuneLite version: 1.10.31.3 Launcher version: 2.5.0

**Comment by Felanbird** [comment]
Are you able to replicate this in [safe mode](https://github.com/runelite/runelite/wiki/FAQ#how-do-i-run-runelite-in-safe-mode)?

**Comment by Felanbird** [comment]
The ladder in this room is the same ladder as the barb agility course
https://github.com/runelite/runelite/blob/f449e550ee29bb285350f73643402d5152351b3d/runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java#L61
![image](https://github.com/runelite/runelite/assets/41973452/4c08017d-bbce-4b32-9283-3573e08c17ab)
