### ISSUE TITLE
Sidebar bug

### ISSUE THREAD

**Issue by husker94** [runelite/runelite#1793]
Hi im new to runelite. Just downloaded it today and i noticed that whenever i used the sidebar i'm getting motion trail (effect when you win solitaire game) and it's really hard to ignore. It seems to go away when i minimize the client but happens again when I decide to use the sidebar.

**Comment by MagicfTail** [comment]
Try this https://github.com/runelite/runelite/issues/1449#issuecomment-380942422

**Comment by deathbeam** [comment]
Duplicate of #1449

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by TheXodius** [comment]
Thank you!
