### ISSUE TITLE
Client Freezes and ‘X-logs’ me

### ISSUE THREAD

**Issue by theJonasButte** [runelite/runelite#1794]
I’ve used this client for about a week now, done some Zulrah trips, some jad, some vorkath. No issues,  however went I went to Lizardman Shamans after 20 minutes my game would freeze, thus me having to reload client and log back in. Though it was a once off, but it happened 30 minutes later. 
I stopped using the client for a day or two but missed the features too much, went back to it and after a day of playing I went back to Shamans and 15 minutes later same problem. 
Not sure what the issue is, but I’ve never had any issue with clients freezing and gameplay stopping except for this.

**Comment by Roughsketch** [comment]
I'm having the same issue. It only popped up for me in the latest release, but now it is impossible for me to PvM because it keeps freezing.

**Comment by PoxyDoxy** [comment]
I too have this issue, the entire client freezes, not responding to any input and not doing any GUI updates, resulting in a screen-shot like appearance. 
The entire window, including screenshot button, sidebar button, and drag ability does not respond to hovering or clicking/dragging. 
Windows does not detect the application as unresponsive. 
The Program still presents a Java-Like "Are you sure you want to close" Yes/No Box, when right clicking the program in the task bar, and selecting Exit. 

It occurs with both "--mode=OFF" used to disable hardware acceleration, and with it on. 
The client was in Resizable Mode, on Windows 10 x64 bit. 
Windows was not lacking in hardware resources at the time. 

Timing for this can occur from 1 hour into NMZ, or 5 hours into NMZ, at random.

**Comment by deathbeam** [comment]
This seems inreproducible and we have like x other bugs, with same mostly 0 info and 0 solutions.
