### ISSUE TITLE
World Hopper bounty worlds not filtered out

### ISSUE THREAD

**Issue by alotOSRS** [runelite/runelite#17960]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

In the World Hopper settings you can set the World type filter. I set it to Normal.
This however still keeps all the "Bounty hunter worlds" in the list. So when I am quick hopping through worlds it suddenly pops up with a  warning message stopping me from hopping into a dangerous world "Warning the next world is a bounty hunter world". 
I am guessing that is not Normal and when the type filter is set to normal these Bounty Hunter worlds should be filtered out.

If I am mistaken and Bounty Hunter worlds are considered "Normal" then sorry about that and you can close this.

### Screenshots or videos

![del](https://github.com/runelite/runelite/assets/169375942/8b95db43-9493-4fd9-bd13-a00beea5df4a)

### RuneLite version

Runelite version: 1.10.31.4
Launcher version: 2.6.7

**Comment by cdfisher** [comment]
It looks like the "normal" filter has always included Bounty Hunter worlds so this is probably intentional.
