### ISSUE TITLE
[ItemStats] Pride capes are being considered body-slot items, not capes

### ISSUE THREAD

**Issue by Enriath** [runelite/runelite#17979]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Due to an error on the wiki listing the new pride capes as a body slot items and not capes, the item stats plugin won't display stat changes correctly when hovering over one; it will show changes as if you're replacing your chestpiece. This also affects plugins that make use of this slot data, such as Transmog.

I fixed the issue on the wiki a few days ago; The wiki scraper needs to be re-ran to fix this issue.

### RuneLite version

This bug will affect any version, as it is server side data the client loads.
1.10.32.1 was when I was first made aware of it.

**Comment by Nightfirecat** [comment]
Fixed in runelite/static.runelite.net#736
