### ISSUE TITLE
Add chat filter plugin

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1798]

**Comment by Gamer1120** [comment]
I'm making nice progress on this. I've figured out how to change names and chat messages. I'm going to have to look into deleting messages from chat, how I will determine whether a message is spam, how to kick people from CC, and how I can hide it above player's heads. (red text in this screenshot, also look at the chat):
![image](https://user-images.githubusercontent.com/9074448/39146379-df2c1d6a-4736-11e8-8ba2-60655048ea21.png)

**Comment by Adam-** [comment]
I think we definitely do not want to be automatically doing anything, including kicking people. Maybe we could hide messages we deem as spam but detecting when something is "spam" is hard and due to have false positives, which is bad.

**Comment by c-schell** [comment]
One option I foresee is to have the ability to have the client hide messages from users under a certain total level as seen on the hi scores. This could be additional to the blacklisting of certain phrases, but the auto kicking seems to be getting into "macroing" territory.

**Comment by c-schell** [comment]
Additionally, there is already a "clan chat" plugin at this time, would this be suited better as a config option within that plugin? I'm taking a look at Total Level filtering at this time and will update if I make any headway.

**Comment by SoyChai** [comment]
Definitely agree that anything which directly affects the game experience of another player, ie. kicking them from their clan chat, should never be automated. Letting players opt-in to a system which locally mutes people is completely fine though, as long as Pmods and Jmods are excluded from being filtered.

**Comment by SoyChai** [comment]
That would be a very natural feature of Gamer1120's [word blacklisting idea](https://github.com/runelite/runelite/pull/1847). You should combine your efforts into the same plugin. 👍

**Comment by Flexo013** [comment]
As nice as it would be to have this for clan chats I also think there is a much simpler use that should be easier to fulfill. Namely blacklisting specific keywords in regular chat.

This would obviously be opt-in and the user should have full control of what words they want to blacklist. But it would be a nice automated way of not having to deal with bots. Anything from bannable ads to people just advertising a clan chat. 

Maybe a simple work-around could be to add the user saying a blacklisted word on your ignore list. This would remove both the message in chat and the yellow text in game. On top of that would it give the user control over somebody who accidentally got ignored.

**Comment by devLotto** [comment]
Found this issue from ianspam's request over at https://twitter.com/ianspam/status/1058104900121518082.

Yeah, a word blacklisting plugin would be neat. Automatic "spam filtering" is probably not possible.

**Comment by deathbeam** [comment]
Updated title, removed the part about clan-chat and kicking

**Comment by Gamer1120** [comment]
Due to time constraints and programming not being something I want to spend time on in my spare time, I am abandoning this. Someone else can pick it up.
