### ISSUE TITLE
Fairy Rings - Searching for favorites

### ISSUE THREAD

**Issue by Saltkringel2** [runelite/runelite#17990]
### Type

Bug

### Operating System

None

### Bug description

When a fairy ring is set as "favorite" it is not showing up if searching for it.

### Screenshots or videos

![image](https://github.com/runelite/runelite/assets/31405952/de6ed026-de77-47e2-8e83-5ac4a84e8a42)
![image](https://github.com/runelite/runelite/assets/31405952/5bcb1f55-c069-41ed-b0e3-b48f46a0631d)
![image](https://github.com/runelite/runelite/assets/31405952/456f6ffe-d2f7-40f7-bbad-c4c00bbf982a)

### RuneLite version

1.10.33.1

**Comment by YvesW** [comment]
Relevant prs: https://github.com/runelite/runelite/pull/16172
https://github.com/runelite/runelite/pull/16168

**Comment by Felanbird** [comment]
added in 675ad97ff2595a967b97f979dab66f1babaaa028
