### ISSUE TITLE
Run button 

### ISSUE THREAD

**Issue by Runescape69** [runelite/runelite#17993]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The Run button on mini map hub keeps turning itself off while the run is still lit up causing you to click it showing run is off. Moments later it will correct and your run will be off again. Then you turn run on and it will eventually turn off without button hub being clicked 

### RuneLite version

Launcher

**Comment by Bram91** [comment]
Do you mean this game behavior?
![image](https://github.com/runelite/runelite/assets/7499230/c924de5c-0fef-495b-be2d-b7e7cf7646b3)
You can change that in the in-game settings.
