### ISSUE TITLE
onItemContainerChanged does not trigger when plank sack is filled from sawmill

### ISSUE THREAD

**Issue by YeahImRose** [runelite/runelite#18002]
### Type

Incorrect behavior

### Operating System

None

### Bug description

onItemContainerChanged does not trigger when plank sack is filled from sawmill. Found this behavior from what I thought was a bug in the Plank Sack plugin, but then found out the actual function isn't even triggered when the planks are put in the sack.

### RuneLite version

RuneLite version: 1.10.33.1
Launcher version: 2.6.10

**Comment by YeahImRose** [comment]
I plan on looking into the root cause of this, but posting this as an issue in advance in case anyone with more experience finds an easy fix.

**Comment by Adam-** [comment]
This either means the plank sack has no inventory or the inventory is not opened on the client. It isn't a bug.

**Comment by YeahImRose** [comment]
> This either means the plank sack has no inventory or the inventory is not opened on the client. It isn't a bug.

The thing is, this does get trigged when the plank sack is manually filled or emptied.

**Comment by YeahImRose** [comment]
> This either means the plank sack has no inventory or the inventory is not opened on the client. It isn't a bug.

https://github.com/Enriath/external-plugins/blob/5c460f8ffa6a1d7ec33e74f9c1efef73196ae104/src/main/java/io/hydrox/planksack/PlankSackPlugin.java#L185C63-L185C64
Here's the use case of it in that Plank Sack plugin, where it does in fact trigger for the plank sack in (seemingly) all cases except planks entering it after being made at the sawmill

**Comment by Adam-** [comment]
> > This either means the plank sack has no inventory or the inventory is not opened on the client. It isn't a bug.
> 
> https://github.com/Enriath/external-plugins/blob/5c460f8ffa6a1d7ec33e74f9c1efef73196ae104/src/main/java/io/hydrox/planksack/PlankSackPlugin.java#L185C63-L185C64 Here's the use case of it in that Plank Sack plugin, where it does in fact trigger for the plank sack in (seemingly) all cases except planks entering it after being made at the sawmill

This is showing a check for the inventory item container. I would expect that to be updated as the inventory isn't closed when purchasing planks.

**Comment by YeahImRose** [comment]
Ah, I see what you mean.
