### ISSUE TITLE
Certain Slayer Targets Not Being Highlighted

### ISSUE THREAD

**Issue by CharlesLove** [runelite/runelite#1800]
All monsters featured below do not automatically highlight when assigned on slayer tasks.

Flesh Crawlers,
Small Lizards (Desert Lizards alternative), and
Baby Dragons (Have only seen blue, but this likely affects all color variants)

**Comment by Kamielvf** [comment]
The issue with baby dragons is that they're all named "baby dragon", and I think the plugin is matching names.

**Comment by CharlesLove** [comment]
For baby dragons, maybe levels could also be taken into consideration to differentiate them.

**Comment by rherms** [comment]
Hey I'm a new dev to RuneLite and this fix sounds relatively easy so I'm going to give it a shot!

**Comment by rherms** [comment]
Baby dragons are all the same level unfortunately.

**Comment by titegtnodI** [comment]
Sulphur Lizards also don't highlight. They also don't decrease the slayer counter (I assume it's the same issue, so I'm only mentioning it here).

**Comment by Alexsuperfly** [comment]
with the update today jagex have said `Baby dragons now have their colour in their name in order to help colourblind players determine which is which.`  So solving the baby dragon portion of this issue is now possible.

**Comment by Narozzy** [comment]
Is this still an issue, looking through the `Task.java` and the `SlayerPlugin.java` code, seems like we are just checking if the name of a monster contains the target name, which are not set for any of the dragons as an example.

**Comment by Nightfirecat** [comment]
Yes, this is still an issue for the specific cases outlined in the original post.
