### ISSUE TITLE
Chat Filters for Nex

### ISSUE THREAD

**Issue by MoistSlothPhD** [runelite/runelite#18023]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The "Chat Filter" plugin was filtering Nex's dialog until the While Guthix Sleeps update on 07/10. This dialog is no longer registered by the filtered words/regex/names or the collapse game chat. 

A plugin reset was tried and my filtered lists redone (Fumas, Umbra, I demand a blood sacrifice, Cruor, Infuse me with the power of ice, Contain this, NO ESCAPE, Darken my shadow, Fear the shadow, Taste my wrath, AT LAST, Let the virus flow through you, There is..., Embrace darkness, A siphon will solve this, Fill my soul with smoke, in a prison of ice, don't fail me, THE POWER OF ZAROS)

### RuneLite version

Runelite Version: 1.10.34
Launcher Version: 2.6.1

**Comment by YvesW** [comment]
For future reference, this is likely caused by today's game update introducing a new chat message type for this npc text.

**Comment by WhatTheHai** [comment]
Small bump to notify you're still unable to filter out Nex dialogues because of this.
