### ISSUE TITLE
GE filters plugin needs to be updated

### ISSUE THREAD

**Issue by kweetman222** [runelite/runelite#18030]
### Type

Other

### Operating System

Windows

### Bug description

GE Filters needs to be updated

### RuneLite version

1.9.11

### Logs

[client.log](https://github.com/user-attachments/files/16182248/client.log)
[launcher.log](https://github.com/user-attachments/files/16182250/launcher.log)

**Comment by Nightfirecat** [comment]
We aren't the authors of that plugin, please ask the author to update it.
