### ISSUE TITLE
Floor not being drawn in Wintertodt (Low detail)

### ISSUE THREAD

**Issue by SirRando** [runelite/runelite#1805]
The floor instead of being rendered as a flat texture is utilising the texture of the floor around the Wintertodt (parallax) giving the impression of an invisible floor.

- Reproducible by setting detail mode to Low and then entering the WT lair.
- No difference is made if the play logs in and out again.

Java version used: 1.8.0_161 64bit

Sorry I couldn't add more

**Comment by deathbeam** [comment]
Duplicate of #1481
