### ISSUE TITLE
When the option "remove dead npc menus" is active, sometimes npcs after respawning will become unclickable

### ISSUE THREAD

**Issue by Seanzuwu** [runelite/runelite#18091]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When the "Remove dead npc menus" from menu entry swapper is enabled an npc will never regain it's click function back, the monster is essentially invisible to the mouse, doesn't highlight, can't be right clicked.

### Screenshots or videos

![image_png](https://github.com/user-attachments/assets/24e3079c-d7b9-4d66-93c3-df73b683f7d8)

### RuneLite version

1.10.35

2.7.1

**Comment by Nightfirecat** [comment]
Duplicate of #15490
