### ISSUE TITLE
Lost Souls in Whisperer fight affected by Compute Shaders

### ISSUE THREAD

**Issue by Sephesly** [runelite/runelite#18097]
### Type

GPU

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Whilst the GPU plugin is enabled, the Lost Soul NPCS in the Whisperer fight render differently than intended. Instead of the black skeletal body rendering above the ghost, a large amount of this gets cut off around the chest and head. Disabling Computer Shaders fixes this, but I assume this isn't ideal. This is the only notable error I've had with the setting enabled.

### Screenshots or videos

![ghostrenderwrong](https://github.com/user-attachments/assets/ed735b03-d691-422b-bcc4-9b1e474299a8)

### RuneLite version

RuneLite version: 1.10.35
Launcher version: 2.6.8

### Logs

[client.log](https://github.com/user-attachments/files/16402631/client.log)
[launcher.log](https://github.com/user-attachments/files/16402632/launcher.log)

**Comment by YvesW** [comment]
The screenshot looks fine to me? I don't do any whisperer though. Can you show a screenshot with and without?
While I doubt it has any impact, does enabling or disabling animation smoothing change anything?

**Comment by Sephesly** [comment]
> The screenshot looks fine to me? I don't do any whisperer though. Can you show a screenshot with and without? While I doubt it has any impact, does enabling or disabling animation smoothing change anything?

![wrongghosts](https://github.com/user-attachments/assets/c9fc2c47-c009-4064-bd6f-4f4fc41045df)
With Compute Shaders

![correctghosts](https://github.com/user-attachments/assets/83988a8e-ab02-4950-a156-c4586222a0e4)
Without Compute Shaders

![300px-Lost_Soul_(Vita!)](https://github.com/user-attachments/assets/f1bce5bc-5dac-44fa-a5e2-f597447c9d42)
https://oldschool.runescape.wiki/w/Lost_Soul_(The_Whisperer)#Shadow_Realm The wiki page also displays the intended render alongside footage, which should be fine for comparison.

Animation smoothing has no effect. Vertex snapping setting also has no impact.

**Comment by Adam-** [comment]
fixed in cf24c842573a01b50b17face3dbfd041de6117d6
