### ISSUE TITLE
Loot Tracker - Gem Bags

### ISSUE THREAD

**Issue by shortcircuit21** [runelite/runelite#18106]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Loot Tracker plugin doesn't track the Gem Bags purchased from the mining guild with stardust.

### RuneLite version

1.10.34

**Comment by Felanbird** [comment]
Restart your client, the version of RuneLite that came out 9 days ago supports Gem Bags.
