### ISSUE TITLE
[Attack Styles] Blue Moon Spear not Hiding Styles

### ISSUE THREAD

**Issue by PureIllenium** [runelite/runelite#18124]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When using the Attack Styles plugin and selecting to hide styles, the Blue Moon Spear does not properly hide all the styles.

### Screenshots or videos

![Attack Styles Blue Moon](https://github.com/user-attachments/assets/b3524fda-aee9-47a5-8187-ad520123f055)

### RuneLite version

RuneLite Version: 1.10.35
Launcher Version: 2.7.1

**Comment by YvesW** [comment]
- Does the set effect button also show when you are not wearing the full outfit?
- In case it does not, does it properly hide the styles then?
- Does the same issue happen on jagex's C++ client (EHC)?

**Comment by Adam-** [comment]
We can probably just special case it like we did with the keris.

**Comment by PureIllenium** [comment]
> * Does the set effect button also show when you are not wearing the full outfit?
> 
>     * In case it does not, does it properly hide the styles then?
>

The screenshot that I took was with just the weapon equipped.
