### ISSUE TITLE
Idle animation while holding Ursine mace

### ISSUE THREAD

**Issue by Rahib0** [runelite/runelite#18143]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10

### Bug description

Equip an Ursine mace and stand still. The characters idle animation while holding the mace creates some strange movement while the plugin is enabled. The idle sway of the mace becomes very exaggerated and looks strange.
![image](https://github.com/user-attachments/assets/c42eeae7-9149-4154-b265-1435512ba2fb)

### RuneLite version

RuneLite Version: 1.35.10
Launcher Version: 2.6.4

**Comment by Felanbird** [comment]
We added chainmace to the list of animations not-to-smooth, due to the jittering it does when we try to smooth it.
