### ISSUE TITLE
Medium cluescroll - Incorrect world point and icon

### ISSUE THREAD

**Issue by mtarik550** [runelite/runelite#1814]
https://i.imgur.com/oi0kD9e.png its meant to be a world point or highlight on the crate and not on the floor also remove the spade icon because its misleading. Thanks

**Comment by Roughsketch** [comment]
I believe this was fixed in #1876

**Comment by Nightfirecat** [comment]
Confirmed, closed in #1876. @deathbeam Close this one too? :heart:
