### ISSUE TITLE
Weird Face buttons appearing on screen

### ISSUE THREAD

**Issue by BurgerFan45** [runelite/runelite#18141]
### Type

GPU

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Weird face buttons appeared on main screen today, not sure why, they seem to disappear when I click off runescape then re-appear when I tab back in.
Still appeared when I closed then ran in safe mode.

### Screenshots or videos

![Faces Bug](https://github.com/user-attachments/assets/366beb85-fae6-4162-865b-8bed8d807474)

### RuneLite version

Runelite version: 1.10.35
Oldschool version: Rev 223
Launcher Version: 2.7.1

### Logs

[client.log](https://github.com/user-attachments/files/16535760/client.log)
[launcher.log](https://github.com/user-attachments/files/16535762/launcher.log)

**Comment by Felanbird** [comment]
It looks like the emoji icon from Discord, does disabling the Discord overlay remove them?

**Comment by BurgerFan45** [comment]
Yes must be something on discord's end then, disabling the discord runelite plugin does nothing.
But shutting down discord itself stops it.
