### ISSUE TITLE
Player Indicators: Clan chat ranks not working properly with the extra ranks Jagex added July 31st

### ISSUE THREAD

**Issue by robuuuste** [runelite/runelite#18159]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Player Indicators is not showing the correct ranks when using the new ranks that were added in the [game update](https://secure.runescape.com/m=news/a=13/qol-improvements--further-deadman-armageddon-tweaks?oldschool=1) July 31st. If a clan member has one of the new ranks, Player Indicators will incorrectly show the icon of the default (lowest) rank.

### Screenshots or videos

![13-08-2024_11-46-23](https://github.com/user-attachments/assets/5f145717-6c59-4c70-a6f7-2d337f219393)
![13-08-2024_11-45-48](https://github.com/user-attachments/assets/c67f4882-52df-4eb3-bca9-8a681f16a71f)
![13-08-2024_11-51-08](https://github.com/user-attachments/assets/03061725-178f-40b7-8589-cb54e8b3084d)

### RuneLite version

RuneLite version: 1.10.35
Launcher version: 2.7.1

**Comment by Adam-** [comment]
This should be fixed by 00d6ffc43965963d6b890c2af5b2bf88e5f10c20 - if you want to test it that would be helpful - but it will be released tomorrow
