### ISSUE TITLE
Ground Items Highlight

### ISSUE THREAD

**Issue by thestdman** [runelite/runelite#1816]
I have an issue with the ground items ui, the boxes for adding new highlight or blocked items is much too small and as so is hard to edit easily.

My proposed solution for this is the ability for it to be an editable text document through notepad or otherwise that is stored locally.

**Comment by devLotto** [comment]
You can edit these input boxes in the Ground Items plugin's settings:

![](https://i.imgur.com/9323XVh.png)

Is that what you wanted?

**Comment by Reasel** [comment]
Also to go off this, you could make a document in notepad and fill it with your items. then copy all of it and paste it into the Highlighted or Hidden Items list.

**Comment by deathbeam** [comment]
The textfields has been changed to textareas so now it is a lot easier to edit, I guess this has been resolved.
