### ISSUE TITLE
Corp FFA Plug in Special attacks are not registering

### ISSUE THREAD

**Issue by FatherTacos** [runelite/runelite#18176]
### Type

Performance

### Operating System

Windows

### OS Version

11

### Bug description

I do a lot of Corporial Beast, and use the Corp FFA plug in.  Typically, when you use the plug in, you are able to see your group's specs. This has gone away. You can see the words and the item being used, but it is not registering the spec attacks. 

### RuneLite version

Rune Lite 

### Logs

.

**Comment by cdfisher** [comment]
Issues for hub plugins should be reported to their respective authors. You can report an issue with the Corp FFA plugin [here](https://github.com/Box-Of-Hats/runelite-plugin-corp-ffa/issues).

**Comment by Felanbird** [comment]
As mentioned above and in the issue template, We do not accept bug reports for 3rd party/pluginhub plugins.

You can right-click a hub plugin in the 🔧 tab and select the `Support` option to find the correct place to report an issue, or in your case use the direct link for the plugin you are having issues with, that cdfisher has supplied you.
![image](https://github.com/user-attachments/assets/fde44bf5-1cd3-4864-9947-218bf65b2943)
