### ISSUE TITLE
[Inventory Tags] Duplicate Tags showing up in inventory panel

### ISSUE THREAD

**Issue by Nick2bad4u** [runelite/runelite#18172]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

WIn 11 - Build 22631.4037

### Bug description

Inventory Tags are showing up to the left of the Helm space.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/88fa3b9f-fdb3-48dd-a098-e7e0bcde47a2)

### RuneLite version

1.10.36.1
Rev 224
2.7.1

**Comment by Nightfirecat** [comment]
Does this behavior happen while running in safe mode?

For info on launching in safe mode, see: https://github.com/runelite/runelite/wiki/FAQ#how-do-i-run-runelite-in-safe-mode
