### ISSUE TITLE
Desktop Icon

### ISSUE THREAD

**Issue by choocher13** [runelite/runelite#1818]
This is rather nit picky but can the icon for the shortcut be a full sized icon? Rather annoying to see that white box around it on the desktop. thanks.

**Comment by MESLewis** [comment]
What OS are you on? Could you post a screenshot?

**Comment by choocher13** [comment]
![screenshot](https://user-images.githubusercontent.com/32646750/39101214-a3d865fc-4664-11e8-9621-21849dd87e9d.png)

This is what I'm referring to

**Comment by MESLewis** [comment]
This is what it looks like on Windows 10 for me
![image](https://user-images.githubusercontent.com/597053/39101269-7c2b2c20-4654-11e8-9491-33f921c382e6.png)

**Comment by choocher13** [comment]
It looks fine when the icon is small. But when you make the icons larger, that white line emerges.

**Comment by choocher13** [comment]
It looks fine when the icon is small. But when you make the icons larger, that white line emerges.

**Comment by MESLewis** [comment]
Wow I never knew it would do that. I'm seeing the same white border on most of my desktop icons when zoomed in. I'm not sure there is anything we can do about it.

**Comment by HypoxiaOSRS** [comment]
This isn't a bug from our side. Every Java.exe I have creates that border while using scaled layout.

**Comment by choocher13** [comment]
It has to do with the .ico they use when compiling the program. If he scaled the current icon to a full 512x512, the issue would be resolved. This is what I'm asking for.

**Comment by choocher13** [comment]
Any thoughts?

**Comment by deathbeam** [comment]
https://github.com/runelite/launcher this should be reopened here.
