### ISSUE TITLE
GPU plugin forcing antialiasing

### ISSUE THREAD

**Issue by elf-lambda** [runelite/runelite#18217]
### Type

GPU

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Is it possible to turn offf gpu plugin forcing antialiasing? i dont like how the game looks smooth and would like the vanilla pixelated look. Is it possible to force turn it off but still keep the draw distance and improved fps?

### Screenshots or videos

GPU OFF
![image](https://github.com/user-attachments/assets/d991f68c-bcba-4110-b185-4690875d3fd6)
GPU ON
![image](https://github.com/user-attachments/assets/5da4d821-3f67-48a2-80a5-e81c27712f0a)

### RuneLite version

latest

**Comment by elf-lambda** [comment]
bump

**Comment by Adam-** [comment]
With anti aliasing set to "disabled" anti aliasing *is* disabled. What you are seeing is probably the result of using a floating point projection instead of integer. There isn't a way to avoid that.

**Comment by elf-lambda** [comment]
> With anti aliasing set to "disabled" anti aliasing _is_ disabled. What you are seeing is probably the result of using a floating point projection instead of integer. There isn't a way to avoid that.

shame, really ruins the nostalgia

**Comment by elf-lambda** [comment]
> Regarding rendering distance, you could use `::setdrawdistance x` to adjust it, with `x` being a value between 25-90. This is a vanilla feature and will work without the GPU plugin.

How do you set this setting?
