### ISSUE TITLE
Time Tracking : Showing celastrus tree icon bug

### ISSUE THREAD

**Issue by DeniZgamR** [runelite/runelite#18224]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

For the time tracking plugin it shows my celastrus tree is done, I don't have one planted and it's not listed in any of the lists from the plugin so there is no way for me to remove the notification.

### Screenshots or videos

<img width="787" alt="tree" src="https://github.com/user-attachments/assets/4ce8983e-0031-4e40-a5f5-3a8c3bc0f396">

### RuneLite version

Runelite version: 1.10.36.3
Launcher version: 2.7.1

**Comment by YvesW** [comment]
This is the time tracking reminder pluginhub plugin. We do not support hub plugins, as we do not create, maintain, or quality control them.

Support for hub plugins should be directed to the author of the plugin. You can find the support link by searching for the plugin in the Plugin Hub panel and clicking the `?` button on the plugin, or by right-clicking the plugin in the plugin panel and clicking the `Support` menu option. Then you can create an issue using the link in the top right.
