### ISSUE TITLE
Item Stats shows wrong bonuses for Guthix damaged book

### ISSUE THREAD

**Issue by KeepBotting** [runelite/runelite#18246]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

SteamOS stable

### Bug description

I noticed the tooltip for all the Damaged book items correctly report the only bonus as +5 prayer except Guthix's book

### Screenshots or videos

Correct:
![image](https://github.com/user-attachments/assets/95fdc17b-b8b6-46c4-89fb-e01a32f0df57)

Incorrect:
![image](https://github.com/user-attachments/assets/ba9c0968-2749-40db-b3ba-76857e802e0e)

The incorrectly-reported attack stats are of course not reflected in-game when equipping the item: 
![image](https://github.com/user-attachments/assets/f34e65b3-3796-4dab-995b-f4e78e918f1f)

And the wiki agrees: https://oldschool.runescape.wiki/w/Damaged_book_(Guthix)

This damaged book has page 3 added to it, not sure if that matters

### RuneLite version

RL version 1.10.36.3
Launcher version 2.7.2

### Logs

Let me know if these are relevant here and I will provide them

**Comment by Adam-** [comment]
I've resyned the stats from the wiki to fix this. The wiki had given it stats earlier https://oldschool.runescape.wiki/?title=Damaged_book_%28Guthix%29&diff=14725562&oldid=14540146
