### ISSUE TITLE
These spells won't go away?

### ISSUE THREAD

**Issue by Simpuhl** [runelite/runelite#18243]
### Type

Incorrect behavior

### Operating System

None

### OS Version

Windows 11

### Bug description

I can't get the 3 highlighted spells to disappear, I tried disabling a bunch of different spell addons but nada... don't know which is causing it... I could have sworn there was one for that spellbook that are supposed to disappear when your not on it but they been stuck here for over a week now.

### Screenshots or videos

https://i.imgur.com/5ZuvoAi.png

### RuneLite version

Latest

**Comment by YvesW** [comment]
![image](https://github.com/user-attachments/assets/e9b500bb-9720-4f8e-af93-95ad3ea9f8e6)

This is very likely just a misbehaving hub plugin, so it'd not happen in safe mode. Please refer to [this flowchart](https://raw.githubusercontent.com/runelite/wiki/master/img/flowchart.png) for further troubleshooting.

**Comment by Felanbird** [comment]
Closing as this received no updates, and was likely a hub plugin as mentioned above.

**Comment by Simpuhl** [comment]
Sorry, this went away after resetting the plugin.
