### ISSUE TITLE
Plank sack plugin scuffed

### ISSUE THREAD

**Issue by SL0BO** [runelite/runelite#18252]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Was a lil scuffed before is big scuffed now. Shows wrong amount of planks in the sack. I think its for others aswell

### RuneLite version

1.10.36.3
2.6.7

**Comment by Felanbird** [comment]
![image](https://github.com/runelite/runelite/assets/41973452/41758311-b94a-485f-9694-4108139903e6)

Support for hub plugins should be directed to the author of the plugin.
You can find the support link by searching for the plugin in the Plugin Hub panel and clicking the `?` button on the plugin, or by right-clicking the plugin in the plugin panel and clicking the `Support` menu option.
