### ISSUE TITLE
screenshot boss kills no longer working over one thousand kc

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#18258]
### Bug description

boss kill messages now have a thousands place comma separator which [the regex](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/screenshot/ScreenshotPlugin.java#L99) fails to match

### Screenshots or videos

a kill message auto screenshotted before the update today
![image](https://github.com/user-attachments/assets/704c0186-c974-46c2-9893-8a9e0579253c)

a kill message manually screenshotted after the update today
![image](https://github.com/user-attachments/assets/ca507080-fbfc-4c83-b25d-33955a2b81d4)

**Comment by 416c616e** [comment]
This applies to more than just bosses, Barrows also reports a comma as well. Perhaps expand the changes as I presume this is the new norm?
