### ISSUE TITLE
Object marker does not apply settings on profile change

### ISSUE THREAD

**Issue by ac0ff43** [runelite/runelite#18256]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Switching between profiles does not apply the new profile settings to objects in the scene, instead requires a scene load or plugin toggle (disable-enable) to reflect the new profile config.

### RuneLite version

v1.10.37
rev225
launcher 2.7.2

**Comment by Veri7ion** [comment]
Thanks to your post I was finally able to load my correct settings by toggling the plugin. The Camera Keys plugin has the same issue.

**Comment by Adam-** [comment]
fixed in 1257187978fd306d05028c0042349d4b78ada9f8
