### ISSUE TITLE
Incorrect label for falconry Hunter node on world map

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#18269]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Greater sirens are only available from aerial fishing on Molch Island.

### Screenshots or videos

![2024-09-13-03-28-10](https://github.com/user-attachments/assets/d46a6643-32e6-4337-9f4b-00219cb616e0)

### RuneLite version

RuneLite version: 1.10.37
Launcher version: 2.6.10

**Comment by tylerwgrass** [comment]
This is fixed but issue didn't auto-close
