### ISSUE TITLE
Lightbox Solver

### ISSUE THREAD

**Issue by inewman** [runelite/runelite#1826]
Since RuneLite solves most (all?) other clue scroll puzzles, I think it would be good if it could also solve a Lightbox (item name: Light box) from master clues.

I would like to work on this myself. I have already implemented the logic for a reasonably efficient solving pattern that attempts to find a solution after pressing each button (only guaranteeing a found solution after having pressed all buttons, but attempting a solution as soon as a new controlled set of lights is discovered). I'll submit a PR once I obtain a Light box in-game and can set up the visuals.

**Comment by Jalopyy** [comment]
Something like this already exists if you wanted to look at the code to make something similar for Runelite. I personally use the first one because it hooks to the client and does it all for me after you run it in python.

https://github.com/subjectivelyobjective/osrs-lightbox-solver

https://osrs-lightbox-solver.fletom.com/

**Comment by inewman** [comment]
I didn't know about the first one, but I did know about the second one. That's pretty cool. My solving logic is much like fletom's (except I attempt a solution after pressing each button as opposed to identifying the lights for each button before attempting a solution). Thanks for the info.

**Comment by Jalopyy** [comment]
I'd probably only make it give a solution after you click every button. If it tries to solve it and fails after a click or two people will probably assume it's broken and submit a ticket/complain.

**Comment by inewman** [comment]
It won't fail, it'll ask you to press the next button.

Basically, the process is:

"Press A"
User presses A
Save changed lights as A's matrix
Check if solution is possible using current known matrices (currently just A), if so, display solution.
"Press B"
User presses B
Save changed lights as B's matrix
Check if solution is possible using current known matrices (currently just A and B), if so, display solution.
etc.
