### ISSUE TITLE
Artio, spindel kill screenshots are not being captured. Other bosses works (not wildy ones)

### ISSUE THREAD

**Issue by mantas7779** [runelite/runelite#18281]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Boss kill folder does not contain wildy bosses screenshots. noticed this recently by killing some Artio and spindel. Nothing is there

### Screenshots or videos

[
![Screenshot_34](https://github.com/user-attachments/assets/9a64423e-30b4-48d4-bd6c-9db58322688f)
](url)

### RuneLite version

1.10.37.1

### Logs

[launcher.log](https://github.com/user-attachments/files/17013
[client.log](https://github.com/user-attachments/files/17013351/client.log)
350/launcher.log)

**Comment by raiyni** [comment]
Can you look without windows search?

**Comment by mantas7779** [comment]
yes, last screenshots are from barrows i was doing yesterday but after that I went for Artio (no ss) today I was farming around 100+ spindel kills (0 ss in the folder.
![Screenshot_35](https://github.com/user-attachments/assets/9395ed69-8146-4304-875c-dcfd23cb3a85)

**Comment by cdfisher** [comment]
Are your Artio and Spindel KC 1000 or over?

**Comment by mantas7779** [comment]
no, both under. Does it stop capturing past 1k?

I have Calvarion, Spindel and Artio SS saved from previous windows installation so it was working fine before but not recently.

**Comment by cdfisher** [comment]
> no, both under. Does it stop capturing past 1k?

There's currently a known issue where (some?) bosses no longer trigger a screenshot when the KC is 1,000 or over because Jagex added a comma to the message.

Can you post screenshots of what the message is when you get a KC at those bosses?

**Comment by mantas7779** [comment]
by enabling "notify when taken" option in screenshot plugin?

**Comment by Alexsuperfly** [comment]
enable the debug option in https://github.com/runelite/runelite/wiki/RuneLite-Launcher-Configuration then launch the client, do a kill, and post the client log again

**Comment by mantas7779** [comment]
[client.log](https://github.com/user-attachments/files/17014127/client.log)

**Comment by Alexsuperfly** [comment]
this looks fine, do you have boss screenshots turned on

**Comment by mantas7779** [comment]
yes i do, havent changed any settings and mentioned It captured plenty of barrows but no Grotesque Guardians from yesterday I now see.

**Comment by Alexsuperfly** [comment]
actually this looks like the case fixed in #18272, the kc message has a trailing period punctuation mark which is causing the match to fail

**Comment by Alexsuperfly** [comment]
wait for the next release
