### ISSUE TITLE
Screenshot plugin not working on Dagannoth kings

### ISSUE THREAD

**Issue by Luiz-Loch** [runelite/runelite#18287]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

Macos 14.6.1 and 15.0

### Bug description

While in a Dagannoth King task, no boss kc screenshot was taken.
The screenshot plugin was always on. The Screenshot Boss Kills was toggle as well.

### RuneLite version

2.6.11

**Comment by Felanbird** [comment]
Duplicate of #18258 & #18281

The applied fix for the original issue accidentally broke the matching in a different way, it will be fixed in the next RuneLite version
