### ISSUE TITLE
Highscores

### ISSUE THREAD

**Issue by Mclovin999999** [runelite/runelite#18289]
### Type

Other

### Operating System

Windows

### OS Version

11

### Bug description

New group account not appearing on Runelite Highscores with other requirements like min lvl met, any ideas of what I need to do to make this appear? Name Group07JC

### RuneLite version

Launcher version

**Comment by Alexsuperfly** [comment]
RuneLite doesnt have HiScores, it merely displays the Jagex HiScores, if you arnt not on those then RuneLite has nothing to display.
