### ISSUE TITLE
Game automatically disconnecting/logging out on runelite in macOS Sequoia

### ISSUE THREAD

**Issue by saepstei** [runelite/runelite#18290]
### Type

Crash or hang

### Operating System

MacOS

### OS Version

15.0

### Bug description

After upgrading to Sequoia on 2 separate devices, the game is constantly automatically logging out, doing temporary hiccup disconnects (disconnects then reconnects before logging out entirely) and is entirely unstable. Game worked 100% fluidly until the upgrade.

This has been attempted on 3 separate types of wifi in 3 locations.

Also attempted to remove and reinstall, removed all cache repeatedly, and kept timers on to determine how long game lasted.

Even something as benign as fishing in catherby couldn't be handled consistently for more than a minute with disconnects. Similar issues were found in the grand exchange, Kourend, Fossil Island (it didn't seem to be affected by anything server-side).

OSRS default client seems fine.

**SPECS**:

M3 Pro 14" Macbook Pro
18GB of RAM

### RuneLite version

Runelite: 1.10.37.1
Launcher: 1.2.0

### Logs

[client.log](https://github.com/user-attachments/files/17050116/client.log)
[launcher.log](https://github.com/user-attachments/files/17050117/launcher.log)

**Comment by saepstei** [comment]
Reinstalled macOS on both devices and it seems to have worked just fine

**Comment by saepstei** [comment]
Reinstalled macOS on both devices and seems to be working just fine now

**Comment by nudabagana** [comment]
No way reinstalling macOS is the fix? That's something I cannot do on my laptop. Any other suggestions?

**Comment by saepstei** [comment]
Sorry, it incidentally only fixes it temporarily. It's worse than that, it seems it's a Sequoia issue--to the point whole universities and companies are preventing people from upgrading:

https://techcrunch.com/2024/09/19/apples-new-macos-sequoia-update-is-breaking-some-cybersecurity-tools/

https://www.forbes.com/sites/ariannajohnson/2024/09/20/macos-sequoia-update-why-some-organizations-are-advising-against-updating-devices/

https://discussions.apple.com/thread/255761318?sortBy=rank

People are having insane internet issues and connectivity ones, particularly those that have any security tools installed, such as a VPN or other things. I think until this is resolved on Apple's end this will continue. Even those without some tools are having issues.
