### ISSUE TITLE
MacOS 15.0 Sequoia constant discconects

### ISSUE THREAD

**Issue by nudabagana** [runelite/runelite#18292]
### Type

Crash or hang

### Operating System

MacOS

### OS Version

15.0

### Bug description

After updating to MacOS 15.0 Runelite keeps constantly disconnecting. It does it every 15s-2mins. It's impossible to use.
I saw a post by other person, but it got closed, so I'm adding a new one since the problem is still there (other post: https://github.com/runelite/runelite/issues/18290).

### RuneLite version

Runelite version: 2.7.2

### Logs

[client.log](https://github.com/user-attachments/files/17060517/client.log)
[launcher.log](https://github.com/user-attachments/files/17060522/launcher.log)

**Comment by Adam-** [comment]
Your client log seems to have a large number of client errors - have you tried safe mode first to see if that resolves your issue?

**Comment by nudabagana** [comment]
Found the cause of this after multiple days. It seems to be related to wi-fi specifically. People are having overall wi-fi problems on MacOs 15.0 and they also manifest in Runeline.
Here are a couple solutions that work for some: https://discussions.apple.com/thread/255761318?answerId=260758305022&sortBy=rank#260758305022 https://www.reddit.com/r/MacOS/comments/1fihlge/macos_15_sequoia_bugs_and_issues_megathread/
Also, if you have LAN port and a cable, you can use that and it will also work. Hopefully Apple fixes all of this in 15.1
