### ISSUE TITLE
World Hopper - Scaling issue & skill total worlds not being filtered out

### ISSUE THREAD

**Issue by Sebastipole** [runelite/runelite#18315]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Just noticed while opening the world hopper that the worlds list will scale on size to fill empty space. (example screenshots added)

As well as, skill total worlds not being filtered out of the list with only "Normal" worlds selected in the list.

### Screenshots or videos

Skill total worlds not filtered out, and strange scaling issue.
![1](https://github.com/user-attachments/assets/2a86121c-2819-43cb-bc10-ab618c9b9629)

Test in master by Zom, same issue
![master 2](https://github.com/user-attachments/assets/58e2c818-500e-462d-adbc-d1aa1139995b)

### RuneLite version

Release
RL Version: 1.10.37.2
Launcher Version: 2.7.1

Master
RL Version: 1.10.38-SNAPSHOT
Launcher Version: unknown (tested by zom)

### Logs

[client.log](https://github.com/user-attachments/files/17117681/client.log)
[launcher.log](https://github.com/user-attachments/files/17117682/launcher.log)

**Comment by MosheBenZacharia** [comment]
the skill total worlds being included in 'normal' is expected. 

the scaling to fill issue is probably related to this which just got merged: https://github.com/runelite/runelite/pull/16290

**Comment by YvesW** [comment]
Reverting 3ea4ba67656e44f55c15b2324b9aea6fa0e112a6 fixes the scaling issue.

**Comment by Adam-** [comment]
The commit causing this was reverted bbb54ae8cc36ffb4f993e6284bf774154ff94e85
