### ISSUE TITLE
Food and potions from Moons of Peril do not show HP/prayer restore in the status bar

### ISSUE THREAD

**Issue by joshi-sh** [runelite/runelite#18310]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Moonlight Potions from Neypotzli (Moons of Peril) can restore prayer, but this does not show in the prayer status bar. Same with Bream fish and Moss lizards for the HP bar

### RuneLite version

Runelite version: 1.10.37.2
Launcher version: 2.7.1

**Comment by YvesW** [comment]
Relevant PR: https://github.com/runelite/runelite/pull/17607

**Comment by YvesW** [comment]
Added in https://github.com/runelite/runelite/commit/a12fec482e34693926006473d80846389b3ca51e, https://github.com/runelite/runelite/commit/d6001c3f6f8a10b505622ca1e4b6ed6294e3e607, https://github.com/runelite/runelite/commit/e791d0854b3d36371ed371830b4a60488fc2f083
