### ISSUE TITLE
Menu entry swapper submenu for Construction cape missing new teleport

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#18319]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Varlamore part 2 added a new PoH portal in Aldarin, which is on the Construction cape teleport menu but not the submenu.

### Screenshots or videos

![2024-09-25-03-29-18](https://github.com/user-attachments/assets/158b010a-71dd-4e34-9dac-f3aa1cffcef0)
![2024-09-25-03-29-12](https://github.com/user-attachments/assets/ebd44c7c-e011-4410-81ba-ee319d455055)

### RuneLite version

RuneLite version 1.10.37.2
Launcher version 2.6.10

**Comment by Adam-** [comment]
fixed in b7f9c74b91d467fa900a9474d14e470d5e2b1f15
