### ISSUE TITLE
Enter Key Not Working in "X Amount" Interface After Latest RuneLite Update (Mac)

### ISSUE THREAD

**Issue by acastropohl** [runelite/runelite#18324]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

sonoma 14.4.1

### Bug description

Hi,

Since today's update (09/25/24) update, I’ve encountered an issue on my Mac where the Enter key no longer works when trying to confirm custom amounts in the "X amount" interface (for example, when withdrawing items from the bank or charging weapons). I can type the custom amount, but pressing Enter does nothing. This problem is limited to these interfaces, as the Enter key works fine in chat and other parts of the game.

Steps to reproduce:

Open the "X amount" interface (e.g., withdrawing items from the bank or charging a weapon).
Type in a custom number.
Press Enter, but the interface doesn’t respond (only manual clicking works).
The issue only started after today’s update, as I was able to use the Enter key without any problems yesterday. I’ve tried the following steps to troubleshoot:

Disabled plugins like Menu Entry Swapper.
Cleared RuneLite cache.
Checked my Mac's keyboard settings.
None of these fixed the issue. I’m using RuneLite on a Mac, and the problem seems to be update-related. Any help or insight would be appreciated!

Thank you!

### RuneLite version

Runelite version: Version 2.5.0
Launcher version: Version 1.2.0 (1.2.0)

**Comment by werenall** [comment]
Same happens for answering clues and setting custom price at ge

**Comment by cdfisher** [comment]
This is probably an issue with "GE Calc" from the Plugin Hub, as several people have reported that plugin causing this issue today. Try disabling it and restarting your client.

**Comment by woodenscalpel** [comment]
> This is probably an issue with "GE Calc" from the Plugin Hub, as several people have reported that plugin causing this issue today. Try disabling it and restarting your client.

I was having the same issue, and can confirm that disabling "ge calc" fixed it.

**Comment by cman8396** [comment]
> > This is probably an issue with "GE Calc" from the Plugin Hub, as several people have reported that plugin causing this issue today. Try disabling it and restarting your client.
> 
> I was having the same issue, and can confirm that disabling "ge calc" fixed it.

I can confirm this is an issue with the method I use to set the quantity in the chatbox. No fix yet. Looks like Decimal Prices plugin has the same issue.
