### ISSUE TITLE
Kourend Library plugin makes the Brimhaven Agility Arena arrow disappear

### ISSUE THREAD

**Issue by larsRikard** [runelite/runelite#18328]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The arrow indicating the correct Ticket dispenser will consistently disappear if you enable the Kourend Library plugin.

When the plugin stays on there is a big chance that the arrow will disappear, often after collecting the ticket but sometimes before. Sometimes the arrow never appears as well.

When the plugin stays off there is still a chance for the arrow to disappear, albeit very small. I'm thinking an additional plugin i have installed might also use the api for this arrow.

### Screenshots or videos

The arrow in question
![image](https://github.com/user-attachments/assets/1cdfc3a3-b8e1-4bf2-88b2-1ebbc6b9dfa4)

### RuneLite version

![image](https://github.com/user-attachments/assets/199ce694-a877-4b9d-af41-ac5fcd0353bb)

### Logs

[client.log](https://github.com/user-attachments/files/17138221/client.log)
[launcher.log](https://github.com/user-attachments/files/17138224/launcher.log)

**Comment by Adam-** [comment]
The commit causing this was reverted edc1ef0b54e6dfd05446e52f7dfeb6979b038981

**Comment by ConjureGanja** [comment]
Im having this issue as well, the no arrow showing up in the brimhaven agi arena... I can't for the life of me figure out what the reason is... Anyone have any suggestions?
