### ISSUE TITLE
Menu entry swapper

### ISSUE THREAD

**Issue by mmartinandersson** [runelite/runelite#18333]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The menu entry swapper used for having the "pay" option on farmers as the number 1 choice does no longer work. each time I log in the main option is set back to "trade" instead of pay.

### RuneLite version

Runelite Version: 1.10.38
Launcher version: 2.7.2

**Comment by raiyni** [comment]
Added in e3a2c3edd6f069b99ebdbac9776042cf994e38ce
