### ISSUE TITLE
Bank Tags Tabs overlays on top of new potion storage button making it hard to click

### ISSUE THREAD

**Issue by cloud-aspect** [runelite/runelite#18339]
### Type

Other

### Operating System

Windows

### OS Version

Windows 11

### Bug description

The new potion storage button in the bank menu is positioned in a way that the bank tags tabs overlay renders on top of it, making it hard to click.

You need to have enough tabs that stretch down to just above the incinerator button which is where the new potion storage button is. I have many tabs that even with a lot of vertical screen space it still renders above the button (see screen shots).

### Screenshots or videos

Bank Tags w/ use Tag Tabs on, resize mode on, potion storage unlocked.
1440p (2560x1440) screen size (window is stretched all the way vertically)
![image](https://github.com/user-attachments/assets/bab9d183-211b-47e9-8494-71c6b0abfeba)

Same but Bank Tags -> Tag Tabs off
![image](https://github.com/user-attachments/assets/0af4646d-f0d2-40cc-9b6c-51498df9bf27)

### RuneLite version

RuneLite Version: 1.10.38
Launcher Version: 2.7.1

**Comment by Adam-** [comment]
fixed in 34252a3267e4efd6e0eec373171784a351936dce
