### ISSUE TITLE
Ground Items displaying random items in colors I haven't set (Wrong Label, I haven't used GitHub before)

### ISSUE THREAD

**Issue by Tdude0406** [runelite/runelite#18358]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Was doing Perilous Moons quest, and dropped the hammer given during the quest. For some reason, despite Ground Items being programed to hide items under a specific value, the hammer shows up on the ground in blue text. The only other item in my testing to do this are regular logs, which show up in red text. I reset the Ground Items plugin's settings, which did not solve the issue, and disabling the plugin removes the item text. A new plugin Profile does not have this issue.

### Screenshots or videos

My Default Profile, using the freshly reset Ground Items Plugin
![Bug 1](https://github.com/user-attachments/assets/d6e90e87-34f6-4bd8-885f-0b0d0820ca9b)
After Creating the brand new Profile the problem goes away
![Bug 2](https://github.com/user-attachments/assets/218d4cd2-0dd2-4b25-9cb6-6f13c8fe0508)

### RuneLite version

RuneLite Version: 1.10.38.1
Launcher Version: 2.6.4

**Comment by YvesW** [comment]
Shift + right click the item and set the color.

**Comment by Tdude0406** [comment]
I have 0 recollection of changing the color of these specific items, but that did solve the problem. Thanks
