### ISSUE TITLE
Item stats plugin does not show restore amount for moonlight moth mixes

### ISSUE THREAD

**Issue by Ironarmies** [runelite/runelite#18377]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 11

### Bug description

When you hover over the mix, it does not show the restore amount as is used to do

### Screenshots or videos

![image](https://github.com/user-attachments/assets/2cab5191-a6c6-4521-ba89-00ac22261599)

### RuneLite version

![image](https://github.com/user-attachments/assets/e786730b-1ee7-4091-b817-01ecc100e64c)

**Comment by Ironarmies** [comment]
![image](https://github.com/user-attachments/assets/c990a2fc-2ffb-499a-8257-c0dc39ec699e)

**Comment by cdfisher** [comment]
#17607 , which is pending review, would implement this.

**Comment by YvesW** [comment]
Added in https://github.com/runelite/runelite/commit/bfe21caa2f6592b1ecc75977dc5ffddc0b3f82f3
