### ISSUE TITLE
Poison and Prayer Indicator + clearer indicator

### ISSUE THREAD

**Issue by nmq12** [runelite/runelite#1838]
It would be nice to have a prayer indicator on which prayer is being used, and a poison indicator to see poison damage.

Also, the current indicator for boost information is very crowed and hard to see. (Especially the drained stats). Maybe make picture size smaller or have a border around the numbers.

Thanks!

**Comment by deathbeam** [comment]
I think we have issues open already for prayer and poison indicators. And for the 3rd thing, that is very subjective, but we plan to add resizing support for overlays. What if you change the boosts indicators to use info boxes in settings?

**Comment by nmq12** [comment]
I've not use the info boxes but I switched back to the default boost info with the name and number since the numbers are easier to look at.
