### ISSUE TITLE
Request focus "force" does not work when RuneLite is minimized

### ISSUE THREAD

**Issue by oschei** [runelite/runelite#18381]
### Type

Incorrect behavior

### Operating System

MacOS

### OS Version

MacOS Monterey (12.7.5)

### Bug description

The request focus notification setting "force" only works when the RuneLite window is either not focused or hidden (command+H). If RuneLite is minimized, it doesn't work. Adding the below code snippet in `requestForeground()` of `runelite-client/src/main/java/net/runelite/client/util/OSXUtil.java` resolves the issue (i.e. the forced notification retrieves the minimized window), however I'm not sure of the broader implications of this change on other parts of the code.

```
if (frame.getState() == Frame.ICONIFIED)
{
    frame.setState(Frame.NORMAL);
    log.debug("Restored minimized window to normal state");
}
```

### RuneLite version

RuneLite version: 1.10.38.1
Launcher version: 2.7.2

**Comment by Adam-** [comment]
It would be best to put a setState() inside of forceFocus() I think. The tray icon focus code has this which is similar:

```java
				if (OSType.getOSType() == OSType.MacOS && !frame.isFocused())
				{
					// On macOS, frame.setVisible(true) only restores focus when the visibility was previously false.
					// The frame's visibility is not set to false when the window loses focus, so we set it manually.
					// Additionally, in order to bring the window to the foreground,
					// frame.setVisible(true) calls CPlatformWindow::nativePushNSWindowToFront.
					// However, this native method is not called with activateIgnoringOtherApps:YES,
					// so any other active window will prevent our window from being brought to the front.
					// To work around this, we use our macOS-specific requestForeground().
					frame.setVisible(false);
					OSXUtil.requestForeground();
				}
				frame.setVisible(true);
				frame.setState(Frame.NORMAL); // Restore
```

but I am not sure how much of this is necessary. In particular it seems to think that flipping isVisible is also required
