### ISSUE TITLE
Right click attack NPC option by choice.

### ISSUE THREAD

**Issue by CaraPis** [runelite/runelite#1839]
Hello,
I was thinking if it would be possible to create a plugin like the NPC Indicators plugin where you would be able to enter the name of the NPCs you would like to right click attack(something like this: https://i.imgur.com/6T1SZ98.png)? I think this would be pretty useful for Abyssal Sire.

Regards, Cara

**Comment by deathbeam** [comment]
Based on discord discussion we dont want to implement something like this
