### ISSUE TITLE
[Low Detail] Low detail mode no longer works for most of Hallowed Sepulchre

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#18404]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Arch Linux

### Bug description

Low detail mode no longer removes floor decorations, ground objects, etc. for any of the Hallowed Sepulchre except for small parts of the first floor. I can reproduce this with RuneLite running in safe mode. 
It used to remove all of them - see [he box jonge's video](https://www.youtube.com/watch?v=V54QceFYzZU) for comparison.

### Screenshots or videos

Floor 1, Low detail setting disabled
![2024-10-07-23-10-24](https://github.com/user-attachments/assets/bfa1dfd9-f69f-4869-b96d-51eb715815a6)
Floor 1, Low detail setting enabled
![2024-10-07-23-10-30](https://github.com/user-attachments/assets/9e8fb5a2-87dc-4772-8024-a3bbffcacebb)
Floor 2, Low detail setting disabled
![2024-10-07-23-11-19](https://github.com/user-attachments/assets/9ec0833e-74b7-4fde-8201-97f1a52e7027)
Floor 2, Low detail setting enabled
![2024-10-07-23-11-25](https://github.com/user-attachments/assets/683d259a-29aa-421e-a9b3-98a3c56e0699)

### RuneLite version

RuneLite version: 1.10.39
Launcher version: 2.6.10

**Comment by Felanbird** [comment]
Jagex changed the floors here and in Verzik's room, so low detail no longer works in these places.

Using `Ground Object Hider` from the hub has been the workaround people have been doing since this was changed a month ago.

cc: https://github.com/runelite/runelite/discussions/18250#discussioncomment-10593711

**Comment by fuzxi** [comment]
Cheers. Here's a list of Sepulchre ground object IDs in case anyone else finds it useful (doesn't include the lightning tiles). The first floor is weird in that some sections will look how they used to with low detail mode and some will look pure black, which is how all the other floors look.
<Details>
<Summary>List</Summary>
38142,38141,38135,38149,38150,38146,38143,38145,38132,38133,38136,38137,38131,38129,38138,38139,38140,38147,38391,38389,38390,38148,38163,38164,38151,38169,38167,38168,38165,38154,38155,38170,38159,38153,38161,38162,38160,38158,38156,38171,38172,38388,38386,38387,38157,38185,38197,38202,38395,38396,38201,38397,38198,38199,38205,38206,38253,38248,38252,38240,38254,38247,38250,38244,38246,38245,38225,38221,38222,38394,38392,38393,38229,38230,38223,38226,38217,38211,38209,38213,38216,38215,38212,38219,38218,38187,38189,38188,38203,38251,38227,38653,38228,38220,38242,38236,38233,38235,38234,38214,38283,38296,38295,38406,38407,38300,38297,38285,38405,38299,38291,38307,38319,38327,38316,38309,38320,38324,38321,38402,38323,38404,38403,38312,38313,38314,38343,38347,38344,38333,38334,38331,38350,38346,38398,38399,38400,38351,38345,38337,38335,38332,38341,38338,38339,38134,38194,38196,38204,38328

</Details>
