### ISSUE TITLE
Medium Clue Scroll Varlamore

### ISSUE THREAD

**Issue by RyanNaughty** [runelite/runelite#18415]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

10.0.22631 Build 22631

### Bug description

Medium Clue Scroll step for Varlamore Twilight Temple mine states to use "Jump for Joy" when emote is "Bow"

### RuneLite version

1.10.40
2.6.7

**Comment by YvesW** [comment]
Relevant PR: https://github.com/runelite/runelite/pull/18401

**Comment by YvesW** [comment]
Added in https://github.com/runelite/runelite/commit/5a919328e29450e5f39e23399335be65199e8b27
