### ISSUE TITLE
XP drops gone

### ISSUE THREAD

**Issue by awess02** [runelite/runelite#18416]
### Type

Crash or hang

### Operating System

Windows

### OS Version

windows 10

### Bug description

All of a sudden I cannot get any XP drops to show up. I tried resetting my computer and starting from scratch on Runelite but nothing seems to bring them back. I have adjusted all of the setting for XP drops and Customizable XP drops and still nothing.

### RuneLite version

1.10.39
2.7.2

**Comment by Alexsuperfly** [comment]
click the xp button by the minimap
