### ISSUE TITLE
Show ground item if it is either >HA value OR >GE value

### ISSUE THREAD

**Issue by inewman** [runelite/runelite#1841]
When slaying, I like to pick up any items that can net me a profit. Therefore, I pick up any items that are above 1000 GE value. Additionally, I carry alch runes, so if I see an item that high alchs for at least the cost of a high alch spell (let's say ~250 GP), then I pick it up and alch it. I would think that RuneLite should be able to show ground item text for all the items I want to pick up by selecting a GE value of 1000 and an HA value of 250.

Currently, the GroundItemsOverlay plugin decides not to draw the text if the value is less than GE value OR less than HA value. This means that it will only draw the text if the item's GE value is more than 1000 AND the item's HA value is more than 250.

There a few notable examples, primarily with herbs and potions, where the HA value is less than 250 but the GE value is more than 1000. For example, a Ranarr weed has values of HA=15, GE=7500.

I feel RuneLite should offer the option to draw items if either value is greater than the minimum. Honestly, I think it should be the default (because when are HA and GE prices ever compared in the context of items found on the ground?), but the option should be there regardless of what the default is.

**Comment by deathbeam** [comment]
I believe my PR #1213 will fix this, you can read through on what it does and confirm/deny.

**Comment by inewman** [comment]
Ah, yeah, it does. Cool, thanks! Feel free to close.

**Comment by deathbeam** [comment]
No, this is still valid, that PR is still open and needs review :d
