### ISSUE TITLE
High Alch value on over while in item selection.

### ISSUE THREAD

**Issue by mrshlll** [runelite/runelite#1842]
Title.

**Comment by rherms** [comment]
Maybe do like Konduit and while you hold down the "alt" key it shows high alch value of items?

**Comment by Infinitay** [comment]
I believe we already have this, look at the Item Prices plugin, however I believe there isn't functionality to hold alt to view prices, I think its either always on/off

**Comment by ajbinky** [comment]
Yes, it is already implemented. Just be sure "Hide Tooltips on Inventory Items" is unchecked in the config.

**Comment by mrshlll** [comment]
Killer, thank you! Loving the client, finding new features every day :) Got
an ETA on farm timers?

On Apr 25, 2018 12:01 AM, "Andrew Behncke" <notifications@github.com> wrote:

Yes, it is already implemented. Just be sure "Hide Tooltips on Inventory
Items" is unchecked in the config.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/runelite/runelite/issues/1842#issuecomment-384154123>,
or mute the thread
