### ISSUE TITLE
Medium clue - Arrow hints not following some NPCs

### ISSUE THREAD

**Issue by MalakaJones** [runelite/runelite#1843]
Instead of following the NPC, Edmond's arrow is pointing toward the ground as if it was a dig clue

![image](https://user-images.githubusercontent.com/15826583/39140453-9baee070-46f2-11e8-9a5c-12aa6c641182.png)
![image](https://user-images.githubusercontent.com/15826583/39140582-073b02a6-46f3-11e8-8947-345e06fad97e.png)

**Comment by MalakaJones** [comment]
Here's for Gabooty medium clue

![image](https://user-images.githubusercontent.com/15826583/39141996-65c33f38-46f7-11e8-9d5b-414f11aabf54.png)
![image](https://user-images.githubusercontent.com/15826583/39142003-6ccbc192-46f7-11e8-9617-279c985ffdba.png)

**Comment by MalakaJones** [comment]
Here's Captain Khaled's clue in Kourend

![image](https://user-images.githubusercontent.com/15826583/39146291-6172934a-4704-11e8-986b-49c675de90e3.png)
![image](https://user-images.githubusercontent.com/15826583/39146313-70f3636c-4704-11e8-9e03-3934549bc246.png)

**Comment by sethtroll** [comment]
I am pretty sure cff46bb3d891eb0109882f80d22f2bcfe72da08f has fixed this. I can at least confirm that the last picture you posted is fixed now because of said commit.

**Comment by MalakaJones** [comment]
I can confirm that this issue if fixed for weeks now. (Forgot to take a picture of Gabooty...)

![edmond](https://user-images.githubusercontent.com/15826583/40581507-8af80504-6128-11e8-8cef-fe8b187c1fb8.PNG)
![khaled](https://user-images.githubusercontent.com/15826583/40581508-8ca41ca8-6128-11e8-99eb-adb684514d15.PNG)

**Comment by MESLewis** [comment]
@MalakaJones if this issue is fixed you can close it
