### ISSUE TITLE
Extended anti-venom+ not showing doses with Item Charges plugin

### ISSUE THREAD

**Issue by williamvd2** [runelite/runelite#18437]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Item Charges plugin shows a number on the inventory item for the amount of doses that are left in the potion. However, this number is not visible for the newly added extended anti-venom+

### Screenshots or videos

![image](https://github.com/user-attachments/assets/2d1c2a91-1dc7-47a2-8dc2-c915961b41bf)

### RuneLite version

RL 1.10.40 - launcher version 2.6.9 - os revision 225

**Comment by Felanbird** [comment]
Looks like this was added in f8dd6f5fefbdf1360f534f08451e7c50c16a8401 so it will be available whenever the next RuneLite version comes out
