### ISSUE TITLE
Incorrect cursor position on screen

### ISSUE THREAD

**Issue by hballington12** [runelite/runelite#18439]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Ubuntu 24.04

### Bug description

Since today's update (16/10/24), the cursor position on screen does not correspond properly to the click location in the client. It appears to be offset in the y direction by some small (but significant) amount.
![output](https://github.com/user-attachments/assets/ffe7cf1e-9252-4089-8a13-cd26bb677939)

Tile markers also appear to be bugged, which now m
ark the tile hovered by the current cursor position, rather than the tile the was hovered when the right-click menu was opened.
![output](https://github.com/user-attachments/assets/04230eff-5080-43f3-816f-1dea5b49809c)

The issue is repeatable regardless of whether custom window chrome is enabled and is reproducible in safe mode.

### RuneLite version

Runelite version: 1.10.41
Launcher version: 2.7.2

**Comment by Adam-** [comment]
We see an issue with the mark tile option selecting the wrong tile, but we are unable to find any issue with walking selecting the wrong tiles. Do you have a more clear example of that being broken?

**Comment by Adam-** [comment]
We're able to confirm an issue with vanilla in fixed mode selecting the wrong tiles when walking.

**Comment by hballington12** [comment]
This now appears to be fixed on my end.
