### ISSUE TITLE
Core Layouts not compatible with menu entry swapper custom ui swaps.

### ISSUE THREAD

**Issue by geheur** [runelite/runelite#18447]
When in a core layouts tag tab, you cannot see the submenus when shift-clicking an item nor will the swaps work. This is likely because the Widget.getActions returns null.

### RuneLite version

1.10.42-SNAPSHOT intellij

**Comment by Adam-** [comment]
fixed in 6ac0793e50fe28feb1a0fddcb241ae2b8e0109a1
