### ISSUE TITLE
Farming Payment

### ISSUE THREAD

**Issue by rosenbaum420** [runelite/runelite#18440]
### Type

Other

### Operating System

Windows

### OS Version

windows 10

### Bug description

Stopped showing when trees have payment protection, compost still shows

### Screenshots or videos

![RuneLite_Sk5G2Giy9P](https://github.com/user-attachments/assets/f8046c28-9a17-495a-b135-57937ef3dcbd)

### RuneLite version

Runelite: 1.10.41
Launcher: 2.7.1

**Comment by evilgenious448** [comment]
Yep, getting this issue also.

**Comment by coopermor** [comment]
This was fixed in cab0ed2f5ff8f5213b03c26973f8eae0bc94dd1f

**Comment by rosenbaum420** [comment]
That was 5 days ago. This happened after update today

**Comment by rosenbaum420** [comment]
My bad, that was meant for someone else that replied. Idk how email replies
work. They said it was fixed but was talking about an issue reported 5 days
ago not today

**Comment by abextm** [comment]
Jagex reverted the text back to what it was the week before last.
Refixed in 051dc222d34685ef0f08928918c940929d1720bc
