### ISSUE TITLE
Client not full screening after update. Also client chronically crashing.

### ISSUE THREAD

**Issue by Kwazix** [runelite/runelite#18444]
### Type

Crash or hang

### Operating System

Windows

### OS Version

W10 Home

### Bug description

Since todays update my client just keeps crashing about 10 seconds after opening, Restarting computer fixes it temporarily but then it starts again randomly. Also fullscreen is completely broken. Client says its fullscreen but its clearly not as i can see the windows border around the client aswell as a small line of my desktop at the bottom.

### Screenshots or videos

<img width="873" alt="runelitebroken" src="https://github.com/user-attachments/assets/6a5dec10-de43-4a56-acab-9f736bb2798b">

### RuneLite version

1.10.41.1
2.6.4

### Logs

[client.log](https://github.com/user-attachments/files/17403422/client.log)
[launcher.log](https://github.com/user-attachments/files/17403423/launcher.log)
[jvm_crash_pid_6848_r.log](https://github.com/user-attachments/files/17403424/jvm_crash_pid_6848_r.log)

**Comment by Kwazix** [comment]
Also discovered that my bank now only shows 3 tab tabs instead of 4, but when i open the sidebar menu, it corrects to 4 while open. but then back to 3 if closed.

**Comment by Felanbird** [comment]
Did you try safe mode mentioned at the top of the bug report template?

**Comment by Kwazix** [comment]
Isnt that in regard to the issue being caused by a newly installed plugin or is it also possible from a plugin being updated?

**Comment by Felanbird** [comment]
Yes plugins get updates, it says nothing about when to/not to check safe mode, it just says to please check safe mode before you open an issue.

**Comment by Kwazix** [comment]
Crashing seems to stop in safe mode which i suppose means its plugin related, However all display issues persist in safe mode.
