### ISSUE TITLE
Tile not marking in correct place,

### ISSUE THREAD

**Issue by DaFuxYaGonnaDo** [runelite/runelite#18441]
### Type

Crash or hang

### Operating System

None

### OS Version

Windows 10

### Bug description

Tile isn't marking in correct location and when I click unmark it marks another tile in the location of where the scroll menu and 'unmark tile' text is

### RuneLite version

1.10.41
Rev 226
Launcerh 2.7.1

**Comment by Bram91** [comment]
This is fixed in 1.10.41.1, restart your client.
