### ISSUE TITLE
Bank Tags not working all the time

### ISSUE THREAD

**Issue by Icelight123** [runelite/runelite#1845]
I have made bank tags for my Farming set and Master farmer thieving set with the names "Farm" and "Master". When I search "Farm it displays all of the items correctly but when I search "Master" it shows none of them. However when I search Tag: I can see both tags displayed correctly.

I have restarted Runelite twice and tried toggling bank tags off and on but the issue persists.

Thanks

**Comment by deathbeam** [comment]
Is this still an issue?

**Comment by Icelight123** [comment]
I do believe it has been fixed.
