### ISSUE TITLE
Medium clue - Some dig hints are misplaced

### ISSUE THREAD

**Issue by MalakaJones** [runelite/runelite#1846]
Instead of highlighting the crate in the center of the mining camp, the plugin creates a hint arrow for digging right next to it. I'm not sure if this is meant as a workaround but it's odd.

![mining_camp1](https://user-images.githubusercontent.com/15826583/39145550-1731efc6-4702-11e8-93b9-26cc8fe748ea.PNG)
![mining_camp2](https://user-images.githubusercontent.com/15826583/39145559-1afbbdbc-4702-11e8-875b-01a8fd886fd3.PNG)

**Comment by deathbeam** [comment]
Fixed in #2030
