### ISSUE TITLE
Clue Scroll plugin does not check jaw slot

### ISSUE THREAD

**Issue by Frosty-J** [runelite/runelite#18471]
### Type

Incorrect behavior

### Bug description

If the user's jaw slot is occupied, such as with a blue icon, "nothing at all" clue requirements will be marked as fulfilled by RuneLite. The game requires that this slot is empty, so players must first unequip it - the Chaos Elemental can help with this.

### Screenshots or videos

![panic](https://github.com/user-attachments/assets/587ce96d-c8c0-4871-af4f-5d24fa20af47)

(icon is not very visible under tile overlay - if you look closely, you will see a blue circle)

### RuneLite version

RuneLite version: 1.10.41.2
Launcher version: 2.6.8

### Logs

N/A

**Comment by Adam-** [comment]
The plugin checks the equipment inventory, not the appearance (which is where the "jaw slot" is), and the inventory doesn't have a jaw slot. I don't think this is really a RuneLite bug.

**Comment by Frosty-J** [comment]
Yes, I naïvely believe we could add `JAW(11)` to `EquipmentInventorySlot` then amend the `emptySlot()` calls to check it. But even if it is that simple, testing it might not be, as the icon smuggle (publicly known for years and Jagex doesn't seem to care) depends on letting your membership lapse. I got rid of mine to complete the clue and confirm the coordinates are correct.

**Comment by Adam-** [comment]
I was able to test it by just going into the soul war tutorial, it equips item 25217 in inventory slot 11

**Comment by Frosty-J** [comment]
While I don't think we need to concern ourselves with what is in the jaw slot, the item depends on your facial hair. Could be 25212 or 25213 to 25227; 25217 is clean-shaven.

**Comment by Adam-** [comment]
Ive added it in d827e82587b82810cee2c045f97479239c16a127 and 2667d8ee53e220e114ce1671af926924fa8926fa
