### ISSUE TITLE
[Clue Scroll] Clue incorrectly labeled as having a double agent

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#18474]
### Type

Incorrect behavior

### Operating System

None

### Bug description

The hard clue step 
> Yawn in the rogues' general store. Beware of double agents!
> Equip an adamant square shield, blue dragon vambraces and a rune pickaxe. 

previously had a double agent spawn, but this was silently changed at some point. The step no longer spawns a double agent and the plugin has not been updated to reflect this.

### RuneLite version

RuneLite version: 1.10.42
Launcher version: 2.6.10

**Comment by Felanbird** [comment]
If the clue text says a double agent will spawn, I think we should keep saying it will. If they change the text we'll have to update the clue anyway, if we make the change and they fix it, we'll have to change it back.

**Comment by Nightfirecat** [comment]
I'm fairly certain this clue, and all hard emote clues, still works in a way such that sometimes Uri will spawn without a double agent spawning. Unless the clue text has changed to not say a double agent will spawn, I don't think anything has changed and this is normal behavior.

**Comment by fuzxi** [comment]
I happened to get this exact step again and you're right, double agents only have a chance of spawning. Cheers!
