### ISSUE TITLE
idle notifier doesnt work when doing prayer in varlamore

### ISSUE THREAD

**Issue by rendragon4** [runelite/runelite#18475]
### Type

Incorrect behavior

### Operating System

None

### Bug description

it doesnt work when chiseling blessed bones into bone shards, or making sunfire wines, or using the libation bowl. it doesnt send any notifications at all even if they're configured. expected behaviour is having idle animation notifications enabled causes notifications to happen

https://github.com/runelite/runelite/pull/18210

### RuneLite version

1.10.42
2.7.2

**Comment by evilgenious448** [comment]
For the time being you can use the action progress plugin which has functionality to track actions you named such as: chiseling blessed bones into bone shards, or making sunfire wines (not sure about the use of libation bowl). It also has functionality to send notifications when finished.

**Comment by coopermor** [comment]
All of this has been added in #18210 but the PR has not been merged yet.

**Comment by cdfisher** [comment]
Added with d6fc25fb6b8b3a6a6bb4901bdcab62e3aef609fb
