### ISSUE TITLE
Right click still moves camera, even with the option disabled.

### ISSUE THREAD

**Issue by CthulhuInACan** [runelite/runelite#18484]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

With the Camera Plugin, Right click still moves the camera, even with the "Right click moves camera" option disabled.
Enabling "Right click menu blocks camera" fixes this, but this is still clearly incorrect behavior.

### RuneLite version

RuneLite Version: 1.10.41.1
Oldschool Version: Rev 226
Launcher Version: 2.7.2

**Comment by CthulhuInACan** [comment]
Yeah it works if you turn on right click menu blocks camera, so the issue isn't a big deal, it's just it doesn't really make sense for right click to still move the camera to when 'right click moves camera' is disabled, as in this config.
![image](https://github.com/user-attachments/assets/302ac1a0-2ed8-4575-87fc-37c6e4b5b0dc)

**Comment by lithream** [comment]
@CthulhuInACan I made a quick change that seems to have solved the issue. Do you mind checking this video I recorded and letting me know if this is the behaviour you had in mind? If so, I can PR my branch.

https://www.youtube.com/watch?v=lPNe3eYb_qk

**Comment by CthulhuInACan** [comment]
Yeah, that behaviour makes a lot more sense, thank you for the change! :)
