### ISSUE TITLE
Re-add Silver Sickle (b) in Menu Entry Swapper

### ISSUE THREAD

**Issue by vanzoest96** [runelite/runelite#1848]
This was in here a few days ago and now it's gone? Can it be added again?

**Comment by Adam-** [comment]
This was removed after we gained the ability to configure custom shift clicks, since you can just do that now. We are thinking of adding a permanent-shift click mode in #1556 which would address this.

**Comment by vanzoest96** [comment]
Just figured this out. Thank you.
