### ISSUE TITLE
Inventory is way too small to be able to play

### ISSUE THREAD

**Issue by metroburger82** [runelite/runelite#1849]
I'm not sure if I'm being an idiot and it's already in the settings, my resolution of my laptop is too big or there is something wrong but my inventory is way too small in full screen mode and the stretched mode on improved graphics is still pretty poor, even for Runescape. Is there any way to increase the size of my inventory and minimap whilst keeping the full screen size? Thanks

Stretched mode- https://imgur.com/a/4FHuHEj
Regular Full Screen- https://imgur.com/a/1zLat58

**Comment by Unmoon** [comment]
[10:48 PM] BOTRuneLite: Is your game window unusually small? If you downloaded RuneLite before April 22, try using the updated launcher: https://runelite.net/

**Comment by metroburger82** [comment]
thanks a lot
