### ISSUE TITLE
Bank Tags Extra _invsetup_ Tags Added Everywhere

### ISSUE THREAD

**Issue by vahnx** [runelite/runelite#18503]
### Type

Other

### Operating System

Windows

### OS Version

Windows 11

### Bug description

Not sure why but today I've noticed **all** my items with tags have a bunch of extra __invsetup_dhjudhd31234981_ in them.
See the attached screenshot.

### Screenshots or videos

![image](https://github.com/user-attachments/assets/0a38f04c-33f9-40b6-9cb5-fca54415b156)

### RuneLite version

RL: 1.10.43
Launcher: 2.7.1

**Comment by fuzxi** [comment]
This is a result of the hub plugin Inventory Setups migrating from using the hub plugin Bank Tag Layouts to the built-in Bank Tags plugins. It's not a bug, those items need those tags so Inventory Setups can filter them.

**Comment by vahnx** [comment]
> This is a result of the hub plugin Inventory Setups migrating from using the hub plugin Bank Tag Layouts to the built-in Bank Tags plugin. It's not a bug, those items need those tags so Inventory Setups can filter them.

I'm trying to understand as Inventory Setups did not add these tags until recently and worked just fine. I've been using both plugins now for well over a year and this did not happen until the past few weeks.

**Comment by fuzxi** [comment]
Because the migration happened a few days ago. Inventory Setups previously relied on Bank Tag Layouts for filtering. It's now been updated to rely on Bank Tags instead, which fixes some longstanding bugs and enables filtering potion storage, but also requires items to have visible tags.

**Comment by vahnx** [comment]
Gotcha, that makes more sense. They need to then make a scroll wheel as all these additional _invsetup_ tags make most of my items now unmodifiable as they eat up the entire tag text box (see original screenshot - out of space to type). Is there an alternate method to edit bank tags to make them usable again?

**Comment by fuzxi** [comment]
I agree with that, it's not very usable at the moment with long tags. As a workaround, you can make a new tag tab (big + button at the top left of the bank) with your desired tag, drag the items you want to tag into it, delete the tag tab, and choose to delete only the tab. Then the items will still have that tag applied. To delete the tag, make the tag tab again and delete, but choose to delete both the tab and tag.

**Comment by dillydill123** [comment]
Adam is adding a feature to hide tags, which inventory setups can use to make those tags not appear.

**Comment by Felanbird** [comment]
The above mentioned hide feature, was added in b53dd8355bb13047e20e841e44521cc708d97375 - and that update to `Bank Tags`, as well as the one for `Inventory Setups` are both available in the client, meaning these tags are no longer cluttering the `edit-tags` box
