### ISSUE TITLE
[Bank Tags] With layout enabled, item overlays in tag tabs do not match hovered items

### ISSUE THREAD

**Issue by fuzxi** [runelite/runelite#18501]
### Type

Incorrect behavior

### Operating System

None

### Bug description

Create a tag tab and add at least one item.
Right-click the tag tab and enable layout.
Open the tag tab.
With an item overlay plugin enabled, e.g. Item Prices, Item Stats, etc., hover over an item.
The overlay will match the item in that position in the second bank tab (not tag tab) instead of the item in the tag tab.

### Screenshots or videos

Layout disabled:
![2024-11-06-23-00-27](https://github.com/user-attachments/assets/b41a0f00-1563-46dc-9fe6-1a0a8f71da85)
Layout enabled:
![2024-11-06-23-00-51](https://github.com/user-attachments/assets/a8a9c79f-5b3e-486c-ab2c-72381e82b30b)
The first item in my second bank tab:
![2024-11-06-23-01-11](https://github.com/user-attachments/assets/63340f51-ce3f-49b7-9064-5adb18816286)

### RuneLite version

RuneLite version: 1.10.43
Launcher version: 2.6.10

**Comment by Adam-** [comment]
Are you still able to reproduce this? It looks ok to me:

![image](https://github.com/user-attachments/assets/0a565678-decf-4581-9297-a1fb99764d5b)

**Comment by Adam-** [comment]
I was able to reproduce this for item prices, but not item stats, as stated in your original post. I've fixed it in bc10954c3d9395a69311977d3ea7e313757ba019.

**Comment by fuzxi** [comment]
The issue I saw with Item Stats was that consumables would not show the correct stat changes, but I can no longer reproduce that. Thanks!
