### ISSUE TITLE
Motherload mine 

### ISSUE THREAD

**Issue by Chris2me7** [runelite/runelite#18507]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

windows 10 

### Bug description

The ore bag overlay isent working when deposition ore into hopper in the mother 
load mine. 

### RuneLite version

1.10.43

**Comment by Felanbird** [comment]
This was fixed in [this weeks game update](https://secure.runescape.com/m=news/guardians-of-the-rift-changes-out-now?oldschool=1)
> After depositing Paydirt into the hopper in Motherlode Mine, the Sack's counter now correctly updates to display how many ores you've deposited.
