### ISSUE TITLE
Highlight sacred eel fishing spot.

### ISSUE THREAD

**Issue by Nithe** [runelite/runelite#1852]
Both on the tile and on minimap, just like the rest of the fishingspots

**Comment by iinc** [comment]
dupe #1354

**Comment by RobertLeeMich** [comment]
This is still an issue, the spots show up but then they stop showing up until I relog. They show up for anywhere between 5-10 minutes after that and then disappear again.

**Comment by Felanbird** [comment]
> This is still an issue, the spots show up but then they stop showing up until I relog. They show up for anywhere between 5-10 minutes after that and then disappear again.

This is not a post about an issue, this was the request to add the feature to highlight the fishing spots. 
If you're having a problem you'll need to follow the issue template [here](https://github.com/runelite/runelite/issues/new?assignees=&labels=needs-triage&projects=&template=bug-issue.yml).
