### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by t0msk** [runelite/runelite#18534]
### Type

Incorrect behavior

### Operating System

Linux

### OS Version

Arch Linux

### Bug description

I tried RuneLite flatpak version, even AppImage version, issue is the same I have no sound at all, no effect, no music, nothing :( sound in official OSRS client works just fine

My specs:

Vulkan support: YES
Esync support: YES
Fsync support: YES
Wine installed: YES
Gamescope: YES
Mangohud: YES
Gamemode: YES
Steam: YES
In Flatpak: NO
[System]
OS: Arch Linux rolling n/a
Arch: x86_64
Kernel: 6.11.6-zen1-1-zen
Desktop: GNOME
Display Server: wayland
[CPU]
Vendor: AuthenticAMD
Model: AMD Ryzen 5 4500 6-Core Processor
Physical cores: 6
Logical cores: 12
[Memory]
RAM: 31.1 GB
Swap: 32.0 GB
[Graphics]
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
OpenGL Version: 4.6.0 NVIDIA 565.57.01
OpenGL Core: 4.6.0 NVIDIA 565.57.01
OpenGL ES: OpenGL ES 3.2 NVIDIA 565.57.01
Vulkan Version: 1.3.295
Vulkan Drivers: NVIDIA GeForce GTX 1060 6GB (1.3.289)

### RuneLite version

Runelite: 1.10.43
Launcher: 2.7.2

### Logs

Client: https://pastebin.com/raw/vexLAKQ6
Launcher: https://pastebin.com/raw/Mv8V7zPH

**Comment by YvesW** [comment]
Try installing ``pipewire-alsa`` and rebooting.

**Comment by t0msk** [comment]
Already have:

```
warning: pipewire-alsa-1:1.2.6-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) pipewire-alsa-1:1.2.6-1

Total Installed Size:  0.00 MiB
Net Upgrade Size:      0.00 MiB
```

**Comment by t0msk** [comment]
> Download the jar.
> 
> Follow these instructions: https://bugs.launchpad.net/raspbian/+bug/1980601

okay this fixed solution for java version, is known why it doesnt work for app image version or for flatpak version or for AUR version? :)

**Comment by DominickCobb-rs** [comment]
Flatpak and Appimage package their own versions of Java. For the flatpak version you'd probably have to modify this in the files of the flatpak itself. You'd have to ask someone more knowledgeable that me about the AppImage. The .jar works fine though.

**Comment by t0msk** [comment]
okay so problem is in Java? I mean, is possible to release RuneLite fix which will solve that thing that you dont have to set these parameters? something like fallback values? like use this as it is for now, and if it is not found or something, use these parameters?

**Comment by DominickCobb-rs** [comment]
Couldn't tell you where the problem is. The way it reads to me is users on Windows/Mac have no sound issues, and users on Linux do. Sounds like a Linux problem to me.

**Comment by t0msk** [comment]
okay thank you :)
