### ISSUE TITLE
Side bar glitches out

### ISSUE THREAD

**Issue by fannylipz** [runelite/runelite#1853]
Hi guy's, had this issue on osbuddy before, after a while of the client being open the side bar starts glitching, it's weird i cant no longer see whatever tab im on, then if i click another tab i can start seeing overlaying images of the others tabs etc.

**Comment by sethtroll** [comment]
When did you download runelite? We pushed a fix for this in the launcher yesterday that should have fixed this. I would re-install the launcher and see if that fixes your issue.

**Comment by fannylipz** [comment]
I'll give that a try, I installed it yesterday lunchtime (gmt) :) Thanks for the reply will let u know  h ow I get on .

**Comment by deathbeam** [comment]
Fixed in launcher/launcher#10
