### ISSUE TITLE
GameObject LocalState

### ISSUE THREAD

**Issue by tr33s** [runelite/runelite#1854]
We need access to a GameObject's LocalState. 

The LocalState is the current state of the object, which takes into account instances, as well as transformed npcs (e.g. an npc modified during a quest).

Specifically, I would like to make an Abyss plugin that requires the local state of the obstacles (although the Abyss itself is not a per-player instance, the obstacles are).

Related:
#1755 
#1572

**Comment by abextm** [comment]
This has been accessible since before this issue was created.
