### ISSUE TITLE
Remove dead NPC menus: Abyssal creatures cannot be interacted with afterwards

### ISSUE THREAD

**Issue by JCTKhuu** [runelite/runelite#18588]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Windows 10

### Bug description

Menu Entry Swapper setting "Remove dead NPC menus" resulting in NPCs in the Abyssal Area to no longer be attackable (no context actions at all) once killed.

If you autoretaliate onto one, once their HP changes they display menu options again.
Tested on all creatures in the Abyssal Area minus the Abyssal Demons.

Perhaps a result of how quickly the respawn? (Entirely a guess)

### Screenshots or videos

![image](https://github.com/user-attachments/assets/78432e15-04cd-454e-999d-38797bfb476f)
(This image shows all context actions beside shift click actions have disappeared)

### RuneLite version

Runelite version: 1.10.45
Launcher version: 2.6.8

**Comment by JCTKhuu** [comment]
Potentially linked, potentially independant: killing these creatures do not result in drops displaying in the loot tracker

**Comment by xDemoN** [comment]
Did you test this on main? I believe respawn is increased during Leagues
