### ISSUE TITLE
Menu Entry Swapper 'Teleport submenus' doesn't work with Xeric's talisman

### ISSUE THREAD

**Issue by Ali-Jasim** [runelite/runelite#18593]
### Type

Incorrect behavior

### Operating System

Windows

### OS Version

Winsows 10

### Bug description

Menu Entry Swapper 'Teleport submenus' doesn't work with Xeric's talisman

### RuneLite version

Runelite Version: 1.10.45

Launcher Version: 2.7,1

**Comment by Felanbird** [comment]
This is intentional, the rule change allowing us to add the `Teleport submenus` setting, was worded specifically for only achievement capes.
