### ISSUE TITLE
QoL - Add Dwarven Rock Cake to Menu Entry Swapper

### ISSUE THREAD

**Issue by zlshames** [runelite/runelite#1860]
It would be awesome if we can swap the eat and guzzle options for Dwarven Rock Cakes. Would reduce the number of right clicks I need when trying to get to 1 HP for NMZ (dharoks)

**Comment by Kamielvf** [comment]
You can change its shift-click to guzzle and then shift click the item. #1556 would allow you to change this to first click but its not added yet.

**Comment by zlshames** [comment]
How do I activate the configuration for the custom shift click? I have it enabled in the Menu Entry Swapper config, but I don't see it on any items

**Comment by Kamielvf** [comment]
Like this
![preview](https://puu.sh/zVEcD/aff42db5c7.gif)

**Comment by Kmtfwtm** [comment]
Left click guzzle is on Nmz Utilities on the plugin hub (:

**Comment by Hydrox6** [comment]
Now that configs can have sections, we don't have to worry as much about there being an obscene amount of options in the config, so this could be added.
