### ISSUE TITLE
Plug-in profile missing all plug-ins

### ISSUE THREAD

**Issue by natehelmick** [runelite/runelite#18606]
### Type

Incorrect behavior

### Operating System

Windows

### Bug description

Logged in this morning after no having any issues yesterday, and all my plug-in icons on the right bar were missing aside from the defaults that runelite comes with. I checked my profiles and there wasnt an incorrect one selected. I also tried importing my profile from my laptop which does not have this issue and it had the same issue. It seems the plug-ins are still downloaded, I just cant see them. For example, if I search the "quest helper" plugin on plugin hub, it shows as installed, but if I go to my plugin settings it isnt there.

### RuneLite version

Runelite Versions 1.10.46.1
Launcher version 2.7.1

**Comment by cdfisher** [comment]
Follow the instructions [here](https://github.com/runelite/runelite/wiki/FAQ#my-plugins-are-gone-or-my-config-profile-is-missing) carefully and you should be able to re-import the missing profile.

**Comment by natehelmick** [comment]
Yes I tried all of the profiles that were there, both in /profiles2 and the email under /profiles

**Comment by natehelmick** [comment]
Well, I fixed it by deleting the entire users/.runelite folder, relaunching through the jagex launcher, logging in to my runelite account, then one of the profiles that showed up had everything.
