### ISSUE TITLE
Shift Click Additions

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1867]
-Deposit all in Bank interface
-Withdraw all in Bank interface
-Deposit all in raids chest
-Withdraw all in Raids Chest

Just some qol stuffs

**Comment by Fryslan** [comment]
Won't this be to OP?

**Comment by Kamielvf** [comment]
This won't be added, see [this](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features)

**Comment by Reasel** [comment]
To piggy back off this, Jagex _might_ implement this on their own when mobile drops, until then it is too strong.

**Comment by Kamielvf** [comment]
I would assume nothing from mobile will be done on desktop at the same release time. If they implement it that would be the best because I feel like this would push certain boundaries.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
