### ISSUE TITLE
Gathering Skill Overlays only show up if you have the required items on you

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#1868]
Would be nice if you could have the overlays for fishing, mining spots and any others to only show up if you have the tools either on you or in your inventory

**Comment by chsami** [comment]
This might be confusing for soms players.

Op di 24 apr. 2018 10:16 schreef Stickaplex <notifications@github.com>:

**Comment by Stickaplex** [comment]
Care to explain?

**Comment by deathbeam** [comment]
This was already implemented
