### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by TheArbalist** [runelite/runelite#1873]
Could there be an option to play a sound, rather than using the OS notifications?
Currently, any notification will cause the RuneLite window to request focus and this is extremely undesirable if you're using another application in the foreground. This has gotten me killed a few times, playing other games in the foreground, because RuneLite will steal focus and cause my inputs to no longer be registered.

**Comment by deathbeam** [comment]
There is actually already such option, you can disable "Request windows focus", "Send tray notifications" and just keep the "beep" option on. In the 'RuneLite' settings.

**Comment by Kamielvf** [comment]
![image](https://user-images.githubusercontent.com/35824069/39179259-25dfba82-47b4-11e8-9422-b70e75a34fc9.png)
in runelite settings would fix your focus issue i assume, as for the sound that is valid.

**Comment by TheArbalist** [comment]
Disabling "Request focus on notification" does not work. I've had it disabled the entire time I've used the client, but it still onfocuses other games when the notification activates.

**Comment by deathbeam** [comment]
That is probably also behaviour of the OS notification itself. What if you try to keep only the sound enabled and disable tray notification?

**Comment by TheArbalist** [comment]
I'll test it in a while, currently in the middle of an NMZ session on Konduit.

**Comment by vwboy** [comment]
I've tested this on macOs, and disabling "focus request" does indeed work. Ill test later on windows 10.

**Comment by chsami** [comment]
Why konduit?

Op di 24 apr. 2018 11:43 schreef TheArbalist <notifications@github.com>:

**Comment by TheArbalist** [comment]
>Why konduit?

Been experiencing unexplained disconnections specifically on RuneLite, but other clients don't have this issue for me.

**Comment by TheArbalist** [comment]
>What if you try to keep only the sound enabled and disable tray notification?

That seems to have worked.
