### ISSUE TITLE
Client size stays reduced after opening side panels.

### ISSUE THREAD

**Issue by RomainEmpire** [runelite/runelite#1874]
When opening any of the side panels on resizeable mode, the client size is reduced to make up for the side panel opening. However, when closing the side panel it doesn't go back to the previous size unless it's manually changed in the settings again. Previous behavior didn't have the game client shrinking at all. This still happens with the client size locked option on.

![bug1](https://user-images.githubusercontent.com/38688811/39181470-1b192664-47ba-11e8-8b62-0e190ab87a55.JPG)
![bug2](https://user-images.githubusercontent.com/38688811/39181478-1e3ff494-47ba-11e8-9b60-dcb645b26fa8.JPG)
![bug3](https://user-images.githubusercontent.com/38688811/39181485-22190c18-47ba-11e8-8021-b090e3e76956.JPG)

**Comment by Adam-** [comment]
Fixed in #1977
