### ISSUE TITLE
Clue Scroll Messages

### ISSUE THREAD

**Issue by AzureLight** [runelite/runelite#1882]
I noticed when doing a clue scroll that the tips use US flooring convention while the game/UK uses a different convention. Would it be possible to have an option added to swap from US to UK convention at will (specifically, the Wizard Traiborn medium clue instructed you to go to the 2nd floor whereas in the UK we call it the 1st floor)?

**Comment by jpabeem** [comment]
I can relate, maybe just use the British notation everywhere? See also OSRS wiki's [styleguide.](http://oldschoolrunescape.wikia.com/wiki/RuneScape:Style_guide#Floor_numbering)

**Comment by jorisrs** [comment]
I suggest adding a locale option to the client in general so it will affect any plugin that makes use of it.

**Comment by deathbeam** [comment]
Looks like this was fixed in https://github.com/runelite/runelite/pull/2244 . We should not add toggles and just follow the game naming convention
