### ISSUE TITLE
Entity respawn timer

### ISSUE THREAD

**Issue by SakuraTheSky** [runelite/runelite#1888]
Respawn timer for mobs when you tag them would be amazing.

**Comment by TheLonelyDev** [comment]
Tile tagging is already addressed in https://github.com/runelite/runelite/pull/1812 for the next release.

**Comment by SakuraTheSky** [comment]
didn't see, sorry for the repeat on that.

**Comment by deathbeam** [comment]
Updated feature and title to match actual request.

**Comment by Stormcrownn** [comment]
:(

**Comment by Adam-** [comment]
Added in #3495
