### ISSUE TITLE
Option to notify when finished Woodcutting

### ISSUE THREAD

**Issue by Saer-Dev** [runelite/runelite#1889]
I was wondering if it would be possible to add an option to Woodcutting that will notify you when you finish chopping?  This would be very useful for when idling at Magic Trees.

Something similar to OSBuddy's `You are now idle` notification would be the most appropriate.

The best implementation would likely be an OS-level notification as OSBuddy does (not sure if this also occurs on their macOS version), but some sort of on-screen alert with a sound would also be adequate if this proves to be too much of a technical difficulty.

**Comment by Kamielvf** [comment]
Check `Idle Notifier` plugin & some notification settings under "RuneLite", we already have this.

**Comment by deathbeam** [comment]
Already implented, closing.
