### ISSUE TITLE
Add a dark custom UX theme

### ISSUE THREAD

**Issue by Saer-Dev** [runelite/runelite#1893]
It would be really nice if we could have a dark theme for the custom UX, or even better an RGB slider for changing the UX element colours.

The Win98-style light grey contrasts poorly with modern OS' UX design.

**Comment by Juzzed** [comment]
Will be done with #1419

**Comment by Saer-Dev** [comment]
Looks good, excited to see it implemented! 😄

**Comment by deathbeam** [comment]
Duplicate of #1342
