### ISSUE TITLE
Add Fight Caves spawn prediction

### ISSUE THREAD

**Issue by jpabeem** [runelite/runelite#1894]
As explained in [this](https://www.youtube.com/watch?v=LG5hy9bfb_g) video. It's possible to predict the spawn location of the monsters in the waves to come. I think this might be a nice addition to the current fight caves plugin.

Mockup:
 ![quick mockup](https://i.imgur.com/nCgvFOj.png)

Because of the minimap size limitation, it might be possible, or needed even, to highlight this info in the client itself, e.g. a "spawn" tile which has the icon of the monster above it.

Additional info: [reddit post](https://www.reddit.com/r/2007scape/comments/5wd2h3/want_your_own_fight_caves_spawn_predictor_heres/)

**Comment by choocher13** [comment]
I always thought they were random. That'd be very cool

**Comment by Nightfirecat** [comment]
This is likely too strong for us to implement in the client.

**Comment by jpabeem** [comment]
@Nightfirecat Even though the information is readily available on the wiki? I agree that it's a tad bit OP in its current form, but some clues about the next wave could add a lot of value.

**Comment by TheStonedTurtle** [comment]
Maybe add a note on the double 360 wave that lets the player know that Jad spawns where the off-color 360 spawned.

**Comment by Nightfirecat** [comment]
The [Fight Cave Helper hub plugin](https://runelite.net/plugin-hub/show/fight-cave-helper) does this.
