### ISSUE TITLE
Windows Defender SmartScreen flag

### ISSUE THREAD

**Issue by Saer-Dev** [runelite/runelite#1895]
Windows Defender _Smart_ Screen is wrongfully flagging the RuneLight Setup executable as a risky application.

I'm assuming, given the message and the fact that it can't find the Publisher (see attached), it's because you haven't written the author into the executable, or have otherwise failed to identify yourselves correctly.

![image](https://user-images.githubusercontent.com/34461618/39214771-7e097d7a-480d-11e8-92a9-fcbbacab386f.png)

May want to put this issue on the forefront as it almost turned me off from using it until I saw the massive Open Source community you guys have (non-techies who just want a good, free, safe client may not bother).

**Comment by 9338088** [comment]
it will be removed when windows 10 see enought user using the program anyway so no need to sign it

**Comment by devLotto** [comment]
I've been working on getting a signing certificate, so this might be alleviated in a while.

**Comment by IanWONeill** [comment]
The cheapest available is from Comodo however I push you to check out this organisation -> http://www.cacert.org

**Comment by Adam-** [comment]
A new launcher release 1.5.1 is available, and is signed with a valid code signing certificate. We think this will either fix this, or cause it to be fixed soon.
