### ISSUE TITLE
Add filter option for fairy rings

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1897]
When configuring a fairy ring, I would like to be able to type: "Misc" and then press Enter to teleport to Miscellania. MSPaint mock-up:
![image](https://user-images.githubusercontent.com/9074448/39215329-b9250924-4817-11e8-8a1a-3a9a5466c313.png)

**Comment by HypoxiaOSRS** [comment]
I'd suggest something like this to Jagex. While it may be possible to do this you would be removing the players interaction with multiple clicks and scrolling to choose.

**Comment by jerwuqu** [comment]
"Enter to teleport" seems a bit much and probably won't be added since it requires faking interaction (similar to why a world hopping plugin doesn't exist), but the filtering in itself seems fine to me and would be appreciated.

**Comment by Gamer1120** [comment]
I believe this was added to master in last release with the fairy ring search option.

**Comment by Nightfirecat** [comment]
Implemented in #3838.

**Comment by Gamer1120** [comment]
What Nightfirecat said.
