### ISSUE TITLE
Expeditous Bracelet doesn't have a count

### ISSUE THREAD

**Issue by ayyyyllmao** [runelite/runelite#1901]
Also the count on Slayer Left to Kill Count does not change when Expeditous Bracelet loses a charge. 
To get right count of how many left to kill, you need to manually refresh it by checking from the Slayer helm or Slayer ring.

**Comment by jpabeem** [comment]
That's weird and unexpected behaviour. Is this always the case or does this happen in certain cases only?

The slayer plugin should support the expeditious bracelet:
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/slayer/SlayerPlugin.java#L260

**Comment by deathbeam** [comment]
Fixed in #1033
