### ISSUE TITLE
Swap the menu entry for Port Phasmatys Energy Barrier

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#1902]
Currently the left click option opens a dialog, and the Pay-toll(2 ecto) gets you through w/o a dialog.
![Image](https://vgy.me/OVaSWk.png)

**Comment by ajbinky** [comment]
Looking through the code, it appears that it is already implemented. It should be grouped with the "Travel" checkbox. I do not have the quest done, however, so I cannot test this.

`
else if (config.swapTravel() && option.equals("pass") && target.equals("energy barrier"))
		{
			swap("pay-toll(2-ecto)", option, target, true);
		}
`

**Comment by SomeZer0** [comment]
Hmm it appears so. I'm not running the snapshot so I didn't see it/can't test it.
And I didn't find any open/closed PRs when searching "phasmatys."
