### ISSUE TITLE
Filterable Quest Tab

### ISSUE THREAD

**Issue by sha1riar** [runelite/runelite#1905]
It'd be nice to be able to filter quests. I think runescape used to have this feature. 

Ideally I'd like the filters below:

1. F2P/P2P
2. Completed
3. Unable to Start

Additionally it'd be cool to be able to sort the quests in the optimal quest order.

**Comment by Adam-** [comment]
Going to call this done from #8306 . You could open another FR for `#3` maybe, but it is significantly more involved.

**Comment by NAM31322CRYPT1C** [comment]
I was thinking being able to put the list in optimal order was a great idea and would love to see this implemented into runelite!
