### ISSUE TITLE
low cpu mode suggestion

### ISSUE THREAD

**Issue by stfnnnnnn** [runelite/runelite#1917]
When I'm doing something that doesn't require much of anything, I'd prefer the option to save laptop battery over 60 fps gameplay and extra visuals. Maybe even an option to restrict the fps to 15/30/45?

**Comment by SoyChai** [comment]
#1350 will take care of precisely this when (if..?) it gets merged.

**Comment by stfnnnnnn** [comment]
Great!

**Comment by Adam-** [comment]
Added in #1350
