### ISSUE TITLE
Interesting behavior for Guardian Mummy clue in Pyramid Plunder minigame

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1920]
I entered through the wrong entrance and got this:
![image](https://user-images.githubusercontent.com/9074448/39246751-c5044040-4897-11e8-9912-66e57ca09274.png)
Is this intended or a bug?

**Comment by deathbeam** [comment]
When entering the correct instance does it work?

**Comment by Gamer1120** [comment]
Yes

**Comment by deathbeam** [comment]
interesting, that might be the correct behaviour then and the actual mummy is somewhere there :D

**Comment by Nightfirecat** [comment]
The pyramid plunder entrance rooms appear within the same region as one of the other variations (two are on plane 2, the other two are on plane 3) so this is intended behavior.
