### ISSUE TITLE
 A Few Suggestions

### ISSUE THREAD

**Issue by BigSmokesDip** [runelite/runelite#1921]
Hello,

For Agility, could you add another option so when there is a Mark of Grace the clickable areas turn a different colour like other clients as OSBuddy and RuneLoader

Is it possible to make dragon bones when left clicked, it goes to USE rather than Bury, OSBuddy has this as a Pro Feature but only when in PoH.

All Banks left click and Grand Exchange Left click

If these are can be implemented that would be so sick.

**Comment by MagicfTail** [comment]
Your second and third requests are already in under the "Menu Entry Swapper" plugin

**Comment by sethtroll** [comment]
Marks of grace recolor will be in the next update.

**Comment by BigSmokesDip** [comment]
Awesome, thanks guys

**Comment by deathbeam** [comment]
Everything here is already implemented, invalid.
