### ISSUE TITLE
Buy-plank menu entry swapper

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1930]
Add buy-plank swapping for Sawmill Operator.

**Comment by Gamer1120** [comment]
This is how I made it:
![image](https://user-images.githubusercontent.com/9074448/39269981-d6fd3cd8-48d4-11e8-93f6-2a97afe45a6a.png)

**Comment by Nightfirecat** [comment]
This is [a rejected feature](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping):

> `Menu reorder in shop/artisan skill screens`: Other clients don't implement these swaps, and would be too strong for numerous activities (examples include "Buy-50" swaps, "Make All" swaps for smithing/crafting, etc.)

**Comment by lund8619** [comment]
Okay, then I'll upload the code that I have for this, cause I've already done this one.

**Comment by lund8619** [comment]
yes, ya got me. lund8619 = ironmosiah. I've been linked the reject page and have read it, but I guess I still don't get where the line is drawn cause ya'll just post the same bit without really explaining. I tried to say I'm new and learning the ropes still.

**Comment by azzawoody** [comment]
is this getting added or not ??? would help ironman running planks at woodcutting guild

**Comment by Nightfirecat** [comment]
This is a niche feature that is best suited for the plugin hub, and is currently covered by the Menu swapper extented plugin there. See runelite/plugin-hub#42
