### ISSUE TITLE
Hard Clue Scroll Error ( Search box underground)

### ISSUE THREAD

**Issue by CurseofAres** [runelite/runelite#1939]
![image](https://user-images.githubusercontent.com/29232391/39274870-a559a11c-48e3-11e8-8749-48051eceac85.png)

With this clue, it shows all the boxes within Yanille to be searched but the only box that needs to be searched is underground. The arrow is also pointing in the wrong way.

**Comment by deathbeam** [comment]
Fixed in #1707
