### ISSUE TITLE
Is it, or would it be possible, to remove the healing tooltip of various food. Thanks in advance guys haha

### ISSUE THREAD

**Issue by GODTFREDSENAPMXD** [runelite/runelite#1947]
:)

**Comment by Kamielvf** [comment]
disable the item stats plugin

**Comment by GODTFREDSENAPMXD** [comment]
Thanks a lot! lol 
I'm amazed by the quickness of your reply, good sir/siress/genderfluid. How come that works though? haha xd

**Comment by Infinitay** [comment]
Because the Item Stats plugin displays a tooltip for (supported) consumables

**Comment by GODTFREDSENAPMXD** [comment]
Oh, now I'm enlightened haha, thanks to you too man/girl/hybrid!
