### ISSUE TITLE
Add "Set Target Level" to XPTracker

### ISSUE THREAD

**Issue by Berry-95** [runelite/runelite#1948]
Rather than just showing xp left, actions left and ttl for the next level, let the user set a target level (default next level). Similar behaviour to OSBuddy XPTracker, useful for training skills for long periods of time, or with a goal in mind.

**Comment by NAM31322CRYPT1C** [comment]
I would love to see this as well!

**Comment by Nightfirecat** [comment]
@NAM31322CRYPT1C FYI, this feature has already been added. Set your goals via the ingame XP interface, and RuneLite will use them to determine your target level. :)

**Comment by NAM31322CRYPT1C** [comment]
I literally just found it!

**Comment by irkanu** [comment]
@NAM31322CRYPT1C WHERE?

**Comment by irkanu** [comment]
![screenshot_2623](https://user-images.githubusercontent.com/6570433/43665957-f37b9b8e-973f-11e8-9461-0fc592eb60a2.png)
![screenshot_2624](https://user-images.githubusercontent.com/6570433/43665958-f4f21902-973f-11e8-8158-e4d4b1106f5f.png)
![screenshot_2625](https://user-images.githubusercontent.com/6570433/43665960-f635087e-973f-11e8-9c24-d474b36c8253.png)
![screenshot_2626](https://user-images.githubusercontent.com/6570433/43665962-f78822c4-973f-11e8-8588-faa36c5d2201.png)
![screenshot_2627](https://user-images.githubusercontent.com/6570433/43665980-f8c7bfb4-973f-11e8-8fb2-94c48833b80b.png)
![screenshot_2628](https://user-images.githubusercontent.com/6570433/43665987-f9e26f66-973f-11e8-819d-3cd6df5ab52f.png)

**Comment by Nightfirecat** [comment]
@irkanu Thanks for getting those images, [I've added them to a new "Setting Level Goals" section of the XP Tracker wiki page](https://github.com/runelite/runelite/wiki/XP-Tracker#setting-level-goals).

**Comment by Fizbun** [comment]
Hello

Yes coming back 4+ years later to complain about this. 

Maybe I am misremembering - or remembering some other OSRS client but I felt like this feature was a thing.
As @Derek-Baum said, the current way to "set target goal" feature is too complex - it could just be two clicks, done and dusted.

Why is this not a thing?
