### ISSUE TITLE
MAC Client Unable to Intstall - runelite.dmg

### ISSUE THREAD

**Issue by SimplyDeek** [runelite/runelite#1950]
When opening runelite.dmg from the mac os install the image fails to mount and is labeled as corrupt.

**Comment by Adam-** [comment]
What version are you on? We have heard people not on Sierra or High Sierra say that the image is corrupt. But it works for others. We don't know why.

**Comment by SimplyDeek** [comment]
Currently running OS X Yosemite (10.10.5) on a late 2013 model

**Comment by deathbeam** [comment]
Closing, created issue for this in launcher https://github.com/runelite/launcher/issues/16
