### ISSUE TITLE
Enable native window snapping while using custom chrome

### ISSUE THREAD

**Issue by SoyChai** [runelite/runelite#1953]
Pretty much the only downside of this window mode. It'd be great to have the full visual branding but still make use of basic multi-monitor features.

**Comment by deathbeam** [comment]
Well, that is because custom window chrome breaks native functionality. This breaks a lot of stuff on other operating systems too, and I don't think we want to re-implement stuff like this.

**Comment by SoyChai** [comment]
The current implementation indeed breaks this functionality. There are ways to write a custom frame which supports all native functions however, as we can see with the web browsers we're using to read this. Maybe the solutions would need to be platform-specific, but I think it's worth it to fix something that we're breaking ourselves.

**Comment by deathbeam** [comment]
We don't break it, we decide we want to handle our window by ourselves. The result behaviour is expected.

**Comment by SoyChai** [comment]
Well I mean, broken from the perspective of a user who'd expect RuneLite to act like any other window.

**Comment by deathbeam** [comment]
We now have retain in screen option, but otherwise we cant really implement working "snapping", because, that heavily depends on other windows on screen too, what we have no info about
