### ISSUE TITLE
crystal equipment counter overlay

### ISSUE THREAD

**Issue by e-102** [runelite/runelite#1954]
this feature is a counter overlay displaying remaining charges for all crystal equipment. this is meant to be visually similar to the rune pouch or teleport jewelry.

**Comment by Nightfirecat** [comment]
+crystal bow, crystal halberd

**Comment by Nightfirecat** [comment]
Crystal halberd charge tracking is done here: https://runelite.net/plugin-hub/show/weapon-charges-2. I think it has some support for the crystal bow; I'd recommend requesting it or developing it further there.
