### ISSUE TITLE
Colorblind plugin

### ISSUE THREAD

**Issue by Juzzephe** [runelite/runelite#1959]
Basically a plugin that recolors certain colors depending on your color blindness.

- Recolor Plugins
- Recolor Minimap dots
- Draw a filter over the game 

![b8txmheiyaaohof](https://user-images.githubusercontent.com/25037124/39289755-ae47ee24-492d-11e8-9bf2-e853a8dd6425.png)

Can be tested with:
http://www.color-blindness.com/coblis-color-blindness-simulator/

**Comment by IanWONeill** [comment]
Offtopic sorry: Looking at that color swatch image makes my eyes trip out like I see random Circles inbetween the swatches.

**Comment by Incarceron** [comment]
Still hoping this gets implemented. I'm red-green colorblind and healthbars being blue for the player would be amazing.

**Comment by cheekywario** [comment]
The filters for color blindness were added to Windows 10 in the Fall Creators Update, which is in the process of being installed now on most Windows 10 computers. If you don’t see these filters, you may not have gotten the update yet.

If you have Deuteranopia or Protanopia (the two types of red-green color blindness) or Tritanopia (blue-yellow color blindness), try the color filters to make colors look more accurate on your Windows 10 display.

  •  Go to Settings / Ease of Access / Color and High Contrast.

  •  Toggle Apply Filter on. Choose Deutaranopia, Protanopia or Tritanopia from the dropdown menu.

  •  After the toggle is turned on, you can turn the color filter on and off using the keyboard shortcut Windows key + Ctrl + C.

The filters are applied at the system level, so they affect all displays from all programs.

**Comment by longshottah** [comment]
The filters for color blindness were added to Windows 10 in the Fall Creators Update, which is in the process of being installed now on most Windows 10 computers. If you don’t see these filters, you may not have gotten the update yet.

If you have Deuteranopia or Protanopia (the two types of red-green color blindness) or Tritanopia (blue-yellow color blindness), try the color filters to make colors look more accurate on your Windows 10 display.

  •  Go to Settings / Ease of Access / Color and High Contrast.

  •  Toggle Apply Filter on. Choose Deutaranopia, Protanopia or Tritanopia from the dropdown menu.

  •  After the toggle is turned on, you can turn the color filter on and off using the keyboard shortcut Windows key + Ctrl + C.

The filters are applied at the system level, so they affect all displays from all programs.

**Comment by Adam-** [comment]
added in #12744
