### ISSUE TITLE
Make every quest with requirements cross out the levels/quests you have completed 

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1964]
From https://www.reddit.com/r/2007scape/comments/8eyks2/suggestion_make_every_quest_with_requirements . Since Jagex probably won't do this, maybe we can implement it. Image: https://i.imgur.com/4ZxqgyP.png

**Comment by Gamer1120** [comment]
This was definitely done for diaries. I'm not sure if this is done for quests. Can be closed if done.

**Comment by melkypie** [comment]
I am pretty sure this is added as quests get their requirements striked out each of them is done. I just can't find when this was added as a runelite or vanilla feature.

**Comment by makingcomment** [comment]
> I am pretty sure this is added as quests get their requirements striked out each of them is done.

Unless something has changed (and I don't think it has), the issue is that only _some_ quests get their requirements striked out, rather than all of them.

> I just can't find when this was added as a runelite or vanilla feature.

I'm pretty sure it's vanilla.

**Comment by Hydrox6** [comment]
At some point, Jagex seem to have gone through and standardised all the quest scroll texts, which seems to have fixed this.
