### ISSUE TITLE
Swap "Walk here" with Build in POH

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#1967]
Might be OP, but really useful for construction training. Opinions welcome.

**Comment by Rheon-D** [comment]
Asked this the other day, OP was the general consensus.
Sadly they are right

![zuwnium 1](https://user-images.githubusercontent.com/38576432/39303483-7d1d59ca-4995-11e8-8643-966479efc8d3.png)

**Comment by deathbeam** [comment]
This will not be implemented due to obvious reasons.
