### ISSUE TITLE
Mouse tooltips size is always small

### ISSUE THREAD

**Issue by TaxoRubio** [runelite/runelite#1968]
Even though I selected the text size to be regular in the RuneLite plugin config

**Comment by deathbeam** [comment]
Yes, that is intended.

**Comment by Astug** [comment]
I would like to see a seperate option for the mouse tooltip font style. 

This could be added under the Mouse Tooltips category in the Plugin Configuration menu.

**Comment by deathbeam** [comment]
No, because there are mouse tooltips, item stats that add tooltips too, item prices with own tooltips. It would need to be RuneLite global option.

**Comment by Astug** [comment]
Oh yes, forgot about those.

**Comment by deathbeam** [comment]
Tooltip font size was added
