### ISSUE TITLE
"Highlight marks of grace" doesnt work on bridges

### ISSUE THREAD

**Issue by Nithe** [runelite/runelite#1976]
Ive only yet noticed 2 places on the varrock course where this is the case, but there might be more.
https://imgur.com/gallery/2WeC3as
https://imgur.com/gallery/HipEUI0 (idk if this is a bridge, but it doesnt work)

**Comment by samrobben** [comment]
I'm working on a fix for this. Currently testing my fix.

**Comment by Adam-** [comment]
Tried to reproduce this today and couldn't do it. Maybe it is unrelated to bridges.
https://cdn.discordapp.com/attachments/419891709883973642/440165992300150805/unknown.png

**Comment by Nithe** [comment]
hmm yea it might be, i also have a problem with the ground item overlay is not showing once i a while

**Comment by Nightfirecat** [comment]
This is unrelated to bridges, it's caused because of the issue described here: #4076

**Comment by Nightfirecat** [comment]
This can be closed as duplicate
