### ISSUE TITLE
Potential Bot Hiding Plugin

### ISSUE THREAD

**Issue by IanWONeill** [runelite/runelite#1978]
I think a plugin to hide players who are Level 3, (or below the typical bot level maybe.) from the right-click menu when attempting to interact with certain things.

If possible using the Entity hiding plugin idea to completely hide these players.

I know not all players at Level 3 will be bots but i feel you will agree they are mostly. However I think there should be a system where by if a hidden player interacts with the player allow the option to 'unhide' a certain player or something along those lines. 

This will encourage newer players i feel.

**Comment by deathbeam** [comment]
Hide people in ignore list?

**Comment by Infinitay** [comment]
Instead of hiding combat level, hide if total skill level < than _x_

**Comment by Reasel** [comment]
I am working on adding an option to the entity hider for hiding ignored players. Won't be automatic but still nice.

**Comment by ShaunDreclin** [comment]
Just auto-hide them if they look like this 😂

![bot.jpg](https://user-images.githubusercontent.com/5851433/39319459-14decb3c-494f-11e8-9d3e-27d48af75d2d.jpg)

**Comment by IanWONeill** [comment]
People are overwhelmed and put off by the sheer amount of bots running arround the game.

**Comment by Saer-Dev** [comment]
I can see the benefit of this feature request, but I believe that catering to new players is a weak argument for the simple reason that very few new players are going to be downloading a third-party client.  The benefits of this client are meaningless to somebody who is just now learning that you can kill cows to become stronger.

**Comment by IanWONeill** [comment]
Your thinking too new, Im thinking thise who have yet to decide to purchase Membershio and access the whole game. I imaging quite quickly into playing the game people search for possibly some sort of help or tutorial via YouTube, those will notice 3rd Party clients. I imagine mainly OSB to be fair but when searching for it theyre bound to come accross RL, which is offtopic anyway.

Its not really catering, so much as offering. What about those who have started a new account and dont want to be surrounded by bots while Woodcutting/Fishing.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
