### ISSUE TITLE
If there is entity under hidden entity the entity will be hidden as well

### ISSUE THREAD

**Issue by TheSexyNerd** [runelite/runelite#1979]
When selected to **not** render players, if there is an NPC underneath of them the NPC will also not render.

**Comment by Reasel** [comment]
I don't think this is possible to fix as the way Entity hider works is by simply not rendering something. Had the player been rendered the NPC would still be hidden from view which means it was never going to be rendered. We cannot force render an NPC, or at least I don't think we can.

**Comment by devLotto** [comment]
I have a surprisingly small fix for this. Requires edits internally before it can be PRed to GitHub though.
https://gfycat.com/EverlastingLargeAlbino
