### ISSUE TITLE
Kingdom of Miscellania Favor using wrong quest requirement

### ISSUE THREAD

**Issue by adrianped** [runelite/runelite#1980]
Does not display Favor during and after quest complete of throne of miscellania even if standing in miscellania

**Comment by ShaunDreclin** [comment]
Can confirm, having this issue myself. The overlay just never seems to show up

**Comment by TheSexyNerd** [comment]
I've never seen the code for this plugin, but try asking an NPC what your favour is and then re-log, see if that works!

**Comment by adrianped** [comment]
Did not make a difference.

**Comment by Infinitay** [comment]
I think it may be a logic error under the `hasCompletedQuest` method so I'm trying to see if thats the case. Hopefully it's not an issue elsewhere because my membership conveniently ran out

**Comment by MagicfTail** [comment]
Mine is working. Have the people having issues completed royal trouble?

**Comment by ShaunDreclin** [comment]
Hm I didn't even consider that as a potential issue. I have completed royal trouble

**Comment by Infinitay** [comment]
That shouldn't be an issue seeing as Throne of Misc is a pre-req for Royal Trouble

**Comment by adrianped** [comment]
i have not completed royal trouble but code only asks to check for throne of misc

**Comment by ShaunDreclin** [comment]
It's possible that the varbit/flag/whatever for throne of misc changes after completion of royal trouble

**Comment by Infinitay** [comment]
Thats a very good point, I will look into it

**Comment by Lorenso0** [comment]
Happening to me aswell - https://i.imgur.com/m3JOvtd.png, nothing shows up at all even after I cut a tree or ask a NPC what my favor is

**Comment by Gieliron** [comment]
I can confirm that this is still a bug.  I've got both Misc quests completed and this plugin has never worked for me.  I've toggled it many times, spoken to NPC's to check approval etc.  Nothing.

**Comment by Nightfirecat** [comment]
Fixed by #5212?
