### ISSUE TITLE
Chat scrollbar positioning 

### ISSUE THREAD

**Issue by Jasblaze** [runelite/runelite#1982]
Allow scroll bar to be put on either side of chat. As of last update it has been moved to left side of chat but having the bar on the right side where it originally was seems a lot better.

**Comment by ShaunDreclin** [comment]
Isn't it a toggle now?

**Comment by deathbeam** [comment]
Yes it is.

**Comment by ShaunDreclin** [comment]
Ah yeah here, from the news post

![scrollbar position](https://i.imgur.com/KT9OxZO.png)
