### ISSUE TITLE
Add numbering and clear all to tile markers

### ISSUE THREAD

**Issue by MrArkTen** [runelite/runelite#1989]
I love the mark tile feature, its great if you want to measure distance or mark terrain. I thought of some ways to improve it: 
1. Tiles should be numbered with the number written on it somewhere (small in a corner sounds reasonable), to help remember which tiles you placed first. 
I'm also thinking it could be displayed by a color variation, a gradient, related to the tile's age, for example, the first tile you placed is red, and the newest tile is green, all the tiles in-between are a gradient of both colors.
2. A "Clear All" button in the menu would be useful.

Thanks, great work guys

**Comment by TheLonelyDev** [comment]
1. Seems a little bit niche and perhaps not really useful for most usecases and perhaps sometimes annoying? I don't really see a use case atm for it (but that is me).

2. Do you mean in the config tab? I don't believe "custom buttons" are posible atm, but you can reset the marked tiles with ctrl+shift+right click.

(Just my opinion, I can be wrong though)

**Comment by Gyllenfalk** [comment]
@TheLonelyDev I don't believe that the hotkey you mentioned "Ctrl+Shift+Right Click" is working. Is there currently an option to remove all marked tiles?

**Comment by S33kerX** [comment]
If I may add to this, I could see the numbering, or at least a option to recolor a marked tile, being useful for things like learning Zulrah. I'd be able to mark the tiles I need to stand on and color them for what combat style I'd need to use. Or if numbering, I could mark rotations and what not. Would be that much easier to learn it.

**Comment by Hydrox6** [comment]
Both halves of this issue are now effectively implemented:
Numbering can now be done with tile labels
An option can now be enabled to clear all markers around the player from the world map button
