### ISSUE TITLE
Hovering empty string configurations causes a black dot to appear

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#1993]
![untitled](https://user-images.githubusercontent.com/2199511/39324993-930cb6aa-4980-11e8-8265-43d965b870f9.png)

Hovering the "Highlighted items" box (which is not empty) shows a normal text tooltip as expected.

**Comment by Nightfirecat** [comment]
This issue is still present after the redesign.

![field-hover-bug](https://user-images.githubusercontent.com/2199511/41444648-edeee672-7033-11e8-98b6-793ffc560f23.png)

**Comment by deathbeam** [comment]
Is this issue still present?

**Comment by Nightfirecat** [comment]
Doesn't look like it... Text fields don't seem to have tooltips anymore I guess. :woman_shrugging:
