### ISSUE TITLE
Venge-other Timer

### ISSUE THREAD

**Issue by Kosmikz** [runelite/runelite#2001]
Currently the only vengeance spell that has a timer on the RuneLite client is the regular vengeance spell, however without much effort or dev time a new, very useful timer could be introduced further helping PVMers - a Venge-other timer. This timer would act very similarly to the current Vengeance timer, except it'd be for the alternative spell!

**Comment by Hydrox6** [comment]
Provided in #2013

**Comment by Gamer1120** [comment]
Can be closed.
