### ISSUE TITLE
Hard Clue :  MIssing Equip Items

### ISSUE THREAD

**Issue by GETrackerDan** [runelite/runelite#2004]
![xacm4xk](https://user-images.githubusercontent.com/38025439/39332328-0d43a01e-499f-11e8-9e8a-11a340ce0400.png)

Should list 

Equip:
Any rune heraldic shield
Blue mystic Robe Top

![dog2khu](https://user-images.githubusercontent.com/38025439/39332420-3924de1e-499f-11e8-8096-20bb3ef36a11.png)

**Comment by Reasel** [comment]
Corrected in [#2006](https://github.com/runelite/runelite/pull/2006)
