### ISSUE TITLE
Adding a teleblock track feature for opponents

### ISSUE THREAD

**Issue by whallis** [runelite/runelite#2009]
When tb'ing someone, a teleblock timer to be over their head showing remaining time on tb, allowing easier tracking of time left

**Comment by jessebake** [comment]
An identical feature already exists in the PvP client Exilent so I don't think that this would create any unfair advantages.

**Comment by whallis** [comment]
Any ideas on how much work this would be to implement?

**Comment by SoyChai** [comment]
Just for reference, we don't consider Exilent a very trusted client since they don't seem to have the same courtesy towards Jagex that other clients do.

**Comment by deathbeam** [comment]
We decided to not do this as it is op

**Comment by Jellex420** [comment]
i would donate for this plugin, stun and teleblock timer like in Pvp clients!!
