### ISSUE TITLE
Add Freeze time on the opponents

### ISSUE THREAD

**Issue by mrpker9** [runelite/runelite#2011]
Is it possible to create a freeze time on the opponent so when someone gets binded or frozen it shows on him how many seconds left till he can move?

**Comment by devOSRS** [comment]
Are opponent freeze/bind timers are off the table? Don't want to pursue a feature if there are issues with the feature being added to runelite. (i.e.: https://github.com/runelite/runelite/pull/604)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features Yeah, they are on rejected list now based on previous discussions we had about them.

**Comment by TwiNaga** [comment]
Since unfair advantages when PKing seems to be the main concern, would it be possible to have this added only for NPCs?  It would greatly help with bosses such as Scorpia.
