### ISSUE TITLE
Add option to swap Talk-to and Pickpocket

### ISSUE THREAD

**Issue by Sovexe** [runelite/runelite#2017]
Similar to the already existing option "Pickpocket on H.A.M." in the "Menu Entry Swapper" plugin

Allow swapping the left click option to be "Pickpocket" instead of "Talk-to" on Fremennik citizens

**Comment by Adam-** [comment]
I really do not like these pickpocket swaps. We are trying to only swap what other clients already do with regard to them.

**Comment by deathbeam** [comment]
If it is not doable with in-game attack style hiding and other clients are not doing it we are not going to implement it too

**Comment by Adam-** [comment]
This is being revisited due to OSB adding it.

**Comment by Adam-** [comment]
This has been added for all non blackjacking npcs.
