### ISSUE TITLE
Cannon ammo can be desynced.

### ISSUE THREAD

**Issue by Roughsketch** [runelite/runelite#2019]
I encountered this issue while running to the bank with ammo still in the cannon. I loaded the cannon and left immediately, and when I came back the cannon was empty but both overlays showed 22 ammo. When loaded, the counter jumped to 52 instead of 30. Manually emptying the cannon does not reset the overlay, but picking up and replacing the cannon does fix it. I believe this is an issue with the cannon not being within render distance while it's shooting.

Here's a screenshot of it: https://i.imgur.com/AKbeodP.png

**Comment by Adam-** [comment]
Maybe this is related to 9d215b4b285711e511997157b944a2fb745b873e
