### ISSUE TITLE
Hiscores level 1 combat

### ISSUE THREAD

**Issue by psikoi** [runelite/runelite#2025]
When a player is unranked in combat skills, have a minmum combat level of 3 to prevent it from displaying 1.

@devLotto 
![](https://i.gyazo.com/1d90cd185723ce01032708f467df3184.png)

**Comment by olligobber** [comment]
This bug seems to be back?

![2023-04-22-143743_229x502_scrot](https://user-images.githubusercontent.com/11549963/233762814-c88c53d7-4ebd-4bb0-ab1e-51b2899662e2.png)
