### ISSUE TITLE
Menuentryswapper PoH Swapping "Enter" to "Friend's house" instead of "Home"

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#2027]
runelite-master\runelite-master\runelite-client\src\main\java\net\runelite\client\plugins\menuentryswapper

https://github.com/runelite/runelite/tree/master/runelite-client/src/main/java/net/runelite/client/plugins/menuentryswapper

ctrl-f "home" you find the plugin
tried to change it to friends house with the 2 java files in that folder but couldnt do it would be nice if someone found a quick fix

**Comment by Adam-** [comment]
Added in #3565
