### ISSUE TITLE
Screenshots from Deadman Mode can overwrite screenshots from Normal Accounts

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#2050]
If a player uses the same account on both Normal and Deadman modes, the automatic screenshots for levelling up/clue rewards/barrows rewards can overwrite images from the other mode.

**Comment by deathbeam** [comment]
This is still valid issue until the PR will be added.

**Comment by Adam-** [comment]
Fixed in 6c803dce035d3f18e179421bedc36e7df1ea7826
