### ISSUE TITLE
hide 'trade with' from player menu options

### ISSUE THREAD

**Issue by forgot-username** [runelite/runelite#2051]
like how you can remove the report/lookup menu options... so only 'follow' would appear when right clicking?

**Comment by forgot-username** [comment]
not that i am aware of sir

**Comment by SomeZer0** [comment]
Would be immersive for Ironmen btw.

**Comment by deathbeam** [comment]
Hiding menu entries is listed here, so closing as wontfix: https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
