### ISSUE TITLE
[Request] List of most valuable items in bank

### ISSUE THREAD

**Issue by neb7777** [runelite/runelite#2062]
Similar to runeloader's feature

**Comment by renfc01** [comment]
Bump, Is anyone working on this atm?

**Comment by Nightfirecat** [comment]
This is mostly/entirely fulfilled via the [Bank Heatmap plugin](https://runelite.net/plugin-hub/show/bank-heatmap) on the hub. If this is wanted in some other format, it should be added to that plugin, or added to the hub as a separate plugin.
