### ISSUE TITLE
Custom cursors

### ISSUE THREAD

**Issue by Chaoticx** [runelite/runelite#2068]
Is it possible to add custom cursors like osb/konduit has? Not a major update, but it just feels much better when your ingame cursor is different from normal mouse pointer.

**Comment by Chaoticx** [comment]
![17047](https://user-images.githubusercontent.com/33873259/39389438-231a927e-4a91-11e8-915b-d54e549369a5.png)
Something like this i guess

**Comment by WSylv** [comment]
Or different weapons like the godswords, d scim, etc.

**Comment by dappersnapper456** [comment]
http://www.rw-designer.com/cursor-set/runescape-jagex-animated-dragon- Please WE NEED THIS

**Comment by CybertronicToon** [comment]
I just want to clarify that I was referring to the cursors changing depending on what you hover over.

**Comment by Kamielvf** [comment]
I was thinking you meant the cursors from rs where they would show an apple when you hover over food, sword for attack etc.

**Comment by dappersnapper456** [comment]
Custom .ani animated cursors now!!

**Comment by dginovker** [comment]
The touchups on 2006/2010 client could really bring it to life. I still support this

**Comment by AmazingJesus** [comment]
Still need this :)
