### ISSUE TITLE
cannon upper limit issue

### ISSUE THREAD

**Issue by whallis** [runelite/runelite#2072]
if you go offscreen and cannon keeps firing, the cannonballs will not go down on counter so when you come back and fill it, it shows a number over 30. Simply cap cannon balls at 30 to fix. Example : https://i.imgur.com/Ut9xSiZ.gifv

**Comment by SoyChai** [comment]
Big man Woox is currently working on this: #2020

**Comment by whallis** [comment]
shit

**Comment by deathbeam** [comment]
Duplicate of #2019
