### ISSUE TITLE
Right click menu on a friend in chatbox

### ISSUE THREAD

**Issue by forsco** [runelite/runelite#2086]
Whilst right clicking on another players name in the chatbox that is currently on your friendslist still shows 'Add friend playername' in the right click menu instead of "Message playername".

**Comment by deathbeam** [comment]
Is this vanilla bug or is this caused by RuneLite?

**Comment by forsco** [comment]
> Is this vanilla bug or is this caused by RuneLite?

To the best of my knowledge this only happens in Runelite.

**Comment by Nightfirecat** [comment]
I can't reproduce this, I'm seeing identical behavior on official client and Runelite. (with the exception of the added "Lookup" option)

**Comment by deathbeam** [comment]
Looks like this is jagex bug then, closing
