### ISSUE TITLE
Impling Plugin: "Show Spawn locations" not working.

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#2087]
Example:
https://streamable.com/7x7sa

Normally a highlighted tile would appear right after catching this nature imp, which highlights an invisible "spawn" location that flies around like an imp would.

**Comment by Juzzed** [comment]
Im working on it #2128

**Comment by SomeZer0** [comment]
Issue resolved, dynamic spawns removed, and static spawns added via #2371
