### ISSUE TITLE
Request: Prayer Flick on HP bar

### ISSUE THREAD

**Issue by forsco** [runelite/runelite#2088]
I currently utilise the pray flick tick on the prayer orb at the minimap, I was wondering if anyone would be interested in applying the same effect to the player health bar?

This would allow people to keep their attention more focused on the central gameplay area of the screen instead of the prayer orb for people who can't keep their timing for prayer flicking.

**Comment by SoyChai** [comment]
I like the idea of moving the flicker closer to the screen center, but isn't the HP bar only visible if you're taking damage? Which means it would disappear the moment you start flicking Protect prayers successfully?

**Comment by forsco** [comment]
> My bad, the bar appears when you're taking 0-hits as well. Supporting this!

This was my reasoning because i've been pray flicking melee tasks 😛 

If this could happen I would totally be keen to see it, even if it's only while the health bar is visible.

**Comment by Chdata** [comment]
I wanted to try doing something like this for my Prayer Bar plugin. And perhaps I will some day ;p

Prayer Bar's my first PR so far so hopefully that works out:
https://github.com/runelite/runelite/pull/2549

**Comment by forsco** [comment]
@Chdata Will you be re-writing the prayer plugin to incorportate your additions?

If not I can look at doing it whilst working on the original feature request above.

**Comment by deathbeam** [comment]
Well, we have this in prayer bar now, so looks like this is solved
