### ISSUE TITLE
Multiple occurencies of "Search x" on inventory item

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#2094]
![image](https://i.redd.it/lwnnjk01xju01.png)

**Comment by MagicfTail** [comment]
This happens when you press alt and right click at the same time (the timing is a bit wonky). The options have the correct effect but are renamed.

![image](https://user-images.githubusercontent.com/12607046/39396150-33eb4ba4-4ae9-11e8-984d-fcacbfb8099f.png)

**Comment by deathbeam** [comment]
If someone could recheck this on latest master, maybe #4048 was related. @MagicfTail

**Comment by MagicfTail** [comment]
This isn't fixed in master

**Comment by raiyni** [comment]
This appears to be fixed. Right click menu can't open with alt.

**Comment by SieBrum** [comment]
![image](https://user-images.githubusercontent.com/14212955/46360555-02c48000-c66c-11e8-95dc-0c03f0e114cf.png)
Still an issue for me

**Comment by Nightfirecat** [comment]
Per @raiyni's comment from nearly 4 years ago, I can't repro this because the menu can't be opened while holding <kbd>Alt</kbd>.
