### ISSUE TITLE
Game not loading in properly

### ISSUE THREAD

**Issue by Regath** [runelite/runelite#2095]
So, my game looks like this: https://i.imgur.com/gs6tumg.png

I'm running Manjaro with JDK 10. Fairly new to linux in general, sorry if I'm missing something obvious. I've tried other versions of Java, they all seem to produce the same result.

**Comment by sethtroll** [comment]
Try running with “java -jar RuneLite.jar --mode=OFF”

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Regath** [comment]
It works, thank you. :)
