### ISSUE TITLE
No Idle Notification plays when attaching feathers to arrow shafts/arrow tips to Headless arrow

### ISSUE THREAD

**Issue by battlesmit** [runelite/runelite#2100]
Idle sounds play when turning logs into arrow shafts, but not when you attach feathers to the arrow shaft nor attaching arrow tips to the Headless Arrows

**Comment by tr33s** [comment]
Not sure about this one. The idle notifier code doesn't specifically include any constants for fletching/feathering/arrow-heading arrow shafts, which would suggest the animation is the same.

Does this happen in other third party clients?

**Comment by deathbeam** [comment]
Does attaching feathers to arrow shaft even have animation?

**Comment by tr33s** [comment]
@deathbeam the idle notifier code would suggest that, otherwise it's the default sounds playing.

**Comment by Nightfirecat** [comment]
A number of fletching animations have been added in today's update:

![various player fletching animations](https://cdn.runescape.com/assets/img/external/oldschool/2019/newsposts/2019-08-01/fletching.gif)

> Animations have been added for when a player tips arrows, bolts and darts, and adds feathers to shafts. These animations will not affect the rate at which you do actions and will not prevent movement or other actions such as doing Agility while Fletching.
