### ISSUE TITLE
Built-in authenticator.

### ISSUE THREAD

**Issue by gccltl** [runelite/runelite#2102]
Suggestion: Built-in authenticator for authentication purposes.

**Comment by devLotto** [comment]
Can you go into more detail?

**Comment by Gamer1120** [comment]
A big nono to this. The point of the authenticator next to a password is that an unauthorized individual would, next to your password, also need physical access to your phone and your phone's unlock code. If you were to store the secret which generates authentication codes on your PC, your account can be compromised by having malware on it (keylogger for password and something that reads the secrets for 2FA). This strongly weakens the security you get for having an authenticator on your account. I would suggest closing this issue and not implement it.

**Comment by gccltl** [comment]
Well, it's also possible to fetch secrets from phone & also you can have keyloggers on phone too, and phones unlock code is not even protection, it's a joke.

**Comment by Sharpienero** [comment]
@gccltl If I handed you a phone with a 4 digit passcode with incremental wait periods for incorrect activities, you wouldn't be able to crack it in a timely manner what so over (make sure you read with time delays, as most phones do have). On top of that, most phones are now using bio-metrics with longer pass codes or phrases.

I think you're majorly missing the point of 2FA. It's supposed to provide a secondary, much more secure second layer of protection, and having that on the client itself is a security risk.

So, what I can recommend to you is using authy? They have a desktop client, if you really want to use that.

**Comment by SoyChai** [comment]
Modern phones do tend to be more secure than desktop computers, due to a combination of verified app marketplaces, tightly defined permissions, and encrypted internal storage. They're also designed by people who probably have much more experience in cybersecurity than any of us at RuneLite. 🕵️

**Comment by gccltl** [comment]
@Sharpienero Yes, you have a code, and you can try guessing it, what I'm saying that the passcode provides zero protection (placebo protection), it my stop some kid getting in dads phone, but you can get around the passcodes easily. The secrets in phone are stored as plain (not encrypted) database files.

**Comment by Gamer1120** [comment]
@gccltl On an updated Android or iOS device, it is not possible to gain access to the data without knowing the passcode, since the data is encrypted.

**Comment by Gamer1120** [comment]
Also, after a couple of attempts you have to wait 30 seconds before trying again. This wait time increases with every failed attempt. Good luck cracking it. You would also need physical access to the phone. Imagine someone from Venezuela attempting to hack a European player. It would not be efficient money-wise.

**Comment by Sharpienero** [comment]
@Gamer1120 To elaborate a bit, hacking accounts that have authenticators on them is much easier (i.e shared passwords, cracked databases, etc) than snatching someone's phone. I agree in the idea that this ticket should be denied outright.

**Comment by Gamer1120** [comment]
@Sharpienero Your comment made no sense. You are implying that is it easier to hack an account which uses password + authenticator than an account who has just a password. Do you mind elaborating on that?

**Comment by ypperlig** [comment]
I agree with what's been said here. Enabling 2FA on your account is to make sure in the cases your password is exposed, that they will need the one time pass as well. 

Leaving the secret key with a 3rd party provider (e.g a RuneScape client) gives you a false sense of security, and the entire point of 2FA is gone. You leave your account in the hands of the RuneScape client to make it easier to login..

I'm surprised other clients offer this feature instead of educating the users that would use it.

**Comment by deathbeam** [comment]
This is effectively decreasing security rather than increasing it. Also, we don't want to store sensitive user data at all. This issue should be closed and put to rejected features probably.

**Comment by Gamer1120** [comment]
+1 to deathbeam's comment. Completely agree.

**Comment by Gamer1120** [comment]
@Sharpienero Ah, now it makes sense.

**Comment by deathbeam** [comment]
So I guess this can be closed, we will not be storing authenticator codes on our own.
