### ISSUE TITLE
Blast Mine additions

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2105]
1) Add an 'experience on collect' line which tells you how much experience will be gained by collecting your ore. Experience can be viewed at https://i.imgur.com/OPkCCaB.jpg (via OSRS wiki)

2) Maybe a line that shows the GE value of the current uncollected ore? 

3) The above two could be made into a whole new overlay window that shows ore amount in the sack and the default one hidden, or just put on the side/under the overlay.

**Comment by Adam-** [comment]
Some of this was addressed in #1079.
