### ISSUE TITLE
Elite anagram clue "OUR OWN NEEDS" arrow error

### ISSUE THREAD

**Issue by RobinLaevaert** [runelite/runelite#2106]
So I got this when I tp'd to xeric's look-out, weird thing is that the arrow fixed itself after the correct npc was rendered
![screenshot](https://i.imgur.com/XkM1HS3.png)

**Comment by Roughsketch** [comment]
This is likely because clues that have NPCs are given a nearby location to guide you, and then lock on to the NPC when they're in range. In this case the location is further away from the NPC than it should be.

I can add a fix to #2030

**Comment by deathbeam** [comment]
Fixed in #2030
