### ISSUE TITLE
Xp drops

### ISSUE THREAD

**Issue by markkjaep** [runelite/runelite#2121]
Would it be possible to get some sort of experience drops while doing all kinds of skilling instead of just when doing combat stats? :) 
Also if possible, could you add a "customize" category, so you can customize your own XP drop, size of it, color of it, drop location, how fast it goes away? 

Sincerely
A happy user of Runelite! :)

**Comment by SoyChai** [comment]
Hi mark, the vanilla game already supports everything you're asking for :)

See: https://github.com/runelite/runelite/wiki/XP-Drop

**Comment by markkjaep** [comment]
But isnt that just the OG runescapes xp drops? Thats Not some overlay in runelite? :)

**Comment by Kamielvf** [comment]
Yes, which you can configure with a different colour, different font size, different position, different speed.

**Comment by deathbeam** [comment]
Looks like everything in this issue is already implemented. If you want anything over that, open more specific issue.
