### ISSUE TITLE
Show levels needed for diaries

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2123]
Dunno how to best make this w/o making it look messy af but having the requirements next to the diary tasks would be a neat thing to have.  

So for example ardy elite task currently says:
Catch a Manta ray in the fishing trawler and cook it in port khazard.

Make it something like this:
Catch a Manta ray in the fishing trawler and cook it in port khazard. (81 fishing, ~91 cooking~)

**Comment by marshdevs** [comment]
Working on this.

**Comment by Stickaplex** [comment]
Dunno if its just cause im lookimg on phone  but the white text under the strikethrough makes it a tad hard on the eyes...maybe same color as the other levels? Altho quite close to the same color there so idk

Other than that though it looks fkn sexy

**Comment by marshdevs** [comment]
I agree about the white, I'll play around with some other colors (maybe the blue from the "Members only" above).

When it was all black the sea of text kinda blended together, made it hard to tell which reqs were for which task

**Comment by Stickaplex** [comment]
:)

**Comment by Adam-** [comment]
added in #2251
