### ISSUE TITLE
Remind us Weekly to do Tears of Guthix

### ISSUE THREAD

**Issue by Exstatic** [runelite/runelite#2125]
Since we have daily reminders to get staves or collect rune essence. Why not a weekly reminder that reminds us to do Fist of Guthix?

We can set a day (lets say Saturday) and every Saturday, it notifies us.

Some say its built in the vanilla client but I have personally never seen this.

**Comment by iguaan** [comment]
Quoting the wiki page.

>By talking to Juna, it is possible to toggle alerts upon logging in whenever you are eligible to play this minigame again.

**Comment by deathbeam** [comment]
This is already implemented in game.

**Comment by ShaunDreclin** [comment]
The in-game implementation only notifies you on the first login after weekly reset, it's very easy to miss that notification so I think adding one of our own would be a good idea.

**Comment by StephanBijzitter** [comment]
Above is still the case, I got my ingame notifications enabled but I was two days late this week
