### ISSUE TITLE
Suggestion: Highlight bank (castlewars chest) in colour when runecrafting 

### ISSUE THREAD

**Issue by damane888** [runelite/runelite#2127]
When I am doing lavas, i tend to zoom out my screen as far as possible, so I would be able to see altar, not having to make additional clicks. The problem is that it is difficult to see bank or castlewars chest when you zoom out too far. 
In agility - the steps are highlighted by green colour, marks of grace are highlighted also. Would it be possible to add this option to bankstands and chests?

**Comment by Adam-** [comment]
Use the tile marker plugin to mark the bank tile

**Comment by deathbeam** [comment]
This is too specific and solved with Ground Markers.
