### ISSUE TITLE
Overlay over bank

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#2131]
You know, you can move overlays by holding ALT.

When I'm doing Blast Furnace, there's this one overlay telling me how many ores are in the furnace or w/e.
I'm playing on fixed resolution, so when I open bank - The overlay is behind the bank screen.

Somehow (example. make it toggleable to show overlays over or behind bank - all overlays or just spesific ones)... Or even implement this thing to the Blast Furnace plugin. I think this issue can be in other activities in RuneScape so there's a thought for you on that, but for me I request this spesifically for Blast Furnace.

**Comment by ShaunDreclin** [comment]
Going full customizable with overlay layers could be a pain in the ass but it's probably worth adding an option for this specific overlay (or just change it to always be above the bank)

**Comment by deathbeam** [comment]
You can move the overlay slightly so it will not be in snap corner and it changes layer above bank. Is that what you want? if yes i would consider this issue solved.

**Comment by Popedigoz** [comment]
Well, yes... But as I was talking in the RuneLite's Discord server, Unmoon said it's a bug (that it's possible to move elsewhere) and might be fixed someday, so when it's fixed, it might not be possible anymore - making this issue relevant?

**Comment by deathbeam** [comment]
Huh? I don't see any bug in current functionality.

**Comment by ShaunDreclin** [comment]
I think unmoon was talking about being able to move it on top of the minimap, being able to move them in general is an intended feature

**Comment by Unmoon** [comment]
@ShaunDreclin Yep, I didn't know they change to be on top of bank when moved.

**Comment by deathbeam** [comment]
Changing layers of them when not snapped is intended feature as well.
