### ISSUE TITLE
Show countdown timer to prayer drain in Barrows

### ISSUE THREAD

**Issue by rherms** [runelite/runelite#2134]
I am doing a big Barrows grind right now and it would be useful for potting before fighting Dharok when he is in the tunnels and for knowing if I need to not be so afk and get out of the crypt quickly when fighting the other brothers. Anyone else interested in this feature? If so, I might take a stab at coding it!

**Comment by Reasel** [comment]
Well does the prayer drain at a set rate each time as in 10 each time it procs or is it scaling? If the timer is based on entering then you should be able to time from each tick if you are in the crypts as well as underground. You would need to verify both of those in game yourself most likely and then add it to the barrows plugin.

**Comment by Reasel** [comment]
Yeah it should be a simple thing and would be super useful.

**Comment by FatalWaffles** [comment]
It should drain every 18 seconds, at which rate I'm not sure though.
