### ISSUE TITLE
Add a way to completely delete your synced configs

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#2135]
Title

**Comment by ShaunDreclin** [comment]
I think that will only update the settings that currently exist, it won't clean out settings you used in development that have since been removed

**Comment by Alexsuperfly** [comment]
afaik this can now be done by importing a fresh default config into the synced one by using the import button in the info tab

**Comment by Nightfirecat** [comment]
This is now possible by creating a new config profile and deleting or no longer using the previous profile(s).
