### ISSUE TITLE
Find a way to get Viggora's position per player

### ISSUE THREAD

**Issue by Roughsketch** [runelite/runelite#2142]
[Viggora ](http://oldschoolrunescape.wikia.com/wiki/Viggora)can be in three different places depending on the route that was randomly assigned to the player in the[ Curse of the Empty Lord](http://oldschoolrunescape.wikia.com/wiki/Curse_of_the_Empty_Lord) miniquest. To make the clue plugin display his location would require knowing which location he is for the player, but I do not believe we have a varbit for this miniquest or Viggora yet.

**Comment by Roughsketch** [comment]
Preferably there would be a way to check without user interaction, but if there isn't an easy way to do it then this can be the hacky fix.

**Comment by Nightfirecat** [comment]
@Macweese how did you come up with these values?
