### ISSUE TITLE
Display hit beside experience drop

### ISSUE THREAD

**Issue by Subhaven** [runelite/runelite#2144]
Use `ceil(hpXp * .75)` and [bonus experience multipliers](https://imgur.com/75jYsCw) to determine your hit from the experience drop. 

The multiplier can be calculated using the formula:
 `Multiplier = 1 + floor(floor((AttackLevel + StrengthLevel + DefenceLevel + HitpointsLevel)/4)*(floor((StabDefBonus + SlashDefBonus + CrushDefBonus)/3) + StrengthBonus + AttackBonus)/5120))/40`
(see [here](http://services.runescape.com/m=forum/c=PLuJ4cy6gtA/forums.ws?317,318,712,65587452,209,337584542#209))

**Comment by dztance** [comment]
Would be dank <3 ill have a crack on it when I have some time tomrorow

**Comment by Noizexx** [comment]
We were requested to remove this plugin from OSBuddy. Wouldn't waste my time on it.

**Comment by LlemonDuck** [comment]
This can now be achieved with InstantDamageCalculator on the Plugin Hub: https://runelite.net/plugin-hub/show/instant-damage-calculator
