### ISSUE TITLE
Add a panel that shows how much XP all the herbs in my inventory give

### ISSUE THREAD

**Issue by marvinwz** [runelite/runelite#2152]
I have a suggestion
I'd like to see the amount of XP I would get when, for example, I have them all noted in my inventory. 
Over time by doing slayer, I collected alot of herbs. It would be very helpful to instantly see how much xp all these herbs would give me, if I all used them, for example, on the highest potions available (for me). 
Thanks for reading!

**Comment by LeviSchuck** [comment]
What reference of XP makes the most sense here?
Just the amount it takes to clean the herbs when grimy? 
What about when they are clean?

**Comment by marvinwz** [comment]
The highest possible potion you can create. If this isn't easy/possible, Maybe a settings panel where you can select what potion you make with a herb?
I mean clean herbs to potions but cleaning them would also be useful. But clean to potions is way more needed.
Example, I got 100 irit leaves. I take them noted in my inventory and now I see that if I used all my 100 irit leafes to create (For example) super attacks, I would get 100 x 100 = 10k xp.
Now I also take 100 Avantoes out. I would see in the panel that if I used all 100 avantoes, I would get 100 x 117.5 = 11750 xp
Add this together and I would see that my 100 avantoes and my 100 irits would get me 21750 xp.
I hope this explains it well!

**Comment by deathbeam** [comment]
This seems very useless, and there is herb box what makes it also wrong
