### ISSUE TITLE
Runelite doesn't work with GPU at all

### ISSUE THREAD

**Issue by TaxoRubio** [runelite/runelite#2157]
Until the last update I would set my Nvidia GPU as the primary renderer for the game's graphics and it worked flawlessly. Now it is always shown as inactive and I can't play with the GPU anymore, which makes other activities a pain. I'm submitting this as an issue becuase I've tried configuring the Nvidia in many ways and it hasn't been fruitful.

GFX model: Nvidia GeForce 840M (in case it can be helpful)

Feel free to delete this if it doesn't fit as a client issue, I'll understand

**Comment by deathbeam** [comment]
Are you sure you are running latest launcher? E.g 1.5.1

**Comment by TaxoRubio** [comment]
The latest I can download from runelite.net is 1.3.6. Where do I download 1.5.1 from?

**Comment by Kamielvf** [comment]
1.5.1 is the launcher version, not the client version. If you have downloaded runelite recently your launcher version is most likely up to date.

**Comment by deathbeam** [comment]
Any update? Launcher update should solve this.

**Comment by TaxoRubio** [comment]
Sorry, had lots of things to do irl. I confirmed by reinstalling and even downloading from the launcher repo that the launcher version is indeed 1.5.1. The GPU is not showing any activity. I've tried assigning the .exe again in the Nvidia Control Panel, but it didn't work :(

**Comment by Gamer1120** [comment]
I'm experiencing the same issue. Win 10, i5-7300, GTX 1060. I'd prefer RuneLite to run on the GTX 1060, so I can watch livestreams better, since that consumes a lot of CPU as well.

**Comment by deathbeam** [comment]
I guess this is not even an issue after all, OSRS runs on CPU so I dont understand where is the problem.
