### ISSUE TITLE
Bank value sometimes multiplies

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#2159]
For whatever reason the bank value sometimes multiplies (x2 mostly, but also had x3 happen).
As much as I'd like a bigger bank, this isn't ideal.

I'm not sure how to replicate this issue as it seems to happen very randomly.

**Comment by capSAR273** [comment]
If you take an item out to significantly change the bank value does it cause the inaccuracy then? Or is this just from opening and closing the bank several times?

**Comment by deathbeam** [comment]
Is this still an issue?

**Comment by Kamielvf** [comment]
I have not used the bank value plugin for a while but I'll turn it back on and see if it occurs still.

**Comment by Kamielvf** [comment]
Closing this as I cannot seem to reproduce this issue. Must have been resolved somewhere among the changes.
