### ISSUE TITLE
RuneLite repetitive pattern screen (Linux)

### ISSUE THREAD

**Issue by Kart5a** [runelite/runelite#2168]
My RuneLite on Linux looks like this https://imgur.com/En8xfZf
I really don't know what's happening there. I tried to install java 2 times but no difference.

**Comment by Kamielvf** [comment]
Try launching the jar with `--mode=OFF` passed to it

**Comment by Kart5a** [comment]
@Kamielvf Wow, that was quick and it worked, thanks mate :) Should i delete this?

**Comment by deathbeam** [comment]
This is launcher issue, and I believe we closed the ddraw ones after we added the possibility to set the param, so I guess yea, or open issue in https://github.com/runelite/launcher
