### ISSUE TITLE
Cannon has constant increment shown

### ISSUE THREAD

**Issue by Fox4148** [runelite/runelite#2181]
When I left the slayer cave, i had some cball in my cannon. 
When i came back, *empty cannon* i had an increment of 10 on the cball count.
when I load my cannon it goes to 40 total cball.

**Comment by Fox4148** [comment]
I didn't picked up my cannon yet, wich i know could solve the issue, it is just a minor bug

**Comment by iguaan** [comment]
Fixed in #2020
