### ISSUE TITLE
Tile and NPC Marker tag/untag mark/unmark

### ISSUE THREAD

**Issue by TheArbalist** [runelite/runelite#2184]
Could NPCs and Tiles you've already marked have the "Tag" right-click option be changed to say "Un-tag"?
When there are multiple NPCs in close proximity, it can make it impossible to tell which NPC you're trying to remove a tag from. It can also be difficult to tell if you've right-clicked the correct tile, and you may end up marking *another* tile accidentally, when all you wanted was to remove the tag from it.

**Comment by adwitkow** [comment]
I think this can be closed as #9389 has been merged.
