### ISSUE TITLE
configure shift click on equipment screen

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2203]
preferably a different set of shift clicks as the left/right clicks are typically different but be able to shift click config on the equipment screen. 

useful for jewelry and other teles an such

**Comment by SunWithFaceClap** [comment]
Or better yet, customize the Left Click command (ex; 1-Click Glory Tele etc.)

**Comment by Stickaplex** [comment]
Why not both?

**Comment by couxo** [comment]
i feel like adding a toggle to enable pressing Shift to activate menu swap is the best solution in general

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
