### ISSUE TITLE
Smaller font for overlays removed?

### ISSUE THREAD

**Issue by Fromnz** [runelite/runelite#2205]
you use to be able to make the font size for boost overlays etc smaller but i cant seem to find that option anymore?

**Comment by Reasel** [comment]
I believe [#1999](https://github.com/runelite/runelite/pull/1999)will fix it.

**Comment by Fromnz** [comment]
sorry im completetly code retarded, how do i change it?

**Comment by Reasel** [comment]
It **will** fix it. Its waiting for review right now. If it is merged it will be available on thursday. You are completely fine. Just letting you know that someone has worked on the issue! :)
