### ISSUE TITLE
Medium clue - wrong NPC to kill

### ISSUE THREAD

**Issue by aarlin** [runelite/runelite#2209]
This is for the cryptic clue,
`Search the upstairs drawers of a house in a village where pirates are known to have a good time.`

I didn't take a screenshot but it was marking both Pirate Guard and Pirate. Only the latter drop the key needed for the clue.

**Comment by Roughsketch** [comment]
Should have been fixed in #2119

**Comment by aarlin** [comment]
Ah thanks for quick response. Cheers
