### ISSUE TITLE
Low hitpoint notification occurs in Nightmare Zone even with absorption potions being used

### ISSUE THREAD

**Issue by millettmb** [runelite/runelite#2210]
At the moment, the low hitpoints notification goes off when a user takes an overload potion and has absorption points remaining. This can be troublesome, as a user may take an overload and then change windows, and when the overload knocks the player down to 1hp, the notification will occur. 

Obviously the user would not wish to be notified of their low hitpoints when they have absorption points, as there is no way of them dying.

The `IdleNotifierPlugin` should be modified to check `if (client.getVar(Varbits.NMZ_ABSORPTION) != 0)`, and only set `checkLowHitpoints()` if the player doesn't have absorption points.

There is no use case that would be in jeopardy if this change is made.

**Comment by SoyChai** [comment]
I would expand this check to first confirm whether the Absorption notifications from the NMZ plugin are enabled. If they are not, this plugin should continue working by *including* the absorption points in the remaining HP total, to prevent any nasty surprises.
