### ISSUE TITLE
Accurate volume slider

### ISSUE THREAD

**Issue by JWalty** [runelite/runelite#2213]
Instead of making the volume slider go from deafening to deafening but on the left, would it be possible to make the in-game volume slider have more accurate control of the game volume?

**Comment by Adam-** [comment]
I looked into this before. The slider ingame is actually just a series of 4 images that are made to look like it slides. It would be fairly difficult to change the ingame slider to actually slide with more granularity. Maybe we could make a plugin with a separate volume control though.

**Comment by Adam-** [comment]
#9899 added a config option for volume to override the in-game volume.

**Comment by Seppobb** [comment]
@abextm @Adam- @JWalty   I belive this plugin/update on RL has been broken due to Jagex updating the settings menu. I tried searching for a solution to this but couldn't find one. Will this be adapted in the RL itself, or maybe the music plugin?
