### ISSUE TITLE
Mage Training Arena plugin

### ISSUE THREAD

**Issue by Nathan-cook1** [runelite/runelite#2218]
In the mta alchemy room, the items are always in the same order in a clockwise direction

Boot
Shield 
Helm
Gem
Sword
Empty * 3

I was wondering if it was possible, so if you searched and found and item during that current rotation (40 secs or so), it could display the locations of the rest of the items on the alchemy cupboards, perhaps highlighting the one worth 30 coins.

**Comment by TheArbalist** [comment]
I wrote a rough plugin for this a couple of weeks back, which also includes the Graveyard room.
May make a pull request when I feel that it's more complete.

**Comment by jpabeem** [comment]
@capSAR273 Rogues 'den is also approved with almost the same functionality, it's a grey area imo.

**Comment by Adam-** [comment]
Added in #3596
