### ISSUE TITLE
Multiple plugin setting profiles

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#2220]
Depending on the activity I'm doing, I use vastly different plugin settings. Right now I have to manually enable/disable and change a dozen plugins settings multiple times every day.

**Comment by Kamielvf** [comment]
For now a workaround would be logging in with different google accounts. I know this wouldn't be ideal but for the meantime it works. Also when logged out your settings should be different than the ones when logged in.

**Comment by DillonDerner** [comment]
This would be amazing!

**Comment by ruscur** [comment]
Yeah, this would be great.  The main thing I'm after is to have multiple devices on the same account but different GPU profiles for example.

**Comment by ruscur** [comment]
Documented a workaround to enable having different settings per-account for Linux users

https://russell.cc/runelite/

**Comment by AverageHumanoid** [comment]
@ruscur Basically you just need Runelite to use a different config directory which can be done with an alternative and I think simpler solution. Using the firejail program you can create a sandbox with the mount namespace of the home directory changed to any existing directory.

```
$ mkdir alt{1..3}
$ firejail --private=alt1 java -jar RuneLite.jar
$ firejail --private=alt2 java -jar RuneLite.jar
$ firejail --private=alt3 java -jar RuneLite.jar
```
https://firejail.wordpress.com/documentation-2/basic-usage/#private

**Comment by SirKhaoz** [comment]
The issue, at least to me, is mostly that (for arguments sake) I play on one account.

I have two devices, a computer at my home (powerful rig) and a macbook pro which does not like intensive GPU usage.

It would be fantastic to be able to have two profiles I can switch between. Now I know I can set up another profile or log out of runelite on the laptop, however this means:
1. I do not get accurate or updated farming/timers tracking
2. I do not get collated loot-logging
3. I do not get any other plugin-shared information like bot-busting for example
4. I do not get changes to plug ins I DO want to sync, like perhaps I update my shift-click swaps or NPC highlights - this would not sync if I was logged out or had a different profile on one machine.

It would have the added benefit outlined here: https://github.com/runelite/runelite/issues/13823 where even if you had only one machine (perhaps less powerful) you could quickly swap in and out plug ins depending on activity to reduce load on your client/machine.

**Comment by pwatts6060** [comment]
If you want to use different settings for different accounts, you can use multiple RuneLite (Google) accounts, and easily switch between them: https://github.com/runelite/runelite/wiki/General-Features#playing-with-multiple-accounts

**Comment by Jademalo** [comment]
https://github.com/antero111/plugin-presets

Just wanted to shout out Plugin Presets from the plugin hub, which basically covers this request completely. I've been using it for the last few weeks, and it's perfect.

**Comment by APKiwi** [comment]
I've been testing this for three months and this has been exactly what I was after, and solved each of my problems. Thank you very much for sharing this, a fantastic plugin.

**Comment by Nightfirecat** [comment]
Config profiles were added in 831189459ba51538b239a33b7d632bd2d9e4e8a3.
