### ISSUE TITLE
Chat Text Recolor

### ISSUE THREAD

**Issue by neverrebuild** [runelite/runelite#2224]
i see there is an option to change chat color based on its appropriate msg type, but when i change them nothing happens. i tried restarting the client after i changed them still nothing.
the chat commands option is checked on as well
please help i really want to use this client but i am colorblind and need to change my colors

**Comment by deathbeam** [comment]
Yeah we are planning to add that, but noone actually started looking at it yet.

**Comment by LeviSchuck** [comment]
What messages would you want to color?
Things like game events, public text, friend text in public, friend direct message, clan chat, and so on?

**Comment by deathbeam** [comment]
I think that is the request yea.

**Comment by psikoi** [comment]
I was thinking of adding a general color blind support after I was done with my current ui project. @neverrebuild do you have discord? I'd like to talk to you about it as I am not color blind.

**Comment by Antedekebab** [comment]
Also the "valueable drop" that appears in the chattbox are coloured red so hard to read if you could make that colour changeable aswell. Runelite allows me to change the colours on the drops on the ground but not the chattbox.

Also add colour option for untradeable notifications?

**Comment by SirLehto** [comment]
Please have this request as a high priority. Being able to recolor messages from clan chat, public chat, the seperate private chat is something this client really is missing

**Comment by Antedekebab** [comment]
Also the boss timers from runelite, antifire timers etc changes colour from white to red the last 10/30secs thats also a thing I cant see.

**Comment by Adam-** [comment]
Added in #3421
