### ISSUE TITLE
Fishing Spots in Rellekka not highlighted

### ISSUE THREAD

**Issue by Cwade789** [runelite/runelite#2228]
As the title suggests, I have noticed fishing spots in Rellekka are not highlighted. Could someone please code that in and add them to the list? That would be awesome. Thank you.

**Comment by jpabeem** [comment]
Could you provide us with a location or picture so we know where this exactly occurs?

**Comment by Cwade789** [comment]
![2018-05-01_15-40-19](https://user-images.githubusercontent.com/38387926/39490286-6048fb32-4d56-11e8-966e-5eccee26539c.png)
![2018-05-01_15-39-49](https://user-images.githubusercontent.com/38387926/39490287-60563b44-4d56-11e8-9e4b-033cd1ea82e1.png)

**Comment by Cwade789** [comment]
@jpabeem I hope this helps

**Comment by jpabeem** [comment]
It does, thanks! I'll see if I can add the spots in a bit.
