### ISSUE TITLE
[Clue] Traiborn is on the 1st floor, not 2nd.

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#2232]
Runescape uses british floor numbering, so the "area" for clue 19764 needs to be changed to say 1st floor

**Comment by Nightfirecat** [comment]
Duplicate of #1882

**Comment by ShaunDreclin** [comment]
Not duplicate, that one is talking about the floor numbering in general

**Comment by Nightfirecat** [comment]
Ah, good point. It does make specific mention to this clue, but you're right.
