### ISSUE TITLE
Disable Certain Sounds

### ISSUE THREAD

**Issue by RileyMichael** [runelite/runelite#2240]
Having a toggle to disable common sounds would be a really nice feature. Turning off game area sounds & turning them back on when you visit populated areas isn't the most convenient thing, and this could alleviate it. (e.g. toggle for "Fletching", "Pets", "Alching" etc)

**Comment by SoyChai** [comment]
Does alching make a sound when other players do it? That'd be a nightmare. Good idea though.

**Comment by Nightfirecat** [comment]
The [Annoyance Mute plugin](https://runelite.net/plugin-hub/show/annoyance-mute) on the hub can do this.
