### ISSUE TITLE
Zulrah helper

### ISSUE THREAD

**Issue by vanzoest96** [runelite/runelite#2241]
This would be a great feature for those who aren't very experienced in killing Zulrah. (Players such as myself)

So basically a Zulrah helper wich shows you where the next spawn will be, if it'll be range/mage/melee/jad and where to stand during that spawn. (A great example would be the Zulrah helper from the Exilent client)

**Comment by ypperlig** [comment]
See https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

> In-game Zulrah Helper: Removed at Jagex's request (see 1.2.13 blog, relevant discussion in #1386)

**Comment by forfiet2** [comment]
reference this https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features #1386
