### ISSUE TITLE
screenshot upon boss kill with some customizable options

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#2247]
screenshot upon boss kill with:

-Option to have screenshot of individual boss in own folders within screenshots folder
-Option to customize name format of screenshot file, killcount/date/time. in whatever order one chooses.

**Comment by Reasel** [comment]
What are you trying to get from this? Showing what the boss dropped in terms of the in game chat message or what?

**Comment by buldosis** [comment]
@Reasel yes that was the idea. A lot of people i know and including myself like to have picture logs of drops but the process can be very tedious. I'd imagine this feature could take alot of disk space so would probably be off on default but would be a really nice thing to have.

**Comment by Reasel** [comment]
If you are just looking for a screenshot of the chat when you get a kill I think I might be able to rig that up via [#2249](https://github.com/runelite/runelite/pull/2249). Ill give it a go tomorrow to see if I can nail it down.

**Comment by DeeJayLove** [comment]
Came here to suggest this! i think it'd be a great addition.

**Comment by deathbeam** [comment]
Looks like screenshotting of boss kills was implemented, rest of the request should either be separate issue or discarded (as it is not useful and probably wont be implemented)
