### ISSUE TITLE
Cerberus Plugin: Ghost Icons Missing or Incorrect

### ISSUE THREAD

**Issue by RudeDude-420** [runelite/runelite#2252]
Sometimes the ghost overlay has missing and incorrect icons. This seems to happen after killing Cerberus while the ghosts are spawned and about to attack, although, I'm not sure if this was merely a coincidence or the actual cause. I'll add a screencap if I can get one without dying.

**Comment by deathbeam** [comment]
Are you sure you saw all the ghosts when they spawned? If they are out of sight it sometimes do not properly register.

**Comment by RudeDude-420** [comment]
I'm not sure, but I did notice that the overlay stays messed up until another round of ghosts has come and gone.

**Comment by Sociopaat** [comment]
i can confirm that sometimes the ghosts still does'nt show correctly in the new update
got the wrong order 2 times in 17 kills

**Comment by deathbeam** [comment]
Did you saw all 3 ghosts when they spawned?

**Comment by Sociopaat** [comment]
hmm that's a good one, cerb has some hp left i needed to kill those ghosts
but didn't look at the spawn of them
i can look at it to see if something is different next time
