### ISSUE TITLE
Mage Training Arena helper

### ISSUE THREAD

**Issue by CaraPis** [runelite/runelite#2256]
Would be cool to see a helper for this minigame. For example, in the telegrab room it tells you where to stand for each puzzle, alchemist room it tells you where all the items are once opened a chest + a timer that tells you when the next rotation happens. I don't thinks the other rooms need any kinda helper. Now the question is, if it is possible to create and if it would be allowed. I don't see this to be OP or so, since all the puzzle solutions are found on the wiki and alchemist room always has the same rotation in items once you know where one item is.

**Comment by capSAR273** [comment]
See #2218 for a similar suggestion, but I believe this is a gray area for how much the client would be telling the player what to do and where to stand. Just my opinion.
