### ISSUE TITLE
[Suggestion] Shift+Backspace to clear chatbox

### ISSUE THREAD

**Issue by rlw0014** [runelite/runelite#2277]
shift+backspace to clear text in current chat box

**Comment by Nightfirecat** [comment]
Related: ctrl+backspace to clear up to last space

**Comment by deathbeam** [comment]
I don't think we want to provide any enhancements to chatbox typing, correct me if I am wrong. Also, fix your title to be more descriptive.

**Comment by deathbeam** [comment]
Already implemented
