### ISSUE TITLE
Medium clue scroll emote clue overlay error

### ISSUE THREAD

**Issue by buttonpoker** [runelite/runelite#2280]
<img width="627" alt="medcs" src="https://user-images.githubusercontent.com/36622019/39562274-9a32145a-4e5f-11e8-90d2-3889cce490c6.png">

The runelite overlay is showing mithril platelegs when it should be the platebody. Appears to be correct under "EmoteClue.java" though.

**Comment by devLotto** [comment]
Yes, it will be fixed in today's release
