### ISSUE TITLE
Can't get past 0% on Runelite launcher

### ISSUE THREAD

**Issue by korolex1** [runelite/runelite#2281]
Tried everything to do with changing internet dns, restarting, redownloading etc.. Something about error in bootstrapping, Here are the logs
[launcher.log](https://github.com/runelite/runelite/files/1969943/launcher.log)

**Comment by bloodma** [comment]
Also experiencing this issue, tried uninstalling and reinstalling, resetting my router and computer, standard osrs launcher works fine. 

[launcher.log](https://github.com/runelite/runelite/files/1970024/launcher.log)

**Comment by deathbeam** [comment]
Duplicate of https://github.com/runelite/launcher/issues/18

**Comment by korolex1** [comment]
@deathbeam literally no response on that one in 2 days but this one gets a response in 20mins?
