### ISSUE TITLE
Wintertodt plugin

### ISSUE THREAD

**Issue by wajabirap** [runelite/runelite#2290]
It would be nice to have a Wintertodt plugin, have features that could display your current action like Firemaking, Fletching, Woodcutting or idle. It would also be extremely helpful as well if within this plugin certain items hidden while they're on the floor. The most common thing I see on the ground are just empty jugs or empty vials.

**Comment by jpabeem** [comment]
Wouldn't an entity hider make more sense here? Displaying the current action doesn't seem important enough info to grant it it's own plugin imo.

**Comment by RomeuG** [comment]
Just hide the items.

**Comment by AmazingJesus** [comment]
Indicator where snow is going to fall?

**Comment by FearrMe** [comment]
@AmazingJesus https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

was removed

**Comment by jbfleischman** [comment]
#4662 wintertodt plugin PR here, includes the suggested requests (minus the item hiding) and some more goodies

**Comment by deathbeam** [comment]
Looks like we added WT plugin already
