### ISSUE TITLE
Regression: Client game window changes size when sidebar is opened or closed

### ISSUE THREAD

**Issue by Jimbimanim** [runelite/runelite#2291]
Before today's update, if you expanded the sidebar with one of the sidebar buttons the game window would stay the same size and the client window (not the game window) would expand to fit the sidebar in without altering the size of the actual game window.
Since today's update, when expanding the sidebar the game window reduces its size to fit the sidebar in and stays small when the sidebar is closed again, meaning i have to resize my client every time i open or close the sidebar.
Manually putting in values and locking the client size (in the main runelite plugin) makes no difference, this still happens

I believe this used to happen when i first tried out the client maybe around 4 months ago but was fixed since then, something in this update seems to have broken whatever fix was done

Not sure if i described this very well, please let me know if it isnt clear

I am on Runelite 1.3.7 on linux mint 18.3 with java version 1.8.0_162

Edit:
I have just tried the brand new button that completely hides the sidebar and this works as expected (how the sidebar buttons worked previously, but of course hiding the entire sidebar instead of minimising)

edit 2:
After further testing the brand new button causes this same behaviour when the sidebar is expanded, but not when it is in its minimised form. The new hide button only works as expected with the sidebar minimised

**Comment by Astug** [comment]
This also effects the game size (resolution) you set. It applies that resolution to the game window without taking into account the sidebar. When you then close the sidebar (after setting the game size) the game window expands to the size of the client window, which is the game size you set + the size of the sidebar.

I hope that makes sense.

I feel like the sidebar should always expand the client size and never effect the game size you set.

**Comment by Jimbimanim** [comment]
update:
this issue is still prevalent on 1.3.8 even with woox's new feature, but now it works as intended as long as "lock window size" is also enabled (this wasnt the case in 1.3.7)

i have tested the client in a few VMs and this seems to be a linux-specific issue as it works flawlessly under windows.
i have tested the kde plasma 5 and cinnamon 3.6 desktop environments (with kwin and mutter WMs respectively) and on both of these the game window changes size when the sidebar is shown/hidden or expanded/minimised unless the "lock window size" in the main runelite plugin is also enabled

this used to work properly just as it does on windows until the 1.3.7 update last thursday, something in that update broke it

**Comment by deathbeam** [comment]
This is fixed already when having setting keep game size on.
