### ISSUE TITLE
Allow for client to be manually re-sized when Maximized

### ISSUE THREAD

**Issue by BoulderFalcon** [runelite/runelite#2294]
On OSBuddy, when you maximized the game client, you could move your mouse to the right or left edges of the screen and the manually adjust the screen size. 

Currently for RuneLite you can only manually adjust when the client is not maximized, and you must position it yourself. (unless I'm missing something)

**Comment by deathbeam** [comment]
I don't think what you are describing is maximized client. You can't resize maximized window, because it is maximized, that is how it works literally everywhere.

**Comment by BoulderFalcon** [comment]
Hmmm I'm not sure. Maybe with OSB it was not actually maximizing? When you clicked maximize on OSB it would snap the window edges to fit your screen, but if you hovered over them you could resize it. 

Not sure how to enable snapping though - when I drag the RuneLite window past the edge of the screen currently it just goes past the border and stays there.

**Comment by SoyChai** [comment]
>Not sure how to enable snapping though - when I drag the RuneLite window past the edge of the screen currently it just goes past the border and stays there.

Edge snapping doesn't work with our fancy default window mode, you have to disable it in the RuneLite plugin under the wrench tab to use native window frames.

**Comment by BoulderFalcon** [comment]
> Edge snapping doesn't work with our fancy default window mode, you have to disable it in the RuneLite plugin under the wrench tab to use native window frames.

Dang thanks man, this client has it all.

**Comment by deathbeam** [comment]
Looks like this is not actual issue
