### ISSUE TITLE
2 accounts on 1 client

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2298]
![image](https://user-images.githubusercontent.com/37475765/39593474-c60f9f28-4f01-11e8-9084-52e9b0dfb072.png)
maybe we are able to play on multiple accounts on 1 client and don't need to open two client?

**Comment by Floukru** [comment]
Certainly would love to see this.

**Comment by permedd** [comment]
thanks for the support man, yeah i don't really like using two clients not a big fan of it and it certainly covers a lot of space :( i think so many players would use this where they want to afk their mains and play on their other accounts etc.

**Comment by deathbeam** [comment]
Closing for same reason as #5540
