### ISSUE TITLE
Native desktop notifications

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#230]
Hello, I just found out about this awesome project. I tried running it on OSX, and I tried the idle plugin, and based on source code I found out that you are using TrayIcon to send notifications, what seems to not work under OSX. 

What about sending the native notifications? I was using plugin for maven called maven-notifier that was sending notifications on build success/failure and it was correctly sending native notifications on Windows, Linux and OS X, and it is using this nice [library](https://github.com/jcgay/send-notification) for sending the native notifications. If I would have enough free time I guess I can create pull request by myself to implement this, but I cannot promise anything, and I am not sure if this feature is wanted, but it would be definitely cool to have.

**Comment by Adam-** [comment]
I think native notifications would be great. I just googled it some and it looks like notifications on OSX pop up a dialog box? Which is definitely not what is intended. Feel free to submit a PR using better notifications.
