### ISSUE TITLE
Add Kill Count notification in the chat for the boss log

### ISSUE THREAD

**Issue by Fox4148** [runelite/runelite#2307]

**Comment by deathbeam** [comment]
There is already kill count chat notification for each boss.

**Comment by Fox4148** [comment]
well apparently not
I don't have any kill count notification in my chat.

https://postimg.cc/image/cg6czffwd/

**Comment by deathbeam** [comment]
Go to OSRS settings (wrench) and click I think on balloon (notifications) and tweak it there

**Comment by Fox4148** [comment]
I can't see the setting "Notification" , and I've tried every wrench and not able to find anything related to kill count

**Comment by Rheon-D** [comment]
- [Go here click the thing](https://i.imgur.com/QsZpd2d.png)
- [Select Unfiltered](https://i.imgur.com/9OF4unp.png)
- ???
- Profit <s>snake<s>
