### ISSUE TITLE
Hot/Cold Clue Solver

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2318]
https://twitter.com/bitterkoekjers/status/840219782372839424

I feel this would be hard to implement, but if done would be amazing. If you knew the exact ranges of what each temperature meant for how close you are to the clue (not sure if that is documented anywhere) then you could effectively have a plugin that narrows down the locations for you over time.

**Comment by Eadgars-Ruse** [comment]
I've got a working solution for this. I need to clean up my code and work on the UI a bit, but I should be able to do a PR soon.

Here's some teasers:

https://streamable.com/370tj

https://streamable.com/hrgrq

https://streamable.com/gb8bn

**Comment by Adam-** [comment]
Done in #2412
