### ISSUE TITLE
2006 In-game Interface

### ISSUE THREAD

**Issue by Viizva** [runelite/runelite#2322]
Can we please get a 2006 interface? I am sure a lot of people would love it and its one thing that I enjoy using that Runelite doesn't have yet.

A lot of the assets were made by a reddit user and posted here - https://www.reddit.com/r/2007scape/comments/54kbbw/2005_era_interface_for_old_school_assets_made/

**Comment by Viizva** [comment]
Done. This can be deleted and closed. I posted there!

**Comment by Veteranhd** [comment]
You can do better on the interface chatbox make it look like the original
