### ISSUE TITLE
Pre-EOC Xp Drops

### ISSUE THREAD

**Issue by Viizva** [runelite/runelite#2323]
Another client had this option and would be great if more customizable xp drops were added. Below is an example!

https://streamable.com/u8ppz

**Comment by TzZek** [comment]
It's all about the aesthetics, I would love to see these implemented. I know client uses vanilla drops currently but these are 🔥🔥🔥🔥

**Comment by zeruth** [comment]
You can move the xp drops to mid screen. as far as resizing and recoloring not sure.
https://github.com/runelite/runelite/wiki/XP-Drop

**Comment by TzZek** [comment]
@zeruth , I currently have a PR open for the recoloring of the XP-Drops, nothing for resizing or changing the fonts yet.

**Comment by zeruth** [comment]
And actually native XP Drop config allows you to recolor, resize and reposition. Not really sure this is needed at all.

**Comment by TzZek** [comment]
Yes but it only offers a set number of colors, https://i.imgur.com/1wz3AAt.png , 8 colors , some people prefer to set exact colors and or something not offered by vanilla.

**Comment by Nightfirecat** [comment]
159c239908e844d9e22d2a32b67d450b6da5d0b2 added support for recoloring your XP drops to any arbitrary color, which is the only thing that was really missing for this feature to be available. Center your XP drops, hide the skill icons, and set the color to whatever you want, and you'll have Pre-EOC style XP drops.
