### ISSUE TITLE
Mac OS no xp drops

### ISSUE THREAD

**Issue by MeatM0untan** [runelite/runelite#2325]
No xp drops are visible, potentially disabled feature on accident but can't find anything.

**Comment by SoyChai** [comment]
We're using the vanilla XP drops, refer to this article: https://github.com/runelite/runelite/wiki/XP-Drop

**Comment by MeatM0untan** [comment]
I apologize, I opened the vanilla client and the same issue is present. Not sure if issue is specific for me or the client for mac os in general.

**Comment by MeatM0untan** [comment]
After clicking on your link I feel like an idiot, this fixed it.
