### ISSUE TITLE
Low contrast on the farming panel's progress bars

### ISSUE THREAD

**Issue by SoyChai** [runelite/runelite#2326]
Reported by a Discord visitor. Farming timers are difficult to read at a glance due to the similar shades of green (or if diseased, yellow) used for each half of the progress bar.

Naturally the whole bar has to be coloured so a crop's health can still be seen during early growth, but perhaps lighter & darker shades should be used?

![](https://runelite.net/img/blog/1.3.7-Release/farming.png)

**Comment by Nightfirecat** [comment]
Fixed in #1419, whenever that ends up getting merged?

**Comment by deathbeam** [comment]
The UI has been reworked so I believe this is non-issue anymore
