### ISSUE TITLE
Next stat change infobox reappears when hitting zero

### ISSUE THREAD

**Issue by Pupper3** [runelite/runelite#2327]
Currently the next stat change infobox resets so that other boosts are reorganized for 1 second. Having it loop without restarting would be more natural.  I'm not certain but I assume the infobox would have to display all the time for it to run without resetting like this instead of waiting for a stat decrease. 

![2018-05-04_04-10-42](https://user-images.githubusercontent.com/16019892/39618304-227f8f3a-4f51-11e8-983b-190d8222927f.gif)

**Comment by deathbeam** [comment]
This was fixed already
