### ISSUE TITLE
Farming Tracker Update

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2328]
First off loving the tracker so far and ive only used it for like 5mins so cheers for that =)

Just have a few suggestions to make it look a tad better

-Move harmony patches to the bottom of the list instead of the middle. I know its done alphabetically currently but harmony is quite a high level unlock and (imo) it looks a tad off not being able to use one in the middle. Thats just personal pref though.

-Have the progress bar a bit "thicker". In combo with #2326 would make it quite a bit better imo. Not quite as big as it was before though.

-When its just weeds have it a "blank" color. I know its probably due to the fact that there is *something* there but its not really like anybody tracks the growth of their weeds =p

I know a lot of this is prolly nitpicky but w/e

**Comment by psikoi** [comment]
Full grown weeds will be hidden in #1419, only growing weeds will show progress (but how often does anyone let weeds grow anyways)

**Comment by deathbeam** [comment]
1 request per issue please, i believe we have already some issues open from the list here, if not, feel free to make separate issues
