### ISSUE TITLE
Herbiboar plugin

### ISSUE THREAD

**Issue by Floukru** [runelite/runelite#2331]
@![image](https://user-images.githubusercontent.com/38350898/39628126-b16f2020-4fb0-11e8-8b04-2d049b652aca.png)

While watching someone's stream I saw this client (OSB PRO) having it.

PROS:
- Easy to use
- Turds can follow this (jks)
- We love RL  (jks)

CONS: 
- NONE  (jks)

**Comment by deathbeam** [comment]
Herbiboar plugin is already feature of RuneLite, it was also there before OSB had it.
