### ISSUE TITLE
Login screen bug

### ISSUE THREAD

**Issue by EytanMorg** [runelite/runelite#2334]
On linux
open RuneLite.jar with `java -jar RuneLite.jar`

gets stuck before login screen with the background displayed as multiple tiles (see picture).
![screenshot from 2018-05-04 17-34-15](https://user-images.githubusercontent.com/12435345/39636966-060aed4c-4fc2-11e8-8645-1d4baf642a62.png)

**Comment by deathbeam** [comment]
This will fix it: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by EytanMorg** [comment]
Thanks man, that fixed it
