### ISSUE TITLE
Idle notifications doesn't bring client to the front on Windows 10

### ISSUE THREAD

**Issue by fiya1d** [runelite/runelite#2335]
Windows 10 plays a toast during the idle notification but doesn't switch to the client or bring it to the front of my screen

'Send notifications when focused' and 'Request focus on notification' are both selected under Runelite settings

**Comment by deathbeam** [comment]
This is OS specific functionality, I don't think we can do much about this. The game requests focus correctly, what happens next is unknown.

**Comment by patriqdesigns** [comment]
I also am experiencing this, also in Windows 10. 
If it helps I am in the last Windows 10 update, the one who introduced the "Focus" mode.
Also I have custom chrome disabled.

**Comment by orlp** [comment]
Still experiencing this :(

**Comment by Blinzerr** [comment]
Anyway this can be fixed?
