### ISSUE TITLE
Tutorial Island : Achievement diary reward bug

### ISSUE THREAD

**Issue by GETrackerDan** [runelite/runelite#2337]
Creating a new account on tutorial island getting this message. 

I currently have two clients open one (main) that has achievement rewards available but it appears to be coming up on a new client / different account.

![111](https://user-images.githubusercontent.com/38025439/39641442-15e53b88-4fc6-11e8-8534-c421bb4c09ad.png)

**Comment by SoyChai** [comment]
This is due to a bug with the Daily Task Indicators, which literally aren't working at the moment.

**Comment by sethtroll** [comment]
I believe this was fixed in #2963

**Comment by SoyChai** [comment]
I expect that would've fixed it too, yeah.
