### ISSUE TITLE
Display issue.

### ISSUE THREAD

**Issue by Puz3** [runelite/runelite#2338]
Hi,

When launching Runelite I get such weird display issue. Please find attached screenshot. I am running Archlinux with OpenJDK 10. Other OSRS clients are working fine such as Konduit, therefore I think that this issue is not related to my hardware / setup.

Launcher logs: [launcher.log](https://github.com/runelite/runelite/files/1975373/launcher.log)
Applicaiton logs: [application.log](https://github.com/runelite/runelite/files/1975379/application.log)

![screenshot from 2018-05-04 20-38-36](https://user-images.githubusercontent.com/13761998/39642680-24db8204-4fdb-11e8-9251-9658a45808c1.png)

**Comment by TzZek** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Puz3** [comment]
@TzZek Thanks, issue is now fixed. Any ideas why this is happening? Is there something from my side that I can do to run Runelite with HardwareAcceleration?

**Comment by deathbeam** [comment]
Yeah, most likely update/install graphics drivers.

**Comment by R1GAS** [comment]
@Puz3 What fixed this issue for you in the end?
