### ISSUE TITLE
Clue Scroll: Opening world map with a location arrow (Emote, Coordinate) crashes client

### ISSUE THREAD

**Issue by ajblaida** [runelite/runelite#2340]
Noticed during an anagram clue, tried with a coordinate and emote and all failed. A task one however (pickpocket an elf) did not and opening with no clue did not either. Stack trace of error: 

![image](https://user-images.githubusercontent.com/24727496/39646325-06c7465e-4fa9-11e8-9520-b2048c40ad3e.png)

Current git head: 248ba6a

**Comment by deathbeam** [comment]
You incorrectly built the client.
