### ISSUE TITLE
Grand Exchange tracker - Completion bar is off

### ISSUE THREAD

**Issue by MalakaJones** [runelite/runelite#2341]
It seems that the completion bar in the GE tracker plugin is not showing the appropriate proportion of items bought. (probably sold ones too.)

![image](https://user-images.githubusercontent.com/15826583/39648299-ca71950e-4faf-11e8-8d1c-a8085467012e.png)

**Comment by deathbeam** [comment]
Isn't that 1193 left out of 1500? The bar looks correct to me if that is the case.

**Comment by MalakaJones** [comment]
If I'm correct, I was about 300 jars off from the 1500 offer I placed and not the other way around.

**Comment by Nightfirecat** [comment]
Has this been fixed in the new UI? I've not heard of any similar issues since the redesign.

**Comment by MalakaJones** [comment]
Yes, it looks like it has been fixed with the new UI.
