### ISSUE TITLE
lobster icon not showing

### ISSUE THREAD

**Issue by padilhozo** [runelite/runelite#2344]
![rune](https://user-images.githubusercontent.com/38412912/39653664-e7eafe58-4fbf-11e8-8f35-0e50fa170d63.png)

**Comment by episkorowski** [comment]
I can't seem to replicate this. Even if "Show Lobster/Swordfish/Tuna" is unchecked in the fishing plugin, it hides the squares as well as the icons.

![image](https://user-images.githubusercontent.com/25601041/39667334-8742df7c-5081-11e8-8e23-3b98bedb722a.png)

![image](https://user-images.githubusercontent.com/25601041/39667348-c15aaa1e-5081-11e8-874a-0f27676db6aa.png)

**Comment by sethtroll** [comment]
This was probably an api issue at the time and it just nulled when caching the image.

**Comment by deathbeam** [comment]
Looks like this was not an issue.
