### ISSUE TITLE
feature-request Left Click Banker

### ISSUE THREAD

**Issue by Superraiden** [runelite/runelite#2348]
Hi,

OSBuddy allows for the left click default of a banker to open the bank. Can this feature be added, similar to how the default click action for Ardy Knights is pickpocket?

Thanks!

**Comment by SoyChai** [comment]
Enable the Menu Entry Swapper plugin and you're good to go, we have this feature.

**Comment by Superraiden** [comment]
Hi,

Thank for showing me where it's located! Interestingly, the box was ticked for the bank, but only swapped over in-game once I ticked and then unticked the box for 'Bank'

Not sure if it's a transient error or a bug.

Either way, thank you!

Tom
