### ISSUE TITLE
Toggle between HP and Percent on Health Indicator

### ISSUE THREAD

**Issue by alex-vincent** [runelite/runelite#2349]
Would be nice to see how much hp is left needed on the npc shown in a percentage. 
Example of when this would be useful is switching at 35% from ruby to diamond bolts at vorkath, and i'm there are are plenty other instances for when this would be nice to have.

**Comment by alex-vincent** [comment]
Cancel this, apparantly it already does it in percentages :o

**Comment by Kamielvf** [comment]
It shows percentage if the monster health is not found in the file we use to get our data from. I would leave this open if you would like to see a toggle for this option because at some point  the health file will be updated and the monsters that show percentages atm will show actual numbers.

**Comment by alex-vincent** [comment]
Ah ok :)

**Comment by Adam-** [comment]
Added in 78eb357bbfc1a960346992104a36bb01a10e4c92
