### ISSUE TITLE
Clue Fix (Mausoleum)

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2354]
https://i.imgur.com/T9iS5UF.jpg

Add a 'No Boots' check to the list of equip.

**Comment by Jalopyy** [comment]
Closing because #2355

**Comment by Nightfirecat** [comment]
Don't close the issue--it will be closed once the pull request is merged. Until then, it's technically not fixed. :)

**Comment by Jalopyy** [comment]
:pray:
