### ISSUE TITLE
Let idle notification trigger while WCing/fishing if bags are full

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2357]
Sometimes the animation keeps going until you try to chop the next log/catch the next fish, which creates a period where you aren't idle, but don't need to be doing the same action. Might be nice to have an idle trigger if actively doing either of those activities and your bags fill up.

**Comment by Nightfirecat** [comment]
You can trigger notifications upon reaching a full inventory [via the Advanced Notifications plugin](https://runelite.net/plugin-hub/show/advanced-notifications) on the hub.
