### ISSUE TITLE
clue scroll helper

### ISSUE THREAD

**Issue by snowcaster** [runelite/runelite#2358]
whenever i get a coordinate clue, the helper box pops up but it only tells me to "travel to the marked location". which is definitely not easily noticeable or it there is not a marked location. love the client though otherwise.

**Comment by Kamielvf** [comment]
If all goes well, this will be fixed next release. See #2064

**Comment by Jalopyy** [comment]
Looks like it will be in the next version 100%, Adam merged it with the master branch.
