### ISSUE TITLE
Slight issue to anti-venom+, for Vorkath, for potions too..

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#2369]
![image](https://user-images.githubusercontent.com/38350898/39662877-82b60e44-5071-11e8-8e47-2b9ed73c5fc3.png)

Now according to this pictures, I'm frozen.. but in fact I'm not because I killed the spawn scorpion thing. So to stop this confusing please add a new timer with vorkath head as the icon showing, until you kill the spawn you are free to move.. Applying ice barrage on this is so confusing. I killed the spawn in less than 10 seconds and says I'm frozen for another 10.

Again this is just a slight thing. you can ignore it/this.

-------------
![image](https://user-images.githubusercontent.com/38350898/39662892-d8d8a2c8-5071-11e8-858d-05926809c891.png)

Notice, the first pictures says my Anti-venom+ is going to last for 0:46 seconds.. This is absolutely correct. But after the 46 seconds is gone this happens (Picture above).. Now you may ask what's wrong? This is what's wrong. 

> Anti-venom+ is a potion that instantly cures venom and poison. It provides immunity to poison for 12 minutes and venom for approximately 3 minutes.

It provides immunity to the venom for 3 minutes.. But it also provides immunity to poison for 12 minutes. It currently shows only the venom part.

So why don't you show this:
After drinking a anti-venom+ potion.. Show that you are immune to the venoms for 3 minutes and posion for 12 minutes. And start counting.

---------
![image](https://user-images.githubusercontent.com/38350898/39662934-a2fcec9e-5072-11e8-8891-59442861beb3.png)
![image](https://user-images.githubusercontent.com/38350898/39662940-b32af656-5072-11e8-923e-717d6900463b.png)

Some potions has a hover info box thing, but for the extended antifire and the antivenom they don't. Not sure about others but maybe add like for
- anti-venom+ "Provides immunity for x minutes"
- Antifire extend "Provides immunity for x minutes" or something like this?
Thanks.

**Comment by deathbeam** [comment]
Looks like the reported does not exists anymore and the issue contains a lot of unrelated stuff, so closing (1 request per 1 issue next time)
