### ISSUE TITLE
Farming plugin - Fails to detect grown cactus

### ISSUE THREAD

**Issue by MalakaJones** [runelite/runelite#2373]
So apparently my cactus is fully grown and ready to be harvested, but the plugin states it will be ready in 12 minutes.

![image](https://user-images.githubusercontent.com/15826583/39665669-cdf9bf60-5065-11e8-95fa-af4a93490aa6.png)

![image](https://user-images.githubusercontent.com/15826583/39665699-17294ae8-5066-11e8-8b61-ffb49f31f9e0.png)

**Comment by Abextm** [comment]
Fixed in #4125
