### ISSUE TITLE
Exact timer overlay for pyramid plunder

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2377]
can be hard to tell how much time is left so this would be handy

**Comment by RebornFX** [comment]
The normal timer also tends to get in the way of the XP globes which isn't terrible but not ideal, so yeah would love this addition.

**Comment by Frankkz** [comment]
+1 Would be nice to have a countdown timer, each session is 5 minutes.

**Comment by jacksonbob10199** [comment]
doing pp now and thought of this, would be nice

**Comment by dekvall** [comment]
Added in #11718
