### ISSUE TITLE
Public Beta Testing

### ISSUE THREAD

**Issue by Saer-Dev** [runelite/runelite#2379]
I propose that a _Public Beta_ branch be created for the repository (equivalent to a _release_ branch for a UAT programme in GitFlow) to allow us to preview and test upcoming and WIP features by synchronising our RuneLite clients to the branch.

**Comment by deathbeam** [comment]
Well, everything that is in master is available to everyone using snapshots.

**Comment by Nightfirecat** [comment]
In the short term, one possibility would be to run another CI system (like AppVeyor, or something similar) which allows storage of build artifacts so that non-technical users can just download PR/branch's build and run it to test. In the longer term, it sounds like Travis is adding this functionality soon™? travis-ci/travis-ci#532

**Comment by deathbeam** [comment]
Well, we already have that, everything is deployed to maven repository, you can just download shaded.jar from there and run it. But, we don't have this documented, as it is not very good to have average users run snapshots.

**Comment by Abextm** [comment]
The problem with this isn't a technical one, we already provide snapshot binaries to the launcher. The problem is that the builds are not for public consumption. Most people who do not have the technical knowledge to build the client do not have the knowledge to report bugs in a useful capacity.

**Comment by MagicfTail** [comment]
That would pretty much be the same as the old plugin importing system (or whatever it was called), which Jagex made us remove. I feel like having the Snapshot for people who really can't wait is fine. Also, having people randomly import not fully completed prs/plugins would also be a 'customer support' nightmare

**Comment by Adam-** [comment]
As stated, we do deploy everything pushed to master to repo.runelite.net, and you can pass `--version=` to the launcher and give it the current snapshot version. I think we shouldn't make it any easier than this. In the past we've found giving snapshot to people who do not understand the implications usually does not end well.

**Comment by Saer-Dev** [comment]
I'd say a more elegant solution would be to offer a simple GUI for enabling WIP versions, albeit buried in the settings, but with a big warning indicator stating that features involved on the WIP version are not guaranteed to work and offer an easy reversion for people in over their heads.

Also, bug reports are only as good as the facility used to report them.  If they're simply reported on here in free-form, they're guaranteed to be lacking.  However, if you provide an intuitive bug reporting form and hook it into your GitHub issues via a script, you would obtain far better reports, helping to propel the project forward at a greater pace.

**Comment by deathbeam** [comment]
I would say expecting people that want to run snapshots to at least know how to pass simple parameter to launcher is not very harsh criteria for allowing people to run snapshots, there is no need to have GUI for that.
Even though having some beta testers could be nice, but having people be able to test the snapshot that do not know what they are doing would be worse than not having testers at all imo.

**Comment by Saer-Dev** [comment]
Having a greater pool of testers available is not a problem, so long as you have a solid enough bug reporting system to take advantage of the sheer numbers, as I detailed previously.

**Comment by Nightfirecat** [comment]
I've created a wiki page for running the development snapshot version. (thanks @xaviergmail for the screenshot!) I think this should be enough to satisfy this issue for now?

https://github.com/runelite/runelite/wiki/Running-on-the-Development-Snapshot-Version

**Comment by deathbeam** [comment]
Just build client from github
