### ISSUE TITLE
Remove teleblock info box when entering a safe zone (non-pvp zone)

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#2384]
Currently it remains until the full duration is up.

**Comment by TylerNichols** [comment]
I personally would want to still see it.

**Comment by Kamielvf** [comment]
I think it makes more sense to show the box as long as the TB is affecting you.

**Comment by Nightfirecat** [comment]
TB wears off as soon as you enter a safe zone.

**Comment by Nightfirecat** [comment]
http://oldschoolrunescape.wikia.com/wiki/Tele_Block

> The effects of the teleblock are lifted when the affected player leaves the Wilderness by any means (jumping over the wilderness ditch, dying, etc.), or when the teleblock timer expires.

**Comment by Kamielvf** [comment]
Yeah thats what I meant with having it only show the box as long as the TB is affecting you, I didn't mean to disagree with you :+1:

**Comment by TylerNichols** [comment]
Oh... I didn't realize that's how tb works?? :O
