### ISSUE TITLE
Stat Boosts Plugin - Turn Red when time to re-pot

### ISSUE THREAD

**Issue by redsfan7035** [runelite/runelite#2387]
Add an option that makes current level stat red when it falls below a certain % of level or something similar. Example, dragon battleaxe special 116/99 when first done, 116 is green. When level falls to 110, make it turn red so that I know to repot. The color change just makes my eyes draw to it easier rather than having to constantly check to see what level my stats are.

Thanks! #

**Comment by Alexsuperfly** [comment]
this was added in #5761
