### ISSUE TITLE
Dead herb patch only updates to dead when in range

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2388]
Assume this is for any type of patch but just noticed when doing a herb run

**Comment by MalakaJones** [comment]
@Stickaplex Are you talking about visual range? I know that it's posssible to fetch the patch status a little bit further than than the view distance but not that much more.

**Comment by Stickaplex** [comment]
no im more talking about loading range. noticed it on mort patch and updated prolly like right b4 the farmer house so couldnt see it yet @MalakaJones

**Comment by Rprrr** [comment]
The client can only know that it's diseased/dead when you cast geomancy or go to the patch. Seems like it may work just fine.

**Comment by Abextm** [comment]
The client doesn't know about diseased/dead patches until you go near them. There is nothing we can do about this, and even if we could it would be very OP.

**Comment by Rprrr** [comment]
(Used to be possible, but Jagex removed it - because it, indeed, was considered too OP.)

**Comment by Stickaplex** [comment]
Rip

**Comment by sethtroll** [comment]
Can probably be closed, as abex said, not possible and probably OP
