### ISSUE TITLE
Drop Text Not working

### ISSUE THREAD

**Issue by IronPerish** [runelite/runelite#2389]
So, I have it so only highlighted items show up on the ground and anything worth 10k HA or GE. But sometimes, my highlighted items don't show up. I'm not sure why this is. Like most of the time, they do, but sometimes they don't. This just freaks me out in case I were to miss some big drop.
Not sure if anyone else is having this issue.

**Comment by MalakaJones** [comment]
I also experience this issue once in a while. The drop appears as an untradable.

**Comment by Adam-** [comment]
I think this was fixed in 2ef485dc309ecc15ccb1c9ef7cc946587ab1b0c2

**Comment by MalakaJones** [comment]
Could this be expand to npcs such as implings? I think I had a similar issue with highlighted imps in puro-puro.
