### ISSUE TITLE
Allow left-click Pickpocket for NPCs whose only higher action is Attack

### ISSUE THREAD

**Issue by SoyChai** [runelite/runelite#2392]
Xavier on discord pointed out that the vanilla game already allows this - it's just a hassle remembering to toggle your Attack-hiding options after thieving sessions. We could easily add this as a permanent menu swap for convenience.

**Comment by deathbeam** [comment]
I dont think we should when there is already in-game option for it that works perfectly well, and its not like you are going to thieve for 2 mins and then return to w/e you were doing previously so it would be annoying to change back and forth
