### ISSUE TITLE
Data Export (woox drop)

### ISSUE THREAD

**Issue by Castro3halo** [runelite/runelite#2393]
Ability to export drop and kill data from Woox's upcoming drop plugin. (to notepad or excel, etc. the Raw data to be able to implement. This would vastly improve compatibility with things like Gingbino's Slayer sheet, and other places when calculating accurate XP/H and Profit/H

**Comment by Kamielvf** [comment]
Yes, he is planning to do this.

**Comment by xandyman999** [comment]
exporting to a .csv file would make it easy for people to be able to copy and paste their data to share their loot logs. Potentially allowing to people safely share the raw text data - via something like pastebucket, then add into a separate spreadsheet without having to worry about downloading a .xlsx with a virus or key logger. Data could be easily copy and pasted into notepad by a PVM clan to sum drop data by using separate tab per player. 

What i'd really like to see is a summed value of all drop NOT looted, so I could see how much pure in gp i let spawn by not looting common drops.

**Comment by Adam-** [comment]
Recent loot can now be exported from the API in json format if loot tracking is enabled.
