### ISSUE TITLE
Toggle to track "current" xp/hr

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2401]
Have a toggle to track current xp/hr. 
currently the xp/hr is tracked by the amount of xp youve gained total since whenever you first gained xp in that skill. It would be nice if there was a toggle to show hm your current gains are, as in hm xp youve gained in the past hour . Granted it would be off until you hit the hour mark but with this way you can tell how your doing currently compared to say 2hours ago

**Comment by deathbeam** [comment]
You can now auto-pause and manually pause the tracking
