### ISSUE TITLE
Use correct hiscore when looking up player from right click menu

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2403]
when you right click and do lookup on an hardcore ironman the highscore should atuomatically show the players stats on the hardcore icon 
![image](https://user-images.githubusercontent.com/37475765/39673320-ebabcf36-5131-11e8-89c1-5cd8e1d900af.png) 
 not the normal highscore, 
that also goes for ultimate ironman 
![image](https://user-images.githubusercontent.com/37475765/39673322-fc8f8b80-5131-11e8-9782-800f3e74f236.png) 
 and ironman 
![image](https://user-images.githubusercontent.com/37475765/39673328-027e29ca-5132-11e8-8d58-be75176ae58e.png) 
 it shouldn't go to normal high score 
![image](https://user-images.githubusercontent.com/37475765/39673338-2327fc3c-5132-11e8-9987-c5c7ac0cd7fe.png) 

this is a bug

**Comment by capSAR273** [comment]
Strange, it looks like there are enums for the different player types but it must not be using them properly.
![image](https://user-images.githubusercontent.com/5252505/39675897-51b13062-512f-11e8-9c56-1fa35b3f4f76.png)

**Comment by permedd** [comment]
Yeah i don’t mind clicking them either but then when you forget to click what mode they are playing at and you see their rank it just confuses you, it will be so much better if it went to the mode automatically of what mode they are playing on which is normal/ironman/ultironman/hcim etc.
I think it should work for lookup option also when you type their names.

**Comment by deathbeam** [comment]
It is not possible to determine account status without some ugly workarounds like querying hiscore api and checking for 404 or something
