### ISSUE TITLE
Join/Leave Clan Chat messages + clickable x to clear Plugin Configuration

### ISSUE THREAD

**Issue by rlw0014** [runelite/runelite#2406]
I just want me Konduit features over here that I know and love...
including but not limited to:
ctrl+shift+backspace to clear chatbox: [[Suggestion] Shift+Backspace to clear chatbox](https://github.com/runelite/runelite/issues/2277)
Join/Leave Clan Chat - whenever anyone joins or leaves, it leaves a message User has joined, User has left.
When searching for a plugin and after being done with the setting, I _click_ back and would rather _click_ to clear my search option also instead of backspacing after clicking or highlighting it etc. I know, lazy.

**Comment by deathbeam** [comment]
Open separate issues for separate feature requests. For now, marking this as duplicate of #726 as that is the main request.
