### ISSUE TITLE
donate

### ISSUE THREAD

**Issue by Vishous** [runelite/runelite#2410]
this may be the wrong place to write this but is there a way to donate to the devs? i am enjoying runelite i came from osbuddy, and runelite is so much smoother

**Comment by devLotto** [comment]
We have a Patreon at https://www.patreon.com/runelite 😄

**Comment by deathbeam** [comment]
I don't think this issue should be open here, this has mostly not much to do with the client source code

**Comment by Vishous** [comment]
yeah i know sorry about that @deathbeam was something i wanted to ask but didnt know where to ask

**Comment by stefanrsk** [comment]
Please btc donations i want donate
