### ISSUE TITLE
Login screen doesn't work, can't do anything (Linux) 

### ISSUE THREAD

**Issue by mrfires** [runelite/runelite#2413]
![screenshot at 2018-05-06 15-40-55](https://user-images.githubusercontent.com/39036922/39678572-e8066366-5143-11e8-8bce-d9013a0fc4bd.png)
I think it's an issue with runelite? I'm not sure. OSBuddy works just fine.

**Comment by Kamielvf** [comment]
See https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration and how to disable OpenGL hw acceleration which is causing your issue.

**Comment by mrfires** [comment]
wtf that was the fastest response ive ever had thanks a lot

**Comment by AverageHumanoid** [comment]
I haven't experienced this using Intel driver with Arch Linux or Nvidia driver with Ubuntu 16.04.

**Comment by JordanWhittle** [comment]
I'm using Arch 4.16.2 with Nvidia driver 390.48, haven't seen this problem before.

**Comment by deathbeam** [comment]
It mostly because of misconfigured graphics cards, what is apparently very common with Linux users :P

**Comment by CrashyBang** [comment]
I fixed this by running `java -jar RuneLite.jar --mode=OFF` (I found this on Reddit) and was hoping someone could explain what the `--mode=OFF` is doing and should I be doing it?

Also I experienced this problem on Debian (buster) with what I think is a properly configured `Intel HD 620`.

**Comment by Nightfirecat** [comment]
@CrashyBang That's the same as is documented here: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by CrashyBang** [comment]
@Nightfirecat sorry I completely missed that part my apologies.
