### ISSUE TITLE
Camera does not take local offset into consideration

### ISSUE THREAD

**Issue by cmg5461** [runelite/runelite#2420]
The camera is not centered on the local player. This innacuracy is not much of an issue at low scales, but at higher scales, the issue becomes apparent:

![java_2018-05-06_19-14-28](https://user-images.githubusercontent.com/9099791/39678833-2bc611d2-5162-11e8-95f9-9ebbbd1c1db0.png)

![java_2018-05-06_19-14-12](https://user-images.githubusercontent.com/9099791/39678834-2f404076-5162-11e8-8ab0-ad99941e44ff.png)

cyan: problem
green: local correction

I've found the issue to be located in Perspective.java
**public static Point worldToCanvas(Client client, int x, int y, int plane, int tileX, int tileY, int zOffset)**

pointX needs an offset of -6, while pointY needs an offset of -18.

Through local testing, this corrects the problem, but I'd rather find an answer to why -6 and -18 fix the issue. These values were found by iterating and visually checking accuracy.

**Comment by Abextm** [comment]
I think your overlay needs a `setPosition(OverlayPosition.DYNAMIC);` in it's constructor.

**Comment by cmg5461** [comment]
I tried what you have suggested. On initial inspection, it fixes the issue. Is there any documentation on these overlay settings/options? That setting seems like a hidden secret :)

**Comment by Abextm** [comment]
`OverlayPosition` has some documentation. Any other plugin that draws in "3D space" will use it too.

**Comment by cmg5461** [comment]
I hate to ask this, but where? I don't see reference to any javadocs in this project.

**Comment by Abextm** [comment]
http://static.runelite.net/api/runelite-client/net/runelite/client/ui/overlay/OverlayPosition.html
