### ISSUE TITLE
favorite list for plugins, icons for sidebar, toggle shown boosts

### ISSUE THREAD

**Issue by abra238** [runelite/runelite#2427]
I know people have suggested categorizing plugins, like combat, skilling, etc., but additionally a category for favorites would be nice.

Being able to toggle plugins by clicking an icon on the sidebar would be handy, though maybe redundant if a favorites list would be added.

OSB has the ability to toggle shown boosts with ctrl+b. Add the same (whatever custom modifier).

**Comment by deathbeam** [comment]
Please split this issue to multiple requests, having X completely different requests in 1 issue is annoying for both maintainers and person who will be working on 1 of your requests.

**Comment by deathbeam** [comment]
We added favorites, open issues for your other requests as separate. Make sure if it is not duplicate too.
