### ISSUE TITLE
Add option to not focus the client when receiving a notification

### ISSUE THREAD

**Issue by Noobish1** [runelite/runelite#2433]
I'm using OSX High Sierra with Java 8 Update 171. Runelite 1.5.1.

I'd like the ability to not focus the client window when a notification is received (idle or otherwise). It is super annoying when typing in another application (coding, instant message etc) and a notification focuses Runelite and I end up typing in-game instead.

**Comment by Kamielvf** [comment]
Disable "Request focus on notifications" under "RuneLite" in the plugin settings.

**Comment by Noobish1** [comment]
Ah thanks @Kamielvf, some of these configuration options are a pain to find.
