### ISSUE TITLE
Change left click option from Starlight to Zilyana when both are stacked 

### ISSUE THREAD

**Issue by mino830** [runelite/runelite#2438]

**Comment by deathbeam** [comment]
I don't think we want to do this.

**Comment by Floukru** [comment]
No, wouldn't want this. Too OP. The whole point of sara is to run, range 1 time, and in this 1 time you must kill zilyana once even if it's under starlight..

**Comment by deathbeam** [comment]
Yeah this seems OP/controversial, so, closing as wontfix
