### ISSUE TITLE
Cannot type into the client

### ISSUE THREAD

**Issue by alapaille** [runelite/runelite#2442]
Hi, first time user here.

When I opened the client initially, I had an issue with hardware acceleration. Now, I'm unable to type into the game client. I'm also unable to type into the boxes provided such as the settings and high scores tabs. 

Any help would be appreciated!

Another thing to note, the client isn't acknowledging that I'm clicking on these text boxes. It doesn't come up with the blinking line that shows that you're typing. (I'm not sure how to explain the line blinking thing)
 
I'm using Ubuntu, if that is important.

**Comment by AWarbear** [comment]
I'm having this issue as well. Clicking away to another application and focusing the application with super+num or by clicking from the (ubuntu) launcher restores the typing functionality.

**Comment by alapaille** [comment]
@awarbear

Thank you for taking the time to try to help me, but I think we’re having different issues. My client isn’t registering any typing at all. 

Though, running as super might fix the issue, I will be home in about an hour to try that, thank you for the suggestion!

**Comment by AWarbear** [comment]
@alapaille Not running as super, switching to the app using the super key eg. windows key

**Comment by AWarbear** [comment]
@alapaille with the blinker missing do you mean the login box or the plugin search field? or both?

**Comment by nickazcarate** [comment]
I can click in the text box (notes tab for example) but hitting keys does not register. The same happens when I type in the levels calculator -- I can't input numbers. I have tried opening the app from another app view using fn + click, control + click, option + click, command + click. Nothing works. I'm on macOS Mojave 10.14. Thanks a bunch.

**Comment by DiddlyStix** [comment]
> I can click in the text box (notes tab for example) but hitting keys does not register. The same happens when I type in the levels calculator -- I can't input numbers. I have tried opening the app from another app view using fn + click, control + click, option + click, command + click. Nothing works. I'm on macOS Mojave 10.14. Thanks a bunch.

I'm having the same issues. For me, sometimes closing the client and reopening grants a temporary fix, but, again that only works sometimes. I'm on macOS Mojave 10.14.2.

**Comment by chxon** [comment]
I too am having the same issues on MacOS Mojave 10.14.2.

**Comment by la-korasi** [comment]
same issue here, running Mac OS Mojave 10.14.3, the text cursor (blinking vertical line) appears and flickers as usual, but typing doesn't register. A couple days ago I found a work-around that involved something like minimising then maximising the runelite window, or tabbing out and back in, but now it's happening again and I can't recall how I quick-fixed it previously. It's worth fiddling around with these sorts of things to see if you can get it working again. I'll keep trying and if I get it to work I'll post an update.
Note: this is only in the runelite GUI, not in the OSRS section of the client (i.e. i can type in the OSRS chatbox but not run a search in the settings or write in the runelite notes tab).

**Comment by la-korasi** [comment]
Update: I don't know how, but it just started working again. I posted this comment, returned to the client, opened notes and tried to type, and bang; it registers. Hmmm... Something is triggering this, i'll keep trying to work it out and I'll post updates if I can crack it.

**Comment by korasii** [comment]
SOLUTION: Click on one of the chat fields that isn't working (notes, preferences search bar etc...), and press and hold a key on your keyboard for a couple seconds and BOOM! You can type again.
You're welcome! :)

**Comment by jonathan-nielsen** [comment]
@korasii This actually worked, thank you very much!!
Still annoying though and should be treated as a bug.

**Comment by al3x-huang** [comment]
Any updates on this issue? It has been occurring for me on macOS 10.13.6 for some time now and the only workaround is the one mentioned by @korasii

**Comment by Alexsuperfly** [comment]
you're likely experiencing #3514

**Comment by al3x-huang** [comment]
I don't believe so. I can, in fact, type accented characters. When this problem occurs I cam unable to type any character until I hold down a key for a couple seconds.

<img width="181" alt="Screen Shot 2020-09-11 at 10 56 08 AM" src="https://user-images.githubusercontent.com/20210402/92957593-ca707380-f436-11ea-898f-259eeb21f07a.png">
