### ISSUE TITLE
Counter for number of "regular" attacks on vorkath

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2447]
Regular attacks being range, melee, fireball, and his multiple types of dragon fire

Reason so you can tell when his zombie/rapid fire specials are coming

**Comment by SirGirion** [comment]
I'll look into this and see if this is something we want to add to the client

**Comment by Stickaplex** [comment]
imo its no different than demonics plugin as all that really does is "count" the attacks for you before it switches styles in addition to what its switching to @SirGirion

**Comment by deathbeam** [comment]
I believe we decided to not implement vorkath plugin
