### ISSUE TITLE
Change functionality of player indicators slightly

### ISSUE THREAD

**Issue by benzarzen** [runelite/runelite#2453]
I really like how the player indicators feature is set up (how names are drawn on minimap, ingame, and in right clicks) but I would like to suggest a change.

Would it be possible for the client to also paint players who you have added to your friend's list but they do not have you added back (or have PM off)? Most other clients have this functionality and it'd be incredibly useful for me!

Thanks

**Comment by TzZek** [comment]
Sounds like a Raggers dream don't think this would be good implementation.

**Comment by benzarzen** [comment]
It's for anyone who PKs as their primary reason to play this game. I agree that raggers would find it useful but there's nothing stopping them from using any of the other multitude of clients that have this functionality (OSB/Konduit/RL/Exlient)

**Comment by TzZek** [comment]
Pking is the only reason I play as well. But imo even with the other clients having it, it makes my time in wild or pvp areas hell as people can instantly find me.

**Comment by benzarzen** [comment]
Fair enough. Just have differing opinions then I suppose. Don't really see it as a negative just because, as mentioned, other clients already have this functionality. Hopefully it's worth considering regardless.

**Comment by deathbeam** [comment]
I don't think supporting feature with very small benefits that has great benefits for people abusing it just because other clients have it is reasonable suggestion.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
