### ISSUE TITLE
Add agility shortcut clickboxes to the elven lands

### ISSUE THREAD

**Issue by Pupper3** [runelite/runelite#2454]
Tirannwn is one of the most frustrating places to travel in runescape because of how hard it is to find the various shortcuts you have to take. Highlighting these in someway would make life easier for everyone, through the currently existing agility plugin. 
![runelite_2018-05-07_15-27-08](https://user-images.githubusercontent.com/16019892/39720747-5c466614-520b-11e8-8544-0d8bd55ae057.png) ![runelite_2018-05-07_15-26-32](https://user-images.githubusercontent.com/16019892/39720752-5e303630-520b-11e8-84fb-e9735d5cb264.png) ![runelite_2018-05-07_15-25-49](https://user-images.githubusercontent.com/16019892/39720765-60230814-520b-11e8-95ad-fc4968b43be3.png) ![runelite_2018-05-07_15-25-34](https://user-images.githubusercontent.com/16019892/39720782-61ffcfb4-520b-11e8-8c95-a42f7c988b17.png)

**Comment by TzZek** [comment]
I'll add these in tonight, if no one else gets to it first.
