### ISSUE TITLE
pure plugins

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2455]
maybe we can be able to not be able to click on defence or attack on the weapon windows (f5) where we can toggle it off and on.
what i mean is this 
![image](https://user-images.githubusercontent.com/37475765/39721482-9c134eac-5237-11e8-93f2-c6e335037831.png)
if we do try clicking the attack or defence style it wouldnt switch attack style and will be on the str style no matter what.

this will make pures wants to use the client.

**Comment by TzZek** [comment]
This already exists

**Comment by deathbeam** [comment]
Already implemented
