### ISSUE TITLE
Spin Flax(Magic) Plugin

### ISSUE THREAD

**Issue by CubeSlime** [runelite/runelite#2458]
In the plugin it could have a two options in which I can think of.
Show how many casts left via overlay, would take the amount of flax in your inventory and / 5.
time before next cast? so a timer of some sort.

idk how complicated this would be to make but would be a nice "quality of life" plugin

**Comment by Nightfirecat** [comment]
I feel like this isn't necessary now that we have the Inventory Viewer plugin--it can be used for all of the lunar spells that affect inventory items.

**Comment by deathbeam** [comment]
I agree, we can close this
