### ISSUE TITLE
UI Progress bar not completing correctly

### ISSUE THREAD

**Issue by guidodobboletta** [runelite/runelite#2459]
Java Version and Operating System: Ubuntu 18.04 Oracle Java 1.8.0_171
Reproduce the Error: Buying things on the grand exchange will sometimes cause this issue in which the progress bar is not completed.

This is what I'm talking about:

![screenshot from 2018-05-07 17-57-22](https://user-images.githubusercontent.com/24704808/39729254-8bf106f2-5220-11e8-9c71-c995bcd790b5.png)

I'm not exactly sure how to reproduce this as it's intermittent and sometimes it just works correctly

![screenshot from 2018-05-07 18-01-04](https://user-images.githubusercontent.com/24704808/39729267-a2337a08-5220-11e8-9d6a-dcd8158596fa.png)

**Comment by Kamielvf** [comment]
Duplicate (?) of #2341, assuming this is still valid after the UI update.
