### ISSUE TITLE
Idle warning notification while performing an action

### ISSUE THREAD

**Issue by Saer-Dev** [runelite/runelite#2460]
RuneLite gives me a notification stating that my character has been idle for too long and will soon be logged out even while I'm completing an action.  In my case, this is chopping Magic Logs, which often incurs long periods of AFKing while the character chops the tree.

Correct me if I'm wrong, but RuneScape servers do not interpret time spent performing an action, even if the UI is not interacted with, as idle time.  Therefore, I believe this to be a bug in the RuneLite client and not something I encountered using other clients such as OSBuddy.

**Comment by deathbeam** [comment]
This behaviour is correct, you can get logged out while not interacting with the client for long enough and not in combat. People get logged at Redwoods pretty often for example/

**Comment by Saer-Dev** [comment]
How very troubling.  Strange that I didn't experience it on other clients, perhaps I whacked my mouse over the screen accidentally more often when I used those.
