### ISSUE TITLE
Add a "Protected / Composted" icon to farming timers, if they have been applied to the patch

### ISSUE THREAD

**Issue by Hillohei** [runelite/runelite#2472]
Just as the title says. Sometimes you miss/forget to put a compost or protect tree, would be nice if the timer would show it.

**Comment by Fathlete** [comment]
Sometimes you forget if you've composted or not with the bottomless bucket since you don't see empty buckets in your inventory anymore. It'd be awesome to get a visual to show this ingame (not just in the farming timers menu). Something like this (pic taken from reddit) https://i.redd.it/pkp67bdguvq21.png

**Comment by Pathemeous** [comment]
I would like to upvote this feature-request. In-game is an interesting nice-to-have, but the farming timers menu seems like a great non-invasive way of managing your crops.

**Comment by JacoboMoral** [comment]
Is adding an indicator to the timers the only option being considered? I've started working on an in-game overlay which would indicate whether patches are composted or not.

![image](https://user-images.githubusercontent.com/24235786/82606339-33e22300-9bb7-11ea-9cc7-17b1021e2568.png)

**Comment by Pathemeous** [comment]
> Is adding an indicator to the timers the only option being considered? I've started working on an in-game overlay which would indicate whether patches are composted or not.

I think both are desirable. The extra benefit of an indicator in the timers menu is that you don't need to be at the patch.

**Comment by SwampyApple** [comment]
> 
> 
> Is adding an indicator to the timers the only option being considered? I've started working on an in-game overlay which would indicate whether patches are composted or not.
> 
> ![image](https://user-images.githubusercontent.com/24235786/82606339-33e22300-9bb7-11ea-9cc7-17b1021e2568.png)

I'd very much appreciate such overlay. I often end up using the bottomless bucket on the patch multiple times 'just in case' when I absentmindedly farm.

**Comment by JacoboMoral** [comment]
> > > Is adding an indicator to the timers the only option being considered? I've started working on an in-game overlay which would indicate whether patches are composted or not.
> > > ![image](https://user-images.githubusercontent.com/24235786/82606339-33e22300-9bb7-11ea-9cc7-17b1021e2568.png)
> > 
> > 
> > I'd very much appreciate such an overlay. I often end up using the bottomless bucket on the patch multiple times 'just in case' when I absentmindedly farm.
> 
> That's great! What is the status of the overlay? I'm also forgetting to compost and would like such a feature.

I am afraid it's still under development with not much progrss and without an estimated time of resolution, since I can't find any spare time at this moment to continue developing.

**Comment by killzone111** [comment]
Any update on this?

**Comment by orlp** [comment]
I think this feature would be great.

**Comment by Adam-** [comment]
added in #14892

**Comment by CalebBarnes** [comment]
@Adam- As far as I can tell, the overlay reminder was never added, just an icon in the sidebar. The overlay would be amazing.

**Comment by CalebBarnes** [comment]
Agreed. I almost always end up trying to reapply the compost. There is a similar plugin for birdhouse seeds. Maybe it would be helpful to review their code?

https://github.com/hong-niu/runelite-birdhouse-overlay
