### ISSUE TITLE
Auto-Collapse LVL tracker

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#2476]
Whenever the client is restarted I have to manually collapse my levels, the whole point for me is to see xp / h & time until next level, let's save clicks!

https://i.imgur.com/67HF6b9.gifv

**Comment by Caia-OSRS** [comment]
I think this is similar to #974 I posted a while back

**Comment by Popedigoz** [comment]
Yeah. Damn, Mar16? Apply this to the next update please devs
c;<

**Comment by deathbeam** [comment]
Duplicate of #974

**Comment by deathbeam** [comment]
Also, this will be solved with the Obsidian theme redesign

**Comment by Popedigoz** [comment]
what's obsidian theme redesign doe..:/?

**Comment by ypperlig** [comment]
See #1419
