### ISSUE TITLE
Panel is not expanded on lookup with sidebar hidden

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#2486]
When you had sidebar hidden and you did not had opened plugin panel before closing sidebar, after clicking "Lookup" on player, the hiscore plugin panel is not being expanded, only sidebar is expanded and hiscore menu highlighted.

**Comment by Kamielvf** [comment]
I cannot reproduce this issue, might have been fixed among one of the UI updates.

**Comment by deathbeam** [comment]
Well that is good, closing then
