### ISSUE TITLE
Herblore actions left can be calculated better

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#2488]
If I'm doing slayer and cleaning herbs for whatever reason, and then I want to make potions later, it should give me the actions remaining till level once I start making the potions. That sentence is difficult to understand, so let me break it down.

I'm cleaning herbs during slayer.
I go to the bank and make potions.
The actions remaining till level now takes me cleaning herbs into account.

I know this is the default behavior, but I believe it would be better if it just calculated it based on the potions I'm making.

**Comment by DaanG96** [comment]
I think this is because the last 10 actions get taken into account when getActionsRemaining() gets calculated

**Comment by deathbeam** [comment]
I dont think this is an issue, as it averages last 10 actions and after that it will correct itself.
