### ISSUE TITLE
RuneLite HD mode

### ISSUE THREAD

**Issue by calvinkoch** [runelite/runelite#2489]
So can you make a mode like Runescape HD

**Comment by Infinitay** [comment]
See: https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

"OpenGL: Jagex is working on their own implementation (see #1165)"

**Comment by Gamer1120** [comment]
Can be closed.

**Comment by deathbeam** [comment]
Duplicate of #1165
