### ISSUE TITLE
Slayer plugin - Task carrying over to other accounts

### ISSUE THREAD

**Issue by tylerthardy** [runelite/runelite#249]
**Detailed Problem:**
Slayer task amount is only saved for the client, not per account. As a result, when a user switches accounts it will still show the slayer task from the previous account, and even progress the task if not checked on the new account.
**Cause/Limitations:**
Slayer task amount is saved as an extra variable in the saved plugin settings. There is no distinction between different accounts, because plugins settings are global between all accounts, Plugin settings currently do not support saving Maps because the database is not structured to handle them.

**Comment by StephenLynx** [comment]
I also like to add that the plugin is not able to pick up the streak from the dialogue with the master that is able to reset your streak. I figure that problably you can't pick it up from anywhere but this npc and completing a task.

**Comment by MESLewis** [comment]
This should be a simple addition now with #12834
