### ISSUE TITLE
Barbarian Assault Round timer 

### ISSUE THREAD

**Issue by Aukk** [runelite/runelite#2500]
Hey, 
I need some help from you guys! I do alot of barbarian assault speeding/leeching. We are using all kinds of timers atm (ahk, autosplitter...) I was thinking of adding another timer(from waves 1-10) under the already existing 30sec call change timer. Or just round time after the wave 10 complete ( just like some bosses have kill time (raids, zulrah...). Would be nice if someone can try make something like that. Thank you!

**Comment by deathbeam** [comment]
Would be nice to have this as infobox probably, in similar way we do with raids now.
