### ISSUE TITLE
Improved and redesigned Color Picker

### ISSUE THREAD

**Issue by psikoi** [runelite/runelite#2503]
As I was looking for a next project, it was mentioned that the color picker could be improved, as the default java is not visually pleasant and the substance color picker lacks features such as an alpha slider.

I propose that I develop a new color picker, with the features the devs need, I would appreciate any suggestions or feedback.

Mockup:
![](https://i.gyazo.com/f198c93bab2424004fe953d20b249555.png)

**PS: A feature I didn't draw in would be a section with pallets/color presets.**

Also a feature that was discussed on the discord chat was a live-preview, so as the user slid the color sliders, the new color would be previewed on the game window (ex: grounditem color highlight)

**Comment by dztance** [comment]
Would love to see this added :)
