### ISSUE TITLE
Ubuntu 18.04 Graphical bug

### ISSUE THREAD

**Issue by FabulousAid** [runelite/runelite#2507]
Hi,

Anyone know what I'm doing wrong? Can't find anything online and OSBuddy works just fine. Using Ubuntu 18.04 and oracle-java8-installer. Installed java versions:

![image](https://user-images.githubusercontent.com/38670662/39806345-9b72acf0-5371-11e8-9320-a06d40087167.png)

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by FabulousAid** [comment]
Thank you! Wasn't Googling the correct key words it seems.

**Comment by engelmic** [comment]
sorry to necro, but the method described to disable hardware acceleration produces a plethora of errors. Is there an updated solution, or should a new bug be filed? 
java -jar Runelite.jar --mode=off
Ubuntu 18.04

**Comment by deathbeam** [comment]
its --mode=OFF not --mode=off

**Comment by engelmic** [comment]
sorry, my mistake - didn't notice the case. 
Thank you
