### ISSUE TITLE
RuneLite Render Issue

### ISSUE THREAD

**Issue by Bazzzzz** [runelite/runelite#2515]
I wanted to try and use RuneLite but I very quickly bumped into some weird and annoying behaviour. Whenever I hover my mouse over the RuneLite client's buttons the client will start rendering the last hovered item at my mouse position. This behaviour doesn't start immediatly but only after I've been hovering for a few seconds. Restarting the client does not resolve the issue, the behaviour just returns. I've included a couple of images to better display what I mean (links at bottom). 

I'm almost 100% certain this is a problem with my PC but I'm not sure where to look to fix it. Any ideas as to why this may be happening, or even better, how to fix this? 

I've updated Java and my video card to their latest versions. All other drivers were up-to-date.
Java version: v8.0.1710.11 (update from 17th April 2018)
Nvidia GeForce GTX 570: v23.21.13.9135 (update from 23rd March 2018)

Windows specs:
Windows 10 Pro 64 bit
Version: 1703
Build: 15063.726
CPU: Intel Core i7 920 2.67GHz
Ram: 12GB

![runelite bug example 2](https://user-images.githubusercontent.com/11329172/39825485-3384481a-53b2-11e8-916a-0c60d7ae6e51.png)

![runelite bug example 1](https://user-images.githubusercontent.com/11329172/39825472-28b0500a-53b2-11e8-980c-78050b471f3b.png)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Bazzzzz** [comment]
Seems like it worked. Thanks for the help!
