### ISSUE TITLE
compare highscore stats

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2516]
this will be awesome to the client, i think i havent seen anyone have this kind of thing on their clients.
![image](https://user-images.githubusercontent.com/37475765/39827673-9630415a-53b0-11e8-815f-a17f2a666103.png)

maybe add another new slot to compare? but then it wouldnt be able to be part of lookup so you will have to type their full osrs name :( 

![image](https://user-images.githubusercontent.com/37475765/39827706-aad54862-53b0-11e8-92d3-a46428a0e375.png)

or you can add this new addition on lookup section?

**Comment by deathbeam** [comment]
I think this was partially implemented by stat compare in opponent info and is probably no longer needed/relevant
