### ISSUE TITLE
Item comparison

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2519]
Would be nice to have an item comparison to compare 2 items. Preferably how it was done in like 2009 or w/e it was made

**Comment by Reasel** [comment]
Do you have an example? Do you mean like in the equipment screen?

**Comment by Stickaplex** [comment]
Iirc how it worked in rs2 was in equip scrren if you used an item on another (or maybe it was right click compare? ) it wpuld popup a screen having side by side with the better stats in white

**Comment by Stickaplex** [comment]
Im sure if you take 5mins to look should be easy to find. Just cant cause at work atm. Will post when i get home if some1 else hasnt

**Comment by Stickaplex** [comment]
@Reasel @Chdata this was best i could find as to how it worked...thought would be easier to find tbh 

![image](https://user-images.githubusercontent.com/33562756/39866734-ae1b9c00-5406-11e8-8fa1-2a70450cb6fb.png)

video i pulled the pic from: https://www.youtube.com/watch?v=kEGd-JL5OGo&ab_channel=RuneSharkVideos

**Comment by Chdata** [comment]
Thanks. I couldn't search earlier because of work too. If you can find a screen of that Stats option too, that'd be useful.

**Comment by Stickaplex** [comment]
What do you mean stats option? cause you have a pic of the actual comparison. Altho there is one in the video i linked as well

**Comment by Chdata** [comment]
There's the option for Compare and the one for Stats in the context menu pic you posted, I forget what the UI looked like for Stats.

**Comment by Reasel** [comment]
This feature hinges on us having the stats for every item in game. Just a lot of data to gather in one place.

**Comment by Chdata** [comment]
I have a stat dump from pre-eoc... would probably be a bit inconsistent with OSRS though, as it has things like chaotics, damage soaking, and summoning defence.
