### ISSUE TITLE
Add more stuff on the high-score (lookup)

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2523]
![image](https://user-images.githubusercontent.com/37475765/39837598-daf04290-53ce-11e8-9b8d-ed306d97867f.png)

when you move your mouse on top of the total level (skill:Overall) it should show 
- which skills the player done last? so as in last action?

Example: if i done thieving and i didn't log in for a week it will still show thieving? till i do another skill.
-which skill is the closest to level up, and if your level 99 the next xp will be 200m xp so which skill is the closest to 200m xp.

**Comment by Nightfirecat** [comment]
Since this panel was redesigned a long time back with the Obsidian redesign, this gap no longer exists and thus does not need filling.
