### ISSUE TITLE
Slayer plugin infobox

### ISSUE THREAD

**Issue by Temposrs** [runelite/runelite#2525]
Task infobox not showing up and yes I have the task infobox ticked in the slayer configuration.

**Comment by Nightfirecat** [comment]
Have you checked your task with a slayer ring or slayer helmet?

**Comment by josharoo** [comment]
This is probably the expiry timer removing the infobox, the timer resets (and displays infobox again) when you get a slayer kill, get a new task, check task etc. and removes it after X minutes but you can change the expire timer to something like 600 minutes in the slayer plugin settings and it'll be there essentially permanently
