### ISSUE TITLE
Runelite does not remember "Trust this computer" authentication

### ISSUE THREAD

**Issue by capSAR273** [runelite/runelite#2526]
I've used several other clients from this PC before Runelite, and they all remembered the authenticator's "Trust this PC for 30 days" option. For some reason Runelite does not, at least every 24 hours it asks for the authenticator upon login. It will remember within the past several hours however.

**Comment by Stickaplex** [comment]
I dont believe this is a runelite thing

**Comment by deathbeam** [comment]
THis do not looks like RuneLite related at all.
