### ISSUE TITLE
Farming tracker is partially localized

### ISSUE THREAD

**Issue by poshdan** [runelite/runelite#2532]
When the "show relative time" option is ticked off, the completion times for the farming plugin use a partially localized time string to display the date at which the plant will finish growing - which clashes a bit with the rest of the interface being english.
Example:
"Fossil Island Middle - Done montag at 2:00"
I don't know what the community's stance on localization is, but I prefer to use english whenever possible.

**Comment by Abextm** [comment]
Duplicate #2268 
This will be fixed in today's update
