### ISSUE TITLE
would anybody like to see simulated drops in game?

### ISSUE THREAD

**Issue by TheSexyNerd** [runelite/runelite#2537]
I had just made an API for drop tables that mimic Runescape and I was wondering if anybody would like to see a command in game much like the discord bot where you could simulate X amount of kills and see what loot you get? syntax would be something like !kill 15 zulrah

**Comment by Stickaplex** [comment]
as long as i dont have to see it tbh...cause personally i dont even like seeing that stuff on discord

**Comment by josharoo** [comment]
Good concept, useful in other locations such as Discord or a site for it, but I don't personally see the use for it ingame.. displaying the results could possibly get quite ugly too

**Comment by devLotto** [comment]
I don't think this is useful to have in-game

**Comment by MattyJacques** [comment]
I would agree with some of the comments above, maybe a feature on a site or maybe a plugin on the side

**Comment by deathbeam** [comment]
Chat games are no I would say.
