### ISSUE TITLE
Almost all of my runelite tabs/functions are gone. 

### ISSUE THREAD

**Issue by Torevedoy** [runelite/runelite#2540]
![image](https://user-images.githubusercontent.com/39160716/39871943-b5dc9d26-5466-11e8-9eb8-c084910e41c9.png)

At this current time the only difference between normal runescape and runelite for me is the easily accessible  hiscores menu, which is really just a bonus not a reason to keep using the client.

**Comment by deathbeam** [comment]
RuneLite is outdated, that is vanilla, expected behaviour.

**Comment by abringley1083** [comment]
This happened to me this morning as well. Is it bc of the osrs client update? Runelite hasn't caught up?

**Comment by Nightfirecat** [comment]
Yes. Runelite needs to update after each osrs client update. You can re-open Runelite now and it will have been restored to full functionality.
