### ISSUE TITLE
Most plugins are gone

### ISSUE THREAD

**Issue by Weenyhutjr** [runelite/runelite#2541]
I logged into Runelite today and for some reason nearly all of the plugins are gone. The only plugins still there are: Account, HiScore, Info Panel, News Feed, Notes, and Runelite. I have already tried restarting the client and my computer and that didn't solve the problem. I have not tried uninstalling and reinstalling just in case there is a simpler fix. If anyone knows any way to fix this please let me know!
![issue](https://user-images.githubusercontent.com/39160618/39872043-b42809e8-5434-11e8-9637-907f01b5cb5b.PNG)

**Comment by deathbeam** [comment]
RuneLite is outdated, that is vanilla, expected behaviour.
