### ISSUE TITLE
Plugins disappered?

### ISSUE THREAD

**Issue by ssbanic** [runelite/runelite#2542]
Was doing barrows last night finding the plugin super helpful, and when I logged in this morning all of the plugins have disappeared? I'm a new user so I might have done something but how do I fix this?

**Comment by MarcJtk** [comment]
If your plugins are not loading, it is most likely because OSRS was recently updated and RuneLite is not updated yet. Please be patient, we are working on update.

**Comment by StephenAllan** [comment]
Is there a reason all features of the client become disabled on an osrs client update? Feature compatibility? How do other clients get around this issue: allowing users to continue to use features/plugins until they can release the next patch to their client?
