### ISSUE TITLE
Runelite not showing all options

### ISSUE THREAD

**Issue by 5ylum** [runelite/runelite#2543]
my Runelite client is not showing all its options. Reopening client ,restarting computer, reinstalling client or running the "no-ddraw" bat file does not fix the issue. Is there currently a fix to this?
![capture](https://user-images.githubusercontent.com/39132637/39872474-6166af78-5468-11e8-8282-2c5210d7456a.PNG)

**Comment by MarcJtk** [comment]
If your plugins are not loading, it is most likely because OSRS was recently updated and RuneLite is not updated yet. Please be patient, we are working on update.
