### ISSUE TITLE
New note plugin appears to have broke right click lookup in friends list

### ISSUE THREAD

**Issue by Caia-OSRS** [runelite/runelite#2548]
<img width="242" alt="screen shot 2018-05-10 at 11 23 54 am" src="https://user-images.githubusercontent.com/37057941/39877769-c9c2fb9a-5444-11e8-8a24-504cce72abeb.png">
As you can see the lookup option is not there anymore. If the friend note plugin is turned off the lookup option appears again.

**Comment by Adam-** [comment]
Fixed in https://github.com/runelite/runelite/commit/688a43fbc18d6b35028a096c04e05391dfe731d9 and https://github.com/runelite/runelite/commit/13b80ec85f60ceffc5e367137217915346d858e3
