### ISSUE TITLE
Wiki lookup

### ISSUE THREAD

**Issue by Zyxts** [runelite/runelite#2551]
The idea of when you Examine a monster it pulls the information of what it drops and displays in a table from OSRS Wiki, found this on google aware its a private server but this kind of idea.

https://gyazo.com/97dcc89fa21f349e586569a2ffb8f1e7

**Comment by Reasel** [comment]
Fixed in [#2304](https://github.com/runelite/runelite/pull/2304).

**Comment by Gamer1120** [comment]
There was a pretty decent suggestion on the implementation of this on Reddit: https://www.reddit.com/r/2007scape/comments/9j5f5l/ingame_wiki_lookup_orb_tool_here_you_go_mod_sween/
