### ISSUE TITLE
Changing "highlighted Items" and other boxes

### ISSUE THREAD

**Issue by wilsoc18** [runelite/runelite#2557]
Could it be possible to change how you input what you want highlighted? As an ironman I want to see every herb and herb seed drop and you have it so I have to type each individual herb and seed name into a very small box. its hard to even see if I have typed them in there correctly. Can you add check boxes for herbs and seeds and the like or make it so that the box is larger or opens up another window to input information? also, thanks for this client. makes playing the game much better.

**Comment by deathbeam** [comment]
Just type *herb*, *seed* 🎉

**Comment by Reasel** [comment]
You can input a * character to denote any other character any amount of times.

Something like: Grimy *
Would match to:
Grimy Ranarr
Grimy Toadflax
Grimy Marentill

Also you can press Ctrl + A to copy the text in that small box and paste it into a notepad or word document. Then make your changes and then copy and paste the list back into the RuneLite box.

**Comment by wilsoc18** [comment]
Ah, thanks. I don't know coding at all so stuff like this is beyond my brain power.

**Comment by wilsoc18** [comment]
When I input the information like I described I colored it so I can see it over the white. When I do *herb* it doesn't color it like I would like. Is there a way to change that?

**Comment by Kamielvf** [comment]
Adding items to the list will color them using the `Highlight` color. What were you expecting?

**Comment by Reasel** [comment]
This is a pretty nice thing to learn! Just mess around with it with something like runes.
You can do: * rune
Which will match anything that ends with rune. You could do: Rune*
Which would match anything that **starts** with Rune.

Once you get the hang of it you can add all the items you want pretty fast.

**Comment by wilsoc18** [comment]
kamielvf That's the color I was changing. I got it to work by erasing and redoing it all. I also found out you can just hit alt to add or remove. handy.

**Comment by Reasel** [comment]
I think your issue is that you just added herb and not the name of the herb you wanted.

**Comment by deathbeam** [comment]
Looks like this was resolved
