### ISSUE TITLE
Fairy Ring on Minimaps

### ISSUE THREAD

**Issue by Exstatic** [runelite/runelite#2560]
This is a suggestion but im trying to do clues and some of them lead to islands like this one: https://imgur.com/a/RNHOVqz

I dont know the island name or anything about it and when i hover over it, i get this: https://imgur.com/a/EemK96J

2 ways we can solve this:

- Make it like OSBuddy and just have the ring code on top of the fairy ring on the map
- Replace the "Transportation" text with the fairy ring code

**Comment by episkorowski** [comment]
Addressed in #2451. Hopefully it gets merged soon, seems like it'd be useful.

**Comment by deathbeam** [comment]
Duplicate of #1067
