### ISSUE TITLE
Raid attack marker

### ISSUE THREAD

**Issue by uzot** [runelite/runelite#2565]
Would be awesome if there was a X showing on the spot where an attack would hit in the Chambers of Xeric.
Talking about bosses such as shamans poison bombs, vasa's rocks and tektons lava balls after he goes back.

Konduit has this feature at the moment and its amazing to prevent damage like that.

**Comment by Stickaplex** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

shamans was removed before. i assume vasa/tekk would fall under this category
