### ISSUE TITLE
Tooltips rendering behind the game

### ISSUE THREAD

**Issue by XrioBtw** [runelite/runelite#257]
https://i.imgur.com/5RHLfK2.png

**Comment by deathbeam** [comment]
![screenie2](https://user-images.githubusercontent.com/5115805/34043773-ce4a4aca-e1a2-11e7-8d15-d711d1284806.png)

it is working for me

**Comment by XrioBtw** [comment]
https://i.imgur.com/NojTnWO.gif
The shadow not showing on a the tooltip is probably because of my dying graphics card and not an issue with the client

**Comment by XrioBtw** [comment]
Fix (at the cost of losing shadow on tooltips):
`ToolTipManager.sharedInstance().setLightWeightPopupEnabled(false);`
`System.setProperty("jgoodies.popupDropShadowEnabled", "false");`
