### ISSUE TITLE
Cant launch game properly

### ISSUE THREAD

**Issue by FishyFyn** [runelite/runelite#2576]
Whenever I try to install the game, it installs correctly and then I try to launch it. At this point, the loading bar opens and after zipping through some parts, It finally gets blocked on 100% when it comes to the jna-4.5.1.jar.

https://gyazo.com/248846623d1e97c49ca11e23ec616619

**Comment by deathbeam** [comment]
Open issue in https://github.com/runelite/launcher, this is wrong repo
