### ISSUE TITLE
Barrows Feature Request: Add a config to only highlight doors that'll lead to the chest (not all openable doors)

### ISSUE THREAD

**Issue by amp4045** [runelite/runelite#2588]

**Comment by SomeZer0** [comment]
Do any other clients do this?

**Comment by Reasel** [comment]
I don't think this is possible since when you drop down you cannot see all of the doors which means you don't know the full path. I guess you could only marks doors that have at least 2 operable doors, but that seems like overkill for the minigame.

**Comment by amp4045** [comment]
@Reasel Do the ID's of the openable doors only get accounted for when they're in the viewport?  If not, could we not have the set of openable doors and traverse this to see which door leads to the chest's ID door?  The leg that leads to the chest door would be the only route, thus returned.

**Comment by Reasel** [comment]
So it seems like we simply mark all the 'walls' which include the doors and then if the 'walls' have an action they can do we mark them differently. As of now we do not know where they are so to speak, but since each object has a world location I am sure someone could formulate an algorithm for what the path is given all the doors. Then mark those doors.

**Comment by amp4045** [comment]
@Reasel Do we really care about the world location, though?  I'm thinking that if we know all clickable doors the moment we go down, we should be able to create a final leg of all clickable.

I suppose a limiting factor, are all clickable doors on their own static ID? (i.e. not changing)?

**Comment by Reasel** [comment]
The thing is that we doing have all the clickable doors. We currently just grab all the walls/doors and mark them on the minimap differently. That is the problem. We don't have a full map. Just parts of it

**Comment by amp4045** [comment]
@Reasel So that goes back to my first question, do we only mark them differently when it's within the viewport? If so, I understand your point, if not.... and all wall/doors are marked the moment we go down the crypt, I still think this is possible :)

**Comment by amp4045** [comment]
If each door has it's own ID, and that's set in stone, we can define a 'map' without the actual world location of the door, this would give us the ability to iterate through and discover the route.

**Comment by Reasel** [comment]
As far as I can tell its only within the viewport. When the client renders the objects we also mark them on the minimap. That is why I was leaning towards only marking doors with 2 or more doors in that room...Which we could do by using the world points. Also we could use a different color for 'unsure' where we haven't rendered the rest of the connecting room.

I think there is a set path when you go down each time and random other doors are turned on such that any door that is turned on connects to the path. Maybe there are set rotations though..

**Comment by Reasel** [comment]
![barrowsmap](https://user-images.githubusercontent.com/1210740/39940882-9a14c8d0-550f-11e8-9827-d4006446cfa7.png)

So what I am suggesting is simply checking if  the room has more than 1 door. If it does not then mark all those door with RED unless it is the starting room. If we can only see 1 door in that room, but have not seen the other doors then mark that door YELLOW. If we see more than 1 door in a room mark them all GREEN. If a door goes to a RED door then mark that door RED. This should eliminate all dead end paths and leave the player on a good path.

An alternative is to look for the chest door that is operable and then mark doors connecting to it as GOOD. From there path out to the player through other known doors and if a path makes it to the player eliminate other paths.

**Comment by SomeZer0** [comment]
I would be against having the barrows plugin give you the correct path.

That would increase barrows runs/hour. And I don't think any other clients do this.

**Comment by valryk** [comment]
It's doable but JaGeX will not allow it and you will be banned for doing it.

**Comment by Adam-** [comment]
No other clients do it, I am not interested in it.
