### ISSUE TITLE
Add customization of flash notifications

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2593]
Color, number of times it flashes, tenths of seconds/milliseconds each flash is. At least the second two.

Also with how eye-grabbing flash notifications are and the inability to toggle which idle actions I want to be alerted of, re-plugging #2215. Not looking forward to repeatedly turning flash notifications on and off based on what I'm doing.

**Comment by dicrypt** [comment]
Would having color picking options alongside the various plugin properties that enable notifications be good? For example: I want low health red, low prayer teal, action idle black, etc. 
I wouldn't mind picking up this feature if that's the case.

**Comment by Jalopyy** [comment]
Doesn't matter to me, personally.

**Comment by deathbeam** [comment]
I dont think this should be implemented, and part of issue is duplicate of #2215

**Comment by JorgeFernandezH** [comment]
I hope this gets implemented, having a red light flash in ur face sucks
