### ISSUE TITLE
Feature Request: Kalphite Queen Helper

### ISSUE THREAD

**Issue by ThatGamerBlue** [runelite/runelite#2598]
Shows the tile kq is on, what tiles count as "lured" i.e. you can walk out, hit and walk back under and she won't move (https://clips.twitch.tv/SarcasticKindOpossumLeeroyJenkins) and possibly (if it's not too op, probably is) what movements to get to a lured position.

**Comment by ThatGamerBlue** [comment]
it's a cheap method, like 3m costs. do you mean like marking tiles and marking kq? i dont know all the tiles thats "lured" though, only got 2 kc

**Comment by kulershk** [comment]
Idk what u meant, but Kq is stuck couz of kalphite workers, all u need to do just go in the corner so workers can surround Kq

**Comment by deathbeam** [comment]
There is no such thing as "lured" spots, you just go to corner and let workers block the KQ.
