### ISSUE TITLE
Feature request: RuneLite mobile

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#2599]
Would be nice to have an Android port of the client :)

**Comment by jpabeem** [comment]
Yes please, let's do this! ![+1](https://i.imgur.com/m2tFaXx.jpg)

**Comment by Stickaplex** [comment]
In all seriousness though, wouldnt a 3rd party client be rather spammy on such a small screen?

Dunno for sure tho as i didnt get either invite.

**Comment by RobinDson** [comment]
I think it could be useful on iPads and tablets with larger screens.

**Comment by RebornFX** [comment]
I do think that many of plugins would be unnecessary, but some features would be great. I think in reality the majority of mobile users will use it for afk skills, so things like idle notifiers and timers for things like nmz would be invaluable.

**Comment by rhyseli** [comment]
I agree with @RebornFX. Especially for skills such as agility and minigames so that the clickable areas are highlighted. I might see if decompiling the current client apk is possible.

**Comment by raiyni** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by devLotto** [comment]
https://twitter.com/RuneLiteClient/status/1057301530569777154
