### ISSUE TITLE
Health percentage is floored

### ISSUE THREAD

**Issue by henke96** [runelite/runelite#2614]
The decimal digit on the health % is always 0 because it is floored. Not sure why this is done.

This is done on the line `textToWrite = DECIMAL_FORMAT.format(Math.floor(pc * 100d)) + "%";`
in [https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/ui/overlay/components/ProgressBarComponent.java](url)

**Comment by deathbeam** [comment]
This should be fixed already with https://github.com/runelite/runelite/pull/2609, the input value was wrong

**Comment by deathbeam** [comment]
oh wait, you mean decimal digit. Yes, we always want full % right?
