### ISSUE TITLE
C:\Users\Adam directory

### ISSUE THREAD

**Issue by jhenahan** [runelite/runelite#2615]
Based on https://www.reddit.com/r/mac/comments/8ipkxe/any_idea_what_this_folder_is_it_keeps_popping_up/ and https://ubuntuforums.org/showthread.php?t=2391617, it looks like some component of Runelite is writing a directory called `C:\Users\Adam` with the file `.runelite` to user directories. Not sure how to go about fixing it, just wanted to let you know.

**Comment by Adam-** [comment]
This is a bug with the launcher and fixed here: https://github.com/runelite/launcher/commit/7f0fd21b898af7d3992fc6fdd260f66c0f25102d. A release has not been made yet with it.
