### ISSUE TITLE
Reposition AGS/BGS images on special attack counter

### ISSUE THREAD

**Issue by S7venlives** [runelite/runelite#2620]
Move the Damage dealt text to the corp beast.

Reposition the Arclight/BGS images on the special attack counter. 

![image](https://user-images.githubusercontent.com/39206427/39952558-b1c2a4ae-5599-11e8-819e-2e9c9e793de1.png)

**Comment by deathbeam** [comment]
You can reposition the acrlight/bgs images by yourself, hold ALT

**Comment by S7venlives** [comment]
I mean the Arclight image is getting cut by the side of the indicator square. and the bgs is almost.

**Comment by deathbeam** [comment]
you can now resize infoboxes to fix this
