### ISSUE TITLE
Trouble with launch Linux mint

### ISSUE THREAD

**Issue by danielmoss22** [runelite/runelite#2623]
Recently installed Runelite via the official website from the all platforms link , at first the .jar file was not marked executable , so i went into the permissions and made it executable , when it laucnhed it seemed to launch normally but after launching when the screen is minimized all i get is a 4x6 tiled screen that appears to be the top end of the flaming fire in the normal runescape login screen , when the screen is maximized its all black.
PS running with Java 8 Runetime

![screenshot from 2018-05-11 21-57-57](https://user-images.githubusercontent.com/39208294/39953347-5f99347c-5567-11e8-9c51-a5411b0a2a07.png)
![screenshot from 2018-05-11 21-57-36](https://user-images.githubusercontent.com/39208294/39953349-64a8a790-5567-11e8-8405-f09e7945c9fd.png)

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by danielmoss22** [comment]
Awesome this worked for me thanks !

**Comment by danielmoss22** [comment]
Awesome this worked for me thanks !
