### ISSUE TITLE
Disable tracking of skills after 99 (Option)

### ISSUE THREAD

**Issue by eezehh** [runelite/runelite#2631]
Give us the option to hide this - https://gyazo.com/87c5c950595288c8f0191a48923103a4 

I'd rather not see skills that I've already got 99 in.
![87c5c950595288c8f0191a48923103a4](https://user-images.githubusercontent.com/39213607/39956339-28c81764-55d6-11e8-9119-b4f9963e5809.png)

**Comment by cusamoly** [comment]
or a toggle to keep them at 99

**Comment by PandahRS** [comment]
Would also be nice to consider within the XP globes.

**Comment by GSchuringa** [comment]
@PandahRS solved #2720

**Comment by Nealon01** [comment]
Is there an update as to when this might be added?

**Comment by eezehh** [comment]
still waiting too!
