### ISSUE TITLE
Small QOL - Shorten the full name of items on GE

### ISSUE THREAD

**Issue by eezehh** [runelite/runelite#2632]
As you can see, I have to type the full name of the item for it to appear. Of course this would be expected however, OSbuddy allows for shortening of the name when looking it up.

![9d76bfdf6f65f41ba12edb71b91d495b](https://user-images.githubusercontent.com/39213607/39956416-f9c920fa-55d7-11e8-87b9-dc20779ad1a6.png)
![819143faf9fc718ffa31d95d50780205](https://user-images.githubusercontent.com/39213607/39956417-f9debd0c-55d7-11e8-86d2-61a93fd1ff61.png)
![b3447090ab50f458d09e9e6e3d7d7be0](https://user-images.githubusercontent.com/39213607/39956418-f9f33304-55d7-11e8-8dc3-66632b0b68f7.png)
![d7e8aaddced336ce6f3cc0371ce8a308](https://user-images.githubusercontent.com/39213607/39956419-fa086d1e-55d7-11e8-9d7d-a841f942fb3c.png)

**Comment by Abextm** [comment]
Duplicate #1338
