### ISSUE TITLE
Borderless, modern looking plugin.

### ISSUE THREAD

**Issue by Wiedersehen** [runelite/runelite#2643]
https://i.imgur.com/fQV5ZoG.png

What i am requesting is a borderless top/sides with options to enable/disable those.

It will give it more a clean, professional look(my opinion).

Or make the top/sides transparent and apart of the game client.

Thank you.

**Comment by deathbeam** [comment]
Disable custom window chrome and configure your OS to not display title bar, you can already hide the sidebar with hotkey
