### ISSUE TITLE
Feature Request: Add a timer for Brewing Vats (Keldagrim & Port Phasmatys)

### ISSUE THREAD

**Issue by NEETboxing** [runelite/runelite#2648]
This would be extremely useful for Iron man and normal players trying to make money via Mature Kegs.
The main issue I could see is that the time it takes to finish brewing is very random, it could take 12-72  on average or in some rare instances two weeks for single vat to finish brewing. Usually it is 2-3 days though.

Thank you for your time.

**Comment by broskees** [comment]
Is this something that may be considered?

**Comment by fuzxi** [comment]
This would probably be ineffective. Regular brews seem to always take exactly 3 cycles to ferment (10h40m farming cycles, not game ticks), but mature brews can take anywhere from 3 to 16 of these cycles. Even if you don't add The stuff, brews still have a 5% chance of naturally maturing, so it's not like you could limit the timer to only brews that don't contain The stuff. I think the best you could do is a timer that lets you know your brews _might_ be finished after 3 cycles, and then if the brew is not fermented and hasn't gone bad, reset the timer to be finished on the next cycle. Repeat until the brew is fermented or goes bad, or until 16 cycles have passed.

**Comment by broskees** [comment]
> This would probably be ineffective. Regular brews seem to always take exactly 3 cycles to ferment (10h40m farming cycles, not game ticks), but mature brews can take anywhere from 3 to 16 of these cycles. Even if you don't add The stuff, brews still have a 5% chance of naturally maturing, so it's not like you could limit the timer to only brews that don't contain The stuff. I think the best you could do is a timer that lets you know your brews _might_ be finished after 3 cycles, and then if the brew is not fermented and hasn't gone bad, reset the timer to be finished on the next cycle. Repeat until the brew is fermented or goes bad, or until 16 cycles have passed.

This is a good approach..

**Comment by Nightfirecat** [comment]
The [Brewing plugin](https://runelite.net/plugin-hub/show/brewing) on the hub does this.
