### ISSUE TITLE
Examine Plugin: toggle for moving examine text to a tooltip

### ISSUE THREAD

**Issue by NullBy7e** [runelite/runelite#2655]
I think RS3 does it like this, you examine an object and the text that normally shows in the chat is shown to you via a tooltip that fades in and then fades out, after a second or two.

This could be a toggle or something.

**Comment by Cyborger1** [comment]
I should have spotted this when I made my plugin.

I make a plugin for the plugin hub, [Examine Tooltip](https://github.com/Cyborger1/examine-tooltip), which does this and #12196 was closed following its addition.

See if it works for you and you can close the issue?
