### ISSUE TITLE
Run HTTP calls on a different thread pool than client actions

### ISSUE THREAD

**Issue by jplsek** [runelite/runelite#2666]
When the HTTP API goes down, some plugins "stop working" because an API call is blocking the plugin task from running. Once the timeout gets hit, then the plugin works again. Most specifically, disabling and enabling a plugin (ConfigManager.setConfiguration()).

The setConfiguation method was running on the same SingleThreadedExecutor's task thread as the HTTP call, thus blocking enabling and disabling plugins.

So, there should be a separate thread pool for executing HTTP calls so the client UI doesn't block or other plugin tasks.

![ezgif-5-80d21e5dc5](https://user-images.githubusercontent.com/2388657/39963077-d658b1d2-562f-11e8-8e91-afea582102e5.gif)

(Discord is on fire btw)

**Comment by Adam-** [comment]
okhttp has a built in threadpool for this. Maybe we should just use that instead? https://square.github.io/okhttp/3.x/okhttp/okhttp3/Call.html#enqueue-okhttp3.Callback-

**Comment by Adam-** [comment]
Fixed in #3428
