### ISSUE TITLE
Force Right Click on certain NPCs

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#2667]
Request from Discord:

> ... NPC Right Click Only Filter ... Some monsters I find you want to have it default set to right click only (KQ, Nechs Bursting, Ardy Knights etc.) But swapping that option might get tedious ...

Could potentially be controlled like Tagging currently is (Shift + Right Click)

**Comment by abextm** [comment]
Jagex's [recent statement](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1) prohibits `Allows you to prioritise the walk-here option by holding a certain key, or similar` and `Removal or swapping of menu entries on any entity ` during bosses
