### ISSUE TITLE
Barrow Chest Values No Longer Working

### ISSUE THREAD

**Issue by ebbruns** [runelite/runelite#2669]
I'd previously seen accurate values from Barrows chest pulls, but they have not been accurate today (I did not run Barrows yesterday). For example, I got 177 Death Runes, along with other rewards, but the value was listed as 1,124 coins (much less than what I actually received). I'm not sure if it's only counting cash right now, or if there's some combination of factors.

**Comment by Hydrox6** [comment]
This is likely due to the API dying earlier. Don't worry, this will be fixed once Adam wakes up.

**Comment by ebbruns** [comment]
Cool, thanks for the super fast response. I was unaware the API was down. Should I close the issue?
