### ISSUE TITLE
Client black screen on Ubuntu 16.04

### ISSUE THREAD

**Issue by bcosc** [runelite/runelite#2675]
I open the jar file with `java -jar RuneLite.jar` and get this now. A couple days ago it worked fine, but it was slow to open (no logs for that sorry). But then I upgraded to latest and now I only get the black screen.

![bsodrunelite](https://user-images.githubusercontent.com/7707893/39968555-d4f714d8-569c-11e8-9c7d-4bf2c5b8fc23.png)

I think it still works because I hear the opening theme song, but something is not rendering properly.

**Comment by deathbeam** [comment]
What if you try this: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by bcosc** [comment]
It works! Thanks!

**Comment by joaoluizn** [comment]
Solved my problem too! Ty!
