### ISSUE TITLE
Highlight the the thing (e.g. NPC) you're clicking on

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#2676]

**Comment by peter-uk** [comment]
Tile indicators already exist, search for tile in plugin configuration and enable.

**Comment by Gamer1120** [comment]
Alright, I'll edit it.

**Comment by Nightfirecat** [comment]
The Interact Highlight plugin was added to RuneLite in e276d5e5cee9d43d8dabeae6d8f326759b0d194f, which does what this issue describes.
