### ISSUE TITLE
Toggling the Demonic Gorillas plugin whilst nearby the gorillas causes no gorilla to be tracked until they respawn

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#2700]
This is down to Gorillas being added to the tracking list when they spawn. A fix would be to attempt to obtain all the gorillas in the area when the plugin starts up

Gif courtesy of *path* from the Discord
https://gyazo.com/1c530b5459b5cd2b7e2f909c926179d0

**Comment by Horacijus** [comment]
Your welcome Woox :)
