### ISSUE TITLE
Add Health Regeneration Notification

### ISSUE THREAD

**Issue by CardinalCyn** [runelite/runelite#2704]
NMZ suggestion: Making a notification appear whenever your health is about regenerate at a certain point such as at this point in the regeneration process. 
<img width="576" alt="hp sugg" src="https://user-images.githubusercontent.com/39255304/39980176-300964b6-5710-11e8-9c42-cc64fdf407ea.png">

**Comment by CardinalCyn** [comment]
I've got a rock cake, but having the ability to notify when I should switch screens would be really nice

**Comment by Titowam** [comment]
I know I'm almost a year late but... A notification like this would be really nice, unless it's already been implemented (which I can't find in that case haha)

**Comment by Kalzz** [comment]
> I know I'm almost a year late but... A notification like this would be really nice, unless it's already been implemented (which I can't find in that case haha)

Same! This would be so useful to have.

**Comment by MJM941** [comment]
@deathbeam Hi Tomas, is this something that is going to be added to runelite?

**Comment by ssaleem1** [comment]
Just to tie off on this for future readers: this feature now exists under Regeneration Meter -> Hitpoint Regen Notification.
