### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by seanjohnsonsarp** [runelite/runelite#2713]
I find the rs chat very inconvenient to screenshot when funny stuff is said because there are just a couple of lines before you need to scroll. I also believe it is just generally convenient and useful to save chatlogs. It is also unique. Could we get a chat history plugin with some options on what you would like to save? ( clan, game, public, !price ( commands) etc. )

**Comment by Infinitay** [comment]
We already have a Chat history plugin, but it doesnt export, simply keeps (the last 100?) messages when logging out and back in
