### ISSUE TITLE
Client crashing computer.

### ISSUE THREAD

**Issue by shaun768** [runelite/runelite#2718]
This happened twice today consecutively, I've been using runelite for about a week now without problems today it started happening. Both time as it crashes, it freezes the game all frames stop and then it will crash my browser and windows. Unable to crtl + alt + del to bring up task manager. Therefore only solution was to manually power the computer down.

As the crash was happening both times I noticed that the hard drive started making weird sounds which never happened before, now I'm back to using konduit for the while, I submitted the issue and see whats going on. I have not crashed yet since I came back to konduit which doesn't make any sense cause I crashed both times on runelite within the first 10mins of logging and playing the game.

I will do a disk clean up and check any windows update but if there anything else I can do please do let me know, not quite sure if its a global problem or only me problem.

Thanks in advance

With warm regards.

**Comment by GSchuringa** [comment]
Is there anything in the Windows Event Viewer indicating a severe issue with the computer at the time of the crash?

**Comment by Stormcrownn** [comment]
I can second that this also happened to me two times on Sunday. I can go look for windows events.

**Comment by shaun768** [comment]
Yeah after this happened to me I've updated Windows, I'm refraining from using runitelite until I can get an answer back from admins about this situation. Please keep me updated! :)

**Comment by VincentRavoet1** [comment]
Same here, still happening :/

**Comment by Adam-** [comment]
This may have been fixed in #3588 if someone here would like to test it.
