### ISSUE TITLE
Add 4K/scaling support on Linux

### ISSUE THREAD

**Issue by Giggybyte** [runelite/runelite#2719]
**Overview of the Issue**
RuneLite does not scale to a 4k resolution (3840x2160) regardless of X DPI setting or specific launch settings. While there does not seem to be any scaling on Linux, I do not have a Windows system to test if this issue is exclusive to Linux.

**Java Version and Operating System**
```
[dws@refrigerator ~]$ java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)
[dws@refrigerator ~]$ uname -a
Linux refrigerator 4.16.5-1-ARCH #1 SMP PREEMPT Thu Apr 26 16:53:40 UTC 2018 x86_64 GNU/Linux
[dws@refrigerator ~]$ screenfetch -n
 dws@refrigerator
 OS: Arch Linux 
 Kernel: x86_64 Linux 4.16.5-1-ARCH
 Uptime: 1d 17h 37m
 Packages: 1081
 Shell: bash 4.4.19
 Resolution: 3840x2160
 WM: i3
 GTK Theme: Adwaita-dark [GTK2/3]
 Icon Theme: Adwaita
 Font: Cantarell 11
 CPU: Intel Core i7-6700HQ @ 8x 3.5GHz [25.0°C]
 GPU: GeForce GTX 960M
 RAM: 1924MiB / 15863MiB
```

**Reproduce the Error**
https://i.imgur.com/hO23zIK.png
https://i.imgur.com/jA78Phd.jpg
Possess a 4K screen and a Linux installation, and launch RuneLite by the standard `java -jar RuneLite.jar`. Different versions of Java don't seem to make a difference and neither does specific launch settings like `-Dsun.java2d.uiScale=2`. 

**Related Issues**
#858 #715 

**Suggest a Fix**
RuneLine could detect your resolution and automatically set a scaling factor, or maybe there could be a slider or input box somewhere that asks for a scaling value. 

**Workarounds**
I can play normally by setting my resolution to 1080p before launching RuneLite. I prefer to do this by having two separate X servers with separate resolutions: 4K on tty1 and 1080p on tty2. This allows me to easily switch between the two without the scaled-down resolution needed for RuneLite messing with my other applications.

**Comment by Adam-** [comment]
I think we don't know how to fix this on Linux. The launcher release uses Windows DPI scaling on Windows and it works well. If newer Java versions cannot scale it and your OS also cannot scale it, we can't do anything about it in the immediate future.

**Comment by WhiteRayne2** [comment]
Another common solution is to add the option to manually set the application scaling in the settings, because detecting scaling settings on linux can still sometimes be fucky.

**Comment by Aitai** [comment]
In case anyone is still looking for a solution, using GDK_SCALE=2 works with OpenJDK 11:

`export GDK_SCALE=2 && java -jar RuneLite.jar`

**Comment by WhiteRayne2** [comment]
Like the suggestion above, as a temporary workaround, I was able to get good HiDPI scaling on Linux after installing Oracle JRE9 and using:

`export GDK_SCALE=2; java -jar RuneLite.jar`

**Comment by deathbeam** [comment]
This seems like bug with JVM. But, for me DPI scaling works on Linux. Anyway, closing because its not related to RuneLite.

**Comment by JackSwett** [comment]
> Like the suggestion above, as a temporary workaround, I was able to get good HiDPI scaling on Linux after installing Oracle JRE9 and using:
> 
> `export GDK_SCALE=2; java -jar RuneLite.jar`

This works as of writing this comment. Thanks! Wish there was a fix in the 2 years since you posted this though!

**Comment by ferreiramx** [comment]
It worked for me too. In my case, I'm playing on Pop!_OS 21.04 with RuneLite installed from Flathub.

In case anyone stumbles upon this and is playing the Flathub version, I easily fixed the scaling with this command
`flatpak override --user --env=GDK_SCALE=2 net.runelite.RuneLite`
