### ISSUE TITLE
Interface scaling, no need to right for bank and to access GE

### ISSUE THREAD

**Issue by kaas1641** [runelite/runelite#2725]
i was wondering if Runelite could get some interface scalling? i know osbuddy have something that makes the whole client bigger, the interface is bigger on fixed and fullscreen.

I am using a 2560x1440 monitor, so the interface is way to small for comfort...

Also was wondering if you could make it so u dont need to right click in order to bank and access ge at varrock at least :)

**Comment by deathbeam** [comment]
Enable menu entry swapper for left click bank, other one is probably duplicate of #2719 of some sort.
