### ISSUE TITLE
Sidebar Issues

### ISSUE THREAD

**Issue by clarkeyclarkey** [runelite/runelite#2727]
After a minute or so of doing anything in the sidebar this happens -https://gyazo.com/f34b5fc75396a360960feed0e19f038e

It's whenever i highlight anything clickable until I close the client.

I'm using dual screen and it stops when I move the client to another screen but starts again when after another minute or so of using sidebar functions. I tried disabling the custom window chrome and that didn't fix it.

Makes changing any settings or using sidebar functions impossible.

**Comment by MESLewis** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by devLotto** [comment]
Likely one of your screens is running on a GPU that doesn't play well with the hardware acceleration (such as Intel's integrated "HD graphics").
