### ISSUE TITLE
Entity NPC hider removes click box for fly-fishing spots

### ISSUE THREAD

**Issue by whitmabc** [runelite/runelite#2732]
![screenshot from 2018-05-14 18-42-18](https://user-images.githubusercontent.com/22404459/40027175-aea20206-57a6-11e8-93e4-e727c6eabc25.png)
![screenshot from 2018-05-14 18-42-11](https://user-images.githubusercontent.com/22404459/40027176-aeb3304e-57a6-11e8-867f-5f14f0978232.png)

**Comment by sethtroll** [comment]
Fishing spots are NPC's

**Comment by Hydrox6** [comment]
This is because Fishing Spots are NPCs. Simple option is to not hide NPCs whilst fishing.

**Comment by deathbeam** [comment]
Marking as wontfix, don't think this is solvable without plugins depending on each other.
