### ISSUE TITLE
Add a weapon speed timer overlay to the special attack orb

### ISSUE THREAD

**Issue by Tylemagne** [runelite/runelite#2733]
Since every weapon speed is different, it can be difficult to get 100% perfect flicks unless you use an external interval program that's tuned to your weapon's speed. Even then, it's difficult because it can get off-beat.

Would this be possible to implement?

**Comment by Infinitay** [comment]
I'm going to assume you mean adding a weapon speed to help when using your special attack when PvPing.

If so, I think this feature would be too overpowered. PvPing should take skill, same with timing your special attacks, not getting an advantage over players not using the client, especially as no other client has this feature as far as I know.

**Comment by Tylemagne** [comment]
No, I mean an overlay that will tell you when the weapon will hit next.

This isn't going to change PvP, since players engaged in combat with one another don't really have much to gain by flicking. They're busy with other things like eating, equipping, casting spells, trash talking, etc. This is 100% about saving prayer as flicking is intended, but actually knowing when the weapon will hit next so you don't miss the flick. The game has an issue where there's a delay sometimes and it makes it more difficult the higher your ping is.

**Comment by Infinitay** [comment]
Oh I see, my mistake, I thought you meant a timer to help you spec right on time, I didn't know you meant it for prayer purposes

**Comment by Tylemagne** [comment]
Yes, exclusively for prayer.

For more context, the "xp drop" already aids in this perfectly -- but only for one single type of weapon. I think it's the whip hits exactly when the last pixel of the HP xp icon leaves the top of the screen.

I think it would be cool if this existed for every weapon. Specifically, slow ones that hit long after the xp drop leaves the screen.

**Comment by deathbeam** [comment]
You can now get this info from hovering the weapon from item stats plugin
