### ISSUE TITLE
Fishing Plugin: Minnow Rotation Notification

### ISSUE THREAD

**Issue by abigteddy** [runelite/runelite#2734]
A feature that I enjoyed from other clients was the notification sound every time a minnow spot rotated. The rotation cycles every 15 seconds and the current idle notification doesn't alert you fast enough to be efficient. I've noticed that the animation for fishing doesn't stop for about 1-2 seconds after a spot has rotated. Another useful feature would be an alert for the flying fish random that steals minnows from you.

**Comment by Adam-** [comment]
#4320 doesn't completely address this since there are no notifications, only overlays, but I think it is probably sufficient? Minnows is not very afk-ish anyway.

**Comment by deathbeam** [comment]
Yeah i would say this is fine to close.

**Comment by odhil** [comment]
I don't think this should be closed since notifications and overlays are not the same thing. Notifications would be more useful, at least for me, since I'd prefer an audible cue to switch to the next spot.
