### ISSUE TITLE
Client pop up option when idle

### ISSUE THREAD

**Issue by lifestyless** [runelite/runelite#2738]
Is there a way for the client to open up/pop up when u get an idle notification while ur on other tabs/doing other things on ur pc/laptop? So you dont have to go to the bar below to open your client seperately

If there isn't would it be possible to add such a function to the client?

Thanks for reading this

**Comment by deathbeam** [comment]
There is "Request focus on notification" in "RuneLite" settings already.

**Comment by hizbullah106** [comment]
Hey mate, I cannot find this option in the settings? Has it been renamed?

**Comment by Nightfirecat** [comment]
You should be searching "Runelite", not "Request".
https://github.com/runelite/runelite/wiki/RuneLite#request-focus-on-notification
