### ISSUE TITLE
Keep specs up for both phases of kq

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#2741]
Currently def specs only stay up for first phase. Would be nice if it would stay up for both.

**Comment by Nightfirecat** [comment]
Is this still an issue? Based on how the code for this plugin reads now, I don't believe it is.

**Comment by Nightfirecat** [comment]
I confirmed ingame this is no longer a bug, the special counter is not removed after the grounded form dies, but is removed after the flying phase dies.
