### ISSUE TITLE
Make potion time remaining indicators blink more for better visibility

### ISSUE THREAD

**Issue by Vikerules** [runelite/runelite#2751]
Right now for example the extended super antifire potion text turns red at 30 seconds and thats about it.
Is it possible to make the whole area around the potion blink red instead to grab my attention easier? Or make the actual potion icon blink red. Right now the text is very thin and it turning red is not very easy to spot if you're focusing on bossing etc.

**Comment by deathbeam** [comment]
Its enough when they are just red, blinking is too excessive (and would be very annoying if you would have multiple potions expiring at same time)
