### ISSUE TITLE
Overall xp in the plugins settings

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#2755]
![image](https://user-images.githubusercontent.com/37475765/40062569-690d1bf6-5853-11e8-817f-998cdfad6f62.png)

as the image shows can we have the overall xp at the top right or left or even at the middle as we wish to be shown and can be toggled through the plugins? and the xp drops should be at the middle or left or right as we wish.

for example i would like to have my xp drops at the middle i would like to have xp orb at the middle but i would love to have the overall xp at the top right corner. (this is something where osbuddy has)

![image](https://user-images.githubusercontent.com/37475765/40062696-b5dd014e-5853-11e8-900a-4699a43f46e0.png)

this is how it looks like when we try to have the orb+overall xp bar it overlays and when we move the overall xp bar the xp drops moves as well.

**Comment by deathbeam** [comment]
Now overall xp is movable
