### ISSUE TITLE
GUI Bug in the plugins menu

### ISSUE THREAD

**Issue by mysticsnail** [runelite/runelite#2758]
Whenever i load the client and open the plugins menu, highlighting over icons and text boxes make my UI show a weird graphical glitch that changes every time i highlight over something in the UI. Drivers are up to date. I have added a photo to show what it looks like.
![uibug](https://user-images.githubusercontent.com/39273599/40069318-d4a73acc-5862-11e8-9c59-a6fe1bf300fd.JPG)

**Comment by Nuketato** [comment]
I found this issue as well. I tried uninstalling the client and reinstalling but it did not fix it.

**Comment by Adam-** [comment]
See https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
