### ISSUE TITLE
GPU renderer

### ISSUE THREAD

**Issue by Tylemagne** [runelite/runelite#2760]
There's been requests in the past, but everyone says it's not worth it since a new one could come with mobile: https://github.com/runelite/runelite/issues/1165

I know it's possible, but this is Jagex's management. Sometimes it seems they intentionally do the incorrect thing (that takes more work) just to spite some players. Again... not the OSRS team, but the management.

If this never happens or is announced to be years down the road, we (the players) absolutely need a plan B. The current Java renderer from 2004 is almost unplayable. Not only is the framerate capped at 50, but it starts to drop exponentially they higher you set the resolution of the resizable window. It uses a single CPU core and completely ignores the GPU.

There is absolutely no way this game can go on as a serious option beyond 2018 if it's going to hold onto its rapidly aging single-core no-GPU renderer. OSRS has a choice here: get a new renderer and continue growing, or keep the original renderer and slowly fade.

This isn't 2005. Modern computers are equipped much differently. They should all be able to run a game that looks like OSRS at 60+ FPS at their native resolution.

If, and I mean IF, Jagex doesn't move the renderer over, should a free client offer a renderer that actually works right?

**Comment by james-munson** [comment]
they have money, I don't understand how this is not even finished yet. its been a year + "Rumored to be coming with the release of mobile access. MMK was asked on Faux's stream for an update. MMK stated that it was planned to be released BEFORE mobile access. 

Unfortunately, MMK said he's been on a two-week vacation and said plans could have changed." - taken from Reddit and now with this new client drama I can see why they dropped opengl if they did, most of the mod team just uses osbuddy. I think runelite could easily add something better if they had someone or could hire someone with funds from patreon.

**Comment by devLotto** [comment]
As I said in #1165 , they will probably eventually release it for desktop.
We'll see how far they get with it after they've released mobile.

**Comment by james-munson** [comment]
10 months ago this was Jul. 16 2017, Sunday. Before "MMK said he's been on a two-week vacation and said plans could have changed."
Picture if we could player above 144fps ...
That personally would make me come back to RuneScape.

"Darkimmortal
 79 points 10 months ago 
Soon™
Also it's going to remove the 50 fps cap among other improvements :)"
"Darkimmortal RS mod
My potato macbook runs the old renderer at 20 fps at 2K res, and the new GPU one at 200+ fps"

**Comment by james-munson** [comment]
Ya hopefully mobile comes out then they release it.

**Comment by james-munson** [comment]
BETA IS COMING SOON HYPE, hopefully the gpu render code gets pushed to old school runescape

**Comment by Adam-** [comment]
I've reopened 1165
