### ISSUE TITLE
Count of how many of a certain item you have in your inventory

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#2771]
Would be useful when using superglassmake and buying from Charter Crewmembers on an ironman.

**Comment by basicDamen** [comment]
What did you have in mind on how it would be displayed?

**Comment by Gamer1120** [comment]
Maybe an overlay similar to the team overlay?

**Comment by basicDamen** [comment]
Could get very cluttered though. It's possible, of course, though, can get quite messy.

**Comment by Gamer1120** [comment]
This would be a summarized inventory viewer, basically.

**Comment by Hydrox6** [comment]
Maybe an option for Inventory Viewer that shows a summary of your inventory instead of the full thing?

**Comment by deathbeam** [comment]
So why not just use inventory viewer at that point?

**Comment by Hydrox6** [comment]
Well a number is easier than eyeballing it

**Comment by Gamer1120** [comment]
Exactly. With for example 9 soda ash and 11 buckets of sand, it's difficult to see what you need to buy more of.

**Comment by deathbeam** [comment]
I still think its sort of dumb, but I guess we could add grouping to inventory viewer as toggle, why not.

**Comment by Hydrox6** [comment]
Fulfilled by runelite/plugin-hub#189
