### ISSUE TITLE
RuneLite doesn't use the dimensions I've set in the game size setting

### ISSUE THREAD

**Issue by Denny966** [runelite/runelite#2777]
Example

![test](https://user-images.githubusercontent.com/12098006/40083356-2912c1c2-5894-11e8-8a72-5ad9191b3712.gif)

**Comment by jplsek** [comment]
Uncheck "Remember client position", then it should use your set size.

Maybe the option should be inverted, put near the game size, and called "Use custom game size" or something.

**Comment by Denny966** [comment]
Thanks, that works, not sure why the option should be off for the custom game size to work

**Comment by deathbeam** [comment]
It should be probably off by default, but anyway, this issue has been resolved.
