### ISSUE TITLE
Rumor

### ISSUE THREAD

**Issue by thestdman** [runelite/runelite#2788]
Is the post on reddit confirmed by adam as real? Just want truth not hearsay.

**Comment by CustardGod** [comment]
Yes, it's on the blog

**Comment by ypperlig** [comment]
Yes. There is a blog post as well:
https://runelite.net/blog/show/2018-05-15-RuneLite-threatened-to-shutdown

**Comment by Mod-MattK** [comment]
The inaccuracies are alarming. I had told "Adam" that we have to dis-allow users from being able to submit in their code. This is the issue, we have a hard time giving players security anymore than we have in the past towards 3rd party clients. All we want, is code to be passed between us. The balls in "Adam's" court.

**Comment by CustardGod** [comment]
Nice fake account

**Comment by Mod-MattK** [comment]
im not fake idiot

**Comment by Hydrox6** [comment]
@Mod-MattK Proof on Twitter or GTFO

**Comment by Mod-MattK** [comment]
I don't have to prove myself. If you have an issue with my identity, I'd suggest putting in a ticket to support. On the flip side, we are going to be attempting to take down OSBuddy and Konduit.

**Comment by Joshua-F** [comment]
> im not fake idiot

Lol cya

**Comment by deathbeam** [comment]
GitHub issues are not discussion board
