### ISSUE TITLE
Dynamic instrumentation 

### ISSUE THREAD

**Issue by GHXST01** [runelite/runelite#2789]
In light of recent events, has anyone ever considered using the official client with a dynamic instrumentation toolkit?

This solution would look a lot like xposed framework for Android. Or alternatively, which I enjoy using even more: https://frida.re/ .

Most of my experience is on the Android platform, but if this has some interest I wouldn't mind exploring this idea further.

**Comment by Mod-MattK** [comment]
We will be tagging Soy to take a look at this issue. Bitte warten...

**Comment by abextm** [comment]
Jagex would probably be upset if we started shipping everything needed to instrument the client again.
