### ISSUE TITLE
Severe lag using client

### ISSUE THREAD

**Issue by Pokeaye** [runelite/runelite#2790]
Been having trouble using runelite every since i downloaded it. Most of the time it's fine but about a few times a day the client will start dropping frames on all my PC. So if I have netflix on my other monitor it will also drop frames. My CPU and RAM are fine when checking it on task manager while these "drops in frames" are happening. This only happens with runelite and goes away when i log off or after an episode of dropped frames. I have redownloaded the client multiple times with the same issues. My laptop doesn't have the issue. I have a I5-6500 cpu and 16g of RAM so I don't see that being a problem

Any help?!?!?

**Comment by gregh203** [comment]
It is a problem with the user not the machine

**Comment by Unmotivated** [comment]
Can I ask if you're running the client or if you're running the open-source code via IntelliJ 

If you're running with IntelliJ then try switching to the client, if you're still having issues post back and ill try my best to help

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
