### ISSUE TITLE
Move RuneLite development to TOR

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#2792]
If we can use a similar service to Github on the TOR network, and provide instructions on how to use it, Jagex can't sue, because they don't know who to sue.

**Comment by vitaly-smirnov** [comment]
Why use a different service? Just use Github and anonymize your connections and commits. Use git over a proxy server.

Also if Jagex succeeds in shutting down RuneLite, 100s of forks will be reborn and they can say goodbye to disabling "overpowered features"... The butterfly effect will prevail and good luck stopping that.

**Comment by Gamer1120** [comment]
That would work. I do believe the website should be moved to TOR then. This way, it's not possible for Jagex to find out where it's hosted and who hosts it and request the hoster to take it down. This is similar to what the largest private server group for CoD:MW2 did on PC: https://iw4xcachep26muba.onion.to/

**Comment by Mod-MattK** [comment]
No. We will take legal action. As long as you are making a client for OUR game, we have the right and will use that right to take the entire project down idiots.
