### ISSUE TITLE
Add a splashscreen at client launch to make ALL RuneLite users aware of what is happening.

### ISSUE THREAD

**Issue by jcwhisman** [runelite/runelite#2795]
When Runelite launches, I think there should be a splash screen informing all users of what is currently happening with the client. Kinda like what a lot of websites would do during the Net Neutrality ordeals.

Something shady is going on at Jagex, and people need to be made aware. Not everyone checks runelite blogs and reads reddit. We need everyone that enjoys the client to know what is happening.

If not, this will end up like every other piece of controversy spawned from jagex... They will take a lot of heat for making a decision, they attempt to soften the blow by (falsley) saying they are targeting other big 3rd party clients as well. Finally the community calms down, and everything is swept under the rug. We all know it.

**Comment by deathbeam** [comment]
Well the case is done so I guess this is not valid anymore
