### ISSUE TITLE
Can't login Ubuntu 18.04

### ISSUE THREAD

**Issue by theonetoday** [runelite/runelite#2797]
![screenshot from 2018-05-16 10-58-28](https://user-images.githubusercontent.com/16528083/40128921-8e6b51c4-58f8-11e8-8a06-67f9b773ca58.png)

I can't see the username or password lines so I can't login.

**Comment by kusochi** [comment]
Try `apt install openjdk-11-jdk` to get latest version of OpenJDK or disable hardware acceleration `java -jar RuneLite.jar --mode=OFF`.

Older OpenJDK (default in 18.04 is openjdk-8 I think) has broken hardware acceleration I guess.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by theonetoday** [comment]
That worked, thanks
