### ISSUE TITLE
Fairy ring helper says invalid location

### ISSUE THREAD

**Issue by drnfc** [runelite/runelite#2800]
No matter which ring I try to use it says invalid location

**Comment by moglia1** [comment]
I'm only getting invalid location when the code isn't used for a location. Can you try reinstall the client and see if you get the error again?

**Comment by MESLewis** [comment]
Is there any more information on this @drnfc ?

**Comment by deathbeam** [comment]
Looks this is non-issue, reopen if it still persists for you + include more information
