### ISSUE TITLE
Ban fake Mod-MattK account

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#2802]
Ban or prevent https://github.com/Mod-MattK from imposting the real Mod Mat K.

**Comment by sainttx** [comment]
Can be done in Organization Settings -> Blocked Users
https://blog.github.com/2016-04-04-organizations-can-now-block-abusive-users/

**Comment by OTRD5k** [comment]
Is it even worth the effort though? It's easy enough to make a new account.

Just ignore the troll until he gets bored.

**Comment by deathbeam** [comment]
GitHub issues is not discussion board
