### ISSUE TITLE
Add hook for host

### ISSUE THREAD

**Issue by CustardGod** [runelite/runelite#2805]
I was using this for my ping plugin but it is no longer working. I'm assuming this is a hook issue

@Import("host")
@Override
String getWorldHostname();

**Comment by Mod-MattK** [comment]
We will tag Soy and see if she can get this coded for you.

**Comment by Mod-Archie** [comment]
Soy said that she's pretty sure this is impossible. We can't override the method called "Ping". The Current code has 30 methods inside it. So if we tried to override it, it would cause an error on Notepad++. Sorry.

**Comment by SoyChai** [comment]
Hi Custard, ignore the two trolls above, I haven't even looked into this issue.

**Comment by Mod-Archie** [comment]
We are passing this to Mod Ash. Please allow us time for Mod Ash to create his official account here. He will give you the code.

**Comment by Mod-MattK** [comment]
We've looked into it. This would require too much Dev time for the Engine team. We are currently working on Mobile.

**Comment by CustardGod** [comment]
Hmmmm

**Comment by Nightfirecat** [comment]
Since this issue has been opened, we've added a ping utility to the World Switcher plugin, and server hostnames are available in the http-api `World` class which is fetched by the world service.
