### ISSUE TITLE
We are still going to take legal Actions

### ISSUE THREAD

**Issue by Mod-MattK** [runelite/runelite#2808]
The post on Reddit was faked. We are still taking legal action against RuneLite. If you use RuneLite you will be banned, and mac banned if using a mac machine. 

Thankyou
MMK

**Comment by Demivrga** [comment]
RAAAAAAAAAAAAAAAAAAAAAT

**Comment by Mod-MattK** [comment]
Since the client is Open-Source, we will add code stuff to make it ban you instantly.

**Comment by Mod-MattK** [comment]
Suprise m♥therFu█ker
