### ISSUE TITLE
Chat History (when hopping worlds) does not store !price commands

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#2809]
!lvl and !total commands are saved with the modified values, but !price commands are just stored as !price

![runelite_2018-05-17_03-56-42](https://user-images.githubusercontent.com/2979691/40154466-579302a8-5986-11e8-8bee-e3c059dfdc79.png)

**Comment by Mod-Archie** [comment]
Weird, let me get Seth to look at the issue. One second, he should respond shortly.

**Comment by csmith1210** [comment]
This was due to the nbsp characters in the search term. My pull request fixes this by replacing them before the lookup/comparison.

**Comment by deathbeam** [comment]
That is intentional. The nbsp was supposed to also break the !total and !lvl commands but apparently it does not.

**Comment by Adam-** [comment]
fixed in e71b18b02b124bff69cc347238551d2e0d3bf29b
