### ISSUE TITLE
Error loading RS! timeout

### ISSUE THREAD

**Issue by minhal92** [runelite/runelite#2819]
Hi,
I downloaded RuneLite today, I'm on Windows 10, downloaded the .exe file, I cannot get it to work, the problem seems to be in loading Runescape. 

The client installs just fine, and when I run the launcher it shows the RuneLite.jar (java file) at 0% for around 10 seconds after which it closes itself. When I checked the logs the launcher seems to have downloaded everything just fine but the application cannot load RS, the error is below with the rest of the .txt file. I suspected it may have to do with windows blocking it from downloading so I added RuneLite (and the setup) to allowed apps through Windows Firewall (this did not change anything)

2018-05-17 01:02:44 [RuneLite] ERROR net.runelite.client.ClientLoader - Error loading RS!
java.net.SocketTimeoutException: timeout
[application.log](https://github.com/runelite/runelite/files/2011716/application.log)

[launcher.log](https://github.com/runelite/runelite/files/2011719/launcher.log)

Any help would be appreciated.

**Comment by moglia1** [comment]
Can you try reinstalling and see if you can repeat and receive the same error?

**Comment by minhal92** [comment]
Okay wait.. no idea what happened, I just tried it uninstalling, restarting and reinstalling again now on a different internet connection and it worked. Sorry for bothering you all.

**Comment by moglia1** [comment]
Will have most likely been a problem with your internet connection, glad you got it fixed.

**Comment by minhal92** [comment]
Thought it was an install issue.. I tried it at home again and it still refuses to load. I'm sure something in my connection is blocking it but not sure what.

**Comment by moglia1** [comment]
If you go on to #support in the discord, someone may be able to help there as I’m not fantastic with connection issues.

**Comment by minhal92** [comment]
Okay, I can't figure out how to add an exception either. I'll try AT&T customer support or I'll post a topic on Discord on how to add Runelite as custom service.

**Comment by deathbeam** [comment]
Well I guess this is not RuneLite-related problem, so closing.
