### ISSUE TITLE
Possibly broken idle notification timeout

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#282]
Currently, the idle notification is immediately thrown when I stop woodcutting. Based on the defualt configuration it is supposed to be thrown 5 seconds after last action, but it is thrown even when I start chopping the tree and stop before 5 seconds pass.
It looks like it is working correctly in the Motherlode Mine (at least based on @utsukami testing).

**Comment by matthewpetch** [comment]
Having a similar problem with combat. If I start fighting something else after being idle for a second, the notification will happen 3 seconds into fighting the new monster

**Comment by deathbeam** [comment]
To expand on this issue (not sure if it requires now one) the idle notification occurs also when you stop following person, or use bank interface via banker NPC.

**Comment by UniquePassive** [comment]
Was this fixed with #340 ?

**Comment by utsukami** [comment]
No @UniquePassive, only the issues mentioned in @deathbeam's 2nd comment. I haven't been able to replicate the original issue to attempt in fixing it, seems to happen randomly.
