### ISSUE TITLE
Exporting bank item layout as local file

### ISSUE THREAD

**Issue by persecom** [runelite/runelite#2822]
I don't know all of the technical jargon to properly describe what I'm describing.

Is it possible to save the position of every individual item in order from the first to last position in your bank to a file locally? Including any possible placeholders, bank fillers, and maybe even bank tags?

The purpose of this is to share a specific bank layout to make bank organization easier for new accounts. Instead of having to reorganize your bank, you can download a "preset bank layout" that you sort of force overlay onto your account. If you lack an item specified in the preset layout, a bank filler is placed instead maybe?

Hopefully someone smarter than me can help me flesh out the idea.

**Comment by capSAR273** [comment]
Exporting a bank might not be impossible, but importing probably is. Although, someone could make a separate tool to accept this export to show what the bank _would_ look like. Then someone could have this open alongside their new bank to organize it.

**Comment by moglia1** [comment]
I’d quite like a tool similar. It would allow placeholders in an inventory to make gearing up slightly quicker

**Comment by deathbeam** [comment]
Exporting can be done, importing never.

**Comment by persecom** [comment]
Can importing not be done because, on Jagex's side, items in your bank would be moved way too quickly?

**Comment by deathbeam** [comment]
You cant move them without extensive faking of user input, what will probably get you banned very quickly in such big scope.

**Comment by Reasel** [comment]
It would still be nice to 'sort' your inventory to a template of sorts. Then you could manually move everything around knowing exactly what the end result would look like.

**Comment by persecom** [comment]
Possibly! Doesn't hurt to try.

**Comment by Patriq** [comment]
Would a screenshot of the whole bank be considered an export?
