### ISSUE TITLE
Mac Client Corrupt

### ISSUE THREAD

**Issue by washac** [runelite/runelite#2824]
Downloaded the Mac Client but it tells me that the download is corrupt.

**Comment by moglia1** [comment]
Hi, can you give us a little bit more information? 

* Overview of the Issue - if an error is being thrown a non-minified stack trace helps
* Java Version and Operating System - is this a problem with a specific setup?
* Reproduce the Error - provide details, if possible, on how to reproduce the error
Related Issues - has a similar issue been reported before?
* Suggest a Fix - if you can't fix the bug yourself, perhaps you can point to what might be causing the problem (line of code or commit)

At this point I can only recommend is to try downloading again.

**Comment by deathbeam** [comment]
Duplicate of https://github.com/runelite/launcher/issues/17

**Comment by washac** [comment]
Hi Ya

I have downloaded the Runelite.dmg several times now and keep getting the same error when trying to open the .dmg.

When I try to open the Runelite.dmg file I get a warning open………

The following disk image couldn’t be opened
Runelite.dmg corrupt image
