### ISSUE TITLE
Become the most popular client

### ISSUE THREAD

**Issue by BartWillems** [runelite/runelite#2830]
Right now, OSBuddy sadly is most popular client, I would love to see this fixed by the RuneLite community.

**Comment by moglia1** [comment]
Hi this isn’t really an issue appropriate here, please take a look at the contributing guidelines here: https://github.com/runelite/runelite/blob/master/CONTRIBUTING.md

You can also join the discord here: https://discordapp.com/invite/mePCs8U

**Comment by deathbeam** [comment]
GitHub issues is not discussion board
