### ISSUE TITLE
Unable to display GE prices or look up players

### ISSUE THREAD

**Issue by vtruong68** [runelite/runelite#2834]
https://prntscr.com/jj73s8
https://prntscr.com/jj752v
https://prntscr.com/jj75ba

Here are the screenshots of what's going on. I also noticed that on the login, the world selection setting isn't working for me. These all worked fine for me just a day ago. I have no idea what's preventing RuneLite from looking up all this info.

**Comment by moglia1** [comment]
Has this happened for you before? Would it be possible to restart your client and see if it happens again?

**Comment by vtruong68** [comment]
It's been like this since yesterday. I've tried uninstalling and reinstalling as well as restarting my computer. I'm on windows 10 for what it's worth.

**Comment by moglia1** [comment]
Okay, seems strange. Is your client running 1.3.8.1? Also what version of Java are you running?
