### ISSUE TITLE
Show Value of Item On Hover In Bank

### ISSUE THREAD

**Issue by fidgetspinnerz223** [runelite/runelite#2835]
This is the main thing stopping me from fully leaving osbuddy. Would be nice to have on RL

**Comment by SirGirion** [comment]
Already exists, the setting is disabled by default. I believe it is in the bank value plugin settings.

**Comment by fidgetspinnerz223** [comment]
Dont see anything http://prntscr.com/jj8yn1

**Comment by wheelszr** [comment]
This feature is under the Item Prices plugin, which is disabled by default.
