### ISSUE TITLE
Add hooks for the UI customizer plugin.

### ISSUE THREAD

**Issue by raqes** [runelite/runelite#2843]
Add the missing hooks for the UI customizer plugin.

See #2722 

@devLotto - should know what to get ;)

If I remember correctly these are needed

# Hooks

@Export("getSpriteAsSpritePixels")

## class 35
@Export("compass")
static SpritePixels compass;

## widgets
@Export("widgetSpriteCache")
public static NodeCache widgetSpriteCache;

@Import("getspriteunid")
public SpritePixels getspriteunid(boolean var1) {

@Import("originalHeight")
@Override
int getOriginalHeight();

@Import("originalHeight")
@Override
void setOriginalHeight(int originalHeight);

@Import("originalWidth")
@Override
int getOriginalWidth();

@Import("originalWidth")
@Override
void setOriginalWidth(int originalWidth);

**Comment by devLotto** [comment]
"getspriteunid" should be "getWidgetSprite"
