### ISSUE TITLE
Linux: Unable to Login Due to Graphical Glitches

### ISSUE THREAD

**Issue by bscubed** [runelite/runelite#2847]
![screenshot from 2018-05-17 19-34-53](https://user-images.githubusercontent.com/1623826/40208782-7bb7af3e-5a09-11e8-9326-d8f3cfb170af.png)
Upon running RuneLite for the first time, I'm greeted with a weird graphical glitch where the flames on the sides are just tiled across the screen. I'm unable to click on anything or sign in. I'm not sure if it's a java thing or a linux thing? I'm on Arch linux and i'm running java version 10.0.1

**Comment by MagicfTail** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by bscubed** [comment]
Fix works! Sorry, I didn't see that
