### ISSUE TITLE
Client doesn't scale with Windows settings

### ISSUE THREAD

**Issue by skrooms** [runelite/runelite#2849]
When using the scaling options in Windows settings to change the size of UI elements (including applications) by a percent amount, RuneLite does not scale. It stays at its native size. This becomes a problem when playing on my laptop, which has a resolution of 2880x1800 at a 13 inch screen size. Though I'm not sure how to implement a fix myself, I believe the error is that the swing package claims that it is DPI aware, so Windows ignores it.

**Comment by Kamielvf** [comment]
Are you using the latest launcher? If you have an older version it is most likely one where we haven't fixed the DPI issue yet. Try redownloading the RuneLite installer and re-installing the program. Your settings will not be lost.

**Comment by deathbeam** [comment]
Use latest launcher, it works.

**Comment by poshdan** [comment]
It doesn't work for me:
https://imgur.com/a/GqO1177
I've got a 4k monitor running with Windows 7 at 150% DPI scaling.
I have reinstalled the latest launcher. Is there anything I have to do besides running the setup to make sure this works?
This option is not available on Windows 7:
https://github.com/runelite/runelite/wiki/Change-DPI-Scaling-%28Windows%29

Any help would be greatly appreciated!
