### ISSUE TITLE
How to enable bold text on ground items?

### ISSUE THREAD

**Issue by leochen0000** [runelite/runelite#2850]
Hey guys,

how do I make ground item text larger/bolder? 
A Friend was able to do it at 1:55 in this video but I cannot find the option.
https://www.youtube.com/watch?v=U_SPWPXFXmo&t=117s

Thanks,

Leo

**Comment by MagicfTail** [comment]
Settings -> RuneLite

**Comment by leochen0000** [comment]
Thanks for the quick reply
