### ISSUE TITLE
Jewellery count - Hide counts when inventory is force-closed

### ISSUE THREAD

**Issue by Unmoon** [runelite/runelite#286]
Jewellery count plugin draws the remaining charges even if the inventory is force-closed/hidden.
Happens with magic carpets. Maybe with random events and cutscenes too?

**Comment by SomeoneWithAnInternetConnection** [comment]
Tears of guthix appears to be affected by this as well:
![2018-02-26-080703_269x328_scrot](https://user-images.githubusercontent.com/34518321/36672199-6c9385ea-1acc-11e8-95aa-d1e5b178673d.png)
