### ISSUE TITLE
Death Markers & "Disconnect Marker"

### ISSUE THREAD

**Issue by Infinitay** [runelite/runelite#2864]
As the title states, a member in discord, SQWERTY, requested for a death marker plugin to help indicate where you've died. 

Some things to maybe consider, if possible of course:

- Use the world map to display the death marker ("go to death marker" button might be nice if so)
- Use of HintArrow to guide the user to death marker or point out where it is
- Note the world which the user last died in (and save it so it persists), maybe thru the use of an infobox

This might be too much, but also add a disconnect marker which kicks in when your `GameState` changes to `CONNECTION_LOST`. Also save the world and location, although if their internet disconnects, I'm not sure if it will be saved or not...

**Comment by DannysPVM** [comment]
Currently working on marking the location of death and setting a hint arrow to point in the direction of the players death. Not the most experienced in Java, but I'll also work on saving and displaying the world the player died on. I believe I can figure out those two things, but for the 'go to death marker' on world map and the 'disconnect marker', I think those are a bit out of my league. Will update tonight on what I've accomplished. Sidenote: If anyone else would like to do this while I try to figure it out, by all means, go for it. :)

**Comment by DannysPVM** [comment]
I'm just about done with this plugin. Currently, I am displaying the death location on the world map (you can click on the icon snapped to the edge of the world map to "go to" the location of the marker on the world map), displaying a hint arrow that guides the player to the death location, and showing an infobox that contains the world the player died on, as well as a countdown timer to reclaim items. I believe I am meeting all of the requested functionality for this plugin, aside from the disconnect marker. I'm not against working on a disconnect marker down the line, but for now I'll likely just PR the death marker. Below is a gif of the current plugin.

_Death Marker Plugin -- Thus Far_
https://puu.sh/As5XO.gif

**Comment by DannysPVM** [comment]
Just got done adding support for client crash/client close (Death information is saved now). Special thanks to @SoyChai for help with getting the timer correct on login after client closes/crashes. Cleaning up the code and running some tests now, will PR later tonight or early tomorrow morning if everything works as it should.
