### ISSUE TITLE
When I change settings, the UI goes crazy until I maximize

### ISSUE THREAD

**Issue by TheOnlyLite** [runelite/runelite#2865]
When I change a settings that has to do with text boxes, the UI goes crazy like this:

https://gyazo.com/d4ca7aaf44f6746f2c9163a094bf992a

It only gets fixed if I maximize the client then back to regular size.

**Comment by Infinitay** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
