### ISSUE TITLE
Feature Request: Prevent Skull tricking by highlighting Enemy players

### ISSUE THREAD

**Issue by Dustiness** [runelite/runelite#2868]
Last night, while doing some wildy slayer i was skull tricked and killed by 2 players with an almost identical username. (name was a weird combination of letters/numbers though its not like its a new concept.) I was winning against a pker who was seemingly very bad with his switches (range/melee) after a while he started running, i took the risk and chased, he had a slight gap he went into the rev caves northern enterence i went in after him i then saw him running to the left towards black dragons, i attacked him, except it was his friend who was named nearly identically to him, same level, same armor except he had ancients, for freezes as opposed to normal book for Tb i tried to escape them but ultimately failed since they kept swapping off on me and ultimately beat me. I'm sure something similar has happened to many of us here, it's part of the game

I had a thought, jagex once polled whether other player damage splats should have a different colour when they damage you, and it passed but was never implemented due to engine work, The philosophy behind that was to prevent or at least reduce players scamming by logging in under you and pretending to attack you when really it's their friend. IMO implementing a feature where players who have attacked you are highlighted similar to how slayer monsters can be would be similar in spirit as the previously proposed hitsplat change and not be infringing on game integrity. I have no problem with dying to other players, i enjoy anti-pking while doing some wildy slayer as much as others enjoy pking me, what i do have a problem with is how easy it is to wear identical gear to another player, have a name with a  single letter (1 instead of I) and tricking others into skulling up. Ultimately It's just another hour of Vorkath for me and i already had the NMZ points, but for some players losing their gear like this can be devastating and to me this is an integrity issue equivilant to GE Scammers/botters/fishers/lures/duel arena scammers

**Comment by SomeZer0** [comment]
I believe that Exilent has a similar feature, and since it really only serves to prevent scams, I'd support this.

However, we may want to consider disabling it in multi areas, as it could provide an advantage when clanning. (See how many people are attacking you, where they are, and who they are)

**Comment by Popedigoz** [comment]
Do you mean like this?
https://youtu.be/BHd1LsU0jtE

**Comment by Popedigoz** [comment]
I'd suggest a plugin where you right-click a player and it has 'Walk here', 'follow', **'Attack'**, 'Cancel', 'Lookup'
The 'Attack' would be modified into **'Attack (WILL give you a skull)'** or **'Attack (NO skull)'**.

**Comment by deathbeam** [comment]
We don't want to explicitely highlight players in wilderness. You can already highlight tiles of all players
