### ISSUE TITLE
OSBuddy is cheating their user stats. Change your to show RuneLite clients open rather than users logged in+playing

### ISSUE THREAD

**Issue by Tylemagne** [runelite/runelite#2883]
https://www.reddit.com/r/2007scape/comments/8k6aif/osbuddy_gained_13k_players_over_a_single_day/

**Comment by trimbe** [comment]
This is already the metric we show, we don't have support for logged in clients yet.

**Comment by devLotto** [comment]
OSBuddy is not cheating their user stats.
