### ISSUE TITLE
TripBuddy - Automated item list checker plug in. Make a new list, add items to it, and click scan invy+worn to get notified if you forgot items.

### ISSUE THREAD

**Issue by Tylemagne** [runelite/runelite#2885]
Original suggestion found here: https://www.reddit.com/r/2007scape/comments/8kf6xg/plugin_suggestion_equipment_checker/

**Comment by SirGirion** [comment]
I'll take a stab at this. Our side panel is a bit constrained for space so that will be the biggest challenge.

**Comment by Tylemagne** [comment]
Awesome
