### ISSUE TITLE
Idle Notifier no delay toggle

### ISSUE THREAD

**Issue by RebornFX** [runelite/runelite#2887]
As someone who loves paying as little attention as possible while doing afkable activities, I find the Idle notifier to be invaluable and a key feature that sets RuneLite apart from clients like Konduit. The Idle Notification Delay setting is basically the only thing that makes this feature usable while doing certain activities (such as fletching and glassblowing), as they have gaps in the player animation which would cause the client to spam the user with notifications if there wasn't a delay. However, some activities, afk woodcutting for example, one can get away with having no delay whatsoever and naturally the sooner the user is notified the better.

I would like to suggest a toggleable option to set up the the notifier so that there is no delay for these particular tasks. In order to know which tasks the notifier functions perfectly fine with no delay, I would be more than willing to test every task I can think of and compile a spreadsheet of which tasks work without a delay and which ones don't. Before going ahead and doing these tests, I wanted to see if it would be worth my time (if anybody is interested in the suggestion/if it's even possible/with the uncertain state of the future of RL, if it's worth making this change to the plugin).

**Comment by deathbeam** [comment]
I would suggest reconfiguring the delay when doing such activities instead of having no-delay toggle. Closing as wontfix, as you can already achieve desired result with already present config.
