### ISSUE TITLE
Java client is buggy on Linux distribution(s)

### ISSUE THREAD

**Issue by tom-sar** [runelite/runelite#2889]
While loading the jar file, the opened window looks like this:
https://imgur.com/a/lSN8Wrh
A piece of the interface is shown and duplicated. Maximising the window makes it turn completely black.

**command used:**
`java -jar RuneLite.jar`

**log:**
https://pastebin.com/zuZcRxY2

**java version:**
openjdk version "1.8.0_171"

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by drudigger** [comment]
I tried using this solution and now the window is blank and has no audio, Tested on my hp mini(intel atom) running lubuntu using same java. Atleast without disabling it loaded the game and music it was just super messed up.
