### ISSUE TITLE
Scaling issue on Windows

### ISSUE THREAD

**Issue by franzvrolijk** [runelite/runelite#2890]
RuneLite doesn't seem to follow Windows scaling. This is on Windows 10 64-bit. On a 4K display is it almost impossible to use because of how small it gets. I run my monitor @ 150% scale to make things a bit bigger, and RuneLite is the only application not following the scaling settings.

**Comment by Lordsthan** [comment]
It's a Java problem. Try this [solution](https://superuser.com/a/1207925).

**Comment by deathbeam** [comment]
As long as you are using launcher with .exe it should work.

**Comment by franzvrolijk** [comment]
Doing what Lordsthan said worked, only on the RuneLite executable instead of Java. Thanks.
