### ISSUE TITLE
Raids Item Reminder/Checklist (Based on Scouter)

### ISSUE THREAD

**Issue by bheisenberg** [runelite/runelite#2896]
This plugin will be an overlay (similar to the raids scouter) that has a checklist of required/recommended items based on the scouted raid. 

- Items that are required or recommended that are **present** in the player's inventory would show up green.
- Items that are required that are **missing** from the player's inventory would show up red
- Items that are required that are **missing** from the player's inventory would show up yellow

Each item would be checked based off an array of items. For example, if Guardians are present, the plugin would check your inventory/equipment for any type of pickaxe (bronze-dragon) to determine if the item is present or not.

This would be an addition to the Chambers of Xeric Plugin and would be disabled by default.

**Comment by bheisenberg** [comment]
I plan to develop this feature and would like to be assigned if it is approved.

**Comment by Stickaplex** [comment]
other than pick/anti or sanfew not sure what else you would add. Theres a lot of variations for some bosses you can bring. Like vasa its best if you bring either hasta or abby dagger but not everyone does or wants to. So as long as its not any actual weapons as thats a bit up to personal preference. 

Also something to note is pures/zerks or w/e who typically have alternatives to what the majority of people would use.

**Comment by Nightfirecat** [comment]
A plugin which does most of this is the [Cox Scouter External plugin](https://runelite.net/plugin-hub/show/cox-scouter-external) on the plugin hub. I don't believe it highlights the overlay or your inventory for items which are needed, but it does have most of these features. If needed, this can be extended, or another hub plugin can be developed for this specific purpose.
