### ISSUE TITLE
Herbiboar plugin performance issues

### ISSUE THREAD

**Issue by JDVaylen** [runelite/runelite#2898]
Herbiboar plugin drops fps immediately upon marking ground tiles with clickbox option showing. Fps goes back up as soon as they go away/when herbiboar spawns to be harvested.

**Comment by deathbeam** [comment]
Can you include logs? from %userprofile%/.runelite/logs/application.log

**Comment by JDVaylen** [comment]
https://pastebin.com/ggkAuesh Here is a copy of that file.
