### ISSUE TITLE
[Feature Request] Bank Place holder prices

### ISSUE THREAD

**Issue by Joshwat** [runelite/runelite#2900]
Hello,

I think a cool thing to add is to make the price check possible for bank place holders.

That would make it easier for you to keep track of the price of the items that you once had and for some reason sold or lost.

Lets say you got a Twisted bow in a friends raid and had to split it between them, you added the bow to your bank and now once you examine it you can see the current price.

Thank you :)

**Comment by deathbeam** [comment]
Implemented in #5894

**Comment by Joshwat** [comment]
Thats awesome! Thank you Tomas! :)
________________________________
De: Tomas Slusny <notifications@github.com>
Enviado: sábado, 29 de setembro de 2018 05:04
Para: runelite/runelite
Cc: Joshwat; Author
Assunto: Re: [runelite/runelite] [Feature Request] Bank Place holder prices (#2900)


Implemented in #5894
