### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by MrTIB** [runelite/runelite#2908]
Having problems downloading runelite. After starting the download the run file in the runelite folder disappears and Im unable to run the client. Using the windows version.

**Comment by Dovry** [comment]
Any antivirus throwing an error?

Does it appear in the start menu under 'recently installed programs'?

**Comment by deathbeam** [comment]
This is caused by falsy triggers probably from Avast. I would suggest trying the version for all platforms or adding exception to your antivirus.
