### ISSUE TITLE
[Skill Calc] Fletching Unf/Finished

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#2916]
Finished bows are listed, xp wise, as finishing the second half of it, like only if you strung an unf. Add a tick box or something to display full bows/crossbows as the full experience for making them.

Ex. Magic longs are 91.5 for unf, 91.5 for strung, 183 total. Checkbox would show Magic Longbow as 183xp.

**Comment by MagicfTail** [comment]
You can select multiple actions by holding shift, and the total will appear as the first option. You can use that for stuff like bows.

**Comment by forsco** [comment]
I feel this can just be achieved by using the shift highlight for the two parts.:

Unstrung Magic Longbow
String Magic Longbow

**Comment by Jalopyy** [comment]
Good points, I hadn't even thought of that. With the multi-action merger thing there doesn't need to be anything else.
