### ISSUE TITLE
Game display shows as repeating tile in Arch Linux

### ISSUE THREAD

**Issue by ggaytan00** [runelite/runelite#2919]
![screenshot from 2018-05-19 00-16-37](https://user-images.githubusercontent.com/6005968/40265229-0696789c-5afa-11e8-8259-bb4f35bcff8d.png)

Could very well be due to Arch linux and its finicky nature. Regardless, the normal client by jagex seems to work fine so something is amiss. 

If anyone knows where the code for the game display is I could also take a look, but my graphical programming experience is fairly limited

**Comment by gvjordan** [comment]
Have you tried to disable hardware acceleration yet?

https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by deathbeam** [comment]
Disable hardware acceleration.
