### ISSUE TITLE
3 step master clue scroll missing 

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#2923]
![image](https://user-images.githubusercontent.com/38350898/40266270-9e247154-5b50-11e8-8768-06de2663a12b.png)

You should put a box on the left stating:

1.) Go to GWD, Sara'a post chamber and dig
2.) Go to monks of entrana in Port Sarim and take a boat.
3.) Khazari jungle requiring legends.. Go to the dragons eyes.

**Comment by Hydrox6** [comment]
Master clue scrolls are not handled fully at the moment.
