### ISSUE TITLE
[Suggestion] Light/white ground EVERYWHERE

### ISSUE THREAD

**Issue by yaze1** [runelite/runelite#2927]
Could someone make a plug-in/code that changes the ground/floor into a very light color (for example: desert ground EVERYWHERE)?

The purpose is for dark places in runescape that make it hard to play/difficult to see in light real-life enviroments, to make it easier to see.

Perhaps also add the option to make the ground completely white.

If this is possible, could someone pm me (in-game name=cristo rei) when it is in the client and what the name is called?

**Comment by Abextm** [comment]
You can turn up your brightness in runescape's settings menu, that might help

**Comment by yaze1** [comment]
That does barely anything in places like wildy.

**Comment by deathbeam** [comment]
This was bad idea from the beginning so simply closed this
