### ISSUE TITLE
New Fairy Ring Icon for World Map Plugin

### ISSUE THREAD

**Issue by Con-No-1** [runelite/runelite#2940]
Updated the fairy ring icon for the world map to be more authentic looking and less busy.
[New icon here](https://i.imgur.com/82ZSoXC.png)

**Comment by MESLewis** [comment]
Comparison Pic (old over new)
![image](https://user-images.githubusercontent.com/597053/40268831-f601d802-5b42-11e8-9292-4e27a9d420ee.png)

**Comment by deathbeam** [comment]
I like the proposed one probably a bit more, the current one is a bit hard to look at tbh.
