### ISSUE TITLE
Add HP and Prayer bar on sides of inventory

### ISSUE THREAD

**Issue by Malfuryent** [runelite/runelite#2943]
Feature request 
Add a permanent / bigger hp bar above or below the player.
Or a hp bar next to your items ( optional prayer bar )
![hpbar](https://user-images.githubusercontent.com/22975740/40269141-32618810-5b7a-11e8-8e83-328cc353e21c.PNG)

Bar progression : 
![hpbar 2](https://user-images.githubusercontent.com/22975740/40269145-3de969f0-5b7a-11e8-838f-1528b6757bdd.png)

Resizable mode:
![hpbar resizable](https://user-images.githubusercontent.com/22975740/40269350-bdfbe69c-5b7d-11e8-861b-6d8f25563c4d.png)

i would love this so i don't have to look at the hp bar above my character, or the hp orb next to the minimap, but just focus on the inventory to eat my food / drink my prayer pots before looking back on the play screen. 
Should provide a more relaxing experience and looks quite nice. The inventory bars alone would be a very nice plugin on their own. 
The permanent HP bar above the player is nice for niche situations like wintertodt.

**Comment by forsco** [comment]
I like the idea, but where do they get placed for a user on resizable?

Prayer bar under the original HP bar is part of #2549 but needs to be rebased before continuation.

**Comment by Jossparla** [comment]
Added a resizable mode mockup

**Comment by raqes** [comment]
I really like the bar idea on the different viewports, so currently working to create this.

**Comment by Jalopyy** [comment]
Really like this idea, would love a 3rd party hp/pray bar above my character. One of the things I hate about coming back to RS after WOW is how I have to look away from the center of the screen to check important values, which isn't conducive to good awareness.

**Comment by Malfuryent** [comment]
@Jalopyy  yes this is exactly where my suggestion comes from, these are some important values which would be nice if you could check them and see them change from within the inventory

**Comment by Malfuryent** [comment]
@raqes Thank you :), i wish you the best of luck, i have no experience myself in developing sadly D:

**Comment by Adam-** [comment]
This was added in #3563 in Nov 2018
