### ISSUE TITLE
  Suggestion: allow the timers to be moved to diffrent locations on the screen

### ISSUE THREAD

**Issue by newtogithub9035** [runelite/runelite#2949]
atm the timers like veng timer and boss timers in the top left could use to be able to move where you want them, unless they already can be and im just dumb, but while pking the k/d ratio overlay from the actual game covers up the veng timer and makes it hard to see. would be nice to move it where It could be more visible, thanks to everyone who has a part in this client, yall are beautiful people!

**Comment by wa1id** [comment]
Hold ALT and start dragging overlays to whatever place you'd like ;)
