### ISSUE TITLE
RuneLite on Ubuntu (Gallium OS)

### ISSUE THREAD

**Issue by WKWilson7392** [runelite/runelite#2950]
I am having an issue and I don't know if anyone else has faced. Using Runelite in Gallium OS on my Chromebook I am having issues after loading up the client.

The screen is black, but the sound plays. I can click in the relative position of the sound button and mute it. So it seems the game is loading up, but nothing is actually displaying inside the client.

I do not think it is a resource issue, as I can load up OSB on on here with no issues, but I would much rather use Runelite because of the resource issues on chromebooks.

Any suggestions?

**Comment by ypperlig** [comment]
Hi,
Could you try disable hardware acceleration and see if that resolves the issue?
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by WKWilson7392** [comment]
That did it! Thanks!
