### ISSUE TITLE
[Suggestion] Show opponents stats (staking)

### ISSUE THREAD

**Issue by yaze1** [runelite/runelite#2961]
Could there be a plug-in that shows another player's stats when you hover over them?

This would be extremely handy in the duel arena.

If not hover over, is it possible to add an option to the right click menu that says "show player's stats"? and if u click it, you can see it in the chat box on the right side?

**Comment by devinfrench** [comment]
You can right click the player and select Lookup if you have the HiScore plugin enabled.

**Comment by RiskAGS** [comment]
Yes but on osbuddy, they show the stats on the bottom right screen during the challenge screens.
![examplezz](https://user-images.githubusercontent.com/39632018/40561262-28f41b48-608f-11e8-859e-f942c33728a8.PNG)

**Comment by deathbeam** [comment]
What about examining player and sending chat message?

**Comment by RiskAGS** [comment]
That would be as helpful!! Just display their combat stats only.

**Comment by Kamielvf** [comment]
OSB shows that whenever you interact with a player (attack, follow etc)

**Comment by RiskAGS** [comment]
loool I didn't even realise! That would be nice if something similar like that is implemented on Runelite as my laptop monitor is not too big and looking up peoples stats will take space on my screen.

**Comment by Infinitay** [comment]
Correct me if I'm wrong, but doesn't OSRS already list your opponents stats when you duel them?

**Comment by Nightfirecat** [comment]
This feature would be really useful for interaction with other players though--eg. attacking or following; it's one I miss from OSB for sure.
