### ISSUE TITLE
(MacOS Client) Client Minimize Button Not Working Properly

### ISSUE THREAD

**Issue by Jooaaay** [runelite/runelite#2967]
When trying to minimize the client the minimize button remains highlighted after clicking, but does not minimize the client. Additionally, the sidebar becomes frozen and other options cannot be clicked on. I tired right clicking in game to lookup people on the highscores in the sidebar to see if that would unfreeze it, but that did not work. So far, the only way to resolve this is to restart the client.

**Comment by JosephLivengood** [comment]
This happens to me as well on my devices running 10.13.4 and has been for months :-1:

**Comment by ypperlig** [comment]
Is the issue still present when you disable "Custom chrome" under RuneLite plugin settings?

**Comment by TheWindyMan** [comment]
@ypperlig No, after disabling "Custom Chrome" there is no issue

**Comment by RickertdeH** [comment]
This still happens. Would be great if anyone can take a look at this.

**Comment by traddcodes** [comment]
This is still an issue..

**Comment by Adam-** [comment]
I don't know what is causing this, but it appears to only happen if you 1) use the packr generated launcher and 2) use custom window chrome

**Comment by TylerADavis** [comment]
This might be due to a JVM issue relating to undecorated frames not iconifying on macOS, see below

https://bugs.openjdk.java.net/browse/JDK-8214046

**Comment by TylerADavis** [comment]
I updated my local JDK from 11.0.2 to 11.0.6 (as well as updated substance, but that didn't immediately fix it) and it now minimizes properly.

The minimized icon is just the app icon instead of how the game looks, but that's another issue

<img width="291" alt="image" src="https://user-images.githubusercontent.com/16804460/77713067-ab6a4c00-6f92-11ea-914b-bc174809bf6d.png">

**Comment by Adam-** [comment]
A new launcher release has been made (2.1.2) to fix this. See https://github.com/runelite/launcher/issues/81
