### ISSUE TITLE
[FEATURE REQUEST] RuneLite Interface/Aesthetic 

### ISSUE THREAD

**Issue by 2manyhits** [runelite/runelite#2975]
Hi Adam/Devs, (Images referred to at bottom of page)
Im loving using RL atm but one problem I have is the aesthetic/interface of it, I've been a paid member of OSB for years now and recently switched over to RL however maybe because im used to OSB but I think the interface looks cleaner and less aggressive? Im not sure what font is used in RL but but its quite sharp and pointy even when in bold, as I haven't really explained this very well I've linked some pics so you can kinda see what I mean (this is worse for me on left click options etc but also occurs on the sidebar too). I think it partly stands out to me because the font used doesn't match the font in game and to my ocd self it comes off a bit ugly, anyway I would love a plug in/ tooltip that allowed u to select the font of the entire client (including sidebar etc), failing that maybe just change to match the font in game as I believe osb has, furthermore ik this update has just been released but when hovering over and item in bank osb has the value and alch value contained in a box with coin and alch symbols on the left and it just looks really clean as opposed to RL, all this is also shown in the pics as im aware it may be confusing to understand just reading this. I believe RL is already a far superior client to OSB and its only getting better, thanks for reading this keep up the amazing work!

Kind regards 
Alex
<img width="1280" alt="screen shot 2018-05-19 at 21 52 05" src="https://user-images.githubusercontent.com/39445242/40273055-05c57d02-5bb1-11e8-9fad-56c4b0940225.png">
<img width="1280" alt="screen shot 2018-05-19 at 21 50 59" src="https://user-images.githubusercontent.com/39445242/40273069-34444456-5bb1-11e8-848b-24620dcfe0fa.png">
<img width="1280" alt="screen shot 2018-05-19 at 22 20 32" src="https://user-images.githubusercontent.com/39445242/40273166-53638c0a-5bb3-11e8-9602-b84f3b049f35.png">
<img width="1280" alt="screen shot 2018-05-19 at 22 21 12" src="https://user-images.githubusercontent.com/39445242/40273168-55e4ebd6-5bb3-11e8-9b3a-6f3dcccb05c6.png">

**Comment by Nightfirecat** [comment]
Next week's release re-skins the client, so you may want to check that before giving feedback. Screenshots can be found here: https://github.com/runelite/runelite/pull/1419

**Comment by deathbeam** [comment]
The font used is exactly same as the font in-game.

**Comment by deathbeam** [comment]
Closing this issue. Open respective issues for each part of the request, also i believe most of this issue is resolved.
