### ISSUE TITLE
Streaming mode.

### ISSUE THREAD

**Issue by mattgcc** [runelite/runelite#2980]
**Suggestion**:
Add streaming mode, which blurs all the important stuff:

1. Current world
2. etc

Such a mode could help streamers so their fans don't stream-snipe them.

**Comment by williammetcalf** [comment]
As a non-streamer, I'm not sure what all would need to be blocked out, could you provide a more thorough list if you can think of it?

**Comment by Nightfirecat** [comment]
Username, current world, clan chat name possibly?

**Comment by stoddy15** [comment]
My issue got closed can someone here create a toggle that hides your username locally

**Comment by Nightfirecat** [comment]
There are two RSN hider plugins (https://runelite.net/plugin-hub/show/rsn-hider, https://runelite.net/plugin-hub/show/custom-rsn-hider) and a world hider plugin (https://runelite.net/plugin-hub/show/world-hider) on the hub which address this problem handily.
