### ISSUE TITLE
Pvp left click options

### ISSUE THREAD

**Issue by cokeman439** [runelite/runelite#2983]
It would be a nice addition to the client if the option to remove left click attack on friends and clan members was added. This would help pull some users away from the konduit launcher which is much more pvp based.

**Comment by Nightfirecat** [comment]
This is disallowed by [Jagex's unofficial client statement](https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1):

> Removes or deprioritises attack, cast (or similar) options from the minimenu in any scenario
