### ISSUE TITLE
Add categories to skill calc

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#3000]
Would be nice to sort by categories in the various skills with a drop down menu

So for example farm would have allotments, herbs, trees, fruit trees, hops, tithe etc. (I know farm needs updating but still)
Con would have the various skilling rooms

Would be nice to have especially for things that have quite long lists, and honestly some skills categorize themselves like this so it would be easier to find/compare similiar things

**Comment by SoyChai** [comment]
Tip: Use each issue to try and describe *why* a feature is useful instead of just saying that it's nice c;

**Comment by Stickaplex** [comment]
@soychai fair point. Will do in the future. But for this one i compromised cause its nice to do

**Comment by deathbeam** [comment]
With search bar added this is probably no longer relevant as you can just search for stuff
