### ISSUE TITLE
Request: Add opacity bars to agility markers/ground markers

### ISSUE THREAD

**Issue by Rozza2hot4u** [runelite/runelite#3001]
My older laptop pixels struggle to differentiate between the coloured markers on tiles and the regular background. Could it be possible to add a dense, filled colour to replace the markers? 

Additionally, would it be possible to replace the clickable areas on agility courses to a solid circle? Thanks in advance :) 

~R

**Comment by deathbeam** [comment]
I dont understand, there is color configuration for both already isnt i.t

**Comment by Rozza2hot4u** [comment]
yeah, there is definitely. I was just wondering if it would be possible to implement an opacity sliders for the colours. Sorry if I was unclear

**Comment by deathbeam** [comment]
Ah, that is global issue we have atm, duplicate of #890
