### ISSUE TITLE
Could the potion change show immideatly like in OSBuddy?

### ISSUE THREAD

**Issue by yaze1** [runelite/runelite#3005]
Currently it takes 1 minute or something before it shows "next change in xx seconds"

Could it show instantly like in OSbuddy?

**Comment by yaze1** [comment]
but maybe show a "guess" right from the start, which may be incorrect like you say, but also might be correct, until it can show the 'for sure' correct one.

**Comment by iguaan** [comment]
We could save the stat drain timer before the logout and then load it on login.

**Comment by deathbeam** [comment]
This should be already sort of implemented.
