### ISSUE TITLE
Attack Indicator - Overlay not above chatbox in resizable window mode

### ISSUE THREAD

**Issue by AvonGenesis** [runelite/runelite#301]
When running the game in resizable mode instead of static, resizing the window causes the attack indicator overlay to not be fixed above the chat window.

Suggested solution is to probably create a new overlay position above chatbox left/right.

Screenshot of issue:
![unknown](https://user-images.githubusercontent.com/905293/34450256-9c37518c-ecb9-11e7-99b2-8473f874858d.png)

**Comment by Adam-** [comment]
Fixed in #302
