### ISSUE TITLE
Idle Notifier is dependent on Windows Notification Center

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#3014]
I have that shit on gaming/silent mode, + my Windows sounds are muted. I want to hear a sound when my HP is below <X> as the plugin promises. Make your own sound to the client itself rather than using Windows Notification Center. I know you can as there is the Metronome plugin which I CAN hear.

**Comment by deathbeam** [comment]
There is issue open already for custom notifications and sounds
