### ISSUE TITLE
Vet'ion timer erroneously appears after killing first form and not second form

### ISSUE THREAD

**Issue by bbirmingham** [runelite/runelite#3017]
https://github.com/runelite/runelite/blob/638e56b0d55de0d647a5e7bccc7252fc6e395c9a/runelite-client/src/main/java/net/runelite/client/plugins/bosstimer/Boss.java line 49

Perhaps changing it to

VETION("Vet'ion Reborn", 30, ChronoUnit.SECONDS, ItemID.VETION_JR),

would work?

**Comment by Adam-** [comment]
Added in #3306
