### ISSUE TITLE
Mac OS download gives corrupt image

### ISSUE THREAD

**Issue by Lenus1** [runelite/runelite#3021]
I've lurked OSRS reddit and youtube for a few months now, haven't played since the first android beta ended. I've noticed the drama and would like to support runelite through this tough time. Unfortunately I only have a mac laptop right now and every time I download, I get a warning and it says "corrupt image". I was wondering if this is something on my end or what exactly it is. Thank you

**Comment by deathbeam** [comment]
Duplicate of https://github.com/runelite/launcher/issues/16
