### ISSUE TITLE
Runelite crashing randomly when teleporting

### ISSUE THREAD

**Issue by somewhattoxic** [runelite/runelite#3026]
Literally got on and within a minute I attempted to teleport via Xeric's talisman and the client crashes fully. I received help from unmoon on discord in the #support section but nothing came of it. Here is the pastebin showing the log from today as soon as I logged on and crashed. https://pastebin.com/HUNBULiA

//side note//
I tried to replicate it by logging in and out then teleporting as well as reloading the client and teleporting, neither were successful in replicating the crash. Which leads unmoon and I to assume it's something on jagex's end.

**Comment by baaggg** [comment]
Happened to me and I couldn't replicate it either. I went into my POH, then tried using the Frem boots 4 to go to Rellekka and it crashed. Could be a **_big issue if pking_** and trying to go to deep wildy, or any other dangerous areas

**Comment by MESLewis** [comment]
Can we try and gather more data here? 
#3218 - @liamthfc says he teleported from draynor to camelot.

Multiple others have said it was when leaving PoH.

Can any further reports include their teleport destination and where they were teleporting from?

**Comment by Infinitay** [comment]
Can confirm PoH to tears of guthix via jewelry box doesn't make you crash

**Comment by Genesee101** [comment]
This happened to me. I was doing Vorkath and teleported out just as I was about to take damage. I spam clicked the ornate rejuvenation pool. The client lagged for a good 1-2 seconds. After I healed I used the Fancy Jewelry Box to teleport to Castle Wars. The client then lagged again for 1-2 seconds and then forced closed.

**Comment by deathbeam** [comment]
Is this still happening?

**Comment by deathbeam** [comment]
The original issue looked like it happened on outdated client, closing
