### ISSUE TITLE
Hopping worlds messes up NPC Indicators

### ISSUE THREAD

**Issue by Sovexe** [runelite/runelite#3030]
https://i.imgur.com/z75kbwa.png

Hopping worlds while the NPC indicators plugin is highlighting NPC's causes it to incorrectly highlight non-existent NPCs. The more times you hop the worse it becomes. Unsure if this same issue also exists with slayer highlighting.

Toggling the plugin resolves this.

**Comment by deathbeam** [comment]
This has been already resolved in master.
