### ISSUE TITLE
Add a tab that allows you to navigate the runescape wiki

### ISSUE THREAD

**Issue by littleflamingo** [runelite/runelite#3038]
I think adding the runescape wiki to the client would allow many players to have a much more pleasant experience, for example, if they were stuck on a quest, they can simply click a single button to be directed to that quests guide on the wiki. This would also allow players to search the wikis great features like the high alch calculator, or the detailed skill training guides. I don't know why this feature wasn't implemented from the start!

**Comment by xaviergmail** [comment]
This would have to open links in your default browser instead of having a separate 'tab' in order to keep the client lightweight. I do like the idea of being able to open a quest guide from the quest list, though!

**Comment by SomeZer0** [comment]
A menu in the sidebar that is able to load the mobile version of the osrs wiki would be pretty cool.

**Comment by deathbeam** [comment]
There is PR that adds wiki lookup options to various things in game. I feel like having wiki straight in the sidebar is moderately useless and that lookup PR is a lot better approach.

**Comment by Reasel** [comment]
You can checkout the PR Deathbeam mentioned [here](https://github.com/runelite/runelite/pull/2829).

**Comment by deathbeam** [comment]
Adding browser to sidebar is bad idea, closing as wontfix
