### ISSUE TITLE
Option to open/close SideBar when custom window chrome is disabled

### ISSUE THREAD

**Issue by Bistalock** [runelite/runelite#3039]
While using the RuneLite custom window chrome, an Open/Close SideBar button is available for users to show or hide the SideBar. 

Please give us the option to do this while not using the custom window chrome. The SideBar toggle option can be shown when right clicking on the already existing RuneLite system tray icon. Example screenshots below.

![image](https://user-images.githubusercontent.com/8323553/40284458-8bfeab4e-5c5d-11e8-9f2f-99a0c6d90252.png)

![image](https://user-images.githubusercontent.com/8323553/40284651-75783db0-5c60-11e8-9f11-b8fd240b981f.png)

**Comment by Kamielvf** [comment]
You can press ctrl+F11 to toggle the sidebar

**Comment by Bistalock** [comment]
I was not aware of this! Issue can be closed as functionality is already implemented.
