### ISSUE TITLE
Focus plugin search bar when opening plugin panel

### ISSUE THREAD

**Issue by MESLewis** [runelite/runelite#3044]
Automatically focusing the search box when opening the plugin configuration panel allows users to open and immediately search for plugins.

Personally when I want to change a plugin setting I use the search to find the plugin 90% of the time.

**Comment by deathbeam** [comment]
This looks like regression it was working before.

**Comment by psikoi** [comment]
Fixed locally, will upload a PR soon with a few ui fixes.

**Comment by Nightfirecat** [comment]
@psikoi @deathbeam I'm still seeing this issue in v1.4.3.1

**Comment by psikoi** [comment]
Really? Has the code on that ui component changed? Haven't been paying much attention due to exams.

**Comment by Nightfirecat** [comment]
Not as far as I can see, it still seems to be in there:

https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/ui/components/IconTextField.java#L169-L174

It just isn't focusing the search bar. :man_shrugging:

**Comment by psikoi** [comment]
Well, thats the code i added to prevent this, but ill take a look at this in a bit
