### ISSUE TITLE
2010 Hitsplats and HP bar and right click menu 

### ISSUE THREAD

**Issue by TylerTr95** [runelite/runelite#3048]
would like to see these added to the existing 2010 interface in the current 1.4 snapshot 

https://vignette.wikia.nocookie.net/runescape2/images/2/26/HitpointsBar.png/revision/latest?cb=20111122192135

https://cdn.discordapp.com/attachments/301497432909414422/447975911288209428/unknown.png

**Comment by Adam-** [comment]
2010 menu added in 917921dd477fc7aca442a96fc4d9a34ee00dc281

**Comment by chiragbharadwaj** [comment]
@Adam-  was wondering if there is any possibility of including the 2010-style hitsplats as well as a toggle on the style interface? IMO currently it looks a little strange with the old-school hitsplats but the 2010-style health bars.

**Comment by Nightfirecat** [comment]
Can you open that as a separate issue so we can track that?

**Comment by chiragbharadwaj** [comment]
Sure, will do.
