### ISSUE TITLE
Prayer Calculator

### ISSUE THREAD

**Issue by rubabubbbadub** [runelite/runelite#3049]
I think the Prayer skill calculator calculates Lit Gilded Altar and Ectofuntus bonuses correctly. Instead of making the multiplier 3.5x or 4x, it seems to add 350% and 400%, thereby making the multipliers 4.5x and 5x. 

I don't know anything about how to fix this, but I hope it isn't too tough to do. Would really appreciate it so I could plan things quicker! Thanks!

**Comment by forsco** [comment]
#2921
