### ISSUE TITLE
[Suggestion] Implement Item groupings for ground items.

### ISSUE THREAD

**Issue by Zanacross** [runelite/runelite#3053]
It would be awesome to have different coloured ground items for different item groups. 

Could have a herb group and have it as red, rune group as blue, ect.

**Comment by PimmoSocks** [comment]
I agree,I just made an account to suggest this same thing. I would love this feature! Some day please :)

**Comment by deathbeam** [comment]
Why I added label to this issue, I am pretty sure I wanted to close it at some point for some reason :d

**Comment by deathbeam** [comment]
So as I said, ground items config is already VERY cluttered, and you can mostly achieve different colours with just value thresholds (what is useless as well).
