### ISSUE TITLE
Add Extended Super Antifire to skill calc

### ISSUE THREAD

**Issue by cuenolife** [runelite/runelite#3054]
Currently top-level potions unsupported:

Extended Super Antifire(1-4)
40xp (per dose of shard) 

Most people do the 4 dose for most EXPERIENCE.

Could we maybe also add gp/xp based on GE values?

**Comment by psikoi** [comment]
The original developer for the Skill calc is planning on adding gp/xp.

**Comment by deathbeam** [comment]
Added in #3141 . For the gp/xp, that is either duplicate or open up new issue.
