### ISSUE TITLE
Kill count command

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#306]
It would be nice to have the "!kc" command in the RuneLite as well. I don't know how hard that would be, but it is doable I think.

**Comment by Adam-** [comment]
As discussed on discord, the reason why this probably won't be done is that it is too hard to prove when you have gotten a kill. Probably will have to wait for Jagex to release an API for this.

**Comment by matthewpetch** [comment]
If someone were to do it, would you decline the PR Adam?

I see no reason for it not to be added if someone writes it. Most other clients have it and it'd be nice to see what most other people see when players use !kc commands in-game (even if it isn't trustworthy). An API from Jagex would be nice, if it ever happens.

**Comment by Noremac201** [comment]
Wouldn't it only work with RuneLite users?

**Comment by l2-** [comment]
yes, it is possible to get (and even set) killcount info from osbuddy services with a guest token but adam is not a fan of the idea.

**Comment by Adam-** [comment]
I spoke to matthew about us pulling kc data from OSB. He said he is okay with us pulling data, but not submitting data until they can get some sort of verification in place. So, I would be okay with just showing the kill data from them but not submitting new kills.

**Comment by deathbeam** [comment]
Ah cool. So this means we can do following:

On "!kc" command:
1. Get kc data from OSB
2. Get kc data from RuneLite
3. Compare OSB and RuneLite data
4. Store OSB data if they are higher kc to RuneLite
5. Display RuneLite kc data

On kill/house check/row check:
1. Determine boss
2. Store kill count to RuneLite database

This requires:
* Service for accessing OSB kc data
* Making own RuneLite database for kill counts
* Find a way how to extract data from ring of wealth and house adventurer's log (from kill it is easy, just parse chat message)

Sounds doable.

**Comment by Adam-** [comment]
Added in #4067
