### ISSUE TITLE
Add hook to DynamicObject constructor

### ISSUE THREAD

**Issue by Rprrr** [runelite/runelite#3065]
Would be nice if the RuneLite API could support this. 

Olm Head for example makes use of DynamicObject for each animation (and not regular animations for an NPC).

**Comment by Harmindersingh05** [comment]
This could be very helpful. Is anyone is working on adding this hook?

**Comment by Nightfirecat** [comment]
As-is, plugins can subscribe to object spawn events to accomplish the same effect. What would this help with in particular?
