### ISSUE TITLE
29th and 30th expeditious (and maybe slaughter) bracelet charges dont decrease slayer kill count

### ISSUE THREAD

**Issue by iVilux** [runelite/runelite#3067]
![image](https://user-images.githubusercontent.com/1732344/40315050-fe34babc-5d22-11e8-86c9-147606d1a220.png)

This didn't update the kills left counter.

**Comment by iVilux** [comment]
Also this:
![image](https://user-images.githubusercontent.com/1732344/40315351-cb66dc7c-5d23-11e8-9bc8-7a53ed1e05dc.png)

**Comment by Reasel** [comment]
I will work on this. I think I know why this was happening.
