### ISSUE TITLE
Vanguards HP overlays for raids

### ISSUE THREAD

**Issue by Xexp** [runelite/runelite#3070]
Making small indicators for vanguards or for each bosses. Like for vanguards, a indicator that shows each 
 vanguard HP or the difference in percentages.  For shamans, you can have a little indicator for whenever he spits out acid and this can be the exact same concept for other bosses if needed.

**Comment by Infinitay** [comment]
I think @Kamielvf is working on adding more features to the existing raids plugin, such as the vanguard indicator you're asking for

**Comment by Nightfirecat** [comment]
This is provided in the [Cox Timers & Additions hub plugin](https://runelite.net/plugin-hub/show/cox-additions), and possibly others? This is somewhat less important now that the vanilla boss hp widget shows a range for the health they must stay within.
