### ISSUE TITLE
A new tab called npc-wiki

### ISSUE THREAD

**Issue by Floukru** [runelite/runelite#3072]
I'm suggesting this new plugin (which might need a lot of work?), but for sure this is going to be one of the best runelite features if developed or written.. I just hate opening google chrome just to check the npc's information and check his weakness and so on. So why don't we merge this on Runelite and it'll become like this?

- You'll need to draw the boxes 
- Extract info from osrs wiki?

![image](https://user-images.githubusercontent.com/38350898/40320507-a11da7f0-5d34-11e8-93d8-8857d1d250c8.png)

**# An example:**
![image](https://user-images.githubusercontent.com/38350898/40320976-31cf2962-5d36-11e8-87e6-80976f13d1e9.png)
You/we can edit few things about this and add or remove and so on.

Would like to hear everyone's opinion?

**Comment by Reasel** [comment]
I think someone already suggested this in [#3038](https://github.com/runelite/runelite/issues/3038). 

I also have an open PR that will allow you to take you to the wiki page for almost anything in game. You can find it [here](https://github.com/runelite/runelite/pull/2829). I think this should be enough. Adding a full tab would be very cumbersome and would limit you to only monsters...

**Comment by Floukru** [comment]
Just saw #3038 and Reasel's PR. Mb.
