### ISSUE TITLE
Remove individual xp trackers, low hp notification

### ISSUE THREAD

**Issue by PxuLL** [runelite/runelite#3080]
Feature request:

Would like to be able to remove a single skill from the xp tracker sidebar, without resetting them all.

Also would be great if a notification would be added if hp was say below 20 or 10 etc. 

Lastly, is it possible to make the notification for now out of combat be a bit longer in terms of detecting not in combat. When afking in spiders f2p sometimes it takes about 3-5 seconds for the second spider to manoeuvre if they're stuck and most of the time the notification gets sent that not in combat, but when opening the client a spider would attack after 1sec of the notification.

**Comment by Nightfirecat** [comment]
1. Click the skill icon for the specific skill tracker
2. The Idle Notifier plugin has a low HP notification threshold which you can configure
3. The same plugin has a delay that can be configured as well

**Comment by PxuLL** [comment]
Wow sorry for that lol, that solved it thanks. Didn't realise you could reset the skill by clicking its icon. And found the idle notifier plug in cheers!

**Comment by Reasel** [comment]
I think this issue can be closed then yes?

**Comment by PxuLL** [comment]
Yeah
