### ISSUE TITLE
Runelite button tooltips

### ISSUE THREAD

**Issue by Blood-Raven** [runelite/runelite#3087]
Whenever I use the interface and hover over a button to display the tooltip for the button my interface completely brakes. Pictures of what happens below.

![image](https://user-images.githubusercontent.com/9058554/40330518-193f57e6-5d45-11e8-9312-174a46602360.png)
![image](https://user-images.githubusercontent.com/9058554/40330528-213ea032-5d45-11e8-9678-8e97f2fa660e.png)
![image](https://user-images.githubusercontent.com/9058554/40330533-2837259e-5d45-11e8-98ff-cd72e336229d.png)

**Comment by devLotto** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
