### ISSUE TITLE
Something wrong with my client

### ISSUE THREAD

**Issue by ShadySus** [runelite/runelite#3098]
After re-downloading my client again, i notice when i hovered over the side bar where all the icons are, that it is all black on the side and when i hover over them and after i move my mouse away they disappear. I tried re-downloading it several times but it keeps happening, is there a way i can fix this issue? Let me know if i need to explain it better if need be.

Kind regards, 
ShadySus

**Comment by Juzzed** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
