### ISSUE TITLE
Feature Request: Indicate whether an item is required for a Clue Scroll

### ISSUE THREAD

**Issue by antweer** [runelite/runelite#3105]
The examine message for an item should display if that item is required for a Clue Scroll, and if it is, display what the level of the Clue Scroll is. This would improve players' ability to decide whether they should keep or drop items that are seemingly useless.

**Comment by Nightfirecat** [comment]
[Per @eprkr's comment, another solution may be to highlight items used by clue scrolls:](https://github.com/runelite/runelite/issues/10855#issue-569405324)

> When toggled, any item that is required for a clue step/stash unit is marked with a small symbol or something so you know that it should go in the bank for later instead of alching/dropping. This would mostly only be useful for ironmen.

**Comment by Nightfirecat** [comment]
This is addressed [by the emote-clue-items hub plugin](https://github.com/larsvansoest/emote-clue-items).
