### ISSUE TITLE
Menu Swapper Suggestion Construction

### ISSUE THREAD

**Issue by king-koda** [runelite/runelite#3107]
Is there a way to swap the menu items in construction so that a superior garden bench has the menu item "sit on bench" at the bottom? this way the remove and build position in the menu will be the same, i use mousekeys to do construction however the distance to hop is different between the bench being built and bench being removed. this also occurs for the carved wardrobe. currently i have to mouse keys with teak tables because the build and remove are in the same position in the menus. this would be awesome thanks!

**Comment by William1Gray** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features Under menu entry swapping if I'm understanding your request properly

**Comment by king-koda** [comment]
Oh nah I didn't mean make it left clickable I mean, currently the menu when building with teak garden benches is:
(Not built) - walk here, examine, build, cancel
(Built) - sit on bench, walk here, examine, remove, cancel

When using mouse keys to right click go down click it can't be done because build is the 3rd menu entry when it's not built but is the 4th menu entry when built aka. if my mouse key setup can right click and jump to the the 3rd entry to build, ideally I'd want the remove menu entry when built to also be the 3rd entry, otherwise can't mouse keys fast build it. It's the same with carved wardrobes too becAuse open is the first menu entry and remove becomes the 4th. Hope this makes sense

**Comment by deathbeam** [comment]
We dont want to swap anything construction related, sorry.

**Comment by TheBauwssss** [comment]
@deathbeam If I may ask, what is the reason for not wanting to swap anything construction related? 

I have the program skills to do it myself, but I would rather not get banned. Would I get banned if I were to use a modified RuneLite client with a modified Menu Entry Swapper plugin to make Build (if not built) and Remove (if built) the left click options on for instance, an oak larder?

**Comment by Nightfirecat** [comment]
It's basically the same reason as the rest of the entries described in the "Menu Entry Swapping" section--it's more than a client ought to change; it would be too strong.

You can run whatever version of Runelite you want locally (official or not), but we cannot guarantee unofficial builds will be considered allowable by Jagex's standards.
