### ISSUE TITLE
swap "talk to" and "bank" options for bankers, "talk-to" and "exchange" option for GE Clerks, OSbuddy has this, would love RL to

### ISSUE THREAD

**Issue by kaydiechii** [runelite/runelite#3109]
one of the many QOL things i really would like to see RL have is this, one click banking and one click use of the ge would be really nice <3

**Comment by raqes** [comment]
That's already in Runelite. Checkout the Menu entry swapper plugin.

**Comment by Reasel** [comment]
If this is resolved you should close it.

**Comment by Nikkandoh** [comment]
When barb fishing, it says "Training: Agility" on Discord
