### ISSUE TITLE
No-break spaces are not displayed correctly

### ISSUE THREAD

**Issue by UniquePassive** [runelite/runelite#311]
The comma character ``,`` is not displayed correctly in the font we're using:

![](https://i.imgur.com/AbPVaZ1.png)

**EDIT:** It's not a comma that is not being rendered, it's a so-called no-break space [NO-BREAK SPACE (U+00A0)](http://www.fileformat.info/info/unicode/char/00a0/index.htm).

**Comment by UniquePassive** [comment]
Hmm.. yeah, seems like they only look weird in the JSpinners..

![](https://i.imgur.com/PTuN3ug.png)

**Comment by SomeoneWithAnInternetConnection** [comment]
I've definitely seen the same thing happen in the hiscore name textbox though, I'm don't think that the spinners are necessarily the cause. Next time I see someone with a space in their username, I'll see if I can reproduce it

**Comment by UniquePassive** [comment]
If I remove ``setUIFont(new FontUIResource(FontManager.getRunescapeFont()));`` from ClientUI, I see that the comma separator is a correctly displayed space, so it seems like it's related to spaces like you said.

**Comment by UniquePassive** [comment]
If I copy the "space" in the spinner, I get %C2%A0 (``0xc2a0``) and not a space. Now I wonder why the spinner is using that instead of real spaces..

**Comment by SomeoneWithAnInternetConnection** [comment]
Looks like that's UTF-8 for [NO-BREAK SPACE (U+00A0)](http://www.fileformat.info/info/unicode/char/00a0/index.htm)

**Comment by UniquePassive** [comment]
Using ``setUIFont(FontUtilities.getCompositeFontUIResource(FontManager.getRunescapeFont()));`` makes it so it falls back to a default font for the glyphs that cannot be rendered using the Runescape font, but FontUtilities is from the proprietary ``sun.font`` package, so there's that..

Apparently you can get around the proprietaryness by making use of StyleContext as per https://stackoverflow.com/a/35327059, but I could not get it to work.

**Comment by UniquePassive** [comment]
Okay it seems like the StyleContext method didn't work because the font hadn't been loaded at the point of trying to use it. FontManager's static initializer must be run before the setUIFont line.. Hmm..
