### ISSUE TITLE
XP tracker: only use in-game time for ETAs

### ISSUE THREAD

**Issue by LeviSchuck** [runelite/runelite#3113]
If I let runelite stay on overnight while I am gone, when I am back the next day and **continue** smithing, it has really bad estimates for time til next level/goal since it includes all the time I was gone from the game.

Suggested solution: use game ticks to add time to each skill, and only if the delta between ticks is within say 10 seconds (to account for connectivity?).

I plan to address this one myself, making an issue to document my intent.

**Comment by LeviSchuck** [comment]
@MagicfTail Can you explain what you mean?

**Comment by Jasper-ketelaar** [comment]
I think he means that not everyone will want to have their xp/hr only be tracked when they are playing. I would personally prefer just having a pause button for this as opposed to your suggestion solution as that'd be easier than having to turn it on and off all the time.

**Comment by LeviSchuck** [comment]
How does this sound, ability to auto-pause skills that stop receiving xp changes after a minute or so?

**Comment by Jasper-ketelaar** [comment]
That sounds like a good solution to me.

**Comment by LeviSchuck** [comment]
I have auto unpausing when XP is gained working, as well as some graphical changes to indicate the pause clearer.
