### ISSUE TITLE
Expand the Raids Plugin

### ISSUE THREAD

**Issue by kopvm** [runelite/runelite#3119]
Would it be possible to get the raids plugin expanded so that it also showed the projectile hits for vasa and tektoon etc.
 Would make runelite the perfect client for raids aswell!

**Comment by 2manyhits** [comment]
Also maybe make it so you can see the rotation whilst in the raid, as well as, if possible show what att olm is doing (mage/range) and possibly warn you what specials are coming eg warning before lightening and reminder for crystals (maybe highlight your square and have a 3 second countdown).

**Comment by deathbeam** [comment]
Duplicat of some other raids issue. Please, search issues before posting to not waste our time.
