### ISSUE TITLE
Runelite Notes Issue/Inconvenience

### ISSUE THREAD

**Issue by VladmirVorkeshky** [runelite/runelite#3130]
So if you're like me you have an alt account. However, if you have an alt account and write a note on one Runelite application and not both, the note resets to the last Runelite application closed's notes. I'm assuming this would be a rather simple and easy issue to patch. Thank you!

**Comment by deathbeam** [comment]
Dont think this is easily solvable, we cant just magically sync settings between 2 different open clients.

**Comment by basicDamen** [comment]
@deathbeam I'm not too sure on if it's feasible or not, but, what if when 'notesChanged' is called and it saves the config completely. Then, when the notes 'focusGained' is called, it reloads the config for 'notesData'.

Essentially, it would save completely after being changed. Then, upon gaining focus within the plugin again, it reloads itself to make sure it's completely up-to-date with the config-data.

Scenario:
- Client 1's notepad is edited.
- Client 1 loses notepad focus and saves config.
- Client 2 gains notepad focus, reloads config, and is now identical to Client 1's notepad data.

Let me know if this is a realistic concept or not.

**Comment by Nightfirecat** [comment]
This issue is more actually "Settings are saved by the last-closed client", than anything to do with the Notes plugin specifically. Anyways, this is largely solved by the addition of config profiles, which were added in 831189459ba51538b239a33b7d632bd2d9e4e8a3.
