### ISSUE TITLE
2010 interface close button inconsistency 

### ISSUE THREAD

**Issue by Pupper3** [runelite/runelite#3136]
When hovering over the close button in the skill guides, the button is replaced by the new sprite temporarily. 

All of the close buttons are untouched except for the logout button in resize-able and the skill guides.
 
![2018-05-22_23-16-13](https://user-images.githubusercontent.com/16019892/40402229-73b02268-5e18-11e8-8df3-dd673cd90535.gif)

**Comment by sethtroll** [comment]
@raqes this is just sprite 54, should be a simple fix

**Comment by j03l** [comment]
Need to find the 541 image, dont know if anyone has it?

**Comment by raqes** [comment]
I got the image and fixed it locally, I'll make a PR once I get home.
