### ISSUE TITLE
[Feature upgrade] Herbiboar hide pick fungis

### ISSUE THREAD

**Issue by sven8100** [runelite/runelite#3142]
![image](https://user-images.githubusercontent.com/35641814/40421349-e7b776fc-5e8b-11e8-83cf-b3d9cb92e6a9.png)

Almost at every object you need to search are there one,

Annoys me, also a risk for hardcore ironmans btw

**Comment by deathbeam** [comment]
We are not planning to add hiding of menu entries, so, no.

**Comment by dupperT** [comment]
you don;'t have to hide it just swap it with walk
