### ISSUE TITLE
Arclight charges 

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#3144]
![image](https://user-images.githubusercontent.com/38350898/40427152-8f4897fc-5ea5-11e8-9ff6-bedd2ec4c496.png)

Features:
- Charges

**Comment by Reasel** [comment]
Where should this be placed? Is there plans to have a config for items like this and the other weapon charges? Like Iban's, Tentacle Whip, etc.

**Comment by Reasel** [comment]
@Floukru I mean where would the plugin be located. Like is this under slayer? Is this under jewelry? I would think this belongs in its own item charges plugin. Also as far as I know the best way to track arclight charges would be to count attack animations, which wouldn't be very consistent.

**Comment by Floukru** [comment]
@Reasel I'd say mostly slayer/bossing so ya
-

**Comment by Nightfirecat** [comment]
This either is tracked, or should be tracked, in a hub plugin like this one: https://runelite.net/plugin-hub/show/weapon-charges-2
