### ISSUE TITLE
Login interface is just one tile repeating on Linux

### ISSUE THREAD

**Issue by karliyo** [runelite/runelite#3146]
Running ElementaryOS and latest build from Runelite.net.  
Java version: Java(TM) SE Runtime Environment (build 1.8.0_171-b11)

![https://i.imgur.com/xyWZ4HX.png](https://i.imgur.com/xyWZ4HX.png)

No such issues when running project from IntelliJ.

**Comment by Juzzed** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by ypperlig** [comment]
Try disabling hw acceleration:
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by karliyo** [comment]
Yeah, that worked. Didn't think of this.
