### ISSUE TITLE
Huge FPS decrease when browsing plugins

### ISSUE THREAD

**Issue by gccltl** [runelite/runelite#3149]
**Huge FPS decrease when browsing plugins**.

FPS drastically decreases if you're scrolling through plugin menu.

![fps](https://user-images.githubusercontent.com/28257966/40431252-e59252be-5e5b-11e8-87b5-efd3de08cf36.gif)

**Comment by Kamielvf** [comment]
Do you have the FPS control plugin's limit mode set to unfocused? If that's not it then try [this](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration).
