### ISSUE TITLE
Clue scroll plugin - Missing guide for aggie

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#316]
Clue scroll plugin is missing guide for this cryptic clue:

```
Aggie I see, Lonely and southern I feel I am neither inside nor outside the house yet no house would be complete without me. Your treasure lies beneath me. 
```

**Comment by Noremac201** [comment]
https://github.com/runelite/runelite/blob/7ed639068fea22fb7b80c40f84c44d6808551618/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/ClueScroll.java#L243

There should be, is it not rendering?

**Comment by deathbeam** [comment]
No, not rendering :/

**Comment by deathbeam** [comment]
Closing as duplicate of #357
