### ISSUE TITLE
Configurable jagexcache location

### ISSUE THREAD

**Issue by dovydasvenckus** [runelite/runelite#3162]
I wasn't able to find how to change default jagexcache location. By default it stores it in /home/<username>jagexcache .

I'd like to keep my home directory tidy. So it would be nice to be able to configure location where jagexcache is stored

**Comment by devLotto** [comment]
I think Matthew of OSBuddy said that they were banned for changing the location. I don't know the specifics, but yeah.. Maybe you can use a symlink

**Comment by odhil** [comment]
You could give JVM -Duser.home argument. I don't think that the launcher will pass JVM arguments to the client so you can set _JAVA_OPTIONS environment variable to -Duser.home="/pat/to/jagexcache". 

```bash
RL_DIR="/path/to/jagexcache"

if [ -z _JAVA_OPTIONS ] ; then
	_JAVA_OPTIONS="-Duser.home=\"$RL_DIR\""
else
	_JAVA_OPTIONS="$_JAVA_OPTIONS -Duser.home=\"$RL_DIR\""
fi
export _JAVA_OPTIONS

java -jar /path/to/RuneLite.jar
```

**Comment by jeffhoe** [comment]
I too would love this feature. rsu-client has this feature built in. I believe it's opensource as well. Anyway to look into it? Not too sure where to start. Maybe I could email HikariNight?

**Comment by ChrisLane** [comment]
Just came to suggest this myself after finding a bunch of files in my home directory.
I'd appreciate if this also defaulted to `$XDG_CACHE_HOME` on Linux if available.

**Comment by jorgeluiscarrillo** [comment]
I've been using the above mentioned workaround in a Desktop Entry to launch the Linux AppImage and it works well.
```
[Desktop Entry]
Type=Application
Terminal=false
Name=RuneLite
GenericName=Old School RuneScape client
Comment=RuneLite is a free, open-source and super fast client for Old School RuneScape
Exec=env _JAVA_OPTIONS=-Duser.home=/home/MY_USER/.local/share/runelite /home/MY_USER/path/to/RuneLite.AppImage
Icon=/home/MY_USER/.local/share/runelite/.runelite/icon.png
Keywords=runescape;osrs;
Categories=Games;
```
In my case, I created a runelite directory, under `$XDG_DATA_HOME` (`.local/share`), because that's where it made the most sense to me.

**Comment by coreybruce** [comment]
Change the launch script to 

```
#!/bin/sh

RL_DIR="/home/$USER/.runelite"

if [ -z _JAVA_OPTIONS ] ; then
	_JAVA_OPTIONS="-Duser.home=\"$RL_DIR\""
else
	_JAVA_OPTIONS="$_JAVA_OPTIONS -Duser.home=\"$RL_DIR\""
fi
export _JAVA_OPTIONS

exec java -Dhttps.protocols=TLSv1.2 -jar /usr/share/java/runelite/RuneLite.jar "$@"
```

to easily fix the issue, it's that easy.

**Comment by Nightfirecat** [comment]
[Per Adam's comment](https://github.com/runelite/runelite/issues/7940#issuecomment-999270924) and linked commit, we've moved jagexcache into `~/.runelite`. Allowing `.runelite` to be in a user-configurable location (`$XDG_CONFIG_HOME` for instance) is tracked in #7940. imo the root of this issue--`jagexcache` polluting the user's home dir--is solved, so I am closing this issue.
