### ISSUE TITLE
Medium Cryptic clue highlights all barbarians, not just males

### ISSUE THREAD

**Issue by Enriath** [runelite/runelite#3164]
The Medium Cryptic clue "The dead, red dragon watches over this chest. He must really dig the view" requires the player to kill a male barbarian to obtain the key, but the plugin incorrectly highlights all barbarians, including females.

![runelite_2018-05-23_18-46-27](https://user-images.githubusercontent.com/2979691/40441832-114eb844-5eba-11e8-8ce9-24f17c8c3189.png)

**Comment by devLotto** [comment]
Not fixable at the plugin's current state, as it uses npc names and not npc ids.

**Comment by yanikore** [comment]
If desired, current names could be migrated by allowing both IDs and names until the names have been converted to IDs. Otherwise this might look like a big task.

**Comment by Scahry** [comment]
when highlighting the npcs you could ignore those with the female IDs when this clue is active though this is probably not a clean solution and the hintarrow can still point at them.

**Comment by Nightfirecat** [comment]
This particular clue is no longer problematic [as Jagex has updated it to drop the key from barbarians of either gender](https://secure.runescape.com/m=news/diversity--inclusion-changes-and-quest-speedrunning-updates?oldschool=1):

> To coincide with the above change, Barbarian Village inhabitants of any gender can now drop Clue Keys - hurrah!

The more general issue of the clue scroll plugin highlighting the wrong NPCs (which have the same name), we'll continue tracking this in #5231.
