### ISSUE TITLE
Client crashes on Java client, when interacting with sidebar.

### ISSUE THREAD

**Issue by m00fin** [runelite/runelite#3165]
I am running Ubuntu 18.04 LTS. The client freezes up some-what randomly when interacting with the side bar.

I will afk grind for a couple of hours without interacting with the sidebar, once I go to click an icon on the sidebar, the sidebar opens up, then over about 3-5 seconds the game fps slowly drops to 0 and then I am then unable to interact with the client window at all and need to open system monitor to end the java process. The issue seems more common when I do not interact with the sidebar for an extended period of time, though the issue has occurred after about 15-20 minutes as well a few times.

Have had this issue for about a fortnight so it has occurred over multiple client versions.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
