### ISSUE TITLE
Prayer Potion Notifier (request)

### ISSUE THREAD

**Issue by FaLLeNShoTz** [runelite/runelite#3178]
Is anyone able to add a prayer notifier in an in-game overlay similar to the one osbuddy uses. It will pop up with a little flashing icon on screen when the ideal time to drink a prayer pot is. Let me know!

**Comment by Infinitay** [comment]
#3089 is working on this and nearly complete if I'm not mistaken.

**Comment by FaLLeNShoTz** [comment]
Okay thanks! Yeah I see it now. Someone me tioned a comment to make it more noticeable. But that's much better than nothing!

**Comment by FaLLeNShoTz** [comment]
Hope it gets added soon!

**Comment by Adam-** [comment]
Duplicate of #598
