### ISSUE TITLE
Tears of Guthix plugin to track tear streams' guaranteed 9 second minimum lifespans

### ISSUE THREAD

**Issue by Sovexe** [runelite/runelite#3180]
Around 2 months ago Tears of Guthix received a rather significant buff. That buff was guaranteeing that tear streams will last a minimum of 9 seconds before vanishing

![https://i.redd.it/jtzm74hi1kk01.jpg](https://i.redd.it/jtzm74hi1kk01.jpg)

Please create a plugin that tracks tear streams to indicate their remaining guaranteed life span

I would recommend color coded pie timers that would count down from 9 seconds to 0. As for colors you could either green and blue to match the good and bad tear colors. Or maybe Blue and Red to be easier to discern quickly.

**Comment by Infinitay** [comment]
I have the code for this thats a month or two old, I guess I'll work on updating it when I get the chance

**Comment by Stickaplex** [comment]
How would you do it once its past 9secs though? Because as far as i know there is no maximum time

**Comment by deathbeam** [comment]
i guess just create some red marker?

**Comment by Infinitay** [comment]
No they disappear after 9 seconds

**Comment by Sovexe** [comment]
Looks great! Exactly what I had in mind

**Comment by Infinitay** [comment]
Alright I guess I'll update it/clean it up and push it

**Comment by Infinitay** [comment]
Yep #3475, changed it to use the new `ProgressPieComponent` we have which made things cleaner and simpler, so thank you to Kamiel
