### ISSUE TITLE
Medium digsite clue

### ISSUE THREAD

**Issue by somewhattoxic** [runelite/runelite#3188]
https://i.gyazo.com/dfef6cde5fb6c5b61febe127ed020f1e.png

^ add this to the clue plugin, it doesn't highlight the emotes necessary to do the clue step.

**Comment by Nightfirecat** [comment]
It looks to me like this is already implemented... I double-checked the clue text and didn't see anything wrong with it.

https://github.com/runelite/runelite/blob/a56c32f8ae28427ad0be3d102e3a3d75d777e554/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java#L440

**Comment by Nightfirecat** [comment]
I think this issue can be closed, this has not been reported again since being opened, and the code looks fine.
