### ISSUE TITLE
Menu |entry swapper configuration addition

### ISSUE THREAD

**Issue by zygis278** [runelite/runelite#3194]
Can there be addition to change "talk-to" and "pickpocket" on the bandits in pollniveach.
That way you wouldn't need to right click once you knock the guard down.

**Comment by Hydrox6** [comment]
[Rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features)

**Comment by deathbeam** [comment]
Rejected feature, sorry

**Comment by zygis278** [comment]
why? ;(

**Comment by kulershk** [comment]
What why @Hydrox6 posted why! 
![image](https://user-images.githubusercontent.com/26186873/40483737-a4780a42-5f61-11e8-8f95-4a164d5d72d7.png)
