### ISSUE TITLE
Camera Location List

### ISSUE THREAD

**Issue by shuyin82** [runelite/runelite#3195]
I was wondering if anyone could make a plugin that will allow me to save the current camera angle to a list to be used later. Something like this would be useful for me when I create YouTube videos.

An example of how this would work would be camera is at x degrees, click save, move camera to different position.. click the saved camera angle on a list for it to snap back to that desired location. Being able to name the camera angles would also make it a lot easier to remember them. 

I have no idea how the runelite client works, I would need some help on how to install this plugin also.

Cheers in advance!

**Comment by abextm** [comment]
This would be highly abusable.
