### ISSUE TITLE
Use . instead of , for decimal points in the Experience tracker

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#3196]

**Comment by sanderdegroot** [comment]
I think whether `.` or `,` is used as the thousands separator should depend on which symbol is configured for the thousands separator at the OS level. For example in Windows:
![a5tef 1](https://user-images.githubusercontent.com/20391979/40505882-a7803cee-5f63-11e8-9190-6ea94e1cabcf.png)

I would assume other OS's make this symbol configurable as well, but if not, we can fall back to the user's locale to determine which symbol to use.

**Comment by deathbeam** [comment]
Duplicate of #4054 (as that one is more nicely written)
