### ISSUE TITLE
Screen marker delete warning hides behind client if client always on top is on.

### ISSUE THREAD

**Issue by Kiskis1** [runelite/runelite#3197]
Have to open task manager and try to end the task. The client is not moving and gives sounds when trying to click anything.

**Comment by TzZek** [comment]
Temp fix would probs just to be hit enter to confirm the deletion.

**Comment by MESLewis** [comment]
As a work around for now you can hit enter when this happens and it will delete the marker.

**Comment by deathbeam** [comment]
Duplicate of #2690
