### ISSUE TITLE
[Suggestion] Could the GE plug-in be changed so it's more clear? (with picture example)

### ISSUE THREAD

**Issue by yaze1** [runelite/runelite#3204]
https://imgur.com/a/ULqsp8L

Letters should be bigger (specifically the amount of the item and wether it's buying or selling).
The progress bar should be bigger, (when there's progress, two clearly distinguishable colors) and thus more visible.

Lastly, the boxes should be so big that in fixed mode, the boxes fit the screen from top of runescape client to bottom of runescape client.

This would be so helpful.

Thanks in advance.

![suggestion](https://user-images.githubusercontent.com/39431966/40485550-1e6cfa68-5f5f-11e8-9c90-7aa69f46cf79.png)

**Comment by Kamielvf** [comment]
It exactly fits the screen, and with your suggestions making them bigger they would no longer fit.
![image](https://user-images.githubusercontent.com/35824069/40485684-8284dba6-5f5f-11e8-9895-5ffd89aee747.png)

**Comment by deathbeam** [comment]
No, this is bad suggestion.
