### ISSUE TITLE
Feature Request: Option to use Brimhaven Agility timer without the agility clickboxes

### ISSUE THREAD

**Issue by brimbrim** [runelite/runelite#3206]
I would like to use the timer without showing the clickboxes
![2018-05-24_22-40-02](https://user-images.githubusercontent.com/39590807/40486198-f68252d8-5fa3-11e8-9c04-dff92f787b3f.png)

**Comment by F-Lambda** [comment]
To expand on this, I'd like to suggest that the clickboxes can be disabled at any agility course. In the meantime, I just set them to solid black, so they're not as noticeable when training.

**Comment by Felanbird** [comment]
The option to hide the highlights was added to the Agility plugin sometime in the past 6 years
