### ISSUE TITLE
Idle notification - toggle focus request

### ISSUE THREAD

**Issue by ortizdaniel** [runelite/runelite#3208]
Whenever you get a notifcation for idling (no longer fishing, woodcutting, mining, etc), apart from getting the system notification the client **also** comes on top or even switches the current desktop (on macOS).

Please make the latter toggeable, as it's not always wanted to go _instantly_ to the RuneLite client.

**Comment by deathbeam** [comment]
It is toggleable, check "RuneLite" settings

**Comment by Hydrox6** [comment]
RuneLite Settings -> Request Focus on Notification
