### ISSUE TITLE
Add teleport scroll locations to world map

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#3214]
Similar like the jewellery teleports, but then for each teleport scroll. The item sprite can be used for this and would be the most effective way to display it I think.

**Comment by MESLewis** [comment]
[This Google Sheet](https://docs.google.com/spreadsheets/d/1yt2Rdy1fpL_fYcWC4aM_tVrkb1U9pPqzxte8_iNYg04/edit?usp=sharing) has a lot of teleport locations that have been gathered for use in RuneLite.

The second tab has an example of how the data is output for use as an enum.

I'm not interested in putting more icons on the map at this time, but the data is there if someone wants to make a PR

**Comment by shmeeps** [comment]
For the most part, the data just needs added to the `MagicTeleportLocationData` enum? I can check this out a little later.

**Comment by MESLewis** [comment]
I would probably make a new enum that takes an item ID to use for the image. The magic one is designed to support magic level required which wouldn't be needed for teleport scrolls.
