### ISSUE TITLE
Jewellery count - Inventory overlay moves when GE is opened

### ISSUE THREAD

**Issue by Unmoon** [runelite/runelite#322]
1. Have something with charges in your inventory
2. Open Grand Exchange
3. Overlays move towards top-left

Also happens with the rune pouch.
![image](https://user-images.githubusercontent.com/7273082/34596151-24bca90e-f1e6-11e7-83ef-e64c9bae7273.png)

**Comment by bryandh** [comment]
Judging from your screenshot, this might not be specifically related to just the jewellerycount plugin as it seems to also happen to the runepouch plugin's overlay.

**Comment by Sethtroll** [comment]
Seems to be a bug only happening with the side panel UI settings.
