### ISSUE TITLE
Jewellery Box in POH was being force closed

### ISSUE THREAD

**Issue by Spongled** [runelite/runelite#3224]
Possibly to do with Interface Styles being enabled - doesn't seem to be happening after I disabled them.

**Comment by Kamielvf** [comment]
I am unable to replicate this issue.

**Comment by deathbeam** [comment]
I dont think this is related to runelite at all.

**Comment by Spongled** [comment]
Seems like I only encountered this on the singular occasion, must've rectified itself after a client reboot. I agree that this can be closed.
