### ISSUE TITLE
Allow to use Ctrl + scroll to zoom

### ISSUE THREAD

**Issue by mihkelwow** [runelite/runelite#3226]
I can't count how many times I've accidentally zoomed in or out in client when using dual monitor setup and reading/scrolling something on other screen and thinking my mouse was not on RuneLite client.

Can we please have an option to use Ctrl + scroll option to zoom for people like me?

![ctrl scroll](https://user-images.githubusercontent.com/39198864/40496139-b0bace3c-5f81-11e8-93b8-c11de25b0e85.png)

**Comment by MESLewis** [comment]
Duplicated of #1124 , that issue should be used for additional discussion.
