### ISSUE TITLE
Menu bugging out when moving Runelite from one screen to another

### ISSUE THREAD

**Issue by 114167** [runelite/runelite#3229]
I've had this issue for a while, I reported it as a bug before but it seemed to be another issue at the time, when ever I move my Runelite from one screen to another (Additional screen to my laptop screen) it bugs out, either large squares overlay my menu, or the menus just overlay each other, I can temporarily fix it by dragging Runelite from one screen to another, but it'll bug out again instantly if I move my mouse over the menu options.

Some screenshots.
https://i.imgur.com/SU59Sll.jpg
https://i.imgur.com/ei9KEjy.jpg
https://i.imgur.com/kFxEdnl.jpg

Its getting to a level where I can not use any of the runelite menu items on my main screen, and I can only use the menu items on the screen runelite uses to load in. The game itself does not experience any issues, and the features do work if I have them enabled, it's just the menu that bugs out.

**Comment by SoyChai** [comment]
Try this: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by 114167** [comment]
Tried all of the options, when I attempt to disable the hardware acceleration the RuneLite application doesn't' open at all, using the java options also do not open the client.

**Comment by deathbeam** [comment]
This is definitely caused by HW acceleration being enabled.
