### ISSUE TITLE
AntiDragging

### ISSUE THREAD

**Issue by VapingBogan** [runelite/runelite#3241]
Hey first off wanted to let you guys know great job with the client! The only issue i'd like to see (which i heard used to be an option) is if we could possible turn off the shift key needed for anti drag? i use the shift key for a lot of things and I tihnk it would be easier if the option was just enabled or disabled. Sorry my english is not greatest but if you have any questions let me know

**Comment by ypperlig** [comment]
Duplicate of #3200
