### ISSUE TITLE
XP tracker does not display level properly when 99

### ISSUE THREAD

**Issue by berndvdw** [runelite/runelite#3253]
The current XP tracker shows that I'm lvl 74 Farming instead of 99 (got 33M xp). Bug how it processes levels?

**Comment by deathbeam** [comment]
Check your xp goal settings probably, maybe you have set it to 74 base.

**Comment by berndvdw** [comment]
Yes this was the case. Is this intentional behaviour?

**Comment by deathbeam** [comment]
Yeah. But I am going to change the functionality to just show current and next level in case you are already over the goal probably as that is what most people want. But, also, then you will never know to clear that super old goal setting :P

**Comment by deathbeam** [comment]
This was already resolved, closing.
