### ISSUE TITLE
Error connecting to server

### ISSUE THREAD

**Issue by Niittari** [runelite/runelite#3256]
For no apparent reason, cannot connect to the OSRS servers through the client after v1.3.7. It tries to connect me for some seconds, but then just returns the "Error connecting to server" message. Tried uninstalling and reinstalling, did nothing. Official OSRS client connects just fine. Using Windows 10.

**Comment by Niittari** [comment]
I did try that, but for some reason the executable wouldn't even show on the list.

**Comment by iguaan** [comment]
Are you trying to connect to world 373? Some people have been having issues connecting to that specific world, try another one.

**Comment by Niittari** [comment]
Now that you mention it, yes. It's currently pretty late here, but I'll try
logging in to different servers in the morning. Thank you for the help.

pe 25. toukok. 2018 klo 0.18 Iguaan <notifications@github.com> kirjoitti:

**Comment by aedelgod** [comment]
@Iguaan are you still having this issue?

**Comment by Niittari** [comment]
Nope, it's not occurring anymore. The issue was solved by simply trying to
log in to a world other than 373, but it seems that the world is back in
action as well now.

3.6.2018 0.21 "Dillyn Barber" <notifications@github.com> kirjoitti:

@Iguaan <https://github.com/Iguaan> are you still having this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/runelite/runelite/issues/3256#issuecomment-394117994>,
or mute the thread

**Comment by deathbeam** [comment]
Looks like this was jagex-related issue.
