### ISSUE TITLE
Icons on the client aren't showing up but only when i scroll over them

### ISSUE THREAD

**Issue by ShadySus** [runelite/runelite#3258]
I made a post a few days ago having an issue with my client where the icons on the client aren't showing up but only when i scroll over them, and used the link that was posted in my thread. I did what it told me and i still have the same issue and ive deleted and re-downloaded the client multiple times. Is there anything else that i can do to solve this?

![image](https://user-images.githubusercontent.com/39513420/40515597-147fabd6-5f73-11e8-8d44-b44f6b414cc8.png)

Thanks,
ShadySus

**Comment by Gamer1120** [comment]
Join the Discord and use the #support channel.

**Comment by deathbeam** [comment]
What icons?

**Comment by Nightfirecat** [comment]
The sidebar icons

**Comment by deathbeam** [comment]
Probably related to hw accel that needs to be disabled in this case, closing
