### ISSUE TITLE
[Regression] Double-clicking highscore search field no longer looks up your character

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#3259]

**Comment by cricket1650** [comment]
It looks like it still looks up your character if you double click the search icon on the left hand side of the text box. I'm going to assume it worked before by double clicking anywhere?

**Comment by drivfe** [comment]
Yep it used to work anywhere.

**Comment by MESLewis** [comment]
It was changed to prevent double clicking to highlight the text resulting in you looking up yourself
