### ISSUE TITLE
HiScores Static Info

### ISSUE THREAD

**Issue by Moneyman199** [runelite/runelite#3262]
With the new layout of RuneLite, to see the HiScores information, you mouse over the icon, wait a second, and a popup appears for about 5 seconds then disappears. Can we change this to be similar to how it was before the layout change where the information was fixed at the bottom of the plugin?

![image](https://user-images.githubusercontent.com/35946781/40517434-50c3eff2-5f83-11e8-9a6e-242828bcc502.png)

**Comment by permedd** [comment]
Yes!!
 i agree!!!

**Comment by deathbeam** [comment]
We agreed on the new design in discord and I dont think it is going to change. The reasoning behind tooltip is that without box on bottom we have a lot more space where we can put hiscore boxes without adding scrollbar
