### ISSUE TITLE
Barrows Minimap Colour-Blind Friendly

### ISSUE THREAD

**Issue by Winchh** [runelite/runelite#3268]
When in the tunnels at Barrows, the doors that are open-able are currently green squares (I think). However, I am colour-blind and it is really hard to distinguish from all of the yellow dots on the mini-map.

If there is any way to change the colour of the squares that are representing the doors, to something a little easier to see, it would make barrows a little more convenient for the colour-blind.

Thanks!

**Comment by deathbeam** [comment]
Duplicate of #2941
