### ISSUE TITLE
where is the anti drag config toggle?

### ISSUE THREAD

**Issue by bowplox** [runelite/runelite#3269]
![screenshot_3](https://user-images.githubusercontent.com/39606562/40520127-4282ab90-5fc4-11e8-81ad-bd18a918f120.png)
where did this toggle option go?

**Comment by Nightfirecat** [comment]
Removed in #3073.

**Comment by Infinitay** [comment]
As we said in discord when you asked, it got removed. You now **have** to hold shift, there is no more toggle. See #3200 for discussion.

**Comment by bowplox** [comment]
so now I have to turn off shift click dropping :'(

**Comment by Kamielvf** [comment]
You can set shift-click configs for items: https://puu.sh/zVEcD/aff42db5c7.gif

**Comment by bowplox** [comment]
where do I do that

**Comment by deathbeam** [comment]
Duplicate of #3200
