### ISSUE TITLE
Suggestion: Multiple panes for the side panel; view multiple sections at once

### ISSUE THREAD

**Issue by SeanAvak** [runelite/runelite#3277]
I can see this becoming useful in the future, with the suggestion of timers being implemented; what if the side panel had the ability to be split into multiple areas? For example, the top half of the panel could be dedicated to timers, and the bottom half could be dedicated to experience rates, or vice versa.

This could extend into any combination of the panels, GE and News, Farming and Skill Calculator, I can imagine a few possibilities where a feature like this would be massively beneficial to players. Perhaps to the extent where the panes are re-sizable, allowing you to scroll through a smaller news feed, while maintaining experience view?

**Comment by deathbeam** [comment]
I don't think "massivelly benefical" applies and adding this is not realistic because it would most likely break our panels and sidebar.
