### ISSUE TITLE
Do not show (or move) Mouse Tooltips for dungeons on the World Map

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#3278]
Mouse tooltips when hovering over a dungeon sign overlay tooltips from the vanilla client.
I think that one of these should be moved/removed.
![Image](https://i.imgur.com/Qnrprss.png)

**Comment by deathbeam** [comment]
As a workaround you can disable the interface tooltips in Mouse Tooltips settings for now

**Comment by mercster** [comment]
I just turned off "Mouse Tooltips" and the World Map tooltip for "Open Map" on dungeons still pops up.

**Comment by deathbeam** [comment]
Hmm, world map might work differently then
