### ISSUE TITLE
Farming plugin confusion

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#3282]
![image](https://user-images.githubusercontent.com/38350898/40529591-47ab4b56-5ffe-11e8-9745-6658983e6a12.png)

As you can see, I just planted the seed. But on the right it says "Done in (x)h (xx)m" and the green bar under it.

So, please change the following @psikoi;
- Green if it's fully grown
- Yellow if it's currently growing
- Red if it's empty

**Comment by psikoi** [comment]
The colors were not my decision, currently, as the original dev @abex made it, it is:

Red for dead
Orange for diseased
Green for healthy

Percentage on the bar has no relation to the color

**Comment by Floukru** [comment]
Alright you said it, he's missing just the yellow bar. @Abextm 
Red - dead
yellow - growing
orange - sick/diseased
green - grown

**Comment by kulershk** [comment]
For dead, diseased.... just make icon changed, like when its dead just recolor herb to dark or diseased recolor herb icon yellow or something

**Comment by Abextm** [comment]
The reason its green is because green is "OK". As there is nothing to do to "fix" the patch it should not show a warning/error color. Additionally yellow is similar enough to orange that it would be mistakable on first glance. That being said, I would like to see more contrast between an empty progress bar and a full one.

**Comment by deathbeam** [comment]
Is this still issue? Or anything. The title of the issue is horrible, and I don't have any in-progress plants to check the difference

**Comment by Abextm** [comment]
As I stated in my comment I think implementing this is incorrect
