### ISSUE TITLE
Screen Marker Anchoring

### ISSUE THREAD

**Issue by Hampo** [runelite/runelite#3283]
Could screen markers be updated to allow anchoring, which would then work for when the client is resized after creation? Default would be Top Left, but it could allow any combination of Top, Right, Bottom, Left, and would reposition/resize as configured.

Example of use would be when you're marking your inventory, but sometimes have the client bigger than others, but still want to mark the same spot in your invent. Anchoring to Bottom Right would position it there no matter what the client size.

**Comment by deathbeam** [comment]
#3784 would be better solution to this I guess
