### ISSUE TITLE
Runelite sidepanel is buggy

### ISSUE THREAD

**Issue by fliffo** [runelite/runelite#3285]
So i just started using runelite and had to go back to osb. The sidepanel gets really messy if i hover my mouse over it. It starts to lag, flicker and duplicate stuff on the screen. What could be wrong?
Im using Windows 8. 1920x1080. 
![runelite](https://user-images.githubusercontent.com/39618481/40536438-655b4a30-600c-11e8-84d0-b4533bc5b0a2.jpg)

**Comment by Juzzed** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
