### ISSUE TITLE
[Farming plugin] When the crops is growing, make the bar yellow

### ISSUE THREAD

**Issue by Drakur** [runelite/runelite#3288]
During a farm run I tend to forget which patches I already went to. I then check in the farming tab where I should still visit but because the bar for a growing patch and a full grown patch both are green, it's easy to be mistaken. I know it says "Done at xx:xx" for a growing patch and just "Done" for a fully grown patch, but for some reason your brain finds it easier to look at the colored bars. Is it possible to change the color of the bar to yellow (or something else, just not green/red) to make the difference more clear? Thanks in advance.

**Comment by Floukru** [comment]
Here #3282 been suggested
