### ISSUE TITLE
Menu Entry Swapper's shiftModifier gets stuck when window loses focus

### ISSUE THREAD

**Issue by xaviergmail** [runelite/runelite#3289]
A very simple way to reproduce is to alt-shift-tab on windows, re-open runelite and see that any customized shift-click options in your inventory are activated even though shift is not depressed. You have to press & release shift for it to go back to normal.

I think we should either ditch the ShiftClickInputListener and instead check inside onMenuEntryAdded --

Or for performance reasons it, might be worthwhile to just set shiftModifier in a MouseMoved event that way it's only triggered once per menu rebuild rather than once per menu entry?

**Comment by Abextm** [comment]
This is an issue in a number of places, including the game's shift down check. It would be nice to centralize all of the modifier keys so they work when focus is lost. The major problem is that this is a form of faking input to an extent. Perhaps we could use the cs2 opcode for forcing shift.
