### ISSUE TITLE
amount of actions needed in calculator not updating after target level selected

### ISSUE THREAD

**Issue by Wiggli** [runelite/runelite#3293]
As per title says ,when I input target experience or target level the amount of actions required for that level dont refresh, I have to unselect and select the item again.
![d56735810e42cc9d2c4e334a4f5e2669](https://user-images.githubusercontent.com/35573717/40542783-ddb2d5c4-6021-11e8-892d-c17a12dc1096.png)
![3dc2c398ef4c5a493f02d822ed7c22db](https://user-images.githubusercontent.com/35573717/40542790-e17808a0-6021-11e8-9519-ad6c0df9b0fc.png)
![ea0e64abaf251f120fe7473fc5689433 1](https://user-images.githubusercontent.com/35573717/40542793-e40b4230-6021-11e8-8d40-a8607a91cb22.png)

**Comment by drivfe** [comment]
There's a PR for this: #3126

**Comment by Nightfirecat** [comment]
@bartoloandre98 Don't close this issue--it will be closed once #3126 (or some other PR) is merged to fix this.

**Comment by bartoloandre98** [comment]
Sorry, thought I'd remove the clutter since there was another one opened,my mistake

**Comment by deathbeam** [comment]
#3126 was merged, so I guess this is resolved
