### ISSUE TITLE
Ground items plugin not working.

### ISSUE THREAD

**Issue by Maniac809** [runelite/runelite#3296]
I downloaded runelite 4 days ago and it worked great for about and hour. I really only want it for the ground items but for some reason it will only show me the High alch value of my drops and not the ge value. It was working for when I first used it but It just stopped for some reason. Also the examine option used to show the item values but that not longer works either. Does anyone know a fix for this or a reason why it keep happening? Thanks.

**Comment by deathbeam** [comment]
Probably API went down or your firewall is blocking it? not sure, but this is not bug for sure.
