### ISSUE TITLE
Ground Item filtering based on stack count.

### ISSUE THREAD

**Issue by Tehterokkar** [runelite/runelite#3302]
Yo.

I'd like to request a feature to be added to the Ground Item Filter -plugin.

I would like the item filter to be able to filter items based on the stack count. 

For example whenever I am killing Kurasks, they drop a stack of 2-3k and 10k coins very often and I want to obviously see those stacks. But whenever I am killing some low level monsters, or monsters which don't drop multiple thousands of coins at once, I still have to see those drops of 5, 30, or 70 coins.

So thus, the idea that you can filter those lower amounts out and only show coin stacks on ground filter when the coins drop is above a value that is user defined, such as 500gp or 1k.

This would be done on the item filter with a line entry such as "Coins<500", meaning Coins stacks below the value of 500 would be hidden.

This special filter should obviously apply to all items, as it would also make Rune drops easier to filter out from example Kalphite workers which drop runes in quantities of 1-10 I would like to be filtered out, but Fire Giants dropping 150 Fire runes I would like to see.

Thanks for the great client!

**Comment by deathbeam** [comment]
You can already use hide < value.

**Comment by Tehterokkar** [comment]
What is the full syntax? Trying x>Coins or Coins<x does not work.

**Comment by deathbeam** [comment]
Its the field Hide < GE value

**Comment by Tehterokkar** [comment]
That is not what I even asked.

**Comment by deathbeam** [comment]
Well, the overall request do not makes much sense when it can be done in better way :D . I have also PR that adds new option to highlight items over value if that helps, but I dont think something like this is useful to implement. Also probably duplicate of another issue.

**Comment by deathbeam** [comment]
Duplicate of #2572

**Comment by Tehterokkar** [comment]
How can it be done in a better way than allowing the user to define per item what amounts should be hidden/shown? More control in the hand of the user is always better.

Just because YOU think it's not useful, doesn't mean it would not be used by those that want a specific item filter list that shows exactly what you want and hides what you want.

**Comment by deathbeam** [comment]
Well, we are not going to add every single one requested feature. You want it? Back it up with some proper use case. Your current use case is already doable with existing config.

**Comment by Tehterokkar** [comment]
So.... If I want to see coin stacks above 1k coins to show only, I would have to set G.E hide limit to 1k.

This would mean that it would hide 150 Fire Rune drops, which I want to see, but adding Fire runes to Highlight list would also make those drops of 1-10 Fire runes show.

Therefore your logic is bullshit.

**Comment by Reasel** [comment]
@Tehterokkar No need to get aggressive here. Deathbeam simply doesn't understand your use cases. What you described is alright, its just hard to visualize why its needed without plenty of examples.

**Comment by Tehterokkar** [comment]
Why it's needed? Because if I'm doing slayer and killing different monsters of vastly varying combat levels and they have similar drops in some cases, but vastly different quantities. 

For example Kurasks drop noted 10-12(or something) Limpwurt roots. These I would pick up and want to show, but I do not care for single un-noted Limpwurt roots that drop from Hill giants or something if I'm doing points boosting.

I don't want useless clutter on my screen and I want the filter to only show what I want to pick up exactly.

**Comment by deathbeam** [comment]
So just toggle for not hiding stacks is enough.

**Comment by Reasel** [comment]
@Tehterokkar I think toggling per item is a bit much. It would be difficult to manage in the UI having either two lists (one for noted and one un-noted) or even just managing per item stack count..

**Comment by Tehterokkar** [comment]
Stop looking at the request for 1 item which I use as an example and responding based on that.

And would it really be? The client already tracks the stack count, so adding a simple syntax at the end of the item name on the item list would suffice, Osbuddy has syntaxes like "Bronze*" which filters every item that starts with Bronze, or "*bolt" which filters every item ending in the word bolt.

**Comment by Kamielvf** [comment]
Wait, you're making a fuzz over a feature which is already implemented? You can already use wildcards for these settings.

**Comment by SomeZer0** [comment]
I think this would be a good way of doing it:

"Show Noted/Stacks of these items (even if on block list)"
[Input Box]
[Optional "Minimum stack requirement to highlight"]

**Comment by Tehterokkar** [comment]
@Kamielvf If such a feature exists, then please share it, because @deathbeam who is marked as Admin on RL discord has no idea of such feature or doesn't understand how more control over filter is good.

**Comment by Kamielvf** [comment]
>adding a simple syntax at the end of the item name on the item list would suffice, Osbuddy has syntaxes like "Bronze*" which filters every item that starts with Bronze, or "*bolt" which filters every item ending in the word bolt.

I'm talking about this, where wildcards already work.

**Comment by Reasel** [comment]
Okay, for 

1. We already have the wildcard feature...You can already do that. 
2. It would be awful to add any syntax at the end of a string. How would say to hide <150 fire runes? Fire Rune<150? Would get messy really fast and hard for the layman to use.

AS @SomeZer0 said sure it makes sense to have a hide under stack amount. Maybe even an additional field, but then again you then have to manage 2 fields just to make things work. Its too much for the user to figure out. Hell Wildcard imports are slipping by people it seems.

**Comment by SomeZer0** [comment]
@Tehterokkar
I don't think anybody will want to make a plugin for you if you're acting rudely to the admins/contributors.
This is basically a hobby for them, so they don't have to cater to anyone.

**Comment by Tehterokkar** [comment]
I don't think Fire Rune<150 is hard to understand, unless you have never taken math lessons past like 3rd grade. And again you seem to have tooltips that come up when you highlight over options in the plugins, just add it to that list.

And since you have the "wildcard" features, those are not mentioned anywhere, so again, how would a regular pleb user know of those in the first place?

You are already contradicting yourself. Adding more "wildcard" features when the existing ones are not mentioned ANYWHERE in the client. So again, why would a regular user get "headache" over this when they wouldn't even know such features exist.

**Comment by Tehterokkar** [comment]
But then again, why can't this be visible on the client when you have the option to add tooltips and such.

@deathbeam Yes I am, but people seem to have this opened. Closed =/= Locked.

**Comment by deathbeam** [comment]
Collect your previous statements in some reply on the original issue then I guess, as this can get easily lost and never looked at.

**Comment by Tehterokkar** [comment]
Because you locked it prematurely when it suited you when you never understood the suggestion in the first place. 🤔

**Comment by deathbeam** [comment]
I closed it as duplicate.

**Comment by Tehterokkar** [comment]
You gave the same reply in the duplicate issue and it is faulty logic for thinking "just have g.e value set to X", that is not how a good item filter list would work, because especially as an Ironman account, the G.E or HA value has no meaning sometimes.

And as I explained earlier with the Fire rune example a few posts up. Setting a G.E filter limit would still not solve my issue of not wanting to see low amounts of Fire runes but wanting to see fire rune stacks above 50.

So you are just making this convenient for you because again you don't understand the suggestion.

**Comment by Simpuhl** [comment]
> I think this would be a good way of doing it:
> 
> "Show Noted/Stacks of these items (even if on block list)" [Input Box] [Optional "Minimum stack requirement to highlight"]

Did you ever add this?

**Comment by king-koda** [comment]
did this feature ever get added? it would be really useful, and I'm not opposed to an end of string syntax that supports operators like >= <= ? was a great idea, that got boldly misunderstood almost immediately and dismissed, to which the OP responded in the same regard, and then got demonised for it 😆

**Comment by riktenx** [comment]
`item<x` works yes

**Comment by king-koda** [comment]
> `item<x` works yes

if this is true, then that is massive, thank you for such a quick response
