### ISSUE TITLE
when marking clue dig sites the northwestern tile is highlighted rather than the center or the entire zone

### ISSUE THREAD

**Issue by duracell33** [runelite/runelite#3308]

**Comment by Nightfirecat** [comment]
The points aren't automatically selected, they are manually entered. If you know of any that need adjusting, please feel free to give examples and we can adjust them to better reflect the actual dig point.

**Comment by duracell33** [comment]
so far only tested the clue west of champs and east of the tree which was the northwestern one, i'll start testing as i go

**Comment by SomeZer0** [comment]
A good one to change, is the one where you dig behind the room with the anvil in Yanille, there is a tile inside the room (quicker to get to) that you can dig on.

**Comment by Nightfirecat** [comment]
Good point, that's one where it's technically advantageous not to dig in the center point.

**Comment by SomeZer0** [comment]
Its a map clue
![Map](https://vignette.wikia.nocookie.net/2007scape/images/f/f2/Map_clue_Yanille_anvil.png)

**Comment by Nightfirecat** [comment]
If there are no other specific examples, it's probably better to close this issue and raise new ones as specific clues with issues are encountered.

**Comment by Nightfirecat** [comment]
As I mentioned now more than a year ago, if any specific clues have problematic locations marked, they can be raised in new issues.
