### ISSUE TITLE
Special Attack Orb is rendering above right-click menu

### ISSUE THREAD

**Issue by XrioBtw** [runelite/runelite#331]
![specorb_rendering_ontop](https://user-images.githubusercontent.com/33559295/34651602-b541cd72-f3d2-11e7-9b4a-23ff76139fa1.png)

**Comment by deathbeam** [comment]
This applies for all overlays, I don't think this can be solved without somehow adding hook to render stuff before (so under) rs interface is rendered.

**Comment by deathbeam** [comment]
Solved in #372
