### ISSUE TITLE
Client triggers a windows sound

### ISSUE THREAD

**Issue by Hp-x-Hp** [runelite/runelite#3321]
So I've just started using RuneLite and sometimes I get a windows sound playing as if I was trying to delete text in a field without text (also the sound it plays when I run out of prayer). I think it might have something to do with the idle alerts, the only idle alerts I have turned on is for prayer and it's set to 1 prayer point, but the sound comes at different states of my prayer.

Thanks for reading

**Comment by sethtroll** [comment]
Do you have the "Configures if idle animation notifications are enabled" option in the idle notifier turned off?

**Comment by Hp-x-Hp** [comment]
Yes, I have turned what seems to all notifiers off apart from prayer (I'm in NMZ and have also turned off the powerups/OVL/absorp etc.)

**Comment by sethtroll** [comment]
can you take a picture of your idle notifier configs and put them here?

**Comment by Hp-x-Hp** [comment]
https://gyazo.com/02284cd809ac7d5f761b752f9dde9a18 https://gyazo.com/218ef55a8f7330b7e2ab5aa78a0fdd0c

**Comment by Hp-x-Hp** [comment]
Okay I just tried to trigger it, I prayed up to 99, minimized the client and didn't touch my mouse at all, at 64 prayer the sound played im using Superhuman str (10% str pray) and my pray bonus is 10 if that helps at all (could be the 5min idle? ill test the how long it takes this time)

**Comment by Hp-x-Hp** [comment]
4 minutes and 45 seconds for the alert ill now try with client focused

**Comment by Hp-x-Hp** [comment]
4 minutes and 40 seconds with client focused (still no mouse-movement) gonna try when I move my mouse around

**Comment by sethtroll** [comment]
There is a idle logout notifer which fires every 4 minutes and 40 seconds like you have stated. Unfortunately there is no way to turn those off unless you disable the idle notifier plugin.

**Comment by Hp-x-Hp** [comment]
Ehm okay, so that would be a suggestion to a future feature "Disable when in combat" or what? :)

**Comment by sethtroll** [comment]
yeah, if you want to rename this issue and description that would be nice

**Comment by Hp-x-Hp** [comment]
Thanks for helping ill do that now :)
