### ISSUE TITLE
Logout notifier toggle

### ISSUE THREAD

**Issue by Hp-x-Hp** [runelite/runelite#3322]
So I've had problems while afking in NMZ when I haven't interacted with the game for 4mins and 40 seconds the "log out notifier" or whatever it is fires. Apparently you have to disable idle notifiers to turn it off, so there's not really any button or feature to only disable that. (also it would be great if it could register that you were in combat so it wouldn't play when you're actually not becoming logged out in 20secs.

Suggestion / TLDR:

Option to choose whether or not you wan't the 5 min idle/log out notification

**Comment by Hp-x-Hp** [comment]
How do I lable it? BIG L

**Comment by permedd** [comment]
Yeah i totally support this i even done a post about this but something similar that is this https://github.com/runelite/runelite/issues/996 
But i agree mate.

**Comment by deathbeam** [comment]
Fixed in #5222
