### ISSUE TITLE
Xeric's Talisman Teleport Locations not on World Map

### ISSUE THREAD

**Issue by trini0n** [runelite/runelite#3324]
With the recent addition of showing teleport locations on the world map, I've noticed the locations for the Xeric's Talisman isn't shown.

e.g.
![](https://i.imgur.com/1u7daep.png) Xeric's Look-out
![](https://i.imgur.com/Bd6gdMP.png) Xeric's Glade
![](https://i.imgur.com/zFKLMQm.png) Xeric's Inferno
![](https://i.imgur.com/fz62BLY.png) Xeric's Heart

**[Insert Xeric's Honour teleport here because I don't have it]**

**Comment by iguaan** [comment]
This is still a work in progress, these teleports are known and will be probably added later. Full list: https://docs.google.com/spreadsheets/d/1yt2Rdy1fpL_fYcWC4aM_tVrkb1U9pPqzxte8_iNYg04/edit#gid=0

**Comment by Adam-** [comment]
Added in #3391
