### ISSUE TITLE
Client lags significantly when playing another high CPU / RAM usage game. Lags until reset.

### ISSUE THREAD

**Issue by RevenantWendigo** [runelite/runelite#3327]
I played Overwatch while afking crabs and my client would stay at 20FPS instead of the usual 50FPS. Closing Overwatch did not fix the problem. Closing and reopening my client did fix the issue (FPS went back to constant 50FPS)

Java: 1.8.0_161
GPU: GTX 1080
CPU; i7-2700k @ 3.5 GHz

If you need any other info let me know. Thank you.

**Comment by deathbeam** [comment]
What if you try https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by deathbeam** [comment]
As this is quite old and no more info was provided, closing. Reopen if issue persists
