### ISSUE TITLE
Add OpenGL (Or something Similar) to combat NPC Flickering

### ISSUE THREAD

**Issue by bromagic** [runelite/runelite#3331]
NPC's such as Ardy Knights can flicker when more than one person fails thieving it at a time. This issue has been fixed with the addition of OpenGL mode on osbuddy, and I would like to see a solution on runelite. I'm not sure what other options could be looked into in order to fix this issue, but hopefully there are some out there.

**Comment by iVilux** [comment]
Have you tried using entity hider at ardy knights?

**Comment by Adam-** [comment]
"opengl" is unrelated to the npc flickering which is a behavior of the renderer. We think that the flickering can be resolved by using the entity hider to hide other players. It sounds like what is happening is the engine is prioritizing the other players over the npc - and we recent merged a fix into the entity hider to deal with this (#5445).
