### ISSUE TITLE
Obsidian Client redesign issues

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#3333]
Noticed since the update some stuff has dissapeared (dunno if some of it was intentional or not)

-Double click on highscores doesnt search your name
-No button for skill tracker site or reset all in skill tracker (i know you can currently right click to reset but having a left click option is good too)
-Left click on the individual skill icons doesnt reset the skill in skill tracker (by icon i mean saw for construction, sword for attack, tree for woodcutt etc)

Just some things ive noticed so far

**Comment by Abextm** [comment]
- You can double click on the search icon to autofill your own name
 - You can access the online tracker by right clicking
 - You can reset all by right clicking the header
 - You can reset an individual skill with a right click, the previous behavior of clicking on the icon was confusing for many people
 - Putting multiple issues in 1 bug report makes it difficult for us to track issues. In the future please separate multiple bugs into multiple issues

**Comment by Stickaplex** [comment]
Why were the left click options removed then? Cause iirc we had both the left click buttons and right clicks

**Comment by Abextm** [comment]
They were removed because they were confusing, and people often clicked on them accidentally because they didn't show what they were supposed to do. If you want a left click option, I would recommend that you open a new issue specifically for that.
