### ISSUE TITLE
Macbook High CPU Usage 

### ISSUE THREAD

**Issue by Misclique** [runelite/runelite#3335]
Client spikes to 99% CPU usage under normal use, which is causing considerable lag and the game itself seems slightly out of focus/blurry, while web browsing, etc is fine. Prior to the 1.4 update CPU seemed fine and there was no blurry issue. CPU ran at 59-61 degrees celsius and now runs about 70-71 degrees. 

This happened at the GE while fletching. Computer specs are: 
Early 2015 MBP
2.7 GHz Intel Core i5
8 GB 1867 MHz DDR3

Couldn't replicate this on my Windows PC.

**Comment by LeviSchuck** [comment]
@Misclique what plugins do you have enabled, what region are you at?

In the mean time, try the FPS plugin to force it to render at a lower rate, if setting it to 10 reduces the CPU dramatically, then we may have a clue as to where the problem is.

**Comment by Misclique** [comment]
@LeviSchuck Sorry, it was the stretched fixed mode. I guess even though the client wasn't stretched it was giving my computer hell. I should've guessed that since the screen looked like it does when you're in stretched mode and have taken up the whole monitor. 

Sorry for not troubleshooting this a little better before coming here and thank you for replying.

**Comment by DougSteiert** [comment]
I would like to re-open this. My specs are older - 2012 MacBook Pro. 
2.3 Ghz i7
16 GB RAM
NVIDIA GeForce GT 650M 1 GB
Intel HD Graphics 4000 1536 MB

I am having pretty bad lag. Every so many steps the screen like halts/stutters and catches up. I do not have it in stretched mode, and I tried the FPS plugin mentioned, set it to 25/18/10 - at 10 it definitely was worse lag, much less playable. 18 FPS didn't notice a difference from 25 nor from without using the plugin.
