### ISSUE TITLE
Side bar grahpical issue

### ISSUE THREAD

**Issue by ChandlerFord** [runelite/runelite#3336]
The side bar will start to become glichy after short use, the only temporary fix is to click another application, but as soon as the mouse hovers or clicks on any of the sidebar items the glitch returns.

Gif of the glitch:
https://gyazo.com/2715b72aa7d1ed7a035fedb2f94f7009

**Comment by SoyChai** [comment]
Try this: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by ChandlerFord** [comment]
That seemed to have fixed it, thank you!
