### ISSUE TITLE
Highscores lost some functionality after recent update.

### ISSUE THREAD

**Issue by The-Onceler** [runelite/runelite#3339]
Hello, just wanted to let you guys know that after the recent update/reskin for Runelite the highscores no longer allow you to double-click on the search box to look up the account your're currently playing on.

On top of this you also used to be able to hover over your total level and it would display some extra information about the account (for example, it's overall rank), but unfortunately that no longer works either.

I used both of these functions quite often and would really love to see them come back. 

Thanks!

**Comment by Abextm** [comment]
- You can double click on the search icon to autofill your own name
 - Hovering over total level should show your overall Rank and XP, reopen if this doesn't work for you 
 - Putting multiple issues in 1 bug report makes it difficult for us to track issues. In the future please separate multiple bugs into multiple issues
