### ISSUE TITLE
A right click option to only reset XP/H while keeping XP Gained

### ISSUE THREAD

**Issue by iVilux** [runelite/runelite#3344]

**Comment by psikoi** [comment]
@LeviSchuck

**Comment by deathbeam** [comment]
Uuuh, that do not makes much sense tbh.

**Comment by psikoi** [comment]
Kinda does, I like seeing big numbers on Exp gained but i also like to know my exp rates even if I have to take a break, not high priority at all, but nice

**Comment by iVilux** [comment]
I want to see the total how much XP I've gotten throughout the session, but XP/H decreases if I go AFK or do something else.

**Comment by LeviSchuck** [comment]
@iVilux I think I have a PR that will address your concern: #4114

**Comment by Nightfirecat** [comment]
Duplicate of #3413.
