### ISSUE TITLE
Entity hider issue!!

### ISSUE THREAD

**Issue by RiskAGS** [runelite/runelite#3346]
I would like to only 'hide' my friends instead of hiding everyone else. Is there a way to do this without hiding everyone but people on the friend's list? Thanks! PS: I know that you can only have your friend's "visible" once 'hide players' option is on.
![entity hider](https://user-images.githubusercontent.com/39632018/40578151-cea145d6-6141-11e8-89ee-96157d097dc3.PNG)

**Comment by Kamielvf** [comment]
You need to toggle "hide players" for the entity hider to work. It was made this way to balance it out for PvP situations, where for example, you would hide your friends/clan and only see your opponents.

**Comment by RiskAGS** [comment]
Yes, i know what to toggle. But there are other things I want to use this feature for.

**Comment by devLotto** [comment]
You will not be able to do this.
