### ISSUE TITLE
Hide Ignored Players (Hide Entity)

### ISSUE THREAD

**Issue by RiskAGS** [runelite/runelite#3349]
I was wondering if it is possible if the client could hide ignored players completely without having to hide other players around me. It would help with hiding players such as:
- Bots
- Scammers
- Lurers

Thanks.

**Comment by deathbeam** [comment]
No, that can be abused so we dont want to add that I think

**Comment by Kamielvf** [comment]
No reason to open a new issue when the older one was closed with valid reasoning. Same applies.

#3346

**Comment by RiskAGS** [comment]
This is a different issue, why would hiding ignored players be abused?

**Comment by devLotto** [comment]
Because you could add your clanmates to your ignore list.

**Comment by deathbeam** [comment]
You could just add people from CC to ignore in team fights so they will be hidden and you wont missclick, so, yeah.

**Comment by JZomerlei** [comment]
@deathbeam I am trying to create this plugin for my own personal use. For the exact reason of the poster here. There is a series of perm logged in level 3s in f2p over top of the barbarian village forever fire. 

I have a lot of the headway done but I don't understand some of this project... I am a software developer (Java mostly) by trade and even in coursework interfaces/the like have confused me. 

I don't want to create a new plugin entry which would solve this. I want to extend off of the hide ignored player, it would look cleaner that way. 

also the reasoning of: 'Add players from CC to ignore' is a bit silly, as you can already hide clan chat friends & you can also hide regular friends. 

I am unsure if you can private message people on github or not, I use vsts in my work life. I would appreciate it if you could help.

**Comment by m4chinations** [comment]
This needs to be re-opened, or someone needs to update the reasoning behind the wontfix. The original reason was given that you could hide CC members, but this exact functionality was introduced directly with 6c21b2e.

**Comment by Adam-** [comment]
I think that currently you can still not hide ignored players, which I believe is an intentional decision, so it makes sense that this is marked wontfix? And also we think that that commit did not introduce the ability to hide only ignored players.

**Comment by m4chinations** [comment]
I misunderstood the current functionality - the current toggle is for "unhiding" friends chat members (not hiding them, like the name suggestions). 

I think, there is some compromise on the issue that can be made, as it has some valid use cases (hiding abusers/scammers/spammers, etc), we can disable the "hide ignored" toggle in PvP scenarios as to prevent the initial concern of abuse.

**Comment by Adam-** [comment]
This has been revisited now and will allow hiding of ignored players outside of pvp zones
