### ISSUE TITLE
Changing name of Sceptre teleports

### ISSUE THREAD

**Issue by daanzii** [runelite/runelite#3354]
Would it be possible to change the name of the Pharaoh's sceptre's teleports to something a bit more friendly, I can never remember which one is which, Not sure if it's even possible 

 Jalsavrah  > Sophanem (Pyramid Plunder) 
Jaleustrophos > Agility Pyramid
Jaldraocht - Azzanadra's pyramid (Ancient Magicks)

Thanks

**Comment by Malfuryent** [comment]
https://gyazo.com/50b9ad1c487e2b840a989f27b7aafa35
I'm also going to change names of wilderness teleports to be more understandable or any other teleports which are not very clear

**Comment by 3mptylord** [comment]
Xeric's Talisman nicknames would be nice, too.

**Comment by SandroVA** [comment]
Was this finished an never pushed? @Malfuryent I can't find renaming anywhere in runelite currently.

**Comment by Nightfirecat** [comment]
The [Easy Pharaoh Sceptre plugin](https://runelite.net/plugin-hub/show/easy-pharaoh-sceptre) on the hub renames the dialog options. I'm sure they'd be willing to add renaming for the worn options as well if asked.
