### ISSUE TITLE
Timers still overlayed after leaving NMZ

### ISSUE THREAD

**Issue by twoodward1** [runelite/runelite#3355]
Disconnected in NMZ and the overlays for the Overload were still on my screen as seen in picture
![image](https://user-images.githubusercontent.com/34960782/40578961-7a3322ca-6115-11e8-8a51-7ef3a1fa2c7d.png)
Edit: I just left the NMZ instance **without** disconnecting and the Overload timer still appears on my screen.

**Comment by deathbeam** [comment]
Duplicate of #4773
