### ISSUE TITLE
Request: Allow for a modifier key to be required for Zoom.

### ISSUE THREAD

**Issue by Dumbdragon** [runelite/runelite#3358]
As title says. I use a Logitech mouse whose scroll wheel either allows for frictionless scrolling, or for "friction" (EG, clicking/resistance each time you scroll a tick). 
I have always played with frictionless, but it becomes very annoying on Runelite, as occasionally I'll bump the button and it moves the zoom. 

Turning the option to zoom off isn't viable, as that will reset my zoom to "normal" game standards if I ever touch the wheel (as I play zoomed further out with the "expand outer zoom limit" option). 

Wasn't an issue on OSbuddy because OSB requires you to hold alt when scrolling to modify the window. Hoping something similar can get implemented.

**Comment by deathbeam** [comment]
Duplicate
