### ISSUE TITLE
Elite clue minor bug

### ISSUE THREAD

**Issue by Tolvinas** [runelite/runelite#3361]
Elite clue: "I live in a deserted crack collecting soles".

Solution: Enter the crack west of nardah rug merchant and talk to the genie.

BUT to enter that crack you need light source and a rope, so its only a minor bug. Its not saying that

**Comment by Nightfirecat** [comment]
Fixed in https://github.com/runelite/runelite/commit/1b84f97b0bc5a65dfd0ee16db259feed0cdfc12b, @deathbeam close this now?

**Comment by whartd** [comment]
Can we have the kind of interface that spade req clues have, where it shows up in red if you have no light source / rope?
