### ISSUE TITLE
Put RuneLite into a Snap for Linux

### ISSUE THREAD

**Issue by AlexHurd11** [runelite/runelite#3370]
I was wondering if putting RuneLite into a Snap on Linux would be possible/worth the time. I know personally I use snaps a lot due to just wanting things to work and not having to worry about it. I'm not sure if putting RuneLite into a snap would make things easier for Linux users. I was wondering if this could also get rid of the hardware acceleration issue most people have on Linux too. I have no real idea how the client works, just a thought that came to me the other day.

Thanks!

**Comment by TzZek** [comment]
This could be nifty, I believe I've seen RuneLite on the AUR but I'm not sure it's by an "official" developer.

**Comment by aedelgod** [comment]
I have mixed feelings about this. If someone put it in a snap, etc. it _could_ be on an update channel that would always be behind (doesn't have to be though). I like just having the jar file and making my own .desktop file for it as a launcher. However, an official snap would be needed for those new to linux or someone could load in a "malicious" one if it's not an official snap to protect the newcomers. This project is on git (obviously) so maybe there just needs to be the "so simple a caveman can do it" git clone instruction or a simple shell script in the releases tree.

**Comment by TzZek** [comment]
Why not just use the .jar on Linux Henry?

**Comment by AlexHurd11** [comment]
My whole idea behind this was to make it easier for those who want to switch from Windows or Mac but don't want to learn the command line. Not everyone who wants to use Linux wants to be a power user. GitHub for someone who just wants to play their favorite game and has no development experience can be confusing. Wine can be pretty daunting to a new Linux user and now with Steam having Proton, not as many new users may find a reason to use Wine. I feel like continuing to make it easier for those who want to come to the Linux desktop is the right decision in every way possible. On the security note, Snaps can be verified by Canonnical in the snapstore, similarly to Twitter to help keep people from downloading a malicious version. 

That's just a couple of my thoughts. I have plenty more :)

**Comment by HenryR-226** [comment]
I'm happy to QA check whatever builds are made or provide documentation, I
have access to varying PC hardware performance quality levels, but I don't
have the expertise to even attempt a Linux build of anything at this point,
unfortunately.

WINE gives me problems, particularly with graphics, so a Linux build would
be sweet. That plus losing the performance overhead.

**Comment by TzZek** [comment]
@HenryR-226 , sorry was just curious why you run in through Wine , instead of installing the JRE and than just downloading the .jar and running it that way with. java -jar RuneLite.jar --mode=OFF

**Comment by HenryR-226** [comment]
Didn't know that was an option, very new to Linux. Reading up on the
philosophy of Java it does seem this is what the developers of the language
intended.
Thanks for the tip, I'll give it a try soon.

**Comment by TzZek** [comment]
@AlexHurd11 I'm aware of the original reasoning of this thread, I'm just trying to figure out why you'd setup Wine for RuneLite when it already has Linux support. I'm aware that installing a Snap or straight from the AUR could make it easier, I was just curious of his reasoning which he has now stated above.

**Comment by deathbeam** [comment]
This should be reopened in https://github.com/runelite/launcher so please do that, closing this issue
