### ISSUE TITLE
Client Crashing

### ISSUE THREAD

**Issue by Axelnoob** [runelite/runelite#3374]
Just downloaded the client to try for the first time. If I try to resize or click any of the buttons on the client it crashes. Tried to reinstall it and it did not work. 

If anyone has any suggestions please let me know! Thanks!

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration did you treid this?

**Comment by deathbeam** [comment]
I will just close this now as no more informations were provided and we have enough crash bugs open already
