### ISSUE TITLE
NMZ new notification

### ISSUE THREAD

**Issue by cluerangers** [runelite/runelite#3381]
I have a suggestion for nmz: add notification when your hp is close to regen to 2 so you can use rapid heal and stick to 1
rapid heal the prayer restore your regeneration
so you don t have to use rock cake
For example you can look away from the screen and when you hear the sound you click rapid heal and your regen restores

**Comment by akump** [comment]
Hi. I'm currently looking into adding this feature to the RegenMeter plugin!

**Comment by Gamer1120** [comment]
I'm pretty sure this might be a duplicate.

**Comment by RickertdeH** [comment]
Maybe also a notification when your boosts are running out (not just absorption)

**Comment by ThatGamerBlue** [comment]
Duplicate of #2704 but I support the suggestion.
