### ISSUE TITLE
Timestamps on chat-box messages

### ISSUE THREAD

**Issue by twoodward1** [runelite/runelite#3382]
Similar to the RS3 chatlog:
![image](https://user-images.githubusercontent.com/34960782/40586462-43501bfa-61ba-11e8-8034-07fe1bcd03b5.png)
This should be toggle-able.

**Comment by CasvanDongen** [comment]
![example](https://i.imgur.com/SaehK33.png)

I'm currently working on this. I'll create a PR later when I've cleaned up the code, tested it and have unit-tests.

**Comment by 2yangk23** [comment]
Are you still working on this?
