### ISSUE TITLE
XP Tracker - Range

### ISSUE THREAD

**Issue by SorceryOfFishy** [runelite/runelite#3389]
XP Tracker for range says "Lvl. 5 <percentage> <next Lvl.>"  (Next level is not 6 and is stuck saying that even when level is achieved.
![image](https://user-images.githubusercontent.com/24929142/40589540-e8cf699c-61e6-11e8-8fff-2ba60c394a97.png)

**Comment by deathbeam** [comment]
Check your goal settings in vanilla client. This is correct behaviour.
