### ISSUE TITLE
ape atoll elite clue not showing

### ISSUE THREAD

**Issue by qelprs** [runelite/runelite#3392]
not sure if this hasn't been added or not, but the elite clue step where you search the crate in the shack on the southwest shore of ape atoll doesn't highlight the crate. [screenshot](https://imgur.com/qmT82rI)

**Comment by Nightfirecat** [comment]
[Is this the map clue you're referring to?](https://vignette.wikia.nocookie.net/2007scape/images/6/68/Map_clue_ape_atoll_shack.png/revision/latest?cb=20160716050227) If so, the world point is `2703, 2716, 0` and the object id is `6616`, but I don't know the map clue ID... It looks like this clue has never been added before.

If you (or somebody else) happen to get this clue step again, please reach out to the #development channel in Discord for help on finding the item ID in your inventory--with that, we can add this clue.

**Comment by deathbeam** [comment]
Fixed in #3777
