### ISSUE TITLE
Multiple coloured ground markers

### ISSUE THREAD

**Issue by Allemaalbaas** [runelite/runelite#3395]
Hi, I want to suggest multiple coloured ground tiles. How it would work is that you have a slider or checkbox to choose of you want to change all ground tiles to this colour or just one. This way a ground tile  would automatically be another colour if you change the colour (with the colour picker). If you would slide or check the box it would change all the tiles to the chosen colour.

**Comment by ElevatedLife** [comment]
Lots of support for this feature.

https://github.com/runelite/runelite/issues/5812#issue-366864846
https://github.com/runelite/runelite/issues/5187
https://github.com/runelite/runelite/issues/4242

**Comment by Adam-** [comment]
Reopening as the merged PR could not stabilize prior to release.

**Comment by eggbrow** [comment]
> I'm starting work on this, but it'll probably be a little while before I have this ready for review.
How likely is it that there'll be support for different-coloured unique object markers and npc indicators?
