### ISSUE TITLE
#3376 closed as duplicate but linked post is different 

### ISSUE THREAD

**Issue by duracell33** [runelite/runelite#3399]
#3376

**Comment by Abextm** [comment]
You can reopen #3376 if you want, but its still a duplicate of #3289, they are both about shift not working when loosing focus.

**Comment by duracell33** [comment]
but im not swaping or losing focus at any point

**Comment by duracell33** [comment]
i never had this issue with osbuddy and it seems to be more related to the screen flash, like it only stops registering at the start/end of the flashing

**Comment by Abextm** [comment]
If you turn off screen flashing does it stop happening?

**Comment by duracell33** [comment]
i had forgot that was in the runelite settings tbh, still happens, noticed same happens when navigating and changing options on the settings tab is that know?

**Comment by Abextm** [comment]
Yes, any interaction outside of the gameframe in subject to the bug/lack of feature mentioned in #3289
