### ISSUE TITLE
Screen Marker teleporting

### ISSUE THREAD

**Issue by Miickey564** [runelite/runelite#3402]
When you teleport after placing screen markers, they bunch together to the first marker created

example:

before: https://i.imgur.com/mTPxNxT.png

after: https://i.imgur.com/H7UixSk.png

happens weather gameframe is on or off

**Comment by Kamielvf** [comment]
I cannot seem to replicate this issue. Is this possibly related to #3240?

**Comment by deathbeam** [comment]
I dont think this is issue anymore
