### ISSUE TITLE
Have imbued heart overlay always be on if in inventory

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#3408]
Make imbued heart overlay always be on, even if the timer runs out. Was thinking to have it turn green if its ready to use and red if its not. Probably leave time at 0:00 (maybe?)

Sometimes you dont necessarily notice it when ur doing stuff

**Comment by matthewpetch** [comment]
Surely by it not being on screen you know it's available though? It would be inconsistent with everything else (like potions). Can you imagine if antifire potion timers stayed on screen if they were in your inventory when they ran out? Most people would just assume they were still potted

**Comment by Stickaplex** [comment]
Its more of an in-your-face type of warning if your not paying attention to much. antifire and things of that nature are different because its all of a sudden your taking a bunch of damage, but heart is just a stat boost so you tend not to notice it as much (or at least i dont) and the message can get lost quite easy in the chat.

while the timer itself does help you prepare to boost it, it can be easy to get a bit distracted and not notice it go off. 

just because it works now doesnt mean it cant be improved a bit more.

**Comment by deathbeam** [comment]
There is better request to solve this and that is give warnings when your stat boost goes under specified value. This request is way too specific imo, and do not really work well with the timer system we have in place.

**Comment by deathbeam** [comment]
The boost notifications was implemented so this should be solved I guess
