### ISSUE TITLE
Runelite Submenu Options Bug

### ISSUE THREAD

**Issue by TheRealBertyz** [runelite/runelite#3411]
Runelite Version: 1.4.0
GeForce Driver Version: 397.93
Hardware: ASUS ROG Zephyrus GX501 15.6” Full-HD 120Hz Ultra-portable Gaming Laptop, GTX 1080, Intel Core i7, 512GB PCIe SSD, 16GB DDR4

Bug: 
Currently when hovering over the submenu options it causes the submenu options to bug out.  

Debugging: 
Re-downloaded Runelite client version from the website.
Re-downloaded GeForce drivers. 

Current Solution: 
Minimizing the client and re-opening will reset the submenu options 

Example: 
https://gyazo.com/c587e0b8e9cb8d77f24c52eaf2dc807b

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by TheRealBertyz** [comment]
Thank you! 💯
