### ISSUE TITLE
Reset xp/hr but nothing else

### ISSUE THREAD

**Issue by StealthyJet** [runelite/runelite#3413]
Would it be possible to be able to reset only the xp/hr in a skill, but not the other data? Like the total xp gained, or in some skills the amount of resources gained?

**Comment by HarryOMalley** [comment]
It would probably be nice if we could set the XP/Hr to reset after x minutes, i.e only calculate it from the last 5 minutes of data.

**Comment by LeviSchuck** [comment]
@StealthyJet 
The totals are collected from all the individual skills, so with the current implementation, that is not possible.

@HarryOMalley 
This would be a separate feature, it could be implemented, but check out the pause PR that I just made, refer to #4114

**Comment by Nightfirecat** [comment]
Added in 8a5a0f88f966d550ab1548d8e345b33d90ef52d8
