### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#3422]
My RuneLite goes white if I Windows + L or (I think) open fullscreen games (did not receive any answer from anyone after asking thrice on Discord)

**Comment by stevenoctopus** [comment]
I just received this on Windows when a program was asking for administrator rights and the popup window hid and dimmed my screens.

**Comment by sedmicha** [comment]
I just encountered this issue after returning from lock screen on Windows 10 while having RuneLite in stretched fixed mode

**Comment by Popedigoz** [comment]
Yeah, I forgot to mention I am also playing RuneLite with fixed stretched mode, (fullscreen) 'Keep aspect ratio' is ticked if it counts.

**Comment by thgonzalez** [comment]
Same as everyone here.

**Comment by Y2Grs** [comment]
For a temporary fix you can disable "Stretched Fixed Mode" and the screen should reappear and then you can just enable the plugin again and you should be fine... Its a little annoying having to do this but hey it might save you some gear if this happens to you while you're in the wild or something

**Comment by deathbeam** [comment]
Looks like this is solveable by disabling hardware acceleration: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by DankSteelMemes** [comment]
Still happens even with that flag there and HW acceleration disabled. 

Disabling Stretch mode like advised does fix the issue but enabling it brings the white screen right back. Unfortunate this won't be fixed...

**Comment by khogeland** [comment]
Disabling HW acceleration isn't a great solution if you're trying to alt tab from a full screen game because it degrades the performance of both

**Comment by Adam-** [comment]
The root cause of this was identified and fixed in f072c82973d58889abcb3df064ac3efb2eee4deb
