### ISSUE TITLE
Side Menus overlaping.

### ISSUE THREAD

**Issue by Bonesanblood** [runelite/runelite#3433]
Not sure whats causing it but it seems like its the look up menu doing it, when i reopened it it was working fine but after the second look up it started overlapping again.

![default 2](https://user-images.githubusercontent.com/39714241/40631782-c90f7864-62ad-11e8-9d2e-8005b1375921.png)
![default 1](https://user-images.githubusercontent.com/39714241/40631783-c9264a12-62ad-11e8-8776-28c67d4afe79.png)

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Bonesanblood** [comment]
So fix a problem by giving a guide on things most people, including myself. Can't follow and understand......

**Comment by Abextm** [comment]
Sorry, this is the best solution for the minority of people that have this problem. The guide is incredibly simple, I'm sorry if you can't follow it. What part of it is confusing to you?

**Comment by Bonesanblood** [comment]
Trying to actually read it. Says theres a video but shows nothing, personally it should be spaced into different posts for different methods as #3 is far and beyond what most people will do. I ended up on #2 doing the .bat file after reading it I understood. Just too much info in a small space with a lot of code language just doesn't work too well.

**Comment by Kamielvf** [comment]
https://gfycat.com/DamagedWealthyKoalabear

**Comment by Bonesanblood** [comment]
Yah it loaded again after I tried 2, but I thought about it again, the reason i was so confused was it didn't look like methods it looked more like steps. Just scimming thru it, looked like more of a pain then it was worth.

**Comment by MagicfTail** [comment]
It clearly states that this is 3 separate instructions. The first and seconds set of instructions are very simple and will solve it for people running windows, who are the majority of our users. The 3rd instruction step is a fix for every single operating system (hopefully) and slowly becomes more advanced, as people running those operating systems are generally more experienced. Even then, if people have any questions they are free to ask in our discord

**Comment by Bonesanblood** [comment]
How many people read the parts that aren't the instructions, because that is what most people are looking for is how to fix it. Should put METHOD next to the numbers.

**Comment by Bonesanblood** [comment]
Thanks Kamielvf sorry too inconvenience you like that.
