### ISSUE TITLE
[XP Tracker] Cooking skill always starts at lvl 1

### ISSUE THREAD

**Issue by munsta0** [runelite/runelite#3434]
Hey all,

My XP Tracker shows cooking as if I had started lvl 1. So far it's the only skill affected but I haven't tested them all. Restarting the client doesn't fix this.

Here is what it looks liked : http://puu.sh/AuPXq/5803de5679.png

**Comment by psikoi** [comment]
The exp trackers use the in-game trackers to set start/target levels, edit those configurations ingame to change it.

**Comment by munsta0** [comment]
It's sort of what I figured, but I have no idea how to do that. I've checked the settings and didn't see anything related to what you are talking about. Could you give me a few pointers?

**Comment by psikoi** [comment]
Actually I just tested and it doesn't seem to get the start level of the trackers.

@LeviSchuck @deathbeam you know what's up?

**Comment by MESLewis** [comment]
The XP on the side bar is based on your vanilla XP tracker goals
https://github.com/runelite/runelite/wiki/XP-Drop

**Comment by munsta0** [comment]
That was it @MESLewis, thank you.

For reason unkown I probably activated those a long time ago and forgot about it.

I'll close this issue then, sorry for the troubles

**Comment by MESLewis** [comment]
Yeah I think a lot of people messed with the XP goals when they were first introduced and then have promptly forgotten about it until now
