### ISSUE TITLE
Add Antifire potion expiring alerts

### ISSUE THREAD

**Issue by ReeeMan** [runelite/runelite#3443]
Hi

Just like how you get an alert/notification for when your overload runs out or you get low hp/prayer. Please could you add a notification for when "Your antifire potion is about to expire." and "Your antifire potion has expired."
Screenshot of messages in chatbox - [https://i.gyazo.com/566267f90a583c9e3cb448f07057fadc.png](https://i.gyazo.com/566267f90a583c9e3cb448f07057fadc.png)

Thank You

**Comment by Adam-** [comment]
This is possible to do now with chat notifier from #3636
