### ISSUE TITLE
Highlighted items on the top of the pile

### ISSUE THREAD

**Issue by 2manyhits** [runelite/runelite#3448]
Hey, I was wondering if theres any way of making it so highlighted items appear on the top of a loot pile so looting a pk is easier as well as other functions and you can spam click the pile without missing loot. Also if u have different colours for highlighted items ie red of items <1m orange for >1m  then you would have the orange on top then red then items that are not highlighted? I think that would be a good feature.

**Comment by Reasel** [comment]
I don't think we will implement making highlighted items on the top of the pile. 

But if you want different colors for different values check out the ground items plugin config. There are settings there for varied values. [Wiki entry](https://github.com/runelite/runelite/wiki/Ground-Items) for an explanation for each setting.

**Comment by Abextm** [comment]
Duplicate #1615
