### ISSUE TITLE
Add Shift + Up/Down key combination to recall previously entered chat messages.

### ISSUE THREAD

**Issue by YoItsObama** [runelite/runelite#3455]
This is a simple yet super cool feature on another OSRS client. It's extremely helpful in crowded areas where sometimes your messages will not go through, even if you type them out multiple times. All you would need to do is hold Shift and the Up/Down key and you could alternate through your old messages that were entered. Sorry if this is in the wrong forum area.

**Comment by Nightfirecat** [comment]
This feature is basically auto-typing. If I recall correctly, we aren't interested in implementing this.

**Comment by deathbeam** [comment]
Yeah, I guess we should close this as wontfix
