### ISSUE TITLE
Bedabin != bandit camp clue location

### ISSUE THREAD

**Issue by Aneexul** [runelite/runelite#3458]
For the cryptic clue, "The cheapest water for miles around, but they react badly to religious icons", this clue location is at bedabin camp in wilderness, which runelite shows correctly in map. But the soultion in text form says to go to bandit camp (in wildernes), so please fix it :)

**Comment by SomeZer0** [comment]
>this clue location is at bedabin camp in wilderness

I am unfamiliar with any bedabin camps in the wilderness.

Bedabin Camp is in the desert.
![Bedabin Camp](https://emps-world.net/wiki/images/9/94/Bedabin.png)

Bandit Camp (Wilderness) is not called Bedabin camp.
![Bandit Camp](https://i.imgur.com/XWI2HYH.png)

**Comment by deathbeam** [comment]
This looks like correct wording after all.
