### ISSUE TITLE
Account Plugin: Add ability to copy local profile settings to synced settings

### ISSUE THREAD

**Issue by Dgc2002** [runelite/runelite#3465]
Currently when logging into a Google account to sync your RuneLite settings you are reverted to the default settings. This is a big headache when you've done things like set up a lot of bank tags/tweaked a lot of settings.  
  
I'd like to request the ability to copy the local settings onto the new profile. For example this could be done during the creation of a profile(first time logging in), potentially prompting the user to either copy the current settings or start with the default. 
  
Currently the local settings are stored at `.runelite/settings.properties` and settings synced to a Google account are stored at `.runelite/profiles/example@gmail.com/settings.properties`. I attempted to manually overwrite the profile-specific `settings.properties` file but it seems the synced settings will just overwrite the changes.

**Comment by caliweed** [comment]
Yeah it's bad for bank tags. Also I hate having to type email each time to log in diff accounts.

**Comment by Adam-** [comment]
This was added in #7410
