### ISSUE TITLE
Slayer Plugin counts incorrectly when kills happen simultaneously

### ISSUE THREAD

**Issue by TylerNichols** [runelite/runelite#3466]
There is a problem where the count of remaining monsters for the given task is wildly off when killing multiple monsters at once. This is most noticeable when bursting a task such as dust devils.

**Comment by TylerNichols** [comment]
From looking at SlayerPlugin.java , it looks like we are saying every xp change is one kill. 


To fix this I think we need to know the HP or XP rewarded from a single monster and compare our XP difference to get the count killed. I would be interested in fixing this unless there is blocker that I am not aware of.

**Comment by deathbeam** [comment]
Duplicate of #1046
