### ISSUE TITLE
Add Anti-Drag support to bank interface

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#3471]
Would help when withdrawing gear, you don't accidentally rearrange gear.

Shift+Click should not be required for this as there's no real advantage over other players to be gained when clicking inside your bank.

This should not increase XP/H of any activities, as any bankstanding skills will usually require withdraw-X or withdraw all, instead of withdraw-1.

Edit: Jagex has added left click withdraw-x/all. Possibly could insignificantly increase xp rates for bankstanding skills.

**Comment by dekvall** [comment]
Closing in favour of #10262 as it has a PR.
