### ISSUE TITLE
Missing highlight for dense forest

### ISSUE THREAD

**Issue by Floukru** [runelite/runelite#3472]
![image](https://user-images.githubusercontent.com/38350898/40690920-1332c194-63b2-11e8-92c2-9a958faf80e4.png)

It only highlights the middle one, but not all 3? 

Where is this: In port khazard - camp site.

**Comment by jplsek** [comment]
Not related to clues @Abextm ;) #2674 should fix this.

**Comment by sethtroll** [comment]
Added in #3731 I believe

**Comment by Nightfirecat** [comment]
Confirmed, these obstacles are being highlighted now.
