### ISSUE TITLE
Feature request: item pick up log

### ISSUE THREAD

**Issue by Laxson1** [runelite/runelite#3477]
Have a tab on the side that just shows everything you have picked up, so you can track a slayer task or show boss drops without having to figure out what you already had in you bank. Have it where you can clear either everything off the tab or remove a specific item. (Not sure how to tag with feature request?)

**Comment by Infinitay** [comment]
#3174 this is already in development by none other than Woox

**Comment by Abextm** [comment]
Duplicate #2393
