### ISSUE TITLE
Change attack options to right-click if doing Master Clue w/New Crystal Bow (i)

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#3481]
I'll say I'm not sure if this is even possible w/o faking user actions.

There's a master clue step where you have to do an emote in elf lands w/a New Crystal Bow (i). If you accidentally shoot the bow, it becomes useless to the clue and you'll have to buy another for 900k or deplete the one you just got and recharge it. It's not exactly hard to misclick while running to Iorwerth for the emote (he's surrounded by elves), or use a charge on the Double Agent, both which will fuck you.

Solution would be to turn the attack options to right-click to avoid misclicking, since I doubt there is a way for Runelite to turn off attack options completely on the condition that a new Crystal Bow (i) is currently equipped while the clue tracker detects this specific step.

**Comment by williammetcalf** [comment]
This wouldn't be faking user input, but the difficult part is that it would be hard to code in a clean way.

It would be difficult to make in a way that doesn't either:
1. Make connections between different plugins (something that should be avoided), or
2. Rewriting a bunch of code to avoid *1* (also should be avoided)

That said, it would be a cool feature, and there are a lot of similar things that a condition menu entry swap could be used for.

**Comment by Jalopyy** [comment]
Well it'd be nice. I've had that clue 2 times since then and it makes me paranoid as fuck.

**Comment by ittwit** [comment]
@williammetcalf 
Or it could just remove the attack option from the MenuEntry list when holding the bow

**Comment by Jalopyy** [comment]
That would certainly work if it can work when the clue frame detects this specific clue step (or something similar).

**Comment by JeljoGb** [comment]
You don't actually need a new one. It works fine with a regular imbued one.
![image](https://user-images.githubusercontent.com/34870401/43654386-54fb95a2-974b-11e8-8b6d-aca574b6277b.png)
