### ISSUE TITLE
Improve GrandExchange notifications (PR #3233)

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#3484]
Currently the notifications are done in horrible way. There are chat messages for all the events, so all that needs to be done is check for the chat messages.
Also, the notification delay is completely useless there.

Introduced in: #3233

**Comment by deathbeam** [comment]
@shmeeps

**Comment by shmeeps** [comment]
The chat message notifications are not as reliable as the events handler; I had several notifications missed when testing the alternative implementation. The benefits of either are debatable, as the current implementation may be too busy for some users, and some may not like receiving notifications on login.

Regardless, addressed in #3492.
