### ISSUE TITLE
Bank value calculator

### ISSUE THREAD

**Issue by Dreyri** [runelite/runelite#349]
What it says, combined bank value and bank value per tab probably.

A special list of items referencing other ids to account for certain untradables  #such as charged dfs.

**Comment by bryandh** [comment]
Would/should it, as an additional functionality, also provide GE/alch value when hovering over an item/stack?

**Comment by TheLonelyDev** [comment]
Working on a plugin. I will do some tests with the hovering/tooltips... We just need to do something about 'used' items for their value etc

**Comment by Dreyri** [comment]
A first version should probably just calculate your entire bank, from there we can expand

**Comment by Peaslek** [comment]
@TheLonelyDev Any plans on picking this up again?

**Comment by Adam-** [comment]
Done in #824
