### ISSUE TITLE
Wrong `Actions Left` while fletching adamant darts?

### ISSUE THREAD

**Issue by RomeuG** [runelite/runelite#3496]
While fletching adamant darts, the `Actions Left` part shows a mathematically incorrect number, even when compared to OSBuddy.

Runelite: 
![Actions left Runelite](https://i.gyazo.com/thumb/1200/ae3118c8c9d7a20fe0e0c2a33808d75a-png.jpg)

Osbuddy:
![Actions left OSBuddy](https://i.gyazo.com/thumb/1200/4ead8b3395f71da12b1ab9e0b91ce08a-png.jpg)

As you can see,  the mathematically correct number of actions left is 5957, while RuneLite shows a very different number, 3972.

What is going on here?

**Comment by sethtroll** [comment]
If you are spamming darts, sometimes the xp drops are grouped together, which makes the number skewed.

**Comment by RomeuG** [comment]
Well, I am afraid that is not the case. In both images only 1 set of darts were made.

**Comment by AlexKolpa** [comment]
Did you happen to fletch anything beforehand in that session? RuneLite uses the 10 last actions for a specific skill to estimate the amount of actions required, so if you did something earlier it could very well be the case that those actions influence that value. I tested adamant darts with a new session and got the correct number of actions. That's not to say this behaviour is slightly counter-intuitive, but it should correct itself after 10 action if that's indeed the underlying issue.

**Comment by RomeuG** [comment]
Well you're right. Makes sense. Anyways, why the last 10 actions and not the ONE last action? Anyways, thank you for your explanation.
