### ISSUE TITLE
DPS calculator in equipment interface

### ISSUE THREAD

**Issue by frengels** [runelite/runelite#350]
Calculate max hit, accuracy, special attack max hit & accuracy, and DPS.

based on [Bitterkoekje's spreadsheet](https://docs.google.com/spreadsheets/d/1wzy1VxNWEAAc0FQyDAdpiFggAfn5U6RGPp2CisAHZW8/edit#gid=158500257)

**Comment by matthewpetch** [comment]
You would need to be able to select the NPC you're wanting to fight for the DPS

**Comment by deathbeam** [comment]
or the DPS would update when in combat, otherwise it will calculate it based on target dummy/undead target dummy, that can work pretty good.

**Comment by Not-Dreyri** [comment]
You'd also need a list with all stats of NPC's

**Comment by deathbeam** [comment]
Yeah, that can be scraped from the wiki.

**Comment by Dreyri** [comment]
That was actually me, but logged in to the wrong account

**Comment by TheSexyNerd** [comment]
If anybody would like to make this I've already started the basics of a combat simulator
[https://github.com/TheSexyNerd/OSRS-Combat-Simulator](url)

**Comment by shermaza** [comment]
Seems like a reasonable MVP for this would be DPS vs whatever monster you're fighting, then another iteration would be a panel to select any monster.

**Comment by mironec** [comment]
I have started writing this at [https://github.com/mironec/runelite/tree/plugin/dps-calculator](https://github.com/mironec/runelite/tree/plugin/dps-calculator). The problem would be scraping the wiki for all monster data and presumably creating a runelite API for that. I have just thrown this together quickly in a day or two (one godclass), but maybe people can pick it up if they like it.

**Comment by sadegr** [comment]
I'd prefer for this to be a new panel rather than something added in the equipment interface. I feel it'd be much quicker to use dropdowns to select your gear rather than having to take gear out of the bank/buy it when you may be comparing dozens of options.

**Comment by cloakd** [comment]
Ive built this into a web tool with all the data processing for the DPS within a REST API, once ive finished the bugs on the tool ill migrate it into a runelite plugin (should only take a day or two)

Any feedback would be greatly appreciated: https://osrs-genie.com [osrs-genie com]

**Comment by LovinLifee** [comment]
> Ive built this into a web tool with all the data processing for the DPS within a REST API, once ive finished the bugs on the tool ill migrate it into a runelite plugin (should only take a day or two)
> 
> Any feedback would be greatly appreciated: https://osrs-genie.com [osrs-genie com]

It looks great, only thing I don't like is how long the lazily-loaded images take to load in. Perhaps you could add a spinner or something. :)

**Comment by winterdaze** [comment]
There's an updated version of bitterkoekje's spreadsheet, btw. it's now maintained by koekenpan:
[link](https://docs.google.com/spreadsheets/d/1wBXIlvAmqoQpu5u9XBfD4B0PW7D8owyO_CnRDiTHBKQ/edit?usp=sharing)

**Comment by cloakd** [comment]
> There's an updated version of bitterkoekje's spreadsheet, btw. it's now maintained by koekenpan:
> [link](https://docs.google.com/spreadsheets/d/1wBXIlvAmqoQpu5u9XBfD4B0PW7D8owyO_CnRDiTHBKQ/edit?usp=sharing)

Oh awesome ill go through and update any formula thats been missed!




> > Ive built this into a web tool with all the data processing for the DPS within a REST API, once ive finished the bugs on the tool ill migrate it into a runelite plugin (should only take a day or two)
> > Any feedback would be greatly appreciated: https://osrs-genie.com [osrs-genie com]
> 
> It looks great, only thing I don't like is how long the lazily-loaded images take to load in. Perhaps you could add a spinner or something. :) Also could add specs for their respective weapon as well as support PVP by using the 2nd set

Yeah i agree the original iconset dump is all PNG files so will be moving to webp and improving the UX today to resolve this :)

**Comment by Nightfirecat** [comment]
A DPS calculator was added the plugin hub in runelite/plugin-hub#1397
