### ISSUE TITLE
Easy clue step "The hand ain't listening."

### ISSUE THREAD

**Issue by Ammako** [runelite/runelite#3506]
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CrypticClue.java#L261

![image](https://i.imgur.com/e2sm5Ix.png)

"The hand ain't listening!" --> "The hand ain't listening."

**Comment by Nightfirecat** [comment]
Will write a PR for this in a few hours if nobody else does first.
