### ISSUE TITLE
Objective / to do sidebar

### ISSUE THREAD

**Issue by RickertdeH** [runelite/runelite#3507]
I'm currently tracking my objectives, goals and other to do's in the notes tab. However that gets messy and un-organized quickly. Would love to have a object/to do list in the sidebar when I can easily track and organise everything. If it can track skill/quest goals directly from in game that would make it even better.

**Comment by ProtocolHD** [comment]
Are you asking for essentially a notepad that you can then make an outline of sorts that you can then 'check off' goals as you go? @RickertdeH

**Comment by SolveSoul** [comment]
If this were a simple checklist with textual goals then it wouldn't be that difficult to implement. If it were a goal list that supports different goals (skills/quests/diaries/music unlocks/ ...) and extracts progress/completed state from the game then we're on a whole other level of amount of work required to make this work.

Could also be a simple checklist at first and later be improved with dynamic goals in a v2 (only a Sith deals in absolutes, so...)

Either way, I do like the idea!

**Comment by ConnorVG** [comment]
I built something similar to this for a private client a long time ago. I know stuff such as quests and music unlocks are trivial to track. What other sort of goals would we expect to track bar diaries, levels and drops?

**Comment by Nightfirecat** [comment]
A number of list/task tracking plugins exist on [the plugin hub](https://runelite.net/plugin-hub/). I recommend searching for them there. (a search for "task" yields 8 results for instance)
