### ISSUE TITLE
Idle notification disrupting Os sticky keys shift drop 

### ISSUE THREAD

**Issue by Pluginrs** [runelite/runelite#3510]
I think there is an issue with idle notification disrupting Os sticky keys shift dropping. (i'm on Mac). Don't know if Runelite devs are already aware of this issue or not. Sharing it just in case.

e.g. My character is fishing with sticky keys enabled (so i don't have to keep pressing the shift key every time my inventory is full with fish). When character stops fishing appears a notification on the top right of my screen and it will automatically disrupt the sticky keys shift drop. 

Thanks in advance

**Comment by deathbeam** [comment]
This sounds like OS issue. Try disabling request focus on notification, otherwise, cant do much about this.

**Comment by Pluginrs** [comment]
Disabling request focus on notification won't fix it unfortunately..
