### ISSUE TITLE
Change imbued heart infobox condition

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#3516]
I assume as of now it's set to the animation ID for using the heart. Sometimes in combat the animation gets ignored/overwritten depending on what you're doing, causing the infobox not to show up.

Is it possible to change the infobox condition for appearing to be when your magic level gets set to what the heart boosts it to, which is 10% of level (rounded down) +1? No other magic boost in the game does the same thing (maybe there could be some overlap if you do something like use a magic potion when level 30-39). Not sure if OSRS allows some type of condition where you can set code to execute if item in inven = true, or something.

**Comment by humphrjm1** [comment]
Seeing this again. This can be addressed by adding a listener for the chat message. the "judging by how it feels" message can be used to set an approximate timer
