### ISSUE TITLE
Dorgesh-kann broken lamp overlay

### ISSUE THREAD

**Issue by Justin222111** [runelite/runelite#3519]
There is a clue challenge that requires you to fix a broken lamp in dorgesh-kann. it is often really hard to spot a broken lamp, if there is even one to be found. I spent around 20 minutes just now, trying to find a lamp to fix. so I was wondering if it would be possible to add an overlay to broken lamps to make them less annoying to find.

**Comment by dekvall** [comment]
Closing in favour of #10069 as it has a PR.
