### ISSUE TITLE
Full screen mode not working when losing focus/on mac

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [runelite/runelite#3523]
when in full screen doing ALT + TAB to switch from window and then back to runelite the full screen mode gets bugged which is only fixable by price checking an item in your inventory or by player lookup 

https://github.com/runelite/runelite/pull/3521

some players are not getting full screen at all as shown bellow

Draconyte - Today at 3:07 PM
http://prntscr.com/jp0wt6 this is what happened when i switched to fixed mode LUL
Lightshot
Screenshot

LUL http://prntscr.com/jp0wcm this is using fullscreen mode in "Runelite" settings on expanded window
Lightshot
Screenshot

^^^^^^ user above has the discord code: Draconyte#0019

**Comment by deathbeam** [comment]
As fullscreen mode was removed this is no longer an issue
