### ISSUE TITLE
Add ability to set goal levels in XP tracker

### ISSUE THREAD

**Issue by TylerNichols** [runelite/runelite#3527]
I am interested in there being a right click > set goal level in the skill XP tracker.

It seems like looking at the code that this would not be too large of an addition as it somewhat set up to handle goals, but it always defaults to current level + 1 as the end goal. Unless there is another way to set the goal level that is not visible from the plugin itself, it doesn't seem possible to ever change it.

If this is a reasonable addition to the plugin I will be happy to make it.

**Comment by Hydrox6** [comment]
This is already possible through the Vanilla XP drops system

**Comment by deathbeam** [comment]
We already have goals, we use vanilla goals (this interface: https://github.com/runelite/runelite/wiki/XP-Drop)
