### ISSUE TITLE
Clue scroll plugin - Required items doesn't hide when a new step is opened

### ISSUE THREAD

**Issue by Unmoon** [runelite/runelite#353]
May happen only with maps or elite clues?
![image](https://user-images.githubusercontent.com/7273082/34811562-22066650-f6aa-11e7-8a32-5b2aa94c4960.png)

**Comment by devLotto** [comment]
This probably has to do with ``WidgetInfo.CLUE_SCROLL_TEXT`` not existing in clues that don't have text in them (like the one you're showing).

That would have the effect that clueScrollOverlay.clue is never reset to null, unless a clue with text in it pops up.
