### ISSUE TITLE
JVM crash after few minutes of playing

### ISSUE THREAD

**Issue by Nido32** [runelite/runelite#3539]
I recently switched from OSB to Runelite. But only after 5 minutes of playing, I noticed some frames droped and the game crashed. I tried downloading the latest version and put the --mode=OFF-- at the end of the shortcut. I logged onto runescape, walked a bit and when the map loaded, the client crashed again. It said Runelite stopped working. Any idea how to fix this?

**Comment by RickertdeH** [comment]
Can you give some system info? Did osbuddy run fine all the time?

**Comment by Nido32** [comment]
Yes OSB runs fine all the time. By system info do you mean the specs of my computer? If so, it has 4 GB of ram, Radeon hd series 7700, Intel Core 3.00GHz

**Comment by Nido32** [comment]
The first time I open it, when a loading screen shows up, like teleporting away, the client crashes leaving a hs_err_pidxxxx text file.

**Comment by Kamielvf** [comment]
If you are in the discord, could you message that error file to me? It most likely contains useful information for us to find out what's crashing the JVM. you should be able to see me in the members list on discord.

**Comment by Nightfirecat** [comment]
As has been mentioned by Kamiel, [please join our Discord's `#support` channel](https://runelite.net/discord), and post your JVM crash log there. It will be found in your log folder and will be named something like `jvm_crash_pid_12345`.
