### ISSUE TITLE
Clanning Features & Other

### ISSUE THREAD

**Issue by tsenif** [runelite/runelite#3549]
**Is your feature request related to a problem? Please describe.**
No, more of a convenience & would be very popular within the clanning community.

**Describe the solution you'd like**
There's a few.
- Multi lines, display lines on the screen to display exactly where multi combat zones are. Useful for PKers that are unfamiliar with areas, very useful for clanning. PvMers could also find use for this I suppose.
- Resizable clan-cape counter to display them vertically like Konduit has. Also displaying the team-cape image for whatever team-capes are nearby would be sweet. The current Team-cape overlay is rather large & intrusive. 
- Built in video recording for easy access for recording.
- Ability to see players on the minimap/game screen whether or not they have you added, so long as you have them added. (OSBuddy, Konduit, RuneLoader, & Exilent all had this feature). This is helpful to find the Leader of your clan easily, because a Leader surely isn't going to have every member added. Also helps for finding piles.
**Describe alternatives you've considered**
A not-so-popular client called 'Exilent' has the multi line feature & built-in recording feature.

**Additional context**

**Comment by Infinitay** [comment]
Multilines is being worked on by woox and he has made great progress on it already. As for seeing offline friends on your minimap, it was rejected to respect players' privacy (https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features, more specifically #951)

**Comment by tsenif** [comment]
Perhaps a feature that just highlights higher ranked individuals on the minimap if you're in the same clan chat as them?
