### ISSUE TITLE
1.4.1 inventory tooltip for expeditious bracelet keeps resetting to 30 after charges change

### ISSUE THREAD

**Issue by abra238** [runelite/runelite#3550]
I'm just doing tasks with them and I notice this happens. I 'check' it and it goes back to what it actually is, but then goes back to 30 after the charge count changes, except when the charge changes to 1, then it actually shows 1 even without 'check'ing it.

this only started happening on 1.4.1

this also only happens with the expeditious bracelet, not the bracelet of slaughter.

[video showing this](https://youtu.be/h7eGT7ZxNKc)

**Comment by deathbeam** [comment]
This was already fixed in master, will be fixed next release.
