### ISSUE TITLE
Clue scrolls plugin - Add missing guides

### ISSUE THREAD

**Issue by Unmoon** [runelite/runelite#357]
At least "Does one really need a fire to stay warm here?" is missing.
Check [wiki](http://oldschoolrunescape.wikia.com/wiki/Treasure_Trails/Full_guide) for more?

**Comment by Sethtroll** [comment]
IRRC when making this plugin I scraped the wiki for the clue answers/riddles. Any new clues added after this plugin would have to be added manually (or changed to automatically scrape/add).

**Comment by deathbeam** [comment]
Another missing one:

```
Aggie I see, Lonely and southern I feel I am neither inside nor outside the house yet no house would be complete without me. Your treasure lies beneath me. 
```

**Comment by Abextm** [comment]
From @Apo on discord.
Anagram "AREA CHEF TREK" has the wrong answer. The correct answer is 20, due to DS2 being relased.
