### ISSUE TITLE
Screen markers being moved to top left of screen

### ISSUE THREAD

**Issue by voetre** [runelite/runelite#3571]
| Java Version | Version 8 Update 161
| Operating System | Windows 10 Pro Version 1803 OS build 17134.48

When creating screen markers, if you click the new screen marker button, then collapse the side panel and proceed to draw a screen marker on the right side of the screen, if the marker is too far right when you expand the side panel it will be hidden until you confirm its placement, upon confirmation it will then change its position to the top left of the screen. If you move it from the top left of the screen to the position you wish to have it with the side panel closed it will remain there until you reopen the client, upon which it will be moved back into the top left of the screen.

here is a video demonstrating this issue:
https://youtu.be/o1wCSSLGycw

steps I take in video:
1. I first click add screen marker
2. next I close the side panel
3. I draw the marker
4. I extend the side panel
5. marker is no long visible
6. I confirm marker placement
7. Marker is moved to top left of screen
8. I move marker back to desired location
9. I log out and back in
10. marker remains in correct position
11. I close and reopen client
12. Marker is back in top left of screen

**Comment by Adam-** [comment]
Fixed in 4792e61997bd95bedd494ef1d29dbb45c691efe2
