### ISSUE TITLE
GE Prices on Drops and Examines not working

### ISSUE THREAD

**Issue by GumFlap** [runelite/runelite#3576]
So I've checked all plugins, and nothing relevant is turned off. Ive been through the settings of ground options and cant see anything other then turn on high alch values. If i examine an item it used to show the gran exchange price and high alch and now only high alch price not even mentioning GE. am i missing something? 

I havnt messed with any settings, until i noticed it was missing, too cause any of this.

**Comment by GETrackerDan** [comment]
Similar thing happening too myself too.

https://i.imgur.com/vNYsfkL.png

I've been working on a few chatcommands so assuming it was something i had done though.

**Comment by djbuggy** [comment]
I noticed it stopped working when I had the shift-click setup running on my inventory when I clicked save it solved that examine bug

**Comment by deathbeam** [comment]
This was probably caused by API issues so closing
