### ISSUE TITLE
Ardougne rooftop gameobject not being highlighted

### ISSUE THREAD

**Issue by l2-** [runelite/runelite#3580]
https://i.imgur.com/LlkTDHa.png
The steep roof object is not being highlighted.

I traced this to Perspective.java line 485, seems like get2DGeometry() returns an empty area.
If you search a little further in get2DGeometry() it seems that the faces for this particular object are culled and therefore not added to the area. 
I don't know if these faces in case of 2DGeometry should be culled, but we're looking for the area of a clickbox, and a clickbox area in oldschool runescape isn't blocked because it's on the "wrong" side of an object. From what i understand, in case of a clickbox area, there shouldn't be a face culling check.
Anyway when the face culling check is commented out the object is highlighted like it should be:
https://i.imgur.com/gAAPgy9.png

I hope someone with more knowledge about the Perspective class can fix this issue

**Comment by sethtroll** [comment]
What version are you running? We pushed a fix for this in 1.4.1.1 edb55fd

**Comment by l2-** [comment]
Yea sorry missed that nevermind then
