### ISSUE TITLE
Add an option to block out strings to ConfigItem

### ISSUE THREAD

**Issue by CustardGod** [runelite/runelite#3584]
Currently working on a Twitch chat plugin in which the user needs to enter their oauth token in a string Config option to speak in the chat. I would like to be able to block out that string so that streamers can't accidentally leak their token.

Example:
Instead of: "oauth:..."
Show: "******..."
In the text box

I've tried looking into this myself but don't really know how to do it.

**Comment by Adam-** [comment]
Added in #5276
