### ISSUE TITLE
Screen markers don't work

### ISSUE THREAD

**Issue by Mantas1452** [runelite/runelite#3591]
Screen markers don't work at all. I don't see them while drawing or after they're drawn. Changing the settings (filling them in, changing borders, etc.) doesn't do anything. Disabling and enabling the plugin also doesn't do anything. I've tried disabling hardware acceleration too, no results though.

I'm on Windows 7 and using Java 8u171.

Sorry if I'm missing something obvious.

**Comment by SoyChai** [comment]
Are you dragging from top-left to bottom-right? It's not mentioned at the moment, but this is the only way you can currently draw markers.

**Comment by Mantas1452** [comment]
Holy shit I'm dumb lol. That works, thanks. I'm left handed, might be why everything goes from right to left for me. Sorry.

**Comment by Unmoon** [comment]
Should maybe keep this open but make it about drawing them in any direction.

**Comment by Nightfirecat** [comment]
@Unmoon That's already being tracked in #3524 and #3590 has been opened to fix it.
