### ISSUE TITLE
XP globes actions left dependancy

### ISSUE THREAD

**Issue by raqes** [runelite/runelite#3595]
The XP Globes plugin depends on the XP Tracker for the actions left calculation.
So when the XP Tracker plugin is disabled actions left is set the max integer or the last known value.

![runelite_2018-06-03_14-32-29](https://user-images.githubusercontent.com/13276766/40886616-bb908bc8-673b-11e8-8bc0-28dc3a7d6bf9.png)

The correct behaviour would be to not show actions left unless the XP Tracter plugin is enabled.

**Comment by Adam-** [comment]
Fixed in #3638 by resetting xp stats when the xptracker plugin is shut down.
