### ISSUE TITLE
Missing pause button?

### ISSUE THREAD

**Issue by Floukru** [runelite/runelite#3598]
**Is your feature request related to a problem? Please describe.**
It's not a problem we just need pause and play button for skills just like konduits features. I was only trying to take break to eat my lunch and want my grind to stay. But couldn't.

**Describe the solution you'd like**
A play and a pause button to stop calcuating.

**Describe alternatives you've considered**
N/A 

**Additional context**
 
![image](https://user-images.githubusercontent.com/38350898/40888895-b12e1d0a-6766-11e8-8206-0946aa2e2ce1.png)

**Comment by LeviSchuck** [comment]
I've got an implementation in progress that also handles mine too #3113

Last is refining some display niceties.
