### ISSUE TITLE
Splashing timer

### ISSUE THREAD

**Issue by JurreBrandsen1709** [runelite/runelite#3611]
**Is your feature request related to a problem? Please describe.**
After the Splashing nerf, you will automatically log-out after 20 minutes of splashing. Currently I'm using an Online stopwatch that count-down 18 minutes and after I receive that warning I will have to click on my RuneScape screen.

**Describe the solution you'd like**
Like the Idle notification, you receive a warning when you're almost logged out.

**Comment by Abextm** [comment]
Duplicate #925
