### ISSUE TITLE
Metronome sound independant from ingame sounds

### ISSUE THREAD

**Issue by Scahry** [runelite/runelite#3614]
**Is your feature request related to a problem? Please describe.**
The  Metronome sound currently only works with the ingame sounds turned on and these are so loud i can barely here the metronome anymore

**Describe the solution you'd like**
I'd like a volume slider added to the metronome setting so i can choose the volume of the metronome sounds

**Describe alternatives you've considered**
I dont have a problem if you have to turn on in-game sound, but i'd like to configure the metronome volume even if dependant on the ingame sound volume.

**Comment by Abextm** [comment]
Duplicate #530
