### ISSUE TITLE
Boss timer notification

### ISSUE THREAD

**Issue by pjdr5** [runelite/runelite#3616]
Hello, would love to see a boss timer notification. We have got the boss timer now and it would notificate you when you are in another window like the idle notifications you get right now, but when a boss spawns.

**Comment by deathbeam** [comment]
This feature is not very useful as bosses do not take that long to respawn

**Comment by andreykaipov** [comment]
How long a respawn takes is relative. I think it would be useful for afking specific bosses. For example Rex takes 1 minute 30 seconds to respawn. I can do so many things in one minute! 😄

**Comment by andreykaipov** [comment]
Related PRs https://github.com/runelite/runelite/pull/7397 https://github.com/runelite/runelite/pull/7439
