### ISSUE TITLE
Anti-Screenshake

### ISSUE THREAD

**Issue by Edvinas-Smita** [runelite/runelite#3621]
When the camera shakes randomly (most notably this occurs on the very last stage of Olm, in the volcanic mine and after looting a barrows chest (probably more places have this but i could only think of these right now)) it is really tiring for my eyes and after a few short seconds I will start blinking more often and involuntarily start shifting my focus away from the screen. I would love if there was a way to disable this sort of camera behavior.

**Comment by SolveSoul** [comment]
The fishing trawler mini-game has a vanilla in-game toggle to switch from moving to static camera. Maybe this could be a starting point when investigating how to implement this. Just throwing it out here.

**Comment by Kamielvf** [comment]
I don't think we should be doing this, something which effectively prevents a certain game mechanic from doing anything could be considered OP.

**Comment by deathbeam** [comment]
Yeah
