### ISSUE TITLE
Slayer task showing up after losing members in a F2P world

### ISSUE THREAD

**Issue by AssassinA04** [runelite/runelite#3628]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | x.y.z
| Operating System | e.g. Ubuntu/Windows/MacOS

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by Nightfirecat** [comment]
More generally, the slayer infobox appears on F2P worlds regardless of your account's membership status.

**Comment by AssassinA04** [comment]
Thanks for the reply! Been playing for a few months and love the client!

**Comment by Adam-** [comment]
Fixed in #4012
