### ISSUE TITLE
MacOS Battery Usage Too High

### ISSUE THREAD

**Issue by LordGigaraticus** [runelite/runelite#3637]
Client seems to be using significantly more battery power than it should be. According to the MacOS Activity Monitor, the client uses at least ten times as much energy as any other app running on my machine. Screenshot attached showing Activity Monitor reading when idling on the login screen. Energy Impact will jump to over 70 while in game.

![screen shot 2018-06-05 at 10 48 23 am](https://user-images.githubusercontent.com/18078944/40990683-dc5980e8-68ae-11e8-8b13-7ca5fe2312fd.png)

**Comment by Unmoon** [comment]
This is normal for video games.

**Comment by Jasper-ketelaar** [comment]
What battery power is used by the vanilla client?

**Comment by LordGigaraticus** [comment]
Looks to be about the same or slightly better than the vanilla client. Closing issue as issue is a non-issue.

**Comment by jtstein** [comment]
For anyone in the future who finds this thread:
On RuneLite, enable FPS control and set the cap to 20-30 to significantly lower the power impact.

**Comment by OliverHeward** [comment]
> For anyone in the future who finds this thread:
> On RuneLite, enable FPS control and set the cap to 20-30 to significantly lower the power impact.

Found this to be the only viable way to prevent it. Also some other tips for anyone... these don't fix it but they can help.

- Turn off unused plugins
- Turn screen brightness down by 5 - 7 "bars"
- FPS 20-30 for Slaying/Combat and drop it all the way down to 5-10 for any afk skilling
- Always play in fixed mode, stretched destroys mine
- Keep the Runelite window on your Macbook, don't move it across to external monitors (always found my laptop goes nuts when i do this) 
- Turn low-detail mode on
