### ISSUE TITLE
Large clue scroll overlay takes up too much screen real estate 

### ISSUE THREAD

**Issue by RuneliteFan** [runelite/runelite#3644]
Certain clue scroll steps have a large overlay that overtakes the screen (example here: https://imgur.com/27xB69J). Three possible solutions discussed include 1. Condensing the amount of information displayed to include only relevant information  2. Introduce a clue scroll helper in the sidebar so that information does not interfere with the screen or 3. Add the ability to hide/unhide clue steps

**Comment by RuneliteFan** [comment]
https://imgur.com/a/o5G2CLQ

I am going to compile a list of steps that are too large on fixed screen.

**Comment by laagone** [comment]
Support for making a panel on the sidebar, that way it's always available if you want it but it doesn't take up screen space on the game. It's distracting and can get there even when you just pick up a clue scroll and haven't opened it (https://i.imgur.com/A8IE4TR.png), and turning off the plugin is the only way to get rid of it but that's not a very elegant method.

**Comment by deathbeam** [comment]
This was solved by removing full cryptic clue descriptions from overlay
