### ISSUE TITLE
Plugin for 1 way pvp safe spots

### ISSUE THREAD

**Issue by dakoolking23** [runelite/runelite#3646]
In pvp combat, there are tiles you can stand on next to an object where you can hit your opponent and he can not hit you back even if he's in range. It counts as him behind an obstacle and you are not. It can also work vice versa where the target is next to an object and you are not, yet you still have him in a place where he can't hit you back even if you are within 1 square. There is already a private plugin for this but I would like a public one to be made available. 

This plugin would see where your target is standing, then compare it to nearby obstacles and highlight squares where you could stand and be in a 1 way safespot and squares where if you stood there the opponent would have you in a 1 way safespot.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
