### ISSUE TITLE
Player Indicators showing offline Friends

### ISSUE THREAD

**Issue by Scahry** [runelite/runelite#3653]
**Is your feature request related to a problem? Please describe.**
When having the Player Indicators on, it does not show friends next to you if they have turned private off

**Describe the solution you'd like**
I'd like to draw the name of my friends even if they are hidden in my friends list if they are next to me

**Comment by gtjamesa** [comment]
I believe this has been rejected before to respect user's privacy

**Comment by ypperlig** [comment]
See discussion in #951

**Comment by Scahry** [comment]
ok, so be it. Even tough is disagree with it
