### ISSUE TITLE
Skill Planners

### ISSUE THREAD

**Issue by Mollerz** [runelite/runelite#3654]
It would be nice if the Skill Calculator tab was enhanced to also include Skill Planners for each event. 

Let's say I want to know how much herblore experience I would be getting with the current herbs I have, I could put into the planner that I *plan* to make this many of x, y, and z potions and it would tell me what level I would have at the end.

I am not a graphic designer at all so I will just explain how it should look. Pretty much identical to the Skill Calculators, except there is no target level, it just states what the final level/experience would be after the actions selected. Each item on the list would have an edit box that you can put an integer in for how many of that item that you plan to make. You can do this for as many items on the list as you need and it would just spit out that final experience number at the end.

**Comment by Nightfirecat** [comment]
The [Banked Experience hub plugin](https://runelite.net/plugin-hub/show/banked-experience) effectively does this. I'd recommend using that to accomplish this.
