### ISSUE TITLE
Xp tracker doesn't track xp gained after hitting virtual level 126 in the skill

### ISSUE THREAD

**Issue by nevermorexxx** [runelite/runelite#3658]
You can see in the pic I'm gaining smithing xp but it's not appearing on the tracker. This happened after hitting virtual level 126.

![image](https://user-images.githubusercontent.com/38351285/41062791-80ec88a4-69df-11e8-9235-2c3220b6c76b.png)

**Comment by 07RS** [comment]
Slightly related issue: 

Last time I checked when you enter an xp value which is higher than that required for level 126 (>188.8m) in  the skill calculator, it defaults it back to the closest virtual level. So if you were to set a target of 200m it would calculate the items/resources required for you but only to level 126. 

This may have already been addressed, I'm on my phone so cannot check at the minute.

**Comment by LeviSchuck** [comment]
Confirmed and I have a fix for this.
