### ISSUE TITLE
runelite display tiled on ubuntu 16.04.4

### ISSUE THREAD

**Issue by duracell33** [runelite/runelite#3660]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | java-8-oracle
| Operating System | Ubuntu 16.04.4 LTS

when i open runelite [this](https://user-images.githubusercontent.com/36210845/41069028-0b95e622-69e4-11e8-87b7-2d343416ed37.png
) is all i get, i think i could log in if i could find the button as i was able to mute the game 

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by Kamielvf** [comment]
Try https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
