### ISSUE TITLE
Boss log

### ISSUE THREAD

**Issue by natanvdmeulen** [runelite/runelite#3667]
It would be nice to have a boss log which describes what bosses you've killed when ur client is open, with the loot. Like, if you've killed 20 Vorkath, it would show 20 Vorkath, 40 Superior dragon bones with it's actual price. It's easy to track ur gp/hr that way. OSBuddy has something similar, but theirs is buggy as hell.

**Comment by CaraPis** [comment]
I believe this is what you're looking for?
https://github.com/runelite/runelite/pull/3545

**Comment by natanvdmeulen** [comment]
Yep! Im kinda new to runelite. Will this be added? Do I have to do something myself?

**Comment by Alexsuperfly** [comment]
this was added in #4555
