### ISSUE TITLE
slayer plugin tooltip highlight not accurate/doesn't work

### ISSUE THREAD

**Issue by abra238** [runelite/runelite#3673]
https://i.imgur.com/80xbUXz.png

**Comment by Abextm** [comment]
What is incorrect?

**Comment by abra238** [comment]
mousing over the task icon shows points and streak. streak shows 0, and
points shows 8/9.

**Comment by Alexsuperfly** [comment]
I've spoken to a friend of mine and he has the same issue.  He says it shows `Points: 17` `Streak: 0`.  he currently has over 17 thousand slayer points and told me that when he was at ~15k it showed `Points:15` and when he broke into the 16 thousands it showed `Points: 16`.  This seems to me like the regex is mis matching when the points total is over one thousand points.
