### ISSUE TITLE
Allow regex or glob style item names for highlighted or hidden ground items

### ISSUE THREAD

**Issue by grantmwilliams** [runelite/runelite#3679]
I think having the ability to add items to the highlighted and hidden items list using glob or regex styles would be useful. If you were an ironman hunting for keys you might want to be able to add something like `(*key)` that would allow you to match any item that name that ends in 'key'.

Looking through the source code i didn't see anything like this implemented. 

It'd have to be in a way that has some sort of escape for the regex so people don't accidentally use them.

If this is something that people want, I'd be happy to help contribute.

**Comment by Hydrox6** [comment]
Wildcards work in Ground Items, so `Clue Scroll *` will match all clue scrolls.

**Comment by deathbeam** [comment]
This looks like it is already a feature.
