### ISSUE TITLE
Screenshot plugin

### ISSUE THREAD

**Issue by UniquePassive** [runelite/runelite#368]
- Takes screenshots automatically upon opening clue scrolls, completing quests, leveling up, getting barrows + raids loot and winning duels

- Adds a screenshot button to the side panel for manual screenshotting

- Allows to automatically upload screenshots to Imgur or equivalent image hosting site, and sets the clipboard by ``Toolkit.getDefaultToolkit().getSystemClipboard()`` to the image URL after upload

- Saves screenshots in user.home/.runelite/screenshots:
```java
new File(RuneLite.RUNELITE_DIR, "screenshots")
```

---

Using java.awt.Robot might work for taking the actual screenshot (code inserted into ClientUI):

```java
public BufferedImage takeScreenshot() {
    try {
        Robot robot = new Robot();
        Rectangle bounds = this.getBounds();
        return robot.createScreenCapture(bounds);
    } catch (AWTException e) {
        throw new RuntimeException(e);
    }
}
```

**Comment by Adam-** [comment]
Done in #395
