### ISSUE TITLE
Add charge value to weapons in worn item inventory

### ISSUE THREAD

**Issue by TheStonedTurtle** [runelite/runelite#3683]
Add a counter that shows how many charges until your weapon degrades (I.E. Trident, Archlight, Tentacle, Ibans Staff, Etc) similar to how the slayer helmet overlay looks (example: ![](https://i.imgur.com/h4oZxOR.png) )

**Comment by Alexsuperfly** [comment]
basically duplicate of #953

**Comment by Nightfirecat** [comment]
I don't think that's the request--as I understand it, this is simply a request to show the charges for any equipment we track charges for when on the equipment tab in addition to on the inventory tab.

**Comment by deathbeam** [comment]
Both are requests to show charges for items with charges, so closing as duplicate of #953
