### ISSUE TITLE
Player Indicators - Wild Only Toggle

### ISSUE THREAD

**Issue by TheTurtle42** [runelite/runelite#3684]
Would it be possible to add a toggle that allows the player indicator feature to only work in the wild? 

I find the feature very useful for quickly spotting pkers, but can be annoying when not in the wild. I find myself having to change the configuration every time I move between wild and non-wild.

Thank you!

**Comment by DannysPVM** [comment]
Yes it is possible @TheTurtle42. Here is what I've done to the plugin so that it only shows player indicators in the wilderness. Will PR this soon.

_Demo Player Indicators - Wild Only Toggle_
 https://puu.sh/ABd9I.gif

**Comment by TheTurtle42** [comment]
Awesome! Exactly what I had in mind.

Thank you, DannysPVM

**Comment by DannysPVM** [comment]
No problem, glad I was able to help. :)

**Comment by deathbeam** [comment]
Same as a lot of previous similar requests. You can just re-configure the plugins based on what you are doing, adding auto-config option for every niche case seems counter-productive.

**Comment by picocode1** [comment]
so where is the option for this?
