### ISSUE TITLE
Bank tags disappear

### ISSUE THREAD

**Issue by Chobotek** [runelite/runelite#3689]
I use 2 accounts and have 2 emails to switch between individual settings. I use bank tags on my main account, but they all get deleted on a regular basis.

**Comment by Abextm** [comment]
Could it be #3561

**Comment by Chobotek** [comment]
it's for all my items tho

**Comment by Chobotek** [comment]
that's for 1 item. But I have all the bank tags for my items get deleted

**Comment by Chobotek** [comment]
oh and sorry for the bird house duplicate

**Comment by raiyni** [comment]
Any more information on this or can it be closed without more information?

Maybe it's related to your config being reset.

**Comment by deathbeam** [comment]
I bet this is related to config being reset, as no more informations were provided I will just close this
