### ISSUE TITLE
NMZ overlay active in KBD private instance

### ISSUE THREAD

**Issue by williammetcalf** [runelite/runelite#3692]
KBD lair is the same region as NMZ, so the points overlay is showing up

[![https://gyazo.com/512afc360389590644b75a198f6b0215](https://i.gyazo.com/512afc360389590644b75a198f6b0215.png)](https://gyazo.com/512afc360389590644b75a198f6b0215)

**Comment by Adam-** [comment]
The fix for this was backed out in ff7f06dffdda3f20bf12214a715c9adc29251a4c as it is breaking the notifications.
