### ISSUE TITLE
Swap "Talk-To" with "Pickpocket" for Guards/H.A.M Store Room Guards

### ISSUE THREAD

**Issue by skossan** [runelite/runelite#3693]
I'm always frustrated that I have to right click to pickpocket the HAM guards when I try to get some keys for the jewellery chests. 

The best solution would be to make a toggle so that we can swap the talk-to button with the pickpocket button

Thanks in advance.

**Comment by skossan** [comment]
Thanks. There don't seem to be a solution in that thread. I reckon this change isn't difficult to make so hopefully someone will be able to do it. I'd do it myself if I knew how. Thanks for linking me that.

**Comment by Jasper-ketelaar** [comment]
This should be working? Check the Menu Entry Swapper plugin.

**Comment by skossan** [comment]
I have done several times but it's not working for me at all sadly.

**Comment by Hydrox6** [comment]
@Jasper-ketelaar the current HAM menu entry swap is just for the Men and Women commonly used to obtain Easy Clue Scrolls, and not the HAM guards for the storerooms.

**Comment by skossan** [comment]
@Hydrox6 Is this something that can be added? It would be a huge help for the ironmen out there.

**Comment by Jasper-ketelaar** [comment]
@skossan What are the menu options for H.A.M guards? The code just checks if the name contains h.a.m so they should be functional unless their menu entries are different.

**Comment by skossan** [comment]
@Jasper-ketelaar The menu option just says "Pickpocket Guard (level-22)"

**Comment by Jasper-ketelaar** [comment]
Ah they're named Guard and not H.A.M. Guard as I thought they were.

**Comment by skossan** [comment]
@Jasper-ketelaar Is this something you'd be able to fix?

**Comment by Hydrox6** [comment]
For now this is not something that will get into the client, sorry. Adam does not feel comfortable adding it due to the OP potential of the Menu Entry Swapper

![discordptb_2018-06-08_20-54-10](https://user-images.githubusercontent.com/2979691/41178135-45deb7a2-6b5e-11e8-8fe7-d34dcc9667ff.png)
