### ISSUE TITLE
client.isFriended(String name, boolean mustBeLoggedIn) is returning true when the local player is passed in the first argument

### ISSUE THREAD

**Issue by bmiddle** [runelite/runelite#3694]
| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.0_171
| Operating System | Windows 10

# Problem
Calling `client.isFriended()` by passing the name of the local player returns true, despite the fact that you cannot add yourself. Only workaround currently is doing a winded second check if the local player's name equals the name of the player being passed through.
This was found after PR #3677 (to add ability to change the color of friends in public chat) was created but was amended to have a quick check before any merging could happen. Here's a screenshot with debugging messages:

![Image demonstrating isFriended with local user passed through](https://i.imgur.com/Hhaazos.png)

On the right, I set the friend names to be colored red if they show in opaque public chat. I sent a message and also logged what the problematic code is with its result printed after it.
# Reproduction
Call `client.isFriended("your name here", true)` while logged into OSRS.

# Fix
We can fix this by modifying the method's logic.

**Comment by bmiddle** [comment]
```
@Inject
@Override
public boolean isFriended(String name, boolean mustBeLoggedIn)
{
	RSName rsName = createName(name, getLoginType());
	return getFriendManager().isFriended(rsName, mustBeLoggedIn);
}
```
The only implementation I found is under `RSClientMixin.java` at line 587, displayed above. The friend manager points at an interface method that isn't implemented so I'm not sure where to go there, would it be better to check the client itself immediately and check if the local player equals the name passed through. My suggested fix could be:
```
public boolean isFriended(String name, boolean mustBeLoggedIn)
{
	if (client.getLocalPlayer().getName() == name) return false;
	RSName rsName = createName(name, getLoginType());
	return getFriendManager().isFriended(rsName, mustBeLoggedIn);
}
```

**Comment by deathbeam** [comment]
This looks like correct behaviour to me
