### ISSUE TITLE
Game message when you unlock a new song

### ISSUE THREAD

**Issue by SolveSoul** [runelite/runelite#3697]
It'd be cool to have a message whenever you unlock a new song. This was implemented in RS2 back in the day and it was a neat feature. Especially for music cape hunters!

I've got the Runelite project checked-out locally and I've already been able to add a new plugin and show an in-game message in the same format as in the screenshot below. So I'd be able to implement myself, if it wasn't for the fact that I have no clue how to query the currently (un)locked songs or receive an event whenever a new song is unlocked.

I've also been playing around with the varbits dev-tool but alas, I didnt' figure it out (yet).

Any pointers are appreciated or if someone else would like to implement this.

Thanks!

Example from RS2/3: https://imgur.com/K5G8IOE

**Comment by rctgamer3** [comment]
This would be a useful feature.

**Comment by Adam-** [comment]
The logic the client uses to build the music interface is:

```
for (i:=0;i<lenEnum(818);i++)
{
    widget := createDynamicWidget(parentWidget, TEXT, i)
    songID := enum818[i]
    songName := enum812[songID]
    widget.setText(songName)
}
```

To test unlock status use `enum819[songId]` to get a packed `varId` and `bitshift`: https://github.com/RuneStar/cs2-scripts/blob/master/scripts/[clientscript,music_init_component].cs2#L27
