### ISSUE TITLE
PMod Public chat not being recolored via "Chat Color" plugin

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#3703]
Probably something to do with how PMod chat used to bypass public filter (different chat type)
Not sure if this happens with CC or PMs
![image of public chat](https://i.imgur.com/oghy6pg.png)

**Comment by Hydrox6** [comment]
PMod Public chat is the ChatMessageType 22 (which we don't support atm)

![2018-06-09_03-28-54](https://user-images.githubusercontent.com/2979691/41186838-90ed8534-6b95-11e8-99b3-5ced9866b5f1.png)
![2018-06-09_03-27-17](https://user-images.githubusercontent.com/2979691/41186835-8f1aa642-6b95-11e8-900d-c9c0ccc0da75.png)

**Comment by Hydrox6** [comment]
PMods use type 1 for Public (unsupported before PR 3706), 7 for PMs, and 9 for CCs. This was (surprisingly) the only type that wasn't supported.
