### ISSUE TITLE
[Master Clue] Hot/Cold @ East of Watson's house too far north

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#3708]
https://i.imgur.com/Of1ej6A.jpg

Dig site should be where the marked tile is. Current spot is a touch too north.

**Comment by Nightfirecat** [comment]
So that's 4 tiles too far north?

**Comment by Jalopyy** [comment]
Looks like it, yea.

**Comment by deathbeam** [comment]
Fixed in #3780

**Comment by Nightfirecat** [comment]
Damn, I thought mentioning `fixes so-and-so-issue` from the commits would've been enough. I'll add that to the description next time.
