### ISSUE TITLE
Zulrah

### ISSUE THREAD

**Issue by artrown** [runelite/runelite#3710]
a plugin would be very good that would make it easier to see the rotations of the zulrah

**Comment by Shieldeh** [comment]
There was one, however it was removed as Jagex did not want it in the client. Have a look at https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features to make sure what you are requesting hasn't already been rejected/removed.

**Comment by Abextm** [comment]
Duplicate of #1386
