### ISSUE TITLE
Hot/Cold clue location southeast of chaos temple not working

### ISSUE THREAD

**Issue by 000000653** [runelite/runelite#3711]
The hot and cold helper for the area southeast of the western chaos temple in the wilderness highlighted a tile to dig that was outside of the zone that would trigger the brassican mage to spawn. This caused the hot and cold helper to say that there were no possible areas left where the correct place to dig could be.
![runelite_2018-06-09_04-53-29](https://user-images.githubusercontent.com/40111569/41190742-0737e87e-6baa-11e8-8571-d467c2ed7cee.jpg)

No errors were shown in the logs, and I was able to recreate it multiple times by using the strange device somewhere else, and then going back to the dig spot and using it there again.

**Comment by xDemoN** [comment]
#6990 fixed this, please close
