### ISSUE TITLE
Screen Markers issue

### ISSUE THREAD

**Issue by YungSephi** [runelite/runelite#3716]
Hi,

There is a problem with Screenmarkers.
If you play in resizable mode and you make screenmarkers as an example in your inv (ring slot)
after closing the client and re-opening it, the screenmarker you made for the ringslot moved to the topleft corner.

**Comment by Hydrox6** [comment]
A work around for now is to hold Alt and drag the marker. However, this is still something that should get solved in the long term

**Comment by Adam-** [comment]
Duplicate of #3571. It is due to the client thinking they are off-screen and repositioning them.
