### ISSUE TITLE
Theatre of Blood features that Jagex probably wouldn't mind

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#3720]
I know we're not allowed to make Theatre of Blood plugins, but there are few features that we could add that wouldn't be the OP stuff that Jagex will be worrying about.

* Loot chest value, like the Barrows chest. Could be only for the final (Monumental) chest, or for all of them.
* Raid timer and/or boss timer, either on the Report button or as an infobox. I think the raid is timed by boss kill time only, so the code would be a little different.
* Custom Health orbs to replace the vanilla ones, so that they could be moved, and could also show the full names of the party members (would help for parties running 2 or more user with the same first letter)

**Comment by MagicfTail** [comment]
And something to screenshot your loot and or kc

**Comment by Pashweetie** [comment]
maybe we could also add your party members live hp (don't know if we have the API to support it but im sure we could figure it out somehow)

**Comment by Hydrox6** [comment]
Wow, it's been a while. Turns out all of these now exist in some form

* The Loot Tracker now shows the value of the rewards (the mechanics of the normal chests were changed after release, so the second half of the sentence doesn't make sense)
* There is now a hub plugin to show time splits for the raid (`Theatre of Blood Stats`)
* There is a hub plugin to use health bars instead of the vanilla health orbs (`Tob Health Bars`)
