### ISSUE TITLE
Dharok Rapid heal notification

### ISSUE THREAD

**Issue by alexbowers** [runelite/runelite#3726]
**Is your feature request related to a problem? Please describe.**
When using Dharok's you want to keep it on 1hp using rock cakes at a roughly 50 second interval flicking Rapid heal. A notification when we are ~ 10 seconds away from health regen'ing would be a good notification

**Describe the solution you'd like**
A notification which alerts when we need to flick the prayer.

**Comment by Jasper-ketelaar** [comment]
#3427 has this almost exactly as you described.

**Comment by alexbowers** [comment]
Ah yes, sweet.
