### ISSUE TITLE
Add counter for fungicide spray

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#3727]
**Is your feature request related to a problem? Please describe.**
When slaying Fungis it is nice to know how much Fungicide is in a sprayer.

**Describe the solution you'd like**
Counter for this like the slayer ring or the teleport items.

**Describe alternatives you've considered**
Not applicable

**Additional context**
![image](https://user-images.githubusercontent.com/9074448/41202322-c5ca2130-6cc7-11e8-9d50-69fa0f6642ee.png)

**Comment by Adam-** [comment]
Added in #3701

**Comment by Gamer1120** [comment]
Damn, that was fast. Thanks Adam!

**Comment by Gamer1120** [comment]
O, I should be thanking Mitchell. Thanks Mitchell!
