### ISSUE TITLE
Show Runecrafting altars on the map

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#3736]
It would be nice to know where the Runecrafting altars are when looking at the minimap. I suggest placing a marker on each mysterious ruins to indicate which altar it is.

**Comment by Abextm** [comment]
Why?

**Comment by Gamer1120** [comment]
Why not? I mean, there is no reason for there not to be markers on the altars.

**Comment by Abextm** [comment]
Because its something we would have to write, maintain, and provide support for.

**Comment by Gamer1120** [comment]
Alright. Feel free to close if you believe this adds nothing to the client.
