### ISSUE TITLE
Item Prices only showing inventory prices with bank open

### ISSUE THREAD

**Issue by Meako** [runelite/runelite#3738]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | x.y.z
| Operating System | e.g. Ubuntu/Windows/MacOS

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by Hydrox6** [comment]
There's an option in `Item Prices` called `Hide Tooltips on Inventory Items`. You probably have this on.

Also, don't put your issue inside \ tags, as they can't be seen.

**Comment by Meako** [comment]
I don't know why that was checked on it never was before, thank you so much lol.

**Comment by Hydrox6** [comment]
In future, questions like this should be asked in the Support channel in the RuneLite discord.

**Comment by Nightfirecat** [comment]
This can be closed.
