### ISSUE TITLE
Improper new line in public chat

### ISSUE THREAD

**Issue by LeviSchuck** [runelite/runelite#3739]
Not sure if this is present in the vanilla client, but it seems that there's an unnecessary new line at the beginning of a long message of only `11111..` 

<img width="496" alt="screen shot 2018-06-10 at 9 15 34 pm" src="https://user-images.githubusercontent.com/245911/41209849-a25eda2a-6cf3-11e8-88a9-fb5e397b38a9.png">

**Comment by Nightfirecat** [comment]
I think this is vanilla client behavior.

**Comment by dekvall** [comment]
This is vanilla behavior. Jagex tries to wrap around whitespace if the message is too long, so if you prepend a message that is too long with a space, the described behavior can be observed. By putting a space somewhere in the end part of the message you can actually get two improper newlines as it will try to wrap on that one as well. 

![improper_whitespace](https://user-images.githubusercontent.com/25151927/67856530-08adbe80-fb15-11e9-92d6-d628359b4e11.png)
