### ISSUE TITLE
Incorrect menu entry order after get and set of client menu entries

### ISSUE THREAD

**Issue by XrioBtw** [runelite/runelite#374]
The following code will give incorrect menu entry order:
```
@Subscribe
public void onMenuEntryAdded(MenuEntryAdded event)
{
    client.setMenuEntries(client.getMenuEntries());
}
```
![runelite_menu_entries_problem](https://user-images.githubusercontent.com/33559295/34911845-933a6b94-f8d2-11e7-8bb5-d0774cc9f89c.png)

**Comment by XrioBtw** [comment]
#388 will not fix this issue. A complete MenuAction enum will prevent dead menu entries, but it will not fix the menu entry order.

**Comment by XrioBtw** [comment]
I think we need to figure out where the last menu entry is being re-ordered. Normally, the menu entries are added like this:
"Cancel", "Walk here", "Chop down Tree", "Examine Tree"
but ends up as this:
"Cancel", "Examine Tree", "Walk here", "Chop down Tree"
 This also makes it so that the following code 
```@Subscribe
public void onMenuEntryAdded(MenuEntryAdded event)
{
    MenuEntry[] entries = new MenuEntry[0];
    client.setMenuEntries(entries);
}
```
will end up as a menu with "Examine Tree" rather than being empty.

**Comment by tylerthardy** [comment]
I've been looking at it as well, but not enough. This may help: You can eliminate "Examine Tree" by having the `addMenuEntry` hook run after the RS api method via this change in the Export code:
```@Export("addMenuEntry")
@Hook(value = "addMenuEntry", end = true)
public static final void addMenuEntry(String var0, String var1, int var2, int var3, int var4, int var5) {
   Varcs.method1806(var0, var1, var2, var3, var4, var5, false);
}
```

**Comment by XrioBtw** [comment]
Adding
```
@Hook(value = "addMenuEntry", end = true)
```
to the addMenuEntry export in NPCComposition.java will (almost) solve this issue.
For the most part the menu entry order will now be correct, only with a few exceptions like re-ordering "Walk here" and "Cancel". Menu entries like "Cancel" and "Examine X" might be treated differently due to their specific menu positioning. "Cancel" will seemingly always go to the bottom even if you add it to the top of the menu. "Examine X" is seemingly always added last to the menu, but ends up as the second entry from the bottom in the menu. I will close this issue if someone else can approve that changing the hook to the end will fix this issue and not cause other problems I don't know about.

**Comment by ShaunDreclin** [comment]
Meant to post this earlier, might be helpful.

![Context menu ordering](https://user-images.githubusercontent.com/5851433/36235200-374ed6e0-11bd-11e8-92fc-712b1191e53f.png)

There is clearly some sort of special case for examine, seeing as it's added last but shuffled to the bottom of the list instead of the top, which seems to be the default position for new entries.

Walk here doesn't actually need to be re-ordered since it's added to the list first, at least in my testing,

Cancel doesn't even trigger the event, so I'm thinking it's hard-coded into the context menu.

**Comment by Adam-** [comment]
This is due to not having MenuActions for everything. Some more were added since this. They should be added as encountered probably.
