### ISSUE TITLE
Craft all option as first

### ISSUE THREAD

**Issue by Meako** [runelite/runelite#3741]
**Describe the solution you'd like**
Craft all as first option for when making things such as jewelry, I know it's such a small thing but would feel extremely useful.

**Comment by Pashweetie** [comment]
Im interested in making this work, first project on runelite so i'll see.

**Comment by Pashweetie** [comment]
Done implementing!

**Comment by deathbeam** [comment]
```
Menu reorder in shop/artisan skill screens: Other clients don't implement these swaps, and would be too strong for numerous activities (examples include "Buy-50" swaps, "Make All" swaps for smithing/crafting, etc.)
```
