### ISSUE TITLE
Runelite settings Import/Export

### ISSUE THREAD

**Issue by shermaza** [runelite/runelite#3748]
**Describe the solution you'd like**
Add an option to the Runelite plugin panel to import or export Runelite settings to/from a text file. Stretch goal would be to allow partial imports/exports by plugin or by setting, i.e. I can only share my drop highlight list if I desire.

**Describe alternatives you've considered**
Share settings to other people via a link to a Runelite profile page from your RL client if you are logged in.

**Additional context**
I see people asking "How can you do this in Runelite" or "Can I get your setup". This issue is requesting a possible solution to that problem.

**Comment by TheStonedTurtle** [comment]
`C:\Users\*NAME*\.runelite\` has a file `settings.properties` which holds all this information.

**Comment by nguyetr3** [comment]
but `settings.properties` contain username. So i dont think is safe share with someone that file. 

`rememberusername.username=XYZABC@KLMN.COM`
`farmingTracker.XYZABC@KLMN.COM.12594.4771=8\:1528866648`

**Comment by Nightfirecat** [comment]
With the addition of config profiles in 831189459ba51538b239a33b7d632bd2d9e4e8a3, you can export and import profiles. Account-specific settings are saved separately from config profiles, so for any sufficiently-new profile (which doesn't have legacy data/keys), they would not be exposed or shared.
