### ISSUE TITLE
NPC Quest Start Location

### ISSUE THREAD

**Issue by supermxn** [runelite/runelite#3749]
I was wondering if we could add a plugin it shows where you can start the quest by adding a tile or arrow in the image.
![image](https://user-images.githubusercontent.com/10204414/41263093-f5d3c20c-6da1-11e8-95f6-d9db946cb72f.png)

I believe this will help new players that want to start quests, most of the time the new player have a struggle finding their quest start locations. To activate the where the quest will start, we could hold SHIFT + Click on any quest then the world map will appear showing where it is.

**Comment by Felanbird** [comment]
[Quest Helper](https://runelite.net/plugin-hub/show/quest-helper) was added as a plugin from the hub about 4 years ago
