### ISSUE TITLE
Loot Blocker

### ISSUE THREAD

**Issue by Feature-Request** [runelite/runelite#3752]
**Is your feature request related to a problem? Please describe.**
Picking up unwanted items by mistake. Ex. bones, ashes & vials.

**Describe the solution you'd like**
A menu entry swapper feature that hides bones/ashes/vials.

**Describe alternatives you've considered**
'Walk here' as first option, rather than the 'take' option.

**Additional context**
The Loot Blocker feature would only block certain unwanted items like different bone types/ashes/vials.
To combat looters, the feature could be blocked in PvP situations, whether it's the wilderness or PvP worlds. This would also allow the feature to have a wider variety of items that could be blocked.

**Comment by Gamer1120** [comment]
Relates to or duplicate of #1711

**Comment by bmiddle** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features last bullet point

**Comment by Nightfirecat** [comment]
This can be closed, it's a feature on the rejected/rolled-back wiki page as mentioned above.
