### ISSUE TITLE
Chat notifications sends own name notification without option enabled

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#3755]
With `Highlight own name` enabled, it sends a notification even with `Notify on own name` disabled.

**Comment by Nightfirecat** [comment]
I wasn't able to reproduce this on current code. I believe 0d70ae4144fa8b424ad83a5386ed2a50f7e3ca2f fixed this issue.

**Comment by Kamielvf** [comment]
Yes, judging from that code it should have fixed it. I remember the brief discussion in discord about it too.
