### ISSUE TITLE
Game size (width) not restored when selecting "Remember client position"

### ISSUE THREAD

**Issue by Mollerz** [runelite/runelite#3757]
| Question    | Answer
| ------------| ---------------
| Java Version | V8 Update 171 (build 1.8.0_171-b11)
| Operating System | Windows

Game width does not restore when saved and locked upon re-opening RuneLite. I am using RuneLite on my secondary monitor on a two monitor setup. RuneLite configuration and how I keep my game window shown below - I leave the icons open on right hand side but minimise them when not in use. https://github.com/runelite/runelite/pull/3499 does not appear to have fixed this.

![](https://i.imgur.com/EiGt0jJ.png)
![](https://i.imgur.com/VZQlpi7.png)

**Comment by deathbeam** [comment]
This should be working now.

**Comment by deathbeam** [comment]
If you have both remember client position and game size option enabled, remember client position will simply overwrite it (because it is also remembering client size, not only position).

**Comment by Mollerz** [comment]
Surely this now becomes a feature request then, allow client position to be remembered whilst using game size option? 

Seems silly that I want to be able to just save the client position to the top right of my second monitor, however if I choose remember client position then I have to resize it each time, and if I decide to keep game size then I have to drag it to position.

**Comment by Mollerz** [comment]
@deathbeam Sorry I don't want this to be forgotten since it seems like a bit of an oversight.

**Comment by deathbeam** [comment]
Create new issue to add separate option for remembering game size and game position then I guess.
