### ISSUE TITLE
Fight Caves wave content

### ISSUE THREAD

**Issue by Reasel** [runelite/runelite#3772]
**Is your feature request related to a problem? Please describe.**
When in the fight caves I am tired of having to have an extra browser window open showing the content of the waves

**Describe the solution you'd like**
I would like to see in the chat where it tells you what wave you are on also tell you the monsters you will have to fight.

**Describe alternatives you've considered**
The alternative is having the wiki up listing every wave and following along as you play.

From the wiki:
Wave 23.) 180, 90, 22
Wave 24.) 180, 90, 22, 22
Wave 25.) 180, 90, 45
Wave 26.) 180, 90, 45, 22
Wave 27.) 180, 90, 45, 22, 22

Would appear in game as:

Wave: 23 - 180, 90, 22
OR
Wave: 23 - 180(Yt-MejKot), 90(Tok-Xil), 22(Tz-Kih)

**Comment by Nightfirecat** [comment]
This should be implemented in #3356, once merged
