### ISSUE TITLE
Pre Eoc Healthbars

### ISSUE THREAD

**Issue by RatIrlL9** [runelite/runelite#3774]
**Is your feature request related to a problem? Please describe.**
Healthbars in the game looks like shit, if you played pre eoc I'm pretty sure there's tons of people who miss the health bars we once had too. It's a daily annoyance. 

**Describe the solution you'd like**
A toggle for on/off on pre eoc healthbars, just like you'd change interface styles

**Describe alternatives you've considered**
None as far as I'm aware? 

**Additional context**

Maybe create multiple lengths of healthbars for more precise guestimations of enemys health ?

**Comment by etiks** [comment]
This would go well with the 2010 gameframe. Support.
