### ISSUE TITLE
Missing help for crate clue (Ape Atoll).

### ISSUE THREAD

**Issue by xmatias** [runelite/runelite#3776]
There's no current help on this clue in the client.

Here's a picture which should have enough info so it can be added in the plugin.

![image](https://user-images.githubusercontent.com/14856681/41379921-47455f82-6f5b-11e8-9ab0-00f273b03125.png)

**Comment by Nightfirecat** [comment]
Duplicate of #3392, but the inventory ID will help fix this.

**Comment by deathbeam** [comment]
Fixed in #3777
