### ISSUE TITLE
On slayer masters, use menu swapper to change the left-click to 'Assignment'

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#3782]
Title. How often do people besides beginners trade slayer masters for stuff?

Alternatively, just change the menu swapper option to make a specific line for slayer masters, and make it a drop down list where you can choose which you want.

**Comment by Nightfirecat** [comment]
This will be implemented once #1864 is rebased and merged.

**Comment by deathbeam** [comment]
Implemented in #1864
