### ISSUE TITLE
[Master Clue] Hot/Cold 'South of Mausoleum' inaccurate

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#3783]
https://i.imgur.com/ofGI6UA.jpg

Move 3 west and 2 north. The solution place in the infobox goes away when you dig in the incorrect spot, so maybe that needs a fix too?

Not sure why so many of these are wrong, could it have been from when the dig places were swapped over overlaying a whole area to 1 tile?

**Comment by Nightfirecat** [comment]
All the spots are manually placed, and all of the work on the plugin was done by one person so it's possible they just didn't get some of them exactly right.

I'll look at fixing this one soon enough.

**Comment by Jalopyy** [comment]
That makes sense since I don't think there's any documented online resource that lists the EXACT dig spots.

**Comment by Pashweetie** [comment]
Pretty sure that the areas mapped out are generic areas because it can slightly differ from clue to clue. Gets you pretty darn close right off the bat though.
