### ISSUE TITLE
expeditious bracelet charge overlay doesn't reset to 30 after breaking one

### ISSUE THREAD

**Issue by abra238** [runelite/runelite#3787]

**Comment by sethtroll** [comment]
I've tested this, and it does in fact reset the value when I break one. It checks for the break widget text every game tick, and it's possible the widget was opened/closed before it was able to detect it.

**Comment by Alexsuperfly** [comment]
unable to reproduce, even exiting the message that says charge count reset as quickly as possible

**Comment by Nightfirecat** [comment]
@abra238 Are you able to reproduce this?

**Comment by Nightfirecat** [comment]
I think we're safe to close this one for the time being. Please comment if this is coming up again and we will re-investigate.
