### ISSUE TITLE
add ability to hide menu listings of items under 'ground items'

### ISSUE THREAD

**Issue by abra238** [runelite/runelite#3790]
would be useful at places like nechryaels because of the ashes filling up the whole screen with menu listings. There could be a separate list for this, and an option to either always apply, or only apply when the price of the item/stack is below the hidden value. This could quickly be modified like highlights/hiddens with a button when holding alt [-][+][x]

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
