### ISSUE TITLE
Fairy ring clickboxes

### ISSUE THREAD

**Issue by nguyetr3** [runelite/runelite#3792]
I think is would be nice if possible highlight clickboxes fairy ring

actually is really hard to click on fairy ring from distance while walk/run

**Comment by edgarsaurus** [comment]
This would be so useful.

**Comment by Gubzs** [comment]
This. So much this.

**Comment by honeyhoney** [comment]
I was thinking of adding a clickbox overlay to fairy rings in the Fairy Ring Helper plugin was I was wondering if it would be worthwhile creating some sort of generic "Clickbox Plugin" through which players could choose specific objects to show the clickbox for and maybe have a few presets such as fairy rings?
