### ISSUE TITLE
Sidebar glitch

### ISSUE THREAD

**Issue by jwc17** [runelite/runelite#3803]
https://i.gyazo.com/1178706ca40511afec9aed9d14839254.mp4

My sidebar is glitched and I can't use it. I just started using runelite and i've been experiencing this issue since I first downloaded it. Any fixes?

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
