### ISSUE TITLE
Show icon when Vengeance is active

### ISSUE THREAD

**Issue by Ryshoe** [runelite/runelite#3809]
**Is your feature request related to a problem? Please describe.**
Not able to accurately tell when Vengeance is active. This means wasted runes and inefficient use of cooldown time when casting it again while still active.

**Describe the solution you'd like**
An icon to be displayed in the boost area of the UI which shows when Vengeance is active.

**Describe alternatives you've considered**
Changing how the Vengeance icon in the spellbook is displayed when Vengeance is active, such as graying the icon, adding an outline, or changing the color.

**Additional context**
Konduit has this feature using the Vengeance icon with a plus sign displayed where boosts are shown.

**Comment by deathbeam** [comment]
This is already a feature, check "Timers"  plugin.

**Comment by deathbeam** [comment]
Ah you mean after you cast the spell.

**Comment by Pashweetie** [comment]
I might be willing to implement this although the graphics side will be more challenging for me :P

**Comment by Jasper-ketelaar** [comment]
Vengeance lasts until you take damage/log out. I agree it would be nice to have an infobox that shows you whether or not it's still active. If you just put the vengeance icon in an infobox without the timer, would that be enough of a difference to easily distinguish them?
