### ISSUE TITLE
Add a kitten status indicator

### ISSUE THREAD

**Issue by slazum** [runelite/runelite#3815]
Can you please create a plugin for kitten status? 

A screen overlay which basically says:
Kitten hunger: really hungry
Kitten attention: Fine

Using a red amber green colour indicator on text

Any information about time until it becomes a cat would also be great

This would be amazing for ironmen 

Thanks!

**Comment by ypperlig** [comment]
There is a PR that implements this functionality at #2894

**Comment by slazum** [comment]
Thanks for linking this, I’m really new to github and runelite.

Can you explain or link to me how to install plugins like this?

Also, are the plugins that need to be downloaded seperately to the official client vetted and checked before being allowed on here?

**Comment by ypperlig** [comment]
There isn't an easy way for you to use it without building the client yourself. Yes, all pull requests are reviewed and approved before they are added to the official client.

**Comment by WolfAttacks** [comment]
I really really would like to use this plugin for my Runelite. How can I add it? Very thankful for help, thanks!

**Comment by LlemonDuck** [comment]
If you see the referenced pull request, the author deleted their repository, and the recommended action for future development was to make a new external plugin. I don't believe anyone has done so yet. 

Please don't resurrect old issues just to express interest in a feature. Just add a 👍 to the original request instead.

**Comment by Nightfirecat** [comment]
This is addressed [by the kitten-tracker hub plugin.](https://github.com/pieterjanbuntinx/kitten-tracker)
