### ISSUE TITLE
Ground items plugin is broken

### ISSUE THREAD

**Issue by Mantas1452** [runelite/runelite#3816]
I don't know why, but the ground items plugin has been changed and now it's horrible. If there's a workaround and I can go back to the old one please tell me.

The "Do not hide untradeables" option doesn't work at all. I want to see raids potions, kindling, etc. and I have to highlight them manually. If I highlight them, they become a different color, if I set the color to #FFFFFF or whatever the invisible is, there is no more highlighted items and my clue scroll might look like something that's valued over 10k that I don't want to pick up.

Currently you can enter a value on which items are HIGHLIGHTED, making the highlighted items list almost completely useless, as well as making everything you MIGHT want to pick up highlighted. If you set the value high enough, you can't see the stacks of stackable items that might cost less, but you still want to pick up as they accumulate.

If you block everything below a value, it grays out everything and it's just annoying and I still can't see untradeables...

**Comment by deathbeam** [comment]
Restart client.

**Comment by Mantas1452** [comment]
wtf? I did? It's the same shit...

**Comment by deathbeam** [comment]
Are you sure? the right-click greying out of items was temporarily removed to revert to old functionality, and the highlight > value was set to 0 to disable it.

**Comment by Mantas1452** [comment]
Could've just said that instead of "restart client".

Why was it changed in the first place? It was so good. It's hardly a workaround though. I had things like cave worms and such blocked. Now when I block and item, say like a bucket or something, it appears as normal. It was extremely handy.

**Comment by deathbeam** [comment]
I dont understand. The item hiding should still work as before yesterdays update. Same with item highlighting. Only thing that changed was the right-click menu greying out, addition of the highlight > value (that you can disable by setting it to 0) and that now highlighted items take priority over hidden items. Otherwise the plugin should work exactly same as before.

**Comment by Mantas1452** [comment]
I remember it being a show > value, not a highlight, it was super good. The things below ( https://i.imgur.com/RcU5Rmh.png ) are the highlights, and the items you highlight manually, the highlight > value feature is complete nonsense. The block < value feature is nice though, say I want to see everything above 10k as normal items and anything below 5k grayed out, I can do that. If I want to add a highlight to items with a certain value, say like 25k, I can go to the "low value price" and set it to 25k, now everything that's over 25k will be highlighted blue.

**Comment by deathbeam** [comment]
We never had show > value. But we have show only highlighted items if that is what you mean. Well yes, you are not forced to use highlight > value. It is mostly for people who like consistency and use only 1 option (as the price thresholds can be quite annoying to setup as you need to change 4 different values). I personally dont use the price thresholds and I set them all to 0 to disable them and so now I use highlight > value as the "low value" price, only difference is that I have only 1 color on ground.

**Comment by Kamielvf** [comment]
Could you list the steps to replicate your issue?

**Comment by Mantas1452** [comment]
https://i.imgur.com/Kd6Umn5.png

This is what I was after. But the temporarily part worries me, as I really like the old functionality of the plugin.

Something what I assume is unintentional, is that untradeables don't show when the options "do not hide untradeables" and "show only highlighted items" are selected. The untradeables are still hidden, and anything over a certain value gets a color, if you want that item to appear as a text. The "temporary fix" does fix the issue when you block < value for what you do not want and unselect "show only highlighted items".

This overall makes the tool an inconvenience to use, as you can't just display ground items as text over a certain value without giving them a color and if you remove the color, you give up a feature to highlight items manually. When the block < value feature reverts back to graying out items and you don't want that, you'll lose the ability to block and gray out certain items manually. Either way it's bad.

Plus, a highlight > value has existed all along, in fact, you could have multiple tiers of items and if you only wanted one tier, you could set 0 on the others to disable them. So this whole update to the plugin is just nonsense.

**Comment by deathbeam** [comment]
"Don't hide untradeables" means that hide < value filter do not applies to them. It has nothing to do with highlighted items. When option show only highlighted items is checked, obviously only highlighted items are shown.

I dont understand what is the problem here? Everything you mentioned is working as intented. The graying out items in right-click menu will be optional if reimplemented.
