### ISSUE TITLE
Add item information lookup

### ISSUE THREAD

**Issue by supermxn** [runelite/runelite#3822]
I would love to see a feature where you can see items Information when holding SHIFT + clicking on Examine. Example when you right click a Rune platebody then hold SHIFT + clicking on examine, the sidebar or a small box in game will appear showing stats of the Rune platebody. Why would this be useful? Well you could take off all your armour or google to see what stats that item gives. This feature can save time and it will be easily assessable.

Picture example: https://i.imgur.com/QeF0F9a.png

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/pull/2829 might be related, also probably way better implementation than suggested here.
