### ISSUE TITLE
Option to make Item overlay and moving overlays use shift and not alt

### ISSUE THREAD

**Issue by Caia-OSRS** [runelite/runelite#3826]
**Is your feature request related to a problem? Please describe.**
With the recent update to item overlay (which allows highlighting/hiding by clicking the item and not just the boxes), I am often mis-clicking on an item when using alt to move the camera around. As it is now, using alt with the client interferes with the function jagex has added to move the camera.

**Describe the solution you'd like**
I would like for there to be an option to change alt as the hot key for moving overlays and to show the item overlay. Shift makes sense to me with it already being used to mark tiles and npc.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by Caia-OSRS** [comment]
Anybody want to take a stab at this? If I could, I would :(

**Comment by Nightfirecat** [comment]
4f4c502b1796ca70c3830ee7e563b8b4e16a8037 was added to configure the drag hotkey.
