### ISSUE TITLE
RuneWatch/RS JUSTICE support

### ISSUE THREAD

**Issue by Fox4148** [runelite/runelite#3828]
For players that hate to get stolen their splits during raid or even if you ask yourself: should I really lend this item to that guy?

Just a notice in the chat or some way to tell the user that this guy should not be trusted (with STRONG-MEDIUM-SOME evidences) according to RS Justice webstie. That said I don't think they have an API yet.

**Comment by permedd** [comment]
There are two **RUNE JUSTICE** the other one is called **RuneWatch**, but i do agree we should have it on the side panel and just searches the name and has info about the player.

**Comment by Nightfirecat** [comment]
Not that I'm against a lookup feature of this sort, but this post reads more like an advertisement than a feature request given that there's no feasible way to implement this currently.

**Comment by Fox4148** [comment]
Advertisement or not, still good feature.

Http calls... They just have to return a JSON and you can do whatever then.

**Comment by Adam-** [comment]
This was discussed this morning in some length in Discord. One of the rune watch admins (which apparently rsjustice got merged into?) stated they didn't want to see it added:

```
Nibss: Its Runewatch's firm opinion that adding blacklisting functions to game clients is totally something we don't want to be involved with. It would be unwise for the site and i imagine unwise for Runelite too. Jagex have never been happy about targeted lists or things that directly target players
```

[This comment](https://github.com/runelite/runelite/issues/7128#issuecomment-450706477) from DB on a duplicate issue I still agree with completely.

**Comment by RuneWatch** [comment]
We have refactored our case system and are now able to support this feature.
Here's a case list you can use: https://www.runewatch.com/api/cases/list
If you would like to query a single rsn please let us know via twitter @RuneWatch or dm Will osrs#0480 on Discord.

(I do not wish to re-open an issue/request for this, so pick it up if you'd like to move forward with it)

**Comment by dekvall** [comment]
I will reopen this issue based on the previous comment, but I too agree with DB: relying on a 3rd party service flagging people as "bad" feels dangerous and i don't like it.

**Comment by Blackberry0Pie** [comment]
OPRS has a ban list plugin. I have a local stripped-down runelite port. Currently WDR discord has a bot that queries both RW and the WDR non-public spreadsheet. I was previously not comfortable releasing my port as it depended on querying a RW list scraped by an OPRS dev and WDR lists that that are NOT maintained. I talked to some devs at in WDR about fixing their lists and got mixed responses. Since RW now has an API for this one of those issues is solved.

**Comment by raiyni** [comment]
This has been added on the plugin hub.

**Comment by OSRSBotKiller** [comment]
Could we have a @RuneWatch equivalent but for bots? I could setup a donation page so your userbase could support us so I and many others can spend our time scouting for bots. We all want a Runescape without bots.
