### ISSUE TITLE
Make the clue overlay only show on hover-over

### ISSUE THREAD

**Issue by Grabbin** [runelite/runelite#3839]
**Is your feature request related to a problem? Please describe.**
Especially when in fixed mode, the clue overlay can take up a lot of your screen (pic for reference: https://i.imgur.com/9Vg2Gn2.png )

**Describe the solution you'd like**
Instead of the whole box, just show a small icon with a clue, when you hover over that, it brings up the whole text.

**Describe alternatives you've considered**
Maybe make it a toggle? Not sure.

**Additional context**
/

**Comment by Jasper-ketelaar** [comment]
I like having it open at all times. For fixing instances like this I think a better solution would be to hide the clue text considering it adds very little helpful information.

**Comment by Grabbin** [comment]
I can see how some people would probably like to keep it the way it is right now, so maybe an option in the clue scroll plugin to toggle the display?

**Comment by deathbeam** [comment]
With #6203 this request is no longer necessary
