### ISSUE TITLE
Cannot shift tag menaphite thugs

### ISSUE THREAD

**Issue by wilburx** [runelite/runelite#3844]
Cannot right click shift tag menaphite thugs (useful for blackjacking) but it is possible to add the NPC to the NPC tagging list by hand; however, this is undesirable since it tags all 50 thugs in the nearby location.

**Comment by Nightfirecat** [comment]
The issue with Menaphite Thugs specifically seems to be two-fold: their NPC object returns a composition with null fields for `NPC.getComposition()` unless transformed. Even after that point, they have no extra menu slots available to add a "Tag" slot to, meaning that it would only be possible if another menu option was first removed.
