### ISSUE TITLE
Focused client doesnt actively give you idle notification.

### ISSUE THREAD

**Issue by Pashweetie** [runelite/runelite#3850]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.151
| Operating System | Windows 7

2018-06-16 13:30:31 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-06-16 13:30:32 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-06-16 13:30:32 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by Nightfirecat** [comment]
Is this option set under the "RuneLite" configuration? https://github.com/runelite/runelite/wiki/RuneLite#send-notifications-when-focused

**Comment by Pashweetie** [comment]
This is still an issue not a question i understand how to mess with the configuration

**Comment by Nightfirecat** [comment]
@Pashweetie Can you be more clear? What case are you testing, what is the expected behavior of it, and what behavior are you experiencing instead?

**Comment by Kamielvf** [comment]
So, the issue here is "some things dont fire idle notifications when they should" or "some actions are missing idle notifications", and not an issue with the client being focused or not.

If i'm incorrect please elaborate your issue.

**Comment by Pashweetie** [comment]
You're right things such as battlestaffs and adding bolt tips either dont have api animations or dont have an animation change
