### ISSUE TITLE
Players with >99 levels in Lookup Tool

### ISSUE THREAD

**Issue by Saer-Dev** [runelite/runelite#3851]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | Unknown - I doubt it's relevant here
| Operating System | Windows 10 Pro 64-bit (version 1803)

I was looking up this guy who was woodcutting in the Zeah Woodcutting Guild and found that he has some pretty bizarre level readings ([see here for screenshot](https://image.prntscr.com/image/S0RQi58lSWCeiS_a3jo26Q.png)).  Not sure why this might be, perhaps something to do with calculating someone's level based on the amount of experience and not capping it at 99?  Just strange anyway and thought I'd bring it to your attention.

<details>
 <summary>stack trace</summary>
 
 ```
2018-06-16 23:30:58 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2018-06-16 23:30:59 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2018-06-16 23:30:59 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
 ```
</details>

**Comment by MagicfTail** [comment]
This is done on purpose, you can turn it off by toggling "Display virtual levels" in the HiScore plugin
