### ISSUE TITLE
Rouges HP Glitch

### ISSUE THREAD

**Issue by BigSmokesDip** [runelite/runelite#3863]
Hello doing some Wildy slayer when i noticed the HP bar for level 135 Rouges is broken
I assume its using the HP bar for the lower levels.
![glitch](https://user-images.githubusercontent.com/38731052/41509558-e7879204-724d-11e8-9757-990ac0543c14.png)

**Comment by Nightfirecat** [comment]
@Kamielvf Was this fixed with your PR?

**Comment by deathbeam** [comment]
Should be
