### ISSUE TITLE
Staff of the Dead Defensive Cast

### ISSUE THREAD

**Issue by SmuntBloke** [runelite/runelite#3865]
Unsure if there are any others but the Staff of the Dead and Toxic Staff of the Dead do not hide their defensive casting option when you have defensive options set to hide. I know Master Wand, Ancient Staff, and Ahrim's Staff all hide it properly.

**Comment by Nightfirecat** [comment]
Interestingly, if you equip a Staff of the Dead after equipping some other staff which has its defensive casting option correctly hidden, the bug doesn't present itself.

**Comment by SmuntBloke** [comment]
Awesome thanks! :)
