### ISSUE TITLE
Make Idle Notification Delay Apply To Combat Idle

### ISSUE THREAD

**Issue by Grehgous** [runelite/runelite#3867]
Currently combat idle notification sends an alert as soon as combat ends. This gets irritating if you are fighting aggressive monsters that Take 1 or 2 seconds for the next one to attack you. I can be tabbed out and still consistently fighting monsters but getting spammed with notifications. The way it is set up now I am unable to tell when they become non aggressive and when they are still aggressive.

I suggest either making the current notification delay time apply to combat idle too, or make a separate delay for combat.

**Comment by deathbeam** [comment]
The delay is already applied to combat too.
