### ISSUE TITLE
Elite emote clue scroll - Top of Slayer Tower

### ISSUE THREAD

**Issue by xmatias** [runelite/runelite#3871]
current code:
`		new EmoteClue("Headbang at the top of Slayer Tower. Equip a seercull, a combat bracelet and helm of Neitiznot.", new WorldPoint(3115, 3420, 0), HEADBANG, item(SEERCULL), item(COMBAT_BRACELET), item(HELM_OF_NEITIZNOT)),`

1st bug:
Combat bracelet (4) is not recognized on both inv and equipment menu.
![image](https://user-images.githubusercontent.com/14856681/41512275-d21d8d26-727d-11e8-8bd7-491c119d8dc6.png)

2nd bug:
Correct location:
![image](https://user-images.githubusercontent.com/14856681/41512287-fe616da8-727d-11e8-9b6b-590e13bf17c9.png)

**Comment by Nightfirecat** [comment]
I'll write a fix for these today or tomorrow.
