### ISSUE TITLE
Binding necklace- Destroy issue

### ISSUE THREAD

**Issue by Pingdrops** [runelite/runelite#3874]
| Operating System | /Windows 10

When I use binding necklace and destroy it, the client doesn't seem to register it's been destroyed so the charges stay the same. It changes the display on the necklace when I use a new binding necklace to '?' untill the next one goes to the number of charges the previous binding necklace was at. Kind of hard to track when i'm trying to use the necklace to disintegrate with every two duelling rings for Runecrafting.

**Comment by iBelg** [comment]
You can right-click and press "Check" to update the counter. This can be used as a work around until someone finds a proper solution.
