### ISSUE TITLE
Runelite creates windows folders in my home folder on Linux

### ISSUE THREAD

**Issue by BartWillems** [runelite/runelite#3878]
| Question    | Answer
| ------------| ---------------
| Java Version | openjdk version "1.8.0_172"
| Operating System | Arch Linux btw

Runelite creates 2 folders in my $HOME dir:

* $HOME/"C:"
* $HOME/"C:\\Users\\Adam"

In the "C:\Users\Adam" folder, there is a .runelite folder, which has a logs dir.
This folder has a launcher.log, which just contains some update logs.

**Comment by deathbeam** [comment]
Update your launcher to latest version.

**Comment by BartWillems** [comment]
But my name is not Adam :thinking:

**Comment by deathbeam** [comment]
Yeah, this was known issue that was already resolved, but, you need to manually update the launcher.

**Comment by BartWillems** [comment]
Ah okay, thanks!
