### ISSUE TITLE
Mark herbiboar before marking start of trails in herbiboar plugin

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#3881]
**Is your feature request related to a problem? Please describe.**
When I'm doing herbiboar using the plugin, I sometimes just click the next thing the plugin shows me. Currently, when there is a herbiboar on the ground, it will mark the start of the trails, instead of the herbiboar.

**Describe the solution you'd like**
Once the trail is complete, mark the herbiboar. Once the herbiboar is harvested, mark the start of the trails.

**Describe alternatives you've considered**
None.

**Additional context**
Not applicable.

**Comment by kulershk** [comment]
Duplicate #1899
