### ISSUE TITLE
Raise/remove Framerate Cap (apparently it's all in the camera?)

### ISSUE THREAD

**Issue by Tylemagne** [runelite/runelite#3890]
50FPS caps suck. It's not 2003 anymore. Many players even have 75 or 144Hz monitors.

I'd like to see if this can be removed. According to Mod Atlas, it's really all in the camera: https://twitter.com/JagexTitan/status/868882850023604224

I read through the camera code, but didn't see anything to do with time slicing or fixed iteration rates, it's all just the camera logic that another class probably calls: https://github.com/runelite/runelite/blob/master/model-viewer/src/main/java/net/runelite/modelviewer/Camera.java

I do realize that the new renderer may have no cap, but it'd still be nice to see it complete and in the client (if possible). I don't know if this is something RuneLite could even have control over, but seeing as OSBuddy replaced their entire renderer, I don't see how removing the cap for the software renderer would be trouble.

It could also be that when the new renderer does come out, the code written to remove the cap from the software renderer could help make any would-be caps removable from the next one as well.

**Comment by deathbeam** [comment]
I dont think this is possible. We would need to wait for Jagex hw renderer.

**Comment by NataIynn** [comment]
This is from 2018 -facepalm.

**Comment by Adam-** [comment]
We added this in the 1.8.0 release https://runelite.net/blog/show/2021-10-28-1.8.0-Release
