### ISSUE TITLE
Runelite Client get's cut off

### ISSUE THREAD

**Issue by Romaniann** [runelite/runelite#3899]
| Windows |

My Client has been getting cut off recently when the window is maximized, before it was the bottom half so it didn't really bother my gameplay experience and I ignored it, but now its the top half and I can't even see the minimize or exit buttons, as well as the settings tab, I tried uninstalling and reinstalling Runelite and the problem still persisted. 
![runelite bug](https://user-images.githubusercontent.com/40387781/41590792-c39b540a-736c-11e8-8de4-306a7c9b5c7e.png)

**Comment by deathbeam** [comment]
You can try disabling custom window chrome probably

**Comment by deathbeam** [comment]
Is this still an issue?

**Comment by Zypher232** [comment]
I'm having this exact issue. Any fix? I'v reinstalled the client multiple times now and no dice.

**Comment by raiyni** [comment]
Try disabling hardware acceleration or custom chrome.

**Comment by Zypher232** [comment]
Just to update, I couldn't figure out how to disable my hardware acceleration since my PC did not have the option for whatever reason. I went ahead and updated my graphics driver and it seemed to fix it. Thanks for your help.

**Comment by deathbeam** [comment]
Then it was HW accel related and we can close this I guess
