### ISSUE TITLE
Customizable window size.

### ISSUE THREAD

**Issue by vwboy** [runelite/runelite#390]
Resizable users need to change the window size every time they reset their client. Please allow us to have a plugin where we could set a custom width/height and the client would default to those values everytime.

**Comment by UniquePassive** [comment]
Possibly should add an on/off switch for "saving client state", such that if you have for example maximized the client, it'll be maximized the next time you start the client. Or if the frame has a certain size, save that size and use it at the next launch.

That's maybe better than inputting a custom resolution?

**Comment by Unmoon** [comment]
I think inputting one would be a nice feature for streaming etc. where you want to have exactly 1280x720 or similar resolutions.

**Comment by vwboy** [comment]
@UniquePassive Imo input sounds better because you can use a specific resolution. Or at least some label that shows the current resolution so you can resize to the resolution you want.

**Comment by UniquePassive** [comment]
Perhaps width and height fields and then a button that you can press to put your current client resolution into the fields, should cover both cases. Streamers can set the client frame size and I can get a maximized frame by default.

**Comment by vwboy** [comment]
@UniquePassive sounds good for me :D

**Comment by deathbeam** [comment]
This was resolved in #394
