### ISSUE TITLE
Fishing Notification/ Animation Notification

### ISSUE THREAD

**Issue by xcameron7** [runelite/runelite#3910]
Is there anyway to make the client alert the user when fishing as soon as the fishing spot is finished rather than after the animation is finished as the animation continues after the spot is gone. I think this should be possible as the UI can easily show fishing spots and updates as the fishing spots disappear so a notification should be able to be added to when the fishing spot that is currently being used disappears.

**Comment by LeviSchuck** [comment]
It might be possible. 

Here's how I think it could be done:
1. Store which fishing spot was interacted with when the user clicked
2. Monitor npc teleported, compare to stored npc
3. If fishing, and npc teleported matches fishing spot npc, then fishing is done.

**Comment by tr33s** [comment]
@LeviSchuck it can be done simpler than that. Just store the fishing spot (NPC object) and it's initial position, then if the fishing object becomes invalid (removed) or the position changes then alert.

**Comment by deathbeam** [comment]
Implemented in #6457
