### ISSUE TITLE
Feature Request: Grand Exchange Completed Offers Logger.

### ISSUE THREAD

**Issue by Phader** [runelite/runelite#3915]
**Describe the solution you'd like**

An addition to the existing grand exchange plugin, allowing for the logging of completed offers within a "notes like" section in the sidebar, potentially with the ability to export to a text or csv file.

 Optimally, the ability to upload these offers automatically to Ge-Tracker to track profits or losses, however this is a stretch goal.

**Comment by Abextm** [comment]
Duplicate #1767
