### ISSUE TITLE
Auto-completion of highscore lookup

### ISSUE THREAD

**Issue by Twiglet1022** [runelite/runelite#3920]
| Question    | Answer
| ------------| ---------------
| Java Version | Java Version 8 Update 171
| Operating System | Windows 10

When typing a name into the highscore search bar it will find a name from your friends list and place the rest of the letters from their name after what you have typed. After typing a second letter the letters from auto-complete remain there, tagged onto the end of what you just typed.

GIF demonstration below

![runelive-v1 4 3 2-highscore-search](https://user-images.githubusercontent.com/29353990/41688740-389ada40-74e5-11e8-9d4c-04fb9dfd36c7.gif)

**Comment by pettenge** [comment]
I'm able to reproduce this when I type two letters in quick succession. Is that what you did here?

**Comment by pettenge** [comment]
I think the problem is that calling `SwingUtilities.invokeLater` is causing a race condition somewhere down the line. I'm going to look into this.

**Comment by Twiglet1022** [comment]
It didn't seem to have anything to do with that, no. I can't actually reproduce it now. It's as if the client was in a glitched state and after I restarted it again it was fine. Not sure what initially caused it, but I didn't need to type two characters quickly to get the result I did there. In fact you can see after type the first letter it duplicates the auto-fill twice. Looks like the same thing as issue #4154

**Comment by pettenge** [comment]
I wonder if the key listener could somehow be getting added twice?

**Comment by Adam-** [comment]
Fixed in 30c3ce9dc17f799aec59a177d82360becf6a664b
