### ISSUE TITLE
Add command/toggle to un-render other player models, similar to ::renderself

### ISSUE THREAD

**Issue by mah110020** [runelite/runelite#3921]
The ```::renderself``` command makes the player model invisible. The chat/trade options allow you to ignore other players. This is precedent for a potential command to make other player models invisible. This is helpful because many players enjoy game modes where they do not want to interact with other players, and that is permissible in most game-play.

**Comment by Kamielvf** [comment]
Try the entity hider plugin.

**Comment by Alexsuperfly** [comment]
entity hider plugin

**Comment by cmg5461** [comment]
The ability to render others after a distance would have been a great option for spectating the raids 2 release. On crowded worlds, an option to decrease the maximum render distance would be nice as well.
