### ISSUE TITLE
Fix music button trigger area in the main menu

### ISSUE THREAD

**Issue by arvyy** [runelite/runelite#3923]
I'm not sure if I should have put this as bug, but I put it here since it's reproducible on Jagex official client. 

| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.0_171
| Operating System | Windows 7

The music button in the main menu has gigantic toggle area. Clicking anywhere in the green rectange will trigger it 
![runelite](https://user-images.githubusercontent.com/15849668/41699219-7e9b7568-752b-11e8-954f-a075fd76da89.png) .

Funny enough, this doesn't happen on my Debian machine.

**Comment by Nightfirecat** [comment]
I can confirm on my machine this isn't a vanilla client issue.

**Comment by Adam-** [comment]
> 
> 
> I can confirm on my machine this isn't a vanilla client issue.

This is definitely a vanilla client issue, maybe it is was not at the time you tested it

**Comment by Adam-** [comment]
I've patched this internally since the world switcher arrows can occupy this space as noted in #14367 - which makes it slightly more complicated

**Comment by arvyy** [comment]
hey props to you for coming back for fairly insignificant issue reports
