### ISSUE TITLE
Thieving Chest timers

### ISSUE THREAD

**Issue by SolveSoul** [runelite/runelite#3924]
**Is your feature request related to a problem? Please describe.**
When a thieving chest is looted a timer starts (time depends on chest), when the timer has expired the chest can be looted again. It's kind of annoying you can't actively see when the chest is available for thieving again.

**Describe the solution you'd like**
It would be nice to have an overlay on the chest which shows the cooldown period visually.

**Describe alternatives you've considered**
There is a similar timer for hunter traps. This is what I think would be the best.
![](https://user-images.githubusercontent.com/25905465/38783826-df138de8-40d5-11e8-85cb-815d343f2dbf.png)

**Additional context**
N/A

**Comment by zivc** [comment]
Bump.

**Comment by dhharris** [comment]
What's the status on this feature?

**Comment by Mr-Vexy** [comment]
Status please?

**Comment by th3oryofch4os** [comment]
Still nonexistent ??

**Comment by Nightfirecat** [comment]
This was added to the plugin hub in runelite/plugin-hub#181
