### ISSUE TITLE
Disabling side mouse buttons to make push to talk easier

### ISSUE THREAD

**Issue by Justin222111** [runelite/runelite#3925]
**Is your feature request related to a problem? Please describe.**
I use my mouses side button as a push to talk button in discord, but this also registers as a click in runescape, which can be problematic when doing group pvm content
**Describe the solution you'd like**
i was thinking about making it possible to toggle off certain clicks within the client itself, thus i could click my side mouse button to talk without it clicking withing the client.

**Comment by 07RS** [comment]
Just go into your mouse settings and rebind your side button to insert/end or something that you don't commonly use and something that won't interact or interfere with the game or any web browsers or applications you use.

**Comment by Justin222111** [comment]
the issue with that, is that most other games i play dont have this issue. i played around 1300 hours of dota and like 600 hours of heroes, with that as my push to talk button, so changing the push to talk keybind is actually worse than just dealing with the occasional misclicks. however i think it would be really nice to be able to prevent those occasional misclicks. this may be a niche problem, but i am not the only one of my friend group with said issue

**Comment by Nightfirecat** [comment]
Is this also an issue in the vanilla Runescape client, or only in RuneLite?

**Comment by Justin222111** [comment]
this is not exclusive to the runelite client is happens in the vanilla, and like all other clients unless that have some kind of feature like i describe

**Comment by FappyMcFap** [comment]
For now you can make an ahk script that rebinds that button only within Runelite using #IfWinActive (if interested in this workaround I can write it in more detail.)

**Comment by Justin222111** [comment]
Thank you, i plan on doing this especially since it doesn't seem like anyone is interested in making this a feature

**Comment by deathbeam** [comment]
Well i dont think we should really solve issues wiht your mouse when it is not our fail

**Comment by mmcmd** [comment]
osbuddy apparently disables this if you press . on your numpad, would be great to see something similar with this client.

**Comment by KuzmaVolkov** [comment]
And yet this would help discord too. Seeing as it's been a month and they can't figure it out.
