### ISSUE TITLE
Low FPS on full resolution(resizable mode)?

### ISSUE THREAD

**Issue by saleri** [runelite/runelite#3926]
I get 30-40 FPS on fixed mode, and 15-20 on resizable mode. I'm kind of stuck on a shitty laptop for the time being, but I supposed it could run a 16 year old java game at least better than that.

Specs:
Intel Pentium J3710 @ 1.60GHz
4,00GB DDR3 @ 1600MHz (11-11-11-28)
Intel HD Graphics (Holco Enterprise Co,/Shuttle Computer)
29GB Kingston M52532 (SD (SSD))

I already tried disabling the CPU acceleration hardware, but it didn't change much.

**Comment by deathbeam** [comment]
I believe this is also issue in vanilla, dont think we can do much about this

**Comment by ewagsjr** [comment]
Have you tried the low graphic details setting in RuneLite?

**Comment by Kamielvf** [comment]
This is most likely something that also happens with the vanilla client. Try it out on the official runescape client and see if your FPS issues are resolved there (with same resizable mode/full resolution)

**Comment by saleri** [comment]
I can't even install the official client, supposedly the installation only work if english is your system language, and my laptop has a installation of Windows 10 that only allows one idiom(that can't be changed).

Anyway, I tried OSbuddy and the low FPS problem is still there, so I guess the issue is with OSRS's lack of optimization, low detail mode helps, but every now and then the FPS goes down to single digits and stays there for like a minute, which is weird.

**Comment by saleri** [comment]
I can't even install the official client, supposedly you can only install it if your system language is set to english, and I'm on a Windows 10 installation where you can only have one language(and it can't even be changed). 

Regardless, I tried playing it on Osbuddy, and the FPS issues are still present, so the problem is probably OSRS not being very well optimized to begin with.  Though it's weird how sometimes the FPS dips into the single digits and stay there for like one minute, even in fixed mode.

**Comment by deathbeam** [comment]
Closing as wont fix, I dont think keeping such generic jagex issues open in our issue tracker make any sense.
