### ISSUE TITLE
Arc Library Plugin Update

### ISSUE THREAD

**Issue by puppylife** [runelite/runelite#3929]
Hello, I know that today's update makes the arc library dissapear when you are away from the area for those that only search for books for a limited time. There are many ironmen that have been hurt in terms of xp rates from this. We use Woox's method which we catch imps with magic box's and use them to bank bulk amount of books. Yesterday I was getting 60k rc xp per hr at 68 rc with 6k books banked total. I used the plugin to figure out the amount of books I need since there are 15 books and we use 2 of each besides the one on ground floors. We use one of each of those. Now we have to walk towards the library if we forgot what books are called which given the names, its common to get them mixed up. I ask that you add in a toggle option for it not to dissapear or atleast include the region of the bank to help accomodate a very good RC method. Also we have to always manually click on the plugin again upon entering.

**Comment by Adam-** [comment]
Fixed in #3934
