### ISSUE TITLE
MacOS - Permissions issue on RuneLite in app package contents

### ISSUE THREAD

**Issue by grimeshark** [runelite/runelite#3932]
I'm really not sure if this is the right section considering it's just an issue with the MacOS client build, but I figure I'd post it in case anyone else runs into it. 

| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.0_121
| Operating System | MacOS

In the RuneLite.app/Contents/MacOS directory, the RuneLite file has permissions 744 which only allows execution for the owner of the app (i.e., by default, whichever user installed the app). This can be solved by running chmod +x on the file bringing the permissions to 755, allowing any users to execute it.

<img width="532" alt="screen shot 2018-06-21 at 9 43 20 am" src="https://user-images.githubusercontent.com/6944839/41733814-ecc60b44-7539-11e8-874b-f6957a5de6de.png">

<img width="532" alt="screen shot 2018-06-21 at 9 58 23 am" src="https://user-images.githubusercontent.com/6944839/41733822-f2768636-7539-11e8-86e8-b4d9dfb07972.png">

**Comment by deathbeam** [comment]
Probably should be opened in: https://github.com/runelite/launcher

**Comment by grimeshark** [comment]
Fair point, I'll re-open it over there.
