### ISSUE TITLE
MTA plugin: Hint arrow does not get cleared

### ISSUE THREAD

**Issue by Abextm** [runelite/runelite#3945]
On commit 26fbf78399e328b73fee72d6a1d7f1841e528b50

The hint arrow does not get cleared sometimes after leaving the enchanting room
![2018-06-22_01-56-33](https://user-images.githubusercontent.com/12366911/41765002-0014c72c-75c0-11e8-876a-8a9fc12da3b7.png)

**Comment by Jasper-ketelaar** [comment]
Should be fixed now in #3947

**Comment by deathbeam** [comment]
Fixed in #5162
