### ISSUE TITLE
Clear freeze/entangle timers on movement

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#3960]
When a freeze timer is added by an entity which despawns or runs outside of interaction range, the timer will remain even after the freeze expires. Since we do not have a way of tracking the source of a freeze, timers could be reset upon local player movement.

Edge cases:

* If you teleport while frozen, but are still within range of the freeze's source, you are still frozen
* Planting mithril seeds will cause your character to remain frozen and still move one tile
* Being hit by a dragon spear special attack will cause your character to remain frozen and still move one tile
* ???

**Comment by ScottMCarr** [comment]
I believe the only way to fix this would be to add a hook for the players' movement and check that they are moving with it while also not having the dspear animation present.

**Comment by Nightfirecat** [comment]
Fixed in 720c5f018465f4e854dd0da8b056f735542c0b12:

https://github.com/runelite/runelite/blob/89b8bc52ca28d445d52747bc34ef7cbc477a80f6/runelite-client/src/main/java/net/runelite/client/plugins/timers/TimersPlugin.java#L515-L521
