### ISSUE TITLE
Add regular calculator to sidebar

### ISSUE THREAD

**Issue by Justgotsniff** [runelite/runelite#3967]
I would like to see a simple Regular calculator added to the RuneLite client

**Comment by deathbeam** [comment]
I dont think we really want to implement this because calculator is not really related to RuneScape and it takes like 2 seconds to open Windows open.

**Comment by J-Leg** [comment]
What are some of the instances where you would use a calculator? 
I think supporting chat commands like:

```!maths 70395*93853```
(arithmetic operations in Java syntax for simple parsing)

is a better alternative. I always find alt-tabbing a hassle.

I agree in that a full-blown calculator is a bit overkill for the client.

**Comment by IronApeiron** [comment]
I might work on this...

**Comment by Skaxa** [comment]
WINDOWS CALC SUCKS GIVE CALC OR RIOT REEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by deathbeam** [comment]
No
