### ISSUE TITLE
Chat-command for clue scrolls completed (+ Rank)

### ISSUE THREAD

**Issue by J-Leg** [runelite/runelite#3968]
**Is your feature request related to a problem? Please describe.**
A simple addition to the chat-commands, because right now the list looks a bit lonely :smiley:.

**Describe the solution you'd like**
Uses the ```HiscoreClient``` to fetch the relevant data.  

Something like this:
![screenshot from 2018-06-23 15-18-34](https://user-images.githubusercontent.com/30682722/41806071-8fb197e0-76f9-11e8-9edf-cc52d1887b16.png)

**Comment by Nightfirecat** [comment]
@J-Leg I think you implemented this with #3973?

In the future, [you can close the issue from a PR using specific keywords](https://help.github.com/articles/closing-issues-using-keywords/) so it is closed automatically upon merge.

**Comment by deathbeam** [comment]
Implemented in #3973

**Comment by J-Leg** [comment]
Ah yeah, was wondering how to do that. Thanks!
