### ISSUE TITLE
Idle/Boost Notifications [Bug]

### ISSUE THREAD

**Issue by DanPaguirigan** [runelite/runelite#3970]
| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.0_25
| Operating System | Windows 10 (17134)

### Features: 
- Boosts Information Configuration 
- Idle Notifier

### Issue: Incorrect notifications
Example: 
- Boost Amount Threshold set at: 8.
Notification received with boosted stat > 8.
Notification received on incorrect skill. (e.g. Attack instead of Range)
- Hitpoints/Prayer Notification Threshold set at: 30/20
Notifications received frequently happen above the threshold.

**Comment by deathbeam** [comment]
I dont think this issue is present anymore, and for boost amount threshold we already have open issue with better info by @Nightfirecat
