### ISSUE TITLE
Client glitching

### ISSUE THREAD

**Issue by justaguy1234** [runelite/runelite#3985]
This was not fixable by restarting or downloading runelite again.
it happens when lets say i mouse over exp tracker,then another exp trackers comes up or if i mouse over any configuration option another menu comes up(all the extra menus as shown in picture dissapear with alt-tab and i dont know how to fix,(plz help).
![rip](https://user-images.githubusercontent.com/40529255/41814408-6b7b6b9c-774b-11e8-8283-56ba819df17c.PNG)

**Comment by CustardGod** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
