### ISSUE TITLE
Stamina timer is not triggered by drinking a Stamina mix

### ISSUE THREAD

**Issue by 8992scripts** [runelite/runelite#3986]
Stamina timer is not triggered by drinking a Stamina mix

**Comment by Nightfirecat** [comment]
I'll work on this in the next couple days. At a glance it looks like all mixed potions have been missed by the game timers and item stats plugins.

**Comment by AverageHumanoid** [comment]
I noticed this too while killing mithril dragons which drop various mixes that hovering my mouse over them in my inventory does not show much much stats they will restore/boost.

**Comment by Nightfirecat** [comment]
For reference, the chat string for drinking a stamina mix is "You drink the lumpy potion.", which is the same as any other mixed potion. :anguished:
