### ISSUE TITLE
Mouse cursor styles

### ISSUE THREAD

**Issue by A2s5** [runelite/runelite#3993]
**Describe the solution you'd like**
Different mouse cursor styles beyond the vanilla Microsoft mouse.

**Describe alternatives you've considered**
Perhaps the mouse cursor from RS2 2010 to accompany the currently available menu styling.
Custom mouse image.

Just an aesthetic touch, nothing important really, but nice to have available.

**Comment by jplsek** [comment]
Duplicate of #2068
