### ISSUE TITLE
Sidebar interface issue

### ISSUE THREAD

**Issue by okimsorry** [runelite/runelite#3998]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.0_171
| Operating System | e.g. Windows

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by jplsek** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
