### ISSUE TITLE
Agility Plugin - Al Kharid's First Tightrope Counts as Lap

### ISSUE THREAD

**Issue by Blastburn94** [runelite/runelite#4020]
| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.0_171-b11
| Operating System | Microsoft Windows 10 Pro (Version 1803, OS Build 17134.112)

**Description:** When successfully crossing the first tightrope (_TIGHTROPE_10284_) on the Al Kharid agility course, it counts as a completed lap on the _Total Laps_ counter. The counter does increment normally when jumping the final gap (_GAP_10352_). This causes the addition of two total laps during one full lap, or one lap if a later obstacle is failed.

**Reproduction:** Cross the first tightrope on the Al Kharid agility course.

**Comment by bmiddle** [comment]
For some reason the tightrope and the final obstacle give the exact same experience when done successfully (30 xp). The agility plugin seems to base an increment for a lap off of the final obstacle's experience, so that's currently why it increments twice during one lap.

**Comment by Adam-** [comment]
Fixed in abce07bcc7f875a88a0d7d5dd0b654d6b539a737
