### ISSUE TITLE
Brimhaven Agility Arena ticket timer resets after failing specific obstacles

### ISSUE THREAD

**Issue by 115Apollo** [runelite/runelite#4023]
| Question    | Answer
| ------------| ---------------
| Java Version | build 1.8.0_45-b15
| Operating System | Microsoft Windows 10 Home (Version 1803, OS Build 17134.112)

Description: When failing an obstacle that would make the player fall in or near the spike pit underneath the course the timer would reset back to 59 seconds. Failing obstacles that would not make the player fall (i.e. dart trap, fall rock trap, spinning blades, blade trap, or floor spikes) will not reset timer.

Reproduction: Fail any obstacle that would make the player fall off the course.

**Comment by Adam-** [comment]
Fixed in #4029

**Comment by robmonte** [comment]
@Adam- Doesn't seem to actually be fixed, it will still reset the timer when failing obstacles in the Brimhaven Agility Arena
