### ISSUE TITLE
Runelite Status Bar Icon dull on OS X Mojave Dark Mode

### ISSUE THREAD

**Issue by ewagsjr** [runelite/runelite#4032]
| Question    | Answer
| ------------| ---------------
| Java Version | 8.171.11
| Operating System | MacOS

Updated to the OS X public beta and It seems dark mode messes with the colors of the icon in the status bar.
<img width="577" alt="screen shot 2018-06-26 at 10 28 57 pm" src="https://user-images.githubusercontent.com/25017419/41951565-14b63736-7991-11e8-94c4-4f8264139a07.png">

**Comment by ewagsjr** [comment]
This may be in the wrong location. If so, let me know.

**Comment by Nightfirecat** [comment]
Is this still an issue? I've not heard of others being affected by this.

**Comment by ewagsjr** [comment]
Been 5 years, I have stopped playing on my Mac since :) If it’s hung around this long without others talking about it I’m sure it’s either fixed or not a big enough deal. Can probably close it.
________________________________
