### ISSUE TITLE
Clan Chat (Not able to attack members while pking) aka missclick

### ISSUE THREAD

**Issue by pircx** [runelite/runelite#4037]
For example if im pking with a 10man cc. And where going out pking i can't turn my attack options off other wise i can't attack other players. So It would be nice to add a feature where if there in the ClanChat with you it just says *Walk here* *CLAN CHAT ONLY*

Thank you for taking a look
A big thanks to the coder if he decide's the make this happen. would benefit a lot of players
Feel free to add me on Discord if you have added it or any questions
Pirc#4311

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
