### ISSUE TITLE
FPS drop

### ISSUE THREAD

**Issue by Antedekebab** [runelite/runelite#4039]
Past 2 days my FPS have went down from stable 50 to now 10fps sometimes goes up to 30 for afew seconds. Mainly at 10FPS

Using an intel I7
GTX 960
8GB Ram

Have any idea why?

**Comment by Antedekebab** [comment]
What information is needed?

**Comment by Antedekebab** [comment]
Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

So far looking at my "cores" usage it seems like my core nr 2 is the one doing some job. Everytime the cose usage spikes up then the FPS follows up. When the core usage spikes down the FPS drops close to 10 FPS.

Looks like I have no Java at all

Windows 10 Home 64bit

**Comment by Antedekebab** [comment]
I had to download oldscoolclient again playing on 10fps is not possible... :(

**Comment by Nightfirecat** [comment]
I am closing this as no further information has been posted for many months now. Please re-open this issue if you have further information to report on the FPS issues you've been seeing.
