### ISSUE TITLE
Alt lookup for items doesn't work when the grand exchange offer interface is open.

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#4040]

**Comment by JeljoGb** [comment]
Oh, it's apparently already been mentioned, you can merge this one with that one probably.
I couldn't find it, but my search terms weren't good enough I guess.

**Comment by jplsek** [comment]
What? I think your fine. That's just a pull request, that was made because of this ticket, and just mentions this ticket. It will also automatically close this ticket once it gets added into the client.

**Comment by JeljoGb** [comment]
Oh ok, I'm not completely familiar with how GitHub works. Thanks for
explaining!

Op do 28 jun. 2018 01:23 schreef Jeremy Plsek <notifications@github.com>:
