### ISSUE TITLE
Remove the "Impling" part of the minimap/in world impling overlay.

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#4041]
Currently, you see "Baby impling", "Essence impling".
I'd like it if it changed to just "Baby", and "Essence". This would make it have less text, and remove redundancy.

**Comment by basicDamen** [comment]
Is it just for the Baby and Essence, or for all of them?
Could you provide a screenshot as well for it?
I believe I understand the issue, but, would like to clarify.

**Comment by JeljoGb** [comment]
It's for all of them.
https://user-images.githubusercontent.com/2388657/39968766-6f4544b2-56a0-11e8-8e87-9cdf793e9e95.png

**Comment by Nightfirecat** [comment]
We're highlighting implings the same way as the NPC Indicators plugin would, which includes writing their full NPC name on the minimap, like any other highlighted NPC. In places where this causes clutter (probably just Puro-Puro?), I recommend adjusting the plugin's settings to highlight only the tiers of imps you're focusing on catching.
