### ISSUE TITLE
Charter option to Menu Entry Swapper.

### ISSUE THREAD

**Issue by tuba000** [runelite/runelite#4053]
I'd like to click straight charter ship when talking to the trademen. As it would be faster to run farm runs then :)

**Comment by basicDamen** [comment]
You can already do this. You just have to disable the 'trade' option in 'Menu Entry Swapper.'
![menu_entry_charter](https://user-images.githubusercontent.com/16967401/42120772-04e722a6-7bef-11e8-8ef2-f7aaa8014a43.png)

**Comment by RickertdeH** [comment]
This doesn't solve the immediate problem, @basicDamen. I'd like to have the trade option available on other npc's, but specifically the charter option first with charters. 

Is it possible to have it similar to the Home Portals and Fairy Rings that you can pick your option?

**Comment by Hydrox6** [comment]
`Menu Swapper Extended` plugin on the [Plugin Hub](https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub) does this.
