### ISSUE TITLE
Change the Decimal and Thousand Separators to the UK/US format

### ISSUE THREAD

**Issue by Saer-Dev** [runelite/runelite#4054]
Currently, the Decimal Separator is in the non-UK/US format (where the Decimal Separator is a comma - [see image](https://prnt.sc/k0ekvs)).

**Is your feature request related to a problem? Please describe.**
It's not a problem as such, but may be considered confusing to some UK/US users.  Especially considering that it is not the format used in OSRS itself.  **EDIT:** From reading chatter regarding this in the Discord, I've found out that the formatting is inconsistent, with the ground items using the UK/US format.  So that could be considered a _problem_.

**Describe the solution you'd like**
I would prefer that this is switched to the UK/US format (where the Decimal Separator is a full-stop/period and the Thousand Separator is a comma) to bring it in line with the format used by OSRS.

**Describe alternatives you've considered**
I would also be happy to have a toggle put in place to allow non-UK/US users to maintain the current format.

**Additional context**
- [Image linked at the top of the issue](https://prnt.sc/k0ekvs)
- [Wikipedia article regarding the Decimal Separator](https://en.wikipedia.org/wiki/Decimal_separator)

**Comment by NathenSample** [comment]
We should probably be using a generic formatter thoughout, such as `Stackformatter` (With a more generic name to represent that it isn't just for formatting stacks)

**Comment by deathbeam** [comment]
Fixed in #4059
