### ISSUE TITLE
Xp drop toggle  to show damage dealt instead

### ISSUE THREAD

**Issue by GoEasyImBad** [runelite/runelite#4055]
Make a plug in that instead of showing xp gained example - 500 exp drop show what you hit whether it be a 50 or 80 etc. would probably need scaling at certain places as not all drops are equal.

**Comment by saibottig** [comment]
As mentioned on #5420 is there still a negative stance from Jagex on this feature?

**Comment by abelbriggs1** [comment]
I'd like to implement this but I'm not sure how to get in contact with a relevant JMOD to confirm its legality.

**Comment by Ca5oul** [comment]
support!

**Comment by Nightfirecat** [comment]
We're not likely to implement this as we're not confident in handling all the (many) possible edge cases--particularly weapons granting different amounts of HP exp per damage and the multitude of monsters with increased/decreased xp scaling. The [Customizable XP drops](https://runelite.net/plugin-hub/show/customizable-xp-drops) and [Instant Damage Calculator](https://runelite.net/plugin-hub/show/instant-damage-calculator) hub plugins both have code which attempts to achieve this; I recommend giving them a try.
