### ISSUE TITLE
Implement option to change Grand Exchange tab redirect to OSBuddy's Exchange History as opposed to Runescape's

### ISSUE THREAD

**Issue by vedver** [runelite/runelite#4056]
Currently if you click on an item in the Grand Exchange tab it will redirect you to the item's history such as [Wine of Zamorak](http://services.runescape.com/m=itemdb_oldschool/Wine_of_zamorak/viewitem?obj=245). However, I think it would be beneficial to users who have a preference to allow them to configure the exchange tab to change the redirect to [OSBuddy's exchange history](https://rsbuddy.com/exchange?id=245&).

**Comment by Hydrox6** [comment]
With the move to Wiki prices, this has been implemented for them in 088cb19752169acefef5ac0df88dcbfcd6645f39
