### ISSUE TITLE
Adding Ground Items to be toggled w/ a hotkey.

### ISSUE THREAD

**Issue by bigdaddycupcake** [runelite/runelite#4057]
The idea is simple adding a hotkey such as alt or ctrl a bind of ctrl+1 or anything of that nature to toggled on ground items on/off.  Personally, while in raids or something where a lot of items are dropped (pking) when the ground items shoot to the sky with text is quiet a bit annoying; however, being able to toggle them off with a simple hotkey is a lot simpler than having to go through the options to manually turn them off.

**Comment by Nightfirecat** [comment]
Duplicate of  #1141
