### ISSUE TITLE
Inventory Tags do not take quantity based icons into consideration

### ISSUE THREAD

**Issue by NathenSample** [runelite/runelite#4061]
For items which have a inventory icon which varies depending on stack size inventory tags will outline based upon the 1 stack size, rather than taking current stack size into consideration
![runelite_2018-06-28_22-11-35](https://user-images.githubusercontent.com/9803552/42060887-410ceeca-7b20-11e8-8c3e-c2e66ef27b1d.png)

**Comment by Adam-** [comment]
Fixed in 2e336cd5d193e2a790cd892e01589c1fe9fcc4a5
