### ISSUE TITLE
Mouse hover tooltips misaligned

### ISSUE THREAD

**Issue by Lunchguy** [runelite/runelite#4068]
| Java Version | Not sure
| Operating System | Windows 8.1

</details>

The 14.4 update on 2018-06-21 broke the mouse tooltip overlay for my client. The tooltip is massively misaligned. The misalignment seems to scale with the size of the client, so the tooltip appears in the same position relative to my mouse cursor whether I'm in full screen, fixed mode, stretched fixed mode, or resizable.
![cursortooltipmisaligned](https://user-images.githubusercontent.com/40678810/42068329-6c53202a-7b9f-11e8-803f-8a6a98c1283b.png)

This is a problem because if my cursor isn't in the top left part of the client window, I can't see the tooltip at all.

**Comment by Lunchguy** [comment]
Update: I managed to resolve the issue by deleting everything related to runelite off my pc and reinstalling. My initital attempt at fixing this involved on reinstalling the client, but it seems I had to reset my settings as well for this to go away.

**Comment by deathbeam** [comment]
Hmm looks like this got solved then. No idea why it was problem in first place, but, closing
