### ISSUE TITLE
Agility plugin does not increment laps at the agility pyramid

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#4075]
Because of [the variable bonus experience at the end of an Agility Pyramid run](https://oldschoolrunescape.wikia.com/wiki/Agility_Pyramid#Obstacles) the agility plugin does not increment your lap counter once you've completed a lap.

**Comment by Ishadijcks** [comment]
What would be the preffered way to handle this? It would be possible to update this with a hardcoded pyramid edge case:
````
		if (course == null
			|| Math.abs(course.getLastObstacleXp() - skillGained) > 1
			|| (course.getCourseEndWorldPoints().length > 0 && Arrays.stream(course.getCourseEndWorldPoints()).noneMatch(wp -> wp.equals(client.getLocalPlayer().getWorldLocation()))))
		{
			return;
		}
```
Or something like anglerfish, although that seems a bit overkill for 1 course

**Comment by Adam-** [comment]
I would add the location for the end of the course to the agility plugin and make the last obstacle xp optional.

**Comment by Ishadijcks** [comment]
So check if the object interacted with is at the same location of the final obstacle of the course?
Wouldn't you need to use a different subscriber for that?

**Comment by Nightfirecat** [comment]
@MIK0MIK0MIK0 If you're talking about the skill calculator, this issue is completely unrelated to that.

**Comment by MIK0MIK0MIK0** [comment]
> @MIK0MIK0MIK0 If you're talking about the skill calculator, this issue is completely unrelated to that.

oh ok im sorry
how would i go about requesting to add the agility pyramid to the skill calculator?
