### ISSUE TITLE
Staff of Light special attack

### ISSUE THREAD

**Issue by Floukru** [runelite/runelite#4078]
**Is your feature request related to a problem? Please describe.**
Feature request. The special attack description is 

> The staff has a special attack, Power of Light, which is the same special attack as the staff of the dead's Power of Death. It halves all Melee damage of your opponent(s) (all opponents that hit you in the time of the special attack) for one minute at a cost of 100% special attack energy. This effect stacks with the PvP damage reduction effect of the Protect from Melee prayer, **but is lost if the staff is unequipped**.

Meaning the staff of light must be worn for 1 full minute of you want to keep the special attack in effect.

**Describe the solution you'd like**
A timer counting from 60 to 0. 

**Describe alternatives you've considered**
N/A.

**Additional context**
![image](https://user-images.githubusercontent.com/38350898/42091418-f6759dce-7bad-11e8-99b7-feb594b8d968.png)

**Comment by deathbeam** [comment]
Dont we have support for this already? I thought we do when we added support for SOTD.

**Comment by Floukru** [comment]
@deathbeam Nope. I'm pretty sure you just need to add the item id next to the SOTD.
