### ISSUE TITLE
Zulrah - ring of recoils

### ISSUE THREAD

**Issue by Bkh1994** [runelite/runelite#4080]
When doing Zulrah and the rings of recoil break, there is a small chat notification, but that is it. 

**Describe the solution you'd like**
On Konduit there is a Windows notification and sound that pops up once the ring of recoil breaks. Anything that is more obvious would be nice. When doing Zulrah you can't just stare at the text box waiting for the message to come up.

**Comment by deathbeam** [comment]
Check Item Charges plugin
