### ISSUE TITLE
Notification when Rune Pouch degrades

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4089]
It would be nice to have a notification when a Rune Pouch degrades.

**Comment by Gamer1120** [comment]
I think that it warrants its own notification, since doing it with the chat notifier is not intuitive. I will try to see if there is a message.

**Comment by Gamer1120** [comment]
![image](https://user-images.githubusercontent.com/9074448/42124144-d76ae6e0-7c5d-11e8-8f45-80ec67742408.png)
This is the message in the chat. "Your pouch has decayed through use."

**Comment by Adam-** [comment]
Added in #4155
