### ISSUE TITLE
Critical health notification in Idle Notifier

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4090]
I currently use the Idle notifier on my HCIM to let me know when I should eat (when I have lost 18 HP from my max). It would also be nice to know when I reach 30 or 40 HP, for example when I miss the notification. This simple addition could save some lives. Maybe allow multiple HP levels to be set for the idle notifier.

**Comment by deathbeam** [comment]
Just set the idle notifier threshold to higher value.

**Comment by Gamer1120** [comment]
That's not the point. I want multiple thresholds to alert for HP.
