### ISSUE TITLE
Linux Mint - Login screen is bugged

### ISSUE THREAD

**Issue by JWiddershoven** [runelite/runelite#4104]
| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.0_171
| Operating System | Linux Mint 18.3 Sylvia

The login screen is bugged and doesn't show the username & password fields. See below for a screenshot.

![screenshot from 2018-06-30 14-40-20](https://user-images.githubusercontent.com/11158613/42125255-8bf7e350-7c73-11e8-9bc8-b24ecabdd385.png)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
