### ISSUE TITLE
Saving runelite configuration presets

### ISSUE THREAD

**Issue by Twiglet1022** [runelite/runelite#4105]
**Is your feature request related to a problem? Please describe.**
The particular settings I like to use vary by activity. It can take a while to go through multiple settings when switching between activities.

**Describe the solution you'd like**
The ability to save and give a name to various configuration presets.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by deathbeam** [comment]
Duplicate of #2220
