### ISSUE TITLE
Mouse tooltips keep getting added

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#4106]
As mentioned by the user `Curse of Ares#0534` on discord, after helping his ironman friend with a quest (I assume) by using a key on the ironman to hand it to him, the mouse tooltips kept being added and thus resulted in the following:

![preview](https://i.imgur.com/9WwdLEjh.jpg)

**Comment by deathbeam** [comment]
Any steps to reproduce this?

**Comment by Kamielvf** [comment]
Aside from the steps listed in the main comment, no. Also have not seen this happen myself or to anyone else.

**Comment by deathbeam** [comment]
I guess I will close this for now as it looks not reproducable
