### ISSUE TITLE
Make Cerberus ghost helper infobox glow if prayer <X

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#4107]
IE make an option to set so I can put that if my prayer level is under <X (say X=31) that the border of the infobox will glow or change color to a light blue to tell me that I need to take a sip of potion so the 2nd ghost doesn't smite me and make me eat a 30 hit.

**Comment by deathbeam** [comment]
Just set prayer indicator plugin to warn you or idle notifier
