### ISSUE TITLE
Xp tracker isn't working properly

### ISSUE THREAD

**Issue by Zitski** [runelite/runelite#4111]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| Java Version | x.y.z
| Operating System | e.g. Ubuntu/Windows/MacOS

- Hello
  I just started using the client but for some odd reason the xp tracker does something weird.
  For instance i have 82 strength but it shows me the progress from level 71 strength till 83 strength.
  I've never had a target level for that skill and i have the same problem with other skills.
  Reset isn't working and i allready re-downloaded the client but still the same problem.

- Please complete the above table with a correct information.

- Please include steps to reproduce your issue.

- For general support, please use our Discord server: https://discord.gg/mePCs8U

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by deathbeam** [comment]
Check your vanilla goal settings in this interface: https://github.com/runelite/runelite/wiki/XP-Drop
