### ISSUE TITLE
Add timers for special attacks to Cerberus plugin

### ISSUE THREAD

**Issue by Jalopyy** [runelite/runelite#4113]
According to some sources while I've looked up this boss, it runs on an approximate timer (or attacks since engage?), which means you could probably make a plugin similar to Gorillas for it.

https://www.youtube.com/watch?v=6-dpNiEhjYs

https://i.imgur.com/n1Gj3CH.jpg (tl;dr)

- Every approx 30s from engage, if under 400hp, it'll summon ghosts.
- On engage, and on the 2nd attack after the final ghost (if it spawns, for the first one 30s in) hits you, it'll do a triple mage->range->melee attack. Generally speaking, after the pull, I think it's approximately every 45s it'll do a triple?
- Pools are guaranteed to cast on the 2nd ghost set that happens 60s~ in, if none have been cast so far. From there it's apparently about every 15s afterwards?

From those rules you could probably generate a semi-accurate timer/warning system. Probably not accurate to the attack but enough you could do a 'reminder' type plugin based on time elapsed since boss engage.

**Comment by abextm** [comment]
Jagex's [recent statement](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1) prohibits `Indicates the time where a boss mechanic may start or end`
