### ISSUE TITLE
Farming plugin disease false positives

### ISSUE THREAD

**Issue by NathenSample** [runelite/runelite#4130]
If the user nears a farming spot (Experienced with fruit trees, not noticed the behaviour on other types of plot) then the tracker will false-positive the plot into a `diseased` state.

Thus far I've noticed this behaviour with both pineapple, and papaya trees at both the brimhaven and catherby spots.

Diseased plant - 
![screen shot 2018-07-02 at 13 04 32](https://user-images.githubusercontent.com/9803552/42163035-e315aaa6-7df8-11e8-9817-38c3f9757dfa.png)

False Positive - 
![screen shot 2018-07-02 at 13 07 49](https://user-images.githubusercontent.com/9803552/42163062-f9dca168-7df8-11e8-81aa-c474ea8731c7.png)

Noticed locations - 
Running towards catherby fruit tree from allotments
Brimhaven boat, after arriving, but before taking a single step

**Comment by NathenSample** [comment]
As an addition that I previously didn't notice at time of posting, not only is the state suffering from a false positive in displaying `diseased` but it also shows the plot, which contains a fully grown papaya sapling, as being a banana tree

**Comment by Araevin** [comment]
I've run into the same bug, where orange trees at catherby are shown as dragonfruit

![Catherby-Orange-Dragonfruit](https://user-images.githubusercontent.com/6397700/95026764-b00a6e00-0661-11eb-9e50-4c0374166c5a.png)
