### ISSUE TITLE
Remember whether side bar was closed when re-opening the client

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4133]
Currently, the client defaults to side-bar always on. If I press CTRL+F11, the sidebar goes away. I want this to persist between client restarts. So if I hide it, and restart the client, the sidebar should remain closed.

**Comment by Kamielvf** [comment]
I think current behaviour is better. If someone accidentally hid the sidebar with custom chrome disabled, he would have no idea on how to show it again unless he knows about the keybind.

**Comment by deathbeam** [comment]
Also we are not remembering if plugin panels were open or not so why it should be different with entire sidebar hidden state?

**Comment by Gamer1120** [comment]
I think this should be disabled by default, and a notification/warning should be shown when it is toggled on, similar to enabling the Custom Window Chrome.
![image](https://user-images.githubusercontent.com/9074448/42177879-aa7837f0-7e2e-11e8-88e7-44b3d6ff5fe5.png)
I generally maybe change my settings once a week or so, so for the other >80%, it just fills a bit of my screen on which I'd prefer to have more space for Twitch or Netflix.

**Comment by raiyni** [comment]
duplicate https://github.com/runelite/runelite/issues/2312
