### ISSUE TITLE
Highlight yourself

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4134]
In crowded area's, where nearly every player looks identical, it would be useful if the player could highlight themselves:
![image](https://user-images.githubusercontent.com/9074448/42177331-a36c7f54-7e2c-11e8-932b-0bbbe00c8c71.png)
This would work similar to the NPC indicators plugin.

**Comment by Kamielvf** [comment]
Feature already implemented.
`Player indicators -> highlight own player`

**Comment by Gamer1120** [comment]
Well, not a box, but a thing like this:
![image](https://user-images.githubusercontent.com/9074448/42177722-15aa61b6-7e2e-11e8-8e2e-1f90125a60e5.png)

**Comment by Kamielvf** [comment]
Just place a screenmarker around your player, you're always in the middle of your screen anyways so it will be correct no matter what.

**Comment by Gamer1120** [comment]
I suppose that works too. Thanks for the workaround.
