### ISSUE TITLE
Inventory viewer: Change padding between items to be same as in inventory

### ISSUE THREAD

**Issue by Twiglet1022** [runelite/runelite#4136]
| Question    | Answer
| ------------| ---------------
| Java Version | Version 8 Update 171
| Operating System | Windows 10

It looks like the size of the text for numbers of items in the new inventory viewer are the same as in the actual inventory, despite the inventory viewer being a bit smaller than the actual inventory. This leads to a really really minor issue of the numbers from two adjacent items joining together to look like a single very long number: https://i.imgur.com/Mc10uv3.png

**Comment by Nightfirecat** [comment]
The numbering is rendered exactly the same, the issue is that the items themselves are too close together. There is 6px more whitespace between items in the inventory than there is in the inventory viewer panel.
