### ISSUE TITLE
Duplicate login screens in the client

### ISSUE THREAD

**Issue by Wirelessbrainx** [runelite/runelite#4140]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/issues)

| Question    | Answer
| ------------| ---------------
| RuneLite Version | 1.4.5 - RuneLite.jar 
| Java Version | OpenJDK 1.8.0
| Operating System | Open SUSE Leap 42.3

Once Client loads the Login screen is duplicated (tiled) multiple times over the client. (See image 1)
![image](https://user-images.githubusercontent.com/11902542/42189312-99a7373e-7e4f-11e8-81b8-d6eeab97d32a.png)

When the client is maximised the screen is just black and fails to load. (See image 2)
![image](https://user-images.githubusercontent.com/11902542/42189248-5bdf5d6e-7e4f-11e8-832d-8f9d09447dc3.png)

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
