### ISSUE TITLE
Clue/Pot overlays overlapping

### ISSUE THREAD

**Issue by PxuLL** [runelite/runelite#4142]
| Question    | Answer
| ------------| ---------------
| Java Version | x.y.z
| Operating System | e.g. Windows

- Once at NMZ, i accidentally moved my overlay and I have attempted to put it back in order but for some reason everytime I get a different overlay, for instance, a pot overlay and then reading a new clue it just overlaps. Is there a setting that I cant find to reset this?

Pic for info: https://i.gyazo.com/5fc5cc6abf245810df0290d8859494be.png

<details>
 <summary>stack trace</summary>
 
 ```
  %paste your stack trace here%
 ```
</details>

**Comment by MagicfTail** [comment]
You can move them by holding alt

**Comment by MagicfTail** [comment]
It looks like you need to snap it to the corner, you can do it by moving it to the blue box

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/General-Features#moving-overlays
