### ISSUE TITLE
Looting Bag Info

### ISSUE THREAD

**Issue by VioRS** [runelite/runelite#4143]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Requesting an overlay on the looting bag in the inventory that shows the total value of the items in the bag. Additionally showing how many spaces are used/free (x/28) would be nice too.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Nightfirecat** [comment]
The [Looting Bag hub plugin](https://runelite.net/plugin-hub/show/looting-bag-value) looks like it does this.
