### ISSUE TITLE
Change transparency of interface

### ISSUE THREAD

**Issue by gman977** [runelite/runelite#4152]
Often find in game interface obstructs what I can see. 

Could an option be added to toggle the transparency of the interface including icons etc?

**Comment by CaraPis** [comment]
I found it rather annoying to read the interfaces because of the transparancy. I'd much more when it's just a solid color tbh.

**Comment by raiyni** [comment]
Chatbox transparency exists on the plugin hub, you can change the transparency of the right click menu, you can change the background color/transparency of overlays now, and there is a hide all widgets plugin on the plugin hub.
