### ISSUE TITLE
tile.getGroundItems() returns Incorrect list of items

### ISSUE THREAD

**Issue by TheStonedTurtle** [runelite/runelite#4159]
Title.

Happens when you pickup a one stack of items from a tile when there are 2 stacks of that item ID (Stackable items are the issue)

![2018-07-03_16-39-18](https://user-images.githubusercontent.com/29030969/42249648-4f76a108-7ee1-11e8-9b19-18b8eb841218.gif)

### Replication:

Drop X coins on the floor and then wait ~30 seconds.
Drop a different amount of coins on the same tile.

Pick the top item up from the floor.

### Code:
I was using `onGameTick()` but it really doesn't matter when you call it.
```java

	@Subscribe
	protected void onGameTick(GameTick t)
	{
		WorldPoint you = client.getLocalPlayer().getWorldLocation();
		int regionX = you.getX() - client.getBaseX();
		int regionY = you.getY() - client.getBaseY();
		Tile tile = client.getRegion().getTiles()[you.getPlane()][regionX][regionY];

		List<Item> items = tile.getGroundItems();

		if (items != null)
		{
			StringBuilder s = new StringBuilder();
			s.append("[");
			boolean f = false;
			for (Item item : items)
			{
				if (f)
				{
					s.append(",");
				}
				s.append("Item(id=").append(item.getId()).append(",quantity=").append(item.getQuantity()).append(")");
				f = true;
			}
			s.append("]");
			log.info(s.toString());
		}
	}
```

**Comment by Abextm** [comment]
So the tl;dr with this is that the packet to remove items doesn't contain anything other than the tile and the item id that needs to be removed, so the client always returns the first one in the deque. The only way I could see to deal with this is to track interaction with the pile and figure it out based upon that.

**Comment by TheStonedTurtle** [comment]
Could we use that packet in conjunction with inventory memorization to figure out if the player picked up and item or if it despawned? IIRC the items on top are the newer items

**Comment by Adam-** [comment]
Rev 208 updated this to also include the item qty, which fixes this.
