### ISSUE TITLE
Opponent text in opponent health panel overlaps border for opponents with long names

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#4162]
Example: [(and zoomed version for more detail)](https://user-images.githubusercontent.com/2199511/42261510-04630216-7f58-11e8-8646-754462aa99d2.png)

![Opponent name overlaps panel border](https://user-images.githubusercontent.com/2199511/42261476-ed21dbf4-7f57-11e8-8e5d-7f51e2e25e64.png)

**Comment by Adam-** [comment]
fixed in 82cef9329663833ee800575d32b52c97fda34e4a
