### ISSUE TITLE
Runelite problem on fedora 28

### ISSUE THREAD

**Issue by jdamata** [runelite/runelite#4170]
![screenshot from 2018-07-04 21-38-43](https://user-images.githubusercontent.com/33775101/42298218-c99af38e-7fd2-11e8-97d6-4ad37b132158.png)

[jdamata@localhost Desktop]$ java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

[jdamata@localhost Desktop]$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)

Not sure what is causing the issue in the screenshot. Any advice or pointers is welcome.

**Comment by Kamielvf** [comment]
See https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
