### ISSUE TITLE
Official Barrows overlay not hiding properly

### ISSUE THREAD

**Issue by Athemoe** [runelite/runelite#4180]
https://i.imgur.com/WoVH8Ud.png

The official brother counter is still displayed, causing issues with the stat boost plugin.

**Comment by Adam-** [comment]
Is this a new bug as of this release?

**Comment by Adam-** [comment]
This was caused from an update to the interface ids. Fixed in e2d4ec6893890672649df9bf170ac1880cbd9ebc.
