### ISSUE TITLE
xp tracker bug

### ISSUE THREAD

**Issue by EAS-Andrew** [runelite/runelite#4183]
xp tracker total xp/h seems to be a sum of all skills xp/h rates apposed of actual xp gained in session / time.

e.g:

training attack yielding 30kxp/h then switch to str yielding roughly the same 30kxp/h
ttl xp/h = 60kxp/h when in reality it's still roughly 30kxp/h

**Comment by NathenSample** [comment]
Reset your XP tracker for skills you don't want incorporated into your Xp/hr statistics. 
Total is simply a sum of XP/XPhr on stats which are in the tracker - Any attempt to be smart here would likely run afoul of as many people as it helps.

**Comment by Pashweetie** [comment]
It wouldn't be too hard to have a toggle option for a faster algorithm that doesn't base off of xp/hr but perhaps xp/minute or xp/15 minute would that be a good solution do you think?
