### ISSUE TITLE
Runelite on Mac Whitebox that closes when trying to open

### ISSUE THREAD

**Issue by ImpekkabIe** [runelite/runelite#4186]
Just closed my previous Runelite client and tried opening it to be welcomed by a white loader bar that shuts out immediately, currently on Mac High Sierra, I've tried redownloading and using the all platform client if anyone can help please it would be appreciated.

**Comment by gccltl** [comment]
Pictures would be helpful

**Comment by NathenSample** [comment]
Capture your `application.log` and `launcher.log` and upload to gist.github.com or pastebin.

```
RuneLiteBOT - Today at 5:30 PM
To find logs, either open screenshot directory (by right-clicking "Camera" button) and navigate 1 directory up and then open logs folder, or navigate to %userprofile%\.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS.```

Alternatively, try clear your runelite folder -

1) Launch a terminal
2) `rm -rf ~/.runelite`

**Comment by NathenSample** [comment]
This issue was discussed on discord, and was determined to be 403's when connecting to maven due to cloudflare blocked IP - and can be closed.
