### ISSUE TITLE
Change vanilla xp drop Color if damage boost prayer is active.

### ISSUE THREAD

**Issue by vwboy** [runelite/runelite#420]
Changing XP drop colour to (red -> melee damage boosting prayer), (blue -> mage damage boosting prayer), (green -> range damage boosting prayer), will allow the player to know if the pray flick actually was activated at the time the damage was dealt. Keep the XP drop as it is, but just change the font colour to the corresponding prayer active.

**Comment by Sethtroll** [comment]
Was added in #423
