### ISSUE TITLE
Can we get the custom dynamic cursor?

### ISSUE THREAD

**Issue by rabbit99999** [runelite/runelite#4207]
Hello I was just wondering if possible to add the gold custom cursors from like 2010 where if you hover over an item or an NPC it'll display different actions such as a sword icon to attack, a chat bubble to talk, or even an apple with a bite taken out of it for eating food. I think that would be super awesome to add alongside the 2010 interface. Thank you for reading, hope this gets implemented. Keep up the outstanding work. ❤️

**Comment by Nightfirecat** [comment]
Duplicate of #2068

**Comment by Hydrox6** [comment]
Now that custom cursors are a thing, this is no longer a duplicate

**Comment by Hydrox6** [comment]
The Contextual Cursors plugin on the [Plugin Hub](https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub) does this.
