### ISSUE TITLE
Prayer bonus tooltip missing prayer values for certain items

### ISSUE THREAD

**Issue by FearrMe** [runelite/runelite#4208]
ring of suffering (ri)'s prayer bonus is missing from the prayer bonus in the tooltip, and also isn't used in the calculation for time left until prayer drain. picture [here](https://i.imgur.com/DPm53NI.png)

not sure which other items might have this same issue

**Comment by spanksy** [comment]
The Devout Boots also have this issue. The bonecrusher necklace may also have this issue as it is similarly a new item with prayer bonus released with the Kebos update.

**Comment by spanksy** [comment]
Sorry, this is my first time bug reporting. Thanks m8!
