### ISSUE TITLE
Show number of planks above your Butler's head

### ISSUE THREAD

**Issue by HaverchuckRS** [runelite/runelite#4214]
So when training construction, sometimes you forget how many planks your butler is carrying. So I'm suggesting having the number of planks above his head to maximize efficiency.

https://i.imgur.com/WmKRTO3.jpg

https://i.imgur.com/ZM61KGZ.jpg

**Comment by Gamer1120** [comment]
Would like to request this too, but then displayed like boost information is currently displayed.

**Comment by Nightfirecat** [comment]
This is available [via the Butler Info plugin on the plugin hub](https://runelite.net/plugin-hub/show/butler).
