### ISSUE TITLE
Plugin to Disable Mouse Buttons in RL Client

### ISSUE THREAD

**Issue by Seanaissance** [runelite/runelite#4217]
I use this script `#if (mouseIsOver("ahk_exe RuneLite.exe"))
 
XButton1::
XButton2::return
 
mouseIsOver(W) {
  MouseGetPos,,, mW
  return WinExist(W " ahk_id " mW)
}`

to disable mouse buttons on the client (mouse4/5 acts as left click in osrs) because I use them for other things like push-to-talk keys. I can't have AHK open a lot anymore, is there a way to make a plugin for the client that does this?

**Comment by deathbeam** [comment]
No, I dont think we want to do any mouse button remapping. https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
