### ISSUE TITLE
Add "Woodcutting Guild" to Discord plugin

### ISSUE THREAD

**Issue by despacittto** [runelite/runelite#4218]
There should be a new location called "Woodcutting Guild" on a Discord playing status.

**Comment by jplsek** [comment]
How is this different than the "Exploring" status?

**Comment by deathbeam** [comment]
Exploring: is dungeons, Location: is above I guess.

**Comment by SquirrelHub** [comment]
I'll be submitting a pull request for this hopefully soon.

**Comment by deathbeam** [comment]
Fixed in #4813
