### ISSUE TITLE
Move "Prayer Notification Threshold" From 'Idle Notifier' category to 'Prayer' category

### ISSUE THREAD

**Issue by tjhillard** [runelite/runelite#4229]
**Is your feature request related to a problem? Please describe.**
The "Prayer Notification Threshold" config option does not make sense living within the "Idle Notifier" parent category. A user will intuitively expect that it exists within the "Prayer" parent category.

**Describe the solution you'd like**
Move the "Prayer Notification Threshold" configuration to the "Prayer" category.

**Describe alternatives you've considered**
N/A

**Comment by deathbeam** [comment]
It does make sense because you care about that notification mostly only when you are afking?
