### ISSUE TITLE
Incorrect hot/cold location for west of Nardah

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#4238]
The hot/cold location tile, west of the Nardah genie cave entrance thing, is off by a few tiles.
It says (around) here: ![image](https://user-images.githubusercontent.com/34870401/42425163-07270a8c-8319-11e8-85f9-2d84433a1488.png)
It is (around) here: ![image](https://user-images.githubusercontent.com/34870401/42425166-0ff9723a-8319-11e8-9af8-cd82c73620db.png)

**Comment by Nightfirecat** [comment]
So to be clear, a successful dig spot is roughly 4 or 5 tiles north of where the indicator was?

**Comment by JeljoGb** [comment]
Iirc yes.

Op ma 9 jul. 2018 05:53 schreef Jordan <notifications@github.com>:
