### ISSUE TITLE
Ali Morrisane Rune Puzzle Solver

### ISSUE THREAD

**Issue by Lloy123** [runelite/runelite#4253]
The puzzle isn't too difficult but it's really annoying to do over and over when you're looking to buy bulk runes without going into the wilderness.

Would be nice if someone could make a plugin to solve the puzzle.

No alternative solutions I can think of, it's just a puzzle solver. 

https://vignette.wikia.nocookie.net/2007scape/images/5/55/Rogue_Trader_-_Examine.png/revision/latest?cb=20140608213903

**Comment by devLotto** [comment]
https://github.com/runelite/runelite/pull/955#issuecomment-382589463
