### ISSUE TITLE
Absorption points left is difficult to read, should not be yellow text

### ISSUE THREAD

**Issue by franzvrolijk** [runelite/runelite#4258]
The contrast between the points left and the absorption potion in the background is really low in nightmare zone, and can be difficult to read.

Would be nice with either an option to change the color manually, or just choose another color than yellow to display the remaining points.

Here is an example: https://i.imgur.com/WdQJcKO.png

**Comment by franzvrolijk** [comment]
I reckon the green displaying the boosted levels would be better.

**Comment by Spedwards** [comment]
I think this can be closed. You can edit the colour to whatever you want.
