### ISSUE TITLE
Stairs in the Myth's guild missing in low detail mode

### ISSUE THREAD

**Issue by Paradoxis** [runelite/runelite#4259]
| Question    | Answer
| ------------| ---------------
| Java Version | 1.8.0_171
| Operating System | Windows 10

The section before the stairs in the Myth's guild missing in low detail mode:

![2018-07-10_18-24-03](https://user-images.githubusercontent.com/6770124/42534624-6bcacc1a-848d-11e8-960a-24f355294ba4.png)

**Comment by Adam-** [comment]
Is this not a duplicate of #1481?

**Comment by deathbeam** [comment]
It indeed is.
