### ISSUE TITLE
Multiple plugins not working need help

### ISSUE THREAD

**Issue by zarrard** [runelite/runelite#4263]
|( Question )   | Answer
| ------------| ---------------
| Java Version | 10.0.1 "OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)"
| Operating System | Ubuntu
Runelite version | 1.4.6
Launcher version | 1.6.0

I am running ubuntu 18.04 with hardware acceleration turned off. When I try to look at the grand exchange by typing, or by looking up a player stats, I get a red exclamation

The issue seems to be connected some how with these plugins ( Grand Exchange, HiScore, News feed, Item Prices, Examine) can't think of anything else, but if anyone with any coding knowledge that knows how theses plugins are connected would fix my issue i think, i mean a step in the right direction. . ill be happy to reply with anymore information that is need thanks.

**Comment by Alexsuperfly** [comment]
look at the `Problems with logging in to RuneLite and accessing API` section of https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by zarrard** [comment]
Thanks so much
