### ISSUE TITLE
Overload notification before it goes off.

### ISSUE THREAD

**Issue by 1lon4** [runelite/runelite#4279]
Overload notification is already in RuneLite, however runelite warns you after overload ends which makes your hitpoints jump up to 50 for at least a few ticks during which, if you are on a low defense account you will get murdered or lose at least a hundred absorbtion points extra. 

Please add an option to set time before overload duration ends at which the notification sounds off.
We already have such an option for absorbtion points (defaulting to 50). The parallel to that would be absorbtion warning warning you when your points have already ran out.

Alternatively allow for a chat warning to do the same.
![overload](https://user-images.githubusercontent.com/41133338/42608603-c3e41dce-8588-11e8-9e1c-f6f7e4d276d7.png)

**Comment by Nightfirecat** [comment]
If nothing else, you can use the Chat Notifier plugin to send a notification on the "The effects of overload will wear off in 10 seconds" text message.

**Comment by 1lon4** [comment]
>If nothing else, you can use the Chat Notifier plugin to send a notification on the "The effects of overload will wear off in 10 seconds" text message.

If there was such a chat line to put a notification on. That is only in raids, not in NMZ.
I've checked 3 youtube videos about NMZ to confirm that wasn't an issue on my side none of them had it enabled and there is no setting anywhere for it.

**Comment by Nightfirecat** [comment]
Oh, I see--that middle line of text is put in by you, not by the game.

**Comment by kristian-welsh** [comment]
I've nearly finished work on this, but I'm experiencing a timing issue that I don't understand.

My implementation sends notifications a little too late, the error grows with a larger amount of time configured. If it's configured to leave 10 seconds, it leaves 7 seconds, if configured to leave 30 seconds it leaves 20 seconds.

I'd be happy to submit a pull request as is, but it obviously isn't ideal with that unresolved error. If anybody would like to work on this feel free to clone my fork.

**Comment by kristian-welsh** [comment]
That was exactly the problem, thank you.

**Comment by Nightfirecat** [comment]
This was added in #11995.
