### ISSUE TITLE
White Dot Notifier

### ISSUE THREAD

**Issue by Mabel5** [runelite/runelite#4282]
I'm just wondering where a white dot indicator would sit in regards to the game rules around third party clients as well as if its possible

**Comment by Kaptn225** [comment]
If you haven't seen it yet, you can change the colour of players on the minimap in the "minimap" plugin, and even have their names drawn above their heads/on the minimap in the "player indicators" plugin.

**Comment by abextm** [comment]
Jagex's [recent statement](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1) prohibits `Offers additional information about other players, with the purpose of scouting PvP targets`
