### ISSUE TITLE
Runelite crashes as soon as it opens

### ISSUE THREAD

**Issue by Miowa** [runelite/runelite#4285]
I try to open runelite, the loading bar appears saying 0% and it immediately closes again.
I've already tried reinstalling restarting my pc.

**Comment by Matsyir** [comment]
All clients are currently down, as well as the RS servers.
https://twitter.com/OldSchoolRS/status/1017360323068792832

**Comment by SieBrum** [comment]
Runescape is down...

**Comment by deathbeam** [comment]
This was caused by OSRS being down
