### ISSUE TITLE
24 clients on Ubuntu 18.04

### ISSUE THREAD

**Issue by Beagon** [runelite/runelite#4288]
| Question    | Answer
| ------------| ---------------
| Java Version |java 10.0.1 2018-04-17 Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10) Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
| Operating System | Ubuntu 18.04 LTS

When I open the client it shows 24 clients. This does not happen when I run the Official OSRS client.
https://imgur.com/a/32RpDxM

There is nothing special in the logs, this also appears when I'm using OpenJDK 8/10 or Oracle JRE 8.

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by deathbeam** [comment]
See last reply (also props to you for counting the tiles)
