### ISSUE TITLE
Magic Effects Overlay

### ISSUE THREAD

**Issue by devOSRS** [runelite/runelite#4295]
*** Feature Request ***

Overlay to see opponent's magic effects, such as binds/barrage times. 

Exilent Client has this, but I do not see it on their current feature list. A quick snapshot video is [here](https://youtu.be/Xv3_13QDtZU?t=28).

**Comment by Nightfirecat** [comment]
Duplicate of #2011 and #2009; the latter may not be implemented as Exilent is not considered a "trusted" client, so we will not necessarily implement features only offered in that client.
