### ISSUE TITLE
Add an item viewer and sprite viewer to dev tools plugin

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#4297]
**Is your feature request related to a problem? Please describe.**
It would be useful to get easy access to item or sprite images.

**Describe the solution you'd like**
A pop-out window (similar to the variable viewer or widget tools windows) with a table of images with name labels, perhaps with a search bar to filter the visible images.

**Comment by abextm** [comment]
Item images are on static.runelite.net now, and you can get sprites from my cache dumps
