### ISSUE TITLE
Linear XP Leveling

### ISSUE THREAD

**Issue by Excaliburke** [runelite/runelite#4305]
I've always found that Runescape's exponential XP requirements intimidating, and the idea of 92 being halfway through is somewhat odd.

I would like a feature that removes Runescape's default level up messages and hides your levels, replacing them with linear levels and new "level up" messages every 132,000 exp. This would remove intimidation at growing XP numbers.

**Comment by Drazneel** [comment]
Get off your asses and bring this important feature to game except revise it to leveling 1-73.

**Comment by dekvall** [comment]
This is a very niche request and not something we are going to implement.
