### ISSUE TITLE
Clue Scroll Hint Optimization

### ISSUE THREAD

**Issue by TheStonedTurtle** [runelite/runelite#4307]
### [We are now using a google sheet to track clues](https://docs.google.com/spreadsheets/d/1QwQcMkui12WCyrN2XRGp2KoMJAx_9qf8SZddy385t74)

Would be nice to optimize the clue scroll plugin info box with hints tied to Clue ID. This would also allow us to show the info box without reading the clue scroll, which can be useful since you can't read the clue if in certain combat situations.

I.E. Hard clue ID 3558 is a coord clue that takes you to rouge castle in 50+ wildy.

Current Infobox says:
```
Click the clue scroll along the edge of your world map to see where you should dig.
```

Could be optimized to include the estimated location.

```
Estimated Location: Rogues Castle deep wildy
Click the clue scroll along the edge of your world map to see where you should dig.
```

If you find any clues while playing please add them using the below format:

| Clue Tier | Clue Type | Clue Id | Possible Solution Text
|- |- |- |-
| Hard | Coordinate | 3558 | Rogues Castle deep wildy

Copy-Paste format
```
| Clue Tier | Clue Type | Clue Id | Possible Solution Text
|- |- |- |-
| Hard | Coordinate | 3558 | Rogues Castle deep wildy
```

## Currently Recorded Clues

<details>
<summary>Easy Clues</summary>
<p>

| Clue Type | Clue Id | Possible Solution Text
|- |- |-
| Cryptic | 2682 | Crates inside Al Kharid house with Range
| Map | 2713 | Varrock West Mine (Chronicle/Varrock Teleport)
| Map | 2716 | Varrock East Mine (Senntisten/Varrock Teleport)
| Map | 2719 | Standing Stones between Falador & Barbarian Village (Falador Teleport)
| Cryptic | 3505 | Ardougne's Market house north of silver merchant
| Cryptic | 3508 | Drawers in Seer's Village spinning wheel room
| Map | 3518 | South of Wizards Tower (Fairy ring: DIS)
| Map | 7236 | North of Falador, 1 tile south 3 tiles east of statue
| Emote | 10182 | Wizards Tower Bridge (Passage Necklace: Wizard's Tower)
| Emote | 12164 | Falador Gem Store
| Map | 12179 | Al Kharid Mine (Duel ring: Duel arena)
| Cryptic | 19828 | N/A (already has solution text)

</p>
</details>

<details>
<summary>Medium Clues</summary>
<p>

| Clue Type | Clue Id | Possible Solution Text
|- |- |-
| Coordinate | 2823 | Lumbridge Swamp, north-east of Zanaris Shed
| Cryptic | 2855 | Sinclair Mansion, talk to Donovan the Family Handyman
| Cryptic | 3607 | Burthrope. Kill Penda for Key then search drawers in Dunstan's house.
| Emote | 12025 | Seers Court house
| Coordinate | 12041 | Far West of Jiggig near Chompy Hunting area. (Fairy Ring: BKP)
| Cipher | 19772 | talk to Drezel in Paterdomus (A: 7)

</p>
</details>

<details>
<summary>Hard Clues</summary>
<p>

| Clue Type | Clue Id | Possible Solution Text
|- |- |-
| Map | 2722 | Search a crate inside Varrock lumber yard
| Coordinate | 2737 | Near Ladder to KBD Lair (41 wildy)
| Coordinate | 2739 | North of Pirates' hideout (55 wildy)
| Cryptic | 2785 | Lumbridge windmill, Top floor
| Cryptic | 2786 | Dig under crossbow spawn in Graveyard of Shadow (18 Wildy, outside corp cave)
| Cryptic | 2790 | Dig near cauldron by Moss Giants under Varrock Sewers
| Map | 3522 | West Ardougne
| Coordinate | 3540 | East of Shilo across Stepping Stones
| Coordinate | 3546 | Near Keef in Gu'Tanoth
| Coordinate | 3548 | Island south of Yanille (Dungeon icon north-west of Feldip Hills Glider)
| Coordinate | 3554 | Inside Duel Arena (Obstacles on)
| Coordinate | 3558 | Rogues Castle deep wildy
| Coordinate | 3562 | South of Elf Camp (Across river, passed some sticks)
| Cryptic | 3572 | Northern Bookcase first floor Sorcerer's Tower
| Cryptic | 3575 | Heckel Funch, first floor Grand near daero
| Cryptic | 3580 | Karamja Volcano, dig on tile red spiders' egg respawns on
| Map | 7239 | South-east of Wildy Agility Course, 50 Wildy
| Map | 7241 | Between Tables south of Legends Guild
| Cryptic | 7247 | Bookcase by doorway of building south-east of Shilo Gem Mine
| Cryptic | 7254 | Haystack in Ranger's Guild (South corner)
| Emote | 10234 | Chaos Temple, 13 wildy
| Emote | 10244 | Rogue General Store (23 wildy)
| Emote | 10250 | White Wolf Mountain Gnome Glider
| Emote | 12544 | East Coast Kharazi Jungle, Legends Quest 
| Emote | 12548 | Inside Jiggig up the stairs
| Coordinate | 12558 | Island south of Witchaven (Fairy Ring: AIR)
| Anagram | 12566 | Prospector Percy in Motherlode Mine (A: 12)
| Coordinate | 12562 | Inside Burgh de Rott, South-West of Barrows
| Fairy Ring | 19862 | A I Q (Mudskipper point)
| Fairy Ring | 19864 | A I R (Island SE of Lumbridge)
| Fairy Ring | 19872 | B L P (Tzhaar Area)
| Fairy Ring | 19874 | C K P (Cosmic entitys plane)
| Fairy Ring | 19876 | D I P (Sire Lair)
| Fairy Ring | 19878 | D K S (Polar hunter area)
| Anagram | 19884 | Awowogei on Ape Atoll (A: 24)
| Cipher | 19898 | Eluned outside Lletya (A: 53000)
| Cipher | 19904 | Kalphite Lair entrance, talk to Weird Old Man (A: 150, Fairy Ring: BIQ)
| Cipher | 19906 | King Percival, Fisher Realm (A: 5, Fairy Ring: BJR)

</p>
</details>

<details>
<summary>Elite Clues</summary>
<p>

| Clue Type | Clue Id | Possible Solution
|- |- |-
| Emote | 12077 | Warriors Guild Bank (Emote: Salute, Items: Black Sally, nothing else)
| Coordinate | 12110 | Inside Hardwood Grove (100 trading sticks, near tai bwo wannai)
| Emote | 12080 | Top of Slayer Tower (Emote: Headbang Items: Seercull, combat brace, nezy helm)
| Coordinate | 12090 | West of ice gate from RFD (N of Troll Stronghold west of Troll Child)
| Coordinate | 12097 | Inside the wildy agility course
| Coordinate | 12109 | Lava Dragon Isle
| Cryptic | 12115 | Talk to Sherlock
| Cryptic | 12117 | Talk to Sherlock
| Challenge | 12128 | Sherlock Challenge (dynamic)
| Cryptic | 12140 | Head mourner in West Ardy HQ (underground)
| Cryptic | 12147 | Vannaka in Edgeville Dungeon.
| Map | 19784 | Soul Altar
| Emote | 19790 | Ardy Gem Store (Emote: Laugh Items: CW bracelet, Dragonestone amulet, Ring of forgeing)
| Anagram | 19792 | Guard Vemmeldo, Gnome Stronghold Bank near Slayer Cave (A: 3)
| Cryptic | 19796 | Kill a rock crab
| Cryptic | 19804 | Kill a crocodile
| Cryptic | 19805 | Kill an Ankou
</p>
</details>

**Comment by TheStonedTurtle** [comment]
| Clue Tier | Clue Type    | Clue Id | Possible Solution Text
|- |- |- |-
| Hard | Coordinate | 7239 | South-east of Wildy Agility Course, 50 Wildy

**Comment by WillThomas** [comment]
Some easy clues will get more soon. I've included a 'closest-ish' teleport in (), might not be too useful as everyone has different teleports unlocked though.

| Clue Tier | Clue Type | Clue Id | Possible Solution Text
|- |- |- |-
| Easy | Map | 3518 |  South of Wizards Tower (Fairy ring: DIS)
| Easy | Map | 12179 |  Al Kharid Mine (Duel ring: Duel arena)
| Easy | Map | 2719 |  Standing Stones between Falador & Barbarian Village (Falador Teleport)
| Easy | Map | 2716 |  Varrock East Mine (Senntisten/Varrock Teleport)
| Easy | Map | 2713 |  Varrock West Mine (Chronicle/Varrock Teleport)

**Comment by dicrypt** [comment]
I feel like it might be beneficial to make use of a [Google Sheet](https://docs.google.com/spreadsheets/d/119fGqaR82ZP9jylJPeEogtuuMDI7AFgdB-hcVR1qt1c/edit?usp=sharing) to make data collection easier. I also added a "Requirements" column that we might be able to display to the user if they can do it or not (either doing the check programmatically or just display the info).

**Comment by Nightfirecat** [comment]
| Clue Tier | Clue Type | Clue Id | Possible Solution Text
|- |- |- |-
| Easy | Cryptic | 19828 | N/A (already has solution text)

**Comment by SomeZer0** [comment]
| Clue Tier | Clue Type | Clue Id | Possible Solution Text
| Hard | Coord | 12554 | Fairy Ring CLP

**Comment by Nightfirecat** [comment]
| Clue Tier | Clue Type | Clue Id | Possible Solution Text
|- |- |- |-
| Medium | Emote | [12021](https://user-images.githubusercontent.com/2199511/45246041-9f566500-b2ee-11e8-8076-2d6b186111cd.png ) | Bring a light source
| Medium | Emote | [12029](https://user-images.githubusercontent.com/2199511/45246050-b2693500-b2ee-11e8-9211-47b9497ee683.png ) | N/A
| Medium | Cipher | [19770](https://user-images.githubusercontent.com/2199511/45246064-c876f580-b2ee-11e8-9c4a-ca5cc652e03b.png ) | Adam, Outside Lumbridge castle (Answer: 666)
| Hard | Cryptic | [2774](https://user-images.githubusercontent.com/2199511/45245589-85b41e00-b2ec-11e8-823c-54d784f02890.png ) | Dig in Edgeville, just east of the Southern Yew tree
| Hard | Cryptic | [2783](https://user-images.githubusercontent.com/2199511/45245144-99f71b80-b2ea-11e8-8349-d9cd97877484.png ) | Dig by the torch in the Ardougne Zoo, between the penguins and the scorpions
| Hard | Cryptic | [2792](https://user-images.githubusercontent.com/2199511/45245712-1559cc80-b2ed-11e8-8a18-9ecad2004836.png ) | Talk to Hans roaming around Lumbridge Castle
| Hard | Coordinate | [3526](https://user-images.githubusercontent.com/2199511/45245739-391d1280-b2ed-11e8-81b5-417f0a3af93e.png ) | Trollheim summit, near entrance to Eadgar's cave (Saradomin wizard)
| Hard | Cryptic | [3574](https://user-images.githubusercontent.com/2199511/45245927-2525e080-b2ee-11e8-9de2-f93b9213c7ea.png ) | Search the boxes around the hut where the broken Dwarf Cannon is, close to the start of the Dwarf Cannon quest
| Hard | Cryptic | [7245](https://user-images.githubusercontent.com/2199511/45245966-471f6300-b2ee-11e8-8db9-834779d05cd3.png ) | Dig in the centre of Mort'ton, where the roads intersect
| Hard | Cryptic | [7248](https://user-images.githubusercontent.com/2199511/45245102-64523280-b2ea-11e8-9398-901fd0458f97.png ) | Search the crates in the General Store tent in the Bandit Camp
| Hard | Coordinate | [7264](https://user-images.githubusercontent.com/2199511/45245840-b0eb3d00-b2ed-11e8-95f3-d326424301a7.png ) | In level 22 Wilderness, past the Black Salamanders (Zamorak wizard)
| Hard | Emote | [10236](https://user-images.githubusercontent.com/2199511/45245776-636ed000-b2ed-11e8-9462-b616ef2d9e56.png ) | N/A
| Hard | Emote | [12546](https://user-images.githubusercontent.com/2199511/45245557-6e753080-b2ec-11e8-84bd-0058c9f1903f.png ) | N/A
| Hard | Emote | [12552](https://user-images.githubusercontent.com/2199511/45245853-c3fe0d00-b2ed-11e8-8cee-d9ddf04094ab.png ) | N/A
| Hard | Anagram | [12568](https://user-images.githubusercontent.com/2199511/45245171-c743c980-b2ea-11e8-99b7-1b8f8c491249.png ) | Barrows (Answer: 40)
| Hard | Coordinate | [19842](https://user-images.githubusercontent.com/2199511/45245815-93b66e80-b2ed-11e8-8d2f-5f572a4c4dd3.png ) | South of the burning man located south-east of Kourend's Lovakengj House mine (Saradomin wizard)
| Hard | Cryptic | [19866](https://user-images.githubusercontent.com/2199511/45245669-da579900-b2ec-11e8-8f5b-8a026743954d.png ) | A L P (Lighthouse)
| Hard | Cipher | [19902](https://user-images.githubusercontent.com/2199511/45245205-e80c1f00-b2ea-11e8-9d5b-6e82cf6a09f0.png ) | Pirate Pete, standing on the dock northeast of the Ectofungus (Puzzle)
| Hard | Cipher | [19908](https://user-images.githubusercontent.com/2199511/45245547-59989d00-b2ec-11e8-8764-099668b24f25.png ) | Fairy Godfather in the Zanaris throne room (Answer: 64)
| Hard | Coordinate | [21526](https://user-images.githubusercontent.com/2199511/45245998-674f2200-b2ee-11e8-9f84-087afec56133.png ) | East of the Museum Camp on Fossil Island (Saradomin wizard)
| Elite | Cryptic | [12121](https://user-images.githubusercontent.com/2199511/45245251-27d30680-b2eb-11e8-948f-138b9aef0cb6.png ) | Talk to Sherlock
| Elite | Cryptic | [19799](https://user-images.githubusercontent.com/2199511/45245510-3c63ce80-b2ec-11e8-9e7d-6bed2da325ab.png ) | Kill a green dragon
| Elite | Cryptic | [19802](https://user-images.githubusercontent.com/2199511/45245293-4fc26a00-b2eb-11e8-8f0e-b60d0ce75381.png ) | Kill an Abberant spectre
| Elite | Cryptic | [19810](https://user-images.githubusercontent.com/2199511/45245632-abd9be00-b2ec-11e8-8772-967827023cd2.png ) | Dig on the toad batta spawn in Tarn's Lair

**Comment by Gamer1120** [comment]
It would be nice if this could happen for Coordinate Clues too. "South of the Morytania Slayer Tower" is a lot more descriptive than "Look at your map to see where to dig".

**Comment by Nightfirecat** [comment]
| Clue Tier | Clue Type | Clue Id | Possible Solution Text
|- |- |- |-
| Easy | Cryptic | [2678](https://user-images.githubusercontent.com/2199511/47113694-377a2f00-d249-11e8-8e54-8936ae460e68.png) | Located on the first floor of the souther tower at the Lumbridge Castle entrance
| Easy | Cryptic | [2687](https://user-images.githubusercontent.com/2199511/47113780-6c868180-d249-11e8-890c-4b8031e2139f.png) | Search the drawers upstairs in Varrock's east bank
| Easy | Cryptic | [2692](https://user-images.githubusercontent.com/2199511/47113740-5082e000-d249-11e8-87da-b449026d1451.png) | Falador general store
| Easy | Emote | [10194](https://user-images.githubusercontent.com/2199511/47111875-47434480-d244-11e8-8bc0-86a2617f476e.png) | Clue text: Headbang in the mine north of Al Kharid. Equip a desert shirt, leather gloves and leather boots.
| Easy | Cryptic | [12188](https://user-images.githubusercontent.com/2199511/47111822-21b63b00-d244-11e8-8089-f5d3467d60d6.png) | House east of Betty's. Contains a cooking sink.
| Medium | Coordinate | [2817](https://user-images.githubusercontent.com/2199511/47054219-1dd0dd00-d1a0-11e8-876d-89ac1e6bc677.png) | In the centre of the mine north of Shilo Village, north-west of fairy ring CKR
| Medium | Cryptic | [2841](https://user-images.githubusercontent.com/2199511/47112107-e9632c80-d244-11e8-88b7-553423ef49fc.png) | NPC: Hazelmere; Location: Located upstairs in the house to the north of fairy ring CLS
| Medium | Cryptic (Challenge scroll) | [2842](https://user-images.githubusercontent.com/2199511/47112112-eec07700-d244-11e8-9121-903c2ca794c0.png) | Answer: 6859
| Medium | Anagram | [2858](https://user-images.githubusercontent.com/2199511/47112045-b6209d80-d244-11e8-9e6f-cb517a878ceb.png) | NPC: Luthas; Area: Banana plantation, Karamja
| Medium | Coordinate | [7313](https://user-images.githubusercontent.com/2199511/47054069-7358ba00-d19f-11e8-8298-a7ddefc02d05.png) | South of the Water altar ruins
| Medium | Coordinate | [12037](https://user-images.githubusercontent.com/2199511/47112183-1e6f7f00-d245-11e8-8c53-f88f4ef4e0b4.png) | In the castle grounds of Fenkenstrain's Castle in Morytania
| Medium | Cipher | [19766](https://user-images.githubusercontent.com/2199511/47054114-a602b280-d19f-11e8-901f-53f131d0b0ba.png) | NPC: Captain Khaleed; Area: Large eastern building in Pscarilius House
| Medium | Cipher (Challenge scroll) | [19767](https://user-images.githubusercontent.com/2199511/47054167-d8acab00-d19f-11e8-8162-6b44bb2d8861.png) | Answer: 5
| Hard | Emote | [10250](https://user-images.githubusercontent.com/2199511/47054404-24138900-d1a1-11e8-8e3a-f88610d82cdb.png) | Clue text: Panic by the pilot on White Wolf Mountain. Beware of double agents! Equip mithril platelegs, a ring of life and a rune axe.
| Hard | Cryptic | [3572](https://user-images.githubusercontent.com/2199511/47054430-4e654680-d1a1-11e8-9381-6e312b74aa05.png) | Search the northern bookcase on the first floor of the Sorcerer's Tower
| Hard | Cipher | [19898](https://user-images.githubusercontent.com/2199511/47054479-91271e80-d1a1-11e8-9c8b-f80bfdc62dde.png) | NPC: Eluned; Area: Outside Lletya
| Hard | Cipher (Challenge scroll) | [19899](https://user-images.githubusercontent.com/2199511/47054485-96846900-d1a1-11e8-860d-c7fbb07b79b2.png) | Answer: 53,000
| Hard | Cipher | [19906](https://user-images.githubusercontent.com/2199511/47054723-ff201580-d1a2-11e8-9ca0-18d91b5dbb13.png) | NPC: King Percival; Area: Fisher Realm, first floor. Fairy ring BJR
| Hard | Cipher (Challenge scroll) | [19907](https://user-images.githubusercontent.com/2199511/47054746-1c54e400-d1a3-11e8-91ee-0e8fefebe337.png) | Answer: 5
| Hard | Cipher (Puzzle box) | [19911](https://user-images.githubusercontent.com/2199511/47054773-3d1d3980-d1a3-11e8-91e8-3d86e7def6c8.png) | N/A
| Hard | Map | [2722](https://user-images.githubusercontent.com/2199511/47106706-d6496000-d236-11e8-9d60-20e9e5aad490.png) | Search a crate in the Lumberyard north-east of Varrock
| Hard | Coordinate | [2723](https://user-images.githubusercontent.com/2199511/47112908-26c8b980-d247-11e8-85c6-ab19714e4bba.png) | In the Wilderness near the two runite rocks located north of the Lava Maze
| Hard | Coordinate | [2731](https://user-images.githubusercontent.com/2199511/47113852-a48dc480-d249-11e8-8855-c23761e33a8c.png) | In the Demonic Ruins in level 44 Wilderness, near the Annakarl Teleport location
| Hard | Coordinate | [2743](https://user-images.githubusercontent.com/2199511/47106928-6c7d8600-d237-11e8-81a7-c886cde6aabc.png) | In the Graveyard of Shadows in the Wilderness (Zamorak Wizard)
| Hard | Cryptic | [2797](https://user-images.githubusercontent.com/2199511/47105989-01cb4b00-d235-11e8-9326-aa7f37e9ed01.png) | Speak to Wilough, next to the Fur Merchant in Varrock Square
| Hard | Cryptic (Puzzle box) | [2798](https://user-images.githubusercontent.com/2199511/47105999-07289580-d235-11e8-909b-c8626f8ee5de.png) | N/A
| Hard | Cryptic | [2790](https://user-images.githubusercontent.com/2199511/47113122-ba01ef00-d247-11e8-8b84-ec02d8b2525a.png) | Dig near the cauldron by the Moss Giants in the Varrock Sewers
| Hard | Cryptic | [2799](https://user-images.githubusercontent.com/2199511/47112368-aa81a680-d245-11e8-9e4e-f116661158c7.png) | NPC: General Bentnoze; Area: Goblin Camp north of Falador
| Hard | Cryptic (Puzzle box) | [2800](https://user-images.githubusercontent.com/2199511/47112380-b0778780-d245-11e8-9ba3-d94af73c74a1.png) | N/A
| Hard | Map | [3522](https://user-images.githubusercontent.com/2199511/47106999-99ca3400-d237-11e8-8d8e-3f5b30c573a1.png) | In West Ardougne, in a crumbling building
| Hard | Coordinate | [3528](https://user-images.githubusercontent.com/2199511/47105476-9765db00-d233-11e8-8ad1-413dd47e42c3.png) | Near entrance to Troll Stronghold, next to the sleeping troll named Mushroom (Saradomin Wizard)
| Hard | Coordinate | [3530](https://user-images.githubusercontent.com/2199511/47105650-080cf780-d234-11e8-9f44-806115c67c59.png) | On Cairn Isle, Karamja, south-west of fairy ring CKR (Saradomin Wizard)
| Hard | Coordinate | [3542](https://user-images.githubusercontent.com/2199511/47106786-11e42a00-d237-11e8-8681-6ef4c2dfbfdd.png) | Just north of the Nature Spirit's grotto tree in Mort Myre Swamp, near fairy ring BIP (Saradomin Wizard)
| Hard | Coordinate | [3546](https://user-images.githubusercontent.com/2199511/47106883-4952d680-d237-11e8-9bf9-665d79f9c0c1.png) | In the center of Gu'Tanoth, requires partial completion of the Watchtower quest (Saradomin Wizard)
| Hard | Cryptic | [3564](https://user-images.githubusercontent.com/2199511/47111425-0f87cd00-d243-11e8-98cf-e05ab9927147.png) | NPC: Lord Iorwerth; Area: Elven camp near Prifddinas
| Hard | Cryptic (Puzzle box) | [3565](https://user-images.githubusercontent.com/2199511/47111439-157dae00-d243-11e8-9d60-f0ef49ba9ce0.png) | N/A
| Hard | Cryptic | [3568](https://user-images.githubusercontent.com/2199511/47112629-6e9b1100-d246-11e8-848c-ebd6cd1c1e50.png) | Talk to Hamid, the monk at the altar in the Duel Arena
| Hard | Cryptic (Puzzle box) | [3569](https://user-images.githubusercontent.com/2199511/47112636-73f85b80-d246-11e8-92e9-0a45bb4d115b.png) | N/A
| Hard | Cryptic | [3579](https://user-images.githubusercontent.com/2199511/47113624-0a2d8100-d249-11e8-880e-7b366fffcb1b.png) | On Entrana, search the southern drawer in the house with the cooking range
| Hard | Cryptic | [3580](https://user-images.githubusercontent.com/2199511/47107685-743e2a00-d239-11e8-9378-278c42f5d3f5.png) | Inside Karamja Volcano, dig directly underneath the Red spiders' eggs respawn
| Hard | Cryptic | [7250](https://user-images.githubusercontent.com/2199511/47107811-d72fc100-d239-11e8-8ba9-6d738f5d5b55.png) | Search the crate, west of the Air Elementals, inside the Elemental Workshop
| Hard | Coordinate | [7258](https://user-images.githubusercontent.com/2199511/47112452-e3ba1680-d245-11e8-8a4a-e521fc6accb3.png) | West of the Bandit Camp in the Kharidian Desert, at the small peninsula
| Hard | Anagram | [7268](https://user-images.githubusercontent.com/2199511/47107370-b024bf80-d238-11e8-8487-e2fd4e41eac5.png) | NPC: Gnome Coach; Area: Gnome Ball course
| Hard | Anagram (Challenge scroll) | [7269](https://user-images.githubusercontent.com/2199511/47107378-b5820a00-d238-11e8-8796-ca7f81850e6f.png) | Answer: 6
| Hard | Emote | [10234](https://user-images.githubusercontent.com/2199511/47111119-2d086700-d242-11e8-85ad-c5d4a639c015.png) | Clue text: Shrug in the Zamorak temple found in the Eastern Wilderness. Beware of double agents! Equip rune platelegs, an iron platebody and blue dragonhide vambraces.
| Hard | Emote | [10248](https://user-images.githubusercontent.com/2199511/47113232-00574e00-d248-11e8-9c4b-cf5e3f6e1775.png) | Clue text: Laugh in Jokul's tent in the Mountain Camp. Beware of double agents! Equip a rune full helmet, blue dragonhide chaps and a fire battlestaff.
| Hard | Anagram | [12572](https://user-images.githubusercontent.com/2199511/47105746-57ebbe80-d234-11e8-9147-959134d589e2.png) | Area: Draynor Village; NPC: Wise Old Man
| Hard | Anagram (Challenge scroll) | [12573](https://user-images.githubusercontent.com/2199511/47105754-5d490900-d234-11e8-9fc0-1bd7e3723551.png) | Answer: 28
| Hard | Emote | [12544](https://user-images.githubusercontent.com/2199511/47111337-d0f21280-d242-11e8-9fcb-d20414990f1c.png) | Clue text: Beckon on the east coast of the Kharazi Jungle. Beware of double agents! Equip any vestment stole and a heraldic rune shield.
| Hard | Anagram (Challenge scroll) | [12575](https://user-images.githubusercontent.com/2199511/47107306-8370a800-d238-11e8-9544-989abcebf8d8.png) | Answer: 129
| Hard | Anagram (Challenge scroll) | [12569](https://user-images.githubusercontent.com/2199511/47113299-2977de80-d248-11e8-8ba2-0394a2bb8f9c.png) | Answer: 40
| Hard | Anagram | [12570](https://user-images.githubusercontent.com/2199511/47110863-786e4580-d241-11e8-8e64-95c988481bba.png) | NPC: Martin Thwait; Area: Rogues' Den
| Hard | Anagram (Challenge scroll) | [12571](https://user-images.githubusercontent.com/2199511/47110870-7e642680-d241-11e8-825b-be7365fbeaf1.png) | Answer: 2
| Hard | Anagram | [12574](https://user-images.githubusercontent.com/2199511/47107296-7ce23080-d238-11e8-9258-c3fbe5f4d867.png) | NPC: Brother Omad; Area: Monastery south of Ardougne
| Hard | Cryptic | [12578](https://user-images.githubusercontent.com/2199511/47107063-cda55980-d237-11e8-8b98-8a935ff60bc3.png) | Speak to Saniboch at the Brimhaven Dungeon entrance
| Hard | Cryptic (Puzzle box) | [12579](https://user-images.githubusercontent.com/2199511/47107088-e7df3780-d237-11e8-9063-da7a5adb2cb0.png) | N/A
| Hard | Cryptic | [12581](https://user-images.githubusercontent.com/2199511/47111733-d9971880-d243-11e8-8322-fe93101b918e.png) | Speak to Ellena at the Catherby fruit tree patch
| Hard | Cryptic (Puzzle box) | [12582](https://user-images.githubusercontent.com/2199511/47111762-eddb1580-d243-11e8-863b-efeb1f260ec2.png) | N/A
| Hard | Cryptic | [12590](https://user-images.githubusercontent.com/2199511/47106119-51117b80-d235-11e8-988f-bac72a750a07.png) | Dig at Barbarian Village, next to the Stronghold of Security
| Hard | Cryptic | [19852](https://user-images.githubusercontent.com/2199511/47106072-33dcad00-d235-11e8-8ce6-f771dc41e4a2.png) | Talk to Zul-Cheray in a house near the sacrificial boat at Zul-Andra
| Hard | Cryptic | [19846](https://user-images.githubusercontent.com/2199511/47107574-36d99c80-d239-11e8-8ed7-3ed5b0cd15f6.png) | NPC: Miner Magnus; Area: Miscellania mine, east of fairy ring CIP
| Hard | Cryptic (Challenge scroll) | [19847](https://user-images.githubusercontent.com/2199511/47107581-3d681400-d239-11e8-8a7d-ab1a4dccf401.png) | Answer: 8
| Hard | Cryptic | [19853](https://user-images.githubusercontent.com/2199511/47106466-1d832100-d236-11e8-947d-5cb04cf194a4.png) | Talk to the Head cook in Cooks' Guild west of Varrock
| Hard | Cryptic (Challenge scroll) | [19855](https://user-images.githubusercontent.com/2199511/47112264-5aa2df80-d245-11e8-883d-312a3619c5c9.png) | Answer: 22
| Hard | Cryptic | [19857](https://user-images.githubusercontent.com/2199511/47111700-ba988680-d243-11e8-9d71-17920bc5b46d.png) | Speak to Wizard Mizgog at the top of the Wizard's Tower south of Draynor
| Hard | Fairy Ring | [19862](https://user-images.githubusercontent.com/2199511/47107726-95067f80-d239-11e8-9aad-ac7441acbb66.png) | Code: A I Q; Area: Mudskipper Point
| Hard | Fairy Ring | [19874](https://user-images.githubusercontent.com/2199511/47106380-e57bde00-d235-11e8-9ac3-658855294dff.png) | Code: C K P
| Hard | Fairy Ring | [19878](https://user-images.githubusercontent.com/2199511/47107768-b8c9c580-d239-11e8-9591-f3e9d9d7a4ae.png) | Code: D K S; Area: Relekka polar area, near Keldagrim cave entrance
| Hard | Anagram | [19884](https://user-images.githubusercontent.com/2199511/47112795-e79a6880-d246-11e8-8d6b-c6e263f15c87.png) | NPC: Awowogei; Area: Ape Atoll
| Hard | Anagram (Challenge scroll) | [19885](https://user-images.githubusercontent.com/2199511/47112806-ecf7b300-d246-11e8-936b-c218e4d79916.png) | Answer: 24
| Hard | Anagram | [19886](https://user-images.githubusercontent.com/2199511/47111022-ea468f00-d241-11e8-8b13-2682e3b4f296.png) | NPC: Lumbridge Guide; Area: Lumbridge
| Hard | Anagram (Puzzle box) | [19887](https://user-images.githubusercontent.com/2199511/47111022-ea468f00-d241-11e8-8b13-2682e3b4f296.png) | N/A
| Hard | Anagram | [19888](https://user-images.githubusercontent.com/2199511/47111948-75288900-d244-11e8-8947-a85e74a84cab.png) | NPC: Dark Mage; Area: Centre of the Abyss
| Hard | Anagram | [19889](https://user-images.githubusercontent.com/2199511/47111963-7d80c400-d244-11e8-86b3-caafed29f1ab.png) | Answer: 13
| Hard | Cipher (Challenge scroll) | [19901](https://user-images.githubusercontent.com/2199511/47106229-9766da80-d235-11e8-91df-7df42460a5eb.png) | Answer: 3
| Hard | Cipher (Puzzle box) | [19903](https://user-images.githubusercontent.com/2199511/47106529-51f6dd00-d236-11e8-8ff0-6076b4377d27.png) | N/A
| Hard | Cipher | [19904](https://user-images.githubusercontent.com/2199511/47111216-70fb6c00-d242-11e8-97b8-8988db6c2b8a.png) | NPC: Weird Old Man; Area: Kalphite Lair entrance near fairy ring BIQ
| Hard | Cipher (Challenge scroll) | [19905](https://user-images.githubusercontent.com/2199511/47111223-76f14d00-d242-11e8-8bd2-0a7b98da8d08.png) | Answer: 150
| Hard | Cryptic (Challenge scroll) | [19909](https://user-images.githubusercontent.com/2199511/47111499-3c3be480-d243-11e8-915c-5416b43001ac.png) | Answer: 64
| Hard | Cipher (Puzzle box) | [19911](https://user-images.githubusercontent.com/2199511/47106555-6b982480-d236-11e8-9202-b8e5b9c5cecc.png) | N/A
| Elite | Cryptic | [12144](https://user-images.githubusercontent.com/2199511/47054346-c8e19680-d1a0-11e8-8559-6bb24b920239.png) | Speak to Kamfreena on the top floor of the Warriors' Guild
| Elite | Cryptic | [12156](https://user-images.githubusercontent.com/2199511/47054251-5e305b00-d1a0-11e8-8d5d-d87327fac8c9.png) | Search the stones several steps west of the Guthixian stone circle in Taverley
| Elite | Cryptic | [19801](https://user-images.githubusercontent.com/2199511/47054361-e282de00-d1a0-11e8-8955-85a5e19e87fa.png) | Kill a Bloodveld. (Mutated Bloodvelds will not work)
| Elite | Cryptic | [21525](https://user-images.githubusercontent.com/2199511/47054286-8029dd80-d1a0-11e8-835b-aa35c7edeb58.png) | Dig next to the fire near the Volcanic Mine entrance
