### ISSUE TITLE
Minimap icons displaying only in fixed mode

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#431]
Currently, the minimap icons (f.e. for fishing spots) are displayed on minimap only in fixed mode, but when changed to resizable mode, they dissapear.

**Comment by Sethtroll** [comment]
So, this "bug" is actually caused by the OverlayLayer.UNDER_WIDGETS making the dots appear under the minimap.

**Comment by Adam-** [comment]
Fixed in 4b2e8cd1cdb0ef8c8aa4f0c8fadc03898870851d
