### ISSUE TITLE
Bank tags input text gets overwritten by new X found text

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#4310]
Since last OSRS update the bank tags searching text gets overwritten with the new jagex text that also shows the items found in bank (what we should probably incorporate into our interface to not remove functionality if we are going to fix this).

Preview:
![screenshot 2018-07-13 13 50 19](https://user-images.githubusercontent.com/5115805/42690322-05b17d7a-86a4-11e8-9af9-31ea305df09a.png)

**Comment by Adam-** [comment]
Fixed in 94fe9de7e04c9399fefb9c5795b84c026455f000
