### ISSUE TITLE
FPS drop with a good computer

### ISSUE THREAD

**Issue by KarimCool** [runelite/runelite#4311]
Hello i'm using runelite to play osrs and I have a problem .
My fps are dropping to 30 when i am on areas with a lot of people ( example : grand exchange ) and i don't think it is normal because I have a computer able to run games like GTA V in ultra settings at 60 fps .
I tried disabling hardware acceleration and using the all platforms client but I experience the same issue.

**Comment by William1Gray** [comment]
Could you tell us your:
OS
Hardware

**Comment by KarimCool** [comment]
Windows 10 familial edition 64 bits
Intel core I5 6400 2.70Ghz
Nvidia Geforce GTX 960 2GO
16 GO of ram

**Comment by dhharris** [comment]
I'm having similar issues.

**Comment by deathbeam** [comment]
Does this happen also on Vanilla client?

**Comment by dhharris** [comment]
No, vanilla client is fine.

**Comment by deathbeam** [comment]
You can try https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration otherwise there is nothing that we can do and FPS should be same as in vanilla
