### ISSUE TITLE
Screenshot Plugin not working for Ranged, Slayer, Prayer Level Ups.

### ISSUE THREAD

**Issue by Jegflax** [runelite/runelite#4312]
Screenshot plugin is not taking screenshots for any level ups, persists over client and system restart. 

| Java Version | (build 1.8.0_171-b11)
| Operating System | Windows 8.1

**Comment by LeviSchuck** [comment]
This is a known problem and affects all level ups. The vanilla Jagex client had an update which changed how level ups are detected.
