### ISSUE TITLE
Teak table in Calculator has wrong Xp Value

### ISSUE THREAD

**Issue by Neokolzia** [runelite/runelite#4317]
- The Exp value of Teak Table as shown and calculated by Runelite is at 270exp, which would be 3 planks of 90 exp Teak, but the Table costs 4 planks and should be 360exp.  I am unsure whether this effects other construction items calculations

- Please include steps to reproduce your issue.
Open Calculator, Go to Construction, Check Exp Value on Teak Table.

**Comment by forsco** [comment]
I'm just looking through the code, currently Teak tables are as follows.

      ```
"level": 38,
"icon": 8118,
"name": "Teak Table",
"xp": 360
```

**Comment by Nightfirecat** [comment]
![untitled](https://user-images.githubusercontent.com/2199511/42727227-5cf0aba8-8792-11e8-8134-9b698a272430.png)

Not sure which Teak Table you're looking at; it's got the correct value in there.

**Comment by Neokolzia** [comment]
Oh I see where the issue is, there is a second item at Lv. 52 called Teak table as well, which isn't the carved one and unsure what it actually is.

![image](https://user-images.githubusercontent.com/39064580/42729250-0b7440e8-8786-11e8-9de9-28e4ef20e775.png)

**Comment by Alexsuperfly** [comment]
the lvl 52 one is the teak kitchen table

**Comment by Neokolzia** [comment]
That makes sense, I wasn't able to find it when I was searching through the Wiki and since it used the same icon it was a bit confusing.  I imagine it should have its name adjusted so it says 'Teak Kitchen Table'
