### ISSUE TITLE
Timer for Extended Super AntiFire

### ISSUE THREAD

**Issue by mrpker9** [runelite/runelite#4321]
**Is your feature request related to a problem? Please describe.**
Just need to add the timer for the extended antifire

**Describe the solution you'd like**

Add that damn timer :)

**Comment by Nightfirecat** [comment]
There is already a timer for that...

https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/timers/GameTimer.java#L66

**Comment by deathbeam** [comment]
Looks like there is.
