### ISSUE TITLE
XP drops without skill icons are misaligned

### ISSUE THREAD

**Issue by Mikest3r** [runelite/runelite#4325]
| Question    | Answer
| ------------| ---------------
| Java Version | 8.0.1510.12
| Operating System | Windows 7

Description: XP drops are sometimes misaligned and are slightly to the left or right. This is without skill icons. 

Reproduce: Turn off skill icons for exp drops and gain some fast xp to see multiple drops at once (e.g. use a blowpipe).

gif of the bug:

https://gyazo.com/2d4cd8095e147f9b012934199a7841f9

I believe this was already happening before the recent XP drop update.

**Comment by Adam-** [comment]
Fixed in 6bf32768f19fdae990ae5edfc42b50052beec42f
