### ISSUE TITLE
Add Leather hide shields to crafting calculator

### ISSUE THREAD

**Issue by Solburst** [runelite/runelite#4326]
Leather hide shields don't appear in the crafting skilling calculator.

**Comment by TheEnigmaThatIsMe** [comment]
Where are the item icon numbers found? Doesn't appear that LEATHER_SHIELD is in ItemID.java, unless its supposed to be HARD_LEATHER_SHIELD?

**Comment by Solburst** [comment]
Sorry i don't understand code at all, just letting people who do code know
that it doesn't appear on the skilling calculator

On Mon, Jul 16, 2018 at 10:52 PM, George Gilmartin <notifications@github.com

**Comment by rbbi** [comment]
@Solburst have you checked out the leatherhide-shields branch on my fork?

**Comment by deathbeam** [comment]
Added in #4331
