### ISSUE TITLE
No information about failure of opening the browser at Linux when user tries to login

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#434]
In case game is unable open the browser window (this do not works on Linux like 90% of time) the game should instead of putting it to console open popup window with the link and informations, that are currently in log (similar popu window that is shown when user tries to exit game while being logged in).

**Comment by skimboarder** [comment]
Hi! I've been using Runelite for some time now and I'm interested in getting involved with the project. 

This seems like a good first start. Is this issue still available?

**Comment by Abextm** [comment]
Yeah, this still needs to be done. Feel free to come on discord if you have any questions.
