### ISSUE TITLE
Caching bank files and allowing user to search/view bank whilst not at bank

### ISSUE THREAD

**Issue by olivermchaleTU** [runelite/runelite#4343]
**Is your feature request related to a problem? Please describe.**
It becomes frustrating when I'm halfway through a slayer task or when I've just been assigned a new slayer task and I'm not sure whether or not I have a item. For example, I get assigned banshees and I don't know whether or not I have earmuffs in the bank. Or, I just want to view the bank for any other reason. Allowing the user to search the contents of their bank whilst not actually at the bank would be useful in many a situation. 

**Describe the solution you'd like**

A button on the right hand side of the RuneLite client where the hi scores, stats, calculator and notes feature is. This button would show you an interface containing what your bank was. The bank files would be cached and refreshed every time the user used the bank.

**Describe alternatives you've considered**

Other implementations include a separate window, button on the client, or a chat command.

**Additional context**

This is a feature popular in the large MMO 'World of Warcraft' For example, the [bagnon addon](https://wow.curseforge.com/projects/bagnon) which boasts 38.5 million downloads. They describe the feature as 

> Ability to view the items of any character, from anywhere... Inventory, bank, vault and guild bank support

 Obviously, you would only be able to view your own characters items. 

I have very limited knowledge of the OSRS/Runelite API, but am affluent in Java. If someone would point me in the right direction/tell me whether this is actually possible, I would be happy to give this a go.

**Comment by ShaunDreclin** [comment]
Baggins > Bagnon tho 😛

**Comment by Hydrox6** [comment]
With the introduction of the Plugin Hub, two plugins fill this issue's request.

* `Bank Value` provides a simple sidebar that can be sorted
* `Bank Memory` provides a searchable sidebar interface, and can view banks from multiple accounts or snapshots you make.
