### ISSUE TITLE
!remindme type feature to alert the user about something at a later point in time.

### ISSUE THREAD

**Issue by BrianAllenGit** [runelite/runelite#4356]
**Is your feature request related to a problem? Please describe.**
The problem is my memory. I constantly attempt to remember to bring an item, or do some goal _after_ finishing something else, and I always forget. It would be great to have a feature somewhat like the reddit bot !remindme so that I can write myself a future message.  Have the message appear as either an OS notification or an in game message. 

Example: `!remindme 10 minutes get water spells`

Simple time based functionality seems fine for now.  Maybe it can be expanded on to include location based features in the future. 

Example: `!remindme ge buy plant pots`

**Describe alternatives you've considered**
Taking b12 to support my poor short term memory.

**Additional context**

**Comment by Nightfirecat** [comment]
If implemented, could be used to extend #1612.

**Comment by Nightfirecat** [comment]
I believe this is well covered by the Time Tracking plugin, which was added to the client some time ago in #4510.
