### ISSUE TITLE
Toggle for OpponentsOpponentName

### ISSUE THREAD

**Issue by ptfo-rs** [runelite/runelite#4361]
Would like a toggle showing the player being targeted by the NPC. Even though it only shows in multi, there's no need for it for solo players which most pvm is nowdays or people don't find it useful. Differing sizes of the box also makes it awkward when wanting the opponent health box in a specific position around other plugin boxes (box enlargens to fit room for player name in multi from standard size when in singles). Owner of a previous thread requesting this closed his own thread but a label tag was added. https://github.com/runelite/runelite/issues/2570

**Comment by laagone** [comment]
+1. It's completely unnecessary when you solo everything, and a lot of PVM takes place in multi-combat areas, including bosses like Zulrah and Sire that are exclusive to solo.
