### ISSUE TITLE
Track and Record GE buy/sell history

### ISSUE THREAD

**Issue by douglasg14b** [runelite/runelite#4377]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
GE buy/sell history tracking. This would be an amazing feature to have for GE flippers, even if it was just a simple list of buy/sell orders and histories.

An expanded scope would be providing insights on that information such as margins, profits, losses, common items bought/sold...etc

**Describe alternatives you've considered**
OSBuddy keeps track of this information and displays a list of  historical purchases and sales on their site under your account.

**Comment by Asymons** [comment]
It was meant to solve a somewhat separate issue, but was marked as duplicate. May work on extending to full list in future.
