### ISSUE TITLE
Add ETA to level up to XP globes

### ISSUE THREAD

**Issue by kbeliasas** [runelite/runelite#4380]
Hi,

can you please add feature which shows how much time is left to level up skill. Couse now it only shows how much actions left and xp/hour rate. Time can be based on xp/houre rate and how much xp left to level up. Thanks.

**Comment by Nightfirecat** [comment]
An ETA is available if you hover the tracker for the specific skill.

**Comment by kbeliasas** [comment]
![image](https://user-images.githubusercontent.com/35032624/42867681-fb35b86a-8a78-11e8-8655-c92b102edb15.png)
![image](https://user-images.githubusercontent.com/35032624/42867692-02c85704-8a79-11e8-9522-53af0459620b.png)
Can't see it :(

**Comment by deathbeam** [comment]
That is not xp tracker, those are xp globes. You have the ETA in sidebar.

**Comment by deathbeam** [comment]
Duplicate of #1041
