### ISSUE TITLE
Nightmare Zone Plugin Add on Request

### ISSUE THREAD

**Issue by NAM31322CRYPT1C** [runelite/runelite#4386]
This necessarily isn't a problem of any sort but would make multitasking while playing a whole lot simpler now it may also possibly be to OP but id like for the community to decide. I am no programmer but might be willing to try and learn some stuff, but as I type this I'm also in NMZ trying to gain levels. 

So when I'm in NMZ I go in with a full inventory of prayer pots, sit in the corner with protecting from melee prayer on and fight at least 4 combatants at a time but mostly for levels, now i do not know if this will fall under NMZ or prayer or what but I suggest that you get an alert "almost identical to when your player is idle from combat" that your prayer is at 10 points or below notifying me to click over and drink some prayer potions to stay above what I need to be.

**Comment by deathbeam** [comment]
There is already feature in idle notifier to notify you if your prayer is below certain value.

**Comment by NAM31322CRYPT1C** [comment]
@deathbeam I looked every but there thank you so much!!
