### ISSUE TITLE
Add a toggle to the raid scouter to allow the overlay to remain when in the raid

### ISSUE THREAD

**Issue by amp4045** [runelite/runelite#4395]
Currently when scouting a raid, the amazing plugin helps scout.  Unfortunately, through many raids I'm often asking myself "crap...what's the next room again?". We should allow the user to toggle the overlay as a sticky to their screen that will not disappear once in the raid. (Perhaps because of this, it needs to move to a new location/become draggable?).

**Comment by deathbeam** [comment]
Duplicate
