### ISSUE TITLE
StretchedFixedModePlugin: Camera resetting

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#4401]
When using the mouse wheel to position the camera, the perspective will snap to a fixed point before moving.

Video showing the issue: https://gyazo.com/397663d642dbc2d91d0500ff6d9c5615

**Comment by Linkandzelda** [comment]
Can confirm, this wasn't there last night and now it's here today.

**Comment by GitFinny** [comment]
I was about to post this to reddit before realising it was a RL thing. I want to add to this issue.

These are only happening in stretched fixed mode, after I went from resizeable to fixed mode after the update.

Number one. 
https://i.gyazo.com/9e50aa2490a118e5d29124d554172fa6.mp4

The camera snaps to some angle whenever I pressed and drag the mouse button and then the cursor doesn't align with where the mouse is in-game. 
Screenshot https://i.imgur.com/r3iFCiE.png
I had cursors off in screenshot but the red circle is where the cursor was but it acted as if it was around that area where the fairy ring is.

Number two. The last right click of this gif. 
https://i.gyazo.com/4c8f5813796462d8cfb03d13ad4a9bd6.mp4

It instantly closes sometimes even though I only right-click.

Thanks!

**Comment by Adam-** [comment]
Maybe we should have a third label 'update' - since this is not broken due to us, but due to logic change in the newer client. The mouse handlers are now calling each other (!) for some reason and we are hooking into the handlers - so multiple events are being fired.
