### ISSUE TITLE
Specific order for boosts

### ISSUE THREAD

**Issue by Learthy** [runelite/runelite#4408]
Currently the boosts shown are ordered depending on the order they were added. For example, during raids, if I drink a prayer enhance followed by an overload, the enhance effect would be shown before the ovld affect on boosts. Could this be changed to have a specific priority order to what is shown first regardless of when you get the boost? An order like konduit's would be good. This saves a few seconds for when having to check for the boost timers instead of having to look for the boost.

**Comment by deathbeam** [comment]
Now they should have specific order
