### ISSUE TITLE
When you press inventory hotkey to all your overlays are hidden

### ISSUE THREAD

**Issue by SirDylan** [runelite/runelite#441]
Shows amount, but not the rune type.

Also when you press F1 or what ever your inventory is bound to all your overlays are hidden.

**Comment by Sethtroll** [comment]
I am unable to reproduce the bug you listed regarding the hotkeys. Is this still happening to you? And if so, provide details such re-sizable/fixed mode or any other details you might think would associate with this bug.

**Comment by deathbeam** [comment]
It happened to me, but I can't reproduce it. I think it is similar issue as we had with bank before (but reversed). Should be separate issue imo, and not together with wrath runes.

**Comment by deathbeam** [comment]
As we are not doing widget-based checks for displaying overlays anymore, this issue should be solved. Reopen if it will occur again.
