### ISSUE TITLE
XP Tracker Target Level

### ISSUE THREAD

**Issue by theletterandrew** [runelite/runelite#4414]
**Is your feature request related to a problem? Please describe.**

Not really a problem, no.

**Describe the solution you'd like**

Having a "Target Level" option: if a user inputs a target level higher than their next level for a skill, then the percentage value, xp left, and actions displayed on the tracker will correlate to this target level.

**Describe alternatives you've considered**

I cannot think of an alternative, other than just not having this feature.

**Comment by deathbeam** [comment]
This is already a feature, but you need to setup target level in vanilla interface, see https://github.com/runelite/runelite/wiki/XP-Drop how to get there.

**Comment by theletterandrew** [comment]
Sorry about that.

**Comment by theletterandrew** [comment]
No wait!

That post has to do with XP-Drops and goals related to when you hover over a stat.

I'm talking about the XP Tracker (with the level icon on the right).

**Comment by deathbeam** [comment]
Yeah, the goal settings set in that interface will reflect in XP tracker in sidebar

**Comment by Nightfirecat** [comment]
Read this section: https://github.com/runelite/runelite/wiki/XP-Drop#goals
