### ISSUE TITLE
Screenshot plugin stopped talking screenshots of Raids 1 chest loot.

### ISSUE THREAD

**Issue by hihi9190** [runelite/runelite#4418]
| Operating System | Windows 10
I completed one Raid on mobile and since after than on PC I no longer get screenshots saved for Raids chest loot. All other screenshot functionality still works other than Raids 1.

**Comment by deathbeam** [comment]
It is named "Chambers of Xeric" now so maybe try checking that.

**Comment by hihi9190** [comment]
Yeah I found them, didn't know the name was changed. Thank you
