### ISSUE TITLE
Fairy ring search is not searching in favorites

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#4419]
When you have fairy ring in your favorites, new fairy ring search fails to find it.

![unknown](https://user-images.githubusercontent.com/5115805/42971453-a0038d2a-8bac-11e8-9644-d71cb22a648a.png)

**Comment by Namekian-Ejaculation** [comment]
@Abextm Hi, can you please make favorited [fairy rings](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/fairyring/FairyRingPlugin.java) searchable? :)

**Comment by deathbeam** [comment]
Closing as wontfix as it is not easily solveable. Easy solution is to just remove stuff from favorites
