### ISSUE TITLE
Slayer count on items suggestion

### ISSUE THREAD

**Issue by Ampl-T** [runelite/runelite#4435]
Hey fellas, Just got a small suggestion, 
I tend to slay with a slay ring in my inv and don't enjoy constantly being able to see my slayer count, but i like being able to switch to my armour tab and see my slayer count on my helm.

So I'm just putting it out there, if you fellas were able to add a toggle so the count can only be shown on certain items (gem, helm, ring, eternal ring) that would be awesome.

**Comment by deathbeam** [comment]
This request is not really necessary, you can just see the count in infobox and disable the inventory counters
