### ISSUE TITLE
Toggle roof not working, always hidden

### ISSUE THREAD

**Issue by Grehgous** [runelite/runelite#4438]
**Describe the bug**
When training agility at Draynor rooftop course I noticed that I can't see the roofs. I tried doing ::toggleroof as well as manually doing it through Options>Advanced Options. I also turned off low detail mode and entity hider just to make sure that those were not the cause. 

**Expected behavior**
I would expect to be able to turn roofs on and off.

**Screenshots**
![image](https://user-images.githubusercontent.com/23343347/43039840-cd612220-8d03-11e8-9097-bd89c13c9566.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.8.1
 - Launcher version: Unknown

**Additional context**
I logged onto to OSBuddy just to compare, and I am able to see roofs properly there. I would have checked the official client but I do not currently have it installed on this PC.

**Comment by deathbeam** [comment]
Disable low detail mode, it is causing this issue.
