### ISSUE TITLE
Reorder Equipment Menu Options

### ISSUE THREAD

**Issue by FoxyToaster** [runelite/runelite#4439]
Is there a possibility of adding an option to reorder things in the equipment menu?

This would be beneficial for changing teleports on skill capes to be the distance as teleports on rings so using windows mouse keys would be consistent. 

I tried to search for a similar request, but could not find one.

**Comment by CaraPis** [comment]
They don't wanna add such features if OSB doesn't add it first, to prevent further disputes with jagex.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
