### ISSUE TITLE
Untradable versions of Pharaoh's sceptre does not have a GE price

### ISSUE THREAD

**Issue by MeicoPotato** [runelite/runelite#4448]
The tradable versions of Pharaoh's sceptre, which are the uncharged version and Pharaoh's sceptre (3) have correct GE prices. The untradable versions (ones that have 1, 2, 4, 5, 6, 7, or 8 charges) do not have a GE price at all. Perhaps the untradable versions could use the uncharged version's prices.

**Comment by deathbeam** [comment]
Fixed in #4664
