### ISSUE TITLE
Chambers of xeric

### ISSUE THREAD

**Issue by thisisrobert22** [runelite/runelite#4450]
Hey if it could be possible can it be added that when lizard-men shaman throw the green poison it marks on the ground like Konduit? Also maybe vanguards with health % and mager would have blue highlighter under it, ranger has green , red has melee and health % like in Konduit? Last thing could the scouting show pictures of the bosses also like Konduit lol..

Thanks!

**Comment by deathbeam** [comment]
For the shamans https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features. For other we already have issues open.
