### ISSUE TITLE
Hot/Cold clue location is wrong for West of the Keldagrim entrance mine step

### ISSUE THREAD

**Issue by Justinas95** [runelite/runelite#4453]
Location is shown on stump: 
![runelite_2018-07-22_23-01-30](https://user-images.githubusercontent.com/16999673/43049670-115e02a8-8e04-11e8-9ef1-7e9f5c3142b3.png)

when true location is this(cursor location is the highlighted stump)
![image](https://user-images.githubusercontent.com/16999673/43049666-04b6e3f8-8e04-11e8-8abc-ec6f9b1aa62f.png)

**Comment by JeljoGb** [comment]
https://i.imgur.com/rcipyOg.png
I have the same clue, for me it's on the marked tile, and not on the stump.

**Comment by MSAskew** [comment]
Resolved in PR #5642

**Comment by Justinas95** [comment]
Nice :)

have a nice evening :P and thank you for what you do :)

2018-09-25 23:01 GMT+03:00 Mike <notifications@github.com>:
