### ISSUE TITLE
Add missing teleport locations to world map

### ISSUE THREAD

**Issue by FearrMe** [runelite/runelite#4456]
Diary reward teleports, teleport crystal(lletya), quest cape, camulet, pharaoh's sceptre teleports and Kharedst's memoirs are missing. There's probably more that are missing, but these are the ones I found.

Teleports that are very close to dungeon entrance also aren't on the map, but this seems to be deliberate. Might be a nice addition, though(think Paddewa, slayer ring rellekka).

~~On roughly the same topic, maybe add a transportation icon with a hover over for the level of wilderness for wilderness obelisks?~~ Duplicate of #4216

**Comment by deathbeam** [comment]
Looks like we implemented quite a lot of those. for any missing, open separate issue for each missing thing and not put them all in one
