### ISSUE TITLE
NPC HP covering up pest control info

### ISSUE THREAD

**Issue by shogunreaper** [runelite/runelite#4457]
The npc health bar in the top left is displayed overtop of the pest control info (void night health/your damage)

here's a picture
https://i.imgur.com/wORx6R9.png

can it be moved down a bit?

**Comment by FearrMe** [comment]
You can move overlays by holding alt and dragging your mouse.

**Comment by shogunreaper** [comment]
thats cool, thanks.

**Comment by deathbeam** [comment]
We have issue open for improvements to Pest Control, and the existing issue can be solved by moving the overlay, so closing
