### ISSUE TITLE
Several dev tool labels are cut off

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#4458]
![screenshot](https://user-images.githubusercontent.com/5851433/43052334-c5523db8-8df2-11e8-98ed-e465157dc94d.png)

Either larger buttons or adding tooltips to the buttons would be great.

**Comment by whitehooder** [comment]
Might as well fix this by making the sidebar resizable. I'm working on it but not gonna make any promises. Soon though, hopefully.
[Demo](https://streamable.com/xt22u)
