### ISSUE TITLE
Double Trouble Slayer Reward Bug

### ISSUE THREAD

**Issue by iTsALFE** [runelite/runelite#4459]
When ever you kill the Grotesque Guardians the KC only goes down 1 on all the indicators instead of 2 as you can see in the image - https://imgur.com/KPi1lZq - Its also doesn't show on the Slayer rings and the actually Slayer KC counter.

Thought I'll let you know :)

**Comment by Nightfirecat** [comment]
Please feel free to re-open the issue, since that lets us know that it's still a bug that's being encountered.

**Comment by whitehooder** [comment]
Duplicate of #4336
