### ISSUE TITLE
rearrange spellbook

### ISSUE THREAD

**Issue by willin275** [runelite/runelite#4467]
ive seen a few requests to be able to rearrange the spellbook, to which people reply that they cant see a practical use for it or that its a duplicate post, however please hear me out, i think it would be an extremely useful feature for things such as stun alching, both icons could be placed next to each other at the top left of the spellbook, or when doing agility you could place the high alch spell on the left of the spellbook meaning less distance to move the mouse across the screen, making it easier to do. 
![spellbook](https://user-images.githubusercontent.com/41592601/43097675-b8ac26ce-8eb4-11e8-97a9-6f36a2c134b8.png)

**Comment by William1Gray** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

Spellbook Re-ordering and Hiding: Other 3rd party clients do not have these features and it failed a Jagex poll (see #1038)

**Comment by deathbeam** [comment]
Yeah, its not like it would not be nice, we simply dont want to add it at the moment.
