### ISSUE TITLE
Add a context menu altering plugin

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#447]
Has been talked about on discord, making a note here so we don't forget!

Possible uses/features:
• Move "Exchange" option to the top of exchange clerks
• Move "Bank" option to the top of bankers
• Move "Pickpocket" option to the top of pickpocketable npcs
• Move "Use Item ->" to the top of furnaces (for when players are in the way)
• Hide "Bury" option on bones while in ectofuntus and poh
• Hide "Chop down" option on trees (they get in the way!)

**Comment by deathbeam** [comment]
Depends on #374

**Comment by Abextm** [comment]
- Fairy ring reordering

**Comment by Adam-** [comment]
Fixed in #627
