### ISSUE TITLE
(mockup included) manual pausing and ability to clear xp tracker

### ISSUE THREAD

**Issue by tyrdev** [runelite/runelite#4471]
Sorry if either have these have been suggested already, but a couple feature requests for the XP Tracker -

Could there be a way to manually pause skill progress on the tracker?  It could be presented as a pause button when the user hovers over the progress bar or something upon those lines.  It would be nice just to have that ability alongside the timer if you'd rather do it yourself.

Secondly, it would be nice to have a button at the top to clear the XP tracker.  This would help clean up the inevitable clutter if you're training multiple skills in one session.

Very crappy mockup of both: 
![capture](https://user-images.githubusercontent.com/23371618/43118191-bb4d6896-8ede-11e8-8007-c3761dba31da.PNG)

**Comment by deathbeam** [comment]
We already have both as right-click menus.
