### ISSUE TITLE
Slayer task kills remaining should resynchronise based upon text events

### ISSUE THREAD

**Issue by NathenSample** [runelite/runelite#4473]
Slaying on an unlinked Runelite, any other client, mobile etc will result in your actual kills remaining desyncing from the actual value.

This is fairly simple to rectify by simply checking kills on a slayer gem, however for those of us who've yet to acquire helms, and become so used to Runelites functionality that they never bring a gem, this can be mildly frustrating.

To rectify this whenever the user receives a 

`You still need to kill X monsters to complete your current Slayer assignment`

message, we should use its value to refresh the kills remaining, thus allowing the counter to once again accurately update.

**Comment by deathbeam** [comment]
When do you receive that message?

**Comment by FearrMe** [comment]
@deathbeam It's the [combat bracelet](http://oldschoolrunescape.wikia.com/wiki/Combat_bracelet).

**Comment by Nightfirecat** [comment]
@deathbeam Wrong issue, you're looking for #4773.
