### ISSUE TITLE
Add multiple types of highlighted items

### ISSUE THREAD

**Issue by EpicCows** [runelite/runelite#4475]
So I play with my ground items off except highlighted ones in the ground item overlays - I have a few slayer tasks where I want to see some items, but they're not big ticket items, so I'd prefer if there was a way to have like Highlighted items 1 and Highlighted items 2 or the ability to make as many as you want so that you can have items still display but different colours not just based on values.

This is just so that I don't glance over, see purple text and be like oh damn that's the item I'm hunting for! before being disappointed when I actually click it... e.g. I can set noted raw sharks to orange at trolls so I still know to pick them up but know it's not like long bones or something which I'm actually excited for, so I could keep long bones in highlighted one but noted sharks in highlighted 2.

Not important at all but would just be nice to have the ability to have a bit more control over the colours of ground overlay highlights and easier instantaneous differentiation.

**Comment by deathbeam** [comment]
You can have mutliple tiers of items with price thresholds. So this is already a feature, as the "big ticket" items you are talking about usually have high prices.
