### ISSUE TITLE
Entity Hider - Doesn't hide players on the same tile as you.

### ISSUE THREAD

**Issue by lulwut** [runelite/runelite#4480]
Players who are standing on the same tile as you are able to be interacted with items (for example dragon bones when using gilded altar on W330), however players who are on different tiles are (correctly I assume) cannot be "used" on.

**To Reproduce**
Stand on a tile with a lot of players (A public house on world 330 gilded altar)
Click bone and hover your own players tile and click
The bone will be "used" on the player

**Expected behavior**
Hidden players should not be able to be interacted with

**Screenshots**
[Using an item on players on the same tile](https://media.discordapp.net/attachments/466519346672435210/471271365022973973/unknown.png?width=625&height=411)

[Expected behaviour](https://media.discordapp.net/attachments/466519346672435210/471271420941434880/unknown.png?width=625&height=411)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.8.1
 - Launcher version: "Unknown"

**Comment by shanekautz** [comment]
I am testing at the GE:

- able to 'use' item on players standing on my tile
- able to 'use' item on players standing on different tile(s)

[GIF](https://i.gyazo.com/2fb39b065d8b9b26451c42ac27268c92.mp4)

Is it possible the large number of players at w330 altar are causing surrounding players to not fully render, making it impossible to 'use' item on? When SparcMac does giveaways the game can only visually render 1 tile worth of players.

>  players who are on different tiles are (correctly I assume) cannot be "used" on.

I don't think this is intended behavior. It would make prayer training easier, but I'm afraid this is built in to OSRS.

**Comment by Kamielvf** [comment]
I assume the reason it "fails" to hide players beneath you is because the method we are intercepting and determining if the player should be hidden or not is never hit.

**Comment by lulwut** [comment]
This also happens at barb fishing when I'm 3 ticking (and mess up) even when theres only a couple of other players around me.

**Comment by FearrMe** [comment]
It doesn't show the players under you if your local player is hidden as well. Seems like a bug.

**Comment by deathbeam** [comment]
This is exactly same problem as with #1979 just different scenario.
