### ISSUE TITLE
Add a hotkey to completely hide the sidebar

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#449]
Title.

Also, hotkeys to pop open the sidebar to a specific tab would be nice too.

Possibly something like Ctrl-Esc to close, Ctrl-F1 for first tab, Ctrl-F2 for second, etc.

**Comment by Adam-** [comment]
Duplicate of #656

**Comment by ShaunDreclin** [comment]
Uhh #656 is a duplicate of *this* issue :p
