### ISSUE TITLE
Master clue in pyramid plunder checks for wrong item

### ISSUE THREAD

**Issue by duracell33** [runelite/runelite#4493]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
the master clue in pyramid plunder checks for "Menaphite purple robe" it should be "Menaphite purple kilt"
**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment]
It doesn't check the wrong item, it just doesn't check for all combinations of menaphite robes. I've opened #4494 to fix this.
