### ISSUE TITLE
Log in Screen Glitch

### ISSUE THREAD

**Issue by g02h** [runelite/runelite#4495]
When the log in screen loads up, there is pixels that keep flicking in different parts of the client. This is for the all platform.

**Comment by Joshua-F** [comment]
Give https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration a try.

**Comment by g02h** [comment]
Im using it on a mac so how does that work? The directions seem to be for windows only

**Comment by g02h** [comment]
Yeah no idea how that works. Thanks for answering probably won't be able to use runelite ever again.

**Comment by whitehooder** [comment]
Lol... Come chat in #support and we'll help you out :)
