### ISSUE TITLE
Add mark point on the world map 

### ISSUE THREAD

**Issue by jacienpang** [runelite/runelite#4496]
I suggest to add mark point on the world map because sometimes might forgot where to go without marking. The purpose of mark point is to let players to point at their destination. After left click of the mouse once on the world map, the mark point will pointing the destination of the player that the player wishes to go. As what the picture shows:
![image](https://user-images.githubusercontent.com/40648537/43187964-89d7ecda-9025-11e8-8fdc-72683198257c.png)

**Comment by Rman887** [comment]
This exists on the plugin hub: https://github.com/iipom/map-waypoints

**Comment by stoddy15** [comment]
> This exists on the plugin hub: https://github.com/iipom/map-waypoints

why isn't this a default plugin? it should be built in and enabled for everyone.

**Comment by Nightfirecat** [comment]
If the author of that plugin wants to have it added to the main client, they're welcome to open a pull request on this repository with their code. :)

**Comment by al3x-huang** [comment]
In case others want to add this plugin - it's not immediately clear from the discussion above how to do it. 

Go to plugin tab -> scroll to bottom -> click 'Plugin Hub' -> type in search box 'map waypoints' -> install it 

Now you can right click anywhere on world map and then set a waypoint!
