### ISSUE TITLE
Highlight motherlode mine upper area ladder

### ISSUE THREAD

**Issue by Littik** [runelite/runelite#4497]
The ladder is hard to see sometimes and has a lot of people going through. The ladder is brown and it kind of blends in with the land below

Highlight the ladder, perhaps add it into the motherlode mine plugin

![2018-07-25_11-47-59](https://user-images.githubusercontent.com/38294768/43221566-0f357dbc-9002-11e8-9552-63b353901e5d.png)

**Comment by deathbeam** [comment]
Before anyone starts working on this, I feel like this would be solved with generic object marking plugin (for what we have feature request open somewhere). For now I guess you can use ground markers to mark the bottom and top of the ladder, that is what I do.

**Comment by Gamer1120** [comment]
I do the same as Deathbeam.
