### ISSUE TITLE
Wealth evaluator/Rune Metrics

### ISSUE THREAD

**Issue by Jwcsg** [runelite/runelite#4498]
Something similar to Runescape's version which is capable of tracking the value of your bank/account and keeps track to show your money gain per hour/week/month etc

http://runescape.wikia.com/wiki/RuneMetrics

Doesn't have to be an overlay. Can be on like the RHS along with farming plugins etc

https://i.imgur.com/qjlQQ13.png

**Comment by cnkeats** [comment]
Maybe with a graph like WoW's "Tradeskill Master - Accounting" addon?

https://i.imgur.com/jNpT8GF.png

**Comment by raiyni** [comment]
This was added in the plugin hub.
