### ISSUE TITLE
Save different settings per account

### ISSUE THREAD

**Issue by Claws14124** [runelite/runelite#4499]
When I play, sometimes I enjoy playing on a couple of different accounts. Something that I constantly find myself thinking could be cool would be to have different settings for each account. This way, I could save different bank tags for farm runs on each account as I use different things on both accounts and it would clutter the search to include both sets of items in one search. I could also see this being useful for a ton of other things, but that is the main one I want.

**Comment by Nightfirecat** [comment]
Duplicate of #2220
