### ISSUE TITLE
Sound of Idle Notifier

### ISSUE THREAD

**Issue by zeno17** [runelite/runelite#4508]
Hello,

I am currently using the Idle Notifier when RCing on Zeah but the volume of the notification is extremely loud and id like to reduce it (not mute). Now normally i could do this by adjusting system sounds in the volume mixer but this doesnt work. In fact, even if i completly mute both system sounds and runelite in the volume mixer it still plays the notification at an absurd volume.
![image](https://user-images.githubusercontent.com/33040059/43265640-a5d23f02-90e9-11e8-8624-75a39b523ef6.png)

It seems that RuneLite ignores the settings of the system sounds but at the same time isnt adjustable through the client?

**Comment by whitehooder** [comment]
This is strange as it should be using the standard system alert. Did you check if another entry pops up in the volume mixer as the sound is played?

**Comment by deathbeam** [comment]
It is using system sounds, you need to somehow adjust them somewhere (notification sounds maybe?). There is already issue open for custom sound so this one can be closed.

**Comment by zeno17** [comment]
@whitehooder I just checked this and no this is not the case

**Comment by whitehooder** [comment]
Suppose you could replace the alert sound with something that isn't as loud, but it's a rather hacky solution.

**Comment by zeno17** [comment]
This seems to be the only way to do it as it is a bug in Windows 10 itself that has not been fixed since 2015. Taking the .wav file from the default noise and using a program to reduce it in decibels and selecting the fixed version seems the only way to effectively deal with this.
