### ISSUE TITLE
Client takes a screenshot every time I type the letter s

### ISSUE THREAD

**Issue by Twiglet1022** [runelite/runelite#4513]
**Describe the bug**
Every time I type the letter s runelite takes a screenshot. My screenshot shortcut is set up to ctrl+s and I don't have sticky keys enabled (which could cause the ctrl key to be permanently active).

**To Reproduce**
1. Set the screenshot shortcut to ctrl+s and type the letter s.
2. Try this with any other combinations like ctrl+d for example. Typing d will take a screenshot.

**Expected behavior**
A screenshot should only be taken when I press both ctrl and s at the same time, given that my screenshot shortcut is set to ctrl + s.

**Screenshots**
Oh I got lots. Check it out. https://imgur.com/a/pHugyAu

**Environment (please complete the following information):**
 - OS: Windows 10.1
 - RuneLite version: 1.4.9
 - Launcher version: Unknown

**Additional context**

**Comment by deathbeam** [comment]
Any idea what can cause this @Abextm ?

**Comment by 392781** [comment]
I tested and this occurs regardless of modifier set.  In addition to this I found that the modifier value that's being found is 128 or 0x80 for ctrl.  It does the same for shift which is 64 or 0x40.
