### ISSUE TITLE
Colour Selection not working

### ISSUE THREAD

**Issue by IanWONeill** [runelite/runelite#4514]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When using the magnifier to select a color.

**To Reproduce**
1. Go to 'XP Globes'
2. Click on 'Progress arc Color'
4. Click on '[(())] Color select'
5. See error.

**Expected behavior**
The right colour to be shown.

**Comment by Kamielvf** [comment]
Works for me.

**Comment by IanWONeill** [comment]
Shows the wrong colour for me. Asif the mouse is about 100px off.

**Comment by IanWONeill** [comment]
![image](https://user-images.githubusercontent.com/20154372/43293061-34f1f0c4-9130-11e8-84ca-572d8e24d994.png)

**Comment by Kamielvf** [comment]
If you are talking about the color in the sidebar, this is intentionally shown in a less bright color else the white-on-white text would not be readable. Ingame however, it will be the same color as you have picked.

**Comment by deathbeam** [comment]
Yeah, it works in-game.
