### ISSUE TITLE
Slayer highlight target doesn't color the target's minimap dot properly.

### ISSUE THREAD

**Issue by Voltimolt** [runelite/runelite#4518]
**Describe the bug**
The highlight target normally would color the yellow dot but I seem to have 2 different dots, the normal yellow one and the custom color dot that is offset with the yellow dot.

**Screenshots**
![minimap](https://i.imgur.com/kjH9WyR.png)

**Environment (please complete the following information):**
 - OS: Windows 10 64-bit
 - RuneLite version: 1.4.9.1
 - Launcher version: 1.5.2

**Comment by Adam-** [comment]
Fixed in #4532. The way we are calculating minimap position changed recently to support the dynamically positioned minimap, and the minimap overlay was not updated to correct for it.
