### ISSUE TITLE
On-Screen Jewellery Charge Count

### ISSUE THREAD

**Issue by Meow764** [runelite/runelite#4520]
So yes, you can see jewellery charge counts on top of the item in your gear tab, but that really isn't enough for e.g. runecrafting, especially lavas. Need an actual on screen counter example [here](https://i.imgur.com/HdAZrIk.png) from an other client.
You have to make split second decisions on whether or not you want to take out a new dueling ring/binding necklace when at the bank, and you really can't do that with the charge counters only being able to be seen from the gear tab.

And please don't let me see replies like "oh, look at the charges before you go to bank" or "read what the charges say in your chatbox". That would impossibly inconvenient.

I can't imagine this being a too big of a thing to do, since there already are those stat drains and whatever in the "on screen tiles". So please, I'm begging. Who can I bribe to get this feature implemented?
This is the only feature missing from RuneLite so that I'd be able to use it.
I'm stuck using a crappy 3rd party client where the devs don't give a flying fuck about the client anymore because that client has this feature. 
Seriously can't wait to get away from that shitty client that starts with the letter K and ends with onduit, so please please help me. RuneLite is where the cool kids are at. Let me be apart of the cool kids.

**Comment by deathbeam** [comment]
We already have issue open for this, closing as duplicate
