### ISSUE TITLE
Highlight birdhouse being empty

### ISSUE THREAD

**Issue by Invalids** [runelite/runelite#4527]
I'm a dumb person who often forgets to fill my birdhouses with seeds (Even after 100+ runs I'm still doing it...).

A red overlay in the square of a Birdhouse (Empty) would be fantastic for me. It wouldn't have to do much, just highlight a birdhouse that isn't filled and disappear when the birdhouse is filled.

I've considered just getting gud, but that hasn't worked so far.

**Comment by deathbeam** [comment]
Looks like we will not be implementing this
