### ISSUE TITLE
Add alt hotkey to quickly highlight/hide drops.

### ISSUE THREAD

**Issue by SirDylan** [runelite/runelite#453]
Hold alt to bring up a small menu left of the item on ground overlay allowing you to quickly hide and show items.

![untitled](https://user-images.githubusercontent.com/35585687/35443143-9ba985ac-026f-11e8-8ea0-376e99b90f56.png)

**Comment by ShaunDreclin** [comment]
I'd say ctrl, I think that's what other clients use.

**Comment by TheSexyNerd** [comment]
I'd remove the 2nd option and leave it to a singular toggle-able box, it will get too crowded when there's multiple drops on the ground.

**Comment by ShaunDreclin** [comment]
Could be done like Konduit does it, have two tick boxes with no text on them but when you mouse over, it changes the item name into the option you're selecting.

![Example](https://user-images.githubusercontent.com/5851433/37188170-c25c3858-231b-11e8-8ccc-074a307187b5.gif)

**Comment by sethtroll** [comment]
I have a current WIP of what I'm working on. I am also looking at #674 being merged before I PR this.

![animation_4](https://user-images.githubusercontent.com/5454364/37188275-ea315eb0-2313-11e8-93f1-9f6eed6fb289.gif)

**Comment by ShaunDreclin** [comment]
Oh very nice! ❤️
