### ISSUE TITLE
worldToCanvas marks below ground surface

### ISSUE THREAD

**Issue by forsco** [runelite/runelite#4530]
**Describe the bug**

worldToCanvas is currently marking below ground level.

**To Reproduce**
1. Enable Tile Indicators plugin
2. Head to any Y axis location greater than the games ground level
3. Click a destination to walk to
4. Marking won't be on the surface your character is on

**Expected behavior**
Indicator should be on the surface, not the sub level.

**Screenshots**

https://lambda.sx/PtL.gif

https://lambda.sx/YCk.png

**Environment (please complete the following information):**
 - OS: Win10
 - RuneLite version: Current Master

**Comment by forsco** [comment]
Updated

**Comment by forsco** [comment]
The changes made last night have now resolved the issue I reported on.

**Comment by deathbeam** [comment]
Then I guess it should be closed
