### ISSUE TITLE
On screen indicator for NMZ power ups

### ISSUE THREAD

**Issue by shogunreaper** [runelite/runelite#4531]
Can an on-screen indicator showing which power ups are currently spawned in nmz be added?

Sometimes the chat just goes by too fast and if i'm not paying 100% attention i'll miss it.

I think right beside the potion icons would be a good spot.

**Comment by Nightfirecat** [comment]
I'd recommend using the Chat Notifier to get notifications when powerups spawn.

**Comment by deathbeam** [comment]
Duplicate of #2278
