### ISSUE TITLE
Ground Item Timers

### ISSUE THREAD

**Issue by tgeene** [runelite/runelite#4535]
When doing safe spot combat, it kind of sucks running out to grab loot from the ground every time something nice drops. It would be wonderful if players could have the option to see a timer next to the ground item labels that tell the player how long until the items despawn. This could potentially be limited to items that are above (x) threshold. Doing this would allow player to only have to go pick things up once they are close to despawning.

**Comment by deathbeam** [comment]
Duplicate

**Comment by tgeene** [comment]
Can someone link the original thread? I did try to look and verify that it wasn't duplicate. I guess I missed it somewhere.

**Comment by Nightfirecat** [comment]
#2383
