### ISSUE TITLE
The more you are zoomed out the more off are the tile highlights in fixed mode

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#4539]
Zoomed out more:
![screenshot 2018-07-28 09 39 58](https://user-images.githubusercontent.com/5115805/43354333-6bbf0338-924a-11e8-8b17-2df9c0def864.png)

Zoomed out less:
![screenshot 2018-07-28 09 37 59](https://user-images.githubusercontent.com/5115805/43354334-6c027cc6-924a-11e8-8b80-b00e60779b38.png)

Side
![screenshot 2018-07-28 09 43 47](https://user-images.githubusercontent.com/5115805/43354348-cea8ab98-924a-11e8-947b-6ca40dffca12.png)

**Comment by cmg5461** [comment]
see https://github.com/runelite/runelite/issues/2420

**Comment by deathbeam** [comment]
Oh so it actually was an issue.
