### ISSUE TITLE
Saving and using multiple logins

### ISSUE THREAD

**Issue by shuyin82** [runelite/runelite#4540]
**Is your feature request related to a problem?
YES, I use many account at once... it's very frustrating having to manually enter each login email/password for each account. (bear in mind in my case it's at the most extreme scale, I play over 10 accounts at once).

**Describe the solution you'd like**
A feature to save all login emails to a local database (not passwords), a feature to click from a list to automatically fill in the login info in game. 

**Describe alternatives you've considered**
currently the only way to "sort of" do this is to use a bot client...

**Comment by CaraPis** [comment]
You could also use an ahk login script. Here is a decent guide on how to set it up and also how to make it only work on a certain client so it doesn't interfere with other tabs you might have open on your desktop.
