### ISSUE TITLE
Add a color highlight to items to denote type (green highlight around range, purple around mage, blue around melee.

### ISSUE THREAD

**Issue by BrianAllenGit** [runelite/runelite#4541]
**Is your feature request related to a problem? Please describe.**
It's not a problem, it would just make swapping much easier if the items to switch to were highlighted.

**Describe the solution you'd like**
Something similar to this: 
<img width="240" alt="screen shot 2018-07-28 at 9 42 14 am" src="https://user-images.githubusercontent.com/8545472/43358703-beaa1876-924a-11e8-9bbe-690a8bf27932.png">

**Describe alternatives you've considered**
Hand made scripts.

**Additional context**
None

**Comment by deathbeam** [comment]
You can already do that with inventory tags? I dont see the missing feature here

**Comment by BrianAllenGit** [comment]
Ahhhhhh my error. I just saw the picture from someone else and they claimed it was their own script they run.
