### ISSUE TITLE
RuneLite not launching and when it does cannot world hop and very laggy

### ISSUE THREAD

**Issue by AchillesV10** [runelite/runelite#4544]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I try and launch RuneLite and it takes almost 3 launches to get the application to boot up. Once it does world hopping from the login screen does not work, and i get a error connecting to server error. Runelite has been working perfectly since about 8 hours ago. 

**To Reproduce**
1. Double Click on Runelite launcher icon
2. keep double clicking till the launcher loads
4. See error connecting to server and extremely slow login along with lag in game that no one else is experiencing. 

**Expected behavior**
RuneLite should launch on first double click. World hopping from login should be smooth as well as in game. Lagg should be minimal.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.9.1
 - Launcher version: 1.6.0
[application.log](https://github.com/runelite/runelite/files/2238189/application.log)
[launcher.log](https://github.com/runelite/runelite/files/2238190/launcher.log)

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by rhysowen** [comment]
Does this happen in other clients such as vanilla/OSBuddy?

**Comment by AchillesV10** [comment]
Yea just checked it seems to be happening on all three whats causing this?

**Comment by rhysowen** [comment]
Are you able to access [http://oldschool.runescape.com/jav_config.ws](http://oldschool.runescape.com/jav_config.ws)? It seems to be timing out whilst making the request. I imagine the issue will resolve itself.

**Comment by AchillesV10** [comment]
So you want me to go the website in browser?

**Comment by rhysowen** [comment]
Sure.

**Comment by AchillesV10** [comment]
Yup it loads forever on both chrome and edge.

**Comment by rhysowen** [comment]
Try running a traceroute and see if there's a hop hanging you up. I imagine this issue will be closed as it's not a RuneLite specific issue.

**Comment by AchillesV10** [comment]
![trace route](https://user-images.githubusercontent.com/41838788/43361594-a1308d7e-92a0-11e8-917a-6878a32cb785.PNG)
I ran the traceroute this is the result i got.

**Comment by thaumavorio** [comment]
> FIOS_Quantum_Gateway.fios-router.home

Verizon has been having issues all day (28 July). I expect this bug is from something on their side.

**Comment by AchillesV10** [comment]
OK so basically wait this out?

**Comment by deathbeam** [comment]
Well that looks like you cant access OSRS so this is not related to RuneLite.
