### ISSUE TITLE
Improvement to the 'Instance Map'

### ISSUE THREAD

**Issue by ElevatedLife** [runelite/runelite#4545]
In its current form the built in RL map only shows you a small area around your current location.
The Built in OSRS 'Floating Map' is clunky and I avoid using it at all costs.

I am proposing that more functionality is added to the instance map, i.e the ability to scroll past the currently limited shown region and the ability to see levels above or below you.

1 example of when this could be especially useful is in the Chambers of Xeric, sometimes you may want to see what the blind room ended up being (i.e ice with no scavengers before it) with the current map you can't see it until you run up to it. Also the ability to see the rooms on the bottom floor is very convenient. 

Obviously there are many other places that this could be used.

**Comment by Kamielvf** [comment]
1) You can already scroll using mousewheel to traverse planes
2) It shows you as much as other clients do, if you would compare the map vs. OSB's you would see the same area visible.

**Comment by ElevatedLife** [comment]
> You can already scroll using mousewheel to traverse planes
> It shows you as much as other clients do, if you would compare the map vs. OSB's you would see the same area visible.

On Osb you can drag across to reveal more. or zoom in / out.

**Comment by Kamielvf** [comment]
It does not reveal more, it just shows less initially because it is zoomed in / cropped out partially.

**Comment by deathbeam** [comment]
Looks like features requested here for instances are already present.

**Comment by kaydiechii** [comment]
bumping this request, it's 2022 and we still cant click to drag and move around the instance map, making it bascially unusable in most cases
