### ISSUE TITLE
"Actions Left" is horribly inaccurate

### ISSUE THREAD

**Issue by 0fif** [runelite/runelite#4546]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

Please see the screenshot: https://i.imgur.com/14LvvCY.png

As you can see, I have 19,491 crafting experience from my next level.
I am getting 52.5 exp drops per orb made.
In reality, I need to make 371.2571428571429 actions left (orbs) to make; not 14K.

Here's another taken a few minutes later as I typed this:
https://i.imgur.com/I3jiR0M.png

**To Reproduce**

Honestly a lot of skills are doing this, including slayer, herblore, fletching, and even woodcutting.

**Expected behavior**

I would expect it to do math correctly I guess.

**Screenshots**

https://i.imgur.com/14LvvCY.png

and later: https://i.imgur.com/I3jiR0M.png

**Environment (please complete the following information):**
 - OS: Windows 10 
 - RuneLite version: [1.4.9.1]
 - Launcher version: [1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by deathbeam** [comment]
You probably have set XP goal, and the XP globes are taking actions left from XP tracker what uses them, but they are not taking rest of the XP data from there, so its messy like that.

**Comment by 0fif** [comment]
I don't have an XP goal or a target set.

https://i.imgur.com/9BzVrO4.png

**Comment by deathbeam** [comment]
Not there, in vanilla interface. In this interface https://github.com/runelite/runelite/wiki/XP-Drop

**Comment by 0fif** [comment]
https://i.imgur.com/t89sSZs.png

**Comment by deathbeam** [comment]
This should not be issue anymore, or at least now the XP left/actions left etc are using same values from XP tracker and I was not able to reproduce this issue
