### ISSUE TITLE
ItemContainer for INVENTORY doesn't decrement when items are dropped

### ISSUE THREAD

**Issue by jbassos** [runelite/runelite#4548]
```
final ItemContainer itemContainer = client.getItemContainer(InventoryID.INVENTORY);
      
  if (itemContainer == null)
        {
            return -1;
        }

        final Item[] items = itemContainer.getItems();
```
`items.length`
Increments when new items are added to the inventory, but stays the same when items are removed from the inventory. The size of the item container should decrease when items are removed.

**Comment by Abextm** [comment]
This is working as intended, If you want a higher level api use `InventoryItemQuery`
