### ISSUE TITLE
Have an option to automatically pause XP/h tracker upon logout/hop/disconnection from game

### ISSUE THREAD

**Issue by day2406** [runelite/runelite#4549]
**Is your feature request related to a problem? Please describe.**
There should be an option to automatically pause the XP/h trackers when you logout or disconnect. A lot of people like myself have the client open all day even if we're not logged in and the XP/h trackers get annoying when they keep tracking all day even if you aren't logged in.

**Comment by deathbeam** [comment]
That is already a feature
