### ISSUE TITLE
Display item stats even when they'd have no effect

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#455]
Currently, item stats for items that replenish HP/Stamina aren't so useful while my HP/Stamina is full:
![Stew of +0 health](https://user-images.githubusercontent.com/34518321/35456834-d39810a2-02a4-11e8-9a09-4d9c71fb8f69.png)
![Strange fruit of +0 stamina](https://user-images.githubusercontent.com/34518321/35456921-1af69f9a-02a5-11e8-91a8-e7711f35a59d.png)

It'd be nice if there was a way to see what the item is theoretically able to restore instead of/in addition to how much it will restore when consumed

**Comment by deathbeam** [comment]
Well, you want to see usually the how much will be currently restored. But, I can see the other case being useful as well, togglescape maybe?

**Comment by Adam-** [comment]
Fixed in #527
