### ISSUE TITLE
Idle notfication's don't go off sometimes

### ISSUE THREAD

**Issue by Bren002** [runelite/runelite#4556]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
1. Go to When i'm woodcutting

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 
 - RuneLite version: Runelite version 1.4.9.1
 - Launcher version: Unknown

**Additional context**
I havent changed any settings with windows notifications.

**Comment by deathbeam** [comment]
Enable "Send notifications when focused" in RuneLite settings
