### ISSUE TITLE
!lvl Cmb command

### ISSUE THREAD

**Issue by ElevatedLife** [runelite/runelite#4561]
straight forward, a command "!Lvl Cmb" that displays your 8 combat details. cmb level, atk, str, def, hp, mage, range , and pray. Its a quick and effective way to show your build.

**Comment by deathbeam** [comment]
I believe in OSB it is just `!cmb` so maybe we should follow that.

**Comment by Nightfirecat** [comment]
[From their features page](https://rsbuddy.com/osbuddy/features):

> **Chat Commands**
> Adds commands to the chat! Try `!cmb`, `!total` and `!lvl` skill_name

So I have to agree, `!cmb` seems like the way to go.

**Comment by Adam-** [comment]
Added in #3808
