### ISSUE TITLE
Achievement diary typo

### ISSUE THREAD

**Issue by memementor** [runelite/runelite#4563]
![image](https://user-images.githubusercontent.com/41897069/43388187-ce28af46-942b-11e8-9566-5dd04b5957dc.png)
![image](https://user-images.githubusercontent.com/41897069/43388209-e1e3cbf6-942b-11e8-93ce-a1487cdc275d.png)
In the hard lumbridge/draynor diary...
says i need 68 farming but really i know i need 63

**Comment by generiskk** [comment]
Since its under the same, I will add this too. 


![](https://i.imgur.com/wBRMf6Z.png)
![](https://i.imgur.com/tDlxccj.png)
