### ISSUE TITLE
UI Glitch unable to log in on Ubuntu 18.04.1 running Wayland

### ISSUE THREAD

**Issue by simernes** [runelite/runelite#4564]
**Describe the bug**
See screenshots

**To Reproduce**
Start the jar with java -jar ./RuneLite.jar

**Expected behavior**
Enjoying a nice day of fishing

**Screenshots**
This is the easiest way to describe the problem. Can't get past this to log in.

First it looks like this while loading:
![screenshot from 2018-07-30 12-20-30](https://user-images.githubusercontent.com/1278451/43392215-3fcd1a1c-93f3-11e8-92b6-950c4f21ed36.png)

Then it looks like this forever:
![screenshot from 2018-07-30 12-16-27](https://user-images.githubusercontent.com/1278451/43392199-3add8e6a-93f3-11e8-8b9d-ba5d3b3a584f.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - RuneLite version: 1.4.9.1
 - Launcher version: 1.6.0
 - Running GNOME on Wayland

**Additional context**
See attached logs
[application.log](https://github.com/runelite/runelite/files/2240729/application.log)
[launcher.log](https://github.com/runelite/runelite/files/2240730/launcher.log)

**Comment by Kamielvf** [comment]
See https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
