### ISSUE TITLE
Another achievement diary typo

### ISSUE THREAD

**Issue by memementor** [runelite/runelite#4567]
Morytania elite...
client says 61 slayer required to kill abyssal demons but they require 85 slayer
![image](https://user-images.githubusercontent.com/41897069/43394431-13622b98-943e-11e8-9735-521813b07726.png)
![image](https://user-images.githubusercontent.com/41897069/43394452-21d7f8b0-943e-11e8-8248-23a45bf644a7.png)

**Comment by Nightfirecat** [comment]
This is already fixed in #4523 and will be updated with this week's release.
