### ISSUE TITLE
Tears of guthix timers positioning

### ISSUE THREAD

**Issue by forsco** [runelite/runelite#4571]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Tears of guthix stream timers are positioned on the canvas down 1-2 Y-axis levels

**To Reproduce**
1. Visit Tears of Guthix with the plugin enabled

**Expected behavior**
Timers should be overlayed on the streams

**Screenshots**

https://lambda.sx/8Tt.png

**Environment (please complete the following information):**
 - OS: Win10
 - RuneLite version: 1.4.10 (Latest Master as of time of issue creation)

**Comment by deathbeam** [comment]
Are you sure you are still on latest master?
