### ISSUE TITLE
Add remember last equipment when banking

### ISSUE THREAD

**Issue by Joepeke3** [runelite/runelite#4576]
Someway somehow to remember your last equipment.
so you can do a farm run inbetween thieving, that if you comeback from the run you can set your last equipment back faster.

**Comment by kristian-welsh** [comment]
Do you mean you want it to highlight items in your bank, that were in your inventory last time you opened your bank?

**Comment by Joepeke3** [comment]
yea something like that yes.
or a button to highlight the current items you have in your inventory and equipment.

**Comment by raiyni** [comment]
Closed with https://github.com/runelite/runelite/pull/5988
