### ISSUE TITLE
No Idle Notification when crafting dhides

### ISSUE THREAD

**Issue by rswindows10** [runelite/runelite#4599]
**Describe the bug**
The idle notifier plugin doesn't work when crafting dragonhide bodies (works for battlestaves though). Also works for any other activity in-game. 

**To Reproduce**
1. Have a needle, some thread, and dragon leather (any color) in inventory
2. Click needle, click dragon leather, and select an option
3. Wait until you've finished crafting the inventory
4. No notification shows up.

**Expected behavior**
Upon finishing crafting the inventory, runelite should throw a "... is now idle!" notification

**Screenshots**
https://gyazo.com/d7f9953d6610acb951a9dccf1d31c134?token=ca942b6cd684472c9da3068d55ad0f01

**Environment**
 - OS: Windows 10
 - RuneLite version: 1.4.9.1
 - Launcher version: 1.5.2

**Comment by MagicfTail** [comment]
The missing animation is ```CRAFTING_LEATHER```, it is added in #3363

**Comment by rswindows10** [comment]
Thanks @MagicfTail , will this be released in the next update?

**Comment by MagicfTail** [comment]
Probably not unless someone makes a pr fixing only this issues, and very soon

**Comment by rswindows10** [comment]
@MagicfTail Is there anything I can do to speed it up? It'd be incredibly helpful to me.

**Comment by Kamielvf** [comment]
Problem with #3363 is it including like 10 changes when all this request would need is 1 simple line added to the plugin.
