### ISSUE TITLE
Create a unified codebase for highlighting Actors

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#4606]
**Is your feature request related to a problem? Please describe.**
Currently, there is code relating to highlighting Actors of various types used throughout numerous plugins (NPCs in the slayer plugin, Players in the player indicators plugin, NPCs in the npc highlight plugin), and each plugin implements this highlighting slightly differently--some allow hull highlighting (NPC, slayer), some allow minimap dot rendering to be disabled (NPC, player indicators), some have options to draw names of players/NPCs above their models (NPC, player indicators), and they may not all have the same highlighting style. (NPC and slayer plugins show a 3d hull, player indicators only highlights players' tiles) As a result, options one might expect to have between these plugins may not be available. (For example, there is no option to disable the minimap circle overlay of slayer task highlighting. Additionally, the respawn timers of the NPC indicators plugin do not exist in the slayer plugin highlights--ref: #3730)

**Describe the solution you'd like**
A more consistent codebase around Actor highlighting to remove some of the inconsistencies between highlighting plugins. This might require a more involved configuration option for highlighting as well, seeing as there are a number of foreseeable options for any particular class of NPCs to highlight. (Highlight style--tile/hull/other? see #3629, minimap circle overlay, respawn timers, etc.)

**Describe alternatives you've considered**
It's possible given the currently limited scope that it would be simpler to make the settings between these three plugins more uniform to address this issue.

**Additional context**
None.

**Comment by Jbluehdorn** [comment]
Any update on this? Its been two years. Someone said it was being worked on?

**Comment by Nightfirecat** [comment]
I don't know of anyone working on this as of now.

**Comment by ReinierAarnink1996** [comment]
> I don't know of anyone working on this as of now.

Hey man great that you spotted a duplicate but more importantly can we actually discuss to get this fixed instead of just closing my thread and leaving it at that...?!

**Comment by Nightfirecat** [comment]
Added in c52667a5cc2e55c7e61e96479c9d59f80772b2ea
