### ISSUE TITLE
Item Prices plugin not working on Linux

### ISSUE THREAD

**Issue by mjglqw** [runelite/runelite#4616]
**Describe the bug**
OSBuddy item prices are simply not showing on grand exchange, even with the plugin turned ON. I have no problems with this plugin on my Windows 10 device.

**To Reproduce**
1. Turn on the plugin
2. Open the Grand Exchange
3. Search an item and view it

**Expected behavior**
Item price from OSBuddy being displayed.

**Environment (please complete the following information):**
 - OS: Linux, Ubuntu 18.04
 - RuneLite version: 1.4.9.1
 - Launcher version: 1.6.0

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client you probably miss certificates
