### ISSUE TITLE
Ornament kit issues

### ISSUE THREAD

**Issue by kyleman526** [runelite/runelite#4636]
I noticed that when putting ornament kits on the anguish, sara godsword , bandos gosword  , torture , and fury are off in price when put in the bank. EX: anguish w/ kit in bank is 21.1m, but the total price of both is like 36m. Note this value is inconsistent **ONLY** when hovering over the item, i believe the price in your overall estimated bank value is correct, just not when hovering over it. Thanks.

**Comment by Nightfirecat** [comment]
Duplicate of  #3909
