### ISSUE TITLE
Zoom bug, goes to default zoom when opening an interface in game

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#4642]
when you open any interface while zommed out or in, it will go back to the default zoom.

the expand out zoom limit must be checked off for it to trigger if youre zoomed out, same for inner zoom limit.

https://gfycat.com/ResponsibleEasyCockatoo

**Comment by AmenoEra** [comment]
I am having the same issue when I try to bank, herb runs etc. Tried restarting client and didn't fixed the issue.

**Comment by forsco** [comment]
Runescape was updated. This will be fixed when the client receives it's weekly update.

**Comment by deathbeam** [comment]
This has been already resolved

**Comment by KerZam** [comment]
Still having this issue
