### ISSUE TITLE
Monster database (Perhaps linked to Osrs Wikia) 

### ISSUE THREAD

**Issue by RuneliteFtw** [runelite/runelite#4643]
Stats like this 
![afbeelding](https://user-images.githubusercontent.com/41970701/43590141-a3350108-9670-11e8-93fe-05820f464c04.png)

This will help a lot knowing the enemy is half of the battle. Having this information will give us a lot of advantage.

**Comment by RuneliteFtw** [comment]
How do I add label to this ?

**Comment by deathbeam** [comment]
Duplicate of #4004
