### ISSUE TITLE
Loot tracker showing noted items with 0 value

### ISSUE THREAD

**Issue by dragonite2524252** [runelite/runelite#4644]
Snapdragons and Adamantite bars from Zulrah show as 0 GP value in the loot tracker.

**Comment by xron89** [comment]
Items showing 0 GP value from Zulrah - 
Noted Runite ore (2)
Noted Adamantite bars (20)

**Comment by liquidsystem** [comment]
I'm pretty sure it's all noted items are not calculating properly, not certain items.

**Comment by xron89** [comment]
Shall we stop listing items then? It appears you're right all noted items don't display their value correctly. Could this be hot fixed? Shame to wait till Thursday

**Comment by LuisRivera162** [comment]
Yeah it won't show noted drop values

**Comment by DiskImage** [comment]
I got the same, Killed vorkath and it shows the 28.1k value of his 2 blue hides/bones but 0 for the 21 noted red hides and 17 noted blacks.

**Comment by jcwhisman** [comment]
Came here to post this. Noted DKS bones are showing as 0gp

**Comment by Kyle-Newton** [comment]
Looks like it never has worked, you can check the value of items on the Zulrah example on the dev update post, and it's not accounting for the ~20K from the 50 noted Mahogany logs. Confirming it appears to be ALL noted items displaying as 0gp.

**Comment by rouge171** [comment]
Noted drops from vorkath do not add to loot value. Same as above users

**Comment by William1Gray** [comment]
I believe @deathbeam has a fix for this he posted in discord earlier. Not sure if there is a PR for it yet though

**Comment by deathbeam** [comment]
Yeah its actually already linked to this issue, #4630

**Comment by William1Gray** [comment]
Oh yeah how did I even miss that. Guess I scrolled too quickly
