### ISSUE TITLE
When entering player house and when any items are on ground, they will be shown in loot tracker

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#4653]
As reported on Discord:
```
when i enter player house and if there is things on the ground , that item will be shown on loot tracker
```

**Comment by JaimySmets** [comment]
Issue can be reproduced by going to a house host in w330 and dropping any item after entering the house.
Leaving and re-entering causes players who spawned together with you to "drop" the item.
Dropping 1 fish and entering twice, gave 3 tracked drops:

![f0yncqi](https://user-images.githubusercontent.com/9333155/43603454-4d091fee-9693-11e8-8935-28b1e823cc4b.png)
