### ISSUE TITLE
Add per-type view to loot tracker

### ISSUE THREAD

**Issue by super11ama** [runelite/runelite#4658]
Option to combine drops of the same monster in the loot tracker.

**Comment by DannysPVM** [comment]
I would also love the option to combine drops from the same monster(s). Preferably implemented via a config option, "Combine similar loot" (or something along those lines), with a tooltip that says, "Combines drops from monsters with the same name". Would be much more visually appealing imo than showing 150-200 rows of loot on a slayer task. Though, I also understand that it could be desirable to view each kill as a new entry for the sake of seeing average loot per kill, etc. That said, I think it would be amazing to be able to toggle which way the loot tracker shows your loot.

**Comment by Adam-** [comment]
Added in #4925
