### ISSUE TITLE
Allow us to Blacklist NPCs from Loot Tracker

### ISSUE THREAD

**Issue by owninjoe** [runelite/runelite#4659]
Like the title says, let us right click on a single loot tracker entry to remove and or blacklist that NPC's drops from showing up in the loot tracker. This would be useful for NPCs that don't drop anything besides bones such as the NPCs in the barrows crypt (Crypt Rat, Skeleton, etc). 

I've added an image for reference:

![loot_tracker](https://user-images.githubusercontent.com/29988643/43614932-014a5e14-967b-11e8-9a95-9e3217b2cbd3.PNG)

**Comment by deathbeam** [comment]
You can just right click reset on each entry for now.

**Comment by deathbeam** [comment]
We now have #4925 what is better solution than blacklisting stuff, so I would say this is no longer necessary
