### ISSUE TITLE
Multi cryptic clues

### ISSUE THREAD

**Issue by nmq12** [runelite/runelite#4660]
Cryptic clue with multiple clues are missing hint.
This particular clue require visiting all three location: Key Master, Piles, and digging in front of Shilo Village furnace

![image](https://user-images.githubusercontent.com/5819477/43617989-cdbd0d94-9693-11e8-9624-593992c94472.png)

**Comment by Nightfirecat** [comment]
Basically a duplicate of #2923; the three-step master-level cryptic clues are not currently handled.

**Comment by deathbeam** [comment]
Duplicate of #2923
