### ISSUE TITLE
"Omit value" option for loot tracker

### ISSUE THREAD

**Issue by Ysterman** [runelite/runelite#4661]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

No related problems to what I would like to suggest.  Loot tracker doesn't have an option for not counting value of a specific loot, i.e. if I kill zulrah and receive 237 scales, 2 calquat seeds and 12 noted dragon bones I may consider leaving the calquat seeds as they are a very low value.  Other times you have possibly received the drop but were unable to collect it due to dying in an instance for example, and thus can't count that loot anymore.  Loot tracker only finds what was dropped and adds them together with no way to remove in certain circumstances for more precise measurement of gain.

**Describe the solution you'd like**

The most user-friendly option I could think of personally would consist of a user being able to simply left click one of the loots displayed from a recent kill.  It would act as a toggle to remove the item's value from the overall value displayed.  It should also have some clear visual feedback, such as turning the panel behind that item specifically red to show that the loot's value has been omitted.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

A possible solution might be to include a minimum value threshold for drops received in the player's name.  This would help players set the value to act as a catch all for loots under a specific amount to just not be added to the tracker.  This wouldn't offer the functionality of removing drops that were unable to be secured as previously described.

**Additional context**

Example of what visual feedback what look like if player selected to omit noted flax from loot:
https://i.imgur.com/Bq8QWaY.png

**Comment by psikoi** [comment]
If I could suggest a visual improvement, maybe the bank filler icon could be displayed on top of the item instead of painting the background red.

**Comment by Unmoon** [comment]
I think there should be a "Hide items below x gp" option.
