### ISSUE TITLE
Show time until run energy full and time until depletion

### ISSUE THREAD

**Issue by ltvill** [runelite/runelite#4666]

**Comment by yourkittenishungry** [comment]
I also had this idea.

**Is your feature request related to a problem? Please describe.**
It would be convenient if you could look at run energy, like prayer bonus, without having to open the equipment dialog, as well as have a feel for how long your run energy will last or take to refill.

**Describe the solution you'd like**
When mousing over run energy orb, show:
-weight (kg)
-time to empty run energy if one was constantly running, I believe this is energy/((min(weight,64)/100)+0.64), times 4 if Stamina effect is active
-time to recharge run energy, (100-energy)*360/(Agility+48), doubled by Rapid Restore and 30% increase from graceful outfit

**Comment by seandewar** [comment]
Hi, I've been working on this request. Here's an image: 

![38787427_514416792351388_2505049540931878912_n](https://user-images.githubusercontent.com/6256228/43909381-1ffe3192-9bf2-11e8-8c27-00b2e8b83ab1.png)

I'll submit a PR soon.
