### ISSUE TITLE
Save loot tracker loot between client sessions

### ISSUE THREAD

**Issue by datashe12** [runelite/runelite#4671]
When runelite is closed the loot tracker is cleared, this means if the loot tracker is used for tracking boss loot over a long time it has to be manually screenshot before closing runelite each time. I don't know if it is viable but it would be great if the tracked loot could be archived automatically as a text file or a screenshot or something rather than manually saved each time.

**Comment by psikoi** [comment]
As stated in the release blog post, this plugin will continue to be developed, and I think this feature is already being planned

**Comment by datashe12** [comment]
thats great! thanks for the reply

**Comment by russel204** [comment]
Came to suggest this. Glad its being worked on!

**Comment by Adam-** [comment]
Added in #7068
