### ISSUE TITLE
BGS and DWH spec counters go away at Vorkath when crumble undeading the crab

### ISSUE THREAD

**Issue by rouge171** [runelite/runelite#4678]
Anytime you are killing vorkath and you target the zombie crab with crumble undead, when you return to killing vorkath it no longer shows the spec amount you hit.

While this is not gamebreaking by any means lol, it is nice to be able to see what you specced during the entire fight

How to reproduce bug:
1.) Go to vorkath and hit a Bandos Godsword special attack on vorkath. 
2.) Wait until the crab spawns and cast crumble undead on the crab killing it.
3.) Return to killing vorkath and the special indicator is no longer available to be seen.

Why this happens:

I believe the Special Attack counter is written to disappear anytime a target is switched so when you go to kill the crab with the spell it counts the crab as a new target and forgets the special you hit on vorkath. 

Solution:

Possibly edit the section of code to remember what has been special attacked in the last 5 minutes or X amount of targets ago and any time that target is returned to display the counter again. 

-I can not code, so if my solution doesn't make sense I apologize, mad respect for you lads who can-

**Comment by deathbeam** [comment]
I would probably just add special case for zombified spawn there

**Comment by Kamielvf** [comment]
Could go along with KQ 2nd phase.

**Comment by Caia-OSRS** [comment]
I've noticed this happening at sire as well on second phase.

**Comment by FearrMe** [comment]
Also happens at corp when hitting the core. Can get real annoying when soloing and core spawns as you spec with bgs and lose all your spec info.

**Comment by Alexsuperfly** [comment]
I believe this was fixed in aa1cd2c7ff79e368db6769d1c09f6b8a11c917d9
