### ISSUE TITLE
Timer For Gilded Altar's Burners

### ISSUE THREAD

**Issue by DewFPS** [runelite/runelite#4679]
**Describe the solution you'd like**
A timer similar to tears of guthix or minows before the burners burn out depending on firemaking level.

**Comment by rbbi** [comment]
Hi @DewFPS I've started work on this

**Comment by 07Arab** [comment]
Very excited for this @rbbi

**Comment by Retoxified** [comment]
@rbbi is this still in active development? if not, I will pick it up tomorrow

**Comment by rbbi** [comment]
@Retoxified no, the time changes slightly every time for the same player

**Comment by 07Arab** [comment]
@rbbi it changes because of your firemaking level. The higher the FM level the more time is added to the burner up to 4 minutes and 20 seconds at level 99 FM

**Comment by rbbi** [comment]
@07Arab, yes, however this time changes slightly between burns - i’ve heard it’s tick based?

**Comment by 07Arab** [comment]
@rbbi I think If I'm correct on my theory, for each additional FM level it's 1.33 seconds of additional time

so 1.33 x 98 (assuming the first level 1 of FM doesn't add any time) = 130.34 + 130 seconds (default burn time) = 260.34 so round to 260 seconds which equates to 260 seconds (4 minutes 20 seconds if at 99 fm)

hope all this made sense lol

**Comment by Retoxified** [comment]
@rbbi do you still have your old research on it? It doesn't need to be 100% accurate so long as it doesn't differ more than a few seconds. I'm still having measurements taken to figure out the scaling

**Comment by rbbi** [comment]
@Retoxified formula was provided by Mod Ash - see #5179, https://twitter.com/JagexAsh/status/1037623830062288897
