### ISSUE TITLE
Include Value of Noted Items to Loot Tracker

### ISSUE THREAD

**Issue by A-RooK** [runelite/runelite#4690]
I was not able to find a similar issue and surprised it has not been suggested yet.

Loot Tracker does not appear to calculate the value of noted items.

![image](https://user-images.githubusercontent.com/42080020/43670779-11fb97b2-975e-11e8-9c57-03c5fae2b107.png)

This is pretty low priority compared to some of the other loot tracker suggestions i have seen.

**Comment by forsco** [comment]
Addressed in #4630

**Comment by Abextm** [comment]
A hotfix has been released for this, restart your client
