### ISSUE TITLE
Loot Tracker doesnt show every drop at Grotesque Guardians

### ISSUE THREAD

**Issue by il3ctro** [runelite/runelite#4699]
Not every drop is recorded in the tracker. Sometimes after a kill nothing will appear.

**Comment by h911reiver** [comment]
Ran into this as well, 5 kills, only three of them recorded

**Comment by MagicfTail** [comment]
Could you try recording a couple kills where it doesn't work so we can see what makes it not work? It's almost certainly a certain spot

**Comment by h911reiver** [comment]
I can do that tomorrow after work

**Comment by h911reiver** [comment]
@MagicfTail I'm running it right now but so far 7/7 on getting the loot to show up.  I noticed there was an update when I loaded it up today, is it possible that it fixed it, or if not, what's the spot you're looking for so I can test that spot.

**Comment by h911reiver** [comment]
@MagicfTail the very next kill produced a positive result https://clips.twitch.tv/PhilanthropicPiercingKangarooUncleNox

**Comment by h911reiver** [comment]
https://www.twitch.tv/videos/293964197

These are my repro attempts.

Kill one I didn't get loot even though I didn't do quit what I wanted.  Kill two was a perfect repro of what I thought the issue was but it tracked the loot.  There are a few more kills some with and without loot.

**Comment by Nightfirecat** [comment]
I suspect the same behavior would be present when killing regular gargoyles too then.

**Comment by h911reiver** [comment]
Doesn't happen on regular gargoyles, and I don't have a task to test it on the bosses right now so I'm not much help.

**Comment by JaimySmets** [comment]
Running on an up-to-date master with #4868 merged, not all loot is being tracked. Seems not fixed.

![2018-08-12 16_52_32-runelite](https://user-images.githubusercontent.com/9333155/44003287-8abc54ea-9e50-11e8-9fd3-dc28b7d82cae.png)

**Comment by MagicfTail** [comment]
Could you check and make sure it's the correct npc id, 7888, when he dies?

**Comment by JaimySmets** [comment]
He starts at 7888, during his death animation he turns into 7889. Tried making a gif with his ID. Loot also fails to be added here.

![naamloos-1](https://user-images.githubusercontent.com/9333155/44003693-3218ade6-9e57-11e8-84ef-a2518e29bc44.gif)
