### ISSUE TITLE
Highlight Troll Thistle by default

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4702]
It's rather difficult to find the Troll Thistle during the Eadgar's Ruse quest. It would be nice if it could be highlighted.

**Comment by deathbeam** [comment]
Cant you add it to ground items by yourself to spot it. Also by default, it should have just white text above, so that is good enough.

**Comment by Gamer1120** [comment]
That would be better I think.

Op za 4 aug. 2018 16:43 schreef Tomas Slusny <notifications@github.com>:

**Comment by Gamer1120** [comment]
That would be better, yeah.

**Comment by deathbeam** [comment]
There you go then
