### ISSUE TITLE
Add option to show quantity on ground items as x 15

### ISSUE THREAD

**Issue by GoEasyImBad** [runelite/runelite#4715]
Adding an option to either show x amount of items on ground vs the ( x ) option. 
would probably be an easy add. the Parantheses are clunky in my opinion.

**Comment by GoEasyImBad** [comment]
yes you are right. instead of (100) make it x 100.. maybe Blood Rune (100)
can be swapped to Blood Rune x 100

**Comment by adm1n1stra1tor** [comment]
@GoEasyImBad 
@deathbeam 
Further suggestion in this thread.

Make the quantity color changeable. So you get further contrast, based on what color you like,

**Comment by adm1n1stra1tor** [comment]
Additional thoughts;
Making the quantity text, automatically a bit different from the original color you chose for that value-bracket.

Example: (Blue)Coins (Ligther Blue)x 100

**Comment by deathbeam** [comment]
As we now have collapsing, this will be confusing, closing
