### ISSUE TITLE
Add notifications to random events and (selected) drops

### ISSUE THREAD

**Issue by AlgebraicGeometry** [runelite/runelite#4720]
I'm always frustrated when afking a skill/combats and I miss a useful random event like the genie, surprise exam or the maze, since they provide a small boost to my account, and since I am also collecting random event pieces, I don't want to miss the gravedigger, mime, etc either. Also, when I am afking something like fossil crabs, I also want to collect the unidentified fossils, but since I am afking while doing it, it is likely I'll miss these drops which are quite rare.

I want a (toggleable) notification for all random events, with the option to select only the ones you want. Also, a toggle to select the drops for which you want a notification.

An alternative solution is to add a toggle for either all random events, or just genie/surprise exam since they would be the most popular.

**Comment by deathbeam** [comment]
We already have issues opened for both of these requests. Also, you can already get notification for unidentified fossils, just setup in game chat notification and then use chat notifier to notify you about it.
