### ISSUE TITLE
Idle Notification Alert priority

### ISSUE THREAD

**Issue by newruneliter** [runelite/runelite#4723]
This problem is regarding the idle notifier. I only receive alerts when runelite is minimized or running in the background. The client will not send an idle alert when the client is in focus.

I would like to configure runelite so that it sends alerts all the time, even when open and running as the main application on the screen.

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/RuneLite#send-notifications-when-focused

**Comment by newruneliter** [comment]
I do not know how to access this menu, can either of you please help. The link you sent is a wiki page with an image of a configuration menu I would love to be able to use. The only input I have over the notifier is: idle animation notifications, combat idle notifications, idle notification delay, hitpoints notification, prayer notification threshold.
