### ISSUE TITLE
Ability to enable/disable CTRL sprinting

### ISSUE THREAD

**Issue by storyy1** [runelite/runelite#4731]
**Is your feature request related to a problem? Please describe.**
When you hold CTRL and left click, it automatically enables sprint for the click and makes your character sprint to the location.

**Describe the solution you'd like**
I wanted to suggest the ability to toggle this option on and off

**Additional context**
The CTRL button is a button that I use to toggle things on other programs and it makes me use up a lot of sprint energy by habit of already using CTRL. OSBuddy used this feature and it was one of the key features that really made me want to swap off the client.

**Comment by Hydrox6** [comment]
This was added by Jagex shortly after adding Ctrl Click while running to walk
