### ISSUE TITLE
See names of people you have added on the minimap even if they have their private off.

### ISSUE THREAD

**Issue by DonHaci** [runelite/runelite#4734]
It's been said that the only reason this wont get implemented is because of "we respect players their privacy" but anyone who would really want to abuse it can already use konduit or osbuddy which both have it free, RL is just holding itself back with it since it's crucial in certain clans to have this and you cant have everyone added.

The only reason some pking clans still use konduit(or osb) over Runelite is this, especially when you dont want anyone to know your world you have your private turned off but cant see your friends names in the mini map anymore.

Id understand if that feature was a paid-only osbuddy benefit meaning not everyone has it but if anyone really does wish ill with it they could use any of the other clients and just hop between them, all this is doing is holding back the full switch for some people over to Runelite

If not is there a code to add this yourself?

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

We can make clan members cache probably and so player indicators will work straight away after hop for CC. Even though OSB and Konduit has it, it can be used to harrass players and the reasoning that it already exists elsewhere do not changes the fact and the thing that we simply do not want to promote such behaviour.

**Comment by DonHaci** [comment]
But that's the point, if someone REALLY wants to harrass someone they could just use osbuddy or Konduit straight away. Id completely understand if the feature was never made or wasnt available by just hopping to a different client within 5 seconds
