### ISSUE TITLE
[Suggestion] Create Google calendar events for when farming plots are done

### ISSUE THREAD

**Issue by FabulousAid** [runelite/runelite#4735]
**Is your feature request related to a problem? Please describe.**
No reminder outside of Runelite for when farming plots are ready to harvest. 

**Describe the solution you'd like**
Create Google calendar events for when farming plots are done. 

**Additional context**
Currently I set Google calendar events to remind me when I my farming plots are done, seeing as everyone already logs in with their Google account why not have the option to create Google calendar events automatically through Runelite?

https://developers.google.com/calendar/create-events

**Comment by Abextm** [comment]
I don't think we ever want to add events to external services for this. Notifications in general are in #2212
