### ISSUE TITLE
Highscores page for all Theatre of blood party sizes

### ISSUE THREAD

**Issue by Aloeeeeee** [runelite/runelite#4744]
Currently theres only the official oldschoolrs highscores page for fastest TOB times which is only for 5 man teams since 4-man/trio/duo are slower.
Would be cool if you could see seperate highscores for each team size since trios and 4 mans are more efficient to do than a 5 man.

**Comment by WILECL** [comment]
Is this information available through the osrs API?

**Comment by deathbeam** [comment]
No. This is impossible to do:
1. Because the data would need to be tracked in runelite and so if someone would beat it on other client runelite users will not know and the data will be invalid
2. The data can be easily faked, and in this case it is impossible to prevent that.

**Comment by WILECL** [comment]
Exactly, thank you for the informations @deathbeam
