### ISSUE TITLE
Loot tracker adds multiple entries if you open ToB reward chest more than once

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#4754]
Steps to reproduce: finish a raid and open the chest, close the interface and open again. Will result in multiple loot entries.

**Comment by Kyle-Newton** [comment]
Same with Xeric, I suppose they would assume there should be no reason that we open the chest multiple times. :)

**Comment by Kamielvf** [comment]
As far as I know you cannot open the Barrows chest twice in a row unlike the ToB and Xeric ones. I will do a run real quick to check if this is the case or not.

**Comment by Brodan** [comment]
Okay, that'd be good to know! I've never done barrows so it's easier if someone else checks. T hank you!

**Comment by Kamielvf** [comment]
Yeah the game just tells you `The chest is empty.` and does not show the rewards a second time.

**Comment by psikoi** [comment]
Couldn't we just do a kc check when opening the chest? compare to the last stored kc, if its the same, ignore.

**Comment by deathbeam** [comment]
That would require us loading other plugin's configuration, what seems incorrect and we do not do that anywhere

**Comment by psikoi** [comment]
Just literally have an int where when the kc message pops up, assign that int to the kc, if that value is unassigned when the first chest is opened, then that's the first time it's opening anyways

**Comment by deathbeam** [comment]
Oh the in-game kc? People can have the kc messages disabled so that will not work.

**Comment by Kyle-Newton** [comment]
Could you add some sort of few minute cool down for CoX and ToB entries?

**Comment by Kyle-Newton** [comment]
That's true.. Here's a quick brainstorm on some solutions mentioned 

Based on KC - Might not be enabled
Based on raid timer - Might not be enabled
Based on Duplicates - Wont work in the case of a B2B
Based on an arbitrary time after opening chest - Could potentially sit around until timer is over
Based on current instance - May or may not have a good system in place to check this

Anyone else have any ideas? Based on instance seems like the more foolproof, but does anything exist that could check this? Would it work if you logged out and back in during an instance?

**Comment by Nightfirecat** [comment]
In discord, it was suggested that this be a boolean flag that is cleared upon region change.

**Comment by Brodan** [comment]
> In discord, it was suggested that this be a boolean flag that is cleared upon region change.

cool, i can try to implement this asap

**Comment by Kamielvf** [comment]
I was not in the discord when this discussion happened, but I think all that is needed is indeed a flag that will be set when the raid is started/entered (there are already methods for these in the raids plugin you could use logic from there) and then flipped when the chest has been opened.

**Comment by Mansalu** [comment]
I'm experiencing this as well, with loot from Chambers of Xeric. Seems like an issue anytime the Loot Tracker is recording loot coming from some type of chest system.
