### ISSUE TITLE
Pile Finder

### ISSUE THREAD

**Issue by mrpker9** [runelite/runelite#4757]
Is it possible to make a pile finder?

It shows you the name of the person that most of your friends/clan chat are attacking

**Comment by LShirohana** [comment]
It is possible, yes. Create a table of players that are in your clan chat + friends list and are in renderable radius, then you can just check if X is interacting with Y. X being your friend/member. After checking all of them, do a % check to see if, as example, 50% are attacking 1337CowKiller. Set Target to the one with the highest percentage, and proceed to do a few options on them such as:

Highlight them
Menu swap them to the top
Mark their name in a specific color(?)

Etc..

Possible, but no one is currently working on such plugin.

**Comment by mrpker9** [comment]
Yep, thats what you said it will be great to actually have someone to work on it ! :)
