### ISSUE TITLE
Option to launch Testing/Unstable version

### ISSUE THREAD

**Issue by alex-vincent** [runelite/runelite#476]
Lots of people i'm sure would enjoy the latest features as well as testing and notifying of bugs seen.

**Comment by zeruth** [comment]
Honestly if that's something a user wants, they should be building it from source. Seems like a lot of work to spoon feed something that's already not that complicated.

**Comment by Adam-** [comment]
You can pass ```---version=1.2.15-SNAPSHOT``` to the launcher (or any other version) for this.
