### ISSUE TITLE
add Kingdom of miscellania claim rewards to the daily task indicator feature.

### ISSUE THREAD

**Issue by offZills** [runelite/runelite#4760]
i know that it sounds wrong to do this because the time of claiming rewards differs from player to another depends on what time they finished the quests, BUT if you can give the user the option to manually set the time they want to get notified at i think it is doable,also it doesn't have to be an in game chat notification likes zaff staves or herb boxes currently in client, it can be simply a client-sided notification.

**Comment by Kyle-Newton** [comment]
Don't we already have a notifier for Kingdom that will start to appear once under X%? I know it wasn't working very consistently in the past and I stopped using it, but if it's working correctly you could just set it to show up at 99% for you. 

I'm personally not a fan of daily reminders as I collect every 2-3 weeks only, and have never considered it a daily task.

**Comment by LlemonDuck** [comment]
Completed in 2d5d490b50d39bc53ba5ca6da257d3e1f2f9ff03, accessible through "Kingdom of Miscellania" plugin rather than Daily Task Indicators
