### ISSUE TITLE
NPC Indicator improvements: Ability to toggle 'Draw ALL NPC names above heads, excluding[...]'; and more...

### ISSUE THREAD

**Issue by la-korasi** [runelite/runelite#4765]
**Is your feature request related to a problem? Please describe.**
No particular problem. I would just love to be able to have all NPC names displayed above heads. This would be fantastic for questing (as opposed to tagging and adding each NPC one at a time).

**Describe the solution you'd like**
A i/o toggle feature to display ALL npc names above heads (also logically for hull/tile options. These would ideally be totally independent of each other, meaning you would have a i/o toggle for each "draw NPC names above heads"; "highlight hull"; and "highlight tile". The latter two I feel aren't necessary in my case, but they are logical, if such a feature is to be added for names above heads.
In the case of this feature being added, **I think it is very important to add a text box allowing for exclusions, similar to the "Ground items" exclusion text box"**, maybe certain players don't want every single goblin, banker, and rat to be drawn above their heads!

**Describe alternatives you've considered**
n/a

**Additional context**
A similar feature may be worth considering for drawing ALL other player names above heads, rather than only friends/clan mates/team mates... It might be quite cluttered in busy areas, but I'm certain many players would find this option very useful, and would likely be actively toggling the option on and off in circumstances in which such a feature could be useful. I won't list all context in which this could be used, I'm sure you can work your imaginations and realise how popular this toggle would become.

Thanks in advance to anyone who takes notice of this, and a very deep thank you from the bottom of my heart if someone with the right skill set programs such a feature into the already existing NPC indicator plugin.

Sincerest appreciation for all members on this GitHub. 
A new member on the Runelite GitHub,
Korasi

**Comment by deathbeam** [comment]
This is already a feature, just put `*` to highlighted list in NPC indicators.

**Comment by la-korasi** [comment]
Hi,

Thanks for replying! I’m very glad this feature exists, however there doesn’t appear to be a way to exclude certain NPCs. Before making another post I figured I would run this by you as I may be missing how to do this. If effectively this feature doesn’t exist, I’ll submit another feature request.

Thanks again! :)
Korasi

**Comment by la-korasi** [comment]
Hi again,

To follow up my last email, there appears to be a bug (not so much a bug, but an unwanted side-effect of putting an asterisk in the NPCs to highlight text box). In motherlode mine, once pay-dirt has been added to the hoppe, and goes into the water, (what I think is) a string of code is drawn above the pay-dirt while it goes through the water, and vanishes upon arriving in the sack at the end. I’m guessing this happens for various things across the game, if I encounter any other I’ll take note of them and post them to the github.

Thanks.
Korasi
