### ISSUE TITLE
Have boosted level turn to red when it reaches your set notification level in settings

### ISSUE THREAD

**Issue by redsfan7035** [runelite/runelite#4767]
When training combat, it would be great if your boosts didn't just stay green until they reset to normal. The notification is a bit more clunky as you'd have to enable all notifications while client is focused for it to give you the desired result. This way, once your eyes notice the change in color, boom, re-pot or re-spec. 

Thank you!

**Comment by WILECL** [comment]
Pretty sure I have this on my home desktop build, turn yellow between config threshold and current level. Will check after work

**Comment by redsfan7035** [comment]
If you can check, that'd be awesome. Is it something that is easy for me to
do myself? So if I boost to 118 and have config threshold to 114, at levels
15 to 117 it'll be yellow and then 114 and below it'll be red?

**Comment by WILECL** [comment]
The changes are very easy as long as you have a development environment;
The changes are now in a branch in my fork on my profile. 

It looks like:
![runelite](https://user-images.githubusercontent.com/22059229/43871941-0ca1665a-9b4d-11e8-898a-ed2c1d38e0ed.png)

@redsfan7035

**Comment by redsfan7035** [comment]
Darn, definitely don’t have a development environment. Can it just be put in the regular build?

**Comment by redsfan7035** [comment]
Hey @WILECL I have no idea how to modify my settings or what a branch is. Is there anyway to just get it pushed to a live Runelite build? I'm fine with yellow as I see the use of red. I'd really just like it to stay green until it hits my config threshold. So from 118 to 115 it is green and then when it hits my config threshold it is yellow from that point on. 

If you don't mind walking me through doing it on my own, I'd appreciate. Thanks for your kindness!
