### ISSUE TITLE
Inferno timers

### ISSUE THREAD

**Issue by GoEasyImBad** [runelite/runelite#4775]
Adding a timer to wave 69 to reflect when the mage and range will spawn and possibly an HP alert for Zuk to let you know that Jad will be spawning/ healers

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by GoEasyImBad** [comment]
I didn’t see anything against the inferno maybe I overlooked?

**Comment by deathbeam** [comment]
Oh, I guess it should be added then

**Comment by GoEasyImBad** [comment]
To the rejected list I assume?
