### ISSUE TITLE
"Contain in screen" ignoring taskbar

### ISSUE THREAD

**Issue by laagone** [runelite/runelite#4776]
The "contain in screen" feature is nice, but my problem with it is that it ignores the taskbar and goes under it. It's a bit annoying because I like to play with the client on the bottom-right, and if I accidentally reposition the client, I have to carefully place it along the taskbar edge (so as not to waste screen space). It kinda goes against the nature of what the feature is.

I'm not sure if this is intentional or a bug, but I assume it could be fixed as Konduit doesn't have the same problem. I don't see any benefit to having a part of the client under the taskbar, but on the off-chance someone does, they could just disable it.

**Comment by deathbeam** [comment]
Not possible to fix in custom window chrome and make it work cross-platform, so I guess just disable custom window chrome in "RuneLite" settings.
