### ISSUE TITLE
Client window doesn't remember size/position anymore.

### ISSUE THREAD

**Issue by offZills** [runelite/runelite#4778]
Starting today 8/8/2018, the client for some reason resets settings on its own every time i launch it, it doesn't remember what size and position i set for it,was working just fine yesterday, now i have to resize it all over again and adjust my settings every time i open it, tried to reinstall but nothing changed.

**Comment by KingLehon** [comment]
this does not work for me as well for client position
Ex.
[Me opening the client after turning off and on the "remember client position," feature.](https://youtu.be/mPScGYelmis)
