### ISSUE TITLE
Ability to toggle "Highlight untradeable drops"

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#4779]
https://i.imgur.com/KQ0GLsh.png

As you can see, doing AFK slayer for example, players may not notice they received untradeable drop(s)

There is no option to highlight untradeable drops, my option for "Do not hide untradeables" does not make untradeables highlighted.

**Comment by adm1n1stra1tor** [comment]
This would be a nice change actually. But currently you can add the wanted items to highlight manually.
Highlighting everything untradeable would result in a lot of crap, that you would have to hide manually.
So either way, ur gonna have to manually enter items.

**Comment by Durtes** [comment]
Maybe you didn't knew about it, but you can set 'Untradeable loot notifications' on, which then would show as a coloured text in your chatbox.
Tho can't help you with the notifications of ground items.

https://imgur.com/gallery/tzglDG2

**Comment by Popedigoz** [comment]
Durtes, I do know about it, and I do use it - but still it's not very helpfull, like at all...

**Comment by deathbeam** [comment]
You can just add untradeables to highlighted list, there is only like 5 untradeables that are interesting (after using wildcards). Otherwise you can simply use chat notifications as others said.
