### ISSUE TITLE
[Menu Entry Swapper] Add swappable entries on equipped items.

### ISSUE THREAD

**Issue by GrimWrath** [runelite/runelite#4782]
Request to expand Menu Entry Swapper to equipment interface. Would allow one to shift click or left click an equipped item to use one of the alternate options on that equipped item. (Teleport destinations, trim options, bloom, etc)

**Comment by oplosthee** [comment]
This is on the list of [rejected features](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features), as it could result in an increase of xp/h or make certain things in game much easier.

**Comment by Battulga93** [comment]
please we need ring of dueling swape beetwheen duel arena and castle wars this would help for runecrafting so much and make it easier. we need autoswapper between duel arena and castle wars! i don't even get 50k xp per hour when i following guide switch says 70k plus xp per hour. even if i use f keys it still not get up to 70k xp not even close. so swaping in equipment interface is all people need for runecrafting!
