### ISSUE TITLE
Figure out the exact world hop limits and add them to the world hopper and world switcher

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4786]
Both the world hopper and the world switcher haven't been merged yet, but it would be nice if they could optionally not hop worlds if the login limit is exceeded. It is currently unknown (according to a quick Google search) what these login limits are.

**Comment by Abextm** [comment]
From what I understand its not a static delay. I would assume its probably some sort of sliding window, so predicting it accurately may be difficult/impossible.

**Comment by adm1n1stra1tor** [comment]
@Abextm 

A solution could be to have sort of a "status bar" of danger, based of a bit of sample collection.
"red: Your at high risk of hitting the log in limit"
"Yellow: Your at medium risk of hitting the log in limit".

I'm guessing collecting a semi-small samplebase would atleast give a bunch of probabilities you can base these warnings off

**Comment by deathbeam** [comment]
Looks like wontfix as it is not possible to determine this
