### ISSUE TITLE
Brewing Plugin For Kandarin and Phasmatys Brewing Vats

### ISSUE THREAD

**Issue by drmlkjr** [runelite/runelite#4788]
**Is your feature request related to a problem? Please describe.**
No problems here, an idea I had while getting back into brewing while on Rlite.

**Describe the solution you'd like**
Basically, I was wondering if it would be possible to do a farming plugin , but except for farming it tracks brewing.  To be honest, I have no idea how the farming plugin works, and I'm even more unsure if brewing works in a trackable way . I know Port Phasmatys is a random time, while kandarin is more stable.

**Describe alternatives you've considered**
I've been considering trying to do this myself, but I don't know anything about the language Lite is in.  I was going to try and learn the terminology, copy the farming plugin, and see if I can get any variables to read as 'The Vat', but again I don't actually know if this is possible.

**Additional context**
I don't think this is a really high priority, but I am curious if it is possible.

**Comment by trimbe** [comment]
Duplicate #2648
