### ISSUE TITLE
Pest Control Add-On disables Target Info, XP Globes

### ISSUE THREAD

**Issue by LuitenantDan** [runelite/runelite#4790]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
If you turn on the Pest Control add-on, the XP globes and Target information overlays are disabled. Turning off the add-on re-enables the XP globes and Target Info.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.10.2
 - Launcher version: 1.6.0

**Comment by Kamielvf** [comment]
Fixed with tomorrows release
