### ISSUE TITLE
Clue Scroll Stash Checker!

### ISSUE THREAD

**Issue by SirDylan** [runelite/runelite#4814]
**Is your feature request related to a problem? Please describe.**
It's hard to remember if you have filled a stash at a clue scroll location.

**Describe the solution you'd like**
I would be nice if it would include within the GUI if you have an existing stash at the location and if it contains the necessary items.  It could also include a reminder to refill your stash after you finish the clue step.

**Comment by Abextm** [comment]
Duplicate #1662
