### ISSUE TITLE
Suggestion; Clan Chat history

### ISSUE THREAD

**Issue by adm1n1stra1tor** [runelite/runelite#4833]
Suggestion; Clan Chat history
Sucks to constantly have to google forgotten ones
A notepad would fix this i know.
But i'm thinking about interface like, when u left one
There could be a list, in the emptyness - where u normally see people
Saves the last 5 - history.
Maybe able to make favorites that sticks there?
It wouldnt provide a edge over other players skill-wise
And from my understanding, not to hard to implement.

**Comment by deathbeam** [comment]
What is this actually? I dont understand the request

**Comment by adm1n1stra1tor** [comment]
@deathbeam 
![eb86b086b138500fd27c40f81835611c](https://user-images.githubusercontent.com/42292767/43990602-c53666cc-9d5d-11e8-8eda-9405c4cb9175.png)

In this little window. Above "Join Chat" 

A history of previously joined clan chats would come handy. 
Sort of like the Fairy ring "history".

The window is empty when your not in a CC. 
And this space could be utilized to have a log of previously joined clan-chats, or favorites. 

Regards, i'm sorry for being unclear.

**Comment by DannysPVM** [comment]
Very hard to tell what is being requested here, but my interpretation leans towards asking for a list of recently visited clan chats. So like, when you click 'join chat' or whatever it is in the cc tab, it shows like the last 5 clan chat names you entered so that you can just click on one of them, and it join that cc for you. Of course, I may not understand what is being asked for here, That's just my understanding of it.

**Comment by adm1n1stra1tor** [comment]
I*m thinking just as plain text/overlay above "Join Chat".
And not functional buttoms. Just to keep track if your in multiple clan chats and change quit often to new ones.

**Comment by DannysPVM** [comment]
Oh, gotcha. I submitted that like right when you explained further. Ignore me.

**Comment by deathbeam** [comment]
I see, that is actually pretty cool idea. Yeah functional buttons are out of question because that would be faking user input, most likely.

**Comment by DannysPVM** [comment]
I was gonna say that the 'hyperlink like' buttons that I thought he was talking about would likely be out of the question because of faking user input, but yeah, I completely agree. The other way of just showing plain text list of recently visited cc's is pretty cool though.

**Comment by adm1n1stra1tor** [comment]
Thanks for feedback! I really hope it gets implemented, personally i would have alot of use of it. 
And nothing buggers me more than unused areas/spaces. :D
