### ISSUE TITLE
Suggestion: Favourite / custom farming timers tab

### ISSUE THREAD

**Issue by hubalekt** [runelite/runelite#4834]
**Is your feature request related to a problem? Please describe.**
Tracking different farming produce across all tabs is frustrating and slow.

**Describe the solution you'd like**
A simple tab allowing the user to add custom favourite timers to it to keep track of them.

Example: Allow the user to select multiple different trackers such as seaweeed, cactus, calquat and poison ivy and add them to a separate custom tab to keep them in one place for faster reference.

**Describe alternatives you've considered**
There is no alternative other than manually browsing each farming timer category.

**Additional context**
Raised based on MBBrabus' suggestion

**Comment by adm1n1stra1tor** [comment]
Lunar Spellbook has a spell called; Geomancy. Which is quit handy. 

Suggestion to Jagex: Add Geomancy tabs to the game. 
(I know jagex aint reading here :P)

**Comment by deathbeam** [comment]
Duplicate of #3056
