### ISSUE TITLE
Suggestion. Freeze/TB/Venge/SOTD timer on top of players tile

### ISSUE THREAD

**Issue by Valmiel** [runelite/runelite#4836]
Just a timer on a players tile to show any timers they have on them. Another client called exilent already has this feature, it shows TB Timer/Freeze timer/Venge timer/SOTD timer over the top of the player.

Clip of what it looks like:

https://clips.twitch.tv/NurturingBenevolentStrawberryFreakinStinkin

It would be very useful for pkers, a lot of us prefer the Exilent clients way of displaying the timers and we use it over runelite, we'd all use runelite instead though if it had this feature

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
