### ISSUE TITLE
High Alch Improvement, Ground items: 

### ISSUE THREAD

**Issue by adm1n1stra1tor** [runelite/runelite#4838]
Make GE prices and High Alch prices two seperate units.

So that you can for example; Enable 300 HA + to show, without showing GE value 300+

Something like: 
High Alchemy Value:  >500
Include Nature Rune in price) ( X / I ) 
High Alchemy Display Color: 

Would be cool if it could be made so that, it still shows to the right of the G.E value. 
And not show up at all, if it's under the limit you set in settings.

And the opposite; 
If the G.E value isn't high enough, but the High Alchemy is. Only display High Alchemy value/excess from Nature rune.

Reasoning:
If you feel it's worth high-alching items that gives you a net profit, or simply 30gp+ for the Magic XP.
You are currently forced to set the highlight item value; To 100, basically.

Since certain items are worth  100 gp GE, but are  240 HA valued.

**Comment by deathbeam** [comment]
This was done intentionally and so would be reverting previous change and reopening multiple issues related to this.
