### ISSUE TITLE
Add "Fairy Ring BIQ" to Weird Old Man Kalphite Lair Entrance clue

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4842]
![image](https://user-images.githubusercontent.com/9074448/43991012-457f539c-9d64-11e8-9cfc-65e6b77dc1ed.png)
It would be nice if this could include fairy ring BIQ, so I don't have to look it up every time.

**Comment by adm1n1stra1tor** [comment]
Awesome!

**Comment by Gamer1120** [comment]
That was quick

**Comment by Gamer1120** [comment]
Closed by merging #4844
