### ISSUE TITLE
Special Attack Notifier

### ISSUE THREAD

**Issue by adm1n1stra1tor** [runelite/runelite#4843]
A notifier for when you gain 100% special attack.

This would be very useful for example; Fishing, mining and Woodcutting
With the usage of Dragon Axe, Pickaxe, Harpoon's special attack giving 3+ stats boost. 

If you were to give the function these two parameters;
Notify at level: 1-100%
Notify at level: 1-100%
(Multiple warnings possible)

You could use it in some pvp instances, for example. 25% for a DDS specc.
And 75% for a dds specc + something else. 

Being able to chose when to get the notify, also helps the skilling aspect. 
If you put it on 90/95% - You are given a headsup in time, so you donät have to stress.

Regards

**Comment by deathbeam** [comment]
Always search for existing issues first before opening new one, this is duplicate

**Comment by graingert** [comment]
@adm1n1stra1tor here's the PR: https://github.com/runelite/runelite/pull/6877
