### ISSUE TITLE
If client fails to start, show the error in a popup in addition to the logs

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4847]
I've seen multiple issues get opened about clients not starting up. Usually there is more information required to find the cause (logs etc.), which is usually not given by the OP. MSPaint mock-up:
![image](https://user-images.githubusercontent.com/9074448/43991426-e00a93f6-9d6c-11e8-8bb9-65ac80c3e090.png)

**Comment by dekvall** [comment]
Launcher 2.0 has this.

**Comment by Alexsuperfly** [comment]
I believe #9629 added this
