### ISSUE TITLE
Add an X to the end of the plugin search bar to clear the field

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4850]
Mockup: 
![image](https://user-images.githubusercontent.com/9074448/43991845-5401b19c-9d75-11e8-9942-d78ad1ff21b4.png)
If you're just using your mouse to play, it saves you from having to use the keyboard to erase the field.

**Comment by Justsofun** [comment]
How do you search anything without using the keyboard?

**Comment by Gamer1120** [comment]
There are cases in which you already have something typed and just want to erase it to show all options again.

**Comment by Nightfirecat** [comment]
Duplicate of #3222
