### ISSUE TITLE
Menu Entry Swapper for Dismiss on random events

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4851]
If you want to dismiss any random event, having this the default option would be great.

**Comment by doxxide** [comment]
such a petty thing. random events happen so infrequently and you're asking for a default option to dismiss which is 1 right click away. this would essentially have you 1 second over the course of maybe 1 hour

**Comment by Gamer1120** [comment]
Yup, nonetheless it's a very low-priority nice-to-have.

**Comment by deathbeam** [comment]
I dont think this should be implemented. You can just ignore random events and the ones you want to click on you dont want to dismiss with left-click.

**Comment by Gamer1120** [comment]
Ok
