### ISSUE TITLE
Client sending multiple notifications to windows 10

### ISSUE THREAD

**Issue by Chronolis** [runelite/runelite#4852]
**Describe the bug**
Whenever any notification goes off, it sends multiple windows notifications. I tried changing the notification sound so something more pleasant, but now I am receiving both the new notification sound, as well as the original windows notification sound

**To Reproduce**
1. Go to Windows Sounds options
2. Go to the notification section and change the notification sound to something new
3. Trigger any notification

**Expected behavior**
Plays the new and expected notification sound

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.11
 - Launcher version: 1.6.0

**Additional context**
I believe that this is likely an issue with Windows, but I cant seem to find the source anywhere online. Was seeing if anyone has had this issue here.

**Comment by Kamielvf** [comment]
One sound is from your OS, one is from RuneLite (sound notification option under "RuneLite" in settings).
You probably want to disable the latter.

**Comment by Chronolis** [comment]
That doesn't quite make sense. How would windows know to send a notification if i disable the runelite notification in settings?

**Comment by deathbeam** [comment]
We send extra sound notification by default together with windows notification. Just disable the sound notification in RuneLite settings

**Comment by Chronolis** [comment]
Should i disable every notification or is there a specific setting that contains this extra notification?

**Comment by deathbeam** [comment]
Yeah, search for "RuneLite" in the sidebar and disable "Enable sound on notifications"

**Comment by Chronolis** [comment]
That did the trick! Thank you very much :)
