### ISSUE TITLE
Brimhaven agility arena timer resets when falling off obstacles

### ISSUE THREAD

**Issue by nelsonong** [runelite/runelite#4859]
Brimhaven agility arena timer resets when falling off obstacles.

**Expected behavior**
Timer should continue to count down.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.4.11
 - Launcher version: 1.6.0

**Comment by Adam-** [comment]
This was reported before in #4023 and fixed before in #4029. Maybe someone else should look at this.

**Comment by Justsofun** [comment]
The fix in #4029 doesn't actually fix the problem at all

**Comment by Adam-** [comment]
Previous fix was indeed not fixing the actual issue. I gone and checked it out. Fixed in d1d6d26b60396244e6420b22cb8bd467bbdb0564.
