### ISSUE TITLE
Highlight Broken fence at Varrock sawmill as Agility Obstacle?

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4860]
I'm not sure if it is really an agility obstacle, and whether we want to highlight it, but this is the fence I'm talking about:
![image](https://user-images.githubusercontent.com/9074448/43996278-b6954cf2-9dbf-11e8-8e54-fe24c1cb3731.png)

**Comment by Nightfirecat** [comment]
Thus far, we've highlighted other obstacles that aren't necessarily tied to agility shortcuts, so this seems like a fine addition.
