### ISSUE TITLE
getEquipmentId() returns -1 for HEAD KitType, even when target player has something equiped

### ISSUE THREAD

**Issue by osrsbox** [runelite/runelite#4866]
**Bug description**
I have noticed that the `getEquipmentId()` function is returning -1 (no itemID or nothing equipped) for the head slot of a target player when the target player is actually wearing something in the head slot.

**To Reproduce**
This can be reproduced in a plugin. The following code should reproduce the same bug, where `p` is a `Player` that has already been targeted. In my case, the player is targeted using an additional menu entry when right-clicking a player in-game.

```
PlayerComposition playerComposition = p.getPlayerComposition();
for (KitType kitType : KitType.values())
{
     int itemId = playerComposition.getEquipmentId(kitType);
     log.debug("itemId: {}", itemId);
}
```

What is interesting, is that I am getting different results using the following two functions:

- `getEquipmentIds()`
- `getEquipmentId()`

The output I am getting from each are:

- `getEquipmentIds()`: `[1091, 1533, 0, 0, 1089, 0, 0, 1523, 386, 3454, 9517, 266]` 
- `getEquipmentId()`: `[1021, -1, -1, 577, -1, 1011, -1, 2942, 9005, -1]`

Please note, that the `getEquipmentIds()` output above is not taking into account minus 512 from any value greater than 512 (as documented in the API). When you do perform that, you will get the same ID values. However, the returned item ID value 1091 (aka actual item ID number 579) - which is the head slot that is missing... in this case a blue wizard hat (579).

**Expected behavior**
I expected the head slot to be returned when using `getEquipmentId()`.

**Screenshots**
Not applicable

**Environment (please complete the following information):**
Windows 10, IntelliJ with JDK version 8u181, git version object hash: `6ef32bf91`

**Additional context**
Not applicable

Happy to help with any additional questions (and hope I am not missing something basic which is causing this problem!). Thanks!

**Comment by HSJ-OSRS** [comment]
the KitType index for the head slot is incorrect currently its 8 when it should be 0
