### ISSUE TITLE
Discord chat overlay enabling?

### ISSUE THREAD

**Issue by ru-ni** [runelite/runelite#4873]
It doesn't work for me by default, although discord will detect the client and the overlay is enabled just fine. So i assume it's a feature that'll need something doing under the hood for that to happen

**Comment by deathbeam** [comment]
I dont think this is related to RuneLite at all.

**Comment by ru-ni** [comment]
Discord detects runelite perfectly fine for the rich presence stuff but for the life of me I can't figure out how to get the overlay to trigger.

The overlay is whitelisted and whatnot so i figure there's something that needs to happen within runelite for it to detect it as an "overlayable" thing?

**Comment by deathbeam** [comment]
Not really, there is no API for "intergrating" that. It either works or do not works, but its all on Discord side.
