### ISSUE TITLE
RuneLite startup problems. Logs attached.

### ISSUE THREAD

**Issue by loamii** [runelite/runelite#4877]
Used RuneLite perfectly fine for the first time opening. Next time i opened it, it immediately closed upon startup. Now it keeps happening without working. (I started using RuneLite today).
Tried reinstalling twice, didn't fix the problem.

[application.log](https://github.com/runelite/runelite/files/2281301/application.log)
[launcher.log](https://github.com/runelite/runelite/files/2281302/launcher.log)

**Comment by loamii** [comment]
I have IPV6 disabled on my computer so could that be the reason?

**Comment by Gamer1120** [comment]
I can't see anything weird in the logs. Feel free to hop on the #support channel in the Discord. Maybe we can get to the bottom of this.

**Comment by deathbeam** [comment]
Closing as this issue has no info, and is most likely some common issue found in Troubleshooting: https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client
