### ISSUE TITLE
Add Ability to Ignore Skills in XP Tracker

### ISSUE THREAD

**Issue by Nealon01** [runelite/runelite#4879]
For skills that I already have 99 in, I don't want the XP tracker to show rows for.  Can you add the ability to ignore certain skills?

**Comment by deathbeam** [comment]
Duplicate

**Comment by Nealon01** [comment]
Duplicate of what issue?  Is this being worked on?

**Comment by deathbeam** [comment]
#2631 #1080

**Comment by Nealon01** [comment]
Both of those issues deal with the XP Tracker globes.  My request is for the XP Tracker itself.

**Comment by deathbeam** [comment]
#2631 is for xp tracker

**Comment by Nealon01** [comment]
Ah, my mistake.  I saw the comment at the end of that issue mentioning the orbs issue and thought it had been addressed as that.  Thanks.
