### ISSUE TITLE
NPC aggression notifier

### ISSUE THREAD

**Issue by AugustIgner** [runelite/runelite#4880]
**Is your feature request related to a problem? Please describe.**
Destroying some sand crabs while studying and time passes so quick you don't even notice they're not aggressive anymore. Results in XP waste. The out of combat notifier is not enough, as often you slay those bastards faster than they can spawn or someone crashes you. Also, the log out for idling notifier is still broken in afk combat scenarios (extra annoying when splashing). 

**Describe the solution you'd like**
A notifier moments before monsters stop being aggressive. Togglable of course.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by deathbeam** [comment]
Duplicate

**Comment by lexlikely** [comment]
Cannot find the original. Please link
