### ISSUE TITLE
World Hopper: Current world highlight

### ISSUE THREAD

**Issue by forsco** [runelite/runelite#4881]
Currently when building runelite with the world hopper plugin the local players current world highlight is not being updated.

I logged in with default world 390 but 388 was being highlighted green. After hopping a few worlds I noticed 388 was still showing as the highlighted world.

**Expected behavior**
I would expect the players new world to be refreshed and the highlights `updated`

**Screenshots**
https://lambda.sx/AXy.png

**Environment (please complete the following information):**
IntelliJ Build using shaded jar.

**Comment by Alexsuperfly** [comment]
unable to reproduce, seems to work fine now
