### ISSUE TITLE
XP Tracker, Set to level 

### ISSUE THREAD

**Issue by Zachigg** [runelite/runelite#4885]
**Is your feature request related to a problem? Please describe.**
No there is no problem with my request that i am aware of, but i would love it if the XP tracker had a set level option, idk i just think its nice to be able to see the goal ahead... for example being at 80 Strength and setting the XP tracker for strength at 85 to see what you're in for.. similar to OSB xp tracker would be awesome. 

**Describe the solution you'd like**
Being able to see xp tracker set levels, just a little more in depth

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by oplosthee** [comment]
This is a feature of the vanilla client, right click the xp orb close to your minimap to configure it.
