### ISSUE TITLE
Allow xp tracker to set a target level

### ISSUE THREAD

**Issue by russel204** [runelite/runelite#4888]
In OSB the tab that shows your xp rates allows you to right click and set a "target level" it will then show your XP to that level instead of the xp to your next level. Could that be implemented to RL?

**Comment by MagicfTail** [comment]
https://github.com/runelite/runelite/wiki/XP-Drop

**Comment by russel204** [comment]
@MagicfTail that's not what i'm referring to. I mean on the client itself not inside of the game window. On the tab under settings that shows xp rates, actions left, xp gained and whatnot. Rather than having to use the built in one can it be made so that I can right click the skill in the tab i'm referring to.

https://gyazo.com/3f3f5a2884d7b431a7399615a36ff0fa

**Comment by deathbeam** [comment]
This is intentional. XP tracker sidebar will reflect the vanilla settings.

**Comment by russel204** [comment]
@deathbeam I know its intentional to work that way. You're saying you're saying you refuse to implement it this way as well? Using that functionality is a lot less intuitive than the way OSB does it.

**Comment by Nightfirecat** [comment]
That's correct--there are no plans to reimplement the ingame goals system.

**Comment by russel204** [comment]
@Nightfirecat I hope you'll reconsider. That system is terrible. having to stop what you're doing to set goals when it can be done with an un-intrusive right click is much better.

**Comment by russel204** [comment]
Either way thanks for the quick responses everyone

**Comment by deathbeam** [comment]
You dont set goals that often. Also, it is not possible to force set vanilla xp goal, so then we would need to either drop vanilla support or have 2 different goal settings (1 vanilla and 1 ours), so yeah.
