### ISSUE TITLE
Oxygen Level bar overlaps RuneLite overlays

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4892]
![image](https://user-images.githubusercontent.com/9074448/44058177-a0c1db36-9f4d-11e8-8994-d309d8d10da9.png)
I know I can just move it with alt, but this shouldn't be default behaviour.

**Comment by EricWagnerJr** [comment]
alt drag the Runelite overlays somewhere else.

**Comment by deathbeam** [comment]
Yeah, you can just move it, I dont think we are solving this. We can maybe add support for movable oxygen bar too, but this is problem at way too many places anyway.
