### ISSUE TITLE
World hopper plugin causes left/right arrow camera movement to get stuck.

### ISSUE THREAD

**Issue by Wea1thRS** [runelite/runelite#4897]
**Describe the bug**
World hopper plugin checks for ctrl + shift + left and ctrl + shift + right keypresses to swap worlds by default, when only left or right is pressed the camera movement turns around in circles with no stopping it unless you change focus off of the runelite client.

**To Reproduce**
1. Run runelite with default world hopper quick-hop keybinds.
2. Try moving the camera left or right with arrowkeys.

**Expected behavior**
I expect for the arrow keys to stop moving the camera around once you let go of the keypress.

**Screenshots**
https://gfycat.com/RealVillainousFishingcat

**Environment (please complete the following information):**
 - OS: [Windows]
 - RuneLite version: [1.4.12-SNAPSHOT]
 - Launcher version: [Unknown?]

**Additional context**
I don't think logs are needed for this; if they are let me know and I can upload.

**Comment by forsco** [comment]
Can confirm this is happening.

**Comment by Matt2408** [comment]
Having the same issues aswell. Solved by disabling word hopper atm.

**Comment by Wea1thRS** [comment]
For anybody else having this issue, can fix it by using a different keybind in the settings:
![image](https://user-images.githubusercontent.com/30428646/44085590-a2a4eb82-9f7f-11e8-9210-1287386aa2d6.png)

**Comment by oplosthee** [comment]
```
	@Override
	public void keyReleased(KeyEvent e)
	{
		if (keybind.get().matches(e))
		{
			isPressed = false;
			isConsumingTyped = false;
			
			if (Keybind.getModifierForKeyCode(e.getKeyCode()) == null)
			{
				// Only consume non modifier keys
				e.consume();
			}
		}
	}
```

For whoever wants to look at his: the arrow key is consumed here, which causes the game to keep the key held down and the camera spinning.

**Comment by Adam-** [comment]
@Abextm can you look at this?
