### ISSUE TITLE
All The Things!

### ISSUE THREAD

**Issue by Feyl0rd** [runelite/runelite#4900]
Would be sweet to have a item tracker for collecting **All The Things**! Something that auto-tracks it if possible and maybe options for toggling no longer obtainables. Inspired directly from the WoW addon ATT. Maybe an option to choose to play a little fanfare when you get an item you haven't gotten yet.

**Comment by psikoi** [comment]
but like, all of them? that's a lot of things

**Comment by Feyl0rd** [comment]
Probably not? I'm not sure what would be easier from a design pov. Adding every item or going through and putting in only certain ones. What I personally like about ATT is seeing the % collected going up

**Comment by psikoi** [comment]
Please give us some concrete examples

**Comment by Feyl0rd** [comment]
Examples of what items someone might put in? Well if it isn't all of them maybe its better to have it to where the user tracks the items they want instead

**Comment by oplosthee** [comment]
This reminds me a bit of the [in-game collection log](http://services.runescape.com/m=news/looting-bag-improvements-pid-changes-and-bounty-hunter-targets?oldschool=1) that Jagex is planning to add. We might be able to extend that system once it's live to show progression and stuff like that, or perhaps even add more items/quests to it.

**Comment by Feyl0rd** [comment]
Also going back to the **ALL the things?**
Maybe instead of tracking each individual item it could be instead just persistent quest items, weapons and armors with other items of general interest

**Comment by deathbeam** [comment]
Well it looks like that jagex tracker would be able to collect most of stuff that also the ATT plugin for WoW does, I think (based on quick googling).

**Comment by winterdaze-rs** [comment]
in-game collection log has been added so this can probably be closed?
