### ISSUE TITLE
Screen Markers not working

### ISSUE THREAD

**Issue by Y3R** [runelite/runelite#4904]
When trying to create a new screen marker it follows graphical lines already in the client instead of creating a box shape which I requested it to do. Is there any fix to this? I have it in fixed mode as well also tried it in resizable it's not worked.

https://ibb.co/itoSGU

**Comment by deathbeam** [comment]
Looks like https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration is fixing this

**Comment by Y3R** [comment]
Just found a solution for it 5 minutes ago with disabling hardware acceleration, thank you!
