### ISSUE TITLE
graceful marks per hour

### ISSUE THREAD

**Issue by shogunreaper** [runelite/runelite#4909]
can this be added?

currently going for full graceful and its easier to be motivated when i know approximately how long i need to do something.

**Comment by GillGurpreet** [comment]
There's no public formula for determining how many marks of grace you should expect per hour, and there's different account factors that can either increase (diaries) or decrease (level caps) the amount you can get. If we were given some formula on this, the approximations would, naturally, become more accurate.

I guess the plugin could take this into account, but based on what we know the plugin would only display approximations for the number of marks you get, pulled from past experiences of other players.

**Comment by shogunreaper** [comment]
yeah i just mean based on what you get, for example if i picked up 10 marks in the last hour then it would be 10 marks per hour.

**Comment by deathbeam** [comment]
This is way too random, sometimes you can get a lot sometimes none. I dont see any reason why displaying data like this to users makes sense or the data are useful for anything

**Comment by deathbeam** [comment]
Because XP/hr is not usually based on so much randomness as marks of grace are.

**Comment by shogunreaper** [comment]
but just because its random doesn't mean it will be inaccurate.

**Comment by deathbeam** [comment]
What i am trying to say is that with current counters you can say that if you will keep doing what you are doing, you WILL gain ~x xp/hr, or around x logs/hr, fish/hr.
But if your average marks of grace /hr will be idk, 10, you can as well just get 0 next hour if you will be really unlucky.

**Comment by shogunreaper** [comment]
then it would just average out?
