### ISSUE TITLE
WASD plugin not consuming input correctly on MacOS

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#4915]
When moving with WSAD and then pressing enter, the typed text will be sent as message.

**Comment by Adam-** [comment]
I can't reproduce this.

**Comment by Kamielvf** [comment]
Can't reproduce this either

**Comment by jamyc** [comment]
I can also reproduce this on Mac.

**Comment by deathbeam** [comment]
This was fixed in 1f82fe4c8d0c330cd1019fe994895f6a8e029f8d
