### ISSUE TITLE
Add a built-in recording tool

### ISSUE THREAD

**Issue by offZills** [runelite/runelite#4920]
i guess it would be cool if you could add a built in video recording tool of the game like you did with screenshotting, going to be so useful and won't consume much memory like other softwares do.

**Comment by raiyni** [comment]
What's wrong with sharex?

**Comment by Nightfirecat** [comment]
There are full programs (see OBS Studio) with entire teams devoted to creating good video recording/streaming tools. I would highly recommend using one of those instead.

**Comment by GillGurpreet** [comment]
Not exactly sure why but typically built-in recording tools occupy a lot of space/put a lot of load on the client and aren't feasible for a client as widespread as RL.

**Comment by deathbeam** [comment]
Yeah I think this is very bad idea when there are programs that will always do better job than w/e implementation would we have.

**Comment by deathbeam** [comment]
Yeah this looks like wontfix to me
