### ISSUE TITLE
Puzzle Box solver not working for Cerberus Puzzle Box

### ISSUE THREAD

**Issue by ZufiOSRS** [runelite/runelite#4923]
Usually the puzzle box helper works but the arrows to guide you aren't appearing for the cerberus puzzle box for my master clue.

 - OS: Windows
 - RuneLite version: [e.g 1.4.11]
 - Launcher version: [e.g 1.6.0]

**Comment by devLotto** [comment]
Fixed with #4819. Will be in tomorrow's release.

**Comment by Alexsuperfly** [comment]
arrows are broken till update tomorrow, use the dots option in the puzzle solver plugin till then
