### ISSUE TITLE
A plugin that makes you unable to open more implings if it sees you have a clue in inventory

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#4927]
Since you can't humanly react to stop looting impling jars as soon as there is a clue looted this would remove that issue and save impling jars.

When a clue scroll is in inventory change the left click option to "use" or just not left clickable at all as long as it stops you from using the left click option.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features see section about conditional menu entry swapping

**Comment by Scahry** [comment]
how about this in the plugin hub?
