### ISSUE TITLE
Little improvement for the Birdhouse notification

### ISSUE THREAD

**Issue by Didnotdiebtw** [runelite/runelite#4928]
It seems the bird house notification only shows when the client is in the background/not focussed. This causes me to miss some notifications about bird houses.

I'd like the possibility to receive notifications when the client is focussed. (So on top of other windows)

**Comment by deathbeam** [comment]
Enable send notifications when focused in RuneLite settings

**Comment by Didnotdiebtw** [comment]
Oh my bad, thank you very much!
