### ISSUE TITLE
When sorting by activity, first show all worlds with an activity, and then without

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4938]
If you sort by activity, you get this:
![image](https://user-images.githubusercontent.com/9074448/44211150-a1eaf200-a168-11e8-9b6e-338730b22916.png)
The activities are way down. Just like the RuneScape client does, first show the worlds with activities, and then without.

**Comment by deathbeam** [comment]
Just click the button again?

**Comment by psikoi** [comment]
Fixed in #4941

**Comment by Gamer1120** [comment]
Thanks!
