### ISSUE TITLE
Alt to move map, xp orb and other details issue

### ISSUE THREAD

**Issue by Arastaiel** [runelite/runelite#4939]
**Is your feature request related to a problem? Please describe.**
I really get quite frustrated when accidentally press my Alt key and move around items on my screen like XP orbs and map

**Describe the solution you'd like**
I would like there to be an option to turn on and off the Alt to move option.

**Comment by whitehooder** [comment]
You can reset the position with alt + right click, though it is still a reasonable request.

**Comment by deathbeam** [comment]
Duplicate of #3826
