### ISSUE TITLE
Add color for ignored player in player indicators

### ISSUE THREAD

**Issue by Jerpai** [runelite/runelite#4944]
I just added known scammers to my ignored list and thought about how i would recognize them if i ever meet them.

I immediately thought about player indicators but it doesnt seem to have this function. It would be very helpful be able to recognize dangerous players that you should not play/trade with fast and easily.

**Comment by deathbeam** [comment]
Same thing as offline friends https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by fuzxi** [comment]
Can this be looked at again? The base Entity Hider already allows you to essentially highlight offline friends by adding them to your ignore list, enabling Hide Others, and disabling Hide Ignores. Everyone who isn't on your ignore list will then be hidden, leaving only ignored players visible.
I would just like an option to disable player indicators for ignored players. It's jarring to have Hide Ignores enabled in Entity Hider and run into someone you ignored previously - you can't see or hear them, but their name is still visible.
