### ISSUE TITLE
WASD Plugin - Pressing space to select make all does not work when plugin is active

### ISSUE THREAD

**Issue by Battlenex** [runelite/runelite#4946]
**Describe the bug**
When the WASD Plugin is active, you can not select the make all crafting button using the space bar. 

**To Reproduce**
1. Enable WASD Plugin
2. Craft something that brings up the craft interface(Chat box one)
3. Press space bar to accept the button and start crafting

**Expected behavior**
When pressing the space bar on the make all interface, it should accept the button and start crafting.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.12
 - Launcher version: 1.5.2

**Comment by deathbeam** [comment]
This was resolved
