### ISSUE TITLE
World Map Button

### ISSUE THREAD

**Issue by Zeek49494** [runelite/runelite#4947]
**Describe the bug**
When you click the World Map Button within the minimap area; You open the World Map and move your character at the same time.

**To Reproduce**
1. Click the World Map within the Minimap Area
2. Protfit

**Expected behavior**
Open the World Map without moving my character.

**Screenshots**
Green = Where you can click to open the World Map without moving your character.
Red = Where you can click to open the World Map, but you'll move your character.
https://i.gyazo.com/23f8a092b0975694bef931ebd8d8fca7.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Lastest Version (8/16/2018)
 - Launcher version: Lastest Version (8/16/2018)
(Don't know where to find the version, sorry Adam. <3)

**Additional context**
n/a

**Comment by Kamielvf** [comment]
This is something you should report to jagex, not to us.

**Comment by Zeek49494** [comment]
Sorry, about that.
