### ISSUE TITLE
Runecrafting Altar menu-entry swapping

### ISSUE THREAD

**Issue by TheArbalist** [runelite/runelite#4960]
Could we have the Menu Entry Swapper get the ability to make the left-click option for all RC Altars be "Walk here", instead?

If you're crafting combination runes, it's easy to accidentally click the "Craft-rune" option on the altar.
I think that a lot of people would be glad to see a plugin that helps prevent this, as it incurs a rather grating penalty due to the delay and the much-reduced experience for that inventory.

**Comment by LlemonDuck** [comment]
This can be done by configuration with hub plugin [Combo Runes Only](https://runelite.net/plugin-hub/show/combo-runes-only) or with the new shift-click custom swaps.
