### ISSUE TITLE
Runecrafting Puches

### ISSUE THREAD

**Issue by Dudification** [runelite/runelite#4961]
I think it would be a useful feature to have rune essence pouches left click switch from fill to empty when they are full.

**Comment by Dudification** [comment]
Put in wrong place

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping

> `onditional menu entry removing`: This can be overpowered in some cases (hiding attack options on NPCs/players based on some conditions, like it being friend or it being specific type of NPC). This includes removing ground items that are hidden or grayed out.
