### ISSUE TITLE
Clicking on world map icon can sometimes click on world map

### ISSUE THREAD

**Issue by hjdarnel** [runelite/runelite#4965]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
1. Click on top left part of world map icon, inside the world map circle

**Expected behavior**
World map opens, character doesn't move. World map button takes priority over world map itself.

**Actual behavior**
Both world map opens and character moves.

**Screenshots**
If I click on the end of this arrow, I will move and the world map will both open. 
![image](https://user-images.githubusercontent.com/7868899/44252426-b9a29480-a1c1-11e8-8207-559f2420da8b.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.12.1
 - Launcher version: Rev 172

**Comment by Abextm** [comment]
Can you reproduce this on the official client?

**Comment by hjdarnel** [comment]
I cannot readily reproduce it, like I can in Runelite. A lot more sporadic in the official client than in RL.
