### ISSUE TITLE
Missing agility coloring/highlight

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#4966]
![image](https://user-images.githubusercontent.com/38350898/44260287-9ce77a80-a21c-11e8-878f-ac1f03644b5a.png)
![image](https://user-images.githubusercontent.com/38350898/44260374-e0da7f80-a21c-11e8-97f0-76a481cf065c.png)

As you can see; the agility shortcut isn't highlighted.. These 2 rocks as you can see on the pictures.

Place: Tree gnome village - b ehind barb fishing area
Skill and level required: Agility - 37?

**Comment by Gamer1120** [comment]
I'm pretty sure it also requires completion of Tree Gnome Village for the person who is going to implement this.

**Comment by VanspauwenSebastiaan** [comment]
Are you sure you have obstacles overlay on? They are already implemented in the code

**Comment by Asymons** [comment]
It is styled on my client.
https://i.gyazo.com/e24f8b2de3c13a59914f3f1d0a22a84e.png

**Comment by Nightfirecat** [comment]
@Floukru Can you please post your agility plugin settings?

**Comment by deathbeam** [comment]
Looks like this is prevent in client, closing
