### ISSUE TITLE
'Collect' as left click for Priestess Zul-Gwenwynig (Zulrah) - Menu-entry Swap

### ISSUE THREAD

**Issue by nmq12** [runelite/runelite#4969]
It would be nice to have 'Collect' option to be left click when collecting items on death at Zulrah's shrine.

**Comment by TheStonedTurtle** [comment]
>Looks good, not needed though. "Talk to" option already collects all items.
https://gyazo.com/71a8799d866aa0db5d5ba2771ac9efa1

This should probably be closed for the same reason.

**Comment by deathbeam** [comment]
Yeah, looks unnecessary
