### ISSUE TITLE
Controlling the mouse on the canvas

### ISSUE THREAD

**Issue by Velixium** [runelite/runelite#4971]
I'd really like to be able to control the internal mouse on the canvas that way I can have a "helper" of sorts for in-game emergencies, such as if i am in combat and i forget to eat or I am not paying attention, my "helper" could move my mouse onto my inventory and then eat some food for me. (I have notifications disabled because they annoy me).

I'm thinking maybe I just need to find the right client script id for mouse movement, and invoke it on the main client thread? Thank you guys.

**Comment by devLotto** [comment]
This is not a bot client.
