### ISSUE TITLE
Graceful cape clipping

### ISSUE THREAD

**Issue by somewhattoxic** [runelite/runelite#4973]
If you have animation smoothing turned on and you zoom in while harvesting herbs your cape will clip through the torso. I'd expect it to not clip through my torso but rather stay on my back where it should be. The bug occurred on windows 10 latest version from yesterday.

https://i.imgur.com/N6Zxtj3.png

Edit: in case its not noticeable its the black jagged line going through the torso.

**Comment by Nightfirecat** [comment]
I'm pretty sure that's a Jagex bug, since we don't affect the rendering order with animation smoothing.
