### ISSUE TITLE
Add "Fairy Ring CKS" to Ulizius clue

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4975]
![image](https://user-images.githubusercontent.com/9074448/44278203-8e658700-a24d-11e8-9e39-f6cd93f7dfe0.png)

**Comment by deathbeam** [comment]
But salve graveyard tele should be better than this? Idk if fairy ring really makes sense in this scenario.

**Comment by Nightfirecat** [comment]
They're about the same, but I'd imagine most people would use fairy rings over arceuus teleports in most cases.
