### ISSUE TITLE
Can't rearrange Corp specs and total damage correctly (maybe fixed already)

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#4978]
From a Discord discussion:
Gamer1120: I asked Faux why he preferred OSBuddy over RuneLite for Corp, and this was his answer: https://clips.twitch.tv/ResoluteCrowdedPelicanYouDontSay (basically likes the spec counter better and can set the dark core to click-through)
FluffyRabbit: he was having trouble positioning it when he first tried it
Gamer1120: Does anyone have the VOD or clip of that?
FluffyRabbit: @Gamer1120 found it https://www.twitch.tv/videos/292173006?t=03h46m06s

Now, I watched Faux struggle a bit with rearranging Corp specs, and this clip seems to sum it up perfectly: https://clips.twitch.tv/WealthyOilyNikudonFutureMan .

Note that this was around 2 weeks ago and might have been fixed already. I have no way of testing this, other than that Faux still uses OSBuddy for Corp.

Relates to #4559

**Comment by Gamer1120** [comment]
Faux did not understand how snap corners work.

**Comment by Nightfirecat** [comment]
:upside_down_face:
