### ISSUE TITLE
Stretched fix constant retuning

### ISSUE THREAD

**Issue by Telavus** [runelite/runelite#4982]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The game window constantly restretches/retunes whenever the sidebar is minized when using stretched fixed mode.

**To Reproduce**
Enable stretched fixed mode
Turn on fixed mode in-game
Minimize sidebar

**Expected behavior**
Static and non-disruptive screen

**Screenshots**
https://imgur.com/a/17gT17x

**Environment (please complete the following information):**
Windows 10 LTSB

**Comment by deathbeam** [comment]
Change Resize type to Keep game size in "RuneLite" settings
