### ISSUE TITLE
Game freezes when using system menubar

### ISSUE THREAD

**Issue by Telavus** [runelite/runelite#4983]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
If you choose to use the system menu bar instead of the "custom window chrome" the game seems to freeze every now and then for up to 3 seconds.

**To Reproduce**
Disable "custom window chrome" in RuneLite settings
Wait or do something until it eventually happens.

**Expected behavior**
Not freezing seemingly at random

**Screenshots**
N/A

**Environment (please complete the following information):**
Windows 10 LTSB

**Comment by deathbeam** [comment]
Seems like your OS issue. Did you tried: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Telavus** [comment]
I have.

This seems to have happened recently with a new update, I am quite sure it
is a bug or unintended side-effect from one of the settings in the client

Den tir. 21. aug. 2018, 13:01 skrev Tomas Slusny <notifications@github.com>:

**Comment by Nightfirecat** [comment]
Does this issue still happen? If so, can you post your application log?

**Comment by Nightfirecat** [comment]
This issue has seen no posts for nearly one year after being asked for more information, so I am closing it.
