### ISSUE TITLE
World switcher flood and delayed hop bug

### ISSUE THREAD

**Issue by ltvill** [runelite/runelite#4988]
First off, make sure that the in-game world switcher is off and you're on the login screen, with the "Did you enjoy playing Old School RuneScape today?" text. Open any shop and quick-hop to the next world. The chat gets flooded with "Please finish what you're doing" and if you exit the shop interface you hop about ten seconds later.

**Comment by Kamielvf** [comment]
This was fixed in #4936

**Comment by ltvill** [comment]
Thanks for letting me know!
