### ISSUE TITLE
Crashes before login

### ISSUE THREAD

**Issue by cmattiacci** [runelite/runelite#4993]
Runelite crashes before I can get to the login screen. The vanilla client works fine. I reinstalled but that didn't work and then I disabled hardware acceleration and it worked yesterday but now its crashing again. I checked and it is still disabled. Anyone have any ideas on what to do?

Here is a video of it: https://youtu.be/znq8XCrWyeI

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client this is corrupted cache looks like, that page has solution how to fix it
