### ISSUE TITLE
incorporating the "paint" application

### ISSUE THREAD

**Issue by partyphat** [runelite/runelite#4994]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [... ]

**Describe the solution you'd like**
- Paint should be incorporated with the runeclient client, because it enables players to take screenshots/videos - and edit them similar to snapchat. There are many other benefits of doing this for example: You're afk skilling, and you don't want to accidentally click on something, so this allows you to censor that "something" whatever it may be.  I think its very simple, easy to do and it has many benefits.

Does not have to be the old paint app - It could be a more modern application which allows for a more user-friendly edit

**Comment by deathbeam** [comment]
Just open the screenshot in actual paint, or use screen markers to censor stuff.
