### ISSUE TITLE
[Experience trackers] Drop-down menu is missing: "Reset all" -option

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#5001]
https://i.imgur.com/dIz7ro7.png

Instead of forcing me to click four times in order to reset all exp trackers, allow me to save clicks by 50%, thanks!

**Comment by deathbeam** [comment]
Right click the box at top

**Comment by Popedigoz** [comment]
Wow, would of never guessed to click there! Should be on the drop-down menu as well!

**Comment by Popedigoz** [comment]
https://i.imgur.com/b75xv5i.png
