### ISSUE TITLE
Switchable in-client profiles

### ISSUE THREAD

**Issue by Vampiricx** [runelite/runelite#5006]
I, like many other RuneLite users, play on multiple accounts at the same time using the client, and one thing that bugs me personally is loading up a Zulrah account and having all of the settings from my main account interfering with with the client (screen markers for instance) and having to change settings for each time can be frustrating. I think it would be cool if we could set up personalised profiles to change between depending on what we're doing.

**Comment by Alexsuperfly** [comment]
this already sort of exists, you can log into the client and it cloud syncs your settings. Could just have multiple of those and that will accomplish what you want.

**Comment by Abextm** [comment]
Duplicate #2220
