### ISSUE TITLE
Don't open the world switcher tab after quick-hopping

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#5008]
When using the quick hop keyboard shortcuts, it shouldn't switch which tab you have open in game. If it's the vanilla client doing it, maybe add something that remembers what tab you had open and switches back to it?

**Comment by deathbeam** [comment]
This would require anothe faking of user input, e.g opening different interfaces for user other than world hopper. not even OSB is doing this, I dont think we should too.

**Comment by ShaunDreclin** [comment]
OSB doesn't open the in-game hopper after hopping though, pretty sure it leaves you on the tab you were on

**Comment by deathbeam** [comment]
I am pretty sure it does that as well. The world hopper will only open if you never opened it before tho.
