### ISSUE TITLE
Remember mouse position on alt-tab

### ISSUE THREAD

**Issue by JustAPerson** [runelite/runelite#5011]
I am willing to implement this. 

I play two accounts at once (ironman btw) and moving my mouse between windows is really tiresome, to the point where I feel fatigue in my hands. I would love to be able to alt-tab between two RuneLite windows and have the cursor position either remembered in each window separately or to recenter it over the viewport.

Before I implement this, I wanted to get some other opinions. I desperately want this functionality to save my hands. I think what I've described is pretty limited, but moving the cursor automatically (even to maintain the illusion that it never moved) is edging towards cheating.

**Comment by Nightfirecat** [comment]
That sounds rather akin to multiboxing, which is definitely cheating.

**Comment by Abextm** [comment]
Having multiple accounts is allowed, however mirroring inputs to all of your clients (like you would in WoW) is not allowed. I think this would be fine to implement, though it sounds rather awkward to use.

**Comment by deathbeam** [comment]
Closing as this as wontfix is automating user input, e.g basically botting.
