### ISSUE TITLE
NPC Indicators config has an issue with trailing commas

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#5012]
If your list of NPCs ends with a comma, Dairy cows get a small triangle under them highlighted.

![screenshot](https://user-images.githubusercontent.com/5851433/44305383-dc5cb680-a343-11e8-9efa-08c3c4e809cb.gif)

**Comment by Nightfirecat** [comment]
From what I recall, that's because unnamed NPCs are selected with an empty string tag, which is effectively what a trailing comma indicates. The same thing can be observed in the Kalphite Queen lair.

We should probably not try to tag NPCs that don't have names.
