### ISSUE TITLE
Do not send idle notification if a click occurred during idle delay

### ISSUE THREAD

**Issue by orlp** [runelite/runelite#5013]
Currently when you enabled the 'send notifications when focused' option you will always receive a notification when your character starts idling (assuming you have idle notifications turned on). However, sometimes I'm looking at my character anyway, and notice the idling and already clicked to resolve this during the idle notification delay. In this scenario it's quite annoying to still receive an idle notification.

I suggest we add some logic to the idle notifier (possibly as an option if this breaks some people's workflow) that *if the game has received a click during the idle notification delay, the notification gets cancelled*.

**Comment by deathbeam** [comment]
#3412 solves this

**Comment by orlp** [comment]
@deathbeam Could someone else review that maybe? It doesn't seem like @Adam- is responding.
