### ISSUE TITLE
Issues on right click hop-to in clan chat

### ISSUE THREAD

**Issue by Tangentajohn** [runelite/runelite#5023]
I was trying to use lookup function for someone in clan chat and accidentally clicked hop-to on that guy and found out a bug.

When you try to right click world hop to a person in clan chat when you are in something like raid1, the world hopper will attempt to hop endlessly even though it is not possible to hop in raids1, which results in the chatbox will keep spamming "this is not a good place to hop world", you can hardly move your character when the spamming starts. After awhile the game will start short dcs repeatedly. I tried to turn off world hop plugin and it fail to stop the attempts.

At last I could only close the client completely to end this spamming thing

**Comment by deathbeam** [comment]
This was already fixed, will be in next release
