### ISSUE TITLE
JVM crash on "Loading game sprites"

### ISSUE THREAD

**Issue by cmattiacci** [runelite/runelite#5029]
Hello! I'm sorry to make the same post twice but the last one got closed before it got solved. Runelite crashes when loading, usually on "loaded sprites". On the last post someone said it was a corrupted cache and that I should delete it. I did that and it worked but now its crashing at the same stage again. Whenever I delete the cache it works for one launch. When I close it and get on later it crashes again until I delete the cache. Is there a way to permanently fix it or will I always  have to delete the cache. I otherwise love Runelite and I hate to make this post again.

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest RuneLite release.
