### ISSUE TITLE
Change plugin configuration search to index sub settings/descriptions

### ISSUE THREAD

**Issue by GibsDev** [runelite/runelite#503]
https://github.com/runelite/runelite/blob/2e94607655143b9dbc19c22ccda9386ba86a82a8/runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java#L144

I think changing the keys for the `children` Map from plugin names to keys would be useful. Currently the keys are built using the name of the plugin (`Boosts Info` rather than `boostsinfo`).

https://github.com/runelite/runelite/blob/2e94607655143b9dbc19c22ccda9386ba86a82a8/runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java#L112

Ideally this would prioritize results depending on where the search string was found. Such as
name of plugin > plugin description > sub setting name > sub setting description

A step further would provide some way of actually viewing sub setting matches (like tooltip popup for each applicable result) without having to click on each search result to peek inside them.

**Comment by deathbeam** [comment]
I believe this was already fulfilled by adding tags to plugins. With good enough tags searching sub options is not needed anymore.
