### ISSUE TITLE
Hide prayers within the prayer tab

### ISSUE THREAD

**Issue by SirDylan** [runelite/runelite#5032]
There's a large number of prayers within the tab that one will never use after a certain level. Why can't we just remove those?

I'd love to be able to remove prayers while reordering, and the possibly resize them a tad.

Excuse my poor photoshop skills. 

![oof](https://user-images.githubusercontent.com/35585687/44373114-1a291e80-a4ad-11e8-90de-34a27f36e6dd.png)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
