### ISSUE TITLE
Add support for thieving to loot tracker

### ISSUE THREAD

**Issue by Matyim** [runelite/runelite#5033]
I was thinking that with the new addition of the loot tracker for kills on mobs that it would also be good to have one tracking thieving loot to show the total price. I was thinking of instead of the way where it tracks items on the ground after a kill that it would just check each time you pickpocket for a new item going into your inventory. Or by looking in chat and then adding that to the list, so for a master farmer in chat it would say 4 potato seeds, then it could list potato seeds in the loot counter and say the total price.

**Comment by deathbeam** [comment]
This makes no sense, would you display thousands of entries for each pickpocket? We have #4126 what is more skilling oriented, adding this to loot tracker would be dumb
