### ISSUE TITLE
Option to have the Harpoon entry in Menu Entry Swapper not affect Monkfish spots

### ISSUE THREAD

**Issue by ProgenitorX** [runelite/runelite#5037]
**Is your feature request related to a problem? Please describe.**
Players who fish at Monkfish locations go specifically for Monkfish. The current option in Menu Entry Swapper make Harpoon the default for every fishing spot, causing a very small inconvenience when fishing Monkfish.

**Describe the solution you'd like**
Have a checkbox to keep Net as the left click option only for Monkfish spots (overrides Harpoon option).

**Describe alternatives you've considered**
Turning Harpoon off from Menu Entry Swapper when Monkfishing, back on when done.

**Additional context**
Obviously this is just a very small QoL change, but would be nice to have as an option.

**Comment by deathbeam** [comment]
I think as this is configurable and now disabled by default this is no longer necessary
