### ISSUE TITLE
Add in game notifications on jewelry when it breaks

### ISSUE THREAD

**Issue by danny303** [runelite/runelite#504]
Something similiar to konduit - binding necklaces, duel rings, glories, etc.

**Comment by josharoo** [comment]
When you say in-game notifications do you mean a message in the chatbox or a system tray notification? I thought most jewellery already has a chat message, at least dueling ring and glory tell you when using a charge and when it is destroyed 
![](https://i.imgur.com/4juZi3e.png)

**Comment by AugusDogus** [comment]
I'm in favor of a system tray notification.

**Comment by deathbeam** [comment]
This is doable via chat notifiactions plugin now
