### ISSUE TITLE
Vanilla XP drop issue

### ISSUE THREAD

**Issue by SlaughterRS** [runelite/runelite#5052]
XP drops only remain visible for ~1s, then cut off halfway up inventory?
Happens in both fixed and resizable?

**Comment by Nightfirecat** [comment]
Can you share a gif or video of this happening?

**Comment by deathbeam** [comment]
Is this also issue in Vanilla?

**Comment by SlaughterRS** [comment]
Hey, guys,

 I have uploaded an image of the issue.

As you can see the drop starts at the bottom and cuts off almost immediately? Any help is much appreciated!

Thanks!
![drop](https://user-images.githubusercontent.com/42600730/44625891-9b980b00-a90a-11e8-9ac0-9886a677b22e.png)

**Comment by SlaughterRS** [comment]
haha thanks for that!

Yes it always occurs, almost as if it is starting lower on the client than it should and hitting an invisible wall?

![untitled](https://user-images.githubusercontent.com/42600730/44631605-6c16ec00-a966-11e8-9022-f7ca482c2878.png)

**Comment by ShaunDreclin** [comment]
What happens if you change this setting?

![screenshot](https://user-images.githubusercontent.com/5851433/44631627-c602bc00-a93c-11e8-9381-fc5a2ca84cd1.png)

**Comment by SlaughterRS** [comment]
Exactly the same issue, just either left, right  or middle.

**Comment by ShaunDreclin** [comment]
Well this one's a head scratcher! I'm out of ideas.

Try asking in the #support channel on discord, link them this issue

**Comment by fimppah** [comment]
So i fixed my issue with it. you need to make the progress bar visible first. Right click xp button and select setup and put progress bar ON then press and hold alt and drag the bar to the TOP of the screen. then they should appear normally again.

**Comment by Nightfirecat** [comment]
Hm, so the collapsed progress bar was covering the top of the XP drops as they moved up, since it had been moved down?

**Comment by fimppah** [comment]
kinda yeah but it doesnt matter where the bar is the xp drops dont go higher than the progress bar. made a vid take a look.
[2018-09-03 08-58-56.zip](https://github.com/runelite/runelite/files/2344350/2018-09-03.08-58-56.zip)

**Comment by deathbeam** [comment]
Hmm so this looks like it is not solvable by us and it is limitation of the widget system, closing as wontfix
