### ISSUE TITLE
Using the quick-hop feature from world 35 causes a hop to world 16, rather than to world 26.

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#5068]
**To Reproduce**
1. Go to world 35
2. Use the <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>↑</kbd> quick-hop shortcut
3. See that you will be hopping to w16 rather than 26.

**Expected behavior**
As w26 is not a pvp world, I would not have expected it to be skipped.

**Comment by Karolcz125** [comment]
will take care of it

**Comment by devLotto** [comment]
Treat LMS worlds as regular worlds to fix this
