### ISSUE TITLE
Feature to add Hotkey/Keybindings in WASD camera-tool

### ISSUE THREAD

**Issue by lib3x** [runelite/runelite#5070]
**Is your feature request related to a problem? Please describe.**
As a Macbook user i find it hard to use [fn]+[f *number*] when switching from one prayers to bag interface, especially when i do PvM or PK, my current DIY-fix is a small rock taped to the [fn]-key that allows me to place my palm on it and use my fingers freely across the keyboard, however, it's not practical. 

**Describe the solution you'd like**
Hotkeys/keybindings without pressing [fn] or [shift]

**Describe alternatives you've considered**
When looking through all the tools i found one very nifty tool - WASD Camera, that allows me to use  WASD-keys to control the camera and ENTER-key to type my message when needed. 

That's very useful! But i would love it if a feature was added that allowed me to bind hotkeys to the numbers [1]-[9] without having to use [shift] or [fn] this would make things such as switching from prayers to bag much easier, it would allow me to be more focused on bosses such as JAD or when i'm PKing :) 

**Additional context**
Thanks for an awesome client!

**Comment by raiyni** [comment]
https://github.com/runelite/runelite/pull/4991

**Comment by drmlkjr** [comment]
Not a Runelite feature but I had the same issue, and use Alfred to force all my f keys to be just that: f keys.

https://www.alfredapp.com/

http://www.packal.org/workflow/toggle-between-special-fn-keys-and-standard-fn-keys-mac

Pretty crappy that on a mac I had to resort using a paid program, but tbh Alfred is the most useful thing I've installed in years on this OS.  I didn't even get it for this originally.  But I'm not sure when, Apple "used" to have an fkey setting in the keyboards menu to make them normal, they took it off now. 

You may also be able to go your Sys Pref > Keyboard > Shortcuts and tick "off" all the fkeys that are mapped there.  Idk if it'll change how they work, definitely worth trying though.

**Comment by deathbeam** [comment]
You can just do that in Mac settings, e.g make the special keys require FN and by default make them act as F keys

**Comment by EVOuser94** [comment]
After searching for a feature like this i wrote an AHK script to do that, as I was suggested to do...
If anyone wants to use it here it is.

`#Persistent
DetectHiddenWindows On
#NoEnv
#SingleInstance force ;Prevents popup asking for new instance
#ifWinActive, RuneLite ; only allows Script Interaction within RuneLite
Runwait, C:\Users\Matt\AppData\Local\RuneLite\Runelite ; Set this to your RuneLite Path
SetTitleMatchMode, 2

;**********************
;|Exit Script on Close|
;**********************

Sleep 500
SetTimer StopScript, 200
Loop 
WinWait, RuneLite, 
IfWinNotActive, RuneLite,
WinWaitActive, RuneLite, 

StopScript:
IfWinNotExist, RuneLite
    ExitApp
Return

;***************
;|Call Commands|
;***************

^Ins::Run Login.exe ; used to make a seperate Script log OSRS accounts in with key combos'




;************************
;|Hotkeys For Tab Switch|
;************************

Numpad0::F2 ;Skill Tree
Numpad1::ESC ;Inventory
Numpad2::F5 ;Prayers
Numpad3::F6 ;Magic
Numpad4::F1 ;Combat Options
Numpad5::F4 ; Worn Equipment
Numpad6::F3 ;Quest
Numpad7::F8 ;Account Management
Numpad8::F7 ;Clan Chat
Numpad9::F11 ;Emotes
NumpadDiv::F9 ;Friends
NumpadMult::F10 ;Options
NumpadSub::F12 ;Music Player
NumpadAdd::Launch_App2
NumLock::WinClose Calc

;**************
;|Disable Keys|
;**************
F1::MsgBox To use press Numpad 4 
F2::MsgBox To use press Numpad 0 
F3::MsgBox To use press Numpad 6 
F4::MsgBox To use press Numpad 5 
F5::MsgBox To use press Numpad 2 
F6::MsgBox To use press Numpad 3 
F7::MsgBox To use press Numpad 8 
F8::MsgBox To use press Numpad 7 
F9::MsgBox To use press Numpad / 
F10::MsgBox To use press Numpad * 
F11::MsgBox To use press Numpad 9
F12::MsgBox To use press Numpad -


;***********************
;|Miscellaneous Hotkeys|
;***********************

RCtrl::Rbutton ; Add Hotkey to Right click by pressing the Right Ctrl Key
RAlt::Lbutton ; Add Hotkey To Left click by pressing the Right Alt key
PgUp::Suspend ; Suspends This Script
SetNumLockState, AlwaysOn
Ins::Run, https://oldschool.runescape.wiki/
Home::Run, https://oldschool.runescape.com/
return`

I do realize this is shitty scripting, if anyone wants to make this better feel free, but as of right now this is working for me with AutoHotKey

**Comment by deathbeam** [comment]
@EVOuser94 `s a Macbook user i find it hard to use [fn]+[f number]`

**Comment by EVOuser94** [comment]
@deathbeam honestly I wouldn't know how to go about solving that one, I use Windows 7, and have no experience really with any of this...

**Comment by Adam-** [comment]
This was added in #8915
