### ISSUE TITLE
Movable/ larger XP drops

### ISSUE THREAD

**Issue by Jmac191** [runelite/runelite#5075]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

It'd be nice to be able to make the XP number drops larger than what we're currently able to. Would it also be possible to add an ALT+drag option somewhat like the XP globes to the XP drops? I'd like to be able to put the drops right beside my character or beside my inventory. 

**Additional context**
N/A

**Comment by SirDylan** [comment]
Agreed.

**Comment by CamiloJac** [comment]
Has anything happened with this yet?

**Comment by Felanbird** [comment]
This is possible via the hub plugin `Customizable xp drops` 

![image](https://github.com/runelite/runelite/assets/41973452/9e257b23-cf59-4bab-b7e4-b3e2cf5edfda)
