### ISSUE TITLE
Plugins Gone after update

### ISSUE THREAD

**Issue by Edanias06** [runelite/runelite#5078]
After the update today 8-23-2018 all the plugins I had set up within Runelite are now gone and there is no plugin panel could you please look into the issue Thank you 

 Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by NathenSample** [comment]
*bashes user round the head with a frying pan*

**Comment by Wea1thRS** [comment]
Close and relaunch. It was just updated.

**Comment by Edanias06** [comment]
Im sorry but is is not nice to hit me with a frying pan and Thank you very much @Wea1thRS and honestly I did not know about the update thanks again

**Comment by Wea1thRS** [comment]
No problem! This issue can be closed.
