### ISSUE TITLE
Overlays no longer working after todays update

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#5080]
Having the side panels set to "resizable mode stone buttons" will make runelite overlays not show up.
To fix this, toggle the side-panels under "Advanced Options" under the in-game graphics options.

**Comment by alex-vincent** [comment]
jagex bug. do this: https://pbs.twimg.com/media/DlS3l6YWsAMe3Of.jpg:large

**Comment by ollieatkinson** [comment]
![aecc6b9a-b205-4357-97d9-d5dd3481ddbc](https://user-images.githubusercontent.com/1382565/44539063-15f24080-a6fb-11e8-92f4-bbac5a76b04e.png)

Looks fine to me. I am on version 1.4.14

**Comment by justind-dev** [comment]
Toggling side panels did not resolve my issue #5081 for me. Must be a separate issue? @raiyni

**Comment by raiyni** [comment]
Works for me

**Comment by Kamielvf** [comment]
This is only in resizable, with bottom line stones enabled.

**Comment by justind-dev** [comment]
I cannot seem to get the bottoms stones to enable in resizable mode.

**Comment by Kamielvf** [comment]
Yes, see https://twitter.com/OldSchoolRS/status/1032652169017806848

**Comment by justind-dev** [comment]
<a href="https://ibb.co/kpobxe"><img src="https://preview.ibb.co/cDYn3K/resizable.png" alt="resizable" border="0"></a>

**Comment by raiyni** [comment]
Click the button so it is grayed out.

**Comment by justind-dev** [comment]
Ah, thank you very much. I must have missed that tweet this morning. Thank you again.

**Comment by Olvaliance** [comment]
okay to anyone still confused do not click on the dots with checks, click directly on the image. thanks deathbeam.

**Comment by justind-dev** [comment]
@Olvaliance thank you! That cleared it right up.

**Comment by 22pickle2** [comment]
@oplosthee It used to lay down at the bottom. Like this.
![woodcutting 47](https://user-images.githubusercontent.com/42656490/44550202-1e418000-a6e9-11e8-9a71-6c2717c7566d.png)

**Comment by oplosthee** [comment]
@22pickle2 That's an issue introduced by Jagex in the latest update. They'll hopefully fix that as soon as possible. See https://twitter.com/OldSchoolRS/status/1032652169017806848.

**Comment by 22pickle2** [comment]
@oplosthee  i see. Thanks!

**Comment by Ganjaflow** [comment]
My plugins work, but not the changes I made to them. Like i've changed the colours of certain drops or xp drops for example. but it just shows the default settings.

**Comment by timbriers** [comment]
I'm glad other people are having similiar issues, for me the client is completely bugged and the settings reset every time i restart. Rune pouch, ground items text not showing etc...

**Comment by Kamielvf** [comment]
This issue is no longer valid, as jagex fixed their issue which affected our overlays.
