### ISSUE TITLE
No Mouse Over Tool-tips 

### ISSUE THREAD

**Issue by justind-dev** [runelite/runelite#5081]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
No mouse over tool tips after update. "Such as hovering over NPC's or hovering over crops while farming"

**To Reproduce**
1. Login In
2. Hover mouse over normally intereactive features and NPCs.
3. Nothing appears at the mouse.

**Expected behavior**
There should be a hover tool tip showing default action for NPC and enviornment. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.4.4
 - Launcher version:1.5.2

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by raiyni** [comment]
https://github.com/runelite/runelite/issues/5080
