### ISSUE TITLE
Hide/minimize/reorder time tracking sidebar

### ISSUE THREAD

**Issue by RandW5** [runelite/runelite#5084]
**Is your feature request related to a problem? Please describe.**
When playing on fixed screen size the time tracking menu requires you to scroll down to see all the timers when only some of them are relevant to each player. I only care about the bush, tree, fruit tree and birdhouse timers but can't only have these ones open.

**Describe the solution you'd like**
Add the ability to reorder the time tracking sidebar, or be able to minimize/hide time trackers you don't want or need.

**Comment by deathbeam** [comment]
Duplicate of #3056
