### ISSUE TITLE
Streamer Mode - Hide World etc

### ISSUE THREAD

**Issue by TzZek** [runelite/runelite#5087]
When Streamer Mode is enabled, world list on friends list is hidden, in clan chat is hidden, when hopping worlds the worlds are scrambled but the world you are on can be viewed on the sidebar. Option to show different username in chatbox.

Would help to easier prevent stream sniping.

Not sure if this is practical but could be neat for various users.

**Comment by gccltl** [comment]
I already proposed this suggestion.

**Comment by TzZek** [comment]
My bad repeat of #2980
