### ISSUE TITLE
Chat command - killcount not working 

### ISSUE THREAD

**Issue by bugginben** [runelite/runelite#5091]
When using the !kc chat command, a lot of the options will not show the kill count, the bosses I have tried is jad, armadyl, zamorak, vorkath, zul'rah, king black dragon and barrows. Each of these didn't work when I tried to use the kill count chat command. However "!kc bandos" and "!kc general graardor" did work and showed my bandos killcount. The price chat command works fine but just not the kill count command, and because it shows my bandos kc it proves it is toggled on.

**To Reproduce**
Enter into the chat "!kc [boss]"

**Expected behavior**
When entered into the chat a lot of bosses will not show the players kill count for the bosses and just show the command

**Screenshots**
![screenshot_44](https://user-images.githubusercontent.com/42657246/44552087-f837d200-a720-11e8-8aa1-90541e62ce0a.png)
![screenshot_45](https://user-images.githubusercontent.com/42657246/44552093-fa9a2c00-a720-11e8-8552-b32a2fddb558.png)

**Environment (please complete the following information):**
 - OS: Windows 10 - 64 bit
 - RuneLite version: [e.g 1.4.14]

**Comment by Nightfirecat** [comment]
Have you killed these bosses or viewed your boss log in your ring of wealth on Runelite? If not, it has no way to know what your boss kill count is.

**Comment by deathbeam** [comment]
You nee to either get the kill or check ring of wealth
