### ISSUE TITLE
Not All Client Features Working

### ISSUE THREAD

**Issue by SHEPTHESHEEP** [runelite/runelite#5097]
Some features are not working.
Been using runelite for 4 months now. Never had a problem with it. Recently got hacked and lost everything so I took a week off. Went back on to find out that most of the client features had stopped working. 

Not too sure how this could be reproduced. I took a week off and now the client isn't working properly.

I uninstalled and reinstalled runelite and it still isn't working. Tried turning off the features and turning them back on. Also asked a friend in-game if they had any problems. 

 - OS: [Windows 10]
 - RuneLite version: [1.4.14]
 - Launcher version: [1.6.0]
 - Oldschool revision: [Rev 174]

![desktop screenshot 2018 08 23 - 22 29 05 43_li](https://user-images.githubusercontent.com/42662589/44561772-5619e900-a724-11e8-9895-86a86b96416b.jpg)
![desktop screenshot 2018 08 23 - 22 28 56 23_li](https://user-images.githubusercontent.com/42662589/44561774-587c4300-a724-11e8-98e5-2731f0cfabd1.jpg)

**Comment by raiyni** [comment]
https://github.com/runelite/runelite/issues/5080
