### ISSUE TITLE
Osbuddy Active Prices Displaying Twice

### ISSUE THREAD

**Issue by 000000653** [runelite/runelite#5098]
"Osb Actively Traded Price" Displayed twice, unable to reproduce, 

![2018-08-23_21-45-30](https://user-images.githubusercontent.com/40111569/44562603-ea358180-a71f-11e8-85ea-1554d3cb817c.png)

Using Windows 7
Runelite version 1.4.14 
Launcher version 1.6.0
Java version 8, Update 181

Logs: https://pastebin.com/6EPS5Pti

**Comment by EricWagnerJr** [comment]
I actually ran into an issue similar to this where it showed two but one of them was a previous item that I had just looked up. I was unable to reproduce, though.
