### ISSUE TITLE
Specific plugins not working after 08/23/18 Update

### ISSUE THREAD

**Issue by Godric777-OpenRSC** [runelite/runelite#5101]
Hi,

After yesterdays update my Cannon, Ground Items, and Screenshot plugins no longer work. I have tried uninstalling and reinstalling the software but no matter what I cannot use these plugins anymore. I seriously need help with this issue asap. I use Windows 10 on an ASUS ROG JZ750 computer with the GTX 880M Graphics Card.

**Comment by ItsSebas** [comment]
https://twitter.com/OldSchoolRS/status/1032652169017806848

**Comment by raiyni** [comment]
this should be fixed as of 2 hours ago
