### ISSUE TITLE
Lumbridge swamp put marker next to stash unit for emote clue

### ISSUE THREAD

**Issue by KingLehon** [runelite/runelite#5104]
Currently the plugin doesn't put markers near stash locations for emote clue items.

Ex.
Me doing emote near stash
![image](https://user-images.githubusercontent.com/29807845/44590778-f7875600-a789-11e8-821a-35bdf9b0f015.png)

Where the plugin puts a marker.
![image](https://user-images.githubusercontent.com/29807845/44590732-daeb1e00-a789-11e8-8772-7c47a1eeaba3.png)

**Comment by Nightfirecat** [comment]
The marker is near a stash unit. Is there more than one stash unit for that particular clue??

**Comment by KingLehon** [comment]
According to [this](http://oldschoolrunescape.wikia.com/wiki/STASH) there is only one stash unit in the lumbridge swamp caves.

**Comment by astaninger** [comment]
Ya I think there are two. The one that OP used is the more common one. It's close to the Lumbridge teleport. This makes it easier to get to by just going into the cellar. I think it makes sense to switch it.

**Comment by KingLehon** [comment]
One is an easy clue that is on ground level next to the zanaris shack.
The ONLY stash unit for that medium clue step is where I was.

**Comment by Nightfirecat** [comment]
That is not correct, there are apparently two stash units for this clue step. From the [Emote clues wiki page](https://oldschoolrunescape.wikia.com/wiki/Treasure_Trails/Guide/Emote_clues):

> Two STASH units are provided, one near each of the main entrances. Building one of them will automatically build the other one.

Proof:
![location #1](https://user-images.githubusercontent.com/2199511/45049722-ffd76f00-b06e-11e8-9535-8b3bf8b0bda7.gif)
![location #2](https://user-images.githubusercontent.com/2199511/45049726-01a13280-b06f-11e8-8489-54eb17964215.gif)

**Comment by deathbeam** [comment]
Soo looks like this is solved by original poster not having full info
