### ISSUE TITLE
Interface Styles plugin drawing logo's on wrong tabs

### ISSUE THREAD

**Issue by jordi2830** [runelite/runelite#5105]
The Interface Styles plugin is not working correctly. It draws some tab logo's on wrong tabs. 
This started after the game update on 08/24/18.

Both the 2005 and 2010 gameframe's are having issues.

![image](https://user-images.githubusercontent.com/4589528/44591621-82824380-a7be-11e8-9b12-93680e6f2012.png)

![image](https://user-images.githubusercontent.com/4589528/44591658-a04fa880-a7be-11e8-8715-5cb5899b136c.png)

**Comment by raiyni** [comment]
This is only a problem in resizable..

While you resize the client, it shows them.
Once you stop resizing, they disappear.

**Comment by ltvill** [comment]
@deathbeam, also, the options for shift-click, inventory tags and prayer re-ordering are on the wrong tiles.

![image](https://user-images.githubusercontent.com/40988464/44618579-6e534a80-a881-11e8-84bd-21b92997cfe8.png)

**Comment by deathbeam** [comment]
Oh interesting

**Comment by Adam-** [comment]
Fixed in 50b19b2cedd556a66288a74cad83e426941b4074
