### ISSUE TITLE
Request feature for adding seaweed to farming tab overview

### ISSUE THREAD

**Issue by collwyr** [runelite/runelite#5108]
Was wondering if someone could add the timer for the seaweed patches in the overview screen when you click on the farming tab, currently it has it for everything else except for the seaweed.

thanks!

**Comment by ItsSebas** [comment]
Check the special patches (mushroom) for seaweeds
![image](https://user-images.githubusercontent.com/34197030/44602363-b752c280-a7df-11e8-8ee0-5be962eb6da4.png)

**Comment by collwyr** [comment]
apologies, I should have been a bit more specific with pictures, im aware that the timer is shown if i click on the mushroom.

but on the overview (picture below) it shows a quick option to see what birdhouses/tree's/herb patches are ready instead of having to click on the tabs to see, was wondering if the same could be added for the seaweed seeing as that isn't on the list.

https://gyazo.com/bfa5f2c63828812a301e62031b0bd2a1
