### ISSUE TITLE
Farming Timer Widget Similar to OSB/Konduit

### ISSUE THREAD

**Issue by MatthewSH0** [runelite/runelite#511]
This is the only thing stopping me from using runelite. It keeps track of herbs/trees etc on the right side using a Widget. Possible addition of a notification when your plants are ready would be nice.

**Comment by deathbeam** [comment]
As the farming update is in OSRS already, this should be now a lot easier feature to add.

**Comment by kircherv** [comment]
is this coming some day?

**Comment by raiyni** [comment]
We have the timer panel that shows this information.
