### ISSUE TITLE
Including a Max Hit 

### ISSUE THREAD

**Issue by MutazHelal** [runelite/runelite#5111]
**Is your feature request related to a problem? Please describe.**
 I recently started using this extremely helpful client, one thing that I noticed is that the interface doesn't show you your max hit when you view equipment stats. 

**Describe the solution you'd like**
Code to calculate your bonuses as well as your combat levels to determine your maximum hit. Then the calculated number would be displayed when viewing the equipment stats. 

**Describe alternatives you've considered**
Including the max hit in the top left corner of the client, right under the health bar of the enemy would also be a great solution. 

**Additional context**
http://prntscr.com/kmltgx

**Comment by oplosthee** [comment]
@MagicfTail was/is working on a plugin that achieves this (https://github.com/runelite/runelite/pull/2841). I can't tell you when it'll be added to the client though.
