### ISSUE TITLE
Enchant Helper (New Plugin Request)

### ISSUE THREAD

**Issue by AttackOfTheMoons** [runelite/runelite#5113]
When enchanting rings on OSBuddy, there is a feature called Enchant helper. Basically it puts screen markers on the unenchanted rings automatically while enchanting rings. Is there a way to do a similar thing in a plugin?

![](https://i.gyazo.com/fdc85493c0a587977a4eccf6a5928a5c.png)

**Comment by Abextm** [comment]
Try the `Inventory Tags` plugin
