### ISSUE TITLE
so someone explain why runelite is hacking people???

### ISSUE THREAD

**Issue by revenanttax** [runelite/runelite#5115]
computer is clean and fresh no other ways of being hacked!
only way was through this 3rd party client ! 
so keep advertising whilst you clean peoples accounts?

**Comment by deathbeam** [comment]
You either downloaded phishing client from other site than **runelite.net** or clicked some phishing link and entered your user details. Either way, the official release is NOT hacking people.

**Comment by revenanttax** [comment]
certainly not thats what time telling you 1 day ive used the client and i used it from this website -.-

**Comment by revenanttax** [comment]
i used the url runelite.net and thats a certain fact , also full computer scan no malware found ...

**Comment by deathbeam** [comment]
Well the certain fact is that RuneLite is not hacking people too, I mean you can check it by yourself if you would really want to. It's open-source and If there was anything fishy someone would point it out long time ago already.

**Comment by revenanttax** [comment]
well explain why ive been hacked since 1 day of downloading the client then my friend , i understand open source and how it works. have a good understanding of this, and i know that this is where its came from , i know 2 other people ive spoken too now and it was runelite thats caused the same, so maybe its time you start looking at your open source code!

**Comment by deathbeam** [comment]
I know how the code looks and it does not contain any malicious code as we speak. I would maybe start questioning your security and maybe double check next time you click on something to prevent something like this happening in future.

I am locking this conversation as it is clearly leading nowhere as you are not listening.
