### ISSUE TITLE
RegenMeterPlugin is not taking into account regen bracelet and HP cape

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#5117]
Without that it malfunctions with these items equipped.

**Comment by ItsSebas** [comment]
Seems like the code is working like intended
Checked the regen plugin with regen bracelet & hitpoints cape  + prayer enabled/disabled and they both worked like it should

**Comment by deathbeam** [comment]
Alright cool

**Comment by WillThomas** [comment]
The plugin incorrectly handles Hitpoint capes. The HP cape has its own 'timer' which when complete will increment the players hp. This can be observed by equipping the HP cape very shortly after a natural regen tick and then after waiting a minute the players hp will increment twice in short succession. The attached video shows this.

[2023-02-15-19-00-46.webm](https://user-images.githubusercontent.com/40471636/219127929-4c524b11-9351-427d-9504-d499be77a401.webm)
