### ISSUE TITLE
Highlight attackable players in wilderness

### ISSUE THREAD

**Issue by Jay1175** [runelite/runelite#512]
**Top Request**

- Overlay player names for ALL players with an option to exclude people from your own clan-chat (very useful for clanwars fights)

**More advanced request**

- Exclude players outside your level range (only displays player names of people you can attack while in wilderness/PvP world)

**Comment by Mod-Archie** [comment]
Sure, one moment. Let me ask Custard if he can do this.

**Comment by Nightfirecat** [comment]
Given the reason for closing https://github.com/runelite/runelite/issues/7072#issuecomment-450448227, I think this issue can be closed as well?

**Comment by deathbeam** [comment]
Yes
