### ISSUE TITLE
Option to reposition Kourend favor

### ISSUE THREAD

**Issue by itsSimplex** [runelite/runelite#5128]
The kourend favour bars often overlap the XP globes when you get XP for more than 2 skills. Just wondering if it is possible to move it

**Comment by raiyni** [comment]
https://github.com/runelite/runelite/pull/5064

**Comment by deathbeam** [comment]
Well #5064 actually just adds possibility to mave the widgets layoutable but it is not adding new widgets to the list, so someone would need to also add the kourend favour widget id to it
