### ISSUE TITLE
Bank tag upgrade.

### ISSUE THREAD

**Issue by SirSuhdude** [runelite/runelite#5129]
Tagging items one at a time from the bank interface is time consuming and tedious. 

I propose being able to assign a tag, or multiple tags to gear set ups and inventory set ups once the player has all the items withdrawn and worn, essentially, gearing up for a task, and being able to assign a tag for every item they need at once. 

Alternatively, there could be a built in toggle-able community built list of common tags for tasks in the game, like herb farming, and slayer monsters.

No coding knowledge, understandable if this is not feasible

**Comment by trimbe** [comment]
I have a PR that makes mass adding tags a bit easier, not quite what you're proposing though - #4862

**Comment by Abextm** [comment]
Duplicate of #4426
