### ISSUE TITLE
System Clock

### ISSUE THREAD

**Issue by Dcat682** [runelite/runelite#5130]
**Is your feature request related to a problem? Please describe.**
Windows computers have an option to drop the taskbar until you hover over the bottom of the screen on the windows screen.  Doing so with a program like RuneLite open will not do anything.  In short to take advantage of the larger feeling of full-screen RuneLite some players lose access to a clock.

**Describe the solution you'd like**
Please create a toggleable plugin where the system clock is checked and is added to an overlay in-game which shows the computer's system time.

**Describe alternatives you've considered**
If an overlay wouldn't work a new section could be added to the Timers & Stopwatch plugin  where the time is listed above the timers or stopwatches on the sidebar

**Additional context**
An example of this can be seen here.
https://cdn.mmos.com/wp-content/gallery/mabinogi/Mabinogi-Title.jpg

The game clock in Mabinogi can show both it's in-game clock and system clock.  Since Runescape doesn't have a day-night cycle all I'd like is a System Clock on the side of the screen.

**Comment by deathbeam** [comment]
You can already show local time in the report button plugin settings
