### ISSUE TITLE
Ctlr&+/Ctlr&- to world hop to the next/last world

### ISSUE THREAD

**Issue by SirDylan** [runelite/runelite#5136]
World hopping can be super tedious, but it's a large part of some activities in this game.

Maybe we could add a hotkey so we could hop quickly to the next & last world?

Filter options including:
 * No F2p Worlds
 * No P2p Worlds
 * Avoid High Risk worlds
 * Avoid Pvp Worlds
 * Avoid DMM/Event worlds.

**Comment by deathbeam** [comment]
Ctrl + shift + larrow and rarrow does this already
