### ISSUE TITLE
Timestamps for NPC kills and Sort loot by NPC type / Time period

### ISSUE THREAD

**Issue by ozzymansam** [runelite/runelite#5140]
Would it be possible to implement Timestamps and further ways to sort the information that loot tracker keeps hold of? That way tracking exact values for loot / hour or a set timeframe could be more easier established. Or if you input a certain timeframe (i.e. from 17:00 to 18:00) and it will show you how much you made just within that time.

Or potentially to take it further, use the total values *combined* with the timestamps so that the loot tracker automatically evaluates the overall gp/hour of whatever task you're currently doing.

Also being able to search for specific NPC kills instead of viewing *all* kills at once, so that if you doing Dagganoth Kings for instance, you could just search "Dagganoth Prime" and it will show only the drops from Prime, whilst keeping the rest hidden.

**Comment by deathbeam** [comment]
We implemented grouping, rest of filtering should be implemented on website and not in client after we will have loot tracker persistence
