### ISSUE TITLE
Woodcutting plugin does not work on Ape Atoll when wielding a Karamjan monkey greegree

### ISSUE THREAD

**Issue by jbak920** [runelite/runelite#5143]
The "Logs cut" and "Logs/hr" counters work, but the "Woodcutting"/"NOT woodcutting" indicator always reads "NOT woodcutting" while wielding a Karamjan monkey greegree. I haven't tested it with other kinds of greegrees.

**Comment by deathbeam** [comment]
Here is monkey #547
