### ISSUE TITLE
Entity hider- hide players on ignore list

### ISSUE THREAD

**Issue by jnanfito** [runelite/runelite#5144]
Would be useful to have this as an option. My use case would be to hide bots I've already reported at air obelisk both so I don't bother reporting them again, and so I don't have to right-click through them to use the obelisk. Hiding all players would make me unable to see potential PKers. This feature would probably be useful in other places as well.

This suggestion was brought up before in #1978 but the developer who was working on it seems to have been inactive for a while.

**Comment by devLotto** [comment]
https://github.com/runelite/runelite/issues/3349

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features (actually I should close #1978 too)
