### ISSUE TITLE
Make the Raid Loot screenshotter also include Challenge Mode Raids.

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#5145]

**Comment by dey0** [comment]
I heard that the issue in implementing this was that no one had the IDs of the loot chest interface.

I went and found the widget IDs for the cm loot chest: 
![2019-02-13 00_30_29](https://user-images.githubusercontent.com/13173140/52735185-a31ca080-2f8c-11e9-96a2-12efc676092a.png)
See that 539.5[0] through 539.5[3] contain the loot items. I don't know if this is any different than in normal CoX.
