### ISSUE TITLE
Boss global killcount/-time rankings

### ISSUE THREAD

**Issue by bryandh** [runelite/runelite#5146]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem. It’s merely a new feature.

**Describe the solution you'd like**
I would like to be able to see a ranking/highscores system for amount of kills on a specific boss and personal best times for that boss.
I can already imagine it looking something like a list of bosses on which you can click, which navigates to a different window where you can click either a ‘Kill time’ or ‘Kill count’ button, which will then show all the kill times or counts of the people that have used this plugin (ordered by highest kill count and fastest kill time, of course).

**Describe alternatives you've considered**
I couldn’t think of any alternatives.
I searched through the Runelite repo issues but I couldn’t find any similar feature requests regarding this idea.

**Additional context**
I would love to discuss the possibilities for this.
I understand this requires storing of the killcount and killspeed data in a database through perhaps the Runelite API.
To capture this data, we could hook into the event when a boss dies and the kill message shows up in the chat.

I’m a programmer myself so I can definitely work on this as well. However, I just departed on a roadtrip (during which I conjured up this idea), so I can’t develop this idea just now.

I would like you guys’ opinions on this. Especially how we could organise the infrastructure of storing the kill data, if at all possible/allowed by the Runelite core team.

Looking forward to your responses.

**Comment by deathbeam** [comment]
It is simply not possible to make rankings systems for bosses that would be global as it can be spoofed, and in case every second matters its just unreal request.

**Comment by deathbeam** [comment]
Also it would not work with the bosses killed on other clients so the rankings would have like little to no value.

**Comment by bryandh** [comment]
It would give you a good estimate on how well you are performing compared to others. Of course it would only contain data from the people using Runelite.
The spoofing part would indeed be hard to prevent, unfortunately.

**Comment by deathbeam** [comment]
It is impossible to prevent the spoofing.

**Comment by Abextm** [comment]
The only way I could think of implementing this is to use it as aggregate data, eg: `You killed the thing in 0:59, (50th percentile)`, so that people have less of a reason to spoof.

**Comment by Adam-** [comment]
We probably won't ever do this since its not possible in a way that won't be abused by people who want their name ranked at the top. I have added a `!pb` chat command though in #7561 which at least lets you show your personal best time to a number of people.
