### ISSUE TITLE
Session Timer

### ISSUE THREAD

**Issue by Jmac191** [runelite/runelite#5149]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
It's not super important, I just find it slightly annoying when I'm hopping worlds and the Login timer resets. I just like to see how long I'm at revs or doing other things but the timer keeps resetting (since I technically log out of that world it's understandable)

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

Would y'all be able to add a "session" timer to the report button or at the top of the client beside the RuneLite logo (toggle on and off in case people don't want it there)? I know we have a Login Timer for when we login/out of the game but would it be possible to add one to keep counting up till we close our client? I also know there's a stopwatch/ timer but I'd rather not have to keep switching back and forth between that and the loot tab etc etc.

**Additional context**
N/A

**Comment by DannysPVM** [comment]
I'd reccomend checking out the new Stopwatches for such a thing. It should keep counting up for as long as the client is open (Independent of logging out/hopping worlds).

Here's a picture of what I'm talking about: 
![image](https://user-images.githubusercontent.com/39487676/44642378-86b28a80-a991-11e8-8786-921607942144.png)

**Comment by deathbeam** [comment]
You dont need to go back & forth, just look at that tab when you need to know (what is mostly never). I would say if we already have feature that can be used for this, use it and dont be lazy.

**Comment by Jmac191** [comment]
Was just a suggestion. I knew about the timers tab, I just thought it'd be good to have a sessions one.

**Comment by DannysPVM** [comment]
When speaking on Discord about this topic, the idea was brought up by @Abextm that we could potentially allow for any timer/stopwatch to be bound to the report button to solve the 'issue' mentioned above. Currently, the Report Button plugin only has an enum with the various timers/times, maybe they could be migrated into the stopwatches/timers plugin and make the stopwatches/timers be bindable to report button.
