### ISSUE TITLE
Runelite not going fullscreen on second monitor 

### ISSUE THREAD

**Issue by TBBRKCK** [runelite/runelite#5153]
When trying to use runelite on my second monitor it won't take up the full screen, it leaves areas on the left and right and bottom where you can see whatever is open behind it.
![ss 2018-08-27 at 09 29 44](https://user-images.githubusercontent.com/42734223/44649466-e03fa700-a9db-11e8-9d6a-48a4b8f65431.jpg)

**Comment by Karolcz125** [comment]
![deepin-screen-recorder_sun-awt-x11-xframepeer_20180827111452](https://user-images.githubusercontent.com/15970653/44651766-8beff380-a9ea-11e8-8291-fe3fd2d20bb3.gif)

Have you tried that?

**Comment by TBBRKCK** [comment]
Just tried it, didn't make a difference

**Comment by ShaunDreclin** [comment]
I've run into a similar issue, possibly the same one. When I try to maximize the client on my secondary monitor, it only goes as big as the resolution on my primary monitor. Custom chrome is disabled.

**Comment by raiyni** [comment]
well for one, you aren't logged in

**Comment by TBBRKCK** [comment]
I'm not logged in because it makes no difference if I'm logged in or not

**Comment by Karolcz125** [comment]
Just to make sure, have you tried what Ive shown on the gif while logged in?

**Comment by raiyni** [comment]
pretty sure they are talking about the actual window size, not the ingame size. That sounds like a windows explorer issue after changing resolution/monitor settings.

**Comment by TBBRKCK** [comment]
Yes I've tried it while logged in

**Comment by TBBRKCK** [comment]
Yes raiyni it's the window size. Both my monitors are identical and the exact same resolution/settings

**Comment by raiyni** [comment]
This usually happens if you change resolutions or plugin a new screen without logging out of windows.

**Comment by v0idp** [comment]
same Issue here, can confirm and reproduce.

**Comment by scapinAbout** [comment]
I found that setting my monitor to be the main display, instead of my laptop screen, in the "display settings" fixed the issue.

**Comment by sleibrock** [comment]
Using NixOS and can reproduce issue. I have two monitors, and RuneLite will only maximize it's window on the primary monitor and not my secondary.

**Comment by deathbeam** [comment]
Did you tried without custom window chrome?

**Comment by sleibrock** [comment]
@deathbeam that corrected it for me, never knew about the setting. Thank you!!

**Comment by Deph0** [comment]
Can confirm this issue, with or without custom chrome window. Only uses primary screen's resolution to maximize the window.

**Comment by v0idp** [comment]
chustom chrome windows didn't fix it either for me.

**Comment by Vigilantly** [comment]
I believe this may be the issue here as well: https://github.com/runelite/runelite/issues/3279

I can't get RuneLite to go full-screen on my second vertical monitor. It tries to go to a horizontal full-screen. It must be pulling my main monitor's resolution, rather than the resolution of my vertical monitor.

**Comment by graingert** [comment]
If I set my primary screen to be the largest screen then maximize works on both screens

**Comment by Adam-** [comment]
fixed in f7606c7acaf25331331e85d4d1bad7b8e2ff3e9c

**Comment by cnkeats** [comment]
I am still encountering this issue after updating to launcher v2.1.6.

A workaround that I have been using is to have RuneLite maximized (with this bug) on my third monitor, then using a hotkey to move it to my second monitor. After doing that, it will be maximized until I move the window again.

**Comment by Shares5** [comment]
this is still an issue

**Comment by itsozone** [comment]
I am also still encountering this issue, was fixed for almost 2 years, but now it's back.

**Comment by tannerbroberts** [comment]
Still busted. I'm using an M1 mac, and double clicking the window handle at the top doesn't maximize it. Yes, this IS a runelite issue. My other apps maximize to fit the second display's dimensions just fine.
