### ISSUE TITLE
Random Event Tracker

### ISSUE THREAD

**Issue by CaptainCerg** [runelite/runelite#5159]
I believe that a random event notification should be added to Runelite. For example, if someone is woodcutting and not exactly looking at their screen, a genie may pop up, but the player may miss it. In this case, the notifications can be toggled on for certain random events and toggled off for others, such as the sandwich lady. That way, the player will not miss a random event they have been waiting for in order to get outfits, exp, etc.

**Comment by ShaunDreclin** [comment]
Would need to make sure an event actually belongs to the player before notifying or it'll get annoying quick.

**Comment by deathbeam** [comment]
Duplicate

**Comment by ShaunDreclin** [comment]
#1634
