### ISSUE TITLE
Chompy Bird Notification

### ISSUE THREAD

**Issue by CaptainCerg** [runelite/runelite#5160]
Since the Western Provinces Diaries require the player to kill a certain amount of chompy birds, I believe that a notification setting should be added that has a pop up notification of when chompy birds appear. This would help the player realize that a chompy bird has spawned where they are not looking. You may also add a small notification in the order of the screen near the dropdown xp tab is that informs the player of how many chompies they have killed in total along with their chompy rank.

**Comment by ShaunDreclin** [comment]
This isn't really necessary if you're doing it properly, since you'll always either be killing birds or dropping toads. No time to look away and need notification to bring your attention back

**Comment by deathbeam** [comment]
You can just tag the NPC what would be more useful than notification because the chompies will be spawning really often
