### ISSUE TITLE
NPC indicator highlighting after NPC transforming

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#5161]
Currently if a tagged (from the name in settings) NPC spawns it will be highlighted. If it then proceeds to transform into another NPC which is _not_ highlighted, it will stay tagged because of its initial spawn.

This is mainly an issue in the Theatre of Blood's Nylocas room.

Expected behavior: the NPC would no longer be highligted after transforming into another NPC.

**Comment by Nightfirecat** [comment]
Do you know of any more accessible monsters which have this issue as well? I'm looking at rebasing the PR but would like to test this to make sure it actually works once I do.

**Comment by Kamielvf** [comment]
I think the werewolves in canifis might?

**Comment by Hydrox6** [comment]
Rock, Sand, Swamp, and Ammonite Crabs do this.
