### ISSUE TITLE
Add brewing timers to time tracking plugin

### ISSUE THREAD

**Issue by sirlaige** [runelite/runelite#5164]
In the Time tracking tabs there are some great timers/trackers such as birdhouses and farming plants.  I would like to add an additional tracker for brewing.

In both Port phastasmus and Keldrem there are brewery stations and they take a great deal of time to brew stuff.  I personally brew chef's delight.  It take many hours (a few days) to get the results of brewing.  The two breweries do not brew at the same speed as each-other.  There is also a chance of getting bad ale which is a failure to brew.  

I imagine the tracker would be just like the many others, showing estimated time until done and then an icon of the item being brewed at the station just like the icon that shows it shows what plant is in the patch.  

When done brewing it would be nice if the icon would change to show the product.  Like Chef's delight icon, Chef's delight(m), or bad ale(failed).  But I know that the other trackers' icon won't change based on situation, so I understand if you left that out.  Example: a dead herb in herb patch will not change its' icon to show a dead one but rather keep the herb type and say dead with a red line.

This tracker would be helpful to me, would this be helpful to others too?

**Comment by trimbe** [comment]
Duplicate #2648
