### ISSUE TITLE
Sidebar Issue

### ISSUE THREAD

**Issue by annexoxoxo** [runelite/runelite#5171]
I just recently started using RuneLite and I've noticed an issue with the sidebar. I searched other threads but haven't found this one yet. Below I have attached a gif of the issue. The only thing that solves it is restarting the client. 

https://gyazo.com/3a83bca1ab7a63f8027830fb6cb6de5d

**Comment by Abextm** [comment]
Graphical artifacts? Try disabling hardware acceleration: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by annexoxoxo** [comment]
Hi I have a Mac, is there a different guide for this?

**Comment by FusionLord** [comment]
Check out method 3.
