### ISSUE TITLE
Game time in title bar

### ISSUE THREAD

**Issue by sirlaige** [runelite/runelite#5177]
It is nice how the report button can show in-game-time or logged-in-time.  I find both time useful and would like to have both times displayed.  So it would be nice to be able to have a time displayed in the title bar, and then I could have the other time displayed on the report button.  

For me I would have logged-in-time on the title bar and the in-game-time on the report button.

**Comment by deathbeam** [comment]
Displaying timestamp in titlebar is definitely not happening as that is really bad idea (updating title bar every second sounds very dumb).
