### ISSUE TITLE
Skyboxes

### ISSUE THREAD

**Issue by majorvegas** [runelite/runelite#5181]
Would it be possible to add a toggle that allows a skybox? Not asking for anything crazy, a simple shade of light blue would work for me.

I think you could probably just add a polygon/texture behind the rendering, I'm not super sure how it works. 

While I don't care that deeply how the skybox changes based on context, I think it would be possible to add night modes, or cave modes if this functionality was added.

**Comment by deathbeam** [comment]
Duplicate of #3941
