### ISSUE TITLE
Agility plugin- colour overlay for obsticles beyond your level

### ISSUE THREAD

**Issue by sirlaige** [runelite/runelite#5183]
Please add in an additional colour overlay.  I love how all the obstacles, shortcuts, and traps light up with the Agility plugin.  I would like this new suggested overlay (purple, blue, ?) to show that the short cut is too advanced for your skill level.  

I think this would be rather useful to have ability to identify shortcuts that are too advanced for you.

**Comment by deathbeam** [comment]
Duplicate
