### ISSUE TITLE
Ability to use Esc key to close dialogues like GE and Bank

### ISSUE THREAD

**Issue by bendol-i3** [runelite/runelite#5184]
**Describe the solution you'd like**
Ability to use the `Esc` keypress to close dialogues like the bank and the GE.

**Additional context**
I would implement this over the weekend, but I'm not familiar with creating scripts for invoking a close request.

**Comment by Alexsuperfly** [comment]
that exists in the game already

**Comment by bendol-i3** [comment]
It does? Doesn't seem to be working for me, do I need to configure it somewhere?
