### ISSUE TITLE
Multiple coloured ground markers

### ISSUE THREAD

**Issue by lewartv2** [runelite/runelite#5187]
Would be great if we could add multiple ground markers with different colours. For example right clicking with shift could give the option to place a yellow ground marker while right click with alt could give the option to place a blue ground marker.

Colours and hotkeys for placing the separate markers would need to be user options but by default only one marker and colour is enabled, being the stand right + shift click.

This would be helpful in boss areas or specifically the inferno where there is a lot of different points of interests and safespots, see here https://imgur.com/a/R98FlBY, where you could colour code your markers accordingly.

Could do this for different activities, entirely up to the user.

**Comment by deathbeam** [comment]
Duplicate

**Comment by ShaunDreclin** [comment]
#3395
