### ISSUE TITLE
Farm Timer Broken.

### ISSUE THREAD

**Issue by fermonos** [runelite/runelite#5190]
Farm timers seem to be broken. If I plant a herb at 5:03pm for example and it takes 80m to be able to harvest, it should be done at 6:23 and will be 80m on the timer, but for some reason runelite rounds up to the nearest 10 minute.

so example I plant at 5:03, it will say it's done at 6:10pm and will only take 67m, meaning you'll arrive 13 minutes early. Even sometimes some of the patches can even be off by 30m. - This also happens for all types of farming products example trees, bushes, flowers, not just herbs.

I suggest either fixing the timers so when you plant a herb it will count down from 80m or have it so the user can make a customisable timer like what you can do right now but make it automatically so when the client determines a ranarr seed has been planted it will count down from what the custom time has been put in the settings by the user.

Thank you so much for taking your time to read, I've attached a link [https://i.imgur.com/u4C2ipP.png](url) to show the 'bug' in question. The herbs in the picture were all planted from within 10s-120s of each other, but as you can see it says they'll only take a total of 67m (13 minutes early), while it should be 78m-80m. One is even off by 33m.

I sincerely hope this is fixed, it can be really annoying because when you show up to a herb in it's last cycle of growing, if you are near by while it's supposed to finish it's cycle and be ready to harvest you can stop it and make the whole of the last cycle to repeat. For herbs, it's only around 10 minutes or so but it can go into hours for trees, and almost even a day for the hardwood tree if you turn up early, so yeah. It can become quite annoying.

**Comment by deathbeam** [comment]
Just keep it in #2491 I guess
