### ISSUE TITLE
Ground Items Not Showing Exchange Price

### ISSUE THREAD

**Issue by 22pickle2** [runelite/runelite#5191]
My ground items is not showing the exchange price. Even though it is set to show both the High Alch and Exchange Price.

**Comment by deathbeam** [comment]
Restart your client, sometimes on startup loading prices fails on timeout

**Comment by 22pickle2** [comment]
I restarted client and it still is not working. 
![2](https://user-images.githubusercontent.com/42656490/44808597-42420d00-ab92-11e8-8377-4b47427570d7.PNG)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client maybe you cannot access API then. does the !price command work?

**Comment by 22pickle2** [comment]
No. The !price command does not work

**Comment by deathbeam** [comment]
Thought so. Check the troubleshooting guide then

**Comment by 22pickle2** [comment]
How do i update my certs if im on windows? I can see the commands for Linux.
