### ISSUE TITLE
Item charges for expeditious and slaughter bracelets

### ISSUE THREAD

**Issue by Klundsi51** [runelite/runelite#5192]
Under the item charges setting on runelite, can we have a option for the silver bracelets - Expeditious bracelet and bracelet of slaughter?

**Comment by deathbeam** [comment]
We should already have expeditious bracelets in slayer plugin, I think

**Comment by Klundsi51** [comment]
There kind of is. But i meant some kind of sound when it breaks, like when youre account is idle it plays a windows sound

**Comment by deathbeam** [comment]
you can already achieve that with chat notifer, just add the message to the list

**Comment by Klundsi51** [comment]
Alright ill try that. Thanks for the quick reply 👍
