### ISSUE TITLE
Ability to customize the position of overlay elements

### ISSUE THREAD

**Issue by johnkorzhuk** [runelite/runelite#5196]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to customize the position of overlay elements. Similarly to Kondiut where you can right click the element and select "move" or a toggle in the settings similar to the `Reorder Prayers` setting.

**Additional context**
https://gyazo.com/24fab479ff4058ede05c295164df9868

**Comment by Alexsuperfly** [comment]
hold alt then you can drag them around

**Comment by Nightfirecat** [comment]
Do you mean this? https://github.com/runelite/runelite/wiki/General-Features#moving-overlays
