### ISSUE TITLE
Player equipment examine

### ISSUE THREAD

**Issue by dupperT** [runelite/runelite#5200]
I'm always frustrated when someone is wearing gear that I don't know the name of. OSRS has come a long way since 2007 and I feel this would help new and even old players. 

I Think  a good solution would be the something similar the the RS3 [player examine](https://vignette.wikia.nocookie.net/runescape2/images/e/e4/Player_examine_%28privacy%29.png/revision/latest?cb=20171008074625) .. 

Thanks for reading.

**Comment by Nightfirecat** [comment]
An external plugin has been added to the plugin hub in runelite/plugin-hub#105 which provides this functionality.
