### ISSUE TITLE
Exp Globes

### ISSUE THREAD

**Issue by Odell74** [runelite/runelite#5201]
Once you reach 99 in a skill, such as hitpoints, it no longer becomes relevant to have the xp globe pop up on screen, as there are no levels you're progressing towards. This just ends up clogging up the screenspace, and especially on fixed resolution, there isn't a lot of screenspace to go around.

A solution to this problem is to enable or disable xp globes for specific skills that the user can select. This is a fairly simple fix and shouldn't take much work, but would be greatly appreciated.

**Comment by deathbeam** [comment]
Duplicate
