### ISSUE TITLE
[Banking] Shift click on stack to deposit all

### ISSUE THREAD

**Issue by Psyda** [runelite/runelite#5205]
**Describe the solution you'd like**
While holding shift and clicking a stack of items in the inventory it would deposit all off the stack into the bank. (swapping deposit 1 with deposit all)

This would help when managing lots of items quicker.

An example use scenario would be farming  medium clues where you have to take small amounts of eclectic implings out and it is very frustrating to deposit stacks of items repeatedly and its not worth using the deposit all button since you'd deposit teleports/tools.

**Comment by ShaunDreclin** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
