### ISSUE TITLE
Put the map under this big game screen box and now i cant undo it?

### ISSUE THREAD

**Issue by daviie** [runelite/runelite#5208]
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/42838432/44852490-a5e83b00-ac63-11e8-973a-ba30603dcfdc.gif)

**Comment by ItsSebas** [comment]
Disable the total xp counter by clicking on xp (above hp) and then drag the minimap (will be fixed after update)

**Comment by daviie** [comment]
thank you sebas
