### ISSUE TITLE
"Enable" option on timer plugin does nothing

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#521]
The "enable" option does nothing. Timers still appear with this option disabled.
When disabling the timers plugin, all active timers are still displayed.
When disabling a specific timer and re-enabling it, the timer doesn't re-appear until you drink another dose.

Also timers are a little off but I'm not sure what causes it. Possibly the overload is 5 minutes from when the self-damaging effect is over, so it's actually a 5:05~ duration after the chat message is displayed.

**Comment by deathbeam** [comment]
PR #351 solves the first part of the issue. And I think the second part should be separate issue.

**Comment by Adam-** [comment]
First part of this is fixed in 77c11c8cfbed78e40d32896da729fc1699fc672e.

"When disabling a specific timer and re-enabling it, the timer doesn't re-appear until you drink another dose." won't be fixed.

The second part of this is tracked in #439
