### ISSUE TITLE
Diary progress plugin not showing karamja elite completed

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#522]
Since the fix for #484, it is now working as intended for the easy to hard diaries, but it broke the elite.

![image](https://user-images.githubusercontent.com/35824069/35765230-1c35650a-08c0-11e8-81b6-8c2e33e7585e.png)

**Comment by deathbeam** [comment]
Diary plugin was removed in favour of OSRS new diary interface, closing as wontfix.
