### ISSUE TITLE
Discord: Runelite description shows NMZ instead of KBD

### ISSUE THREAD

**Issue by MatthiasDh** [runelite/runelite#5221]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When you are on a slayertask and are at KBD the info that discord provides you about the player playing runelite is wrong. It says the player is in nightmarezone training slayer

**To Reproduce**
(Get slayer task for black dragons)
Go to KBD
Check discord information about runelite player.

**Expected behavior**
Shows Killing KBD and training slayer

**Environment (please complete the following information):**
 - Windows 7
- RuneLite 1.4.15

**Comment by Nightfirecat** [comment]
This was fixed some time ago in #11052. Now your location is hidden while fighting KBD, like it is when in the wilderness.
