### ISSUE TITLE
Rare tree indicators on the map should show what type of tree is there in the tooltip

### ISSUE THREAD

**Issue by Tyler81198** [runelite/runelite#5223]
This one is pretty self-explanatory. I would like to be able to hover over the rare tree indicators to see what kind of tree is in that location( I.E. "Rare Trees - Yew"). 
Pardon me if this is already a feature as I am relatively new to Runelite, but I couldn't find this option in the menu.

**Comment by ShaunDreclin** [comment]
Do we have any way of automatically generating this, or would somebody have to go in and do it by hand? If it's the latter I don't imagine anyone will be volunteering for the job

**Comment by deathbeam** [comment]
Yeah, i dont think this is easily doable, it is like giant amount of data we would need to gather manually

**Comment by ShaunDreclin** [comment]
If somebody does actually feel like doing it though, it'd be neat to also make the icon change depending on the type of tree
