### ISSUE TITLE
Include 'to:' and 'from:' when recolouring split private messages.

### ISSUE THREAD

**Issue by montrers** [runelite/runelite#5230]
**Is your feature request related to a problem? Please describe.**
Currently the 'to:' and 'from:' part of split private messages cannot be recoloured, this looks out of place when the rest of the message is another colour. 

**Describe the solution you'd like**
There is two possible solutions: 
1. Add another option in the chat recolour plugin to recolour the 'to:' and 'from:'.
2. Include the 'to:' and 'from:' when recolouring split private chat using the chat recolour plugin.

**Additional context**
Osbuddy:
![screen shot 2018-08-31 at 2 10 56 pm](https://user-images.githubusercontent.com/42737438/44889052-56b80e00-ad28-11e8-93e9-8c7cff2b6139.png)
Runelite:
![screen shot 2018-08-31 at 2 12 11 pm](https://user-images.githubusercontent.com/42737438/44889053-56b80e00-ad28-11e8-9e48-245531281dad.png)

Thank you :)

**Comment by ShaunDreclin** [comment]
I'm in favour of option 1.

I actually prefer having the name and message a different colour, makes them stand out better.
