### ISSUE TITLE
Customizable in-game UI Elements

### ISSUE THREAD

**Issue by Gawz** [runelite/runelite#5233]
I'm not sure if this would interfere with the ToS of the game?

Much like the ability we already have to move the minimap around, it would be good to also be able to move other UI elements of the game.
More specifically the chat and inventory as well as being able to dynamically resize them to our liking.

At the moment i'm playing in stretched fixed mode as i prefer a larger UI due to playing on a large monitor.
Being able to play resizeable mode but upscaling UI elements like the in game chat, inventory and minimap would be a nice and preferable update to stretched fixed mode.

**Comment by deathbeam** [comment]
We already have issue for scalable UI open, and for moving inventory and chat, we will not do that as that could be abused.
