### ISSUE TITLE
Can't put screen marker too far right on the screen

### ISSUE THREAD

**Issue by lilbuff** [runelite/runelite#5236]
When you part the marker too far right on the screen then open up the sidebar to confirm location it will push the marker over.
![image](https://user-images.githubusercontent.com/42870728/44918781-d5518300-ad09-11e8-9bac-42566d72ea2f.png)
![image](https://user-images.githubusercontent.com/42870728/44918795-dd112780-ad09-11e8-90a7-4ff80d758af8.png)
![image](https://user-images.githubusercontent.com/42870728/44918799-e00c1800-ad09-11e8-8e36-ea69ddc22630.png)
![image](https://user-images.githubusercontent.com/42870728/44918804-e3070880-ad09-11e8-8aa8-76f66094537d.png)

**Comment by deathbeam** [comment]
We have issue open for making positions of screen markers relative
