### ISSUE TITLE
zeah rune essence idle notifier 

### ISSUE THREAD

**Issue by johnsonn14** [runelite/runelite#5241]
Before the most recent update (1.4.15), you received idle notifications when the rune essence depleted at the arceuus essence mine. However, after the idle notifier improvement update, ie 

"The idle notifier plugin has been significantly improved, now it should not throw false warnings while in combat or when doing activity that is using same animations as some of the animations that display idle warning"

You no longer get a notification when you deplete the essence. Not sure if this can be easily fixed, but it would be cool if it was.

**Comment by deathbeam** [comment]
Will be fixed next update, also duplicate
