### ISSUE TITLE
Recolour Official Experience Drops

### ISSUE THREAD

**Issue by montrers** [runelite/runelite#5242]
**Is your feature request related to a problem? Please describe.**
The official experience drop colour options are both ugly and do not match the overall exp counter. 
Osbuddy gives the option to recolour both the drops and the overall counter, I would love to see this in RuneLite!

**Describe the solution you'd like**
Similar to the chat recolour plugin, a option to recolour:
The official experience drops
The official experience counter

**Additional context**
Osbuddy:
![screen shot 2018-07-18 at 8 59 52 pm](https://user-images.githubusercontent.com/42737438/44934813-5f5d2280-adc2-11e8-9868-f90d377cc9f8.png)
Official:
![screen shot 2018-07-18 at 9 00 25 pm](https://user-images.githubusercontent.com/42737438/44934814-5ff5b900-adc2-11e8-8247-b3bea0357365.png)

**Comment by montrers** [comment]
I see there is already the option to change the colours depending on combat prayers, so the foundation is already there!

**Comment by montrers** [comment]
Thank you!

**Comment by Adam-** [comment]
added in #13729
