### ISSUE TITLE
Platform for plugins

### ISSUE THREAD

**Issue by killje** [runelite/runelite#5243]
When I tried to create a plugin for RuneLite a few days ago i was surprised that plugins where created in "RuneLite Client".

After a small discussion on the discord I found that the reason was that Jagex does not like there be plugins that could be easily be distributed, and there is definitely something to be said about preventing malicious content to be created.

After some more discussion it seems that there might be some benefits and drawbacks to this idea. In this issue I would like to explore this idea some more and would like to create a discussion for this idea.

Some of the things already discussed i have typed out below. The general consensus in the discord was very divided at the end where people both singed from it being a good idea and a bad one, while not much in between.

There is definitely a lot of hurdles to overcome to implement this. But this could help make RuneLite be more maintainable and to grow bigger.

The biggest advantages of doing it this way is so that more niche plugins could be made. The plugins could be more easily be vetted as only malicious content need to be found. A user could also more easily make the client more to their liking by using a different plugin that does the same thing.

Current idea:
* The current idea is to create a platform (be it a repo, branch or something completely different) where people can submit plugins to. These plugins would be vetted and be downloadable inside the client.
* To insure that only vetted plugins are able to run in the client they need to be verified. Two ways are possible. The first way is to have a certificate with the plugin that the client would verify. The second way is for the client to run the plugin hash against a database of verified plugins.
* Only in developer mode you would be able to create a plugin that would be run without verification (maybe you need to apply for developer verification and/or a maximum of X unverified plugins)

Current opposition to the idea:
* People will blame RuneLite for not working while this is a problem from a specific plugin
* This might be something to big for crowdsource project to implement
* After each update plugins would break and people would complain in discord
* RuneLite would need to manage building and deploying all of them (?)

What is currently written here is not going to be the final version and there is a very big chance that this is not going to go through, but would like to ask for a exploration for this idea and maybe we get a something out of this that is useful for the project.

**Comment by killje** [comment]
Also something discussed in the discord but not in here is to still have a core set of plugins that would be included in the client. This might solve a few of the problems in breaking, deploying and maintaining as there could just be said that it is not the responsibility of RuneLite to maintain plugins outside of the core plugins.

**Comment by ShaunDreclin** [comment]
This sounds interesting but it might be pushing it with Jagex, since they specifically told us to remove support for external plugins. If we did do it we'd still need to curate any submitted plugins to not allow overpowered ones, and at that point why not just include them in the client?

**Comment by killje** [comment]
We need to curate less. When we curate a plugin now it needs to adhere to all coding styles we have. With this we only need to look for malicious code and plugins that Jagex would not want.

From the conversation in discord, it was not so that Jagex specifically told us to remove external plugin support, but that certain plugins should not be able to run. To do that at the time it was decided to not have external plugins, but this discussion is here to look at this again and see if there are opportunities to have external plugins while still pleasing Jagax.

For me one of the main reasons to have external plugins is to be able to build faster and I hope to have when this is implemented a way to update a plugin without even closing the client

**Comment by Reasel** [comment]
I know this hasn't been touched in ~5 months but I I really like the idea of this. It would require a complete shift in the general flow of feature development by the major devs of this project.

A good system might be that the 'Core' plugins are all vetted and tested as usual, but there is a list of 'Non-Core' plugins that simply got checked for malicious code as well as not containing rejected features.

If some plugin is well received it might need an official rework and review and then it could be moved into the 'Core' plugins. Would allow greater feedback on plugins beyond gifs and picture in a PR or the rare person who pulled your code to test it themselves.

**Comment by dekvall** [comment]
The [Plugin Hub](https://github.com/runelite/plugin-hub) was added in #10446.
