### ISSUE TITLE
Integer Scaling feature on ultra wide monitor

### ISSUE THREAD

**Issue by osrsexo** [runelite/runelite#5260]
Bug Discription:
When you go full screen on a ultra wide monitor (fixed mode/static size) and Integer scaling is enabled your screen starts resizing every 1,5 seconds.

To recreate:
-go full screen static size on a ultra wide monitor
-have "Integer scaling" enabled in the "stretched fixed mode" setting.

Problem:
https://gyazo.com/8293c38e6559fa303150e5735f6310f0

"Integer scaling" disabled:
https://gyazo.com/a0ce1e828e8b0d4b55cbf40c71d90293

**Comment by osrsexo** [comment]
I've noticed that 1080p widescreens don't have this issue, I think it's regarding 1440p and up.
I suspect the integer is able to scale up to 1080p but not beyond, causing it to crash.

**Comment by robmonte** [comment]
@osrsexo Is this no longer an issue? Why did you close it?
