### ISSUE TITLE
Menu entry swapper - Support for bank withdraw/deposit options

### ISSUE THREAD

**Issue by Antimated** [runelite/runelite#5261]
**Problem**
Because you can't use things like autohotkeys anymore it might be slightly more annoying to train things like herblore, fletching, ... every skill that is related to banking extensively.

**Sollution**
Make it so that you can choose whatever withdraw/deposit option that you like. For herblore and fletching for example it would be nice if you could have it so that the *Withdraw-14* option (achieved by selecting Withdraw-X) is the default left click option.
Would be a nice update to the existing menu entry swapper as more and more people are getting into osrs mobile (where you DO have the option to pick 14 items at once out of the bank)

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
