### ISSUE TITLE
Being able to zoom camera whilst mouse is over interface (inventory etc.) 

### ISSUE THREAD

**Issue by SaintJuniper** [runelite/runelite#5264]
**Describe the solution you'd like**
Being able to zoom (via scroll wheel) whilst mouse is hovering over inventory/prayer book etc. 

**Additional context**
Currently not possible (was a feature in Konduit), very useful for many situations such as PvP and PvM. Currently have to move mouse manually off the interface to zoom and move mouse back after

**Comment by deathbeam** [comment]
Duplicate of #2316
