### ISSUE TITLE
NPC South-Western square shower 

### ISSUE THREAD

**Issue by SaintJuniper** [runelite/runelite#5265]
**Describe the solution you'd like**
An indicator (like tile tagging) that shows the most southern western square of NPCs that are larger than 1x1. 

**Additional context**
In OSRS the most southern western square of a large NPC determines where splash damage is applied (chins, barraging etc.). For example, to kill Kree'ara with chinchompas, the southern-western square of the minion must be adjacent to the southern-western square of Kree'ara for the splash damage to apply correctly. 

This is also important for determining how monsters are 'blocked' by scenery. For example, in the Inferno, to safespot a melee creature you must line their southern-western square up with your character.

By adding this in, it will make such activities more convenient

**Comment by deathbeam** [comment]
You can already just tag the monster, use tile highlighting to see whole tile and then just use compass
