### ISSUE TITLE
Graphical UI Problem

### ISSUE THREAD

**Issue by u47700** [runelite/runelite#5270]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I get lines from every graphical UI I have.

**To Reproduce**

**Expected behavior**
No lines

**Screenshots**
https://s22.postimg.cc/7cgr7eqfl/Line_Glitch.png

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
I've tried " -mode=OFF" Fix.

**Comment by Abextm** [comment]
Duplicate #4922
