### ISSUE TITLE
Recorder/Replay system?

### ISSUE THREAD

**Issue by SirDylan** [runelite/runelite#5271]
How plausible would it be to get a replay system similar to how Nvidia's Instant Replay works?

Pressing a hotkey would save the last 1-10 minutes of gameplay.

Temporary files cleaned out regularly. 

Seems like a massive project, but would make this client great.

**Comment by deathbeam** [comment]
I closed similar issues in past, implementing our own video recorder is simply unreal, just use existing software that does it better.

**Comment by Unmoon** [comment]
You can use OBS for this.
