### ISSUE TITLE
separate run energy counter

### ISSUE THREAD

**Issue by zulohh** [runelite/runelite#5280]
**Is your feature request related to a problem? Please describe.**
can't keep track of run energy when hiding orbs or map 

**Describe the solution you'd like**
separate run energy counter

**Describe alternatives you've considered**

**Additional context**
here's an example
 [![Screenshot from Gyazo](https://gyazo.com/7e1c4c859f25676fb16461475cb5d5cb/raw)](https://gyazo.com/7e1c4c859f25676fb16461475cb5d5cb)

**Comment by deathbeam** [comment]
Just dont hide the orbs/map then, it is same principe as with this request. You can already move the map around however you please and if you want to see the in-game data there are orbs.

This is very niche request and I dont think it will be implemented so I will just close it now.

**Comment by chance0909** [comment]
This is a helpful feature for the best woodcutting exp in game (1.5t teaks). Despite that it's probably still a niche request; however, it would serve a purpose and have a use within the efficient meta of the game. For that reason alone I think it should be considered.

**Comment by deathbeam** [comment]
You can just move the minimap and see the run energy there

**Comment by chance0909** [comment]
The method requires you to click all over the screen, having the minimap anywhere on screen will occasionally obstruct where you need to click. An alternate display specifically for run energy will fix this.
