### ISSUE TITLE
Option to disable time elapsed on discord activity

### ISSUE THREAD

**Issue by Majst** [runelite/runelite#5282]
On the discord configuration would it be possible to put a Show Time Elapsed toggle, so people clicking on your discord profile would not be able to see how long you have been playing, only what activities you are currently doing.

**Comment by deathbeam** [comment]
Why?

**Comment by ShaunDreclin** [comment]
Privacy, I would imagine.

**Comment by deathbeam** [comment]
Yeah well you could just disable entire plugin if you care about that :d
