### ISSUE TITLE
Screen Marker Issues

### ISSUE THREAD

**Issue by Runezscazmatar** [runelite/runelite#5291]
**Describe the bug**
RuneLite Screen Markers seem to distort and warp after a minute or so of being logged on. This seems to happen randomly and can also seemingly randomly fix itself. The issue can last anywhere from a few minutes to hours. Occasionally restarting the client seems to fix it but most of the time it does not. Making the screen markers invisible and visible again seems to have no effect. I have also uninstalled and reinstalled the client and the issue seems to persist.

Simply starting the client seems to have this effect. The issue appears most of the time a few moments after logging in.

**Expected behavior**
There should be small square boxes like so:
![screenmarkers](https://user-images.githubusercontent.com/42963657/45024304-9df81480-b030-11e8-95d1-5ea830b3dd91.JPG)
However, randomly the screen markers will become completely distorted and jump all over the screen like so:
![screenmarkerlines](https://user-images.githubusercontent.com/42963657/45024161-507ba780-b030-11e8-87da-28040b50f4d4.JPG)

**Environment (please complete the following information):**
Windows 10

**Comment by Unmoon** [comment]
Please try this: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Abextm** [comment]
Duplicate #4922

**Comment by Runezscazmatar** [comment]
I have already tried this. Hardware Acceleration is already disabled. The issue still persists when running Runelite as a .bat file and when using the shortcut where the mode=OFF.
![ha](https://user-images.githubusercontent.com/42963657/45025196-c254f080-b032-11e8-84cd-0ff430cd9238.JPG)
