### ISSUE TITLE
Chat commands should support different ways to type commands

### ISSUE THREAD

**Issue by Unmoon** [runelite/runelite#5294]
Currently chat commands only work with specific strings. For example, level command only supports `!lvl`, but not `!level`.

`total` -> `total, overall`
`price` -> `price, ge, value(?)`
`lvl` -> `lvl, level`
`cmb` -> `combat, cmb, cb`

**Comment by Unmoon** [comment]
As a side note, if anyone looks in to chat commands, the short boss names should probably be changed to not be a big pile of switch.

**Comment by astaninger** [comment]
what would you want instead of the switches?

**Comment by Unmoon** [comment]
Probably something similar to `SkillAbbreviations` (also part of chat commands plugin).

**Comment by deathbeam** [comment]
I think we decide to not add abbrevs because other clients will not work with those (e.g OSB)
