### ISSUE TITLE
Weird sound issue.

### ISSUE THREAD

**Issue by derpyderpaderp** [runelite/runelite#5302]
Having a weird sound loop when I have sound effects on only in runelite. I will have a video and logs attached to help find the issue. Any help would be appreciated.

Video of weird sound loop: https://www.youtube.com/watch?v=C-J0-LV9FNg

Logs are attached
[application.log](https://github.com/runelite/runelite/files/2349934/application.log)
[application_2018-09-02.0.log](https://github.com/runelite/runelite/files/2349935/application_2018-09-02.0.log)
[application_2018-09-03.0.log](https://github.com/runelite/runelite/files/2349936/application_2018-09-03.0.log)
[launcher.log](https://github.com/runelite/runelite/files/2349937/launcher.log)
[launcher_2018-09-02.0.log](https://github.com/runelite/runelite/files/2349938/launcher_2018-09-02.0.log)
[launcher_2018-09-03.0.log](https://github.com/runelite/runelite/files/2349939/launcher_2018-09-03.0.log)

**Comment by Abextm** [comment]
Turn off the metronome
