### ISSUE TITLE
Runelite Lagging on game PC

### ISSUE THREAD

**Issue by anthonynl** [runelite/runelite#5314]
Hello guys ,

Runelite is lagging somehow.

i5 8600k coffee lake processor
GTX 1060 6GB Graphic card.
Game motherboard etc etc....

Can anyone help me fix this problem?

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client past that guide we cannot help you more with this
