### ISSUE TITLE
Agility marker not present at GWD crossbow shortcut

### ISSUE THREAD

**Issue by royoffire** [runelite/runelite#5318]
The green agility box is not present on the agility shortcut for the crossbow clue near GWD. It's not a major bug, but for consistency sake it probably should be fixed.

https://gyazo.com/015359dee527c5347b6b83db8b148870

**Comment by NathenSample** [comment]
World map location would be useful as I'm sure there are developers out there, myself included, who have 0 idea where that location specifically is, so would have to run around like headless chickens to locate it.

**Comment by royoffire** [comment]
My apologies. It's right here, north-east of the god wars dungeon (not the shortcut going into the Wilderness).

https://gyazo.com/c37a101aa573c128f3041251913e9c57
