### ISSUE TITLE
Will not run: Error

### ISSUE THREAD

**Issue by trounce1** [runelite/runelite#5326]
FIXED

**Comment by Alexsuperfly** [comment]
the error literally says re-run maven. do that

**Comment by trounce1** [comment]
Cheers.

**Comment by ShaunDreclin** [comment]
Welcome to the project! For future reference, don't remove the body of an issue like that. If you need to, use `~~strikethrough~~` to cross things out.

Also, the issue tracker is for bug reports and feature requests. If you need help go to the discord server and use #support for general questions and #development for dev questions
