### ISSUE TITLE
Exp Globes don't reset

### ISSUE THREAD

**Issue by David21212** [runelite/runelite#5331]
**Describe the bug**
The reset option, as well as the "center orbs" options don't seem to do anything. If I manually put a single exp globe back to center screen, it'll right align any other globes that come up next to it.

**To Reproduce**
I discovered you could move the orbs around, so did so out of curiosity. However it messed up the center alignment. I went to reset it back to default but nothing changed. 

Move the globes around, then use the reset options.

**Expected behavior**
I expected the orbs to reset to their default location after hitting the reset button. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.4.15
 - Launcher version: unknown

**Comment by deathbeam** [comment]
This is fixed next update, or well the behaviour changed. Now the centering is gone and you use alt + right click to reset position + the xp globes can now be layouted properly and new center snap point was added as default for them
