### ISSUE TITLE
Split "Reset" option in menu entry swapper to ground laying and box resetting

### ISSUE THREAD

**Issue by manacrazed** [runelite/runelite#5335]
**Is your feature request related to a problem? Please describe.**
Currently, enabling "reset traps" under menu entry swapper applies to 2 things:
1. It makes traps on the ground relayable with left click 
2. It makes the left click for failed traps reset them 
The left click lay box (that is on the ground) is very useful and handy,.
However, the reseting trap option is very time consuming, and pretty terrible overall. 

At the moment, enabling the swapper option puts them both on, while only ground laying is useful.

**Describe the solution you'd like**
I would like an option to select only 1. ground laying or 2. box resetting.

**Describe alternatives you've considered**
A split in the option of the menu entry swapper, to choose ground laying seperate to box resetting.

**Comment by MackBryan** [comment]
So if I am understanding correctly you want:

1: If a chin is successfully caught then the left click option is "Check"? I understand this since it will not automatically reset the trap.
2: If a chin fails a trap, the left click option should be dismantle. This also makes sense.

I just took a look at what needs to be done and should be a quick fix. I just want to confirm this is what you had in mind. I noticed this last night while doing black chins and would definitely be helpful for 3-ticking.

**Comment by manacrazed** [comment]
Just confirming...

1. If a chin is caught, left click should be check.
2. if a trap fails, left click should be dismantle (as reset is terrible.
3. If a trap times out - it falls to the ground, menu entry allows the left click option for this to become "lay" instead of pick up. 

Ideally it would be...

1. Check
2. Dismantle
3. Lay

I wasn't entirely sure we were on the same page and didn't want to waste your time so im repeating a lot of what you said :)

**Comment by MackBryan** [comment]
@manacrazed I just added entries in the config allowing you to customize swapping all of them except "Investigate" and "Dismantle", which is when a trap is active and waiting to be tripped (Didn't seem very useful). 
So this should let you customize the menu entries to your liking.

**Comment by manacrazed** [comment]
Wonderful! Thanks a lot!

**Comment by Adam-** [comment]
This should be possible now by setting each box types left click option individually with the custom left-click object settings in 92aac53f4273e7944c3da767637e083847c03808
