### ISSUE TITLE
Duplicating image on sidebar when mouse is moving across it

### ISSUE THREAD

**Issue by ChordPlayy** [runelite/runelite#5336]
A little while after I log in, if i move my mouse across the RuneLite taskbar on the side it will start to duplicate images and make it difficult to use because it clutters my screen. I already tried uninstalling and reinstalling, but unfortunately didn't resolve the issue. Please help

![image](https://user-images.githubusercontent.com/43042291/45170486-fc0e2e80-b1cd-11e8-90b8-42262c13a0b3.png)

![image](https://user-images.githubusercontent.com/43042291/45170539-16e0a300-b1ce-11e8-9678-52b5b7800d23.png)

**Comment by ItsSebas** [comment]
Try this 
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
