### ISSUE TITLE
Screenshots for finishing quests have incorrect filenames

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#5353]
Screenshot gets saved as "ds with My Arm.png"

![ds with My Arm](https://user-images.githubusercontent.com/5851433/45186090-5329f880-b1fa-11e8-92f9-cbf73ca9ab0a.png)

**Comment by oplosthee** [comment]
Many quests have this issue, I think another approach has to be taken to name screesnhots unless we want to add specific cases for each quest.

**Comment by ShaunDreclin** [comment]
https://oldschoolrunescape.wikia.com/wiki/Category:Quest_reward_scroll_images

Looked at a few of them, it's a total crapshoot what format any given quest will use. Specific cases for each quest might be the way to go here

**Comment by kittenparry** [comment]
* Horror from the Deep
* The Giant Dwarf
* Recruitment Drive
* The Feud (kind of)

Is some of the quests I came across in my screenshots directory. As I understand without looking at the code, the first "You have completed " length characters of the quest sentence is chopped and the rest is appended to screenshot name text. Maybe a way could be implemented to check for exceptions like these.

![Screenshot from 2020-03-26 07-46-34](https://user-images.githubusercontent.com/12991847/77611276-f6a24180-6f35-11ea-9e8e-2cc792aef34d.png)

**Comment by Nightfirecat** [comment]
I'm adding the `help wanted` tag, as this is very likely some extra/different widget text present for certain quests that's causing this. Anyone who hasn't completed some of the quests listed in the comment above and having some knowledge of how the screenshot plugin code gets quest names can help determine why it is these quests are having the beginnings removed in error.

**Comment by Belieal** [comment]
As was pointed out by kittenparry, it seems the filename is determined with 
`String text = client.getWidget(WidgetInfo.QUEST_COMPLETED_NAME_TEXT).getText();`
`fileName = "Quest(" + text.substring(19, text.length() - 1) + ")";`
which means it only expects quests complete screens with the "You have completed {Quest_name}!" format at the top.
Unfortunately, Jagex isn't entirely consistent with the text at the top.

Luckily however, the Wiki provides a screenshot of every quest completed screen, so I've compiled a list of the quests with exceptions to the format that would generate this error in the filename.

- [The Slug Menace](https://oldschool.runescape.wiki/images/6/65/The_Slug_Menace_reward_scroll.png?ad854) (no period or exclamation mark at the end)
  * [Mourning's End(s?) Part 2](https://oldschool.runescape.wiki/images/9/9b/Mourning%27s_End_Part_II_reward_scroll.png?393bd)

- [Swan Song](https://oldschool.runescape.wiki/images/e/e0/Swan_Song_reward_scroll.png?10935)
- [Rag and Bone Man II](https://oldschool.runescape.wiki/images/2/29/Rag_and_Bone_Man_II_reward_scroll_%28Bonesack%29.png?8f424)
- [Every Recipe for Disaster subquest and endquest except for the first one](https://oldschool.runescape.wiki/w/Recipe_for_Disaster)
- [The Ratcatchers](https://oldschool.runescape.wiki/images/c/c2/Ratcatchers_reward_scroll.png?9cbbe) (the closing quote will be cut off)
  * [Icthlarin's Little Helper](https://oldschool.runescape.wiki/images/4/49/Icthlarin%27s_Little_Helper_reward_scroll.png?856f4)
  * [Lunar Diplomacy](https://oldschool.runescape.wiki/images/a/aa/Lunar_Diplomacy_reward_scroll.png?9c0b6)
   * [The Feud](https://oldschool.runescape.wiki/images/2/2c/The_Feud_reward_scroll.png?44446)

- [Forgettable Tale of a Drunken Dwarf](https://oldschool.runescape.wiki/images/a/a9/Forgettable_Tale_of_a_Drunken_Dwarf_reward_scroll.png?8a236)
- [Recruitment Drive](https://oldschool.runescape.wiki/images/8/8e/Recruitment_Drive_reward_scroll.png?d8b57)
- [The Giant Dwarf](https://oldschool.runescape.wiki/images/b/b9/The_Giant_Dwarf_reward_scroll.png?0884b)
- [One Small Favor](https://oldschool.runescape.wiki/images/8/8b/One_Small_Favour_reward_scroll.png?7eb50)
- [In Search of the Myreque](https://oldschool.runescape.wiki/images/6/62/In_Search_of_the_Myreque_reward_scroll.png?edf3e)
- [Between a Rock...](https://oldschool.runescape.wiki/images/0/0d/Between_a_Rock..._reward_scroll.png?06459)
- [Horror from the Deep](https://oldschool.runescape.wiki/images/7/7e/Horror_from_the_Deep_reward_scroll.png?e6b9d)
- [Lucien ](https://oldschool.runescape.wiki/images/e/e2/Temple_of_Ikov_reward_scroll.png?efed1)and [armadyl ](https://oldschool.runescape.wiki/images/9/95/Temple_of_Ikov_reward_scroll_%28Armadyl%29.png?4d656)versions of Temple of Ikov
- [Making Friends with My Arm](https://oldschool.runescape.wiki/images/d/df/Making_Friends_With_My_Arm_reward_scroll.png?b400b)

**Comment by kittenparry** [comment]
Thank you for compiling this huge list, must have taken some time.

Fake completion of the Hazeel Cult also results in a screenshot being saved named `Quest(... completed the Hazeel Cult Quest) DATE.png`. I guess if an exception could be implemented for the rest, maybe it could also be implemented to ignore this quest completion screen.
![Screenshot from 2020-03-26 13-54-56](https://user-images.githubusercontent.com/12991847/77639258-86151800-6f69-11ea-9201-7ca14c46322c.png)

**Comment by johannfrias** [comment]
I've been running some test scripts in Python and I propose a solution that uses two regexes to capture the quest name from the image. But before I share sample code, I want to address what I think is the bigger question among this entire thread, which is "To what extent do we care about matching the quest name to wiki name?" Above replies have cited many quests for one of multiple reasons, from totally missing the quest name to having an extra character, but no mention of any guideline for what the output should be (e.g. match wiki name exactly, 1-2 char difference is okay, 1 word difference is okay).

The proposed mechanism carries its own exceptions, so I want to discuss guidelines with this mechanism. The first question is, is *any* exception worth the extra code to handle them? An easy, yet suitable answer is "no", which means the base solution is roughly 9-ish lines of code. The probable answer, though, is "yes", and in that case the second question is, which exceptions should be handled and how? I've listed a sample of 8 exceptions I came across in my testing so I and others can decide whether it is appropriate to handle them. Exception means a not 100% match with wiki name, which is the strictest definition.

Guide for table: Each row is a category of exception, with example quest and description. I compare the output of current RL code, and of 2-3 approaches I created. Option 1 uses the base solution. Option 2 uses the base solution plus extra code to refine the output. Option 3 uses the base solution but modified regexes, which affects more than that category of cases. Only 2 quests are double-counted (see row #*5*).

Quest Name | Quest Description | Current RL Code | Proposed Code (Option 1) | Proposed Code w/Extra Code (Option 2) | Proposed Code w/Modified Regex (Option 3)
--- | --- | --- | --- | --- | ---
(#*1*) [Hazeel Cult](https://oldschool.runescape.wiki/w/File:Hazeel_Cult_partial_completion_reward_scroll.png) | case-specific | Quest(... completed the Hazeel Cult Quest) | Quest(Hazeel Cult) *Duplicates [this](https://oldschool.runescape.wiki/w/File:Hazeel_Cult_reward_scroll.png) but RL avoids overwrite | Quest(Hazeel Cult partial completion) | N/A
(#*2*) [Rag and Bone Man II](https://oldschool.runescape.wiki/w/File:Rag_and_Bone_Man_II_reward_scroll_(Bonesack).png) | case-specific | Quest( completed Rag and Bone Man) | Quest(Rag and Bone Man) *Duplicates [this](https://oldschool.runescape.wiki/w/File:Rag_and_Bone_Man_reward_scroll.png) but RL avoid overwrite| Quest(Rag and Bone Man II) | N/A
(#*3*) [Making Friends with My Arm](https://oldschool.runescape.wiki/w/File:Making_Friends_With_My_Arm_reward_scroll.png) | Differs from wiki name by 1+ words (5-count) | Quest(ds with My Arm) | Quest(Made Friends with My Arm) | Quest(Making Friends with My Arm) | N/A
(#*4*) [Recipe for Disaster/Defeating the Culinaromancer](https://oldschool.runescape.wiki/w/File:Recipe_for_Disaster_(Defeating_the_Culinaromancer)_reward_scroll.png) | RFD Subquests (10-count) | Quest(u have defeated the Culinaromancer) | Quest(Culinaromancer) | Quest(Recipe for Disaster - Culinaromancer) *(2a) | Quest(Recipe for Disaster - Defeating the Culinaromancer) *(2b)
(#*5*) [Doric's Quest](https://oldschool.runescape.wiki/w/File:Doric%27s_Quest_reward_scroll.png) | Contains "Quest" in wiki name (5-count + "Another Cook's"(#4) + "Legends"(#3)) | Quest(Doric's Quest) | Quest(Doric's) | Quest(Doric's Quest) | Quest(Doric's Quest) *but a quest like Demon Slayer becomes Quest(Demon Slayer Quest)
(#*6*) [The Golem](https://oldschool.runescape.wiki/w/File:The_Golem_reward_scroll.png) | Differs from wiki name by word "The" (14-count) | Quest(the Golem quest) | Quest(Golem) | Quest(The Golem) | Quest(the Golem) *but a quest like Demon Slayer becomes Quest(the Demon Slayer)
(#*7*) [Lost City](https://oldschool.runescape.wiki/w/File:Lost_City_reward_scroll.png) | Contains wiki name plus extra words (4-count) | Quest(the Lost City Of Zanaris Quest) | Quest(Lost City Of Zanaris) | Quest(Lost City) | N/A
(#*8*) [Mourning's End Part II](https://oldschool.runescape.wiki/w/File:Mourning%27s_End_Part_II_reward_scroll.png) | Differs from wiki name by 1-2 chars (12-count) | Quest(Mourning's Ends Part ) | Quest(Mourning's Ends Part 2) | Quest(Mourning's End Part II) | N/A

Consider each row independently in deciding which of the options is the most appropriate, and consider the tradeoff between simplicity of code and accuracy of output. As it seems to be beyond a simple patch, I wanted to share a (lengthy) description first before sharing code. That said, I've tested all cases in Python and have an idea of how to implement each option for each exception, but I'm new to the RL code and less fluent in Java, so I'd appreciate some pointers. Also it's not clear to me how this could be effectively tested in practice other than legitimately completing the relevant quests. (Edit: I found [ScreenshotPluginTest](https://github.com/runelite/runelite/blob/master/runelite-client/src/test/java/net/runelite/client/plugins/screenshot/ScreenshotPluginTest.java) but I'm still comprehending the mechanics in case I should add to that file.) If needed, I could go into further detail about any aspect of this proposal, or how any specific quest is handled.
