### ISSUE TITLE
Diary requirements aren't showing after Update!!

### ISSUE THREAD

**Issue by usmcmartin** [runelite/runelite#5360]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Diary requirements are turned on but are not showing on interface**

**To Reproduce**

**Expected behavior**

![2018-09-06_18-29-08](https://user-images.githubusercontent.com/43051511/45190345-27f7d700-b203-11e8-926b-d8baab596e04.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by deathbeam** [comment]
Fixed in master, duplicate
