### ISSUE TITLE
An option to display idle notifications regardless of user input

### ISSUE THREAD

**Issue by RaspberrySchnapps** [runelite/runelite#5374]
**Is your feature request related to a problem? Please describe.**
The new Idle Notifications have one flaw, that isn't technically a flaw, but it could be a little better:
a notification is not displayed when the client detects user input, for example, when moving the mouse as the mining animation stops. 

**Describe the solution you'd like**
The solution to this would be making it(preferably an option, since I'm sure not everyone would want this) so that the notification would be sent regardless if the user is active in the client or not. Consider such a case: 

The mouse is being dragged through the client as the skilling animation is finished. The user is not paying attention and the idle notification is not displayed, since the client detects mouse movement and therefore thinks that the user is not afk. The user now either notices this sometime after it happens or gets the notification that the account is about to log out, both of which may take some time and defeat the purpose of idle notifications.

**Additional context**
Ideally, there could be a checkbox in the Idle Notifcations plugin settings such as this:
"Display notifications regardless of user input". 
While having this on, the idle notifications are displayed no matter what. 
While having this off the idle notifications are not displayed when there is mouse activity in the client.

**Comment by ShaunDreclin** [comment]
Huh, is *this* why that plugin seems so unreliable? I thought it was a bug this whole time.

**Comment by RaspberrySchnapps** [comment]
Pretty much, I thought it was bugging out on me at first, but I did a few tests and all signs point to some user input detection that determines whether or not an idle notification will be shown.

**Comment by ShaunDreclin** [comment]
I think rather than adding an option this should just be changed, most people aren't going to know it's intended behaviour.

**Comment by deathbeam** [comment]
it happens very rarely that you move your mouse at the same time as your anim ends, i would just keep it as is. maybe change it from detecting movement and clicks to just clicks?

**Comment by RaspberrySchnapps** [comment]
To be honest, I can understand both sides of the argument - I have two monitors and have Runelite on the primary one in full screen. For me the issue happens often enough for it to be annoying. But then again, when I remember the old idle notifications and how I tried using them with a 1000ms delay, I would get spammed for _a lot_ of random things despite being active, setting it to 2000 or 3000 would fix it.

That being said, if an option to toggle the feature request seems redundant or too big of a task, I'd gladly agree with either of your suggestions. I'm just glad that I'm not the only one who finds the current behaviour weird and slightly infuriating.

**Comment by deathbeam** [comment]
Atm the idle notifier is checking for < 10 client mouse idle ticks, that should be around ~200ms timeframe for such thing to happen. I can change it to 1, what is 20ms, that would still most likely remove the falsy notifications, what is another alternative what to do in this case.

But, I think I am most inclined to toggle that is off by default, eg something like you suggested `Display notifications regardless of user input`, as otherwise the system is working fine for most people.

**Comment by RaspberrySchnapps** [comment]
Yup, I feel like having such a toggle would please both parties!

**Comment by ShaunDreclin** [comment]
What's the benefit of not notifying if there is mouse activity? The logout notification already checks for that and with the others it doesn't seem like it should apply

**Comment by deathbeam** [comment]
To prevent false notifications as @RaspberrySchnapps mentioned. E.g with that you will not get any false thieving notifs, or random notifs when emptying birdhouses etc, you only get notifications when you are really idle, so only those you care about.

**Comment by ShaunDreclin** [comment]
Ahh I see. Yeah I guess it is worth having a toggle then

**Comment by deathbeam** [comment]
I created #5403 what is using last mouse and keyboard press events what will mitigate this issue as well, and is probably better than toggle. Also, it makes more sense as it is using same mechanism to check for idle state as client (as client is ignoring mouse movement events too).
