### ISSUE TITLE
Add minimap icons for new teleports from Making Friends with My Arm

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#5377]
Either above or below the agility shortcut on the Herb patch depending on Fremennik Hard completion, and I believe there was another new teleport to Weiss using salt? I can't find it on the Wiki. Maybe someone else knows.

**Comment by ItsSebas** [comment]
#5371 solved this

**Comment by Gamer1120** [comment]
Sorry, I should have also searched pull requests instead of just issues.
