### ISSUE TITLE
Menu Entry Swapper for Escort on Temple Trekking

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#5380]
![image](https://user-images.githubusercontent.com/9074448/45243983-2824cf00-b2f6-11e8-9259-158e2e404d32.png)
It would be nice to have Escort the default option.

**Comment by Nightfirecat** [comment]
This is a niche feature that is best suited for the plugin hub, and is currently covered by the Menu swapper extented plugin there. See runelite/plugin-hub#42
