### ISSUE TITLE
Minimap moves to middle of screen

### ISSUE THREAD

**Issue by KyleStiers** [runelite/runelite#5382]
**Describe the bug**
On boot the minimap appears in the middle top of my screen. Upon resizing (to or from) maximized window to any size except minimum, minimap remains in the middle of the screen. If I log out of my runelite account that syncs settings the minimap moves back to its correct position.

**To Reproduce**
1. Log in to game
2. Log into Runelite account (that stores settings) and see minimap isn't in correct position.

**Expected behavior**
Minimap should always stay to the top right regardless of resizing window and being logged into Runelite account or not.

**Screenshots**
![capture](https://user-images.githubusercontent.com/1393758/45247937-23015900-b2d1-11e8-8ed4-07d917c05599.PNG)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.16 
 - Launcher version: 1.6.0 Rev 174

**Comment by deathbeam** [comment]
alt + right click to reset position, you moved the minimap

**Comment by KyleStiers** [comment]
Wow, I had no idea that was a thing. Thanks a lot.
