### ISSUE TITLE
Adding quest name to quest locations on the map

### ISSUE THREAD

**Issue by itsSimplex** [runelite/runelite#5388]
Title

**Comment by ShaunDreclin** [comment]
Maybe also requirements if you haven't finished the quest?

**Comment by Gamer1120** [comment]
If this gets implemented, it would also be nice to have a status (not started, started and finished) and an option to hide markers for completed quests.

**Comment by kleinaeinar** [comment]
OMG yes please!  This is the one thing I REALLY miss from RS3.  Fuck the toolbelt or money pouch or lodestones.  I want this.
