### ISSUE TITLE
Change fairy ring destinations to be same as in in-game list

### ISSUE THREAD

**Issue by itsSimplex** [runelite/runelite#5389]
Using fairy rings displays 2 different location names when setting and comparing codes from the map and the menu

**Comment by raiyni** [comment]
have a screen shot?

**Comment by fairyfoam48** [comment]
Is this an issue of Jagex naming the location one thing within their fairy ring interface and then rune lite naming it another? A lack of consistency?

**Comment by itsSimplex** [comment]
Yeah that's what i was asking about, seems inconsistent

**Comment by deathbeam** [comment]
Don't think the location names in the fairy ring interface are supposed to match the in-game ones

**Comment by Abextm** [comment]
This is very much working as intended.

**Comment by ShaunDreclin** [comment]
If we're going to rename it in one place why not rename it in both? We should either use the Jagex names or overwrite them, having two different names for each destination *is* kinda confusing

**Comment by Rowan-Mulder** [comment]
RuneLite only adds the search filter to fairy rings. Inconsistent naming would have to be corrected by Jagex.

**Comment by Nightfirecat** [comment]
This is working as intended, we're not interested in changing it.
