### ISSUE TITLE
Eat to Use in Menu Entry Swapper

### ISSUE THREAD

**Issue by DonBagels** [runelite/runelite#5390]
**Is your feature request related to a problem? Please describe.**
I always have a minor fear that whenever I'm trying to make food like Tuna Potatoes or use food in quests such as Recipe for Disaster that I'll accidentally eat the food or ingredients and have to make up for the loss.

**Describe the solution you'd like**
Add an option in the Menu Entry Swapper to swap Eat/Drink and Use for foods to add some peace of mind during Cooking or quests.

**Describe alternatives you've considered**
Obviously, customizable shift-click alleviates this problem by simply holding shift to swap Drop to Use, but there could always be an added layer of convenience by only requiring clicks instead of shift-clicks.

**Additional context**
I want this feature simply as added convenience for cooking foods that require various ingredients that normally have Eat as a left click (baked potatoes, cooked sweetcorn, tuna, tomato, cheese, etc.), as well as to have peace of mind during quests that require you to bring food that were difficult or time-consuming to acquire, such as Fishcakes during RfD Freeing Pirate Pete.

**Comment by deathbeam** [comment]
We do not want to add menu entry swapping for inventory items for what you can already simply use shift-click.
