### ISSUE TITLE
Add an easier way of enchanting salve amulets

### ISSUE THREAD

**Issue by JuckFono** [runelite/runelite#5393]
**Is your feature request related to a problem? Please describe.**
Enchanting salve amulets at the moment is a pain and you need a lot of salve amulets(e) for Theatre of Blood.

**Describe the solution you'd like**
Maybe able to hold shift/ctrl/alt to make the first option on tarn's diary to "use"

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Abextm** [comment]
Use shift-click reordering for this

**Comment by oplosthee** [comment]
To add to this, this is how you do it:

After enabling the menu entry swapper plugin, you can customize your shift-click settings per item like this: ![](https://puu.sh/zVEcD/aff42db5c7.gif)

**Comment by JuckFono** [comment]
Alright sweet, thanks guys

**Comment by JuckFono** [comment]
Super quick responses :)
