### ISSUE TITLE
Add a notification after slayer task to tell you to go to Duradel (When appropriate)

### ISSUE THREAD

**Issue by danxgh10** [runelite/runelite#5396]
So every 9th, 19th...etc slay task you get a warning to tell you to do the next one with Duradel.
Would be a nice toggleable addition to the slayer settings.

**Comment by LlemonDuck** [comment]
Konar is now the highest point offering slayer master, and this can be accomplished with hub plugin [Konar Milestone Reminder](https://runelite.net/plugin-hub/show/konar-milestone-reminder) (it also allows selecting other slayer masters).
