### ISSUE TITLE
Add Fairy ring AIQ to mudskipper point clue

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#5399]
Fairy Ring: AIQ
Clue: ![clue](https://i.imgur.com/OgTj2JK.png)

**Comment by MackBryan** [comment]
If am not mistaken this is already implemented?

**Comment by deathbeam** [comment]
Hmm, @MagicfTail ?

**Comment by deathbeam** [comment]
Looks like it is not

**Comment by garyfish618** [comment]
Hi if no one else is working on this could I give it a shot?

**Comment by MagicfTail** [comment]
Ofc, go for it 😃

**Comment by Gamer1120** [comment]
![image](https://user-images.githubusercontent.com/9074448/45672416-5ee5bb00-bb28-11e8-9034-7272c7ffbbde.png)

Can confirm that this is currently not in release version.

**Comment by Adam-** [comment]
The fix for this regressed and broke the clue.
