### ISSUE TITLE
Pickpocket Coin Pouch notification

### ISSUE THREAD

**Issue by ValgeHunt07** [runelite/runelite#5413]
Was wondering if it is possible to make a coin pouch notification to notify when you are on max amount and need to open the pouches to keep on pickpocketing :) would be really helpful and make things much more afk and not worry that much about how much you have in inventory and so on :) thx.

**Comment by trimbe** [comment]
There's a chat message when you try to pickpocket and you're full on pouches, you can use the Chat Notifications plugin to trigger on that.

**Comment by ValgeHunt07** [comment]
Thats actually a nice solution, thanks :)

**Comment by Nightfirecat** [comment]
What have you tried? It's hard to help when there's no details.

**Comment by trimbe** [comment]
Make sure you have "Send notifications when focused" enabled in the settings for the 'RuneLite' plugin.

**Comment by deathbeam** [comment]
Duplicate of #4308
