### ISSUE TITLE
Chat recolour not working

### ISSUE THREAD

**Issue by CliffDiver** [runelite/runelite#5423]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When i select a colour to change different chat options, nothing happens, but the colours stay set.
When i log out of the game and back in the char recolour works for any messages received or sent before i logged out, but then any new messages are default colour.
**To Reproduce**
 Change colour, log out and in.
**Expected behavior**
I expected my colours to change with no issue
**Screenshots**
![0973ff4962f93f2005244fe88d321bc2](https://user-images.githubusercontent.com/43142193/45303197-2aad4180-b50d-11e8-89c1-51fcbf4b390c.png)
![c1987e959e4ed4451ad9e2d871436d54](https://user-images.githubusercontent.com/43142193/45303207-2da83200-b50d-11e8-8c64-bf73549f4d59.png)
![c56b6b8cc60e0f83421a97e08be11d3e](https://user-images.githubusercontent.com/43142193/45303214-300a8c00-b50d-11e8-890f-7c6ed9c3923a.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.6
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by raiyni** [comment]
user isn't using transparent settings

**Comment by NathenSample** [comment]
Whilst it does seem that the problem exists between keyboard and chair for the most part

the second screenshot does highlight that there may be an underlying issue whereby historic text will be recoloured wrongly upon login.
