### ISSUE TITLE
Incorrect hot-cold clue dig location

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#5424]
Reported from Discord:

![](https://i.imgur.com/AC0yzFW.png)
It worked 3 squares east

**Comment by MackBryan** [comment]
Looking into the code for the first time I am not sure what can be done for this one. It seems that dig coordinates are determined off of player coordinates when clicking the device. I'd like to see if this has been an issue for anyone else or he was just unlucky.

**Comment by Nightfirecat** [comment]
We could fix the worldpoint of this clue spot that we defined manually? I'm not sure what you mean "not sure what can be done for this".

**Comment by MackBryan** [comment]
Ahh okay I see it in the API now. I was looking the logic of possible dig locations too much. I have not looked much into the API yet but I'll give it a shot.
