### ISSUE TITLE
Maximising client when idle

### ISSUE THREAD

**Issue by AdamAliRS** [runelite/runelite#5425]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when I don't realize that my player has gone idle

**Describe the solution you'd like**
Maximize the client when the player is idle.

**Comment by deathbeam** [comment]
We already have request focus on notification, what will unminimize your window. if it is not working for you i believe that is known issue on Windows too. Either way, no reason for this issue to be open
