### ISSUE TITLE
Allow a way to easily search for emote clue items in bank

### ISSUE THREAD

**Issue by asherbasher** [runelite/runelite#5436]
**Is your feature request related to a problem? Please describe.**
Right now when you have an emote clue you have to manually find/search for the individual items in your bank.

**Describe the solution you'd like**
Allow users to search something like "clue" or "emote" in the bank and have it return the items for the current emote clue you have in your inventory.

**Comment by AverageHumanoid** [comment]
That's what stash units are there for.

**Comment by asherbasher** [comment]
> That's what stash units are there for.

I'm sure plenty of people do clues before they are in any sort of position to have built all of the STASH units or have the spare cash to keep some of the more expensive items permanently.

**Comment by raiyni** [comment]
I'll take a look at this after bank tags upgrade as it would extend the filter search

**Comment by IzzyTanuki** [comment]
You can add the words "clue" and "emotes" to the items as a bank tag and they would show up if you searched them. There is no need for an update.

**Comment by raiyni** [comment]
That's pretty cumbersome for all 100+ clue items.

**Comment by MagicfTail** [comment]
That would also show every single item with that tag, I think the request is to only show the items you need for the specific clue, similar to how osbuddy does it

**Comment by asherbasher** [comment]
> That would also show every single item with that tag, I think the request is to only show the items you need for the specific clue, similar to how osbuddy does it

Exactly this.
