### ISSUE TITLE
Could you make a Lizardman Shaman helper for Chambers of Xeric?

### ISSUE THREAD

**Issue by Haavard924** [runelite/runelite#5437]
Could you make a Lizardman Shaman helper for Chambers of Xeric? I don't want to be using konduit every time I go raid, I love runelite :)

**Comment by NathenSample** [comment]
As was said in discord, what you're wanting is help with their projectile attacks.

Which was historically part of the projectiles plugin, which got removed.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
