### ISSUE TITLE
Diary Requirements Plugin not functioning

### ISSUE THREAD

**Issue by MouldyTaco** [runelite/runelite#5461]
**Describe the bug**
About a week ago I was able to view level requirements underneath each diary task by enabling the Diary Requirements Plugin.  However, this has stopped functioning for me and disabling plugins one at a time to find a possible conflict were unsuccessful.

**To Reproduce**
1. Open RuneLite
2. Enable Diary Requirements Plugin
3. Open a Diary
4. See that no level requirements are displayed beneath each task

**Expected behavior**
Expecting to see level requirements displayed beneath each task.

**Environment (please complete the following information):**
 - OS: Win10 Home 64 bit
 - RuneLite version: 1.4.16
 - Launcher version: Unknown

**Comment by deathbeam** [comment]
This is already fixed in master, just wait for next release
