### ISSUE TITLE
total logged in time

### ISSUE THREAD

**Issue by coolkidzzz** [runelite/runelite#5465]
suggestion to add total logged in time per runelite session to info tab

**Comment by Alexsuperfly** [comment]
Hes called Hans in Lumbridge

**Comment by deathbeam** [comment]
This just gives people incentive to not close their clients after updates so I dont think this should be implemented as it would have negative effect.

**Comment by coolkidzzz** [comment]
from my experience you have to close RuneLite to update RuneScape on thursdays. yes?

**Comment by forsco** [comment]
> from my experience you have to close RuneLite to update RuneScape on thursdays. yes?

Not everyone comprehends this unfortunately

**Comment by raiyni** [comment]
only have to restart if it's a revision increment

**Comment by deathbeam** [comment]
also the new runelite version is not out when RuneScape updates, so if people just restart there, then there is a lot higher chance that they will just dont restart when actual runelite update comes out.

**Comment by ollieatkinson** [comment]
@deathbeam I agree with you, it might mean people do not close their clients.

> This just gives people incentive to not close their clients after updates

But this might be that the solution is incorrect (session length). 

Total time logged in on RuneLite sound's like a good stat to know. We probably need to think of a better solution.

**Comment by deathbeam** [comment]
Discord plugin already shows the logged in time, and max is 6 hours anyway (and report button shows it too). For play time you have hans. I will just close this because this is bad idea.
