### ISSUE TITLE
Herbiboar plugin to highlight the correct click when possible

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#5466]
Herbiboar isn't always 50/50 when there are 2 options to inspect. So highlighting the paths that are 100% odds of showing the next step is what im suggesting.

https://pastebin.com/ZJzEVNvr

Here are the herbiboar routes afaik.

**Comment by Hydrox6** [comment]
With the [Wiki](https://oldschool.runescape.wiki/w/Herbiboar) being updated to have rules as to where the trail can go at certain combinations of direction and location, it should be fine to implement it into the client now.
