### ISSUE TITLE
The woodcutting overlay thinks I'm not woodcutting when I'm a monkey

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#547]
I'm not sure if there's actually a way to solve this, since the overlay is using the player's animation to figure out if there's any woodcutting going on, but it doesn't look like there's any animation for woodcutting while you're a monkey.
![2018-02-08-000109_555x507_scrot](https://user-images.githubusercontent.com/34518321/35956366-3a3c5a62-0c63-11e8-82a6-9ed90f0a990b.png)

**Comment by sethtroll** [comment]
Can this be fixed? I don't think there is a way to determine if you are woodcutting without an animation.

**Comment by SoyChai** [comment]
If it's impossible, the overlay could show something helpful like `Woodcutting not detectable in monkey form` when the player gains wc experience in this state.

**Comment by SomeoneWithAnInternetConnection** [comment]
Unfortunately I'm not in a position to check right now, but I think I was still getting woodcutting *noises*, even if there wasn't any visible animation going on. It's possible that the animation may still be playing, to some degree, since that's one source of sound effect playback. It's also possible that the server's just sending "yo, there's a sound" messages to the client, in which case, Soy's suggestion is probably the best we can do, barring wierd heuristic magicks

**Comment by SomeoneWithAnInternetConnection** [comment]
I just checked, it would appear as though every attempt to gather a log (even an unsuccessful one) *does* play a chopping noise, at least, as long as you've got the "Area sound volume" (ie sfx that have a position) turned on. Though, as far as the devtools are concerned, I'm definitely not animating: 
![woodcutting-monkey-devtools](https://user-images.githubusercontent.com/34518321/38436312-4adea91c-39a2-11e8-8192-f788174a5495.png)

**Comment by kernelpaste** [comment]
@Adam-, can this be closed?

**Comment by Adam-** [comment]
This is still a valid issue, I just think it can't be fixed currently.

**Comment by Azarekk** [comment]
A chopped tree leaves a tree stump before a new one respawns. I was thinking this could be used as an indicator for Idle notifier.

**Comment by Adam-** [comment]
Having a notification when a nearby tree falls sounds like it would have a lot of false positives. We could probably get away with sending a notif if you are monkey & have an axe & also are next to a tree which falls though.
