### ISSUE TITLE
Add @SuppressWarnings annotations as needed in project

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#5482]
There are a number of places in the project, particularly in runelite-api where we define hardcoded values to be consumed in plugins or other client code, where values will be defined as `public` but not yet used in a way that requires that access level, or defined and are unused--either because client code using the values was removed or because they were preemptively added. Cases such as these will raise warnings in IDEs which could be suppressed with a `@SuppressWarnings` annotation such as `@SuppressWarnings("WeakerAccess")` or `@SuppressWarnings("unused")`.

**Comment by deathbeam** [comment]
I dont this supressing warnings for unused code is good idea, if we have it exposed and don't use it, that is valid case for having warning.

**Comment by Nightfirecat** [comment]
Would it be better to remove entries from files like WidgetID and WidgetInfo than to suppress the warnings there? I don't feel that way.

**Comment by raiyni** [comment]
WidgetID, ItemID, etc shouldn't be removed if they aren't in use.
