### ISSUE TITLE
Fishing Icons can no longer be toggled

### ISSUE THREAD

**Issue by HotdogCombo** [runelite/runelite#5488]
**Describe the bug**
On previous versions you could toggle specific fishing spot icons to not show, this way you would only see the blue dots on the minimap and the visual icons for specific fish. Since updating to 1.4.17 the options are now missing.

**To Reproduce**
1. Go to 'Fishing' option
2. There is now only 'Display Fish Icons' with no further list of each individual spot.

**Expected behavior**
There used to be a list of every type of fishing spot. There is still a GIF present on the WIKI that shows the settings be available: https://github.com/runelite/runelite/wiki/Fishing

**Screenshot**
https://i.imgur.com/LXsQsGJ.png

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - RuneLite version: 1.4.17
 - Launcher version: 1.6.0

**Comment by Adam-** [comment]
It looks like it was deemed unnecessary in https://github.com/runelite/runelite/pull/5446

**Comment by deathbeam** [comment]
As I said in discord (probably to this person, not sure), we can add toggle to only show display fishing spots for currently fished fish, what would be a lot nicer solution (as that is what the OP wants anyway).
