### ISSUE TITLE
Notification control

### ISSUE THREAD

**Issue by psukys** [runelite/runelite#549]
Instead of creating many notifications  of same type, let it be reused/cleared?

For example:
When idling - a new notification is created and the the old one stays thus after some time a significant list of same type of notifications builds up.

**Comment by devLotto** [comment]
Maybe we can make use of https://github.com/dorkbox/Notify as mentioned on the Discord.
Would give more control over the notifications, but I don't know if it works well or not.

**Comment by deathbeam** [comment]
Non-native notifications are ugly :/

**Comment by psukys** [comment]
If we want native notifications, the we could use [Strategy pattern](https://en.wikipedia.org/wiki/Strategy_pattern) for handling peculiarities for each system's nativity.

**Comment by deathbeam** [comment]
But we already have ones.

**Comment by psukys** [comment]
then it's a bug fix, not a feature request

**Comment by deathbeam** [comment]
Bug in your operating system.

**Comment by deathbeam** [comment]
Soo, it looks like that the timeout for the notification in notify-send was never set, maybe Ubuntu default is never timeout unless set. I will prepare patch to address this.

**Comment by deathbeam** [comment]
This was resolved in 61a586c , notifications should now properly disappear after some time. If it is still problem, please reopen.
