### ISSUE TITLE
Charged Glory / Ring of Wealth Warning

### ISSUE THREAD

**Issue by breadbreadbread** [runelite/runelite#5492]
**Is your feature request related to a problem? Please describe.**
When pking, doing rune crafting, or anything similar- it can often be frustrating when you bank having used your last glory charge and leave. 

**Describe the solution you'd like**
A simple chat message that would warn you if you have just banked after recently using your last glory/row charge. Perhaps a toggle could be used so that you could only get this message when also skulled.

**Describe alternatives you've considered**
Having better memory, perhaps a warning for uncharged glory/row could go alongside your stats/prayers boxes as well.

**Additional context**
There are similar warnings already employed in runelite, this does not seem to be overpowered, this would not increase your ability to do anything, it would just be a nice reminder- as is the last charge message on your glory, but this may go unnoticed.

**Comment by raiyni** [comment]
enabling client focus for notifications should notify you.

**Comment by deathbeam** [comment]
Duplicate of #504

**Comment by breadbreadbread** [comment]
Its not at all a duplicate, and that isn't the solution. The current method warns you as the glory runs out of charges- if you are doing something or in a fight this does not notify you when you bank- the specific and common situation.
