### ISSUE TITLE
Item API 404s when requesting untradeable item icons

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#5497]
Reported in discord

For example:

* Proselyte Tassets: https://api.runelite.net/runelite-1.4.17/item/9678/icon (returns image successfully)
* Max cape: https://api.runelite.net/runelite-1.4.17/item/13342/icon (HTTP 404)

This can apparently be reproduced for any untradeable item.

**Comment by deathbeam** [comment]
I marked this a bug even though it is mostly just incomplete feature so idk how to mark it properly.

**Comment by ftbcoders** [comment]
https://api.runelite.net/runelite-1.4.19/item/9678/icon

use the newer api

**Comment by Nightfirecat** [comment]
@ftbcoders https://api.runelite.net/runelite-1.4.19/item/13342/icon still 404s, which is what was reported...

**Comment by ftbcoders** [comment]
@Nightfirecat Your first link you posted is 404 as well though..? https://api.runelite.net/runelite-1.4.17/item/9678/icon

**Comment by Nightfirecat** [comment]
Not sure what you're talking about... It returns a blank HTML page, but it definitely 404s:

```
$ curl -I https://api.runelite.net/runelite-1.4.19/item/13342/icon 2>/dev/null | grep 'HTTP'
HTTP/2 404
```

**Comment by deathbeam** [comment]
Actually, we have cache api, so e.g. https://api.runelite.net/runelite-1.4.22-SNAPSHOT/cache/item/19845/image

So I guess we have this already implemented, closing

**Comment by Nightfirecat** [comment]
In that case, would it be better to just remove the item image endpoint then? The cache image endpoint is always more comprehensive.

**Comment by deathbeam** [comment]
Not sure if cache image endpoint is cached, and also background from images there is white for some reason

**Comment by Nightfirecat** [comment]
The image you linked doesn't have a white background... :thinking:
