### ISSUE TITLE
Widget/Text/overlay additions/toggles

### ISSUE THREAD

**Issue by GoEasyImBad** [runelite/runelite#5504]
Would it be possible to add an option to “alt” or “ctrl” toggle for ground items to appear/disappear. Also adding more text options that are less bulky for widgets and overlays such as clue scrolls,mouse over text etc. 
being able to fill in the background of these overlays and widgets would along with the text changes would be a nice customization option.

**Comment by deathbeam** [comment]
Maybe. It would help to close the issues as duplicates if you made 1 issue per request.
