### ISSUE TITLE
Don't give low hitpoint notification when you get hit and regen over the threshold in the same tick

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#5506]
Let me give an example. My HP is 89, and I have my low hitpoint notification set at 71, so I can eat a Karambwan whenever I get a notification. Occasionally, I get the notification after getting hit, but notice that I'm at 72 hitpoints, because I regenerated health. This effectively wastes 1 hitpoint from my Karambwan. These are my settings:
![image](https://user-images.githubusercontent.com/9074448/45585660-44bd9a00-b8e8-11e8-8417-9098dc5ff8fb.png)

**Comment by Kamielvf** [comment]
Don't eat it and wait till it notifies again? This issue is invalid.

**Comment by Gamer1120** [comment]
The issue is that it should not have notified in the first place.

**Comment by Kamielvf** [comment]
It surely hit the threshold else it would have never notified you. There is no way that the program just decides that `71` is now `72` and notifies you. You hit `71` hp and then regen happened after.

**Comment by deathbeam** [comment]
You reached the threshold. We would need to delay the notification 1 tick and then it would not be longer accurate and might cause deaths of people depending on it.

**Comment by Kamielvf** [comment]
For a workaround, set your threshold to 70.

**Comment by Gamer1120** [comment]
Makes sense, thanks!
