### ISSUE TITLE
Ground items: Show only my drops (Iron Man)

### ISSUE THREAD

**Issue by Treedot** [runelite/runelite#5512]
I don't know if this is even possible, but if so, it would be really nice to have the option to only show overlays on ground items that are yours to pick up for Iron Man accounts.

**Comment by raiyni** [comment]
duplicate https://github.com/runelite/runelite/issues/3801

**Comment by Treedot** [comment]
> duplicate #3801

So is this in development? That post was made in June and nothing has happened with it since.

**Comment by raiyni** [comment]
no
