### ISSUE TITLE
Add an Option in the Menu Entry Swapper For Wilderness Lever

### ISSUE THREAD

**Issue by SakuraTheSky** [runelite/runelite#5516]
This Issue is just for a quick  QoL for those with the wilderness Diary nothing more. Also makes escaping to Edgville from PKers easier but not making escape itself easier all together.

**Comment by MackBryan** [comment]
Is the option to teleport to both locations visible regardless of your diary progression?

**Comment by Nightfirecat** [comment]
No, it only appears once you have completed the appropriate diary. (easy iirc?) Nonetheless, this should be easy to implement since the menu entry swapper code we use shouldn't cause failures if the desired option isn't found.

**Comment by deathbeam** [comment]
Does this request even make sense? If you are just trying to escape pkers you can as well teleport to ardougne, it does not really matter.

**Comment by Alexsuperfly** [comment]
I find it annoying when i forget to right click it and select edge. since i just left click and look away without thinking sometimes.  Theres 0 reason to go to ardy after you have the diary done so i would support this feature.

**Comment by Nightfirecat** [comment]
This is a niche feature that is best suited for the plugin hub, and is currently covered by the Menu swapper extented plugin there. See runelite/plugin-hub#42
