### ISSUE TITLE
Notifications do not pop up Runelite client

### ISSUE THREAD

**Issue by JackSmith23** [runelite/runelite#5519]
**Describe the bug**
Idle notification only adds message to notification center on windows 10 and sometimes flashes the taskbar. I have the "Request focus on notification" setting turned on as seen in the image below .

**Expected behavior**
Runelite client should pop up to the foreground upon notification.

**Screenshots**
![image](https://user-images.githubusercontent.com/39570169/45602890-ff868e80-b9f3-11e8-97c2-4cfa364196cf.png)

![image](https://user-images.githubusercontent.com/39570169/45603112-b3891900-b9f6-11e8-9547-4aaf19a4d1b6.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.17.1
 - Launcher version: "unknown"

**Comment by jhumphrey1** [comment]
I don't believe idle notifications appear when you are actively interfacing with the screen, only when actually afk when screen is focused

**Comment by humphrjm1** [comment]
I don't believe notifications pop up when you are actively interacting with the screen, only when "afk" while the screen is focused

**Comment by deathbeam** [comment]
We have issue already open for this. Also, the option is just named "Request focus" nothing guarantees that request will go through it is OS-dependant
