### ISSUE TITLE
Add the Buy Plank option to the menu entry swapper

### ISSUE THREAD

**Issue by SirRahmed** [runelite/runelite#5526]
Basically, It would help me a lot (and others doing the make plank money maker) if someone could swap the menu entry boxes for "Buy-plank" with the "Trade" on the sawmill operator.

**Comment by MackBryan** [comment]
The config is up to nearly 20 entries now, should we keep adding config options for new entry swap abilities?

**Comment by deathbeam** [comment]
Duplicate of #1930
