### ISSUE TITLE
Let's talk about the new mobile render 

### ISSUE THREAD

**Issue by james-munson** [runelite/runelite#5536]
#2760 
beta is the 30th woto
hopefully it wont end up like 
https://twitter.com/MrIanGower/status/607698751482765313

so can run elite support it out of the box or would it have to add support?

**Comment by Nightfirecat** [comment]
I'm not sure how the mobile rendering engine changes anything. Also, how is this different from #2760?

**Comment by deathbeam** [comment]
OSRS Mobile != OSRS , its like 2 different codebases, we can't support out of the box something that does not exists
