### ISSUE TITLE
Chest Respawn Timer

### ISSUE THREAD

**Issue by ScrPits** [runelite/runelite#5539]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Respawn timer for "theving" chest 
pull the time the chest is thevable

**Describe alternatives you've considered**
Chest Respawn timer Gui paint.

**Additional context**
Search for traps "respawn" timer (this is to help even your elvish adventures) (the traps around the elv kingdom

**Comment by deathbeam** [comment]
Duplicate of #3924
