### ISSUE TITLE
Tabbed Instances

### ISSUE THREAD

**Issue by Vokuar** [runelite/runelite#5540]
**Is your feature request related to a problem? Please describe.**
Only the inabilty to have 2 accounts at the same time in one browser window

**Describe the solution you'd like**
Tabbed Instances for Multiple Accounts

**Describe alternatives you've considered**
opening 2 versions of runelite

**Comment by deathbeam** [comment]
This is very bad idea (well in void it sounds cool) as that will most likely break 99% of how client is working atm and I dont think we can ever implement this. Just open multiple runelite clients
