### ISSUE TITLE
Exp trackers not accurate 

### ISSUE THREAD

**Issue by osrskevin** [runelite/runelite#5541]
Regardless of what activity and whether it be exp globes or exp side menu, it will never show any skill being aove 4k/hr when in reality it is far above that. 
![exp](https://user-images.githubusercontent.com/42685340/45683752-6c904600-bb12-11e8-80cc-ff05f318c19a.png)

**Comment by deathbeam** [comment]
Reset the XP tracker (right click menu), you probably started skilling and ten stopped
