### ISSUE TITLE
When using indicators in the Boost Information, allow it to be displayed as "Current/Total"

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#5548]
![image](https://user-images.githubusercontent.com/9074448/45735329-d0d10980-bbe7-11e8-8b7c-e461d16c86e5.png)
This isn't very descriptive for me. I would like to for example see "62/60" instead of "60" on the overlay.

**Comment by deathbeam** [comment]
Well just simply looking at the image you posted, it do not fits at all. You already have a choice to show what you want in panel instead of indicators. this is how all other clients display it too, and there is simply not enough space for displaying X/Y and won't be.
