### ISSUE TITLE
Highscore Ironman lookup stall

### ISSUE THREAD

**Issue by jayrankon** [runelite/runelite#5549]
**Describe the bug**
whilst using the high score, if switching to iron man look up, feature stalls for extended period of time
and requires client restart, unknown if it is completely on my side

**To Reproduce**
1. click on high scores, or look up in game
2. type in any name
4. try to switch to iron man and back to regular or any other
3. feature will stall and require reboot of client to use again

**Expected behavior**
when switching between high scores, it should do so successfully, without requiring reboot to use

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43401646/45738810-01e51600-bbb7-11e8-952f-98e7af3b0c0b.gif)

**Environment (please complete the following information):**
Windows 7, runelite version 1.4.17.2

**Comment by Abextm** [comment]
Duplicate #5513
