### ISSUE TITLE
Apply the ground item name color also to examine

### ISSUE THREAD

**Issue by alexmcjuicy** [runelite/runelite#5554]
**Is your feature request related to a problem? Please describe.**
no problem just a ui fix that bugs me

**Describe the solution you'd like**
please make the item name color also apply to examine options too cuz it's ugly to see currently

**Describe alternatives you've considered**
no other alternative, make it happen or else :(

**Additional context**

![image](https://user-images.githubusercontent.com/5326839/45771054-b3ad3280-bc09-11e8-91c2-6c7d3f19b969.png)

**Comment by deathbeam** [comment]
This do not makes any sense, because all where the option matters is take

**Comment by deathbeam** [comment]
I guess this is good to close because the current behaviour is working as expected
