### ISSUE TITLE
Really bad FPS

### ISSUE THREAD

**Issue by peslak** [runelite/runelite#5556]
So I have a custom built PC, Geforce 1060 6gb/i5 processor/plenty of ram. I can run battlefield, skyrim remastered, witcher 3 all in ultra perfectly fine and smooth but I cannot surpass 10fps on the RuneLite client. Ive tried prioritizing the app through the task manager but that helps very slight (1/3fps at most) and its so unnoticeable. Its definitely not a problem with my rig and I've tried resetting it multiple times for the same thing to occur. A fix or tips how to would be greatly appreciated

**Comment by Abextm** [comment]
Does this happen on the vanilla client?

**Comment by peslak** [comment]
> Does this happen on the vanilla client?

It does when its on expanded to fit mode. The fixed, static size runs perfectly fine and I am totally confused as to why

**Comment by Abextm** [comment]
Then there is nothing we can do about it. You may want to turn on the `Stretched Fixed Mode` plugin and turn on vanilla fixed mode.

**Comment by peslak** [comment]
> Then there is nothing we can do about it. You may want to turn on the `Stretched Fixed Mode` plugin and turn on vanilla fixed mode.

I will try that, but any clue on why I'm running into this problem?

**Comment by Abextm** [comment]
typically its because your window is too large for your cpu's speed
