### ISSUE TITLE
Sell all on GE

### ISSUE THREAD

**Issue by astaninger** [runelite/runelite#5557]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to sell multiple (i.e. > 5 stacks) stuff on the GE. 

**Describe the solution you'd like**
It feels like there should be a sell all at average price in inventory button for GE. This way don't have to offer and confirm so many times. Maybe have a warning for items that are above a certain threshold. But even then most of the time they could be bought back easily. 

**Describe alternatives you've considered**
Selling each item individually. Takes extra unnecessary time and is surprisingly click intensive.

Not sure if this feature is allowed. It would be nice if Jagex implemented this. Maybe if we implemented it they would consider it.

**Comment by Abextm** [comment]
This is most certainly botting, and hence we will not be doing it

**Comment by astaninger** [comment]
I realize that we shouldn't implement. But do you at least think Jagex should? People might've said the same thing before the "deposit all to bank" button. Not saying that we should do it. Just want confirmation that it's not a totally dishonest idea...

**Comment by Abextm** [comment]
You would have to ask Jagex to poll it to find out the answer to that question.
