### ISSUE TITLE
Permanent chat effects, planting seeds in filled plant pots and watering them in inventory

### ISSUE THREAD

**Issue by r00nlyte** [runelite/runelite#5563]
Permanent chat effects such as using white:shake:, glow1: instead of typing it over and over "white:shake:" it does it automatically for you as you type in anything in the chat bar for public chat, not using the autochat, but typing any message in the public chat and it uses the chat effects without typing "glow1:shake:" for example over and over. I know it works for autochat, but I want to type multiple different messages using the chat effects without adding "green:" over and over again. 

When planting a seed in a filled plant pot, when we looked in our inventory let it say maple seedling over the pot instead of hovering over the item in your inventory with the mouse, and let it say (w) for water in the inventory when you water it and then turn it into a sapling.  You know how jewelry has the number in the inventory or when wearing it? Instead of a number, you can show in your inventory when a seed has been planted into a filled plant pot (s), then watered(w).

Thank you.

**Comment by ShaunDreclin** [comment]
One suggestion per issue please

**Comment by trimbe** [comment]
You can accomplish the last two requests by using the [inventory tagging](https://github.com/runelite/runelite/wiki/Inventory-Tags) plugin.

**Comment by raiyni** [comment]
Also #1 is faking too much input

**Comment by deathbeam** [comment]
Yeah, looks like inventory tagging is more than enough for this. And rest is faking user input
