### ISSUE TITLE
Menu Entry Swapper - Adding construction 'Build' / 'Remove' options to the top

### ISSUE THREAD

**Issue by DeeRock94** [runelite/runelite#5567]
I always find it difficult skilling construction, not because the resource demand or cost of the skill but the constant right clicking and moving mouse to options then left clicking. Even when using the numbers on a keyboard, it's a pain having to right click all the time to open the build/remove interface

My idea is to incorporate into the already developed menu entry swapper, the ability to switch the Remove and Build options to the top to allow _left_ clicking instead, or whether to use the functionality of that item as the top option. For example a larder having 'Search'

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
