### ISSUE TITLE
Remove the idle alert when using pot share

### ISSUE THREAD

**Issue by Beckxr** [runelite/runelite#5571]
After using pot share, the idle alert activates and sends an alert

**Comment by Unmoon** [comment]
Should check other Lunar spells too, NPC Contact is causing this too.

**Comment by forsco** [comment]
So far i've found that Pot share, NPC Contact, Fertile Soil and Bake Pie all share the same animation id, so it can't be ignored based purely on ID.

**Comment by forsco** [comment]
Pending GFX id's as I don't have the requirements for a big portion of the Lunar spell book.

**Comment by deathbeam** [comment]
NAME/ANIM/GRAPHIC

Spellbook Swap - 6299, 1062
Heal Group - 4409, -1
Heal Other - 4411, -1
Veng - 8147, 726
Energy Transfer - 4411, -1
Tele Group? Catherby/Fishing Guild - 1816, 747
Plank Make - 6298, 1063
Boost/Stat Pot Share - 4413, 733
Dream - 7627, -1(1056 zzzz)
Stat spy - 6293, 1050
