### ISSUE TITLE
Loot tracker does not track amount of barrows chests opened

### ISSUE THREAD

**Issue by Daylend** [runelite/runelite#5573]
![image](https://user-images.githubusercontent.com/4407295/45858365-489f5100-bd1a-11e8-8ed0-182a47b958c6.png)

As you can see, after doing a few barrows trips, there is no kill counter next to the name, as opposed to the 16 skeleton loots counted below. Using runelite 1.4.18.

**Comment by psikoi** [comment]
Okay I found the issue, will PR a fix tomorrow (it's 5 am)

**Comment by psikoi** [comment]
Fixed in #5588
