### ISSUE TITLE
Delete "raw" from alt + clicking to search GE price

### ISSUE THREAD

**Issue by MildPanda** [runelite/runelite#5577]
I think most people may want to see raw fish price along with cooked fish price making the Alt + Click search ignore raw from search results would fix that. Also to my knowledge most fish searches wouldn't produce too many results so even if there is more that pops up like Lobster Pot you can still find price in there easily for raw lobster and cooked

**Comment by deathbeam** [comment]
That is not how the feature works. The alt + click simply searches the item you want to search. If you want to search for something specific like in this case, just enter that to sidebar.
