### ISSUE TITLE
Item stats tooltip not being cleared

### ISSUE THREAD

**Issue by Cetacian** [runelite/runelite#5579]
![booost error](https://user-images.githubusercontent.com/43474252/45885308-162a3e00-bd84-11e8-9da1-b8afba69aaca.png)
There is a boosted stats change following my cursor around despite my stats not being boosted, plus it would be a weird feature regardless as it follows your mouse wherever and blocks the view. I also included my boosts information tab in the shot. Please fix!

**Comment by Alexsuperfly** [comment]
That is the Item Stats plugin creating a Mouse Tooltip when you hover over any item that can modify your stat levels.

**Comment by deathbeam** [comment]
Changed the title and changed this to bug, looks like item stats tooltips was not cleared for you for some unknown reason

**Comment by Alexsuperfly** [comment]
Another instance of this happening, reported in discord by another individual

![](https://cdn.discordapp.com/attachments/248286630933299202/493273817494454274/unknown.png)

**Comment by Adam-** [comment]
Why is this labelled jagex-bug?
