### ISSUE TITLE
Plugin for tracking burner times in Player Owned Houses

### ISSUE THREAD

**Issue by toxxicjtag** [runelite/runelite#5580]
Looking to get a new feature for runelite. I currently have to use a web timer with a loop feature to keep track of my burners in the player owned houses. At the end, it makes a sound. Someone suggested that I suggest this to help with hosting houses and guilded altars. 

Anyway, it's based on firemaking level. At 30, its 2 minute burn time, and 99 is 4 minutes. 
Not sure if theres a way to track the current status or from the lantern be able to see its about to go out, but if there was a way to determine it, it would be a great plugin. I wouldn't care if there wasn't a sound, even just a clock.

Thank you

**Comment by trimbe** [comment]
Duplicate #4679 

Also there's a PR open for this #5179
