### ISSUE TITLE
Expand in-game ignore list to more people

### ISSUE THREAD

**Issue by Deformance** [runelite/runelite#5584]
With the number of scammers/ spammers (Doublers, web advertisers) present in OSRS, my blocklist is filling up insanely fast to keep the game playable (up to 300 out of 400 available ignore slots in a matter of two weeks). I, therefore, would like to request the 'Expanded Block List' feature to increase the limit of 400 people to however high would seem realistic.

**Comment by osrs-music-map** [comment]
would the chat filter achieve the same purpose in place of this proposed feature

https://github.com/runelite/runelite/tree/master/runelite-client/src/main/java/net/runelite/client/plugins/chatfilter

**Comment by Nightfirecat** [comment]
I agree, we aren't going to be able to change the behavior of the ingame ignore list. The Chat Filter plugin, which has been added since this issue was originally opened, should fulfill this function sufficiently.
