### ISSUE TITLE
Request for Quest Markers to Change When Quest is Completed on Minimap/Map

### ISSUE THREAD

**Issue by proEndreeper** [runelite/runelite#5589]
**Is your feature request related to a problem? Please describe.**
I'd like it if the minimap had some indication if a quest had been completed on the map, similar to how the agility shortcuts are crossed through if you can't use them.

**Describe the solution you'd like**
When a quest is completed, draw a red line through it signifying the quest is done.

**Describe alternatives you've considered**
Perhaps just hide the quest marker if the quest has been completed.

**Comment by deathbeam** [comment]
Duplicate of #1964

**Comment by proEndreeper** [comment]
Err, I don't think this is a duplicate of that feature-request, as that one covers the quest description, mine covers the markers on the minimap.

**Comment by deathbeam** [comment]
Ah right

**Comment by Adam-** [comment]
Added in #9086
