### ISSUE TITLE
Adjust tab distance in notes plugin

### ISSUE THREAD

**Issue by SirDylan** [runelite/runelite#5591]
I keep a lot of things in my note pad, but it be dreadfully hard to read and keep organized.

I think decreasing the tabbing spacing would go a long way to aid in creating clear notes.

It would also be awesome to add bullet lists with a hot-key to activate.

![9474f8fc586c3ff816c40f34d174814c](https://user-images.githubusercontent.com/35585687/45921936-77860600-be85-11e8-9723-e99efc48f842.png)

**Comment by raiyni** [comment]
Use sticky notes

**Comment by deathbeam** [comment]
The notes plugin contains only text, we will not be adding any editor-like features that isnt just plain text, but the tab distance makes sense, idk why it is so horrid atm.
