### ISSUE TITLE
Hint for mudskipper point easy emote clue is missing

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#5596]
Wave on mudskipper point easy clue doesn't show up after teleporting to it

Get clue, see required stuff, go to place, don't see required stuff.

Happened twice today. Thought first time was a fluke.
Not the second time.
Dropping the clue, tping away and back, combinations of things like that, don't work.

**Comment by deathbeam** [comment]
Looks like the map icons get cropped even without menu widget being actually visible https://gyazo.com/ee99649ab8ddb060f5207ef21b1fcbaf. @Nightfirecat maybe you know why?

**Comment by Nightfirecat** [comment]
Hm... Will look into this tomorrow, that definitely shouldn't be happening.

**Comment by Nightfirecat** [comment]
I'm unable to reproduce this behavior... No matter what I click on, or how I resize the map (in fixed and resizable layouts), I am not able to get this same behavior.

**Comment by Nightfirecat** [comment]
To anyone who may also have this issue--does the issue persist after restarting your client?

**Comment by JeljoGb** [comment]
I'll test that when I get the step again

**Comment by Nightfirecat** [comment]
You should be able to test this without a clue step by seeing if our custom world map icons get clipped.

**Comment by JeljoGb** [comment]
Oh?  
But it didn't show the "wave" emote outline either.
I should've taken screenshots.

**Comment by deathbeam** [comment]
Updated the issue title as this looks like it is related to different issue than we originally thought, e.g simply by missing clue step.

**Comment by xDemoN** [comment]
Please Close - This regression happened as a result of #5538 that went live with the 1.4.18 release on 9/20/18, and was then reverted by #5664 on 9/27/18 for 1.4.19
