### ISSUE TITLE
Display "Members objects" by their actual name

### ISSUE THREAD

**Issue by astralach** [runelite/runelite#5597]
Is this feasible? If so, it would be a fantastic QoL improvement for ex-members.

**Comment by astralach** [comment]
This would be a great help

**Comment by whartd** [comment]
Would this exist as it's own plugin? If so what would be the name? If not, where would it be housed? 

Since it's changing the text of menu entries, the Menu Entry Swapper plugin *sounds* decent, but it's very different from that plugins existing functionality.

**Comment by Adam-** [comment]
added in 09be0b63ce222624594b14bbda9502ed660c1529
