### ISSUE TITLE
Stuck on Ignore Tab

### ISSUE THREAD

**Issue by Gloego** [runelite/runelite#5601]
So, lately whenever I open runelite, it opens with the ignore list open. Whenever I try to click on any other tab, inventory, prayer, magic, whatever, it instantly goes back to the ignore tab.
Any ideas?
Thanks

![halp](https://user-images.githubusercontent.com/31053382/45930105-17dd3880-bf21-11e8-8ccf-6aeb4f39829b.PNG)

**Comment by trimbe** [comment]
I don't think it's possible for runelite to be causing this. Check the F-key you have bound to ignore, maybe it's stuck?

**Comment by deathbeam** [comment]
Yeah this looks like it is problem between chair and computer, we cant really cause this to happen.
