### ISSUE TITLE
Add a lock zoom level to the Camera zoom tool.

### ISSUE THREAD

**Issue by offZills** [runelite/runelite#5605]
It would be helpful and a nice add-on if you can add a toggle on/off option to the camera zoom plugin to make it locked in a level you adjusted so the mouse wheel doesn't affect it after that, for people who got sensitive mouse wheel or mis-adjust their zoom levels by mistake when they move the camera using mouse wheel.

**Comment by deathbeam** [comment]
Duplicate of #1124 (as that is better solution I guess)

**Comment by Abextm** [comment]
This is just a vanilla feature

**Comment by offZills** [comment]
I guess having to press another button to do something is over-work (along with Shift to drop,alt to move camera,tab to answer chat) i guess having the lock option for people who is used to a certain zoom level and change it is the better option.

**Comment by Abextm** [comment]
locking camera zoom is a vanilla feature, click the scroll wheel by the zoom bar in the options panel
