### ISSUE TITLE
minor user interface improvements

### ISSUE THREAD

**Issue by greenmist49** [runelite/runelite#5607]
First off Barrows pieces and other degradable items displaying their percentage left when in inventory and equipped.  (blowpipe etc. how many shots available)
 
Nmz improvements - updating it so a message displays if you attempt to eat a rock cake and your hp after will be below 51, this you can toggle on and off in the NMZ settings along with a notification when your health is at level X.(going up not down, so you could rock cake down to 51 drink an overload then be at one and be notified every time you hp hits 2. 

Here is just a thought somehow binding quick prayers to an F key that will not be ban-able by jagex's bot detection. 

Adding combat stats to the calculator (not necessarily all monsters but xp and how many kills some monsters would take you(the most common))

possible quest helper it could be anywhere from required stats, items needed and maybe even full quest guides.

**Comment by greenmist49** [comment]
^^ tagging alters or marking them.

**Comment by deathbeam** [comment]
1 request per issue, also, we have issue open for 4. and 5. Probably also for 1. 2. is not possible because we cant prevent the action. 3. is not possible because it is faking user input.
