### ISSUE TITLE
Add Feature - Manual tally counters with customized naming

### ISSUE THREAD

**Issue by IAMGENTLY** [runelite/runelite#5608]
Can a developer please add this... Custom manual tally counters say starting at 0 and ending up to 9999 before reset  or so with adjustable increments of 0.1  or even decrements 

say i want a way to tally all my daily teleports  or any old thing from Random event well a manual way to tally such things could and would be useful

**Comment by deathbeam** [comment]
This will be useful like only for you, so just use external software for it.
