### ISSUE TITLE
Wilderness multy-single lines

### ISSUE THREAD

**Issue by pkermen** [runelite/runelite#5613]
Me and thousands of pkers would highly appreciate if you guys could make plugin that would show multi-single lines as white lines ingame.  Attached a photo as example what it could look like.
![multiline](https://user-images.githubusercontent.com/43535675/45944506-0cf2d880-bff3-11e8-8bd5-79b95db2674e.PNG)

**Comment by deathbeam** [comment]
We already have issue open for multi lines this is duplicate

**Comment by pkermen** [comment]
> We already have issue open for multi lines this is duplicate

My bad, didnt find it until now. Is there any chance it could be re-opened for other contributors? Looks like the contributor currently working on it don't really have time to work on it. (Based on the fact that he has been inactive past few months) Not trying to sound ungrateful or anything but just wondering if the eta is next summer or is it forgotten entirely.

**Comment by Unmoon** [comment]
What db said means there is an issue (as in, a feature request) like this already. The pull request is different and this would not be closed as a duplicate even if it was active.
