### ISSUE TITLE
Option to add a sky/fog

### ISSUE THREAD

**Issue by IamAPancake** [runelite/runelite#5616]
One of the biggest problems I have with OSRS is the black void constantly in the background. It is quite ugly to look at and even scares me a little bit for some reason lol.

A good solution to this could be to have something similar to OSBuddy, where the black has been replaced by a sky. Or another idea could be to have a fog. Or both as options?

This is the "black void" I'm referring to.
![runelite_2018-09-24_14-15-04](https://user-images.githubusercontent.com/37846618/45954185-3d8f3e00-c004-11e8-8c9f-83da4ae69398.png)

This is how OSBuddy resolves the issue. 
![image](https://user-images.githubusercontent.com/37846618/45954266-76c7ae00-c004-11e8-86ba-70eaf5f6be9e.png)

OSBuddy also increases the render distance which would also be nice for Runelite, but I believe the increased render distance is going to be implemented by Jagex eventually. However the black void is still going to be a problem, so I hope Runelite can add a Sky/Fog feature similar to OSBuddy.

**Comment by ltvill** [comment]
That's OSBuddy OpenGL. An official OpenGL version is coming to PC some time after the mobile release, then more options will be available.

**Comment by Abextm** [comment]
Duplicate #3941

**Comment by IamAPancake** [comment]
> Duplicate #3941

The duplicate you're referencing was ignored. Is this being worked on at all?

**Comment by raiyni** [comment]
no

**Comment by IamAPancake** [comment]
> no

cool, back to osbuddy for the time being then
