### ISSUE TITLE
Linux: Black bars

### ISSUE THREAD

**Issue by CTJansson** [runelite/runelite#5622]
**Describe the bug**
The buttons do highlight if I mouseover them, the runelite client also looks normal (working as intended) when it's out of focus (when window is not selected), but as soon as you mouseover any buttons on the right bar of runelite client the goes black around the runescape window.

**To Reproduce**
1. Linux Mint 19, Mesa 18.3 devel
2. Install RuneLite through the software manager
3. Launch the client
4. Mouseover the buttons in the right bar of the client and it should look something similar to the attached screenshots

**Expected behavior**
To not go black, all buttons should be visible and the window that opens when pressing a button.

**Screenshots**
![screenshot from 2018-09-24 18-09-19](https://user-images.githubusercontent.com/8863468/45965000-902e2180-c027-11e8-855a-a32a0e55d696.png)
![screenshot from 2018-09-24 18-10-33](https://user-images.githubusercontent.com/8863468/45965010-96240280-c027-11e8-9139-8c3f7f70e74a.png)

**Environment (please complete the following information):**
 - OS: Linux Mint 19
 - RuneLite version: 1.4.18
 - Launcher version: 1.6.0

**Additional context**
[application.log](https://github.com/runelite/runelite/files/2411695/application.log)
[launcher.log](https://github.com/runelite/runelite/files/2411696/launcher.log)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration if that do not helps also disable Custom window chrome in "RuneLite" settings in sidebar
