### ISSUE TITLE
Add farming harvest to loot tracker or perhaps a new section like the latter

### ISSUE THREAD

**Issue by sunset904** [runelite/runelite#5626]
Title, i think it would be a neat addition knowing how much gp is worth the entire harvest before selling it all to GE or just at least have a track of profit on a run

**Comment by Alexsuperfly** [comment]
click this button when you finish your farm run 

![](https://i.imgur.com/fPxjvFg.png)

**Comment by oplosthee** [comment]
I believe this is a duplicate of https://github.com/runelite/runelite/issues/5088 as well.

**Comment by deathbeam** [comment]
Duplicate of #5088
