### ISSUE TITLE
Show how much exp gained from raw materials while hovering in bank or invent

### ISSUE THREAD

**Issue by Cardman123** [runelite/runelite#5647]
Good day everyone.

My Request:  Show the amount of exp gained from raw materials while hovering in bank or invent.

For example: I have 50k raw sharks in my bank.  If i would hover the 50k sharks in my bank or invent it would show 10.5m exp on a little screen like the ge option.  

Thanks for reading

**Comment by ajbinky** [comment]
Pretty cool idea imo. For items with multiple related skills, would it just show all skills?

**Comment by Cardman1234** [comment]
Maybe can be put on a panel

**Comment by TheStonedTurtle** [comment]
I've been working on a Banked Xp calculator for a while now, if anyone is interested in working together hit me up.

Example of the current UI (still a W.I.P.): 
![](https://i.imgur.com/aIanQRi.png)

**Comment by raiyni** [comment]
This has been added as the external plugin `Banked Experience`
