### ISSUE TITLE
Loot tracker: Show how many times a drop was received

### ISSUE THREAD

**Issue by MajorAlt** [runelite/runelite#5649]
It would be convenient if the loot tracker showed how many times a particular drop was received. The loot tracker currently displays the cumulative quantity of item drops, which is fine if the monster always drops the same quantity of an item, but otherwise, you must go through each kill to see how many times that drop was received. This change would make it significantly more convenient to keep long-term track of kills and estimate drop rates.

Perhaps this number could be shown on the "Group loot by source" page via selection in the context menu, or by hovering over a stack, similar to how you would see the value of a stack you received.

Thanks for your consideration.

**Comment by psikoi** [comment]
This seems excessive

**Comment by deathbeam** [comment]
This seems like bad idea, there is enough data already displayed in the loot tracker, this seems like it could be simply displayed somewhere where the data will be processed, e.g on website if we will ever implement that
