### ISSUE TITLE
Notification when slayer task is complete

### ISSUE THREAD

**Issue by SRLJustin** [runelite/runelite#5652]
**Is your feature request related to a problem? Please describe.**
An add-on to the Slayer plugin to receive a notification (if enabled) when your slayer task is complete. Very useful for bursting tasks where the slayer tracker can fail to keep count if multiple targets are killed in the same tick

**Describe the solution you'd like**
A tickbox in the slayer plugin to enable/disable this feature

**Describe alternatives you've considered**
Using the Chat Notifications but failed

**Additional context**

**Comment by Alexsuperfly** [comment]
Use the Chat Notifications plugin to notify you on the task complete message.

**Comment by Reasel** [comment]
@Alexsuperfly I thought the Chat Notifications doesn't work with game messages...or am I reading the code wrong?

**Comment by Alexsuperfly** [comment]
i know it works for the untradeable drop notification, so i see no reason it wouldnt for task complete

**Comment by Reasel** [comment]
Then this is can be closed.
