### ISSUE TITLE
Left click fill rune pouches with new bank feature

### ISSUE THREAD

**Issue by NickThompson1993** [runelite/runelite#5668]
**Is your feature request related to a problem? Please describe.**
The new banking update allows you to fill rune pouches from within the banking interface with a right-click drop down menu, an option to set this to the default (left click) option would be helpful.

**Describe the solution you'd like**
An extra option in the "Menu Entry Swapper" configuration to set "Rune Pouches" as Left Click "Fill"

![rune pouch fill](https://user-images.githubusercontent.com/43541207/46144928-5c850e80-c256-11e8-8cc4-584efb4560ca.png)

**Comment by CakeWizard** [comment]
Yes please.

**Comment by Nightfirecat** [comment]
Based on a question asked in Q&A, it sounds very likely they will add shift+click filling/emptying while in the bank down the line. Hence, I don't think we should do this ourselves in the meantime.

**Comment by Majst** [comment]
Would love this

**Comment by GrimyPothead** [comment]
@forsco it's not a duplicate, i said "maintain functionality with all quantity set in bank" this was not stated here, check with your 2 eyes before you close threads.

**Comment by forsco** [comment]
> @forsco it's not a duplicate, i said "maintain functionality with all quantity set in bank" this was not stated here, check with your 2 eyes before you close threads.

I didn't close it, but you were asking for the fill option to be menu swapped which is a duplicate.

- maintain functionality with all quantity set in bank

is irrelevant because if we are swapping to fill that would be implemented anyway to prevent accidental deposit of your rune pouch using a different bank withdraw preset.

**Comment by thlisym** [comment]
Has this been decided on yet? Seems like it could deliver a lot of value even if in the longer term Jagex are planning on implementing this themselves?

cc @deathbeam @Adam-

**Comment by deathbeam** [comment]
I think simply the reason that this could increase exp rates if implemented should be good enough to just wait for Jagex to implement this by themselves.

**Comment by forsco** [comment]
I’m with Deathbeam on this. For the time being I agree that this shouldn’t be added to Runelite.

**Comment by Kamielvf** [comment]
Generally any swaps for items aside from the shift-click customization we already offer has been on the rejected list so I would not expect for this to ever make it into the client.

**Comment by thlisym** [comment]
That makes sense. Could we close this then?

**Comment by deathbeam** [comment]
Yeah, updated wiki here: https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features and closing this as wontfix until Jagex implements it by themselves

**Comment by dekvall** [comment]
Added in 4845560cb8f7b735ea4fd5ca0f8a0336d9f1d3b9
