### ISSUE TITLE
Notification for amulet of chemistry break

### ISSUE THREAD

**Issue by Majst** [runelite/runelite#5669]
**Describe the solution you'd like**
When your amulet of chemistry breaks while doing herblore, a notification similar to bird nest dropping since you can toggle to stop crafting potions when the amulet breaks. If you are tabbed the game will flash, etc.

**Comment by deathbeam** [comment]
Duplicate of #504

**Comment by Nightfirecat** [comment]
FYI, you can configure your Chat Notification plugin to notify you on the break text.
