### ISSUE TITLE
Swap Eat and use option on Caviar

### ISSUE THREAD

**Issue by BarbaricEmu** [runelite/runelite#5674]
**Is your feature request related to a problem? Please describe.**
Now that decanting into 2 dose potions is possible barbarian herblore is a viable training method (it is 1t and you can create potions just like darts essentially).  The current problem is that caviar has a left click eat option which means for every potion you make you have to right click and choose the use option

**Describe the solution you'd like**
Add an option in menu entry swapper for Caviar to swap the eat and use options

**Describe alternatives you've considered**
Could also swap the potions drink and use options but jagex might disagree with going this far

**Comment by deathbeam** [comment]
Use shift-click configuration and simply hold shift
