### ISSUE TITLE
Windows Styled Mouse Keys On Mac OS X

### ISSUE THREAD

**Issue by drmlkjr** [runelite/runelite#5678]
**Is your feature request related to a problem? Please describe.**
So for those who don't know, Mac Mouse Keys do not work in the same way that Windows Mouse Keys do.  On windows, the mouse moves in steps.  On Mac, the mouse 'slides' as you hold down the key.  Naturally this leads to issues with usability of Mac MK when doing anything involving predictable mouse movements.  I know OSB has 'windows styled mouse keys' on their client, wondering if it's possible here.  I've tried to talk to the Fox guy over in the OSB discord about it 2 years ago, but that didn't really go anywhere. 

**Describe the solution you'd like**
An on/off setting in Runelite  that allows for windows styled mouse keys, either on numpad only or remappable keys.  I would also say the custom distance the mouse moves would be nice.

**Describe alternatives you've considered**
Using a tool called Mousetools (http://www.hamsoftengineering.com/codeSharing/MouseTools/MouseTools.html)
I wrote my own set of Applescripts to make the mouse hop similar to windows, but when it comes to packing it up and distributing it I have no idea how.  I've been using Alfred to execute the scripts on key presses I assign, but they are all not attached random scripts that are iffy in performance.

**Additional context**
I work on a computer all day, and use a mouse a LOT already.  After years of this, certain methods of training in game have a big barrier to me.  Drop fishing, construction training, anything involving sporadic mouse movements / clicks constantly is pretty much no-go due to this.  For the most part I just do alternative training methods, but Construction is something I can't get around.  At least for me this would be a game changer.

**Comment by Nightfirecat** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#not-currently-being-considered

> * Mouse Keys: You may only use your operating system's official default mouse keys program. (see [Jagex Statement](https://services.runescape.com/m=news/mouse-keys---changes--clarification?oldschool=1))

**Comment by drmlkjr** [comment]
Ah I missed that, my bad.
