### ISSUE TITLE
Discord Integration shows "Exploring: Entrana Dungeon" when in Taverly Dungeon Black Demon area

### ISSUE THREAD

**Issue by bigblock111** [runelite/runelite#5680]
**Describe the bug**

The Discord integration shows that the player is "Exploring: Entrana Dungeon" when they are in Taverly Dungeon's Black Demon area. I imagine this is likely the case as the black demon area is within the square likely made around Entrana dungeon for the integration

**To Reproduce**

1. Go to Taverly Dungeon's Black Demon area
2. See error in Discord

**Expected behavior**

Discord integration should display: "Exploring: Taverly Dungeon", as shown in the rest of the dungeon.

**Screenshots**

![Discord](https://i.imgur.com/yaceu3K.png)
![Map](https://i.imgur.com/ecZcQnR.png)

**Environment (please complete the following information):**
 - OS: Windows 7 Home Premium
 - RuneLite version: 1.4.19
 - Launcher version: "Unknown"

**Comment by deathbeam** [comment]
Looks like this is happening because the regions overlap, so removed the good for first contribution label as it is not so trivial to solve

**Comment by Hydrox6** [comment]
This was fixed in #12377 by just outright removing Entrana Dungeon as a possibility. Given that Entrana Dungeon is only needed for a relatively short part of a quest, having it show up as Taverly Dungeon isn't *the worst* solution
