### ISSUE TITLE
Restore ignore list icon on classic interface styles

### ISSUE THREAD

**Issue by Revnov** [runelite/runelite#5690]
The Account Management tab has replaced the Ignore List tab on the default client. This affects the 2005 and 2010 interface styles and the new icon is out of place. Would like to see this change reverted or the Account Management tab moved to be accessed from within the Settings tab. I'd be happy if the icons were just switched out as this point since both tabs are useless.

Probably worth waiting until the next Q&A on 10/3/18 to see if this gets addressed since Ayiza mentioned he would like to see this update be toggleable but doesn't know how possible it is. 
Source: https://www.reddit.com/r/2007scape/comments/9jkc92/just_saying/e6sb0zm/

**Comment by Nightfirecat** [comment]
We're not planning on removing/changing the icon behavior. If the account management tab isn't toggleable in the future via ingame settings, we could look into using community-created icons for the 2005/2010 styles to represent that tab.

**Comment by Paradoxis** [comment]
@Nightfirecat can't it just display the old ignore list icon, but keep the functionality of the account management tab? Would really help to retain the the nostalgic feel of the 2005 layout

**Comment by raiyni** [comment]
I disagree with that statement. That would hide the intentions of the tab because it no longer is an ignore list tab.

**Comment by troypressley1** [comment]
I would love the option to restore the Ignore list icon

**Comment by deathbeam** [comment]
We are not going to restore ignore list icon, as it is different interface now. If you want more old-school icon for 2005 style or something via interface styles, open up separate issue

**Comment by Paradoxis** [comment]
@deathbeam could you maybe point at how the current interface icons are replaced so I can create my own plugin to do this? 

I understand it won’t be added here but I’m having issues figuring out where the assets are replaced

**Comment by deathbeam** [comment]
InterfaceStylesPlugin, after reading the code it should be pretty straightforward to use, just replace one sprite with another
