### ISSUE TITLE
Menu Entry Swapper extra feautres

### ISSUE THREAD

**Issue by Miickey564** [runelite/runelite#5692]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Currently doing lavas, I would like to one click teleport with my cape, and left click wear dueling rings, currently after a ring breaks I disable and reenable the plugin to get around it, but its quite annoying.
**Describe the solution you'd like**
The ability to have cape left click teleport separate to ring teleport. I.E Be able to left click teleport on crafting cape and still left click wear a dueling ring.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by raiyni** [comment]
Use shift click configure

**Comment by deathbeam** [comment]
We are not going to swap stuff in equipment window, and for rest use shift-click config.
