### ISSUE TITLE
Add barrows color chooser for chest value chat notification.

### ISSUE THREAD

**Issue by godnabes** [runelite/runelite#5693]
I've been doing barrows for the first time ever recently, and i find it hard to read what my chest was worth each time i looted, I thought it would be cool if we had the ability to change the chat value notification.
![runelite req 1](https://user-images.githubusercontent.com/28495629/46234501-7cd2cd00-c32b-11e8-9077-26d967bd8005.png)

**Comment by deathbeam** [comment]
I think you can change it already in chat colors configuration

**Comment by deathbeam** [comment]
Yes you can check Game highlight color or something

**Comment by CakeWizard** [comment]
Should be under Chat Color options, you'll have to experiment to find which one it is though.
