### ISSUE TITLE
General manual ticker/counter

### ISSUE THREAD

**Issue by CakeWizard** [runelite/runelite#5698]
An example of where this would be useful is at pest control to track how many successful runs you've had as a motivator and to see how many you have left for void. Ideally this counter would be persistent across application restarts, with a reset button when you are finished.

**Comment by deathbeam** [comment]
Just use Notes plugin or other software made for this

**Comment by CakeWizard** [comment]
> Just use Notes plugin or other software made for this

Trying to keep a counter in the Notes plugin would be a painful experience, and the whole point of me requesting this is so that it's something built-in to the client. I believe this is something standard to most osrs clients so it's confounding that it's not already implemented.
