### ISSUE TITLE
Can't log in on the client

### ISSUE THREAD

**Issue by R2KUM** [runelite/runelite#5699]
**Describe the bug**
When I try to log on, the whole client freezes and then closes. I uninstall the client and re download it, but it keeps doing it. 

**Environment (please complete the following information):**
 - Windows

**Comment by ftbcoders** [comment]
Same issue. Windows 64 bit. working on my brothers PC but not mine. Deleted cache, still not working. reinstalled twice.

**Comment by deathbeam** [comment]
Duplicate of #5675
