### ISSUE TITLE
Screenshot when your hp goes to 0

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#5707]
To be clear, not a screenshot after you've died in the spawn area but when ur hp goes to 0 ingame.

Purposes:
When you go afk wondering how you died. 

More screens of hcim dying which is always fun.

Maybe disabled in some minigames where dying is common.

**Comment by CakeWizard** [comment]
In addition it would aid in quick resupply/rearmament as well which is a big plus. I usually take screenshots before I head into the wilderness or anywhere I might die where I can't recover my items, but this solution would make forgetting irrelevant.
