### ISSUE TITLE
Loot tracker caps coin picking up at 16-bits (65535).

### ISSUE THREAD

**Issue by Shibalicious** [runelite/runelite#5709]
When picking up coinstacks > 65535, loot-tracker will only register 65535. I PK'ed 24m cashstack and Runelite's loot-tracker only registered 65535 (I was using Looting Bag in case it matters).

**To Reproduce**
1. Enable loot-tracker.
2. PK someone with a 100k cashstack.
3. Pick it up.
4. See the loot-trackers log.

**Expected behavior**
A correct amount would be expected to have been displayed.

**Screenshots**
[https://imgur.com/C0XNgkb](url). The last track only shows 9.66m when the full PK'ed amount was 34m.

**Environment:**
 - OS: Windows 7 Ultimate
 - RuneLite version: 1.4.19
 - Launcher version: 1.6.0

**Comment by Alexsuperfly** [comment]
thats a jagex bug, its the highest number they supply, so its the highest we can track

**Comment by Adam-** [comment]
This is not really a Jagex "bug" it is just a limitation of the protocol which we cannot work around.

**Comment by psikoi** [comment]
Going hard on those glory loots
