### ISSUE TITLE
Give Teleport item Its own options in Menu Entry Swapper

### ISSUE THREAD

**Issue by rogierdevries** [runelite/runelite#5728]
For example. i like to use me crafting cape to be a one-click teleport, however i dont want to one-click rub on my glory, this would be useful for people who only want to swap specific teleport items.

Thank you.

**Comment by deathbeam** [comment]
Use shift-click configuration (https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper)

**Comment by rogierdevries** [comment]
that defeats the purpose of having a oneclick teleport imo.
