### ISSUE TITLE
Vorkath attack counter

### ISSUE THREAD

**Issue by runelite-is-fun** [runelite/runelite#5769]
We need a Vorkath attack counter above its head every 6 normal hits similar to the counter for demonic gorillas to better anticipate when the next special attack is coming.
-------------------------------------------------------------------------------------------------------------------
Info explaining the mechanics from wiki:

- Occasionally (after six normal/dragonfire attacks), he will use one of two special attacks and alternate between them:

- Freezing the player in place and summoning a Zombified Spawn that will approach the player and explode violently if not killed, resulting in up to 60 damage
- Launching acid pools around the area and rapidly spitting fireballs at the player that must be dodged or they will deal high damage very quickly

Pros
-------------------------------------------------------------------------------------------------------------------
- everyone who kills vorkath will use it
- wont have to count to 6 in my head ever again

Cons
-------------------------------------------------------------------------------------------------------------------
- literally none this is a buff if anything

**Comment by deathbeam** [comment]
We need less duplicates, and this is duplicate
