### ISSUE TITLE
Adding Ultimate Force Support to NMZ Plugin

### ISSUE THREAD

**Issue by EZScape** [runelite/runelite#5787]
**Is your feature request related to a problem? Please describe.**
Despite what most guides tell you in saying Ultimate force is not useful, it actually is for slayer. If you have a troll or black demon task you can afk it in NMZ. Ultimate force is helpful in the fact that it will kill the monsters for you yet still grant slayer xp, and if there is no slayer monster spawned you can clear all of the current ones out in hopes to spawn one.

**Describe the solution you'd like**
A checkmark added for ultimate force powerup that works the same as the others, can be defaulted to disabled since it's not a very popular powerup.

**Comment by trimbe** [comment]
You can use the Chat Notifications plugin to achieve the same effect.
