### ISSUE TITLE
Menu-Entry swap for runecrafting altars

### ISSUE THREAD

**Issue by p0tata** [runelite/runelite#5791]
I accidentally craft fire runes pretty frequently when doing Lava rune crafting, so hiding that option would help a lot to stop making that mistake.

I think adding a menu entry swap option for it would be great, as it would just make you walk to the altar rather than craft the fire runes.

I have tried making it myself, but my knowledge of Java is very limited and I did not get very far. It showed up in the menu for menu-entry swapping, but I could not get anything in-game to change.

**Comment by deathbeam** [comment]
Duplicate of #4960
