### ISSUE TITLE
Hide attack styles overlay unless on warned style

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#5794]
**Is your feature request related to a problem? Please describe.**
Usually when using the attack styles plugin, I'm most interested in hiding attack styles that I don't want to use. I don't need or want to see the attack style overlay unless I'm using a style that's hidden.

**Describe the solution you'd like**
Add a toggle to show the overlay only when using a hidden style.

**Comment by forsco** [comment]
This is achievable by having your settings configured as per

![notes marker](https://lambda.sx/uO0.gif)

**Comment by Nightfirecat** [comment]
Clearly I didn't read through the settings enough.

**Comment by deathbeam** [comment]
Maybe always show style should be disabled by default
