### ISSUE TITLE
Add Mage Arena 2 hot/cold finder

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#5795]
**Describe the solution you'd like**
A hot-cold clue style finder for the Mage Arena 2 miniquest (and afterwards)

**Comment by unmrshl** [comment]
I'd like to pick this up. Gonna take a bit of research.

**Comment by Nightfirecat** [comment]
I'd imagine the code could be extracted out of the clue scroll plugin to some common location, then it would be significantly less work, just some research on the demon spawn locations. (those are pretty well documented on the wiki)

**Comment by Nightfirecat** [comment]
This has been added to the Quest Helper hub plugin. I don't know for sure that it works after the mini-quest has been completed, but I'm sure it wouldn't be too much work for that to be added if it's not added already. Hence, I'm closing this issue.
