### ISSUE TITLE
Approach for menu entry swapping / removing

### ISSUE THREAD

**Issue by XrioBtw** [runelite/runelite#580]
Menu entry swapping / removing is a highly requested, but also slightly controversial topic. Therefore, I think we need to define some guidelines for what we can do and what we can't do.
- Should we swap or remove unwanted menu entries?
- Should we pre-define which menu entries you can swap / remove, or should we let the user decide this in the plugin config (e.g. option: "Bank", target: "Banker")?
- Should menu entry swapping / removing be able to adjust to what you are doing (e.g. swap / remove the "correct" entry when using a staircase to allow left-clicking)?

P.S:
OSB Matthew has said that Jagex does not want any menu entry swapping that can give increased xp rates. Therefore, OSBuddy has a 1 tick delay on left-click use bones on altar.

**Comment by ShaunDreclin** [comment]
related to #374 and #447

**Comment by ShaunDreclin** [comment]
My opinions:
- Swapping the order is better than removing, it's really only the left-click option that matters.
- User-defined menus would be too abusable, adding stuff like OSB's delay on bones is important.
- Yes, this is very useful! Unless Jagex specifically says no to context-aware menus, let's do it.

**Comment by Adam-** [comment]
Done in #627
