### ISSUE TITLE
"Burthorpe" misspelled on Discord Rich presence in Burthrope Games Room

### ISSUE THREAD

**Issue by ScuzzyBeta** [runelite/runelite#5802]
"Burthorpe" is misspelled as "Burthope" in Discord's rich precense
**To Reproduce**
1. Go to Burthorpe Games Room in game
2. Click on your discord name if you have it displayed
3. Burthorpe is spelled wrong

**Screenshots**
https://i.imgur.com/M8cIrDh.png

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - RuneLite version: 1.4.20
 - Launcher version: 1.6.0

**Comment by ScuzzyBeta** [comment]
I don't know if you got this but it was misspelled when in the Burthorpe Games Room as well, same misspelling

**Comment by forsco** [comment]
I’ll double check this when I get home

**Comment by deathbeam** [comment]
Probably should've mentioned that in original issue @ScuzzyBeta :d I will reopen the issue and edit the description then

**Comment by ScuzzyBeta** [comment]
@deathbeam Sorry about that, I didn't even notice it until it was already closed. Thanks again.
