### ISSUE TITLE
feature-request NPC Tagging

### ISSUE THREAD

**Issue by alex-vincent** [runelite/runelite#581]
Plugin that can outline selected npcs, very useful for chin hunting

**Comment by McSwindler** [comment]
I've got a question about how you want to select the NPCs.
Are you wanting the ability to right-click -> 'tag' a specific NPC and it will only outline that single NPC?
Or, are you wanting something where you can enter an NPC name and all NPCs with that name will be outlined?

**Comment by Adam-** [comment]
Done in #939
