### ISSUE TITLE
Discord Rich Integration: Display what you are slaying instead of 'exploring x'

### ISSUE THREAD

**Issue by Veeeeeeeee** [runelite/runelite#5815]
Apologies if this has already been requested, I've searched for this request and can't find anything similar to what I'm requesting.

I would like it to display what slayer task I am killing instead of "Location: x" or "Exploring x". For example;

RuneLite
Slaying Gargoyles
Training: Slayer
x:x elapsed.

Or if the user has disabled the time elapsed, it can also add an additional line showing how many is left to kill.

RuneLite
Slaying Gargoyles
38 Left
Training: Slayer

**Comment by deathbeam** [comment]
There is no space left in the discord rich presence, and location is more interesting than task
