### ISSUE TITLE
Opponent Info Freeze Timer

### ISSUE THREAD

**Issue by SamuraiMugen** [runelite/runelite#5821]
This would be a great feature to Runelite and i'm sure that many other players feel the same way. Exilent is the only client that has this, and is not nearly as trust worthy as Runelite.

**Comment by Nightfirecat** [comment]
This is a duplicate

**Comment by SamuraiMugen** [comment]
Ah, sorry I didn't know. Do you know if it is being worked on? I'm very interested in this. and can delete this or whatever.
