### ISSUE TITLE
Multiple Tabs for Notes

### ISSUE THREAD

**Issue by OffensiveExile** [runelite/runelite#5822]
**Is your feature request related to a problem? Please describe.**
I frequently find myself scrolling up and down to find a specific line of text in my Notes page and this is quite frustrating.

**Describe the solution you'd like**
By introducing "Multiple Tabs for Notes", you can allow the users to organise their Notes in whatever order they decide. For example, I can have a note for "Goals", "Farming", "Slayer" or just "Bosses".

**Describe alternatives you've considered**
An alternative would be to just have multiple "Notes" buttons in the available list where the current "Notes" button is.

**Comment by deathbeam** [comment]
The notes plugin is supposed to be very simple way to just store arbitrary text, for more advanced editor features you are supposed to use actual text editors.
