### ISSUE TITLE
Suggestion: a toggle to hide ground items, as in making them hidden.

### ISSUE THREAD

**Issue by freminik** [runelite/runelite#5837]
This would be a great feature, especially when doing skilling tasks such as woodcutting, this way you wont accidentally press a log that is on the ground and pick it up when 2t woodcutting at teaks. This could also be a nice feature for pvp, hiding empty vials etc.

Suggestion is to completely hide items, this is a toggle that you can turn on when skilling. Example: Hide logs or such. Similar to the ground item list, except that its the item that gets hidden instead of only the text.

Thanks

**Comment by Nightfirecat** [comment]
This is a [rejected feature](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping):

> * `Hide/reorder ground items`: This would make it so that all items on your hidden items list in grounditems would not show the take option. This would push the meta on many things and would make looting too easy. As such it is not going to be added.
