### ISSUE TITLE
Add buy limit for cavalier hats to GE plugin (it is 4)

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#5838]
I instabought 4 on one accounts, and instabought another 4 on another account.

**Comment by fatfingers23** [comment]
Hey can i get some confirmation from some that this is held under "ge_limits.json" and that there is no automatic way to add to this list? Just people manually adding to it? If so, i'm going look at adding a way to automatically update this json file.

**Comment by fatfingers23** [comment]
Ah i come from RS3 but love open source and runescape so i wanted to help out, didn't realize the os wiki didn't have as many buy limits on it :(. Manually added the numbers supplied here and tested it and did a pull request #5855.

**Comment by Nightfirecat** [comment]
Most of these are collected from a number of sources, and we're not pulling dynamic values since those could be tampered with.
