### ISSUE TITLE
configure shift click for all right-clickable things outside of inventory

### ISSUE THREAD

**Issue by eggbrow** [runelite/runelite#5839]
This would be a powerful tool that essentially allows player to set their own menu entry swappers (MES) with shift-left click on obscure objects or NPCs that probably wouldn't have a place in the MES menu.

This might be considered over elaborate but would save having to manually add more npcs and objects into the menu entry swapper menu.

**Comment by deathbeam** [comment]
And exactly for a reason you just described this is not going to be implemented (it will also allow multiple rejected features to exist: https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features)

**Comment by eggbrow** [comment]
Do you expect the menu entry swapper to continue receiving additions indefinitely. List might need categorisation at some point if it becomes really long. Would be useful to add more of a variety of ueful things to the MES settings to fill in gaps. Especially as it has not received any additions for a while (which are needed if you are going to disregard this request).

Heres an idea of the possible additions that might be wanted:
shift left click on construction build objects for 'remove' and 'build'
shift left click on rogues chest to search for traps
shift left click trade or charter on npcs that haven't been added

dozens or scores more obscure objects and npcs that this would make a huge impact on for players.

**Comment by raiyni** [comment]
`shift left click on construction build objects for 'remove' and 'build'`

Has been rejected.
