### ISSUE TITLE
Ancient shard has (0 ea) next to it in the examine

### ISSUE THREAD

**Issue by granpawalton** [runelite/runelite#5841]
When examined the ancient shard with 2 of them reads "Price of 2 x ancient shard: (0 ea) HA value 288 (144 ea)"

![untradeable ge each](https://user-images.githubusercontent.com/36310010/46565807-70291880-c8d9-11e8-8b8d-186166148b1f.PNG)

There typically inst a GE value next to untradables but having multiple could be producing this 

 - OS: Windows
 - RuneLite version: 1.4.20
 - Launcher version: 1.6.0

I don't know this code base but this could be a potential good first issue?

**Comment by Alexsuperfly** [comment]
this was added in #5850
