### ISSUE TITLE
WASD-camera button stuck if held during loading

### ISSUE THREAD

**Issue by Tobi1202** [runelite/runelite#5849]
**Describe the bug**
When loading happens for either teleport or procedural world generation the held WASD-button is stuck and needs to be pressed again in order to release, else the camera keeps spinning.

**To Reproduce**
1. Enable WASD Camera
2. Hold down W/A/S/D
3. Teleport to house & release key
4. See bug

**Expected behavior**
The button is released and the camera doesn't move

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.20
 - Launcher version: "Unknown"

**Comment by Karolcz125** [comment]
Could you post a gif of this bug? Seems like I cant reproduce it

**Comment by FrozenPigs** [comment]
I cannot replicate this either, the only way I've seen it happen is when going into the grand exchange buy interface while having a direction held.

**Comment by Tobi1202** [comment]
I have not been able to reproduce this issue since reporting it.
At the time of reporting it the bug occurred multiple times each session.
I will open another issue if I find a more solid way to reproduce it

**Comment by rolzy** [comment]
I have seen this error too. It happens frequently when I teleport while holding down WASD. 

My Environment:
Windows 10
RuneLite version: 1.4.21
Launcher version: 1.6.0
