### ISSUE TITLE
Kourend Library Plugin - No longer working

### ISSUE THREAD

**Issue by majora2007** [runelite/runelite#5854]
**Description**
The Kourend Library Plugin overlays for books and dark manuals no longer show. This started at least a week ago. 

**To Reproduce**
1. Go to Arceuus Library
2. Turn on Kourend Library Plugin
3. Notice no overlay present

**Expected behavior**
Expecting to see book names and Dark Manuscripts on the overlay.

**Screenshots**
This is if the plugin was activated before the version that broke it:
![image](https://user-images.githubusercontent.com/735851/46575556-dc108d00-c97c-11e8-8ef0-982dd76b82d7.png)
This is it after toggling on/off:
![image](https://user-images.githubusercontent.com/735851/46575583-a6b86f00-c97d-11e8-8c43-be721a63aca4.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.20
 - Launcher version: 1.6.0

**Logs:**
https://pastebin.com/Smix2MxH

**Comment by raiyni** [comment]
you have to search a bookcase

**Comment by majora2007** [comment]
@raiyni I just searched, the blank squares came back up, the logs have this in them:
2018-10-06 15:31:21 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.account.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@15d5b0dd opened
2018-10-06 15:37:48 [Thread-7] INFO  n.r.c.plugins.kourendlibrary.Library - Setting bookcase [89] to null

**Comment by raiyni** [comment]
Find a book.

**Comment by majora2007** [comment]
You're right, once I found a book it worked. Sorry, last time I used this it had all books. I'll close the defect. Thanks for the help.
