### ISSUE TITLE
OSBuddy Actively traded price appears multiple time if a hiscore lookup is submitted before display

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#5858]
**Describe the bug**
If a hiscore lookup is initiated (say, by accidentally double-clicking a grand exchange item while searching and clicking a player's chat entry) before the "OSBuddy Actively traded price" is displayed, it will be delayed until completion of the hiscore lookup, and will display multiple times.

**To Reproduce**
1. Enter the "Choose an item" buy item search screen, search for any item
2. Quickly click on the item and on a chat line after the widget changes back to the normal chat widget
3. See error (see gif at bottom of post)

**Expected behavior**
Hiscore lookup and osbuddy price lookup are performed in parallel, and do not cause adverse effects

**Actual behavior**
OSBuddy price lookup is paused while hiscore lookup occurs, results show multiple times after the hiscore lookup completes

**Screenshots**
![osbuddy actively traded price display bug](https://user-images.githubusercontent.com/2199511/46578989-4b2bc700-c9f9-11e8-81a8-33faaf86ccdb.gif)

**Comment by Karolcz125** [comment]
Gonna take care of it
