### ISSUE TITLE
Linux installation experience is not user friendly

### ISSUE THREAD

**Issue by JackRhodes** [runelite/runelite#5861]
Currently to install Runelite on Linux you have to download the JAR file manually. You are then required to install the java runtime, and every time you wish to run Runelite you have to run the .jar file via the terminal using "java -jar runelitefile.jar" or manually perform numerous manual steps to set the jar to executable and add it to your desktop/ favourites.

This is not very user friendly, and there is currently no guidance on the RuneLite website on how to do this, I had to search numerous reddit threads to find out how to do this.

I propose that Runelite should be packaged in a way to allow a once click install experience, for example via a .deb file or added to a package management repository. Or at least provide some official documentation on the installation page to detail how to run the application.

**Comment by Karolcz125** [comment]
### RuneLite.sh
```shell
#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
echo $DIR
java -jar $DIR/RuneLite.jar
```
Just place this script in the same folder as your jar, mark it as executable and make a link to this script (for example from your desktop)

**Comment by deathbeam** [comment]
You should open this issue in runelite/launcher repository, it is not related to runelite client
