### ISSUE TITLE
Resize Infobars

### ISSUE THREAD

**Issue by MrsDoggy** [runelite/runelite#5869]
For the resizing of the info bars I don't understand how it works? am I doing something wrong?
Whenever I go to move the InfoBar It allows me but I have no clue how to change the size of them. I press alt and go around the edges but nothing seems to do the trick.

What it looks like for me:
https://gyazo.com/887fd41d29a5fe0d40a684eeb80cd933

**Comment by Nightfirecat** [comment]
That feature has not been added yet.

https://github.com/runelite/runelite/pull/4509

**Comment by deathbeam** [comment]
You can resize the infoboxes in RuneLite settings via option, what you are describing has not been implemented yet and we already have issue and PR open for it
