### ISSUE TITLE
Toggle option for total level affected by virtual level

### ISSUE THREAD

**Issue by nathan122696** [runelite/runelite#5878]
Currently the virtual level plugin also adds them to your total level, is there any way to add a toggle option so it does not change that? 
![virtual on](https://user-images.githubusercontent.com/40904161/46621679-1b161e00-caf6-11e8-9802-187ee5ebcecf.PNG)
![virtual on1](https://user-images.githubusercontent.com/40904161/46621688-1d787800-caf6-11e8-98f4-812678555a7a.PNG)

**Comment by Smeety** [comment]
Support

**Comment by Joniiiiii** [comment]
support

**Comment by AbdelelKharbachi** [comment]
Support!
