### ISSUE TITLE
Add fight caves next wave display

### ISSUE THREAD

**Issue by swordsith** [runelite/runelite#5885]
**A clear and concise description of what the problem is:** 

Whilst doing fight caves I would like to highlight / select text in the notes panel to look back at what wave i'm on, but when clicking back on the game the text I had highlighted would go back to how it is normally. 

**A clear and concise description of what you want to happen.**

To be able to click back on the game and have the text I had highlighted to stay that way, or to be able to style the text so that it could be picked out from the other text in the notes panel.

**A clear and concise description of any alternative solutions or features you've considered.**

A wave counter showing the enemies and the remaining left similar to the slayer plugin for the Inferno/Fight caves, possibly even showing the upcoming wave and the prayer that may be needed, which could also show recommended kill order.

n/a

**Comment by TylerNichols** [comment]
I don't think inferno plugins are being considered.

**Comment by swordsith** [comment]
> I don't think inferno plugins are being considered.

Just a suggestion, this idea was mostly for fight caves but I knew the inferno was wave based so I threw it in there.

**Comment by Nightfirecat** [comment]
Inferno plugins will not be released with Runelite. As for a fight caves wave display, there is a PR open in #3356, but hasn't been updated in some time.

**Comment by Nightfirecat** [comment]
For now, this should probably stand as the de-facto "fight caves wave overlay" request.

**Comment by deathbeam** [comment]
Updated the title to be just Fight caves wave display request
