### ISSUE TITLE
[Feature Request/Bug] Scroll to Zoom

### ISSUE THREAD

**Issue by GrimWrath** [runelite/runelite#5904]
Currently, when you try to change your windows scroll settings to be able to scroll more or less per scrolling "click", it is not reflected in Runelite or OSRS's scroll to zoom feature. Not sure if this is a RL or OS issue.

Would like to be able to either make RL read the system scroll settings or have its own zoom scroll settings to be able to change scroll speed.

**Comment by deathbeam** [comment]
This sounds like jagex issue.

**Comment by abextm** [comment]
#9035
