### ISSUE TITLE
Stretched Resizable Mode

### ISSUE THREAD

**Issue by AnotherJellyfish** [runelite/runelite#5918]
Just as fixed mode has a stretched mode (Stretched Fixed Mode in the Runelite options menu), where some horizontal & some vertical lines are doubled to give the game the effect of being larger, and if done on an integer scale, 2x or beyond scaled. Stretched resizable mode would do the same thing except with resizable mode.

Why? 

- This allows the UI to be "scaled" being more comfortable for some users. Eg. I'm used to stretched fixed mode's speed when turning the camera with middle mouse button which has a way slower sensitivity than regular resizeable mode
- This would also allow for less clipping of terrain which happens in fixed mode. 
- A more "clean" UI. More efficient use of game space 
- In effect, a "scaled UI" that Jagex was working on years ago and never got around to officially implementing. 

I'd also like to preface the rest of this with: I checked the to see if there were any completely similar suggestions. While #4769 and others were closed because they were recommended they use dpi scaling, this isn't a real solution to me because while it does scale the game, it also scales the Runelite UI, leading to a lessened experience than an official implementation. I could not find any other suggestions that were the exact same as mine.

![fixed stretched](https://user-images.githubusercontent.com/44043092/46774022-58350880-ccce-11e8-8c3b-cf31e4d66c68.png)
As you can see in this image, when using integer scale and using stretched fixed mode the game doesn't use all of the available screen. This is as intended and working perfectly if the user doesn't want to distort their game in any way. But this still leads to there being "wasted space" surrounding the game.

Here is a photo manipulated mock up of what this might look like when implemented:
![resizeable stretched concept](https://user-images.githubusercontent.com/44043092/46773881-ae557c00-cccd-11e8-9ead-74e7ae9e5197.png)

Here is what resizable mode normally looks like:
![08jrf5v](https://user-images.githubusercontent.com/44043092/46774851-874d7900-ccd2-11e8-9e37-403fa61dcec7.png)

This mock up was just created by taking my [available screen real estate](https://i.imgur.com/rDXqlcn.png) (1642 x 1057) when accounting for the runelite panel (which I always have open) and dividing this number by half, (821x528.5) [then resizing my game to create an image this size](https://i.imgur.com/y8kvSQD.png). And finally just taking this image and scaling it 2x to fit the space.

So stretched resizable mode would work as so: Calculate the available screen real estate the user has (the area beside the panel), divide by 2, and set that as the client size, then scale that image 2x. Or if the user wants, 3x, 4x, etc.

**Comment by devLotto** [comment]
Made a thing: https://www.youtube.com/watch?v=pdCwzXRd6U4
