### ISSUE TITLE
Skills Bars [feature-request]

### ISSUE THREAD

**Issue by Aidan402** [runelite/runelite#5919]
Having to put my mouse over each skill every time I do a task to check how much experience I need or to see if I'm close to levelling up gets tiring after awhile. Skill bars that show the level of a skill and progress on the side would make it so that you could quickly glance at them and be able to identify everything you need to know without breaking away from the task in progress.

**Comment by troypressley1** [comment]
There's a progress bar built into the vanilla client. Right click the xp drop icon

**Comment by deathbeam** [comment]
There are XP globes, XP tracker sidebar, vanilla progress bar. I believe this is already well covered.
