### ISSUE TITLE
Current World Overlay

### ISSUE THREAD

**Issue by devOSRS** [runelite/runelite#5920]
**Feature Request**
Show current world somewhere on the main screen/overlay.

Once solution could be to put it on top of the world map orb.
<img width="50" alt="screen shot 2018-10-11 at 1 05 38 am" src="https://user-images.githubusercontent.com/38792370/46789858-6c8afc80-ccf2-11e8-8f2e-f47978cf8ada.png">

**Comment by deathbeam** [comment]
How is this useful when you can already see current world in world hopper, and also in sidebar i believe

**Comment by devOSRS** [comment]
To tell your friends via voice chat your world immediately. 

It's annoying having to remember before hopping, opening your friends list, or opening sidebar/in-game world hopper where you might have scrolled around the list of worlds and no longer see the world immediately.

**Comment by Hydrox6** [comment]
This can now be done with the `Current World` hub plugin
