### ISSUE TITLE
Add default zoom cap for the new zoom update

### ISSUE THREAD

**Issue by GrimyPothead** [runelite/runelite#5930]
**Is your feature request related to a problem? Please describe.**
Alot of players are used to having their zoom at a set default level and don't want to accidentally zoom out while in combat making you misclick or even die. My suggestion is to add an option to CAP the current zoom to the previous default settings, as of right now you can only right click on the menu to put it back to default but its not a CAP like it should be.

**Describe the solution you'd like**
zoom capped to the previous default zoom setting so players don't get confused

**Additional context**
I feel like this problem will only get worse as time goes on, im just the first one to actually notice and say something about it.

**Comment by Aborts** [comment]
Add an option for the default, and add an option to make your own custom zoom cap.  i like being able to zoom out just a little past the old default zoom cap.  but i can barley see my character now when i’m zoomed all the way out 😪😅

**Comment by Vikerules** [comment]
yes please god, i was happy with the default max zoom the default game had, every time i wanted to zoom out i just scrolled back the mousewheel real fast in one motion to get max zoom. now it goes out way too far. what a horrible update from jamflex, shouldve just let it be on 3rd party clients instead

**Comment by kingjasko** [comment]
I have a bit different problem.. When I enable the camera zoom feature, it will not let me scroll past the max zoom of the game anymore, after the update.. On the other hand, it WILL let me zoom further in if I enable the "expand inner zoom limit"

**Comment by Adam-** [comment]
The outer limit was made configurable in #6591
