### ISSUE TITLE
RuneLite Weird Glitch 

### ISSUE THREAD

**Issue by wh0watme** [runelite/runelite#5932]
Greetings,

I am trying to use RuneLite Client on my Debian OS computer and whenever I load up the Runelite.jar something odd tends to happen. It loads perfectly fine and I get the shell but OSRS looks like its running but in tiles? Its extremely odd. Im not too sure of a fix. Ive tried reinstalling, Ill post a picture. If anyone has any clue Id appreciate any help!

![screenshot at 2018-10-11 11-43-59](https://user-images.githubusercontent.com/22081250/46816499-b56aa180-cd42-11e8-919b-5bdb4a209246.png)

**Comment by Kamielvf** [comment]
Follow [this](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration) solution
