### ISSUE TITLE
Add 4 Fairy Ring codes to the Hard Clue step to get to Fairy Resistance Hideout

### ISSUE THREAD

**Issue by bloodred** [runelite/runelite#5937]
https://oldschool.runescape.wiki/w/Fairy_Queen

A hard clue step involves talking to the Fairy Queen at the Fairy Resistance Hideout and to get there you need to input 4 codes into a Fairy Ring. Whenever I get this clue I have to look up what the 4 codes are and it would be really helpful to put these 4 codes onto the tooltip.

air
dlr
djq
ajs

**Comment by trimbe** [comment]
Scroll to the bottom of the destinations list, if you keep clicking the fairy ring hideout entry, you'll input the codes automatically.

**Comment by deathbeam** [comment]
Yeah this is already vanilla feature
