### ISSUE TITLE
Easier Item Tagging

### ISSUE THREAD

**Issue by Quoze** [runelite/runelite#5941]
At the moment tagging a lot of items in the bank can be long and tedious, so I would love to see a feature that could make this a lot more pleasant.

There could be a feature where you could right click an already existing bank 'tag tab' (which we will have created with the newest runelite feature) and choose 'edit selected items'. This would enable us to scroll through our bank (unedited via searching) and see each of the tagged items highlighted with a yellow circle or something. Then, we can left click an item to either tag or un-tag them with the selected tag.

This is a super brief idea to help speed up the process of tagging items in our bank and utilise the newest runelite feature conveniently, I'm sure you guys can make something great out of this.

Thanks for reading (=

**Comment by deathbeam** [comment]
Use bank tags properly: https://github.com/runelite/runelite/wiki/Bank-Tags

**Comment by Quoze** [comment]
I was suggesting that instead of having to write 'nmz' to 20 different items, you could set up something to make this quicker

**Comment by raiyni** [comment]
Read the wiki. That method is there.

**Comment by Quoze** [comment]
Oh I seeeee, apologies lads :(
Thanks for showing me the way
