### ISSUE TITLE
Telekenetic Room has a WorldPoint.equals(LocalPoint) call

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#5948]
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/mta/telekinetic/TelekineticRoom.java#L135

This would always be false, as there is no relation between `WorldPoint` and `LocalPoint` instances.

**Comment by Adam-** [comment]
Maybe this is related to #3946.
