### ISSUE TITLE
Add a regular, not runescape-related calculator 

### ISSUE THREAD

**Issue by fuckjayce** [runelite/runelite#5955]
**Describe the solution you'd like**
The calculator button on the right hand side would have a simple number pad with addition, subtraction, multiplication and division 

**Describe alternatives you've considered**
Can easily use the calculator that Google provides - I just find it easier to calculate things all in one place, such as when I'm using the XP calculator for a certain skill, and want to calculate how long a certain level will take with my current XP rates.

**Comment by deathbeam** [comment]
The very same issue was already closed as wontfix, it is not worth reimplementing something that you already have very easy access to from your OS, and not worth maintaining that as well. Closing as duplicate
