### ISSUE TITLE
Tag tabs: Items where the charged version uses the same placeholder as the uncharged version doesn't show the placeholder

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#5957]
This technically isn't a bug since it's a placeholder of an uncharged version, but still kinda annoying.

Tagging the uncharged placeholder "fixes" this

https://media.discordapp.net/attachments/280385695254839296/500220388882776085/2018-10-12_11-15-54.gif

**Comment by MagicfTail** [comment]
It searches specifically for tagged items, and since the uncharged version (which is the item the placeholder if being made of) isn't tagged, the placeholder doesn't show up

**Comment by deathbeam** [comment]
oh so isnt this duplicate of that issue that is requesting for all charged/uncharged versions to be tagged?

**Comment by MagicfTail** [comment]
I guess it is, although I hate the idea of every item with charges being tagged when tagging one. And since the workaround is so easy, this shouldn't be 'fixed' tbh
