### ISSUE TITLE
Idle notifier does not wait the ms configured in settings after getting out of combat

### ISSUE THREAD

**Issue by FloydvanHassel** [runelite/runelite#5961]
So, since the newest update of Runelite, my idle notifier does not wait the default 5000ms before notifying. 
I am fighting ammonite crabs, this means the out of combat situation happens after 10 minutes. At this point, normally, I would receive an idle notification. Since the ammonite crabs did not aggro anymore.

Now, since this new updates, after 5 minutes, which is the regular log out from idle situation. Every time I am out of combat, even if it is for a second (when auto-retaliating for example). I get a warning that I am about to log out from idling. 

Simply stated, the idle notifier does notice that I am in combat, so not idle. But after getting out of it, it does not wait the required milliseconds to notify me about idling.

Hope I could be of any use :)

**Comment by ollieatkinson** [comment]
![playback](https://user-images.githubusercontent.com/1382565/46868073-0b147c00-ce1f-11e8-96b3-25052614f93a.gif)

I just tested this and it waits for the duration specified in the idle delay (look at stat restore counter)

**Comment by deathbeam** [comment]
Idle logout notification is not taking the delay into account, it is just firing like 15-20 secs earlier. If you are in combat for long than 5 minutes, you are suppoed to logout immediatly after end of combat, I think, and so that is why idle logout notif is firing

**Comment by FloydvanHassel** [comment]
No, in combat, the logout timer is set to 20 minutes. And the agro of crabs is 10 minutes. So before the latest update, only after the 10 minutes, when getting out of combat, the idle logout timer would fire. 

Quick edit to the last update:
Hovering over the client does not seem to reset this timer, only hovering over the gamescreen does.

**Comment by FloydvanHassel** [comment]
One more edit: Putting the client into focus does not influence this bug, it was the mouse hovering that influenced it. so as long as your mouse stays on the settings screen, this should be fine.
