### ISSUE TITLE
Blast furnace foreman highlighted

### ISSUE THREAD

**Issue by Mamboosun** [runelite/runelite#5974]
Currently training my smithing at the Blast Furnace , and so far the plugin is absolutely flawless, however when it comes to repaying the foreman to use the furnace he sometimes gets lost in the crowd of players. For someone who is far better than me at coding is it possible to add an highlighting option so you can easily spot where he is?
Thanks in advance

**Comment by deathbeam** [comment]
You can use NPC highlighting for this
