### ISSUE TITLE
Camera zoom bug

### ISSUE THREAD

**Issue by kingjasko** [runelite/runelite#5978]
When I enable the "camera zoom" feature, it will not let me scroll past the max zoom out of the game anymore. On the other hand, it WILL let me zoom further in if I enable the "expand inner zoom limit". This probably has something to do with the recent update, right?

**Comment by Abextm** [comment]
This is working as intended

**Comment by kingjasko** [comment]
can I get a further explanation? Is it supposed to not zoom out as far as before?

**Comment by Nightfirecat** [comment]
The difference between the previous zoom distance and the new current vanilla zoom distance is small enough that we did not feel it still needed an option.

**Comment by kingjasko** [comment]
Well it's big enough that for example people doing ZMI aren't able to see the ladder when they spawn with ourania teleport, I'm sure other people may have been affected by this, as well. If some of us are irritated enough by it it means it's different enough, that it should stay how it was, perhaps.

**Comment by kingjasko** [comment]
Also, a random off-topic question.. Is it possible to highlight any object the same way as NPC's can be highlighted?

**Comment by shogunreaper** [comment]
it may be a small difference but its definitely noticeable

please change it back
