### ISSUE TITLE
Prayer potion dosing indicator 

### ISSUE THREAD

**Issue by lulwut** [runelite/runelite#598]
A good feature would be having an indicator for when you can sip a ppot/Sup restore and gain the most benefit out of it. I've been caught out a few times and had my prayer run out since I'm used to osbuddy. Keep in mind holy wrench.

**Comment by SomeoneWithAnInternetConnection** [comment]
I'm not sure if it counts, but the item stats tooltips should contain that information at the very least. The text will be green if you aren't going to waste any points, like this:
![prayerpot](https://user-images.githubusercontent.com/34518321/36313387-61efbd72-12ff-11e8-81c7-f52df38946a8.png)

 It doesn't look like it accounts for the holy wrench right now though.

**Comment by lulwut** [comment]
Ideally a more noticeable indicator (can just be a box in the top right)
which appears whenever you should dose.

**Comment by Unmoon** [comment]
Idle notifier can also notify you when you are low on prayer.

**Comment by Adam-** [comment]
Added in #3089
