### ISSUE TITLE
The runelite menues are all glitching out

### ISSUE THREAD

**Issue by rs3isshit** [runelite/runelite#5980]
https://imgur.com/a/lU98iz9

Im on the latest version of runelite 

Windows 10 64 bits

**Comment by MagicfTail** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by rs3isshit** [comment]
yeah iv'e already done that

**Comment by MagicfTail** [comment]
Then you did it wrong, because your issue is fixed by disabling hw acceleration

**Comment by rs3isshit** [comment]
yeah maybe, i'll try again , last time it worked for a week
