### ISSUE TITLE
!KC command throwing uncaught exception

### ISSUE THREAD

**Issue by forsco** [runelite/runelite#6005]
**Describe the bug**

Using `!kc skotizo` throws an uncaught exception

**To Reproduce**

- Use the !kc command

**Expected behavior**

!kc skotizo should be replaced with the kill count message

**Screenshots**

https://lambda.sx/BA3.png

**Environment**
 - OS: Win10
 - RuneLite version: 1.4.22-SNAPSHOT - updated to current master on a `clean install` with -U

**Comment by Nafana** [comment]
The API endpoint `https://api.runelite.net/runelite-1.4.22-SNAPSHOT/kc?name={USERNAME}&boss={BOSSNAME}` seems to return a 404. 

According to a user in game, the command was working "a couple of days ago". No changes were made to `net.runelite.http.api.kc` or `net.runelite.http.service.kc`. The only recent changes have been to the ChatCommandsPlugin class itself.

Just thought I'd put some of the info I was able to gather about it here.
