### ISSUE TITLE
Wrong quantity displayed on ground items

### ISSUE THREAD

**Issue by cmg5461** [runelite/runelite#6006]
![java_2018-10-13_21-49-43](https://user-images.githubusercontent.com/9099791/46911911-7b61f100-cf36-11e8-832b-5cec3ebe4b33.png)

Seems to happen on tiles which contain one visible to public item & one visible to player item.

Index 0 coins quantity is 3,000.

**Comment by Adam-** [comment]
Duplicate of #1220
