### ISSUE TITLE
Special attack counter incorrect for Corporeal Beast and Chaos Elemental

### ISSUE THREAD

**Issue by alexbowers** [runelite/runelite#6009]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
If i'm duoing with somebody else, the special attack counter cannot keep accurate count of my damage dealt.

This happens at Chaos Elemental and corp with a bgs (haven't tested other weapons).
If i hit a 40 with my spec, the counter shows ~44 damage done.

**To Reproduce**
1. Spec something with somebody else in a duo (whether they use a spec weapon or not).
2. Note your spec damage.
3. Check the amount Runelite says has been dealt.

**Expected behavior**
I expect the count to be correct

**Environment (please complete the following information):**
 - OS: OSX
 - RuneLite version: 1.5.1
 - Launcher version: (not sure how to check)

**Comment by alexbowers** [comment]
Does that mean that perhaps the XP counter is incorrect if using a "shared" style?

Is there a way for this to be resolved, or is that all that can be done for it.

Can you point me to the line of code that gets the XP so i can try messing around with it to see if anything can be done for it.

**Comment by alexbowers** [comment]
https://github.com/runelite/runelite/blob/9e95ff5117504802f13cd9d484b8baad1223e947/runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java#L237

found it.

**Comment by raiyni** [comment]
This issue stems from some monsters giving increased xp I think

**Comment by alexbowers** [comment]
There is a "modifier" variable that is taken into account based on the boss
though.

So either there is an issue with the modifier not working properly, or the
way it obtains the XP and calculates is a little off.

**Comment by Kamielvf** [comment]
I cannot seem to reproduce this on corp, but on chaos ele I hit a 45 bith bgs (65 hp exp) and the counter registered a 49.

**Comment by alexbowers** [comment]
I may be mistaken at corp then, because I do duo that and trio that so perhaps looking at wrong hitspats. I solo chaos and thats when i properly noticed it.

**Comment by raiyni** [comment]
It doesn't use hitsplats.

**Comment by alexbowers** [comment]
No, but I was to see whether it was different (by comparing what I thought i hit, to what runelite told me was done).

Is it always the HP xp drop that is counted?

**Comment by raiyni** [comment]
yes

**Comment by alexbowers** [comment]
Also, doesn't OSRS always round down?

https://github.com/runelite/runelite/blob/9e95ff5117504802f13cd9d484b8baad1223e947/runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/SpecialCounterPlugin.java#L248 

perhaps this needs to be `floor` also.

**Comment by alexbowers** [comment]
That doesn't fix the current issue though

**Comment by raiyni** [comment]
You probably looked at the wrong hitsplat. If you can provide a video/gif of it happening for proof, that's a different story.

**Comment by alexbowers** [comment]
Yeah ignore corp for now, i'll try that some other time.

@Kamielvf has managed to repro at Chaos Elemental though.

**Comment by alexbowers** [comment]
I have tested this against normal wilderness monsters and venonatis, the issue is not at either of those.

That to me indicates there is not an xp boost for wildy monsters / bosses. Will keep testing.

Interestingly, it seems that the actual xp drop is 1.4444 instead of the usual 1.3333

I have asked Mod Ash whether this is actually correct.

**Comment by raiyni** [comment]
Because venonatis is correctly in the xp boost enum..................

https://github.com/runelite/runelite/blob/9e95ff5117504802f13cd9d484b8baad1223e947/runelite-client/src/main/java/net/runelite/client/plugins/specialcounter/Boss.java

**Comment by raiyni** [comment]
Chaos Elemental and Abyssal Sire have a casing issue. So they don't match. Plugin should be updated to be case insensitive or use npcId

**Comment by alexbowers** [comment]
Ah okay.

PR made. 

https://github.com/runelite/runelite/pull/6030
