### ISSUE TITLE
Bank Tag Tabs - Return to last used tag tab after opening and closing bank

### ISSUE THREAD

**Issue by RebornFX** [runelite/runelite#6012]
Firstly, love this new plugin. It's brilliant. I was just wondering if it would be possible if the tabs could function more similarly to normal bank tabs. 

It would be ideal for after having closed your bank, if the last tab you had open when you closed your bank was a bank tag tab, when you next open your bank, you would still have that bank tag tab open. Right now you are returned to the last opened regular bank tab rather than the tag tab.

**Comment by deathbeam** [comment]
Already implemented duplicate
