### ISSUE TITLE
Customizable goals for XP Globes + integration with the skill calculator

### ISSUE THREAD

**Issue by Volney47** [runelite/runelite#6018]
In RS3 you can right click a skill in the skill tab and set either a level or exp goal that reflects on the xp globes of that skill. Considering there are skills where you would do the same action for dozens of levels, it would be nice to have the xp globe track the end goal. In addition, an integration with the skill calculator would be the cherry on top, input goal > right click action > set as goal

**Comment by deathbeam** [comment]
We already have target goals https://github.com/runelite/runelite/wiki/XP-Tracker
