### ISSUE TITLE
Allow setting tag tabs icon by id and/or by lookup

### ISSUE THREAD

**Issue by forsco** [runelite/runelite#6021]
Currently there is no way to set a tab tag icon to an item you don’t currently have. 

It would be nice to implement a feature to be able to set an icon via a lookup or id without having to time manually changing your settings configuration. This becomes even harder to do when you log into the client.

**Comment by Hydrox6** [comment]
Definitely needs to be a way that isn't by ID, as those aren't listed anywhere to normal users; could get confusing. Would be nice to have ID in addition, for the power users who are willing to seek the information out (or use dev tools)

**Comment by forsco** [comment]
Definitely agree with the id part for more adept users

**Comment by deathbeam** [comment]
I dont think ID selection should be implemented. Also, with my recent PR (the import/export) you can just set your own icon id so maybe this feature request is no longer necessary after that? Implementing the lookup is not good idea, unless we want to maintain ge-like search that also includes untradeables, and I dont think adding that is reasonable.
