### ISSUE TITLE
Integer scaling in stretch fixed mode does not work!

### ISSUE THREAD

**Issue by robmonte** [runelite/runelite#6022]
**Describe the bug**
Integer scaling in stretch fixed mode does not work, keeping the game tiny.

**To Reproduce**
Presumably only affects high resolution screens, but ironically those are what this setting is necessary for.

1. Go to 'Configuration'
2. Click on 'Stretched Fixed Mode'
3. Enable 'Integer Scaling'
4. See screenshot

**Expected behavior**
The game should scale to nearly the window size and not run my laptop so hard

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/46930270-4fb03b00-d00a-11e8-851b-3dfdddbcabb6.png)

**Environment (please complete the following information):**
 - OS: macOS 10.14 (Happened in 10.13 also)
 - RuneLite version: 1.4.21.1
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by deathbeam** [comment]
Your display is too small

**Comment by robmonte** [comment]
> Your display is too small

I had thought that might be the case but I don't think it's true actually. The reason why is because this used to work actually on an earlier version of Runelite a few months ago. Some update around July had randomly broke its functionality for me.

I found another bug report and forgot I had actually commented on it here: https://github.com/runelite/runelite/issues/4504

I have both a 13 inch 2017 macbook and a 15 inch one. Both have this exact same issue that started at that time. The game is nearly unplayable on either device because the window is either way too small or it runs at 6fps when turning off integer scaling. But like I said, it actually worked before so something must be at play here other than size.

**Comment by robmonte** [comment]
I get that, but obviously my screen size didn't change. It's the same two laptops I used before. Like I already stated, and I said the exact same thing on the previous bug, it worked before and then after an update it didn't anymore. And in case it comes into question, it used to work with the plugin config panel open, I never play with it closed.
