### ISSUE TITLE
Cow Home/Minigame teleport can be cancelled during the final animation, which causes an incorrect infobox

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#6029]
**Description**
The Home and Minigame Timers check for the final action of the Cow teleport's animation to decide to show the infobox. It is possible to move during this final animation, since it goes on for so long, and cause an infobox to appear when it should not.

**To Reproduce**
0. Activate the Cow Teleport (RuneFest 2014 animation)
1. Start a home or minigame teleport
2. As the cow kicks you, spam click somewhere
3. Notice that you haven't teleported, yet there is a timer for the teleport you just used

I know this is an edge case, and I know this would be a massive pain in the arse to fix, I've tried. 

**Video Example**
https://gfycat.com/TinyTatteredGalapagossealion

**Environment:**
 - RuneLite version: 1.4.21.1
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
I don't think this is worth trying to fix since:

* It's rare&mdash;you usually have to be trying to produce this outcome
* Completing a home teleport resets the timer to the proper time anyway

**Comment by Nightfirecat** [comment]
Fixed in #14842
