### ISSUE TITLE
CPU Usage High

### ISSUE THREAD

**Issue by tgeene** [runelite/runelite#6036]
Not sure when it started, some time in the last week, but my RuneLite is using a lot of my CPU. Before this started happening I could run 3 copies of RuneLite and watch a show (streaming) without any problems, but now even 1 instance is using 15-20% of my CPU.

Specs:

- Computer: Asus ROG GL503VD
- Ram: 16 GB
- Processor: i7-7700HQ @ 2.80 GHz
- Hard Drive:  1TB HHD

I have turned off as many options as I can, but still the problem persists.

**Comment by Abextm** [comment]
This is just how RuneScape works.

**Comment by tgeene** [comment]
What do you mean this is just how RuneScape works? I have been playing this game for year and never had an issue like this.

**Comment by Abextm** [comment]
RuneScape is typically CPU bound, so it will pin a core, so you will almost always have a relatively high cpu usage.
