### ISSUE TITLE
Add "Clean Herb" to Menu Entry Swapper

### ISSUE THREAD

**Issue by Kingdavid337** [runelite/runelite#6049]
I often accidentally clean a herb when attempting to note it after a farming run. This results in a slight loss of GP for some herbs and an extra inventory space being taken up with the cleaned herb being on its own.

If possible, making an option to change the "Use" menu option into the default left click would be greatly appreciated!

**Comment by deathbeam** [comment]
Use shift-click configuration and remap use to be shift-click
