### ISSUE TITLE
Bank tag tabs are losing the tag for barrows eqiupment if it degrades. 

### ISSUE THREAD

**Issue by KassaPng** [runelite/runelite#6054]
**Describe the bug**
Barrows equipment that degrades will disappear from a bank tag tab.

**To Reproduce**
1. Create a bank tag tab and drag any barrows equipment into it. 
2. Take the item out of the bank and drop it on the ground to make it degrade completely(or use it till it degrades and skip step 3).
3. Repair item at armour stand.
4. Add item to bank (it will not go back in the bank tag tab).

**Expected behavior**
The equipment should go back to its bank tag tab after it degrades.

**Comment by raiyni** [comment]
#5972
