### ISSUE TITLE
Equipment tagging: Doesn't work with graceful

### ISSUE THREAD

**Issue by Abextm** [runelite/runelite#6059]
Because equipped graceful (and anything else that has a negative weight bonus) has a different id when its equipped it doesn't get tagged.

**Comment by deathbeam** [comment]
This might not work with other weight reduction gear as well

**Comment by MagicfTail** [comment]
Can confirm, max cape doesn't get tagged either

**Comment by raiyni** [comment]
re: https://github.com/runelite/runelite/pull/5972

I'm not sure how tagging inventory/equipment will fit into that.
