### ISSUE TITLE
Nightmare zone NMZ absorption counter is hard to read (white on light blue)

### ISSUE THREAD

**Issue by M-a-x-y** [runelite/runelite#606]
It can be quite hard to see how many points you have left! 

![image](https://user-images.githubusercontent.com/36554991/36336300-6e25b2f8-13eb-11e8-8813-7adde279a1e9.png)

**Comment by Rerbun** [comment]
Bit of a late comment, but I thought this would be useful for people Googling. 

In the plugin settings for RuneLite itself you can change the infobox size so the absorption text no longer overlaps with the potion icon. This should make it a lot easier to read.

Also, you can turn on stretched mode with Integer Scaling to 100%. Looks quite odd at first but I got used to it by now.
