### ISSUE TITLE
Feature request: Menu swap "Make All" for smelting jewelry

### ISSUE THREAD

**Issue by edgarsaurus** [runelite/runelite#6068]
Please add a menu swapper for the jewelry smelting menu that allows a left click to "make-all" of one jewelry item.

**Comment by Nightfirecat** [comment]
This has been discussed with the team and [has been added to the rejected features list](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping):

> * `Menu reorder in shop/artisan skill screens`: Other clients don't implement these swaps, and would be too strong for numerous activities (examples include "Buy-50" swaps, "Make All" swaps for smithing/crafting, etc.)
