### ISSUE TITLE
nbsp should be replaced with spaces in CC history to make it match properly

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#6069]

**Comment by raiyni** [comment]
It shouldn't. 

`chats.removeIf(s::equalsIgnoreCase);`

**Comment by MagicfTail** [comment]
![image](https://user-images.githubusercontent.com/12607046/47182732-79c56e00-d326-11e8-9251-a3ee027a2fb0.png)
🤷‍♀️

**Comment by deathbeam** [comment]
So looks like this is not casing issue, but nbsp issue after all
