### ISSUE TITLE
Scrolling while hovering tag tabs scrolls in main bank window as well

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#6076]
I would expect it to only scroll the tab, and not scroll the bank window.

**Comment by deathbeam** [comment]
Hmm not sure if this is regression as @Abextm marked it

**Comment by Abextm** [comment]
Its a jagex-caused regression; from the last weeks changelog: 

>Increased scrollable area of the bank
>
>Mobile players will now be able to make use of the empty sides of bank interface to scroll through their bank. This gives more interface real-estate to be able to navigate through the bank.

**Comment by deathbeam** [comment]
Ah
