### ISSUE TITLE
Playlists/Favorite Music?

### ISSUE THREAD

**Issue by Corzappy** [runelite/runelite#6093]
I really like a few of the osrs songs but not all of them are ideal. They are either not fitting for whats happening or too distracting at the time. Thats usually why I play with the music off.

I would love if you where able to quickly select your favorite songs and play them right there. Maybe a favorite option to put them at the top of the list, A playlist type thing where you can group together your songs and play them from the name of the playlist, Or my personal favorite; a music tab on the sidebar of the client where you can select your music and/or change the music volume.

If this is simply not possible maybe highlighting songs that you favorited or hiding songs you havent unlocked?
Another post was made titled Playlist shuffle/autoplay suggestion #1916
This is fairly similar to what I am suggesting

**Comment by devLotto** [comment]
Jagex recently published songs on Spotify. Maybe that will do it for now. 
https://open.spotify.com/track/7g8HA6O413CebKY20aP3nR?si=xWbKqs4lRCWxPnBqvFmLQQ

**Comment by deathbeam** [comment]
I think simply using external player with OSRS sounds is way better rather than trying to add bunch of stuff to very limited player in game.
