### ISSUE TITLE
Bulk fetching item prices

### ISSUE THREAD

**Issue by Joshua-F** [runelite/runelite#610]
Currently item prices must be fetched one at a time, which is terrible when you're wanting to lookup a mass amount of items. Having a way to lookup all or a bulk amount of items would be a great improvement.

There was also discussion about loading prices on startup so that they'd be loaded in memory already to avoid the need to fetch them when requested which can take up to a few seconds causing delay until we get the response.

**Comment by SomeoneWithAnInternetConnection** [comment]
Unless I'm mistaken, this was fixed by 3ead452d

**Comment by Joshua-F** [comment]
It appears so.
