### ISSUE TITLE
Add Fairy ring "D J P" to this medium clue map solution

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#6102]
![image](https://user-images.githubusercontent.com/34870401/47258572-4e18c400-d49d-11e8-98fd-e169e9044ac6.png)

**Comment by Nightfirecat** [comment]
The current structure of map clues doesn't allow us to add any text to them. We do plan on eventually reworking the clue plugin to allow for that, but that's not currently possible.

**Comment by JeljoGb** [comment]
Oh okay, I thought I saw it with other clues, but they were probably not map clues

**Comment by JeljoGb** [comment]
Oh and @db, I know the location, I just don't know the fairy ring if I haven't medium clued for a while.
I try to never open the world map because it takes a second of game freeze to open. Unless for coordinate clues.

**Comment by Nightfirecat** [comment]
If you have the world map plugin enabled, it will show you fairy rings, and display their codes in a tooltip.

**Comment by JeljoGb** [comment]
Yeah but I need to hover over the fairy ring, after opening the world map, which lags when opening, I just searched for the "tower of life" in the search bar of the fairy ring.

**Comment by Nightfirecat** [comment]
Closing for now in favor of #8705, which is more general.
