### ISSUE TITLE
GE price no longer shown up on items dropped [Regression]

### ISSUE THREAD

**Issue by urbanracer34** [runelite/runelite#6107]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)
IT'S NOT! 

**Describe the bug**
GE prices no longer showing beside High Alc prices on items on the ground, dropped from monsters

**To Reproduce**
1. Go to a place where lots of items are dropped (edgeville dungeon with Hill Giants is my main example.)
2. Kill NPCs
3. Items will drop

**Expected behavior**
GE Prices should show right beside High alc prices

**Actual Behaviour**
Only shows up High Alc Prices, NO GE Prices.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 1803
 - RuneLite version: 1.4.22
 - Launcher version: 1.6.0

**Additional context**
N/A

**Comment by urbanracer34** [comment]
Issue appears to be either intermittent or was a problem on my end. I just restarted the client on the computer I posted this from / about and the GE prices are now showing above items dropped on the ground.

**Comment by deathbeam** [comment]
Looks like just trouble with accessing the API, closing.
