### ISSUE TITLE
Organized Crime world logger, Location arrow

### ISSUE THREAD

**Issue by ScrPits** [runelite/runelite#6110]
**Is your feature request related to a problem? Please describe.**
Current Client doent Log the Crime world or time

**Describe the solution you'd like**
A Widget and or side bar to keep logs of crime ex: | W330 | 20mins | Southwest Graveyard... ect

With the time counting down "till finished" and remove the entry on "times up"
  
**Describe alternatives you've considered**
Embed the note with the world (this keeping to rs fair play issues. doing this will make you need to read the note .
issues is multiple notes

**Comment by Judman** [comment]
Agreed! Would love to have this feature to save me post-it notes!

**Comment by Pikamander2** [comment]
+1 for this feature request

By the way, some of the worlds are synced, and it appears to be partially based on IP address, but I haven't figured out the exact formula yet.

Here's a quick Python script to output the world IP addresses if somebody wants to test it further:

```
import socket
for world_number in range(1,230+1):
	print('World ' + str(world_number) + ' (' + str(world_number + 300) + '): ' + socket.gethostbyname("oldschool" + str(world_number) + ".runescape.com"))
```

**Comment by LlemonDuck** [comment]
Hub plugin [Shayzien Organised Crime](https://runelite.net/plugin-hub/show/shayzien-organised-crime) now provides this.
