### ISSUE TITLE
Bank Tag Tab Monster Icons

### ISSUE THREAD

**Issue by alexbowers** [runelite/runelite#6115]
If you tag your weapons for a specific monster, Eg. setup for a sara trip, or bandos, etc, then it doesnt really make sense to tag it with a picture of your weapon, since that weapon is used at multiple places. If we could tag it with a picture of the monster instead, like you get with a slayer assignment task.

**Describe the solution you'd like**
When you change icon, you can type in the name of the monster, and  if it matches it will use that as the icon instead of an item.

**Comment by raiyni** [comment]
Duplicate https://github.com/runelite/runelite/issues/6021
