### ISSUE TITLE
Redraw on tiling window managers is inconsistent.

### ISSUE THREAD

**Issue by Spencer-H** [runelite/runelite#6120]
Description:
Runelite does not redraw properly in tiling window managers.

Open Runelite from within a tiling window manager such as i3 or dwm.
Click on the menu icons off to the right.
Runelite will often fail to redraw the menu panel and the opened tab, causing either only text to be drawn or nothing at all.

I would expect clicking on the menu buttons or searching for something in the settings menu to redraw that frame.

 - OS: Ubuntu
 - RuneLite version: 1.4.22
 - Launcher version: 1.6.1

**Comment by deathbeam** [comment]
It is not related to tiling window manager (works just fine for me on bspwn). Its this: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
