### ISSUE TITLE
control and Ground items

### ISSUE THREAD

**Issue by bobalicioussss** [runelite/runelite#6121]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when i have to manually type each and every one of the items i don't want to show up on the ground with the price 
**Describe the solution you'd like**
why don't you guys add a a CTRL option where if you hold it down it shows a box to check to hide it or another key to hold .

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Alexsuperfly** [comment]
hold alt, then click the + or - to highlight or hide items on the ground
