### ISSUE TITLE
Grand Exchange Log

### ISSUE THREAD

**Issue by BopOSRS** [runelite/runelite#6125]
OSBuddy used to save everything you bought and sold through GE to their site, I kind of miss this and was wondering if there is any way to implement something similar to RuneLite.

Should preferably just save it to a .txt file or something, stating whether you sold or bought, what item, amount of items and price of each individual item bought/sold.
Should also allow us to set a minimum gp for the transaction to be saved in the log (so that me selling my loot tab doesn't get saved for example)

Thank you!

**Comment by raiyni** [comment]
duplicate https://github.com/runelite/runelite/issues/1250
