### ISSUE TITLE
Hide all players except friends with Entity Hider

### ISSUE THREAD

**Issue by ChlorideCull** [runelite/runelite#6126]
**Is your feature request related to a problem? Please describe.**
I have a pretty weak machine with an integrated GPU, and whenever I go somewhere with crowds my FPS tanks to single digits. Makes it hard to do much.

**Describe the solution you'd like**
I'd like the ability to hide all players other than my friends.

**Describe alternatives you've considered**
Hiding all players means I can't interact with friends.

**Additional context**
I suppose this could be abused for PvP outside multi-combat areas if you add whoever you're fighting to your friendslist.

**Comment by robinwithes** [comment]
I think this was denied in the past due to what you stated in your additional context.

**Comment by ChlorideCull** [comment]
I did look through the "Rejected and rolled back features" section of the
wiki, and search through all issues, but there I could only find hiding
friends and ignored people, which I do understand can be an issue with PvP.

This is for hiding everyone but friends, which technically could be abused
for PvP, most likely wouldn't, since you're going to be entirely blind to
people around you. Would be a shame to kill someone in Wildy, then have his
invisible friend kill you, who you couldn't see since he isn't on your
friendslist!

**Comment by deathbeam** [comment]
You can already do that? Check hide players, and do not check hide friends

**Comment by ChlorideCull** [comment]
Hm, I tried, but couldn't get it to work. I'll give it another shot, and if it doesn't work, I'll see if I can get a reproducible minimal test case.
