### ISSUE TITLE
Bank Tags Wildcard [Suggestion]

### ISSUE THREAD

**Issue by KPndaD2** [runelite/runelite#6127]
Here's an example of exactly what I'm talking about:

![image](https://user-images.githubusercontent.com/29396842/47290358-16a93500-d5cd-11e8-9d6b-97b11d32ff57.png)

If I have a bunch of tags that start with:

> herblore - 

It would be awesome to be able to add a wildcard to items.

So for vials I could do:

> herblore - *

and the vials would show up in any tag that started with herblore -

**The benefits would be that it would take less time to set up some of the tag tabs and it would be easier to manage your tags.**

**Comment by deathbeam** [comment]
You can already do partial search for tags cant you

**Comment by raiyni** [comment]
he wants to tag an item will all available tag prefix

**Comment by KPndaD2** [comment]
> 
> 
> You can already do partial search for tags cant you

Talking about wild carding when tagging an item.
EG:

I set a tag on Prayer Potion (4) 

> prayer set -*

I make a tag tab called 

> prayer set - melee

and a tag tab called 

> prayer set - ranged

Now Prayer Potion (4) will show up in 

> prayer set - ranged

 and 

> prayer set - melee

**Comment by deathbeam** [comment]
Also that is not how tagging works, you set the tag, not search for existing tags when tagging item

**Comment by deathbeam** [comment]
So yeah, based on my previous comment, closing as wontfix
