### ISSUE TITLE
Option to hide minimap, compass etc.

### ISSUE THREAD

**Issue by M-a-x-y** [runelite/runelite#614]
I was looking at making this to learn but quickly realised it's far beyond me - for now at least.

It would be cool to have the ability to hide things; minimap, orbs, compass, XP button. Would be nice for times when you're bankstanding, skilling, PVMing (opens up some valuable click-space), recording etc. 

Maybe a few toggles in-case you wanted to keep the world map or others individually?

**Comment by Kamielvf** [comment]
As for the xp button and orbs, theres already a setting in the official client under advanced options called "data orbs" that you can enable/disable to hide or show them.

**Comment by M-a-x-y** [comment]
I did think about that setting but figured it would be handy if they could be turned off individually like if you wanted prayer/HP but not run/spec (or any other combination of such).

**Comment by Adam-** [comment]
Done in #927
