### ISSUE TITLE
Notification on dark core spawn

### ISSUE THREAD

**Issue by Trevor159** [runelite/runelite#6146]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

I die sometimes when afking corp too much when i spec him down when the core spawns in.

**Describe the solution you'd like**

An option in either the corp plugin or the npc indicator plugin that allows a notification when the NPC spawns

**Comment by deathbeam** [comment]
You can just highlight dark core in NPC indicators plugin

**Comment by 15987632** [comment]
> You can just highlight dark core in NPC indicators plugin

Yes, I already have that done. I am asking for a notification when an npc (specifically the dark core) spawns, which to my knowledge can not be done through the NPC indicators plugin currently. Hence the request.

**Comment by deathbeam** [comment]
I dont really see valid use case for that

**Comment by Adam-** [comment]
I don't see anything wrong with making this an option of the corp plugin.

**Comment by Twiglet1022** [comment]
I just had a go at trying to do this, but the dark core spawn even triggers every time it jumps so it ends up being a "The Dark Core has just jumped!" notifier.

**Comment by 15987632** [comment]
> I just had a go at trying to do this, but the dark core spawn event triggers every time it jumps so it ends up being a "The Dark Core has just jumped!" notifier.

If you looked closely you can see it is already solved https://i.imgur.com/lKOQ0iC.png

**Comment by Twiglet1022** [comment]
> > I just had a go at trying to do this, but the dark core spawn event triggers every time it jumps so it ends up being a "The Dark Core has just jumped!" notifier.
> 
> If you looked closely you can see it is already solved https://i.imgur.com/lKOQ0iC.png
Ah thank you, I didn't realise that that meant it had already been solved.

**Comment by abextm** [comment]
Jagex's [recent statement](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1) prohibits `Adds additional visual or audio indicators of a boss mechanic`
