### ISSUE TITLE
VarbitChange event posted before change

### ISSUE THREAD

**Issue by Dreyri** [runelite/runelite#616]
Since commit f8c7a8b1c0f19b1344937504b972c71fd052a2f4
```
Use client Varbit for index, lsb, msb
```
The varbit gets changed 1 cycle after the event was posted. Leading to the use of the wrong varbit for things such as most notably the Attack Indicator (switching between whip and shortbow will display the issue).

**Comment by Adam-** [comment]
Previous behavior has been readded in 68c0661c2770598112a5876d2445ba2b67cfb1f8. I am not sure it is correct though since the clients getVarbit() reads the other settings array. I don't know what the difference is between the two.

**Comment by Dreyri** [comment]
I can confirm everything works now
