### ISSUE TITLE
STASH unit plugin?

### ISSUE THREAD

**Issue by erzinhehe** [runelite/runelite#6176]
I always forget which STASH units I have unlocked and which I don't, resulting in sometimes bringing in unnecesary items or sometimes expecting the STASH units to have the items for the step but end up with no items.

When the clue steps are shown in the corner, maybe a small line saying 'this STASH is filled' or 'This stash needs to be filled'

**Comment by deathbeam** [comment]
Duplicate

**Comment by Abextm** [comment]
Duplicate #1662
