### ISSUE TITLE
External/Pop-out Map

### ISSUE THREAD

**Issue by ZenVee** [runelite/runelite#6196]
**Concept**
Make it possible to have a external / pop-out style map that is not bound to the client itself. 

**Reasoning**
I think this would be useful to players that have multiple monitors and want to preserve the UI jumble of having the pop-out mini-worldmap in game.

![external-map-idea](https://user-images.githubusercontent.com/7267811/47550208-20c87d80-d8c4-11e8-838f-81a13b71c270.png)

**Comment by Nightfirecat** [comment]
Not saying we won't implement something like this, but this seems like it would be better solved by using https://www.osrsmap.net or any number of other world map sites opened in a browser window.

**Comment by ZenVee** [comment]
> Not saying we won't implement something like this, but this seems like it would be better solved by using https://www.osrsmap.net or any number of other world map sites opened in a browser window.

I used to do it this way, but I find the Runelite map way more informative which teleport locations etc, that and the player indicator helps with navigation.

**Comment by deathbeam** [comment]
This would require partially or fully reimplementing world map and we decided against that when we started enhancing Jagex one, so closing as wontfix
