### ISSUE TITLE
Hunter Butterfly Release

### ISSUE THREAD

**Issue by hypedmoose** [runelite/runelite#6210]
Is it possible to have a one click "release" butterfly option for the menu swapper?

**Comment by forsco** [comment]
The only reason this would be useful is when using the 2x or 3x hunter training method.

Personally I don't feel this warrants a left click swap and could be done by utilizing shift left click.

**Comment by Nightfirecat** [comment]
We are not planning on adding further left-click option swaps for inventory items. As forsco mentioned, use the customizable shift-click behavior for this.

**Comment by deathbeam** [comment]
Use shift-click
