### ISSUE TITLE
Can't download Runelite! Dropdown menu on Runelite.net does not work! [gif explains it all]

### ISSUE THREAD

**Issue by TyrannusOSRS** [runelite/runelite#6211]
https://imgur.com/a/1RjHRq3

**Comment by Abextm** [comment]
1) This should be on [runelite/runelite.net](https://github.com/runelite/runelite.net)
2) What browser are you using
3) What OS are you using
4) Are you sure you are not on a phishing website?

**Comment by KasparRosin** [comment]
Turn of noscript or any other javascript blocker and try again.
If you aren't using a blocker, try to drag your mouse down slower.

**Comment by KasparRosin** [comment]
There is a small gap between the dropdown menu and downloads for all platforms could that be the problem?

**Comment by deathbeam** [comment]
Reopen on rl.net, wrong repo
