### ISSUE TITLE
"Remember last Tag Tab" option only works if closing the bank with "X" button

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#6212]
Closing the bank with "Esc" does not remember the current tag

**Comment by deathbeam** [comment]
Duplicate of #6198

**Comment by Nightfirecat** [comment]
I guess? 6198 didn't explain anything about how to reproduce. :man_shrugging:

**Comment by deathbeam** [comment]
I believe it is exactly same issue, widget not being nulled
