### ISSUE TITLE
Add tile coordinates to instance map

### ISSUE THREAD

**Issue by Kharazni** [runelite/runelite#6214]
**Is your feature request related to a problem? Please describe.**
The instance map is fairly limited in its current form, functioning more or less as an extended minimap. I think it could benefit from some extended utility.

**Describe the solution you'd like**
I would like the instance map to show the player's coordinates at all times, or as a toggle in settings; while this isn't a massive change to the map, it would be an interesting and at times useful addition that would not subtract from the feature as it stands.

**Describe alternatives you've considered**
The goal would be to have some way for players to see their coordinates, so other options might be adding that to the minimap itself (cluttered ui, no thanks) showing coordinates of marked tiles or of players (not very helpful in many cases), showing coordinates on the vanilla world map (doesn't show instances or some non-instanced areas), or adding a chat command like !coords or something (i have an instinctive dislike of chat commands because of lvl 80s spamming !price figter tordo !pricf fighter torso !price fighter tosro, and chat commands would really not be the best way to go about this)

**Additional context**
not applicable.

**Comment by deathbeam** [comment]
You can already do this with dev tools - https://github.com/runelite/runelite/wiki/Using-the-client-developer-tools, this is useless for normal player

**Comment by Vokuar** [comment]
Now dev tools are locked would this be feasible

**Comment by Nightfirecat** [comment]
It was feasible before they were locked, but unnecessary like deathbeam said. The location overlay already accomplishes this.
