### ISSUE TITLE
Add username of player killed in the filename on auto-screenshots of kills (PVP)

### ISSUE THREAD

**Issue by MitchWeaver** [runelite/runelite#6215]
currently they are just saved as the date, but it would be really handy if it had the username in it so it could be searched. 

it's quite annoying trying to find a name you know you have a kill on, but being unable to do so out of thousands of generic pictures in a folder

i'm sure there's a way to read text printed in the chat box, so this should be a quick job :)

**Comment by arthurtyukayev** [comment]
I’ll work on this.

**Comment by HiddenKn** [comment]
What is the situation with this one? Was it resolved already?
I tried figuring out from the linked requests but couldn't really figure it out.

**Comment by Nightfirecat** [comment]
Fixed in #6920
