### ISSUE TITLE
Left-click player options

### ISSUE THREAD

**Issue by qnps** [runelite/runelite#6225]
Is it possible to implement a player left-click option setting?  Id like the ability to trade a player with a single click.

**Comment by deathbeam** [comment]
No

**Comment by qnps** [comment]
Menu-swapper is available for NPCs and objects. What prevents having menu-swapper on other players?

**Comment by deathbeam** [comment]
Because it can be abused. Also, swapping Trade as left-click for players is just bad idea in general, because by default players have no left-click options (other than in PvP scenarios).

**Comment by qnps** [comment]
Ok thanks
