### ISSUE TITLE
Menu Entry Swapper - Construction Cape Fix

### ISSUE THREAD

**Issue by DeputyPhatt** [runelite/runelite#6227]
When using the Menu Entry Swapper with "Teleport Item" selected, you can one click teleport with a teleporting skill capes such as the crafting cape. When it comes to the construction cape (A cape that has a "Teleport" option and a "Tele to POH" option), the "Teleport" option is the left click option. Since the left click option is "Teleport", when the cape is left clicked, it brings up a menu to teleport to your POH or other POH portals. This menu can be interrupted by combat. Every person with 99 Construction teleports to their own POH substantially more than the other portals. 

As a solution to the above "Issue", would it be when the "Teleport item" option is selected within the Menu Entry Swapper Setting, make the default left click option for a Construction Skill cape "Tele to POH"

An alternate solution would be to add a separate option just for the construction skill cape. Instead of it being a check box option like the "Teleport Item" option, it could be a drop down menu option like the "Fairy Ring" option. Inside of the drop down menu, players can select the left click option to "Wear", "Teleport", or "Tele to POH".

**Comment by Nightfirecat** [comment]
That's intended behavior--that option explicitly only performs swaps for "Teleport" and "Rub" options, exactly. I would recommend setting up shift-click configuration for the "Teleport to POH" option.

**Comment by deathbeam** [comment]
As @Nightfirecat said, this is intended behaviour. Use shift-click configiguration to change it to something else.
