### ISSUE TITLE
Ignoring a player causes some messages from other players to be hidden from the chatbox.

### ISSUE THREAD

**Issue by purrincessMirri** [runelite/runelite#6228]
Sometimes, when I add someone to my ignore list, certain messages from other players will still appear above their heads, but not be in the chatbox. This isn't all messages from these players either, only some, seemingly randomly.

**Comment by forsco** [comment]
Are you sure these are typed chat messages and not from items etc?

**Comment by deathbeam** [comment]
This looks like jagex bug, we do not do anything with ignored players
