### ISSUE TITLE
info panels for Gem Mining?

### ISSUE THREAD

**Issue by xdrahmahx** [runelite/runelite#6232]
Anything about info panels for Gem Mining? Maybe how many gems of each type that got 
 mined/deposited(underground/above Shilo Village gems)

**Comment by deathbeam** [comment]
We have #4126 for tracking stuff like this

**Comment by xdrahmahx** [comment]
umm i dont see the feature of using for Gem mining?

**Comment by Alexsuperfly** [comment]
i believe he means something more like how mlm shows gems recieved

**Comment by xdrahmahx** [comment]
^
