### ISSUE TITLE
Coin drop with ring of wealth equip causes loot tracker items to dissappear

### ISSUE THREAD

**Issue by nmq12** [runelite/runelite#6240]
The items appear again on next item drop.
![image](https://user-images.githubusercontent.com/5819477/47625673-f31a4900-dafc-11e8-831d-d7cd6e3c085d.png)

**Comment by psikoi** [comment]
@abex probably missing one of the repaints you took out? I can't check today

**Comment by psikoi** [comment]
So you killed abby demons, then kurasks, ans when kurasks dropped coins that happened? And right when the next drop came along it fixed itself? Is this correct? I need to recreate the context

**Comment by psikoi** [comment]
So you killed abby demons, then kurasks, and when kurasks dropped coins that happened? And right when the next drop came along it fixed itself? Is this correct? I need to recreate the context

Also, do you have any ignored items? You can check this in the loot tracker configa

**Comment by nmq12** [comment]
There were other monsters in the list before. My ignores are "Bones,Ashes". I noticed that it happen without ring of wealth sometimes. The coins drop does not show up in the loot tracker. The only mob that this happened to me was kurasks.
