### ISSUE TITLE
Menu entry swapper for POH mounted jewellery

### ISSUE THREAD

**Issue by GenericGames** [runelite/runelite#6248]
**Is your feature request related to a problem? Please describe.**
Menu entry swapper for POH

**Describe the solution you'd like**
Make a menu entry swapper entry for the mounted jewelry in the PoH (Currently just the mounted glory, but when the portal nexus room comes out add the Digsite pendant and Xeric's talisman assuming they work the same as the glory)

**Additional context**
Good for people who farm rune dragons, or go to fossil island for trees/herbivore/Bird house runs for the mounted digsite pendant.

**Comment by deathbeam** [comment]
I personally think this is bad idea, but leaving this open so other people can comment

**Comment by KasparRosin** [comment]
I think it doesn't needs a MES.

**Comment by JZomerlei** [comment]
I can create this for you, you will be able to maintain an updated plugin... You will need to compile & build through InteilliJ.

**Comment by ollieatkinson** [comment]
You can already configure the left-click options in-game, there is no reason to add this feature to RuneLite.

**Comment by JZomerlei** [comment]
I had no idea lol I’m f2p for now yet

**Comment by deathbeam** [comment]
Yeah this is not really necessary
