### ISSUE TITLE
Potion notification

### ISSUE THREAD

**Issue by GenericGames** [runelite/runelite#6249]
**Is your feature request related to a problem? Please describe.**
When fighting monsters that a potion that is not a boost assists in fighting I forget to take the potion (Dragons specifically)

**Describe the solution you'd like**
A toggle notification when potions are about to wear out, as they wear out.

**Comment by deathbeam** [comment]
You can already use chat notifier for this

**Comment by deathbeam** [comment]
And we closed https://github.com/runelite/runelite/issues/3443 for same reason and this is basically duplicate of that
