### ISSUE TITLE
Custom Cursors

### ISSUE THREAD

**Issue by 0hi** [runelite/runelite#6253]
Hello, I was wondering runelite could have a custom cursor feature like the one in OSB and Konduit that uses a RS2 2010/2012 style cursor on the client. Thank you

**Comment by deathbeam** [comment]
Duplicate of #2068

**Comment by 0hi** [comment]
> Duplicate of #2068

Hey, I know this is a duplicate. But the original suggestion was closed with the answer "No because it could cause problems". So this could never be suggested or implemented because of that response?

**Comment by Nightfirecat** [comment]
Until/unless we find a way to work around that issue, that's correct.

**Comment by deathbeam** [comment]
#2068 is still open
