### ISSUE TITLE
Xp Progress Bars

### ISSUE THREAD

**Issue by tmk2003** [runelite/runelite#6265]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to see an overview of **all** my skills progression on my screen at all times.

**Describe the solution you'd like**
I would like to see something similar to an MMO xp bar (see wow) where I can constantly see progression in *all* my skills. The overlay would include multiple, differently colored bars stacked, showing the percentage of progress for that skills current level.

**Describe alternatives you've considered**
The Jagex Xp widget and the Xp globes. However, the Xp Globes disappear and only show currently utilized skills. The Jagex Xp widget does not allow for **all** the skills to be shown at once.

**Comment by KasparRosin** [comment]
Doesn't the current XP Tracker offer basically the same feature? Or is there something I'm misunderstanding.

**Comment by deathbeam** [comment]
You have XP tracker, so you can see it on your screen if you open sidebar. Otherwise there is vanilla interface where you can hover on skills
