### ISSUE TITLE
Add support for popout sidebar

### ISSUE THREAD

**Issue by tmk2003** [runelite/runelite#6267]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when using some runelite features that reduce my game screen space, especially when the feature is used constantly. I would like to be able to utilize multiple monitors with runelite effectively.

**Describe the solution you'd like**
As a desktop user, I would like the ability to popout runelite features (i.e. plugins, worldswitcher, notes) to a separate window to increase the viewport space.

**Comment by Hubcapp** [comment]
I'd like this too. On an 800x600 screen, there is no room for the sidebar. I know you're thinking "800x600? that's clearly a deprecated desktop resolution", but playing in fixed mode, this is the original minimum resolution RS2 was designed for back in 2003, and it still looks great today, except for the fact that there's no room for runelite's side bar.

At the other extreme, on a 4k screen, the sidebar is very hard to read. If it were in a separate window, it would be possible to either put the sidebar on a screen with more DPI, or if the WM_CLASS property for the sidebar-popout window were different, with some window managers it would be possible to create custom rules to scale it automatically.

**Comment by abextm** [comment]
Duplicate #2463
