### ISSUE TITLE
Add Points Per Hour marker at NMZ

### ISSUE THREAD

**Issue by fairyfoam48** [runelite/runelite#6268]
I'm trying to maximise my points per hour at NMZ and can figure out the amount of points I'm getting per hour by figuring out how many doses of overloads I've taken and multiplying it until it reaches the equivalent of 1 hour of doses of overloads

for example, 100k points in the first 5 minutes means 1.2m points per hour. 150k points in 10 minutes means 900k points per hour

not sure of the formula required but surely this wouldn't be super complex
![pph](https://user-images.githubusercontent.com/43065852/47752107-73f16480-dcf8-11e8-8251-d494a359930b.png)

**Comment by samuelengland** [comment]
I'll take a look at this.

**Comment by Haashi** [comment]
A solution in #6701
![image](https://user-images.githubusercontent.com/29370205/49031271-cca60700-f1a9-11e8-9671-2a1479c23677.png)
