### ISSUE TITLE
Shift Click Banking

### ISSUE THREAD

**Issue by KPndaD2** [runelite/runelite#6272]
**Is your feature request related to a problem? Please describe.**
No.
Switching between the 1, 5, 10, x, and all bank buttons can get annoying.

**Describe the solution you'd like**

Option to set bank shift click to 1, 5, 10, x, or all.

**Describe alternatives you've considered**

Hotkey to cycle through the buttons. 
E.G. if it's set to 1... tap shift... and now it's on 5.

**Additional context**

N/A

**Comment by raiyni** [comment]
that would be faking input

**Comment by deathbeam** [comment]
We don't want to swap any menu entries in bank interface

**Comment by KPndaD2** [comment]
Gotcha. Thanks
