### ISSUE TITLE
Runecraft Pouch Menu Entry Swap

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#6277]
Runecrafting pouches are able to be filled while in a bank by right clicking them and selecting "Fill". This is slow and can be annoying. Obviously you can exit out of the bank and single click to fill them, however, at Ourania Altar you are charged to use the bank so being able to do everything quickly in a single bank is ideal.

My idea is to raise "Fill" to the top while in a bank, otherwise have "Empty" as the default option.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
