### ISSUE TITLE
Menu entry swapper for Runecrafting pouch fill option

### ISSUE THREAD

**Issue by Malfuryent** [runelite/runelite#6278]
**Is your feature request related to a problem? Please describe.**
Jagex allowed us to fill runecrafting pouches from within the bank, now it would be nice
if you could left click fill with the bank interface open instead of having to right click fill.
This would be a huge quality of life upgrade for runecrafting.

**Describe the solution you'd like**
make fill option with bankinterface open on top in the inventory instead of deposit.
probably an addition to the menuentryswapper.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
