### ISSUE TITLE
Please add konduits chambers of xeric features:)

### ISSUE THREAD

**Issue by Littleblueju** [runelite/runelite#6282]
- auto-tagging Vanguards NPCs with their respective color from the combat triangle
- Vanguards displays all of their HP percentages close together

- targets of various projectiles like vasa stones and shaman poison

-crystal bombs timer

Please add these, would make the awesome client even better!

**Comment by Hydrox6** [comment]
> targets of various projectiles like vasa stones and shaman poison

https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
