### ISSUE TITLE
"Pirate" highlighted during Rat slayer task

### ISSUE THREAD

**Issue by Nickenator8** [runelite/runelite#6285]
**Describe the bug**
When doing a Rat slayer task on my obby mauler i noticed that a nearby Pirate was highlighted

**To Reproduce**
1. Get Rat slayer task
2. Go to a Pirate

**Expected behavior**
A pirate is not a rat

**Screenshots**
https://i.gyazo.com/52348c4088e4de6aa9994a551cdaadd3.png

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.4.23
 - Launcher version: 1.6.0

**Comment by KasparRosin** [comment]
Could the rat have been under him and that's why he was highlighted?

**Comment by Hydrox6** [comment]
@KasparRosin this happens because the Slayer Plugin uses strings to find what to kill, as opposed to NPC IDs. The check that's used is a simple `String#contains`, and since `Pirate` contains `Rat`, it highlights them.

**Comment by Nickenator8** [comment]
@KasparRosin exactly what @Hydrox6 said. it has it's own highlight box (idk what you call it)

Thought it might just be a simple fix so I reported it. It's not a big deal at all really
