### ISSUE TITLE
Entity Hider Addition request

### ISSUE THREAD

**Issue by OffensiveExile** [runelite/runelite#6287]
**Is your feature request related to a problem? Please describe.**
I frequently run essence to players at ZMI and I have to toggle the Entity Hider addon while running and waiting for the crafter. In detail, I enable entity hider while at the altar to see the clan member's animation and I disable it while running so I can follow the player in front of me.

**Describe the solution you'd like**
I would like for users to be able to select an area in which the entity hider is enabled and then disabled elsewhere. Maybe have the original options changeable for every set of coordinates given.

**Describe alternatives you've considered**
The only alternative would be to just have the current settings with a region selector and it is enabled while in that region and disable while not.

**Comment by deathbeam** [comment]
Just use the attacker check in entity hider I guess, otherwise no this will not be implemented
