### ISSUE TITLE
Highlight clickbox for Herbiboar

### ISSUE THREAD

**Issue by Dyliotic** [runelite/runelite#6289]
**Is your feature request related to a problem? Please describe.**
Been doing herbiboar for a few days now, and sometimes I forget to harvest the Herbiboar because I am braindead focussing on clickboxes while watching a tv show.

**Describe the solution you'd like**
A simple clickbox highlight when you are able to harvest the herbiboar would be awesome. Maybe even highlight the Herbiboar run after you harvested the Herbiboar.

**Describe alternatives you've considered**
There are none.

**Additional context**
![image](https://user-images.githubusercontent.com/44668710/47846452-31975880-ddc8-11e8-8b21-9d05d884f1df.png)

I hope this explains it.

**Comment by deathbeam** [comment]
Duplicate

**Comment by Dyliotic** [comment]
How is this duplicaten it isnt in the game

**Comment by Hydrox6** [comment]
It's a duplicate because someone has already made an issue about it

**Comment by Dyliotic** [comment]
> It's a duplicate because someone has already made an issue about it.
> 
> #1899

Thank you, there is a good solution. Sorry, first time using github and couldn't find it
