### ISSUE TITLE
Loot tracker does not track coins picked up by ring of wealth

### ISSUE THREAD

**Issue by OlavH96** [runelite/runelite#6290]
**Describe the bug**
Coins dropped (by Kurasks in this case, only happens to Kurasks?), does not show up on the loot tracker.

**Expected behavior**
Loot tracker should show coins dropped even if picked up by RoW.

**Screenshots**
https://i.imgur.com/JGbkh58.png
The coin drop that was tracked was because I had not enabled my RoW, the rest was not tracked.

**Environment (please complete the following information):**
 - OS: Linux Mint
 - RuneLite version: 1.4.23

**Comment by deathbeam** [comment]
we already have issue for this, this is duplicate
