### ISSUE TITLE
Disabling stretched mode plugin in resizeable mode does nothing

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#6294]
Without manually triggering canvas resize after disabling the plugin the stretched resizable mode will not disable.

**Comment by devLotto** [comment]
I cannot reproduce this. Disabling the plugin does remove the stretching/scaling for me.

**Comment by Nightfirecat** [comment]
I was testing this last night and noticed it doesn't immediately resize (either when turning on or off), but you don't need to resize canvas; it will in a short time re-trigger it.

**Comment by deathbeam** [comment]
Try with integer scaling

**Comment by devLotto** [comment]
With integer scaling enabled it does not resize back, you're right.
