### ISSUE TITLE
Hot/cold clue finder doesn't display an arrow when the correct solution is found

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#6313]

**Comment by MagicfTail** [comment]
This one was beside the bar on Mos Le'Harmless, but i assume it's the same for all of them

**Comment by MagicfTail** [comment]
Another step where it happens, so it is probably for all hot/cold clues https://i.imgur.com/fKeqtfN.png

**Comment by Nightfirecat** [comment]
I believe this has long since been fixed.
