### ISSUE TITLE
Highlight the tile that container hidden player entity

### ISSUE THREAD

**Issue by arthurtyukayev** [runelite/runelite#6319]
In response to this person's complaint on twitter:
https://twitter.com/LavineOSRS/status/1058519281229594624

Simplest solution would be to highlight the tile if it contains a hidden player entity. Assuming it's a valid concern?

**Comment by deathbeam** [comment]
Entity hider is used to hide entities, if we will keep drawing stuff after they are hidden what is the point? Also that person's tweets make no sense, so I would not base anything off them.
