### ISSUE TITLE
Examine Price Info Inside Looting Bag

### ISSUE THREAD

**Issue by alanbaumgartner** [runelite/runelite#6320]
When examining an item inside of a looting bag, it doesn't show GE and high alch values when it is enabled.

1. Enable "item prices" plugin which shows an items high alch and GE price an item after examining (or whatever the plugin that enables the examine price text is)
2. Open a looting bag with items inside.
3. Right click examine an item.

**Expected behavior**
The price info an item would be shown similarly to an item outside the looting bag.

 - OS: Windows 10
 - RuneLite version: 1.4.24

**Comment by Adam-** [comment]
Added in #6333
