### ISSUE TITLE
Move the Sidebar to the bottom of the client as a toggleable feature

### ISSUE THREAD

**Issue by deviize** [runelite/runelite#6327]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

It's annoying having a sidebar on the side of a client when alot of runescape players have half the monitor for a Internet browser and the other half containing runelite, it makes it awkward to use the sidebar, having an option to move it to the bottom of the client would eliminate all problems.

**Describe the solution you'd like**

Give an option to move the sidebar to the bottom of the client instead so when you click on a tab (e.g, stats - it extends to the bottom and not from the side).

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

N/A

**Additional context**

N/A

**Comment by raiyni** [comment]
duplicate https://github.com/runelite/runelite/issues/1641
