### ISSUE TITLE
Show friends in friend finder that dont have you added

### ISSUE THREAD

**Issue by Yoobs** [runelite/runelite#6329]
**Is your feature request related to a problem? Please describe.**
On other clients it shows people who you have added but don't have you added back, this is useful for clan pking.

**Describe the solution you'd like**
To display the people you have added show like the people that you have added and have you added back.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Hydrox6** [comment]
[Rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
