### ISSUE TITLE
Snail meat is missing food heal hover overlay

### ISSUE THREAD

**Issue by Hubcapp** [runelite/runelite#6332]
Thin snail meat heals between 5 and 7 according to the wiki. 6 hp healed at 73 hitpoints level.
Fat snail meat heals between 7 and 9 according to the wiki. 7 hp healed at 73 hitpoints level.

Lean snail meat also exists.

**Comment by samuelengland** [comment]
@Hubcapp Do you mean 8 hp at 73 for fatsnail?

**Comment by Hubcapp** [comment]
I think it's actually random and not dependent on HP level.

**Comment by samuelengland** [comment]
https://github.com/runelite/runelite/pull/6362
