### ISSUE TITLE
Examination of Small crystal seed shows wrong High Alch value

### ISSUE THREAD

**Issue by Thexus** [runelite/runelite#6340]
**Describe the bug**
It shows that the HA value is 6000, while you can't alch it.

**To Reproduce**
1. Complete The Eyes of Glouphrie
2. Train magic up to 55
3. Buy a nature rune and 5 fire runes
4. Try to alch the seed
5. It says "You can't do that to elven crystal!"

**Expected behavior**
I expected to find a new money making method, because you can get more with the drop trick.

**Screenshots**
https://cdn.discordapp.com/attachments/290559371656822784/508611720722382848/unknown.png

**Environment (please complete the following information):**
 - Windows 7
 - RuneLite version: 1.4.24
 - Launcher version: couldn't find it

**Comment by deathbeam** [comment]
But it's high alch value is still it's high alch value even if you can't alch it, we should HA for all items
