### ISSUE TITLE
Raids private storage reminder

### ISSUE THREAD

**Issue by psikoi** [runelite/runelite#6341]
**Is your feature request related to a problem? Please describe.**
I almost always finish a raid and continue on playing completely forgetting that i have items still on my private storage.

**Describe the solution you'd like**
A reminder overlay that reminds me to collect my stored items.

**Comment by Hydrox6** [comment]
For anyone who wants to do this, there is a message when you leave a raid with items in private storage. Add that message to the Chat Notification plugin
