### ISSUE TITLE
Split Private Chat Recolour Not Fully Working

### ISSUE THREAD

**Issue by montrers** [runelite/runelite#6351]
**Describe the bug**
The split private chat recolour does not work for the colon (':') nor the '_ has logged in/out' text. 
I have both transparent and normal recoloured, with both names and messages. 

**Screenshots**

![screen shot 2018-11-05 at 4 29 51 pm](https://user-images.githubusercontent.com/42737438/47977038-c7115000-e11a-11e8-8f13-5e55df7a0371.png)

**Environment (please complete the following information):**
 - Mac OS
 - RuneLite version: 1.4.24
 - Launcher version: Unknown

**Comment by Nightfirecat** [comment]
Is this still an issue?
