### ISSUE TITLE
Moveable Inventory Pane

### ISSUE THREAD

**Issue by hhaag** [runelite/runelite#6355]
It would be very nice to be able to move the inventory and possibly the other panes when in resize-able mode. I think a lot of us choose to play in fixed/stretched fixed simply because on larger monitors the distance you have to move your mouse cursor from the center to the bottom right is just too far.

I would love to be able to snap & unsnap things like my inventory (or even just one entire panel for everything) to a more central position on my monitor. Yes, it would hinder your vision but being able to have that inventory pane closer to the center of your large monitor or wherever you wanted it would be quite nice.

I have never taken a look at the code myself, but since it was doable with the map and other objects, I'd assume there has to be some way?

**Comment by deathbeam** [comment]
This can be abused and so won't be implemented
