### ISSUE TITLE
Pvp Hybrid Luck calculator

### ISSUE THREAD

**Issue by ytthrowaway** [runelite/runelite#6357]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
I'm always frustrated when I have a hybrid fight and I feel like I'm getting extremely bad rng and that is why I'm losing.

**Describe the solution you'd like**

Create a feature that shows how lucky you are in pvp fights. Reset every new opponent or out of combat for 20 seconds. While in combat, take into account your chance to hit and whether you do. What your average hit is if you are successful and what you actually hit. Also your chance to defend their attack and if they hit, their average hit if successful and what they actually hit. Keep track over the entire fight and display how unlucky/lucky you are. If you are able to just grab their stats and gear bonuses do that, if not allow you to enter an approximation of what you figure their gear/stats to be.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Abextm** [comment]
This is far too complicated for an niche feature that does't actually help any.
