### ISSUE TITLE
Camera zoom plugin is causing game crash when zooming too much

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#6358]
As reported in Discord, when zooming in with camera zoom enabled near Chambers Of Xeric, the game crashes (but without anything in log). The sidebar is still interactable so it is just applet exploding.

[game-crash](https://gyazo.com/c619a6eac76a0b4f410daa6ef488adba)
[sidebar-working](https://gyazo.com/a4778dce062f5a0e26b55f3561a08b35)
[application.log](https://pastebin.com/ShZ8XBsL)

**Comment by Adam-** [comment]
This is a crash from Rasterizer3D_zoom being set to 0 from the extended zoom in distance
