### ISSUE TITLE
chat highlight notification noticing smaller words in bigger ones

### ISSUE THREAD

**Issue by allowe786** [runelite/runelite#6359]
this is a bit hard to explain so ill do my best.
currently, the chat notification feature can only warn you when a word is being said by itself however, if a word is being said in a bigger word, you wont get a notification. For example, if someone says "mattttttt" and you have the word "matt" in the chat highlight notification, you wont get a notification saying that the word matt was said. is there a way to add a feature that could trigger a notification when smaller words are being said in a bigger word?

(i hope this made sense haha)

**Comment by deathbeam** [comment]
This is intentional, there needs to be word separator around target word
