### ISSUE TITLE
xp globe moved to centre of screen

### ISSUE THREAD

**Issue by uknownname** [runelite/runelite#6360]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
the xp globe has moved from top of client to just above middle ( see screenshot)

**Screenshots**
![2018-11-05_23-32-48](https://user-images.githubusercontent.com/44790151/48033632-fee8b980-e153-11e8-84a8-45a237dd490b.png)

**Environment (please complete the following information):**
 - OS:  Windows
 - RuneLite version: 1.4.24
 - Launcher version: 1.6.0

**Comment by raiyni** [comment]
hold alt and move them.

**Comment by uknownname** [comment]
thank you, didnt know about that
