### ISSUE TITLE
Notifications/Popups appearing on KDE

### ISSUE THREAD

**Issue by Odzinic** [runelite/runelite#6364]
When using the KDE desktop environment the notifications for Runelite do not appear in the standard notification way. Occasionally, small notification boxes appear in random locations across the screen and contain text such as "User is now idle" but they do not always popup and are not very visible. Sometimes the notification do not appear it all even after the notification setting is checked off and on.

A notification system similar to the way Runelite works in the Gnome desktop environment would be excellent because it would cause Runelite notifications to appear like other system notifications and be much easier to notice.

I am using Kubuntu 18.10 with KDE 5.51.0 and Plasma 5.14.2. The same issues occurred in Plasma 5.12 and 5.13. I am unfortunately unable to screenshot the notification that does appear because I have not been able to trigger it again.

**Comment by Nightfirecat** [comment]
What is the standard notification utility for KDE? As-is, [we're calling `notify-send` to issue notifications](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/Notifier.java#L211) on UNIX platforms.

**Comment by deathbeam** [comment]
1. Enable send notifications when focused, 2. if notify-send is not working for you install it, otherwise fix it.
