### ISSUE TITLE
Allow shift anti drag to better interface with shift dropping

### ISSUE THREAD

**Issue by SheepySean** [runelite/runelite#6365]
Currently shift anti-drag is quite a nice feature but the issue is that it maps to the same key binding as shift dropping. This means utilizing anti-drag, requires you to disable shift dropping which albeit works but can be really annoying, especially when you forget to re-enable shift dropping and you accidentally left-click something, like a brew, when you though you were dropping it.

**Potential Solutions**
 * Add ignorable items for shift dropping. Similar to a feature that exists in OSBuddy, you can configure items that will be ignored by shift dropping (by setting the click option of the item when shift is held, drop->use).
 * Allow remapping of anti-dragging. Potentially either a select from a choice of preset keys or user's personal choice of keys as opposed to **Shift**, which could remain as the default. Potential key choices could be things like **Ctrl**, **Alt**, or **Function Keys**.

**Comment by Abextm** [comment]
This is by design

**Comment by SheepySean** [comment]
Why is it by design though? To comply with Jagex requirements or code base support?
