### ISSUE TITLE
More information on tooltips for hiscore entries

### ISSUE THREAD

**Issue by tylerjameshurst** [runelite/runelite#6368]
I, like a lot of newer players; are not 100% familiar with all of the entries on the hiscores, and some entries have no information as to what the rank is. (The bottom two ranks and the second to bottom right rank)

All other entries say the skill name of the entry, for consistancy and to save players the trouble of going to the hiscores to try and find out what those are, perhaps the tooltip could read: 
"Last man standing"   
"Rank: X"                   
etc
![image](https://user-images.githubusercontent.com/31933584/48046747-2727e680-e15b-11e8-9175-d4454e7f0c9c.png)

**Comment by Nightfirecat** [comment]
Added in 2f85f574875f13ad60317ecfc2a4a79727ccef04
