### ISSUE TITLE
Phishing targetting new users

### ISSUE THREAD

**Issue by JBerben** [runelite/runelite#6369]
Phishing website which abuses the fact that ads put searched keywords at the top of results.
- Site mimics RuneLite's and includes a mirror to a modified/infected jar from their Dropbox.

- https://runeliteclient.com/

- https://runeliteclient.com/download-post.php

Thought I might put this out there due to the fact that the owner of the website probably hasn't removed all of the web service features the RuneLite has. It might be possible for the one of the devs to give an alert.

**Comment by deathbeam** [comment]
We are aware of this, and opening issues with links to phishing sites is not good idea, so closing
