### ISSUE TITLE
runecrafting pouches

### ISSUE THREAD

**Issue by kahmazah** [runelite/runelite#6376]
Hello, is there anyway you can make that pouches are green or red based on the fact are they are filled or empty and if its not hard to code, i would recommend to make them show when they going to degrade.

**Comment by Nightfirecat** [comment]
This used to be in the client until Jagex changed the way that the client gets information about runecrafting pouch filled statuses with the fill/empty-in-bank feature. We removed the feature after that since we can no longer accurately display that information.

**Comment by Nightfirecat** [comment]
Also, duplicate of #5667
