### ISSUE TITLE
Add the Taverley outhouse stile to the agility shortcut plugin

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#6378]
![image](https://user-images.githubusercontent.com/34870401/48151767-6d4b8a00-e2c2-11e8-9ce8-c21e7b5ff5c4.png)

**Comment by JeljoGb** [comment]
Also this one at Burgh de Rott
![image](https://user-images.githubusercontent.com/34870401/48152750-fe236500-e2c4-11e8-923b-56fd41b4fffd.png)

**Comment by deathbeam** [comment]
Create new issue for that ^then

**Comment by JeljoGb** [comment]
Will do
