### ISSUE TITLE
Add small indicators for farming Trees/Herbs in game

### ISSUE THREAD

**Issue by 4tson** [runelite/runelite#6382]
Add trees/fruit trees/herbs as indicators in the same bar as slayer monsters/skill boost info for when all trees and fruit trees are ready to be checked. I know this info already exists in the sidepanel, but it would be more convenient to have it in game, maybe have it require relogging so as not to be too overpowered and work as a notification that the patches are ready.

Alternatively it could always be there and have the info of each patch on the tooltip, although that feels even more overpowered. 

Thank you.

**Comment by Abextm** [comment]
Close enough to #2212
