### ISSUE TITLE
Add Avernic defender to bank value

### ISSUE THREAD

**Issue by troypressley1** [runelite/runelite#6384]
When you combine the Avernic defender hilt with the Dragon defender and store it in your bank, it doesn't add any value to it. A lot of the untradeable items have their value in there. It's sad seeing your bank drop 100m in value even though it really hasn't

**Comment by Kamielvf** [comment]
It doesn't have 100m value because when you remove the hilt, it is lost. The item only has a 1,5m alch value (or whatever it is).

**Comment by troypressley1** [comment]
By that logic it has no value since it can't be alched.

**Comment by Kamielvf** [comment]
I don't know, have you tried?

Jokes aside, if that's the case then it should not have a value linked at all, so that's something that needs to be fixed then.

**Comment by deathbeam** [comment]
Duplicate of #3622 basically
