### ISSUE TITLE
runlite window can't be dragged across multiple monitors

### ISSUE THREAD

**Issue by Tyler81198** [runelite/runelite#6387]
I run a dual monitor setup and would like to have runelite on my secondary monitor while I do something else on the primary one, however when I attempt to drag the runelite window across to my other monitor it stops at the border between them and refuses to go any further.

**Comment by deathbeam** [comment]
Disable "contain in screen" in RuneLite settings and/or disable custom window chrome too

**Comment by d4ng0** [comment]
Disabling window chrome did the trick, thanks @deathbeam!
