### ISSUE TITLE
Portal Nexus Menu Entry Swap

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#6390]
The new Portal Nexus in player-owned houses has two main options people can select from in the menu; the left-click option the house owner set, or Teleport Menu.

This suggestion is to raise Teleport Menu to the left-click option so you can then quickly select your destination.

**Comment by deathbeam** [comment]
```
[2:02 PM] magic fTail: You can already do that :thinking:
[2:03 PM] Jake 🍔: :joy:
[2:03 PM] Malfuryent: yeah xD
```
