### ISSUE TITLE
3 minor issues

### ISSUE THREAD

**Issue by Handegg** [runelite/runelite#6392]
1). When using RuneLite, the default Old School xp tracker always appears on the right side, even when I have 'Middle' selected.

2). When I log into the client it's not saving my settings after I close & re-open.

3). When setting up Bank Tags, it's across accounts. So if I set bank tags for my Ironman, it'll be the same on my main which is not overly problematic, but still a bit of an issue.

**Comment by raiyni** [comment]
1 bug per issue,

2. Sign in to an account

3. we know

**Comment by Handegg** [comment]
Thank you for the swift response

**Comment by deathbeam** [comment]
We have issues for this
