### ISSUE TITLE
UAC Prompts in Windows cause blank screen with Stretched Mode on

### ISSUE THREAD

**Issue by widget-** [runelite/runelite#6394]
## Describe the bug

When

- Stretched mode is enabled
- HW acceleration is enabled (probably)
- Runelite is ran on Windows

Then

- Having a UAC prompt open (the run as administrator dialog) will cause the game canvas to go white while Stretched Mode is enabled.

This can be worked around by dragging the window to another monitor, at which point it seems like the graphics gets re-initialized.

This has been happening for the last few months for me.

## To Reproduce
1. Be on Windows
2. Turn on Stretched Mode
3. Run anything as an administrator
4. Observe that the game screen is now completely white
5. Move Runelite to another monitor
6. Observe that the game screen is back

## Expected behavior
1. Not having the game vanish

## Screenshots

Screen recording starts just after the UAC prompt because ShareX ends recording at the prompt. Just before it has the game showing normally.

This laggy GIF shows
- Just after the UAC prompt (white screen)
- Toggling stretched mode off then on (to show that it's only with it on)
- Dragging the game to my other monitor and back, which fixes it.

![2018-11-08_09-54-49](https://user-images.githubusercontent.com/7691630/48210149-65c8c700-e33c-11e8-981c-23b533b49d07.gif)

## Environment (please complete the following information):
 - OS: Windows 10 Home x64 v1803 build 17134.345
 - RuneLite version: `master` branch, currently `1.4.25-SNAPSHOT`
 - Launcher version: `Unknown`

## Additional context
Logs look normal - no exceptions or warning thrown.

Apparently people have been correlating this with League of Legends (LoL) and the Blizzard Launcher. The Blizzard Launcher seems to need admin privileges and maybe LoL does too for major updates.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by widget-** [comment]
Well yes, but if hardware acceleration is enabled by default then I would think this should be tracked.

**Comment by deathbeam** [comment]
We mostly can't fix it, and it is all just 1 issue with hw accel, having separate issues for some specific scenarios is not really helpful
