### ISSUE TITLE
Bank Tags Disappear (still)

### ISSUE THREAD

**Issue by FaxOsrs** [runelite/runelite#6401]
Every time I setup bank tags and start a new client, the tags disappear entirely. It seems to keep them if i don't start a new client. The tags that disappear are copy codes from a discord that use item IDs (copy -> import tab), but it also removes items I tagged myself for those same bank tags and ones I have created myself. This has happened to me several times over the past couple weeks. It's super frustrating after setting up everything for bosses and raids, only to lose it next time I log in.  Hope there is a fix or something I can do about it.

Misc info:
I do run an alt using the same client, but the settings are the same on both. 
RL ver: 1.4.25
OS rev: 176
Launcher ver: 1.5.2 

"gear" discord.

**Comment by deathbeam** [comment]
This is not related to bank tags. Running 2 clients means that every setting that you made in the session is deleted when you modify some setting on other client. And I believe we already have issue for adding per-account settings for bank tags, so closing
