### ISSUE TITLE
Refresh OSRS Within Client

### ISSUE THREAD

**Issue by A-MagicianRS** [runelite/runelite#6405]
The idea behind the refresh button would be to allow people to save their XP Gains, their Loot Tab, etc. for longer than a week at a time.
Clicking it would just reload OSRS after there has been an update released, without clearing the other data saved within the Runelite client.
![refreshclient](https://user-images.githubusercontent.com/44888108/48243264-4493c500-e394-11e8-908e-23587f9a8e35.png)

**Comment by deathbeam** [comment]
You can't avoid update like this, as RuneLite needs to be updated too. And keeping client open for long periods of time ignoring RuneLite updates is highly discouraged, so closing this as wontfix
