### ISSUE TITLE
Username/account manager. 

### ISSUE THREAD

**Issue by lulwut** [runelite/runelite#641]
Since I often play alts and with friends accounts I often have to type the long email and pw. So I switched to short keys and now typing a few letters inputs my details.

What I think would be handy would be able to *only* store a list of login usernames and  then when a login is picked from a list the client automatically sends it to the username text field.

Obviously security is an issue, I'm unsure if something like storing logins as salted hashes would work. In addition instead of selecting an account name, you can define an account as simply "main" and that would be the extent at which the client would show the login, add in the automatic turning on of hiding usernames and it would provide an additional layer of security from keyloggers and RATs. As well as this it allows quick logins to alt accounts. I don't think this feature request should be given a high level of priority, but it would be a neat thing to have. 

Just clarify, at no point would a password be stored. The user can find a solution for that or just type it out.

**Comment by ypperlig** [comment]
In my opinion this is probably not a great idea.

There already exists great password managers already which are under review/audit constantly such as KeePass, which also supports copy-pasting to login screen.

**Comment by deathbeam** [comment]
This looks like something that we do not want to do, and otherwise there is already issue for multiple profiles, that work with remember username plugin

**Comment by jwiliker** [comment]
I like this idea.  Would be extremely helpful for those that multiclient.

**Comment by Nightfirecat** [comment]
As mentioned, we are unlikely to implement this feature. We would recommend using a password manager, as that would allow auto-typing or auto-pasting your account details into the login screen. (see the "Ctrl-V paste" option of the Login Screen plugin)

If you're interested in seeing something like this becoming a part of the base client, I would recommend sending this request directly to Jagex, as they would be able to implement this feature in a way which would not compromise account security.
