### ISSUE TITLE
Add a right click option to the death timer thing to clear it.

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#6410]
![image](https://user-images.githubusercontent.com/34870401/48270772-203ef380-e43b-11e8-9861-932cb22ce466.png)
Instead of having to search for the plugin, let us just right click clear it.

**Comment by newcomer9087** [comment]
I would like to have an option to reset it meaning it will go away once I reset it and wont come back again till I get killed again.

**Comment by JeljoGb** [comment]
That option exists, it's in the death plugin.

**Comment by Adam-** [comment]
This is probably not gffc due to that we cannot currently add menus to individual infoboxes.
