### ISSUE TITLE
Online tracker does not handle name changes

### ISSUE THREAD

**Issue by xmagepurx** [runelite/runelite#6421]
**Is your feature request related to a problem? Please describe.**
When you change your username, you cant view experience gained on your previous username unless you search for it specifically.

**Describe the solution you'd like**
Perhaps an "update username" button? If the date the original username stopped gaining xp and the new user gained xp is the same, the update check out.

**Describe alternatives you've considered**
Manual username verification and/or checking

**Comment by Nightfirecat** [comment]
We removed the runelite.net xp tracker in runelite/runelite.net@da1125eef30047ae488187736546722626c5ea16 and removed the link to it from the client in 9214480a02c98e0835f59ca181c373e689209d7b, so this no longer applies.
