### ISSUE TITLE
Bank tags only show the first tag in its Tags

### ISSUE THREAD

**Issue by JarJarr** [runelite/runelite#6422]
My bank tags will only show the very first tag I have it listed under.

For example: I have my Slayer Helmet tagged with "kq sire dk goril" and the item will only show under the "kq" tag.

This happens will any tagged item, and always only shows the very first tag.

Any help or advice would be greatly appreciated!

**Comment by Kamielvf** [comment]
Note that your tags need to be comma separated, is this the case?

**Comment by JarJarr** [comment]
Yes it was, that was fast! It had always worked without them for me until a week ago, thanks!

**Comment by Nightfirecat** [comment]
That's because they weren't quite working correctly for a long time. :P
