### ISSUE TITLE
Anything lower than 40 attack & Anything lower than 15 Prayer won't show up on HiScores

### ISSUE THREAD

**Issue by runelitepk** [runelite/runelite#6423]
For example, if someone is 13 prayer it won't show up on HiScore. It will say "Unranked" Same goes with Attack. Anything lower than rune (40 attack) won't show up on HiScores. I'm pking on a low level at the moment so i'd like to know if they're 1 attack, 5 attack, 10 attack, 20 attack or 30 attack. It just shows "Unranked" 

Basically what i'm trying to say is that 40 attack & 15 prayer shows up on HiScore but not 13 prayer & 30 attack.

**Comment by deathbeam** [comment]
If they are not on hiscore then they are not on hiscore otherwise I am pretty sure the plugin is fetching data from hiscores correctly.

**Comment by runelitepk** [comment]
What exactly do you mean by i they are not on hiscore then they are not on hiscore? If a player has 13 player, why won't it show on HiScore? Instead it shows "Unranked" Same goes with anything lower than 40 attack...

**Comment by Adam-** [comment]
We don't control what is and is not on the hiscores.

**Comment by runelitepk** [comment]
Ok so i checked if OSbuddy have the same problem but they don't. OSbuddy shows 13 prayer and 30 attack, which means you should be able to control it, no? Only Runelite shows "unranked"

**Comment by Adam-** [comment]
Do you have a name of a player which osb shows levels for and we do not?

**Comment by runelitepk** [comment]
Sorry for late response, take this player for example: "Magnet o" he is 5 def with 13 prayer but doesn't show. Says "unranked", osbuddy shows 5 def and 13 prayer. Now for attack, look up "Change dark" he is 10 attack which shows on osbuddy but not Runelite. So again, anything under 15 prayer and 40 attack won't show. I believe 14 prayer shows but not 13 and under, very weird. Now look up "x-spec2wreck" he is 30 attack which shows on osbuddy but not runelite.

**Comment by Kamielvf** [comment]
OSBuddy maintains their own hiscore/xp tables, they don't fetch from the osrs ones (which we do
).
See https://secure.runescape.com/m=hiscore_oldschool/hiscorepersonal.ws and look him up, you should expect the same results from runelite.
