### ISSUE TITLE
Add a clear all option to the inventory tags plugin

### ISSUE THREAD

**Issue by casper20051** [runelite/runelite#6427]
![inventorytags](https://user-images.githubusercontent.com/3000350/48310498-46a97f80-e55e-11e8-8462-d87347e030c1.jpg)
Instead of having to remove all inventory tags one item at time, add an option to remove all of them.

**Comment by Nightfirecat** [comment]
@casper20051 Why did you close this issue? A fix for this request hasn't been merged yet...
