### ISSUE TITLE
Double fingered scroll on mousepad registers as a click.

### ISSUE THREAD

**Issue by ZeroTroubles** [runelite/runelite#6434]
I couldn't find any open bug reports on this issue, so please forgive me if I missed an open issue somewhere.

**Describe the bug**
Whenever I use my mousepad on my XPS 15 9560 laptop to scroll, dragging two fingers from down to up, RuneLite picks up the input as if I'm scrolling, but also as if I'm constantly clicking. I checked to see if it's my OS. I'm running on Ubuntu 18.04, and couldn't find a specific option that would cause this issue. It also does not happen in any other program, so we can exclude that it's a hardware issue. It might still be caused by my drivers somehow, but I can't reproduce it in any other software I tried.
I'm running the 'All Platform' version, with `java-11-openjdk-amd64`, using the command `java -jar RuneLite.jar mode=OFF` (so without hardware acceleration)

This is extremely frustrating because when you want to scroll through, for example, your bank, you'll end up clicking a ton of times, withdrawing items you do not wish to withdraw, or you might accidentally click somewhere on the game floor and walk away from the bank, closing the interface.

**To Reproduce**
1. Log on
2. Mouse over any area you want to scroll (for example just anywhere on the screen to zoom in/out)
3. Scroll up/down
4. See the scroll working but also a few clicks registering

**Expected behavior**
Scrolling without clicking.

**Screenshots**
Not really needed here.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - RuneLite version: 1.4.25
 - Launcher version: 1.6.1

**Comment by deathbeam** [comment]
This sounds like jvm bug and not something we can or should be fixing. What if you try with JRE 8? That is the officially supported version

**Comment by ZeroTroubles** [comment]
> This sounds like jvm bug and not something we can or should be fixing. What if you try with JRE 8? That is the officially supported version

Thanks for the reply, and adding the jvm label. I really wasn't sure where to put this... 
I now changed my default java configuration to `java-8-openjdk-amd64` but the issue still persists, exactly as before.

**Comment by deathbeam** [comment]
Hmm unfortunate. Did you tried with vanilla OSRS client?

**Comment by ZeroTroubles** [comment]
> Hmm unfortunate. Did you tried with vanilla OSRS client? (or OSBuddy/Konduit if it is still working)

I did, same problem persists. I guess it's not a RuneLite problem afterall. 
If anyone has any suggestions on how to fix this, I would like to know.
