### ISSUE TITLE
Kourend Library Reset button doesn't work as intended

### ISSUE THREAD

**Issue by mathieubrusselairs** [runelite/runelite#6448]
When the Kourend Library plugin is active, and the books shift, resetting the library through the settings menu doesn"t reset the locations.

**To Reproduce**
1. Start Kourend Library plugin
2. Find a book in Arceuus library
3. Open the Kourend Library settings and click "Reset"

**Expected behavior**
Locations are reset, all locations are possibilities, squares are white and near every bookcase.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.4.25
 - Launcher version: Unknown

**Comment by trimbe** [comment]
Are you clicking the reset button in the plugin settings? You want to use the one in the Kourend library sidepanel (represented by a book).

**Comment by deathbeam** [comment]
Yeah you need to click the reset button in kourend library panel
