### ISSUE TITLE
Add a cannon tile marker to Myth's Guild

### ISSUE THREAD

**Issue by ieneoj** [runelite/runelite#6449]
I did some testing and I believe that the optimal location for placing a cannon for blue dragons in the Myth's guild is at [this spot](https://media.discordapp.net/attachments/396147184237805569/511730103080976385/unknown.png), and I believe a cannon tile marker should be placed there.

**Comment by deathbeam** [comment]
Fixed in https://github.com/runelite/runelite/pull/6460
