### ISSUE TITLE
Chin Spot placement highlight tiles

### ISSUE THREAD

**Issue by alex-vincent** [runelite/runelite#645]
Would be great to have added to the hunter plugin. Common spots to place traps for chin hunting,

e.g. https://twitter.com/Zoydberg/status/745229185447268352

Very similar to cannon placement plugin

**Comment by Nightfirecat** [comment]
We have NPC tagging, and as of #2404, will have respawn locations of tagged NPCs. Chin placement spots are always around the respawn locations, so unless there's more to it than that, this should be resolved with #2404?

**Comment by dekvall** [comment]
As others have said, use respawn indicators and/or ground markers.
