### ISSUE TITLE
Use keyboard numbers to select withdraw option

### ISSUE THREAD

**Issue by Jabirr** [runelite/runelite#6451]
Is it possible that you can press a number on your keyboard and fast select a withdraw option 
![image](https://user-images.githubusercontent.com/31471200/48411231-38678900-e741-11e8-9150-2c6bd247618e.png)

so if i press 2 on my keyboard it will select the second option of withdrawing a item.

**Comment by forsco** [comment]
No and it's somewhat similar to menu entry swapping which is on the rejected list.

**Comment by Jabirr** [comment]
> No and it's somewhat similar to menu entry swapping which is on the rejected list.

Ahh okay, Thx anyways for the fast response.

**Comment by deathbeam** [comment]
As I replied in discord, this is very close to faking user input
