### ISSUE TITLE
Runelite Hiscore issues

### ISSUE THREAD

**Issue by FlipperSlipper** [runelite/runelite#6454]
Sometimes i lookup people hiscore some of their skill doesen't show up it just says --- and sometimes i search someone next to me or logoff or ironman it says name or account doesen't exist can u update the client please or find a fix for that it doesen't happen always but the 1+ skill doesen't show up always happen it's more like almost every lookup please find a fix for that and thanks!

**Comment by Hydrox6** [comment]
If the user isn't on the highscores, there's not much we can do to get information on their stats. Also, pretty sure this is a Duplicate issue
