### ISSUE TITLE
XP tracker issue

### ISSUE THREAD

**Issue by Bad-Brother** [runelite/runelite#6463]
**Describe the bug**
-When I perform High alchemy on an item, attack and defense xp is registered on the XP tracker with 0 xp gained.

**To Reproduce**
1. Go to 'high alchemy'
2. Click on 'item'
3. result

**Expected behavior**
attack and defense xp not registered in the xp tracker

**Screenshots**

https://imgur.com/a/DV1UAmR

**Environment (please complete the following information):**
 - OS: windows 10 pro
 - RuneLite version: [1.4.25]
 - Launcher version: [1.6.0]

**Comment by forsco** [comment]
This is already known and fixed in the next release.
