### ISSUE TITLE
Add pay-dirt to Skill Calculator

### ISSUE THREAD

**Issue by erikmukk** [runelite/runelite#6464]
**Is your feature request related to a problem? Please describe.**
It can be seen as a problem, because at the moment pay-dirt is not in Skill Calculator.

**Describe the solution you'd like**
I would like to see pay-dirt added to Skill Calculator. Currently it is not displayed there among other ores and mineable things.

**Describe alternatives you've considered**
There is no other alternative than adding it to Skill Calculator

**Additional context**
Nothing

**Comment by Alexsuperfly** [comment]
pay dirt is variable the amount of exp you get so its non trivial adding it and would still be off by a margin based on your rng

**Comment by erikmukk** [comment]
According to OSRS wiki "Mining pay-dirt grants 60 Mining experience and requires a minimum Mining level of 30." Do you want to say that I can get more than 60 exp per pay-dirt mined (without prospector armour)?

**Comment by Hydrox6** [comment]
You get more than 60 xp from Pay Dirt because you wash it into actual ores, which gives more xp

**Comment by erikmukk** [comment]
Oh okay. Now I see how that could mess things up. Thanks for explaining!

**Comment by deathbeam** [comment]
Yeah, this is not very helpful because you get a lot of side xp by cleaning the dirt
