### ISSUE TITLE
Take screenshots of virtual level-ups

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#6473]
**Is your feature request related to a problem? Please describe.**
When achieving a virtual level (100+), no screenshot is taken as there is no level-up widget presented.

**Describe the solution you'd like**
When getting an XP drop that achieves a virtual level, a screenshot should be taken.

**Comment by deathbeam** [comment]
Screenshot of exactly what? You get no message, no widget, no particles, so the screenshot will be basically screenshot of you doing some skilling/combat with no context

**Comment by Abextm** [comment]
I don't see how the widget is especially interesting. What you are doing is the purpose of the screenshot, otherwise we would just write it to a text file.

**Comment by deathbeam** [comment]
Well yes, but you are taking screenshot of nothing in this case. E.g there is no indicator that you achieved said level on the screenshot except file name.

**Comment by Abextm** [comment]
Your taking a screenshot of what you are doing, the indicator not important.

**Comment by Nightfirecat** [comment]
Yeah, I guess I kind of agree with db. Given that there's not really an indicator, it would just be some random screenshot. Didn't really think too much about this request haha
