### ISSUE TITLE
Sulliuscep helper

### ISSUE THREAD

**Issue by robinwithes** [runelite/runelite#6476]
**Is your feature request related to a problem? Please describe.**
Walking around the Sulliuscep area i sometimes miss tar monsters that roam around which i could have avoided. The npc indicator can't highlight them. It would also be nice for people starting out there to see the rotation of Sulliuscep mushrooms on their map or something.

**Describe the solution you'd like**
A plugin that highlights tar bubbles as well as highlighting the next location and current location of the Sulliuscep mushroom

**Comment by deathbeam** [comment]
I am pretty sure NPC indicator can highlight them as long as they have name, otherwise you can just right-click tag them

**Comment by DanMossa** [comment]
@deathbeam I'm unable to right click tag them
