### ISSUE TITLE
GPU renderer sometimes sees too far

### ISSUE THREAD

**Issue by Adam-** [runelite/runelite#6478]
Eg, at the agility pyramid you can see the abyssal sire.

**Comment by Adam-** [comment]
test

**Comment by Adam-** [comment]
test

**Comment by ShaunDreclin** [comment]
Would this be dealt with by lowering the render distance cap, or with some sort of system that won't render across borders we define? I'd much prefer the latter

**Comment by Adam-** [comment]
added in bc0d6a9c0897848b8ddb26a54e354b15c5638223
