### ISSUE TITLE
Add the option to have different Draw Distance based on whether a laptop is plugged in or not

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#6484]
I've just tried out the GPU plugin, which looks absolutely phenomenal. Thanks for the work on this!

On a laptop, it is a problem that on battery, GPUs tend to be throttled due to save battery or there not being enough power output from the battery to support a GPU at full power. Therefore, it is useful to have different Draw Distances based on whether your laptop is plugged in to an outlet or not. This is specific to the GPU plugin, since CPU usually doesn't really get limited by the battery. My suggested solution would be to detect whether the user is on a laptop, and have 2 different settings for draw distances based on whether it is plugged in or not. If the user also uses a desktop, it would use the plugged in option, since desktops don't suffer from this problem.

A workaround would be to have 2 Google accounts or implement profiles. Since this setting is particular to the GPU, I think it's fine to put it in the plugin configuration.

To put it into perspective: On a laptop with an i5-7300HQ CPU and a GTX 1060 my experience on battery with 30 Draw Distance is buttery smooth around Shilo Village bank, solid 50 fps, When I up it to 50, I get lagspikes when loading new areas, going down to around 30 fps. Upping it to 100 gives many lagspikes below 15 fps. I'll have to test it in an hour when it's plugged in how the performance is, but since Woox ran smoothly on a 1070, I think my experience will be similar. Here is a screenshot of my GPU usage with 100 Draw Distance on battery:
![image](https://user-images.githubusercontent.com/9074448/48569739-d48cbe00-e902-11e8-9ef3-84704df5eb91.png)

**Comment by raiyni** [comment]
max draw distance is 90 by the way.

**Comment by deathbeam** [comment]
I think this is very weird request

**Comment by Gamer1120** [comment]
Although I agree that this might be a weird request, normally NVIDIA Geforce Experience does this for you (note the "Aangesloten", which is Dutch for connected, and "Op batterij" which is Dutch for on battery):
![image](https://user-images.githubusercontent.com/9074448/48649090-c79ac800-e9f1-11e8-81a0-f4e5cb67dcc9.png)

**Comment by deathbeam** [comment]
You can just adjust the draw distance if you are on battery. E.g, use plugin configuration
