### ISSUE TITLE
Stretched mode plugin does not work with gpu plugin enabled

### ISSUE THREAD

**Issue by robinwithes** [runelite/runelite#6487]
**Describe the bug**
When having both the gpu plugin and stretched mode plugin enabled in either fixed or stretched mode it will glitch out and malform your game window.

**To Reproduce**
1. Enable both the gpu plugin and stretched mode plugin
2. See what happens

**Expected behavior**
I would expect them to work at the same time

**Screenshots**
https://gyazo.com/b6f309eaafda7a7bb06eee7ca8ee6971

**Environment (please complete the following information):**
 - OS: [Windows]

**Comment by james-munson** [comment]
can confirm does not work on 4k screens

**Comment by ProcrastinatorSal** [comment]
Can confirm doesn't work.
Following image is captured on a 4k monitor with GPU and Stretched mode plugins ON: 
![image](https://user-images.githubusercontent.com/5962674/48588774-76fa7080-e906-11e8-9d5b-837bef72a44b.png)

**Comment by MammothJerk** [comment]
I have the same problem, running on a 4k screen aswell.

**Comment by Kamielvf** [comment]
Yes, see https://github.com/runelite/runelite/wiki/GPU-FAQ and the blogpost, both stated this plugin is currently NOT working with the gpu plugin.
