### ISSUE TITLE
Full screen alpha widgets causing FPS drop

### ISSUE THREAD

**Issue by dey0** [runelite/runelite#6488]
**Description**
The full screen widgets that are alpha overlays (ie darkness or lightness at TOB/GWD) take a lot of CPU to render, causing FPS to drop even in GPU mode. 

**To reproduce**
Using the GPU plugin at any darkened area like TOB or GWD will result in an abnormal FPS drop.

**Expected behavior**
Instead of the CPU taking the performance hit of these overlays, remove the widget and re-darken the region via GPU. 

**Media**
These clips show the effects of the fullscreen darkening overlay reducing FPS at the Theatre of Blood.
https://streamable.com/rwxpl
In this first clip, simply entering a darkened area reduces the FPS from 50 to 38.
https://streamable.com/1ovbd
In this second clip, hiding the offending widget brings the FPS back up to 50.
![image](https://user-images.githubusercontent.com/13173140/48573202-20bf0a80-e8d1-11e8-8c94-5e0f9be68966.png)
The first column is CPU usage, and the second column is GPU usage. See that, since I have a quad-core processor, Runelite is consuming one core, and the GPU is not maxing out.

**Environment (please complete the following information):**
 - OS: Windows 7 x64
 - RuneLite version: 1.4.27
 - Custom launcher running latest shaded snapshot; 32-bit Java 1.8.

**Comment by Adam-** [comment]
fixed in 246b0f8a863d3e1973628c2ef58f967a32ec5c87
