### ISSUE TITLE
GPU Plugin: Smoke dungeon overlay causes issues with some Runelite overlays

### ISSUE THREAD

**Issue by trimbe** [runelite/runelite#6489]
![](https://i.imgur.com/3R9LKfu.png)

This only occurs in the Smoke Dungeon with the GPU Plugin enabled, and only when the infoboxes are in a snap area in the bottom of the screen. 

Seems to be caused by widget 313.0, which is a gradient overlay used to mimic smoke along the bottom of the screen. 

![](https://i.imgur.com/4lUORcL.png)

Bounds of 313.0 shown.

**Comment by sst37** [comment]
Also happens when thrown by Grotesque Guardians. See: https://im.ezgif.com/tmp/ezgif-1-53c96a2a6fd6.gif

**Comment by Sneakzz** [comment]
I also experienced this in the smoke dungeon with runelite overlays. Picture included.

![image](https://user-images.githubusercontent.com/32787307/48664156-dab5a280-ea9a-11e8-85c4-bd5e4d46b633.png)

**Comment by Adam-** [comment]
Fixed in #6780
