### ISSUE TITLE
Artifacting with older GPU hardware (AMD)

### ISSUE THREAD

**Issue by cmg5461** [runelite/runelite#6491]
i7-7700k
Radeon 6870 w/ 1GB GDDR5
AMD 15.7.1 drivers

Click here to play freezes with GPU enabled

Turned GPU off, can log in, turn it back on and experienced lots of artifacting.
![image](https://user-images.githubusercontent.com/9099791/48580831-3858bc00-e8ee-11e8-8ffc-6d6b04aff8de.png)

GPU passes benchmarks just fine.
![image](https://user-images.githubusercontent.com/9099791/48581125-ee240a80-e8ee-11e8-8126-0b1ff882d25e.png)
![image](https://user-images.githubusercontent.com/9099791/48581929-2cbac480-e8f1-11e8-9ce8-7aecbbc94b13.png)

On close of client, this thread stays running
![image](https://user-images.githubusercontent.com/9099791/48580801-24ad5580-e8ee-11e8-93f6-28e4fbed28f5.png)

GPU data while artifacting
![image](https://user-images.githubusercontent.com/9099791/48582137-ab176680-e8f1-11e8-9e74-c9b853e7849c.png)

Draw distance reduced to 10:
![java_2018-11-15_16-17-35](https://user-images.githubusercontent.com/9099791/48582293-1bbe8300-e8f2-11e8-825c-9f74188ff74b.png)
![gpu-z_2018-11-15_16-17-57](https://user-images.githubusercontent.com/9099791/48582295-1cefb000-e8f2-11e8-87cf-d728abb1813d.png)

**Comment by RuddeK** [comment]
@snapstermap
Could you post your system specs. 
My guess is that you both have under 2GB VRAM.

**Comment by jdoiron94** [comment]
@RuddeK OP says 1GB GDDR5, so that's likely the culprit.

**Comment by beansaboutbro** [comment]
2gb seems a bit much tbh, wonder why so much is needed?

**Comment by cmg5461** [comment]
Memory usage right now seems to not be optimized. I tested with a 7970 as well and it quickly eats up 3gb of vram.

**Comment by MESLewis** [comment]
Does this still happen on the latest release of RuneLite?

**Comment by Adam-** [comment]
reopen if this is still an issue
