### ISSUE TITLE
Add plugin to remove window size minimum

### ISSUE THREAD

**Issue by ragsmaroon** [runelite/runelite#6492]
Can we get the ability to make the client smaller? Right now there's a default minimum value on the size of the client/window, I'd like to be able to remove that limit, or at least make it a smaller minimum

**Comment by Nightfirecat** [comment]
Duplicate of #3937

**Comment by ragsmaroon** [comment]
> 
> 
> Duplicate of #3937

Oops sorry, this didn't come up with the title search thing, thank you.

**Comment by Nightfirecat** [comment]
To be fair, I only found it because I knew that it existed. It wasn't easy to find for me either.
