### ISSUE TITLE
Selecting a bank tag tab lights up chatbox for a couple frames

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#6494]
https://i.imgur.com/ZqkUi2p.gif

**Comment by deathbeam** [comment]
I guess this is because @WooxSolo's optimizations? E.g the chatbox is refreshed and it takes some time till the "fix" is applied

**Comment by MagicfTail** [comment]
Idk if this is only because my laptop sucks, but this also happens when switching between chat tabs https://i.imgur.com/56kVLmN.gifv

**Comment by WooxSolo** [comment]
This is because of the optimizations I made with the chatbox correct, just haven't gotten around to fixing it yet

**Comment by Adam-** [comment]
As Woox mentioned in discord, this is due to `WidgetPositioned` only firing every gametick due to it using the deferred eventbus.  I don't actually see why the deferred eventbus is on gametick and not client tick though. Regardless this seems like a bug with the positioned event. cc @abextm
