### ISSUE TITLE
NPCs Fighting other NPCs Missing Health Bars

### ISSUE THREAD

**Issue by chasertw123** [runelite/runelite#6495]
When an npc is engaged in combat with another npc the health bar is not displayed. Such as when npcs fight each other in god wars dungeon.

https://gyazo.com/ccf1b206508c77ef717ba942bb6a1bb1

**Comment by Kamielvf** [comment]
Perhaps you have the `hide NPCs 2D` option in the entity hider plugin turned on.

**Comment by chasertw123** [comment]
You're correct, my apologies.
