### ISSUE TITLE
Special Attack Orb is rendering above side-panel

### ISSUE THREAD

**Issue by XrioBtw** [runelite/runelite#650]
![specorb_above_sidepanel](https://user-images.githubusercontent.com/33559295/36508398-e552a7b8-175c-11e8-91e9-35e20a86ac6c.png)
Left image is how it is and right image is how it should be.

**Comment by devLotto** [comment]
Fixing this would require us to be able to draw after certain widgets, such that the inventory is drawn on top of our overlay. Maybe overlay layers can be extended to support passing in WidgetInfo, and then we would have a raw injector that injects the required code into the game.

**Comment by Adam-** [comment]
The special attack orb was added by Jagex and is no longer a plugin.
