### ISSUE TITLE
Add 'spade required' when doing the Trollweiss Mountain sled elite clue 

### ISSUE THREAD

**Issue by theinterestingstory** [runelite/runelite#6500]
**Is your feature request related to a problem? Please describe.**
"I'm always frustrated when" I get the clue scroll "Green is the colour of my death as the winter-guise, I swoop towards the ground." and the clue help box doesn't say "Spade required!"

**Describe the solution you'd like**
Let it say "Spade required!"

**Describe alternatives you've considered**
I'm not that much of a thinker.

**Additional context**
N/A

**Comment by WesleyM77** [comment]
Solved by commit [c3dcd08](https://github.com/runelite/runelite/commit/c3dcd08de7a1b38615f3f3297639e199e746ef10)
