### ISSUE TITLE
GPU plugin allows for 1-click ZMI

### ISSUE THREAD

**Issue by towelcat** [runelite/runelite#6510]
https://i.imgur.com/Gpbt5d7.png

Sorry to ruin everyone else's fun. Looks like you guys missed a literal _edge_ case.

To reproduce, stretch the window as far as you can horizontally, and as least you can vertically. You're able to click on interactables on the left/right sides of the screen. (This works on normal fullscreen ratios as well, but it's most abusable with a squashed window.)

**Comment by trimbe** [comment]
Are you able to actually interact though? I can replicate this but the click has no effect.

Also - I believe object interaction is limited by Jagex, not us.

**Comment by towelcat** [comment]
I tested and was able to click once and let it take me directly to the altar, crafting the runes in the process.

**Comment by stefanlawr** [comment]
You can't click on the alter, but the land next to it. When OSB made their GPU renderer, Jagex patched out object interaction.

**Comment by Alexsuperfly** [comment]
i can reproduce this, as long as the width of the game is larger than about 2350 and spinning the camera until the altar is just barley peeking on screen

**Comment by towelcat** [comment]
https://streamable.com/j629g

Demonstration, proving that it still interacts after reaching the destination.

**Comment by Adam-** [comment]
The cause of this might be that only the bounding box check has a distance check, and not the triangle checks
