### ISSUE TITLE
Overlays turn black with gpu plugin

### ISSUE THREAD

**Issue by Justin222111** [runelite/runelite#6511]
**Describe the bug**
The overlays in the runelite plugin turn black with the new gpu pluggin
**To Reproduce**
While fighting the gargoyle boss, if you get caught but dusks aura move and get thrown, your overlays turn all black for the duration of the special attack

https://gyazo.com/7a5f757d9bf504a222233232dcb73fcf

**Comment by trimbe** [comment]
Duplicate #6489
