### ISSUE TITLE
Enabling the GPU plugin freezes the game and doesn't load at all [SOLVED]

### ISSUE THREAD

**Issue by MichaelUnce** [runelite/runelite#6514]
**Describe the bug**
As soon as i enable the plugin it freezes, even before i login into rs.

**To Reproduce**
I have a  NVIDIA GTX 1080 and an i5-8600k CPU am running windows 10. My client also has hard ware acceleration off with the line --mode=OFF on startup due to artifacting with the side bar I tried it without this line of code and it still doesn't work.

**Expected behavior**
Freezes once enabled

**Screenshots**

**Environment (please complete the following information):**
windows 10
 - RuneLite version: [1.5.0]
 - Launcher version: [1.6.0]

**Comment by AntonioMS005** [comment]
Can confirm, same issue here running the lastest version of RuneLite on a GeForce 940M and i5 6200U with Windows 10. Fresh install of RuneLite, no settings changed from default and the problem persists.

**Comment by MESLewis** [comment]
Make sure your graphics drivers are up to date. You can find more information for possible fixed and requirements at https://github.com/runelite/runelite/wiki/GPU-FAQ

**Comment by AntonioMS005** [comment]
Thank you, compatibility options were the problem, after turning those off it runs perfectly (Graphical issues as a separate bug aside).10-20fps increase on integrated graphics, pretty nice

**Comment by MichaelUnce** [comment]
I found what the problem was, i reinstalled runelite using the "all platforms" version and it worked fine, i use a bat file to remove acceleration since it is a .jar file and everything is working as it should
