### ISSUE TITLE
GPU plugin causes certain tree leafs to show through objects and terrain

### ISSUE THREAD

**Issue by NewGuyGames** [runelite/runelite#6515]
With the GPU plugin the tree leafs on ape atoll and in feldip hills show through everything. I'm not sure where all these trees are but I'm sure it happens there as well.

https://imgur.com/a/PCIMJo4
Windows 10

**Comment by Nightfirecat** [comment]
This likely isn't strictly a GPU bug, but is rather a weird coincidence caused by extended render distance. That is, if CPU rendered the same distance, it would have the same problem.

**Comment by Adam-** [comment]
This is because the top half of the trees are roofs and it renders the roofs last. Mostly can't fix this.
