### ISSUE TITLE
Tiles are not connected on integrated intel GPUs

### ISSUE THREAD

**Issue by middragoon** [runelite/runelite#6519]
Floor has black lining around the squares when GPU is turned on.

![image](https://user-images.githubusercontent.com/45108495/48645198-f47bba80-e9b2-11e8-80cc-c714da8b2d2c.png)

**Comment by fussyeater** [comment]
Yup, same here!

**Comment by MagicfTail** [comment]
Have you tried this? https://github.com/runelite/runelite/wiki/GPU-FAQ

**Comment by middragoon** [comment]
Nope tried that didn't work either.

**Comment by LarsWalraevens** [comment]
> Floor has black lining around the squares when GPU is turned on.
> 
> ![image](https://user-images.githubusercontent.com/45108495/48645198-f47bba80-e9b2-11e8-80cc-c714da8b2d2c.png)



> Yup, same here!

Try the changing what I said in prev post above ^^

**Comment by Veradictus** [comment]
This seems like a rounding error when drawing the tiles. Mind providing some more information about your system? CPU, OS, GPU?

**Comment by Coldwire** [comment]
I can provide logs or whatever if you need them, just tell me where to look.

OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	Microsoft Corporation
System Model	Surface Pro 4
System Type	x64-based PC
Processor	Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz, 2496 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Microsoft Corporation 108.2318.769, 8/14/2018

**Comment by MESLewis** [comment]
What version of the intel graphics driver do you have installed?

**Comment by Veradictus** [comment]
@Coldwire No external GPU? Are you using an integrated GPU?

**Comment by MESLewis** [comment]
This is a known issue with intel integrated graphics running driver versions above 20.19.XX which is fairly old. I'm looking into it, trying to find release notes from that time to see what may have changed.

**Comment by Coldwire** [comment]
Adapter Description	Intel(R) HD Graphics 520
Driver Version	24.20.100.6136

**Comment by Coldwire** [comment]
No eGPU.

**Comment by MESLewis** [comment]
**AT YOUR OWN RISK** If you are feeling confident you can try downgrading your display driver to 20.19.XX. Intel doesn't have the driver packages available on their site but Windows update has them. You can search here https://www.catalog.update.microsoft.com/home.aspx

Here is a guide on installing from the .cab that microsoft will give you https://www.windowscentral.com/how-properly-update-device-drivers-windows-10
Follow the directions under the "Installing drivers manually" header.

Make sure you select a compatible driver! I am not responsible for your actions if you mess up your computer.

**Comment by Coldwire** [comment]
Will this help you debug? If it's just so I can enjoy the plugin, I'd rather just wait for a fix (hopefully).

**Comment by MESLewis** [comment]
It won't help with debugging, we are working on a fix but it is difficult to find information about what exactly changed to make it not work.

**Comment by Coldwire** [comment]
Then good luck, and let me know if I can provide any more information.

**Comment by LarsWalraevens** [comment]
> Then good luck, and let me know if I can provide any more information.

Whatever I did fixed it, did u try doing whatever I posted?

**Comment by MESLewis** [comment]
@LarsWalraevens your fix only works if you have an external GPU
