### ISSUE TITLE
My GPU usage shoots up from 15% to 100% when the plugin is enabled. 

### ISSUE THREAD

**Issue by Dephire** [runelite/runelite#6521]
Disabled - https://i.imgur.com/Hmjhyy4.png

Enabled - https://i.imgur.com/rPIfbdK.png

My graphics processor is an AMD A8 with AMD radeon R5 graphics. There should be no issue, but yet the game becomes incredibly laggy. Yes, the drivers are fully updated.

**Comment by raiyni** [comment]
That's the kind of the point of the plugin. To use your GPU. 

Which A8 do you have?

**Comment by Dephire** [comment]
> That's the kind of the point of the plugin. To use your GPU.
> 
> Which A8 do you have?

The processor in device manager just says "AMD A8-6410 APU with AMD Radeon R5 graphics" It's a laptop, as my gaming PC has a dead PSU. :(

I understand the point is to use the GPU but my entire computer seems to be chugging with the plugin enabled as well as a drop in FPS in game. Input lag even when typing this comment. Sure, 100% GPU might be normal elsewhere but this is runescape, right?

**Comment by Dephire** [comment]
> That chip doesn't really meet the processing requirements of the GPU plugin, sorry to inform you.
> 
> As you may know, APU chips aren't the most graphically powerful especially when compared to their Intel counterparts.

Ah, I actually didn't know that. Really wasn't expecting it to not meet the requirements because I used to play games like Smite on it pretty decently. If you say it's not enough then at least I know it's not some non-hardware problem, which is a good thing. Thanks.

**Comment by deathbeam** [comment]
Looks like this is expected behaviour
