### ISSUE TITLE
As of update 1.5.0, inventory viewer doesn't work

### ISSUE THREAD

**Issue by Tomcoid** [runelite/runelite#6525]
As of updating to 1.5.0, the inventory viewer plugin does not function.
Runelite 1.5.0
Windows 10

**Comment by Monsterxsync** [comment]
works perfect for me. when does it not work?

**Comment by Tomcoid** [comment]
It does not work when it is turned on or off, the inventory viewer window just doesn't appear. I've tried with gpu both on and off

**Comment by Tomcoid** [comment]
Never mind. I am monkey. It just doesn't appear when nothing is in your inventory.
