### ISSUE TITLE
Low FPS using GPU on Fossil Island

### ISSUE THREAD

**Issue by tgeene** [runelite/runelite#6528]
Went to do a bird house run. Went to Verdant Valley with no problem, but the moment I went to the Mushroom Forest my fps dropped from 50 to 6. I have been using GPU all day with no issue. When things started happening I switched servers and check my internet speed, but everything was good. It wasn't until I turned GPU off that I was able to bring my FPS back up.

I can give more detail if needed, but this one was pretty self explanatory.

**Comment by doorknob60** [comment]
For the record, on my machine, I noticed no slowdown when doing a birdhouse run (50 FPS at 1440p), but the one place I have found where the framerate tanks is God Wars Dungeon. It dropped to probably 10-15 FPS there for me (in the 30s with GPU plugin off). I have a GTX 1070, i5-6600k and am using Arch Linux.

**Comment by raiyni** [comment]
FPS will tank where there is a full screen overlay

**Comment by tgeene** [comment]
Since doorknob60 said he wasn't having issues I wanted to give my specs for reference.

- CPU. Intel Core i7-7700HQ 17.
- GPU. NVIDIA GeForce GTX 1050 (4GB GDDR5) 38.
- Display. 15.6”, Full HD (1920 x 1080), 120 Hz, IPS.
- HDD/SSD. 256GB M.2 PCIe NVMe SSD + 1TB HDD, 7200 rpm.
- RAM. 16GB DDR4, 2400 MHz.
- Windows 10
- Internet: ~300 mb/s

**Comment by tgeene** [comment]
I found out what my problem was. I had to force my NVIDIA Control Panel to recognize RuneLite and run it with NVIDIA instead of integrated graphics. First time I have ran into something like this.

**Comment by Tylemagne** [comment]
This seems to be due to the foliage:

![fps1normal](https://user-images.githubusercontent.com/3228492/48983545-b7e84700-f0b5-11e8-88e7-ee8db568ba88.png)

![fps1loss](https://user-images.githubusercontent.com/3228492/48983555-bcacfb00-f0b5-11e8-8fb5-32f67d2018f8.png)

**Comment by Andrew5569** [comment]
Could we remove the foliage in low detail mode?

**Comment by ileathan** [comment]
Runelite drops to 10 fps only when using Invalid Movement plugin.

Also adding the option --mode=OFF in the runelite shortcut target helped me keep it stable.

But the only real problem for me was that plugin, however I keep it running and use --mode=OFF and I get 30fps. Im using a 3080.
