### ISSUE TITLE
Adding a Feature to remove "Deposit Items worn"

### ISSUE THREAD

**Issue by xdrahmahx** [runelite/runelite#6532]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

(Always mis-click and end up Depositing all my gear instead of "deposit Inventory")

**Describe the solution you'd like**

(Just an Enable/Disable Feature to turn off "Deposit worn Items")

**Comment by wallnutkraken** [comment]
It's already available in the base game. Go to the little wrench thing in a bank.

But this will also change the spacing between the deposit/search buttons
