### ISSUE TITLE
Flashing When using GPU Plug-in (Intel iGPU)

### ISSUE THREAD

**Issue by SallustRS** [runelite/runelite#6536]
different parts of my screen are continually flashing bright white when GPU is turned on.

**Comment by cernodile** [comment]
Would be nice if you could provide information about your system and GPU.

**Comment by deathbeam** [comment]
This issue was fixed for me with https://github.com/runelite/runelite/commit/3286594d6b583aa261483a73ddf30823c102e923, so I guess we can close it, unless someone else wants to try it as well?

**Comment by deathbeam** [comment]
As I cant reproduce this anymore, closing. Reopen if issue still occurs (on master branch, its not in release yet)

**Comment by Delphik** [comment]
Im having the same issue using a GTX 1080 with the 415 drivers.

**Comment by deathbeam** [comment]
So the issue is still present even on latest release @Delphik ?

**Comment by jorenham** [comment]
I have the same on Ubuntu with GeForce GTX 1050 Ti on version 1.5.2.1.
Same behavior when opening with OpenJDK 8, Oracle Java 8, 9 10 and 11.

**Comment by Borancer** [comment]
Still facing same problem. im using linux mint 19 64 bit. Might be too because im using 4k. Especially does that when i do something else and it gets worse when using 3 accs same time.
