### ISSUE TITLE
Blurry Text Using CPU Plugin

### ISSUE THREAD

**Issue by GlavasRho** [runelite/runelite#6538]
**Describe the bug**
When activated, the GPU plugin causes my in-game text (chatbox, dialogue, etc.) to become blurred and less opaque. 

**To Reproduce**
1. Simply active the GPU plugin

**Expected behavior**
The text would retain its sharpness and clarity.

**Screenshots**
Before:
![before](https://user-images.githubusercontent.com/45124721/48662188-6a803000-ea4c-11e8-91a9-4b0432e0305f.JPG)

After:
![after](https://user-images.githubusercontent.com/45124721/48662189-6fdd7a80-ea4c-11e8-96e0-7104cd916452.JPG)

**Environment (please complete the following information):**
 - OS: Windows 10 64-bit
 - GPU: GeForce GTX 1060
 - RuneLite version: 1.5.0
 - Launcher version: 1.6.0

**Comment by Rheon-D** [comment]
If Anti aliasing is enabled in Nvidia control panel it will cause this sort of behaviour.
You can try disabling anti aliasing globally or customise Runelites profile within the control panel.
After you have made the changes, restart the client.

**Comment by MagicfTail** [comment]
You should add the solution to the wiki

**Comment by GlavasRho** [comment]
> If Anti aliasing is enabled in Nvidia control panel it will cause this sort of behaviour.
> You can try disabling anti aliasing globally or customise Runelites profile within the control panel.
> After you have made the changes, restart the client.

This did the trick! Thanks a million!
