### ISSUE TITLE
Volcanic Abyssal Whip missing textures with GPU plugin

### ISSUE THREAD

**Issue by 2Milky** [runelite/runelite#6540]
**Describe the bug**
Equipping the Abyssal Whip with the Volcanic Mix applied to it causes the volcanic texture/animation to disappear from the whip. I'd assume this is also the case with the Frozen Mix as well (though I don't have one to confirm my assumption).

**To Reproduce**
1. Equip an Abyssal Whip that has the Volcanic Mix added to it
2. In the RuneLite plugin list, turn the GPU plugin on and off to notice the difference

**Expected behavior**
Expected the Volcanic Abyssal Whip to have its regular textures

**Screenshots**
https://imgur.com/a/jPDcrVu

**Environment (please complete the following information):**
 - OS: Windows 10 Pro Version 10.0.17134
 - RuneLite version: 1.5.0
 - Launcher version: Unknown
 - CPU: Intel i7 4790K
 - GPU: GTX 1080

**Comment by raiyni** [comment]
it does that on the mobile renderer too
