### ISSUE TITLE
Camera control with mouse

### ISSUE THREAD

**Issue by Cyithral** [runelite/runelite#6542]
In OSbuddy it allows me to change the angle of my camera with my side buttons of my Logitech G900. I do this by switching the buttons to the scroll wheel. I would love for this to be a feature! Thank you.

**Comment by Nightfirecat** [comment]
Moving the camera with your middle mouse button is a native feature of OSRS, not a 3rd-party client feature. This should work without any code added to runelite

**Comment by EvanWalden** [comment]
There's an in game setting. 

Options > Controls > Middle mouse button controls the camera

**Comment by deathbeam** [comment]
Looks like this is already a thing, closing
