### ISSUE TITLE
Attack Styles - Defensive casting option is not hidden again after selecting autocast

### ISSUE THREAD

**Issue by DevBoas** [runelite/runelite#6557]
When you have defence as a warned style in attack styles and you select a spell to autocast, the defensive casting option pops up again. Can this be fixed so it removes it after you return to your spellbook?

**Comment by deathbeam** [comment]
Nope, we cant do this that would be faking actions

**Comment by Nightfirecat** [comment]
@deathbeam If I'm understanding the issue report, they're saying that after clicking on autocasting and selecting a spell, once they come back to the combat interface, the defensive casting widget re-appears.

**Comment by deathbeam** [comment]
Oh looks like I misunderstood the issue, reopening

**Comment by DevBoas** [comment]
> @deathbeam If I'm understanding the issue report, they're saying that after clicking on autocasting and selecting a spell, once they come back to the combat interface, the defensive casting widget re-appears.

That is exactly what I mean

**Comment by Nightfirecat** [comment]
I couldn't reproduce this issue with a Staff of the Dead. What staff/spell/settings were you using that you were able to get this to happen with?

![no-repro](https://user-images.githubusercontent.com/2199511/48741807-70486200-ec54-11e8-9746-81ba7b5273f8.gif)

**Comment by Nightfirecat** [comment]
I'm able to reproduce this only in the side panels resizable view, looking into a fix now.
