### ISSUE TITLE
Animation Smoothing - "Viggora's chainmace"

### ISSUE THREAD

**Issue by Mrs-Sithy** [runelite/runelite#6566]
**Describe the bug**
In the default animations, there's 1 "frame" where the mace moves horizontally, with the RuneLite Animation Smoothing on, that 1 "frame" instead spins around in a big way.

**To Reproduce**
Equip Viggora's chainmace (both charged and uncharged) and turn on Animation Smoothing.

**Expected behavior**
For the mace to not spin around like it's alive.

**Screenshots**
![viggora s-chainmace-3](https://user-images.githubusercontent.com/42724319/48676725-94565700-eb1f-11e8-868e-ada8513e5448.gif)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Unsure how to check, has been a bug since the wilderness weapons release.
 - Launcher version: Unsure how to check, has been a bug since the wilderness weapons release.

**Additional context**
Other people I've asked have told me they see it as well, so it is not my RuneLite Client specifically.

**Comment by Nightfirecat** [comment]
This animation is no longer smoothed with the plugin as of client patch 1115467381.80.
