### ISSUE TITLE
Turning off the GPU plugin freezes the game, but input still passes through

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#6568]
Turning off the GPU plugin freezes the game, but input still goes through. The game unfreezes when the plugin is turned back on.

https://i.imgur.com/B8MAqmv.gif

<details>
<summary>Specs</summary>
OS: Windows 10 <br>
CPU: Intel i5-4210U <br>
GPU: NVIDIA 820M <br>
RAM: 8GB
</details>

**Comment by deathbeam** [comment]
Anything in log with --debug flag?

**Comment by MagicfTail** [comment]
Nothing in the log, it's on master, and oops, yes it is.
