### ISSUE TITLE
GPU Renderer - Not wanting to display further than a certain draw distance.

### ISSUE THREAD

**Issue by Loukey95** [runelite/runelite#6573]
With the GPU renderer my draw distance is capped at 65 for some reason and to get it to go to 65 I had to slowly increase it and then close thr programme, log back in, and increase it by a few integers at a time.

For example I was logged in, the draw distance was at 60, I increase it 1 step at a time, it gets to 65 no problem but then will not increase after that. I have had to do that multiple times seemingly at random to get the draw distance to this point.

So I am unsure if this is a bug or whatever or just something weird with my machine or something, or if anyone else has had this issue?

For reference my system is a i5 4440 16gb ddr3 ram dual channel at 1666mhz with a gtx 970 4gb (3.5gb ;P) on a z97 board. (yes i know I should have got a 'k' variant CPU to overclock it with)

**Comment by whitehooder** [comment]
It's capped at 90 and only draws what's loaded. Test some more by running around and looking back at where you came from to see whether you can render any further.

**Comment by Loukey95** [comment]
> It's capped at 90 and only draws what's loaded. Test some more by running around and looking back at where you came from to see whether you can render any further.

Having now tested this, It seems that has done the trick, thank you kind sir.
