### ISSUE TITLE
Custom Hotkeys

### ISSUE THREAD

**Issue by DaNewChamp** [runelite/runelite#6582]
**Describe the solution you'd like**
Is it possible to add the option to remap the F1-F12 keys into any key on the keyboard? Like B opens the backpack, etc.. 

**Describe alternatives you've considered**
Autohotkey remap buttons, B for backpack, C for character screen. Already use this and it would be amazing if runelite did this so i can hit Enter to chat and still type without using another AHK key to suspend the macro.

**Comment by dginovker** [comment]
Support

**Comment by dginovker** [comment]
It should definitely be doable since we supported remapping hotkeys before Jagex allowed it

**Comment by Adam-** [comment]
I don't think we ever remapped hotkeys ourselves.

**Comment by Nightfirecat** [comment]
Also I'm pretty sure this is a duplicate of another open issue.

**Comment by deathbeam** [comment]
Duplicate of #5070
