### ISSUE TITLE
Problem With GPU and Stretched Mode Compatability

### ISSUE THREAD

**Issue by thestdman** [runelite/runelite#6587]
**Describe the bug**
I am unable to run both the GPU and the Stretched Mode plugins at the same time, trying to use both results in the screen becoming improperly sized and virtually unplayable.

**To Reproduce**
1. Turn on Gpu (I've tried various numbers but most notedly 100 and 50)
2. Turn on Stretched Mode
3. See the error that is present with the screen becoming a similarly small screen as regular but with less clickability

**Expected behavior**
When you perform the steps your screen will (in my experience) shrink to the bottom left of the client and act as if it is fullscreen and therefore make it impossible to click accurately.

**Screenshots**
https://gyazo.com/26c3a6d868d4a4b71cfa10c83745a8f7
https://gyazo.com/4f8a8336b3964e6a21775280cd198eca

**Environment (please complete the following information):**
 - Windows 10 home
 - RuneLite version: 1.5.0
 - Launcher version: 1.6.0

**Comment by deathbeam** [comment]
We already have issue for this
