### ISSUE TITLE
Ground items text hides the items underneath

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#659]
![2018-02-22-122716_259x137_scrot](https://user-images.githubusercontent.com/34518321/36553949-bbf18a96-17cb-11e8-855b-6b523bba9843.png)

This is especially bad when you're zoomed out, and/or high above the item.

**Comment by deathbeam** [comment]
We should definitely move it up. And, maybe optional feature to highlight the tile item is on? Maybe only for insane/highlighted items.
