### ISSUE TITLE
Hide "Deposit Inventory" + other function buttons

### ISSUE THREAD

**Issue by SalTor** [runelite/runelite#6598]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem. This is related to a preference. I try to play the game as close to how it was in 2007. I use the 2005 game frame, which helps with the immersion, and having the banking interface close to how it was back then would be that much better.

**Describe the solution you'd like**
First and foremost, I would like to hide the "Deposit Inventory" button, rather than merely disabling it (which is a separate feature request someone has made). If that is feasible or permitted, I would like to be able to hide the rest of the buttons in that row. Namely, from "Rearrange mode" at the left-most side, all the way to "Search/Deposit Inventory" at the far right.

**Describe alternatives you've considered**
The alternative solution to this proposal is merely disabling "Deposit Inventory", as done in Konduit.

**Additional context**
No additional context comes to mind.

**Comment by Nightfirecat** [comment]
Hiding deposit equipment and inventory buttons are a vanilla feature, found in the bank settings.

**Comment by SalTor** [comment]
Not quite. You're correct that hiding deposit equipment is a vanilla feature, but not hiding deposit inventory

**Comment by deathbeam** [comment]
I dont think we should be hiding vanilla functional interfaces just because you do not like them. We already have issue for making deposit inventory/equipment right click only
