### ISSUE TITLE
Custom timer - world hopping focus, mining/thieving/fixing struts.

### ISSUE THREAD

**Issue by M-a-x-y** [runelite/runelite#6600]
**Is your feature request related to a problem? Please describe.**

When mining rune ore, or thieving from chests/stalls that take minutes to re-spawn, I find it arduous to start various different timers and trackers to know which world will next respawn for me to mine.

**Describe the solution you'd like**

I would like a plugin that displays a list of worlds that I've gathered a thing (mine a rock, thieve a chest) as well as a 'countdown' until that resource is available again in that world. This could include Silver stalls and above, Arrow-Tip chests and above - not Rogues',  Addy/Rune rocks. 

**Describe alternatives you've considered**

Running timers and stopwatches. This quickly falls apart as it can take a varied amount of time to mine something. 
It could also be possible to create something that tracks the exp gained between each hop and then to automatically start a timer if a certain amount of exp were to be gained. This would expand the timer beyond the thieving and mining examples I've given above.

**Additional context**

This provides no unfair advantage and helps combat features that bots use (having timers and tracking worlds).

This is NOT like #3924 as this focuses on tracking between worlds and expands to mining.

**Comment by deathbeam** [comment]
Please open 1 issue per request, parts of this request are duplicates
