### ISSUE TITLE
Status bars light up when any prayer is on

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#6605]
The prayer side of the status bars currently lights up when you turn your quick prayers on. Would help if it lit up if you turned prayers on manually as well in case you forgot one on.

Side note: potentially adding this to the prayer orb as well?

**Comment by Malfuryent** [comment]
I guess this makes sense for the prayer bar, it's not like your can click the bars to active quick-prayer. I'll get on it when i get home.

**Comment by LlemonDuck** [comment]
I cannot find an exact commit for when this was changed, but the prayer bar now lights up as activated when manually toggling prayers.
