### ISSUE TITLE
Support SLI and/or CrossFire for GPU plugin

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#6612]
**Is your feature request related to a problem? Please describe.**
When running the GPU plugin, only one of my two graphics cards (running in SLI) are utilized, thus capping the full potential of their use, and generally causing greater use for one card without making use of the other whatsoever.

**Describe the solution you'd like**
For configurations running SLI (for nVidia) or Crossfire (for AMD), I'd like to be able to make use of both/all running graphics cards.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by deathbeam** [comment]
https://www.geeks3d.com/20101209/tips-how-to-enable-sli-and-crossfire-support-for-opengl-applications/ looks like we cant support this

**Comment by deathbeam** [comment]
And as I stated in my reply already, this cannot be implemented
