### ISSUE TITLE
Chat Commands !kc

### ISSUE THREAD

**Issue by TheSexyNerd** [runelite/runelite#6618]
The chat commands plugin, more specifically the `!kc` command does not work for me. I can not view my own nor anybody elses KC.
I've already checked my boss log to make sure Runelite could recognize it and made sure the plugin was enabled.
I'm using the syntax
```
!kc [boss name]
```
![Image of bug](https://prnt.sc/ll7g19/direct)

**Comment by gutsuv** [comment]
I can attest to this. Was not working for me last night.

**Comment by Nightfirecat** [comment]
Sounds like it could be the API being on the fritz

**Comment by deathbeam** [comment]
Is this still issue? !kc should work

**Comment by TheSexyNerd** [comment]
No longer an issue, it works now after the most recent client update!

**Comment by deathbeam** [comment]
Thanks for verification
