### ISSUE TITLE
GPU Distance advantage

### ISSUE THREAD

**Issue by forsco** [runelite/runelite#6628]
With the GPU Plugin enabled you can see certain objects further away which can provide an advantage when scouting other players within the wilderness.

- Cannons
- Chinchompa traps
- Projectiles

**To Reproduce**
Enable GPU Plugin and find a cannon, stand at a distance at which the cannon would normally not be rendered without GPU and toggle the plugin to see the difference.

**Expected behavior**
I would expect these models and graphics to not be rendered outside of their normal limitations.

**Comment by raiyni** [comment]
I checked vs OSB and it's the same distance that you can see them.

**Comment by deathbeam** [comment]
Looks like until OSB removes their, we will keep ours
