### ISSUE TITLE
Kill notice

### ISSUE THREAD

**Issue by Andrek25** [runelite/runelite#6629]
I would like the runelite to warn when the enemy you are killing is below a certain % of life, maybe configure with a notification, a sound or activating the window.

The problem arises when I'm killing Skeletal Wyvern while I worked on other things, either watching facebook or youtube.

**Comment by deathbeam** [comment]
We already have out of combat notification

**Comment by Andrek25** [comment]
That's right!, but what about a notification when the enemy is <= 20% of hp or something?
