### ISSUE TITLE
linux gpu plugin ui flickering

### ISSUE THREAD

**Issue by Jimbimanim** [runelite/runelite#6631]
**Describe the bug**
when gpu plugin is enabled the UI and overlays flicker

**To Reproduce**
enable gpu plugin on linux

**Expected behavior**
no flickering

**Screenshots**
video showing gpu plugin toggled on and off and back on again
https://giant.gfycat.com/BriefMarriedFlea.webm

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Mesa: 18.2.4
 - Nvidia driver: 410.73
 - Nvidia GTX 960
 - Java: 1.8.0_192
 - RuneLite version: 1.5.1
 - Launcher version: 1.5.1?

**Comment by theGeekPirate** [comment]
FWIW, I don't have any issues regardless of the GPU/UI settings I enable/disable, with the exact same setup (except I have a 1060). Also tried updating to the latest 410.78 release, which also worked.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
