### ISSUE TITLE
Hide left click option for zygomites/ancient fungi

### ISSUE THREAD

**Issue by EvanCosper** [runelite/runelite#6632]
**Is your feature request related to a problem? Please describe.**

Yes. It is very annoying when you accidentally left click on an ancient fungi while hunting Herbiboars

**Describe the solution you'd like**

Make an option to set ancient fungi to right click only.

**Describe alternatives you've considered**

Although it would be nice, I don't think its possible to remove the "Pick ancient fungi" option.

**Additional context**

When hunting Herbiboars, you have to click around the "Ancient Fungi" (which are buffed zygomites).

**Comment by deathbeam** [comment]
We already had issue for this, and it was closed as wontfix, so closing this as duplicate
