### ISSUE TITLE
[GPU] White squares shows on pillars, but not in CPU rendering

### ISSUE THREAD

**Issue by JorgenRe1** [runelite/runelite#6633]
Location is the temple where you kill the dog in the Priest in Peril quest. 
In that temple every wooden pillar on the wall has a white square on its bottom. Something that is not shown when not using GPU rendering.
Lighting seems to be very different too.

**To Reproduce**
1. Go to Priest in Peril temple undeground with the dog.
2. Turn on GPU rendering 
3. See white squares on the wooden pillars on the walls.

**Expected behavior**
CPU and GPU rendering should be equal.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.1
 - Launcher version: ??

**Comment by Adam-** [comment]
Fixed in #6634
