### ISSUE TITLE
Toggle hide chatbox in resizeable

### ISSUE THREAD

**Issue by MarniRS** [runelite/runelite#6638]
Make a shortcut/plug-in to toggle hide chatbox in resizeable mode. Bind it to an f-key or any symbol on the keyboard.

**Comment by deathbeam** [comment]
You can just hide it with ESC already?

**Comment by MarniRS** [comment]
Really? I dont think you can

**Comment by robinwithes** [comment]
Would like to expand on this idea by suggesting a feature to remember your choice to close your chat box when hopping worlds. Currently your chat is ALWAYS visible when logging into the game which can be annoying.

**Comment by mmccoy37** [comment]
+1 on this request

**Comment by LlemonDuck** [comment]
This can now be done with hub plugin [Toggle Chat](https://runelite.net/plugin-hub/show/toggle-chat)
