### ISSUE TITLE
GPU spikes RAM 

### ISSUE THREAD

**Issue by Cryiin** [runelite/runelite#6640]
When using the GPU plugin, RAM goes through the roof. It uses my GPU, but it also wrecks my RAM. Is this supposed to happen?

-OS Windows 10
-GPU Nvidia GEFORCE GTX 960M

One RuneLite without GPU plugin, one with.
![image](https://user-images.githubusercontent.com/45275014/48924416-4d1dec80-eeb8-11e8-965e-f7d67fe33d3f.png)

**Comment by Alexsuperfly** [comment]
if your gpu is pulling from shared ram yea

**Comment by Cryiin** [comment]
Think I should upgrade my ram to 16gb? Or can i tweak some settings to get better performance?

**Comment by deathbeam** [comment]
Looks like this is expected behaviour
