### ISSUE TITLE
Ctrl+Click to 'ping' items in chat.

### ISSUE THREAD

**Issue by GZusRS** [runelite/runelite#6642]
So sometimes while scouting for a COX raid, you'll find one and teammates will ask "what items do I need" being able to Ctrl+click them to instantly 'ping' them in chat would be much nicer than having to type them out also if anyone ever asks what an item that you're wearing is, you'd be able to 'ping' it for maximum laziness.

I feel like this might rely on being able to paste into the chat box which could potentially flag up as an autotyper but if there could be another method that I haven't thought of, this feature would be nice.

**Comment by Alexsuperfly** [comment]
this would require auto typing and so wont be done

**Comment by daviscook477** [comment]
does this go against the rules of 1 action 1 action

**Comment by GZusRS** [comment]
I thought so, but figured there could be another method of making it work that wouldn't break rules. Worth asking people with more experience than myself.

**Comment by MESLewis** [comment]
If this really wanted to be done within the rules you could do something with a ! command. Lets say control click brings up a small overlay that says !1234 for item id # 1234. Then you type that, and the client will change that into whatever information you want.

**Comment by deathbeam** [comment]
Auto-typing is no no, and we have issue for just sending pings
