### ISSUE TITLE
Bank tags icons not persistent between client restarts if name contains a slash /

### ISSUE THREAD

**Issue by 40Cakes** [runelite/runelite#6644]
**Describe the bug**
I have a tab named birdhouse/seaweed, every time I reload the client, the icon I set for the bank tag resets to a shovel.

**To Reproduce**
1. Make a bank tag and give it a name with a forward slash in it ///
2. Set an icon for the tag
3. Restart client
4. Icon should reset to a shovel

**Expected behavior**
Icon should be persistent between client restarts

**Screenshots**
![image](https://user-images.githubusercontent.com/16377135/48938968-e3105080-ef66-11e8-90e3-acf57726e87b.png)

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - RuneLite version: 1.5.1
 - Launcher version: 1.6.0

**Comment by raiyni** [comment]
I'm going to assume that this is an issue on the api side. The url that gets built is `Built URI: https://api.runelite.net/runelite-1.5.2-SNAPSHOT/config/banktags.icon_some%2Fthing` and it doesn't save it seems.

I can't be for sure until I get my local api working again.
