### ISSUE TITLE
Pasting long things into login

### ISSUE THREAD

**Issue by vikke1234** [runelite/runelite#6645]
*Describe the bug**
see picture below

**To Reproduce**
1. Go to login thing
2. paste a long string, like say url or something
3. See error

**Screenshots**
http://prntscr.com/llzuiy
**Environment (please complete the following information):**
 - OS: Ubuntu 18.10
 - RuneLite version: current

**Comment by deathbeam** [comment]
What is the issue exactly?

**Comment by oabdellatif** [comment]
There's a 20 character limit on passwords for RuneScape as a whole; you shouldn't be able to paste anything longer than that into the password field. It should automatically truncate it to 20 characters. Trying to log in would probably result in some undefined behavior as well.

**Comment by deathbeam** [comment]
It will just fail on wrong password. I dont see anything wrong in you pasting random stuff there as it is not causing any problems

**Comment by deathbeam** [comment]
It does that because its reading your clipboard and not because it is inserting it to password field I am pretty sure.

**Comment by oabdellatif** [comment]
My mistake, I worded that incorrectly; it pastes just fine, it's when you click log in that the game freezes.

**Comment by deathbeam** [comment]
Fixed in #6652
