### ISSUE TITLE
When tagging NPC with rightclick, add it to the list of tagged NPCs so it stays through client restart.

### ISSUE THREAD

**Issue by sst37** [runelite/runelite#6648]
When tagging NPCs with right click it is only tagged during the time you keep your client open. Only if you manually add the NPCs name to the NPC indicators list will it stay tagged forever.

**Describe the solution you'd like**
Make an option to tick in the settings "Add to list when using Right-click tag" or simply just do it as standard.

**Comment by deathbeam** [comment]
The tag and highlight options serve different purposes, tag highlights only 1 npc, and highlight by name highlights all. We cant store these 1 npc tags as they are based on index in local npcs array and that one can change

**Comment by icorne** [comment]
@deathbeam Any way to change the way 1/tagging works? I'd use it to tag specific mobs to see their spawn points, and these don't change I assume?

**Comment by Nightfirecat** [comment]
For technical reasons we can't preserve single NPC tags through client restarts. If you'd like an NPC's tag to persist, use "Tag-All" instead.

**Comment by icorne** [comment]
How come it can persist cross world hops then?

**Comment by Nightfirecat** [comment]
Because world hops aren't the same as closing the client and reopening it.
