### ISSUE TITLE
Screenshots do not work correctly when the GPU plugin and Strechted mode are enabled.

### ISSUE THREAD

**Issue by GaagumMagier** [runelite/runelite#6649]
**Describe the bug**
When Runelite makes a screenshot when GPU plugin and Stretched mode are enabled you will only see the bottom left side of the screen.

**To Reproduce**
1. Enable GPU Plugin and Stretched mode.
2. Make a screenshot with Runelite.
3. Look at the screenshot.
4. You only see the bottom left side of the screen.

**Expected behavior**
I expect to get a screenshot of the whole game screen.

**Screenshots**
![death 2018-11-23_14-02-16](https://user-images.githubusercontent.com/39624517/48947770-9743b400-ef32-11e8-9701-9e0b0d9e1437.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.1
 - Launcher version: 1.6.0

**Comment by MammothJerk** [comment]
i have a similar issue
![](https://i.imgur.com/yJxzgzk.png)
