### ISSUE TITLE
Ground Items - Untradeable Items - Ancient Shard

### ISSUE THREAD

**Issue by EVOuser94** [runelite/runelite#6651]
The Ancient shard isn't showing up in the Ground Items, I have the setting "Do not hide untradeable items" checked, and have made sure it isn't in hidden items. I can manually add it to highlighted items to make it show up, but still feel like this is a bug.

**Comment by Alexsuperfly** [comment]
screenshot your ground items setting page and post here, im pretty certain its something on your end

**Comment by EVOuser94** [comment]
Settings
[https://photos.app.goo.gl/QxNJF8MYvXVhqJzm7](url)
Item On Ground with Same settings
[https://photos.app.goo.gl/Q88mVwqCfxAbqqow5](url)
Item in Inventory
[https://photos.app.goo.gl/fuf6cmfHWPHN7xqN9](url)

**Comment by Alexsuperfly** [comment]
disable show only highlighted items

**Comment by EVOuser94** [comment]
I feel like they should work together, because without that option I see it yes, but I also see everything I don't wanna see too.....

**Comment by Alexsuperfly** [comment]
change the title to request that the not hide untradeables option supersede show only highlighted items

**Comment by deathbeam** [comment]
We already have issue for highlighting untradeables I believe, and "Do not hide untradeables" means exactly what the name says, the hidden filter is not applied to those
