### ISSUE TITLE
Freezeing at startup

### ISSUE THREAD

**Issue by Griffihr** [runelite/runelite#6653]
**Describe the bug**
Every time i start Runelite it runs normally for 5 second and then my whole computer freezes, after 30 seconds it unfreezes and then after 5 it freezes again and just continues in this pattern.

**To Reproduce**
1. Start Runelite (doesn't matter if it's in administrator)

**Expected behavior**
I expected the game to start normally and i would be able to play.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.1
 - Launcher version: 1.6.0

**Additional context**
I reinstalled the Runelite, tried the all platforms version. I reinstalled java. I checked my event viewer and there were no errors. i tried to run in both administrator and normally. i've also tried to mess around with the compatibility mode on runelite but nothing is working.

**Comment by deathbeam** [comment]
Did you tried other java-based applications? Or, vanilla client/OSB?

**Comment by gwyndal** [comment]
Have you tried turning off your plugins?
Runelite is currently freezing on startup for me if I have the GPU plugin enabled. Check to see if it's enabled, and if it is, disable it and exit out of the application and then try to launch it again.

**Comment by dekvall** [comment]
No additional information has been provided for more than a year so I am closing this. If the problem persists feel free to reopen the issue.
