### ISSUE TITLE
Allow XP Tracker to set level goal

### ISSUE THREAD

**Issue by samabenie1** [runelite/runelite#6656]
**Describe the solution you'd like**
OSBuddy allows me to set a custom targel "level goal". Then tells me the actions/kills required to get to that goal. RuneLite needs this as well.

**Describe alternatives you've considered**
There are no current alternatives, besides switching to OSBuddy

**Additional context**
https://imgur.com/a/yl2bTeM

**Comment by Alexsuperfly** [comment]
use in game goals, our plugin pulls from there
