### ISSUE TITLE
RuneLite Client Crashes during Cold War Quest

### ISSUE THREAD

**Issue by HeavensVibe** [runelite/runelite#6661]
**Describe the bug**
During Cold War Quest, after player is on iceberg and has created the hut. Speaking to larry to start observation cut scene causes client to crash and close.

**To Reproduce**
1. Go to Larry on the Iceberg
2. Click on Larry to Talk to Larry
3. Observe

**Expected behavior**
Cutscene plays out

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 8.1
 - RuneLite version: 1.5.1
 - Launcher version: 1.6.0

**Additional context**
N/A

**Comment by deathbeam** [comment]
Is this with GPU plugin? If yes, what GPU do you have

**Comment by HeavensVibe** [comment]
> Is this with GPU plugin? If yes, what GPU do you have

Yes, GPU Plugin issue. Disabling allowed progress.
AMD Radeon R7 200 Series

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the current RuneLite release.
