### ISSUE TITLE
Incorrect "Kills left" on Prayer when using Bonecrusher

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#6666]
![image](https://user-images.githubusercontent.com/9074448/48972207-18c83e80-f026-11e8-9910-7091a168148d.png)
Was slaying some Dagannoth in the Catacombs, and noticed the "kills left" was way off. I'm getting 2 xp per kill.

**Comment by deathbeam** [comment]
This should be solved already with the combat skill check that was added to master
