### ISSUE TITLE
Fedora 29 Glitch when starting

### ISSUE THREAD

**Issue by Acarea** [runelite/runelite#6668]
![image](https://user-images.githubusercontent.com/19951099/48972534-a0b14700-f02c-11e8-8f08-8d22da8e153f.png)

Using Fedora 29 and executed the .jar file. Ends up glitching like this. Is this a known issue? Is there a way to fix it?

**Comment by MagicfTail** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by Acarea** [comment]
> https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

That was it. Thank you. Very quick response too! :)
