### ISSUE TITLE
Add the ability for the XPTracker API to handle account types

### ISSUE THREAD

**Issue by EricTurf** [runelite/runelite#6681]
**Is your feature request related to a problem? Please describe.**
I was trying to implement [this feature](https://github.com/runelite/runelite.net/issues/51) for the runelite website and I came across the problem that the `XPTrackerController` only fetches a user's rank based on the __normal__ highscores. This makes the issue linked above not doable since the SQL records only contain ranks for the normal highscores.  

**Describe the solution you'd like**
By looking at the code the flow that I kind of came up with is:
   -  When creating a new user, check the HC,ult,iron highscores(breaking out and continuing if one works). If none of these work, fallback to the  normal highscores. We would also attach a `type` on the User record to help in future updating.
 
   - When updating, we already fetch the user record so we could simply get the user's `type` and call the appropriate jagex endpoint to get the ranks and update the record

  - I also think we should add an endpoint to change a user's account type. This endpoint would be hit by the `runelite` website and would simply change a users type
       - Might be an issue here in the `select` statement for the `xp/get` route that we could get records for an old user `type`. So maybe the query would need to be updated to get records where the type is the current user's type.

**Describe alternatives you've considered**
I thought about moving the logic of fetching ranks for a type to the frontend since that could be possible. However, this completely loses the ability to look at things within a time interval, making it not the right solution to implement.

**Additional context**

**Comment by psikoi** [comment]
@deathbeam  I think should be closed
