### ISSUE TITLE
Tooltip for notification when focused in RuneLite settings is wrong

### ISSUE THREAD

**Issue by daviscook477** [runelite/runelite#6687]
**Is your feature request related to a problem? Please describe.**
It is unexpected that the setting for allowing idle notifications when runelite is focused is available under the runelite plugin rather than the idle notifications plugin.

This is not a duplicate of #3620 #1405 or #3208 since it is requesting a change to the location of this setting rather than being confused about its existence.

**Describe the solution you'd like**
The idle notifications when focused setting should be moved from runelite in the plugin menu to idle notifications.

**Describe alternatives you've considered**
Alternatively we could just mention how to enable this setting on the wiki page for idle notifications.

**Additional context**
![why_is_this_under_runelite_config](https://user-images.githubusercontent.com/10566967/48987531-dec26f80-f0ed-11e8-8904-163e54e5a3e0.png)

**Comment by Adam-** [comment]
This setting is not specific to the idle notifier.

**Comment by daviscook477** [comment]
Then at least this could have a quick pr to change the tooltip to indicate that this setting is for any notifications rather than saying "Toggles idle notifications for when the client is focused"

**Comment by deathbeam** [comment]
Updated the title
