### ISSUE TITLE
Something going on with the placeholder.

### ISSUE THREAD

**Issue by Texhilarate** [runelite/runelite#6692]
Hey I am seeming to have a bug within runelite using the placeholders. I can have a placeholder of an item and that exact item side by side within my bank. it seems to happen with anything that can deplete in uses eg potions tele necklaces etc. i have windows 10 and RL version 1.5.1 Launcher 1.5.2 OS revision: Rev 177. I was also selling a magic potion on the ge and was able to sell that same potion 4 times. I had a bunch of potions in my inv that i was selling off but am 100percent sure it was the same one. I don't think it would matter but I do also have 3 clients running.  I have tried closing the client and restarting and if i use a tele necklace with (4) uses and leave a placeholder when i re-enter with only (3) uses it will overlap the (4) placeholder. I have also tried accessing the bank from different locations castlewars, seers, edgeville and same thing.

**Comment by deathbeam** [comment]
That is just how OSRS works, the charge variations of items usually share same placeholder
