### ISSUE TITLE
Centered resizable mode.

### ISSUE THREAD

**Issue by Psyda** [runelite/runelite#6704]
**Is your feature request related to a problem? Please describe.**
Not really. Currently resizable feels really off center at lower screens sizes compared to fixed mode.

This screenshot where I resized the games frame might explain for what I'm looking for.

![dl0wp7a 1](https://user-images.githubusercontent.com/17040097/49053824-bdca4f00-f1bf-11e8-974c-94f7ce89176b.png)

**Describe the solution you'd like**
A plugin that keeps the game's frame resized to fit like in the screenshot above. This is much higher quality over running in fixed mode.

This would require the player is playing on resizable mode.

**Describe alternatives you've considered**
The stretched mode plugin is kind of a solution but is very low detail.

**Additional context**
This could probably fall into the stretched mode plugin as an option.

**Comment by deathbeam** [comment]
` The stretched mode plugin is kind of a solution but is very low detail.` next release we will have just UI scaled in GPU plugin with stretched mode, but canvas should remain the same size, so is that solution to your problem as well?

**Comment by Psyda** [comment]
Yes that's a perfect solution. I just tested the latest build and it's exactly what I wanted.

I've been annoyed by that issue for quite awhile. You guys work so fast my problems are addressed before I can even post them.

Cheers.
