### ISSUE TITLE
Clue Scroll Cryptic Clue visual glitch

### ISSUE THREAD

**Issue by Agridal** [runelite/runelite#6705]
The Cryptic Clue for the upstairs east Varrock bank drawer search for easy clue scrolls shows a shovel icon instead of a clue scroll icon with the Clue Scrolls plugin
![capture](https://user-images.githubusercontent.com/45377731/49054296-cae83d80-f1c1-11e8-92da-f5038ada80c9.PNG)

**Comment by Shield1739** [comment]
> Was the drawer already opened once you went upstairs?

![applicationframehost_2019-01-11_07-11-09](https://user-images.githubusercontent.com/18101480/51033050-15eec200-1570-11e9-9330-c5dfb9091a48.png)

same bug happened to me.
the drawer was closed when i went up
