### ISSUE TITLE
disable house portal exit at less than 80 stamina

### ISSUE THREAD

**Issue by graingert** [runelite/runelite#6709]
**Is your feature request related to a problem? Please describe.**
I'm always
frustrated when I forget to drink from the rejuvenation pool

**Describe the solution you'd like**
Disable clicking on the house portal exit at less than a certain stamina

**Describe alternatives you've considered**
Maybe hide the entity at less than x stamina

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features `Conditional menu entry removing`

**Comment by forsco** [comment]
Alternatively you could just drink from the pool when you go to your house? It's always the first thing you should be doing if that's what you're using your own POH for.

**Comment by graingert** [comment]
I'm using it to run items on other houses

**Comment by graingert** [comment]
yeah I figured the response would be 'git gud' ;)

**Comment by deathbeam** [comment]
Probably not worth implementing as notification, as the use case is very niche and useful probably just to you.

**Comment by forsco** [comment]
Otherwise you could implement it in your own build.
