### ISSUE TITLE
Update current level/XP of skill calculator as you gain XP

### ISSUE THREAD

**Issue by orecros** [runelite/runelite#6725]
**Is your feature request related to a problem? Please describe.**
There's no way to get a live feed of how many more times you have to perform some task to reach your target level/XP. you can quickly change the "current level" to reflect your true current level by clicking on your selected skill again, but this resets your target to be the next level.

**Describe the solution you'd like**
If you haven't "dirtied" your current level/xp by clicking in to the textbox, It'll update as you gain XP. switching skills at the top resets this.

**Describe alternatives you've considered**
move the level box over a bit to the right and add a refresh symbol that sets your current level / xp to reflect the true level / xp without modifying your target

**Comment by deathbeam** [comment]
Well, just use XP tracker and actions left, they are usually pretty accurate
