### ISSUE TITLE
Account banned for botting using RuneLite

### ISSUE THREAD

**Issue by CrashyBang** [runelite/runelite#6732]
**Describe the bug**
I have been running the latest version of RuneLite on Debian with the following command:
```
java -jar /opt/RuneLite/RuneLite.jar --mode=OFF
```

And I have just discovered I was banned 3 days ago on the grounds that I was botting, I have submitted an appeal but I doubt it will be successful, I don't really mind it was a new account but I thought it was worth alerting you.

**Environment (please complete the following information):**
 - OS: Debian Buster
 - RuneLite version: 1.5.1
 - Launcher version: 1.6.1

**Comment by james-munson** [comment]
thats what happens when you bot

**Comment by deathbeam** [comment]
Well, this has nothing to do with runelite
