### ISSUE TITLE
GPU vertex snapping affected by stretched mode scale %

### ISSUE THREAD

**Issue by poshdan** [runelite/runelite#6738]
When both the GPU and Stretched Mode plugins are enabled, the classic "vertex snapping" effect of the game is increased by the specified scale percentage.

Comparison:
https://imgur.com/a/yTAnCPE
Scale is set to 300% on a 4k screen (resizable mode) on the second image. The lower the percentage, the more normal it looks (0% being the same)

**Comment by Adam-** [comment]
This might be caused by the 3d renderer using the centerx/y from the smaller canvas in stretched mode.

**Comment by logarrhythmic** [comment]
The geometry shader currently translates the world coordinates for each vertex into integer screen coordinates in the smaller canvas. This causes very visible vertex snapping when these integer coordinates are later scaled up.

The geometry shader can be changed to output floating point screen coordinates, I tried doing that, and it works fine.

I didn't notice a performance hit either, although I'm not running this on hardware where that would be immediately apparent. GPU load was jumping between 35% and 45% in the area in the following videos, and changing to floats didn't increase it by any noticeable amount.

Comparison videos below. Both have 2x stretched mode enabled, and the video is taken from a 1600x900 region in the middle of a 2560x1440 display.
https://pinfu.pw/ln/stretched2x-int.mp4
https://pinfu.pw/ln/stretched2x-float.mp4

**Comment by Adam-** [comment]
Do you have a patch?

**Comment by logarrhythmic** [comment]
I'll clean things up a bit and make a pull request. Sorry for the sketchy links, I didn't want to upload to youtube since I ended up capturing in 900p and it would get downscaled to 720p.
