### ISSUE TITLE
Increase size of spellbook icons

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#6742]
Since around 74.7% of the people wanted spellbook icons size to be increased when filters are active, maybe this can be implemented in RuneLite.

**Comment by Nightfirecat** [comment]
Generally speaking, we're never interested in making updates to accommodate features that failed polls.

**Comment by deathbeam** [comment]
Unless jagex will do it, we wont

**Comment by Krigeris** [comment]
This entire client is stuff Jagex won't do...
