### ISSUE TITLE
Idle Notifier after chiseling Dense/Dark Essence Blocks fails to notify.

### ISSUE THREAD

**Issue by majorvegas** [runelite/runelite#6747]
**Describe the bug**
The Idle Notification plug-in does not notify when the player is idle after chiseling dense/dark rune essence blocks. 

**To Reproduce**
1. Turn on Idle Notification plug-in and appropriate settings.
2. Chisel (not mine) dense rune/dark essence blocks
3. Wait

**Expected behavior**
The plugin should generate a notification when the player is done chiseling 

**Screenshots**
N/a

**Environment (please complete the following information):**
 - OS: Window
 - RuneLite version: 1.5.2.1

**Additional context**
This is a pretty minor bug, I only got the ability to use dark essence blocks last night, could have sworn it was working last night but I can't remember. Mining works fine but chiseling/finishing the blocks does not.

**Comment by deathbeam** [comment]
set the delay > 601

**Comment by majorvegas** [comment]
My current delay value is at 10,000.

**Comment by Twiglet1022** [comment]
#6564 will work for this as it will notify immediately when the essence blocks run out

![essence block inventory idle](https://user-images.githubusercontent.com/29353990/49262852-29baea80-f440-11e8-9edd-c8bf8b28d24b.gif)
