### ISSUE TITLE
Notification displays active window username

### ISSUE THREAD

**Issue by ebelties** [runelite/runelite#6751]
**Describe the bug**
When you have two open RuneLite clients, the (Windows) notifications display the wrong name sometimes. When you get a notification that you (for example) are idle, it'll display the username of the active window.

**To Reproduce**
1. Open two clients
2. Do a activity in-game (ex. woodcutting)
3. Get the idle notification on the background client
4. You'll see the wrong name is in the notification

**Expected behavior**
The username of the client that is idle.

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - RuneLite version: 1.5.2.1
 - Launcher version: 1.6.0

**Comment by deathbeam** [comment]
This cant happen. You probably just got notification for the other char, or the notif was delayed (what can happen)
