### ISSUE TITLE
Menu Entry Swapper Suggestion

### ISSUE THREAD

**Issue by Sillyman69** [runelite/runelite#6752]
I'm always frustrated when I am making necklaces while crafting or smithing dart tips. It is a pain to right click make all.

Please add the smithing interface to the menu swapper add-on

Woox For President!

**Comment by Nightfirecat** [comment]
This is on [our rejected features list](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping):

> * `Menu reorder in shop/artisan skill screens`: Other clients don't implement these swaps, and would be too strong for numerous activities (examples include "Buy-50" swaps, "Make All" swaps for smithing/crafting, etc.)
