### ISSUE TITLE
Duplicate Sound Effects Play when Spam Clicking Equipable Items While the Equipment Bonuses Interface is Open

### ISSUE THREAD

**Issue by Millerni456** [runelite/runelite#6754]
**Describe the bug**
When spam clicking equipable items with the equipment bonuses interface open, the sound effect plays multiple times before finishing, leading to an unpleasant sound artifact.

**To Reproduce**
1. Open the Equipment Bonuses Interface
2. Spam Click an equipable item in your inventory, making sure that another equipment item is placed in the inventory slot you just clicked.
3. If you have sound effects enabled, you will hear the respective equipment sound effect playing multiple times, overlapping with itself and sounding unpleasant

**Expected behavior**
My expectation was that the sound effect would not play a second time until it finishes the first time. This is how it works if you repeat the above steps with the equipment bonuses interface closed.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - RuneLite version: 1.5.2.1
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
Does this happen on the vanilla client?

**Comment by deathbeam** [comment]
I dont think we can cause this, this sounds like vanilla bug

**Comment by Nightfirecat** [comment]
Can you provide more information on this, per my previous question?

**Comment by Nightfirecat** [comment]
This issue has seen no posts for nearly one year after being asked for more information, so I am closing it.
