### ISSUE TITLE
Reposition Wilderness "level" HUD

### ISSUE THREAD

**Issue by machvise** [runelite/runelite#6758]
is it possible to be able to reposition the wilderness "level" HUD with alt key like minimap? If you have the Inventory scaled up to large in resizable mode, it covers up the Wilderness level HUD. I have attached an example picture of the problem. 
![runelite_2018-11-30_02-58-50](https://user-images.githubusercontent.com/45482694/49279153-49581000-f44c-11e8-901d-a730b5b6f025.png)

**Comment by Adam-** [comment]
added in 0a86fe35aff62d24942405490ac8b88b98bc9dcc
