### ISSUE TITLE
Outdated Farming timers showing incorrect times

### ISSUE THREAD

**Issue by WobbleCogs** [runelite/runelite#6767]
Farming timers on RuneLite are showing the old farm tick system (assumes every growth cycle occurs at a fixed time)

Current timers are based on a 'personal' timer where the crop grows xx minutes after planting. For example, herbs are ready 80 mins after planting. 

Farming timers need updating to use the existing model.

**Comment by raiyni** [comment]
It's still a tick based system. The problem is that ticks can happen with a X minute window and we don't know when that happens.

**Comment by deathbeam** [comment]
We already have issue for farming timers, and description of this issue is mostly wrong
