### ISSUE TITLE
Border of RuneLite and the windows task bar

### ISSUE THREAD

**Issue by Jmac191** [runelite/runelite#6770]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...] 
When I try to drag the client to the bottom it always goes past the blue bar at the bottom. It's just slightly annoying not being able to drag it and have it pop into place or stop at the blue bar. It's nothing important and it's only slightly annoying lol. (I'm on windows 7. Just in case y'all were going to ask.)

**Describe the solution you'd like**
When we drag the RuneLite client towards the task bar have it stop so it doesn't go past the windows task bar and cover up part of the client. (Yes contain in screen is turned on.)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**
Picture 1 is where I manually drag it and picture 2 is when I just drag it down to the corner. Like I said it's nothing important but I figured it probably annoys other people also so I figured I'd make a post and see if y'all are able to fix it. Thanks for everything you do guys/ gals.
1. https://imgur.com/a/UPcf2Wu
2. https://imgur.com/a/LlNMTWm

**Comment by deathbeam** [comment]
Disable "Custom window chrome" in "Runelite" settings

**Comment by Jmac191** [comment]
@deathbeam That didn't work. It removed the custom window etc but now it won't contain in screen.

**Comment by deathbeam** [comment]
Well that was not part of the issue
