### ISSUE TITLE
World hopper shows up as world switcher in side bar

### ISSUE THREAD

**Issue by daviscook477** [runelite/runelite#6777]
Can we either rename the plugin to world switcher or rename the side bar icon to world hopper for consistency.
![inconsistency](https://user-images.githubusercontent.com/10566967/49324417-f0938080-f4fa-11e8-810e-9f4cb565d645.png)

**Comment by deathbeam** [comment]
The plugin do not provides only the world switcher functionality, but also keyboard shortcuts for hopping. I dont see why the names should be consistent

**Comment by inewman** [comment]
Maybe the main option doesn't need to be consistent with the sidebar hover text, but the option to enable the sidebar specifically ("Show world hopper sidebar") should be.
