### ISSUE TITLE
RuneLite client going under taskbar

### ISSUE THREAD

**Issue by Jmac191** [runelite/runelite#6781]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
(This is a re-up since the last one got closed because I forgot to wright down some problems. My bad.)
When I try to drag the client to the bottom it always goes past the blue bar at the bottom. It's just slightly annoying not being able to drag it and have it pop into place or stop at the blue bar. It's nothing important and it's only slightly annoying. I'm on windows 7 just in case y'all were going to ask. Yes contain in screen is turned on and when I disable custom window chrome like suggested all it does is remove the custom window from RuneLite. It returns to the normal windows 7 look and doesn't contain in screen anymore. I figured I'd add this to the issue to let you know what happens when I try that, since I forgot to put that in my last issue,

**Describe the solution you'd like**
When we drag the RuneLite client towards the task bar have it stop so it doesn't go past the windows task bar and cover up part of the client. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**
Picture 1 is where I manually drag it and picture 2 is when I just drag it down to the corner. Like I said it's nothing important but I figured it probably annoys other people also so I figured I'd make a post and see if y'all are able to fix it. Thanks for everything you do guys/ gals.

1. https://imgur.com/a/UPcf2Wu
2. https://imgur.com/a/LlNMTWm

**Comment by deathbeam** [comment]
https://stackoverflow.com/questions/10123735/get-effective-screen-size-from-java

**Comment by deathbeam** [comment]
Well based on people's commens this is correct behaviour and should not be changed
