### ISSUE TITLE
feature-request Increase size of RuneLite client UI text and icons

### ISSUE THREAD

**Issue by pineapplemachine** [runelite/runelite#6783]
**Is your feature request related to a problem? Please describe.**

On my high-resolution monitor, the icons and text in the RuneLite UI (the sidebar) may be pretty, but they appear small and are hard to read.

**Describe the solution you'd like**

I would like an option to scale or otherwise increase the font and icon sizes in the RuneLite UI. I would like for this option to be independent of my OS DPI or scaling settings - I'm having trouble reading the tiny pixelated RuneLite text - some of these fonts are only a few pixels high! - but my larger and more legible OS text is fine.

**Additional context**

You know, this bit:

![image](https://user-images.githubusercontent.com/7266412/49330896-ee363280-f59d-11e8-888c-704eacbb8bff.png)

**Comment by pineapplemachine** [comment]
I am running Windows 7 and I do not have this option. Checking the similar option "Disable display scaling on high DPI settings" does not change the UI appearance.

If your suggestion involves changing the OS text size setting for that checkbox to have an effect, then this does not solve my problem - my OS text size is fine. I want to increase the size of the RuneLite UI text independently of my OS settings.

![image](https://user-images.githubusercontent.com/7266412/49337782-74e02380-f621-11e8-935d-22a09ac7fb46.png)

**Comment by deathbeam** [comment]
That is usually not how this works, the apps should adapt to your DPI settings. Idk about windows 7

**Comment by pineapplemachine** [comment]
Sorry, I may have been unclear. This is not a duplicate of #715. I do not have a DPI problem. The RuneLite pixel fonts display at the same DPI as everything else on my monitor, and the RuneLite UI is the only thing that I'm having a hard time with. This is not a technical display issue, but an accessibility issue. I said "high-resolution monitor", but I did not mean 4K - I meant 1440p.

The issue is that the RuneLite UI text commonly uses characters that are _five or six pixels high_ and that are not anti-aliased, which makes them difficult to read. Other font options including anti-aliased fonts would help, but just scaling it up 2x like I already scale up the Runescape client using the extremely helpful stretch plugin would be good enough.

**Comment by deathbeam** [comment]
Well as I said, you can already do that. With java 9+, there is param: `java -Dsun.java2d.uiScale=2.5 -jar RuneLite.jar`.

**Comment by pineapplemachine** [comment]
You did not mention that solution before. When I tried it, there was no change in the application's appearance or behavior. My log is here: https://pastebin.com/9mimfsuP

Regardless, I would suggest that this should be an option in the UI, or at least in a configuration file.

Will you please re-open the issue so that someone else might take a look?

**Comment by Alexsuperfly** [comment]
you need at least java 9 for that to work, you're currently using 8

**Comment by deathbeam** [comment]
It cant be an option, because it do not works with Java 8 what we ship with launcher. And the uiScale param is taken directly from the stackoverflow threads that are linked in #715.

**Comment by pineapplemachine** [comment]
I'm a bit lost here. After trying to update Java through the Java Control Panel and receiving a "Download failed" error, I went to find an installer to download. The Java download page lists Java 8 as the recommended and apparently most recent version. https://www.java.com/en/download/manual.jsp

Even so, this is an undocumented and very user-unfriendly manner of UI configuration. I would like to suggest again that the issue be re-opened and that a more accessible option for increasing the size of the text and icons in the RuneLite UI be considered.

**Comment by raiyni** [comment]
I don't have problems viewing the UI at 1440p looks like the same scale as 1080p

**Comment by deathbeam** [comment]
You need Java 9+ for the paramater to work, and then command I sent earlier is what should solve your problem (maybe you would also need to add --nojvm at the end). There is no reason to add config for this as 1. we cant, 2. this is unusual scenario because the DPI scaling should be everything that you need.

**Comment by pineapplemachine** [comment]
I was able to get the Java update to work, but the uiScale option still does not do anything, with or without `--nojvm`. The updated version is still "jre1.8.0_191", which I am guessing is not Java 9. It might help if you can share a link for where to download and install a version of Java which will recognize the uiScale option, since I'm having a hard time with this myself. Are you referring to JDK 9, maybe, as opposed to a JRE version? I don't have this machine set up for Java development, and I don't really like the idea of taking a couple of hours to set that up to experiment with an undocumented config option that only _might_ work.

I do not understand why it should be especially difficult to just load a different font? Hell, point me to instructions on how to build the project and where in the code base fonts are loaded and displayed and I can probably get around to doing it myself.

**Comment by jessedezwart** [comment]
For Jagex accounts (you can't set args), you can temporarily set JAVA_OPTIONS.

Create a bat file:
```
@echo off
set _JAVA_OPTIONS=-Dsun.java2d.uiScale=1.25
start "" "C:\Users\<you>\AppData\Local\JagexLauncher\bin\JagexLauncher.exe"
```

When toying with the scale, make sure Jagex Launcher doens't keep running in the background, otherwise it won't use the new JAVA_OPTIONS.

**Comment by ojsl1** [comment]
The client is literally unusable on 2160p monitors because there's no way to scale the client UI.

**Comment by coopermor** [comment]
> The client is literally unusable on 2160p monitors because there's no way to scale the client UI.

https://github.com/runelite/runelite/wiki/RuneLite-Launcher-Configuration#Scale
