### ISSUE TITLE
Update slayer task based on last interacted monster when combat brace notif occurs

### ISSUE THREAD

**Issue by kuhnertdm** [runelite/runelite#6793]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
After changing the current slayer assignment (outside of the Runelite client), the current slayer task GUI item at the top left of the screen stays as it was (I wouldn't think this part would be fixable). However, after killing enough of the new slayer enemy to get the combat bracelet notification, **the number of remaining enemies in the GUI item is updated, but the type of enemy is not.**

**To Reproduce**
1. Get a slayer assignment on the Runelite client, and note the current assignment GUI item at the top left (should be correct)
2. Outside of the Runelite client (on mobile, vanilla OSRS, OSB, etc), change the assignment (through skipping or completion)
3. Back in the Runelite client, note that the assignment GUI item has not changed
4. In the Runelite client, kill enough of the newly assigned enemy to get a combat bracelet notification
5. Note that the current assignment GUI item's image/text for the type of enemy has not changed, but the number has updated.

**Expected behavior**
After the combat bracelet gives its notification, the GUI item updates to show the new assignment's image and text.

**Screenshots**
![](https://i.imgur.com/IkBzc1J.jpg)

**Environment (please complete the following information):**
 - OS: Windows 7
 - RuneLite version: 1.5.2.1
 - Launcher version: 1.6.0

**Additional context**
I would suppose that you'd need to detect the enemy that the player just killed in order to trigger the combat bracelet notification. If that's not something you can do, this fix would probably be impossible.

**Comment by Alexsuperfly** [comment]
we cant know what monster you're assigned unless you get the task on RL or check the task using gem/helm. so you gotta do that, theres no way around it

**Comment by daviscook477** [comment]
and although it's true that we could do some work to time the xp drop with the monsters that died to try to verify if our current idea of what task you are on is correct, that seems like a lot of work for a feature that would be pretty buggy and mostly unnecessary (if you either A just use runelite or B use your slayer gem when coming back to runelite from another client) - I think the wiki probably does a good job of explaining solutions A and B so I doubt there's much we can/should do a bout this

**Comment by Adam-** [comment]
fixed in 1f6ae893d732cf3a022fe6d9662cd2a42ff2b217
