### ISSUE TITLE
More features for bank organization.

### ISSUE THREAD

**Issue by techdeck591** [runelite/runelite#6795]
**What:**   
- Bank organization grinds my gears.

**Solution:**   
- Implement a way to add more tabs. I'm thinking an arrow button next to the last tab to view more tabs. 
- Implement a way to have a blank space. I say this because it would be nice to have rows dedicated to (a) specific item(s).

**Comment by deathbeam** [comment]
1. We have bank tag tabs
2. There are placeholders in vanilla

**Comment by techdeck591** [comment]
That's cool and I didn't know about that, but I still don't think that's the same idea. 

I attached a screenshot of my bank with a square around a blank space, and an arrow where I'd want to put it. Hopefully this helps you visualize what I'm talking about more.
![screenshot 3 _li](https://user-images.githubusercontent.com/45544279/49345822-6a388500-f647-11e8-870b-7b100c2b7988.jpg)

You only have blank spaces at the end of groups of things in the bank, I want to be able to put them in the middle.

**Comment by Alexsuperfly** [comment]
thats what fillers can do

**Comment by 15987632** [comment]
just move the bank filler where you want them to go, you can drag them like an item.

**Comment by Hydrox6** [comment]
That's because the bank doesn't have the concept of absolute positioning, it's just a collection of lists. This is not something we really want to change.

As others have said, Fillers can be used to add blank spots to any section you want.

Alternatively, there are situations in which you can make vertical groups of items using the leftover spaces on rows.

**Comment by SomeZer0** [comment]
> Fillers can be used to add blank spots to any section you want.

A downside of this is that it counts against your bank space.

I know that, at least for (late game) ironmen, extra bank space is pretty non-existent.
