### ISSUE TITLE
Oak Armchairs are listed as requiring level 23 when they actually require level 26 in the Construction Skill Calculator

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#6798]
Reported by `Bauer` in Discord

**Comment by Twiglet1022** [comment]
Perhaps these could all be tidied up in one issue? Just need to verify the wiki's xp values in-game.

![image](https://user-images.githubusercontent.com/29353990/49350204-009b9380-f6a6-11e8-9b2a-4eff7eb9a4a3.png)

**Comment by Berry-95** [comment]
> Perhaps these could all be tidied up in one issue? Just need to verify the wiki's xp values in-game.
> 
> ![image](https://user-images.githubusercontent.com/29353990/49350204-009b9380-f6a6-11e8-9b2a-4eff7eb9a4a3.png)

A quick look at the wiki, contradicts some of your xp-wiki values...
Also the fern requiring level 12 already exists however the level 1 requirement is true when planting for a big plant spot (http://oldschoolrunescape.wikia.com/wiki/Fern_(small_plant))

**Comment by Twiglet1022** [comment]
Yea they would need to be checked in game. I got the wiki values from a page that lists all the construction items in 4 tables (level 1-24, 25-49 etc), but it doesn’t surprise me that the wiki contradicts itself elsewhere.
