### ISSUE TITLE
Screenshot copy to clipboard and imgur upload not working

### ISSUE THREAD

**Issue by tikeyike** [runelite/runelite#6801]
**Describe the bug**
The copy to clipboard and upload to imgur functionality not working at all

**To Reproduce**
1. Manually take a screenshot with Upload to Imgur checked
2. Right click and paste (nothing in clipboard)

**Expected behavior**
When taking a screenshot with the Upload to Imgur checked, it should upload your screenshot and copy the URL to your clipboard so you can paste it.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Latest Version
 - Launcher version: Latest Version

**Comment by deathbeam** [comment]
I  am pretty sure this is working, can you try again?

**Comment by tikeyike** [comment]
I guess it kind of fixed itself, earlier today it wasn't working, but looks like after restarting my PC it works.

**Comment by 15987632** [comment]
This shouldn't be closed, it is caused by the plugin not have an onConfgUpdate event or whatever it is. I didn't actually check to make sure what i just said is true but the option only started working after a restart so I assumed.

**Comment by SomeZer0** [comment]
I was having issues with ShareX uploading images to Imgur earlier today, I assume it's related.

**Comment by tikeyike** [comment]
Looks like it was imgur: http://status.imgur.com/
They had some uploading issues before.

**Comment by SomeZer0** [comment]
I'm assuming there wasnt any sort of message stating that the image "failed to upload to imgur."

If not, that should probably be a thing.
