### ISSUE TITLE
BSOD when using GPU mode 

### ISSUE THREAD

**Issue by FelipeBodelon** [runelite/runelite#6803]
I am getting fatal error crashes (Blue screens) when using RuneLite, this has only happened when using GPU mode and stretched mode, not sure if it happens otherwise. I will test with CPU mode as for now it is impossible for me to play otherwise. It crashes minutes into playing. It has crashed doing certain actions:
- Click to trade player.
- Examine object (crashes right after)
- Pressing enter to type (on WASD camera mode).
- Even on the background.

Running on:
- GPU: gtx 960m
- CPU: i5-6300hq
 - OS: Windows 10
 - RuneLite version: 1.5.2.1

I read that it may be a problem with the 9xx series graphics card and Java VM.

I can post log files, but as for now they doesn't seem to give any useful information.

Edit: With further testing, I noticed that my machine actually uses Intel Integrated graphics when the GPU option is selected, so it doesn't use the GPU at all. GPU mode off seems to be stable.

**Comment by TheStanian** [comment]
Also seem to be getting BSODs when running in GPU mode, but mine seem to be more at random. Haven't been able to find a pattern yet. It is also using the Intel HD Graphics 630, which in itself is fine, but I'd like to be able to use my dedicated GPU and not BSOD.

Specs:
- CPU: Core i7 7700HQ (with Intel HD Graphics 630)
- GPU: GTX 1050 Max Q
- OS: Windows 10
- Runelite Version: 1.5.5
- JVM Version: 1.8.0_131

**Comment by dusanjosik** [comment]
I have the problem on the same version of RuneLite as @TheStanian. My problem is a bit different, it gives me a blue screen of death at random. It could happen after 2 minutes, it doesn't even have to give me it. My specs are:

CPU: Intel i3-6100U 2.3Ghz
GPU: Nvida GeForce 940MX
RAM: 8GB DDR4
OS: Windows 10

**Comment by Abextm** [comment]
This is an issue with your hardware and/or drivers
