### ISSUE TITLE
Change Dragon Battleaxe spec text

### ISSUE THREAD

**Issue by stefanlawr** [runelite/runelite#6805]
Changing the text from RRAAAAARGH to REEEEEEEEEE would increase the value of the weapon and make Pest Control a bit more bearable.

**Comment by deathbeam** [comment]
It's almost great idea except that I don't think we want to do meme plugins outside of april fools, sorry.

**Comment by Twiglet1022** [comment]
Raarrrrrgggggghhhhhhh!

![raarrrrrgggggghhhhhhh](https://user-images.githubusercontent.com/29353990/49475578-7ff8a680-f80f-11e8-8de8-44cff355bb09.gif)
