### ISSUE TITLE
[SOLVED] Could ctrl + w dont erase last word?

### ISSUE THREAD

**Issue by Ravor9** [runelite/runelite#6806]
Edit: I cant tag is as solved, I believe its a moderator tool. Just in case, its solved

**Is your feature request related to a problem? Please describe.**
To type question mark on my pc is ctrl + alt + w. But for some reason ctrl + w wipe the last word, (and the question mark), I have no way to type it in game since the question mark is used for another macro. I dont want to do one exclusively for runescape since I dont talk too much in game 

**Describe the solution you'd like**
ctrl + w do nothing

Notes:
I believe its not important, probably will not be used for 99% of the players, and maybe some people even like it. But if its easy to code its something I would really appreciate.

**Comment by Alexsuperfly** [comment]
disable the clear shortcuts option of the chat commands plugin
