### ISSUE TITLE
Plugin for disabling ironman chat icons

### ISSUE THREAD

**Issue by hi-im-branx** [runelite/runelite#6807]
**Is your feature request related to a problem? Please describe.**
The ironman chat icons are excessive and distracting, especially when multiple people are talking in a clan chat. 

**Describe the solution you'd like**
The plugin would completely remove ironman chat helms from in-game messages (and move the players name a bit left to compensate for it being gone)

**Describe alternatives you've considered**

**Additional context**

**Comment by deathbeam** [comment]
`We should not hide game elements that uniquely identify accounts`.

**Comment by hi-im-branx** [comment]
Iron man helmets don't uniquely identify accounts...

**Comment by TheStonedTurtle** [comment]
@hi-im-branx They do identify something unique to the account.

No icon = Regular Player
Gray helmet=Ironman
Red helmet =HCIM
White helmet = UIM
Crowns = P Mod/J Mod

**Comment by hi-im-branx** [comment]
@TheStonedTurtle Right but that's different from uniquely identifying an account. The only thing that uniquely identifies an account is the username.
