### ISSUE TITLE
Click distance varies based on camera rotation

### ISSUE THREAD

**Issue by Syklis** [runelite/runelite#6824]
**Describe the bug**
Upon enabling GPU rendering and greater draw distances, I've noticed that the distance you can click on objects varies a little based on camera rotation.

Here I'm unable to click the bank window, as I'm too far away.
![straight](https://user-images.githubusercontent.com/1354227/49519941-dd8e0100-f8aa-11e8-80d3-11c960de97ea.png)

Yet here, standing at the same spot but the camera rotated, I'm able to click even the further bank window.
![skewed](https://user-images.githubusercontent.com/1354227/49520079-280f7d80-f8ab-11e8-8b79-7b08d29bf035.png)

**To Reproduce**
1. Enable GPU rendering and greater draw distances for ease of testing.
2. Find anything static to click on and move a couple tiles too much away from it to be able to click.
3. Rotate the camera and try to click it again.

**Expected behavior**
Max click distance remains the same independent of camera rotation.

**Environment (please complete the following information):**
 - OS: Windows 10 64-bit
 - RuneLite version: 1.5.2.1
 - Launcher version: 1.6.0

**Comment by Twiglet1022** [comment]
Reminds me of #6510 could be a similar root cause?

**Comment by Adam-** [comment]
It is based on camera position, and this is intended behavior I think.

**Comment by Nightfirecat** [comment]
Per Adam's comment, this is intended.
