### ISSUE TITLE
'use with' menu re-ordering

### ISSUE THREAD

**Issue by paul-kline** [runelite/runelite#6825]
**Is your feature request related to a problem? Please describe.**
Specifically thinking about farming, but I'm sure this is applicable elsewhere. When I use seeds or compost on a plot and there is another person around, the default is to use the seed/compost with the person. Which I frustratingly do frequently. Much like the bank and shopkeep menu re-ordering it would be really nice to have menu re-ordering for 'use with' that is practical. I never mean 'use with' another player. I know I could hide all other players, but that's not a solution. 

**Describe the solution you'd like**
Could an 'order of operations' priority be implemented for common items that are 'used with' frequently? For example, when using any compost with something, a plot has a higher priority level than other players and npcs and is the top option.

**Describe alternatives you've considered**
Hiding other players, but this is lonely and doesn't solve the 'use with' npc problem either due to wandering farmers.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features <- conditional menu swapping
