### ISSUE TITLE
Skill Calculator Magic Combat Spells Is kinda not clear

### ISSUE THREAD

**Issue by daviscook477** [runelite/runelite#6828]
**Describe the bug**
For the skills calculator we allow the user to calculate actions for combat spells using the base magic xp. This is only really useful for splashing since otherwise the xp per action is much larger due to actual damage being dealt. If a user were to use the skill calculator to determine the number of casts they need to bring to some training area to reach some level they will end up getting way too many casts because the xp / action values will be off.

This may be deemed unnecessary as players should probably know that magic spells give base xp plus damage xp but it might be good to clarify this in the skills calculator.

Some potential solutions are to not display combat spells by default and hide them behind a checkbox for splashing so users understand that this is only accurate for splashing. Additionally we could have a bit of text on the magic panel that clarifies this before going into the list of spells. Furthermore we could just add a tooltip to the combat spells that indicates it's base xp per cast. Or we could modify the txt itself of the combat spell in the list to indicate that the xp is base xp (not damage xp).

**Comment by deathbeam** [comment]
We cant really do anything else as that depends on hits, just magic xp is static. We can either remove combat spells completely or just leave it as is, and I vote for leaving it as is
