### ISSUE TITLE
Total exp per slayer task

### ISSUE THREAD

**Issue by sparky12007** [runelite/runelite#6831]
**Is your feature request related to a problem? Please describe.**
No, just something I think would be useful

**Describe the solution you'd like**
I'd like to see when you highlight your slayer task how much slayer exp & potentially HP/combat exp to expect from that task

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by deathbeam** [comment]
This is not really possible because you can kill different monsters + there are superiors etc
