### ISSUE TITLE
Add laps/hr to agility display

### ISSUE THREAD

**Issue by Feenoh** [runelite/runelite#6836]
title

**Comment by jackbrown1993** [comment]
I think @Feenoh is asking for a display showing an estimated amount of laps per hour based on the time you are taking to complete the current course.

**Comment by deathbeam** [comment]
The preferred way to go about implementing this is move the laps data to XpTrackerPlugin (or if used in both agi and xp tracker, to shared place) and then integrate laps done to XpTrackerPlugin in similar way as kills done and kills/hr are integrated atm.

**Comment by LlemonDuck** [comment]
This was added in a626e97176a872425a9209ca03eaa0325e277c30
