### ISSUE TITLE
Mining ticks for 3t 4g

### ISSUE THREAD

**Issue by tai5** [runelite/runelite#6840]
I am suggesting a feature, simmilar to what Konduit has, shown in this video at 9:06 https://www.youtube.com/watch?v=ou4FGh_fzZM&t=545s

The mining tick is a tool used to indicate every three ticks and is used in doing 3t 4g. It shows a blank xp drop, so the rythm is not messed up, and players are able to focus on the mining.

**Comment by Adam-** [comment]
So really this is a request for 0 xp xpdrops?

**Comment by tai5** [comment]
Yes, precisley

**Comment by Adam-** [comment]
I dont see why this has to be specific to mining then. It could just be its own plugin to generate xpdrops when one is not generated on a tick.

**Comment by tai5** [comment]
Yeah, that is true, it would be a very good update in my opinion, but the way the xpdrops are generated would need to correlate with the action one is doing. For example, one fake xpdrop generating 3 ticks after the first real xpdrop, and not just at login

**Comment by while-loop** [comment]
Does the metronome plugin help with this?
