### ISSUE TITLE
Drops from Abyssal Sire don't show up when using "Only show loot" option

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#6843]
No drops show up with Ground Items when killing the Abyssal Sire with `Only show loot` enabled

**To Reproduce:**
1. Enable `Ground Items` and `Only show loot`
2. Go to Sire
3. Kill Sire
4. Wonder why your Onyx Bolt Tips didn't show up

**Environment:**
 - RuneLite version: 1.5.3

**Comment by GottaSlay** [comment]
Same issue with zulrah.
