### ISSUE TITLE
GPU MSAA Bug

### ISSUE THREAD

**Issue by Isafdor** [runelite/runelite#6846]
Nvidia Control Panel MSAA no longer functional after GPU render MSAA was implemented
I have forced MSAA enabled in the Nvidia Control Panel and have had it on for a while now and it has worked until the recent update, now the lines have become jagged again despite it still being on, so I assumed the plugin can override Nvidia's settings and tried enabling the GPU plugin's MSAA and all I get is a black screen until I set it back to Disabled on the plugin.

1. Go to 'GPU plugin'
2. Click on 'Anti Aliasing'
3. Scroll down to 'MSAA x2 or x16 (all of them yield the same result)'
4. Black screen

**Expected behavior**
Runescape with no jagged edges.

**Screenshots**
https://imgur.com/a/uhCwXX4

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.3
 - Launcher version: 1.6.0

**Additional context**
[application.log](https://github.com/runelite/runelite/files/2654184/application.log)
nd macOS.

**Comment by Twiglet1022** [comment]
Set Antialiasing - Mode to "Enhance the application setting" and it should work.

You've got your Nvidia Control panel set to override any application specific setting which will mean that unless you set runelite to use 8x MSAA it'll glitch out. Not sure if that's what it's supposed to do, but that was the case for me.

**Comment by Isafdor** [comment]
> Set Antialiasing - Mode to "Enhance the application setting" and it should work after a restart of the client.
> 
> You've got your Nvidia Control panel set to override any application specific setting which will mean that unless you set runelite to use 8x MSAA it'll glitch out. Not sure if that's what it's supposed to do, but that was the case for me.

This fixed the problem, thanks.

**Comment by Isafdor** [comment]
> Set Antialiasing - Mode to "Enhance the application setting" and it should work after a restart of the client.
> 
> You've got your Nvidia Control panel set to override any application specific setting which will mean that unless you set runelite to use 8x MSAA it'll glitch out. Not sure if that's what it's supposed to do, but that was the case for me.

This fixed the problem thanks.
