### ISSUE TITLE
Add hunter area tooltips to world map plugin

### ISSUE THREAD

**Issue by Rusty-Gravy** [runelite/runelite#6848]
Hey,

My friend came up with the idea of showing which hunter level you need for each training area, much like the teleports do.
An extra idea would be showing what can be hunted at the location.

Are these good ideas? Let me know what you think, thanks for your time.

**Comment by Nightfirecat** [comment]
Many hunter areas have multiple creatures to hunt... How would we handle those cases?

**Comment by Hydrox6** [comment]
It could be shown on the tooltip, something like this (but looking better)
![hunter](https://user-images.githubusercontent.com/2979691/49616086-7f931380-f9a7-11e8-9cdf-4ef4d5df078f.png)

**Comment by Rusty-Gravy** [comment]
> 
> 
> It could be shown on the tooltip, something like this (but looking better)
>

Yeah that looks nice!

**Comment by nlruk** [comment]
> Many hunter areas have multiple creatures to hunt... How would we handle those cases?

There is a guy called milky who has done all the other tooltips. he'll know.

**Comment by nlruk** [comment]
I found him @melkypie
