### ISSUE TITLE
Entity Hider - Hide Tagged NPCs or vice-versa

### ISSUE THREAD

**Issue by overwatcheddude** [runelite/runelite#6854]
Using Entity Hider and NPC indicator features, allow the player to hide marked/highlighted NPCs or vice-versa.

**Comment by deathbeam** [comment]
The entity hider is intentionally made to be all or nothing, to prevent abuse

**Comment by benjaminlwest** [comment]
> The entity hider is intentionally made to be all or nothing, to prevent abuse

@deathbeam can you expand on this further? I assume there has been a conversation regarding potential for abuse, but I am of the opinion that there is genuine merit to hiding specific NPCs while persisting others.

**Comment by benjaminlwest** [comment]
> > The entity hider is intentionally made to be all or nothing, to prevent abuse
> 
> @deathbeam can you expand on this further? I assume there has been a conversation regarding potential for abuse, but I am of the opinion that there is genuine merit to hiding specific NPCs while persisting others.

nevermind, found Adam's comment [https://github.com/runelite/runelite/issues/14605#issuecomment-1014914306](url)
