### ISSUE TITLE
Player and NPC Alt Click Lookup

### ISSUE THREAD

**Issue by Jimdm3** [runelite/runelite#6859]
You can alt click items to search GE values. Add the ability to alt click NPCs and players to bring up information like stats and drops.

Press alt and click on a player's name or character and it would pull up a hiscores search. Press alt and click on a Dark beast and it will pull up drop table, combat stats, and maybe other information from the wiki.

The NPC interface could look something like this. https://i.imgur.com/BNwc1cx.png

**Comment by deathbeam** [comment]
You can already right click lookup, and for the NPC lookup, we already have issue for wiki plugin
