### ISSUE TITLE
XP Tracker: single level indicators

### ISSUE THREAD

**Issue by Rsl1122** [runelite/runelite#6863]
**Is your feature request related to a problem? Please describe.**

Current XP Tracker can be set to track progress to, for example 5 levels ahead of the current level.
When leveling multiple levels it is daunting to see how large amount of actions is required.

**Describe the solution you'd like**

I would like to see indicators where next levels will be attained to break down the task into smaller subtasks

**Describe alternatives you've considered**

I have considered multiple trackers per skill, but I think that is a bit pointless.

**Additional context**
Here is an image of the current xp tracker and an example of what I mean
![1](https://cdn.discordapp.com/attachments/360418274619555841/520678601587425280/unknown.png)

**Comment by JAnken123** [comment]
This would be pretty neat. Have you looked at possible ways of implementation?

**Comment by Rsl1122** [comment]
> This would be pretty neat. Have you looked at possible ways of implementation?

Looks like [XPInfoBox](https://github.com/runelite/runelite/blob/ed5fb05a5195bf9ae6c890a7af9886409d76c16e/runelite-client/src/main/java/net/runelite/client/plugins/xptracker/XpInfoBox.java) uses [ProgressBar](https://github.com/runelite/runelite/blob/c68dcb073d8d86de15ce23d1cd7f44c8358050a7/runelite-client/src/main/java/net/runelite/client/ui/components/ProgressBar.java) to display the progress.

Since ProgressBar uses a BorderLayout it might not be possible to draw the indicators in that class.

Instead it might make more sense to place another component that draws the indicators on top of the ProgressBar.
I'm not an expert with swing, but [here is a stackoverflow answer on how to draw on top of other components](https://stackoverflow.com/a/15961969)

To get xp required for certain levels it would be possible to use `Experience.getXpForLevel(Integer)`
