### ISSUE TITLE
Graceful pieces in bank and examine have a grand exchange value.

### ISSUE THREAD

**Issue by Nazdro** [runelite/runelite#6867]
The graceful pieces have a grand exchange value through the Bank Value addon as well as when examining  them in bank or inventory. Can't rememberwhich addon has the examine price functionality.

RL Version: 1.5.3
OS revision: Rev 177

**Comment by raiyni** [comment]
That's intended.

**Comment by Nazdro** [comment]
Okay, I suppose? 
What value is used to determine their value? If it's mark -> amylase, then it's off by a bit:
Boots = 40 marks, 1 mark = 14,740gp => boots should show 589,600, but are showing 471,680, as of current GE evaluation.

**Comment by deathbeam** [comment]
Its based on sell price not buy price, you sell grace pieces for less marks than you bought them
