### ISSUE TITLE
Anti Aliasing does weird things when I'm on my actual PC

### ISSUE THREAD

**Issue by SakuraTheSky** [runelite/runelite#6873]
When activating AA in the GPU plugin, no matter which setting i put it to it freezes my screen and causes a weird repeating and glitched images repeating pattern when i rotate the camera.

To reproduce this bug you just need to enable the anti aliasing, and also rotate the camera 

Screenshot for refrence

![image](https://user-images.githubusercontent.com/38703528/49686337-f243e200-fac0-11e8-83d5-aa72661af82b.png)

Enviroment
 - OS: Windows 10
 - RuneLite version: 1.5.3
 - Launcher version: Unkown

I'll list a copy of my log as well.
[application.log](https://github.com/runelite/runelite/files/2659713/application.log)

**Comment by Twiglet1022** [comment]
Try this, it worked for me:

1. Right-click on your desktop and go to the Nvidia Control Panel.
2. In either the global settings or the application-specific settings for runelite, change Antialiasing mode from "Override any application setting" to either "Enhance the application setting" or "Application-controlled.
3. Restart your client.

**Comment by Twiglet1022** [comment]
It's under "Manage 3D settings"

**Comment by SakuraTheSky** [comment]
this fixed everything, thank you

**Comment by deathbeam** [comment]
Average users were not messing around with AA settings in their GPU control panel most likely and so for them it should work

**Comment by acshearer** [comment]
I experience a similiar issue however only on MSAA x16, x2,x4 and x8 work as expected.

Enviroment
- OS: Arch Linux 4.19.1-1-ck
- GPU: RX480
- Driver: AMDGPU 18.1.0-1
- RuneLite version: 1.5.5
- Launcher version: 1.6.1
- [glxinfo.txt](https://github.com/runelite/runelite/files/2719175/glxinfo.txt)

**Comment by deathbeam** [comment]
This should be fixed now, well, the option will do nothing as the GPU plugin checks for max supported AA
