### ISSUE TITLE
Max hitsplat plugin 

### ISSUE THREAD

**Issue by yarcanine** [runelite/runelite#6883]
Would it be possible to add a plugin that shows when you hit your maximum hit with your current weapon? Similar to pre eoc your hitsplat would be orange instead of red showing you hitting your max.

**Comment by forsco** [comment]
Maybe if we ever receive the hitsplat color update. Can't remember if it failed/passed the poll.

**Comment by scuttlegun** [comment]
That did pass (Content Poll 46, 11-Aug-2016) but it's never been fully implemented because of engine work they never got around to. I believe some preparatory work done for it is the reason clients stopped being able to get the precise current hp of your opponent

**Comment by LlemonDuck** [comment]
This can be viewed with either of the hub plugins [Max Hit](https://runelite.net/plugin-hub/show/maxhitplugin) or [DPS Calculator](https://runelite.net/plugin-hub/show/dps-calculator).

Jagex is also making more progress toward showing the orange hitsplat.
