### ISSUE TITLE
Change hotkey defaults using "Ctrl" to "Meta" for users on MacOS

### ISSUE THREAD

**Issue by weblue** [runelite/runelite#6884]
**Is your feature request related to a problem? Please describe.**
MacOS behavior dictates the "Meta" key be used in place of the "Ctrl" key in many commands where "Ctrl" is used comparably on Linux or Windows

**Describe the solution you'd like**
Change the client defaults for hotkeys to use "Meta" instead of "Ctrl" on MacOS. Nothing should change for existing users.

**Describe alternatives you've considered**
Ask users if they'd like to switch on next client start, if they're using MacOS.

**Comment by deathbeam** [comment]
Arent the hotkeys already configurable? Or idk what do you mean

**Comment by weblue** [comment]
This suggestion is specifically addressing the defaults being set by RL on first-time-run. Yes the settings can be changed, but imo this would make runelite follow macOS best practice without user intervention

**Comment by deathbeam** [comment]
Doing OS-specific configuration is very bad idea unless there is very good reason to do it (and this isnt) because the configuration is synced (and so, if you would just use meta for OSX on first run, it will simply not work at all on synced windows machine)

**Comment by weblue** [comment]
I had forgotten about hotkey syncing in the client. While non-trivial, it may be worth thinking on the issue as the CTRL key on Mac can be more awkward, but obviously this issue is in no way urgent.

**Comment by deathbeam** [comment]
Imo as long as it is configurable, its fine as it is now
