### ISSUE TITLE
Add the Fossil island Ancient Wyvern staircase to the agility plugin thing

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#6889]
![image](https://user-images.githubusercontent.com/34870401/49701371-e143bf80-fbeb-11e8-8aa2-68c962d302ea.png)
It's really hard to click on imo.

**Comment by LewisHolt** [comment]
Does it give agility xp when used?

If not, it shouldn't be added since only agility related things are allowed.

**Comment by JeljoGb** [comment]
Oh I didn't know that, I thought it was just for things that were hard to click on.

**Comment by Nightfirecat** [comment]
@LewisHolt There are plenty of shortcuts/obstacles that don't grant exp that we add to the agility highlighter.
