### ISSUE TITLE
Bank organizer plugin

### ISSUE THREAD

**Issue by sanderb93** [runelite/runelite#6896]
Hi Runelite Devs, 

First of all thanks for the amazing client!

I'm really having problems organizing my bank. Im just a bit of a messy person.
But as my bank grows it's getting more inconvenient.

I'm not sure what the possibilities are but maybe a sort bank option?

That sorts on specific filters, like maybe herbs, gems, armour, weapons or just sort by value.

Just thought about this and thought why not suggest it, I could not find another issue about it, Im not that familiar with github so sorry if there actually is one, if so could you link me?

Kind regards,

Sander

**Comment by deathbeam** [comment]
We cant really "sort" actual bank if that is what you mean. You can use tag tabs

**Comment by sanderb93** [comment]
> We cant really "sort" actual bank if that is what you mean. You can use tag tabs

Aha, yeah bank tanks require you to tag every item tho right? so that is still alot of work. If you didn't do it from the start. I was hoping the client could somehow check what item it is and maybe give the item a bank tag automatically(like herb or armour or something) and then you would be able to filter/sort.

Again just an idea, I'm not really experienced in programming so I have no idea if I am asking for something impossible. However if it's not possible I would be interested in hearing why.

Kind regards

**Comment by piksu** [comment]
As @sanderb93 said, sorting bank requires a lot of manual labor. I would actually suggest supporting the idea that the bank tags were a shareable commodity.

Lets say you've got a potentially common tab for "teleportation", where all runes and items offering teleports are listed. It would make sense to have this kind of tag template available and enable means to import this template of tab. Furthermore, lets say that you are interested in my custom tab, whatever it is. It would be great if I could share the tab to you and you could take it into use via import mechanism. What are your thoughts?

~piksu

**Comment by forsco** [comment]
We have this rolling on the discord server under #bank-tags. The gear setup also has an extensive list of import strings.

**Comment by deathbeam** [comment]
We added sharing for bank tags and also we have bank tags and so I don't think this feature request is valid anymore, as it do not provides any benefits over existing implementation, so closing
