### ISSUE TITLE
[Suggestion] Bank Value Tracker

### ISSUE THREAD

**Issue by SGlascott** [runelite/runelite#6898]
**Is your feature request related to a problem? Please describe.**
I am a senior computer science major and I am looking for a side project, so I started looking into my favorite game client RuneLite! I thought it might be cool to add some sort of metric to track the value of your bank over time and I wanted to gauge community interest.

**Describe the solution you'd like**
I think it would be fairly simple, I was looking into the code and think it would tie into the BankValue plugin. When enabled, there would be a map where the key is the date and the value would be the user's bank value that would update when they sign in(or out) each day.  This map would be saved to a file and be saved and loaded when the client is running. Then users would be able to track their bank's value over weekly, monthly, or yearly periods. This could be represented in numerous ways but I figure a percentage growth would be good for initial testing, they could also see the exact value of their bank that has been tracked each day in the form of a list.

**Additional context**
I would love to contribute to this plugin and would appreciate a mentor of sorts who is familiar with the platform to point me in the right direction as well as check my code quality. I think this would be a great learning experience!

Thank you,
Scott

**Comment by AverageHumanoid** [comment]
I'm not sure how accurate this would be for cases such as mine where it fluctuate greatly depending on what I'm wearing, what's in my inventory, Grand Exchange offers, Chambers of Xeric chest, etc at any given time.
