### ISSUE TITLE
Toggle to remove marks of grace/graceful/gold nuggets from bank value

### ISSUE THREAD

**Issue by MaxBartlett** [runelite/runelite#6899]
I'd like the option to toggle marks of grace/graceful/gold nuggets from being included in bank value. I don't think graceful is something most people would consider to include in their total bank value, and displaying it as such can be misleading.

**Comment by deathbeam** [comment]
This was intentionally done like this, and our bank value is liquify price, so it is correct. It is not trivial to toggle, and so it is best as is
