### ISSUE TITLE
[Suggestion] Gem Bag Overlay / Icons

### ISSUE THREAD

**Issue by AmazingJesus** [runelite/runelite#6905]
This can be done in 2 ways.
An option like Rune Pouch to show whats inside of the Gem Bags.
![](https://i.gyazo.com/de9fccf5811721762438355f6658d841.png)

Or a hover option like RS3
![](https://i.gyazo.com/6c1105072cd314a0d32e415eb98909f3.png)

Idk if its a lot of work, its a simple thing to have :)

**Comment by Nightfirecat** [comment]
I don't believe the client has any information on what gems exist within the gem bag, and it wouldn't be reliable to try and track when gems are added to it.

**Comment by AmazingJesus** [comment]
What if it updates when u check?

**Comment by raiyni** [comment]
then it's fairly useless because you already checked it to know what's in it

**Comment by AmazingJesus** [comment]
You telling me that this would be the only plugin on the client that you would need to check before it displays the correct information?

**Comment by deathbeam** [comment]
"correct" information, you would still need to track deposits/withdrawals from gem bag, and that sounds unreliable (same problem as with rune pouches)

**Comment by deathbeam** [comment]
Duplicate of #5133
