### ISSUE TITLE
XP Globe failed to disappear for extended period of time

### ISSUE THREAD

**Issue by AncientDawn** [runelite/runelite#6907]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
See title.

**To Reproduce**
- Bloodveld Task
- Manually bury Bone you received as a drop

**Expected behavior**
XP Globes fail to disappear for an extended period of time despite not gaining xp in the skill.

**Environment (please complete the following information):**
 - OS: Windows
 - RL version: 1.5.3
 - Launcher version: 1.6.0

**Comment by Twiglet1022** [comment]
Sounds like #6588 but that one is closed

**Comment by AncientDawn** [comment]
Adam told me it wasn't a known issue -- this only happened last night. So I'm not really sure. I haven't been able to reproduce it since however.

**Comment by Nightfirecat** [comment]
That was the same problem with the original issue; nobody was able to reproduce it.

**Comment by deathbeam** [comment]
I dont think this is actually an issue
