### ISSUE TITLE
Barrows brothers plugin's minimap feature adds yellow dot under player

### ISSUE THREAD

**Issue by Hubcapp** [runelite/runelite#6918]
Believe me, there is not an NPC under me lol. The yellow dot remains underneath the player's white square no matter where I walk.

<img src="https://i.imgur.com/lk9HHIh.png" />

Related to #6672

**Comment by deathbeam** [comment]
So if it is related to #6672, is it your pet?

**Comment by Hubcapp** [comment]
No. It is related to #6672 because in both cases, an entity that is not an NPC is being given a yellow dot. The fix for #6672, #6698, looks like they plan to fix it by  "Also adds a helper function in NPC called isPet, which returns true if an NPC is a pet." which would not fix this issue.

**Comment by deathbeam** [comment]
What is this entity then? I dont think I ever had that to happen, idk. More info would help. But fix for 6672 would fix this issue, based on what Adam replied there

**Comment by Hubcapp** [comment]
probably the fix for this is to make sure "client.getNpcs()" doesn't return the local player. but if there are side-effect bugs from doing that, then a similar fix to what was done in #6698 would fix #6918 too.

**Comment by deathbeam** [comment]
This was fixed

**Comment by Hubcapp** [comment]
No, it was not fixed with #7505. Players still get given yellow dots, including the local player. This issue is unresolved.

**Comment by deathbeam** [comment]
Oh I see
