### ISSUE TITLE
Rich Text in Notes

### ISSUE THREAD

**Issue by burntsoop** [runelite/runelite#6921]
**Is your feature request related to a problem? Please describe.**
It is not.

**Describe the solution you'd like**
More options to edit text in notes section such as bolding, indents, and more pages/tabs within the notes plugin.

**Describe alternatives you've considered**
Adding an edit pane, or allowing html tags/bb tags

**Additional context**
None

**Comment by deathbeam** [comment]
You can already do that, use e.g markdown. Otherwise notes are just plaintext and you should treat it like that
