### ISSUE TITLE
Some items not showing equipment stats

### ISSUE THREAD

**Issue by haakonrp** [runelite/runelite#6926]
Only tested a few items from the bank.

Not showing:
Volcanic/Frozen abyssal whip
Berserker ring (i)
Magic shortbow (i)
Ava's assembler

Seems to happen to some imbued equipment, and also items with different name like frozen abyssal whip etc.

**Comment by Hydrox6** [comment]
It seems to be untradeable items, as Fire Cape and Dragon Defender are also missing stats

**Comment by haakonrp** [comment]
Not all untradeables though, Archers/Seers ring (i) works

**Comment by Kamielvf** [comment]
Missing:
- dragon defender
- avernic defender
- primordial boots
- pegasian boots
- eternal boots
- infernal pickaxe (uncharged)
- volcanic abby whip
- fighter torso
- warrior ring (i)
- berserker ring (i)
- guthan helm (100)
- guthan spear (100)
- veracs helm (100)
- proselyte cuisse
- The following skillcapes: Construct. cape(t), Slayer cape(t), Crafting cape(t), Attack cape(t), Hitpoints cape(t), Fishing cape(t), Fletching cape(t), Herblore cape(t), Prayer cape(t), Thieving cape(t), Woodcut. cape(t)

**Comment by deathbeam** [comment]
As I am, and I will keep automatically generating this file when update happens, any addition to this should be fixed here: https://github.com/deathbeam/osrs-data otherwise it will be just removed from the file eventually again, or the file would need to be updated manually instead every time.

**Comment by deathbeam** [comment]
I fixed most of the items thanks to @raiyni . Closing, reopen for respective items/item types
