### ISSUE TITLE
Fix the ctrl+backspace discrepancies and the ctrl+w bugs.

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#6929]
Pressing ctrl+backspace in the text boxes in Runelite's sidetabs removes one word correctly
E.g.: "hello this is sentence" =(ctrl+backspace)> "hello this is "

But in game, it removes everything you've typed in the chat box. For some reason, ctrl+w does remove one word, but it also removes the leading space, and the "/" for clan chat text.

**Comment by deathbeam** [comment]
The behaviour in text boxes in sidebar is system dependant. As we have them configurable, we cant just use system-dependant defaults as that is not how our config system works

**Comment by Hubcapp** [comment]
II agree with Jeljo that more common defaults for deleting a word make sense. ctrl-w may be preferable to vim users and bash wizards, but most keyboard shortcut users will be familiar with ctrl-backspace from web browsers and graphical text editors like Word.

**Comment by deathbeam** [comment]
This was already discussed in discord when we implement this. The keybindings are configurable because people do not liked the defaults, so use plugin config.

**Comment by deathbeam** [comment]
Looks like they are not configurable, i thought they are, so reopening

**Comment by Psyda** [comment]
Can we get an update to the plugin? I'd give it a shot myself since it's very annoying repeatedly deleting my whole messages daily, but I'm very new to java and am just fumbling through.

**Comment by JeljoGb** [comment]
Sorry for reopening this but it fits here better than in a new issue.
Currently, ctrl backspace removes the last word, but also the space before the word. 

Imo it should remove the spaces after the word, and the word itself. This is how it works everywhere else I use it.
I tested it on linux as well, to see if this is not a windows issue, and there it also removes trailing spaces, and then the word. It also considers punctuation as "words", as in, removes only the spaces after the punctuation and the punctuation itself.

**Comment by Nightfirecat** [comment]
Re-opening so we can address the trailing space being removed. Punctuation being erased is very inconsistent across OSes and software, so we may not look at changing that behavior.

**Comment by JeljoGb** [comment]
That makes sense, it was just something I noticed on linux (kubuntu). Just tested it now and it also works on windows. But that's the least of my worries, I just hated having to add one space every time I ctrl backspaced.
