### ISSUE TITLE
Add "Swap talk-to with pickpocket" to Bandits

### ISSUE THREAD

**Issue by weblue** [runelite/runelite#6930]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add entries into the plugin settings for swapping talk-to and pickpocket on bandits.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
