### ISSUE TITLE
Messages do not appear in public chat

### ISSUE THREAD

**Issue by sugozu** [runelite/runelite#6933]
Windows
RuneLite version: 1.5.4
Launcher version: 1.6.0

When someone sends a message in public chat, I can see the message over their head, but there is nothing in the public chat or all other tabs. Works fine with official client and I checked filter isn't on.
Clan chat worked fine, as well as friends chat.

Tried disabling all plugins, but that didn't work.
Restarting the client worked, but the issue shouldn't happen in the first place.

**Comment by trimbe** [comment]
Can you try to replicate this on the vanilla client? This may be related to #6453, which is Jagex's bug.

**Comment by YTXZ** [comment]
Updated post with extra info, also this happened under 10 minutes of being logged in at an area with nobody talking for majority of time.
