### ISSUE TITLE
XP Progress Bar ignores Configure XP Drops settings

### ISSUE THREAD

**Issue by YTXZ** [runelite/runelite#6934]
![adfsdfasdf](https://user-images.githubusercontent.com/39009972/49971126-0dd24100-ff36-11e8-9ee3-93b2767eef6d.png)
An issue that somehow every single 3rd party client has managed to copy over.

**Comment by Nightfirecat** [comment]
The progress bar is one of the moveable widgets. Press <kbd>Alt</kbd> and click-and-drag it to whatever location you'd like, including the top-middle anchor point.
