### ISSUE TITLE
MSAA x16 broken on AMD GPU

### ISSUE THREAD

**Issue by GottaSlay** [runelite/runelite#6949]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Setting the AA value to MSAA x16 causes glitching.

**To Reproduce**
Set the AA value to MSAA x16

**Expected behavior**
Glitching

**Screenshots**
https://gyazo.com/75c2321e6b3ed1bd2370daed421f8384

**Environment (please complete the following information):**
 - Win 10
- RuneLite version: 1.5.4
 - Launcher version: 1.6.0
- GPU is an RX580 Nitro+ 8GB

Changing the setting from your GPU manufacturer's software to "Enhance application setting" does not work in this case like how it does with Nvidia cards.

**Comment by Kallu609** [comment]
RX480 Nitro+ 8GB and experiencing the same issue.

**Comment by GottaSlay** [comment]
Before driver update, all of the AA options used to work out of the box, apart from the MSAA x16 one, after driver update i also started to have that weird wireframe stuff and the AA options were broken altogether. However, I found out that if you manually set your Anti-aliasing mode to "Override Application settings" from Radeon Settings, then put the Anti-aliasing level to 8xEQ, you'll be able to set the in-game AA to x8, setting it to x16 will cause the same glitching as before driver update.

I haven't tried to see what different Anti-aliasing levels do and how they change the behavior as 8xEQ sort of works fine enough for me.

**Comment by Blastburn94** [comment]
As far as I'm aware (correct me if I'm wrong), no AMD GPUs support MSAA x16. The client should query what MSAA modes are supported.

**Comment by hsombini** [comment]
@Kallu609 stated that all anti-aliasing are broken on recent drivers, I can confirm this on latest driver 19.1.1, this should not be considered as fixed as @GottaSlay solution breaks the RuneLite GUI
