### ISSUE TITLE
Separate color assignments for friends' chats.

### ISSUE THREAD

**Issue by michaelcubed** [runelite/runelite#6950]
**Describe the solution you'd like**
Similar to adding notes to friends, we could edit the chat color of a friend. 

**Describe alternatives you've considered**
In the chat options, we could add a username and color.

**Additional context**
It is difficult to see if a different friend has messaged you which can lead to responding to the incorrect person at times. With different colored chats, this could be prevented.

**Comment by Vokuar** [comment]
we can do this with the chat color plugin if i remember correctly
under public friend username or private friend username
and there is one for transparent and default i made mine green

**Comment by Vokuar** [comment]
not all of the stuff you want but username color is doable atm

**Comment by raiyni** [comment]
This was added in the plugin hub.
