### ISSUE TITLE
[Suggestion] Public Chat setting automatically toggles when entering/leaving an area

### ISSUE THREAD

**Issue by MysticInfer** [runelite/runelite#6951]
Most people I know leave their Public Chat on _Hide_ when entering places like the Grand Exchange, Wintertodt, Blast furnace etc. I find myself always missing important stuff because I don't ever change it off of hide when leaving the GE.

It would be nice if there was a plugin to automatically change your Public Chat setting when entering certain areas, then changing back when leaving. A drop-down with pre-mapped areas would be good, and more can be added if suggested.

**Comment by deathbeam** [comment]
That would be faking input, so no
