### ISSUE TITLE
"Item Stats" plugin does not recognise Bottle of Wine as food

### ISSUE THREAD

**Issue by LavyLavender** [runelite/runelite#6957]
**Describe the bug**
The item stats plugin does not show me how much health the bottle of wine will restore and does not show how much attack I will loose. I understand it isn't super game breaking but it was quite annoying. this might be an issue with other food but the bottle of wine was the only one I saw

**To Reproduce**
1. Put mouse over Bottle of Wine with the item stats plugin enabled

**Expected behavior**
does not show how much health it will restore

**Screenshots**
![image](https://user-images.githubusercontent.com/28632931/50042046-13bf4380-0056-11e9-8623-c1d549876010.png)

**Environment**
 - OS: windows
 - RuneLite version: 1.5.4
 - Launcher version: 1.6.0

Sorry I don't really know how github works but this bug was annoying me

**Comment by Nightfirecat** [comment]
Can you confirm that, [per the wiki, it heals 14 hitpoints and has no other effects](https://oldschool.runescape.wiki/w/Bottle_of_wine)?

**Comment by LavyLavender** [comment]
> Can you confirm that, [per the wiki, it heals 14 hitpoints and has no other effects](https://oldschool.runescape.wiki/w/Bottle_of_wine)?

![image](https://user-images.githubusercontent.com/28632931/50045695-708b2000-008f-11e9-9c45-75b9ce43ea40.png)

it also takes away 3 attack levels

**Comment by Nightfirecat** [comment]
Ok, so just to be clear, it did heal 14hp as well?

**Comment by LavyLavender** [comment]
> Ok, so just to be clear, it did heal 14hp as well?

yes it heals 14 hp
