### ISSUE TITLE
No sound with low detail mode

### ISSUE THREAD

**Issue by Wolles007** [runelite/runelite#696]
Hey i've experiencing no sound in my Runelite Client yesterday and this very day, i've checked all my windows and ingame sound settings, and there are sounds when i'm using other clients... Please fix, or tell me how to fix it, can't seem to find a solution. Ps. i've tried reinstalling 3 times. Pps. i love this client please save me

**Comment by deathbeam** [comment]
Hmm, can you send logs from your home directory/.runelite/logs/ here? Maybe there is something wrong happening, it's really weird issue.

**Comment by deathbeam** [comment]
Also, what operating system are you using?

**Comment by deathbeam** [comment]
Any update? Seems like it is Java/sound device issue. Try the "fix" i posted in reply above.

**Comment by deathbeam** [comment]
Reopen if issue occurs again and previous mentioned solutions will not help.

**Comment by SkrillexAkaCraft** [comment]
got the same issue on my end,, Win8.1

tried all kind of suggestions none solved my issue

[logs.zip](https://github.com/runelite/runelite/files/1778067/logs.zip)

**Comment by deathbeam** [comment]
Reopening because at least from the limited informations we have it looks like there might be problem with installer version of RuneLite (as with .jar it looks like sound is working properly, but with installer version it stops working after some time). Can you report back here after few days of using the .jar @SkrillexAkaCraft to confirm that the .jar solved the issue, or if the issue appears in the .jar again then comment that here too please.

**Comment by SkrillexAkaCraft** [comment]
sure can will use the jar for 3-4 days before heading back to this issue

**Comment by simisai** [comment]
For me the issue was that I didn't have a sound scheme selected within Windows, After selecting one idle sounds were working again.
see: https://stackoverflow.com/questions/15441910/why-does-toolkit-getdefaulttoolkit-beep-not-work-in-windows

**Comment by SkrillexAkaCraft** [comment]
ok day 2: the jar still works, seems like users with windows 8 to 8.1 are affected by having no sounds

**Comment by Unmoon** [comment]
I managed to reproduce this with the installer:
- Download and install using the Windows installer
- Let installer launch the client (you will have sound)
- Restart the client (you will not have sound)
Windows 7

**Comment by Adam-** [comment]
Someone on discord says this is due to starting the client in low detail mode.
