### ISSUE TITLE
Minor bug for ground markets

### ISSUE THREAD

**Issue by GreasyLips** [runelite/runelite#6964]
The reset button on the plugin doesn't work resulting in your client always displaying all the tile markers you marked. 

**To Reproduce**
1. Go to ground markers plugin
2. Set a marker via shift+right click to mark a tile
3. Then try and reset them via the button in the plugin settings to no avail 
**Expected behavior**

All the marked tiles to disappear 

**Environment (please complete the following information):**
 - OS: Windows 10 
 - RuneLite version: Latest
 - Launcher version: [e.g 1.5.2]

**Comment by Nightfirecat** [comment]
This is already expected behavior; the reset button only resets configurable settings, not hidden settings. A "Clear all tiles" feature has been requested here: #1989
