### ISSUE TITLE
Skill Cape - Menu Entry Swapper

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#6971]
Currently skill capes are included in the Menu Entry Swapper plugin under "Teleport item". This is nice but I believe skill capes should have their own item in the plugin. Those that want to left click for everything can still enable both, but for those that just want their capes can have that instead.

I'm not sure if this is possible given how the plugin works, but it is something I'd very much like to see.

**Comment by deathbeam** [comment]
You can just disable teleport and use shift-click configuration

**Comment by Spedwards** [comment]
I'm already using the Shift-Click option for the "Tele to POH" on my construction cape, so I'm stuck with the same problem.
