### ISSUE TITLE
Add "Items Kept on Death" item examines to Examine plugin

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#6974]

**Comment by TheStonedTurtle** [comment]
Do you mean show if the item will be kept or lost on death via the examine options?

**Comment by Nightfirecat** [comment]
No, I mean if you examine the item, it doesn't show item price

**Comment by Nightfirecat** [comment]
Apparently the menu option for that interface is "Item:", not "Examine" :upside_down_face:
