### ISSUE TITLE
Item Stats - Broad Bolts Missing Ranged Strength

### ISSUE THREAD

**Issue by Demonslay335** [runelite/runelite#6975]
**Describe the bug**

For the new equipment stats feature of the Item Stats plugin, it appears to not see the Ranged Strength of "Broad bolts". This causes other bolts to show their full stat instead of relative such as when other bolts are equipped.

**To Reproduce**
- Hover mouse over item "Broad bolts" with Item Stats plugin enabled.
- Alternatively, equip broad bolts, and hover mouse over another range-related item (e.g. other bolts).

![image](https://user-images.githubusercontent.com/5551512/50050375-31c08e80-00be-11e9-8e29-89317a6e59b5.png)

Example 1:
Broad bolts equipped, hover over adamant bolts - shows +100, expected to not show since the stat is the same.

![image](https://user-images.githubusercontent.com/5551512/50050372-253c3600-00be-11e9-925f-55c3ce3f074e.png)

Example 2:
Broad bolts equipped, hover over runite bolts - shows +115, expected to show relative +15 like when other bolts are equipped.

![image](https://user-images.githubusercontent.com/5551512/50050385-9f6cba80-00be-11e9-801a-0bc95b5711e5.png)

**Environment**
OS: Windows 7 x64
RuneLite version: 1.5.4
Launcher version: 1.6.0

**Comment by jakebellotti** [comment]
The stats are missing from https://static.runelite.net/item/stats.min.json
