### ISSUE TITLE
Cannon Overlay Does Not Work In Mos Le'Harmless Caves

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#6976]
The cannon overlay does not appear when in the Mos Le'Harmless Caves. In addition, the cannonball counter next to the cannon timer will not count down from 30.

![Cannon image](https://i.imgur.com/5CO9xD2.png)

All my cannon related settings are turned on.

I am on Windows 10, RuneLite version 1.5.4, and Launcher version 1.6.0.

**Comment by deathbeam** [comment]
I am pretty sure you are just in wrong spot
