### ISSUE TITLE
Wiki Chat Command

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#6993]
Before I start, I understand this might not be possible, but it doesn't hurt to ask.

The idea would be to have a chat command for the OSRS wiki, in the format of `!wiki [page]`.

The text would then be displayed as `Wiki Page: [page]` and clicking to will open the wiki page in your browser, similar to how Jagex shares updates and their official stream.

Using the link, `https://oldschool.runescape.wiki/w/Special:Search?search=%s`, where `%s` is the query, you will be taken to the page if it exists, otherwise it will be a search page.

This feature would be very useful for quickly accessing the wiki and/or to help other players.

**Comment by deathbeam** [comment]
The URL itself would probably just be filtered, also I dont see how is this useful

**Comment by Spedwards** [comment]
@deathbeam Why would the link be filtered? It would be added by the client after the fact. All the game would actually see would be is `!wiki [page]`.

And I can see multiple uses for it. To quickly access a wiki page yourself, or to link a friend to a page would be the two most common ways I would use it.

**Comment by deathbeam** [comment]
You can just tell the friend name of the item, searching on wiki is simple

**Comment by deathbeam** [comment]
Also, other clients do not have this command, so it would be just spam for them, and as this is moderately useless (and the lookup solution that reasel was working on is better) closing
