### ISSUE TITLE
Toggle to display bank 'tab 0' value

### ISSUE THREAD

**Issue by TziOSRS** [runelite/runelite#6995]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

I don't know the value of the first section of my bank (the one at the top of your bank, in the tab with the infinity symbol) excluding tabs 1+

**Describe the solution you'd like**

Ability to right click on the bank value at the top of your bank to "display 'tab 0' value" or "hide 'tab 0' value". Ability for which value to display to be persistent/remembered upon closing bank/logging out.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

Ability to right click on the tab with the infinity symbol to 'view tab 0' (and display the value of this 'tab' at the top of the bank) or to 'view all items'. When in 'view tab 0' mode that tab could display an icon/number/roman numeral etc. Ability for mode to be persistent/remembered upon closing bank/logout. 

**Additional context**

Please discuss, maybe this idea could be improved.

**Comment by deathbeam** [comment]
Isnt this already a feature?

**Comment by deathbeam** [comment]
Imo this is already a feature so closing. You can disable bank plugin to disable prices

**Comment by TziOSRS** [comment]
> Imo this is already a feature so closing. You can disable bank plugin to disable prices

Maybe I didn't write very clearly, sorry, I know you can disable the bank prices, but I want a quick way of knowing the value of all the items in the first section of your bank - i.e everything that is not in tab 1 onwards. Right now the only way to do that is to mouseover each stack and add them up, or add up the values of tabs 1 onwards, then take away from total bank value. Or am I being dumb and missing something here?

**Comment by Spedwards** [comment]
As I previously stated, a lot of people, myself included, use that section as it's own tab, thus having it's value displayed is useful.

If you don't like it, you don't need to use it. There's no reason for this not to be implemented.

**Comment by deathbeam** [comment]
Well the fact that "tab 0" is not a thing and never was is good enough reason to not implement this feature?

**Comment by Spedwards** [comment]
It would be an easy implement. Next to the total bank value, include the sum of every bank tab subtracted from the bank's total value.

If this comment chain has proved anything, it's the people want it. If you don't want it, you simply don't have to use it.

**Comment by TziOSRS** [comment]
I just want a quick/easy way of seeing the value of the first section of your bank, I don't mind how it's implemented or whether you call it tab 0 or whatever you call it
