### ISSUE TITLE
Getter for GameObject array

### ISSUE THREAD

**Issue by BenjaminFaal** [runelite/runelite#7]
We need this if we want to make full featured plugins.

**Comment by Adam-** [comment]
Okay. If you could point out where that is, or perhaps send a PR exporting it, that would help.

**Comment by BenjaminFaal** [comment]
In the Client class one would expect just a getter like getPlayers and getNpcs

**Comment by Adam-** [comment]
Here is one array of game objects in Region: https://github.com/runelite/runelite/blob/master/runescape-client/src/main/java/Region.java#L105-L106 - Is this what you mean?

**Comment by BenjaminFaal** [comment]
Nice this should suffice, thanks very much.
