### ISSUE TITLE
Sulliuscep Mushroom plugin

### ISSUE THREAD

**Issue by freminik** [runelite/runelite#7011]
A plugin that could keep track of the rotation that the Sulliuscep Mushrooms go, there is a rotation that they follow and it would be nice for a sort of arrow pointing to them & highlighting them sort of like the agility plugin with the little box over the clickable areas.

It's really just a QOL, maybe add it to the woodcutting plugin that already exists? However, it should be expanded a little bit because cutting Sulliuscep Mushrooms isnt really as afk as doing regular woodcutting.

**Comment by deathbeam** [comment]
Duplicate of  #6476
