### ISSUE TITLE
Cannon Overlay Not Worknig

### ISSUE THREAD

**Issue by hkbertoson** [runelite/runelite#7020]
Cannon is not showing how many cannonballs i have left.
![2](https://user-images.githubusercontent.com/44106297/50227194-d23adb00-036a-11e9-8ce2-49cf18a59b00.PNG)

**Comment by basicDamen** [comment]
Have you tried picking it up and placing it back down? Or did you leave the area?
Do you have the option enabled? It works fine on my end, so it seems scenario based.

**Comment by hkbertoson** [comment]
It is working now. It must have just been that spot.
