### ISSUE TITLE
Notify on full inventory when woodcutting

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#7024]
Before the completion of Monkey Madness 2, wielding a greegree is required for cutting Teaks on Ape Atoll. This means the normal idle notifier for woodcutting does not work. To resolve this, add a notifier for when your inventory is full.

May overlap #547 and/or #3969.

**Comment by Nightfirecat** [comment]
This seems like a duplicate of #547 which you've linked? The only difference is that you've suggested one possible solution, which seems to be mostly a duplicate of #3969
