### ISSUE TITLE
In builds 1.5x and above after sometime the client will crash and become unresponsive.

### ISSUE THREAD

**Issue by IObviouslyDontExist** [runelite/runelite#7029]
**Describe the bug**

**To Reproduce**
1. Start runelite
2. Wait about 5-8 minutes even disabling all plugins
3. Crash
4. See behavior

**Expected behavior**
The client just freezes up and is in-recoverable without restarting Rune lite.

**Environment (please complete the following information):**
 - OS: Windows 10, Professional
 - RuneLite version: 1.5x - recent
 - Launcher version: v1.77

**Additional context**
Upon searching why, by building the client myself in debug mode; The stack trace is as followed.

Method: setTimestamp()

```
ERROR
2018-12-15 12:02:56 [Thread-5] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.AbstractMethodError: Method bw.setTimestamp(I)V is abstract
at bw.setTimestamp(bw.java)
at net.runelite.client.chat.ChatMessageManager.add(ChatMessageManager.java:567)
at java.lang.Iterable.forEach(Iterable.java:75)
at net.runelite.client.chat.ChatMessageManager.process(ChatMessageManager.java:546)
at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:171)
at client.methodDraw(client.java:1249)
at client.ar(client.java)
at ah.o(ah.java:356)
at ah.run(ah.java:310)
at java.lang.Thread.run(Thread.java:748)
```

**Why this happens**
This happens due to the timestamps being called and parsed incorrectly and so the client will report and fail and immediately crash. 

**How to fix this for now**
Going to the following files and simply commenting out timestamps, then rebuilding solves the issue and no freezes happen while the client runs accordingly.

#1
> Directory: runelite\runelite-client\src\main\java\net\runelite\client\chat\
> File: ChatMessageManager.java
> Function: private void add(QueuedMessage message)
> Line: 567
> Comment: line.setTimestamp(message.getTimestamp());

#2. 
> Directory: runelite\runelite-mixins\src\main\java\net\runelite\mixins
> File: RSMessageNodeMixin.java
> Function: RSMessageNodeMixin()
> Line: 59
> Comment: setMessage.setTimestamp(rl$timestamp);

#3. 
> Directory: runelite\runelite-mixins\src\main\java\net\runelite\mixins
> File: RSMessageNodeMixin.java
> Function: public void setMessage(int type, String name, String sender, String value)
> Line: 113
> Comment: setMessage.setTimestamp(rl$timestamp);

**Comment by Abextm** [comment]
1) That launcher version does not exist
2) that crash log is because you didn't build the client correctly. Try following the [Building guide](https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA).

**Comment by raiyni** [comment]
1. Timestamps don't exist on the live version if you are experiencing the freezing there. 
2. You need run maven
3. Your freezing sounds like it's characteristics of https://github.com/runelite/runelite/pull/6909
