### ISSUE TITLE
itemManager.search is not 100% accurate

### ISSUE THREAD

**Issue by 15987632** [runelite/runelite#7036]
The following three things are missing from it

Bronze hasta(p+)
Gilded magic wardrobe
Opulent table

the last two are flatpacks

To reproduce just search for any of these things in the GE plugin and they wont show up.

**Comment by Abextm** [comment]
Manually hitting the `/item/{id}/price` endpoint for one of these items added it to the results after the cache expired. I guess that means that the `ItemService::crawlPrices` either doesn't work, or has just randomly never hit these items.

**Comment by Abextm** [comment]
Fixed in a952ea3bae8217dd6d8061eb4d2a8ac041c76bb1
