### ISSUE TITLE
Clan Chat plugin randomly stops displaying ranks.

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#7038]
**Describe the bug**
Ranks will stop showing in CC, seemingly randomly.

**To Reproduce**
~~It seems to happen (sometimes) upon login/world hop and sometimes just randomly.~~ Also seems to happen after teleports. (Especially fairy rings)

**Expected behavior**
To display ranks consistently.

**Screenshots**
https://i.imgur.com/2Wl4S4T.png

Temporary fix: Disable then Re-Enable "Clan Chat" plugin.

**Comment by Adam-** [comment]
It might not show for messages added by the chat history plugin. Does it happen to normal messages?

**Comment by SomeZer0** [comment]
It happens to normal messages.

New messages after logging in/hopping.

Also sometimes it is working normally, then just stops (no logout/hopping)

**Comment by Adam-** [comment]
This might be related to #6933

**Comment by SomeZer0** [comment]
To clarify, once it stops showing the rank, it stops showing it for everyone, and will not re-enable unless I toggle off/on the Clan Chat plugin.

**Comment by ncx9** [comment]
Seems like upon bankstanding without interacting with client (other than typing in clan chat) the issue has stopped. Going try and replicate what I was doing to see if I can figure out what is causing it.

**Comment by SomeZer0** [comment]
It seems to happen pretty often when I teleport (especially with fairy rings)

In a fairly talkative cc.

**Comment by ncx9** [comment]
Can confirm, did not happen for 20 minutes at bank, took 1 fairy ring out of my poh, and clan chat immediately stopped showing ranks.

**Comment by ncx9** [comment]
Apologies for the spam, but in the last 20 minutes I have been able to replicate this issue 100% of the time. After taking any fairy ring, clan chat ranks stop displaying. 

Issue is fixed by turning clan chat plugin off and on again. Thank you.

**Comment by Cullen-Dubbs** [comment]
I concur, I have been able to replicate with all fairy rings.

Other teleporting methods seem more random

**Comment by dr-bing** [comment]
I seem to lose clan chat ranks after taking any fairy ring. Does not happen with other teleports. 

I have to reset plugin to fix. I am glad to see I am not only one having this issue.

**Comment by SomeZer0** [comment]
Last night I tried to replicate with fairy rings and I failed to replicate the issue.

Here's what I did:

1. Configure fairy ring

2. Manually spin the dials

3. Click teleport

Using this method, I did 20+ teleports, and my cc plug-in failed to break.

I wonder if it happens more reliably using a different method (clicking on list, or using search + clicking on list) I can test more when I get home.

**Comment by ncx9** [comment]
Interesting. Just tested myself:

Left click ring Last destination - works 10/10 times.
Left click ring Zanaris - works 10/10 times.
Manually configuring dials - broken 10/10 times.
Clicking off list - broken 10/10 times.

Spirit trees, spellbook teles, and jewelry teles do not break it for me. Only fairy rings.

**Comment by SomeZer0** [comment]
My left click option for rings is configure. Seems both of lot left click options work fine..

Maybe try changing what your left click option is, and see if it still breaks while using that method.

**Comment by ncx9** [comment]
Changed left click option with menu entry swapper - made no difference for me.

What I did figure out though is that:

1. It is not the actual teleportation that breaks it for me but the clicking 'configure' on the ring (regardless of left or right click). Once the ring configuration screen pops up, if I close out of it without actually teleporting, it will still break.

2. While doing nothing within the game, if I turn off ANY plugin, it will exhibit the same behavior and stop showing clan ranks. Turning that plugin back on does not fix it. Only resetting Clan Chat plugin fixes the issue.

**Comment by SomeZer0** [comment]
Do you have the fairy ring search option enabled?

Try toggling that option and see if it makes any difference while in the configure screen.

**Comment by ncx9** [comment]
So with the 'Open search automatically' turned off within the fairy ring plugin, the issue no longer occurs unless I manually use the fairy ring search function. So this is a nice fix for me as I can live without the search function. 

The issue still happens however when turning off any plugin.

Thanks for finding the temporary fix for me mate.

**Comment by SomeZer0** [comment]
I have "open search automatically" turned on, and the clan plugin does not break for me.. This is a very odd issue for sure.

I also turned off a random plugin a few times and my clan icons did not disappear. Dunno why it does that for you.

**Comment by SomeZer0** [comment]
I encountered the issue you're talking about.

Where just opening the search dialog or turning off a plugin broke the cc plugin 100% of the time..

Restarted my client and the issue went away. Not sure what causes it.

**Comment by tgeene** [comment]
This issue is still happening. Not sure if it is related to fairy ring as stated above, but is rather annoying.

**Comment by SomeZer0** [comment]
Can confirm that the issue still persists.

This issue seems to happen from any custom search dialog that RuneLite creates.

The issue does not happen 100% of the time for me, but when it happens it is always right after one of these dialogs is created.

I have noticed that it happens after the search dialog on the fairy rings is opened/closed, and also when setting a bank tag on an item.

I am playing on resizable with a transparent chat box and the 2005(? - whichever one is the oldest) game UI.

The CC ranks will still appear over other player's heads next to their name, but it stops showing in the chatbox. If this issue happens once, it will continue happening every single time that one of these search dialogs is created. A temporary 'fix' for this is to toggle off/on the clan chat plugin, but it must be done every single time after opening/closing one of these dialogs.

Sometimes restarting the client will fix the issue temporarily. However, the issue comes back after a while.

My guess is that we hide the CC ranks while creating the search dialog so there aren't random icons floating around the interface. But then for some reason the ranks might not get re-enabled once the dialog is closed.

**Comment by Aero56** [comment]
This completely stopped working for me now since recently.
None of the ranks are showing up in chat anymore now, no matter what. I can restart RuneLite or re-enable the plugin as much I want, doesnt work.

**Comment by Alexsuperfly** [comment]
there was a conversation a few days ago in discord where somebody said that recoloring the clan name with the chat color config is what seemed to cause this.  Can you confirm as well?

**Comment by Aero56** [comment]
> there was a conversation a few days ago in discord where somebody said that recoloring the clan name with the chat color config is what seemed to cause this. Can you confirm as well?

I can check, but how do I turn off the chat coloring plugin? If I'd press reset all my colors would be gone and I don't want that.

**Comment by Alexsuperfly** [comment]
unfortunately that is the only way to send any option back to default, and since its not a true plugin it doesnt have an on off switch

**Comment by Aero56** [comment]
> unfortunately that is the only way to send any option back to default, and since its not a true plugin it doesnt have an on off switch

Okay, no worries. I screenshotted my settings and reset it to default, the ranks are now showing up in chat. The ranks are shown in the clan chat's channel name and when I change the color of that, it breaks and they no longer show up.

**Comment by Alexsuperfly** [comment]
thanks for confirming that, minds better than mine would probably be able to fix it now that we know where its happening.

**Comment by Adam-** [comment]
We think this is fixed by #10492
