### ISSUE TITLE
Item Stats incorrectly states a +4 Prayer bonus for untrimmed skill capes

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#7048]
Only trimmed skill capes give a prayer bonus, so this is a mistake.

![Incorrect prayer bonus](https://i.imgur.com/gGpEW5h.png)
![Untrimmed skill cape stats](https://i.imgur.com/CrAUCNu.png)

As I don't have one, I cannot confirm, but I believe trimmed skill capes have a (t) following their name.

**Comment by bcowell** [comment]
Can confirm, the untrimmed construct. cape should have a +0 prayer bonus, but shows +4. 
Trimmed cape has a prayer bonus of +4.
Incorrect stats are coming from [static.runelite.net](https://github.com/runelite/static.runelite.net/blob/gh-pages/item/stats.json#L19440)
And it looks like a few other capes also are mislabelled. I can work on this.

**Comment by TorkelV** [comment]
duplicate #6936
