### ISSUE TITLE
Item Stats missing dragon defender and firecape

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#7051]
Currently, the Item Stats plugin won't show the stats for some items. I don't have a complete list, but it only shows the weight for the Dragon Defender and Fire Cape.

**Comment by Ririshi** [comment]
This seems to be the case for more items. In my experience, the only items affected are untradables such as those you named, as well as Ava's devices. This might just be a coincidence, though.

**Comment by kingoomieiii** [comment]
None of the Defenders have stats listed in the plugin.
