### ISSUE TITLE
Graceful has a GE average price

### ISSUE THREAD

**Issue by Monose** [runelite/runelite#7053]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

My Graceful is causing my bank wealth to increase by exactly 2,716,480

**To Reproduce**

**Expected behavior**

**Screenshots**

https://gyazo.com/6ad2ecce0d7ff5428aac9a7b93b29ef7

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Abextm** [comment]
This is because graceful can be converted to amylase and sold.
