### ISSUE TITLE
My nexus clips through the ceiling

### ISSUE THREAD

**Issue by SilverLugia1992** [runelite/runelite#7055]
I have my nexus room on the first floor of my POH, and if I tilt my camera downwards and towards the northeast, I can see my nexus clipping through the floor while in the room on the second floor above it. I tried recreating it in the vanilla client, and it doesn't do it.

![image](https://user-images.githubusercontent.com/2846116/50376320-3068f780-05d1-11e9-9710-555d86f46713.png)

**Comment by Nightfirecat** [comment]
Does this also happen on OSRS mobile?

**Comment by SilverLugia1992** [comment]
Forgot to check that, yeah it does

**Comment by Nightfirecat** [comment]
Runelite uses a very similar renderer to what Mobile does, so generally they should have similar behavior for strange rendering bugs like this.

**Comment by Adam-** [comment]
This happens on vanilla too. I don't want to try to fix it.

**Comment by SilverLugia1992** [comment]
So should I report it to jagex as a mobile bug then?

**Comment by Adam-** [comment]
I think this happens on vanilla too? So it isn't mobile specific.

**Comment by SilverLugia1992** [comment]
But it doesn't, I just checked a second time.

**Comment by Adam-** [comment]
Does it happen with GPU mode off on RL?
