### ISSUE TITLE
Jad Prayer Switch Indicator 

### ISSUE THREAD

**Issue by RubyStarsUniverse** [runelite/runelite#7057]
When in the fight caves, one of the largest issues I find if figuring out when to prayer switch for jad. Is there any possibly of this being implemented in runelite in the future?

**Comment by j2wick** [comment]
See: https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

The feature had been implemented but was removed due to making the Jad fight too trivial. I suggest watching some youtube guides on Jad (using sounds in-game helps you distinguish which sound is which attack).
