### ISSUE TITLE
Premade banktabs for quest items

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#7059]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to have a list with all quests which you can click to create a banktab. After you create the banktab you see every item you have and need for the quest.

**Describe alternatives you've considered**
/
**Additional context**
/

**Comment by Hydrox6** [comment]
There's no need for this to be a dedicated feature with tag importing, as someone could make a bank tag for every quest, if they really wanted to, and post it in the #banktags channel of the Discord.

**Comment by Dradeth93** [comment]
>           There's no need for this to be a dedicated feature with tag importing, as someone could make a bank tag for every quest, if they really wanted to, and post it in the #banktags channel of the Discord.

Well, it would be nice for people that don't use discord to have a list with all the banktags for each quest.

**Comment by Hydrox6** [comment]
You don't need an account or a program to access the Discord, even if you don't use Discord it's incredibly simple to go to the invite link in the client, give a random name, and peruse the bank tags channel in the comfort of your browser.

**Comment by deathbeam** [comment]
We could do it in similar way as clue? e.g show required items for current quest.

**Comment by raiyni** [comment]
@Mitchell-Kovacs This is a candidate for your plugin

**Comment by ThatGamerBlue** [comment]
> @Mitchell-Kovacs This is a candidate for your plugin

@MitchBarnett

**Comment by raiyni** [comment]
Quest helper does this
