### ISSUE TITLE
Mipmapping for GPU Plugin

### ISSUE THREAD

**Issue by AustinGarrettR** [runelite/runelite#7062]
Textures in RS look very poor when far away. Mip mapping would solve this issue. It's also very low overhead, as you're rendering smaller textures for farther away textures.
Example of the effects of mip mapping textures. 

![image](https://user-images.githubusercontent.com/42952632/50381874-39001300-064f-11e9-922f-0e75f38a95fc.png)

**Comment by Adam-** [comment]
this was added a few years ago in 24cfac14fa66a5a7af89e718c42d61452143b5fa
