### ISSUE TITLE
Add ability to see on the mini-map, same level combat players, one level below and one level above, with a different customized color dots.

### ISSUE THREAD

**Issue by newcomer9087** [runelite/runelite#7072]
Hello, I have a suggestion and I think it might be something really useful and easy to implement.
Add an option to have the ability to see on the mini-map, same level combat players, one level below and one level above, with a different customized color dots. very useful for F2p and P2P pking. (Find same combat levels players or one below or above to fight really easily.)

**Comment by zlshames** [comment]
I am going to give this a shot

**Comment by zlshames** [comment]
Here is what I've been able to do so far:

- [x] Create config for highlighting players close in combat (option, color, and threshold)
- [x] Code for performing said highlighting (on scene, menu, and names on minimap)
- [ ] Code for highlighting player dot on minimap

**Comment by zlshames** [comment]
I am going to hold off development of this until it gets approved by someone else. Many people do not like the idea of a PVP helper.

**Comment by newcomer9087** [comment]
Hey Zach thanks for doing it, I really don’t understand why people call this and tag it as a PVP helper, I really don’t think this will give you an andvantage on a fight, the reason I thought of this was because it would really save time **finding** you a fight not that it will help you win a fight, instead of searching around for some time to find a same combat level player to ask for a fight.
Anyways are you able to share the files with me so I can add it to my runelite plugins?

**Comment by newcomer9087** [comment]
Make it work only on level 1-2-3 wilderness non multi combat only.

**Comment by raiyni** [comment]
You can still scout that...

**Comment by zlshames** [comment]
The way I see it (as a person who doesn't really do PvP), it's more of a safety system for players who don't want to get PK'd. Though, I can see how it can be used as a scouting plugin. And if it can be used for something in the grey area, even if it's not its main purpose, then maybe it's not a good idea to have it in the client

**Comment by newcomer9087** [comment]
you don’t need to scout in level 1-2-3 wildy non multi area, I feel like the runelite comminuty has taken a fear out of even stuff that are called PvP.

**Comment by newcomer9087** [comment]
Zach are you able to share me the files?

**Comment by zlshames** [comment]
> Zach are you able to share me the files?

If you know how to compile it yourself, here are the files: [plugins/playerindicators](https://github.com/zlshames/runelite/tree/plugin/highlight-near-combat-level/runelite-client/src/main/java/net/runelite/client/plugins/playerindicators)

**Comment by Adam-** [comment]
I don't want to add any features which alters PVP this much.
