### ISSUE TITLE
Add webhooks to loot tracker

### ISSUE THREAD

**Issue by hoozuni** [runelite/runelite#7077]
**Is your feature request related to a problem? Please describe.**
No problem mainly an **ADDON** to the loot tracker.

**Describe the solution you'd like**
An API added to the Loot Tracker portion and being able to hook it up to discord, so if you were to hit an item over 5m and in the discord they have runelite drops enabled it'll send a message.

**Describe alternatives you've considered**
I've seen something similar done with this but it was in WoW other than that just adding the API and such would be

**Comment by LlemonDuck** [comment]
This can be done with any of the following hub plugins:
* https://runelite.net/plugin-hub/show/discord-loot-logger
* https://runelite.net/plugin-hub/show/discord-rare-drop-notificater
* https://runelite.net/plugin-hub/show/better-discord-loot-logger
