### ISSUE TITLE
[chatcommands] Add shorthands for Chambers of Xeric Challenge Mode

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#7078]
Currently, to get the kc for Challenge Mode, users have to type `!kc Chambers of Xeric:Challenge`

**Comment by TorkelV** [comment]
What shorthands do you propose?

**Comment by Usernamerino** [comment]
I noticed this too after I did a few CM raids and decided to add a few shorter versions 
https://github.com/runelite/runelite/pull/7242

**Comment by deathbeam** [comment]
Fixed in #7242
