### ISSUE TITLE
[Item stats] Missing Yak-hide armour (top and legs)

### ISSUE THREAD

**Issue by RAGwe** [runelite/runelite#7081]
The Yak-hide armour (top and legs) are missing from https://static.runelite.net/item/stats.min.json

Be aware that both of these items have the same name which would create 2 json objects using the same keyname.

https://oldschool.runescape.wiki/w/Yak-hide_armour_(legs)
https://oldschool.runescape.wiki/w/Yak-hide_armour_(top)

**Comment by zlshames** [comment]
I'll do this. Seems pretty quick and easy.

**Comment by Hydrox6** [comment]
@zlshames Please don't do editing the item stats json file, as that will get overwritten when the scraper is next run. Instead, fix the scraper to work with those items 

https://github.com/deathbeam/osrs-data

**Comment by zlshames** [comment]
> @zlshames Please don't do editing the item stats json file, as that will get overwritten when the scraper is next run. Instead, fix the scraper to work with those items
> 
> https://github.com/deathbeam/osrs-data

That's why I deleted my comment ☹️
