### ISSUE TITLE
Ground Items - show Low Alch value too

### ISSUE THREAD

**Issue by Grandclosing** [runelite/runelite#7083]
Hi guys, just started using RuneLite today - loads to configure and do still, really enjoying it. 

For Ironmen and Ultimate Ironmen who can't trade or use the Grand Exchange, we're often stuck with selling items to general stores. It'd be nice to see the low-alch value of ground items so we know how much we could possibly get for them.

**Comment by deathbeam** [comment]
Low alchemy is simply 60% of High Alchemy value, what is 60 % of the sale value. You can just use simple math to convert these values. Also noone should ever use Low Alchemy and GE and HA value are important values to show, rest are not so its up to user to make use of existing presented data.

**Comment by Grandclosing** [comment]
@deathbeam Ironmen accounts don't always have the option to high-alch items, and we're often left with just the option of selling items to general stores, or the dangerous bandit camp store in the wilderness (which buys for high-alch prices). 

Selling to general store (low alch) prices is common for ironmen accounts, so it ought to be added in to RuneLite so we don't need to do unnecessary calculating. That's the point of RuneLite - quality of life enhancements so players don't need to do unnecessary work and break out of the immersion of the game. I don't see this as a difficult or monumental enhancement for the amount of benefit to literally every single ironman account.

**Comment by 15987632** [comment]
> @deathbeam Ironmen accounts don't always have the option to high-alch items, and we're often left with just the option of selling items to general stores, or the dangerous bandit camp store in the wilderness (which buys for high-alch prices).
> 
> Selling to general store (low alch) prices is common for ironmen accounts, so it ought to be added in to RuneLite so we don't need to do unnecessary calculating. That's the point of RuneLite - quality of life enhancements so players don't need to do unnecessary work and break out of the immersion of the game. I don't see this as a difficult or monumental enhancement for the amount of benefit to literally every single ironman account.

Just sell it to west ardy gen store, high alch price and safe
