### ISSUE TITLE
General Store sell price

### ISSUE THREAD

**Issue by Grandclosing** [runelite/runelite#7084]
Hi guys, 

Another suggestion to help out Ironmen accounts - it'd be nice if the sale value of items in your inventory could be seen when interacting with a general store. Either on hover or right-click. 

The displayed value would update accordingly as you sold the item to the general store, so you always know how much the general store is buying your items for. 
See: http://oldschoolrunescape.wikia.com/wiki/General_store#Sell_prices

**Comment by deathbeam** [comment]
It's fixed value, so just multiply it by w/e the difference is
