### ISSUE TITLE
Add the ability to show a bigger Run indicator

### ISSUE THREAD

**Issue by remigo** [runelite/runelite#7085]
This is just a personal thing I'd like to see implemented, don't be afraid to turn me down. 
But during herbiboar you have to be very focused on your run energy and using stamina potions.
That means focusing on a super tiny part of the screen, which can be annoying.

[mockup I made very very fast, just to give you an Idea what I'd like to see](https://i.imgur.com/UYhEmOI.png)

**Comment by deathbeam** [comment]
You can f.e move the minimap around to be closer to your inventory with ALT? Or to where are you looking

**Comment by Hydrox6** [comment]
You can't move the minimap in fixed mode @deathbeam

**Comment by deathbeam** [comment]
So?

**Comment by deathbeam** [comment]
Well thee are only 2 sides of inventory so I dont see where?

**Comment by Gamer1120** [comment]
Oh, right. I use resizable, so both bars are on the left of the inventory. That is why I thought it would work.

**Comment by Nightfirecat** [comment]
Run energy is now one of the options to be displayed in the Status Bars plugin.
