### ISSUE TITLE
Boost plugin breaks when fighting stat draining npcs

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#7087]
**Describe the bug**
When fighting some npcs that reduce stats (karamel in nmz/galvek from ds2) the boost plugin disappears

**To Reproduce**
Go to nmz or something and fight any npc that reduces your stats and the plugin dissapears

**Screenshots**

https://i.imgur.com/gjdgj6L.png

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS] Windows 10
 - RuneLite version: [e.g 1.4.6] 
 - Launcher version: [e.g 1.5.2]

**Additional context**
Also note that rebooting the client does fix it, but id rather not have to do that everytime

[client_2018-12-27.5.log](https://github.com/runelite/runelite/files/2712194/client_2018-12-27.5.log)

**Comment by Adam-** [comment]
Where is the overlay positioned at when this happens?
