### ISSUE TITLE
Differentiate farming patches on world map

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#7091]
It is currently unclear which farming patch does what on the minimap. It would be useful to know that the patch below is a Bush patch for example. This could be added in the tooltip or the icon could be changed.
![image](https://user-images.githubusercontent.com/9074448/50494618-b3041380-0a24-11e9-854b-35bdfcd3746d.png)

**Comment by TorkelV** [comment]
Working on this now 👍 

![farming_patch](https://user-images.githubusercontent.com/16988960/50541864-00ac8780-0baf-11e9-9d58-14a5ee2d02a5.png)
