### ISSUE TITLE
[loottracker] Armadylian & Bandosian guards are not tracked

### ISSUE THREAD

**Issue by Enriath** [runelite/runelite#7093]
The monsters in question appear in Elite Coordinate clues. 

The reason that the loot doesn't appear is likely because it is slightly delayed.

Also affects the "Only show loot" option for the Ground Items plugin

**Comment by Nightfirecat** [comment]
I suppose this would also mean that the loot tracker wouldn't track loot from these NPCs?

**Comment by Hydrox6** [comment]
Loot tracker does not track the loot from these NPCs, correct

**Comment by Felanbird** [comment]
This was fixed at some point
