### ISSUE TITLE
Add a sidebar plugin to scan friendslist for RSJustice match

### ISSUE THREAD

**Issue by day2406** [runelite/runelite#7097]
I don't think the use of third-party websites will be that bad, considering RL already uses a crystalmathlabs 'scan and update' process.

I think, keeping in mind RS integrity, it would benefit everyone if you could press a button to scan RSJustice for matches of anyone on your friendslist, so then they can promptly be deleted and/or shamed.

This would probably make less people scam/fk people over, because who wants to be friends with a scammer?

**Comment by Nightfirecat** [comment]
Duplicate of #3828
