### ISSUE TITLE
Add a left click pickpocket option for the bandits in Pollnivneach

### ISSUE THREAD

**Issue by Pikamander2** [runelite/runelite#7099]
Similar to HAM members, the bandits in Pollnivneach have a "talk" option that prevents you from pickpocketing them with a single left click.

Can we add a "Pickpocket on bandits" option to the Menu Entry Swapper?

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
