### ISSUE TITLE
Add more features to raids helper plugin

### ISSUE THREAD

**Issue by winterdaze-rs** [runelite/runelite#710]
- Blacklisting and highlighting rotations: e.g. Blacklisting FCPCC-PSCSF Rotation
- Blacklisting rooms in certain positions: e.g. blacklisting rooms that dont drop seeds as being the first combat room
- Option to toggle showing list of all rooms instead of only combat/puzzle
- Add a highlight feature for rooms by name similar to existing blacklist feature

**Comment by Kamielvf** [comment]
To add to this, people have requested a whitelist for boss rotations
