### ISSUE TITLE
Runelite Not Opening at All. 

### ISSUE THREAD

**Issue by mumbomination** [runelite/runelite#7101]
Today, Runelite for me is not opening, which was strange, because my computer ran it just fine, without any problems yesterday. I opened my shortcut to Runelite, where I expected it to open the client. At first, when I opened it, it was at 0% for a few seconds, and then it closed. The Task Manager showed that Runelite was running in the background, but there was no app. I looked at Runelite's Wiki to see the common solutions, and first I tried to redownload Runelite, as I first downloaded back in April. I downloaded the 64 bit Windows version on the front page runelite.net. However, when I tried opening it now, here is what happens:

-My mouse signifies that something is loading with the blue spiral.

-It stops, and nothing happens. No background process of Runelite, and the bar with 0% didn't even appear.

I tried a number of things with Runelite, including deleting jagexcache, deleting repository, but the 
problem remains the same. My firewall allows Runelite through, and my internet connection is mostly fine. 

The version of my OSRS launcher is 1.2.7, and it works fine. The current Runelite version I downloaded is 1.5.5. 

My computer has a processor Intel (R) Core(TM) i7-6700HQ CPU @ 2.60 GHz 

I have 16.0 GB of RAM

And the system type is 64-bit, x64 based processor. 

The error and exception that appears in my logs is this: 2018-12-29 09:37:00 [RuneLite] ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.net.SocketTimeoutException: Read timed out

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client try this. But that looks like you cant access OSRS? maybe its blocked for you.

**Comment by mumbomination** [comment]
Like I said, regular OSRS works fine for me and I've already looked through troubleshooting.
