### ISSUE TITLE
Three Agility Obstacles Not Highlighted

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#7107]
During the Making Friends with My Arms quest, there are a series of obstacles to get past, the first few are highlighted, but the last three are not.

They should be added for completion's sake, since the first half is already there.

![Obstacles](https://i.imgur.com/NNHbNYP.png)

**Comment by hjdarnel** [comment]
Happy to add this. Anyone know where these obstacles are named? I see these lines, but I don't know where the constants come from. https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java#L34-L237

**Comment by Honestidade** [comment]
> 
> 
> Happy to add this. Anyone know where these obstacles are named? I see these lines, but I don't know where the constants come from. https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/agility/Obstacles.java#L34-L237

TheStonedTurtleYesterday at 11:47 PM
they come from the * imports
import static net.runelite.api.NullObjectID.*;
import static net.runelite.api.ObjectID.*;

TheStonedTurtleYesterday at 11:54 PM
i figured theyd be reading this chat
if not that's their fault

Discord is nice for quick responses in the future.
