### ISSUE TITLE
ESC to close the side bar

### ISSUE THREAD

**Issue by Error64** [runelite/runelite#7110]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
When for instance looking up a player, the side bar opens and you have to manually drag your mouse over and close the side bar. Since the side bar gains focus, it would be nice to just click ESC to close it again. Would be convenient.

**Describe alternatives you've considered**
Not sure if there are alternatives to this.

**Additional context**
None.

**Comment by deathbeam** [comment]
We can't do this in reasonable way because we would have to inject input listener to every custom field in sidebar
