### ISSUE TITLE
Waterbirth Island Client Rendering Issue

### ISSUE THREAD

**Issue by 14manj01** [runelite/runelite#7113]
Hello, 

The client seems to freeze when traveling to water-birth island. All the plugins and side menu work, however the actual Runescape game GUI portion of the client freezes. I tried to isolate the issue with GPU rendering plugin although having it enabled and disabled have the same effect. The official RS client has no issue with this area. 

With the following system
8700k
RTX 2080
16GB DDR4

**Comment by Cstock5** [comment]
After testing on Discord, we have deduced that issue is a RuneScape (and not RuneLite) issue.
