### ISSUE TITLE
Add a map waypoint feature

### ISSUE THREAD

**Issue by robinwithes** [runelite/runelite#7116]
A way-point system would be a really good feature to have especially for new players in my opinion.
It would work the same way that it works in RS3 and you already have a lot of the tools necessary for it; for example how the clue scroll plugin guides you towards where you need to dig.

I don't see any downsides to this idea except the time someone has to spend making it.

**Comment by deathbeam** [comment]
I think this is duplicate of https://github.com/runelite/runelite/issues/4496?

**Comment by robinwithes** [comment]
> 
> 
> I think this is duplicate of #4496?

Yeah you're right, did not find that one while searching.
