### ISSUE TITLE
NPC Indicator persisting after npc's death

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#7117]
![Example](https://i.imgur.com/AqpzZZE.png)

I don't know what caused this or how to reproduce, but while killing Chompy birds, which I have tagged, I ran into this. I killed and plucked a bird during a lag spike, and the indicator persisted.

**Comment by deathbeam** [comment]
I think this should be solved by @Adam- s change that ensured spawn/despawn events happen in order
