### ISSUE TITLE
Add tile Label option

### ISSUE THREAD

**Issue by MushuEE** [runelite/runelite#7120]
It would be great to be able to add labels to tiles for rotational information. Obvious one is labeling the Zulrah tiles with the position #s. Or label a tile in a row 'Multi' to remind yourself that it is multi beyond that location. Or Label the ground at EVERY bank 'Bring Spade'

**Comment by deathbeam** [comment]
I think #3395 solves this just fine?

**Comment by MushuEE** [comment]
@deathbeam great thank you, I will track it
