### ISSUE TITLE
Birdhouse timer finishes too early

### ISSUE THREAD

**Issue by LolRiTTeR** [runelite/runelite#7121]
**Describe the bug**
When the birdhouses are shown as ready, they actually aren't. I still have to wait a couple of minutes to dismantle them.
(I've tested this a couple of times already, happened every time)

**To Reproduce**
1. Plant (mahogany) birdhouse
2. Put seeds in
3. Wait til timer shows "Done"
4. Try to dismantle them, a text will apear telling you it's not ready yet

**Expected behavior**
Timer should say Done when they're actually done.

**Environment**
- OS: Windows 10 Pro x64
- RuneLite version: 1.5.5
- Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
This sounds like a duplicate of #2491. Timers are always somewhat inacccurate, and there's not really anything we can do to be more accurate.

**Comment by LolRiTTeR** [comment]
Thanks for the fast response.

I thought the time it takes was a fixed value, but apparently it isn't. Just found this post where it says "average time": http://services.runescape.com/m=news/dev-blog-fossil-island?oldschool=1

I guess i'll just add up 5 more minutes myself then :)


- LolRiTTeR
