### ISSUE TITLE
Special Attack Counter doesn't show up for 200m exp

### ISSUE THREAD

**Issue by purebtw** [runelite/runelite#7125]
![counter](https://user-images.githubusercontent.com/43530666/50565947-c4a72d00-0d3c-11e9-92a9-69b2e21542a3.png)

I have tried changing different settings, logging out multiple times and even reinstalling runelite. Nothing seems to work.

**Comment by deathbeam** [comment]
Dont you just have it moved somewhere? I am pretty sure the special attack counter still works

**Comment by purebtw** [comment]
Where could I possibly have moved it? If so, is there a way to reset it's position or something?

**Comment by purebtw** [comment]
ok I just found out that it's working on my alt but not main, any idea why? my other infoboxes like slayer task and different timers are working, just not spec counter.

**Comment by Nightfirecat** [comment]
I suppose we might be able to fix this if we hook into the fake exp drop script? Maybe not though, I haven't considered the edge cases for that much...

**Comment by Adam-** [comment]
@purebtw are you available to test a fix for this?

**Comment by Adam-** [comment]
fixed in e12d0bd23bdda7ebb73b6f9686d1e7b0bee2c29e
