### ISSUE TITLE
Runelite crashes when starting

### ISSUE THREAD

**Issue by bassix6** [runelite/runelite#7126]
Hi all,

Everytime I try to open Runelite i get a BSOD with an APC_Index_Mismatch error. This occured after I did a fresh install of Windows 7. All my drivers are updated, so I really wouldn't know what is the issue. Maybe important to mention, the regular client of OSRS also crashes. Hope one of you can help me!

**Comment by deathbeam** [comment]
Well if regular client is crashing for you too then the issue must be on your side, and nothing we can really solve
