### ISSUE TITLE
RuneWatch lookup

### ISSUE THREAD

**Issue by farhan1666** [runelite/runelite#7128]
**Is your feature request related to a problem? Please describe.**
As a member of staff in the largest discord of OSRS raiding (WeDoRaids) I have witnessed many people sneak into raids hosted in the discord and continue to scam items as people are too lazy to check the discords ban list as well as use the bots provided in the discord, this leads to people scamming millions of gp, playing on peoples laziness

**Describe the solution you'd like**
It would be nice if the client could look up players in your cc against the RuneWatch database and flag any members that show up by changing the colour of their name or having a message in chat

**Describe alternatives you've considered**
An alternative solution which I am not sure if would be simpler to implement is to have a sidebar for this plugin that allows you to individually look up players by clicking on their name in the sidebar, where names would be retrieved from the cc

**Comment by deathbeam** [comment]
We don't really want to depend on 3rd party service that is flagging people as "bad", that seems like very dangerous thing to rely on, and I believe we discussed this already before.

**Comment by RuneWatch** [comment]
We have refactored our case system and are now able to support this feature.
Here's a case list you can use: https://www.runewatch.com/api/cases/list
If you would like to query a single rsn please let us know via twitter @RuneWatch or dm Will osrs#0480 on Discord.

(I do not wish to re-open an issue/request for this, so pick it up if you'd like to move forward with it)
