### ISSUE TITLE
2 games in 1 client

### ISSUE THREAD

**Issue by EDUAaron** [runelite/runelite#7130]
**Describe the solution you'd like**
Being able to control 2 RS Profiles, like having 2 clients open, so you can do RC and anything else without having to open and switch client.

**Describe alternatives you've considered**
Opening 2 clients.

**Additional context**
The layout look like either of these
![aglu85s](https://user-images.githubusercontent.com/24701673/50568709-e6f57680-0d4d-11e9-9a5a-2206cf210caa.jpg)
![aglu8ss](https://user-images.githubusercontent.com/24701673/50568728-3176f300-0d4e-11e9-9748-e44c3a0ed312.jpg)

**Comment by Spedwards** [comment]
Or you can open two clients and resize them to be side-by-side?

**Comment by Abextm** [comment]
Just open 2 clients

**Comment by EDUAaron** [comment]
> 
> 
> Or you can open two clients and resize them to be side-by-side?

Which doesn't actually work too well considering you need two clients and most of the time the other one gets in the way because of the stupid Runelite client bar..

**Comment by deathbeam** [comment]
Change your resolution, use window manager that will handle that for you, possibilities are endless

**Comment by EDUAaron** [comment]
> 
> 
> Change your resolution, use window manager that will handle that for you, possibilities are endless

You can't use Windows Manager to make the clients the same size like you can with every other app.

**Comment by Cstock5** [comment]
Disable "Enable custom window chrome" in the Runelite settings, and then you can use the windows manager like any other app.
