### ISSUE TITLE
Fishing Icons displayed twice

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#7133]
![Doubled Icons](https://i.imgur.com/ETUfl23.png)

Fishing icons are getting displayed twice. Not sure what's causing this, it's being displayed on fishing spots I am not fishing at as well as ones that I am fishing at.

It seems to last up until my inventory is full, at which point it fixes itself.

**Comment by Nightfirecat** [comment]
Those are tiles where two fishing spots exist at the same location, it is expected behavior.

**Comment by Spedwards** [comment]
Oh, didn't realise that was even a thing. Should two icons be displayed then if it's the same type of fishing spot then? Kind of redundant to show multiple.

**Comment by Nightfirecat** [comment]
Duplicate of #1392
