### ISSUE TITLE
Loot Tracker saved loot not loading full 1024 kills

### ISSUE THREAD

**Issue by Honestidade** [runelite/runelite#7134]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The loot tracker plugin loads the last 1024 items worth of data from the database instead of the last 1024 kills, resulting in only showing 500-700 kills depending on how many items were in each kill.

**To Reproduce**
1. Amass 600-800 kills of npc's that drop bones+another item regularly.
2. Check loot tracker, note # of kills and gp.
3. Exit and reload client.
4. Check loot tracker, the kills\gp will not match up.

**Expected behavior**
Up to 1024 KILLS are meant to be loaded from the database and put on the loot tracker.

**Screenshots**
From discord: https://streamable.com/1iztj

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.6 (pulled new files on 12/30/2018)
 - Launcher version: 1.5.6?

**Comment by TheStonedTurtle** [comment]
I'm not a MySQL expert but I believe updating the `SELECT_LOOT_QUERY` to something like this should fix the issue.

```
SELECT id,time,type,eventId,itemId,itemQuantity FROM 
	(SELECT * FROM kills WHERE accountId = :accountId ORDER BY TIME DESC LIMIT :limit) as killsq
	JOIN drops ON drops.killId = killsq.id;
```

**Comment by dekvall** [comment]
The number has been increased in #10590
