### ISSUE TITLE
ADD DESCRIPTION TO COORDINATES CLUE - MEDIUMS

### ISSUE THREAD

**Issue by MedPeppa** [runelite/runelite#7135]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i have to open the map every time when doing a lot of clues you waste a lot of time [...]

**Describe the solution you'd like**
Add description to coordinates map instead of https://imgur.com/a/SQGcdV4
**Describe alternatives you've considered**
ADD THIS - the list is not mine made by kelvino(list is public for everyone) but is complete and very accurate whit very good descriptions for each cord map+i consider those descriptions usefull only for medium clues beacause everyone is speedrunning meds for money nowdays
05.20S, 04.28E / Feldip Hills
01.35S, 07.28E / North of Hazelmere's house
00.05S, 01.13E / West of Tree Gnome Village
01.18S, 14.15E / North East Karamja
03.07S, 03.41W / South West of Castle Wars
00.31S, 17.43E / North of Mudskipper point
07.05N, 30.56E / Morytania Swamp
14.20N, 30.45W / South of Chasm of Fire
09.48N, 17.39E / Ice Mountain
12.28N, 34.37E / Fenkenstrain's Castle garden
00.30N, 24.16E / Lumbridge Swamp
00.20S, 23.15E / South of Water Alter in Lumbridge Swamp
00.18S, 09.28E / South of Brimhaven dungeon
01.26N, 08.01E / Moss Giant Island, West of Brimhaven
04.00S, 12.46E / Tai Bwo Wannai mine
03.35S, 13.35E / East of Tai Bwo Wannai
06.41N, 27.15E / West of Digsite Library
11.33N, 02.24W / South of the Falconer, near Eagle's Peak
09.35N, 01.50W / North of Terrorbird pen, Gnome Stronghold
02.48N, 22.30E / West of H.A.M hideout
05.43N, 23.05E / Lumbridge cow pen
00.13S, 13.58E / West of Banana Plantation on Karamja
04.13N, 12.45E / Crandor Island
11.41N, 14.58E / Burthorpe pub garden
10.45N, 04.31E / By Coal Trucks, North West of Ranging Guild
06.58N, 21.16E / North East of Draynor Manor
08.33N, 01.39W / Terrorbird pen, Gnome Strongold
11.05N, 00.45W / Grand Tree Swamp
11.03N, 31.20E / South of Morytania Slayer Tower, Outside gate area
11.18N, 30.54E / South of Morytania Slayer Tower
14.54N, 9.13E / North West of the Golden Apple Tree
06.31N, 01.46W / West of Outpost
0.243S, 33.26E / South of Uzer
22.30N, 03.01E / North of Miscellania teleport
02.50N, 06.20E / South of South Ardougne bank
15.22N, 07.31E / By the cabbage and onions
09.33N, 02.15E / Before the Waterfall entrance, South Barbarian Outpost
07.33N, 15.00E / Lady of the Lake in Taverly
08.11S, 04.48E / East of red chinchompas

**Comment by Nightfirecat** [comment]
Are you requesting the addition of the descriptions? Because the locations themselves are already parsed and marked on the world map currently.

**Comment by MedPeppa** [comment]
yes i know the locations are marked on the map but if you have the description you don t have to use the map.What i want to say is if you do 20mediums/h and you have to open the map everytime for cord clues is frustrating cuz it takes a lot of time i know it sounds stupid but this is usefull for a lot of people that are speedrunning meds

**Comment by AverageHumanoid** [comment]
You don't have to open the map every time. After about 6000 medium clues I've memorized every step so doing clues now is pretty effortless as I can just set my brain to autopilot mode while focusing mostly on other activities.

**Comment by Spedwards** [comment]
@AverageHumanoid Just because you have memorised them doesn't mean anyone else has. I would personally love this feature as it saves time having to open up the map. As with everything, if you don't like it, you don't have to use it.

**Comment by AverageHumanoid** [comment]
I would describe my memory as average at best so I believe anyone could memorize the steps if they a dedicated clue hunter. In the meantime I've seen people paste coordinates descriptions into the notes section for convenient reference such as https://i.imgur.com/sUU2jSr.png

**Comment by MedPeppa** [comment]
> I would describe my memory as average at best so I believe anyone could memorize the steps if they a dedicated clue hunter. In the meantime I've seen people paste coordinates descriptions into the notes section for convenient reference such as https://i.imgur.com/sUU2jSr.png

but why paste them there and search for them when you could have them in the left box wtf do you try to prove?ok you are smart i am stupid but still you can`t say this feature is not helpful

**Comment by unmrshl** [comment]
OP is correct in that CoordinateClue is implemented differently. Where AnagramClue keeps a static instance for each clue, CoordinateClue converts the coordinates to a WorldPoint and creates a new instance. 

Is the added bonus of having location worth changing that?

**Comment by deathbeam** [comment]
Its still probably very simple to implement, just create separate Map<Coord, Description> in coord clue and use it when building overlay for it.
