### ISSUE TITLE
Graphical issues caused by premultiplied alpha pull

### ISSUE THREAD

**Issue by ffsidk** [runelite/runelite#7137]
**Describe the bug**
Graphical issues with gpu plugin on with the latest master release where premultiplied alpha was pulled. Things like transparent chatbox and inventory transparency will be discolored.

Pull mentioned:
https://github.com/runelite/runelite/pull/7090

**To Reproduce**
1. Enable transparent inventory in osrs settings in resizable
2. Turn gpu plugin on
3. See graphical errors

**Screenshots**
https://i.imgur.com/fv6rwdn.gifv

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.6
 - Running straight off Intellij

**Comment by Adam-** [comment]
@Abextm please look at this.

**Comment by Abextm** [comment]
You need to rerun maven. See !linkerror in discord
