### ISSUE TITLE
Disable "lookup" option on player right click

### ISSUE THREAD

**Issue by odxs** [runelite/runelite#714]
There is currently no option in the settings to disable the hiscores right click lookup function.

**Comment by SomeoneWithAnInternetConnection** [comment]
If you don't want hiscore lookup stuff at all (no sidebar, no right click), the next release (which should go live on thursday) will correctly remove the option from the right click menus, thanks to ae1eaef6

**Comment by odxs** [comment]
Ah.... Thank you

**Comment by Adam-** [comment]
Fixed in 07addf681a4af276f8bcf979b3103e2a5f2a6894
