### ISSUE TITLE
Add scaling support for high DPI monitors

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#715]
This is similar to, but not quite the same as, #615. We've had a number of folks stop by the discord because they're having issues with everything being tiny as a result of their incredibly high resolution monitors. It looks like we may need to mess with the `dpiAware` setting. Unfortunately it sounds like java 8 [has a bug](https://bugs.openjdk.java.net/browse/JDK-8080153), forcing dpiAware to always be true :(

There are some potentially useful stackoverlfow posts about this [here](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display) and [here](https://stackoverflow.com/questions/30555401/java-disable-dpi-aware-not-working)

**Comment by deathbeam** [comment]
Looks like the best solution for this is upgrade the packr distribution to use Java 9 as it is supposed to be fixed there. Other solutions are just plain ugly and bad unfortunately :/

**Comment by Adam-** [comment]
Until a solution for this is implemented we have a workaround on the wiki: https://github.com/runelite/runelite/wiki/DPI-scaling-on-Windows
