### ISSUE TITLE
Menu Entry Swapper - Tears of Guthix

### ISSUE THREAD

**Issue by Spedwards** [runelite/runelite#7150]
Simple addition, add an option to make Story the left-click option. The only two times you want to talk to Juna is for the Tears of Guthix and Another Slice of H.A.M. quests.

![Current options](https://i.imgur.com/EqaT5df.png)

**Comment by Nightfirecat** [comment]
This is a niche feature that is best suited for the plugin hub, and is currently covered by the Menu swapper extented plugin there. See runelite/plugin-hub#42
