### ISSUE TITLE
OSRS Client rendering bug

### ISSUE THREAD

**Issue by brycegallion** [runelite/runelite#7163]
Running Ubuntu 18.04.

I've downloaded the jar file, and am running the client with the following command:
       'java -jar /path/Runelite.jar'

The view of the actual osrs client is not rendering correctly.
At normal size, a single square about 100px x 100px is replicated across the screen.
Any resizing renders it black.

![image](https://user-images.githubusercontent.com/28766123/50623433-200b2380-0ed3-11e9-9033-48650864f64a.png)

**Comment by deathbeam** [comment]
Graphical artifacts? Try disabling hardware acceleration: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by brycegallion** [comment]
Holy crap man, thank you so much.

Sorry!
