### ISSUE TITLE
Allow WASD Camera movement while shift is enabled

### ISSUE THREAD

**Issue by iBlazit** [runelite/runelite#7165]
The WASD feature is amazing, but when using sticky keys to make it easier to drop items/just having it be more useful to have enabled in general, I am unable to use the awesome WASD camera movement and have to rely on the mouse-wheel instead

I have no idea how coding works but this would be very useful as I wouldn't have to keep turning on and off sticky keys which is somewhat rough considering I can't remap keys on my keyboard.

So yeah, being able to move camera with WASD while shift is enabled, if anyone can make this happen I'd be forever grateful

**Comment by deathbeam** [comment]
Idk why is this not working with shift in first place so seems like a bug?

**Comment by Keith-Cancel** [comment]
Well that pull request fixes this issue. Pretty straight forward.
