### ISSUE TITLE
GPU plugin experience orb pixelation and inventory brightness

### ISSUE THREAD

**Issue by eexxaa** [runelite/runelite#7169]
**Describe the bug**
Pixelation and brightness increase on GPU plugin

**To Reproduce**
1. Go to GPU plugin
2. Turn it On / Off while experience orbs are enabled
3. Experience orbs pixelate and inventory brightens

**Expected behavior**
No changes.

**Screenshots**
GIF on enabling and disabling GPU plugin, including experience orb pixelation:
https://i.imgur.com/oeaA2JR.gifv

Inventory with GPU enabled
https://i.imgur.com/MlwEnCu.png

Inventory with GPU disabled
https://i.imgur.com/0w8uyvx.png

**Comment by deathbeam** [comment]
Looks like also the XP tracker is not alphaing anymore there?

**Comment by eexxaa** [comment]
Just to add to this. the issue extends to the experience tracker, Information text box (Such as clue information) attack style infobox and boost overlay.

**Comment by Abextm** [comment]
You need to rerun maven. See `!linkerror` in discord.
