### ISSUE TITLE
xptracker: hunter immediate markers are almost invisible

### ISSUE THREAD

**Issue by devLotto** [runelite/runelite#7170]
https://twitter.com/Bearistdk/status/1080853514115375106

![](https://i.imgur.com/PaX7dQv.png)

**Comment by deathbeam** [comment]
White sounds like bad solution because text is white, but otherwise yeah it's kind of invisibile, lol

**Comment by JakeBCR** [comment]
![screenshot_3](https://user-images.githubusercontent.com/39069587/50648411-6181ea00-0f38-11e9-8644-5e63b0d08cbe.png)
Your right white isn't the best, how about black like the background? Here is a mock up I think works well.

**Comment by JAnken123** [comment]
Yes sure. I can do it. However I don’t think black is that nice. How about checking the color difference of each skill color to the background and just use darker until it’s enough of a difference percentually? Might be good in case this happens with other skills. It’s atleast what my intuition tells me.
