### ISSUE TITLE
Screenshot plugin showing mostly black screen, no UI

### ISSUE THREAD

**Issue by dsbrause** [runelite/runelite#7171]
**Describe the bug**
When I click the screenshot button, the resulting screenshot in the screenshots folder is broken, mostly black, and has no UI in it.

**To Reproduce**
1. Launch Runelite
2. Log in
3. Click screenshot button on the top bar

**Expected behavior**
Screenshots to not be broken

**Screenshots**
https://imgur.com/a/52iYZnl

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.6
 - Launcher version: 1.6.0

**Additional context**
Client log: https://pastebin.com/DuecYsDK

**Comment by deathbeam** [comment]
Fixed in https://github.com/runelite/runelite/commit/8e5da844b6c4db28be47778ab1264a969101d2c7

**Comment by herewegothen** [comment]
I'm having the same issue.
