### ISSUE TITLE
virtual levels

### ISSUE THREAD

**Issue by norskaaa** [runelite/runelite#7173]
any chance we can have the virtual levels have an option for the skills to not looked drained? 

Currently my slayer virtual level is 101 and it thus displays as 99/101 and it would look a lot cleaner if it could have a toggle to set it to 101/101.
what we currently have: https://i.imgur.com/G9ZhQ56.png
pref: https://i.imgur.com/vDGs3zc.png

**Comment by Adam-** [comment]
This makes it ambiguous when you are boosted.

**Comment by deathbeam** [comment]
As the virtual level is doing nothing, and stats on left side is actually what is used as requirement in-game and for combat/skill boosting, this would be just confusing for everyone.
