### ISSUE TITLE
Untradeable Bank value toggle

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#7178]
Add a toggle to show whether or not to include untradeables in bank value.

Sometimes i just want to know how much a tab is worth if i sell it and usually I don't want to get rid of my untradeables

**Comment by deathbeam** [comment]
It's intentionally unified, see the original PR for more context

**Comment by Stickaplex** [comment]
Know the number by chance?

**Comment by deathbeam** [comment]
Because it's integrated in ItemManager and used in consistent way everywhere
