### ISSUE TITLE
Lock monsters in Loot Tracker to prevent reset

### ISSUE THREAD

**Issue by verknaller** [runelite/runelite#7180]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to clear my entire loot tracker EXCEPT a single boss or monster. 
This way I could keep the Loot Tracker clean but still keep track of long term grinds spread across multiple days.

**Describe the solution you'd like**
I would like to be able to 'lock' certain tracked monsters in the Loot Tracker plugin which would not reset if I do a 'Reset All'.
This could perhaps be implemented like so with a toggle lock icon and in the context menu: 
![image](https://user-images.githubusercontent.com/18063446/50667536-0bee2180-0fba-11e9-9b84-cfd9c1c370e2.png)

**Comment by deathbeam** [comment]
You can just go to detailed view for specific monster and reset everything there with 1 press, it's good enough.

**Comment by verknaller** [comment]
Perhaps I should have explained my scenario more clearly:
Right now I want to track all of my Saradomin Godwars Dungeon loot. I do various things in between these kills. This is a long term tracking goal of mine.  

As you can see in the attached screenshot there is random junk tracking like Penance creatures and a Man, perhaps some slayer monsters too. I want to easily clear out these junk trackers with a single action. "Reset All" is implemented but this would clear my current record of Saradomin God Wars Dungeon loot. 

My requested feature would allow you to lock certain grouped monsters, which would not be reset whenever you use the "Reset All" function.

![image](https://user-images.githubusercontent.com/18063446/50667829-92573300-0fbb-11e9-976e-d45b7ac657be.png)

In this example I have locked: Commander Zilyana, Bree, Starlight and Growler. Whenever I would press "Reset All" only these monsters would get reset/removed from the Loot Tracker: Penance Fighter, Penance Ranger, Man.

**Comment by verknaller** [comment]
Could you perhaps have another look at this with the added explanation? @deathbeam

**Comment by deathbeam** [comment]
Imo it's simple enough to just press reset all on each different type of monster and clear it like that
