### ISSUE TITLE
GPU Plugin Client Freeze (While Underground?)

### ISSUE THREAD

**Issue by SarahLovesDoug** [runelite/runelite#7185]
I have checked with all the issues of similar nature to this, but my issue seems to be a bit different.

If I have the GPU Plugin on at any point in time, and then I go into a barrows hill where the crypts are, my client will freeze. I have went through all of the steps in the previous issues, and in the gpu information section, hardware acceleration is off, and I am using the latest GPU drivers.

Have the GPU plugin on, (Not even draw distance changed) everything working normal.
Dig into barrows hill, and client freezes.

I am on the latest version of runelite.
I have Windows 7
A Radeon HD 7770
and 6 GB of RAM with a FX 4300.

I couldn't find any logs that fit the client crashing what so ever.

**Comment by SarahLovesDoug** [comment]
Alright this has happened to me again when I tried to turn the gpu plugin on, and I went to travel via the ogre boat in RFD during Skrach Uglogwee's part, I have found an error log. 
[hs_err_pid3160.log](https://github.com/runelite/runelite/files/2799474/hs_err_pid3160.log)

**Comment by yanikore** [comment]
I also have crashes in specific instances and maps. I'm currently experiencing it in the Pinball random event instance. After switching to my dev build it does not crash anymore, but outputs the following: https://pastebin.com/raw/8EZtiiTJ

**Comment by edward789121** [comment]
i get the gpu crash when i click on something.

**Comment by ypperlig** [comment]
The GPU plugin freezes the game for me, but only when ram usage is quite high (usually around 90%).
When this happened I was loading a server on Rust which tends to consume a lot of memory.

Stack trace:
```
GLDebugMessageHandler: GLDebugEvent[ id 0x0
	type Error
	severity High: dangerous undefined behavior
	source GL API
	msg Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
(pid=18768 java.exe 64bit)
	when 1561924480324
	source 4.5 (Core profile, arb, debug, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 4.5.0 NVIDIA 417.35 - hash 0x5e639036]
GLDebugMessageHandler: GLDebugEvent[ id 0x505
	type Error
	severity High: dangerous undefined behavior
	source GL API
	msg GL_OUT_OF_MEMORY error generated. Failed to allocate memory for buffer data.
	when 1561924480325
	source 4.5 (Core profile, arb, debug, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 4.5.0 NVIDIA 417.35 - hash 0x5e639036]
2019-06-30 21:54:40 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: GL-Error 0x505 while creating mutable storage for target 0x8892 -> buffer 11 of size 13485648 with data null
	at jogamp.opengl.GLBufferObjectTracker.createBufferStorage(GLBufferObjectTracker.java:176)
	at jogamp.opengl.gl4.GL4bcImpl.glBufferData(GL4bcImpl.java:40258)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:905)
	at ba.sm(ba.java:1341)
	at ba.g(ba.java)
	at ba.run(ba.java:374)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the current RuneLite release.
