### ISSUE TITLE
RuneLite loot tracker for different timeframes.

### ISSUE THREAD

**Issue by KiwyRS** [runelite/runelite#7188]
I've run into an issue with the RuneLite loot tracker. I've been wanting to track daily kills and now that you've made this new features I'd also like to track weekly kills. 

A solution to this would be to create two seperate loot trackers, one for how long the session is running for and one permanent one.

Another option is to make us able to select a timeframe for how long we want to track the loot, and when to stop tracking it.

**Comment by deathbeam** [comment]
Your data are already persisted, just portion of them is loaded on startup. Full display will be eventually on website and not in client. And 2 separate loot tracker are definitely not an option. If you want, open up issue on website repo for adding loot tracker display there.
