### ISSUE TITLE
Improve Time-to-goal visibility in xp tracker

### ISSUE THREAD

**Issue by EJ-K** [runelite/runelite#7193]
**Is your feature request related to a problem? Please describe.**
Visibility of time-to-goal is currently hidden behind hovering the XpInfoBox - this information should be available "at a glance". 
An option should be added to make this one of the 4 default labels displayed.

**Describe the solution you'd like**
Add an option which would add time-to-goal as one of the default labels displayed in the XpInfoBox.
This should be disabled by default.

I believe the "Actions" display is the most suitable to replace if the feature is enabled.

Option:
![idea64_2019-01-04_23-34-37](https://user-images.githubusercontent.com/28347320/50716389-52568580-1079-11e9-9308-4e904672a68c.png)

Implementation:
![java_2019-01-04_23-34-02](https://user-images.githubusercontent.com/28347320/50716365-3ce15b80-1079-11e9-93c3-461cc1e983b0.png)

**Comment by Numteg** [comment]
Would really like this as well, but I would rather want the option to 'add' Time Left not 'replace'.

**Comment by Hydrox6** [comment]
This has been possible since 3cb2f68725c1e33b1f130f067032b9dc56137a41
