### ISSUE TITLE
Add distinctions to hard to differentiate sprites, such as herbs, herb seeds

### ISSUE THREAD

**Issue by barlakopofai** [runelite/runelite#7201]
The herbs in this game are all confusingly identical to each other. So just add a little thing on the sprites.
![image](https://user-images.githubusercontent.com/46401702/50726178-5913e580-10d7-11e9-9501-9700cdb82fee.png)

**Comment by zlshames** [comment]
I think this is a good idea. Maybe instead of roman numerals, just the first 2 letters of the herb name?

**Comment by Hydrox6** [comment]
Annoyingly, you need to use 3 letters for Tarromin, Toadflax, and Torstol

I've already got this done with Seeds, but it only works in the inventory. I'll try to find a way to have it work everywhere
![](https://thumbs.gfycat.com/MixedSharpBobwhite-size_restricted.gif)
(The gif is old, before I made Tarromin TAR, Toadflax TOA, and Torstol TOR)

**Comment by barlakopofai** [comment]
I liked mine a little better because I have a much easier time sorting items by their level rather than their name, but for the sake of distinguishing them, yes letters are better. Or maybe do both and have it as an option.

**Comment by Hydrox6** [comment]
Toadflax is actually just 1 word @barlakopofai

**Comment by barlakopofai** [comment]
A. That's semantics, it's clearly the words Toad and Flax put together.
2. I made this thread, why would you @me

**Comment by Hydrox6** [comment]
Toadflax is still its name, not Toad Flax

**Comment by Spedwards** [comment]
Aside from arguing over "toad ?flax", I think having an option to swap between tier and their name would be ideal.
