### ISSUE TITLE
Cooking in Hosidius kitchen

### ISSUE THREAD

**Issue by x-fusion** [runelite/runelite#7207]
**Describe the bug**
Cooking karambwans in Hosidius kitchen doesnt track how much of karambwans cooked, only burnt

**To Reproduce**
1. Go to Hosidius kitchen
2. Click on Clay oven to cook karabwan

**Expected behavior**
Cooked karabwans are not tracked, only burnt ones

**Screenshots**

**Environment (please complete the following information):**
 - OS: WINDOWS
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Hydrox6** [comment]
Support for Karambwans was added in #7096, and will be in the client next Thursday
