### ISSUE TITLE
Add a third Ground Item list for notify only

### ISSUE THREAD

**Issue by Ailuue** [runelite/runelite#7217]
**Is your feature request related to a problem? Please describe.**

I have a list of items I want highlighted, but are Uncommon drops (like valuable runes), and I don't want to be notified every time these drop. However, I DO want to be notified when high-value items drop.

**Describe the solution you'd like**

Add another list box specifically for items you'd like to receive notification on when they drop.

**Describe alternatives you've considered**

Currently, I haven't found an alternative.

**Additional context**

I don't think any are needed.

**Comment by deathbeam** [comment]
You can use chat notifier with in-game valuable item drop setting, this has really no place in ground items

**Comment by Ailuue** [comment]
Except something like a totem isn't "valuable" but I want to know when it drops if I'm looking away while AFKing hellhounds...

**Comment by Spedwards** [comment]
You can still use the same feature. Just use "Untradeable" instead of "Valuable".
