### ISSUE TITLE
Screen Markers Sections

### ISSUE THREAD

**Issue by EatSleepSlay** [runelite/runelite#7218]
I know this might be a simple and odd request but I think this will be useful.

Would it be possible to make screen marker sections in the screen marker tab.

So if I make a section 1 for fetching, 1 for blast furnace etc... I for one have multiple markers for my skills and  having sections will be helpful.

{x} = the toggle for all of the subsequent markers inside that single section. 

[blast furnace]    {x}
   - marker 
   - marker
   - marker

[blast furnace]    {x}
   - marker 
   - marker
   - marker

[blast furnace]    {x}
   - marker 
   - marker
   - marker

**Comment by Spedwards** [comment]
Duplicate of #3205.
