### ISSUE TITLE
Add Tablet Creation animation to Idle Notifier

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#7220]
The animation ID seems to be 4067, though I've only tested with House Tablets

Good first contribution for someone 👍

**Comment by Luv2C0de** [comment]
Hey I can try to tackle this. Is there more info on how to find where this file is located?

**Comment by deathbeam** [comment]
You need to use Developer Tools with Players option enabled and then create tablet and watch what is behind A:, then add it to AnimationID and then use it in IdleNotifierPlugin

**Comment by ermalsh** [comment]
Confirmed: 3652 for Animation ID when clicking Lantern, and 4067 for Animation ID when creating a tablet.
I will work on this, should have it done soon.

**Comment by ermalsh** [comment]
Is this what you're looking for? :)
![08a5c95ed5638dc77c495388a1ce1c8b](https://user-images.githubusercontent.com/19981656/51203742-d279b800-18cf-11e9-84d9-e92fbef1c864.jpg)
