### ISSUE TITLE
Runelite won't maximize on 2nd monitor

### ISSUE THREAD

**Issue by XBULLETX** [runelite/runelite#7221]
When trying to maximize a second RuneLite client on my second monitor, it will never go full screen, only partially.

On my main monitor it works fine and maximizes more than 1 client (with 1 in the background) so I'm not sure why it won't work on my second?

This is how it looks when supposedly "maximized". I've had a look around other problems but they only seem to have a small bar or something, not a huge chunk of screen like I'm experiencing.

I've tried disabled the chrome window option, makes no difference. I've tried using the screen size option in game as well but still no luck.

![runelite problem](https://user-images.githubusercontent.com/46458795/50789942-76060f80-12b5-11e9-9083-e7b62b63336f.png)

**Comment by raiyni** [comment]
duplicate https://github.com/runelite/runelite/issues/4778

**Comment by XBULLETX** [comment]
That doesn't give any advice on what I'm supposed to do?

**Comment by deathbeam** [comment]
Becuase it's unresolved @XBULLETX and it's bug

**Comment by scapinAbout** [comment]
I found that setting my monitor to be the main display in the "display settings" fixed the issue. (By monitor I mean not my laptop screen.)
