### ISSUE TITLE
When switching between spotify and runelite i am experiencing crashes

### ISSUE THREAD

**Issue by slazum** [runelite/runelite#7223]
When swapping between runelite and spotify i experience lag in runelite and sometimes it crashes. This does not happen when using chrome etc.

I am currently running runelite with hardware acceleration off, as this was making my side menu slow and also causing crashes.

**To Reproduce**
1. Open spotify
2. Open runelite
3. Login to runescape
4. swap between runelite and spotify
5. increase speed of swaps to cause full crash and shutdown of runelite

**Expected behavior**
To not lag or crash

**Environment (please complete the following information):**
 - OS: Windows

**Comment by Spedwards** [comment]
Based on your steps to reproduce, it sounds like you're intentionally swapping back and forth between Spotify and RuneLite. Solution is to stop doing that.

Either way, this is likely a hardware or external software issue as RuneLite has no connection to Spotify and vice versa.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration try this
