### ISSUE TITLE
Setting the default timer time.

### ISSUE THREAD

**Issue by Qualphey** [runelite/runelite#7224]
I use timers to track runite rock respawns on different worlds. I start the timer right after the rock gets depleted and label it with the world number. This way i know exactly when to hop to a certain world.

Now the problem is that each new timer is set to 5 minutes, and I want it to be 6 or 12 minutes by default so I wouldn't have to change it each time when I add it. So could you please add a feature, to change the default time of a new timer?

That shouldn't be too difficult to implement and it would help a lot of people out.

Thanks!

**Comment by jakewilson** [comment]
working on this
