### ISSUE TITLE
Optimal Quest List with account

### ISSUE THREAD

**Issue by WildsIM** [runelite/runelite#7230]
http://oldschoolrunescape.wikia.com/wiki/Optimal_quest_guide

Wiki has an awesome quest list that is in order of difficulty/distance from previous quest. Perfect for new accounts. Id love a plugin, that shows you this list in order (maybe have a few different sorting options, 1 being to cross out all quests that give defense xp or something) but as you complete, they turn green or cross out. Then quests you are missing levels for are red and show you what you are missing.

**Comment by Spedwards** [comment]
Or you could just look at the wiki page you provided? You can click on quests to highlight them to show that you've completed them so this would honestly be pointless.

**Comment by WildsIM** [comment]
But i have completed about half of the quests completely random, and want to know what would be next. Because the list is optimized so training skills is minimal.

**Comment by Spedwards** [comment]
I'm aware of the list. It still won't change the fact that adding this into RuneLite would be pointless and we'd just be doing the same calculations that the wiki has already done.

I'm not saying that someone won't try and get this added, but it's a really bad request.

**Comment by Berry-95** [comment]
I've been playing with this idea for a while and still can't decide if it's a useful enough addition...
On the one hand it saves you manually tracking what quests you've completed (as the plugin could probably detect this and the wiki on multiple occasions has forgotten my highlighted entries), as well as dynamic ordering based on user preference and current levels (accounts for skilling, which the wiki does not unless specified).
But as @Spedwards says even then it would be only a slight improvement over the wiki article.

**Comment by deathbeam** [comment]
Just use the wiki article, I believe we already have open issue for quest helper tho
