### ISSUE TITLE
The Chaos Altar percentage in the Prayer Category of the Skill Calculator plugin is wrong

### ISSUE THREAD

**Issue by Hacki96** [runelite/runelite#7231]
**700% at Chaos Altar makes no sense whatsoever because it would mean that the altar would have a 100% chance not to consume the bones, which in turn would mean you'd need 1 bones item and could stay there till 200m xp (theoretically).**

Chaos Altar gives 350% prayer experience for bones and has a 50% chance to not consume the bones.
On average this would mean you get 3 bone uses out of 2 bones.

Here the maths:
3 times 350% is 1050% divided by 2 for 2 bones used = 525%.

It should be changed from 700% to 525% in order to reflect the average amount of experience per bones.

**Comment by TheStonedTurtle** [comment]
https://en.wikipedia.org/wiki/Fibonacci_number

**Comment by Abextm** [comment]
This is working as intended because you can use each bone more than twice. The wiki has [a good explaination.](https://oldschool.runescape.wiki/w/Chaos_Temple_(hut)#The_chaos_altar)
