### ISSUE TITLE
Red edge on 2005 interface style minimap

### ISSUE THREAD

**Issue by troypressley1** [runelite/runelite#7235]
This has been an issue for a while, but has been seemingly fixed in past versions. Having the 2005 interface active causes the minimap to get a red edge after less than a minute of use every single time. 

It can be fixed by turning the interface style off and on again, but the red comes back within 30 seconds, which is as fast as its ever done that. This bug was around for a while before, but previous versions had seemingly gotten rid of this problem, but for some reason it basically happens 24/7 again now. A bit pedantic, but it's annoying enough to make me not use that interface style.

![map 2005](https://user-images.githubusercontent.com/25185645/50836015-2b70ab80-1326-11e9-8a5e-2f90a24488ed.png)

**Comment by Spedwards** [comment]
This appears to only be on fixed style. I get a fine blue edge but it's still buggy. Turning the plugin off and on seemed to fix it as I have not got the edge since.

![](https://i.imgur.com/qDJCMfe.png)

**Comment by AmazingJesus** [comment]
It's not only the colour red. It can be any colour I don't know where it picks the colour from.

**Comment by Lipstopica** [comment]
Yeah, happens to me too. Hopefully a fix will come through soon.

**Comment by Lipstopica** [comment]
Not sure if this information helps but, the red line appears when the screen flashes red from what I've noticed.

**Comment by Alexsuperfly** [comment]
sounds like that space is just null canvas where it just displays the last color drawn on it and never repaints to clear it

**Comment by Lipstopica** [comment]
Yeah seems that way. 

But for the people who find it irritating make sure you do not have flash (causes the red) on and make sure you do not close and open the sidebar(causes the grey line). If it appears you can just turn off Interface Style and turn it back on.

**Comment by Lipstopica** [comment]
Still nothing?
