### ISSUE TITLE
Skybox disappearing on certain camera angles in varrock sewers entrance

### ISSUE THREAD

**Issue by Juuldamen** [runelite/runelite#7239]
If you stand in the marked tiles within varrock sewers and move your camera to specific angles the skybox will disappear. 

![java_2019-01-08_22-13-14](https://user-images.githubusercontent.com/31408341/50859114-b8514e80-1392-11e9-90b0-22f941d77a28.png)
![java_2019-01-08_22-13-21](https://user-images.githubusercontent.com/31408341/50859117-bb4c3f00-1392-11e9-9916-5ab82e1e4917.png)

[Example video](https://www.youtube.com/watch?v=MWIPDahPbxc&feature=youtu.be)

**Comment by Adam-** [comment]
@Abextm I guess this is due to the camera inverting?

**Comment by Abextm** [comment]
Yeah, this is because the sample point is entering a chunk with no data. The band-aid fix would be to just use the player's position without accounting for the camera, but I think that looks odd.

**Comment by Adam-** [comment]
Can it use the player position only if the inverted camera position has no data?

**Comment by Abextm** [comment]
that would cause a discontinuity
