### ISSUE TITLE
Sorting timers in `Time Tracking` by time left and timer text color change at last seconds.

### ISSUE THREAD

**Issue by Qualphey** [runelite/runelite#7240]
There would be much more ease of use if you could **sort timers by how much time is left**. _Again,_ I use timers for rune mining. Each timer represents a world and is started when rune depletes, since they are not arranged this way it requires a lot of effort to find which timer is about to end counting. 

Also the **text color of a timer should change when there is little time left** (say orange 5-10 sec). And of course it would be more convenient if you could modify the color and time at which to alert in settings.

Thank you!

**Comment by jakewilson** [comment]
working on this
