### ISSUE TITLE
Ghost clicks / Double clicks / Random clicks

### ISSUE THREAD

**Issue by civRS** [runelite/runelite#7243]
Been experiencing this issue specifically since I downloaded RuneLite, there are barely any other posts or people talking about it, so I figured I would post.

For the record, I have tried 3 different mice, 3 different clients (OG, OSBuddy, & RuneLite), I have uninstalled and reinstalled RL on different 2 different drives (HDD & SSD), I have disabled Hardware Acceleration, ran RL as Admin, disabled all plugins (multiple times).

The only thing I have fallen short of is factory reseting my PC.

PC Specs:
i7 8700k
32gb RAM
GTX 1070
(https://pcpartpicker.com/user/civilian./saved/FTX7hM)

I can include a video of the issue if necessary.

It seems like it mainly happens with I am instance switching and clicking too fast for the game? I have noticed it a lot in Pyramid Plunder, I will click to disable the wall traps and a ghost click will happen after clicking the walls, making my character walk or perform actions I didn't specify.

**Comment by Digbigpig** [comment]
You said you tried 3 different clients, meaning it is happening on all 3 clients?

**Comment by civRS** [comment]
Tried 3 different clients, only happens in RL. Doesn't happen in OSBuddy or on the OG client.

**Comment by deathbeam** [comment]
No idea why is this happening only in RuneLite for you but it should not

**Comment by Abextm** [comment]
Try running RuneLite with ` --c --rs=vanilla` and see if your issue persists. Additionally a video showing the bug happening would be helpful

**Comment by civRS** [comment]
Update - Haven't experienced this issue since I uninstalled Logitech's Mouse / Keyboard software, as well as switched keyboards from the Logitech G Pro. Not sure why it was causing the issue?

**Comment by Alexsuperfly** [comment]
this sounds like #9179 which was fixed in a3e9b790dd92d8fe7eb12d35de6db250f1f78328

**Comment by deathbeam** [comment]
This can be probably closed then
