### ISSUE TITLE
Bank value missing for Mystic Steam battlestaff(orn), Lava Battlestaff(orn)

### ISSUE THREAD

**Issue by Crystalknoct** [runelite/runelite#7251]
Hi I was told to make a issue post about the bank value not displaying properly for certain cosmetically affected items. IE, Mystic Steam battlestaff(orn), Lava Battlestaff(orn). Would it be possible to combine the cost of the ornament+the item together like you do with fury, etc. I understand you lose it but lots of people keep those items forever once they do so.

**Comment by Bjdufre1** [comment]
In a discord conversation it was decided if you don’t get the item back we won’t add it to the price checker

**Comment by Alexsuperfly** [comment]
This can be closed since the plugins purpose is liquid-able value and so this would not be implemented for that reason.
