### ISSUE TITLE
Hide other players' Barrows brothers

### ISSUE THREAD

**Issue by WLoumakis** [runelite/runelite#7252]
It's really annoying doing Barrows with tons of other players stacking up their current brother either in the same tomb or in the chest room making you have to right-click to attack the brother that's attacking you. With the entity hider plugin you can hide NPCs, which helps with the brothers but then you can't see the monsters you need to kill for points.

Is there any way to implement a "Hide all other players' brothers" option to the Barrows plugin (or entity hider)? If not, no worries. Just wanted to see if there was any way to increase the efficiency. If so, well I suppose that's what this post is for :)

Another potential solution for this, which I feel like would be more under Jagex's belt than RuneLite, would be to send the attacking brother to the top of the list so that you don't have to right-click.

**Comment by deathbeam** [comment]
We are intentionally not hiding specific NPCs/Players, so this will not be implemented

**Comment by edi-spaghetti** [comment]
hello from the future, for anyone searching for this specific issue you can now hide other players' barrows borthers using entity hider plugin by setting the following;

hide npcs = checked
hide attackers = false

This will make it so other players' barrows brothers are hidden, but as soon as your brother attacks you it will show up.
There's a one-tick delay from them spawning to aggro-ing you, so I generally use this to move closer to the stairs for a faster exit and then that's it. happy days.

optionally, to make your screen a little less messy if there's really a LOT of others doing barrows (like during leagues), you can also set the following;

hide others = checked
hide others 2D = checked
hide NPCs 2D = checked
