### ISSUE TITLE
Make a VR plugin

### ISSUE THREAD

**Issue by Mugdog** [runelite/runelite#7257]
Seriously just a suggestion. Would a VR plugin be possible? I could imagine it might be but I'm not sure. I own a Windows Mixed Reality VR headset and thought Runescape VR would be kind of neat to see. Might be impossible but figure I'd throw it out there. A lot more people are getting VR headsets. Slowly but surely. I'd say it's not a bad idea.

**Comment by deathbeam** [comment]
No it will not be possible, at least not with RuneLite/OSRS

**Comment by ijustlovemath** [comment]
This might actually be technically feasible with recent developments.There might need to be a new rendering process, but you can easily communicate things like ingame location, clicks, armors, scene elements etc over a network port, and then model places using the same blender techniques that are so popular in series like Coxies. Google also confirmed that headsets with Android XR will be able to run full android apps, so you could always fallback to the desktop mode with the OSRS mobile client.
