### ISSUE TITLE
Make shift-click configuration not require shift

### ISSUE THREAD

**Issue by RandaliciousRS** [runelite/runelite#7261]
Trying to play runelite on a surface pro in tablet mode and can't drop items by touching them (like how you can on mobile app I want a similar experience on this) and sticky keys don't appear to work in tablet mode. Requesting an option to have the menu swapper work even if shift key isn't held down or have a setting in runelite to always have the shift key held down so this could be possible. 

God bless

**Comment by Nightfirecat** [comment]
Added in 8944eb9be6d62ec8384e29484dab14c4c2858d9d, alongside the already existing shift-click configuration
