### ISSUE TITLE
Map Markers / Path Finder / Quest Assistant

### ISSUE THREAD

**Issue by EraSwift** [runelite/runelite#7262]
I would like to see destination markers from RS2 re-introduced into the world map. Double clicking on the map created a blue marker which then puts an arrow on your mini-map pointing you in the direction to go.

Like this, but blue
![image](https://user-images.githubusercontent.com/18635655/50967946-c2f41b00-152d-11e9-972f-89c9783a8304.png)

But since RuneLite is in the spirit of improving upon Runescape, it would be even better to show the optimal route to take on your mini-map, perhaps even going as far as suggesting different teleports and fairy rings to get you closer to your target destination.

This has the potential to be one of the biggest updates to the client, since 80% of the game is just running around, and once built this system could easily be used as part of a quest assistant plugin, where each subsequent location is shown to you (no more wiki guides, no more getting lost in the jungle, etc).

I see there are currently 892 open issues and understand that it is difficult to please everyone, there's no doubt everyone would love this plugin and might not even be that hard to pull off. I'd even be willing to help work on this, provided someone can help me setup the project (I suck at Maven).

**Comment by deathbeam** [comment]
We already have open issue for this
