### ISSUE TITLE
Add skill requirements for Kourend & Kebos Tasks to the Diary Requirements plugin

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#7264]
![image](https://user-images.githubusercontent.com/9074448/50970056-9ebe1d00-14e0-11e9-8e00-8c91eedc4187.png)
Requirements are listed here: https://oldschool.runescape.wiki/w/Kourend_%26_Kebos_Diary

**Comment by Abextm** [comment]
Restart your client.
