### ISSUE TITLE
Object marker doesn't work on sulphur vents

### ISSUE THREAD

**Issue by vikke1234** [runelite/runelite#7265]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Object marker doesn't work on sulphur vents

**To Reproduce**
have object marker on -> rightclick on sulphur vent by e.g. inferno bank -> doesn't mark it

**Expected behavior**
should mark it

**Environment (please complete the following information):**
didn't work on either ubuntu 18.04 or windows

**Comment by deathbeam** [comment]
Based on discord report also `Is it known that you cant "Object mark" the Loose Railing you can Squeeze-through in the Tree Gnome Village?`

**Comment by Hydrox6** [comment]
Added in https://github.com/runelite/runelite/commit/ad5514acdefe657b31326c2f6776c66884daf060
