### ISSUE TITLE
Tasks from konar don't trigger the slayer counter to show.

### ISSUE THREAD

**Issue by Barragek0** [runelite/runelite#7267]

**Comment by Nightfirecat** [comment]
Could you provide a screenshot of the dialog she provides when giving a task?

**Comment by Barragek0** [comment]
Will do the next time i get a task

**Comment by Alexsuperfly** [comment]
![](https://cdn.discordapp.com/attachments/361679294679744524/532930652497248266/unknown.png)

**Comment by Barragek0** [comment]
The icon also doesn't show the correct task.
https://i.imgur.com/FkB34XC.png

**Comment by Alexsuperfly** [comment]
heres an image for checking task on helm if you would like that aswell 
![image](https://user-images.githubusercontent.com/7191512/50988085-8dbddd80-14d9-11e9-9bbc-227c3be13f0e.png)

**Comment by ChaoticConundrum** [comment]
See #7288

**Comment by Alexsuperfly** [comment]
gem check also can not have a "the" for location 
![image](https://user-images.githubusercontent.com/7191512/51063727-38152e00-15ca-11e9-93fe-2ec2b5ee5d1c.png)
