### ISSUE TITLE
Add clan chat join alerts, something to avoid accidental kicks

### ISSUE THREAD

**Issue by Unmoon** [runelite/runelite#727]
- Join alerts on: total level, P2P/F2P exp, F2P/P2P/RS3/RS3Lobby worlds
- Chat message right click -> Kick from CC
- Something to  avoid accidental kicks, maybe to do with ordering of the cc members list?

**Comment by TheStonedTurtle** [comment]
> Join alerts on: total level, P2P/F2P exp, F2P/P2P/RS3/RS3Lobby worlds
Total level/skill exp would require hiscore lookups which could run into rate limit issues.
#8160 adds the worlds request.

> Chat message right click -> Kick from CC
Already exists on both the messages and the interfaces

> Something to avoid accidental kicks, maybe to do with ordering of the cc members list?
You can sort by rank & name which seems to account for this?

**Comment by Adam-** [comment]
Doesn't the game already force kicks to be right click? (or left clicking opens the menu always)

**Comment by Alexsuperfly** [comment]
when wanting to use the lookup and hop-to options, kick is just a twitch away, and miss clicks can easily happen.  Thus was the explanation in discord earlier about this topic and the new pr opened for it.
