### ISSUE TITLE
Add new Kebos hard clue hint

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#7275]
https://www.reddit.com/r/2007scape/comments/aei10v/the_kebos_lowlands/edpg1ji/

> New hard clue step?
> 
> "The effects of this fire are magnified"

Also, per #4307, if we can get the clue ID for this new clue, that would be very helpful.

**Comment by Alexsuperfly** [comment]
ID: 23045

**Comment by JeljoGb** [comment]
Dig by the fire beside Ket'sal K'uk in the westernmost part of the Kebos
![image](https://user-images.githubusercontent.com/34870401/51496791-5268bc00-1dc1-11e9-9e21-f739a6da15da.png)

**Comment by xDemoN** [comment]
@Nightfirecat Didn't #7800 close this?

**Comment by Nightfirecat** [comment]
Yeah
