### ISSUE TITLE
Herbs displaying as "Done" a farming tick too early

### ISSUE THREAD

**Issue by Alfie94** [runelite/runelite#7278]
**Describe the bug**
A herb patch displays as done in the herb timers tab, but upon going to the patch it is still one farming tick away from being completed.

This is not always the case, more often than not the timers work correctly.

**To Reproduce**
Unsure how to get this to reproduce consistently. sometimes it happens, sometimes it doesn't. Do not know the criteria, sorry.
1. Plant herb
2. Check timer one farming tick before it's supposed to be completed.
3. Go to patch and see the herb is not finished growing.
4. Clicking the patch updates the timer to be correct.

**Expected behavior**
The timer to correctly time the herb completion.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.7
 - Launcher version: 1.6

**Comment by Abextm** [comment]
Duplicate #2491
