### ISSUE TITLE
Add new medium clue step (Mount Karuulm)

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#7280]
![image](https://user-images.githubusercontent.com/7191512/51005005-199c2d80-150b-11e9-952b-be3eb0892f94.png)

**Comment by Bjdufre1** [comment]
Do you have a screenshot or anything of the exact location?

**Comment by Hydrox6** [comment]
It's right next to the STASH unit

**Comment by Alexsuperfly** [comment]
next to the stash, like everything else

**Comment by Bjdufre1** [comment]
:man_facepalming: Oops
