### ISSUE TITLE
Add Timers for the new Farming Guild patches

### ISSUE THREAD

**Issue by sycp001** [runelite/runelite#7281]
Farming Timers should be added for the new patches added in the farming guild including the new seeds. 
new patches are:
2 allotments
1 flower
1 bush
1 cactus/potato cactus
1 herb
1 anima
1 Hespori
1 Tree
1 Celastrus
1 Fruit tree
1 Spirit tree
1 redwood tree

**Comment by gregg1494** [comment]
Working on this now

**Comment by kblicharski** [comment]
@gregg1494 Do you need any help?

**Comment by deathbeam** [comment]
I think this was added
