### ISSUE TITLE
Alchemical Hydra plugin

### ISSUE THREAD

**Issue by freminik** [runelite/runelite#7290]
I'd like a plugin for the Alchemical Hydra boss, similar to the demonic gorilla plugin where it shows you the three attacks it will do on you and then switches to the other attack style. Would be sick with a plugin like this, considering it basically only needs to be a copy-paste from demonic gorillas and modified a little bit. Would help a ton for us that forget a lot.

A plugin to show what attack style the hydra uses, similar to the demonic gorilla where it shows the three attacks and then switches to the other combat style. In this case, the alchemical hydra does 3 ranged & mage attacks and then on some phases there are special attacks like the lightning, the poison blob and the fire. Also it switches to the opposite attack style in the last phase of the kill.

**Comment by Adam-** [comment]
Historically we've avoided adding plugins for new PVM content and have also had Jagex express interest in us not making plugins for new PVM content in the past, so this is not something we want to do now. Maybe in the future.
