### ISSUE TITLE
GameObjectSpawned activating on mined ore

### ISSUE THREAD

**Issue by liverare** [runelite/runelite#7297]
```
@Subscribe
    public void onGameObjectSpawned(GameObjectSpawned gameObjectSpawned) {

        GameObject gameObject = gameObjectSpawned.getGameObject();
        WorldPoint worldPoint = gameObject.getWorldLocation();

        if (gameObject.getId() == 7491 /* gold ore rock ID */
                && (worldPoint.getX() == 2938 && worldPoint.getY() == 3280) /* Crafting Guild - opposite to the bank chest */) {

            System.out.println("Gold ore exists");
        }
    }
```

"Gold ore exists" is logged out even after the gold ore has been mined and I re-enter the scene/hop world and then hop back.

 - OS: Windows
 - RuneLite version: 1.5.4
 - Launcher version: unknown (launched via IntelliJ IDEA)

**Comment by deathbeam** [comment]
That is just how it works, you need to store that you already mined it or something, objects "spawn" again whenever you enter the scene again
