### ISSUE TITLE
Custom skybox colors. [RGB]

### ISSUE THREAD

**Issue by Raiinn** [runelite/runelite#7300]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
-feature request
**Describe the solution you'd like**
-Custom skybox colors [RGB]
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
-None
**Additional context**
-None

**Comment by deathbeam** [comment]
We can't really support custom colors because the skybox is different on every location
