### ISSUE TITLE
Ancient Cavern Chasm Skybox

### ISSUE THREAD

**Issue by BongoBooty** [runelite/runelite#7304]
**Describe the bug**
With skyboxes on, the chasm in the Ancient Cavern is the same color as the skybox (grey).

**To Reproduce**
1. Go to Ancient Cavern
2. Go down the east side of the cave by mith dragons.
3. See problem. Chasm is same color as skybox.

**Expected behavior**
The chasm should be black.

**Screenshots**
![image](https://user-images.githubusercontent.com/46613797/51069095-5f81f000-15f6-11e9-9f79-aa10471ca7f4.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.7
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
Dulicate of  #7250
