### ISSUE TITLE
Notification flash persists on login screen

### ISSUE THREAD

**Issue by 15987632** [runelite/runelite#7316]
When you open the client and get a notification with the enable flash option on the red persists. https://i.imgur.com/5zZEe6T.jpg

I am pretty sure this is the same issue as being able to draw on the black part of the login screen with the world hopper tooltips.
https://streamable.com/dd36n

Might be jagex bug for the second part but we should be able to fix the first, maybe disable the flash on the login screen?

**Comment by Twiglet1022** [comment]
I came across this too in #6375 when adding a config for the flash duration. If it was extended long enough to persist to the login screen it would do exactly what you've described.

I solved that with this: https://github.com/runelite/runelite/pull/6375/files#diff-bf265f5ad83eea9b469bdd43046c6ce2R163
