### ISSUE TITLE
Show fishing spot type in world map

### ISSUE THREAD

**Issue by TheF0rg1ven** [runelite/runelite#7317]
https://i.imgur.com/Dlb9irZ.png
Add what fish can be caught at a fishing spot when hovered over on the minimap.
Example. Fishing Spot - Lobster, Swordfish, Tuna
Could maybe add the needed fishing equipment as well.

**Comment by ermalsh** [comment]
I'll work on this, already implemented it just need to fill in all the locations lol - there's a lot of spots though so community help with 

> Spot Location: Type of Fish

 would be sweet :)

Preview:
https://gyazo.com/57806eca67a4388ca3483088a4a8fdd5

**Comment by nlruk** [comment]
@ermalsh Any updates?

I suggested the same thing but it got closed https://github.com/runelite/runelite/issues/11396

**Comment by nlruk** [comment]
@ermalsh Let me know how to add this and I will try

**Comment by nlruk** [comment]
@melkypie I saw you completed my agility suggestion would you be kind enough to do https://github.com/runelite/runelite/issues/11396 or show me how? I'd love to contribute.

**Comment by basicDamen** [comment]
> @melkypie I saw you completed my agility suggestion would you be kind enough to do https://github.com/runelite/runelite/issues/11396 or show me how? I'd love to contribute. 

If you would like to help him, then you can gather a list of all data for all fishing spots. He stated he already has the system in place, he just needs help filling it in.
