### ISSUE TITLE
Additional fonts for notes?

### ISSUE THREAD

**Issue by HiImTaylor** [runelite/runelite#7322]
**Is your feature request related to a problem? Please describe.**
-Edit- Not related to a problem. I'm just dumb and didn't read correctly when I first made the post.
Like the title suggests, would it be possible for additional fonts to be implemented for the in client notes tab? I personally prefer to have a monospace for notes for formatting things nicely. Recently, I have started creating more and more notes, and I personally prefer when I can format lists of things, but with the current font, the lists don't line up nicely. 

**Describe the solution you'd like**
An option for different fonts within the options menu for the notes tab, or maybe just a font change? Ideally, to appeal to the largest number of people, multiple fonts would be best. That way, some people like myself could get a monospaced font so that all the characters line up evenly, where as someone else might prefer a more fancy font. 

**Describe alternatives you've considered**
Using a different program to keep notes in if I want neat formatting.

**Additional context**
As can be seen in the screen shot, it is visible that not all the payments for each type of tree lines up nicely, which is annoying in my personal opinion. 
![notes tab](https://user-images.githubusercontent.com/31742972/51080788-f6a28280-169e-11e9-9124-79d2c9fc147d.PNG)

**Comment by NoNameOsrs** [comment]
I'd like to see more add-on to the notepad, as in:

Being able to combine text + image, different font sizes, different fonts, different font colors, etc.

**Comment by deathbeam** [comment]
We already have issue open for general client ui font, we are not going to extend notes plugin with more features, it is supposed to be just for storing notes in plaintext, if you want more, I bet Microsoft has some products in what you might be interested :p

**Comment by NoNameOsrs** [comment]
haha, no worries, was just an idea @deathbeam. thanks for ur quick response.

**Comment by HiImTaylor** [comment]
The thing I like about the notes plugin is that it follows me across multiple devices, whereas Microsoft product files aren’t as EASILY transferable. Can be done, yes, but it’s more of a hassle than worth, and it adds having to switch between different windows when the runelite notes are much easier to play and use at the same time. 

Not wanting to change what the plug in currently is is understandable though. Thanks for the response

**Comment by deathbeam** [comment]
I usually use Dropbox for bigger stuff
