### ISSUE TITLE
Item Prices tooltip not showing up on Mac

### ISSUE THREAD

**Issue by bilvy** [runelite/runelite#7327]
I just installed Runelite on a PC yesterday, and got to see the Item Prices tooltip which was really handy. Today I installed it on my own Mac, and made the settings all the same (to the best of my memory), but the Item Prices aren't showing up this time. It doesn't appear when items are on the ground, in my inventory, or in the bank (even with 'Hide Tooltips On Inventory Items' unchecked). Also, when I enabled the "Examine" plugin, the info only showed me the HA number, and didn't give me any GE information.
Edit: Also, just remembered, with "Bank Value" enabled, it only shows me the amount of coins i have, and doesn't take into account any of my items.

I've restarted the client, tried checking and unchecking multiple plugins to see if there's a compatibility issue, and checked the logs. Can't find any "SSLException", "ERROR" or "Exception". !Price also does not seem to do anything (my toon just says "!Price" as if i'm chatting, and yes I have Chat Commands on).

**Comment by deathbeam** [comment]
You probably cant access api: https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by repsejnworb** [comment]
@deathbeam I have the same issue, nothing in the logs about anything with issues accessing the API. 
Which OP also stated.

**Comment by deathbeam** [comment]
Yeah I have no idea why you dont have anything about that in logs, but the symptoms looks like that is exactly what is happening, and there is not much we can do about that.

**Comment by repsejnworb** [comment]
@deathbeam anyway to enable more verbose logging?

**Comment by deathbeam** [comment]
You can try running clauncher with `--debug --clientargs="--debug"`

**Comment by repsejnworb** [comment]
@deathbeam wow my bad. I apparantly hade the "Hide Tooltips on Inventory Items" enabled on my mac. Sorry for wasting your time.

@bilvy you might want to try adding more logging though.
