### ISSUE TITLE
Show slayer infobox when you don't have a task

### ISSUE THREAD

**Issue by vosdev** [runelite/runelite#7333]
When your task is complete, the infobox disappears, and will stay away until you get a new task.

The infobox holds useful information that I would like access to without having to get a slayer assignment. If I am on a 99 slayer streak, I want to make sure I don't go to Turael. You cannot get this information from the game itself without completing a task.

**Describe the solution you'd like**
When you do not have an active task, show the infobox anyways (slayer gem logo) (Optional). It can show your Pts, Streak, and instead of a task name like `Black Demons` it can say : `You need something new to hunt.`

**Describe alternatives you've considered**
Sticky Note on my monitor with the streak number written down on it.

**Comment by deathbeam** [comment]
You can change the timeout in slayer plugin settings

**Comment by Nachtmerrie** [comment]
I already have the timeout set to 9999 minutes. This does not matter. The infobox is only active when you do not have a slayer task. My feature request is for it to be also active (optional) when you do *not* have a slayer task.
