### ISSUE TITLE
Option to turn off Hitpoints/Prayer Threshold

### ISSUE THREAD

**Issue by Toxxed** [runelite/runelite#734]
Would like to have an option to turn off HP/Pray threshold entirely, hitting this threshold stops FKeys from working or ability to type in general for a few seconds. Yes, it is possible to turn off the Idle Notifier any time this could happen, but that's extra settings changes based on in-game activity, would be QOL to never have to touch it

**Comment by Unmoon** [comment]
Turn off "Notify When Focused" to fix the F keys not working.

**Comment by deathbeam** [comment]
Also you can set the threshold to 0 to effectively disable it.

**Comment by Toxxed** [comment]
For health maybe, but prayer causes same issue @deathbeam but what unmoon said works well for everything I've been able to think of

**Comment by deathbeam** [comment]
It might work then if you set it to -1 if possible. But yeah the notify when focused disabled solves it. I think we even have it disabled by default :D

**Comment by deathbeam** [comment]
Resolved in #2007
