### ISSUE TITLE
slayer task completion eta

### ISSUE THREAD

**Issue by graingert** [runelite/runelite#7349]
**Is your feature request related to a problem? Please describe.**
I'd like to see an estimation of the time remaining on my slayer task

**Describe the solution you'd like**
similar to the actions per hour on the slayer xp goal, but with the arithmetic done for you

**Describe alternatives you've considered**
I can do it manually - but it's a bit of a pain

**Additional context**
na

**Comment by deathbeam** [comment]
Just check actions left and actions/hr

**Comment by graingert** [comment]
Yeah I know I can do the math myself - it's just easier for the computer to do it for me
