### ISSUE TITLE
click through cannon

### ISSUE THREAD

**Issue by TicksWasted** [runelite/runelite#7351]
it would be nice to have a toggle in the cannon plugin where it would make the the first option on the cannon "walk here" instead of "fire", that way u wouldnt misclick on "fire" after you went to pick up a loot and u trying to get in position for double hit spots, since a lot of people use cannonballs on the cannon instead of clicking fire anyways

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features <- conditional menu entry swapping
