### ISSUE TITLE
Kill count for demonic gorrillas

### ISSUE THREAD

**Issue by Stickaplex** [runelite/runelite#7363]
I requested this in the past #1733 which at the time wasnt possible.

Was wondering if it is now possible with the addition of collection log now tracking them. 
If the issue is it tracks both demonics and regular ones I don't really see that being an issue as most don't kill the small ones anyway.

Just wanting to open this up again to see if anything had changed

**Comment by deathbeam** [comment]
No, still same scenario.

**Comment by deathbeam** [comment]
(also you can just use loot tracker now)
