### ISSUE TITLE
Issues with using Sidebar while GPU is enabled

### ISSUE THREAD

**Issue by Disproven** [runelite/runelite#7364]
**Describe the bug**
When I click on any of the sidebar icons with GPU enabled on my high performance Nvidia GPU processor the game crashes. I have tried disabling hardware acceleration and that did not fix it.

**To Reproduce**
1. Run runelite with high performance gpu with gpu feature enabled
2. Click on sidebar icons(sometimes crashes when i open one, other times crashes after clicking on the tab multiple times or navigating around the tab)
3. Crashes
**Only for my setup**

**Expected behavior**
The game goes [unresponsive.](url)

**Screenshots**
![img_3308](https://user-images.githubusercontent.com/46703526/51163766-5e53fb80-1860-11e9-9e09-2dd7a8c24326.jpg)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: Latest
 - Launcher version: Latest

Please help me, its really annoying having to restart the game multiple times when I'm playing.

**Comment by deathbeam** [comment]
I am pretty sure this is issue with having HW accel enabled, are you sure you followed the guide properly
