### ISSUE TITLE
Feature Request: Colored text that says "is attacking/is not attacking"

### ISSUE THREAD

**Issue by psrkallez06** [runelite/runelite#7366]
**Is your feature request related to a problem? Please describe.**
No problem, just would like it!

**Describe the solution you'd like**
Exactly the same as with mining/woodcutting/fishing. When you are attacking/fighing something it says "fighing" with a green text, when you are not in combat anymore it says "not fighting" 

Cheers and keep up the great work with this client!

**Comment by Hydrox6** [comment]
![](https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif)

**Comment by deathbeam** [comment]
We have idle notifier and opponent info that can already tell you that
