### ISSUE TITLE
"Draggable" xp tracker

### ISSUE THREAD

**Issue by aWayOutOfLoneliness** [runelite/runelite#7367]
**Describe the solution you'd like**
Let us drag the xp tracker onto the game screen just like you could do with Konduit in the past.

**Additional context**
Konduit's old feature

![image](https://user-images.githubusercontent.com/46714673/51183913-07d3d500-18d3-11e9-910f-897a641b2625.png)

Current and proposed function on Runelite

![image](https://user-images.githubusercontent.com/46714673/51183959-2cc84800-18d3-11e9-9c88-d9aebba6a137.png)

**Comment by deathbeam** [comment]
We already have issue for this

**Comment by aWayOutOfLoneliness** [comment]
> 
> 
> We already have issue for this

Where's the thread?

**Comment by deathbeam** [comment]
#1749
