### ISSUE TITLE
Demon butler leaves respawn timers when sent to bank

### ISSUE THREAD

**Issue by HSJ-OSRS** [runelite/runelite#7368]
**Describe the bug**
When you have the demon butler highlighted through the npc indicators plugin and send him to the bank he leaves behind respawn timers as tho he died some start with like 0.1 seconds and disappear instantly others have very long timers.

**To Reproduce**
1. put "demon butler" into NPCs to highlight box in the npc indicator plugin config
2. Send him to the bank
4. See respawn timers appear as tho he died

**Expected behavior**
Npc to leave and come back without creating respawn timers

**Screenshots**
![bug](https://i.imgur.com/ow0FIGa.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.8-SNAPSHOT
 - Launcher version: n/a

**Comment by Adam-** [comment]
This is probably wontfix since we cant tell the different in him dieing and leaving.

**Comment by deathbeam** [comment]
NPC "despawned", so this is correct behaviour. Just disable respawn timers if you dont want to see them
