### ISSUE TITLE
Lock to screen

### ISSUE THREAD

**Issue by norskaaa** [runelite/runelite#737]
Any thoughts on being able to have a toggle to lock client to a screen? I find this very useful to line my clients up along the bottom of my screens.

This is what i mean if its not clear (me dragging my client towards my left screen from my right):
https://i.imgur.com/mEXGDrK.gifv

**Comment by sethtroll** [comment]
Added in 1b7bdc616b5268bfc6a0de5cfabdab4bed2d3f49
