### ISSUE TITLE
Add option to *permanently* save a NPC's loot tracker loot

### ISSUE THREAD

**Issue by EliasLahham** [runelite/runelite#7379]
**Describe the solution you'd like**
At the moment the loot tracker saves all the loot from a finite amount of monsters before they start to be replaced once you go over that limit. As I understand you can only have 10 or so NPC in the loot tracker before they start to get replaced by the next NPC you kill. Please read my suggestion below:

**Describe alternatives you've considered**
By simply adding a tick mark/star on an NPC in the loot tracker plugin will allow that NPC to never be taken off the list as long you don't turn off the plugin.

**Additional context**
Here's an example screenshot of what I would like to see in the loot tracker plugin:
https://imgur.com/a/twwpq3Z

**Comment by deathbeam** [comment]
You dont understand how the loot tracker works, it just loads last 1000 entires but the data are still persisted on remote even when youh dont see them
