### ISSUE TITLE
Motherlode Mine Show Ores Mined

### ISSUE THREAD

**Issue by SirGirion** [runelite/runelite#7381]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just want to keep track of how many of a specific ore I mined without referencing my bank.

**Describe the solution you'd like**
Add a tracker similar to the gem overlay that shows what ores have been mined and how many were mined.

**Describe alternatives you've considered**
I suppose this could be incorporated into loot tracker somehow but I think this makes sense as part of the existing motherlode mine plugin.

**Additional context**
![image](https://user-images.githubusercontent.com/3239328/51226177-36c26900-191c-11e9-82dd-ae3011bd02c0.png)
Example of how the overlay would show information

**Comment by EatSleepSlay** [comment]
Maybe integration with the loot tracker?
