### ISSUE TITLE
add screenshot of valuable drops minimum value

### ISSUE THREAD

**Issue by lord0fham** [runelite/runelite#7388]
I turned on the option to screenshot valuable drops and it start screenshotting pretty much every drop I got from cerb or even dust devils. There should be an option to put a minimum value like 1m, 5m or whatever to avoid this.

**Comment by Nightfirecat** [comment]
Change your ingame settings for what constitutes as a "Valuable" drop.

**Comment by deathbeam** [comment]
As @Nightfirecat said. And we already had issue for this (what is probably closed now)
