### ISSUE TITLE
Skybox/GPU Draw Distance issue

### ISSUE THREAD

**Issue by ChaMarda** [runelite/runelite#7394]
Ever since activating the new skybox feature my draw distance is now large area chunks and will not load the next part of the map until I am  about 20 tiles away from the edge. Previously I always had 70 (The number I had my draw distance set to) tiles surrounding me and a they would load with every step I took.

How it usually looks all the time
![capture](https://user-images.githubusercontent.com/46765747/51286022-18766f00-19e9-11e9-8673-a1fed1744579.PNG)

How it looks when I move towards the edge
![capture3](https://user-images.githubusercontent.com/46765747/51286047-3a6ff180-19e9-11e9-8a8f-689f5c48cab5.PNG)

How it looks a couple steps later (Huge chunk loads in, usually each tile loads gradually as I step)
![capture4](https://user-images.githubusercontent.com/46765747/51286087-5e333780-19e9-11e9-8caf-567d5c305543.PNG)

**Comment by Alexsuperfly** [comment]
Its always been like that, just took until now for you to notice.

**Comment by ChaMarda** [comment]
Wll i'll be damned
