### ISSUE TITLE
Wiki option on Right click

### ISSUE THREAD

**Issue by Expression7** [runelite/runelite#7396]
It's a hassle when I need to look up the wiki page to a certain quest, item or NPC. I'd like to Right click on something in game and have a "Wiki" option on the drop down menu. Which would open a link to it in your default browser. This could be an optional toggle too.

**Comment by Alexsuperfly** [comment]
duplicate of #2551

**Comment by Expression7** [comment]
> duplicate of #2551

was #2304 added to runelite? , it looks like it was approved.
