### ISSUE TITLE
Unable to use GPU Plug In

### ISSUE THREAD

**Issue by Beowulf7** [runelite/runelite#7398]
I am unable to turn on the GPU setting. It has been working fine for the last couple months since it was released. I meet all the requirements for it and have tried the trouble shooting tips provided on here, as well as uninstall and reinstall Runelite. I have an Intel UHD 620 if that's helpful at all. When I try to turn it on it just automatically switches itself off. Today is the first day having this problem.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/GPU-FAQ . you probably updated your driver or somehting
