### ISSUE TITLE
Restoration of maximized state results in visual bug

### ISSUE THREAD

**Issue by devLotto** [runelite/runelite#740]
Boot up client -> maximize -> open sidebar -> restore/unmaximize.
The bug disappears if you move the frame.

![](https://i.imgur.com/9p4544U.png)

**Comment by deathbeam** [comment]
By the bug dissapearing you mean panel get's closed or the window get's resized to correct size with open panel?

**Comment by devLotto** [comment]
The window gets resized to the correct size

**Comment by Kamielvf** [comment]
I have this fixed in #708 but that PR will most likely not get merged, or at least not as it is right now.
