### ISSUE TITLE
Have the bank tag tab list take the swap/insert rearrange mode into account

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#7405]
Currently you can only swap the tags' places, but inserting would be way more practical for ordering.
![image](https://user-images.githubusercontent.com/34870401/51328126-faede780-1a72-11e9-883e-99747d694db2.png)
Letting go would make it so that tinderbox tab and mole tab would swap places, I'd like tinderbox be inserted above mole.

**Comment by raiyni** [comment]
It functions like the normal bank tabs

**Comment by JeljoGb** [comment]
Sure, but I'd like it to be better than Jagex's stuff. Like most Runelite stuff is better than Jagex stuff.
