### ISSUE TITLE
Cannot open Runelite anymore

### ISSUE THREAD

**Issue by AMB111** [runelite/runelite#7407]
hey guys,

i searched the recent posts but didnt find any bug reports about this problem.

I started runelite after the update and everything was fine. closed it and came back 30 minutes ago and now it doesnt  open again. it stays at 0% and cancels after a few seconds. while it tries to load everything else i have open is freezing but the CPU usage and everything looks fine. i cannot explain it..

any solutions to this? anyone else experience this? I use the 64bit version since i can think and never had problems!

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client
