### ISSUE TITLE
Double G.E. Notifications

### ISSUE THREAD

**Issue by hillj17** [runelite/runelite#7409]
**Describe the bug**
Since the latest update, whenever I get an update on my G.E. with a notification, I get my previous notification, then my new one.

**To Reproduce**
1. Sell multiple items on the ge
2. Get update notification
3. Get second update notification, but see first one again

**Expected behavior**
It should only show the current notification

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.8
 - Launcher version: 1.6.0

**Comment by deathbeam** [comment]
Any more info? This was working just fine for loong time and was not changed

**Comment by Nightfirecat** [comment]
Given that it has been over a year since the last post here, I am closing this issue. If you re-encounter this bug or have more information, please re-open this issue.
