### ISSUE TITLE
Levels to next combat are not correct for most skills

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#7411]
Related to #7103 and its fix.

https://i.imgur.com/nGLPrL6.png

This is with the following stats, and should be the same result with 2 prayer levels to level, not 0:

* 70 attack
* 74 hp
* 66 defense
* 69 magic
* 60 prayer
* 70 range
* 76 strength

**Comment by Nightfirecat** [comment]
Updated title as I found during working on this issue that the range/magic to next level are also incorrect for some accounts.

**Comment by lund8619** [comment]
@Nightfirecat, Which calculator were you checked against when you noticed this? I've hand checked the stats above, and they appear to be correct except for prayer.

https://oldschool.tools/calculators/combat-level < correct
https://oldschool.runescape.wiki/w/Calculator:Combat_level < incorrect
