### ISSUE TITLE
Outline Text on Ground Items (toggle-able)

### ISSUE THREAD

**Issue by Meme-Wizard** [runelite/runelite#7419]
It's sometimes a bit tedious having to scope out ground items when the text blends into the background of the game. Now I know jack about coding or runelite's infrastructure, but I assume adding the ability to add a sharp outline around text for ground items isn't too far of a stretch when it comes to the capability of this client. I was thinking a similar feature to whatever this client is (see pic)
![](https://i.gyazo.com/46b9338d030f933c974e7211969a71bf.png)
Would that be a possibility? It was be a great feature and would make collecting pked items/pvm drops a lot nicer on the eyes : )

**Comment by ermalsh** [comment]
Done, preview:
https://gyazo.com/0a266a8bc734bcfb798ca1bfde8f2e44

**Comment by gregg1494** [comment]
#7421 non toggle-able option

**Comment by ermalsh** [comment]
> I would probably prefer new font for this, because it might be useful for other overlays too? Adding this just for ground items as toggle is very silly.

I tried this, and believe it or not it looked pretty good on the other overlays rather than just ground items. Should I make the changes or should we wait on more feedback?

**Comment by Meme-Wizard** [comment]
> > I would probably prefer new font for this, because it might be useful for other overlays too? Adding this just for ground items as toggle is very silly.
> 
> I tried this, and believe it or not it looked pretty good on the other overlays rather than just ground items. Should I make the changes or should we wait on more feedback?

I mean it's worth a shot, i'm curious how it would look to be honest in different fonts and overlays.

**Comment by deathbeam** [comment]
Imo it would look pretty good on other dynamic overlays, like player names etc

**Comment by ermalsh** [comment]
Player names pop out more - I like it. Also, check out the items text when I hover over it in my inventory. 
Check this out:
https://gyazo.com/d783e90492641651a2ac54f2286ed3af
