### ISSUE TITLE
Farming Timers are Incorrect

### ISSUE THREAD

**Issue by fraserprice** [runelite/runelite#7424]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Farm timers are offset by about 10 minutes (i.e. predict plant growth 10 mins too early). When farm ticks were "fixed" about a year ago, growth windows shifted slightly.

Here is an image exemplifying the issue: https://i.imgur.com/xif9Sfg.png
Blue rectangles are predicted windows (old system); white dots are the correct growth windows. Note that this is the case for ALL growth window lengths. This means plants with longer times between growth windows are also affected.

**To Reproduce**
1. Plant any herb/plant with longer time between growth windows
2. Predicted finish time is always wrong

Screenshot of plants being predicted done despite not being finished: https://i.gyazo.com/db83aaf6046747c5b1ade949e372c8c4.jpg

**Expected behavior**
Correct time expected; about 10 minutes should be added to a number of plants

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows and MacOS
 - RuneLite version: 1.5.8
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Abextm** [comment]
d7aecb257cc83c6c8b4f8b693c7d3b73b6a1b98e should make this occur less often, but the root cause of this is not fixable with our current knowledge
