### ISSUE TITLE
Add current farming growth tick progress to patch timers

### ISSUE THREAD

**Issue by Alfie94** [runelite/runelite#7434]
**Is your feature request related to a problem? Please describe.**
Unclear what numbers the green bars on the patch timers represent.

**Describe the solution you'd like**
A simple "x/y" piece of text for each patch. Where x is the current growth tick progress, and y is the completed growth tick.

**Describe alternatives you've considered**
Casting geomancy spell and using wiki

**Comment by deathbeam** [comment]
This makes no sense. We have issue for geomancy spell update
