### ISSUE TITLE
Hiding Status Bars when out of combat!

### ISSUE THREAD

**Issue by SirBenvil** [runelite/runelite#7436]
Is your feature request related to a problem?:
Not quite, more so inconvenience. 

Describe the solution you'd like:
A toggle that would make the status bars disappear automatically out of combat after X amount of seconds!

Describe alternatives you've considered:
The only alternative would be to go manually toggle the entire plugin constantly, depending on whether I'm doing skilling or combat activities. 

Additional context:
Whilst this is a bit of a first world problem, I do feel these big bright bars are a bit intrusive when I'm just skilling. How intrusive they are will depend on interface settings, but when using the "Bottom Line" setting with the collapsed rocks, they do feel a bit in your face.

**Comment by ermalsh** [comment]
Something like this? (without toggle)
https://gyazo.com/bcd61045320b7d4d6fa4ac2e031ba0bb

**Comment by SirBenvil** [comment]
To this day I still really want this option to be a reality, but if getting it to the main Runelite client is proving to be a challenge, could it perhaps be considered for the Plugin Hub?
