### ISSUE TITLE
No Sound For Notification On Linux

### ISSUE THREAD

**Issue by Retalak** [runelite/runelite#7437]
My notifications for the client are not making any sound even though I have "Enable sound on notifications" checked. I have tried disabling enable tray notifications, and just about every other option related to notifications. I have alsa and pulseaudio and the client is not muted anywhere. I can hear in game sounds just fine (music, sound effects, area sound effects).

**Comment by deathbeam** [comment]
We already have issue for this

**Comment by Retalak** [comment]
I'm sorry I'm having trouble finding the duplicate, could I get a link please?

**Comment by deathbeam** [comment]
Oh hmm I guess we dont. Well, the sound on notification does system beep, so make sure that is working for you (you can probably try it from console running the `beep` command). Otherwise just setup your notification daemon to send sounds on notification, basic stuff.

**Comment by bowerscd** [comment]
For anyone looking at this years later, Retalak's solution still works. 

The default notification sound is under ` /usr/share/sounds/Oxygen-Sys-App-Error.ogg`.

**Comment by Retalak** [comment]
Coming back to this because it is now an issue on Pipewire and the original fix I posted is Pulse specific.
