### ISSUE TITLE
WASD Keys Stuck

### ISSUE THREAD

**Issue by Drummerz** [runelite/runelite#7438]
One of the WASD keys will seemingly get stuck during gameplay. Smashing all those keys repeatedly eventually gets the one key unstuck. Happens every 5 min or so and I do not have mousekeys or sticky keys on. Happens on both of my computers as well.

**Comment by Whired** [comment]
It seems like this issue is tied to load screens / map loading

It's hard to purposefully reproduce, but my best luck is spamming WASD during a load screen - eventually one of them gets stuck

**Comment by ryanleonard1** [comment]
Can confirm I'm having this issue as well, if I'm rotating the camera at the same time a new section of the map loads, the key stays 'stuck down', I have to press it again to fix it.

I can reliably reproduce this by holding A or D to spin the camera, then tele to a different section of the map and just watch the camera spin.

**Comment by Adam-** [comment]
I think this is specifically due to depressing a key when the client is loading a map.

**Comment by Adam-** [comment]
Fixed in f57abb7a7c09ec5504a8aa6a262c1045d52e3e2f
