### ISSUE TITLE
Timer plugin area bound

### ISSUE THREAD

**Issue by Athemoe** [runelite/runelite#7442]
Instead of sorting timer tab per patch, it would be nice to have an option to switch to area.
So instead of having a tab for hops, trees, fruit trees, maybe have tabs for Brimhaven, Catherby or Farming guild.

**Comment by Power27** [comment]
To add to this, it would be better to be able to customise the farming plug, so you can remove groups and create your own groups.
This way you don't have to click into each section to see if all your most planted patches are done?

**Comment by deathbeam** [comment]
We have issue for custom categories
