### ISSUE TITLE
Recolorable Quest/Music list text for color blindness

### ISSUE THREAD

**Issue by Rizyq** [runelite/runelite#7443]
**Is your feature request related to a problem? Please describe.**
Being red-green colorblind (deuteranopia) it's very difficult to notice the difference between completed and not started (green and red) quests. 

**Describe the solution you'd like**
The ability to recolor the text in the quest and music tabs as one would like. Options for "Completed," "In-Progress," and "Not Started." Possibly separate options for the music tab as well for "Unlocked" and "Locked" songs. 

**Describe alternatives you've considered**
Possibly some sort of highlight or overlay on/around the incomplete quests/songs. Maybe some sort of icon before or after the quest/song names indicating they are incomplete.  

**Additional context**
![image](https://user-images.githubusercontent.com/46845510/51428610-a150fe80-1bd3-11e9-98ee-538c996961cb.png)

The picture shows all 3 states of a quest in the log. Personally I can see the difference between the green (complete) and yellow (in-progress) quite easily/quickly. The difference between the green and red (not started) is a lot less noticeable, especially when scrolling through the quest/music list looking for incompleted/not unlocked quests and music.

**Comment by ShaunDreclin** [comment]
Was this not resolved by the vanilla update? I remember this being changed a while back

**Comment by Nightfirecat** [comment]
I'm inclined to say this would be better to ask Jagex to address. A vast majority of the userbase would not find such a feature useful.

**Comment by Rizyq** [comment]
Something like 8% of men are red-green colorblind, so it's a sizable minority.

Regardless, the recent update to the Quest List plugin added filters based on quest completion, which resolves that issue. #8473 asks for the same features to be added to the Music Player which would completely solve my colorblind issues. Not really familiar with GitHub etiquette but I guess I should close this since it seems to be being resolved elsewhere.
