### ISSUE TITLE
Anti-Venom shows wrong time left

### ISSUE THREAD

**Issue by Nic-Grunklee** [runelite/runelite#7446]
**Describe the bug**
See title

**To Reproduce**
1. Sip anti-venom(normal)
2. See wrong time on overlay(shows 12:00 minutes)

**Expected behavior**
Only should be 1:00 minute on timer

**Environment (please complete the following information):**
 - OS: macOS 10.14
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Comment by gregg1494** [comment]
Nope it is wrong based on what the anti venom plus is showing. So I will fix change it to 1 min

**Comment by gregg1494** [comment]
Fixed
#7453

**Comment by deathbeam** [comment]
Fixed in #7453
