### ISSUE TITLE
Ranged exp tracker not working correctly with wyrms while killing them with blowpipe

### ISSUE THREAD

**Issue by erikmukk** [runelite/runelite#7452]
**Describe the bug**
When I am killing wyrms with blowpipe, it seems like kills remaining/"actions" is calculated by every exp drop, not per kill.

**To Reproduce**
1. Go to wyrms
2. Click on a wyrm to kill it with BLOWPIPE
3. Keep your eye on ranged exp tracker

**Expected behavior**
"Actions" is supposed to decrease by each kill, but it does not do so
**Screenshots**
https://gyazo.com/90c98be09cd4dc195f2e1b7fc2511d1f

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: [1.5.8]
 - Launcher version: [1.6.0]

**Additional context**
---

**Comment by Nightfirecat** [comment]
This is probably because we don't have HP data for these enemies entered yet.

**Comment by deathbeam** [comment]
This is working as intended, when we dont have HP data we fall back to actions
