### ISSUE TITLE
Custom Skybox Colour

### ISSUE THREAD

**Issue by lucastimothy** [runelite/runelite#7458]
This may or may not have been requested already, but the option to modify the global skybox colour would be great under settings for "Skybox". I understand the skybox changes colours between locations but by default, it's black. So this option would recolour the black original skybox to a custom coloured one. This would obviously exclude you from using the already implemented version of Skybox with custom colours varying by location; it'd be a choice between default (black), skybox (dynamic), and skybox (custom).

**Comment by deathbeam** [comment]
It is intentionally not configurable because its different everywhere and i dont think making the "base" color configurable is good idea

**Comment by lucastimothy** [comment]
Why not make it so that the code for making the skyboxes dynamic exists while simply changing the colour for every region the same? Either a custom colour or at least manually code the black skybox to be the exact colour of gray outlining the client as an option. 

tld;dr

essentially same code as dynamic skybox the same colour id for every region, either custom colour or "Runelite" gray to blend into the client.
