### ISSUE TITLE
"Tag-All" option for "NPC Indicators"

### ISSUE THREAD

**Issue by scuttlegun** [runelite/runelite#7459]
I use npc indicators very often for killing random monsters. Right now my best way to highlight them as a group is to manually add their name to the "NPCs to highlight" box inside the plugin's settings, which works exactly how I want it but can get a little cumbersome to edit. My request is for an additional shift+right-click option to tag (and untag) all npcs with the same name, also ideally adding it to that same list so that it tracks across sessions

**Comment by deathbeam** [comment]
Just write the name down, it is not that hard.
