### ISSUE TITLE
Optional short price notation for ground items

### ISSUE THREAD

**Issue by Umdlye** [runelite/runelite#7461]
Ground item text can get unnecessarily long when you're already aware that the price on the left is GE value and the one on the right is HA value. An option for a shorter price notation would reduce screen clutter:

`(EX: 477K gp) (HA: 43.2K gp)` becomes
`[477K | 43.2K]` or
`[477K|43.2K]`

and

`(EX: 1,545 gp) (HA: 60 gp)` becomes
`[1,545 | 60]` or
`[1,545|60]`

**Comment by deathbeam** [comment]
You can already simply disable GE or HA value

**Comment by Umdlye** [comment]
How does that help when I want to keep seeing both prices?

**Comment by deathbeam** [comment]
You want less clutter, you have many options to do so already.

**Comment by Umdlye** [comment]
That's missing the point a bit but I suppose it's a bit of a niche case anyway. Cheers.
