### ISSUE TITLE
Plugin for chatting 

### ISSUE THREAD

**Issue by Mattjones171** [runelite/runelite#7463]
So basically what I am pitching here is a plugin that shows me who can see my chat in the proximity.

When I am at GWD standing outside the door, I would like to know if I am wasting my time asking people if they're almost done or not. 

Or when I am having a conversation with someone, I would like to know if I am getting too far away for them to see my chat.

**Comment by Adam-** [comment]
I don't think we have a reliable way of figuring this out.
