### ISSUE TITLE
CTRL-backspace only deleting after pressing CTRL again

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#7466]
Somewhat related to #6929

When I type text, and then press CTRL-backspace, I have to press CTRL again to actually delete it. Here is a video:
https://youtu.be/OZdYhdm4TG0

Win10 1809
RuneLite version 1.5.8
Launcher version unknown
(unknown as in this:)
![image](https://user-images.githubusercontent.com/9074448/51443672-d13ff500-1cec-11e9-858a-99eaaf64cf83.png)

**Comment by Nightfirecat** [comment]
I've noticed a similar, but possibly different issue where after pressing <kbd>ctrl</kbd> + <kbd>Backspace</kbd>, only the first character is deleted, and only after pressing it a second time (that is, press control, press backspace, release backspace, press backspace a second time without having released control) does it actually delete the full text.
