### ISSUE TITLE
Kill until level issue

### ISSUE THREAD

**Issue by angona2** [runelite/runelite#7469]
Hello,

When on the controlled attack style the kill count until level for strength, defense, and attack are showing 1/3 the value they are supposed to be. So if on controlled att/str/def, just simply multiply the calculated value for kill to level by 3.

I was going to submit a change into github but for whatever reason I could not find the source code for this specific calculation; I will keep looking but figured this would be faster for someone already familiar with the package.

Regards,
Jake

**Comment by Nightfirecat** [comment]
Duplicate of #6479
