### ISSUE TITLE
Loot tracker does not save loot with multiple clients open

### ISSUE THREAD

**Issue by Follmer** [runelite/runelite#7474]
**Describe the bug**
If playing with multiple accounts, i.e. main and ironman, if using the loot tracker for one of the accounts, the loot will not be reloaded when the client is opened again.

**To Reproduce**
1. Log in to two accounts (2 clients)
2. Enable loot tracker
3. Kill npc giving loot (in my case, barrows)
4. Close clients (order does not seem to effect this)
5. Reopen clients
6. See that no loot is shown in either client

**Expected behavior**
Loot should be shown when the client sees that you have logged into the game under the same username that the loot was previously saved to

**Screenshots**

**Environment (please complete the following information):**
 - OS: Win 10
 - RuneLite version: 1.5.8
 - Launcher version: Unknown

**Additional context**

**Comment by deathbeam** [comment]
Are you logged in to RuneLite? (not to OSRS but to RuneLite account)

**Comment by Follmer** [comment]
I was not. However I've been trying to log into RuneLite and it brings me to the web page that says I successfully logged in, but the green arrow at the top of the client shows that I'm not logged in, and the info panel says I'm also not logged in. I'm going to try reinstalling to see if that fixes anything

**Comment by Follmer** [comment]
Doesn't seem to have changed anything unfortunately

**Comment by deathbeam** [comment]
For the loot tracker to work it requires you to be logged in to RuneLite and have the option to persist loot enabled. And then it will work. If you can't login to RL then it's different issue
