### ISSUE TITLE
Log in not logging in...

### ISSUE THREAD

**Issue by oceanq55** [runelite/runelite#7475]
**Describe the bug**
When I go to click on the log in button on runelite, it directs me to the "You have logged in successfully! You may now close this window". However, the log in icon is still green not red. Giving the message to still log in

**Expected behavior**
I expected the icon to turn red to indicate I'm logged in, and have my settings from my account to be applied to the game.

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: [e.g 1.4.6] or whatever is recent...
 - Launcher version: [e.g 1.5.2]

**Comment by Follmer** [comment]
I'm also seeing this. If I turn the account plugin off and then on, the green login icon turns red, however the info panel still says I'm logged out and it appears that none of my data is saved.

OS: Win 10
RuneLiter version: 1.5.8
Launcher verion: 1.6.0

**Comment by oceanq55** [comment]
After Follmer posted this I disabled the plug in and it seemed to turn red immediately, then logging off again. I still have the same problem with it not "logging in"

**Comment by Adam-** [comment]
This is working again now it is no longer the weekend. 63ca800ff7aeebea5c13a91dbd41d4f9c3cb68db should probably fix it by keeping us well under the websocket limits.
