### ISSUE TITLE
Suggestion: Further Customizable Idle Notifications

### ISSUE THREAD

**Issue by Braaxton** [runelite/runelite#7476]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

I would like to receive idle notifications for birdhouses while the client is both focused or unfocused but I would not like to receive combat or interaction notifications while the client is focused. It does not currently seem possible to get birdhouse notifications while focused without enabling all notifications coming through. 

**Describe the solution you'd like**

The ability to allow birdhouse notifications when focused, overriding runelite settings that prevent other notifications from going through while focused.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

I've considered adjusting the settings every time I choose an in game activity that would require me to do so, however, this would be a nice quality of life change that would prevent constant adjustment.

**Additional context**

**Comment by Th3yS33M3** [comment]
I would like to add another suggestion considering notifications, custom sound for every notification.
Ex. Health low = U can add own sound for it "lowhp.wav"
Ex2. Out of combat = "ooc.wav" etc. etc.

**Comment by deathbeam** [comment]
Notifications being configurable centrally is intentional and with current config system it will not be changed. But you should be fine with just having send notifs when focused enabled all the time. @Th3yS33M3 we have different issue for custom notification sound, what will not be per-plugin again.
