### ISSUE TITLE
Add monsters to ignore / hide in loot tracker

### ISSUE THREAD

**Issue by janholbrouck** [runelite/runelite#7482]
**Is your feature request related to a problem? Please describe.**
Whenever I use the loot tracker, and I kill irrelevant monsters (eg. Scavenger beasts in raids), all the loot of those monsters shows up in the loot tracker. When I reset the loot tracker and I kill another, it pops up again.

**Describe the solution you'd like**
I'd like an option in the loot tracker settings menu, where we can enter names of monsters that we do not want the loot to appear from, in the loot tracker.

**Describe alternatives you've considered**
You could right click a monster name in the loot tracker, and select "Add to ignore monster list of loot tracker" to add it to that list.

Both solutions could also be implemented.

You could also hide the monsters instead of putting them on ignore, like you can do with items.

**Comment by deathbeam** [comment]
Right click ignore on loot I believe

**Comment by janholbrouck** [comment]
I can only seem to do this with items, not with monsters. If I do it with items, the item would dissapear for all monsters. I'd like to be able to hide an entire monster, without having it hide the items that the hidden monster would drop in other monsters. I can only reset a monster, but that doesn't prevent it from showing up again the next time I kill it

**Comment by deathbeam** [comment]
Yes, it is only for items.

**Comment by DADtheMaggot** [comment]
Is this closed because it can't be done, or just because there isn't enough interest for it?

I feel that janholbrouck is right, it's rather obnoxious to have to disable every possible drop in order to not see a monster's loot, especially if you want to see any of those items when you get them from another monster.
