### ISSUE TITLE
Typo for Iasor on Special Patches Tab

### ISSUE THREAD

**Issue by stringsanbu** [runelite/runelite#7487]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When hovering over the anima patch on the Special Patches tab while having an Iasor planted, the hover text says "Iasro" instead of Iasor like intended.

**To Reproduce**
1. Plant an Iasor in the Anima Patch in the Farming Guild
2. Go to Special Patches tab on thje Time tracking section
3. Hover over the picture of the Anima patch

**Expected behavior**
Instead of "Iasro" it should say "Iasor"

**Screenshots**
https://imgur.com/a/gd44oYO
You can see it on the right below the hespori patch.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.8
 - Launcher version: Unknown

**Comment by Adam-** [comment]
Fixed in #7488
