### ISSUE TITLE
Pking tools?

### ISSUE THREAD

**Issue by ImCOTW** [runelite/runelite#7495]
Would it be possible to add pking plugins such as a freeze timer for your opponent once you freeze them? 

Example:

I Entangle my opponent so i little timer could be in the bottom corner of my screen showing me how long it is until their unfrozen also possible with the few game tick delay added in? 

I know another client has that function but i would much rather use runelite.

**Comment by Nightfirecat** [comment]
This is on our [Rejected or Rolled Back Features page](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features):

> **Not currently being considered**
>
? - Opponent freeze timers: Not supported by other reputable 3rd party clients, can be very powerful for pking (see #2011)
