### ISSUE TITLE
Login time plugin

### ISSUE THREAD

**Issue by offZills** [runelite/runelite#7498]
i guess it would be helpful and nice qol add-on to have a login timer plugin that shows you for how long have you been online, it will help people know how much time exactly they spent playing and also to avoid the 6 hours logout that people sometimes forget about,it may be cool if you can make it show in the report button too.

**Comment by steffenhauge** [comment]
This already exists under "Report button" -> Login timer

**Comment by offZills** [comment]
it is not there for me?? hello? o.O

**Comment by Spedwards** [comment]
Yes it is.

**Comment by steffenhauge** [comment]
Search for the "report button" plugin and go into its settings
