### ISSUE TITLE
Runelite doesn't work correctly with GDK_SCALE on Ubuntu

### ISSUE THREAD

**Issue by Bastani** [runelite/runelite#7504]
**Describe the bug**
Setting GDK_SCALE to a higher value (say **n**) while using the GPU plugin causes the game to only display on 1/**n**<sup>2</sup> of the window. Although where the game is interacted with still uses the whole window.

**To Reproduce**
1. Go to 'Command line and use the following command: export GDK_SCALE=2 && java -jar RuneLite.jar'
2. Enable 'GPU Plugin'

**Expected behavior**
Game should display on the entire window.

**Screenshots**
![Image](https://i.imgur.com/u4SMcXP.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.1 LTS
 - RuneLite version: 1.5.8
 - Launcher version: 1.6.1

**Comment by Espionage724** [comment]
Can confirm the same on Fedora Workstation 29 with GNOME (RuneLite 1.5.8, Launcher 1.6.1)

**Comment by deathbeam** [comment]
I dont think its even supposed to work. What Java version are you using?

**Comment by Bastani** [comment]
I believe this used to work fine and was only recently introduced seeing as it was used as a solution in a previous post: https://github.com/runelite/runelite/issues/2719.

I originally tested this on Java 8 until I updated to the latest version so I believe it's not related to the version of Java. 

I'd like to also mention the issue only occurs when using the GPU plugin and works fine otherwise.

**Comment by ChristiaanDev** [comment]
Same thing happens for me with GPU plugin on. Works absolutely fine without it on.

**Comment by deathbeam** [comment]
I completely forgot that we have issue open for this, but I have PR with fix (as I ran to this problem myself).
