### ISSUE TITLE
Add predicted death time to timers plugin if plant is diseased

### ISSUE THREAD

**Issue by cox34** [runelite/runelite#7511]
If a plant is diseased, the timer plugin will display "diseased". May I suggest it display something like "diseased (death at 12:00)"?

**Comment by deathbeam** [comment]
We cant possibly know when the disease started

**Comment by cox34** [comment]
AFAIK, it doesn't matter when the disease started. 

If a plant is diseased, it will die on the next growth tick. 

I'm asking for the time of the next growth tick for that diseased patch to be displayed in the timer plugin.
