### ISSUE TITLE
60 FPS Option Like Runeloader

### ISSUE THREAD

**Issue by cmonguys666** [runelite/runelite#7515]
If you know Runeloader, it's a client that it's pretty much garbage but it had an option for 60 fps, when you toggle it your fps would fly to the roof.

It was the only way I could play but now Runeloader is closed, can you guys add this, I know there is already a low detail option on RL but it doesn't do anything, for me at least.

**Comment by Hydrox6** [comment]
Duplicate of #6856

**Comment by nlruk** [comment]
Was this ever added?
