### ISSUE TITLE
Make FPS control plugin affect only game itself instead of plugins.

### ISSUE THREAD

**Issue by Puz3** [runelite/runelite#7517]
Hey guys i have a suggestion to make. At the moment, runelite's drawing performance (for example prayer flicking cyan line) is affected by fps plugin. Could you please create it so fps plugin lower game's fps instead of whole client?

For example, if i am using prayer flicking plugin and if i set my fps to 15 (potato pc) the prayer flicking line is affected by it too which makes prayer flicking impossible to prayer flick accurately. The line jumps by 10 px per second instead of going smoothly.

**Comment by deathbeam** [comment]
That is not how FPS limiting works
