### ISSUE TITLE
{Suggestion} Ability to toggle transparency of members skills in F2P

### ISSUE THREAD

**Issue by andyflynn1** [runelite/runelite#7527]
I think it should be a toggle feature in interface settings. Reason being; the skills have never been faded out like that and if there's options for 2005 and 2009 interfaces, you should also be able to have a checkbox to not fade out members skills. Most of the F2P people using this feature probably have members accounts anyways and know which skills are which.

**Comment by deathbeam** [comment]
This was implemented by jagex and is better behaviour than before
