### ISSUE TITLE
Export Collection log as JSON

### ISSUE THREAD

**Issue by gc** [runelite/runelite#7529]
Suggestion: Allow us to export our Collection Log as a JSON file so it can be consumed by websites/services. For example, there are many websites which track how many items you have, mostly for ironmen, these websites could use the JSON file to automatically fill in your details. RuneLite might open up explorer (on windows) asking where you want to save it, or just save it to your RuneLite user directory.

It could be a plugin that's enabled, and when enabled - it shows as an "Export" button in the collection log GUI, OR a right click menu option on the collection log book item (which is probably better, and more unobtrusive)

Some consideration should be given (e.g. chaos ele pet appears in 3 separate pages) to make it structured well, and that all the data is included,

**Comment by deathbeam** [comment]
This would be probably on website and not in client after website integration will be finished

**Comment by gc** [comment]
Are you saying the ability to export the collection log as JSON is a planned feature for the website?

**Comment by gc** [comment]
Alright, can we re-open this as a suggestion for the website as you mentioned? Also, why is it definitely not something for the client?

**Comment by deathbeam** [comment]
Feel free to open it there. Because client is loading just subset of data and so you would just export that small subset of data what will be pointless
