### ISSUE TITLE
Prayer window is broken

### ISSUE THREAD

**Issue by renivate** [runelite/runelite#7531]
After the update this morning, the prayer window was oddly ordered, missing Augury, and is now not working at all (upon trying to enable reordering)
Check screenshot below:
http://prntscr.com/mbicbl

**Comment by willnotcy** [comment]
Disable prayer reordering and restart the client

**Comment by sklirg** [comment]
@Adam-, did 8e650e06588eb9e940416a675a34f26719718a6c fix this issue? If so I guess it can be closed?
