### ISSUE TITLE
Add farming guild redwood to idle notifier

### ISSUE THREAD

**Issue by chrees** [runelite/runelite#7532]

**Comment by Alexsuperfly** [comment]
What exactly is this asking for, how does idle notifier have anything to do with a location?

**Comment by Nightfirecat** [comment]
![2019-08-03_14-19-06](https://user-images.githubusercontent.com/2199511/62416991-66289100-b634-11e9-90b5-e21ff3f47c29.png)

This animation is the same one as usual, so it already works as intended.
