### ISSUE TITLE
!Request Add a plugin that hides the "bury" option of bones

### ISSUE THREAD

**Issue by LukaMrkonjic** [runelite/runelite#7540]
Hey guys!

I would love to see this plugin happen. As a 1 def pure I am scared of miss-clicking at times, especially during quests. This would be awesome.

Please make my day!

**Comment by deathbeam** [comment]
We already have this, in menu entry swapper plugin. Enjoy rest of your day!

**Comment by LukaMrkonjic** [comment]
> We already have this, in menu entry swapper plugin. Enjoy rest of your day!

OMG, this is awesome. Thank you so much! Been looking for it.
