### ISSUE TITLE
You Are Fishing in fishing plugin is not working

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#755]
In recent update Jagex changed the names of the fishing spots, so it's not only "Fishing Spot" anymore, so plugin cannot detect if you are fishing anymore. Probably replacing .equals with .contains in the FishingOverlay would do it.

**Comment by devinfrench** [comment]
It depends on the location from what I've seen. Both action and names have changed.

![](https://i.imgur.com/XGCjTFj.png)

**Comment by deathbeam** [comment]
Yeah, f.e. also at Infernal Eels, it's changed too.
