### ISSUE TITLE
Config values don't update until a different field gets focused

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#756]
The UI should either make it clear that the new value isn't actually set, or update it immediately. Handling ⏎ keypresses might also be nice here

**Comment by sethtroll** [comment]
This can be done using
`textField.getDocument().addDocumentListener(new DocumentListener()
{
	@Override
	public void insertUpdate(DocumentEvent e)
	{
		textChanged();
	}

	@Override
	public void removeUpdate(DocumentEvent e)
	{
		textChanged();
	}

	@Override
	public void changedUpdate(DocumentEvent e)
	{
		textChanged();
	}

	private void textChanged()
	{
		changeConfiguration(textField, cd, cid);
		textField.setToolTipText(textField.getText());
	}
});`

The downside being that the event/config is set everytime you type a letter.

**Comment by deathbeam** [comment]
This was solved with support for saving the values on ENTER
