### ISSUE TITLE
Slayer target highlighting no longer works on Desert Lizards

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#7565]
This was caused by the Desert Lizards task being changed to just Lizards with the addition of Sulphur Lizards.

**Comment by KC3BZU** [comment]
I'm seeing this bug as well. I also noticed that killing Desert Lizards and Small Lizards don't cause the kill count to update.

**Comment by dekvall** [comment]
I believe this was fixed by 6c56880989a72143a8e670729d3e6f2fbd318682
