### ISSUE TITLE
Idle notifier timeout applies to Prayer and HP alerts

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#757]
This seems kinda silly, when there's already a threshold check. I care about when my HP/Prayer dips below the threshold *immediately*, not "for at least 5 seconds", even if I only care about being out of combat if it's for more than 5 seconds. If someone's got their timeout up high enough, this could probably even get them killed.

**Comment by deathbeam** [comment]
It's not really silly, the timeouts are mostly there if you notice it yourself, and eat/drink pray pot, so the notifcation like that do not fires immediately. Because that can be annoying as well. So both cases are valid, maybe having separate timeout for animation idle and combat idles would work.

**Comment by deathbeam** [comment]
Based on discord discussion the "timeout" for the HP/pray can be just solved by setting the threshold to lower number.
