### ISSUE TITLE
Ground Item Sort by Value

### ISSUE THREAD

**Issue by alexpixler** [runelite/runelite#7575]
It's annoying when high value items are hidden at the bottom of ground item stacks. For example, runescape gives the option to pick up oysters before giving the option to pick up gems. I also often see fremmenik rings hidden at the bottom of pk loot stacks. This is for both left-clicking on a pile of ground items as well as right-clicking a pile of items and opening the ground item menu. 

Ground item stacks should show the highest value items first - for both directing picking off the ground and within the ground item menu.
![image](https://user-images.githubusercontent.com/14062225/51789938-f77dee80-214b-11e9-87bd-a2422575807b.png)

**Comment by CreativeTechGuy** [comment]
@deathbeam would you not accept a PR for this? Is there a fundamental reason this shouldn't be an option? I came across this issue looking for the same feature.
