### ISSUE TITLE
Loot not syncing properly

### ISSUE THREAD

**Issue by MildPanda** [runelite/runelite#7579]
This has happened to me multiple times and I'm surprised nobody else has said a thing about it so perhaps I am doing something wrong. 

When I close and reopen my client it seems to pull old data from my loot tracker. What I have been doing is resetting all of my kills on my loot tracker so I am only tracking my vorkath kills (even resetting vorkath loot if there are any so I can see all from this play time) but when I go to close the client and reopen it later all of the NPCs I had reset are back and no vorkath kills are even displayed.

I am signed in and I do have save loot checked https://i.imgur.com/KOb6xNh.png

Edit: Now it's just refusing to even save my loot. I had tried doing this with my 20 vorkath kills but hit abort instead of stop so here is an example with 1 goblin kill https://gfycat.com/MeatyPleasedIndianpalmsquirrel I have no idea if this could possibly be a thing related to my storage being full on that gmail account but just to take blame off that if there may be any it says 9GB out of 17GB on my gmail

**Comment by Adam-** [comment]
Fixed in d228add898137be850ccc41f9ccbe15f51f8d0ff
