### ISSUE TITLE
Late 2006 early 2007 interface style

### ISSUE THREAD

**Issue by Espio419** [runelite/runelite#7581]
Title. Found the images on Google.
![1486223369302](https://user-images.githubusercontent.com/12127034/51794559-59b60e00-21a3-11e9-944c-ed0a8ec38758.jpg)

**Comment by Alexsuperfly** [comment]
turn on the interface styles plugin

**Comment by Alexsuperfly** [comment]
i fail to see the difference

**Comment by RobertCurll** [comment]
> i fail to see the difference

https://runescape.wiki/images/b/b9/2005_Easter_event_old.png?cc9e5
the icons of the inventory, skills ect.
