### ISSUE TITLE
How do I remove the arrow near the minimap?

### ISSUE THREAD

**Issue by zanderb21** [runelite/runelite#7583]
Hello I recentely started playing again and I notice every time I move my mouse to the minimap an arrow appears to remove the runelite stuff on the side. How can I change this button backto how it used to be a few months ago? I could not find the option for it if it exists at all.

I find it extremely distracting thanks.

**Comment by Lucwousin** [comment]
I don't think you can disable it but it's only there when you don't use the custom window chrome, so disabling the custom window chrome would get rid of it.

**Comment by zanderb21** [comment]
Thanks for the reply, but I had already discovered this and I used the windows border because I didnt like the custom one... If a developer from runelite reads this, please add a toggle for this arrow button, thanks.

**Comment by Alexsuperfly** [comment]
you cant get rid of it otherwise there would be no way to toggle the sidebar buttons

**Comment by deathbeam** [comment]
You cant, it auto-hides
