### ISSUE TITLE
NPC block color

### ISSUE THREAD

**Issue by KingNefarious** [runelite/runelite#7586]
**Is your feature request related to a problem? Please describe.**
It's not a problem as such, however, I have pretty bad eyesight (rip me) and I play super zoomed out on Runescape (always played like this on MMOs for whatever reason). But I struggle seeing just the outline of an NPC and was wondering whether there was a way to make it a block color? Even if it's not pushed to the client update, any assistance on what I should edit in the Runelite files would really help me out (I've got it set up in IntelliJ.

**Describe the solution you'd like**
Option or a way to make it a block color opposed to it being outlined.

**Describe alternatives you've considered**
None.

**Additional context**
My eyesight sucks and I play zoomed out (obviously like making life difficult for myself).

**Comment by deathbeam** [comment]
You can probably just use more contrasting color. or tile highlighting. I dont think we have method that just draws square around model in client, but you can look at the convex hull implementation and just alter it in your fork.
