### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by padilhozo** [runelite/runelite#7587]
bring runelite to front when idle notifications pop up? Is that possible guys? 
I think is pretty useful!

**Comment by Alexsuperfly** [comment]
I feel like you're looking for the `request focus on notification` feature which is already located in the "RuneLite" config area.

**Comment by padilhozo** [comment]
I cant fins, where is ?

**Comment by ShaunDreclin** [comment]
![screenshot](https://user-images.githubusercontent.com/5851433/51808781-48820580-2266-11e9-8bb1-f2aba5c79d52.png)

Also in future when you make a suggestion, you should write a descriptive title so people can get the gist of what you're suggesting without having to read the whole thing

**Comment by Hydrox6** [comment]
This is also the kind of problem that's perfect for the [Discord server](https://discord.gg/mePCs8U)
