### ISSUE TITLE
The client is lagging

### ISSUE THREAD

**Issue by Mantas4682** [runelite/runelite#759]
Probably the only problem is my end. All I'm currently in possession of is a very crappy laptop, no time to really play anything anyway. Wanted to catch up for when mobile comes out. Saw your client pop up, it looked super nice and clean, said it was lightweight too, so I wanted to try it out. It's laggy, even with all plugins off, though I can run the original client perfectly well and OSB runs almost good with half the plugins enabled. Am I doing something wrong or maybe something can be tweaked? I apologize if this does sound dumb, as I'm the one with a crappy laptop and an upgrade would fix everything, but I can't justify buying anything of that sort at the moment.

**Comment by Kamielvf** [comment]
I've only heard one person before you having issues with the client "lagging", and he said it was only happening with the install version of the client. Try downloading the .jar ([Download for all platforms](https://runelite.net/)) and running that.

**Comment by Adam-** [comment]
I do not think that they will have a different behavior anymore since the launcher was updated to use the same parameters as the jar.

**Comment by deathbeam** [comment]
What was the laginnes? Was it occasional freezes or just being slow in general? Best would be if you could provide some .GIF showing the issue, with ::displayfps turned on as well.

**Comment by Mantas4682** [comment]
@Kamielvf I've tried that.

@deathbeam It's slow in general. Sub-par fps and what feels like stuttering when running.

**Comment by Mantas4682** [comment]
Haha, sure.

Intel Celeron CPU B800
4GB RAM
Intel HD Graphics

Wasn't kidding when I said it was bad. Can't wait for mobile.

**Comment by deathbeam** [comment]
This was most likely solved with having the abillity to configure the hardware acceleration mode. Reopen if issue is still present.
