### ISSUE TITLE
Screen Marker color tied to Action

### ISSUE THREAD

**Issue by rowlanddeep** [runelite/runelite#7590]
**Is your feature request related to a problem? Please describe.**
When I'm Barbarian Fishing I rely on the Fishing Overlay to tell me when I'm not fishing so that I can pay attention to other things, but the "Fishing"/"NOT Fishing" text is very easy to miss when it changes.

**Describe the solution you'd like**
I would like to be able to setup a semi-transparent screen marker that is tied to whether an action is being done so that I can make a big box on the screen that is a transparent red when NOT Fishing and a transparent bright green when I am Fishing. 

**Describe alternatives you've considered**
I haven't thought of any tbh.

**Additional context**
N/A

**Comment by deathbeam** [comment]
You can just setup idle notifier.
