### ISSUE TITLE
[Suggestion] Add a way to disable game chat completely.

### ISSUE THREAD

**Issue by zlokquay** [runelite/runelite#7594]
Title.

To expand, a way to right click the game chat button below the chat box to disable game chat. Already exists for Public/Private/Clan/Trade.

If anyone is willing to help me learn I wouldn't mind some mentoring to work on the task together.

**Comment by zlokquay** [comment]
Can you tell me how I can do this then?

**Comment by deathbeam** [comment]
You can right click each chat and disable it or make it filtered (for game chat)

**Comment by zlokquay** [comment]
Yeah I want more than filtering game chat.
