### ISSUE TITLE
Customizable text for NPC chatboxes

### ISSUE THREAD

**Issue by Zooka128** [runelite/runelite#7595]
**Is your feature request related to a problem? Please describe.**
When I'm sat about ~1m away from my computer screen, the text in the NPC chatboxes is really hard to read, because it looks like it's black with white parts.

**Describe the solution you'd like**
Ability to change the colour of the NPC chatbox and/or chatbox text. Also possibility to make the NPC chatbox font bold.

**Describe alternatives you've considered**
Making the chatbox transparent could be an alternative, and the text white could work, as the current transparent textbox with white writing is very visible.

**Additional context**

**Comment by deathbeam** [comment]
You can just use stretched mode to enlarge it if you are having problems to read it. I don't think we want to add any customization for the chat popups as 1. it will probably not work correctly 2. it is unnecessary.
