### ISSUE TITLE
Chat Notifications plugin doesn't work on messages with colour changes

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#7596]
![screenshot](https://user-images.githubusercontent.com/5851433/51817515-07571900-2299-11e9-9109-4985e5ad389e.png)
^For example, trying to highlight `slayer faster. It then crumbles` doesn't work.

Probably related to #7371

**Comment by Alexsuperfly** [comment]
this is caused by the `.` at the end of the "highlighted word" which does not fufill the regex of an ending `\b` in the plugin

**Comment by Alexsuperfly** [comment]
OK, its been pointed out that the "word" extends further than the period I just didn't catch that in my initial read through so my previous comment is incorrect for this case. 🙃

**Comment by Alexsuperfly** [comment]
8988226d1cbe5de8c40adfb49ba6dd08214e4b9c reintroduced this

**Comment by Adam-** [comment]
fixed in 58c5017ae91fcde536a141e74f4eb405dea50b5b
