### ISSUE TITLE
Mage training arena telekenetic maze bug

### ISSUE THREAD

**Issue by XueSosBlyat** [runelite/runelite#7601]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Mage Training Area Telekenetic Maze doesnt solve the maze.
it doesnt do anything at all, and I remember in my older account when I used to grind for bones to peaches that was really helpful and now it is not working at all.

**Expected behavior**
should have put an arrow on the floor exactly when to run and cast the spell.

 - OS: Windows
 - RuneLite version: 159

**Comment by deathbeam** [comment]
Its already solved, will be fixed next update

**Comment by XueSosBlyat** [comment]
> be

when next update? and thank you for fast answer.

**Comment by deathbeam** [comment]
Same as every update, thursday
