### ISSUE TITLE
Show total Nightmare Zone points

### ISSUE THREAD

**Issue by sadegr** [runelite/runelite#7607]
When inside a Nightmare Zone dream (session) both the vanilla client Nightmare Zone interface and Runelite's Nightmare Zone plugin show the number of Nightmare Zone points earned within the dream you're currently in, but not the total points (i.e. points you had before you entered the dream + points earned during the current dream). This is inconvenient because it may take multiple dreams to get the number of points needed to imbue something, in which case you have to remember how many points you had before you entered the dream in order to know when you have earned enough points rather than being able to see it in the interface.

Would it be possible to show the total number of Nightmare Zone points in the Nightmare Zone plugin's overlay, in addition to the number of points earned just in the current dream already shown?

**Comment by jmm140330** [comment]
#6701

**Comment by jmm140330** [comment]
#6701
