### ISSUE TITLE
Medium Emote Clue Blue Snail Helmet

### ISSUE THREAD

**Issue by Trobosko** [runelite/runelite#7618]
**Describe the bug**
For the Emote Clue helper it tells you that you need a bruised blue snelm, a staff of air and a bronze sq shield. In reality, you need a pointed blue snelm and not a bruised one. Sort of a big deal for iron man who don't have the easiest access to this stuff and can be annoying if you depended on the runelite plug in.

**Comment by RyBo** [comment]
It looks like there's pointed and round but they're both [bruised blue snelms](https://oldschool.runescape.wiki/w/Bruise_blue_snelm) regardless. I'm guessing for this emote they're always going to be pointed?

**Comment by Nightfirecat** [comment]
A pointed blue snelm is what it calls for, yes: https://github.com/runelite/runelite/blob/eb69a8990b4127f20ca99f4e79e2fa9d17eb2219/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/EmoteClue.java#L118

**Comment by Nightfirecat** [comment]
I concur, bruise blue snelm with ID 3343 seems to be the pointed one already: https://www.osrsbox.com/tools/item-search/

**Comment by xDemoN** [comment]
@Nightfirecat could this be cheated using any() with only 1 item?

For example:

`any("Bruised Blue Snelm (Pointed)", item(BRUISE_BLUE_SNELM_3343))`
