### ISSUE TITLE
Add 'Search for traps' to the menu entity swapper for Nature Rune chest.

### ISSUE THREAD

**Issue by Kevinclon** [runelite/runelite#7622]
**Is your feature request related to a problem? Please describe.**

When camping the Nature Rune Chest it is currently possible to thieve from the chest with no mouse movement. Just double click every 15 seconds. When using a side laptop this is quite easy, to do while working, however, if using the computer you are playing Runescape on it becomes more challenging.

**Describe the solution you'd like**
Switch the left click option from "Open" to "Search for traps"

**Describe alternatives you've considered**
Moving the camera into the perfect angle, then putting a box on the screen to denote where to double click. This works. However, it is tedious.

**Additional context**
Posting on the discord and got a response that it might conflict with 
"Rejected feature:
Pickpocket on non-H.A.M. members: Not supported by other 3rd party clients, and absurdly powerful when blackjacking."

I believe it does not because:
This forbids pickpocketing, This is not pickpocketing, and the chest cannot move.
Also, it is possible to set up a similar effect on the vanilla game.

Note* I can/will implement this myself as it is trivial just need to know if it's allowed.

**Comment by Nightfirecat** [comment]
We discussed this in discord earlier. We're unlikely to implement this swap as it's not available on any other reputable client.

**Comment by Kevinclon** [comment]
I fail to see how that is a logical reason to exclude something. 
It would mean nothing new would come about.

**Comment by Nightfirecat** [comment]
Sorry you feel that way, but the logic of "this menu entry swap isn't allowed" doesn't lead to "RuneLite can't/won't implement novel features first". You need only compare our changelog to that of other clients to see that. Nevertheless, I would recommend discussing this with the project admins and/or regular contributors on discord if you feel strongly that this is an acceptable feature to add.

**Comment by Kevinclon** [comment]
The logic of "this menu entry swap isn't allowed" doesn't lead to "RuneLite can't/won't implement novel features first.

Correct, and stop trying to make it seem like I presented that.

The logic that would lead to that is the logic you raiyni put forth, and you defended here. That "Does OSB do it? if no then we probably won't do it."

I'm not saying there isn't a good reason not to implement it, I'm saying that I haven't seen one, and the defense that you give of "We're unlikely to implement this swap as it's not available on any other reputable client." Either is incorrect or leads to a client that doesn't push out many of its own updates. As you so gleefully pointed out you only have to look at the differences between runelite and others changelogs to see that runelite pushes out many updates, so the only other logical option is that the reason given is wrong.

**Comment by deathbeam** [comment]
If you can already achieve this on vanilla client then I dont see why this should be implement. Also, looks like this was discussed in Discord, and our other menu entry swaps are mostly just qol, but this is requesting something that will trivialize the setup you need to do in game before using this method, so its not good idea.
