### ISSUE TITLE
Add separate .txt files for hidden and highlighted items

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [runelite/runelite#763]
A way to add items in 2 separated files, Where for example only the items in file names Show.txt will highlight the items you did add in that file while a different file disables highlighting for the items which are added to it would also make it easier for users to share their files

**Comment by deathbeam** [comment]
I would say this is solved with config text-areas as I guess that was the primary reason of people being annoyed with how it worked back when this issue was created.

Closing for now, reopen if you really feel like this is still necessary.
