### ISSUE TITLE
MTA Telekinetic Theatre plugin not working?

### ISSUE THREAD

**Issue by xGeneriicxNamex** [runelite/runelite#7630]
Is anyone else having any issues with the plugin or know a fix? I've tried going in and out of the room multiple times, restarting client, reinstalling client and restarting pc.

![461b0ebf7e78921436ba594e191d1940](https://user-images.githubusercontent.com/47193322/52010049-962d9500-2528-11e9-9662-546deb8f5ae8.png)

**Comment by deathbeam** [comment]
It will be fixed tomorrow
