### ISSUE TITLE
Stat debuffs break indicators

### ISSUE THREAD

**Issue by NewGuy274** [runelite/runelite#7632]
SO I posted about this before but not in the greatest detail. I did say what I knew but now I know at least a bit more. It seems anything that makes my stats go down breaks all indicators. It first happened when going to GWD for a clue and when going back to pvm none of my boost information would show up nor timers or even cluescroll locations on the map. I had to reload my client to fix this. That happened a couple times always involving GWD and happened to a friend. Today it happened when KBD used it's stat debuff on me. If I turn off "display as indicators" I can see the boost information, but timers and clues on map still don't work.

EDIT: It seems signing in with a google account makes it not happen.

**To Reproduce**
Go to KBD or GWD and let your stats be hit down while boosted with display as indicators on.

**Expected behavior**
No indicators till work. Timers, boost info, clues on map, etc.

**Screenshots**
https://imgur.com/a/4YQ3Pdq

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.9
 - Launcher version: Not really sure how to check...latest I guess?

**Comment by deathbeam** [comment]
This was most likely already fixed. After release today can you rechek if this issue is still happening? as i am like 99% sure it will be solved and not happen again after that. And can you maybe also provide logs?

**Comment by Nightfirecat** [comment]
@NewGuy274 Can you confirm whether this is still an issue? As db said, this is likely fixed now.

**Comment by Nightfirecat** [comment]
Closing as this did not receive any further information.
