### ISSUE TITLE
Ground item value seperation

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [runelite/runelite#764]
Would be cool to have a "," separate bills,mills,k's and normal gps so for example

1B,1M,200K,400

![2018-03-02_01-42-33](https://user-images.githubusercontent.com/17284305/36877766-bb85d29a-1db3-11e8-95a0-2542485f5933.png)

**Comment by ShaunDreclin** [comment]
Should follow the same pattern stacks of items in game use.

1 - 99,999
100k-9999k
10m-9999m

**Comment by SomeoneWithAnInternetConnection** [comment]
I think this was fixed by #788

**Comment by Adam-** [comment]
I think this is invalid. Dropped stacks can't be over 65535.

**Comment by SomeoneWithAnInternetConnection** [comment]
I figured the numbers > 65535 were in reference to the monetary value, not the number of items on the ground

**Comment by Adam-** [comment]
Oh. In that case yes it was fixed in #788
