### ISSUE TITLE
Export bank or bank tabs as CSV with GE and alch prices

### ISSUE THREAD

**Issue by ryanleonard1** [runelite/runelite#7644]
**Is your feature request related to a problem? Please describe.**
No, it would be a nice to have, would make it easy to calculate stored exp and to locate/calculate high value items in Excel.

**Describe the solution you'd like**
Click an 'export' button under a bank export plugin while the bank window is open and save a .csv file in the runelite data folders (alongside screenshots folder)
May require you to scroll through the bank to load all items into the client (not sure how the bank interface works).

It would be nice to have the following columns:
Item ID, Item Name, Quantity, GE Average, Alch Price

**Describe alternatives you've considered**
Not aware of any alternate methods of this.

**Comment by jmm140330** [comment]
Got the plugin complete as far as compiling the list, just got to write to file and polish it to meet standards.

**Comment by deathbeam** [comment]
Why? You can already export bank tags with right click export. And then you can look up GE/HA price online. And in meantime someone also made PR, I guess I should've closed this sooner.
