### ISSUE TITLE
Add "Tag" option as default to right-click context menu without Shift key

### ISSUE THREAD

**Issue by CayrelStarZer0** [runelite/runelite#7648]
**Is your feature request related to a problem? Please describe.**
It's frustrating to click "Shift" in order for NPC Tag option to be added to right-click context menu, especially because nowhere in the tool itself or the tooltips does it say that "Shift" needs to be pressed.

**Describe the solution you'd like**
Add an option to add "Tag" to right-click menu by default, without the need to press or hold "Shift" key.

**Comment by deathbeam** [comment]
This cant really be done because then it makes the option left-click on some NPC
