### ISSUE TITLE
Add a !bank command to show your current bank value in chat.

### ISSUE THREAD

**Issue by 07Arab** [runelite/runelite#7667]
Basically just a request to add a !bank command to show current bank value in chat, similar to the !kc command that displays monster kills. I assume this wouldn't be too hard of a request since there is already the "Bank Value" plugin that displays the bank value information already.

**Pros for a "!bank" command:**
- Easily and quickly obtain information of your current bank value, for the requests of others. 📚 
- Not have to try and prove your bank with screenshots/videos that could show things you don't wanna show? 
- Flexing gp will make others cry maybe if they are poor, or have an opposite effect of making players want to improve their banks by playing the game more to prove to the world they don't live in the shitty looking shed in Lumbridge swamp. 

**Cons for a "!bank" command:**
- Flexing gp will make others cry maybe if they are poor, or have an opposite effect of making players want to improve their banks by playing the game more to prove to the world they don't live in the shitty looking shed in Lumbridge swamp. 
- Not much else I think. 🤷‍♂️

**Comment by deathbeam** [comment]
This command is not something other clients have and also it is kind of pointless to have command for this in first place, it provides no value to literally anyone.
