### ISSUE TITLE
Add amount to level to fishing/wcing plugin

### ISSUE THREAD

**Issue by fairyfoam48** [runelite/runelite#7670]
The fishing and woodcutting plugin show fish caught and logs cut and also shows fish/logs per hour. 1 more statistic that could be added is "Fish/lvl" or "Logs/lvl" and the number can be figured out by taking the fish you're catching dividing the xp to lvl but the xp the fish gives, same for logs.

**Comment by deathbeam** [comment]
Just use the XP tracker sidebar and actions left there
