### ISSUE TITLE
Game freezes in GPU mode

### ISSUE THREAD

**Issue by zanderb21** [runelite/runelite#7684]
**Describe the bug**
The game freezes randomly when I was fishing, or running to ardougne. Also happens almost everytime the first time I login after booting my computer. Runelite still works but only the game it self freezes.

**To Reproduce**
1. Turn on GPU mode
2. Log in my account
3. play the game

**Expected behavior**
No freeze

**Screenshots**

**Environment (please complete the following information):**
 - OS: windows 10
 - RuneLite version: 1.5.10
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by zanderb21** [comment]
found the solution

**Comment by btaluy** [comment]
@zanderb21 Could you please elaborate what your solution was?

**Comment by zanderb21** [comment]
I fixed it by using the official client instead of a custom one with broken plugins
