### ISSUE TITLE
Add High Gamble Count for Barbarian Assault

### ISSUE THREAD

**Issue by rlw0014** [runelite/runelite#7691]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to show off my high gamble count in public chat.

**Describe the solution you'd like**
!gc (for gamble count) => Barbarian Assault High-level gambles: 9001

So the only places we could grab this information is from:
1) Adventurer Log in PoH(in counters)
2) Collection Log Book Minigames tab
3) Doing a High-level gamble
**Additional context**
![55c16c7d4a 1](https://user-images.githubusercontent.com/38933102/52183404-a61dd100-27d5-11e9-992c-ce010210f208.gif)
![9ff5ddce5a 1](https://user-images.githubusercontent.com/38933102/52183428-debdaa80-27d5-11e9-9353-85d3d2cf17c7.png)
![cf9e24981b 1](https://user-images.githubusercontent.com/38933102/52183520-8dfa8180-27d6-11e9-9758-711722636d81.png)

**Comment by Aukk** [comment]
Why wasnt this added ?

**Comment by TheFuries** [comment]
Wow! This feature would be a prodigious help! Why wasnt it added yet!

**Comment by kschmanski** [comment]
I could have sworn I saw this in a PR months ago.  I'd be happy to work on it

**Comment by Adam-** [comment]
Things get lost. There's no reason it can't be added. I'll look at #7706 this morning.

**Comment by Adam-** [comment]
Added in #7706
