### ISSUE TITLE
Unable to build 1.5.11-SNAPSHOT

### ISSUE THREAD

**Issue by acory32590** [runelite/runelite#7698]
IntelliJ version - 2018.3.4
JRE/JDK version - 1.8.0_201

Issue: 

I am attempting to follow this guide in setup - https://github.com/runelite/runelite/wiki/Building-with-IntelliJ-IDEA

Confirmed that I have completed all of the above steps several times but the same issue persists.

In the runelite-client workspace, both WorldHopperPlugin.java and HiscorePlugin.java reference & use the library "org.apache.commons.lang3.ArrayUtils".  They both use the function "swap" which is only in version 3.5, see: https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/ArrayUtils.html

...However, the runelite-client POM doesn't even reference & pull this library.  And on the Building with IntelliJ walkthrough, when you are completing the Import Project step, I noticed the version was off (https://imgur.com/CbvxhAp) ... it's 3.4.

Any ideas as to what I can do to remedy this?  Or is this an issue with the latest snapshot?  I attempted to add a later version of the lang3 to the runelite-client POM to no avail:

```
<dependency>
  <groupId>org.apache.commons</groupId>
  <artifactId>commons-lang3</artifactId>
  <version>3.8.1</version>
</dependency>
```

Any other thoughts or suggestions are appreciated.

**Comment by Adam-** [comment]
Probably no, it is not possible. If you want to see what is pulling in dependencies, run `mvn dependency:tree`.

**Comment by deathbeam** [comment]
Everyone else can build the project so you should probably just fix your maven config
