### ISSUE TITLE
Add configurable shift-click withdraw options for bank items

### ISSUE THREAD

**Issue by v-d-x** [runelite/runelite#7700]
I find that I frequently either want to withdraw all of an item, in the form of banknotes or for seeds, or a small number of them (two potions, throwaway hammers for questing, that sort of thing). Being able to choose between two left click options would cover a lot of frequently used withdraw quantities I tend to use without having to mess with the tiny icons on the bottom of the bank. Plus, you could potentially use it to have shift-click releases on placeholders if you want to quickly get rid of a few quest items or slayer drops.  

The feature seems to have some base to build off of in the form of inventory item configurable shift-clicks, so I was hoping it might not be too hard to implement

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
