### ISSUE TITLE
When i run Runelite a see tiles with fire on them

### ISSUE THREAD

**Issue by masrourmouad** [runelite/runelite#7703]
When i run Runelite a see tiles with fire on them, i see the window the settings but the login screen is just in tiles, this bug is only on Runelite, other clients work well.
thanks

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by masrourmouad** [comment]
after disabling hardware acceleration still the same problem

**Comment by deathbeam** [comment]
You did not followed the guide properly then

**Comment by masrourmouad** [comment]
![capture d ecran_2019-02-04_15-20-08](https://user-images.githubusercontent.com/403487/52213858-8f888000-2890-11e9-8f39-e163699293cd.png)
![capture d ecran_2019-02-04_15-23-43](https://user-images.githubusercontent.com/403487/52213989-e726eb80-2890-11e9-995e-06f1f9295e06.png)

**Comment by deathbeam** [comment]
Then downgrade Java or something, we support only Java 8.

**Comment by masrourmouad** [comment]
thanks
