### ISSUE TITLE
something wrong here

### ISSUE THREAD

**Issue by masrourmouad** [runelite/runelite#7720]
![](https://user-images.githubusercontent.com/403487/52213989-e726eb80-2890-11e9-995e-06f1f9295e06.png)

Disabling Hardware Acceleration change nothing

**Comment by Nightfirecat** [comment]
Graphical artifacts? Try disabling hardware acceleration: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by deathbeam** [comment]
Duplicate of #7703
