### ISSUE TITLE
Slayer Plugin: Flesh Crawler not recognized as target during task

### ISSUE THREAD

**Issue by yanikore** [runelite/runelite#7721]
**Describe the bug**
The Flesh Crawler does not get highlighted by the slayer plugin when the task is "fleshcrawlers"

**To Reproduce**
/

**Expected behavior**
The Flesh Crawler is highlighted

**Screenshots**
![image](https://user-images.githubusercontent.com/6956790/52299805-a7dac680-2986-11e9-9a74-f85fe4388e82.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.10
 - Launcher version: 1.6.0

**Comment by Alexsuperfly** [comment]
Seems to be that when the task is given Flesh Crawlers is a single word. 

![](https://i.imgur.com/N5a2lml.png)

**Comment by kschmanski** [comment]
Thinking of taking this one, is there a way to test this outside of getting a "Fleshcrawlers" task myself?

**Comment by Alexsuperfly** [comment]
unrestricted worlds infinite skips
