### ISSUE TITLE
Magic tree icon misplaced

### ISSUE THREAD

**Issue by Nachtmerrie** [runelite/runelite#7722]
**Describe the bug**
The icon should go down a bit

**Screenshots**
![image](https://user-images.githubusercontent.com/45820840/52305416-571e9a00-2995-11e9-8a64-5b390257dffe.png)

**Environment (please complete the following information):**
 - OS: Windows,
 - RuneLite version: 1.5.10

**Comment by Nachtmerrie** [comment]
👍  if that is the case then you can close this! Thank you.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/commit/12ae359876626c73d0a86ce39cab16d733dd788b yeah, looks like its here. It will be in next release.

**Comment by Joshua-F** [comment]
Yeah, was fixed in #7683
