### ISSUE TITLE
MLM Plugin - Nugget counter incorrect

### ISSUE THREAD

**Issue by robuhde** [runelite/runelite#7724]
When you are taking ores out of the sack, you can click a second time. If there is another golden nugget to be given to the player when there is already a stack in the inventory. e.g. I have 70 pay-dirts deposited, I just extracted 27 and received 2 golden nuggets. If I withdraw from the sack again and receive 2 more golden nuggets, the MLM plugin will then add 4 instead of an extra 2.

You can quickly re-create this, buy having any amount of golden nuggets in your inventory while you search the sack in MLM and it will add those whole amount.

Not sure if this is fixable but I imagine you can check if there are any in the player inventory prior to search then subtracting that from total to add to the overlay

**Comment by Alexsuperfly** [comment]
fixed in 640e0d291549d98d6a69820caed6f288f21cd89e
