### ISSUE TITLE
Add configuration for Status Bars plugin to change stats displayed

### ISSUE THREAD

**Issue by Yttrium-tYcLief** [runelite/runelite#7728]
**Is your feature request related to a problem? Please describe.**
I'd like to see the Status Bars plugin see more customization, so they can be used outside of combat or to players' preferences.

**Describe the solution you'd like**
Essentially, a refactor to show/hide icons, show/hide values, and change stats displayed for each bar. Things displayed could be hitpoints, prayer, special attack, run energy, or maybe even empty inventory %.

**Additional context**
I think these images show what I want pretty cleanly.

- [Before](https://i.imgur.com/Nq8Bb6O.png)
- [After](https://i.imgur.com/xh5rmX1.png)

Paging @Malfuryent since he added this plugin and is probably in the best state to fulfill this request.

**Comment by Malfuryent** [comment]
Yeah i could probably make some changes to support Run & Special values and to let the user choose himself which bar he wants left or right. I'll see if i have some time to tinker around with it.

But i would leave the colors of the bar just hardcoded into the client to keep everything familiar with the original colors of OSRS and to not overcomplicate the settings menu and keep the userexperience uniform for all users.

If i wanted to implement custom colors there would also need to be settings for custom Venom / Poision / Active run / Unactive run / Stamina affected run / active prayer etc.
This would get a little bit too crowded in my opinion.

**Comment by Yttrium-tYcLief** [comment]
>I'll see if i have some time to tinker around with it.
Awesome!

>This would get a little bit too crowded in my opinion.
That's fine. I do want to make sure the colors change based on the pre-programmed stat, though. I just don't want Run to be bright cyan.

**Comment by Malfuryent** [comment]
no hahaha, each stat would have their own colors, cyan run energy would look weird yes 👍

**Comment by Yttrium-tYcLief** [comment]
That PR looks perfect, feature-wise. Awesome stuff!

**Comment by supermxn** [comment]
could we add a goal level on the status bars? ex. if you set up a goal from 45 to 60 attack, you can see the progress on the status bar?

**Comment by Malfuryent** [comment]
@supermxn we have the xp orbs for that kind of feature. i'd like the statusbars to remain for combat related statusses.

**Comment by Yttrium-tYcLief** [comment]
Closing as this was integrated with 1165780f.
