### ISSUE TITLE
Highlight Agility Colors - add colors

### ISSUE THREAD

**Issue by aleenie478** [runelite/runelite#7734]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I see an agility shortcut highlighted but I can't actually use it. 

**Describe the solution you'd like**
Have it highlight a different color such as red if your agility is not high enough to use and the original green when you are able to use it. Then you can see right away if you can use it or not. Additionally, it might be nice to have the level requirement pop up with the text describing the shortcut. For example: "climb down spikey chain (61)" vs "climb down spikey chain" - what it currently says.

**Comment by Abextm** [comment]
Duplicate #3754
