### ISSUE TITLE
Command that prints the raids layout

### ISSUE THREAD

**Issue by WaltervonGabain** [runelite/runelite#7736]
After scouting for a raid I'd like it to have a !layout command so that my scouted raid gets shown in clan chat for my friends to see.

**Comment by deathbeam** [comment]
I think https://github.com/runelite/runelite/pull/7715 solves this?

**Comment by WaltervonGabain** [comment]
My bad, I'm glad it's already in the works!

**Comment by deathbeam** [comment]
Its not merged yet, so the issue is still valid
