### ISSUE TITLE
Brimstone key loot in loot tracker

### ISSUE THREAD

**Issue by fargoldbee** [runelite/runelite#7749]
**Is your feature request related to a problem? Please describe.**
The Brimstone keys don't appear in the loot tracker

**Describe the solution you'd like**
Make entries for each chest opened with the key.

**Comment by Dragon911XX** [comment]
I'd love to have something like Barrows tracker for brimstone. and the crystal key chest in taverly

**Comment by villagerapist** [comment]
Saving my keys for this release

**Comment by fargoldbee** [comment]
Same here

**Comment by rsslayerzz** [comment]
Anyone working on this? This would be awesome
