### ISSUE TITLE
Fishing plugin overlay randomly doesn't appear

### ISSUE THREAD

**Issue by MichaelUnce** [runelite/runelite#7750]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
fishing overlays stop working randomly

**To Reproduce**
No Clue

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Windows 10
![download 4](https://user-images.githubusercontent.com/45104546/52448373-b00b4100-2b01-11e9-89b5-3e08751bb29e.png)
]
 - RuneLite version: [e.g 1.5.11]
 - Launcher version: [e.g 1.6.0]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by nmq12** [comment]
Happened to me when I disconnected and reconnect shortly after while fishing.

**Comment by Adam-** [comment]
If someone can find concrete steps to reproduce this I'd appreciate it. I heard of this issue before the release but was never able to reproduce it myself.

**Comment by MichaelUnce** [comment]
Ive noticed it happening when im running to another spot that is out of view but i think its happened in my view as well

**Comment by MichaelUnce** [comment]
> If someone can find concrete steps to reproduce this I'd appreciate it. I heard of this issue before the release but was never able to reproduce it myself.

not sure if this helps maybe it might just be 1 fishing spot here?  [https://prnt.sc/mimuye](url)

**Comment by Zelxy** [comment]
I had this same issue, on the eastern most fishing spots at catherby.

**Comment by nrodriguesdev** [comment]
I noticed this issue while I was testing a fix for duplicate icons. Only thing I noticed was that the fishing spot had moved around the time that it happened.

This happened to me while I was analyzing barbarian rod fishing spots. Maybe it's related to rod fishing spots?

**Comment by Alexsuperfly** [comment]
This was just posted in the discord, may or may not prove useful. The poster said this as well "Every time my game lags it'll keep the tile up that I went to click on." and the gif shows that in action

https://gfycat.com/gracefulformalamericancurl

**Comment by Shawn-Smith** [comment]
I just had this issue, it happened when I got the second to last fish from a full inventory, after returning from the bank the tiles were properly highlighted again.

Shortly after returning from the bank 7 fish caught, the tile highlights have disappeared again. Not sure what caused it to happen either time. Both times I was fishing standing still, and the spot hadn't moved.

**Comment by Shawn-Smith** [comment]
I've had this issue again tonight, and I've reproduced it multiple times.

Nearly every time the screen loads while running to a fishing spot in Corsair Cove the fishing tile highlights disappear.

**Comment by MichaelUnce** [comment]
I thought this too but ive had it randomly happen while just at the same fishing spot


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Adam-** [comment]
Fixed in 0821cf216d43265188f4408be29e64f83bc6c286

**Comment by SouLPrisoner** [comment]
This usually happens to me after fishing for like 2-3 hours straight.

**Comment by matt-buckley** [comment]
This issue is currently appearing for me.
