### ISSUE TITLE
Party plugin build warnings

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#7753]
When building, the following warnings are generated for the http-api party user sync and party plugin tile ping classes:

> C:\runelite\http-api\src\main\java\net\runelite\http\api\ws\messages\party\UserSync.java
> Warning:(29, 1) java: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.
> C:\runelite\runelite-client\src\main\java\net\runelite\client\plugins\party\messages\TilePing.java
> Warning:(31, 1) java: Generating equals/hashCode implementation but without a call to superclass, even though this class does not extend java.lang.Object. If this is intentional, add '@EqualsAndHashCode(callSuper=false)' to your type.

**Comment by deathbeam** [comment]
Looks like simply adding `@EqualsAndHashCode(callSuper=true)` below Data/Value annotations there should work

**Comment by ksergio39** [comment]
Sent extra files that twinkiel0ver fixed the other day.
Resending pull request.

**Comment by NPittinger** [comment]
I've submitted a pull request adding the annotation to the affected classes.
