### ISSUE TITLE
Remove Demonic Gorillas Plugin

### ISSUE THREAD

**Issue by ScreeenSlaver** [runelite/runelite#7762]
With rejecting the vorkath and hydra plugins, and removing the jad and zulrah plugins, to remain consistent with the precedent we should remove also remove the demonics plugin. 

It offers an easier barrier of entry to what is supposed to be challenging content. This content is also one of the best solo money makers in the game.

**Comment by eioo** [comment]
If I remember correctly Jad and Zulrah plugins were removed by Jagex's request. Demonic gorilla plugin is still allowed.

I personally don't think it doesn't give too much of a handicap when killing them, you still need to focus a lot when doing them. Prices of Zenyte shards haven't dropped since the release of the plugin.

**Comment by Hydrox6** [comment]
Jad plugin wasn't removed at Jagex's request @eioo

**Comment by eioo** [comment]
> Jad plugin wasn't removed at Jagex's request @eioo

Thanks for the clarification (Here's a [discussion ](https://github.com/runelite/runelite/pull/6724) about it)

**Comment by ScreeenSlaver** [comment]
@eioo Exactly. You still need to focus a lot to kill them, except it makes the barrier of entry a lot easier. Why not just remove it to remain consistent.

Also the price of the rare shouldn't be factored into this, but since you brought it up; EVERYTHING went up due to inflation except zenyte jewelry. They stayed at 14mil for the longest time and finally shot up to 17mil recently. 

Again price is not relevant.

**Comment by GibsDev** [comment]
I do not think that any plugin should be removed unless it defies any requests by Jagex. An exception being a plugin that causes major bugs. If you don't want it to be there, it is a plugin, and it can be disabled. We can speculate about what is good or bad for the game as third party client users, but ultimately that responsibility falls on Jagex (who's rules we follow).

That being said I do have an opinion on this plugin specifically. I do not think that it makes gorillas significantly easier. After reading the wiki or watching a guide, anyone who can count to 3 can do gorillas without the plugin.

**Comment by jbaker5011** [comment]
Couldn't have said it any better myself than GibsDev already did to be honest. I really don't think that demonic gorrilas are intended to be challenging content at all. They probably just didn't want them to be completely AFKable

**Comment by ScreeenSlaver** [comment]
Right, so the plugin isn't needed and should be removed. @GibsDev

**Comment by eioo** [comment]
> Right, so the plugin isn't needed and should be removed. @GibsDev

_If you don't want it to be there, it is a plugin, and it can be disabled._

**Comment by ShaunDreclin** [comment]
I think removing the Jad plugin was unnecessary and removing this one would be too.

If jagex had an issue with it, they would have said so. They haven't, so why should we remove it?

**Comment by Adam-** [comment]
https://secure.runescape.com/m=news/a-message-about-unofficial-clients?oldschool=1

**Comment by ShaunDreclin** [comment]
*Now* it should be removed lol
