### ISSUE TITLE
Farming tree timer begins even if tree not planted

### ISSUE THREAD

**Issue by yamogi** [runelite/runelite#7772]
**Describe the bug**
I accidentally tried to plant a calquat seed into its tree patch (north of Tai Bwo Wannai) even though I didn't have the level 72 farming requirement. When I used the calquat sapling on the tree patch, the calquat farming timer started (i.e. it changed from "Unknown" to "Done at <time>") even though the sapling was never successfully planted.

**To Reproduce**
1. Go to the calquat tree patch, north of Tai Bwo Wannai. Have a calquat sapling with you. Be less than 72 farming.
2. Use the calquat sapling on the tree patch.
3. Observe that the timer believes the tree to have been planted, even though it failed due to the level requirement.

**Expected behavior**
The timer should remain as "Unknown".

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.11
 - Launcher version: 1.6.0

**Additional context**
I didn't test this on other tree patches that I don't have the level for, but I assume similar behaviour would be observed.

**Comment by Abextm** [comment]
this is fundamentally impossible as you have described

**Comment by yamogi** [comment]
![runelite_maznejw031](https://user-images.githubusercontent.com/2281879/52520791-74898780-2c65-11e9-90f8-b23309391f4b.png)

Not sure how this happened? Active calquat timer with only 55 farming. I'll wait until it's finished and try it again.

**Comment by Abextm** [comment]
thats not growing a calquat, that's growing weeds

**Comment by yamogi** [comment]
I'm a complete moron. Apologies.
