### ISSUE TITLE
Disable fake xp drops

### ISSUE THREAD

**Issue by robinwithes** [runelite/runelite#7775]
**Is your feature request related to a problem? Please describe.**
People have been asking jagex for months for a option to disable fake xp drops, the ones that occur when gaining xp in a skill that you already have 200m in. ([example](https://cdn.discordapp.com/attachments/509879178645209088/543881748623130654/unknown.png))

**Describe the solution you'd like**
A plugin or option to disable fake xp drops

**Comment by deathbeam** [comment]
https://twitter.com/JagexWolf/status/1100337130335887360
