### ISSUE TITLE
I get a BSOD or my laptop restarts after a few minutes of playing on RuneLite

### ISSUE THREAD

**Issue by dusanjosik** [runelite/runelite#7779]
Describe the bug
As the title states, my laptop gets a BSOD(blue screen of death) or just simply restarts after a few minutes of playing OSRS on RuneLite. It doesn't happen on my computer. Also, it only creates logs for the times when it doesn't crash(which happens occasionally). It has been like this for at least a month now. I tried updating my GPU driver(nvidia geforce 940mx 2gb gddr5), but it still didn't fix the problem.
It doesn't happen in any particular locations.

Environment:
 - OS: [Windows]
 - RuneLite version: [1.5.11]
 - Launcher version: [1.6.0]

**Comment by eioo** [comment]
Windows version? GPU driver version? Other hardware?

**Comment by dusanjosik** [comment]
It is Windows 10. Since I updated my GPU drivers 2 or 3 days ago I assume they are the latest. I have 8gb DDR4 ram and intel i3-6100u.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration try this also we already have similar issue open
