### ISSUE TITLE
Configure shift click doesn't work on "bananas (1)" on MacBook

### ISSUE THREAD

**Issue by WizardMascot** [runelite/runelite#7797]
**Describe the bug**
So, as you know you can configure shift click. This works so well and makes a lot of things easier, however on "bananas (1)" it does not work.  It does work on bananas (5) - (4) - (3) - (2), but unfortunately not on (1)

Apparently this does work on Windows, but not on Mac. So if you guys could please, look into this, that would be much appreciated. 

Kind regards

**Comment by deathbeam** [comment]
I am pretty sure there is no difference between shift-click on windows and mac, so this looks like user error.
