### ISSUE TITLE
GroundItems breaks after opening bank interface in certain areas

### ISSUE THREAD

**Issue by abelbriggs1** [runelite/runelite#78]
The most notable example is the Gnome Stronghold bank near Nieve. If you drop an item, open the bank, and close it, the overlay will no longer show up anywhere.

I've done some investigation and haven't found the cause yet. Widget.isHidden() seems to be working correctly - it may have something to do with the plane/region requests, but the overlay still works in Lumbridge Castle (2nd floor) bank, which makes me think it's not related to your level/floor on the map.

I'd appreciate if someone else could try looking into this as well.

**Comment by tylerthardy** [comment]
Resolved with merge from #160
