### ISSUE TITLE
Ge Feature request

### ISSUE THREAD

**Issue by DynamicDeveloper** [runelite/runelite#7806]
Is there any way of a feature for the grand exchange plugin, say hold shift and set a threshold of say 200Gp +- guide or below, press shift and say have 6 items for 6 empty slots, hold shift and able to send them all to the GE? by clicking each item?

Or would such feature be calssed as OP?

thanks

**Comment by deathbeam** [comment]
We cant do this no

**Comment by SevenEightFour** [comment]
The "threshold of 200gp +/- guide price" feature would not be possible, for the same reason that a GE offer of that kind is not possible in the official client. GE offers must have an exact price. To sell within an acceptable range you must make one offer, wait to see if it sells, cancel it and make a new offer with a different price. There is no way around through client-side code.

The suggestion of shift-clicking to quickly list an item in one action, while possible, would probably be considered macroing or botting, as it would be automating a series of actions into a single action. That series being: "select item to sell, select quantity to sell, select sale price, confirm offer" It also wouldn't even be as conveinient as you hope, as each offer isn't actually listed until Jagex's GE server verifies it, which will take a noticable amount of time regardless of how quick you make the client-side interactions required to offer an item for sale.
