### ISSUE TITLE
Change medium clue Captain Tobias answer back from 6 to 7

### ISSUE THREAD

**Issue by AverageHumanoid** [runelite/runelite#7808]
Revert #7764

https://twitter.com/OldSchoolRS/status/1095016176013508608

**Comment by AverageHumanoid** [comment]
Not sure about the last part of the tweet, "The Corsairs already found there will move to Rimmington" if that includes their ship as well so maybe keep answer as is until after update.

**Comment by Hydrox6** [comment]
Yeah it's sounding like they're moving a different ship out of Port Sarim at the same time

**Comment by fiestapants** [comment]
As of 02/13/2019 21:48 CST the answer is still 6 ships. I got the answer "7" from the runelite plugin and kept getting it wrong until I realized Veos had moved.
