### ISSUE TITLE
Make ALT hotkey customizable

### ISSUE THREAD

**Issue by xpownx** [runelite/runelite#7831]
Using alt click to move camera, when you do this, for ground items that are hidden they reappear. Same goes with moving the minimap/total exp ect...

Would be nice to have a plugin which could change the buttons so instead of using alt u could use ctrl.

**Comment by LlemonDuck** [comment]
Done in 43e8a57cadc232c151c002cbfe5a7e4dd95e8b53 for ground items and 4f4c502b1796ca70c3830ee7e563b8b4e16a8037 for widgets
