### ISSUE TITLE
Can't open Runelite

### ISSUE THREAD

**Issue by sgbdoe** [runelite/runelite#7837]
I'm not very knowledgeable about computer-related things, so bear with me. I recently moved states, and I can't get Runelite to open at my new place. When I click the RL icon, the bar that pops up loads all the way, disappears, and then the client never opens. I'm not sure what is happening or how I can fix it. Any suggestions are welcome, thanks.

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by sgbdoe** [comment]
I can't find any of the "client not launching" problems in my launch log. Mine says "unable to download artifacts."

**Comment by Alexsuperfly** [comment]
this discussion is better suited to the discord if you could join that and use the #support channel
