### ISSUE TITLE
Slayer plugin tracking unrestricted worlds

### ISSUE THREAD

**Issue by TheStonedTurtle** [runelite/runelite#7839]
Slayer plugin is tracking points/task in unrestricted worlds and overwriting the real game data.

![https://i.imgur.com/IRF1OCX.png](https://i.imgur.com/IRF1OCX.png)

**Comment by ShaunDreclin** [comment]
This is also an issue for deadman worlds, and for playing on multiple characters.

Do we have a way of saving character-specific configs?

**Comment by Adam-** [comment]
This probably has not been a problem for awhile, ever since we migrated storage of the pts/streak to rsprofile.
