### ISSUE TITLE
Screenshots from Unrestricted/Beta Worlds are put into the screenshot folder for Normal Accounts

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#7840]
Notably this happens with boss kill screenshots.

Similar to #2050

**Comment by NPittinger** [comment]
Sorry for the mess! I'm still rather new at this. 😅

**Comment by yanikore** [comment]
MAybe add the date to the filename?

**Comment by Nightfirecat** [comment]
Screenshots being overwritten has been fixed in #4374. That said, these screenshots are still filed into the wrong screenshot folder so this issue is still valid.

**Comment by Nightfirecat** [comment]
Fixed in #13631
