### ISSUE TITLE
Make agility lap counter count towards "target level" instead of "next level"

### ISSUE THREAD

**Issue by Lorentary** [runelite/runelite#7844]
I guess the title is pretty on point. It would be nice to have an option in the pluggin that counts lap until you reach the target agility level set in the experience tracker

Alternatively the "Actions Left" in the experience tracker pluggin could show laps left when on an agility course

The reason I think this would be appreciated is that you generally do not care about when you will get from 75 to 76. Rather, you are interested in when you can move to the next course or when you reach level 99 (or 200M)

**Comment by ddaltonzkd** [comment]
If it's still open/available, I would like to work on this issue.

**Comment by deathbeam** [comment]
The best way (and only way I would personally accept this change) to make this work is to intergrate it with XP tracker first (and I already have PR for that) so I don't think working on this without doing that is good idea.

**Comment by ddaltonzkd** [comment]
No problem, if there are any issues that could use some attention I would still be very interested in contributing.

**Comment by AndreasBoegh** [comment]
This issue seems to be resolved

**Comment by Nightfirecat** [comment]
Looks like this was added in 030a052ea179c2331e074b93dccf4a6a0509eba0
