### ISSUE TITLE
Alchchemical Hydra Slayer Boss Attack Counter

### ISSUE THREAD

**Issue by DewFPS** [runelite/runelite#7849]
Just like the Demonic Gorilla plugin. Have it count the attacks of the Hydra's Range and mage attacks. Every 3 attacks it switches to range or magic.

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by DewFPS** [comment]
Aww okay
