### ISSUE TITLE
Auto-completion of name when looking up player on highscore

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#785]
Have the name be "highlighted" when you start typing so you can simply press enter instead of having to type out the full name.
Logical names to autocomplete would be nearby players, the players in your cc/friends list, and players you have previously looked up. Incompatibilities between names, like the lookup autocompleting "Tom" to "Tom1337" when trying to look up "Tom", could be resolved by having the first backspace turn off the auto-completion.

**Comment by pettenge** [comment]
I'm going to have a go at implementing this.

**Comment by Adam-** [comment]
Added in #2528

**Comment by Kyle-Newton** [comment]
This got broken in the recent update

**Comment by Juzzed** [comment]
double click the magnifying glass

**Comment by Nightfirecat** [comment]
@Kyle-Newton And it will be fixed in the next update; the fix has already been merged: #3247
