### ISSUE TITLE
Hidden auto retaliate messes with the special attack bar

### ISSUE THREAD

**Issue by Tiadeche** [runelite/runelite#7851]
**Describe the bug**
When hiding the auto retaliate button and then use the special attack button, the special attack bar freezes (stays visually full). https://i.imgur.com/p2deOkD.png 

Also, when enabling the "hide auto retaliate" option for the first time, the special attack bar was removed completely. Turning "hide auto retaliate" off and back on fixes this issue, but the visuals of the special attack bar do not change unless the "Hide auto retaliate button" is turned off-on.

**To Reproduce**
Steps to reproduce the behaviour:
-Hide auto retaliate button in the attack styles plugin (spec bar disappears if turned on for the first time)
-Use special attack (e.g. dragon axe special attack)
-Watch the special attack bar (the % left will not change)

**Expected behaviour**
The special attack bar should visually represent the % of the special attack power left. 

**Environment:**

* RuneLite version: [e.g 1.5.12]

**Comment by NPittinger** [comment]
The AttackStyles plugin doesn't seem to be checking `VarPlayer.SPECIAL_ATTACK_ENABLED`.

**Comment by Mabel5** [comment]
The issue is the special attack widget listeners are attached to the text widget for auto-retaliate.

**Comment by Tiadeche** [comment]
So is there a way to fix this? :)

**Comment by deathbeam** [comment]
For now dont use the auto-retalliate hiding :)

**Comment by Tiadeche** [comment]
Alright

**Comment by Adam-** [comment]
@Mabel5 do you know specifically which listener on which widget is responsible for it?
