### ISSUE TITLE
Wiki skill lookup

### ISSUE THREAD

**Issue by Truesh00ter** [runelite/runelite#7852]
See: https://github.com/runelite/runelite/pull/6708

**Is your feature request related to a problem? Please describe.**
N/a.

**Describe the solution you'd like**
Since we now have the wiki links and shortcuts, I would like to request the same for the skills.
Right click a skill, show a option like the quest guides and redirect to the skill page. 

**Describe alternatives you've considered**
N/a.

**Additional context**
![image](https://user-images.githubusercontent.com/17280249/52799878-fe2cc100-307a-11e9-954b-4c40e42124ed.png)

**Comment by InfinitySamurai** [comment]
I would be interested in picking this one up, however I will need to set my computer up for Java development and the project... that might take a while
