### ISSUE TITLE
Cannot select items in bank for wiki lookup

### ISSUE THREAD

**Issue by MarkKoz** [runelite/runelite#7854]
**Describe the bug**
Items in the bank cannot be targeted for wiki lookup.

**To Reproduce**
1. Enable the wiki plugin.
2. Open the bank.
3. Click on the `Lookup Wiki` option on the wiki button under the minimap.
4. Click on any item in the bank.
5. Observe that nothing happened.

**Expected behavior**
The item in the bank would be selected and then a web page for the wiki would open up showing the article for the selected item. Basically, it would work exactly like the lookup feature works on items in the inventory.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.12
 - Launcher version: 1.6.0

**Comment by InfinitySamurai** [comment]
Similarly, if you have the Grand Exchange open you can't lookup items in your backpack
