### ISSUE TITLE
Allow users to move the kick option from the clan chat

### ISSUE THREAD

**Issue by Newbiekilla** [runelite/runelite#7868]
Currently, as soon as your get to a rank that you can kick people from a CC the kick option replaces the hop-to option, this means that lots of new admins in chats end up kicking people they want to hop to, would it be possible to allow users to move this to the bottom option still allowing people to kick from the clan chat, but also removes the risk of kicking people from the cc.

**Comment by ShaunDreclin** [comment]
Would this go in the menu entry swapper plugin or the clan chat plugin?

**Comment by Newbiekilla** [comment]
I thin menu entry swapper

**Comment by Nightfirecat** [comment]
I feel this would be better implemented by forcing a right-click menu like #3380

**Comment by Hydrox6** [comment]
Current behaviour is to have the menu forced open on when kick is the top option, so this isn't a problem anymore
