### ISSUE TITLE
Convex hull of npcs drifts away from their model on slopes

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#7872]
Noticed this when I was on a slayer task on White Wolf Mountain, the wolves standing on slopes had their target highlight offset. The steeper the slope, the bigger the offset.

![screenshot](https://user-images.githubusercontent.com/5851433/52888592-5383d380-314a-11e9-984a-8c9fa61d4e1c.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.13-SNAPSHOT
 - Launcher version: Unknown

**Comment by deathbeam** [comment]
Did you also tried clicking the NPC?

**Comment by ShaunDreclin** [comment]
Just checked, the clickable area stays where it should be around the model. Only the overlay moves.

Also just tried with NPC Indicators plugin, same issue. (expected ofc but thought I should test it)

![screenshot](https://user-images.githubusercontent.com/5851433/52891237-c47db800-3157-11e9-92ea-dc50d4bdbabf.png)

**Comment by ccarpenter04** [comment]
I've also confirmed the same results.

**Comment by ShaunDreclin** [comment]
It's happening when I mark the stash object too.

![Screenshot](https://user-images.githubusercontent.com/5851433/55195608-74950680-5183-11e9-9567-d371611da001.png)
