### ISSUE TITLE
Friends chat bubbles

### ISSUE THREAD

**Issue by redturtlez** [runelite/runelite#7885]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
Im always frustrated when i press tab while talking to friends and i respond to the wrong person or it gets cut off.
**Describe the solution you'd like**
chat head bubbles replacing bubbles on bottom for "game, public, private, clan, trade" as the friend name and a chat filtering to only show their messages
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
not sure how tab will react when using this tool, may need an alternativate to work around it
**Additional context**

**Comment by Hydrox6** [comment]
Looks like #6875 will fix this
