### ISSUE TITLE
Left click pickpocket in HAM Store Rooms

### ISSUE THREAD

**Issue by pesoaek** [runelite/runelite#7890]
**Is your feature request related to a problem? Please describe.**

Expanding on the menu entry swapper, it would be a huge QOL for HAM Store Rooms

**Describe the solution you'd like**

Make left click pickpocket on the guards

**Describe alternatives you've considered**
n/a

**Additional context**

Common way to make money on low level ironman accounts etc.

**Comment by deathbeam** [comment]
Duplicate of #3693
