### ISSUE TITLE
Reorder store options.

### ISSUE THREAD

**Issue by jnac91** [runelite/runelite#7894]
I can't find anything directly addressing stores for this. Is it possible to enable or add something to allow you to enable the reordering of store menus?

For example, when you click an item in a fishing store you value the items. Right click gives you the options to buy 1, 5, 10 etc. I'd like to be able to have left click be buy one, if possible. 

Thanks in advance for any info.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
