### ISSUE TITLE
Weird grid-like graphics bug

### ISSUE THREAD

**Issue by DongVGH** [runelite/runelite#7901]
I'm trying to run RuneLite on Puppy Linux Xenial, with JRE 8 update 144 installed. When opening RuneLite on this system all i get is this: https://ibb.co/t8J4S5j

I suppose it may help if i mention that this same system also runs BloodGDX and Minecraft, so i don't think it's the Java install.

**Comment by Hydrox6** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
