### ISSUE TITLE
bank value on first (all) tab

### ISSUE THREAD

**Issue by Vokuar** [runelite/runelite#7907]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**
in addition to total bank value the bank value of the first tab 

**Describe alternatives you've considered**
having both numbers at the top or toggable in the bank tabs plugin 

**Additional context**
![image](https://user-images.githubusercontent.com/23405516/52942583-f771b700-33b6-11e9-8529-ac230a0cdd6b.png)
![image](https://i.imgur.com/bqokIsF.png)
as you can see theres 264k value in the first tab (all tab)

also i believe its similar to #6995
i think that was misunderstood
i hope this gives more clarifcation

**Comment by deathbeam** [comment]
This is same thing as #6995 , and no it was not misunderstood. first tab is whole bank
