### ISSUE TITLE
GPU plugin crazy display

### ISSUE THREAD

**Issue by 12kcvorki** [runelite/runelite#7917]
**Describe the bug**
Huge graphics bugs when I turn on the GPU plugin: https://imgur.com/a/E57yKBj

**To Reproduce**
1. Open Runelite.
2. Turn on GPU plugin
3. See error

**Expected behavior**
Improved draw distance and better graphics. 

**Screenshots**
[https://imgur.com/a/E57yKBj](https://imgur.com/a/E57yKBj)

**Environment (please complete the following information):**
 - Windows 10
 - RuneLite version: 1.5.12
 - Launcher version: 1.6.0 

**Additional context**
Logs attached
[client.log](https://github.com/runelite/runelite/files/2877181/client.log)
[launcher.log](https://github.com/runelite/runelite/files/2877182/launcher.log)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/GPU-FAQ

**Comment by 12kcvorki** [comment]
Hey, i forgot to mention in the description that I tried the solutions in
the FAQ to no avail. Can you please Un close it?

Na(o) segunda, 18 de fev de 2019, 19:45, Tomas Slusny <
notifications@github.com> escreveu:

**Comment by Hydrox6** [comment]
Join the Discord and use the `support` channel instead

**Comment by deathbeam** [comment]
I added new entry about your GPU settings there, its at bottom (because apparently noone did before)

**Comment by 12kcvorki** [comment]
Thank you

Na(o) segunda, 18 de fev de 2019, 19:55, Hydrox6 <notifications@github.com>
escreveu:
