### ISSUE TITLE
Computer freezes when playing Runelite

### ISSUE THREAD

**Issue by frank0805** [runelite/runelite#7918]
When playing the Runelite client, may computer will randomly freeze frame and sound loop, becoming totally unresponsive until a hard reset is performed. It used to happen sporadically but today it happens within 5 minutes of running the client, sometimes when I'm not even logged into the game. I've had the same issue with OSBuddy and Vanilla client so apologies if this not an issue directly related to Runelite, although any help would be appreciated.

**Comment by ShaunDreclin** [comment]
Try asking in the #support channel on discord, somebody might be able to help you sort it out.

Doesn't sound like a runelite issue if it's happening with other clients too

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/GPU-FAQ  or this https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

If neither of those helps, your computer is probably broken
