### ISSUE TITLE
XP Tracker Online shows 0 xp gained

### ISSUE THREAD

**Issue by bigwildo010** [runelite/runelite#7919]
Online XP Tracker shows 0 xp or ranks but shows charts with labels.

When skill or total xp is right-clicked in XP Tracker addon and Open Online Tracker is selected, it opens my default browser (Chrome 71.0.3578.98) to the correct page, and it loads the skill list and X axes, but displays 0 gains for rank and xp charts. Clicking other skills or total changes chart labels but not data (0s). I think this started in November 2018. I've also tried copy-pasting the URL into MS Edge (42.17134.1.0) to the same result. I'm running Windows 10 Pro x64. Runelite version 1.5.12. Launcher version 1.6.0. 
![blpmi7k](https://user-images.githubusercontent.com/47758398/52974675-04c37d00-3388-11e9-93d3-7579d5e6c376.png)
K

**Comment by Nightfirecat** [comment]
This should be opened on runelite/runelite.net

**Comment by bigwildo010** [comment]
Thanks for the clarification, Nightfirecat. Reposted in runelite/runelite.net issue 193.

**Comment by deathbeam** [comment]
We believe we partially solved this issue, or well, wait at least a week and then we will have any results. Until that making new issues is pointless, because behaviour changed.

**Comment by bigwildo010** [comment]
Is the issue such that data was still collected while it couldn't be displayed? Just wondering how I'll be receiving my dopamine..

**Comment by shogunreaper** [comment]
is this still broken for anyone else?

**Comment by bigwildo010** [comment]
It was sort-of working for me several weeks ago, but now I'm seeing the same issue again. By sort-of working, it just listed my HiScores values

**Comment by florisdg** [comment]
Doesn't work for me either, the whole online tracking page is blank. I've reset all my XP gains being tracked in the client but that didn't work. Also have all ad/script-blockers disabled on runelite.net

**Comment by florisdg** [comment]
Issue should be reopened by the way, as issue runelite/runelite.net#193 is closed too.
