### ISSUE TITLE
Boosts and other indicators go under raids points counter

### ISSUE THREAD

**Issue by JereHakala** [runelite/runelite#792]
![osbuddy64_2018-03-03_14-42-52](https://user-images.githubusercontent.com/2786086/36934374-30759016-1ef1-11e8-83bc-aa47e7eee22c.png)
![osbuddy64_2018-03-03_14-38-41](https://user-images.githubusercontent.com/2786086/36934350-dae89166-1ef0-11e8-96df-3fc3f89c0b53.png)
Quite annoying, would love if the indicators went under the points counter.

**Comment by deathbeam** [comment]
We are aware of this issue. Current workaround is to put XP drops in center so raids points go to right.

**Comment by JereHakala** [comment]
Ah okay, thanks for the quick response!

**Comment by deathbeam** [comment]
Well that is just workaround so the issue should probably still stay open until it is actually solved :D

**Comment by JereHakala** [comment]
Oops, yeah :)
