### ISSUE TITLE
Sidebar arrow pointing the wrong way

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#7923]
**Describe the bug**
When you have `Resize type` set to `Keep window size`, the arrow to open/close the sidebar points the wrong way.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/5851433/52980353-a8705580-33a7-11e9-8f2b-7c8a6eb75f8f.gif)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.13-SNAPSHOT
 - Launcher version: Unknown

**Comment by deathbeam** [comment]
We are surely not going to flip the icon just based on that configuration property, I will rather keep it point same direction all the time (its also how it works without custom chrome). Main thing is that the icon is different based on sidebar state, so, its fine :d
