### ISSUE TITLE
Colour Picker: Add a section to save some favourite colours

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#7926]
The new colour picker is great, but one thing lost from the old one is being able to quickly select certain colours without having to manually put them in every time. Being able to set a list of maybe 8 colours would be particularly useful for things like #5890 or the Screen Markers plugin.

**Comment by Nightfirecat** [comment]
Alternatively, a "recent colors" section would probably satisfy this without needing as much UX design.

**Comment by ShaunDreclin** [comment]
Yeah that'd get the job done too, preferrably remembered between sessions
