### ISSUE TITLE
Progress-bars inside taskbar application icon (for timers, inventory fill, nmz absorps, etc.)

### ISSUE THREAD

**Issue by Megaddd** [runelite/runelite#7930]
It would be great to see the progress of an activity you are doing if it is of predictable/repeated duration, at a glance without un-minimizing the client. For example seeing the % of your absorption remaining, custom timer remaining duration, prayer/hp remaining, inventory space filling up, afk logoff timer, and more based on what is selected from a list, in the application bar icon.

![image](https://user-images.githubusercontent.com/8878624/53007437-ed47cb00-343f-11e9-8637-372c1c2a7b93.png)

**Comment by deathbeam** [comment]
We would need to like call native Windows stuff for that to work, so its not worth implementing (ignoring the effort required to actually track start and end of what are you currently doing). And also, this do not even works on win 10, i think?
