### ISSUE TITLE
Visual interface bug causing ghost Ghost UI images

### ISSUE THREAD

**Issue by CJohnston888** [runelite/runelite#7934]
**Describe the bug**
Moving my mouse over any of the icons on the right hand side causes the ui to bug out as seen here:
https://imgur.com/Vxy0VQs

**To Reproduce**
1. open Runelite
2. mouse over any icon, even the window resize icons
This may not be helpful, but It's all I've done.

**Expected behavior**
Normal behaviour, no ghost images

**Screenshots**
Extra screenshots to show It's not just a random occurance
https://imgur.com/IegBych
https://imgur.com/Rh5cDRA

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.12
 - Launcher version: 1.6.0

**Additional context**
Logs below
[client.log](https://github.com/runelite/runelite/files/2881162/client.log)
[client_2019-02-18.0.log](https://github.com/runelite/runelite/files/2881163/client_2019-02-18.0.log)

**Comment by Hydrox6** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
