### ISSUE TITLE
Add the the ability to set up and use load-out checklists.

### ISSUE THREAD

**Issue by RobOSRS** [runelite/runelite#7948]
I'm sure everyone here is familiar with the situation of forgetting something you usually take to a farming run, while killing wyverns, or doing some other task. Or having to think hard of what to take for your next farming trip.

What I propose is a load-out checklist that shows you what you're missing from previously saved load-outs.

For example, I want to create and use a load-out named "Wyvern Killing":

1. I'd equip or take the required items for my load-out.
2. RuneLite would let me "Save" the list of items I have equipped or in my inventory into a load-out I could name myself. In this case it would be "Wyvern Killing".
3. When I decide to use the load-out, all I'd have to do is left-click on the name of the load-out, and it would show a list of what I have and what I'm missing. Much like it does with clue scrolls. But I think it would be more convenient to put a large list like this in the sidebar of the client.

BONUS if it's possible to filter the bank to only show items in the load-out.

**Comment by raiyni** [comment]
https://github.com/runelite/runelite/wiki/Bank-Tags
