### ISSUE TITLE
Way to open Wiki page from Grand Exchange plugin in sidebar

### ISSUE THREAD

**Issue by verknaller** [runelite/runelite#7950]
**Describe the solution you'd like**
With the addition of the Wiki plugin I feel like there is a possibility to add more Wiki functionality to the Grand Exchange plugin. Currently when you click on a searched item it opens up the official Oldschool Runescape GE page. 
_Maybe right clicking could open up the Wiki page of the clicked item._
An alternative is to make the whole block unclickable but add two clickable buttons, one for the GE page and one for the Wiki page.

A picture of the Grand Exchange plugin where right click could open Wiki page of the AGS.
![image](https://user-images.githubusercontent.com/18063446/53116056-03d94980-3548-11e9-8279-745eca757684.png)

**Comment by deathbeam** [comment]
Just use wiki search instead
