### ISSUE TITLE
Bog path highlighter for Temple Trekking

### ISSUE THREAD

**Issue by aguscerdo** [runelite/runelite#7957]
The bog in Temple Trekking has a path, where hard tiles have ID 13838 and soft tiles have ID 13839. 

Add a feature in which 13838 tiles are highlighted (for Swampletics reasons)

**Comment by deathbeam** [comment]
This is not possible to see on vanilla and no other 3rd party client provides this

**Comment by dhharris** [comment]
Can we make this a developer mode feature? My reasoning behind this is that it's pretty easy to do  already using the object ids + eyes. You're a maintainer though, so I respect your decision regardless.

**Comment by ShaunDreclin** [comment]
You can already do it with developer mode and reading the IDs, that's probably the best you'll get on this one.

**Comment by fartingkoala** [comment]
This would be much better if it was coded to remove the overlay once leaving the bog. As it is right now, the highlighted tiles would remain indefinitely. In the event that a second bog is stumbled upon, the highlighted tiles from the first bog will invariably blend in with the brand new highlighted tiles from the second bog.

Adding a feature that removes tiles once the bog is completed is necessary for this to be functinoal
