### ISSUE TITLE
Developer tools missing/not activating?

### ISSUE THREAD

**Issue by JohnUrban1** [runelite/runelite#7961]
So last night I had the developer tools working on the client just fine, now this morning the developer tools plugin has gone missing from the client side bar. In the Runelite properties in the target field I have --clientargs "--developer-mode" to show the developer plugin but now it's not working, I've uninstalled and redownloaded, restarted my computer but the problem persists.

**Comment by deathbeam** [comment]
They were removed from launcher, now they work only on client builds
