### ISSUE TITLE
Add option in Menu Entry Swapper- Shift Click 1-2-3 dose potions to "use" for easy decanting

### ISSUE THREAD

**Issue by eX-C0n** [runelite/runelite#7963]
**Is your feature request related to a problem? Please describe.**
As you use potions and bank partial doses, its not always easiest to go to the GE and talk to Bob to decant, quicker to just use partial dose on another partial dose

**Describe the solution you'd like**
An option in menu entry swapper to set 1, 2, and 3 dose potions to "use" when holding shift.

**Describe alternatives you've considered**
manually setting dose potions to use on shift-click via Shift-Click Customization

**Comment by MagicfTail** [comment]
[Shift click customization](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper)

**Comment by eX-C0n** [comment]
Adding the feature for all potions, as doing it for 300 potions (different potions, different doses) would be extraordinarily time consuming
