### ISSUE TITLE
[Suggestion] Marked Tiles Option: To appear on the Minimap as well

### ISSUE THREAD

**Issue by robthedrunk** [runelite/runelite#7968]

**Comment by eX-C0n** [comment]
can you give a use case for this? you are aware they'd be a single dot, similar to an npc on the minimap

**Comment by robthedrunk** [comment]
My apologizes, for the late reply. The usage could be not only to map out areas for example infernal safe locations on the game screen, but to also have them visible on the minimap to know where to click as well, without having to turn the game camera to see the marked tile locations.

**Comment by Nightfirecat** [comment]
This could use the `[good-for-first-contribution]` tag

**Comment by Adam-** [comment]
Added in #8411
