### ISSUE TITLE
Send a notification when a farming patch is updated to a diseased state

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#7970]
It would be helpful to have a notification sent when coming within range of a farming patch and having its state change to a diseased one. This would be helpful for players to know to address the diseased patch before it dies during its next growth stage.

**Comment by Abextm** [comment]
I don't think this is a good idea because it will only know about things becoming diseased when you enter the region with the crop in it, which seems moderately useless and confusing to those who do not understand how the farming system works.
