### ISSUE TITLE
Arceuus essence mine doesn’t have “mining/not mining” panel

### ISSUE THREAD

**Issue by c33dmb** [runelite/runelite#7976]
Hi! This is my first suggestion and I couldn’t find anything specifically about it while searching so forgive me if I missed it.

Would it be possible for mining dense essence blocks for blood/soul crafting to have the “mining/not mining” panel that also houses the counter for how many actions you’ve completed? Thank you for reading!

**Comment by LlemonDuck** [comment]
Added in 5a524471f8358e75405f787964391c986e529029
