### ISSUE TITLE
Account type on Right click Player menu

### ISSUE THREAD

**Issue by MySonsNameIs** [runelite/runelite#7979]
When you right click players in the world, it would be good to be able to see their account type displayed next to their names in the right click panel. 

Right now, if someone doesnt talk, you have to view their hiscores and then see if they have entries in any of the Ironman type hiscores, my proposal would essentially make something that looks like the attached image. This doesnt need to be limited to this menu. 

![mock up](https://user-images.githubusercontent.com/47891155/53244524-1025e980-36a3-11e9-9b6b-ca13ddc6bcc7.png)

**Comment by deathbeam** [comment]
We cant really do this because client do not exposes this information

**Comment by deathbeam** [comment]
Also, this would just help griefing, so its bad idea.
