### ISSUE TITLE
Slayer task (!task)

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [runelite/runelite#798]
a slayer task plugin could be usefull

**Comment by Kamielvf** [comment]
there's already a slayer plugin, if you wan't something specific please explain more about what you want

**Comment by SkrillexAkaCraft** [comment]
I mean where you can do !task

**Comment by deathbeam** [comment]
Ah. You should probably update the title of the feature request. Also, for future feature requests I highly recommend putting more effort into choosing the proper title and description in the issue to avoid confusion like this.

**Comment by SkrillexAkaCraft** [comment]
sorry will update it asap
