### ISSUE TITLE
Add a side-bar button for drop tables

### ISSUE THREAD

**Issue by Zoiding** [runelite/runelite#7986]
**Is your feature request related to a problem? Please describe.**
Alternative to looking at the wiki all the time

**Describe the solution you'd like**
It would be nice to be able to type in a monster name, or hotkey click an enemy and have their drop table appear in the sidebar. Extremely nice for Ironmen.

**Describe alternatives you've considered**
Can't totally think of any alternatives, besides of course just opening a tab in my browser, but I don't want to do that.

**Additional context**
I'm not sure how hard it would be to just pull drop tables from the wiki and implement it into your UI or something, would be handy though. 

You could also add a feature to the client where it tracks what drops you've gotten, and adds data to the table or something? Since I know some tables are not finished/extremely overlooked.

**Comment by deathbeam** [comment]
We have wiki button, just press it and press on monster, or use wiki searc
