### ISSUE TITLE
Setting Goals int he EXP Tracker

### ISSUE THREAD

**Issue by exxzy** [runelite/runelite#7988]
Essentially right now it is a pain to set a level goal for a skill to track it further than one level in advance. You have to do it through the XP Goals ingame, when on other clients you can just rightclick the xp/hr tracker and set a new lvl goal that way. Is it possible to implement that into Runelite?

**Comment by deathbeam** [comment]
No, the way it is done is intentional. In-game interface is good enough so just use it.
