### ISSUE TITLE
Fallback font is not working on macOS, special characters are missing from RS font

### ISSUE THREAD

**Issue by Iron-Zezima** [runelite/runelite#7992]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When you have slain a barrows brother the checkmark turns into an 'f'. This also occurs when doing clue scrolls that require you to wear certain items and do emotes. If you are carrying the correct clue items it turns into an 'f' and not a checkmark.

**To Reproduce**
1. Doing barrows
2. Doing Uri emote clues (hard)
3. Any overlay that would have a "checkmark" in the overlay box. 

**Expected behavior**
A checkmark inside the box instead of an 'f' outside the box

**Screenshots**

![screen shot 2019-02-23 at 9 58 25 pm](https://user-images.githubusercontent.com/47934462/53295042-e0b4d100-37b7-11e9-8b66-50eea402a185.jpg)

**Environment (please complete the following information):**
 - OS: Macbook Pro
 - RuneLite version: [e.g 1.5.13.1]
 - Launcher version: [e.g 1.6.0]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Adam-** [comment]
I've worked around this issue with ca56ef10823aea1ecd275c0d3c3f9a3b17838ff9
