### ISSUE TITLE
Loot tracker killcount doesn't work with bonecrusher

### ISSUE THREAD

**Issue by Azderi** [runelite/runelite#7994]
Having bonecrusher on you while killing enemies that have a chance to only drop bones causes the killcount of the loot tracker to show wrong value, because it doesn't count it as a kill if there's nothing on the floor after the kill.

**Comment by TheStonedTurtle** [comment]
This is expected behavior as the enemy did not drop any loot.

**Comment by deathbeam** [comment]
There is nothing we can do about this, nothing is not loot

**Comment by CookiesBestDinner** [comment]
> nothing is not loot

It's not loot. But it is a kill, and it isn't being counted. This makes the loot per kill appear better than it is.

Hiding items also lowers the killcount, same problem with misrepresented kc.

**Comment by Nightfirecat** [comment]
It's a loot tracker, not a kill tracker. We don't have any way to accurately track "kills" as the client doesn't send information about which monster deaths are tied to player kills. The loot they drop is the only indicator we can semi-reliably tie to kills. Hence, without any loot, we can't track kills.
