### ISSUE TITLE
Black Demon is highlighted in NMZ if it is your task

### ISSUE THREAD

**Issue by TroostJames** [runelite/runelite#7996]
Very simple issue not a big deal at all. Just thought I would let you know in a never ending strive for perfection. 

Issue is simple. I have a black demons task, I am training in nightmare zone and all the black demons are highlighted.

You could have a check for nmz if you are on a black demons task. I am unaware of any other monsters you can fight in nightmare zone that are also possible to get as a slayer task. So this may be the only example.

**Comment by deathbeam** [comment]
I have no idea what are you asking for in this issue, but, if you have slayer task, and you have highlight slayer targets enabled, black demons in nmz will be highlighted, because they are your slayer task.
