### ISSUE TITLE
Resize Type setting is ignored when window is too small

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#8003]
**Describe the bug**
When window width is less than 1044px, showing and then hiding the sidebar ignores the `Resize type` setting and acts as if `Keep game size` was selected.

**Screenshots**
![screenshot](https://i.imgur.com/XGvXRiL.gif)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.14-SNAPSHOT
 - Launcher version: Unknown

**Additional context**
`Enable custom window chrome` is disabled and native borders are stripped.

**Comment by deathbeam** [comment]
This is intentional because there is not enough space for sidebar

**Comment by ShaunDreclin** [comment]
But when the sidebar is closed shouldn't it return to the original width?
