### ISSUE TITLE
Reorder Prayers Plugin addition: Hide prayers

### ISSUE THREAD

**Issue by Auxytocin** [runelite/runelite#8004]
It would be awesome to be able to reorder the prayer interface without all the added clutter of prayers I never use. 

Additionally, these hidden prayers should be locked from being activated and hidden. If possible, they should remain draggable after hidden. This would require added UI to show/hide hidden prayers.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
