### ISSUE TITLE
RS3 Music Plugin

### ISSUE THREAD

**Issue by per1d0t** [runelite/runelite#8008]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A plugin that allows you to hear RS3 music instead of OSRS music when it automatically plays in game ( if an RS3 version exists of the current song). It would also override the music when played manually via the music menu.

**Describe alternatives you've considered**
The only alternative I can find is manually playing the songs via Youtube, a very poor solution.

**Additional context**
None

**Comment by Abextm** [comment]
This is 
a) nearly impossible to do correctly
b) violating Jagex's copyright
c) solved easily by external software
