### ISSUE TITLE
The ability to remove icons on xp drops.

### ISSUE THREAD

**Issue by CaraPis** [runelite/runelite#801]
This might seem stupid, but would it be possible to remove the icons in front of the xp drop (https://i.imgur.com/uJFfoy4.png)? I just like to have my stuff as clean as possible :p

Regards!

**Comment by arlyon** [comment]
Would you be wanting just the name of the skill then or nothing at all?

**Comment by CaraPis** [comment]
Well, i would just want the icons of the skills removed, so only the amount of xp shows up. I just think it looks a lot more clean if those are gone.

**Comment by CaraPis** [comment]
Well, i would just want the icons of the skills removed, so only the amount of xp shows up. I just think it looks a lot more clean if those are gone.
