### ISSUE TITLE
Client size presets 

### ISSUE THREAD

**Issue by GoEasyImBad** [runelite/runelite#8010]
Make a section on runelite in the settings that have a preset for client sizes ( like one for fixed ) maybe one for a certain size like 500 x 500 for resizable etc. would be a nice qol feature

**Comment by Lucwousin** [comment]
This kinda already is a thing. If you just keep your size set to whatever size you want (for instance 1280x720) and manually drag the corner resize your screen to fixed size the values in the setting don't change. If you just increase the value by one and decrease it again it'll automatically *poof* back into the size you want.

**Comment by GoEasyImBad** [comment]
Yeah for one style though, would be nice to have multiples

**Comment by deathbeam** [comment]
Use external software for stuff like this really, we have the custom size option what is good enough for normal users.
