### ISSUE TITLE
More xp drop colors to show more colors

### ISSUE THREAD

**Issue by DreamyRS** [runelite/runelite#8012]
The client already has the option to customize your own color for xp drops when you have a combat prayer enabled (eg. piety), so can we have the option just customize our xp drops altogether instead of only being able to customize a combat prayer xp drop? Would be a nice addition to the xp drop setting

**Comment by ShaunDreclin** [comment]
This is already in the vanilla client
![screenshot](https://user-images.githubusercontent.com/5851433/53367510-664d9380-3914-11e9-84ac-f5a55c15da53.png)

**Comment by Nightfirecat** [comment]
The idea behind recoloring combat exp drops is to highlight them certain colors according to whether the appropriate prayer was active. What purpose is there in coloring other types of XP drops? (aesthetics only?)

**Comment by DreamyRS** [comment]
Yea the only purpose would be for aesthetics, and I guess you could color the xp drops for the combat prayers to something different to differentiate between the two. Idk I just wanted more options than the one the vanilla clients provides, as its very limited and kinda weak imo

**Comment by deathbeam** [comment]
I think this is extremely pointless, you have already enough colors to choose from vanilla, you dont need full color pallete?

**Comment by DreamyRS** [comment]
Well it was just a suggestion to make more colors available, as its only like 8 colors right now

**Comment by ShaunDreclin** [comment]
The vanilla selection *is* pretty sparse, to be fair.

**Comment by TzZek** [comment]
My PR #3078, was going to enable this I just don't think enough people wanted it.

**Comment by DreamyRS** [comment]
I know I would love for this to be added to the client, and I feel like people would start to use it if it were added aswell. This situation is sort of similar to the customizable chat colors, which has **54** different customizable color options, as not a lot of people use it, but some people do. I feel like if theres 54 options to customize chat colors, why can't we then have 1 extra option in the XP drop setting to customize the xp drops?

**Comment by deathbeam** [comment]
Because chat colors are not already configurable in-game, this is
