### ISSUE TITLE
No redraw of panel when fullscreen

### ISSUE THREAD

**Issue by ralpha** [runelite/runelite#8013]
**Describe the bug**
The panel on the right side of the screen from RuneLite does not redraw correctly.
Example screenshot: https://imgur.com/a/XA0Kwa6

**To Reproduce**
Steps to reproduce the behaviour:
1. Open RuneLite
2. Maximize the window
3. Open any part of the sidepanel (or switch panel)
4. It sometimes draws correctly and sometimes does not

**Expected behaviour**
To draw the panel correctly.

**Screenshots**
https://imgur.com/a/XA0Kwa6
Some buttons on the right side are also missing.
This also effects the window buttons on top.

**Environment (please complete the following information):**
 - OS: Linux (Mint 19.1) 
 - RuneLite version: 1.5.13.1
 - Launcher version: 1.6.1

**Additional context**
Nothing abnormal in logs. (no errors or warnings)
This only seem to happen when window is maximized. The game drops fps when mouse is hovering over panel. It redraws buttons when moving the mouse over them or when fields get updated.
Sometimes graphics overlap because new graphics are draw on top of old graphics.

I found that closing the panel and opening it again makes the windows draw correctly sometimes.

Bug seem to be present since a week or 2-3.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
