### ISSUE TITLE
All items from one tag get displayed in another if it starts with the others tag name

### ISSUE THREAD

**Issue by Codar97** [runelite/runelite#8014]
**Describe the bug**
If you have two tags and the second tag starts with the name of the first, the items shown in the first tags tab will display the items from the second too.
For example: 
Take two tabs vorkath and vorkath-loot. Adding items to vorkath-loot tag will mean that it displays in vorkath tag tab too.

This is due to the tags being searched using startsWith (line:133 TagManager.java).
This behavior is good when using the search bar as you might only type in the first few letters but when selecting tabs it should behave differently but it uses the same methods to search for the items.

Obviously, a workaround can be to have tags never starting with an existing tag.
So instead of it being vorkath-loot you could have loot-vorkath instead. It works but may not be ideal for every use case.

**To Reproduce**
1. Create a tag tab called 'tagliatelle'
2. Create a tag tab called 'tag'
3. Add an item to the 'tagliatelle' tag
4. It will appear in the tag tab too

**Comment by raiyni** [comment]
That's by design

**Comment by Codar97** [comment]
I see how it's by design when searching for tags but makes less sense when using tab tags as you have selected to only see what's under that exact tag and not everything that follows, otherwise you'd just search

**Comment by raiyni** [comment]
Don't name your tag `tagliatelle` then. It's so you can do `Slayer - Melee` and `Slayer - Magic` then search `Slayer` and it returns all of them

**Comment by Codar97** [comment]
Okay, it seemed to me like the tab tags had a different use case to searching for tags. I was just mistaken about that and I will close this issue.
