### ISSUE TITLE
Object Marker for the "Sack" in motherlode mine not working

### ISSUE THREAD

**Issue by rsflynhi** [runelite/runelite#8020]
Hello, the title pretty much sums it up, but when trying to mark the the "Sack" at the end of the conveyor in the motherlode mine it wont highlight/mark the sack.
Tried using multiple colors and nothing showed up for me.

**Comment by ShaunDreclin** [comment]
I've found many objects in general don't work with the object marker plugin, haven't been able to figure out a pattern to it yet.

**Comment by Adam-** [comment]
Fixed in ad5514acdefe657b31326c2f6776c66884daf060
