### ISSUE TITLE
Publish Combined Loot Tracker Statistics

### ISSUE THREAD

**Issue by tjbarrett96** [runelite/runelite#8023]
To me, it seems that drop rates are not well-measured for the vast majority of monsters. The wiki often cites general and relative descriptors such as "common", "uncommon", "rare", or "very rare", or occasionally cites an officially published drop rate for more high-profile drops, or rarely cites an empirical rate based on a small sample of kills supplied by some user(s).

Given the inclusion of the Loot Tracker feature, I think it would be incredibly useful for RuneLite to amalgamate the drop records of all Loot Tracker users into a histogram of recorded drops from any given source (a particular monster, a particular treasure trail tier, etc.), and publish this data publicly. For example, RSBuddy publishes something similar for clue scrolls; see https://rsbuddy.com/cluescroll. I am not proposing a permanent record of individual drops with identifying details such as usernames or timestamps, but rather a combined (and therefore anonymized) record of the total number of recorded occurrences of each drop, for each dropping monster (or clue, etc.) that the Loot Tracker recognizes. Perhaps this information could be added into a global database when each participating user ends a RuneLite session, and the database could be made accessible and periodically updated on RuneLite's website.

This information could be used for applications such as constructing empirical probability distributions for a monster's drops, or for the total value of any single drop (from which a mean value and its variance could be computed). Using existing GE trackers, these drop value statistics could also be computed as a function of time, showing the time evolution of any given monster's profitability (i.e. whether or not the monster is a stable money-maker). This could help answer questions regarding what monsters a player should target, and for how long, in order to achieve a certain goal -- a particular drop, or a particular profit, for example. With such a large sample size as RuneLite's user base, this feature would yield better statistics (and broader coverage of the drop tables) than ever available before.

**Comment by raiyni** [comment]
duplicate #6688
