### ISSUE TITLE
Loot tracker enhancements

### ISSUE THREAD

**Issue by fargoldbee** [runelite/runelite#8039]
1. Add the total value of all kills to the loot tracker on the site
2. Sort highest value items first like on the client

![image](https://user-images.githubusercontent.com/46892701/53587000-a36e8b80-3b89-11e9-89f7-bda646c07e49.png)
![image](https://user-images.githubusercontent.com/46892701/53586833-4d99e380-3b89-11e9-984d-795f7949b4c4.png)

Not sure if I put this here in runelite client issues or on the website issues

**Comment by deathbeam** [comment]
We have repository for website, so please reopen here: https://github.com/runelite/runelite.net/

**Comment by fargoldbee** [comment]
No worries, thanks for the feature btw
