### ISSUE TITLE
Sync imgur generated links to server and display it on website

### ISSUE THREAD

**Issue by mattgcc** [runelite/runelite#8040]
https://github.com/runelite/runelite/issues/3147
Since this new really neat feature is out, which allows us to track Grand Exchange offerings & Loot straight from the web panel, maybe are you guys open to reconsidering this idea?

Original idea: save Imgur upload links in some file
New idea: sync the images in the web panel

Then @deathbeam commented:

> "There is already upload to Imgur. If you need to use cloud storage for files, use services made for that when it is possible with them."

With new web panel, I think this idea is worth to reconsider.

**Comment by Nightfirecat** [comment]
We're not interested in becoming an image hosting service.
