### ISSUE TITLE
Ground Markers in POH

### ISSUE THREAD

**Issue by machvise** [runelite/runelite#8045]
Ground markers are not working like they used to inside of POH. When I enter my POH, the ground markers are not visible. If i "mark" a random tile, the other ground markers then appear where i marked them in the past. Then if i leave and re-enter my POH, they are gone again and i have to mark a random tile again to make them appear.

Notice how there are no ground markers..
https://puu.sh/CTcHO/4a632957e8.png

Now if i mark a random tile (the tile beside the entrance portal) the other 3 appear on the ground automatically.
https://puu.sh/CTcJ4/053edfd679.png

**Comment by Nightfirecat** [comment]
This only seems to apply to certain room types. I noticed tiles in the starting portal and normal portal rooms appeared fine on first load. Tiles in portal nexus rooms or studies would not appear until another marker was placed. I'm looking into why that is now.
