### ISSUE TITLE
Tears of Guthix Quest Guide wiki 

### ISSUE THREAD

**Issue by AronU** [runelite/runelite#8053]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Right clicking the Tears of Guthix quest in the quest tab, wanting to go to the guide on the wiki leads to a dead link. 
**To Reproduce**
1. Right click Tears of Guthix Quest and click QuickGuide. 

**Expected behavior**
Link to the quickguide for Tears of Guthix

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Hydrox6** [comment]
This happens because the Tears of Guthix quest page is at `Tears_of_Guthix_(quest)`, unlike every other quest which doesn't have the `(quest)`. Interestingly, using the guide option works, though it leads to a disambiguation page instead.

**Comment by Nightfirecat** [comment]
A disambiguation page should be expected for something like this which would point to multiple pages. This issue should be closed imo.

**Comment by Abextm** [comment]
There is now a redirect in place

**Comment by Abextm** [comment]
Additionally, `Tears_of_Guthix` now is the quest guide, not a disambiguation
