### ISSUE TITLE
Resizeable spell icons

### ISSUE THREAD

**Issue by renfc01** [runelite/runelite#8054]
What do you guys think about a runelite plugin to implement resizeable spell icons? I can look into it, perhaps as part of a spell icon rearrangement plugin. Perhaps it would be similar to implement as the prayer icon rearrangement.

**Comment by ShaunDreclin** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

I'm gonna guess resizing spells would fall under this too since it failed a poll

**Comment by Nightfirecat** [comment]
We're not really interested in implementing features which failed ingame polls.

**Comment by renfc01** [comment]
Sure Jordan, but what if I implemented it?

**Comment by ShaunDreclin** [comment]
The issue isn't who does the work, it's that they don't want the feature period

**Comment by renfc01** [comment]
Ah damn, okay. Got it
