### ISSUE TITLE
Nickname for god wars dungeon bosses

### ISSUE THREAD

**Issue by Swirlyy** [runelite/runelite#8067]
It is not related to any problems, I simply want this feature implemented.
Some bosses should have a nickname added to them so that whenever I use the !kc or !pb commands I can type 
"!kc Zilly" instead of "!kc zilyana" for example.

**Comment by Hydrox6** [comment]
There are already nicknames for GWD bosses, you're spelling `zily` wrong though
```java
case "sara":
case "saradomin":
case "zilyana":
case "zily":
	return "Commander Zilyana";
case "zammy":
case "zamorak":
case "kril":
case "kril trutsaroth":
	return "K'ril Tsutsaroth";
case "arma":
case "kree":
case "kreearra":
case "armadyl":
	return "Kree'arra";
case "bando":
case "bandos":
case "graardor":
	return "General Graardor";```

**Comment by Swirlyy** [comment]
Oh great, thanks man!
