### ISSUE TITLE
World Map Custom Symbols

### ISSUE THREAD

**Issue by WasabiCannon** [runelite/runelite#8074]
**Is your feature request related to a problem? Please describe.**
Sometimes I find a nice area that I want to make note of for the future but there is nothing on the map to make note of easily.

**Describe the solution you'd like**
A method to add our own symbols to the map(Clicking on the globe) along with a description that would show when you hover over them.

**Additional context**
The main benefit of this is for snowflake accounts where there is not a lot documented about the areas so when you find a nice spot that is not documented in a wiki you could actually mark it on your map for future use.

**Comment by Hydrox6** [comment]
Basically #4496 but better

**Comment by deathbeam** [comment]
I would then basically make this duplicate of #4496 as that should be enough
