### ISSUE TITLE
High-granularity in-game volume sliders

### ISSUE THREAD

**Issue by xZoks** [runelite/runelite#8076]
**Is your feature request related to a problem? Please describe.**
In-game sounds and music have volume sliders that usually leave the user wishing there were more than 5 volume levels.

**Describe the solution you'd like**
A continuous slider (as a bonus, with very high granularity towards the quieter volume).

**Describe alternatives you've considered**
Complaining to Mod Ash on Twitter

**Comment by Adam-** [comment]
Duplicate #2213
