### ISSUE TITLE
Developer tools mode

### ISSUE THREAD

**Issue by XueSosBlyat** [runelite/runelite#8084]
Describe the bug

I tried to add the quote  --clientargs ''--developer-mode'' to the properties of the client to add the developer mode but the client is up normally without any other options of the developer mode.                      is it a bug? can someone help me activate it?
thanks.

Expected behavior
should have add the developer tools options to the client

OS: Windows
RuneLite version: 1.5.14

**Comment by deathbeam** [comment]
Developer tools now only work when enabled on client directly, enabling it via launcher do not works anymore and it was intentional change

**Comment by XueSosBlyat** [comment]
> Developer tools now only work when enabled on client directly, enabling it via launcher do not works anymore and it was intentional change

so how do i enable them via client now I cannot find this on settings

**Comment by steffenhauge** [comment]
You need to build the client from sources.

**Comment by XueSosBlyat** [comment]
> You need to build the client from sources.

:( there is no other option? like getting older version or something?
why is it not allowed anymore btw?

**Comment by steffenhauge** [comment]
Because people abuse it, like you?

**Comment by XueSosBlyat** [comment]
> Because people abuse it, like you?

most of the settings in runelite are abuse lol
I need to to know where is the right door at the pyramid plunder and thats it because im grinding for pharaoh sceptre right now

**Comment by steffenhauge** [comment]
Smh, also you can't see the right door with that :)

**Comment by XueSosBlyat** [comment]
> Smh, also you can't see the right door with that :)

i assume that the right door doesnt share the same id as the wrong doors :\

**Comment by Malfuryent** [comment]
code is executed at the moment you click the door, id for all 4 are the same. the code determines if you are on the right spot or not and that we are unable to see/detect even with dev tools.

**Comment by XueSosBlyat** [comment]
thank u


> code is executed at the moment you click the door, id for all 4 are the same. the code determines if you are on the right spot or not and that we are unable to see/detect even with dev tools.

thanks
