### ISSUE TITLE
Can't switch RL accounts in same session

### ISSUE THREAD

**Issue by russel204** [runelite/runelite#8089]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When using multiple accounts, if you launch Runelite play on the account that is logged in and then log of RS and RL you can no longer log into any RL account. 

**To Reproduce**
1: Open RL and login to an RL account
2: Login to RS.
3: Log out of RS and then RL
4: Attempt to log into RL 

**Expected behavior**
The ability to log in and out of RL accounts in the same session in order to be able to use my mains settings and my irons settings when playing them without having to close and relaunch the client.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows  10
 - RuneLite version: 1.5.14
 - Launcher version: 1.60

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by deathbeam** [comment]
Hmm I noticed this behaviour on local build but I thought it was issue with my implementation. Maybe it was and this is just the deadlock issue again.

**Comment by deathbeam** [comment]
Tested this on release, it is definitely not working. Steps to reproduce:

- Start client without being logged in to RuneLite
- Log in to RuneLite
- Log out of RuneLite
- Log in to RuneLite

Everything till last step will work.

**Comment by russel204** [comment]
@deathbeam Looks like you've already got it sorted. Much appreciated!

**Comment by Adam-** [comment]
fixed in 420744c7a7c6e9515f0dc2bc0f6e50ed311f8c5e
