### ISSUE TITLE
Exceptions for ground items plugin

### ISSUE THREAD

**Issue by mtnlol** [runelite/runelite#8098]
I'd love a feature for the ground items plugin where you could add an exception to an item to make it not get hidden if its below the Hide < value, for example I have my Hide < value set at 500 but that hides toadflax seeds, I'd like to add an exception WITHOUT highlighting it as I don't want to highlight it.

**Comment by deathbeam** [comment]
but highlighting it already solves the issue. you can also change color of highlighting from purple
