### ISSUE TITLE
Auto item dropper

### ISSUE THREAD

**Issue by Juhovv** [runelite/runelite#8100]
Id like to see item auto dropper be added, it would be helpful in several skills, thieving, woodcutting. mining..

When user picks up or receives an item, it will be instantly dropped, red alert box would appear on hud when it's enabled to avoid dropping valuable stuff when not intended

**Comment by Hydrox6** [comment]
This would be botting, so no

**Comment by edoquendo1314** [comment]
I'll make it bro you'll just get in-trouble for using it
