### ISSUE TITLE
Black screen when turning on GPU plugin Linux

### ISSUE THREAD

**Issue by claytonmcfarland** [runelite/runelite#8101]
**Describe the bug**
When turning on the gpu plugin, the game turns black. It does not crash or freeze and I can still click and move my character; however it is just all black. I have hardware acceleration turned off. I am running Manjaro Linux and downloaded it via AUR. I saw this issue in the FAQ but it seems like those solutions are windows specific.

**To Reproduce**
1. Turn on gpu plugin
2. black screen

**Environment (please complete the following information):**
 - OS: Manjaro Linux
 - RuneLite version: 1.5.14

**Comment by RyBo** [comment]
https://github.com/runelite/runelite/wiki/GPU-FAQ

Downgrade mesa to 18.2.5 and use Java version 8
