### ISSUE TITLE
Cannon Overlay not working at Cave Horrors

### ISSUE THREAD

**Issue by Elli-tt** [runelite/runelite#8106]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The cannon overlay does not work in the mos le harmless caves, in particular when cannoning cave horrors.

**To Reproduce**
1. Go to Mos Le Harmless caves.
(not sure if it makes a difference but I am not wearing a witchwood icon)
2. Place cannon in the recommended cannon spot.

**Expected behavior**
The cannon will be setup but there will be no overlay like there is in other places. The cannonball indicator tile does not update either.

**Screenshots**
![image](https://user-images.githubusercontent.com/18116850/53765476-f917a080-3ec7-11e9-89f5-c85e0a90dbfd.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.14
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by iamjerrchen** [comment]
So I encountered the same issue; the conclusion encountered is that if you are in combat (being attacked) while placing the cannon, the overlay will not appear, so if you quickly clear the cave horrors or wait until they stop aggression, and replace the cannon again, your overlay should reappear.

**Comment by Domitan** [comment]
This is also happening with me 👍 

Runelite version: 1.6.10
Launcher version: 1.6.0
OS: Windows 10

**Comment by Alexsuperfly** [comment]
it tracks which cannon is yours by the animation you make when placing the last piece down.  The animation can be canceled by blocking in combat, just pick it up and put it down again.
