### ISSUE TITLE
Hespori Notification

### ISSUE THREAD

**Issue by IronPerish** [runelite/runelite#8109]
Can we get a Hespori notification in chat or something to let us know when it's fully grown without going to the Farming Guild to find out?

**Comment by Hydrox6** [comment]
Hespori is listed in the Time Tracking plugin's sidebar under the "Special" crops section. Check that to know when Hespori is ready to be fought

**Comment by IronPerish** [comment]
> Hespori is listed in the Time Tracking plugin's sidebar under the "Special" crops section. Check that to know when Hespori is ready to be fought

I'm not seeing a "special" crop section?

**Comment by Hydrox6** [comment]
It's the tab with the mushroom, named "Special Patches"

**Comment by IronPerish** [comment]
Ye, mb. I thought you meant in the notifications. I'd like a feature that notifies me in chat or something like my dailies. I guess I'm just lazy? Haha. Just thought it'd be a neat feature.

**Comment by deathbeam** [comment]
Dupliate of #2212
