### ISSUE TITLE
Bank Cleaner

### ISSUE THREAD

**Issue by Hagendazpvp** [runelite/runelite#8118]
**Is your feature request related to a problem? Please describe.**
I find myself hitting my bank limit more often than I like to admit, as I'm sure some other players do too. To solve this issue would it be possible to add a bank cleaner? Something that when enabled allows you to see items in your bank (placeholders you may not use anymore) or quest items that aren't needed any longer? I'm aware the Wise Old Man in draynor clears quest items from f2p quests but there's no option to do so (or any suggestion as to what's not needed) for p2p quests.

**Describe the solution you'd like**
I'd like some way to highlight the stuff in the bank that's not needed anymore, IE. Quest items that aren't needed, placeholders that you may not use anymore, or other items that fit the description of not needed but may still be lingering in the bank. Perhaps there'd be a way to figure out what items are still useful but aren't too hard to obtain. Also might be nice to add an option (or color for the icons) that suggest things you can put elsewhere, like the mourners gear into your PoH. 

I know this seems like a lot but it may be worth at least bringing to your attention, in the hopes someone has a better idea of how to remedy this problem. 

Thank you.

**Comment by Hydrox6** [comment]
Wise Old Man does do members quests now

**Comment by Hagendazpvp** [comment]
Sorry for not knowing that, it's been a while since I've tried. I'll see how much junk he actually tosses and update accordingly. Thank you, Hydrox.

**Comment by 15987632** [comment]
Report the things you think need improving about the wise old man to jagex, not us.
