### ISSUE TITLE
Alch warning per item

### ISSUE THREAD

**Issue by jmm140330** [runelite/runelite#8121]
**Is your feature request related to a problem? Please describe.**
The vanilla client allows for a warning before alching items above a certain value. Sometimes however you may want to protect an item that is below the minimum threshold. For example, my friend accidentally equipped a fire battlestaff and alched his rune crossbow while on a slayer trip.

**Describe the solution you'd like**
Allow us to give a warning before alching specific items, regardless of value.

**Comment by Hydrox6** [comment]
#7972
