### ISSUE TITLE
Add proxy authentication support for dependecy download

### ISSUE THREAD

**Issue by PapaiVader** [runelite/runelite#8129]
**Is your feature request related to a problem? Please describe.**
I'm behind a proxy, and can't download the .jars upon first starting the client. Using the env vars on the system (Windows) does not seem to help. 
I'll probably need something using the Authenticator class to set System Properties accordingly

**Describe the solution you'd like**
something along the lines of
```
final String authUser = "user";
final String authPassword = "password";
Authenticator.setDefault(
   new Authenticator() {
      @Override
      public PasswordAuthentication getPasswordAuthentication() {
         return new PasswordAuthentication(
               authUser, authPassword.toCharArray());
      }
   }
);

System.setProperty("http.proxyUser", authUser);
System.setProperty("http.proxyPassword", authPassword);
```

Upon first starting the client, at the moment of downloading the dependencies, ask for host, user and password for connecting via proxy 

**Describe alternatives you've considered**
Tried using env vars and setting up proxy upon JVM, but neither showed results.

**Comment by deathbeam** [comment]
As I already said in discord I am pretty sure this thread solves this and do not requires us changing anything in launcher: https://stackoverflow.com/questions/14113341/http-407-proxy-authentication-required-how-to-handle-in-java-code
