### ISSUE TITLE
Add ability to drag the instance map contents around with mouse

### ISSUE THREAD

**Issue by rothsrs** [runelite/runelite#813]
I just popped open the instance map, and there were a few things I could see that might be beneficial.

1) Make it so it doesn't clip into the chatbox? There is a lot of empty black space that could be cropped.
[https://i.imgur.com/jZobmFb.png](url)

2) Make it a click-and-drag thing like the RS worldmap. That would help it take up less space and also probably fix suggestion 1 if the whole area is used for something that I don't know about 😛 

3) Up and down floor buttons. Could those be remapped from "Ascend" and "Descend" in the world map icon to two buttons and an indicator of which floor you're on somewhere in the instance map?
[https://i.imgur.com/oUMlO05.png](url)

4) Put the instance map and the world map together to create one central map that we can use? I don't like to rip off of other clients and say "oh they have this you should do that" a whole lot but having the whole map in one place like RL/OSB does would be godlike

Thanks y'all 🥂

**Comment by Kamielvf** [comment]
There is #805 that I just put together quickly earlier because those were the major issues about the instance map. I am aware of the map drawing very awkwardly, but that and the other issues will be worked on later.

**Comment by rothsrs** [comment]
Thank you Kam!

**Comment by deathbeam** [comment]
1. You can move the minimap around
3. Is duplicate
4. This is way too broad

Edited the issue to contain only 2.

**Comment by deathbeam** [comment]
Actually 2. is 1., so closing

**Comment by kaydiechii** [comment]
a fresh runelite install with all plugins except this disabled still does not allow you to move the map around so maybe this has changed since 2018? but this plugin is very clunky when it only draws a tiny fraction of a instance map but you cant even move it or zoom out. its unusable in most cases

https://i.imgur.com/OhKkYKO.png

this is a good example.
