### ISSUE TITLE
Pay-dirt in MLM water trough is invisible

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#8131]
Tried disabling both the GPU and Skybox plugins, still not showing up. Appears fine in the vanilla client

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.15-SNAPSHOT

**Comment by Kamielvf** [comment]
Are you using the entity-hider to hide NPCs?

**Comment by ShaunDreclin** [comment]
🤦

Didn't consider that they'd count as NPCs. Good call
