### ISSUE TITLE
Special attack orb clicks on minimap

### ISSUE THREAD

**Issue by Malfuryent** [runelite/runelite#8137]
**Describe the bug**
If you click on the spec attack orb in fixed mode then it will click on the minimap and move the character. I tested this on vanilla and it doesnt appear to do that there

**To Reproduce**
Fixed mode, click on orb

**Expected behavior**
moves the character instead of only clicking the button

**Comment by WoneTooPhree** [comment]
Same here

**Comment by Hydrox6** [comment]
This is because the Wiki plugin changes the click mask for the minimap. For the time being, disable the Wiki plugin and restart the client
