### ISSUE TITLE
Reverse order of ground item prioritization

### ISSUE THREAD

**Issue by eX-C0n** [runelite/runelite#8141]
Change the prioritization currently as:
Highlight specific > Block Specific > Highlight Wildcard > Block Wildcard

use-case:    I have "Dragon *" in my Highlighted Items, thus allowing and dragon items to highlight. It also highlights Dragon Bones, as it fits the wildcard. Putting "Dragon Bones" or " *bones " in Hidden Items, does nothing

**Comment by deathbeam** [comment]
Basically duplicate of #3942
