### ISSUE TITLE
XP Globes aren't centered on resizable

### ISSUE THREAD

**Issue by ptolodo** [runelite/runelite#8145]
Up until the recent update, XP Globes were centered on resizable, now they seem to be where they should be if the game were set to fixed. The center point seems to be misaligned.

**To Reproduce**
1. Use XP Globes

**Screenshots**
![untitled](https://user-images.githubusercontent.com/48342219/54006699-6cb9e780-412c-11e9-8733-31677ea7b66e.png)

**Environment (please complete the following information):**
 - OS: Windows 7
 - RuneLite version: 1.5.15.1
 - Launcher version: 1.5.2

**Comment by Alexsuperfly** [comment]
your screenshot shows the globes being centered

**Comment by ptolodo** [comment]
> your screenshot shows the globes being centered

I cut out the inventory and map by accident, my character is to the right, it's definitely not centered.

It was directly above my character before the last update

**Comment by raiyni** [comment]
It's centered on the viewport.

**Comment by ptolodo** [comment]
> It's centered on the viewport.

Is there any particular reason it changed?

Can I revert it back?

**Comment by raiyni** [comment]
It didn't.

**Comment by ptolodo** [comment]
> It didn't.

What do you mean?

As of yesterday, my globes were in a completely different position.

Something changed, but the only thing I did was log out, and then log in after runelite had updated.

**Comment by Abextm** [comment]
This hasn't been touched since October, maybe you moved the orbs out of their snap zone.

**Comment by ptolodo** [comment]
> This hasn't been touched since October, maybe you moved the orbs out of their snap zone.

The snap zone itself seems to have moved. Is there any way to move it back?

**Comment by raiyni** [comment]
resize your client.

**Comment by Abextm** [comment]
false, the snap zone hasn't been moved ever.

**Comment by ptolodo** [comment]
> false, the snap zone hasn't been moved ever.

How can I change the globes from middle_viewport to middle_canvas?

**Comment by ptolodo** [comment]
> resize your client.

what do you mean by this?
