### ISSUE TITLE
Runelite GPU Plugin doesn't render anything for Intel HD 630

### ISSUE THREAD

**Issue by Shin-Aska** [runelite/runelite#8149]
I don't know when this started but at the moment, I can no longer use GPU mode. To be exact, when I turn it on, it doesn't render anything (it use to be working). If the skybox is black, everything is black except for text.

I tried turning hardware acceleration off to no avail. It still doesn't work.

**Video**
https://youtu.be/Ee8vxPSMuvg

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - GPU: Intel HD 630
 - RuneLite version: 1.5.15.1
 - Launcher version: (The latest)

This is what the output of glxinfo looks like
https://pastebin.com/wBc3BD2P

The content of the client.log
https://pastebin.com/0FfQxsf5

Then finally the launcher.log
https://pastebin.com/cF3szKEg

**Comment by 8Keep** [comment]
Hi, I have this same issue. I am on Manjaro, all packages updated. My screen is black though, not blue like yours. I have HD 520 (skylake) though. 

[glxinfo.txt](https://github.com/runelite/runelite/files/2974015/glxinfo.txt)

**Comment by Shin-Aska** [comment]
8keep Have you tried turning on the skyboxes? The only reason why its blue is because I turned on the skyboxes, otherwise it would be black too

**Comment by Alexsuperfly** [comment]
Have you guys tried this yet https://github.com/runelite/runelite/wiki/GPU-FAQ#my-client-turns-black-when-i-enable-the-plugin

**Comment by 8Keep** [comment]
Shin-Aska: Skyboxes makes it blue, just like yours.

Alexsuperfly: We're both running linux, as we've mentioned

**Comment by Alexsuperfly** [comment]
Ohh sorry didnt see that, there is however a thing on there about downgrading mesa. Even though you arnt freezing maybe look at that anyways.

**Comment by Shin-Aska** [comment]
I tried downgrading mesa to 18.2.8. It did not have any effect. However, I tried to upgrade to bleeding-edge builds 19.1~git and its working again.

![image](https://user-images.githubusercontent.com/8596711/54790344-c2d07400-4c70-11e9-8c56-0c8e1e927474.png)

@8Keep  can you try getting driver updates under this repo? https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers this is the one i use that help resolved the issue.

**Comment by 8Keep** [comment]
@Shin-Aska
I am on Manjaro. Shouldn't be too long for mesa 19.1, if the fix is included there. I'll wait for stable

**Comment by Adam-** [comment]
I would be interested in knowing the commit it was fixed in if someone feels like bisecting.

**Comment by 8Keep** [comment]
I can confirm that mesa 19 fixes this issue! But, I do not have the technical knowledge to find which commit it was fixed in.

**Comment by Shin-Aska** [comment]
I could downgrade back to the previous mesa that I am using. Although I need to know how I am able to make the GPU plugin produce meaningful debug messages so that I can pinpoint which commit exactly fixes it.

**Comment by deathbeam** [comment]
Just add --debug param probably

**Comment by pacf531** [comment]
Mesa 19.1 was released today and in the changelog, there was an interesting mention of RuneLite. I think the issue mentioned was the culprit for this issue.

>...
> Bug 109601 - [Regression] RuneLite GPU rendering broken on 18.3.x
>...

https://bugs.freedesktop.org/show_bug.cgi?id=109601
