### ISSUE TITLE
World map location markers (flashing arrow on minimap)

### ISSUE THREAD

**Issue by Antimated** [runelite/runelite#8150]
**Description**
I would like to propose a feature that would be amazing in your everyday scaping. I would love to have a feature like RS3 already has in it's world map:
- An option to place a marker on the official OSRS world map.
- Minimap arrow hinting to where you placed your marker (IIRC this is used for coordinate clues)

**Use cases**
- Doing quests
- Doing clue scrolls
- Regular playing
- ...

**Extra features**
- Clear marker option on minimap orb
- Possibility to place multiple markers on the map (maybe make a chain of markers so when you reach point A you get a notification and the arrow now points to point B if that makes any sense)

**Comment by ShaunDreclin** [comment]
Duplicate #4496 #8074
