### ISSUE TITLE
Spade reminder for strange device clues

### ISSUE THREAD

**Issue by dhharris** [runelite/runelite#8151]
**Problem**
It is easy to forget a spade when getting a Jorral (strange device) clue

**Describe the solution you'd like**
Leverage the existing spade-reminder functionality of the client to remind you in this situation

**Describe alternatives you've considered**

**Additional context**
I can work on this new feature

**Comment by Adam-** [comment]
Added in a8c86490a734f2789b05071b7ec24a94c47cab88
