### ISSUE TITLE
HiScore Live Progress

### ISSUE THREAD

**Issue by Smileynator** [runelite/runelite#8152]
**Is your feature request related to a problem? Please describe.**
I like to see realtime progression. If i know my current XP, and the current hiscore listing. I can request a list of all the people above me in the hiscore. But i can not see those in HiScore currently.

**Describe the solution you'd like**
A list of the first 100? entries above me in the highscore, that updates with my ingame XP to reflect my movement past others as i gain XP. (possibly just fetch and cache some pages beyond your own page to prevent rate limit issues etc.)

**Describe alternatives you've considered**
Manually following my XP rate through the charts. It's not fun.

**Comment by deathbeam** [comment]
This makes no sense, idk. just check your rank
