### ISSUE TITLE
item-stats: stats not shown for mage's book

### ISSUE THREAD

**Issue by RobinLaevaert** [runelite/runelite#8157]
item stats plugin not showing/using mage's book stats

![Alt Text](https://i.gyazo.com/645da82536f2ac7ebdff613ec45de5d4.gif)

**Comment by nateisonfire** [comment]
I'm pretty new with this codebase, but I was able to trace the issue down into the `http-api` directory. It seems that the Mage's Book's stats aren't in the massive list of itemstats. So RuneLite doesn't render a tooltip.

Will keep digging later this evening!
