### ISSUE TITLE
Turn off rendering lower floors when "upstairs"

### ISSUE THREAD

**Issue by andaiakudj** [runelite/runelite#8159]
Hi there! This is a request for the low detail plugin; disable rendering lower levels of the map. Going upstairs in Zeah, especially to 3rd floor of Kourend Castle and Arceus Library really impacts my FPS because it's rendering all of the lower floors.

This was a feature with the low detail setting back in old RS2, which you had to pick on the website (http://i.imgur.com/Z95tbmO.png) as there was no in-game settings for graphics back so that explains why OSRS has nothing like this. I think it was finally added to the in-game settings after the RS HD update and was labeled "visible levels." if you disabled it, you would just see a black void instead of the lower floors.

It would be highly appreciated if such a feature could be added to the client. Places like Zeah are just too harsh on my CPU after I've climbed a few floors.

Anyway, thank for your time. Apologies for the bad writing in this post, my English isn't that great. T_T

**Comment by Adam-** [comment]
added in 1c191f005b9c25ae8d1591d9373d516107d3d35b
