### ISSUE TITLE
Change keybind for function keys

### ISSUE THREAD

**Issue by DeagleBiegel** [runelite/runelite#8161]
**Is your feature request related to a problem? Please describe.**
I absolutely hate the current keybinds (F1 - F5) for changing menu. As
the position is terrible imo.

**Describe the solution you'd like**
Same as WASD Camera plugin. Change the bind for each
individual key, and press enter to chat.

**Comment by Adam-** [comment]
This is a in-game feature which you can change in game.

**Comment by Adam-** [comment]
At best this is a duplicate of #5070
