### ISSUE TITLE
Add an option to highlight fishing spots within 4 tiles of the player on Molch Island

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#8163]
According to the [wiki](https://oldschool.runescape.wiki/w/Lake_Molch#Catching_fish), there is a ~~9x9~~ square centred on the player that can be fished from in one tick. Would be great to make spots in that square a different colour or something!

Edit: After testing it a bit myself, it seems to only work for tiles INSIDE that 9x9 border, so it's actually a 7x7 area centred on the player.

**Comment by Adam-** [comment]
Added in #8338
