### ISSUE TITLE
Bring back RuneLite CoX points overlay

### ISSUE THREAD

**Issue by GothicLogic** [runelite/runelite#8164]
The official overlay looks really bad and inconsistent with other RL overlays like timers.
Can't put it over your chat box either though that is a small issue.

At least let you choose between them it really looks terrible. Ty.

**Comment by deathbeam** [comment]
Our overlay was intentionally dropped in favour of vanilla overlay and will not be coming back as there is no reason for it to exist. The "inconsistency" with runelite overlays doesnt matter because its vanilla overlay not runelite overlay. If you don't like how it looks probably just ask Jagex.

**Comment by GothicLogic** [comment]
Out of many very small things on RL, it seems very weird to me to be completely against adding an option to have the overlay look better than it currently does. Would be interested to hear why it's not an option and why it was intentionally dropped in the first place.

**Comment by Adam-** [comment]
I see two reasons for the overlay to exist:

1) you can move it out of the viewport
2) it provides an easy way to view raid party count, without having to enable/disable the clan option. Additionally, I don't think the clan one is always right since it can't count players outside of the scene?

**Comment by deathbeam** [comment]
1. this is issue with literally every single movable overlay we have atm, I don't think it makes any sense to "try" to solve that by redoing vanilla widgets, that is just stupid
2. is easily solveable by making clan counter respect being in raid
