### ISSUE TITLE
XP Tracker not incrementing time

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#8167]
two people have come into the support channel with weird xp tracker xp/hr readings
neither had auto pause enabled
toggling the plugin on and off did not resolve the issue
manually pausing and unpausing did not seem to effect it either

the second guy said that after a full restart of the client it seems to have returned to normal behavior

![](https://i.gyazo.com/thumb/1200/a0f269c08ad0d96a5d75b84d8eb5363f-png.jpg)

![](https://i.gyazo.com/7df17e7035596990a2a6824779b80539.png)

possibly unrelated but i had a friend with this which looks to me like another time tracking bug but it doesnt use xp tracker so im not sure

![](https://cdn.discordapp.com/attachments/397229158377455620/554137293862993940/SPOILER_unknown.png)

**Comment by Adam-** [comment]
I think this might be related to people with no construction xp & it not initializing the overall xp

**Comment by Alexsuperfly** [comment]
I have spoken with both individuals and one has 99 construction, the other only has 28 exp in the skill but says he gained that exp before the incident.

**Comment by Adam-** [comment]
a5f9d7bbcc6988935a3ddb644874f0016689cf12 probably fixes it
