### ISSUE TITLE
Bank's Items Counter

### ISSUE THREAD

**Issue by EyezNation** [runelite/runelite#8168]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Nightfirecat** [comment]
There is already a banked items counter in the top left; this is a vanilla feature.
