### ISSUE TITLE
Barb-tail harpoon doesn't trigger idle notifications

### ISSUE THREAD

**Issue by Nukas** [runelite/runelite#817]
Looks like fishing sharks with the barb-tail harpoon or dragon harpoon isn't triggering tray notifications when you stop fishing.

**Comment by sethtroll** [comment]
it does support skilling idle notifications

https://github.com/runelite/runelite/blob/23df0ddb74721dc5d2b90fb7eb456c9f6fd8f756/runelite-client/src/main/java/net/runelite/client/plugins/idlenotifier/IdleNotifierPlugin.java#L164-L238

**Comment by Nukas** [comment]
Huh that's weird, it's not working for me. I'll test again.

**Comment by Nukas** [comment]
Well now it makes more sense, they do indeed work EXCEPT for the barb-tail harpoon and dragon harpoon. Those two don't trigger the fishing idle notification. Sorry for the confusion.

**Comment by sethtroll** [comment]
ah #818 should fix this
