### ISSUE TITLE
[BUG] Friend Notes Don't save due to spaces

### ISSUE THREAD

**Issue by pancake4me** [runelite/runelite#8173]
**Describe the bug**
I love using the friend notes to remember different people on my friends list. It helps alot because not all of them are active 24/7 so i might forget them if they leave for a few months. However certain individuals on my friends list dont keep the note I setup for them. I noticed it was olny on the freinds that have a space in their name (ex. "Mrs BlahBlah"    or "Dr BlahBlah"    or "Blah Blah")

**To Reproduce**
1. Go to your friends list
2. Right click and add notes to certain people who have a space and those that dont
3. Log out and Relaunch the client. 
4. Those that didnt have a space in their name keep their notes while those that did dont keep their notes. their just gone. 

**Expected behavior**
Normally they would save like any other friend notes. 

**Environment (please complete the following information):**
Not sure if the problems are just for my PC and OS or universally wide 
- OS: Windows 10 64 bit
- version 64 bit .exe launcher.

**Comment by Adam-** [comment]
I can't reproduce this using the given steps.

**Comment by Seven-Ate** [comment]
> I can't reproduce this using the given steps.

It was easily reproducible for me, any time my client closed and re-opened I lost notes

**Comment by tehjagjr** [comment]
Can confirm, reproduced using the given steps by @pancake4me. I did notice that it does not affect all users with spaces in their name only a subset of users. 
![Issue8173](https://user-images.githubusercontent.com/7780322/54157720-cda13280-4440-11e9-9e4a-e94377caefc4.gif)

**Comment by Adam-** [comment]
Do you have the name of a person it doesn't work on?

**Comment by pancake4me** [comment]
> Do you have the name of a person it doesn't work on?

These are the only friends for me that the friend notes don't save and each one has a space. 

Alfano alt
A Jug
Take Jug
Mrs Theodora
Dr Craig

**Comment by Adam-** [comment]
This was due to the way the config database is encoding non breaking spaces. I've fixed it in 6371a7dd0b0d49259e2a3326c62e1f3e2c0f28ac just by using normal spaces.
