### ISSUE TITLE
Bring unknown ping worlds to bottom of world list when sorting in ascending

### ISSUE THREAD

**Issue by AdamtheNoob** [runelite/runelite#8176]
Right now you need to scroll down and either click on the quickly rising world with lowest ping or wait for all the worlds to be pinged.

**Comment by Seven-Ate** [comment]
I was thinking about this yesterday; I think a better solution is to postpone resorting of the list until after all worlds have updated or to not clear out a world's ping until the new ping is found. I'm not very comfortable in async programming and having trouble implementing either solution, however.

**Comment by Shingyx** [comment]
I've done this as part of https://github.com/runelite/runelite/pull/9020.

**Comment by abextm** [comment]
put `Closes #8176` in your pr's description, rather than linking to it here
