### ISSUE TITLE
<col> tags are not removed from NPC indicators name highlighting

### ISSUE THREAD

**Issue by daviscook477** [runelite/runelite#8177]
![pay-dirt](https://user-images.githubusercontent.com/10566967/54153425-eea05e00-4415-11e9-8760-1bcb4d359088.png)

**Comment by Adam-** [comment]
What is the bug here? The `col` tags in the name?

**Comment by TheRealJP** [comment]
It looks like the color tag is just missing '#'. Unfortunately, I wasn't able to duplicate this bug with NPC indicators enabled and using #FF9040 as the highlight color.
