### ISSUE TITLE
Barrows plugin updates: Show potential above NPC heads in tunnels & Calculate optimal kills

### ISSUE THREAD

**Issue by AnotherSuggestion88** [runelite/runelite#8185]
An couple of updates which I think would be simple-is to implement and very beneficial are

Showing the potential for each NPC in the tunnels above their heads, similar to the name when the NPC Indicator plugin is suggested. It could be a straightforward "turn on/off" tickbox in case some people don't want the overcrowding on their screens.
Bloodworm: 5.2%
Skeleton: 7.7%
Crypt rat: 4.3%
Crypt spider: 5.6%
Giant Crypt rat: 7.6%
Giant Crypt Spider: 7.9%

In addition to this, having a dynamic calculation of what combination of monsters would get you to a chosen % that could also be entered on the plugin page. As the value for these potential %'s are just the combat level of the monster, it could be simple to hardcode this value in, as well as include the following combinations. I don't have any experience coding in Java, but it seems that something like [This](https://www.programcreek.com/2014/02/leetcode-combination-sum-java/) could effectively be used to calculate the possible combinations, or if this isn't an option, just running through the possible combinations that get you as close as possible would also be beneficial.

E.G:
Goal inputted is 88%
All Brothers = 66.8% 

2 Skeletons, 1 Bloodworm = 66.8 + 2*7.7 +5.2 = 87.4%
4 Bloodworms = 66.8 + 4*5.2 = 87.6%
5 Crypt Rats =66.8 + 5*4.3 = 88.3%
1 Skeleton, 1 Bloodworm, 2 Crypt Rats = 66.8 + 7.7 + 5.2 + 2*4.3 = 88.3%

Thanks! Let me know any feedback on this idea

**Comment by deathbeam** [comment]
Just kill skeletons
