### ISSUE TITLE
Stat tracker bug

### ISSUE THREAD

**Issue by h8dip** [runelite/runelite#8188]
**Describe the bug**
Whenever I go and do something that gets me XP , the Stat Tracker just sets Gained : to 15.7M or something along those lines and Per Hour to 6.3M or something along those lines...

**To Reproduce**
Well, to me all I have to do is gain any xp

**Expected behavior**
I'd expect the stat tracker to correctly track xp gains

**Screenshots**
![imagem](https://user-images.githubusercontent.com/14077597/54232409-7e233b00-4502-11e9-9494-03d75d0f3d59.png)

**Environment (please complete the following information):**
 - OS: Windows 10 x64 Home
 - RuneLite version: 1.5.15.1
 - Launcher version: 1.6.0
- Oldschool revision : Rev 178

**Additional context**

**Comment by h8dip** [comment]
and yes , this wasn't a one time occasion, its been happening for a while now

**Comment by deathbeam** [comment]
I think this was already fixed by @Adam- 's commit. Reopen if issue still persists
