### ISSUE TITLE
Zombie Protester animations glitch when smoothed.

### ISSUE THREAD

**Issue by LShirohana** [runelite/runelite#8206]
**Describe the bug**
Animations freak out a bit with smoothing on -- Seems to be the start of the animation specifically. Probably a lerping issue.

**To Reproduce**
https://csgofoodreviews.com/bp/mit_00140b3194SuperiorAsiantrumpetfish.mp4

**Environment (please complete the following information):**
Windows 10
1.5.15.1 runelite
1.6.0 launcher

**Comment by ShaunDreclin** [comment]
Should this be grouped together with all the other animation smoothing issues like the water wheels in MLM?

**Comment by LShirohana** [comment]
Possibly, and furthermore, I've also confirmed that animation smoothing also breaks on Wyrms. Makes them jittery, like above.

**Comment by Nightfirecat** [comment]
This animation is no longer smoothed with the plugin as of client patch 1115467381.80.
