### ISSUE TITLE
Question about the "Client" interface implementation

### ISSUE THREAD

**Issue by ZoidbergZero** [runelite/runelite#8209]
In this Plugin: net/runelite/client/plugins/loginscreen/LoginScreenPlugin.java, On Line 59 you can See an Instantiation of the Client interface. Im very new to Java Programming so i wanted to find the Implementation of the Client.setUsername or Client.setPassword functions (Which are called at Line 189 and 194) but i couldnt find any! How and where are these Functions implemented? Why does intelliJ not Find any Implementations?

**Comment by Adam-** [comment]
Discord is the best place to ask questions, and not on the github issue tracker, which is used for tracking feature requests and bugs. The implementation of those methods are generated by some tools we have that we no longer release due to threats from Jagex.
