### ISSUE TITLE
Achievement diary -some requirements missing

### ISSUE THREAD

**Issue by TziOSRS** [runelite/runelite#8210]
Easy Achievement Diary for Ardougne - "Go out fishing on the Fishing Trawler" - doesn't display the 15 fishing requirement next to it.

Also, for Falador easy diary, you are required to fix a broken strut in the motherlode mine - does this require 30 mining to enter mlm or can you enter at any level?

Fremenik easy diary - "Enter the troll stronghold" - should display requires death plateau and started troll stronghold

Kandarin Easy diary - kill 1 of each elemental in the workshop - requires starting elemental workshop

**Comment by RyBo** [comment]
Also found:
Kandarin Hard -  Kill a shadow hound in the Shadow Dungeon - requires starting Desert Treasure and 53 thieving
