### ISSUE TITLE
Grand Exchange plugin cuts off price text when multiple options are enabled

### ISSUE THREAD

**Issue by Bonfire** [runelite/runelite#8215]
**Describe the bug**
When items with long descriptions are viewed within the GE as a sell offer or buy offer, the "OSBuddy Actively traded price" plugin text is cut off. This issue only occurs when the "Enable GE Limits on GE" and "Enable OSB actively traded prices" options are **both** enabled for the Grand Exchange plugin.

**To Reproduce**
1. Go to the Grand Exchange
2. Verify that both the "Enabled OSB actively traded prices" and "Enable GE Limits on GE" options are enabled for the Grand Exchange plugin.
3. Click on a Grand Exchange clerk to open the Grand Exchange buy and sell offers
4. Click buy offer
5. Search for a item with a long description (such as Justiciar chestguard)
6. Notice that the "OSBuddy Actively traded price" plugin text is cut off

**Expected behavior**
The plugin text should be clear and concise, and not cut off. As it stands, the text is barely viewable, completely defeating the purpose of the plugin

**Screenshots**
![2019-03-14_17-10-21](https://user-images.githubusercontent.com/5704760/54391722-109b1a00-467c-11e9-87ca-908eef5995ca.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.16
 - Launcher version: 1.6.0

**Additional context**
The character count for the Justiciar chestguard's examine text is 124 characters. I believe this issue occurs when an item's examine text is over 100 characters but I am uncertain of this.

**Comment by whartd** [comment]
I'm guessing one or both of those should be moved elsewhere. 

Perhaps a button under price that will set the value to OSB active price, similar to how the hand+coins button sets it to the GE avg. Could also hover over the price to view the OSB price. Could also replace the "Price Per Item:" text as most users know what that field is for.

The limit quantity might look nice after the boldface item name near the top. I'm not sure if any item names are long enough with large enough limits to hit the same cutoff issue, just horizontally. Perhaps "Quantity:" could be replaced with "Quantity (Limit x):" 

Perhaps item descriptions on 3 lines could be cut off to fit on the second line with a "[...]".

Any of these sound good?

**Comment by Bonfire** [comment]
I think truncating the third line to a "[...]" would yield the best result while also being the least intrusive/different. Any solution that works here I think is a good solution! Of course it's not up to me to decide that though.
