### ISSUE TITLE
Teleblock timer should be removed when entering the abyss

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#8217]
Apparently, entering the abyss via the mage in Edgeville removes teleblock. I'll check on whether this is also true in PvP worlds.

**Comment by whartd** [comment]
> Apparently, entering the abyss via the mage in Edgeville removes teleblock. I'll check on whether this is also true in PvP worlds.

Did you ever check if this is true on PvP worlds? I'm also curious if this is the case in the other world types too (DMM, Unrestricted)

**Comment by Zynorthis** [comment]
Has anyone investigated this yet? If not I will test it in the morning with my clan and work on fixing the timer.

**Comment by Nightfirecat** [comment]
I haven't tested this yet, sadly. This may turn out not to be an issue after all (if I was wrong about the timer persisting after entering the abyss), I'm not sure. Checking this on PVP worlds is probably the only real possible edge case here.

**Comment by Nightfirecat** [comment]
I'm fairly certain at this point this isn't a real issue, so I'm closing it.
