### ISSUE TITLE
Client closes when hovering over sidebar 

### ISSUE THREAD

**Issue by SoMuchSwagMan** [runelite/runelite#8218]
**Describe the bug**
The client closes immediately if i hover over the sidebar icons for 1 or more seconds
**To Reproduce**
1. Open client
2. Hover over sidebar icons for 1 or more seconds 
3. client closes without warning

**Expected behavior**
The client does not close until i hit close

**Environment (please complete the following information):**
 - OS: windows 7 
 - RuneLite version: 1.5.16
 - Launcher version: 1.6.0

**Additional context**
i recently got a new monitor (1920x1080 144hz) and 2 new ram sticks. the client would crash on my new monitor only without hardware acceleration disabled. after i disabled hardware acceleration i find it only closes if i linger on the sidebar too long.
[client.log](https://github.com/runelite/runelite/files/2969338/client.log)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
