### ISSUE TITLE
Suggestion - Fairy Ring code interface improvements

### ISSUE THREAD

**Issue by kyle-glick** [runelite/runelite#8221]
### Problem
The Fairy Ring codes seem to be currently organized by the letters in the code for each location. At least for me, I don't really memorize the codes since installing RuneLite and prefer to look at the locations. It can be very difficult to find the location I want because the list of locations is not ordered by name. In addition, the location names are easier to read than the fairy ring codes.

### Proposed Solutions
I propose that the interface is changed so that it sorts by the location name rather than the fairy ring code. In addition, reverse the positions of the fairy ring code and location name to better emphasize that it is ordered by the location (see screenshot 2).

### Current Interface
Notice that they are ordered by fairy ring code yet the location names are much more prominent and generally what I'm going to look at when searching for a location. If I want to go to Edgeville, I don't look for `DKR`, I look for `Misthalin: Edgeville`.

![image](https://user-images.githubusercontent.com/12898988/54418386-cf822480-46d2-11e9-8b6f-b6ff12856092.png)

### Proposed Ordering by Location
Disregard the bad photoshopping. Locations are ordered by name which makes it very easy for me to find exactly where I want to go, and fairy ring code and name are swapped to make the name more prevalent.
![54418386-cf822480-46d2-11e9-8b6f-b6ff12856092](https://user-images.githubusercontent.com/12898988/54419458-841d4580-46d5-11e9-8f7f-af620e0d73f0.png)

**Comment by deathbeam** [comment]
We already have search in fairy ring interface what is imo enough. Redesigning this interface should be Jagex's job if needed
