### ISSUE TITLE
Change text on bird house timer

### ISSUE THREAD

**Issue by Truesh00ter** [runelite/runelite#8225]
**Is your feature request related to a problem? Please describe.**
N/a.

**Describe the solution you'd like**
Changing the wording of different states of the bird houses in time tracking plug in.
Currently the time between the correctly set bird house: build + seeds and the moment it has run out of seeds after 10 x 5 minutes is "Done at HH:MM". 

**Describe alternatives you've considered**
Since it isn't growing like the other timers in this plug in. 
I would like to suggest to change the text to: "Catching until HH:MM". 

**Additional context**
![image](https://user-images.githubusercontent.com/17280249/54452843-5d532380-4756-11e9-8bc7-e7206cacc39c.png)

**Comment by deathbeam** [comment]
This should be consistent with rest of interface, so current wording is correct
