### ISSUE TITLE
Add Slayer Monsters to the Wiki

### ISSUE THREAD

**Issue by DArgo2006** [runelite/runelite#8229]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Left Clicking the Wiki Button then clicking the Slayer Task (Top Left Corner) should bring up the Wiki page of that monster, would make stuff a lot easier!

**Comment by deathbeam** [comment]
You can just use Wiki search (right click the icon)

**Comment by whartd** [comment]
Ouch, I thought this was a cool idea. Understandable though.

**Comment by Hydrox6** [comment]
Gonna leave this here for anyone else who comes across this and wonders why:

When doing slayer, you don't always kill the actual monster you're assigned to kill. Bloodvelds, Nechraeyal, Black Demons, Cave Kraken, Lizardmen, Hydras; all are tasks that are commonly done on an alternate mob, being Mutated Bloodvelds, Greater Nechraeyal, Demonic Gorillas, Kraken, Lizardmen Shamans, Alchemicsl Hydra. Outside of Konar, we wouldn't even have a way of knowing where you're going to complete a specific task (and even with Konar there are some overlapping areas, like Shayzien Canyon for Lizardmen).

Using the Wiki Search feature allows the user to decide for themselves how they want to complete a task. Get an Aviansie task? You could search Aviansie to find the regular drops, but you could also search up Kree'arra and prepare for some boss killing.
