### ISSUE TITLE
Add 1300 black knight killcount requirement to Falador Elite diary 

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#8231]
The step "Purchase a white 2h sword from Sir Vyvin." requires the player to have a White Knight rank of Master, which requires both completion of the Wanted! quest--which is already marked in the plugin--as well as at least 1300 black knight kills. I'm not sure whether these kills can accrue before quest completion, but I can say that these kills are stored in VarPlayer 573, so we could check for the player's killcount that way.

**Comment by xDemoN** [comment]
Is this still necessary after the [QoL changes](https://secure.runescape.com/m=news/deadman-spring-finals-and-qol?oldschool=1) this week?

> **Black Knight Kill Score** 
>A Black Knight Kill Score is now tracked in the "Wanted!" quest journal and shown in the POH Achievement gallery.

**Comment by Nightfirecat** [comment]
imo it would still be nice to explicitly call this out in the plugin.

**Comment by xDemoN** [comment]
If we're to implement this, I think we should also implement the same thing for chompy kills

**Comment by Nightfirecat** [comment]
Hm, well that's unfortunate. I wasn't able to reproduce varp 573 (or any var, for that matter) changing on either of my accounts. Admittedly, the first account has fully completed the falador diary, however the second has completed Wanted! and is therefore eligible to purchase white equipment and complete that diary step. Thus, I do not think we can actually check for black knight kill completion.

Chompy bird kill completion, however, I have not checked. It's possible a var for this kill count is still transmitted.
