### ISSUE TITLE
linux plugin settings wont load

### ISSUE THREAD

**Issue by orwiga** [runelite/runelite#8235]
**Describe the bug**
the plugin sidebar won't load the plugin settings and the plugins sidebar takes a while to load in

**To Reproduce**
click on any of the plugins in the sidebar

**Expected behavior**
that the clicked plugin should load the settings for it

**Screenshots**
![Screenshot from 2019-03-16 12-04-01](https://user-images.githubusercontent.com/44853129/54480309-ef553d80-47e3-11e9-8c25-1e6a5e891e30.png)
![Screenshot from 2019-03-16 12-04-18](https://user-images.githubusercontent.com/44853129/54480310-ef553d80-47e3-11e9-9be8-df8ac94a75c6.png)
![Screenshot from 2019-03-16 12-04-33](https://user-images.githubusercontent.com/44853129/54480311-ef553d80-47e3-11e9-8bea-a2f33c81640e.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
OS: Windows
RuneLite version: 1.5.16
Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
Graphical artifacts? Try disabling hardware acceleration: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by orwiga** [comment]
I tried it on the .jar version and it worked haven't had this issue until this update I was running fine with acceleration on. Also question for the ubuntu appimage any idea how to turn hardware acceleration off? My understanding of appimages is you cant modify them once you create them you you would have to recreate the image I guess.

**Comment by deathbeam** [comment]
You can just append the argument like you would append it to jar there is no difference.
