### ISSUE TITLE
Show Ground Markers on the minimap

### ISSUE THREAD

**Issue by Andrek25** [runelite/runelite#8243]
Is there a way to do it?

**Comment by xDemoN** [comment]
It's being worked on, #7906

**Comment by Nightfirecat** [comment]
I'm pretty sure that is not what this request is asking for.

**Comment by Andrek25** [comment]
I forget explain that i would like ground markers on the minimap to be easy to click, in this way to be able to move without seeing the ground markers. Thanks!

**Comment by xDemoN** [comment]
My bad, I totally misinterpreted this. Although, it does look like a duplicate of #7968
