### ISSUE TITLE
Party system without discord

### ISSUE THREAD

**Issue by Tsitex** [runelite/runelite#8244]
i really like the party system but i think it could be even better if we could just do a /join *name*  and it will add the person to your party even if you dont have discord i dont know if it could be made because i assume discord is the thing that pull the data (health,prayer etc) soo maybe add a friend system inside runelite so you can add two client so they can speak to each other

**Comment by deathbeam** [comment]
It is intentionally done like this so no we are not going to do it without Discord

**Comment by Adam-** [comment]
More specifically, discord is the only way we can automatically establish a shared secret between clients.

**Comment by Place1** [comment]
Now that this PR has merged I think it may be possible to support parties without discord?

https://github.com/runelite/runelite/pull/14270

Seems like the only thing stopping you from joining a party is the username set here: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/ws/PartyService.java#L99
