### ISSUE TITLE
Add menu entry swapper for diary items

### ISSUE THREAD

**Issue by Velite12** [runelite/runelite#8245]
Currently diary items with multiple teleports don't have entry swaps, not even the early ones with only 1 teleport. I know it requires more work to specify if they have more than one, but something like karamja gloves 3 has only 1 teleport option so would it be possible to be able to swap options for it?

**Comment by Hydrox6** [comment]
Use [Shift Click Configuration](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#shift-click-configuration)
