### ISSUE TITLE
Custom Keybinding for Mouse Movement

### ISSUE THREAD

**Issue by lucastimothy** [runelite/runelite#8248]
Currently there is an option in the default client called "Middle mouse button controls the camera". Possible to add a plugin to have a custom keybind to control the camera opposed to the middle mouse button and middle mouse button only?

**Comment by lucastimothy** [comment]
note: meant Camera Movement in title, not Mouse movement.

**Comment by king-koda** [comment]
Basically to remap the middle mouse button press to another keybind hey?

**Comment by kecleon** [comment]
Using AutoHotKey you can remap very easily:

You can make the "a" key function like middle mouse with just this:
`a::MButton`

Holding down "a" and moving your mouse now rotates the camera.

**Comment by deathbeam** [comment]
Just use external software to do this like other people stated
