### ISSUE TITLE
Clan wars causing entire OS to crash to blue screen (GPU Plugin)

### ISSUE THREAD

**Issue by npollender** [runelite/runelite#8253]
**Describe the bug**
While visiting clan wars upon teleporting from Barrows, some black tiles flicker periodically and then about 5 seconds later the whole OS crashes to blue screen and my system reboots.

**To Reproduce**
1. Finish Barrows run
2. Teleport to clan wars from barrows
3. Approximately 5 seconds later the OS crashes

**Expected behavior**
The OS should not be crashing from playing Runescape...

**Screenshots**
![unknown](https://user-images.githubusercontent.com/35607155/54573205-b5419280-49c1-11e9-999f-b7de4b36ff92.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.15.6
 - Launcher version: 1.6.2

**Additional context**
It should be noted that this problem only occurs while using the GPU plugin, however, it had never been a problem up until today, I had previously visited clan wars several hundred times with no issues. Turning off the GPU plugin solves the problem the the game is barely playable without it enabled...

**Comment by Abextm** [comment]
This is an issue with your hardware and/or drivers

**Comment by npollender** [comment]
How is it related to hardware or drivers if it literally only happens in OSRS at clan wars and any other title I run on the pc doesn't crash?

**Comment by Abextm** [comment]
Because userland applications cannot cause a kernel panic without a bug in your kernel, drivers, and/or hardware
