### ISSUE TITLE
Consistent computer crash when running through mushroom forest/mushroom meadow

### ISSUE THREAD

**Issue by daviscook477** [runelite/runelite#8254]
computer: xps13

with gpu plugin enabled running through this location in mushroom forest/mushroom meadow forces a computer crash with WHEA_UNCORRECTABLE_ERROR.
![gpu_crash](https://user-images.githubusercontent.com/10566967/54576093-32263980-49cd-11e9-8590-d40a0b7848cb.png)

how to reproduce. use the mushtree to go to mushroom meadow (option 4). run south towards the south birdhouse spot -> computer will crash with given error.

when gpu plugin is disabled this area will not induce crash.

**Comment by Adam-** [comment]
https://github.com/runelite/runelite/issues/8253#issuecomment-474166164
