### ISSUE TITLE
Add shift-click withdraw quantity configuration

### ISSUE THREAD

**Issue by chanmioo** [runelite/runelite#8256]
adding a shift-click withdraw configuration will allow players to have a second readily available quantity withdraw (ie. withdraw 1, 5, 10, 299, or all) as a shift-click while having your primary manual in-bank setting be your regular left click.
I don't know if this would be against the rules but it seems convenient.

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
