### ISSUE TITLE
Add a Food Eaten value tracker to the Loot Tracker plugin

### ISSUE THREAD

**Issue by qnnplmr** [runelite/runelite#8261]
**Is your feature request related to a problem? Please describe.**
I would like to know the net loot value of my kills taking into account food eaten.

**Describe the solution you'd like**
Within the Loot Tracker plugin, add an option to track food consumed and subtract its GE value from the Loot value.

**Comment by psikoi** [comment]
That seems oddly specific, and doesn't seem to be what a "Loot Tracker" should do

**Comment by qnnplmr** [comment]
Loot Tracker currently gives a monetary value of loot gained - it would be useful to me if it gave me the option to get a Net value for my expended resources rather than just a Gross value

**Comment by Hydrox6** [comment]
Duplicate of #6700
