### ISSUE TITLE
Different color for timer lines

### ISSUE THREAD

**Issue by yani** [runelite/runelite#8262]
It's hard to differentiate the inactive part of timers against timers that are done but where the status is unknown.

![image](https://user-images.githubusercontent.com/6956790/54630323-d06fd900-4a79-11e9-9318-0fe160a9161e.png)

Both the top and bottom are Done. But it seems the third one is not done when referencing against the second one.

**Comment by whartd** [comment]
I've been poking around the code for this one. Trying to find the best place to change it. Right now the only yellow bar is for diseased plants, but I think it makes sense to change that to red and change in progress patches to yellow.

**Comment by yanikore** [comment]
> I've been poking around the code for this one. Trying to find the best place to change it. Right now the only yellow bar is for diseased plants, but I think it makes sense to change that to red and change in progress patches to yellow.

Seems good. Keeping patches that are done but where the status is unknown as darker green, right? 

Would a different text status be good for those as well? Alive / Done (unknown) / Done (Alive) / Harvestable. Something along those lines? That way if there's only one tint of green you'll know if it has a chance to be deceased or is definitely harvestable.
