### ISSUE TITLE
Change default chat

### ISSUE THREAD

**Issue by Kainzor** [runelite/runelite#8264]
So I'll make this short, 

What I feel like we need is a option that we can change the default chat. The default one that we are currently using is obviously the public chat but I was thinking of a idea that you could change your default chat into something else so it is way more comfortable to communicate.

Like me, I am more of a person that turn off public chat tons of times and communicate only through my clan chat but it can be really tiring to press the "/" button or like most average people do is to press shift + 7 (depending on keyboard).

So my point is, is it possible to add a feature that you can enable or disable that the clan chat is your "default chat" so you don't have to press "/" for every sentence.

**Comment by whartd** [comment]
This issue doesn't mention current alternatives. I believe that clicking the Clan tab will let you send messages in cc without a '/', at least on mobile. However, this prevents you from seeing game chat, unsplit private chat, or public chat. 

Can this issue be reworded to specifically mention clan chat? Toggling between clan chat and public chat is the only realistic use case I can think of for "something else." I think it would get really messy if your default chat is private. 

Also, I assume that you would like to use '/' for public chat when cc is your default. Was there some other way you had been thinking of?

**Comment by Kainzor** [comment]
> Can this issue be reworded to specifically mention clan chat? Toggling between clan chat and public chat is the only realistic use case I can think of for "something else." I think it would get really messy if your default chat is private.


I know what you mean it might be messy but I think it's all about the personal preference which is usually the point of runelite aim to make it so it has options depending on the person. But personally I wouldn't use it for PM's but only clan chat default.

On runelite or osrs there isn't any option that you can send clan chat message without the '/'

**Comment by Matsyir** [comment]
> On the PC neither osrs or runelite don't have the option that you can send clan chat message without the '/'

Yes they do, it's a native OSRS feature. If you left click the Clan chat tab at the bottom of the chat (top on mobile), then you can send clan chat messages without "/", by just typing your message. You mentioned you also turn off public chat so this applies even more, because clicking the clan tab will also filter messages to only clan chat messages. I agree with whartd in that this only really logically applies between public & clan chat, and given you can already type without "/" when selecting the clan tab, I think this feature is unnecessary.

**Comment by Hydrox6** [comment]
@Matsyir 

![2019-03-20_15-48-40](https://user-images.githubusercontent.com/2979691/54698709-aa087700-4b27-11e9-89f0-ebc8499084f0.gif)

**Comment by Matsyir** [comment]
I appreciate the example. I'm very surprised, sorry to mislead anyone. I really remember this being a feature, and not from mobile. Maybe from RS3/pre-oec, I barely use CCs anymore. I take back what I said, this is a valid suggestion I'm sure lots of people would use.

**Comment by whartd** [comment]
Is the config panel the best way to toggle this? I'm not sure if this would get toggled frequently enough to warrant any easier methods in game. (right click clan chat/public chat etc). Is there a use case for needing easy access to the toggle?

**Comment by Kainzor** [comment]
So yeah, I guess my suggestion still stands, this would be a very helpful feature for most people!
