### ISSUE TITLE
Adapt Demonic gorilla plugin for Hydra

### ISSUE THREAD

**Issue by SmurphF** [runelite/runelite#8268]
**Is your feature request related to a problem? Please describe.**
 Everyone hates having to actually count hydras hits that boss is zzzzzzzzz count for me plz runelite

**Describe the solution you'd like**
 Adapt the plugin that counts the demonic gorillas attacks and when they switch styles to 
 teh alchemical hydra, should be easier(idk how to code so dont hate me for this) as it only has 2 styles and isnt dependent on whether or not it hits

**Describe alternatives you've considered**
ive considered just getting good but thats not afk enough for me to play my multi accounts cmon ezscape

**Comment by l2-** [comment]
LOL good luck with this one

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by SmurphF** [comment]
> LOL good luck with this one

it was worth the shot for my lazy ass
