### ISSUE TITLE
Remaining Toxic Blowpipe Zulrah Scale/Dart Counter

### ISSUE THREAD

**Issue by PuffBigDoink** [runelite/runelite#8270]
An optional GUI feature which shows you how many Zulrah's scales and darts you have left in your toxic blowpipe would be very helpful, if possible :)
(Yes I am aware that you can right click->check on the blowpipe but it's all about that QoL mane)

**Comment by Hydrox6** [comment]
Duplicate of #953

**Comment by PuffBigDoink** [comment]
> Duplicate of #953

ty for swift response
