### ISSUE TITLE
There is no "reset others" in loot tracker

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#8272]
every day I waste 2 minutes reseting every monster loot tab this is enormous QoL fix thank you

**Comment by Matsyir** [comment]
To be clear, you are asking for a right click option that will reset every monster's loot besides the selected one, correct? Support

**Comment by MagicfTail** [comment]
You can just turn off Synchronize panel contents under the loot tracker if you don't want it to be filled when you log in

**Comment by Popedigoz** [comment]
> 
> 
> You can just turn off Synchronize panel contents under the loot tracker if you don't want it to be filled when you log in

I tried that already and it did not cure my autism, it is useless for me and many others

**Comment by deathbeam** [comment]
I already closed similar issue before, as we have grouping and also filtering of loot, this feature should not be necessary at all.
