### ISSUE TITLE
Glitch for clue scroll answers

### ISSUE THREAD

**Issue by sneeezers** [runelite/runelite#8276]
Upon attempting a challenge scroll answer, pressing space closes the dialogue without a chance to enter an answer. Upon relogging the user input box appears, but a graphical glitch appears upon trying to fill it. Only observed at Otto godblessed clue step.

**Expected behavior**
To be able to complete the clue

**Screenshots**
https://imgur.com/bdDGao5

 - OS: Windows 10
 - RuneLite version: 1.5.16
 - Launcher version: Unknown

**Comment by Hydrox6** [comment]
Restart your client

**Comment by Abextm** [comment]
this was fixed in 776d27cc4772d9ad3c779a2799ecef9a12aa0904
