### ISSUE TITLE
Camera Zoom Settings Not Working

### ISSUE THREAD

**Issue by yyruneliter** [runelite/runelite#8278]
Outer zoom limit, inner zoom limit, require control down in "Camera Zoom" settings do not work after Runescape update for March 21, 2019. Seems to be at default zoom levels. Vertical camera is functioning properly.

1. Go to 'Runelite'
2. Login
3. Click on 'Configuration'
4. Scroll down to 'Camera Zoom'
5. Click on 'Edit Plugin Configuration'
6. See that settings do not work when changed (except 'Vertical camera')

 - OS: Windows 10
 - RuneLite version: 1.5.16
 - Launcher version: 1.6

**Comment by Abextm** [comment]
This was fixed in 776d27cc4772d9ad3c779a2799ecef9a12aa0904

Restart your client

**Comment by deathbeam** [comment]
Restart your client
