### ISSUE TITLE
Player attacking NPC at muttadile

### ISSUE THREAD

**Issue by Brezzoff** [runelite/runelite#828]
It says the player which is currently attacking the muttadile is the meat tree whenever it goes to heal itself.

**Comment by deathbeam** [comment]
It shows with what is NPC currently interacting with, so the information displayed is correct I believe.

**Comment by Kamielvf** [comment]
It's displaying your target's opponent, so the meat tree would be correct. It does not display what player is currently attacking the muttadile.

**Comment by deathbeam** [comment]
Working as intended.
