### ISSUE TITLE
Devtools: World Map Location does not match when in Motherlode Mine

### ISSUE THREAD

**Issue by yanikore** [runelite/runelite#8280]
In the devtools you can see that the World Location does not match the players location.

3100, 9670 compared to 3740, 5638

![image](https://user-images.githubusercontent.com/6956790/54758550-aa1e7a80-4bec-11e9-85b3-28bc39da2ad1.png)

**Comment by Hydrox6** [comment]
That's specifically Motherlode Mine, btw

**Comment by Abextm** [comment]
This is because these are relocated, and we use post-relocation coords on the world map

**Comment by deathbeam** [comment]
Looks like this works as expected
