### ISSUE TITLE
Password appeared in plaintext on screen when attempting to answer clue scroll

### ISSUE THREAD

**Issue by ws-volt** [runelite/runelite#8281]
Went to answer a challenge clue scroll question, the input box for the answer opened, but when I typed the answer, my username and password appeared behind the answer (in a non-RS font) in plaintext. After restarting the client, I cannot recreate this but feels like its worth mentioning as this could be a potentially serious problem. 
at the same time I kept getting that thing where I couldn't press enter to send messages on runelite, no idea if its related. 

**Environment**
 - OS: Windows 10
 - RuneLite version: [e.g 1.5.16]
 - Launcher version: [e.g 1.6.0]

**Comment by deathbeam** [comment]
This was already solved, it was because rl was outdated

**Comment by Adam-** [comment]
Additionally after the update we fixed this in f7a937463991e193d52752302b5604d317455339 - what happened is the chat box close hooks were not working due to the update, which caused the chatbox input scripts which RL uses to capture keystrokes on the login screen which it then placed into chatbox inputs later.

**Comment by ws-volt** [comment]
Thanks for the explanation, can I ask why runelite needs to capture keystrokes on the login screen? Im not familiar with how 3rd party clients need to operate but that sounds odd at face value.

**Comment by Adam-** [comment]
It doesn't. The bug caused it to not stop capturing (which it does for chatbox input to work) when the game changed to the login screen. It has to capture input for chatbox input dialogs to work. The bug was triggered by the game update. But now we have changed the code to be more safe.
