### ISSUE TITLE
Chat filter should not filter messages from yourself, your friends and clan members

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#8282]
I don't think this needs any explanation, it just makes sense.

**Comment by Hydrox6** [comment]
This should be an option, since streamers would love to be able to block everyone from saying certain things.

**Comment by dmeredith96** [comment]
Should something like this always be on, or should there be an option for it? Expanding on the option idea, should users be able to only allow friends or only allow clan members to bypass the filter (e.g. messages from friends are not filtered, but clan member messages are, or vice versa), or should the setting apply to both groups?
