### ISSUE TITLE
XP tracker header disappears when using the "Reset Others" right-click option

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#8296]
It re-appears once new experience is gained (in any skill)

![2019-03-22_22-02-43](https://user-images.githubusercontent.com/2199511/54861851-0f778600-4d29-11e9-8630-a2b7d8014e47.png)

**Comment by xDemoN** [comment]
Hmm, just spent about an hour running back commits all the way to when the xptracker was implemented and it looks like this has always been a bug - working on a fix now

**Comment by xDemoN** [comment]
EDIT: This IS a regression, I reverted Adam's 3 previous commits for xptracker and it's working properly again

**Comment by xDemoN** [comment]
On top of the "reset other" issue, the total experience doesn't recalculate at all after using "reset" - Thoughts on reverting the other 2 commits?
