### ISSUE TITLE
GPU Mode has terrible screen tearing. 

### ISSUE THREAD

**Issue by Tekken179** [runelite/runelite#8298]
![D2TFGOyXgAISgMq](https://user-images.githubusercontent.com/48856546/54865238-5a5dc180-4d5a-11e9-9b8d-6f0f652a7add.jpg)
![D2TFGOyXgAISgMq](https://user-images.githubusercontent.com/48856546/54865239-5b8eee80-4d5a-11e9-8873-2f09378918f7.jpg)

This is the result of me turning on GPU mode, No Anti-Aliasing is on, drivers updated to their latest versions, tried reverting same results, I understand it's an old low tier GPU, worth a check as it seems to be working on OSBuddy fine!

**Comment by Tekken179** [comment]
![D2TFs2qWoAITxlC](https://user-images.githubusercontent.com/48856546/54865382-d2c58200-4d5c-11e9-8c9c-d4fb8b023e65.jpg)

**Comment by WoneTooPhree** [comment]
From the wiki:

> When i turn on Anti Aliasing weird lines appear
If you have an AMD graphics card, roll back the driver to version 18.12.1

> I have weird lines all over the screen
Try disabling anti-aliasing in your GPU properties and in RuneLite, or reset your GPU properties to default.

**Comment by devLotto** [comment]
@WoneTooPhree I don't think his GPU supports 18.12.1

**Comment by WoneTooPhree** [comment]
Yeah my bad, last drivers are old.

**Comment by Mendaxxxxxxx** [comment]
From memory the 6670 series were 1GB cards, sounds like a vram issue sadly :( even mobile suggests 1.5+ iirc

**Comment by Hydrox6** [comment]
As it says in the GPU FAQ:

>The GPU plugin requires Windows (7, 8, or 10) or Linux, a GPU with support for OpenGL 4.3 or newer, and **2GB of VRAM**.

**Comment by Mendaxxxxxxx** [comment]
Then there's 2 issues iirc OpenGL 4.1 is supported and they're 1GB.

**Comment by xDemoN** [comment]
As shown in his screenshot above, he has the 2 GB version. It appears to be OpenGL support

**Comment by Tekken179** [comment]
> As shown in his screenshot above, he has the 2 GB version. It appears to be OpenGL support

Yep screenshot of specific version was submitted, My card has 2gb VRAM and supports Open GL.

**Comment by xDemoN** [comment]
Check [this link](https://feedback.wildfiregames.com/report/opengl/device/Radeon%20HD%206670) out. If you're on Windows, things probably aren't looking too great.

**Comment by ziggyman77** [comment]
Those would be artifacting. Screen Tearing happens at a monitor level. Maybe the right wording will get you somewhat closer to a solution.

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest release of RuneLite.
