### ISSUE TITLE
Command to display your official risk for PKing

### ISSUE THREAD

**Issue by MangoMau** [runelite/runelite#8302]
I think a lot of one versus one PvP fights would be much easier if a player could just type "!risk" or ":risk" and the client would officially display the **Value of lost items** from inside of the _Items Kept on Death_ user interface. This would be posted into the world's public chat. There may need to be a way to confirm that this has been automated and is official.

It would make for a lot of fairer fights and avoid potential scamming and having to explain how you risk what you claim every single fight.

**Comment by Nightfirecat** [comment]
This value can always be faked from the client side; this is possible with our current commands as well, and there's not really anything we can do to prevent that.

**Comment by critzd** [comment]
Wouldn't adding commands that have a high probability to be faked probably defeat the whole purpose of the command? Especially since there's no way to verify that it's correct. Don't people trade to show what they're risking anyway?

**Comment by alexnygaard** [comment]
This feature reminds me of an old World of Warcraft addon that faked achievements, which are used to prove that you completed a specific raid or boss. This particular addon was used to cheat a lot of people into allowing the player into their raids, and I believe that your proposed feature may be misused in the same way.

**Comment by Abextm** [comment]
This is impossible to implement in a way that would not be immediately abused
