### ISSUE TITLE
Improve Wintertodt Plugin

### ISSUE THREAD

**Issue by odxs** [runelite/runelite#8304]
Wintertodt plugin currently _only_ displays the amount of points if you are planning to fletch the logs before putting in burning brazier. Based off Reddit's suggestions, doing Wintertodt without fletching the logs is better firemaking XP per hour. However, when you follow this style of training, the points overlay reporting is inaccurate.

A simple QOL enhancement would be to have a drop-down that lets the user define how the calculation should be made - they don't plan on fletching the logs, they do plan on fletching the logs, or to dynamically calculate how many points you have in your inventory based off the amount of kindling/logs in your inventory.

**Comment by Alexsuperfly** [comment]
it already shows both
