### ISSUE TITLE
G-Sync and RuneLite

### ISSUE THREAD

**Issue by ziggyman77** [runelite/runelite#8307]
**Describe the bug**
Whole game screen flickering darker and lighter when any sidebar items open that are making graphical updates (Eg. XP counters going up or xp rates changing)

**To Reproduce** (With G-Sync compatible hardware)
1: Make sure G-Sync is turned on with the mode being set to windowed and fullscreen (I play borderless window because of multi monitor setup so I must use this setting)

2: Doing anything while gaining XP (Eg. Nightmare zone/slayer) 

3: Open the XP Tracker tab

**Expected behavior**
Nothing should change with the flickering of the main game screen's brightness or and graphical artifacts. 

**Screenshots**
Only video will explain [https://www.youtube.com/watch?v=Tr0tHQ771uA](url)
It's hard to see, but it's similar to the jumps in ISO when a camera is auto adjusting.
The white balance auto adjust may also make it harder to see, But all you need to know is that it looks like ISO jumps. 

**Environment (please complete the following information):**
 - OS: Win10
 - RuneLite version: 1.5.17.1
 - Launcher version: 1.6.0

**Additional context**
Graphics drivers from nvidia are always on the latest. (Bug has persisted for more than a month. So multiple drivers have been used) 
Monitor is an Asus ROG Swift PG279Qz
Graphics card is a 1060 6GB

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

Also we dont really support Gsync so if its not working just disable it for runelite
