### ISSUE TITLE
Daily task reminders incorrectly say "Requires relog"

### ISSUE THREAD

**Issue by Seven-Ate** [runelite/runelite#8308]
The buckets of sand daily notifications says "(Requires relog)"; this is incorrect. Code change should be easy & I would do it myself, but I'm not sure if any of the others also have the text that don't need it, and I don't want to do a half-assed pull request.

**Comment by xDemoN** [comment]
Just by a quick look at the plugin, all of them relay the relog message. Someone just needs check every one of the daily tasks to see which ones don't require a relog.

**Comment by zuleger5656** [comment]
As you guessed, it is easy enough, it's literally just deleting "RELOG_MESSAGE" to each event that does not require relogging. The only difficult obstacle (at least for someone like me who isn't an avid RuneScape player) is knowing which events require re-log and which ones don't. I changed it for the buckets of sand, but nothing else.
