### ISSUE TITLE
Dragonfruit shows incorrect level in Skill Calc

### ISSUE THREAD

**Issue by russel204** [runelite/runelite#8309]
**To Reproduce**
Under the Farming Skill calc it shows dragonfruit as level 82. They are level 81.

**Environment (please complete the following information):**
 - OS: Win10
 - RuneLite version: 1.5.17.1
 - Launcher version: 1.6

**Comment by deathbeam** [comment]
Fixed in https://github.com/runelite/runelite/pull/8311
