### ISSUE TITLE
Infinite sound loop bug

### ISSUE THREAD

**Issue by Kipcurry** [runelite/runelite#8310]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Kipcurry** [comment]
When I turn on the game sound it keeps playing the sound of picking herbs in an infinite loop. I tried uninstalling runelite but it wont go away. I tried it on the regular osrs client and there is no problem there.
Anyone have an idea on how to fix this please?

**Comment by Kamielvf** [comment]
Do you have the metronome plugin enabled by any chance?

**Comment by Kipcurry** [comment]
> 
> 
> Do you have the metronome plugin enabled by any chance?

Yes, I feel so stupid now. I didnt know that could cause the problem my bad. I turned it off and the problem is gone. Thank you.
