### ISSUE TITLE
KC doesnt track if wearing ring of wealth and coin drop.

### ISSUE THREAD

**Issue by Alext162** [runelite/runelite#8314]
Was killing Gargs and noticed loot tracker KC and the actual coin drop doesnt count when wearing a ring of wealth (coins auto collected).

Kill anything with coin drop and wear ring of wealth.

Windows
 RuneLite version: 1.5.17.1

**Comment by Hydrox6** [comment]
Duplicate of #5077

**Comment by Alext162** [comment]
Oh sorry.
