### ISSUE TITLE
Username Lookup spamming search

### ISSUE THREAD

**Issue by russel204** [runelite/runelite#8316]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When trying to manually type a players name in the high scores lookup, it spams the account name multiple times.

**To Reproduce**
1: Go to the highscore lookup
2: manually type in a name that has been looked up or starts with the same letter as a name that has been looked up previously
3: view the chaos

**Expected behavior**

**Screenshots**
https://gyazo.com/81e62af08b11745806e0098f1c80aa18
^a gyazo gif

**Environment (please complete the following information):**
 - OS: Win10
 - RuneLite version: 1.5.17.1
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by deathbeam** [comment]
I think this can be solved with https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by russel204** [comment]
Noted. i'll give that a try.

**Comment by deathbeam** [comment]
Did it worked/

**Comment by russel204** [comment]
@deathbeam i apologize. I honestly forgot to update. Just saw the notification in my email but yes this does seem to have fixed it. Thank you!

**Comment by deathbeam** [comment]
Awesome, thanks. So I guess I can close it because its not really solvable otherwise
