### ISSUE TITLE
Add options to Wiki plugin

### ISSUE THREAD

**Issue by SomeZer0** [runelite/runelite#8320]
I don't like having the wiki button near my minimap, but I do like the option to right click quests and pull up the guide.

Would be nice to have configurable options to enable different parts of the plugin.

**Comment by critzd** [comment]
I'll take a crack at it and see what I come up with.

**Comment by Reasel** [comment]
Would something like a shift + right click be better? Or do you want a setting to always show the wiki option?

**Comment by SomeZer0** [comment]
Since Jagex has added a wiki button to the vanilla client, this is no longer needed.
