### ISSUE TITLE
Add text to tile markers

### ISSUE THREAD

**Issue by Treedot** [runelite/runelite#8321]
I like to mark certain item spawns or safe spots for my ultimate ironman and it would be nice to be able to apply text to the markers I place so I can remember what they're there for.

**Comment by TerrorNisse** [comment]
That was a good idea. I would also like to be able to mark tiles in different colors, depending on what I do with them

**Comment by Hydrox6** [comment]
@TerrorNisse Coloured Ground Markers were released a week ago

**Comment by TerrorNisse** [comment]
Ok damn I didnt know that. That's sweet! Well I tested it, and it should possibly have some premade colors to just click instead of the whole color wheel thing.

**Comment by deathbeam** [comment]
I think custom colored markers are good enough for this

**Comment by Treedot** [comment]
That’s just your opinion, I don’t see why that means you get to close this.
