### ISSUE TITLE
Player Inspect

### ISSUE THREAD

**Issue by JasonLorinzo** [runelite/runelite#8323]
I'm not sure how feasible this is, however I know it to be an option, and have seen it within World of Warcraft.

As the title suggests, i'd love the ability to inspect other players. (Right click > inspect) which will show that players current gear and stat bonuses etc.

Would be a neat touch for those curious...I.E me...

Not sure if this is a duplicate, or if it isn't feasible, or if it's already a thing or not, so please let me know!

**Comment by deathbeam** [comment]
Duplicate

**Comment by thu3n** [comment]
Sorry, but where is the original post if this is duplicate?

**Comment by Alexsuperfly** [comment]
#4353
