### ISSUE TITLE
Zero out bank tabs for correct boss loot, Wiki button->GE lookup item and Stats tracker for the highscore lookup

### ISSUE THREAD

**Issue by TerrorNisse** [runelite/runelite#8327]
**Zero out bank tabs for correct boss loot**
Basically to let you see exactly what you get from lets 1k raids in a bank tab. So when you create the bank tab you zero it out, so even if you have several of that item in the bank, it will say 0 of the item in the actual tab you made.

**Wiki button-> GE lookup item**
Allows you to use the wiki button under the minimap to lookup the items you have searched for in the G.E database to the right

**Stats tracker for the highscore lookup**
Maybe consider using RuneTracker, as they have already done it for years.(RuneScript) http://runetracker.org/api.php. It would be sick to have that combines with the stats lookup. Also including 1d, 7d, 14d, 1m and AllTime buttons.

Some might have been suggested before, but I didnt find it.
- _Terror_nisse_

**Comment by Abextm** [comment]
Please do not submit multiple issues in a single issue

1) This is not really possible
2) Duplicate #7854
3) Duplicate #720
