### ISSUE TITLE
Issue with text styling when using an item on a clan member

### ISSUE THREAD

**Issue by jackkenney10** [runelite/runelite#8328]
**Describe the bug**
When you click an item and right click one or more players to bring up the list of players you can Use the item on, the text styling that should apply to your fellow clan chat member is applied to your item instead. 

**To Reproduce**
Left click an item in your inventory, then right click a player in your clan chat.

**Expected behavior**
The clan chat member's name should be stylized, rather than your item.

**Screenshots**
https://i.imgur.com/oTjXXOy.png

**Environment (please complete the following information):**
Windows 10
Runtelite 1.5.17.1
Old school revision 178
Launcher version 1.6.0

**Additional context**
Not a huge deal obviously, but figured I'd report anyway.
![screenshot](https://user-images.githubusercontent.com/4061716/55114595-59a59200-50b0-11e9-813d-713b334b56c8.png)

**Comment by deathbeam** [comment]
This was intentional afaik
