### ISSUE TITLE
XP Globe Actions Left Counter/XP Average

### ISSUE THREAD

**Issue by chanmioo** [runelite/runelite#8329]
Instead of solely displaying the skill icon in the center of xp globes, allow it to be changed to display a counter of actions left or your xp average without needing to open the runelite sidebar.

make it so the skill icon is still visible to avoid confusion - ex. skill icon still in the background of globe.

ex. (31.6K) 
or 
(327)...(326)...(325).

**Comment by Nightfirecat** [comment]
This isn't exactly what you're asking for, but you can already hover an xp orb to see that information.

**Comment by chanmioo** [comment]
I am aware of this but I wanted to ask if we could have something like that stay there

**Comment by deathbeam** [comment]
You can alraedy hover it, so no, I dont see the point
