### ISSUE TITLE
Farming Guild Seed Vault Seed Value

### ISSUE THREAD

**Issue by EVOuser94** [runelite/runelite#8332]
I would like to be able to see the G.E. Value of my seeds in the new seed vault. If it's possible be able to see vault value within any bank interface aswell.

**Comment by tgeene** [comment]
I don't know if I should add a separate issue, but can we have the hover/examine text show GE/HA pricing in the Seed Vault system for each item.

**Comment by deathbeam** [comment]
New issue. Also, if anything, it should be just examine, like everywhere else.
