### ISSUE TITLE
Special Attack Counter tooltip totals incorrect when in discord party

### ISSUE THREAD

**Issue by Twiglet1022** [runelite/runelite#8334]
**Describe the bug**
When using the special attack counter with a party and the party is using multiple types of special attacks, the totals for each type of special attack in the tooltip are incorrect. This is because they appear to be showing the total for whichever special attack the player last used rather than remembering how much that player dealt with each type of special.

**To Reproduce**
1. Join a party using discord.
2. Use BGS specs on corp.
3. Have your party member use DWH.
4. The tooltip will show that you have hit as many times with the DWH as you have done with the BGS.

This doesn't appear to be an issue when not in a discord party. I attempted to reproduce this when not in a party and the tooltip was correct even when using both BGS and darklight.

**Expected behaviour**
Each individual special counter should only show the total that each player has contributed to that special attack in the tooltip.

**Screenshots**
![image](https://user-images.githubusercontent.com/29353990/55200267-4b8d6980-51b5-11e9-87fc-dca49a99a10b.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.18
 - Launcher version: Unknown

**Comment by Adam-** [comment]
Fixed in b384ff776edd97fa47d5c2fb109da9c879cd69b4
