### ISSUE TITLE
Runelite not launching on i5 machine with fresh windows install.

### ISSUE THREAD

**Issue by Sokoloft** [runelite/runelite#8337]
**Describe the bug**
Runelite will not launch at all on this system with a fresh windows install. Even the regular OSRS client is having issues launching on this machine as well. I originally made a post [here](http://services.runescape.com/m=forum/c=tEpF5xDfqeU/forums.ws?409,410,463,66063122,14,344273329,#14) on the runescape forums. PINGUICULA sent me the following cmd command and it launched no problem.

`cd "%userprofile%\jagexcache\jagexlauncher\bin" && "%programfiles%\Java\jre1.8.0_201\bin\javaw.exe" -cp jagexappletviewer.jar -Dsun.java2d.noddraw=true -Dcom.jagex.config=http://oldschool.runescape.com/k=3/l=$(Language:0)/jav_config.ws -Xmx384m -Xss2m -XX:CompileThreshold=1500 -Xincgc -XX:+UseConcMarkSweepGC -XX:+UseParNewGC jagexappletviewer /oldschool`

I've tried both the install of Runelite and the .jar, both do not work. Nor do I get any error txt generated. However the jar says the following: java virtual machine launcher; a java exception has occurred. Everything is up to date, downloaded within the last week since its a fresh windows install.. Any help is appreciated, thanks so much! As well as thanks for the awesome client, I like it heaps more than Osb. Just got back into OSRS a month ago.

**To Reproduce**
I would imagine you'd need the same hardware I'm using.
msi b150m pro-d, i5-6400, msi 610GT, 8gb ram.

**Expected behavior**
The launcher to launch and run the game as intended.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10 Home Edition x64 bit
 - RuneLite version: Latest
 - Launcher version: Latest

**Comment by Abextm** [comment]
If the vanilla client isn't working properly it is not our bug
