### ISSUE TITLE
Show Drop Rate Chance Next To "Valuable Drop Text"

### ISSUE THREAD

**Issue by OgeGhost** [runelite/runelite#8339]
Ever kill a monster like Cerberus and get a crystal at only 50 KC ? don't you wonder what your chances were at getting that drop? Or you get a rune spear from the RDT?

A solution to this would be done by adding a calculation at the end of a rare drop
EX: https://gyazo.com/4bdc5f9c3eaff60ac67151cb80215e04
It would calculate your total KC to the drop rate and output a percentage, that would then display beside your "Valuable drop: Pegasian crystal (119,436 coin)(5.68% Chance)

**Comment by Abextm** [comment]
Making the client know droprates would be difficult, see #7905

**Comment by OgeGhost** [comment]
> Making the client know droprates would be difficult, see #7905

It can pull the calculation off the wiki drop rates. Of course we don't know.
But that shouldn't hold you back from creating something semi-convenient and cool
