### ISSUE TITLE
unable to launch please check log

### ISSUE THREAD

**Issue by oschaotic** [runelite/runelite#8342]
unable to launch please check log

i open runelite and it says unable to connect please check logs 
(note i was running osrs on runelite 2 hours prior and have been for 9 months)
this is the log  
[client.log](https://github.com/runelite/runelite/files/3022202/client.log)

**Comment by Raelenna** [comment]
same problem

[client.log](https://github.com/runelite/runelite/files/3022430/client.log)

**Comment by TheStonedTurtle** [comment]
```
[RuneLite] ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.net.SocketTimeoutException: timeout
```

You both are having the same connection timed out issue which means you failed to connect to the Old School RuneScape Servers. Since these are hosted by jagex this isn't something we control/fix.

#8035 adds a more descriptive error pop-up, which may be the "fix" for this issue?

**Comment by oschaotic** [comment]
half my guild is having the same issue also :(

**Comment by oschaotic** [comment]
i have never experienced this before im so confused XD

**Comment by TheStonedTurtle** [comment]
The problem is either http://oldschool.runescape.com/jav_config.ws doesn't load for you or the gamepack jar isn't. The gamepack jar url is based off the above config url's `codebase` and `initial_jar` values. 

I.E. http://oldschool55.runescape.com/gamepack_9623388.jar

**Comment by oschaotic** [comment]
im on osb fine :( just runelite not co operating

**Comment by AZ887** [comment]
check your firewall and add client into exception, this solved my problem and i googled mostly is network related issue

**Comment by Raelenna** [comment]
Disabling Bitdefender's (my antivirus) firewall and using only windows firewall fixed it for me.

**Comment by oschaotic** [comment]
turned off firewall completely isssues continuing but can log in but sometimes it will continue accour 4/10 times -no anti virus
