### ISSUE TITLE
Warrior's Guild Plugin

### ISSUE THREAD

**Issue by qnnplmr** [runelite/runelite#8344]
**Describe the solution you'd like**
A plugin to aid in the Defender grind at the Warrior's Guild. It would track Tokens and Time Remaining based on those tokens, track how many Cyclopes you've killed, highlight Defender drops while in the Cyclopes room.

**Comment by Hydrox6** [comment]
The Loot Tracker will already track how many Cyclops you've killed (as long as you don't have Big Bones blocked), and adding `* defender` to the Highlighted Items list in Ground Items will highlight all the defenders

**Comment by qnnplmr** [comment]
I did not realize this feature of highlighting items, thank you. I guess that about covers it.
