### ISSUE TITLE
Runelite graphical glitch making it unplayable.

### ISSUE THREAD

**Issue by jackdungan** [runelite/runelite#8349]
Changed monitors over and got this overlay/black screen glitch, can't seem to find anywhere on the net with the same problems. Any help would be appreciated.

![1](https://user-images.githubusercontent.com/49083301/55269455-960f0300-52e7-11e9-9ece-348a03178688.png)
![2](https://user-images.githubusercontent.com/49083301/55269456-96a79980-52e7-11e9-83f0-2ef8731f1491.png)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by jackdungan** [comment]
didn't work..

**Comment by Alexsuperfly** [comment]
thats the amd antialiasing thing so this is the more relevant link https://github.com/runelite/runelite/wiki/GPU-FAQ
