### ISSUE TITLE
[URGENT FEATURE REQUEST] Dynamic Volumed Player Text to Speech

### ISSUE THREAD

**Issue by PhilT24** [runelite/runelite#8350]
Toggleable: makes all player text spoken using text to speech.
There's gotta be an API to hit to get back audio for microsoft sam voices.
Male and female?
Don't ID the players in the speech, just say what they said.
Depending how far away people are the lower in volume the text is.
Just imagine how funny wintertodt would be.
Doesn't seem too hard. Get text and how far player is from your player. Send text to api, get back audio. adjust volume for how far away that player is, play audio.
This is very important.

**Comment by deathbeam** [comment]
Based on discord discussion we are not going to implement this, and I believe we closed similar request in past
