### ISSUE TITLE
Scaled mode interface sharpening

### ISSUE THREAD

**Issue by rrazgriz** [runelite/runelite#8351]
**Problem**

When using scaled mode, interface graphics are blurry/scaled in a low-quality and jarring way, especially compared to the game itself when rendered in GPU mode. This is most noticeable with [hitsplats](https://i.imgur.com/4VNKBt8.png), but of course occurs in all interface elements, including [vanilla](https://i.imgur.com/i49A4qX.png) and [runelite](https://i.imgur.com/1okzbLI.png) overlays. 

**Solution**

If possible, allow the user to enable a sharpening setting that would add a configurable sharpness filter to interface elements, similar to [OBS' simple implementation](https://i.imgur.com/1dB3om1.png). This is possible in OBS in real time acting on 1080p 60 fps video. 

**Alternatives**

HQX filtering, another possible solution to this issue, [has been suggested in the past](https://github.com/runelite/runelite/issues/5781), and was initially marked as `wontfix` due to computational overhead but was tentatively reopened in light of the GPU plugin. There are a plethora of [pixel-art scaling algorithms](https://en.wikipedia.org/wiki/Pixel-art_scaling_algorithms) documented in this vein which could be appropriate for interface scaling.

**Example of desired effect**

An example of sharpening with Photoshop's smart sharpen set to 30% at 1px radius is given here: [before](https://i.imgur.com/wBjU10e.jpg) and [after](https://i.imgur.com/DVPmKEY.jpg) (make sure to view at 100% zoom). Note that sharpening is applied here to the whole image, and ideally would not be applied to the 3d graphic interface, only the 2d elements overlaid on it.

I am not familiar enough with the rendering methods in Runescape/Runelite to know if the processing overhead is too significant to implement sharpening, nor if the GPU plugin alleviates this significantly, so it may not be feasible to implement real-time sharpening.

**Comment by deathbeam** [comment]
We already have issue open for HQX
