### ISSUE TITLE
Share quests and stats to local API (Like RS3 Runemetrics)

### ISSUE THREAD

**Issue by iawhd** [runelite/runelite#8358]
**Is your feature request related to a problem? Please describe.**
Some RS3 wiki pages (Quest guides & Calculators) have an option to automatically import user data about quests completed, allowing Javascript on the wiki to check off completed quests and required levels automatically. It's a small convenience that goes a long way.

 Example pages can be found below.

**Describe the solution you'd like**
Players would be able to opt-in to share their data to an API, like the Runemetrics API, the wiki guys (and other services) could then use that data instead.

**Describe alternatives you've considered**
A way to link a Runelite account to a oldschool.runescape.wiki account, either within the existing wiki plugin or as a new plugin. This plugin would read player stats; quests; and diary status from the client and then pass them to the wiki, where the wiki devs would handle the data on their end.

This would require collaboration with the wiki developers and be more restrictive.

**Additional context**
- **Example RS3 wiki calculator (note the lookup button):** https://runescape.wiki/w/Calculator:Herblore
- **Example RS3 wiki quest page (note the lookup button):** https://runescape.wiki/w/Sliske%27s_Endgame
- **Info about the runemetrics API:** https://runescape.wiki/w/Application_programming_interface
- **API example user:** https://apps.runescape.com/runemetrics/profile/profile?user=X&activities=20
- **API example quests:** https://apps.runescape.com/runemetrics/quests?user=X

![image](https://user-images.githubusercontent.com/29826207/55280426-637ffd00-531d-11e9-96b1-10dbebdc648c.png)

![image](https://user-images.githubusercontent.com/29826207/55280418-48ad8880-531d-11e9-8468-dff64e19a6bd.png)

**Comment by IAWHD** [comment]
Extra screenshots:

![image](https://user-images.githubusercontent.com/29826207/55280353-8958d200-531c-11e9-9785-ad9010998623.png)

**Comment by IAWHD** [comment]
![image](https://user-images.githubusercontent.com/29826207/55280403-1ac84400-531d-11e9-920c-9e5328ca9d03.png)

**Comment by deathbeam** [comment]
I dont think we should do anything else other than exposing local api to cover this, sending non-anonymized data to 3rd party do not sounds very reasonable.

**Comment by IAWHD** [comment]
Yeah, the local API is probably the more reasonable answer.

**Comment by IAWHD** [comment]
I just updated the post to have more of a focus on the local API

**Comment by repsejnworb** [comment]
+1.

Just being able to export the quest list as JSON would give me enough value.

**Comment by Adam-** [comment]
I added a local api plugin on the pluginhub awhile ago which export stats, if you want to use that/expand on it.

**Comment by Hydrox6** [comment]
The wiki people have developed `WikiSync` to export quest data to use on the Wiki. Not sure how much of a market there is outside of that for other data export for local stuff.

**Comment by Nightfirecat** [comment]
I believe this is sufficiently covered by the previous comments. Any further coverage should be supplied via hub plugin.
