### ISSUE TITLE
Rune Pouch Overlay Disappears in Seed Vault

### ISSUE THREAD

**Issue by mwalker55** [runelite/runelite#8359]
Overlay showing the runes in your rune pouch disappears when you open the Seed Vault.

**To Reproduce**
1. Go to the Farming Guild with runes in your pouch pouch
2. Open the Seed Vault
3. Rune pouch overlay disappears

**Expected behavior**
Rune pouch content overlay remains visible, still showing which runes are in the pouch.

**Screenshots**
https://i.imgur.com/223jETr.png <-- rune pouch overlay not visible when in seed vault
https://i.imgur.com/9y9kvso.png <-- rune pouch overlay visible with bank open, comparable scenario

**Environment (please complete the following information):**
 - OS: ArchLinux
 - RuneLite version: 1.5.18
 - Launcher version: 1.6.0

**Comment by xDemoN** [comment]
Item Charges isn't working on the Skills Necklace either
