### ISSUE TITLE
No idle notification when mining dense essence

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#836]

**Comment by sethtroll** [comment]
what pickaxe are you using?

**Comment by rune3132** [comment]
Dragon with an ornament kit

**Comment by Lalonde33** [comment]
This was happening yesterday for me w/ infernal pick uncharged.

**Comment by deathbeam** [comment]
Oh infernal pick uncharged probably have different item id, so i guess that is why it was not working for you. I didn't knew it can be uncharged tbh, i thought it will revert to like smouldering stone or something.

**Comment by deathbeam** [comment]
Is this still valid?

**Comment by Nightfirecat** [comment]
Could not reproduce with normal dragon pickaxe.

**Comment by RaspberrySchnapps** [comment]
Broken again in today's update. Tested with Rune and Ornamented Dragon pickaxes as well as 3000ms and 5000ms(default) delay. No idle notifications whatsoever.

**Comment by albumdownloader** [comment]
The notifications for mining dense essence are still not present. I have reproduced this issue with a dragon as well as a rune pickaxe.

**Comment by deathbeam** [comment]
On master or on release? The fix is not in release yet
