### ISSUE TITLE
Tool bug

### ISSUE THREAD

**Issue by pleccc** [runelite/runelite#8361]
After opening RuneLite, the tools on the right side work fine and as intended, it seems as if when I alt tab out and click back in or alt tab back in, they break and become very odd when interacting. I have tried changing certain settings but nothing has worked.

![Buggo](https://user-images.githubusercontent.com/49109211/55283506-8c050700-53b0-11e9-9982-5035fb075c31.PNG)

**Comment by Abextm** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
