### ISSUE TITLE
runelite has x ray vision

### ISSUE THREAD

**Issue by lemonpepper420** [runelite/runelite#8365]
I'm not sure what is going on with runelite. I'm new to the client but I know it is not supposed to look like this. I'm not sure what information I should add but I have the latest version of Java 

![Screenshot (1)](https://user-images.githubusercontent.com/49134965/55299214-ea0d0b00-53ff-11e9-88ad-bf9b411e9f75.png)

**Comment by Adam-** [comment]
Is the GPU plugin on? Try turning it off.

**Comment by Alexsuperfly** [comment]
this is the amd antialiasing bug listing in our wiki in the gpu faq page, roll back your driver to the listed one there

**Comment by lemonpepper420** [comment]
Well that certainly did it, thanks you kind sir
