### ISSUE TITLE
Add option to show Time till level in xp vs % till goal complete

### ISSUE THREAD

**Issue by Jhandy93** [runelite/runelite#8373]
In the xp info box it has the % till your goal is complete, I would maybe like an option to switch that to the total time till goal is complete.

**Comment by JesseBurke** [comment]
If you hover over the progress bar the time till goal is completed will pop up

**Comment by Jhandy93** [comment]
I understand that, I would like to switch that with the % in the progress bar

**Comment by larkable** [comment]
Bump.

**Comment by larkable** [comment]
Time to Level needs to be added. 

Thanks.
