### ISSUE TITLE
Always getting 3-6 second input lagg.... it got very annoying so I stopped using

### ISSUE THREAD

**Issue by claytray** [runelite/runelite#8379]
I have a fine internet connection i use runelite i get an input lagg so i click and nothing happens for me for 3- 5 seconds...
and everyone around me is moving just fine...

i use the normal runescape launch app.. and it's fine...

**Comment by Nightfirecat** [comment]
Sorry to hear about this problem. Unfortunately, without more information, we can't really help you. I am closing this issue for now. If you have further information on this problem, please post it and re-open this issue.
