### ISSUE TITLE
Giant Seaweed timer needs to be adjusted.

### ISSUE THREAD

**Issue by Huaqas** [runelite/runelite#8383]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The farming timer for the Giant Seaweed patches is inaccurate. Its 10 minutes longer than is should be.

**To Reproduce**
1. Go to the Giant Seaweed patch off the coast of Fossil Island.
2. Plant a Seaweed Spore into one of the two patches.
3. The farming tab will then list the seaweed patch to be ready after 60 minutes.
4. Come back in 50 minutes to see the seaweed to be fully grown and ready for harvest.

**Expected behavior**
The timer should be 50 minutes long. Somebody accidentally wrote the code in include an extra 10 minute farming tick when it shouldnt.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143737/55416230-fbd9e400-55a0-11e9-929e-fa1a03efc3b8.png)
Screenshot 1 shows the current time being 11:44PM and runelite displaying the time the seaweed patch will finish growing at 11:55PM.

![image](https://user-images.githubusercontent.com/25143737/55416477-6f7bf100-55a1-11e9-9bdb-4dcbafe46c74.png)
Screenshot 2 shows the currrent time being 11:46PM. Runelite says the seaweed patch in now harvest-able despite it displaying 11:55PM 2 minutes prior. The Seaweed timer in Runelite is one 10 minute farming tick too slow.

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.18
 - Launcher version: 1.5.2

**Additional context**
`

**Comment by Abextm** [comment]
This is working as intended
