### ISSUE TITLE
Visualizing where you are in your current cycle.

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#8385]
An overlay of some sorts that display what tick you are in, in your current cycle and how many there are left, this is useful for pvm and skilling. 
A quick image to show what i mean. This would be a 4 tick cycle (like wcing a tree or attacking with a whip).
https://imgur.com/a/hVWm42I
![HUNjOvY](https://user-images.githubusercontent.com/38779087/55442077-7446a200-55ad-11e9-8382-7f4e98b74d1c.png)

**Comment by Alexsuperfly** [comment]
xp drops plugin does this well enough imo

**Comment by Drazneel** [comment]
I love this idea -- this would be a great addition.

**Comment by Abextm** [comment]
Use (fake) xp drops for this
