### ISSUE TITLE
1-73 Virtual Levels 

### ISSUE THREAD

**Issue by Drazneel** [runelite/runelite#8388]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
This idea came to me as I was fishing. I just hit level 73 (1/13th) to level 99. The XP to the higher levels is demotivating to look at. 

**Describe the solution you'd like**
I would like a way to virtually "reset" the level and relive the experience of going from 1-73. 12 more times but every time will become quicker and more enjoyable. 

**Additional context**
This can show you what cycle of 73 you are on as well (73)3 for example would mean you've gotten to 73 fishing 3 times so far.

**Comment by Abextm** [comment]
Duplicate #4305
