### ISSUE TITLE
Quest List: Quests are not filtered on completion

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#8390]
**Screenshots**
![screenshot](https://i.imgur.com/DTvvCtf.gif)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.19-SNAPSHOT

**Comment by ShaunDreclin** [comment]
Tried `!linkerror` and that didn't fix it, issue is still present on latest build.

![screenshot](https://i.imgur.com/lSAP5nD.gif)

**Comment by ShaunDreclin** [comment]
Also probably related, sometimes when I open the quest list the filtering isn't applied at all.

![screenshot](https://i.imgur.com/WssG2qe.png)

**Comment by Quasindro** [comment]
I will look into this once I get home from work.

**Comment by ShaunDreclin** [comment]
Not totally sure on that one yet, I'll post here if I manage to figure out a reliable way to reproduce it.

**Comment by zhulb001** [comment]
I've also had the issue where quests are sometimes not filtered even though the filter is selected. Haven't figured out whats causing it yet. I did a few quests yesterday so it might have occurred on completion or something. I'll update if I figure it out.

**Comment by ZachPL** [comment]
I've also had the issue where quests are sometimes not filtered even though the filter is selected. Haven't figured out whats causing it yet. I did a few quests yesterday so it might have occurred on completion or something. I'll update if I figure it out.

**Comment by trimbe** [comment]
The filter not being applied is caused by hopping, the widgets all get recreated and at the time the quest list widget is loaded, the header is hidden so the filter doesn't update.

**Comment by ZachPL** [comment]
Oh that makes sense, that is what was happening. Thanks

**Comment by canderis** [comment]
Can confirm the filter does not apply correctly on hopping worlds.

**Comment by spudjb** [comment]
The reason for not filtering when the header is hidden was to avoid an exception in the scrollbar update script. Not familiar at all with how the scripts work, so not sure what's best. Perhaps always filter and check if the scrollbar script should run on tab switch?

**Comment by stringsanbu** [comment]
To add to this, I noticed the quest filter breaks even on teleport, at least to Lumbridge. I tried it teleporting in place in Lumbridge with it filtered, then clicked on the quest tab to see it became unfiltered again.

**Comment by ShaunDreclin** [comment]
Can confirm, filtering breaks on teleport if the quest list is not open. This is the most likely cause of the unexplained issue I was experiencing with it.

![screenshot](https://i.imgur.com/CsaQXrX.gif)
