### ISSUE TITLE
Blacksreen, but can still click on the left tap

### ISSUE THREAD

**Issue by Hyrdehunden** [runelite/runelite#8392]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When i write something where i have used shift, like to make a big letter or !"#¤%&/() or something like that, it goes black after i press enter, and sometimes even before
**To Reproduce**
1. Write something with shift, like a big letter or a sign
2. press enter
3. Screen goes black

**Expected behavior**
I just wanted to write a a letter or capsed a word

**Screenshots**
![bug](https://user-images.githubusercontent.com/49242895/55488054-9a148b00-562f-11e9-9d26-00440c4da582.PNG)

**Environment (please complete the following information):**
Windows 10
 - its the newest version (downloaded it yesterday, but cant find where it says version)
 - Launcher version: [e.g 1.5.2] (cant find where it says launcher version)

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Kamielvf** [comment]
If you are still able to reproduce this, could you please post your logs as instructed in the `Additional context` section?

**Comment by Nightfirecat** [comment]
As this has not received any new information in many months, I am closing this issue. Please re-open it if you have further information on this problem.
