### ISSUE TITLE
Discord party plugin disconnection

### ISSUE THREAD

**Issue by Twiglet1022** [runelite/runelite#8395]
**Describe the bug**
Discord party plugin disconnected and stopped updating the party's info. I had to restart the client to get it working again. Toggling the party plugin on and off and joining from discord didn't help.

With reference to the attached log, I logged in around 8:30pm, discord plugin disconnected at around 9:37pm while spamming my log with NPEs.

It's happened before but this is the first time anything showed up in the log. I also found myself logged out of my runelite account when I restarted the client which hasn't happened before.

Any ideas what could cause that?

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.18
 - Launcher version: Unknown

**Additional context**

[client.log discord party bug.txt](https://github.com/runelite/runelite/files/3040828/client.log.discord.party.bug.txt)

**Comment by Twiglet1022** [comment]
Similar issue with the party plugin again yesterday while using it to track specs at corp but this time my log shows a bunch of NPEs from SpecialCounterPlugin instead.

[client_2019-04-05.0.log](https://github.com/runelite/runelite/files/3050971/client_2019-04-05.0.log)

**Comment by LlemonDuck** [comment]
Party plugin no longer uses discord parties so this is no longer valid.
