### ISSUE TITLE
Give a higher value to mysterious emblems above tier 1

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#8396]
ItemManager currently values Mysterious emblems above tier 1 much lower than their actual value. For instance, emblem selling clan chats will often sell tier 7 emblems (which, after degrading on death to tier 6 trade in for enough points to buy a rune pouch) for roughly 1m and tier 10 emblems for roughly 2m each. While the value of emblems in between likely do not linearly scale, it seems safe to say that emblems of tier 2-6 would be worth at least that of a tier 1, and emblems of tiers 8 and 9 are worth at least that of a tier 7. It would be helpful if ItemManager could override the value of these emblems so players can have a more accurate understanding of their worth.

**Comment by deathbeam** [comment]
Entire value of emblems above tier 1 is based on trust trading and I dont think we should support that, and otherwise it will be just made up number. We can maybe set the price to price of items you can buy for points for them, but that sounds like nonsense too because noone is doing that to get money from them.

**Comment by Lucwousin** [comment]
You could argue the same thing about graceful having a value based on selling it back to grace and using those marks to buy amylase packs. I personally don't care for this, but it seems pretty backwards to me that something which actually does get traded for money doesn't get it's price overridden while something 99,9% of the people won't sell does.

**Comment by deathbeam** [comment]
The point is that marks of grace have fixed value that will never change (in relation to price of amylase).

What is this requesting is to set some made up price based on trust trading, that can change at any point. And the other alternative is just us hand picking some random item from bounty shop and price it based on it. TLDR: just re-read my first reply again so I dont have to repeat myself.

**Comment by Lucwousin** [comment]
The bounty hunter doesn't change what it's selling nor does it change the price (in bh points) of the items. Calculate which item would be worth most and base the price off that. That way you at least have a baseline price, and even though it's not accurate with what you would get in the trust trading market it would still be an improvement.

**Comment by Nightfirecat** [comment]
I'm not too picky personally about the values assigned (though the prices I quoted have been steady and consistent for some time now); the higher-tier emblems having a higher value than tier 1 emblems would be appreciated though, for better bank value/loot tracker display. It's always weird to see them listed below tier 1 emblems in a loot tracker entry.

**Comment by Nightfirecat** [comment]
For what it's worth, if we come to decide we want this feature and agree upon the values that should be assigned to emblems, I have a local branch which implements this feature.

**Comment by deathbeam** [comment]
Any kind of hardcoded value for each tier of emblems is no. If you want to implement any value for those items, it should be based on rewards from bounty hunter store, there is no alternative (well, other than just not implementing it at all).

**Comment by Nightfirecat** [comment]
Given the BHv2 update and the fact that new emblems have defined gp values, this issue is no longer valid.
