### ISSUE TITLE
!bankvalue Command 

### ISSUE THREAD

**Issue by OgeGhost** [runelite/runelite#8398]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The !bankvalue command would show your current bank value in chat
EX: [Username]'s: Bank Value is [Value].

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by deathbeam** [comment]
There is no point in having this feature as it provides no value and is not even super accurate, and also someone can easily fake it and scam people into trusting them with this
