### ISSUE TITLE
Command for boss pet killcount

### ISSUE THREAD

**Issue by OgeGhost** [runelite/runelite#8399]
This command would be something like
"!bandospet" 
and will show the killcount you received the bandos pet on.

Essentially taking advantage of the collection log

**Comment by genetic-soybean** [comment]
Does the collection log actually show the kc you recieved specific loot or pets?
Might be able to track stuff you get after such Feature was implemented, but everything before that would be missing.

**Comment by OgeGhost** [comment]
> Does the collection log actually show the kc you recieved specific loot or pets?
> Might be able to track stuff you get after such Feature was implemented, but everything before that would be missing.

Sadly no, I do not believe so.

**Comment by raiyni** [comment]
duplicate #8397
