### ISSUE TITLE
Notification Sound isn't mute despite having it mute in settings

### ISSUE THREAD

**Issue by FappyMcFap** [runelite/runelite#840]
I'm not sure weather or not this has to do with the Client or Windows 10.
When going to the notification settings of RuneLite I have the "Play a sound when a notification arrives" turned off but a sound still plays when receiving notifications from the Client.

**Comment by deathbeam** [comment]
Check the "RuneLite" settings, there is separate option for the "beep".

**Comment by FappyMcFap** [comment]
Thanks for the quick reply :) Had no idea that was a thing.

**Comment by deathbeam** [comment]
Np :) Few of the settings from Idle Notifier will be moved there to be reused also by other plugins in next release, so it will make more sense.

**Comment by JohnAppleased** [comment]
> Check the "RuneLite" settings, there is separate option for the "beep".

Sorry to necro this issue but I was still having trouble with this problem.
Where exactly is this separate option?

**Comment by Alexsuperfly** [comment]
there is a "runelite" entry in the plugins list, which has settings and within those settings a notification section

**Comment by JohnAppleased** [comment]
Oh perfect!! This worked thanks so much : D
