### ISSUE TITLE
The drive or UNC share you selected is not selected or does not exist or is not accessible. please select another. 

### ISSUE THREAD

**Issue by AFuller1** [runelite/runelite#8400]
Tried to re download runelite after a break from OSRS and now I am getting this bug when i try and run the exe file for both the 32bit and 64 bit options. 

![Capture](https://user-images.githubusercontent.com/26751127/55519373-87a54c00-5645-11e9-8255-c0c7481770e1.PNG)

**To Reproduce**
1. Go to 'downloads'
2. Click on '.exe file'

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: N/A
 - Launcher version: N.A

**Comment by devLotto** [comment]
This should probably be on the launcher issue tracker: https://github.com/runelite/launcher/issues.
