### ISSUE TITLE
More bank withdraw options

### ISSUE THREAD

**Issue by M0dii** [runelite/runelite#8406]
Add configurable withdraw options for all (or specific, configurable, just like bank tags) items or in other words possibility to change default withdraw options.

(and or remove unnecessary examine option)

![image](https://user-images.githubusercontent.com/11699611/55553680-875e8c80-56e9-11e9-9a0a-364625834a42.png)

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features we dont want to change anything related to withdraw in bank option s
