### ISSUE TITLE
Loot Tracker: Track runes crafted at the ZMI/Ourania Altar

### ISSUE THREAD

**Issue by LUMIAH** [runelite/runelite#8407]
An overview in the loot tracker plugin to see how many of a certain rune you've crafted.

**Comment by Nightfirecat** [comment]
I don't think we want to add skilling resources to the loot tracker.

**Comment by Twiglet1022** [comment]
Maybe one for the runecrafting plugin. MLM plugin tracks ores, fishing plugin counts fish, same for WC, so it seems like the natural place to put it.

**Comment by deathbeam** [comment]
We already have issue open for this

**Comment by Hydrox6** [comment]
#4126
