### ISSUE TITLE
Ground Marker Counter

### ISSUE THREAD

**Issue by TighHyto** [runelite/runelite#8410]
Would it be possible to have a "counter" that counts the amount of ground markers you have placed of a specific color? would save me a lot of math

**Comment by Nightfirecat** [comment]
Why? What would this be useful for?

**Comment by TighHyto** [comment]
personally im trying out a limited ironman where i roll on tiles that im allowed to stand on for a specific period of time etc etc and im using a random number generator to decide in which tiles are allowed so if i were to mark the edges with said counter id be able to continue this process without constantly counting the edges, very very specific circumstances i know. thought id try tho

**Comment by deathbeam** [comment]
This is extremely niche use case and so we will not be implementing it. You can edit the client by yourself to add this feature or parse your local configuration file and display it somewhere
