### ISSUE TITLE
Antifire timers are inaccurate

### ISSUE THREAD

**Issue by Lucwousin** [runelite/runelite#8422]
Antifire seems to function the same as antipoison, which makes timers which start with a set time inaccurate. (#7967 fixes this for antipoison timers btw ;))

Just like antipoison, antifire protection seems to run on a cycle of 30 ticks (18 seconds). The cycle gets deferred if a player has an interface opened or is teleporting (There's probably more times things like this happen, but these are the only 2 I know for sure). You can test this by drinking both antifire and superantipoison (both are 6 minutes) and opening an interface (to defer both cycles); the antipoison and antifire cycle will sync up and show the warning they're about to wear off and the message they've ended at the same time.

While poison status is something the server sends to the client, antifire isn't, so we would have to check whether or not a tick actually can happen, rather than have the server tell us if it did.

**Comment by Nightfirecat** [comment]
If antifire information is not sent to the client, I don't believe we can make it any more accurate than it is already.

**Comment by Nightfirecat** [comment]
This was fixed/added in 2b5fe681b060a64f31ba0b17478463360ca9bde2
