### ISSUE TITLE
would it be possible to make click boxes bigger and have an unlocked camera, love your work guys keep it up :)

### ISSUE THREAD

**Issue by jamie243243** [runelite/runelite#8427]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by deathbeam** [comment]
We cant make clickboxes bigger, and I believe there already is issue for detached camera, that was either closed or is still open
