### ISSUE TITLE
Enhancement - Display if item is clue item with wiki query

### ISSUE THREAD

**Issue by persecom** [runelite/runelite#8428]
**Is your feature request related to a problem? Please describe.**
Would like a more convenient method of determining if an item is a clue item without having to constantly refer to the wiki.

**Describe the solution you'd like**
Querying (?) the clue items table on the wiki to determine if [item] is a clue reward. The option would be similar in design as the GE search. This method would also display every tier the item exists in, including the quantity. I.e., a rune full helm is used several times I believe. 

**Describe alternatives you've considered**
An interactable list in RuneLite containing every item of every tier of clue scroll, along with a checkbox you can click to determine if you already have it. Sounds tedious as hell to put in. Especially if that included icons.

**Additional context**
This is only an issue for those that do not have completely filled hidey holes. If I remember correctly, there's plans for a future update to OSRS that will display if a hidey hole is full or not. This could make the update somewhat unneeded, maybe.

I have noticed that #3470 has a somewhat similar idea, but I also noticed it was closed by the poster.

**Comment by Abextm** [comment]
Duplicate #3105
