### ISSUE TITLE
Idle notifier doesn't work with cat

### ISSUE THREAD

**Issue by jamalt5** [runelite/runelite#8429]
**Describe the bug**
With idle notifier, I don't get notifications when stopped fishing when I'm interrupted by my cat(being needy.) I get notifications normally though

**To Reproduce**
No clue, maybe just try fishing with a cat?

**Expected behavior**

**Environment (please complete the following information):**
 - OS:Windows
 - RuneLite version: latest

**Comment by zwilkin** [comment]
Not just for cat interruptions; it happens when gaining a level too.

**Comment by deathbeam** [comment]
Duplicate of #9714
