### ISSUE TITLE
Highlight background of current choose option

### ISSUE THREAD

**Issue by Jbleezy** [runelite/runelite#8430]
Kamiel had made this a while back, but unfortunately he lost the code for it.

![Choose Option Highlight Background](https://user-images.githubusercontent.com/20487224/55664246-32ea0880-57e0-11e9-930a-8715d2c66bdc.gif)

This GIF also showcases the menu option switched for the newer RS look, but what I would mainly like to see is the background highlighted.

**Comment by Kamielvf** [comment]
Just a note that this cannot be done without internal access.

**Comment by Jbleezy** [comment]
High Detail choose option menu was added in 1.5.21, which works for me.
