### ISSUE TITLE
Wiki Lookup

### ISSUE THREAD

**Issue by M0dii** [runelite/runelite#8431]
Lookup Wiki option (imo) should be implemented into bank and equipment menu.

![image](https://user-images.githubusercontent.com/11699611/55668732-72fbca80-5876-11e9-85fc-08d7670a2299.png)

![image](https://user-images.githubusercontent.com/11699611/55668731-7000da00-5876-11e9-9162-0d9fab74274e.png)

**Edit**
Also, would be great for Quests.

**Comment by raiyni** [comment]
duplicate #7854
