### ISSUE TITLE
Ground markers but everywhere to show the floor grid.

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#8438]
Some places, especially newer content have the floor grid very well blended together so its hard to know where an actual tile is. Useful for pvm where you have to be precise, counting tiles correctly etc..

Basically a ground marker on every tile to show the grid. (pref thinner lines and custom color)

**Comment by Twiglet1022** [comment]
You can probably achieve the desired effect with the existing tile indicator plugin by turning on the option of highlighting the tile currently under your mouse.

**Comment by buldosis** [comment]
> You can probably achieve the desired effect with the existing tile indicator plugin by turning on the option of highlighting the tile currently under your mouse.

true, but there scenarios where you have several npcs and not enough time to check with mouse hovering bacause your mouse has to be else where (like prayer switching or flicking)

this just seemed like a really useful and low effort plugin to make and have, maybe just a toggle in the ground marker plugin.

**Comment by deathbeam** [comment]
This would have so horrible performance its not worth implementing. Just using tile indicators with currently hovered tile should be good enough
