### ISSUE TITLE
Agility Plugin: Yanille north wall shortcut highlighting improperly

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#8441]
**Describe the bug**
Two ends of the same agility shortcut are highlighted with different colors. (I am able to travel through it in both directions no problem)

**Screenshots**
![screenshot](https://i.imgur.com/6LBnYPs.png)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.19-SNAPSHOT

**Comment by ksergio39** [comment]
@ShaunDreclin where is agility shortcut?
