### ISSUE TITLE
Plugin to record inventory prior to death

### ISSUE THREAD

**Issue by zezman45** [runelite/runelite#8447]
I'm annoyed that when i die while doing an activity (Zulrah, Vorkath, questing) where I can retrieve items after death there is no way of knowing for sure what items to bring for another attempt.
So i end up bringing extra monkfish, extra potions etc. which I have to drop - wasting gold.

I'd like:
A plugin that records the inventory that I had before I died, so that I know what Items (runes, food, potions) to bring for my next attempt.

Curently, i try and 'print-screen' before I die, but sometimes this isn't possible.

Ideally, there'd be a list in the sidebar of items that I had on me before I died. (say for example, it shows what my inventory was 10 seconds ago, which I can then freeze)

**Comment by Lucwousin** [comment]
Screenshot plugin has an option to automatically screenshot deaths. Enable inventory viewer if you find yourself dieing with tabs other than inventory open.

**Comment by zezman45** [comment]
Amazing, thankyou very much!

**Comment by Kamielvf** [comment]
Closing as a good workaround has been suggested for something niche like this.
