### ISSUE TITLE
Add "Requires MM2 or greegree and monkeyspeak amulet" to Awowogei clue

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#8449]
![image](https://user-images.githubusercontent.com/9074448/55754514-1b638780-5a4d-11e9-9a77-ed71923979d1.png)

**Comment by Nightfirecat** [comment]
It doesn't require either of those things if you've completed MM2.

**Comment by Gamer1120** [comment]
Oh, I didn't know that. Maybe it's time for me to do the quest then. 

The clue checker could check for MM2 completion or simply write "Requires completion of MM2 or a greegree and monkeyspeak amulet"

**Comment by Adam-** [comment]
you can do this with clue notes now in d87f3f6319f61d6bc43a28384d1175be78f689db
