### ISSUE TITLE
reset settings

### ISSUE THREAD

**Issue by M4rest** [runelite/runelite#8450]
is there possibly a way we could reset all the runelite settings to default, there have been many times where i have changed a setting have come away from my computer for a while and when i have got back i cannot remember what setting i fiddled with so i have to spend 20 minutes going through all the settings i have to find what i have done, maybe a "reset all settings" button then make it have "are you sure" option if its possible.

**Comment by deathbeam** [comment]
You can also just delete ~/.runelite/settings.properties for now. I dont think such extreme scenario like this needs separate button when there is already a way to do that (by deleting config) and there is per-plugin reset button

**Comment by brianj64** [comment]
How do I reset the settings when I'm using a RuneLite account? Everytime I delete my settings it's back to how it was before the reset if I login my account.

**Comment by BenDol** [comment]
I also need this

**Comment by Nightfirecat** [comment]
This is now possible by creating and switching to a new config profile: https://github.com/runelite/runelite/wiki/General-Features#profiles
