### ISSUE TITLE
[Suggestion] Marked Tiles Option: Ability to add text or numbers

### ISSUE THREAD

**Issue by azzawoody** [runelite/runelite#8451]
Is it possible to have the ability to add text/numbers to the tile markers so we could leave notes on tiles for future times

**Comment by Dovry** [comment]
Just out of curiosity... what is the usecase for this?

**Comment by azzawoody** [comment]
i use markers for a lot of things and some times i forget y i put them there or what order to use them in

**Comment by gccltl** [comment]
I think this would be too much for Jagex to handle...
This would make many PvM tasks much easier.

No.

**Comment by Kamielvf** [comment]
I think this would just clutter the screen way too much + distract from other (more important) overlays (ground items, player indicators etc)

**Comment by ShaunDreclin** [comment]
FWIW I think being able to label marked tiles with numbers or short words/acronyms would be helpful without adding too much clutter. It only needs to be as visually noisy as the user decides to make it

**Comment by Nightfirecat** [comment]
I mentioned this on Discord, but I feel this can largely be covered by using different-colored markers already. (mark things in a certain color order, or with different opacities) Furthermore, I can't imagine any UX for this which is both (a) good, and (b) not complicated.

**Comment by ShaunDreclin** [comment]
Was thinking maybe hold down another modifier key to make it pop up a text input when you mark the tile. Probably not the best but it'd work

**Comment by raiyni** [comment]
This was added as an external plugin `Ground Markers with Labels`
