### ISSUE TITLE
Notes do not sync between two devices, glitched, now my notes are always blank.

### ISSUE THREAD

**Issue by mparsakia** [runelite/runelite#8452]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I play on desktop and a laptop, and I am signed into runelite. At one point, my laptop had no notes in the sidebar, and my desktop had notes. Now, my notes are always empty. Even when I copy/paste my notes into both my laptop and desktop runelite while signed in, then close the app, on next launch my notes are always empty. I don't know what the problem is but I have tried syncing from both devices and it does not work.

**To Reproduce**
See above.

**Expected behavior**
Notes are supposed to sync from the last changed location.

**Screenshots**
None.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - RuneLite version: 1.5.18
 - Launcher version: 1.6.0

**Additional context**
Will post logs upon request as I do not know which to post.

**Comment by mparsakia** [comment]
Additionally, I have clicked "Import local settings to remote RuneLite account" while my newly typed notes are in the sidebar, in the hopes that it would sync & override whatever is happening; however this did not work, as again when I closed RuneLite and relaunched it, the notes I had just typed in were erased again.

**Comment by forsco** [comment]
Not sure how valid this issue is because notes don’t sync until you change focus after typing in a note.

**Comment by mparsakia** [comment]
I am changing focus, clicking elsewhere, changing settings, etc. Trying whatever I can do make sure that it syncs properly. Even in my config files it has the "content" of my notes there, until the app closes at which it wipes the config file for the notes line.

**Comment by forsco** [comment]
Can you launch with the debug console and see if it’s throwing an error when attempting to sync?

Are you also logged into your runelite profile on both systems?

**Comment by mparsakia** [comment]
I was logged in on both. I haven't logged into my laptop in a while, but I can go see if I'm logged in there. I was signed into my runelite profile on both my devices.

Can you instruct me on how to launch in debug?

**Comment by forsco** [comment]
You’ll need to add a launch parameter ‘—debug’

Someone may be able to elaborate further. I’m currently at work.

**Comment by Abextm** [comment]
Post your logs, see https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client

**Comment by mparsakia** [comment]
I made a new RL account, signed in, put my notes in, and now they stay there. Had to redo all of my custom settings however. Here's my logs.


[application.log](https://github.com/runelite/runelite/files/3063268/application.log)
[client.log](https://github.com/runelite/runelite/files/3063269/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3063270/launcher.log)
