### ISSUE TITLE
!pb doesn't pick up some boss timers

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#8454]
This is known to affect:

- [ ] Theatre of Blood completion time
- [x] Chambers of Xeric completion time
- [x] Fight Caves (TzTok-Jad)
- [x] Inferno (TzKal-Zuk)
- [x] Grotesque Guardians

**Comment by Adam-** [comment]
This is not specific to tob, but probably to any activity that has the pb time in a separate message from the kc.

**Comment by Alexsuperfly** [comment]
Inferno and Fight Caves also fall under this


![](https://cdn.discordapp.com/attachments/361679294679744524/566191511491051520/bb89ef0e99bc6e7d5e362c539b1b7fb4.png)

![](https://i.imgur.com/tHfpsZ9.png)

**Comment by Alexsuperfly** [comment]
Grotesque Guardians seems to have the same problem but its even more annoying to account for since the duration is sent before the boss kill.

image provided by someone else in the discord
![](https://image.prntscr.com/image/HBr_6AeLTOexBb6jbZskiw.png)

**Comment by Nightfirecat** [comment]
Renamed issue and updated original post to reflect that this isn't a ToB-specific issue.

**Comment by Alexsuperfly** [comment]
if we're going to do ToB might as well put CoX in there 

![](https://cdn.discordapp.com/attachments/361679294679744524/566733979282309130/d165036a80ab6fb3a3b7f82668342af3.png)

**Comment by Adam-** [comment]
Here is the other zuk message: https://cdn.discordapp.com/attachments/301497432909414422/585270372761337856/unknown.png

**Comment by Alexsuperfly** [comment]
![image](https://user-images.githubusercontent.com/7191512/62170822-c77df680-b2fa-11e9-87bb-311cbc164567.png)

**Comment by Adam-** [comment]
Zuk/Jad fix is in 1ce2e5aa930d122d1c543c497f9990b2cde8b235 and gg in 1b2219374ff5dbc5c3380ff596779a06a34e7040
