### ISSUE TITLE
Overlay for STASH units

### ISSUE THREAD

**Issue by Treedot** [runelite/runelite#8455]
Imagine like an overlay on each STASH unit that shows if it's built or not and what is/can be in it.

So if you've got it built it's outlined in green and if not it's outlined in red and on top of it would be a text list of what items go into it and the text would be red or green depending on if you've got them stored or not.

Seems useful to me?

**Comment by deathbeam** [comment]
Duplicate of #1662

**Comment by deathbeam** [comment]
Github search seems more useful to me
