### ISSUE TITLE
Barrows plugin doesn't scale with stretched fixed

### ISSUE THREAD

**Issue by EcahRS** [runelite/runelite#846]
Examples attached

fullscreen stretched fixed
![image](https://user-images.githubusercontent.com/37051168/37013986-5bdc5998-20b2-11e8-971d-4e0734dc8c88.png)

normal fixed
![image](https://user-images.githubusercontent.com/37051168/37014005-728ac1de-20b2-11e8-8f6e-abdf54b9b564.png)

**Comment by sethtroll** [comment]
This issue is not specific to just barrows, it is everything that uses the minimap location.

Maybe @devLotto can look into it.

**Comment by devLotto** [comment]
This is because the worldToMiniMap method takes into account ``client.getCanvas().getWidth()`` even when in fixed mode. I'll make a fix.
