### ISSUE TITLE
Simple API to fetch live data. Specifically - farming timers

### ISSUE THREAD

**Issue by gccltl** [runelite/runelite#8460]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Implement public API to fetch data - screenshots, timers, loot trackers, etc.

**Describe alternatives you've considered**
There is an ability to download data in CSV formats. That's not enough.

**Additional context**
None.

**Comment by gccltl** [comment]
Maybe this should be moved to website repository?
If a moderator is not fine with it.

**Comment by deathbeam** [comment]
We have public API for all of this, check how runelite.net is fetching that data

**Comment by deathbeam** [comment]
Except screenshots, because we are not storing screenshots anywhere
