### ISSUE TITLE
Small timer icons in UI

### ISSUE THREAD

**Issue by pkerfrost** [runelite/runelite#8465]
So the icons for the home tele timer, slayer task box, potion timers is really small see picture. 

Do you know how how to fix it? 

<img width="1280" alt="Screenshot 2019-04-11 at 10 23 21" src="https://user-images.githubusercontent.com/49517108/55947329-233a4c00-5c46-11e9-875a-480d816f4245.png">

 - OS: Mac
 - RuneLite version: 1.5.18
 - Launcher version: 1.6.2

Sorry if this is a copy and if you want more info just ask :) thanks guys! amazing client!!

**Comment by pkerfrost** [comment]
by the way tired to like move and reset with the alt button :)

**Comment by Nightfirecat** [comment]
What do you have the infobox size set to in your Runelite settings?

**Comment by deathbeam** [comment]
As @Nightfirecat just change your infobox size configuration

**Comment by pkerfrost** [comment]
thanks for getting back to me guys! much appreciated - but sounds dumb af where is that in the settings? 
<img width="652" alt="Screenshot 2019-04-11 at 16 38 25" src="https://user-images.githubusercontent.com/49517108/55970868-4b42a300-5c78-11e9-931d-7420b259ece6.png">

**Comment by raiyni** [comment]
It's in runelite

**Comment by pkerfrost** [comment]
thanks mate!! being a right noob here! gl in game :)
