### ISSUE TITLE
add ability to hide musics that aren't unlocked yet.

### ISSUE THREAD

**Issue by badgehunter** [runelite/runelite#8473]
**Is your feature request related to a problem? Please describe.**
Yes because you can't currently see easier what songs you have unlocked yet and which you have and rather you need to scroll through 600 songs to see which you haven't unlocked yet.

**Describe the solution you'd like**
Similar button to quest page but it would hide the unlocked songs and leave only the ones that you haven't unlocked.

**Describe alternatives you've considered**
hides the ones that you haven't unlocked yet and leaves the ones that you have.

**Additional context**
Search to search the songs that you want to play.

**Comment by Atrolantra** [comment]
Looking into this. 👍🏻

**Comment by Nightfirecat** [comment]
I feel like this is a pretty niche feature. Music tracks, unlike quests, are not as often the target of completion since the music cape is much less useful and desirable than the quest cape.

**Comment by Adam-** [comment]
This was added in #8779
