### ISSUE TITLE
Easy Clue: Talk to Turael in Burthrope, Incorrect Highlighting

### ISSUE THREAD

**Issue by kanno100** [runelite/runelite#8476]
**Describe the bug**
While using an easy clue with the step: Talk to Turael in Burthrope. There is no indicator to move towards or talk to Turael. 

**To Reproduce**
1. Get an easy clue with the step: Talk to Turael in Burthrope,
2. Head to Burthrope

**Expected behavior**
I expected the clue plugin to show an arrow above Turael's model, and an arrow to show which direction he is from the player.

**Screenshots**
Before I did the step(forgot to screenshot clue step itself)
![before clue step](https://user-images.githubusercontent.com/49525798/55964202-ebc5a280-5c39-11e9-97f0-4c25f29321ab.png)
After I completed the step(to show casket from the clue step)
![after clue step](https://user-images.githubusercontent.com/49525798/55964205-ed8f6600-5c39-11e9-95dc-b5d8ab43b934.png)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.19.1
 - Launcher version: 1.5.2

**Comment by xDemoN** [comment]
Closed by 31a044887d5174e92abad5dde0d840e22d9a84df
