### ISSUE TITLE
GPU Plugin severe artifacting under Linux (Mesa)

### ISSUE THREAD

**Issue by tj28** [runelite/runelite#8486]
![Screenshot from 2019-04-11 16-16-53](https://user-images.githubusercontent.com/6042288/55990251-403a4380-5c75-11e9-8a74-13cf70c12aaf.png)

AMD Radeon R9 290 4GB
Ubuntu 19.04, Mesa 19.0.1, Linux Kernel 5.0

Works fine under windows so not a hardware issue.
`
xtended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD HAWAII (DRM 2.50.0, 5.0.0-10-generic, LLVM 8.0.0) (0x67b1)
    Version: 19.0.1
    Accelerated: yes
    Video memory: 4096MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 2119 MB, largest block: 2119 MB
    VBO free aux. memory - total: 275 MB, largest block: 275 MB
    Texture free memory - total: 2119 MB, largest block: 2119 MB
    Texture free aux. memory - total: 275 MB, largest block: 275 MB
    Renderbuffer free memory - total: 2119 MB, largest block: 2119 MB
    Renderbuffer free aux. memory - total: 275 MB, largest block: 275 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 6139 MB
    Currently available dedicated video memory: 2119 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD HAWAII (DRM 2.50.0, 5.0.0-10-generic, LLVM 8.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
`

Console spits out this constantly:
`
GLDebugMessageHandler: GLDebugEvent[ id 0x3
	type Warning: implementation dependent performance
	severity Medium: Severe performance/deprecation/other warnings
	source GL API
	msg using glBufferSubData(buffer 2, offset 0, size 32) to update a GL_STATIC_DRAW buffer
	when 1555014058784
	source 4.5 (Core profile, arb, debug, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 4.5 (Core Profile) Mesa 19.0.1 - hash 0x7f151bbc]
`

Client is up to date (today's master branch as of `0b078d15`)

**Comment by fryt0l** [comment]
hello experienced same issue after last update on my manjaro box try downgrading mesa to version 18.3.4-1 vorked for me.
no ture if the last version is bugged on runelite or mesa side

**Comment by tj28** [comment]
> hello experienced same issue after last update on my manjaro box try downgrading mesa to version 18.3.4-1 worked for me.
> not sure if the last version is bugged on runelite or mesa side

@fryt0l Thank you... Ubuntu 19.04 comes with Mesa 19 ootb so it would be quite a pain to downgrade. Glad to know there's a workaround though. Sounds like amdgpu-pro may be a valid workaround also.

I tried PR #7664 and that successfully suppressed the constant console error above but didn't do anything else.

Below is what I get when I start and stop the GPU plugin
[https://pastebin.com/Wsw4fc00](url)

Highlights
`
Thread-2: X11GLXDrawable.setRealized(true): X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7fecc8b13cf0, owner true, JAWTToolkitLock[obj 0x445510bc, isOwner true, <6540e6cc, 58e487e8>[count 1, qsz 0, owner <Thread-2>]]], idx 0], visualID 0x318, fbConfigID 0xa9,
	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]],
	chosen    GLCaps[glx vid 0x318, fbc 0xa9: rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4/GL4.hw], on-scr[.]]]
`

**Comment by fryt0l** [comment]
well you can try but last time i installed amdgpu-pro i got very bad performance like half of fps i can get using opensource drivers

**Comment by DavidVentura** [comment]
Seeing exactly the same, also on ubuntu 19.04

**Comment by Hydrox6** [comment]
I've done some testing, and it turns out that it's LLVM 8 causing issues. Any version of mesa will work as long as it's built with LLVM 7 or lower (19 requires 7+, 18 requires 5+). It's also possible to build a separate version of Mesa and have only RL use it, though it's a bit involved.
I'm currently trying to get mesa to properly build with a custom LLVM so that I can figure out exactly what caused it to break; I'll let you guys know what I find

**Comment by sleibrock** [comment]
Ran into this issue today when upgrading my Manjaro system. Tried rolling back `mesa` to 18.3.4-1 from my pacman cache but didn't fix anything for me (GPU plugin refuses to turn on). Will keep trying to play with it.

**Comment by tj28** [comment]
> Ran into this issue today when upgrading my Manjaro system. Tried rolling back `mesa` to 18.3.4-1 from my pacman cache but didn't fix anything for me (GPU plugin refuses to turn on). Will keep trying to play with it.

You need to also roll back llvm to 7.x and use Java 8

**Comment by twiclo** [comment]
I also wanted to report I'm having the same issues with mesa 19 on fedora 30

**Comment by JarnoB** [comment]
I'm having the exact same issue. Running Linux Mint 19.1, mesa 19

**Comment by LivingAutoMode** [comment]
Same issue here, Linux Mint 19.1 Tessa and Mesa 19. Using a RX 560, I was told that maybe the game was utilising integrated graphics, but I have none, only a discreet GPU.

**Comment by ruscur** [comment]
I have mesa downgraded to 18.2.5 to skip this, we're up to 19.1.1 now.  Is this a bug in RuneLite or mesa?  If the latter, are those guys aware?

**Comment by fryt0l** [comment]
as hydrox said its in LLVM.
the second one i dont know dont realy have enought understanding of problem so i cant provide enought info to report it

**Comment by Hydrox6** [comment]
I've been meaning to bisect LLVM and figure out the cause for a while, but I was having trouble with getting Mesa working with a custom LLVM build. Figured that out recently, but I'm getting really weird runtime errors and I'm not sure if there's actually an issue, or if I'm doing something wrong again.

**Comment by Hydrox6** [comment]
If anyone here could test this potential fix, that would be great. You'll need to take this patch and `git apply` it to the source code of the project, then build the client. If you could report back with the mesa version you're using (which can be found by using `glxinfo | grep "OpenGL versioN") and whether it worked or not, that would be amazing.
[mesa-fix.patch](https://github.com/runelite/runelite/files/3366208/mesa-fix.patch.txt)

**Comment by Noiseko** [comment]
@Hydrox6 Unfortunately "DYNAMIC_DRAW" made no difference for my setup 
MESA = 4.5 (Compatibility Profile) Mesa 19.0.6 (19.0.6-1 arch)
LLVM = 8.0.0 (8.0.0-2 arch)

**Comment by fryt0l** [comment]
sorry i would like to but  i failed to compile the client :(
keep getting this
Tests in error: 
  ImageUtilTest.resizeImage:165 » AWT Assistive Technology not found: org.GNOME....


Tests run: 210, Failures: 0, Errors: 1, Skipped: 4

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] RuneLite ........................................... SUCCESS [  3.369 s]
[INFO] Web API ............................................ SUCCESS [  3.785 s]
[INFO] Cache .............................................. SUCCESS [ 34.157 s]
[INFO] RuneLite API ....................................... SUCCESS [  0.410 s]
[INFO] Protocol API ....................................... SUCCESS [  0.042 s]
[INFO] Protocol ........................................... SUCCESS [  0.478 s]
[INFO] Cache Client ....................................... SUCCESS [  0.327 s]
[INFO] Cache Updater ...................................... SUCCESS [  0.680 s]
[INFO] Script Assembler Plugin ............................ SUCCESS [  1.298 s]
[INFO] RuneLite Client .................................... FAILURE [ 12.626 s]
[INFO] Web Service ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 58.342 s
[INFO] Finished at: 2019-07-10T23:03:34+02:00
[INFO] Final Memory: 44M/555M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (default-test) on project client: There are test failures.
[ERROR] 
but tbh i dont know what im doing so its probably my fault

**Comment by BartWillems** [comment]
I'm using Mesa 19.1.3-1 on Arch Linux with an AMD Radeon RX580 and it seems to be solved for me.

**Comment by Noiseko** [comment]
same as above ^ :)

**Comment by ruscur** [comment]
Confirming the same, finally upgraded from mesa 18.2.5 to 19.1.3 on an Intel integrated GPU and all working

**Comment by MESLewis** [comment]
Multiple reports of this being solved. Reopen this issue if the problem persists in the latest release of RuneLite.

**Comment by wilkub** [comment]
I'm having having GPU plugin issues now, just looks different, I'm on manjaro kde, everything should be up to date.


![Screenshot_20220302_182622](https://user-images.githubusercontent.com/68994137/156415450-7d917f65-ebb4-41c8-b335-0488b7aa9c4a.png)

**Comment by wilkub** [comment]
> I'm having having GPU plugin issues now, just looks different, I'm on manjaro kde, everything should be up to date.
> 
> ![Screenshot_20220302_182622](https://user-images.githubusercontent.com/68994137/156415450-7d917f65-ebb4-41c8-b335-0488b7aa9c4a.png)

Somehow, either playing around with the render distance or turning on and off a zoom altering plugin fixed everything for me.
