### ISSUE TITLE
Expanded Private Chat History

### ISSUE THREAD

**Issue by michaelcubed** [runelite/runelite#8499]
**Describe the solution you'd like**
Currently you can only see the last 5 messages, please allow custom resizing.

**Describe alternatives you've considered**
User specified chat history size box near chat history option

**Additional context**
Being able to see more chat history will allow for additional context in conversations

**Comment by SuperRonJon** [comment]
You can just clic on the "Private" stone below the chatbox and it will show all private message history. The only thing limited tothe last 5 private messages is the separated window in blue text above the chatbox, which is limited so it doesn't fill up your entire screen with messages.

**Comment by dekvall** [comment]
As previous commenter said: Use the chatbox to display more messages.
