### ISSUE TITLE
Time Tracking: Add infoboxes to show when birdhouses/herbs/etc are ready

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#8500]
I find myself not noticing the notification sometimes, an infobox would be much harder to miss!

**Comment by Cabbage303** [comment]
+1, would like it if we could "add to canvas" like you can with xp trackers

**Comment by LlemonDuck** [comment]
This can be accomplished with the hub plugin [Time Tracking Reminder](https://runelite.net/plugin-hub/show/time-tracking-reminder)
