### ISSUE TITLE
Clue Update 2019

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#8504]
Here are all the clues that the current system supports that we need to support

- [x] Anagrams:
    - [x] Beginner:
        - [x] The anagram reveals who to speak to next: AN EARL
        - [x] The anagram reveals who to speak to next: CARPET AHOY
        - [x] The anagram reveals who to speak to next: DISORDER
        - [x] The anagram reveals who to speak to next: I CORD
        - [x] The anagram reveals who to speak to next: IN BAR
        - [x] The anagram reveals who to speak to next: RAIN COVE
        - [x] The anagram reveals who to speak to next: RUG DETER
        - [x] The anagram reveals who to speak to next: SIR SHARE RED
        - [x] The anagram reveals who to speak to next: TAUNT ROOF
    - [x] Medium:
        - [x] This anagram reveals who to speak to next: CALAMARI MADE MUD
        - [x] This anagram reveals who to speak to next: CLASH ION
    - [x] Master:
        - [x] This anagram reveals who to speak to next: A ELF KNOWS
        - [x] This anagram reveals who to speak to next: RIP MAUL

- [x] Cipher
    - [x] Hard:
        - [x] The cipher reveals who to speak to next: BSOPME MZETQPS
        - [x] The cipher reveals who to speak to next: IWPPLQTP

- [x] Coordinates:
	- [x] Medium:
		- [x] 02.16N 12.07E
		- [x] 17.39N 37.16W
		- [x] 23.01N 41.33E
	- [x] Hard:
		- [x] 16.45N 03.05W
		- [x] 19.09N 21.58E
		- [x] 24.22N 17.15E
	- [x] Elite:
		- [x] 17.58N 19.05E
		- [x] 20.24N 03.52W
	- [x] Master:
		- [x] 18.26N 37.15W

- [x] Cryptic:
    - [x] Beginner:
        - [x] Always walking around the castle grounds and somehow knows everyone's age.
        - [x] In a village of barbarians, I am the one who guards the village from up high.
        - [x] In the place Duke Horacio calls home, talk to a man with a hat dropped by goblins.
        - [x] Near the open desert I reside, to get past me you must abide. Go forward if you dare, for when you pass me, you'll be sweating by your hair.
    - [x] Easy:
        - [x] Search the chest in Fred the Farmer's bedroom.
        - [x] Search the eastern bookcase in Father Urhney's house.
        - [x] Search the boxes next to a chest that needs a crystal key.
        - [x] Search the crates in Falador General store.
        - [x] Search the crate in Rommiks crafting shop in Rimmington.
        - [x] Search the single crate in Horvik's smithy in Varrock.
        - [x] Talk to Ali the Leaflet Dropper north of the Al Kharid mine.
        - [x] Talk to Charles at Port Piscarilius.
        - [x] Talk to the cook in the Blue Moon Inn in Varrock.
        - [x] Talk to Morgan in his house at Draynor Village.
        - [x] Talk to Turael in Burthorpe.
        - [x] Talk to Wayne at Wayne's Chains in Falador.
    - [x] Elite:
        - [x] More resources than I can handle, but in a very dangerous area. Can't wait to strike gold!
        - [x] Observing someone in a swamp, under the telescope lies treasure.

- [x] Emotes:
    - [x] Beginner:
        - [x] Blow a raspberry at Gypsy Aris in her tent. Equip a gold ring and a gold necklace.
        - [x] Bow to Brugsen Bursen at the Grand Exchange.
        - [x] Spin at Flynn's Mace Shop.
        - [x] Panic at Al Kharid mine.
        - [x] Cheer at Iffie Nitter. Equip a chef hat and a red cape.
        - [x] Clap at Bob's Brilliant Axes. Equip a bronze axe and leather boots.

- [x] Hot/Cold:
	- [x] Inside the Ruins north of the Graveyard of Shadows, level 27 Wilderness.
	- [x] North of Venenatis, level 32 Wilderness

In addition, the following new types of clues were added, and could do with support:

- [x] Beginner Hot/Cold
        Base Clue: Buried beneath the ground, who knows where it's found. Lucky for you, a man called Reldo may have a clue.
	Has 5 locations it can be in
- [x] Music Clues
- [x] Beginner Map Clues
	These work like no other maps clues in the game, using 1 ItemID for all 5 map types. As a result they can't be added easily to the current maps
- [x] Charlie Tasks
	Similar to Sherlock Challenges
	Consists of 3 parts:
		A Clue telling the player to go to Charlie
		A Challenge telling the player what to do
		A Challenge telling the player to return to Charlie with the item

	Current known challenges:
```
		I need to cook Charlie a pike.
		I need to take the cooked pike to Charlie.

		I need to fish Charlie a herring.
		I need to take a raw herring to Charlie.

		I need to fish Charlie a trout.
		I need to take a raw trout to Charlie.

		I need to cook Charlie a trout.
		I need to take the cooked trout to Charlie.

		I need to smith Charlie one iron dagger.
		I need to take the iron dagger I smithed to Charlie.

		I need to take the iron ore to Charlie.
		I need to mine Charlie a piece of iron ore from an iron vein.

		I need to craft Charlie a leather body.
		I need to take the leather body I crafted to Charlie.

		I need to craft Charlie some leather chaps.
		I need to take the leather chaps I crafted to Charlie.
```

**Comment by Nightfirecat** [comment]
I'll look at taking a crack at abstracting the master clue hot/cold solver to apply to these new hot/cold beginner clues, and implementing the beginner map clue solver for next week.

**Comment by xDemoN** [comment]
With #8607 merged, the 2 new hot/cold clue locations (that aren't beginner) are done.

**Comment by TheAtomicOption** [comment]
Charlie challenge red chat notification text (note the run-on sentence **is** accurate currently in game at least for this specific clue):
> You have completed Charlie's task, go back and give him the Pike.

Charlie challenge changed clue text after the challenge is complete:

> I need to take the cooked pike to Charlie.


Currently, reading a clue after accepting or completing Charlie's challenge does not create a clue overlay.

**Comment by Nightfirecat** [comment]
That's expected, since we don't have code which handles Charlie (or Sherlock, for that matter) clues. We're hoping to have that implemented in the near future.

**Comment by TheAtomicOption** [comment]
Are you referring to `public class ThreeStepCrypticClue` that lacks a `Set<>` of actual clue info? I didn't see a trivial way to pull request the info, then found this issue with search. My Java skills are mediocre (i.e. borrowed from C#), so it's probably best I don't try to finish that class if anyone else has plans to do it.

**Comment by Hydrox6** [comment]
`ThreeStepCrypticClue` has nothing to do with Sherlock or Charlie. I've got a PR for it 95% complete however
