### ISSUE TITLE
Automatically Track Slayer Target Aggression Timer

### ISSUE THREAD

**Issue by Jademalo** [runelite/runelite#8507]
**Is your feature request related to a problem? Please describe.**
Generally, I find that I primarily want to know aggression timers when I'm on a slayer task safespotting. I have to manually add whichever NPC is my target, and then manually remove it when I;m done.

**Describe the solution you'd like**
Have an option in the NPC Aggression Timer to automatically enable the timer for your current slayer target.

**Describe alternatives you've considered**
Manually adding works, but it's fairly tedious.

**Additional context**
I feel like this would be a fairly simple and extremely useful change. Not having to manually add NPCs every task would be super useful, and make the aggression timer plugin better.
I would also argue adding similar functionality to the NPC indicator plugin would also be extremely useful, but that's one for another ticket.

**Comment by LlemonDuck** [comment]
Added in c669f6462bf9a9bca82befdeb6bc58915b9ed6c4
