### ISSUE TITLE
Entry Swapper - Hide 'Empty' on potions

### ISSUE THREAD

**Issue by Dovry** [runelite/runelite#8512]
I have never been in a situation where I would rather empty my potion doses than drop the entire vial, or just bank it.

When decanting while out and about, it's easy to misclick and empty a 3-dose potion

Either hide the 'Empty' option on potions, or move it below drop, since you can just pick it back up if you misclick drop it.

pic related used to be a Prayer Potion (3) :'(
![image](https://user-images.githubusercontent.com/15201298/56084944-690c3580-5e3b-11e9-85c4-40ace56487cc.png)

**Comment by Trevor159** [comment]
We don't want to remove any menu options anywhere
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by Dovry** [comment]
wth, did you not read the alternative option I suggested?

**Comment by deathbeam** [comment]
You can already use shift-click configuration cant you?

**Comment by Dovry** [comment]
Please re-read what I'm asking for.

**Comment by deathbeam** [comment]
Please re-read my answer
