### ISSUE TITLE
my settings have been reset and notes are all gone

### ISSUE THREAD

**Issue by Aritoone** [runelite/runelite#8522]
yes im signed in and ive never used github someone please help me understand

**Comment by slimelia** [comment]
Having the same issue; I've tried signing out and back in but it has not restored my settings. Every time I close the client I lose my setting configuration, even when I've clicked to import it to my Google account.

**Comment by nevada5147** [comment]
> Having the same issue; I've tried signing out and back in but it has not restored my settings. Every time I close the client I lose my setting configuration, even when I've clicked to import it to my Google account.
> 
> Edit: I've tried uninstalling and reinstalling, which seems to have done the trick for now. Will update if my settings are erased again.

i just had to change mine just to reply to this but i have had that issue for the past week with everything i use on a daily but if it doesn't happen again then i wouldint be to considered about it personally that is

**Comment by deathbeam** [comment]
This should be resolved now, but the data that were lost are lost permanently so just redo your settings, sorry.
