### ISSUE TITLE
Barbarian Assault (Healer) health bar display

### ISSUE THREAD

**Issue by chanmioo** [runelite/runelite#8523]
Barbarian Assault healer role displays health of other players as 99/99, 87/87, etc.

Please consider changing this to display a health bar (similar to Opponent Information) for an easier time as the Healer role.

**Comment by whartd** [comment]
Should this be housed in the Opponent Information plugin or the Barbarian Assault plugin?

**Comment by Nightfirecat** [comment]
Teammates wouldn't be considered opponents, and it wouldn't really make sense to work only if the Opponent Info plugin was enabled, so BA plugin

**Comment by chanmioo** [comment]
down in the barbarian assault plugin. sorry, I just meant I'd prefer if the health bar looked exactly like it did in the Opponent Information one. it should visually be that health bar in place of the numerical health.

**Comment by Nightfirecat** [comment]
It doesn't need to look exactly the same. (see the Status Bars plugin)

**Comment by whartd** [comment]
I've been working on this, should have something to submit soon.

**Comment by whartd** [comment]
I based this on the Status Bars plugin. I'm not sure if it's an issue that it's drawing the overlay on top of the widget. 
![image](https://user-images.githubusercontent.com/21340086/56444131-81f66a00-62c5-11e9-9f33-d5ab4b58841e.png)

**Comment by chanmioo** [comment]
you have the right idea, this is much easier to read for the healer role.
could it turn from green>yellow>red?
