### ISSUE TITLE
slayer assignment counter not changing

### ISSUE THREAD

**Issue by waderz** [runelite/runelite#8525]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

If you have a current task going on the RuneLite client and finish that same assignment on mobile and start a new one the next time you use the RuneLite client it will still show the counter for the first assignment. 

**To Reproduce**
Go to Konar on the RuneLite client and get a task (fire giants). Start that task and in the middle of the assignment switch to playing on mobile. Finish the assignment on mobile and get a new one from Konar (bloodveld). Start that task then switch back to playing on the RuneLite client and while you're killing Bloodveld you will still get xp (duh) but the counter pops up and still shows the Fire Giants task

**Expected behavior**
I expected it to show me how many more Bloodveld I need to kill since it's giving me slayer xp to kill them.

**Screenshots**

https://imgur.com/I5WbUoI

Here I'm definitely on a Bloodveld task but it shows Fire Giants. Also my first ever brimstone key omegalul. 

**Environment (please complete the following information):**
 - OS: Windows/iOS 12.1 Mobile version 179.1
 - RuneLite version: 1.5.19.1
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Abextm** [comment]
please describe your issue

**Comment by waderz** [comment]
> please describe your issue

Sorry I double clicked something and posted it blank so I had to edit it.

**Comment by Twiglet1022** [comment]
You need to check your slayer gem/helm to let runelite update your task since there's no other way for the client to know how many you have left on your current task otherwise.

**Comment by Nightfirecat** [comment]
Just check your task at your slayer master, or using your helm or gem like Twiglet described. There isn't any way for the client to know that your task has changed since your last session otherwise.
