### ISSUE TITLE
Random Client crashes/disconnections

### ISSUE THREAD

**Issue by MichaelUnce** [runelite/runelite#8529]
**Describe the bug**
I would be playing runescape normally and randomly i will have a black screen/dc sometimes screen freezes completely and i cannot interact with the client at all. When it does the black screen it just takes me out the game and i have to log in again. Also this happens only to 1 account all the other accounts im playing on at the sametime dont dc/freeze

**Screenshots**
![index](https://user-images.githubusercontent.com/45104546/56101293-66b7e300-5ef0-11e9-890e-0c2181362f33.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - RuneLite version: 1.5.19.1
 - Launcher version: 1.6.0

**Additional context**
[client.log](https://github.com/runelite/runelite/files/3078011/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3078012/launcher.log)

**Comment by MichaelUnce** [comment]
At the time i was playing on the .jar version so idk if the logs are correct but they were the latest logs created

**Comment by Nightfirecat** [comment]
Was this one account on a different world than the other accounts? This sounds more like this specific account is disconnecting from its world than a client issue.

**Comment by MichaelUnce** [comment]
> 
> 
> Was this one account on a different world than the other accounts? This sounds more like this specific account is disconnecting from its world than a client issue.

Yes was on 359

**Comment by Nightfirecat** [comment]
I've noticed having connection issues myself on certain worlds today, and it sounds like other people have intermittently seen the same. I suspect it will probably go away in the next couple days if it's an issue on Jagex's side.
