### ISSUE TITLE
Standardise spacing of Chat Time plugin

### ISSUE THREAD

**Issue by loldudester** [runelite/runelite#8533]
**Is your feature request related to a problem? Please describe.**
It's a minor issue, but chat messages from a single person don't line up as the spacing for the Chat Time plugin is different for different numbers. See here: https://i.imgur.com/UMnHLA1.png

**Describe the solution you'd like**
I'm not sure if it's possible with how the chat box works, but if there's anyway to have the time characters be monospaced it would solve the issue.

**Comment by deathbeam** [comment]
I dont think this is possible but I agree that it would be nice addition

**Comment by Nightfirecat** [comment]
I also don't think this is possible since we're effectively just inserting text, and the RS font isn't monospaced.

**Comment by loldudester** [comment]
Yeah I worried it would be as simple as that. Worth asking though. Thanks!

**Comment by deathbeam** [comment]
Then I guess just closing this as wontfix makes sense as we cant implement it
