### ISSUE TITLE
Farming timers

### ISSUE THREAD

**Issue by Lexthegayotter** [runelite/runelite#8534]
**Is your feature request related to a problem? Please describe.**
Just a small issue, farming timers don't update to what is displayed if you use the geomancy spell, to check on disease or progress with kronos seeds

**Describe the solution you'd like**
Have farming timers use the info displayed by geomancy to update, the same way they do when the actual patch is loaded on the client

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by Kamielvf** [comment]
Duplicate of #7350
