### ISSUE TITLE
Smith all on Menu Entry Swapper

### ISSUE THREAD

**Issue by SkrillexAkaCraft** [runelite/runelite#8539]
When smithing and using an anvil you have to right click to make all, would it be possible to have that added to the menu entry swapper that it will say 'Smith all sets <item name>'?

Like you just have to left click what you wanna make and it will instantly smith 'all'

**Comment by Nightfirecat** [comment]
This is [a rejected feature](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping):

> `Menu reorder in shop/artisan skill screens`: Other clients don't implement these swaps, and would be too strong for numerous activities (examples include "Buy-50" swaps, "Make All" swaps for smithing/crafting, etc.)
