### ISSUE TITLE
Logging improvement

### ISSUE THREAD

**Issue by lajur** [runelite/runelite#8540]
i think it would be a good solution to make a generic logging of (http) request + response in the pipeline (intercept call before processing request), so nobody would ever care to catch exceptions (they would be caught in the pipeline) unless some actions has to be taken on exception. For example do some cleanup or respond specific status/error code, but ONLY IF clients need to act on it.

Furthermore, when already have generic logging in pipeline we can upgrade it. That is to add logging of unique request correlation id of a specific request. This would allow to follow (in logs) all log path of specific request/response and see exception logged if it occurs.

Even furthermore, that correlation id could be added to headers of request (as well by interceptors in pipeline), this way the correlation id would allow to correlate all services (if there are multiple) chit-chatting.

**Comment by deathbeam** [comment]
We cant just add "middleware" to okhttp to catch all exceptions, and they are usually useful. I don't think catching all exceptions is solution for anything in any case anyway. And if we will catch all exceptions what would we return, null?

Unless I am misunderstanding what do you want I will just close this as invalid.
