### ISSUE TITLE
Export loot tracker log back into the client

### ISSUE THREAD

**Issue by TerrorNisse** [runelite/runelite#8541]
**Is your feature request related to a problem? Please describe.**
It is very annoying if you want to do a grind of a boss to see how much you get from let's say 1k Vorkath and after a few hundred kills it removes half of the kills, making the loot tracker useless. The website shows them all, but without the price check. Also what if I only want to see my last 1k grind and not all of them.

**Describe the solution you'd like**
Somewhat a option for you to decide how many kills you would like to see in the loot tracker. Either Show all kills, a set amount and a reset to start over.

Keep up the good work though,
Terror_nisse

**Comment by Abextm** [comment]
Currently the client downloads the last 1k loots from the server and will display those. If it displays any more the current implementation of the panel becomes non responsive, so the number cannot be blindly increased.

**Comment by TerrorNisse** [comment]
That I can understand. But what about adding a option to save them locally as well?

**Comment by Abextm** [comment]
Having them local would have the same issue

**Comment by TerrorNisse** [comment]
What if you save kill 1000- not as seperate kills but together? It wouldn't need to loop through that much information. That way you can still do 1k seperate kills, but also load in total kills without much hassle

**Comment by Abextm** [comment]
The issue is not the amount of data held, it is the amount of data displayed, which would stay constant regardless of how it was stored on disk

**Comment by deathbeam** [comment]
You can already view full history on website, as abex said, the low amount displayed in client is intentional, and website has way more organized display for it anyway and its searchable
