### ISSUE TITLE
Add the option to have timestamps for non-chat messages

### ISSUE THREAD

**Issue by Shugy0** [runelite/runelite#8542]
Add the option to have timestamps for non-chat messages, such as level up messages, etc.

**Comment by hjdarnel** [comment]
It'd be helpful if these were toggleable per message type so you could enable/disable timestamps selectively.

**Comment by iawhd** [comment]
Was about to post the same thing, @hjdarnel makes a good point too.

**Comment by Kagiri12** [comment]
Yes please, this would be nice.
