### ISSUE TITLE
Chat replayed from the chat history plugin is not filtered through the chat filter plugin

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#8545]
This can be reproduced by filtering any kind of spam message at the GE, then hopping worlds.

**Comment by HalfOfAKebab** [comment]
Can confirm this is still an issue as of 1.5.28

**Comment by sadegr** [comment]
I've looked into this a bit, what I've found is that the historical messages are being censored by the chat filter plugin, but then replacing them on the string stack does not cause the message in the chat history to be replaced with the censored message:
https://github.com/runelite/runelite/blob/3700876cf89eaff2c66afa6ad021a6084c3bb505/runelite-client/src/main/java/net/runelite/client/plugins/chatfilter/ChatFilterPlugin.java#L151

The issue may lie within the cs2 scripts, but unfortunately that stuff is a bit outside of my wheelhouse.
