### ISSUE TITLE
2 + options when holding ALT on items

### ISSUE THREAD

**Issue by Synatec** [runelite/runelite#8550]
**Is your feature request related to a problem? Please describe.**
When highlighting an item it's always the same color, default purple. As an Ironman I always forget to pick up certain items I should pick up because they're hard or tedious to get as an ironman. I now mark them purple but everytime I go bossing I think I got a unique when it is actually just an uncut sapphire... 

**Describe the solution you'd like**
I'd love it if we got the option to highlight in different colors so I can highlight items I should pick up light red and rare items, untradables and uniques purple for that satisfying feeling of seeing a purple item on the floor. 
For example, the uncut sapphire would remain light red on the floor and the lets say, Primordial crystal is purple on the floor. 

**Describe alternatives you've considered**
Not highlighting the unique but I am scared I'll look over it and TP out of an instanced boss fight. Especially when it is an untradable drop which doesn't have GE value.

**Comment by TerrorNisse** [comment]
I might be missunderstanding you here, but do you mean HOLD ALT -> Then hit the + sign to make it highlighted in purple?

**Comment by raiyni** [comment]
You can adjust your item prices highlight colors to reflect this.
