### ISSUE TITLE
Agility Plugin: Show a timer on the moving blocks in the agility pyramid

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#8557]
The number of times I've been pushed off the pyramid because I thought I had a second longer than I did to run past it is frustratingly high

**Comment by GaryGooch** [comment]
I feel this could be an easy add, a small circular timer such as the one used in Tears of Guthix?

**Comment by forsco** [comment]
I believe you would need to be in range to see the last time it did its animation for the countdown to work properly.

**Comment by ShaunDreclin** [comment]
I think you would only need to see it move once, then just start counting game ticks from there

**Comment by fetchable** [comment]
I'd like to take a stab at this because I also feel this frustration

(Would be my first runelite contribution so it might take a while :) )

**Comment by fetchable** [comment]
#8647

**Comment by WesleyM77** [comment]
I created a plugin in the plugin-hub, for those still wanting this feature. https://runelite.net/plugin-hub/show/agility-pyramid-slider-block-timer
