### ISSUE TITLE
Client making network connections to runehq.com which causes AV false positives

### ISSUE THREAD

**Issue by cadyb** [runelite/runelite#8574]
Is there a reason why the runelite client would be making network connections to **192.169.82.146** or runehq.com, our endpoint AV Sophos has runehq.com flagged as malicious and looking at the virustotal report for it it seems to be less than legit now: https://www.virustotal.com/#/ip-address/192.169.82.146

I don't care if our users play OSRS with runelite but runehq.com seems to be no longer legitimate and having our AV freakout whenever a user uses runelite is a pain and potentially a security issue mattering on why/how the client is connecting to it.

**Comment by Adam-** [comment]
The client doesn't make connections to runehq.com.

**Comment by cadyb** [comment]
Yeah my bad I was reading the AV logs incorrectly. Sorry to report a invalid issue and waste your guys time. Keep up the good work!
