### ISSUE TITLE
Add ability to scale resizable mode HUD

### ISSUE THREAD

**Issue by rsrex** [runelite/runelite#858]
I'm not sure about the possibility of doing this, but a scaleable HUD would be a world of difference and open up playing on Resizeable Mode on pretty much most modern PC's. As it is, I really have trouble reading chat without leaning and clicking on menus would be far easier.

Cheers.

**Comment by SomeoneWithAnInternetConnection** [comment]
Related to #715, though probably not a duplicate, since being able to scale things might be nice in general, even without having an obscenely high DPI

**Comment by Adam-** [comment]
There is also #615, which is related, and is stretched fixed mode. It was merged earlier.

**Comment by rsrex** [comment]
I've tried Stretched fixed mode in other clients and the quality is very bad obviously, but the bigger thing is being used to resizeable. At this point I'd rather have small HUD in resizeable than stretch fixed mode. Might just be me and stretch fixed mode would fix it for many.

**Comment by Adam-** [comment]
N.B. this is closed by #6119 which does not really scale the UI but is scaling the whole game, which effectively will scale the UI.

**Comment by michaelgosling** [comment]
> 
> 
> N.B. this is closed by #6119 which does not really scale the UI but is scaling the whole game, which effectively will scale the UI.

I guess if you're fine with making everything blurry? I can't find a way to scale the resizable HUD while keeping the game clear :/

**Comment by Alexsuperfly** [comment]
gpu plugin will render the scene at full res which makes the only thing stretched the UI at that point

**Comment by michaelgosling** [comment]
Huh. I did not realize that. Thanks!
