### ISSUE TITLE
Minnow Fishing Plugin Adit

### ISSUE THREAD

**Issue by AHKSammich** [runelite/runelite#8584]
When fishing Minnows, and the 'shark' thing pops out of the water and eats your Minnows, the fishing overlay should indicate that you're not actually 'fishing' 

After recently transitioning from OSBuddy (OSBuddy have this feature, their plugin says 'Not ACTUALLY Fishing' when it happens. 

This is great for when I'm watching youtube or whatever and I can see the red text in the overlay in my peripheral vision.

**Comment by ddaltonzkd** [comment]
Is this still open?
