### ISSUE TITLE
Make clicking on the Wiki orb and then on a clue scroll take you to the Wiki page of that clue scroll

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#8588]
When you haven't been to Meiyerditch in ages for example, it can be useful to look up how to get there again with a couple of clicks. For Elite clues, it would open up this page: https://oldschool.runescape.wiki/w/Treasure_Trails/Full_guide/Elite , scrolled down to the correct clue step. This might require an update from the Wiki team to make it work, but I don't know.

**Comment by Abextm** [comment]
The wiki has enough data to implement this if they want.
