### ISSUE TITLE
Runelite-mixins build error on JDK 12 Source option 6 no longer supported

### ISSUE THREAD

**Issue by GSchuringa** [runelite/runelite#8593]
**Describe the bug**
While building the runelite-mixins project it displays the following error:

![image](https://user-images.githubusercontent.com/7204450/56459714-fb5e8d00-6397-11e9-8f23-ef2a34ba7d08.png)

**To Reproduce**
Building on Intellij Ultimate,

**Expected behavior**
Built the runelite source files

**Environment (please complete the following information):**
- Maven version : 3.6.1
- Java version 12.0.1
- Windows 10 x64
- RuneLite master branch (20-04-2019)

**Comment by Adam-** [comment]
This is non trivial for us to fix correctly, and probably isn't worth it until Java 14 comes around. For now we support both LTS releases of Java, 8, and 11.

**Comment by GSchuringa** [comment]
> This is non trivial for us to fix correctly, and probably isn't worth it until Java 14 comes around. For now we support both LTS releases of Java, 8, and 11.

Thank you for the quick response, just tried on JDK 11 and worked fine! issue is thereby closed

**Comment by deathbeam** [comment]
Well, no, this is still issue so it should still be tracked
