### ISSUE TITLE
Loot tracker does not keep track of all the kills

### ISSUE THREAD

**Issue by AbdelelKharbachi** [runelite/runelite#8596]
So basically i was killing Skeletal Wyverns and i closed the client yesterday on ~1300 kills, i reopened the client the next day and only had the loot showing from 1050 kills.

Please have a look into the loot tracker plugin :(

**Comment by Hydrox6** [comment]
The loot tracker only loads the newest 1000 drop stacks when the client opens. This is by design

**Comment by deathbeam** [comment]
Check https://runelite.net for full history

**Comment by Nightfirecat** [comment]
A bit more is explained in #7485 as well. But as deathbeam said, you can log in to runelite.net to see the full loot history.

**Comment by AbdelelKharbachi** [comment]
> The loot tracker only loads the newest 1000 drop stacks when the client opens. This is by design

a friend of mine was killing zulrah and had 50 kills one day the next day he had 31 on loot tracker, how is that possible?
