### ISSUE TITLE
Suggestion for banned players

### ISSUE THREAD

**Issue by corndawg49** [runelite/runelite#8597]
Hi, I am aware of the overhead usernames feature in runelite, and I wanted to suggest maybe implementing the list of banned runewatch usernames into this client, and visualizing it by setting a red line through the username. This could also be done through a list of selected usernames to which you could input people you want personally crossed off seperated by commas. Might be a bit more useful than the ingame ignore feature, and crossing it with runewatch can hopefully protect lots of players from being scammed.

**Comment by Hydrox6** [comment]
Duplicate of #3828
