### ISSUE TITLE
Removing warned styles only works if the style is pre-warned

### ISSUE THREAD

**Issue by josharoo** [runelite/runelite#860]
Overview of the Issue 
In the Attack Indicators plugin, the 'Remove warned styles' option only removes styles if they are selected as warned BEFORE ticking 'Remove warned styles' - this means if you tick 'Remove warned styles' and _then_ tick e.g. 'warn for attack', attack xp combat styles will not be removed and you are able to gain XP with those styles. They _are_ removed if you un-tick and re-tick the remove option. Most people would probably notice this and play with it until it works but there is still room for user error.

Reproduce the Error 
Have no attack styles warned
Tick 'Remove warned styles'
Tick 'Warn for ____' 
No style options are removed, and you can gain xp in the warned style that is supposed to be disabled

Suggest a Fix 
Whatever code is running on the ticking of 'remove styles' - possibly also run the same code when a 'warn for ____' is ticked?

This bug is also currently noted on the [wiki page](https://github.com/runelite/runelite/wiki/Attack-Indicator/ad0dfeaa9cc9a186f09edf30004e53b2db46d6b8) for this plugin in case people configure it incorrectly and leave an unwanted style usable. This warning can be removed once this bug is fixed.

**Comment by skimboarder** [comment]
I believe I've implemented a fix for this by inserting a call to 'processWidgets()' at the end of the 'onConfigChanged(ConfigChanged)' method inside of 'AttackIndicatorPlugin'. 

I'll be hopping in the discord to discuss things like testing and properly issuing a PR.

**Comment by sethtroll** [comment]
Was this fixed in #891 ?
