### ISSUE TITLE
Esc Close bank to close server side instead of client side

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#8602]
https://gfycat.com/calculatingradiantclumber
common example of anoyance when skilling is you use ESC to close bank and try to make for example potions. but you are still in the bank interface on server side so the potion making interface gets interupted.
A plugin that makes the esc close the bank server side instead of client side (not sure if this is the best way to explain it but its what i could think of).
E.G. clicking run energy icon closes the bank server side.
https://gfycat.com/sociablepinkamericansaddlebred

**Comment by Adam-** [comment]
This should be a Jagex thing to fix, we can't do this without doing bot-like things.
