### ISSUE TITLE
Slayer task command bug

### ISSUE THREAD

**Issue by papa723** [runelite/runelite#8604]
It cannot show the task to myself when using the !task command but it has no problem for other players to read it.
![d0b83de05d03de69cfcaead97d09de2](https://user-images.githubusercontent.com/44521018/56466485-7762de80-6445-11e9-9bfb-fa5645d3e43c.png)

**Comment by Nightfirecat** [comment]
Do you have the chat filter plugin enabled? If so, what are your settings for that plugin?

**Comment by deathbeam** [comment]
This looks like its being filtered by chat filter plugin, so just adjust your filters
