### ISSUE TITLE
Incorrect use of world masks

### ISSUE THREAD

**Issue by xdesr** [runelite/runelite#8605]
High risk standard world (W365) is incorrectly being defined as a PVP world.
The current masks for this world are: [MEMBERS, PVP_HIGH_RISK]
Whereas the masks for any PVP high risk world are:[MEMBERS, PVP, PVP_HIGH_RISK]

As current PVP high risk worlds are being defined as PVP worlds twice. 
would be ideal to change the PVP_HIGH_RISK mask to HIGH_RISK and remove the HIGH_RISK mask from PVP_WORLD_TYPES enum.
The world snapshot needs to be updated for this to work.

**Expected behavior**
High risk standard world (W365) masks should be [MEMBERS, HIGH_RISK]
and PVP high risk world mask should be [MEMBERS, PVP, HIGH_RISK]

**Comment by Nightfirecat** [comment]
To be clear, there are three types of worlds this could impact:

* Normal, non-high-risk PVP worlds
* High-risk PVP worlds
* High-risk worlds (non-PVP)

Can you confirm the bit masks for each of these? Sounds like we may just have a poor name for the high risk mask.

**Comment by xdesr** [comment]
- Normal, non-high-risk PVP worlds - Mask types: [MEMBERS, PVP] Mask bits: 5
- High-risk PVP worlds - Mask types: [MEMBERS, PVP, PVP_HIGH_RISK] Mask bits: 1029
- High-risk worlds (non-PVP) Mask types: [MEMBERS, PVP_HIGH_RISK] Mask bits: 1025
