### ISSUE TITLE
Menu Entry Swapper: Butterfly Jars

### ISSUE THREAD

**Issue by persecom** [runelite/runelite#8606]
**Is your feature request related to a problem? Please describe.**
Right-clicking to empty a butterfly jar.

**Describe the solution you'd like**
Have the empty option as a left click.

**Describe alternatives you've considered**
Suggesting this change on the weekly Q&A.

**Comment by Hydrox6** [comment]
Duplicate of #6210

Use [Shift Click Configuration](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#shift-click-configuration)
