### ISSUE TITLE
Incorrect Celastrus growth indicator

### ISSUE THREAD

**Issue by sswetonic** [runelite/runelite#8609]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The celastrus patch in the farming guild shows an incorrect time for the growth indicator. It's showing done when it's not and does not update when next to the patch.

**To Reproduce**
1. Plant a Celstrus sapling in the farming guild
2. Wait until the growth indicator says done
3. Check whether or not the tree is actually done

**Expected behavior**
The growth indicator should say done when it actually is.

**Screenshots**

**Environment (please complete the following information):**
- OS: Windows 10 bootcamp
- Client: Runelite latest version

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Abextm** [comment]
#7424
