### ISSUE TITLE
Runelite instantly closes at 0%

### ISSUE THREAD

**Issue by RetiredEmo** [runelite/runelite#8612]
Not necessarily a bug of the client, but somewhere in the past few days have caused my system to not let Runelite load up.

I can't quite put my finger on where I went wrong. I'm on windows 10.
I've attempted to fix it by following the troubleshooting guide, redownloading the client, fiddling with my firewall to make sure Runelite isn't denied access, I've deleted my repository folder, as suggested on a different thread, I've even reinstalled windows and cleaned out my harddrive and installed on a fresh copy of the system, and the problem still persists.

I'm on the newest version of Windows 10, and I'm using the newest version of the Runelite client. My drivers and bios are updated. The OSbuddy client does not work either, but the regular OSRS client does work.

Any advice? 
Also please do not close the thread as a duplicate. I've looked over all the recent issues with this, and attempted all solutions, with no luck.

**Comment by Hydrox6** [comment]
This kind of issue is better suited for the Support channel in the Discord. Come join us there
