### ISSUE TITLE
Runelite crashes whenever interaction occurs with client UI

### ISSUE THREAD

**Issue by Brucas1** [runelite/runelite#8615]
I am able to play Runescape through the client, however anytime I interact with the client itself a crash occurs. 

https://pastebin.com/jYYTkS0G

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration try this

**Comment by Nightfirecat** [comment]
This issue has seen no posts for nearly one year after being asked for more information, so I am closing it.
