### ISSUE TITLE
Item charge overlay number is at wrong offset when in bank

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#8618]
Comparing these two images:
![item-charge-wrong-offset-in-bank](https://user-images.githubusercontent.com/2199511/56539077-6359d280-6554-11e9-9003-dcf0cd4bd69f.png) ![item-charge-wrong-offset-outside-bank](https://user-images.githubusercontent.com/2199511/56539078-6359d280-6554-11e9-8900-7a6d3fce192c.png)

And this image, which shows only the games necklace in these two images overlaid:
![item-charge-wrong-offset-overlaid](https://user-images.githubusercontent.com/2199511/56539079-6359d280-6554-11e9-94e2-69483fe06a60.png)

The item charges number displayed in the inventory while the bank is open (in fixed viewport, not sure about others) is one pixel too far down and right than it is meant to be. This is reproduceable on master since the ItemWidget overlay change.

**Comment by Nightfirecat** [comment]
And an animated gif showing the issue:
![item-charges-position-issue-animated](https://user-images.githubusercontent.com/2199511/56540312-e03a7b80-6557-11e9-96c3-99d888f25de4.gif)

**Comment by xdesr** [comment]
This issue occurs with all recently updated Widget item overlays : rune pouch, slayer helm , item charges and inventory tags, when in the bank interface the itemWidgetCanvasBounds x,y  increase by 1 pixel
