### ISSUE TITLE
Opponent info not updated until retargeted

### ISSUE THREAD

**Issue by l2-** [runelite/runelite#862]
reproduce: attack an opponent and click away when you see the xp drop. the hp info will not update until you target the npc again

**Comment by devLotto** [comment]
This might be if the server stops sending HP data when you stop interacting with the opponent?

**Comment by l2-** [comment]
I'm not sure but i noticed this at raids when running olm for example or attack vanguards im. i didn't notice this with other clients but i may have to test it again on other clients

**Comment by l2-** [comment]
nah definitely a RL issue since you can see the opponent hp bar ingame get smaller but the target info doesnt update

**Comment by Adam-** [comment]
This is because when you click away you are no longer interacting with the NPC

**Comment by Kamielvf** [comment]
OSB works like this as well, at least from what I can remember it doesn't update if you don't have a target.

**Comment by deathbeam** [comment]
Reopening because of #887, if this is valid, leave it open, if not, close again.

**Comment by Adam-** [comment]
Added in #917
