### ISSUE TITLE
Add numbers to on screen markers

### ISSUE THREAD

**Issue by GaryGooch** [runelite/runelite#8621]
Add on screen numbers for screen markers. For instance when having multiple screen markers on for agility clicking, being able to identify which one is next in the sequence can be hard to remember. Being able to number each screen marker (for instance adding the number into the middle of the marker) helps the user identify which marker would be next in the sequence.

**Comment by Reasel** [comment]
I feel like this would kind of be messy however you ended up implementing it. If you show a number in the center that only works for certain cases. Adding the marker name above the marker would also just take up screen space... Maybe very small and in one corner of the marker?

I know the use case you are talking about and I agree it would be nice.

**Comment by GaryGooch** [comment]
> 
> 
> I feel like this would kind of be messy however you ended up implementing it. If you show a number in the center that only works for certain cases. Adding the marker name above the marker would also just take up screen space... Maybe very small and in one corner of the marker?
> 
> I know the use case you are talking about and I agree it would be nice.

I'm not sure of the best user friendly method that could be eventually implemented. It's all down to user preference. Ideally for me as I use the translucent fill in the boxes the number could be worked the same, have a certain opacity level on it that can be adjusted on the users needs. 

I think they're plenty of implementable options that could be then left down to the users discretion what they preferred to use.

**Comment by xdesr** [comment]
I would prefer to show the name of the marker above it and have that toggle-able which would allow for this and more use cases, i will look into this now.

**Comment by Hydrox6** [comment]
At the moment, you can recolour markers to show the order you want. Making a rainbow or a gradient where the colours are different enough is usually easy enough to follow

**Comment by GaryGooch** [comment]
Disagree. Colours are in a random order meaning having to remember which
colour is for what. Having an on screen description or identifier
eliminates that.

**Comment by Hydrox6** [comment]
I wouldn't say following the classic rainbow of Red Orange Yellow Green Blue Purple Pink is a "random order"

**Comment by xdesr** [comment]
Is this something you are after?
![2019-04-23_14-56-03](https://user-images.githubusercontent.com/49791189/56586653-00118400-65d8-11e9-9de4-225037187f9f.png) 
If the text was to be displayed inside of the box then we would run into issues when the markers get too small.

**Comment by Reasel** [comment]
> I wouldn't say following the classic rainbow of Red Orange Yellow Green Blue Purple Pink is a "random order"

Yeah, but it could be a lot easier to do.

@xdesr I like the label like that but what I was saying is that some people might not. I like the idea of having two colors for each marker. The rim and the fill. Then you can have the text be with the rim.

**Comment by GaryGooch** [comment]
Xdesr that's pretty much my thoughts!

**Comment by Nightfirecat** [comment]
Much like the feature request for labeled ground markers, I feel if you're using so many screen markers that you need labels/numbers to remember which ones do what, you're using too many at once and should remove some instead. Just my 2 cents.

**Comment by XrioBtw** [comment]
Any updates on this? PR #14511 has an implementation for this

**Comment by Adam-** [comment]
Added in 109ad81473be78fba1a7ca1ab49dc140f194413f bit labels applied to the markers using the marker name.
