### ISSUE TITLE
Wilderness level attack range does not work on high-risk worlds

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#8624]
1. Log in to world 365 (the only non-pvp high-risk world)
2. Enter the wilderness
3. See error

**Comment by xdesr** [comment]
On the CombatLevelPlugin Line 184:9 the if statement returns true due to the bug with the incorrect mask for non-pvp high risk worlds see #8605

**Comment by Strazdonis** [comment]
Ok

**Comment by Nightfirecat** [comment]
So I guess the issue is just that `PVP_HIGH_RISK` needs to be removed from the private `WorldType#PVP_WORLD_TYPES` set? (in addition to this world type being renamed to be more clear about this)
