### ISSUE TITLE
Alt-click price lookup only works on items in the inventory

### ISSUE THREAD

**Issue by SomeoneWithAnInternetConnection** [runelite/runelite#863]
The biggest missing ones here are probably the fake "inventory" when you've got the bank open, as well as the items in the bank. Other places where it might be nice to have include the equipment panel and items on the ground

**Comment by Kamielvf** [comment]
probably also items in trade etc.

**Comment by ShaunDreclin** [comment]
Didn't even know this was a feature. Neat!

**Comment by Adam-** [comment]
I guess this auto closed from the PR closing. If you really want trade then maybe open a separate issue.
