### ISSUE TITLE
Idle Notifier: No Notifications for Pottery Crafting

### ISSUE THREAD

**Issue by iRoxor** [runelite/runelite#8630]
**Describe the bug**
The Idle Notifier does not notify the user when they are finished interacting with the Potter's Wheel nor when using the Pottery Oven.

Secondly, there is no notification when a player levels up using these crafting methods (as a workaround, a player can be notified by turning on the Screenshot module), even though this feature is present when fishing.

**To Reproduce**
1. Use "soft clay" on **Potter's Wheel** and select an option.
2. Wait to finish.
3. No notification when finished.

--

1. Use "unfired X" (from previous steps) on **Pottery Oven** and select an option (if applicable).
2. Wait to finish.
3. No notification when finished.

**Expected behavior**
Upon transforming all of the items available in your inventory into the finished product, the Idle Notifier should throw a "... is now idle!" notification. Runelite should also notify the player when they level up using these methods.

**Screenshots**
This screenshot shows that Runelite did not output into chat that the player had become idle due to stopping from leveling up while using the pottery crafting benches.
https://i.imgur.com/1AkvZIz.png

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.20
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
Level-ups don't trigger any notifications in general, so I don't see why it should specially do so while crafting pottery. (Turn on notifications from the screenshot plugin and enable screenshots of level-ups if you want that)

Sounds like the pottery animation just needs to be tracked in the idle plugin.

**Comment by iRoxor** [comment]
Ah, I thought there was a notification for leveling up. It was probably just the screenshot module, then.
