### ISSUE TITLE
Account got banned, while using RuneLite 

### ISSUE THREAD

**Issue by ralaud** [runelite/runelite#8638]
I was not playing Runescape for 4 years and just wanted to start Old School Runescape again. But this experience about Jagex and the worst macro detection did make me reconsider playing Runescape again.

I was banned two days ago. I have submitted an appeal, but Jagex did not even allowed me to tell them my opinion. They just did not accept my appeal. I think Jagex did implement some code to verify if the user is using the original Old School Runescape Client or not. I was just leveling my combat and at the same time I was collecting cow hides, to earn some gold. I was doing it myself, while watching TV (I never used a bot!). Fortunately I just wasted 24 hours. 

My intention with this issue, is not to make RuneLite worse, RuneLite is a nice lightweight client. Which is by the way, working better than the original one. My intention is just to make clear, that Jagex don't like to allow 3rd party software, so the macro detection will detect you as a bot. It is equal if you are botting or not. They maybe just verify the signature of the original Old School Runescape Client and mark 3rd party software as potential macro.

Again, my intention is just to tell you guys, that the macro detection from Jagex in not working well!

Best regards,
ralaud :)  

![Screenshot_2019-04-25 Regelverstoß-Beweis - RuneScape Old School RuneScape](https://user-images.githubusercontent.com/27868982/56752444-8e2c6c80-6788-11e9-8a3d-aa867b78f1b8.png)

Thats the Email I got for my appeal request:
![rs-email](https://user-images.githubusercontent.com/27868982/56753920-f7fa4580-678b-11e9-8003-5afddacd926b.png)

**Comment by Strazdonis** [comment]
Interesting to see something like this. Either Jagex really messed up or you're lying or someone else was using your account since we all, obviously, are using runelite ourselves and Jagex has stated before that they are **not** against third-party clients like OSB or Runelite.

**Comment by deathbeam** [comment]
This is not related to RuneLite at all, so it must've been something else.

**Comment by ralaud** [comment]
> Interesting to see something like this. Either Jagex really messed up or you're lying or someone else was using your account since we all, obviously, are using runelite ourselves and Jagex has stated before that they are **not** against third-party clients like OSB or Runelite.

I am not lying and it is not possible that someone else used my account (I activated Two-factor authentication before I started playing). I started playing for fun again, not for botting. In my opinion there is no sense of botting in a game, the fun factor is more important for me.

And why I should lying and write it here? I will not get my account back and if it is so easy to ban a player for botting, even if the player never used a macro or another bot client. In summary, ban without a reason. There is no sense for me, for playing this game again and get banned if I play for example 1 year. With this experience I considered not playing Runescape again, so I do not care if you believe me or not.

To avoid something like that again, I would suggest an "Anti Bot" feature in RuneLite Client. Some code to prove Jagex, that you was using RuneLite and not a macro client or a modification of RuneLite.

Runescape was nice 4 years ago, when I played quite often. But now, even if it was only 24 hours of play time, it looks like for me that about 50% of players are bots and scammer. Anyway I wish you guys a nice time!

Best regards,
ralaud

**Comment by Kamielvf** [comment]
Since RuneLite does not play the game for you, it will not trigger bot/macro bans. Also we cannot unban you account so please stop responding on this issue and contact Jagex support or appeal.

**Comment by FubarPerth** [comment]
I just tried to login today and I've been Banned same as you on the 7th of May at 10am. 
Considering I haven't played in 4 weeks and was at work from 5-5 that day I have no clue why I've been banned... also the ban appeal system is an utter joke!!

**Comment by ralaud** [comment]
> I just tried to login today and I've been Banned same as you on the 7th of May at 10am.
> Considering I haven't played in 4 weeks and was at work from 5-5 that day I have no clue why I've been banned... also the ban appeal system is an utter joke!!

Just how I told, Jagex Anti-Macro-Detection system is just a joke. They allowed using Runelite client, but I think it will be detected as not authorized client by the macro detection.

**Comment by osrsplaya** [comment]
This same thing happened to me 2 days ago this is not an invalid post I was banned for macro major and I was just using runelite for ge active trade price jagex has poor customer service and they have little support for these issues my account is 15 years old and I play clean I am afraid I am done with runescape after this

**Comment by CalebWhiting** [comment]
I was banned on the 24th of December 2019 on my main account and my ironman, the only client I have used is RuneLite, I got exactly the same generic response to my ban appeal, word for word.

**Comment by JagexbotsWedontTheirony** [comment]
Same here 7 of my accounts got banned when i have me on video playing by hand (public youtube videos a whole channel stopped from a false ban). i wont use rune lite again out of fear like an abused person trying to leave a bad relationship

**Comment by nlruk** [comment]
What are you guys doing on runelite to get banned? it's not possible to get banned just for using runelite as its an approved client.

Maybe post more information on the activity you were doing prior that got you banned or just admit you were using a bot.

**Comment by simbleau** [comment]
> just admit you were using a bot.

Either that or they were using 3rd party plugins or RL+ features for example and mistakenly didn't know the risk involved.

My money is honestly on that, or they were using mouse macros or auto clickers or something they thought was benign in nature, unaware of Jagex's stance on such shortcuts.

**Comment by nlruk** [comment]
btw even if you genuinely did only use runelite and authorized plugins but was botting on a different account connected to your IP (which is common) then you must write that.

This is what most probably happened.

**Comment by simbleau** [comment]
Another thing to mention is that Jagex will often ban players after an arbitrary amount of time that botting took place (which can be several **months**). This is to prevent botters from knowing what behavior was detected as botting. This guards against botters de-obfuscating the process of bot detection in order to circumvent those triggers.

This means if you stop botting and make a new (legitimate) account before you get banned for botting your other account, there's a chance you'll be banned on a legitimate account that is tied to the botter. Since you botted once, you are therefore ToS breaking scum. Jagex officially does not care about the legitimacy of any of your accounts, even if you never botted on them, as long as you botted once.

It only takes **one time** on an **alt account** _several months prior_ for **all of your accounts** to be banned randomly in the _present_.

**Comment by JagexbotsWedontTheirony** [comment]
look at my YouTube Runescape Rick and Runescape Morty
