### ISSUE TITLE
Add visual indicator for ammunition

### ISSUE THREAD

**Issue by rothsrs** [runelite/runelite#864]
Hey guys - how about an Ammo orb near the minimap?
This is a really crappy lower-than-mspaint quality idea of what I had in my mind - 
https://i.imgur.com/PyqxgKd.png
Cheers!

**Comment by Unmoon** [comment]
Extra ideas for this:
- Autocasted spells remaining
- Items with charges, like rings of dueling

**Comment by ShaunDreclin** [comment]
Not sure if this would be best done as an orb or just a general overlay. There isn't all that much room around the minimap. Maybe something like what Konduit does, have two orb "slots" and let people choose which ones they want to use

**Comment by Infinitay** [comment]
^ Was thinking about that when looking thru the api, to add on Unmoon's suggestion, I was thinking the orb would be 'split' and display your weapon charge+ammo if applicable, but there's only so much space as you brought up

**Comment by Kamielvf** [comment]
I think the way konduit does it is fine, one small orb displaying some info you can select. I'd be against using more overlays for this until we get the ability to move our overlays around.

**Comment by deathbeam** [comment]
Making this infobox would be probably best
