### ISSUE TITLE
Menu Entry swapper - Smithing, Could it be able to change the smith all sets to the top?

### ISSUE THREAD

**Issue by Sinderius** [runelite/runelite#8648]
It would be nice so I could just click the item I am smithing instead of opening the right-click menu and then clicking from there

**Comment by ShaunDreclin** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

> `Menu reorder in shop/artisan skill screens`: Other clients don't implement these swaps, and would be too strong for numerous activities (examples include "Buy-50" swaps, "Make All" swaps for smithing/crafting, etc.)

It'll be added to the vanilla client in the near future anyway, judging by the other interfaces they've updated recently
