### ISSUE TITLE
Mouse Tooltips Monster Bug

### ISSUE THREAD

**Issue by ajro9630** [runelite/runelite#8654]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Since yesterdays update, mouse tooltips has bugged when hovering over monsters. The tooltips sometimes do not appear when hovering over a monster, with the interface tooltips option unchecked, which normally allows to have monsters and objects highlighted but to not have inventory tooltips active.

**To Reproduce**
1. Go to mouse tooltips
2. Uncheck interface tooltips, check chatbox tooltips
3. Hover over a monster to see if it works 

(Only sometimes happens - possibly on a second login of a session? Restarting client occasionally fixes)

**Expected behavior**

For tooltips to be active on monsters and objects, but not for inventory items.

**Screenshots**

https://imgur.com/a/qRkhjpC

(working and not working, mouse is hovered over cerb in same style for first ss)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.21
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by WhaleGuy3** [comment]
We're you able to fix it? Been having this probelm for a while.

**Comment by ajro9630** [comment]
Hi, I have had this problem again - is there any advice to fix it?

**Comment by Nightfirecat** [comment]
Please upload your client logs from the day you experienced this bug

**Comment by 1CooKiee** [comment]
I also have this issue fairly often, I'll post my logs from today when it's most recently happened though I put them on the discord and they said they couldn't see anything wrong.
[client.log](https://github.com/runelite/runelite/files/4843222/client.log)

**Comment by Adam-** [comment]
This is probably fixed now by https://github.com/runelite/runelite/commit/e53e33d6fb53abab9397bd17f462d692a65a1ab5 - reopen if it isn't.
