### ISSUE TITLE
Screenshot plugin making multiple screenshots

### ISSUE THREAD

**Issue by JacoboMoral** [runelite/runelite#8656]
If you toggle multiple screenshot options (such as Screenshot Boss Kills, Screenshot Valuable drops and Screenshot Untradeable drops), plugin will trigger multiple times at the same instant of time. 

Take this image as an example:
![2019-04-26 19_58_06-Window](https://user-images.githubusercontent.com/24235786/56826957-c356be80-685d-11e9-9e87-94163cb576a0.png)

Plugin triggered 4 times for the same picture. I request it to change to only make one, or add the possibility to choose whether to screenshot multiple times or just once.

**Comment by deathbeam** [comment]
You can always just disable some screenshot options. This is intentional, and I dont think there is way around that.
