### ISSUE TITLE
CTRL TO SHOW GROUND ITEMS

### ISSUE THREAD

**Issue by ZebGasm** [runelite/runelite#8665]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always

- frustrated when When i press ALT to move my camera and my loot shows up Like this i would 
   like it to be like osbuddy to move it to CTRL https://imgur.com/tPbjgql

- Also i would love to be able to have this option to remap the F keys to other Binds on my 
 Keyboard i use AHK for it but it would be nice to have it in runelite.  Example to suspend the 
 Remap just like WASD camera press enter so you can chat https://i.imgur.com/hvsyH25.png

**Describe the solution you'd like**

In ground items to option to Switch Between CTRL/ALT to show hidden loot

**Additional context**
Sorry for my bad english i hope you understand what im tying to say i explained it best as i could Thanks in advance

**Comment by deathbeam** [comment]
This is duplicate
