### ISSUE TITLE
Ruenlite won't run

### ISSUE THREAD

**Issue by Hakameda** [runelite/runelite#8679]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Power went out while RL was loading, It refuses to open or do anything now. Even reinstalling changed nothing. Clicked to open, No loading cursor or anything. Just does nothing

**To Reproduce**
Have a snowstorm at the end of april in an old house

**Expected behavior**
Get some gains

**Screenshots**

**Environment (please complete the following information):**
Win 10
**Additional context**
I don't see any logs, they seem to be lost after the reinstall

**Comment by Nightfirecat** [comment]
Does this persist after deleting your `~/.runelite` folder and re-installing?

**Comment by hourfreedev** [comment]
I'm not sure I can reproduce a snowstorm, but if there aren't any logs for some odd reason, you could try running the following command in command prompt to see where the launcher is failing.
`java -jar "%LocalAppData%\RuneLite\RuneLite.jar" -debug`

Posting the error that is produced would be very helpful in narrowing down the problem. Alternatively, if no error is shown, you could paste the output in its entirety.

**Comment by Hakameda** [comment]
Yeah it was kind of weird, Never seen something like happen. I just tried removing .runelite, Didnt seem to change anything and was a fresh download of the runelite installer

**Comment by Hakameda** [comment]
So running that command, Actually did open runelite. But the icon starter still does not work

**Comment by Hakameda** [comment]
https://pastebin.com/itMBZqxD

**Comment by hourfreedev** [comment]
The log looks normal from what I can tell, which would make sense as the client initialized without an error when you ran the jar directly. 
Are you able to launch RuneLite by running the executable directly instead of the using shortcut? That could be tested by running the following command in command prompt:
`%LocalAppData%\RuneLite\RuneLite.exe`

**Comment by Hakameda** [comment]
Does nothing when i run it

**Comment by hourfreedev** [comment]
Can you run `%LocalAppData%\RuneLite\RuneLite.exe -c --console` and post the output if any here?

**Comment by Hakameda** [comment]
Changing working directory to C:\Users\Haka\AppData\Local\RuneLite ...

**Comment by Hakameda** [comment]
The workaround had an odd side effect as well - http://prntscr.com/ni4xlm

**Comment by hourfreedev** [comment]
I may be wrong, but I believe that's a side effect of playing on higher resolution such as 4k. You should be able to enable the `Stretched Mode` plugin and change the settings (specifically the `Resizable Scaling (%)` setting) to your liking in order to fix that.
