### ISSUE TITLE
Add an overlay showing total loot value in the looting bag.

### ISSUE THREAD

**Issue by gccltl** [runelite/runelite#8682]
**Is your feature request related to a problem? Please describe.**
Add an overlay showing total loot value in the looting bag.

**Describe the solution you'd like**
Implement an overlay which displays total loot value in GP of the looting bag.
**Describe alternatives you've considered**
Clicking and checking myself.

**Additional context**
It's great for PvMing.

**Comment by Hydrox6** [comment]
Duplicate of #4143
