### ISSUE TITLE
Improve "North-east of Rellekka" clue hint

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#8683]
![image](https://user-images.githubusercontent.com/34870401/56870200-3dc54100-6a0c-11e9-9179-c9d36b010253.png)
Rename clue hint to northwest of fairy ring dks, instead of the current northeast of Rellekka.

**Comment by Nightfirecat** [comment]
In my opinion the clue hint is fine.

**Comment by JeljoGb** [comment]
I like it more that I know the closest teleport to the location.
North-east of Rellekka could be inside the town's borders, making me use the Fremennik sea boots teleport.

**Comment by Felanbird** [comment]
This was added in 7b82d61e09bac82ed23934a93f3d519766c381a7
