### ISSUE TITLE
Online XP tracker doesn't handle queries encompassing player renames

### ISSUE THREAD

**Issue by hjdarnel** [runelite/runelite#8685]
**Describe the bug**
When I rename my character, and then get XP on that new name, I can't query for a time that includes that name change. If my query includes only "new name" time, it seems to work fine.

**To Reproduce**
1. Rename character.
1. Get some XP, wait 6 months.
2. Go to https://runelite.net/xp/show/overall/New%20Name/1week/now
3. This works.
4. Go to https://runelite.net/xp/show/overall/New%20Name/1year/now
5. This fails.

**Expected behavior**
If my "start date" for my XP query is on my old name, I should still be able to query. It should simply use 0 for those time periods, and start again where we have XP tracked.

**Additional context**
CML seems to handle this ok, though they have a manual rename procedure where "old username" xp is presumably migrated to "new username" xp. This would be user friendly enough for us as well imo.

**Comment by Nightfirecat** [comment]
This should be opened on runelite/runelite.net
