### ISSUE TITLE
Hide completed quest functionality removed

### ISSUE THREAD

**Issue by Alexgopen** [runelite/runelite#8689]
**Describe the bug**
The functionality to hide completed quests was removed in this commit:
https://github.com/runelite/runelite/pull/8354

This seems like an oversight, and now your only options are displaying All Quests, ONLY Completed, ONLY In Progress, or ONLY Not Started.

Previously you could toggle to hide the completed quests so that you could work down your quest list, and this feature was eventually added to RS2/3 at one point.  

**To Reproduce**
1. Go to the quest tab
2. Click on the button that replaced the old hide completed button
3. You no longer have the ability to hide completed quests

**Expected behavior**
The previously existing hide completed quests feature should still be available.  It could be re-implemented as an additional state that you can toggle to with the new button.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.21
 - Launcher version: 1.6.0

**Comment by ShaunDreclin** [comment]
On the UI side, the option could be called "Show Not Completed" and have the icon be a half red and half yellow circle
