### ISSUE TITLE
Implementing other 2010-era interfaces

### ISSUE THREAD

**Issue by chiragbharadwaj** [runelite/runelite#8693]
I was guided in #3048 to open up a new feature request for this.

### Is the feature request related to a problem?

Not really, it's more of a suggestion.

### Describe the feature that you'd like to see.

I am hoping that the "Interface Styles" plugin, which has a 2010-toggle, would let us choose from many more options than just health bars and inventory style. Basically I was wondering if it's possible to achieve something like this:

 + 2010-era hitsplats. Example:

![hitsplat](https://user-images.githubusercontent.com/7849039/56978726-29855f00-6b46-11e9-81c1-4b5ed5457b2b.jpeg)

 + 2010-era XP-tracking. Example:

![xp-tracking](https://user-images.githubusercontent.com/7849039/56978729-29855f00-6b46-11e9-83e5-7e62f9790ec9.png)

 + 2010-era XP drops. Example:

<img width="403" alt="xp-drop" src="https://user-images.githubusercontent.com/7849039/56978840-6ea99100-6b46-11e9-944f-bdbd1086d544.png">

 + 2010-era minimap interface. Example:

![minimap](https://user-images.githubusercontent.com/7849039/56978727-29855f00-6b46-11e9-87e7-35d480668cbc.png)

 + 2010-era chat fonts. Example:

![chatbox](https://user-images.githubusercontent.com/7849039/56978795-58033a00-6b46-11e9-9592-c6e643dd4679.png)

### Provide additional information.

If this is asking for too much, please let me know. I am fine with the way the client looks now and I am grateful for everything y'all do. This is just a suggestion for those of us who like how the game looked during that era, and it should be toggleable.

I have a bit of professional programming experience, so I was also wondering if I am allowed to submit a pull request with my own implementations of these features in a forked version of the project. I am sure that anything written by anyone undergoes an extensive review/QA process before being merged, but I would like to see these toggleable features added, and if the main team is a bit busy with more important QOL plugins, I am more than happy to step up and try to implement them myself.

**Comment by Kamielvf** [comment]
Each of these should be a separate issue, else the same will happen as what happened in #3048.

Also these hitsplats you posted are not the ones from 2010 era, these are:
![2010](https://user-images.githubusercontent.com/35824069/56979850-03c67d00-6b7b-11e9-8844-469ddae3f93d.png)

**Comment by chiragbharadwaj** [comment]
My apologies. I didn't want to spam the issue tracker by opening 5 different issues. I can open them separately later this evening when I have some more time.

And I see, it seems that these hitsplats that I was talking about are from an different time period. I seem to remember them quite well, though. When I think of RS2-era hitsplats those are the ones I think of, not these.

**Comment by Ammako** [comment]
This chat font is also not from 2010, it's from 2014 (post-EoC.)

**Comment by chiragbharadwaj** [comment]
Yes, you're right. Here's an example of the 2011-ish style chatbox that I was interested in:

![2011](https://user-images.githubusercontent.com/7849039/56998779-961a5100-6b7a-11e9-98b8-93ec02666b1d.png)

It also shows that the hitsplats are from ~2011, but pre-EOC. This was the interface style that I was interested in. It is clean, compact, and easy to read IMO. Hitsplats in OSRS are a bit more messy.

This image also contains an example of the XP-tracker. Perhaps what I was really interested in was a 2011-era interface, which subsumes the 2010-era health bars + inventory styles. 

Probably opening 5 different feature requests for the dev team is very annoying though. Am I allowed to join your Discord and try implementing it myself? I know that custom plugins are not taken very kindly towards, so if you would prefer that I do not try implementing this myself, please let me know and I will not do it.

**Comment by Nightfirecat** [comment]
Opening 5 different feature requests would actually be preferred, that way they can be separately tracked and implemented. But feel free to join discord to discuss as well.

**Comment by chiragbharadwaj** [comment]
I see. OK, I will join Discord sometime towards the end of this week when I have some more time and discuss with everyone to see what the consensus is. I imagine this will probably not be popular enough, though.

Thank you.

**Comment by Ammako** [comment]
For future reference: [#6937](https://github.com/runelite/runelite/issues/6937) and 
[#5106](https://github.com/runelite/runelite/issues/5106) already exist (for minimap and xp tracker respectively.)
