### ISSUE TITLE
World map labels malfunction in Fixed screen

### ISSUE THREAD

**Issue by Ammako** [runelite/runelite#8697]
**Describe the bug**
Labels on the world map that have been modified by the World Map plugin don't show properly and get kinda cut off when in Fixed screen. Behavior kinda differs depending on whether Stretched Mode is enabled or not (see pictures down below.)

**To Reproduce**
1. Have World Map plugin enabled and have the game in Fixed screen
2. Open world map and mouse over an icon that the World map plugin affects
3. The labels will be either completely invisible or get cut off depending on where they are on the screen

**Expected behavior**
The labels showing up properly.

**Screenshots**
Stretched (x2):
https://gfycat.com/bouncyobedienteider

Standard size:
https://gfycat.com/limitedlankydogwoodtwigborer

**Environment (please complete the following information):**
 - OS: Windows 8.1
 - RuneLite version: 1.5.21
 - Launcher version: 1.6.0

**Additional context**
This happens even if World Map is the only plugin active. It also depends on the size of the client window (the issue doesn't happen when the window size is the smallest it can be for Fixed screen, and it will cut off at different points depending on how large the screen is.)

**Comment by garrettspringer** [comment]
I just tested this on MacOS and found the same bug.  This issue only happened when the screen was standard size (fixed) and the RuneLite client was fullscreen.  The locations affected by the World Map plugin were completely invisible in this setting.

**Details:**
- MacOS 10.14
- RuneLite Version: 1.5.22.1
- Launcher Version: 1.6.2

**RuneLite in fullscreen with a fixed window size**
https://gfycat.com/FarflungAgedAndalusianhorse
