### ISSUE TITLE
Menu Entry Swapper not working with Juna (Tears of Guthix)

### ISSUE THREAD

**Issue by xSlysoft** [runelite/runelite#8698]
When interacting with Juna at Tears of Guthix, the menu entry for story no longer defaults to the top option. The option to swap her entries is not in the menu entry swapper plugin, but I am positive that this used to work the last time I did ToG.

Was this removed in a recent update?

**Comment by Nightfirecat** [comment]
This feature has not yet been added. #7150 is open requesting it, and #7151 implements that request, but has not yet been merged.
