### ISSUE TITLE
NPC indicators "true position highlight"

### ISSUE THREAD

**Issue by buldosis** [runelite/runelite#8702]
At the moment, the NPC indicator "tile" highlight only highlights around the monsters character and doesnt show its true location of the monster (i.e. if it has long attack animations, its actual location is very wrong from the one thats shown on your screen if you are moving around).
The npc indicator "south west tile" highlights its true location but only the south west tile, would work on 1x1 npcs but not bigger, so this would be the same thing but would work for other npcs bigger than 1x1's

**Comment by jachymb** [comment]
This would be very useful to have for PvM activities where you specifically want or specifically do not want to stand under the monster.

**Comment by Nightfirecat** [comment]
We've had to remove this feature in the past ([see Adam's comment on this](https://github.com/runelite/runelite/pull/7748#issuecomment-636353341)) so we're not likely to add this feature again.
