### ISSUE TITLE
High contrast black mode for chat box (Legally Blind)

### ISSUE THREAD

**Issue by Vexflame** [runelite/runelite#8704]
Change the colours of the chat completely including the text and background of the entire chatbox, I cannot see the text due the colour scheme OSRS uses if there were anybody out there that could create a completely colour customizable chatbox I could actually see the chat and talk to people in game due to this issue I cannot communicate with anybody in game unless its in private DM's (When split) (Even then its tough if I'm in a snowy area)

So I cannot help others if they start following me asking for help nor can I join a clan and use the in game text channels to communicate with others, making the game kinda RPGish which for me isn't the most fun thing, I enjoy the game enough to play it still but would love the chance to join the in game community.

Colours that would help me a lot are.
Black Background
Yellow Text
Light/Sky Blue for boss drops and chat popups like daily/weekly resets etc.

Regardless anything with a dark background and lightly coloured text would improve my quality of gameplay dramatically thanks to anyone reading that can be of any assistance, I do have low vision around 9% remaining and decreasing slowly.

I will make another post for other things in the game I cannot see and wish to have assistance on tackling I don't have any coding experience, its hard to get heard in the community when you're a single person but would love to have any help where its needed.

Thank you.

**Comment by StaleDeveloper** [comment]
I can definitely fix this for you but could you please message me on discord to discuss further.
Stale#2048

**Comment by Vexflame** [comment]
Thank you so much for what you have made so far on the plugin its amazing exactly what I need to be able to access the chat in game, now I can talk to people and see boss drops and daily resets in the chat and read NPC options with eaze
<img width="716" alt="Stale" src="https://user-images.githubusercontent.com/48697392/57205426-c185bb80-7012-11e9-88b2-6b1773b167cd.png">

**Comment by SageBajeebus** [comment]
idk if anyone will answer since this was a year ago. but how does one do this? is it in runelite? or is it a osbuddy thing? i have runelite and i wanna mess with chat colors but the lighter colors hurt my eyes. and i cant seem to find an answer anywhere. and this shows me its possible but again no answer on to how is here xD lol so if either of you see this. let me know xD <3

**Comment by Alexsuperfly** [comment]
the chatbox opacity plugin on the [plugin hub](https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub) should likely do what you want

**Comment by SageBajeebus** [comment]
> the chatbox opacity plugin on the [plugin hub](https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub) should likely do what you want

Thank you very much! didnt even know the plugin hub was a thing but its awesome xD thank you again <3

**Comment by Nightfirecat** [comment]
I think that plugin is a satisfactory solution to this issue, so I am closing this request.

**Comment by Vexflame** [comment]
The issue was resolved temporarily and someone did code me a black
background/yellow text version of the Runelite plugin and named it
Vexvision but they didn't add it to the main line of code and implement it
permanently
