### ISSUE TITLE
Maven variable consistency

### ISSUE THREAD

**Issue by WilliamCollishaw** [runelite/runelite#8709]
The maven plugins and dependency version variables are inconsistent. They differ between hard coded and variable.
This issue will focus on converting all versions to variables and if the package is used across multiple modules, the version will be defined in the parent pom.
 EDIT: Prevent upgrading any packages. Focus on the variable consistency.

**Comment by abextm** [comment]
The way it is now (and the way it should stay) is that anything where there are >1 module depending on a single dependency should be in `dependencyManagement` in the root pom. The properties are for when there are multiple dependencies that should be versioned together, (jogl and its natives for example).

Additionally we can't easily accept PRs relating to the root pom as we have to rebase them onto our internal branch, which for things like this means redoing them from scratch. Best case scenario is that is our internal branch has an inconsistent style, worst (and imo most probable) case it breaks in some non-obvious way.
