### ISSUE TITLE
Screenshot Subfolders

### ISSUE THREAD

**Issue by Jademalo** [runelite/runelite#8711]
**Is your feature request related to a problem? Please describe.**
After playing for just over a month, I have over 2,300 screenshots in my screenshot folder. Windows is beginning to struggle to load the folder, and actually finding a given screenshot is an absolute nightmare.

**Describe the solution you'd like**
The screenshots should be organised into subfolders. 
The actual subfolders themselves are fairly easy to decide, simply separate each of the selectable categories in the plugin into their own respective folders.

- Manual Screenshots
- Rewards
- Levels
- Kingdom Reward
- Pet
- PvP Kills
- Boss Kills
- Deaths
- Duels
- Valuable Drops
- Untradable Drops

Levels could also potentially be divided into further subfolders for each skill, since theoretically a maxed character could have 2245 screenshots in their levels folder. 

This would not only make searching for a specific screenshot much easier, it would massively reduce the loading time of the folder and the indexing when viewing it on windows.

**Describe alternatives you've considered**
You could do this manually, but that's inconvenient

**Comment by Nightfirecat** [comment]
Not closing since it sounds like there's some support for something like this. But I can say I've got a similar number of screenshots in my main's screenshots folder and it loads fine for me on what's probably now a middle-of-the-line Windows computer. (though the screenshots are stored on a SSD, which is probably what makes it quicker)

You could arrange your screenshots into personal folders if you find it's an issue for you, and that would have you set until you end up with another 2000 screenshots.

**Comment by Jademalo** [comment]
It loads relatively fine, but if I try to sort them by date then it seriously struggles and takes a long time to index. This is a new PC with a new install, and an i7 8086 with a 570 Pro nvme ssd.

Regardless of that though, it is extremely inconvenient to find a specific screenshot, since scrolling to a specific place is very difficult and searching is pretty slow for me. Obviously automatic screenshots are named which helps, but for what I imagine would be a relatively simple addition I can only see positives.

**Comment by raiyni** [comment]
relatedish #7840

**Comment by AverageHumanoid** [comment]
I have over 22000 screenshots in mine (mostly from clue scrolls) so I've had to use the command line to find anything and copy them into a another directory.

**Comment by Jademalo** [comment]
Actually, that's a relevant thought - It might be worth having different tiers of clue scrolls in their own subfolders too.

**Comment by Jademalo** [comment]
I feel like either leaving them in the root directory or calling the folder "Manual" would be fine. I think after considering it a bit, I'd just leave them in the root screenshots folder.

**Comment by BopOSRS** [comment]
Any updates on this? Would really like this or something similar added as sorting through thousands of screenshots can get annoying

**Comment by dekvall** [comment]
As you can see, #8813 is is open and should close this issue. It will get merged eventually :)
