### ISSUE TITLE
Create screenshots for virtual levels.

### ISSUE THREAD

**Issue by hugofaas** [runelite/runelite#8719]
**Is your feature request related to a problem? Please describe.**
No, it's not a problem. 

**Describe the solution you'd like**
I would love it if Runelite could fake a level up screenshot when you hit a virtual level. That would mean saving a screenshot as it does with actual level-ups and also faking that chatbox overlay that you get when leveling up below 99.
(Chatbox overlay: Skill icon + "Congratuations, you just advanced a Range level. Your Ranged level is now 100")

**Describe alternatives you've considered**
I'm currently taking the screenshots with my mouse hovered over the skill, to in that way tell the viewer that that is what the screenshot is about. But that's not very clear and a lot less cool than having a real level up screenshot.

**Additional context**
It would be a great aid in visualizing skilling progress after max, both for sharing purpose as well as for archiving the history of an account.

I saw this was suggested in the past, but that was without the chatbox overlay part. I agree that the feature wouldn't make sense without that, so it depends on the feasibility of that part.

**Comment by WilliamCollishaw** [comment]
Related #6619
