### ISSUE TITLE
RSHD interactive/hover cursors

### ISSUE THREAD

**Issue by ena931** [runelite/runelite#8723]
Now that the custom cursor plugin is out, there is no excuse to not implement these bad boys.

![cursor](https://user-images.githubusercontent.com/50211252/57091229-f939ee00-6d08-11e9-9947-179c762df677.PNG)

They would fit perfectly with the 2010 interface plugin, though I reckon sourcing them could be somewhat of a problem.

**Comment by Hydrox6** [comment]
Duplicate of #4207
