### ISSUE TITLE
Rock shortcut at Zeah essence mine no longer highlighted

### ISSUE THREAD

**Issue by tma02** [runelite/runelite#8727]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The rock shortcut north of the Zeah essence mine was changed in an update today to go from two rocks to one. As a result, the rock is no longer highlighted as it was before and as how the other shortcuts are highlighted at the mine.

**To Reproduce**
Pretty much just go to the Zeah essence mine.

**Expected behavior**
Rock shortcut should be highlighted

**Screenshots**
![](https://puu.sh/DmYe9/81b7d11ecd.png)

**Environment (please complete the following information):**
 - OS: Win 10
 - RuneLite version: 1.5.22.1
 - Launcher version: 1.5.2

**Additional context**
N/A

**Comment by tma02** [comment]
I originally thought this was part of some Runecraft skill plugin but it's actually a part of the Agility plugin obstacle highlighter.

**Comment by Nightfirecat** [comment]
This is no longer highlighted because Jagex removed the previously-existing pair of rocks at that location and replaced it with a single object which can be crossed in both directions.

**Comment by xDemoN** [comment]
Closed by #8773
