### ISSUE TITLE
Error Creating a Run Configuration

### ISSUE THREAD

**Issue by volt72** [runelite/runelite#8734]
When I try to run RuneLite.main() I get this error. I followed the instructions so I am not sure why I am getting this error, the project builds fine but I cannot get the run configuration to work.

"Connected to the target VM, address: '127.0.0.1:53573', transport: 'socket'
Error: Could not find or load main class net.runelite.client.RuneLite
Disconnected from the target VM, address: '127.0.0.1:53573', transport: 'socket'

Process finished with exit code 1"

**Comment by Nightfirecat** [comment]
Please join our development discord channel for support with that.
