### ISSUE TITLE
Prayer potion overlay does not factor in holy wrench

### ISSUE THREAD

**Issue by Caia-OSRS** [runelite/runelite#874]
I assume this is an issue for super restores and well but I do not know for sure. In the picture I'm 70 prayer which is +24 normal but should be +25 with wrench.
<img width="201" alt="screen shot 2018-03-07 at 12 57 10 am" src="https://user-images.githubusercontent.com/37057941/37076060-c5056450-21a2-11e8-9c76-c5b8550f295f.png">

**Comment by Abextm** [comment]
This as also missing for ring of the gods(i), the prayer cape, and the max cape
