### ISSUE TITLE
Externalize SQL queries

### ISSUE THREAD

**Issue by arvyy** [runelite/runelite#8740]
Perhaps a rather minor thing, but I only mention it because code is otherwise very clean. 

SQL queries (e.g. https://github.com/runelite/runelite/blob/master/http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java) can be moved into xml file inside src/main/resources, and then read using standard java properties.

E.g.:
src/main/resources/sql/loottracker.sql:

```
<properties>
    <entry key="createTable">
    <![CDATA[
        CREATE TABLE ....
    ]]>
    </entry>
</properties>
```

and then inside service file:
```
Properties sqlProperties = new Properties();
sqlProperties.loadFromXML(new ClassPathResource("sql/loottracker.sql").getInputStream());
String createTableQuery = sqlProperties.getProperty("createTable");
```

**Comment by deathbeam** [comment]
If anything, it should be just loaded as string from sql file. but also, from what i said in discord:

```
20:57] deathbeam: even though current static strings are horrible too
[20:57] deathbeam: sort of
[20:58] deathbeam: its hard to read. but also it can be only 1 statement so sql files might confuse people
```

There is a reason why people use ORM (and stuff like Hibernate) in Java tho, but I guess adam wanted to use some simple lib that is not overkill like Hibernate is.

**Comment by arvyy** [comment]
I mean what's nice about this (as opposed to reading strings directly) is that you can have multiple queries in one file, so you can avoid the "1 statement per file" situation, and instead group as many as needed by domain.

**Comment by LlemonDuck** [comment]
No longer applicable here as of 055f5c2d2b37e63532f35dc470818723ab0477c3, moving to runelite/api.runelite.net#2
