### ISSUE TITLE
Add Olm Attack Timer

### ISSUE THREAD

**Issue by riceoftheasian** [runelite/runelite#8750]
Can we get a feature that counts Olm's attacks, and what his next attack would be. 
Something like this.
In the picture (S) would be the next attack while in 2 ticks would be the auto.
![Imgur](https://i.imgur.com/KHyPLLy.png)

**Comment by Kamielvf** [comment]
Since it looks like this is already someones plugin, maybe contact them and they could PR their work?

**Comment by melkypie** [comment]
This is prohibited as per Jagex's statement or 3rd party clients: https://secure.runescape.com/m=news/another-message-about-unofficial-clients?oldschool=1
This would fall under:

> Indicates the time where a boss mechanic may start or end
> Adds additional visual or audio indicators of a boss mechanic
