### ISSUE TITLE
[Windows 10] Title bar color match system light/dark theme

### ISSUE THREAD

**Issue by jeffreyjhaywood** [runelite/runelite#8752]
I play with custom window chrome turned off in order to make use of the Windows snap features. Many programs will automatically change the color of the title bar to match Windows' dark mode if it is enabled. Runelite's title bar remains a white color that does not match the rest of my other open programs.

Can a feature be added that will automatically change the title bar based on if the system light/dark theme is enabled?

I could play with custom window chrome enabled, but then I would not have the snap features.

**Comment by raiyni** [comment]
It's whatever your accent color is in desktop settings

**Comment by jeffreyjhaywood** [comment]
This isn't accent color though, its a separate setting in Windows for light/dark theme. For instance, if you are using the default theme for Google Chrome it will automatically become black if dark mode is enabled on your pc.

**Comment by abextm** [comment]
Only UWP applications (and applications that draw their own decorations and know about that setting) get their title bar changed by that setting. We are not a UWP application and cannot become one, nor can we easily read that setting, nor can we effectively emulate all the features one wants when drawing our own decorations.
