### ISSUE TITLE
Add the ability to show GE/alch values on top of items

### ISSUE THREAD

**Issue by Pikamander2** [runelite/runelite#8766]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to tell how much the items in my inventory are worth at a glance. In particular, seed values are really annoying due to how similar the seeds look.

The "View guide prices" button and Runelite's right click examine feature come close, but I'd really like to see the item prices overlayed on top of the items at all times.

**Describe the solution you'd like**
Something like this would be fantastic:

![image](https://user-images.githubusercontent.com/5246872/57205213-f9492080-6f8a-11e9-8525-f7ee6324e55d.png)

Since it adds clutter, it would probably be best to have it toggled off by default.

**Comment by Alexsuperfly** [comment]
item prices plugin already lets you hover over them to get this info

**Comment by Pikamander2** [comment]
Right, that's a third way to see them. But it would be really nice to have the option to show them at all times. Inspecting every item individually is tedious, especially when you're doing something like pickpocketing Master Farmers.

**Comment by Nightfirecat** [comment]
The item identification plugin already will display seed/sapling names, so that should address the seed issue you mentioned. Generally, I don't see a use for displaying item values at all times.

**Comment by Pikamander2** [comment]
The idea is to be able to discern the value of your inventory items at a quick glance.

If I'm using a cannon or something and my inventory's getting full, then I don't care about the item names; I just want to quickly drop a low value item.

**Comment by Pikamander2** [comment]
Just wanted to add that it would also be super useful in your bank. I have over 700 items in the default tab, as do many people. Figuring out what's valuable and what's not would be significantly faster if every item stack had its value overlayed on top of it,

**Comment by deathbeam** [comment]
Item prices plugin is enough, just hover, or examine, or w/e. this is too much clutter, looks horrible and fits like only your use case
