### ISSUE TITLE
Cutscene related glitches during Wanted! Quest

### ISSUE THREAD

**Issue by Vitaleyezation** [runelite/runelite#8768]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The cutscenes during the quest Wanted! were not displaying properly with the GPU plugin enabled. The camera would zoom out extremely far from the subjects of the cutscene. I was also unable to move my camera around, but could later do so in other cutscenes. I'm unsure if I was supposed to have that ability or not.

![2019-05-05_23-28-21](https://user-images.githubusercontent.com/50310504/57205710-5c888200-6f8e-11e9-9803-605202455843.png)

**To Reproduce**
1. Enable the GPU plugin.
 - Issue happened with any combination of settings set within the plugin.

**Expected behavior**
The cutscene should have played as intended. In the screen shot, the camera should have been focused over the market area. 

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.22.1
 - Launcher version: 1.6.0

**Comment by ShaunDreclin** [comment]
90% sure this isn't a runelite issue, I remember reporting it as a bug a long time ago

If you're still on the quest, try the vanilla client and see if the issue is present

**Comment by Alexgopen** [comment]
I did this quest on resizeable mode with the GPU plugin enabled a few days ago and did not have this issue.  Maybe it has to do with how far zoomed out you are before the cutscene begins?

**Comment by Nightfirecat** [comment]
This is much more likely caused by a large outer or inner zoom than by the GPU plugin.

**Comment by Adam-** [comment]
Multiple issues related to this have been fixed since, reopen if still an issue on 1.8.12-SNAPSHOT
