### ISSUE TITLE
Herbiboar !kc

### ISSUE THREAD

**Issue by Nigamus** [runelite/runelite#8771]
So we currently get an herbiboar kc through runelite atm. Why not add that kc to the actual !kc command for herbiboars?

**Comment by Nightfirecat** [comment]
This exists already: `!kc herbi`.

**Comment by Nigamus** [comment]
That command doesn't work. Never has.

**Comment by Kamielvf** [comment]
![image](https://user-images.githubusercontent.com/35824069/57235041-4af0ba00-7022-11e9-8efc-bfd763714f89.png)
Works fine

**Comment by Nigamus** [comment]
Does my client need to be updated or something? I've tried that command since I started doing them and I have like 700 kc

**Comment by Nigamus** [comment]
!kc herbi                doesn't register as a command.. and yes I have done herbiboars with runelite. It literally shows my kill count after I harvest, but can't use the command. I'm not the only one with the issue

**Comment by Nigamus** [comment]
> ![image](https://user-images.githubusercontent.com/35824069/57235041-4af0ba00-7022-11e9-8efc-bfd763714f89.png)
> Works fine

Is that after typing in the !kc herbi command? You cropped it so I can't tell if that's just after a harvest or the actual command.

**Comment by raiyni** [comment]
Yes.

**Comment by Kamielvf** [comment]
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/chatcommands/ChatCommandsPlugin.java#L1114

**Comment by Nigamus** [comment]
I've checked all logs and actively gathered from herbiboars. What am I missing that would stop the command from working?

**Comment by Nigamus** [comment]
So is there just not a fix for this?

**Comment by Loupak420** [comment]
command works fine now, but KC doesn't update when it has been changed from playing on another account. Going to the herbi spawner and right clicking "check count" does NOT update the kc for the current account. Please fix, in a similar way as checking ring of wealth fixes the kc across different accounts

**Comment by VecnaJr** [comment]
still doesn't work for me
