### ISSUE TITLE
Add option to change align of player names above heads

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#878]
As requested on Discord, some people prefer to have it on right side of player in cluttered areas.

**Comment by Kamielvf** [comment]
Possibly also draw it on the center of their model, since osb uses that some people might prefer it.

**Comment by CaraPis** [comment]
Yea center would be very nice actually

**Comment by deathbeam** [comment]
Something like enum with few values as option would be easy to add, I guess

**Comment by Nightfirecat** [comment]
What positions would people want to see?

* Centered above head
* Centered on model
* Right side of player (Right side of their model? Aligned right above their head?)
* ???

**Comment by deathbeam** [comment]
I think just the ones you listed
