### ISSUE TITLE
Same issue as always, 0% crash

### ISSUE THREAD

**Issue by ultratronger** [runelite/runelite#8781]
I've had this three times already, the previous two times it just went away by itself, I have the latest runelite version, the latest java version, tried reinstalling both like 10+ times and restarting my computer.
I've seen some stuff from the troubleshooting page, mainly SSLHandshakeException and SSLException on the log but I don't understand the "fix" that's there and it's related to ubuntu which I don't use, I have windows 10

[launcher.log](https://github.com/runelite/runelite/files/3154512/launcher.log)

**Comment by xDemoN** [comment]
Try [this](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration)

**Comment by ultratronger** [comment]
> Try [this](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration)

now it doesn't crash, but it stays at 0% forever

**Comment by Nightfirecat** [comment]
I strongly recommend seeking support on our Discord's `#support` channel as that will give a much quicker and easier feedback loop to get information on this issue, especially since you have had this issue multiple times in the past.

**Comment by osrs-music-map** [comment]
try this

mvn clean install -DskipTests && java -jar runelite-client/target/*shaded*.jar

**Comment by abextm** [comment]
@osrs-music-map He's using the launcher, not building the client himself. That would not work for him, or help him.

**Comment by ultratronger** [comment]
Ok, for everyone with a similar issue, what I would recommend is to go to this website: https://static.runelite.net/bootstrap.json , click on the little lock on the top, go to certificate then certificate path and this should show up

Sectigo (formerly Comodo CA) ECC > 
       COMODO ECC Doman Validation Secure Server CA 2 > 
                 sni27007.cloudflaressl.com



if that's any different, you have some kind of malware, and should run a virus check and removal, that worked as a charm
