### ISSUE TITLE
Ground markers behaving strangely in Meiyerditch

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#8796]
**Screenshots**
![screenshot](https://i.imgur.com/vVqlSZN.gif)

**Environment**
 - OS: Windows 10
 - RuneLite version: 1.5.23-SNAPSHOT

**Comment by abextm** [comment]
I don't see anything wrong here?

**Comment by ShaunDreclin** [comment]
The markers aren't appearing where you click to place them

**Comment by abextm** [comment]
Its appearing above the (invisible) tile you clicked on, presumably where the top of the tile is

**Comment by ShaunDreclin** [comment]
Ahh, I see. It makes it hard to remove markers if you place one by accident, since clicking where the marker appears just adds another marker
