### ISSUE TITLE
p hotkey toggles report button display values and doesn't type p in chat

### ISSUE THREAD

**Issue by davidmoed** [runelite/runelite#8801]
**Describe the bug**
When the 'p' key is pressed it is hotkeyed to the report button (whether the report button plugin is on or off). This does not happen when 'p' + 'shift' is pressed and flashes when 'p' is held (probably is related to keydown)

**To Reproduce**
1. Press the 'p' key

**Expected behavior**
a 'p' will be typed in the chat

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS High Sierra
 - RuneLite version: 1.5.22.1
 - Launcher version: 1.6.1

**Additional context**

**Comment by Hydrox6** [comment]
If it's quickly showing the date on the report button, you have your Screenshot key bound to P

**Comment by davidmoed** [comment]
@Hydrox6 you're a life saver :)
