### ISSUE TITLE
Player Indicators to change based on CB lvl in Wildy

### ISSUE THREAD

**Issue by clovermatt** [runelite/runelite#8802]
A potential solution and assistant in the wildy to change player indicators based on CB lvl and if they are attackable. 

If there was an option for player indicators to change to a specific colour if that other player is able to attack you depending on the lvl of wildy you are standing in.

**Comment by Hydrox6** [comment]
[Rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features)
