### ISSUE TITLE
GE Price on tag tabs

### ISSUE THREAD

**Issue by folraferob** [runelite/runelite#8804]
It's frustrating how every bank tab has a ge price but the tag tabs that we make don't. 
Like I would like to see an aprox ge price of my monster drops.

Maybe instead of the tag tab titled showing items xyz, have it changed to either changed to the format of regular tabs or append the estimated ge price at the end like so "showing items xyz (xxxm).
It would be greatly appreciated. Thank you.

**Comment by deathbeam** [comment]
This is intentional, because tag tabs are search, and the title needs to display the searched value, and price will simply not fit there
