### ISSUE TITLE
Western Diary incorrect requirement

### ISSUE THREAD

**Issue by Hacksaw140** [runelite/runelite#8806]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Incorrect diary requirement for Western provinces elite.

**To Reproduce**
1. Go to 'Achievement Diary Tab'
2. Click on 'Western Provinces'
3. Scroll down to 'Elite section'
4. The task, 'Pickpocket an Elf (85 Thieving, Mourning's Ends Part II' is incorrect in the fact that you only need 85 Thieving and Access to Lletya, requiring the start of Mourning's Ends Part I.

**Expected behavior**
The task should state 'Pickpocket an Elf (85 Thieving, Started Mourning's Ends Part I'

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 Home, 64 bit.
 - RuneLite version: [1.5.22.1]
 - Launcher version: [1.6.0]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Hydrox6** [comment]
What requirement is this?

**Comment by Nightfirecat** [comment]
It's the Mournings End Part II completion requirement of the "Pickpocket an Elf." step; it should instead be a requirement to have started Mournings End Part I.

**Comment by Hydrox6** [comment]
oh, I didn't see the extra info that had been added, my bad
