### ISSUE TITLE
Drop All context menu option

### ISSUE THREAD

**Issue by Marlzey** [runelite/runelite#8807]
I have an issue with my hands where excessive use of them in a short time span causes me pain, this is noticeable when grinding out skills rapidly, mining ore and fishing in particular, as if you want to power-level you must drop the fish/ore. currently to drop a full inventory this requires 56 clicks. 

a setting you can enable that enables a new option in the right click menu, which when pressed drops all identical items. i.e all iron ore gets dropped, all salmon etc. an extra setting to specify which items you want this to appear under would be preferable. 

i'm aware shift clicking exists, however best case scenario this only halves the clicks required at 28. moreover i do not have a keyboard as i play on a tablet, and while i have bound shift to one of my mouses buttons, its rather uncomfortable, which still contributes to pain.

i'm also aware that instant dropping of all items may not be kosher, but i'm not asking for instant drop, only that it drops all of it on its own.

**Comment by Nightfirecat** [comment]
Such a feature would be considered botting, so we cannot add that.
