### ISSUE TITLE
Item and NPC loot table search query

### ISSUE THREAD

**Issue by ThimbleFire** [runelite/runelite#8809]
I'd like to propose there be a plugin that lets users search for NPCs and their loot tables, and Items and the various NPCs that drop the item.
I've made a little design of how I'd see it looking.
This information is already available on the wiki so it's not overly necessary to have a plugin, but Runelite has always been about its niceties and I think it would be an excellent feature.

![NPC Search](https://i.imgur.com/pVEfnvF.png)

![Item Search](https://i.imgur.com/P78SvRt.png)

![Item Search Example](https://i.imgur.com/2JVodcn.png)

**Comment by Trevor159** [comment]
Cool in practice, but would require us to store every drop table of every monster somewhere. Your better off just using the wiki button in the client as the wiki has this information.

**Comment by ThimbleFire** [comment]
> Cool in practice, but would require us to store every drop table of every monster somewhere. Your better off just using the wiki button in the client as the wiki has this information.

I thought there might be a public database or something floating around that's regularly updated, like the one the wiki uses.

**Comment by Trevor159** [comment]
> > Cool in practice, but would require us to store every drop table of every monster somewhere. Your better off just using the wiki button in the client as the wiki has this information.
> 
> I thought there might be a public database or something floating around that's regularly updated, like the one the wiki uses.

Nope, the wiki gathers data themselves or guesses. They are not even that accurate on rates for most things. We have given them some anon info but they have to process it.

**Comment by ddaltonzkd** [comment]
I could work on building a database to store the drop tables for each npc in mySQL

**Comment by Trevor159** [comment]
> I could work on building a database to store the drop tables for each npc in mySQL
There is approx a 0% chance that something that makes it into the main client would send data to your server.

**Comment by deathbeam** [comment]
We already have wiki search what already perfectly covers this. We do not need to have every single tiny thing built into client, nor reimplement what wiki people are doing.
