### ISSUE TITLE
Impling loot tracker (loot tracker update)

### ISSUE THREAD

**Issue by zimknot** [runelite/runelite#8810]
I believe it'd be convenient to have the  loot from impling jars being tracked similarly to how clues and drops are tracked in the current loot tracker, please and thank you

**Comment by Hydrox6** [comment]
This would be better handled in a Resource Tracker, as requested in #4126

**Comment by Adam-** [comment]
Have reconsidered this to be more loot than resources, added in 08359a0df0f31bfeac49d286395c4d0dbcaaadfc
