### ISSUE TITLE
Managing Miscellania workers bug

### ISSUE THREAD

**Issue by blahblah2345224** [runelite/runelite#8812]
On runelite I can't allocate all of my workers. My hypothesis is it thinks I've done Royal trouble and so the max amount of workers in a given resource is 67% of my total workers. I haven't done Royal trouble and so it is leaving workers idle unless I login on the OSRS Jagex client where the issue becomes apparent as I can see the workers I had idle and couldn't tell on the Runelite client

**Comment by Nightfirecat** [comment]
Is this still an issue? We don't touch anything regarding Miscellania which should affect what you're seeing in the client/able to allocate regarding workers.

**Comment by blahblah2345224** [comment]
No Thanks it was a user error,

You need the 2nd quest unlocked the extra workers but also it makes your old workers more efficient So you start to make a profit only then, which is where I was confused.
