### ISSUE TITLE
Unable to download setup/Unable to delete setup

### ISSUE THREAD

**Issue by doom777** [runelite/runelite#8824]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I am having trouble installing the client. When I download the Win64 setup using the Brave browser, it downloads the file until 0 left, but then doesn't complete the download. The, I cannot delete the downloaded file in any way, except marking as 'delete on reboot' and rebooting. Every other way to delete the file crashes.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

This really feels like a security bug, could the setup executable be poisoned?

**Comment by Adam-** [comment]
This isn't a security bug. The executable is fine and hasn't changed for ~10 months.

**Comment by doom777** [comment]
Look, can you just download it from the site and verify the checksum, or even wipe runelite from windows and download and install fresh from the site?

I just tried again with Edge, and same problem. It's been "Checking file with antivirus" for half an hour with no end in sight.

**Comment by doom777** [comment]
tried again with 32bit and jar versions. Same problem
