### ISSUE TITLE
Document `WallObject`'s Orientation Parameters

### ISSUE THREAD

**Issue by MichaelMitchellM** [runelite/runelite#8825]
**Is your feature request related to a problem? Please describe.**
It is very hard to interpret the `int` result from `GetOrientationA` and `GetOrientationB` does not seem to return anything other than `0`.

**Describe the solution you'd like**
I would like some documentation on these functions to describe the meaning of their return values. If the output can be described by an enum I would like that as well.

Thank you!

**Comment by abextm** [comment]
The docs are wrong on these methods. They are in the range 0 through 8 (see BlastMineRockOverlay). OrientationA is for renderableA, OrientationB is for renderableB, which is only set when there are 2 walls on one tile, and is zero if there isn't a second renderable.
