### ISSUE TITLE
Item Red d'hide vamb hover dont show + stats

### ISSUE THREAD

**Issue by Nopzen** [runelite/runelite#8826]
**Describe the bug**
When looking at the inventory and hovering the red d'hide vamb in the inventory.

**To Reproduce**
1. Have a Combat bracelet & a red d'hide vamb in inventory
2. Equip red d'hide vamb, hover combat bracelet (shows stats)
3. Equip Combat Bracelet, hover vamb (No stats are shown just name plate)

**Expected behavior**
I expect to to see + stats to compare whit the one i currently use, see the two screenshots

**Screenshots**
<img width="1954" alt="Skærmbillede 2019-05-13 kl  07 37 13" src="https://user-images.githubusercontent.com/2326591/57598077-131dd100-7552-11e9-80d5-731892b004dd.png">

<img width="1954" alt="Skærmbillede 2019-05-13 kl  07 37 22" src="https://user-images.githubusercontent.com/2326591/57598086-1add7580-7552-11e9-90ab-60ea0fcaf731.png">

**Environment (please complete the following information):**
 - OS: macOS
 - RuneLite version: [e.g 1.6.2]
 - Launcher version: [e.g 1.6.2]

**Additional context**
Nothing else to add

**Comment by testerm0nkey** [comment]
Its actually missing a ton of equipment stats especially lesser used items as I'm a pure I see it all the time.

**Comment by xDemoN** [comment]
Similar to #8489

I remember having some conversation with @deathbeam or @TheStonedTurtle about parsing issues when pulling item stats from the wiki(?)

**Comment by Nopzen** [comment]
@xDemoN I just read the similar and checked it on all my red d'hide item:

Body, Champs, Vambs, Shield non of them reports stats. So yes it would say its similar.

**Comment by wrightmalone** [comment]
I think it might be the apostrophe that's causing issues. For instance, I get no stats on seer's ring, ava's assembler, bandos range gear (d'hide in name). There are other examples if required.

**Comment by xDemoN** [comment]
It is the apostrophe, that's what I mean't with the parsing issue

**Comment by Nopzen** [comment]
xDemoN is that becuse the runelite parser cant parse apostrophe when
fetching data from wiki or how is it fetched?


søn. 19. maj 2019 kl. 21.55 skrev xDemoN <notifications@github.com>:

**Comment by xDemoN** [comment]
Not entirely sure, take a look at [this repo](https://github.com/deathbeam/osrs-data) or talk to @deathbeam

**Comment by Nopzen** [comment]
@xDemoN Im sadly no java developer otherwise i would have tried to fix this. And i dont think this project need a elephant in a glass shop :D So any other way i can help the project i would be happy to :p
