### ISSUE TITLE
Ability to send messages to clan chat without using '/' character

### ISSUE THREAD

**Issue by hjdarnel** [runelite/runelite#8835]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to chat without typing "/" first. 

**Describe the solution you'd like**
When I'm on the Clan tab, or alternatively when enabled, my messages go to my clan chat without me having to type / first.

**Describe alternatives you've considered**
Maybe it could type / for me before I type, if it's a Jagex client requirement?

**Comment by abextm** [comment]
Duplicate #8264
