### ISSUE TITLE
Emoji plugin disregards chat recolor

### ISSUE THREAD

**Issue by Thource** [runelite/runelite#8842]
**Describe the bug**
When typing emojis in clan chat, the colour of the message gets reset, I've got my clan chat colour set to blue but it gets reset if someone uses an emoji in a message

**To Reproduce**
1. Enable emoji plugin
2. Edit chat color plugin and change clan chat colour
3. Type some words in clan chat
4. Type some words followed by an emoji in clan chat

**Expected behavior**
Both lines of text should be the colour you chose

**Screenshots**
https://i.imgur.com/KUOEVJX.png

**Comment by devLotto** [comment]
1. It's supposed to use the value from the message node, not the ChatMessage's message.
2. Colored chat strings are formatted like this ``<col=3556e5>Test :)</col>``, and the plugin splits by whitespace, so the strings it will check are ``<col=3556e5>Test`` and ``:)</col>``, not ``Test`` and ``:)``.

**Comment by Adam-** [comment]
Fixed in 879e7f6b5df0183b6ccd617c5bfbc5ae6ccce461
