### ISSUE TITLE
Alternative ignore list

### ISSUE THREAD

**Issue by mattd96** [runelite/runelite#8846]
Current in-game ignore list is tedious to fill/maintain with usernames from runewatch/runejustice and is limited to 400 entries.

Suggestion:
A plug-in that could take comma delimited lists of player names similar to how ground item highlighting works. If a player on the list is near you, their name would appear above their head in red similar to a friend you have added 

This would make avoiding scammers while raiding an easier process.

**Comment by Hydrox6** [comment]
This would come under Generic Player highlighting, which is [Rejected](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features) as it would be incredibly strong for PKing. Sorry
