### ISSUE TITLE
Attack options removed on attack style 

### ISSUE THREAD

**Issue by 07RS** [runelite/runelite#8849]
Would it be possible to have the attack option on players and npc's removed if a weapon I equip has a certain attack style? For example, if don't want to gain defence xp and I equip a weapon that has every attack style as shared, such as the magic butterfly net, then i would be unable to left click attack. Thanks

**Comment by ajbinky** [comment]
I believe this was on the list of things that were either removed or won't be implemented.

[Conditional menu entry removing](https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping)

**Comment by Nightfirecat** [comment]
For what it's worth, I don't feel this would be conditional in the same way other similar menu swaps/removals are, since it would apply to all NPCs.

Also for any curious, this was implemented in a now-closed--but I believe still functional--PR: #5951

**Comment by abextm** [comment]
Jagex's [recent statement](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1) prohibits `Reorders or removes player-based options, such as ‘Trade with’`, which this falls under.
