### ISSUE TITLE
Cannon overlay remains when cannon fully degrades off-screen

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#8855]
It leaves behind the current ammo number where the cannon was. This could easily be fixed by clearing the cannon location when the message that your cannon has been destroyed comes up, which looks like
![Screenshot_2019-05-17_00-24-31](https://user-images.githubusercontent.com/2979691/57893261-2ecaf500-783a-11e9-8430-e1f2da41e022.png)

**To Reproduce**
1. Set up a cannon, get the text showing how many cannonballs are loaded
2. Move so the cannon is out of the scene
3. Wait 25 minutes for it to degrade
4. Wait a further 10 minutes for it to get destroyed
5. Go back to the cannon and notice the number is floating there

![0](https://user-images.githubusercontent.com/2979691/57893682-c1b85f00-783b-11e9-85c1-ac340ffc802c.png)

**Comment by gregg1494** [comment]
I tried this twice and couldn't get a message to appear, weird. I had a fix I was trying out. I just set cannonPoint to null when the message appeared in chat. I'll have to try it again tomorrow if no one fixes it.
