### ISSUE TITLE
Add "Ring of Forging" to the "Item Charges" plugin

### ISSUE THREAD

**Issue by iRoxor** [runelite/runelite#8865]
**Is your feature request related to a problem? Please describe.**
Currently, Runelite's Item Charges plugin does not have any tracking features for the Ring of Forging. This item currently sees more use recently due to being introduced to Free-to-Play players.

**Describe the solution you'd like**
The Item Charges plugin can be updated to add useful "charge count" features similar to that of the "Dodgy Necklace" tracked features.

**Describe alternatives you've considered**
A notification (and/or audible warning) could be added for when Runelite sees the message "Your Ring of Forging has melted." in the chatbox.

**Comment by zachtyll** [comment]
I tried, but for some reason I can not get it to work properly. When adding in tests Mockito gives me a [strange error](https://pastebin.pl/view/27b1d092) when attempting to use `verify `. [Link to repo for anyone who wishes to figure this one out](https://github.com/zachtyll/runelite/tree/c0b13c97d579ff1a3a0f9e4d43bbce275126e7a2).

**Comment by Adam-** [comment]
That just means `config.ringOfForging(-1);` was not invoked and your test expects it to be.

**Comment by zachtyll** [comment]
Then I have probably missunderstood how it gets invoked. The dodgy necklace passes the tests without trouble but my code is written using that code as a template. Do you know where the dodgy necklace is invoked?

**Comment by Adam-** [comment]
Probably in `updateDodgyNecklaceCharges`. If you think that yours should be hit and it isn't, run the test in a debugger.

**Comment by zachtyll** [comment]
Thank you for your help! The pattern matcher was incorrect and did not match the if-statements. The test now passes successfully. I will continue the work!
