### ISSUE TITLE
Degradable items disappear from bank tags.

### ISSUE THREAD

**Issue by Glynnyx** [runelite/runelite#8866]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
1. Go to Runescape Bank
2. Create a bank tab with a degradable items. 
3. Use the item until it degrades some more
4. Put the item back in the bank and remove it and it disappears. Gif below:

**Expected behavior**
I would expect the armor to not disappear when removed. 

**Screenshots**
https://i.imgur.com/eUtJkHw.gifv

**Environment (please complete the following information):**
 - OS: Windows
- Latest as of 18/05/2019

**Additional context**
As far as I can see, this issue has been raised and was previous fixed.  Multiple tickets have been created labelling them as duplicate to an old fix that no longer works.

**Comment by abextm** [comment]
You need to use a [variation tag](https://github.com/runelite/runelite/wiki/Bank-Tags#setting-tags)

> You can tag and un-tag all variations of an item, e.g. all dosages of a particular type of potion, all charges of an Amulet of Glory, or all degraded states of a Barrows equipment piece or piece of crystal equipment, etc. To do so, drag the item onto a tag tab while holding Shift, or add "*" to the end of the tag.
