### ISSUE TITLE
Highlight ground items

### ISSUE THREAD

**Issue by Popedigoz** [runelite/runelite#8876]
Instead of only highlighting ground items with text, have an option to toggle to highlight the whole item in the ground, similar to highlighting objects or NPCs/mobs.

**Comment by shogunreaper** [comment]
you can highlight the tile

**Comment by Popedigoz** [comment]
> 
> 
> you can highlight the tile

I know, but it's not good enough.

**Comment by deathbeam** [comment]
It is

**Comment by Popedigoz** [comment]
> 
> 
> It is

No, it is not... I often misclick a lot on small objects, and the tile or text don't give me the exact position to click onto. Making this is probably easy for you coders and you are ignorant because you don't see the use?

**Comment by shogunreaper** [comment]
the tile would highlight a larger area than just the item itself, so how would doing the latter make it easier to see?

**Comment by Popedigoz** [comment]
> 
> 
> the tile would highlight a larger area than just the item itself, so how would doing the latter make it easier to see?

?? The tile that is highlighed doesn't enlarge the hitboxes of the object, I want outlines for objects
https://www.dropbox.com/s/5thkic6qhwyqdnp/HDxYFRe8lc.mp4?dl=0

**Comment by shogunreaper** [comment]
It shows you exactly what tile an item is on, how do you miss it with that enabled?

**Comment by Alexsuperfly** [comment]
hes looking for the clickbox of the item on the ground

**Comment by Popedigoz** [comment]
> 
> 
> hes looking for the clickbox of the item on the ground

yeah

**Comment by Popedigoz** [comment]
@deathbeam Can you unlock as perhaps you didn't at first get what I meant??
