### ISSUE TITLE
hidden ground items and notifications for value

### ISSUE THREAD

**Issue by shogunreaper** [runelite/runelite#8877]
Would it be possible to make it so if you have an item on the hidden item list and it comes in noted form for it to still notify you if its valuable?

For example, i have uncut rubys on there but i got a drop of 10 noted ones which was worth 15k and that normally would have notified me because of the price but didn't because i had it hidden.

**Comment by deathbeam** [comment]
Just use the highlight > value config in ground items

**Comment by shogunreaper** [comment]
i have that set already, ignored items that are under that amount when non noted don't trigger it when noted.
