### ISSUE TITLE
Wine making timer goes negative

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#8880]
**Describe the bug**
The timer seems to only reset once you finish making wines, rather than when you start. This causes it to go negative when you start making a second inventory of wines before the first one ferments

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/5851433/58103669-5eb72700-7bb1-11e9-88b3-58f6123a6c10.png)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.24-SNAPSHOT

**Comment by abryant2113** [comment]
Took a look at this and submitted a PR with a fix: https://github.com/runelite/runelite/pull/8894

**Comment by ShaunDreclin** [comment]
Fixed in acaef50
