### ISSUE TITLE
Show clan rank next to player's name when right clicked

### ISSUE THREAD

**Issue by TheAngriestPasta** [runelite/runelite#8883]
A plugin that shows clan rank next to a players name when right clicked.

_Edited to only feature per request._

**Comment by oojava** [comment]
I like the idea of clan rank when right clicked, however hiding attack options on clan members seems op to me. 

Predicting the target hp and xp is kinda pointless they could eat in the same tick, and you can just get good and know your xp drops. 
It would be better to have that as kind of  143xp (73) or whatever the values are when you get the xp drop. 

I however think this is unlikely as I'm pretty sure that they're not trying to make plugins that might be seen as op for pvp.

**Comment by TheAngriestPasta** [comment]
The HP prediction would not only be useful for PVP, but PVE aswell. And showing the value of the hit splatter a few seconds early I think wouldn't be too op. As well as a way to distinguish your hit from other players would be nice to include with that as well.

**Comment by Kamielvf** [comment]
Only part I see being put in the client would be `A plugin that shows clan rank next to a players name when right clicked.`.

**Comment by Nightfirecat** [comment]
Please submit one issue per feature request. We can't effectively track and manage them if they are all bundled into a single issue.

**Comment by LlemonDuck** [comment]
I do not have the exact commit for this but the rank image is now shown on the minimenu 
![image](https://user-images.githubusercontent.com/1868974/179174859-f526714d-10b7-42c8-a275-1badc3ba5331.png)
