### ISSUE TITLE
Fishing Spot Missing

### ISSUE THREAD

**Issue by ImTheNewGuy** [runelite/runelite#8888]
Fishing overlays are not present at barbarian fishing spots in Mount Quidamortem.

There are 3 fishing spots just South East of the COX enterance (World location: 1266, 3541, 0).

The three spots have NPC ID's like other fishing spots, but it appears they have not been added to the Runelite plugin. Not sure if this is a bug, oversight or just haven't been added, but I thought I would raise it to the devs attention.

The information I am getting from the NPC ID in the developer tools are:
Fishing spot (ID:7323) (A: -1)(G: -1)

**Screenshots**
https://imgur.com/txCXoU0
https://imgur.com/0N7XsNt

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Unsure. Current version as of 22/5/19
 - Launcher version: Unsure. Current version as of 22/5/19

**Comment by Nova-Static** [comment]
It shows fine you just have to have the barbarian rod in your inventory.

**Comment by Nova-Static** [comment]
https://gyazo.com/a9b8384f776f019cf9c2ff664cb80278

**Comment by ImTheNewGuy** [comment]
im an idiot. Thanks for that.
