### ISSUE TITLE
Suggestion about xp tracker canvas

### ISSUE THREAD

**Issue by Mcaviio** [runelite/runelite#8891]
this is a really good update but i think we should be able to get more out of it .. like we should be able to see the actions left for target lvl (or next lvl) and the amount of xp left til the target lvl (or next lvl) .. just like the one in the xp tracker sidebar
![49cfe107861062efd32e96f99980810e](https://user-images.githubusercontent.com/50927227/58201801-47258e80-7cd6-11e9-9b4a-d265d1bfc372.png)
![34baa0771df08ecf504e59ce804592a6](https://user-images.githubusercontent.com/50927227/58201802-47258e80-7cd6-11e9-8983-f6dfde932fa0.png)

**Comment by deathbeam** [comment]
It do not fits, but you can configure the lines displayed in xp tracker configuration

**Comment by Mcaviio** [comment]
Cant you at least replace xp/hr with actions left?

**Comment by deathbeam** [comment]
Yeah, it was already merged to master, so it will be in next release

**Comment by Mcaviio** [comment]
amazing
