### ISSUE TITLE
Sort Bank by Value

### ISSUE THREAD

**Issue by adrunkllama** [runelite/runelite#8897]
**Is your feature request related to a problem? Please describe.**
Many of us in the Reddit_07 clan chat agree that a "Sort Bank by Item Value" filter would be undeniably helpful. Many times you must sell something of value, be that a weapon or armor, to fund the ingredients of skilling items but searching for these things is hard currently. This feature would organize a bank by value making it much easier to identify what is worth keeping and what is worth selling. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by deathbeam** [comment]
Its not possible to reorder bank.
