### ISSUE TITLE
[Suggestion] Bank Tag Improvements

### ISSUE THREAD

**Issue by Gawz** [runelite/runelite#8898]
To have an the option to remove the text and spacing of "Tab x" where each item is located in imported tag tabs.

As well as ordering the items in the imported tag tabs in the order each item is written in the code.

I'm not sure if it would be possible, but also an option to have blank spaces in between imported items as well, to cater for the OCD.

**Comment by deathbeam** [comment]
We already have issue/pr for 1st one, 2nd one is not how this works, that is just how export behaves, 3rd one do not makes much sense, the export format is not meant for reading.
