### ISSUE TITLE
Xeric's Talisman - Xeric's Glade teleportation icon misplaced

### ISSUE THREAD

**Issue by RRickkert** [runelite/runelite#8899]
**Describe the bug**
After the latest runescape update, the xeric's glade teleport has been moved. The map icon location hasn't been updated yet.

**To Reproduce**
1. Teleport with your Xeric's Talisman to Xeric's Glade.
2. Open your world map and notice that the Xeric's Glade teleport icon is at the wrong location.

**Expected behavior**
The icon should show up in the world map at the location it teleports you to.

**Screenshots**
![image](https://user-images.githubusercontent.com/38819529/58252628-dbd7cd00-7d66-11e9-8d78-06f246f0331c.png)

![image](https://user-images.githubusercontent.com/38819529/58252634-ded2bd80-7d66-11e9-921f-881f3723a3f0.png)

**Comment by forsco** [comment]
https://lambda.sx/tAl.png

**Comment by Cistoran** [comment]
Fixed in #8900
