### ISSUE TITLE
Not a way to set transparency with colors in config

### ISSUE THREAD

**Issue by sethtroll** [runelite/runelite#890]
Currently there is not a way to set the transparency of a color when changing colors in the configuration. This seems to be an issue with substance not having the transparency slider. We also do not store alpha values in config which would also need changing.

**Comment by deathbeam** [comment]
Based on this reply https://github.com/kirill-grouchnikov/substance/issues/84 we need to build Substance without it's custom color picker. Looks like profile for building it without is here: https://github.com/kirill-grouchnikov/substance/blob/master/build.xml#L127 . Maybe @Adam- can deploy substance without classes mentioned there?
