### ISSUE TITLE
Notification Types

### ISSUE THREAD

**Issue by altonslayer** [runelite/runelite#8908]
I was curious if there was any way to have multiple idling notification types in Runelite.

For instance, If I'm at Motherlode Mine, and my node runes out, notification 1, but if instead I stop mining because my inventory was full. That would be a different notification.
I understand Runelite Uses the default windows notification sound, and I have no idea if a program can run different sounds through the notification system. But regardless there is the screen flash option in the general Runelite settings. Perhaps it could flash different colours for different things. Such as red for idle, light blue for prayer, purple with polka dots for inventory full or what have you. 
I've seen a few other posts relating to notifications, and generally the system seems pretty fairplay to make QOL changes to, but either way.
Not sure if doable or if other people would b interested but it would make my experience with playing while watching videos or otherwise not fully attentive easier if before I looked I knew what I was going to do. Whether that was click a bank, ore node, prayer pot, or whatever.

**Comment by deathbeam** [comment]
We already have issue open for custom notifications that would allow us to use different sounds, but I dont think we will be implementing per-action sounds or different notifications.
