### ISSUE TITLE
Telekinetic Grab in Right click menu

### ISSUE THREAD

**Issue by Neriek** [runelite/runelite#8923]
Pretty self-explanatory, I have no idea if it'd be considered "too cheaty" or not but I've been wanting to have Telekinetic Grab appear in the right click menu whenever I right click on an item.
I was looking into doing it myself but I simply couldn't find enough documentation or information on how the MenuEntry system works.

![java_2019-05-25_23-23-51](https://user-images.githubusercontent.com/10354342/58369947-d801a180-7f44-11e9-96d2-158d7badf9f4.png)

**Comment by Unmoon** [comment]
This would require faking actions (i.e client playing for you), which is extremely likely to trigger bans.

**Comment by Neriek** [comment]
I see, that's really unfortunate. All I wanted to do was be a little extra lazy xD
