### ISSUE TITLE
GPU Rendering For Stretched Mode

### ISSUE THREAD

**Issue by MarkusWallace3rd** [runelite/runelite#8926]
**Is your feature request related to a problem? Please describe.**
Yes/No. The issue I have is, I like to use stretched fixed mode, but it's too blurry.

**Describe the solution you'd like**
I'd like to have the GPU Plugin work with the interfaces, chatbox, objects, outlines, map, etc.. That way the anti-anti-aliasing can smooth things out while using stretched mode.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by abextm** [comment]
Duplicate  #5781
