### ISSUE TITLE
Blue to Black

### ISSUE THREAD

**Issue by lucastimothy** [runelite/runelite#8928]
Option configurable in skybox plugin to keep all of the custom skybox colours (eg. blue for Zanaris, grey for Draynor Manor, etc.) except change the default blue to the original black.

Eg. Lumbridge, Falador, Varrock all have original black skybox but still transitions to the other colours.

TL;DR replace the default blinding blue with black option in Skybox.

**Comment by deathbeam** [comment]
The skybox colour is intentionally not configurable, and this request is super niche.
