### ISSUE TITLE
Have Grand Exchange results link to ge-tracker

### ISSUE THREAD

**Issue by RickertdeH** [runelite/runelite#8931]
Currently the grand exchange results link to the official OSRS website with more price history, etc.

It would be great to have an option to go directly to the GE-Tracker page for the item.

**Comment by Nightfirecat** [comment]
What is GE-Tracker, and why should we link to it? Generally speaking, we don't interface with third party websites without good reason.

**Comment by RickertdeH** [comment]
GE-Tracker.com is a website that provides a lot more historical trade information for the grand exchange.

It provides a lot more accurate selling and buying prices than the actual GE does.

**Comment by deathbeam** [comment]
We do not want to interface with 3rd party services very much, and GE tracker is basically OSB prices what we already have.
