### ISSUE TITLE
npc icons for bank tags

### ISSUE THREAD

**Issue by shogunreaper** [runelite/runelite#8936]
Can we have the option to use the npc icons that are shown for slayer tasks for bank tag icons?

I'd like to be able to do tags for each slayer assignment.

**Comment by Kamielvf** [comment]
You can do this but you will have to export a tag, change the first ID which resembles the icon of the tab to one of the task ones ([you can grab from here](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/slayer/Task.java)) and then import the tag again.

**Comment by shogunreaper** [comment]
i'll go ahead and do that thanks, would be nice to be able to do it through the client like regular tags though.

**Comment by raiyni** [comment]
duplicate https://github.com/runelite/runelite/issues/6021
