### ISSUE TITLE
Client freezing

### ISSUE THREAD

**Issue by jgpeace92** [runelite/runelite#8942]
**Describe the bug**
Every 15 seconds or so the client freezes for anywhere between 2 and 6 seconds.

**To Reproduce**
Starts when client opens

**Expected behavior**
Smooth gameplay

**Environment (please complete the following information):**
 - OS: MacOS Mojave 10.14.5
 - RuneLite version: 1.5.24.1
 - Launcher version: 1.6.2

**Comment by Nightfirecat** [comment]
Try updating your launcher by downloading RuneLite from our website again. As of version 2.0.0, the launcher is built with Java 11 which uses a different garbage collection system that will likely fix this issue.
