### ISSUE TITLE
NPC aggression timer does not save on logout 

### ISSUE THREAD

**Issue by Trevor159** [runelite/runelite#8945]
It looks like the plugin tries to save the two center locations, the last player location, and the timer on player log out. It was reported that this doesn't happen.

reported by Boo#2221 in discord

**Comment by Nightfirecat** [comment]
I haven't seen this be an issue recently. Has anyone else experienced this?

**Comment by Trevor159** [comment]
I am going to assume this was somehow user error or a one off thing as no one has experienced this since this issue was opened and the user was not very tech savvy.
