### ISSUE TITLE
Barrows Loot Tracker 

### ISSUE THREAD

**Issue by Orest-Cokan** [runelite/runelite#8948]
**Describe the bug**
The loot tracker doesn't drop the gold drop from the chests.

**To Reproduce**

1. Perform a barrows run
2. Click on the chest
3. Receive gold coins and various runes from the chest
4. Open loot tracker tab to see goodies received 

**Expected behavior**
The loot tracker should show the coins received from the barrows chest, but it only shows the runes. 

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.17

**Comment by OzairP** [comment]
I'm pretty sure it tracks it, are you sure you didn't ignore coin drops? You can check by opening the settings for Loot Tracker.
