### ISSUE TITLE
Slayer plugin does not account for bracelet of slaughter activations

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#8956]
Reported by 𝒜𝓈𝑔𝒶𝓇𝒹 🍻#5894 in Discord.

The plugin does correctly account for expeditious bracelet triggers, but not slaughter bracelet triggers.

**Comment by Alexsuperfly** [comment]
unable to reproduce, both bracelets seem to work correctly when tracking remaining task count.  I assume the original individual was bursting and failed to test adequately.

**Comment by Nightfirecat** [comment]
Given that they are not on github, I am closing this issue. We can re-open if someone can reproduce this.
