### ISSUE TITLE
Numulite Buy Limit is Incorrect

### ISSUE THREAD

**Issue by jmynes** [runelite/runelite#8960]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Set up a buy offer for Numulite in the GE

**To Reproduce**
1. Set up a buy offer for Numulite in the GE
2. Observe a buy limit of 18,000

**Expected behavior**
1. Observe a buy limit of 30,000 (at least according to the wiki)

**Screenshots**
Self-explanatory enough, really.

**Environment (please complete the following information):**
 - OS: Debian
 - RuneLite version: Most up to date
 - Launcher version: Most up to date

**Comment by Hydrox6** [comment]
Source:
The Seed Vault update on the 28th of March raised the buy limit
