### ISSUE TITLE
Barrows and Void Set addons

### ISSUE THREAD

**Issue by jb896** [runelite/runelite#8964]
an indicator if youre not wearing the full barrows set. if you had ahrims hood on with full dharoks. the dharoks helm would be highlighted with red

**Comment by Nightfirecat** [comment]
Please add a comment or edit your post to describe your issue. The title as-is does not explain what you are requesting.

**Comment by jb896** [comment]
an indicator if youre not wearing the full barrows set. if you had ahrims hood on with full dharoks. the dharoks helm would be highlighted with red

**Comment by jb896** [comment]
a suggestion. same idea with void, if youre ranging and switching with mage and mess up on your switches. it indicates you in red that ur missing an item.

**Comment by Nightfirecat** [comment]
In my opinion this is already adequately fulfilled by the [Inventory Tags plugin](https://github.com/runelite/runelite/wiki/Inventory-Tags)

**Comment by jb896** [comment]
That works too. Thanks alot
