### ISSUE TITLE
Highscore - Own Stats Default

### ISSUE THREAD

**Issue by mikexsouth** [runelite/runelite#8968]
Hiscores Suggestion:
It would be very useful, and possibly a simple fix, to be able to revert Hiscores to default your own stats.  Via:
- A double click of the Search bar?
- A right click of search bar > My stats?

Benefits:
- People could quickly+simply look up their own stats that were official prior to log-in to compare with realtime xp.
- People could quickly 'pin' their stats to the side whilst working in other ingame interfaces.

Thanks.
Mikey.

**Comment by Twiglet1022** [comment]
It’s a bit obscure but double click the magnifying glass in the search bar and it will look up your own character.
