### ISSUE TITLE
Music List Plugin - Filter/search context menu constantly expands

### ISSUE THREAD

**Issue by asherbasher** [runelite/runelite#8971]
**Describe the bug**
The right-click context menu of both the filter and search buttons on the music list will continue to add more and more of the same option. I believe it's each time a different track is automatically played each session. Please see my screenshot as it's much easier to explain in image format.

**To Reproduce**
1. Go to the music tab after having your music on auto and having been in a few different areas which would've played different songs
2. Right-click either the filter or search buttons

**Expected behavior**
The menu should not be adding duplicates of the "Toggle" or "Open Search" context entries.

**Screenshots**
![Context menu bug](https://user-images.githubusercontent.com/10160470/58712545-ad866d00-83b8-11e9-821b-75deb0fff857.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.25
 - Launcher version: 1.6.0

**Comment by andmcadams** [comment]
It looks like this happens when teleporting places. When I tried walking around to areas with different music, no new menu items were added.

**Environment (please complete the following information):**

- OS: Linux Mint 19 (Tara)
- RuneLite version: 1.5.25
- Launcher version: 1.6.2

**Comment by Adam-** [comment]
Looks like this does only happen when teleporting places. Also I got it to happen to the quest list search thing too but it doesn't happen as reliably as it does with the music one for some reason.

**Comment by andmcadams** [comment]
Yeah, it looks like there are assumptions that these buttons will only be created once. I've been looking at the quest one for a while now. On startup, it actually generates two of each button, but since they overlay each other, you can't tell the second button is underneath unless you right click.

**Comment by Adam-** [comment]
fixed in c020717346f32ffa1695ad7aa412f32b6b01606f
