### ISSUE TITLE
Dragon hasta(kp) marked as tradable

### ISSUE THREAD

**Issue by EvanCosper** [runelite/runelite#8980]
**Describe the bug**
The dragon hasta(kp) has a GE value, while it is not tradable.

**To Reproduce**
1. Go to Grand Exchange plugin in RuneLite
2. Search for "Dragon Hasta(kp)"

**Expected behavior**
The dragon hasta(kp) should be marked as untradable

**Screenshots**
https://imgur.com/Gn3ijS1

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.25
 - Launcher version: 1.6.0

**Additional context**
It also effects bank value.

**Comment by omegabiscuit** [comment]
I can take care of this

**Comment by Adam-** [comment]
The prices are stored server-side in the database and we don't have a way to actually remove things from it. What happened with the hasta was when it was first introduced it had a GE value and so we stored that. I think the only way to fix it is I have to go into the database and manually delete it.

**Comment by Adam-** [comment]
```
> delete from prices where item = 22743;
Query OK, 193 rows affected (0.00 sec)
```
