### ISSUE TITLE
Activating some sidebar panels takes keyboard focus away from game applet

### ISSUE THREAD

**Issue by scuttlegun** [runelite/runelite#8989]
When activating some panels (configuration and hiscores that I've noticed, including using the hiscores lookup function ingame--maybe anything with a text input field?) it'll take keyboard focus away from the game, so fkeys and arrow keys won't work until you click back inside the rs applet which is kind of annoying. Typing while the focus is lost to the panel doesn't even seem to do anything so this seems unintended

**Comment by Nightfirecat** [comment]
At least for the hiscores panel, this is likely intentional since most players will want to type to search for a player when opening it.

**Comment by deathbeam** [comment]
Text input fields taking focus is intentional, for Hiscore and Config panels, but if you can't start typing right away to input to text fields there, it sounds like a bug.

**Comment by abextm** [comment]
Fixed in 46b56797418264b0b8427e7b5baed2f3976d17eb
