### ISSUE TITLE
Wiki Search-> Flambeed (hard) NZM opens Gelatinnoth Mother (hard) web page

### ISSUE THREAD

**Issue by ThimbleFire** [runelite/runelite#8994]
**Describe the bug**
In NMZ when using the Wiki search function on Flambeed (hard) while in NZM, the wiki page that opens is instead Gelatinnoth Mother (hard).

**To Reproduce**
1. Enter nightmare zone (I was in Rumble hard mode)
2. When Flameed spawns, click the wiki search function, then click Flambeed

**Additional context**
Windows 10, Chrome web browser.

**Comment by Adam-** [comment]
We just perform a search on the wiki with the npc name. I don't think there is anything for us to do here.

**Comment by Twiglet1022** [comment]
The wiki plugin looks up on both name and NPC ID. It looks like if it finds a match on NPC ID then that takes priority over name.

I've corrected the wiki so it should go to the right page now.
