### ISSUE TITLE
i just dont want notifications when i get low str/att

### ISSUE THREAD

**Issue by worldsawayy** [runelite/runelite#8997]
i just dont want notifications when i get low str/att (after sipping pots and they get lowered)

an option to disable it

**Comment by Twiglet1022** [comment]
`Boosts information` > `Boost Amount Threshold` set that to zero

**Comment by Nightfirecat** [comment]
OP is looking for a way to see that information displayed in the overlay as yellow boost numbers, but disable the notification that is currently bundled with them. There's no way currently to have one without the other.
