### ISSUE TITLE
Client sometimes freezes when instance map is opened in Inferno city

### ISSUE THREAD

**Issue by deathbeam** [runelite/runelite#900]
Sometimes, when opening map in Inferno city, client completely freezes, without any logs in console.

**Comment by Kamielvf** [comment]
https://hastebin.com/cufuyoxalo.pl just leaving this here so it won't be lost

**Comment by Adam-** [comment]
Fixed in 0ebcb9cf8e54a37ec0832eac9e639690ea70400d
