### ISSUE TITLE
Head Bang at the Exam Center Clue - Wrong Stash Highlighted

### ISSUE THREAD

**Issue by russel204** [runelite/runelite#9019]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
The clue for the Headbang at the Exam Center Hard clue highlights the easy stash instead of the hard stash.

**Expected behavior**
Hard Stash should be highlighted.

**Screenshots**
https://gyazo.com/6c7dfda7e9cf228b06a1f58d94789a21

**Environment (please complete the following information):**
 - OS: Win10 
 - RuneLite version: 1.5.25
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Hydrox6** [comment]
Already fixed in #8963

**Comment by russel204** [comment]
Strange i looked to see if this issue had been raised and didn’t find that one. Thanks!
