### ISSUE TITLE
Client Resizing Issue

### ISSUE THREAD

**Issue by mrmcbreakfast** [runelite/runelite#9031]
I had my computer refurbished and had to reinstall all my programs. When I ran Runelite the game client did not resize to fit my window anymore. Previously I was not running the stretched mode plugin, and the game client would resize leaving the UI at the same scale. Now, the game client stays the same size regardless of window size, and when running the stretched mode plugin it resizes the UI as well and doesn't fill up the entirety of the screen anyway. 
![Capture](https://user-images.githubusercontent.com/51417710/58978082-57367700-8788-11e9-822a-96d701f110a7.PNG)
![Capture2](https://user-images.githubusercontent.com/51417710/58978083-57cf0d80-8788-11e9-9103-d46e1a7e5b29.PNG)

Did I miss something during my re installation?

**Comment by Kamielvf** [comment]
Are you perhaps looking for the resizable mode the game has? It is in the ingame settings.
