### ISSUE TITLE
Feature Request: Ability to enter bank pin via keyboard

### ISSUE THREAD

**Issue by Paradoxis** [runelite/runelite#9033]
**Is your feature request related to a problem? Please describe.**
At the moment, when having to enter bank pins you have to find where each number is as they're randomized. This is generally quite tedious to do and might stop people from setting a bank pin at all (atm takes me around 10 seconds just to enter the pin), with the plugin it could take less than 1 second.

**Describe the solution you'd like**
Would it be possible to create a plugin which disables the chat and redirects all numeric input as clicks on the pin buttons (eg: pressing 1,2,3,4 enters 1,2,3,4 as your bank pin)? All other text would be ignored during this time as you wouldn't be chatting with your friends as clicking bank pins anyways.

**Describe alternatives you've considered**
Alternatively, instead of doing this, it would be possible to press shift and enter the bank pin. This would probably lead to more instances of people accidentally entering their bank pins in the chat window without pressing shift and hitting enter, resulting in their bank pin getting blasted into the chat window.

**Comment by Nightfirecat** [comment]
This feature would be considered botting, as it would require faking clicks. Additionally, it would remove the whole point of having bank PINs presented this way to begin with--that is, the reason bank pin numbers are randomized is so that a keylogger or a click tracker would not enable a malicious actor to get access to your bank even with that information.

**Comment by graingert** [comment]
@Paradoxis @Pooooky this feature came out in runelite 1.6.13 https://runelite.net/blog/show/2020-05-01-1.6.13-Release/

here's the commit that added it: https://github.com/runelite/runelite/commit/c1fdec9d2ed44302cbc93df4fcc7caba17bdfd9c

https://github.com/runelite/runelite/issues/9033
https://github.com/runelite/runelite/issues/11512

**Comment by graingert** [comment]
@Nightfirecat out interest why did this feature get added? Is it no longer considered botting?
