### ISSUE TITLE
ChatMessage#getSender returns null

### ISSUE THREAD

**Issue by LoudPacks** [runelite/runelite#9036]
**Describe the bug**
`onChatMessage(ChatMessage event) -> event.getSender()` always returns null 
(or atleast for `ChatMessageType.PUBLICCHAT`)

**Expected behavior**
`event.getSender()` should return the name of the source player where applicable

**Environment:**
 - RuneLite version: 1.5.25

**Comment by Hydrox6** [comment]
Events have documentation as to what each field does

**Comment by Adam-** [comment]
I think that the field is named incorrectly and should be `clanChatName`

**Comment by LoudPacks** [comment]
I see now that there is a ChatMessage#name field
