### ISSUE TITLE
Visual glitching in taskbar

### ISSUE THREAD

**Issue by MangoMau** [runelite/runelite#9037]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
I recently got a new monitor which runs at 120Hz. When I go to settings there is a lot of glitching from the client. I tried disabling GPU and FPS settings and restarting Runelite but the issue still persists.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/20467731/59029658-22e1ba00-885f-11e9-88b3-74ae6893ca0c.gif)

**Environment (please complete the following information):**
 - OS: Windows 10 version 10.0.17763
 - RuneLite version: 1.5.25
 - Launcher version: 1.6.0
 - 120hz g-sync monitor

**Comment by abextm** [comment]
https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
