### ISSUE TITLE
Certain Object Markers become incredibly dark due to overlapping

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#9040]
![h8IVL4L](https://user-images.githubusercontent.com/2979691/59035930-380e1700-8866-11e9-8881-d2c7eb9458aa.png)
Certain objects get added to the array multiple times, which highlights them multiple times, causing them to be incredibly dark
This was caused by commit 417e48fc7e99bbadf33ab3e6276afbd13e6c43b9

Making `ObjectIndicatorsPlugin` use a `HashSet` for the object list as opposed to an `ArrayList` fixes this, though it would be better to tackle the underlying issue.

**To Reproduce**
1. Mark something
2. Leave the area
3. Return to the area such that a region change happens
4. Certain objects that you marked will appear as above

**Environment:**
 - RuneLite version: 1.5.26

**Comment by Adam-** [comment]
417e48fc7e99bbadf33ab3e6276afbd13e6c43b9 changed the event behavior to fire events multiple times for objects which are >1x1 tile. We should probably just change this behavior back.

**Comment by Adam-** [comment]
I reverted the change in 59886b084ae2740e30c225eb0f2bd79fb41fdbcd.
