### ISSUE TITLE
Add positioning options for mouseover text plugin

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#905]
I prefer having the mouseover text to the right of my cursor instead of the left, would be nice if there was a toggle for showing it on the left or right side, and custom vertical and horizontal offset options.

**Comment by deathbeam** [comment]
Probably having it to the right of the cursor should be default one and it should not be configurable as all other clients have it on right, and having it on left can overlap with most of the actions that user wants to perform.

**Comment by ShaunDreclin** [comment]
Well there's nothing wrong with having it configurable really, some people might actually prefer it on the left. But yeah at least by default it should be on the right

**Comment by ShaunDreclin** [comment]
Gonna call this one resolved, the tooltip has since been moved to a better location. Options could be nice but not really needed

**Comment by cernodile** [comment]
The current height distance of tooltip is still unsettling and feels odd. Would be great if we could configure the distance from mouse.

**Comment by CaraPis** [comment]
Yea, i agree. The tooltip is still akwardly placed. I believe just right of the mouse would be best imo.

**Comment by deathbeam** [comment]
The current tooltip positioning follows standard tooltip positioning in other applications, even in OSB, so I believe this is non-issue. Maybe the Y distance from the mouse can be reduced by a few pixels, but making that configurable is just too much nit-picking.

**Comment by ShaunDreclin** [comment]
It doesn't actually match OSB. They have it directly to the right, not below the cursor.
