### ISSUE TITLE
Purple light from CoX on selected rare drops outside of raids.

### ISSUE THREAD

**Issue by GottaSlay** [runelite/runelite#9050]
Basically allow us to have this sweet joy of light shine upon the pile of cash in form of an item/unique drop. 
https://i.imgur.com/6f0A8eq.png

To simplify, I'd love to be able to have that light shine onto an item on the ground and the user can choose a certain price at which from the light will start to appear. Lets say 10m for an example.

**Comment by Adam-** [comment]
added in 48c6434e6d0930a85c09a848fcdab9176862744a
