### ISSUE TITLE
NPC Indicators: Tagged NPCs can become an invalid NPC, causing the overlay to crash when rendering names

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#9051]
https://youtu.be/AgFH-xY1vS4

Log: https://gist.github.com/Mijzical/02eafa956b399debe3c6f4599af10af4

As shown there, certain tagged implings will crash the NPC Indicators overlay upon trying to render the name. This is due to `NPC::getName` returning `null`, and further inspection shows the id becomes `-1`

**To Reproduce**
1. Go to Puro Puro
2. Tag an NPC from the shift right click menu. This might need to be done multiple times
3. Catch one of the tagged implings
4. It doesn't break every time. Setting a breakpoint somewhere in `NpcSceneOverlay::renderNpcOverlay` that fires when `actor.getName() == null` will help to notice when it does break

**Environment:**
 - RuneLite version: 1.5.26

Thanks to `Mijzical` in the Discord for reporting this

**Comment by dekvall** [comment]
Closed by #9093
