### ISSUE TITLE
Ability to move the "Make-X" interface button to anywhere on the screen

### ISSUE THREAD

**Issue by freminik** [runelite/runelite#9054]
I am always frustrated when I have to go through the Make-X interface whenever I do cooking, make headless arrows etc.

I would very much, like many others, appreciate a plugin that let's us move the make-x button to anywhere on the screen. 

An alternative would be to that the client automatically presses the button after x amount of seconds but that wont happen.

![concept](https://user-images.githubusercontent.com/43894731/59124738-c5359680-8960-11e9-9246-a0bc468e6743.png)

**Comment by abextm** [comment]
Moving this will probably trigger bot detection. You can just hold down spacebar anyway.

**Comment by freminik** [comment]
Oh yeah & the inventory viewer is totally fine as well I assume. The only difference is that you can click on the interface I suggest.
