### ISSUE TITLE
Inventory Grid in While in Bank/Seed Vault

### ISSUE THREAD

**Issue by EVOuser94** [runelite/runelite#9055]
With the New Inventory grid option it'd be nice to see it implemented while you're in your bank/seed vault aswell

**Comment by kaicianflone** [comment]
I was thinking of taking a look into this but how would you like the plugin to be configured?

3 separate plugins for each grid or one larger encompassing plugin?

**Comment by gregg1494** [comment]
@EVOuser94 are you looking to have the grid system in your bank or do you want the inventory grid to appear while in the bank?

**Comment by EVOuser94** [comment]
I want the inventory grid to appear while in bank, not the bank itself, tho that also sounds pretty useful to me too.

**Comment by while-loop** [comment]
Not sure if the seed vault feature is doable. Items in the invy are not draggable.
