### ISSUE TITLE
Disable left click for clearing bank fillers

### ISSUE THREAD

**Issue by the5thyonko** [runelite/runelite#9058]
I sometimes load into the bank too quickly and clicking on the item I want clears a single bank filler instead. This leads to me having to replace the filler if I notice it and if I close the bank I have to rearrange my items.

**Comment by Nightfirecat** [comment]
Bank fillers open a right-click menu by default on left click, don't they?

**Comment by the5thyonko** [comment]
This might be something Jagex has to fix then. Normally left clicking pulls up the menu but in the situation I mentioned it'll clear the single filler with just a left click.

**Comment by dekvall** [comment]
Duplicate of #2555
