### ISSUE TITLE
Add more XP Globe arc options

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#906]
I would like an option to toggle if the arc starts at the bottom or top of the globe, and some people might also like a clockwise/counterclockwise toggle.

**Comment by abextm** [comment]
This seems like its not actually useful in any way.

**Comment by ShaunDreclin** [comment]
iirc the idea was to make them behave the same as the rs3 globes.

Not "useful" I guess, just a polish thing.
