### ISSUE TITLE
Low fps

### ISSUE THREAD

**Issue by HangUpp** [runelite/runelite#9063]
One or two days ago i was getting a constant 50fps now i get 10-30 fps and my GPU is almost being maxed out I've tried almost everything i could to improve fps but i only got a 1-2 fps improvement.

**Comment by Unmoon** [comment]
Try disabling Object Markers, there is a bug with the plugin on release ATM.

**Comment by HangUpp** [comment]
> Try disabling Object Markers, there is a bug with the plugin on release ATM.
It hasn't been turned on

**Comment by Kamielvf** [comment]
Tagged npcs and similar overlays that highlight entities have the same issue

**Comment by HangUpp** [comment]
> Try disabling Object Markers, there is a bug with the plugin on release ATM.



> Tagged npcs and similar overlays that highlight entities have the same issue

I'm fucking retarded i had power saver

**Comment by Kamielvf** [comment]
So by this the issue is resolved and can be closed?
