### ISSUE TITLE
Ranged Icon is Misaligned on Hiscores Plugin

### ISSUE THREAD

**Issue by xDemoN** [runelite/runelite#9065]
**Description**
Seems like the Ranged icon is a pixel or two larger than the rest of the icons.

**Screenshots**
![image](https://user-images.githubusercontent.com/14188974/59147966-34969f00-89d0-11e9-9d77-cb49b1ba042f.png)

**Additional context**
Literally unplayable :)

**Comment by Unmoon** [comment]
I believe these are taken from [OSRS HiScores page](https://secure.runescape.com/m=hiscore_oldschool/overall.ws). Some of them do look a bit smaller than others, and the Ranged icon is certainly one of the biggest, surrounded by smaller icons making it look out of place.

With that in mind, I don't think this is an issue for us.

**Comment by Nightfirecat** [comment]
I agree, we are displaying the same icons as are shown on the hiscores and in the same way, so I don't think this is an issue which needs fixing.
