### ISSUE TITLE
Open news feed when RuneLite starts after an update

### ISSUE THREAD

**Issue by lynlevenick** [runelite/runelite#907]
Some players might not be aware that the client has updated, and it might be helpful to nudge them to check out the patch notes to help them discover new features or fixes.

**Comment by skimboarder** [comment]
I've been playing around with this in between classes today. Currently, I have a simple dialogue window that pops up if the users client is out-of-date. If the user clicks 'Ok' their browser will open to the patch notes. If they press cancel then the client proceeds as it currently does. 

If the browser can't be opened for some reason, a dialogue opens to let them know and allows them to copy the blog post URL to their clipboard. 

Does this sound sufficient?

**Comment by Adam-** [comment]
Generally if the client is out of date there are no patch notes, since there is no newer release.

**Comment by skimboarder** [comment]
Hmm I think I'm misunderstanding something. When the client starts up in ClientLoader.loadRs(), there is a check made on UpdateCheckClient.isOutdated(). If this returns true I had believed this meant the user was behind the current version and an update would be triggered to obtain the newer release.

Is this not correct? 

I get the patch notes by just getting the most recent blog entry obtained by BlogService.getBlogPosts() which will obviously fail if the most recent post is not the patch notes. I'll need to do some testing of this to make sure it behaves properly.

**Comment by Kamielvf** [comment]
`UpdateCheckClient.isOutdated()` will check the current OSRS version vs the injected client and check if that one is outdated. I don't think it's the RuneLite client.

The launcher will run before the RuneLite client, and it will update trough there if there's a newer version.

I might be wrong but I think that's how it works.

**Comment by Adam-** [comment]
The launcher always ensures you are running the latest release. If it is outdated it means Jagex has updated and we haven't yet. So there is no further RuneLite update. OSB has a "reduced functionality" mode for this situation that pops up a dialog. We just generally don't load any plugins but otherwise don't say much.

**Comment by skimboarder** [comment]
Ahhh okay. I understand now, thank you. It seems like this can most likely not be implemented then, right? At least not from the client...

**Comment by ShaunDreclin** [comment]
Yeah I'd say just have the client launch with the news feed open, with an option to disable that feature somewhere.

**Comment by devLotto** [comment]
```java
@Subscribe
public void onClientUILoaded(ClientUILoaded e)
{
	navButton.setSelected(true);
	navButton.getOnSelect().run();
}
```

in FeedPlugin seems to do it. Idk if this is the best way to go about it.

**Comment by Kamielvf** [comment]
You could maybe check the date of the latest blog post and open it only if its timestamp is within an hour of current time if you really wanted to only open it when there was an update.

**Comment by Adam-** [comment]
For some reason the blog post times are only accurate to 1 day.

**Comment by devLotto** [comment]
^ @deathbeam

**Comment by deathbeam** [comment]
The blog post knows only about the date of the post and not exact time (as it is taken from the blog file name) so you can't get hour from that. I can maybe extend the blog loader to add support for hour and minute to the file name.

For opening the sidebar by default, what @devLotto did in snippet is the correct way to do it I think, except the `setSelected` what is no longer required, as the getOnSelect callback manages the selection state. But i don't know if it is good idea to do it, might screw up some layout managers and also might confuse people who set custom size to client.

**Comment by JustANull** [comment]
You could store the last runelite version that launched, and if it is older than the current or not present then you know to show the blog post etc.

**Comment by JustANull** [comment]
I’m in favor of an option to show the changes or news panel whenever there’s an update, no matter when the blog post happened.

**Comment by Nightfirecat** [comment]
We've removed the news feed plugin as Twitter's API is no longer freely accessible, and OSRS/RuneLite posts are more easily accessed directly via their websites.
