### ISSUE TITLE
FrameDumper not working with certain caches

### ISSUE THREAD

**Issue by hcsfred** [runelite/runelite#9080]
FrameDumper works as intended with the 165 cache, but when using a newer cache (e.g., 180) it fails:
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 42 out of bounds for length 15
	at net.runelite.cache.definitions.loaders.FrameLoader.load(FrameLoader.java:63)
	at net.runelite.cache.FrameDumper.main(FrameDumper.java:95)`

Seems to also happen with other, older caches too. For instance, 172:
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 9
	at net.runelite.cache.definitions.loaders.FrameLoader.load(FrameLoader.java:63)
	at net.runelite.cache.FrameDumper.main(FrameDumper.java:95)`

But it works properly with a 177 cache I tried. I believe it may have something to do with ids being skipped (see this [issue](https://github.com/kfricilone/OpenRS/issues/11#issue-441769604) for another cache library). Other dumpers may well be affected by this problem.

**Comment by abextm** [comment]
I can't repro this on the latest cache. Judging by your error I would guess that your frames and framemaps in the caches that are failing are out of sync.

**Comment by hcsfred** [comment]
@abextm Did you load the latest cache explicitly? As the cache lib loads 165 by default. I shall try the latest release again once I am back from holiday.

**Comment by abextm** [comment]
yes I explicitly loaded a `2019-06-13-rev180` and `2019-06-06-rev180` caches

**Comment by hcsfred** [comment]
@abextm I just tried again and I still get the same ArrayIndexOutOfBoundsException. Perhaps I am missing something... here is my process: pulled latest repo, navigated to FrameDumper, replaced
`try (Store store = new Store(base))`
with
`try (Store store = new Store(new File("./180cache/")))`
where the 180cache is the directory for the 2019-06-13-rev180 cache. I then ran the class.

**Comment by Adam-** [comment]
For me, it crashes on archive 2093 file 0 on the latest cache.

**Comment by hcsfred** [comment]
Yes, archive 2093 for me too. For that frame, the frame map archive id is 1803, but during decoding it is read in as 1796. The frame's data can't be corrupted, as it obviously works in the live game, so I presume the issue is linked to how the indices are read in.
