### ISSUE TITLE
Overlay for untradable items on 'Items Lost on Death' screen

### ISSUE THREAD

**Issue by JustenMeyer** [runelite/runelite#9081]
**Is your feature request related to a problem? Please describe.**
I struggle to determine what items would actually be lost on death when PVMing, would enjoy seeing an overlay on the "Items Kept on Death" screen that truly shows what items you would keep/lose.

**Describe the solution you'd like**
Some sort of overlay, maybe a green box at 25% opacity for items that would be kept, and a red one for items lost.

Sorry if this already exists, tried searching and didn't see anything.

**Comment by TheStonedTurtle** [comment]
Somewhat related to #6669, could probably use some of the info in there.

**Comment by Adam-** [comment]
This seems exactly what #6669 is to me?

**Comment by TheStonedTurtle** [comment]
I just read the title but yeah its pretty much exactly what they are asking for

**Comment by Adam-** [comment]
Added in #6669
