### ISSUE TITLE
Key Remapping -- Disable F-Keys while in NPC dialogue 

### ISSUE THREAD

**Issue by Passwordhunter1** [runelite/runelite#9085]
**Is your feature request related to a problem? Please describe.**
Typing 1-0 on the keyboard while in NPC dialogue to enter a selection will change the current inventory tab displayed.

**Describe the solution you'd like**
Disable F-keys while in NPC dialogue

Possibly return to "Press Enter to chat..." state after closing a private message to a friend

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by cfoulk** [comment]
This would be great!

**Comment by RALEx147** [comment]
This has already been added and should be in the next release:

https://github.com/runelite/runelite/commit/bb25aee4cc190463c694498039a311b4dcbb147a
