### ISSUE TITLE
Runelite unexpectedly closes after several hours

### ISSUE THREAD

**Issue by dpedu** [runelite/runelite#9091]
**Describe the bug**
If I leave runelite running for several hours, eventually it closes unexpectedly. 

I tend to leave the client open when I am finished playing, sometimes for long periods of time e.g. overnight. Sometime the next day - always when I have returned and am using it again - the client unexpectedly closes. I would estimate 18-24 hours are needed to reproduce the issue.

**To Reproduce**
1. Open and play Runelite for several hours.
2. Log out of the game, and leave runelite sitting for several hours
3. Log into the game and play for several hours.
4. Eventually, the client unexpectedly closes.

**Expected behavior**
The client does not close until I ask it to.

**Screenshots**
N/a

**Environment (please complete the following information):**
 - OS: OEM Windows 10 x64
 - RuneLite version: Latest? Where do I find this?
 - Launcher version: Latest? Where do I find this?

**Additional context**
I looked at the logs and didn't see anything that looked like a crash or shutdown. I am not comfortable attaching logs, I don't know what other information is in them.

It is NOT running out of memory and being killed either by the system or java runtime.

**Comment by Hermetism** [comment]
I just want to suggest that if you've made your own plugins that you may have a value in your plugin that is overflowing eventually, probably a 'timer' of some kind or a thread.

I don't recall seeing anything that would overflow in the source I have read.

**Comment by dpedu** [comment]
I'm not using any custom plugins, but an assortment of default ones that ship with the client (including GPU). 

I happened to look in

**Comment by dpedu** [comment]
I'm not using any custom plugins, but an assortment of default ones that ship with the client (including GPU).

I happened to look in Appdata\Local\RuneLite and came across some java crashdumps - the sort that start with:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe7e500e0e, pid=7484, tid=0x0000000000003c18
#
# JRE version: Java(TM) SE Runtime Environment (8.0_172-b11) (build 1.8.0_172-b11)
```

The timestamps of the dumps don't align with client exits I've had (there should be many more), but it's a starting point. I have a java update pending anyways, so I'll go ahead and install it and see if anything changes.

**Comment by Hermetism** [comment]
The default `-Xmx` of 512mb that is set for the JVM might be too low for the client to run for 24+hours but that also suggests garbage collection isn't releasing something that runelite is creating.

That crash you are seeing is the JVM running out of memory, not your system.

**Comment by abextm** [comment]
That crash is a segfault, not an oom, and has nothing to do with heap pressure. It means there is a bug in one of the following:
 1) The JVM
 2) One of our native libs (jogl, discordrpc)
 3) Your hardware

**Comment by Hermetism** [comment]
Unexpected [xkcd](https://xkcd.com/371/)

Sorry for the bad info, thought is was a alloc failing or something.

**Comment by Nightfirecat** [comment]
I'm closing this issue as there have been no updates in some time. If any further information is found on this, please feel free to re-open it for further investigation.
