### ISSUE TITLE
Kalphite Cave Crashes computer

### ISSUE THREAD

**Issue by ImAcoustic** [runelite/runelite#9095]
So, while having no resources to show or even reproduce this effect, i've been doing kalphite queen recently without the desert elite diary's, forcing me to do the ~2ish minute run just to get there. i have noticed that a few times (5 out of 100 kill so far) runelite basically locks up my computer. it stops everything on my computer from working, so bad that my cursor dissapears from my screen and i either have to restart my pc or wait out the 5 minutes. while task manager shows runelite is taking up 500 mb's of ram, when i close out of runelite my ram load goes from maxed out (16 gb's ddr4) down to just 3 gb's usual usage. I have no idea what causes this problem cause like i said it happens very rarely and i havent been able to reproduce the effect by trying. that being said my theory is due to the excessive amount of ground clutter in that area, the 16x anisotropic filtering goes haywire every once and a while and destroys ram usage.

**Comment by Nightfirecat** [comment]
If you are still seeing this issue, please reproduce it ingame and post your client and launcher logs [(steps to find those are on our troubleshooting page)](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client) and we will re-open this issue.

**Comment by Darek79** [comment]
yo, i have the same issue. the computer when i get poisoned by a kalphite attack
