### ISSUE TITLE
Interface Styles -> High Detail Health bars

### ISSUE THREAD

**Issue by AildirMike** [runelite/runelite#9096]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)
**No previous described issue**

**Describe the bug**
After the latest runelite update High Detail health bars no longer show up. The old healthbars show even though the box is ticked and the plugin is activated.

**To Reproduce**
1. Go to 'Interface Styles'
2. Click on 'High Detail Health Bars'
3. See error High Details health bars not showing

**Expected behavior**
The High Detail Health Bar should be showing whenever someone is in combat.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - RuneLite version: 1.5.26
 - Launcher version: latest version

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Hydrox6** [comment]
Jagex changed how default healthbars work, which caused this. A fix is in development

**Comment by AildirMike** [comment]
Thank you very much! I just wanted to put it out there, in case you guys didn't know yet :-) Thanks for the fast reply!
