### ISSUE TITLE
Allow arbitrary key remaps

### ISSUE THREAD

**Issue by AildirMike** [runelite/runelite#9097]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
- The key Remapping feature remaps the F keys to 1, 2, 3 and so on.. However on my Azerty Keyboard their default is &, é, ", ', and so on.. Making the feature unusable for me.

**Describe the solution you'd like**
- Is there a possibility for other keyboard to be supported by runelite?

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
- X

**Additional context**
- X

**Comment by Adam-** [comment]
fixed in 3125b74f4fb4cbfb05e90d78a61c9ad216b1b08e
