### ISSUE TITLE
Examine Brings up Wiki page

### ISSUE THREAD

**Issue by hookemt** [runelite/runelite#9103]
**Is your feature request related to a problem? Please describe.**
Sometimes its just annoying to open a new tab and go to the wiki and search up monsters, not necessarily a problem but would be an interesting and nice addition. 

**Describe the solution you'd like**
When examining monsters that have a corresponding wiki page, it will open it up in your default browser. 

**Additional context**
Just a thought, i understand it might be a big project ;)

**Comment by Twiglet1022** [comment]
This is already a feature and implemented in an even better way: https://github.com/runelite/runelite/wiki/Wiki

Click the wiki banner then click on the monster to go to its wiki page.
