### ISSUE TITLE
Drop Notification bug

### ISSUE THREAD

**Issue by DarthMadara** [runelite/runelite#9106]
**Describe the bug**
The bug occurs while at the GE. While standing at the GE, with the window minimized, the drop notification tells me I received an odd drop (last one was like 200+ ropes) The drop changes every time it happens, there is 0% chance the drop is real. Only happens when minimized. This has happened to me multiple times. 

**To Reproduce**
1. Go to 'The Grand Exchange'
2. Click on 'The minimize window button'
3. Wait til 'the notification bubble tells you, you got a random drop'

**Environment (please complete the following information):**
 - OS: Windows 7. 
 - RuneLite version: 1.5.26
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
If you are still seeing this problem, please post your client logs when you notice the bug and we will re-open this issue.
