### ISSUE TITLE
Client Crash while resizing

### ISSUE THREAD

**Issue by RiceBoxer** [runelite/runelite#9115]
**Describe the bug**
While resizing the client window, the game window crashed. The game window appeared half drawn and no sounds played. As an application, Runelite did not - I still received a prompt asking if I wanted to exit before closing the game.

I use a tiling window manager which forces Runelite into a very small window size while repositioning windows ~(960 x 270).

I encountered this issue twice while repositioning windows; but, could not reproduce it on demand with a fresh client

**Expected behavior**
Game window should not crash

**Screenshots**

This screenshot is not of the crash but has a similar layout to when it occurs
![screenshot](https://i.imgur.com/khCh1dN.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 bionic
 - RuneLite version: 1.5.26
 - Launcher version: 1.6.2

I have been using the RuneLite.AppImage
```
java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```
**Additional context**

The following snippet was taken directly from the console output
```
2019-06-15 09:21:13 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
java.lang.ArrayIndexOutOfBoundsException: 201199
	at net.runelite.client.callback.Hooks.clearColorBuffer(Hooks.java:498)
	at ad.gf(ad.java:4899)
	at az.ir(az.java:9676)
	at az.ir(az.java:9707)
	at bv.iz(bv.java:9565)
	at client.jh(client.java:4587)
	at client.ab(client.java:1690)
	at ba.p(ba.java:419)
	at ba.run(ba.java:373)
	at java.lang.Thread.run(Thread.java:748)
error_game_crash
```
client log: https://pastebin.com/axxyumAB

**Comment by Apocalypsing** [comment]
I started facing the same issue on my system running Windows 10 today, specifically after I had changed RuneLite's DPI settings from the Windows default "System" to "Application" (under the Windows program compatibility settings, to be clear). With that compatibility flag set, RuneLite no longer enforced the minimum 765x503 size for the client applet. And, like clockwork, I can easily get the client to crash by resizing below that normal minimum size. Reverting the DPI settings and the minimum applet size works as intended and no crashes.
