### ISSUE TITLE
Title toolbar buttons can become non-accessible

### ISSUE THREAD

**Issue by Abextm** [runelite/runelite#912]
As it is right now the InfoPanel can be disabled while custom chrome is also disabled, making the buttons non-accessible. We could solve this a couple ways and I'm not sure what would be best.

1) Make the info panel always enabled
2) Conditionally set the disable-ability based on the custom chrome setting.

**Comment by deathbeam** [comment]
Imo this is fine, because users can always re-enable the info plugin again if they need the buttons.

**Comment by Abextm** [comment]
I feel like this is a trap for new users

**Comment by deathbeam** [comment]
Resolved in #1146
