### ISSUE TITLE
Woodcutting special attack boost notifier

### ISSUE THREAD

**Issue by Paradoxis** [runelite/runelite#9122]
**Is your feature request related to a problem? Please describe.**
When afking woodcutting, I often forget to use the dragon axe special attack to get the boost.

**Describe the solution you'd like**
Would it be possible to add a notifier to the woodcutting plugin which notifies you when you  can perform another boost?

**Comment by Twiglet1022** [comment]
This feature already exists. Check out the special attack threshold notification in the Idle Notifer

https://github.com/runelite/runelite/wiki/Idle-Notifier

**Comment by Paradoxis** [comment]
Thanks, didn’t realize it was part of the idle notifier
