### ISSUE TITLE
Highlighted Item Priority

### ISSUE THREAD

**Issue by AildirMike** [runelite/runelite#9129]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

- It would be useful for a priority system to be implemented in Runelite that works with the Ground Items highlight..

E.G. When fighting green dragons, Green Dragonhide and Dragon Bones are highlighted items.. Gold, Adamant Full Helm and other clutter objects are not highlighted. I would be usefull to be able to left-click pick-up the Dragonhide and Bones... Rather than prioritising gold and other useless objects.

**Describe the solution you'd like**

- A priority system that will left-click pick-up your highlighted objects first.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

- X

**Additional context**

- X

**Comment by Unmoon** [comment]
This is rejected, see https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features#menu-entry-swapping
