### ISSUE TITLE
Add actions left until next level

### ISSUE THREAD

**Issue by 25toLife** [runelite/runelite#913]
It would be nice to see how many actions are required until your next level given the latest xp drop you received in that skill (or in the case of combat skills ~kills left).

**Comment by deathbeam** [comment]
This is already implemented, hover over the XP bar in XP tracker sidebar. But for combat skills it is tracking only last XP drop too and not kills left.

**Comment by Kruithne** [comment]
Would it be possible to get it so that this information can come up in the XP tracker window without having to hover over the bar? Perhaps configurable by the user as to what comes up in each box?

**Comment by deathbeam** [comment]
There is #507 that will do it.

**Comment by sethtroll** [comment]
Added in #507
