### ISSUE TITLE
left click quick enter tob

### ISSUE THREAD

**Issue by martijn26** [runelite/runelite#9131]
**Describe the solution you'd like**
when you left click the  door inside tob make it quick enter instead of enter

**Comment by rlw0014** [comment]
The Theatre of Blood Door only has "Enter" option. RuneLite does not add the Quick-Enter menu options that you may have seen at other places. Jagex would have to add this option and then we would be able to swap it to the first menu option for you.

**Comment by martijn26** [comment]
there is a quick enter option already. only you need to right click the door atm the moment and then choose the second option in the right click dropdown menu. 

https://imgur.com/a/rrjDGHO
