### ISSUE TITLE
Moveable and scalable world map

### ISSUE THREAD

**Issue by lacaze** [runelite/runelite#9135]
**Is your feature request related to a problem? Please describe.**
The world map is large and it would be handy to be able to scale the map to a size whilst playing so u can click on the world and interact with stuff while the map is open and a scaled down size

**Describe the solution you'd like**
when opening the world map, you can drag a corner to change the width and height of the world map size. This helps one be able to look at the map while interacting with the world at the same time easier as regularly u can only see the sides on the screen when the map is open.

**Describe alternatives you've considered**
There isnt much other than using the mini map. 

**Additional Notes**
I believe this was actually added in a later version such as 2008 or 2009 in runescape where u could edit the map size and do what i described.

**Comment by Hydrox6** [comment]
You can already move and change the size of the Floating world map
