### ISSUE TITLE
Custom key remapping (In addition to F-keys)

### ISSUE THREAD

**Issue by Passwordhunter1** [runelite/runelite#9139]
**Is your feature request related to a problem? Please describe.**
OSRS is not the only game that I play. Being able to use keybind from other games to do similar actions would be a nice quality of life change.

**Describe the solution you'd like**
Ability to add (In addition to current f-key changes) other keybinds to do certain actions. Such as 'O' to open quest tab or 'M' to open the world map.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**
I have my keybinds set up as such I can press 7 (using your key remapping) to go to my quest menu. I would prefer to press 'O' to get there. Additionally, and what actually brought this to my mind, I would like to be able to press 'M' to open the world map.

**Comment by Vokuar** [comment]
I don't think you can do that without a mouse movement on its own but I could be wrong

**Comment by abextm** [comment]
We can't open the world map with a hotkey because there isn't an existing hotkey for it. The part of this that is possible is duplicated by #9097.

**Comment by 5l4y3r-burrito** [comment]
sorry to necro this, but there is now a hotkey for world map (Ctrl-M) with the latest OSRS render update, no option yet to remap that in RuneLite's Key Remapping plugin.

I would love to be able to rebind this to M, and not need to hold control (like how maps work in literally every other game)

**Comment by wwboynton** [comment]
> I would love to be able to rebind this to M, and not need to hold control (like how maps work in literally every other game)

I'm not sure if that will violate the OSRS principle of remapping one input to one input -- having one key do the job originally done by two keys could _technically_ be a party foul. It would be silly, but I've seen sillier stuff be denied in Runelite because it's safest for Runelite to play to the letter of the law with Jagex policies.

If they can get away with it though, I'd really really like this. It would allow me to just put it on a mouse button.

**Comment by HydrogenHydroxide** [comment]
+1 in favor of finding out.

**Comment by ksulli10** [comment]
Please allow us to change this to M instead of Ctrl+M!
