### ISSUE TITLE
Client closes randomly after a few hours of playing

### ISSUE THREAD

**Issue by kaboomtheory** [runelite/runelite#9141]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Happens when i'm afk training at NMZ, and after about an hour or more the client will just close with no message or warning.

**To Reproduce**
Just sit in NMZ afking training until it eventually closes my client.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Latest Version
 - Launcher version: Latest Version

Running on a Surface Pro 4 with i5 6300u with 4gb RAM. I understand my laptop isn't the best thing in the world especially with the low amount of RAM, so I hope that isn't the culprit.

[client.log](https://github.com/runelite/runelite/files/3303544/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3303545/launcher.log)

**Comment by Nightfirecat** [comment]
Is there a file in your log folder with the name `hs_err`? Your client logs don't show any issues.

**Comment by dekvall** [comment]
I am closing this, if the problem persists and you have information to add feel free to reopen the issue.
