### ISSUE TITLE
Notification for NPC Aggression Timer

### ISSUE THREAD

**Issue by Notboo** [runelite/runelite#9143]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
Add a notification alert when the Time until NPCs become unaggressive. 

**Describe alternatives you've considered**
Add a feature on Idle Notifier or NPC Aggression Timer 

**Additional context**
This feature can be modified in either the plugin for NPC Aggression timer or Idle Notifier.

**Comment by pullup** [comment]
Would help a lot, since the out of combat one often goes off AFTER I log out :/

**Comment by Notboo** [comment]
> Would help a lot, since the out of combat one often goes off AFTER I log out :/

that happens a lot as well lol

**Comment by Zaino60** [comment]
Support!

**Comment by osrs-music-map** [comment]
@Nightfirecat @notboo @h0dgep0dge I think this has been implemented in https://github.com/runelite/runelite/commit/99e26aa17410c8743fb87f13ab89c6de375961e6#diff-98d1aeae4bf883a8e4a8eabdd6dd3578

can probably close this issue

(though I'd like to see an option to stop the notification sound if we are using a long-running custom audio file for it)

**Comment by h0dgep0dge** [comment]
@osrs-music-map I'm not certain what you mean by "long-running custom audio file", it's not implemented by playing a recording of a notification noise preceded by 10 minutes of silence haha.

Unfortunately I'm unable to close the issue, but this is the exact issue I wrote my code to solve, I would encourage OP to try it out now that is integrated into the mainline code.
