### ISSUE TITLE
Java 11 and RuneLite: How to blow your eardrums 101

### ISSUE THREAD

**Issue by Farcrada** [runelite/runelite#9149]
**Describe the bug**
Sound devices seem to be entirely ignored with Java version 11 (`pavucontrol` and `pulseeffects` for me).

**To Reproduce**

1. Have (and use) Java version 11
2. Launch
3. Turn sound on
4. Go see a doctor for hearing problems - oh, and buy a new pair of headphones/speakers as the current ones will probably be blown.

**Expected behavior**
- Shows up in `pavucontrol` and `pulseeffects` like Java 8 does (although maybe not two streams (~~where one is silent~~)).
- Doesn't blow my ears out.

**Screenshots**
For version 8 this should be there:
![Selection_259](https://user-images.githubusercontent.com/8385001/59795237-15a2e180-92db-11e9-9b5d-8a3ccdd1497f.png)
![Selection_260](https://user-images.githubusercontent.com/8385001/59795271-2b180b80-92db-11e9-9a63-ad7e44cb0b16.png)
For version 11 this doesn't exist.

**Environment (please complete the following information):**
 - OS: Linux Mint 19.1 (Cinnamon)
 - RuneLite version: 1.5.26
 - Launcher version: 1.6.1

**Additional context**
https://github.com/runelite/runelite/issues/3999#issuecomment-475908972
And
https://github.com/runelite/runelite/issues/5040#issuecomment-417112504

**Comment by Farcrada** [comment]
> (although maybe not two streams (where one is silent))
Found out what this is: one is for music, the other is for effects/everything else. Seperate issue, but related in a way: Can this be combined into a single stream from RuneLite on-out?

**Comment by abextm** [comment]
This sounds like a bug in pavucontrol/pulseaudio/jvm to me. Are you sure java is running through pulseaudio and has not taken the alsa output directly?

**Comment by Farcrada** [comment]
I don't really know how to check; though if RuneLite is giving the correct (albeit in two streams) on Java 8 without any additional tinkering, what happened to 11?

**Comment by bekemaydin** [comment]
I have the similar sound issue with my pc. If I am start the launcher before spotify, browsers or discord, i cant even hear any sound from my system. (In discord call, my voice continues to go to other people while the sound does not work.) When I turn off the launcher, sounds start to work.

The only solution is to turn on other audio sources before start to launcher.

System: Ubuntu based Pop_OS!
Java version: 11.0.4
RuneLite version: 1.5.30.1
Launcher version: 1.6.2

**Comment by abextm** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#pulseaudio-forcibly-taken-over-by-client
