### ISSUE TITLE
"Out of Combat" Notification steals focus

### ISSUE THREAD

**Issue by Farcrada** [runelite/runelite#9151]
**Describe the bug**
As soon as you leave combat and RuneLite detects this it notifies the system, but the window also orders focus (focus stealing). The latter is not supposed to happen.

**To Reproduce**
Dunno, just have RuneLite and get into combat and Alt+Tab before getting out of combat and the notification (event) will steal focus.

**Expected behavior**
A notification; not stealing focus. Not tested with other types of notifications (As I type that the idle notification stole focus.).

**Environment (please complete the following information):**
 - OS: Linux Mint 19.1 (Cinnamon)
 - RuneLite version: 1.5.26
 - Launcher version: 1.6.1

**Additional context**
Other applications that notify (Discord for example) don't steal focus. Also, RuneLite has stolen focus without changing Alt+Tab order. The option in Cinnamon (Start -> Windows -> Behavior -> Window Focus -> Prevent focus stealing) is also on, which means my Desktop environment is already doing it's best to stop focus stealing.

**Comment by Hydrox6** [comment]
Requesting focus on notification is an option, under `RuneLite` -> `Request focus on notification`

**Comment by Farcrada** [comment]
> Requesting focus on notification is an option, under `RuneLite` -> `Request focus on notification`

Oh damn, I completely missed that! Thank you.

Given that, though, it doesn't respect my settings in the DE; which I'd still consider undesirable and as such also a bug.

**Comment by Adam-** [comment]
It seems unlikely this is a bug in RL. It is probably either in your DE or maybe in Java somewhere.
