### ISSUE TITLE
How to find an InventoryID?

### ISSUE THREAD

**Issue by robrichardson13** [runelite/runelite#9154]
Does anyone know how to find an InventoryID? Looks like contains like Chambers of Xeric Chest (581) and Theatre of Blood Chest (612) are defined in InventoryID.java, but where did those numbers come from?

I'm trying to setup an InventoryID for the Looting bag to grab the items in the bag once you open it, but I can't figure out where to look to find the ID.

Thanks

**Comment by Joshua-F** [comment]
This is probably a better question for the discord. The ID is `516` though. 

https://github.com/RuneStar/cs2-scripts/blob/master/scripts/%5Bproc,bankside_lootingbag_draw%5D.cs2#L10
