### ISSUE TITLE
Raids Special Loot

### ISSUE THREAD

**Issue by Aneexul** [runelite/runelite#9157]
**Describe the bug**
COX final interface is all de-colored to default text color.

**To Reproduce**
1. Get a rare drop in your name.
2. Drop is not highlighted
3. Infinite rage.

**Expected behavior**
Red color text for special rare loot. Purple color text for other important stuff.

**Screenshots**
How it looks without bug
![Image of Cox Drop without bug](https://cdn.discordapp.com/attachments/368250382884798464/463347541283569684/unknown.png)
How it looks with bug
![Image of Cox Drop with bug](https://cdn.discordapp.com/attachments/368250382884798464/591007534941208576/unknown.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.27
 - Launcher version: Latest..?

**Comment by Hydrox6** [comment]
Could you provide a screenshot of your `Chat Notifications` configuration please?

**Comment by Aneexul** [comment]
![Image of Chat Notification settings](http://prntscr.com/o4cwrv)

**Comment by Hydrox6** [comment]
`Highlight words` strips colour before highlighting, and since you have your name in there (`Frir`), it killed all the colour from the unique. You don't actually need your name in the highlight list, as `Highlight own name` will do that automatically.

**Comment by Aneexul** [comment]
lets hope that was the problem, thanks.
