### ISSUE TITLE
REQUEST: Make more plugins related to 2010-2011 Runescape

### ISSUE THREAD

**Issue by lugia00** [runelite/runelite#9160]
Anything from xp drops from back in the day, slayer task counter, move hp/prayer orbs on the other side,  hitsplats, some variety of HD ground textures and even more 'smoothness' in the general gameplay.

Thanks.

**Comment by Nightfirecat** [comment]
We have a number of open issues related to some of these items. As-is, we will not be able to effectively track this request as a single "master" list, so please check for existing issues related to individual requests and file new issues (one per request) for ones which don't exist yet.
