### ISSUE TITLE
Crafting Calc Missing Snakeskin gear

### ISSUE THREAD

**Issue by xDeadweightx** [runelite/runelite#9162]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**
1. Go to 'Skill Calculator'
2. Click on 'Crafting Icon'
3. Scroll down to '(Between 45-55 )' or filter using 'Snake'
4. no Snakeskin Gear (except the shield)

**Expected behavior**
Should see the snakeskin gear

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.27
 - Launcher version: 1.6

**Additional context**
--

**Comment by Serpa88** [comment]
Will work on it
