### ISSUE TITLE
Items Kept on Death Graceful

### ISSUE THREAD

**Issue by doulosiesous** [runelite/runelite#9171]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Items Kept on Death does not accurately show how graceful outfit works with other items.

**To Reproduce**
1. Go to Draynor Village with Full Graceful Outfit and any third item (I used ring of wealth and amulet of glory on two separate tests) equipped and nothing else.
2. Click Items Kept on Death tab. It shows full graceful outfit is kept on death, but not the extra item.
2. Pickpocket Master Farmer until it kills you.
3. Get teleported to lumby on death but retain all items including the most valuable other item All items remain equipped except for extra item, Graceful Cape, and Graceful Top.

**Expected behavior**
Expected to lose all items except graceful. Kept most valuable item in inventory as well when I died

**Screenshots**
![Glory 6 1](https://user-images.githubusercontent.com/19418878/59895194-d5a63200-93a0-11e9-9494-1c8d06a6ebbc.PNG)
![Glory 6 2](https://user-images.githubusercontent.com/19418878/59895208-e2c32100-93a0-11e9-8cea-70865c705ae3.PNG)
![Glory 6 3](https://user-images.githubusercontent.com/19418878/59895212-e5257b00-93a0-11e9-98f9-9bea5eeb504d.PNG)

**Environment (please complete the following information):**
 - OS: Windows
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.0

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by doulosiesous** [comment]
![image](https://user-images.githubusercontent.com/19418878/59895426-cf648580-93a1-11e9-9497-8d071379e5af.png)

Runescape official client thinks you will lose most of graceful on death, but those items stay equipped when you die in this fashion.

**Comment by TheStonedTurtle** [comment]
Should be fixed by #9161

**Comment by Adam-** [comment]
fixed in #9161
