### ISSUE TITLE
Kingdom of Miscellania Price Check Rewards

### ISSUE THREAD

**Issue by SeanRP** [runelite/runelite#9173]
It would be nice to know how much the Kingdom of Miscellania resources are worth upon collection.

A possible fix would be adding a chat notification similar to the clue casket message ("Your treasure is worth around X Coins!").

**Comment by dappersnapper456** [comment]
OMG YES

**Comment by basicDamen** [comment]
If someone can grab me the InventoryID from the Kingdom Loot Interface, I'll work on it. - I don't use Kingdom, so I have nothing to collect to grab it with, lol.

**Comment by dappersnapper456** [comment]
> If someone can grab me the InventoryID from the Kingdom Loot Interface, I'll work on it. - I don't use Kingdom, so I have nothing to collect to grab it with, lol.

Someone help this fellow

**Comment by Pineapplezz** [comment]
I tried adding it but there is no dev tool to get the inventoryID so the only way to get the ID is by using runestar(Which I am unsure how to use) If someone can grab me the inventoryID of the kingdom interface I also can put this together quick, just having issues with getting the inventoryID as well

**Comment by abextm** [comment]
Just subscribe to `InventoryChanged` and log that.

**Comment by Pineapplezz** [comment]
InventoryChanged?

**Comment by Adam-** [comment]
Added in #9607
