### ISSUE TITLE
Client won't startup (Have had it working for over a year)

### ISSUE THREAD

**Issue by Luck-y-Thirteen** [runelite/runelite#9174]
When I start up the client a second window pops ups saying "OpenGL ES error - Can't find the Intel graphics". This then forces the client to close without loading.

I have been running Runelite fine for over a year until the last week where I have been experiencing crashes in the middle of gameplay. I realised this was because after recently moving my pc, I mistakenly plugged the HDMI into the motherboard rather than the graphics card directly. Having now plugged the HDMI back into the graphics card, runelite now cannot run at all.

I know this is a slightly dumb problem completely of my own making but how on earth do I get runelite to stop searching for Intel graphics (presumably the built in graphics to the pc) that I am no longer using?

EDIT: I plugged the HDMI back into the wrong slot which has allowed me to load runelite and turn the GPU settings off. Now back with the HDMI in the graphics card, I can load runelite but NOT the graphics plugin. The question is now how can I use the GPU plugin without it trying to detect the integrated graphics instead of my graphics card.

**Comment by aurismat** [comment]
@Luck-y-Thirteen Try toggling between built-in graphics and dedicated graphics before you run RuneLite. This happened to me just now, and this fixed it right away. Using my laptop with Nvidia MX130 GPU. What do you know - doing the good old 'turn off and back on' seems to help.
