### ISSUE TITLE
Runelite fails to start up

### ISSUE THREAD

**Issue by Garfiend** [runelite/runelite#9175]
**Describe the bug**
Runelite is able to load a few plugins, but then it comes up with an error, "Error loading client! Check your logs for more details."

**To Reproduce**
1. Open Runelite.
2. See error

**Screenshots**
![err](https://user-images.githubusercontent.com/50038638/59933062-788c9980-93fd-11e9-8a65-0c68e8ed726f.PNG)

**Environment (please complete the following information):**
 - OS: Windows 7 64 bit Service pack 1
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.0

**Additional context**
[launcher_2019-06-20.0.log](https://github.com/runelite/runelite/files/3315057/launcher_2019-06-20.0.log)

**Comment by StormRaiser245** [comment]
I assume you've got this line in your log: ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.io.IOException: unexpected end of stream on Connection{oldschool.runescape.com:80, proxy=DIRECT hostAddress=oldschool.runescape.com/91.235.140.148:80 cipherSuite=none protocol=http/1.1}


If so, then I've got exactly the same problem.

**Comment by StormRaiser245** [comment]
I assume you've got this line in your log: ERROR net.runelite.client.rs.ClientLoader - Error loading RS!
java.io.IOException: unexpected end of stream on Connection{oldschool.runescape.com:80, proxy=DIRECT hostAddress=oldschool.runescape.com/91.235.140.148:80 cipherSuite=none protocol=http/1.1}

But I found one way to fix this: Just open your OldSchool RuneScape program, then close it and open RuneLite. It should work now.

Apparently the program needs to get the latest updates.

**Comment by Garfiend** [comment]
Thanks for the solution, it works now. :)
