### ISSUE TITLE
GPU MSAA bug

### ISSUE THREAD

**Issue by Evolution0** [runelite/runelite#9178]
**Describe the bug**
With MSAA enabled (Any level) all objects seem to have their wireframe poking out of them.

**Screenshots**
![2019-06-21_14-34-28](https://user-images.githubusercontent.com/1984403/59978073-85002600-95a6-11e9-96b0-b83bf3c547fc.png)
![2019-06-21_14-34-32](https://user-images.githubusercontent.com/1984403/59978074-85002600-95a6-11e9-81fa-9fab5a39dae6.png)

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.0

**Additional context**
 - GPU: RX580
 - OpenGL version: 26.20.11000.13558

Edit: Screenshots now actually added after I forgot >.>

**Comment by xTheEc0** [comment]
Can confirm.  
I have a Lenovo ThinkCentre M910x at work that runs Radeon RX 460 and has the same issue even with the newest driver.

**Comment by Alexsuperfly** [comment]
as per this https://github.com/runelite/runelite/wiki/GPU-FAQ#when-i-turn-on-anti-aliasing-weird-lines-appear you dont want to be on the latest version
