### ISSUE TITLE
Tile Indicators Highlight hovered tile phantom clicks

### ISSUE THREAD

**Issue by TzRotJed** [runelite/runelite#9179]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Clicking on a wall with void behind or clicking out of range doesn't produce any input until the cursor hovers a tile in range.

**To Reproduce**
1. Enable **Tile indicators** and **Highlight hovered tile**
2. Go to POH and walk all the way to the border to see the void
3. Click the void
4. Move the cursor onto a tile in range
5. Now the click in the void registers, producing unexpected behavior.

**Expected behavior**
When clicking the void, nothing at all should happen, resulting in the same behavior as not having the Highlight hovered tile enabled.

**Screenshots**
![RuneLite_012L3rnVZS](https://user-images.githubusercontent.com/52086195/59949770-6863d100-9474-11e9-842a-45dc59704f50.png)

**Environment (please complete the following information):**
 - OS:  Windows 10
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
Can you reproduce this behavior on the vanilla OSRS client?

**Comment by TzRotJed** [comment]
Just tested vanilla OSRS client **does not** produce any input when clicking at the void nor when clicking at the void and then hovering the ground with the cursor.

**Comment by Unmoon** [comment]
Some streamer (I forgot the name, and can't find it in history) reported this on Discord as well.

**Comment by Adam-** [comment]
fixed in a3e9b790dd92d8fe7eb12d35de6db250f1f78328
