### ISSUE TITLE
Add NSEW to compass

### ISSUE THREAD

**Issue by lacaze** [runelite/runelite#9181]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A North South East and West letter on compass for easier navigation 

**Describe alternatives you've considered**
Not that it is a huge problem without it but it would allow quicker navigation when going to places with directions 

**Additional context**
n/a

**Comment by Nightfirecat** [comment]
It's not a perfect fix, but the 2006 interface style has a compass with all cardinal directions labeled.

**Comment by dekvall** [comment]
#5019 seems to have it figured out, but that is also with an interface style change.

**Comment by Hydrox6** [comment]
This is probably better solved with the `Resource Packs` plugin and a custom made pack with the compass image from #5019
