### ISSUE TITLE
Items Kept on Death - Clue Boxes

### ISSUE THREAD

**Issue by winterdaze-rs** [runelite/runelite#9184]
**Describe the bug**
Clue Boxes are not taken into account in the interface

**To Reproduce**
Have clue/casket and clue box in inventory

**Expected behavior**
From the wiki:

> If a player dies in the Wilderness with a clue scroll while having the clue box in their inventory, the clue box will be destroyed, but the clue scroll will be protected. If the player is carrying multiple clue scrolls on death, only one will be protected, even with multiple clue boxes. The protected clue scroll does not take the place of one of your three items kept on death (hence Items Kept on Death interface not showing it as protected), or four with the Protect Item prayer, so it is possible to keep a total of five items on death if you have a clue scroll and clue box in your inventory upon death. As the clue box will also protect the reward casket, it is advised to not open it before leaving the Wilderness if you want to protect your reward. Although clue scrolls are always kept on death outside the Wilderness, clue boxes are always lost on death.

**Screenshots**
[link](https://gyazo.com/b4ebf9be0d5ba7d4dff973e66ef5d6c9)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.2

**Additional context**
N/A

**Comment by TheStonedTurtle** [comment]
> If the player is carrying multiple clue scrolls on death, only one will be protected, even with multiple clue boxes. 

Do we know which clue scroll it will protect if you have multiple? I'm assuming the highest tier but not sure.

**Comment by TheStonedTurtle** [comment]
Per some testing with `fire truck73`:

If you have multiple scrolls in your inventory the highest tier will be protected. If you have both a clue scroll and reward casket for that tier the casket will be protected. 

The OSRS wiki has been updated to display this as well. I'll be looking into a fix for this today.

**Comment by dappersnapper456** [comment]
The clue box isn't kept on death, the clue scroll is? Therefore the client should display the highest tier clue scroll being kept on death while showing you would lose the clue box.

**Comment by Adam-** [comment]
fixed in #9161
