### ISSUE TITLE
[Entity Hider] Hide Toys

### ISSUE THREAD

**Issue by Committing** [runelite/runelite#9187]
**Is your feature request related to a problem? Please describe.**
Yes, when people thieve at ardy bank with a splasher, often a little troll will come strolling in and start dropping "Toy Mice" on top of the guard. This then means that you cannot left click the guard to pickpocket. Instead you have to right click everytime. There is no way to hide the toys to be able to continue pickpocketing. There are hundreds of people who all suddenly have to leave to another world. The troll soon follows...

**Describe the solution you'd like**
A new option of "Hide Toys" under "Entity Hider" plugin.

**Describe alternatives you've considered**
It doesn't really make sense to add it to any other category under Entity Hider.

**Additional context**
Multiple days in a row a single person comes in and messes up thieving for EVERYONE. There are a lot of people who thieve here: http://magaimg.net/img/89pr.png

A simple "hide toys" option would be extraordinarily useful

Thanks!

**Comment by deathbeam** [comment]
We are not adding support for hiding specific npcs/objects to entity hider, this was rejected in past

**Comment by Committing** [comment]
So that's the end of it is it? We just have to cope with trolls everyday all day... Can we not come up with a new solution instead of disregarding it and closing it?

**Comment by Nightfirecat** [comment]
You can report it ingame as a bug to Jagex, and they may fix it.
