### ISSUE TITLE
Item GE Price - Accuracy Improvement

### ISSUE THREAD

**Issue by FrontEndLou** [runelite/runelite#9192]
**Preface:** I _have_ spent time reading old feature requests and am aware that a similar issue was brought up previously and rejected.

**Issue:** OSBuddy users have been on the decline and especially bad lately, as many of the Pro users yearly subscriptions are up and switching to Runelite. The low amount of OSBuddy users makes the GE Price inaccurate and its been getting very bad lately. With a fraction of the users, many marchers - who's active trading patterns are crucial for accurate prices - can't use OSBuddy as their exact buy/sell points are too exposed now. The low and declining users also make price manipulations much easier and have been noticeably getting worse and worse lately. OSBuddy prices on low volume and/or high price items are barely relatively accurate more than they're mils off. Especially over the last few weeks, prices on anything 100m+ are consistently 1M-15M off.

**Solution:** I have a two ideas, either should work but the first is slightly more complicated to ensure price manipulation isn't an issue.

1) Imo the most effective solution would be to use the actively buying/selling offers data of **only currently logged on players.** Re-calculating prices on a similar time interval, you'd be taking snapshots of actual current offer prices, where using completed offers is always going to be old and potentially wrong. For exact price calculations, I'd suggest randomizing a value between the highest buy offer and lowest sell offer with a slight weighting (15-30%) in favor of the one with less offers. (I.e. A random item has 10 active buy offers between 11m-12m and 5 sell offers at 14m-14.5m you should expect it around a price of 13m with enough variance to not give away exact offers.)
2) Similar to above, track trade offers completed while the player is logged in. That will give accurate time stamps to prevent manipulation and you can average in the OSBuddy overall price, factoring in their quantities (buy+sell)/2 compared to Runelites. Basically take an average of the prices Runelite and OSBuddy report, scaled evenly by quantity.

Unfortunately I don't know Java or I'd be writing this as a merge request explanation myself later today. Prices are so bad lately with rampant manipulation and nownhuge volatile market swings that updating GE prices to a more accurate mode is needed.

**Comment by TheStonedTurtle** [comment]
A GE Tracker is a rejected feature (well, one not being considered)

> GE Tracker: There's no way to validate that any of the data coming from the client is legitimate, thus allowing for easy spoofing and price manipulation.

https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

**Comment by RALEx147** [comment]
How is that sufficient justification to not consider it. There is always a tradeoff in these situations, but the benefits of an accurate ge tracker could be worth considering it again. We could even poll it to the runelite playerbase/discord while providing the pros/cons of an implementation.

**Comment by TheStonedTurtle** [comment]
> but the benefits of an accurate ge tracker could be worth considering it again. 

How can it be accurate when the data can be faked...

**Comment by RALEx147** [comment]
Yes the data can be faked but with the trust of the player base, items with high trade volumes should have good data. There will always be a workaround for low volume items, or they can be ignored completely. Saying that data can be faked and completely ignoring the fact that, for the most part, this would be a good addition is disingenuous.

**Comment by abextm** [comment]
It will always be possible to fake any item, regardless of its volume or player trust. That's just how crowd sourced data works. The effort to weed out good from bad data is a cat and mouse game that we cannot win.
