### ISSUE TITLE
Fix Notification Popup Bar

### ISSUE THREAD

**Issue by cblakej** [runelite/runelite#9195]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

Fix Popup Notification i.e. Idle , Loot Drop

**Describe the solution you'd like**

Add Color and Highlight to Names , Drops

**Comment by Nightfirecat** [comment]
Can you please be more clear with this request? As-is, I don't have a good idea of what you're requesting.
