### ISSUE TITLE
Burnt Stew does not count towards "Burnt" counter in Cooking plugin

### ISSUE THREAD

**Issue by Cobodobo** [runelite/runelite#9196]
**Describe the bug**
Burning a stew does not count as burning food in the Cooking overlay.

**To Reproduce**
1. Enable Cooking plugin
2. Burn a stew
3. Note that the Burnt counter has not incremented

**Expected behavior**
Burning a stew should increase the burnt items counter.

**Environment (please complete the following information):**
 - OS: Debian
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.2

**Comment by xTheEc0** [comment]
Looking into this, but my cooking is too high to burn stews and I don't have an alt.  
What message in the chat window do you get when the stew is burnt?
