### ISSUE TITLE
Allow custom sound notifcations

### ISSUE THREAD

**Issue by Gum13** [runelite/runelite#920]
Different sound notifications other than windows notifiactions (runeloader does it perfect by adding almost a bell sound or a 'ting' that makes you always hear it during movies/games/shows)

**Comment by TomMartow** [comment]
Piggybacking onto this suggestion, a different sound effect for the Prayer and Hitpoints Threshold could be useful as well.

**Comment by Lalonde33** [comment]
You can change your notification sound in windows. fyi

**Comment by treycedits** [comment]
I've tried changing every windows setting and it still plays the default notif. sound. I muted windows system sounds, I muted Runelite sounds, I changed the notif. sound in system settings, I turned off the notif. sound in system settings, and for some reason it still plays the obnoxious default one. Any tips on how to fix this?

**Comment by Spuffeld** [comment]
I'd like to see a different unique notification noise, a change from whichever your standard windows notification is. It's a very common noise and when you're doing multiple things it can easily be missed.

Have customisation options would only be a plus in this regard, and separate sounds for health/prayer/minigame etc.

**Comment by Smileynator** [comment]
I was going to make this one, but once reading it i realize my issue is that i don't hear any at all.
Please add a way to hear notifications that do not go through windows notifications. I have all my system sound volume turned off permanently because windows sounds irritate me.

**Comment by Dovry** [comment]
An option to specify local .mp3 (or any audio format) or URL (gdrive, soundcloud, etc.), please.

**Comment by azzawoody** [comment]
is this in the making ?

**Comment by larkable** [comment]
> I was going to make this one, but once reading it i realize my issue is that i don't hear any at all.
> Please add a way to hear notifications that do not go through windows notifications. I have all my system sound volume turned off permanently because windows sounds irritate me.



> An option to specify local .mp3 (or any audio format) or URL (gdrive, soundcloud, etc.), please.

Also requesting that this be added. Thank you.
