### ISSUE TITLE
Woodcutting level icons around Hosidius area not updated

### ISSUE THREAD

**Issue by xTheEc0** [runelite/runelite#9204]
**Describe the bug**
Woodcutting level icons around Hosidius area not updated

**To Reproduce**
1. Open the map and go to Hosidius area (preferably on an account with 1 WC)
2. See that some icons are missing, some are slightly misaligned, some are in the middle of nowhere.

**Expected behavior**
Icons on the exact location of the tree

**Screenshots**
![Screenshot 2019-06-25 at 15 26 55](https://user-images.githubusercontent.com/24303281/60098535-66dd2600-975e-11e9-8a0f-70aa873a69d5.png)  
Notice Kingstown. North is an unmarked Magic tree. South is 2 unmarked Yew's.  
Then in Hosidius. Unmarked Magic threes, one south, one east.  
Then west (and slightly north) of Forthos Ruin is an unmarked Maple.  

![Screenshot 2019-06-25 at 15 27 40](https://user-images.githubusercontent.com/24303281/60098655-bc193780-975e-11e9-8cd0-63fac2d89081.png)  
Woodcutting guild. 2 misaligned yews and one without a tree.

![Screenshot 2019-06-25 at 15 28 55](https://user-images.githubusercontent.com/24303281/60098744-dfdc7d80-975e-11e9-813d-060bce28aba3.png)  
West of Tithe farm is icon without a tree

**Environment (please complete the following information):**
 - OS: Win
 - RuneLite version: 1.5.27
 - Launcher version: 1.6.2

**Comment by deathbeam** [comment]
Fixed in https://github.com/runelite/runelite/pull/9205
