### ISSUE TITLE
Multi-part chat messages

### ISSUE THREAD

**Issue by Trevor266** [runelite/runelite#9208]
It's always cumbersome to have to type out 2 or 3 messages to send a message to a player in a cc as an example

It would be really cool if the chat window in RuneLite supported long strings of text, up to a reasonable length of course to avoid spam, and it could then send maybe 2 or 3 messages one right after the other so that you can essentially send long messages to other players. I think 3 messages worth of text would be a reasonable max limit to avoid spam, maybe at a certain point the client could delay sending of longer messages so that it can't be abused.

**Comment by abextm** [comment]
I would be worried about this setting off some autotyper detection

**Comment by deathbeam** [comment]
This is blatant autotyping, so closing.
