### ISSUE TITLE
Collapsing right panel settings via a Command/Button

### ISSUE THREAD

**Issue by Gum13** [runelite/runelite#921]
Completely collapsing right panel, so theres nothing on the right hand side.
(Konduit also had a ctrl+f1 feature where it will hide the side panel, making your client symmetrical with nothing on the right hand side).

**Comment by ShaunDreclin** [comment]
Duplicate of #449 & #656
Related to #783

**Comment by deathbeam** [comment]
Closing as duplicate of #656
