### ISSUE TITLE
Add a clue map icon and a flashing arrow when the player has to get a strange device from jorral for the first time

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#9219]
I never had a strange device on my character, and when the clue scroll told me to visit Jorral the client didn't help me find out where he was/where I was meant to go to. I think this is a bug? I'm not sure. Obviously it hasn't been coded in the client.

**Comment by Nightfirecat** [comment]
fwiw the flashing arrow part of this request is already present, it's just the world map indicator that doesn't currently exist in the client.
