### ISSUE TITLE
Add drag-select feature to inventory

### ISSUE THREAD

**Issue by rvi857** [runelite/runelite#9220]
**Is your feature request related to a problem? Please describe.**
Usually when I'm level training cooking/smithing/fletching/crafting, I find many of the similar kind of item in my inventory at once. I currently have to go through a multiple-click action for every distinct sub-type of item (prompting me for kind of item, number of item, etc.), which can get repetitive/boring.

(E.g. If I have different raw foods in my inventory, I have to cook each kind of food separately, even if I'm using the same range to cook them)

**Describe the solution you'd like**
I'd like the option of drag-selecting a subset of the inventory grid, and using all of them at once.

(E.g. If I have many different kinds of logs, I can drag-select all of them and use them on a tinderbox)

I have thought about the scenario where a type of item can be used in multiple different ways to make different kinds items. In this case, when drag-selecting, I'd only prompt the user for the items that can be made by all sub-types in the selection. (E.g. if I use a knife on a drag-selection of many different kinds of logs, i'll only be prompted for making arrow shafts. If I use a drag-selection of iron and coal and mithril ore on a furnace, I'll only be prompted for making steel and mithril bars.)

I've also thought about the scenario where my level is high enough to act on some items but not others. In this case, I'd go ahead and make the lower-level items, and then send a message (either in the chat console or as a notification) that my level isn't high enough to make the other items.

Obviously there are countless more edge cases to consider, but it would be a really cool feature that could possibly be extended to drag-selecting in the environment as well (cutting down all the trees in a certain area, picking all the potatoes/wheat in a certain grid, etc.)

**Describe alternatives you've considered**
I thought about removing the user prompts for making items altogether, but they're much needed because of how dumb most of us are (the amount of times I accidentally cooked food I wanted to keep raw for a quest back in the day...yeesh)

**Additional context**
![Here's a possible idea of how it would look.](https://user-images.githubusercontent.com/4419069/60209334-07dfe580-9820-11e9-85be-57a99d67bca2.png)

**Comment by Hydrox6** [comment]
Doing anything like that with multiple items at once would be considered botting by Jagex, so it's not something we can add.

**Comment by rvi857** [comment]
Ah ok makes sense, thanks!
