### ISSUE TITLE
Ability to 'stress test' Runelite 

### ISSUE THREAD

**Issue by KyleStiers** [runelite/runelite#9221]
**Is your feature request related to a problem? Please describe.**
DCs and client crashes are a major annoyance to all and an ever present threat to hardcore ironmen in the game. I know a few people who encounter sporadic crashes of runelite who I've tried to help find a solution to with no luck, despite following the official recommendations of the RL time in terms of Java versions, memory amounts, etc. This greatly limits their confidence in doing dangerous content on their accounts.

**Describe the solution you'd like**
A way to stress test RL on a given system, i.e. a plugin that's effective purpose is to max out tracked xp/drops/etc that runelite is capable of tracking and run it in a way that will crash it if the setup is unstable. Or perhaps a 'low memory' option within tracking plugins that stores less data.

**Describe alternatives you've considered**
An alternate way to go about this could be to provide a custom download page, where you can simply check boxes for the plugins you'd like to include in your build. The main benefit of this (instead of simply disabling the plugin) would be to trim weight from the client. 

**Additional context**
Admittedly, I haven't dug deep enough into the client's code to know if simply disabling the plugin reduces the resources used overall. I simply seek to help out the HC community to enjoy RL. I imagine most of the stability issues are with the JVM on people's systems though, not runelite.

**Comment by Nightfirecat** [comment]
Per your post, most if not all outright crashes aren't at all related to RuneLite code, but are caused by JVM crashes, which we generally cannot avoid.

**Comment by Adam-** [comment]
With plugins off, the only resources they use is possibly memory in permgen space (is that still a thing?). I don't think it could possibly potentially destabilize the client having a plugin off, so I see no reason to offer builds with reduced plugins.

**Comment by abextm** [comment]
If Runelite is crashing in java code, submit a bug report to us. If Runelite is crashing in JVM code submit a bug report to your JVM vendor and ensure your hardware is working with standard stress test tools such as prime95 and/or memtest86+. If you are running out of memory (with the GPU plugin disabled) get more memory.

There isn't anything we can effectively stress test as a jvm application anyway.
