### ISSUE TITLE
Introduce a "soft barrier" like other mac applications to stop the client expanding/dragging below the taskbar on mac

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#9230]
![Screenshot 2019-06-27 at 17 55 43](https://user-images.githubusercontent.com/39419158/60284977-cd9c4400-9904-11e9-9b42-038dcebdfde7.png)

Often on Mac, I come across this problem where when I'm trying to resize the client so I can watch a youtube video/make space for a quest guide etc. I end up stretching the client below the task bar. It is very fiddly trying to fix this. You can drag the client below the taskbar as well which produces the same problem.

Can you make the client like other native mac applications where there is a "soft barrier" such that when you try dragging/extending the client below the taskbar, it stops the client unless you continue to expand the client/drag it (try other mac apps like notes/finder if you don't get what I mean). It would help out a lot as it is a very frustrating experience atm, especially on laptop where you're trying to squeeze in notes for a herb run or a youtube video.

**Comment by abextm** [comment]
Does this happen with [Runelite > Enable custom window chrome](https://github.com/runelite/runelite/wiki/RuneLite#enable-custom-window-chrome) disabled?

**Comment by dappersnapper456** [comment]
> Does this happen with [Runelite > Enable custom window chrome](https://github.com/runelite/runelite/wiki/RuneLite#enable-custom-window-chrome) disabled?

Ah there's a "soft barrier" now. Thank you.
