### ISSUE TITLE
dungeon crashing

### ISSUE THREAD

**Issue by chherman0** [runelite/runelite#9238]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
Almost every time i enter a dungeon/go into an instanced fight/ npc teleports me Runelite crashes

**To Reproduce**
1. Go to 'abyss'
2.  See error

**Expected behavior**
Issue to be fixed. Its been happening since two updates ago and was hoping it would have been fixed, but it hasn't.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ Windows]
 - RuneLite version: [e.g 1.5.27]
 - Launcher version: [e.g 1.6]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by abextm** [comment]
You need to give us logs or something. `It just crashes` is completely useless
