### ISSUE TITLE
Select right-click menu options via keyboard numbers, like chat options

### ISSUE THREAD

**Issue by ThimbleFire** [runelite/runelite#9239]
This'll probably be too game breaking but I'm going to suggest it anyway: Have a plugin that lets players select right-click menu options via keyboard numbers in the same way players can select chat options.

This would drastically speed up option selections which currently require constant mouse repositioning.

For example if a player wanted to level construction they would only need to mouse over the object they want to build or remove, right click, select the option via the keyboard number go from there.

**Comment by Nightfirecat** [comment]
Given that that would not be allowed even using something like AHK (as it is not 1-for-1), this would certainly be considered to be botting.
