### ISSUE TITLE
Valuable ground item color priority over highlighted ones

### ISSUE THREAD

**Issue by Elbcore3** [runelite/runelite#9241]
**Is your feature request related to a problem? Please describe.**
Ground items plugin works great, however i would really like the value tier colors to take priority over the one highlight color if it falls into these categories. The only choice is to either have all items above a value threshold become highlighted, meaning they will have the same (highlighted item) color OR you have to refrain from highlighting them to get the tier colors, but pass on all loot notifications by doing so.

**Describe the solution you'd like**
I want the item value tier colors to take priority over the highlighted color, so that if a highlighted item drops, it still gets colored (or to stand out maybe multiplied) according to the Low,Medium,High,Insane tier setups while still throwing its highlight drop notification.

**Describe alternatives you've considered**
I have considered using the "Highlight > value" option and set it to my Low/Medium value setting so that i can still get notifications on drops that i want to pay attention to, but it removes the fun "rarity" colors by making them all the same highlighted items color.

Alternative non-existent solutions would be to separate item notifications from highlighted items, then adding two settings to toggle notifications on valuable and highlighted drops.

**Additional context**
I really love the existing value tier color feature and it just bugs me that i have to choose between it and receiving notifications. Thanks for taking the time to read my suggestion!

![runelite suggestion](https://user-images.githubusercontent.com/10433839/60376898-feb66a80-9a11-11e9-9814-6ad3fcfed636.png)

**Comment by abextm** [comment]
You can configure the [in game valuable drops](https://oldschool.runescape.wiki/w/Options#Chat) then use the [Chat Notifications Plugin](https://github.com/runelite/runelite/wiki/Chat-Notifications) to notify on the `Valuable drop` text
