### ISSUE TITLE
Export drop tables from wiki as bank tags

### ISSUE THREAD

**Issue by Budfraiz** [runelite/runelite#9244]
**Is your feature request related to a problem? Please describe.**
No problem so far, just be handy to export the drop table for lizardman shamans (just an example) from the wiki and then import it into my bank tags

**Describe the solution you'd like**
a way to make a drop list off the wiki into a bank tag import list

**Describe alternatives you've considered**
nil

**Additional context**
nil

**Comment by LlemonDuck** [comment]
This can be accomplished with hub plugin [Bank Tag Generation](https://runelite.net/plugin-hub/show/bank-tag-generation)
