### ISSUE TITLE
Sync farming timers across multiple devices/clients

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#9245]
**Is your feature request related to a problem? Please describe.**
When I do farming on one device, the timers register that and give me correct timings. However when I log in on another devices, the new timers don't show up. I'm logged in with a Runelite account on both.

**Describe the solution you'd like**
When you're doing farming, when you've planted/inspected something the timers should sync with your Runelite account, so once you've logged in on whatever the device the timers will always show the most up to date timers depending on when a patch was last checked, regardless of device

**Additional context**
So I do a herb run or tree run on one computer. It shows me correct timings. But I end up logging in on a laptop later and because the timings it shows there are out of date I end up starting a herb/tree run, finding out I'm too early as timings haven't been updated.

**Comment by abextm** [comment]
Login to a [RuneLite account](https://github.com/runelite/runelite/wiki/Account)
