### ISSUE TITLE
Amulet of Chemistry/similar item replace overlay

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#9246]
**Is your feature request related to a problem? Please describe.**
When I'm making potions I'm always having to check my equipment spot to see if the amulet has run out. This is because when I'm making prayer potions for example if the amulet breaks on the 14th slot it's hard to tell whether the amulet needs replacing without checking equipment, because the message flies by the chatbox.
 
**Describe the solution you'd like**
An overlay telling me I need to replace the amulet. I know other amulets/rings have similar effects, so it would be nice if they could get similar treatment too.

**Comment by deathbeam** [comment]
You can just setup chat notifier. Or use item charges plugin, I think it has support for amulet of chemistry? not sure

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/pull/8836 looks like there is pr for this
