### ISSUE TITLE
Add Simple Brewery Timer

### ISSUE THREAD

**Issue by TheDoctorHu** [runelite/runelite#9250]
Hey everyone,

Most of us have certain daily routine while playing the game. (Herbs/Trees/Birdhouse/etc.)
I also added brewery to my daily routine, but i keep forgetting when i started or last checked my beer. Is there a possibility to add a brewery timer to the list of timers?

I know it is impossible to add the exact timer due the randomness of "Turning" mechanism of brewery. But the timers when turning will happen are set to a certain time. 
According to the wiki there are 3 stages for a vat of beer, the starting stage, an intermediate stage and the harvesting stage. During the starting stage, the beer requires 24 hours before reaching a Turning point. If the Turning is succesfull it will change colour and continue to the intermediate stage. If the Turning failed the beer stays in the starting stage and need another 24 hours before reaching a turning.
After reaching the intermediate stage, the beer only needs 12 hours to reach a turning point. If the turning during the intermediate stage was succesfull it will reach its harvesting stage. If not, it will need another 12 hours to reach a new turning point.
( oldschoolrunescape.fandom.com/wiki/Brewing )

Is it possible for runelite to add a timer for when a turning point will happen for your beer? 
This would help the brewers of runescape to not arrive just before the turning point, thinking it failed its turning, walking away and a minute later the beer turned into its harvesting stage. This could save a potential 12 hours of brewing time (or 24 hours if you are like me and only check daily).

**Comment by abextm** [comment]
duplicate #2648
