### ISSUE TITLE
Crashing entering abyss

### ISSUE THREAD

**Issue by chherman0** [runelite/runelite#9251]
Describe the bug
Almost every time i enter a dungeon/go into an instanced fight/ npc teleports me Runelite crashes. Just being in the abyss seems to crash as well. Hope these are the logs and help.
[launcher_2019-06-21.0.log](https://github.com/runelite/runelite/files/3342853/launcher_2019-06-21.0.log)
[launcher_2019-06-23.0.log](https://github.com/runelite/runelite/files/3342854/launcher_2019-06-23.0.log)
[launcher_2019-06-28.0.log](https://github.com/runelite/runelite/files/3342855/launcher_2019-06-28.0.log)
[launcher_2019-06-20.0.log](https://github.com/runelite/runelite/files/3342856/launcher_2019-06-20.0.log)

.

To Reproduce

Go to 'abyss'
See error
Expected behavior
Issue to be fixed. Its been happening since two updates ago and was hoping it would have been fixed, but it hasn't.

Screenshots

Environment (please complete the following information):

OS: [ Windows]
RuneLite version: [e.g 1.5.27]
Launcher version: [e.g 1.6]
Additional context
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
C:\Users\<your_user_name>\.runelite\logs on Windows and ~/.runelite/logs on Linux and macOS.

**Comment by abextm** [comment]
We need client logs, because the client is crashing, not the launcher.

**Comment by chherman0** [comment]
[client_2019-06-23.0.log](https://github.com/runelite/runelite/files/3343255/client_2019-06-23.0.log)
[client_2019-06-28.0.log](https://github.com/runelite/runelite/files/3343256/client_2019-06-28.0.log)
[client_2019-06-21.0.log](https://github.com/runelite/runelite/files/3343257/client_2019-06-21.0.log)
[client_2019-06-22.0.log](https://github.com/runelite/runelite/files/3343258/client_2019-06-22.0.log)

**Comment by Nightfirecat** [comment]
Are you still seeing this crash? If so, can you please post your client and launcher versions (found on the info tab in the side panel), your client logs, and any `jvm_crash` files you may have in your logs folder?
