### ISSUE TITLE
Show Remaining XP in skill calculator

### ISSUE THREAD

**Issue by lacaze** [runelite/runelite#9260]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
On the xp calculator, when u put two level in to see the xp it will give you both xp that each level has but it would subtract the xp to tell you how much xp you need till u would get to the level.
ex:
Mining -
Level: 2 (current level) = 83
Level: 5 (desired level) = 388
Remaining XP = 305

**Describe alternatives you've considered**
I usually have to open the calculator and type in the digits to subtract so i can find something like and xp per hour and calculator how long it would take to do something but having to type all the digits in, especially when it gets to the millions, is tedious and i feel like it can be easily resolved with a "remaining xp" variable somewhere. 

**Additional context**
I think this would be a small very useful function.

**Comment by Nightfirecat** [comment]
Remaining XP was added in #11509
