### ISSUE TITLE
Sell to store options

### ISSUE THREAD

**Issue by TheDoctorHu** [runelite/runelite#9262]
The mobile version of OSRS has a feature that the PC versions doesn't have. 
When you sell/buy in the shop on the mobile version, you can pre-set a certain amount to buy/sell. Is it possible for runelite to copy this feature?
If so, can there be a toggle option to keep the pre-set value even when you logout/worldhop?

**Comment by gregg1494** [comment]
While this is not a feature that RuneLite will implement, you could still post this one of the OSRS subreddits to see if Jagex would be in favor of implementing it.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features
