### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by tannert709** [runelite/runelite#9263]
whenever i put my info in and log in my client instantly closes.

**Comment by Nightfirecat** [comment]
Please post your client logs.

**Comment by Macca3006** [comment]
I've been having the same issue, how do I post client logs?

**Comment by Alexsuperfly** [comment]
https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client#client-crashing-on-login

**Comment by Macca3006** [comment]
Moving to Lumbridge worked. Thanks heaps!

**Comment by dekvall** [comment]
I am closing this, if the problem persists and you have information to add feel free to reopen the issue.
