### ISSUE TITLE
Fairy ring search

### ISSUE THREAD

**Issue by Javvee** [runelite/runelite#9271]
Fairy ring search filter does not find (BJS) "Islands: Near Zul-Andra" no matter what you type.

**Comment by abextm** [comment]
I can't reproduce this - Is this code in your log and not favorited?

**Comment by Javvee** [comment]
It is favored. Does that in a way kill the search option?

ke 3. heinäk. 2019 klo 16.49 Abex <notifications@github.com> kirjoitti:

**Comment by abextm** [comment]
Yes, favorited codes do not show up in the results because they are too different.
Duplicate #4419
