### ISSUE TITLE
Fun weapons not working with HiScore plugin enabled

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#928]
With the HiScore plugin enabled, the fun weapons (rubber chicken, snowball, prop sword, possibly others I didn't think of) actions do not work. When you whack/pelt/slash a player nothing will happen.

Disabling the HiScore plugin and restarting the client will allow you to perform these actions again.

**Comment by Adam-** [comment]
Fixed in 94c0e12d7fd25ebbbb08e8033161db0db3532ff7
