### ISSUE TITLE
Add LocalPlayerLoaded event

### ISSUE THREAD

**Issue by XrioBtw** [runelite/runelite#9284]
A LocalPlayerLoaded event is useful for e.g. knowing when the login event is completed.
When this event fires, requests for e.g. skill experience or similar are valid.
Could for example be used in ClientUI.java to add username to client title instead of using `clientThread.invokeLater(() -> { ... });`

**Comment by Nightfirecat** [comment]
How would this different in any way from triggering code upon `GameStateChanged` changing the game state to `LOGGED_IN`, when previously being `LOGIN_SCREEN` and `LOADING`?

**Comment by Nightfirecat** [comment]
Closing since this can already be achieved by following my comment above.

**Comment by XrioBtw** [comment]
@Nightfirecat I should have given some more information, sorry. I did try `GameStateChanged`, but that event fires way before e.g. `client.getLocalPlayer().getName() != null`. The aforementioned implementation in ClientUI.java is specifically implemented that way because `GameStateChanged` cannot work in that situation. My suggestion is a "when login event is actually finished" event.

**Comment by Nightfirecat** [comment]
So should we have an event just for that? As I said, we already have a "login event actually finished" event. What you're asking for is an event specifically for GameState reaching LOGGED_IN and the local player being non-null. Given that this requirement is so specific, it would be better to implement like it already is--by using `invokeLater` or null checks in the code subscribing to GameStateChanged.
