### ISSUE TITLE
Shift Anti Drag without Shift

### ISSUE THREAD

**Issue by sehnsehn** [runelite/runelite#9286]
Shift Anti Drag should be allowed to function without holding shift. This is a core feature of PVP clients and the only reason why many players do not use RuneLite for Clan Wars. RuneLite has features such as player indicator tile highlighting which would make RuneLite desireable as a PVP client, but it is currently a bad client for PKers because there is no anti drag. 

This feature is vital, because it stops food items from dragging while spam clicking pizzas in f2p, or while triple/quad eating in p2p during moments of panic.

This issue is under rejected issues because, 

"General Anti-Drag: People complained and we decided to remove it as no other clients have it (see #3200)"

Which is an invalid/incorrect reason, as the Exilent client supports general anti drag and it is a core feature for PKers. 

Proof: https://exilent.org/wiki/Anti_drag

Instead of removing the feature, it should be a check box that is not enabled by default, so as to not interfere with PVM players. There is currently no valid reason listed why this feature should not be in RuneLite. The code is already written, and disabling it by default would address PVM players' concerns with the feature while allowing for it to be used by bossers and Pkers.

**Comment by deathbeam** [comment]
It was removed intentionally due to community backslash and also decision of admins/people in Discord. We will not be bringing it back.

Pking 3rd party clients are also not excuse to implement the feature, because many of them have features that are against Jagex rules, or what Jagex requested to be removed in past.
