### ISSUE TITLE
Unable to load client

### ISSUE THREAD

**Issue by hrmb26** [runelite/runelite#9289]
I can't seem to load the client I have reinstalled multiple times and nothing works
[client.log](https://github.com/runelite/runelite/files/3362483/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3362484/launcher.log)

**Comment by Nightfirecat** [comment]
The error in your client logs is the same as the one from [our troubleshooting wiki page](https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client):

> If you see `Error loading RS!` in the `client.log` you are unable to get the osrs client from jagex. The error will be accompanied by an exception
>
> -  `SocketTimeoutException: timeout` - this means the connection took too long to either connect or receive any data, most of the time caused by a slow or inconsistent internet connection, you can try resetting your network or maybe using a VPN.

**Comment by Nightfirecat** [comment]
Closing as no updates have been posted. Please reply back if the above troubleshooting steps did not change anything.
