### ISSUE TITLE
Removing GPU fog Cap?

### ISSUE THREAD

**Issue by CorzappyRS** [runelite/runelite#9291]
Right now I don't really see a reason as to why there is a cap on the fog amount.
I feel like removing the cap could add a good challenge to the game by increasing it to very high amounts. It doesn't seem like too much to ask for IMO and It would be great if it could go back to the way it was :)

**Comment by Nightfirecat** [comment]
I don't see a good reason to un-cap it. If you'd like to override this, you're welcome to run your own build of the client with that cap value changed or removed entirely.
