### ISSUE TITLE
Motherlode rock obstacles are not being marked after logging in or entering the area

### ISSUE THREAD

**Issue by Quasindro** [runelite/runelite#9301]
**Describe the bug**
The rock obstacles in MLM do not get marked when a player logs in or has just entered the area.

**To Reproduce**
1. Be in MLM
2. Stand near any rock obstacle
3. Log out
4. Log back in
5. The obstacle tiles are not marked in red, even though they should be

**Expected behavior**
The rock obstacles' tiles should be marked reliably when the config setting is on

**Screenshots**
After logging in:
![image](https://user-images.githubusercontent.com/10108473/60766475-82bfc080-a0aa-11e9-8a5a-b40c56060f70.png)

When the rocks respawn after being broken
![image](https://user-images.githubusercontent.com/10108473/60766481-b569b900-a0aa-11e9-80e1-3ddd68637a6e.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.29-SNAPSHOT
 - Launcher version: Unknown

**Additional information**
I already have an idea as to what may be wrong in the plugin, so I will submit a small PR shortly.

**Comment by Adam-** [comment]
fixed in #9302
