### ISSUE TITLE
Enabling Reshade support

### ISSUE THREAD

**Issue by KyoSohma** [runelite/runelite#9305]
So I know that OSBuddy is able to do this with their opengl mode, and since the the GPU plugin utilizes OpenGl, I figured Runelite would be able to work as well. When I install reshade into runelite, it doesn't even let me open the gui for reshade. I really want to be able to use this feature, but I don't want to have to switch over to OSBuddy.

https://www.reddit.com/r/2007scape/comments/7s14ab/defactos_old_school_runescape_hd_v11_osbuddy_pro/

**Comment by abextm** [comment]
If an external application is unable to interact with our process, its the external application's bug. Report this feature request to them.
