### ISSUE TITLE
Jvm Crashes when starting up 

### ISSUE THREAD

**Issue by smwiss326** [runelite/runelite#9309]
**Describe the bug**
The JVM crashes when I try to start up runelite. I am occasionally succeeding in loading all the way to the login screen but 90 percent of the time it crashes at the connecting to update section. I've tried deleting the repository2 file, as well as all of the jars independently, I've updated java, I've reinstalled Runelite, I've turned my computer on and off again etc.. dont know what to do next. 

**To Reproduce**
  attempt to run runelite

**Environment (please complete the following information):**
 - OS: Windows 10 64
 - RuneLite version: 1.5.2
 - Launcher version: 1.5.2

[client_2019-07-06.0.log](https://github.com/runelite/runelite/files/3366202/client_2019-07-06.0.log)
[launcher_2019-07-06.0.log](https://github.com/runelite/runelite/files/3366203/launcher_2019-07-06.0.log)
[hs_err_pid6436.log](https://github.com/runelite/runelite/files/3366204/hs_err_pid6436.log)

**Comment by abextm** [comment]
Try disabling `ASUS GPU TweakII`, and if that fails, try [disabling hardware acceleration](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration)

**Comment by smwiss326** [comment]
ur a legend m8.
Uninstalling GPU tweakII fixed it.
Do you want me to add this to the readme or anything for you?

**Comment by abextm** [comment]
It might be worth adding to https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client. It also is probably worth reporting to asus.

**Comment by smwiss326** [comment]
k cool thanks again.
