### ISSUE TITLE
Stash Outline Color

### ISSUE THREAD

**Issue by Spud1y** [runelite/runelite#9333]
Issue: The Stash tile outline is always red. Because of this, I still have the issue where I forget to put my things back into the stash before quickly teleporting away to get to the next location.

Potential solution: When the stash is full have the outline be green. When it is empty have it be red. This way there is a visual that stands out when you don't place your items back into the stash

**Comment by Nightfirecat** [comment]
We don't currently have a way to track the filled state of stash units. We do have an open request for that here: #1662, and I'm sure whenever we implement the feature, we'll extend the highlight color of the stash unit overlay to display different colors based on that state.
