### ISSUE TITLE
Item Identification Suggestion (Fishing Nets, Greegrees, Bones, etc.)

### ISSUE THREAD

**Issue by mparsakia** [runelite/runelite#9338]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
Item Identification should also tag fishing nets, as they are hard to distinguish between small, big, drift net, etc. Additionally waterskins (0-4) all have the same model but no graphical way to distinguish what has what amount in the bank, but Item Charges does show this while in inventory. Bones as well are hard to distinguish between what types are held as many use the same graphic model. Same logic for monkey greegrees as they are tinted but hard to tell which is which although these are so rarely used I don't know if its worth adding the dev time for them.

**Describe alternatives you've considered**
Alternatives could be to just tint the items different colors with an overlay or have the item highlight tags show in the bank as well, but this seems like a best fit for the Item ID plugin.

**Additional context**
N/A

**Comment by Dava96** [comment]
In what situation would you have more than one net/Bone in your Inventory?

**Comment by mparsakia** [comment]
Most of the time I use this feature to withdraw the correct items out of the bank faster. I suppose it may help those Ironman players who can’t use bank either.
