### ISSUE TITLE
Suggestion: Hide scroll bar in chatbox when transparent.

### ISSUE THREAD

**Issue by TomMartow** [runelite/runelite#934]
It has been mentioned a few times by myself and others on Reddit, and it can get in the way sometimes when you are trying to do certain tasks like agility.

You can still scroll up and down the chatbox with the middle button on the mouse.

https://imgur.com/a/7NPxz

**Comment by deathbeam** [comment]
I think this was solved by jagex adding option to move scrollbar to the left. Reopen if this is still needed.
