### ISSUE TITLE
Switched monitors now runelite cant find my graphics card

### ISSUE THREAD

**Issue by goon123** [runelite/runelite#9342]
Hello I've recently switched monitors and now every time i try to open the client it loads half way then says "Open gsle error cannot find intel graphics" the thing is my computer uses a navidia graphics card so im not really sure what to do about it. Saw an earlier post with a similar problem but the solution was switching hdmi ports however i only have one. Any help would be much appreciated thanks

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest release of RuneLite or join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.
