### ISSUE TITLE
Emote Clues don't show clue location in overlay

### ISSUE THREAD

**Issue by dappersnapper456** [runelite/runelite#9355]
![Screenshot 2019-07-12 at 23 18 21](https://user-images.githubusercontent.com/39419158/61161382-6d5bf380-a4fb-11e9-89c6-d7630b105457.png)

"Shantay's Awning" is around the Shantay Pass

https://oldschool.runescape.wiki/w/Treasure_Trails/Full_guide/Medium#Emote_clues

**Comment by Alexsuperfly** [comment]
open the map

**Comment by Nightfirecat** [comment]
I think the issue is that it doesn't have a "Location" line in the overlay panel, which I know I've found to be annoying in the past as well.

**Comment by xDemoN** [comment]
FYI, none of the emote clues use the "Location" line the overlay panel
