### ISSUE TITLE
Swapping rub / teleport with wear / wield does not work

### ISSUE THREAD

**Issue by XrioBtw** [runelite/runelite#936]
Swapping rub and wear option on e.g. Amulet of glory in #627 is not working.

Using the following (with `@Hook(value = "addMenuEntry", end = true)` in class169.java)
```
@Subscribe
public void onMenuEntryAdded(MenuEntryAdded event)
{
    if (client.getGameState() != GameState.LOGGED_IN)
    {
        return;
    }

    System.out.println(event.getOption());
}
```
you can see that Rub, Wear and Drop options are missing if you hover over an amulet of glory in the inventory.

Through comparison with `client.getMenuEntries()` it looks like only the Use and Examine options are added, while the other options have already been added to the MenuEntry[]. So it looks like most menu entries for inventory items are hard coded.

**Comment by ShaunDreclin** [comment]
I just ran into this myself when I was trying to add functionality for the Silver sickle(b).

```
INFO  n.r.c.p.m.MenuEntrySwapperPlugin - walk here: 
MenuEntrySwapperPlugin - use: <col=ff9040>Silver sickle(b)
MenuEntrySwapperPlugin - examine: <col=ff9040>Silver sickle(b)
```
What's even weirder is there isn't even a walk here option in the right click menu when you mouse over inventory items.

**Comment by SomeoneWithAnInternetConnection** [comment]
Looks like the method we currently hook, `addMenuAction`, is the method that's used to add all menu entries *aside from menuEntries defined in ItemDefinitions*. Hooking `method193` instead fixes the issue, but I suspect that inlining-related shenanigans may be required to make that stick.
