### ISSUE TITLE
Add the HAM hideout trapdoor pick-lock option to the menu entry swapper

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#9366]
![image](https://user-images.githubusercontent.com/34870401/61176796-8cc05280-a5c7-11e9-9792-6f4f569d4e63.png)

It'd be nice for grinding easy clues.

**Comment by isaacph** [comment]
I tried to solve this by adding a swap to MenuEntrySwapperPlugin.java, but I found that the client forcibly orders options of type 3 (open's type) over options of type 1001 (pick-lock's type), so using client.setMenuEntries() here does not work. I am not sure if this is doable with the current API.

**Comment by pirak3** [comment]
I looked at it as well and came to the same conclusion. The current client doesn't allow swapping those 2 specific types.

**Comment by Adam-** [comment]
added in 3fd1ba69500b3cd14ece4e1163e9e7a428d10935
