### ISSUE TITLE
Real-time friends location on world map

### ISSUE THREAD

**Issue by dustingriffie** [runelite/runelite#9369]
Not even sure if this would be possible, but a way for you to open the world map and if your friends have the plugin enabled, show where they are in game if on the same world. Would really add the MMO feel. Maybe even for clans as well.

**Comment by jorisrs** [comment]
Yes it would be possible if your friends have the plugin aswell. Sure it’s a fun gimmick but not really something that is worth putting time into in my opinion

**Comment by Unmoon** [comment]
This is already a part of the party plugin. I doubt we would want to do similar for just friends, since it would not be very obvious behavior, and be an unwelcome addition for PKers trying to avoid being scouted. Most MMOs don't show your friends on world map, only party members.

**Comment by Nightfirecat** [comment]
As unmoon mentioned, this is already a feature of the discord party plugin.
