### ISSUE TITLE
[[Item Identification Plugin]] Add sacks/baskets of farming crops

### ISSUE THREAD

**Issue by Lorentary** [runelite/runelite#9371]
The title is pretty self explanatory

You cannot currently see the difference between **an empty sack**, a sack of **potatoes** (**10**), a sack of potatoes (**9**) and a sack of **cabbages** (10) and... (ok you get the idea)

**Comment by jachymb** [comment]
You can see it in the inventory with the item charges plugin. You cannot see it in the bank, as far as i know.
