### ISSUE TITLE
Entrana river fishing not showing spo tiles

### ISSUE THREAD

**Issue by doom777** [runelite/runelite#9375]
**Describe the bug**
River fishing spots in Entrana are not marked even when fly fishing rod is in inventory

**To Reproduce**
1. Go to Entrana
1. Have Fly FIshing rod in inventory
1. Approach the river fishing spots
1. See no fishing tiles

**Expected behavior**
fishing tiles show up like in other fly fishing spots

**Screenshots**
![image](https://user-images.githubusercontent.com/632448/61195253-ce6aff00-a694-11e9-9936-c3515a9f2062.png)

**Environment (please complete the following information):**
 - OS: Win10
 - RuneLite version: 1.5.28
 - Launcher version: 1.6.0

**Comment by psikoi** [comment]
@deathbeam good first contribution?
