### ISSUE TITLE
Runelite Chat Bug

### ISSUE THREAD

**Issue by CoolJule** [runelite/runelite#9379]
Hello, 
I hope someone can help me out. Since I've installed Runelite (I've also tried uninstalling and reinstalling), when I use the chat box and accidentally try to type in caps, i.e. LOL, using shift to create the uppercase, my game just crashes. 

This is what it looks like:
![rsbug1](https://user-images.githubusercontent.com/52929304/61232825-31907c00-a6fd-11e9-99eb-9fa039353e50.png)
![rsbug2](https://user-images.githubusercontent.com/52929304/61232829-32c1a900-a6fd-11e9-9a79-9440f2f6e258.png)
![rsbug3](https://user-images.githubusercontent.com/52929304/61232832-33f2d600-a6fd-11e9-9c64-3f3274ce18fd.png)

So, in the full screen versions, it becomes half frozen, I can only move my character and zoom in/out. 
In the half screen version, I can move my character but I lose all features EXCEPT the runelite sidebar, that seems to be working fine. 
It's only happens when I use shift to type in capital letters in chat. It doesn't happen when I use shift for drop clicking or anything else. 
The only solution I have right now is to close out and reopen my game, which stinks 'cause you lose your tracking and chat history.

Also, I have a smaller issue of, specifically with trees, time tracking not being synced. The sidebar will say done, so I go to that tree patch and find out it actually isn't done and then runelite will update the sidebar with the "correct information" (although, earlier today it corrected it to 4 hours for my redwoods to be done, and then 4 hours passed and it said "done" and then I go to the patches and it has 9 hours left).

I hope someone can help me! 
Thanks :)

Edit: As I was putting this post together, I kept runelite logged in and open in the background and this is what happened: 
![rsbug4](https://user-images.githubusercontent.com/52929304/61233328-4e797f00-a6fe-11e9-8b10-f2f7f3aecce0.png)

**Comment by winterdaze-rs** [comment]
Open a separate issue for the problem with farming timers. Also, can you include your client logs? If you can't find them, right click the screenshot button and go to that folder, then from there try to find the .logs folder.

**Comment by CoolJule** [comment]
Wow! Thank you so much for responding! Yeah, here you go: 
[launcher_2019-07-15.0.log](https://github.com/runelite/runelite/files/3417817/launcher_2019-07-15.0.log)
[client.log](https://github.com/runelite/runelite/files/3417819/client.log)

**Comment by CoolJule** [comment]
Let me know if that worked and what else you might need!

**Comment by Alexsuperfly** [comment]
youd need the log from the day it happened

**Comment by CoolJule** [comment]
[client_2019-07-15.0.log](https://github.com/runelite/runelite/files/3417831/client_2019-07-15.0.log)
[launcher_2019-07-15.0.log](https://github.com/runelite/runelite/files/3417833/launcher_2019-07-15.0.log)

**Comment by Alexsuperfly** [comment]
Nothing stands out to me in there, I would expect it to be some sort of problem with your system then.  Whether that's how it handles java or otherwise i cant say because I've never seen something of this sort before.  You can look for jvm logs which would have been placed in the Runelite install directory located in `%localappdata%/runelite` or `%TEMP%` and named something like `hs_err_pid#####`.

**Comment by CoolJule** [comment]
So weird. When I looked at the client log, I would have figured the error message pointed to something! It's just so odd that it only happens when I type in chat and use Shift for caps. 

Sorry, you've kind of lost me though, I've been spending the past 15 minutes trying to find the runelite install directory to no avail LOL... :(

**Comment by Alexsuperfly** [comment]
You can paste the strings I highlighted into the address bar of your file browser and it will take you directly there.

**Comment by CoolJule** [comment]
Alright, so sorry to be a complete idiot. When I pasted "%localappdata%/runelite" this is what comes up: 
![rl1](https://user-images.githubusercontent.com/52929304/61650547-f30d3b00-ac81-11e9-943d-2bd87a3600e0.PNG)

I'm not sure where to go from there ^

And when I do %temp%:
![rl2](https://user-images.githubusercontent.com/52929304/61650636-23ed7000-ac82-11e9-8af5-8991c7908989.PNG)

And I'm not seeing "hs_err_pid#####" in %TEMP%

**Comment by Alexsuperfly** [comment]
that means it never did create one

**Comment by Alexsuperfly** [comment]
only other thing i can think of is do this https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration

**Comment by CoolJule** [comment]
It's funny because I did try to do that :( unless I completely did it wrong. When I did it, it created a Runelite(2) shortcut on my desktop, and the properties show like "mode=off" at the end, exactly like the gif.  :(

**Comment by Nightfirecat** [comment]
No additional information has been provided for quite some time so I am closing this. If the problem persists feel free to reopen the issue.
