### ISSUE TITLE
Add ability to unbind/rebind CTRL to run

### ISSUE THREAD

**Issue by xanderqixter** [runelite/runelite#9393]
Is your feature request related to a problem? Please describe.
Holding CTRL and left clicking, activates Run for that particular click. This is useful and/or needed for certain PvM activities, however for some of users that button is used by other programs and causes unintentional side effects when pressed.

Describe the solution you'd like
Either a toggle on/off for this function, or the ability to bind a different key to this function

Additional context
Personal context, i have been using CTRL as a push to talk in various programs for the past 11 years. it negatively impacts my experience when after a couple sentences are uttered to my chat, i have depleted my run energy, and/or potentially left a safe spot on a tick I was not prepared for.

**Comment by xanderqixter** [comment]
It is currently possible to Unbind, but Preferably a rebind would be possible
Currently, you can use the Key Remapping plugin to "disable" the function by doing something like this.
[https://i.imgur.com/TgFvhcu.png](url)

However then you have disabled a functionality that is useful in some scenarios and in my opinion would be better served to rebind it

**Comment by deathbeam** [comment]
This is outside of scope of key remapping plugin
