### ISSUE TITLE
Allow plugins to define meta tags that the plugin searchbar can work off of

### ISSUE THREAD

**Issue by whaevr** [runelite/runelite#9396]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

Sometimes its difficult to remember what plugin a particular feature is located in, the name of the plugin does not always make this obvious. I've had to google describing certain plugin features in the past, find the announcement of the plugin or the release notes and grab it's name from there.
 
**Describe the solution you'd like**

If plugin creators could define meta tags, such as "seeds" on Item Identification it would be more intuitive to find/leverage them using RuneLite's plugin search bar

**Comment by deathbeam** [comment]
We already have this
