### ISSUE TITLE
Tree respawn timer

### ISSUE THREAD

**Issue by ThomasHoltkamp** [runelite/runelite#9397]
I feel like we’re missing something, when mining rocks we see a respawn timer but when cutting trees we don’t, this is really the case with yew+ level trees

I would like to see the exact same solution added to this like the one added to ores, but maybe a slider to change the size of the timer circle or a number only view (time in text)

**Comment by Adam-** [comment]
added in 3fd8fb79aa171c924af5f3cb577ec9dce404e4da
