### ISSUE TITLE
AFK logout causes a textbox over the login screen 

### ISSUE THREAD

**Issue by fiya1d** [runelite/runelite#9408]
**Describe the bug**
After being logged out from AFK ~5mins, a box shows "you have been disconnect from server" over the login screen. 

**To Reproduce**
1. AFK and wait until it logs out. 

**Expected behavior**
Shows a box that says "you have been disconnected from server" 

**Environment (please complete the following information):**
- Win 10
- 1.5.29 Release

**Comment by abextm** [comment]
this is something jagex has changed
