### ISSUE TITLE
Remove drawing to minimap when "hide minimap" plugin is enabled

### ISSUE THREAD

**Issue by winterdaze-rs** [runelite/runelite#941]
Examples: shouldn't draw player name and fishing spots to map when the minimap is hidden. Not sure what other plugins draw to the map.

**Comment by SomeoneWithAnInternetConnection** [comment]
Needing to add a check for this in every plugin that ever touches the minimap graphically seems kinda error-prone. In the case of the fishing plugin, this is probably decent opportunity to replace our slightly-sketchy "yeah, we'll just do the math ourselves and draw some dots over top of the minimap" with actual calls to the builtin "draw a dot plz" methods.

It'd be pretty cool if there was a similar text-drawing thing we could take advantage of for the player names, but unfortunately I can't think of any instances where they draw text on the minimap in the course of normal gameplay.
