### ISSUE TITLE
Add Collapsable Loot Tracker Entries

### ISSUE THREAD

**Issue by OliverBroadbent** [runelite/runelite#9416]
**Feature Description**
Add the ability to collapse per monster loot in the loot tracker plugin.

**Describe the solution you'd like**
Left-clicking the monsters name in the loot tracker should "collapse" the items looted for that monster. Left-click again to reveal again.

**Additional context**
If you're asking why this is useful, well I just finished a full day of slayer and my loot tracker scrolls for days. I want to shorten that list so it's easier to navigate (for example: i want to find all of my loot for the brimstone chest), while keeping my "total value" at the top the actual total value. I can't use "reset" for that.

**Example Screenshots:** https://imgur.com/a/CCwr7b3

**Comment by psikoi** [comment]
I'll do it

**Comment by Serpa88** [comment]
> I'll do it

I already talked to @psikoi about also having an attempt at this, in case anyone was wondering.
