### ISSUE TITLE
Bank Tags not remembering last open tab

### ISSUE THREAD

**Issue by ThimbleFire** [runelite/runelite#9433]
![](https://i.imgur.com/qXvCgzV.gif)

Went I open my bank and select a tab, then close my bank and re-open the bank it doesn't automatically open to the earlier selected tab. This used to work but for some reason its not any more.

I've tried disabling the plugin and its options, and re-enabling them but that didn't fix it.

**Comment by raiyni** [comment]
duplicate #9401

**Comment by Alexsuperfly** [comment]
duplicate of #9401
