### ISSUE TITLE
Client keeps crashing with HW accel. on

### ISSUE THREAD

**Issue by pr0f3ss** [runelite/runelite#9434]
**Description:** 
Client crashes or freezes after a few minutes (log says client crashed after 18 minutes). It seems that turning off HW acceleration has fixed the client from crashing for now. Full reinstallation of client and reformatting the drive has not helped fix the issue.

**Cause:**
EXCEPTION_ILLEGAL_INSTRUCTION
Problematic frame:
sun.reflect.annotation.AnnotationInvocationHandler.invoke(Ljava/lang/Object;Ljava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object; (277 bytes) @ 0x000002de68fa1140 [0x000002de68fa07a0+0x9a0]

**System:**
OS: Windows 10.0 , 64 bit Build 17134 (10.0.17134.753)
see log for more

**Crash log file:**
[hs_err_pid1648.log](https://github.com/runelite/runelite/files/3419353/hs_err_pid1648.log)

**Comment by Matsyir** [comment]
Not all hardware viably supports hardware acceleration. If it works well with it disabled, just keep it disabled. The guide to turn it off is recommended/referred to frequently because of this, many people have to keep it turned off for RL to work properly on their system.
