### ISSUE TITLE
Lag at olm (stuttering/slowed down animations/freezing), possible memory issue?

### ISSUE THREAD

**Issue by ghost** [runelite/runelite#9437]
I experience some sort of lag or stuttering while killing olm. Sometimes the screen will freeze for just a second. Nowhere else in runescape do I have this problem and it only happens in the olm room. The rest of the raid runs smooth.

I don't know how to produce this error. It doesn't happen 100% of the time. I've tried different worlds and playing at different times and it happened all the same. The issue doesn't occur while playing on the official client. 

I don't use animation smoothing or the GPU thing. I tried GPU last night but that made my computer crash during the raid (at shamans room). I did that in combination with turning hardware acceleration off, following the guide on here. I have no idea what happened because I have very little tech knowledge.

**Expected behavior**
It should run smooth like the rest of the raid but it usually doesn't. 

**Environment (please complete the following information):**
 - OS: Windows
-Runelite Version: the latest, just tried reinstalling but it still happens. 

Edit:
When I use 'displayfps' it gives me a constant 50 fps, even when the stuttering is happening. The memory part however constantly goes up in red (450k+) before resetting again, whereas normally it stays between 200-250k when using runelite. After fully rebooting my computer this problem fixed itself but it seems keep coming back after some time. 

When this problem does happen nothing really changes except for during the olm fight because that's where it's the most noticeable. The increased memory usage happens all over runescape.

**Comment by Nightfirecat** [comment]
Closing because this issue is very stale. If this continues to be an issue, [please open a discussion in the Q&A category](https://github.com/runelite/runelite/discussions/categories/q-a).
