### ISSUE TITLE
Mining timer is wrong in Miscellania coal rocks.

### ISSUE THREAD

**Issue by NickMendes** [runelite/runelite#9452]
While mining coal rocks for favour I noticed that the timer on coal rocks once you mine them is quite off, they respawn when the timer is 25% through.

![rcLs1q3](https://user-images.githubusercontent.com/35135520/61853793-a65d7600-aeb4-11e9-9f5c-8800eabf5a7f.gif)

**Comment by dekvall** [comment]
This can be closed. #9467 is merged.
