### ISSUE TITLE
Feature-Request Gauntlet attack counter

### ISSUE THREAD

**Issue by marvinwz** [runelite/runelite#9464]
The Gauntlet boss switches attack style every 4 attacks. A counter for this would be nice just like Demonic Gorillas.

**Comment by nateisonfire** [comment]
Probably not going to happen. We don't have a counter for hydra, and the demonic gorillas overlay is a very argued topic.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features `Any new high-end PvM boss plugins`

So i guess this settles it.

**Comment by Adam-** [comment]
:+1: The gorillas counter is very controversial and I don't see why this wouldn't also be. I think that the broader userbase wouldn't like to see this type of plugin.
