### ISSUE TITLE
Artisan Skill by Tedious

### ISSUE THREAD

**Issue by Tsukaime** [runelite/runelite#9484]
**Describe the solution you'd like**

https://www.youtube.com/watch?v=6MdnwG5H8a4
A youtuber created the concept of the artisan skill, + wrote the majority of code required. Would love to see it implemented as an extension

**Describe alternatives you've considered**
Continuing to use his spreadsheet works, but automatization would be nice. 

**Additional context**
https://docs.google.com/spreadsheets/d/1BoAGtWsrN-zcL2k1yTKCPyQxAuTWFYKAxrauu5dv0jo/edit?usp=sharing

**Comment by Kamielvf** [comment]
This seems out of the scope of what RuneLite is, therefore closing this issue. The creator has already provided a way of doing this yourself - and it seems fitting to use that instead.
