### ISSUE TITLE
Add toggles to XP Orb hovered line items display

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#9497]
Additional context

on the xp orb we should be able to see what we want to see what I mean is right now whenever we move out mouse on top of the xp orb we see this which is located on the left side of the image underneath.
image
![image](https://user-images.githubusercontent.com/37475765/62008857-c197e200-b14f-11e9-9301-9383f648b768.png)

but I want to pick what I want to see out of all the options which are;

**name of skill, current XP, Kills Left, XP Left, XP per hour.**
we should be able to pick which ones we want to see out of the list above.
so, for example, you can make a plugin at the 'configuration' which is called 'XP Orb'
and in that XP Orb you can have it saying
do you want to see **name of skill,**
do you want to see **current XP,**
do you want to see **Kills Left,**
do you want to see **XP Left,**
do you want to see **XP per hour,**

or you don't have to have it saying 'do you want to see' you can just have the enable/disable plugin which is this
![image](https://user-images.githubusercontent.com/37475765/62008828-9dd49c00-b14f-11e9-8ed8-31a9947a4341.png)

example of this 
name of skill ![image](https://user-images.githubusercontent.com/37475765/62008890-163b5d00-b150-11e9-9fb7-7f5d1b73f0f5.png)
current XP ![image](https://user-images.githubusercontent.com/37475765/62008890-163b5d00-b150-11e9-9fb7-7f5d1b73f0f5.png)
Kills Left ![image](https://user-images.githubusercontent.com/37475765/62008890-163b5d00-b150-11e9-9fb7-7f5d1b73f0f5.png)
XP Left ![image](https://user-images.githubusercontent.com/37475765/62008890-163b5d00-b150-11e9-9fb7-7f5d1b73f0f5.png)
XP per hour ![image](https://user-images.githubusercontent.com/37475765/62008890-163b5d00-b150-11e9-9fb7-7f5d1b73f0f5.png)

**Comment by mfboulos** [comment]
I'll leave it up to the runelite dudes to mark this one as a feature request if necessary. However, I can give you some insight based on my quick look at the plugin:

 1. `Skill name` and `Current XP` are _always_ rendered within the tooltip.
 2. `[actions] left`, `XP left`, and `XP per hour` are only rendered if there is an XP goal that your current XP does not exceed. If you do not have an XP goal set, the default seems to be the XP of the next level.

**Comment by Darkkgreen** [comment]
But we're still able to change the drawTooltip function anyway. I'm going to take a look at it.

**Comment by Darkkgreen** [comment]
What should happen when we disable every info inside the info box? I mean, we already have a 'Enable Tooltips' option.

Maybe we could have the option disable the `XP Left`, `XP per hour `and `Actions left`, but not the `Skill name` and `Current XP` since we already have this tooltips option.

**Comment by permedd** [comment]
i think all the option should be on the option which is called, 'Xp Orb' and in there it should have enable/disable XP Left, XP per hour and Actions left, and if there is skill name and current xp option to disable/enable then it should also be in the 'Xp Orb'.
they should all be in one category so its easier to find it and use it etc.

**Comment by Darkkgreen** [comment]
There's actually no option called `XP Orb` afaik.

**Comment by permedd** [comment]
Yeah i know, well i didnt say make one but i was trying to say make one called ‘Xp Orb’ on the configuration.

**Comment by Darkkgreen** [comment]
I'll see what I can do

**Comment by Darkkgreen** [comment]
@permedd I left `Skill name` and `Current XP` as permanent inside the tooltip box

**Comment by permedd** [comment]
Ahh i think it should be, optional to players, if they want to see it or not to be honest, so players are more free to pick what they want which is good.
Some pkers might just want to see current xp or some might just want to see the orb. Because the box is little big so yeah.

**Comment by Darkkgreen** [comment]
If you don't want to see the box, you can disable the `enable tooltip` option. I left those as permanent because they complete the information XP Orb gives you (Skill and % til next level)
