### ISSUE TITLE
Emote master clue item helper - tzhaar gem store

### ISSUE THREAD

**Issue by winterdaze-rs** [runelite/runelite#9510]
**Describe the bug**
Clue step: Cry in the Tzhaar gem store. Beware of the double agents! Equip a fire cape and a TokTz-Xil-Ul.

Regular infernal cape, fire max cape, and infernal max cape also count for this step, so the item checker should also show a checkmark if you have any of those in your inventory.

**Comment by Darkkgreen** [comment]
Looking into it
