### ISSUE TITLE
drop tile marker cache.

### ISSUE THREAD

**Issue by martijn26** [runelite/runelite#9514]
**Is your feature request related to a problem? Please describe.*

I tried to make my own agilty click highlights for the new agility course. but the tiles ahere are super strange as you can see in my video. so i cant get rid of them anymore .  

https://youtu.be/H2MBUA9z5Ig 

so i tried the reset button thinking this would reset all my marked tiles. But it didnt the button only reset your plugin configuration.

**Comment by Alexsuperfly** [comment]
duplicate of #1989
