### ISSUE TITLE
Display Level Progression in Skills Tab

### ISSUE THREAD

**Issue by OliverBroadbent** [runelite/runelite#9518]
**Is your feature request related to a problem? Please describe.**
Only being able to see the level progression after you gain xp in that skill (per session) can sometimes be annoying. It would be really nice to see every skills level progression in the skills tab.

**Describe the solution you'd like**
Display the level progression of every skill in the skills tab. See example.

**Describe alternatives you've considered**
As you will see in the photos below, I have both top and bottom aligned the progress bar as I'm not sure which would be best.

**Additional context**
Example: https://imgur.com/a/2M7L0ac

Honestly, i'm not 100% set on my example mainly because it looks too cramped. The bars are 1px tall and still, it's not perf. I still like the idea, obviously.. but hey, there's no harm in posting and seeing what others think.

**Comment by Hydrox6** [comment]
This is fulfilled by the [Skills Progress](https://runelite.net/plugin-hub/show/skills-tab-progress-bars) hub plugin
