### ISSUE TITLE
Hunter plugin doesn't trigger on ferrets

### ISSUE THREAD

**Issue by LarsHLunde** [runelite/runelite#9523]
**Describe the bug**
Box trap does not show a green circle when box trapping ferrets.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go north of Eagles Peak
2. Set a box trap
3. Catch a ferret in said box trap
4. The box trap doesn't turn green

**Expected behavior**
I expected the indicator circle to turn green instead of remaining orange.

**Screenshots**
Pre capture:
https://i.imgur.com/GLcQ2xX.png

Captured without change on indicator:
https://i.imgur.com/kjSxlJa.png

**Environment :**
 - OS: Windows 10
 - RuneLite version: 1.5.29.1
 - Launcher version: 1.6.0

**Comment by Xortrox** [comment]
Adding to this, you can also not left click release ferrets at the moment.
