### ISSUE TITLE
Missing clickbox from agility obstacle in Fremennik hunter area

### ISSUE THREAD

**Issue by AcridBrimistic** [runelite/runelite#9534]
There is no agility clickbox for this rock-slide in the fremennik hunter area, unlike all other obstacles.

1. Go to the northern part of the fremennik hunter area. (eagle is good way to get there)
2. Enter the cave to the north.
3. Rockslide with missing clickbox will be just beside you.

There should be a green box indicating where you can click to use the rockslide.

![2019-08-01_16-01-25](https://user-images.githubusercontent.com/18503603/62296078-1355aa80-b477-11e9-8545-3b227a16ce65.png)

 - OS: Windows 8.1 & Xubuntu 16.04
 - RuneLite version: 1.5.29.1
 - Launcher version: 1.6.0

**Comment by Darkkgreen** [comment]
I'll look into it soon
