### ISSUE TITLE
Highlight failure ladder on Prif agility course

### ISSUE THREAD

**Issue by scssquatch** [runelite/runelite#9538]
**Is your feature request related to a problem? Please describe.**
When you fail in the latter half of the Prif agility course there is a ladder to get back up. It's hard to see this ladder depending on the camera angle.

**Describe the solution you'd like**
Could you highlight the ladder like the other ones in the course?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dabolink** [comment]
fixed in issue #9508

**Comment by xDemoN** [comment]
This needs to be closed
