### ISSUE TITLE
Discord Party

### ISSUE THREAD

**Issue by leonardbonfils** [runelite/runelite#9542]
Currently, making a Discord party is glitchy and basically impossible if you have more than one client open.
Could you add the possibility of choosing which client you want the party to be associated to, or even better, could there be a toggle for each client you want to have in the party ? e.g. if I'm running 3 clients, I could have 2 of them in the party.

**Comment by MESLewis** [comment]
https://github.com/wesley-221/easyparty this may be a solution to this issue

**Comment by LlemonDuck** [comment]
Party plugin no longer uses Discord and is much more reliable now
