### ISSUE TITLE
SkillCalc: Clear button does not reset the search results

### ISSUE THREAD

**Issue by xdesr** [runelite/runelite#9545]
![clearbuttonfail](https://user-images.githubusercontent.com/49791189/62326028-09e33700-b4a5-11e9-9da8-434ce5f806ac.gif)

**Comment by Dava96** [comment]
This is like this with the Grand exchange plugin, so I'm assuming it's meant to be that way

**Comment by dekvall** [comment]
To be fair, even if the GE plugin works in the same way, the UX is a bit un-intuitive. If the text field is empty the results displayed should be the same, it shouldn't matter whether or not it was cleared with backspace or the red x. An empty field is an empty field.

**Comment by psikoi** [comment]
@deathbeam good first contribution?

**Comment by Adam-** [comment]
Do you mean it doesn't reset the search results?

**Comment by xdesr** [comment]
yes
