### ISSUE TITLE
[chatcommands] Add shorthands for Gauntlet and Corrupted Gauntlet kc

### ISSUE THREAD

**Issue by Jimbobiss** [runelite/runelite#9549]
Currently you have to write '!kc The Corrupted Gauntlet' to get a kc print out. This is rather heavy handed, so having some alternatives available would be useful such as '!kc tcg' or '!kc cgaunt'. You get the idea.

Would be great if possible, but if not I suppose no worries.

**Comment by Adam-** [comment]
This is a bug. The row tracks it as `The Gauntlet` and we track it as `Gauntlet`
