### ISSUE TITLE
Add Menu Entry Swap for Teleport Crystal and Eternal Teleport Crystal

### ISSUE THREAD

**Issue by Jademalo** [runelite/runelite#9559]
**Describe the solution you'd like**
An extra option added to the Menu Entry Swapper plugin that allows the Left Click of the Teleport Crystal and Eternal Teleport Crystal to be swapped between Lletya and Prifddinas.

**Additional context**
This is a fairly simple request, since the crystal now has two options on it and I've been finding a lot more use for the Prif teleport.

**Comment by OneProGoober** [comment]
Not saying it's a bad idea, but wouldn't shift chift click configurations do the trick?

**Comment by Jademalo** [comment]
Shift click works certainly, but it's still an extra key to press instead of a pure one click. I'd rather have Prif be primary with a shift click Lletya personally.

**Comment by Nightfirecat** [comment]
I don't think we're likely to prioritize one teleport location over another, given that we use the same behavior (that is, not adding configurations for them) for all of the various other teleport items which can teleport to multiple locations. (Ardy cloak, Morytania legs, Pharaoh's Sceptre, etc.)

**Comment by Jademalo** [comment]
That's fairly reasonable, though to be fair, those three are wear on the left click by default rather than the teleport. I can't really think of another example of a pure teleport item with two different options.

**Comment by Alexsuperfly** [comment]
it has two options, one on left click the other you can make shift left click, thats good enough, and all that will be done, this issue is invalid imo.

**Comment by deathbeam** [comment]
As @Alexsuperfly said
