### ISSUE TITLE
Move titlebar buttons into a top-bar when custom chrome is disabled

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#956]
Currently, if you disable custom window chrome the title bar buttons (screenshot, discord, account) move into the info panel. This makes 0 sense.
My proposed fix is instead of moving them there, add a top bar that would contain the elements of the title bar when custom window chrome option is disabled.

To add to this, as a user on discord mentioned, if this would be implemented, it would be nice if hiding this title bar was also possible. OSB does this when you press alt+F11 and I think konduit has has a keybind for this too.

Once something like #668 has been added it would be possible to play with a client looking like the vanilla one, by having no extra UI elements.

**Comment by Nightfirecat** [comment]
#1146 was merged some time ago, which was justification for closing #1113, which implemented the original suggestion. Is this issue solved, or is there still something leftover to be added?

**Comment by deathbeam** [comment]
I think this is solved well-enough
