### ISSUE TITLE
Updated scouting feature for CoX

### ISSUE THREAD

**Issue by MEstlander** [runelite/runelite#9560]
**Is your feature request related to a problem? Please describe.**
Currently the scouting feature cannot find all rooms, especially 4c1p layouts are never found while it is possible while using lyzrdlite for example. 

**Describe the solution you'd like**
Be able to scout 4c1p and some of the 4c2p are also hidden

**Describe alternatives you've considered**
You can manually add the plugin but it is a huge hazzle for those who have never used ides etc

**Additional context**

**Comment by Kamielvf** [comment]
This is not a bug, and also not something we wish to implement.
