### ISSUE TITLE
Runelite fails with java 11 & 12

### ISSUE THREAD

**Issue by ThaChillera** [runelite/runelite#9562]
**Describe the bug**
When trying to start runelite using java 11 or 12, it fails with the error code
`Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion 'version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!`

Java 10 does work.

**To Reproduce**
1. Install Runelite using the AUR package https://aur.archlinux.org/packages/runelite/
2. Set default java runtime using the `archlinux-java` set command
3. Start Runelite

**Expected behavior**
It should start on the latest versions of Java

**Screenshots**

**Environment (please complete the following information):**
 - OS: Arch Linux, latest updates as of 03-08-19
 - Java 10 version: 10.0.2.u13-2
 - Java 11 version: 11.0.4.u11-1
 - Java 12 version: 12.0.2.u10-1
 - RuneLite version: 1.5.30
 - Launcher version: Not used

**Addition Context**
This issue might be due to the linked AUR entry, but since it hasn't changed significantly since it did work, I assume the issue is with java/runelite

**Comment by Adam-** [comment]
The AUR version is not something we officially maintain or support. Does the Linux version on https://runelite.net work?

**Comment by ThaChillera** [comment]
Yes, the AppImage file downloaded from runelite.net does not have these issues. It appears the issue isn't due to Runelite. Thanks for the troubleshooting help
