### ISSUE TITLE
Discussion on different country flags in the world selector 

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#9563]
There have been suggestions for Dutch and Swedish and whatever worlds for quite some time now. Since Jagex isn't going to do this, maybe RuneLite could add a plugin, probably off by default, which changed the flags of specific worlds to the flags of other countries. An example would be to make a couple of German worlds have the Dutch or Swedish flag. 

This is probably a stupid idea and the community would have to agree on which worlds would have which flags, but I just wanted to throw the idea out there for discussion purposes.

**Comment by Nightfirecat** [comment]
The flags correspond to the servers' datacenter locations. Displaying any other flag for them would be inaccurate. What benefit would there be to doing this?

**Comment by Specced** [comment]
I agree with @Nightfirecat. If you want a change then send Jagex some feedback that you want servers in your home country.
