### ISSUE TITLE
When Alt is spammed on-ground item text disappears

### ISSUE THREAD

**Issue by PerthGoat** [runelite/runelite#9567]
**Describe the bug**
When I press left or right alt rapidly, text above items on ground can vanish

**To Reproduce**
Drop an item with overlay text on the ground, and press alt rapidly to see the text disappear.

**Expected behavior**
The text over the item should not disappear when alt is pressed rapidly.

**Screenshots**
Before:
https://i.imgur.com/rCw1rsI.jpg
After:
https://i.imgur.com/RFCGYG6.jpg

**Environment (please complete the following information):**
 - OS: Windows 10
 - OpenGL Version: OpenGL 4.6
 - RuneLite version: 1.5.31-SNAPSHOT compiled with javac 1.8.0_222
 - JRE version:  openjdk version "1.8.0_222"
 - RuneLite commit hash: 715c7a26b903016f6dce0d7fe6bef9448051a615
 - Launcher version: Not applicable

**Additional context**
There doesn't seem to be anything in the logs describing any errors.

**Comment by Alexsuperfly** [comment]
thats a feature, you can change the double tap time in the ground items settings

**Comment by PerthGoat** [comment]
Thanks I never looked in the settings, that seems to be it
