### ISSUE TITLE
Ä in chatbox after username and colon

### ISSUE THREAD

**Issue by PerthGoat** [runelite/runelite#9568]
**Describe the bug**
In the chatbox on the latest RuneLite snapshot, a letter Ä is rendered after the username and colon, all typed chat goes after it.

**To Reproduce**
Log in and view the chatbox.

**Expected behavior**
The chatbox should not have an Ä.

**Screenshots**
View the chat box specifically in this:
https://i.imgur.com/FMbkDgt.jpg

**Environment (please complete the following information):**
 - OS: Windows 10
 - OpenGL Version: OpenGL 4.6
 - RuneLite version: 1.5.31-SNAPSHOT compiled with javac 1.8.0_222
 - JRE version:  openjdk version "1.8.0_222"
 - RuneLite commit hash: 715c7a26b903016f6dce0d7fe6bef9448051a615
 - Launcher version: Not applicable

**Additional context**
There is nothing out of the ordinary in the logs.

**Comment by Alexsuperfly** [comment]
duplicate of #7983

**Comment by PerthGoat** [comment]
Closing this issue because developers are aware of it from #7983
