### ISSUE TITLE
Username Syncer plugin should respect the vanilla "Remember username" setting.

### ISSUE THREAD

**Issue by ShaunDreclin** [runelite/runelite#957]
This one was driving me nuts until I figured out what was doing it, the plugin was forcing my username into the login box even though I always unchecked remember username. Disabled the plugin and it stopped doing it, but that's not very intuitive.

**Comment by deathbeam** [comment]
Is this still valid?

**Comment by ShaunDreclin** [comment]
Seems to have been fixed at some point
