### ISSUE TITLE
Recolor Prifddinas Agility Course Portals

### ISSUE THREAD

**Issue by Mollium** [runelite/runelite#9574]
**While doing the new Prifddinas Agility Course, you’ll randomly get portals to click on that accelerate your laps. 

Runelite colors them in the same color that’s given to the other agility obstacles on the course. This makes it harder to spot them thus resulting in missclicking and skilling them.

**A simple solution would be to give them another color, like blue for example. Something to distinguish them from the standard obstacles.

**Another great way could be to make an arrow over the portals: just something to make it easier to spot a portal.

**Comment by melkypie** [comment]
Added in #10543
