### ISSUE TITLE
LootTracker: Loot Drops From Server are in Reverse Order

### ISSUE THREAD

**Issue by dabolink** [runelite/runelite#9575]
**Describe the bug**
When reloading the client the drops that are loaded from prev sessions are in reverse order

**To Reproduce**
1. switch loot tracker to individual kill
2. Kill a mob
3. kill another mob
4. restart runelite
5. open loot tracker and see drops have been reversed

**Expected behavior**
the loot tracker should always have the same order of drops

**Screenshots**
Kill Order: 
rabbit -> guard -> guard

Loot Tracker before reloading runelite:
![image](https://user-images.githubusercontent.com/5316046/62429882-979f6c00-b6c9-11e9-9fea-773b90bf5134.png)

Loot Tracker after reloading runelite:
![image](https://user-images.githubusercontent.com/5316046/62429885-ae45c300-b6c9-11e9-9dfc-b97c880b46e0.png)

Loot Tracker after killing imp after reload:
![image](https://user-images.githubusercontent.com/5316046/62429894-da614400-b6c9-11e9-9789-b55905e84885.png)

Expected:
(top -> bottom)
imp -> guard -> guard -> rabbit

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.30.1
 - Launcher version: 1.6.0

**Comment by dabolink** [comment]
https://github.com/runelite/runelite/blob/08fed6dba1771a6ac86dcd99d3964e1be8601d7d/http-service/src/main/java/net/runelite/http/service/loottracker/LootTrackerService.java#L69

i'm not 100% sure but I believe the fix for this would be either:
- change the SELECT_LOOT_QUERY from "...ORDER BY TIME DESC" to "...ORDER BY TIME ASC"
or
- it's because TIME is uppercase (this depends on if the database used is case-sensitive)

**Comment by raiyni** [comment]
We want the last X entries, so selecting by descending is correct.

**Comment by dabolink** [comment]
oh yes you are corrent, I was thinking of trying to reorder the ones selected. not the entire drops table. mistake on my part.
