### ISSUE TITLE
KC Command for Lizardman Shamans

### ISSUE THREAD

**Issue by Krikke93** [runelite/runelite#9581]
I'd like to suggest a !kc command for lizardman shamans. I'm not entirely sure how hard this would be to implement, but I feel like this should be entirely possible since there's a way to obtain your killcount ingame by talking to a shayzien NPC in the canyon.

Ideally, this would work for:
- !kc shaman
- !kc shamans
- !kc lizardman shaman
- !kc lizardman shamans

**Comment by deathbeam** [comment]
Lizardman shamans don't have kill count message after each kill

**Comment by Joepicklebob** [comment]
Allow the option to visit the Shayzien Infiltrator and manually update !kc command since it doesn't track normally. would that work?
