### ISSUE TITLE
Bug: Despawn Timers Appear w/ ALT When Turned Off

### ISSUE THREAD

**Issue by xDemoN** [runelite/runelite#9583]
**To Reproduce**
1. Open Ground Items config
2. See that despawn timers are off
3. Hold ALT
4. See despawn timers on ground items

**Expected behavior**
Despawn timers not showing anywhere when turned off

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.30.1
 - Launcher version: 1.6.0

**Comment by Nightfirecat** [comment]
I believe it was coded that way intentionally. Nevertheless, if we changed behavior, it would re-open #9558

**Comment by xDemoN** [comment]
Oops, didn't search through closed issues. Thanks for pointing out that it may be intentional. I'll let you all discuss and close this if need be.

**Comment by Nightfirecat** [comment]
Well, is there some reason you'd want to see them not appear when ALT is pressed? They appear for much the same reason that the rest of the overlay appears when it is pressed--so that players can be aware of it.

**Comment by xDemoN** [comment]
Personally, it was just annoying. After awhile, I thought that it may not have been intentional and filed this issue. Since then, I've learned it was intentional.

**Comment by deathbeam** [comment]
Well, based on the original issue description, this sounds like despawn timers are still showing when they are disabled in config completely? If that is not the case, this issue description is horribly worded.
