### ISSUE TITLE
Freeze when login, not PC just client

### ISSUE THREAD

**Issue by BlemFoReal** [runelite/runelite#9586]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

client works fine, until i log in, then it always freezes on loading. ive tried turning off gpu and everything still does not work.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment]
As is described in the "Additional context" section of the issue template, please post your client logs.

**Comment by BlemFoReal** [comment]
Don’t worry, I logged out of my runelite account and it suddenly works for some reason so I guess I’ll just play not logged in


________________________________

**Comment by mikexsouth** [comment]
Try clear out your cache.  It sounds similar to my issues particularly when GPU is on. Some pc's are not good at managing cache.

If you have NVIDIA and GPU on, try using free Ccleaner program to automatically clear cache everyday automatically.  Set it to clear the folders: 
- C:\Users\USERHERE\AppData\Local\NVIDIA\GLCache\
- C:\Users\USERHERE\AppData\Local\NVIDIA Corporation\NVIDIA GeForce Experience\CefCache\

**Comment by MESLewis** [comment]
Reopen this issue if the problem persists in the latest release of RuneLite.
