### ISSUE TITLE
Implings: Incorrect Color Picker behavior when copy-pasting Color Codes

### ISSUE THREAD

**Issue by alro5921** [runelite/runelite#9587]
When choosing an impling's highlight color: if you copy-paste a color code and leave the impling's color picker without pressing ENTER, the configuration menu will show the new color, but the in-game highlight will NOT change. And after resetting the client, the config menu shows the old color. Hitting ENTER correctly changes the color.

**Reproduction:**
1. Go to the Implings configuration menu, find an impling.
2.  Click on its corresponding color picker
3. Copy paste a color code (#FFFFFF) and exit with the "x".
4. The menu's color will change to the new color, but the in-game impling highlight will remain the same.

**Expected behavior**
(Ideally) The in-game impling highlight correctly changes, or the menu shows the color it's actually highlighting.

(I suspect this might apply to other color wheels)

**Environment:**
 - OS: Windows
 - RuneLite version: 1.5.30
 - Launcher version: ??? (Don't see where this is)

**Comment by Nightfirecat** [comment]
Is this the same behavior when typing out a color code and hitting "X" rather than hitting "Enter"? Sounds like this isn't an impling plugin behavior issue, but a color picker behavior issue.
