### ISSUE TITLE
Suggestion: Add Pyramid Plunder chest and sarcophagus counter

### ISSUE THREAD

**Issue by Aealm** [runelite/runelite#9595]
Possible to add a counter for the chests and sarcophagi opened in PP? Maybe under Loot Tracker?

**Comment by jachymb** [comment]
+1 for adding to loot tracker

**Comment by JJGrootveld** [comment]
Bumping this, would be awesome

**Comment by jachymb** [comment]
Related: #12084

**Comment by Nightfirecat** [comment]
Given the similarities of the request, and that we're more likely to implement loot tracker expansions than a PP-specific counter, I am closing this as a duplicate of #12084.
