### ISSUE TITLE
Add a visual indicator to the tick metronome as well as a hotkey bind to turn it on/off

### ISSUE THREAD

**Issue by Auxytocin** [runelite/runelite#962]
Not sure what would be the best type of visualizer but I was thinking either a flashing or pulsating orb.

**Comment by Toocanzs** [comment]
The pray flicking plugin does exactly this, although it always happens every tick. 
![pray flicking](https://i.gyazo.com/6b150b3cf183063bf980b59d775b6611.gif)

**Comment by Auxytocin** [comment]
I noticed, but isn't that only when you're using a prayer?
