### ISSUE TITLE
First time logging in in 4 months and get a scam mail within couple hour

### ISSUE THREAD

**Issue by crazyxangel** [runelite/runelite#9621]
hello,

so i have no idea where to report any of this or if this is runelite related but
for the first time in 4 months i come back to osrs with runelite (i logged in about a month ago in rs3 same account)
and within a couple hours i receive a scam mail involving osrs

now i dont believe in coincidence so either my computer got infected with something today
or runelite might have a email data breach

**Comment by deathbeam** [comment]
Well, we are not sending scam emails to anyone, and we do not have any "email data breach", so you either have wrong version of runelite, or its simply coincidence, idk. Regardless of that, this is issue tracker, so closing
