### ISSUE TITLE
Bank tag tab tab

### ISSUE THREAD

**Issue by JeljoGb** [runelite/runelite#9625]
I suggest a bank tag tab tab, which would show all of your bank tag tabs' icons in a tab, to more easily locate them. Right now, if you have 20/30+ tag tabs, it takes a while to find the tag tab you want, scrolling through 3-4 at a time.

Having a tag tab tab (could do with a better name) would let me quickly click the tag tab I want.

Not sure about alternatives.

Not sure about where you'd place the button, maybe under the "+", or make that button "manage tag tabs" or something?

**Comment by raiyni** [comment]
You can scroll with mouse wheel and organize them how you want with drag and drop

**Comment by JeljoGb** [comment]
![image](https://user-images.githubusercontent.com/34870401/62784095-f8f67f00-babd-11e9-9514-0287f908e7ee.png)
Scrolling through them whilst seeing 3 at a time, and having way more than that, can be tedious.
Also, drag and drop swaps them, which is an annoying way of sorting, and also a different topic tbh.

**Comment by raiyni** [comment]
You mean like this? 
![uXffm4IyyE](https://user-images.githubusercontent.com/22979513/62944140-b07ee000-bda1-11e9-8c77-31c255ab59e0.gif)

**Comment by JeljoGb** [comment]
Oh my god that looks amazing. Yes exactly that!

**Comment by JeljoGb** [comment]
One day this will be added, right?

**Comment by OliverBroadbent** [comment]
I too feel like there needs to be a form of management for tag tabs. After all they can add up quickly. 

I have a different solution to this issue that I think will feel more natural to the user. Folders for bank tag tabs, just like discord server folders. Here's my concept art... 

![new group](https://user-images.githubusercontent.com/10792231/66708767-db5bc500-ed4d-11e9-803a-beaa182c3f76.jpg)
![folder](https://user-images.githubusercontent.com/10792231/66708769-de56b580-ed4d-11e9-8262-ea9ddfc02767.jpg)

**Comment by AmazingJesus** [comment]
Been half a year since this was looked at, I really like Oliver's design.

**Comment by raiyni** [comment]
I don't see that being wrote without an interface writer
