### ISSUE TITLE
Menu Swapper: Coal bag and Gem bag "Empty" option primary for banking interface.

### ISSUE THREAD

**Issue by ChiSox** [runelite/runelite#9633]
**Is your feature request related to a problem? Please describe.**
While mining, bank fillers are often used to deposit quickly. If you are using the coal bag though, you need to right click > Empty. Shift click does not work in the banking interface.

**Describe the solution you'd like**
Allow "Empty" to be made the primary left click option for the coal bag.

**Describe alternatives you've considered**
Shift click, but that doesn't work in the banking interface.

**Comment by deathbeam** [comment]
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

We are intentionally not swapping any menu options in bank
