### ISSUE TITLE
Suggestion: Add option to hide Special loot from chat during COX

### ISSUE THREAD

**Issue by hootiii** [runelite/runelite#9637]
Add an option for Chambers of Xeric to hide the chat message of which special loot you received, so that the reveal doesn't happen until you see the purple light and then loot the chest. Similar reveal to Theatre of Blood.

**Comment by LlemonDuck** [comment]
Available as a hub plugin, [CoX Censor](https://runelite.net/plugin-hub/show/cox-special-loot-hider)
