### ISSUE TITLE
Suggestion - XP Tracker Addition

### ISSUE THREAD

**Issue by MrCulted** [runelite/runelite#9638]
Can XP until certain level be added, kind of like the OSBuddy feature. Example, on the OSBuddy client, the XP tracker will allow me to look at my current level until whatever level I set. Like if im level 45, I can put Goal Level 75, and it track from lvl 45 to 75, Instead of only to the next level.

**Comment by Hydrox6** [comment]
This is already in the client 
https://github.com/runelite/runelite/wiki/XP-Drop#goals
