### ISSUE TITLE
Menu Entry Swap for Pizza Bases (& potentially other right click cooking items)

### ISSUE THREAD

**Issue by Korasto** [runelite/runelite#9639]
Hello Runelite Devs!

I would really love to see a few menu entry swaps to enhance cooking. My example I'll be using is more focused towards F2P players (Anchovy Pizzas) but could be used for higher tier members items also (Pineapple Pizzas+)

I'd love to see pizza bases have the use option before eat. It's really frustrating and cuts into profit and XP P/HR margins while cooking when you accidentally eat one of your bases. It's subtle and won't dramatically change the game, or cause damage to cooking EHP.

Thanks for reviewing my suggestion, I love RuneLite and appreciate all the effort the Devs are putting into this amazing project! I hope to see this in-game soon:)!

**Comment by Dava96** [comment]
You can just Shift-click configure to change the option to what you want (use in this example). Then enable sticky keys so shift is always pressed. 
See this for reference - https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper

I believe there is an effort to try and avoid adding more options to this plugin.

**Comment by Kamielvf** [comment]
Use the [menu entry swapper](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper) to configure shift-click to "use".
