### ISSUE TITLE
Client crashing when opening a chat interface

### ISSUE THREAD

**Issue by Jagerblue** [runelite/runelite#9640]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
On a fresh pull(As of august 10th 10 pm est) the client crashes when trying to "Withdraw-x" of something or "Configure" a fairy ring in your house. Likely other things that try to bring up a chat box prompt will crash the client as well. 

The issues inside the bank are resolved when the "Bank Tag" plugin is turned off.

**To Reproduce**
1. Go to your bank or a fairy ring in your house.
2. Click on Withdraw-X or Configure(for the fairy ring)
4. The client will crash, telling you that your maven classes are out of date.

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.31 ? Latest from the github pull as of August 10th 10 pm est.
 - Launcher version: 1.5.31

**Additional context**
https://pastebin.com/SbgyePzV
https://pastebin.com/h30W2juC

I have reimported all maven projects, built maven with "clean install -DskipTests -U -f pom.xml" and when I pull it tells me all files are up to date. User @Daxe#1635 on Discord has the same issue and has done the same things as me as per his discord messages.

**Comment by Adam-** [comment]
This was due to internal not syncing due to a merge conflict.
