### ISSUE TITLE
Idle Plugin - Standing Still

### ISSUE THREAD

**Issue by Coollegolas** [runelite/runelite#9649]
Would it be possible to add an idle alert for just being idle? I'm picturing it for an alt where I've moved between objects and am now just standing, so the main flash won't ever happen since I moved to a point to stand still. For instance, you're crafting blood runes and get stopped halfway to the altar, but you don't notice and forget about the alt.

It would hopefully be configurable and generally set to a long enough time that it wouldn't be going off all the time (I'd probably set it to 15-20 seconds default?) and should definitely be able to be isolated from the rest of the idle alerts so that it's not overriding or happening when people don't want it to.

**Comment by HalfOfAKebab** [comment]
Doesn't the Idle Notifier plugin do this?

**Comment by Darkkgreen** [comment]
The idle notifier does that, or you didn't make yourself clear. You want a custom idle timer? I don't get it lol

**Comment by Alexsuperfly** [comment]
he wants it to track idle after just moving, which the plugin does not do atm other than the logout timer

**Comment by Darkkgreen** [comment]
> he wants it to track idle after just moving, which the plugin does not do atm other than the logout timer

So...just a custom idle timer. I see

**Comment by deathbeam** [comment]
This do not sounds useful at all

**Comment by Coollegolas** [comment]
The utility is for alts where you're doing things such as banking or moving between areas, it happens fairly often that you just forget about the second or third accounts.

I agree that it doesn't seem particularly OP or anything, but I figured that it seemed like a small addition to make which could help out for alts or help with keeping people more efficient if they don't want to spend too much time bankstanding or the like.

**Comment by deathbeam** [comment]
Implemented in https://github.com/runelite/runelite/commit/ed17bdaed351549e7547238e354a145154da3668
