### ISSUE TITLE
Player Names Overheads

### ISSUE THREAD

**Issue by mikexsouth** [runelite/runelite#9650]
**Feature request:**

I would like to see an option for showing all **players' names overhead** - not just friends, but in public too.  This could look similar to friends' names overheads, but could be grey (or customisable colour).  I am forever right-clicking players to reveal their name.  It could also be tied in under Entity Hider.

A possible problem would be in GE - could it also be auto-disabled (or given an option to auto-disable) in GE area?

Mike

**Comment by Nightfirecat** [comment]
This can already be done using the "Highlight non-clan members" option of the [Player Indicators plugin](https://github.com/runelite/runelite/wiki/Player-Indicators)
