### ISSUE TITLE
Multiple Runelite Accounts

### ISSUE THREAD

**Issue by ez1ollie** [runelite/runelite#9652]
Add in a runelite account switcher. So you sign in to a runelite account, then there would be a drop down menu to choose which account you want to use. This would replace the sign in & sign out process that is currently required when switching runelite accounts.

Something like this https://i.imgur.com/EW1IPqz.png

This should solve #2200

**Comment by Alexsuperfly** [comment]
duplicate of #2220

**Comment by ez1ollie** [comment]
Hardly a duplicate. It’s a separate approach to the same problem.
