### ISSUE TITLE
Crashing when i enable GPU- worked for months without issue.

### ISSUE THREAD

**Issue by kendostick70** [runelite/runelite#9654]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Ubuntu, macOS]
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Additional context**
Add any other context about the problem here, e.g. logs. Your client logs can usually be found in
`C:\Users\<your_user_name>\.runelite\logs` on Windows and `~/.runelite/logs` on Linux and macOS.

**Comment by Nightfirecat** [comment]
We won't be able to help with no information added. Please add some more description and post your client logs (and crash logs if applicable) and we can start to investigate this.

**Comment by karljakober** [comment]
This also started happening today too. I cant get through a single NMZ session but am unable to provide exact reproduction steps.
I also dont believe the logs have anything but I will include them anyways.
I am going to also include a screenshot windows pops up with once runelite crashes.
There is a crash dump for each time this happened in the runelite folder inside appdata. included.

[client.log](https://github.com/runelite/runelite/files/3503855/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3503856/launcher.log)
[hs_err_pid11396.log](https://github.com/runelite/runelite/files/3503870/hs_err_pid11396.log)
![2019-08-14 16_16_47-Window](https://user-images.githubusercontent.com/140006/63065112-9afcd980-beb9-11e9-91ac-596c638f612a.png)


I am running windows 10
Runelite version 1.5.30.1
Launcher version 1.6.0

I have completely remove my nvidia graphics drivers while in safe mode, and reinstalled them to no avail.

Thanks guys!

**Comment by kendostick70** [comment]
> We won't be able to help with no information added. Please add some more description and post your client logs (and crash logs if applicable) and we can start to investigate this.

since moving to a launcher given from someone on discord (admin) it produces no logs.

upon putting old GPU drivers (rolled back 2 drivers) it seems mostly fixed

**Comment by karljakober** [comment]
Its not GPU Drivers for me, as mine dont auto update. It started happening randomly, and seems to only happen when runelite is being game captured by OBS

**Comment by kblicharski** [comment]
Bumping this as I'm experiencing the same issue. Enabling the GPU plugin instantly causes the client to crash. Seemingly appeared out of nowhere.

**Comment by MESLewis** [comment]
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.
