### ISSUE TITLE
xp tracker false xp gains

### ISSUE THREAD

**Issue by Alexsuperfly** [runelite/runelite#9664]
![](https://cdn.discordapp.com/attachments/301497432909414422/611574157078953985/unknown.png)

**Comment by dekvall** [comment]
I could (approximately) replicate this ~60% of the time by:
1. Log into a normal world and gain some xp
2. While logged in, press reset others on one of the skill trackers, then press rest on the last one, leaving you with the overall counter.
3. Log into a beta world and watch the xp/h go through the roof.

[Logs](https://paste.ee/p/qQ5VH)

**Comment by SRLJustin** [comment]
Any chance you logged into a Beta world then back into the "live" game?

**Comment by Adam-** [comment]
We figured out this was a race due to the server sending npc updates prior to bursting xp data on login. Fixed in e0af554c698ea2029f8aa5aa6bff64ed55328890
