### ISSUE TITLE
Runelite crashes directly after loading and freezes my whole pc

### ISSUE THREAD

**Issue by Jochem228** [runelite/runelite#9666]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
after startup my whole pc freezes and i cant do anything. Need to hard reset my pc to get it working again

**To Reproduce**
Boot up the client.
Freeze

**Expected behavior**
not freezing on startup

**Screenshots**
Cant
**Environment (please complete the following information):**
 - OS: windows 10
 - RuneLite version: latest

**Comment by MalakaJones** [comment]
Just experienced a similar issue. I entered my credentials then pressed enter and it just crashed. My PC didn't freeze tho.

**Comment by Nightfirecat** [comment]
If this is still a problem, please post here and we will look into this issue further. For now I am closing this issue.
