### ISSUE TITLE
Overlay drag outlines are incorrectly placed

### ISSUE THREAD

**Issue by Hydrox6** [runelite/runelite#9671]
When dragging an overlay, the bounding box of the overlay is incorrect. This effect increases the further away from the top left of the screen the overlay is.

The bounding box in the following picture is for the infoboxes:
![Example](https://i.imgur.com/EriSQQo.png)

Caused by changes in [eb118c24dee7694535bca8ee0dd3d557738b2ca7](https://github.com/runelite/runelite/commit/eb118c24dee7694535bca8ee0dd3d557738b2ca7)

**Comment by deathbeam** [comment]
so this https://github.com/runelite/runelite/commit/eb118c24dee7694535bca8ee0dd3d557738b2ca7#diff-92690448256fce608fdb2a01f3fcac02R299

needs to be moved between snap corner drawing and movable overlay drawing, and also after dynamic draw. I guess just transform will be enough, but it should be consistent imo and so everything should be moved there.

**Comment by Adam-** [comment]
Does a95671a57d9ac2ebe544686800e86b2e6959c7ca work?

**Comment by Adam-** [comment]
@Hydrox6 can you test a95671a57d9ac2ebe544686800e86b2e6959c7ca ?
