### ISSUE TITLE
Can't click on certain areas like inventory display

### ISSUE THREAD

**Issue by adamwd392** [runelite/runelite#9672]
After the recent update I can't click on any of info panels other than combat options and skills. Within those menus I can't actually click on anything. If I make the xp tracker visible I am now able to click on all the menus to display such as inventory, spells, prayer, etc. But, I can only click on objects that are within the left half of the menu if you were to draw a vertical line straight down the middle. For example, I can only click on items that are located in the first 2 columns.

**Comment by Nightfirecat** [comment]
If this is still a problem, please post here and we will investigate this issue further. For now, I am closing this issue.
