### ISSUE TITLE
screenshot plugin doesn't capture full game area on new launcher with gpu plugin on

### ISSUE THREAD

**Issue by 000000653** [runelite/runelite#9673]
**Describe the bug**
Taking a screenshot with windows dpi scaling set to 125% doesn't capture the full game area unless GPU plugin is turned off

**To Reproduce**
1. Set windows 10 dpi scaling to be 125%
2. Turn on GPU plugin
3. Launch runelite with launcher 2.0.0
4. Take a screenshot with the screenshot plugin

**Expected behavior**
The screenshot plugin should capture the full game regardless of GPU being turned on or off

**Screenshots**

With GPU turned on
![2019-08-16_11-43-37](https://user-images.githubusercontent.com/40111569/63184135-4887fe00-c01c-11e9-809f-96264511514c.png)

With GPU turned off
![2019-08-16_12-00-42](https://user-images.githubusercontent.com/40111569/63184707-98b39000-c01d-11e9-80ca-1f0eaa00f281.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.31.1
 - Launcher version: 2.0.0

**Additional context**
Launcher logs: https://pastebin.com/M2244Hvu
Client logs: https://pastebin.com/xWx8BJWU

**Comment by SirKingst0n** [comment]
I am having the same issue myself!!

https://i.gyazo.com/16dd2772094440ac190dc61304501347.png

**Comment by Alexsuperfly** [comment]
Can you try with the launcher listed [here](https://github.com/runelite/runelite/issues/9696#issuecomment-522385946), it has a fix in it that helps with another dpi issue that might solve this aswell.

**Comment by SirKingst0n** [comment]
> Can you try with the launcher listed [here](https://github.com/runelite/runelite/issues/9696#issuecomment-522385946), it has a fix in it that helps with another dpi issue that might solve this aswell.

Just tried this and it hasn't worked :(

**Comment by Adam-** [comment]
Can someone double check this isn't fixed with launcher 2.0.2?

**Comment by 000000653** [comment]
launcher 2.0.2 works for me
GPU on, 64 bit if that matters
![2019-08-23_18-45-21](https://user-images.githubusercontent.com/40111569/63629238-91b8ee80-c5d6-11e9-8fa1-e70a49ab402d.png)
