### ISSUE TITLE
Show high alchemy values on price check screen

### ISSUE THREAD

**Issue by follmer** [runelite/runelite#9674]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the ability to see high alchemy values in the in-game price checker. This would allow for ironmen to see the high alchemy value of their inventory, rather than a grand exchange value which wouldn't be useful.

**Describe alternatives you've considered**
Checking the high alchemy value of every item in the inventory

**Additional context**

**Comment by Lightness248** [comment]
I'm working on it :)

**Comment by oplosthee** [comment]
This is a duplicate of https://github.com/runelite/runelite/issues/8502
