### ISSUE TITLE
Mouse Tool Tips Bug

### ISSUE THREAD

**Issue by Dragon911XX** [runelite/runelite#9688]
When making Curry, I found that (inconsistently) suddenly my item tooltips just kind of disappears. I couldn't find out exactly how to recreate the bug all the time, but it's happening to me about every 5-10 mins of doing Curry.

I'll try to see if I can recreate it, but it seems like just making Curry causes it to break every little bit, and banking fixing it.

Windows 10 Pro Version 10.0.17763 Build 17763.
RuneLite Version 1.5.31.1

https://i.imgur.com/e35lyOw.gifv

**Comment by deathbeam** [comment]
Do you have logs? https://github.com/runelite/runelite/wiki/Troubleshooting-problems-with-the-client see the section at top, and paste them here

**Comment by Dragon911XX** [comment]
https://pastebin.com/0FBThS2T

This is the client.log file for today.

**Comment by deathbeam** [comment]
Hmm weird, I dont see any errors there

**Comment by Hydrox6** [comment]
I've had this happen before, and it seems to have something to do with the VarClientInt (?) that controls whether the vanilla client is showing a tooltip getting stuck as `1`

**Comment by Nightfirecat** [comment]
If this is still a problem, please comment here and we will re-open this issue for further investigation. For now I am closing this issue.
