### ISSUE TITLE
Feral vampyres not counted towards vampire slayer task

### ISSUE THREAD

**Issue by Kamielvf** [runelite/runelite#9689]
The counter from the slayer plugin does not decrease as these Feral vampyres are slain, but they are a valid slayer target.

**Comment by Alexsuperfly** [comment]
this bug was introduced in #9490 with the null check return before the killedOne() method in onExperienceChanged

**Comment by Nightfirecat** [comment]
Hm, maybe we should change the fix from 9490 to allow null tasks to decrement the task counter by 1? Seems like an easier fix than fixing each case of an alternate monster being allowed as a slayer kill individually.

**Comment by deathbeam** [comment]
I would rather just add the special cases
