### ISSUE TITLE
Remove 'Teleport Item' from Menu Entry Swapper

### ISSUE THREAD

**Issue by Primoyultimo** [runelite/runelite#9695]
I've been seeing suggestions for adding additional teleport item swaps in the menu entry swapper such as the teleport crystals, pharaoh's sceptre, etc. #9559 #9691. The desire for these swaps seem to stem from the 'Teleport Item' swap option in the menu entry swapper which swaps certain teleport options on a few items. The 'Teleport Item' swap is incomplete and lacks many common teleport items, and all of the items that are currently included in the 'Teleport Item' swap can be swapped using Shift-click (making the the option completely useless). I propose removing the incomplete and redundant 'Teleport Item' swap option from the menu entry swapper as it's unnecessary and players should just use Shift-click. It will clean up an already bloated menu and hopefully clarify RuneLite's stance on teleport swap options.

**Comment by Nightfirecat** [comment]
8944eb9be6d62ec8384e29484dab14c4c2858d9d was added to master, which sufficiently covers this use case.
