### ISSUE TITLE
Window Maximize Doesn't Properly Fit Screen

### ISSUE THREAD

**Issue by RSNKitt3n** [runelite/runelite#9696]
**Describe the bug**
When clicking the maximize button, my client only takes a portion of the screen. I have tried reinstalling runelite and deleting related files, changing display settings, and restarting my computer but nothing has helped. I tried with the official OSRS client and it works just fine.

**To Reproduce**
1. Open the client as normal
2. Login or stay logged out, doesn't matter
3. Click maximize button and then be sad :(

**Expected behavior**
Client is expected to take up the whole screen.

**Screenshots**

<img width="1280" alt="NWghOerCcw" src="https://user-images.githubusercontent.com/54251743/63231703-f4784780-c1dc-11e9-999e-4f8fb8001c1d.png">

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: 1.5.31.1
 - Launcher version: 2.0

**Additional context**
None

**Comment by Adam-** [comment]
If you set DPI scaling override to `System` does that do anything?
![image](https://user-images.githubusercontent.com/309739/63231867-c9e3ba00-c1ef-11e9-9b41-bf2955adb029.png)

**Comment by RSNKitt3n** [comment]
damn you're my hero thanks for the speedy response!

**Comment by Adam-** [comment]
This is probably still a bug I was just wondering if that would fix it or not.

**Comment by RSNKitt3n** [comment]
well i'll leave open and let someone else decide then, ty

**Comment by Crownescent** [comment]
I am also having the same problem as RSNKitt3n. I'm sorry if me commenting this is useless/annoying, I'm not really sure how issues like this are brought up on Github as I've never used it, but I just wanted to let you know that I'm also having this problem. I was installing Runelite on a new laptop, and the same issue occurred. I tried the DPI override you suggested with no success.

**Comment by Adam-** [comment]
If you use https://sigterm.info/runelite/RuneLiteSetup32.exe - does that fix it?

**Comment by Crownescent** [comment]
Am I supposed to uninstall and use that setup to reinstall Runelite?

**Comment by Adam-** [comment]
What do you mean by "crashing"? I can run it and it works okay.

**Comment by Crownescent** [comment]
Crashing as in when I use that specific setup to install Runelite, the game does not make it to the log-in screen. Using the installation setup from runelite.net, the game installs properly and works fine aside from the issue stated in this thread.

**Comment by Adam-** [comment]
Does the 32bit installer from runelite.net work?

**Comment by Crownescent** [comment]
Yes.

**Comment by Adam-** [comment]
@RSNKitt3n are you available to test it instead?

**Comment by raiyni** [comment]
This worked for a user in discord.

![Discord_5ISRw5lkAw](https://user-images.githubusercontent.com/22979513/63315646-95e0c580-c2d1-11e9-93a8-8cbe6652a8bd.png)

**Comment by Crownescent** [comment]
Upon rechecking my Runelite version, the 32 bit installer does not work for me, but the 64 bit installer does. Sorry for the confusion.

**Comment by Hawkie1** [comment]
all of this is true for me as well, but the 32bit version runs very poorly for my pc is 64 bit. There seems to only be a link on runelite.net for a previous version in 32bit. getting like 15 fps where before I had at least 40 or 50 on the 64bit client

**Comment by Hawkie1** [comment]
i might just stick with the fcked up maximize client just to get better fps, over this previous 32bit version provided on runelite.net

**Comment by NikoZBK** [comment]
> If you use https://sigterm.info/runelite/RuneLiteSetup32.exe - does that fix it?

This fixed my resolution issue. Main monitor is 1440p, side monitor is 1080p. Issue was launcher was using the 1920x1080 resolution of the side monitor rather than the 2,560 x 1,440 resolution of the main monitor.

**Comment by Adam-** [comment]
Fixed with launcher version 2.0.2.
