### ISSUE TITLE
Intellij passing --mode=OFF

### ISSUE THREAD

**Issue by l33t-boga** [runelite/runelite#9698]
I'm on lubuntu trying to run RuneLite through Intellij, I can't seem to figure out how to make the game show up, all I get is a RuneLite window that I can see through.

Jdk 8 is set to the project, I have it running in --debug and dev mode. I tried adding --mode=OFF here, but it just through's errors.

Exception in thread "main" joptsimple.UnrecognizedOptionException: mode is not a recognized option

**Comment by Adam-** [comment]
`mode` is an argument to the launcher, it is not a valid client argument.

**Comment by l33t-boga** [comment]
How would I be able to do it with Intellij, I need the dev mode. I've done it on windows before like that.
