### ISSUE TITLE
Make hooks importer for RuneStar

### ISSUE THREAD

**Issue by BenjaminFaal** [runelite/runelite#970]
I came accross this repo: https://github.com/RuneStar/client

It contains almost every hook in the game, its really high quality. Someone should write an importer for the hooks it already has.

Just run `mvn install` and it will update all hooks, then in the `updater/target` folder there is a hooks.json file which should be made an importer for.

**Comment by devLotto** [comment]
``mvn install`` results in this for me:

```
[WARNING] The POM for org.runestar:general:jar:0.161.1-SNAPSHOT is missing, no dependency information available
...
[ERROR] Failed to execute goal on project client-updater-create-maven-plugin: Could not resolve dependencies for project org.runestar.client:client-updater-create-maven-plugin:maven-plugin:0.165.0-SNAPSHOT: Could not find artifact org.runestar:general:jar:0.161.1-SNAPSHOT -> [Help 1]
```

**Comment by Adam-** [comment]
That is what https://github.com/runelite/runelite/tree/master/deobfuscator/src/test/java/net/runelite/runesuite is - the project got renamed awhile ago.
