### ISSUE TITLE
Elite Clue - "Has no one told you it is rude to ask a lady her age?" - Incorrect NPC 

### ISSUE THREAD

**Issue by ICarrotU** [runelite/runelite#9700]
Just completed the elite clue step "Has no one told you it is rude to ask a lady her age?"

Runelite pointed to [Lady Tangwen Trahaearn](https://oldschool.runescape.wiki/w/Lady_Tangwen_Trahaern) in Prifiddnas, but correct NPC to speak to is [Mawrth](https://oldschool.runescape.wiki/w/Mawrth) in Lletya.

**Comment by Alexsuperfly** [comment]
fixed in master

**Comment by Hydrox6** [comment]
Specifically in https://github.com/runelite/runelite/commit/b87e50e43b9bb4b10342d4ec1a96833e2b9f4109
