### ISSUE TITLE
Split up the "Teleport item" option in the menu entry swapper plugin

### ISSUE THREAD

**Issue by MagicfTail** [runelite/runelite#971]
Make it possible to differentiate between 1 click teleports like Kandarin headgear, multi-teleport items like amulet of glory and multi-function items like slayer ring. 1 click items is mostly because they are easily clicked by mistake and multi-function items should have their own category since they aren't solely a teleport item.

**Comment by deathbeam** [comment]
We have shift-click now so this is unnecessary
