### ISSUE TITLE
When you get over 100KC at Thermonuclear smoke devils you can no longer see ur KC in the loot tracker

### ISSUE THREAD

**Issue by imzondax** [runelite/runelite#9713]
If you get more than 100KC at Thermonuclear smoke devils you can no longer see how many kc uve gotten because of the lenghty name of the NPC. 

![image](https://user-images.githubusercontent.com/36119211/63440876-e6226980-c430-11e9-9377-b64093b81e4f.png)

**Comment by Hydrox6** [comment]
Duplicate of #5673
