### ISSUE TITLE
Enabling GPU plugin causes client to glitch out

### ISSUE THREAD

**Issue by Chronolis** [runelite/runelite#9718]
When turning on the GPU plugin, even after logging in, the screen shows up like this. 

![image](https://user-images.githubusercontent.com/13292745/63522375-d3a24180-c4bd-11e9-811d-0e6432bc2b88.png)

I have tried disabling compatibility mode - running as admin - disabling full screen optimization and other compatibility things for windows. I am not sure what else to do, so if anyone has any suggestions that would be great!

**Comment by Hydrox6** [comment]
Turn down the level of AA in the GPU plugin settings.

**Comment by Chronolis** [comment]
BOOM! Thank you very much!
