### ISSUE TITLE
Broadcasting 

### ISSUE THREAD

**Issue by vaqah** [runelite/runelite#9727]
Just as it is on RS3 can we get the Broadcasting of friends getting 99 in skills and even boss drops 

"noobmaster69" has received a bandos chestplace drop.

"NUBNUB" has just achieved 99 in strength.

**Comment by AverageHumanoid** [comment]
I would like the opposite with a way to block getting spammed with broadcast messages after an update, before a stream or during some event.

**Comment by Adam-** [comment]
It's not possible for us to verify who you are or who your friends are, so I don't think this could be done in a way people couldn't just use to spam. Also we don't have a way to push events to the client at all.

**Comment by Alexsuperfly** [comment]
duplicate of #2353
