### ISSUE TITLE
Feature request: The ability to remove the tooltip describing a spell when hovering over a spell

### ISSUE THREAD

**Issue by hellohiretrowow** [runelite/runelite#9730]
It's annoying when PVMing!

The ability to remove the tooltips on mouseover like Jagex did with prayers would be amazing

Thanks

**Comment by deathbeam** [comment]
You can already disable interface tooltips in Mouse Tooltips plugin

**Comment by AverageHumanoid** [comment]
One of my friends recently mentioned wanting to remove the description when hovering over a prayer but I don't think there is any way to do that currently.

**Comment by willediger** [comment]
FYI, this feature was recently added as a plugin in the plugin hub https://runelite.net/plugin-hub/show/hide-spellbook-tooltip
