### ISSUE TITLE
Add a Drift Net Fishing Plugin

### ISSUE THREAD

**Issue by AkilliesX** [runelite/runelite#9731]
**Is your feature request related to a problem? Please describe.**
Currently there is no plugin available for Drift Net Fishing as far as I am aware. As someone who really enjoys the activity, there are a number of QOL things that RuneLite could add that could make Drift Net fishing more enjoyable.

**Describe the solution you'd like**
A plugin for Drift Net Fishing that adds some QOL changes. From my own personal suggestions: 
1. A clickbox highlight for setting up nets at the Drift Net Anchors so you know where to click to set up traps, similar to Rooftop Agility.
2. A red highlight on the Drift Nets for when they are full (they are named "Drift net (full)" when full and just "Drift net anchors" when not full. They also change appearance, if that helps with implementation)
3. A left click option change in Menu Entry Swapper to change Annette's left click from "Talk-to" to "Nets".
4. Highlights for the Fish shoals that you have already clicked "Tag" on, and a different color for ones you have not clicked "tag" on.

**Describe alternatives you've considered**
Using a combination of current RuneLite plugins, I can roughly match some of the requested features, however they are definitely lacking. In order of the requested features:
1. I tried tagging the object for Drift Net Anchors. It works for highlighting the entire anchor but the only places you can actually click to set up the nets are the tiny little stones at the edges of the highlight. The object tag includes entire empty space in the middle that you can't click to set up the trap.
2. The closest thing is to set up a chat notification for when it says "Your Drift net is full.", which at least highlights the chat in red so you know one of your nets is full but a red highlight on the net itself would be much preferable so you know which of the nets is full and can see it better.
3. No way to implement this with current plugins as far as I know.
4. Currently I have the shoals tagged with NPC indicators, which really helps with visibility but does not show if I have tagged them or not.

**Additional context**
The suggestion about changing the highlight color for fish shoals pre/post tagging (suggestion 4) may be unbalanced, and ought to be discussed on whether it should be implemented. Much of the "skill" involved with Drift Net fishing involves remembering which shoals you have already clicked on and which you haven't, so this particular addition might be too much. The rest of the suggestions would be very welcome QOL.

**Comment by Allemaalbaas** [comment]
Support! I'd like to add that it is sometimes frustrating that you don't know how many fish there is in each net. Each net can hold 10 fish shoals. I'd like to see a little square with a fish in it and a number that shows the number of shoals (Design for square, like the make wines plugin).

**Comment by theFoof** [comment]
Is anyone working on this yet? I wanted to try making a plugin so I might do this if nobody else has.

**Comment by Nightfirecat** [comment]
After having spent a little time drift net fishing testing the loot tracker addition for it, I can confirm the following:

* #10865 has proper values for the widget group ID and inventory ID
* The following varbits are used:
  - 5812: Northern drift net status (0 = not set up, 1 = empty, 2 = has fish but not full, 3 = full)
  - 5813: Northern drift net catches (0-10, corresponding to # of fish caught)
  - 5814: Southern drift net status (see 5812)
  - 5815: Southern drift net catches (see 5813)
  - 5933: Drift net catch dialog status (0 = not open, 1 = viewing north net catches, 2 = viewing south net catches)
* Fish shoals have NPC ID 7782
* The following are the chat messages you get from prodding fish shoals: (unsuccessful and successful)
  ```
  2020-02-27 20:28:07 [Client] DEBUG net.runelite.client.RuneLite - Chat message type SPAM: The fish look at you strangely and carry on their way.
  2020-02-27 20:28:09 [Client] DEBUG net.runelite.client.RuneLite - Chat message type SPAM: You prod at the shoal of fish to scare it.
  ```

To anyone implementing/reviewing this feature, please make sure it lines up with that data.

**Comment by dekvall** [comment]
#10874 lines up with the data above
