### ISSUE TITLE
Idle notifier notifies on every cannonball craft

### ISSUE THREAD

**Issue by VKupliauskis** [runelite/runelite#9747]
While smelting an inventory of steel bars to cannonballs, the idle notifier notifies midway through each cannonball craft. 
It only notifies with "idle animations notifications" is checked, and ignores any timers set.

1. Take a cannonball mould and more than one steel bar.
2. start smelting the bars
3. Make the runelite window inactive.
4. Idle notification happens midway through the smelting of a cannonball batch.

**Expected behavior**
Idle notification happens at the end of ALL cannonball smelts.

**Screenshots**
Idle notification setup:
![image](https://user-images.githubusercontent.com/17051891/63766191-4f8ff580-c8d3-11e9-8db6-c86f6dbd5d3a.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - RuneLite version: 1.5.311

**Comment by Hydrox6** [comment]
That's because your delay is only 7 milliseconds. Cannonball smithing wants a much higher delay, probably around 2000. Keep adjusting until you find a good value

**Comment by VKupliauskis** [comment]
thank you, i was under impression it was seconds. 

Closing.

**Comment by Hydrox6** [comment]
Hovering over the label shows a tooltip with the full name on it, by the way
