### ISSUE TITLE
In game CoX item chance

### ISSUE THREAD

**Issue by The-Real-Gizzy** [runelite/runelite#9760]
**Is your feature request related to a problem? no

**Describe the solution you'd like**
Instead of having to pull up a calculator in my browser it could be instantly in-game next to your points in Chambers of Xeric

**Describe alternatives you've considered**
the only other option is to pull it up on a website that will calculate it for you so the coding behind it should not be difficult at all

**Additional context**
Ge-Tracker has one on their site. As well as other clients already having this ability.

**Comment by melkypie** [comment]
This has been added to a plugin-hub plugin called Raid Points overlay. If you don't know what plugin-hub is, here is some info: https://github.com/runelite/runelite/wiki/Information-about-the-Plugin-Hub
