### ISSUE TITLE
Idle Notifier Inconsistent Behavior

### ISSUE THREAD

**Issue by dpedu** [runelite/runelite#9761]
On macOs 10.14, whenever the Idle Notifier plugin sends a notification, the RuneLite window jumps to the foreground. E.g. if I was using a different application, RuneLite jumps in front of it as if I had command-tabbed to it.

On windows 10, RuneLite is not brought to the foreground when it sends a notification.

These behaviors should be consistent. 

Ideally, this behavior should be a toggle option in the plugin. Personally, I'm a fan of it jumping to the front.

**Comment by Alexsuperfly** [comment]
duplicate of #2335
