### ISSUE TITLE
Better Organization Idea for World Switcher.

### ISSUE THREAD

**Issue by FidgetyJester** [runelite/runelite#9763]
Think is can be annoying for both member and non-member to find a certain worlds. Especially for the non-member. Non-member cannot even join the member world, so they always have to look for a non-member world. And the fact that there are way too many member world makes it very more annoying for the non-member.

So to fix that. You should add a option to show only certain worlds. Like this one option have a toggle on and off option for both non-member and member worlds. If you toggle off for the member world, then you'll only see the non-member world.

Think that would be AWESOME, lol XD

**Comment by Hydrox6** [comment]
This is already a feature in the `World Hopper` plugin, under `Show subscription types`. This was added in https://github.com/runelite/runelite/commit/1a73893065ea7eae835c4dfb58275812f9a5258e

**Comment by FidgetyJester** [comment]
Oh ok. Thanks :D
