### ISSUE TITLE
Inventory tag color borders obscure edges of base item sprites [OSB Feature Mirroring]

### ISSUE THREAD

**Issue by Marstead** [runelite/runelite#9768]
**Describe the bug**
Inventory tag colors should add a clear outline to item sprites without covering or obscuring any part of the original item sprite. Instead, inventory tag colors cover parts of the edges of items, making the tags look messy. In OSBuddy, these tags outline items only outside of the existing sprites, avoiding the messy look.

**To Reproduce**
1. Add an inventory tag group to any group of items in RuneLite.
2. Add an inventory tag group to the same group of items in OSBuddy.
3. Compare the look and feel of the tags between OSBuddy and RuneLite

**Expected behavior**
The appearance of tags should be identical between OSBuddy and Runelite. Tags look cleaner when they do not obscure the original sprite.

**Actual Result**
The tags in Runelite obscure the original sprite with elements of the original sprite sometimes bleeding out behind the tag outline.

**Screenshots**
![Item Tags](https://user-images.githubusercontent.com/54672873/63944513-7ca0ed00-ca26-11e9-8837-fc512835844e.png)
![Item Tags Close Up](https://user-images.githubusercontent.com/54672873/63944519-7f9bdd80-ca26-11e9-9e93-60cbf0001bbb.png)

**Comment by Adam-** [comment]
fixed in 197c667edfb9ffc1500bb6e721eb0d0e4194dc3e
