### ISSUE TITLE
Ctrl + click any tickbox in the settings to create a toggle on/off keybind

### ISSUE THREAD

**Issue by Auxytocin** [runelite/runelite#977]
Not sure how UI friendly this would be, but I'm sure it'd be easier than only making certain options toggleable via keybinds, such as ground items, cannon hit spots, metronome, and boosted stats.

**Comment by deathbeam** [comment]
This should be specific to plugins, and seems like there is like almost no interest in this feature as its pretty generic. We already have open issues for both metronome, ground items and cannon (that shows the spots only if you have cannon in inv) so this issue is no longer relevant/way too much generic for no reason.

**Comment by Auxytocin** [comment]
It’s meant to be generic, allowing users more freedom as far as customization goes. The fact it is generic means you, the developer, has to do less work WHILE allowing users to have a customizable interface. I still think this type of UI would be very useful. Not sure if you misunderstood this or what.

**Comment by deathbeam** [comment]
It would not actually mean less work. Also as I said we have issues open already for your examples, and doing it per-plugin should be better anyway since we have the new hotkey config type.

**Comment by Auxytocin** [comment]
Fair enough. I haven’t been playing rs lately but since this was addressed I figured I’d address my original intentions for this issue. Anyways keep up the good work.

**Comment by Auxytocin** [comment]
It would require more effort to add keybind toggles for any tickbox compared to specifically tailoring options per plugin?

**Comment by deathbeam** [comment]
Yeah. We already have quite easy way to create keybind for specific options and check for it being pressed when its plugin specific, but making it generic would require us actually making something that works with that.

**Comment by Auxytocin** [comment]
Gotcha.
