### ISSUE TITLE
Add a method to EntityHiderBridgeMixin to hide specific NPCs

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#9775]
![image](https://user-images.githubusercontent.com/9074448/63978970-05b43480-cab8-11e9-87c3-212f3cddebab.png)
I want to hide Ancient Fungi, this is currently not possible. Add a method here which accepts a list of Strings of NPC's to be hidden, and from there this feature could be implemented.

**Comment by Nightfirecat** [comment]
Duplicate of #6854
