### ISSUE TITLE
Sidebars glitching weirdly

### ISSUE THREAD

**Issue by Leotarr** [runelite/runelite#9779]
weird graphic glitches on the side.

checkout out another thread where it says something with parameters fixed but i dunno how to do that -- https://github.com/runelite/runelite/issues/1449

![glitching out sadly](https://user-images.githubusercontent.com/54727296/64054323-d7515a80-cb86-11e9-9100-d097d996cd18.png)

win 10
gtx 980

**Comment by deathbeam** [comment]
Just follow the linked wiki page: https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration
