### ISSUE TITLE
XP Tracker - Undead Druids show "Actions remaining" instead of "kills remaining" when fought

### ISSUE THREAD

**Issue by DBHHeroesJojy** [runelite/runelite#9780]
![undeaddruids](https://user-images.githubusercontent.com/29988763/64055846-bcfe8900-cb54-11e9-8975-f8896f9dda82.PNG)

**Comment by DBHHeroesJojy** [comment]
Originally only tested with Toxic Blowpipe, without thinking that the venom's lack of XP might cause this. But I hit it with melee to be sure, and I still see actions remaining, not kills.

**Comment by Nightfirecat** [comment]
This is because there is no entry for them in [npc_health.json](https://github.com/runelite/runelite/blob/master/runelite-client/src/main/resources/npc_health.json)

**Comment by abextm** [comment]
Fixed by #9890
