### ISSUE TITLE
Keyboard Bank Pin

### ISSUE THREAD

**Issue by Pooooky** [runelite/runelite#9786]
**Is your feature request related to a problem? Please describe.**
No Problems, just convenience.

**Describe the solution you'd like**
Instead of clicking to put your bank pin in, you use your keyboard, it would save so much time.

**Describe alternatives you've considered**
None really.

**Additional context**
I tried out runelite plus and thought everything on it was ridiculously over powered, but i really liked the keyboard bank pin idea.

**Comment by Kamielvf** [comment]
As convenient as it sounds, this is not possible without faking input and thus will not be something we're doing as it resembles a very bot-like action.

**Comment by graingert** [comment]
@Paradoxis @Pooooky this feature came out in runelite 1.6.13 https://runelite.net/blog/show/2020-05-01-1.6.13-Release/

here's the commit that added it: https://github.com/runelite/runelite/commit/c1fdec9d2ed44302cbc93df4fcc7caba17bdfd9c

https://github.com/runelite/runelite/issues/9033
https://github.com/runelite/runelite/issues/9786
