### ISSUE TITLE
Having clickboxes enabled in the Herbiboar plugin causes massive FPS drops

### ISSUE THREAD

**Issue by Gamer1120** [runelite/runelite#9787]
I go from 15 FPS to 25-50 FPS when clickboxes are disabled. It might be an idea to disable the config option or optimize how clickboxes are rendered or something.

**Comment by Nightfirecat** [comment]
Related to #2898 maybe? I don't know what the resolution of that issue was.

**Comment by raiyni** [comment]
Probably an extension of #6528

**Comment by Gamer1120** [comment]
Here's a video. First a run with switching it off and on repeatedly, then a run with it off, then a run with it on. https://www.youtube.com/watch?v=GznnoxNklp8

**Comment by Gamer1120** [comment]
Since YouTube decides that it wants to keep my video at "Processing 0%", here's a direct download link: https://mega.nz/#!HtMxAAJL!rz-3M95NhSCVEqWT4H1f8n70lE6d25myfofjUoS2Y7E

**Comment by Adam-** [comment]
I think this is why we have the setting off by default. It doesn't happen to everyone necessarily and depends on a lot of factors. I'm not sure if there is a way we can improve it short of trying to improve the algorithm which does the click boxes.
