### ISSUE TITLE
Trouver's Parchment-protected items should be marked as always kept in the Items Kept On Death plugin

### ISSUE THREAD

**Issue by Nightfirecat** [runelite/runelite#9790]
https://oldschool.runescape.wiki/w/Trouver_parchment

> Once an item is locked, it will be kept in its unbroken state upon dying with it past level 20 Wilderness, but its locked status will be lost. In order to lock it once more, the parchment and the locking fee must be given to Perdu once more. For the killer, 75% of the locking fee is dropped as loot (37,500 coins for bronze to adamant defenders and 375,000 coins for all other lockable items).

I have no idea how it affects other items being protected. [Based on this video (see at 3:25)](https://youtu.be/-4tFoZjoArs?t=208), it seems that these items are kept in addition to whatever other items would be kept. I also do not know if these items affect items kept in non-PVP deaths/PVP deaths below 20 wilderness.

In any event, the items which this scroll can be applied to are found on these lines:

* [11182-11192](https://github.com/runelite/runelite/blob/cf65eb81cd4234dfd9d6652dd3cfdeb0133dbb75/runelite-api/src/main/java/net/runelite/api/ItemID.java#L11182-L11192)
* [11199-11228](https://github.com/runelite/runelite/blob/cf65eb81cd4234dfd9d6652dd3cfdeb0133dbb75/runelite-api/src/main/java/net/runelite/api/ItemID.java#L11199-L11228)
* [11234](https://github.com/runelite/runelite/blob/cf65eb81cd4234dfd9d6652dd3cfdeb0133dbb75/runelite-api/src/main/java/net/runelite/api/ItemID.java#L11234)
* [11236](https://github.com/runelite/runelite/blob/cf65eb81cd4234dfd9d6652dd3cfdeb0133dbb75/runelite-api/src/main/java/net/runelite/api/ItemID.java#L11234)
* [11238](https://github.com/runelite/runelite/blob/cf65eb81cd4234dfd9d6652dd3cfdeb0133dbb75/runelite-api/src/main/java/net/runelite/api/ItemID.java#L11238)
* [11240](https://github.com/runelite/runelite/blob/cf65eb81cd4234dfd9d6652dd3cfdeb0133dbb75/runelite-api/src/main/java/net/runelite/api/ItemID.java#L11240)
* [11242](https://github.com/runelite/runelite/blob/cf65eb81cd4234dfd9d6652dd3cfdeb0133dbb75/runelite-api/src/main/java/net/runelite/api/ItemID.java#L11242)
* [11250-11252](https://github.com/runelite/runelite/blob/cf65eb81cd4234dfd9d6652dd3cfdeb0133dbb75/runelite-api/src/main/java/net/runelite/api/ItemID.java#L11250-L11252)

**Comment by makingcomment** [comment]
The Items Kept On Death plugin no longer exists.
