### ISSUE TITLE
client.getCollisionMaps() always returns null

### ISSUE THREAD

**Issue by rokaHakor** [runelite/runelite#9792]
getCollisionMaps() does not seem to be working it always returns null. I am trying to create a plugin to check line of sight but having problems since getCollisionMaps() keeps returning null.

**Comment by JamesLear92** [comment]
What's the point of the API then?

**Comment by ThatGamerBlue** [comment]
it works in instances, see: https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/mta/telekinetic/TelekineticRoom.java#L454
