### ISSUE TITLE
4k, 16x Anti Ailiasing, animation smoothing GPU requirements

### ISSUE THREAD

**Issue by Menst** [runelite/runelite#9797]
Hi everyone,

I know this isn't an issue but I thought there would be no better place to ask then on here. So I'm thinking of downgrading my system from a vega 64 to a RX560 16cu 4gb. I have a 4k monitor (16:9), and was wondering if the RX560 would be enough the drive the client at 4k, 16x anti-ailiasing with animation smoothing. I have ryzen 5 3600 and 16gb (2x8) of memory. Sorry if this is in the wrong place and thanks for taking the time.

**Comment by Elpan1** [comment]
I would suggest asking on their official community discord channel as that would be more appropriate. Link on their website and here on github.

**Comment by Menst** [comment]
Awesome, I'll go there. Thanks for the help.
