### ISSUE TITLE
Monster tick attack counter

### ISSUE THREAD

**Issue by Frooby91** [runelite/runelite#9799]
**Is your feature request related to a problem?
no

**Describe the solution you'd like**
I would like it to show me the amount of ticks until the monster attacks so I can know exactly when to prayer flick the monster. This is also very helpful when flinching.

**Describe alternatives you've considered**
N/A

**Additional context**
Runelite plus has this but I do not want to give them my login details.

**Comment by Adam-** [comment]
Considering this would impact basically every boss everywhere I'm going to go with "no" unless there is some non-fringe demand for it.
