### ISSUE TITLE
switch "teleport" and "teleport to POH" on construction cape?

### ISSUE THREAD

**Issue by CaraPis** [runelite/runelite#980]
Hi, i don't think many people actually use the teleport option on the construction cape, so could the options maybe be switched?

Regards, Cara

**Comment by ShaunDreclin** [comment]
Could you screenshot the ops the cape has in the inventory and while equipped?

**Comment by CaraPis** [comment]
yea sure:
inventory: https://i.imgur.com/Yk7GICY.png
Equipped: https://i.imgur.com/wSHbj0s.png

**Comment by alex-vincent** [comment]
Been working on this, first github contribution :) [#1058](https://github.com/runelite/runelite/pull/1058)

**Comment by ShaunDreclin** [comment]
I think we decided we don't want to do left click teleport on equipped items, that should be a shift-click thing

**Comment by Stickaplex** [comment]
Can do it so only works so it just switches the 2 options. So would still be left click tele to poh while its in invy
