### ISSUE TITLE
Wrong achievement requirement (Karamja hard: Kill a metal dragon)

### ISSUE THREAD

**Issue by jachymb** [runelite/runelite#9808]
**Describe the bug**
The achievement diary requiement plugin says I need 12 Agility + 34 Woodcutting to kill a metal dragon in Brimhaven dungeon. This is not true, you can use the southern dungeon entrance which has no such requirement and is closer to the dragons anyway.

**To Reproduce**
Open the Karamja Achievement diary guide, scroll to hard.

**Expected behavior**
No skill requirement for this task.

**Comment by Elpan1** [comment]
The southern entrance has a one time fee of 5000 trading sticks.

**Comment by jachymb** [comment]
Yes, but getting these does not require any skill, imo even for ironmen. You can get them by exchanging jades/opals which can be obtained in various ways.

**Comment by Elpan1** [comment]
I guess that's one way of seeing it. It's a very quick fix, however I don't know the others opinion about this matter.

**Comment by Hydrox6** [comment]
The requirements are low, to the point where most accounts will have them well before doing the hard diary, and the 5k trading sticks have quite a bit of use. The accounts that don't want to or can't get those requirements will likely already know of the trading stick method.

**Comment by trelkins3** [comment]
Is the best way to fix this simply to remove the level requirement text? Any update on this?

**Comment by Elpan1** [comment]
The requirements for going trough the dungeon is **12 agility** and **34 woodcutting**. However, there exists an alternative method of paying **5k** trading sticks to bypass mentioned requirements. Which of these cases to choose and how to formulate this in the guide is merely a question of Runelite standards. How are stuff like this usually done, based on mechanical requirement or alt. methods?

**Comment by dekvall** [comment]
Fixed in 9321d6e64e1fed4d52b8bee51b709c9fe8384e7a.
