### ISSUE TITLE
Make LMS rank overlay movable

### ISSUE THREAD

**Issue by kendall2307** [runelite/runelite#9818]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]
https://imgur.com/VIkIr8V
this menu at lms is extermely inconvient since in middle of screen cant see someone running at u or your own prays.. 

**Describe the solution you'd like**
please make it moveable like exilent has it. it came with jagex new update today
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
able to take it away completely?
**Additional context**

**Comment by Adam-** [comment]
https://twitter.com/JagexRoq/status/1173970566790942721
