### ISSUE TITLE
Clue answer (drawers) not being highlighted

### ISSUE THREAD

**Issue by gc** [runelite/runelite#9819]
Usually clue answers highlight drawers/crates/etc if you need to search them, this clue doesnt.

Clue: `Monk's residence in the far west. See robe storage device.`
Clue Tier: Easy

Expected: highlight the drawers that you need to search
Actual: An arrow is shown in the tent

Shown in image:
![unknown](https://user-images.githubusercontent.com/30398469/64402895-cab69000-d0b9-11e9-8f66-2bda364cc673.png)

**Comment by gc** [comment]
Same with this clue:

![image](https://user-images.githubusercontent.com/30398469/64486786-09dd1080-d275-11e9-9c13-020b46a6ae0e.png)


![image](https://user-images.githubusercontent.com/30398469/64486775-f9c53100-d274-11e9-8b3f-d39a08212a9a.png)

**Comment by TaylorRatliff** [comment]
I just noticed the drawers weren't highlighted when I did the monk's clue today. I believe I have the solution for the issues
