### ISSUE TITLE
Allow Bank and Inventory Tags for degradable (Barrows etc.) items to be set for all degradation levels

### ISSUE THREAD

**Issue by zombiezrule** [runelite/runelite#9825]
Having barrows items degrade after you've added a new tag to them makes it seem like they aren't added to the tag, as only one degradation level has the tag added. Would be nice to add an option to the bank tags plugin to have degradable items have shared tags amongst each stage, e.g. tag "Karil's Leathertop" with "bandos" and all degradation states are given that tag. 
Also, having the inventory tag (coloured outline) set the same for all states would be nice.

This should be kept as an option and not made standard, as I'm sure some people who are rich enough have multiple sets and don't want to take nearly degraded sets PKing or wherever else.

**Comment by Alexsuperfly** [comment]
put a `*` after the name when tagging, or shift drag it into a tag tab
