### ISSUE TITLE
Can't delete copy pasted text if key remapping is enabled

### ISSUE THREAD

**Issue by RaidanAlyssi** [runelite/runelite#9828]
When key remapping is enabled and the chat says "Press Enter to Chat", if you copy paste and press enter it'll send what you've copy and pasted. There's no way to delete what was copy and pasted easily.

**Comment by Adam-** [comment]
You can't paste into the chat.

**Comment by RaidanAlyssi** [comment]
Oh, I use runeliteplus and thought this was an issue with a runelite plugin. My bad.
