### ISSUE TITLE
2 Hot n  Colds in a row results in 0 possible locations

### ISSUE THREAD

**Issue by gc** [runelite/runelite#9830]
Doing beginners clues, I noticed this:

If you get 2 Hot/Cold clue steps in a row, for the second one you'll always have to drop the clue and pick it back up, as it shows 0 possible locations.

To reproduce, do a lot of beginner clues (??) until you get 2 Hot/Colds' in a row.

**Comment by Nightfirecat** [comment]
I'm pretty sure this should be handled, but I'll take a look at this.
