### ISSUE TITLE
Runelite crashes upon entering Stronghold of Security and other dungeons.

### ISSUE THREAD

**Issue by CilloDemon** [runelite/runelite#9836]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
When Runelite is running and I enter a dungeon, it crashes, however running OSRS normally does not reproduce this crash.
**To Reproduce**
1. Go to Stronghold of Security

**Expected behavior**
I expected Runelite not to crash upon entering a dungeon, but instead it does.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - OS: Windows 10, 64 bit
 - RuneLite version: 1.5.32
 - Launcher version: Latest

**Additional context**
Latest client and launcher logs included as files.
[client.log](https://github.com/runelite/runelite/files/3588018/client.log)
[launcher.log](https://github.com/runelite/runelite/files/3588019/launcher.log)

**Comment by CilloDemon** [comment]
I'd love it if someone could tell me if this is an issue on my end or if it's a known bug that others are having, I can't stand playing Old School without Runelite ever since I tried it out.

**Comment by Rengifo00** [comment]
Seems like it's a problem with the GPU plugin, had the same problem and solved it by disabling it.
