### ISSUE TITLE
Green friends on map

### ISSUE THREAD

**Issue by Barpodi** [runelite/runelite#9845]
I know that there is currently a setting to show friends on the mini map in a certain colour but these friends need to have you added. 
I was wondering if you could have it so that if you have that person added it would show up as green, regardless of the fact they wouldn't have you added.
This would help me out in PVP so much. 
Osbuddy does it and as your the better app i was hopping you would ;)

**Comment by Kamielvf** [comment]
The plugin respects peoples privacy settings, this is intended behaviour and is not a subject to change. If you wish you can use the other setting inside the plugin that shows anyone who is not in your clan/friendslist as red on your screen.

**Comment by Hydrox6** [comment]
Duplicate of #950
