### ISSUE TITLE
Add "Bring 20gp" to the Gu'Tanoth Coord Clue Text

### ISSUE THREAD

**Issue by djohns2021** [runelite/runelite#9847]
**Is your feature request related to a problem? Please describe.**
The Gu'Tanoth coordinate clue requires 20gp to cross the bridge. It would be extremely useful if the clue description RL provides included this information.

**Describe the solution you'd like**
Add in a hint text after Gu'Tanoth, so it reads as "Gu'Tanoth, bring 20gp." as a friendly reminder.
Line of text in question:
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/cluescrolls/clues/CoordinateClue.java#L97

**Additional context**
Another example of a coordinate clue having help text is in the line directly below the text for this one. It reads, "Gu'Tanoth island, enter cave north-west of Feldip Hills (AKS)."
If it would help, I can submit a PR for this request tomorrow.

**Comment by jmandli12** [comment]
I actually ran into this today. Good find

**Comment by Nightfirecat** [comment]
I think that's only needed if you've not completed the requisite step of the Watchtower quest? I've never needed 20gp for that step.

**Comment by Nightfirecat** [comment]
Ok, I've figured out what the deal is. You do need 20gp at least once to jump over the bridge, but if you teleport out rather than take the bridge back, you can cross without needing the gold the next time you go to this clue location. So long as you continue to use teleports to leave that location instead of taking the bridge back the other way, you would not need to bring 20gp to that location again.

**Comment by djohns2021** [comment]
Yep, I still think this is a good change as that is an intended feature in the game ( https://twitter.com/JagexAsh/status/1172245332106907648). This is similar to the text for "Gu'Tanoth island, enter cave north-west of Feldip Hills (AKS)," where the cave description is present even though it's the same cave every time.

**Comment by Adam-** [comment]
Just making the clue text say "bring 20gp for bridge jump" is also wrong since you can be in a state where you don't need 20gp for the bridge jump. If I had to guess probably most people are in this state since most people just teleport after digging for the chest. Maybe "May require 20gp"?

**Comment by djohns2021** [comment]
Doesn't matter to me which way we go with this as long as it mentions the 20gp haha.

**Comment by djohns2021** [comment]
@Adam- I'm good with your suggestion. If that's what we want to go with, could you add your suggestion as a review in the PR?

**Comment by Adam-** [comment]
Okay

**Comment by djohns2021** [comment]
Thanks, made making the change easier as I don't currently have the code pulled down on my machine.
