### ISSUE TITLE
Menu Entry Swapper for Razmire Keelgan (Limestone)

### ISSUE THREAD

**Issue by eroomleinad7** [runelite/runelite#9850]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I misclick while trading Razmire Keelgan in Mort'ton. This NPC has 2 trade options "Trade-General-Store" and "Trade-Builders-Store". The store that is accessed repeatedly is the "Trade-Builders-Store" as it is a supply of limestone for training construction.

**Describe the solution you'd like**
Please add the option to toggle the menu entry swapper for this NPC so that you can left click him to trade "Trade-Builders-Store" as there is this option for almost every other NPC.

**Describe alternatives you've considered**
I have tried to get used to right clicking this NPC but this is a well used NPC and many people would benefit from this change. I have spent many hours thinking of alternate solutions and tried mouse keys with no success.

**Additional context**
This is a viable construction training method for Ironman and it would benefit many people. Also this NPC has 2 different forms one is "afflicted (Razmire)" and the other is "Razmire Keelgan". So to even be able to trade this NPC you must first click "Talk-to-Afflicted (Razmire)" then (after the completion of the Shades of Mort'ton quest) this NPC will change to "Razmire Keelgan" with the 2 different trade options. So the process of trading him is already lengthily so to also have to right click trade him it makes it very difficult.
![Afflicted (Razmire)](https://user-images.githubusercontent.com/55238607/64781260-4d56a980-d517-11e9-8dc2-00de47f2929e.png)
![Razmire Keelgan](https://user-images.githubusercontent.com/55238607/64781266-521b5d80-d517-11e9-8019-9bbcd807d6e2.png)

**Comment by eroomleinad7** [comment]
Am I able to bump this thread? Or do I just wait for someone to reply? Thank you!

**Comment by Nightfirecat** [comment]
This is a niche feature that is best suited for the plugin hub, and is currently covered by the Menu swapper extented plugin there. See runelite/plugin-hub#42
