### ISSUE TITLE
Fake Ironman Chat Icon

### ISSUE THREAD

**Issue by mrkingsly** [runelite/runelite#9857]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Non ironman accounts have a plugin to put a fake ironman, jmod icon in their chatbox.
Saw Skidder, EvScape, Purpp & RonPlaysGames use one and it would be cool to have for everyone to use in my opinion
![IronmanHelm](https://user-images.githubusercontent.com/19797660/64874583-79df0280-d68a-11e9-82a9-3c01c01bbc16.png)

**Comment by Nightfirecat** [comment]
This is not something we want to support.
