### ISSUE TITLE
Removing higlights from world objects?

### ISSUE THREAD

**Issue by UncleZeebs** [runelite/runelite#9859]
This isn't so much a bug report as a request for help. I only just started using Runelite and one feature I don't like is the highlighting of world objects, as it takes me out of the game. I figured out how to disable agility shortcut highlights, but there are still highlighted objects like the stile in the picture below.
![2019-09-13_12-50-50](https://user-images.githubusercontent.com/55292115/64880267-c80dea80-d625-11e9-837d-6cc4bffd4fc9.png)
I am not using the object marker to highlight this and I have no idea which function is doing it. I really want this turned off. Please let me know if there's any other information I can provide.

**Comment by xnemesis** [comment]
This is a feature of the agility plugin. If you navigate to this, you can then disable highlighting of agility objects.
Queries like this are often best posted on help forums or in the discord channel.
