### ISSUE TITLE
Shortcut Highlight for MLM upper level ladder

### ISSUE THREAD

**Issue by pluffindonk** [runelite/runelite#9860]
**Is your feature request related to a problem? Please describe.**
When I'm mining in MLM while doing something else I find it can sometimes take a extra moment to find the ladder, especially if the camera is top down.

**Describe the solution you'd like**
A green highlight on the upper level ladder.

**Describe alternatives you've considered**
Me being less lazy.

**Comment by Hydrox6** [comment]
The ladder can be marked with Object Markers already
