### ISSUE TITLE
Any way to get Item Type

### ISSUE THREAD

**Issue by extreme4all** [runelite/runelite#9863]
i'm looking to get the item type of all the items, i found something basic but this does not include all items:
runelite/runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/

Could the API provide one or more types or categories for each item:
example:
rune crossbow:
-weapon;ranged;fletching
gold ore:
-ore;mining;smithing
gold bar
-bar;smithing;crafting

**Comment by Hydrox6** [comment]
This is not something the game even has. `Item Identification` doesn't have everything because it is a plugin with very specific uses. Getting that list is something you'd have to do yourself manually.
