### ISSUE TITLE
Missing cannon spots

### ISSUE THREAD

**Issue by rune3132** [runelite/runelite#987]
I have made a list of (what I think is) all the missing monsters and their respective spots. Attached is a link to images of all the spots. [Link](https://imgur.com/a/lVHJt)
- Brine rat(2707, 10132, 0)
- Dagganoth(2524, 10020, 0)
- Dark beast(1992, 4655, 0)
- Dust devil(3218, 9366, 0)
- Kalphite(3307, 9528, 0)
- Lesser demon(2838, 9559, 0)
- Lizardmen(1500, 3703, 0)
- Scabarites/minions of scarabas(3297, 9252, 0)
- Smoke devil(2398, 9444, 0)

**Comment by Adam-** [comment]
Added in #566
