### ISSUE TITLE
MacOS Mojave: while key remapping is toggled unable to type in runelite. 

### ISSUE THREAD

**Issue by SYNflood404** [runelite/runelite#9873]
**Describe the bug**
While using MacOS I cant use the feature "key remapping" as it makes it impossible to type in the runelite client e.g. calculator, high scores, grand exchange. typing in OSRS chat works as intended. 

**To Reproduce**
1a. toggle "key remapping" feature ON
1b. toggle "remap camera" ON
1c. toggle "remap F keys" OFF
2. close and reopen runelite 
3. login
4. type in chat
5. use camera feature
6. click to move character
7. type anywhere in runelite client eg. search grand exchange. (if you're able to type repeat steps 4, 5 and 6)

**Expected behavior**
I should be able to type into the runelite client e.g. search grand exchange, use calculator, ect. 

**Environment (please complete the following information):**
 - MacOS Mojave
 - RuneLite version: 1.5.33.1
 - Launcher version: 1.6.2

**Comment by Alexsuperfly** [comment]
could this be related to #3514 or #6948 in any way?

**Comment by SYNflood404** [comment]
Just tested. Holding down 'a' with key mapping turned off seemed to produce the same bug.
