### ISSUE TITLE
Suggestion for menu entry swapper

### ISSUE THREAD

**Issue by sswetonic** [runelite/runelite#9877]
Doing farm runs a lot I noticed there isn't a menu entry swapper option for cleaning herbs. This would make farm runs a lot easier not having to right-click to use grimy herbs every time.

**Comment by Hydrox6** [comment]
You can already do this with the [Shift Click configuration](https://github.com/runelite/runelite/wiki/Menu-Entry-Swapper#shift-click-configuration)
