### ISSUE TITLE
Loot Tracker - Adding a fixed value to Tattered Pages

### ISSUE THREAD

**Issue by DBHHeroesJojy** [runelite/runelite#9881]
The Tattered Pages dropped from the monsters in Forthos Dungeon are untradeable and (I believe) unalchable, however they do have value. After completion of the "In Search of Knowledge" miniquest, the pages can be turned in to the librarian in Arceuus Library for 1,000 gold each. It would be nice to see that reflected in the tracker, if possible.

**Comment by EvanWalden** [comment]
Long and Curved bones can similarly be exchanged for some gold.
