### ISSUE TITLE
Menu Entity Swapper: Store All instead of Store-1 as default on Rune Pouch

### ISSUE THREAD

**Issue by RansomTime** [runelite/runelite#9883]
When changing the runes in the Rune Pouch (the bounty hunter store inventory space saver, not the rune essence pouch), the default option is Store-1/Withdraw-1, would it be possible to add an option in the swapper to swap that to Store-All, as I'm willing to bet that's the behaviour that most people want to do when using this.

**Comment by Nightfirecat** [comment]
People who want to store all their runes most often simply use their rune stack with a pouch while in their inventory, outside of the pouch interface. I feel this would be so niche that it would not benefit most users.

**Comment by RansomTime** [comment]
I honestly didn't realise that this could be done. Gonna close this one because use is much easier
