### ISSUE TITLE
Ability to make the sidebar as a whole (including text) bigger

### ISSUE THREAD

**Issue by Capepanwa** [runelite/runelite#9884]
I'd like to suggest the ability to make the sidebar of RL as a whole, bigger. i play from the sofa and im some distance away from the monitor. ingame this works fine but the sidebar is rather small and hard to read. 
i'm sure i wont be the only one with this issue and giving us the option to make the sidebar bigger would be a nice addition to the gaming experience.

thanks,

**Comment by EvanWalden** [comment]
I agree that this would be nice as a built int feature.

In the meantime, your operating system may be able to scale applications for you. For example in windows 10 there is an option under Start > Settings > System > Display > Scale and Layout  > Change the size of apps, Text and other items.

**Comment by LlemonDuck** [comment]
This can be done by passing the --scale option to the launcher, e.g. --scale=2 to double the size)

Follow the same instructions as [Disabling Hardware Acceleration](https://github.com/runelite/runelite/wiki/Disable-Hardware-Acceleration#disabling-hardware-acceleration), but replace --mode=OFF with --scale=N, where N is your desired scaling factor
