### ISSUE TITLE
Invisible Draynor rooftop course 

### ISSUE THREAD

**Issue by Cetacean87** [runelite/runelite#9885]
**Describe the bug**
Draynor rooftop is invisible, I do not know how this happened, relogging and rehopping back onto the course top doesn't change the situation, neither does hopping. 

**To Reproduce**
hop on to the rooftop course unless this is only my runelite

**Expected behavior**
You can't even finish the course

**Screenshots**
https://gyazo.com/3a9539c896ac2be30ce17c359797c303

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: [e.g 1.4.6]
 - Launcher version: [e.g 1.5.2]

**Comment by Alexsuperfly** [comment]
turn off low detail
