### ISSUE TITLE
Stored Local Loot Tracker

### ISSUE THREAD

**Issue by bitesized** [runelite/runelite#9886]
Suggestion for a stored local loot tracker that could be divided into bosses, similar to that of another client that I won't name :)

**Comment by Kamielvf** [comment]
Similar features like this (storing locally) have been discussed before and they were not something we want to do. Currently we provide a way to export your loot tracker through the website after logging in, which you can do whatever you like with afterwards.
If you mean an addition to the already existing sidepanel, please specify in detail in your request  and we can reopen this issue.
