### ISSUE TITLE
GPU Rendering Crashes

### ISSUE THREAD

**Issue by amerheb** [runelite/runelite#9889]
Hey everyone,

Lately, every time I've been playing with the GPU renderer on, I've had my game randomly crash on me. 

Here is a pastebin of the error log: https://pastebin.com/L4Ez9ux8

The crash error happens here:

> 2019-09-19 00:46:36 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: Error swapping buffers
    at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
    at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
    at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1121)
    at bn.uw(bn.java:52168)
    at bn.l(bn.java)
    at bn.run(bn.java:326)
    at java.lang.Thread.run(Thread.java:748)
>

My GPU is an EVGA GTX 1080 FTW. Any idea if this is a client based issue, or hardware?

**Comment by thomasdelamp** [comment]
> Hey everyone,
> 
> Lately, every time I've been playing with the GPU renderer on, I've had my game randomly crash on me.
> 
> Here is a pastebin of the error log: https://pastebin.com/L4Ez9ux8
> 
> The crash error happens here:
> 
> > 2019-09-19 00:46:36 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
> > com.jogamp.opengl.GLException: Error swapping buffers
> > at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
> > at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
> > at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1121)
> > at bn.uw(bn.java:52168)
> > at bn.l(bn.java)
> > at bn.run(bn.java:326)
> > at java.lang.Thread.run(Thread.java:748)
> 
> My GPU is an EVGA GTX 1080 FTW. Any idea if this is a client based issue, or hardware?

hey did you ever get a fix for this?

**Comment by GitToTheChoppuh** [comment]
@thomasdelamp, I also get a similar issue from time-to-time. I have the RuneLite GPU plugin enabled with:

- Draw Distance: 50
- Remove Color Banding: False
- Anti Aliasing: Disabled
- Fog Depth: 5

Running on an AMD Radeon RX 5700 XT

> 2020-02-24 18:05:15 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
> com.jogamp.opengl.GLException: Error swapping buffers
> 	at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
> 	at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
> 	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1100)
> 	at bf.cg(bf.java:56571)
> 	at bf.g(bf.java)
> 	at bf.run(bf.java:328)
> 	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by RahilSagarwala** [comment]
Looking for a fix too. Nvidia GeForce GT 750M

**Comment by j-c-o-n** [comment]
Looking for a fix too. Nvidia GeForce GT 750M

**Comment by j-c-o-n** [comment]
was working for the past week, restarted with this weeks update and now GPU is unplayable again

**Comment by j-c-o-n** [comment]
@RahilSagarwala try running with the integrated graphics processor instead of NVIDIA, it's working for me at the moment.

**Comment by j-c-o-n** [comment]
Don't try what I suggested above... CPU crashed during the last phase of Olm...

I think I found an actual solution though: https://i.imgur.com/LSp7B9h.png
source: https://www.reddit.com/r/2007scape/comments/9zii1k/step_by_step_gpu_instructions_runelite/ea9esa1/

This seems to resolve the issue that I was having.

**Comment by MESLewis** [comment]
Join us at https://runelite.net/discord in the #support channel so we can fix this issue for you.
