### ISSUE TITLE
GPU Plugin causing double mouse cursor

### ISSUE THREAD

**Issue by aujared** [runelite/runelite#9891]
**Describe the bug**
When GPU plugin is enabled I sometimes get a second mouse cursor appearing under my mouse, or a slight trail

**To Reproduce**
1. Enable GPU plugin
2. Move Mouse Around
3. Disable GPU plugin

**Expected behavior**
Normal Cursor behavior can only be achieved by disabling the GPU plugin

**Screenshots**
[![Screenshot from Gyazo](https://gyazo.com/07eecbb155f132eb537fa34b304677d3/raw)](https://gyazo.com/07eecbb155f132eb537fa34b304677d3)
https://gyazo.com/07eecbb155f132eb537fa34b304677d3

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: [1.5.331]

**Additional Details**
This is a laptop with integrated graphics and a dedicated Nvidia GPU, perhaps this is causing the issue? I do not experience this on my desktop which only has the dedicated gpu.

I had a issue with the sidebar glitching, but this was remedied by disabling hardware acceleration

**Comment by abextm** [comment]
https://github.com/runelite/runelite/wiki/GPU-FAQ#there-are-two-mouse-cursors-when-gpu-is-on
