### ISSUE TITLE
Weird bug when i log in to the game

### ISSUE THREAD

**Issue by MrXerax300** [runelite/runelite#9895]
when i log in to the game, i get this weird text bar trailing and also the mouse was trailing too, how do i fix this? i tried uninstalling and reinstalling runelite,and it still does the same thing. also i tried with the the oldschool client it works perfectly fine.
![Untitled](https://user-images.githubusercontent.com/55608389/65365721-c75af280-dbe9-11e9-9acd-1af2883fa2c0.jpg)

**Comment by huddy987** [comment]
So a couple things that might be useful to know: What operating system are you using? What hardware are you using? Is the “GPU” option turned on or off in Runelite?

**Comment by Alexsuperfly** [comment]
thats gpu on with an AA level too high for your card

**Comment by MrXerax300** [comment]
> So a couple things that might be useful to know: What operating system are you using? What hardware are you using? Is the “GPU” option turned on or off in Runelite?

windows 10 pro and yes i have gpu option on

**Comment by MrXerax300** [comment]
> thats gpu on with an AA level too high for your card

oh thank you :) , i had it on x16 but it was working fine before, but i lowered it to x2 and now it's working fine
