### ISSUE TITLE
Warning: Illegal reflective access operation

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [runelite/runelite#9909]
**Describe the bug**

Running RuneLite generates the following warning in the output:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.runelite.client.config.ConfigInvocationHandler (file:/C:/Users/username/Documents/Programming/Development/Open-Source-Contributions/runelite/runelite-client/target/classes/) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of net.runelite.client.config.ConfigInvocationHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The client launches just fine, though.

**To Reproduce**

1. Checkout bac42955f on master.
2. Run the `RuneLite` class from `runelite-client`.
3. Note the warning under the Run tab.

**Expected behavior**
Not sure, but is this something I should be concerned about in general? I'm not sure what illegal access operations it's referring to.

**Screenshots**

![image](https://user-images.githubusercontent.com/19352442/65472137-f4084780-de3f-11e9-9802-a57c7c57ad98.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Home, 64-bit
 - RuneLite version: N/A (bac42955f on master)
 - Launcher version: Not sure where to get this

**Additional context**
N/A

**Comment by Adam-** [comment]
This is basically because we aren't using Java 9's module system, but you are running it on 9+. It's fine to ignore for now. Its not clear to me if we can fix it without breaking compatibility with 8, which we cannot do.

**Comment by AleksandrHovhannisyan** [comment]
Gotcha, thanks for clarifying! We can close this, then.

**Comment by AlanBateman** [comment]
The warning looks genuine. It is alternating to your code in net.runelite.client.config.ConfigInvocationHandler that is hacking into a private constructor in MH.Lookup. That constructor doesn't exist in JDK 14 EA builds. Is there any reason why you aren't using MethodHandles.privateLookupIn ?

**Comment by deathbeam** [comment]
privateLookupIn is Java 9+ afaik, and we still use java 8 as target, I think?

**Comment by AlanBateman** [comment]
Lots of goodies in JDK 9+ to help with cases like this. Look at `javac --release 8` and Multi-Release JARs.

**Comment by Adam-** [comment]
I think this is a valid issue still and probably shouldn't be closed, though I am not sure we have a resolution to it other than moving off of 8.

**Comment by abextm** [comment]
There are other issues related to running the client on jdk14 — the vanilla client calls methods that no longer exist.

**Comment by skrttskrtt** [comment]
I am also having this issue, Has it been solved or am I blind?

**Comment by Adam-** [comment]
It's being worked on. I recommend using either Java 8 or 11 as those are the only two things we officially support.

**Comment by cluzier** [comment]
So it looks like the solution to this is to just use Java 8 or 11? Has this been patched yet? I am having this exact issue right now.

**Comment by Adam-** [comment]
> 
> 
> So it looks like the solution to this is to just use Java 8 or 11? Has this been patched yet? I am having this exact issue right now.

I believe most of these are fixed now, what error are you getting?

**Comment by dginovker** [comment]
Anyone getting this, make sure you do Runelite > Lifecycle > install again on the right-hand Maven tab
