### ISSUE TITLE
Menu Entry Swapper: Quickleaving Pyramid Plunder

### ISSUE THREAD

**Issue by Emil-Hammer** [runelite/runelite#9912]
I would like for a menu entry swapper option on the tomb door in Pyramid Plunder so you can quick leave.

**Comment by Hydrox6** [comment]
Start-minigame is a duplicate of #7138

If you could edit the title and description to focus on the quick leave request, that would be great 👍

**Comment by Emil-Hammer** [comment]
Of course. I was trying to search but couldn't find anything.

**Comment by whartd** [comment]
Wouldn't this fall under the category of a feature that "leads to you using fewer clicks than you would when using our client."? This would now be explicitly bannable.

**Comment by Emil-Hammer** [comment]
> Wouldn't this fall under the category of a feature that "leads to you using fewer clicks than you would when using our client."? This would now be explicitly bannable.

#9950

**Comment by Adam-** [comment]
added in 5344cd6ddbd0e435bad7a088dbc266738319a5fc
