### ISSUE TITLE
Expeditious Bracelet gets stuck at 2 charges

### ISSUE THREAD

**Issue by zJolt** [runelite/runelite#9916]
Please check if your issue is not a duplicate by [searching existing issues](https://github.com/runelite/runelite/search?type=Issues)

**Describe the bug**
On a slayer task the bracelet functions normally until 2 charges and then doesn't update unless you manually check the charges.

**To Reproduce**
1. Use bracelet during task until 3 charges left
2. Get kills until you see a notification your bracelet speeds up your task
3. Bracelet will now not update past 2 charges remaining.

**Expected behavior**
Bracelet should say 2 charges remaining, then 1 charge remaining.

**Screenshots**

**Environment (please complete the following information):**
Windows 10 64bit
Latest RuneLite version

**Comment by Nightfirecat** [comment]
Do you have screenshots of the chat messages that appear when you would expect to see the charge counter hitting 2 charges, then 1 charge? Also, can you post your `client.log` file from the day you noticed this bug?

**Comment by Nightfirecat** [comment]
This issue is extremely old, has no further information provided, and is likely no longer valid with the code of the item charges plugin today. Thus, I'm closing it.
