### ISSUE TITLE
Cooking Burned % is wrong

### ISSUE THREAD

**Issue by Xowie89** [runelite/runelite#9928]
I have cooked 1027 swordfish and burned 335 it says the percentage is 24.6% but the real percentage (335/1027)*100 is 32.61% quite a big difference. 

![Image](https://user-images.githubusercontent.com/41758045/65762859-03152100-e0f0-11e9-86f5-9a00aa2a3273.png)

Not that big of a deal but when cooking for xp and attempting to buy/fish/gather
 exact amounts to reach a specific level this could be frustrating.

**Comment by steffenhauge** [comment]
Well actually it's (335/(1027+335))*100=24.6%, since the total amount is the cooked + the burned :)

**Comment by Kamielvf** [comment]
You have successfully cooked 1027, burnt 335 which adds up to a total of 1362 attempts.
The percentage is correct.
