### ISSUE TITLE
Buying clue items

### ISSUE THREAD

**Issue by LewisKappa** [runelite/runelite#9933]
Soo, not 100% sure if this is possible, but... 
https://i.gyazo.com/256f74544c9975c9c4c4ef49448f1854.png

![github idea](https://user-images.githubusercontent.com/55903186/65810003-9015b400-e19c-11e9-88e4-3347b09f3e24.png)

So let's say you're on the GE screen, as it is above, and you have the clue scroll items required... Would it be possible to maybe click on the item requirement, and it opens it up on the buy menu on the ge? Not sure, sorry if I've added this to wrong place, first post ever...

Thanks for reading anyway, and yess!! I know about the stash places but meeh :D

**Comment by abextm** [comment]
This would be handled by #6236
