### ISSUE TITLE
Day/night cycle 

### ISSUE THREAD

**Issue by Benoit-vg** [runelite/runelite#9934]
Hi,

Something that I always wanted so much is a day/night cycle in osrs. There is already an in game clock that keeps the time I think? So a cosmetic overlay that would follow this day night cycle, things that could change is brightness, lanterns/light sources that light up at night, fog/skybox changes depending on the time,... Stuff like that. If I knew anything about how to do it I would work on it but I can't. Is there any possibility of this happening? Would be amazing.

**Comment by dekvall** [comment]
Strong similarity to #7451
