### ISSUE TITLE
Enhancement towards the Skill Plugin display to show the next level on the right of the percentage bar.

### ISSUE THREAD

**Issue by TomMartow** [runelite/runelite#994]
Currently, the Skill Plugin bar looks like this:

![skill orig](https://user-images.githubusercontent.com/10462926/37554653-e163eade-29d3-11e8-9635-52f7da1d8412.png)

The current level is placed over the top of the icon which you can't see at all on the skills which have a mostly white palette.

I suggest removing the skill level on top of the skill icon and displaying the next level on the right of the progress bar, like so:

![skill new](https://user-images.githubusercontent.com/10462926/37554704-72c1c492-29d4-11e8-9233-7def33527071.png)

**Comment by jamesahhh** [comment]
#1174 Changed this here. It drastically reduces size of the bar and looks a little odd, open to suggestions on how to make this look nice. Maybe match the text color? 
![mar-28-2018 18-43-44](https://user-images.githubusercontent.com/21230572/38063836-9b0c7338-32b8-11e8-8a8e-3ff9bf32b7ed.gif)

**Comment by MESLewis** [comment]
Is it possible to show current level on the inside left of the progress bar and next level on the inside right of the bar? Or just current level on top of bar.

**Comment by jamesahhh** [comment]
I like the idea, here is how I implemented it https://github.com/runelite/runelite/pull/1174/commits/b94590dfcba294eb03321c031cad7cf6af364cfe
![mar-29-2018 00-13-38](https://user-images.githubusercontent.com/21230572/38073151-0d0ff6ca-32e7-11e8-9f76-74b140dc625a.gif)

**Comment by shmeeps** [comment]
Fixed with the Obsidian updated:

![image](https://user-images.githubusercontent.com/1050677/40558486-0fd90022-6019-11e8-97f8-2bebfb715b66.png)

This can probably be closed now.
