### ISSUE TITLE
Neitiznot faceguard GE value not shown in bank

### ISSUE THREAD

**Issue by RGood** [runelite/runelite#9943]
Presently, the Neitiznot faceguard's value is not calculated in bank value calculator.

**Comment by trelkins3** [comment]
@RGood - to clarify, should this just be the GE price of the Helm of Neitiznot + the GE price of the basilisk jaw?

**Comment by Nightfirecat** [comment]
Yes. The faceguard can be separated into the jaw and helm without losing either piece
