### ISSUE TITLE
Rather than remove the Demonic Gorilla plugin, modify it to only count attacks

### ISSUE THREAD

**Issue by Farwger** [runelite/runelite#9949]
As far as I know, the Demonic Gorilla plug-in is going to be removed because it goes against Jagex's newly released guideline on plugins, which forbids "Features which tell you what the next Demonic gorillas attack will be." However this does not forbid a plugin from simply counting their attacks without predicting their attack styles. So rather than removing the Demonic Gorilla plug-in entirely, why not remove the offending parts of the plug-in, and keep the overlay that counts their attacks? Unless I'm misunderstanding something here.

**Comment by Trevor159** [comment]
The post was made for people to interpret and use their brain. Reading it literally like that is exactly what it isn't meant for.

**Comment by Farwger** [comment]
I did use my brain, which is how I came up the idea I wrote. If it's a bad idea, so be it, but I thought it was worth a mention

**Comment by Adam-** [comment]
Technically the existing plugin doesn't "tell you what the next attack will be" either, since its not possible to predict it. I think this is just a case of go-by-what-they-mean-not-by-what-they-say.

**Comment by Farwger** [comment]
Fair enough
