### ISSUE TITLE
Remove MenuEntrySwapper plugin

### ISSUE THREAD

**Issue by whartd** [runelite/runelite#9952]
Jagex's recent statement on 3rd party clients states:

"We consider features which enable you to bypass gameplay mechanics to be unacceptable [...] The same can be said of features which might modify how you select actions in the game or change how you click on menus, players, or NPCs, especially where the feature leads to you using fewer clicks than you would when using our client."

Based on this statement the entire plugin is explicitly unacceptable. As such the plugin should be removed as soon as possible. 

I understand that the statement lists some of the more contentious uses in other clients, but acknowledges that it is not an exhaustive list, and notes that they are merely examples.

**Comment by SieBrum** [comment]
https://github.com/runelite/runelite/pull/9950/

**Comment by Nightfirecat** [comment]
Though I do not think it is likely that we will fully remove the plugin, it's possible we will remove specific swaps which go in line with the guidelines of their statement, or remove specific swaps after more discussion is had with Jagex leadership.

**Comment by abextm** [comment]
Jagex's [recent statement](https://secure.runescape.com/m=news/a=13/another-message-about-unofficial-clients?oldschool=1) provided clarification on this.
