### ISSUE TITLE
Suggestion: Stay on top feature for RuneLite?

### ISSUE THREAD

**Issue by Stiahn** [runelite/runelite#9956]
What do you think of an “always stay on top” feature for RuneLite? 
I was watching my friend stream on Discord, and the pop-up window of that stream had an option to make the window stay on top. Meaning that I could interact with other programs and the stream would not disappear behind them. 
I think this would be appreciated by a lot of people, especially when you only got one monitor.

**Comment by Alexsuperfly** [comment]
"runelite" settings has an `always on top` option

**Comment by dekvall** [comment]
This is already a feature https://github.com/runelite/runelite/wiki/RuneLite
