### ISSUE TITLE
MLM Ladder object marker glitch

### ISSUE THREAD

**Issue by ChiSox** [runelite/runelite#9959]
**Describe the bug**
A random invisible large object seems to be highlighted using the object marker plugin when both the upper and lower ladders are marked in MLM.

**To Reproduce**
1. Hold down shift and right click "mark object" on upper and lower ladder in MLM
2. Hop worlds or logout/in
3. You will see an extra invisible object marked that can't be removed
(Only way to get rid of it is to disable object marker plugin

**Expected behavior**
Only the actual lower and upper ladder used to highlight.

**Screenshots**
Screenshots 
![image](https://user-images.githubusercontent.com/44905890/66048411-17418f80-e4ef-11e9-9284-1ade2f4c2b72.png)
![image](https://user-images.githubusercontent.com/44905890/66048432-21fc2480-e4ef-11e9-88ed-143ea9e8d61f.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - RuneLite version: Current as of 10/2
 - Launcher version: Current as of 10/2

**Comment by Adam-** [comment]
fixed in d6772a3be4f228a6e686ac1e3f5036cdba69d2e6
