### ISSUE TITLE
Add incantivity logout timer together with logged in time to report button

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#996]
read the whole suggestion there is two suggestions in one issue

**1st suggestion**
![image](https://user-images.githubusercontent.com/37475765/37556034-437b81b4-29e8-11e8-8a73-ee4121d4dfb4.png)
This is the normal report player section looks for me but I want it so I can see my 5:00 minute inactivity logout time as well so like this.

![image](https://user-images.githubusercontent.com/37475765/37556052-71a27282-29e8-11e8-98d2-01d1b3da6390.png)
This is just a template on how I want it to look like.

![image](https://user-images.githubusercontent.com/37475765/37556077-9bbf39c4-29e8-11e8-8cf7-c69e1658ee3a.png)
And this is how I want it to look like at the end.

This will be useful instead of having idle notification we can have a timer on the report player section, I think this will bring more people to use this client cos no other clients have these two together, like me i don't like using idle notification i rather see a timer.

**2nd suggestion**

Or maybe a Better suggestion.

We can use colours such as yellow and green which means these;
Yellow - is under attack (which will be a 20 minutes count down)
Green - is not under attack (which will be a 5 minutes count down)

maybe another suggestion for this is maybe you can do it like this
time online [how long left to logout]
**01:33:08 [00:04:59]**
I have added this because maybe
![image](https://user-images.githubusercontent.com/37475765/89530124-dccb1200-d7e5-11ea-8a95-60ebf778f5e2.png)

having this might make the numbers be super small, so i decided to change this one to a better option where it will not be on top of each other but next to each other examples showing below.

This is a better and updated version:

this is the new updated version which you might consider to add is this
![image](https://user-images.githubusercontent.com/37475765/89530155-ec4a5b00-d7e5-11ea-8306-e7ab83eba3fc.png)
like I said before
Yellow - is under attack (which will be a 20 minutes count down)

![image](https://user-images.githubusercontent.com/37475765/89530181-f9ffe080-d7e5-11ea-89a2-7e1c501d90f2.png)

like I said before
Green - is not under attack (which will be a 5 minutes count down)

side note:
you might not even need the 6, 0s what I mean is this 00:00:00, you can just have 4 because if you are afking or not the max logout timer is 20minutes so you can just have it as 00:00 so example
**01:33:08 [04:59]** which this means that the player will log out in 4mins and 59 seconds and will go down to 00:00

**Comment by permedd** [comment]
hope this gets added though.

**Comment by permedd** [comment]
Or maybe it can be on one line something like this


Login timer [idle timer]
00:44:40 [4:58]

^ i think this will be so much cleaner and less crowded, if you don’t understand i can show screenshots if you want.

**Comment by permedd** [comment]
Better suggestion

maybe another suggestion for this is maybe you can do it like this
time online [how long left to logout]
**01:33:08 [00:04:59]**
I have added this because maybe 
![image](https://user-images.githubusercontent.com/37475765/61962265-0d685100-afc1-11e9-84e6-79a2d8941dc3.png) 
having might make the numbers be super small.




this is the new updated version which you might consider to add is this
![image](https://user-images.githubusercontent.com/37475765/61962820-5240b780-afc2-11e9-858a-3a3b3e63b075.png)
like I said before
Yellow - is under attack (which will be a 20 minutes count down)

![image](https://user-images.githubusercontent.com/37475765/61962862-671d4b00-afc2-11e9-9996-2d91f704dd77.png)
like I said before
Green - is not under attack (which will be a 5 minutes count down)


side note:
you might not even need the 6, 0s what I mean is this 00:00:00, you can just have 4 because if you are afking or not the max logout timer is 20minutes so you can just have it as 00:00 so example
**01:33:08 [:04:59]** which this means that the player will log out in 4mins and 59 seconds and will go down to 00:00

**Comment by whartd** [comment]
I like this, but I'm not sure any of the existing suggestions look as clean as I'd like. I don't know a better solution. Perhaps similar to the last one, without the extra `00:` , as there will never be hours until logout? Does anyone have alternative design ideas?

Additionally, I have noticed that I get notifications in NMZ when I shouldn't. I can't remember if they indicate that I'm about to log out, or that I'm out of combat. Does anyone have the same experience and remember this? This may affect how effective this would be if copy-pasting code from other plugins.

**Comment by permedd** [comment]
added another suggestion to this.

**Comment by Nightfirecat** [comment]
The [AFK Countdown hub plugin](https://runelite.net/plugin-hub/show/afk-countdown) looks like it achieves this handily.
