### ISSUE TITLE
AA Bug

### ISSUE THREAD

**Issue by Leohige** [runelite/runelite#9963]
I'm getting some weird stuff on the screen when using AA.

**Screenshots**
![image](https://user-images.githubusercontent.com/7697524/66085696-518b4b00-e548-11e9-8cf8-3b134bfbb603.png)

**Environment:**
 - OS: Windows 10
 - RuneLite version: 1.5.35
 - Launcher version: 2.0.2

**Comment by Nightfirecat** [comment]
This is a known (but probably unfixable) issue where some graphics drivers report support for AA above what they will actually support. Reduce your AA level--say, from 16x to 8x, or lower as needed--or disable it and you'll find that these artifacts will stop appearing.

**Comment by Alexsuperfly** [comment]
if you have an AMD graphics card, try rolling back the driver to whats detailed here https://github.com/runelite/runelite/wiki/GPU-FAQ#when-i-turn-on-anti-aliasing-weird-lines-appear

**Comment by Leohige** [comment]
> if you have an AMD graphics card, try rolling back the driver to whats detailed here https://github.com/runelite/runelite/wiki/GPU-FAQ#when-i-turn-on-anti-aliasing-weird-lines-appear

> This is a known (but probably unfixable) issue where some graphics drivers report support for AA above what they will actually support. Reduce your AA level--say, from 16x to 8x, or lower as needed--or disable it and you'll find that these artifacts will stop appearing.

Unfortunately these options dont work, only if I disable AA.

**Comment by Leohige** [comment]
I finally fixed the problem. But the FPS is always locked in 50, I tried to put in 60, but dont work.

![image](https://user-images.githubusercontent.com/7697524/66276936-ec986380-e86d-11e9-888d-3050f467d452.png)

I just used these settings for RuneLite in the AMD panel. (It's in Portuguese)

![image](https://user-images.githubusercontent.com/7697524/66276940-020d8d80-e86e-11e9-88d4-b79fccd9fece.png)

**Comment by Nightfirecat** [comment]
FPS is locked at 50 in the engine, not based on rendering speed, so that is expected.

**Comment by Leohige** [comment]
> FPS is locked at 50 in the engine, not based on rendering speed, so that is expected.

OK, so everything is fine, thank you!
