### ISSUE TITLE
Boss Hiscores idea suggestion

### ISSUE THREAD

**Issue by Andrewcapo** [runelite/runelite#9972]
I think a Hiscores feature that shows the top players for kill counts of each boss and a way to view boss kill counts in the existing hiscores plugin would be really awesome. Of course this feature would probably only be able to track RuneLite users, but would still be really cool IMO. 

Sorry if this has already been suggested, I tried searching for it and got no results.

**Comment by abextm** [comment]
Duplicate #5146
