### ISSUE TITLE
Bind anti-drag to other keys

### ISSUE THREAD

**Issue by justhereforsuggestion** [runelite/runelite#9974]
I love the anti-drag feature, as it helped me a lot since I suffer from tremors in my hand with any press I make. However, the anti-drag is exclusively tied to shift at the moment.

I don't know how to make my own anti-drag with AHK, so I was wondering if you guys knew or if you guys could allow us to change the hotkey for anti-drag in RL.

**Additional context**
This will be very helpful to people who suffer from tremors and make switching gear much less stressful and in line with those who do not suffer from this.

**Comment by dekvall** [comment]
This has been discussed extensively in #3200 and while i sympathize with your situation, this is currently not something we are looking to implement.

**Comment by justhereforsuggestion** [comment]
Aww, that's a shame. I see that it has been more than a year ago since the controversy but if that's still your stance, so be it.

**Comment by Kamielvf** [comment]
Closing, relevant discussion in #3200

**Comment by Castro3halo** [comment]
Given that it has been nearing on half a decade since this was initially suggested and a lot of jagex policy has changed on this over the years. Any chance this could be reviewed ?
