### ISSUE TITLE
Add Time To Level also Time to 99

### ISSUE THREAD

**Issue by permedd** [runelite/runelite#998]
underneath the xp orb it should say how long left till next level or underneath this 
![image](https://user-images.githubusercontent.com/37475765/37558690-ba558efc-2a0f-11e8-810b-c12dd1536e7e.png) (i dont know what this is called but yeah).
 also if you do set target level please please add a timer to show how long left till 99 or how long left till that certain level in hours etc

**Comment by deathbeam** [comment]
You can now set target level to 99 so I believe this is solved by that.

**Comment by Nightfirecat** [comment]
I don't think we have "Time to level" or "Time to target" at all. I agree there's no point in having "Time to 99" when the target level can just be set to 99.

**Comment by deathbeam** [comment]
We do, when you hover over the progress bar.
