### ISSUE TITLE
Mac: Stay On Top feature / SIMBL compatibility

### ISSUE THREAD

**Issue by remywandby** [runelite/runelite#9986]
Keeping the window always on top is super useful for AFKing while multitasking ect.

I think it would be an amazing feature if you could select an option for the RuneLite to "stay on top" so its always visible for AFK training and multitasking.

I believe windows have this option on their OS, however mac doesn't. We can achieve the a similar effect for some applications using SIMBL and a plugin called aFloat. However, it is not compatible with every application.

![Screen Shot 2019-10-05 at 3 57 17 pm](https://user-images.githubusercontent.com/51684734/66260782-f7c59380-e788-11e9-8b46-388e127645ce.png)

![Screen Shot 2019-10-05 at 3 57 54 pm](https://user-images.githubusercontent.com/51684734/66260787-001dce80-e789-11e9-937a-ac059ce578ce.png)

**Comment by Kamielvf** [comment]
Does the option `Enable client always on top` not work on your system? It is found under the RuneLite plugin settings.
![image](https://user-images.githubusercontent.com/35824069/66270524-185b1f80-e855-11e9-9df1-09f20629bf02.png)

I will be closing this issue, but if this feature does not work for you leave a reply and I will reopen it.

**Comment by remywandby** [comment]
Oh wow, sorry I didn't realise there were these settings. That's great
thank you.

Remy
