### ISSUE TITLE
Time-related plugins depend on the system clock

### ISSUE THREAD

**Issue by FrozenState** [runelite/runelite#999]
The report button plugin / idle notifier plugin currently make use of Instant objects to get and make use of the system clock for time based calculations.

If a user modifies their system clock, these time-based calculations will be thrown off and in some cases can cause exceptions to be thrown. Time-based calculations should use the current system up-time (System.nanoTime()) which cannot be easily modified.

![idea64_2037-03-17_13-27-14](https://user-images.githubusercontent.com/14159901/37558808-dee95e06-29e7-11e8-9efa-b800c998dc62.png)

**Comment by SoyChai** [comment]
This is a perfect issue, thanks for describing both the problem and its solution so clearly! I should have this fixed in a jiffy.

**Comment by xDemoN** [comment]
Close?
