### ISSUE TITLE
Client launches, however game does not appear

### ISSUE THREAD

**Issue by boozster** [runelite/runelite#9993]
client launches and cannot find my 'session file', therefore not showing my game on screen.

official OSRS client works, running runelite reguarly doesnt display the client at all & administrator mode opens it but does not display the game.

client.log = https://imgur.com/a/hh1v8xf
video of bug on both launch options = https://www.youtube.com/watch?v=Gtv6Rer28zA

tried reinstalling runelite, running all compatability modes & updating my drivers even though i dont believe thats the issue.. help would be appreciated.

environment:
 - OS: Windows 10
 - RuneLite version: 1.5.35
 - Launcher version: 2.0.2
 - OldSchool version: Rev 184

**Comment by Nightfirecat** [comment]
The "No session file exists" log entry is normal and is not the cause of this issue.

**Comment by boozster** [comment]
Any other information I could get for you? Im clueless to why my runelite client is broken and really want to fix it.

**Comment by djjotheman** [comment]
I'm having the same issue I launch the client and its loads the client but black screens the game

**Comment by FatherLewy** [comment]
I'm also having the same issue! Would love any help at all

**Comment by Alexsuperfly** [comment]
can yall try this https://github.com/runelite/runelite/wiki/GPU-FAQ#client-is-freezing-after-enabling-gpu-plugin

**Comment by boozster** [comment]
shameless bump, really looking for more info on this.

**Comment by djjotheman** [comment]
[launcher.log](https://github.com/runelite/runelite/files/3727576/launcher.log)
heres my launcher log still have the same issue

**Comment by boozster** [comment]
bump

**Comment by boozster** [comment]
1.5.37 released, still have the same issue

**Comment by Alexsuperfly** [comment]
I'm still pretty sure its the GPU plugin doing it since i've helped more than a dozen people with this same thing in discord.
If you cant turn it off while loading you'll need to manually disable it in the settings file located in the `.runelite` directory.

**Comment by to-forgive** [comment]
> I'm still pretty sure its the GPU plugin doing it since i've helped more than a dozen people with this same thing in discord.
> If you cant turn it off while loading you'll need to manually disable it in the settings file located in the `.runelite` directory.

Can you please explain your fix further, hoping it will fix for me. I have the file open im just not sure on what to change

**Comment by Alexsuperfly** [comment]
discord really is the better place to help with things such as this

**Comment by boozster** [comment]
> I'm still pretty sure its the GPU plugin doing it since i've helped more than a dozen people with this same thing in discord.
> If you cant turn it off while loading you'll need to manually disable it in the settings file located in the `.runelite` directory.

Disabling the GPU plugin manually through the .runelite directory worked for me and it seems like many others.
Thanks alot!

**Comment by Joblivion** [comment]
> I'm still pretty sure its the GPU plugin doing it since i've helped more than a dozen people with this same thing in discord.
> If you cant turn it off while loading you'll need to manually disable it in the settings file located in the `.runelite` directory.

I have the same problem, I tried to turn off the GPU processes you mentioned, but there wasn't any process like that going on.
Can you please explain this manual method? I couldn't find this settings file.
